### ISSUE TITLE
Text Length

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1060]
Nikse should we include `\r\n` when counting line length? /cc @niksedk 

P.S: https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Controls/SubtitleListView.cs#L579

**Comment by aaaxx** [comment]
I don't really see good reason for that; it would just make things counter-intuitive (e.g. having to set max. length to desired + 1 when working to a specific length requirement).
