### ISSUE TITLE
Feature Request: Fine tune supervision for Multi Replace batch processing

### ISSUE THREAD

**Issue by yportier** [SubtitleEdit/subtitleedit#1069]
It would be nice to be able to process a **batch of subtitles** within the Multi Replace tool.  
I'd like also to be able to mark which replacements need **supervision** and be able to toggle between **All** and **Need Supervision** in the _Lines found_ section so it's easier to catch the false positives.
We could also have a **Apply and load next file** and eventually an **Apply to all** to either to skim through the **batch** or process all in one go.

**Comment by niksedk** [comment]
Via "Tools" -> "Batch convert" you can use "Multiple replace" on several files.

**Comment by yportier** [comment]
Great thanks, my bad for not checking this one...

However, I'd like to hold on to the second part of my request, i.e. the ability to enable supervision for some selected replacements (some need context that are not easily resolved by RegEx)
