### ISSUE TITLE
Google translate - 503 service unavailable 

### ISSUE THREAD

**Issue by Sopor-** [SubtitleEdit/subtitleedit#1075]
When i try to use Google translate i only get error 503 service unavailable. I'm running Subtitle Edit 3.4.7 but it was the same in 3.4.6. Is this a temporary issue or have Google made any changes that make this fail?

**Comment by niksedk** [comment]
You can also test a beta here: http://www.nikse.dk/SubtitleEdit.zip (no installer)

**Comment by Sopor-** [comment]
Working perfect, thanks!

**Comment by ukdtom** [comment]
Confirmed here as well.....

Takker meget ;-)
