### ISSUE TITLE
Ability to choose specific audio channel/track for Wave generation.

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#11]
I know this will make little sense to most users, but currently I do meet such need when working on a project. The video clip got both Left/Right channels. However, the wave seems messed up, because the L channel is full of noise and no voice.

AFAIK, on some video files, one of the
stereo channels (typically left) is used to encode LTC time code. So, here I think the R channel would be the ideal one for wave generation, instead of the mix or stereo channels. 

So I just wonder if it would be possible for users to decide which channel to use, L, R, or stereo. FYI. Thank you!

**Comment by niksedk** [comment]
I think this is working now
