### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by InCogNiTo124** [SubtitleEdit/subtitleedit#1109]
I would like to propose a feature where a simple sound would be played when chat message has been recieved during network translation. Thank you.

**Comment by niksedk** [comment]
He, like this? beta: http://www.nikse.dk/SubtitleEdit.zip
( go to options -> Settngs -> Network: set audio file to perhaps this wav file: https://docs.google.com/file/d/0B14BXHai2DrEU3lYUnp6cXBOcFE/edit )

**Comment by niksedk** [comment]
@InCogNiTo124: Could you verify that it works?

**Comment by InCogNiTo124** [comment]
It works. Thank you.

**Comment by niksedk** [comment]
np, thx for testing :)
