### ISSUE TITLE
Audio extraction via VLC - choosing audio track does not work

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#1119]
This does not work with VLC 2.2.x...

https://forum.videolan.org/viewtopic.php?f=2&t=127773

Any other way to do this or should we disable this feature from VLC wave extraction?

**Comment by LeonCheung** [comment]
The new optional track selecion option seems really nice, I just wonder if it is also possible to spit extraction L / R channel only in a single track, which was mentioned at #11.  :)

**Comment by niksedk** [comment]
Works in latest VLC again
