### ISSUE TITLE
Selecting Options from menu then settings gives an error, SubtitleEdit 3.4.8 Build 1

### ISSUE THREAD

**Issue by baselsaliba** [SubtitleEdit/subtitleedit#1147]
![options then settings in menu gives error message](https://cloud.githubusercontent.com/assets/13798487/9275755/287633d4-42a8-11e5-9951-7374db4c7746.png)

**Comment by xylographe** [comment]
What is the absolute path of the VLC executable?

**Comment by baselsaliba** [comment]
Hi.

This is the path I have:

"C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"

 

Basel Saliba

Email:                    <mailto:baselsaliba@gmail.com> baselsaliba@gmail.com

Mobile                  +962 79 500 0124

Skype                    basel.saliba

**Comment by niksedk** [comment]
@baselsaliba: could you test latest beta: http://www.nikse.dk/SubtitleEdit.zip (no installer - or compile from latest github source)?

**Comment by baselsaliba** [comment]
Hi,

The problem I reported no longer appears.

Thanks,

 

Basel Saliba

**Comment by niksedk** [comment]
Fixed by xylographe :)

**Comment by xylographe** [comment]
just for the record: commit bf4c9cbf845999a405e88e33f20d52d6c3108a5b :wink:
