### ISSUE TITLE
Cannot customize shortcut for some items

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#1153]
For example, I failed to set shortcut for "Save" from **Ctrl N** to **Q**. It also it report some error message (see below). However, it does work in 3.4.6.

![se](https://cloud.githubusercontent.com/assets/494788/9293722/41028012-4468-11e5-8f57-e7b076b26fb5.jpg)

**Comment by niksedk** [comment]
It's possible... for short cuts with menu items at least (you cannot even set a menu item to a single letter in Visual Studio)

**Comment by niksedk** [comment]
It works for shortcuts with no UI menu items, so I guess a validation for shortcuts with menu items is missing

**Comment by LeonCheung** [comment]
Hmm, strangely that it works before 3.4.7

**Comment by niksedk** [comment]
It does not... at least on my computer.

**Comment by LeonCheung** [comment]
I swear it did work!! Because I use it for quite long time. But I don't know why it didn't work anymore since last night.... That is the most strange I've ever met.... Anyway, luckily I can set it to **Save All**.  So let it be. :)
