### ISSUE TITLE
Feature request: Move text only

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#1154]
Highly appreciated if we can support text swapping between two selected lines, because sometimes we want to reorder text between lines. Currently it seems we have to sort of "copy > jump > paste > copy another > jump again > paste another", or delete the current line and insert a new one, any retype. That's really quite a lot clicks! :sweat: 

Thank you!

**Comment by niksedk** [comment]
cool idea :)

**Comment by LeonCheung** [comment]
Now I think it could be better achieved by a simple funtion that allows moving text of selected subtitle(s) up/down. (Note: Move text only, and without any changes on any timecodes) Maybe it would be okay to add two new shortcuts for such a convenient operation?

**Comment by LeonCheung** [comment]
A picture is worth a thousand words:
![demo1](https://user-images.githubusercontent.com/494788/35190809-c4424d16-fe62-11e7-85af-e46074b4237e.gif)

If possible like below, then it really rocks!
![demo2](https://user-images.githubusercontent.com/494788/35190810-c6faae72-fe62-11e7-9df0-b43c6c077f28.gif)

**Comment by niksedk** [comment]
Move text feature included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/35685228-66036004-0769-11e8-96f0-dd172ebe0468.png)

How does that work?

**Comment by LeonCheung** [comment]
O-M-G~ Just tested (with Shift Ctrl Up/Down as shotcuts), it works even more powerful than I imagined. Thank you so much!
Just one thing to discuss if you don't mind:

When making discontinuous selection, maybe it should make a bit more sense by making the selected lines continous as well by this operation? Or shouldn't?

**Comment by LeonCheung** [comment]
Maybe just leave it as it is now. Anyway, it's cool enough already. :)

**Comment by niksedk** [comment]
OK, we'll leave it as is. It would also be a bit strange to change selection automatically.
