### ISSUE TITLE
New feature: Count find

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1174]
@niksedk  What do you thing?

![Find Dialogue](http://i.imgur.com/VPohleF.png)

**Comment by nikse** [comment]
ahhhhhhhhhhhhhhhhhhh you all need to stop @'ing me! for crying out loud

**Comment by ivandrofly** [comment]
Ups :confused: SORRY

**Comment by aaaxx** [comment]
Yeah, this would be great. Maybe also in Replace window.

**Comment by ivandrofly** [comment]
yeah it's :smile: @aaaxx

**Comment by ivandrofly** [comment]
https://www.dropbox.com/s/erakwi0m2dk529a/SubtitleEdit.exe?dl=0

**Comment by niksedk** [comment]
Looks good :)
