### ISSUE TITLE
Drop multiple subtitle files in main should open join dialog

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1176]
Allow loading split subtitles directly to main listview

**Comment by niksedk** [comment]
Could you explain a bit more?

**Comment by LeonCheung** [comment]
I assume he means a faster way than using right-click menu **"Insert subtitle after this line"** for each split subtitle one by one?

**Comment by ivandrofly** [comment]
:+1: @LeonCheung, @niksedk Same thing as `Join subtitle...` doesn't, instead of having it in a separated form we could have use `Join subtitle` is class as helper

**Comment by niksedk** [comment]
Hm, I still don't get it... ;)

**Comment by LeonCheung** [comment]
Someting like this?
![insert_after](https://cloud.githubusercontent.com/assets/494788/9427530/4672340a-49b5-11e5-8ff5-41f08562f0fb.jpg)

**Comment by ivandrofly** [comment]
o.O, @LeonCheung, not dropping to `Join subtitle` form but to `Main` FORM instead

**Comment by LeonCheung** [comment]
I know what you mean. I'm not sure how possible to define the mouse cursor position as where to insert a sub file, but it sounds cool. 

I know there are softwares that support drag-to-append other than drag-to-open by holding down some combo key, e.g. by dragging while holding **Shift** or something.
