### ISSUE TITLE
Xml Content Translator

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1184]
@niksedk Isn't better setup new repository for http://www.nikse.dk/XmlContentTranslator here in GitHub?

I have been working in a patch so...

**Comment by niksedk** [comment]
Yeah, you're right - source code history too :)

**Comment by ivandrofly** [comment]
;)

**Comment by niksedk** [comment]
https://github.com/SubtitleEdit/XmlContentTranslator
