### ISSUE TITLE
"Fix alone lowercase 'i' to 'I'" in "Fix common errors" for all languages

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1185]
Considering there are some language-specific options in "Fix common errors", like "Fix Danish letter 'i'" and "Fix Spanish inverted question and exclamation marks", how come that "Fix alone lowercase 'i' to 'I' (English)" is present for all languages when even its name says it's only used in English and there's also a pop-up window notifying you it's ticked when you click "Next >" if the subtitle language isn't English?

Shouldn't it be removed from the list of options for all other languages?

**Comment by ivandrofly** [comment]
:+1: @niksedk  I think we should consider this it's quite annoying actually

**Comment by ivandrofly** [comment]
[DOWNLOAD TEXT](https://www.dropbox.com/s/ozhh7r8urcwu6ap/SubtitleEdit.exe?dl=0)

**Comment by aaaxx** [comment]
It's still the same. You sure you uploaded the right .exe?

**Comment by ivandrofly** [comment]
ah, wrong `.exe` I switch branch & build ;) just a sec

**Comment by ivandrofly** [comment]
@aaaxx link should be fixed now ;)

**Comment by aaaxx** [comment]
It's still there for all languages but there's no pop-up warning when it's ticked.

**Comment by ivandrofly** [comment]
Are you running portable or Installed version? Try downloading portable version extract it remove `SubtitleEdit.exe`, copy the file you downloaded from dropbox inside the portable folder and execute

**Comment by aaaxx** [comment]
Sorry, I wasn't looking closely enough and mistook it for "Fix uppercase 'i' inside lowercase words (OCR error)".

Seems to work OK. Appears only for "en".

**Comment by ivandrofly** [comment]
:wink:

**Comment by aaaxx** [comment]
Commit merged. Closing issue.
