### ISSUE TITLE
Move SE logic to DLL

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#1192]
I would like to move the logic to a dll - it's a huge task to make it 100% free of Windows.Forms/Word/UI/WindowsStuff but it will give some nice advantages:
- Better separation of logic and UI stuff
- The possibility to use the dll from other apps (reverse plugin;)
- The possibility to make real cmd line version 
- The possibility to make better Linux/Mac support

Perhaps it can be made in steps.

What do you say? @ivandrofly @xylographe  ?
(the dll can still be linked into SubtitleEdit.exe)

Any good ideas?

**Comment by xylographe** [comment]
Perhaps, on a separate branch? You would still have a stable **master** for releases.

The Logic part in master could remain frozen (except for real bug fixes) until you are ready to merge.

**Comment by ivandrofly** [comment]
Nice improvement, btw I also agree with @xylographe you may want to do it in separated branch to avoid critical

**Comment by niksedk** [comment]
Initial version 99%... But I have no wifi (only phone) and my computer don't have wireless 😢

**Comment by niksedk** [comment]
Internet again :)

Initial version committed... note that linking (including of dll files inside SubtitleEdit.exe) now only happens in the build.bat file (makes running from VS faster)

@ivandrofly: I saw that the installer script is failing... any ideas?

**Comment by ivandrofly** [comment]
Failing in `master` or....?

**Comment by ivandrofly** [comment]
Hmm... let me :eyes: , Trying to fix `build.bat` for Visual Studio 2014

**Comment by niksedk** [comment]
I just tested libse on Xamarin on windows and it works :)
Can anyone run Xamarin on Linux or OSX? Perhaps @ivandrofly or @xylographe  ?

**Comment by Betsy25** [comment]
When compiling the latest commit a0da9d1cabf105955ba3cff71ff63664b7d2fc79, VS Express 2013 errors out.
> CSC : error CS0006: Metadata file 'C:\Users\Vita\Source\Repos\subtitleedit\libse\bin\Debug\libse.dll' could not be found

**Comment by niksedk** [comment]
@Betsy25: Could you try again? libse.dll was missing the "allow unsafe" (allow pointers) check, so that might be the problem...

**Comment by Betsy25** [comment]
@niksedk Works fine now ! :+1:

**Comment by niksedk** [comment]
Cool :)

**Comment by xylographe** [comment]
> I would like to move the logic to a dll

Well… that went very fast, and amazingly smooth!
Congrats, Nikolaj. :)

**Comment by niksedk** [comment]
Yes, that was nice.
Some more code should definitively be moved out as well - especially from Fix common errors and main.cs (sorry about the insane size of main!). Some small examples of how to load/save a sub with libse should be added etc... and comments are more important in libse now too.

I'm considering to keep libse.dll outside SubtitleEdit.exe - that would make it usable from the plug-ins, right?

I guess Xamarin is the platform to support for libse, but I'm not too familiar with their roadmap (are they dropping their old mono framework for a new smaller one with less namespaces?)
