### ISSUE TITLE
[BUG] text center aligned problem with <b><i> tags

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#1194]
Hi...

On SE 3.4.8 the text is not center aligned with bold+italic tags when export to Blu-ray sup and idx/sub

example:
![capturar](https://cloud.githubusercontent.com/assets/7856897/9482148/ea5e908e-4b88-11e5-9f19-226bd3e4b8ba.PNG)

**Comment by aaaxx** [comment]
I did some testing and it seems to happen only when the tags are at the beginning of first line and end of last line. When each line is enclosed in tags it centres properly. Still, that *is* a bug.

And another bug that popped out. It seems that the text won't be rendered in bold, just italic, if the order of the tags is `<b><i>...</i></b>` (as you can see in the screenshot above) but will if it's `<i><b>...</b></i>`.

**Comment by marb99** [comment]
@aaaxx, I confirm your test in rendered bug.

And thanks for the font suggestion, I will try Segoe UI, thanks :)

This is an old bug, I hope going to be fixed soon.

**Comment by niksedk** [comment]
Thx for the info :)
Had not seen these cases... hopefully fixed now.
