### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1201]
Subtitle Edit is displaying `LibSE.dll` instead `SubtitleEdit.exe`

**Comment by ivandrofly** [comment]
I moved: 
`` c#
public static string AssemblyVersion
        {
            get
            {
                return Assembly.GetExecutingAssembly().GetName().Version.ToString();
            }
        }

        public static string AssemblyDescription
        {
            get
            {
                var assy = Assembly.GetExecutingAssembly();
                var assyName = assy.GetName().Name;
                bool isdef = Attribute.IsDefined(assy, typeof(AssemblyDescriptionAttribute));
                if (isdef)
                {
                    Console.WriteLine(assyName);
                    var adAttr = (AssemblyDescriptionAttribute)Attribute.GetCustomAttribute(assy, typeof(AssemblyDescriptionAttribute));
                    if (adAttr != null)
                        return adAttr.Description;
                }
                return null;
            }
        }
```

To `UiUtil.cs` any better idea?

**Comment by xylographe** [comment]
I think, you want `System.Reflection.Assembly.GetEntryAssembly()`.

**Comment by ivandrofly** [comment]
That is right, but we may want the SeLib.dll ver info aswell

**Comment by niksedk** [comment]
I think that libse.dll should follow the SubtitleEdit.exe version number...
@xylographe: thx for the hint - now used.
I've tried to make this easier here: https://github.com/SubtitleEdit/subtitleedit/commit/6e438005b05747f2656209318c7f4fa0c77ad323 (now you only have to change the version number if SubtitleEdit Property-Application window)

**Comment by niksedk** [comment]
Well, it actually just uses the Github release tag now :)

**Comment by ivandrofly** [comment]
Nice :+1:
