### ISSUE TITLE
Unhandled exception when using Multiple Replace

### ISSUE THREAD

**Issue by SirEllert** [SubtitleEdit/subtitleedit#1211]
Hi, i get this error after trying to use multiple replace after upgrading to version 3.4.8 - is there a possible fix for this? 

![subtitleeditprob](https://cloud.githubusercontent.com/assets/14052609/9576205/0dbe2f70-4fd6-11e5-80e4-df617d69689b.jpg)

**Comment by ivandrofly** [comment]
Hmm... let see you replace list

**Comment by xylographe** [comment]
Apparently, there is a literal `\u001F` (SYMBOL FOR UNIT SEPARATOR) in one or more *Find what* or *Replace with* strings. And, apparently, the .Net XmlWriter refuses to convert it to an XML entity.

If it is in a *Find what* string, you could replace it with **\u001F** (the regex engine will replace that sequence with the literal character), but in a *Replace with* (a replacement pattern) that doesn't work.

Of course, if the unit separator was entered unintentionally, you only have to remove it. :smile:

**Comment by xylographe** [comment]
Just found out that entity `&#31;` (XML encoded unit separator) is only valid in XML 1.1, not in XML 1.0.

**Comment by SirEllert** [comment]
I've attached pictures of the multiple replace list. 

![subtitle1](https://cloud.githubusercontent.com/assets/14052609/9580534/6be8a85e-4ffa-11e5-988c-7ed68d17df84.jpg)
![subtitle2](https://cloud.githubusercontent.com/assets/14052609/9580535/6c0e9820-4ffa-11e5-990a-971c872a9dae.jpg)

I'm not really into the "programming" myself, so I appreciate your comments @xylographe, but seems to be out of my knowledge :) I guess it's something that has to be fixed for the next update, or?

**Comment by xylographe** [comment]
Unfortunately, the unit separator is an invisible control character.

Clearly, you entered it by accident (I don't know how—to reproduce, I had to use clipboard pasting).
To get rid of it, select every item in turn, select the *Find what* text input, use the cursor left/right key to move the text cursor from end to beginning (or from beginning to end), do the same with the *Replace with* text input. If you press the cursor key, and the text cursor does not move, then you found an invisible control character; press Delete to remove it.

There are two ways to "fix":
- prohibit the use of invisible control characters (at least those that are prohibited by XML 1.0)
- make invisible characters visible, and transform the strings when saving/loading Settings.

**Comment by xylographe** [comment]
@ivandrofly To reproduce:
```powershell
PS> add-type -AssemblyName System.Windows.Forms
PS> [System.Windows.Forms.Clipboard]::SetText("a$([char]0x1f)b")
```
Paste text from clipboard in SE (the unit separator is between **a** and **b**).

**Comment by niksedk** [comment]
I gues would could do either:
1) Some cleaner method for ascii codes from 0-31 
2) Some validation for ascii codes from 0-31 

C# even have a "Char.IsControl" function.

**Comment by niksedk** [comment]
I just got a bad xml subtitle and this control character fix also fixes this bad subtitle :)
White spaces should probably not be removed though from raw xml files though.

Any better ideas?

**Comment by xylographe** [comment]
IMO, this will do just fine.
I can't see a good reason, why someone would want control chars in a find&replace rule.

**Comment by xylographe** [comment]
To clarify: intentional use of CC is still possible with RE pattern, e.g., `find="\u009"`, `replace=" "`.
Safe, because no literal CC involved
