### ISSUE TITLE
[UI] File menu strip

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1225]
Hey @niksedk I think we should move all the **Import subtitle** option in **File** menu strip into **Import** context menu just like **Export**

what do you think?

![menu](https://i.imgur.com/8wZ5sq4.png)

**Comment by niksedk** [comment]
Yes, good idea :)

**Comment by OmrSi** [comment]
@niksedk Closed?

**Comment by OmrSi** [comment]
@niksedk Closed?

**Comment by OmrSi** [comment]
@ivandrofly @niksedk Closed?

**Comment by OmrSi** [comment]
@ivandrofly @niksedk Should be closed.
