### ISSUE TITLE
Main.cs 

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1243]
What is the point of running **ShowSubtitleTimerTick** in a infinite loop? :confused: 

``` C#
private void ShowSubtitleTimerTick(object sender, EventArgs e)
{
          ShowSubtitleTimer.Stop();
             ..........
             .............
          ShowSubtitleTimer.Start();
}
```

**Comment by niksedk** [comment]
To show subtitles...

**Comment by jdpurcell** [comment]
As for stopping/restarting the timer, it's simply a way to make the timer's interval account for the work being done in the tick event. For example, without stop/start, a timer with a 1000 msec interval and a Thread.Sleep(500) in the tick event would fire every 1000 msec. By using stop/start, the tick event would fire every 1500 msec.
