### ISSUE TITLE
[Enhancement] Adding an additional more accurate OCR

### ISSUE THREAD

**Issue by Elheym** [SubtitleEdit/subtitleedit#1259]
Hello. 
I would like to see this tool in the future. As the current Tesseract and VobSub with this, to put it mildly, do not. It is about SubExtractor, which, though in manual mode, where more precise than those two. Of course, with its further consideration as an automatic OCR. :) http://subextractor.codeplex.com/SourceControl/latest

**Comment by niksedk** [comment]
An OCR engine is pretty complex - and I don't believe just image compare is enough.
I've started on something but don't really have the time atm... if you edit settings.xml and set "ShowBetaStuff" to true you will get a new OCR method.

**Comment by Elheym** [comment]
But what is it different from the current method, why it is not available by default? Do it so moist?
Yes, you are right in saying that comparisons of images is not enough. Absolutely each program has its own peculiar advantages and disadvantages. Unfortunately, Tesseract OCR has only one advantage - automatic recognition. And that is questionable. When you compare the original text with the recognized in the tesseract, you find so many inaccuracies, many will not find in any any similar program. For example: ABBYY FineReader, SupRip, OCR via image compare and SubExtractor - give an order of magnitude fewer bugs. And that means less time for correction. Of all tested, the latter is the most accurate. You can believe me.
If it be possible to add it at least in a compiled form?

**Comment by niksedk** [comment]
Sorry, it's not possible just to add it in compiled form.

I've just given the "new image compare" (also does line compare if no image compare match is found) a quick update... http://www.nikse.dk/SubtitleEditOcr.zip
Hint:To fix bad results right click in the list view and choose "Inspect compare matches for current image"
How does it work?

**Comment by Elheym** [comment]
Looks interesting. Tried the "New" way, always quick to recognize the errors still appear. Differences from VobSub noticeable. Later I will be more understanding. They're still going to develop? )

**Comment by Elheym** [comment]
nOCR - works wonderfully. About recognition of English... copes. Please change the "No of pixels is space" to the value of 13, it is most suitable to him there are fewer errors and inaccuracies with spaces. Also, please enable "Draw missing texts".
Recognition on the Russian... with him for a little more complicated. Invalid recognizes (vertically) the letter "Й", in any case. The top character sees, the rest - no. 
![default](https://cloud.githubusercontent.com/assets/14152676/10084797/12148470-630e-11e5-9879-df9aa1167db6.png)
Similar situation is with "Ы", sees it as "Ь" + some symbol, but they are two different letters. A typical hereditary trait from VobSub. Also, the letter "Н" confusing uppercase and lowercase. ![2](https://cloud.githubusercontent.com/assets/14152676/10085639/f0737600-6312-11e5-813c-b01d181d1e79.png)
There would be a useful program "charmap.ехе" folder located in the System 32, made in the shape of the window. =)
Regarding the NEW method... a lot of mistakes, inaccuracies, confusion of letters and italics. More than 40% of the text.
P.S. Really liked - nOCR - good perspective for further development of the SE. Thanks a lot for him. ;)

**Comment by niksedk** [comment]
Thx for testing :)

The "Й" issue I will try to look at soon.
The "H" vs "h" issue could a bug too.

About the "NEW" method - you can improve the quality by right clicking on a line a press '"Inspect compare matches for current image"... that should probably be a button. The "NEW" method actually fallbacks to nOCR if no "image compare match" is found.

Could you email me the subtitle from above (so I can test it a bit)?

**Comment by Elheym** [comment]
Excuse me, I did not say... It was not about The "H" vs "h", and of The "Н" vs "н". It's not Latin, it is Cyrillic.
If the new method is used at 40% of inaccuracies, "Inspect compare matches for current image", I think it will still be a very long time. Therefore, this method can not be seen yet.
What do you say about the "Ы" vs "ы"? This letter is also not uncommon in the text, respectively, and is no less inaccuracies.
Previously sent you email from two different addresses... But never got no response on one mailbox. Therefore, they provide you the original files by means of cloud. :) https://cloud.mail.ru/public/MHp9/YXoqwD7EM

**Comment by Elheym** [comment]
Maybe I can still with something to help? Appositely, the correction recognition letters "Й / й" can help the program code of the original VobSub. =)

**Comment by agabrielluz** [comment]
I guess allowing us to export all subtitles in a way so that Abby Finereader can read and OCRit would help. VideoSubFinder (http://sourceforge.net/projects/videosubfinder/) allows users to export subs BUT not VobSub or Sup files. In order to export bitmaps, you must have a hardcoded subtitled video. So it would be great if SubtitleEdit could actually let us save all the subtitles as PNG or something like that so that we can open them (using Batch method in Finereader) and then, with the TXT generated files, SubtitleEdit then grabs those TXT files and creates SRT files with them (that's how VideoSubFinder does, but it lacks VobSub support, only hardcoded subtitles with video as input available)

**Comment by niksedk** [comment]
Have you tried right clicking in ocr window -> export... ?

**Comment by agabrielluz** [comment]
Yep. The problem is not exporting. The problem is reimporting. Because I can use Finereader to OCR the subs. But I need SubtitleEdit to actually read the OCRed subs and create a SRT file.
So the process is something along these lines:
1) SubtitleEdit first exports VobSub to bmp/png files
2) FineReader reads the BMP files
3) FineReader create TXT from BMP files
4) SubtitleEdit reads those TXT and generates SRT files
5) Finished!
That's what VideoSubFinder does. Except it doesn't take VobSub or image subtitles as input. It actually takes only video files as input and it extracts hardcoded subtitles from them.

**Comment by niksedk** [comment]
OK, and File -> "Import plain text" does not work?

**Comment by agabrielluz** [comment]
It does, but not with the timecode.

**Comment by niksedk** [comment]
Is the time code a part of the file name? If yes, how does it look and is it always the same?

**Comment by agabrielluz** [comment]
I'll have to look at it. I'll do it and then I'll tell you in a few hours.

**Comment by PannenkoekenNL** [comment]
Yes, the time code is a part of the file name. It looks like this:
0_01_48_280__0_01_49_879_01.jpeg
0_20_58_960__0_21_01_119_01.jpeg
