### ISSUE TITLE
Fix common errors - deselect ignored

### ISSUE THREAD

**Issue by Reeshar** [SubtitleEdit/subtitleedit#1275]
In SubtitleEdit 3.4.8, if you use "Fix common errors..." and deselect certain proposed changes in the list, those changes are often now still being applied. This was not the case in an earlier version.

**Comment by niksedk** [comment]
Hi Reeshar, could you test latest version in Github - or this beta: http://www.nikse.dk/SubtitleEdit.zip

**Comment by Reeshar** [comment]
Yup, that seems to have fixed it. 

Thanks Nikolaj! 

Richard

**Comment by niksedk** [comment]
cool, thx for verifying :)
