### ISSUE TITLE
Problem with spaces when exporting to FAB Image script

### ISSUE THREAD

**Issue by felagund** [SubtitleEdit/subtitleedit#1279]
Using version 3.4.8 (using mono under Linux - not sure if that has any effects), and this file:

```
[Script Info]
; This script was created by subtitleeditor (trunk)
; http://home.gna.org/subtitleeditor/
PlayResX: 1920
PlayResY: 1080
ScriptType: V4.00+
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,57,&H0000FFFF,&H0000FFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,50,50,50,0
Style: Nahore,Arial,57,&H0000FFFF,&H0000FFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,8,50,50,50,0
Style: Modry,Arial,57,&H00CF9F72,&H0000FFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,50,50,50,0
Style: Right,Arial,57,&H0000FFFF,&H0000FFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,6,50,50,50,0
[Events]
Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:01.20,Default,,0,0,0,,Down.
Dialogue: 0,0:00:01.32,0:00:02.52,Nahore,,0,0,0,,Up.
Dialogue: 0,0:00:02.64,0:00:03.84,Modry,,0,0,0,,Blue.
Dialogue: 0,0:00:03.86,0:00:05.86,Right,,0,0,0,,Right space.
```

when exporting to FAB Image Script, the fourth title gets renderes as this:
![image004](https://cloud.githubusercontent.com/assets/1218098/9877056/d1c362ba-5bba-11e5-8bf5-3e05c63d118d.png)
- it missing "e." at its end. when I remove the blank between "Right" and "space.", it gets displayed correctly.

**Comment by niksedk** [comment]
What's your video size?

**Comment by felagund** [comment]
I was doing the conversion without a video loaded, is that a problem?

**Comment by felagund** [comment]
Otherwise, the ass file says the video is fulllhd.

**Comment by niksedk** [comment]
No, should not be a problem... but the images are correct here...!? 
Perhaps you could try latest beta: http://www.nikse.dk/SubtitleEdit.zip
(also, you should probably set border width to 2 or 3)

**Comment by felagund** [comment]
you mean it works on your machine?

I tried with the latest beta and it is the same. However, I found out that the problem disappears when I check "simple rendering". It might have something to do with mono and Linux?

Also, I have to change the border via ASS styles, I cannot use the option in the "export FAB image" dialog. Is that expected?

**Comment by felagund** [comment]
Also, when using position right/center (as indicated by number 6), I get this rendering - it seems that left and right positions are all broken.
![image004](https://cloud.githubusercontent.com/assets/1218098/9909477/b5945ce6-5c98-11e5-999f-aa69602a8774.png)

**Comment by felagund** [comment]
(It should be right and in the middle.)

**Comment by felagund** [comment]
(also, ASS {\pos(<x>,<y>} is not supported?)

**Comment by niksedk** [comment]
The "Space." is not missing "e." on windows... 
The vertical center bug is present here too - should be fixed now though :)
Could you test latest beta: http://www.nikse.dk/SubtitleEdit.zip

When using ASS/SSA border settings must be set in ASS/SSA style.
{\pos...} is not supported.

**Comment by felagund** [comment]
Yes, it works now. I guess you can close this one now, I will reopen it if I manage to reproduce the space issue on Windows.

BTW: the dialog to export the images to FAB format does not seem to remember the settings that I use. I have no idea if it is hard to implement, but I found myself always checking "simple rendering" as it produced better looking pictures, it would be fabulous if it just remembered the setting I used last.
