### ISSUE TITLE
OCR correction issue adding space

### ISSUE THREAD

**Issue by Rudde** [SubtitleEdit/subtitleedit#1282]
Hello!

Love this software! Best I've ever tried. When I rip subs to srt it is suppose to automatically correct 

-Word to - Word and it does that on the first line, but if it's more then one line and it does the line jump it does not correct it on second line. Any way to make this work?

**Comment by niksedk** [comment]
Could you give a few examples?

**Comment by Rudde** [comment]
Hey, didn't come back to this since it wasn't that important and I didn't have any English subs to OCR at the time. But here is an example. 

![Example](http://i.imgur.com/1q2wUip.png)

http://i.imgur.com/1q2wUip.png

As you can see it will change "-Morning." to "- Morning.", but not "-Good morning." to "- Good morning." because it is not on the first line.

**Comment by niksedk** [comment]
Thx for the example :)
Should be fixed with https://github.com/SubtitleEdit/subtitleedit/commit/728f0d07960052531a5907ab6a0bfdf9d7cdc330
