### ISSUE TITLE
[Linux] - SE throws expection

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1285]
Was running some test on using Linux (SE portable): 

![image](http://i.imgur.com/JxiLux9.png)

**Comment by niksedk** [comment]
When running the pre-compiled SubtitleEdit.exe or after compiling with Xamarin? or both?

**Comment by ivandrofly** [comment]
> When running the pre-compiled SubtitleEdit.exe or after compiling with Xamarin? or both?

Pre-compiled

**Comment by niksedk** [comment]
Nice to get this working :)
