### ISSUE TITLE
Windows 10 - does not start

### ISSUE THREAD

**Issue by zaalbarxx** [SubtitleEdit/subtitleedit#1293]
Hi!
I tried to dig some information, but I couldn't find anything so I thought I'll ask here. The problem is that the app does not start on fresh Windows 10 installation. Previously I had it on Win 7 upgraded to Win  10 and it worked fine, but now when I run the app nothing seems to happen. I see the process being spawned in task manager and then immediatly shut down. Is there any option to run it in debug mode or something so I could eventually see what causes the problem? BTW I have .net Framework 3.5 and 4.6 so I think that 4.6 might be the issue here ?

**Comment by niksedk** [comment]
Does anybody else has this problem?

Could you try re-installing .net framework 4.6?

**Comment by suvjunmd** [comment]
Subtitle Edit 3.4.8 build 1 Portable works fine on Windows 10 Pro x64 with .NET Framework 4.6.

**Comment by zaalbarxx** [comment]
I tried 3.4.8 and 3.4.7, both portable and installers and nothing seems to work for me. The problem is I have no real way to debug this, because I don't see any error log or similar kind of thing.

**Comment by marb99** [comment]
Subtitle Edit 3.4.8 lastest build Portable works fine on Windows 10 Pro and Enterprise x64 with .NET Framework 4.6.

**Comment by niksedk** [comment]
@zaalbarxx: Did you ever find a solution for this?
If you know a little about programming you could try the free visual studio: https://go.microsoft.com/fwlink/?LinkId=615464&clcid=0x409
Get, unpack and run from source code: https://github.com/SubtitleEdit/subtitleedit/archive/master.zip

**Comment by zaalbarxx** [comment]
Yeah I found it, I mean I have no idea what exacly caused this, but after a week or two it just started to work, I suppose it was related to .NET framework or something. Anyway you can close it, thanks for trying to solve my problem, cheers.
