### ISSUE TITLE
Request: command line batch processing

### ISSUE THREAD

**Issue by kailia** [SubtitleEdit/subtitleedit#1300]
Hello,
I use SubtitleEdit every day to correct subtitles (correct casing, remove text for HI and fix common errors). Unfortunately, none of this can be done from the command line currently.
I'd love to see that feature, so I can automatically correct subs after downloading or extracting them.
Greetings,
F.

**Comment by Plazik** [comment]
The same request.
I usualy use: fix common errors, remove text for HI and adjust all time.
