### ISSUE TITLE
[bug] Tesseract stopped working

### ISSUE THREAD

**Issue by Elheym** [SubtitleEdit/subtitleedit#1307]
After installing Visual Studio 2015 PE.
<a href="http://lostpic.net/image/RJQ"><img src="http://lostpic.net/images/2015/09/21/f0337591e309550935ff6f224e03c129.th.png" border="0"></a>

**Comment by niksedk** [comment]
Have you checked this: http://www.nikse.dk/SubtitleEdit/Help#issues

**Comment by Elheym** [comment]
Tesseract has been installed, is now removed. Where can I find "TESSDATA_PREFIX"?

**Comment by xylographe** [comment]
Open Control Panel (All Control Panel Items view), select System, select Advanced System Settings, click Environment Variables button.

**Comment by Elheym** [comment]
__xylographe__, thank you, understand a situation. Now everything is working.
