### ISSUE TITLE
[ENHANCEMENT] Case insensitive regular expressions

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1310]
Would it be possible to make regular expression search (and replace and multiple replace) case insensitive by default, with a "Case sensitive" checkbox that modifies both "Normal" and "Regular expression" search?

<pre>
(•) Normal
( ) Regular expression

[✓] Case sensitive
</pre>

**Comment by xylographe** [comment]
In multiple replace you could add prefix `(?i)` to the regular expression pattern.

**Comment by aaaxx** [comment]
I know about regex modifiers, but I think my suggestion would make a better UX.
