### ISSUE TITLE
Bug in "Fix common error"

### ISSUE THREAD

**Issue by Nhoise** [SubtitleEdit/subtitleedit#1313]
When using the "Add period after lines where next line start with uppercase letter" it doesn't add periods if the next line start with a single uppercase I.

Example:
89
00:15:41,090 --> 00:15:43,496
The house seemed desolate to me

90
00:15:44,319 --> 00:15:47,086
I wasn't sure if somebody lived in there.

**Comment by aaaxx** [comment]
Probably because it doesn't necessarily mean that it's the start of a new sentence.
