### ISSUE TITLE
Why does SE add two newlines to the end of file?

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1314]
I know there are some historical reasons for ending text files with a newline, but Subtitle Edit appends two of them (CRLF, CRLF). It does this even when there were none previously, not just when there is already an existing one. I'm talking about SRT here, didn't check the other formats.

And speaking of trailing newlines, are they really necessary in subtitle files?

**Comment by niksedk** [comment]
Apparently some old programs require them. I've had many requests for them...

**Comment by aaaxx** [comment]
Do you mean you've had requests for final newline in general, or for **two** final newlines?

**Comment by xylographe** [comment]
Nothing historical, POSIX defines text files in terms of lines which are **terminated** by a newline.

In SRT format each subtitle has four parts:
- index number (one line)
- time codes (one line)
- text to be shown (one or more non-empty lines)
- empty line to indicate the end of the text

Software requiring the empty line for **all** subtitles is not incorrect, but it is a bit unusual. :)

**Comment by aaaxx** [comment]
Got it now. Thanks.
