### ISSUE TITLE
Fix Common Errors wrong language detection

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#1317]
Hi... 
I have noticed that in recent beta builds of SE 3.4.8 it has detected in (Fix common errors) the wrong subtitle language.

Detects subtitles pt-pt as Spanish. 

And lately happens a lot in several pt-pt subs.

![capturar](https://cloud.githubusercontent.com/assets/7856897/10031312/64b48608-6174-11e5-9098-93469401af30.PNG)

I leave here the sub in pt-pt as the SE (Fix common errors) detects as Spanish language.

Subtitle:
http://www93.zippyshare.com/v/Kdnd8q0d/file.html

-----------------------------------
I have a take a look in code.

And I think the problem can be in AutoDetectWordsSpanish = { "el", "bien", "Vamos", "Hola", "casa", "con" };

and in code:

int spanishCount = GetCount(text, "Hola", "nada", "Vamos", "pasa", "los", "como"); // not french words

"Vamos" and "casa" and "nada" and "como" are equal and very common words in Portuguese too.

perhaps because of it detects subtitles in pt-pt as Spanish.

**Comment by aaaxx** [comment]
If you want to help, get the word frequency lists for Spanish and Portuguese from [here](https://invokeit.wordpress.com/frequency-word-lists/), compile new lists with the most used words for both languages and post them here so the code can be updated.

Twenty or so unique words per language should be enough.

**Comment by xylographe** [comment]
@marb99  What about Portuguese detection words:
```
AutoDetectWordsPortuguese = { "não", "Não", "Estás", "Então", "isso", "com" };
```
Are (some of) these words common in another language (or languages)?


BTW Word lists to differentiate between pt-PT and pt-BR would also be nice.

**Comment by marb99** [comment]
@xylographe 

I think it is not common.

the differences between pt-PT and pt-BR are many differences.

orthographic, syntactical, prosodic and semantics

for some lexical differences.

try this list: https://pt.wikipedia.org/wiki/Lista_de_diferen%C3%A7as_lexicais_entre_vers%C3%B5es_da_l%C3%ADngua_portuguesa

**Comment by xylographe** [comment]
I was thinking of changing the detection order: try Portuguese before Spanish. However, "Estás" is also common in Spanish, "com" is common in Catalan, "não" in Vietnamese, and "isso" might be Italian.

I think this might resolve the issue for now: (with the currently detectable languages)
```
    count = GetCount(text, AutoDetectWordsSpanish);
    if (count > bestCount)
    {
        int frenchCount = GetCount(text, "[Cc]'est", "pas", "vous", "pour", "suis", "Pourquoi", "maison", "souviens", "quelque"); // not spanish words
***     int portugueseCount = GetCount(text, "[Ee]ntão", "[Nn]ão", <<MORE-WORDS>>); // not spanish words
        if (frenchCount < 2 && portugueseCount < 2)
            return "es";
    }

    count = GetCount(text, AutoDetectWordsItalian);
    if (count > bestCount)
    {
        int frenchCount = GetCount(text, "[Cc]'est", "pas", "vous", "pour", "suis", "Pourquoi", "maison", "souviens", "quelque"); // not italian words
        if (frenchCount < 2)
            return "it";
    }

    count = GetCount(text, AutoDetectWordsFrench);
    if (count > bestCount)
    {
        int romanianCount = GetCount(text, "[Ss]înt", "aici", "domnule", "pentru", "Vreau");
        if (romanianCount < 5)
            return "fr";
    }

    count = GetCount(text, AutoDetectWordsPortuguese);
    if (count > bestCount)
        return "pt"; // Portuguese
```
Just need a few (3‒5 I guess) appropriate candidates for `<<MORE-WORDS>>` .

**Comment by marb99** [comment]
this problem will be solved???

for now with new gits the problem remains

**Comment by xylographe** [comment]
As I wrote above, I will need some Portuguese words, that may occur frequently in Portuguese subtitles, and are definitely *not* Spanish words (other languages don't matter in this particular context).

I'm not at all familiar with Portuguese, and just a little with Spanish. Hence, it will be up to you and/or @ivandrofly to provide some appropriate words.

**Comment by marb99** [comment]
@xylographe 

but what is necessary is not to change the words in Spanish?

because if the Spanish words are the same as the Portuguese will always detect the subtitle as Spanish first??

**Comment by xylographe** [comment]
The **AutoDetectWordsSpanish** are an *indication* that the subtitle might be Spanish. But, if the subtitle contains French words (`frenchCount > 1`) or Portuguese words (`portugueseCount > 1`) the search will continue with the next languages (Italian, French, Portuguese, etc.).

For example, if the subtitle seems to be Spanish, but it contains French words, like **pour**, **vous**, or **quelque**, it won't be accepted as Spanish. A similar list of exclusion words can be used for Portuguese (in the line marked with `***`). Of course, that list should contain more words than only **então** and **não**.

**Comment by marb99** [comment]
@xylographe 

ok, thanks for explanation :)

maybe the portuguese words above help

thanks

**Comment by aaaxx** [comment]
Is there really need for these acrobatics? Couldn't there be just two lists, Spanish and Portuguese, that contain the most frequent words that don't occur in the other language, like there are for Croatian and Serbian? They are also *very* similar, sharing most of the vocabulary, and the recognition has been working fine since the last list revision.

**Comment by xylographe** [comment]
@aaaxx 
I've looked at the Spanish and Portuguese frequency lists (thx for the link :) ), and I think it would be possible to compile an **AutoDetectWordsPortugueseAndSpanish** list (similar to the **AutoDetectWordsCroatianAndSerbian** list). The problem is to compile two lists to differentiate between the two languages. The Croatian/Serbian differentiation was only possible because you and @diomed know **both** languages very well.

These ‟acrobatics” OTOH are also used for other languages (Danish/Norwegian/Dutch, Spanish/French/Italian/Romanian, Arabic/Hebrew/Romanian). It's a bit messy, but, probably,  easier when more than two languages are involved. 

@marb99
You can test [this branch](https://github.com/xylographe/subtitleedit/tree/xfix0) (only one commit ahead of SubtitleEdit:master), if you want. It's a start—I'll try to add some more words later.

**Comment by xylographe** [comment]
@marb99 
I hope, this will improve Portuguese subtitle detection: [source-archive](https://github.com/xylographe/subtitleedit/archive/xfix0.zip) or [compiled](https://www.dropbox.com/s/1hdn0t7d40rbwob/SE-3.4.8.555-pt-detect.7z?dl=1)

**Comment by aaaxx** [comment]
@xylographe, I [compared](http://i.imgur.com/hZYBeW1.png) Spanish, Portuguese, French and Italian lists in Excel and compiled new detection lists with unique words for each language. They should function on their own now; could you please test it?

```
SPANISH:

"qué", "eso", "muy", "esto", "ahora", "hay", "estoy", "tú", "así", "cuando", "cómo", "él", "sólo", "quiero", "gracias", "puedo", "bueno", "soy", "hacer", "fue", "eres", "usted", "tienes", "puede", "señor", "ese", "voy", "quién", "creo", "hola", "dónde", "sus", "verdad", "quieres", "mucho", "entonces", "estaba", "tiempo", "esa", "mejor", "hombre", "hace", "dios", "también", "están", "siempre", "hasta", "ahí", "siento", "puedes"


FRENCH:

"pas", "vous", "ça", "une", "pour", "moi", "nous", "dans", "elle", "tout", "plus", "mon", "suis", "au", "avec", "oui", "toi", "fait", "ils", "être", "faire", "comme", "était", "quoi", "ici", "veux", "rien", "dit", "où", "votre", "pourquoi", "sont", "cette", "ton", "peux", "alors", "comment", "avez", "bon", "très", "même", "merci", "ont", "aussi", "chose", "voir", "allez", "tous", "ces", "deux"


ITALIAN:

"che", "per", "questo", "hai", "bene", "sì", "tutto", "più", "della", "gli", "questa", "fare", "essere", "fatto", "perché", "chi", "detto", "così", "quello", "tutti", "anche", "molto", "voglio", "niente", "stato", "grazie", "dove", "abbiamo", "tuo", "nel", "allora", "sta", "siamo", "vuoi", "hanno", "noi", "suo", "stai", "due", "ancora", "qualcosa", "vero", "sia", "loro", "quella", "andiamo", "andare", "delle", "ehi", "signore"


PORTUGUESE:

"não", "uma", "ele", "bem", "isso", "você", "sim", "meu", "muito", "estou", "ela", "fazer", "tem", "já", "minha", "tudo", "só", "tenho", "agora", "vou", "há", "seu", "quem", "então", "lhe", "quero", "nós", "coisa", "são", "ter", "dizer", "eles", "pode", "bom", "mesmo", "mim", "estava", "assim", "estão", "até", "quer", "temos", "acho", "obrigado", "também", "tens", "deus", "quê", "ainda", "noite"
```

The only problem now is telling apart pt-PT and pt-BR. And even though marb says there are many differences, they happen really infrequently – at least in subtitles.

You'll notice in the Excel screenshot that the pt-BR is completely highlighted. Unlike ES, FR, IT, which are checked for duplicates against every language; and PT, which is checked against those three; PT-BR is only compared to PT and already lights up like a Christmas tree. Most of the words occur in both languages all the way down the list to the words with very low frequency (about 3500 words and less in 15912 files, so 0.2 words per subtitle file).

I'll try to come up with some sublists for differentiation tomorrow, probably using a ton of those unique words *and* differences in frequency of duplicate words between languages.

**Comment by xylographe** [comment]
@aaaxx Thank you!
Implemented in [branch uadgl1.](https://github.com/xylographe/subtitleedit/tree/uadgl1)
Portable version `SE-3.4.8.558-pt-it-fr-es-detect.7z` in [this folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)

IMO the main disadvantage of detection lists with unique words for each language is that the addition of another language to `AutoDetectGoogleLanguage` may require compilation of new lists.

To differentiate pt-PT and pt-BR smth more sophisticated than counting words would be needed.
