### ISSUE TITLE
[BUG] "Un-dock video controls" makes them show up at every start

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1334]
When "Un-dock video controls" is set, the Control window (but not Video) opens together with Subtitle Edit, even if it was hidden when SE was last closed.

It's especially annoying because the Control window gets its own item in the taskbar, so when you open a few subtitle files the whole taskbar gets crowded.

**Comment by niksedk** [comment]
A fix it would require a "Show video controls" menu item in the "Video" menu I guess, right?
(it's done on purpose atm)

**Comment by aaaxx** [comment]
I don't think it needs a new menu item. The current "Show/hide video" shows both "Video" and "Controls" windows and also hides both of them (works properly when docked and undocked). The only problem is "Controls" won't *stay* hidden when you run SE the next time, if it was undocked.

**Comment by taxen** [comment]
Hi, I come across this problem, using SE 3.5.7 build 5..

I usually do not use video controls. I only use SE to remove unnecessary lines and fix some line, no need to sync.
So, "Controls - No video loaded" and "Audio - No video loaded" dialogs, which are opened every time no matter how I set [Video]->[Show/hide video], are always in the way.
![157](https://user-images.githubusercontent.com/3875423/45528507-7d437200-b81b-11e8-8eea-531bc77eac10.png)
The shortcut Ctrl+Q does not close the two dialogs at once, but it opens one more dialog, that is "Video - No video loaded".
![158](https://user-images.githubusercontent.com/3875423/45528515-85031680-b81b-11e8-8d97-b09810bd5288.png)
It seems the setting of [Show/hide video] is only effective on the last dialog, but not on the first two dialogs.

Can't they be just hidden all the time?

**Comment by taxen** [comment]
So... I figured it out. To hide even "Controls - no video loaded" dialog, what we have to do is:
1) Dock video controls by using [Video] -> [Un-dock video controls] menu (if undocked)
2) Hide video control pane by using [Show/hide video] menu
3) Close and restart
