### ISSUE TITLE
Got an error while opening a srt file

### ISSUE THREAD

**Issue by ttvd94** [SubtitleEdit/subtitleedit#1350]
"Object refrence not set to an intance of an object."
The subtitle language I'm working on is Persian.
OS: Win 10 x64

![image](https://cloud.githubusercontent.com/assets/14959312/10265960/7d214726-6a52-11e5-9af2-7a5103db45d5.png)

The portable version was OK!

**Comment by niksedk** [comment]
So the installer for SE 3.4.9 crashes on this one subtitle only? Always?
And the portable version works fine with this subtitle?

**Comment by niksedk** [comment]
If you unpack the files in this zip ( http://www.nikse.dk/Debug.zip ) to your installer version folder (probably C:\Program Files\Subtitle Edit or C:\Program Files (x86)\Subtitle Edit) you should get a line number where the crash occurs...

**Comment by ttvd94** [comment]
> So the installer for SE 3.4.9 crashes on this one subtitle only? Always?
No! It happens on all subtitles. Yes, always.

> And the portable version works fine with this subtitle?
Yes, it's ok with any srt file.

**Comment by ttvd94** [comment]
> So the installer for SE 3.4.9 crashes on this one subtitle only? Always?

No! It happens on all subtitles. Yes, always.

> And the portable version works fine with this subtitle?

Yes, it's ok with any srt file.

**Comment by ttvd94** [comment]
> If you unpack the files in this zip ( http://www.nikse.dk/Debug.zip ) to your installer version folder (probably C:\Program Files\Subtitle Edit or C:\Program Files (x86)\Subtitle Edit) you should get a line number where the crash occurs...

Thanke you, I did that and here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/14959312/10289713/a7e54bdc-6bac-11e5-974e-7b77ac0162c2.png)

**Comment by ttvd94** [comment]
**I found some kind of odd solution!**
After extracting your zip file, I created a copy of my srt file using *CTRL+C* and *CTRL+V* and then it successfully opened. I don't know why!

**Comment by niksedk** [comment]
Thx a lot for the line number :)
I believe it's an issue of auto-loading a video file extremely fast combined with late initialization of some variables - could you take the SubtitleEdit.exe (only this file) from this package: http://www.nikse.dk/SubtitleEdit.zip and overwrite the exe in your install folder?

**Comment by ttvd94** [comment]
Sorry for taking too long to answer.
I replaced the file but the problem persists.

![image](https://cloud.githubusercontent.com/assets/14959312/10339603/13f2c0d0-6d19-11e5-9ec9-11ddb6549df7.png)

**As I mentioned before, changing the name of the srt will fix the error. Doesn't that help?**

**Comment by niksedk** [comment]
OK, what about SE 3.4.10 ?

**Comment by ttvd94** [comment]
This new version works as well. No error!
Thanke you so much
