### ISSUE TITLE
"Change casing" seems to be broken?

### ISSUE THREAD

**Issue by insurw** [SubtitleEdit/subtitleedit#1362]
Why does SE's "Change casing" (Normal casing+Fix name casing) wanna fix something that's already correct? Tried 3.4.10 and 3.4.8. It seems all 65 "errors" are already correct.

I added some new errors by changing some sentences to start with lowercase. They are ignored by "Change casing", while "Fix Common errors->Start with uppercase letter after paragraph" correctly detects both original and new errors.

![sebug1](https://cloud.githubusercontent.com/assets/5414960/10329606/030a641c-6cc4-11e5-929e-ddaf7e4ab54c.PNG)
![sebug2](https://cloud.githubusercontent.com/assets/5414960/10329607/030bae58-6cc4-11e5-8ae6-263750e8415c.PNG)
![sebug3](https://cloud.githubusercontent.com/assets/5414960/10329608/030bcdb6-6cc4-11e5-90e2-8077536989d4.PNG)
![sebug4](https://cloud.githubusercontent.com/assets/5414960/10329609/030c4f84-6cc4-11e5-961f-fe1b462dc916.PNG)

**Comment by niksedk** [comment]
I need some concrete cases and also note that the "Change casing" window is only the preview regarding names...

**Comment by insurw** [comment]
You want the SRT file or what do you mean? What do you mean only a preview? It seems broken. Shouldn't a preview show [b]actual[/b] casing errors? Don't you see that it wrongly detects uppercase as lowercase?

Here's the SRT file, but it's not the actual file it's a problem with:
https://drive.google.com/file/d/0BxIAJYOpIauFV3ZuRGZkbWJsSlk/view?usp=sharing

Anyway. With same SRT file that SE finds 65 lines
"Normal casing" ONLY: 0 lines
First/second/Xtime/ using  "Normal casing+Fix name casing": 65 lines
First time using "Fix only name casing": 1 line
Second time (already open SRT) using "Fix only name casing": 65 lines

**Comment by niksedk** [comment]
Change casing "normal casing" first makes all lowercase first , then it applies uppercasing rules (redo all casing)... could some of the radio button texts be improved ?

**Comment by insurw** [comment]
Ah, sorry. I get it now. It wasn't obvious when using "normal casing+fix name casing" that something is done before the popup.
