### ISSUE TITLE
[Request] Mac OSX Version?

### ISSUE THREAD

**Issue by djkrimson** [SubtitleEdit/subtitleedit#1368]
Any plans for mac osx version? There are few mac subtitle editors out there, none work very well.

**Comment by DotTheI** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/81

**Comment by niksedk** [comment]
Duplicate

**Comment by alangfp** [comment]
Please???????? Are there any plans?? This is the best software for windows and I hate Windows!! I'd even buy it for mac! Please?!??!
