### ISSUE TITLE
Bug(?) in "Fix common errors"

### ISSUE THREAD

**Issue by Nhoise** [SubtitleEdit/subtitleedit#1375]
Continuation of Issue #1313 because you locked it before I could respond further and I keep running into this issue.
...
When using the "Add period after lines where next line start with uppercase letter" it doesn't add periods if the next line starts with ~~a single uppercase I.~~ an uppercase I or words which begin with an I (i.e. It's & I'm)

Example:
> 89
> 00:15:41,090 --> 00:15:43,496
> The house seemed desolate to me

> 90
> 00:15:44,319 --> 00:15:47,086
> I wasn't sure if somebody lived in there.

Another example, where it should definitely have put a . at the end of line.
If not only for the fact that there are 2 minutes passed between the two lines. clearly indicating both are separate lines.

> 30
> 00:09:46,607 --> 00:09:49,075
> It's the only way

> 31
> 00:11:48,927 --> 00:11:51,487
> I'm tired.

...
aaaxx commented 19 days ago
> Probably because it doesn't necessarily mean that it's the start of a new sentence (in English, at least).

The first example is questionable, and could possibly do without a dot at the end, though it would look a lot cleaner.
But for the second example, it's obvious both are separate sentences and that the first line should have a dot added.
I've found it's more often that lines starting with an I actually indicate a new sentence than not.
And when it's not, there's often a comma at the end of the previous lines. (In neatly formatted subtitles)
I really feel when there is no comma present and the next line starts with an I, the previous line should always have a dot added at the end.

**Comment by niksedk** [comment]
I've made a minor fix, so now a period will be added if the next line starts more than 400ms after current line. Does that seem okay?
