### ISSUE TITLE
[BUG] TextST subs not imported correctly 

### ISSUE THREAD

**Issue by Rudde** [SubtitleEdit/subtitleedit#1377]
Hello! Great TextST is being implemented! But I have some issues with it. I first tired to import it from the BluRay m2ts stream, Subtitle Edit analyzed it but said it didn't find any streams. So I remuxed it with MakeMKV and now I try importing the made mkv to Subtitle Edit and it do find the TextST streams but it does not seems like it is parsing it correctly, I know the fault could be at MakeMKV but there is no other way of parsing TextST subs at this moment. 

So after doing all this Subtitle Edit gives me this

![Subtitle Edit TextST](http://i.imgur.com/4bMUDvv.png)

As you can see it's filled with a bunch of � and some more on the line I mark have some more question marks and some presumably correct text. Saving this to SRT and opening in notepad gives me this

![Notepad](http://i.imgur.com/XwYJytv.png)

and in the lines I marked in Subtitle Edit the text is all gone

![Notepad](http://i.imgur.com/ViDVgR9.png)

**Comment by niksedk** [comment]
@Rudde: Could you supply sample files - both m2ts and mkv? (either here a via email nikse.dk@gmail.com).

**Comment by Rudde** [comment]
https://mega.nz/#!dMAChKJR!zpR4SBOAfmJy4A8IQJb-Wmqcl5BG1syomOgYDiI0iYs

Here is the MKV, convertet from BD with MakeMKV. It does not seems like the largest m2ts stream contain the subs so I tried to find other TextST and I did find all the subs in seperate smaller m2ts files, so I guess I conclude that this is a MakeMKV problem, would however be nice if Subtitles Edit could identify these subs from the full BD.

**Comment by niksedk** [comment]
Thx for the file :)
Importing TextST from mkv was not supported in SE - be it should be in next update :)
You can test it here (or compile from latest sources):  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip

Yes, the smaller m2ts seems to contain the TextST... Sorry, I've not clue about BDSUP file structure :(

**Comment by Rudde** [comment]
Thanks for feedback!

I don't even think the official vendors have a clue to BDSUP file structure since I have a bunch of films where with TextST subs where most of them work with software like PowerDVD, one of them didn't even tho subs where listed at the cover, found them now with SE, so they are there but somehow will not in PowerDVD. 

Looking forward to support with MKV!
