### ISSUE TITLE
[ENHANCEMENT] "Break line at cursor position"

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1380]
An option to put a line break at cursor position while removing all other line breaks would be great for faster reformatting.

To speed things up (i.e. prevent pixel hunting), you could also make it work not just when the cursor is in front/back of a word, but also when it's inside of a word, by breaking at the first space character before it.

Another great functionality would be to automatically skip to the next subtitle after breaking, so that only a single shortcut is needed when reformatting whole files with bad line breaks.

Since all this would take four items in the right-click menu ("break before/after", "break before/after & jump to next line")), I'd put them all in a sub-menu "Break line at cursor position". That's enough to make people aware of the function, and then they can use shortcuts for speed.

**Comment by aaaxx** [comment]
@niksedk, since you've been working on various breaking options lately, could you give this one a go?

**Comment by aquaticarmadillo** [comment]
Any chance this gets implemented in the near future? I've got a bunch of automatically formatted transcripts that I need to reformat semantically for an upcoming project.

**Comment by LeonCheung** [comment]
@aquaticarmadillo, Hmm, in that case, maybe it would be better to unbreak all lines when starting the reformatting work? Or, if I didn't misunderstand, does it equal to a "unbreak, enter" macro?

**Comment by aquaticarmadillo** [comment]
Yeah, unbreaking them all as the first step is what I'm doing now. But the above-mentioned single shortcut for "break at previous/next space & jump to next subtitle" would be easier than pixel-hunting the space + backspace/delete + enter + go to next sub.

**Comment by aquaticarmadillo** [comment]
Also, even for occasional rebreaking of a few lines in regular subs, it's simpler than the manual routine.

**Comment by OmrSi** [comment]
@niksedk The new shortcuts are for this, right?

**Comment by niksedk** [comment]
Yes :)
And the shortcuts are included in UI in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
