### ISSUE TITLE
[Enhancement] Close open subtitle without exiting

### ISSUE THREAD

**Issue by ricardocosta89** [SubtitleEdit/subtitleedit#1383]
I think it would be helpful to have an option under the File menu to close the current "session" without exiting SubtitleEdit. This would, of course, close any associated resources, such as video, waveform, translation,... Basically, it would be like closing and reopening the application.

Thank you.

**Comment by niksedk** [comment]
Try "New" either via File -> New or via the toolbar icon.

**Comment by ricardocosta89** [comment]
Thank you. That works as well.
