### ISSUE TITLE
[Suggestion] More buttons and functions

### ISSUE THREAD

**Issue by rebawest** [SubtitleEdit/subtitleedit#139]
To improve the timing/spotting process, some functions could be added (with shortcuts). Also, buttons could be placed above the waveform or next to it.
For example:
![waveform redesign](https://cloud.githubusercontent.com/assets/6587015/3253076/d4c93766-f1ce-11e3-8a00-1721a998c0e8.png)
![waveform redesign 2](https://cloud.githubusercontent.com/assets/6587015/3253078/dbde2af2-f1ce-11e3-870d-ed10579dbd6c.png)

These functions would be:
1) Play start of current subtitle/selection (from start-500ms to start+500ms)
2) Play current subtitle/selection (from start-500ms to end+500ms)
3) Play current subtitle (already existing function)
4) Play current selection (already existing function)
5) Play end of current subtitle/selection (from end-500ms to end+50ms)

These functions would make the spotting process easier. For example, after correcting and end time, you would use function "5" (there would be no need to play the whole subtitle to check the end time).
Also, when timing, we need to be sure that the start and end times are correct, so function "2" would be very useful (sometimes it's not enough to play the subtitle: we need to check what happens before and after).

These ideas come from several users I've talked to and were taken from Aegisub, the old SubStationAlpha and some professional programs.

Thank you. Kind regards...

**Comment by niksedk** [comment]
Shortcuts will have to suffice
