### ISSUE TITLE
Error Message-Stack Trace

### ISSUE THREAD

**Issue by nanacastillo** [SubtitleEdit/subtitleedit#1392]
![image](https://cloud.githubusercontent.com/assets/15237370/10647789/27cd8a8a-7800-11e5-8458-600ea60d7c63.png)
![image](https://cloud.githubusercontent.com/assets/15237370/10647796/383f775c-7800-11e5-8ec6-4e2272d23e7d.png)

**Comment by niksedk** [comment]
Have you customized the shortcuts?

**Comment by nanacastillo** [comment]
Yep (at least I tried) but other than that I keep having problem with the video player. I already installed VLC, also the LAV filters, but it is still not working I get a very bad quality and the audio is not sincronized with video.
I´ve just unistalled everything. Should I try it from the top?

**Comment by nanacastillo** [comment]
the video is in mp4 format

**Comment by nanacastillo** [comment]
![image](https://cloud.githubusercontent.com/assets/15237370/10648908/e8afedbe-7806-11e5-9dd2-1822344d043b.png)

**Comment by niksedk** [comment]
Try reading about codecs here: http://www.nikse.dk/SubtitleEdit/Help

**Comment by niksedk** [comment]
Normally it's enough to install lav filters: https://github.com/Nevcairiel/LAVFilters/releases
A few media files cannot be played with lav filters - try switching video player to VLC.

(Hm, I see the error windows says your are running VLC... but that's not true as the video player uses directshow - says so in the main window)

**Comment by xylographe** [comment]
@nanacastillo 
Install [K-Lite Codec Pack](http://www.codecguide.com/download_kl.htm) with MPC-HC (included in Standard, Full and Mega).
The K-Lite installer tries to detect conflicting codecs.

Try to play `Finding Phong.mp4` with MPC-HC.

Select *DirectShow* in SubtitleEdit's `Options > Settings > Video player`.
If it plays in MPC-HC, it should play in SE too.
