### ISSUE TITLE
Issue with OCR Tesserac

### ISSUE THREAD

**Issue by jpsdr** [SubtitleEdit/subtitleedit#1394]
I have some issues with OCR Tesserac. Sometimes, i have the result which is something like "D: oi", when the picture displayed is a normal text.
You can see here an exemple :
![ocr_error](https://cloud.githubusercontent.com/assets/1788001/10691685/628c6402-798b-11e5-890e-b49ac1ffe2c6.jpg)
I don't know if it's a know issue or not. I can provide several files which produce the issue.
Version is 3.4.10.

**Comment by xylographe** [comment]
Is the `TESSDATA_PREFIX` environment variable set?
If so, rename/remove it, and try again.

**Comment by jpsdr** [comment]
I've seen nothing like that in the windows environment variable (in "Configutation panel" "System->Advanced->etc..."), neither the global or local (user).
If it's in SubtitleEdit, i've not found it.

**Comment by niksedk** [comment]
We would probably need the subtitle to have a close look...

**Comment by jpsdr** [comment]
I've send you a mail with informations fonr that. Notify me  when received.

**Comment by niksedk** [comment]
Got the files, thx

**Comment by niksedk** [comment]
OK, SE tries to resize the bitmap to get a better result if unknown words are detected, and a bug sometimes allowed to use worse OCR results of resized bitmaps - should be fixed (if you add the unknown names to the "names etc list" SE will do a little better at OCR).

You can test it via latest sources or here:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip

Also, if you edit Settings.xml (while SE is closed) and set "ShowBetaStuff" to true, you can access a few extra ocr methods...

**Comment by jpsdr** [comment]
I've tried this beta version, when i open an mkv, i've the following message (part are still in french even when i left english in program langage)
![image1](https://cloud.githubusercontent.com/assets/1788001/10710165/7ef4c5dc-7a4c-11e5-9842-704b25353d16.jpg)
After clicking "Ok" several dozen of times, i have  the OCR windows, whith the following error message when i "Start OCR"
![image2](https://cloud.githubusercontent.com/assets/1788001/10710170/a50802f2-7a4c-11e5-99a3-d3af0dc766a4.jpg)

**Comment by xylographe** [comment]
Just a wild guess… Would it be possible, that in [this loop](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Forms/Main.cs#L8962) `p.Data` contains some sort of end-marker(s), causing `outZStream` to Close, while `inStream` has more bytes (following those markers) to be copied?

The WinFormThExc is most likely a result of `mergedVobSubPacks.Count` equalling zero.

**Comment by niksedk** [comment]
New portable beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip (fixed a bug regarding vobsub in mkv due to recent refactoring).

Is it only with some files? 
What your OS?
Do you unpack the beta portable files, to something like D:\Tools ?

**Comment by jpsdr** [comment]
mkv issue solved with new portable beta.
OS Win7 x86 and x64. I was until now using installed version, but, as i'm using SE also on a PC without internet, finaly i'll switch to portable. It's more conveniant for transfering dictionnaries.
I've tested on file 1 & 4 of the files i've provided you. It's better, but there is still some issues. If you take the Ep4 i've provided you, use tesserak with "music symbol" uncheck, and "try to guess unknow words" also uncheck, after OCR, there is still several lines with errors, but it's better than before :
Line 140 : Text is still messed-up.
Line 263 : Italic detected when not. Appened also on others files, sometimes a word in a middle of a line is detected italic when not.
Line 238,240,241,242 : Lines are blank.
There still some issue, but it's better than before.
After, i don't know if actual status is the best possible because OCR can't do better, or if there is still some improments possible.

**Comment by xylographe** [comment]
@niksedk 
Perhaps, [the `Stream.CopyTo` in **ManagedBitmap.cs**](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/ManagedBitmap.cs#L23) should be replaced too?

**Comment by jdpurcell** [comment]
The problem with CopyTo is only due to a bug / bad design with ZOutputStream. ZOutputStream's CanRead / CanWrite properties always return false, which is why CopyTo thinks it has been disposed.

**Comment by xylographe** [comment]
Ty, J.D.
The CanWrite property would do well to `return out_Renamed.CanWrite;`

**Comment by jpsdr** [comment]
Maybe udating Terreract may improve things ?
SE apparently uses the 3.02, and it seems that we are at least at the 3.04, and more, several commits seems to have been done since the 3.04 release tag.

**Comment by jpsdr** [comment]
I've tested the 3.04, using the build made for msys2. It seemed slower, and it produced output garbage like before the fix, when the 3.02 produced correct output. Didn't see anything realy better for the detection of italic. Now, maybe just replacing brutaly the 3.04 when thing are tuned for the 3.02 may not be also the best idea... But i was curious to test out.

**Comment by niksedk** [comment]
New portable beta up again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip 
The italic issue is not possible to fix (line 236) - the blank lines and the messed up line should be better.

Great you tried the new Tesseract - not so great that it did not perform better. I'm waiting for an official release. I've added an issue here - https://github.com/tesseract-ocr/tesseract/issues/47 - but it's been several years since last windows release so... you might want to test the "NEW image compare" or "nocr" via the "ShowBetaStuff" setting (the line splitting should be improved at least).

**Comment by jpsdr** [comment]
Thanks for the new version.
I've just quick tested the "tesseract-core-20150916" on the link you provided, and result is still not better, and it's slower than the version provided with SE.
I'll test later the "betastuff" you talk about.
Otherwise, thanks for all the work done on SE and all the features it has, it's a very usefull tool.

**Comment by jpsdr** [comment]
I've been able to make more tests, on the file of the Ep4.
First, i've still tried the "tesseract-core-20150916", results are not very good.
Slower, more false italic detections, a little less miss italic detection, text ouput garbage on lines version of SE produce good results.
With the version of SE, good improvements, but line 140 is still messed-up. After, maybe this is the limit, i know that sometimes trying too much to have a good result on a specific situation, may broke others.
I don't know if it's the case, but it's not use to try forcibely to solve an issue, if the counterparts is to generate 10 others. So, i don't know the situation, if it can be improved, ok, otherwise, there have been already very good improvements.

**Comment by niksedk** [comment]
Line 140 in Ep4 is good here...
I will wait for an official Tesseract release - or wait until I hear about an unofficial release that rules :)
