### ISSUE TITLE
Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by scope73** [SubtitleEdit/subtitleedit#1397]
Some of the TS files I try to extract subtitles from crash with this error message and the following:
![untitled](https://cloud.githubusercontent.com/assets/15326321/10736319/2eeb62f8-7c04-11e5-9bc9-79b6789d1220.png)

Can you help?

**Comment by niksedk** [comment]
Could you possibly supply a sample file either via a link here or email?

**Comment by niksedk** [comment]
@scope73: Could you test this version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip (no installer, beta)

**Comment by scope73** [comment]
It's working fine now. Thanks!

**Comment by niksedk** [comment]
thx for verifying :)
