### ISSUE TITLE
Default font

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#1399]
Is this the way to set the default font in SE?

`this.Font = SystemFonts.MessageBoxFont;
InitializeComponent();`

http://benhollis.net/blog/2007/04/11/setting-the-correct-default-font-in-net-windows-forms-apps/

**Comment by xylographe** [comment]
Running 
```
sls '.Font = ' (gci -Recurse -Filter '*.Designer.cs') -List -SimpleMatch -CaseSensitive
```
reports 57 files. In those files `InitializeComponent()` would set the Font property back to *Tahoma* or *Microsoft Sans Serif*.

Perhaps, setting the Font property in a base Form (inherited by every other Form), and not changing it in the inheritor, might be the more flexible way. If in future a change would become necessary, it would only have to be changed in one file.

**Comment by niksedk** [comment]
Later versions of SE uses default system font...
