### ISSUE TITLE
[BUG] Google/Microsoft translate original line crash

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#1405]
Google/Microsoft translate original line crash on SE 3.4.10 build 108

![capturar](https://cloud.githubusercontent.com/assets/7856897/10896908/d42c6022-81b4-11e5-90b0-de88bed09469.PNG)

**Comment by niksedk** [comment]
Should be fixed via https://github.com/SubtitleEdit/subtitleedit/commit/16564ef0126fc16ef1437459ed80602d5db61754 and https://github.com/SubtitleEdit/subtitleedit/commit/beda2a9849665ec08c9ce1afd3033b32b1ca896d - also some info here: https://github.com/SubtitleEdit/subtitleedit/pull/1476 - thx :)
