### ISSUE TITLE
inserted first line?

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#1408]
why this program doesn't start up with already open first line, and ready for editing, but we have to insert it all the time we open it? is there any good reason for that?

**Comment by aaaxx** [comment]
This is a good point. Even though I don't usually create subtitles, whenever I needed to write something from scratch I was annoyed by this. The first time, I actually kept clicking the "New" button wondering why nothing was happening.

**Comment by ivandrofly** [comment]
Ah :+1:  @diomed, we need to consider this /cc @niksedk.

**Comment by diomed** [comment]
How come this never came into realization?
Can you do something about it, @ivandrofly ?
