### ISSUE TITLE
[Feature Req] Show selected line and after earlier/later

### ISSUE THREAD

**Issue by Nhoise** [SubtitleEdit/subtitleedit#1414]
You would select a line and it would function the same as the "show selected lines earlier/later" function except it would keep the timing of the lines before your selection intact.
Handy for i.e. editing Theatrical release subs to Director's Cut subtitles.
Currently you have to select all the lines you want to change manually each time, and having this function would make it way faster.

**Comment by niksedk** [comment]
"Set start and offset the rest" is available in multiple forms - via audio visualizer and via buttons and via shortcuts :)
