### ISSUE TITLE
SHD removal fixes

### ISSUE THREAD

**Issue by Thunderbolt8** [SubtitleEdit/subtitleedit#1420]
some SHD removal fix suggestions. already posted these on doom9, but I dont know how often posts over there gets checked.
I have to stretch the italic markers < i > and < /i > out like this, otherwise they get turned into code here. Also, the • symbol is supposed to be a hyphen "-" but it gets turned into this • symbol when placed it in front of the music symbol ♪.

some more SHD removal inconsistencies, some parts of lines are not removed correctly when italics are involved

("remove text between ♪ and ♪" is ticked and "remove text if it contains: ♪,♪♪" is unticked)

correct:

- ♪ Was a good friend of mine ♪|- All right!    ==> All right!

incorrect:

< i >- ♪♪[Continues ]< /i >|- It's pretty strong stuff.    ==> < i >< /i >|- It's pretty strong stuff. (Should be: It's pretty strong stuff.)

---------------------------------------------

this one here is debatable, I guess its working as intended. it just looks a bit strange just to have the hyphen within the italics and not the rest of the line, as it was already strange with having the hyphen + [Nick] speech information in italics and not the rest as well, before. if youd ask me, the italics could be removed in *such* a case, but as said, according to the rules its probably working as intended:

- The meal is ready. Let's go!|< i >- [Nick]< /i > J. T. Lancer!   ==> - The meal is ready. Let's go!|< i >-< /i > J. T. Lancer!

-----------------------------------------------------

in this case here, the italics tag needs to be closed after the first line, because the closing tag gets removed along with the SHD content ("whoa" was added to the "remove interjections") of the line after the break and the italics tag extends over that line break (this should not be a problem in case of subtitles which have a separate open&close tag for each part of a subtitle line, before and after the line break symbol):

< i >- Here it is.|- Whoa!< /i > ==> < i >Here it is. (Should be: < i >Here it is.< /i >)

--------------------------------------------------

it would be nice if the "remove text between" tick box for ♪ and ♪ could be extended to also have ♪,♪♪ and ♪,♪♪ as the "remove text if it contains:" box right next to it already has. right now, the line

♪ Trotting down the paddock|on a bright, sunny day ♪♪

does not get removed, because the open and closing music symbol is different. the line would get removed if the "remove text if it contains: ♪,♪♪" box was ticked, but then a line like

- ♪ Was a good friend of mine ♪|- All right!

would get removed entirely as well (instead of only the part before the line break). so in such cases, if a subtitle file consists of different lines like

- ♪ Was a good friend of mine ♪|- All right!

*and*

♪ Trotting down the paddock|on a bright, sunny day ♪♪

theres currently no option to have this handled automatically correctly (which is not to remove the "all right" part in case of the first line *and* remove the 2nd line entirely), youd have to tick/delete stuff manually. this could be avoided if the options to select from of the first box "remove text between" would be extended from only including ♪ to include ♪,♪♪ as well.

----------------------------

in such a case here, if SHD information gets removed and a hyphen ("—" "-" or "--") follows afterwards, a syntactic indicator of ending or linking a sentence like full stop (.), exclamation mark (!) or comma (,) which directly preceeds that SHD information should be removed then.

Oh. Oh, yeah. Um —   ==>   Yeah. — (Should be: Yeah —)

**Comment by niksedk** [comment]
thx for the info - I've tried to fix the issues here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip

**Comment by Thunderbolt8** [comment]
thanks, I'll try it and report back something might be still not working as intended

**Comment by Thunderbolt8** [comment]
some addition similar to what we already had with 1 line break, also should extend to lines with 2 (or more) line breaks ("remove text between ♪ 'and ♪" is ticked and "remove text if it contains: ♪,♪♪" is unticked)

<i>- ♪ Honey, honey, yeah ♪|- ♪ Heard it through|the grapevine ♪</i>

==> <i>♪ Heard it through|the grapevine ♪</i>

everything should be removed entirely in this case.

**Comment by niksedk** [comment]
I don't think SE has much support for 3 or more lines. It's a new issue...

**Comment by Thunderbolt8** [comment]
well, the first case with the music symbols is fixed now. so I guess the same should be possible in the 2nd case? afaik I havent seen subtitles with more than 3 parts of a line (=more than 2 breaks) as well so making a fix for anything beyond this should not be needed. I rather wanted to say when creating these rules it might be useful to make sure that they not only apply to lines which have a max length of 2 parts (= 1 break), but also for those with 3 parts as otherwise you'd have to change/add the same rules again at some point in case of the latter lines.
