### ISSUE TITLE
Improvement: Better colours in "compare subtitles" window

### ISSUE THREAD

**Issue by Thunderbolt8** [SubtitleEdit/subtitleedit#1422]
In the "compare subtitles" window, please change the colour of how same lines are marked in the right window, of that subtitle file you are comparing against. currently, that colour looks like sand, its too difficult to spot from the white background. please turn it into something easier to distinguish from white.

**Comment by niksedk** [comment]
Is it better like this: http://www.nikse.dk/SE_Compare.png

**Comment by Thunderbolt8** [comment]
judging from the screenshots I would say yes, it is.

**Comment by niksedk** [comment]
OK, fixed in commit d45a47738fb3b61269bdbbde9d2faac5227216fb

**Comment by niksedk** [comment]
Hm, the color could also be green?

**Comment by Thunderbolt8** [comment]
I dont mind as long as it isnt already used in that window and can be distingushed well from the background, the other colours and that the subtitles lines are still readable. 

though something like green should perhaps rather be used to indicate something like sameness instead of difference for which red would be better? but frankly said this would be secondary.
