### ISSUE TITLE
more SHD removal stuff

### ISSUE THREAD

**Issue by Thunderbolt8** [SubtitleEdit/subtitleedit#1427]
since we cannot reopen topics on our own (unless I havent found out yet how) I suggest to leave this topic open so I (or someone else) can periodically add stuff when finding something new. Otherwise I'd have to open another topic each time for these SHD removal problems.

I added two things to the other topic after it was closed, but I dont know if you saw these. At least they havent been fixed yet, so Ill list them again:

refering the latest fix of the closed topic: Its working fine when all 3 parts of the line have the music symbol included, but not when this only applies to two of the tree parts ("remove text between ♪ and ♪" is ticked and "remove text if it contains: ♪,♪♪" is unticked):

< i >- ♪ You make me feel like a natural woman ♪♪< /i >|- Oh. I— I—

==>

< i >- ♪ You make me feel|like a natural woman< /i >|- I— I—

part 1 and 2 of that line should be removed entirely 

------------------------------------------------------------------------------------

another normal SHD problem, not involving music symbols: The line break symbol remains even though it shouldnt:

< i >Ow. Ow.|Ow, my head.< /i >

==> < i >|My head.< /i >

**Comment by niksedk** [comment]
I think github works best with one issue per bug (or bugset). I've tried to add a label called "remove text for hi" so it can still be grouped.

**Comment by niksedk** [comment]
Updated the beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip

**Comment by Thunderbolt8** [comment]
thanks
