### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by heforfree** [SubtitleEdit/subtitleedit#1428]
An application error occurred in Subtitle Edit.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Nikse.SubtitleEdit.Forms.Main.timer1_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by niksedk** [comment]
thx for the info.

Could you try this file: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip 
It is a debug version and the error from this version should include a line number.

Also, what were you doing when the application crashed?

**Comment by heforfree** [comment]
hello thank you for replay.it seems i don't get that error in beta test.
i have ffdshow installed,i set vlc path but when it start it seems load ffdshow icon in appear in tray.so wont play anything.
but in betatest vlc work.i uninsaled ffdshow insatalled K-Lite Codec Pack,but when i select directshow just show subtitle and audio not video

**Comment by niksedk** [comment]
OK, thx for testing.

If you're running a 64-bit os (I guess most are) then you need a 64-bit VLC: http://get.videolan.org/vlc/2.2.1/win64/vlc-2.2.1-win64.exe

For directshow I recommend: https://github.com/Nevcairiel/LAVFilters/releases

Also check the help page: http://www.nikse.dk/SubtitleEdit/Help

**Comment by heforfree** [comment]
thankyou very much
