### ISSUE TITLE
batch conversion of .srt subs to .ass

### ISSUE THREAD

**Issue by Thunderbolt8** [SubtitleEdit/subtitleedit#1431]
this is about batch conversion of .srt subtitles to .ass. several things:

1. when altering the default style, after the conversion the style template is reset again to its default style which I find very annoying as I always want to use the ~same style (with little changes) and not having to change all this again once I did a conversion. Could you change this please (you then could also add a "reset defaults" button)? Also, could you please add the option to create & select different templates? 

2. Could you please add the option to set the default resolution of the .ass file as well? Default one is 0x0 pixels, but it would be useful to be able to change this. Also, when adding this, please also add the option to "scale border and shadow" as well.

3. In the style field, under colours: the value "alpha" = 255 here corresponds to alpha = 0 in aegisub. changing it to 0 makes the subtitle somehow look grey or black. is this intended that there is this difference between these two programs?

4. in the colour wheel selection screen, the colours I selected cannot be applied accurately. I changed the primary colour to be "246 245 222" (red green blue), but after the conversion I got "246 243 222" and another time "246 244 222" (it seems like the colours are already not saved correctly when accessing the field again just to check, they have already changed then)

**Comment by Thunderbolt8** [comment]
this is about batch conversion of .srt subtitles to .ass. several things:

1. when altering the default style, after the conversion the style template is reset again to its default style which I find very annoying as I always want to use the ~same style (with little changes) and not having to change all this again once I did a conversion. Could you change this please (? Also, could you please add the option to create & select different templates? 

2. Could you please add the option to set the default resolution of the .ass file as well? Default one is 0x0 pixels, but it would be useful to be able to change this.

3. In the style field, under colours: the value "alpha" = 255 here corresponds to alpha = 0 in aegisub. changing it to 0 makes the subtitle somehow look grey or black. is this intended that 255 here is 0 in aegisub?

4. the conversion process cant apply the colours I selected accurately. I changed the primary colour to be "246 245 222" (red green blue), but after the conversion I got "246 243 222" and another time "246 244 222"

**Comment by niksedk** [comment]
The batch ass/ssa settings should be saved now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip

3) It's internationally that alpha 0 = transparent and alpha 255 is fully visible (works like this in all image programs - and so the actual code)

4) was unable to re-create this...

**Comment by Thunderbolt8** [comment]
thanks, 1. is fixed

3). as long as the colours are the same I dont mind in the end why its 0 or 255. was just curious why there is this difference between subtitle edit and agisub

2) any plans on that? theres still a box of space left in the style field :)

4) it still happens to me. I used your latest beta from above^^

I opened subtitle workshop by clicking on an .srt subtitle file and clicked batch convert.

I clicked style. I did some changes to the font size and the vertical margin.

I clicked on colors primary. it looked like this: http://www.imagebam.com/image/6f7bf7451206698

then I changed the colours values to this: http://www.imagebam.com/image/8687c7451206701

I clicked ok and then on colors primary again. now it looked like this: http://www.imagebam.com/image/e1e081451206708

I clicked ok and again on colors primary. it looked like this: http://www.imagebam.com/image/8b773f451206718

clicked on, colors primary & ok again for a few times, but changed further from that occured

**Comment by niksedk** [comment]
4) Ah thx :)
You could test this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip ?

1+2) Good ideas... perhaps even something for editing the raw header...

**Comment by Thunderbolt8** [comment]
4) fixed, thanks!

**Comment by niksedk** [comment]
Updated beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip
Does it look okay?

**Comment by Thunderbolt8** [comment]
looks really good, thanks!

the only thing missing now is the ability to save & load different styles, then it would be perfect :)
