### ISSUE TITLE
request for timestamps editing

### ISSUE THREAD

**Issue by Thunderbolt8** [SubtitleEdit/subtitleedit#1432]
could you please add the possibility to change the timestamps of subtitles as you can do it in subtitle workshop with "adjust subtitles..." ?

what you can do here is to specify the timestamps of the first spoken line and the last spoken line. this is useful when having subtitles which e.g. drift slightly out of sync over time.

e.g. if you change the timestamps of the last spoken lane to 1 second later, then all lines in between will be adjusted evenly with a slight delay until the delay reaches set +1 second for the last spoken line.

**Comment by niksedk** [comment]
Check the sync menu...

**Comment by Thunderbolt8** [comment]
Ive already taken a look at this but I dont really know how to use it. it looks rather complicated :S

**Comment by aaaxx** [comment]
You need "Point sync...".

Select the line you want to use as a first point (i.e. first spoken line) and click the "Set sync point" button. Then, in the new window that pops out, find it in the video and click "Set sync point".

Now you're back to the previous window and you just have to do that again for the second point (last spoken line). Hit OK when done.

Note that you can type the timecodes manually, which makes it really easy if you have another file that's already in sync.

**Comment by Thunderbolt8** [comment]
ok I understood. I tried it and it seems to work the same way as in subtitle workshop. good, then this request is not needed :)
