### ISSUE TITLE
options ass / ssa ?

### ISSUE THREAD

**Issue by n1dminhd** [SubtitleEdit/subtitleedit#1436]
If :

![01](https://cloud.githubusercontent.com/assets/4449742/11620092/ce2b244a-9ce1-11e5-94f2-8fc4cfdc1e0a.jpg)

SAME

![02](https://cloud.githubusercontent.com/assets/4449742/11620093/ce2f38d2-9ce1-11e5-991b-5b3ea1c20bd1.png)

will be very convenient

**Comment by aaaxx** [comment]
If you're saying that all of the SSA/ASS options should be available in Settings, then I agree :+1: .

By the way, Tahoma doesn't have italic, so you'll get automatically angled text that looks nasty if there are italics in your subs. See second part of [my comment here](https://github.com/SubtitleEdit/subtitleedit/issues/1194#issuecomment-134775172) for some font recommendations.

**Comment by n1dminhd** [comment]
Yes, I am saying that all of the SSA/ASS options should be available in Settings
Every convert, to adjust, very laborious

**Comment by niksedk** [comment]
Sorry, there's some differences between SSA and ASS so it not possible to merge all options - but next version will have more of settings in options - and the options in batch convert will be remembered - https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEdit-3.4.10-Setup.zip

**Comment by n1dminhd** [comment]
Yes, very Good
Thanks !

**Comment by niksedk** [comment]
Batch ASS/SSA settings a bit more: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip

**Comment by n1dminhd** [comment]
too standardized, extremely well, thank you
