### ISSUE TITLE
Could I get exportable character count?

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1437]
I'm working on some statistics and could really use an option to replace each line with its character count.

I don't know where it would make most sense to stick such an option, but since I can't think of a reason anyone would ever use it maybe it would be best to put it in "Export custom text format..." – something like a "Text" dropdown box with options to "replace with char. count (one number per line)" and "replace with char. count (one number per subtitle)", the second one summing counts in multiline subs.

Oh yeah, and could you prevent the "Export custom text format" window from automatically closing after saving the file?

**Comment by aaaxx** [comment]
And also "replace with CPS (decimal point)" & "replace with CPS (decimal comma)", if it's not too much to ask. (Don't truncate the decimals.)

**Comment by aaaxx** [comment]
Actually, thinking about it, the best solution would be to just make these things separate {placeholders}, just like the existing {number}, {start}, {end} and {text}. That would be easy to customize and simple to extend in the future if there's need for some other info. Then just add another frame to the window with a list of available placeholders and explanations. And also include timecode format and new line mark as part of the placeholders.

Something like this:
<blockquote>
<p><i><b>Placeholders</b></i></p>

<ul>
<li>{sub number}</li>
<li>{start "&lt;time&gt;"}</li>
<li>{end "&lt;time&gt;"}</li>
<li>{text "&lt;line separator&gt;"}</li>
<li>{char. count "per line / per subtitle"}</li>
<li>{CPS "&lt;decimal mark&gt;" "&lt;number of decimals&gt;"}</li>
</ul>

<p><i><b>Formatting</b></i></p>

<p><b>&lt;time&gt;</b></p>
<ul>
<li>hh:mm:ss,zzz</li>
<li>hh:mm:ss.ff</li>
<li>h:mm:ss,zzz</li>
<li>h:mm:ss,zz</li>
<li>ff</li>
<li>zzz</li>
<li>ss</li>
</ul>

<p><b>&lt;line separator&gt;</b> can be any character</p>

<p><b>&lt;decimal mark&gt;<b></p>
<ul>
<li>point</li>
<li>comma</li>
</ul>

<p><b>&lt;number of decimals&gt;</b></p>
<ul>
<li>number up to ???</li>
<li>if omitted the number won't be rounded</li>
</ul>

<p><b>invisible characters</b></p>
<ul>
<li>\r\n = line break on PC</li>
<li>\n = line break on Mac</li>
<li>\t = tab</li>
</ul>
</blockquote>

**Comment by philippwr** [comment]
This is an old issue, but are there some news on this? Any chance to export subtitles to a format (custom or not) that also includes character count and CPS?
