### ISSUE TITLE
Issue with french OCR fix

### ISSUE THREAD

**Issue by abibouba** [SubtitleEdit/subtitleedit#1439]
Hello,

First of all thanks for this awesome piece of software.

There is an issue with the "Fix common OCR errors" in French. Everytime a « l' » is found, the following character is a capital while it should not.

I can't find which part of the code must be changed. I would really appreciate (and a lot of french users as well I guess) if you could do the change or at least point me to the file which needs to be changed.

Thanks,

**Comment by diomed** [comment]
This file should be changed:

https://github.com/SubtitleEdit/subtitleedit/blob/master/Dictionaries/fra_OCRFixReplaceList.xml

I however don't know French so am not sure is this problem that exists in file itself, or is it something that you plan to add. Nevertheless, take a look, and change what you need.

**Comment by xylographe** [comment]
@abibouba 
I couldn't reproduce. Perhaps, you can post an example.

**Comment by abibouba** [comment]
Sorry guys. My explanation was wrong.
Actually it's : if there is a « l' » and the following letter is capital, then « l' » is set as « L' » (which is not correct)

Please check the attached file (row 3)
![3](https://cloud.githubusercontent.com/assets/672894/11680182/a57c6394-9e56-11e5-9b94-05acd96f12ad.PNG)

**Comment by abibouba** [comment]
(And you can see as well that "Fix common OCR errors" removes spaces between numbers even though the option is not selected.

**Comment by xylographe** [comment]
Both issues are caused by enabling hard-coded rules (*Options > Configurations… > Outils Erreurs :: OCR courantes - utilise aussi les règles codées en dur*).
See [FixFrenchLApostrophe()](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Logic/OCR/OcrFixEngine.cs#L446) and [RemoveSpaceBetweenNumbers()](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Logic/OCR/OcrFixEngine.cs#L573).

**Comment by xylographe** [comment]
@niksedk 
Perhaps, it would be better to merge [`OcrFixEngine.RemoveSpaceBetweenNumbers()`](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Logic/OCR/OcrFixEngine.cs#L573) with [`RemoveSpaceBetweenNumbers.Fix()`](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/Forms/FixCommonErrors/RemoveSpaceBetweenNumbers.cs#L11) ?

**Comment by niksedk** [comment]
@abibouba: Should be fixed in next update - you can also test this portable version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip
