### ISSUE TITLE
[Feature Req] EBU-TT / TECH-3350 support

### ISSUE THREAD

**Issue by feulix** [SubtitleEdit/subtitleedit#1441]
It looks like EBU-TT isn't supported yet. This is the follow-up to the widely used EBU STL format.
More info: https://tech.ebu.ch/ebu-tt

**Comment by niksedk** [comment]
Is EBU-TT in use today?
Some sample files would help a lot...

**Comment by feulix** [comment]
I'm not sure if it is in use at this moment, but I think it's good to be prepared.

The XML schema for EBU-TT is available here, maybe that can help? ​​https://tech.ebu.ch/files/live/sites/tech/files/shared/ebu-tt/ebu-tt-xml-schema-v.1.0.1.zip

**Comment by rebawest** [comment]
@niksedk As far as I know, EBU-TT is based on TTML, which is already implemented in SE (as Timed Text). EBU-TT is just another XML format, very similar to TTML.

By the way, TTML just won an Emmy Award. :-O
https://tech.ebu.ch/news/2016/01/timed-text-subtitling-receives-e

What is more, the Netflix format DFXP, which was requested in issue #1511, seems to be the same as TTML.

If you decide to go ahead with EBU-TT, I can try importing and exporting from EZtitles to check compatibility. The same with other formats.

However, when I try to export to EBU-TT, I get this Window. I'm sure how important those parameters are, but implementing this format might not be easy, as it's an industry standard.

![image](https://cloud.githubusercontent.com/assets/6587015/12726135/ace539b2-c8f4-11e5-9889-6163270d5400.png)

**Comment by JW301** [comment]
I too would like to see support for this format.

I have some EBU-TT subtitle files that I cannot use with SubtitleEdit. When opening these files, it shows some items with wrong time codes, and the text is just "{\an8}" for every item.

The format seems to be widely used by european state TV networks when distributing their content through their websites. (I attached a file I downloaded from the german ARD media library).

Technical specification for this format can also be found with the BBC: http://bbc.github.io/subtitle-guidelines/

Funnily enough, I can open the file with Subtitle Edit Online, but in the Desktop version it doesn't work.

[1370197_15958271.zip](https://github.com/SubtitleEdit/subtitleedit/files/1342256/1370197_15958271.zip)

**Comment by niksedk** [comment]
@JW301: Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip ?

**Comment by JW301** [comment]
Seems to work fine with the beta. Thanks!

**Comment by niksedk** [comment]
thx for verifying :)
