### ISSUE TITLE
How to batch extract pgs subtitle from mkv and convert them to srt?

### ISSUE THREAD

**Issue by garymaxallen** [SubtitleEdit/subtitleedit#1444]
I find no easy way and do it one item a time. it's cray! God help me!

**Comment by adem0x** [comment]
Would this help?

https://github.com/SubtitleEdit/subtitleedit/issues/1510

**Comment by OmrSi** [comment]
@niksedk Isn't this already available via Batch convert?

**Comment by niksedk** [comment]
Yep, thx :)
