### ISSUE TITLE
import from html index file

### ISSUE THREAD

**Issue by heforfree** [SubtitleEdit/subtitleedit#1448]
hi
import image as sub idx file and read timing from html index file

**Comment by niksedk** [comment]
Could you explain a bit more about this and why it's important? Also, what is an html index file? Some samle input would also be nice...

**Comment by heforfree** [comment]
thank you when opening sub idx file when right clicking on image there is context menu
save all images with HTML index... when you save with this way it extract all images and at the end create file index.html html file have timecode for each extracted image.

file name
0001.png
0002.png

html look like this.

<html>
<head><title>Subtitle images</title></head>
<body>
#1:2:12,882->2:13,144<div style='text-align:center'><img src='0001.png' /></div><br /><hr />
#2:2:52,881->2:53,780<div style='text-align:center'><img src='0002.png' /></div><br /><hr />
</body>
</html>

honestly,i already try with Timings Cleaner to delete duplicate image but it is not very accurate
searched and found VisiPics.it can detect very better duplicate image.so i want when remove
duplicate image then re import all remained image and timing read from html file (sub idx file is big i can not upload around 23mb)

http://www.fosshub.com/VisiPics.html 

also this can make "save all images with HTML index..." more usefull option
thankyou very much

**Comment by heforfree** [comment]
thank you very much.i very much appreciated.
