### ISSUE TITLE
Remove uppercase lines for hearing impaired - bug

### ISSUE THREAD

**Issue by Krzysiu** [SubtitleEdit/subtitleedit#1449]
Hello! I think it counts as bug. In tool *Remove text for hearing impaired* there's an option *Remove line if UPPERCASE*. In facts it does kind of different thing. It doesn't remove uppercase lines, but it **deletes line if it's not lowercase**. In `Let's count!<br>1.. 2... 3!` the second line will be removed as `1... 2... 3!` is not lowercase (nor uppercase; or it's both lowercase and uppercase<sub>eh, quantum physics ;)</sub>). I think it should be renamed to *Remove line if not lowercase* or (preferably) fixed to remove lines which are uppercase, i.e. contains only uppercase characters. I don't know C, but it could be like (in pseudocode)

    IF line == uppercase(line) AND line != lowercase(line) THEN mark_to_remove

**Comment by niksedk** [comment]
thx, should be fixed with this commit: https://github.com/SubtitleEdit/subtitleedit/commit/fd46e005c5b8c68e90d50fc53aa0924860dd694c
Beta update: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip
