### ISSUE TITLE
Remove Dash in Beginning

### ISSUE THREAD

**Issue by TMDaines** [SubtitleEdit/subtitleedit#1450]
There still appears to be an error with this check. The latest version still does not pick up on all lines that begin with dashes, offering the option to remove them. Very few in fact are detected.

**Comment by niksedk** [comment]
Could you give some examples?

**Comment by TMDaines** [comment]
It appears to be subtitles that have two lines separated by dashes where it does not work. Perhaps this is working as intended, but I would expect it to strip opening dashes from all lines. Why do you need them after all?
![capture](https://cloud.githubusercontent.com/assets/13799044/11902570/ad71afcc-a5aa-11e5-9abf-50c72caa90f0.PNG)

**Comment by ivandrofly** [comment]
It indicates that the paragraph was narrated by 'two' different person.
ex:
- John: Hello!
- Hanna: Hi, how are you?

**Comment by ivandrofly** [comment]
Actually there is a Plugin which does remove dashes but only in first line, I'll update/add feat to allow removing dash in both first and second line

**Comment by TMDaines** [comment]
That's great. I'm only interested in removing them from the first line, i.e. any opening dashes in a piece if text. They always seem redundant to me and take up precious characters. Subsequent dashes, of course, have an important role to play in introducing text from another speaker.

**Comment by ivandrofly** [comment]
@TMDaines the feat is ready
https://github.com/SubtitleEdit/plugins/releases/download/v.1.1/DiaOneHyphen.zip or you can get it using Subtitle Edit
`File\Plugins\Get Plugins\Dialogue one hyphen only`

**Comment by TMDaines** [comment]
Thanks. This works very nicely.

**Comment by TMDaines** [comment]
Could this be modified to have a further option to strip all initial dashes in lines where there is only the one initial dash? Currently this plugin only strips all initial dashes in dialogues with more than one dash OR all dashes.

I want to strip all initial dashes, regardless of whether there is a second line of dialogue, but keep any dashes introducing any second or third lines of dialogue.

Fix Common Errors does not offer this function either.

What I want is that:

- Hello.
- Bye.

becomes

Hello.
- Bye.

- Hello.

becomes

Hello.

**Comment by TMDaines** [comment]
@ivandrofly 
Would you be able to modify this plugin again? In addition to the issue above, this plugin is still not capable of removing all opening hyphens from all lines.

For example, in the attached film (which you will need to add the .srt extension to again), unless you tick "Strip all Beginning Hyphen" lines 40 and 55 are missed, but then this removes hyphens from the second line of some text like in line 153.

[Мелодiя для шарманки (2009).eng.txt](https://github.com/SubtitleEdit/subtitleedit/files/334864/i.2009.eng.txt)

**Comment by ivandrofly** [comment]
> Fix Common Errors does not offer this function either.
> 
> What I want is that:

I tested it with example you gave seems to be working without any problem...

`- Hello.
- Bye.`

becomes

`Hello.
- Bye.`

and

`- Hello.`

becomes

`Hello.`

**Comment by TMDaines** [comment]
Hi,

Are you able to try the subtitle file, which I uploaded? The plugin does not correctly amend the lines mentioned.

Kind Regards,

Thomas Daines

**Comment by TMDaines** [comment]
@ivandrofly 

That's odd. Could you please have a look at the file I uploaded?

If you run the plugin once (without ticking 'Strip all beginning hyphen'), you are then left with the following when you run the plugin again:

![image](https://cloud.githubusercontent.com/assets/13799044/16559590/c958b280-41e5-11e6-9d2e-631c26c57c24.png)

You still have lines with dashes at the beginning, for example 40, 55 and 81. To get of these opening dashes you need to tick 'Strip all beginning hyphen', but these strips dashes from the middle of other lines, for example 17 35, 63. This seems to be not be working as intended.

I only want opening dashes to be stripped and not any in the middle of a line.

**Comment by ivandrofly** [comment]
> I only want opening dashes to be stripped and not any in the middle of a line.

In order to remove the middle/beginning dash both lines have to contain dash, I'll update the plugin soon.

**Comment by ivandrofly** [comment]
The intention of the plugin was only to remove *hyphen* at the beginning of lines

**Comment by TMDaines** [comment]
Yes, that is correct. I would like all beginning hyphens/dashes to be removed and nothing else.

At the moment that does not happen unless you tick 'Strip all beginning hyphen', but this then removes dashes from middle of text, for example, where there is one at the beginning second piece of dialogue with a line break. These should stay

When I say **line**, I am referring to the numbered entries. For each of these numbered entries, I want the opening dash/hyphen removed and nothing else!

**Comment by ivandrofly** [comment]
> At the moment that does not happen unless you tick 'Strip all beginning hyphen', but this then removes dashes from middle of text, for example, where there is one at the beginning second piece of dialogue with a line break. These should stay

To remove first hyphen there must be a hypen after line break otherwise the hyphen won't be removed unless  'Strip all beginning hyphen' is checked.

**Comment by ivandrofly** [comment]
At the moment this plugin doesn't consider hyphen in middle of the text as 'narrator start dialog'.

**Comment by TMDaines** [comment]
OK, but 'Strip all beginning hyphen' seems to remove some hyphens that are not at the beginning and that introduce other lines. That's the problem I guess. I just want to remove all opening hyphens and those only.

**Comment by ivandrofly** [comment]
Work in progress...

**Comment by ivandrofly** [comment]
@TMDaines can you try this https://www.dropbox.com/s/yyeotieuzz8p6f3/DiaOneHyphen.zip?dl=0

**Comment by ivandrofly** [comment]
Update same link, can you test it again and let me know please. /cc @TMDaines

**Comment by TMDaines** [comment]
That's great. For some reason I had to run it twice for it to pick up lines 848 and 958, but it appears to catch them all now.

I will use further over the next week or so and will let you know if I discover any further issues.

@ivandrofly Thank you very much!

**Comment by ivandrofly** [comment]
Plugin updated, you can get the updated version via SE\Plugins... /cc @TMDaines
