### ISSUE TITLE
can not connect to google

### ISSUE THREAD

**Issue by heforfree** [SubtitleEdit/subtitleedit#1461]
error
System: The remote name could not be resolved: 'translate.google.com'

**Comment by xylographe** [comment]
Have you tried opening https://translate.google.com/ in your browser?

**Comment by heforfree** [comment]
yes it will open browser but seems don't make any connection with  SE.
I allowed it in firewall and security software.i suspect that was because UDP.i think it blocked by my isp.but not sure.if you can add option like use system p---r---o--_-x-y so i think it can help

**Comment by xylographe** [comment]
You might try to set *Options* **>** *Settings* **>** *Network* **>** *Proxy server settings*.

**Comment by heforfree** [comment]
don't make any connection
already try that.with this format
ip
or
host:port

**Comment by heforfree** [comment]
it seems windows problem tested in another pc and work thanks
