### ISSUE TITLE
[QUESTION] What is `&amp;` in translation files?

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1472]
There are also other XML entities like `&lt;` and `&gt;` that are normally translated to "<" and ">" in the interface, but ampersand occurs where it doesn't exist and usually in the middle of a word.

**Comment by xylographe** [comment]
The letter succeeding the ampersand is used as a keyboard accelerator by Windows. For example, if you set language to English, press (and release) `Alt` followed by `F` followed by `O`, the file selection dialogue will open (menu item *File* **>** *Open*).

Windows shows the accelerator keys underlined when you enter keyboard accelerator mode (by pressing and releasing the `Alt` key). Pressing `Esc` after `Alt` will exit keyboard accelerator mode.

Keyboard accelerators can also be used with buttons (eg. `&OK` makes `O` the accelerator key for the **OK** button).

**Comment by aaaxx** [comment]
Ah, of course. Thanks.

But how do you get an actual ampersand in the interface then? Doesn't it need escaping in XML?

**Comment by xylographe** [comment]
Two consecutive ampersands: `&Ot&&vori…` displays as **Ot&vori…** in the interface. The **O** will be underlined in keyboard accelerator mode. The **&** is just a regular character like the **t** and the **v**.

In hr-HR.xml `&Ot&&vori…` would be written `<Open>&amp;Ot&amp;&amp;vori…</Open>`.

XML entities are automatically converted when the XML file is loaded ([`XmlDocument.Load()`](https://msdn.microsoft.com/en-us/library/system.xml.xmldocument.load%28v=vs.110%29.aspx)).

**Comment by aaaxx** [comment]
Got it. One more thing: can I use normal XML comments `<!-- -->`?

**Comment by xylographe** [comment]
Translations are typically created/updated with [Xml Content Translator](http://www.nikse.dk/XmlContentTranslator), which doesn't preserve XML comments. Hence, adding comments to a translation would be fruitless.

**Comment by niksedk** [comment]
@xylographe: Very nice explanations :)
