### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sultan59** [SubtitleEdit/subtitleedit#1482]
![error](https://cloud.githubusercontent.com/assets/16682574/12290849/3bbdc1f6-b9e4-11e5-8dfb-b0b710e496c6.jpg)
I am an SE user. it is a very useful software. Bun now I can't use it because I receive the error message. Few days before I coud use it. I don't know what happned.
Best regards:
Dénes Zoltán

**Comment by xylographe** [comment]
- Do you use Windows 10, or something else?
- Do you use Subtitle Edit 3.4.10 build 0, or a different version (*Súgó* **>** *Névjegy*)?
- Does this "Arithmetic operation resulted in overflow" exception occur **each time** you select *Fájl* **>** *Új*?

**Comment by niksedk** [comment]
What happens if you run latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip (should at lease give a line number...)

**Comment by niksedk** [comment]
@Sultan59: Have you looked more at this?

**Comment by Sultan59** [comment]
Hello!
Thank you for your help. My problem was the error of the operating 
system. Eny nessesery file was deleted (not by myself). I installed my 
Win7 again and it is working properly. Thank you for yor qick help. I 
like use your program, because very simply and I can resolve any project 
with it.
Best regards:
DÉNES, Zoltán


2016.01.21. 10:34 keltezéssel, Nikolaj Olsson írta:
>
> @Sultan59 <https://github.com/Sultan59>: Have you looked more at this?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SubtitleEdit/subtitleedit/issues/1482#issuecomment-173515683>.
>



---
Ezt az e-mailt az Avast víruskereső szoftver átvizsgálta.
https://www.avast.com/antivirus
