### ISSUE TITLE
Subtitles editing

### ISSUE THREAD

**Issue by luizabauer** [SubtitleEdit/subtitleedit#1486]
I am looking to download the subtitle edit and I cannot ......am I that thick that cannot get the grip of this? is it I have to download all those zip files under?
thank you

**Comment by niksedk** [comment]
Just download the installer: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEdit-3.4.11-Setup.zip

**Comment by luizabauer** [comment]
thank you ....I will try it now. I am not very good with techy stuff. Thank you

Yes I have installed it. N thank you very much. Could I bother you with another question about what now?

**Comment by niksedk** [comment]
Sure, but do take a look at these first:
http://www.nikse.dk/SubtitleEdit/Help
https://www.youtube.com/results?search_query=subtitle+edit
