### ISSUE TITLE
Error at windows 32-bit

### ISSUE THREAD

**Issue by ecikurcaci** [SubtitleEdit/subtitleedit#1491]
hello~ 
I get this message . 
![capture](https://cloud.githubusercontent.com/assets/16760461/12393705/f65b9490-be29-11e5-9b45-c71b3351dfee.PNG)
I use windows 32bit . SE doesn't work on 32bit? I'm already try all version but the message stil 
appear. What should I do?
Thanks

**Comment by heforfree** [comment]
install ,net frame work 4.0 or higher version

**Comment by ecikurcaci** [comment]
work it. thank you for help :)

**Comment by ecikurcaci** [comment]
work it. thank you for help :)
