### ISSUE TITLE
[Feature Request] Apply button to HI removal window

### ISSUE THREAD

**Issue by Splike** [SubtitleEdit/subtitleedit#1496]
When I am using the hearing impaired removal feature, I tend to be careful not to remove anything important. This means that I remove lines over several steps, checking and un-checking the different options available.

Right now, your can confirm the changes by hitting the "OK" button, but this closes the window. Which means I have to re-open the window for every change I make.

I'd like either an Apply button, which will do the same as OK, but keep the window open. Or just leave the window open after hitting OK.

**Comment by aaaxx** [comment]
ivandrofly, in case you're in the mood for some more coding, another thing that would be useful here is highlighting of the bits that will be removed (highlighting background would be better than changing letter colour because it shows spaces).

**Comment by Splike** [comment]
That's a good idea! Kinda like how Github shows code changes.
