### ISSUE TITLE
OCR Promt after its finished.

### ISSUE THREAD

**Issue by shogunreaper** [SubtitleEdit/subtitleedit#1504]
So i was using the ocr import feature and thought it was incredible annoying that i had to baby sit the window throughout the entire process.

Wouldn't it be much better to let the program fix all the lines it can first and then prompt the ones it can't afterwards?

**Comment by Splike** [comment]
I sat through all six star wars movies doing this... I would very much also like this implemented.

**Comment by shogunreaper** [comment]
?

**Comment by PannenkoekenNL** [comment]
Me too.
