### ISSUE TITLE
SubRip (SRT) feature request: Remove all special formatting, like italic, bold or colored text

### ISSUE THREAD

**Issue by Zack-od-Bins** [SubtitleEdit/subtitleedit#1507]
All special formatting of SubRip (SRT) subs, like italic, bold or colored text, will only show as their formatting when playing a movie, or worse, cause a crash. This is, when they are not burned in, but merely included as stream in MKV's. This appears to be specific to some players, like DVD, Bluray or TV-USB media players. Perhaps because some manufacturers use cheap versions of codecs, although I wouldn't know how it's possible for them to (want to) deviate from standards, like H.264. Sometimes it will cause a movie not to play at all. 

The only solution I can come up with is the replacing of all special formatting by plain text. Burning in is no option for me, since my MKV's are with multi languages subs which must be switchable. 

So, is it possible to please add this as a feature to SubtitleEdit ?

**Comment by ivandrofly** [comment]
@Zack-od-Bins  you can remove all special formatting by select all text by `Right click  + Normal (remove all formatting)` I hope this answer your question :)
