### ISSUE TITLE
Re: past issue #1300, additional question

### ISSUE THREAD

**Issue by kailia** [SubtitleEdit/subtitleedit#1510]
Hi, for command-line fixing of subrip subtitles without conversion (a feature I requested some time ago and was graciously executed - thanks for that), I've got it to work using the following command line only: 
"C:\Program Files (x86)\Subtitle Edit\SubtitleEdit.exe" /convert *.srt subrip /fixcommonerrors /removetextforhi /overwrite
... is this how it's supposed to work ? I make it believe I'm converting to and from "subrip" ?
Additionally, could you add the "multiple replace" feature (from Batch convert) to command line as well ?

**Comment by xylographe** [comment]
You *are* converting from SubRip to SubRip. The input files are parsed into internal data structures. FCE and RHI are performed, then the output files are generated in SubRip format from the internal data structures.

Multiple replace from command line should work in [SubtitleEdit-3.4.12.117-issue1510.7z:](https://www.dropbox.com/s/z6ed9h07hwcv68i/SubtitleEdit-3.4.12.117-issue1510.7z?dl=1)
  The switch is named `/multiplereplace`.
  Only the replace rules from `Settings.xml` are used, importing is not (yet) supported.

**Comment by kailia** [comment]
Great, thanks ! 

Sent from my iPhone

On 14 Apr 2016, at 22:52, xylographe <notifications@github.com> wrote:

You are converting from SubRip to SubRip. The input files are parsed into internal data structures. FCE and RHI are performed, then the output files are generated in SubRip format from the internal data structures.

Multiple replace from command line should work in SubtitleEdit-3.4.12.117-issue1510.7z:
The switch is named /multiplereplace.
Only the replace rules from Settings.xml are used, importing is not (yet) supported.
