### ISSUE TITLE
Random failure to replace characters near accentuated ones or that are accentuated

### ISSUE THREAD

**Issue by kurosu** [SubtitleEdit/subtitleedit#1515]
When performing spell check, and whether using the suggestions from a French language dictionary (correctly set), or manual correction, words with the same faulty character randomly fail.

I haven't tested with other languages.

For instance, at the start of a line or sentence, the characters like E and e, which are to be replaced by respectively É and é when performing the action, are actually not replaced.

Also, when trying to replace Ià by là, the word isn't corrected.

In the attached file, lines 15 (containing Ià instead of là) and 181 (containing Etats instead of États) are affected.

[example.zip](https://github.com/SubtitleEdit/subtitleedit/files/110816/example.zip)

EDIT: tested with a84c33a / 3.4.11

**Comment by niksedk** [comment]
Latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBetaTest.zip

**Comment by kurosu** [comment]
Confirm fixed, thanks.
