### ISSUE TITLE
SHD removal fix

### ISSUE THREAD

**Issue by Thunderbolt8** [SubtitleEdit/subtitleedit#1519]
in combination with italics

works fine:

\- (CROWD JEERING)|- SANDY: < i >Go, hard.< /i >

==>

< i >Go, hard.< /i >

does not work when these kind of lines are placed the other way round. the hyphen remains:

\- NORA: < i >Sir?< /i >|- (CAR DOOR CLOSES)

==>

< i >- Sir?< /i >

**Comment by Thunderbolt8** [comment]
Another one:

- Well, received, technically.|- KEVIN: < i >Mmm-hmm.< /i >

==>

- Well, received, technically.|< i >< /i >

(Mmm-hmm is on my remove interjections list)

**Comment by aaaxx** [comment]
Just a note: you can use backslash to escape hyphens at the beginning of lines and prevent Markdown from automatically converting them to bulleted lists.

For example, typing this
<pre>\- (CROWD JEERING)|- SANDY: < i >Go, hard.< /i ></pre>
turns into this

\- (CROWD JEERING)|- SANDY: < i >Go, hard.< /i >

**Comment by Thunderbolt8** [comment]
thanks
