### ISSUE TITLE
App breaks down every 5 seconds

### ISSUE THREAD

**Issue by Visub** [SubtitleEdit/subtitleedit#1522]
The app, installed on Windows 7, beaks down every 5 or 15 seconds. Latest 3.4.11 version. 
![error_screenshot](https://cloud.githubusercontent.com/assets/16993231/12705224/bc2e6094-c875-11e5-9989-ca55a06eaa61.jpg)

**Comment by ivandrofly** [comment]
According to [this site](http://www.infoworld.com/article/2925777/microsoft-windows/microsoft-issues-patch-kb-3065979-to-fix-win7-gdi-drawing-problems-brought-on-by-kb-3045171.html) the issue with GDI+ is a bug present in **patch 3045171**...

**Comment by OmrSi** [comment]
@niksedk Also closed?
