### ISSUE TITLE
Arabic-English issue

### ISSUE THREAD

**Issue by omarmrizk** [SubtitleEdit/subtitleedit#1523]
whenever I write an arabic word then an english it starts the english word at the begining of the line
for example : 
كلمةword
it should be like this:
wordكلمة
and so on 
I hope that I've presented my issue clearly .
for any other details please contact me on maromaro612@gmail.com
thank you ..

**Comment by heforfree** [comment]
use edit menu fix RTL via Unicode control character
and or select right to left mode
