### ISSUE TITLE
[Smells] - SpellCheckWordLists

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1527]
Bug? https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/SpellCheck/SpellCheckWordLists.cs#L323

``` c#
            var s = "foobar";
            var sb = new StringBuilder();
            for (int i = 0; i < s.Length; i++)
            {
                sb.Append(s[i]);
            }
            if (sb.Length > 0)
                Console.WriteLine(s.Length - 1 - sb.Length);
            Console.ReadLine();
```
**Output:** -1
I think that -1 shouldn't be there :confused:, right?

**Comment by xylographe** [comment]
Logically it would be `Index = ( (s.Length - 1) - sb.Length ) + 1`, I believe, which could be simplified to `Index = s.Length - sb.Length`
