### ISSUE TITLE
Only one subtitle track seen in XML file with more subtitle tracks

### ISSUE THREAD

**Issue by RealGreenDragon** [SubtitleEdit/subtitleedit#1532]
HI!

I tried to convert an XML subtitle file to ASS format.
But the XML file contains more subtitle tracks, and the program see only the first.

It is normal or is a bug??

**Comment by niksedk** [comment]
Hard to say without the actual subtitle... could you post or email it?

**Comment by MagicGreenDragon** [comment]
I sent you the xml file by email.

**Comment by niksedk** [comment]
I've tried to fix the issue here: https://github.com/SubtitleEdit/subtitleedit/commit/c6411bf6fb7043661df697c73f82b741d8bd5180 - can be tested here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBeta.zip

**Comment by MagicGreenDragon** [comment]
I tried the new version, and it fix the reading bug, but put all the tracks into the same file!
In this way, when I tried to convert the XML file to other format (for example ASS or SRT), each subtitle of each track (the file contains the same subtitle track in different languages) in the video is showed simultaniously!

Can you edit for save the XML multiple tracks in different files (based on the track title, that in this case is the language) when is exported in other formats (for example ASS or SRT)?
