### ISSUE TITLE
Minor BDN/XML capitalization bug

### ISSUE THREAD

**Issue by jaysedai** [SubtitleEdit/subtitleedit#1546]
Sony Blu-print rejects files exported in Subtitle Edit because False and True are capitalized like this:
DropFrame="False" or DropFrame="True"

I have to manually change to "DropFrame="false"  or "true" in order for Blu-print to work with the file.

**Comment by niksedk** [comment]
Could you attach or email a 'correct' BDN/XML file?
SE uses the same syntax a BdSup2sub...
