### ISSUE TITLE
JSON order of keys

### ISSUE THREAD

**Issue by fela98** [SubtitleEdit/subtitleedit#1555]
When you provide a JSON file generated from another program, it's not always compatible with SubtitleEdit.

Only if the keys (ie. "start", "end" and "text") come in the right order, the file is correctly parsed. However other programs may provide the keys in a different order.

See the introduction of the [JSON rfc](http://www.rfc-editor.org/rfc/rfc7159.txt), there it states the following:

>  An object is an **unordered** collection of zero or more name/value
   pairs

Which means that the order of the keys should be insignificant if you want to adhere to the RFC.

**Comment by niksedk** [comment]
Could you provide a file not compatible with SE? (either here or by email)

**Comment by fela98** [comment]
Hete an example, egen i open this in SE i Get an erter while parsing:
`[{"text": "This does not work","start":1,"end":2}]`

If I however place the text after the start and end properties it works.

**Comment by niksedk** [comment]
thx for the info -  could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBeta.zip
Hopefully fixed via this commit: https://github.com/SubtitleEdit/subtitleedit/commit/8fcf78f9081cc59ce468bc64eba48f269d3ef89a

**Comment by fela98** [comment]
Yes, this is fixed in the latest beta.
