### ISSUE TITLE
 (SE 3.4.11) SRT file can't be overwritten anymore while in use by VLC because file is locked.

### ISSUE THREAD

**Issue by Whisker72** [SubtitleEdit/subtitleedit#1562]
When watching a video with VLC and editing a .srt file which is also displayed in VLC, it's not possible to edit the same .srt file and save it as long as VLC is running. Instead, Subtitle Edit v3.4.11 shows an error message that the file is locked and can't be saved under the same name.
(VLC used is the 64-bit 2.2.1 "Terry Prattchet (Weatherwax)" release and hasn't changed for months.)

I remember this issue from a veeery old version of SE many years ago (sorry, can't remember which one, I think it wasn't even a 3.* version of SE), but this hasn't been a problem for years now.

And I just tested it with SE 3.4.10. The problem doesn't exist there, an .srt file can be overwritten over and over again while it is used by VLC at the same time and if reloaded in VLC, the changes made are shown.

**Comment by ivandrofly** [comment]
@Whisker72 the problem is not with Subtitle Edit, this issue should be reported to VLC team. VLC stream subtitle while playing instead of reading it to memory and display.

**Comment by niksedk** [comment]
Should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBeta.zip

(read access was missing - was removed by mistake when I added the "FileOptions.WriteThrough" to avoid issues with power failure)

**Comment by ivandrofly** [comment]
:+1: @niksedk

**Comment by Whisker72** [comment]
@niksedk Kudos, mate!

Just one question remains: I downgraded to 3.4.10 because the bug didn't exist back there, and I'm normally using the installer.
So should I just update to 3.4.11 via installer and then overwrite all files with the ones from the ZIP, or do I just need to copy (and maybe overwrite) certain files?

TIA

**Comment by niksedk** [comment]
Hm, try this one: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBetaSetup.zip

**Comment by Whisker72** [comment]
Yep, works. Great!  :ok_hand:
