### ISSUE TITLE
Installer associates .srt with SE even when the user doesn't choose so (and, in the installer the relevant checkbox is unchecked by default)

### ISSUE THREAD

**Issue by darkred** [SubtitleEdit/subtitleedit#1569]
Using win10x 64.

During installation of  SubtitleEdit-3.4.11-Setup.exe :
![http://i.imgur.com/VpxQPFA.png](http://i.imgur.com/VpxQPFA.png)
i.e. `Assosiate SubRip Text (.srt) with Subtitle Edit` is unchecked by default. 
I don't check it, neither.

After the installation finishes, .srt files are associated with SE.

**Comment by xylographe** [comment]
Are `.sup` and `.sub` files also associated with SE?

**Comment by darkred** [comment]
Yes.

**Comment by xylographe** [comment]
Thanks!

The SE installer registers these three file types (`.srt/.sup/.sub`) as being **supported** by SE. The `.sup` and `.sub` file types are never **associated** with SE, users may choose to do so, if required, in Explorer/ControlPanel. The `.srt` file type will be associated with SE on demand (if the option in the installer is checked).

It would seem that Win10 works different from its predecessors: automatically associating a file type, if the file type is only supported by one program. I haven't found appropriate documentation on MSDN yet, but hopefully there is some way to prevent this behaviour.

**Comment by xylographe** [comment]
@darkred Sorry about the long delay.
Could you please test `SE-3.4.11-WinX01-setup.exe` from [this folder:](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)

- Install SE with `Assosiate SubRip Text (.srt) with Subtitle Edit` **checked**
- Check 1: `.srt` files are associated with SE.
- Check 2: `.sup` (or `.sub`) files are NOT associated with SE.
- Check 3: When right-clicking a `.sup` (or `.sub`) file in Explorer to open the context menu, Subtitle Edit is shown in the `Open with` submenu.
- Install SE with `Assosiate SubRip Text (.srt) with Subtitle Edit` **unchecked**
- Check 4: `.srt` files are NOT associated with SE.

**Comment by darkred** [comment]
[**@xylographe**](https://github.com/xylographe) commented on [Mar 13, 2016, 4:17 PM GMT+2](https://github.com/SubtitleEdit/subtitleedit/issues/1569#issuecomment-195963384 "2016-03-13T14:17:40Z - Replied by Github Comment Enhancer"):
> [@darkred](https://github.com/darkred) Sorry about the long delay.  
> 
> Could you please test `SE-3.4.11-WinX01-setup.exe` from [this folder:](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)
Ok.
In both cases, I run the application right after the installation finishes. So:



> *   Install SE with `Assosiate SubRip Text (.srt) with Subtitle Edit` **checked**
> 
> *   Check 1: `.srt` files are associated with SE.
> *   Check 2: `.sup` (or `.sub`) files are NOT associated with SE.
> *   Check 3: After right-clicking a `.sup` (or `.sub`) file in Explorer to open the context menu, Subtitle Edit is shown in the `Open with` submenu.
No, all 3 extensions DO get associated.
And, the `open with` (expandable) submenu only appears for `.srt` files. 
For the other two it shows `Open with...` (which cannot be expanded) instead.

> *   Install SE with `Assosiate SubRip Text (.srt) with Subtitle Edit` **unchecked**
> 
> *   Check 4: `.srt` files are NOT associated with SE.
No, they DO get associated

**Comment by xylographe** [comment]
@darkred Ty for testing.

In a last attempt to fix this issue, I can think of two more register settings that might make a difference. The test-installer is **`SE-3.4.11-WinX02-setup.exe`** from [the same folder.](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0) The `Assosiate SubRip Text (.srt) with Subtitle Edit` option does not affect the register settings. Each of the three extensions (`srt/sup/sub`) is treated slightly different, in the hope that at least one of them will behave as required.

Hence, the questions for all three extensions are:
- Does the extension get associated with Subtitle Edit?
- Does the `Open with` (expandable) submenu contain `Subtitle Edit`?

**Comment by darkred** [comment]
Now, in both cased, i.e. either having `Assosiate SubRip Text (.srt) with Subtitle Edit` checked or unchecked:
from the 3 extensions, only `.srt` gets associated, 
and the `Open with` (expandable) submenu does contain Subtitle Edit

**Comment by xylographe** [comment]
Thanks, @darkred 

If PR #1633 is accepted, the installer will work like [**SE-3.4.11-assoc-fix-setup.exe**](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0) (under any Windows version >= XP).
