### ISSUE TITLE
Support for mpv

### ISSUE THREAD

**Issue by emk2203** [SubtitleEdit/subtitleedit#1579]
Is support for mpv planned? mplayer/mplayer2 are stagnant, mpv is the successor of mplayer under active development. It would benefit all versions of SubtitleEdit (Linux, Windows).

**Comment by niksedk** [comment]
https://mpv.io/ looks very interesting! 
I never liked the mplayer/mplayer2 slave mode, but this new C API sounds really good! 

Does anybody know if the api dll is available anywhere?

**Comment by emk2203** [comment]
Isn't this libmpv.dll? https://github.com/mpv-player/mpv-build talks about it at the bottom (next-to-last).

**Comment by niksedk** [comment]
Found another link: https://github.com/mpv-player/mpv/tree/master/DOCS/client_api_examples
The dll is included in the DEV builds: https://mpv.srsfckn.biz/

**Comment by niksedk** [comment]
Could anybody try to test mpv support in this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBeta.zip
(win64 bit only for now)

**Comment by aaaxx** [comment]
Works fine for me except with Blu-ray .m2ts files; they are loaded and show the length, but won't start playing.

Other than that, sound is always muted by default when you load a new file, and there's a black bar under the video that seems to be for displaying subtitles instead of placing them on top of the video.

![black bar under the video](https://cloud.githubusercontent.com/assets/6186480/13375457/3c608ffa-dda0-11e5-8398-90706c53d9b1.jpg)

**Comment by niksedk** [comment]
@aaaxx: thx for testing :)
Yeah, seems to have issues with some transport stream files...
On the plus side "seeking" is very precise which is nice when working with waveform :)

Sorry, I don't know how to display subtitles "on top of the video"... if anybody can do that do let me know ;)

**Comment by niksedk** [comment]
@aaaxx  + others: Could you test this updated beta with mpv: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBeta.zip
You can now change the video output engine (Options -> settings -> Video player). "vdpau" seems to work for transportstreams here...
Muted sound at startup should be fixed.

**Comment by aaaxx** [comment]
After exiting SE without closing the video file, the next time it's run it will have the video loaded and paused at 00:02:15,[ms different for different files].

And while you're fiddling with this, could you take a look at issue https://github.com/SubtitleEdit/subtitleedit/issues/1335?

**Comment by niksedk** [comment]
Support for mpv is available in 3.4.12: https://github.com/SubtitleEdit/subtitleedit/releases/tag/3.4.12
