### ISSUE TITLE
Audio extraction issues if repeat or shuffle is enabled in VLC

### ISSUE THREAD

**Issue by davidzou2131** [SubtitleEdit/subtitleedit#1580]
### Repeat (Loop one) Issue
If repeat (loop one) is turned on in VLC, audio extraction when generating waveform/spectrogram will never finish. The temporary `.wav` file that VLC generates simply resets to 0 bytes as the whole process starts again, repeating indefinitely.

### Loop (Repeat all) Issue
If loop (loop all) is turned on in VLC, audio extraction when generating waveform/spectrogram will fail, informing us to check free space. The temporary `.wav` file that VLC generates is reset to 0 bytes in size.

### Random (Shuffle) Issue
If random (shuffle) is turned on in VLC, audio extraction when generating waveform/spectrogram will fail 50% of the time, informing us it could not find the extracted `.wav` file. VLC shuffles the queue/playlist and `vlc://quit` is executed before the transcoding 50% of the time.

### Steps to reproduce
1. Open VLC
2. Enable loop all or repeat one
3. Close VLC to save preferences.
4. Generate waveform/spectrogram in SubtitleEdit
5. Observe indefinite/failed extraction

### Solution
Add `--no-random`, `--no-repeat` and `--no-loop` to the arguments when extracting waveform with VLC.

<hr>
Windows 7 64, SE 3.4.11, VLC 2.2.2

**Comment by niksedk** [comment]
thx for the info :)
Latest beta updated to include these fixes: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBeta.zip

**Comment by davidzou2131** [comment]
Thanks. Beta works a treat :)
