### ISSUE TITLE
Project builds every time I try to debug/run the project.

### ISSUE THREAD

**Issue by rsarang** [SubtitleEdit/subtitleedit#1583]
Project builds every time since some resources in the .csproj file have the CopyToOutputDirectory set to Always,
Example:
`<Content Include="Icons\Find.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>`
and
`<Content Include="Languages\ar-EG.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>`

This causes a the build.
![subtitleedit - microsoft visual studio](https://cloud.githubusercontent.com/assets/6271469/13205055/81808db0-d904-11e5-941b-32bae131b1e8.png)

Resolution:
Change all `<CopyToOutputDirectory>Always</CopyToOutputDirectory>`
to `<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>`
in the SubtitleEdit.csproj file.

**Comment by rossi9** [comment]
Reference: [http://stackoverflow.com/questions/14916729/visual-studio-rebuilds-unmodified-projects](url)
