### ISSUE TITLE
Issue of BDN XML / PNG for Netflix

### ISSUE THREAD

**Issue by snakeLo** [SubtitleEdit/subtitleedit#1585]
When I was using SE 3.4.11, open the xml file, it will pop up the window automatically to tell me to OCR but without pictures and timelines.

However, when using SE 3.4.10, open the xml file, even though it won't load the pic but it got timelines, so I can first export them to BDN/XML to a new folder, then modify the generated xml file and put it back in the original file folder, open the xml file and it work properly.

Can you solve it?

You can download an example file from below link
http://so1.akam.nflximg.com/soa7/562/0a1567216a1c1353fc316188b184e301.isc/range/

Thanks in advance

**Comment by niksedk** [comment]
Latest beta updated to include this fix: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBeta.zip

**Comment by snakeLo** [comment]
That was fast and it works perfect. Thank you so much.
Looking forward to the official release of 3.4.12 :)

**Comment by shad00m** [comment]
How did you get a hold of that isc/zip ? Bluestacks and Andy didn't seem to work with netflix.
