### ISSUE TITLE
error message: "An item with the same key has already been added"

### ISSUE THREAD

**Issue by montillasauces** [SubtitleEdit/subtitleedit#1591]
Hi,

This error message appears in Subtitle Edit when I open it:
"An item with the same key has already been added"

See below screenshot with the problem.

Thanks!

![error_sub_edit](https://cloud.githubusercontent.com/assets/17450438/13283118/24a60066-dae4-11e5-908a-c73462c499aa.jpg)

**Comment by xylographe** [comment]
Because the ST line starts with `<i></i><i>6 `, `italicLookups.Add(italicBegin, ...)` is invoked twice with `italicBegin == 0` (`italicBegin` is not increased between the first `<i>` and the second `<i>`).

**Comment by niksedk** [comment]
thx guys :)
Latest beta should be updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBeta.zip

**Comment by montillasauces** [comment]
Thanks xylographe. It solved the problem
