### ISSUE TITLE
Error Message:'l-', hexadecimal value 0x19, is an invalid character 

### ISSUE THREAD

**Issue by SuzyF** [SubtitleEdit/subtitleedit#1592]
Hi there,
I've received the error message about whenever a new file is open in Subtitle Edit.
Please help, thank you!!

![subtitle edit error](https://cloud.githubusercontent.com/assets/17451264/13284255/18b12368-db2e-11e5-8efb-49f1cc1d15ca.JPG)

**Comment by xylographe** [comment]
ASCII 25 (U+0019) is the EM (end of medium) control character. Apparently, it is (but shouldn't be) part of a SE Settings string. Unfortunately, the stack trace doesn't show which Setting string causes the problem.

Perhaps, you can try renaming the `Settings.xml` file (usually in `%APPDATA%\Subtitle Edit`) before starting SE.
