### ISSUE TITLE
.stl not saving changes.

### ISSUE THREAD

**Issue by sutai** [SubtitleEdit/subtitleedit#1604]
Hello. I don't know if it's just me being dumb, or if it's a bug, but I have tried changing the timing on .stl subtitles using Subtitle Editor, and sometimes they don't save. For example, if I run the "fix common errors" thing it fixes everything, but when I save the file and open it again, some of the changes seem to disappear. Can someone help me with this? I've tried with a few different video files, tried changing the ebu.stl settings, basically everything I could think of.

Thanks.

**Comment by niksedk** [comment]
Really hard to say without a concrete example... (also multiple stl formats exists). 
My guess is that your format is frame based - and SE will suggest minor timing corrections which will be lost when saved in a frame based format.
