### ISSUE TITLE
[request] allow cmdline conversion by specifing output filename only

### ISSUE THREAD

**Issue by eadmaster** [SubtitleEdit/subtitleedit#1609]
For instance:
`    SubtitleEdit.exe /convert input.srt output.smi`

Will guess the correct output format from the "output.smi" filename extension (like ffmpeg does).

**Comment by niksedk** [comment]
Sorry, subtitle edit supports 200+ formats and actually most formats use extensions like .txt, .cap, .xml, .stl, and .sub...
