### ISSUE TITLE
[SubtitleFormat] - Subtitle formats with expensive IsMine

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1611]
Format-Name: Unknown 41                              , Time: 42312863

Format-Name: SubRip                                  , Time: 608568

Format-Name: Final Cut Pro Xml                       , Time: 102709

Format-Name: Final Cut Pro X Chapter Marker          , Time: 70029

Format-Name: Final Cut Pro X Xml                     , Time: 62497

Format-Name: Unknown 59                              , Time: 62017

Format-Name: Belle Nuit Subtitler                    , Time: 60458

Format-Name: FLVCoreCuePoints                        , Time: 58736

Format-Name: Adobe Encore (tabs)                     , Time: 57681

Format-Name: Final Cut Pro Test Xml                  , Time: 53382

Format-Name: YouTube Transcript one line             , Time: 53202

Format-Name: Final Cut Xml Gap                       , Time: 49347

Format-Name: Final Cut Pro Test2 Xml                 , Time: 46751

Format-Name: Avid DVD                                , Time: 44257

Format-Name: WebVTT File with#                       , Time: 43916

Format-Name: Unknown 67                              , Time: 41830

Format-Name: WebVTT                                  , Time: 41804

Format-Name: SubViewer 2.0                           , Time: 36117

Note: **Time = ElapsedTicks**. Tested with **.SRT** (Main format)

**Comment by niksedk** [comment]
These tests sound weird to me (unless you have a really really slow computer). I've tested this on a regular bases with VS Perf tester to find the slowest ones. I can run a bad format file (100k) through all 200+ formats in less that half a second... and just Unknown 41 takes more than 4 seconds for you. 

Also, do please display results in "milliseconds"!
