### ISSUE TITLE
Request: please add Multiple Replace to command-line processing

### ISSUE THREAD

**Issue by kailia** [SubtitleEdit/subtitleedit#1655]
Hi,

would it please be possible to add the Multiple Replace function to command-line processing ? I can now perform basic SRT cleanup (Remove Hi, fix errors) since a few versions ago (thx for that !), right now the only thing I'm missing is the ability to perform a Multiple Replace at the same time. I use that to remove ads from websites, tv channels, etc. from the SRTs.

**Comment by niksedk** [comment]
@kailia / @xylographe: xylographe has fixed this I believe - you can try out latest beta here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip
