### ISSUE TITLE
Request: Please publish app in Windows Store using .NET bridge

### ISSUE THREAD

**Issue by RidleyDragon** [SubtitleEdit/subtitleedit#1671]
https://developer.microsoft.com/en-us/windows/bridges/desktop

Nice tile and auto-update from store will be big advantage.

And of course program's range for new users will be better, if SubtitlesEdit could be found in Store.

**Comment by RidleyDragon** [comment]
Converter has been published: https://www.microsoft.com/en-us/download/details.aspx?id=51691
Looks like this is working since Redstone 1, not TH2.

**Comment by dihmandrake** [comment]
Are there any News or plans on that?
