### ISSUE TITLE
[ENHANCEMENT] Treat newline as space when searching

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1673]
This would be really handy when searching for multiple words or phrases (normal search, not regex). Although I don't know what would be the best way to handle replacing such matches.

Actually, it might be a good idea to make all Unicode [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character) match a normal space.

**Comment by xylographe** [comment]
I'm afraid I can't see the benefits. Regex search **`\bword1\s+word2\b`** will do this.

Perhaps, some new search mode that allows **`("word1" and "word2") or /a[bcd]+e/`** : find subtitles that contain both words (in any order), and subtitles that match the regex pattern.
Only in the Find dialogue, of course, not in Replace.

**Comment by aaaxx** [comment]
Well the idea is to easily find a string if it exists in the file without having to worry about formatting (especially for non advanced users).

But, since you mention a new mode, maybe a completely normalized search would be a good idea, like disregarding diacritics and treating smart quotes/apostrophe as straight ones, in addition to newlines treated as spaces.
