### ISSUE TITLE
[BUG] Language parsing in idx/sub: old DVD language codes

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1675]
It seems that DVD specification uses some deprecated version of ISO 639-1 for setting language codes, which messes up the language selection dropdown box in SE's Import Vobsub dialog. What happens is the track with the unknown code takes the Language name of the following track, which ripples down the rest of the list pulling all other track names out of sync, and the final track then gets marked as "Unknown language". [Here's a sample file](https://app.box.com/s/65yeki4js0wwlcib3x89mo7onrwz8uc2) with Hebrew (iw) being the offender.

I compared the list of language codes used by the DVD spec (see [p. 186 here](https://books.google.hr/books?id=vMQqBgAAQBAJ&pg=PA186&lpg=PA186&dq=dvd+language+codes&source=bl&ots=sCbvvBiQqR&sig=TOtHPhduInxjp96xJkEQhFJ4kp0&hl=en&sa=X&ved=0ahUKEwi8nvvMpe_LAhXG7hoKHSaaALsQ6AEIMTAI#v=onepage&q=dvd%20language%20codes&f=false) or [p. 525 here](https://www.american.edu/soc/resources/upload/DVD-Studio-Pro-4-User-Manual-en.pdf)) with the current ISO 639-1 and these are the differences:

<table>
	<thead>
		<tr> <th>DVD code</th>  <th>ISO 639-1</th>  <th>Language name</th>  <th>Change notice</th> </tr>
	</thead>
	<tbody>
		<tr> <td>in</td> <td>id</td> <td>Indonesian</td> <td>changed 1989-03-11</td> </tr>
		<tr> <td>iw</td> <td>he</td> <td>Hebrew</td>     <td>changed 1989-03-11</td> </tr>
		<tr> <td>ji</td> <td>yi</td> <td>Yiddish</td>    <td>changed 1989-03-11</td> </tr>
		<tr> <td>jw</td> <td>jv</td> <td>Javanese</td>   <td>“jw” published in error; withdrawn in favor of “jv”, 2001-08-13</td> </tr>
		<tr> <td>mo</td> <td>ro</td> <td>Romanian</td>   <td>“mo” for Moldavian has been withdrawn, recommending “ro” also for Moldavian, 2008-11-03</td> </tr>
		<tr> <td>sh</td> <td>bs</td> <td>Bosnian</td>    <td>Serbo-Croatian was deprecated in 2000 in favor of separate codes for each individual language (Serbian, Croatian, and then Bosnian was added), 2000-02-18 <br/> [since Serbian and Croatian were already present in the old DVD code list it’s probably best to map it to Bosnian]</td> </tr>
	</tbody>
</table>

And here's the full list of DVD codes in case someone needs it for future reference:

<table>
	<thead>
		<tr> <th>Language name</th>                       <th>Code</th>  <th>Hex</th>   <th>Decimal</th>    <th>Native name</th> </tr>
	</thead>
	<tbody>
		<tr> <td>Abkhaz</td>                              <td>ab</td>    <td>6162</td>  <td>24930</td>      <td>аҧсуа бызшәа, аҧсшәа</td> </tr>
		<tr> <td>Afar</td>                                <td>aa</td>    <td>6161</td>  <td>24929</td>      <td>Afaraf</td> </tr>
		<tr> <td>Afrikaans</td>                           <td>af</td>    <td>6166</td>  <td>24934</td>      <td>Afrikaans</td> </tr>
		<tr> <td>Albanian</td>                            <td>sq</td>    <td>7371</td>  <td>29553</td>      <td>Shqip</td> </tr>
		<tr> <td>Amharic</td>                             <td>am</td>    <td>616D</td>  <td>24941</td>      <td>አማርኛ</td> </tr>
		<tr> <td>Arabic</td>                              <td>ar</td>    <td>6172</td>  <td>24946</td>      <td>العربية</td> </tr>
		<tr> <td>Armenian</td>                            <td>hy</td>    <td>6879</td>  <td>26745</td>      <td>Հայերեն</td> </tr>
		<tr> <td>Assamese</td>                            <td>as</td>    <td>6173</td>  <td>24947</td>      <td>অসমীয়া</td> </tr>
		<tr> <td>Aymara</td>                              <td>ay</td>    <td>6179</td>  <td>24953</td>      <td>aymar aru</td> </tr>
		<tr> <td>Azerbaijani</td>                         <td>az</td>    <td>617A</td>  <td>24954</td>      <td>azərbaycan dili</td> </tr>
		<tr> <td>Bashkir</td>                             <td>ba</td>    <td>6261</td>  <td>25185</td>      <td>башҡорт теле</td> </tr>
		<tr> <td>Basque</td>                              <td>eu</td>    <td>6575</td>  <td>25973</td>      <td>euskara, euskera</td> </tr>
		<tr> <td>Belarusian</td>                          <td>be</td>    <td>6265</td>  <td>25189</td>      <td>беларуская мова</td> </tr>
		<tr> <td>Bengali, Bangla</td>                     <td>bn</td>    <td>626E</td>  <td>25198</td>      <td>বাংলা</td> </tr>
		<tr> <td>Bihari</td>                              <td>bh</td>    <td>6268</td>  <td>25192</td>      <td>भोजपुरी</td> </tr>
		<tr> <td>Bislama</td>                             <td>bi</td>    <td>6269</td>  <td>25193</td>      <td>Bislama</td> </tr>
		<tr> <td>Breton</td>                              <td>br</td>    <td>6272</td>  <td>25202</td>      <td>brezhoneg</td> </tr>
		<tr> <td>Bulgarian</td>                           <td>bg</td>    <td>6267</td>  <td>25191</td>      <td>български език</td> </tr>
		<tr> <td>Burmese</td>                             <td>my</td>    <td>6D79</td>  <td>28025</td>      <td>ဗမာစာ</td> </tr>
		<tr> <td>Catalan</td>                             <td>ca</td>    <td>6361</td>  <td>25441</td>      <td>català</td> </tr>
		<tr> <td>Chinese</td>                             <td>zh</td>    <td>7A68</td>  <td>31336</td>      <td>中文 (Zhōngwén), 汉语, 漢語</td> </tr>
		<tr> <td>Corsican</td>                            <td>co</td>    <td>636F</td>  <td>25455</td>      <td>corsu, lingua corsa</td> </tr>
		<tr> <td>Croatian</td>                            <td>hr</td>    <td>6872</td>  <td>26738</td>      <td>hrvatski jezik</td> </tr>
		<tr> <td>Czech</td>                               <td>cs</td>    <td>6373</td>  <td>25459</td>      <td>čeština, český jazyk</td> </tr>
		<tr> <td>Danish</td>                              <td>da</td>    <td>6461</td>  <td>25697</td>      <td>dansk</td> </tr>
		<tr> <td>Dutch</td>                               <td>nl</td>    <td>6E6C</td>  <td>28268</td>      <td>Nederlands, Vlaams</td> </tr>
		<tr> <td>Dzongkha</td>                            <td>dz</td>    <td>647A</td>  <td>25722</td>      <td>རྫོང་ཁ</td> </tr>
		<tr> <td>English</td>                             <td>en</td>    <td>656E</td>  <td>25966</td>      <td>English</td> </tr>
		<tr> <td>Esperanto</td>                           <td>eo</td>    <td>656F</td>  <td>25967</td>      <td>Esperanto</td> </tr>
		<tr> <td>Estonian</td>                            <td>et</td>    <td>6574</td>  <td>25972</td>      <td>eesti, eesti keel</td> </tr>
		<tr> <td>Faroese</td>                             <td>fo</td>    <td>666F</td>  <td>26223</td>      <td>føroyskt</td> </tr>
		<tr> <td>Fijian</td>                              <td>fj</td>    <td>666A</td>  <td>26218</td>      <td>vosa Vakaviti</td> </tr>
		<tr> <td>Finnish</td>                             <td>fi</td>    <td>6669</td>  <td>26217</td>      <td>suomi, suomen kieli</td> </tr>
		<tr> <td>French</td>                              <td>fr</td>    <td>6672</td>  <td>26226</td>      <td>français, langue française</td> </tr>
		<tr> <td>Galician</td>                            <td>gl</td>    <td>676C</td>  <td>26476</td>      <td>galego</td> </tr>
		<tr> <td>Georgian</td>                            <td>ka</td>    <td>6B61</td>  <td>27489</td>      <td>ქართული</td> </tr>
		<tr> <td>German</td>                              <td>de</td>    <td>6465</td>  <td>25701</td>      <td>Deutsch</td> </tr>
		<tr> <td>Greek</td>                               <td>el</td>    <td>656C</td>  <td>25964</td>      <td>ελληνικά</td> </tr>
		<tr> <td>Guaraní</td>                             <td>gn</td>    <td>676E</td>  <td>26478</td>      <td>Avañe'ẽ</td> </tr>
		<tr> <td>Gujarati</td>                            <td>gu</td>    <td>6775</td>  <td>26485</td>      <td>ગુજરાતી</td> </tr>
		<tr> <td>Hausa</td>                               <td>ha</td>    <td>6861</td>  <td>26721</td>      <td>(Hausa) هَوُسَ</td> </tr>
		<tr> <td>Hebrew</td>                              <td>iw</td>    <td>6977</td>  <td>26999</td>      <td>עברית</td> </tr>
		<tr> <td>Hindi</td>                               <td>hi</td>    <td>6869</td>  <td>26729</td>      <td>हिन्दी, हिंदी</td> </tr>
		<tr> <td>Hungarian</td>                           <td>hu</td>    <td>6875</td>  <td>26741</td>      <td>magyar</td> </tr>
		<tr> <td>Icelandic</td>                           <td>is</td>    <td>6973</td>  <td>26995</td>      <td>Íslenska</td> </tr>
		<tr> <td>Indonesian</td>                          <td>in</td>    <td>696E</td>  <td>26990</td>      <td>Bahasa Indonesia</td> </tr>
		<tr> <td>Interlingua</td>                         <td>ia</td>    <td>6961</td>  <td>26977</td>      <td>Interlingua</td> </tr>
		<tr> <td>Interlingue</td>                         <td>ie</td>    <td>6965</td>  <td>26981</td>      <td>Originally called Occidental; then Interlingue after WWII</td> </tr>
		<tr> <td>Inupiaq</td>                             <td>ik</td>    <td>696B</td>  <td>26987</td>      <td>Iñupiaq, Iñupiatun</td> </tr>
		<tr> <td>Irish</td>                               <td>ga</td>    <td>6761</td>  <td>26465</td>      <td>Gaeilge</td> </tr>
		<tr> <td>Italian</td>                             <td>it</td>    <td>6974</td>  <td>26996</td>      <td>italiano</td> </tr>
		<tr> <td>Japanese</td>                            <td>ja</td>    <td>6A61</td>  <td>27233</td>      <td>日本語 (にほんご)</td> </tr>
		<tr> <td>Javanese</td>                            <td>jw</td>    <td>6A77</td>  <td>27255</td>      <td>basa Jawa</td> </tr>
		<tr> <td>Kalaallisut, Greenlandic</td>            <td>kl</td>    <td>6B6C</td>  <td>27500</td>      <td>kalaallisut, kalaallit oqaasii</td> </tr>
		<tr> <td>Kannada</td>                             <td>kn</td>    <td>6B6E</td>  <td>27502</td>      <td>ಕನ್ನಡ</td> </tr>
		<tr> <td>Kashmiri</td>                            <td>ks</td>    <td>6B73</td>  <td>27507</td>      <td>कश्मीरी, كشميري‎</td> </tr>
		<tr> <td>Kazakh</td>                              <td>kk</td>    <td>6B6B</td>  <td>27499</td>      <td>қазақ тілі</td> </tr>
		<tr> <td>Khmer</td>                               <td>km</td>    <td>6B6D</td>  <td>27501</td>      <td>ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ</td> </tr>
		<tr> <td>Kinyarwanda</td>                         <td>rw</td>    <td>7277</td>  <td>29303</td>      <td>Ikinyarwanda</td> </tr>
		<tr> <td>Kirundi</td>                             <td>rn</td>    <td>726E</td>  <td>29294</td>      <td>Ikirundi</td> </tr>
		<tr> <td>Korean</td>                              <td>ko</td>    <td>6B6F</td>  <td>27503</td>      <td>한국어, 조선어</td> </tr>
		<tr> <td>Kurdish</td>                             <td>ku</td>    <td>6B75</td>  <td>27509</td>      <td>Kurdî, كوردی‎</td> </tr>
		<tr> <td>Kyrgyz</td>                              <td>ky</td>    <td>6B79</td>  <td>27513</td>      <td>Кыргызча, Кыргыз тили</td> </tr>
		<tr> <td>Lao</td>                                 <td>lo</td>    <td>6C6F</td>  <td>27759</td>      <td>ພາສາລາວ</td> </tr>
		<tr> <td>Latin</td>                               <td>la</td>    <td>6C61</td>  <td>27745</td>      <td>latine, lingua latina</td> </tr>
		<tr> <td>Latvian</td>                             <td>lv</td>    <td>6C76</td>  <td>27766</td>      <td>latviešu valoda</td> </tr>
		<tr> <td>Lingala</td>                             <td>ln</td>    <td>6C6E</td>  <td>27758</td>      <td>Lingála</td> </tr>
		<tr> <td>Lithuanian</td>                          <td>lt</td>    <td>6C74</td>  <td>27764</td>      <td>lietuvių kalba</td> </tr>
		<tr> <td>Macedonian</td>                          <td>mk</td>    <td>6D6B</td>  <td>28011</td>      <td>македонски јазик</td> </tr>
		<tr> <td>Malagasy</td>                            <td>mg</td>    <td>6D67</td>  <td>28007</td>      <td>fiteny malagasy</td> </tr>
		<tr> <td>Malay</td>                               <td>ms</td>    <td>6D73</td>  <td>28019</td>      <td>bahasa Melayu, بهاس ملايو‎</td> </tr>
		<tr> <td>Malayalam</td>                           <td>ml</td>    <td>6D6C</td>  <td>28012</td>      <td>മലയാളം</td> </tr>
		<tr> <td>Maltese</td>                             <td>mt</td>    <td>6D74</td>  <td>28020</td>      <td>Malti</td> </tr>
		<tr> <td>Māori</td>                               <td>mi</td>    <td>6D69</td>  <td>28009</td>      <td>te reo Māori</td> </tr>
		<tr> <td>Marathi (Marāṭhī)</td>                   <td>mr</td>    <td>6D72</td>  <td>28018</td>      <td>मराठी</td> </tr>
		<tr> <td>Moldavian, Moldovan</td>                 <td>mo</td>    <td>6D6F</td>  <td>28015</td>      <td>limba moldovenească, лимба молдовеняскэ</td> </tr>
		<tr> <td>Mongolian</td>                           <td>mn</td>    <td>6D6E</td>  <td>28014</td>      <td>Монгол хэл</td> </tr>
		<tr> <td>Nauruan</td>                             <td>na</td>    <td>6E61</td>  <td>28257</td>      <td>Dorerin Naoero</td> </tr>
		<tr> <td>Nepali</td>                              <td>ne</td>    <td>6E65</td>  <td>28261</td>      <td>नेपाली</td> </tr>
		<tr> <td>Norwegian</td>                           <td>no</td>    <td>6E6F</td>  <td>28271</td>      <td>Norsk</td> </tr>
		<tr> <td>Occitan</td>                             <td>oc</td>    <td>6F63</td>  <td>28515</td>      <td>occitan, lenga d'òc</td> </tr>
		<tr> <td>Oriya</td>                               <td>or</td>    <td>6F72</td>  <td>28530</td>      <td>ଓଡ଼ିଆ</td> </tr>
		<tr> <td>Oromo</td>                               <td>om</td>    <td>6F6D</td>  <td>28525</td>      <td>Afaan Oromoo</td> </tr>
		<tr> <td>Panjabi, Punjabi</td>                    <td>pa</td>    <td>7061</td>  <td>28769</td>      <td>ਪੰਜਾਬੀ, پنجابی‎</td> </tr>
		<tr> <td>Pashto, Pushto</td>                      <td>ps</td>    <td>7073</td>  <td>28787</td>      <td>پښتو</td> </tr>
		<tr> <td>Persian (Farsi)</td>                     <td>fa</td>    <td>6661</td>  <td>26209</td>      <td>فارسی</td> </tr>
		<tr> <td>Polish</td>                              <td>pl</td>    <td>706C</td>  <td>28780</td>      <td>język polski, polszczyzna</td> </tr>
		<tr> <td>Portuguese</td>                          <td>pt</td>    <td>7074</td>  <td>28788</td>      <td>português</td> </tr>
		<tr> <td>Quechua</td>                             <td>qu</td>    <td>7175</td>  <td>29045</td>      <td>Runa Simi, Kichwa</td> </tr>
		<tr> <td>Romanian</td>                            <td>ro</td>    <td>726F</td>  <td>29295</td>      <td>limba română</td> </tr>
		<tr> <td>Romansh</td>                             <td>rm</td>    <td>726D</td>  <td>29293</td>      <td>rumantsch grischun</td> </tr>
		<tr> <td>Russian</td>                             <td>ru</td>    <td>7275</td>  <td>29301</td>      <td>Русский</td> </tr>
		<tr> <td>Samoan</td>                              <td>sm</td>    <td>736D</td>  <td>29549</td>      <td>gagana fa'a Samoa</td> </tr>
		<tr> <td>Sango</td>                               <td>sg</td>    <td>7367</td>  <td>29543</td>      <td>yângâ tî sängö</td> </tr>
		<tr> <td>Sanskrit (Saṁskṛta)</td>                 <td>sa</td>    <td>7361</td>  <td>29537</td>      <td>संस्कृतम्</td> </tr>
		<tr> <td>Scottish Gaelic, Gaelic</td>             <td>gd</td>    <td>6764</td>  <td>26468</td>      <td>Gàidhlig</td> </tr>
		<tr> <td>Serbian</td>                             <td>sr</td>    <td>7372</td>  <td>29554</td>      <td>српски језик</td> </tr>
		<tr> <td>Serbo-Croatian</td>                      <td>sh</td>    <td>7368</td>  <td>29544</td>      <td>srpskohrvatski jezik</td> </tr>
		<tr> <td>Shona</td>                               <td>sn</td>    <td>736E</td>  <td>29550</td>      <td>chiShona</td> </tr>
		<tr> <td>Sindhi</td>                              <td>sd</td>    <td>7364</td>  <td>29540</td>      <td>सिन्धी, سنڌي، سندھی‎</td> </tr>
		<tr> <td>Sinhala, Sinhalese</td>                  <td>si</td>    <td>7369</td>  <td>29545</td>      <td>සිංහල</td> </tr>
		<tr> <td>Slovak</td>                              <td>sk</td>    <td>736B</td>  <td>29547</td>      <td>slovenčina, slovenský jazyk</td> </tr>
		<tr> <td>Slovene</td>                             <td>sl</td>    <td>736C</td>  <td>29548</td>      <td>slovenski jezik, slovenščina</td> </tr>
		<tr> <td>Somali</td>                              <td>so</td>    <td>736F</td>  <td>29551</td>      <td>Soomaaliga, af Soomaali</td> </tr>
		<tr> <td>Southern Sotho</td>                      <td>st</td>    <td>7374</td>  <td>29556</td>      <td>Sesotho</td> </tr>
		<tr> <td>Spanish</td>                             <td>es</td>    <td>6573</td>  <td>25971</td>      <td>español</td> </tr>
		<tr> <td>Sundanese</td>                           <td>su</td>    <td>7375</td>  <td>29557</td>      <td>Basa Sunda</td> </tr>
		<tr> <td>Swahili</td>                             <td>sw</td>    <td>7377</td>  <td>29559</td>      <td>Kiswahili</td> </tr>
		<tr> <td>Swati</td>                               <td>ss</td>    <td>7373</td>  <td>29555</td>      <td>SiSwati</td> </tr>
		<tr> <td>Swedish</td>                             <td>sv</td>    <td>7376</td>  <td>29558</td>      <td>svenska</td> </tr>
		<tr> <td>Tagalog</td>                             <td>tl</td>    <td>746C</td>  <td>29804</td>      <td>Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔</td> </tr>
		<tr> <td>Tajik</td>                               <td>tg</td>    <td>7467</td>  <td>29799</td>      <td>тоҷикӣ, toçikī, تاجیکی‎</td> </tr>
		<tr> <td>Tamil</td>                               <td>ta</td>    <td>7461</td>  <td>29793</td>      <td>தமிழ்</td> </tr>
		<tr> <td>Tatar</td>                               <td>tt</td>    <td>7474</td>  <td>29812</td>      <td>татар теле, tatar tele</td> </tr>
		<tr> <td>Telugu</td>                              <td>te</td>    <td>7465</td>  <td>29797</td>      <td>తెలుగు</td> </tr>
		<tr> <td>Thai</td>                                <td>th</td>    <td>7468</td>  <td>29800</td>      <td>ไทย</td> </tr>
		<tr> <td>Tibetan Standard, Tibetan, Central</td>  <td>bo</td>    <td>626F</td>  <td>25199</td>      <td>བོད་ཡིག</td> </tr>
		<tr> <td>Tigrinya</td>                            <td>ti</td>    <td>7469</td>  <td>29801</td>      <td>ትግርኛ</td> </tr>
		<tr> <td>Tonga (Tonga Islands)</td>               <td>to</td>    <td>746F</td>  <td>29807</td>      <td>faka Tonga</td> </tr>
		<tr> <td>Tsonga</td>                              <td>ts</td>    <td>7473</td>  <td>29811</td>      <td>Xitsonga</td> </tr>
		<tr> <td>Tswana</td>                              <td>tn</td>    <td>746E</td>  <td>29806</td>      <td>Setswana</td> </tr>
		<tr> <td>Turkish</td>                             <td>tr</td>    <td>7472</td>  <td>29810</td>      <td>Türkçe</td> </tr>
		<tr> <td>Turkmen</td>                             <td>tk</td>    <td>746B</td>  <td>29803</td>      <td>Türkmen, Түркмен</td> </tr>
		<tr> <td>Twi</td>                                 <td>tw</td>    <td>7477</td>  <td>29815</td>      <td>Twi</td> </tr>
		<tr> <td>Ukrainian</td>                           <td>uk</td>    <td>756B</td>  <td>30059</td>      <td>Українська</td> </tr>
		<tr> <td>Urdu</td>                                <td>ur</td>    <td>7572</td>  <td>30066</td>      <td>اردو</td> </tr>
		<tr> <td>Uzbek</td>                               <td>uz</td>    <td>757A</td>  <td>30074</td>      <td>Oʻzbek, Ўзбек, أۇزبېك‎</td> </tr>
		<tr> <td>Vietnamese</td>                          <td>vi</td>    <td>7669</td>  <td>30313</td>      <td>Tiếng Việt</td> </tr>
		<tr> <td>Volapük</td>                             <td>vo</td>    <td>766F</td>  <td>30319</td>      <td>Volapük</td> </tr>
		<tr> <td>Welsh</td>                               <td>cy</td>    <td>6379</td>  <td>25465</td>      <td>Cymraeg</td> </tr>
		<tr> <td>Western Frisian</td>                     <td>fy</td>    <td>6679</td>  <td>26233</td>      <td>Frysk</td> </tr>
		<tr> <td>Wolof</td>                               <td>wo</td>    <td>776F</td>  <td>30575</td>      <td>Wollof</td> </tr>
		<tr> <td>Xhosa</td>                               <td>xh</td>    <td>7868</td>  <td>30824</td>      <td>isiXhosa</td> </tr>
		<tr> <td>Yiddish</td>                             <td>ji</td>    <td>6A69</td>  <td>27241</td>      <td>ייִדיש</td> </tr>
		<tr> <td>Yoruba</td>                              <td>yo</td>    <td>796F</td>  <td>31087</td>      <td>Yorùbá</td> </tr>
		<tr> <td>Zulu</td>                                <td>zu</td>    <td>7A75</td>  <td>31349</td>      <td>isiZulu</td> </tr>
	</tbody>
</table>

**Comment by xylographe** [comment]
Does [SubtitleEdit-3.4.12.75-issue1675.7z](https://www.dropbox.com/s/kgfbi5x0kf8634u/SubtitleEdit-3.4.12.75-issue1675.7z?dl=1) fix this?

**Comment by aaaxx** [comment]
Yes, it does. Thanks. :smile:
