### ISSUE TITLE
more SHD removal

### ISSUE THREAD

**Issue by Thunderbolt8** [SubtitleEdit/subtitleedit#1684]
not really a bug, but a small improvemtent. could you please adjust ... dots position in case of SHD removal?

- oh... alright| - ok

would be 

- ... alright |- ok 

instead of

 - ...alright| - ok

so basically reposition the three dots directly next to the following word if the word originally preceeding them go got removed due to SHD removal (same in case with italics).

--------------------------------------------------------------------------------------------------------------------------

a different case involving en dash – (I guess) and em dash —

\(clears throat) Oh, uh —|Well, Major, I said there are exactly —

correct:

Well, Major, I said there are exactly —

the em dash hyphen is correctly identified as part of SHD in the first part of the line and thus removed as well.

\- How many, sir?|- Uh — (clears throat) 275.

incorrect:

\- How many, sir?|- — 275.

the em dash hyphen should be removed as well here.

-------------------------------------------------------------------------------------------------------------------------------

some comma thingie:

Oh, I, uh — I got a guy |picks them out for me

-->

I, — I got a guy|picks them out for me

either comma or hyphen is too much. personally, I prefer to have the hyphen in such cases, looks better to support the repetition or stuttering. just dont know how, in case of a normal hyphen like I- I... or I-I... but the em dash hyphen is a bit longer so not sure how this looks. Maybe I— I... or I — I...
cant really decide which looks better.

**Comment by niksedk** [comment]
I've tried to fix the issues in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip
Let me know how it works...

**Comment by Thunderbolt8** [comment]
thanks. however, the first case doesnt seem to be solved. well, its a .ass subtitle I have here with line positioning information, dont know if that makes a difference.

/{\an4\pos(597,896)}Uh... Tight.

/--> {\an4\pos(597,896)}... Tight.

/instead of {\an4\pos(597,896)}...tight.

ideally the first letter is small case then as its supposed not to be imagines beginning of the sentence.
