### ISSUE TITLE
[Bug] Some Shortcuts crash or not work

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#1708]
hi....

some shortcuts not work or crash SE

shortcut move selected lines 100 ms forward and back, not work 

shortcut "Remove text for hearing impaired..." crash SE if you choose the keys (shift+H)

same for others shortcuts, but I not remember now which are

![capturar](https://cloud.githubusercontent.com/assets/7856897/14579778/b6147df0-03ae-11e6-84d4-89ff809b86f7.PNG)

tested in SE 3.4.12 build 117

**Comment by xylographe** [comment]
This exception was thrown after selecting **Opções > Configurações...** (or **Configurações** in the tool bar) , right?

Please, open SE Settings file (e.g., `%APPDATA%\Subtitle Edit\Settings.xml`) in your favourite text editor, and copy&paste the `<Shortcuts>` section in a [Gist.](https://gist.github.com/)

**Comment by marb99** [comment]
Not only in toolbar, but i menu bar too..

here is it : https://gist.github.com/marb99/047c1fa61c6a7867360c7a4d288e75cd

**Comment by xylographe** [comment]
Ty, @marb99 
I can reproduce. Will try to fix it later this week.

**Comment by marb99** [comment]
ok, xylographe 

thanks ;)

**Comment by niksedk** [comment]
I fixed the shortcut validation yesterday. Not committed yet though... and this crash has happened before. (Visible menu item shortcuts has a stricter validation than non-visible ones it seems)

**Comment by niksedk** [comment]
Fix committed in https://github.com/SubtitleEdit/subtitleedit/commit/58077afaf6fea76dcc5c2d8738cba01bdf66a305

The fix will not make your crash go away - you can delete your "settings.xml" file  (or remove "Shift+H" in the shortcuts section). 

The shortcut for `Move selected lines 100 ms forward/back` only works when "Adjust" mode is active (a tab in the video controls)

**Comment by xylographe** [comment]
@niksedk 
The exception is thrown when you press **Update** in the Shortcuts tab of the Settings dialogue.
This could be fixed by disabling this button until the displayed keyboard shortcut is valid.

**Comment by niksedk** [comment]
@xylographe: (I get the exception when  I press `OK` in the settings window after updating the shortcuts + every time I start SE after that.) I guess it would more be more user-friendly to disable shortcut if it's not valid.
No matter the solution, it might be difficult to understand why some shortcuts allow `Shift+N`and others don't!

**Comment by xylographe** [comment]
@niksedk 
Yes, clicking **OK** will throw the exception.
To to stop the user from, unknowingly, adding an invalid combination, it would be good to disable **Update** until the displayed keyboard shortcut is valid.

**Comment by niksedk** [comment]
@xylographe: should be fixed via https://github.com/SubtitleEdit/subtitleedit/commit/3f04d3c1f621e0010d344de408fbbc85aadd9cd0

**Comment by niksedk** [comment]
@marb99: The changes are now included in latest portable beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip

**Comment by xylographe** [comment]
Ty, @niksedk 
I think this immediate feedback to the user works well.

One more tiny detail: perhaps add `treeViewShortcuts.SelectedNode.Select()` at the end of `buttonUpdateShortcut_Click()` (Settings.cs) to set focus back to the tree view?

**Comment by marb99** [comment]
Ty, @niksedk
