### ISSUE TITLE
[bug] Remove text for hearing impaired - "Apply" does not update the text view, and the first line is not changed

### ISSUE THREAD

**Issue by Jolar** [SubtitleEdit/subtitleedit#1710]
Two (2) bugs:

1. When pressing the button "Apply" in the dialog for removing subtitles for hearing impaired, the text view window doesn't update with the changes. The little editor window shows the new lines however (which clearly no longer match the lines you select above). It is changed "internally" though, if you save and re-open changes are there with the exception of an eventual first line:

2. If the very first line is a hearing impaired subtitle within parenthesis, it is not removed when pressing "Apply".

Using 3.4.12

**Comment by niksedk** [comment]
Thx for the bug report - this should already be fixed in latest beta - see change log here: https://github.com/SubtitleEdit/subtitleedit/blob/master/Changelog.txt

You could test latest beta and verify: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip
