### ISSUE TITLE
Feature: Save settings in user's home

### ISSUE THREAD

**Issue by larvanitis** [SubtitleEdit/subtitleedit#1724]
I am trying to create a linux package but I stumbled on the hardcoded `Settings.xml` location which resolves to DataDirectory.

Under linux it should be something like `~/.config/subtitle-edit/Settings.xml`

I am not sure but this probably affects other "runtime" modifiable files (plugins, dictionaries etc)?

**Comment by xylographe** [comment]
Does `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)` return a usable path under mono?

**Comment by larvanitis** [comment]
Yes, it returns `/home/USER/.config`.

**Comment by xylographe** [comment]
Ty, @larvanitis 
Then [this change](https://github.com/xylographe/subtitleedit/compare/master...xylographe:xunix) should fix the issue.

\[exe in `SubtitleEdiit-3.4.12.213-issue1724.7z` in [this folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)]
