### ISSUE TITLE
Error under Linux

### ISSUE THREAD

**Issue by larvanitis** [SubtitleEdit/subtitleedit#1726]
#### ERROR

While running under Linux I sometimes (maybe half the times) get the following error.

![subtitleedit-error](https://cloud.githubusercontent.com/assets/1144686/14814348/88d66d28-0bae-11e6-997d-8f20e24500ac.png)

Selecting `Retry` or `Ignore` dismisses the dialog and the program seems to work.

I am attaching a zip with debugging output I got using `MONO_LOG_LEVEL="debug" MONO_LOG_MASK="all" mono SubtitleEdit.exe`. The error occurs right after `Mono: Found as 'XUndefineCursor'.`
[subtitle-edit-debug.zip](https://github.com/SubtitleEdit/subtitleedit/files/236370/subtitle-edit-debug.zip)
#### SYSTEM

OS: Arch Linux
Arch: x64
Mono version: 4.4.0
Subtitle Edit version: 3.4.12 (from SE3412.zip)

```
$ mono --version
Mono JIT compiler version 4.4.0 (Stable 4.4.0.40/f8474c4 Mon Mar 28 12:22:29 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
```

---

_PS. FYI [Mono Compatibility](http://www.mono-project.com/docs/about-mono/compatibility/)_

**Comment by xylographe** [comment]
Related to #1522? (GDI+)
