### ISSUE TITLE
Enhancement requests for transport stream/dvbsub

### ISSUE THREAD

**Issue by kurosu** [SubtitleEdit/subtitleedit#1728]
I have observed the following shortcomings:
- Duration is incorrectly set and seems to be forced to 3.5s
- SubtitleEdit doesn't seem to offer a way to select the dvbsub stream
- OCR of dvbsub does not seem to retain position
- OCR seems to miss some lines: highlight them yellow/orange and the subtitle is empty (probably a tesseract issue)

I have 250MB samples recorded obviously from DVB streams without errors. Not sure what size would still exhibit all the shortcoming listed.

**Comment by niksedk** [comment]
About selecting a dvbsub stream SE should prompt if the ts file contains more than one dvbsub.

I guess a sample file would be nice to look closer at 1 + 4 - could you make a link? (can also be in an email)

**Comment by niksedk** [comment]
These issues are hopefully mostly fixed now... if anybody experiences "blank lines when using Tesseract OCR" then try checking "gray-scale" (works fine with "use color")
