### ISSUE TITLE
[ENHANCEMENT] Subtitle length in em units

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1731]
[Em](https://en.wikipedia.org/wiki/Em_%28typography%29) is a typographic unit relative to the specified font size (1 em = font size). To calculate it, you would divide line length by font size, and, being a relative unit, you'll get the same result regardless of font size.

The benefit of ems is they're actually a meaningful metric, unlike character count. For example, all of these lines have 40 characters but wildly different widths:
- Jared, it's a little early for all that.
- People act more important than they are.
- POLICE CLOSING IN ON MICHEL POICCARD ...

(Go ahead, count it. You know you want to. :wink:)

When measured in ems, though, they are 14.5, 18.1 and 22.2 ems wide in Arial (with similar values for other common sans-serif fonts).

Once you start measuring the lines this way there's all kinds of useful things you can do, like calculate the maximum available screen area for a given font and size, or make better line breaks in cases when character count would force you to move a chunk of line to the next one even if the overflowing characters are narrow letters or punctuation.

The only program that currently supports ems is Gaupol, but its implementation is broken and gives completely wrong values. I filed a [bug report](https://bugzilla.gnome.org/show_bug.cgi?id=763589) but it doesn't look like it's gonna be fixed any time soon. (If anyone can figure it out, [send them a patch](http://home.gna.org/gaupol/development.html).)

This function should work the same way as character count does, but the user should be able to set the desired font and size in Settings, unrelated to the ones that are used right now for customizing the interface.

**Comment by niksedk** [comment]
The plugin "Check line width in pixels" does something similar... perhaps you can use that?

**Comment by aaaxx** [comment]
Hmm, it shows me wrong widths. They're way too wide. Also, for some font sizes, like 10, it actually sets the size to an approximation, like 9.75, which is really strange.

But in any case, this feature should be an integral part of SE and work in all the same ways as character count does, so that it's possible to use it even while writing subtitles from scratch.

**Comment by niksedk** [comment]
Pixel width is included now
