### ISSUE TITLE
Batch converter Bluray sup create

### ISSUE THREAD

**Issue by pierinho** [SubtitleEdit/subtitleedit#1739]
Hi, in batch converter mode there is a bug when i create a bluray sup subtitle...
When i go on setting for create bluray sup the border style and shadow width not working... if i chage value nothing change.
If i use the export function in file menu, shadow wìidth and border style works perfectly.
Only in batch mode non working.
I try the latest beta, but the batch conversion for bluray sup show me an error when i try to convert.
Thanks

**Comment by niksedk** [comment]
It seems to work fine with my settings... 

What's the error?
Is it a special subtitle file that gives the problem? 
What are you Blu-ray sup export settings?
