### ISSUE TITLE
BridgeGaps listViewColor

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#174]
@niksedk What do you think to switch the item background color from something more friendly take a  look below, Green doesn't display _foreColor_ friendly...
![new_color](https://cloud.githubusercontent.com/assets/6579818/3349739/f5088bd0-f976-11e3-981f-bfee5e22e1bd.png)
![default_color](https://cloud.githubusercontent.com/assets/6579818/3349742/faeba8b6-f976-11e3-8513-ba77966d99bf.png)

**Comment by niksedk** [comment]
Seems to be fixed now
