### ISSUE TITLE
Unable to choose VLC, options stuck to "directshow" only

### ISSUE THREAD

**Issue by Unixware** [SubtitleEdit/subtitleedit#1744]
Can't choose the VLC, and other options except DirectShow are greyed.

**Comment by xylographe** [comment]
At the upper right hand corner of the tab it says either 64-bit or 32-bit.
If 32-bit you must install 32-bit VLC. If 64-bit, install 64-bit VLC.

Or, you could try SE beta version and download mpv lib.

**Comment by Unixware** [comment]
I've installed both 64bit of vlc and SE!
Anyway, I am running the SE beta with mpv lib now , thx
