### ISSUE TITLE
[ENHANCEMENT] Delay for individual replacements

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1748]
Sometimes I'm feeling a bit paranoid and would like to check every replacement (especially with regex) and I think it would be nice to have an option to pause for a bit before automatically jumping to the next match. Either a customizable value in milliseconds or just a checkmark with a fixed value (let's say half a second).

**Comment by xylographe** [comment]
I think, pausing would only make sense if it were possible to interrupt when you spot an unwanted replacement, right? To implement that efficiently would require .Net 4.5 but SE requires only .Net 4.0 (last version that supports WinXP).

Perhaps, a preview of the affected subtitles (similar to MR and FCE) would be a reasonable alternative?

**Comment by aaaxx** [comment]
Well I was thinking of just closing the Replace dialogue in case of a bad replacement and then manually fixing it. It seems to be a pretty simple solution.

Actually, now that you mention it, preview would be great. Especially with highlighting (background, not text).
