### ISSUE TITLE
[ENHANCEMENT] Add support for spu/png OCR

### ISSUE THREAD

**Issue by claunia** [SubtitleEdit/subtitleedit#1749]
These subtitles come with a xml description file containing timing for png files that contain picture subtitles.

They are used to author DVD subtitles and get extracted by ccextractor from DVB subtitles.

**Comment by niksedk** [comment]
Could you email me/attach/link-to a sample file?

**Comment by claunia** [comment]
Sure,

https://mega.nz/#!ZZxWFIwZ!IgeVj0C_DJ8QcN1CAoeDlGmwyXnrrFDNsDEHim627W0

**Comment by niksedk** [comment]
thx for the files - should be fixed in this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip

**Comment by claunia** [comment]
Works perfectly and gets same output as opening the TS file directly. But, it doesn't allow the option to choose colors (not a problem for me because I have no way to save the colors on the move to MP4) while it does opening the TS.
