### ISSUE TITLE
[ENHANCEMENT] Ignore angled quotation marks on spell checking

### ISSUE THREAD

**Issue by claunia** [SubtitleEdit/subtitleedit#1751]
When OCRing a Spanish subtitle, the vertical quotation marks " get converted to angled quotation marks «.

This behaviour is correct, but collides with spell checking, so
`"después"`
is ignored by the spell checker because it's correct but
`«después»`
gets detected as misspelled.

https://en.wikipedia.org/wiki/Quotation_mark#Spanish

The ideal solution should be to leave the angled quotation marks alone (as they're the recommended one by RAE), or otherwise don't convert the vertical ones as angled ones on OCR.

This only affects Spanish subtitles, as the conversion is not done on English, French or Dutch (other languages not tested).

**Comment by niksedk** [comment]
Fix included in latest portable (no installer) beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
and thx for the info :)

**Comment by claunia** [comment]
@niksedk thanks for the prompt patch and the beta version. This will be most useful, 90% of OCR pauses in my usage were because of the quotation marks!
