### ISSUE TITLE
[LINUX]Untranslated file encodings in options and toolbar

### ISSUE THREAD

**Issue by larvanitis** [SubtitleEdit/subtitleedit#1755]
The file encodings (other than UTF8) in the drop downs in the toolbar and in `Settings` > `General` > `Default file encoding` are not translated, as you can see in the image bellow.

![se-codepages](https://cloud.githubusercontent.com/assets/1144686/15269317/ab91d600-1a03-11e6-9e0d-3f505d0d88c7.png)

**Comment by xylographe** [comment]
Doesn't look like an SE bug. SE invokes [`Encoding.GetEncodings`,](https://msdn.microsoft.com/en-us/library/system.text.encoding.getencodings%28v=vs.110%29.aspx) and uses the [`EncodingInfo.DisplayName`](https://msdn.microsoft.com/en-us/library/system.text.encodinginfo.displayname%28v=vs.110%29.aspx) property. See [`Forms/Main`.](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Forms/Main.cs#L337)

Related to issue #1285. Seems like we need a second work-around. :(

**Comment by larvanitis** [comment]
OK.

Looking at [`EncodingInfo.DisplayName`](https://msdn.microsoft.com/en-us/library/system.text.encodinginfo.displayname) and running the code from that page under mono, I can see that while the `DisplayName` is "gibberish" the `Name` is still human understandable.

```
Info.CodePage      Info.Name                    Info.DisplayName
...
1250               windows-1250                 Globalization.cp_1250        
1251               windows-1251                 Globalization.cp_1251        
1252               Windows-1252                 Globalization.cp_1252 
...
```

Maybe we could check if `DisplayName` starts with `Globalization.cp_` and use `Name` instead.

[mono-encodings.txt](https://github.com/SubtitleEdit/subtitleedit/files/264627/mono-encodings.txt)

**Comment by larvanitis** [comment]
Further, you could change [`Forms/Main.cs#L342`](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Forms/Main.cs#L342) by replacing it with:

```
string displayName = (ei.DisplayName == "Globalization.cp_" + ei.CodePage) ? ei.Name.ToUpper() : ei.DisplayName;
comboBoxEncoding.Items.Add(ei.CodePage + ": " + displayName);
```

**Comment by xylographe** [comment]
Please, try branch [issue1755.](https://github.com/xylographe/subtitleedit/tree/issue1755)

\[SE exe in [`SubtitleEdit-3.4.12.253-issue1755.7z`](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)]

**Comment by xylographe** [comment]
Added more commits to (hopefully) fix the same problem in other Forms and in libse.

**Comment by larvanitis** [comment]
> Added more commits to (hopefully) fix the same problem in other Forms and in libse.

Can you please provide an updated exe for testing?

**Comment by xylographe** [comment]
Updated [`SubtitleEdit-3.4.12.252-issue1755.7z`](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0) to latest commit (5d46d4e4c4563dee456d28fef2c25eadebb2825f).

**Comment by xylographe** [comment]
Added minor cosmetic improvement (commit 7f510336eb1151d43e8af0d4551377d222a3b3d1).

Updated [**`SubtitleEdit-3.4.12.252-issue1755.7z`**](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0) to latest commit.

**Comment by xylographe** [comment]
@larvanitis Have the `Globalization.cp_*` disappeared? Or is it time for plan B?

**Comment by larvanitis** [comment]
I won't have access to my Linux pc until tomorrow.
I will let you know then.

**Comment by xylographe** [comment]
Branch issue1755 was [merged into master](https://github.com/SubtitleEdit/subtitleedit/commit/fb9fdc66b26553b760d438df6d6bfc4a7f785e85).
If necessary, the encoding display names can be adjusted in [**`Logic.TextEncodingListItem`**](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Logic/TextEncodingListItem.cs#L37).

Beta build [`SE-3.4.12.280` or later](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)

**Comment by larvanitis** [comment]
Sorry for the long delay.

I just found some time and tested your changes. Yes, it works great now so I'm closing the issue.

Thanks @xylographe, you are the man!
