### ISSUE TITLE
Object reference not set to an in stance of an object

### ISSUE THREAD

**Issue by Enzo0o** [SubtitleEdit/subtitleedit#1756]
how i solve this issue? 
take a look http://up.harajgulf.com/do.php?img=766245

**Comment by xylographe** [comment]
Perhaps, a missing image ([`GenerateImageFromTextWithStyle`](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Forms/ExportPngXml.cs#L3247) returns `null`) ?

Does this happen on one particular subtitle, or on every subtitle?

**Comment by niksedk** [comment]
Perhaps you could upload the sub somewhere?
Latest beta (hopefully) will give us the line number where the error occurred and that will help us fix it: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip (no installer - just unpack)

**Comment by niksedk** [comment]
@Enzo0o: Did you have time to test the beta?
