### ISSUE TITLE
Gap at start of waveform

### ISSUE THREAD

**Issue by mohammadrezaprw** [SubtitleEdit/subtitleedit#1757]
Hi,
I click on waveform to add an mp3 file, file loaded correctly but wave bar and soudnd not mapped on together and there is about 4 sec difference.
Why this happen?
tnx

**Comment by mohammadrezaprw** [comment]
This problem resolved by using mpv package.

**Comment by niksedk** [comment]
Yes, mpv seems to be good indeed - fast and precise seeking. VLC is a nice fallback if you have a really weird video format though.
