### ISSUE TITLE
Auto-translate problem

### ISSUE THREAD

**Issue by Yekutiel** [SubtitleEdit/subtitleedit#1766]
I am running GalliumOS 1.0 (which is based on Ubuntu 15.04) on an Acer C720 (Chromebook) with 4 gigs of RAM.

SubtitleEdit seems to be working  properly with one exception:

When I choose SubtitleEdit’s menu option **Auto-translate->Translate (powered by Google)** and then click on the Translate button instead of seeing a translation of my captions I receive the following error message:

`System error getting response stream (Write: The encryption and decryption has failed)`

And after searching Google little while I guessed that the following might help therefore I ran:

`sudo mozroots --machine --import --sync`

Amongst other information, my terminal displayed the following

> Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
> Importing certificates into user store...
> 140 new root certificates were added to your trust store.
> Import process completed.

But that didn't solve the problem.

I would appreciate some help resolving this problem.

In case it is relevant I have included the following information:

To get SubtitleEdit running on my machine I did the following:

I installed it by running this command: `sudo apt-get install mono-complete`

Then I downloaded **SE3412.zip** from https://github.com/SubtitleEdit/subtitleedit/releases.

Then I unzipped SE3412.zip

Then I ran SubtitleEdit.exe

Also, I wiped the ChromeOS from my machine so that is essentially an ordinary machine running Linux. Finally, I am running 

I flashed "... custom firmware with a SeaBIOS payload on 37 distinct models of Intel based Chromebook, allowing you to run an alternative OS such as Linux." https://johnlewis.ie/custom-chromebook-firmware/rom-download/

**Comment by xylographe** [comment]
Please, try **`SubtitleEdit-3.4.12.285-issue1766.7z`** from [this dropbox folder.](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)

**Comment by Yekutiel** [comment]
Thanks for working with me on this.

**Terse Response**
I downloaded and ran an 3.4.12.287-issue1766.7z The update failed to solve my problem. I encountered the identical error message.

**Detailed Response**
I am supplying the following information to assure you that I properly followed your explicit and implicit instructions.

I just downloaded SubtitleEdit-3.4.12.287-issue1766.7z from the indicated Dropbox folder because SubtitleEdit-3.4.12.285-issue1766.7z was not extant and had apparently been superseded by SubtitleEdit-3.4.12.287-issue1766.7z.

I extracted the contents of SubtitleEdit-3.4.12.287-issue1766.7z to a new folder I created.

Then I launched SubtitleEdit.exe from within the new folder I had just created

Then I added a caption in SubtitleEdit

When I chose SubtitleEdit’s menu option **Auto-translate->Translate (powered by Google)** and then clicked on the Translate button instead of seeing a translation of my caption once again I received the following error message:

`System error getting response stream (Write: The encryption and decryption has failed)`

**Comment by xylographe** [comment]
You can ignore the build number (285/287), it increases automatically when new commits are added to the SubtitleEdit master branch.

[**`SubtitleEdit-3.4.12.287-issue1766-2.7z`**](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0) does not solve this issue, but it should pop up a message box with more detailed information about the failed server validation.

Note that if you choose to continue despite the validation failure, the message box will reappear over and over again, because Google translation is performed by splitting the subtitle, invoking Google Translate for each part.

**Comment by Yekutiel** [comment]
Thanks for your quick response.  A message box with more detailed information about the failed server validation appeared

**Comment by Yekutiel** [comment]
Here's a screenshot of the message box with more detailed information about the failed server validation appeared.

![may 26- detailed information about the failed server validation](https://cloud.githubusercontent.com/assets/16394972/15585697/8549c38c-2335-11e6-9336-47366d9e3bea.png)

**Comment by xylographe** [comment]
I think, the [PartialChain status](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509chainstatusflags%28v=vs.100%29.aspx) means that mono could not find the appropriate [GeoTrust](https://www.geotrust.com/resources/root-certificates/index.html) root certificate. Weird, because you already ran `mozroots`. Perhaps, mono is looking in the wrong place? (probably `~/.config/.mono/certs/Trust` and `/usr/share/.mono/certs/Trust`).

**Comment by Yekutiel** [comment]
Thanks again for responding promptly.

Neither `~/.config/.mono/certs/Trust` nor `/usr/share/.mono/certs/Trust` exist on my machine.

How would I go about finding where mono is "looking"?

**Comment by xylographe** [comment]
I would try this: download the [GeoTrust](https://www.geotrust.com/resources/root-certificates/index.html) [Global CA root certificate (Serial Number: 02 34 56)](https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem), convert it to a DER encoded certificate, and install it in the mono user store. For example,
```
curl -o GeoTrust_Global_CA.pem "https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem"
openssl x509 -in GeoTrust_Global_CA.pem -outform der -out GeoTrust_Global_CA.crt
mono certmgr.exe -add -c -v Trust GeoTrust_Global_CA.crt
```

And perhaps, `certmgr` with the *verbose* option will also reveal where the user store is located. Or, you could use find(1): `find ~ -type d -name cert` or `find ~ -type f -name \*.crt | less`.

**Comment by Yekutiel** [comment]
Thanks. Did I do something wrong? Please see the following:

yekutiel@yekutiel-Peppy:~$ curl -o Georust_Global_CA.pem "https://www.geotrust.com/resources/root_certificates/certificates/Georust_Global_CA.pem"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:100 17452    0 17452    0     0  18594      0 --:--:-- --:--:100 24063    0 24063    0     0  25514      0 --:--:-- --:--:-- --:--:-- 25517

yekutiel@yekutiel-Peppy:~$ openssl x509 -in Georust_Global_CA.pem -outform der -out Georust_Global_CA.crt
unable to load certificate
140421787920016:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: TRUSTED CERTIFICATE

**Comment by xylographe** [comment]
Looks like something went wrong with curl(1). Try to create the ASCII certificate file with cat(1), and verify the contents of `GeoTrust_Global_CA.pem` : 
```
cat <<EOF >GeoTrust_Global_CA.pem
-----BEGIN CERTIFICATE-----
MIIDVDCCAjygAwIBAgIDAjRWMA0GCSqGSIb3DQEBBQUAMEIxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9i
YWwgQ0EwHhcNMDIwNTIxMDQwMDAwWhcNMjIwNTIxMDQwMDAwWjBCMQswCQYDVQQG
EwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEbMBkGA1UEAxMSR2VvVHJ1c3Qg
R2xvYmFsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2swYYzD9
9BcjGlZ+W988bDjkcbd4kdS8odhM+KhDtgPpTSEHCIjaWC9mOSm9BXiLnTjoBbdq
fnGk5sRgprDvgOSJKA+eJdbtg/OtppHHmMlCGDUUna2YRpIuT8rxh0PBFpVXLVDv
iS2Aelet8u5fa9IAjbkU+BQVNdnARqN7csiRv8lVK83Qlz6cJmTM386DGXHKTubU
1XupGc1V3sjs0l44U+VcT4wt/lAjNvxm5suOpDkZALeVAjmRCw7+OC7RHQWa9k0+
bw8HHa8sHo9gOeL6NlMTOdReJivbPagUvTLrGAMoUgRx5aszPeE4uwc2hGKceeoW
MPRfwCvocWvk+QIDAQABo1MwUTAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTA
ephojYn7qwVkDBF9qn1luMrMTjAfBgNVHSMEGDAWgBTAephojYn7qwVkDBF9qn1l
uMrMTjANBgkqhkiG9w0BAQUFAAOCAQEANeMpauUvXVSOKVCUn5kaFOSPeCpilKIn
Z57QzxpeR+nBsqTP3UEaBU6bS+5Kb1VSsyShNwrrZHYqLizz/Tt1kL/6cdjHPTfS
tQWVYrmm3ok9Nns4d0iXrKYgjy6myQzCsplFAMfOEVEiIuCl6rYVSAlk6l5PdPcF
PseKUgzbFbS9bZvlxrFUaKnjaZC2mqUPuLk/IH2uSrW4nOQdtqvmlKXBx4Ot2/Un
hw4EbNX/3aBd7YdStysVAq45pmp06drE57xNNB6pXE0zX5IJL4hmXXeXxx12E6nV
5fEWCRE11azbJHFwLJhWC9kXtNHjUStedejV0NxPNO3CBWaAocvmMw==
-----END CERTIFICATE-----
EOF
cat GeoTrust_Global_CA.pem
sha1sum GeoTrust_Global_CA.pem
```
The SHA1 sum should be `03e0b79c05a92a953e17fa223e79959424780168`
Then proceed with openssl(1) : 
```
openssl x509 -in GeoTrust_Global_CA.pem -outform der -out GeoTrust_Global_CA.crt
mono certmgr.exe -add -c -v Trust GeoTrust_Global_CA.crt
```

**Comment by Yekutiel** [comment]
I sincerely appreciate you spending your time to help me but I am unwilling to spend more time attempting to debug this.

**Comment by xylographe** [comment]
Closing, because it is a local configuration problem, not a Subtitle Edit issue.
