### ISSUE TITLE
Manual chosen encoding

### ISSUE THREAD

**Issue by hucky291158** [SubtitleEdit/subtitleedit#1772]
Could you please add "Import Subtitle with Manual Chosen Encoding" to the Explorer context menu?

**Comment by niksedk** [comment]
Perhaps just enabling "auto detect ANSI encoding" in Options -> Settings is enough for you?

**Comment by hucky291158** [comment]
Was it that simple? I'm all red-faced now...

Many, many thanks for all your great work (and for this swift reply, of course)!
