### ISSUE TITLE
Cancelling OCR

### ISSUE THREAD

**Issue by hucky291158** [SubtitleEdit/subtitleedit#1773]
If an OCR import is cancelled, the main SE window will open anyway.

Could you please prevent SE doing that?

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip
could you verify?

**Comment by hucky291158** [comment]
To be honest with you, I don't know if I can check it, since I've got SE 3.4.12 build 1 installed (Win7 x64).
 If I try to open a .sup file (Open with... pointing to SE 3.4.12 build 306 executable), then cancel the OCR window, SE build 1 will still open.
However, if you acknowledged the issue and done a fix, I fully trust you by now that it will work, I'll be patient until the next installer release...
