### ISSUE TITLE
[QUESTION] Slow startup

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1787]
Subtitle Edit has always been slow to start for me. It takes about 3 seconds the first time after restarting Windows and about 2 seconds every time after that. Is this something others are experiencing too?

I run Windows 8.1 on Intel i3-4130 @ 3.4 GHz, 8 GB DDR3, 7200 rpm HDD, so it doesn't look to me like the problem is on my end.

If this is caused by SE, is there something that can be done to optimize the startup time.

**Comment by xylographe** [comment]
If you close SE while a subtitle, video, audio, waveform are loaded, it will take some time to load these files again when starting SE later on. Otherwise starting SE should take less than a second, unless you've updated the portable version (installer version invokes ngen to compile IL during installation).

Opening the Settings dialogue OTOH is extremely slow (5 seconds at least).

Win7SP1 Intel i3-530 @ 2.9 GHz

**Comment by aaaxx** [comment]
This is just empty SE I'm talking about, with nothing loaded.

I *was* using the portable version, but now I've tried installing it and got the same results: 2.5 s after restart and 1.7 s after that, for both versions ([PassMark AppTimer](http://www.passmark.com/products/apptimer.htm)).

**Comment by marb99** [comment]
It's slow for me too, I've put this question some time ago on nikse home page

He he suggested use ngen

**Comment by niksedk** [comment]
The startup time has been optimized a few times (e.g. with custom loading of settings and custom loading of language file), so I'm not sure how much more can it can be improved (but do let me know if you find something that can be optimized).

The installer already uses ngen, but ngen will make SE portable startup a bit faster.

**Comment by heforfree** [comment]
i'm not sure helpfull or not
but please check
https://blogs.msdn.microsoft.com/dotnet/2012/10/18/an-easy-solution-for-improving-app-launch-performance/

**Comment by Deepcuts** [comment]
Most likely something messed up in settings.
I had ~18 seconds to open a srt file on a i7 with SSD and 32 GB ram.
The only thing that fixed it was uninstall with the option to NOT keep the settings and a CCleaner for good measure before re-install.

**Comment by chorong761** [comment]
Even until now with version 3.5.9, I still encounter the slow starting issue like OP. Opening subtitle edit (without file) would take 3-4 seconds. Subtitle Edit is the setup installed version, on Windows 10/i7 5820k/Samsung 950 Pro, fresh OS install today.

**Comment by Det87** [comment]
Yeah this is an issue that would need some profiling. It's way more than just the C#.

I don't feel like disabling the video & waveform views helps all that much even.

**Comment by niksedk** [comment]
SE takes about 1.5-1.8 seconds here which is fine for me... I've profiled this a few times without any revelations:
![image](https://user-images.githubusercontent.com/1261331/54385448-ee62c580-4696-11e9-9a8f-4db3837f153a.png)

But, if someone could squeeze a few more milliseconds off the startup it would be nice :)
