### ISSUE TITLE
[QUESTION] “Import this VobSub subtitle?”

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1792]
Is there some particular reason for this dialogue popping up when drag-and-dropping or double-clicking an .idx or .sub file, because it's kind of annoying. It doesn't appear for .sup files or when using `File → Import/OCR VobSub`, so I don't really see the logic.

**Comment by niksedk** [comment]
So it should have "don't show again" option or don't appear?

**Comment by aaaxx** [comment]
Well, yeah. I mean, unless you added it to address some specific concern, why show it at all?
