### ISSUE TITLE
Newline in “Export custom text format...”

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1802]
Is there some other way to specify a newline  apart from leaving the box set to `[Do not modify]`? The problem with it is that it turns to literally "[Do not modify]" if you include anything else around it.

I'm trying to make a custom HTML format  and would like to set it to `<br/>[newline][tab]`, so that it displays like this:

```html
<p>
	First subtitle line,<br/>
	second subtitle line.
</p>
```

**Comment by xylographe** [comment]
Inserting HT (horizontal tab) in the newline template is rather inconvenient, while inserting CR and LF seems impossible.

Perhaps, the newline template should recognise '{tab}', '{cr}', '{lf}', and '{nl}' (`Environment.NewLine`)?

Like commit d8d5d790b63c2409ff9a8ce5cd802faa7f62fd95 ([`SubtitleEdit-3.4.13-issue1802.7z`](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)).

**Comment by aaaxx** [comment]
Looks good.
