### ISSUE TITLE
[ENHANCEMENT] Replacements in Multiple Replace should be saved after pressing Add button

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1803]
Currently, the "Add" button will just add the new replacement pair to the list without actually storing it until you click the potentially destructive "OK" button ("potentially destructive" because the newly added replacements are automatically checked). Hitting "Cancel" or "Esc" to close the window without replacing anything in the file will discard all newly created pairs.

Suggestions:

- make the "Add" button store the new replacement immediately when clicked
- don't tick the replacement's checkbox  automatically when created
- rename the confusingly named "OK" button to "Replace"

**Comment by xylographe** [comment]
Press Alt+F4 or click ⊠ (close button).

**Comment by aaaxx** [comment]
Interesting. I didn't think of trying that. However, I would still argue it makes more sense to also prevent Cancel and Esc from discarding new replacements: it's much more forgiving to the user and, besides, it's easier to delete a pair than to type it in again.

**Comment by xylographe** [comment]
> it's easier to delete a pair than to type it in again.

After importing one or more replacement-rule files it won't be that easy to restore the original replacement-rule list manually. :)

**Comment by aaaxx** [comment]
Yeah, I guess you're right. I only ever used a single replacement ruleset and didn't even know they are appended when you import them.

The whole workflow could do with a rethink in the future because it's not exactly intuitive. Maybe something like a single list of all replacement pairs that you can then link to from multiple named rulesets would be simpler to use (e.g. like it's done with Actions in [Mp3Tag](http://www.mp3tag.de/en/), if you've ever used it, but with Actions being global instead of specific to each Action Group) and everything being done right in the interface – no mucking around with import/export.

**Comment by aaaxx** [comment]
That's a part of it. Here's what it actually looks like: ![Mp3tag actions example](https://cloud.githubusercontent.com/assets/6186480/16254454/6323678e-3840-11e6-8232-90f62f9d6677.png)

You create and edit actions inside action groups and then you just select the action groups that you want to apply. They are applied top–down as they are ordered (both action groups and actions within them).

This generally works well. The main problem is that actions are tied to action groups, and you usually have dozens and dozens of convoluted actions. So, if you need to use them in another group, you'll have to duplicate them, and soon enough it becomes a nightmare to maintain. I tried to get them to make the actions global and use groups just as lists of pointers to actions but the developers there aren't crazy about changes, even much smaller ones than that.

I don't think there's really a need for global rules in SE, though, 'cause we only use simple replacements, and simply integrating the groups in the interface would be a good solution.

Here's what I think could work:
![subtitle edit - multiple replace](https://cloud.githubusercontent.com/assets/6186480/16259963/6aa16586-3865-11e6-9f1a-180947cb16fd.png)

Ideally, you'd be able to tick/untick both the groups and the replacements in them that you want to apply.

And highlighting of changes would be great, too.

**Comment by Elheym** [comment]
Off topic: grouping is similar to that specified in the second picture not yet implemented in SE 3.4.13? Or it doesn't work in Windows 7 x64?

**Comment by aaaxx** [comment]
It's not implemented yet. That's just my proposal.

Why? You like it?

**Comment by Elheym** [comment]
@aaaxx, yep, more like. Useful innovation. I have long wanted to ask him.
It is possible to try it? =) 
P.S. Missing an item "rename group".

**Comment by niksedk** [comment]
I'll give it a go... the high-lighting is not possible in winforms as far as I know.

**Comment by niksedk** [comment]
How does this work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip ?

**Comment by Elheym** [comment]
@niksedk, all work is great!
