### ISSUE TITLE
[BUG] "Replace with" field treats regex `\n` as environment newline

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1805]
It outputs `\r` literally and `\n` as `\r\n` (CRLF), at least on Windows.

The "Find what" field doesn't seem to have that problem. That is, it matches *only* CR when looking for `\r` and it will replace *only* CR if you try it, leaving LF in the source file.

**Comment by xylographe** [comment]
It's not a bug, it's intentional, see [Forms.MultipleReplace:202](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Forms/MultipleReplace.cs#L202).
If you are really sure you want a single linefeed try `\u000A`.

**Comment by aaaxx** [comment]
Ah, I see.

I'm not sure it's a good idea, though, since whoever knows how to use regex will expect both characters to function normally, especially when they already do function normally in the Find field.

**Comment by xylographe** [comment]
Wait a minute… Normally the `\n` in a replacement pattern is not a newline. Only substitution elements starting with `$` are recognised in replacement patterns.

[MSDN:](https://msdn.microsoft.com/en-us/library/ewy2t5e0(v=vs.110).aspx) *“Substitutions are the only special constructs recognized in a replacement pattern. None of the other regular expression language elements, including character escapes and \[…] are supported.”*

For example,
```
PS> [regex]::Replace('aXb', 'X', '\n')
a\nb
```

**Comment by aaaxx** [comment]
Wait, what? This comes as a total surprise to me. Every regex implementation in text editors I've seen allows them in replace patterns and treats them normally. So, what, you have to basically code a substitution rule for the substitution pattern to be able to use newlines in it when they're not part of the matching pattern?

**Comment by xylographe** [comment]
Well, SE replaces `\n` in the replacement pattern with a literal newline (`Environment.NewLine`), and passes the resulting replacement pattern to the .Net regex implementation, which takes care of the `$` substitution elements (if any).

Other character escapes, like `\a`, `\t` or `\v`, do not appear to be very useful in a *subtitle* text?
In most subtitle formats control characters will be either harmful or prohibited (XML 1.0, for example, prohibits C0 controls, except for U+0009, U+000A, and U+000D).

**Comment by aaaxx** [comment]
What about `\n`-delimited files? I remember running into a couple of those in the past. They could end up with with mixed newlines.

**Comment by xylographe** [comment]
In theory,

1. ST parsers create multi-line paragraphs with `Environment.NewLine` delimiter.
2. Internal processing (e.g., FCE) uses `Environment.NewLine` delimiter in multi-line paragraphs.
3. ST exporters are responsible for generating output adhering to their format specification. Text based formats like SubRip may write platform-dependent `Environment.NewLine`, cr+lf, lf-only, cr-only, or whatever their specification requires.

Mixed newlines would most likely indicate a bug (unless explicitly requested in custom text format).
