### ISSUE TITLE
DCP D-Cinema Interop with tag to specific font file

### ISSUE THREAD

**Issue by F5System** [SubtitleEdit/subtitleedit#181]
In DCP-Interop XML standard it is possible to set font file which is locate near subtitles in DCP directory which cinema server will use to show subtitles. It works using this string:
<LoadFont Id="theFontId" URI="Arial.ttf"/>

In XML file it looks like:
<SubtitleID>45c56f55-ceff-4167-a0ea-f2924c65df42</SubtitleID>
<MovieTitle>Movie Title</MovieTitle>
<ReelNumber>1</ReelNumber>
<Language>English</Language>
<LoadFont Id="theFontId" URI="Arial.ttf"/>
<Font Id="theFontId" Color="FFFFFFFF" Effect="border" EffectColor="FF000000" Italic="no" Size="42" Script="normal" Underlined="no" Weight="normal">

Can you implement this feature by manually writing down font's name in options or may be by specifying font file when saving subtitle to disk? I think first is better when you work with a lot of subtitles with same font.

Thank you.

**Comment by felagund** [comment]
BTW, how do I sent default values for this? (FadeUpTime set to non-zero value is unfortunate, I think)

**Comment by niksedk** [comment]
@felagund: And what would be a reasonable default value (in frames)?

**Comment by felagund** [comment]
From my own going to cinemas, I think 0 is widely used. Subtitles just appear in a cinema, they do not fade in and out. Usually you have little time for them, so you do not want to cut it further by fadeout and fade in.

**Comment by felagund** [comment]
From my own going to cinemas, I think 0 is widely used. Subtitles just appear in a cinema, they do not fade in and out. Usually you have little time for them, so you do not want to cut it further by fadeout and fade in.

Anyway, I think it wouldbe great if user could configure this for herself. Language, for example, cannot have a reasonable default.

**Comment by niksedk** [comment]
@felagund: How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?
(default value will be 0 for a fresh install)

**Comment by felagund** [comment]
Great, I confirm the defaults. Fade up/down was available even before, I think. Thanks!

BTW, this can bre closed, I think the OP's problem is solved via your response too.
