### ISSUE TITLE
Space in shortcuts

### ISSUE THREAD

**Issue by lilhand** [SubtitleEdit/subtitleedit#1816]
I've always used the Ctrl+Space shortcut to pause/unpause video. Since last update, when I use the shortcut it works but also adds a space to the text box. Is this a bug or is there a way to change this?

Thanks in advance.

**Comment by niksedk** [comment]
It does not add spaces to the text box here (Win10)... what os are you on?

**Comment by lilhand** [comment]
I'm on Windows 10 too.

**Comment by lilhand** [comment]
Hey, I wanted to let you know, just in case it helps. This only happens when MPC-HC is selected as the player, it doesn't happen with Directshow or mpv. I don't have VLC to try it.

**Comment by OmrSi** [comment]
@niksedk I just found that these two are related, One of them should be closed:
https://github.com/SubtitleEdit/subtitleedit/issues/2852 https://github.com/SubtitleEdit/subtitleedit/issues/1816

**Comment by OmrSi** [comment]
@niksedk This is also closed with https://github.com/SubtitleEdit/subtitleedit/commit/6df51feab01dfd9e9e2d24126726e39d344d2550
