### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by homermarin** [SubtitleEdit/subtitleedit#1826]
![image](https://cloud.githubusercontent.com/assets/20269524/16546774/e3637b22-411a-11e6-9f16-f73683da19a4.png)

I keep getting this error after I export as Final Cut Pro, but only when I use _boxes_ for the border.
I'm using Win10.
When this happens, I have to uninstall and delete all settings (where can I find the settings to delete them without uninstalling?). Export works one time, but after that one time, this error keeps coming and it can only be fixed by uninstalling and choosing not to keep the settings.

**Comment by xylographe** [comment]
Duplicates issue #1790 
Fixed in commit 6f6f9e7fd02a399ada6b2457d92294c626f86c82 (any [SE Beta](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0) >= 3.4.13.10)

`%APPDATA%\Subtitle Edit\Settings.xml`
