### ISSUE TITLE
Convert from wsrt

### ISSUE THREAD

**Issue by serpico1** [SubtitleEdit/subtitleedit#1831]
Can Subtitle edit convert from wsrt to srt. SVT play use wsrt instead of srt?

**Comment by niksedk** [comment]
Yes, SE can load wsrt files - tags most wsrt tags will be removed automatically and file will be saved as srt

**Comment by serpico1** [comment]
Ok it works but when i play an mp4 file with external subtitle converted from, wsrt to srt in my bluray player i get some characters on the left side and on the right side of the subtitle but the subtitle display correct character. It is possible to remowe that from beginning and the end.

**Comment by niksedk** [comment]
Could you make the wsrt subtitle available? (you can also email it to me if you don't want it public)

**Comment by serpico1** [comment]
Try this wsrt file.

**Comment by niksedk** [comment]
thx for the file - could you test latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip

**Comment by serpico1** [comment]
Now i test the latest beta you link to and it seems to work. I download Movie with vtt subtitles and open in SE and just save as srt and it seems to work in my standalone player good.
Why cant i attach file here on site i send you mail again.

I also wonder if there is enough to just open subtitle file and save as srt its there no more to do.

**Comment by niksedk** [comment]
As @aaaxx found out the e.g. <33> tags are colored in SVT... do you prefer italic or the colors from SVT? Are the colors used to indicate a person not visible speaking?

**Comment by niksedk** [comment]
yes, it's enough to just save the file - the wsrt tags are removed when loading.

**Comment by serpico1** [comment]
Hi What do you mean with prefer italic or colors from svt?

**Comment by niksedk** [comment]
A subtitle like this:
`
2
00:00:43.000 --> 00:00:48.840
<33>Nu ska han serva</33>
<33>och har sin fjärde match-boll.</33>
`
has a 33 tag which seems to indicate a person speaking which is not visible on the screen - normally this is shown by using italic - but SVT uses colors...

**Comment by serpico1** [comment]
Have you test the files i mailed you. It seems like svt use different files sometimes with and sometimes without the 33 tag.

**Comment by niksedk** [comment]
Yes, looks fine to me... do you see anything strange?
The `i` tags are made to make text italic, e.g. `<i>italic text</i>`
If you want to remove all formatting via SE, select all lines in the list view, right click and choose "Normal (remove formatting)".

@aaaxx comment was here: https://github.com/SubtitleEdit/subtitleedit/commit/73d4e829748ad4349253438d1b6c3a2872f01cff

**Comment by serpico1** [comment]
I f i know right the only i need to do are just open wsrt or vtt file ans just save it in SE. I have a lot of subtitle files i want to convert can i use batch?

**Comment by niksedk** [comment]
Yes, `Tools -> Batch convert` should work fine :)

**Comment by serpico1** [comment]
Have you make some Changes in the beta version you told me to download?

**Comment by niksedk** [comment]
I don't think so, but you can download latest beta here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip

**Comment by serpico1** [comment]
I use this already. It is necessary to have exactly same name on the subtile as the Movie fil`?

**Comment by serpico1** [comment]
Now i have test and it works really great with the subtitles i have batch convert and it seems to work fine in my bluray player. Thanks again

**Comment by aaaxx** [comment]
As far as I can tell, the colour tags are used primarily for differentiating speakers, not for off-screen voices. You can see it in action at [http://www.svtplay.se](http://www.svtplay.se). You can also "View Page Source" with your browser and search for ".wsrt" to get the file's url.

So it's probably best to just remove them or, if SE uses those sort-of-nonstandard `<font color="#FFFF00">` SRT tags, replace them with that.

**Comment by serpico1** [comment]
I know what you mean now i have seen it in the beginning og some program when they are present some program the subtitl e wiews like you wrote and when the program start it works fine. You wrote i can remowe these character with SE how do i do that which option i use?

**Comment by aaaxx** [comment]
That post was actually meant for Nikse to suggest how to handle them in SE. In the latest beta they are automatically replaced with italics (`<i>…</i>`) because he thought colour is used only for off-screen dialogue, and italics are usually used for the same purpose. So you could remove all italic tags but then you would, obviously, lose any meaningful italics that might have been in the original file.

**Comment by niksedk** [comment]
The 5-6 subs I've checked do not have italics and tags are used for off-screen dialogue...
