### ISSUE TITLE
Extract all subtitles from MKV in "Batch convert"

### ISSUE THREAD

**Issue by Ede123** [SubtitleEdit/subtitleedit#1838]
Subtitles can be extracted from MKV files during batch convert, but apparently only the first subtitle track is extracted.

It would be helpful if (at least optionally) all subtitle tracks could be extracted and (in order to prevent collisions) the track number+language could be appended to the file name of the subtitle file saved to disk.

**Comment by xylographe** [comment]
Command line conversion (e.g., `SubtitleEdit /convert *.mkv SubRip`) extracts most (not VobSub / PGS) supported subtitle tracks.

Run `SubtitleEdit /?` or `SubtitleEdit /convert /?` for usage info.

**Comment by niksedk** [comment]
Fixed in #3297
