### ISSUE TITLE
[RFE] When doing an online translate

### ISSUE THREAD

**Issue by ukdtom** [SubtitleEdit/subtitleedit#1852]
When doing an online translate, from like Google, and translating the file:
``<MyMedia>.srt`` into like danish, it would be nice if the proposed filename to save as was:

``<MyMedia>.<Language_Code>.srt``

Also would be nice, if a prefs option was present, that could force insert a first line into the file saying:
"Translated via Google Translate by SubTitleEdit"

Above line I use myself, and is nice as a search param, when trying to determine, if a human translated file might be a better match

**Comment by niksedk** [comment]
@ukdtom: thx for your input :)
SE should now propose the file name `<MyMedia>.da.srt` after translating into Danish ... you can test it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip

About the second issue: I don't think a lot of ppl would want this - and hopefully ppl don't just use auto-translated subtitles raw...
