### ISSUE TITLE
Navigation shortcuts

### ISSUE THREAD

**Issue by techtonik** [SubtitleEdit/subtitleedit#1854]
It is not clear how to navigate through video / waveform with keyboard shortcuts. Would be nice to those somewhere in the Help menu.

**Comment by niksedk** [comment]
It's in the help page: http://www.nikse.dk/SubtitleEdit/Help#shortcuts
But also check Options -> Settings -> Shortcuts... here it's possible to customize it to your liking.

**Comment by techtonik** [comment]
I expected to find something offline in Help.
