### ISSUE TITLE
OCR failure with index out of range

### ISSUE THREAD

**Issue by Sinnlosvoll** [SubtitleEdit/subtitleedit#1857]
When trying to ocr the attached pgs subtitle with tesseract it doesn't display an image but instead it shows this exception:
![se_pgs_exception](https://cloud.githubusercontent.com/assets/3251999/17076272/675c0004-50af-11e6-8079-2bbd1a0888f3.png)
Version is 3.4.13
[subtitle.zip](https://github.com/SubtitleEdit/subtitleedit/files/379391/subtitle.zip)

**Comment by niksedk** [comment]
Hi, could you give latest beta a test run: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip

Do you know which program created the file? The Blu-ray sup segment are separated in multiple mkv elements (and not in just one like files made with mkvtoolnix).

**Comment by Sinnlosvoll** [comment]
Yeah, the new version does the trick.

The original mkv was created with ffmpeg from a blu ray source, the subtitle extracted via mkvtoolnix.
Those subtitles also break ffmpeg when it copies them over to a new mkv.
Some error with 

> non monotonically increasing dts

Thanks a lot for fixing it though.

**Comment by richb93** [comment]
I've ripped an HD-DVD using MakeMKV and extracted out the sub and idx files, sadly SubtitleEdit is giving me this problem again I'm afraid - happy to submit files for testing. Using the latest version.
