### ISSUE TITLE
[Main] - Very slow resizing.

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1863]
I think we need to do something about **Main-Form's** resizing, it's very slow.

The main problem seems to be with the resizing logic. Its seems to be reloading the entire subtitle for every time main **form** changes size which is kind expensive. 

I saw a comment that says: _Due to strange bug in listview when maximizing_ (Main.cs). 
This comment seems to be a aged comment since there have been a lots of changed to SE I think the bug is probably fixed, isn't it? I couldn't produce it so... /cc @niksedk

**Comment by niksedk** [comment]
Fixed mostly in 980b2be0b6f45a0474759b58254a374a8252b8b9
