### ISSUE TITLE
“Windows Forms Thread Exception” when using Export function

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1864]
Using the latest version, 3.4.13, here's what I get for any of the options in the `File → Export` menu.

The interesting thing is it worked the first time after updating to this version.

![Windows Forms Thread Exception dialogue window](https://cloud.githubusercontent.com/assets/6186480/17090125/d7ce5c7c-522d-11e6-930c-b1c6e9d6f00d.png)

**Comment by niksedk** [comment]
Have you tried latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip ?

**Comment by aaaxx** [comment]
OK, beta seems to work fine.

**Comment by niksedk** [comment]
Perhaps we should release 3.4.14 a bit sooner  - what do you say?
(apply/ok in "Remove text for HI" is also somewhat buggy....)

**Comment by aaaxx** [comment]
Doesn't really matter to me as I don't make bitmaps often, but I guess it's a good idea.

Also see if you can squeeze these issues in: https://github.com/SubtitleEdit/subtitleedit/issues/1872, https://github.com/SubtitleEdit/subtitleedit/issues/1873.

**Comment by ivandrofly** [comment]
Close? @niksedk

**Comment by niksedk** [comment]
Yep
