### ISSUE TITLE
Exporting to bitmap format: inconsistent size for simple and non-simple rendering

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1872]
For the same font size, the "Simple rendering" option will render bigger text than the non-simple one. The right size out of those two is the one produced by non-simple rendering.

By the way, what's the deal with that simple rendering? Why would anyone use it if it renders worse?

**Comment by niksedk** [comment]
Simple rendering is an older API from Microsoft, but it handles some languages better - Arabic and few others (a bit strange MS never fixed this).

**Comment by aaaxx** [comment]
Ah! But why the different sizes?

**Comment by niksedk** [comment]
I don't know why the font size renders differently and I cannot see any clear system in it...
