### ISSUE TITLE
Exporting to bitmap format: weird behaviour with background box selected

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1873]
When you first select "Box for each line" or "One box" from Border style dropdown, the border will be huge, covering the whole preview area. To make it snap to text you need to click Border color button and then OK (even if you don't change the colour).

Also, a bit of padding in those boxes wouldn't hurt. I think 0.25 ems left and right would look about right.

**Comment by niksedk** [comment]
I cannot re-create this... could you post a screenshot?

**Comment by aaaxx** [comment]
Sure.

- [HD, broken](https://cloud.githubusercontent.com/assets/6186480/17271433/8ace1b54-567b-11e6-90cd-a1c12e888066.png)
- [HD, fine](https://cloud.githubusercontent.com/assets/6186480/17271431/8ac2736c-567b-11e6-9c87-7f50f7d1f35d.png)
- [SD, broken](https://cloud.githubusercontent.com/assets/6186480/17271434/8ad0e550-567b-11e6-9b58-74fd88b23197.png)
- [SD, fine](https://cloud.githubusercontent.com/assets/6186480/17271432/8ac3b7f4-567b-11e6-9053-a3fd8d536884.png)

**Comment by niksedk** [comment]
Hm, still cannot re-create this... what OS are you on?

**Comment by aaaxx** [comment]
Windows 8.1.

**Comment by niksedk** [comment]
See #1980
