### ISSUE TITLE
VTT to srt

### ISSUE THREAD

**Issue by serpico1** [SubtitleEdit/subtitleedit#1875]
SVT use VTT sometimes instead of WSRT on subtitles how can i convert from VTT to SRT?
When i use batch convert the result are still VTT extension.

**Comment by niksedk** [comment]
Are you sure the "Output format" is "SubRip" in batch convert?
(I just converted a few files here with correct extension)

**Comment by serpico1** [comment]
I use this settings you can see in the attached file.

![urklipp-1](https://cloud.githubusercontent.com/assets/20015055/17278608/33afb88c-5761-11e6-9adc-28ff36f35f29.jpg)

**Comment by niksedk** [comment]
What version of SE are you using?
What files are in your "C:\Konvertering" folder after a convert?

**Comment by serpico1** [comment]
I use 3.4.1.3 build 106
Now i have test again and it seems to work. Maybe i do something wrong Before.  There are both the vtt and the srt file. And it work fine in my standalone player. Do you know why svt are using wsrt or vtt instead of srt?
Thanks for your quick help and a wonderful program.

**Comment by niksedk** [comment]
Cool, I'm glad it's working now :)
Sorry, I don't know know why SVT uses wsrt/vtt instead of srt (but it could be because wsrt/vvt are more standardized)
