### ISSUE TITLE
Feature Request: google voice recognition

### ISSUE THREAD

**Issue by njozsef** [SubtitleEdit/subtitleedit#1878]
Hi All.

I think is good feature the voice recognition for "clean-voice" type video production (studio talking etc.)
THX

**Comment by JeanDown123** [comment]
I also voted to add that option to Subtitle Edit. I think it would be relatively easy.

Provisionally Autosub can be used to translate video files or audio via a single click (EASY).
Depending on the language, sound quality, accuracy can vary from 100% to 0%.
I tried it with English and Spanish, 80% and 100%
Japanese only 0-10%.

https://github.com/agermanidis/autosub
Install Step by Step for Windows.
https://github.com/agermanidis/autosub/issues/31
.
Another option also is:
https://github.com/Uberi/speech_recognition,
This gives you the advantage of using multiple Speech recognition engine / API support
CMU Sphinx (works offline)
Google Speech Recognition
Wit.ai
Microsoft Bing Voice Recognition
api.ai
Houndify API
IBM Speech to Text

**Comment by niksedk** [comment]
SE beta now has speech recognition built-it:

Open a video and click on "Video/audio to text"
![image](https://user-images.githubusercontent.com/1261331/147871741-0d2106f3-ffa9-409a-b40b-e9df5a4ca6d0.png)


https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
