### ISSUE TITLE
Compile SE with NET Framework 4.6.2 some plug-ins not load and crash

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#1880]
hi...

if compile SE with new NET Framework 4.6.2 some plug-ins not load given an error message

plug-ins I tested, word spell check, AmericanToBritish and RemoveUnicodeCharacters

this plug-ins crash and not load if compile SE with NET Framework 4.6.2

**Comment by marb99** [comment]
Can anyone else confirm this or is there any solution to compile with 4.6.2 netframework???

**Comment by niksedk** [comment]
Works fine here... a bit late, sorry.
