### ISSUE TITLE
Respect Default Matroska Language

### ISSUE THREAD

**Issue by mkver** [SubtitleEdit/subtitleedit#1896]
Hello,

according to the [Matroska specifications](https://matroska.org/technical/specs/index.html) the default language in Matroska is English, i.e. if a track doesn't have a language element, its language is English. Subtitle Edit currently doesn't honour this: Upon opening of a Matroska file with multiple subtitle tracks at least one of which does not contain a language element I am asked to select a subtitle track; the non-English tracks are shown with their country code, the English ones without.
MKVToolNix doesn't write a language element for English for years. So this affects lots of files.
Thanks for your work on Subtitle Edit.

Andi

PS: If I am not mistaken, it's not forbidden to write the "Eng" element.

**Comment by niksedk** [comment]
Thx for the info :)
Should be fixed in next update. You can also test it in latest beta (or compile from latest source): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip (portable version)
