### ISSUE TITLE
Bug in Auto-Translate (By Google)

### ISSUE THREAD

**Issue by JeanDown123** [SubtitleEdit/subtitleedit#1901]
Sometimes, Auto-Translate it does not work properly. Disorder, mix or ignores lines, so confused.
As shown in the figure below.
Japanese test is performed to English
Each line (Original) contains the line number (Line1, Line2, respectively)
![bugauto-translate](https://cloud.githubusercontent.com/assets/20913258/17639184/719984e0-60b5-11e6-8561-1b0dd457f4df.jpg)
As after the translation is observed, it does so erroneous.

On line 5 makes the translation of the line 4.
In line 6 left blank.
In line 7 puts the translation of the line 5,3 and 7.

Tested in Windows 8, XP in all version Subtitle Edit.

the file is attached.
Change txt to ass
[Bug_SubtitleEdit_Jap-English.ass.txt](https://github.com/SubtitleEdit/subtitleedit/files/416266/Bug_SubtitleEdit_Jap-English.ass.txt)

**Comment by Shadowviewer** [comment]
I think i have the same problems...he leave me most of the lines Un-translated 
maybe we have the same problem ?
[https://github.com/SubtitleEdit/subtitleedit/issues/2016](url)

**Comment by niksedk** [comment]
Should be fixed in SE 3.5
