### ISSUE TITLE
The last additional line confuses comparison

### ISSUE THREAD

**Issue by vsemozhetbyt** [SubtitleEdit/subtitleedit#1910]
If the left subtitle has additional lines in the end, "Next difference" does not work and alignment is incoherent.

![se](https://cloud.githubusercontent.com/assets/10393198/17819651/9614ca4a-6651-11e6-820e-ca3304d0298d.gif)

**Comment by niksedk** [comment]
ivandrofly made a fix :)
You can verify/test it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip

**Comment by vsemozhetbyt** [comment]
@niksedk Thank you! Is there a portable beta? The zip contains only the installer.

**Comment by ivandrofly** [comment]
@vsemozhetbyt  try this https://www.dropbox.com/sh/thgk5507tteg6ze/AADwZeDNK8ei6hn3u2Zvtnzpa/SE-3.4.13.286.7z?dl=0

**Comment by vsemozhetbyt** [comment]
Yes. it's fixed. Thank you.
