### ISSUE TITLE
Could Baidu Translation be added to auto translation drop list?

### ISSUE THREAD

**Issue by pendave** [SubtitleEdit/subtitleedit#1915]
As you know google services are all forbidden by Chinese Gov, so we have to use proxy settings if we want to use Google Translation.

Could you please add Baidu Translation toolset?

http://fanyi.baidu.com/

Thanks a lot!

**Comment by niksedk** [comment]
Gave it a quick try - could you try to unpack this file to your "plugins" folder and see what happens?
https://github.com/SubtitleEdit/plugins/releases/download/v.1.1/BaiduTranslate.zip

**Comment by pendave** [comment]
I test this plugin but it does not work

{"error":8,"msg":"ARG_NULL"}

![o ksu5 dcqyze5_w6s4l 9](https://cloud.githubusercontent.com/assets/1331881/18041658/bfccb93a-6ded-11e6-9267-79186b21998a.png)

**Comment by pendave** [comment]
If Baidu translate is not free to use, maybe Youdao translate could be working:

http://fanyi.youdao.com

http://fanyi.youdao.com/translate?smartresult=dict&smartresult=rule&smartresult=ugc&sessionFrom=null

**Comment by niksedk** [comment]
@pendave: You can toggle the log by pressing "F1"... what does it say?
Do you know C# coding?

**Comment by pendave** [comment]
Sorry I have no knowledge of C# coding but python.

**Comment by pendave** [comment]
@niksedk   I got some python codes using the test API key and it works well in DOS Command line.

http://www.bathome.net/viewthread.php?tid=44021&pid=200098&page=1&extra=page%3D1#pid200098

Can you fix this BaiduTranslate.dll plugin with the key? Thanks, hope for the update.

```
appid     = '20151113000005349'      #【测试用的 appid】
secretKey = 'osubCEzlGjzvw8qdQc41'   #【测试用的 secretKey】
```

**Comment by niksedk** [comment]
@pendave: thx for the info :)
I've made two different methods for translating in latest plugin (v0.4) - see combo box next to "powered by Baidu".
First one is the api from your comments (adapted code from www.okbase.net) and the second one is the same api as the web page uses.
(it's available from SE via File -> Plugins)

How does it work?

**Comment by pendave** [comment]
@niksedk Thanks it works well. Baidu translation is another selection now.
I prefer to use Google translation plugin as the result is much better, though guys from China have to set PROXY to cross the Great Fire Wall of China.
![_2j8 zdaw 1149vvf1 lt m](https://user-images.githubusercontent.com/1331881/26971527-1d639e6a-4d40-11e7-8936-277e3e1757c9.png)

I also write some Python code for translating srt files using Google, Baidu and Youdao. The translated result is the same as what done throught Subtitle Edit.
Google is outstanding almost!

**Comment by pendave** [comment]
Full context translation means the program will get rid of the index number & timeline code & \n or \r\n or replace it with blank space, to connect the whole lines of sentences. Actually the meaning is better than one line to one line translation by API.

![mlq m lfzz 39g 4vyos4je](https://user-images.githubusercontent.com/1331881/26973096-4c2cef38-4d47-11e7-95eb-b5583d2f1bd0.png)
![vi4lei m s5_ b 7h6 3ak](https://user-images.githubusercontent.com/1331881/26973104-56d3706a-4d47-11e7-9ca7-3b4389dd4e20.png)

**Comment by pendave** [comment]
Also the workable Google translation service deblocked is  https://translate.google.cn/m?q=
Such as:
https://translate.google.cn/#auto/zh-CN/Full%20context%20translation%20means%20the%20program%20will%20get%20rid%20of%20the%20index%20number%20%26%20timeline%20code%20%26%20%5Cn%20or%20%5Cr%5Cn%20or%20replace%20it%20with%20blank%20space%2C%20to%20connect%20the%20whole%20lines%20of%20sentences.%20Actually%20the%20meaning%20is%20better%20than%20one%20line%20to%20one%20line%20translation%20by%20API.

You need to add a `中国国内版Google` which is working for guys from China without using PROXY.

Just use `.cn` instead of `.com` I think. :)
![t9 _6v58 cv8479w qvq91r](https://user-images.githubusercontent.com/1331881/26973709-4fd3345a-4d4a-11e7-86e8-3c224b54f28b.png)
