### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by Jeck70** [SubtitleEdit/subtitleedit#1926]
I use SE version 3.4.13. and tried to export some subtitles as EDL. It worked only a single time. Now I always receive the following message no matter what kind of format I am choosing to export. 

![export error](https://cloud.githubusercontent.com/assets/21238865/17966690/129d4ea0-6ac3-11e6-9cec-3a84a939d08e.png)

Do you have any idea how to solve this?

Thanks,
Johannes

**Comment by xylographe** [comment]
IIRC this has been fixed in [SubtitleEditBeta](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip) (or recent beta from [this folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)).

**Comment by Jeck70** [comment]
Great. Thanks a lot.
