### ISSUE TITLE
[Feature] Read teletext subtitles from MPEG TS

### ISSUE THREAD

**Issue by claunia** [SubtitleEdit/subtitleedit#1928]
It would be great if alongside DVB subtitles the teletext ones would be supported also.

**Comment by niksedk** [comment]
Yes, that would a great feature !

I've been working in this for a while and now SE hopefully has some support for this via File -> Open... choose .ts/.m2ts file:
![image](https://user-images.githubusercontent.com/1261331/68086269-25fec780-fe4a-11e9-9ce3-f0765205ff57.png)


Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

@mkver: Please also take a look if you have time :)

_Project X is a great program, but I nearly always have trouble with the UI..._

**Comment by claunia** [comment]
@niksedk I'll try asap, thx
