### ISSUE TITLE
Index of limit

### ISSUE THREAD

**Issue by malgane** [SubtitleEdit/subtitleedit#1932]
Hello

While i want to open en TS file on the application I get errors. Running on W10 64 bits with subtitle 3.4.13

![error](https://cloud.githubusercontent.com/assets/21320938/18068091/09074ed8-6e40-11e6-8034-18cd76a03a29.png)

**Comment by malgane** [comment]
http://gofile.me/2ao4K/78LizNzlq

**Comment by ivandrofly** [comment]
Close? @niksedk  | @xylographe

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip
