### ISSUE TITLE
EBU STL export uses NewLine instead of vertical position

### ISSUE THREAD

**Issue by ghoogland** [SubtitleEdit/subtitleedit#1938]
Summary:
In EBU STL files (converted from 890) we notice `<br />` at the start of single lines.
Tools like FAB show these lines too high: not on the bottom line.

Investigation:
Cavena890 stores double subtitle lines in separate fields (line 1 & line 2)

When SubtitleEdit (SE) loads Cavena890, it joins double lines in one single string.
It adds a NewLine to separate the lines inside the string, even if only line 2 contains text (and line 1 is empty).
This shows as `<br />` in the UI, at the start of each single line.
..which was not present in the original file...

(See Cavena890.cs, line 758:
`p.Text = (line1.TrimEnd() + Environment.NewLine + line2).TrimEnd()`; )

When exporting to EBU STL (in Ebu.cs) the newline is not removed, but stored as 8A Hex.
Some tools like FAB cannot deal with this and show the line too high.
probably because the STL export uses the same vertical position for each line (14H),
and FAB ignores the NewLine.
(While in the original STLs, I see 14H for double lines and 16H for single lines.)

Ideally,
- Omit NewLine at the start of a line, during export to STL.
- Specify a correct vertical position for each line instead. 
  But to which value? What is the standard? is 14H and 16H always correct?
  (Not specified in https://tech.ebu.ch/docs/tech/tech3264.pdf)

**Comment by ghoogland** [comment]
Tested the fix with FAB: This fixes it, but introduces another issue: FAB shows everything left aligned.
Sofar, I did not find the cause. Binary the STL looks fine, and justification is 00 (=unchanged).
While the 890 showed the subtitles centered. So this seems to be a separate problem.

**Comment by boriseetgerink** [comment]
@niksedk Are you open to setting the justification to centered if the justification of the source file is not known? This looks like a more sensible default. I'll see if I can create a pull request.

**Comment by boriseetgerink** [comment]
That justification code 00 instead of 02 might be because of an unusual STL file. I'll do some more research on this.

**Comment by boriseetgerink** [comment]
When saving a Cavena890 file it does write the justification to the file: https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/SubtitleFormats/Cavena890.cs#L399

But when loading a Cavena890 file it doesn't read the justification anymore: https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/SubtitleFormats/Cavena890.cs#L731

**Comment by ghoogland** [comment]
issue can be closed: code is correct
