### ISSUE TITLE
SubtitleEdit CLI /fixcommonerrors does nothing

### ISSUE THREAD

**Issue by elbaelrog** [SubtitleEdit/subtitleedit#1953]
Hi, I'm trying to run SubtitleEdit in CLI with /fixcommonerrors but it does nothing? Even in the UI version batch mode the fixcommonerrors wont work.

**Comment by niksedk** [comment]
UI batch convert works fine here... do you go into the settings dialog and checked some rules?

**Comment by elbaelrog** [comment]
Yes, the only rule I checked was "fix subtitles with more than two lines" but the subtitles still as 4 lines. I'm using Scenarist file (.scc)

**Comment by niksedk** [comment]
Ah, then you probably need shorter lines... max 32 chars on each line!
