### ISSUE TITLE
“Fix uppercase ‘i’ inside lowercase words” needs some exceptions

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1955]
Irish name prefixes:
- Mc
- Mac
- O'

For example, I've just run into "McInturff".

There might be similar cases in other languages, but I can't think of anything right now.

**Comment by ivandrofly** [comment]
Can you provide full text example?

**Comment by aaaxx** [comment]
[Sure](http://pastebin.com/r4U6V83y), but how is that gonna help? The only rule you need to add is to check if Mc/Mac/O' precede the "l".

**Comment by ivandrofly** [comment]
Thx :)



> Sure, but how is that gonna help?

I was just asking for **Mc/Mac/O' precede the "I".** though.

**Comment by aaaxx** [comment]
Sorry, don't quite get what you mean? Do you still need something?

**Comment by ivandrofly** [comment]
> Sorry, don't quite get what you mean? Do you still need something?

Ah no-no! :)
