### ISSUE TITLE
[QUESTION] Why is it so slow and hardly using system resources?

### ISSUE THREAD

**Issue by drakanor** [SubtitleEdit/subtitleedit#1966]
OCR runs at about 5 to 10 subtitle rows / second for me. I have an i7 3 GHz, and while doing OCR it uses about 3% to 4% CPU. I'm using "OCR via Tesseract".

Is that normal behaviour or am I doing something wrong?

**Comment by niksedk** [comment]
Sorry, Tesseract OCR is slow... and SE does some extra re-tries is the words are not spelled correctly
