### ISSUE TITLE
Leon's Wishlist   :-)

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#1968]
After years of experience on SE, allow me to write down a wishlist hidden deeply in my heart:
- [ ] Allow setting start number while importing plain text.
- [ ] Allow using SPACE and/or TAB as line break symbol while importing plain text. (as test, it seems \s and \t cannot be currently used as line break)
- [ ] While appending subtitles. it would be nice to append right at the waveform cursor position. (to avoid annoying overlapping which has to be corrected every time)
- [ ] Allow Backward finding and replacing. (Currently it only supports finding/replacing the next match, not previous)
- [ ] Unbreak without automatically adding space.(very convenient for languages such as CJK)
- [ ] While splitting lines at textbox cursor position, it will be great to allow splitting timelines based on waveform cursor position, as well. (the current method is sort of a semi-automatic one, not ideal for many cases)
- [x] Not sure why the Split at Cursor Position tool fails to work for only splitting the first one or two characters, which is strange, hope it can be fixed. 
- [ ] Automatic Speech Recognition (ASR) based on existing timeline (for a single line or batch). It can be greatly helpful for workflow like below:
1. making timeline;
2. transcripting (via ASR);
3. reviewing.

I know it sounds crazy, but just imagine that, it can save typing work hugely! Not sure if there are any open source solutions for that. Anyway, FYI.  Thank you so much! :)

**Comment by niksedk** [comment]
Sorry, please create each issue in it's own issue... creating multiple issues in one issue really makes it hard to track/discuss much.

**Comment by LeonCheung** [comment]
Oh you are absolutely right! My apologize, will never ever happen again.  :P

**Comment by niksedk** [comment]
lol
