### ISSUE TITLE
Cavena 890, make diacritics mapping more complete

### ISSUE THREAD

**Issue by ghoogland** [SubtitleEdit/subtitleedit#1969]
Summary:
in Cavena890.cs: GetTextAsBytes() there is still missing some mapping of special characters (diacritics), which we notice in FAB. This shows as missing characters in some broadcastings.
I Reverse-engineered the mapping, using FAB, and will try to implement this in Cavena890.cs in the near future.

Details:
I have reverse engineered the Cavena 890 character code mapping, by generating a list of character codes as text and as bytes. I have read this in FAB and also converted to STL to be able to view it in SE.
Here is a summary of the mapping, according to FAB:

0x81, 0x41 = À ... 0x81, 0x5A = Z (capitals with accent grave)
0x81, 0x61 = à ... 0x81, 0x7A = z (lowercase with accent grave)
0x82, 0x41 = Á ... 0x82, 0x5A = Ź (capitals with accent aigu)
0x82, 0x61 = á ... 0x82, 0x7A = ź (lowercase with accent aigu)
0x83, 0x41 = Â ... 0x83, 0x5A = Ẑ (capitals with accent circonflexe)
0x83, 0x61 = â ... 0x83, 0x7A = ẑ (lowercase with accent circonflexe)
0x85, 0x41 = Ã ... 0x85, 0x5A = Z (capitals with tilde)
0x85, 0x61 = ã ... 0x85, 0x7A = z (lowercase with tilde)
0x86, 0x41 = Ä ... 0x86, 0x5A = Z (capitals with trema)
0x86, 0x61 = ä ... 0x86, 0x7A = z (lowercase with trema)
(Often 0x7A is followed by 0x7B, which maps to ij with same accent, so not y. For example, in case of trema, you see two layers of dots)
(I have to double-check range 0x84, 0x41 ... 0x84, 0x5A and  0x84, 0x61 ... 0x84, 0x7A  ... seems to have  caron)

I will implement this in Cavena890.cs in the near future.
I have attached my test files, to provide a complete overview:
- My generated 890 file
- The FAB-converted STL file.
However, when you load this STL in SE, you see that not all diacritics are displayed as they should be,
but as a normal alphabetic character, without the accent. 
So maybe loading the STL can be improved a bit too.

[TEST HEX CODES.zip](https://github.com/SubtitleEdit/subtitleedit/files/487279/TEST.HEX.CODES.zip)

**Comment by ghoogland** [comment]
Ok, I have a proposed fix ready.
See my pull request

**Comment by niksedk** [comment]
Fixed in #1970 :)
