### ISSUE TITLE
[BUG] Box - single and multi line it's broken

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#1980]
there is a bug in box single and multi line, 

the black box is to large.

in earlier versions work great and its broken in  SE 3.4.13 build 365

windows 10 pro

![capturar](https://cloud.githubusercontent.com/assets/7856897/18860135/715da8c2-8472-11e6-9528-73d678db8b94.PNG)

**Comment by aaaxx** [comment]
Check if this is the same as [this](https://github.com/SubtitleEdit/subtitleedit/issues/1873).

**Comment by marb99** [comment]
@aaaxx 

yes is the same

**Comment by niksedk** [comment]
Still cannot re-producte it...

**Comment by niksedk** [comment]
Is latest source any better?
Beta also updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip

**Comment by marb99** [comment]
@niksedk 

yes, fixed now :)

**Comment by niksedk** [comment]
:)
