### ISSUE TITLE
BorderStyle 4 in Advanced Sub Station Alpha detected as incorrect style

### ISSUE THREAD

**Issue by franontanaya** [SubtitleEdit/subtitleedit#1981]
The value 4 for BorderStyle in Advanced Sub Station Alpha is supported for color box text background, but it triggers an incorrect style warning on load. It doesn't affect anything else, but the warning is not necessary and may mask other style validation issues.

**Comment by niksedk** [comment]
Does this also happen in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip ?

**Comment by niksedk** [comment]
Can this be closed?

**Comment by franontanaya** [comment]
Still triggers the same warning dialog on 3.5. The value is preserved on Load → Save so it seems to be harmless. Although BorderStyle 4 wasn't in the 2002 spec doc it does works on MPlayer, VLC and ffmpeg.

**Comment by niksedk** [comment]
Border style 4 is supported now
