### ISSUE TITLE
Cannot open an AAC file as video

### ISSUE THREAD

**Issue by amn** [SubtitleEdit/subtitleedit#1982]
The application says with a dialog:
"There seems to be missing a codec (or file is not a valid video file)!" followed by the usual suggestion to install LAV Filters, and links to various DirectShow debugging utilities like GSpot, etc.

I have LAV filters installed. The x64 version, just as the app. I have tested the .AAC file I am trying to use (yes, I am subtitling audio, no video track) with Graph Studio Next to see if the DirectShow pipeline works. It does (with GSN). Why wouldn't Subtitle Edit open the media?

Windows 7 x64
Subtitle Edit 3.4.13
LAV Filters 1.68.1-x64

**Comment by niksedk** [comment]
thx for the info :)

Portable beta version updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip

**Comment by amn** [comment]
Those nasty spelling errors, ey? :)

On a more serious note, I thought DirectShow is capable of detecting the media container format itself? I am talking about the code in your program that hardcodes list of supported or recognized audio-only files.

As far as I remember reading, in DirectShow each splitter filter can define a pattern which when masked against potential source can tell DirectShow if said filter will parse the source (file, as an example). In addition, to support more complicated container formats where pattern matching simply cannot help reliably recognize the format, DirectShow also lets each splitter define a procedure which it calls for each splitter installed to see which of these returns success code as to indicate that the splitter has recognized the format and is able to parse the source. It calls this procedure for each splitter to build a list of these that are able to parse the source, and then selects one based on MERIT or other criteria that are built in to DirectShow.

All this implies to me that you don't have to hardcode supported multimedia formats when using DirectShow (can't give you any advice on your VLC-based player backend as I am unfamiliar with "libvlc.dll") -- when you are invoking DirectShow methods to attempt to build the playback filter graph automatically, if the graph can be built this means your media can be played, through one splitter or another, you don't have to know which or how. You can then query and see whether there is a video track, and audio track, or both (or multiple of each even). You would ideally behave differently in a situation where there is *no* video/audio track as opposed to a situation whether DirectShow gives you an error telling you that no suitable decoding/splitting filter could be found for video, audio, or both.

Anyway, I hope you find this useful, just a humble suggestion from a fellow developer. If I find time, I might want to fork your repository and assist! Either way, thank you for the useful program!
