### ISSUE TITLE
Release 3.5

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#1990]
Time for a new release... Tesseract dictionary download don't work for old version + much new stuff :)
I think the "Multiple replace", "Scene changes" + new sub formats are more than just a patch...

TODO:
- [x] General testing + (fixing bugs)
- [x] Test compare
- [x] Test "Binary image compare OCR"
- [x] Test "Multiple replace"
- [x] Test "Scene changes"

If you know any issue that should be included then do let us know :)

**Comment by aaaxx** [comment]
Can you decide on [this](https://github.com/SubtitleEdit/subtitleedit/issues/1792)?

**Comment by niksedk** [comment]
@aaaxx: ok, removed prompt.

What about showing videoplayer + waveform default for new users?

**Comment by ivandrofly** [comment]
Some minor fixes for ExportPngXml: https://github.com/SubtitleEdit/subtitleedit/pull/1992

**Comment by niksedk** [comment]
Compare is still somewhat buggy...

**Comment by ivandrofly** [comment]
> Compare is still somewhat buggy...

Did you find something?

**Comment by niksedk** [comment]
Show only differences... if I delete first line in a subtitle.

**Comment by ivandrofly** [comment]
Does it throw or something...?

**Comment by niksedk** [comment]
It works :)
I was comparing the "compare function" to 3.4.12 which only showed differences in text when starting compare which seems like what we want most of the time, right?

**Comment by niksedk** [comment]
Fixed a few issues in fb5c619fcd7a1d5cd1c4ed905d791e7786550888 - extra lines where hidden when showing only changes (regression) + deleted lines (or new) are not shown correct (with red empty line) if next line has same duration (old bug) + coloring in listview2 more consistent (old bug).
@ivandrofly: Does it look/work okay  ?

**Comment by ivandrofly** [comment]
Looks good :); I have made some minor changes: https://github.com/SubtitleEdit/subtitleedit/pull/1995

**Comment by niksedk** [comment]
Only found a renaming bug in the "Multiple replace"... a8febaca51a9ab9df464c311442327add61cccfa

**Comment by Elheym** [comment]
Perhaps, it is useful to add in the "Multiple replace" the ability to remember window position? Because after you close the program window position is reset.

**Comment by Elheym** [comment]
Sometimes shows not the whole text.

![bandicam 2016-10-09 15-00-34-977](https://cloud.githubusercontent.com/assets/14152676/19220528/187f245e-8e38-11e6-99ba-0a6fdf435650.png)
![bandicam 2016-10-09 15-01-18-329](https://cloud.githubusercontent.com/assets/14152676/19220530/18840028-8e38-11e6-997e-aa6c38879abc.png)
![bandicam 2016-10-09 15-08-15-334](https://cloud.githubusercontent.com/assets/14152676/19220529/18833daa-8e38-11e6-99ae-d1fba6ef80ff.png)
![bandicam 2016-10-09 15-11-30-645](https://cloud.githubusercontent.com/assets/14152676/19220531/18857fd4-8e38-11e6-949f-84c62b6d5b6d.png)

**Comment by ivandrofly** [comment]
Why are you trimming the lines when Comparing (we wanna see the difference right)?
Subrip will trim end when loading, should it be when by FCE?

**Comment by niksedk** [comment]
@Elheym: Sorry, I can move something a few pixels... but I think you have to shorten the texts.

**Comment by Elheym** [comment]
#2001

**Comment by niksedk** [comment]
@Elheym: thx :)

Besides the fixed bug in compare regarding save/load settings (87191e699b73dc32ccdbd8df3739de68fa379def), compare still have problems - show only differences is still buggy e.g. when inserting a new line (works in old version)

**Comment by ivandrofly** [comment]
How did you produce the bug? (by inserting new line while in Main/Listview and compare it with current subtitle)?

**Comment by MaximPro** [comment]
Please also insert this as well, should be more or less easy to do:
https://github.com/SubtitleEdit/subtitleedit/issues/2017

**Comment by diomed** [comment]
Can you please merge #1952 for this release, so this program can be more intuitive?

**Comment by ivandrofly** [comment]
# Bug 
If you try to download portuguese portugal dictionary from (SpellCheck) it will throw exception.

**Comment by niksedk** [comment]
Nice find about the spell check dictionary :)

**Comment by niksedk** [comment]
Compare fix here: https://github.com/SubtitleEdit/subtitleedit/commit/dbb267513086784dd43f9cf03a8af467031c4b34
Portuguese dictionary fix here: https://github.com/SubtitleEdit/subtitleedit/commit/953d07589d4fcc5e83f04e192670f790b6eb5b9c

Hopefully close now...

**Comment by MaximPro** [comment]
Great Stuff Niksedk, you're a hero for the sczene 👍 :)
When you will release a new beta maybe - we help you to check on more errors and stuff in Version 3.5.

I had some guy lately who could not open videos, so I told him to install the codecpack from codecguide.com, maybe you should give a hint or something, if it doesn't work to open a video.

**Comment by niksedk** [comment]
Latest (and probably last) beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip (portable version)

**Comment by diomed** [comment]
please squash and merge these commits for Croatian:
https://github.com/SubtitleEdit/subtitleedit/pull/1993
before new release! @niksedk

**Comment by ivandrofly** [comment]
https://github.com/SubtitleEdit/subtitleedit/pull/1830/commits/6211fe2120825ea35034def687a68263408868e3

**Comment by niksedk** [comment]
Thx for the updates :)
Sorry, don't have too much time...  but another last beta is up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip
Trying to improve #2016

**Comment by niksedk** [comment]
@ivandrofly: It looks like MacSub format is freezing SE... could you take a look (just pick any random text file)

**Comment by ivandrofly** [comment]
Patch I sent regarding to numbering subtitle issues in MacSub: https://github.com/SubtitleEdit/subtitleedit/pull/2023/files



> @ivandrofly: It looks like MacSub format is freezing SE... could you take a look (just pick any random text file)

Sorry, I don't understand how to produce it... should I drag&drop a random .txt file while MacSubs is selected ?

**Comment by niksedk** [comment]
No, "IsMine" is just very very slow when opening an unknown file...

**Comment by ivandrofly** [comment]
> No, "IsMine" is just very very slow when opening an unknown file...

I'll take a look.

Please see https://github.com/SubtitleEdit/subtitleedit/issues/1990#issuecomment-255793610.

**Comment by niksedk** [comment]
OK, not all text files freezes MacSub but some do, like this: http://www.nikse.dk/sub.zip

**Comment by ivandrofly** [comment]
Bug in UnknownSubtitle41.cs ⚠️

**Comment by niksedk** [comment]
3.5 is out finally :)

Was a bit tougher than usual... more bugs (especially in compare) and less time I guess.

**Comment by ivandrofly** [comment]
Ups, I think you forgot https://github.com/SubtitleEdit/subtitleedit/pull/2023/files, line number will be messed up when loading from a MacSub. 😕

**Comment by niksedk** [comment]
Jep, no biggie though. Merged now.
