### ISSUE TITLE
simple feature request

### ISSUE THREAD

**Issue by heforfree** [SubtitleEdit/subtitleedit#1994]
feature request is simple
when set sync point of two subtitle via "point sync via other subtitle..."
the position of last selected sync point in left side (subtitle that we want sync)
after click apply goes to top and its not comfortable and time wasting
another option for this dialog  #1430 

edit error already fixed

**Comment by ivandrofly** [comment]
I think this is already fixed in latest version. SE will not open **"point sync via other subtitle..."** if no subtitle was loaded.

**Comment by heforfree** [comment]
i downloaded Subtitle Edit 3.4.13
https://github.com/SubtitleEdit/subtitleedit/releases

**Comment by ivandrofly** [comment]
Nope, 👉  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip

**Comment by heforfree** [comment]
sorry
you are correct
