### ISSUE TITLE
(Suggestion) CPS and separation in subtitle list

### ISSUE THREAD

**Issue by rebawest** [SubtitleEdit/subtitleedit#2]
Let me suggest to add CPS and Separation (or Blank, Gap, Pause) to the subtitle list.
I attach a capture of Softni subtitler.
I know you can't have 2 lines in a listview, so two more columns would be needed is this is done.

Notice that by having more info in a single cell (in Softni) the subtitle list is narrower, and so there is more space for the video on the right. Also, each subtitle in the list appears in two lines which makes them easier to read.
So maybe a in a future version the list could be improved, maybe using a textbox inside each cell; I can't think of any other way of having line breaks inside a cell.

Thank you very much. Regards...

**Comment by niksedk** [comment]
CPS available in list view in latest beta
