### ISSUE TITLE
MPC-HC interaction isn't working

### ISSUE THREAD

**Issue by frozenspider** [SubtitleEdit/subtitleedit#2010]
![screenshot](https://cloud.githubusercontent.com/assets/2077017/19412873/86a0c15e-9338-11e6-832d-d2515ec0b9ef.png)
As you can see, MPC-HC is greyed out, but I have it installed properly on my system (`K-Lite_Codec_Pack_1090_Standard.exe`), it works without issues.
I'm running Win8.1 x64, both MPC-HC and SubtitleEdit are x64 as well.
Also, I'm curious on how exactly MPC-HC presence is resolved?

**Comment by ivandrofly** [comment]
Where is your MPC-HC installed (full path)?

**Comment by frozenspider** [comment]
`E:\ProgramFiles\K-Lite Codec Pack\MPC-HC64\mpc-hc64.exe`

**Comment by ivandrofly** [comment]
Hmmm... I'll try to add an option to select *mpc-hc64.exe* directory from a custom location.

**Comment by aaaxx** [comment]
Why not just convert that VLC path field to generic path-to-executable for the currently selected video engine?

**Comment by OmrSi** [comment]
@niksedk Closed?

**Comment by stzokev** [comment]
This is still not working after all these years? @ivandrofly I don't see an option to manually point Subtitle Edit to MPC-HC using latest SubtitleEdit 405
