### ISSUE TITLE
[Settings] - Why having four textboxes if we will only need two?

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#2011]
![settings-video](https://cloud.githubusercontent.com/assets/6579818/19417247/cabdeaee-939f-11e6-8165-e9d65a2de5fb.PNG)

![settings-player](https://cloud.githubusercontent.com/assets/6579818/19417256/1ea48a6e-93a0-11e6-9bef-57ad89bb570f.PNG)

**If user wants to use other than 1st and 2nd he can just select from combobox.**

**Comment by niksedk** [comment]
The rest can be used from shortcuts
