### ISSUE TITLE
openSuse 42.1 - GStreamer Erro?

### ISSUE THREAD

**Issue by kholyphoenix1** [SubtitleEdit/subtitleedit#2012]
Hello, 

Once you have installed noticed that when you insert videos in the format: MP4 or MVK closed the application alone.
Open the command terminal and was shown that:

`inux@linux-5vsz:~> subtitleeditor           

(subtitleeditor:24310): GLib-GObject-WARNING **: The property GtkButton:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.

(subtitleeditor:24310): GLib-GObject-WARNING **: The property GtkButton:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.

(subtitleeditor:24310): GLib-GObject-WARNING **: The property GtkImage:stock is deprecated and shouldn't be used anymore. It will be removed in a future version.

** (subtitleeditor:24310): CRITICAL **: bool Config::get_value_bool(const Glib::ustring&, const Glib::ustring&): assertion 'state' failed

(subtitleeditor:24310): GLib-GObject-WARNING **: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.

(subtitleeditor:24310): GLib-GObject-WARNING **: The property GtkSettings:gtk-can-change-accels is deprecated and shouldn't be used anymore. It will be removed in a future version.

(subtitleeditor:24310): GLib-GObject-WARNING **: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.

(subtitleeditor:24310): GLib-GObject-WARNING **: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(subtitleeditor:24310): GLib-GObject-WARNING **: cannot retrieve class for invalid (unclassed) type '<invalid>'

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_object_class_find_property: assertion 'G_IS_OBJECT_CLASS (class)' failed

(subtitleeditor:24310): glibmm-WARNING **: Glib::ConstructParams::ConstructParams(): object class "(null)" has no property named "name"

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_type_class_unref: assertion 'g_class != NULL' failed

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_object_newv: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(subtitleeditor:24310): GStreamer-CRITICAL **: gst_object_ref_sink: assertion 'object != NULL' failed

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_object_set_property: assertion 'G_IS_OBJECT (object)' failed

(subtitleeditor:24310): GStreamer-CRITICAL **: gst_element_message_full: assertion 'GST_IS_ELEMENT (element)' failed

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_object_set_property: assertion 'G_IS_OBJECT (object)' failed

(subtitleeditor:24310): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(subtitleeditor:24310): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(subtitleeditor:24310): GStreamer-CRITICAL **: gst_element_get_bus: assertion 'GST_IS_ELEMENT (element)' failed
segmentation fault
linux@linux-5vsz:~`

**Comment by niksedk** [comment]
Wrong product...

**Comment by kholyphoenix1** [comment]
Sorry...'
