### ISSUE TITLE
ASS to SRT Subtitles multi files

### ISSUE THREAD

**Issue by AhrimanSefid** [SubtitleEdit/subtitleedit#2015]
Hi.
Very good software 
but me need ASS to SRT Subtitles multi files.
and support (Persian-farsi lange) (arabic-utf-8)

http://cloud.githubusercontent.com/assets/1332246/19419315/e5c5eda4-93e1-11e6-95ba-ee72229d3f88.png

![utf](http://cloud.githubusercontent.com/assets/1332246/19419315/e5c5eda4-93e1-11e6-95ba-ee72229d3f88.png)

**Comment by darnn** [comment]
I'm no expert, but, have you tried the "batch convert" function? You can reach it throuth Tools -> Batch convert.
I don't know anything about Farsi, but if your file is in Farsi and SE doesn't automatically open it using the correct encoding, I suggest you try File -> Import subtitle with manual chosen encoding.
