### ISSUE TITLE
Not translation possible Empty lines / Win10 Update the bad guy??

### ISSUE THREAD

**Issue by Shadowviewer** [SubtitleEdit/subtitleedit#2016]
Hello!
I have a problem with my SubtitleEdit-3.4.12 and same with (now)13
I think , since the great win10 update...i don´t now some other reason for it

I have not installing new software or make some other creepy updates ...only windows 10 make some changes with their huge update...... i think

(The Problem is also on FF in my Addon IM Translator...since weeks ,
if i use a other Browser like Chrome all works Perfect!
Only the Microsoft translator in IM works....Google translate side works also.

Now same here on my loved Subtitle Edit installed program

I really do nothing, it comes from alone
i use it every day..all works perfect...since 4 Days i can´t work with subtitle edit
If i use the translator English to German (or something different else)
He leave me most of the lines empty ...only 15% of the full srt file 
maybe 25% are written and translated => rest are empty (sure my internet are good)
If i use the Microsoft translator (Line by line) all works perfectly ...but line by line is not the best alternative ...i really don´t like!

What i have do, to fix the problem (Is not fixed yet)
I update the crazy FF
I update Flash player and some other Adobe stuff = all shines green > up to date!
But nothing help -  it works not like day before

Today i use the Hammer Method ...deinstall Subtitle Edit and install a newer version
It helps nothing a bit

But Thanks God(Developers) i have found your Online Translator ...and first time it works for me and fits!

But pls, can someone help me ,with my crazy PC ?i really need my lil loved program back again! 
my english is not the best ,as you can show here ;) 

Only speech slow i will understand your advice ! 

I can make u a screen shot or upload the file were most of it empty is :(
The Original srt file is also not corrupted or crashed ...the old files from last week(all was working perfect)...he leave now empty lines..so what can i do?

Sorry i writ to much , but i will tell all Informations what can be important.
Greetings SV;)

![empty line full of it](https://cloud.githubusercontent.com/assets/22874470/19421060/4c400e6e-93f8-11e6-8d7f-ebf49ca9a2e5.JPG)

**Comment by niksedk** [comment]
Could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.13/SubtitleEditBeta.zip
