### ISSUE TITLE
File naming got screwed up in 3.5.0

### ISSUE THREAD

**Issue by mzso** [SubtitleEdit/subtitleedit#2036]
If I open a file named:
`Whatever.S06E05.1080p.WEB-DL.DD5.1.H.264-CLZ.mkv`

SE defaults to saving:
`Whatever.S06E05.1080p.WEB-DL.DD5.1.H`

The extension is added automatically, so that works at least. Since the extension does not show up in the text field (but it used to) I guess the bug was added when this change was implemented.

**Comment by niksedk** [comment]
Hm, cannot re-create this... I get prompted for ´Whatever.S06E05.1080p.WEB-DL.DD5.1.H.264-CLZ.srt´.

**Comment by mzso** [comment]
[**@niksedk**](https://github.com/niksedk) commented on [2016. okt. 27. 20:37 CEST](https://github.com/SubtitleEdit/subtitleedit/issues/2036#issuecomment-256731915 "2016-10-27T18:37:39Z - Replied by Github Reply Comments"):
> Hm, cannot re-create this... I get prompted for `Whatever.S06E05.1080p.WEB-DL.DD5.1.H.264-CLZ.srt`.

That's how it worked with 3.4.13. Also it's weaird that you get "Whatever.S06E05.1080p.WEB-DL.DD5.1.H.264-CLZ.srt" with the extension. It doesn't do that at all to me.

**Comment by niksedk** [comment]
What do yo do exactly? And what OS?

**Comment by mzso** [comment]
Windows 8.1. I use the zip version. But I doubt that matters.
You sure you didn't miss something I wrote? Are you opening an .mkv file then try to save the text subtitle that was extracted from it?

**Comment by niksedk** [comment]
Ah... I just opened the video file and created a new subtitle. Will test...

**Comment by mzso** [comment]
Hi!
It's nice that it's fixed. Will there be a .1 release soon?
