### ISSUE TITLE
Replace windows always pops up on the left side of the screen.

### ISSUE THREAD

**Issue by Yomodo** [SubtitleEdit/subtitleedit#2037]
When pressing `CTRL`+`H`, the Replace windows always pops up on the left side of the screen,
even if you drag it somewhere else.

Could it (a) **remember its last position** and (b) **initially open as a centered popup on the main window**.

**Comment by niksedk** [comment]
What version of SE are you using?

**Comment by Yomodo** [comment]
The latest and greatest: 3.5.0, but the previous version also had this.

**Comment by Yomodo** [comment]
Version 3.5.0 also suffers from this, albeit a bit less.
It happens whilst browsing through through the lines in the main window
and making small manual adjustments.

**Comment by Yomodo** [comment]
This is how to replicate this:
1. `CTRL`+`F to find someting.
2. `CTRL`+`H` to replace someting, the window will open up on the left side.

**Comment by Yomodo** [comment]
Cool, thanks a million!
