### ISSUE TITLE
Copy selected subtitles as a pure text

### ISSUE THREAD

**Issue by vsemozhetbyt** [SubtitleEdit/subtitleedit#2038]
Is there a way to do this (for a dialog quoting, for example)? In the list view, the context menu function copies the source instead of the pure text (i.e. it copies with numbers and time codes in SubRip, for example).

**Comment by niksedk** [comment]
There's a shortcut for copying text only from selected lines - tools -> options -> shortcuts -> list view

**Comment by vsemozhetbyt** [comment]
Thank you!
