### ISSUE TITLE
directories Waveforms - Spectograms

### ISSUE THREAD

**Issue by j0boelaert** [SubtitleEdit/subtitleedit#2042]
When opening "Show/hide video" I get error messages concerning directory Waveforms or Spectograms:

---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:
Error Message:
Toegang tot het pad C:\Program Files\Subtitle Edit\Spectrograms is geweigerd.
Stack Trace:
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   bij System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   bij System.IO.Directory.CreateDirectory(String path)
  bij Nikse.SubtitleEdit.Core.WavePeakGenerator.SpectrogramDrawer.GetSpectrogramFolder(String videoFileName)
   bij Nikse.SubtitleEdit.Forms.Main.OpenVideo(String fileName)
   bij Nikse.SubtitleEdit.Forms.Main.TryToFindAndOpenVideoFile(String fileNameNoExtension)
   bij Nikse.SubtitleEdit.Forms.Main.ShowVideoPlayer()
   bij Nikse.SubtitleEdit.Forms.Main.toolStripButtonToggleVideo_Click(Object sender, EventArgs e)
   bij System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bij System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   bij System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bij System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bij System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType et)
   bij System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bij System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bij System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bij System.Windows.Forms.Control.WndProc(Message& m)
   bij System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bij System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bij System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bij System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bij System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Afbreken   Opnieuw   Negeren   
---------------------------

**Comment by niksedk** [comment]
Do you use the installer version or the portable version - and where is it installed (e.g. d:\utils\se) ?

**Comment by niksedk** [comment]
Try not to install the portable version to "C:\Program Files\Subtitle Edit" - if you want that, then use the installer.

**Comment by j0boelaert** [comment]
Indeed, that’s the solution. Thanks.

 

Groetjes

Johan

 

Van: Nikolaj Olsson [mailto:notifications@github.com] 
Verzonden: zaterdag 29 oktober 2016 22:54
Aan: SubtitleEdit/subtitleedit <subtitleedit@noreply.github.com>
CC: j0boelaert <jboelaert@skynet.be>; Author <author@noreply.github.com>
Onderwerp: Re: [SubtitleEdit/subtitleedit] directories Waveforms - Spectograms (#2042)

 

Try not to install the portable version to "C:\Program Files\Subtitle Edit" - if you want that, then use the installer.
