### ISSUE TITLE
V3.5 not able to import template to "multiple place"

### ISSUE THREAD

**Issue by SirEllert** [SubtitleEdit/subtitleedit#2055]
Hi.

Is it made by purpose that, you cannot longer import a saved template to the "Multiple Replace"-function? Or somehow drag-n-drop the template. 

In case you have made a lot of settings for subtitle editing, you have to add them all by hand it seems.
The old version had an "Import" and "Export" function, which made it easy to configure SubtitleEdit on a new PC.

**Comment by ivandrofly** [comment]
You can import templates, 1st you need to add or select a group
from groups located in left top corner
go to list rules, right click and you will see the Import option.
