### ISSUE TITLE
[EffectTypeWriter] - Doesn't go well if text start&ends with HTML tag.

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#2063]
**Input:**
\<i>meu primo já havia crescido
e se tornado o Superman.\</i>

**In some stage will become:**
\<i>meu primo já havia crescido
\</i>

*Note: This bug was present in **EffectKaraoke** was fixed in:* https://github.com/SubtitleEdit/subtitleedit/pull/1643

**Comment by OmrSi** [comment]
@ivandrofly @niksedk I think this has been fixed at some point.
