### ISSUE TITLE
Whatever I set the horrid windows media player stays the actual player.

### ISSUE THREAD

**Issue by mzso** [SubtitleEdit/subtitleedit#2065]
I tried setting VLC, selected folder. Then had the SE dowload the mpv lib and setting that.
Still the same...
(also it auto pauses, when I jump to a subtitle which is annoying)

**Comment by ivandrofly** [comment]
SE doesn't use WMP, you can see which player is current in use (image below):
![github_image](https://cloud.githubusercontent.com/assets/6579818/20033643/5c67271e-a39d-11e6-8083-f40b9cbec366.PNG)

**Comment by darnn** [comment]
And as for the other thing, settings -> general -> "double clicking line in main window list view will".

**Comment by mzso** [comment]
Thanks guys! The WMP like GUI is a tad confusing.
