### ISSUE TITLE
SE gets flagged by a virus scan

### ISSUE THREAD

**Issue by Bitsky** [SubtitleEdit/subtitleedit#2067]
Portable and Installer get both positive results on virustotal:
https://virustotal.com/en/file/8ddd401acc9b3132186cfc07cd5f785f638e842211053267b977642cbbd4305d/analysis/1478289079/
https://virustotal.com/en/file/04940062a910eec82e87ad0dc7cfeffb0361b9879617d858749116c99868b90b/analysis/1478369951/

**Comment by niksedk** [comment]
SE uses an exe packer which annoys some anti-virus programs... feel free to submit the problem to "CAT-QuickHeal".
