### ISSUE TITLE
Text in textbox automatically selected on switching to a different window

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2068]
I'm using Windows 7, and Subtitle Edit 3.5.0.
To reproduce this, open Subtitle Edit, and then:
1. Create a new subtitle file.
2. Insert a new subtitle (i.e. the first one), via the keyboard shortcut "List view -> Insert after", and type something in it.
3. Insert a second subtitle using the same keyboard shortcut as in step 2 and type something in it.
4. Switch to a different window using alt+tab and then switch back to Subtitle Edit. The text in the textbox will now be selected, as though you had pressed ctrl+a.

This does not occur if you add the individual subtitle by clicking "insert after" in list view , for whatever reason.

Demonstration:
![sub ed](https://cloud.githubusercontent.com/assets/19672444/20038076/dd939fdc-a435-11e6-8af2-0caaa51aabd5.gif)

**Comment by niksedk** [comment]
Hm, does not happen here...

**Comment by darnn** [comment]
Weird, it happens on at least two computers for me... I tried out a couple of things now, and what I can add is that to reproduce it, you must alt+tab to a window that covers up the portion of the screen that Subtitle Edit takes up completely, or, to be on the safe side, to a window that has been maximized.

If you still can't reproduce it that way, the only thing I can think of is to see what the differences are between inserting a subtitle using the keyboard shortcut and inserting a subtitle using the right-click menu in list view, since the text doesn't get selected if you do it the second way.
