### ISSUE TITLE
The position of the selected line in list view is not saved properly.

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2069]
Once again, I'm using Windows 7 and Subtitle Edit. 3.5.0.

The problem is this: When editing e.g. srt files, when a certain line is selected in list view, if you use search to switch to a different line, or go up and down in the list view using keyboard shortcuts while the textbox is focused, the position of the selected line is not stored properly, and the next time you focus list view and try to move up or down in it, the selection will move as though you had not performed the search/moved while the focus was on the textbox.

To reproduce with search:
1. Open a subtitle file containing several subtitles (I'd say at least 15 if you want to observe the effect clearly).
2. In list view, select the first subtitle. If you are doing this using the keyboard, once you have selected it, press the keyboard shortcut to switch to the source view (i.e. ctrl+page down, among others), and then press it again to switch back to list view. This saves the true location of the selected subtitle properly, for some reason.
3. Open the find window, either through edit->find or through the keyboard shortcut. Type a word found in, e.g., the sixth subtitle, and press enter. The sixth subtitle is now selected in list view, and the focus has switched to the textbox.
4. Press the keyboard shortcut for "toggle focus between list view and subtitle text box" (ctrl+down by default). The focus has shifted to the list view. Note that while the sixth subtitle is ostensibly selected, you can still see the "proper" selection of the first subtitle, in the dotted line surrounding it.
5. Press down. Note that instead of the seventh subtitle being selected, the second subtitle is selected, as though you were moving from the first subtitle (which we selected properly in the beginning) to the second.

Demonstration:
![sub ed - search line selection](https://cloud.githubusercontent.com/assets/19672444/20038365/0e257d14-a43b-11e6-8611-78e4ca3300da.gif)

To reproduce with "go to next line"/"go to previous line" keyboard shortcuts (steps 1-2 are as above):
1. Open a subtitle file containing several subtitles.
2. In list view, select the first subtitle.
3. Press the keyboard shortcut for "toggle focus between list view and subtitle text box". The focus is now on the textbox.
4. Press the keyboard shortcut for "go to next line" five times. The sixth subtitle is now selected in list view.
5. Press the keyboard shortcut for "toggle focus between list view and subtitle text box". The focus is back to list view. As before, note that while the sixth subtitle is ostensibly selected, you can still see the "proper" selection of the first subtitle, as it is outlined with a dotted line.
6. Press down. As before, the second subtitle is now selected, rather than the seventh.

Demonstration:
![sub ed - go to next line selection](https://cloud.githubusercontent.com/assets/19672444/20038459/11b19808-a43d-11e6-883c-1de67fd591c6.gif)

**Comment by niksedk** [comment]
Yes, can replicate that (nice gifs by the way:)
Could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.0/SubtitleEditBeta.zip (portable version, just unzip to e.g. d:\tools\se)

**Comment by darnn** [comment]
Gifs simplify everything. :)
And, more importantly, it works!! Thank you!
