### ISSUE TITLE
Remeber last language selected

### ISSUE THREAD

**Issue by rhazor** [SubtitleEdit/subtitleedit#2087]
CTRL+Shift+F always set to 'cs' language for no reason each time you open that window and I have to switch it to my own language all the time (e.g. lt). It should remember my last set language.

Also should be nice if search with keyboard in language list worked with all letters, not only just first letter. If I press 'L' key it selects first language code in the list that starts with L and it's La, but if I need Lt and I press L+T, it jumps to Ta language code. I don't know why it's set to that, should work just like default browsing with keyboard through folders in Windows Explorer.

**Comment by niksedk** [comment]
SE has some language auto detection... but not Latvian (is that your language?) which is probably the main issue.

I've tried to add Latvian auto-detect via this code:
https://github.com/SubtitleEdit/subtitleedit/commit/c4b509c5fd9864348db50eefba141c7ed7999bef

Can be tested via this portable beta:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.0/SubtitleEditBeta.zip

Better?

**Comment by rhazor** [comment]
Lt is Lithuanian. And all LT subs gets detected as CS for some reason. That beta still detects Lt as Cs in ctrl+shift+f window

**Comment by niksedk** [comment]
OK, Lithuanian also added :)
https://github.com/SubtitleEdit/subtitleedit/commit/e7b5e6e66f1081fd181a1fd495c57e90238eb432

Beta updated:  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.0/SubtitleEditBeta.zip

Could you give it a test run?

**Comment by rhazor** [comment]
I'm not sure what I'm supposed to do. I open LT .srt sub (any, you can try yourself, just snatch any lt sub from google) and launch the ctrl+shift+r and selected language is always [cs]

**Comment by ivandrofly** [comment]
> ctrl+shift+r

Don't you mean CTRL+SHIFT+F?

**Comment by rhazor** [comment]
ye ctrl+shift+f

**Comment by niksedk** [comment]
New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.0/SubtitleEditBeta.zip
Based on this commit: https://github.com/SubtitleEdit/subtitleedit/commit/a0fc3f74db2e1c757157d9ed3f228693f053a533

The Czech auto detect was a bit aggressive. I snatched 4-5 Lithuanian subs from Google and it seems to work... but you probably have a few more Lithuanian subs - and probably understand the keys words from above commit. How does it look now?

**Comment by rhazor** [comment]
ye it works now

**Comment by niksedk** [comment]
thx for verifying :)
