### ISSUE TITLE
Word-List/Rules to Start/End Subtitles to fix youtube auto captions

### ISSUE THREAD

**Issue by MaximPro** [SubtitleEdit/subtitleedit#2094]
Hello,

Thanks alot for your great work here! I really love it!

I just got a 10h+ Video Translation Projekt right now and I found a great shortcut for me, that is really useful. I upload the Videos to Youtube first and get the automated captions with timings and recognition from yt. This is a good start, because you just need to fix most things, but don't need to time everything manually. However it doesn't subtitle it by meaningful sentences, but just by words. This needs to be fixed or it means a huge workload to split and recombine lines a few thousand times, only to make sense...

So a great solution would be a intelligent Word-List/Rules to Start/End Subtitles to fix youtube auto captions. This Word list will be created by the users or anyone who wants it and it will grow even more by the time. Basically it should be a second word-list menu, but for correcting the meaning.

**It would be important to be able to create rules like:**

If Word = "and" , "so that" , "or" , "but"> start a new line with this word
If Word = "I don't" , "I would" , "I'm" , "I" "ok" > start a new line with this word
If Word = "isn't new" , "open source design" > split line after this word

**Rules needed so far:**
• Start a new line using these words
• Split after word
• merge line with these words
• always combine these words if near (open source, not open
source, next line going on)
• typical questions, place a symbol (?) after those. ("can you do that" would be a question to put in the list)

(please add more suggestions for rules @users)

It should be just like the common error thing. A way to fix voice recognition text, especially youtube automatic captions. Wich are a amazing and great boost at start.

This is also very important for translations and for better readabillity. We read in logical parts.

Could you please add this very soon?
This would be sooo amazing, especially for people who do long video translations!

I would be really satisfied! And I would donate a good portion for sure! Others as well I believe.

I believe you can do that pretty.
Thanks for all what you do here anyway! You are great! :)
Best regards
Maxim

ps: You should also add a donate button by the way. (as a menu point, maybe just like the programmer "z_o_o_m" did it with his multi file uploader)

**Comment by niksedk** [comment]
I think SE already has this to some degree... check Options -> Settings -> Tools -> Misc: Use "do-not-break-after" list
