### ISSUE TITLE
Change all / Use always selection in spell checking is not saved

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2095]
I'm still having issues with the Change all / Use always options in spell checking. The current subtitle is affected but the word pair is not saved anywhere so the same correction is not applied automatically to future spell checks or OCRs.

If I use the Add pair to OCR replace list in the Import/OCR phase, the word pair is added to the word list.

The Add to names/noise list and Add to user dictionary are working fine in both OCR and spell checking phase.

**Comment by OmrSi** [comment]
@niksedk Wasn't this included in a commit recently?

**Comment by Boulder08** [comment]
@OmrSi @niksedk Part of it is in, the Change all -selection during spell check is not remembered for future spell checks as far as I know.

**Comment by niksedk** [comment]
It's now an option in latest beta - see Options -> Settings -> Spell check

**Comment by niksedk** [comment]
Hm, not sure if it actually works in OCR spell check... will check.

**Comment by Boulder08** [comment]
Did you find anything? I just did some spell checking, and using Change all when you spell check and correct something manually, does not put the word pair to the list.

**Comment by hifrench** [comment]
hi there,
still there is problem ! :(
i set the settings to remember too but if i open another .srt file and start checking spell , i see some words that i corrected before and now must be correct them auto , still are the same ! (version : 3.6 SE)
![SRT Remeer](https://user-images.githubusercontent.com/18724952/154060453-967865f7-c669-49e8-ad18-9cb3af96558b.png)
ty :)
