### ISSUE TITLE
A small adjustment to Fix missing spaces in the Finnish version

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2096]
Finnish sentences often have postpositions like this: "FBI:n". Subtitle Edit thinks that this is an error and offers to correct it to "FBI: n".

**Comment by niksedk** [comment]
Can it also be :en or :et or is it always :n ? (Gotta fix Swedish too)

**Comment by Boulder08** [comment]
I'm afraid there's a lot of them. I found out this webpage with a rather comprehensive list:

http://www.tuomas.salste.net/doc/roman/sijamuodot.html

The tables cover numerals but the same combinations are often used for abbreviations as well.
