### ISSUE TITLE
Removing Hard-of-hearing adds extra dashes if there's a line break

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2098]
```
Original:
478
00:37:44,679 --> 00:37:48,266
KIRK:
<i>Captain's log, stardate 1514. 1:</i>

After removing HoH:
478
00:37:44,679 --> 00:37:48,266
- <i>- Captain's log, stardate 1514. -</i>

If there's no line break after "KIRK:", the removal works fine:
478
00:37:44,679 --> 00:37:48,266
<i>Captain's log, stardate 1514. 1:</i>

```

**Comment by niksedk** [comment]
If you don't compile from source code then you can test latest beta here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.0/SubtitleEditBeta.zip

**Comment by Boulder08** [comment]
Thank you, will test this one as I'll be working on those Star Trek TOS subtitles :)

**Comment by niksedk** [comment]
Cool, let me know how it works!
TOS is a bit old for my taste though, but I do love Star Trek :)

**Comment by Boulder08** [comment]
That reported one works now (and the end of the stardate was also snipped but not anymore, I missed that initially).

I've got one more which I noticed going through that episode:
```
269
00:20:05,038 --> 00:20:08,291
BALOK [OVER RADIO]:
<i>--and trespassed into our star systems.</i>

turns to
269
00:20:05,038 --> 00:20:08,291
<i>and trespassed into our star systems.</i>
```
