### ISSUE TITLE
A couple more things about Find

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2100]
Hey, so, I see that the find functionality has indeed been altered, but I feel like there are two problems that still remain that pertain to the same issue: 
1. Say you're typing in the textbox and you type "aa ab ac ad". If you then hit the shortcut key for Find, and type "ad" into the text line, the first result found would still be "ad" from the text you had just typed. Presumably because once the Find dialogue pops up, the textbox loses focus, and SE treats the currently highlighted subtitle as the "next" occurrence.
2. If you're creating subtitles from scratch, like I am, the subtitle you're currently typing out usually isn't followed by any other subtitles. However, even when this is the situation, every time you perform a search, SE will pop up this dialog:
![continue find](https://cloud.githubusercontent.com/assets/19672444/20465451/078eb0f2-af66-11e6-9fff-d63cd5da4fd5.png)
In order for this new fix to be truly effective, I think there should be the option to disable this dialogue from appearing (i.e. automatically "loop" the search to the beginning of the file if no instances of the search term are found in the remainder of the document after the currently highlighted subtitle). At the very least I think SE should do a check when a search is performed to see if the currently highlighted subtitle is the last one, and if so to go back to the beginning of the document automatically.

**Comment by ivandrofly** [comment]
"Find" has some very serious "bug" (found while I was working on this patch https://github.com/SubtitleEdit/subtitleedit/pull/2060)

/cc @niksedk
