### ISSUE TITLE
Standard Win10 user missing words lists and dictionaries

### ISSUE THREAD

**Issue by insurw** [SubtitleEdit/subtitleedit#2102]
When the installation finishes 34 XML, 2 OCR and 2 dictionary files gets added to the admin's folder automatically. When I launch it as the logged in standard user (the admin was installing because the UAC prompt) the Dictionaries folder is completely empty and the OCR folder doesn't exist. Dictionaries can be downloaded but not words list. You can enable names_etc.xml from online but that leaves out "user word list" and "OCR fix list". 
So I'm forced to copy the Subtitle Edit folder from the admin's folder to get a properly configured program

I guess most home user on Windows use an admin account, but when I upgraded my PCs to Win10 I saw no reason to keep doing that and am now using standard accounts.

**Comment by niksedk** [comment]
Are you installing the portable version into "Program files"?
Either install the portable version to e.g. d:\tools\se or use the installer if you want to install to "Program files".

**Comment by insurw** [comment]
I'm using the installer and install to Program files. As you get the UAC it's installed for the admin instead for the logged in standard user that initiated the installation.

**Comment by niksedk** [comment]
Where is the "admin" folder the 34 XML, 2 OCR and 2 dictionary files resides in?

I did not make the installer and don't know much about it...

**Comment by insurw** [comment]
...\AppData\Roaming\Subtitle Edit
