### ISSUE TITLE
[ENHANCEMENT] "Play through subtitles only"

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#2103]
Could you add the option to play the video through subtitled ranges only (including about one second before and after), skipping everything in between. Other than that, it should work the same as the normal Play does, starting at the current position in the video.

Hopefully, this will make professional-level quality control easy, allowing you to watch the entire video together with the subs in only about half of its duration time or less.

**Comment by aaaxx** [comment]
Any chance someone finds some time to implement this in the near future?

**Comment by OmrSi** [comment]
Good idea.
When I wanna review a subtsubtitlei have to press on each line to view it.
The way you're suggesting would be easier. :)

**Comment by niksedk** [comment]
Play selected lines - F5
