### ISSUE TITLE
[ENHANCEMENT] Rule to "Remove ellipses linking continued subtitles"

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#2104]
It used to be common practice in professional subtitling to use ellipses (three dots) to indicate that a subtitle continues into the next one. Usually, they would put an ellipsis at the end of the first one and the beginning of the second one. Thankfully, nobody seems to do this anymore, but there's still plenty of existing subs using that convention.

It would be useful to have a new rule in Fix Common Errors (separate from Remove leading '...'), that would remove ellipses in pairs of such subs – that is, remove the trailing one if the next sub starts with the leading one, and remove the leading one if the previous sub ends with the trailing one.

When implementing, make sure you include both the three dots *and* the ellipsis character ("…", U+2026 HORIZONTAL ELLIPSIS). Also, BBC's subtitles use two leading dots instead of three for the continued subtitle.

I'm aware that this could also affect valid cases if the subtitler used a leading ellipsis after the previous sub ended with a pause, but when I'm just trying to watch a film, I only need a quick fix, and missing a few pause-indicating ellipses is a lot less annoying than having every other pair of subs sprinkled with them.

**Comment by javierdoor** [comment]
I'm also interested in this. Is it possible to implement this?

**Comment by OmrSi** [comment]
@niksedk This is implemented with the new continuous lines style, right?
