### ISSUE TITLE
[New features] Adjust start and end times one frame at a time

### ISSUE THREAD

**Issue by rebawest** [SubtitleEdit/subtitleedit#2122]
Please add the following functions and shortcuts for them; default shortcuts could be left blank of course.

- **Start time + 1 frame:** Increase current start time with a frame.
- **Start time - 1 frame:** Decrease current start time with a frame.
- **End time + 1 frame:** Increase current end time with a frame.
- **End time - 1 frame:** Decrease current end time with a frame.

These four functions would move the start or end time one frame at a time, until they reach the previous or next subtitle (there shouldn't be overlapping and they would consider the minimum gap).
They would work until the minimum duration is reached.

Additionally, there could be four more functions:
- **Start time + 1 frame and pull previous:** Increase current start time with a frame and previous subtitle end time as well.
- **Start time - 1 frame and push previous:** Decrease current start time with a frame and previous subtitle end time as well.
- **End time + 1 frame and push next:** Increase current end time with a frame and next subtitle start time as well.
- **End time - 1 frame and pull next:** Decrease current end time with a frame and next subtitle start time as well.

These four functions would move the start or end time one frame at a time until they reach the previous or next subtitle (considering the minimum gap); when that happens, they would keep moving the start or end and, at the same time, they would move the end of the previous subtitle or the start of the next.
They would work until the minimum duration is reached, either for the current subtitle or for the previous/next subtitle.

My own shortcuts would be: Add, Subtract, Shift+Add, Shift+Subtract, Ctrl+Add, Ctrl+Subtract, Ctrl+Shift+Add, Ctrl+Shift+Subtract. But again, they could be blank by default.

Please let me know if anything is not clear or if you need a video sample of these functions working in professional software.

Thank you. Regards.

**Comment by niksedk** [comment]
Included in latest beta
