### ISSUE TITLE
Error in italics

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2126]
![image](https://cloud.githubusercontent.com/assets/11799308/20858091/f99e42a8-b944-11e6-892d-e03693f531f7.png)

The OCR'd line is:
`The <i>Horizon's</i> contact came`

**Comment by niksedk** [comment]
You can change the last "s" to be recognized as italic... 
SE do not allow part of a word to be italic, so it works as intended - what seems wrong to you?

**Comment by Boulder08** [comment]
OK, I didn't know that the word could not be split to italic and non-italic. The compare matches are correct, the "s" is not italic in the graphical subtitle.
