### ISSUE TITLE
Issue with names list and fix uppercase 'i'

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2127]
The names that I have added to the names list are being autocorrected by the Fix uppercase 'i' inside lowercase word option.

For example, I have words Iotia, Iotian and Iotians in the names list but the autocorrection wants to turn them to lotia, lotian and lotians respectively.

**Comment by niksedk** [comment]
It works fine here...

**Comment by Boulder08** [comment]
I tried it with a freshly built version and just added those three words and tried the functionality. It doesn't try to fix them. I then tried the same with the version I've been working with and it tries to fix them.

I copied all the xml files from the version I've used to OCR things to the dictionaries folder of the fresh version and now it also wants to fix them :)

Could it be that this OCR replacement would actually cause the thing?
`<Word from="Iot" to="lot" />`

**Comment by niksedk** [comment]
I guess it could be the OCR replacement list... could you link to it or email it to me?

**Comment by Boulder08** [comment]
Here are the dictionary files related to English subs:

[Dictionaries.zip](https://github.com/SubtitleEdit/subtitleedit/files/629375/Dictionaries.zip)

**Comment by niksedk** [comment]
Thx for the files... still could not replicate the bug. 
Can I use some of the words from your replace list by the way?

**Comment by Boulder08** [comment]
I can link to the whole program folder if you like, it might be that there's some setting affecting this.

Feel free to use the words as needed :)
