### ISSUE TITLE
Issue with removal of H-O-H subtitles

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2128]
```
227
00:13:46,493 --> 00:13:48,578
- M-5, tie in.
M-5: <i>M-5.</i>
```
is turned to

```
227
00:13:46,493 --> 00:13:48,578
- M-5, tie in.
```

**Comment by Boulder08** [comment]
Also this one fails a bit:

```
674
00:40:02,233 --> 00:40:05,153
M-5: <i>Daystrom acknowledged.</i>
- M-5...
```
```

674
00:40:02,233 --> 00:40:05,153
<i>- Daystrom acknowledged.</i>
```

**Comment by niksedk** [comment]
Strange... I don't have none of the issues as I get:

`- M-5, tie in.
<i>- M-5.</i>`

and

`<i>- Daystrom acknowledged.</i>
- M-5...`

**Comment by Boulder08** [comment]
I got it now: it's the "Remove line if UPPERCASE" option which causes the removal. Apparently the dash and the number is not being considered.
