### ISSUE TITLE
Get dictionaries "German" don´t work

### ISSUE THREAD

**Issue by Massaguana** [SubtitleEdit/subtitleedit#2129]
Is it not possible to download German disctionary...

**Comment by Massaguana** [comment]
Cool, and now? What must i do to use this fix? Wait for an Update?

**Comment by niksedk** [comment]
I'll upload a beta in a few minutes...

**Comment by niksedk** [comment]
Could you verify that latest beta works:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.0/SubtitleEditBeta.zip
(it's the portable version - just unpack to something like C:\Tools\SE)

**Comment by Massaguana** [comment]
It works fine... Thanks for your extrem fast fix...

**Comment by niksedk** [comment]
You're welcome - and thx for reporting it :)
Also about 15 other dictionary links were broken (all libre office links)

**Comment by Massaguana** [comment]
Your Mac Version are still in development? because i am Mac user… in moment i use your Software with an VM

**Comment by niksedk** [comment]
SE 3.5.1 out now: https://github.com/SubtitleEdit/subtitleedit/releases
