### ISSUE TITLE
No Video Playback

### ISSUE THREAD

**Issue by Massaguana** [SubtitleEdit/subtitleedit#2131]
With Subtitle Edit 3.5 and your beta from Yesterday is it not possible to Play the Video file... just black...

Is this Normal?
![bildschirmfoto 2016-12-04 um 09 51 52](https://cloud.githubusercontent.com/assets/15521791/20865058/5f1ca7a6-ba07-11e6-8953-ee3ea153c4cc.jpg)

Regards
Massaguana

**Comment by Massaguana** [comment]
A short answer would have been nice...

**Comment by niksedk** [comment]
Yeah, sorry about that. I've gotten this question a lot... also on Github. Try reading here: http://www.nikse.dk/SubtitleEdit/Help
My current recommendation is "mpv" video player is it's very fast and it's just one dll file - you can get it from Options -> Settings -> Video player -> click the "..." button right of mpv and then click "Download".

**Comment by Massaguana** [comment]
Thanks, now it works... I had read the FAQ but did not understand it. Even after your instructions I could not read this out there...
