### ISSUE TITLE
Layout of translator mode in RTL mode is confusing

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2132]
Hi. My issue is this. When RTL mode and translator mode are combined, in list view, the original text is on the left and the translation ("text") is on the right. However, the subtitle text box for the original text is on the right, and the text box for the translation is on the left.

**Comment by niksedk** [comment]
I've tried to switch the textboxes here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

Does it work okay?

**Comment by darnn** [comment]
Not quite, I'm afraid. The positions of the "text" and "original text" columns are now properly aligned with the "text" and "original text" textboxes, so that's good.
But two things have gone wrong:
in RTL mode, only the "original text" column is now aligned to the right, "text" is aligned once again to the left , which sort of defeats the purpose.
And, if SE starts with an original file, a translation file and a video loaded, if you then create a new file to clear everything, and then reopen the translation file (which also opens the original file and the video), the textboxes shrink.
You can see both of these here:
![se 2017 03 05](https://cloud.githubusercontent.com/assets/19672444/23586780/7c13dc40-01a5-11e7-89b4-c30abb5d3dcf.gif)

You can also see how the alignment isn't how it should be when SE opens and loads the two files for the first time, but that's a different bug that I hadn't submitted a report about yet.

**Comment by niksedk** [comment]
thx for testing :)
New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
Any better?

**Comment by darnn** [comment]
The alignment in the columns is now correct, but the textboxes still get smaller whenever a translation is open, you create a new file, and then reopen the translation.
Also, since I'm translating from English into Hebrew, what I'd like to be able to do is determine both the alignment and the reading order of a given column. So, for instance, I'd have the "text" column (which is Hebrew) be aligned RTL and the text direction would also be RTL. The "original text" column would have a LTR text direction, because it's English, but would be aligned RTL, so that the text would be closer to the other column and I wouldn't have to look farther away. Is it okay to open a feature request for that? I ask because I know I've submitted a bunch of bug reports and feature requests recently and I don't want to overwhelm you.

**Comment by niksedk** [comment]
Beta updated again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

If the text is English it should be left-aligned - in both list view and text box or only text box?

Yeah, sorry I don't have time to fix everything... I also get about 5-10 emails per day regarding SE + I've also got another project + (normal?) life ;)

**Comment by darnn** [comment]
Now it works. Yeah, if you don't want to make it too complicated, English should be left-aligned - in the text box you don't need to change anything, it's already behaving properly there (i.e. you can change alignment with left-ctrl+left-shift/right-ctrl+right-shift). It should be left-aligned in list view. But this is also why I think it should be togglable - if I were translating from Hebrew into English, it would be the inverse, I would need "text" in list view aligned left and "original text" aligned right.

And yeah, I totally understand! It's amazing to me that you fix as much as you do, I'm really grateful. I'd donate again but you've disabled donations!

**Comment by niksedk** [comment]
Yet another test version - I've tried to add some auto-detect of language/alignment: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

How does it work?

**Comment by darnn** [comment]
Mixed results. Starting in RTL mode looks like this:
![se alignment test](https://cloud.githubusercontent.com/assets/19672444/23591268/373f303c-01f6-11e7-998d-a8d5aafbd9c6.png)
So, which it's technically meant to be in RTL mode, it actually isn't. If you then create a new file and then turn RTL mode off and on again, it will now go into real RTL mode. Once this is achieved, if I open the translation again, I get this:
![se alignment test2](https://cloud.githubusercontent.com/assets/19672444/23591278/6547d1d2-01f6-11e7-9e62-63022e798903.png)
So, the Hebrew's okay, but the English, while aligned left, is still in RTL reading order, rather than in LTR.

**Comment by niksedk** [comment]
Hm, the list view does not support setting RTL mode for a single column :(
So, a basic version here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip (only text box is affected in "translator mode")

Seems okay?

**Comment by darnn** [comment]
Wait, so, what should I be looking for now? The current build pretty much looks like build 8 (i.e. two builds ago) to me. And hey, I guess if it doesn't support it, it doesn't support it. There's only so much you can do.
