### ISSUE TITLE
Question: Online Subtitle Edit 

### ISSUE THREAD

**Issue by flixajki** [SubtitleEdit/subtitleedit#2135]
Is there source files for online subtitle editor. 
I have quite big library hosted on Amazon Drive & Plex Media Server, and I would like to host editor that would load my database and give me option to fix subtitles ( mostly offset )

**Comment by niksedk** [comment]
Sorry, no source files for the online editor. Also, I don't think that the windows version can open a video from a stream...

**Comment by flixajki** [comment]
Hopefully at one point the online version will be released as well :)
