### ISSUE TITLE
Release 3.5 .1

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#2137]
Time for a new release as many spellcheck dictionaries cannot be downloaded.

TODO:
- [x] Test download of all dictionaries
- [x] General testing + (fixing bugs)

If you know any issue that should be included then do let us know :)

**Comment by Elheym** [comment]
@niksedk It seems that the "Auto-backup" (after delete) is not working correctly. "1 month" is displayed as "6 month". 6 as 3... 3 as 1... It's really confusing.

**Comment by niksedk** [comment]
@Elheym: thx, nice catch :)
Fixed in b245c3ced1017e93cdf977834197f99e0b992365

**Comment by diomed** [comment]
what's so wrong with this that you don't wanna merge it @niksedk :

https://github.com/SubtitleEdit/subtitleedit/pull/1952
I think it provides more intuitive way of using SE.

**Comment by rebawest** [comment]
Hello. When "Auto duration" is used, the subtitle might overlap with the following.
As you can see in the screenshot, subtitle #3 overlaps with #4. Is this a bug?
Also, my "Max. reading speed" is set at 20; however, with "Auto duration", the subtitle extends, in my example, until the reading speed is "14.47 cps". Shouldn't it extend until the "Max. reading speed" is reached.

![image](https://cloud.githubusercontent.com/assets/6587015/21080228/d44a8d50-bf88-11e6-9790-11faccb43013.png)

Let me know if I should open a new task. ;-)

Thanks. Regards.

**Comment by darnn** [comment]
Oh, I'd appreciate it if you take a look at this for the new release: https://github.com/SubtitleEdit/subtitleedit/issues/2099
Right now I have to have two instances of SE running, 3.5.0 for ELR conversion and the latest beta.

**Comment by niksedk** [comment]
@diomed: #1952 annoys me as it insert a blank subtitle at a wrong time code... I think it's easier to just insert a subtitle at the correct time code - also a lot of stuff needs to be tested.

@rebawest: thx :) Overlap issue should be fixed in 252259cfd689f4540f6a64e1b121060b30cbb05f 

@darnn: Fixed in commit 866ed4d12558105a9cd482cb480aa1b453f6d8a9

**Comment by niksedk** [comment]
Latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.0/SubtitleEditBeta.zip

**Comment by rebawest** [comment]
> @rebawest: thx :) Overlap issue should be fixed in 252259c
Thanks, niksedk. OK, there's no more overlapping. However, the speed is reduced to 15 cps, no matter what the "Max. reading speed" is. Is this on purpose?

**Comment by niksedk** [comment]
@rebawest: Yes, that is on purpose... you can only edit this value directly in Settings.xml (it's called "SubtitleOptimalCharactersPerSeconds").

**Comment by rebawest** [comment]
OK, can we add this to the parameters Window in a future release? Like 4.0.
Some professional software use one number and percentages: for example, 17 cps +/- 10%, that is, 17 is the optimal and 17+10% is the maximum.
Having 2 numbers would be fine, such as "Max. 20", "Optimal 17".
Thanks!

**Comment by diomed** [comment]
sorry to annoy, but is there any way to fix this issue:

https://github.com/SubtitleEdit/subtitleedit/issues/2084

@niksedk @ivandrofly

**Comment by darnn** [comment]
Thanks for pointing out the existence of "SubtitleOptimalCharactersPerSeconds", I'd been looking for something like that but couldn't find it in the settings!

**Comment by niksedk** [comment]
@diomed: #2084 is not super easy to fix - and it takes less than ½ a second on my computer...

**Comment by niksedk** [comment]
SE 3.5.1 out now :)
Commit 87e3ba26051eb4a350026b85ced47df51395a364
