### ISSUE TITLE
Failed to download french dictionnary

### ISSUE THREAD

**Issue by itamma** [SubtitleEdit/subtitleedit#2138]
Hi, 

I just try to download the french dictionnary in Subtitle Edit 3.5 but the download failed (error 404). 

Thanks ! 

itamma

**Comment by niksedk** [comment]
Sorry, Libra Office has changed the download location - will be fixed in SE 3.5.1: https://github.com/SubtitleEdit/subtitleedit/issues/2137

**Comment by niksedk** [comment]
Fixed in SE 3.5.1
https://github.com/SubtitleEdit/subtitleedit/releases
