### ISSUE TITLE
SE 3.5.0 build 121 - subtitle filename taken from video file even if it already has a distinct name

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2139]
1. Open SE, create a new subtitle file (so there is a clean playing field, as it were). There should be no subtitles and no video open.
2. Modify the new file so that it may be saved.
3. Save the file via file->save as (or the appropriate keyboard shortcut).
4. Modify the subtitle file again.
5. Save it again via "save as". Note that the filename will be the same as the one you gave it in step 3.
6. Drag and drop a video file into the video preview pane. It must be in a different folder from the subtitle file you've created, and have a different name.
7. Modify the subtitle file again.
8. Attempt to save the file via "save as". Unlike in step 5, SE will now attempt to save the file in the folder of the video file that was just loaded, and its name will be the name of the video file, even though the original subtitle file has a different name and is in a different folder.

This behavior will persist. For instance, say you saved the subtitle file in c:\a\1.srt. Once you open the video, e.g. c:\b\2.mp4, and attempt to save the subtitle file via "save as", SE will offer to save it in c:\b and call it 2.srt. If you then navigate to c:\a and save the file as 1.srt again, and then modify the file and attempt to "save as" once more, SE will still offer to save it in c:\b as 2.srt.

**Comment by niksedk** [comment]
Hm, this behavior has been requested...

**Comment by darnn** [comment]
I mean, I think it's fine if you don't already have a filename that you chose yourself. But once you do, "save as" should prefer that over the video filename. This way everyone gets what they want - if someone wants to get the filename from the video, they just load the video first and then save the file. If someone wants to name their file ahead of time, they get to retain the filename regardless of which video file is loaded.
