### ISSUE TITLE
Visual sync doesn't work with some subtitles and other questions

### ISSUE THREAD

**Issue by Ormendahl** [SubtitleEdit/subtitleedit#2140]
Hi, first of all, thanks a lot for this awesome progam.
-I don't know if this is normal but there's some subtitles that don't get synced right when i use the visual sync option, most of the time it syncs just perfect but there's some subtitles that doesn't.
-I have a doubt, when a movie starts and/or ends with text on screen instead of a voice what should i select in the visual sync inicial and final points? Should i select the first subtitle when a voice is heard or the first subtitle translation of the first text on the screen?
For example, the movie/subtitle starts with this text on the screen"based on a true story"(no voice), then only after like 30 seconds you hear the first voice, so in the visual sync what i select as initial point, the "based on a true story" part or the voice heard 30 second after that?

-Is there a way to delay/advance a specific section of a subtitle?For example, i wanna delay the subtitles 3 seconds from the 30 minutes mark to 40 minutes mark and advance 2 seconds from the 60 minutes mark to 70 minutes mark(just an example), is this possible? I ask this because some times after i use visual sync the subtitle isn't synced in some portions of the video, so this would make things faster. Instead of having to go and sync each subtitle of that portion(let's say a 10 minute portion of the video where you want the subtitle to come 3 seconds faster), if you could just advance that whole portion 3 seconds it would help a lot.

**Comment by niksedk** [comment]
Visual Sync is only for simple speed adjustment - does not need to be the absolutely first and last scene that you sync.

I normally just use the waveform and the "set start and offset the rest" (check the waveform shortcuts - works well if scenes has been added and/or removed). If it's a really difficult sync job, then you might need to use "Visual sync" on selected lines (right click on selected lines in the list view and choose "Visual sync selected lines"). 
Once you're used to the waveform it should be pretty quick to sync much stuff... I hope.

**Comment by Ormendahl** [comment]
Thanks for the answer. Is there a way to select like 50 lines instead of having to Ctrl+C each of those 50 lines, i only see the option to select all lines.

**Comment by aaaxx** [comment]
Select the first one, then Shift+click the last one.

**Comment by Ormendahl** [comment]
^ Thanks a lot man, never would have have found that.

**Comment by Ormendahl** [comment]
How do i change the default language/audio track when using the visual sync option? For example, i have this video where audio track 1 is english language plus russian Voice over and audio track 2 is only english(but it doesn't say the languages when i go switch between the 2 in a video player, it only says audio track 1 and 2).When i go to visual sync it looks like it auto-selects audio track 1 with the russian dub voice over and that really difficults things up, so is there like a shortcut or option to change audio track? I can't find it anywhere.

**Comment by niksedk** [comment]
If you use "mpv" or "VLC" you have an menu item to change audio-track in the main window under the "Video" menu.

**Comment by Ormendahl** [comment]
I have VLC but i actually prefer Potplayer but when i use subtitle edit i think it is using Windows media player, so how do i change it to VLC or even Pot player?

**Comment by niksedk** [comment]
Try Options -> Settings -> Video player... I recommend "mpv".
Yeah, gfx looks somewhat like an old wmp. 
Pot player does not have an API.

**Comment by Ormendahl** [comment]
I don't get it why i can't change to VLC under video engine, it doesn't let me select it.

**Comment by darnn** [comment]
If you don't want to install it (but don't mind downloading it), you could try this: http://www.nikse.dk/SubtitleEdit/Help#portable

**Comment by Ormendahl** [comment]
Thank you @darnn

**Comment by niksedk** [comment]
SE default uses the DirectShow engine... required codecs on your machine like LAV filters: https://github.com/Nevcairiel/LAVFilters/releases (new version out yesterday)

**Comment by OmrSi** [comment]
@niksedk This is closed?
