### ISSUE TITLE
Chinese translation could be better

### ISSUE THREAD

**Issue by tinyboxvk** [SubtitleEdit/subtitleedit#2141]
![image](https://cloud.githubusercontent.com/assets/13696594/21030978/83b0c566-bd77-11e6-97b2-ec5bcf3da499.png)
The translation for "Remove text for hearing impaired..."
should be
"删除为听觉障碍描述的文本..."
instead of
"删除妨碍听觉的文本..."

**Comment by tinyboxvk** [comment]
This has been bugging me for quite some time now. Just thought I might contribute.

**Comment by LeonCheung** [comment]
Thanks for the feedback. It will be fixed with the language pack I'm about to contribute later today.

**Comment by niksedk** [comment]
Fix in commit a0b39527579ed74ef452d680510f3252b6dbd72c

**Comment by niksedk** [comment]
SE 3.5.1 out now: https://github.com/SubtitleEdit/subtitleedit/releases

**Comment by tinyboxvk** [comment]
![image](https://cloud.githubusercontent.com/assets/13696594/21139688/7a0c86e4-c10a-11e6-9f91-defba96f0892.png)
![image](https://cloud.githubusercontent.com/assets/13696594/21139702/8c1ab4a0-c10a-11e6-8295-2fd494b6ca34.png)
![image](https://cloud.githubusercontent.com/assets/13696594/21139723/9d9e6d98-c10a-11e6-9488-181e18398bb7.png)
![image](https://cloud.githubusercontent.com/assets/13696594/21139737/af466cb2-c10a-11e6-81bd-133a02f645a3.png)
The first three translations haven't been fixed.

**Comment by LeonCheung** [comment]
You are right... It seems to be partially fixed by last commit, will do asap. Thanks for the feedback again.

**Comment by tinyboxvk** [comment]
@LeonCheung It seems that you forgot to fix this in 3.5.2.

**Comment by LeonCheung** [comment]
Fixed #2270 . Thx tinyboxvk, feel free to point out any faults in it if you find anything in future.
