### ISSUE TITLE
Liking the program, getting better, but I'm bad at this stuff and need a little help

### ISSUE THREAD

**Issue by dannyhaase** [SubtitleEdit/subtitleedit#2142]
Hi, please bear with me, I'm new and not good at this stuff and trying to learn. I'm trying visual sync. What I'm looking for is a way to play to the video while arranging the times of the subtitles so that you can see first hand whether or not the subtitles are in sync. 

What I'm doing now in visual sync is on the left video. when I hear a voice I find that subtitle and click it, then press the 1/2 second back once or twice. I feel like all I'm really doing is guessing if it's right. 

Like I don't see in visual sync how I am changing the times of the subtitles. All I see is that the video skips back 3 seconds, 1/2 seconds, or whatever you clicked, but not how to control the subtitles. That doesn't seem to be changing the time the subtitles appear.

I hope this makes sense. I watched the video and I just don't have a clue what's happening.

So, cliffs: I want to watch the video in SubtitleEdit where I can notice exactly where all subtitles for that show will be. Can I do that, and if so, how? 

ty

**Comment by dannyhaase** [comment]
I believe what I'm looking for is probably pretty easy, no? 

It seems here: http://i.imgur.com/bQYMfcn.png

or here: http://imgur.com/a/mk4so

There I can observe the video, but what I've tried to click on the left doesn't appear to be changing all the times of the subtitles? 

any buttons that will just change the time of all the subtitles? Like select all somehow? My attempts aren't working but I imagine they're there.

**Comment by dannyhaase** [comment]
basically, is there like a way to select all of these at once, and then adjust the time of all? http://i.imgur.com/xKIAAm3.png

I've tried all I can find and you only change the time on the top one, not all. hope it's a reasonable question, I'm just lost in all of this.

**Comment by dannyhaase** [comment]
everything below is super basic level, I suppose. 

hmmm I guess maybe I tried enough times and I figured it out. :)

So basically using the same options in the about imgur, I just press the start video button on the bottom. The subtitles started too late so I clicked the first subtitle on the top and chose an earlier "start time." I hit the rewind button on the bottom a few times and tested it until it was correct. Then I chose "Set start time," then I saved, and everything is golden. :)

Sorry if everything I've said seems stupid. This is just not something I've tried before but I'm getting better. :) Product is amazing you all, love it. 

all good?

**Comment by dannyhaase** [comment]
so I can change the first subtitle to be on time, but I don't know what to press to change the rest to match that time. This has gotta be easy, can someone just please help me?

**Comment by niksedk** [comment]
"Visual sync" is for simple sync where only speed/start is different. Also check the help file: http://www.nikse.dk/SubtitleEdit/Help#visual_sync

For more advanced sync try the waveform: http://www.nikse.dk/SubtitleEdit/Help#waveform
I think that you're looking for "Set start of offset the rest" (it does change the first selected subtitle AND THE REST ALSO, the shortcut in waveform is: left mouse click+Ctrl+Shift). It's what I use...

**Comment by dannyhaase** [comment]
cool, thanks a lot. yeah i asked everyone i could and some information I found is to right click on the first subtitle once you know the time amount it needs to be moved, then press "show selected lines earlier and later" then enter the amount of time it needs to moved, have it on "all lines" and then press "show earlier."  I'll try your way too and see what works best for me. thanks! 


did learn that to right click on the first subtitle, then select

**Comment by dannyhaase** [comment]
does "set start time and off-set the rest" only work in visual sync?

Here is exactly where my subtitles start: http://i.imgur.com/nWwKDfF.png

but that's too late, so I moved back the opening line several seconds back. you can see in this gif the first one is now in the correct time, but once I press "set start time and off-set the rest" for whatever reason the time of the first one, which was right, as well as the following subtitle lines go several seconds forward, the opposite direction. what do i do before I click "set start time and offset the rest"? http://imgur.com/ps63qi2

**Comment by niksedk** [comment]
Try using the waveform....
"Set set and offset the rest" uses the current video time as start time for first selected sub.

**Comment by dannyhaase** [comment]
thanks, but it;s still changing how all the times of the subtitles move for unknown reasons. To explain what I do exactly: 

I inserted the movie and the subtitle (these are the subtitles that start several seconds too late).  I clicked "show waveform." When waveform opened I clicked "select current subtitle while playing" which allowed the subtitles to show in the top video playback.

I moved the first subtitle back to the proper time, so now the first one is in sync.

Then I clicked "set start and off-set the rest." 

If you watch the times on the gif, you see the first one starts in sync at 2.275, and the second is starting out of sync at 10. But after I press "set start and off-set the rest" the first one, which was in sync, is moved to 3.7 out of sync, and the following are moved further ahead of time about 2 seconds. 

http://i.imgur.com/q6Ihrff.gif

What am I missing?

**Comment by dannyhaase** [comment]
I'll insert the subtitle file first, but then after I insert the video it tells me "No subtitles found," even though they obviously should be found. Any chance that's related? 

I also considered maybe when you click "set start and off-set the rest" you need to have the video in a very particular spot, right where you do what the subtitles to start, and you can't just have the first subtitle selected on the top? I feel like there might be something obvious others who are better at this than I would know. Are there any obvious changes I need to make?

**Comment by niksedk** [comment]
Are you drag'n'dropping the video? If yes, the drop it on the video player... if you drop it on the list view, then SE will search the video for embedded subtitles.

**Comment by dannyhaase** [comment]
Sweet! That does it! Sorry I'm so confused about all this (and persistent, apparently, didn't even realize that in my curiosity I posted so much in this thread myself, lol :)), but thanks for solving what was stressing me! :)
