### ISSUE TITLE
Issues parsing irregular SRT files

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2147]
Hey. Using SE 3.5.1. Two things that are kinda related:
1. Attempting to open this SRT file: https://dl.dropboxusercontent.com/u/645489/test-se-1.srt
SE gives the error: "Line 10 - epxected subtitle number: all the stuff"
So, it's trying to parse part of the second subtitle as the number of the third subtitle. Granted, there aren't many subtitles with a line of text, two blank lines and then another line of text, but evidently they exist.
2. Attempting to open this SRT file: https://dl.dropboxusercontent.com/u/645489/test-se-2.srt
SE gives the error: "Line 6 - error reading time code: 2"
It looks like the subtitle consisting of a blank line and then a line with only a number in it confuses it. Again, not a typical case, but it is an actual subtitle that I got (of a bet in a poker game).

Edit: attaching zip with both files: 
[test-se.zip](https://github.com/SubtitleEdit/subtitleedit/files/2668851/test-se.zip)

**Comment by niksedk** [comment]
Minor improvements to SRT parsing: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Works over here!
