### ISSUE TITLE
Feature: Extent Short Subtitle Range to max duration

### ISSUE THREAD

**Issue by MaximPro** [SubtitleEdit/subtitleedit#2149]
Hey,

I have subtitles and some really short parts that are only 1 second, but there is place for another second around them (0,5 before and after)

But there are many many lines.
Could you add an option to fix that or add that to common errors or something.

Feature:
Extent Short Subtitle Range to max duration,  (max X seconds - for empty lines parts) - 
extend before and after, or if it is maxed out, go where the place is.

Maybe this is feature is also somewhat there, but maybe not to that extend.
Would be amazing for the next release!!!
Looking forward for this great feature. 

Thanks Nik
Best regards.

**Comment by MaximPro** [comment]
Well here is an example as well - part of a bigger subtitle project - I can't get the small timings right, exept manualy. I would like to get those things fixed, by the fix common problem feature from subtitle edit, because there is space avaiable as you see on the videos (2 short videos attached/link)
Could you please fix that as well?

We all would like to have readable subtitles and nothing is more frustrating for a viewer, then too short subtitles timings, when you have to rewind, play again and stop the video to see what it was, because a text is snapped away in 1 sec, where it normally would take 2-3 seconds to read.

It should harmonize those that are too short and even let its timings move into the max neighbors timings - so it has the place it needs.

Here are the explanation videos to that topic here: http://xup.in/dl,26511790
also here is the german srt file to mess with: http://xup.in/dl,39290204
so you see exactly what I mean.

Thanks for your hard work and time!
You're wonderful!
Best regards
Maxim

**Comment by MaximPro** [comment]
Hi Nik, did you check on this lately? 
I see you do alot for us for the next update, but could you give me at least your professional opinion on that?
Would be great to see this thread get awnsered by you :)

ps: Please review this other topic regarding youtube subtitles as well if you can.. thx :+1:

**Comment by niksedk** [comment]
I've updated the "Apply duration limits", so it also "improves" duration when it's not possible to achieve the "mininum duration", so it at least improves.
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip

Fix common errors - fix short durations, will try several ways to improve duration (if enabled in Options -> Settings -> Tools - FCE fix short dur - allow move of start time.

You want the option to allow move of start time in "Apply duration limits" too?

**Comment by mario-dedalus** [comment]
@MaximPro sorry for contacting you on that very old issue, but I still do not understand on how to extent a subtitle to its max. duration? I really would love to have the option (or even better the option incl. a shortcut) to extend a subtitle to its max. CPS (character per second). As this issue/request is set to Completed, I guess it is possible, but I simply don't know how to do that. Could you help me?
