### ISSUE TITLE
Feature: Interpret Youtube Subtitles with colors/marking

### ISSUE THREAD

**Issue by MaximPro** [SubtitleEdit/subtitleedit#2150]
Hey again,

This would also be amazing, because googles voice recognition is now really advanced by now.
This makes auto subtitling alot easier. However it's still not perfect, but very good, especially in english!

If it doesn't recognise text so well, it marks it as grey,

Check this here (see the subtitles)
https://www.youtube.com/watch?v=M92WLMq8ll0

So if you download a subtitle and look at the structure of those autosubtitles, you see format like this above.

Could you interpret it and maybe "jump" from one to next, to have a quick error correction done by the user.

This would be amazing!
Please check on that.

Looking forward.
Merry Xmas and a happy new year!
All the best!
Maxim

**Comment by MaximPro** [comment]
Hey Nik, did you checked this?
It is really a revolution and makes things much easier! 
Please support this.

**Comment by MaximPro** [comment]
Well I just looked into it, this video above doesn't seem to have this formating - here is a better example
https://www.youtube.com/watch?v=Jhb1yM54hPE

Now I attached this formatted .srt as well (all colored - the machine is not sure)

**Comment by MaximPro** [comment]
For some reason it doesn't support is 8kb zip file, so I uploaded it to an external hoster:
http://xup.in/dl,13920293

**Comment by MaximPro** [comment]
Thanks Nikolaj for the minimum duration fix, It didn't fix everything yet, however it was some improvement. for a complete fix I would like to see the neighbors to be more reduced so that there is a minimum display time of 1,5-2 sec for the subtitle that is really short and has a lenght above 3-5 words.

Also please review this youtube thing. It would be one of the best improvements, when we can use machine transcribing for the most things incl. timings and later to correct things our selfes quickly.
A feature, incl. hotkey that would let us skip to the next "grey - unsure/not machine understood word" so we can quickly fix those things that the machine didn't understand with it's 90%+ accuracy.

You're doing great!

Best regards
Maxim

**Comment by MaximPro** [comment]
How is it going here? Did you check?

**Comment by MaximPro** [comment]
I mean this whole automation solution would be a big leap forward, aren't you interested in this, Nik?

**Comment by gabriellluz** [comment]
For auto subtitling using youtube engine, use
https://github.com/agermanidis/autosub

It works flawlessly. It basically grabs your video file, encode it to WAV and then gives you a SRT Subtitle file. AUTOMATICALLY.
