### ISSUE TITLE
3.5.0 -> 3.5.1 Multiple replace rules don't import/copy

### ISSUE THREAD

**Issue by tlhintoq** [SubtitleEdit/subtitleedit#2157]
I have several steps in Multiple Replace in 3.5.0 that don't automatically import to 3.5.1.  Are the settings someplace different?  Heck where *do* they live?

**Comment by OmrSi** [comment]
@niksedk This is too old, is there a need for it anymore? And, yes, I'm looking at old issues just to help a little with what I can. 😅

**Comment by tlhintoq** [comment]
Well... That depends.  Is it rectified?  Does the current version migrate all the steps of a multiple replace situation?

**Comment by OmrSi** [comment]
I have many multi replace rules and I've had no problem moving from version to another since 3.5.4.

**Comment by tlhintoq** [comment]
> since 3.5.4
Good to know.  Then I guess its a resolved issue that can be closed.

**Comment by OmrSi** [comment]
I've been using the program since 3.4.5 and a set of multi replace rules with it, no problem happened when moving to newer versions.
I just tested to make sure, the rules move to the new version with no issue.

You can close this.
