### ISSUE TITLE
Issue with importing "Unknown 53 (.txt)" format

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2160]
Hi. SE 3.5.1. When I attempt to open a txt file structured thus:
00:15:07:00 Here is my offer:
00:15:16:00  I set Chelyadintsev free tonight
00:15:20:00 and you come here tomorrow morning
SE recognizes it as "Unknown 53 (.txt)" and opens it. However, since it is expecting the format of tt:tt:tt:tt, space, text, and in the second line in the sample above there are two spaces after the timecode, it does not import this line or pop up an error about this.

**Comment by ivandrofly** [comment]
I tried nothing happened... try uploading the sub file that is producing this error.

**Comment by darnn** [comment]
Weird, when I trim it to just those three lines, it recognizes it as a different format. Here's the full file: https://dl.dropboxusercontent.com/u/645489/PARADISE2.txt
