### ISSUE TITLE
Doesn't select the audio track i choose

### ISSUE THREAD

**Issue by Ormendahl** [SubtitleEdit/subtitleedit#2166]
This was working before but now when i go to video-->choose audio track and change it to 2 it doesn't selected it, it keeps audio track 1 which in this case has russian voices dubbed over.

**Comment by niksedk** [comment]
Hm, it depends of the video player - are you using "mpv" or "vlc"?

**Comment by Ormendahl** [comment]
I think it had to with a particular video file, it's working now. Im using VLC with subtitleEdit but my default player is pot player.

**Comment by niksedk** [comment]
I think this is fixed in latest version of SE - vlc can use non zero based subtitle track numbers which SE now supports.
