### ISSUE TITLE
Batch shift times

### ISSUE THREAD

**Issue by shogunreaper** [SubtitleEdit/subtitleedit#2167]
Can you add in shift time that lets you choose start/end times only? (like aegisub)

right now it just moves both the start and end times at once.

also putting it in the batch convert too.

**Comment by niksedk** [comment]
Could you explain some more? Perhaps a screenshot?

**Comment by shogunreaper** [comment]
a screenshot of what?

**Comment by darnn** [comment]
This is a screenshot of the Aegisub shift times window, so presumably something like this:
![shifttimes](https://cloud.githubusercontent.com/assets/19672444/21779546/d9941cd8-d6b0-11e6-8100-3986a1da9cfb.png)

**Comment by darnn** [comment]
![shifttimes](https://cloud.githubusercontent.com/assets/19672444/21779644/33e816bc-d6b1-11e6-825f-08517c65171d.gif)

**Comment by shogunreaper** [comment]
http://docs.aegisub.org/manual/Shift_Times

**Comment by niksedk** [comment]
thx for explaining :)
