### ISSUE TITLE
Structured titles formatting changes

### ISSUE THREAD

**Issue by Yamato-ua** [SubtitleEdit/subtitleedit#2168]
First of all thank you for this awesome peace of software!

Just one minor problem I'm having. There're some changes to formatting of a Structured titles (txt) file when it's saved by SE 3.5.1.

Here's the original:
```
0622 : 00:44:37:00,00:44:38:20,11
80 80 80
C1N03 What? You don't have the right keys?

0623 : 00:44:38:22,00:44:41:04,10
80 80 80
C1N03 -Shut up!
C1N03 -Is this even your car?
```

And here's the saved one:
```
0622 : 00:44:37:00,00:44:38:20,10
80 80 80
C1Y00 What? You don't have the right keys?

0623 : 00:44:38:22,00:44:41:04,10
80 80 80
C1Y00 -Shut up!
C1Y00 -Is this even your car?
```

Every C1N03 is changed to C1Y00, which has something to do with subtitle position.
And note those 10 and 11 at the end of the end timecode. 10 indicating 2 lines, 11 - 1 line.
SE changes all of them to 10. 

Is there an option for this somewhere?
Can you please fix it so that those things are left as they are?

Thanks.

**Comment by niksedk** [comment]
You can test it by compiling from latest source or use latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip (portable version)
