### ISSUE TITLE
Tweak to Remove unneeded spaces

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2169]
`233
00:17:07,727 --> 00:17:10,997
"Let's see if we can write <i>Pac-Man. "</i>

That was a bit tough.
`

The space after "Pac-Man." is not removed by the autocorrection.

**Comment by ivandrofly** [comment]
I tried it worked fine. :/

**Comment by Boulder08** [comment]
These are my settings, maybe that helps to debug this one.

![sedit](https://cloud.githubusercontent.com/assets/11799308/21692448/a330f3c4-d385-11e6-9cf7-e70449c9d7ca.png)

**Comment by ivandrofly** [comment]
Still working.. what version of SE are you using?

**Comment by Boulder08** [comment]
It's 3.5.1 build 1. I also tried deleting everything else and handling just that line but it still doesn't correct it.

[billions_pacman.zip](https://github.com/SubtitleEdit/subtitleedit/files/688077/billions_pacman.zip)

**Comment by aaaxx** [comment]
It seems that it doesn't work when it's in an italic span.

**Comment by OmrSi** [comment]
@niksedk I think this is also closed, it's working with all cases.
