### ISSUE TITLE
What's the best/fastest way to deal with subtitles when the video you have doesn´t have some scenes

### ISSUE THREAD

**Issue by Ormendahl** [SubtitleEdit/subtitleedit#2172]
Or has them but doesn´t have the subtitles of those portions. For example, i only any have a subtitle for a dvdrip but i don´t have a dvdrip and instead i only have a hdtvrip, and in the hdtvrip there´s some scenes missing and my dvdrip subtitle has translated talks/lines from those missing hdtvrip scenes.
Is there a easier way to spot in which chunk of the video this happens(missing scenes from subtitle or vice-versa) or do i have to go throughout each talk to see find it for myself? I mean, that usually takes a lot of time, it's almost as making a whole new subtitle even though i have one, and just to do doing something that seems easy. Missing scenes/talks or subtitles it's always pain to spot.

**Comment by niksedk** [comment]
I normally use the waveform to detect missing/added scenes - normally easy to spot and very quickly to fix (use "set start of offset the rest"). Will take 5 minutes though...

I think "Kerensky" once wrote a tool to help with this, but I never tried it.

**Comment by niksedk** [comment]
Also, c4aff5c087c4d7faf5b202c8f6973bddba8cae14 should make the mouse wheel forward scroll much better (it jumps a back sometimes atm)
