### ISSUE TITLE
Fix common errors always crashes

### ISSUE THREAD

**Issue by obclown** [SubtitleEdit/subtitleedit#2175]
![subtitle edit-error_08012017](https://cloud.githubusercontent.com/assets/24999204/21757345/4fdb9ef6-d5ea-11e6-9211-f1d23ebed3bf.jpg)

I can't find any log files so I did a screen capture, hope that's ok. I get this error every time I try to use fix common errors on a standard .srt UTF-8 file opening the file using the explorer option open with. I f I open the same file with the portable version (also version 3.5.1) ; it works fine. I'm using Win7 Ultimate Sp 1 64bit.

**Comment by niksedk** [comment]
It looks like of of your name dictionaries is invalid... e.g. "Dictionaries\names_etc.xml" - try to do a full uninstall and the re-install again (if you're using the installer the "Dictionary" folder is something like "c:\Users\<USERNAME>\AppData\Roaming\Subtitle Edit\Dictionaries").

**Comment by obclown** [comment]
Yup, that was the problem. Found a user dictionary that had only 0's, replaced with the one from the portable version and works fine now. Thanks!

**Comment by niksedk** [comment]
I'm glad it's working now :)
