### ISSUE TITLE
Problem converting Simplified Chinese PAC to SRT

### ISSUE THREAD

**Issue by craigmffc** [SubtitleEdit/subtitleedit#2176]
Hi.

I tried converting a Simplified Chinese PAC file to SRT but the Chinese characters in the resultant SRT file don't appear to be valid characters.

I ran the conversion using a command line with the following command:

SubtitleEdit.exe /convert C:\sub1.pac srt /encoding:gb2312

I also tried using utf-8 encoding but both had the same outcome. 

An example of the issue was the translation of the following character string (from the PAC file):
故事再次发生了

In the SRT file this became the following:
嘟岈婬棒楷汜賸

Am i doing something wrong in the command line? I'm using the latest SubtitleEdit (3.5.1)

**Comment by niksedk** [comment]
Have you tried "/pac-codepage:CHS" (simplified) or "/pac-codepage:CHT" (traditional Chinese)?

**Comment by craigmffc** [comment]
Thanks. That works perfectly.
