### ISSUE TITLE
Structured titles (found the problem)

### ISSUE THREAD

**Issue by Yamato-ua** [SubtitleEdit/subtitleedit#2177]
Thanks for fixing that previous issue so fast. You are truly awesome!

Not that big of an issue, but I've found some more inconsistencies with SE 3.5.1 (beta included) when working with Structured titles format. 

SE adds one empty subtitle at the beginning and one at the end:
```
Structured titles
0001 : 00:00:14:23,00:00:17:00,10
80 80 80
C1N03 <Record temperatures>
C1N03 <in the New York area> 
```
```
Structured titles
0000 : --:--:--:--,--:--:--:--,10
80 80 80

0001 : 00:00:14:23,00:00:17:00,10
80 80 80
C1N03 <Record temperatures>
C1N03 <in the New York area>
```
```
0627 : 00:46:44:18,00:46:45:14,11
80 80 80
C1N03 Bang.
```
```
0626 : 00:46:44:18,00:46:45:14,11
80 80 80
C1N03 Bang.

0627 : --:--:--:--,--:--:--:--,-1
80 80 80
```

And strangely enough one particular subtitle in different episodes is always attached to the previous one:
```
0028 : 00:03:47:00,00:03:49:21,10
80 80 80
C1N03 Stand back, everybody.
C1N03 Okay, please, please.

0029 : 00:04:14:15,00:04:16:07,1
80 80 80
C1N03 A NETFLIX ORIGINAL SERIES 
```
```
0028 : 00:03:47:00,00:03:49:21,10
80 80 80
C1N03 Stand back, everybody.
C1N03 Okay, please, please.
C1N03 0029 : 00:04:14:15,00:04:16:07,1
C1Y00 A NETFLIX ORIGINAL SERIES
```
Now that could be because of 1 instead of 10 in the end, so that might be error in the file itself. 

Thanks!

PS. Please let me know if there's a way I can donate or support the project in other ways.

**Comment by Yamato-ua** [comment]
It's been two years, but I've figured out what those digits in Structured titles mean =)

Additionally to line number the 10, 11 and 1 in the end indicate vertical subtitle position:
10 - bottom two-line subtitle
11 - bottom one-line subtitle
1 - top subtitle regardless of line count
Which makes sense, since it's a position of the first line of a subtitle if you divide the screen into 11 lines and count from the top.

`0016 : 00:00:48:13,00:00:51:21,10
80 80 81
C1N03 <We love to ride all day outside>
C1N03 <We like the indoors, too>

0017 : 00:00:51:23,00:00:53:16,11
80 80 81
C1N03 <We don't always agree on stuff>

0021 : 00:00:59:00,00:01:02:01,1
80 80 81
C1N03 <Though we may be different>
C1N03 <Lucky, Pru, and Abigail>

0022 : 00:01:02:03,00:01:03:19,1
80 80 81
C1N03 <One thing we all agree is>
`

Currently SE treats 1 as an incomplete formatting and sticks the next subtitle to the current one thus messing up the structure and the overall number of subtitles in a file.

Hope that helps.

**Comment by niksedk** [comment]
Cool you figured out the 1-11 numbers :)

The SE handling of `Structured titles` in SE is based on a sample file back from 2011. It has empty start tag + empty end tag but I guess they could be "empty lines".

Could you send or attach a few sample files?

**Comment by Yamato-ua** [comment]
Sent some to nikse.dk@gmail.com

**Comment by niksedk** [comment]
thx for the files :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
