### ISSUE TITLE
EBU-STL with balise color for subtitles are deleted after export in EBU-STL 

### ISSUE THREAD

**Issue by jjtronics** [SubtitleEdit/subtitleedit#2178]
Hello,
I found a small bug in version 3.5.1.
If I open an EBU-STL subtitle containing subtitle coloration tags and I export this subtitle in EBU-STL format, the subtitle coloration tags are deleted.
For more details, see the video : https://youtu.be/8LpzbLDWQls

Thank you for your work !!

**Comment by niksedk** [comment]
Are you using "Display standard code" = teletext ?
(open subtitling does not support colors)
