### ISSUE TITLE
Jitter when moving to next line

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2179]
Hi. SE 3.5.1 build 9 (though this is not a recent thing).
When the video and the waveform are hidden and the subtitle list occupies the entire screen, if the first subtitle is selected and then alt+down is pressed to move to the next subtitle, everything functions properly. If one continutes pressing alt+down to move further down the list, at a certain point SE will "center" the selection, i.e. the selected subtitle will jump to the middle of the list. Following this point, whenver alt+down is pressed, there will be a slight jitter when the selection is moved to the next subtitle and the list is centered again:

(all screenshots are best viewed in a separate tab)

![se-jitter2](https://cloud.githubusercontent.com/assets/19672444/21825143/32094e62-d78b-11e6-99bd-90ff7705d4e7.gif)

And here are the individual frames that demonstrate the jitter during the initial centering and then in moving to the next subtitle after it:
![tmp-15](https://cloud.githubusercontent.com/assets/19672444/21825219/7fea4974-d78b-11e6-8004-8211c6fc33ec.gif)
![tmp-16](https://cloud.githubusercontent.com/assets/19672444/21825227/85213fb0-d78b-11e6-9c69-75c257bf3d24.gif)
![tmp-17](https://cloud.githubusercontent.com/assets/19672444/21825229/8789928e-d78b-11e6-9811-1acb325e6445.gif)
![tmp-18](https://cloud.githubusercontent.com/assets/19672444/21825231/89c9963e-d78b-11e6-9551-3e6de511c172.gif)
![tmp-19](https://cloud.githubusercontent.com/assets/19672444/21825233/8bbc261e-d78b-11e6-9b68-7c3d0216a604.gif)
![tmp-20](https://cloud.githubusercontent.com/assets/19672444/21825236/8dd225ac-d78b-11e6-9053-fecf2c9891f4.gif)

**Comment by niksedk** [comment]
Is this any better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?
