### ISSUE TITLE
Missing keyboard shortcuts and menu items

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2181]
Hey, so, this is something that I always wanted to address but never had the time to sit down and compile an organized list of, and I still don't, so I thought I'd just throw it out there:
There are several menu items for which there are no keyboard shortcuts (open/close video, for instance), and conversely there are several functions for which there are keyboard shortcuts but no menu items (merge with previous/next, all the stuff in the menu that appears when you right-click subtitles in list view).

**Comment by niksedk** [comment]
It's kinda supposed to be this way... if you're missing the possibility to customize a specific shortcut do let me know.

**Comment by darnn** [comment]
I'm sorry, I've been swamped with work and haven't gotten around to it... Should I just submit a new issue once I make a list of all the shortcuts I'd like added?

**Comment by niksedk** [comment]
Yes, that would be nice - in prioritized order if possible :)
