### ISSUE TITLE
Currently selected subtitle changes position in list view

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2182]
Hey. SE 3.5.1 build 28, though this has been going on for some time as well. This is in RTL mode.
After working on a subtitle file for a while, the contents of the currently selected subtitle in list view will eventually shift a bit to the left, and stay that way. This is when the focus is on the text box. So, focus on text box, line is shifted. Focus on list view, line looks normal:
![sub ed - rtl line shift 1](https://cloud.githubusercontent.com/assets/19672444/21990577/0a84d6f4-dc18-11e6-925c-68f660e95bbc.gif)
Once this happens it's basically impossible to get rid of it, I can only restart SE, and even then it comes back after a while.
The easiest way I found to reproduce it is: hide the video, create a new subtitle file (withough making changes to it), close SE, open it again, and then create new subtitles in the new file until you reach the bottom of the screen. Once you get there this shift occurs:
![sub ed - rtl line shift](https://cloud.githubusercontent.com/assets/19672444/21990694/6f32ee7e-dc18-11e6-8204-ea98b4f1d11b.gif)

**Comment by niksedk** [comment]
Sorry, don't know how to fix it... it's about list view custom drawing of sub items - see https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Controls/SubtitleListView.cs#L312

**Comment by darnn** [comment]
I don't know the first thing about reading code, sadly... If there's no way to fix the way it currently works, is there maybe a way to just get list view it to display the same thing it displays when I focus on it (except with the lighter blue color)?

**Comment by niksedk** [comment]
OK, I've tried to remove the blue-unselected-color here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip
Better?

**Comment by darnn** [comment]
Yes! Thank you so much!

**Comment by darnn** [comment]
This actually solves this issue as well!
https://github.com/SubtitleEdit/subtitleedit/issues/2070
