### ISSUE TITLE
Feature request: Chars/sec and FPS

### ISSUE THREAD

**Issue by Yamato-ua** [SubtitleEdit/subtitleedit#2186]
Hello.

The more I work with SE the more I love it!
Having worked for some time I'm noticing some things that would make certain parts of the process easier.

For example, it would be awesome in Setting - General to be able to set Max. chars/sec excluding whitespaces. Something like "include spaces" checkbox next to it. (To think of it, second checkbox - "include punctuation" - would be even cooler)

Another thing to think about is separate framerate setting for subtitles display in build-in videoplayer. So that the video fps wouldn't affect subtitle speed (in cases of frame-based timecodes) and won't lead to about 3 sec of desync by minute 40.

Let's say I have 24 fps subs and 23.976 fps video, and I need it to work in sync without changing the actual framerate in the file through Synchronization. Because changing it back isn't as easy and usually I have to import the timecodes from a back-up original. Again, something like "subtitle display fps" drop-down menu in General.

**Comment by niksedk** [comment]
Fixed (I think)
