### ISSUE TITLE
Subtitles position in dfxp

### ISSUE THREAD

**Issue by Plazik** [SubtitleEdit/subtitleedit#2190]
Hello,

Is it possible to add subtitle possition in .dfxp (Netflix)? I'd like to save these subtitles positions (top, bottom) after saving to .ass.

Example:
bottom http://imgbox.com/e4KjibDa
top http://imgbox.com/gymdEO24

Subtitles 
https://mega.nz/#!gEsVQbzS!fYJHIiPiUApCwtkJHFEu2Vo1UcdCu1MXLeeHJIIoKZE

**Comment by niksedk** [comment]
Hi Plazik, could you test this beta (portable version): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEdit-3.5.1-Setup.zip

Fix is in this commit: https://github.com/SubtitleEdit/subtitleedit/commit/bb73e645cfc25bc973f94eeead1ac7bc1ccd8f47

**Comment by Plazik** [comment]
niksedk, thank you for fast fix!

But I can't test in, the last beta commit https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip is https://github.com/SubtitleEdit/subtitleedit/commit/1623ed2 which was before bb73e64.

Should I wait a little more for beta update?

**Comment by niksedk** [comment]
It should also be in the beta... I just compiled before commit (sorry, I should have done it in the correct order).

**Comment by Plazik** [comment]
Yes, I works, thank you!

**Comment by niksedk** [comment]
thx for verifying :)
