### ISSUE TITLE
EBU-STL no color balise after export 

### ISSUE THREAD

**Issue by Craynaud** [SubtitleEdit/subtitleedit#2197]
Hello,
I have an issue when I open an EBU-STL subtitle containing subtitle coloration tags.
If I export this subtitle in EBU-STL format, the subtitle coloration tags are deleted ! 
Does anyone encountered that problem on 3.5.1 version ?

Thanks for your answer !

**Comment by niksedk** [comment]
Are you using "Display standard code" = teletext ?
(open subtitling does not support colors)
