### ISSUE TITLE
Italics in Timed Text 1.0 xml format

### ISSUE THREAD

**Issue by nathaniel1977** [SubtitleEdit/subtitleedit#2199]
Hi, I found a problem with italics in the format stated in the topic.
It seems that whenever you put italics on a double-line subtitle, e.g

<i>He was the happiest man
and knew it wouldn't change.</i>

... after saving the file and opening it again, the subtitle looks like this: 

<i>He was the happiest man</i>
and knew it wouldn't change.

In other words, italics cover only the first line.

**Comment by niksedk** [comment]
Would you prefer one span

      <p begin="1.0s" id="p0" end="2.0s"><span tts:fontStyle="italic">1<br />2</span></p>

or two spans

      <p begin="1.0s" id="p1" end="2.0s"><span tts:fontStyle="italic">1</span><br /><span tts:fontStyle="italic">2</span></p>

or is it all the same to you? ;)

**Comment by nathaniel1977** [comment]
I believe it's all the same to me :), though ctrl+i covering both lines is more convenient. :)
Thank you.

**Comment by felagund** [comment]
By the way, italics don't work for either timed text draft 2006-04 and 2006-10 (when you try to save subtitles with italics, they just get dropped off). Could that be fixed too? I think I still have a need for those formats.

**Comment by niksedk** [comment]
Should be fixed (for ttml 1.0)
