### ISSUE TITLE
Error attempting to enter translator mode

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2200]
3.5.1 build 51.
If I open SE and a file is not loaded (i.e. I closed it with no file loaded and opened it again), when I try to use the keyboard shortcut for "toggle translation mode", SE pops up the following error:
![se error translator mode](https://cloud.githubusercontent.com/assets/19672444/22619784/d12c078c-eb04-11e6-8cc0-b1508ba54776.jpg)
If I press ignore I can continue working in translator mode as usual.

**Comment by niksedk** [comment]
Thx for the info :)

Hm, what would you expect SE to do?

1) Ignore the command as no subtitle is loaded?
2) Prompt for load of both subtitle and original?
3) Create two empty subtitles?

**Comment by darnn** [comment]
Oh, I'd pretty much expect it to do what it does now: Load the original and leave the translation empty. Or rather create a temporary, unsaved translation subtitle with empty lines but timings from the original.

I always start translating with the translation file empty (and I would assume most people do as well, since you have nothing to put into it yet), so I figured it would make sense for SE to let me open the original file without already having a translation file in place.

This actually reminded me of another issue, I'll post in a second.

**Comment by niksedk** [comment]
So you think it should work like "Tools" -> "Make new empty translation from current subtitle" ?

**Comment by darnn** [comment]
Basically, yeah. As long as I can assign a keyboard shortcut to that too. :)
