### ISSUE TITLE
Fix invalid italics tags does not work with three lines in subtitle

### ISSUE THREAD

**Issue by arydmell** [SubtitleEdit/subtitleedit#2205]
Hi,

When I try to use the "fix common errors" to fix invalid italics tags, it doesn't detect a invalid italic if the subtitle has three lines.

Here is an example:
`<i>First line of text with incorrect italics tag:<br /><i>Second line of text.</i><br /><i>Third line of text.</i>`

**Comment by arydmell** [comment]
Here is the same example from the srt-file I try to fix invalid italics tags:

`26`
`00:01:51,720 --> 00:01:55,600`
`<i>Marit Andreassen:`
`<i>Jeg er glad i mat, men jeg er</i>`
`<i>ikke spesielt flink til å lage det.</i>`

**Comment by niksedk** [comment]
Your examples should be fixed correctly in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip
