### ISSUE TITLE
Sync with timecode

### ISSUE THREAD

**Issue by Lucascostantini** [SubtitleEdit/subtitleedit#2208]
I have an issue generating subtitles of a video with 23,976 fps.
Basically the burned time code match the SE time code at he beginning and then have a gap at the end. Having a difference of one second aprox in a video of 12 min long.
Could you help me to know if I'm doing something wrong.
I´m attaching some screenshots.
![tc00_11_34_23_vs_00_11_35_15](https://cloud.githubusercontent.com/assets/20303641/22750653/6684a420-ee10-11e6-9546-b9259a315d2a.png)
![tc00_00_27_04_vs_00_00_27_04](https://cloud.githubusercontent.com/assets/20303641/22750668/71122ec6-ee10-11e6-883f-6b4780f013d7.png)

**Comment by ROB-000** [comment]
Hi,

did you find a solution for this issue?

**Comment by niksedk** [comment]
I think it's because SE use real world time - try the menu item Video -> SMPTE timing (drop frame)
How does that work?
