### ISSUE TITLE
Import issue into "OCR via image compare"

### ISSUE THREAD

**Issue by MagicGreenDragon** [SubtitleEdit/subtitleedit#2216]
Hi!
I tried to parse a VobSub track from an MKV file, and I select the mode OCR via image compare.

But when I try to import a dictionary, I see this error:
http://prntscr.com/e7bs32

Can you fix it?

Thanks in advance!

**Comment by niksedk** [comment]
Thx for the info :)
That button should have been hidden (it only works for "Binary image compare"). 

"Binary image compare" is recommended over the older "Image compare".
