### ISSUE TITLE
Disable automatic video start

### ISSUE THREAD

**Issue by MagicGreenDragon** [SubtitleEdit/subtitleedit#2220]
Hi!

If I import an mkv or other video file it starts automatically in the video player.

Can you provide a way to disable this options?

Thanks in advance!

**Comment by niksedk** [comment]
New setting in `Options` -> `Settings` -> `Video player` - `Auto-open video file when opening subtitle`
The new setting will be included in next update - and should also be included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
