### ISSUE TITLE
Alt + Drag failed on non-active lines

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2222]
As the title tells, alt + dragging to adjust waveform timing now can only work for the active line, instead of all sections as before.

**Comment by niksedk** [comment]
You would like to use that feature? I'm not sure it ever worked...

Off topic: could you update the Chinese translation yet again :)

**Comment by LeonCheung** [comment]
Oh sure I will keep updating it, as long as SE evolves. :)
Yeah, I'm sure that feature works all fine in older versions, but not perfect any longer in latest version(s). Would you help to check what's going on there?

**Comment by LeonCheung** [comment]
PSP: And this feature seems not working after taking a "Sort by" operation. Should it deserve a new issue report?

**Comment by darnn** [comment]
Also, just a shot in the dark, but might it have something to do with this? https://github.com/SubtitleEdit/subtitleedit/issues/2182
Here's the last beta I have from before the change, in case it helps diagnose it... https://dl.dropboxusercontent.com/u/645489/SubtitleEditBeta%20%2818%29.zip

**Comment by niksedk** [comment]
Perhaps moving should just work for selected lines?
(I guess then Ctrl+click to add to selection instead of setting end time...)

**Comment by LeonCheung** [comment]
Well, you know, many times you just passed some gaps, and you can clearly see what's going on in the waveform, then definitely there's no need to having to select the lines one by one, to make that simple adjustment, then go back to current line to continue the work. In a word, it is just inefficient, very. (I could make a video to show that in real case if necessary)

**Comment by MaximPro** [comment]
Please make a video and show the difference. I would like to see that as well :)
You may use snagit or something to quickly record it.
I'm looking for the optimal workflow as well.

**Comment by LeonCheung** [comment]
Alright. [Here ](https://youtu.be/xkO3KwZUtSw)it is.
Pay attention to operations around 03:05 and 04:55, which can expose the inconvenience, in such workflow maybe?

I don't know why I didn't succeeded in recording the actual video screen and audio, but it doesn't matter I suppose. And, this is a very very simple cartoon project, the speaking speed is fairly slow, so I just met only a few such issue in this case. But I do appreciate the old behavior back.

**Comment by niksedk** [comment]
Hm, perhaps it's the bug f824d3eeb43a5f9fa97f1a277fc35b2a29e5d438 I fixed yesterday (alt+dragging only worked when starting with cursor closest to right sub)?

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Ahh, so far it seems being fixed in that build. Thanks!

**Comment by niksedk** [comment]
thx for verifying.

Fixed in https://github.com/SubtitleEdit/subtitleedit/commit/f824d3eeb43a5f9fa97f1a277fc35b2a29e5d438
