### ISSUE TITLE
OCR still having problems with the "..." character.

### ISSUE THREAD

**Issue by Blacklands** [SubtitleEdit/subtitleedit#223]
I was importing a vobsub and OCR'ing it, when I noticed that the OCR seems to remove any and all "..." that are not in the middle of a line. So if there's a "..." right at the beginning or at the end of a line, without any characters in front/after it, it will just get wiped.

It may be that the OCR always behaved this way, and I just never noticed. I've been using SubtitleEdit for a while, mainly to convert vobsubs from Anime series into text subs, but I'm using it only sporadically, so I'm not sure if it has always been this way.

I looked around a bit, and it seems that this has been an issue for quite a while, and had supposedly been fixed now. Well, not for me unfortunately.

I'm using version 3.4.1, I've even deinstalled SE, deleted any settings, and reinstalled it, and I'm still having the same issues.
I noticed this just now because I'm currently converting the vobsubs from the DVD set of "Earth Girl Arjuna", which are VERY "..." heavy. I might add that the subtitles are in German, but one would think that this shouldn't make a difference.
I've tried the OCR set to English and German, but it seems to behave exactly the same, wiping any "..." in front or at the end of lines.

Unfortunately, adding them back by hand is not an option, as there are just too many "..." in the subtitles to do that. Also, I don't think that this is intended behavior, as it doesn't make much sense, at least not without any option to turn it off.

I've looked in the options tab of SubtitleEdit, but there seems to be no entry in the "OCR correction list" which has to do with the "..." character.

I would very much like some kind of reply to this, possibly at least a workaround, because I LOVE SubtitleEdit, but with this issue, it's completely unusable for "..." heavy subtitles.

If you need more information about my setup, just tell me and I'll provide it. I can also upload the vobsub file, so that you can see it for yourself.

Thanks in advance!

EDIT: I've attached an example screenshot as well - hope you don't mind that the GUI is in German.

![unbenannt-1](https://cloud.githubusercontent.com/assets/4943543/4004220/69de6f74-297e-11e4-842d-7db53ef3440a.jpg)

**Comment by Reino17** [comment]
I haven't used Subtitle Edit for quite some time. But when I did last week to process a bluray subtitle, I noticed I had the same "..." issue.

This is a screenshot of the subtitle in question:
![got_tesseract-issue](https://user-images.githubusercontent.com/8537830/30121943-49ef98de-932d-11e7-8b63-152b5d2f0422.png)
Subtitle Edit (with Tesseract) constantly returns:
```
Er komt oorlog.
Ik weet niet wanneer maar er komt oorlog.
```
I've done some research.

I've found https://github.com/UB-Mannheim/tesseract/wiki hosting up-to-date Tesseract builds, so I've first of all updated the ancient '_tesseract.exe_' (from 26 okt 2012) that Subtitle Edit 3.5.3 comes with.
Tesseract 3.05.01 still puts out the same:
```
ffmpeg.exe -hide_banner -i Tesseract-issue.png -f image2 -c:v png - | tesseract-3.05.01.exe - -
Input #0, png_pipe, from 'Tesseract-issue.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 636x131, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'pipe:':
  Metadata:
    encoder         : Lavf57.75.100
    Stream #0:0: Video: png, rgb24, 636x131, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc57.100.104 png
frame=    1 fps=1.0 q=-0.0 Lsize=N/A time=00:00:00.04 bitrate=N/A speed=0.0382x
video:19kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Warning. Invalid resolution 0 dpi. Using 70 instead.
Er komt oorlog.
Ik weet niet wanneer maar er komt oorlog.
```
Resizing the image to 200% doesn't help either:
```
ffmpeg.exe -hide_banner -i Tesseract-issue.png -vf scale=iw*2:ih*2 -f image2 -c:v png - | tesseract-3.05.01.exe - -
[...]
    Stream #0:0: Video: png, rgb24, 1272x262, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
[...]
Warning. Invalid resolution 0 dpi. Using 70 instead.
Er komt oorlog.
Ik weet niet wanneer maar er komt oorlog.
```
OCR Engine mode "Tesseract + cube" is coming close:
```
ffmpeg.exe -hide_banner -i Tesseract-issue.png -f image2 -c:v png - | tesseract-3.05.01.exe - - --oem 2
[...]
Warning. Invalid resolution 0 dpi. Using 70 instead.
Er komt oorlog.
lk weet niet wanneer ..' maar er komt oorlog.
```
Tesseract 4.0.0-alpha.20170804 seem to do it right:
```
ffmpeg.exe -hide_banner -i Tesseract-issue.png -f image2 -c:v png - | tesseract-4.0.0-alpha.exe - -
[...]
Warning. Invalid resolution 0 dpi. Using 70 instead.
Er komt oorlog.
lk weet niet wanneer ... maar er komt oorlog.
```

---
I've also built Tesseract 4 myself and somehow it uses 300 dpi by default:
```
ffmpeg.exe -hide_banner -i Tesseract-issue.png -f image2 -c:v png - | tesseract-4.00.00alpha.exe - -
[...]
Warning. Invalid resolution 0 dpi. Using 300 instead.
Er komt oorlog.
Ik weet niet wanneer ... maar er komt oorlog.
```
Could the dependency libraries have anything to do with it?
```
tesseract 4.0.0-alpha.20170804
 leptonica-1.74.4
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.5.0) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0
vs.
tesseract 4.00.00alpha
 leptonica-1.74.4
  libgif 5.1.4 : libjpeg 9b : libpng 1.6.32 : libtiff 4.0.8 : zlib 1.2.11 : libwebp 0.6.0 : libopenjp2 2.2.0
```
---

Now, the thing is, Tesseract 3.05.01 in Subtitle Edit 3.5.3 works fine, but doesn't OCR the subtitle right. Tesseract 4 (both builds) on the other hand don't work in Subtitle Edit 3.5.3. The OCR process does start, but lines remain empty or are OCRed wrong. But above all, it's much slower and uses a lot more memory!
Does Subtitle Edit have to be updated first to properly work with Tesseract 4?

---

**A side note**: I'm still on Windows XP on a non-sse2 cpu and up until this week I've been using Subtitle Edit 3.4.2. It was the latest build that didn't crash upon starting the OCR process.

http://www.nikse.dk/SubtitleEdit/Help#issues:
> Spell check (NHunspell) crashes | You can change spell check to use MS Word in Options!

But then I read this.
I've replaced '_Hunspellx86.dll_' from v.3.5.3 with the one from v3.4.2 and suddenly the OCR process started without problems.
Next I had a look at https://github.com/hunspell/hunspell. Building v1.6.2 was easy enough. My MingGW setup produced a '_libhunspell-1.6-0.dll_'. After renaming it to '_Hunspellx86.dll_' and putting it in the Subtitle Edit 3.5.3 map, the OCR process again started without problems!

So Windows XP users can use this [Hunspellx86.dll](http://rwijnsma.home.xs4all.nl/files/other/libhunspell-x86-v1.6.2_legacy.7z) for Subtitle Edit v3.4.3 - v3.5.3.

**Comment by niksedk** [comment]
@Reino17: thx for the input :)

Yes, Tesseract 4 seems good (and does work fine with SE) but it's at least 4 times as slow and more memory (use some neural network I think) and even worse - it sometimes ignores a line here and there :(
But T4 is still in alpha, so it might be several years before we see a final...
Also, see this: https://github.com/SubtitleEdit/subtitleedit/issues/2480

**Comment by niksedk** [comment]
A Tesseract issue, not really too much SE can do about this.
Next update of SE will include Tesseract 5 alpha - perhaps that works better with these trailing spaces.
"Binary image compare" is an alternative.
