### ISSUE TITLE
Timed Text Styles Not Working

### ISSUE THREAD

**Issue by aucforum** [SubtitleEdit/subtitleedit#2233]
I am getting an Error in SubtitleEdit when I right click on Timed Text Styles in the text column of a subtitle like this:

![20170221_subtitleedit_timedtextstyles-textcolumnrightclick](https://cloud.githubusercontent.com/assets/25918652/23151553/5e54296a-f847-11e6-93d5-9b36721cfa79.png)

Which results in a Windows Error of an Object Reference Not Found as:

![20170221_subtitleedit_timedtextstyles-errorwindow-objectreferencenotsettoaninstanceofanobject](https://cloud.githubusercontent.com/assets/25918652/23151554/629874fe-f847-11e6-988a-39f7154f9336.png)

Can you please advise what needs to tbe done to correct this?

Furthermore, will this allow me to produce TTML subtitles in for use Youtube? SOme notes I have made include:

Supported subtitle and closed caption files - Advanced File Formats
https://support.google.com/youtube/answer/2734698
TTML (Timed-Text Markup Language)	.ttml	In partial implementation. SMPTE-TT extensions supported for CEA-608 features. iTunes Timed Text (iTT) file format is supported; iTT is a subset of TTML, Version 1.0. Styling and positioning are
supported.

Speechpad - TTML (Timed Text Markup Language)
https://www.speechpad.com/captions/ttml

TTML Subtitle Example 
https://gist.github.com/anotherhale/676a72edc84ca3a37c0c#file-subtitle_example-xml

What I am trying to do is to find a way to make subtitles that will work in YouTube that can allow for differnet fonts, styles, positions, colors, basic markups `(<b>, <i>, <u>)`, etc.

Thank you for your help!

**Comment by niksedk** [comment]
First, I cannot re-produce the bug - could you attach or email me the subtitle?
(I'll try to look at the other questions later)

**Comment by aucforum** [comment]
Sorry for the newbie questions: How do I implement the fix? Or do I have to wait for a new version to be compiled and published on your website?

**Comment by niksedk** [comment]
The fix will be included in next update - probably in a week or two...
You can compile the source code or try latest portable beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip
