### ISSUE TITLE
Feature request(?) - list view column sizes

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2238]
Speaking of column sizes...

 This is partly a bug report (or at least a report of behavior that is perhaps unintended) and partly a feature request. What I'm referring to is the column sizes of the list view.
Currently (e.g. 3.5.1 build 141), when SE is opened, the columns are at their default size. If one changes their sizes, they persist when SE is closed and opened again, or when switching between translator mode and regular mode, or when toggling video on/off... unless one of the columns is shrunk too much. If you for instance shrink the "end time" column so that you can't see it anymore, and close SE and open it again, the columns are back to their default size. I'd like for this to not happen, because sometimes I need to shrink e.g. "end time" in order to expand "text" and "original text" to accommodate the lengthy subtitles inside of them.
So, that's one element. The other element is that sometimes this popping of the column sizes back to default will just happen spontaneously. It's hard for me to reproduce this, but usually if I minimize the window and leave it alone for like half an hour, I'll come back to find that the column sizes have changed.

Now, other thang changing those two things, the feature request part of this is that I think it would be great if the columns behaved similarly to, say, columns in Windows Explorer. When you right-click columns in Explorer you see this menu:
![column menu](https://cloud.githubusercontent.com/assets/19672444/23231538/e2842190-f950-11e6-86c5-74a56aa3f152.png)
The menu, as you can probably tell, allows you to enable/disable certain colums outright. This would be good in general (if, again, someone needs the space on the screen for a certain column and not another one), but it would also be important to have if column sizes are truly saved permanently and don't revert to default after they're shrunk, because you can effectively shrink a column into not appearing on the screen, and it would be hard to make it appear again without this menu.

The way Windows Explorer itself implements this, incidentally, is that you can't shrink columns under a certain size (so they can't "disappear"), but you can, as I've said, just turn them off temporarily. And, for the record, this is also how this behavior is implemented in the last Subtitle Workshop beta:
![column menu sw6](https://cloud.githubusercontent.com/assets/19672444/23231854/f4b1b4c6-f951-11e6-9e11-33fffddf074d.png)

**Comment by niksedk** [comment]
Just a quick test, something like this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip
Should the "Show column button" be removed from Options - Settings - General ?

**Comment by darnn** [comment]
Yeah, like that, except with all of the columns, naturally... And I suppose you can either keep it or remove it, maybe some people are used to it where it is. I never even noticed it, and it seems like everything other than chars/sec and words/min is greyed out in it anyway. Windows Explorer does show the menu both through right-clicking the column list and through view->choose details, so on the basis of that I'd keep it.

**Comment by niksedk** [comment]
thx for the input :)
I've updated the beta here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip

Let me know how it works...

**Comment by darnn** [comment]
Thank you for adding the menu! However, for me, it doesn't display all the columns:
![se column menu](https://cloud.githubusercontent.com/assets/19672444/23256570/ad21c7e6-f9c8-11e6-8139-0fbfa33a6df3.png)
Not that I'd ever want to turn off "test" or anything, but if I accidentally shrink it down to nothing, it'd be nice to be able to turn it off and on again to make it come back.

And also, the sizes of the columns continue to revert to default when I do something to "refresh" the list view, such as show/hide video:
![se column size revert](https://cloud.githubusercontent.com/assets/19672444/23256693/443e1878-f9c9-11e6-8b7a-4c93cedf86ee.gif)

**Comment by niksedk** [comment]
thx for testing :)

It does not display all the columns but the most important ones.

Show/hide video or other stuff that refreshes the list view will only auto-size a column if it's very small (<10 pixels).

If you accidentally shrink a column it will be there again when you restart / resize columns / refresh list view.

Updated beta again as last one was very install if end-time+duration was hidden: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Seems good so far! I'll use it for a few days and let you know if I find anything amiss. And thanks again, this really makes things easier for me!

**Comment by niksedk** [comment]
thx for the nice suggestion - definitively much faster/easier to use than settings :)
