### ISSUE TITLE
Feature req: SRT tags visibility.

### ISSUE THREAD

**Issue by Yamato-ua** [SubtitleEdit/subtitleedit#2247]
Hello there.

Would be nice to have an option to turn off visibility of certain SRT tags in the List view.
Like vertical position tags `{\an2} and {\an8}`, which some titles have. And `<i>, <b>, <u>` too. 
They have to be kept as they are but are sometimes inconvenient when translating.

I think `{\an2}` in SRT should be treated like those C1Y00 in Structured titles, i.e. not shown in List view at all. And `<i>, <b>, <u>` visibility should be selectable in the Settings. 

Thanks.

**Comment by LeonCheung** [comment]
To remove all tags, you can always Ctrl A > RMB > Normal (remove formatting). But for temporally "hide" them from the view, yes, this might be something comfortable for eyes, but can also be dangerous while trying to edit subs, because it will make things messy easily without noticing errors.

**Comment by aaaxx** [comment]
[Related](https://github.com/SubtitleEdit/subtitleedit/issues/1886).

**Comment by Yamato-ua** [comment]
Thanks guys.

Another idea is to move alignment tags to a separate column (which then could be toggled in Settings).
It's not that they're inconvenient to see per se, it's just that they're autoselected with the whole text field when switching the line with alt+down.

**Comment by paulscholes0258** [comment]
> 
> 
> Cảm ơn các bạn.
> 
> Một ý tưởng khác là di chuyển các thẻ căn chỉnh sang một cột riêng biệt (sau đó có thể được chuyển đổi trong Cài đặt).
> Không phải là chúng bất tiện khi xem, chỉ là chúng được tự động chọn với toàn bộ trường văn bản khi chuyển dòng bằng alt + xuống.

Hi bro. I also try to find hide tags in text box . can you introduce to move tag to a separate column ?
I cannot find how to do it. thans for my english.
