### ISSUE TITLE
The "undo" action in the text field

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2248]
3.5.1 build 167, although it's not a recent behavior:
When typing in the text box, pasting a piece of text and then immediately undoing, this not only removes the pasted text, but also the rest of the text in the subtitle:
![se undo](https://cloud.githubusercontent.com/assets/19672444/23333213/63812086-fb90-11e6-847a-cf25c07de87c.gif)

**Comment by ivandrofly** [comment]
Can you please try the following and see if it still include previously typed text as undo text:

Type a word and wait 1 second before ctrl+v again wait 1 second before ctrl+z and see if 
it still undo the whole text.

**Comment by darnn** [comment]
No, that way it does remove only the pasted text... Is there a way to decrease that interval?

**Comment by niksedk** [comment]
The current undo is after 700ms of no input. It guess it can be decreased... 400-500ms?

**Comment by darnn** [comment]
Is there a way to make a special case for pasted text? I think it's fine for typed text, the problem is pasting something unintended. Because when that happens I notice immediately and press ctrl+z immediately, so pretty much any interval (over, like, 100, probably) is too large. But I also don't want to mess with the interval for typed text.
I've also tested a couple of other text editors and they both treat pasted text and typed text differently:
WordPad:
![wordpad undo](https://cloud.githubusercontent.com/assets/19672444/23473685/c9bc0bb4-feb9-11e6-8691-4a15e5510ac6.gif)
EditPad:
![editpad undo](https://cloud.githubusercontent.com/assets/19672444/23473693/cdebdcbe-feb9-11e6-805a-d9dc44cb3279.gif)

**Comment by LeonCheung** [comment]
@niksedk Good idea I suppose.

**Comment by niksedk** [comment]
OK, that's also included in latest beta :)

**Comment by darnn** [comment]
Works fine over here!

**Comment by niksedk** [comment]
cool, thx for verifying - is included in SE 3.5.2 :)
