### ISSUE TITLE
Feature request: Moving words up/down inside subtitles

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2249]
Hey. I think I mentioned this in an email already, but since you were asking if there was anything else we wanted implemented for the new version:
SE currently does this:
Move last word down to next subtitle line [Control+F1]
Move first word from next subtitle line up [Control+F2]
Which looks like this:
![se move words1eng](https://cloud.githubusercontent.com/assets/19672444/23333914/45e35122-fb9d-11e6-8ac1-48c40ac1fd35.gif)

What I'd like (and which I've already hacked together for myself using an external program that sends keystrokes to SE) is something that moves, for instance, the last word in the first line of the subtitle to the second line in the subtitle, or the first word in the second line up to the first line, like this:
![se move words2eng](https://cloud.githubusercontent.com/assets/19672444/23333916/49614e12-fb9d-11e6-92ae-82a184e4f15e.gif)

**Comment by aaaxx** [comment]
[Related](https://github.com/SubtitleEdit/subtitleedit/issues/1380).

**Comment by niksedk** [comment]
Could you test this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

The settings are not in the UI yet, but look for the settings `MainTextBoxMoveLastWordDownCurrent` and `MainTextBoxMoveFirstWordUpCurrent`  in Settings.xml.

**Comment by darnn** [comment]
Hey, I hate to bug you, but since I see you're pushing out other updates, is there any chance you can make MainTextBoxMoveLastWordDownCurrent and MainTextBoxMoveFirstWordUpCurrent have the cursor maintain its relative position in the subtitle (like in https://github.com/SubtitleEdit/subtitleedit/issues/2394), or at least move to the very end of the subtitle (i.e. where it would go if you pressed ctrl+end in the textbox) rather than the beginning?
I've been using the feature ever since you implemented it, and it's great! Much better than my way, which mangled any subtitles with numbers in them. But the way I had always used mine was, I would type a line (or two) and then see that one of them is too long, hit the key for moving one of the words up/down, and then continue typing. Which is, I believe, how anyone would use this. But since the cursor goes back to the beginning now, when I continue typing, the new text appears at the beginning of the first line, rather than at the end of the subtitle.

**Comment by niksedk** [comment]
So, should we keep the position or just go to the end?

**Comment by darnn** [comment]
I'd rather keep the position, I think it's the least disorienting option.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
How does that work?

**Comment by darnn** [comment]
Overall it works great!
There is one exception, though.
So, my config file looks like this:
```
<MainTextBoxMoveLastWordDownCurrent>OemOpenBrackets</MainTextBoxMoveLastWordDownCurrent>
<MainTextBoxMoveFirstWordUpCurrent>Oem6</MainTextBoxMoveFirstWordUpCurrent>
```
Which is to say, the keys to shift the words within the subtitle are [ and ].
Now, when I move the cursor to the end of the first word in a subtitle, and start moving the words down, after I move them all down except the first word and then press the key again, the entire subtitle will move to the first line (as it should), but the cursor will move back one letter. If I repeat this process enough, eventually the cursor reaches the start of the subtitle, and when that happens, SE gives an error. I'm attaching a gif of the entire process plus the error message.
![se-moving-words-error_](https://user-images.githubusercontent.com/19672444/35187874-3f5d877e-fe34-11e7-93ee-593d5b11de39.gif)
![se-moving-words-error](https://user-images.githubusercontent.com/19672444/35187876-42a62df0-fe34-11e7-994d-7ccc86ee0526.png)

**Comment by niksedk** [comment]
thx for testing :)
New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Works great! Thank you!

I don't know if this falls within the scope of what you want to implement, but in translator mode this currently doesn't work in the original textbox, only in the translation. Other than that, feel free to close this.
