### ISSUE TITLE
Waveform display issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2253]
Just wonder if this is normal:
![prob](https://cloud.githubusercontent.com/assets/494788/23347448/71ce28ca-fcdd-11e6-8323-8395a7ccfa20.gif)

**Comment by niksedk** [comment]
thx :)

I had tried to make a minor optimization - move a calculation out of a loop but I divided where I should have been multiplying - my basic math failed ;)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.1/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Haha that's okay. We are human, aren't we  :D thx for the quick fix.
