### ISSUE TITLE
Source view not available

### ISSUE THREAD

**Issue by DanielLH333** [SubtitleEdit/subtitleedit#2258]
On Windows 10 64-bit. Tried multiple versions.

Under source view it merely says "not supported".

Any ideas?

Thanks.

**Comment by ivandrofly** [comment]
Some subtitle formats can't be displayed via Source-View

**Comment by DanielLH333** [comment]
Neither .srt or .stl work for me. Seems odd.

**Comment by ivandrofly** [comment]
> Neither .srt or .stl work for me. Seems odd.

Both .srt an d .stl can be view... how did you produce the error exactly?

**Comment by DanielLH333** [comment]
The error occurs every time I load a file in Subtitle Edit.
I've never been able to use Source View. List view works fine.

**Comment by darnn** [comment]
Works on my wife's computer. I don't know if it's 64 bit or not, but here's source view in action and the winver info:
![sewin10](https://cloud.githubusercontent.com/assets/19672444/23413212/bb58d9aa-fde0-11e6-932c-5ea7734b91ce.png)

**Comment by niksedk** [comment]
EBU STL has no source view (raw text) as it's binary.

@DanielLH333: Can you add a screenshot of .srt source view not working?
