### ISSUE TITLE
Matroska TimecodeScale ignored

### ISSUE THREAD

**Issue by mkver** [SubtitleEdit/subtitleedit#2259]
Hello,

it seems that the TimecodeScale in Matroska files is ignored. Or more precisely: All Matroska files seem to be treated as if they had a TimecodeScale of 1000000 (means 1ms precision). This can be easily shown by either manipulating the TimecodeScale element of an existing matroska file with an hex editor (nothing changes when opening the file with Subtitle Edit which is not expected behaviour) or by e.g. using MKVToolNix and its --timecode-scale feature to directly specify the TimecodeScale.
Looking at the code, we can see that [TimecodeScale](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/ContainerFormats/Matroska/MatroskaFile.cs#L315) is read and used on several occasions, but not at the actual place where it matters, namely in [ReadBlockGroupElement](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/ContainerFormats/Matroska/MatroskaFile.cs#L388) and in [ReadSubtitleBlock](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/ContainerFormats/Matroska/MatroskaFile.cs#L419). (At least I think that it is enough to change these two functions, but I am not sure. I am not well versed in your code.)

Greetings 
mkver

PS: What exactly is the purpose of [this line](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/ContainerFormats/Matroska/MatroskaFile.cs#L320)? It doesn't make any sense to divide the duration in TimecodeScale units by TimecodeScale. These values should be multiplied which yields the duration in ns; division by 1000000 gives the duration in ms. But I don't see where this element is used at all, so I might be wrong.

**Comment by niksedk** [comment]
@mkver: thx for the info :)
Should be fixed in commit https://github.com/SubtitleEdit/subtitleedit/commit/4e38be9546d24f0009535da9ccc07c235447e4b5

Full portable beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

**Comment by mkver** [comment]
Sorry for being so late, but unfortunately this is still not fixed. It still behaves as if the TimecodeScale is 1000000. I don't know why.

**Comment by niksedk** [comment]
I've tested with files generated by mkvtoolnix and that worked for me... could you supply a file where it's not working?

**Comment by mkver** [comment]
Of course. [This file](https://www.dropbox.com/s/movf44ho9icg8yo/Hank.Zipzer.S01E02.The.lucky.Socks.ger.mks?dl=0) here has been created with MKVToolNix from [this file](https://www.dropbox.com/s/fxd8c0oyt5tdekh/Hank.Zipzer.S01E02.The.lucky.Socks.ger.srt?dl=0) with a timecode-scale of 10000000.

**Comment by niksedk** [comment]
np, thx for verifying :)
