### ISSUE TITLE
libse and Assemblyinfo.cs file not found in subtitle edit 3.5.1 version

### ISSUE THREAD

**Issue by mangeshm-cdac** [SubtitleEdit/subtitleedit#2260]
dear all,

i am trying to import subtitle edit 3.5.1 in visual studio but it is not working ,,its showing error's like 
1)reference file libse is missing
2) assemblyinfo.cs not found

**Comment by niksedk** [comment]
You have to create the Assemblyinfo.cs manually from AssemblyInfo.cs.template - replace "[REVNO]" with e.g. "0". 

Another solution is to install git.

**Comment by mangeshm-cdac** [comment]
Thanks
