### ISSUE TITLE
Error get dictonary

### ISSUE THREAD

**Issue by Baswazz** [SubtitleEdit/subtitleedit#2261]
When i add the dutch dictionary from the menu: Spellcheck > Get dictionaries

![screenshot 2](https://cloud.githubusercontent.com/assets/1690629/23558875/866bf46e-0035-11e7-8894-da6d5ee169b6.png)

Windows 10 x64, SE352.zip (portable)

**Comment by kaser2010** [comment]
http://prntscr.com/eflmai

**Comment by niksedk** [comment]
@Baswazz: Do you still get this error? I just tried and it worked...

**Comment by niksedk** [comment]
@kaser2010: thx for the info - will be fixed in next update.
