### ISSUE TITLE
Save all Images with HTML index does not specify charset in HTML

### ISSUE THREAD

**Issue by dgonyier** [SubtitleEdit/subtitleedit#2262]
Windows 10 64-bit, Subtitle Edit 3.5.2, Firefox as default browser.

In the OCR mode, when I right click and select "Save all images with HTML Index..." the HTML file generated by Subtitle Edit does not specify charset so the browser will have guess the character encoding. The generated HTML file appears to be UTF-8. 

In my case Firefox is the default browser and the default character encoding is "windows-1252", so extended characters in the generated HTML file like ♪ look like garbage characters when rendered by the browser.

I manually fixed the HTML by adding a meta tag to specify the character set:

    <html>
    <head><title>Subtitle images</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"> </head>
    <body>
    ...
    </body>
    </html>

After this edit to the HTML file Firefox, Chrome, and Microsoft Edge on my system all rendered the extended characters in the HTML file correctly.

To fix this, Subtitle edit should set the charset to UTF-8 (or whatever the actual used character set is) in the HTML file generated based on user locale.

**Comment by dgonyier** [comment]
Fix looks good. Just a minor detail: It looks lke the `<title>...</title>` HTML is repeated twice in the updated code.

**Comment by niksedk** [comment]
Yeah, thx - was fixed in a later commit: c790596086776aaa4876efee3d9af61f73f57a2c
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
