### ISSUE TITLE
Subtitle Edit works perfectly on previous version than 3.5.2

### ISSUE THREAD

**Issue by alti1981** [SubtitleEdit/subtitleedit#2263]
3.5.2 installs fine, finish fine. Once you start it, it just hangs and VSFilter just hangs also on your process icon. 

# Advice on everyone is to NOT use 3.5.2 hence it is buggy with this one.

ADVISORY: DO NOT USE SUBTITLE EDIT 3.5.2 except previous versions.

Use Subtitle Edit 3.5.1 until newer release is made.

https://github.com/SubtitleEdit/subtitleedit/releases/tag/3.5.1

**Comment by niksedk** [comment]
@alti1981: It works fine here... also, I'm pretty we did not change anything related to directshow.
Perhaps it would help if you installed latest version of LAV filters? 
https://github.com/Nevcairiel/LAVFilters/releases/download/0.69/LAVFilters-0.69-Installer.exe

Are anybody else having problems with directshow/vsfilter?

**Comment by darnn** [comment]
Not me. I had been using the portable version of 3.5.2 so far, but I downloaded the installer now, and the installed one works fine as well.

**Comment by alti1981** [comment]
Never needed anything installed additional latest of, so lame, one
lavfilter has to be updated hence written that you don't have to use the
latest hence it only will eat your processor up because of it.
Others like me do not part take anything that eats up your priorities,
lavfilter or directshow overloading much?

**Comment by niksedk** [comment]
I'll close this one for now as I don't think it's a general problem...
Also, no changes were made to the DirectShow player: https://github.com/SubtitleEdit/subtitleedit/commits/master/src/Logic/VideoPlayers/QuartsPlayer.cs
