### ISSUE TITLE
SE352 Trojan/Keylogger detected

### ISSUE THREAD

**Issue by geeky-gurl** [SubtitleEdit/subtitleedit#2264]
FYI Kaspersky, for both portable and Windows installer versions, CheckSum and Hash match, but Kaspersky is throwing Trojan/Keylogger Malware found alert.
Malware found in Subtitle-Edit-3.5.2-Setup.exe//data0077
Object name: Trojan-Spy.MSIL.Keylogger.cmjc

Also FYI MalwareBytes isn't detecting any malware in them.

I'm currently using SE35 which does not have this problem.

**Comment by niksedk** [comment]
(As usual) I've reported the issue to Kaspersky - please do the same if your antivirus complains.

I got this message from Kaspersky: ´We will thoroughly analyze files. If the result of the analysis is different from this scan result, you will be notified via email within 5 days.´

**Comment by niksedk** [comment]
SHA1 checksums are for the zip files. Which one does not match?

**Comment by geeky-gurl** [comment]
@niksedk  Thanks for your reply and for alerting Kaspersky. I just edited the title, because I realized while typing my message that the Checksums were relevant to the zip file and forgot to change the title. Sorry for any confusion.

**Comment by niksedk** [comment]
@geeky-gurl: Kaspersky seems to be happy now: https://www.virustotal.com/en/file/88ad0af7dfe1483125c31ec29cd11fc4d3ad0ea6576b603fe65cf71bd72d28a5/analysis/

Virustotal had a detection ratio 3 / 58 last I tried - I tried to report to the last three also, but one has a full mailbox and another has a broken upload page... perhaps not so serious ;)
