### ISSUE TITLE
In translator mode, the "redo" function causes the source file to overwrite the translation file.

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2265]
Hey. 3.5.2 3588ccc (although I'm fairly certain this has been going on for a long, long time).
I've referenced this before, but only now accidentally found the method to reproduce it.
In translator mode, a translation file and a source file must be open and saved. Now, if you modify both the source and the translation, then type something, undo it and then redo it, SE will overwrite the translation file with the source file.
Specifically, nothing will change in the "original text" and "text" columns. But in the window title, instead of "path\translation.ext" + "path\source.ext", it will now show "path\translation.ext" + "path\translation.ext", and the next time both files are saved (through the "save all" keyboard shortcut), the contents of the translation file will be overwritten with the source file.
![se redo](https://cloud.githubusercontent.com/assets/19672444/23582896/07e2f52a-013e-11e7-8c90-bd9b9d8369bd.gif)
I realize the description is kinda complicated, so let me know if you need me to explain it further.

**Comment by niksedk** [comment]
thx :)

I've updated the beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Works like a charm!
