### ISSUE TITLE
Version Subtitle Edit 3.5.2 contains Trojan TrojanSpy: Win32/Skeeyah.A!rfn /MS false positive

### ISSUE THREAD

**Issue by Tester0815** [SubtitleEdit/subtitleedit#2266]
Downloaded just 
Subtitle Edit 3.5.2
-> Defender warning and deleted 
SubtitleEdit.exe
Identified TrojanSpy: Win32/Skeeyah.A!rfn

**Comment by niksedk** [comment]
Please report false positive to your anti virus provider!

Also check this: https://github.com/SubtitleEdit/subtitleedit/issues/2264
It's the same every time SE is released :(

**Comment by niksedk** [comment]
I've tried to report it as a false positive here: https://www.microsoft.com/en-us/security/portal/submission/submit.aspx - but I just got an error
    Request Timeout
    The server timed out while waiting for the browser's request.
    Reference #2.e981160.1488738394.365dfdc3 

So please submit it if you want to help!

**Comment by niksedk** [comment]
OK, got through their system at last:

     Thank you for submitting suspicious file(s) to the Microsoft Malware Protection Center (MMPC).
This email acknowledges that we have successfully received the following file(s) at Sunday, March 5, 2017 10:32 AM Pacific Time:

File
========================================
SubtitleEdit.zip


Your submission has been assigned ID MMPC17030548304171, you can view your submission at
http://www.microsoft.com/security/portal/Submission/SubmissionHistory.aspx?SubmissionId=ee6f2bdd-d70f-4192-a3dd-6fff8968680a
Please keep this email and ID for future reference. Customers who are logged into our portal when they submit the sample(s) can later check the status of the submitted file(s) by viewing their submission history page.

The MMPC will analyze the file(s) that you submitted to determine if they contain malware or other potentially unwanted software.
If any file(s) in your submission are identified as either, the MMPC will add detection and publish definition updates after testing and certification.

**Comment by niksedk** [comment]
And virustotal is a nice site: https://www.virustotal.com/en/file/88ad0af7dfe1483125c31ec29cd11fc4d3ad0ea6576b603fe65cf71bd72d28a5/analysis/1488739073/

**Comment by Tester0815** [comment]
Thank you
