### ISSUE TITLE
Trojan in version 3.5.2??

### ISSUE THREAD

**Issue by Thilas** [SubtitleEdit/subtitleedit#2268]
While installing the last version of SubtitleEdit, I got a report from Windows Defender about a trojan (TrojanSpy:Win32/Skeeyah.A!rfn).

And according to VirusTotal, other antiviruses detects something wrong: https://www.virustotal.com/fr/file/955bf1da26206a9d36780d485df5899507e9502d9517b90c2a396b267b8198c1/analysis/

Thanks for your quick answer.

**Comment by ivandrofly** [comment]
Already reported => https://github.com/SubtitleEdit/subtitleedit/issues/2266

**Comment by Thilas** [comment]
Thanks.
