### ISSUE TITLE
subtitle 3.5.2 OCR

### ISSUE THREAD

**Issue by alfix0** [SubtitleEdit/subtitleedit#2277]
when I try to ocr a Bluray SUP file I gert a eeror whwn try to add word to dictionary
![error](https://cloud.githubusercontent.com/assets/26274309/23700304/b4218b38-03f2-11e7-99de-a37df4a431eb.png)

**Comment by niksedk** [comment]
Thx :)

Should be fixed in commit: bcf566c96197298681350d5f7f64708c2f7bcce5
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
