### ISSUE TITLE
Error doing OCR in a second instance of SE when trying to add a word to dictionary

### ISSUE THREAD

**Issue by Muntra** [SubtitleEdit/subtitleedit#2280]
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Objektreferencen er ikke indstillet til en forekomst af et objekt.

Stack Trace:
   ved Nikse.SubtitleEdit.Logic.Ocr.OcrFixEngine.SpellCheckOcrText(String line, Bitmap bitmap, String word, List`1 suggestions)

   ved Nikse.SubtitleEdit.Logic.Ocr.OcrFixEngine.FixUnknownWordsViaGuessOrPrompt(Int32& wordsNotFound, String line, Int32 index, Bitmap bitmap, Boolean autoFix, Boolean promptForFixingErrors, Boolean log, AutoGuessLevel autoGuess)

   ved Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.OcrViaTesseract(Bitmap bitmap, Int32 index)

   ved Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.MainLoop(Int32 max, Int32 i)

   ved Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.mainOcrTimer_Tick(Object sender, EventArgs e)

   ved System.Windows.Forms.Timer.OnTick(EventArgs e)

   ved System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)

   ved System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Afbryd   Forsøg igen   Ignorer   
---------------------------

**Comment by niksedk** [comment]
I think this has been fixed ( via bcf566c96197298681350d5f7f64708c2f7bcce5 ) in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
