### ISSUE TITLE
"Go to Next line" doesn't launch video

### ISSUE THREAD

**Issue by MaYouniSS** [SubtitleEdit/subtitleedit#2282]
when I hit the Go to Next line button _which I had customized_ It doesn't launch the video
It Just goes to the next line and stops, Even when I use "**go to next empty line**"
it's really the first time I experience this issue with the latest update

**Comment by niksedk** [comment]
thx for the info :)

I can see this has been in commit 7fc0da0937a85b2f15490bc3d73d38f81bdf01ba - will be included in next version.
