### ISSUE TITLE
Error with new update when I want to add a new word to the dictionary

### ISSUE THREAD

**Issue by Ninelpienel** [SubtitleEdit/subtitleedit#2284]
I have updated SubtitleEdit to the newest Version and now I can’t add words to the dictionary anymore: https://u.biyori.moe/MLVZ3IDh.png

**Comment by ivandrofly** [comment]
Is this fixed? @Ninelpienel

**Comment by niksedk** [comment]
See #2277

**Comment by niksedk** [comment]
And this one too: #2280
