### ISSUE TITLE
Erro ao baixar dicionario portugues BR

### ISSUE THREAD

**Issue by jorgepbjr** [SubtitleEdit/subtitleedit#2285]
![erro](https://cloud.githubusercontent.com/assets/26388890/23867294/3460c6e6-07fa-11e7-88eb-0a39dcc81812.png)

**Comment by ivandrofly** [comment]
Error message: "Invalid datas found while parsing"

Didn't you lose connection while downloading?
What version of SE are you using?

**Comment by ivandrofly** [comment]
I think we should embed version info into error-message-form." /cc @niksedk

**Comment by jorgepbjr** [comment]
No, I did not lose the connection. I've tried it more than once ...


tks.

________________________________
De: Ivandro Ismael <notifications@github.com>
Enviado: segunda-feira, 13 de março de 2017 12:59:27
Para: SubtitleEdit/subtitleedit
Cc: jorgepbjr; Author
Assunto: Re: [SubtitleEdit/subtitleedit] Erro ao baixar dicionario portugues BR (#2285)


I think we should embed version info into error-message-form." /cc @niksedk<https://github.com/niksedk>

**Comment by ivandrofly** [comment]
Please try this version and see if error still happening https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
