### ISSUE TITLE
Problem with the German open quotation mark

### ISSUE THREAD

**Issue by Ninelpienel** [SubtitleEdit/subtitleedit#2299]
Hey, there is a problem with the German open question mark. It will be detected as a normal word or a part of a normal word: https://u.biyori.moe/0SJc2m1v.png

The character of the open quotation mark is „ and from the close quotation mark “.

**Comment by niksedk** [comment]
Test version here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
