### ISSUE TITLE
Feature Suggestion: Add position for signs and Combining text from multiple lines

### ISSUE THREAD

**Issue by tigre7575** [SubtitleEdit/subtitleedit#23]
First off this is the best sub ocr program I've ever used. Not only does it go a good job, the interface is quite good. However it's missing two features I like from other ocr programs.

The ability to position signs where they are on screen.
{\pos(130,163)}Sign Here!

Secondly be able to combine text from across multiple subtitle lines. An example should help explain this.

14:01.00,0:14:01.49,Hello
14:01.50,0:14:02.00,Hello/NWhat?
14:02.01,0:14:03.00,What?
Change that to
14:01.00,0:14:02.00,Hello
14:01.50,0:14:03.00,What?

**Comment by niksedk** [comment]
SE can show preview with position on video preview - when using "mpv" as video player
