### ISSUE TITLE
Dragging-and-dropping unknown file type causes problems

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2306]
Hey.  3.5.2 build 46. I believe this is something that was introduced in one of the more recent builds, I don't remember it happening before.
If you drag-and-drop a file into the window that SE doesn't know how to open (for instance, a plain TXT file), the normal error will appear ("unknown subtitle file"). However, after you click okay, two things happen: The file that was dropped into SE will become "locked", i.e. to Windows it will appear as though SE is doing something with it:
![se lock1](https://cloud.githubusercontent.com/assets/19672444/24248800/86804b40-0fd9-11e7-82ac-05ccd4fc0c1f.png)
And, if after this you try typing in the text box, SE will give this error:
![se lock2](https://cloud.githubusercontent.com/assets/19672444/24248832/afe3a022-0fd9-11e7-8375-0b0fc03404fc.png)

**Comment by darnn** [comment]
Thank you!

**Comment by niksedk** [comment]
Thank you for finding this :)
