### ISSUE TITLE
SE crashes when loading video

### ISSUE THREAD

**Issue by citizenfaguo** [SubtitleEdit/subtitleedit#2307]
It began 2 or 3 days ago: whenever I want to load a video in the interface (translation mode), the application crashes.

I tried to reinstall it (3.5.2 3588ccc) but it didn't change.
OS is Win 10 v.14393.953.
Any solution?
Thank you.

**Comment by gself4350** [comment]
I'm getting the same error.  I even installed back level VLC (2.2.0) and SubtitleEdit (3.4.13) but the problem continues.  Seems to fail mainly with MP4 videos.  AVI seem to be ok.    Directly launching VLC plays the MP4 video without problem.  Have set the Video Player to all values.... including VLC.   If I hide video... no failure.  Click "Show Video" crashes immediately.

**Comment by ivandrofly** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/2305
https://github.com/SubtitleEdit/subtitleedit/issues/2292

**Comment by ovialex23** [comment]
Same to me : SE ver 3.4.10 & Win 10 pro (kit)
and also I receive this message:
![01](https://cloud.githubusercontent.com/assets/26647040/24287109/e8232f5a-1080-11e7-8392-1de538392cb2.jpg)

**Comment by gself4350** [comment]
Uninstalling KB4013429 fixed my MP4 problem.  Thanks...

**Comment by niksedk** [comment]
@gself4350: No need to uninstall KB4013429 - just install Windows update KB4015438 too: https://support.microsoft.com/en-us/help/4015438/windows-10-update-kb4015438

**Comment by gself4350** [comment]
Reinstalled KB4013429  and installed KB4015438  resolved the problem.  VLC 2.2.4 and SubtitleEdit 3.4.13 --- all is well.  thanks

**Comment by citizenfaguo** [comment]
Thank you, ivandrofly and niksedk.
Installing KB4015438 fixed my problem.

And niksedk, kudos for your wonderful software.
