### ISSUE TITLE
For some languages are not visible OCR fix lists in the menu Word lists.

### ISSUE THREAD

**Issue by Elheym** [SubtitleEdit/subtitleedit#2309]
When adding new languages noticed that some of them are not displayed. Such as: Icelandic, Lithuanian, Serbian and Turkish.
![anigif](https://cloud.githubusercontent.com/assets/14152676/24322507/83c8aa3e-1176-11e7-9370-116412e0a7cb.gif)

By the way, is it possible to change the current display format to a little more clear... for example, "the international name (native name)"? I believe that "Finnish (Suomi)" would be much more recognizable than just "Suomi (Suomi)". Or "Estonian (Eesti)/Estonian (Eesti keel)" than the same Eesti (Eesti)... And similar examples.

**Comment by diomed** [comment]
I'm not sure why you'd need to worry about this since selection is
probably made for people from that countries, who clearly know what to look for.

for example my country's name is Croatia, but I'll rather look for hr [hrvatski],
since that's the original name of language.

**Comment by Elheym** [comment]
May be because I am interested in working not only with native but also with other languages. Maybe it'll be someone useful for whom these languages are not native. We should not exclude this possibility.

**Comment by Elheym** [comment]
It's time to close this topic. Since after the release of 3.5.2.175 (perhaps even earlier) the issue was resolved. Now finally everything works: all the above word lists are displayed. 
Thanks a lot to @ivandrofly for working on the code. Thanks a lot to @niksedk for accepting the changes. Cheers.
