### ISSUE TITLE
v3.5.2 is crashing on launch whenever I try to load a video

### ISSUE THREAD

**Issue by zprewitt** [SubtitleEdit/subtitleedit#2312]
I'm running the latest version of Windows 10 and just upgraded to SE v3.5.1.

**Comment by niksedk** [comment]
Run a Windows Update...

See https://github.com/SubtitleEdit/subtitleedit/issues/2292 for more info

**Comment by zprewitt** [comment]
Sorry, just checked the closed issues and found this had already been reported.

**Comment by niksedk** [comment]
np, I let this stay open for a few more days - so other ppl with the same problem easier can find the solution :)

**Comment by age401** [comment]
Actually, a few days ago, you pointed me to the previous thread and by uninstalling the pertinent Windows update the problem was fixed. But now the problem is back, and the update is still uninstalled. There are a couple others but some don't allow manual uninstall. Any ideas? (Windows 10)

**Comment by Treviso** [comment]
I have the same problem. Importing a video always crashes the program when I reach 100% when it's a text based file or when I finish the OCR process on an image based subtitle. Seperating the subtitle from the video and importing it separately works.
