### ISSUE TITLE
Reverse RTL start/end

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2317]
To use my previous example, with this three-line subtitle:

> -I have a big head.
> ~So do I?
> +I do too!

The expected result when you use "reverse RTL start/end" would be:

> .I have a big head-
> ?So do I~
> !I do too+

The actual result is:
> .I have a big head-
> ?~So do I
> !+I do too

![se bh-eng-reverse rtl](https://cloud.githubusercontent.com/assets/19672444/24331062/4b4b738e-1235-11e7-8446-836a09787f3d.gif)

**Comment by niksedk** [comment]
Thx for the nice explanation :)

How does latest beta work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip ?

**Comment by darnn** [comment]
Looks good over here! Thanks! I haven't tested it out with other combinations of non-text characters, but I assume this should apply all over.

**Comment by darnn** [comment]
So, like, feel free to close this if you were only waiting to see how it looks on my end.

**Comment by niksedk** [comment]
thx for verifying :)
