### ISSUE TITLE
traineddata not detected on Linux

### ISSUE THREAD

**Issue by mooop12** [SubtitleEdit/subtitleedit#2318]
I installed Tesseract and data using my distros packaging manager, and SE detects Tesseract fine, but it doesn't detect the traineddata I have installed, nor does it detect the traineddata downloaded inside SE, the menu is just empty. When I click "Open dictionaries folder" the `eng.traineddata` file is right there in the `/usr/share/tessdata` directory. Am I doing something wrong?

**Comment by niksedk** [comment]
SE searches some different folders... can you see if this is wrong:
https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/Configuration.cs#L155

**Comment by mooop12** [comment]
The last one is right, `/usr/share/tessdata`, that's where my package manager installed the traineddata file, and that's the folder that SE opened when I clicked the "open dictionaries folder". The first 2 directories listed in the file you linked don't exist, on my system at least.

**Comment by niksedk** [comment]
OK, then it should work... what Linux distro are you using?
And are you using SE 3.5.2?

**Comment by mooop12** [comment]
Arch Linux, SE 3.5.2

I believe I found the issue. [This](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Forms/Ocr/VobSubOcr.cs#L6897) line sets `tessdata` directory to `Path.Combine(Configuration.TesseractDirectory, "tessdata")`, when it should set it to `Configuration.TesseractDataDirectory`.

Also, [this](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/Configuration.cs#L164) line should be `return Path.Combine(TesseractDirectory, "tessdata")`, no?

**Comment by niksedk** [comment]
Nice :)
I've added the changes to latest src + updated the beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

**Comment by mooop12** [comment]
Thanks! Works like a charm :)

**Comment by niksedk** [comment]
Well, you found the solution, so thank you too :)
(all issues should be like this ;)
