### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SpasV** [SubtitleEdit/subtitleedit#2319]
[SE application error.pdf](https://github.com/SubtitleEdit/subtitleedit/files/882495/SE.application.error.pdf)

**Comment by ivandrofly** [comment]
An application error occurred in Subtitle Edit.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with
the following information:
Error Message:
Object reference not set to an instance of an object.
Stack Trace:
at Nikse.SubtitleEdit.Logic.Ocr.OcrFixEngine.SpellCheckOcrText(String
line. Bitmap bitmap. String word, List'1 suggestions)
at
Nikse.SubtitleEdit.Logic.Ocr.OcrFixEngine.FixUnknownWordsViaGuessOr
Prompt(lnt32& wordsNotFound, String line, Int32 index, Bitmap bitmap,
Boolean autoFix, Boolean promptForFixingErrors, Boolean log,
AutoGuessLevel autoGuess)
at Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.OcrViaTesseract(Bitmap
bitmap, Int32 index)
at Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.MainLoop(lnt32 max, Int32
i)
at Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.mainOcrTimer_Tick(Object
sender, EventArgs e)
at System.Windows.Forms.Timer.OnTick(EventArgs e)
at
System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message
& m)
at System.Windows.Forms.NativeWindow.Callback(lntPtr hWnd, Int32
msg, IntPtr wparam, IntPtr Iparam)

**Comment by niksedk** [comment]
Has been fix in bcf566c96197298681350d5f7f64708c2f7bcce5
Will be fixed in next update - and should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
