### ISSUE TITLE
OCR via IC suggestion: Separate space recognition setting for italics/non-italics

### ISSUE THREAD

**Issue by kdj1** [SubtitleEdit/subtitleedit#232]
Hi!
I'm experimenting with OCR via Image Compare, partly due to some issues with tesseract, mentioned in #223.

IC actually works a lot better than I expected, but I've noticed, it's usually not possible to determine a single setting for "No of pixels is space" which is optimal for both italics and non-italics - might depend on the actual subs, of course. For example: With the DVB-subs I'm working on, '6 pixels = space' is perfect for non-italics, while a lower setting of, say, 3 or 4 is much better suited for italics.

So, since the engine actually does a fine job of recognizing italized text, I would suggest implementing two separate parameters for 'No of pixels is space' - one for italics and another for non-italics.

Would that be possible?

**Comment by niksedk** [comment]
Some auto improvement regarding exists in latest version.
