### ISSUE TITLE
Bluray Export with limited margins

### ISSUE THREAD

**Issue by gorgorias** [SubtitleEdit/subtitleedit#2320]
Hi,

first of all, you made a really good job with this program, it is awesome.

Now, when I run the "File -> Export -> Bluray sup..." dialog, the "Bottom margin" and "Left/right margin" is somehow confusing. First of all I would expect a spinbox instead of a combobox. The second things is, that these comboboxes are limited to 999, always (!). When I have a video resolution of 352 x 240 the subtitle can exceed the video bounds. When I have 4K the max value is too little. I would expect a dynamic behavior depending on the video size.

![image](https://cloud.githubusercontent.com/assets/26811393/24540057/c99d731c-15f1-11e7-9d46-0072f22bd61d.png)

regards,
Oliver

**Comment by aaaxx** [comment]
Yeah, those should really use percentages so that they're resolution independent.

**Comment by niksedk** [comment]
@gorgorias: Do you agree that using percentage is better?

**Comment by gorgorias** [comment]
I think, percentage is a good way.

**Comment by niksedk** [comment]
I've tried to change margins to use percentage in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

Default value is 5 percent... let me know how it works.

**Comment by gorgorias** [comment]
That looks good. Thanks.
I'll do some more tests later and I'll tell you if something's not working.
