### ISSUE TITLE
Setting up Visual Studio environment to build “subtitleedit” application.

### ISSUE THREAD

**Issue by kdivband** [SubtitleEdit/subtitleedit#2326]
I am looking for an instruction of how to setup Visual Studio 14 environment to build “subtitleedit ” application.

**Comment by niksedk** [comment]
Not really sure... have you installed git for windows?

**Comment by kdivband** [comment]
I don't have git for windows installed on GFE, do I need to install git for windows in order to build "subtitleedit"?

**Comment by niksedk** [comment]
You could try...

**Comment by kdivband** [comment]
Thanks, will try.

**Comment by niksedk** [comment]
Does it work for you now?
