### ISSUE TITLE
Wrong conversion from frames into milliseconds

### ISSUE THREAD

**Issue by Georg-J** [SubtitleEdit/subtitleedit#2329]
Version 3.5.2: When I open the XML/ttml file found at http://api-tvthek.orf.at/uploads/media/subtitles/0008/85/3093fc141c2fc9dfb04610c33431ae0da43b8e41.xml and save it as srt then `begin="00:30:00:00" end="00:30:01:23"` results in `00:30:00,000 --> 00:30:01,023`, i. e. the duration 1 23/25 seconds = 1.920 seconds changes to 1.023 seconds.

**Comment by niksedk** [comment]
thx for the info :)

Will be fixed in next update. Was due to the last line with empty time codes: `<p begin="" end="" />`
