### ISSUE TITLE
Issue with fixing uppercase 'i' in lowercase words, in tool "Fix Common Errors"

### ISSUE THREAD

**Issue by Engztrom** [SubtitleEdit/subtitleedit#2331]
The function "Fix uppercase 'i' in lowercase word" (in tool "Fix common errors") fails at line 53, 273, 391 and 459, for the English subtitle that can be found here: 
http://www.addic7ed.com/serie/Babylon_5/1/22/Crysalis

At line 53, the capital 'I' in the word "Io" turns into common 'l' instead of common 'i'.
(But in this context "Io" is the name of a moon, so it should actually be left unaffected).

At line 459, where capital 'I' (in the _word_ "I") turns into capital 'L', instead of being left unaffected.

(Lines 274 and 391 fails on the same word as line 53...)

I'm running SubtitleEdit version 3.5.2.

**Comment by ivandrofly** [comment]
the link you provided is broke http://www.addic7ed.com/serie/Babylon_5/1/22/Crysalis

**Comment by Engztrom** [comment]
Weird! Because it is a correct URL, and it works if you cut-and-paste it into the browser's command line.
Then you can select and download the English subtitle from there.

**Comment by ivandrofly** [comment]
working now... prev was being redirected to github...

**Comment by niksedk** [comment]
@Engztrom: You'll need to add "Io" to your names list - Options -> Settings -> Word lists - names/ignore list.

I really like the series when I saw the first time (not sure I could watch it again though).
