### ISSUE TITLE
can't download french dictionnary

### ISSUE THREAD

**Issue by simca27** [SubtitleEdit/subtitleedit#2339]
Everything's on the screen

could you help me pls ? :)

![8842442ee35e5969857a050fa4c5a03f](https://cloud.githubusercontent.com/assets/27349727/24956221/f0ea5d24-1f86-11e7-8a37-9806cab1753d.png)

**Comment by Elheym** [comment]
Perhaps here you will find the solution:
http://libreoffice-na.us/English-4.3-installs/dictionary.html#f

**Comment by niksedk** [comment]
What version of SE are you running? Be sure it's the latest, because sometimes the dictionary download links changes.

**Comment by ivandrofly** [comment]
Why not downloading all the dictionaries and host them here in Github (https://github.com/SubtitleEdit/support-files) in order to avoid this problem with link.

So before every release we can update the dictionary and test them too. /cc @niksedk

**Comment by niksedk** [comment]
@ivandrofly: not a bad idea :)
