### ISSUE TITLE
Redirect Output in Windows Command line

### ISSUE THREAD

**Issue by SonSonGoku** [SubtitleEdit/subtitleedit#2340]
I use Subtitle Edit 3.5.2, under Windows 7 Pro.

When I convert subs via OCR, I want to redirect the command line output to file. But Subtitle Edit always write the output to console window.

This is my first batch file named "start.cmd":
call "D:\SubtitleEdit.cmd" > "D:\SubtitleEdit.wri" 2>&1

This is my second batch file named "SubtitleEdit.cmd":
"D:\SubtitleEdit.exe" /convert "D:\subtitle-en.sup" srt /outputfolder:"D:\" /fixcommonerrors

But Subtitle Edit always write the output to console window. Can you fix it? Or can you add a logging option for command line?

Maybe: "D:\SubtitleEdit.exe" /convert "D:\subtitle-en.sup" srt /outputfolder:"D:\" /log "D:\SubtitleEdit.log"

**Comment by niksedk** [comment]
thx for the info :)
I've tried to use the std out stream in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
Is that working for you?

**Comment by SonSonGoku** [comment]
Yes. It works great. Thx. I hope, it will find its way in the next release. :) :+1:
