### ISSUE TITLE
Can't add new subtitles when translating a Timed Text 1.0 .xml file

### ISSUE THREAD

**Issue by nathaniel1977** [SubtitleEdit/subtitleedit#2345]
Hi,
When working on a Timed Text 1.0 .xml file, the source structure looks like this:

begin="00:01:35:10" xml:id="p11" end="00:01:37:05" region="region.before.center" style="style.default">
        <span tts:fontStyle="italic">Text text text text text text,</span>
     

I receive templates in .dfxp format, which I then change to .xml to see the above structure.

Unfortunately, when I need to add an extra subtitle to either the original template or the translation file (generated by "Make new empty translation from the file"), the new subtitles lack lots of information from the xml file. To make matters worse, I've noticed that they even don't appear in the Source View. 

Then, after saving such a file (with several new subtitles) and re-opening it, the new subtitles appear on top of other ones, also without lots of the necessary info:

xml:id="p0" end="00:15:49:01" begin="00:15:47:04">Text text text text text text,

Is it possible to make it work? Or perhaps there already is a way to add the subtitles with the info I need?

**Comment by niksedk** [comment]
How does latest beta work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

You can right click in the list view - and set some Timed Text properties 

If this does still not work, perhaps you could link/email the subtitle?
