### ISSUE TITLE
Feature request: different font for subtitle list and the edited boxes

### ISSUE THREAD

**Issue by nathaniel1977** [SubtitleEdit/subtitleedit#2346]
Hi, 
While translating a specific subtitle, it's useful to use a large font to see the original clearly and make sure that you are not making any mistakes in the translation.
However in the subtitle list such large fonts make it impossible to see the whole content of source and target subtitles.
Would it be possible to make it independent of each other? That is, different font sizes (or perhaps even fonts?) for the box you are now editing and different ones for the list?
Thanks

**Comment by niksedk** [comment]
Included in recent version of SE (options -> settngs -> fonts)
