### ISSUE TITLE
Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by george852** [SubtitleEdit/subtitleedit#2348]
Hi,

I have .ts file which is ~1.5Gb and when I try to extract subtitles from it, SubtitleEdit crash with following error:
![subtitleedit-3 5 2 - error while opening ts file](https://cloud.githubusercontent.com/assets/27940609/25322030/ad91ea3e-28e5-11e7-8143-bf573dc136c9.png)

Please help.

**Comment by niksedk** [comment]
Could you possibly send me a link to the file (per email if's not public)?

**Comment by george852** [comment]
Hi,

Plz try this:
https://drive.google.com/file/d/0Bx5D87XlSnXoUzZBRGxGRDRHODg/view?usp=sharing

Thanks.
2017年4月27日 下午11:16 於 "Nikolaj Olsson" <notifications@github.com> 寫道：

Could you possibly send me a link to the file (per email if's not public)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SubtitleEdit/subtitleedit/issues/2348#issuecomment-297745493>,
or mute the thread

**Comment by niksedk** [comment]
Thx for the file :)
SE could not recognize this file as a TS file, but that should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

**Comment by george852** [comment]
Thanks for the beta, it works now!
BTW, seems OCR via Tesseract and Dictionary are not working properly with Tranditional Chinese. Any recommedations? Thanks again.

**Comment by niksedk** [comment]
Could you explain about Tesseract Dictionary with Tranditional Chinese? Works fine here as far as I can tell...

**Comment by george852** [comment]
I finally figured out Tesseract version 3.05 and 4.0 work, though the
accuracy is not very good, probably ~70%. Besides, the dictionary should be
downloaded during Tesseract installation (Windows). If I download inside SE
shortcut, the dictionary is different in sizes and the accuracy will be
even more worse ....
2017年5月2日 下午10:36 於 "Nikolaj Olsson" <notifications@github.com> 寫道：

Could you explain about Tesseract Dictionary with Tranditional Chinese?
Works fine here as far as I can tell...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SubtitleEdit/subtitleedit/issues/2348#issuecomment-298654413>,
or mute the thread
