### ISSUE TITLE
Difficulty importing large video files

### ISSUE THREAD

**Issue by ecodonohoe** [SubtitleEdit/subtitleedit#2351]
I work with large MXF video files, upwards on 50GB for some. When I try to import these the application crashes. With some smaller sized videos, when I force shut the application and reopen, the video then appears and works normally. Is this a common issue and is there likely to be support for large files soon?

**Comment by niksedk** [comment]
Do you import subtitles from these MXF files?
I've made a fix (7174c93826158e26d3ee8f4ee8b4c4f89ad1ed55) that perhaps will help. - perhaps you could try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

**Comment by ecodonohoe** [comment]
So opening an MXF file via 'Open' ends in the application crashing. When I drag and drop the file I get the following error screen:

![subediterror](https://cloud.githubusercontent.com/assets/15345230/25490230/15853d5a-2b64-11e7-96b4-b23ff07db60d.jpg)

The MXF doesn't have embedded subtitles so I add the .STL file separately.

**Comment by niksedk** [comment]
That's because SE cannot show the video (not video decoder for MXF found).

Try to switch to "mpv" media player - see options -> settings -> video player

Alternately you could download lav filters: https://github.com/Nevcairiel/LAVFilters/releases/download/0.69/LAVFilters-0.69-Installer.exe

**Comment by ecodonohoe** [comment]
Ahhh, perfect! That got it working. Thank you.

**Comment by niksedk** [comment]
You're welcome :)
