### ISSUE TITLE
bugs?

### ISSUE THREAD

**Issue by Miasubs** [SubtitleEdit/subtitleedit#2363]
Hi,

With SE 3.5.2 portable on Win7 64 bit I just click to the text box, but the cursor does not stay in there, it is very annoying clicking there all the time and not to have the ability to modify the text. About the 3rd time is ok, but who can translate like this, clicking 3 times all the time? Anyone has the same issue? Or I am doing something wrong?

Thanks,
Mia

**Comment by niksedk** [comment]
I cannot re-create this issue... can anybody else?
Do you do anything after clicking in the text box? Perhaps you could explain your exact steps?

**Comment by Miasubs** [comment]
Hello,

Thanks for your reply. The problem started with downloading the 3.5.2 portable version. I just simply open a subtitle to translate, add a video file, generate the wave form, and start the video to hear the first sentence to translate. I stop the video, click into the textbox to modify the written line. And the cursor does not stay in the textbox, the list view stays inactive. At the second-third click it is OK. Does this description gets you closer?

Mia

**Comment by Miasubs** [comment]
*sorry, the list view stay active, not inactive

**Comment by niksedk** [comment]
Hm, check Options -> Settings -> Waveform/spectrogram - Set focus on mouse enter/also set list view focus on mouse enter in list view.
Was that enabled?

**Comment by Miasubs** [comment]
Yes, both are enabled.
