### ISSUE TITLE
SE Crashes and I can't install the KB fix

### ISSUE THREAD

**Issue by MrGibbage** [SubtitleEdit/subtitleedit#2364]
I have the same crash that many others are having, related to the Windows Update, as discussed here:
https://github.com/SubtitleEdit/subtitleedit/issues/2292

Many of them have been able to fix the crash by installing this KB:
https://support.microsoft.com/en-us/help/4015438/windows-10-update-kb4015438

However, I have intel architecture (i7), I can't install this (it applies to AMD64). I tried installing it and it just gave an error stating it didn't apply to my computer. Are there any other workarounds? I tried using VLC but that didn't work either.

**Comment by niksedk** [comment]
Just run a windows update :)

If you're still having troubles, then please post a screenshot.
