### ISSUE TITLE
Option to disable video player

### ISSUE THREAD

**Issue by Ede123** [SubtitleEdit/subtitleedit#2365]
It would be helpful if SubtitleEdit offered an option to disable the built-in video player.

Rationale:
I use SE exclusively for editing existing subtitles (i.e. no synchronization or similar) which makes a video preview unnecessary. Sometimes I want to import subtitles from existing video files (for example to remove HI text) but since I have not set-up a codec for the video player SubtitleEdit shows me an error message every time I do so.

A simple additional radio button on the settings "video player" tab allowing to "Disable video player" could easily solve this.

**Comment by niksedk** [comment]
Current beta has a "Video auto-load" setting... just uncheck that and hide waveform/video :)
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

**Comment by Ede123** [comment]
Perfect!

One case where the new option won't work, though:
If one drags and drops a file with embedded subtitle onto the SE window, it's still attempted to play the file.

**Comment by niksedk** [comment]
thx for the info :)
That fix will be included in next update.

**Comment by Deepcuts** [comment]
With 4.0.2 it seems the option to not load the video player is missing?
That or I lost the last 15 minutes looking for it and cannot find a way.

**Comment by rnnc** [comment]
> With 4.0.2 it seems the option to not load the video player is missing? That or I lost the last 15 minutes looking for it and cannot find a way.

i found it, you have to click the layout button, then select the last option without video or waveform
![Screenshot 2023-12-01 133218](https://github.com/SubtitleEdit/subtitleedit/assets/38816455/055bee67-8a22-4b49-9c29-9ddb71ca83ab)
