### ISSUE TITLE
Clicking UI controls only works if the window already has focus

### ISSUE THREAD

**Issue by Ede123** [SubtitleEdit/subtitleedit#2366]
Just noticed a minor issue:
When the SubtitleEdit window does not have focus (i.e. another window on the desktop is focused, but the SE window is visible) and one clicks on an UI element (i.e. the "File" menu), the SE window is activated, but the click event seems to be lost. Only after a second click the file menu is actually opened.

**Comment by Yomodo** [comment]
Confirmed, this is very annoying.

For a couple of times now I would click save and close SE, only to find out the subtitle was NOT saved.
So one has to double-check and cannot assume.

**Comment by niksedk** [comment]
Sorry, it's just how winforms works: https://github.com/dotnet/winforms/issues
