### ISSUE TITLE
When merging with empty line, "auto break" is performed unnecessarily

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2367]
Hey. 3.5.2 build 135, though this isn't a recent issue.
When merging two lines (either by selecting them both and then using the keyboard shortcut for merge or by using merge with previous/next) and one of the lines is empty, the text of the resulting subtitle has the equivalent of "auto break" performed on it, whereas it should just be the unchanged text from the non-empty subtitle:
![se merge auto br](https://cloud.githubusercontent.com/assets/19672444/25626282/b5eee398-2f67-11e7-9e6c-9e3b646b4743.gif)

I often encounter this in translator mode, where the in the source there are two short subtitles, and I've already translated the first one and I want to join them.

**Comment by niksedk** [comment]
Hm, cannot re-create this???
For me it only breaks if the first text has a line that's too long.

**Comment by darnn** [comment]
Tried with latest beta. Single line max. length is 42. When merged with an empty line, this:
> And they lived happily ever after forever.
> Amen.

Turns into this:

> And they lived happily
> ever after forever. Amen.

**Comment by darnn** [comment]
Thanks!
