### ISSUE TITLE
Crash Converting bluray .sub to .srt

### ISSUE THREAD

**Issue by maztheman** [SubtitleEdit/subtitleedit#2369]
![image](https://cloud.githubusercontent.com/assets/1463024/25646958/fcab764e-2f7a-11e7-83db-56257477bc1f.png)

**Comment by maztheman** [comment]
SubtitleEdit.exe /convert "test.sub" subrip /fps:23.976

**Comment by niksedk** [comment]
I think that has been fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
