### ISSUE TITLE
[Feature Request] Remember position window for "Multiple replace"

### ISSUE THREAD

**Issue by Elheym** [SubtitleEdit/subtitleedit#2377]
By default window is located in center. After restarting window needs to be adjusted again.
![bandicam 2017-05-07 15-25-18-500](https://cloud.githubusercontent.com/assets/14152676/25780938/f73ad0c0-3339-11e7-9adc-3e86ab7edb89.png)

It would be nice if SE memorized changes in size of window. Thank you!

**Comment by Perkolator** [comment]
Almost 3 years since this was opened. I also would like to see that the size and position of this window would be remembered.

Also for these other windows:

- Remove text for hearing impaired
- Compare subtitles

**Comment by ivandrofly** [comment]
> * Remove text for hearing impaired

I think this one is already set, right?

**Comment by Perkolator** [comment]
> > * Remove text for hearing impaired
> 
> I think this one is already set, right?

Nope. Size & position of the window is not remembered. When SE is closed and restarted, the window size & position is lost.

**Comment by Perkolator** [comment]
Additionally, forgot to add, if it's possible at all, I'd like to see that the list header (e.g. "before", "after") element sizes would be remembered too.

**Comment by Perkolator** [comment]
I had forgotten about this and requested this again in discussions..

Additional request: Remember also the "splitter" position in the Multiple replace window.

**Comment by Perkolator** [comment]
Why was this closed as "completed"? I don't see any change in the latest version 3.6.8, and the current 3.6.9 beta changelog doesn't say anything about this issue.

**Comment by Perkolator** [comment]
Why wontfix? To me it seems that there are other similar "popup" windows in SE that remember size/position/etc.
