### ISSUE TITLE
When incomplete translation subtitle is open, opening original subtitle erases a line

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2382]
So, currently, if I have an SRT file that I want to translate, I need to create the translation file myself, i.e. a file with the same number of subtitles, with the same timings, but where all the subtitles are blank. The way I've been doing this until now is: I would take the original file, e.g. "original.srt", save a copy of it as "translation.srt", delete all but the last two lines, and delete the text from those lines. This gave me a file with two empty lines with identical timings to the last two lines of original.srt. Then I would go to file->open original subtitle, open original.srt, and SE would populate translation.srt with all the remaining empty lines. If the description isn't clear, here's a demonstration with just one line, because that's all I can get to work right now:
![se creating translation subtitle - working](https://cloud.githubusercontent.com/assets/19672444/25873618/e0e89976-3517-11e7-8f18-1305ca2975ef.gif)

However, occasionally, something goes wrong, and one of the lines from the original file is erased in this process. Note how the four lines turn into three in the gif:
![se creating translation subtitle - not working](https://cloud.githubusercontent.com/assets/19672444/25873728/453392a0-3518-11e7-92c0-1dce32c9e16f.gif)

I'm attaching both my source files in case they help. 2test_or is the one with which this works properly, 1test_or is the one with which it doesn't:
[1test_or.txt](https://github.com/SubtitleEdit/subtitleedit/files/988086/1test_or.txt)
[2test_or.txt](https://github.com/SubtitleEdit/subtitleedit/files/988088/2test_or.txt)

**Comment by OmrSi** [comment]
@darnn Is this still happening in the latest version?

**Comment by darnn** [comment]
Yes. If you take the file 1test_or.txt (rename it to srt) and do what I did in the second gif in my post, the result is the same in 3.5.14 NEXT beta 320.
