### ISSUE TITLE
[Suggestion] Use Individual Syntax Color Settings

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2383]
Basically I mean using different colors for different sytax coloring rules, which can be more flexible and convenient. A humble prototype:

![prototyp](https://cloud.githubusercontent.com/assets/494788/25930600/af281e52-3639-11e7-9a4b-449248261801.png)

**Comment by LeonCheung** [comment]
Not sure if this is a good idea, since there can possibly be some line that match multiple syntax errors, Not sure how we should display that kind of situation. Closing for now I suppose.

**Comment by aaaxx** [comment]
Additional (optional) columns would take care of it.

- gap before
- gap after
- number of lines
- line 1 length
- line 2 length

Probably no need for lengths of lines 3, 4, etc., because most subs have only two lines, and the "number of lines" column could highlight the ones with more.

**Comment by LeonCheung** [comment]
I highly agree with the "separate line length syntax" idea. Since it's crucial for two line subtitles, as well as bilingual ones, even trilingual. Maybe that's another issue to open. Just found another related request #2383
