### ISSUE TITLE
Dropbox plugins not working

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2385]
Hey,  Thanks for the Awesome Programme. 
I have a suggestion and a problem. 
The suggestion is to a a "Duplicate line" future, to add effects in ass files and translate signs. 
The problem is with Dropbox Plugins, both of them are not working .
Thanks in advance. :)

**Comment by niksedk** [comment]
Cool you like SE :)

Could you test the dropbox 1.1 version of the plugins? (plugins moved to v2 of the dropbox api)

Duplicate a line with both time codes and text?

**Comment by OmrSi** [comment]
First of all, Thank You so much for responding, you're the best of the best kind of programmers. :) 

Just Tested, Works like a charm. 😃


As for the "duplicate" you can find it in AegiSub
Just duplicate a line with the time codes, to add an explanation in a certain sentence, when I try to copy a line and paste it, it automatically changes the time, if there is a way to duplicate the time or make it so it doesn't change when I copy, it would be great.

**Comment by OmrSi** [comment]
The main reason for duplicating a line time is if you want to have two different sentence in the same time. 😃

**Comment by OmrSi** [comment]
And, I know this is asking too much, but if you added it could you add it to the shortcuts list too? ♥
