### ISSUE TITLE
[Set time] doesn't add more time

### ISSUE THREAD

**Issue by ghost** [SubtitleEdit/subtitleedit#2392]
When you set start time, it is expected that adds more 200ms before.
When you set end time, it is expected that adds more 300ms after.
It's normal in subtitles in Brazil. There's no tool or option to do it and it's very important. Thank you.

**Comment by OmrSi** [comment]
@niksedk I think this is closed, too.
Set start or end are supoosed to do just that, set, not add time after setting.
