### ISSUE TITLE
Big step of pointer in waveform

### ISSUE THREAD

**Issue by farmaister** [SubtitleEdit/subtitleedit#2399]
Hello,
is somehow possible, to make option for smooth pointer in waveform? I find that 3 steps per second as an issue because it is really imprecise and i cant see where subtitle exactly starts. 
Is this thing possible? Or do you think, that it's useless? Thank you :)

**Comment by niksedk** [comment]
What video player do you use?
VLC, unfortunately, does not have precise seeking. Try mpv or directshow with lav-filters.
