### ISSUE TITLE
3.5.3 Bug! Reverse RTL Start\End

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2400]
Guys, thi is a big bug.
it's reversing the question marks "?"
it should NOT be doing that!

**Comment by farmaister** [comment]
Nothing like this is happening to me in version 3.5.3...

**Comment by OmrSi** [comment]
I translate to Arabic
It used to only reverse: " and ! And comma and other punctuation marks,  now when I use it it reverses "؟" too. 
It's a question mark for RTL languages.

**Comment by OmrSi** [comment]
Double checked and tried Beta
Same problem

**Comment by niksedk** [comment]
Fixed (hopefully) - see #2404
