### ISSUE TITLE
List view right-click menu -> Copy as text to clipboard

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2402]
3.5.3 build 2. The "Copy as text to clipboard" function seems to do exactly the same thing that regular copying does, rather than actually copying just the text.

**Comment by ivandrofly** [comment]
yeah, I think that is the expected result... Maybe tweak things a little bit to allow copy by column.

**Comment by LeonCheung** [comment]
@darnn Since we also got the "Copy text ONLY to clipboard (selected lines)" shortcut, both can be achieved.  So I guess you can close this issue for good. :)

**Comment by darnn** [comment]
True.
