### ISSUE TITLE
Reverse Problem, Back to 3.5.2

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2404]
Reversing RTL Start\End is now reversing the RTL question mark and some Arabic letters
it's reversing "؟" and "ً " and "ٌ " and "ٍ " and others
when i write: "مرحباً" it becomes "ً مرحبا" and so on...
hope you find a solution soon...
@niksedk 
@ivandrofly

**Comment by niksedk** [comment]
Latest beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Tried it, working perfectly. :) 
Thank You. 😄
---------------------------
Unrelated: 
Is there a way to double a line to add an explanation on another part of the screen? 
And will you update Dropbox plugins sometime? 
Thanks again for the Awesome work. 😃
