### ISSUE TITLE
waveform bug

### ISSUE THREAD

**Issue by masihm4** [SubtitleEdit/subtitleedit#2406]
![screenshot 652](https://cloud.githubusercontent.com/assets/27754401/26308186/683a4cf4-3f0d-11e7-9426-d5c323b7f3c5.png)
Hi. I keep getting this error when I try to load an audio in waveform. the waveform will become just a blank white screen.
🐛

**Comment by masihm4** [comment]
i changed the line

m'aidez.
(persian)

to just:

m'aidez.

and it's fixed. odd.

**Comment by niksedk** [comment]
Yes, seems odd. What OS and can you re-create the error?

**Comment by masihm4** [comment]
![screenshot 653](https://cloud.githubusercontent.com/assets/27754401/26322805/c8068dd0-3f41-11e7-856f-4f3a995f7492.png)
No, I can't recreate it. i tried that specific line but this time everything was fine.

**Comment by OmrSi** [comment]
@niksedk Should be closed.

**Comment by niksedk** [comment]
Closed as it's not re-creatable
