### ISSUE TITLE
Spellchecker problem with Arabic language

### ISSUE THREAD

**Issue by Lejohub** [SubtitleEdit/subtitleedit#2407]
The spellchecker doesn't recognize those punctuation marks "؛ ، ؟" as delimiters, which gives a false reports.

**Comment by OmrSi** [comment]
I conquer. 
Every time I want to spell check I have to repalce them all…

**Comment by niksedk** [comment]
Thx for the info :)
How does latest beta work?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Yep, working perfectly. ♥😃
