### ISSUE TITLE
No sound for DTS source

### ISSUE THREAD

**Issue by Stunherald** [SubtitleEdit/subtitleedit#2409]
Hello,

i am having an issue that there is no sound at all if the source is DTS. Playing the video via SubtitleEdit is completely silent which makes the correction of timing nearly impossible.

Media sources with AAC sound have no issue and working properly.

Note that i don't have any issues at all with other players (MPC, ZoomPlayer, VLC)

I am running last version 3.5.3

Or did i missed some configuration?

Thank you 

Alex

**Comment by niksedk** [comment]
SE does not decode audio/video by itself but uses media libraries - DirectShow, mpv, vlc or mpc-hc.

An easy fix should be going to Options -> Settings -> Video player - and download mpv from there.

Alternately you could try to install lav filters: https://github.com/Nevcairiel/LAVFilters/releases/download/0.69/LAVFilters-0.69-Installer.exe
