### ISSUE TITLE
XML subtitles don't work anymore

### ISSUE THREAD

**Issue by PannenkoekenNL** [SubtitleEdit/subtitleedit#2417]
While they were working fine in one of the previous versions, they now show up as empty:
https://i.imgur.com/II136OP.jpg

Examples of two files xml files:
https://mega.nz/#!Xk9BSSpC!sSeFRUogrklGXMq9LHTGYxPKVscacHoeE9zsmHVIdW8
https://mega.nz/#!G9FVhI5I!Wtyd7bd1eSzsFgseQ_IbDsyXesQuUyL8owf-vasUlec

**Comment by niksedk** [comment]
thx for the info :)

Should be fixed via this commit: 9e539abd10090fabaa0a7bcc36092ed27a628144
Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
