### ISSUE TITLE
WebVTT format not supported in IE 11

### ISSUE THREAD

**Issue by bodrick** [SubtitleEdit/subtitleedit#2425]
The currently generated output for WebVTT fails to load properly in IE 11.  The issue is caused by a missing space in the timecode section.
Example of output of SubtitleEdit - 
```
WEBVTT

00:00:08.838--> 00:00:11.037
Welcome to your test subtitles
```

Example of output that IE 11 requires -

```
WEBVTT

00:00:08.838 --> 00:00:11.037
Welcome to your test subtitles
```

The extra space before --> is required by IE11 to work properly, with the extra space the subtitles now work fine on all the major browsers.

**Comment by niksedk** [comment]
Thanks for the info :)
Should be fixed in latest beta (portable version): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
