### ISSUE TITLE
Single-frame seeking not working anymore when using MPV

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#2432]
Hi!

I was still on SE 3.4.13, so I thought I'd update to the latest version (3.5.3). There are some nice new features, but I encountered an issue:

I use the "One frame forward" and "One frame backward" a lot for precise syncing (by default not associated with a shortcut) and I use MPV because it's accurate and fast. However, with the latest version, when using these shortcuts, the video moves, but the timecode in SE doesn't get updated. The white bar in the waveform doesn't move and pressing F11 and F12 has no effect anymore.

This is really breaking for me, so I switched back to 3.4.13 for the time being. (DirectShow doesn't work for me and VLC is too slow.)

I tried looking in the source code, but I couldn't find where the shortcuts are handled.

Thanks!

**Comment by niksedk** [comment]
Thx for the info :)
Could you check latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by Flitskikker** [comment]
Thanks, it's working again now! :)
