### ISSUE TITLE
How to batch convert multiple lines to one line?

### ISSUE THREAD

**Issue by pendave** [SubtitleEdit/subtitleedit#2433]
To replace `<br />` to a space is not working, neither to replace `\N`.

What can I do?

**Comment by darnn** [comment]
Select the lines you want in list view and click the "unbreak" button by the textbox.

**Comment by pendave** [comment]
I know hand to handle with one opened srt file but what I need now is to batch a folder of srt files.

Only to use Python by myself ?

**Comment by darnn** [comment]
Ah, I see. Have you tried \n? \N doesn't work for me, but \n does.

**Comment by pendave** [comment]
Where do you use it? I tried `\n` but not works.
![i8e rosfr no8337 qmtw 5](https://user-images.githubusercontent.com/1331881/26927883-4998b5ac-4c86-11e7-87a8-c8639c16bc5e.png)
![i8e rosfr no8337 qmtw 5](https://user-images.githubusercontent.com/1331881/26927915-70118a6a-4c86-11e7-9595-5c594a17d67e.png)

**Comment by pendave** [comment]
Where do you use it? I tried `\n` but not works.
![i8e rosfr no8337 qmtw 5](https://user-images.githubusercontent.com/1331881/26928671-8f4a80b4-4c89-11e7-8279-840395efd72f.png)
![obsudd ot6odt5v7 wev w0](https://user-images.githubusercontent.com/1331881/26928694-9d77cb60-4c89-11e7-9dae-4583752c003d.png)

**Comment by LeonCheung** [comment]
\n 是正则表达式，勾选 regular expression, 而不是 Normal

**Comment by pendave** [comment]
选了 
regular expression
无用啊！No use!

换成了 `\r\n`  也无用。

**Comment by LeonCheung** [comment]
亲测。除非理解错了你的意思。

**Comment by pendave** [comment]
@LeonCheung 麻烦你把操作的截图发上来看下，难道不是在 Subtitle Edit 里操作的？
截图的话 从本地拖进这个留言框里就可以上传

**Comment by LeonCheung** [comment]
FYI
![demo](https://user-images.githubusercontent.com/494788/26936372-1bdde14e-4ca1-11e7-9b72-65bb5e3e1f64.gif)

**Comment by pendave** [comment]
Cool thx!

是不是因为我srt 字幕的路径里有中文？

**Comment by LeonCheung** [comment]
并没有关系。

**Comment by OmrSi** [comment]
@niksedk This is also closed.
