### ISSUE TITLE
Could you add Google.cn as an extra translating module for guys in China needs PROXY to visit Google.com

### ISSUE THREAD

**Issue by pendave** [SubtitleEdit/subtitleedit#2435]
Hi, thanks for your work on the Google translation module already there.

But for native Chinese they have to set Proxy to use it as Google original services are all forbidden for many years by Chinese Gov.

This year the Google translation service is deblocked and actually we can visit https://translate.google.cn/m?q= directly.

Please check my requirement in details as well in https://github.com/SubtitleEdit/subtitleedit/issues/1915

**Comment by niksedk** [comment]
Could you check latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
Change google url via Options -> Settings - Tools

**Comment by pendave** [comment]
Thanks a lot, it works :P
