### ISSUE TITLE
Arabic auto detection

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2441]
In case you forgot 

private static readonly string[] AutoDetectWordsArabic = { "من", "هل", "لا", "في", "لقد", "ما", "ماذا", "يا", "هذا", "إلى", "على", "أنا", "أنت", "حسناً", "أيها", "كان" };

**Comment by niksedk** [comment]
Hm, I've tried like 10 different Arabic subs from subscene + yifysubtitles - and somehow the old version works but not the new? 
(I might do something wrong as I've auto-detected ANSI encoding - when will ppl learn to use UTF-8!?)

It's fine to add more words to the list...

**Comment by OmrSi** [comment]
I don't know why they like to use ANSI, Man. 
The reason escapes me. 
Anyway, I upload my subtitles in UTF-8
It's better. 
Here is my page: https://subscene.com/u/766688
Use the tv shows subtitles, because I translate the movies with 2 other translators and they make me upload it with ANSI. 

Thanks for all your hard work. :)

**Comment by OmrSi** [comment]
and all the translators upload their subtitles in
ANSI
Arabic Windows-1256
In case you would like to use other subtitles

**Comment by OmrSi** [comment]
The programme doesn't auto detect windows-1256
Arbian translators use Windows-1256 or UTF-8, nothing else. 
I'm guessing you got the words for the old version from another ANSI encoding?

**Comment by OmrSi** [comment]
Have you had the chance to work on this?

**Comment by niksedk** [comment]
@OmrSi: Yes, I probably got the words from a bad code page, so re-tried with "Windows-1256" and it works now :)

Could you add a few more words? (common words with 3 or more letters are best)

**Comment by OmrSi** [comment]
private static readonly string[] AutoDetectWordsArabic = { "من", "هل", "لا", "في", "لقد", "ما", "ماذا", "يا", "هذا", "إلى","على", "أنا", "أنت", "حسناً", "أيها", "كان", "كيف", "يكون", "هذه, "هذان", "الذي", "التي", "الذين", "هناك", "هنالك" };

**Comment by OmrSi** [comment]
I think those are more than enough. 😃

**Comment by OmrSi** [comment]
I think those are more than enough. 😃

**Comment by niksedk** [comment]
thx :)

**Comment by niksedk** [comment]
Included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
