### ISSUE TITLE
New Command Line Option /ForcedOnly

### ISSUE THREAD

**Issue by SonSonGoku** [SubtitleEdit/subtitleedit#2444]
I use Subtitle Edit 3.5.3, under Windows 7 Pro.

When I convert subs via OCR, I want to use forced subtitle only. In GUI there is the option "Show only forced subtitles", but in CLI there isn't. Can you add a new command line option, please?

Maybe: "D:\SubtitleEdit.exe" /convert "D:\subtitle-en.sup" srt /outputfolder:"D:" /forcedonly

**Comment by niksedk** [comment]
Hi SonSonGoku, how does latest beta work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip ?

**Comment by SonSonGoku** [comment]
You're great again. It works fine. Thanks.
