### ISSUE TITLE
how i can ocr japanese

### ISSUE THREAD

**Issue by jazuly** [SubtitleEdit/subtitleedit#2445]
how to ocr japanese vobsub?

**Comment by niksedk** [comment]
If you open a vobsub file with SE you will automatically enter the ocr window. Here you can try different ocr methods, e.g. "Tesseract" or "Binary image compare".
If yo choose "Tesseract" you must click on the "..." button right to the language and download "Japanese" dictionary.

**Comment by jazuly** [comment]
I try to download japanese but error, can i download it manual?

**Comment by niksedk** [comment]
Try here: https://raw.githubusercontent.com/SubtitleEdit/subtitleedit/master/src/Resources/TesseractDictionaries.xml
(Note that SE does not use latest Tesseract as it seems to be worse...)
