### ISSUE TITLE
Keyboard shortcut request: column->paste from clipboard

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2448]
Hey. So, I could really use a keyboard shortcut for column->paste from clipboard (for translation text in translator mode, for the record, though it would be useful outside of translation mode as well).
I'm translating a soap opera with an extensive "previously on" section right now, and I'm pasting dozens of clumps of subtitles from the previous episode to the current episode. I'm trying to do this with my hands on the keyboard, but in order to do that, I have to make a whole bunch of keypresses each time: That key that brings up the right-click menu, whatever it's called, down six times to get to "column", return, up twice to get to "paste from clipboard" and return again.

**Comment by niksedk** [comment]
Can you use the List view - column paste shortcut?

**Comment by darnn** [comment]
Oh, wow, I don't know how I missed it. Thanks!
