### ISSUE TITLE
Networking with a Webservice example

### ISSUE THREAD

**Issue by ergodaveh** [SubtitleEdit/subtitleedit#2450]
Thanks for providing the SubTiitleEdit

at the time of this issue "http://www.nikse.dk/SubtitleEdit/" is rendering to a Service Unavailable

Is there any project or other which contains the code for Server-Side webservices used by SubTiitleEdit

Cheers

**Comment by niksedk** [comment]
Website is up again :)

**Comment by ergodaveh** [comment]
Thanks for the reply.   Is there any project or other which contains the code for Server-Side webservices used by SubTiitleEdit?
