### ISSUE TITLE
Batch converter translates subtitle

### ISSUE THREAD

**Issue by SirEllert** [SubtitleEdit/subtitleedit#2451]
Hi.

I've tried to convert a .pac file to .srt using the batch converter, and mostly it works perfectly.

BUT... Now i've experienced this strange issue, where the output file is translated(probably just the letters, and not the exact words) into some totally different language(russian or something like that).
Please note that this is not consistent. Some .pac files converts perfectly, but i've had several issues where I thought I got the wrong original (.pac) file, but actually it might have been SubtitleEdit playing a game with me. 

I've attached screenshots of the text before conversion and another screenshot after the conversion. 
@niksedk if needed, I can forward you the subtitles 

Another note: 
I've tested and confirmed this in both the previous version and the current version of SE. 

![before_batchconvert](https://user-images.githubusercontent.com/14052609/27537890-fd5851d6-5a75-11e7-812b-e9764aae6994.png)

![after_batchconvert](https://user-images.githubusercontent.com/14052609/27537887-fabf8110-5a75-11e7-86ba-0b7c03329176.png)

**Comment by niksedk** [comment]
thx for the info :)
I just tried a few Swedish subtitles and was unable to re-create the issue, so please do email me one or more subs that can re-create this issue.

**Comment by niksedk** [comment]
Thx for the file :)
You can test latest beta here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
(language auto-detect did not work due the a "/"...)

**Comment by SirEllert** [comment]
Thanks!

By the way.
Is it possible to run the "Multiple replace" tool through command line(CMD)?

Another one: Are you Danish? Based on nikse.dk<http://nikse.dk> ;-)
In that case, there's no reason to communicate in english. :-D

Casper

Sendt fra min iPhone

Den 27. jun. 2017 kl. 16.50 skrev Nikolaj Olsson <notifications@github.com<mailto:notifications@github.com>>:


Thx for the file :)
You can test latest beta here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
(language auto-detect did not work due the a "/"...)
