### ISSUE TITLE
Can't set decimals in batch convert mode

### ISSUE THREAD

**Issue by Ninelpienel** [SubtitleEdit/subtitleedit#2454]
Hey, I can't set decimals in the batch convert mode. I want to set the border to 4.5 but it jump directly to 45. I have the newest installer version.

**Comment by niksedk** [comment]
Because it's a whole number?

**Comment by Ninelpienel** [comment]
But in .ass you can set decimal numbers.

**Comment by niksedk** [comment]
Ah, ASS format - thx for the info :)

I've tried to fix in here in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
