### ISSUE TITLE
Opening and saving a RTF translation file makes the file unreadable

### ISSUE THREAD

**Issue by mihaipopescu** [SubtitleEdit/subtitleedit#2455]
First thing I've noticed is that the file is saved with UTF-8-BOM even if the encoding was a simple UTF-8. Then, the saved file is unrecognisable when it's loaded back from disk. I think it's very simple to reproduce. Let me know otherwise.

**Comment by niksedk** [comment]
I'm not sure what you mean... I can re-open rtf files with UTF-8 BOM just fine in both SE, wordpad and word.

**Comment by mihaipopescu** [comment]
Interesting. Can you send me the sample you are using ? I'm going to do the same and maybe send you an animated gif. Thanks for quick reply.

**Comment by mihaipopescu** [comment]
In this [Archive-Test.zip](https://github.com/SubtitleEdit/subtitleedit/files/1122620/Archive-Test.zip) you will find the original rtf translation file, the translated file as it was saved by SE and one saved-as file.

I think the first issue is encoding. There is nowhere in [rtf file format](https://en.wikipedia.org/wiki/Rich_Text_Format) where I can find that rtf can be saved with any encoding, and definitely doesn't support BOM. I've removed the BOM manually from `test-saved.rtf` as without it no editor can properly open a rtf file encoded with UTF-8-BOM. I've tried with MS Word, Wordpad and even on MacOSX, they fail.

Secondly, the fonts and other text markup (like bold, italic) are not preserved. They are important as they are used in translation to encode different kinds of speech. On the other hand, I've noticed that the editor doesn't support that so this could be a feature request.

**Comment by niksedk** [comment]
thx for the info :)
How do you save as rtf in SE?

**Comment by darnn** [comment]
I just did it by opening the attached original file, modifying it and then using file->save.

**Comment by mihaipopescu** [comment]
Yes, test-save.rtf and test-saveas.rtf are files saved by SE.

**Comment by niksedk** [comment]
OK, SE now saves .rtf without BOM: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

Changes included in this commit: 7d7f387068808af385a08de6bb0285198b52ad5d
