### ISSUE TITLE
Ass Tags

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2457]
When you open an ass file
If a line has both ass tag and html/srt tags
The program is automatically converting the ass tags to srt tags

For example: 
{\fs30\fnArabic Typesetting}< font color="#ffa500">……… </font>

The program makes it: 
< font face="Arabic Typesetting" size=30 color="#ffa500" >

Shouldn't it stay ass when opening an ass?!

**Comment by OmrSi** [comment]
It should do it the other way around 
{\fnArabic Typesetting\fs30\1c&H00a5ff}

**Comment by OmrSi** [comment]
Even when opening a normal ass file with normal tags,  it converts it to srt/html tags

When I open a file with: 
{\fnX\fsY\1c&00FF00}
It automatically makes it: 
< font face="X" size=30 color="00FF00">

The ass should stay the way it is.

**Comment by niksedk** [comment]
SE support 250+ formats and I've chosen that italic etc are in html tags - all code uses this and only when writing to output format is text transformed to the target format.
Also, all formats will look alike in the editor regarding newline and italic etc.

**Comment by OmrSi** [comment]
Well, what about this? 
When I open it and see: 
< font face="Arabic Typesetting" size=30 color="#ffa500" >

If I change it to: 
< font face="Arabic Typesetting" size=32 color="#ffa500" >

When I save it,  it becomes
< font face="Arabic" size=30 color="#ffa500" >

**Comment by OmrSi** [comment]
And in text editor :
{\fs30\fnArabic\1c&H00a5ff& }
