### ISSUE TITLE
Hearing Impaired Needs to Make Text of First Sentance A Capital Letter after Remove Text action

### ISSUE THREAD

**Issue by aucforum** [SubtitleEdit/subtitleedit#2460]
In the 'Remove text for hearing impaired' window, there is a 'Remove text before a colon (':')' option.

I would like to request a sub-option that makes the first word that follows a the removed text to be a capital letter to represent the start of a sentence.

For example:

_Before removal_
**Robert: what do you think about this new car?**

_After removal, currently would do:_
**what do you think about this new car?**

_What I would like is after removal to do:_
**What do you think about this new car?**

This would help where the source subtitle was not a perfectly written sentence.

Thank you for your help!

**Comment by niksedk** [comment]
Fix included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
