### ISSUE TITLE
Change Casing on Names Only Worked Once!

### ISSUE THREAD

**Issue by aucforum** [SubtitleEdit/subtitleedit#2461]
I attempted to Change Casing on Names where is did not work after being used once ever! 

It worked once (where I selected all the text lines) and added some names, from the Tools Menu, Change Casing. However it did not work the second and subsequent times.

Can you please check and test this?

I did this navigation first:

![20170703_subtitleedit_changingcase-namesoption](https://user-images.githubusercontent.com/25918652/27795799-d1f7d720-604a-11e7-8323-d259bac9dc63.png)

Then:

![20170703_subtitleedit_changingcasenameswindows-blanklistnotextlines](https://user-images.githubusercontent.com/25918652/27795803-d523da0c-604a-11e7-8d6c-c3a11b4690d0.png)

The lines found is 0, when I actually selected all the lines. It should be scanning the whole names dictionary too, with a long list of names showing. But only one name showing?

Thank you for your help!

**Comment by niksedk** [comment]
Change Casing on Names Only will not show anything if it's already fixed :)

Try changing the subtitle to all lowercase and run "Change casing" on names only again.

**Comment by aucforum** [comment]
The 'fix' was only partially done. What if someone wants to do a 'fix' again? I already have the text in Sentence form with the start in capitals and some other words in the sentence with capital letters. I cannot see how changing the subtitle to **all** lowercase will address this underlying problem?

**Comment by niksedk** [comment]
OK, I might not have explained it well enough... "Change casing on names only" will only list names and fixes actual for current subtitle... so if you have a name like "peter" in all lowercase, the "Peter" will be a fix. After "peter" is fixed to "Peter" then "Peter" is no longer an available fix (it's already fixed).

**Comment by aucforum** [comment]
OK, after some experimentation I think I see what you mean, and what I was misunderstanding about the feature's behaviour.

When I was performing the 'Add...', I thought it might also be adding the word to the file "Dictionaries\names.xml". But it did not seem to save it anywhere.

Perhaps what I would like to request is feature/improvement that does the following:

1) Creation of a Custom Dictionaries, in which we could select any of them for inclusion, and can easily share with others and backup/restore. For example, I might have a custom dictionary of Medical Terms, and other of Technology Terms that I want to reuse and share with other users.
1.1) It would have its own sub-folder for easy backup and restoration and does not get wiped out during software updates.
2) See all the subtitle text listed in the easy to review table form of Apply, Line#, Before, After.
2.1) Be able to then review it manually, looking for words to rename with the "Add..." button.
2.2) Toggle between 'Found' and 'All' text rows. (This means an 'All' text rows view will allow me or someone else to easily proof read the whole text again.)
2.3) This preview effect is perhaps more desirable than the standard List View, although the List View's right click option could be modified as well to access this proposed feature/improvement.
3) Make it accessible as a new option in the Change casing feature or in the Multiple Replace feature.
3.1) I have looked at the Multiple Replace feature, which might be a place to look at changing instead. 
I did noticed that the 'Multiple Replace' section of the help seems to be out of date:
http://www.nikse.dk/SubtitleEdit/Help
The current version does not seem to have that import and export button depicted. I could not find where the 'Groups' was saved either when I created a new one in the program's folder. 
3.2) Perhaps a merging of these features might be a better idea? These 'Groups' could perhaps be replaced with the proposed Custom Dictionary as well.
It could also be possible to review all the text rows and add to a custom dictionary as I go.

Please let me know if I can clarify this further.
