### ISSUE TITLE
Video And Subtitle Edit

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [SubtitleEdit/subtitleedit#2463]
Hi,
I made many changes to Subtitle Edit, the most important is the ability to cut scenes from video and save a modified version of the video and a modified version of subtitle.
Download it from here:  
http://www.mediafire.com/file/jjrqrfjw6j1jzh9/Video_And_Subtitle_Edit.zip
How can I upload the source code?

**Comment by OmrSi** [comment]
@niksedk As you don't want to add video editing abilities, Closed?
