### ISSUE TITLE
Minor bug, Netflix

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2465]
Netflix Quality check, even when activated, the icon isn't showing up in the toolbar.

**Comment by niksedk** [comment]
?

**Comment by OmrSi** [comment]
In "toolbar" you can add "Netflix Qualify Check"
But when you add it, it doesn't show up.

**Comment by niksedk** [comment]
Ah, it's only for Timed Text + Netflix Timed Text formats atm...

**Comment by OmrSi** [comment]
Oh, sorry. 😅

**Comment by OmrSi** [comment]
I thought it came with the plugin.
