### ISSUE TITLE
when convert smi file to ass file, it’s not working if I add option “fixcommonerrors”

### ISSUE THREAD

**Issue by hhgyu** [SubtitleEdit/subtitleedit#2466]
Convert to ass file in CLI.

SubtitleEdit.exe /convert "44abdc8e132d0b9780a6cb480d8290e6_2872834297.smi" AdvancedSubStationAlpha /overwrite /fixcommonerrors

when execute , it was failed.

Without fixcommonerrors option, it’s worked rightly.
What is the problem?

[44abdc8e132d0b9780a6cb480d8290e6_2872834297.zip](https://github.com/SubtitleEdit/subtitleedit/files/1126760/44abdc8e132d0b9780a6cb480d8290e6_2872834297.zip)

**Comment by niksedk** [comment]
Does it work in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip ?

**Comment by hhgyu** [comment]
of course, i executed at latest beta but it did not worked.

**Comment by niksedk** [comment]
Perhaps it was an older beta you tried?

It works fine here:

     Subtitle Edit 3.5.3 - Batch converter

     1: 44abdc8e132d0b9780a6cb480d8290e6_2872834297.smi -> C:\Test\smi2ass\44abdc8e132d0b9780a6cb480d8290e6_2872834297.ass... done.

     1 file(s) converted
