### ISSUE TITLE
Feature request: Syntax coloring for two-line subtitle that doesn't exceed single line max length

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2469]
Hi.
So, this is something that I think would be useful. Ideally, when creating subtitles, you're trying to fit the entire subtitle into one line. However, you also can't go over a certain number of characters (as determined by settings->general->single line max. length).
What sometimes happens to me is I'll split a subtitle into two lines, even though there's only one speaker, and all the text could fit within the max character limit for a single line. So, like, if my limit is 42, per Netflix, I sometimes end up with two lines, one of which is 20 and the other of which is also 20, which, if you put together in a single line, comes to 41 (because there's a space added between them).
I'd like to suggest the option to include syntax coloring for when this happens, so that you can go back and join the two lines. "Color text when both lines can fit into a single line", or something like that, maybe something catchier.

**Comment by OmrSi** [comment]
@niksedk  @darnn This can be achieved with "Line Unbreaker" plugin. No need for coloring. Closed?

**Comment by darnn** [comment]
I mean, ideally I'd like to be able to use coloring and correct it as it happens, much like I do with exceeding the character limit. But it's not a huge priority for me. So up to you all.

**Comment by OmrSi** [comment]
If it's colored, then the plugin is useless, I think that's why they made the plugin.
Also, I don't think it happens a lot in a subtitle, I mean, when I started I used to miss about 10-20 Lines.
Now, barely 1 or 2 when I'm done translating, and Line breaker does the job with one click.

What I mean is, Instead of coloring and looking for the color and Unbreaking all the lines manually, Line Unbreaker finds the lines and unbreaks all of them with one click.

**Comment by darnn** [comment]
I don't think it would be useless - you could still use it the same way, you'd only have the added option of correcting it manually when it happens.
And I agree that from a purely practical standpoint in terms of the end result, I could just use the plugin. But, first of all, I want to train myself to split the lines properly as I type, because sometimes I'm forced to work in Word, for instance, in formats that it would be a hassle to export into something SE would understand.
And secondly, this is how it already works with the "color text if too long" option: It's based on the currently selected max line length, and it gives you immediate feedback rather than you having to wait until the end to see all the lines that are too long and correct them. It just feels like splitting a subtitle into two lines is the same sort of error, and so should be highlighted in the same way (and be based on the currently selected max line length automatically, unlike in the plugin).
