### ISSUE TITLE
3.5.3 don't set the line breaks in Timed Text correct

### ISSUE THREAD

**Issue by Ninelpienel** [SubtitleEdit/subtitleedit#2470]
When I load a Timed Text subfile (from Amazon) in 3.5.3 the line breaks are not correct: https://u.biyori.moe/bScXf07i.png
In 3.5.2 is everything fine: https://u.biyori.moe/ZdE9bU9q.png

**Comment by niksedk** [comment]
Does it work in latest beta?
If no, could you supply a sample file?

**Comment by Ninelpienel** [comment]
It works in the beta. So I think it is fixed in the next full version, right?

**Comment by niksedk** [comment]
jep :)
