### ISSUE TITLE
Suggestion: option to switch off automatic time correction

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2471]
Hey.
This is a very general thing, and presumably would require a bit of work, so I'd understand if it's not a priority, but:
Currently, when you copy and paste subtitles in list view, SE changes their timing according to where you paste them into. You can't have a subtitle that starts at 20 seconds followed by one that starts at 10 seconds.
I can see how this is useful, but for me it creates more problems than it solves, e.g. when pasting large blocks of subtitles in the wrong place. Since SE changes the timing for each individually, it can cause a massive slowdown.
So, what I'd propose is the possibility of switching off this automatic correction. This is kind of possible right now anyway, with SRT, if I just copy and paste the appropriate subtitles in source view. Their timing will not be automatically fixed. I'd just like to have the same option in list view.

**Comment by OmrSi** [comment]
I agree, sometimes I need to duplicate a line, and when I copy/paste it the time changes, the only way I can do it is by using Source View and re-number the lines after it. 
It would be useful if there was an option to switch it off.

**Comment by OmrSi** [comment]
Well, maybe it shouldn't be an option to turn it on or off. 
Maybe you could make a shortcut
Paste+Shift
Or Just Paste
It would be better.

**Comment by darnn** [comment]
Fixed (https://github.com/SubtitleEdit/subtitleedit/issues/3168)! Hooray!
