### ISSUE TITLE
Save to same folder of input file after ocr

### ISSUE THREAD

**Issue by MonoS** [SubtitleEdit/subtitleedit#2477]
Before version 3.5, SE used to save the resulting textual subtitle after OCR on the same folder as the input file, now it use the last selected folder.

Is there a way to revert this behavior?

**Comment by aaaxx** [comment]
[Related](https://github.com/SubtitleEdit/subtitleedit/issues/2384).

**Comment by niksedk** [comment]
Probably fixed via commit 504ae9373d80f5b861d034da92fc2f08e1945481
