### ISSUE TITLE
Unable to Locate Tesseract

### ISSUE THREAD

**Issue by spncrgr** [SubtitleEdit/subtitleedit#2479]
I just installed SE v3.5.3 (Windows 64-bit) via the installer. I'm trying to extract PGS subs from an MKV container. The "Import/OCR Blu-ray (.sup) subtitle" window appears, but when I click "Start OCR" I get an error that says
```
Unable to start 'Tesseract' (C:\Users\spncr\AppData\Roaming\Subtitle 
Edit\Tesseract\tesseract.exe) - make sure tesseract-ocr 3.x is installed!
```
Two questions:
1. Should the SE installer have included Tesseract, or is that something I need to install separately.
2. I have a custom install of Tesseract already on my system. Is it possible to "tell" SE to use that installation?

As a workaround I downloaded the portable version of SE and was able to import the subs.

Screenshots:
<img width="818" alt="ocr import dialog" src="https://user-images.githubusercontent.com/360099/28398944-91f5a68e-6ccf-11e7-95b1-80287f91e1b2.PNG">
<img width="317" alt="ocr error message" src="https://user-images.githubusercontent.com/360099/28398913-5719b208-6ccf-11e7-9271-5503f7e9b1b2.PNG">

**Comment by niksedk** [comment]
SE has an portable version of Tesseract included, but the Tesseract installer will mess that up :(

If you install Tesseract via the Tesseract installer you should un-select the registry settings. Also, see here: http://www.nikse.dk/SubtitleEdit/Help#issues

![image](https://user-images.githubusercontent.com/1261331/28402688-62b62dce-6d21-11e7-9e16-3dbe9ea172bf.png)
