### ISSUE TITLE
Update Tesseract?

### ISSUE THREAD

**Issue by grenzor** [SubtitleEdit/subtitleedit#2480]
Current version of Tesseract is 3.05.01 and SE is using version 3.02.

Should it be updated?

**Comment by niksedk** [comment]
I did some tests a few months back - and it was really much worse (except for periods at the end of a line), but feel free to do tests :)

**Comment by niksedk** [comment]
Tesseract 4 (beta) seems nearly okay. Gives about same results for high res bd sups as 3.02 and gives better results for low res vobsubs with the only issue being that V4 give some blank lines for shorter words. When ver 4 is out in final then it could be time to look/test again. 
Also, V4 is 4 times as big + 4 times as slow - would that be a problem?

**Comment by Lejohub** [comment]
It won't be a problem for many non-Latin languages speakers. Tesseract 4 gives far better results than any other previous versions for those languages (_even faster_), so it's a huge benefit for many of SE users.

I hope you will take that in your consideration  :)

**Comment by OmrSi** [comment]
Where can I find the files for arabic language?

**Comment by niksedk** [comment]
@Lejohub: thx for the info (I only tested with English). If you see Tesseract 4 out in a final version do let me know.

@OmrSi: In the OCR window, there's a  '...' button next to the language, Here you can download Tesseract languages from inside SE:
![image](https://user-images.githubusercontent.com/1261331/28497079-762e2a88-6f7d-11e7-9af0-fe9fcccd11af.png)

**Comment by niksedk** [comment]
Closed for now... when Tesseract 4 is released in final we can look again
