### ISSUE TITLE
Some special characters are missed in spell check

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2483]
I found at least two special characters (» and “) that are not detected by the spell check. I used Tesseract to OCR.

`168
00:11:38,465 --> 00:11:43,070
Carlos Frenk studies how gravity
shaped the universe» by creating`

`187
00:12:46,867 --> 00:12:51,004
fraction of“ a second after the
Big Bang, a shock wave of energy`

**Comment by niksedk** [comment]
I've tried to fix it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by Boulder08** [comment]
They are still not detected, even if the word attached to them clearly contains a spelling error.

**Comment by niksedk** [comment]
It think spell checkers ignore special characters.
