### ISSUE TITLE
Scene Change

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2484]
Is there a way to create a Scene Change file and import it to SE? 

And if not, how can I use the Scene Change future in SE?

**Comment by niksedk** [comment]
Generate waveform and then go to Video -> Import scene changes...

**Comment by OmrSi** [comment]
And is there a good program to generate Scene Change file?

**Comment by OmrSi** [comment]
I found it. 
And my love for the program just increased. 
Seriously, best one ever. ♥
Thank You.

**Comment by Kaan88** [comment]
What did you find?
