### ISSUE TITLE
Select Point all Sync Via Other Subtitle 

### ISSUE THREAD

**Issue by NoRRt** [SubtitleEdit/subtitleedit#2485]
Select Point all Sync Via Other Subtitle
You can not sync all selected lines

**Comment by dhaneshindika** [comment]
You can match one of the first lines and one of the last lines and hit Sync. Now, all lines will be synced.

**Comment by OmrSi** [comment]
@niksedk Closed?

**Comment by niksedk** [comment]
It's not possible to point sync selected lines with another subtitle.
