### ISSUE TITLE
Arabic File Encoding

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2489]
Hey, could you change the default Arabic encoding when importing a file with manual choosen encoding to Windows-1256?
Because I'm 100% that all Arabic translators who doesn't use UTF-8, uses Windows-1256
And the other Arabic encoding are used rarely if not at all. 
Thanks. :)

**Comment by OmrSi** [comment]
.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
