### ISSUE TITLE
Remove only formatting tags without removing music notes

### ISSUE THREAD

**Issue by nyuszika7h** [SubtitleEdit/subtitleedit#2490]
I'd like to have an option to remove formatting tags from SRT subtitles, but keep music notes. Removing music notes should be a separate option, IMO.

**Comment by techlamajeure** [comment]
Hello this issue is still active especially on command line . /removeformatting is there a command line attribute we can add to keep music notes or to have them be a seperate option? txs

**Comment by niksedk** [comment]
That's a bug... music symbols are probably not really "formatting"... and are not treated as such in the UI and nor in the UI batch convert either.

Committed change here: https://github.com/SubtitleEdit/subtitleedit/commit/e1e39b236e2c3cc1ba8e8a90ca63d0b0a08fef84

Beta updated here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by techlamajeure** [comment]
Awesome you rock! thanks for the quick fix
