### ISSUE TITLE
New Actor field / Name field in SSA format can't be exported in export custom text format

### ISSUE THREAD

**Issue by mellsaid** [SubtitleEdit/subtitleedit#2494]
We were excited to see the new actor field in the SSA format today. 
We tried to export the file using export custom text format for it to be produced in our custom format, and we tried adding the field using the following tags: {name} / {actor} / {Name} / {Actor} however it doesn't pull the field like the rest. 

Can this be added please. And is there an easy way for us at the moment to do that? 

Example attached below:

![image](https://user-images.githubusercontent.com/22168697/28752535-3bfb2076-751a-11e7-8610-9394ad8b9de0.png)

**Comment by niksedk** [comment]
Fix will be included in next update - is also included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by mellsaid** [comment]
@niksedk brilliant! Thank you very much!
