### ISSUE TITLE
The wave grid/line on Subtitle Edit 3.5.3. not working properly with the second .vob video  opened

### ISSUE THREAD

**Issue by Ardiaei** [SubtitleEdit/subtitleedit#2495]
Hi there, 
I received a DVD with an interview that I  am supposed to translate (put translation subtitles in the video).  Having checked  a few programs I opted for Subtitle Edit 3.5.3.

When copied into the computer, the content of the DVD is made up of several  vob files (videos).

When I open the first video vob file  in the Subtitle Edit, I can work  with ti and produce  a '.srt' file and watch the whole video with the translation subtitles as a final product. 

 However, when I open the next vob file ( the continuation of the first one) the whole web grid  gets a little 'strange'. You can't  work with the blue line/needle on the wave space  because it does not show up, unless you click on the wave, and even than it's hard to move it where you want. Secondly, the video does not start at the beginning of the wave line but it is somewhere in the middle ( I fond that it actually starts right at the time  the previous  vob video file finished, lets say at 21 minutes).

Would anyone have an idea what is going on and how to fix this problem?

I thank you in advance
ardiaei@gmail.com

**Comment by darnn** [comment]
Those VOB files aren't meant to be opened separately, they're all part of the DVD structure. Programs that play DVDs read the VIDEO_TS.IFO file, which contains the information about how all the VOB files go together, and play them seamlessly. If I were you I'd use a program to join them all into one video file and work on that.
Here's a free program I found that works for me:
http://www.makemkv.com/download/
And here's what the end result looks like in SE:
![se353-makemkv](https://user-images.githubusercontent.com/19672444/28778907-f4fce2b8-7609-11e7-824b-53f7bbf76e9d.png)

**Comment by Ardiaei** [comment]
Than you for the help.

I thought that might me the case.

I 'll give this  program a try.

Alternatively, can I ask the producer to provide  the video in a different
format and which format would be good for  Subtitle Edit, the one where the
whole video  would be opened as one single file seamlessly?

 Thank you again
Ardiaei

**Comment by darnn** [comment]
It seems to work with any format I tried it with - mkv/H264, mp4/H264, WMV, avi/XviD, etc.

**Comment by Ardiaei** [comment]
Thanx.


Another issue  is, our video editor uses Final Cut and he told me that he
can't use the .srt format in the Final Cut.

Do you know of any program that can help here, i.e. convert the srt file
into some text file compatible with Final Cut or  is it enough just to copy
the text from the .srt file into a Word?

Ardiaei

**Comment by darnn** [comment]
I have no idea myself because I don't use Final Cut, but if you go to file->save as, under "save as type" there are several Final Cut formats you can try.

**Comment by Ardiaei** [comment]
Thanx

**Comment by Ardiaei** [comment]
Guys,

anyone know what specific version of the VLC I need to download for
 Subtitle Edit.

I know it should be 64-bit because my laptop has a &$-bit operating system,
but I do not know if there are other specifications in addition to this
64-bit operating system?

Thanx
Ardian

**Comment by OmrSi** [comment]
Go to video settings and download MPV
It's much better than all of the others

**Comment by Ardiaei** [comment]
Thanx

**Comment by Ardiaei** [comment]
Hi guys,
Does anyone know how do I transform an Arabic text (translation) form a
Word format to .srt format using subtitle edit?
We tried and what we gor as a rwsult was that the whole text got
messy...the sentences moved and thebformat changed?
Anyone had any experience with transforming an arabic word text into .srt
text using Subtitle edit program?
Thanx

**Comment by darnn** [comment]
How did you try? I would suggest using Word to save it as a plain text file with whatever encoding is appropriate (Word will pop up a window to ask you), and then using Subtitle Edit's "import plain text" function (File->Import plain text).
