### ISSUE TITLE
Unbreaking and moving to next line simultaneously break syntax coloring

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2497]
Hi. I'm using SE 3.5.3 build 10, although I don't believe this was brought up since May, so I assume nothing's changed.
The bug comes up in a situation like the following: The single max line length is, for example, 40, and the focus is on the textbox, with a subtitle where the first line is 39 characters and the second line is five characters. If you press the keyboard shortcut to unbreak the subtitle and the keyboard shortcut to move to the next line simultaneously, both actions are performed, but the line in list view is not colored red. Presumably SE doesn't check to see if the subtitle exceeds the single max line length when moving to the next subtitle, provided that it didn't exceed it before.

![se-next line color syntax](https://user-images.githubusercontent.com/19672444/28817685-b0aee482-76b1-11e7-8f83-27874c63737c.gif)

**Comment by niksedk** [comment]
I've given it a try in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
Better?

**Comment by darnn** [comment]
Seems to be! Thanks!
