### ISSUE TITLE
About auto-Detection

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2498]
after the last commit, it works very good
it detects encoding without using "import with manual chosen encoding"
but the problem is, it doesn't put the encoding in the output boxes in the toolbar
it should, after opening a file put the current encoding in the toolbar box so you can change it
Right?

**Comment by ivandrofly** [comment]
> after opening a file put the current encoding in the toolbar box so you can change it
> Right?

this is actually very good idea, just in case subtitle edit couldn't detect encoding this would be helpful. for example on short subtitles /cc @niksedk

**Comment by OmrSi** [comment]
Is this hard to implant? 
Does it require a lot of changes? 
Or just a change to the return value of the box?

**Comment by OmrSi** [comment]
it used to do that automatically when importing in old versions
![untitled](https://user-images.githubusercontent.com/20923700/28928764-c1f77c06-7876-11e7-999a-c011b9cebc8f.jpg)

**Comment by niksedk** [comment]
I'm not sure what you mean... SE show the correct (old and obsolete) ANSI code page in the toolbar for me!

**Comment by OmrSi** [comment]
just tried the latest Beta, it's working.
wasn't working in build 131 for me.
so sorry for the inconvenience.
