### ISSUE TITLE
Tesseract Release has stopped working

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2504]
They released new files 3 days ago
when i use it i get this:
![untitled](https://user-images.githubusercontent.com/20923700/28935662-f3a54564-788d-11e7-836a-390e93db41c6.jpg)

is it a problem from their end?
or am i using a wrong file?

**Comment by OmrSi** [comment]
https://github.com/tesseract-ocr/tessdata/commit/3a94ddd47be01fd897cbe31f05cbd2301454cf8a#commitcomment-23463513

**Comment by niksedk** [comment]
I guess that you should use the older data files as the new data files apparently do not match the executable. 
Also, not really an "issue" when experimenting with beta builds/components :)

**Comment by OmrSi** [comment]
Cool, I guess I'll keep using the old one until it is updated.
There was significant updates to Arabic, I think, it had many problems.
Thanks. :)
