### ISSUE TITLE
{\an8} on srt subtitles with VLC as media player

### ISSUE THREAD

**Issue by alfix0** [SubtitleEdit/subtitleedit#2511]
VLC standalone is capable of show subtitles with {\an8} on top of window.

But when is used on SubtitleEdit as video player it don´t show on top.

What's is the issue?

Best regards

**Comment by niksedk** [comment]
Try using "mpv" if you want a on video preview. To use mpv go to Options -> Settings -> Video player -> Download mpv...

**Comment by alfix0** [comment]
Ok it works.
Thank you.
