### ISSUE TITLE
Bug: Cannot open some files in batch convert (3.5.2+)

### ISSUE THREAD

**Issue by dihmandrake** [SubtitleEdit/subtitleedit#2512]
Version 3.5.2+ has a bug (without any error message) that prevents the batch converter from opening some files. Working in 3.5.1
Open these files in the standard editor works fine.

**Comment by niksedk** [comment]
thx for the info - this should be improved somewhat in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

Do you still have a problem with some files? If yes, what format are those files?

**Comment by dihmandrake** [comment]
Just tested those files again in the beta and they are working again in the Batch Converter.
I should have tested the beta.

For the record:
- .sub
- .sub
were having problems.

**Comment by niksedk** [comment]
Could you email me a sample of those .sub files that are not working?

**Comment by dihmandrake** [comment]
@niksedk I have send some files to your github registered gmail address.
