### ISSUE TITLE
Subtitle preview not RTL in RTL mode when using MPV

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2515]
Hey. 3.5.3 build 139. 
In RTL mode, if I choose mpv as the media player, and check "mpv handles preview text", the preview stops displaying the punctuation properly, the way it does in the normal preview in RTL mode.
Without "mpv handles preview text":
![se-preview-without-mpv](https://user-images.githubusercontent.com/19672444/29244108-caae94e4-7fb8-11e7-8ba8-59f441042427.png)
With "mpv handles preview text":
![se-preview-with-mpv](https://user-images.githubusercontent.com/19672444/29244111-d371567a-7fb8-11e7-8ec1-8bd3883fdcaf.png)

**Comment by OmrSi** [comment]
I've been using RTL with MPV and didn't even know it should show up reversed. 
It would be perfect if it did.

**Comment by darnn** [comment]
Yeah, as you can see, if you let SE handle the subtitle preview, it appears correctly, it just means the subtitle isn't overlaid on the video, which I prefer since it saves space.

**Comment by niksedk** [comment]
SE uses ASS for the mpv preview - can anyone make an ASS sample file that displays correctly?
If it's not possible then I guess SE could run "Reverse RTL start/end" if in RTL mode.

**Comment by darnn** [comment]
I made two ASS files that display correctly, but I literally just did it through the two ways offered by SE, i.e. "fix RTL via unicode control characters" and "reverse RTL start/end".
Unmodified:
https://www.dropbox.com/s/yqmqwsqdnlcrof1/DX16171HD%20KirbyBuckets-F055.ass?dl=1
Fix via unicode control characters:
https://www.dropbox.com/s/jo1moul9eaz0ph8/DX16171HD%20KirbyBuckets-F055-fix-via-control-chars.ass?dl=1
Reverse RTL start/end:
https://www.dropbox.com/s/fi8ymkrkr9o6ae5/DX16171HD%20KirbyBuckets-F055-reverse-start-end.ass?dl=1

So if it could run either of those on the preview subtitles, I think it should be okay.

**Comment by OmrSi** [comment]
I think "Reverse RTL start/end" is better.

**Comment by darnn** [comment]
Sweet! Could you compile a new beta with this, please?

**Comment by niksedk** [comment]
New beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Thank you! However, it seems like it had the opposite effect: things now appear as LTR in RTL mode, and vice versa.

**Comment by OmrSi** [comment]
True.

**Comment by OmrSi** [comment]
Yes. It is working. 
But if there is an ass tag, it doesn't reverse what's in it. 
I tried using "Reverse RTL start/end" on the sentence, but it didn't reverse either
At this point I tried "Fix via unicode control characters", And it reversed everything correctly. 
my initial assumption was wrong. 
So maybe use "Fix via unicode control characters"?
