### ISSUE TITLE
'Fix Missing Spaces' doesn't find lines with unicode music notes when wrapped in italics tags

### ISSUE THREAD

**Issue by cameronks** [SubtitleEdit/subtitleedit#2516]
I was trying to add missing spaces between text and music notes. For example:

`♪ Dream, little one♪`  to  `♪ Dream, little one ♪`

'Fix common errors > Fix missing spaces' will do this, but if the line is wrapped in italics tags like

`<i>♪ Dream, little one♪</i>`

it will be ignored.

**Comment by niksedk** [comment]
Thx for the info :)
Hopefully fixed in latest beta now via commit 97f2d39d739e8afc82322aa2dbf051f13b6df105: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by cameronks** [comment]
Works great! Thank you!
