### ISSUE TITLE
Switching to source view and back from a cluster of subtitles with the same start time/duration

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2517]
Hey. This concerns SRT files - I think it doesn't happen with some of the other formats, but I mostly work with SRT.
So, I often have to insert new subtitles between two existing, timed subtitles. I work with scripts or just inaccurately timed files, and the person after me in the workflow redoes the timing, so this comes up fairly often.
When I insert a new subtitle between two other subtitles, and there's no time gap between them, the new subtitle has a duration of -0.001. If I insert several more new subtitles after that, they all have a duration of -0.001, and the same start time as the first new subtitle I inserted.
Then, if I'm on the last of these new subtitles and I use a keyboard shortcut to switch to source view and then back, the highlighted subtitle in list view is the first subtitle that has the same start time and duration as the one that was highlighted previously. In short, here's a gif:
![se-listview-sourceview](https://user-images.githubusercontent.com/19672444/29254166-035ccf9c-8098-11e7-9189-c91c6b9cb15d.gif)
Here, I'm "teleported" from subtitle 23 back to subtitle 21.

**Comment by OmrSi** [comment]
what is the  keyboard shortcut to switch to source view?

**Comment by darnn** [comment]
just the regular one for switching between tabs, ctrl+tab. ctrl+pgdn/pgup also work, possibly because there are only two tabs.

**Comment by niksedk** [comment]
Should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Seems to work here! Thanks!
