### ISSUE TITLE
Batch Converting to Sup

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2528]
When batch converting a punsh of Srt files to Sup. 
When you activate this: http://imgur.com/a/9WdX7
Then return to settings, the activation is disabled. 
Is this a bug or is there a specific way to it?

**Comment by OmrSi** [comment]
A friend told me about it. 
Sadly, I can't be sure of it myself. 
I don't have a computer these couple of days.

**Comment by nstefy** [comment]
Also selecting font to bold doesn't work
With font selected bold the resulting file has normal text
using export to blu-ray sup with same setting the resulting file is ok
