### ISSUE TITLE
Loading plugins

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#2531]
Subtitle Edit portable will prefer **\AppData\Roaming\Subtitle Edit\Plugins** folder instead of local **Plugins**

PS: I have both Installed & portable version on my machine.

**Comment by niksedk** [comment]
Hm, I cannot re-create this. 
With a fresh unpack of latest portable version it works fine... for me ;)

**Comment by ivandrofly** [comment]
yeah, I was debugging without Dictionaries folder on portable version... so if no **Dictionaries** folder is found SE will use installed **appdata's** as default with I don't think is correct, right?
