### ISSUE TITLE
Sorting is unreliable

### ISSUE THREAD

**Issue by Skrity** [SubtitleEdit/subtitleedit#2535]
When I sort my subtitle by "start time" and there are a few lines that have same "start time" an uncertainty arises where you can do the same sorting and get different results every time.
This is very unsafe for editing ssa and such, because lines can contain background for the next line. Mixing such lines can break output subtitle without editor even noticing.

[Example file](https://pastebin.com/Gmne4X6p)
You can try sorting it by start time and observe change in the order of lines 1-3.

In my opinion when two or more lines have the equal sorting parameter software should sort this lines by id these lines have.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
