### ISSUE TITLE
Waveform hangs on overdesigned ASS/SSA files

### ISSUE THREAD

**Issue by Skrity** [SubtitleEdit/subtitleedit#2536]
[This file in particular](https://drive.google.com/open?id=0B48MYstz4tyBTUdLc2cxc2hHWnM) contains ~300 lines with the same timestamp. Without waveform enabled it loads just fine, but when loaded with waveform enabled(should also be generated) at start of file SubtitleEdit hangs on me.

If I were to guess It tries to render them all at a single place which also requires to recalculate opacity(and probably color), so maybe a _limit to amount of visible(rendered) lines_ is necessary.

Even on a file like [this](https://drive.google.com/open?id=0B48MYstz4tyBdXI3V3p4Nk45V2c) it gets frustratingly bad for me(Windows 10, i7-3770, SubtitleEdit 3.5.2 & 3.5.3) although it only has 13 such lines.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
