### ISSUE TITLE
Some SSA tags getting lost after saving (+feature req)

### ISSUE THREAD

**Issue by Skrity** [SubtitleEdit/subtitleedit#2537]
- [ ] SSA tags bug
When saving SSA with SubtitleEdit some advanced tags(from aegisub) being lost.
[example subtitles](https://github.com/SubtitleEdit/subtitleedit/files/1267827/subs.zip)
Comparison screenshot (source on the left). Mind you nothing was edited, so all red zones is a _possible_ misinterpreting. Selected line is the only one confirmed to be visually wrong.
![screenshot](https://user-images.githubusercontent.com/22554542/29934240-15021632-8e83-11e7-8776-0b9d1f08f347.png)

- [ ] "Timing" mode
@niksedk mentioned in #2457 that all tags being processed into "unified" format.
As I understand it's a simple problem with parser _dropping_ unknown tags. And if that's the case, then I would like to suggest "Timing" mode. I don't know if current SubtitleEdit pipeline will allow it, but I'd like to be able to do simple manipulations(e.g. timing) without lines being processed at all. Since this task doesn't require format conversion it would be way easier to ensure formatting haven't been altered at all.

I think SubtitleEdit is clearly superior to other software I used when it comes to waveform/visual timing(mpv support is good touch too), but currently I'm forced to use something else to apply timings I get from SubtitleEdit because formatting is saved unreliably.

**Comment by niksedk** [comment]
Hm, one way I guess could be skipping too advanced ASS tags and just displaying the original ASS tags - like this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
How does that work?

**Comment by Skrity** [comment]
Now it works way better!, but for some reason in current Beta "Actor/Name" field is not being saved. 
![bcompare_2017-09-05_16-38-10](https://user-images.githubusercontent.com/22554542/30063853-ac4aa24c-9258-11e7-879a-0d01a4a79985.png)

**Comment by Skrity** [comment]
Also SubtitleEdit opens consecutive curly braces and while most of the time it is okay,
![like here](https://user-images.githubusercontent.com/22554542/30065710-72140036-925e-11e7-9804-70978ae23980.png)
there is an "edge" case 
![first line](https://user-images.githubusercontent.com/22554542/30065846-e1cca798-925e-11e7-81ef-40c80b81c13f.png)
where it breaks functionality since "{ }" doesn't contain \\-tags. You can argue that this is bad design and you would be 100% right.
I don't know how to proceed here. I haven't found any info on what this `{0:27, æ¬¡å›˜}` means or how they are proceeded by libass.

I also found a second line like this, I'm not sure if it breaks the same way since `\pos` is properly enclosed. Maybe someone here can shed some light on what this is.
![second line](https://user-images.githubusercontent.com/22554542/30066209-dff11d7c-925f-11e7-848e-635a5585db4c.png)

**Comment by niksedk** [comment]
I think the "Name" tag is from "SSA" or ? Anyway, that should be handled better two in latest beta.

OK, SE now tries not to touch ASS tags when it's not needed.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by Skrity** [comment]
Works wonders, thank you! For reference on {} usage, I regex'd all the lines from subs I currently have.  It seems translators use {} to store commentaries/translation notes for designers/proofreaders/other members. 
[commentary_lines.txt](https://github.com/SubtitleEdit/subtitleedit/files/1278322/commentary_lines.txt)
