### ISSUE TITLE
ASS type subtitle font name tag (\fn) space cut issue

### ISSUE THREAD

**Issue by linzack** [SubtitleEdit/subtitleedit#2541]
Hi,
I have a ASS subtitle need to adjust time offset, it has a pattern like:
`Dialogue: ..... \fnNoto Sans CJK`
which `\fn` is font tag, `Noto Sans CJK` is the font name.
But after I adjusted time offset and saved file, the pattern was changed:
`Dialogue: ..... \fnNoto`
Subtitle Edit 3.5.3 cut the font name after the space character, and that is a unwanted behavior.

Thank you!

**Comment by OmrSi** [comment]
I told him about this issue, and I remember he fixed it. 
Have you tried the latest beta?

**Comment by linzack** [comment]
Yessss! 
This issue get fixed in SubtitleEditBeta.zip, the beta version is commit [a43f8a1](https://github.com/SubtitleEdit/subtitleedit/commit/a43f8a1)

Thank you!

**Comment by OmrSi** [comment]
Great. 👍
