### ISSUE TITLE
Issues with negative time codes in translator mode

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2544]
Hi. 3.5.3 build 180.
In translator mode, if a subtitle with negative time codes is created and text is entered into it, the time code in the translation file changes to a non-negative one, but the one in the original file remains negative (even after saving). This can eventually bring about problems such as those descrived here (https://github.com/SubtitleEdit/subtitleedit/issues/2201).
To reproduce:
1. Create a new subtitle file.
2. Use the "insert subtitle after" keyboard shortcut e.g. three times. Type (e.g.) "a" in subtitle 1, "b" in subtitle 2 and "c" in subtitle 3. Save this file as original.srt.
3. Use Tools->Make new empty translation from current subtitle. Type "1" in subtitle 1, "2" in subtitle 2, "3" in 3. Save the translation file as translation.srt.
4. Focus on the first subtitle in list view, and use the "insert subtitle before" keyboard shortcut. The first subtitle should now have negative time codes.
5. Modify the contents of the first subtitle (both original and translation), e.g. "z" in original and "0" in translation.
6. Press the keyboard shortcut to move down in list view. Note that the time code displayed in the "start time" field for the first subtitle has changed.
7. Use the keyboard shortcut to save the original and translation files. Open the files in a text editor. Note that the time codes for the first subtitle in each are different: Negative in the original file, not negative in the translation file.
8. After this, to reproduce the issues described here (https://github.com/SubtitleEdit/subtitleedit/issues/2201):
In SE, delete the first subtitle. Note that the original text in what is now the first subtitle disappeared.
9. Save both files. SE will pop up the "contains negative time codes" prompt. Click "yes".
10. Open both files in a text editor. Note that in the translated file, the first subtitle was deleted, but in the original file, the second subtitle was deleted.

At this point, working with these two files open in SE could create issues down the line, since the time codes are different. Occasionally inserting a new line will erase the contents of adjacent lines in the original subtitle file.

Gif, which you might have to slow down to make anything out:
![se negative time codes256](https://user-images.githubusercontent.com/19672444/30006892-8990d878-910b-11e7-8363-89c3483581ee.gif)

The specific problem here with the negative time codes is important in itself, but what really bothers me is the thing that takes place in step 8, because it crops up whenever SE somehow has an original file and a translation file open with different time codes.
So, if it's not too hard, as an overall solution to this problem, I would suggest some kind of check to make sure the original file and translation file time codes are always the same. Or, to correspond with what's happening on the screen, whenever the original file is saved, it should just have its time codes overwritten with those of the translation file. Something along those lines.

**Comment by niksedk** [comment]
Hm, I've problems re-creating this...

**Comment by darnn** [comment]
I'll try to upload the actual srt files I'm creating, although they're no different from what's shown in the gif. But I have a deadline right now so I'll have to get back to this tomorrow. I appreciate the effort, though!

**Comment by darnn** [comment]
I've attached the srt files, as well as my settings file, in case there's something unique to it:
[negative timecodes.zip](https://github.com/SubtitleEdit/subtitleedit/files/1341454/negative.timecodes.zip)

Open them as original/translation, highlight the first subtitle and use the shortcut for "insert subtitle before" (and perform the rest of steps 4-6). On my end, in build 289, this happens:
![se-negative-time-codes](https://user-images.githubusercontent.com/19672444/30976724-313e98dc-a47e-11e7-96a2-7beff8056a83.gif)

As you can see, something is already amiss: the "one" propagates to the new subtitle in the original text textbox, and then in list view as well.

On the plus side, the "save original and translation" keyboard shortcut now works as expected. When I save both files, the modified files now look like this:
[negative timecodes modified.zip](https://github.com/SubtitleEdit/subtitleedit/files/1341512/negative.timecodes.modified.zip)

original srt:
1
-00:00:01,001 --> 00:00:00,999
zero

translation srt:
1
00:00:01,000 --> 00:00:03,000
0

So, as you can see, the changes to the text are saved in both, but the negative timecode is saved in the original, but not in the translation. Which is, again, apparently because SE automatically corrects the negative timecode to a non-negative one, as can be seen in list view in the gif when I move around between the lines, but the change only affects the translation timecode. And that's why I suggested that you implement some check to make sure that whenever SE modifies the timecode, it modifies it in both the original and in the translation, since when it assumes they're the same in both (as they should be), but they're actually different, strange things begin to happen.

**Comment by niksedk** [comment]
@darnn: You're running in "frame" mode, right?

**Comment by darnn** [comment]
Right now, yeah.

**Comment by niksedk** [comment]
OK, new beta up where I try to allow negative time codes in frame mode: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
Any better?

**Comment by darnn** [comment]
It is better - both files get saved, and negative time codes aren't corrected. But, for some reason, the timecodes in the two SRT files still aren't exactly the same:

Original:
1
-00:00:01,001 --> 00:00:00,999

Translation:
1
-00:00:01,000 --> 00:00:01,000

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by darnn** [comment]
All good on this end!
