### ISSUE TITLE
Memory leak with MPV

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2547]
Hey. So, ever since I switched to MPV, the SE process has begun to gradually take up a bunch of memory, and eventually this actually slows down my ability to type, skip back and forth in the video and so on. Right now the process takes up 1.2GB, and as soon as I close the video and open it again, it drops to 192MB. Not sure how to reproduce this exactly, it seems to just gradually happen if I'm working on the same video file for like an hour.

**Comment by OmrSi** [comment]
I was just about to write about this.
it's causing many problems.
maybe needs to reset every while?
![untitled](https://user-images.githubusercontent.com/20923700/30052979-ea77b8d0-922f-11e7-8261-ae08a25342a9.png)

**Comment by darnn** [comment]
Thanks! Any chance you can upload a new beta for this?

**Comment by niksedk** [comment]
thx :)
This is a good fix to include in next update!
And yes, new beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Great! Thank you!
