### ISSUE TITLE
UTF-8 Bom Bug

### ISSUE THREAD

**Issue by ukdtom** [SubtitleEdit/subtitleedit#2549]
If you from SubTitle Edit tries to open an srt file, that is encoded with UTF-8 BOM, then SE hangs with a spinning cursor

Env:
OS: Win10 Pro N fully updated
SE: 3.5.3.9e723cc

Opening the srt file in Notepad ++ and change encoding, makes it work with SE

**Comment by niksedk** [comment]
Could you supply a sample file?

**Comment by ukdtom** [comment]
Davs med dig.

****** Danish *********
Extremt pinligt her, men kan sgu ikke reproducere, selvom det er noget jeg har oplevet flere gange,
Næste gang det sker, skal jeg nok være mere omhyggelig, og sikre bedre "beviser"

****** English **********
So sorry here, and so embarrassing, but simply can't reproduce, even though I've seen this several times. Next time it happens, I'll make sure to collect relevant info.

***************************
Closing this for now, crawling back into my cave, and will reopen next time it happens with additional info

Best Regards, and huge thanks for this project

/Tommy
