### ISSUE TITLE
WebVTT timing header incorrect in 3.5.3

### ISSUE THREAD

**Issue by shjiemon** [SubtitleEdit/subtitleedit#2550]
Hello,

After the upgrade to 3.5.3 the WebVTT 'timing header' is incorrect. It is missing a space after the in-cue...

For example:

00:03:58.880--> 00:04:04.040

...should be...

00:03:58.880 --> 00:04:04.040

Regards, Simon

**Comment by niksedk** [comment]
Thx for the info - this is fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

SE 3.5.4 should be out soon...

**Comment by shjiemon** [comment]
awesome, thanks :)
