### ISSUE TITLE
Comments lose layer after saving (ASS)

### ISSUE THREAD

**Issue by Skrity** [SubtitleEdit/subtitleedit#2553]
Nothing major, just subj, some screenshot and test file.
![layers](https://user-images.githubusercontent.com/22554542/30087880-d4a5cb92-92ab-11e7-874d-f6f34f8c32f7.png)
[test file](https://github.com/SubtitleEdit/subtitleedit/files/1279272/Nisemonogatari.e03.x265.12bit.Opus.zip)
I'm on W10, beta build https://github.com/SubtitleEdit/subtitleedit/commit/a9c8f37

Also I apparently cannot remove styles with "Remove" button in "Advanced Sub Station Alpha styles" dialog, "Remove all" works. Repeatable with the [same](https://github.com/SubtitleEdit/subtitleedit/files/1279272/Nisemonogatari.e03.x265.12bit.Opus.zip) file.

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
