### ISSUE TITLE
RTL list focus still not working.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2559]
even in the latest Beta.

**Comment by OmrSi** [comment]
when changing to RTL and back, list view loses focus.

**Comment by niksedk** [comment]
Works fine here...

**Comment by OmrSi** [comment]
Just tried it in the last Beta.
i select an item from list view.
then go to RTL.
and the list goes back to the beginning.

**Comment by OmrSi** [comment]
the line is still selected on the list but the list isn't focused on the selected line.
