### ISSUE TITLE
Add "Match Case/Whole Word" option in Replace window.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2562]
sometimes you only need to replace a matching case.
and it is available in "Find" window.

**Comment by OmrSi** [comment]
Would that be possible? 
If there is a certain word I want to change, I have to use Find in replace Every time 
But if you added "Match Case" you don't have to.

**Comment by diomed** [comment]
This is what OCR can be used for.

Options - Settings - Word Lists - OCR fix list

There u enter words u wanna change, and when u hit Fix Common Errors and select it in list 
☑️ Fix Common OCR Errors

all words you once entered will be constantly fixed to your liking.

**Comment by OmrSi** [comment]
It's much simpler if you use Match Case, especially if your using it to change a certain word in one certain file, not every time, like names. 
And there are a few special cases in Arabic.

**Comment by aaaxx** [comment]
The Replace window has a "Case sensitive" option, so what exactly is your problem?

**Comment by OmrSi** [comment]
Arabic and many other languages doesn't have "cases".
for example, i want to change "علي" to "عليّ", if i use replace all it will change every word which contains the three letters "علي" like "عليها" or "عليه" for example, but if you have a "Match Case" option, it would only change the word "علي".
that is my point/problem.

**Comment by aaaxx** [comment]
Oh, I get it now. But why do you keep mentioning cases instead of just "Whole word"?

**Comment by OmrSi** [comment]
That's what it's called in Word. I made a mistake between them.

**Comment by OmrSi** [comment]
But i think @niksedk got it.
