### ISSUE TITLE
Can't select OCR dictionary with v3.4.0 and upward

### ISSUE THREAD

**Issue by Reino17** [SubtitleEdit/subtitleedit#2565]
Hello Nikolaj,

I can't seem to select the OCR dictionary anymore with v3.4.0 and upward:

![se_dict](https://user-images.githubusercontent.com/8537830/30232860-83815e54-94f2-11e7-8ea7-7d7701329287.gif)

The lastest version that still worked was v3.3.15. I see that's a transition from .NET 2-3.5 to .NET 4-4.5.
https://github.com/SubtitleEdit/subtitleedit/issues/223#issuecomment-327575092:
> A side note: I'm still on Windows XP on a non-sse2 cpu...

I have a terrible feeling this could have something to do with it. Do you have any idea?

**Comment by niksedk** [comment]
Hi Reino,

What happens if you the the hunspell.dll from v3.3.15 ?

Best regards
N

**Comment by Reino17** [comment]
Hmm, that works.
What you see above is what (apparently) happens with the '_Hunspellx86.dll_' I compiled myself.
Then I wonder,... does libhunspell need to be compiled in a certain way, or with a specific option?
