### ISSUE TITLE
zlib compression in Matroska

### ISSUE THREAD

**Issue by mkver** [SubtitleEdit/subtitleedit#2566]
Hello,

SubtitleEdit currently does not fully support track compression in Matroska: zlib compression works only for PGS and vobsub subtitles; it doesn't work for srt, ass and DVBSUB. While in the first two cases the compression is usually useless (and sometimes even counterproductive), it is worthwhile to compress DVBSUB. And MKVToolNix does it by default since version 9.9. But unfortunately SubtitleEdit doesn't support them in the compressed form which surprised me: I thought that it is easiest to use a generec unpacking method that works for all tracks, but apparently that is not so.

Greetings
Andi

PS: There is actually another feature of Matroska that SubtitleEdit doesn't support at all: The compression of the codec's private data. The only muxer that I know of that uses this is mkclean; MKVToolNix can read the files correctly, but does never compress the private data. SubtitleEdit treats a compressed codec private (in a vobsub file -- in this case, one can really save a few byte because their CodecPrivate is so long) as invalid (so the color pallette is missing and the colors are wrong). I don't know if it is worthwhile to support this feature.

**Comment by niksedk** [comment]
thx for the info :)
I don't suppose you have a small sample file?

**Comment by niksedk** [comment]
OK, new beta up which might have better handling of DVBSUB?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

I've not looked at the other stuff yet, but sample files are welcome :)

**Comment by mkver** [comment]
Sorry for not including a sample from the beginning. I thought that you had enough transport streams with DVB subtitles and creating a sample from them with MKVToolNix is easy. [Here](https://www.dropbox.com/s/a5dq72em1jfrydq/Uncompressed.mks?dl=0) is a mks-file with uncompressed DVB subtitles; [here](https://www.dropbox.com/s/s8iem0ex2tyuben/Compressed.mks?dl=0) with compressed subtitles.

**Comment by mkver** [comment]
The new beta can properly handle compressed DVB subtitles. Compressed srt (and probably ass) doesn't work yet.

**Comment by mkver** [comment]
I have also created and uploaded a few more sample: For [track-, but not CodecPrivate-compression](https://www.dropbox.com/s/2o4g4qgq8y2cp9r/uncompressed.codec.private.mks?dl=0); for both [track- and CodecPrivate-compression](https://www.dropbox.com/s/z2lwbnh6b72w4yz/compressed.codec.private.mks?dl=0); for [uncompressed srt in Matroska](https://www.dropbox.com/s/1jq8yzv2jfa0ewa/srt.uncompressed.mks?dl=0); and for [compressed srt in Matroska](https://www.dropbox.com/s/kph2iijc2f3pkuw/srt.compressed.mks?dl=0).

**Comment by niksedk** [comment]
thx a lot for the files :)
I think it all works now (the CodecPrivate is a tiny bit strange as we don't really know if it's compressed or not, so SE just tries to unpack it and if that fails just returns the CodecPrivate uncompressed).

New beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by mkver** [comment]
One actually doesn't have to rely on guessing whether the CodecPrivate is compressed (which theoretically could lead to false positives): The ContentEncodings header field tells you this. Here is the relevant part of the header for compressed.codec.private.mks:
```
6D 80 8A 62 40 87 50 32 81 03 50 34 80
```
Taking a look at the [Matroska specs](https://matroska.org/technical/specs/index.html) we see that 0x6D 80 stand for ContentEncodings; 0x8A is the EBML-length field signalling that the next 10 bytes are children of the ContentEncodings field. 0x62 40 is a ContentEncoding; according to 0x87 the remaining seven bytes belong to this ContentEncoding.
0x50 32 means ContentEncodingScope, the length of its payload is 1, the payload being 0x03; the bits of 0x03 now imply that all frame contents (corresponds to the lowest significant bit) and the tracks private data (corresponds to the 2-bit) have been modified by the ContentEncoding this field belongs to. The default value for ContentEncodingScope is 0x01 (meaning that only the frames have been modified) and therefore this field is omitted in most files. (MKVToolNix doesn't write it as it doesn't compress the headers.)
0x50 34 80 is a ContentCompression master element without any children. Therefore its child ContentCompAlgo has its default value corresponding to zlib.

There are also three more children of ContentEncoding, two of which have default values:
ContentEncodingOrder: It's possible to have more than one ContentEncoding (i.e. first compression, then encryption; or first header removal compression, then zlib compression). The value of ContentEncodingOrder tells in which order they have been applied. It's default value is 0 so that this field needn't be present if there is only one ContentEncoding. The order in which the ContentEncoding elements appear in the file is irrelevant.
ContentEncodingType: It's default value signifies compression (the other value is encyption), so this is usually not present.
ContentEncryption: If ContentEncodingType is set to encyption, this field has to be present; otherwise its absent.

As a second example, the relevant header field for Compressed.mks is:
```
6D 80 86 62 40 83 50 34 80
```
0x6D 80 again means ContentEncodings; 0x62 40 ContentEncoding; 0x50 34 means ContentCompression. Here ContentCompAlgo, ContentEncodingType, ContentEncodingScope and ContentEncodingOrder have their default values (implying zlib, compression, all frame contents (and not CodecPrivate), and 0 (the ContentEncoding described here has been applied first and therefore has to be reversed last)).

**Comment by mkver** [comment]
Thanks that you are still on this. It is also possible that only the private data are compressed. [Here](https://www.dropbox.com/s/1fl9t1vzw4yg3u3/compressed.codec.private.uncompressed.data.mks?dl=0) is a sample file for this. And here is the result I get from the current beta version (according to the timestamps in the archive this version is from today 14:06, so it should include your last commit):
![se error2](https://user-images.githubusercontent.com/18448094/30274308-26efb124-96fd-11e7-87d8-28808ee72b5f.png)

**Comment by niksedk** [comment]
thx a lot for all the info and the sample files :)
New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

I would like to see more sample files :)
"Header stripping" can be used with subtitle tracks?

**Comment by mkver** [comment]
Header stripping can be used with subtitle tracks, but it isn't used. And it is unlikely to be used for it at all. (One exception could be situations in which every subtitle packet starts with e.g. "<font color="#".) (The packets of several codecs always begin with the same data -- a syncword and sometimes also with some other stuff that doesn't change from frame to frame. Header stripping strips this away from the packets and puts it once into the header. This is especially worthwhile with dts -- if you do it with dts, the Matroska container overhead usually becomes negative. Unfortunately a lot of (hardware) players don't support it. Moritz Bunkus tried to popularize this feature by making it the default in MKVToolNix, but there were so many complaints that he backtracked.)
