### ISSUE TITLE
Different types of Netflix TTML not handled properly (position tags)

### ISSUE THREAD

**Issue by Mlmlte** [SubtitleEdit/subtitleedit#2567]
Hi Nikse,

I used to convert Netflix subs to SubRip (.srt) with an old version of SE back from 2015 (3.4.7 or something) only to notice recently that it was simply ignoring italics and position tags.

Anyway, I figured I should update to the latest version to have those tags properly converted as well.

On version 3.5.3, "old Netflix" subs are handled just fine, e.g. with this format:

```
<p begin="796400000t" end="851200000t" style="normal" xml:id="subtitle13">
<p begin="862400000t" end="876400000t" region="top" style="normal" xml:id="subtitle14">
```

Subtitle 13 has no tag and subtitle 14 has an {\an8}, just as you would expect.

However, with more recent subs from Netflix, such as this format:

```
<p begin="513429582t" end="533866666t" region="region.before" style="defaultStyle_1" xml:id="subtitle10">
<p begin="534700832t" end="553469582t" region="region.after" style="defaultStyle" xml:id="subtitle11">
```

Subtitle 10 is supposed to be shown on top with {\an8} and subtitle 11 on bottom with no tag, but SE processes the whole file as if each subtitle was to be shown on top, and each subtitle has an {\an8} tag, which is completely wrong.

Same goes with a slightly different format that I've come across as well:

```
<p begin="1170400000t" end="1226400000t" region="region.bottom.centre" style="style.default" xml:id="subtitle33"
<p begin="2405600000t" end="2432400000t" region="region.top.centre" style="style.default" xml:id="subtitle34">
```

Is there any way you could take these variations into account?

Thanks a lot, SE is a wonderful tool :)

**Comment by niksedk** [comment]
Hi Mlmlte,

Could you show the `head` tag for the two samples above as well?

**Comment by Mlmlte** [comment]
Sure thing, here it is: 

**First sample**
```
<head>
<ttp:profile use="http://netflix.com/ttml/profile/dfxp-ls-sdh"/>
<styling>
<style tts:color="white" tts:fontSize="100%" tts:fontWeight="normal" tts:textAlign="center" xml:id="defaultStyle"/>
<style tts:color="white" tts:fontSize="100%" tts:fontWeight="normal" tts:textAlign="center" xml:id="defaultStyle_1"/>
<style tts:color="white" tts:fontSize="100%" tts:fontStyle="italic" tts:fontWeight="normal" tts:textAlign="center" xml:id="defaultStyle_2"/>
<style tts:color="white" tts:fontSize="100%" tts:fontStyle="italic" tts:fontWeight="normal" tts:textAlign="center" xml:id="defaultStyle_3"/>
</styling>
<layout>
<region tts:backgroundColor="transparent" tts:displayAlign="after" tts:extent="80.00% 80.00%" tts:origin="10.00% 10.00%" xml:id="region.after"/>
<region tts:backgroundColor="transparent" tts:displayAlign="before" tts:extent="80.00% 80.00%" tts:origin="10.00% 10.00%" xml:id="region.before"/>
</layout>
</head>
```

**Second sample**
```
<head>
<ttp:profile use="http://netflix.com/ttml/profile/dfxp-ls-sdh"/>
<styling>
<style tts:backgroundColor="transparent" tts:color="white" tts:fontSize="100%" tts:fontWeight="normal" xml:id="style.default"/>
<style tts:backgroundColor="transparent" tts:color="white" tts:fontSize="100%" tts:fontStyle="italic" tts:fontWeight="normal" xml:id="style.default_1"/>
</styling>
<layout>
<region tts:displayAlign="after" tts:extent="80.00% 80.00%" tts:origin="10.00% 10.00%" tts:textAlign="center" xml:id="region.bottom.centre"/>
<region tts:displayAlign="before" tts:extent="80.00% 80.00%" tts:origin="10.00% 10.00%" tts:textAlign="center" xml:id="region.top.centre"/>
</layout>
</head>
```

**Comment by Mlmlte** [comment]
If that's of any help, I've implemented it in Python here: [https://github.com/Mlmlte/netflix-to-srt/blob/master/to_srt.py]

**Comment by niksedk** [comment]
Your headers look wrong to me... you have `tts:origin="10.00% 10.00%"` for both top and bottom style, but 10% 10% will display both at top, right?

**Comment by Mlmlte** [comment]
It is 100% correct. It's `tts:displayAlign` that really matters here...
I guess `tts:origin` is only applied/taken into account **after** `tts:displayAlign`.
Have a look at the format specifications: https://www.w3.org/TR/ttaf1-dfxp/#style-attribute-displayAlign

**Comment by niksedk** [comment]
Ah, yes - thx :)
I know the links, but I think I might have missed the before/after meaning (also not very clearly explained on w3.org).
New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
Are the positioning tags handled better now?

**Comment by Mlmlte** [comment]
@niksedk Positioning tags are indeed handled properly now, thanks! You seem to add unnecessary `<font color="white">` tags now though
