### ISSUE TITLE
A colon character detected incorrectly by OCR

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2569]
[Latin.zip](https://github.com/SubtitleEdit/subtitleedit/files/1294622/Latin.zip)
[tng_s03e01.zip](https://github.com/SubtitleEdit/subtitleedit/files/1294624/tng_s03e01.zip)

A colon is somehow detected as 'ff'. Settings are 11 pixels for space, 2,0% max error. SE 3.5.3 build 252.

**Comment by niksedk** [comment]
Nice catch!
Seems to be a regression from c9337ad33d969afd9f17234ff46c48102296f100 - should be okay now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
