### ISSUE TITLE
"Whole Word" option in replace window.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2570]
to search for exact words and replace them not just parts of words.

**Comment by OmrSi** [comment]
It us available in Word and every other program.

**Comment by OmrSi** [comment]
![screenshot_20170913-160539](https://user-images.githubusercontent.com/20923700/30378972-a9cd8552-989d-11e7-9580-3e990c347dc6.png)

**Comment by OmrSi** [comment]
Haven't you found the time for this?

**Comment by niksedk** [comment]
It's available in Edit -> Multiple replace... via regex.

**Comment by OmrSi** [comment]
nope
regex is not like "whole word"
it is available in Find but not in Replace

**Comment by OmrSi** [comment]
Arabic and many other languages doesn't have "cases".
for example, i want to change "علي" to "عليّ", if i use replace all it will change every word which contains the three letters "علي" like "عليها" or "عليه" for example, but if you have a "Match Case" option, it would only change the word "علي".
that is my point/problem.

**Comment by OmrSi** [comment]
؟؟

**Comment by niksedk** [comment]
Have you tried the "\b" around a word in multiple replace, e.g. "\bWord\b" ?

**Comment by OmrSi** [comment]
in regex, yeah.
wouldn't it be easier to add the option like the one in Find?

**Comment by niksedk** [comment]
It's not super-easy to code... but could you test this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
works like a charm. :)

**Comment by OmrSi** [comment]
Thank You.
