### ISSUE TITLE
Words all stick together even though pixels space is already set to "1"

### ISSUE THREAD

**Issue by maivutan** [SubtitleEdit/subtitleedit#2572]
This happens after I _Import text with matching time codes..._ to continue from a previous progress. I have to set _No of pixels is space_ to **3**, run, then set it back to **1** as a workaround.

http://somup.com/cbQIjaVom6

I am using **Subtitle Editor 3.5.3.**

**Comment by niksedk** [comment]
Did you already forget #2571?
Use the custom colors :)
