### ISSUE TITLE
Italics handled a bit incorrectly

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2573]
During OCR with binary image compare, some italics cause issues.

For example, this subtitle has the latter part embedded as italic, but the actual detection had found out that the two dashes are italic. Well, they are not but as you can see from the image, it is impossible to say if it's italic or not :)
`230
00:15:54,287 --> 00:15:55,914
I had-- <i>Uh--</i>`

![image](https://user-images.githubusercontent.com/11799308/30657981-f88245c6-9e41-11e7-9801-f1a147a22058.png)

**Comment by Boulder08** [comment]
Maybe sort this one out by not embedding the attached word inside the italic tags if some special characters like the dash are the only ones detected as italic.

**Comment by niksedk** [comment]
Is this beta version better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by Boulder08** [comment]
Yes, seems to work nicely on that particular subtitle. Lots of lines with --'s and they are now correctly parsed as normal text.
