### ISSUE TITLE
Add support for DeepL translations

### ISSUE THREAD

**Issue by ducedo** [SubtitleEdit/subtitleedit#2574]
[DeepL](https://www.deepl.com/translator) is the new translation star allegedly outperforming Google Translate. Unfortunately there's still no official API but there's an inofficiell API with several projects on Github using it.

Example: [DeepLy](https://github.com/chriskonnertz/DeepLy)

Would it be possible to add support for DeepL with automatic translations?

**Comment by niksedk** [comment]
I made a quick test - try unpacking this file ( https://github.com/SubtitleEdit/plugins/releases/download/v.1.1/DeeplTranslate.zip ) in your SE plugin-ifolder ( see File -> Plugins -> show plugin folder ).
A new menu item should appear in the "Translate menu" - how does that work?

**Comment by ducedo** [comment]
Thank you, I'm amazed by the quick work. The new menu item and popup window with translation seems to work great. The only thing is that when I click 'ok', the translation replaces the original text. In contrast, when you use Google Translate, you get the new/old subtitles side by side so you can continue to merge lines and make changes without ending up with two completely different files.

I'm not sure if it's due to how the plugin works or if I'm doing it wrong.

**Comment by ukushu** [comment]
Link is dead, where I can find this plugin?

**Comment by niksedk** [comment]
Try File - Plugins - Get plugins...

**Comment by ukushu** [comment]
There is only DeeplPro translate plugin, but no DeeplTranslate plugin displayed

**Comment by niksedk** [comment]
Yes, the "Deepl Pro translate" plugin is the one to use.

Note that you must create an API key (which is free - allows up to 500,000 characters per month)
https://www.deepl.com/en/pro/change-plan#developer
