### ISSUE TITLE
Error while downloading language

### ISSUE THREAD

**Issue by DeBeerVanWelleer** [SubtitleEdit/subtitleedit#2578]
![afbeelding](https://user-images.githubusercontent.com/32341774/30932961-6c59ac46-a3c9-11e7-9128-b3b75156daf5.png)

**Comment by niksedk** [comment]
Could you test if this has been fixed in latest portable beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip ?

**Comment by ExYuSubs** [comment]
I have some another issue, Nik,

https://s1.postimg.org/2jt305z3m7/Screenshot_2.jpg
https://s1.postimg.org/3tw06hhicv/Screenshot_4.jpg

it works latest 4-5 days, but from today is problem

**Comment by niksedk** [comment]
@ExYuSubs: What happens in Subtitle Edit 3.5.4?

**Comment by niksedk** [comment]
@ExYuSubs: New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

About the blank lines, check the faq: http://www.nikse.dk/SubtitleEdit/Help#issues

**Comment by ExYuSubs** [comment]
Sorry Nik for a late answer, I have reinstalling my windows, and now working everything OK

**Comment by niksedk** [comment]
@ExYuSubs: Super :)
