### ISSUE TITLE
Adjust time of selected lines by "Set start and off-set the rest (F9)" 

### ISSUE THREAD

**Issue by F5System** [SubtitleEdit/subtitleedit#2580]
It would be great if it will be possible to adjust time of **selected** lines by:

1.  stand on desired start time of first subtitle of this selected lines in wave-form monitor or video-player timeline
2. and press "Set start and off-set the rest (F9)" button

This way selected lines will start from your desired time. If they overlap next/previous lines, it's ok, this is the logic*.

Because now the only way I see to do it, is to:

1. Select lines
2. Go to "Adjust all times"
3. Choose "selected lines only" and set some small time like "0:00:00:01"
4. And then press "Show earlier/later" till your selected subtitles go into right start position.
*This way they will also overlay next/previous subtitles if they don't move.

**Comment by OmrSi** [comment]
You can do this by:
1. Select the lines you need.
2. Cut those lines.
3. Click where you want the lines to start on the waveform.
4. Paste the lines.
The lines will be pasted starting from the time on the waveform.
