### ISSUE TITLE
Auto break and lyrics

### ISSUE THREAD

**Issue by SvenErik1968** [SubtitleEdit/subtitleedit#2583]
It is not a big issue, but would it be possible to have a setting that when enabled would get the editor to ignore ♪ lines enclosed by ♪ when using auto break on multiple lines?

Text lines with lyrics are usually formatted in verse form according to how they are sung, and usually don't follow a _"normal"_ sentence structure, and auto break will often "mess up" this formatting.

**Comment by niksedk** [comment]
Thx for the info - portable beta version updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip :)

**Comment by SvenErik1968** [comment]
Thanks!

Tested it on a short "manufactured" subtitle with both long lines of normal text and lyrics and it does not break the lyrics, but the line break position is not optimal if you have a mixed case string with both lyrics and normal text as you can see on this test string below:

Test string:
```
♪ It's her! I know it's her! It's her! I know it's her! ♪
She wants to tell us something! She wants to tell us something!
```
Ends up like this after auto break:
```
♪ It's her! I know it's her! It's her! I know it's her! ♪ She
wants to tell us something! She wants to tell us something!
```

Also tested with the split line function and it ends up like this:
```
♪ It's her! I know it's her! It's her!
I know it's her! ♪ She

wants to tell us something! She
wants to tell us something!
```
A more preferable split of this text would be:
```
♪ It's her! I know it's her! It's her! I know it's her! ♪

She wants to tell us something!
She wants to tell us something!
```

**Comment by niksedk** [comment]
Beta updated again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/31034431-61af03bc-a564-11e7-9cd2-b12ab2e7b7a9.png)

**Comment by SvenErik1968** [comment]
Much better now, only "nagging" detail is that the split line function adds a line break in the lyrics, but I can live with that if the line is too long. ;-)

And BTW, thanks for making this great tool! I use it a lot!
