### ISSUE TITLE
Importing time code after saving in different format

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2585]
Hey. Once again, this isn't urgent, but I just thought I'd point it out.
Open a subtitle file (SRT in my case) and save it in a different format (e.g. PE2). Import time codes into it. Now save, either via keyboard shortcut or file->save. The file should just save normally, but instead SE pops up the "save as" dialog box.
![se-time-codes-after-format-convert](https://user-images.githubusercontent.com/19672444/31046738-99a6796a-a606-11e7-8cef-e4a66a8d078d.gif)

**Comment by darnn** [comment]
Thank you! Has the beta been updated?

**Comment by niksedk** [comment]
Now it has: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

Nice issue (small, but annoying) to get fixed before the release :)

**Comment by darnn** [comment]
Thanks! :)
