### ISSUE TITLE
Strange OCR misdetection

### ISSUE THREAD

**Issue by mkver** [SubtitleEdit/subtitleedit#2586]
I'm experiencing a strange OCR misdetection: "Hey." (without "") is wrongly detected as "He)'-", but only if I use Tesseract with German trained data and a German dictionary for OCR auto-correction. [Here](https://www.dropbox.com/s/7m7k5i946gj0s95/Hey.mks?dl=0) is the file.
The strange thing is that this doesn't seem to be clearly attributable to either the OCR or the autocorrection phase: If I use Tesseract with German trained data and no dictionary or an English dictionary, then it is correctly detected as "Hey."; if I use Tesseract with English trained data and either an English or a German dictionary, it is correctly detected, too. So only the combination German trained data + German dictionary (or Austrian German or Swiss German (in this case it gets autocorrected to "He)'-.")) fails for some reason. It doesn't matter if I enable italic or let it search for the music symbols.
Binary image compare works with any dictionary.
I tested this with beta 3.5.3.302.

**Comment by darnn** [comment]
For what it's worth: Have you tried testing this outside Subtitle Edit with just a Tesseract build? If it happens there too, you might try asking on the Tesseract forums, they were pretty active last time I looked at them.

**Comment by niksedk** [comment]
Hm, it seems that Tesseract find two hits: "Hey." and "He)-". For the German dictionary the first "Hey" is an unknown word but "He" is known, so "He)-" wins...
