### ISSUE TITLE
Unbreak when lines are less than number of characters allowed in on line

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2589]
Hey. I work for a Company, and they use Netflix guidelines
so, you can have 42 characters in one Line and the Line can have two lines
but if the number of letter in a Line is less than or equals 42 they have to be in one line
so, is there a way to unbreak Lines that are less or equal the number of letter you select?

**Comment by ivandrofly** [comment]
Have you tried the plugin **Lines Unbreaker**?

**Comment by OmrSi** [comment]
Oh! Didn't see it before 
Works great :)
Thank you for the osm job.
Could you let it save my choice?
like keep "Skip Dialog" not selected and save the number of letters?
Maybe it can take the number from the selected Man Char per line from settings?

**Comment by OmrSi** [comment]
And if i want it to be 42 after breaking what is the number i should choose?

**Comment by ivandrofly** [comment]
> And if i want it to be 42 after Unbreaking what is the number i should choose?

What do you mean 😕 ?

To unbreak if line is lesser or equal to 42 characters? 🤔 

Ps: please close this and use the plugin issue instead

**Comment by OmrSi** [comment]
Yeah, I seem to have to use 43, does it consider the line break as a letter?
