### ISSUE TITLE
MPV Issues, Tag/Font Size/position problems

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2590]
positions on screen and coordinates are wrong now, and the font is too small
Here is an example:
![untitled](https://user-images.githubusercontent.com/20923700/31090497-78edf558-a7b0-11e7-8f7a-3720dbcf42f2.jpg)

this tag was positioned perfectly in an old beta version of 3.5.3
when i used the new version the position changed and is wrong now.
Here it is in VLC:
![untitled](https://user-images.githubusercontent.com/20923700/31090572-b73261a0-a7b0-11e7-8167-3e5eb86b6b5b.jpg)

and if i fix in SE it gets corrupted in the video player...

Sorry for not reporting earlier, but have tested the latest beta in a while before launching the new version

**Comment by OmrSi** [comment]
Another thing now is font size, 25 was big and i use it to review subtitle
now it is small, like 10 in old versions.

**Comment by OmrSi** [comment]
This is 25 in VLC:
![untitled](https://user-images.githubusercontent.com/20923700/31093830-a78bdcd0-a7bb-11e7-8117-6d0040eaf9ee.jpg)

In mpv:
![untitled](https://user-images.githubusercontent.com/20923700/31093906-eaccb2ee-a7bb-11e7-9302-4e7a6f91628c.jpg)

**Comment by OmrSi** [comment]
Try using {\pos(80,200)} and see the difference between any player and mpv in SE.

**Comment by darnn** [comment]
I've actually been holding off on reporting this because it doesn't affect me as much, but for now, a simple workaround:
![se-mvp](https://user-images.githubusercontent.com/19672444/31094854-3bda4c98-a7bf-11e7-85c0-1e5e67260fd1.gif)

**Comment by OmrSi** [comment]
Aha!
I need this for QC, i need the large font for reviewing the subtitle.
And the position for translating other things, was working on a file today, when tried to continue i found that position tags are not in the write place as before.

**Comment by OmrSi** [comment]
By the way, the workaround didn't work on the file i'm working on...

**Comment by darnn** [comment]
Huh. Well, here are some other things that work for me:
Show/hide waveform
Show/hide video (while waveform is visible, otherwise this one has no effect)
Maximize/restore down the window (i.e. that middle button in the titlebar, between minimize and exit)
And, if you go into settings, even if you change nothing and cancel. If none of those work, I would assume that changing away from MVP and back to it should work.

**Comment by OmrSi** [comment]
Nope. Still the same.
Font is small, position tags is wrong...
you think it was because of this:
https://github.com/SubtitleEdit/subtitleedit/commit/53c0737e76b8170957fcf26e5130b2564ebe92c4
??

**Comment by darnn** [comment]
I would wager that it isn't, since it's been doing that for me since I switched to MPV. But on the other hand it seems to behave differently for you than it does for me, so maybe the thing that's happening to you _was_ affected by that.

**Comment by darnn** [comment]
Also, maybe try disabling and then enabling "mpv handles preview text" in the video settings?

**Comment by OmrSi** [comment]
Nope. Not working.
Tell you what, try in the latest version, writing a sentence with the tag {\pos(80,230)}
and see how it is different between MPV and if you opened the video file outside SE.
it used to be the same, now it is not.

**Comment by darnn** [comment]
You're right, it is different. And if I do it in an older beta, 3.5.3 build 278, it's roughly where it is in MPC for me, unlike in the latest build.

**Comment by OmrSi** [comment]
Exactly.
after a certain Beta it got corrupted.

**Comment by OmrSi** [comment]
Could you upload the beta you have for me? 
I don't have an old beta, and this is really bugging me while working…

**Comment by darnn** [comment]
I knew saving them would come in handy one day!
https://www.dropbox.com/s/cnn09frzyv1f80e/SubtitleEditBeta%20%2852%29.zip?dl=0

**Comment by OmrSi** [comment]
Great! Thank You. 😄
Hope he can fix it soon…

**Comment by OmrSi** [comment]
@niksedk ?

**Comment by darnn** [comment]
Could you update the beta? I'd like to see if this gets rid of my issue as well (i.e. the video opening initially with a black bar for the subtitles, even though they're supposed to be overlaid on it, as can be seen in the gif I posted).

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Thank you! This didn't fix my version of this, unfortunately. I'll open an issue of my own.

**Comment by OmrSi** [comment]
@darnn BTW, the problem you're having happens with me too.
but i usually just ignore it...

**Comment by darnn** [comment]
Yeah, I mean, I've been doing what I described earlier, which makes it go away, but it would still be a nicer experience without it.

**Comment by OmrSi** [comment]
Exactly.
just did what you said about it, and it worked.
but, would be better without it...
