### ISSUE TITLE
Trend Micro Internet Security

### ISSUE THREAD

**Issue by SvenErik1968** [SubtitleEdit/subtitleedit#2591]
Just installed the latest version of SubtitleEdit, and had just started to do an OCR of a vobsub when the program was terminated by Trend Micro and reported as a ransomware threat.

Tested both the installer and the [program on VirusTotal](https://www.virustotal.com/#/file/e485848df2de8aa9879b0d6daf7979885f14b25258d60f02be4c8c4fda8fdb3e/detection) and all the test was green.

The program runs after I unblock it, but seems there are still problems with false AV positives.

**Comment by niksedk** [comment]
OK, I've reported the issue to Trend Micro

Not the first time... https://github.com/SubtitleEdit/subtitleedit/issues/2271

**Comment by niksedk** [comment]
@SvenErik1968: Any news on this? What file is Trend Micro complaining about exactly? 
Both SubtitleEdit.exe and Tesseract.exe (called during OCR via Tesseract) are happy on https://www.virustotal.com

**Comment by SvenErik1968** [comment]
I also tested it on Virustotal with all the test in green.

Here is the report inside Trend Micro and the CSV export from it (I had just started doing an OCR of a vobsub at the time):

> Name: | subtitleedit.exe
> From: | Nikse
> Version: | 3.5.4.0
> Copyright: | Copyright 2001-2017, Nikse
> Detected Resource or Process ID: | c:\program files\subtitle edit\subtitleedit.exe
> Response: | Terminated
> Changed Files: 
> 6ba8fe9b-e13d-47e7-9921-379a31587e06.html
> 8c2d0f5f-1520-4fdc-af44-2d8973837284.html
> bfc3fde7-f7ee-4ae7-b4b5-0e938e315bc3.html


[Ransomware.csv.txt](https://github.com/SubtitleEdit/subtitleedit/files/1353565/Ransomware.csv.txt)

**Comment by niksedk** [comment]
Close as it's more a "Trend Micro" issue...
