### ISSUE TITLE
Persian words are not true

### ISSUE THREAD

**Issue by NoRRt** [SubtitleEdit/subtitleedit#2592]
Persian words are not true 
See :
https://img2.brain4.photobox.com/3762942844117bc3f2b63e2db9bbe894280a73cf9ee65271b44412bfa740051192a7f551.jpg

**Comment by niksedk** [comment]
What happens if you OCR the image via command line and Tesseract 3.02?
I think this is a Tesseract issue which probably only will improve when Tesseract 4 is out.
