### ISSUE TITLE
Windows Forms Thread Exception - Open subtitle to append

### ISSUE THREAD

**Issue by Sopor-** [SubtitleEdit/subtitleedit#2594]
I was trying to append a subtitle but i selected the video file instead of the subtitle and then i got this message

![image](https://user-images.githubusercontent.com/5789283/31140096-c3ac2d1c-a873-11e7-8998-23a89911a788.png)

I know i selected the wrong file but it shouldn't hang like this. After i pressed the Abort button the `SubtitleEdit.exe` was locked even if i couldn't find any task running in the task manager.

**Comment by niksedk** [comment]
What's the size of this video file?

**Comment by Sopor-** [comment]
It was an mkv file at 2 252 743 972 bytes
