### ISSUE TITLE
Find\Replace whole word Error.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2595]
when using Whole Word in Find\Replace
if there was something after the word like an Arabic apostrophe or question mark, it doesn't find it...
For example if i'm searching for "الموسيقا" and there was an "،" or "؟" After it, it sees them as part of the word and therefore doesn't find them.
But it does find them when using Regex...

**Comment by niksedk** [comment]
Thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk Thank you so much for all the hard work :)
hope i'm not bothering you with these thing.

One last thing, can you check the problem darrn mentioned in [this](https://github.com/SubtitleEdit/subtitleedit/issues/2590) problem
The original problem about font number was solved.
he talked about another one that is facing me too and posted a [gif ](https://github.com/SubtitleEdit/subtitleedit/issues/2590#issuecomment-333636074)about it
Thanks a lot. :)

**Comment by niksedk** [comment]
np, it nice to get these bug fixed :)

I don't understand the problem about mpv...

**Comment by darnn** [comment]
Oh, damn, I wrote an entire new issue about it, but I think I just hit "preview" and never posted it. I'll go do that.

**Comment by OmrSi** [comment]
@darnn That would be better, hope you can retrieve what you lost...
