### ISSUE TITLE
Video issues when MPV is selected as the video engine and handles preview text

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2597]
Okay, so, briefly, since I already wrote all this up and failed to actually submit:
Make sure MPV is selected and "mpv handles preview text" is checked. Clear any open video, close SE and open it again. Open a video file. It will look like this:
![se-mpv-blackbar01](https://user-images.githubusercontent.com/19672444/31253486-d4bcd424-aa2d-11e7-9201-205e18f66d6b.png)
This is what it would have looked like if MPV had not been selected and SE needed that black bar to display subtitles in, but it's unnecessary since with these settings SE overlays the subtitles on the video.
Then, do any of the things I describe here: https://github.com/SubtitleEdit/subtitleedit/issues/2590#issuecomment-333645104
For instance, go into options->settings and then click cancel. The video now fills the entire video pane properly:
![se-mpv-blackbar02](https://user-images.githubusercontent.com/19672444/31253596-30b1eecc-aa2e-11e7-804a-849a14bcfa94.png)
Note that this happens with every new "instance" of the video player that is invoked, such as in visual sync, where there are two of them:
![se-mpv-blackbar03](https://user-images.githubusercontent.com/19672444/31253654-5ba351fc-aa2e-11e7-8783-7a38a50e0b4d.png)

In fact (and I'm not sure how to reproduce this, but I think it would be solved along with the rest of this), sometimes when I open visual sync with MPV, one of the video players will open in a separate window altogether. I don't have a screenshot, sadly, but it's, like, the video on the left looks the same, and the one on the right, in the visual sync window, is just totally black, and a new window with just video appears over it, like the one you get if you undock video controls, except it has a purple icon on it somewhere. Again, sadly, I don't have a screenshot of this, but I think it would resovle itself along with the rest of this.

Edit: For what it's worth, I followed a hunch, and that purple icon I was talking about is indeed found inside of mpv-1.dll:
![se-mpv-icon](https://user-images.githubusercontent.com/19672444/31254000-9265e4d8-aa2f-11e7-9222-df879ee1af43.png)

**Comment by OmrSi** [comment]
yep, that happens with me sometimes, opens in a whole separate windows, don't know when. it's almost random.
as for the black bar. i have the same thing here.
when i open a video, sometimes i get a Black Bar 
![untitled](https://user-images.githubusercontent.com/20923700/31280365-c7e3aa0c-aab4-11e7-9c44-0c7b8f610794.jpg)

Then when i do any of the things mentioned it Darnn's comment it becomes whole and the black bar is gone:
![untitled](https://user-images.githubusercontent.com/20923700/31280391-db8b22e2-aab4-11e7-88db-08db5bf760d4.jpg)

**Comment by OmrSi** [comment]
@niksedk I just opened a video file and it has this issue
is there a log file i can send to see what happens when i do some of thing @darnn mentioned and it gets fixed?

**Comment by OmrSi** [comment]
![untitled](https://user-images.githubusercontent.com/20923700/31405173-ecaf156a-ae06-11e7-814f-92db905844ca.jpg)

**Comment by niksedk** [comment]
thx for the info :)

I've re-created the issue and it seems to be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

I've seen the mpv separate window a few times when running from visual studio, but thought it was a development issue only - I've make a hack for this in above beta (just sets the window 3 times...), so do let me know if it happens again!

**Comment by darnn** [comment]
The black bar is indeed gone, but I'm afraid the video popout is still happening, and I've even had it happen in the main window with this build:
![se-mpv-3win2](https://user-images.githubusercontent.com/19672444/31447322-6274880e-aeaa-11e7-9739-73a106e468ee.png)

**Comment by niksedk** [comment]
OK, is this better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
How do you make this happen?

**Comment by darnn** [comment]
It still happens, I'm afraid. And there aren't specific steps to reproduce it, I just open SE, drag-and-drop a video into the video player, if it opens okay I go to visual sync, and if the two instances there open okay too, I close SE and start over. After 5-10 times the video will pop out during one of those stages.

**Comment by niksedk** [comment]
I've tried like 50 times with not failures... but new beta up which tries to re-attach the video 1 second after player is loaded, so I hope this might improve things?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
i tried 10 times, nothing happened here either...

**Comment by darnn** [comment]
It's less frequent, especially in the main window, but I'm afraid it still happens... I can record my screen but I assume that wouldn't help you reproduce it. If there's any kind of hidden verbose log mode or anything, I could get it to happen and then send you the log, but otherwise I'm at a loss.

**Comment by niksedk** [comment]
I've given it another try - libmpv returns a code which is zero if everything is okay - in latest beta SE now retries up to 25 times to set video window: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
Better?

( read about the libmpv c api here: https://github.com/mpv-player/mpv/blob/master/libmpv/client.h )

**Comment by darnn** [comment]
It still happens, alas. And the libmpv api stuff is way too complicated for me, unfortunately. I'll just have to learn to code myself eventually, then maybe I'll be able to make some sense of it.

**Comment by niksedk** [comment]
OK, if you re-download libmpv from options -> settings -> video player - does that help?
(you'll get a newer version of libmpv)
