### ISSUE TITLE
Tweak to Fix missing spaces

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2601]
Fix missing spaces should also suggest fixing this kind of cases where there are two numbers separated by a colon.

`28
00:01:32,301 --> 00:01:33,803
It's 2: 10.`

Maybe this could also be tweaked accordingly:
`1
00:00:09,260 --> 00:00:13,472
<i>Captain's log, stardate 44502. 7.</i>`

**Comment by OmrSi** [comment]
@niksedk This is fixed.
