### ISSUE TITLE
Another timing issue in translator mode : (

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2602]
Latest beta. I don't even know what's causing it this time, but it's the same problem I always have - the text in the original file starts disappearing as soon as I insert new lines.
I'm attaching the file this happens with:
[wpt13 15 EE648815 ENG3 - se test.zip](https://github.com/SubtitleEdit/subtitleedit/files/1373477/wpt13.15.EE648815.ENG3.-.se.test.zip)
Just open it in SE, use tools->make new empty translation, go down to the fourth line in list view, and press the keyboard shortcut for "insert line after". The first three lines now disappear. Gif:
![se-timing-translator mode](https://user-images.githubusercontent.com/19672444/31411542-a26df4d0-ae1a-11e7-9a34-a7bec2786fa1.gif)

**Comment by darnn** [comment]
To be even more specific, here is the original file:


27:23:40,000 --> 27:24:00,000
.'Cause we know all the best games are here

2
27:25:40,000 --> 27:26:00,000
...All the big names are here to play as well, so

3
27:27:40,000 --> 27:28:00,000
.Whatever your stake is, whether it's one-two or 500,000, it's here

4
27:29:40,000 --> 27:30:00,000
.You just don't even think about anywhere else to go, you just come straight here

5
27:31:40,000 --> 27:32:00,000
.Well, that's the very talented Joe Hachem, always entertaining

6
27:33:40,000 --> 27:34:00,000
!But right now, the heads-up battle continues and what a turnaround

7
27:35:40,000 --> 27:36:00,000
.Mohsin Charania, now, he's got 16.5 million

8
27:37:40,000 --> 27:38:00,000
.Garrett Greer, now, down to a million

Here is the original file from translator mode, after inserting a blank subtitle:

1
27:23:40,000 --> 27:24:00,000
.'Cause we know all the best games are here

2
27:25:40,000 --> 27:26:00,000
...All the big names are here to play as well, so

3
27:27:40,000 --> 27:28:00,000
.Whatever your stake is, whether it's one-two or 500,000, it's here

4
27:29:40,000 --> 27:30:00,000
.You just don't even think about anywhere else to go, you just come straight here

5
27:31:40,000 --> 27:32:00,000
.Well, that's the very talented Joe Hachem, always entertaining

6
27:32:00,002 --> 27:32:02,002


7
27:33:40,000 --> 27:34:00,000
!But right now, the heads-up battle continues and what a turnaround

8
27:35:40,000 --> 27:36:00,000
.Mohsin Charania, now, he's got 16.5 million

And here is the newly-created translation file after inserting a blank subtitle - you can see the timecodes have changed for some reason.

**Comment by niksedk** [comment]
New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
Better?

27+ hours? I hope it's a good video :)
SE in HHMMSSFF time code mode only worked to 23 hours... now it should be a little better but SE will max support up to 99 hours.

**Comment by OmrSi** [comment]
I guess it won't work for [Ambiancé](http://www.imdb.com/title/tt3854496/)
It's 720 hours. Haha!

**Comment by niksedk** [comment]
You can change "Time code mode" via Options -> Settings -> General

**Comment by darnn** [comment]
It wasn't actually 27 hours, thankfully, I was just messing around with the parameters of importing plain text. I needed large gaps between individual subtitles, because I tend to import things that require me to add a bunch of subtitles in between them, and if the gaps are small, SE creates subtitles that have negative timecodes, or just the same timecodes, which causes certain things to behave strangely.

Anyway, this is all to say that it's fixed now! Thank you!

**Comment by niksedk** [comment]
Cool, thx for reporting + testing :)
