### ISSUE TITLE
Waveform extraction runs forever, fills up the disk

### ISSUE THREAD

**Issue by ThiefMaster** [SubtitleEdit/subtitleedit#2603]
I had this happen with various series (all mkv files). After ~5 minutes of extractions I already have more than 5GB of audio data. In the past it took much less time so I have the strong feeling that it's extracting data forever instead of stopping when reaching the end of the video.

I am *not* using ffmpeg for the waveform extraction and I'm on Windows 7. Subtitleedit version is 3.5.4.
Let me know if you need more information to debug this.

**Comment by niksedk** [comment]
What version of VLC do you use?

**Comment by ThiefMaster** [comment]
2.2.6 - I actually updated not too long ago so this might have caused the problem.

**Comment by niksedk** [comment]
Could you try with an earlier version - if that works I guess we should report the issue to VLC.

**Comment by 8543** [comment]
Hi! Suffer actually the the problem. SE doesn't create waveforms anymore. Tried several versions on several videos - even those, which worked with SE easily...
But: Waveforms folder doesn't contain anything at all nor is filling up...
Spec: Windows 10 Home (1709), i7, 16 GB RAM), tested SE versions: several from 3.4.5 (installed and stand-alone)

**Comment by niksedk** [comment]
Do you use VLC for audio wave extraction?
What version of VLC do you use?
Could you try an earlier version of VLC?
Could you upload a small video file somewhere that does not work?

**Comment by 8543** [comment]
Hi Nik,

thanks for the quick answer. Just wrote you an email as well.
My VLC is the latest: 2.2.6 (32-bit)
Never used VLC for audio extraction, didn't know that this is even possible...
Okay, will try to find an earlier version of VLC.
Could it be my recent installation of the MPC-HC (64-bit) as well?

**Comment by 8543** [comment]
Obviously uninstalling MPC-HC helped, or maybe it could be also the reinstalling of the mpv lib... but now the beast is working again ;-)
