### ISSUE TITLE
Feature Suggestion: cut segments from video/audio with caption auto-realign

### ISSUE THREAD

**Issue by alexpmorris** [SubtitleEdit/subtitleedit#2605]
We have a workflow where we combine the subtitles from multiple speakers and combine them all into a single VTT file (it's been released as my srt2vtt project).  However, the combined video/audio file often has areas that we would like to splice out, while still maintaining the integrity of our caption file.  

In the same way we can highlight a caption on the audio/video timeline in **Subtitle Edit**, it would be even more powerful if we could **remove** those segments from the underlying video as well, and when we're done, save the updated video/audio along with its updated caption file that reflects all the removed audio/video segments.

If it's too tricky to include all this directly into **Subtitle Edit**, perhaps it may be enough to simply write out the segments to remove and run them through ffmpeg as done in this project: https://github.com/mifi/lossless-cut *(Cross platform GUI tool for lossless trimming / cutting of video and audio files using ffmpeg)*.

As a slight addition to this, it would also be great if we could split the video+audio+captions as well.  For example, if we have 4 interviews in an hour of video, we could split the video+audio+captions for all 4 interviews in one shot and save them into 4 separate video/audio segments with 4 associated caption files with captions properly re-aligned.

**Comment by nutelina** [comment]
It would also be great to remove _noise_ if we'd used auto-captioning services based on Machine Learning. So it would be great to hookup SubtitleEdit to such service similarly to how the automatic translations are done. I had tested an anime and was _very_ surprised it somehow got the Japanese subtitles I never had on my harddrive so it must have fetched them from the internet?

**Comment by OmrSi** [comment]
@niksedk I remember you saying something about not interested in SE handling videos...

**Comment by niksedk** [comment]
Yes, out of scope, sorry.
