### ISSUE TITLE
Playback with MPV reset after opening and closing settings

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2607]
So, I think this is a result of the attempts to fix the video popout thing, but: If MPV is selected and you enter and then exit settings while a video is open, the current time is reset, the player goes back to the beginning of the file.

**Comment by OmrSi** [comment]
Build 19. not having this issue here...

**Comment by darnn** [comment]
I'm on build 20. Any different for you?

**Comment by OmrSi** [comment]
Nope. Not having this problem.
The problem i am having even with 19, is that the volume is reset. it becomes 0 some times when i close and open the program.
And always when i shut down and open my laptop again...

**Comment by darnn** [comment]
My laptop's hidden away somewhere, or I'd try that out... It beats something Subtitle Workshop 2.51 used to do, which was flip the video image if you closed and opened the laptop...

**Comment by OmrSi** [comment]
Still?

**Comment by darnn** [comment]
As of build 32, it has resumed working properly for me.

**Comment by OmrSi** [comment]
Great.

**Comment by OmrSi** [comment]
Can you check to see if this https://github.com/SubtitleEdit/subtitleedit/issues/2604 is happening with you?

**Comment by darnn** [comment]
Sure, commenting over there now.

**Comment by OmrSi** [comment]
you should close this if it is solved.
