### ISSUE TITLE
Move translations to crowdin

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#2609]
[Crodwin](https://crowdin.com) is localization platform and it supports XML.
It is also free for open source projects.

Please enable translations there, because it's more natural for translator experience.
U basically connect this repo, and then it syncs, I believe. Something like that.

Point is, in Crowdin it tells us which strings are not translated [marked red] 
so we can instantly translate them without a hassle.

**Comment by niksedk** [comment]
"XML content translator" already marks not translated lines with read + offers Google Translate.

I've not heard about this before - but if many translators want this perhaps we can look again.
Looks a bit commercial though...
