### ISSUE TITLE
Batch Converting to Sup

### ISSUE THREAD

**Issue by nstefy** [SubtitleEdit/subtitleedit#2610]
selecting font to bold doesn't work
With font selected bold the resulting file has normal text
![untitled](https://user-images.githubusercontent.com/5330623/31850423-ff7e69c4-b659-11e7-9461-e2adb1b6f4f8.jpg)

**Comment by niksedk** [comment]
@nstefy: thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
