### ISSUE TITLE
Wave form extraction samplerate is very low 

### ISSUE THREAD

**Issue by Oritzo** [SubtitleEdit/subtitleedit#2611]
Hello,
I used old version of SE and wanted to upgrade,
However, the waveform is an important tool for me.
I cannot seem to extract it tn the same detailed way it used to be.

Is it a bug or a feature? 
Am I doing something wrong?
I updated all my codecs and no change.

Thank you for all your work.
I appreciate it a lot.
Orit.

**Comment by niksedk** [comment]
Actually, the waveform now contains a lot more info and is more precise now...

**Comment by Oritzo** [comment]
Thank you. 
So I must be doing something wrong.
