### ISSUE TITLE
Problem with greek letter "nu" changed to english v in 

### ISSUE THREAD

**Issue by andremathieu** [SubtitleEdit/subtitleedit#2613]
When using the mode "Binary Image Compare", I asked the letter to be a greek letter "nu" U+03BD but it always changes it to an English v.
This means the words are not found in the dictionary.
Please test the file attached.
![image14](https://user-images.githubusercontent.com/33086886/31999211-d29e8056-b992-11e7-9566-9946a1371de6.png)

The expected text is :

Πω πω! Πούπουλο είναι!
Επιτέλους, θα ευχαριστηθώ ύπνο

In addition, it would be great if I could change the default value for "No of pixels for space" and "Max error %" because only 0.0 works for greek.

**Comment by Flitskikker** [comment]
Did you try unchecking this option?

![image](https://user-images.githubusercontent.com/3516155/31999686-7aad19be-b994-11e7-88e4-e0ee29468bd4.png)

**Comment by niksedk** [comment]
@andremathieu: you know you can edit the ocr choices, right?
![image](https://user-images.githubusercontent.com/1261331/32005551-dbe2c69c-b9a4-11e7-8473-ca09fb0932d2.png)

**Comment by andremathieu** [comment]
Flitskikker; Yes, I tried it works very well but then I can not use a new ocr with this time the Greek dictionary.
 thank you anyway!

niksedk; Yes, I know, by double clicking on the line he opens this window.
![nu grec](https://user-images.githubusercontent.com/33086886/32023604-08300e8c-b9da-11e7-8449-462d32e9e4a9.JPG)
But even if I put the good "nu" U + 03BD (which is the one used by the dictionary that can be downloaded with your program) 
![nu grec2](https://user-images.githubusercontent.com/33086886/32024176-e2ad6784-b9db-11e7-871d-64556168e265.JPG)
and that I do update
when I redo an ocr with this time checked boxes, 
![capture3](https://user-images.githubusercontent.com/33086886/32024192-f01b6574-b9db-11e7-8828-54c169e3a424.JPG)
he does not recognize any word possessing the "nu" Greek because it became (I checked) a v Latin
![nu grec2](https://user-images.githubusercontent.com/33086886/32023842-d5f66776-b9da-11e7-859c-14d7e8205984.JPG)
For other words (without ν) there is no problem

I hope I have correctly explained my problem in any case thanks again for all the work you do

**Comment by andremathieu** [comment]
@Flitskikker , sorry, I misunderstood you message.
When I untick "Fix common OCR errors", then the issue with "nu" changed to "v" does not happen.
Thank you for your help!

@niksedk , I did edit the ocr changes and double check it has "nu" in the Text associated with the image.
However, when "Fix common OCR errors" is ticked, it will always replace "nu" with "v", which means that the greek dictionary will not recognize the word.
