### ISSUE TITLE
Error on Create Subtitle

### ISSUE THREAD

**Issue by Robi67** [SubtitleEdit/subtitleedit#2615]
In Create mode when I try to write in italics, I receive the following error message
[Error.docx](https://github.com/SubtitleEdit/subtitleedit/files/1422124/Error.docx)

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/32131968-ebd5869e-bbba-11e7-943e-7e3e09b42405.png)

OK, do you know how to re-create this error?

**Comment by Robi67** [comment]
The error appears only when I doesn't sellect the the text entirely or
partially.

**Comment by niksedk** [comment]
OK, what are the exact steps? Can you also make latest 3.5.5 crash?

**Comment by Robi67** [comment]
I am in CREATE mode (but is the same in TRANSLATE mode). In the Edit box I
wrote something and without selecting the entire text I try the command
CTRL-I, and it crashes. (from yesterday I work with the newest 3.5.5
version). When I sellect the text (CTRL-A) and after that CTRL-I it all
goes well, without problems.
Another problem that bother me is that: I have set the max cps to 17 but
the Recalculate command gives me allways the same result, 15 cps.
Another problem: The Netflix quality check icon doesn't appear in Toolbar
(in the setting is set to visible).
Greetings and thanks for the help.

**Comment by niksedk** [comment]
OK, so it looks like the crash has been fixed :)

About the recalculate, check the setting called "SubtitleOptimalCharactersPerSeconds" in settings.xml.

Netflix icon only appear for formats "Netflix Timed Text" and "Timed Text 1.0"

**Comment by Robi67** [comment]
Hi! I can't find settings.xml

**Comment by Robi67** [comment]
OK. I find it. How it can be compiled? I have Microsoft Visual Studio
Comunity 2017.
