### ISSUE TITLE
Text on buttons is cut in half

### ISSUE THREAD

**Issue by Xenos71** [SubtitleEdit/subtitleedit#2616]
Hi,
as you can see in the following screen grab (lower left part of the image), after updating SE to 3.5.4, the text on the buttons, as well as some other indications, does not appear correctly any more, with the lower half being cut off. It seems like the text became bigger and it's not adjusted on the buttons properly.
Same also happens with the portable version.

![default](https://user-images.githubusercontent.com/32386964/32134557-f68fd494-bbf7-11e7-8e10-ca91d513107f.jpg)

I tried the previous version 3.5.3 and the text on the buttons and everywhere else is displayed correctly.
I'm on Windows 10, 64bit and I haven't done any changes to my system recently.
Thanks in advance.

**Comment by OmrSi** [comment]
@niksedk This might be also closed after recent changes.
