### ISSUE TITLE
how to hide menu bar bottom when show video fullscreen 

### ISSUE THREAD

**Issue by hosseinarts** [SubtitleEdit/subtitleedit#2618]
hi 
i want alwayes menu bar bottom player when show video full screen hide for me
only work with button Ctrl+Enter and Spacebar Escape .........
please say how menu bar when show full screen video in the subtitle edit alwayes hide form me

**Comment by LeonCheung** [comment]
**Menu** > **Video** > **Un-dock video controls**, then tweak video window size manually.

**Comment by OmrSi** [comment]
@niksedk Closed?
