### ISSUE TITLE
Theme is not applied consistently

### ISSUE THREAD

**Issue by Kzer-Za** [SubtitleEdit/subtitleedit#2620]
I suppose it's a problem with Mono toolkit under Linux.

I use a dark theme applied globally to all GUI applications. The problem is only with Subtitle Edit (3.5.4-1).

On the first screenshot notice that while most of the interface respects the dark theme, some elements do not. The situation with the toolbar and menu is the most inconvenient because of the light text against the light background.

On the second screenshot it is less inconvenient because at least the text is dark, but there you can see also two other issues: text not fitting in its place and that the settings window is too small (and cannot be resized). I'm going to open separate issues for these.

PS As far as I can tell, most Linux users use dark themes for their interface, at least that's the impression I got from most screenshots shared in linux.org.ru and some other sites.

![2017-10-30_23-02-59](https://user-images.githubusercontent.com/26425206/32208100-5c56614c-be11-11e7-9817-0f6b58c268a2.png)
![2017-10-30_23-04-42](https://user-images.githubusercontent.com/26425206/32208101-5c85dd82-be11-11e7-95d1-a5497041ac13.png)

**Comment by ManuLinares** [comment]
Same here, using Manjaro XFCE. Menu item height and font garbled.

![image](https://user-images.githubusercontent.com/3720020/120234733-f636c200-c22e-11eb-93c1-93770f209b0d.png)
![image](https://user-images.githubusercontent.com/3720020/120234755-ff279380-c22e-11eb-89a2-7d709c1f1e1a.png)

**Comment by ManuLinares** [comment]
This isn't completed, using latest version: 3.6.7  
https://aur.archlinux.org/packages/subtitleedit

I'm on EndeavourOS XFCE.
