### ISSUE TITLE
Settings window is too small and cannot be resized

### ISSUE THREAD

**Issue by Kzer-Za** [SubtitleEdit/subtitleedit#2621]
As with my previous issue, I think it's a Mono problem on Linux.

The Settings window is too small for its content (as you can see on the following two screenshots) and (what you can't see) it cannot be resized. When I grab it by the corner to resize it, it gets moved instead.

Subtitle Edit version is 3.5.4-1.

![2017-10-30_23-04-42](https://user-images.githubusercontent.com/26425206/32208101-5c85dd82-be11-11e7-95d1-a5497041ac13.png)
![2017-10-30_23-03-11](https://user-images.githubusercontent.com/26425206/32208484-dead5946-be13-11e7-8883-848dfc53d892.png)

**Comment by kavusha** [comment]
Have the same problem on Windows 10.
I guess it has something to do with the display scaling. Mine is 133%.
Still other programs have no issues with that.

![untitled](https://user-images.githubusercontent.com/31541021/33309531-ac76af92-d41e-11e7-9679-dfe3b679fd91.png)

**Comment by niksedk** [comment]
Mono issues should be fixed
