### ISSUE TITLE
Text in some control elements does not fit in its place

### ISSUE THREAD

**Issue by Kzer-Za** [SubtitleEdit/subtitleedit#2622]
As with my two previous issues, it's probably a Mono problem.

The text near some checkboxes and other control elements is cut off or is superpositioned by the text of other control elements.

On the first screenshot it's "Remove text for H", on the other two it's more obvious.

Subtitle Edit version is 3.5.4-1.

![2017-10-30_23-09-16](https://user-images.githubusercontent.com/26425206/32208627-b23bc98c-be14-11e7-9cc6-8fe4e46b53e9.png)
![2017-10-30_23-03-11](https://user-images.githubusercontent.com/26425206/32208484-dead5946-be13-11e7-8883-848dfc53d892.png)
![2017-10-30_23-04-42](https://user-images.githubusercontent.com/26425206/32208101-5c85dd82-be11-11e7-95d1-a5497041ac13.png)

**Comment by OmrSi** [comment]
@niksedk You've been working on this, you think it's fixed?

**Comment by niksedk** [comment]
Yes, should be fixed :)
