### ISSUE TITLE
Build.bat fails with VS 2017 Community

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2625]
I recently updated my VS 2017 Community installation to the latest version, and using build.bat doesn't work anymore as it doesn't find msbuild.exe.

On my computer, msbuild.exe is now in folders c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\ and c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64. Vswhere.exe is in c:\Program Files (x86)\Microsoft Visual Studio\Installer\.

**Comment by niksedk** [comment]
What happens if you pull latest version and try again?
(I've just updated wswhere.exe which is included in the SE source)

**Comment by Boulder08** [comment]
Still the same error:
Cannot find Visual Studio 2017


 **ERROR: Build failed and aborted!**

**Comment by Boulder08** [comment]
Vswhere returns the correct path : "installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community" , so it should be able to find msbuild.exe as well.

**Comment by niksedk** [comment]
What happens if you put this in a .bat file (in the same folder as build.bat) and run it:

    @echo off
    for /f "usebackq tokens=1* delims=: " %%i in (`vswhere -latest -requires Microsoft.Component.MSBuild`) do (
      if /i "%%i"=="installationPath" set InstallDir=%%j
    )
    echo %InstallDir%
    Pause > null

**Comment by Boulder08** [comment]
I get no output, just "ECHO is off."

With echo off commented out, this is what can be seen:

C:\sources\subtitleedit>for /F "usebackq tokens=1* delims=: " %i in (\`vswhere -latest -requires Microsoft.Component.MSBuild`) do (if /I "%i" == "installationPath" set InstallDir=%j )

C:\sources\subtitleedit>(if /I "Visual" == "installationPath" set InstallDir=Studio Locator version 2.2.11+gf1a9c6c78d [query version 1.12.134.36697] )

C:\sources\subtitleedit>(if /I "Copyright" == "installationPath" set InstallDir=(C) Microsoft Corporation. All rights reserved. )

C:\sources\subtitleedit>echo
ECHO is on.

C:\sources\subtitleedit>Pause  1>null

C:\sources\subtitleedit>

**Comment by Boulder08** [comment]
Started working after I opened the solution directly in VS 2017. There were .NET components missing, in fact quite a lot of them, for some reason after the upgrade. Strange thing is that I upgraded using the Visual Studio Installer and never chose to uninstall anything.
