### ISSUE TITLE
ASS formats - sort by Actor missing. 

### ISSUE THREAD

**Issue by mellsaid** [SubtitleEdit/subtitleedit#2627]
The new ASS format opens new limits to subtitle edit by introducing the actor field. As we continue working with it, we are finding the gaps required to use it well. With that in mind, Is it possible to add sort fields by Actor? (tools - sort by - Actor) where when its sorted, it sorts by actor name in chronological order (actor A (00:00 till 60:00) then Actor B (00:00 till 60:00))

**Comment by niksedk** [comment]
It's already included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip :)

**Comment by mellsaid** [comment]
@niksedk Thats great thank you!. Do let me me know how I can buy you a beer for all your great work. Truly appreciated
