### ISSUE TITLE
Change casing bug, wrong letter

### ISSUE THREAD

**Issue by ahmedtds** [SubtitleEdit/subtitleedit#2628]
There's a very annoying bug in change casing that I couldn't find a way to workaround.

I use last version of Subtitle edit (3.5.4) on Windows 7. Language of my OS is Turkish but I use Subtitle edit in English. Everything about language is set to English in Subtitle Edit.

Now thing is when I do a change casing, Subtitle Edit wrongfully converts **I** to **ı** instead of **i**.
**ı** is lowercase of **I** in Turkish and **i** is lowercase of **İ**. In spite of English there are two different letters involving as you can see. And they both have their own lowercase and uppercase variants.

I think it's because of language of my OS but what's happening is wrong. It's right for a Turkish text but wrong for every other language, it messes English subtitles when I do a change casing. How can I make Subtitle Edit to convert casing according to English not my OS language? Is there a way to do this? This is very annoying. I think this might happen in other areas too when uppercase lowercase conversion happens not just in change casing menu.

Thanks.

**Comment by niksedk** [comment]
Could you provide some examples?

**Comment by ahmedtds** [comment]
I just noticed it also converts **i** to **İ** instead of **I** in "Fix common errors" section (Fix first letter to uppercase after paragraph) and with all uppercase option in change casing as well.

**Comment by ahmedtds** [comment]
examples:

"all right, if you're like me" -> "ALL RİGHT, İF YOU'RE LİKE ME"
"ALL RIGHT, IF YOU'RE LIKE ME" -> "all rıght, ıf you're lıke me"

**Comment by ahmedtds** [comment]
I think I found the root of the problem. Looks like you use ToLower() and ToUpper() when doing that conversion. And by default it uses casing rules of current system language.

Looks like you can fix this by using ToLowerInvariant and ToUpperInvariant instead of vanilla ToLower and ToUpper

Or even better you can tell C# which culture it will be using when doing that conversion with ToLower and ToUpper: https://msdn.microsoft.com/en-us/library/s8z5yt00(v=vs.110).aspx
(implementing this solution would be better because looks like ToLowerInvariant and ToUpperInvariant just sets culture to constant English instead of looking system therefore it can break conversions in a Turkish text. Having an option to change it would be better)

Adding an option in Settings to choose language for casing conversions and passing that info to ToLower and ToUpper with CultureInfo seems like best solution.

https://stackoverflow.com/questions/6225808/string-tolower-and-string-tolowerinvariant
https://stackoverflow.com/questions/3550213/in-c-sharp-what-is-the-difference-between-toupper-and-toupperinvariant
https://stackoverflow.com/a/6601033
https://msdn.microsoft.com/en-us/library/ms973919.aspx#stringsinnet20_topic5
https://msdn.microsoft.com/en-us/library/ms994325.aspx#cltsafcode_topic4

**Comment by aaaxx** [comment]
> Adding an option in Settings to choose language for casing conversions and passing that info to ToLower and ToUpper with CultureInfo seems like best solution.

This doesn't solve the problem. The only good solution from a user-experience point of view is to do the conversion based on the language of the current file, and since the language is already automatically detected, I don't think it should be a problem to implement it.

**Comment by ahmedtds** [comment]
Downloaded the beta from your link and tested but looks like it's not fixed. Still produces random İ and ı around. There's a slight difference in results from latest stable version but still does wrong conversions don't know why.

**Comment by ahmedtds** [comment]
You have to run the program under the Turkish locale to reproduce it. Subtitles don't matter I just open some random subtitle files and do some uppercase lowercase conversions and search for **ı** and **İ** after.
You won't reproduce it under an English or another locale Windows.

I think you can emulate it somehow but don't have detailed information

http://www.moserware.com/2008/02/does-your-code-pass-turkey-test.html
