### ISSUE TITLE
"Gap" column activation is not remembered

### ISSUE THREAD

**Issue by vsemozhetbyt** [SubtitleEdit/subtitleedit#2630]
SubtitleEdit 3.5.4 beta build 77 on Windows 7 x64

After adding the "Gap" column via List View context menu, closing and reopening SE, the "Gap" column is absent again.

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by vsemozhetbyt** [comment]
@niksedk 
Thank you! Build 78 now remembers the visibility and the width of the "Gap" column, but it does not remember the order: say, I drag the "Gap" column after the "Text", but after reopening it is before "Text" again. Should the order be saved?

**Comment by darnn** [comment]
While on this subject, the width of columns isn't saved either. Before restart:
![se-listview-columns01](https://user-images.githubusercontent.com/19672444/32509033-d961fcf8-c3f4-11e7-8173-b4e064ab6177.png)

After restart:
![se-listview-columns02](https://user-images.githubusercontent.com/19672444/32509036-de7475b8-c3f4-11e7-8569-18bd7c6253f9.png)
