### ISSUE TITLE
Windows Form Thread Exception

### ISSUE THREAD

**Issue by NARUTOANIME** [SubtitleEdit/subtitleedit#2633]
![capture](https://user-images.githubusercontent.com/33577232/32691302-82756418-c72b-11e7-89d2-6608d6d41b4d.PNG)

**Comment by NARUTOANIME** [comment]
What's going on? 
Has somebody faced this issue?

**Comment by niksedk** [comment]
Does this happen all the time or only when you are doing what?
Only some videos?

**Comment by niksedk** [comment]
Sounds like a codec issue... try installing lav filters or change video player to mpv.
