### ISSUE TITLE
Cannot undo line merge on newly-created file

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2635]
Hey. So, this one is pretty much what it says in the title.
After creating a new subtitle file, either from scratch or using "import plain text", and then using "merge selected lines" or "merge with next", I can't use undo. Edit->Undo is black, but when I click it nothing happens. And it's the same with the keyboard shortcut.
This seems to happen even if I save the file. However, if I then close the file and open it again, I can merge lines and then undo the merge.

**Comment by niksedk** [comment]
Hm, cannot re-create this...

**Comment by darnn** [comment]
Strangely, I can't reproduce it now with creating a new file from scratch. But it does still happen with importing plain text. I used these settings:
![se import plain text](https://user-images.githubusercontent.com/19672444/32956261-f8ba2e44-cbc0-11e7-9209-ab62017c167f.png)
And, for instance, this file (from which I copied and pasted the text, though I assume it's all the same):
[poker.txt](https://github.com/SubtitleEdit/subtitleedit/files/1482920/poker.txt)

**Comment by niksedk** [comment]
OK, I can re-create this now :)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

thx for the bug report :)
I think I've also seen this but could not remember how I did it...

**Comment by darnn** [comment]
Thank you for fixing it! I've seen it a bunch of times but it was always right as I was starting work (since I had just imported the file), so I mostly ingnored it.
