### ISSUE TITLE
Font problem in main window

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2638]
In the latest Beta assigned Font in settings doesn't apply when opening the program or opening a subtitle
![screenshot 10](https://user-images.githubusercontent.com/20923700/32979670-a147deb6-cc62-11e7-96bf-9626ace37587.png)

Until you open a window, settings or any other windowed option, it returns to the selected font
This is after opening the settings window
![screenshot 11](https://user-images.githubusercontent.com/20923700/32979682-cfcf872a-cc62-11e7-832e-ca7d00bfee1b.png)

**Comment by niksedk** [comment]
thx :)
Is this better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Yeah. it takes some time to adjust, but it's working

**Comment by niksedk** [comment]
Changed a bit again - could you give this a test: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
(for Dark Theme set "DarkTheme" in Settings.xml to "True" - but you probably already knew that ;)

**Comment by OmrSi** [comment]
Sorry, lost my phone and now i can't keep up with all these awesome changes. :)
Thanks, Man. :D

**Comment by OmrSi** [comment]
the original problem is completely fixed. no delay of any sort.

the dark theme is looking good.
only needs work in these areas:
![screenshot 17](https://user-images.githubusercontent.com/20923700/33189543-4f6c7086-d0ac-11e7-9b9c-09fedb521813.png)
Maybe dark grey or black?
