### ISSUE TITLE
The recent font changes make the time display cover a bit of the UI

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2639]
Build 91. Fairly straightforward, in the bottom right corner, the running time now covers up a bit of "libmpv 1.25".

**Comment by niksedk** [comment]
Not that straightforward as I cannot re-create this ;)
Latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
It no longer happens! Thank you!
