### ISSUE TITLE
Opening a file with "import plain text" while it's locked by a different program causes an error

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2642]
![subtitle edit 2017-11-23_172551](https://user-images.githubusercontent.com/19672444/33179908-aea6f104-d073-11e7-9413-a58db20541e0.png)

**Comment by darnn** [comment]
Thanks!

**Comment by niksedk** [comment]
Thx for finding and reporting this :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
