### ISSUE TITLE
OCR via image compare issues

### ISSUE THREAD

**Issue by Belzak56** [SubtitleEdit/subtitleedit#2643]
I'm trying to use this beta feature: "OCR via image compare issues" for Arabic OCR as it is working very well for me comparing to other methods.

However, I'm facing the below (2) issues:

1. It is recognizing two lines as one line:
![untitled-1a](https://user-images.githubusercontent.com/33938912/33185743-29a7615c-d09e-11e7-86a3-4ddea30a80df.jpg)
![untitled-2a](https://user-images.githubusercontent.com/33938912/33185749-324e6da0-d09e-11e7-83ef-e837895b8061.jpg)

This is caused probably by the proximity of the two lines:
![untitled-7a](https://user-images.githubusercontent.com/33938912/33188467-73ab1888-d0b3-11e7-9be6-e54eb0930588.jpg)

I would suggest to resolve this issue by having less value for: 
"Line split min. height" which is currently at (5).

2. In Arabic Language we have Letters and we have something called Tashkeel, Tanween and Hamza.
Tashkeel, Tanween and Hamza can be put above or below the letter.
currently it is recognized separately from the letter:
![untitled-3a](https://user-images.githubusercontent.com/33938912/33188185-2ffe882e-d0b1-11e7-828f-b5e02f1823b7.jpg)

It should be recognized as a part of the letter like this:
 ![untitled-4a](https://user-images.githubusercontent.com/33938912/33188192-46aaec16-d0b1-11e7-8c7d-dcb7bc6ecb56.jpg)

I think this can be resolved by adding an option to control the Letter width and height.

**Comment by niksedk** [comment]
Try "OCR via binary image compare"... I'm no longer working on "OCR via image compare".
You might want to use latest beta is it contains some fixes for this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by Belzak56** [comment]
Thanks Nisk for the prompt reply. I'll try it and provide you with my feedback.
