### ISSUE TITLE
Input video file .ts is corrupted after running SubtitleEdit

### ISSUE THREAD

**Issue by BL-38** [SubtitleEdit/subtitleedit#2646]
Workflow. 

1. Record film via terrestrial HDTV (DVB-T) as a small number of .ts files, each ~1GB. 
2. Concatenate the files via copy /b
3. Check that the concatenated file reads OK with VLC; identify proper DVB subtitle track
4. Run SubtitleEdit save As... srt file
5. Re-check original .ts file: cannot read with VLC

**Comment by niksedk** [comment]
OK, SE only opens the file as read-only, so this is simply just not possible.

**Comment by mkver** [comment]
For reference, you actually ran into [VLC bug #3075](https://trac.videolan.org/vlc/ticket/3075).
