### ISSUE TITLE
Problems with search and replace in translator mode

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2648]
Hey. Latest build.
In translator mode, if you search for a word that appears in the original subtitle, in the "replace" dialogue, clicking "find" will only find the first instace of that word over and over, and highlight it in the textbox of the translation, not the original. What's worse, clicking "replace" will make a change to the translation, rather than the original:
![se-2017-11-25_222559](https://user-images.githubusercontent.com/19672444/33234450-ca3036d4-d22f-11e7-8f9b-85fc534fb451.png)
![se-2017-11-25_222609](https://user-images.githubusercontent.com/19672444/33234452-cc4911d4-d22f-11e7-97b3-71ed4a476303.png)

**Comment by niksedk** [comment]
thx - yes, that works poorly.
Is latest beta better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip ?

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
The "replace" button now replaces the proper thing! So that's good. But "find" still gets stuck on the first result. So you can't cycle through the results in the file and selectively replace some and not others.

**Comment by darnn** [comment]
Actually, this seems to have broken the ability to go to the next result even with the "find" dialogue, and even outside of translator mode.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Only tested briefly, but everything seems to work okay now!
