### ISSUE TITLE
Minor mpv subtitle preview issue with RTL languages

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2649]
Hi. So, typing in Hebrew (and presumably in any RTL language), if you have a subtitle that is several letters, a space and then a number, it's not displayed in the correct order in the MPV subtitle preview:
![se-2017-11-27_021519-mpv-hebrew](https://user-images.githubusercontent.com/19672444/33246073-212b98f4-d319-11e7-9928-cbf916140ccf.png)

**Comment by niksedk** [comment]
Sorry, I don't really understand how this RTL works... I've tried, but I don't understand the rules, so perhaps someone who understands this better could help?

**Comment by darnn** [comment]
Well, I mean, in terms of this specific example (and also for like 99% of the time), it should just be the same as in the textbox if you're typing in Hebrew and you're aligned to the right. So, like in the textbox in the image, right to left, the number, space, and then the word. The rest of the time (from what I've seen so far, and I've been using it for months), the MPV preview is correct.

**Comment by darnn** [comment]
Thanks! If I find any other ones, I'll wait till I have a good chunk before I post about it again.

**Comment by niksedk** [comment]
Actually the text displayed in the above mpv screenshot is the text stored in the program - textboxes just shows the text correctly because they know that they are in RTL mode.

Inserting the RTL unicode control character before all texts seems to work (I hope).
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Yes, when you use "Fix RTL via Unicode control characters" then save the subtitle, you find a weird looking character at the beginning of every sentence, don't know if it happens all the time though...

**Comment by OmrSi** [comment]
@darnn is the original subtitle color changing lately with you when selecting a line then disappearing when you restore the window after minimizing?

**Comment by darnn** [comment]
Actually, this is weird, but now it seems like if a line ends in punctuation, it appears on the right in the preview, rather than on the left like it should. Which was introduced at some point after build 117.
![se-2017-11-28_195432-rtl-preview](https://user-images.githubusercontent.com/19672444/33336030-6eda47a8-d477-11e7-8c25-20cd2c241785.png)

As for the original subtitle color changing, I'm not sure what you mean, so I think that might not happen for me... Do you want to take some screenshots or video and show me, so we can compare notes?

**Comment by darnn** [comment]
Ah, okay, replying there.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
Is this okay?

**Comment by darnn** [comment]
Seems good now, as far as I can tell!
