### ISSUE TITLE
A problem with "Whole word" option in Find/Replace with RTL

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2652]
for example, i write "كلا!" then use Reverse RTL so it becomes "!كلا", when i search for "كلا" as a Whole Word after reversing, it doesn't find the word, it considers the "!" or "،" a part of it...
before reversing there isn't any problem

**Comment by niksedk** [comment]
thx for the info - should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Thx!
