### ISSUE TITLE
English OCR replace list additions

### ISSUE THREAD

**Issue by anewuser** [SubtitleEdit/subtitleedit#2653]
Please consider adding these corrections to the proper sections of the replace list:

- [ ] I ve gotten really good (I've)
- [ ] I ii mother you more (I'll)
- [ ] when I m done (I'm)
- [ ] why d you answer my phone? (why'd)
- [ ] because i... (I...)
- [ ] maybe I couldn t (couldn't)
- [ ] That s how it is... (That's)
- [ ] if I say I Won't do it? (won't)

**Comment by niksedk** [comment]
thx for the input - added :)

**Comment by anewuser** [comment]
Can't the entries for " Won't " be more generic to cover other possibilities (he Won't, they Won't, nicksedk Won't etc.)?

**Comment by anewuser** [comment]
3 more:

- [ ] It's the cortisone. L
hardly recognize myself.
- [ ] Ln a way...
- [ ] Ln the safe.

**Comment by niksedk** [comment]
About the last 3 suggestions -  I don't get the meaning of the first one, the two last already works.

**Comment by anewuser** [comment]
There's a line-break between "L" (supposed to be I) and "hardly".

I'm sorry about the other two. They weren't being corrected for some reason in a file I had, and I can't reproduce it anymore because I edited it manually.
