### ISSUE TITLE
[FindReplaceDialogHelper] - Bug

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#2654]
counting words returns incorrect results, e.g; if text  = `a` then you try to count using regex with pattern (a\d?) it will return 0

**Comment by niksedk** [comment]
OK, how do I re-produce this error exactly?

**Comment by ivandrofly** [comment]
![2017-11-30_19-01-23](https://user-images.githubusercontent.com/6579818/33449530-f5f62696-d600-11e7-9595-05693610fd80.gif)

/cc @niksedk

**Comment by ivandrofly** [comment]
**\d? means match digit if there is any but it's not mandatory**
