### ISSUE TITLE
Exception when fixing common errors in 3.5.4

### ISSUE THREAD

**Issue by watceedee** [SubtitleEdit/subtitleedit#2659]
When using "Fix common errors" on the attached srt file, an exception occurs, as shown in attached image.

Consistently reproducible across restarts of the program.

Program version is 3.5.4

[Carmen 2003.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/1523711/Carmen.2003.srt.txt)

![error](https://user-images.githubusercontent.com/24251978/33514272-7d7fbfea-d751-11e7-8eeb-6e38bb38dce3.png)

**Comment by niksedk** [comment]
thx for the info - can you re-create this in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip ?

**Comment by partenosoft** [comment]
Hi there,

Just to let you know that I had the same issue and the latest beta (build 139) has fixed it (at least for me).

Thank you very much for your incredible work!

**Comment by watceedee** [comment]
The problem seems to have been resolved - further more, the fix common errors dialog is much more performant than before- good job! :)
