### ISSUE TITLE
Option for "Start with uppercase after brackets"

### ISSUE THREAD

**Issue by SvenErik1968** [SubtitleEdit/subtitleedit#2664]
I would like to see an option under _Fix common errors_ for _**Start with uppercase after brackets ")]}"**_.

I sometimes have to change the casing for subtitles that are in all upper case, and where you have lines that contains both hearing impaired text and normal conversation, a sentence that start after a bracket will not be corrected to start with upper case unless it is recognized as a name after you have done the Change casing - Fix common errors tools.

Example:
```
1
00:00:22,432 --> 00:00:25,432
CAPTIONING MADE POSSIBLE BY
BUENA VISTA TELEVISION

2
00:02:35,500 --> 00:02:40,533
[ Newsreel Narrator ] OMINOUS CLOUDS OF WAR
MAY BE GATHERING OVER EUROPE,
```
Ends up like this:
```
1
00:00:22,432 --> 00:00:25,432
Captioning made possible by
buena vista television

2
00:02:35,500 --> 00:02:40,533
[ newsreel narrator ] ominous clouds of war
may be gathering over Europe,
```

**Comment by niksedk** [comment]
I've started with improving "Change casing", so hopefully that works better now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by SvenErik1968** [comment]
Yes, did a quick test with the beta version now, and the results came out great!
Thanks!
