### ISSUE TITLE
OCR via image compare

### ISSUE THREAD

**Issue by yayrre** [SubtitleEdit/subtitleedit#2665]
It seems that OCR via image compare disappear in latest version? Can I convert the image compare database into binary compare database? I don't want to re-enter everything... Also, how can I export a database? I only found  import function...

**Comment by niksedk** [comment]
Sorry, it's not possible to convert from "image compare" to "binary image compare".

If you're using non Latin letters in OCR you should probably use latest beta of SE: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip as some improvements has been made - e.g. from here: https://github.com/SubtitleEdit/subtitleedit/issues/2656

Also, ppl are welcome to submit their own "binary image compare" dictionaries to SE :)
