### ISSUE TITLE
Auto Break issue

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2667]
when you have a line with a tag, auto break doesn't balance the line well

for example i have this:
{\an9}{\fs24}{\fnArabic Typesetting}<font color="#FF1122">الاسم الذي أطلقه عليه في فيلم "أفينجرز" الأول" لأنه يشبه (باترك سويزي) في فيلم "بوينت بريك"

When auto breaking with tag:
{\an9}{\fs24}{\fnArabic Typesetting}<font color="#FF1122">الاسم الذي أطلقه عليه في فيلم
"أفينجرز" الأول" لأنه يشبه (باترك سويزي) في فيلم "بوينت بريك"

Without tag:
{\an9}{\fs24}{\fnArabic Typesetting}<font color="#FF1122">الاسم الذي أطلقه عليه في فيلم "أفينجرز" الأول"
لأنه يشبه (باترك سويزي) في فيلم "بوينت بريك"

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
