### ISSUE TITLE
Problem with Tags + Revesre

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2668]
simple example::
before:
{\an8}{\fs56}"مهلًا! إلى أين تذهب؟"

after:
{\an8}"{\fs56}"مهلًا! إلى أين تذهب؟

**Comment by niksedk** [comment]
thx for the info - should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
