### ISSUE TITLE
Reverse Issue with "*@/<>&^%$#\|"

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2670]
for example i have this sentence:
مهلاً! يا للجنون!*
when i reverse it doesn't do anything
same with other cases

BTW, the last 2 problem were solved, thx a lot.

**Comment by niksedk** [comment]
What should happen?

**Comment by OmrSi** [comment]
There are two cases, if you want to consider it like any other reversible
 *!مهلاً ! يا للجنون

if you want to consider it a Unicode control character, it should be
!مهلاً ! يا للجنون*

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
Any better?
