### ISSUE TITLE
Unable to make a shortcut for exporting plain text

### ISSUE THREAD

**Issue by KitezhGrad** [SubtitleEdit/subtitleedit#2674]
**System**: Windows 10 Pro
SubtitleEdit Version: 3.5.4

**Issue**

Unable to create a **shortcut** for extracting **plain text** from an SRT file.

**Steps to reproduce**

1. Launch SubtitleEdit 3.5.4
2. Options -> Settings -> Shortcuts -> File
3. The only available shortcut option for export is **Export -> EBU STL**
![screenshot 117](https://user-images.githubusercontent.com/19307323/33930208-bb825f02-e01e-11e7-92d2-1155b1659ef9.png)

**Request**

Please enable the shortcut option for extracting **plain text (.txt format)** from SRT.

**Comment by niksedk** [comment]
I think it's already included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
@niksedk Haha, for me it would be more often to use the Import Plain Text setting. And just noticed that it has also been implemented there already. Thanks a lot for that!
