### ISSUE TITLE
reopen saved file Duration ALL changed to 1.000

### ISSUE THREAD

**Issue by bizkitj** [SubtitleEdit/subtitleedit#2676]
Hello
I am running into a strange situation. I googled it  and searched the Issues section, it looks like it is only me running into this issue. Maybe I am doing something wrong.

LatestVersion, Subtitle Edit 3.5.4 installed version on win10 64bit system.
1: Load a mp3 file obtained from the internet.
2: Start puting the subtitles, save the file as .srt or .json(11)
3: Quit \ Close Subtitle Edit 3.5.4.
4: Relunch Subitle Edit 3.5.4, it opens with previous worked file, however, on the List View----Duration section, all of the item's value changed from previous edited value to 1.000.
5: Tried couple of time of unintall Subtitle Edit 3.5.4 an reinstall, or even the portable version, same issue.

Am I doing something wrong here?

**Comment by niksedk** [comment]
Json 11 don't have a duration... so don't save in that format unless you need it.
