### ISSUE TITLE
Subtitle Edit hangs on app quit (Windows 7)

### ISSUE THREAD

**Issue by Kravimir** [SubtitleEdit/subtitleedit#2677]
This happens when exiting the app after using the "adjust all times" feature one or more times. I was hoping that upgrading to 3.5.4 would resolve this as I was having this issue in 3.5.2 as well. I'm using 64-bit now but 3.5.2 may be been 32-bit.

This is what the Windows error message shows:
Description:
  A problem caused this program to stop interacting with Windows.

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	SubtitleEdit.exe
  Application Version:	3.5.4.0
  Application Timestamp:	59d26c3c
  Hang Signature:	24cd
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Hang Signature 1:	24cdd304a5ef094c9fdf0e081521f358
  Additional Hang Signature 2:	0b5f
  Additional Hang Signature 3:	0b5f83d789b38bc03b585f7489ccc6bf
  Additional Hang Signature 4:	24cd
  Additional Hang Signature 5:	24cdd304a5ef094c9fdf0e081521f358
  Additional Hang Signature 6:	0b5f
  Additional Hang Signature 7:	0b5f83d789b38bc03b585f7489ccc6bf

**Comment by niksedk** [comment]
Perhaps you could try to re-install .net framework - https://www.microsoft.com/en-us/download/details.aspx?id=53344

**Comment by niksedk** [comment]
Any luck?
Also, perhaps you could change the video player to "mpv" - Options -> Settings -> Video player

**Comment by Kravimir** [comment]
Yes, re-installing .Net seems to have helped. Thanks.

I've been using the VLC option as the video player. You think MPV might run better on Windows 7?

**Comment by OmrSi** [comment]
MPV is better at everything.

**Comment by niksedk** [comment]
Especially, MPV has precise seeking (VLC do not), but that's only important if you sync or create subs.
