### ISSUE TITLE
Video preview problem

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2681]
a pic is worth a 1000 word
![untitled](https://user-images.githubusercontent.com/20923700/34052851-d116f67a-e1cc-11e7-86a4-e3999dd284df.jpg)

**Comment by OmrSi** [comment]
Just discovered that In MPC it shows up like the TextBox
But when using MPC in SE, it shows up reversed

**Comment by OmrSi** [comment]
Another problem I've noticed when using tags Between MPV and MPC:
![screenshot 56](https://user-images.githubusercontent.com/20923700/34062289-7a800e8c-e1f4-11e7-888d-009ac37cd24e.png)

**Comment by OmrSi** [comment]
after some research i discovered that this problem only occurs when typing a "(" and and Arabic comma "،" after it. Is there an explanation and can it be fixed to show the in in the video player as the Textbox?

**Comment by OmrSi** [comment]
@niksedk any ideas?

**Comment by niksedk** [comment]
Only confused... I don't really understand this stuff!

Also, mpv or mpc ?

**Comment by OmrSi** [comment]
well, Both in SE
In SE when using any player they show up reversed, but if using MPC outside SE it shows up like the TextBox
Here is a photo with MPV:
![screenshot 65](https://user-images.githubusercontent.com/20923700/34183272-9b6840de-e522-11e7-91e1-671af7843166.png)

With MPC:
![screenshot 66](https://user-images.githubusercontent.com/20923700/34183310-d77320b2-e522-11e7-9bde-fd0a586c426c.png)

Note that it happens when using this combination "،)"

**Comment by niksedk** [comment]
Can you supply the actual text?

**Comment by OmrSi** [comment]
556-557 here: https://www.dropbox.com/s/0d1m1qjwt0whb5p/Game%20Of%20Thrones%20Conquest%20And%20Rebellion%202017%20Movies%201080p%20BluRay%20x264%205.1%20ESubs%20rDX.srt?dl=0
