### ISSUE TITLE
Subtitle Edit 3.5.4 ... Entry Point Not Found

### ISSUE THREAD

**Issue by silverwoodchuck47** [SubtitleEdit/subtitleedit#2683]
Every time I drop a video into SE, this is the first of many messages received:

The procedure entry point vlc_fastmem_register could not be located in the dynamic link library C:\Program Files\VideoLAN\VLC\plugins\3dnow\libmemcpy3dn_plugin.dll.

There are seven or so other dlls that SE can't seem to find.

**Comment by niksedk** [comment]
What version of VLC are you running?
I recommend that you uninstall your current VLC version and use this download link for latest 64-bit VLC: https://get.videolan.org/vlc/2.2.8/win64/vlc-2.2.8-win64.exe

**Comment by silverwoodchuck47** [comment]
VLC 2.2.6 Umbrella on Win10/32.  I don't think the 64-bit version will run on with my OS.

**Comment by niksedk** [comment]
OK, could you try to uninstall VLC completely  - and then re-install it?
Alternately, you could try "mpv" as your video player inside SE.
