### ISSUE TITLE
</font> Problem in MPV

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2684]
As you can see, the tag </ font> shouldn't show up in video player:
![screenshot 64](https://user-images.githubusercontent.com/20923700/34158931-04c32fba-e4d0-11e7-90d1-126c254e509b.png)

**Comment by niksedk** [comment]
Could you paste the sub lines?

**Comment by OmrSi** [comment]
I noticed that it also shows up in other players inside SE, but when using the same player outside it doesn't:
![screenshot 67](https://user-images.githubusercontent.com/20923700/34183626-5eadaf88-e524-11e7-8051-f2b2e1be60b3.png)

The line:
{\fs36\fnArabic Typesetting\1c&H0000FF&}والدماء </font>{\fs36\1c&H4080FF&}النار

it shows up when there isn't an HTML tag in the line but only ass tags, Some put it with ass for some purpose, anyway it shouldn't show up on the video

**Comment by niksedk** [comment]
Cannot re-create this... also is the problem with MPC or MPV?

**Comment by OmrSi** [comment]
It's happening in both, inside SE, but if using outside MPC it doesn't happen
Here is the line, i gave you the wrong one:
{\fs36\fnArabic Typesetting\1c&H0000FF&}والدماء </font>{\fs36\1c&H4080FF&}النار</font>

**Comment by niksedk** [comment]
I can still not re-produce this...

**Comment by OmrSi** [comment]
second sentence here: https://www.dropbox.com/s/t9froeeeaiv3sqo/Thor.Complete.TS.%28Colored%29.srt?dl=0
