### ISSUE TITLE
Arabic OCR via Binary Image Compare

### ISSUE THREAD

**Issue by essam315** [SubtitleEdit/subtitleedit#2686]
The Arabic OCR via Binary Image Compare works perfectly most of the time with minor issues need to be fixed:
1. The OCR recognizes the two dots of the letter "ي" as a separate letter but they are part of the letter "ي"

![3](https://user-images.githubusercontent.com/34485960/34312639-484266e8-e76e-11e7-865e-99132186c755.png)

This issue occurs with many letters with dots in it like "ب"  

2. The OCR  considers the question mark and the word before it as a new word as in this image

![1](https://user-images.githubusercontent.com/34485960/34312707-acd1b226-e76e-11e7-8cf4-54b59ac2e7a8.png)

It will be a great help if it is possible to add "skip all" button in "VobSub - Manual image to text " window, the OCR many times recognizes parts of the letters as letters, something like this image

![4](https://user-images.githubusercontent.com/34485960/34312882-e1f19862-e76f-11e7-9329-3c7b28c97b38.png)

**Comment by niksedk** [comment]
1) you can probably set "Min. line heigh":
![image](https://user-images.githubusercontent.com/1261331/34320022-192f11ee-e7f0-11e7-8101-2afb27628170.png)

2) You could you try latest beta too see if it already has been fixed: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
(if not - the sub and line number will be helpful)

**Comment by essam315** [comment]
I'm using the last beta, the best settings for the font are: 
No of pixels is space: 5
Min. line height (split): 42
Max. error%: 0
Right to left

Line: 53

![53](https://user-images.githubusercontent.com/34485960/34320189-b39b6ee2-e7fc-11e7-92f2-78a7657de7f5.png)


The sub

[1.zip](https://github.com/SubtitleEdit/subtitleedit/files/1584166/1.zip)

**Comment by niksedk** [comment]
1) New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
Any better regarding line 93 (and other lines)?

2) regarding question mark - could you upload your OCR dictionary so I can test?

**Comment by essam315** [comment]
The new beta fixed the question mark issue, but it considers part of the question mark as a letter, as you can see in this image

![qq](https://user-images.githubusercontent.com/34485960/34337014-8cd96188-e964-11e7-9229-4b15c73ae6b7.png)


The Dictionaries


[Dictionaries.zip](https://github.com/SubtitleEdit/subtitleedit/files/1585637/Dictionaries.zip)

**Comment by niksedk** [comment]
Try to click the "Expand selection" button.

**Comment by essam315** [comment]
"Expand selection" button fixes the consideration of the part of the question mark as a letter, but the question mark issue return again.

**Comment by niksedk** [comment]
OK, could you upload the OCR folder too?

**Comment by essam315** [comment]
The OCR

[Ocr.zip](https://github.com/SubtitleEdit/subtitleedit/files/1585891/Ocr.zip)

**Comment by niksedk** [comment]
thx for the files - in what line number is this problem regarding question mark occurring?

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by essam315** [comment]
Thank you, the question mark issue fixed but not all the time. It occurs only with this font.

The "Reversed Numbers" issue in this post still exist in the latest beta, and it occurs with all the fonts, you can find it in line 9 and 10 in this sub., it would be great if it fixed or if there is a workaround to solve it.

https://github.com/SubtitleEdit/subtitleedit/issues/2656


[7.zip](https://github.com/SubtitleEdit/subtitleedit/files/1587242/7.zip)

**Comment by essam315** [comment]
Thank you very much, The question mark issue totally fixed.
