### ISSUE TITLE
How do I convert letters to correct encoding?

### ISSUE THREAD

**Issue by rhazor** [SubtitleEdit/subtitleedit#2687]
I downloaded a foreign subtitles and they are written in wrong encoding and don't display correct.

Here's an example https://pastebin.com/p4NDceGd

You can see symbols like ø and áþæ, these are not letters. The language is Lithuanian, and the letters are encoded in wrong symbols or something, I don't know how to explain it. The Lithuanian letters are converted to symbols because of wrong encoding. Right encoding is UTF8, and if you open this subtitle with SubtitleEdit it reports that the encoding is 1252: Western European (Windows).

How do I fix this with SubtitleEdit?

**Comment by darnn** [comment]
File -> Import subtitle with manual chosen encoding. Although when I download the part you put up on Pastebin and open it, it already opens as UTF8.
Also, you might want to try the latest beta, which might automatically recognize it better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
As an aside, you can do this for all text files in general using a text editor like Notepad++. I prefer Edit Pad myself, and it has a free version: https://www.editpadlite.com/

**Comment by rhazor** [comment]
No, it still opens in 1252: Western European. I attached the full subtitle file.

[file.zip](https://github.com/SubtitleEdit/subtitleedit/files/1585847/file.zip)

**Comment by darnn** [comment]
Once again, have you tried opening it through File -> Import subtitle with manual chosen encoding? And going over the various encodings there?

**Comment by rhazor** [comment]
You're right, correct was 1257: Baltic. Cheers.
