### ISSUE TITLE
Which format do these subtitles have? (subtitle edit should tell you, if it knows it)

### ISSUE THREAD

**Issue by Djfe** [SubtitleEdit/subtitleedit#2689]
it would be nice if subtitle edit would tell which format the source subtitles have :)
I have a video lying around with embedded subtitles in it, but ffmpeg doesn't know their format.
But I'm able to extract and open them in Subtitle Edit (binary images)

It then opens the import window for VobSub (.sub/.idx) (tesseract). But if I rename the file to subtitle.sub and use the specific import .sub/.idx function, then subtitle edit tells me, that the subtitles are in the wrong format :/

**Comment by niksedk** [comment]
Check https://mediaarea.net

**Comment by Djfe** [comment]
I'm using that program already.
I was just wondering: You open a file with the subtitle editor, but it doesn't tell you, which format it has found and is trying to decode atm.
