### ISSUE TITLE
different font on spellchecker

### ISSUE THREAD

**Issue by howardmarshall** [SubtitleEdit/subtitleedit#2691]
I have Tahoma set for font to I and l look different, but when I use the spellchecker it shows another font which makes those look like the same letter.

**Comment by niksedk** [comment]
Could you re-test in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip ?

**Comment by howardmarshall** [comment]
already tested it after posting and it seems fine on beta.
