### ISSUE TITLE
Time Code Mode HH:MM:SS:FF causes  incorrect overlap detection

### ISSUE THREAD

**Issue by minimeh** [SubtitleEdit/subtitleedit#2692]
Using SE 2.5.4, build 207, scrolling the cursor through the subtitle list view while opting for Time Code Mode HH:MM:SS:FF causes incorrect overlap detection. Switching to Time Code Mode HH:MM:SS,MS fixes that.

Open the attached srt file. In list view, move up and down through the lines. If using Time Code Mode HH:MM:SS:FF, you'll see overlaps identified incorrectly. On the same file, no overlaps are detected with Time Code Mode HH:MM:SS,MS.

[test04.zip](https://github.com/SubtitleEdit/subtitleedit/files/1594947/test04.zip)

**Comment by niksedk** [comment]
Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip ?

I guess one could argue that the list view (in frame mode) should show overlap if rounding of ms to frames will result in the same frame for end current/begin next...

**Comment by minimeh** [comment]
In my limited testing it seems to be fixed. I didn't notice any unwanted side effects or regressions.

**Comment by OmrSi** [comment]
@niksedk Closed.

**Comment by OmrSi** [comment]
@niksedk I saw this while looking for the shortcut to change the time code mode, I remember using a hidden shortcut, something like "Control + Alt + Shift + F", but it doesn't seem to work. Is there anything like this?
