### ISSUE TITLE
Merging Lines Issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2693]
While merging two lines, is there any way to merge without having to auto break? Thanks in advance.

**Comment by niksedk** [comment]
What's the actual case? 
If I merge "Hello" + "friend." the result will keep the line break.

**Comment by LeonCheung** [comment]
Sorry for late reply. Yes, that's the point, without line break, that's what I expected.  I know I can select the merged ones then press "Unbreak" button. But for some reason, I need to often merge two lines without breaking, which means, I just want to use a "space" instead of <br />. Just like how SE handles while merging 3 lines now. I don't mean to replace the old behavior, just expecting a new operator (or shortcut setting) that can merge two lines without add breaks. Thanks.

**Comment by LeonCheung** [comment]
Oh, btw, this brings another problem with SE,: When I import texts by direcly pasting into List View, it will forcedly break long lines no matter what. And it adds a "-" to the end of the first line, which is really not expected.

**Comment by LeonCheung** [comment]
Ah, just found it's already listed in an old yet"daring" wish list  back to 2016. :P  #1968 (item 5)

**Comment by niksedk** [comment]
Examples?

**Comment by LeonCheung** [comment]
A quick note for a duplicate discussion thread #696
