### ISSUE TITLE
Deal with "l" (lowercase L) instead of "I" (uppercase i)

### ISSUE THREAD

**Issue by mzso** [SubtitleEdit/subtitleedit#2694]
Hi!

This is most common problem that remains after I run fix common errors.
examples: "Henry ll" "(READlNG lN LATlN)" "lndiana" "lDC." "But l..."

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
(Fixes "lndiana")

Try to look at "eng_OCRFixReplaceList.xml" to see how it's possible to improve the OCR fixes and add names/abbreviations to like "IDC" to the names list.
Notice you can enable "Fix common errors - also use hard-coded rules" in Options -> Settings -> Tools.

**Comment by mzso** [comment]
[**@niksedk**](https://github.com/niksedk) commented on [2018. jan. 2. 17:50 CET](https://github.com/SubtitleEdit/subtitleedit/issues/2694#issuecomment-354812689 "2018-01-02T16:50:51Z - Replied by Github Reply Comments"):
> Beta updated: [https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip)  
> 
> (Fixes "lndiana")
> 
> Try to look at "eng_OCRFixReplaceList.xml" to see how it's possible to improve the OCR fixes and add names/abbreviations to like "IDC" to the names list.  
> 
> Notice you can enable "Fix common errors - also use hard-coded rules" in Options -&gt; Settings -&gt; Tools.

I thought it would be possible fix these based on context, some filters work like that, right?
Many of these abbreviations might be rare or single use.

I mean something like replace lower case L in upper case words (which seems to be the most common), maybe the start of sentences (though this might be problematic). Or if they appear alone (instead of upper case "I") or as a group of "l"-s (roman numerals 1-3)


[**@niksedk**](https://github.com/niksedk) commented on [2018. jan. 2. 17:50 CET](https://github.com/SubtitleEdit/subtitleedit/issues/2694#issuecomment-354812689 "2018-01-02T16:50:51Z - Replied by Github Reply Comments"):
> Notice you can enable "Fix common errors - also use hard-coded rules" in Options -&gt; Settings -&gt; Tools.

Is this only in the beta? (I don't see it 3.5.4) What does it do?

**Comment by niksedk** [comment]
The "Fix common errors - also use hard-coded rules" is also available in previous versions:
![image](https://user-images.githubusercontent.com/1261331/34499828-4058a094-f008-11e7-8f27-4981750ab97f.png)

It does things like replacing lowercase L in uppercase words with uppercase "i" and stuff like that...

**Comment by mzso** [comment]
[**@niksedk**](https://github.com/niksedk) commented on [2018. jan. 2. 22:02 CET](https://github.com/SubtitleEdit/subtitleedit/issues/2694#issuecomment-354874489 "2018-01-02T21:02:58Z - Replied by Github Reply Comments"):
> The "Fix common errors - also use hard-coded rules" is also available in previous versions:  
> 
> [![image](https://user-images.githubusercontent.com/1261331/34499828-4058a094-f008-11e7-8f27-4981750ab97f.png)](https://user-images.githubusercontent.com/1261331/34499828-4058a094-f008-11e7-8f27-4981750ab97f.png)
> 
> It does things like replacing lowercase L in uppercase words with uppercase "i" and stuff like that...

It seems like I enabled that yesterday, coincidentally. (But I was looking for the misquoted option you provided so I didn't realize)

How does this relate to the "Fix common OCR errors (using OCR replace list)" option I always used within the "Fix common errors" tool? Because if it also uses a list it will obviously won't catch random acronyms and upper case words. What does the "hardcoded rules" part mean?

Also why is it hidden in the options menu unlike the other options. Shouldn't it appear as a sub-option of the "Fix common OCR errors (using OCR replace list)" in the "Fix common errors" window.

**Comment by mzso** [comment]
It looks like roman numerals are a particular weakness.
I guess the conversion feature doesn't work when the lower case "l" is the first character. (The ones in the middle of a word of capital letters are converted properly)
I think it should if an "l" is followed by an (or several) upper case characters or not a letter. eg: "lDC." "But l..." from the issue description.
