### ISSUE TITLE
"Replace musical symbols with preferred symbol" filter doesn't catch all symbols

### ISSUE THREAD

**Issue by mzso** [SubtitleEdit/subtitleedit#2695]
For example: ¶
There are other symbols that are commonly used, but I didn't make not of them.

**Comment by niksedk** [comment]
You can edit the symbols you need in Options -> Settings -> Tools -> Music symbols to replace

**Comment by niksedk** [comment]
But I'll add "¶" to the default values in next update, thx :)

**Comment by mzso** [comment]
Thanks, I never imagined there's an option for this in another place.

**Comment by mzso** [comment]
[**@niksedk**](https://github.com/niksedk) commented on [2018. jan. 2. 15:09 CET](https://github.com/SubtitleEdit/subtitleedit/issues/2695#issuecomment-354773769 "2018-01-02T14:09:32Z - Replied by Github Reply Comments"):
> But I'll add "¶" to the default values in next update, thx :)

Is it possible to add an isolated "d" (or "D" when it gets capitalized by a filter) to it. I'm seeing this a lot.
It's not practical to search and replace because it's on either end. And may or may not be between a space and line beginning/end because of hyphenation and italics, etc.

Example
```
00:01:49,681 --> 00:01:51,315
- <i>d it's okay d</i>
- <i>d Okay d</i>
```
```
44
00:01:53,352 --> 00:01:56,220
<i>d I guess you're stuck d</i>
```

Another when it accidentally gets capitalized by SE:
```
00:01:40,238 --> 00:01:42,305
<i>- D It's all good d</i> - <i>d All good d</i>
<font color="#FF8C00">Sync by Alice I www.addic7ed.com</font>
```
