### ISSUE TITLE
Use a font where all characters are distinguishable.

### ISSUE THREAD

**Issue by mzso** [SubtitleEdit/subtitleedit#2697]
Hi!

SE uses a font where "I" and "l" are not distinguishable. And by the looks of it you can only change that for the subtitle view. But not for the fix common errors, etc windows where you often can't tell what is changed. Because the changed text is not distinguishable.

I think this is rather counterintuitive in an application like this.

**Comment by niksedk** [comment]
What version are you using? Have you tried latest beta?

**Comment by mzso** [comment]
[**@niksedk**](https://github.com/niksedk) commented on [2018. jan. 3. 16:52 CET](https://github.com/SubtitleEdit/subtitleedit/issues/2697#issuecomment-355046523 "2018-01-03T15:52:40Z - Replied by Github Reply Comments"):
> What version are you using? Have you tried latest beta?

No, but didn't expect it to change since it has always been like this.

**Comment by niksedk** [comment]
Could you test the latest beta - and supply some screenshots?

**Comment by mzso** [comment]
[**@niksedk**](https://github.com/niksedk) commented on [2018. jan. 6. 12:34 CET](https://github.com/SubtitleEdit/subtitleedit/issues/2697#issuecomment-355741162 "2018-01-06T11:34:45Z - Replied by Github Reply Comments"):
> Could you test the latest beta - and supply some screenshots?

I tried it. It seems like the font was changed so now the "I" "l" characters are different. So I guess this issue is solved.

PS:
However I think it wouldn't hurt if you could change the font (and font settings) used on these parts of the GUI. (before/after views in the different tools, etc)
Also a nice thing would be if the characters that were changed and which are to be changed would be highlighted in the before/after text.
