### ISSUE TITLE
Unable to import Subs from Shameless S07 Blu-ray

### ISSUE THREAD

**Issue by Skaronator** [SubtitleEdit/subtitleedit#2699]
This is the first time after importing around 830 files that this kind of issue happened. Here is the error when imporing the *.sup file:

![image](https://user-images.githubusercontent.com/2886913/34587719-d470ccc8-f1a9-11e7-8f51-5a73e5b99615.png)

I tried to MakeMKV the file again and also tried to import the mkv directly (not even having a error, just empty)

MediaInfo says this file should have 2 elements as you can read here:
```
Text #2
ID                                       : 6
ID in the original source medium         : 4610 (0x1202)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 104 ms
Bit rate                                 : 5 384 b/s
Count of elements                        : 2
Stream size                              : 70.0 Bytes (0%)
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray
```

Here are the affected files: (5 out of 12 episodes from both disc)
[brokenSubs.zip](https://github.com/SubtitleEdit/subtitleedit/files/1604978/brokenSubs.zip)

Hope you can help me and thanks for this awesome tool!

**Comment by niksedk** [comment]
Thx for the files - always nice with files to look at :)
These files do not contain any bitmap data at all... only timestamps + picture resolution in the subtitle stream.

This file only has 35 bytes for a run-time-length encoding bitmap with a 256 color palette + resolution + timestamps + headers...

**Comment by Skaronator** [comment]
Thanks for looking at these files. I already guessed that they are some kind of "fake" subtitles.
