### ISSUE TITLE
Remove HTML tags

### ISSUE THREAD

**Issue by schoerg** [SubtitleEdit/subtitleedit#2701]
Maybe I haven't found it, but is there a way to remove HTML tags?

I have a subtitle file with something like this:

```
1
00:00:21,200 --> 00:00:24,960
<span style="style_2"> Things didn't always go entirely</i>
<span style="style_2">to plan on my journey with Alyssa.</i>
```
Which MPC-HC doesn't display correctly. Right now I remove those tags with another editor.

**Comment by niksedk** [comment]
In SE, Normally you can right-click on the selected lines in the list view and press "Normal (remove formatting)", but that only removes tags that SE use.

To remove a broader range of tags, you can use a regex like "<[^>]*>" via Edit -> Multiple replace.

**Comment by schoerg** [comment]
Thanks.
