### ISSUE TITLE
"Split Line at Cursor Position" is missing

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2703]
I think the function can be found through context menu, while it's not:
![qq 20180108235059](https://user-images.githubusercontent.com/494788/34678691-cae72532-f48b-11e7-9e0e-d6e700b37822.jpg)

It seems that, in order to see the menu item, each splitted line should have no less than **three** characters in each. Not sure if this is kinda bug.

**Comment by LeonCheung** [comment]
3.5.5 build 39
Hmm, true that it shows up in such case, however it fails to do it correctly.

**Comment by niksedk** [comment]
OK, what's wrong=

**Comment by LeonCheung** [comment]
![split](https://user-images.githubusercontent.com/494788/35767663-9bc2ad76-092b-11e8-92da-6b2fdae340a3.gif)
