### ISSUE TITLE
Reversed Numbers issue in OCR 

### ISSUE THREAD

**Issue by essam315** [SubtitleEdit/subtitleedit#2704]
In OCR via "Binary image compare" the numbers became reversed when "Right to left" is checked. And it is very annoying to try to fix the numbers manually. Like in this image.

![rev](https://user-images.githubusercontent.com/34485960/34811030-6afbc20e-f6a7-11e7-877f-2ef09c595a5a.png)

Lines: 9 and 10

Sub

[7.zip](https://github.com/SubtitleEdit/subtitleedit/files/1621442/7.zip)

OCR

[Ocr.zip](https://github.com/SubtitleEdit/subtitleedit/files/1621447/Ocr.zip)

Dictionaries

[Dictionaries.zip](https://github.com/SubtitleEdit/subtitleedit/files/1621452/Dictionaries.zip)

**Comment by Teko101** [comment]
عصام; ابعتلي حسابك على فيسبوك او  تويتر ، وانا هقولك على الريچيكس :)

**Comment by essam315** [comment]
@Teko101 
https://www.facebook.com/essam.mohammed.1460693
