### ISSUE TITLE
Error when addings subs in .xml 1.0 files

### ISSUE THREAD

**Issue by nathaniel1977** [SubtitleEdit/subtitleedit#2705]
When trying to add new subtitles at the end of an xml 1.0 file (a translation file created to the original template), the following error occurs.

https://www.dropbox.com/s/ghv7obu7s9qrzyc/Erro%20Subtitle%20EDIT.jpg?dl=0

Then I'm unable to save the file.

**Comment by niksedk** [comment]
Can you supply the file?
(also, it's probably "Timed Text 1.0".... and not ".xml 1.0"

**Comment by niksedk** [comment]
Is the problem still occurring in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip ?

**Comment by nathaniel1977** [comment]
Hi,

 

I’ve checked and unfortunately it’s the same with the new beta. The error comes up and then it’s impossible to save the file…

 

Regards,

 

W
