### ISSUE TITLE
Merge Multiple .db files!

### ISSUE THREAD

**Issue by Teko101** [SubtitleEdit/subtitleedit#2709]
Hi Nikse,

Is there anyway to merge multiple .db files?

As you know, in some languages (RTL 2 b specific) we're actually OCRing words, not just "single characters", and of course this needs so much time and effort just to build one appropriate database file for one single font! 

Currently, my friends and I are working together on different subs, yet we still don't know how we're gonna merge our .db files :(

For sure it would be awesome if you add that feature to SE, but it's okay too If you have any suggestions to help us achieving this... Thanks in advance :)

Regards
Teko

**Comment by niksedk** [comment]
Hi Teko101,

You can import the content of another .db file via the "Import" button (click "Edit" in the OCR window first)):

![image](https://user-images.githubusercontent.com/1261331/34952311-994dbf84-fa19-11e7-8258-82d1bac8121b.png)

**Comment by Teko101** [comment]
That's great, Thanks a lot Nikse :)
