### ISSUE TITLE
"No of pixels is space" in Binary image compare is not saved

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#2711]
Tested both on 3.5.4 98a355c and 3.5.4 build 226 (latest beta).

Issue: The value set in "No of pixels is space" is not saved. The value is always set back to 11 (8 for the latest beta), which is the default one.

![se](https://user-images.githubusercontent.com/3875423/34974558-102ffd08-fad1-11e7-8729-94315b4ca1bf.png)

BTW:
Binary image compare mode is **far more** efficient than OCR via Tesseract (at least) for PGS.
I highly recommend to use this mode for those who have trouble in OCR mode.

For the better use of this mode, some clarifications are needed.
- What do "No of pixels is space" and "Max. error%" mean? (I guess No of pixels is space is a number of pixels as space between characters.)
- How to adjust these values? (I figured 0.4 for Max. error% is quite ideal for most PGS, whereas the default value is 2.5. No of pixels in space varies from 11 to 13.)

**Comment by niksedk** [comment]
@taxen: yes, that is annoying... hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
Could you verify?

**Comment by taxen** [comment]
Build 234 (above beta) works just fine. Thank you for quick fix!

**Comment by niksedk** [comment]
thx for verifying :)
