### ISSUE TITLE
SubtitleEdit command line seems to be appending subtitle files

### ISSUE THREAD

**Issue by Rouzax** [SubtitleEdit/subtitleedit#2713]
Running SubtitleEdit 3.5.4
When I run `SubtitleEdit /convert *.mkv subrip /inputfolder:"C:\TEMP" /removetextforhi /fixcommonerrors`
I end up with an X amount of subtitles files depending on the number that are in the original video.
It seems however that the second file is the first subtitle and then the second subtitle is appended to that.
![image](https://user-images.githubusercontent.com/4103090/35157638-ddb5cbd0-fd34-11e7-8eda-8f1cd3de8718.png)
other example
![image](https://user-images.githubusercontent.com/4103090/35158578-cb801440-fd37-11e7-96d4-ccabaaa5d15d.png)

The result is an subtitle file that shows like this in the video:
![image](https://user-images.githubusercontent.com/4103090/35158246-d4220df2-fd36-11e7-80a2-4e9156de474c.png)

Would it also be possible to only export and convert the first subtitle from the videofile?

**Comment by niksedk** [comment]
Hi @Rouzax: Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip ?

**Comment by Rouzax** [comment]
Will give it a try and let you know.
Would it also be possible to have more control over the file naming? Right now it uses underscores `_` while all my post processing like Medusa expects dots `.`

**Comment by Rouzax** [comment]
Using version
![image](https://user-images.githubusercontent.com/4103090/35182453-f356b804-fdd5-11e7-9782-2919f33d79fd.png)

Still the same issue.
![image](https://user-images.githubusercontent.com/4103090/35182468-19d1f426-fdd6-11e7-8d68-4ff991853dfa.png)

**Comment by niksedk** [comment]
Strange... could you attach/email the mkv without video and audio (with mkvtoolnix) so I try your file?

I guess SE could use dot instead of underscore...

**Comment by Rouzax** [comment]
Here you go. This is just 1 example I've seen it in other files as well.
https://cloud.mgdn.nl/s/9rREM5otXD0Qtzo

**Comment by niksedk** [comment]
thx :)
New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by Rouzax** [comment]
Does this includes dots instead of underscores?

**Comment by niksedk** [comment]
I think so...

**Comment by Rouzax** [comment]
Mysterious :)
Will give it a go.

**Comment by Rouzax** [comment]
This looks very good thank you!
![image](https://user-images.githubusercontent.com/4103090/35184426-f1545690-fdf5-11e7-8957-5a083a3bbf4c.png)

**Comment by niksedk** [comment]
OK, new beta up where `/removetextforh` and `/fixcommonerrors` will run in the order that you specify via cmd line (can even be multiple times): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by Rouzax** [comment]
To be honest that was just my thinking, is there any reasoning to it?

**Comment by niksedk** [comment]
Yes...

**Comment by Rouzax** [comment]
@niksedk Because I put every file through SubtitleEdit command line, sometimes it will try on a file with no subtitle embedded.
Right now I get an error message input file too large
```
Subtitle Edit 3.5.4 - Batch converter

the.big.bang.theory.s11e14.1080p.web.x264-tbs.mkv: subrip - input file too large!

0 file(s) converted
```

**Comment by Rouzax** [comment]
@niksedk Thank you!
One last question, is the command line using the settings that are in the `settings.xml` in regards to the Common Errors and the removal of HI?

**Comment by niksedk** [comment]
Yes, the current setting are using for `Fix common error` and `Remove text for HI`  .
