### ISSUE TITLE
Handling of line breaks

### ISSUE THREAD

**Issue by mkver** [SubtitleEdit/subtitleedit#2716]
Hello,

first some observations: 
a) it seems that SE only treats \r\n as real line breaks; \r or \n is not treated as such (it is not shown as newline) even if I use UTF-8 and although Unicode treats singular \r and \n as line break, too.
b) When loading a subtitle file, singular \r and singular \n and \r\n are all treated as \r\n. (This does not happen when inserting something from clipboard; then it is inserted literally.) \r\r\n is treated as \r\n.
c) In regex replace mode (it doesn't matter whether in the simple replace mode or in multiple replace mode), SE treats \r and \n as the usual special characters for carriage return and newline in the search form; but in the replace form, \r is not treated specially at all any more (but literally as "\r") and \n is treated as carriage return and newline (i.e. replacing \n by \n inserts additional carriage returns that aren't displayed at all due to a)).

a) and c) together can lead to a situation like the following: Some subtitles also set the - in italics when the rest is like in the following situation:
```
1
00:00:01,000 --> 00:00:03,000
<i>- First line.
- Second line.</i>

```
I don't like the dashs to be in italics, so I at first tried to replace the `^<i>- ([^<]*)\r\n- ` with `- <i>$1</i>\r\n- <i>`. It matched, but it also inserted "\r". Therefore I thought that maybe SE treats \n as a generic linebreak and therefore I deleted the \r both in the search and the replace pattern. (I explained the fact that \r\n matched originally with it being a special case that is handled separately.) It still matched and according to the preview in the multiple replace window it did what I wanted, therefore I applied it. It also seemed to work when I looked at it in the normal SE window. Therefore I saved it and muxed the subtitle into a movie file; but when looking at this movie, there now is an additional empty line between the two lines. And when opening the subtitle with SE, there now is an additional line, too. It turned out that \r is now matched by [^<]* so that the interesting part of the result is `\r</i>\r\n- <i>`.

I regard a) as the culprit (b) is not wrong and changing c) (if at all possible -- you are after all relying on the .NET regex engine, right?) would be a disruptive break with little too no gain). SE should have shown me what error I had made in my regex, but didn't and a) is to blame for this. Can this please be fixed?

Greetings
mkver

**Comment by niksedk** [comment]
thx for the info :)

I've tried to fix the replace issue with new-line/regex in latest beta:  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

Also, how and where do you inserting something from clipboard?

**Comment by mkver** [comment]
It looks as if \r and \r\n doesn't match anything at all any more in the new build (build 249). This will definitely break a lot of stuff.
I insert from clipboard via Ctrl+V while the cursor is in the text field.

**Comment by niksedk** [comment]
New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip
It's supposed to work like this: both "\r\n" and "\n" works in find/replace (I will mention "\n" as line break in the help) and the result is Environment.NewLine (\r\n in windows and \n on linux).
Also `Replace` and `Multiple replace` should work the same, thx.

**Comment by niksedk** [comment]
Beta updated again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by mkver** [comment]
Pasting from the clipboard works well now.
