### ISSUE TITLE
Converting files to UTF-8 on linux creates weird characters, same doesn't happen on Windows

### ISSUE THREAD

**Issue by Nottt** [SubtitleEdit/subtitleedit#2720]
[sample.txt](https://github.com/SubtitleEdit/subtitleedit/files/1658853/sample.txt)

This a sample that gives weird characters on linux, but not on Windows. I renamed it to .txt so github would let me upload it, it's a SRT file. I'm converting it to WebVTT UTF-8

On linux I'm using ubuntu 16.04, plus mono + the portable .exe

On windows is Windows 7 with 3.5.4 subtitle edit.

Any idea why this could be happening?

**Comment by niksedk** [comment]
It's probably because the attached file is not saved in UTF-8... looks like Windows ANSI code page 1252.
Just save in UTF-8 (if possible).

**Comment by Nottt** [comment]
What I'm saying is that saving it as UTF-8 on Windows works ok, but on
Linux the conversion is messed up.

I know the original file is not UTF-8, that's the point.

**Comment by niksedk** [comment]
Ah. Are you using Subtitle Edit on Linux?
You might need to try File -> Import subtitle with manual chosen encoding...

**Comment by Nottt** [comment]
I'm using batch convert on both OS. Is this a known issue on Linux?

**Comment by niksedk** [comment]
Yes, sorry. Auto detection of ANSI code is better on Windows.

**Comment by Nottt** [comment]
Well that sucks, thanks.

**Comment by niksedk** [comment]
ANSI coding sucks!

**Comment by Nottt** [comment]
I do wish all respectable subtitles repositories just mass-converted
everything to UTF-8. Why people still encode subtitles without UTF-8 is
beyond me...

**Comment by darnn** [comment]
Hey, for a long time Subtitle Workshop 2.51 was the standard, and it didn't have UTF8 support. I also remember a time when there was such a thing as a DVD player that played XviD files, including subtitles, but only if you did them just so, and part of it was that they had to be ANSI (at least in Hebrew).
