### ISSUE TITLE
Remove color codes when converting timed text 1.0 to srt

### ISSUE THREAD

**Issue by PannenkoekenNL** [SubtitleEdit/subtitleedit#2722]
When convert a timed text 1.0 subtitle file to srt the color codes remain, I have to manually do find and replace. Could these please be automatically removed?
```
<font color="#FFFF00"># Sóc graciós, divertit.</font>
<font color="#FFFF00">Sóc genial i tothom s'enfada amb mi.</font>
<font color="#00FFFF">No siguis vergonyós! Digues</font>
<font color="#00FFFF">alguna cosa als avis de Kyushu.</font>
```

I've uploaded a example of a timed text 1.0 file with color codes (downloaded from Catalan public television):

[209.zip](https://github.com/SubtitleEdit/subtitleedit/files/1663085/209.zip)

**Comment by mkver** [comment]
You don't have to do it manully be find and replace: Select the whole subtitle (all lines), right click and select "Normal (remove formatting)". This will remove color information (as well as other formatting).

**Comment by PannenkoekenNL** [comment]
Thanks, that works.

**Comment by OmrSi** [comment]
@niksedk Closed.
