### ISSUE TITLE
Something about "Insert subtitle here..."

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2724]
![insert](https://user-images.githubusercontent.com/494788/35469771-89f8c738-0377-11e8-8577-9b7fc7cf87e9.jpg)
It seems that this option doesn't show up every time. A fishy bug maybe? Or, is it designed for only showing up at the end?

**Comment by niksedk** [comment]
Yes, it designed only to show at the end... to insert a subtitle file in the middle of another subtitle will complicate things a lot.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Omg, that's exactly what I dreamed thanks a ton Nikolaj! My two cents:

1. Just wonder a bit on why the menu doesn't show up ahead of any line, say, around 1-3s as far as I tested.
2. I can see the insert action that's going to cause overlap is forcely banned, that's okay, though I suppose it be convenient for a "Are you sure?" warning for those who would like to take the risk, since they are willing to fix it afterwards. Secondly, for some advanced formats like .ass/ssa, overlaps really doesn't matter and sometime are actually needed.

**Comment by LeonCheung** [comment]
Yes, the 2nd point is perfect now. Thank you. :)   Yet still wonder on why it doesn't always show up.

**Comment by niksedk** [comment]
I don't want it to popup when clicking on a subtitle...

**Comment by LeonCheung** [comment]
I know, what I mean is:

![new](https://user-images.githubusercontent.com/494788/35612775-f701f9e6-06a4-11e8-8fe4-08fc9e9f2fd6.gif)
