### ISSUE TITLE
Please add option for capitalized name after title.

### ISSUE THREAD

**Issue by 791** [SubtitleEdit/subtitleedit#2728]
In tools/change casing/normal casing, or there about:
ex. "Dr. newman" should get changed to "Dr. Newman." Titles such as Dr., Mr., Mrs., etc.

**Comment by niksedk** [comment]
SE will now do this check, but only for English atm.:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
