### ISSUE TITLE
Change casing tool not refreshing its form.

### ISSUE THREAD

**Issue by 791** [SubtitleEdit/subtitleedit#2729]
In tools/change casing/Fix names casing => "change casing - names" form:
the left "preview" listview is not updating to current text state on main form listview. It retains the original inputted file text state after editing. So prior any editing or running of change casing is not updating that listview. Please update this form to refresh the left listview data during form open event etc.

**Comment by niksedk** [comment]
Sorry, I don't know what you mean - perhaps an image would help?

**Comment by 791** [comment]
After running and making changes with fix names casing, subsequent opening of the change casing still shows the original unedited text. It should show the updated changed text for comparison to the newly selected options.
![4](https://user-images.githubusercontent.com/10005168/35779240-b92d1ae2-0997-11e8-8077-bc529132b3f1.jpg)

**Comment by niksedk** [comment]
OK, reopening will re-run change casing... you probably want to run only "Fix only names casing"...
