### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by shogunreaper** [SubtitleEdit/subtitleedit#2730]
Why do you have to manually download updates?

Why not just do it within the program itself?

**Comment by niksedk** [comment]
A PR is welcome :)

**Comment by shogunreaper** [comment]
a pr? whats that?

**Comment by niksedk** [comment]
Sorry, a "PR" is a "pull request" - a way to contribute to a GitHub project: https://help.github.com/articles/creating-a-pull-request/

I don't find this feature very important as the current update notifier works okay, and  I have so many other features I would rather create, but if you (or someone else) can fix this, then a PR is welcome.
