### ISSUE TITLE
NULL chars added right before line end

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#2732]
Tested both 3.5.5 (build 1) and 3.5.5 beta (build 17 & 18).

Procedure:
1) Open MKS file (made by mkvmerge v20.0.0, attached as sub1.zip) as in ASS format.
(Strangely, two <br \/> between lines instead of just one, at this point --> this is also an issue, but I do not know if mkvmerge is the cause.)
2) Select all lines and do 'remove line-breaks from selected lines' (to solve above two <br \/> problem).
3) [tools] -> [fix common errors] and do [fix missing space] (at least, other options are shown below image) -> [apply selected fixes] and OK.
![options](https://user-images.githubusercontent.com/3875423/35663054-c4a9e836-075e-11e8-8f83-cfd1ac5be236.png)
4) Change format to SRT while encoding keeps UTF-8.
5) Save as SRT (attached as sub2.zip) and exit SE.
(At this point, when open the SRT file in text editor, each line has U+0020 right before the line end (0x0D 0x0A). This text editor I use changes NULL char into a space according to its document.)
6) Open above saved SRT and just save without doing anything other. (This SRT file is attached as sub3.zip.)
Now, all the NULL chars are gone.

So, I am guessing unnecessary NULL chars are added during 1) and 4).
3) [fix missing space] seems to be the problem, but is not... because without 3), the result is the same.

[sub1.zip](https://github.com/SubtitleEdit/subtitleedit/files/1684308/sub1.zip)
[sub2.zip](https://github.com/SubtitleEdit/subtitleedit/files/1684310/sub2.zip)
[sub3.zip](https://github.com/SubtitleEdit/subtitleedit/files/1684312/sub3.zip)

**Comment by taxen** [comment]
Also the result is the same as 1) by 'import subtitle from Matroska (.mkv) file...' from directly MKV file.
So mkvmerge seems not to be a problem.

**Comment by mkver** [comment]
I just tested the first line in the mks-file and the NULL is already there: It ends with 0x2E, 0x2E, 0x2E, 0x00.

**Comment by niksedk** [comment]
Thx for the info :)
@mkver: and thx for pointing to the spec - I was not aware of strings in mkv MAY be null terminated.

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
Okay now?

**Comment by mkver** [comment]
Strings can be padded with null; but the content of blocks is officially a "binary" (i.e. not interpreted by the EBML parser at all) and therefore I don't know whether this rule applies to subtitles at all (the rule about strings applies e.g. to the title or the track titles).
And your commit removes NULL chars from Matroska input, but it doesn't remove them from other input (e.g. if I open the mks file with an old version of SE ("old" like the current release version) and store it e.g. as ASS or so, then this file (opened with current beta) will still have NULL chars) and it doesn't check for other illegal characters.
And isn't it actually against the spec if you ignore one newline in any pair of newlines directly following each other?

**Comment by niksedk** [comment]
@mkver: 
Yes, it's probably a bad idea just to remove "double new lines" - could be made on purpose perhaps. Changed back in 814d01dd70fefd63307bca8b35764fc452cd00e6.
Not sure what to do with binary zeroes... any good ideas?

**Comment by mkver** [comment]
Binary zeros and other illegal characters (what counts as "illegal character" is of course dependent on the used encoding) should be discarded upon importing anything to SE.

**Comment by taxen** [comment]
@mkver Thank you for inspecting the issue.

@niksedk How about adding another option something like 'remove NULL char in line end' in [Tools][Fix common errors...]?
The fact that the 2nd saving removes NULL chars even in current versions suggests SE somehow removes NULL chars. So, it is not difficult to make such function as an option, I guess. That way, we can deal with the issue without opening a subtitle with NULL chars twice.

**Comment by niksedk** [comment]
OK, I guess SE could automatically remove `Control characters` - could perhaps be controlled by a secret setting...

**Comment by taxen** [comment]
@niksedk Thank you! Tested build 68 and it works fine!
Doing my procedures 1) through 5) does not reproduce the problem. NULL chars are not there.
