### ISSUE TITLE
\n Missing with Replace Tool

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2734]
(v3.5.5 build 23)

While replacing via Ctrl H tool (regex mode), \n disappeard when open Ctrl H window again, but it seems still there in the "background". Try this:
![regex](https://user-images.githubusercontent.com/494788/35688431-2115d3f8-07ac-11e8-873b-51de74a96a7a.jpg)
However, it works alright with the Multiple Replace tool.

Thanks for checking.

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Thanks! Just tested, I don't know how to discribe the issue here, please see GIF below:

![test](https://user-images.githubusercontent.com/494788/35690968-3e41b8ce-07b2-11e8-8455-b594402e41a7.gif)

**Comment by niksedk** [comment]
Yeah,,, seems to be complex...

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Works perfect now. :D
