### ISSUE TITLE
[Idea] Allow Backward finding and replacing

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2736]
The current finding/replacing the next match, not previous. I mean, at least there should be a **Shift F3** or something? Just a rough idea here.

**Comment by LeonCheung** [comment]
Duplicated

**Comment by OmrSi** [comment]
The replacement part wasn't included in the new one...
I don't think it's important to me, don't know for others.

**Comment by LeonCheung** [comment]
Haha, I think it is well noticed by the guy over there. I bet it's already in the todo list.
