### ISSUE TITLE
[Idea] Import Plain Text: Every N Lines per subtitle

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2737]
Proto:
![proto](https://user-images.githubusercontent.com/494788/35692614-cc14e14a-07b6-11e8-9504-ded34c08a655.jpg)

This would be a nice timesaver for importing raw texts with formats like above, especially for making bilingual/trilingual subtitles. :)

**Comment by gabriellluz** [comment]
I'm pretty sure there's a plugin which you could merge two subtitles one on top of another BUT I think you need that because of most Chinese movies that show Chinese subtitles above and English subtitles below. Is that correct?

**Comment by LeonCheung** [comment]
@gabriellluz Yep, you can say that. :) In a collaboration workflow, the plain texts received by a subtitler from translator/client can sometimes be like such format, in orther words, they left no blank lines for subtitler to split by, which can be really awkward...

**Comment by LeonCheung** [comment]
Thanks to Nikse, it is well implemented.
