### ISSUE TITLE
[Idea] Unbreak without spacing

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2738]
This is very convenient for languages such as CJK or Thai, since the extra space being added after unbreaking can be often unwanted for CJK subtitlers, which normally don't use spacesbetween words/characters.

My two cents would be to introduce a kind of concept: **Soft/Hard Unbreak**:

1. A **soft unbreak** works as normal, which means spacing would be gently added.

2. While a **hard unbreak** simply does nothing fancy other than removing the break. Hmm, otherwise should we call it **CJK unbreak** or something? jk lol

**Comment by niksedk** [comment]
Should it work on `selected lines` or just in `text box for current sub` ?

**Comment by LeonCheung** [comment]
Both I should say. Same as the current unbreak. :)  I think it can be either added as another shortcut entry for customize, or exposed as a button there. Your choice.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
New shortcut is under "General"

**Comment by LeonCheung** [comment]
Perfect! Hurray for SE!
