### ISSUE TITLE
HI removal misses parts that should be deleted

### ISSUE THREAD

**Issue by Rouzax** [SubtitleEdit/subtitleedit#2740]
Using the latest beta there are parts that are not deleted from the subtitle when using `Remove HI`
![image](https://user-images.githubusercontent.com/4103090/35752475-6ef8af04-085c-11e8-95e6-f4386cbddaf7.png)

**Comment by niksedk** [comment]
Those longer texts before a colon is tricky... slightly improved in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

**Comment by Rouzax** [comment]
I can understand that  it's tricky and better to leave to much text than to remove too much.

**Comment by niksedk** [comment]
Yes exactly, but do post if you come across other issues.
