### ISSUE TITLE
Remove text for HI feature request: "only if in separate line" function for "remove interjections"

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2741]
The subject sums it up, but to elaborate: If I'm translating English subtitles into another language, I omit the interjections in most cases. But sometimes when they're part of a larger sentence ir helps to have them in the subtitle. However, I know I can always safely omit them if the'yre their own subtitle. So I know I can always remove, e.g., these:
![se-hi-remove-interjections-separate-line](https://user-images.githubusercontent.com/19672444/35753200-63d1252e-0867-11e8-9aa0-efc9f4580536.png)

And right now I have to select them by hand each time.

**Comment by niksedk** [comment]
OK, could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip ?

**Comment by darnn** [comment]
Seems to be working so far! Thank you!!
