### ISSUE TITLE
[Feature Request] Improve Line Splitting

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2742]
As mentioned by @OmrSi at #2710, and myself at #1968, I believe that splitting by auto duration guess is not  suitable for every split, thus we have to manually adjust timings for both lines after that.  In other words, it would be convenient to implement kinda "**Split by dual-cursor positions**" feature. What do you think? Thanks.

**Comment by LeonCheung** [comment]
Oh just found another duplicate issue kept open 4 years ago... #49. FYI.  (sorry but I didn't even remember I had posted the very idea before...)

**Comment by OmrSi** [comment]
It would be a very useful feature :D

**Comment by MaximPro** [comment]
yes!

**Comment by niksedk** [comment]
Could you guys give latest beta a run: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
New shortcut + context menu item in the textbox

**Comment by LeonCheung** [comment]
Great to see it's finally in! As tested, it works nearly perfect. Just one problem, which is similar to the problem being exposed on issue #2703. FYI.:

![6688](https://user-images.githubusercontent.com/494788/36186852-9ef1b574-117c-11e8-8e69-ea79ee8e2a01.gif)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
Two characters are required before/after split.

**Comment by LeonCheung** [comment]
Hi, I think this time the waveform was split correctly, just the textbox split issue is still there. Actually the "Split line at cursor location" issue as mentioned at the #2703 hasn't been well solved, either. Should we reopen that issue or wait for an incoming beta? :)

![6](https://user-images.githubusercontent.com/494788/36243843-8a540b52-125e-11e8-9a99-e5f1018dc919.gif)

**Comment by MaximPro** [comment]
@LeonCheung Great way to show Problems! (with videoscreen converted gif's)

@niksedk Is there a standard Hotkey possible for Line skipping? 
because that are really important steps each project require several line breaks

Great to see you care for us so much! Thanks!
Will send you soon some money ;)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

@MaximPro: What do you mean by "Line skipping"?

**Comment by LeonCheung** [comment]
@niksedk It works great now. Thanks a lot!

**Comment by niksedk** [comment]
@LeonCheung: Cool, thx for testing :)
