### ISSUE TITLE
Batch convert fails every time in the latest build..

### ISSUE THREAD

**Issue by readdict** [SubtitleEdit/subtitleedit#2743]
Build convert fails with status message: "Save: Object reference not set to an instance of an object."

Using stable version 3.5.5 it works fine, so it's the latest Beta build that is broken.

**Comment by niksedk** [comment]
Hm, I cannot re-create this... is it all subtitles? What are your settings?

**Comment by niksedk** [comment]
OK, thx - got it now :)
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

**Comment by readdict** [comment]
Hey mate, oh great, I was about to ask you how/where to submit my settings file ;)...
