### ISSUE TITLE
Play rate (speed)

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2745]
I've been using SE for about two years, and I never realized you could change playback speed! I never use the waveform, so I just never saw the controls, and they're not mentioned in the help file (at least not using the words "rate" or "speed").
So, I'd like to suggest adding it to the help file, and request displaying another instance of the controls somewhere outside the waveform window, e.g. in the toolbar.
Those are the main things, but also, if you're feeling up to it, I'd really love the ability to set shortcut keys for every speed, and, if possible, have more speed options, in particular x2, x2.5 and x3 (the highest you can reasonably use for anything subtitle-related, in my experience). This could be very useful for proofreading.

**Comment by LeonCheung** [comment]
Nice idea. Maybe we could create a manual/wiki repository, for anyone who can freely contribute and keep it updated for others to see release notes, to learn what's new in the latest version better than a simple change log, for beginners to do self-learning and so on.  **.rst** is my two cents. Oops, off topic...

**Comment by LeonCheung** [comment]
@darnn Just a bit curious, how come you never use waveform in making subtitles? How would you define the start/end time for each line efficiently?

**Comment by darnn** [comment]
I don't synchronize myself, I only translate. The company I work for pays pennies for synchronization, unfortunately. Anyway, when I used to dabble in it for one-off projects or my own things, I would just get a good feeling for when to press the keys so that the offset is roughly the same, and shift everything ~300ms back. It worked well enough, occasionally I had to add/subtract an extra 100/200ms by hand.

**Comment by LeonCheung** [comment]
I see, making sense then, and I think you really should have learnt about waveform earlier, since it's veeeery handy for that. Talking about the 2X, 2.5X, 3X thing, I think 2X can be sometimes accepatable and needed, but believe me, 3X is a bit too fast for most cases, you know, in which one can hardly get anything right. Anyway, maybe you could.  :)

**Comment by darnn** [comment]
Oh, 2-3x would just be for proofreading and such. But it's still handy. Sometimes I just get proofreading jobs and I don't have to focus as much on the source as I do on the subtitles.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
Shortcuts for speeding up/down added (Video). Works via 10% steps from 50% to 300% play rate.
Would 25% steps be better?

**Comment by darnn** [comment]
Works great!!
10% increments are fine, I think. It's what the podcast player I use has, as well as the Chrome plugin to change video speed, and I never found myself wishing for more options.

I still think it would be nice to have an optional display of the speed in the toolbar (like the "show framerate in toolbar" option), but that's a much lower priority, obviously.

Also, I can't seem to find it right now, for some reason, but Leon's original issue about playback speed is still present: When you modify the speed and then open a new video file, SE still reports the higher speed value, but playback is actually at 100% until you modify the speed again. So, for instance, if I change the speed to 150% and then drag another video file to the video pane, that file will now play at 100%. But if I use the keyboard shortcut to increase the speed, it will increase to 160%.

**Comment by niksedk** [comment]
@darnn: thx for testing + info :)
Should play rate reset to 100% when loading a new video or keep old play rate?

**Comment by darnn** [comment]
I think it should keep the old play rate and reset when SE is closed. That's how VLC does it.

**Comment by LeonCheung** [comment]
Works great here too. Many thanks. I just wonder if it would be cool to expose the rate percentage with the same style like the zoon in/out thing in the same bar, with which we can simply tweak it by mouse wheel scrolling. Just brainstoming here. :)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
Should keep the play rate I hope :)

Also, next SE version will be out soon.

**Comment by darnn** [comment]
Works great!

**Comment by niksedk** [comment]
Help file updated: http://www.nikse.dk/SubtitleEdit/Help#playrate

Also, let me know if other stuff are missing/bad :)
