### ISSUE TITLE
Command line execution problem introduced in 3.5.5

### ISSUE THREAD

**Issue by key2029** [SubtitleEdit/subtitleedit#2746]
The command line execution shows an extra prompt upon exit when null redirection or echo off is issued.

Try the following command in cmd.exe and see the problem:
>nul SubtitleEdit.exe /convert

or a batch file:
@echo off
1>nul 2>&1 SubtitleEdit.exe /convert

No matter the conversion is fail or success, error or not, it just shows the prompt. This problem does not exist in version 3.5.4.

**Comment by niksedk** [comment]
Do you also have the problem in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip ?

**Comment by key2029** [comment]
Ok, it has no problem.

**Comment by niksedk** [comment]
thx for verifying :)
