### ISSUE TITLE
On Linux (ubuntu 16.04) translate fails...

### ISSUE THREAD

**Issue by hafuz** [SubtitleEdit/subtitleedit#2750]
On Linux (ubuntu 16.04) translate subtitles fails with the error:

System: Error: SendFailure (Error writing headers)

Is there a way to make it works ?

Thanks

**Comment by deniskx** [comment]
Same problem. Recently everything worked on Xubuntu 16.04.3 x86, but I reinstalled the system clean and there was an error. I believe, perhaps
- Previously, there were some packages or configs with other programs that helped in work
- Google switched to https and nttp requests no longer supported
On the Internet they writes that mono does not trust any certificates by default. The instructions for adding certificates did not help.
I install SubtitleEdit in Windows 7 in VirtualBox. Besides mono-complete a lot of trash.

**Comment by deniskx** [comment]
I checked in Fiddler, SubtitleEdit perform HTTPS request immediately https://translate.google.com/?hl=en&eotf=1&sl=en&tl=ru&q=Hello%20Hi%0A%0A%0A%20My
Most likely it always been. Certificate is normal. But answer is gzipped, which is not indicated in server header. Only Transfer-Encoding: chunked. Maybe this is the problem. IE still unpacks page and mono is not.
[response.txt](https://github.com/SubtitleEdit/subtitleedit/files/1878576/response.txt)

**Comment by rcspam** [comment]
Thanks, It works like a charm...

**Comment by hafuz** [comment]
Thanks, it works for me too.....
