### ISSUE TITLE
"Use source folder" option for batch conversion output folder

### ISSUE THREAD

**Issue by mzso** [SubtitleEdit/subtitleedit#2753]
It'd nice to have this.
It has a whatever folder by default, and it saves the last folder used. I usually end up converting to the wrong folder.
It would be particularly useful when extracting subtitles embedded into videofiles.

**Comment by mzso** [comment]
Also when I have a bunch of files, each within their own sub-folder it's a pain copying into each one-by-one.

**Comment by OmrSi** [comment]
@niksedk This is implemented. :)

**Comment by mzso** [comment]
> 
> 
> @niksedk This is implemented. :)

In which version, and in what fashion?

**Comment by OmrSi** [comment]
![image](https://user-images.githubusercontent.com/20923700/71922795-50476b00-3194-11ea-801c-3c3920047db9.png)

**Comment by xylographe** [comment]
@mzso  I think, [SubtitleEditBeta](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip) will be required.

**Comment by mzso** [comment]
[**@xylographe**](https://github.com/xylographe) commented on [2020. jan. 7. 21:28 CET](https://github.com/SubtitleEdit/subtitleedit/issues/2753#issuecomment-571757024 "2020-01-07T20:28:01Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) I think, [SubtitleEditBeta](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip) will be required.

Thanks.
