### ISSUE TITLE
Alignment tags in .stl text formats

### ISSUE THREAD

**Issue by Shas2509** [SubtitleEdit/subtitleedit#2755]
The tags for alignments like top/bottom/center/left/right are not correctly translated to formats like DVD Studio Pro and Spruce .stl.

Alignments in the project/list view are always done via anchors as in the Subrip format .srt.
So the Source looks like this: 
SubRip .srt
1
00:00:05,141 --> 00:00:07,344
{\an8}Test

However, when exporting/saving to Spruce .stl it takes the anchor as text, 

Spruce .stl
00:00:05:04,00:00:07:09,{\an8}Test

or simply removes it completely when exporting to DVD Studio Pro .stl

DVD Studio Pro .stl
00:00:05:03	,	00:00:07:08	,	Test

Ideally the subtitle lines with alignment anchors in an .stl should receive an alignment argument before the line with the anchor and one after that to return to the standard alignment, which for ease of use I would always assume center/bottom, unless you allow for editing project settings wich are reflected in the file header, which would then define the standard alignment. So in the case of this example the lines should read:

$VertAlign          =   Top
00:00:05:04,00:00:07:09,Test
$VertAlign          =   Bottom

and

$VertAlign          =   Top
00:00:05:03	,	00:00:07:08	,	Test
$VertAlign          =   Bottom

It would be great if this could be implemented/fixed. 

I am also not sure if it makes sense for the Spruce Subtitles With Spaces format, if the header contains
$HorzAlign          =   Left
and then there is a
$HorzAlign          =   Center
before each subtitle line, changing the header might be a little more clear.

**Comment by niksedk** [comment]
@Shas2509: How is "DVD Studio Pro" in this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip ?

(spruce not fixed yet)

**Comment by Shas2509** [comment]
@niksedk Wow, I didn't expect such a timely response, you are really fast. :)

The beta works just fine if you have standard subtitles, which means they are all bottom/center and you put them to the top if there is burnt in text on the bottom of the video.

I think this is 99% of the use cases, at least for me and all the production scenarios I have seen so far, so I could live with it. ;)

I did test another anchor wich would put the subtitle to the top and right, Result was the same as with the anchor that just puts the subtitle to the top, meaning that the subtitle would appear in the top middle and then revert to bottom middle.

So while Subrip has 9 anchors for the nine directions including the center of the screen, the .stl Text versions have two tags with 3 parameters each.

$VertAlign = Top/Center/Bottom
$HorzAlign = Left/Center/Right

I am not sure if this was just a test if it worked at all and you didn't put in all cases by purpose, but you never know. ;)

I would assume 

$VertAlign = Bottom
$HorzAlign = Center

as the standard which should also be written in the header (unless you would also be making the header editable in SE).

For every Anchor there would need to be the corresponding combo of commands, if there is more than one direction changed. 

The icing on the cake would be, if the code realised if only one or more directions are changed, and if one ore more subtitles following each other have the same anchor, because you can actually put several subtitles inbetween positioning commands, which makes it easier to read if someone only has a texteditor at hand. But always using the combo of 

$VertAlign = ??
$HorzAlign = ??

before and

$VertAlign = Bottom (or whatever is written in the header)
$HorzAlign = Center (or whatever ist written in the header)

after each subtitle that has an anchor would be a valid subtitle.

**Comment by niksedk** [comment]
OK, I've tried to do what you suggest: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
How does that work?

**Comment by Shas2509** [comment]
hm. Converting an .srt to DVD Studio pro works like a charm, with one exception. I've asked a friend to import the subtitle into DVD Studio Pro, and apparently there need to be tabs or spaces before and after the = otherwise DVD Studio Pro ignores the command.

On a side note, he also mentioned the header is wrong, as $Italic             =   0 should be $Italic             =   FALSE

We've also tried importing the STL and convert back to SRT, which also seemed to work fine.

We then tried to trick SE, and manually edited the header to vertalign = Top, which imported by adding vertalign = Top before the first sub and writing the standard bottom/center header.

So I "think", with the exception of the tabs/spaces around the = and the correct $Italic             =   FALSE, everything should be working as intended... unless I missed something. Never can be 100% sure. ;)

**Comment by niksedk** [comment]
Thx for testing :)

New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
Spaces around "=" added + `$Italic = FALSE` in header.

**Comment by Melbar666** [comment]
In the method 'GetAlignment' you should make the comparisons case insensitive, so that, for example, not only "Top" but also "top" and "TOP" is being parsed.

**Comment by niksedk** [comment]
@Melbar666: thx, that's actually why I used the `Equals` instead of just `==`, but I just forgot to add the case insensitive parameter...

**Comment by Shas2509** [comment]
I tested by creating an .srt, converting to .stl, renaming to eliminate chance of something being in the cache, re-importing the .stl. and the anchors were restored correctly. Only Anchor "getting lost" when re-importing is the Anchor for bottom down, as that is the standard for "naked subs" without Anchor, but I would see that as working as intended.

DVD Studio Pro also seems to import the files correctly.

**Comment by niksedk** [comment]
Thx for verifying :)
