### ISSUE TITLE
Another issue with RTL in MPV preview

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2756]
Hi!
3.5.5 build 44.
It seems that if you're in RTL mode and you have a subtitle that contains both a RTL language and a LTR language, the order gets messed up in the preview. If your subtitle is composed of (RTL chunk 1) (LTR chunk) (RTL chunk 2), the order will be reversed, i.e. (RTL2)(LTR)(RTL1). As seen here:
![se-rtl-two-languages](https://user-images.githubusercontent.com/19672444/36038192-af162f9c-0dc7-11e8-89e5-f999d438abb5.png)

**Comment by niksedk** [comment]
Could you make a subtitle with like 5-6 variations of this issue?

**Comment by OmrSi** [comment]
Here is a simple one that we see a lot
[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/2389257/test.zip)

**Comment by OmrSi** [comment]
@niksedk Can you please take a look at this again? Here is an example:
![Screenshot (272)](https://user-images.githubusercontent.com/20923700/54384231-6aabd780-469c-11e9-96c0-4e46d33cd892.png)

**Comment by OmrSi** [comment]
@niksedk Can you please take a look at this again? Here is an example:
![Screenshot (272)](https://user-images.githubusercontent.com/20923700/54384231-6aabd780-469c-11e9-96c0-4e46d33cd892.png)

**Comment by niksedk** [comment]
How is latest source?
Also, please do test with multi line.

**Comment by darnn** [comment]
Still happening for me in 3.5.14 NEXT beta 324.

**Comment by niksedk** [comment]
Try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip (build 327 or newer)

**Comment by OmrSi** [comment]
It's working well, as far as I can see. :D
Thank you.

**Comment by darnn** [comment]
Seems to be working now!
