### ISSUE TITLE
Minor feature request: "Close video file" menu item

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2758]
Hey, so, I've been using the keyboard shortcut for "close video file" ever since you added the option, which I still appreciae very much. I'd like to suggest adding the item to the "video" menu as well, though, since I think every user necessarily goes over every available keyboard shortcut, and so they wouldn't know it exists. Also, sometimes I have my hands off the keyboard for minutes at a time, and it would be handy to be able to do it with just the mouse.

**Comment by niksedk** [comment]
What about Video -> Close video file ?

**Comment by darnn** [comment]
Oh god, I looked for it several times and missed it even though it was right there! Sorry! :)
