### ISSUE TITLE
Arabic OCR via Tesseract

### ISSUE THREAD

**Issue by marhex** [SubtitleEdit/subtitleedit#2759]
I am having an issue with Arabic OCR via Tesseract .When i use Import/OCR VobSub Subtitle with OCR via Tesseract  it return empty lines in the whole subtitle. but when i export one png file from the subtitle and use Tesseract with cmd command it works. 
the cmd command that i use is :
`Tesseract input.png output -l ara`
thanks for your replay.

**Comment by niksedk** [comment]
What Tesseract version do you use from cmd line?
Can you add the png?

**Comment by marhex** [comment]
i used the one that came with the subtitle edit setup. from the location

> C:\Users\Marhex\AppData\Roaming\Subtitle Edit\Tesseract

**Comment by niksedk** [comment]
Try to make the text color white via the custom colors...

**Comment by SLR2019** [comment]
Hi @marhex 

Can I ask you from where you got the Arabic OCR. I've tried to download the Arabic OCR via Tesseract from SE directly but no luck. I also tried to download it from the Internet, but SE crashes when choosing Arabic OCR.

Happy to hear from you.

**Comment by OmrSi** [comment]
@SLR2019 In my opinion, it doesn't really matter, OCR for Arabic is very, very bad.
That aside, Downloading it is working fine with me in the latest version.

**Comment by SLR2019** [comment]
@OmrSi thanks for the reply. I thought I would've given it a try to see if it suits my needs. In this case, what do you recommend to use for converting Arabic .sub to .srt?

**Comment by OmrSi** [comment]
@SLR2019 It has some good results but most lines would contain errors and issue with the commas and Tanwin and Tashkeel.
You can test it yourself, maybe the font in your file is suitable for the database.
It's working for me, just install the latest version of SE and open a .Sub file then download the Arabic dictionary files, I'm not finding any issues in the process.

Sadly there isn't any alternative.
Though someone made a bunch of very good files for Tesseract, he's selling them for 400$. Yeah, that's crazy.

**Comment by SLR2019** [comment]
@OmrSi that's sad there is no alternative except SE. Anyhow, I tried to download the dictionary through SE but it gives me the "download failed" error message, although I just downloaded the SE latest version.

**Comment by day2005** [comment]
محتاج الملف
