### ISSUE TITLE
[Request] Add option to ignore formatting in compare

### ISSUE THREAD

**Issue by mkver** [SubtitleEdit/subtitleedit#2760]
Hello,

I sometimes run into situations where I want to compare the text of various subtitles that use different formatting (e.g. one subtitle uses colours/italics/alignment, the other doesn't) and so I either have to strip the formatting away before comparions or compare them the way they are, but this leads to a lot of false positives. Given that SE can already remove the formatting it should also be possible to make it ignore formatting during comparisons.

Thanks in advance
mkver

**Comment by niksedk** [comment]
Could you give latest beta a test run: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip ?

**Comment by mkver** [comment]
Works like I inteded it to do. I'm therefore closing this.

**Comment by niksedk** [comment]
thx for verifying :)
