### ISSUE TITLE
Use Deepl as the new Auto-Translator!

### ISSUE THREAD

**Issue by MaximPro** [SubtitleEdit/subtitleedit#2761]
Hi,

Did you know the worlds best Translator isn't google?

check out https://www.deepl.com

A german Company did it much better and it works almost perfectly for 7 Languages.

Please add support for this in Subtitle Edit, as the new auto-translate feature, instead of google (but allow to use both options)

This would be amazing! :)

Best regards
Maxim

**Comment by niksedk** [comment]
Check plugins...
