### ISSUE TITLE
MPV isn't show subtitles

### ISSUE THREAD

**Issue by answerwhat** [SubtitleEdit/subtitleedit#2762]
I have same problem in #2476
when i use mpv handle preview, subtitle won't show
and the waveform stuck at beginning and end of every line 
but the #2476 has closed
can anyone help?

**Comment by niksedk** [comment]
Is it all subtitles or just one specific?
What version of SE are you using?
What do you mean by "the waveform stuck at beginning and end of every line" ?
Perhaps some screenshots...

**Comment by answerwhat** [comment]
Acturelly,it's work fine untill last friday
The last action i remember is that i import a wav file to make SRT
but the waveform's playhead (the vertical light blue line) was stuck at beginning and end of every sub so I changed to directshow video mode
then today,MPV's subtitle overlay dosen't work
I tried to install from 3.5.5 down to 3.5.2 ,no one work
and I try another PC ,It's work fine
I know maybe it's my PC's probrem
but don't know how it's happend...

**Comment by OmrSi** [comment]
@niksedk I faced the same problem here: https://github.com/SubtitleEdit/subtitleedit/issues/2476
I found that deleting all cached files in `C:\Users\%userprofile%\AppData\Local\Temp` solved the issue.

Closed?

**Comment by OmrSi** [comment]
@niksedk  I faced the same problem here: #2476
I found that deleting all cached files in C:\Users\%userprofile%\AppData\Local\Temp solved the issue.

Closed?
