### ISSUE TITLE
Russian subtitle appears as gibberish in my win7 64b SE

### ISSUE THREAD

**Issue by luisppk** [SubtitleEdit/subtitleedit#2763]
I use spanish version of latest SE, in win7 64 bits.
When I opened a russian subtitle in order to translate it, I found gibberish and is impossible to translate since it can't be recognized as an idiom.

![sw problema ruso](https://user-images.githubusercontent.com/36453014/36164893-c7acf5f8-10bb-11e8-9b88-21144ac2eb62.jpg)

Edit (subtitle in zip file): 
[sample.zip](https://github.com/SubtitleEdit/subtitleedit/files/1721008/sample.zip)

Any solutions, please?

**Comment by niksedk** [comment]
sub?

**Comment by aaaxx** [comment]
"File" > "Import subtitle with manual chosen encoding..." and choose "Windows-1251 Cyrillic". Then, once it's opened, select "Unicode (UTF-8)" from the "Encoding" dropdown in the main window and save the file.

And in the future, always create your subs in UTF-8.

**Comment by luisppk** [comment]
Thank you aaaxx, it worked.
But, the russian file isn't mine. Just translating and correcting.

**Comment by aaaxx** [comment]
Yeah, I assumed so. It was just an advice to keep in mind if you do make your own in the future. UTF-8 covers all languages and is much easier to detect correctly than other text encodings.
