### ISSUE TITLE
cannot select VLC as video player

### ISSUE THREAD

**Issue by JunkyardCat** [SubtitleEdit/subtitleedit#2765]
when i went to option->settings->video player VLC option is greyed out. I have VLC already installed.

My version of subtitleedit https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SE355.zip
My version of VLC(2.2.8). This is not the portable version

**Comment by niksedk** [comment]
You probably need VLC 64-bit: https://get.videolan.org/vlc/3.0.0/win64/vlc-3.0.0-win64.exe

http://www.nikse.dk/SubtitleEdit/Help#codecs
