### ISSUE TITLE
Save As bug

### ISSUE THREAD

**Issue by maknol** [SubtitleEdit/subtitleedit#2766]
I have file named "**TIN_STAR_EP._02.ts**", when i click "Save As" after OCR, the program cut title to "**TIN_STAR_EP**".

**Comment by niksedk** [comment]
Thx for the info :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
Let me know how it works.

**Comment by maknol** [comment]
Now is better! :)
