### ISSUE TITLE
exception starting OCR

### ISSUE THREAD

**Issue by marantana** [SubtitleEdit/subtitleedit#2771]
I tried to rip an srt from a Matroska file. Subtitle format in the .mkv file is S_HDMV/PGS 
I got a thread exception, screenshot attached. (It's in German, but you should find the relevant information anyway.

![snap038](https://user-images.githubusercontent.com/36553937/36334133-7a806f86-137b-11e8-80e4-65082c4c1544.jpg)

**Comment by mkver** [comment]
It would be advantageous if you made the problematic subtitles available; you can use e.g. MKVToolNix to create a Matroska file with only the subtitles.

**Comment by marantana** [comment]
Sorry to have bothered you -- turned out the .mkv file was corrupted.

2018-02-18 9:10 GMT+01:00 mkver <notifications@github.com>:
