### ISSUE TITLE
Can't access files

### ISSUE THREAD

**Issue by AUSSIETONY57** [SubtitleEdit/subtitleedit#2772]
I have used SubtitleEdit for years and now I can't access files.  Please read the attached file which shows the error that comes up. I can move files to many drives but still can't access them.
[Can't access files.pdf](https://github.com/SubtitleEdit/subtitleedit/files/1733275/Can.t.access.files.pdf)
Thanks,
Tony

**Comment by niksedk** [comment]
Maybe not too much related to SE?

**Comment by AUSSIETONY57** [comment]
I fixed it.  Microsoft Windows 10 update often cause problems and it was them again. :-/

**Comment by niksedk** [comment]
Ok, thx for the info :)
Yes, Windows updates have been a little unstable lately... But the bugs are fixed okay fast.
