### ISSUE TITLE
Bug in fix Remove unneeded spaces

### ISSUE THREAD

**Issue by mkver** [SubtitleEdit/subtitleedit#2773]
Hello,

there is a bug in the "Remove unneeded spaces" fix; or rather a bug in the [FixExtraSpaces](https://github.com/SubtitleEdit/subtitleedit/blob/2153641aaf53354007a4c0c27da9d4d2185ec558/libse/StringExtensions.cs#L189) function. Consider this example:
```
a  
b
```
The first time the loop really does something is when i=2, i.e. when it is processing the second space after a. Then it sets k to 3 and removes the very same space. In the next iteration of the loop, the remaining space is removed. When i=0 the conditions in 205 and 208 are both true and therefore the \r (on Windows) resp. the \n (on non-Windows) that is now at the place with index 1 is removed in line 211. Saving the result and inspecting it with Notepad++ confirms that there is just a \n between the two lines. (Note that I couldn't test the non-Windows behaviour.)   
The comments reveal that the developer had something different in mind: Lines 222-225 show that he wants to delete the unneeded spaces one-by-one; whereas in 207-220 he wants to delete consecutive spaces in one go without regard for whether the spaces have already been deleted. The logic seems to be that 222-225 is for spaces before linebreaks; the other spaces are dealt with in 207-220. If I am not mistaken, then it is enough to also reset k after 224. I'll make a pull request for it. (Also note that I can't compile SE and therefore I couldn't even test my code.)

Greetings
mkver

**Comment by niksedk** [comment]
thx, good catch :)

Added unit tests so this bug will (hopefully) not occur again.
