### ISSUE TITLE
Drag & drop error using VLC 3.0.0

### ISSUE THREAD

**Issue by deu13434** [SubtitleEdit/subtitleedit#2775]
Subtitle Edit 3.5.5 (Installer version)
VLC 3.0.0 x64 (Installer version)

Since updating to VLC 3.0.0 dragging & dropping a video file into Subtitle Edit gives an error message:

> The procedure entry point "decode_URI" could not be located in the dynamic link library "C:\Program Files\VideoLAN\VLC\plugins\gui\libqt4_plugin.dll"

(This message might not be 100% correct, because it was translated, so I checked what the English version would be).

The video file still plays fine after this. Also choosing a video file via the Subtitle Edit menu works flawlessly and does not show this error.

**Comment by niksedk** [comment]
@deu13434: could you try to uninstall vlc completely incl. setting and then re-install + try latest SE beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

Does that work better?

**Comment by deu13434** [comment]
Uninstalling + re-installing (with clearing settings) of VLC worked. It works in both 3.5.5 and the latest beta you linked.

Problem now is that we can't figure out what caused the problem. It must've been some setting being non-default. Close this issue anyway?

**Comment by niksedk** [comment]
OK, I had some problems with VLC 3.0 too... drag'n'drop video when a video already was open caused SE to hang, but that should be fixed in https://github.com/SubtitleEdit/subtitleedit/commit/c5609bf0d67be42b4b33cbb606ea76cbd8dd2190

Yeah, let's just close this.
