### ISSUE TITLE
Is there a way to save my settings?

### ISSUE THREAD

**Issue by matheusguifer** [SubtitleEdit/subtitleedit#2776]
Tired of having to set up my shortcuts every time there's an update.

**Comment by darnn** [comment]
Copy over settings.xml from the previous version's folder.

**Comment by ivandrofly** [comment]
Maybe an **export settings button** in Settings @niksedk ?

**Comment by niksedk** [comment]
So, you always loose your shortcuts after an update?
How do you update? (updating is not meant to reset shortcuts)

**Comment by matheusguifer** [comment]
The pop-up notifies me of a new version, I click "Go to Download Page", download the Zip file, extract on my Downloads folder and send the executable to my desktop.

**Comment by niksedk** [comment]
Which zip file did you download - the portable version (SE356.zip) ?
Send the executable to my desktop as a shortcut or ... ?

**Comment by matheusguifer** [comment]
Yes, I always download the portable version. Send the executable as a shortcut, yes.

**Comment by niksedk** [comment]
OK, yes darnn's suggestion should work fine :)
If you add words to OCR/spell check dictionaries you might want to copy the "OCR" folder and user files from the "Dictionaries" folder too.

You could also overwrite the files from previous release, but copying Settings.xml is probably cleaner.

**Comment by huduvn** [comment]
Save Settings.xml from Appdata\Subtitle Edit

Win + R

%AppData%\Subtitle Edit

**Comment by drsantilli** [comment]
This is now fixed. Whenever you install a new version, you have the option to override previous settings, such as shortcuts.

**Comment by tomsouzas** [comment]
I save the settings.xml file, installed the 3.6.4 version, don't check the "Reset settings" option, pasted the settings.xml file, but part of my shortcuts doesn't work (the shortcuts that I use on numpad).
