### ISSUE TITLE
"Hey." always seems to OCR as "H9)'-"

### ISSUE THREAD

**Issue by ManChicken1911** [SubtitleEdit/subtitleedit#2777]
Not the most important thing in the world, but I've run into this several times recently from Bluray titles where the text

> Hey.

always gets tragically mis-OCR'd as

> H9)'-

(H, 9, close parenthesis, apostrophe, dash  in case the Markdown gets confused after the fact and destroys it.) [See image.](https://ibb.co/kdWCLn) I know OCR is not an exact science but this one is just so odd how wrong it gets it that I had to post :)

**Comment by mkver** [comment]
I have run into this issue before (see #2586) and at the time I could only reproduce it with German trained data + German dictionary. What are your language settings?

**Comment by ManChicken1911** [comment]
Ah sorry I missed that one (guess my Search-Fu was weak)

I am using English. Looking at #2586, I tried turning off the dictionary but still get the same results so I think it must be Tesseract -- Binary Image Compare gets it right. I will have to figure out how to save out as an image and try it in standalone Tesseract.

What's interesting is that if there is other text in the same title, it gets OCR'd properly. For instance:

> BUSINESS:
> Hey.

works fine. I'm wondering if it's maybe something to do with the bitmap its self, due to the small size when it's just "Hey." because it's so tightly cropped to the word, the OCR gets confused.

**Comment by ManChicken1911** [comment]
OK, I saved out a png of the title from SE, grabbed a prebuilt Tesseract 3.05.01 for Windows, and ran it through.. and it gets the correct text.

So I replaced the Tesseract folder bundled with SE (which is 3.02) with 3.05.01, and that seems to be working. It's significantly slower, probably because the binary is not static and loading a bunch of .dll's every execution, but it's otherwise behaving.

**Comment by niksedk** [comment]
Ok, you can also fix words via the "ocr replace list" xml file.

In my tests 3.05 did not give better result than 3.02, but it might be better for you. Tesseract 4 seems (beta for the next few years probably...)  good, but I could not make italic font detection work.
