### ISSUE TITLE
Save Recent files Positions

### ISSUE THREAD

**Issue by ghost** [SubtitleEdit/subtitleedit#2778]
If you open SE directly, it will reload last subtitle, and move to last position. 
I made SE the default app to open srt files. When I re-open an srt file be double clicking, SE doesn't move to last position.
In fact, I want to register the last  position for more than one file, but I can't figure out the best way to do it. Is it ok to save file names and last positions in the Settings.xml file? How and when will older files be recycled?
and what is the max number of recent files?

**Comment by OmrSi** [comment]
@niksedk I believe this is fixed.
