### ISSUE TITLE
Auto Repeat function not working

### ISSUE THREAD

**Issue by Hassan444** [SubtitleEdit/subtitleedit#2779]
Auto Repeat function on Translate mode doesn't work on versions above SE353
on my old Laptop running win xp it works fine
but on my other desktop and laptop running Win10 v1709 with latest updates it's not working
I hope you fix this as SE353 has other annoying bugs, too
Anything you'd need (Logs or whatever) I'll be glad to get for you
Thanks in advance

**Comment by niksedk** [comment]
Could you explain what exactly that does not work? Screenshots?

**Comment by Hassan444** [comment]
When translating subtitles with video file loaded, when pressing (shift+enter) to go to next line, it usually plays the duration of the video which that line was said (that what happens on windows xp), but on Windows 10, it's not working
I'll post tomorrow a video after I return to home showing exactly what I mean, Thanks in advance for your fast response

**Comment by Hassan444** [comment]
Here is the link of the video:
https://www.youtube.com/watch?v=aIHPAnaj3vA&feature=youtu.be
Sorry for being late in response I've been very busy
As you see I'm pressing (Shift+Enter) on keyboard to go next line in translation mode
but neither the duration of subtitle line is being played nor the text in lines is being highlighted for fast typing of the translation
Thanks in advance!

**Comment by OmrSi** [comment]
@niksedk And it's working fine now as far as I see.
