### ISSUE TITLE
Directly load youtube video

### ISSUE THREAD

**Issue by bruceliu2008** [SubtitleEdit/subtitleedit#2782]
Hi,
    Is it possible to directly load youtube video inside subtitle edit, at the same place as loading local video?
I am helping a buddism organisation to generate subtitle from video, there are multiple volunteers invovling it,  it is a bit troublesome for each of us to download the video from youtube.

Thanks,
Bruce

**Comment by niksedk** [comment]
Try using "mpv" video player and download youtube-dl to your SE folder (if you use the installer version, the folder should be something like "C:\Users\USERNAME\AppData\Roaming\Subtitle Edit").

![image](https://user-images.githubusercontent.com/1261331/36618848-fae3d4f8-18ec-11e8-87e3-ef0674432907.png)

**Comment by bruceliu2008** [comment]
Sorry, may I know how to use the mpv player? I can't see the 'open video
from url' menu items.
Thanks.


On 24 Feb 2018 5:59 am, "Nikolaj Olsson" <notifications@github.com> wrote:

Try using "mpv" video player and download youtube-dl to your SE folder (if
you use the installer version, the folder should be something like
"C:\Users\USERNAME\AppData\Roaming\Subtitle Edit").

[image: image]
<https://user-images.githubusercontent.com/1261331/36618848-fae3d4f8-18ec-11e8-87e3-ef0674432907.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SubtitleEdit/subtitleedit/issues/2782#issuecomment-368150545>,
or mute the thread

**Comment by LeonCheung** [comment]
@bruceliu2008 Google "youtube-dl", download the exe file into the SE folder. Then go to SE menu -Options - Settings - Video player, switch video engine to mpv (if it is gray, you should click "Download mpv lib" button first).

**Comment by bruceliu2008** [comment]
Hi Leon,
    Thanks for the instruction.
    'mpv' option is gray and I tried to download it from
https://mpv.srsfckn.biz/ and copy the mpv.exe into the same folder as
ffmpeg.exe, and restart SE, but it is still gray.
I have used youtube-dl before and copied it into the same folder as well.

Thanks

**Comment by LeonCheung** [comment]
@bruceliu2008 
![66](https://user-images.githubusercontent.com/494788/36650275-81a4d504-1add-11e8-984e-556929022dd6.png)

**Comment by bruceliu2008** [comment]
@Leon, sorry, forgot to mention, when I click the button, it shows an error
'unable to download mpv', actually my internet connection is working, which
is why I google mpv and download it separately, but 'mpv' option is still
gray.
Thanks.

**Comment by LeonCheung** [comment]
Sorry I can't help here I'm afraid. at least you can still collaborate by directly make subtitles on Youtube without SE.

**Comment by niksedk** [comment]
Download is not working atm, but will working in next update which should be out very soon - see #2790.

The mpv dll is included in this package: https://mpv.srsfckn.biz/mpv-dev-20171225.7z - but you can also just wait a few days.

**Comment by bruceliu2008** [comment]
ok, take your time. I will wait for the new release.
Thanks.

**Comment by mattez** [comment]
Hi all, hi @niksedk  I am experiencing exactly same issue as was described [here](https://gitter.im/SubtitleEdit/subtitleedit?at=6183e9d938377967f491b9a4).

Unable to get YouTube video to play in video player. 
SubtitleEdit nicely downloaded `mpv-2.dll` and `youtube-dl.exe`.
Youtube video seems to be loaded (`No video laded` title changes to URL of loaded video, in the right bottom corner of videoplayer is "libmpv 2.0") but could not be played.

Subtitle Edit v 3.6.5
in `C:\Users\xxx\AppData\Roaming\Subtitle Edit` ...
`mpv-2.dll` v2.0.0.0
`youtube-dl.exe` v2021.11.10.1

Windows 10 Pro, 64bit
I tried uninstall and fresh installation. NO success.

Any help, tips, hints are highly welcomed.

**Comment by mattez** [comment]
I have made little progress. I copied the `youtube-dl.exe` from directory where SE downloaded it:
`C:\Users\xxx\AppData\Roaming\Subtitle Edit\`
to installation directory of SE where is the `SubtitleEdit.exe` which is
`C:\Program Files\Subtitle Edit`
and surprisingly, the video was loaded, but only plays audio, no picture.
