### ISSUE TITLE
Import/Export Multiple replace

### ISSUE THREAD

**Issue by bruceliu2008** [SubtitleEdit/subtitleedit#2783]
Hi,
    Is it possible to import/export the groups in 'multiple replace' so that other people can use the groups as well?

Thanks,
Bruce

**Comment by mkver** [comment]
They are in your settings (the MultipleSearchAndReplaceGroups entry). You can copy and paste them.

**Comment by bruceliu2008** [comment]
Sorry, I didn't find it under Options/Settings, I found 'Multiple Replace' under Edit menu item, do you mean this?
Thanks

**Comment by LeonCheung** [comment]
mkver means the **Settings.xml** file in the SE folder. You can open it with any text editor, search anything between `<MultipleSearchAndReplaceGroups>` and `</MultipleSearchAndReplaceGroups>`, then share / overwrite the same block in others' **Settings.xml** file. Or you can simply share the whole file assuming you all use the same setting.

![65](https://user-images.githubusercontent.com/494788/36578445-3bce77c0-1898-11e8-84e0-ff5dd8a9d060.png)

But I also think it's a good idea to allow import/export settings such as this and shortcuts solution, which normally needs some time to reconfig, especially for teamwork or in case the old settings lost or messed.

**Comment by bruceliu2008** [comment]
Thanks, Leon.
But I can't find the Settings.xml eithor...
![image](https://user-images.githubusercontent.com/12315890/36580510-8652342a-18a3-11e8-882a-cb3d0a2a6900.png)

**Comment by niksedk** [comment]
If you're using the installer version of SE, then Settings.xml will be in the a folder like "C:\Users\USERNAME\AppData\Roaming\Subtitle Edit".

You can also export via right-clicking in the "rules" list view:
![image](https://user-images.githubusercontent.com/1261331/36619040-a98bde6a-18ed-11e8-938c-ec602eef3096.png)

**Comment by niksedk** [comment]
Also, latest beta looks like this:
![image](https://user-images.githubusercontent.com/1261331/36644158-5e5aa100-1a56-11e8-875f-567f44ffd787.png)
