### ISSUE TITLE
Extra dash '-' added after split a line in Chinese Simplified

### ISSUE THREAD

**Issue by bruceliu2008** [SubtitleEdit/subtitleedit#2785]
![image](https://user-images.githubusercontent.com/12315890/36574911-d6f61fac-1882-11e8-8d00-c7ee256f8262.png)
pls check the last charater of the highlighted line.

**Comment by LeonCheung** [comment]
Use a larger value here if necessary:
![d](https://user-images.githubusercontent.com/494788/36799280-b864287c-1ce7-11e8-9366-f5cb5708bae3.png)

**Comment by bruceliu2008** [comment]
Thanks, I changed to 999 and restart SE, still the same issue, anyway, later I will use the 'split line at cursor position'. It works perfectly.
谢谢。 👍
