### ISSUE TITLE
DeepL crashing Subtitle Edit

### ISSUE THREAD

**Issue by diese31diese** [SubtitleEdit/subtitleedit#2789]
I use Subtitle Edit 3.5.5 portable under Windows 10 x64.
First, Subtitle Edit don't download the DeepL plugin or anything plugins :-( (download failed message)

And then i open a srt file, i use auto-translate DeepL ant i have this message "Windows Forms Thread Exception"
![deepl crashing](https://user-images.githubusercontent.com/36798084/36633327-e867484e-1993-11e8-9fb2-5c41b1928512.PNG)

**Comment by diese31diese** [comment]
and the mpv library fail to download too :-(

**Comment by niksedk** [comment]
Did you get an error message when downloading mpv ?

**Comment by niksedk** [comment]
"mpv" download hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
(also might fix tesseract dictionary downloads)

**Comment by diese31diese** [comment]
Thank you for answering and correcting problems so quickly.
mpv library, as well as the DeepL plugin now download correctly. The DeepL plugin translates my subtitles without crashing. The Tesseract dictionaries download perfectly. Everything's back to normal.
Thank you again and your software is simply amazing !

**Comment by diese31diese** [comment]
oups...the DeepL translation plugin displays this error window during a translation

![capture](https://user-images.githubusercontent.com/36798084/36635340-6b006442-19b3-11e8-9986-65bbf473a93a.PNG)

**Comment by diese31diese** [comment]
I simply click on the Ignore button and the translation will continue.

**Comment by diese31diese** [comment]
or not; the message constantly reappears

**Comment by niksedk** [comment]
The download issue regarding mpv/tesseract dictionaries/plugins should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

The DeepL issue is due to too many requests... should be possible to improve the error message at least.

**Comment by niksedk** [comment]
DeepL plugin updated - but you can only update plugins if you're using latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

Well, you can unpack the plugin manually to the SE Plugin folder: https://github.com/SubtitleEdit/plugins/releases/download/v.1.1/DeeplTranslate.zip

**Comment by diese31diese** [comment]
thank you so much, i go try this

**Comment by niksedk** [comment]
SE 3.5.6 released - should enable plugin download from inside SE again :)

**Comment by diese31diese** [comment]
Yeah, i go try this version ;)

**Comment by peter571** [comment]
I am getting this error on linux debian when I try to upload a video or srt file into the subtitle edit

**Comment by niksedk** [comment]
How is this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.17/SubtitleEditBeta472.zip ?
