### ISSUE TITLE
Auto translate (by Google) crashes SE

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2791]
Not sure whether this is solvable, but I just never get it working on me:
![trans](https://user-images.githubusercontent.com/494788/36650158-e0ef7d1c-1adc-11e8-9687-9d4dae29b218.gif)

**Comment by niksedk** [comment]
Have you choosen google.cn in Settings ?

**Comment by LeonCheung** [comment]
No. It's default **translate.google.com**. However, the **translate.google.cn** seems working, but in a weird way, I mean, I don't think it's Chinese at all:

![33333](https://user-images.githubusercontent.com/494788/36659635-10f90bda-1b10-11e8-9260-5b70bc674cce.png)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
For **translate.google.cn** it works like a charm! Not sure why the .com still doesn't work here. Not sure if this is critical, but many thanks for this quick fix!

**Comment by niksedk** [comment]
Blocked?

**Comment by LeonCheung** [comment]
I know what you mean. I'm pretty sure I can currently visit google, youtube, twitter, facebook, etc. (via proxy tool like shadowsocks or vpn).

**Comment by LeonCheung** [comment]
Maybe I‘ll try find some time to test it further tomorrow. Or try to find some friends abroad to help testing. :)

**Comment by niksedk** [comment]
Also, what is the crash message - I don't read Chinese, sorry ;)

**Comment by LeonCheung** [comment]
Sure, I just tried to switch the system language to English, please see below;

![error](https://user-images.githubusercontent.com/494788/36765079-7a1040ce-1c6a-11e8-8483-cf6fcb002b26.png)

Also, Just tried everyhing like .fr  .de  .co.jp all doesn't work here except .cn.
