### ISSUE TITLE
you didnt include updates for OCR files in 3.5.6.

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#2793]
OCR files in Dictionary in current version are not newest. :(
They are from January. 

I have over 100 lines more in Croatian OCR currently than it is in this new 3.5.6. version.

something's messed up in this release.

**Comment by niksedk** [comment]
Sorry, I forgot to update the "Dictionaries" folder in the portable version.

**Comment by diomed** [comment]
what about plugin for (ispravi.me)
any news? I sent u 2 emails, never got reply 😞 
can u please post me a reply via mail or in gitter?

**Comment by niksedk** [comment]
Sorry, so much to do, so little time :(

Yes, I got the key, thx :)
I'll look at it soon - could you send some screenshots explaining how it works?

**Comment by diomed** [comment]
sure. no problem. ☑️
