### ISSUE TITLE
Get Portuguese dictionaries down

### ISSUE THREAD

**Issue by njjl** [SubtitleEdit/subtitleedit#2797]
Hello.

Both European Portuguese dictionaries are down.
Same issue on 3.5.6.0
![2018-03-01_1430](https://user-images.githubusercontent.com/581915/36850202-f9512e04-1d5d-11e8-8010-bffba5f3ba5d.png)

Should I say that you have a crazy badass software going on here?

Thanks.

**Comment by niksedk** [comment]
Argh, I tested the dictionary links like two days ago.
Anyway, thanks for the info :)

**Comment by niksedk** [comment]
SourceForge gives this message: 

     We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
     the use of javascript to function.  Please check back later.

**Comment by niksedk** [comment]
OK, seems to work again, right?
