### ISSUE TITLE
3.5.6 startup error (on WinXP)

### ISSUE THREAD

**Issue by cliffshit** [SubtitleEdit/subtitleedit#2799]
Since 3.5.6 get an error every time when starting SE. Clicking 'cancel' crashes program, 'retry' or 'ignore' continue program as usual.

**Comment by cliffshit** [comment]
[url=https://postimg.org/image/m22muvp4d/][img]https://s14.postimg.org/m22muvp4d/img_0073.png[/img][/url]

**Comment by cliffshit** [comment]
https://s14.postimg.org/plokkoru9/img_0073.png

**Comment by cliffshit** [comment]
<a href='https://postimg.org/image/m22muvp4d/' target='_blank'><img src='https://s14.postimg.org/m22muvp4d/img_0073.png' border='0' alt='img_0073'/></a>

**Comment by niksedk** [comment]
Sorry, many sites (like github) has upgraded their security to only allow TLS 1.2 and that's why download plugins/mpv/tesseract-dictionaries does not work in SE 3.5.5 and earlier and that feature is not available in .net 4.0.

So, I can no longer make SE work completely in WinXP :(
But you can run older versions of SE or even latest beta of SE - just not with working download of plugins/mpv/tesseract-dictionaries
Latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by darnn** [comment]
btw, since you were asking for suggestions about the help file, maybe put links in there to manually download all this stuff for people who can't download them automatically?

**Comment by darnn** [comment]
Or maybe even custom error messages for every download function in SE that explain the problem and provide a link?

**Comment by cliffshit** [comment]
Thanks for help and beta :)

**Comment by niksedk** [comment]
Mpv  can be found here: https://mpv.srsfckn.biz/ in the "Dev" package. Copy mpv-1.dll to the Subtitle Edit folder.  I don't know if it works on WinXP though.

Plugins here: https://github.com/SubtitleEdit/plugins/releases/tag/v.1.1

Tesseract dictionaries here: https://github.com/SubtitleEdit/support-files/tree/master/tessdata

**Comment by darnn** [comment]
The 64bit version of mpv-1.dll, if you're getting it from that archive, btw.

**Comment by francwalter** [comment]
Which is the last working version for Windows XP?

I tried 3.5.4 but also this throws errors or crashes when I use vlc (13 x "App interupted with ctrl+c" Error MessageBox) or mpv (NtCreateFile-API failed... "Message: MPV - not all needed methods found in dll file" ... ) or DirectShow (missing LAV decoders, not available for xp it seems).

Is there a older version working with VLC then on XP?
Thank

**Comment by darnn** [comment]
Somewhat belatedly, apparently it's this one: https://web.archive.org/web/20161023110401/https://mpv.srsfckn.biz/mpv-dev-20151029.7z

**Comment by OmrSi** [comment]
@niksedk Closed?
