### ISSUE TITLE
Can't edit empty entries in OCR image databases

### ISSUE THREAD

**Issue by sigdrak** [SubtitleEdit/subtitleedit#2800]
SE detects the 'dots' in letter 'ï' as '.' in binary image compare OCR method.

I entered something empty for it. No it OCRs full stops as empty, so lots of them are missing.

Maybe offering the very first or last entry of the list for (empty) could be helpful when editing. I suspect there may be issues for a lot of whitespaces, including the typical space ' '.

**Comment by niksedk** [comment]
I think you can extend the image... could you attach the sub?

**Comment by sigdrak** [comment]
You're right, I can. There's an 'expand' button on the top right I didn't notice, and it works.

Regarding the sub file, as I'm in the process of converting old files where I was lazy and left the streamdump as is (works on a PC but on no TV media player...), I don't even remember what movie it was, nor have I kept it.

Would an equivalent file with the 'ï' letter be OK? I have just triggered another bug with it for which I'm opening another bug.

**Comment by darnn** [comment]
It would be helpful (though this is ambitious, I admit) to have expand/shrink in all four directions. And at the very least right/left, since that's sometimes necessary for RTL languages.

**Comment by niksedk** [comment]
I still think the list of "image database" entries displayed by clicking the edit button should display something for 'empty'.

I'm not sure what you mean - perhaps a screenshot could help?

**Comment by niksedk** [comment]
The empty spaces are not in the ocr database. They are calculated from the "Number of pixels is space" setting
