### ISSUE TITLE
Change casing - Names Window needs better Selection Highlighting

### ISSUE THREAD

**Issue by Blickie** [SubtitleEdit/subtitleedit#2801]
The Change casing - Names Window needs a better highlight scheme or color choice.  It's just too hard to see.  Pls see attached screen cap.
![screen shot 03-03-18 at 09 09 am](https://user-images.githubusercontent.com/37019339/36935213-e8c1af06-1eec-11e8-8741-a2d33aa08195.JPG)
![screen shot 03-03-18 at 09 06 am](https://user-images.githubusercontent.com/37019339/36935214-efeb0f48-1eec-11e8-80f7-c8c07029a121.JPG)

**Comment by niksedk** [comment]
That would be nice, but sorry, it's not possible with winforms :(
