### ISSUE TITLE
Exception when 'inspect compare matches'

### ISSUE THREAD

**Issue by sigdrak** [SubtitleEdit/subtitleedit#2803]
Maybe related to #2800.

I have 'ï' with the only first dot matched as i. When I select the line where I want to 'Inspect compare matches for current image' (name of dialog), when I click "Add better match", I cause the attached exception. Sorry for large image, but I hope it provides you full context.
![inspect_compare](https://user-images.githubusercontent.com/37017880/36936968-842c5210-1f0c-11e8-9c8d-ed3d6b747057.png)

I think I must enter a string first before hiting the button, which means it should be inactive?

**Comment by niksedk** [comment]
Cannot re-create this... could you supply the subtitle + ocr db?

**Comment by niksedk** [comment]
You can also the sub from the OCR window by right-clicking in the list view:
![image](https://user-images.githubusercontent.com/1261331/36947017-841315ce-1fc6-11e8-8672-fbc46bf77e96.png)

**Comment by sigdrak** [comment]
OK, next time I make this happen... Where is the ocr db located? Users\User\AppData\Roaming\Subtitle Edit\Ocr ? I'm attaching the one there irrespective of the sub file. I have fixed some entries since then, however. :(
[Latin.zip](https://github.com/SubtitleEdit/subtitleedit/files/1800590/Latin.zip)

**Comment by sigdrak** [comment]
There's also a .nocr file I just noticed, so attaching it also.
[Latin.nocr.zip](https://github.com/SubtitleEdit/subtitleedit/files/1800593/Latin.nocr.zip)

**Comment by sigdrak** [comment]
Not exactly the same crash, but triggered very similarly.

Steps to reproduce:
1. Use the attached Latin.ocr database (I think?)
2. No of pixels: 9 and max error 1.4% (see image attached?)
3. Click start OCR
4. It should finish parsing the file(s) attached in the zip
5. Move back to the line ocr'ed as "Kl MME" (etc)
6. Double-click it for "inspect compare matches (...)"
7. Select the 'I' identified as 'l' and "Add better match": no crash
8. Select the (selectable) space after, enter no text, click "Add better match"
9. The text in the attached screen capture is displayed

![crash](https://user-images.githubusercontent.com/37017880/37256129-c80b3bea-2556-11e8-8ac2-ed5d5efedf60.png)


[Operation.zip](https://github.com/SubtitleEdit/subtitleedit/files/1800609/Operation.zip)

**Comment by sigdrak** [comment]
This is of course idiotic of me to do this, but I just wanted to try and reproduce the crash, and got another one, maybe of similar origin, so I posted in this report instead of in a new one...

**Comment by niksedk** [comment]
OK, this looks like it has been fixed:
![image](https://user-images.githubusercontent.com/1261331/37256797-07545008-2560-11e8-9f41-3c76c9cd4a88.png)

Try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

Also, for the sup in "operation.zip" you should probably up the "number of pixels is space" to 10...

**Comment by sigdrak** [comment]
Thanks! Some times, I forget to test various numbers, but also one can cause misdetections for all caps or italic texts if it is too high. Might have been one of these where I chose the "least bad" solution.

Anyway, this bug was more about fool-proofing.
