### ISSUE TITLE
[Improvement] Selected OCR dictionary resetting

### ISSUE THREAD

**Issue by sigdrak** [SubtitleEdit/subtitleedit#2805]
I haven't caught the exact rule, but if you don't explicitly select the dictionary you need, because it is already selected, when you start the OCR, it seems to revert to the last/previous one you did select, which is troublesome if it is not the same language.

I think this happens within the same run of the program, not sure if it is persistent, e.g. it also happens when you run it again.

**Comment by niksedk** [comment]
Cannot re-create this...

**Comment by sigdrak** [comment]
OK, don't know how I could help, except proving it happens by recording the screen, but that won't help recreating this.

Usually those are sub+idx files for English and French.

**Comment by sigdrak** [comment]
The files (sub+ocr db) attached in #2803 also trigger this, although I supposed unrelated. I drag'n'drop the sub file, select manually "en_US" dictionary, then OCR'ed it once and saved the srt file generated.
Then I re d'n'd the sub file and re-click "Start OCR", this time without selecting the dictionary (which is still displayed as en_US.

The selected dictionary does reset to fr_FR once I click the "Start OCR".

SE 3.5.6 / ab4c7c1.

**Comment by niksedk** [comment]
could you test this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip ?

**Comment by sigdrak** [comment]
I think you fixed the issue, thanks!
