### ISSUE TITLE
Treat ellipsis (…) the same way as three periods (...)

### ISSUE THREAD

**Issue by SvenErik1968** [SubtitleEdit/subtitleedit#2806]
If I replace three periods (**...**) with the ellipsis punctuation mark (**…**), _Fix common errors_ will try to capitalize the first word in a sentence that starts with an ellipsis, but it does not do this with similar sentences starting with three periods. Would it be possible to get it to treat the ellipsis the same way as it does with **...**?

Example:
```
1
00:01:27,129 --> 00:01:28,171
...but never could.

2
00:01:28,255 --> 00:01:29,881
…but never could.

```

![image](https://user-images.githubusercontent.com/10983802/36947111-0dd62d72-1fc8-11e8-9396-aa94eb68de09.png)

**Comment by niksedk** [comment]
Hopefully improved by c57ebd7b73af1e542de3d634ca807b35381868de: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by SvenErik1968** [comment]
That seemed to do the trick! Thanks!
