### ISSUE TITLE
Bugs found by PVS-Studio

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [SubtitleEdit/subtitleedit#2810]
Hi!

We have found bugs using PVS-Studio static code analyzer.

Code Review: [One Doesn't Simply Edit Subtitles](https://www.viva64.com/en/b/0562/).

Full report: [subtitleedit-html-log.7z](http://cppfiles.com/subtitleedit-html-log.7z)

**Comment by niksedk** [comment]
Cool!
Thx a lot for the code analysis incl. article - looks like a nice product you got :)

**Comment by SvyatoslavRazmyslov** [comment]
I can recheck the project next week.

**Comment by niksedk** [comment]
Some fixes also here: #2823

**Comment by SvyatoslavRazmyslov** [comment]
@niksedk 

Hello,

Would you like to use [PVS-Studio Free](https://www.viva64.com/en/b/0457/) for your project? The using conditions are described in the article by link.

**Comment by SvyatoslavRazmyslov** [comment]
All 372 warnings by PVS-Studio: [download/Dropbox](https://www.dropbox.com/s/t8vwv0j98yn6ju1/Subtitleedit-PVS-Studio-Full-Log.7z?dl=0).
