### ISSUE TITLE
Mysterious error while saving new file

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2811]
So, I did something I do all the time: Imported some text performed "remove text for hearing impaired" in it,, then dropped a video file into the video pane, and then went to save the file. This always works properly, but this time I got an error, for some reason. After I attempted to do the same thing again, it worked. Here it is:

![se-file-save-error](https://user-images.githubusercontent.com/19672444/37031871-2bd90380-2149-11e8-95bb-198f6bdb8d38.png)

**Comment by niksedk** [comment]
I think this has been fixed in latest release...

**Comment by darnn** [comment]
I'm not even sure how to reproduce it, but thanks!
