### ISSUE TITLE
Error when changing play rate if video file isn't open

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2812]
If a video file isn't open, trying to change the play rate (via keyboard shortcut or the menu in the waveform pane) causes an error:
![se-error-change-speed](https://user-images.githubusercontent.com/19672444/37033260-09de3cc8-214e-11e8-9f21-fac6b725c618.png)

**Comment by niksedk** [comment]
Thx for the info - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Thank you!
