### ISSUE TITLE
After you close the program, it remains open in the background.

### ISSUE THREAD

**Issue by pixbr** [SubtitleEdit/subtitleedit#2817]
After you close the program, it remains open in the background.
Pressing CTRL + ALT + DEL, the SE appears listed as open in the background.

**Comment by niksedk** [comment]
OK, what version of SE are you using?
Did this happen only once or is it every time?
What OS are you using?
What did you do (so I can re-create this)?

**Comment by niksedk** [comment]
Hm, I'm also on Win10 and have not had this issue with SE/VLC (I often switch video player, but mostly use mpv).
I've tried to release VLC resource better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
Does this still have this issue?

**Comment by pixbr** [comment]
*I used the VLC player a few times only (it does not flow very well here,
as does MPC-HC either),I always try to use the standard that is
DirectShow.Well, but I tested the portable beta and did not have that
problem anymore.I closed it and even in the background it was closed.
Wow!Could it be something from this version?**I've been using SE for years
and it's the first time with this little problem*.

2018-03-10 17:35 GMT-03:00 Nikolaj Olsson <notifications@github.com>:

**Comment by pixbr** [comment]
Fix: The beta stayed in the background too (the three instances I opened).
 It only appeared on the Details tab of the Task Manager, so I had not seen
it before, only when I tried to delete the video file I had used.
😥

2018-03-10 18:10 GMT-03:00 Jose Henrique <pixzinhu@gmail.com>:

**Comment by niksedk** [comment]
Sorry, I cannot re-create this... so I cannot fix it :(

**Comment by pixbr** [comment]
Thanks anyway!



2018-03-26 14:27 GMT-03:00 Nikolaj Olsson <notifications@github.com>:

**Comment by pixbr** [comment]
Can you add option to add Hyphen (marking dialogues) when join lines with
the same timecode?

Tks in advance!

2018-03-29 14:10 GMT-03:00 Jose Henrique <pixzinhu@gmail.com>:
