### ISSUE TITLE
"Set video offset" modifies original and translation subtitle file

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2818]
3.5.6 build 47, although this isn't recent:
If I'm in translator mode and I've saved the original and the translation file, and then I change the video offset via "set video offset" with "keep existing time codes" checked, the subtitle files are still modified. Their visible content remains the same, but, if I understand correctly, some padding is either added or removed:
Original before "set video offset":
![se-video-offset-original1](https://user-images.githubusercontent.com/19672444/37232384-77a25810-23f7-11e8-8ead-cf1f7db337e1.png)

Original after "set video offset":
![se-video-offset-original2](https://user-images.githubusercontent.com/19672444/37232405-8da9652c-23f7-11e8-829d-7adb3a65e96f.png)

Translation before "set video offset":
![se-video-offset-translation1](https://user-images.githubusercontent.com/19672444/37232408-90c4bf18-23f7-11e8-8014-a5cb857f8bed.png)

Translation after "set video offset":
![se-video-offset-translation2](https://user-images.githubusercontent.com/19672444/37232416-975f2700-23f7-11e8-9ef4-6b4e0040702f.png)

Granted, this doesn't seem to have much of an effect on anything, but I'm always weary of files getting modified when they're not supposed to.

**Comment by niksedk** [comment]
SE saves .srt files with two "0D 0A" (new line, if on windows) appended - even if your source files does not have these blank lines.
I cannot re-create anything other than this - if you can, please report the exact steps :)

The reason for this is (I got some mails some years back) that some older programs would miss last line if no new lines at the end...

**Comment by darnn** [comment]
Ah, okay, I see it's two separate things: If you use "set video offset" with "keep existing time codes" unchecked, you still get the asterisk in the titlebar that makes it seem as though the files were modified. But then if you save them both through "save all" they remain unchanged.

The other thing is that they do actually change if there's no video file open and you then open one. So, for instance:
With no video file open, I create a new subtitle file by importing text, and save it. It looks like this:
![test-time4-1](https://user-images.githubusercontent.com/19672444/37240447-2e5fa5d8-2454-11e8-9121-09367f81c5f1.png)

Now, I drag a video file into the video pane, and save the subtitle via "save all". The file now looks like this:
![test-time4-2](https://user-images.githubusercontent.com/19672444/37240448-31412bb4-2454-11e8-944b-fb190541b9a4.png)

Now I save the file via "save as" using its original name (so, I overwrite it). It now goes back to looking like it did after the first step:
![test-time4-3](https://user-images.githubusercontent.com/19672444/37240451-34a357e6-2454-11e8-9c6b-ead5b8791e31.png)

**Comment by niksedk** [comment]
OK, I can re-create the "video offset" issue - is this version better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

I cannot re-create the issue where subtitle only gets the "0A 0A" issue - any instructions?

**Comment by niksedk** [comment]
OK, I think I got the missing blank lines issue too :)

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Both don't happen for me anymore! Thank you!

**Comment by niksedk** [comment]
Thx for verifying :)
