### ISSUE TITLE
[BUG] 'Add to' Buttons in OCR detail screen don't work

### ISSUE THREAD

**Issue by daed-alus** [SubtitleEdit/subtitleedit#2821]
the red marked buttons don't work, nothing get added to the respective dictionaries,
while the green marked buttons work as expected

![non_working_buttons](https://user-images.githubusercontent.com/16777083/37278601-9591d90c-25e8-11e8-940c-3140c662d8bd.PNG)

**Comment by niksedk** [comment]
Thx for the info - "Add to names/noise list" should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

The "Add to user dictionary" works for me...

**Comment by daed-alus** [comment]
both options are working now here
thx for fixing

**Comment by niksedk** [comment]
thx for verifying :)
