### ISSUE TITLE
SubtitleEdit BETA with Pocket Sphinx does't recognize any subtitles

### ISSUE THREAD

**Issue by gabriellluz** [SubtitleEdit/subtitleedit#2824]
When I try to generate text from video (any format so far, MP4, MKV, AVI) I get the following output:

INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\en-us/feat.params
Current configuration:
[NAME]			[DEFLT]		[VALUE]
-agc			none		none
-agcthresh		2.0		2.000000e+000
-allphone				
-allphone_ci		no		no
-alpha			0.97		9.700000e-001
-ascale			20.0		2.000000e+001
-aw			1		1
-backtrace		no		no
-beam			1e-48		1.000000e-048
-bestpath		yes		yes
-bestpathlw		9.5		9.500000e+000
-ceplen			13		13
-cmn			current		current
-cmninit		8.0		40,3,-1
-compallsen		no		no
-debug					0
-dict					C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\cmudict-en-us.dict
-dictcase		no		no
-dither			no		no
-doublebw		no		no
-ds			1		1
-fdict					
-feat			1s_c_d_dd	1s_c_d_dd
-featparams				
-fillprob		1e-8		1.000000e-008
-frate			100		100
-fsg					
-fsgusealtpron		yes		yes
-fsgusefiller		yes		yes
-fwdflat		yes		yes
-fwdflatbeam		1e-64		1.000000e-064
-fwdflatefwid		4		4
-fwdflatlw		8.5		8.500000e+000
-fwdflatsfwin		25		25
-fwdflatwbeam		7e-29		7.000000e-029
-fwdtree		yes		yes
-hmm					C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\en-us
-input_endian		little		little
-jsgf					
-keyphrase				
-kws					
-kws_delay		10		10
-kws_plp		1e-1		1.000000e-001
-kws_threshold		1		1.000000e+000
-latsize		5000		5000
-lda					
-ldadim			0		0
-lifter			0		22
-lm					C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\en-us.lm.bin
-lmctl					
-lmname					
-logbase		1.0001		1.000100e+000
-logfn					
-logspec		no		no
-lowerf			133.33334	1.300000e+002
-lpbeam			1e-40		1.000000e-040
-lponlybeam		7e-29		7.000000e-029
-lw			6.5		6.500000e+000
-maxhmmpf		30000		30000
-maxwpf			-1		-1
-mdef					
-mean					
-mfclogdir				
-min_endfr		0		0
-mixw					
-mixwfloor		0.0000001	1.000000e-007
-mllr					
-mmap			yes		yes
-ncep			13		13
-nfft			512		512
-nfilt			40		25
-nwpen			1.0		1.000000e+000
-pbeam			1e-48		1.000000e-048
-pip			1.0		1.000000e+000
-pl_beam		1e-10		1.000000e-010
-pl_pbeam		1e-10		1.000000e-010
-pl_pip			1.0		1.000000e+000
-pl_weight		3.0		3.000000e+000
-pl_window		5		5
-rawlogdir				
-remove_dc		no		no
-remove_noise		yes		yes
-remove_silence		yes		yes
-round_filters		yes		yes
-samprate		16000		1.600000e+004
-seed			-1		-1
-sendump				
-senlogdir				
-senmgau				
-silprob		0.005		5.000000e-003
-smoothspec		no		no
-svspec					0-12/13-25/26-38
-tmat					
-tmatfloor		0.0001		1.000000e-004
-topn			4		4
-topn_beam		0		0
-toprule				
-transform		legacy		dct
-unit_area		yes		yes
-upperf			6855.4976	6.800000e+003
-uw			1.0		1.000000e+000
-vad_postspeech		50		50
-vad_prespeech		20		20
-vad_startspeech	10		10
-vad_threshold		2.0		2.000000e+000
-var					
-varfloor		0.0001		1.000000e-004
-varnorm		no		no
-verbose		no		no
-warp_params				
-warp_type		inverse_linear	inverse_linear
-wbeam			7e-29		7.000000e-029
-wip			0.65		6.500000e-001
-wlen			0.025625	2.562500e-002

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='current', VARNORM='no', AGC='none'
INFO: cmn.c(143): mean[0]= 12.00, mean[1..12]= 0.0
INFO: acmod.c(164): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(206): Reading HMM transition probability matrices: C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\en-us/transition_matrices
INFO: acmod.c(117): Attempting to use PTM computation module
INFO: ms_gauden.c(198): Reading mixture gaussian parameter: C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\en-us/means
INFO: ms_gauden.c(292): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(198): Reading mixture gaussian parameter: C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\en-us/variances
INFO: ms_gauden.c(292): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(354): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(835): Maximum top-N: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 138623 * 20 bytes (2707 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\cmudict-en-us.dict
INFO: dict.c(213): Allocated 1014 KiB for strings, 1677 KiB for phones
INFO: dict.c(336): 134522 words read
INFO: dict.c(358): Reading filler dictionary: C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\model\en-us\en-us/noisedict
INFO: dict.c(213): Allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 21336 bytes (20 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 21336 bytes (20 KiB) for single-phone word triphones
INFO: ngram_model_trie.c(347): Trying to read LM in trie binary format
INFO: ngram_search_fwdtree.c(99): 790 unique initial diphones
INFO: ngram_search_fwdtree.c(148): 0 root, 0 non-root channels, 57 single-phone words
INFO: ngram_search_fwdtree.c(186): Creating search tree
INFO: ngram_search_fwdtree.c(192): before: 0 root, 0 non-root channels, 57 single-phone words
INFO: ngram_search_fwdtree.c(326): after: max nonroot chan increased to 152144
INFO: ngram_search_fwdtree.c(339): after: 722 root, 152016 non-root channels, 53 single-phone words
INFO: ngram_search_fwdflat.c(157): fwdflat: min_ef_width = 4, max_sf_win = 25
INFO: continuous.c(307): C:\PortableApps\SubtitleEditBetaPocketSphinx\pocketsphinx\bin\Release\Win32\pocketsphinx_continuous.exe COMPILED ON: Jan 24 2016, AT: 07:35:37

FATAL: "continuous.c", line 158: Failed to open file 'C:\Users\itautec\AppData\Local\Temp\dc76c033-2169-4c0c-b020-69013f64adc2.wav' for reading: No such file or directory

**Comment by niksedk** [comment]
Seems like the .wav file was not generated - could you try latest update: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBetaPocketSphinx.zip

Also, try downloading ffmpeg if it does not work (options -> settings -> waveform - ffmpeg download)

**Comment by gabriellluz** [comment]
I'm testing it right now. It's not showing the same message.

**Comment by gabriellluz** [comment]
It's able to extract all audio formats I have such as mp3, aac, opus but It's not working when it comes to audio recognition. It's recognizing word-by-word, generating a subtitle line for each word, as below:

1
00:01:10,000 --> 00:04:30,000
I.

2
00:04:40,000 --> 00:10:00,000
Happen.

3
00:10:10,000 --> 00:12:50,000
To.

4
00:13:00,000 --> 00:16:30,000
Him.

5
00:16:40,000 --> 00:22:50,000
Now.

6
00:28:00,000 --> 00:38:50,000
Plaintiffs.

7
00:39:00,000 --> 00:41:40,000
In.

8
00:41:50,000 --> 00:43:10,000
The.

9
00:43:20,000 --> 00:47:50,000
Desk.

10
00:48:00,000 --> 00:49:20,000
If.

11
00:49:30,000 --> 00:55:10,000
She.

12
00:55:20,000 --> 01:02:50,000
Allowed.

13
01:08:10,000 --> 01:11:00,000
Now.

14
01:11:10,000 --> 01:13:40,000
I've.

15
01:13:50,000 --> 01:18:10,000
Said.

16
01:18:20,000 --> 01:24:20,000
Before.

17
01:24:30,000 --> 01:26:00,000
I.

18
01:26:10,000 --> 01:29:10,000
Think.

19
01:29:20,000 --> 01:33:00,000
I'll.

20
01:33:10,000 --> 01:38:40,000
Any.

21
01:38:50,000 --> 01:43:50,000
Time.

22
01:44:00,000 --> 01:52:00,000
That.

23
01:52:10,000 --> 01:54:00,000
We.

24
01:54:10,000 --> 01:57:20,000
Can.

25
01:57:30,000 --> 02:06:20,000
Sedate.

26
02:06:30,000 --> 02:08:20,000
The.

27
02:08:30,000 --> 02:13:50,000
Cat.

**Comment by niksedk** [comment]
Gave up on this... results are too poor.
