### ISSUE TITLE
[Feasure Request] Auto-break without hyphens added

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2827]
I really hope that there is a little toggle somewhere to **not** automatically adding hyphens while auto-breaking, You know, for some languages (such as mine), it doesn't make any sense since we never use it. Thx a lot.

**Comment by niksedk** [comment]
Where and how?

**Comment by LeonCheung** [comment]
For example:
![56](https://user-images.githubusercontent.com/494788/37329332-62473fec-26d8-11e8-93ef-3e01d4b799a7.gif)

Btw, not sure if enf of the GIF expose another bug, it ssems the length of the splitted line is no more than the general max length setting, however it is auto-broken anyway. May be or maybe not this is another topic.

**Comment by niksedk** [comment]
Hm, works fine here... could you attach the sub?

"Unbreak lines shorter than" you might want to try with 14 too.

**Comment by LeonCheung** [comment]
You are right. thanks for the "Unbreak lines shorter than" advice. :)

1. Hm, maybe you could try some characters other than Engligh, for example:

一二三四五一二三四五一二三四五一二三四五

They are 20 Chinese characters. After setting "Unbreak lines shorter than" to 14, then try to split at any of the position pointed as below, you can see an extra hypen will be added:

![89](https://user-images.githubusercontent.com/494788/37377931-e7479f18-2767-11e8-8ea4-ac320c097102.png)

2.  Actually I think the result is more like ""Unbreak lines shorter than n-1", maybe because the extra hyphen was added before SE can decide whether the new length is 14 or 15?
