### ISSUE TITLE
Issue when importing plain text file by dragging

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2828]
I must admit that it is very convenient that we can import plain texts by directly dragging in to List View, cheers for that. Yet I found something srange and wonder if there is something "unsafe" while trying to parse things in this way. Here are two files, While dragging the v1.txt in, it says "An Unknown subtitle type", while v2.txt is fine. 
[v1.txt](https://github.com/SubtitleEdit/subtitleedit/files/1806184/v1.txt)
[v2.txt](https://github.com/SubtitleEdit/subtitleedit/files/1806185/v2.txt)

Here is just a simple test. I just did many tests on this. The issue is repeatable, but I cannot figure out when and why.

**Comment by niksedk** [comment]
SE first looks for a known subtitle format, but if that fails then SE check if this file is most likely not a subtitle with time codes: https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/FileUtil.cs#L342

So, "Import plain text" is only opened if the file looks like it's plain text.
Beta change a little: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
