### ISSUE TITLE
"save all" status bar notice

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2831]
3.5.6 build 68. I believe this is a new behavior following the last changes to the way files are saved from a few days ago.
In translator mode, when both the original and the translation are saved, in the status bar (i.e. the thing below the video pane), two messages show up in quick succession, one about the original being saved and one about the translation being saved. I believe there used to be a single message along the lines of "original+translation saved", which is how I think it should be, since otherwise it's easy to miss the first message.

**Comment by niksedk** [comment]
Hm, works fine here (I only get one status message)

**Comment by LeonCheung** [comment]
I think he's talking about: "save all" by customized shortcut.

**Comment by LeonCheung** [comment]
@darnn, anyway you can always click on the bar to see the operation history, right?

**Comment by darnn** [comment]
Okay, I tried the latest build (88), and now it's better, but still different from how it used to be: It flashes for a split second "saved (translation)", and then displays "saved (translation) + saved (original)".

![se-save-flash](https://user-images.githubusercontent.com/19672444/37425246-579b65d4-27cb-11e8-8667-d5168668b185.gif)


And yeah, I can click on the bar, it just always triggers that thing in my brain of "a message went by and i didn't see it, i have to know what it says", which is distracting.

**Comment by darnn** [comment]
thx!

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
