### ISSUE TITLE
"Remove text for HI" doesn't follow order of operations with brackets

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2833]
Here, both sets of brackets should be removed:
![se-remove-hi-brackets](https://user-images.githubusercontent.com/19672444/37427345-cbbad1f6-27d1-11e8-82d1-1b648a4556ee.png)

**Comment by niksedk** [comment]
Thx for the info :)

Should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
