### ISSUE TITLE
Skipping past the start of a video causes it to loop back to the end

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2834]
Using the "five seconds back" keyboard shortcut, when a video is playing:
![se-skip-back](https://user-images.githubusercontent.com/19672444/37427743-f1565768-27d2-11e8-86fa-e4603ac2e48b.gif)

Here I skipped five seconds forward three times, started playing the video and then skipped five seconds back several times. I believe when this happens and the timecode is at, e.g., 00:00:02:00, it should always skip back to 00:00:00:00, and not loop back to the end. Much like if you skip all the way to the end it doesn't go back to the beginning.

**Comment by niksedk** [comment]
Thx for the info :)

Should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Thanks for all of these!!
