### ISSUE TITLE
Error-Bug Report

### ISSUE THREAD

**Issue by obclown** [SubtitleEdit/subtitleedit#2837]
InvalidArgument=Value of '0' is not valid for 'index'.

I keep getting this error, and it says I should report it so I am. I have uninstalled and reinstalled the latest version 3.5.6. This happens when I try to load any .srt files/open with in Win7 Ultimate 64bit. It also happens if I try to load any srt file from a running SubTitle Edit without loading any files. I have been using the program for awhile with no problems. Are there files or settings that are not deleted with an uninstall that could cause this problem? The problem seemed to start after converting a .sub file with the ocr; which no longer works at all now.

**Comment by niksedk** [comment]
Can you supply more information about the error?
Does deleting Settings.xml help?
Located in something like C:\Users\USERNAME\AppData\Roaming\Subtitle Edit\Settings.xml

Perhaps you should try the portable version from a folder like, C:\Tools\SE

**Comment by obclown** [comment]
I deleted the Settings.xml with no difference. I also tried running a portable version; also no difference.

I did find out something interesting. After loading a .srt file with load with - I received this error message:

See attachment 1


Once Subtitle Edit is open if I click on the Listview tab I get a second error:  See attachment 2


It seems to be a problem with the Listview index. If I resize the Subtitle Edit window I get the second error

window again. Hope this helps.




________________________________

**Comment by niksedk** [comment]
@obclown: You probably need to attach the files on github (and not via mail - you can paste images)

**Comment by niksedk** [comment]
OK, could you test this version:  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBetaDebug.zip
(Should give a line number where the error occurs)

Also, perhaps you should re-install the .net framework.

**Comment by obclown** [comment]
The debug version worked great; no problems loading .srt, or .sub file and then running the ocr. I made no changes to my system yet. If needed what version of .net framework should I re-install?

**Comment by walmal** [comment]
I keep getting this error, and it says I should report it so I am.
![error subedit](https://user-images.githubusercontent.com/37711874/37848223-aa07aa26-2ed3-11e8-821b-95e828e9b55d.png)

**Comment by niksedk** [comment]
@walmal: Try reading this: https://github.com/SubtitleEdit/subtitleedit/issues/2799
