### ISSUE TITLE
[Suggestion] Improve Find / Replace for Translation Modes

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2839]
My proposal is: when in Translation mode, a new option could be seen in both Ctrl F and Ctrl H dialog window to allow ppl to choose the target column(s) they want to affect, to be exact, "current", "original" or both.

Currently, the problem is that such operations will take effect on both texts, with "Allow edit of original mode" enabled. However, sometimes we really want to edit texts for both subs, sometimes we just don't want to touch one of them, take Find / Replace for example. I think it would be so inefficient to temporally disable it for times. FYI. Thx.

**Comment by OmrSi** [comment]
Yeah, Also when you Unbreak the current, it Unbreaks the original. :\

**Comment by LeonCheung** [comment]
@OmrSi Totally true, I was just about to update here, to update this one and saw you did it already. :)  

In that case, my suggestion would be leaving a toggle somewhere in the worknig area to enable/ disable editing original sub, instead of having to find it in General Setting, which is really handy when working in translation mode.

**Comment by LeonCheung** [comment]
A humble proto:
![t](https://user-images.githubusercontent.com/494788/38012497-465ecdf0-3294-11e8-8752-09222bca0f25.gif)

**Comment by OmrSi** [comment]
but we should still be able to copy thing from it when it is not allowed. :)

**Comment by LeonCheung** [comment]
Alternative idea:
![888](https://user-images.githubusercontent.com/494788/42608399-1de98bb6-85ba-11e8-92e0-aca41a5af144.png)

(The option can only be seen in Translation mode)

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/2604
