### ISSUE TITLE
Loading the DeepL plugin is not possible

### ISSUE THREAD

**Issue by Trekker1541** [SubtitleEdit/subtitleedit#2842]
Hello,
as already mentioned above, loading the new DeepL plugin (0.8) is not possible. Please correct errors if possible.

With the old version (0.3), an error message always appears and the translation terminates.

**Comment by mkver** [comment]
Can you give us a bit more information about your situation: What version of SE do you use? The portable or the release one? And are we talking about the same version of the plugin (size 82432 B, CRC-32 E6F255ED)? What error message does the old plugin give you? When did it last work (with what version of DeepL and SE)? What OS do you use? (Windows XP only supports old encryption cyphers so that you can't connect to a server that only accepts new ones.)

**Comment by gabriellluz** [comment]
It works for me in both beta and in the most recent stable version.

**Comment by Trekker1541** [comment]
I have two computers. A desktop and a laptop. SubtileEdit has been installed on the desktop for some time. Currently in version 3.5.5, where the plugin DeepL is installed (V. 0.3) and ran well until about two weeks ago. Since then, the translation always terminates after an indefinite time with an error message. I wanted to update the plugin to the current version (then 0.8). Unfortunately the update (via the menu: File/Plugin) aborts again and again with the error message: "Download not possible". Then I installed subtitleedit on the laptop (full version 3.5.6). Here an error message appears when starting the program, but it can be skipped. Then I wanted to load the plugin. Here also comes the same error message as on the desktop computer. Both systems currently run Windows 7, language is German. SubtitleEdit is also set to German. The versions of SubtitleEdit are not the portable versions. This situation currently exists. Just tested. Thank you!

Translated with www.DeepL.com/Translator

**Comment by Trekker1541** [comment]
Supplement:
Is it possible to load the plugin directly without using the menu of the program. Would then (DeepL.dll) in the corresponding directory be replaced by the old one (0.3). This would help me first.

**Comment by niksedk** [comment]
@Trekker1541: What happens if you install latest version of the 4.7.x?

**Comment by mkver** [comment]
You can download the plugins directly from [here](https://github.com/SubtitleEdit/plugins/releases).

**Comment by mkver** [comment]
@Trekker1541: Could you give us an update on your situation?

**Comment by OmrSi** [comment]
Cold Case.
