### ISSUE TITLE
Error while saving in different format

### ISSUE THREAD

**Issue by McrK10** [SubtitleEdit/subtitleedit#2845]
Hello, pardon for the Swedish, but we are having an issue when we change to format to save in .fcpxlm.
What can we do to fix this?
![error code for subtitle edit](https://user-images.githubusercontent.com/37616040/37702236-36c540ce-2cf2-11e8-812c-e9c5bf333ebb.jpg)

**Comment by niksedk** [comment]
@McrK10: Could you attach a subtitle that fails with this error?

**Comment by McrK10** [comment]
It happend when we where trying to save into FCPX XML (Unicode). So we cannot attach the file

Works fine with SRT ,though
