### ISSUE TITLE
XySubFilter syntax error

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2846]
Hey. 3.5.6 build 93.
When opening a video file, if there is a TXT file with the same name in the same folder, SE tries to parse it as a subtitle file.
So, firstly, I got a file that's some weird unfinished internal format:
[Walk Behind The Prank S0 E4_.TXT](https://github.com/SubtitleEdit/subtitleedit/files/1834441/Walk.Behind.The.Prank.S0.E4_.TXT)
When I tried to open the video file with the same filename, I got the following error:
![xysubfilter](https://user-images.githubusercontent.com/19672444/37726628-7d350b6a-2d3e-11e8-98b3-9302ebd7a7ef.png)
Which isn't very clear, since it doesn't mention a filename or anything like that.

Secondly, why is this TXT file even bein read? If it did contain some format the program could parse, what would it do?

**Comment by niksedk** [comment]
My guess is that this message is related to XySubFilter... strange as SE opens mpv with the `no-sub` parameter.

**Comment by niksedk** [comment]
You could try an older version of mpv from https://mpv.srsfckn.biz

**Comment by darnn** [comment]
Ah, I think the problem was that I was actually using the latest version from that link, rather than the one SE downloads. I downloaded the DLL through SE itself again and now this no longer happens.
