### ISSUE TITLE
Command line converter - convert to plain text

### ISSUE THREAD

**Issue by tobimat80** [SubtitleEdit/subtitleedit#2847]
Hi! Does one of the available subtitle formats of the converter convert to plain text? Or is this not possible on the command line. In the GUI there is in the export section a plain text exporter...

**Comment by LeonCheung** [comment]
File > Export > Plain Text...

**Comment by LeonCheung** [comment]
And have you also read [this](http://nikse.dk/SubtitleEdit/Help#commandline)? I think the custom format is what helps.

**Comment by tobimat80** [comment]
Thx! Kind of weird format in the <ExportCustomTemplates/> Settings.xml section - but it works. Thank you!
