### ISSUE TITLE
Feature request: online version

### ISSUE THREAD

**Issue by etomm** [SubtitleEdit/subtitleedit#2848]
Using the online version in the home page as an online edtior hosted inside the normal subtitle edit exe, allowing to open and save remote files, instead of local ones.

**Comment by niksedk** [comment]
SE can use dropbox to load/save files via a plugin - see File -> Plugins...

**Comment by etomm** [comment]
Yes, but I would like to be able to host it like a site and access my nas
to perform quick corrections.
