### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by AlexandreMT** [SubtitleEdit/subtitleedit#2849]
When we set final time of a subtitle line and this time is bigger than the initial time of the next subtitle online, SE should auto adjust the initial time of the next subtitle.

**Comment by LeonCheung** [comment]
You mean dragging while holding Alt key? Also, there's a shortcut setting called "Set end, offset the rest" would help you do that.

**Comment by AlexandreMT** [comment]
Oh, I saw this option now. Thanks for attention.
