### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#2851]
![image](https://user-images.githubusercontent.com/37704802/37837346-e429acc6-2eac-11e8-9830-91d64d08dd75.png)

**Comment by niksedk** [comment]
Thx for the info :)

I've updated the beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip (no installer, just portable version)

Is that better?

**Comment by lambdacore12** [comment]
I'll get back to you as soon as it is applied. Thank you for the swift
response.

**Comment by lambdacore12** [comment]
Thank you. It works perfecty.
