### ISSUE TITLE
Shortcut problem 

### ISSUE THREAD

**Issue by AymanFaik** [SubtitleEdit/subtitleedit#2852]
I've selected Ctrl+Space as a shortcut for toggle play/pause video. But every time I want to play or pause the video it take a space in the translation box. Is there any solution because it's really annoying.

Thank you,
Ayman.

**Comment by darnn** [comment]
I also use ctrl+space and don't have this problem...

**Comment by OmrSi** [comment]
@niksedk  I just checked this problem, when using MPC as your player, when using Ctrl+Space it always adds a space in the textbox when pausing or resuming.
In VLC  it only adds a space when pausing.
MPV doesn't have this problem.

**Comment by OmrSi** [comment]
@niksedk Closed with https://github.com/SubtitleEdit/subtitleedit/commit/6df51feab01dfd9e9e2d24126726e39d344d2550
