### ISSUE TITLE
error 545455

### ISSUE THREAD

**Issue by icoborg** [SubtitleEdit/subtitleedit#2853]
error 545455 opening advanced sub station alpha styles

https://i.imgur.com/4SK57us.png

**Comment by niksedk** [comment]
@icoborg: thx for the info :)
Could you attache the subtitle? (I think the crash has been fixed via b03a8ce896836b9e4c4c66aafe6b01446434ea72 but this should not happen...)

**Comment by icoborg** [comment]
Re: [SubtitleEdit/subtitleedit] error 545455 (#2853)


Hi Nikolaj,

-Monday 26 / 03 / 2018, at 11:01, you wrote:





@icoborg: thx for the info :)
Could you attache the subtitle? (I think the crash has been fixed via b03a8ce but this should not happen...)
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.




hi Nikolaj 

Sorry!  I'm late!! 

The problem is in the "advanced substation alpha styles" section.  It doesn't work properly and 
in the "margins" and "border" subsections all the values show up like 2,0 instead of 2.
I "solved" the issue going back to the release 3.5.3.



Bye.

**Comment by OmrSi** [comment]
@niksedk Closed?
