### ISSUE TITLE
Double words finder

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#2855]
Why is the option "Find double words" not included in the "Spell check" option ?

**Comment by OmrSi** [comment]
@niksedk @lambdacore12 It's available in the spell check menu and it has a shortcut.
What do you mean by "Spell check option"?

**Comment by OmrSi** [comment]
@niksedk @lambdacore12 It's available in the spell check menu and it has a shortcut.
What do you mean by "Spell check option"?
