### ISSUE TITLE
About removing empty lines

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2856]
I think the Fix common eror operation called "Remove empty lines/used line breaks" doesn't take this into acount:

![empty](https://user-images.githubusercontent.com/494788/37885637-f99b667e-30e8-11e8-8651-22e254483b19.png)

And for the case below, it matches "unneeded space" rule instead:
![t2](https://user-images.githubusercontent.com/494788/37885663-228c3d24-30e9-11e8-8674-608d8d528e7e.png)

**Comment by OmrSi** [comment]
@niksedk @LeonCheung It does after this: https://github.com/SubtitleEdit/subtitleedit/commit/18cc31975a743be37dd3ee000092542f3b6823ba
![screenshot 158](https://user-images.githubusercontent.com/20923700/52069836-38309a00-2588-11e9-8840-1067f14d84dc.png)

**Comment by igenaya** [comment]
Hi @OmrSi I have the same problem but I don't really know this code stuff at all. Could you teach me from beginning?
