### ISSUE TITLE
Use Tesseract 4 beta 1

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#2858]
Latest beta now uses Tesseract 4 Beta 1 for OCR - https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

How does that work for you?
Note that a dictionary needs to be downloaded before use, at it's not included per default as it is +20MB.

Many more languages supported + better accuracy for small fonts (I hope).

**Comment by marb99** [comment]
@niksedk 

Now works :+1: 

thanks

**Comment by mkver** [comment]
I tested 3.5.6.139 and every time I run tesseract I simultaneously get two error messages at the start: "An error occured while running tesseract: Error opening data file I:\SubtitleEditBeta\Tesseract4\tessdata/osd.traineddata" OCR still works (regardless of whether I click the errors away or not). I have downloaded and used the English OCR dictionary for that. I don't know why it searches for an "osd.traneddata" or why there is a / instead of the usual Windows \ in front of the filename.

**Comment by mkver** [comment]
The error I wrote about earlier is now gone -- thanks. But now I get a different one: "Detected 4 diacritics". I'll try to find out exactly which subtitle is responsible for this.

**Comment by hussaiiinali** [comment]
![capture](https://user-images.githubusercontent.com/37926004/38130062-32099f7a-340a-11e8-900a-e57a0ac384d3.PNG)

**Comment by niksedk** [comment]
@hussaiiinali: Have you installed "Microsoft Visual C++ Redistributable for Visual Studio 2017"?
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

Downloaing the "osd" dictionary might also help.

**Comment by niksedk** [comment]
@mkver: I think the message about "Detected 4 diacritics" is just info... I will hide that message (both info + error messages are returned so SE has to filter)

**Comment by darnn** [comment]
Is there any way to train Tesseract through SE?

**Comment by niksedk** [comment]
@darnn: Sorry, no way to train with SE.

@mkver: It's seems possible to run multiple images, like this: https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage#ocr-multiple-images-with-one-run-of-tesseract
Not sure how much performance it would gain... yet.

**Comment by mkver** [comment]
I just played a bit with it (more exactly: with the tesseract.exe 4.0 included in SE) and the very first test already convinced me that the performance gain is massive and definitely worthwhile. I extracted some Bluray/pgs-subs to png and used this simple powershell script to create the file with the file paths and test it (working directory was the folder with tesseract.exe in it; tesseract doesn't like a BOM in the file, so I used `-Encoding ascii` so the path should probably only contain characters representable in ASCII):
```
1..900|ForEach-Object{'Path\to\the\Pics\{0:d4}.png' -f $_}|Out-File 'files.txt' -Encoding ascii
measure-command{.\tesseract.exe .\files.txt .\test\output --oem 0 --tessdata-dir .\tessdata -l eng}
```
Result: 59s 693ms.
The powershell for the "one image, one process" approach was:
```
 measure-command{1..900|ForEach-Object{.\tesseract.exe ('path\to\pics\{0:d4}.png' -f $_) ".\output\output.$_" --oem 0 --tessdata-dir .\tessdata -l eng}}
```
Result: 7m 38s.
I also looked at the results and there are some minor differences like "He'II bring hell on Earth." vs. "He'll bring hell on Earth.", but no real winner. I don't know the reason for this. But it seems that the output of tesseract is deterministic.

**Comment by MagicGreenDragon** [comment]
First, thanks to update.

I see that you use the "conservative" version of tessdata instead of the "best" version:
https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/TesseractDictionary.cs#L11

You can fine "best" version here:
https://github.com/tesseract-ocr/tessdata_best

**Comment by MagicGreenDragon** [comment]
@OmrSi: Yes, I opened another issue and niksedk has updated the tesseract version. You can find the issue here: https://github.com/SubtitleEdit/subtitleedit/issues/2966

**Comment by OmrSi** [comment]
No, I mean shouldn't this be closed?
