### ISSUE TITLE
Is There anyway to insert at video position while using Adjust section and the pointer on List?

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2859]
They title says it all, I'm translating with a file that has time codes, but need to add sentences at video position sometimes, is there a fast way to do it while using Adjust?

**Comment by LeonCheung** [comment]
Even if it is added, mormally you have to adjust the end time right? In that case, you have to touch waveform anyway. in case I misunderstand something. :)

**Comment by OmrSi** [comment]
No, If you use F11 and F12, you don't have to.

Also, do you know how to use volume boost? you can activate it from the video section0

**Comment by LeonCheung** [comment]
Okay, then I think you made some point here.  :)  As to volume boost, not sure about it, sorry.

**Comment by OmrSi** [comment]
@niksedk

**Comment by OmrSi** [comment]
I found a workaround. Use focus on Waveform and use Waveform insert, then focus on list.
