### ISSUE TITLE
OCR bug

### ISSUE THREAD

**Issue by maknol** [SubtitleEdit/subtitleedit#2860]
On build 139 https://ibb.co/jikUzn

**Comment by niksedk** [comment]
@maknol: "Bulgarian" works fine here... what OS are you using? Does this happen with all subtitles?

**Comment by maknol** [comment]
Win10 x64.
And it's not working fine at all. A whole sentence is replaced by one word. Some lines i getting empty.

**Comment by maknol** [comment]
yavka.net/soft/HERE_AND_NOW_EP._08.ts - test it
