### ISSUE TITLE
Failed to download Tesseract OCR dictionaries

### ISSUE THREAD

**Issue by cxrn** [SubtitleEdit/subtitleedit#2861]
Can't download any Tesseract OCR dictionaries in 3.5.6 (ab4c7c1).

Works as intended in the latest Beta (build 152) version though (with Tesseract 4).

**Comment by niksedk** [comment]
Works fine here... could you re-try?
What OS are you using?

**Comment by cxrn** [comment]
Oh, that's interesting.

I'm just getting a "Download failed!" message, and since it works in the Beta I thought they changed the download location or something.

I'm using Windows 10 x64 (1709).

**Comment by niksedk** [comment]
Actually, versions prior to 3.5.6 will receive this error...

**Comment by niksedk** [comment]
I'll close this for now as I cannot re-produce this (I've tried on multiple computers).

**Comment by cxrn** [comment]
That's odd! I've tried across 3 computers and it's the same thing. Tried uninstalling (deleting every trace of SE) and re-installing the latest build, but I still get "Download failed!" every time I try to download any OCR-dictionary.

Only thing I could think of that could cause this is my ISP; but I've never had any issues like this before with them.

I'll setup a mobile connection and see if I'm still getting the error message.

Thanks.

**Comment by niksedk** [comment]
@cxrn: Can you download the video player "mpv" via Options -> Settings? Does that work?
(both tesseract dictionaries + lib mpv is hosted on Github)

Could you try installing latest 4.7.x .net framework?

**Comment by niksedk** [comment]
Perhaps you could try something like Fiddler to see the network traffic?

**Comment by cxrn** [comment]
@niksedk Yeah, downloading mpv works fine via Options.

.NET Framework 4.7.1 is installed.

I'm not sure this is relevant, but this message shows up (once) when I open a .sup file, right after re-installing SE:

[https://i.imgur.com/5ZuHdNB.png](url)
