### ISSUE TITLE
Error when using Regex to replace

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2864]
when i try using regex to add a tag to the start of every line, i replace every "^" with "{\fs50}", but the program stops and i have to close it from task manager

**Comment by mkver** [comment]
You did it by using "Replace" (Ctrl+H) and the "Replace all" button therein and not using the "Multiple replace" (Ctrl+Alt+M) tool, didn't you? It seems that in this mode the cursor is not always put to the right of what was just inserted; in particular this happens with zero-width matches like yours. Therefore it always starts again at the beginning of the line and adds your tag until SE ends (by using the task manager or probably until your system runs out of RAM). But it also happens with non-zero-width matches. My first guess was that it actually just doesn't change its index (the cursor position) in the given string. But during testing I also noticed another odd thing with replace: It sometimes does it more often than it should. If I search for `A` in the input string "ABCAA" and want to replace it (once!) with nothing (""), the result is "BC", not "BCAA".
You should use multiple replace for this until this gets fixed. It works fine.

**Comment by OmrSi** [comment]
Good to know. And Yes, I did understand some of it. 😅
Hope he can fix it.

**Comment by niksedk** [comment]
I've tried to fix the issue in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
How does that work for you?

**Comment by niksedk** [comment]
Beta updated again with minor fix...

**Comment by OmrSi** [comment]
Works well.
but if I use it while on translator's mode, it stops again.
I think this is more related to https://github.com/SubtitleEdit/subtitleedit/issues/2839

**Comment by OmrSi** [comment]
Thx. :)

**Comment by OmrSi** [comment]
One problem.
Now if you choose to start from the top, the replacement will occur twice for the lines after and once for the lines before.
If I'm at line 16 it will replace lines 16 to last and when accepting to start from the top, it will happen again for lines after 16.

**Comment by niksedk** [comment]
@OmrSi: Could you explain in more detail?

**Comment by OmrSi** [comment]
I'm at line 16, I press replace all, and the program replaces everything from line 16 to the end, then it asks if it want to start from the beginning of the document, if I press yes, it replace everything from line 1 to the end, so lines 16 to end are replaced again.

**Comment by niksedk** [comment]
@OmrSi: thx, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
I've tried to fix the issue yet again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
How does it look now?

**Comment by OmrSi** [comment]
All Good Now. 😄
Thank You.
