### ISSUE TITLE
Crazy framerates

### ISSUE THREAD

**Issue by maknol** [SubtitleEdit/subtitleedit#2865]
Hi, i get this crazy framerates when loading video on beta 107, but also in later:
https://image.ibb.co/ex8xrc/1.png

**Comment by OmrSi** [comment]
same here

**Comment by niksedk** [comment]
@maknol: could you email me or share a  link to the video?

**Comment by maknol** [comment]
You have mail!

**Comment by OmrSi** [comment]
@niksedk Closed?
