### ISSUE TITLE
"Single line length:" position changed after using Translator's Mode

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2867]
![screenshot 321](https://user-images.githubusercontent.com/20923700/38382533-e485da3a-3912-11e8-83e8-9438f990f533.png)
As you see, it goes right after closing translator's mode, then I have to close the program and open again to return to its position.

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Works Great. :)
