### ISSUE TITLE
Something went wrong with "Find" after last fixes

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2868]
When I search for any word now, it always marks the first word in the sentence.
Here's what happens when I search for "Change":
![screenshot 324](https://user-images.githubusercontent.com/20923700/38446595-9d5afe66-3a01-11e8-8471-214538f3ee66.png)

**Comment by niksedk** [comment]
thx for testing :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Working well.
But one problem, Now, replacing "^" with "3" for example, will add "3" to every line in a Subtitle Line.
Like this:
![screenshot 325](https://user-images.githubusercontent.com/20923700/38454092-ff2e9168-3a68-11e8-9d67-db649dfe86cb.png)

**Comment by niksedk** [comment]
That's because `^` works with all lines - try `\A` instead.

**Comment by OmrSi** [comment]
All is good. 
Thank you very much. :)
