### ISSUE TITLE
Font Size Mixing [Bug]

### ISSUE THREAD

**Issue by ldgbc** [SubtitleEdit/subtitleedit#2872]
Version: 3.5.6.173
Issue: List view text size change upon selection for long line.
What to expect: Font size don't change. Stay as the default size.

Step to reproduce:
1. Options > Settings
2. Font
3. List View, font: 8
4. Text box, font:10
5. OK
6. Highlight few subtitle lines.
6a. Short lines is fine.
6b. Long lines is size 10 (should have been 8). Long lines are those that are highlight "red". e.g. lines that have more than "Single Max Line: 43".

Thanks.

**Comment by ldgbc** [comment]
![font size](https://user-images.githubusercontent.com/1805303/38496047-91d06c7a-3beb-11e8-992b-79d3a7199b7f.jpg)

**Comment by goonis** [comment]
3.5.10 x64 bug still exist.

![1111](https://user-images.githubusercontent.com/8069033/63545733-c4a8a700-c530-11e9-94f9-b1199ee06523.gif)

**Comment by goonis** [comment]
In 3.6.7 x64 behavior is exactly the same as gif in https://github.com/SubtitleEdit/subtitleedit/issues/2872#issuecomment-524056001
