### ISSUE TITLE
Allow resize of Video Player [Enhancement]

### ISSUE THREAD

**Issue by ldgbc** [SubtitleEdit/subtitleedit#2873]
Issue: Video Player look weird on large (vertical) layout.

Please see screenshot. Top 30% and bottom 30% is blank black space. Not sure what should be put in there. Maybe the List View to be wider? But that also look weird. Maybe some one thing like Name Manager or something can goes in those area. Otherwise can just leave it as "blank space". I don't know.

But I just think it look weird. Perhaps a "Floating" Video Player that isn't locked in Subtitle.
Anyway see screenshot.
![moveable video player](https://user-images.githubusercontent.com/1805303/38496326-a9cfb550-3bec-11e8-9c79-002bec2f5802.png)

**Comment by darnn** [comment]
fwiw, you can already undock the video player: video->un-dock video controls.

**Comment by ldgbc** [comment]
I know. But it undock everything (waveform and Translate/Create/Adjust)
