### ISSUE TITLE
Aligment Option in Text Section Box {Enhancement]

### ISSUE THREAD

**Issue by ldgbc** [SubtitleEdit/subtitleedit#2874]
Issue: Alignment currently is only available in (right click) of List view.
What to expect: Able to use Alignment in the size box (context menu) without need to go to the selected line in List view.

See Screenshot.
![align 2](https://user-images.githubusercontent.com/1805303/38496453-232e6fe0-3bed-11e8-891f-a2babbc45edd.jpg)
![align1](https://user-images.githubusercontent.com/1805303/38496454-2377a106-3bed-11e8-83e4-0630960b1da3.jpg)

**Comment by OmrSi** [comment]
You can use the shortcuts for it now without a need to it to be here.
Shortcuts also work in the text box.
