### ISSUE TITLE
MPV (library) Option

### ISSUE THREAD

**Issue by ldgbc** [SubtitleEdit/subtitleedit#2876]
Issue: There are multiple version of MPV when you select "Download". Based on #2242 comments it will sometime be necessary to switch.

Would an option to choose different version of MPV be a good idea without the need to re-download and be stuck with that version. Alternatively adding a description as to which version you are currently using in MPV also help.

**Comment by OmrSi** [comment]
![screenshot 326](https://user-images.githubusercontent.com/20923700/38501702-41846a16-3c16-11e8-8b2e-1ffc3632b8eb.png)

**Comment by darnn** [comment]
Nice to see someone is still translating Married With Children...

**Comment by OmrSi** [comment]
@darnn I hadn't heard of it until They sent it as work for A company.
Now, I wish I had. Probably gonna watch all of it when the work is done.
It's so funny. :D
