### ISSUE TITLE
Error Color issue on RTL mode

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2878]
Error on the Error Color on RTL mode
![screenshot 327](https://user-images.githubusercontent.com/20923700/38506392-5a573878-3c22-11e8-8871-63c42db3b834.png)

**Comment by niksedk** [comment]
How is this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip  ?

**Comment by niksedk** [comment]
The list view in RTL mode can not show other colors than blue... sorry.

**Comment by OmrSi** [comment]
It shows the color but disappears when the line is selected.
But it's not a big problem. :)
