### ISSUE TITLE
Problem after toggling translator's mode off

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2880]
![screenshot 330](https://user-images.githubusercontent.com/20923700/38523561-93076922-3c54-11e8-8e0d-0fe2e5bd59a9.png)

**Comment by niksedk** [comment]
How can I re-create this?

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Thank you so much for all these efforts.
I am studying Computer Engineering and hoping to become anything like you one day. :)

**Comment by niksedk** [comment]
Thx for all the feedback :)
Without feedback SE would really only be a time shifter...

Thx, and happy studying.
