### ISSUE TITLE
Problem braces

### ISSUE THREAD

**Issue by Danpatpang** [SubtitleEdit/subtitleedit#2881]
Hello.
I want to write source codes in Subtitle edit.
I try to use escape character.
but I can't solve this.
help me....
How to use braces???????????????????????? 
![image](https://user-images.githubusercontent.com/19412222/38541758-0511dbf2-3cdb-11e8-8065-e75dd476c3e5.png)

**Comment by OmrSi** [comment]
you can't because they are used in ass tags... I think.

**Comment by Danpatpang** [comment]
@OmrSi 
Oh... thanks!
But I solve this problem!!!
I use _window special characters_!
other name is Type speceal characters(ALT Codes)!
![image](https://user-images.githubusercontent.com/19412222/38554903-4725343e-3cff-11e8-97fc-5f04d6d51b9a.png)

use key board shortcut.
In Korea 'ㄴ' + 한자.
![image](https://user-images.githubusercontent.com/19412222/38555153-14289462-3d00-11e8-83a7-98504db2c1b9.png)

![image](https://user-images.githubusercontent.com/19412222/38555223-5542ba40-3d00-11e8-8717-e6f8fe2a5640.png)


I don't know why it works...
But I'm happy to solve this.
thanks!!!

**Comment by OmrSi** [comment]
Cool. Just make sure it shows up correct on videos, The encoding sometimes causes some problems.
