### ISSUE TITLE
Change keyboard language Error

### ISSUE THREAD

**Issue by ZBanch** [SubtitleEdit/subtitleedit#2882]
When I switch keyboard language from English to Russian (or back) and press any button in main Text box, then I get an error with information follows. After I press Retry, I can continue typing text. But this error message box is annoying. 

---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 3.5.5.1. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Переполнение в результате выполнения арифметической операции.
Overflow as a result of performing arithmetic operation.

Stack Trace:
   в System.Windows.Forms.InputLanguage.get_Culture()
   в System.Windows.Forms.InputLanguageChangingEventArgs..ctor(InputLanguage inputLanguage, Boolean sysCharSet)
   в System.Windows.Forms.InputLanguage.CreateInputLanguageChangingEventArgs(Message m)
   в System.Windows.Forms.Control.WmInputLangChangeRequest(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.TextBox.WndProc(Message& m)
   в Nikse.SubtitleEdit.Controls.SETextBox.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Прервать   Повтор   Пропустить   
Abort Retry Skip
---------------------------

**Comment by niksedk** [comment]
Hm, I cannot re-create this... I've installed Russian keyboard on my Windows 10 and I can switch between Danish and Russian without any errors... what OS are you using? Do you know C#?

**Comment by ZBanch** [comment]
I have Windows 7. Yes, I know C# a little, but I didn't any fork from SubtitleEdit. I use latest version 3.5.5 build 1. And I can add, previous version hasn't this problem.
In addition I have keyboard helper PuntoSwitcher https://yandex.ru/soft/punto/
Oh, when I closed it - this problem disappeared! :)
