### ISSUE TITLE
(Suggestion) In File|'Save as'|'Save as type',  add the relevant file extension(s) to the end of each file type entry (inside parenthesis)

### ISSUE THREAD

**Issue by darkred** [SubtitleEdit/subtitleedit#2884]
Using SE 3.5.6 in win10.
 
Currently the dropdown 'Save as type' In File|'Save as' is like this:
![2018-04-11_002845](https://user-images.githubusercontent.com/723651/38584572-6916ad00-3d1f-11e8-87ca-af33173e3a77.jpg)
i.e. for most file format types, it's not visible what file extension the saved file will have.

My suggestion is to add the relevant file extension(s) to the end of each file type entry (inside parenthesis, e.g. _<sup>(I found the extensions by manually saving a file to each format)</sup>_
`SubRip` ---> `SubRip (*.SRT)`
`Advanced Sub Station Alpha` ---> `Advanced Sub Station Alpha (*.ASS)`
`AQTitle` ---> `AQTitle (*.AQT)`
`Belle Nuit Subtitler` ---> `Belle Nuit Subtitler (*.STP)`
`Cappella` ---> `Cappella (*.DETX)` 
`Caption Assistant` ---> `Caption Assistant (*.CAC)`
`Caraoke XML` ---> `Caraoke XML (*.CRK)`
etc

For the rest file format entries, 
for those where it's not obvious (by the file format name) what file extension the saved file will have (e.g. 'ABC iView' and 'Adobe After Effects ft-MarkerExporter'), 
add the generic relevant `*.XML` or `*.TXT`

Thank you

PS. What I have in mind is the relevant dropdown in Photoshop: [screenshot](https://user-images.githubusercontent.com/723651/38584853-5857f1da-3d20-11e8-897b-9e874b85f350.jpg)

**Comment by aaaxx** [comment]
Good idea. Although, I think the asterisk-dot part of it is unnecessary noise for the average user. Just “SubRip (SRT)” would make things cleaner.

**Comment by niksedk** [comment]
Looks different here - type is included :)
![image](https://user-images.githubusercontent.com/1261331/38633411-da09baac-3dbf-11e8-85c9-3f8fa27e7e7c.png)

**Comment by darkred** [comment]
@niksedk So, why the type is not included for me?

Using SE 3.5.6 _(installed via the installer version - not the ZIP one)_ in win10 version 1803 build 17133.1.

**Comment by darkred** [comment]
> Looks different here - type is included

@niksedk What windows version do you use?

I can't think of any other reason why the type is not included for me.
Using SE 3.5.6 _(installed via the installer version - not using the portable one)_ in win10 version 1803 build 17133.1.

**Comment by niksedk** [comment]
Perhaps you need to show file extension in "Folder options" ?
(I'm on Windows 10)

**Comment by darkred** [comment]
Yes, enabling 'show file extension' makes type become displayed. 
Thank you!

**Comment by niksedk** [comment]
Cool, thx for verifying - it's nice to know.
