### ISSUE TITLE
[SUGGESTION] New line break rules!

### ISSUE THREAD

**Issue by boitata** [SubtitleEdit/subtitleedit#2887]
Please analyze this suggestion! Would save a lot of time editing. Thanks!

Hello,it would be possible the program line break immediately before uppercase letters and also immediately after punctuation?
Obviously respecting the rule of number of characters per line, and the balance between that number of characters per line (preset in the program).
Then the program would only enforce this linebreaking rule (immediately before uppercase letters and immediately after punctuation) if the line balance condition (preset in the program) is respected.
Is the tip!! :)

**Comment by niksedk** [comment]
Do you have some issues with the current line breaking?

You can always add you own replace rules - check Edit -> Multiple replace... (tip: use regular expressions)

**Comment by boitata** [comment]
Thanks, I've already found an editor, do what I need.
