### ISSUE TITLE
Big bug with Adjust's Move Start/End 100 ms Back/Forward

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2888]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20923700/38742443-38b9848e-3f45-11e8-948f-b0976c4190ff.gif)
When using Adjust's Move Start/End 100 ms Back/Forward and going to the next line, the line returns to its original time.

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
