### ISSUE TITLE
[Shortcut request] Go to previous subtitle (from video position)

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2890]
Like the one in waveform section for next subtitle from video position.

**Comment by niksedk** [comment]
OK, I've added the shortcut (+ moved the waveform one) in the video section - https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
thx for verifying :)
