### ISSUE TITLE
Fix Common errors problem

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2891]
In "Fix Lines beginning with a dash (-)
If there is a tag, it sees the dash as a part of it?
I don't see why it's a problem exactly...
![screenshot 337](https://user-images.githubusercontent.com/20923700/38759046-8f1d220e-3f7c-11e8-9b14-06228b017f6b.png)

**Comment by niksedk** [comment]
I don't see the problem either - could you attach or email the sub?

**Comment by OmrSi** [comment]
It happens in all files, for example
I have a sentence:
"- Hello
Hi"
Fix Lines beginning with a dash (-) corrects it to:
"Hello
Hi"
but when you have a tag {\an8}
"{\an8}- Hello
Hi"
so it removes the dash from the second line only and doesn't see that there is a dash after the tag.

**Comment by OmrSi** [comment]
compare them in this file: 
[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/1912984/test.zip)



with Fix (add dash) Line pairs with only one dash (-) and Fix (remove dash) Lines beginning with a dash (-)

**Comment by niksedk** [comment]
Thx for explaining - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Fix (remove dash) Lines beginning with a dash (-) is working good now.
But Fix (add dash) Line pairs with only one dash (-) is still not working.

**Comment by OmrSi** [comment]
Also if you have 
1
00:00:01,000 --> 00:00:03,000
- Hello - Hi

it makes it:
1
00:00:01,000 --> 00:00:03,000
- Hello - Hi

and "Fix dialogs on one line doesn't see it, Am I doing something wrong?
