### ISSUE TITLE
Autoplay stopped working for me in 3.5.5

### ISSUE THREAD

**Issue by Subtitlerpo** [SubtitleEdit/subtitleedit#2899]
After upgrading to 3.5.5 and 3.5.6, autoplay of subtitle stopped working for me. I tried all available players with the same result. Reverting to 3.5.4 and eveything is fine with all videoplayers.

Running Windows 10 Pro on a 2012 Apple MacBook Pro with 16 GB RAM.

**Comment by mkver** [comment]
What is the status of the "Auto-open video file when opening subtitles" property in the video player settings page? And if it is true, then what is the video engine that you use at all?

**Comment by Subtitlerpo** [comment]
SE open a video with the subtitles just fine. The problem is when I enter a subtitle block in Edit mode, and the corresponding video segment does not play automatically as it used to. I have to use the play-button.

**Comment by Hassan444** [comment]
I have this issue, too.
Actually I've reported this since Feburary, it started appearing since I've upgraded to Win10 Redstone 3 from Win7, only version 353 works well, newer versions not.
Right now I'm using 353, but hope this gets fixed soon

**Comment by OmrSi** [comment]
@niksedk Related to https://github.com/SubtitleEdit/subtitleedit/issues/2779
And it's working fine now as far as I see.
