### ISSUE TITLE
Directly load youtube video

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2902]
I have download youtube-dl.exe and put it in the said folder. Still, the option doesn't show up...
![screenshot 343](https://user-images.githubusercontent.com/20923700/38953109-6bf6a48e-4356-11e8-9b2a-cc22647b7393.png)

**Comment by mkver** [comment]
Are you using MPV as your video player?

**Comment by OmrSi** [comment]
Yes, I always use MPV, it's better because it shows ass tags Without converting to ass. 😃

**Comment by niksedk** [comment]
Thx, it only worked for the portable version... should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Working great. Thank you. :)
