### ISSUE TITLE
[Shortcut request] Play from just before text

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2906]
Is there a way to add a shortcut for it in "Adjust"?
Currently, you can only select a shortcut in "Create".

**Comment by OmrSi** [comment]
Maybe move it to Video section?

**Comment by ldgbc** [comment]
Isn't that just F10?

**Comment by OmrSi** [comment]
It's F10 on "Create" mode, if you change to "Adjust", there isn't a shortcut for it...

**Comment by OmrSi** [comment]
@niksedk Maybe make it global instead of linked to a certain mode?
move the ability to assign a shortcut from "Create" to "Video"?
I think it would be the best course of action.
