### ISSUE TITLE
Hide mouse when playing in full screen MPV

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2908]
it is supported in MPC, I don't know if it can be done with MPV.

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
(you have to move down to the bottom to get controls/cursor back)

**Comment by OmrSi** [comment]
Yep. Working Great. :D
