### ISSUE TITLE
[Shortcut request] Add "Adjust via end position"

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2913]
without going to next

**Comment by OmrSi** [comment]
I closed it because I put it in another issue. 
But that issue was closed and the shortcut wasn't added, just saying why I reopened the issue.

**Comment by OmrSi** [comment]
@niksedk Sorry to bother you again and again with this, the thing is, I work with scene changes, and it happens a lot that you need to adjust via end position for the scene change, but then translate the line.
Maybe instead of adding another shortcut, you can change this to just "Adjust via end position" without going to next, since it makes more sense to have this Instead of the other.
Thanks. :)

**Comment by niksedk** [comment]
OK, add shortcut here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
How does it work?

**Comment by OmrSi** [comment]
It isn't working here. :\

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
thx :)
Well, I think that some shortcuts just don't work... sorry, I don't know why. I can use Ctrl+shift+oemcomma...

**Comment by OmrSi** [comment]
It's Okay, I just wanted to check if the problem is from my end. :D
Thank you very much for this. <3

Hope you do this one If you have time for it https://github.com/SubtitleEdit/subtitleedit/issues/2906 
It works with F10 for "create", but doesn't have one in Adjust.
Thanks again. <3
