### ISSUE TITLE
[Go to next line] button does not automatically play video

### ISSUE THREAD

**Issue by MaYouniSS** [SubtitleEdit/subtitleedit#2914]
when moving to the next line the video does not play automatically while it works fine when moving to the previous line, It happened to me when upgrading to both 3.5.5 and 3.5.6 so I'm sticking with 3.5.4. now
I've tried to change the button and the player but still no change.
_Windows 10Pro Build 16299._

**Comment by OmrSi** [comment]
@niksedk Related to https://github.com/SubtitleEdit/subtitleedit/issues/2779
And it's working fine now as far as I see.
