### ISSUE TITLE
Double LF (8A)h control

### ISSUE THREAD

**Issue by Gardozo** [SubtitleEdit/subtitleedit#2917]
I’m trying to export an EBU STL file in 1Level-l teletext format.

Unfortunately the dual line subtitle get 2 LF (8A)h control characters inserted, regardless of the “Number of rows added by a new line” setting.
Please change it to insert only one (8A)h control!

![ebu options 2](https://user-images.githubusercontent.com/38722986/39244000-8c832a4a-488f-11e8-913e-506ecb60a9c3.PNG)
![ebu options 1](https://user-images.githubusercontent.com/38722986/39244001-8ca99ffe-488f-11e8-82e6-037ad0083285.PNG)
![test file in hex mode](https://user-images.githubusercontent.com/38722986/39244002-8cc90e52-488f-11e8-85ff-9b64b5958668.PNG)

**Comment by niksedk** [comment]
Thx for the info - how does this beta work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by Gardozo** [comment]
This bersion works fine!
Thank you!

2018-04-30 16:50 GMT+02:00 Nikolaj Olsson <notifications@github.com>:

**Comment by niksedk** [comment]
Hm, had to roll back due to incompatibility....

**Comment by Gardozo** [comment]
Sorry to hear.
Is the version good for us downloadable still?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mentes
a vírusoktól. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Nikolaj Olsson <notifications@github.com> ezt írta (időpont: 2018. dec.
17., H, 19:35):

**Comment by niksedk** [comment]
@Gardozo: could you supply an EBU STL with double LF (not generated by SE) ?
It could help me implement this...
Sorry, old beta removed.

**Comment by niksedk** [comment]
How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip ?

![image](https://user-images.githubusercontent.com/1261331/54870831-12678a80-4dac-11e9-9925-21b48df00d05.png)

**Comment by Gardozo** [comment]
checking...

Nikolaj Olsson <notifications@github.com> ezt írta (időpont: 2019. márc.
23., Szo, 20:42):
