### ISSUE TITLE
[Feature Request] Show count of total frames in video

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2920]
when using frames mode, maybe show the count of the current frame from all video frames?

**Comment by mkver** [comment]
You know that for several containers (Matroska, transport streams, ...) the only way to get the count of all video frames is by parsing the whole file (and I haven't even started talking about things like soft pulldown...)?

**Comment by OmrSi** [comment]
Maybe do it when generating waveform?
