### ISSUE TITLE
Illegal byte sequence

### ISSUE THREAD

**Issue by herkovb** [SubtitleEdit/subtitleedit#2924]
When trying to input characters like ", the following message appears:
![image](https://user-images.githubusercontent.com/18460377/39663377-95111dc6-5072-11e8-97c9-236f51067d6b.png)

Running SubtitleEdit on Elementary Loki, Mono version 5.10.1.47, amd64

**Comment by mkver** [comment]
Can you give a bit more context? Did you open a subtitle file and tried to modify it by inserting " or did you create completely new subs and wanted to input a ", but only got that exception? If it happens in the first case, but not the second, then you should make the subtitle file that triggers this available for inspection.

**Comment by herkovb** [comment]
Yes, I opened an existing subtitle file which was created by the automatic translation feature of SE on a Windows 8.1 virtual machine. At first, I tried to enter the characters with the keyboard using different keyboard settings, but no character appeared. Then I tried to copy paste it from a LibreOffice document, and then the error appeared. At the moment I can't access the file, but will send you later.

mkver <notifications@github.com> schreef op 5 mei 2018 16:10:37 CEST:
>Can you give a bit more context? Did you open a subtitle file and tried
>to modify it by inserting " or did you create completely new subs and
>wanted to input a ", but only got that exception? If it happens in the
>first case, but not the second, then you should make the subtitle file
>that triggers this available for inspection.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SubtitleEdit/subtitleedit/issues/2924#issuecomment-386808354

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by herkovb** [comment]
I converted the srt to UTF-8 without BOM and now I can input " without errors.

**Comment by herkovb** [comment]
I suppose it is indeed not reproducible in Windows. It appeared only in SE running on Linux with mono.
But it is solved now. Thanks for your quick replies!
