### ISSUE TITLE
Add "Focus textbox" shortcut for waveform

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2925]
like "Focus List view" but for textbox

**Comment by darnn** [comment]
Does "toggle focus between list view and subtitle text box" not do that for you?

**Comment by OmrSi** [comment]
Yeah, but if you used a shortcut to move in the waveform, you have to play the video then use the shortcut, But the requested shortcut would focus the textbox on the line of video/waveform position.

**Comment by darnn** [comment]
Ahh, okay, for video/waveform position, I didn't realize that was what you meant.
