### ISSUE TITLE
EBU STL properties

### ISSUE THREAD

**Issue by SimonM6** [SubtitleEdit/subtitleedit#2930]
Hi,

Using command lines, I would like to convert a stl to EBUSTL and substract a TC offset at the same time  :

SubtitleEdit.exe /convert C:\[...]TEST.stl EBUSTL /offset:-01:00:00:000 /outputfolder:C:\[...]OUT\

My issue is that "EBU STL properties" are not preserved :( Do you you know how to keep the EBU STL properties from source file?

Here it is a screenshot where we can see source properties and output properties :
![compare_properties](https://user-images.githubusercontent.com/39193922/39928596-18c2f5d2-5536-11e8-883d-af97070b01ca.png)

Thank you for your help!

**Comment by niksedk** [comment]
Hm, the "Batch convert" has something similar for Advanced Sub Station Alpha:
![image](https://user-images.githubusercontent.com/1261331/40127569-f6623518-592f-11e8-8933-ee749af4eae2.png)

Do you need cmd line or is "Batch convert" fine?

**Comment by SimonM6** [comment]
Hi Nikolaj,

Thank you for your answer.
Yes I am using cmd line...

**Comment by niksedk** [comment]
How does this work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
(cmd line should you style from source automatically now)

**Comment by SimonM6** [comment]
Hi Nikolaj,

Thank you very much! It works as expected!
I'll wait for the official release.

Simon
