### ISSUE TITLE
Position tags

### ISSUE THREAD

**Issue by SimonM6** [SubtitleEdit/subtitleedit#2933]
Hello!

It could be very usefull that position tags (like {\an1} for example) would be independant from "Text". 

Afterward, we could manage the where the tag should be in "Export custom text format". For example :
```
{number} 
{start} --> {end}  {vertical_tag_position} {horizontal_tag_position}
{text}
```

**Comment by niksedk** [comment]
Sorry, that sounds too advanced.

**Comment by SimonM6** [comment]
Ok!
