### ISSUE TITLE
Video preview bug. 

### ISSUE THREAD

**Issue by weingweing** [SubtitleEdit/subtitleedit#2935]
https://www.youtube.com/watch?v=-1PZDMNxWT0&feature=youtu.be

I show my problem with recorded video.

First, sometime when i open previous file that i worked, The sound of video is too fast. 

Second, after I updated new version of windows 10 probably rs4, the preview is gone as you seen.

when i re-installed or load another version of SubtitleEdit, it works, but when i do some another work and comeback later like 3 or 4 min, preview is broken. 

It there any tips to solve this problem?

**Comment by niksedk** [comment]
Hm, that seems very fast - you can try to change the speed via the green double arrow below the waveform, but I guess you should try to install latest version of lav filters:
https://github.com/Nevcairiel/LAVFilters/releases (get the installer version)

Alternately, you can try to change video player to "lib mpv" via Options -> Settings -> Video player

**Comment by weingweing** [comment]
@niksedk I install again but it happened again. I think my quartz.dll file has damaged some point.
because one of my program for broadcasting use same file, but it doesn't show me preview too.
Thanks for your advice,
I solve my problem using lib mpv but how can i fix my quartz.dll T.T.

**Comment by niksedk** [comment]
Your quartz.dll is probably fine... you just have missing (or bad) codecs - normally installing lav filters will solve this.
