### ISSUE TITLE
[Shortcut Suggestion] Create a subtitle with an assigned color

### ISSUE THREAD

**Issue by LongHairedCoder** [SubtitleEdit/subtitleedit#2936]
Having a few shortcuts to create subtitles with a preassigned color per shortcut would make creating color coded subtitles for deaf people a lot faster.

**Comment by OmrSi** [comment]
Just select all lines and right click -> color would work.

**Comment by OmrSi** [comment]
You make it sound hard...
Ctrl + A
Right click -> color
Click any line

**Comment by GenHuman** [comment]
Yes, the thing is that for you to know what subtitles are what color (being each person a diferent color) you would have to mark the lines by person, then select the marked lines to give them their corresponding color and then delete the marks.
Or go through the file again changing the color line by line.

Unless I'm not understanding the method you say that well or there is an easier way I feel like the shortcut to assing a color is easier.
I requested it as this is the only reason a friend of mine prefers FAB.

**Comment by OmrSi** [comment]
You didn't make it clear that you meant a color for each person in the episode...

**Comment by GenHuman** [comment]
Oh, sorry, that is what I meant when I said "color coded subtitles for deaf people".

I don't know if there is anything similar in subtitleedit.

**Comment by OmrSi** [comment]
There is a plugin that assigns the same color for all speakers...
![screenshot 190](https://user-images.githubusercontent.com/20923700/43343615-8abb1106-91ef-11e8-8b81-3dd217c133fe.png)

**Comment by niksedk** [comment]
Latest version has 8 shortcuts for settings colors...
