### ISSUE TITLE
OCR Request

### ISSUE THREAD

**Issue by Teko101** [SubtitleEdit/subtitleedit#2938]
Hi Nikse,

I've a suggestion about fixing the issue of the numbers being recognized reversely.

I've noticed that; the OCR engine is actually recognizing numbers in the correct order; however, sometimes the OCR engine mistakenly recognize a "space" between numbers, and removing that space either by marking the "Fix OCR errors" option, or even by removing it manually will cause the numbers to be reversed.

Here's an example:

**- Problem: Space** 

![screenshot_20180522175950](https://user-images.githubusercontent.com/7893471/40395308-ac8a47a8-5e27-11e8-9205-f61c29794f71.png)

**- Problem: Reversed Nums** 

![screenshot_20180522175911](https://user-images.githubusercontent.com/7893471/40395309-acf98a1e-5e27-11e8-9618-d045f48b5b4a.png)

Now I can completely handle the spaces issue by using some regular-expression rules ( Matching groups & swapping), but I can't do this accurately unless I unmarked the "Fix OCR errors" option first, which means I'll lose the other advantages of this option :(

So would you plz implement an option to ignore the spaces mistakenly made by the OCR engine, so I can keep using the "Fix OCR errors" option w/o affecting the numbers ? 

If you can add that option, I'll try as much subtitles as possible to test my regex rules, and see if it is really effective, and if so, I think eventually you'll be able to implement a permanent solution by adding an option to the "Fix common errors" list to remove the spaces without reversing the numbers.

Cheers,
Teko

**Comment by SLR2019** [comment]
@Teko101 
Hi buddy,

Just wanna ask how you managed to deal with Arabic OCR. I've tried to download the Arabic OCR via Tesseract from SE directly but no luck. I also tried to download it from the Internet, but SE crashes when choosing Arabic OCR.

Happy to hear from you.

Regards;
SLR
