### ISSUE TITLE
Scene change / Shot change detection with FFMPEG

### ISSUE THREAD

**Issue by JuanPFerre** [SubtitleEdit/subtitleedit#2942]
I downloaded and installed ffmpeg and linked it to subtitle edit to import scene changes. After generating the waveform, I could use the import tool, but when the process finishes, I don't see the shot changes data anywhere. Is this tool working? Am I doing something wrong? Am I supposed to see the shot change marked in the waveform just like when I add it manually?
Thanks!

**Comment by niksedk** [comment]
Yes, you're supposed the see the shot changes as vertical white lines in the waveform - could you try latest beta as it has many improvement regarding generating scene changes? 
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk On the subject of scene changes, when going to next scene and setting End time, why does it look like this:
![screenshot 24](https://user-images.githubusercontent.com/20923700/40837077-cefa018a-65a1-11e8-90a7-a1a735c5387f.png)
Shouldn't it be like this...?
![screenshot 25](https://user-images.githubusercontent.com/20923700/40837090-dc96468c-65a1-11e8-9eff-50be000ac742.png)

**Comment by JuanPFerre** [comment]
Hi, Niksedk. Actually that's the version I'm using right now. The importing process starts and takes a few minutes, but then it just disappear without any notice or sign at all. And obviously, the vertical marks in the waveform are nowhere to be found.
As you may know, scene change detection is one of the most asked rules in the industry. It would be so good if I get to use this feature.

Thanks!

**Comment by niksedk** [comment]
@JuanPFerre: you can check the log by pressing `F8` - what does it say?

@OmrSi: yes, you're probably right...

**Comment by OmrSi** [comment]
is it considered a bug or a problem?

**Comment by Flitskikker** [comment]
@OmrSi The white line stands for a shot cut, so the first frame of a different shot. If the subtitle rectangle would be on the line, that would mean the subtitle is shown for one frame into the new shot.
At least, that's how I interpret it.
