### ISSUE TITLE
[Idea] New Option when Dragging Texts In

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2944]
I see that SE will try it's best to identify what kind of things you drag into SE. However, I see sometimes the automatic way needs kind of "manual assistance". I mean while dragging a text file into SE, if it seem to be a kind of "unkown type" to it, then why not adding a button to import it as plain text, anyway?  :)  Hmm, maybe like this:

![import-plain-text](https://user-images.githubusercontent.com/494788/40893846-a11040b2-67d7-11e8-9696-06fd3244b117.png)

**Comment by LeonCheung** [comment]
A quick thought for the alternative solution:  Maybe SE can support "force importing plain text" by dragging text files in while holding combo keys, say, Shift (or Ctrl) + LMB dragging.

**Comment by niksedk** [comment]
How is this?

![image](https://user-images.githubusercontent.com/1261331/44115482-4d2d2946-a00e-11e8-9398-28e7ac3f7011.png)

**Comment by LeonCheung** [comment]
Even better. than I imagine. :) I picked some plain text files [here ](https://drive.google.com/file/d/1fg5zS2qY8kslakqpcRWTmtnOzCyFtREk/view?usp=sharing)that failed to import this way, maybe useful for your test.
