### ISSUE TITLE
error message -- the requested security protocol is not supported

### ISSUE THREAD

**Issue by arslanfloryan** [SubtitleEdit/subtitleedit#2952]
![clipboard01](https://user-images.githubusercontent.com/40350979/41521841-0de0635a-72d4-11e8-9bcb-5dab23b44ec8.jpg)

**Comment by niksedk** [comment]
Try installing latest .net 4.x framework.

**Comment by arslanfloryan** [comment]
That solved it, thank you very much!
 

Sent: Saturday, July 07, 2018 at 6:45 PM

**Comment by OmrSi** [comment]
Closed. @niksedk
