### ISSUE TITLE
option to remove color

### ISSUE THREAD

**Issue by cyberbrix** [SubtitleEdit/subtitleedit#2953]
I know formatting can be removed, but I it would be nice to just remove color, leaving other formatting.

**Comment by OmrSi** [comment]
Maybe use Regex? 2 rules in multiple replace?
Add two rules:
1. Replace `<font color="(.+)">(.+)</font>` With `$2`
2. Replace ` color=".+"` With nothing.
What do you think?

**Comment by mkver** [comment]
The rules are dangerous: In situations like "<font color="color1">text 1</font> <font color="color2">text 2</font>" (where "text 1" and "text 2" don't contain a newline) it would leave "text 2" because "+" is greedy. And this also makes the second rule dangerous. Using .+? solves this.
PS: Why did you put the color in the first case inside a capturing group?

**Comment by OmrSi** [comment]
Because I'm an Amateur. 😅
Just started exploring the world of Regex.
You can do better, of course.

**Comment by cyberbrix** [comment]
I did a makeshift <font color="#([A-Da-f0-9]{6})">(.+?)<\/font> Replace with $2, but that doesn't work across line breaks.

**Comment by mkver** [comment]
Oops, I overlooked that: . by default doesn't match \n, but everything except \n. Turning on singleline-mode should resolve this: Add `(?s)` to the beginning of the first regex.
(The whole approach used here has by the way another defect: Look at this `<font color="#abcdef"><font size=2>Some text</font>Some more text</font>`. The second closing </font> is the one associated with the color font; yet the regex approach will delete the first one. The consensus is that regular expressions are not a good choice for parsing html (and these are html tags).)

**Comment by OmrSi** [comment]
How about using these:
`(?s)<font color=".+?">` with nothing and ` color=".+?"` also with nothing.
Now  the only thing left is removing the unused `</font>`

**Comment by OmrSi** [comment]
[Remove Color.zip](https://github.com/SubtitleEdit/subtitleedit/files/2115865/Remove.Color.zip)
I did what I can and came up with these, The mentioned scenarios worked on the tested file.
The steps described as "Step 1" should be applied together, sometimes twice, and then "Step 2".
Hope you can test it...

**Comment by ivandrofly** [comment]
There is a plugin to do this, I think is not yet available for download.
I'll upload it soon.
