### ISSUE TITLE
Error Message - Missing Root element

### ISSUE THREAD

**Issue by Mindnap** [SubtitleEdit/subtitleedit#2954]
? Please advise
![seerror](https://user-images.githubusercontent.com/40387150/41590102-78c227f2-73b6-11e8-94c6-5914e5abd5ce.png)

**Comment by niksedk** [comment]
It seems one of the xml files are broken... perhaps "en_US_user.xml".
Try re-installing SE.

**Comment by Mindnap** [comment]
Thanks. Did that a while ago. Fixed it. (C:
