### ISSUE TITLE
Total length not updating

### ISSUE THREAD

**Issue by Issity** [SubtitleEdit/subtitleedit#2955]
The **Total length** value is not updated when selecting subtitles with length issues (with peach highlight). It updates after text editing window is selected.
Jumping between "white" subtitles updates Total length as expected.

OS: Win 7
SE version: 3.5.6

**Steps to reproduce:**
1. Open or create subtitles which have some segments exceeding max line length.
2. Click on any correct (white) subtitle in the list view
3. Click on long subtitle (with peach highlight)

**Result:**
Total length stays unchanged.

**Expected result:**
Total length is updated to show actual length.

**Comment by niksedk** [comment]
@Issity: I'm having trouble re-creating this... could you supply some screenshots, a video or similar?

**Comment by Issity** [comment]
Hi @niksedk I wanted to grab a video but strangely everything worked as expected when I tried.
I'm pretty confident this happened at least a few times. Now I feel like having schizophrenia.
I guess there could be some settings I changed meanwhile or other conditions.
If this ever happens again I'll record a video, copy config file and SRT.
Sorry for trouble and thanks for trying to reproduce this bug.

**Comment by niksedk** [comment]
OK, do let me know if it happens again :)
I'll also try to look for this.
