### ISSUE TITLE
Inconsistency in EBU STL export

### ISSUE THREAD

**Issue by someperson** [SubtitleEdit/subtitleedit#296]
I've noticed that the VerticalPosition when exported as an EBU STL file is not constant, even when the position is the same. It seems to depend on how many lines there are in each subtitle. I'm not sure if there's a reason for this, but it means that on YouTube at least, subtitles with two lines are higher than those with only one line.

I could "fix" this for now by adding a blank line to every subtitle that has only one line, but that would be an arduous process. Any chance of a quick fix?

**Comment by stingra** [comment]
Hi I have a similar problem using EBU .stl files and exporting them just to change the language code, when you save the file it appears to strip or modify the [Start box][Start box] Control characters for teletext subtitles in the file. This occurs in all versions i tested from 3.4.4 ->3.4.6. Would you like me to create a new issue for this??
