### ISSUE TITLE
[Feature Request] Batch Encoding Converter

### ISSUE THREAD

**Issue by erosman** [SubtitleEdit/subtitleedit#2964]
Recently, I have had to change the encoding of a large number of SRT subtitles from ANSI to UTF-8.

Currently, I have to load them one by one and then change the encoding and save. It would be great if there was a way to automate it with a batch conversion, 

Keep up the good work

**Comment by darnn** [comment]
There is, in fact: Tools -> Batch convert. You have format and encoding on the bottom left there.

**Comment by OmrSi** [comment]
![screenshot 88 _li](https://user-images.githubusercontent.com/20923700/42099927-79f4a7ee-7bc7-11e8-91ba-eed72c27b4eb.jpg)

**Comment by erosman** [comment]
Great...thank you 
I had missed it :p
