### ISSUE TITLE
DeepL auto translate "too many requests"

### ISSUE THREAD

**Issue by ShiZZe225** [SubtitleEdit/subtitleedit#2965]
im waiting a "while" (30minutes) and i still need to wait? it didn't even started. i've already uninstalled and installed again the programm.
![bez tytulu222](https://user-images.githubusercontent.com/40721036/42129261-3dcfe34c-7cc0-11e8-9606-47cddccec46c.png)

**Comment by niksedk** [comment]
Sorry, I cannot do anything about this :(
DeepL probably saves your IP...

**Comment by ShiZZe225** [comment]
thanks for answer.
too bad i guess. do you know if there is ANY other way to translate subtitless with DeepL? except going to web site and translate every simple text by myself.

**Comment by darnn** [comment]
First of all, fwiw, you could pay them:
https://www.deepl.com/pro.html (Although presumably your login would have to be integrated into SE somehow)

Secondly, you could do this:
Open your original subtitle file. Export the text into a separate file (file, export, plain text). Translate this text file in 5,000 character chunks using DeepL's web interface. Make sure to put all the translated text back together in exactly the same way as the original, so you have the same number of subtitles.

So if you have, say, this:

> Ich weiß es.
> 
> Du sagst, du hast Jonish nicht getötet. Aber du warst für ihn verantwortlich.
> 
> Er war in deinem Gewahrsam.
> 
> Ich werde dir nur ein bisschen Zeit geben, mir den Mörder zu bringen.

Make sure the translation looks like this:

> I know it.
> 
> You say you didn't kill Jonish. But you were responsible for him.
> 
> He was in your custody.
> 
> I'm just gonna give you a little time to bring me the killer.

And not, for instance, like this:

> I know it.
> 
> You say you didn't kill Jonish. But you were responsible for him.
> 
> He was in your custody.
> I'm just gonna give you a little time to bring me the killer.

Now, take your translated text file and import it into SE (file, import plain text). The settings should look roughly like this:
![se-import](https://user-images.githubusercontent.com/19672444/42138263-56525a26-7d83-11e8-8a65-873b2fdcc876.png)

Save this subtitle file. If everything went well, it should have the same number of subtitles as your original file. Now import the time codes (file, import time codes) from your original file, and voilà. You have a file translated by DeepL with the same time codes.

This works the same with Google Translate, Bing, etc., naturally.
