### ISSUE TITLE
SE fails to open a PE2 file containing the word "speakers"

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#2967]
3.5.6 build 245.
When attempting to open this file (a PE2 subtitle file containing the single word "speakers"):
[speakers.zip](https://github.com/SubtitleEdit/subtitleedit/files/2153094/speakers.zip)
The following error occurs:
![speakers](https://user-images.githubusercontent.com/19672444/42137729-7614666e-7d7a-11e8-93e2-1ecd34c1b99e.png)

If you change the text inside the file to "speaker", for instance, it opens properly.

As a side note, this was very confusing to diagnose, because I had imported a file with 2,800 subtitles from ELR, and thought for sure it was something in the conversion process. Which made it all the more strange when I could save the entire file as SRT, and then open that, and even save it as PE2, but when I tried opening the PE2 file I got the error.

**Comment by darnn** [comment]
Thanks!

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
