### ISSUE TITLE
[Improvement] Ass comment lines

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2971]
How can I know that a line in an ass file is set as a comment?
And can the program ignore comment lines when playing the file?

**Comment by niksedk** [comment]
SE does not have support for this ATM - would that be useful for you?

**Comment by OmrSi** [comment]
When you open an ass file and it has comment lines, it sees them as a part of the subtitle, so if someone put a comment for the translator that extends from the start to, say, minute 10, when opening in SE it will consider it a normal line, it doesn't show up in the video player, but the list stays stuck on it while the video is playing...
Maybe it should just be an Aegisub thing and there is no need for SE to support it...
