### ISSUE TITLE
Two time-saving shortcuts

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2972]
Highly appreciated for kindly adding two new shotcuts:

> **Merge selected lines and unbreak**

and

> **Merge selected lines and unbreak without space(CJK)**

I know we've already had the **merge** and **unbreak** operations separately, but it's really about the efficiency when you have to constantly unbreak after merging. Thank you!

**Comment by OmrSi** [comment]
Add to this "Shift + F3" to find previous...

**Comment by LeonCheung** [comment]
@OmrSi Ha yeah, if you mean #2736.

**Comment by OmrSi** [comment]
Yeah. :D
When I'm moving fast in results I sometimes need to go back one, then I have to start from up in the list and search again. :\
It would be very useful.

**Comment by niksedk** [comment]
Added shortcuts for this - Options -> Settings -> General -> Merge selected lines and unbreak / unbreak-no-space.

How does it work?

**Comment by LeonCheung** [comment]
By "General" you mean the "Shortcuts"? Just tried the lastest test build, It's perfect. :D
