### ISSUE TITLE
No Japanese Dictionary

### ISSUE THREAD

**Issue by FallenPrince** [SubtitleEdit/subtitleedit#2973]
Please add Japanese  dictionary, :(
there is **Italian**  then **Khmer** no Japanese

**Comment by niksedk** [comment]
What kind if dictionary? Spell check or OCR or ?

**Comment by FallenPrince** [comment]
Spelling check

**Comment by niksedk** [comment]
Sorry, SE uses hunspell and I don't think Japanese is available.
