### ISSUE TITLE
Fix missing spaces missing one case

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2975]
This case is not caught by the functionality, there should be a space after the question mark.

```
749
00:48:04,600 --> 00:48:06,600
Why don't we make it?20.
```

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
