### ISSUE TITLE
Different palette for Binary image compare and Tesseract

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2976]
Is it possible to adjust the .sup file palette when OCR'ing? I have some subtitles that are impossible to OCR with binary image compare and Tesseract leaves too many errors. The colours used by Tesseract are very clear and it would be easy to OCR using binary image compare.

Binary image compare:
![image](https://user-images.githubusercontent.com/11799308/42699947-f7ca426a-86ca-11e8-87f5-581292ed1220.png)

With Tesseract selected:
![image](https://user-images.githubusercontent.com/11799308/42699966-0660751a-86cb-11e8-8e04-ae0d895f0884.png)

**Comment by niksedk** [comment]
@Boulder08: Could you attach or email the sub?
There's a setting in the "Settings.xml" file called "OcrBinaryImageCompareRgbThreshold" - what happens if you set it to like "100"?
