### ISSUE TITLE
Bug with "Show only forced subtitles"

### ISSUE THREAD

**Issue by vertigo220** [SubtitleEdit/subtitleedit#2979]
In the import window, if you check this box, then uncheck it, then click ok, it will only import the forced subtitles, and all other lines will be blank. I spent several minutes manually checking an import and lost it all due to this, then tried again by not checking the box at all (everything imported properly), checking then unchecking it (problem happened again), and checking it and leaving it checked (imports only forced subs and only has those lines). This is with v3.5.6 on Win10 with a .sup file.

**Comment by niksedk** [comment]
@vertigo220: thx for the info - yes, I see the problem.
I've tried to make it so, that nothing is lost turning this checkbox on/off - plus renamed it to "Use only forced subtitles": https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

Does that work okay and more logic?

**Comment by vertigo220** [comment]
I tried testing it but as soon as I start running the OCR I get two error messages simultaneously both stating "An error occurred while running tesseract: Error opening data file C:\...\SubtitleEditBeta\Tesseract4\tessdata/osd.traineddata"

Also, I don't think the name of the option was a problem before, but once it's working properly so I can test it I'll let you know if I think it works better.

Another thing, something I just noticed, is that if I drag an mkv into SubtitleEdit and select the SRT from it, it imports it with all the lines, but if I demux the SRT from the mkv, it requires me to go through the OCR step, which makes no sense since it's not an image-based subtitle file, it's text based, so all the data is already there. It seems it should just open it directly in the main interface and not require this step.

Finally, I assume there's a reason the option to use only forced subtitles vs using all of them can't be on the next screen, after the OCR is done and all the subtitles are imported, in order to toggle it at that point? This would be significantly better IMO, allowing, for example, the user to save a file with all subs then immediately save it again after checking that option to create a file with only forced subs, eliminating the need to perform OCR and do all the corrections twice.

**Comment by niksedk** [comment]
@vertigo220: You can download "osd.traindata" via the "..." button - choose "osd" as language.

... "but if I demux the SRT from the mkv" - how do you do that?

The option is available because sometimes ppl only want the forced subtitles - e.g. foreign parts for an English movie.

**Comment by vertigo220** [comment]
I don't want to use osd as the language (not even sure what language that would be. I have English selected, and I have an eng.traineddata file I downloaded (though I have my own I normally use), but for some reason it's complaining that I don't have a data file for a language (osd) that I don't even have selected, nor did I ever select it. Seems to be a bug in this beta, as I didn't have the issue with any previous version.

> ... "but if I demux the SRT from the mkv" - how do you do that?

tsMuxeR or MKVToolNix

> The option is available because sometimes ppl only want the forced subtitles - e.g. foreign parts for an English movie.

I know why the option is there, and I think it's a great option. My point was that instead of having it on the OCR screen, where you have to select it before proceeding to the next screen where you actually save the file to be used, thereby forcing you to only be able to choose one way or the other, it would make more sense to perform the OCR, go to the next screen, then have a checkbox there to switch between all vs foreign lines. This way, I could go through the tedious OCR process, fixing any errors, then once done, I could go to the next screen, make any further adjustments that are necessary, save it as a subtitle file to be muxed into an mkv, then simply check the box on _that_ screen and have it immediately switch to only foreign parts and save it again, thereby creating a separate full and foreign only track. Currently, I'd have to spend the time doing the import/OCR, go to the next screen, make any changes, save the file, then start all over again, redoing the import/OCR, this time checking the box, then saving it as a foreign parts only track.
