### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by Mapsking** [SubtitleEdit/subtitleedit#2980]
Subtitle Edit Crashed, when I went to save a file I was working on, and I was asked to put the information here, so here it is.  Not sure what the problem is, but it reloaded itself automatically, and seemed to work fine.  On a side note, thanks for great software, it really helps me out a lot!

Thanks, Mapsking

![image](https://user-images.githubusercontent.com/41529240/43041627-bca4e142-8d2b-11e8-8763-2e8bd692677a.png)

**Comment by OmrSi** [comment]
@niksedk Might be closed since there is no way to recreate it.
