### ISSUE TITLE
Problem Using brackets in Arabic writing  

### ISSUE THREAD

**Issue by Noortex** [SubtitleEdit/subtitleedit#2983]
![default](https://user-images.githubusercontent.com/41646277/43157110-a0088cda-8f99-11e8-8185-0b8422fddd6e.jpg)

**Comment by OmrSi** [comment]
![screenshot 180](https://user-images.githubusercontent.com/20923700/43173946-3b90f388-8fc0-11e8-965c-7bae6438c4ad.png)
Did you use reverse start\end for RTL?
