### ISSUE TITLE
OCR Google Vision [Feature request]

### ISSUE THREAD

**Issue by DaniGTA** [SubtitleEdit/subtitleedit#2986]
### Can you add OCR Google Vision ?

It is a good alternative for Tesseract and its maybe better but first you need too test it:

https://cloud.google.com/vision/

> Every user that want too use it then must set up his own API key

**Comment by diomed** [comment]
where does it say it's use is free for open-source?
looks like paid thing.

**Comment by Ghostkeeper** [comment]
I think it sort of would be a problem. That is way too technical for most users.

**Comment by DaniGTA** [comment]
That can be.

**Comment by niksedk** [comment]
Could be done - but I would rather look at the audio to text first... (a bit commercial and annoying - you must enter credit card info to get an api key).

Also, my guess is that it is based on Tesseract which SE already uses - does anyone know about that?
