### ISSUE TITLE
DeepL (translator) plugin not working

### ISSUE THREAD

**Issue by lasodamos** [SubtitleEdit/subtitleedit#2987]
the DeepL plugin stoped working 2/3 days ago, leaving blank line instead of translate

**Comment by 1024mb** [comment]
Same here. They must have change something because QTranslate also stopped working with DeepL until they updated the app.

**Comment by niksedk** [comment]
Should be fix via commit e0a3fda10c9a7b3ef4735f6de5c9d660f5eab97d
(update plugins via File -> Plugins)

**Comment by niksedk** [comment]
There's now a `DeepL Screen-Scraper translate` plugin
