### ISSUE TITLE
Line breaking in SE

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#2988]
![](https://static.titlovi.com/uploads/17537/SE002.jpg)

Currently program breaks lines like this:
![](https://static.titlovi.com/uploads/17537/SE003.jpg)

instead of like this - which is desired behavior:
![](https://static.titlovi.com/uploads/17537/SE004.jpg)

2. example:
![](https://static.titlovi.com/uploads/17537/SE006.jpg)

![](https://static.titlovi.com/uploads/17537/SE007.jpg)

There's been a discussion that there is no valid point 
for sentences of other speaker to go into new line.

However it may be, I think you'd agree that this could be amended, and made into [checkbox]
option at least, to break lines in new row with nearly equal amount of letters for each row, unlike
it's currently.

**Comment by LeonCheung** [comment]
Maybe enabling the tool below would be helpful to you here: **Options > Settings > Tools > Use do-not-break-after list.**

**Comment by diomed** [comment]
In all simplicity I want - well, not just me, but there are other translators who think that one of quirks of SE is that it doesn't break lines as SW does - so we want it to break lines like that.

Since SW is also open source, I believe there is some logic in the code that could be applied here from there, and make this possible.

your options don't really help me since - I do want breaking of lines, 
and simply can't make another list, for Croatian, which doesn't have it.

**Comment by niksedk** [comment]
Beta updated to improve the first scenario: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
