### ISSUE TITLE
How to Select Line from Waveform View?

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2990]
Hi, does anyone know how to quickly select / highlight a subtitle line in Waveform view instead clicking in List View?

It seems I can use right click, but a conext menu also shows up, which is really unwanted for the purpose here. And double left click works here, but it will change the time cursor position anyway, which is also unwanted.

Thank you for any advice.

**Comment by OmrSi** [comment]
Like this https://github.com/SubtitleEdit/subtitleedit/issues/2928 ?

**Comment by LeonCheung** [comment]
@OmrSi Quite similar. It seems we both expect a way in selecting lines in waveform view WITHOUT changing current video position. 

It makes sense, because what we see in current waveform view, in most cases, is what we need to handle at the very moment, instead of switching to List view back and forth, which is less efficient.

Hmm, instead of using keyboard as you suggested, I think it could be more convenient by clicking **MMB**, and **Shift MMB** for +/- selection, after all they haven't been occupied yet.

**Comment by OmrSi** [comment]
@niksedk Closed?
A shortcut was added for this: https://github.com/SubtitleEdit/subtitleedit/commit/4b57f16583bea7d74faf9e692e632a1181b554b6
Also, an option for selection with one click was added:
![image](https://user-images.githubusercontent.com/20923700/79574241-86b45080-80c8-11ea-860d-18b268d4a45f.png)
