### ISSUE TITLE
Respective Line Merging Feature

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2991]
If I may, please consider adding an operation / shortcut to do things like below, and imagine how many seconds and clicks can't be saved without it when working with bilingual subtitles like this:
![3](https://user-images.githubusercontent.com/494788/43535175-d9c49402-95eb-11e8-84ec-12cb89280edc.png)

**Comment by aaaxx** [comment]
Out of curiosity, where are those Chinese and English subtitles used and why? The first time I saw them, I thought they were for language learners, but since then I've also seen them on some retail Blu-rays.

**Comment by LeonCheung** [comment]
@aaaxx I assume you mean such bilingual style? There are countless subtitles here are requested made like this, for TV series and online movies, etc. It's very popular nowadays in China for some reason. I really don't know why, to be honest...

**Comment by chriszo111** [comment]
@LeonCheung but merging these two lines would result in this:
```
你好, Hello, 我的朋友.  my friend.
```
 Then you would still have to fix the sentence. Is that what you want to achieve?

**Comment by LeonCheung** [comment]
@chriszo111 Bingo. So far, it would usually cost 10+ steps to make it right for each merge like this, so...

**Comment by chriszo111** [comment]
@LeonCheung Wouldn't it be even more handy to add two or more languages for each subtitle line and you can show them simultaneously instead of merging lines?

I assume that you want the solution to recognize when a chinese sentence ends and when an english sentence ended and merge them at the right position. I don't think that is a solution to aim at, because it is very specific (what about other languages etc.)

**Comment by darnn** [comment]
Sounds to me like he just wants a different merge function that turns
AB
CD

EF
GH
into
AB EF
CD GH
rather than into
AB CD
EF GH

**Comment by LeonCheung** [comment]
@chriszo111 Sorry I don't quite follow your suggestion, could you elaborate a bit more?

Certainly that it is not of any help to single language subs.  So I should emphasis that this is typically a big big time saver only when handling with multilanguage subs of such style, especially when you have to clean the mess left by the transcriber and translator, who usually care nothing about the proper duration, length, and break for long sentences.

**Comment by LeonCheung** [comment]
@darnn Exactly. You got the full point, bet it's not that hard to implement though.

**Comment by chriszo111** [comment]
I'd stick to it is a very specific case and hence functionality, that you only need for your personal (or business) use case. It is certainly not hard to implement. 

I'd suggest just using a simple javascript app where you copy/paste the whole Source view code into a simple HTML form and on button click you do your text serialization which transforms the subtitle source code like you want it. You only have to split the strings after the `<br />` tag and concatenate them.

**Comment by darnn** [comment]
But the whole point, if I may butt in again, is to do it in the process of working on the subtitles. You don't want to have to go to source view, copy, paste in a different program, fix one line, copy, paste to source code, find the line you were on again...

The reason I'm even saying anything is that here in Israel we also have dual-language subtitles, so I'd like to see this added too. I just haven't had to work on them very often, and when I did I had an English file and a Hebrew file, both with one line, and I only joined them (in an outside text exitor) after I finished editing both files.

**Comment by chriszo111** [comment]
Sorry @darnn to not be more clear. I thought you would just copy the whole source code, proceed with your text changes with the tool, paste it back. Or implement file upload to do so with the source code files.

Any way, it seems more people have this issue, it would be very specific (i.e. it has to match this specific pattern where you have ```<language1> <br /> <language2>```, but sure is not that big of a deal in C#

**Comment by LeonCheung** [comment]
@chriszo111 No offense but shall I assume that it's "very specific" to you because you don't think it's a very popular feature?

Allow me to share a bit of my story. For me and the people I ever know, we never use OCR for even once, however I believe Nikolaj developed it for a reason, and there gotta be somebody who can benefit from it. Again, please believe me, there are hundreds of thounsands of bilingual subtitles are made like that, at least in my region, not just about me myself personally, but maybe I'm the one who discussed it here first. This issue report is discussing the solution for merging. I'm about to discuss the solution for splitting separately as well.

I kept promoting SE locally for years. Perhaps there haven't been that many ppl know about SE in China, yet I've been trying to find ways in helping improving it, giving ppl more reasons to use and enjoy it, and support by donating possibly if they find it's really handy.

Thanks for your kind idea. I mean it. :)  But the **simple** script doesn't look **simple** to me. I'm realy not a coder.

**Comment by LeonCheung** [comment]
@chriszo111 So you still think working with multilanguage subtitles is kind of specific task. That's the point, isn't it.

**Comment by chriszo111** [comment]
@LeonCheung no, I am sorry to not be as clear so you could understand me. The task, going from
```
AB 
CD
EF 
GH
```
to
```
AB EF
CD GH
```
means that you concatenate the string exactly this way and no other way. That is a very specific task for a program to do. Nothing more and nothing less is what I was trying to say. And it has nothing to do with subtitles or the way they are written or published.

**Comment by LeonCheung** [comment]
You know this is just my humble suggestion on how to solve it, I mean the inefficiency when handling such subs, to be specific, the merging and splitting operation. It's up to devs to decide whether or not it makes sense. I just did my part. Any better ideas are welcome for sure.

**Comment by LeonCheung** [comment]
If you are merging two subs with dual language, it has to be like that, since that's exactly the expected result. Otherwise?

**Comment by chriszo111** [comment]
I already suggested a possible solution but we are just turning around in a circle and I don't see any productive outcome of this discussion. I wish you the best luck with your request and hope that the dev can implement your feature :)

**Comment by LeonCheung** [comment]
I know you are try to help here. But as I said, your suggestion means that I have to learn a programming language from scratch to solve a "not hard to implement" method, which definitely is not the option. Thank you sincerely all the same.

**Comment by niksedk** [comment]
Added shortcut for this - Options -> Settings -> General -> Merge selected lines bilingual

How does it work?

**Comment by LeonCheung** [comment]
Like magic! Thank you so much.

**Comment by LeonCheung** [comment]
Is it ready to close?

**Comment by LeonCheung** [comment]
@niksedk I think this feature broke in latest build, would you pls give it check?

**Comment by niksedk** [comment]
@LeonCheung: Seems to work here... could be failing in some cases I guess. Do you have a sample where it fails?

**Comment by LeonCheung** [comment]
Hmm, it seems problematic when I use Ctrl Shift B as shortcut, even though I cleared the old existed one.

**Comment by OmrSi** [comment]
Try using a clean Settings file maybe?
See if the shortcut itself is causing the issue or just because you cleared the old one.

**Comment by LeonCheung** [comment]
No difference. Try [this](https://drive.google.com/file/d/1qD9Ja_hDrbnp6Wo6miFJqP2o9NIU-z_G/view?usp=sharing).

**Comment by LeonCheung** [comment]
Yeah, it's a bit naughty... :P
