### ISSUE TITLE
Respecting Break for Waveform Text Preview

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2992]
Just my two cents:
![br](https://user-images.githubusercontent.com/494788/43536524-5dfd18cc-95ef-11e8-9e76-ab618d8c1c2a.gif)

Benefits:
1. Convenient for long multiline texts preview, especially for those of shorter duration.
2. Convenient for bilingual / trilingual subs.
3. More neat and tidy looking from aesthetic aspect.

FYI  :)

**Comment by niksedk** [comment]
How does this work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Pretty cool!
