### ISSUE TITLE
Strange Error With Gap Column

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2993]
How to repaat:
1. Show **Gap** column in List View;
2. Select the first line, then press R.
![err](https://user-images.githubusercontent.com/494788/43537984-5dd675e2-95f3-11e8-8e33-e3bca37e8218.png)

**Comment by niksedk** [comment]
@LeonCheung: thx for the info - I could not re-create the crash - but I've tried to make the code more robust: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
Better?

**Comment by LeonCheung** [comment]
I think it's no problem now. Thx for the quick fix. )
