### ISSUE TITLE
Respective Line Splitting Feature

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2995]
As discussed in #2991, a bilingual subtitle line splitting feature would be nice to implement, as well. Please see the GIF for a possible solution:
![splllll](https://user-images.githubusercontent.com/494788/43602741-6e6ec2e4-96c3-11e8-9718-09d24290bf99.gif)
It can be the most effective way I can think of, just wonder if it is technically possible.

**Comment by LeonCheung** [comment]
IMHO this is the final pain spot left for bilingual work. Hope it is convincing. :)

**Comment by LeonCheung** [comment]
I'll report it here since I think this is the right thread. :)
The splitting works pretty well, just it doesn't split at the video position.

**Comment by LeonCheung** [comment]
GIF:
![illu](https://user-images.githubusercontent.com/494788/44486438-3207ca80-a686-11e8-92f2-55fe8dc073a1.gif)

**Comment by niksedk** [comment]
He, yes - the right thread ;)
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
Perfect! Thanks for the huge time saving input!
