### ISSUE TITLE
Error when importing images

### ISSUE THREAD

**Issue by p1nkyy** [SubtitleEdit/subtitleedit#2998]
Tried to OCR from images, this error message is what I got

http://puu.sh/B84po/f66e6f8dad.png

Previous versions never had problem with importing & OCR-ing images.
I use the SE 3.5.6 Beta because I kept getting error #2952 even though I use Win 7.

**Comment by niksedk** [comment]
Could you send me the subtitle file (images not needed) either via email or attach it here? 

About the error #2952 - did you try installing latest .net 4.x framework?

**Comment by p1nkyy** [comment]
Still in the process of creating it. I made a subtitle from scratch via OCR Image.

**Comment by p1nkyy** [comment]
Hello, I encountered this problem again with SE 3.5.7.
So the images are from hardsubbed movie. I did a process with them using VideoSubFinder until it creates a black & white images of texts. The titles are actually the subtitle's beginning & start time (e.g: 0_00_28_509__0_00_32_480_01) and once that error message appeared, nothing can be OCR-ed.
