### ISSUE TITLE
Max. error% not saving.

### ISSUE THREAD

**Issue by Orum** [SubtitleEdit/subtitleedit#2999]
In version 3.5.6, the "Max. error%" setting for OCR doesn't appear to save.  Interestingly, this appears to only happen if you set it to a very small value (< ~0.7), in which case it will revert to 1.1 when opening it up to OCR again.  When set to larger values, it appears to work just fine.

I've only tested this with "Binary image compare," and not other modes.

**Comment by Orum** [comment]
No, it still seems to be reverting back to 1.1 after I set it to 0.0.

**Comment by niksedk** [comment]
OK, thx for testing - how is it now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip ?

**Comment by Orum** [comment]
Seems to be working fine now.  Thanks!
