### ISSUE TITLE
Wrong fix for OCR errors after a HI tag

### ISSUE THREAD

**Issue by XhmikosR** [SubtitleEdit/subtitleedit#300]
When there is a HI tag without a period, the next line's first letter shouldn't be fixed to be uppercase.

BTW, this shouldn't be in fix OCR errors...

```
105
00:04:39,030 --> 00:04:41,030
Now smoke that [bleep]

106
00:04:41,115 --> 00:04:44,834
or I'll smoke this bitch
right here.

```

/CC @niksedk

**Comment by ivandrofly** [comment]
Fixed.

@niksedk
