### ISSUE TITLE
Recalculate time doesn't work in .ass files

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3001]
I've set the min line time to 833, when using Recalculate time with ass files, it resets it to 830 even after saving and closing.
Just add a new line in an .ass file and use recalculate then save and open the file again, you will see the problem.

**Comment by niksedk** [comment]
Yeah, that's because SSA/ASS only uses two digits for milliseconds... not really sure what to do about this.

**Comment by OmrSi** [comment]
Oh, :\
Yeah, I remember its format now.
I don't think there is something to be done, it's just the format.
Thanks. :D
