### ISSUE TITLE
Scorcuts /edit line/ no working

### ISSUE THREAD

**Issue by desade2** [SubtitleEdit/subtitleedit#3002]
Hallo friends.

I assign keybord schorcuts (Y,X) to "move end 100 ms back" (and forward) und when I (after aktion) load next line, change is not saved. Why? I must have other steps (for example move time line /back and forward/, then saving is working.  Ver. 3.5.6.

**Comment by niksedk** [comment]
Hm, could you check latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip ?

**Comment by desade2** [comment]
Ok. I try it, then answer.

**Comment by desade2** [comment]
Thank you. In this beta version is not loading this error. Working fine. Thank, thank...

**Comment by niksedk** [comment]
Nice, thx for testing :)
I guess it's time for a new release soon...

**Comment by desade2** [comment]
Thanks by prompt.
