### ISSUE TITLE
Shortcut "Column, Delete text" Bug

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3003]
It should just delete the text from the line, but it deletes and shifts up.

**Comment by OmrSi** [comment]
Maybe you can add a shortcut for deleting text and shift cells up and fix this one, or just fix this one's function?

**Comment by niksedk** [comment]
OK, added an extra shortcut, so now both "delete text" + "delete text and shift cells up" should work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
All good. :)
Thank. 😁
