### ISSUE TITLE
Subtitle editing box is reset after switching video to full screen and back

### ISSUE THREAD

**Issue by ryvec** [SubtitleEdit/subtitleedit#3005]
Subtitle editing box size is reset after switching video player to full screen and back
![send](https://user-images.githubusercontent.com/42200865/43822645-20da976e-9b06-11e8-9517-31cb33d700e5.png)

**Comment by ryvec** [comment]
Issue persists across Windows 8.1 / 7 for sure, haven't tried others

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by ryvec** [comment]
Thanks!
