### ISSUE TITLE
Reset waveform position after new file

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3006]
Same as the one before...
![screenshot 202](https://user-images.githubusercontent.com/20923700/43858242-36573c46-9b56-11e8-9c2e-145972334f84.png)

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
Better?

**Comment by OmrSi** [comment]
Yep. :D
