### ISSUE TITLE
Wrong character count in EBU properties

### ISSUE THREAD

**Issue by FVonFaschion** [SubtitleEdit/subtitleedit#3009]
Hello,

In the "EBU STL properties" dialog, the position tags - {\an1}... etc - are counted as characters, so some lines can be incorrectly reported as exceeding the _max# of char per row_ in the "Errors" tab.

Thanks in advance !

Fred

**Comment by niksedk** [comment]
Thx :)
Beta updated;: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
