### ISSUE TITLE
Current subtitle line is displayed in tiny font when editing it (BETA version issue)

### ISSUE THREAD

**Issue by ryvec** [SubtitleEdit/subtitleedit#3010]
Current subtitle line is displayed in tiny font in list view when editing it. This apparently appeared in BETA version.

![donna](https://user-images.githubusercontent.com/42200865/43914322-06ef0198-9c21-11e8-9023-1ccae5ef616e.png)

**Comment by ryvec** [comment]
Or, if this is supposed to be a feature, could you please tell me, how to turn it off?

**Comment by niksedk** [comment]
In order to make background colors in the list view SE does custom drawing of selected lines, but it's not on purpose... and don't think this is specific to the beta version.

How can I re-create this?

**Comment by ryvec** [comment]
Sorry for bothering you! I fixed the problem by deleting settings file.
