### ISSUE TITLE
EBU STL

### ISSUE THREAD

**Issue by LucasCos** [SubtitleEdit/subtitleedit#3011]
Question. Where con I check original attributes of a EBU STL file that I open (margin top and bottom)?

Thanks.

Lucas.

**Comment by niksedk** [comment]
Try File -> EBU STL properties...

**Comment by LucasCos** [comment]
I tried it but it show not the attributes a file that I just opened but the fixed parameters stores in Subtitle Edit.

**Comment by niksedk** [comment]
Could you explain exactly what you want?

**Comment by LucasCos** [comment]
For example I saved a EBU STL with this parameters (Attached):
Margin top: 0
Margin bottom: 1
Number of rows: 1

![screenshot 2018-08-10 12 17 09](https://user-images.githubusercontent.com/30738812/43966227-b5d7eb7c-9c97-11e8-8915-3ed9df57f244.png)

The working for other project I save with:
Margin top: 0
Margin bottom: 2
Number of rows: 2

Then open the first project instead of showing:
Margin top: 0
Margin bottom: 1
Number of rows: 1

It show the last used parameters.
Margin top: 0
Margin bottom: 2
Number of rows: 2

I want to know if there is any option to check the real attribute of vertical position saved in a EBU STL file.

Please let me know if it´s clear my explanation.

Thanks in advance.
Lucas.
