### ISSUE TITLE
Allow customizing BOM mark when exporting to vtt

### ISSUE THREAD

**Issue by vbezhenar** [SubtitleEdit/subtitleedit#3012]
I'm using LG TV with webOS 3.5 and it doesn't work with default exported vtt file. If I open this file in text editor, remove BOM mark from the beginning of the files, it works fine. It would be useful if I could set those settings on export or somewhere else.

**Comment by aaaxx** [comment]
There's a general BOM option, hidden in the Settings.xml file, `WriteUtf8Bom`. You can set it to `False`, but it will affect all formats.

**Comment by niksedk** [comment]
@vbezhenar: You should probably also write to LG as it seems like they have a bug: https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#WebVTT_body

But do use the `WriteUtf8Bom` option as @aaaxx suggests.

**Comment by vbezhenar** [comment]
Thanks, it works.
