### ISSUE TITLE
Error message: Indekset lå uden for området

### ISSUE THREAD

**Issue by daninino** [SubtitleEdit/subtitleedit#3015]
Hi
Tried to OCR a HDMV PGS in a MKV created by MakeMKV only Video, Audio and one subtilte. Got the error below. I don't see a preview of the subtilte as I usually do.

![image](https://user-images.githubusercontent.com/208594/43994492-1604e39a-9d9e-11e8-9bfe-d905455d070a.png)

This is bonus materials from the disc, the main movie works without any issues.

**Comment by niksedk** [comment]
@daninino: Could you possibly email me the file without the audio and video track? (can be removed with e.g. mkvtoolnix)

**Comment by daninino** [comment]
Hi
Sorry for the inconvenience it turned out the subtitle track was a dummy track with no information.
I didn't try out the track in VLC befoer earlier today also I tried the disc directly in a BluRay player. So it seems I'm just an idiot and didn't actually test the track before trying to rip it. This is just the respond to an empty subtitle file.

/Danny

**Comment by niksedk** [comment]
OK, thx for the info - still I would like to check the dummy track, so I can avoid the crash.

**Comment by daninino** [comment]
Sure, it is attached here

**Comment by OmrSi** [comment]
Hey, This isn't a "problem" per se, but it's also a crash.
When importing a scene changes file that doesn't have correct time codes, this shows up:
![image](https://user-images.githubusercontent.com/20923700/44003318-77d5c4a2-9e59-11e8-9580-85cba1349955.png)
