### ISSUE TITLE
remove italics formatting

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#3016]
Hello,
subtitleedit had been working just fine for me, but lately, it has been removing the italics formatting from the subtitles that I input.

**Comment by niksedk** [comment]
@lambdacore12: How can I re-create this?

**Comment by lambdacore12** [comment]
Create an external .srt file with some words in italics, then insert it in subtitledit. See if they are still in italics.

**Comment by lambdacore12** [comment]
@niksedk

**Comment by niksedk** [comment]
@lambdacore12: The words are still in italic here... perhaps some screenshots? 
Could you be saving in a format without support for italic?

**Comment by niksedk** [comment]
@lambdacore12: Could you attach or email the subtitle file?

**Comment by lambdacore12** [comment]
OK. 
[markdown.zip](https://github.com/SubtitleEdit/subtitleedit/files/2280835/markdown.zip)

**Comment by niksedk** [comment]
Was that the original subtitle?
It has no italics...
     
    1
    00:00:01,030 --> 00:00:03,995
    Dans ce chapitre,
    nous allons aborder la syntaxe Markdown

**Comment by lambdacore12** [comment]
After checking, it seems that the problem is from the subtitles themselves. When I am working on the website, I add italics formatting, but as soon as I download the subtitle, the formatting disappears. I am sorry for causing you all this trouble.

**Comment by OmrSi** [comment]
This is kinda funny. 😅

**Comment by lambdacore12** [comment]
@niksedk what about when the ">" transforms into " &gt; " like on the following screenshot?

![image](https://user-images.githubusercontent.com/37704802/44001772-b982a1e2-9e2f-11e8-8bfc-c5ea207ac88f.png)
