### ISSUE TITLE
[Suggestion] Shortcuts Searching

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#3025]
Maybe it would be cool to have a small search tool in shortcuts setting window, since we have a too long list already! :rofl:  Currenlty there are 150+, and things keep growing here.

And a Shortcuts Import/Export feature would also be cool if possible.

**Comment by OmrSi** [comment]
I don't think a search tool is necessary, first of all, you can't search since you don't memorize all the names, and If you did memorize them, then you don't need a search tool.
Also, you have sections, when you need a certain shortcut, you'll find it in its section.

The second part is a good idea, though you can keep a backup settings file and all of your settings are saved.
Just my opinion on the matter.

**Comment by LeonCheung** [comment]
@OmrSi While my opinion is: even if I don't memorize all names, at least I know what I'm trying to find, e.g. if I want to set shortcuts for play rate controls, then I can at least try typing "play rate", then bingo. On the other hand, if I already know we have such setting, then it still need seconds to target them among a so looooong list even though it is categorized. Anyway, just an humble suggestion from an end user's true experience. :)

**Comment by darnn** [comment]
I've often wished for a search tool in the shortcuts menu, both for text in shortcut description and for specific key combinations. I've had to scroll through the entire list to find one specific thing I only remembered one word from before. In the meanwhile I've just taken screenshots of the settings menu and OCRed them, so now I have all the names in a text file.

**Comment by niksedk** [comment]
How does this work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Awesome. :O

**Comment by niksedk** [comment]
I guess that's needed - but it seems to work here...

**Comment by LeonCheung** [comment]
Wow, cool! Hmm, I think I know what OmrSi means. It seems it can only be changed by clicking OK, instead of clicking Update. Is it a problem for now?

**Comment by OmrSi** [comment]
Yeah, I was gonna write that, just noticed it.
I don't think it's a problem.
It will only be a problem if you're editing multiple shortcuts with multiple searches.

**Comment by niksedk** [comment]
Ah, I see it now - after "Clear" it shows the old shortcut

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
How does it work for you guys?

**Comment by OmrSi** [comment]
Still doesn't save after "Clear" and returning to list.

**Comment by LeonCheung** [comment]
So far so good.

**Comment by niksedk** [comment]
@OmrSi: Seems to work here... or what exactly do you do?

**Comment by OmrSi** [comment]
Search for something, select it, click "clear", search for something else, the first one returns to its original shortcut.

**Comment by OmrSi** [comment]
Yep, I tried with and without "update".
![screenshot 220](https://user-images.githubusercontent.com/20923700/44047635-9b535690-9f37-11e8-97ec-4c8e50e780e6.png)
![screenshot 221](https://user-images.githubusercontent.com/20923700/44047636-9b82d014-9f37-11e8-8689-401913733bd4.png)
![screenshot 222](https://user-images.githubusercontent.com/20923700/44047637-9bb2c698-9f37-11e8-8566-7bc2a0d906a5.png)
![screenshot 223](https://user-images.githubusercontent.com/20923700/44047639-9be90ff0-9f37-11e8-9938-db5d35635cb4.png)

I see it now, after returning to the full list, you'll see that the shortcut is still there, but if you click "Okay" and open the settings again, you'll find it cleared.

**Comment by niksedk** [comment]
Ah, that "Clear" button :)
Thx - this should be really close: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

Right!?

**Comment by OmrSi** [comment]
No, It isn't "close", this IS it. :D
I think everything is good now. 👌👍
Thank you.

**Comment by OmrSi** [comment]
Closed?

**Comment by darnn** [comment]
By the way, I left before I could say anything, but I wanted to thank you for this too! It works great!
