### ISSUE TITLE
Tags are considered when splitting by Characters

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3026]
When splitting by characters, normal and ass tags are taken into consideration, while they should be igonred.

**Comment by OmrSi** [comment]
When using advanced splitting, by the number of characters.

**Comment by niksedk** [comment]
Hm, seems to work here... but I think it counts line-break as two characters - how does it work for you?

**Comment by OmrSi** [comment]
Working as they are ignored or working as they are counted as characters?
My point is, when splitting by the number of characters, tags shouldn't be counted, because you won't translate then if you are splitting the file between two translators.

**Comment by niksedk** [comment]
Tags are ignored here... perhaps a screenshot could help?

**Comment by OmrSi** [comment]
With no tags...
![screenshot 207](https://user-images.githubusercontent.com/20923700/44002477-d52a129c-9e4b-11e8-9692-b75a6ba7a126.png)
after adding "{\fs32}{\fnArabic Typesetting}<font color="#FFA500">" to the first three lines
![screenshot 208](https://user-images.githubusercontent.com/20923700/44002481-f06636e4-9e4b-11e8-848a-33935f3b796a.png)
after adding just "{\fs32}{\fnArabic Typesetting}"
![screenshot 209](https://user-images.githubusercontent.com/20923700/44002484-00139f1e-9e4c-11e8-8f1e-3df755761085.png)


I'm sorry If I'm missing something and wasted your time. :\

**Comment by niksedk** [comment]
I was in "split long lines"... also needs a minor fix ;)
