### ISSUE TITLE
[Feature Request] Move Gap Forward/Back

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#3027]
Since this is needed for fine tune, an increment of 100ms would be nice enough. Thank you!
![move gap](https://user-images.githubusercontent.com/494788/44001818-4649a09a-9e6b-11e8-94e1-49bf172b6c25.gif)

**Comment by OmrSi** [comment]
this is like "Alt + Mouse left", right?

**Comment by LeonCheung** [comment]
Exactly, I found sometimes it is more efficient and precise by using keyboard.

**Comment by ldgbc** [comment]
Is that feature already there? Or this image is a demo of feature request? (How you shift it one timer and the timer next to it move too)

**Comment by niksedk** [comment]
Fixed in #4078
