### ISSUE TITLE
Progress status in title bar

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#303]
Translate progress: percent with subtitle orginal and new subtitle. (percent per line translated)
New translation progress: percent with only new subtitle (blank) and translated per movie time.
movie 60min: Translated to 30 minutes is 50%

(some sort of auto-detection of mode or ?)

**Comment by Global90** [comment]
Please add percent in SubtitleEdit for both methods.
1. new subtitle for translate with movie file(get Current time video and Calculation percent).

2. news subtitle for translate with open orginal subtitle (translate mode) . get Current line translated and Calculation percent.

![untitled](https://cloud.githubusercontent.com/assets/8215910/6041209/74df1966-ac8f-11e4-8fef-2c92eae943a8.gif)

**Comment by niksedk** [comment]
@Global90: Could you test this version: http://www.nikse.dk/SubtitleEdit.zip (no installer, beta) ?

**Comment by Global90** [comment]
i tested this version. but i dont see Progress(percent) in the SE.

i write in lines. and open orginal subtitle(translation mode) but any Progress.

Thankyou

**Comment by niksedk** [comment]
it's in the lower left corner - statusbar...
![untitled]http://www.nikse.dk/Test.png)

**Comment by niksedk** [comment]
But if you use something like GT to get a start it won't work...

**Comment by Global90** [comment]
MR. Nikolaj i dont have GT

My PC:
Win7 x86
.Net 4.5

Step1: open SRT file (1700 Lines)
Step2: open orginal Subtitle (this File)
Step3: remove Lines to 10 Line
Step4: ReWrite Line Orginal Text
Step5: All Row (Column Text) to empty
Step6: Write in Column Text

![untitled](https://cloud.githubusercontent.com/assets/8215910/9294195/1992c166-445b-11e5-9dee-96a9f5592e9e.jpg)

![1](https://cloud.githubusercontent.com/assets/8215910/9294194/197e5f28-445b-11e5-9a38-0ed76e7b013a.jpg)

**Comment by niksedk** [comment]
Did you use the beta I linked to?
Included the Settings.xml? (ShowProgress must be true)

**Comment by Global90** [comment]
i download http://www.nikse.dk/SubtitleEdit.zip (3.4.8 build 107)

and add <ShowProgress>True</ShowProgress> in Settings.xml in tag <General> Because ShowProgress not found in Settings.xml.

again dont show Progress

**Comment by niksedk** [comment]
This should be really easy:
1) Download http://www.nikse.dk/SubtitleEdit.zip (3.4.8 build 110 now)
Unpack it and run SubtitleEdit.exe (the folder already includes a Settings.xml)

2) open an existing subtitle.... click Tools -> Make new empty translation for current subtitle

**Comment by Global90** [comment]
Percent Is Very Good Work in This Mode. Thankyou

A few tips:
1. after translate line 10  , Percent go Hide. Why?
2. Please Percent Progress Always show in Statusbar in any Modes.
3. Please Add New Mode: calculate the percent of the translated files in the empty file with Video (Get Video Time and End of Line for calculate Percent of the Translated)

![1](https://cloud.githubusercontent.com/assets/8215910/9313188/c3a965de-4536-11e5-963a-58401aaab831.jpg)
![2](https://cloud.githubusercontent.com/assets/8215910/9313190/c43feab8-4536-11e5-957f-ffb7d58e8a82.jpg)

**Comment by OmrSi** [comment]
@niksedk Isn't this done? I'm using it and not seeing any problems.

**Comment by OmrSi** [comment]
@darnn Maybe you're talking about these cases where the file has no timing, @niksedk notice the number:
![screenshot 182](https://user-images.githubusercontent.com/20923700/52524355-b2f26700-2ca4-11e9-9c40-f7772d03e3b2.png)

**Comment by darnn** [comment]
That might have been it! Also, outside of translator mode, I will sometimes have a file with, like, 800 empty lines that I slowly fill in (in order to just use the "move to next line" key, instead of creating a new line every time), that also creates percentages of over 100%:

![se empty subtitle file](https://user-images.githubusercontent.com/19672444/52524971-94439e80-2cab-11e9-8f29-1caa1027af93.png)

**Comment by OmrSi** [comment]
Yeah, if a subtitle's timing is more then a video's, it goes over 100%.

**Comment by OmrSi** [comment]
@niksedk Issue when importing plain text:
![image](https://user-images.githubusercontent.com/20923700/90775094-11b88800-e301-11ea-8783-3a5990335195.png)
