### ISSUE TITLE
[Suggestion] Splitting in Translator Mode

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#3030]
For splitting in Translator mode, imho it would make more sense to respect position of two cursors, I mean one in translation textbox and another in original textbox. Since we can already track the cursor position, maybe it is possible?

![split](https://user-images.githubusercontent.com/494788/44047869-5557d7b2-9f62-11e8-923f-9c4e0db29798.png)

**Comment by niksedk** [comment]
Now that #2991 is included, this is worth a try too - how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
