### ISSUE TITLE
Error style

### ISSUE THREAD

**Issue by MrGoraj** [SubtitleEdit/subtitleedit#3032]
Subtitles created in Aegisub doesn't work (error) in Subtitle  Edit.

![image](https://user-images.githubusercontent.com/32809530/44094194-cd63e3ea-9fd5-11e8-92a3-ee445407549d.png)

**Comment by niksedk** [comment]
@MrGoraj: Could you possibly attach the subtitle?

**Comment by OmrSi** [comment]
It's probably not my place to say, but the file opened without a problem here.
Have you tried the latest Beta?
![screenshot 224](https://user-images.githubusercontent.com/20923700/44115624-0fcec448-a017-11e8-9790-0186372456b5.png)

**Comment by OmrSi** [comment]
Strange...
![screenshot 226](https://user-images.githubusercontent.com/20923700/44155341-aba8b9ac-a0b5-11e8-9e1c-c978bfd73855.png)

**Comment by MrGoraj** [comment]
@OmrSi I can record how I download the beta version of the program and open it with the subtitles xd

**Comment by OmrSi** [comment]
😂😂😂😂😂😂
Hey, I'm not saying you're lying, man. 😅
Just wondering where the problem is, we will see what Nikolaj finds out. 😁

**Comment by marb99** [comment]
with last build 3.5.6 build 361 opened without a problem here too

**Comment by MrGoraj** [comment]
Where did you get this version? Because I have 3.5.6 build 359

I downloaded it from: https://github.com/SubtitleEdit/subtitleedit/releases

![image](https://user-images.githubusercontent.com/32809530/44164696-048bb180-a0c7-11e8-8343-499319a33e1e.png)

**Comment by OmrSi** [comment]
I think he just means the latest Beta.

**Comment by marb99** [comment]
@MrGoraj 

download lastest SVN and build it with VS 2017

**Comment by MrGoraj** [comment]
Okay, I don't fuckin get it. 

I have last released beta version (bulid 373) and I have still this same error :V

![image](https://user-images.githubusercontent.com/32809530/44363407-659af700-a4c4-11e8-8995-8a7032df2362.png)
