### ISSUE TITLE
Added Lines in .ass files don't have a style

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3035]
When you add a line to an .ass file, it doesn't take the default style until you close and open the program.
The style affects the line but is not written beside it.

Edit: this happens when adding a line with "F9" in "Create" or with Waveform's "Insert a line at video position". 
Also after using typewriter effect.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

thx for all the bug reports :)
You are really good at finding them!

**Comment by OmrSi** [comment]
Perfection. 😄
The thanks is all yours. 
I try to take advantage of all the program's features and that's when I notice these things, I just hope that these reports don't cause you any discomfort and make up for my, sometimes, constant nagging about some things. 😁😅

**Comment by OmrSi** [comment]
The same happens when If you change the file's extension from "format" at the top of the program.
Old Lines don't take a default style.
