### ISSUE TITLE
[Shortcut request] Play from just before text 

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3036]
Just getting it up...

It's F10 on "Create" mode but if you change to "Adjust", there isn't a shortcut for it...
Maybe make it global instead of linked to a certain mode?
move the ability to assign a shortcut from "Create" to "Video"?
I think it would be the best course of action.

**Comment by niksedk** [comment]
Like this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Yeah. :D
But, "Play text from current subtitle" is already available in the waveform section as "Play selection", I don't think it is needed here.
Also, All "F" group has a default action in all modes.

Here is my suggestion, Give "F10" its original default actions back and add a global shortcut for "Play from just before text".

And thank you very much. <3

**Comment by niksedk** [comment]
Yes, will be a minor change: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
How does it work?

**Comment by OmrSi** [comment]
Perfection. 👍👌
