### ISSUE TITLE
not able to display japanese subtitle 

### ISSUE THREAD

**Issue by newbie420** [SubtitleEdit/subtitleedit#3038]
Hi everyone,
I'm using subtitle edit on ubuntu with mono. I have a .srt file in japanese but SE displays the text in weird rectangle symbol. The .srt file is in UTF-8 and the encoding on subtitle edit is also set to UTF-8. The subtitle works fine on other editor like aegisub and gaupol, and also on VLC. Do you have any suggestion, i cant find the solution anywhere. Thanks in advance!!!

**Comment by niksedk** [comment]
@newbie420: What happens if you try File -> Import subtitle with manual chosen encoding ?

**Comment by aaaxx** [comment]
Also could be a font issue (Settings → General → Subtitle Font).

**Comment by newbie420** [comment]
@aaaxx yes, i change the font to Droid Sans Japanese and it works now. Thank you so much !!!
@niksedk i tried import it like that but keep the encoding of the subtitle file and none of the japanese encoding worked. When i tried converting the encoding of the subtitle file to the ones in Subtitle Edit, it said it couldn't save the file with that encoding, so i was stuck there. But changing the font worked. Thank you for replying

**Comment by LeonCheung** [comment]
I wonder if it occurs on that specific file or on all Japanese files.
