### ISSUE TITLE
[suggestion] Find/remove words in all uppercase when removing hearing impaired text.

### ISSUE THREAD

**Issue by Jolar** [SubtitleEdit/subtitleedit#3045]
I regularly come across subtitles where there is no colon or parenthesis in descriptive lines, and could look like for example:

DOG YAPS Beware of the dog.
See you, bye. Bye, Jasper. DOG BARKS

I also see subtitles now and then where the colon probably have been missing to start with when the subtitle was cleaned:

WILLIAM I don't think so.

It would be nice to have a way of removing such text in the "Remove text for hearing impaired" tool. On top of my head I guess you can distinguish such words from abbreviations with the capital letter at the beginning of a sentence, and the punctuation. Example:

IKEA may have something like that. (correct)
OK, let's go to IKEA. (correct)
WILLIAM That's nice. (needs to be fixed)
OK, that's nice. (correct)

Well, I'm sure there are a lot of things to consider... :)

**Comment by diomed** [comment]
this will never really get implemented because trouble with this is - that any thing could be written in capital letters.

like various signs and especially names of towns etc.

**Comment by OmrSi** [comment]
Exactly, Even if, for example, he used Regex to only delete the ones at the beginning of the line, there would be a lot of errors.

**Comment by Jolar** [comment]
Well, the files I have looked at so far are all following the capitalization/punctuation examples I gave above, and would have been correctly cleaned with such an adaptation.

Of course there must be other cases, but maybe it wouldn't be worse than the mistakes the tool _already_ makes? For sure you anyway must always look through the corrections and see where for example parentheses actually should stay (the most common error).

(And I must say the comment with "...various signs and names of towns etc." makes me a bit confused in that those are examples of text that _should_ be removed, and in most cases _are_ already removed with the current implementation of the tool.)

**Comment by SixelAlexiS90** [comment]
Hi! Did this ever got implemented? I see it got closed at "completed" but I can't find the option for it in the latest version (3613), same for the Beta.
I'm using this subtitles that have this random people names in it all in uppercase and it would be great to have an option to just remove the uppercase words, with all the warning of the case as well but at least having an option for situations like this (just as OP have shown, it happens especially in badly cleaned up subtitles).
Having a "Remove words in UPPERCASE" option as well would be a godsend.
[there should be a secondary checkbox to remove only words of at least two letters just to not mess up with something like "I" and such]
Thank you very much!
