### ISSUE TITLE
What happens to .ass tags when converting the file to .ass?

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3046]
I mean, I write the tags in the .srt file and it stays the same, but when I convert it to .ass the ass tags are converted to "HTML" tags and the lines get messed up.
Why can't the tags stay the same when opening an .ass file?

For example, the line was:
{\fs35\1c&H000000&\fnArabic Typesetting\3c&H0000FF&}عـمـر الـشـققـي{\r\1c&H000000&\fs22\3c&FFE87C&} :ترجـمـة

In SE when opening the ass file:
<font size="35" face="Arabic Typesetting"><font color="#000000">{\3c&H0000FF&}عـمـر الـشـققـي{\r\1c&H000000&\fs22\3c&FFE87C&} :ترجـمـة</font></font>

After editing it in SE:
{\fs35\fnArabic Typesetting\c&H000000&\3c&H0000FF&}عـمـر الـشـققـي{\r\1c&H000000&\fs22\3c&FFE87C&} :ترجـمـة{\fn\fs}

Shouldn't the tags just stay as is? Why would they be converted to HTML tags?

**Comment by OmrSi** [comment]
You told me once:
"SE support 250+ formats and I've chosen that italic etc are in html tags - all code uses this and only when writing to output format is text transformed to the target format.
Also, all formats will look alike in the editor regarding newline and italic etc."

But if there is more than one tag in a sentence, or there was one miswritten tag, the whole line gets messed up.
It would be better if all tags are left as is, like when using .srt, just my opinion.

**Comment by niksedk** [comment]
Fixed in 6672501b83023fbe48b23fd3f3f5ff951b9570a9
