### ISSUE TITLE
Waveform isn't loaded when dragging file

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3047]
If you load a file by dragging it, and you had already generated the waveform, it only opens the video, not the waveform, or at least that's what's happening in latest Beta.

**Comment by LeonCheung** [comment]
Dragging a what file? txt or video? Just make sure if you are talking about #2989

**Comment by OmrSi** [comment]
Nope. 
Just a normal Srt or Ass file. 
I had already generated the waveform but it doesn't open with the video.

**Comment by niksedk** [comment]
Hm, that works here...

**Comment by OmrSi** [comment]
Hmmm. I was able to recreate this.
Turns out the waveform doesn't open If I dragged or opened the file from SE.
I use FFMPEG.
Steps:
Downloaded a new video file from youtube, opened the video in SE, generated the waveform, added some lines, Saved the file, closed the program.
So the subtitle file's name was different before generating and after. don't if that's related.
At this point, the generated waveform is "xmj9qz2FV3sjgUHKvVHWLyJ7Ao72EmrroaWOHTWg4o.wav"
then I closed and opened SE again, there was no waveform, when I generated it again it was "RuLF5aAsPmRHbygetQ5wbkYFxynZt8geZh20rEI0".
Now it always works with the video.

Quick note: Isn't it possible to name the generated waveform and scene changes files like the original video? Or is it not because FFMPEG and VLC are the ones that do that?

**Comment by niksedk** [comment]
I still cannot re-create this... did you rename the video file?

**Comment by OmrSi** [comment]
Here, look:
Here I opened the video, then generated the waveform then added some lines:
![screenshot 274](https://user-images.githubusercontent.com/20923700/44550868-240d8480-a72e-11e8-9941-2895b32b58a6.png)
Then I saved the file in the video name.
![screenshot 275](https://user-images.githubusercontent.com/20923700/44550919-4bfce800-a72e-11e8-913f-09877cc6dbcd.png)
Then I closed the program and opened it, then I dragged the srt file to it:
![screenshot 276](https://user-images.githubusercontent.com/20923700/44550975-7058c480-a72e-11e8-8b01-5ef014c000be.png)
Then I generated the waveform again:
![screenshot 277](https://user-images.githubusercontent.com/20923700/44551028-9a11eb80-a72e-11e8-8b85-bc00eed0403f.png)
I noticed this happening when dragging the file or using open with.

**Comment by niksedk** [comment]
thx - it's think it works now:  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk Ok, It's working now, but there are a couple of problems.

1. The waveform file is being saved in "AppData\Roaming\Subtitle Edit" not "AppData\Roaming\Subtitle Edit\Waveforms".

2. When you open the file through "Open with" or dragging it to SE, It doesn't remember the last position, It just goes to the first second of the video, and if you had opened an original file with it, it goes to the beginning of the video and doesn't open the original file.

Note that those things only happen when dragging or opening through "Open with".

When opening from inside SE:
![screenshot 281](https://user-images.githubusercontent.com/20923700/44581530-bc475000-a7a6-11e8-9624-5d988a6a19ce.png)

Dragging to SE or using "Open with":
![screenshot 282](https://user-images.githubusercontent.com/20923700/44581547-d123e380-a7a6-11e8-8c75-6dfae95406e6.png)

**Comment by niksedk** [comment]
thx for testing :)
New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk The mentioned problems above are solved now. Thanks :D

But there is a new problem, for some reason, when I open the program I get "File not found" when there isn't an opened file in the first place, and I haven't deleted the last file I opened.
When I press Ok, it opens without a problem.
![screenshot 285](https://user-images.githubusercontent.com/20923700/44606861-3d2e3800-a7f7-11e8-938e-23d6c8402f90.png)


Also, when importing or generating a scene changes file, it still takes the old name, not the new hash.
![screenshot 286](https://user-images.githubusercontent.com/20923700/44606886-50d99e80-a7f7-11e8-9117-d1bda03d8327.png)

**Comment by niksedk** [comment]
@OmrSi: thx - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
You probably need to clean your waveform/spectogram folders - SE will check for old hash first and use the old hash if it's available ( SE tries to be nice ;)

**Comment by OmrSi** [comment]
Haha. That's why we love SE :D
Thanks a lot.
The problem is solved, but scene changes file still takes the old kind of hash
![screenshot 287](https://user-images.githubusercontent.com/20923700/44607930-acf1f200-a7fa-11e8-993f-95b13bbddc96.png)
![screenshot 288](https://user-images.githubusercontent.com/20923700/44607942-b2e7d300-a7fa-11e8-80c6-88d30313a702.png)

**Comment by LeonCheung** [comment]
Oh, this is sooo cool, yet another efficiency booster for larger video files. Just... when dragging into the Waveform area instead of Videoplayer, it still needs re-generating. Is that by design or?

**Comment by OmrSi** [comment]
@niksedk Yep, Perfectly working.
The only thing left is the other issue I talked about.

" I noticed that if you open it using dragging or open with, it doesn't remember the line you were at, it always goes to Line 1, and when you open it from SE after that, it remembers that it was at number 1 when you opened it by dragging or open with..."

**Comment by OmrSi** [comment]
@niksedk I noticed just now that SE is also returning to line number 1 when you open the file, close SE, and open SE again, but if you opened it from inside SE, it remembers.

So, It's returning to Line 1 when dragging or using open with or closing the opening SE without closing the file.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
How is it?

**Comment by OmrSi** [comment]
Yep. Everything I mentioned I solved and working.
Thank you very much.
If there is nothing else, you can close this. :D

**Comment by niksedk** [comment]
thx for testing :)

**Comment by OmrSi** [comment]
@niksedk I found another problem here. :\
Now index is saved only if a waveform is loaded, If there isn't a waveform and you closed a file then opned it, SE doesn't remember the index.
