### ISSUE TITLE
[Bug] 3 bugs in Translator's mode

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3049]
1. When you unbreak a line, the original subtitle's line unbreaks with it too.
But when you break, the original doesn't.
The desired behavior is that the original stays the same, I think.

2. The "Total length" should be in the right position (The green box).

3. ~~The Chars\sec for the original subtitle isn't recalculated when you change the Line's time (Red Box), it only updates after closing and opening SE.~~
![screenshot 291](https://user-images.githubusercontent.com/20923700/44618852-7497f580-a886-11e8-8cd0-4632d9e0e9bc.png)

**Comment by OmrSi** [comment]
Add to this another two bugs in translator's mode.
1. The "Total length" should be in the right position (The green box).
2. The Chars\sec for the original subtitle isn't recalculated when you change the Line's time (Red Box), it only updates after closing and opening SE.
![screenshot 291](https://user-images.githubusercontent.com/20923700/44618852-7497f580-a886-11e8-8cd0-4632d9e0e9bc.png)

**Comment by niksedk** [comment]
2 + 3 I cannot re-create...

**Comment by OmrSi** [comment]
Strange.
Number 2, I download a beta and used a clean settings file and it's still there.
Maybe because the screen is FHD?
Or bot, even if I override the layout to suit the application or change the screen resolution it's still there.
![screenshot 297](https://user-images.githubusercontent.com/20923700/44627278-be8ae500-a933-11e8-8acb-319e7f55b03b.png)
![screenshot 298](https://user-images.githubusercontent.com/20923700/44627279-c21e6c00-a933-11e8-9d9e-8d22be8558b2.png)

Also with 3, a clean settings file:
![screenshot 299](https://user-images.githubusercontent.com/20923700/44627328-9fd91e00-a934-11e8-9406-b1e06a7b439d.png)
![screenshot 300](https://user-images.githubusercontent.com/20923700/44627330-ac5d7680-a934-11e8-9c60-1c1bdd6e84ab.png)

After closing and opening:
![screenshot 301](https://user-images.githubusercontent.com/20923700/44627335-c1d2a080-a934-11e8-9fa4-3d68af272981.png)

**Comment by OmrSi** [comment]
@niksedk Can you solve No. 1 before the next version? It's the only one that affects the original translation.

**Comment by OmrSi** [comment]
@niksedk Thank you. <3
The one you solved was 2, No. 1 is the one which edits the original, it unbreaks original when you unbreak a line.
Breaking doesn't affect original, just unbreaking.

**Comment by OmrSi** [comment]
@niksedk Thank you. <3
The one you solved was 3, No. 1 is the one which edits the original, it unbreaks original when you unbreak a line.
Breaking doesn't affect original, just unbreaking.

**Comment by OmrSi** [comment]
@niksedk Would you look at no. 1?

**Comment by OmrSi** [comment]
@niksedk Can you please take a look at the unbreaking issue? It's really annoying when working with an original subtitle, breaking doesn't affect the original, only the unbreaking...

**Comment by OmrSi** [comment]
@niksedk I traced it back to this commit https://github.com/SubtitleEdit/subtitleedit/commit/5d7b326c1233d551da213d60f151ddfaacdef18d
After this commit, unbreak started affecting the original in the translator's mode.
