### ISSUE TITLE
"Replace all" not replacing the last instance (build 402)

### ISSUE THREAD

**Issue by ryvec** [SubtitleEdit/subtitleedit#3055]
Sometimes it does, sometimes doesn't. Quite often doesn't. Pictured below:
1. before replacing
2. specifying what to replace, hitting "Replace all" button
3. after

![screenshot 7](https://user-images.githubusercontent.com/42200865/44592560-62f91400-a7da-11e8-968a-b4a5f3328f13.png)
![screenshot 8](https://user-images.githubusercontent.com/42200865/44592557-62607d80-a7da-11e8-8c19-004d01c4fdc0.png)
![screenshot 9](https://user-images.githubusercontent.com/42200865/44592559-62f91400-a7da-11e8-9e77-af36351b6e59.png)

**Comment by niksedk** [comment]
Could you attach the sub also? (just makes it easier)

**Comment by ryvec** [comment]
Sure, uploaded!

[The.Innocents.S01E01.The.Start.of.Us.720p.NF.WEB-DL.DDP5.1.x264-NTG_track24_rus.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/2319223/The.Innocents.S01E01.The.Start.of.Us.720p.NF.WEB-DL.DDP5.1.x264-NTG_track24_rus.srt.zip)
