### ISSUE TITLE
[Request] Merging lines doesn't auto break

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3058]
As I mentioned in the comments here https://github.com/SubtitleEdit/subtitleedit/commit/4ab31e901bc14b3daa7b439127e16cf038d0e9ec
Just thought I'd open an issue to close it with a commit when and if it's done. :D

Can you unify the shortcuts and the menu options the other way around, go back to what the shortcuts used to do.

The list and shortcuts now Merge and auto breaks the line, I'm saying they both should merge without auto breaking or unbreaking because you can just use the auto break after it, They should just put the lines with each other like they used to do.
In Arabic and English, you can only use 42 characters in each line, Netflix rules.

When you use reverse RTL, then review the file and merge some lines, it will be all messed up when it auto breaks, so it would be easier to just merge then auto break if you want instead of, 1. reverse, 2. merge, 3. tidy the line, 4. reverse again.

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

If this works it kinda requires a "merge and auto-break" shortcut...
