### ISSUE TITLE
[Bug] Index isn't remembered without saving

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3060]
If you open a file and set the video position to a line then exit without changing anything or saving, SE doesn't remember the index when you open the file again.
This happens when you set the video position to a line, then open another file or click "New file", but if you set it and close SE then open it again, it remembers.

Also related to this, If you open a file, make a change, close the video, save the file, open the file again, the index will be at the last edited line, but the video position is set to the first line.
![screenshot 295](https://user-images.githubusercontent.com/20923700/44623174-d1b89900-a8d0-11e8-8c47-00f7af08f0e2.png)

**Comment by niksedk** [comment]
thx :)
Should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk The first one is fixed but the second isn't. :D

The second being: "If you open a file, make a change, close the video, save the file, open the file again, the index will be at the last edited line, but the video position is set to the first line."
