### ISSUE TITLE
Application error (Access to the path is denied)

### ISSUE THREAD

**Issue by areacode514** [SubtitleEdit/subtitleedit#3061]
Just installed Subtitle Edit and am getting the following when trying to open the video file associated to the SRT I am trying to edit:

=================
An application error occurred in Subtitle Edit 3.5.6.0
...
Access to the path 'C:\Users\........filename.mp4' is denied.
=================

I have full permission rights on that folder, so not sure why this is occurring.  

Just in case, I installed VLC Player (64-bit version for my 64-bit PC), and selected that as the video engine in Options -> Settings -> Video Player, but that doesn't seem to help and the error message pops up still.

Any suggestions?  Thanks!

![image](https://user-images.githubusercontent.com/42707500/44624535-b80e5600-a8be-11e8-9c16-fa1b109cebc7.png)

**Comment by Zap19Ruder57** [comment]
Same problem here :-(
