### ISSUE TITLE
[Enhancement after the next version] For measurement converter.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3063]
Maybe Make it official instead of beta, and like "Find" when you open it, it takes the highlighted number.
Also, it would be useful to remember the last units you converted from and to, cause if you're working on a file with a lot of numbers, calculating the weight of something for example, it's hard to set the units every time and remember the window's position.

**Comment by OmrSi** [comment]
Like This:
![screenshot 392](https://user-images.githubusercontent.com/20923700/45591514-95230f00-b95d-11e8-944e-5700cb103d51.png)

**Comment by OmrSi** [comment]
@ivandrofly Maybe you could make it as a plugin?

**Comment by ivandrofly** [comment]
@niksedk can you please assign me to this just so I don't forgot, would also make it easier to find in issues later on :)

**Comment by darnn** [comment]
Does this exist currently? How can I get to it?

**Comment by OmrSi** [comment]
@darnn  There Exists a version of it...
![screenshot 696](https://user-images.githubusercontent.com/20923700/48672813-53703980-eb43-11e8-9d9c-b7a27a9ed2d6.png)

You have to activate beta stuff for the settings file:
`<ShowBetaStuff>True</ShowBetaStuff>`

Also, Unrelated, I found it useful to activate: `<ShowProgress>True</ShowProgress>` if you haven't already.

**Comment by darnn** [comment]
Oh, cool! What does ShowProgress do?

**Comment by darnn** [comment]
Ah, I see. Neat!

**Comment by OmrSi** [comment]
@ivandrofly Can you work on this one? :D

**Comment by ivandrofly** [comment]
> @ivandrofly Can you work on this one? :D

I'll take look at this maybe in two weeks or so...

**Comment by OmrSi** [comment]
@ivandrofly What about now? hehe

**Comment by ivandrofly** [comment]
> ShowProgress Shows you how much of the file is done.
> If you have an original file opened, it shows the percentage in relation to the original.
> Else, It shows the percentage in relation to the video's time.

What result are you expecting? 😕

**Comment by OmrSi** [comment]
@ivandrofly I'm not expecting any other result. ^^"
He was just asking what it does.
