### ISSUE TITLE
[Bug] Using waveform's "Split line" doesn't always remove dashes (test file attached)

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3065]
Here is a test file, just try using Waveform's split:
[Skyscraper 2018.zip](https://github.com/SubtitleEdit/subtitleedit/files/2322070/Skyscraper.2018.zip)

**Comment by OmrSi** [comment]
@niksedk Thank you. Beta after this?

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip
