### ISSUE TITLE
[Bug] Apply in Multiple replace

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3068]
When you click apply then ok, it shows "Number of lines with text replaced: 0"
Even if some lines were replaced.

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk Just tested, it if there even if you apply one of the changes on the list, it shows the number of all available changes, not the ones that were applied.
![screenshot 345](https://user-images.githubusercontent.com/20923700/45034993-92711180-b061-11e8-86fd-3850805d587e.png)
![screenshot 346](https://user-images.githubusercontent.com/20923700/45035012-9d2ba680-b061-11e8-92a8-311eeff60b52.png)
