### ISSUE TITLE
[Bug] Dark theme won't go away

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3070]
I went to test the dark theme, saw that it still has some problems, went back to normal, but it won't go back completely.
![screenshot 324](https://user-images.githubusercontent.com/20923700/44858348-73960800-ac7a-11e8-8de7-a6b81ad92ab1.png)

**Comment by OmrSi** [comment]
I changed them from the settings, but they should go back on their own.

**Comment by diomed** [comment]
so it's true what they say. once you go black, you never go back. 😄

**Comment by darnn** [comment]
Hey, not to be a downer, but that joke is inappropriate. Please don't.
