### ISSUE TITLE
[Question] What is "Border marker hit"?

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3071]
I've noticed it but couldn't figure out what it is.
Not an issue, can be closed as soon as answered :D
![screenshot 325](https://user-images.githubusercontent.com/20923700/44870800-c7fcb000-ac99-11e8-9297-87101d90f677.png)

**Comment by niksedk** [comment]
It's how close the mouse needs to be to a waveform start border to go to "move start time mode" (instead of moving the whole subtitle line). A larger value will make the mouse go into "border mode" sooner/easier.
Did I explain it okay?

**Comment by aaaxx** [comment]
It's called snapping in other software. So something like "Snap mouse to subtitle border within ## ms" would be more obvious.

**Comment by OmrSi** [comment]
@niksedk Got it. Although what @aaaxx said was clearer. 😅
Maybe it would be better to write what he said.

Another question, wasn't the Beta file smaller? I noticed it went from 7 to 10 MB, not a big deal, just wondering. 
Maybe I'm mistaken.
