### ISSUE TITLE
[Bug] First line added in a file doesn't take Subtitle Minimum Display.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3075]
![screenshot 333](https://user-images.githubusercontent.com/20923700/44950593-2c636f00-ae54-11e8-8ef6-ba795e30c1be.png)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Hmm, still getting 2 sec while I've changed it to 0.833...
![screenshot 788](https://user-images.githubusercontent.com/20923700/49824337-8a282100-fd8a-11e8-8f62-3536a4e8d5fa.png)

**Comment by OmrSi** [comment]
@niksedk Oh, I think you fixed the one added with the creat shortcut.
Using Insert with the mouse from the list or the insert shortcut still has the problem.
