### ISSUE TITLE
[Bug] overlap when using "Move end 100 ms forward" or "Move selected 100 ms" with more than one line

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3082]
You tried fixing it here https://github.com/SubtitleEdit/subtitleedit/commit/69e0186aa175e14af0dceb8a6a56611e7895c7e1 but seems that it didn't work, or something happened after it.

**Comment by niksedk** [comment]
Works fine here...

**Comment by OmrSi** [comment]
@niksedk 
Oh, I mean "Move end 100 ms forward"
![screenshot 354](https://user-images.githubusercontent.com/20923700/45110161-2ae2c100-b14a-11e8-904a-0851ce41fcc9.png)

**Comment by OmrSi** [comment]
@niksedk  Well, I checked all of them.
When you select more the one line and use "Move selected a 100 ms back/forward" with more than one line, it allows overlap with next or previous.

When using "Move END 100 ms forward" it allows overlap with next.

**Comment by OmrSi** [comment]
@niksedk Yep, Move end 100 ms works now. Thnx.
But moving more the one line 100 ms forward/back still overlaps.
If you see it's not an important thing, just close it. :)
