### ISSUE TITLE
Video player skips to time of first subtitle in file on drag+dropping subtitle into SE

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3084]
3.5.6 build 433.
To reproduce:
1. Close SE without a video or subtitle file open and then run it again.
2. Drag and drop an ELR Studio print format file into SE (this might also work with other formats, I haven't tried).
3. Drag and drop a video file into SE.
4. Save the subtitle as an SRT file.
5. Find the SRT file that was just saved in Explorer and drag and drop it into SE while holding down shift, so that the subtitle opens but the video file also stays open.

In this situation, for me, the video file skips to the time of the first subtitle in the file.

**Comment by OmrSi** [comment]
I don't see the problem. 
If you're using subtitle edit, you want to edit subtitles, why wouldn't it go to the first line's timing?

**Comment by darnn** [comment]
It's not necessarily a problem, but it happens only under certain circumstances. I think it should either be uniform and optional, or not happen at all.
I usually have files where all my subtitles aren't timed (00:00:00:00 or 02:00:00:00), or have the automatic timing from "import plain text", so skipping to the first subtitle isn't desired. And even when I have files that have proper timecodes, I have to watch the entirety of the video in case I need to insert subtitles with, like, text from signs, or the title of the show, or something.

**Comment by OmrSi** [comment]
Dragging used to cause a lot of problems, we worked on them here https://github.com/SubtitleEdit/subtitleedit/issues/3047 as a result, dragging goes to the first subtitle or the one you selected before closing the program.

**Comment by darnn** [comment]
That's probably why... Anyway, it's not a very high priority thing, just thought I'd point it out since I keep encountering it.
