### ISSUE TITLE
[Big Bug] Can't choose size or any setting from "Font name".

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3088]
When you want to change the font name and size from the drop menu, only the font name is changed, size isn't.

**Comment by diomed** [comment]
I have no problems with this, 
but I would like if we could change font in text field, so it would not be the same as general

**Comment by OmrSi** [comment]
You have no problems as in the problem doesn't happen of as in you don't care that it happens?
![screenshot 366](https://user-images.githubusercontent.com/20923700/45266908-7ad3c780-b46b-11e8-8a2b-3695dc5bd91b.png)
![screenshot 367](https://user-images.githubusercontent.com/20923700/45266910-81fad580-b46b-11e8-82a8-4e9c80fb6ade.png)
P.S: it's the same with a friend of mine.

**Comment by diomed** [comment]
sorry, I meant something else. [changing font size via settings]
this surely is an isuse.

**Comment by OmrSi** [comment]
@niksedk  I think this is a very important one, many people I know have been having problems with this, I had to point them to Regex.

**Comment by OmrSi** [comment]
@niksedk  I think this is a very important one, many people I know have been having problems with this, I had to point them to Regex.

**Comment by niksedk** [comment]
Actually it's only meant to use the font name. It was just easy to get via the "standard windows font dialog" which shows a lot of stuff not used by SE. I see that perhaps I should create a custom "font name" dialog from scratch.

@OmrSi: No font size support atm in SE...

**Comment by OmrSi** [comment]
@niksedk  Yeah, you probably should. Some people don't know what tag is added when you select the size, and they assume the size is changed and when they see it isn't they think the program has a problem or that they are doing something wrong.

That's what happened with at least 2 people I know...
