### ISSUE TITLE
How to import the old version OCR image database to the latest version?

### ISSUE THREAD

**Issue by Araynilmar** [SubtitleEdit/subtitleedit#3091]
I've a lot of Chinese OCR image database by SubtitleEdit v3.4.4, but can't import or use to SubtitleEdit 3.5+.

How to import, exchange or upgrade the old version OCR image database to the latest version?

**Comment by niksedk** [comment]
Sorry, that's not possible as the "binary OCR" uses more info than available in the old "image compare".
