### ISSUE TITLE
Google translate issue

### ISSUE THREAD

**Issue by ghost** [SubtitleEdit/subtitleedit#3093]
There is a strange issue related to Google translate. It works fine but I decided to change all projects in the solution to use Framework 4.7.2 instead of framework 4. Now, when I use Google translate window and click the translate button, the mouse pointer movement become too heavy, slow, jumby, and irregular, not only over the translation window, but also anywhere else! The keyboard works fine, and I type on Word normally. The task manager shows that CPU and RAM usage are normal! The problem affects the mouse only (a USB mouse).
When I fall back to use Framework 4 client profile, every thing works fine again!
I am using a PC with windows 7. I retested on a fresh win 7 on a laptop, and got the same results!
Have you any idea why this is happing?
Is there any thing wrong with v4.7.2 ?
Is there anything wrong with windows 7?
Is the problem caused by the Application.DoEvents or by the WebRequest?
can you retest this on win 7, 8 and 10?

**Comment by OmrSi** [comment]
@niksedk Weren't there some changes related to .NET?
