### ISSUE TITLE
Where is "select all on mouse enter" for text box in code?

### ISSUE THREAD

**Issue by buggalicious** [SubtitleEdit/subtitleedit#3097]
As a user, it is driving me nuts that all text is automatically selected when I enter the textbox when new text has been loaded. I often just want to change one or a few words, but now my first click in the textbox selects all text so I have to click again or twice, if I held down the mouse button a little too long, before I can make the actual selection of my choice with a third click. And it gets messier in other situations. So I want to turn this behavior off, but I can't find it in the code.
Any pointers will be greatly appreciated.

**Comment by niksedk** [comment]
It's only there in "translation mode"...

**Comment by buggalicious** [comment]
Thanks for the reply. If you're referring to the three tabs "Translate, Create, Adjust", I exclusively work with the "Adjust" tab active. I believe this behavior that I describe was only introduced with a 3.5.6 beta.

**Comment by buggalicious** [comment]
Okay, Translator Mode, when two files are open. No, I only have one file open, no "original subtitle".
When I first start Subtitle Edit and play back a project and the first subtitle is loaded, I can enter the textbox okay, but as soon as that text is overwritten by another subtitle,  clicking into the textbox will select all that text.

**Comment by buggalicious** [comment]
> It's only there in "translation mode"...<
If it's supposed to be only in translator mode, then it's a bug, because my Subtitle Edit is not in translator mode.

**Comment by buggalicious** [comment]
Can't I please know where in the code this setting is made?

**Comment by OmrSi** [comment]
How do you enter the box? Mouse or focus shortcut?
