### ISSUE TITLE
How to get or export the scence change time code

### ISSUE THREAD

**Issue by Araynilmar** [SubtitleEdit/subtitleedit#3098]
As described in the title, the Generate/import scene changes function is usually used to get the time code, And then it could be used to quickly compare, check or modify the video Chapters Info.

However, after the Generate/import scene changes function is completed, the time code list won't remain and display in the textbox of this form.

Is there any tricks to get these time codes? Or in the future there will be an interface that can keep displaying the time code information?

**Comment by OmrSi** [comment]
You can find the file in the scenechanges folder. 
Just open it as txt and copy the time codes.

**Comment by Araynilmar** [comment]
> You can find the file in the scenechanges folder.
> Just open it as txt and copy the time codes.

Got it, Thx.

**Comment by OmrSi** [comment]
Closed.
