### ISSUE TITLE
Subtitle Edit-------Tesseract problem ?

### ISSUE THREAD

**Issue by Aliage** [SubtitleEdit/subtitleedit#3100]
Hello everybody, I hope you doing well

As far as I'm concerned, I just met a little problem with Subtitle Edit 3.4.10, I explain.... I have a VobSub subtitle **(Arabic sub file)** & I want to change it **(to add a few lines)** so it sticks with my **DC movie**. So when I try to start OCR I receive an error msg **((Unable to start 'Tesseract'- make sure tesseract-ocr 3.x is installed!))**

<a href="http://zupimages.net/viewer.php?id=18/37/oshy.png"><img src="https://zupimages.net/up/18/37/oshy.png" alt="" /></a>

What can I do to solve this problem, to display the sentences of the .sub file so I can change them?

Thank you

**Comment by OmrSi** [comment]
First of all, are you using an old version? The one in the picture seems to be missing some features.
Download and install the last version, then do it like the pic:
![screenshot 385](https://user-images.githubusercontent.com/20923700/45546333-a7019680-b825-11e8-920e-0d74ffddd655.png)

**Comment by marb99** [comment]
the last version is 3.5.7, each new version are fixed many bugs when you post about a bug should be in the last version otherwise you post about a bug that may have already been fixed in the latest version.

Nobody care if someone have bugs in previous versions, download the latest version and if the bug is present post the bug.

**Comment by niksedk** [comment]
You can also try latest beta (especially if you have a 32-bit os): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by Aliage** [comment]
Hi,

Sorry for being away so long....
My current version is 3.4.10, I will change it, and and I'll let you know..............................I hope I'm not going to have the same problem.

Thank you guy's.
