### ISSUE TITLE
Requests & Issues regarding OCR

### ISSUE THREAD

**Issue by vertigo220** [SubtitleEdit/subtitleedit#3104]
I just converted the four subtitle tracks from Crouching Tiger, Hidden Dragon, to .srt files, and it gave me a good bit of insight into the strengths and weaknesses of SubtitleEdit's features and capabilities in that area. This was an especially interesting movie to do because of all the foreign names. I apologize if some of these are due to user-error, I'm still learning how to use the program.

1. I'd really like the ability to save progress while doing OCR. It can take quite a while, and I always feel the need to do it in one sitting in case I spend a lot of time on it and don't finish then the computer resets or crashes or something else happens. Also, maybe this could be used to build a database of sorts to see what common issues the OCR has. For example, one of the ones I saw a lot was with a word ending in "o" having that "o" be changed to a ")" but I don't remember the exact case and didn't bother to take note of it, because I thought those issues were unrelated to SubtitleEdit, but based on other issues I'm now thinking you can maybe fix them. Having a saved database of changes would help to report them.
2. It needs the ability to add custom words to the name/noise list and dictionary during the OCR scan. I'll provide a couple examples from this movie. First, it would flag kung and/or fu (sometimes one, sometimes the other, sometimes both), and I'd just ignore them once, meaning I'd have to keep doing so, because I didn't want to add them individually to the name list or dictionary, in case maybe there was an instance were "to" was changed to "fu" for example. But it doesn't provide an option to add custom words. If I could add "kung fu" then it would skip all other instances and I wouldn't risk it causing a problem elsewhere. Another example is with names, like Bai. It would flag "Bai's" and I could add that, but I'd like to be able to add "Bai" so it would skip both (at least, I assume it would skip "Bai's" since it would "know" the word Bai and see that Bai's is the possessive form of the same word. There are, of course, other examples, but these should give the main idea.
3. One common issue I found it has, and probably where I spent the most time, was that sometimes it would add a space after a hyphen at the beginning of a line and sometimes it wouldn't. So I went through all the corrections and added a space manually where it didn't. After a while, to speed things up, I started skipping ones where the line started with a parenthesis ("-(") because that's easy enough to do with find/replace all at once. But other lines can't be done that way. Even if I did a double find/replace (first replace all "-" with "- " then replace all "-  " (double space) with "- " (the second one would be necessary to fix the ones that already had the space and had another added), it would affect words in the middle of sentences, like "one-half," which would turn into "one- half." There are complicated ways around all this with regex find/replace, but I was thinking SubtitleEdit could have an option to do this automatically. This alone would probably have cut the time it took to do these in half.
4. Another common issue I found, and one that also took a fair amount of time, though not nearly as much, was that it isn't very good at determining italics. If a line has italicized text, more often than not (probably >80% of the time) it would either put one or both tags in the wrong place or randomly throw one or more sets of tags in the line (e.g. "This line has _italicized text_" would become "_This line has italicized text_" or "This _line_ has _italicized text_" or "This _line has_ italicized _text_" and so on). And some lines with _no_ italicized text would be tagged.
5. It could really use an option to display the graphics from the original subtitle next to the OCR results (or somewhere in the window) when on the main screen. In other words, just like you see the graphics for comparison when doing the OCR, so you can see what the original says to help in making corrections, it would be nice to see that for the selected line in the main window. The reason I could have used that was when going through fixing all the italics errors, since I searched for \<i> and fixed each line, but I had to play the video and jump around in it to see where the italics actually were in the original if I couldn't tell. But it would also help for doing a spell-check or just looking at questionable lines.
6. This one is an actual (maybe) bug, and so probably should be its own issue, but I'll put it here for now. AFAICT, items added to the names/noise list and the dictionary should be recognized from that point on and not flagged. Even the help says they're remembered for "future works." I don't know about the dictionary, since the vast majority of the unrecognized words were names and so I added them to that list, but even though I added them, I had to keep doing so every time I did a different subtitle file. And I checked the files in the dictionary folder, and the items I added are there, so it's not an issue of adding them.

**Comment by niksedk** [comment]
thx for the input - a bit long for a single issue...

What version of SE are you using?

I think most of the features you describe are already there... at least in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

try to right click in the list view which will give you save/load capabilities + a html view of graphics + ocr'ed text - like 1 + 5.

2 should already exist.

3 a sample file would be nice to look more closely at it.

6 should also work...

**Comment by vertigo220** [comment]
Yeah, sorry for the length. I figured I'd do it that way instead of spamming a bunch of separate issues, and then hopefully only a couple would need to be broken out into separate ones, especially since it mostly deals with OCR. Anyways, I'm not sure we're on the same page, because you say the stuff is there but I'm not seeing it. I'll try to clarify a bit.

1) What I'm referring to here is not the ability to save the subtitle file, but rather to save the OCR progress so far as a project file. So if I drag a file into SubtitleEdit (SE) and it opens it in the Import/OCR window, I can spend several minutes going through letting it scan and fixing the errors and, instead of having to either finish it in one sitting or leave it sitting unfinished, it would be ideal if it could save it to a SE project file that, when loaded later, would open up the original subtitle (the one opened in SE for import) and load all the OCR progress and fixes done so far. As it is, there isn't any such functionality that I can see, and you mentioned right-clicking in the list view, which a part of the main screen (and I also don't see any save/load options there, either, so I'm not sure what exactly you're referring to).

2) If it already exists, it's unclear on how to do so. For example, if a sentence includes "kung fu" and it pops up asking about kung, I see no way to add "kung fu" to the dictionary or name list. I can change the text in the box from "kung" to "kung fu" but then it would replace it as such, leading to "kung fu fu."

3) Sample file attached: [Sample Subtitle.zip](https://github.com/SubtitleEdit/subtitleedit/files/2408274/Sample.Subtitle.zip)

4) Sample file covers this one as well.

5) Again, I'm not seeing what you're referring to by right-clicking in the list view. I don't see any option to see the graphics, html or otherwise. Here's an example of what I mean: 
![se example](https://user-images.githubusercontent.com/12024557/45922970-ff303c80-bea6-11e8-93b3-40969e773995.png)

6) Unfortunately, what _should_ work and what _does_ appear to be two different things, because in my case it doesn't. If I can provide any logs or anything to help figure out why, please let me know.

7) And a couple new issues: the new version is _very_ slow when doing OCR (it's always been slower than it seems it should be, but it's taking several seconds just to do ~20 lines. Also, I'm getting a lot of line breaks in the middle of lines with the new version.

**Comment by niksedk** [comment]
2: You can do that in several ways, just changing the word in the popup and then click "Add to user dictionary":
![image](https://user-images.githubusercontent.com/1261331/45924654-b8bdfa80-bf05-11e8-8395-ec8062b28cf5.png)

Or in the ocr window:
![image](https://user-images.githubusercontent.com/1261331/45924660-f1f66a80-bf05-11e8-8e74-899bb98d5491.png)


5: Try this:
![image](https://user-images.githubusercontent.com/1261331/45924675-5adde280-bf06-11e8-9976-c6e191113f4e.png)


7: Yes, SE 3.5.7 switched to Tesseract 4 Beta from Tesseract 3.02 - I should probably not have done this as T4 seems to have problems with breaks as you have seen (+ slower and ignore italics).

**Comment by vertigo220** [comment]
2. The problem is it only works to add the word as is, but not to take a flagged word that you want to add _as part of_ a combination of words. For example:

![se 1](https://user-images.githubusercontent.com/12024557/45932528-5ab40600-bf4b-11e8-80a5-5c1bc1732946.png)
![se 2](https://user-images.githubusercontent.com/12024557/45932532-61427d80-bf4b-11e8-8e20-bf98127ec5ee.png)

In this case, I wouldn't want to add "Pei's." If I wanted to add "Pei" I couldn't, because it would change the sentence to read "...Gou Jun Pei brother." And I also can't add "Gou Jun Pei" which I would prefer, because it would change it to read "...Gou Jun Gou Jun Pei brother." So what I'm saying is there should be the ability to, at any time, add anything you want, so when that comes up, I could click a button to add a custom string to one of the lists, add "Gou Jun Pei," and then it would ignore all occurrences of that, but if it finds just "Pei" or "Pei's" those would still be flagged. There's no way, either during the OCR or when checking the results after, to do this, and it should be an option at both times, but _especially_ during the OCR, so it won't keep stopping every time it hits that name. And as I said before, it would be ideal if you could add "Pei" and have it skip all instances of that and "Pei's" though I'm not sure if that's possible or not.

5. That kind of works, and would probably be a _little_ easier than jumping around in the video, but it still requires a) remembering to save it before finalizing the OCR results, b) switching back and forth between SE and the browser, and c) manually jumping around the created web page to each graphic, which even with Ctrl+F is still a good bit more effort than if the graphics were simply automatically preserved and displayed in SE when you select the corresponding lines in the list view, as per my screenshot above. Basically, this would require auto-saving the images as above and adding a frame in the main SE window that displays the image with the same time index as the selected line, then (preferably) automatically deleting the saved images when done.
