### ISSUE TITLE
Imported sup is very small on the OCR screen

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#3107]
I have several sup files in which the actual subtitle area seems to be very small when SE tries to OCR it. This makes it very hard to OCR and there are a lot of errors to correct. If I open the subtitle in BD2Sup2Sub++, the subtitles look normal.

![image](https://user-images.githubusercontent.com/11799308/45604561-3d100980-ba3e-11e8-974c-bbec74734437.png)

[poirot.zip](https://github.com/SubtitleEdit/subtitleedit/files/2387293/poirot.zip)

**Comment by niksedk** [comment]
I guess that because the subtitle is actually that big... In latest version I've tried to add some "Image pre-processing" - try to right-click in the list view and choose "Image preprocessing..." and check "crop transparent colors".

**Comment by Boulder08** [comment]
The subtitle itself looks bigger (already does when opening the sub) but OCR is as difficult. But I guess that if the original size doesn't change, that's also not going to change for any better. It's much easier to see the complete subtitles now though, so that's an improvement.
