### ISSUE TITLE
A small improvement to "Fix first letter to uppercase"

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#3109]
In this case, subtitle line 545 should not begin with an uppercase character. A similar structure to "--" is often "-", ".." or "..." right next to or with one whitespace after the last character of the previous subtitle line.

`544
00:35:00,501 --> 00:35:02,834
He wasn't tall --
well, no taller nor me --

545
00:35:03,042 --> 00:35:04,292
and he wore a 'tache.`

**Comment by OmrSi** [comment]
Also a duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/360
