### ISSUE TITLE
Hashtag issues `#foo`

### ISSUE THREAD

**Issue by XhmikosR** [SubtitleEdit/subtitleedit#311]
Not sure if there's a foolproof way to detect this. I mean, tags do not have a space after the hashtag and they don't have an end hashtag.

```
"I'm at the gym. #gymflow."
```

Also

```
"Oh, I'm standing near a baby.
#babyflow, #circleoflife, #blessed."
```

This doesn't need to start with uppercase.

/CC @niksedk

**Comment by OmrSi** [comment]
@niksedk Also closed?
![screenshot 165](https://user-images.githubusercontent.com/20923700/52165518-9a190d00-270a-11e9-99ee-7e6919a3bfd6.png)
![screenshot 166](https://user-images.githubusercontent.com/20923700/52165521-a309de80-270a-11e9-8c61-d10f12666c56.png)
