### ISSUE TITLE
Improvement: Add "Delete line" button in Spell Check window

### ISSUE THREAD

**Issue by Yomodo** [SubtitleEdit/subtitleedit#3113]
Often there's text I don't want in the subtitles ,so while doing a spell check,
I have to abort it, delete the line from the main window and continue the spell check.

A button inside the spell check window: "Delete line", would be convenient.

**Comment by Yomodo** [comment]
Hi, any idead when this feature will be released?
I was hoping this would be available in v.3.5.8

**Comment by niksedk** [comment]
It's available in the text context menu:
![image](https://user-images.githubusercontent.com/1261331/50526869-1f464c00-0ae5-11e9-8215-2f723331d5b1.png)

**Comment by niksedk** [comment]
Perhaps it should say "Delete current line"....

**Comment by Yomodo** [comment]
Ah, found it, thank you!

I think it would be a bit more convenient if it says: "Delete current line" **and**
deletes the line immediately when selected/clicked, instead of opening another confirmation box.

**Comment by darnn** [comment]
I don't know if this applies to spell check, but you should uncheck "prompt for delete lines" in settings->general.

**Comment by niksedk** [comment]
@darnn: yes, it should work like that... now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip :)
