### ISSUE TITLE
"Continue Find?" window does not respond to [ESC] key.

### ISSUE THREAD

**Issue by Yomodo** [SubtitleEdit/subtitleedit#3114]
Normally one can press the [ESC] key to dismiss pop-ups.

It doesn't seem to work for the "Continue Find?" window.

**Comment by niksedk** [comment]
Should be fixed in latest beta of SE: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
