### ISSUE TITLE
Problem entering č

### ISSUE THREAD

**Issue by rl1234567890** [SubtitleEdit/subtitleedit#3117]
I noticed that when I enter the letter č  in  "Word not found" at the end of a word, the letter does not show up. It is actually there though and it appears in  "Subtitle text". No problem if the letter č is within the word being edited. 
I am using 3.5.7 with mono, Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

Thanks!

**Comment by niksedk** [comment]
Could you show a screenshot?
What version of SE are you using?

**Comment by rl1234567890** [comment]
I downloaded SE357.zip and run it with mono. Better than a screenshot. I have a movie:

https://youtu.be/kKbN4lQyQ6o

I first type č within a word. Then I try to append it.  It does not appear, but it's there when I select it with the cursor.

**Comment by niksedk** [comment]
thx for the video :)
I don't really know why this is happening. Could you try some some different fonts? See options -> settings.

**Comment by rl1234567890** [comment]
It doesn't make any difference. Maybe it is a Linux problem.
