### ISSUE TITLE
OCR error running SubtitleEdit-3.5.7

### ISSUE THREAD

**Issue by x1761** [SubtitleEdit/subtitleedit#3118]
I installed the very latest SubtitleEdit-3.5.7 (setup version). When I launch the program, it runs OK, but when I 'Start OCR', I get an error: "The program can't start because VCRUNTIME140.dll is missing from your computer. Try reinstalling the program to fix this problem". Previous version 3.3.6 runs fine. Please advise. Win 7 x64.

**Comment by niksedk** [comment]
You probably need Microsoft Visual C++ 2017 Redistributable: https://aka.ms/vs/15/release/VC_redist.x86.exe

Next version will go back to defalt include Tesseract 3.02 again (and Tesseract 4 as an optional download) - do test the beta here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by cdgriffith** [comment]
Nothing seems to be working for me at least, hitting start OCR does nothing still: 

Downloaded above redist.x86
Restarted 
Tried 3.5.7, didn't work

Downloaded redist x.64 version, repeated, still didn't work. 

Downloaded 3.5.7 Beta, unzipped, tried both Tesseract 3.0.2 and 4Beta, did not work.  (I did download and select languages)

Is there a way to enable debug logging or something? I took a quick glance through the settings but didn't find anything.

Thanks for looking into it!

**Comment by niksedk** [comment]
@cdgriffith: Where did you unpack the beta to? Must be something like C:\Tools\SE and not a sub directory to "Program files".

**Comment by cdgriffith** [comment]
Directly on my desktop, for the non beta I used the installer.

**Comment by p1nkyy** [comment]
Error when trying to play video/audio from x265 movies. I figured it out after trying out several times then I extracted the audio from the movie, now works fine. Dunno with the video though...

**Comment by marb99** [comment]
@niksedk 

I think it's better to release the 3.5.7.1 or something soon to go back to Tesseract 3.0.2 because a lot of people have had a problems with Tesseract 4 and return to 3.5.6.

**Comment by niksedk** [comment]
@cdgriffith: try going cmd line and running something like `tesseract input.png output -l eng`

@p1nkyy: Try installing lav filters or switch video player to `mpv

@marb99: Yes, but for some languages it's better... 3.02 will be included instead of 4 in next update of SE :)

**Comment by cdgriffith** [comment]
Those both work on the command line fine for me it seems. 

Attaching video of issue I see (and showing the commands working from cmd line) 
[my issue.zip](https://github.com/SubtitleEdit/subtitleedit/files/2420245/my.issue.zip)

**Comment by p1nkyy** [comment]
That solved it, thanks!
Another problem is if I run SE too long while doing it with waveform open too long, it will eventually crash.

**Comment by niksedk** [comment]
@cdgriffith: Could you try latest beta of SE: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
If you press F8 in the ocr window the current text will show the log. Better now? If no, please attach the log.

@p1nkyy: I've left the waveform open for a few days but no crashes - how can I re-create this?
