### ISSUE TITLE
Missing titles from Bluray PGS file

### ISSUE THREAD

**Issue by ManChicken1911** [SubtitleEdit/subtitleedit#3119]
Ran into something for the first time (that I'm aware of) trying to convert the subtitles from A Quiet Place. I'm using an .mks file to start (I always demux them with mkvtools) but it's missing several titles throughout when I drag it in and click through them in the Import OCR window (and just to be clear, this isn't an OCR problem specifically, the titles are missing even before starting the OCR process.)

The curious thing about the titles I've found missing in this case is that they are all part of a "build" which I haven't really seen done before; That is, the finished title is one line of text, but it's is split into many titles to make it appear one word at a time with the start and end times butting up against each other. You can see an exact example from this movie at https://youtu.be/Ku_jmqHIuFU?t=3m56s (**POTENTIAL SPOILER ALERT!**) In that exact scene, the OCR Import window only sees the first three titles ("I have always") and the last two are simply missing. Earlier in the movie the same kind of thing occurs where there's a triplet of subtitles that ultimately say "S.O.S." but the import window only shows the first two, "S." and "S.O." -- It happens twice in a row, with the last complete title "S.O.S." not showing up at all either times.

Happens in 3.5.6 and 3.5.7 (which I was initially running but downgraded back to 3.5.6 just to test.)

If you'd like to see the original subtitle file let me know and I can send it privately.

**Comment by niksedk** [comment]
Sounds interesting - please do email the subtitle.

**Comment by darnn** [comment]
Weird, I downloaded the movie and the MKV contained a SUP file that doesn't have these problems. After OCR the relevant part looked like this: 
`14`
`00:12:36,088 --> 00:12:36,922`
`S.`

`15`
`00:12:36,922 --> 00:12:37,714`
`S.O.`

`16`
`00:12:37,714 --> 00:12:38,340`
`S.O.S.`

`17`
`00:12:38,924 --> 00:12:39,925`
`S.`

`18`
`00:12:39,925 --> 00:12:40,634`
`S.O.`

`19`
`00:12:40,634 --> 00:12:41,260`
`S.O.S.`

**Comment by ManChicken1911** [comment]
I messed with this a little bit more tonight and I think perhaps this is a parsing error in SE when the titles are wrapped in a mks.

If I take the .mks and run it through mkvextract to pop the titles back out into a .sup, the resulting file shows all the missing titles in SE... so they are present in the mks-wrapped version but are somehow skipped by SE when dropped in as such.

**Comment by niksedk** [comment]
Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?

It seems like the mks entry "S.O.S" has no palette... now SE will re-use last palette if no new palette is found, but it's a guess/hack... 

Here's how a "normal" image looks like and what a "image-witout-palette" looks like:

    "S.O."
    0: 0x16 - Picture codes, offset = 3 size=19
    CompNum: 26
    ObjId: 1, WinId: 0, Forced: True, X: 880, Y: 798
    1: 0x17 - Window display offset=25 size=10
    WinId: 0, X: 880, Y: 798, Width: 159, Height: 42
    2: 0x14 - Palette - PDS offset = 38 size=152
    PalId: 0, update: 1, 30 entries
    3: 0x15 - Bitmap data - ODS offset = 193 size=1635
    ObjId: 1, ver: 0, seq: first/last, width: 105, height: 42
    4: 0x80 - END offset = 1831 size=0

    "S.O.S"
    0: 0x16 - Picture codes, offset = 3 size=19
    CompNum: 27
    ObjId: 2, WinId: 0, Forced: True, X: 880, Y: 798
    1: 0x17 - Window display offset=25 size=10
    WinId: 0, X: 880, Y: 798, Width: 159, Height: 42
    2: 0x15 - Bitmap data - ODS offset = 38 size=2303
    ObjId: 2, ver: 0, seq: first/last, width: 159, height: 42
    3: 0x80 - END offset = 2344 size=0

**Comment by ManChicken1911** [comment]
Hmm interesting!

I grabbed that beta and tested it, and yes it seemed to pick up all the subs from the .mks properly.
