### ISSUE TITLE
Microsoft Bing Translator - We are sorry, the page you requested cannot be found

### ISSUE THREAD

**Issue by Sopor-** [SubtitleEdit/subtitleedit#3121]
In the `Settings / Tools / Microsoft Bing Translator` you have added a [How to sign up](https://www.microsoft.com/en-us/translator/getstarted.aspx) but this page will only show this text `We are sorry, the page you requested cannot be found.`

Subtitle Edit 3.5.7

**Comment by niksedk** [comment]
thx for the info - SE now also uses the V3 of the api.
Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
