### ISSUE TITLE
 GoogleTranslateUrl  issue

### ISSUE THREAD

**Issue by eaglepie** [SubtitleEdit/subtitleedit#3122]
this software is very useful for us(non-English speaking country)。But unlike other countries, we don't have access to https://translate.google.com，but we only can access to https://translate.google.cn。I mean, could we set the URL of Google Translate in the software's setting?

The default GoogleTranslateUrl = "translate.google.com";

But we can set the address of this Google Translate to "translate.google.cn"
GoogleTranslateUrl = "translate.google.cn";

And then we can make good use of this software, Thanks to the hard work of the author.

**Comment by OmrSi** [comment]
This problem has already been addressed, you can change it from Settings -> Tools:
![screenshot 437](https://user-images.githubusercontent.com/20923700/46245360-23cf6b80-c3f5-11e8-9cbb-80df527aa7b3.png)

**Comment by eaglepie** [comment]
thank you very much. Great work!

**Comment by OmrSi** [comment]
All thanks to @niksedk I'm just a user like you. :)
Maybe you can close this now. :D
