### ISSUE TITLE
can't export report file for comparison between two subtitles

### ISSUE THREAD

**Issue by billysamk** [SubtitleEdit/subtitleedit#3126]
Trying to export the result to an excel sheet or even a csv format(any file would do) of comparison between two subtitles, gives the following error on windows 10
the save as file type shows Html files only, there is no option to change the file extension, no matter what extension I try to put or whatever name I try to enter, I am greeted by this little error every time.
![compare](https://user-images.githubusercontent.com/11823561/46388784-e23c0a80-c6eb-11e8-9b18-4a4b88a8b300.png)

**Comment by niksedk** [comment]
thx for the info :)
Should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
