### ISSUE TITLE
[REQUEST] Option for translate shortcuts edit

### ISSUE THREAD

**Issue by Hassan444** [SubtitleEdit/subtitleedit#3127]
I want to change the shortcut for this function but can't seem to find in settings.
![image](https://user-images.githubusercontent.com/36653771/46545105-b2485f00-c8c5-11e8-81b9-86caab763f05.png)
Because auto-repeat function only works with it, and doesn't work with (go to next line) in shortcuts in settings and also it doesn't select all text in the textbox automatically
Thanks in advance

**Comment by OmrSi** [comment]
+1

**Comment by niksedk** [comment]
Check Options - Settings - Shortcuts
