### ISSUE TITLE
3 issues with Netflix QC.

### ISSUE THREAD

**Issue by billysamk** [SubtitleEdit/subtitleedit#3129]
**_1st Issue_**
Single line length > 42
This has been popping up for subtitles that have html tags for italics, or the alignment tags, even though they haven't exceeded the limit. they are being counted along with the characters.

**_2nd Issue._**
Fixed italics
What I write in my list view dialog box
```
<i>three passengers have died at the spot,
in an accident.</i>

what I get when I reopen the file after closing the app

<i>three passengers have died at the spot,</i>
<i>in an accident.</i>
```

Extra tags are getting added in the file, the format that I am using and working on is dfxp format.
These were fine in some previous version of the program, but it has been broken since last few updates.

**_3rd Issue_**
Even after setting the Maximum character per second limit from the 
Settings-General tab
Max. chars/sec to a value above 17. (For eg I set 20 which is the CPS limit for English, 17 CPS is for kids programs and for certain documentaries it's 22, sometimes other values specified by the clients. I choose 25 fps videos)

the Netflix error report shows,
**Maximum 17 characters per second**
error for them where ideally it should only generate for those events where the value has exceeded the user specified value from the input textbox, i.e. in my case 20 CPS

I checked the NetflixQualityController.cs file

```
  public int CharactersPerSecond
        {
            get
            {
                if (!string.IsNullOrEmpty(Language))
                {
                    if (Language == "ar") // Arabic
                    {
                        return 20;
                    }
                    if (Language == "ko") // Korean
                    {
                        return 12;
                    }
                    if (Language == "zh") // Chinese
                    {
                        return 9;
                    }
                }
                return 17;                       // Possible culprit
            }
        }
```

Maybe this is the reason it's showing. I have a very basic understanding of programming languages, Just shared this code, for a bit of learning.

Also I feel it would be better if it takes and return values from users input textbox directly, since all users have different guidelines and being an open source program it would greatly help for reviewers for other projects other than netflix. Thanks for this great project!

**Comment by billysamk** [comment]
![isse](https://user-images.githubusercontent.com/11823561/46574934-75fe2700-c9c9-11e8-9bac-b820ed0da462.png)


I am sure this didn't happen either in previous version. it's highlighting error at 20.00 Char/sec. where it should show error at 20.01 Char/sec.

I am using the latest beta version 3.5.7, Maybe that is why.

**Comment by OmrSi** [comment]
@niksedk Closed?
