### ISSUE TITLE
DeepL plugin v0,92 "too many request" 

### ISSUE THREAD

**Issue by diese31diese** [SubtitleEdit/subtitleedit#3130]
Hi, 

the v0.92 deepl plugin from July worked perfectly until today. The plugin sends again a message "too many requests" :-(
Any solution ?? or just waiting ??

 Thanks in advance

**Comment by OmrSi** [comment]
@niksedk Also a duplicate https://github.com/SubtitleEdit/plugins/issues/156 ?

**Comment by niksedk** [comment]
There's now a `DeepL Screen-Scraper translate` plugin
