### ISSUE TITLE
Unable to use OCR

### ISSUE THREAD

**Issue by correctstrawberry** [SubtitleEdit/subtitleedit#3135]
I am on Linux; I tried both the provided release and a version I compiled from the source.

I open a .sup file, choose the language (in my case, Japanese), and press Start OCR. A message pops up saying "An error occured while running tesseract: read_params_file: parameter not found: textord_tabfind_vertical_horizontal_mix". Apparently that feature was removed from Tessaract sometime this year because it was not used anywhere.

I'm not sure if this is a linux-specific problem or not. I was able to get Tessaract to work separately on exported PNGs, but I want to keep the timing. Any help is appreciated.

**Comment by niksedk** [comment]
Sounds a bit like: https://github.com/tesseract-ocr/tesseract/issues/1441
