### ISSUE TITLE
Entire textbox selected unintentionally when working with more than two lines

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3141]
Hi. 3.5.7 build 35.
I'm currently translating text for dubbing, and so I'm working with 4-6 lines rather than two (I set "max number of lines" to 9 just to be on the safe side).
In RTL mode, in translator mode, with the textbox expanded to a certain size (see gif below), when I type in two lines and then press enter, all the text in the textbox is selected. In the following gif, I do this: It starts focused on a certain subtitle. Then I move one subtitle up (ctrl+up) and then move back down (ctrl+down), delete and retype the last word I have typed, and then press enter. That is when all the text gets selected:
![se-textbox-selected](https://user-images.githubusercontent.com/19672444/46970671-6dd97200-d0c2-11e8-89a2-1d477b242d58.gif)

This seems to have something to do with the grayed out scrollbar appearing on the right.

**Comment by DianaLLL** [comment]
Todah rabah - Unfortunately, I'm still seeing this:

discussion in order  /> to help cultivate satisfaction,  /> retention and
belonging

**Comment by OmrSi** [comment]
Have you tried Shift +  Enter?

**Comment by DianaLLL** [comment]
I have. I just can't get rid of the /> symbols.  I tried Ctrl H as well.

**Comment by OmrSi** [comment]
Wrong Issue.
About your's, It should only be shown in the list view and you can change it from settings.
![screenshot 523](https://user-images.githubusercontent.com/20923700/46975882-7b95f400-d0d0-11e8-9481-44dc181e6259.png)

**Comment by niksedk** [comment]
@darnn: Is this still happening in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?

**Comment by darnn** [comment]
I'm afraid so.

**Comment by darnn** [comment]
As of 3.5.12, this still happens, but only on my Windows 7 PC. On my Windows 10 laptop it doesn't. I have no idea why that would be the case, but this might be beyond the scope of something that can be resolved in SE itself.
