### ISSUE TITLE
Linux Installation Instructions

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3142]
I have downloaded the tar.gz file but cannot configure/make/install, please advise how to install.
(Ubuntu 18.04)

**Comment by donlencho** [comment]
Hello,
What works for me is to use the precompiled portable version that you can download from the download page (current version in file SE357.zip). It's compiled for Windows but you can install the package 'mono-complete' on Ubuntu and then you'll be able to run the executable, no compilation or installation required. Make sure you run the executable with Mono.
You may also need the following packages for video playback and OCR: mplayer, libhunspell-dev, tesseract
Hope this works, personally, apart from some visual glitches on the interface, everything works fine.

**Comment by shag00** [comment]
Thank you very much for that.
________________________________

**Comment by Gitraffe** [comment]
Anyone got mpv + waveform to work? It keeps craching, vlc won't crash but it's unusable because of lagging playback and waveform scrolling is not smooth.

**Comment by shag00** [comment]
I have non-appearing font issues. I just wish that someone would take the tar file and make a deb file out of it. It's such a good program but the little errors are quite annoying.

**Comment by niksedk** [comment]
it will never be super easy, but I've described as much as I could here: https://www.nikse.dk/SubtitleEdit/Help#linux
