### ISSUE TITLE
[Bug?] Changing end time doesn't display subtitle

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3143]
When changing the end time, the line isn't shown unless you go back a frame.
Don't know if it's intentional, but maybe it would be better to see the line so that you can see what you are writing after changing the end time.

**Comment by niksedk** [comment]
Could you explain exactly where and how to re-create this?

**Comment by OmrSi** [comment]
Anywhere. Just go to a line, the change the end time using F12, the subtitle won't show up on screen, it's like the video position is after the end time.
You have to go back a frame for the line to show up on video.

**Comment by OmrSi** [comment]
@niksedk You can notice this is general, the end isn't really the end, it's the end+1.
Try using the "go to current line's end" or "F4" and you'll notice.

**Comment by OmrSi** [comment]
@niksedk Also, I notice it when timing with scene changes, when I want to set the end before a new scene, I have to set it right on the scene change, where it should be one frame before it, whereas setting the start time works fine.

Here is a detailed example:

Here is the first shot:
![screenshot 777](https://user-images.githubusercontent.com/20923700/49548960-0b496900-f8f0-11e8-90b4-6384a4af3ed5.png)

Here is the second:
![screenshot 778](https://user-images.githubusercontent.com/20923700/49548991-1c927580-f8f0-11e8-9cf9-514a0a1f690c.png)


So, in theory, if I want the line to end before the shot, I must pause before the shot by 1 frame and end the subtitle, but that's not what happens.
Here is what happens when I end it one frame before the shot:
![screenshot 779](https://user-images.githubusercontent.com/20923700/49549090-67ac8880-f8f0-11e8-8a33-e574854df8c2.png)
See? the cursor is at the end, but the line isn't showing up.

So, If I want it to end one frame before the shot, I have to end it at the shot:
![screenshot 780](https://user-images.githubusercontent.com/20923700/49549276-f1f4ec80-f8f0-11e8-9fee-c11f1b894d3c.png)
![screenshot 781](https://user-images.githubusercontent.com/20923700/49549277-f1f4ec80-f8f0-11e8-84db-5303d9b530ff.png)

Please, just give me a thumbs up if you see this, just so I don't mention it again, you can take your time fixing it.

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/commit/036fd03ca372e921469fbac408282a13b074dcf3
