### ISSUE TITLE
[Bug] Toggle dialog dashes with tags.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3147]
When using it with tags, it doesn't consider tags.

**Comment by OmrSi** [comment]
Awesome. <3

**Comment by OmrSi** [comment]
@niksedk After some testing, it's still misbehaving with HTML tags.
For example:

```
<font color="#40BFFF">تحذير من المستوى الثاني.
تباً!</font>
```

Becomes:
```
- <font color="#40BFFF">تحذير من المستوى الثاني.
- تباً!</font>
```

While it should be:
```
<font color="#40BFFF">- تحذير من المستوى الثاني.
- تباً!</font>
```

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk I just noticed the same thing happening with Music Symbols...
