### ISSUE TITLE
Exporting tu EBU STL always crashes on Linux

### ISSUE THREAD

**Issue by felagund** [SubtitleEdit/subtitleedit#3149]
I am not sure if bugs that only happen under Linux are accepted. Any time I try to export SRT subtitle to EBU STL, SE crashes. It does not happen when I run in under windows in a virtual machine. How can I provide a meaningful stacktrace?

**Comment by p-kraszewski** [comment]
EBU uses braindead `ISO-6937` encoding, A.K.A `x-cp20269` (AFAIK it is the only place where this encoding is used) and Mono does not implement _this particular_ codec.

**Comment by felagund** [comment]
Is this a wontfix or has it been fixed?

**Comment by niksedk** [comment]
> Is this a wontfix or has it been fixed?

It's a timeout wontfix... a PR or an idea for a fix is still welcome.

**Comment by p-kraszewski** [comment]
@felagund it is a thing to report to [mono/mono](https://github.com/mono/mono). Lacking encoding is on _their_ side, not @niksedk .

**Comment by felagund** [comment]
Actually, this has been fixed., I have not tried in the last year or two, I guess (or I would always do it in Virtualbox right away).

Subtitle editor just opens EBU STL, one is able to edit the EBU file properties under "file", one is able to save it (directly from saving/loading, there is no option to import them export them as in the past). Here is a sample file:

[sample.zip](https://github.com/SubtitleEdit/subtitleedit/files/9443531/sample.zip)

So I guess this should rather be reclassified as fixed - thanks to whoever made that happen.

**Comment by p-kraszewski** [comment]
I can confirm your file opens in SE4.6.7 (Arch/aur) with mono 3.12.0.177-1
