### ISSUE TITLE
Can't successfully batch extract/process subtitles. 

### ISSUE THREAD

**Issue by mzso** [SubtitleEdit/subtitleedit#3150]
Hi!

I sometimes use the batch conversion tool to extract subtitles from a bunch of files (eg: series pack) both to fix them and because having external subtitles is more practical because the player can read it all and I can search it, etc.
So I use the "overwrite original file" option, which actually results srt-s being saved right next to the source video file with an identical name, which works fine much of the time. (Though it sucks if I process external subs and actually want to keep the original files too, I have to copy manually a lot.)

But I have a problem which prevents me from doing this if there are multiple subtitles embedded. There is no way to specify which will end up there so I end up with the wrong language one, and not what I want. And I can't figure out a workaround. If I open a file directly in SE I get a prompt to choose between the two embedded subs, but here I can't set a preference.

**Comment by niksedk** [comment]
Fixed in #3297

**Comment by mzso** [comment]
[**@niksedk**](https://github.com/niksedk) commented on [2019. jan. 18. 15:16 CET](https://github.com/SubtitleEdit/subtitleedit/issues/3150#issuecomment-455559989 "2019-01-18T14:16:25Z - Replied by Github Reply Comments"):
> Fixed in [#3297](https://github.com/SubtitleEdit/subtitleedit/issues/3297)

That issue is difficult to follow. Will this also help if there are multiple subtitles in the same language? Which is often the case.

**Comment by OmrSi** [comment]
@mzso It does:
`Steins;Gate EP - 01 Prologue of the Beginning and Ending.#4.eng`
`Steins;Gate EP - 01 Prologue of the Beginning and Ending.#5.eng`

**Comment by mzso** [comment]
[**@OmrSi**](https://github.com/OmrSi) commented on [2019. jan. 18. 18:39 CET](https://github.com/SubtitleEdit/subtitleedit/issues/3150#issuecomment-455628501 "2019-01-18T17:39:46Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) It does:  
> 
> `Steins;Gate EP - 01 Prologue of the Beginning and Ending.#4.eng`  
> 
> `Steins;Gate EP - 01 Prologue of the Beginning and Ending.#5.eng`

Great!
