### ISSUE TITLE
Why nothing happens on SE ?

### ISSUE THREAD

**Issue by Aliage** [SubtitleEdit/subtitleedit#3151]
**Hi everybody,**

I just changed my version of 3.4.10 to v3.5.7 build 1, I just did exactly as you told me, but this time when I click on "start OCR" ! A window opens (Need dictionairies?)

<a href="http://zupimages.net/viewer.php?id=18/43/7rzl.png"><img src="https://zupimages.net/up/18/43/7rzl.png" alt="" /></a>
Nothing happens when I click on "ok", also when I try to choose a language the box remains empty as in the image? it's normal ?

<a href="http://zupimages.net/viewer.php?id=18/43/madf.png"><img src="https://zupimages.net/up/18/43/madf.png" alt="" /></a>

Need some help, I'm only trying to make some changes and fix some errors that are in the subtitles.

**Comment by darnn** [comment]
When the "need dictionaries" window opens, you need to select the language you intend to use for OCR (in this case, it looks like English), and then click "download" and wait for the data to download. Then you can proceed with the OCR. Though I would recommend using the other OCR method, which you can select on the upper left in the menu in your first image.

**Comment by niksedk** [comment]
@Aliage: What OS are you using? 
Do you have latest version of .net framework: https://www.microsoft.com/net/download/dotnet-framework-runtime

Also, SE will switch back to including Tesseract 3.02 again in next update - you can test the beta here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
(it's the portable version - install to something like "C:\Tools\SE" (do not install to "C:\Program files").

**Comment by Aliage** [comment]
Hi everybody,

I'm using Win 7 Basic Home 32 bits, I did exactly that... yesterday I downloaded the language I wanted to use, after that this is what happens when I tried to click on Start OCR...... ?

<a href="http://zupimages.net/viewer.php?id=18/43/r7dz.png"><img src="https://zupimages.net/up/18/43/r7dz.png" alt="" /></a>

The problem is I have the latest version of Microsoft .NET Framework 4.7 & Visual Studio installed recently on my pc, Visual studio C++ V 15.8.28010 ?

**Comment by Aliage** [comment]
I thought maybe the case import/export will do it, I'm wrong?

**Comment by niksedk** [comment]
Most people use "SubRip (.srt)" when saving subtitles.
If you really want to save in VobSub format, then try File -> Export-> VobSub (if you need images consider Blu-ray sup instead).

**Comment by Aliage** [comment]
I did this :
Export---I have chosen---VobSub (Sub/idx)--- I got this :

<a href="http://zupimages.net/viewer.php?id=18/44/xu64.png"><img src="https://zupimages.net/up/18/44/xu64.png" alt="" /></a>

I saved my work, then I wanted to test the subtitles and surprise, the movies (1080p) didn't detect the subs with VLC. I tried another method... I took the movie and the subtitles together by "Mkvtoolnix", to get at the end a single file, the problem is: also the software doesn't detect the subtitle file !!!

**Are there any ideas that can get me out of this ?** **It really sucks.**
