### ISSUE TITLE
SE hangs after opening videos several times

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3154]
Hi. 3.5.7 build 73. The video player selected is MPV.
This happens under various circumstances, but the shortest way to reproduce it is as follows:
1. Create a new file, so that no subtitle or video files are open.
2. Close and reopen SE.
3. Drag and drop a video file into the video player. After the file has opened, drag and drop a video file into the player again. Do this a total of four times.
4. Attempt to drag and drop a video file into the video player. The cursor now changes into a no entry sign, meaning the file cannot be dropped.
5. Attempt to open a video file, either through video->open video file, or by closing the currently open video file, and then clicking on the video player area.
6. SE will now hang.

**Comment by darnn** [comment]
I can add that this wasn't happening in 2.5.6 build 269 (https://github.com/SubtitleEdit/subtitleedit/commit/cc019ec), but was already happening in 2.5.6 build 340 (https://github.com/SubtitleEdit/subtitleedit/commit/fd8292d).

**Comment by niksedk** [comment]
How is this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
(it's not really the perfect solution as it will leak a bit memory...)

**Comment by darnn** [comment]
Seems fine! But I'd like to keep this open for a few days in case I run into any other scenarios where this happens, since it also seemed to happen on opening/closing of subtitles, just in ways I couldn't reproduce as accurately.

**Comment by OmrSi** [comment]
Just how big of a memory leak is it?

**Comment by darnn** [comment]
By the way, in the current build, if you close a video file, the last frame that appeared in the video player stays behind. And then if you open a video file again and change the size of the video pane, there are artifacts that remain.

Before closing:
![se-close-video](https://user-images.githubusercontent.com/19672444/47719625-6aaebc00-dc54-11e8-8448-fc7795cc06af.png)

After closing:
![se-close-video2](https://user-images.githubusercontent.com/19672444/47719631-6edad980-dc54-11e8-9df2-d3bdddd8c450.png)

After resizing window, opening again, and changing size of video pane:
![se-close-video3](https://user-images.githubusercontent.com/19672444/47719652-7dc18c00-dc54-11e8-9a2d-abe0790a3d15.png)

**Comment by OmrSi** [comment]
@darnn  @niksedk  Same here.
![screenshot 607](https://user-images.githubusercontent.com/20923700/47920294-608df700-deba-11e8-99ea-ee207bbf225a.png)

![screenshot 608](https://user-images.githubusercontent.com/20923700/47920365-89ae8780-deba-11e8-8ad5-07fa18a859af.png)

**Comment by OmrSi** [comment]
It's also making problems after a while when moving from a line to another in waveform while the video is playing

**Comment by darnn** [comment]
I tested this briefly. I can no longer reproduce the hanging, and closing the video now functions pretty much like it's supposed to.
There is one thing, but it's much lower priority than the rest of these issues: When you close a video file, it still does this thing where the last frame shrinks in the video pane to the size it would have been if there had been a subtitle preview underneath it with one of the non-MPV video engines:
![se-closing video](https://user-images.githubusercontent.com/19672444/47968326-17cc6e80-e071-11e8-8064-d6c6096f495a.gif)

However, after this happens everything else seems to function like it's supposed to. I'll keep testing.

**Comment by OmrSi** [comment]
@darnn  @niksedk  Just noticed another problem, very annoying.
If you click "new file" the open another, clicking on the video doesn't play and pause. :\

**Comment by darnn** [comment]
Hmm. Same here.

**Comment by niksedk** [comment]
thx for testing :)

New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
Click on video for play/pause should be fixed.

**Comment by darnn** [comment]
Yeah, over here too!

**Comment by niksedk** [comment]
Cool, thx for testing :)
