### ISSUE TITLE
what  is it with Tesseract?

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#3160]
Latest, final v. of Tesseract was relased few days ago.
Shall v. 4.0.0 be included in next version of Subtitle Edit?
or are there some issues'?'

**Comment by niksedk** [comment]
Tesseract 3.02
![image](https://user-images.githubusercontent.com/1261331/47960601-a05df700-dffe-11e8-88dc-dd9d00e9c5db.png)

Tesseract 4.0: 
![image](https://user-images.githubusercontent.com/1261331/47960691-f59a0880-dffe-11e8-8b1d-451d86125ab9.png)

Tesseract 4 beta 3:
![image](https://user-images.githubusercontent.com/1261331/47960699-3a25a400-dfff-11e8-9e3a-6321f25d581f.png)

Yes, I think that Tesseract 4 final has some issues... italic is not supported in T4 beta3 but the accuracy seems way off in T4 final.

**Comment by niksedk** [comment]
Yes, should be closed... Tesseract 4 will be available a separate download in next version (because it works better for some/more languages). No italic detection is also a huge minus.
