### ISSUE TITLE
[Possible Issue] Question about regex

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3165]
I have a file with a "،" at the end of the line, but like other chars, it must be written at the start to show up at the end, so to make sure everything is ok, I use Regex and search for `،$` but it doesn't show any results while I'm sure there is one result and it shows up in Notepad++.

Here is the file:  [The Equalizer 2.zip](https://github.com/SubtitleEdit/subtitleedit/files/2554342/The.Equalizer.2.zip)
 
And the result is in line 295

Here is another test file, it should find 6 results, it's only finding 3: [Test.zip](https://github.com/SubtitleEdit/subtitleedit/files/2554423/Test.zip)

While it finds 6 when reversing the lines and searching for `^،`

**Comment by niksedk** [comment]
Only last line is considered end of text. You could try `،\n|،$` (so it test for `، + new-line` or `، + end-of-text`).

It seems SE was not entirely consistent about new-lines... so please test with latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Regular expressions have an `Multiline` option - that is not enabled in SE atm

**Comment by OmrSi** [comment]
Cool. But how do I go about finding `،\n` but not capturing `\n`?

**Comment by niksedk** [comment]
Try Edit -> Multiple replace - much better for advanced stuff due to preview + grouping + remembering.

Perhaps you can use something like '^(.+)،(\n)' for first-lines lines, and `^(.+)،($)` for the last line (replace with `،$1$2`)

**Comment by OmrSi** [comment]
I have written these: 
[Test.zip](https://github.com/SubtitleEdit/subtitleedit/files/2558817/Test.zip)

You can close this if you don't intend to support Multiline option for now. :D
Thanks a lot.
