### ISSUE TITLE
Re-balance lines - AutoBreakUnbreakLines?

### ISSUE THREAD

**Issue by dvdmunckhof** [SubtitleEdit/subtitleedit#3166]
Hi everybody,

I'm looking to re-balance lines of a subtitle, so unevenly spread lines should become evenly spread.  This is just for 2-line paragraphs that don't fit on a single line (so I don't need to break long lines or merge short lines), For example:
> Lorem ipsum dolor sit amet, consectetur adipiscing
> elit.

should become:
> Lorem ipsum dolor sit amet,
> consectetur adipiscing elit.

I was not able to find such functionality, so I went through the source code and found this form:  `AutoBreakUnbreakLines`. However, I was not able to find out how to launch this form in the UI (so I don't know yet if this is what I need).

My questions:
1. Does the from `AutoBreakUnbreakLines` do what I'm looking for?
2. If so, how can it be started from the UI?
3. If not, is this functionality available elsewhere in SubtitleEdit?

Thank you for the great tool! 😄

**Comment by niksedk** [comment]
The `Auto br` button actually works on selected lines in the list view.

**Comment by dvdmunckhof** [comment]
> The `Auto br` button actually works on selected lines in the list view.

And there it is, right in front of me all the time... 🤦‍♂️ Thanks for your (very quick) reply!

I was expecting it to be in a form with the option to review the list (review the changes and uncheck what you don't want), hence I was looking in the tools menu. From a quick glance over the source code, that's exactly what the `AutoBreakUnbreakLines` does. I'm still wondering, is that form accessible from the UI?

**Comment by OmrSi** [comment]
Can Break and UnBreak be supported from the list, too? Or is it hard to implement?

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/48157891-36c93b80-e2d1-11e8-9b6f-42d37118f708.png)

**Comment by dvdmunckhof** [comment]
That's perfect, it's exactly what I meant. Many thanks!
