### ISSUE TITLE
Issue with copying several subtitles with a duration of zero

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3167]
3.5.7 build 83.
When working in a file where the duration of all the subtitles is zero, if I select several subtitles, copy them, and then try to paste them or perform column paste, the last selected subtitle is not pasted.
For instance, if I copy these three:
![se-zeroduration-paste-1](https://user-images.githubusercontent.com/19672444/48273116-e1179f00-e448-11e8-8fc5-e1ce7de44250.png)

And then perform column paste on subtitle 4, the result will look like this:
![se-zeroduration-paste-2](https://user-images.githubusercontent.com/19672444/48273159-f68cc900-e448-11e8-8420-c776d8aa2d76.png)

And if I simply paste, it looks like this:
![se-zeroduration-paste-3](https://user-images.githubusercontent.com/19672444/48273179-fee50400-e448-11e8-8fa2-68ba68a2c4e1.png)

Even though the text is being copied correctly:
`1`
`02:00:00,000 --> 02:00:00,000`
`11`

`2`
`02:00:00,000 --> 02:00:00,000`
`22`

`3`
`02:00:00,000 --> 02:00:00,000`
`33`

**Comment by niksedk** [comment]
thx :)
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Thank you! Seems like it is!
