### ISSUE TITLE
[Bug] Column paste time codes not working

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3168]
when pasting using column paste, even if "All" is selected, it only pastes the text.

**Comment by OmrSi** [comment]
Yep. Working great. <3

On another matter related to this, when you copy some lines from another file and paste them in the new file, why does SE change the time codes and adds them right after the selected line?
Shouldn't it maintain the time codes if there was not overlap?

**Comment by darnn** [comment]
I agree. Before I knew to watch out for this, I would sometimes copy ~800 subtitles and try to paste them into a different file, and SE would essentially be unresponsive as it was retiming each individual subtitle, which would take a good chunk of time. One way around this is to paste in source view, but I don't always remember to do that.

**Comment by niksedk** [comment]
I've tried to update the pasting to keep time codes if possible - how does it work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
So now if you paste at proper time location, it keeps the time code, else, it adds a certain gap.
I find it good. 👍
Thanks. :D

**Comment by OmrSi** [comment]
@darnn Check this so I can close it.

**Comment by darnn** [comment]
I haven't looked into the retiming thoroughly, if it's still going on, but as far as I can tell, there's no longer a noticeable delay even when pasting thousands of subtitles, so I'm happy. You can close it as far as I'm concerned.

**Comment by OmrSi** [comment]
Cool.

**Comment by OmrSi** [comment]
@niksedk I just noticed that after pasting the focus stays on the current line and doesn't move to the pasted line as it used to, can it be as it was?

**Comment by OmrSi** [comment]
@niksedk Yep. Just like this, that's what it used to do and no one complained. :D
Now just the gap thing when you copy it a different time location, if you can..
It used to be min. gap, now it's 2100 ms for some reason.

**Comment by niksedk** [comment]
beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
