### ISSUE TITLE
[Bug] Fix common errors window unnecessary coloring

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3169]
![screenshot 635](https://user-images.githubusercontent.com/20923700/48295472-ae939380-e494-11e8-8512-1b4852bb69ac.png)

**Comment by niksedk** [comment]
Can you attach a sub with the "bad" line?

**Comment by OmrSi** [comment]
[The Equalizer 2.zip](https://github.com/SubtitleEdit/subtitleedit/files/2568361/The.Equalizer.2.zip)

**Comment by niksedk** [comment]
I've deleted my settings.xml + decreased single line max length to 42 + opened your sub - then in both main view + fix common errors step 2, the list view line 92 shows white background color...

**Comment by niksedk** [comment]
Hm, just saw it...

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Yep. Working great.
You can close this with the commit if you'd like. <3
