### ISSUE TITLE
How to filter lines with single line?

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#3170]
Say I got a bilingual subtitle file, most of the subs are of two lines. But some of them are single line due to mistake or something, which needs manual fix like breaking or translating the missing line or something. Is there any way to quickly filter them out? Using regex or? Thank you.

**Comment by aaaxx** [comment]
This should work: `^.+$`

**Comment by LeonCheung** [comment]
@aaaxx I tried, but...
![failed](https://user-images.githubusercontent.com/494788/48304096-6afd6000-e54e-11e8-933c-cc57da39166e.png)
You see, #1 is what I'm looking for.

**Comment by OmrSi** [comment]
This should work `\A.*$`

**Comment by LeonCheung** [comment]
Ah, I see, you mean by using Ctrl F, instead of Ctrl Alt M. Yes, it works. Thanks guys, both works.

**Comment by OmrSi** [comment]
@LeonCheung Here, try this with multiple replace tool `\A.*(?!\n).*\z`

**Comment by OmrSi** [comment]
@LeonCheung Here, try this with multiple replace tool `\A.+(?!\n)\z` it should also work with Find.

**Comment by LeonCheung** [comment]
@OmrSi Indeed! Thanks a lot OmrSi! :+1:
