### ISSUE TITLE
[Bug] adding music symbols with tags

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3173]
It should ignore that tag and add it to the sentence, instead, it adds on before the tag and one after the sentence.

**Comment by niksedk** [comment]
thx again :)
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk I guess this is the place for that comment.
It's working with ass tags, but not with HTML.

**Comment by OmrSi** [comment]
@niksedk Beta?

**Comment by niksedk** [comment]
beta here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip :)
