### ISSUE TITLE
[Bug] Total length for sub with more than 2 lines

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3174]
When you click on it from the list, you get this:
![screenshot 643](https://user-images.githubusercontent.com/20923700/48366038-54254d80-e6b5-11e8-94b7-b0b68002d8d4.png)
After clicking inside the textbox, you get this:
![screenshot 644](https://user-images.githubusercontent.com/20923700/48366066-64d5c380-e6b5-11e8-8f1b-a1d9b2643021.png)

**Comment by niksedk** [comment]
Good catch again :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
How is that?

**Comment by OmrSi** [comment]
As usual, It is working and Thank YOU. :D
I guess I'm a "Bug eater". 😅
Such a Dad joke. 😂😂

Like always, You can close it with the commit. :)
