### ISSUE TITLE
Single line length not displayed for more than four lines

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3175]
3.5.7 build 102 (fresh out the oven!)
If there are more than four lines in a subtitle, SE will only display the line lengths of the first four:
![se-line-length](https://user-images.githubusercontent.com/19672444/48368989-e3366380-e6bd-11e8-85e9-d5cd1a4bfcb7.png)

And kudos to OmrSi who reminded me about this with his own line length issue.

**Comment by OmrSi** [comment]
@darnn This is written in the code, if the number of lines is bigger than four, append "..."
I think this is intentional so the labels don't overlap.

**Comment by darnn** [comment]
Huh. I mean, I would just make them carry over into the next line if they overlapped (which might force the user to change the size of the text field are if they want to see both lines). But who am I to say. In any case, it was only relevant to that one job I did back then, thankfully. I just think it could still be useful for people who use SE for things other than subtitles, such as transcription and so on.
