### ISSUE TITLE
MPV subtitle preview fails to update after "adjust all times"

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3180]
3.5.7 build 102.
Under certain circumstances, the MPV subtitle preview times will fail to update after using "adjust all times". Specifically, I move all the timecodes two hours forward so as to not get a preview (because my subtitles just have arbitrary timecodes from "import plain text"), but the preview text remains in the video window at the previous timecode positions.
To reproduce:
1. Create a new subtitle file and then restart SE, so as to start fresh.
2. Import plain text (but don't save yet). I use the following settings:
![se-adjustall01](https://user-images.githubusercontent.com/19672444/48513142-c176e100-e863-11e8-86de-461f62dce54f.png)

3. Open a video file.
4. Save the imported text as SRT.
5. Open the SRT file you just saved using "open (keep video)". It will now shift the video position to the timecode of the first subtitle (see https://github.com/SubtitleEdit/subtitleedit/issues/3084), and the subtitle will appear in the preview:
![se-adjustall02](https://user-images.githubusercontent.com/19672444/48513750-4a424c80-e865-11e8-9fd4-0abc3cb3f27f.png)

6. Move the video position to the very beginning (00:00:00:00), either through keyboard shortcuts or by using the "stop" button in the video player.
7. Use "adjust all times" to show all subtitles two hours later (per the log: Show all lines 3600.0 seconds later).
8. Save the file.
9. Now move the video position back to the time that it automatically skipped to in step 5. In my case this is 00:00:10:00. The subtitle preview will still look the same as in step 5, even though the subtitle's start time will now be two hours later:
![se-adjustall03](https://user-images.githubusercontent.com/19672444/48513824-89709d80-e865-11e8-91f7-840841be53e0.png)

**Comment by darnn** [comment]
In that specific instance it updates correctly now, but it's not totally gone. For example:
To start with, a shorter version of the original. Open SE with no files. Open a video file. Open a subtitle using "open (keep video)". Navigate away to a place in the video where there are no subtitles. Move all subtitles forward using "adjust all times".  Save. Go back to the original position the video skipped to. So far so good, the preview's gone (it actually shows up for a split second and then disappears). Now, use "adjust all times" to shift the subtitles back to where they were originally. The preview shows up again. Navigate away in the video to where there are no subtitles. Save. Navigate back to where the subtitles were. They're still there.

**Comment by niksedk** [comment]
Hm, can't re-create this...

**Comment by niksedk** [comment]
How is this https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
I have noticed this happening here too when using extend to next's start.

Go to a sub and hit pause, the use extend:
![screenshot 670](https://user-images.githubusercontent.com/20923700/48638571-af1eb380-e9d9-11e8-8ca0-ee0c876ffc68.png)

The subtitle doesn't show:
![screenshot 671](https://user-images.githubusercontent.com/20923700/48638620-d2e1f980-e9d9-11e8-802c-7b9416a7aaba.png)

**Comment by OmrSi** [comment]
@niksedk Could you check the case I added?

**Comment by OmrSi** [comment]
@niksedk Strange, just tested again with another line.
Go to line -> use extend -> play the video.
The video position should be on the original timing the moves to the added time.
![screenshot 674](https://user-images.githubusercontent.com/20923700/48648504-4430a500-e9f8-11e8-99c8-ed83aad441e0.png)
![screenshot 675](https://user-images.githubusercontent.com/20923700/48648516-53afee00-e9f8-11e8-8b17-f97cc03abd89.png)

**Comment by darnn** [comment]
I believe this is still happening for me too in build 107. Assuming I understand correctly.
I opened a video and subtitles that have been synchronized with it and turned on waveform.
In waveform, I placed the cursor roughly in the middle of a certain subtitle and clicked there to move the video position there:
![se-extend-1](https://user-images.githubusercontent.com/19672444/48649046-03399000-e9fa-11e8-8f30-eac58accbb59.png)


Then, in waveform, I dragged the edge of the subtitle that represents its end time to extend the amount of time it appears:
![se-extend-2](https://user-images.githubusercontent.com/19672444/48649065-12b8d900-e9fa-11e8-9230-5f76e7e4ad4f.png)

Immediately after that I started playing the video (either by clicking on it in the video pane or using the keyboard shortcut), and when it reached the part where the subtitle didn't previously appear, it still didn't appear:
![se-extend-3](https://user-images.githubusercontent.com/19672444/48649106-38de7900-e9fa-11e8-9deb-39f74a4ce37e.png)

**Comment by OmrSi** [comment]
Yes, it is happening in that case here also, whether it was dragged or "Extend to next start" is used, this issue happens.

@darnn By the way, This show is awesome, I hope you have fun translating it. 😄😄

**Comment by niksedk** [comment]
thx for explaining :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Seems to work here!

**Comment by OmrSi** [comment]
It's working, but it's flashing before stabilizing...
![screenshot 695](https://user-images.githubusercontent.com/20923700/48672768-d8a71e80-eb42-11e8-8467-fb29b6388487.png)
It disappears for some time then shows up again.

**Comment by OmrSi** [comment]
@niksedk After some testing, I noticed that it just needs some time to refresh, so If you extend it while playing and without pausing, or if you to the of the line and extend then immediately play, It flashed also.

**Comment by niksedk** [comment]
I think so...
