### ISSUE TITLE
"Windows forms thread exception" in Windows 1809

### ISSUE THREAD

**Issue by blaubart2** [SubtitleEdit/subtitleedit#3182]
In Windows 10 1803 this issue does NOT exist at all:
Just tried latest SE Beta 3.5.7.107 in Win10 1809 2018-11 Update - still no success.

I get "Windows forms thread exception" by simply klicking on "Load" or "Save" Button. Also in old SE v. 3.5.3.0 even in super old 3.3.0.1 I get "Exceptional error".

- klick "open" button brings -> "Windows forms thread exception"
- drag&drop files into open SE works ok / always worked - but
- klick "save" button brings -> "Windows forms thread exception"
- trying most export -> "Windows forms thread exception"

![subted265](https://user-images.githubusercontent.com/44677301/48618502-da81ae00-e999-11e8-8593-eb629ebc1999.png)

**Comment by niksedk** [comment]
Try googling `CLSID DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7`.
check https://stackoverflow.com/questions/29929862/exception-from-hresult-0x80040111-class-e-classnotavailable
or https://stackoverflow.com/questions/7297918/com-class-factory-error-80040154-when-opening-get-directory-dialog

**Comment by blaubart2** [comment]
Thank you niksedk this explained the reason:
> Visual Themes may be turned off at the OS level as well (when using a high contrast theme for instance)<

Indeed here is ALWAYS a high contrast theme running, my eyes are not the best... But while SE runs perfect using a high contrast theme in Win10 1803 the issue indeed starts with Win10 1809 using a high contrast theme.

May be you heared about 1809 starting a new "Standard App Mode = Dark" featuring a new dark Explorer in company with immense visual style changes. May be the new "Windows forms thread exception" issue in SE using a high contrast theme in 1809 is caused by this. 

Would be important for me if you could solve it in SubtitleEdit. Thank You!

**Comment by niksedk** [comment]
@blaubart2: I think it's a Microsoft fix...

**Comment by OmrSi** [comment]
@niksedk If it's a Microsoft fix, is this closed?

**Comment by blaubart2** [comment]
Windows update 2018.12 ... still no fix. After all a SE fix?

**Comment by niksedk** [comment]
Do you still have the problem with latest SE (3.5.9) ?

I still believe it's a ms fix... SE is compiled with .net version 4, but I've also made a 4.6 test version here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta-dotnet-4-6-2.zip - how is this?

**Comment by blaubart2** [comment]
Windows 10 Pro 1809 latest 17763.379 - latest SE 3.5.9 -> problem still the same, too sorry..

You may easily test by yourself, in Win10 1809 create a link to:
`explorer.exe shell:::{26EE0668-A00A-44D7-9371-BEB064C98683}\0\::{ED834ED6-4B5A-4BFE-8F11-A626DCB6A921}`
(is the old control panel design section)

There choose any Hi-Contrast design/theme (believe me there are **much** nicer looking ones ;-). Now try SE any version...

**Comment by zeromind** [comment]
Had the same issue on Windows 10 (1809) earlier today, after upgrading Windows 10 on that system to version 1903 *Open*, *Save as...* and *Export* all work as expected.

Broken: Windows 10 (Version 1809) with High-contrast enabled + SE 3.5.9
Working: Windows 10 (Version 1903, OS Build 18362.145) with High-contrast enabled + SE 3.5.9

**Comment by jernejs** [comment]
This was a common problem on 1809 when using High Contrast mode that affected even some Microsoft's own programs. Supposedly a workaround is to add {4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38} GUID to supportedOS in manifest, which makes these programs use themes in high contrast mode.

**Comment by blaubart2** [comment]
1903 is the 'think-about' vers. not so much new things but repair.. so niksedk was right: 'I think it's a Microsoft fix..'. Yes it was, everything works as expected now. Nevertheless thank you for your couresty.
