### ISSUE TITLE
Spell check misses numbers and text together in a word

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#3183]
The spell check seems to miss cases where there are numbers and characters in the same word.

```
114
00:13:53,440 --> 00:13:58,879
<i>250puntaa asianajalleni Siddawaylle
ja hänen vaimolleen Sarahille.</i>
```

**Comment by niksedk** [comment]
thx :)
Should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

Does that work okay for you?

**Comment by niksedk** [comment]
New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by Boulder08** [comment]
Yes, now it works :)

**Comment by niksedk** [comment]
thx for verifying :)

**Comment by OmrSi** [comment]
@niksedk It's now seeing tags as a mistake. 😅
As you write "{\fn Arabic Typesettings\fs32}"
It sees "Typesettings\fs32" as a mistake, and this a problem, because if the is many tags in the file, you have to skip them one by one.

**Comment by OmrSi** [comment]
![screenshot 686](https://user-images.githubusercontent.com/20923700/48667197-c0e78000-ead9-11e8-9951-f2c11bd6864f.png)

**Comment by niksedk** [comment]
Nice catch :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Working perfectly. Thank you. 😄
