### ISSUE TITLE
Exception occurred with "Add better multi match"

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#3185]
There's a colon with italics that is incorrectly detected as a single dot, so I tried aborting the OCR and inspected the compare matches, then selected the add better multi match option. After that, an exception occurs.

![image](https://user-images.githubusercontent.com/11799308/48639636-d1660080-e9dc-11e8-9e9f-02e52b13cbe3.png)

**Comment by niksedk** [comment]
Thx for the info - could you test this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?

**Comment by Boulder08** [comment]
Thanks, that one works fine :)

**Comment by niksedk** [comment]
@Boulder08: Hm, I've trouble re-creating this... could you guide a bit more precisely?

**Comment by niksedk** [comment]
thx :)
Beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by Boulder08** [comment]
Yes, that one works fine, thank you. First I tried to rebuild from the latest sources and it didn't work, are there some commits still upcoming?

**Comment by niksedk** [comment]
No, all fixes are pushed.
