### ISSUE TITLE
[Question] MPV on Windows XP

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3187]
A friend of mine is trying to run MPV on Windows XP, Here is a video from him with the details of what's happening:
https://mega.nz/#!2HB0WYLA!AKaJAuOJ2m0_Cky78LjAFTrY_WtMSDZK5nXxwmHx3pE

**Comment by darnn** [comment]
Looks like, to quote the build website, XP support has been dropped (but a build from 2015 should still work):
https://github.com/mpv-player/mpv.io/issues/59

**Comment by OmrSi** [comment]
Yep. just saw it. Thanks again.

**Comment by darnn** [comment]
Let me know if it works for him! If it does, it might be a good idea to add the link to the FAQ for people trying to use MPV on XP (I'm just pasting it here for future reference):
https://web.archive.org/web/20161023110401/https://mpv.srsfckn.biz/mpv-dev-20151029.7z

**Comment by OmrSi** [comment]
Will do. :D

**Comment by OmrSi** [comment]
Already tried, it didn't work. :\
MPV and VLC and portable SE are working, But VLC and Directshow and MPV inside installed SE aren't. 😓

**Comment by darnn** [comment]
Weird. And beyond me, I'm afraid.

**Comment by OmrSi** [comment]
I tried deleting everything related to SE and reinstalling, it doesn't work, the sound is only working in portable and with mpc.

And by the way, when my friend tested the version you mentioned, the messages disappeared but the video didn't work.
Just like what happened with me. :\

**Comment by OmrSi** [comment]
😂😂😂😂😂😂😂😂
Somethings are just insane...
I don't know why it would just change but its own.
![screenshot 683](https://user-images.githubusercontent.com/20923700/48664859-19a12380-eaae-11e8-86be-f1920ef4464d.png)

**Comment by OmrSi** [comment]
Yeah, I'll just tell him he has to downgrade SE or upgrade his windows.
XP is old, we're at 10, Redstone 4 now. 😅

**Comment by darnn** [comment]
I stuck with XP as long as I could too, but at a certain point I would have had to upgrade to the 64 bit version if I wanted more than 4 GB of RAM, and I decided to just bite the bullet and switch to 7. But I'm holding on to 7 for as long as I can, now. One of my laptops that came with 8 upgraded itself to 10 on its own, and while it was slow before, it's nearly impossible to use it now. Like, when I use SE, aside from things like lag in playback, which is a given, stuff like this (https://github.com/SubtitleEdit/subtitleedit/issues/2179) or joining two subtitles inside of a file takes like a second or two, which, if you're used to it happening instantaneously, is just the worst.

**Comment by OmrSi** [comment]
Yeah, Windows 10 does need some high specifications.

**Comment by OmrSi** [comment]
By the way, can you test this issue when you have time? https://github.com/SubtitleEdit/subtitleedit/issues/3172
Just copy the latest beta so the system, If you haven't already, and try to download Tesseract 4.

**Comment by niksedk** [comment]
Win XP does not support latest version of TLS, so sites that do not support older TLS (unsecure) connections like github will NOT work on XP :(

**Comment by OmrSi** [comment]
Yeah, The proved to be the case, it's too old, anyway.

**Comment by OmrSi** [comment]
@darnn Installed or portable?

**Comment by OmrSi** [comment]
I replace the installed exe with the beta one.

**Comment by darnn** [comment]
It works when I replace the installed version's exe too.
