### ISSUE TITLE
OCR changes some wrong characters into italic

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#3188]
This kind of match pattern results in all the words being marked as italic. Actually there is a missing space between ! and A.

![image](https://user-images.githubusercontent.com/11799308/48670577-6aeafa80-eb22-11e8-9e0c-eca0be6f12df.png)

```
398
00:44:08,480 --> 00:44:14,510
Minä huomasin. Kiikareita ei näkynyt.
<i>- Trés bien!Alat</i> oppia.
```

**Comment by Boulder08** [comment]
Also a bit different one, this time works the other way around.

![image](https://user-images.githubusercontent.com/11799308/48670753-af2bca00-eb25-11e8-9bd2-d8c37f1dda2c.png)

`77
00:09:18,560 --> 00:09:25,273
"Hippo"tarkoittaa virtaa
ja <i>"potamus"hevosta.</i> Virtahepo.`

**Comment by OmrSi** [comment]
@niksedk Do you think this also might be fixed?
