### ISSUE TITLE
Feature suggestion for "change casing"

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3191]
Hi. I have a fairly specific way I need to use "change casing": I need to only apply it to the start of sentences and to i/I. Whoever is transcribing this show for me capitalizes names and proper nouns (so I don't need those changed), but doesn't capitalize the first letter in a sentence, e.g.:
`thanks to women like Kim Kardashian,
Jennifer Lopez, and Beyonce,`
Don't know if this would be useful for anyone else, but in case you think it might be, I'd love to be able to do that.

**Comment by darnn** [comment]
Oh, huh! It's been so long since I used fix common errors, I forgot about those! Thank you!

**Comment by OmrSi** [comment]
You got it. That's why we're all here. 😄
