### ISSUE TITLE
OCR screen loses color coding

### ISSUE THREAD

**Issue by BxMxK** [SubtitleEdit/subtitleedit#3192]
After an OCR completes and all of the lines are still highlighted with their respective error colors if you right-click and delete a line all of the error color highlighting disappears.

This is beyond maddening if there are multiple lines I want to cut out of a sub when I am reviewing the OCR results before I hit 'Ok' to send them to the main window. Have to make a list of line numbers in notepad, finish reviewing lines, send to main window, scroll through AGAIN and delete.

**Comment by niksedk** [comment]
thx for the info - how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?
