### ISSUE TITLE
[Bug] Adjust Via end position doesn't affect original subtitle.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3194]
Both "Adjust via end position" and "Adjust via end position and go to next" doesn't update the original file's timing...

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk It's working, But now I can't use "Undo" after adjusting. :\

**Comment by niksedk** [comment]
Undo works fine here...

**Comment by niksedk** [comment]
Beta updated with fix related to mpv preview: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
( commit #f782bfc71dc7742ce9a25e3ae850ece151377047 )

**Comment by OmrSi** [comment]
Yeah, undo is working, must have had to restart the program.

**Comment by OmrSi** [comment]
Yep, It's working again. Thanks. <3
