### ISSUE TITLE
[MPV Bug] Opening file goes to first line

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3198]
I don't know If this is a problem exactly,
If you have a file with a line that starts between 00:00:00.000 and 00:00:00.875 (It varies from one file to another) the subtitle always goes to the first line even if you closed the file on another one.

When I open SE, it takes a second to launch and in that seconds it plays a tiny part at the beginning of the video, so the list goes to the first line even if you had selected another line before closing.

If this can't be avoided, you can close this issue as it is not very important.

**Comment by niksedk** [comment]
Hm, I cannot re-create this...

**Comment by OmrSi** [comment]
There has to be a video file opened.

**Comment by OmrSi** [comment]
If you open a subtitle with a line that starts between 00:00:00.000 and 00:00:00.875 and has a video file, when you close and open SE with a file open, when it starts, SE goes to the beginning of the file for a second then tries to go to the saved line, but at that second, it gets stuck on the first line and the list focus moves to that line.

**Comment by OmrSi** [comment]
@niksedk Here, a picture is worth a thousand words. 
![untitled project](https://user-images.githubusercontent.com/20923700/49954194-95a15680-ff08-11e8-8a99-7731a57db856.gif)

You can also notice that the first added line is 2 seconds, which is related to https://github.com/SubtitleEdit/subtitleedit/issues/3075

**Comment by niksedk** [comment]
OK, see it know... this might be a little better I hope: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Perfect, you can close it with the commit. 😄

**Comment by OmrSi** [comment]
@niksedk This is still happening but only when you leave a file open when you close SE, then when you open SE, it goes to the first line.
