### ISSUE TITLE
从354版本开始，字体显示得就怪怪得不正常，是我特例么？

### ISSUE THREAD

**Issue by zameax** [SubtitleEdit/subtitleedit#3199]
从354版本开始，字体显示得就怪怪得不正常，是我特例么？

![20181125154741](https://user-images.githubusercontent.com/42455055/48976880-d5271080-f0c9-11e8-8297-507f8a162c8e.png)

**Comment by LeonCheung** [comment]
貌似还真是，一直用英文界面，没太注意。
It seems so... in both win8.1 and win10. 
![qq 20181125155452](https://user-images.githubusercontent.com/494788/48976914-cee56400-f0ca-11e8-9b08-107862661925.png)

**Comment by tinyboxvk** [comment]
![subtitleedit](https://user-images.githubusercontent.com/13696594/49832263-0cfeab00-fd8e-11e8-8527-4ba15594b648.png)
UI is normal here. My OS is in English, so it may have something to do with the font.
