### ISSUE TITLE
Google translate issue

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [SubtitleEdit/subtitleedit#3200]
Recently, google translate results frequently contain some empty blocks of paragraphs! This maybe a result of bad internet connection, or a pressure on google. I solved this in in the GoogleTranslate.DoTranslate sub by changing this line: 
`result = TranslateTextViaScreenScraping(input, languagePair, _screenScrapingEncoding, romanji);`

to:

```
for (var c = 0; c < 3; c++)
{
  result = TranslateTextViaScreenScraping(input, languagePair, _screenScrapingEncoding, romanji);
  if (!string.IsNullOrEmpty(result))
     break;
}
```

so, this code retries to translate the block more 2 times if it fails. It works fine for me.

**Comment by niksedk** [comment]
thx for the info :)
Does the above commit work for you?
Beta also updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by MohammadHamdyGhanem** [comment]
I see you added the for loop, but I don't see the break when result is not empty. If I didn't miss any thing (becuase I don't understand the whole code anyway), this will always repeat the translation process 3 times, and if the third trial is failed then result will be empty. This condition is a must after reading the result:
```
  if (!string.IsNullOrEmpty(result))
     break;
```
Thanks.

**Comment by MohammadHamdyGhanem** [comment]
And maybe you can add a dropdown list on the translation from to allow the user to choose the trial times (asy 1 to 5), instead of hardcoding it as 3.

**Comment by niksedk** [comment]
I don't think this should be a UI setting... I've upped the loop count to 5.

The break for the loop is here: https://github.com/SubtitleEdit/subtitleedit/blob/66424c474595399bf7f2767db19dcff35cb159ac/src/Forms/GoogleTranslate.cs#L585

**Comment by OmrSi** [comment]
@niksedk Closed?

**Comment by niksedk** [comment]
yes, and thx :)
