### ISSUE TITLE
[Bug?] Selecting a line after selecting all

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3201]
Open a file with a large number of lines, maybe a 1000.
Select all lines the click on one of the lines from the list.
You'll notice that the higher you get. the more time it takes for SE to select the line.
For example, line 1000 takes 3 seconds while line 1 doesn't take any time to get selected.

**Comment by niksedk** [comment]
Hm, it's seems to be okay fast for me with a 1.200 lines sub...

**Comment by OmrSi** [comment]
I think it's the abundance of tags that causes this: 
[Joker.2019.1080p.10bit.BluRay.8CH.x265.HEVC-PSA.zip](https://github.com/SubtitleEdit/subtitleedit/files/4021915/Joker.2019.1080p.10bit.BluRay.8CH.x265.HEVC-PSA.zip)

**Comment by OmrSi** [comment]
![Untitled Project](https://user-images.githubusercontent.com/20923700/71767446-26344580-2f15-11ea-8257-0c21cf29760d.gif)

**Comment by niksedk** [comment]
How is this beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Perfect. :D
You can close this with the commit.
Thank you.
