### ISSUE TITLE
Unused line breaks

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3203]
Hello,
Unused line breaks in Fix Common Errors doesn't work in some instances. I'm attaching a file where it doesn't. I tried it in version 3.3.12 and it works on that, but not in 3.5.7
Thanks.

**Comment by uckthis** [comment]
I'm not sure why file isn't attached.
Here is it: http://s000.tinyupload.com/index.php?file_id=56863570857586860170

**Comment by OmrSi** [comment]
1. The extension is not supported, you need to zip the file then upload it.
2. It's working fine for me in the latest beta:
![screenshot 751](https://user-images.githubusercontent.com/20923700/49160109-a8276780-f32e-11e8-910e-bd76c933c19b.png)

**Comment by uckthis** [comment]
It still doesn't work for me.
See before and after.

And, yes, it's Colbert show.

**Comment by uckthis** [comment]
Still files don't atttach... :@
BEFORE:
[url=https://ibb.co/2txrbFG][img]https://i.ibb.co/qsK8ZDT/1.jpg[/img][/url]
AFTER:
[url=https://ibb.co/fdt9dVJ][img]https://i.ibb.co/r2M32K9/2.jpg[/img][/url]

**Comment by uckthis** [comment]
Still files don't atttach... :@
BEFORE:
https://i.ibb.co/qsK8ZDT/1.jpg
AFTER:
https://i.ibb.co/r2M32K9/2.jpg

**Comment by OmrSi** [comment]
Here's the file you sent after I applied the fixes:
[subtemp.zip](https://github.com/SubtitleEdit/subtitleedit/files/2629308/subtemp.zip)

**Comment by uckthis** [comment]
Nope, I just tried again and it doesn't work. I'm using 3.5.7 build 63. Don't wanna update to latest beta because I lose the "Do not break after list" whenever I update and I'm forced to add words again.

**Comment by OmrSi** [comment]
You can test the beta without moving everything to it.

Plus, the "Do not break after list" is stored in "Dictionaries" folder, Just copy it and your settings file to the new beta folder and you won't lose a thing.
Alternatively, you can replace the exe from the old beta with the new you, you shouldn't lose anything either.
Just to be safe, you should have a backup for your prefered settings in case anything happens.

**Comment by uckthis** [comment]
Just updated to latest beta (Thanks for the advice), but still same.
I'll just use version 3.3 for these.
Thank you.

**Comment by OmrSi** [comment]
I think I see it now, It's working for me because I'm also using "Fix subtitles with more than 2 lines".
But using "delete unused line breaks" doesn't fix the case you mentioned as you said...

**Comment by uckthis** [comment]
I just checked and 3.3 doesn't have "Fix subtitles with more than 2 lines" checked and it still removes all new lines. 
I mostly get these files from CBS as .ssa files and I edit in Notepad; Sel.placing /N/N with /N.

**Comment by OmrSi** [comment]
Then something happened after 3.3 that needs fixing. 👍

**Comment by niksedk** [comment]
Beta updated to fix this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
(a hidden setting "RemoveEmptyLinesBetweenText" can turn this feature off)

Does that work for you @uckthis ?

**Comment by uckthis** [comment]
Yes, It's working now. This is amazing. Thank you. You're a life saver.


But now I see another issue. It used to be that * would come up in  spell check and if you skip all, it wouldn't show again. Now it does. Everytime there is a * in caption, it'll show on spell check. E.g *. *I'm *have, etc. all will show. Spell check considers * as part of the word it is attached to. So *have and *I'm will show up in spell check. I use * indicated few things for the client, so I gotta use them. Is there a work around them? 3.5.7 build 63 works just fine.

**Comment by OmrSi** [comment]
@uckthis That's because someone said it's not detecting numbers attached to letters.
So I guess "*" was added to the detection list with the numbers in this commit https://github.com/SubtitleEdit/subtitleedit/commit/aa2296a500028597fa8b3d2ddebf5f2624db194a

**Comment by OmrSi** [comment]
@niksedk In case you were looking, the "*" issue was here, and you fixed both problems mentioned here. :D

**Comment by uckthis** [comment]
@OmrSi Nope, * issue is still there.

**Comment by OmrSi** [comment]
Nope.
This is from the latest beta...
![screenshot 785](https://user-images.githubusercontent.com/20923700/49707863-da419f00-fc35-11e8-9904-e060d195446c.png)

**Comment by uckthis** [comment]
@OmrSi I had build 163. You're right. Fixed in 164.
Thanks, @niksedk .
