### ISSUE TITLE
File cant be opened because of "subtitles were not found"

### ISSUE THREAD

**Issue by AnaBanana161** [SubtitleEdit/subtitleedit#3204]
mp4 file, full hardsub. 
File can be opened bcs programm doesnt see any subtitles in it.
what s wrong?

**Comment by OmrSi** [comment]
"full hardsub"? Not softsub? Hardsubs are hardcoded to the video, they can't be opened, or am I missing something?

**Comment by niksedk** [comment]
Sorry, SE does not support OCR of hardsubbed videos.

**Comment by AnaBanana161** [comment]
well, i needed a programm which can handle hardsubed video. i found youtube
vlog where a guy did it with the help of this editor. he had hardsubed
video the programm made thousands of SS and converted it to srt file.
i tried to do same, but it didnt work.for me
i pmed the creator guy he said this programm doesnt work with hardsubed
videos.
im confused. 🤔😥

ср, 28 нояб. 2018 г., 17:46 Omar Si notifications@github.com:
