### ISSUE TITLE
Fix RTL via Unicode control characters doesn't also fix LTR

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3205]
Hey. 3.5.7 build 118, but this is old behavior.
So, while what I wrote in the subject sort of goes without saying, the issue is this:
If you write a sentence in a RTL language (e.g. Hebrew) in LTR mode, and then use "Fix RTL via Unicode control characters", the sentence will look as it should in list view. But my problem is that in RTL mode, the Hebrew looks fine but the English doesn't. And as you said here (https://github.com/SubtitleEdit/subtitleedit/issues/2132#issuecomment-284264941), you can't apply RTL to just a single column. But, this is also easy enough to solve with Unicode control characters: For LTR languages in RTL mode, you need to insert one LTR mark at the start of the subtitle and one LTR mark at the end of it. So, could you implement a way of doing it through an option similar to "fix RTL via Unicode control characters"?

**Comment by OmrSi** [comment]
When you use RTL mode, English looks ok in the textbox, only the list view doesn't,
so If he added Unicode control characters, the list would look ok but the textbox wouldn't.
Except if there is a way to make a list column look different.

**Comment by darnn** [comment]
It looks okay in the textbox if you use left-ctrl+left-shift to align it left, since you can do that individually to the source and translation textboxes.

**Comment by OmrSi** [comment]
Oh, It looks ok here because I use center alignment...
So, If he did that, textbox when using center alignment would look reversed...

**Comment by darnn** [comment]
I suppose, though I'm not sure because I don't know how to align the textbox to the center.

**Comment by OmrSi** [comment]
It looks much better in my opinion...
![screenshot 752](https://user-images.githubusercontent.com/20923700/49171893-3cea8f00-f348-11e8-9d63-f9129c03ee62.png)

**Comment by darnn** [comment]
Ah, of course. At any rate, it actually looks fine centered, it remains aligned to the left, just like it does if you don't add the LTR marks. You can try it yourself, just write a sentence in English ending with a punctuation mark and add LTR marks at the start and at the end of it.

**Comment by OmrSi** [comment]
Yeah, that's why I meant but, "English looks ok in the text box, only the list view doesn't", I meant centered. :D

That's why If he used Unicode control characters, the list would look ok but the textbox wouldn't...

**Comment by darnn** [comment]
No no, that's what I'm saying, if the text in the textbox is centered, it looks the same in list view, whether it contains LTR marks or no. Here's centered text without LTR marks:
![se-centered-rtl-01](https://user-images.githubusercontent.com/19672444/49173002-2d207a00-f34b-11e8-8991-d2a5b00b7ef3.png)

Here's the same text with LTR marks:
![se-centered-rtl-02](https://user-images.githubusercontent.com/19672444/49173012-34e01e80-f34b-11e8-9f84-4df9b319dea7.png)

**Comment by OmrSi** [comment]
the text box in RTL mode depends on what language you write in it.
In the same file you're testing, close SE and open it again, you'll notice that difference.
Look:
![screenshot 755](https://user-images.githubusercontent.com/20923700/49174540-39a6d180-f34f-11e8-9f39-1720e8cc7a72.png)

It all depends on the language written, the text box is always right, only the list has a problem, and since it can't show two different alignments, I don't think anything can be done...

**Comment by darnn** [comment]
I see what you're saying. Still, though, I think it would be nice to have the option to automatically add LTR marks at the beginning and end of subtitles like with "fix RTL via Unicode control characters", since, again, it would fix LTR languages in RTL mode in list view, and you can always align the text box to the right (which, granted, isn't as aesthetically pleasing, but is more practical in this case).
I've actually only realized you can do this effectively with LTR marks at the start and end today. Before now, for some years, I was using a series of elaborate and not always accurate regular expressions, which took me days to write and troubleshoot, and which essentially screwed up the text. (But the plus side was that I could just apply them automatically).
So the addition of such an option would make my life a lot easier, at least. And it would also make it easier for me to show SE's effectiveness to others who translate from English or Russian into Hebrew, since they could work in RTL mode but preserve the proper alignment of the original LTR subtitles. So far, since I've only been using my elaborate regular expressions, I was hesitant to tell people how to do that, as they're usually less tech savvy than I am, and it's hard enough for them to get used to a new program as it is.

**Comment by darnn** [comment]
@niksedk Any chance you could look into this? It would function just like "fix RTL via Unicode control characters", except adding an LTR mark at the start and at the end of the text of each subtitle (i.e. the start of the first line and the end of the second line).
