### ISSUE TITLE
[NEW FEATURE] Word spell check integration

### ISSUE THREAD

**Issue by Mmoi-Fr** [SubtitleEdit/subtitleedit#3211]
Hi,

Do you think a Microsoft Word spell check integration (windows only, maybe) could fit into Subtitle Edit?
The thing is that Word is more powerful than a basic spell checker and it could be interresting to have it integrated.

I made a really quick research and it seems to be possible: [link](https://stackoverflow.com/questions/9718687/spell-checking-in-c-sharp-using-word-interop).

**Comment by niksedk** [comment]
How does the Word spell check plugin work for you? 
Check File -> Plugins.

**Comment by Mmoi-Fr** [comment]
Oh damn, sorry and thank you.
