### ISSUE TITLE
A solution for Google Translate

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [SubtitleEdit/subtitleedit#3212]
Hi,
I solved the Google translate problem by using the WebBrowser Control.
It is a bit slower, because the returned page size is about 127 kbyte just to translate a chunk of text (512 chars)!. This is due the CSS and Java script code in the page!
On the other hand, slow translation means low hit rate on google, so, maybe we can survive for a while!
There is something to try to minimize the downloaded size. We can inspect the javascript function to fin the code that executes the translation request, and extract the direct translation url, to get the translated text directly. I will not do that, but you are welcome to try.

Notes about the code:
1-	The WebBrowser control uses IE 7, so I added code to fix that. This code may need permissions to access the registry on the user PC, so it may need to run as admin.
```
    public class WebBrowserHelper
    {
        public static int GetEmbVersion()
        {
            int ieVer = GetBrowserVersion();

            if (ieVer > 9)
                return ieVer * 1000 + 1;

            if (ieVer > 7)
                return ieVer * 1111;

            return 7000;
        } // End Function GetEmbVersion

        public static void FixBrowserVersion()
        {
            string appName = System.IO.Path.GetFileNameWithoutExtension(System.Reflection.Assembly.GetExecutingAssembly().Location);
            FixBrowserVersion(appName);
        }

        public static void FixBrowserVersion(string appName)
        {
            FixBrowserVersion(appName, GetEmbVersion());
        } // End Sub FixBrowserVersion

        // FixBrowserVersion("<YourAppName>", 9000);
        public static void FixBrowserVersion(string appName, int ieVer)
        {
            FixBrowserVersion_Internal("HKEY_LOCAL_MACHINE", appName + ".exe", ieVer);
            FixBrowserVersion_Internal("HKEY_CURRENT_USER", appName + ".exe", ieVer);
            FixBrowserVersion_Internal("HKEY_LOCAL_MACHINE", appName + ".vshost.exe", ieVer);
            FixBrowserVersion_Internal("HKEY_CURRENT_USER", appName + ".vshost.exe", ieVer);
        } // End Sub FixBrowserVersion 

        private static void FixBrowserVersion_Internal(string root, string appName, int ieVer)
        {
            try
            {
                //For 64 bit Machine 
                if (Environment.Is64BitOperatingSystem)
                    Microsoft.Win32.Registry.SetValue(root + @"\Software\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION", appName, ieVer);
                else  //For 32 bit Machine 
                    Microsoft.Win32.Registry.SetValue(root + @"\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION", appName, ieVer);


            }
            catch (Exception)
            {
                // some config will hit access rights exceptions
                // this is why we try with both LOCAL_MACHINE and CURRENT_USER
            }
        } // End Sub FixBrowserVersion_Internal 

        public static int GetBrowserVersion()
        {
            // string strKeyPath = @"HKLM\SOFTWARE\Microsoft\Internet Explorer";
            string strKeyPath = @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer";
            string[] ls = new string[] { "svcVersion", "svcUpdateVersion", "Version", "W2kVersion" };

            int maxVer = 0;
            for (int i = 0; i < ls.Length; ++i)
            {
                object objVal = Microsoft.Win32.Registry.GetValue(strKeyPath, ls[i], "0");
                string strVal = System.Convert.ToString(objVal);
                if (strVal != null)
                {
                    int iPos = strVal.IndexOf('.');
                    if (iPos > 0)
                        strVal = strVal.Substring(0, iPos);

                    int res = 0;
                    if (int.TryParse(strVal, out res))
                        maxVer = Math.Max(maxVer, res);
                } // End if (strVal != null)

            } // Next i

            return maxVer;
        } // End Function GetBrowserVersion 


    }

```
This is how this class is used:

```
        static WebBrowser wb;
        static string browseResult;
        private void GoogleTranslate_Load(object sender, EventArgs e)
        {
            WebBrowserHelper.FixBrowserVersion();
            wb = new WebBrowser();
            wb.DocumentCompleted += wb_DocCompleated;
        }
```

2-	I read the translated text as a plain text, so many of old code that parses the tags is useless:

```
        static void wb_DocCompleated(object sender, EventArgs e)
        {
            var spans = wb.Document.GetElementsByTagName("span");
            foreach (HtmlElement span in spans)
            {
                if (span.GetAttribute("className") == "tlid-translation translation")
                {
                    browseResult = span.InnerText;
                    if (browseResult == null)
                        browseResult = "";
                    break;
                }
            }

        }
```

3-	The Browse function gets the result:
```
        private static string Browse(string url)
        {
            browseResult = null;
            wb.DocumentText = "";
            wb.Url = null;

            wb.ScriptErrorsSuppressed = true;
            wb.Url = new Uri(url);

            var T = DateTime.Now;
            while (browseResult == null)
            {
                Application.DoEvents();
                if ((DateTime.Now - T).TotalSeconds > 30)
                    browseResult = "";
            }

            return browseResult;
        }
```

the TranslateTextViaScreenScraping function should be modified to:

```
        public static string TranslateTextViaScreenScraping(string input, string languagePair, Encoding encoding, bool romanji)
        {
            string url = string.Format("https://translate.google.com/?hl=en&eotf=1&sl={0}&tl={1}&q={2}", languagePair.Substring(0, 2), languagePair.Substring(3), Utilities.UrlEncode(input));
            var result = Browse(url);
            var res = result.Replace("\r\n", "\n");
            res = res.Replace(SplitterString, ((char)0).ToString());
            res = res.Replace("\n", "\r\n");
            return res;
        }
```
I used the null char (ASCII 0) as a paragraph separator. I made some changes in your code to split paragraphs at this char.

Hope you find this useful and enhance the performance. Typically, the Application.DoEvents has heavy impact (all the timers in you app ticks because of it!) but without it the WebBrowser will not load the page!

**Comment by MohammadHamdyGhanem** [comment]
Not untill @niksedk approves this and releases a new beta. I have a modified bransf of SE with this new code and it works like a charm.

**Comment by MohammadHamdyGhanem** [comment]
I modified the Browse function to enhance its performance a little:
```
        private static string Browse(string url)
        {
            browseResult = null;
            wb.Url = null;

            wb.Url = new Uri(url);
            Application.DoEvents();

            var T = DateTime.Now;
            var T2 = T;
            while (browseResult == null)
            {
                var now = DateTime.Now;
                if ((now - T2).TotalMilliseconds > 250)
                {
                    Application.DoEvents();
                    if (_breakTranslation)
                        browseResult = "";

                    T2 = now;
                }

                if ((now - T).TotalSeconds > 30)
                    browseResult = "";
            }

            return browseResult;
        }
```

**Comment by madnesofjuice** [comment]
I hope he will approve. Thanks @MohammadHamdyGhanem

**Comment by KurtHofman** [comment]
@MohammadHamdyGhanem : Is it possible to clone your branch with the WebControl-fix ?

**Comment by maderios** [comment]
> _Is it possible to clone your branch with the WebControl-fix_
>
I think it's not a good idea. We don't need a fork, be patient :)

**Comment by BuluBurid** [comment]
> 
> 
> @KurtHofman
> I did many changes and missed many SE new features since I made my fork, and I didn't care about globalization in mine. This is why I come here to share new ideas, so that it can be added to SE. Anyway, you can download my Video And Subtitle Edit (VASE) executables from here, use the translation and save the file and reopen in your SE, until this problem is solved:
> http://www.mediafire.com/file/jjrqrfjw6j1jzh9/Video+And+Subtitle+Edit.zip
> Note: If a problem happens in translation, reopen exe as adminstrator so it can access the registery to make the WebBrowser use the latest IE on your PC.
> Hope it helps.

I will try it first.. Thanks before..

**Comment by madnesofjuice** [comment]
> @KurtHofman
> I did many changes and missed many SE new features since I made my fork, and I didn't care about globalization in mine. This is why I come here to share new ideas, so that it can be added to SE. Anyway, you can download my Video And Subtitle Edit (VASE) executables from here, use the translation and save the file and reopen in your SE, until this problem is solved:
> http://www.mediafire.com/file/jjrqrfjw6j1jzh9/Video+And+Subtitle+Edit.zip
> Note: If a problem happens in translation, reopen exe as adminstrator so it can access the registery to make the WebBrowser use the latest IE on your PC.
> Hope it helps.

So, Im trying to translate from english to romanian. Its not translating all lines and dont even translate.Im getting first half nothing and second half same text( not translated)

**Comment by svenverslype** [comment]
@MohammadHamdyGhanem
it is normal that it takes so long to translate

**Comment by MohammadHamdyGhanem** [comment]
@madnesofjuice
Google translate sometimes skips some lines, so I filled the missed lines with the original ones. Do you have a slow connection? I use 30 seconds as a timeout, and retry to translate 2 more times. 
I don't know why you have some empty lines. Maybe you have to select romanian language in the secong dropdown list, becuase I make it arabic by default (as I said I didn't make this fork global). Try it.
If the problem continues, try to translate a part of the subtitle in IE directly and see if it goes without any problems.

**Comment by BuluBurid** [comment]
> 
> So, Im trying to translate from english to romanian. Its not translating all lines and dont even translate.Im getting first half nothing and second half same text( not translated)

> 
> 
> @MohammadHamdyGhanem
> it is normal that it takes so long to translate
Yest I have try now and I have the same problem with @madnesofjuice and @svenverslype ..

But in my experiment, I have just found a better way to translated and fastest..
Just open the link that @niksedk give it here : https://www.nikse.dk/SubtitleEdit/Online
And then, please follow my instructions below carefully (already tested on my PC it worked 101% - See on attachment "SE_Beta#2")

- Click tab "Subtitle" then "Open" and browse it and open your subtitle file that you want to translated.
- Leave the tab "Frame rate & Code page" as default itself the click "Load subtitle" - wait it for a moment.
- Now the subtitle you choose is displayed, click on toolbar tab "Auto Translate" and click "Google translate".
- Next you choose what language to be translated. Don't click tab "OK" yet !!
- Before you click "OK", you have to **scrolling slowly** the result translated to make sure each time scrolling is displaying the correct translated from top untill the end _(If you directly click OK, the results will only show a little translation (the top) where the remainder of the next translation must remain in the original - See on attachment "SE_Beta#1")_.
- After you checking each line/paragraph is already correct translate, just scroll back / sliding untill to the first line then you may click "OK"
- Now you can see yourself the resut.. Or you can re-check to make sure it ..
- Next all you have to do is save it (on toolbar, choose "Subtitle - Save/download..." and select what extention you wish to save (default is SRT extention).
- Then click "Save/download" tab. and name it the file as you wish for.
- ------------------------ D O N E ... (^_*)/

(Thanks for @niksedk )

![se_beta 2](https://user-images.githubusercontent.com/45521212/49332942-40ed0a00-f5f1-11e8-97bc-8aa314521ac3.jpg)
![se_beta 1](https://user-images.githubusercontent.com/45521212/49332943-4185a080-f5f1-11e8-9c47-2946dca8cd4d.jpg)

**Comment by MohammadHamdyGhanem** [comment]
@madnesofjuice 
Try this: Right click on VASE exe and click Run AS Administrator. As I said, WebBrowser control will not work correctly unless updated to use the latest IE, and this needs permissions to access the  registry. But first, you must install Internet Explorer 11 or Edge on tour PC. 
By the way, I use Windows 7. I not sure about Win 10!
As I said this is a temp sol until the problem fixed.

**Comment by MohammadHamdyGhanem** [comment]
@BuluBurid
I tried it, but I got some errors, like translating only half of the file!
An advice: please use a decent picture for your profile.

**Comment by BuluBurid** [comment]
> 
> 
> @BuluBurid
> I tried it, but I got some errors, like translating only half of the file!
> An advice: please use a decent picture for your profile.

You said **_"I tried it, but I got some errors, like translating only half of the file!"_**, right ?
Didn't I said on my post **"Before you click "OK", you have to scrolling slowly the result translated to make sure each time scrolling is displaying the correct translated from top untill the end"**.

By the way .. About my profile picture, I think is no problem to anyone. Ive also used the same profile picture on my YouTube channel and Youtube itself does not prohibit using the profile picture.
Because the image matches my profile name and email address...

**Comment by svenverslype** [comment]
the remote server has returned an error 503 server is not available

**Comment by maderios** [comment]
@BuluBurid Your profile picture is an insult to women.

**Comment by BuluBurid** [comment]
> 
> 
> @BuluBurid Your profile picture is an insult to women.

FINE !! Then I'm OUT of HERE !!!
Kamsia & Thanks 4 ALL here !!
GOOD LUCK to find the better way than me ..!!
KALIAN MEMANG 101% BUNTAT BANAAARR...!!!
![ben s waluh](https://user-images.githubusercontent.com/45521212/49338904-f062c480-f663-11e8-9361-c0bc73bd0c35.gif)

**Comment by davc123** [comment]
i wish its work VASE this but is not any alternative software or are all fuckup with new google ?

**Comment by svenverslype** [comment]
@KurtHofman

Ik zie dat je van België bent ik ook. Lukt bij jou voor te vertalen met SE. Van mij niet.

**Comment by Noepie** [comment]
> @BuluBurid Your profile picture is an insult to women.

Maderios, It is not the avatar that is an insult to women, it is your reaction. You seemingly have mistakenly thought by seeing this picture.
There is nothing wrong with the avatar.

**Comment by KurtHofman** [comment]
@svenverslype : voorlopig werkt het nog niet ...

**Comment by KurtHofman** [comment]
@MohammadHamdyGhanem : I just checked and teh registry-entries are in place.

**Comment by svenverslype** [comment]
it also does not work via google without api key. he translates around 70 sentences and I get this the remote server has returned an error 503 server is not available

**Comment by b7398564** [comment]
Nice upgrades. I'll wait for the community's feedback.

**Comment by Maniac8888** [comment]
> it also does not work via google translator without api key in SE new version3.5.7 build 157 he translates around 70 sentences and I get this the remote server has returned an error 503 server is not available

After Microsoft decided to go to a "pay" model for Bing Translate (a service that used to be free), Google did the same thing. No surprise really. Don't hold your breath for a free Google batch capability anytime soon.

**Comment by eaglepie** [comment]
> @KurtHofman
> I did many changes and missed many SE new features since I made my fork, and I didn't care about globalization in mine. This is why I come here to share new ideas, so that it can be added to SE. Anyway, you can download my Video And Subtitle Edit (VASE) executables from here, use the translation and save the file and reopen in your SE, until this problem is solved:
> http://www.mediafire.com/file/jjrqrfjw6j1jzh9/Video+And+Subtitle+Edit.zip
> Note: If a problem happens in translation, reopen exe as adminstrator so it can access the registery to make the WebBrowser use the latest IE on your PC.
> Hope it helps.

hi ,buddy, could you add "Google translate url" to choose  in "Tools panel" ?because chinese mainland area can't open the url “translate.google.com” but only "translate.google.cn" ,
please...

**Comment by niksedk** [comment]
OK, while this can be made to work on some machines... it's seems too hackish - but a pluin is welcome :)

**Comment by MohammadHamdyGhanem** [comment]
@niksedk
I fixed my win 10 x64 machine and discovered the problem. It is related to WOW registry as the one I told you about VLC player. So, I fixed the code that upgrades the WebControl on the x64 systems, and now google translation works on win7, and win 10 both x32 and x64.
This is the modified part:
```
    public class WebBrowserHelper
    {
        public static int GetEmbVersion()
        {
            int ieVer = GetBrowserVersion();

            if (ieVer > 9)
                return ieVer * 1000 + 1;

            if (ieVer > 7)
                return ieVer * 1111;

            return 7000;
        } // End Function GetEmbVersion

        public static void FixBrowserVersion()
        {
            string appName = System.IO.Path.GetFileNameWithoutExtension(System.Reflection.Assembly.GetExecutingAssembly().Location);
            FixBrowserVersion(appName);
        }

        public static void FixBrowserVersion(string appName)
        {
            FixBrowserVersion(appName, GetEmbVersion());
        } // End Sub FixBrowserVersion

        // FixBrowserVersion("<YourAppName>", 9000);
        public static void FixBrowserVersion(string appName, int ieVer)
        {
            FixBrowserVersion_Internal("HKEY_LOCAL_MACHINE", appName + ".exe", ieVer);
            FixBrowserVersion_Internal("HKEY_CURRENT_USER", appName + ".exe", ieVer);
            FixBrowserVersion_Internal("HKEY_LOCAL_MACHINE", appName + ".vshost.exe", ieVer);
            FixBrowserVersion_Internal("HKEY_CURRENT_USER", appName + ".vshost.exe", ieVer);
        } // End Sub FixBrowserVersion 

        private static void FixBrowserVersion_Internal(string root, string appName, int ieVer)
        {
            try
            {
                //For 64 bit Machine 
                if (Environment.Is64BitOperatingSystem)
                    Microsoft.Win32.Registry.SetValue(root + @"\Software\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION", appName, ieVer);
                
                //For 32 bit Machine 
                    Microsoft.Win32.Registry.SetValue(root + @"\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION", appName, ieVer);

            }
            catch (Exception)
            {
                // some config will hit access rights exceptions
                // this is why we try with both LOCAL_MACHINE and CURRENT_USER
            }
        } // End Sub FixBrowserVersion_Internal 

        public static int GetBrowserVersion()
        {
            // string strKeyPath = @"HKLM\SOFTWARE\Microsoft\Internet Explorer";
            string strKeyPath = @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer";
            string[] ls = new string[] { "svcVersion", "svcUpdateVersion", "Version", "W2kVersion" };

            int maxVer = 0;
            for (int i = 0; i < ls.Length; ++i)
            {
                object objVal = Microsoft.Win32.Registry.GetValue(strKeyPath, ls[i], "0");
                string strVal = System.Convert.ToString(objVal);
                if (strVal != null)
                {
                    int iPos = strVal.IndexOf('.');
                    if (iPos > 0)
                        strVal = strVal.Substring(0, iPos);

                    int res = 0;
                    if (int.TryParse(strVal, out res))
                        maxVer = Math.Max(maxVer, res);
                } // End if (strVal != null)

            } // Next i

            return maxVer;
        } // End Function GetBrowserVersion 


    }

```
