### ISSUE TITLE
 Import Plain Text can use an update

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3214]
Hello,
I think Import Plain Text can use an update. It's been long since  a new feature was added to add. I would like to see the plain text broken into perfect captions. I use CaptionMaker to break the plain text and here's how their settings are. I think we should incorporate these into SE.

![sss](https://user-images.githubusercontent.com/28671050/49341467-8c45fd80-f66f-11e8-9ad5-58f37d108af0.jpg)

Side note: End of row with punctuation means a line break after ". ? !", etc.
Bottom-heavy means bottom line of the subtitle is bigger than the top line.

Thank you.

**Comment by darnn** [comment]
I'd second this. I currently just do a version of it myself with regular expressions, it looks sorta like this (in EditPad flavor regex):
(\.|\?|\!|") 
\1\r\n\r\n

^(.{60})(.{0,}?,) 
\1\2\r\n\r\n

^(.{60})(.{0,}?) (.{10,})
\1\2\r\n\r\n\3

And that's for one line that's approximately 60 characters long. But it would be nice to have specific options for it. Mine also creates text that can get kinda messy, for instance:

>MIKE: I'm looking at this burger right now, and I know only one
>way to do it.

as opposed to

>MIKE: I'm looking at this burger right now,
>and I know only one way to do it.

**Comment by uckthis** [comment]
@darnn CaptionMaker does the job. It breaks the text perfectly. I just want SE to be up to speed with it.

**Comment by uckthis** [comment]
@niksedk Latest beta is 100% better than the before. It still needs a few touches. New option " Auto break text after..." can be divided into two separate options. One: Auto break text after ( . ? ! ). Notice that I have only three of them, the sentence enders. New line when a sentence ends. A comma or ; or : is not a sentence ender, so it shouldn't be a part of it.
2nd Option: "Maximum characters per line." 
You have added good option, just make it two separate ones. 
Thank you.

**Comment by uckthis** [comment]
I noticed that too. It doesn't register the line breaks that are in the plain text. They should be line break and must not be over looked. 

and @darnn, I think you can create 50 length single line with CaptionMaker. Change your mode from captions to subtitles.

**Comment by darnn** [comment]
Thanks, but everything I try seems to have a limit of 12-50.

**Comment by uckthis** [comment]
Sorry, then.
Still better than 33, though.

**Comment by niksedk** [comment]
OK, how is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?

**Comment by uckthis** [comment]
Maybe it's me, but I don't get it. I don't get the Split at end char AT.... Why at? In CaptionMaker, Split at end char is a global setting. Which means that a line break will be placed after a . or ? or ! regardless of line length. A line length could be just 10 chars with a sentence ender inside and it will break that line.
Maximum number of char per line is an entirely different option. It just makes sure that the char limit is kept. As you can see here:

![49341467-8c45fd80-f66f-11e8-9ad5-58f37d108af0](https://user-images.githubusercontent.com/28671050/49680255-5c09bf00-fab4-11e8-995e-69f2c8f94049.jpg)

**Comment by niksedk** [comment]
@uckthis: It's for ending a line earlier to avoid endings like `... lorum ipsom. He` and `... lorum ipsum, and`.
Perhaps it should be hidden for UI or as @darnn suggest just a number... like `split [10] chars early if [.!?]` ?

Info: The Import uses the normal settings for max length:
![image](https://user-images.githubusercontent.com/1261331/49682799-cfaeca80-faba-11e8-84af-1d8efc8c4a57.png)

**Comment by niksedk** [comment]
@darnn: Is the issue with final parts of subtitles fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by uckthis** [comment]
Here is my issue:
![untitled](https://user-images.githubusercontent.com/28671050/49683018-e287c600-fadf-11e8-9f6d-bfef2f94c53f.jpg)

The first red arrow, line breaks after "We...". There was a period before it and it didn't break. I want an option where it breaks line after a period or ? or ! regardless of number of chars per line. 
Example: _Hi. How are you?  Good to see you!_
Should be:
_Hi.
How are you?
Good to see you! (New subtitle)_

Second red arrow. The word picture is missing, I think it's what @darnn  is complaining about.

Also, here is the same file when split with CaptionMaker. See how clean it is:

![fghfg](https://user-images.githubusercontent.com/28671050/49683079-e8ca7200-fae0-11e8-9327-cea5c836152e.jpg)

**Comment by darnn** [comment]
Oh yeah, I also always split at the ends of sentences even if they're short.

And it hasn't been fixed entirely (see lines 7-8):
![se-autosplit-4](https://user-images.githubusercontent.com/19672444/49683514-0c84bc80-facf-11e8-8a13-9e7ed725a282.png)

**Comment by niksedk** [comment]
OK, I've remove the end position % stuff is now removed - how is this: 
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ?

![image](https://user-images.githubusercontent.com/1261331/49686628-6bf6c280-faf7-11e8-8b9e-6e5c7e00dd15.png)

**Comment by LeonCheung** [comment]
Nice update, usually I have to manually add breaks after punctuations in notepad++ with regex, now it seems I needn't, which is really handy. Thanks! Since we are talking about this module, maybe #2737 can get change to be investigated as well? Basically, it is useful for handling with bilingual texts that are with no blank lines to be used as separator, which is really no good way to import so far.

**Comment by uckthis** [comment]
@niksedk Amazing. Brilliant. It generated about 518 lines with 32 chars per and only about ten are longer than 32 chars. I'm attaching the script file I used. Please import it and set Max length to 32 and see why some lines go over the 32 limit. I tried it 3 times and every time same lines went about limits. so...
The thing I want now is it to remember the last Max limit I set. It always shows 43 by default. Is it possible for it to remember the last value I entered? Or it can take the default value from SINGLE LINE LENGTH in General Settings.
A check/uncheck box before Split at end char would be nice, too.
Third request. and you can ignore it. it's not that important. Is it possible to use "Don't-break-after" list when importing text? Maybe it's an option that we can check or uncheck. 
[TSOL202 SCRIPT - EDIT.txt](https://github.com/SubtitleEdit/subtitleedit/files/2659729/TSOL202.SCRIPT.-.EDIT.txt)

**Comment by darnn** [comment]
Yeah, but the differenece is that I don't want it to always split on a comma, but only when it will make for two more evenly divided subtitles. Like, if I had something like:
`Blah blah  blah blah blah blah blah blah blah blah, then yes.`

Then I'd rather have it split to two subtitles like this:
`Blah blah  blah blah blah blah`
`blah blah blah blah, then yes.`

rather than to three like this:
`Blah blah  blah blah blah`
`blah blah blah blah blah,`
`then yes.`

but in the above example, it comes out to two subtitles either way, one is just divided more evenly with the comma.

**Comment by uckthis** [comment]
@darnn Okay. I never used this option in CaptionMaker, so I don't really know about it. In CaptionMaker it says break line after , IF APPLICABLE. If you can explain "IF APPLICABLE" in laymen terms to @niksedk, he would probably be able to code it.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

Issues with lines longer than max should fixed + issues with number-of-lines = 1 + added #2737

![image](https://user-images.githubusercontent.com/1261331/49690397-a7fa4980-fb30-11e8-8e87-f13c26c7ea69.png)

**Comment by darnn** [comment]
I see the addition, and it should be handy! But the problem I had remains:
![se-autosplit-7](https://user-images.githubusercontent.com/19672444/49691096-d9304500-fb43-11e8-8a68-3526149a9790.png)

With max number of lines set to 1, subtitles 2 and 4 are still get broken up into two lines.

**Comment by uckthis** [comment]
@niksedk Works for me. All I needed. Thanks a lot.

@darnn That's a you problem. I just ran my script with 1 line Max and 70 chars and not one line broke into two. Try removing the leading ... before and and see.

**Comment by LeonCheung** [comment]
@niksedk Cool fix. Thanks.

**Comment by darnn** [comment]
Same thing in build 159, I'm afraid:
![se-autosplit-8](https://user-images.githubusercontent.com/19672444/49695718-fa2a8180-fba7-11e8-8f05-2577bfccbd40.png)

**Comment by niksedk** [comment]
@darnn: Works fine here... don't really know why - could you attach your settings.xml file? 
![image](https://user-images.githubusercontent.com/1261331/49697393-2a2d5100-fbb7-11e8-8f6d-25f70e816f73.png)

**Comment by darnn** [comment]
Sure:
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/2660520/Settings.zip)

**Comment by niksedk** [comment]
@darnn: Very strange... beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip (added localization etc.)

**Comment by darnn** [comment]
Seems to work now! Thank you for putting in all this effort!
