### ISSUE TITLE
Fixing uppercase words in normal sentences

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#3215]
Would it be possible to have a functionality to fix these kind of subtitles? They are quite annoying to watch..

```
5
00:03:19,491 --> 00:03:23,495
THAT'S the fast train, the 4.33.
```

**Comment by OmrSi** [comment]
I think it would be hard, how would it differentiate between "THAT"S" and "DNA" for example?
One must be in uppercase, the other doesn't...

**Comment by Boulder08** [comment]
Of course, manual checking would be required but that would not be too hard to do by browsing the suggested lines to correct. There are already incorrect "fix missing spaces" corrections that often need that as well.

**Comment by OmrSi** [comment]
@niksedk Closed as well?
