### ISSUE TITLE
fresh installed SE 3.5.7  video player built in does not play at all /  VLC is greyed out tried 3 VLC Versions

### ISSUE THREAD

**Issue by firststeps59** [SubtitleEdit/subtitleedit#3218]
I installed hours ago SE 3.5.7 because i wanted to create Dutch subtitle from a German TV movie for a friend.
movie is codec H264 MPEG-4 AVC (part10)(avc1)    //  MPEG AAC Audio (mp4a)
Movie downloaded with fresh MediathekView

The SE built in Videoplayer does not play the movie and so i tried VLC
It is still greyed out
I tried 3 versions
64bit
32bit and the portable
All 3 downloaded at chip.de
What can i do that SE will pick a movie ?
I tried 10 different movies.

I hope there is somebody who is able to help me.

(Here I try to ad media info about the movie / taken from VLC)
<img width="292" alt="media info vlc" src="https://user-images.githubusercontent.com/45586337/49424739-c7dde600-f79b-11e8-9faf-9f316e19322b.PNG">

**Comment by niksedk** [comment]
If you install VLC 64 bit installer SE should be able to detect and use it: https://get.videolan.org/vlc/3.0.4/win64/vlc-3.0.4-win64.exe

If you want to use "Direct show" you probably should install LAV filters: https://github.com/Nevcairiel/LAVFilters/releases

"mpv" is also a nice video player - supports position in the video preview in SE.

**Comment by firststeps59** [comment]
Thanks,

I will have a try

**Comment by firststeps59** [comment]
I have to fill in the position (which is mented to be only necessary with VLC portable) of the VLC.exe,
 otherwise it does not work.

(See screenshot)
<img width="662" alt="media info 3 vlc" src="https://user-images.githubusercontent.com/45586337/49486499-f5c83680-f83e-11e8-8f6b-bfb8ce1710da.PNG">


### **Thanks 4 now**

**Comment by OmrSi** [comment]
MPV is much better, by the way.

**Comment by firststeps59** [comment]
Have i only to download the mpv payer?

Special download location needed or adviced ?

Already thanks 4 any answer !
