### ISSUE TITLE
Opening RTL .890 in 3.5.7 reverses panctuation marks.

### ISSUE THREAD

**Issue by assafperetz6** [SubtitleEdit/subtitleedit#3219]
When i open a .890 file (in hebrew, RTL), the panctuation marks are reversed, that is appear in the start of each line, instead of the end.
Clicking "reverse RTL start/end" does not fix it, but places the marks to the right of the next word instead of in the end of the line.
The same file opens correctly in version 3.5.2, and "reverse rtl" works there as it should.

I've tried to make a minimal example of .890 file with only one line, but it couldn't open it with 3.5.2 nor with 3.5.7. 

It might be related to [this commit](https://github.com/SubtitleEdit/subtitleedit/commit/686b02c6485e11a9637e80fb1e4fb540b2ab512f#diff-ec3213e666795f946ed9555b978628f0).

Thanks in advance.

**Comment by darnn** [comment]
Try three lines. SE seems to have some issues with subtitles with one/two lines in general.

**Comment by darnn** [comment]
Also, which program did you use to create the 890 file originally?

**Comment by assafperetz6** [comment]
I exported the file using SE as well. I've attached the test file.
opening it on 3.5.2 works perfectly, opening it on 3.5.7 not so much..

[TEST.zip](https://github.com/SubtitleEdit/subtitleedit/files/2643504/TEST.zip)

**Comment by darnn** [comment]
Huh, yeah, it certainly does look very different in 3.5.2.
