### ISSUE TITLE
3.5.7 build 163 - title changes into random string of numbers

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3223]
After working with built 163 for a while, I noticed that the window title changed from the filenames of the source and translation subtitles into a seemingly random string of numbers:
![se-numbers](https://user-images.githubusercontent.com/19672444/49703643-119d5500-fc10-11e8-852f-3974e9aa5548.png)

**Comment by darnn** [comment]
In fact, when I open a previously opened original+translation, and then open the video, change the video position and then play/pause the video, the number seems to grow.

**Comment by OmrSi** [comment]
@darnn While testing something for https://github.com/SubtitleEdit/subtitleedit/commit/6df51feab01dfd9e9e2d24126726e39d344d2550
I noticed that this only happens when using the "Toggle play/pause" shortcut and it returns to the usual name when you open and close the settings. :D

**Comment by darnn** [comment]
But I use it all the time! Doesn't everybody? Play, pause, translate a subtitle, repeat?

**Comment by OmrSi** [comment]
Of course, but most users just use "space" I guess, me included.
That's why no one has noticed until now...

**Comment by darnn** [comment]
I'm not sure what you mean. I have the keyboard shortcut for it set to ctrl+space, like it used to be back in Subtitle Workshop.

**Comment by OmrSi** [comment]
I mean use space when the focus isn't on the text box.
I just hear the whole line then translate it, the hear again with F5 then move to next.
Each one has his way, just saying maybe that's why people haven't noticed this.

I only mentioned when it happens to help. :D

**Comment by darnn** [comment]
Oh no, that's cool, I was just wondering how other people do it. I've gotten so used to it from years of using Subtitle Workshop, I wouldn't have thought there was any other way that made sense. That's how it goes, I guess. I gotta say, though, it's so great to not have to use SW. I could only use the version that came out in 2001 or so, because it had something that passed for RTL support, and it was buggy as hell (to the point of corrupting both your subtitle file and the backup sometimes, or looking like it was saving the file and not saving it) and couldn't do a tenth of the things SE does.

**Comment by OmrSi** [comment]
Oh, Yeah.
I tested it for a while then moved to SE and noticed the very big difference.
SW's support stopped a long time ago, yet some people insist on using it!
I guess the just got used to it.
I've always told a friend of mind that SE is better, he didn't believe it, now after he was forced to use it and asked me about some of its features, he was a 100% convinced that it's way, way better.

**Comment by niksedk** [comment]
thx :)
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Seems good now!
