### ISSUE TITLE
Import plain text auto split suggestion

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3230]
It would probably be a good idea to have a list of words that SE will not split lines/subtitles after, such as, in English, "Dr.", "Mr.", "Mrs.", "Ms." "Sr.", "Jr.", and others here: http://plato.algonquincollege.com/applications/guideToGrammar/?page_id=4498

**Comment by darnn** [comment]
Oh wait, this is just the NoBreakAfter list, huh. Well, it should be applied here as well.

**Comment by uckthis** [comment]
@darnn, Yes, I made this suggestion in #3214.

**Comment by niksedk** [comment]
I've tried use the NoBreakAfter list here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
How does that work for you?

**Comment by darnn** [comment]
This does seem to work, except the list appears to ignore entries like "i.e." or "a.m.".
