### ISSUE TITLE
Subtitle Edit 3.5.8 beta is Subtitle Edit 3.5.7 build 174

### ISSUE THREAD

**Issue by wintermuts** [SubtitleEdit/subtitleedit#3235]
Or I do not see it well?

**Comment by OmrSi** [comment]
There isn't a beta for 3.5.8 yet, there isn't even 3.5.8 yet...

**Comment by OmrSi** [comment]
It's only 3.5.7, he's saying he will release 3.5.8 but needs to work on the bugs in 3.5.7 first.

**Comment by OmrSi** [comment]
When 3.5.8 is out, you'll receive a notification to update. For now, you should close this and delete your comment.

**Comment by marb99** [comment]
This is because someone post on videohelp site and named Subtitle Edit 3.5.8 beta

**Comment by niksedk** [comment]
The Beta is just a "nightly build"... you could call it "3.5.8 beta" (but the version number might in theory be unknown). 
The last number after "3.5.7" (e.g. 174) is the number of commits since the 3.5.7 release.
