### ISSUE TITLE
Installed SE on laptop and many Errors

### ISSUE THREAD

**Issue by Hanzeeo** [SubtitleEdit/subtitleedit#3238]
Hello dear users,

For my X-Mas holiday i installed latest SE on my laptop (Win7-64) so i can work on titles on holiday adress, but when i open i get a lot of errors... I am not a programmer, just a user.

Does anybody has a clue what is going wrong?

I submitted a screenshot with the errorrapport.

Many Thanks in advance!

Hanzee

![problem message](https://user-images.githubusercontent.com/45465332/50006798-35192480-ffaf-11e8-9ccb-54e15adbe4f5.png)

**Comment by niksedk** [comment]
Could you try to install latest .net framework - 4.7.2 atm I think?

**Comment by Hanzeeo** [comment]
Thank you Nikolaj, i just tried, but it says my system in not compatible with that version. 
I saw in regedit that i have 4.0 now on the LT.

**Comment by Hanzeeo** [comment]
Maybe using an older SE for the LT? Would that be better?

**Comment by Hanzeeo** [comment]
> 
> 
> Could you try to install latest .net framework - 4.7.2 atm I think?

My laptop is 32 bit...

**Comment by niksedk** [comment]
Your system should surely be compatible with .net framework 4.7.2... https://support.microsoft.com/en-us/help/4054531/microsoft-net-framework-4-7-2-web-installer-for-windows

**Comment by niksedk** [comment]
Also, latest beta should not show this error... but you should still upgrade your .net version.
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip
