### ISSUE TITLE
[Bug] Auto break remove tags in lastest build

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#3239]
Auto break remove italic,, bold, underline tags

![1](https://user-images.githubusercontent.com/7856897/50015599-e1aed280-ffbe-11e8-888e-298529148b15.gif)

**Comment by OmrSi** [comment]
Did you compile it yourself or do you mean 189?

**Comment by marb99** [comment]
@OmrSi I compile my self, but you can download the lastest beta 191
