### ISSUE TITLE
Auto-break text - Multi Results!!!

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3241]
At current, auto-break text only gives you one result. Is it possible to have multiple results? Every time we hit auto-break, text is broken differently? 
For example, say I have a text: 
**_A B C_**
And Auto-text breaks it to:
**_A B
C_**
Is it possible to have a new result like:
**_A
B C_**
and so on? ( Of course keeping do-not-break-list in mind)
Thank you.

**Comment by OmrSi** [comment]
I don't know if that's possible, Auto-break has a set of rules to break the line, he would have to add another set to it and make it change between them?
I'm not the one to talk, I guess we will see.

**Comment by aaaxx** [comment]
[Somewhat related feature request.](https://github.com/SubtitleEdit/subtitleedit/issues/1380)
