### ISSUE TITLE
Fix common errors: Start with uppercase letter, fix alone lowercase 'i'

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3244]
1. For a subtitle like this:
`It was a roller coaster.`
`-but a different one.‎`
"Start with uppercase letter after paragraph/period" doesn't change "but" into "But", even though it's a new speaker, and the sentence should thus start with a capital letter.

2. For a subtitle like this:
`‎And I was... i just kept trying to find out,`
`what had happened to him.‎`
"Fix alone lowercase 'i'" doesn't change "i just kept" into "I just kept".
Edit: In fact, "start with uppercase letter" seems to ignore the ellipsis as well:
`What is...‎ hi, what's up?`
The "hi" isn't changed into "Hi".

**Comment by darnn** [comment]
Thank you!

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

Uppercase after ellipsis has not been added (except for "... i " for English) as uppercase is not always wanted.
