### ISSUE TITLE
[Feature Request/Slight Change] EDL Export - Option to have single lines placed on top line.

### ISSUE THREAD

**Issue by joedmartin** [SubtitleEdit/subtitleedit#3248]
Hello, 

I posted this request on the Release 3.5.8 #3229 page but realize that page was really meant for quick fixes (although this is a very small and simple change) so I am reposting it as its own request.

When creating subtitles I always stick to two line pairs like so:
![doubleline](https://user-images.githubusercontent.com/32495837/50176771-4bd0bb80-02ce-11e9-9af2-8d59878ee4a1.png)

When exporting subitles to EDL, single lines are always placed on the bottom-most line like so:
![singleline](https://user-images.githubusercontent.com/32495837/50176677-090ee380-02ce-11e9-8603-5d347387e441.png)

I have not been able to find a way around this (I've dug through all the settings with no luck and tried simply placing a blank line below the single line but blank lines are automatically removed).

It would be incredibly helpful and appreciated if there could be a option to place these single lines on the top line or to disable the automatic removal of blank lines.

Thanks!

**Comment by niksedk** [comment]
OK, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

How does this work:
![image](https://user-images.githubusercontent.com/1261331/50372006-5dfc7380-05c6-11e9-9538-9a849eebba0c.png)

(not much about image rendering is simple...)

**Comment by joedmartin** [comment]
Thank you so much!
Sorry if I came off in a bad way, I just genuinely thought it was a simple fix. 
Thank you for your work though, it's greatly appreciated!

**Comment by niksedk** [comment]
np - can you confirm it works?

**Comment by joedmartin** [comment]
Yes, can confirm it is working perfectly!

Thanks again!
