### ISSUE TITLE
fix error in subtitle Edit 3.57

### ISSUE THREAD

**Issue by asadghazanfary** [SubtitleEdit/subtitleedit#3250]
how can i fix this error?
please help me
![capture](https://user-images.githubusercontent.com/5650939/50345161-4cbe5300-0543-11e9-9cef-f445021a89ad.PNG)

**Comment by mkver** [comment]
You probably can't fix this error, but you can help others do it by explaining a bit more about what you were doing before you encountered this crash. Is it reproducible (i.e. does it always happen when you perform certain actions?)? Is it still reproducible with 3.5.8?

**Comment by asadghazanfary** [comment]
i don't have waveform section waveform As you can see in the picture.

i used subtitleEdit 3.5.8 and but when this error happened i decided use 3.5.7 but this error is still displayed

**Comment by niksedk** [comment]
Perhaps upload the subtitle and info about line number that makes it crash?

**Comment by asadghazanfary** [comment]
I used to work normally with this software, this error occurred

**Comment by niksedk** [comment]
It's probably due to the subtitle - could you upload or email it ?
