### ISSUE TITLE
SubtitleEdit 3.58 crashes importing .sup file

### ISSUE THREAD

**Issue by spetragl** [SubtitleEdit/subtitleedit#3251]
I imported a .sup file in SubtitleEdit v3.58 and it crashes on export.
Just for grins I also tried v3.57 and it works fine.
See attached .sup file I used.

Thanks

[Frosty.The.Snowman sup.zip](https://github.com/SubtitleEdit/subtitleedit/files/2703017/Frosty.The.Snowman.sup.zip)

**Comment by niksedk** [comment]
thx - yes, SE 3.5.8 seems to crash on empty images... fixed here I hope: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by spetragl** [comment]
Sorry that didn't work.
Here's the long error screen (attached) if that helps.

![subtitleedit3 5 8crash](https://user-images.githubusercontent.com/10930266/50351668-e7ea0500-0510-11e9-96c0-74a5d0cd18b1.jpg)

**Comment by niksedk** [comment]
thx for the screenshot too - beta updated again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
I think you got a bad SUP file...

**Comment by spetragl** [comment]
How do we make SubtitleEdit create it correctly?

**Comment by niksedk** [comment]
Nice :)
