### ISSUE TITLE
Batch convert 3.5.8 seems to be broken

### ISSUE THREAD

**Issue by danstraughn** [SubtitleEdit/subtitleedit#3252]
Batch converting sub or sup files results in one line srt files and then marks as complete and moves on.  Seems to wonky.

**Comment by niksedk** [comment]
thx for the info :)
Hopefully now fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by danstraughn** [comment]
Thank you! Will give it a shot!
