### ISSUE TITLE
Subtitle Edit 3.5.8 is misconfigured

### ISSUE THREAD

**Issue by gwt10** [SubtitleEdit/subtitleedit#3256]
I just updated to 3.5.8 and I get this ridiculous screen box in OCR that goes letter by letter (Manual image to text) instead of the old way of reading each sentence line by line. Is there any way to turn this off and go back to the old way?

**Comment by gwt1** [comment]
I have a new account now.  Since drag and drop doesn't work, here is a link as to what I'm seeing

https://imgur.com/a/BUItgxG

**Comment by niksedk** [comment]
SE can use different "OCR engines"... red more here: https://nikse.dk/SubtitleEdit/Help#importvobsub
