### ISSUE TITLE
System: The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by NexusMK** [SubtitleEdit/subtitleedit#3257]
Hello,

I have an issue regarding the new google translate change and was wondering if anyone can help.
I get the following message when trying to translate something : "System: The remote server returned an error: (403) Forbidden." (https://gyazo.com/cf1445b00e233fd85d8002c1bb4e406a)

I have activated the 12-month trial period for the Google API key and entered it in the settings part of the program, but I still get this message.
I've tried googling around and someone somewhere indicated that it may be a problem with the restrictions of the key since I've left the key unrestricted. (https://gyazo.com/c0e7d1cd1123f308efa408f0225ac2e3)

I've tried restricting it to my IP (application restriction),  to Google Cloud APIs ( API restrictions) and the combination of both, but still to no avail.
If this part is indeed the error, would someone who knows how to properly manage the restrictions help me?
If not, does anyone know what settings I need to reconfigure to make this work?

Just for a bit of an extra info, tried this on 3 different PCs, on 3 different networks and with 3 different internet providers, the error is still the same (all of them running Windows 10 with latest updates).

Thanks.

**Comment by niksedk** [comment]
You need to setup billing... see more info here: https://nikse.dk/SubtitleEdit/Help#translation

**Comment by albino1** [comment]
I had this same problem.  I had everything setup, including Billing, and it was still just giving me the 403 Forbidden error every time.  To get it to work I had to go to the API Library page and Enable the Cloud Translation API:

https://console.cloud.google.com/apis/library

After that it seems to work flawlessly.
