### ISSUE TITLE
waveform

### ISSUE THREAD

**Issue by Jyaelev** [SubtitleEdit/subtitleedit#3258]
Hi,

i just installed the new version, and now my waveform have "basically" disappear... they seem to be all crunched up on the right side!

[capture](https://user-images.githubusercontent.com/45567434/50477508-f894f200-09cc-11e9-8477-17c8f761562b.PNG)

How can I get the waveform back???

thank you!

JYLevin

**Comment by niksedk** [comment]
Do you get the waveform with 3.5.7?
If no, then try using FFmpeg for generating the waveform - see Options -> Settings -> Waveform
Alternately, you can try converting the video file to mp4 with e.g. handbrake.

**Comment by Jyaelev** [comment]
Hi,
I've been using SE for some years, and I always have the waveform.
Actually I just opened a file on which I worked earlier this week with 3.5.7, and now with 3.5.8 I lost the waveform...

**Comment by niksedk** [comment]
Could you email/post a link to a video file that does not work?

**Comment by Jyaelev** [comment]
I have to go to a meeting, but I thinkg that converting the file may fixe it.
I was talking about an .m2ts file (which I used earlier this week as mentioned, to create the original .srt file)
but I just opened an .mpg file and the wavefome is fine.
i'll try converting when I get back. T
Thank you so much for your prompt reply...

**Comment by Jyaelev** [comment]
I converted the file to .mpg and it worked, but what I don't understand is that I originally started the subtitle file with the .m2ts video file...
anyway, thanks for your help!
