### ISSUE TITLE
Auto Break issue

### ISSUE THREAD

**Issue by borifax** [SubtitleEdit/subtitleedit#3259]
I noticed a certain inconvenience. If the text in the line is quite long, after the use of the "Auto break" function, the final tag is deleted.
Similarly, after using "Splite long lines ..." in Tools, the final tag disappears.

Is there any way to force line breaks after the first comma that appears after a defined number of characters?

**Comment by niksedk** [comment]
@borifax: This was a problem in one of the beta version... what version of SE are you using?

**Comment by borifax** [comment]
3.5.7 b.201

**Comment by OmrSi** [comment]
It was fixed here https://github.com/SubtitleEdit/subtitleedit/commit/4b345238489d7728e903cf1a7372db3103476e72 and is fixed in 3.5.8

**Comment by borifax** [comment]
Indeed, in version 3.5.8, the problem of removing tags in long lines does not occur.

In "Split long lines ..." there is the function "Line continuation begin / end strings". Could someone explain to me how it works. I tried to choose all the options in it, but I don't see any difference.

**Comment by borifax** [comment]
Indeed, in version 3.5.8, the problem of removing tags in long lines does not occur.

**Comment by marb99** [comment]
@OmrSi  you need to close and open SE again to work, 

niksedk try to fix it for work without restarting here [#457fc77](https://github.com/SubtitleEdit/subtitleedit/commit/457fc774621e31dffd8c5eeebe548336c67a8060) but still need restart to work

![1](https://user-images.githubusercontent.com/7856897/50541097-3729d880-0b96-11e9-9018-655c97de81af.gif)

**Comment by marb99** [comment]
@OmrSi yes, but not work for long lines

**Comment by OmrSi** [comment]
it's ok, I just want it to not break after one word of a comma or dot. :D

Though auto-break should automatically break at a comma or dot or ? or !, but it's not, for some reason so I thought this is the best next thing to do.

Well, I guess this is closed.

@borifax You only can choose what it can't break after.

**Comment by borifax** [comment]
I would add to break:
1) - \ s [A-ZĄĆĘŁŃÓŻŹ]
2) after the dot
3) after the comma
And probably a lot more.  ;)

**Comment by borifax** [comment]
A bit off topic.
Is there a "systemic" way to make "?" and "!" appearing at the end of the line were not preceded by a space?

https://i.imgur.com/c1boDkO.png

**Comment by OmrSi** [comment]
@borifax You mean delete the space before them? Try Fix common errors' remove unneeded spaces.

**Comment by borifax** [comment]
Yes, I know it.
I'm more interested in improving these errors "on the run", when extracting subtitles from a .ts file.

**Comment by niksedk** [comment]
Actually, it seems that the final 3.5.8 do have some issues with missing tags after "Auto Break" :(
https://forum.titlovi.com/sinhronizacija-prevoda-subtitle-edit_t35680_n7.html
So a text like `Zato nikada necemo razumjeti pjesmu <i>Louie Louie</i>.` gives problems - it's not very often it happens but it's pretty annoying!

It's fixed in latest beta... but probably a new release a bit sooner than march!

**Comment by OmrSi** [comment]
@niksedk You made many changes in this period and added bookmarking and autosave, I those are more than enough in my opinion. Especially Bookmarking. :)
I wanted to mention autosave before the current version but I thought you had enough on your plate. 😅
