### ISSUE TITLE
DOESNT WORK TRANSLATION "API QUOTA EXCEED"

### ISSUE THREAD

**Issue by dequinha** [SubtitleEdit/subtitleedit#3260]
THE FIRST 3.5.8 ASKED THE API KEY BUT AT LEAST LET TRANSLATE WITHOUT.
 "NOW SAY API QUOTTA EXCEED OR SOMETHING"

WTF

**Comment by niksedk** [comment]
https://www.nikse.dk/SubtitleEdit/Help#translation
