### ISSUE TITLE
[Bug] Settings are reset on every app launch

### ISSUE THREAD

**Issue by eugenesvk** [SubtitleEdit/subtitleedit#3261]
SubtitleEdit can't seem to remember settings after I exit the app and start it again. After I do any changes in the app (e.g. remove a toolbar item, change video player, font, shortcuts, etc.) the `Settings.xml` file is updated. However, when I restart the app, all the changes are lost. Strangely enough, the `Settings.xml` file still has all of the changes, but the app simply doesn't "read" them, it reverts to all the defaults, and when I exit the app the second time, only then all the `Settings.xml` is reverted to the default version.

I've tried different app types (portable, beta, installed) and versions (3.5.8, 3.5.7 and a few older ones), but the issue remains and no persistent changes are possible.

Any idea why that is and how it can be fixed? Thanks!

OS: 10.0.17763
SubtitleEdit version: 3.5.8

**Comment by niksedk** [comment]
Do not install the portable version to C;\Program files\<something> as these folders are write protected.
Removing everything SE and do a clean install perhaps...

If it still fails, where did you put SE and are you running portable version or installer version? 
What happens if you install the portable version to something like C:\Tools\SE?
Could you attach a version of `Settings.xml` with your changes?

Go to Spell check -> Get Dictionaries -> "Open dictionaries folder" to see which folder SE thinks is the "base" folder (that would be nice to know too).

**Comment by eugenesvk** [comment]
> Do not install the portable version to C;\Program files<something> as these folders are write protected

I didn't, it's placed in a non-protected folder, and as I mentioned, the SE **IS** able to write to the settings file, I can see the changes in a text editor as soon as I change the settings. The issue is that these changes are not READ once I launch SE again

>are you running portable version or installer version

I've tried both portable and installer versions, the installer version uses a different settings file in %Appdata% folder, it can change said file, but can't read it

> where did you put SE 

Tried different folders on my main drive C, no difference. I simply unpack the **SE358.zip** file to a folder (so it's a clean portable install) and nothing changes, SE can change the settings file, but can't read it back on a new launch

> Could you attach a version of Settings.xml with your changes?

Here you go, I unpacked to a new folder `C:\Tools\SE358`, opened SE, removed 3 toolbar buttons, quit SE and attached the settings file (when I launch SE again, the toolbar buttons are back even though the settings file still has them as **false**)
The "base" folder is `C:\Tools\SE358\Dictionaries`
https://gist.github.com/eugenesvk/5647a441b276dd16fab7dbd8bf1d39b6

**Comment by niksedk** [comment]
@eugenesvk: thx for the info and file - I cannot re-produce the error, but I've made a debug build here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/DebugFiles.zip

Could unpack the files to `C:\Tools\SE358\Dictionaries` and try again? 
Hopefully it should create an `error_log.txt` with more info.

**Comment by eugenesvk** [comment]
> Hopefully it should create an `error_log.txt` with more info.

Thanks for you help figuring out the issue!
Yep, it did produce an error log, here it is
https://gist.github.com/eugenesvk/f48aa44e8784eefbb8785e254481940e

I don't know what this refers to `C:\Data\SubtitleEdit\subtitleedit\libse\Settings.cs:line 1634`, there is no such folder/file on my PC

**Comment by niksedk** [comment]
Thx for the info - could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip ?

The error was in this line: https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/Settings.cs#L1632
Some culture info was missing I think: a `CultureInfo.InvariantCulture` parameter for `Convert.ToInt32`... I hope.

**Comment by eugenesvk** [comment]
Thank you, it's working now!

**Comment by niksedk** [comment]
thx for verifying :)
