### ISSUE TITLE
Support Position on Netflix's TTML v2 (Used in Image Based Substitles)

### ISSUE THREAD

**Issue by MPThLee** [SubtitleEdit/subtitleedit#3265]
Format looks like
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:ns2="http://www.w3.org/ns/ttml#styling" xmlns:ns3="http://www.netflix.com/ns/ttml#metadata" xmlns:ns4="http://www.w3.org/ns/ttml#parameter" xml:lang="zh-Hant" ns4:timeBase="media" ns4:version="2" ns2:extent="1920px 1080px">
    <head>
        <metadata ns3:schemaVersion="0" ns3:packageId="1183538" ns3:movieId="80049212" ns3:uuid="a2f759a2-1a41-4be1-85a6-91bd9f9dde4f" ns3:textType="SUBS"/>
    </head>
    <body>
        <div ns2:extent="642px 71px" ns2:origin="637px 894px" begin="00:00:06.473" end="00:00:10.443">
            <image src="1.png"/>
        </div>
        <div ns2:extent="518px 71px" ns2:origin="701px 892px" begin="00:00:10.577" end="00:00:14.347">
            <image src="2.png"/>
        </div>
    </body>
</tt>
```
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:ns2="http://www.w3.org/ns/ttml#styling" xmlns:ns3="http://www.netflix.com/ns/ttml#metadata" xmlns:ns4="http://www.w3.org/ns/ttml#parameter" xml:lang="ja" ns4:timeBase="media" ns4:version="2" ns2:extent="1920px 1080px">
    <head>
        <metadata ns3:schemaVersion="0" ns3:packageId="1456428" ns3:movieId="81010670" ns3:uuid="3733b360-a414-4708-9894-76ca63608b79" ns3:textType="CC"/>
    </head>
    <body>
        <div ns2:extent="315px 70px" ns2:origin="802px 845px" begin="00:00:01.626" end="00:00:04.879">
            <image src="1.png"/>
        </div>
    </body>
</tt>

```

It works fine expect some features when you extract zip and open `manifest_ttml2.xml` in subtitle edit.

Related: #2061 But, This issue is more technical.

The problem is **Position**(maybe more). because of custom namespace(s).

In `TimedTextImage.cs`, There's not position support implemented.
Normally, It's ok. but like [Japanese subtitles](https://medium.com/netflix-techblog/implementing-japanese-subtitles-on-netflix-c165fbe61989), Vertical subtitles are used. which will placed in middle-bottom of video when postion is not supported.

This format is now on East Asia(Chinese, Japanese, Korean), Greek, Hebrew languages, and maybe more.

See Also: [Implementing Japanese Subtitles on Netflix](https://medium.com/netflix-techblog/implementing-japanese-subtitles-on-netflix-c165fbe61989)

---
Sorry about my bad english.
Edit 1: Little explain about/with Japanese subtitles.

**Comment by niksedk** [comment]
I'm not sure what the problem is... the format above can be loaded be SE.

**Comment by MPThLee** [comment]
Position of subtitle is not working. due to custom namespace. (like `ns2:extent`).
