### ISSUE TITLE
Video shows original as well as edited subs?

### ISSUE THREAD

**Issue by Zixim** [SubtitleEdit/subtitleedit#3268]
I guess i must have clicked something without knowing what would happen,
the video is displaying 2 subtitles : first the original, and below that the edited by me line.

Can I turn this off somewhere?

**Comment by borifax** [comment]
Hehe, tell me what you did, that you have this effect. I need something like that.
Sometimes I also have double subtitles like yours, but they are identical - those from SE, not from the source file.

**Comment by niksedk** [comment]
Perhaps a screenshot? 
Also, what video player do you use inside SE (see options -> settings -> video player). 
If you using directshow, do you have VobSub 2.23 or some other subtitle filter installed?

**Comment by Zixim** [comment]
![image](https://user-images.githubusercontent.com/7814664/50612910-0fab7680-0edc-11e9-992e-1ce71bc34679.png)

![image](https://user-images.githubusercontent.com/7814664/50612949-37024380-0edc-11e9-978d-a143ea292fe9.png)

reg vobsub, not that i know of ? Where would i verify ?

**Comment by OmrSi** [comment]
I think there might be a subtitle file with the video file already, try using MPV as the video player and see if the issue persists.

This happens in MPV as well, but the other subtitle that is merged with the video disappears as soon as you add a line to the file.

**Comment by Zixim** [comment]
There is no embedded subtitle track in the MKV container.
![image](https://user-images.githubusercontent.com/7814664/50633638-55078c80-0f4c-11e9-9a2f-23ffe170a0df.png)

I also checked for burned-in subs, none.

MPV does not have the issue at all, regardless of adding a line or not.

**Comment by niksedk** [comment]
OK, so I guess you have a directshow filter installed (like VobSub 2.23 / VS-filter / xy-VSFilter).

**Comment by Zixim** [comment]
how can i check for this ?

**Comment by niksedk** [comment]
Nice you solved it :)
What program did you use? (perhaps others will find it useful too)

**Comment by Zixim** [comment]
Something that dates back to 2005, so user beware...
https://www.videohelp.com/software/DirectShow-Filter-Manager
