### ISSUE TITLE
[Feature Suggestion] "Open Next File"

### ISSUE THREAD

**Issue by vassilyzaitsev** [SubtitleEdit/subtitleedit#3270]
I think it would be great if Subtitle Edit had this button/command or even just a keyboard shortcut to open the next or previous subtitle file on folder. I was about to do something on AHK but I figured, maybe someone else needs that too... Anyway... o/

Edit: This is what I'm dealing with https://i.postimg.cc/MGn1H13Z/SubPrint.jpg

**Comment by vassilyzaitsev** [comment]
@OmrSi would you mind explaining why do you think it's not a good idea?

**Comment by OmrSi** [comment]
I don't think it's really a wanted feature, opening a file in the same folder only takes two clicks and doesn't happen a lot on my experience, anyway, I just wanted to show my opinion, which is not the one that matters, and a thumbs down was the easiest way. 😅😅
