### ISSUE TITLE
VLC on win 64 bit

### ISSUE THREAD

**Issue by ghost** [SubtitleEdit/subtitleedit#3271]
SE can't detect VLC 32 bit on win 64 bit. I had to setup VLC 64 bit to be detected. This happens because 32 bit apps keys are registered in wow64 section. This can be solving by searching for the keys in two places if SE works on win 64.
More details:
https://docs.microsoft.com/en-us/windows/desktop/sysinfo/32-bit-and-64-bit-application-data-in-the-registry

**Comment by MohammadHamdyGhanem** [comment]
https://docs.microsoft.com/en-us/windows/desktop/winprog64/shared-registry-keys

**Comment by niksedk** [comment]
Using VLC for... video player or waveform generation?

**Comment by MohammadHamdyGhanem** [comment]
Video player
