### ISSUE TITLE
DVD Studio Pro STL - Tag Conversion

### ISSUE THREAD

**Issue by Shas2509** [SubtitleEdit/subtitleedit#3272]
Hi,

there are some issues with Tag Conversions in DVD Studio Pro .STL files, probably other STL Formats, too.

Some DVD Pro Studio Tags e.g.:
$Bold = True  /  $Bold = False
$Underlined = True /  $Underlined = False
$Italic = True /  $Italic = False

are not converted, when present in a  STL file, they are ignored.
Basically they work like the alignment tags, in that they need to be written before the lines they affect with true, and after the lines they affect with false. They could work as read only conversions, because there are also the tags ^U and ^B, which would convert more smoothly to the SRT equivalents.
However, just like ^I, they need to be paired per line, so there needs to be a start tag and an end tag per line.

If this could be fixed in some future update, it would be great! :)

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip ?
