### ISSUE TITLE
cl

### ISSUE THREAD

**Issue by emperor01x** [SubtitleEdit/subtitleedit#3273]
Auto Min. line height (split) values for English aren't compatible with Arabic which needs 37, 40, 50 and sometimes 60 or rarely 70, could you please add and option to select the range of the auto values?

**Comment by niksedk** [comment]
I don't understand your problem exactly... could you explain in more detail what does not work? Screenshots/subs always help.

It's possible to set min line height:
![image](https://user-images.githubusercontent.com/1261331/50659758-c6236000-0f9d-11e9-85f9-1e52ccac4c91.png)

**Comment by emperor01x** [comment]
Thanks for replay.
an example 
![screenshot_1](https://user-images.githubusercontent.com/46071860/50660030-1357ff80-0fa7-11e9-8274-6f99deca7050.png)
to ocr it right you should change Min. line height (split)
to 40 or 50
but auto don't ocr it right and select "ء" like in the example or the dots not the words.

**Comment by emperor01x** [comment]
also you can try it by yourself, it should work and OCR the word successfully without problems like the example. but you change the Min. line height (split) in another words like 37 or 50 or 60 and it works, so what i need from you is to make the auto in the range of from 30 to 60 to OCR this successfully without problems. and here the subs
https://mega.nz/#!2roSgC7Y!MoOjpO860l7px5zDq84L95tAVird9Lib3Tez_v6dBuU

**Comment by emperor01x** [comment]
It worked perfectly. thank you <3

**Comment by emperor01x** [comment]
Sorry about urgency and closing the issue.
There's a special case there
![screenshot_1](https://user-images.githubusercontent.com/46071860/50727258-2393ea00-1121-11e9-96e3-ba6abe39e5d0.png)
When you put the Min line height 40 it works neither when you put it auto

**Comment by emperor01x** [comment]
And there's another case here, when you put the Min. line height (split) to Auto it doesn't work and if you put it 40 too it won't work
![screenshot_1](https://user-images.githubusercontent.com/46071860/50727356-833ec500-1122-11e9-80e3-6edb7fe61789.png)
 so you should put it 50 to work like this
![screenshot_2](https://user-images.githubusercontent.com/46071860/50727371-b97c4480-1122-11e9-8dad-e4a7b3ad96a0.png)

**Comment by emperor01x** [comment]
@MounaLafi
Yes, Maybe but if @nikse set the vaule from 30 to 60 it would be better because of the special cases

**Comment by borifax** [comment]
For me, sometimes a similar error occurs.
Why do not I see the option "Min. Line height (splite)"?

![image](https://user-images.githubusercontent.com/45988475/50737428-67422e80-11c9-11e9-85d7-ec25fd5fa673.png)
