### ISSUE TITLE
Regex question

### ISSUE THREAD

**Issue by teodargent** [SubtitleEdit/subtitleedit#3274]
I'm trying to make a regex to fix some OCR errors. I need to replace the uppercase "i" with a lowercase "l" if the "i" is not at the begining of the sentence and it is followed by vowel or a ' and a word boundary. This is what I came up with: `(?<=[^\.|\!||\-|\?]\s)I(?=[a|e|i|o|u|']\b)`. 
It works in regex101 but has issue in SubtitleEdit.
In the phrase:
"Aspetta per attaccare e massacrare
Ie loro famiglie."
It matches the uppercase "i" in the word "Ie" but it fails to replace the match with the lower case "l".

In the phrase.
"Ci sono persone preoccupate per te.
Io sono preoccupato per te."
It matches the uppercase "i" in the word "Io" but it shouldn't (in regex101 it doesn't match). 

What am I doing wrong?
`

**Comment by teodargent** [comment]
That works, thanks! I did some testing and this came up:
![image](https://user-images.githubusercontent.com/20757457/50705028-b6695180-1059-11e9-9375-8dce6cbd48d0.png)
Hopefully someone can explain this.

**Comment by OmrSi** [comment]
@niksedk Could you take a look at this? is it intentional?
