### ISSUE TITLE
[Bug] pasting in translator's mode

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3277]
The text box is grayed out when pasting a sentence from another file then renumbering:
![screenshot 64](https://user-images.githubusercontent.com/20923700/50711087-a52e3e00-1075-11e9-8534-f30016a3af15.png)

After renumbering:
![screenshot 65](https://user-images.githubusercontent.com/20923700/50711121-cabb4780-1075-11e9-9e6a-b64db8fb18cf.png)

After restarting SE:
![screenshot 66](https://user-images.githubusercontent.com/20923700/50711153-e6bee900-1075-11e9-80ae-ea016ecf38c3.png)

Also, notice the position of the "Total length:" which is left 14 like the line before it.

On an unrelated matter, I think these two are closed https://github.com/SubtitleEdit/subtitleedit/issues/2467 https://github.com/SubtitleEdit/subtitleedit/issues/696

**Comment by niksedk** [comment]
thx :)
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip  ?

**Comment by OmrSi** [comment]
Perfect, as usual, you can close it with the commit. :D

Also, I tested the cases mentioned here and they all work, it should be closed https://github.com/SubtitleEdit/subtitleedit/issues/2169
And I wrote the solution to this issue, so it might also be closed https://github.com/SubtitleEdit/subtitleedit/issues/2762

**Comment by niksedk** [comment]
thx :)
