### ISSUE TITLE
[Minor request] split at cursor/video position for original

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3278]
Could you make it work on the original subtitle as well?
Sometimes when I'm translating, I want to split the line based on the text in the original subtitle, after a certain word, but split at cursor/video position isn't working in the text box of the original subtitle.

EDIT: if it's hard because it makes a problem with the translation in the left text box, you should just close this.
EDIT2: It already works if you use a right mouse click in the Original's text box, I just want the shortcut to work too...

**Comment by LeonCheung** [comment]
Do you mean something like #3030 ?

**Comment by OmrSi** [comment]
Not quite. Split at cursor/video position in the original text box already works when using it from the right-click context menu, only the shortcut doesn't work there.
I'm not requesting anything new, just to make the shortcut work there too.

**Comment by OmrSi** [comment]
@niksedk Can you do this last one for me? ^_^

**Comment by OmrSi** [comment]
Thank you so much!

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Perfect. <3
Thanks. :)
