### ISSUE TITLE
A bug that deletes eng_OCRFixReplaceList

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#3280]
I mention this to Nikse by email 4 years ago.

I don't extract subtitles from vob files much but when i do i get this error again, same as 4 years ago. Since then, I always load up eng_OCRFixReplaceList using notepad++ just in case.

The problem is when i extract subtitles from vob files it automatically use files to fix errors as it goes through the subtitle file. When it finished, notepad would ask to reload eng_OCRFixReplaceList_User and/or en_GB_user and they both get updated correctly. Sometimes it would ask to reload eng_OCRFixReplaceList and the data all gone and replaced with a exact copy of eng_OCRFixReplaceList_User. Since i opened by eng_OCRFixReplaceList file in advance i can say no to reload.

IS anyone else having this problem?

**Comment by niksedk** [comment]
Sorry, I've never seen that... and I add words to OCR lists often.
Just now I've tested all add buttons I could find + looked through the source code - all looks good. 

Could still be a bug though, so if you find steps to re-create this please share.

**Comment by Ding-adong** [comment]
I tried to recreate the bug but to no avail. Ticked a box at a time and in all known combinations and nothing. It happened rarely and why, I don't know.

**Comment by niksedk** [comment]
OK, I guess I'll close this for now, but if you see this again (hopefully something re-creatable) do post again :)

**Comment by Ding-adong** [comment]
HI

What flavour regex engine are you using?

cheers
