### ISSUE TITLE
SE crashes after pressing Start OCR

### ISSUE THREAD

**Issue by borifax** [SubtitleEdit/subtitleedit#3283]
I downloaded SE358PL, after selecting Tesseract 3.02 and pressing Start OCR begins to happen what you can see in the picture below.
![image](https://user-images.githubusercontent.com/45988475/50764172-3538d700-1272-11e9-9d76-e848674c178b.png)

**Comment by OmrSi** [comment]
Try the latest Beta maybe, some OCR crashes were fixed.

**Comment by niksedk** [comment]
Could you translate the Polish? 
Looks like a confirmation... not a crash.

**Comment by diomed** [comment]
"The publisher could not be verified"

**Comment by niksedk** [comment]
@diomed: thx :)

So, you just need to trust... SE does come with a certificate (as that's very expensive)
