### ISSUE TITLE
[Bug] Multiple replace (test file attached)

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3288]
If you add something to multiple replace then invert selection and click ok, it replaces everything and shows replace count is 0:
![screenshot 74](https://user-images.githubusercontent.com/20923700/50944173-11ef7100-1498-11e9-8343-f7864986c532.png)
![screenshot 75](https://user-images.githubusercontent.com/20923700/50944199-23d11400-1498-11e9-9ea5-06df0704f451.png)

EDIT: After further investigations, it seems to only do that in certain cases,
here is a test case, I have this regex in multiple replace: `(?s)^((?!\p{IsArabic}).)+$` replaced with nothing as I want to delete all lines with no Arabic letters, it does this behavior with all files but here is a test file: 
[[ARSubCrunchyroll] Parasyte The Maxim Episode 15.zip](https://github.com/SubtitleEdit/subtitleedit/files/2745508/ARSubCrunchyroll.Parasyte.The.Maxim.Episode.15.zip)

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip
