### ISSUE TITLE
Converting  File Errors:  *.vtt to *.srt Format

### ISSUE THREAD

**Issue by devilcoelhodog** [SubtitleEdit/subtitleedit#3290]
Hello, dear all.

I got the newest version from Subtitle Edit and try to convert a subtitle format to other.

The original subtitle is *.vtt fomat. The output is to be *.srt format.

But after the convertion the subtitle in srt show some strange errors.

Eg:

00:01:04,562 --> 00:01:08,908
{\an3}&gt;&gt; O que mais lhe
interessa na história?

The symbols:  {\an3}  and  &gt;&gt;  are incorrect.

Do you know how to fix that? 

I can make manual correction after the convertion to srt, but I would prefer that the program could do it at the first attempt, without any "errors" or strange "symbols" after the task. 

Thanks for your time.

Best regards.

**Comment by niksedk** [comment]
Could you attach the source .vtt subtitle?

**Comment by devilcoelhodog** [comment]
Hi, nikse.

See the sample below.

[SAMPLE-VTT.zip](https://github.com/SubtitleEdit/subtitleedit/files/2756966/SAMPLE-VTT.zip)

Please, can you fix such issue?

Thanks for your time.

Best regards.

**Comment by niksedk** [comment]
Thx for the file - how is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip ?

**Comment by devilcoelhodog** [comment]
Hi, nikse.

Thanks for your fast help!

I tried here and it seems work now. The symbol  {\an3}  is gone.

But still have an strange "symbol":  >>

Does it normal or should happen now? 

I'll attach the result I got. The sample *.vtt is bigger now. Srt included for output comparison.

[Sample 2.zip](https://github.com/SubtitleEdit/subtitleedit/files/2757256/Sample.2.zip)

Thanks for your time.

Best regards.

**Comment by niksedk** [comment]
The `{\an3}` was a bug... don't known about the ´>>´ - perhaps is has some special meaning? (I think some old .pac files use `>>` as italic)

**Comment by devilcoelhodog** [comment]
Hi, nikse.

Thanks for the new release. I have updated here. 

As I said before, now the *.vtt here can be opened / converted almost perfectly.

I don't know why still appears  the symbol  >>.

Testing here,  italic does not appear to be.

But this is not a problem. I can fix that manually using a simple text editor.

I don't know if such thing happens with all kind of *.vtt files ( the format itself will be the issue )  or just some of a few "specifical" of them, depending the source we get / create those original *.vtt files.

Thanks for your time.

Best regards.

**Comment by devilcoelhodog** [comment]
Hi, niksedk.

When I tested some files * vtt I still get some errors. Different ones, I mean. Please, can you check it?

[VTT - ERRORS - SAMPLES.zip](https://github.com/SubtitleEdit/subtitleedit/files/2873430/VTT.-.ERRORS.-.SAMPLES.zip)

I can fix it manually using text editor, but I think it will be better if your program could do it automatically for us.  

Thanks for your time.

Best regards.
