### ISSUE TITLE
Plugins can't upload in linux

### ISSUE THREAD

**Issue by edcol** [SubtitleEdit/subtitleedit#3292]
Hello Everybody,

I am using SE 3.5.8 under Ubunto with use of mono package.

Now, I am trying to use plugin 'Copy-Paste Translate' and upon retrieving it appears in subfolder Plugins but it's not visible in Menu Files->Plugins and I can't use it.

Anyway to make it working?

Kind regards
EC

**Comment by bugisbuggingme** [comment]
The title you used is a bit confusing. The problem on Linux is that plugins are downloaded but not installed. (They work on Wine though.)

Subtitle Edit 3.6.5

**Comment by niksedk** [comment]
Should be fixed
