### ISSUE TITLE
[Bug] Remove empty lines/unused line breaks not work

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#3293]
Remove empty lines/unused line breaks not work, tested in SE 3.5.8 build 91

![1](https://user-images.githubusercontent.com/7856897/51145384-9f8de080-184b-11e9-9785-d7fc5404f17e.gif)

**Comment by Araynilmar** [comment]
I tried, there is no such problem.
My SE 3.5.8 x64, d52d9ff

**Comment by LeonCheung** [comment]
Confirmed. I always has this problem after merging translation and original. Because there is an extra break per subtitle after that.

**Comment by marb99** [comment]
@Araynilmar 

I have download the last beta (build 91) from here, and I have tested and the bug persists

Try yourself

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip
