### ISSUE TITLE
Length can not be less then zero

### ISSUE THREAD

**Issue by Rouzax** [SubtitleEdit/subtitleedit#3296]
When trying to do Hearing Impaired on Subtitle Edit 3.5.8 I get `Length cannot be less then zero`
![image](https://user-images.githubusercontent.com/4103090/51273218-76488e00-19cc-11e9-8dee-93782453607f.png)

Same issue on the latest 3.5.8.101 Beta
![image](https://user-images.githubusercontent.com/4103090/51273438-fff85b80-19cc-11e9-91f2-b637c1fb2e9d.png)

[Superstore - S03E11 - Angels and Mermaids (1080p.WEB-DL.ViSUM).eng.txt](https://github.com/SubtitleEdit/subtitleedit/files/2765725/Superstore.-.S03E11.-.Angels.and.Mermaids.1080p.WEB-DL.ViSUM.eng.txt)

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by Rouzax** [comment]
It is fixed, thank you!
Any idea why the other issue is happening?
#3297
