### ISSUE TITLE
Subtitles Edit 3.5.8 klappt nicht wegen Key

### ISSUE THREAD

**Issue by stern20** [SubtitleEdit/subtitleedit#3299]

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/3281#issuecomment-451776143
Duplicate https://github.com/SubtitleEdit/subtitleedit/issues/3298

**Comment by stern20** [comment]
https://www.bilder-upload.eu/bild-91fa52-1547731783.png.html

https://www.bilder-upload.eu/bild-7b29c8-1547731846.png.html

bitte helf mich, wo soll einstellen windows 10

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/3257#issuecomment-450152852 https://github.com/SubtitleEdit/subtitleedit/issues/3257#issuecomment-453658660

**Comment by niksedk** [comment]
Yes, enable the cloud translation api + setup billing - also see https://www.nikse.dk/SubtitleEdit/Help#translation

**Comment by niksedk** [comment]
I presume you also tried the different translation plugins... like "GT screen-scraper" / "BT screen-scraper"...

**Comment by stern20** [comment]
ich brauche  noch error 403 ubtitles Edit.. habe alles ausprobieren.. klappt nicht.. bin sehr traurig weil langeweilig .. kann nicht zuhören.. immer
