### ISSUE TITLE
Option to remove OpenSubtitles ads

### ISSUE THREAD

**Issue by 07416** [SubtitleEdit/subtitleedit#3300]
OpenSubtitles implements advertising to all downloaded subtitles, the ads appear on the first and last line (not precisely, may be timing-based). The ad-line seems to be displayed for six seconds. The paid advertisements aren't marked in any way, but because they contain a domain name filtering should be feasible.

placeholder ads:

```
Advertise your product or brand here
contact www.OpenSubtitles.org today
```
```
Support us and become VIP member
to remove all ads from OpenSubtitles.org
```
I highly recommend enabling this setting by default, opensubtitles.org in any case generates revenue of copyrighted work.

**Comment by OmrSi** [comment]
Just add this to multiple replace: `(?is).*opensubtitles.*` replaced with nothing and it will remove the lines containing `opensubtitles` from the files.
I don't think he'll add this option because if the subtitle file is from the website, it can do what it wants...

**Comment by niksedk** [comment]
Yes, do like OmrSi suggested: Use Edit -> Multiple replace... and use a regex .
Also check `example 3` here: https://www.nikse.dk/SubtitleEdit/Help#multiple_replace

**Comment by 07416** [comment]
> I don't think he'll add this option because if the subtitle file is from the website, it can do what it wants...

I don't understand, unless you mean that websites shouldn't be allowed to profit of ripped subtitle files.

**Comment by 07416** [comment]
`(?is).*.com*` removes all lines containing `.com` as it likely is the most common  advertised top-level domain.

**Comment by OmrSi** [comment]
@07416 It would cause a problem if they mentioned a website in the video...
