### ISSUE TITLE
(400) bad request

### ISSUE THREAD

**Issue by Sopor-** [SubtitleEdit/subtitleedit#3302]
If i get `API key invalid` why do i get `(400) bad request` instead of `(401) Unauthorized`?

![image](https://user-images.githubusercontent.com/5789283/51432817-61733100-1c3e-11e9-83cf-a9b6043ada4a.png)

So i'm not sure what i'm doing wrong here :(

**Comment by niksedk** [comment]
Did you add billing info + got an cloud translation API key like this:
![image](https://user-images.githubusercontent.com/1261331/51436206-22b69880-1c89-11e9-8ed8-43b051625e16.png)

Also do try the "GT/BT screen-scraper" plugins - see File -> Plugins !
If everything fails, then this plugin can help somewhat: https://github.com/SubtitleEdit/subtitleedit/issues/3246#issuecomment-454441559

Read more here: https://www.nikse.dk/SubtitleEdit/Help#translation
