### ISSUE TITLE
[Bug] CPS NOT colored

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3303]
`<SubtitleMaximumCharactersPerSeconds>24</SubtitleMaximumCharactersPerSeconds>`
`<SubtitleOptimalCharactersPerSeconds>20</SubtitleOptimalCharactersPerSeconds>`
![screenshot 117](https://user-images.githubusercontent.com/20923700/51440239-b611bd00-1ccd-11e9-8c54-c25420496064.png)
![screenshot 118](https://user-images.githubusercontent.com/20923700/51440258-e5c0c500-1ccd-11e9-9760-80dcf4b614c9.png)

Could be related to this https://github.com/SubtitleEdit/subtitleedit/commit/0781d71eb518b1283cf74423d92ab03a6187a911

**Comment by niksedk** [comment]
thx :)
Yes was related to https://github.com/SubtitleEdit/subtitleedit/commit/c91bc03f8024fd05aad5f8009da5a39321fadcb1
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Cool. Works great. Thanks. :D

@niksedk I have a question but I don't want to open a separate issue for it.
If I copy a line like this without timing:
`"فقلت "(ألاباما)، اعترفي وأخبريه بما حدث""`
Which is 42 chars and my max char count is 42, and paste it as the first line in an empty file, SE breaks it:
`"فقلت "(ألاباما)،`
`اعترفي وأخبريه بما حدث""`
But if you paste it anywhere else, it leaves it on a single line, is that a bug? If it is, then it is a minor one.
![screenshot 119](https://user-images.githubusercontent.com/20923700/51440902-7ac6bc80-1cd4-11e9-82cb-54b6135f755a.png)
