### ISSUE TITLE
can't make bosnian ocr to work

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#3304]
hi
looks like I didn't pay attention to this before at all because I use older version of SE 
for ocr, but now I've put subtitle into new Subtitle Edit.

looks like that file `ba_OCRFixReplaceList.xml`
isn't properly integrated into Subtitle Edit at all and no changes can be made.

can you check into it? 
because I really need this.

[currently I've found a way around it by deleting content of some other foreign ocr file that I don't 
need and replacing it with it, but that's just a workaround, and I'd like this to be properly fixed].

**Comment by niksedk** [comment]
What happens if you rename the file to `bos_ORFixReplaceList.xml` ?

Also, SE don't have a link to Bosnian spell check dictionary - could this be used: https://extensions.libreoffice.org/extensions/spellchecking-dictionary-for-bosnian-language ?

Do you use Tesseract 4 or `Binary image compare`?

**Comment by diomed** [comment]
yes, renaming to  `bos_ORFixReplaceList.xml` fixes problem. 
I'll add some words, rename and make a PR.

That dictionary doesn't looks like good solution.
Didn't get into it but it looks like people are divided between it being useful.

Currently you're using Croatian - from open source which is also somewhat 
troublesome, because it contains some user inputs that are not correct.
