### ISSUE TITLE
Application error in 3.5.8: BinaryOcrDB.Add Image already in db

### ISSUE THREAD

**Issue by Travellingman** [SubtitleEdit/subtitleedit#3308]
When trying to add a better match, I get an exception message:

**Comment by Travellingman** [comment]
![ocr error](https://user-images.githubusercontent.com/10464213/51513686-b67d9580-1e3e-11e9-979d-e6ba9dc075e1.JPG)

**Comment by niksedk** [comment]
Could you try latest beta and see if the problems still occurs?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by Travellingman** [comment]
Thanks for the very prompt reply! It didn't through an exception when I attempted a character replacement, BUT it didn't save much in the way of converted text either.    The released version that throws the exception gave this: 
---------- Original Message ----------

**Comment by Travellingman** [comment]
It turns out that the IDX and SUB files supplied with the video, while correct, were not necessary.  The MKV contained perfectly good subtitle files which the beta AND released versions processed just fine (after I learned to open the MKV files instead).  I could not reproduce the exception in either versions. Thanks for the program!
---------- Original Message ----------
