### ISSUE TITLE
3.3.8 Cant load the end scene

### ISSUE THREAD

**Issue by ori1337** [SubtitleEdit/subtitleedit#3309]
Hello when i try to load a video i can load the beginning and its run fine for  20m and something 
but in the end it seems that i cannot do anything 

using windows 7 
video encoding V_mpeg4/iso/avc 

:+1: thanks guys

**Comment by niksedk** [comment]
What video player do you use inside SE? 
Try Options -> settings -> video player - and try "mpv" and/or "vlc"
