### ISSUE TITLE
[Feature Request] Auto Save when subtitle sync has changed

### ISSUE THREAD

**Issue by chorong761** [SubtitleEdit/subtitleedit#3311]
When times are changed (sync), there should be an option for it to save automatically instead of having to press save every time.

**Comment by niksedk** [comment]
Latest beta has a new "Auto save" options - try it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip
See Options -> Settings -> General

**Comment by chorong761** [comment]
I've tried it already but it doesn't seem to save automatically after changing time sync

**Comment by niksedk** [comment]
thx for the info - beta updated to save within 3 seconds: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip
How is that?

**Comment by chorong761** [comment]
> thx for the info - beta updated to save within 3 seconds: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip
> How is that?

Works Nice!

**Comment by niksedk** [comment]
thx for verifying :)
