### ISSUE TITLE
Closed  Captions Extraction

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3312]
Hello,
SE extracts embedded subtitles from video files, but doesn't recognize closed captions. 
Example:
![vlcsnap-2019-01-23-15h20m00s223](https://user-images.githubusercontent.com/28671050/51600042-e4d4a100-1f22-11e9-9931-68032d52b93b.png)
Here is the video link to this file:
https://openload.co/f/lOcvzt_qZng/Conan.2019.01.22.Tom.Hanks.480p.x264-mSD.mk

Note: Closed caption tracks display in VLC 3 and higher. 

Thank you.

**Comment by niksedk** [comment]
@mkver: Do you know anything about closed captions in mkv?
