### ISSUE TITLE
[Bug] ListViewNumberWidth in RTL mode

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3314]
@niksedk If you open and close SE while RTL mode is activated, ListViewNumberWidth always resets to 20 then 55 when opening again, then 37 then 20 again and so on...
![screenshot 132](https://user-images.githubusercontent.com/20923700/51686522-32234200-1ff9-11e9-9324-ecdf1431f5e2.png)
![screenshot 133](https://user-images.githubusercontent.com/20923700/51686527-33546f00-1ff9-11e9-8c35-e26016004212.png)
![screenshot 134](https://user-images.githubusercontent.com/20923700/51686532-35b6c900-1ff9-11e9-9366-08154c3aa0e8.png)

And now it's showing this:
![screenshot 135](https://user-images.githubusercontent.com/20923700/51700518-0bc0cf00-2018-11e9-866e-f2c9ef8d4cc8.png)

**Comment by OmrSi** [comment]
@niksedk Could you take a look at this? I have to adjust the size everytime I open SE.

**Comment by niksedk** [comment]
Hm, I cannot re-create this... when I adjust the size if the "#" column in rtl-mode the size is kept.

**Comment by OmrSi** [comment]
@niksedk Hmmm.
I tested it on a clean beta, look, here's what's happening:
https://imgur.com/a/6jqvPYG

**Comment by OmrSi** [comment]
You need to set then close SE and open it.

Also, I just noticed this:
A line like this:
`"<font color="#000000">مرحباً</font>"`
Is getting reversed to this with "Reverse Start\End":
`">font color="#000000">مرحباً</font<"`

**Comment by niksedk** [comment]
thx for explaining :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk Both are fixed. ❤😄
Thanks a bunch.
You can close this with the commit if you'd like.

**Comment by OmrSi** [comment]
@niksedk Now the issue is happening when I close and open SE while an ass file is opened. :\
![untitled project](https://user-images.githubusercontent.com/20923700/51805325-addcf300-2274-11e9-9c1c-7d44f61739f2.gif)

**Comment by niksedk** [comment]
Is this any better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Yep. Fixed. 
Thanks again. 😄
