### ISSUE TITLE
OCR method when using Batch Convert?

### ISSUE THREAD

**Issue by lambdan** [SubtitleEdit/subtitleedit#3315]
I'm converting some PGS/SUP files to SRT using OCR. In my case I dont need accuracy so I use the _Binary Image Compare_ method which is very fast and accurate enough for what I'm doing.

But when doing Batch Convert there doesnt seem to be a way to specify which method to use, so I think it's doing Tesseract which is much slower it seems.

Is it possible to have an option to choose which OCR method to use when doing Batch Convert?

**Comment by borifax** [comment]
I write in this thread not to make a new one.
Could someone help me create a regular expression that would automatically replace "-(" on "- ("   ?
I mean the rule in the OCRFixReplaceList file.
![image](https://user-images.githubusercontent.com/45988475/51932763-1dcbb480-2400-11e9-9b67-dcac1c2a4c03.png)

**Comment by OmrSi** [comment]
@borifax  It would be something like this:
```
  <RegularExpressions>
    <RegEx find="^-(\()" replaceWith="- $1" />
  </RegularExpressions>
```

I personally prefer:
```
  <RegularExpressions>
    <RegEx find="^-(\S)" replaceWith="- $1" />
  </RegularExpressions>
```

**Comment by borifax** [comment]
Thanks OmrSi for the willingness to help, but it does not work.
![image](https://user-images.githubusercontent.com/45988475/51999105-55973280-24ba-11e9-8ba7-8312adf256ff.png)
![image](https://user-images.githubusercontent.com/45988475/51999252-9abb6480-24ba-11e9-9b23-c20b576f4350.png)

**Comment by OmrSi** [comment]
@borifax It worked with me using Tesseract:
![screenshot 153](https://user-images.githubusercontent.com/20923700/52002609-263cf180-24cb-11e9-948b-69f7ddf7d007.png)
![screenshot 154](https://user-images.githubusercontent.com/20923700/52002717-5dab9e00-24cb-11e9-8bde-e8696a9fe199.png)

**Comment by OmrSi** [comment]
Yeah, Sadly I don't have a database to test the other method...

**Comment by niksedk** [comment]
Latest version of SE supports using "nocr" for batch ocr (a lot faster than Tesseract)
