### ISSUE TITLE
Change dictionary download

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#3323]
https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Resources/HunspellBackupDictionaries.xml and https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Resources/HunspellDictionaries.xml

Can you change the links for eng+country version to https://github.com/marcoagpinto/aoo-mozilla-en-dict ,which is obviously vastly superior and updated regularly. The current links is 14 years out of date.

**Comment by niksedk** [comment]
thx for the info - I've looked at other English dictionaries earlier but they lacked especially common swear words which made them unusable for subtitles!
Have you tested the above dictionaries?

(HunspellBakcupDictionaries.xml should not be changed as it is... backup)

**Comment by Ding-adong** [comment]
I have tested them. There are some common swear words in the dic with ! at the end which stands for nosuggest in aff file. Spellchecker accept them but won't suggest them. However i have new swear words added in the en_gb_user.xml and it's not a problem. The dic itself is undergoing major changes at the moment.

**Comment by niksedk** [comment]
OK, it's still missing a few more words than the included en_us dictionary in my tests... but it's close.

Looks good with the activity - if he only had .zip files SE could link directly to them (feel free to make a request ;)

**Comment by Ding-adong** [comment]
Woah. The en_gb doesn't include US words for obvious reason. link `https://github.com/marcoagpinto/aoo-mozilla-en-dict/archive/master.zip`
