### ISSUE TITLE
Merge two subtitle files in different languages into one

### ISSUE THREAD

**Issue by itishussainali** [SubtitleEdit/subtitleedit#3324]
Hi guys. Is there Any option or way to Merge two subtitle and then Export them as plain text?
Thanks.

**Comment by Ding-adong** [comment]
Tools>append or join
File>export>plain text

**Comment by niksedk** [comment]
It really depends on what you mean by "Merge"...

If you mean merge to a dual language subtitle then try:

1) The plugin "Merge two SRT files into one ASS/SSA".

or 

2) If you have a subtitle + original open (translator mode) you can use the shortcut "Merge original and translation". (see options -> settings -> shortcuts

**Comment by OmrSi** [comment]
Wow, I had "Merge two SRT files into one ASS/SSA", but it didn't occur to me that it's for a dual language subtitle. SE just keeps getting better and better. :)

**Comment by itishussainali** [comment]
@niksedk "The plugin" that's it. Thanks.

**Comment by itishussainali** [comment]
@Ding-adong Thanks.
