### ISSUE TITLE
"Bridge gap in durations..." needs a clearer name

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#3327]
As far as I can tell, it makes the gaps that are shorter than <var>n</var> milliseconds uniform by distributing their extra duration to the subtitles around them, and it will only make them shorter, not longer.

I really can't think of when that option would be useful, but in any case, it needs a better name, and here's a suggestion:

Tools menu and window title:
```
Trim short gaps between subtitles to uniform length...
```

Options could also use some better wording:
```
Trim gaps shorter than [--] ms
Desired gap length: [--] ms

Append extra gap duration to previous subtitle
Split extra gap duration between previous and next subtitle

Number of short gaps trimmed: [--]

Gap after (s)  // last table column heading
```

**Comment by OmrSi** [comment]
I think the name is clear enough if you knew what you're looking for. 
And that option would be useful when timing a file for a company as they request that, for example, if there is a 3-frame gap, make it 2, which is the minimum gap between lines. 
Netflix is one of the mentioned companies…

**Comment by aaaxx** [comment]
But to bridge the gap means to "overcome" the gap in some way – to connect the things on the opposite sides of the gap. From the perspective of a first time user, which was me yesterday, it seems like a more abstract way of saying "Merge subtitles that have specific amount of gap between them".

My proposal makes it obvious what the tool does: it will only shorten, not lengthen, the gaps ("trim"), and it will make them all the same length ("uniform length"). Also, it adds the word "short", which is currently used in the window title but not the Tools menu, to make it clear it's intended for short gaps.

**Comment by OmrSi** [comment]
It does "connect" thing if you want to, as it makes the gap 0, therefore connecting the lines by removing the gap between them. At least this is how I understand it...

**Comment by aaaxx** [comment]
But that's only an edge case (i.e., an extreme form of trimming). And even if that was all the tool did, the wording would still be ambiguous (as I said, the first time I noticed it, I thought it merged subtitles) and something like "Abut nearby subtitles"  or "Remove short gaps (abuts subtitles)" would make more sense.

And as you've mentioned, most companies have some minimum gap requirements that's greater than zero (probably because no gap makes it hard to notice subtitle change when they're of similar proportions), so the general use case here is to trim them to a length >0. As such, "Trim short gaps between subtitles to uniform length" makes explicit what the tool does.

**Comment by LeonCheung** [comment]
As far as I can recall, this feature was initially proposed by me. I'm a 3D software user, if you were, you'll see the word **bridge** is perfect in telling this feature. In another similar software, it's called "Make adjacent subtitles continuous". 

![w](https://user-images.githubusercontent.com/494788/52928122-2701ce80-3379-11e9-9f70-172f75588f0f.png)

Hopefully you could get the point either way.

I don't think words like "trim" or "remove" can be that good since "gap" is not a solid thing. Technically speaking, you can only "fill" it, sort of.
