### ISSUE TITLE
[Request] Simple position when importing from Vobsub

### ISSUE THREAD

**Issue by rebawest** [SubtitleEdit/subtitleedit#333]
When a subtitle appears at the top, could SE add `{\an8}`?

For example, this subtitle has an offset of 156 pixels. That's 14% of 1080 pixels.

![top subtitle](https://cloud.githubusercontent.com/assets/6587015/5076036/beb8ab30-6e76-11e4-97fe-da055c91022f.jpg)

So, if the Y offset is less than 20 or 25% of the image height, please add `{\an8`.

Thank you. Regards...

**Comment by niksedk** [comment]
Should work now... better late than never ;)
