### ISSUE TITLE
Minor bug with I converted to i

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#3331]
MRIs whereas `s` indicate plural changes into MRis. However IMRs or MIRs doesn't change the `I`. If `I` is the last letter before `s` then it converts to `i` or `l`. A small code change telling SE that if there is a `s` for plural then do not do anything.

**Comment by OmrSi** [comment]
@niksedk https://github.com/SubtitleEdit/subtitleedit/issues/323 related, I think.

**Comment by Ding-adong** [comment]
It is and a very very long time ago.
