### ISSUE TITLE
Support integer values in WebVTT line cues

### ISSUE THREAD

**Issue by franontanaya** [SubtitleEdit/subtitleedit#3338]
Reference:
https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#Cue_settings

Currently SE only supports percentage values for the line cues. For example, loading a VTT file with `line:1` cues results in position cues being lost.

Integer values refer to "height of the first caption line" times "value", starting from the top if it's a positive number or starting from the bottom if it's a negative value. 

* line:0 is the top of the screen, equivalent to 0%
* line:1 is one line's height below the top of the screen. If we used the traditional 32 screen lines spec as rule it'd be equivalent to 3%.
* line:-1 is bottom of the screen, equivalent to 100%

Translating other line values to percentages may be iffy in combination with font sizes and whatnot, but those three at least should be straightforward, and they are likely the most common ones.

Ideally the file should also export using the same position style it had when loading.

**Comment by niksedk** [comment]
Could you supply a sample file?

**Comment by aaaxx** [comment]
[Official spec.](https://w3c.github.io/webvtt/)

It depends on line height, which is 6% of screen height by default, so probably 16 lines by default.

**Comment by niksedk** [comment]
Seems a bit... let's say "unfortunate" to use line numbers as it depends on resolution/font size, but the above commit adds some support for reading integers in `line` - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip
