### ISSUE TITLE
Enhance regex

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#3340]
`<RegEx find="([a-zI])(?> |\r\n)W(ant|e|ere|hat|hen|here|ho|hy|ith|on't|ould)([ .,;:!?\r\n]+)" replaceWith="$1 w$2$3" />` 

to replace `<RegEx find="([a-z]) Won't " replaceWith="$1 won't " />`

The enhancement would cover more common `W` words and also more potential characters after a word, instead only only space.

**Comment by diomed** [comment]
hey

could you pls help me?
I'm trying to exclude m and j from this - unsuccessfully 
```
    <RegEx find=" ičijo(?&lt;![mj])" replaceWith="ičio" />
```

**Comment by aaaxx** [comment]
The lookbehind at that location doesn't make sense. It checks that the "o" before it isn't `[mj]`, which it obviously can't be because it's "o". I think you want a look<em>ahead</em>, which would be `(?![mj])`.

**Comment by diomed** [comment]
Thanks for help @aaaxx 
Just what I wanted

**Comment by Ding-adong** [comment]
@diomed Your version worked. Did you put in the space before i in the test string?

https://regex101.com/r/FAsfxS/1  Check each version but ignore v5.

Your replacement exclude space - intended?

**Comment by diomed** [comment]
thanks guys for pointing  out what's wrong, my final version is 
`<RegEx find="([aeiou])čijo(?![mj])" replaceWith="$1čio" />`
