### ISSUE TITLE
DeepL plugin not working

### ISSUE THREAD

**Issue by 1024mb** [SubtitleEdit/subtitleedit#3341]
Translating with DeepL is currently not working.
It doesn't translate anything and it doesn't throw any errors neither, it just fills the Translation column with blank/empty lines.

**Comment by niksedk** [comment]
Sorry, I've removed the DeepL plugin as it only allowed something like 7 lines...
See https://github.com/SubtitleEdit/plugins/issues/158

**Comment by 1024mb** [comment]
That's a bummer, DeepL's service was the best one in SE.
Thanks for the clarification, I've searched for DeepL on issues but that one didn't showed up.
I have to ask, is there such a big difference to the way your plugin and QTranslate use the DeepL's service? I mean, don't you both use the same public API (although I believe there is no public API) or something? Because just now I have tested QT with 9 lines and it translated all of them without problems.

**Comment by niksedk** [comment]
How many lines do you get translated with QT?

**Comment by 1024mb** [comment]
Right now I've translated all the quotes given here: https://www.ef.com/english-resources/english-quotes/famous/
And also I've translated the description, all the lines consecutively and the faster I could.
QT translated all the text I input (I used double Ctrl to auto translate the selected text).

**Comment by niksedk** [comment]
There's now a `DeepL Screen-Scraper translate` plugin...
