### ISSUE TITLE
Names.xml errors

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#3343]
There are some words with lower case? I thought all words should be upper case.
Eastenders should be EastEnders (TV).
If you are referring to people living in the east of London then it's East Ender.
  <name>Y.M.C.A</name>
  <name>N.Y</name>
  <name>F.I.T</name> missing . ?
Luthorcorp should be LuthorCorp.
MacBeth should be Macbeth.
add Myspace.
ViXen  should be Vixen

**Comment by Ding-adong** [comment]
What about the words in lowercase??

**Comment by niksedk** [comment]
If these are names, then they are now allowed as (lowercase) words... words go in the word list instead.
Perhaps "vixen" should be a "word" ?
