### ISSUE TITLE
Bug in eng_OCRfixreplacelist_user.xml

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#3348]
After OCRing a vob file, wary of the mysterious bug, I had the file in notepadd++ just in case. Despite no changes being made, Notepad asked to reload the said file. I'd renamed the new file and made a comparison.

`    <Word from="Gargon" to="Garçon" />`
was the original and SE randomly changed it to
`    <Word from="Gargon" to="GarĂ§on" />` 

The word Gargon was never in the subtitle.
Two new lines, both valid, were added.
```
    <Word from="wigmakers" to="wig makers" />
    <Word from="=" to="-" />
```

**Comment by niksedk** [comment]
If you edit files manually, you need to save in utf-8 format - probably with a BOM header

**Comment by Ding-adong** [comment]
All files already have BOM header.
