### ISSUE TITLE
Keeping Color Tags

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3349]
Hello,
I use a Notepad++ macro to keep the color information in the SMI files.
I'm attaching macro actions and SMI file, if you could incorporate it in SE to keep color tags in SRT. I don't bother about screen alignment, but you can do those if you want to.

Also, you did same for VTT files last year, but it doesn't work with color green (<font color="#11FF11">) . Attaching that one as well.
Thank you.
[x4.zip](https://github.com/SubtitleEdit/subtitleedit/files/2847537/x4.zip)

**Comment by niksedk** [comment]
Is `<c.color008000>` a standard way of writing hex #008000 in WebVTT ?

**Comment by uckthis** [comment]
@niksedk , yes, I think so. It's green, which doesn't really look good on screen, so I always replace it with lighter green: #11FF11.

**Comment by aaaxx** [comment]
Nope, as far as I can tell, other than a predefined list of legacy [text colors](https://w3c.github.io/webvtt/#default-text-color) and [background colors](https://w3c.github.io/webvtt/#default-text-background) encoded as reserved class names (e.g., `<c.yellow>...</c>` or `<c.yellow.bg_black>...</c>`) and the usual `<i>`, `<b>`, `<u>` tags, VTT doesn't support mixing presentation and content. Here are the [allowed subtitle components](https://w3c.github.io/webvtt/#caption-text).

@uckthis, use <c.lime> for green (see the note in the above color list and [this VTT discussion](https://github.com/w3c/webvtt/issues/365#issuecomment-343615425)).

**Comment by uckthis** [comment]
@aaaxx I macro VTT to an SRT, so my tags are like this: <font color="#11FF11">.

**Comment by OmrSi** [comment]
@niksedk Closed?

**Comment by niksedk** [comment]
@uckthis: Is this one fixed?
