### ISSUE TITLE
[Bug] Quotes aren't reversed!

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3354]
I was just testing a file and noticed that quotes aren't being reversed at all!
@darnn Have you noticed this?
Original:
![screenshot 192](https://user-images.githubusercontent.com/20923700/52536993-fe227d80-2d69-11e9-9820-6b82b6a0e095.png)

Using reverse in 3.5.8:
![screenshot 189](https://user-images.githubusercontent.com/20923700/52536999-067ab880-2d6a-11e9-9f01-d87e9bd65e6c.png)

Using reverse in the latest version:
![screenshot 190](https://user-images.githubusercontent.com/20923700/52537000-0d093000-2d6a-11e9-9308-f8d771f29c2b.png)

I thought it was only happening with double quotes when I mentioned it here: https://github.com/SubtitleEdit/subtitleedit/issues/3333#issuecomment-461819539
I think this is a huge issue for reversing. :\

**Comment by OmrSi** [comment]
@niksedk I know you take a break for a couple of days after a new release, but please fix this as soon as possible, I don't wanna go back to 3.5.8 because I'm using bookmarks and I don't have a beta after the bookmarks and before this issue. :(

**Comment by darnn** [comment]
I don't really use reverse myself, the only things I need it for I do with unicode control characters, but I tested this and it's just like you say, it changed sometime within the past two-three weeks.

**Comment by OmrSi** [comment]
@niksedk The issue started after this commit https://github.com/SubtitleEdit/subtitleedit/commit/dc7e8633b2147ae5832614e7020be28291d0e878

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Yep, fixed. Thnx. :D
