### ISSUE TITLE
Batch Adjust Durations?

### ISSUE THREAD

**Issue by hurricane51** [SubtitleEdit/subtitleedit#3355]
I have a couple of subtitle files (SRT) and whoever created them left the durations way too long. All of them should be reduced by several seconds. Instead of having to go through each line, I was wondering if there was some way I could attack them with some type of batch command, like take 2 seconds out of every duration. Is that possible?

**Comment by Ding-adong** [comment]
Setting - General - max duration - adjust it to your fancy.

**Comment by hurricane51** [comment]
That's not what I want to do. The subtitles are of varying duration, and I want to subtract a set amount of time. In other words, the ones that are now 3 seconds I want to reduce to 2 seconds and the ones that are 5 seconds I want to reduce to 4 seconds, etc. I'm probably going to have to go through them all one-by-one.

**Comment by darnn** [comment]
I mean, have you tried tools->adjust durations?

**Comment by hurricane51** [comment]
That's it! That's exactly what I needed. Thanks.
