### ISSUE TITLE
Failed to search shortcut

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#3360]
I got little time to test every shortcut, but at least the "set end time" shortcut cannot be looked up via searcher.

**Comment by niksedk** [comment]
thx, seems to be a problems with the ampersand (&) character - should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Cool!
