### ISSUE TITLE
Please do NOT reuse release numbers

### ISSUE THREAD

**Issue by FredThompsonII** [SubtitleEdit/subtitleedit#3363]
There have been multiple sequential releases all with the number 3.5.9.

Please add a build number or something similar to properly designate release order.

**Comment by OmrSi** [comment]
He doesn't reuse release numbers.
He only releases one official version with a setup file, then everything he does between that version and the next version is considered a Beta and has a build number.
For example, this is the current Beta:
![screenshot 195](https://user-images.githubusercontent.com/20923700/52684609-7d24db00-2f4f-11e9-87e8-3c3c2c42f5cc.png)

**Comment by o11598652** [comment]
How do I know about a new beta release? 
They don't have numbers in the release page. Maybe a beta number rename?

**Comment by niksedk** [comment]
I guess I could include the build / version number like this: `SubtitleEditBeta_3.5.9.23.zip`
But that would be annoying when linking to latest beta, so I'm not totally convinced.

@FredThompsonII: Could you explain a bit more what you mean? Did you read the description of the files?

**Comment by OmrSi** [comment]
@niksedk Maybe you can add the build number near the name only in the download page instead of renaming the file itself.

**Comment by niksedk** [comment]
@OmrSi: I'm trying to keep things easy... as I'm somewhat lazy ;)

**Comment by OmrSi** [comment]
@niksedk Haha. There are 10,105 commits that say otherwise. :D
I don't mind the current system anyway. 😁

**Comment by marb99** [comment]
It's just change the name "build" to "beta" and for release do not insert the git number, just 3.5.9 for example

**Comment by niksedk** [comment]
OK, I've hidden the git commit hash for the revision 0 (and 1 in case something goes wrong and I need an extra commit).

I'm no too sure about the beta... it sound like it a beta for prev version. So I like build better, or perhaps like this?
![image](https://user-images.githubusercontent.com/1261331/52896307-21b05280-31c6-11e9-9411-86ba4899aaee.png)

**Comment by marb99** [comment]
If number is the same was the stable version it sounds like it a beta for prev version, should be the number of the next release, ex: 3.5.10 beta 23 not the number of prev version.

if it is the number of the previous version i like build too
