### ISSUE TITLE
S.H.I.E.L.D. gets changed into S.H.I.E.I.D. 

### ISSUE THREAD

**Issue by teodargent** [SubtitleEdit/subtitleedit#3364]
![image](https://user-images.githubusercontent.com/20757457/52678715-ee09ca00-2f32-11e9-93eb-e204d322d544.png)

**Comment by niksedk** [comment]
Thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
