### ISSUE TITLE
"instant translation" for google copy/paste

### ISSUE THREAD

**Issue by o11598652** [SubtitleEdit/subtitleedit#3368]
The old version of Google translate, had a setting to disable automatic translation, but this new version requires to click on the arrow > to send the request. Did anybody have success, maybe creating a script to automatically send the pasted content?

**Comment by niksedk** [comment]
I'm not really sure I understand... 
Did you try the "GT screen-scraper" + the "BT screen scraper" plugins? (File -> Plugins)

**Comment by o11598652** [comment]
What are the required tools to execute that? It gives me an error.

**Comment by niksedk** [comment]
What's the error?

**Comment by niksedk** [comment]
Hm, it might need .net framework 4.6.2+ and updated windows 10...

**Comment by o11598652** [comment]
The error before installing .net 4.6.2
https://i.imgur.com/LiQ3HrG.jpg

After installing, it closes the prompt for translating, and creates blank "translations".
https://i.imgur.com/512O1I9.jpg

Is it because I don't have Edge? It's win10 exclusive.
Maybe some firefox/win7 adaptation for the script?

**Comment by niksedk** [comment]
Yes, sorry, the component only works for latest version of Win10 atm: https://blogs.windows.com/msedgedev/2018/05/09/modern-webview-winforms-wpf-apps/#32YXyZggs6vPI3I8.97
