### ISSUE TITLE
Subtitle Edit crashes

### ISSUE THREAD

**Issue by dschulze747** [SubtitleEdit/subtitleedit#3369]
I have a new computer running Windows 10 Home edition. I have installed Subtitle Edit 3.5.9, c424586. Every time I try to load a srt file, I get an error message.

![annotation 2019-02-14 221023](https://user-images.githubusercontent.com/47651747/52832842-6219ae80-30a8-11e9-96db-41d32099260e.jpg)

It worked fine on my Windows 7 computer.

**Comment by dschulze747** [comment]
Yes, that's what I did. I was using the portable version. However, I was using the portable version on my old computer in Windows 7, installed to the same folder under Program Files, and it worked fine.

**Comment by darnn** [comment]
It's possible your Windows user on your old computer had different permissions, or thet hard drive did, etc. This is a well-known (if unfortunate) issue, it seemed you just lucked out on your old computer.
