### ISSUE TITLE
[Question] Batch Change Color SRT

### ISSUE THREAD

**Issue by amiremami** [SubtitleEdit/subtitleedit#3373]
Hi
I have a question. I wanted to know is it possible to select for example 10 srt files and change the color of all subtitles together, for example to yellow?

Thanks

**Comment by OmrSi** [comment]
Hey. Yeah, it's possible, but not in a direct way.
Follow these steps:
1. Open Batch convert from the tools menu.
2. Open all of your files.
3. Activate Multiple Replace and press the "Settings" next to it.
3. Add a "Regular Expressions" rule. Replace `(?s)\A(<font color=".+?">)?(.+?)(</font>)?\z` with `<font color="#ffff00">$2</font>`, this would remove any existing colors from all lines and add yellow, the rule would change depending on what you have in your file but this would work if there are no tags or if there are color tags, it would remove them and add yellow.
But if you just want to change the color of lines that don't have a color, the rule would change.
4. Press Convert then OK and you'll have you file. :D

**Comment by amiremami** [comment]
Hey @OmrSi Thank you so much for helping, this works great <3

**Comment by OmrSi** [comment]
You got it!

**Comment by ivandrofly** [comment]
Close?  @niksedk , @amiremami
