### ISSUE TITLE
[Bug] Fix common errors list and text box

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3375]
When I sort the errors by function then move between them in the list, the text box doesn't always follow when moving between "Start with uppercase letter after colon\semicolon":
![screenshot 205](https://user-images.githubusercontent.com/20923700/52920825-a495f200-3319-11e9-84f7-91224492e767.png)

Test file: 
[Hawaii.Five.0.S09E15.720p.WEBRip.2CH.x265.HEVC.PSA.Farda.DL.zip](https://github.com/SubtitleEdit/subtitleedit/files/2873520/Hawaii.Five.0.S09E15.720p.WEBRip.2CH.x265.HEVC.PSA.Farda.DL.zip)

**Comment by Ding-adong** [comment]
When you click on any lines `Start with uppercase after colon/....` the text doesn't show/move.

**Comment by OmrSi** [comment]
Yep, moving between them and clicking on one of them both doesn't work.

**Comment by niksedk** [comment]
thx - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk Thank you. ^_^
How much did @darnn pay you to write his name instead of mind? Haha. jk. xD

BTW, you be like, "I go for a couple of days and all hell breaks loose?" Hehe.

**Comment by niksedk** [comment]
LOL, sorry about that - will try to fix it in the change log :)

Yep, was on trip to Amsterdam - and yes, a lot more activity than I expected!

**Comment by OmrSi** [comment]
Hahaha. It's totally fine, of course. The important thing is that the issue is fixed. ^_^

Nice, hope you had fun!
Yeah, I was surprised as well. I mean, were they waiting for you to go? Haha.
