### ISSUE TITLE
Fix uppercase 'i' inside lowercase words (OCR error) matches when there is no uppercase inside words

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#3377]
Tested on both 3.5.9 (c424586) and 3.5.9 beta 28 (0c3fd44).

The function hits a line like
```
I have recorded conversations
with Peter Iannone, Kurt Hewig and Myra Mark
```
and tries to fix, but the way I see it, there is no difference between 'before' and 'after'.

Why does it hit the line?

**Comment by Ding-adong** [comment]
Before
```
I have recorded conversations
with Peter Iannone, Kurt Hewig and Myra Mark
```
After
```
I have recorded conversations
with Peter lannone, Kurt Hewig and Myra Mark
```
Capital `I` was converted to `l`. It's a bug

**Comment by niksedk** [comment]
You can add the name `Iannone` to the name list...
But I've tried to improve this, so `lannone` must a correct word in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
How does that work?

**Comment by taxen** [comment]
I see. It seems every word starting with 'I' and followed by lowercase letters has been wrongly changed to 'l' word.

**Comment by taxen** [comment]
For testing purpose, I made up slightly modified version...
```
I Iave recorded conversatIons
with Ieter Iannone, Iurt IewIg and Iyra Iark
```
and beta 35 (8d173b8) gave me the following output.
```
I lave recorded conversatlons
with Ieter Iannone, Iurt Iewlg and Iyra lark
```

I guess 'conversatlons' 'Iewlg' should be 'conversations', 'Iewig'.
'Iark' to 'lark' is correct, considering 'lark' is a valid word.

I thought "Fix uppercase 'i' inside lowercase words (OCR error)" function simply changes uppercase 'I' inside lowercase words to lowercase 'i' such as 'conversatIons' to 'conversations'.

**Comment by niksedk** [comment]
Hm, I could remove the check from words starting with "I", like this:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

Or change the text to `"Fix uppercase 'i' in lowercase words (OCR error)"`...

Any thoughts?

**Comment by Ding-adong** [comment]
`Fix uppercase 'i' inside lowercase words` implies an `I` somewhere in a word such as `heIlo`. The first letter of a word `Ian` is on the outside and should be left alone except for common errors, which is sorted by fixreplacelist etc. SE should ignore the first letter of each word when checking for `Fix uppercase 'i' inside lowercase words`.

**Comment by niksedk** [comment]
OK, SE will now not change words starting with an uppercase "i" via this function.
