### ISSUE TITLE
[Bug] Crashes lead to missing subtitles

### ISSUE THREAD

**Issue by annjkai** [SubtitleEdit/subtitleedit#3379]
Hi, I just today patched to 3.5.9 on Windows 10.

The program has now crashed a few times, and every time I re-open about half of the subtitles are no longer available in the program - no pattern I can identify, but it's about every other one. Restarting Subtitle doesn't solve the problem. 

My save file is thankfully fine but I've so far had to manually re-insert the missing subtitles to continue working. I'm unable to re-import the subtitle file, possibly because I'm using a custom file format (.csv for Nuendo).

Thanks for any help you can give!

**Comment by OmrSi** [comment]
If the crash leaves a message, you should take a screenshot and leave it here.

**Comment by annjkai** [comment]
Unfortunately it doesn't - crashes without error report either before or after.

**Comment by ivandrofly** [comment]
> Unfortunately it doesn't - crashes without error report either before or after.

What version are you using?

Can you post the subtitle file that is causing the error?

**Comment by annjkai** [comment]
Version is 3.5.9, and unfortunately I can't post the file as it contains proprietary information, but I can tell you it's an Excel CSV file. This is about the 5th or 6th video I'm subtitling, and today/after updating is the first time I'm having this problem. 
The file itself is in perfect condition when opened and contains all my subtitles, time codes etc.

I've now also tried re-importing the .csv file and then attaching the video, I end up with the same problem.

**Comment by darnn** [comment]
I don't know if this is feasible or not, but you could make a sample csv file with only five or ten lines, and replace the actual text with gibberish.

**Comment by annjkai** [comment]
Excellent idea, thanks for the suggestion! 
This is one of the files but I've modified it to contain ipsum text.

[Sub_Edit_V2_3.zip](https://github.com/SubtitleEdit/subtitleedit/files/2876160/Sub_Edit_V2_3.zip)

**Comment by focuspulling** [comment]
I am getting frequent crashes now with 3.5.9, pretty much every other playback start/stop, especially when clicking in the video frame to start/stop (rather than using the space bar).  This never used to happen -- one of the great things about the program has been its incredible, rock-solid stability.  Any ideas?
