### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by lon0** [SubtitleEdit/subtitleedit#3380]
Hi, when I try to import ocr vobsub with tesseract 3.02 or 4, the program crash with the last versions, there are a lot of tesseract process open in task manager, I must close from there. However after the upgrade to tesseract 4 was very slow, so I continue with the v3.5.6, that work fine!

Regards and thanks of the support

**Comment by niksedk** [comment]
What version of SE are you using and what the crash message?

**Comment by lon0** [comment]
I found last versions SE358.zip and SE359.zip with this problem, there aren't crash messages, the program get stuck with a lot open tesseract process in task manager. 

When I download the ocr dictionaries with tesseract 3.02 in these versions, the program download not only the traineddata, but also all the other files as here https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-302
Are they necessary?

**Comment by OmrSi** [comment]
@lon0 SE should only download the languages you choose to download inside SE.
These are the ones that come with it https://github.com/SubtitleEdit/subtitleedit/tree/master/Tesseract302/tessdata

**Comment by lon0** [comment]
Yes, but with the last versions SE download all the files like the archives of the link above, try to download an ocr dictionaries language with tesseract 3.02 and you will find a lot of files in the tessdata folder!

**Comment by lon0** [comment]
Hello niksedk, nothing of this has been resolved, the program yet get stuck when I try to import ocr vobsub with tesseract, I have win7, is the problem the OS?

**Comment by niksedk** [comment]
@lon0: It perhaps could be a missing "Visual C++ runtime"? https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by lon0** [comment]
No, I have all the versions installed both 32-64bit until 2017 (14.16.27012), I have also installed the last now, but doesn't change nothing, however as I had written to the beginning SE v3.5.6 still work fine with just 1 o 2 tesseract process working I see in task manager while with the last version there are about 20 tesseract process and the program get stuck immediately, I must close all from task manager, maybe after v3.5.6 are there interferences after the introduction of tesseract4?

**Comment by lon0** [comment]
After the last updates also the version 3.5.10 works!

Thanks of the support, 
regards
