### ISSUE TITLE
[Bug] VTT issue with the last version

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3383]
When we used to open a Vtt file in SE 3.5.8 it used to leave `&rlm;` tag alone and we would replace it with an RTL Unicode control character, now in SE 3.5.9 it's automatically converting `&rlm;` to an LTR control character and then we have to remove it and add an RTL Unicode control character:
3.5.8:
![screenshot 206](https://user-images.githubusercontent.com/20923700/53032371-67e00d00-3477-11e9-9af4-be82afbe9410.png)
3.5.9:
![screenshot 207](https://user-images.githubusercontent.com/20923700/53032435-7f1efa80-3477-11e9-9d0f-43f58b6c1c10.png)
Notice that even though `&rlm;` is gone, the line is not well-reversed. File: [BoJack.Horseman.S01E01.WEBRip.Netflix.ar.zip](https://github.com/SubtitleEdit/subtitleedit/files/2881028/BoJack.Horseman.S01E01.WEBRip.Netflix.ar.zip)

2. Was mentioned here later: https://github.com/SubtitleEdit/subtitleedit/issues/3385
~~Some files that are converted from vtt to srt show line numbers in each line of the subtitle in 3.5.9 while it didn't in 3.5.8~~

**Comment by OmrSi** [comment]
@ivandrofly Do you have any ideas about replacing `1. &rlm;`? It didn't use to happen.
It wouldn't be a problem if it was replaced with a Right to Left control character, but it's not.
I attached a test file...

**Comment by OmrSi** [comment]
@ivandrofly Do you have any ideas about replacing `&rlm;`? It didn't use to happen.
It wouldn't be a problem if it was replaced with a Right to Left control character, but it's not.
I attached a test file...

**Comment by OmrSi** [comment]
@niksedk The issue started after this commit https://github.com/SubtitleEdit/subtitleedit/commit/f2957b4a3bdbba07b655b390ee1b5a9ad77f404a

**Comment by OmrSi** [comment]
Oh, it converting `<c.arabic>` to `<font color="arabic">` then doesn't delete it when it's converted to srt.
`paragraph.Text = System.Net.WebUtility.HtmlDecode(paragraph.Text);` I think is converting `&rlm;` to `\u200F` but it's not in its right position.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

What position should the `\u200F` char be in?

**Comment by OmrSi** [comment]
@niksedk I don't think `\u200F` is good here. :\
You need `\u202B` like the one used in SE. Check this:
`مسلسلات NETFLIX ألاصلية`
with `\u200F` at start or end: `‏مسلسلات NETFLIX ألاصلية`
with SE's `\u202B`: `‫مسلسلات NETFLIX ألاصلية`

**Comment by niksedk** [comment]
So I could just remove `&rlm;` ?

**Comment by OmrSi** [comment]
Yep, remove it or better yet replace it with \u202b before decoding html.

**Comment by OmrSi** [comment]
The perfect solution would be, replace, if exists, rlm with \u202B and rlm with \u202A the decode the rest.

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
It's not deleting it or replacing it with the proper control char, so I guess this is a good compromise.
As I said, an improvement would be to replace rlm with \u202B and lrm with \u202A, but it's not necessary, we can replace it ourselves. Thank you.
Closed with the commit.
