### ISSUE TITLE
[Bug] Encoding UTF-8 Not Works

### ISSUE THREAD

**Issue by amiremami** [SubtitleEdit/subtitleedit#3384]
Hi
I am using subtitle edit, tools batch convert, as subrip and encoding as utf-8. But it can't convert the encoding of the files to utf-8 and I see weird characters on tv. So, still I need to convert the encoding with notepad++

Why this option not works?

Thanks

This is the file that I am testing:
[Dexter.S03E12.Do.You.Take.Dexter.Morgan.480p.BluRay.x264.dingchris-SiNNERS.zip](https://github.com/SubtitleEdit/subtitleedit/files/2883782/Dexter.S03E12.Do.You.Take.Dexter.Morgan.480p.BluRay.x264.dingchris-SiNNERS.zip)

**Comment by SirEllert** [comment]
Which version of Subtitle Edit are you using?

**Comment by amiremami** [comment]
3.5.9

**Comment by SirEllert** [comment]
Can you upload your original file as well (a non-converted file)? If the attached one is the original, then the input file is simply bad.

**Comment by amiremami** [comment]
That's the original file. I explained it here:
https://i.imgur.com/vIGo73g.png

**Comment by amiremami** [comment]
So, seems the "encoding to utf-8" in subtitle edit is different than "convert to utf-8" in notepad++, or at least it's not working as it should.

**Comment by SirEllert** [comment]
Arh, I see. I can't even convert it correctly in notepad++, so I have to pass on this one. 

Hope someone else can help you!

**Comment by amiremami** [comment]
Thanks : )

It's because you didn't configure the correct settings on windows in language section for Persian language and non unicode preferred language. 

But this is the bug of the software, I hope they can fix it.

**Comment by niksedk** [comment]
Go to Options -> Settings -> General - enable "Auto detect ANSI encoding" - thx should help :)

**Comment by niksedk** [comment]
You can test encodings via File -> Import subtitle with manual chosen encoding...

**Comment by OmrSi** [comment]
@amiremami I don't mean to offend, but I've seen you use it in other places so I thought I'd tell you, it's "doesn't work" or "not working".

**Comment by amiremami** [comment]
Thanks guys for helping : ) Sorry, I'm really new to this software and I didn't have enough knowledge about these options. Thanks again.
