### ISSUE TITLE
3.5.9 adds line number to text for .srt file

### ISSUE THREAD

**Issue by SirEllert** [SubtitleEdit/subtitleedit#3385]
3.5.9 apparently handles UTF-8 BOM differently than previous version. 

See the pictures for differences when loading the same .srt file in the two different versions. 
It includes the line number for the next line when loading.  

The .srt file is attached. 

<img width="594" alt="version3 5 4" src="https://user-images.githubusercontent.com/14052609/53084112-745c7800-3500-11e9-82c3-4859222de7e0.png">
<img width="828" alt="version3 5 9" src="https://user-images.githubusercontent.com/14052609/53084113-74f50e80-3500-11e9-9f9a-a06a0bc84446.png">

[UTF8BOM_test.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/2884093/UTF8BOM_test.srt.zip)

**Comment by aaaxx** [comment]
This is not a BOM issue: there is only one BOM at the beginning of the file, as it should be. The problem is the file has duplicate line numbers:

```
1
00:01:10,040 --> 00:01:13,360
K-A-R...

2

2
00:01:16,840 --> 00:01:19,080
... A-N-T...

3

3
00:01:21,280 --> 00:01:23,720
... Æ-N-E.
```

You can use the following regex in a text editor to remove them (find and replace with nothing):

```regex
^(\d+)(\r?\n)+(?=\1\r?\n\d+:\d+:\d+,\d+ --> \d+:\d+:\d+,\d+)
```

**Comment by SirEllert** [comment]
Actually that is caused by the software as well.. Didn't realize it did that before now. 

I've attached the original file (which is used for the screenshot) and it doesn't contain double line numbers
[full_file.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/2884680/full_file.srt.zip)

**Comment by OmrSi** [comment]
Yeah, it's doing the same thing with vtt files, adding a line number just like this.

**Comment by aaaxx** [comment]
What do you mean by "double UTF-8 BOM"? I've checked the original file in a hex editor, and it has a normal single BOM, `"EF BB BF"`.

**Comment by SirEllert** [comment]
@aaaxx you're right. I just thought another BOM was added because of a script converting subtitles. 

I've edited the title to reflect what we know at this point :)

**Comment by OmrSi** [comment]
I thought this was only happening with files that are converted from Vtt when I mentioned it here https://github.com/SubtitleEdit/subtitleedit/issues/3383
I guess it's happening with many files.

**Comment by niksedk** [comment]
@SirEllert: thx for the info - the error was due to a space after time codes. SE should now handle spaces after (and before) time codes better now:  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk it seems to be the same with the file I had, too.
But was 3.5.8 able to handle it just fine?

**Comment by niksedk** [comment]
Yes, I made some changes here: https://github.com/SubtitleEdit/subtitleedit/issues/2147

**Comment by niksedk** [comment]
I added some unit tests, so hopefully this should not happen again.
