### ISSUE TITLE
Undo function fails to work after column->delete text

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3386]
Hey. 3.5.9 build c424586.
In translator mode, after using the keyboard shortcut for column->delete text, the undo function fails to work.

**Comment by niksedk** [comment]
thx for the info - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk here is another undo issue https://github.com/SubtitleEdit/subtitleedit/commit/9a714e6cdb3fc2ff1b4022a5c801c2510a3788af#commitcomment-32236225

**Comment by darnn** [comment]
Thanks!

**Comment by OmrSi** [comment]
@darnn Shouldn't it not affect the original? I mean, you usually want to delete only the one you're translating, right?

**Comment by darnn** [comment]
It shouldn't affect the original, no. I was going to post about it when I got a minute. Strangely, I think it wasn't doing it immediately, because I only noticed after a while.

**Comment by OmrSi** [comment]
Same thing goes for Unbreak, it's really annoying. :\
I added this to this issue https://github.com/SubtitleEdit/subtitleedit/issues/3418

**Comment by OmrSi** [comment]
@niksedk Yeah, I see it, so it started deleting the original after this commit, huh?
Well, @darnn agrees that it shouldn't delete the original, just that the undo works in when using the undo function, right @darnn?

**Comment by darnn** [comment]
Yep.
