### ISSUE TITLE
"merge original and translation" discards framerate

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3387]
Hey. Once again, 3.5.9 c424586.
I'm working in translator mode using a framerate that isn't set as the default one in SE (specifically the current one is 23.976 and the default is 25).
When I finish translating and use the keyboard shortcut to merge the original and the translation, the framerate changes to the default (25), and consequently, the timing of the subtitles changes.
I assume this is because SE joins both files and then "pastes" the result, as it were, into a newly created file, which is created, like all new files, with the default framerate.

Also, this is a minor thing, but when I merge an original and a translation that both only have one line, I get a gap of a single line between the first line and the second, and have to search for "\r\n\r\n" and replace it with "\r\n".

**Comment by ivandrofly** [comment]
> I'm working in translator mode using a framerate that isn't set as the default one in SE (specifically the current one is 23.976 and the default is 25).
> When I finish translating and use the keyboard shortcut to merge the original and the translation, the framerate changes to the default (25), and consequently, the timing of the subtitles changes.
> I assume this is because SE joins both files and then "pastes" the result, as it were, into a newly created file, which is created, like all new files, with the default framerate.

Open your *Settings.xml* look for a element named `CurrentVideoOffsetInMs` if there is any, try to removed it or set its value to 0 and and see if you are still having the timing issue.

**Comment by niksedk** [comment]
Beta updated to not reset subtitleformat/framerate/video: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

The merged lines have always had a blank line between the original/translation...

**Comment by darnn** [comment]
The framerate part works, thank you!
As for the blank line, does anyone actually need it? As far as I know, whenever you'd actually be using a subtitle file with two languages, they would be shown without a blank line between them. I'm genuinely asking, though, I only know how it works here with English/Hebrew.
