### ISSUE TITLE
A few requests for easyer use...

### ISSUE THREAD

**Issue by MaistroX** [SubtitleEdit/subtitleedit#3388]
1. When saving a file and the info sign pops up saying that file is write protected and there´s only a "OK" button there..... add the choice right there as "Save as" intsed of as of now, you have to push "OK" and go into Archive/ and choose "Save as" in there instead.
It would both save alot of time be more convenient.

2. A separate list to access so one can fix/edit the "Fix Comon Errors" (ctrl+shift+F).

Regards MaistroX

**Comment by niksedk** [comment]
thx for your input.

1. That's default behavior from ms... we better keep that consistent.

2. I'm not sure what you're requesting... you can already edit the text during FCE.

**Comment by MaistroX** [comment]
1. Even if it's the default behavior of MS, does that make it impossible to add an extra choice next to the "OK" button with "Save As" to make user save alot of time and hassel when editing alot of subtitles? 😀

**Comment by niksedk** [comment]
Sorry, I don't have much control of the SaveFileDialog component: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.savefiledialog?redirectedfrom=MSDN&view=netframework-4.7.2
