### ISSUE TITLE
[Bug] Lines with first number 0 follow by number 2, and renumbering problem

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#3393]
Lines with first number 0 follow by number 2, and renumbering problem

![1](https://user-images.githubusercontent.com/7856897/53222392-75f38080-3665-11e9-941c-3f34f035eae9.gif)

**Comment by niksedk** [comment]
Nice catch :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
(Unit tests also added, so this should not happen again)
