### ISSUE TITLE
Regex limitations?

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#3394]
Is there any document on this?
(?|) duplicate subpattern group doesn't seen to work.

**Comment by OmrSi** [comment]
It's not a "limitation". SE uses .NET regex flavor which doesn't support:
1. Branch reset group.
2. Subroutines/Recursion.
3. \K "keep out" feature.
4. Possessive quantifiers.
https://www.rexegg.com/regex-csharp.html

**Comment by OmrSi** [comment]
You can use instead: `((?:...)|(?:...)|(?:...))`

**Comment by Ding-adong** [comment]
What about Boost conditional replacement?

**Comment by OmrSi** [comment]
@Ding-adong Nope, not supported as well.
I looked into it a while ago, the only option is using two different expressions. :\
https://www.regular-expressions.info/refreplaceconditional.html

**Comment by Ding-adong** [comment]
What about this? Could it be a solution?
https://www.rexegg.com/regex-csharp.html#pcre.net

**Comment by OmrSi** [comment]
It's not the one supported by SE. I don't know if he can or want to use it.
But in any case, the first thing that will be gained is `\K` which is just a workaround for PCRE not supporting quantifiers in lookbehinds, so it's not really needed as .NET supports that.
The second thing is (?|), but you can use `((?:...)|(?:...)|(?:...))` so it's not very important.
The third thing is Recursion which you can use balancing group in its place or you can simply write it again.
The fourth thing is Possessive quantifiers and you can use atomic groups instead (?>...)
And the last thing is that Boost conditional replacement is only supported in PCRE2.
So, all in all, I don't think it's worth the effort. 
Plus, I'm don't know if it's that easy to change the supported flavor as what's mentioned in site allows you to use in your code, not in the program itself. (Not sure about this part).

But as usual, @niksedk has the final word.

**Comment by Ding-adong** [comment]
It's a shame. Boost conditional replacement would be brilliant. I find the replacing part very limited in Regex. Thanks for your clarifications.

**Comment by OmrSi** [comment]
Ding-adong Yes, sadly. :\
I looked a lot for a way to use conditional replacement but didn't find any.
I had a case where I needed to add a space if there wasn't one, but couldn't do it in one regex, had to use two just for a space.

**Comment by Ding-adong** [comment]
((?:...))((?:...))|((?:...))((?:...))| so and so doesn't work. I remember now as the capture group count kept on going up to 48 ha ha. It needs to be $1$2 for each alternate.

**Comment by OmrSi** [comment]
Why not `((?:...)(?:...))|((?:...)(?:...))|((?:...)(?:...))`? if this is not what you had in mind, can you write your regex example with a Branch reset group here https://regex101.com/ and share the link?

**Comment by Ding-adong** [comment]
Because i need to insert a character between each 1st and 2nd capture group and suffix as 3rd capture group.
https://regex101.com/r/52WkVx/1/ using above.
https://regex101.com/r/52WkVx/2/ original.

**Comment by OmrSi** [comment]
@Ding-adong That has a workaround, too.
Here: [http://regexstorm.net/tester?p=%28%3fi%29%28%3f%3a%28%3f%3cg1%3ealkal%29%28%3f%3cg2%3eemia%29%7c%28%3f%3cg1%3ean%29%28%3f%3cg2%3eemi%5bac%5d%29%7c%28%3f%3cg1%3ean%29%28%3f%3cg2%3eesthe%5bst%5di%29%7c%28%3f%3cg1%3earch%29%28%3f%3cg2%3eeolog%5biy%5d%29%7c%28%3f%3cg1%3ebougainvill%29%28%3f%3cg2%3eea%29%7c%28%3f%3cg1%3ec%29%28%3f%3cg2%3eesar%5bei%5dan%29%7c%28%3f%3cg1%3eencyclop%29%28%3f%3cg2%3eedi%29%7c%5cb%28%3f%3cg1%3e%29%28%3f%3cg2%3eeon%29%7c%28%3f%3cg1%3e%29%28%3f%3cg2%3eesthet%5bei%5d%29%7c%28%3f%3cg1%3e%29%28%3f%3cg2%3eetiolog%5biy%5d%29%7c%28%3f%3cg1%3ef%29%28%3f%3cg2%3eecal%29%5cb%7c%28%3f%3cg1%3ef%29%28%3f%3cg2%3eeces%29%7c%28%3f%3cg1%3eglyc%29%28%3f%3cg2%3eemi%5bac%5d%29%7c%28%3f%3cg1%3egyn%29%28%3f%3cg2%3eecolog%5biy%5d%29%7c%28%3f%3cg1%3ehyper%29%28%3f%3cg2%3eemia%29%7c%28%3f%3cg1%3ehyperglyc%29%28%3f%3cg2%3eemi%5bac%5d%29%7c%28%3f%3cg1%3ehypoglyc%29%28%3f%3cg2%3eemi%5bac%5d%29%7c%28%3f%3cg1%3ehypokal%29%28%3f%3cg2%3eemi%5bac%5d%29%7c%28%3f%3cg1%3ehypovol%29%28%3f%3cg2%3eemi%5bac%5d%29%7c%28%3f%3cg1%3ehypox%29%28%3f%3cg2%3eemia%29%7c%28%3f%3cg1%3eleuk%29%28%3f%3cg2%3eem%29%7c%28%3f%3cg1%3eorthop%29%28%3f%3cg2%3eed%29%7c%28%3f%3cg1%3eoxyh%29%28%3f%3cg2%3eemoglobin%29%7c%28%3f%3cg1%3etox%29%28%3f%3cg2%3eemia%29%29%28%3f%3cg3%3e%5cw*%29&i=Eons&r=%24%7bg1%7da%24%7bg2%7d%24%7bg3%7d](test)
The sad thing is you can't use `\L` 😕

**Comment by Ding-adong** [comment]
Well that worked except for the E ha ha. I could have saved myself a lot of hassle if I'd cross-checked with regexstorm as it uses .net.

**Comment by OmrSi** [comment]
@Ding-adong Yeah. They've been asking regex101 to add .NET, but they haven't added it yet.
I use RegexBuddy to test my expressions but the site is needed for sharing.
Yep, the `E` is a problem, but you could look for `\p{Ll}\p{Lu}` to check these cases...

**Comment by Ding-adong** [comment]
I leave SE to deal with that. Perhaps remove words, only a few, that requires a char at the beginning of a word. Your way worked in multiple replace of SE but not when I'd put it in eng_ocrreplacelist regex section. Why?

**Comment by OmrSi** [comment]
`<RegEx find="(?i)(?:(?&lt;g1&gt;alkal)(?&lt;g2&gt;emia)|(?&lt;g1&gt;an)(?&lt;g2&gt;emi[ac])|(?&lt;g1&gt;an)(?&lt;g2&gt;esthe[st]i)|(?&lt;g1&gt;arch)(?&lt;g2&gt;eolog[iy])|(?&lt;g1&gt;bougainvill)(?&lt;g2&gt;ea)|(?&lt;g1&gt;c)(?&lt;g2&gt;esar[ei]an)|(?&lt;g1&gt;encyclop)(?&lt;g2&gt;edi)|\b(?&lt;g1&gt;)(?&lt;g2&gt;eon)|(?&lt;g1&gt;)(?&lt;g2&gt;esthet[ei])|(?&lt;g1&gt;)(?&lt;g2&gt;etiolog[iy])|(?&lt;g1&gt;f)(?&lt;g2&gt;ecal)\b|(?&lt;g1&gt;f)(?&lt;g2&gt;eces)|(?&lt;g1&gt;glyc)(?&lt;g2&gt;emi[ac])|(?&lt;g1&gt;gyn)(?&lt;g2&gt;ecolog[iy])|(?&lt;g1&gt;hyper)(?&lt;g2&gt;emia)|(?&lt;g1&gt;hyperglyc)(?&lt;g2&gt;emi[ac])|(?&lt;g1&gt;hypoglyc)(?&lt;g2&gt;emi[ac])|(?&lt;g1&gt;hypokal)(?&lt;g2&gt;emi[ac])|(?&lt;g1&gt;hypovol)(?&lt;g2&gt;emi[ac])|(?&lt;g1&gt;hypox)(?&lt;g2&gt;emia)|(?&lt;g1&gt;leuk)(?&lt;g2&gt;em)|(?&lt;g1&gt;orthop)(?&lt;g2&gt;ed)|(?&lt;g1&gt;oxyh)(?&lt;g2&gt;emoglobin)|(?&lt;g1&gt;tox)(?&lt;g2&gt;emia))(?&lt;g3&gt;\w*)" replaceWith="${g1}a${g2}${g3}" />`

**Comment by Ding-adong** [comment]
Worked that one out after I posted last time. Annoying having too convert <> all the time from xml file to website and back. Cheers for your help.

**Comment by OmrSi** [comment]
Yeah, I remembered it when I saw another regex on the list. Anytime, mate. ^_^
