### ISSUE TITLE
Error when batch OCRing to SRT

### ISSUE THREAD

**Issue by orbittwz** [SubtitleEdit/subtitleedit#3395]
![image](https://user-images.githubusercontent.com/45605734/53266573-d62c0600-36e9-11e9-9e41-a4d6e31dd0ef.png)

Latest BETA 3.5.9b41
Thanks

**Comment by orbittwz** [comment]
![image](https://user-images.githubusercontent.com/45605734/53266919-d4167700-36ea-11e9-9c35-6841d9355e4f.png)
happened also with the latest 3.5.9 release c424586

**Comment by orbittwz** [comment]
also 3.5.8 !! what is happening??

**Comment by orbittwz** [comment]
also 3.5.7!
maybe something leftover from last installation??

**Comment by OmrSi** [comment]
Does it happen when you try to OCR one file? not in Batch?

**Comment by orbittwz** [comment]
Nope, but wait, think it's a problem with the Tesseract
I downloaded Tesseract4, and the single file OCRing passed...
Seems it doesn't display an error on batch OCRing

**Comment by orbittwz** [comment]
yep, passed the first file, so it's fine
maybe Tesseract302 needs to be removed??

**Comment by OmrSi** [comment]
I don't think so, they found 302 to be faster and better, so he added 4 as an optional download.

**Comment by OmrSi** [comment]
Plus I just tested it and it works fine here:
![screenshot 216](https://user-images.githubusercontent.com/20923700/53271098-15f8ea80-36f6-11e9-8b12-94ea91805704.png)

**Comment by orbittwz** [comment]
It's not the same format, i'm doing OCRing of IDX/SUB

**Comment by OmrSi** [comment]
@orbittwz Tested on both:
![screenshot 217](https://user-images.githubusercontent.com/20923700/53271438-2067b400-36f7-11e9-8056-fbfbddb4701e.png)

P.S. I'm not saying there isn't an issue, that testing so he could have enough information...

**Comment by orbittwz** [comment]
OK, i'll wait for an update from @niksedk

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
