### ISSUE TITLE
Support for Hardcoded Subs

### ISSUE THREAD

**Issue by ghost** [SubtitleEdit/subtitleedit#340]
I have tried using AVISubrip and Subrip to rip subtitles but both of them weren't helpful. It is really hard to rip subtitles off of the videos and there is no other alternative. Would you consider adding support for hard coded subtitles?

**Comment by OmrSi** [comment]
@niksedk Closed?

**Comment by OmrSi** [comment]
@niksedk Also related to https://github.com/SubtitleEdit/subtitleedit/issues/1328?
Although this was before it.

**Comment by RaXorX** [comment]
https://github.com/apm1467/videocr
Could this project possibily a solution or inspire one perhaps? I tried using it in the past with some troubles.
