### ISSUE TITLE
Translate with Bing screen-scraping seems to mess it up

### ISSUE THREAD

**Issue by Sopor-** [SubtitleEdit/subtitleedit#3402]
When i use `Translate with Bing screen-scraping` the subtitle will be totally wrong. I will attach the en and the sv and you can see in the beginning that something isn't right. It seems to repeat the text.
Checkout line 17 and line 40 in the `sv` file and compare it with the `en` file. [sv_en.zip](https://github.com/SubtitleEdit/subtitleedit/files/2897337/sv_en.zip)
If i use `Google screen-scraping` it seems to work but i don't run Windows 10 so i have no Edge so i'm stuck with Bing.

**Comment by niksedk** [comment]
Strange... seems to work here:
![image](https://user-images.githubusercontent.com/1261331/53301656-cdf0d980-3855-11e9-8c17-daf6c8d9643c.png)

You can try lowering the bulk size to e.g. 100... but it will be slower.

**Comment by Sopor-** [comment]
Very strange because this is not the first time this has happening. That was the reason i wanted to report it.

**Comment by Sopor-** [comment]
Now it seems to be wrong lines as you can see.

![image](https://user-images.githubusercontent.com/5789283/53687994-aeb5e880-3d3c-11e9-97e4-9cc0b86f75b4.png)

And it will be more and more

![image](https://user-images.githubusercontent.com/5789283/53688002-de64f080-3d3c-11e9-9378-fabe10e6c226.png)

**Comment by niksedk** [comment]
thx :)
It seems a blank line confuses the plugin. I will look into it.

**Comment by niksedk** [comment]
Blank lines should now be fixed - please test updated plugins :)

Fixed in commit: https://github.com/SubtitleEdit/plugins/commit/e5045a9a05f4f84d6d834561daa664476f87860f

**Comment by Sopor-** [comment]
No big deal but should the `Update available` be shown twice?

![image](https://user-images.githubusercontent.com/5789283/53694734-55d56700-3db3-11e9-8ed5-20f41a23c33f.png)
