### ISSUE TITLE
[Question] How remove color tag or font name tag without remove italic and bold tags???

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#3403]
How remove color tag or font name tag without remove italic and bold tags???

and without use regex.

we have in context menu a option to add font color and font name, but there is no option to remove it

**Comment by marb99** [comment]
How romeve color tag or font name tag without romeve italic and bold tags???

**Comment by OmrSi** [comment]
I don't think you can, tags are tags, everything between <> or {} is a tag.
You also can't remove all bold or italic tags from the whole file.
And yes, bold/italic can be toggled because they have a constant format which it <i><\i>, while color and font tags always change depending on the color\font name and whether there is another tag in the line.
Just use the following regex and be done with it `<.{3,}?>`

**Comment by marb99** [comment]
Normaly I use the regex to remove it, but is weird you have an option to add and none to remove it


![1](https://user-images.githubusercontent.com/7856897/53294167-55e4ce00-37d9-11e9-8854-5b1c70538d7f.gif)

**Comment by OmrSi** [comment]
@marb99 Nice regex, what about this one? `<[^>]{3,}>`

**Comment by OmrSi** [comment]
Anyway, about your main question. What about bold/italic tags, why isn't there a way to remove those?

Now, if you say there is, which is using the same shortcut to toggle them off, well that adds a tag to the lines which don't contain a tag. 
So if assume the same for color, then what color or font name would be assigned when toggling?

In general, right now, to my knowledge, there isn't a way to remove them. 
Will @niksedk add it? I guess we'll see. :D

**Comment by LeonCheung** [comment]
Imho, I agree there could be some flexibility enhancement, maybe like this:   :)
![jd](https://user-images.githubusercontent.com/494788/53294771-4b055a00-3828-11e9-96bb-59e098cf062a.png)

**Comment by OmrSi** [comment]
@LeonCheung damn it! Always so convincing with your photos. 😄

**Comment by LeonCheung** [comment]
@OmrSi Phew, that's all I can do... 😂

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/2953

**Comment by marb99** [comment]
@OmrSi  I agree with you in part, but italic and bold is comum on srt format other tags not,
if you add an option to add something to the program should be an option to reverse this option.

@LeonCheung yes, should be like that :)

**Comment by ivandrofly** [comment]
Try plugin

![image](https://user-images.githubusercontent.com/6579818/53298500-e269ad80-3826-11e9-9408-a65350aa6e7e.png)

**Comment by niksedk** [comment]
@LeonCheung: like this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/53303290-e1f20680-3868-11e9-81c4-185ed02bf768.png)

**Comment by OmrSi** [comment]
@niksedk Initial testing, Looks great.
1. Remove font name not working
2. Shortcut "Remove formatting" doesn't work.
3. Remove alignment doesn't work if it was with another tag {\an8\fs10}/{\fs20\an8}.
4. This is closed https://github.com/SubtitleEdit/subtitleedit/issues/2953

**Comment by LeonCheung** [comment]
@ivandrofly That's an interesting plugin, maybe off topic but it also removes SE bookmarks while trying to remove or add colors.

@niksedk Cool! exactly like that. And I confirm what @OmrSi found.

**Comment by niksedk** [comment]
Beta updated with fixes 1-3: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Maybe improvement needed for fonts with non-English name. try this:
`<font face="微软雅黑 Light">Hello World.</font>`

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk Now that you worked on this, the other issues about the position tags might be easier: https://github.com/SubtitleEdit/subtitleedit/commit/c6ec47e504b54851060a9618282a85aaf6ba55cc#commitcomment-31997602

**Comment by niksedk** [comment]
@OmrSi: OK, multi tags should now be better supported I hope: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk It works perfectly when you use the shortcuts from the list, but doesn't inside the text box.

**Comment by LeonCheung** [comment]
Perfect.

**Comment by marb99** [comment]
Thanks :)

**Comment by OmrSi** [comment]
It works perfectly when you use the shortcuts from the list, but doesn't inside the text box.

**Comment by OmrSi** [comment]
It works perfectly when you use the shortcuts from the list, but doesn't inside the text box.
![screenshot 224](https://user-images.githubusercontent.com/20923700/53347795-82f0c800-3922-11e9-806f-bdcaebf9550c.png)
![screenshot 223](https://user-images.githubusercontent.com/20923700/53347801-86844f00-3922-11e9-81c2-32e7ecb8958f.png)

**Comment by niksedk** [comment]
Thx for testing guys :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Everything is perfect, Thank you! <3
