### ISSUE TITLE
Bookmarks and column width

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#3407]
After adding bookmarks, the column width for #numbers keeps still, so numbers cannot be seen unless expanding manually.

![aa](https://user-images.githubusercontent.com/494788/53315434-19f75900-38fe-11e9-80be-e117d048c89b.png)

**Comment by OmrSi** [comment]
Did that start happening recently? 
I worked with him on this, the size should be constant like it is in the settings file, then when activating bookmarks, it adds about 17 to the width. So that shouldn't be happening.

**Comment by OmrSi** [comment]
Latest beta:
![screenshot 221](https://user-images.githubusercontent.com/20923700/53337013-ca6a5a80-3908-11e9-8e99-9c492d944ddc.png)
![screenshot 222](https://user-images.githubusercontent.com/20923700/53337018-ce967800-3908-11e9-9662-e10e6d8c7402.png)

**Comment by LeonCheung** [comment]
Yes, at least for today's beta build.

**Comment by OmrSi** [comment]
@LeonCheung I've worked with bookmarks more since then, haven't had this issue.
What are the steps to recreating it?

**Comment by matheusguifer** [comment]
@OmrSi thank you so much for developing bookmarks, it's extremely helpful! Is there a way they could be visible over network sessions? I collaborate with someone to review my subtitles (as I have mild hearing loss) and I used bookmarks to specify my doubts.

(Sorry if this is the wrong place to ask this. first time using GitHub)

**Comment by OmrSi** [comment]
@matheusguifer I wish.
@niksedk Just adds the names of everyone who reported/helped with testing the feature.
I didn't actually do anything, sadly.

**Comment by niksedk** [comment]
@OmrSi: You did a lot of testing and also provided good ideas :)

@matheusguifer: sorry, that's unlikely atm (the server stuff is based on obsolete tech, so that should probably be fixed first)

**Comment by LeonCheung** [comment]
Cool, then I think this thread completes the final mission. :) BTW, I think it's nice to allow editing existing bookmarks, but that should be another topic. Closing. Good luck guys.
