### ISSUE TITLE
.js script/css for copying results in copypaste translation

### ISSUE THREAD

**Issue by o11598652** [SubtitleEdit/subtitleedit#3408]
The button for copying the translated output on google's website is on bottom of the page, so pasting and scrolling could be smoother if a .css template for firefox changed the position of default's copying buttons  position for the top of the page. I believe it's not that hard to provide a solution for this.
An alternative would be a tampermonkey script that copies automatically the text.

Does anyone know how to do it? It's really tiresome to scroll+click on copy.

**Comment by OmrSi** [comment]
Why scroll and copy? You can just Select All and use ctrl + C.
Or am I missing something?

**Comment by niksedk** [comment]
@o11598652: If you're running Windows 10 you can probably use the translate plugin "GT screen-scraper".

**Comment by OmrSi** [comment]
If not, why not use the "End", doesn't it go to the end of the page? so no need for scrolling.

**Comment by OmrSi** [comment]
If not, why not just use "End" to go to the end of the page?
