### ISSUE TITLE
[Bug] irregular SRT file, worked fine in 3.5.8

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3411]
I just got a file for work and noticed it worked fine in 3.5.8 but now it doesn't.
The file has dots instead of commas in the timestamp, and now SE puts all the lines in one line inside SE.
Here is the file: [test.zip](https://github.com/SubtitleEdit/subtitleedit/files/2902209/test.zip)

**Comment by niksedk** [comment]
thx - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Thank you. And how much did Sopor pay you this time to write his name instead of mine?  Hahaha.  jk.
