### ISSUE TITLE
[Improvement] Add checkboxes to 'Apply duration limits' dialog

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#3412]
Most of the times when I use this feature, I want to enforce only a minimum duration.
To prevent the shortening subtitles, I now enter 9999 in the 'Max duration' input box.
Maybe it would be useful to add checkboxes to the options to toggle these options, for example:

![se1](https://user-images.githubusercontent.com/3516155/53375336-3fff1680-395b-11e9-917f-ceba896afa82.png)

There could be the following bonus option to interact with scene changes:
- [ ] "Don't extend past shot cuts": It's possible that there are titles shorter than the minimum duration, because the end time is on (or near) a shot cut. This option prevents these subtitles from getting extended past the shot cut.

I should be able to add the checkboxes myself and add a PR. I'm not sure if there's access to the loaded shot cuts from this dialog?

**Comment by Flitskikker** [comment]
Added PR for the checkboxes.

**Comment by niksedk** [comment]
Looks good - and even language tags :)
To make it completely perfect you can check the tab index order - could you fix it?

**Comment by Flitskikker** [comment]
@niksedk Thanks! I've updated the tab index order, but I can't seem to have it go to the ListView before the OK button, while the tab index of the ListView is lower than the OK button.

**Comment by niksedk** [comment]
@Flitskikker: thx :)
Made a minor modification of tab order + enable/disable numeric up/down boxes.

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by Flitskikker** [comment]
@niksedk Good catch!

I think this one can be closed -- I'll create a separate issue later with shot cut related suggestions.
