### ISSUE TITLE
[Request] Add option to don't shorten subtitles for the 'Recalculate' option in the 'Adjust durations' dialog

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#3414]
It would be useful to add a checkbox called "Only extend subtitles" when using the Recalculate option in the Adjust durations dialog, so that subtitles won't get shorter than they currently are.

I think I should be able to add this in myself and create a PR, but I'm not sure about the 'consequences' regarding savestate, localization, etc.

**Comment by Flitskikker** [comment]
Added PR.

**Comment by niksedk** [comment]
Looks good (and good idea also) - and even language tags :)
To make it completely perfect you can check the tab index order - could you fix it?

**Comment by Flitskikker** [comment]
@niksedk Thanks! Fixed tab index order. (Sorry, entered commit message in the wrong box.)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by Flitskikker** [comment]
Thanks!
