### ISSUE TITLE
[Request] Add setting for optimal CPS and use it when creating subtitles

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#3415]
At the moment, when you create a subtitle and you let it automatically set the length as you type, it uses the setting for max. CPS.

As the name suggests, this is the maximum CPS that should not be exceeded (~15 CPS for professional Dutch and Scandinavian subtitles). Wherever possible, translators should try to use a 'target CPS'; the optimal reading speed (~11 CPS for professional Dutch and Scandinavian subtitles).

Would it be possible to add an "Optimal CPS" to the settings and then using that when creating a new subtitle?

The "Adjust durations" dialog already features an Optimal CPS box, which then can be connected.

Information about optimal and maximum CPS / reading speed:
- https://www.jostrans.org/issue28/art_pedersen.php (see 5.3.3)
- https://ondertitelaar.wordpress.com/2015/07/20/leestijd/ (Dutch)
- https://undertekstning.dk/english/ (Danish and English)

**Comment by Flitskikker** [comment]
I saw in the code that the optimal CPS has already been implemented (not only for "Adjust durations").
I've added a PR that makes this value configurable via Settings.

**Comment by OmrSi** [comment]
Yeah, it's there, you could change the value from the settings file, but it wasn't available in the UI.

**Comment by niksedk** [comment]
PR looks good - and even language tags :)
To make it completely perfect you can check the tab index order - could you fix it?

**Comment by Flitskikker** [comment]
@niksedk Thanks! Fixed tab index order. (Sorry, entered commit message in the wrong box.)

**Comment by Flitskikker** [comment]
@niksedk Thanks! Fixed tab index order.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by Flitskikker** [comment]
Thanks!
