### ISSUE TITLE
[Bug] Unbreak affects original in translator's mode, traced to the commit

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3418]
I traced it back to this commit [5d7b326](https://github.com/SubtitleEdit/subtitleedit/commit/5d7b326c1233d551da213d60f151ddfaacdef18d)
After this commit, unbreak started affecting the original in the translator's mode.

Also, could you make "column -> delete text" not affect the original? You usually just want to delete the translated...

**Comment by OmrSi** [comment]
@niksedk Can you take a look at this one?

**Comment by OmrSi** [comment]
@niksedk Would you check this?

**Comment by niksedk** [comment]
Text box unbreak/auto-break shortcuts should now only affect the active text box: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk Thank you. <3
It's working perfectly.
I found this minor while testing: original box stays active and info are not reset after deleting all lines:
![screenshot 244](https://user-images.githubusercontent.com/20923700/53750841-8a304c80-3eb3-11e9-82d8-da72a2f9fc64.png)

About the  "column -> delete text", @darnn mentioned here too: https://github.com/SubtitleEdit/subtitleedit/issues/3386#issuecomment-467971852

**Comment by niksedk** [comment]
thx - beta updated again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
How is this?

**Comment by OmrSi** [comment]
The info are gone but the text box is still active.
Also, the "column -> delete text" issue is still there.

**Comment by OmrSi** [comment]
Cool. You can close this issue with the "column -> delete text" commit if you intend to fix it, or you can close it now if you don't.
In both cases, than you so much.

This is just a minor idea, but shouldn't the "Reopen" be greyed out if there is nothing to reopen?

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
How is it?

Not to sure about the delete column text... later in any case ;)

**Comment by OmrSi** [comment]
@niksedk Works well.

About the delete column text, the behavior changes in somewhere in the betas of 3.5.9, it's not deleting the original in 3.5.9, just in the beta, I don't know if that's intentional.
You can close this if you want.
