### ISSUE TITLE
[Bug] Original's "Total length" not in the right position

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3425]
My screen is FHD, I don't know if that's the issue, but I tested with the program's DPI and the system's:
![screenshot 234](https://user-images.githubusercontent.com/20923700/53526703-a320b280-3aed-11e9-8ab0-462244901b98.png)
![screenshot 233](https://user-images.githubusercontent.com/20923700/53526796-cd727000-3aed-11e9-94d6-74cd3adbb6b0.png)

**Comment by niksedk** [comment]
Did you mean about the vertical alignment?
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip `
Total length is now hidden if make the window very small.

**Comment by OmrSi** [comment]
Yes. I did mean the vertical alignment. ^^"
And it is fixed, thank you. <3

The only problem I see left is this https://github.com/SubtitleEdit/subtitleedit/issues/3418 as It used to work fine before version 3.5.4 so I went back and traced it to the commit that started the issue, hope you can take a look. 
Thanks again. :)
