### ISSUE TITLE
PGS export: Position discarded for coloured subtitles

### ISSUE THREAD

**Issue by LeXXuz** [SubtitleEdit/subtitleedit#3427]
Subtitle Edit 3.5.9:

Exporting SRT subtitles to Blu-ray PGS format discards positioning tags within SRT subs WHEN there are also colouring tags in the same line.
example:

{\an8}This is a test.   => will be exported at top of screen (as it should)

(font color="#ffff80"){\an8}This is a test.(/font) => will be exported at bottom of screen (as it shouldn't)

(note: I changed the <> brackets for () in here so they won't be recognized as code)

**Comment by niksedk** [comment]
Thx :)
Definitively a bug somewhere. 
SE kinda expects the alignment tags to be first - and setting font did NOT do that (italic does) , which should be fixed here: 
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by LeXXuz** [comment]
Glad to help. :)
Thx for the quick fix.
