### ISSUE TITLE
[Bug] List not going to video position

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3430]
Steps to recreate:
1. Go to any line and play the video so that the list is focused on the line.
2. Go down the list to see another line elsewhere with setting video position to it. (One click on the line, not double.)
3. Play the video, you'll see that the list will go up a little but it doesn't reach the line that is being played.
![untitled project](https://user-images.githubusercontent.com/20923700/53581619-9734ff00-3b86-11e9-8033-d6df1cccb932.gif)
Notice that I was at 818 but it returned to 823.

**Comment by niksedk** [comment]
Nice catch :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

(regression from smoother waverform go to next sub fix)

**Comment by OmrSi** [comment]
Oh, yeah. I remember that commit. :D
