### ISSUE TITLE
-kun, -san become captalized when using spell check

### ISSUE THREAD

**Issue by PannenkoekenNL** [SubtitleEdit/subtitleedit#3433]
Running spell check causes "-kun", "-san" etc. to automatically become capitalized. Eg "Tora-san" becomes "Tora-San".

**Comment by niksedk** [comment]
You can turn off "Auto fix names where only casing differ" in Options -> Settings -> Tools:
![image](https://user-images.githubusercontent.com/1261331/53632361-09ecbb80-3c15-11e9-9e85-04cec620f895.png)

Or you can add "Tora-san" to the names list.

Or SE could be modified to ignore "-san" and "-kun" and other Japanese honorifics is some way...

**Comment by PannenkoekenNL** [comment]
Thanks, I'll turn that first option off.

**Comment by OmrSi** [comment]
@niksedk Closed?

**Comment by OmrSi** [comment]
@niksedk Also Closed, I think?
