### ISSUE TITLE
Hide menu bar option

### ISSUE THREAD

**Issue by PannenkoekenNL** [SubtitleEdit/subtitleedit#3435]
It would be nice to have a option to hide the menu bar at the top by default, and having a shortcut (Alt in MPC-HC) to show it which will hide it again if you click on a option in the menu bar. That's how it works in MPC-HC.

**Comment by OmrSi** [comment]
MPC is a video player, so you don't need the menu bar all the time, this is a subtitling tool, I personally use items from the menu many times during my work, it would be... inconvenient to have to show it each time you need something from it, In my opinion at least.

**Comment by OmrSi** [comment]
Add to that, I, and many other people have shortcuts where the "Alt" is used, and sometimes when I use that shortcut, the menu is selected by accident, so if you make it hidden, it will show up each time we use those shortcuts.

**Comment by niksedk** [comment]
You can hide the toolbar, by hiding all toolbar buttons in Options -> Settings... could be useful for when working on a small laptop (not shortcut, sorry).

**Comment by OmrSi** [comment]
@niksedk He's asking about the "menu bar" not the "toolbar".

**Comment by niksedk** [comment]
Ah, OK, the menu bar...
