### ISSUE TITLE
Error when going to the previous subtitle.

### ISSUE THREAD

**Issue by dimax0303** [SubtitleEdit/subtitleedit#3436]
Error when going to the previous subtitle.
Help correct the error. Assigned transition to the previous subtitle hotkey. I click on this hot button, an error appears. Windows system 7/64.
Sorry my bad English)  
![error](https://user-images.githubusercontent.com/48198920/53716393-d785cd00-3e65-11e9-9fd3-b57825ce1cdf.jpg)

**Comment by niksedk** [comment]
@dimax0303: thx for the info - how can I re-create this?

**Comment by niksedk** [comment]
Probably same issue as #3486
