### ISSUE TITLE
[Bug] Another list syncing issue, missing a line

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3437]
@niksedk I was QCing a file and I noticed this, steps to recreate:
1. Go to the last visible line in the list.
2. Play the video.
3. When the list moves to the line after, it doesn't show up.
![untitled project](https://user-images.githubusercontent.com/20923700/53819025-cd50f500-3f71-11e9-900b-e40a401bf7f6.gif)

Notice that line 56 didn't show up!

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Perfect, Thank you again. ^_^

**Comment by OmrSi** [comment]
@niksedk Do you think it's better like this or is it better to always center the line that is being played? I can't decide, tbh.

**Comment by niksedk** [comment]
thx for verifying :)
