### ISSUE TITLE
Translating without paying for an API key. 

### ISSUE THREAD

**Issue by rgfx** [SubtitleEdit/subtitleedit#3438]
Always translating English to Spanish subs, I need a programmatic way to translate subtitles again now that our overlords decided to charge for that service, after having us continually refining their AI.  

Does anyone know a good way to do this, without paying for an API key. 

Thanks.

**Comment by niksedk** [comment]
Our overlords are smart ;)

Latest version of SE can do some free translating via GT - but do check the plugins:
- GT screen-scraper, Google translate, requires .net framework 4.6.2 or later + Win10 with April update
- BT screen-scraper, Bing Translate
- DeepL screen-scraper, requires .net framework 4.6.2 or later + Win10 with April update
- PROMPT translate, requires .net framework 4.6.2 or later + Win10 with April update
- Baidu translate

Also, the copy-paste translate plugin should work with most translation web pages - see #3246

There's also a few comments about translating in this thread: https://github.com/SubtitleEdit/subtitleedit/issues/3246#issuecomment-451738571

**Comment by Ding-adong** [comment]
What about win 7 ?

**Comment by niksedk** [comment]
If you're not latest Win 10 then `GT screen-scraper` and `DeepL screen-scraper` will not work.

**Comment by Ding-adong** [comment]
Why win 10 only, win 10 is crap. Never mind.

**Comment by orbittwz** [comment]
![image](https://user-images.githubusercontent.com/45605734/102006649-3959b300-3d2b-11eb-9dbc-ee9b1f3b76ff.png)
does this have a solution? after translating multiple files with google, the program returns an error about free api quota exceeded .
I'm pretty sure setting a 2.5 seconds pause between each call to the api will solve this...
