### ISSUE TITLE
Regex: Replace the 1st group followed by the char "0"?

### ISSUE THREAD

**Issue by teodargent** [SubtitleEdit/subtitleedit#3442]
I tried [this](https://stackoverflow.com/questions/10907440/how-do-i-group-regular-expressions-past-the-9th-backreference), but `\x30` is not recognized as `0` and `$10` is recognized as literal. 
[Regex](http://regexstorm.net/tester?p=%28%5b%c2%a3%24%e2%82%ac%5cd%5d%29o&i=%e2%82%aco.2&r=%241%5cx30)

**Comment by OmrSi** [comment]
Easy, use this [Regex](http://regexstorm.net/tester?p=%28%3f%3csign%3e%5b%c2%a3%24%e2%82%ac%5cd%5d%29o&i=%e2%82%aco.2&r=%24%7bsign%7d0)

**Comment by teodargent** [comment]
Nice! Thanks!

**Comment by OmrSi** [comment]
You got it. ^_^

**Comment by OmrSi** [comment]
@teodargent You can also use [this](http://regexstorm.net/tester?p=%28%5b%c2%a3%24%e2%82%ac%5cd%5d%29o&i=%e2%82%aco.2&r=%24%7b1%7d0) which doesn't need a named group.

**Comment by OmrSi** [comment]
@teodargent You can also use this which doesn't need a named group.
`Putting curly braces around the digit ${1} isolates the digit from any literal digits that follow. This works in the JGsoft applications, Delphi, .NET, Perl, PCRE2, PHP, Boost, and XRegExp`

**Comment by OmrSi** [comment]
@niksedk Closed.

**Comment by OmrSi** [comment]
@niksedk Closed.

**Comment by OmrSi** [comment]
@teodargent @niksedk Closed.

**Comment by OmrSi** [comment]
@teodargent @niksedk Closed.
