### ISSUE TITLE
How to create a OCR Dictionary for lang that download list doesn't provide an option

### ISSUE THREAD

**Issue by Araynilmar** [SubtitleEdit/subtitleedit#3443]
When I use the "Binaray Image Compare" method for OCR subtitles, I would like to have a dictionary to help me correct the OCR errors, but unfortunately the language is not in the language list to download.

So I want to create a dictionary myself for Sino-Tibetan languages, Such as Chinese, Taiwanese, Cantonese etc that download list doesn't provide an option.

Where can I find the Property Expansion of the OCR Dictionary?

**Comment by niksedk** [comment]
What OCR method are you using?
If you're using Tesseract read more here: https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract

**Comment by Araynilmar** [comment]
> What OCR method are you using?
> If you're using Tesseract read more here: https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract

Binaray Image Compare

**Comment by gabriellluz** [comment]
I always import my images on Finereader. It works great for Cantonese, Mandarin and Japanese.
All you have to do is export the subtitle images and then import them on Finereader.
Then, you choose Save one outputfile for each input file.

**Comment by niksedk** [comment]
Hm, the OCR fix list works with spell check... and if a hunspell dictionary does not exist (I could not find one for Chinese) then it's a bit hard - you could try to create an empty hunspell dictionary (like this: 
[zh-CN.zip](https://github.com/SubtitleEdit/subtitleedit/files/2948233/zh-CN.zip)  ) and use `<PartialLinesAlways>`  and `<PartialWordsAlways>`  from the `zho_OCRFixReplaceList.xml`.

**Comment by supermansaga** [comment]
In 2022, do we have better solutions now? The latest Subtitle Edit 3.6.4 portable still doesn't have a dedicated Chinese dictionary to handle .sup subtitles. Is Finereader free? The latest Tesseract is now 4.1.1. How do I make it work with Subtitle Edit 3.6.4 which comes the old 3.0.2 by default? Thx
