### ISSUE TITLE
spell check fails to ignore Cyrillic or Greek characters in English subtitles

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#3445]
I sometimes face supposedly complete English subtitles, where actually some Greek or Cyrillic characters are used.
When trying to spell check these subtitles, SE meticulously picks up the words with Greek or Cyrillic characters as wrong spelling ones, which is right thing to do.

What I want SE to be able to do is... a function to convert these characters into [A-Za-z] letters accordingly (before SE does spell check). That way, spell check only picks up truly wrong words.

For Cyrillic characters,
АВСЕНМРТасеорху should be handled.
(ABCEHMPTaceopxy accordingly)
https://www.unicode.org/charts/PDF/U0400.pdf

For Greek characters,
ΑΒΕΖΗΙΚΜΝΟΡΤΥΧο should be handled.
(ABEZHIKMNOPTYXo accordingly)
https://www.unicode.org/charts/PDF/U0370.pdf

I by myself made a script to convert these subtitles. But it would be very helpful if SE has such a function in Fix common errors.

**Comment by Ding-adong** [comment]
Put it in your ???_OCRFixReplaceList_User in dictionary dir, as that is your personal converter. Then use fix common errors.

**Comment by niksedk** [comment]
You could also make a replace list in Edit -> Multiple replace

**Comment by Ding-adong** [comment]
@niksedk Instead of clicking fix common errors then due process; then click edit, click multiple replace... Why don't you put multiple replace in fix common errors with check box and open button to make changes? Thus all in one place.

I have netflix toolbar checked in settings but it doesn't show up.

**Comment by OmrSi** [comment]
@Ding-adong https://github.com/SubtitleEdit/subtitleedit/issues/2465

Also, I for one, often use Multiple replace outside of fix common errors, as fix common errors don't always have the right fixes for my language, but Multiple replace always has the right ones.
So I can apply Multiple replace immediately, but I have to check everything in FCE.

**Comment by niksedk** [comment]
@Ding-adong: The Netflix icon only shows up for "Netflix Timed Text" or "Timed Text 1.0" (and EBU stl in latest beta).

**Comment by taxen** [comment]
OK. I made a new group in Multiple replace and it works fine.
I thought another entry Fix common errors would be handy for the problem is common.
