### ISSUE TITLE
[REQUEST] Split subtites (specific lines)

### ISSUE THREAD

**Issue by slthelion** [SubtitleEdit/subtitleedit#3446]
Hello !

If you can add in the next version , the posibility to split subtitles by specific numbers of lines.
For exemple I have a subtitle with over 5000 lines and I need to split that subtitle in five subtitles by specific number of lines. Here : http://prntscr.com/mvf16z to have a setting specifing the exact lines (543,1020,2040,3010,4010). Subtitle Workshop let's you split subtitle by item number (line) but you need to reload everytime the subtitle to split the others.

**Comment by niksedk** [comment]
Hello, it's much faster just to let SE decide parts:
![image](https://user-images.githubusercontent.com/1261331/54070341-fbc71c80-425e-11e9-87c0-17d4b5a55379.png)

If you really want to determine the parts yourself, then just select the lines in the main list view, right click and choose `Save selected lines as...`.
![image](https://user-images.githubusercontent.com/1261331/54070354-38931380-425f-11e9-8ab6-ce176d8e7783.png)

**Comment by zicksl** [comment]
For me it's important to determine what parts needs to be splited. I'm using the feature to import images and it's a series over 10 episodes and I want to ocr all 10 episodes in one go and after I save the work to split them up by the number of lines. But with save selected lines works that too, but I wanted to be faster than that. Only to add the exact lines and software to the rest.
