### ISSUE TITLE
Common OCR errors (English)

### ISSUE THREAD

**Issue by SvenErik1968** [SubtitleEdit/subtitleedit#3447]
It does not fix single lover case l's that should have been capital I when it is followed by a 3 period ellipsis [...], however, if it is a true ellipsis […], the error is found.

Example:
```
1
00:11:56,716 --> 00:11:58,550
Sorry if l... Uh...

2
00:11:58,716 --> 00:12:00,550
Sorry if l… Uh…
```
Ends up as:
```
1
00:11:56,716 --> 00:11:58,550
Sorry if l... Uh...

2
00:11:58,716 --> 00:12:00,550
Sorry if I… Uh…
```

Not a big issue for me since I always changes ... to … but most don't do that as far as I can see on various subtitle sites.

**Comment by Ding-adong** [comment]
Worked for me. Check that the line is in your ocrfixreplacelist `    <LinePart from=" i... " to=" I... " />`

**Comment by OmrSi** [comment]
@niksedk Also closed?
