### ISSUE TITLE
Can't edit image settings for Blu-ray SUP export

### ISSUE THREAD

**Issue by globalnomad** [SubtitleEdit/subtitleedit#3448]
On the latest build, I am unable to edit the Image Settings for exporting to blu-ray SUP. I am working from an SRT file. The only options that are active are:

- Video res
- Simple rendering
- 3D
- Ful lframe image
- Frame rate
- Line height

I can't adjust anything else as they are all disabled. I've never had this issue in prior builds.

**Comment by niksedk** [comment]
Hm, I cannot re-create this - could you attach a screenshot?

**Comment by globalnomad** [comment]
I poked around a bit in the SRT file and realized it was a non-standard SRT file and it seemed to have styling written into the headers (including margins). It seems to be a file generated by Aegisub and saved as an SRT. I re-saved a standard SRT with Subtitle Edit then used that one to produce a SUP, which re-enabled the controls. Headers of the non-standard file and an image of the de-activated controls (when using the non-standard SRT file) below.

## Headers

> [Script Info]
> ; Script generated by Aegisub 3.2.2
> ; http://www.aegisub.org/
> Title: Default Aegisub file
> ScriptType: v4.00+
> WrapStyle: 0
> ScaledBorderAndShadow: yes
> YCbCr Matrix: None
> 
> [Aegisub Project Garbage]
> Last Style Storage: Default
> 
> [V4+ Styles]
> Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
> Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
> Style: Arial,Arial,42,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
> 
> [Events]
> Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text

## Deactivated Controls
![image](https://user-images.githubusercontent.com/5398426/54086690-20221680-438f-11e9-951d-66093dc56a9a.png)

**Comment by SvenErik1968** [comment]
@globalnomad, that is not a .srt file, it is in Advanced Substation Alpha format. Close the file, change the file ending from .srt to .ass and then open it in SubtitleEdit again.

**Comment by globalnomad** [comment]
@SvenErik1968 Thanks for the tip on what file type it actually is. Unfortunately, upon renaming the extension and opening with Subtitle Edit, it still is deactivated like above. However, like I mentioned in my previous post, I worked around it by first saving it as an SRT, then using the SRT to create my SUP. Feel free to close the issue if it is intended for Advanced Substation Alpha subs with formatting to ignore Subtitle Edit's own formatting capabilities.

**Comment by niksedk** [comment]
Yes, for ASS/SSA formats many options are locked as styling is per-defined in the subtitle file.

SE detects subtitle format by content - not by file type.

**Comment by binba2** [comment]
I think the clarification missing here is: .ASS file supports the most subtitling features, especially in regards to formatting and styles.
When working with .ASS files in Subtitle Edit, it will utilize those settings as much as possible to generate .SUPs. That's why those settings are grayed out. You should modify them in the "Advanced Sub Station Alpha Styles" window.
