### ISSUE TITLE
Some video files are upside down after updating to the last version

### ISSUE THREAD

**Issue by Ormendahl** [SubtitleEdit/subtitleedit#3449]
https://i.imgur.com/hpozxmd.png How do i fix this?

**Comment by niksedk** [comment]
Try installing latest version of LAV filters: https://github.com/Nevcairiel/LAVFilters/releases (use installer version)

If that does not help, then switch to mpv player (Options -> Settings -> Video player)

**Comment by Ormendahl** [comment]
> If that does not help, then switch to mpv player (Options -> Settings -> Video player)


Didn't work. When i switch to mpv and open a video file it doesn't play on the player

**Comment by niksedk** [comment]
Still no luck?
You could also try VLC...

SE don't really have much to do with codecs - it's the underlying video player + installed software/hardware on the computer... so I guess it's something with your computer, sorry.
You could try to re-install DirectX + your video drivers - or windows in worst case.

**Comment by OmrSi** [comment]
@niksedk Closed? No response.
