### ISSUE TITLE
[Bug] Extend the current line to next subtitle or max time isn't affecting original

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3453]
The latest beta, translator's mode.
Using `Extend the current line to next subtitle or max time` isn't affecting the original subtitle.

**Comment by niksedk** [comment]
Fixed in 9484ffbca1dfbd1e8ae9d7973e5a82df7b6545f7

**Comment by OmrSi** [comment]
@niksedk Beta updated?

**Comment by niksedk** [comment]
Included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Great, thanks.
