### ISSUE TITLE
[Bug] Splitting at cursor/video position doesn't remove dialog dashes

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3454]
Hey, if you use `Split at cursor position` or `Split at cursor/video position` with translator's mode, dialog is only removed in the other text box.
For example, if you do it at the original's text box, it's only removed from the main text box:
![Screenshot (260)](https://user-images.githubusercontent.com/20923700/54231105-85e9dc00-4510-11e9-98a2-ccb756b21eca.png)

And if you do it at the main, it's only removed from the original:
![Screenshot (261)](https://user-images.githubusercontent.com/20923700/54231170-ab76e580-4510-11e9-9747-2896de35b2e7.png)

Whereas waveform's split removes it from both:
![Screenshot (263)](https://user-images.githubusercontent.com/20923700/54231289-f133ae00-4510-11e9-847c-ce0bb801d523.png)

**Comment by OmrSi** [comment]
@niksedk Somewhat related: When splitting a line like this:
```
- What?
- I just think you should consider
```
Dialog isn't removed, while the first line is finished.

**Comment by niksedk** [comment]
Should also be fixed via #3464
