### ISSUE TITLE
[Improvement] Replace/Multiple replace should remove empty lines

### ISSUE THREAD

**Issue by Kronopt** [SubtitleEdit/subtitleedit#3455]
If a replace/multiple replace action causes a line to become empty, that line should be removed automatically.

**Comment by OmrSi** [comment]
Which it does.

**Comment by niksedk** [comment]
@Kronopt: Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip ?

If it still fails, could you provide sub + replace expression?

**Comment by Kronopt** [comment]
The following screenshot is of me testing the 3.5.9 beta you provided.
All lines had an 'a'.
Replacing 'a' with nothing doesn't remove the empty line

![Screenshot 2019-03-12 22 20 03](https://user-images.githubusercontent.com/19473287/54240207-52f61700-4515-11e9-997b-14bfe8165ac4.png)

**Comment by OmrSi** [comment]
Yeah. Only Multiple replace does that.

**Comment by Kronopt** [comment]
> Which it does.
> Yeah. Only Multiple replace does that.

Yeah, it doesn't.
I tested with both `replace` and `multiple replace` and neither of them remove the empty lines.

**Comment by OmrSi** [comment]
![Uploading Screenshot (264).png…]()
![Screenshot (265)](https://user-images.githubusercontent.com/20923700/54245036-e4768080-4537-11e9-8ace-582a39fc3c9a.png)

**Comment by Kronopt** [comment]
Can you please provide the steps you're taking?
I can't reproduce your result.

For `replace`, this is what I do:
- Open `SubtitleEditBeta`
- Open subtitle file (in this case, 4 lines with 'a' as text, ignoring the time).
- `edit `> `replace`
- `Find what:` = a
- `Replace with:` = 
- Hit `replace` multiple times or `replace all`

**Result**: empty lines are not removed.

For `multiple replace` this is what I do:
- Open `SubtitleEditBeta`
- Open subtitle file (in this case, 4 lines with 'a' as text, ignoring the time).
- `edit `> `multiple replace`
- `Find what:` = a
- `Replace with:` = 
- Hit `add`
- Hit `apply`
- Hit `OK`

**Result**: empty lines are not removed.

**Comment by OmrSi** [comment]
I see, it seems that clicking `Apply -> OK` doesn't delete empty lines, but clicking just `OK` does.

**Comment by niksedk** [comment]
thx guys :)

Normal "Replace" should not remove empty lines IMO.

**Comment by OmrSi** [comment]
I agree.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
(Multiple replace "apply" should now also remove lines)

**Comment by Kronopt** [comment]
`multiple replace` removes empty lines in new beta 👍
