### ISSUE TITLE
Command-line execution

### ISSUE THREAD

**Issue by arianaa30** [SubtitleEdit/subtitleedit#3456]
The app has a nice GUI interface. Wondering how/if I can simply do a conversion from a given .scc file to an outpout text file (say JSON 11 as specified in the save as list) using command line?

**Comment by OmrSi** [comment]
This is everything about command line, I think.
https://www.nikse.dk/SubtitleEdit/Help#commandline

```
optional-parameters:
        /offset:hh:mm:ss:ms
        /fps:<frame rate>
        /targetfps:<frame rate>
        /encoding:<encoding name>
        /pac-codepage:<code page>
        /resolution:<width,height>
        /inputfolder:<folder name>
        /outputfolder:<folder name>
        /overwrite
        /multiplereplace:<comma separated file name list> ('.' represents the default replace rules)
        /multiplereplace (equivalent to /multiplereplace:.)
        /removetextforhi
        /fixcommonerrors
        /redocasing
        /forcedonly
```

**Comment by arianaa30** [comment]
Thanks. What's the license of this open-source project? Can I use it in my future startup?

**Comment by niksedk** [comment]
Yep, you can use it in your future startup :)
If you modify the source code, you need to share those changes.
https://github.com/SubtitleEdit/subtitleedit/blob/master/LICENSE.txt
