### ISSUE TITLE
Issues in parsing .scc files

### ISSUE THREAD

**Issue by arianaa30** [SubtitleEdit/subtitleedit#3457]
I was trying the tool for this .scc file, but what I get is messy. Multiple valid lines are put together as a single line. Is there a bug in the tool?!

Here is a sample .scc file.
[sample.zip](https://github.com/SubtitleEdit/subtitleedit/files/2959066/sample.zip)

The created `.srt` file appears like this:

```
1
00:00:00,000 --> 00:00:00,375
,

2
00:00:00,375 --> 00:00:05,792
(Nora)
What''s my tax prep going to
cost? (Tax Guy)
I can''t really say until the
end. (Lisa) [off-screen]
Wait, no. H&R Block has upfront,
transparent pricing so you know the price
before you begin.

3
00:00:05,792 --> 00:00:06,999
(Nora)
So, it can work like that.

4
00:00:06,999 --> 00:00:08,375
(Tax Guy)
I could give you a
ballpark...Ummm, hmmmm.

5
00:00:08,375 --> 00:00:10,918
(Lisa VO) ♪
Know the price before you begin.

6
00:00:10,918 --> 00:00:11,999
With new upfront
transparent pricing.

7
00:00:11,999 --> 00:00:13,834
Block has your back.



```

**Comment by OmrSi** [comment]
Did you create the file with SE?
I did some testing, I converted the file to .srt using a website, it gave the exact same result as SE.
I then created a .srt file with SE and converted that file to .scc using SE, then opened the file, and it was the same, didn't have any issues.
Then I converted the .scc I created with SE on the website to .srt and opened the file with SE, nothing changed.

So I opened your file with a text editor and saw that it only has 7 lines, which is what SE and the website showed.
So, it seems that the file is created this way, it's not an issue from SE as it opens and converts .scc files just fine.

The main idea is that your file only has 7 lines to begin with, so it's not SE's fault, I think.

**Comment by arianaa30** [comment]
I see. When I watch the movie with the original `.scc` file, it looks not stacked up. Something similar to the following parsed captions (this is from `pyCaption` library):

```
{
  "result": [
    {
      "startTime": 333,
      "endTime": 1266,
      "capText": "(Nora)\\nWhat'’s my tax prep going to\\ncost?",
      "mode": "POP"
    },
    {
      "startTime": 2300,
      "endTime": 3033,
      "capText": "(Tax Guy)\\nI can'’t really say until the\\nend.",
      "mode": "POP"
    },
    {
      "startTime": 3066,
      "endTime": 4000,
      "capText": "(Lisa) [off-screen]\\nWait, no.",
      "mode": "POP"
    },
    {
      "startTime": 4033,
      "endTime": 5700,
      "capText": "H&R Block has upfront,\\ntransparent pricing",
      "mode": "POP"
    },
    {
      "startTime": 5733,
      "endTime": 7000,
      "capText": "so you know the price\\nbefore you begin.",
      "mode": "POP"
    },
    {
      "startTime": 7033,
      "endTime": 8366,
      "capText": "(Nora)\\nSo, it can work like that.",
      "mode": "POP"
    },
    {
      "startTime": 8400,
      "endTime": 10800,
      "capText": "(Tax Guy)\\nI could give you a\\nballpark...Ummm, hmmmm.",
      "mode": "POP"
    },
    {
      "startTime": 10833,
      "endTime": 12000,
      "capText": "(Lisa VO) ♪\\nKnow the price before you begin.",
      "mode": "POP"
    },
    {
      "startTime": 12033,
      "endTime": 13733,
      "capText": "With new upfront\\ntransparent pricing.",
      "mode": "POP"
    },
    {
      "startTime": 13766,
      "endTime": 14900,
      "capText": "Block has your back.",
      "mode": "POP"
    }
  ],
  "startIndex": 0,
  "itemsPerPage": 10,
  "totalResults": 10,
  "filtered": false
}
```
I don't know why SE stacks up multiple lines as a single caption.
