### ISSUE TITLE
[REQUEST] When using VLC as video player, use the preferences already set in VLC

### ISSUE THREAD

**Issue by msgjobs** [SubtitleEdit/subtitleedit#3463]
I have trouble hearing the dialogue while creating subs.  I can setup VLC with equalizer settings so I can hear clearly and I save the settings in my preferences, but when I run vlc in SE it does not use any preference settings. 

So as it stands I have to watch the movie in VLC on the side while using SE and listen to the dialogue then switch back to SE to type it in.

So please adjust the call to VLC to use any preexisting settings, or allow the use of the VLC equalizer in SE.

Thanks

**Comment by niksedk** [comment]
Sorry, I don't think that's possible without a huge amount of work...

You could try enabling "Allow audio boost" (on some computers it helps, on other computers it's give bad audio):
![image](https://user-images.githubusercontent.com/1261331/54381078-295ffb80-468d-11e9-86d7-d3bc1dca1dc8.png)

**Comment by msgjobs** [comment]
I came up with a workaround.  I realized it's possible to open an audio file in SE instead of the whole movie, so I stripped out the audio from the movie and enhanced it so I could hear it clearly and then opened it in SE.  A little more work but gets the job done.. Thanks
