### ISSUE TITLE
[Bug] Split doesn't remove dialog dashes from original

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3464]
When splitting a line like this:
```
- What?
- I just think you should consider
```
Dialog dashes aren't removed from the original, while the first line is finished:
![Screenshot (273)](https://user-images.githubusercontent.com/20923700/54387882-28d35f00-46a5-11e9-96d3-8e32e1115d6b.png)

![Screenshot (274)](https://user-images.githubusercontent.com/20923700/54387889-2bce4f80-46a5-11e9-8293-573d50025a66.png)

**Comment by OmrSi** [comment]
Plus, toggling dialog in the original or the main text box only affects the main.

**Comment by Ding-adong** [comment]
You meant the - ? Always been like that, just use FCE and remove dash.

**Comment by OmrSi** [comment]
@Ding-adong Yeah, it removes them in other cases, just not in this case.

**Comment by Ding-adong** [comment]
Really, weird... well i never use 2 columns, 1 is enough for me.

**Comment by OmrSi** [comment]
@Ding-adong This is the "Translator's mode", we use it when we translate.
You have the English file on the right, and you add your translation to the left.
So you don't have to delete and try to remember what you deleted...

**Comment by OmrSi** [comment]
@niksedk This is not fixed.
Look:
![Screenshot (299)](https://user-images.githubusercontent.com/20923700/54497246-faea5680-4900-11e9-8efd-ec5fd4d7b1c0.png)

![Screenshot (300)](https://user-images.githubusercontent.com/20923700/54497248-0047a100-4901-11e9-91cd-6d2452088774.png)

This is Waveform's split.

**Comment by OmrSi** [comment]
@niksedk This is not fixed.
Look:
![Screenshot (299)](https://user-images.githubusercontent.com/20923700/54497246-faea5680-4900-11e9-8efd-ec5fd4d7b1c0.png)

![Screenshot (300)](https://user-images.githubusercontent.com/20923700/54497248-0047a100-4901-11e9-91cd-6d2452088774.png)

This is Waveform's split shortcut.
I'm sorry I wasn't clear about that before.

**Comment by OmrSi** [comment]
Let me know when the Beta's up, not rushing it. Thanks a lot. <3

**Comment by niksedk** [comment]
Beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
I can't thank you enough, man.
