### ISSUE TITLE
[Bug] Do-not-break-after list not working inside the text box

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3465]
I feel like I'm spamming with all these issues in the last couple of days. Sorry.
Anyways, here it goes, try breaking this from inside the text box:
`How are you doing today Mr. whatever Mr. whatever.`

it becomes:
```
How are you doing today Mr.
whatever Mr. whatever.
```

But from the list or the button, it becomes:
```
How are you doing today
Mr. whatever Mr. whatever.
```

Add to this that using the break shortcut from the list when in the translator's mode doesn't work.

**Comment by OmrSi** [comment]
@niksedk Is this done?

**Comment by niksedk** [comment]
Seems to work fine here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

Also, due to a broken water-pipe I only has a small laptop for the next few months...

**Comment by OmrSi** [comment]
Yeah, I think it works fine now.
Break shortcut is still not working from the list in the translator's mode, but that's ok I think.
Also, I was trying to break this:
`لكن اسمعي، أحتاج إلى مساعدتك على فك تشفير بعض الإحداثيات ليس إلا.`

And it was broken to:
```
لكن اسمعي،
أحتاج إلى مساعدتك على فك تشفير بعض الإحداثيات ليس إلا.
```
With 54 chars in the second line, though I have it set on 42 max.
I don't know what's wrong.

> Also, due to a broken water pipe, I only have a small laptop for the next few months...

Oh, god help you. Let's hope not many issues are opened until then.
And thank you very much, as always.

**Comment by OmrSi** [comment]
@niksedk If there is an Arabic comma `،`, it seems to always break at its position, not caring about the length of the second line after the break.

**Comment by OmrSi** [comment]
If this isn't an easy fix, I can close this and open a separate issue for it later.

**Comment by OmrSi** [comment]
Yeah, I think it works fine now.
Break shortcut is still not working from the list in the translator's mode, but that's ok I think as you need to specify the text box you're breaking.

> Also, due to a broken water pipe, I only have a small laptop for the next few months...

Oh, god help you. Let's hope not many issues are opened until then.
And thank you very much, as always.

**Comment by darnn** [comment]
@niksedk Oh no! Do you need money for a computer? I'd be happy to toss a couple of buck your way, you've been nothing short of amazing with everything you've done on SE, I can't imagine what I'd do without it.

**Comment by OmrSi** [comment]
@darnn I've been trying to find a way to do that from here for a while now, sadly we don't have any paying services here. :(

Also, Small in memory or size?

**Comment by niksedk** [comment]
I still have my computer - it's just packed away as I don't have a floor atm :(

**Comment by niksedk** [comment]
The laptop has small screen + is pretty slow (and no ssd drive)

**Comment by OmrSi** [comment]
Yeah, that's tough for editing and building each time.
I wish I could help in anyway...
