### ISSUE TITLE
Error box on Bionic

### ISSUE THREAD

**Issue by jimbolaya** [SubtitleEdit/subtitleedit#3468]
I am running SubtitleEdit on Ubuntu Bionic. I am getting error dialog boxes doing certain actions.

In order to get SubtitleEdit running, I had to install "libmono-system-windows-forms4.0-cil". I used to run SubtitleEdit on Trusty, which required "libmono-winforms2.0-cil", but that package isn't available on bionic.

After I dismiss the error dialogs, SubtitleEdit seems to run fine and no further error dialogs show up until I run SubtitleEdit again.

The first error box "subtitleedit fix common errors.png" I get when I go to Tools|Fix Common Errors or to either of the menu options under Networking.

The second error box "subtitleedit close button error.png" I get when I close SubtitleEdit from the window close button, commonly in the upper right of the window.

![subtitleedit fix common errors](https://user-images.githubusercontent.com/3241087/54476438-cd53bf00-47d3-11e9-9874-a892e401b78d.png)
![subtitleedit close button error](https://user-images.githubusercontent.com/3241087/54476439-d17fdc80-47d3-11e9-9576-c0106f2e586c.png)

**Comment by niksedk** [comment]
Linux info here: https://www.nikse.dk/SubtitleEdit/Help#linux
