### ISSUE TITLE
Implementing free Yandex Translate API?

### ISSUE THREAD

**Issue by ninep9up** [SubtitleEdit/subtitleedit#3469]
https://tech.yandex.com/translate/doc/dg/concepts/About-docpage/
Free API key is 1,000,000 characters per day but not more than 10,000,000 a month.

**Comment by OmrSi** [comment]
Already available in the plugins section...

**Comment by ninep9up** [comment]
Thanks, didn't even know they existed, wouldn't have found it otherwise.

**Comment by OmrSi** [comment]
You got it!
You can find other helpful tools there, too.
