### ISSUE TITLE
[3.5.9] Windows 1809 x64 no video with lav codecs

### ISSUE THREAD

**Issue by Cryosim** [SubtitleEdit/subtitleedit#3470]
Hi! I use video MKV mpeg2, black skreen. sound was ok.
![2019-03-16](https://user-images.githubusercontent.com/35970462/54479697-abd4f080-4830-11e9-82d7-4fb9eeb4af6e.png)

**Comment by OmrSi** [comment]
Have you tried using MPV as your video player?

**Comment by Cryosim** [comment]
> Have you tried using MPV as your video player?
I try vlc 3.0.6. app crash, then i going into Visual sync.

**Comment by OmrSi** [comment]
Try MPV, it's the best with SE, IMO.
![Screenshot (278)](https://user-images.githubusercontent.com/20923700/54479878-73321880-482a-11e9-959d-8c9978d49bbe.png)

**Comment by Cryosim** [comment]
> Try MPV, it's the best with SE, IMO.
> ![Screenshot (278)](https://user-images.githubusercontent.com/20923700/54479878-73321880-482a-11e9-959d-8c9978d49bbe.png)


Why I can use many players for different apps? its not really good.

**Comment by OmrSi** [comment]
It is good. Depending on what program you have. I guess he doesn't want to force MPV on anyone.
Anyway, just try MPV.

**Comment by Cryosim** [comment]
> It is good. Depending on what program you have. I guess he doesn't want to force MPV on anyone.
> Anyway, just try MPV.

With MPV app hangs. then i sync subs. Windows license. 1809 x64.

**Comment by OmrSi** [comment]
Sounds strange. I'm also running 1809 x64 and have LAV installed.

**Comment by marb99** [comment]
I use VLC and until now I don't having any issues.

**Comment by Cryosim** [comment]
Then i use portable vlc 3.0.6.
The name of the failed application is SubtitleEdit.exe, version: 3.5.9.0, time stamp: 0x5c603341
The name of the failed module is dxgi.dll, version: 10.0.17763.1, timestamp: 0x6b3e2414
Exception code: 0xc000001d
Error offset: 0x0000000000001d73
Failed process ID: 0x2e4c
Failed application start time: 0x01d4dca14e9c8a0d
Failed application path: E:\Subtitle Edit\SubtitleEdit.exe
Path faulting module: C:\Windows\system32\dxgi.dll
Report ID: 02ad9e4d-0071-4554-bb7d-5b07d40b2d9f
The full name of the failing package: 
Application code associated with the failed package:

**Comment by niksedk** [comment]
@Cryosim: SE don't really have much to do with codecs - it's the underlying video player + installed software/hardware on the computer... so I guess it's something with your computer, sorry.
You could try to re-install DirectX, your video drivers - or windows in worst case.

**Comment by Cryosim** [comment]
> @Cryosim: SE don't really have much to do with codecs - it's the underlying video player + installed software/hardware on the computer... so I guess it's something with your computer, sorry.
> You could try to re-install DirectX + your video drivers - or windows in worst case.

Video Geforce GTX 970, last drivers.

**Comment by niksedk** [comment]
Did you ever get this working?
I saw that latest LAV filters (0.74.1) fixed a bug with no video: https://github.com/Nevcairiel/LAVFilters/releases
