### ISSUE TITLE
Build errors LibSE

### ISSUE THREAD

**Issue by ergodaveh** [SubtitleEdit/subtitleedit#3473]
I have recently downloaded the latest source and using VS 2015 Pro Update 3 attempted to compile the project for the first time.

The LibSE project fails to build with several errors:

for example:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1003	Syntax error, ',' expected	LibSE	C:\ClosedCaption\subtitleedit-master\libse\SubtitleFormats\AdvancedSubStationAlpha.cs	554	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'unknownTags' does not exist in the current context	LibSE	C:\ClosedCaption\subtitleedit-master\libse\SubtitleFormats\AdvancedSubStationAlpha.cs	873	Active

Any suggestions?
-D

**Comment by ivandrofly** [comment]
Did you try to build Libse separately?

**Comment by ergodaveh** [comment]
Originally along with the solution and then separately.

**Comment by niksedk** [comment]
Sorry, you need VS 2017 or VS 2019.
