### ISSUE TITLE
[Bug] "Translate" shortcuts don't work on another mode

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3485]
Even after making the modes global, using one of "Translate" shortcuts when in another mode doesn't work until you go to "Translate" and get back and even then highlighting new sections doesn't work.
So it's basically only working in "Translate" mode.

**Comment by OmrSi** [comment]
@niksedk Aside from the bug in the first line, I'm basically suggesting to add two sites to the list of websites:
1. Google.com: https://www.google.com/search?q={0}
2. custom: the user would add the link.

**Comment by niksedk** [comment]
The "search" shortcuts?

**Comment by OmrSi** [comment]
Yeah, But I see that when you highlight a section of the text, it moves to the search box and then the search shortcuts work on the text in that box.
When you're in another mode, the highlighted text can't move to the search box.
So if this is complicated, you can just close it. :D

**Comment by niksedk** [comment]
Gave it a try, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Perfect. :D
Thank you, as always.
Closed with the commit.

**Comment by OmrSi** [comment]
Wow, shortcuts too!

**Comment by niksedk** [comment]
thx for finding and testing this bug :)

**Comment by OmrSi** [comment]
@niksedk Why am I unable to use "Control+Alt+ G" as a shortcut for "Google it!"?
When I use "Control+Alt+ G", the shortcut only works from the list.
