### ISSUE TITLE
Error after changing keyboard shortcut

### ISSUE THREAD

**Issue by green-pigeon** [SubtitleEdit/subtitleedit#3486]
Hi,
I was using old version of Subtitle Edit and was used to Go to next subtitle (from video position) using Shift+Return. I updated to the last version and Shift+Return was used for Go to next line. So I went to Settings and changed the shortcut for Go to next line to be Shift+Down and the shortcut for Go to next subtitle (from video position) to be Shift+Return as I was used to. Now every time I press Shift+Return, I get the error message below.

![err](https://user-images.githubusercontent.com/7714689/54863854-8e36e800-4d56-11e9-9378-a3833e4637c7.png)

**Comment by niksedk** [comment]
Are you using the waveform?

**Comment by niksedk** [comment]
@green-pigeon: thx for the info - I think I found the bug. Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/3436
Maybe related.

**Comment by green-pigeon** [comment]
@niksedk I tried the Beta and it is working. Thanks.

**Comment by niksedk** [comment]
@green-pigeon: thx for verifying :)
