### ISSUE TITLE
Issue with "Remove text before a colon"

### ISSUE THREAD

**Issue by teodargent** [SubtitleEdit/subtitleedit#3491]
"Remove text before a colon" didn't catch the sub in the image below:

![image](https://user-images.githubusercontent.com/20757457/54918302-30dd9b00-4efe-11e9-94e2-bbf8c7a2588f.png)

It did work if I added a line break:

![image](https://user-images.githubusercontent.com/20757457/54918342-45ba2e80-4efe-11e9-855f-ea07507f0a5f.png)

**Comment by Ding-adong** [comment]
That's because you have lowercase text before BILLY and you checked "only if text is uppercase".

**Comment by teodargent** [comment]
Ok but that's a different phrase, also BILLY is preceded by "-"
