### ISSUE TITLE
[Bug] Using save after "Import with manual chosen encoding" opens save as

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3502]
When saving a subtitle after using "Import subtitle with manual chosen encoding", it opens the "save as..." window

Also, I think it should be "`manually` chosen encoding".

**Comment by OmrSi** [comment]
Thank you. ♥
Would you up the beta, please?

**Comment by OmrSi** [comment]
Thank you. <3
Could you update the beta, please?

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
