### ISSUE TITLE
[3.5.9] Audio track

### ISSUE THREAD

**Issue by Cryosim** [SubtitleEdit/subtitleedit#3505]
Hi!
When i add waveform
Can't select audio track, by default alvays first audio track selected.

**Comment by niksedk** [comment]
If some can make vlc work I could improve this... but this needs to be fixed first: https://trac.videolan.org/vlc/ticket/21592

**Comment by Cryosim** [comment]
> If some can make vlc work I could improve this... but this needs to be fixed first: https://trac.videolan.org/vlc/ticket/21592
I hope you migrate to ffmpeg, it solve problems with codecs and tracks.

**Comment by Cryosim** [comment]
I hope you migrate to ffmpeg, it solve problems with codecs and tracks.

**Comment by OmrSi** [comment]
@Cryosim You can use FFmpeg, which I do, so I don't have this problem.
Just go to the Waveform section in the Settings and "Download FFmpeg" and use it.

**Comment by niksedk** [comment]
Fixed in SE 3.5.12 :
SE does still not support different waveforms for different tracks...

**Comment by nimma-vk** [comment]
@niksedk, any progress on this?  I use waveform extensively.  It becomes difficult to work with audio tracks which are not default.

**Comment by OmrSi** [comment]
@nimma-vk It's already implemented. 
SE now suppprts different waves for different tracks.

**Comment by nimma-vk** [comment]
Thanks for confirming @OmrSi
