### ISSUE TITLE
[Feature request] Ignore apostrophe (') used instead of ...(n)g

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#3506]
When using OCR, SE picks up some correct spells like "lookin'", "takin'", "talkin'" and "savin'"as wrong ones.
Every time they comes up, I register them in my user dictionary.
But I feel it quite tiresome now, when new words come up in every new subtitle.
For the 5th option in OCR, can I have ignore "(verb)n'" spelling used in place of "(verb)ng"?

**Comment by Ding-adong** [comment]
regex in multiple replace.
`(?i)(?: [^'])?(?<!\S)(\w+)in'\B` replace with  `$1ing`

**Comment by taxen** [comment]
That changes the original. I would like to keep it as it is.

**Comment by Ding-adong** [comment]
`On top of that, it can be only done when text is available (after OCR is done).`

Put in it the ocrreplacelist in regular expressions section. There is no way to have ignore "(verb)n'" as the dictionary isn't designed to separate verb, noun, adjective, etc. Just convert al words to ing as that's the correct spelling.

**Comment by taxen** [comment]
I put <RegEx find="(?i)(?: [^'])?(?<!\S)(\w+)in'\B" replaceWith="$1ing***" /> line into eng_OCRFixReplaceList_User.xml in user dict directory. Then run SE and all the data in the file has been gone. Maybe my xml grammar/tag was wrong. "***" is just to mark and see if the replacement is working or not.
Then I copied all the data from eng_OCRFixReplaceList.xml under program directory and pasted to the above file, adding just one same line. The result is the same. All the data except newly registered ones has been gone in eng_OCRFixReplaceList_User.xml. So maybe my tagging is not the problem.
Anyway, even putting the line into eng_OCRFixReplaceList.xml under program directory directly does not change a target, which is "waitin'". SE only shows "waiting" as one of alternatives and "waiting***" is not there, which I expected.
Could you point out the exact file name and location to modify for English language?

**Comment by Ding-adong** [comment]
I am not sure regex is allowed in eng_OCRFixReplaceList_User.xml as there isn't any to begin with. Put it in eng_OCRFixReplaceList.xml. `<` must be replace by `&lt;` in xml file.
Use fix common error to make the changes not spell checker.

**Comment by OmrSi** [comment]
@niksedk Shouldn't this work?
![image](https://user-images.githubusercontent.com/20923700/79577594-9c784480-80cd-11ea-99b0-37be3acf6de9.png)
