### ISSUE TITLE
[Bug] All dialog splitting issues are back in the latest beta

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3507]
Everything you worked on for split is back again in the latest beta, I think it started after this commit: https://github.com/SubtitleEdit/subtitleedit/commit/d98d65ebbac39f78af01be121e867f500cfacef8

**Comment by niksedk** [comment]
Works fine for me... could you provide some examples that fail? What do you do exactly?

**Comment by OmrSi** [comment]
Strange, I just downloaded the beta and tested with a clean settings file using these: [test.zip](https://github.com/SubtitleEdit/subtitleedit/files/3026708/test.zip)
In the translator's mode, of course.
Look:
Waveform's split:
![Screenshot (314)](https://user-images.githubusercontent.com/20923700/55290517-db612c80-53dc-11e9-96a4-b1db3343af3e.png)
Split at cursor/video position from the original or the normal text box or just at cursor position:
![Screenshot (315)](https://user-images.githubusercontent.com/20923700/55290534-0b103480-53dd-11e9-836b-3c3ec1ed294e.png)

I guess it's not affecting the original anymore...

**Comment by niksedk** [comment]
thx - nice catch. Was surely a small fix: https://github.com/SubtitleEdit/subtitleedit/commit/1d67eab892d7b97276b0a3a0be331ee6aad78418

beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Cool. Thank you, as always. 😄
