### ISSUE TITLE
[Feature request] Remove lines containing certain character/string of characters

### ISSUE THREAD

**Issue by Kronopt** [SubtitleEdit/subtitleedit#3508]
What do you think about removing whole lines if they contain a certain character or string of characters?

Ex:
* Removing lines containing "♪" (sometimes, in my opinion, they don't make much sense when applied to background music lyrics)

**Comment by darnn** [comment]
The option to remove everything between a set of two characters (like ♪) already exists in "remove text for hearing impaired". Though I suppose it would be nice to add a "remove subtitle" option in the search and replace dialogue.

**Comment by OmrSi** [comment]
The is a kind of "remove subtitle" option, as in Multiple replace, when you replace something in a line and that line becomes empty after the replace, SE removes it.
Based on that idea, do this:
![Screenshot (311)](https://user-images.githubusercontent.com/20923700/55287990-6f210180-53b9-11e9-94af-ede26c6d5dd8.png)
Replace the START with any word you want: `\ASTART[\S\s]+` and it will remove the lines starting with that word.

**Comment by Kronopt** [comment]
Thanks for the regex @OmrSi, that will be useful!

But if more people find this feature useful, I think a dedicated option (maybe in the search and replace dialog, like @darnn mentioned) would be much appreciated, as not everyone knows how to use regex.

**Comment by OmrSi** [comment]
@Kronopt On second thoughts, there is already something related to this.
Modify Selections allows you to select lines containing or starting with something, it has many other features.
You could select all lines with it and delete them.

**Comment by Kronopt** [comment]
Cool!
That's another way to do it.
Thanks!

I think this can be closed as no new feature is necessary.
