### ISSUE TITLE
How to automatically create sections of speech activity?

### ISSUE THREAD

**Issue by vanderbuildt** [SubtitleEdit/subtitleedit#3509]
Is there a way we can automatically create sections of speech activity (for ex. 1s -> 3s, 5s -> 10s) based on waveform. Later on we can add text to these empty sections.

**Comment by OmrSi** [comment]
Something like this?
![Screenshot (312)](https://user-images.githubusercontent.com/20923700/55288020-f1a9c100-53b9-11e9-9de7-18a2ac03c633.png)
![Screenshot (313)](https://user-images.githubusercontent.com/20923700/55288048-87455080-53ba-11e9-890c-424077d5bcf6.png)

**Comment by vanderbuildt** [comment]
Thanks, yes, that's it. I was not able to google search keyword to do this.
