### ISSUE TITLE
Comodo Antivirus detects SE installers as malware

### ISSUE THREAD

**Issue by CinderBH** [SubtitleEdit/subtitleedit#3510]
I have the ZIPs for both version 3.5.6 and 3.5.9 and they both get the following result:

ApplicUnwnt.Win32.Adware.Adposhel.BL@489246964

If it helps at all, I have a HxD installer file and it gets flagged the same way.

**Comment by niksedk** [comment]
I've just tested with VirusTotal and it looks fine.
Installer. https://www.virustotal.com/#/file/21fa6abe71cdf0e5a57f76d0e729bbef74cd3adb1f65b74200cef898fd50af30/detection
Portable: https://www.virustotal.com/#/file/9eeca6bba1084f84a9cefcda4109ff7865f5699d7f501a1c6beb5df84bd0df05/detection

Be sure you have latest version of Comodo + that you have downloaded the files from Github.

**Comment by CinderBH** [comment]
I have done both things in the first place, but a direct scan still yelds the same result.

**Comment by niksedk** [comment]
SE distributions use ILRepack ( https://github.com/SubtitleEdit/subtitleedit/blob/master/src/packages.config ) that embeds .net dll files into SubtitleEdit.exe to have fewer files in the final builds which is nice - and that has probably sometimes triggered AV programs.

**Comment by niksedk** [comment]
You can try to submit the file as a false positive to comodo: https://www.comodo.com/home/internet-security/submit.php

**Comment by CinderBH** [comment]
I did do so. And MBAM on the other hand doesn't detect anything. Hopefully the database will be updated accordingly soon.

**Comment by OmrSi** [comment]
@niksedk @xylographe Nothing to do here, Closed?

**Comment by xylographe** [comment]
OK, let's be optimistic and assume the database has been updated by now. :)

Pretty sure though that the problem will return with the next release,
[quote on] Only Comodo Antivirus for Windows utilizes a default-deny policy to automatically block all unknown files into auto-containment where its behavior is observed till a verdict is reached. [quote off]

Closing the issue for the time being, feel free to re-open if needed.
