### ISSUE TITLE
youtube & facebook not working

### ISSUE THREAD

**Issue by DemonRem** [SubtitleEdit/subtitleedit#3513]
i made my subtitle for my video but I see the subtitle with VLC , but on windows media player facebook and youtube I don't why is it?

**Comment by OmrSi** [comment]
Did you add any effects like position or color tags? Also, did you save it as .srt?

**Comment by DemonRem** [comment]
I did and I saved it as .ass

**Comment by OmrSi** [comment]
To my knowledge, Facebook/Youtube don't support .ass or effects for that matter.

**Comment by DemonRem** [comment]
Well you don’t believe what was wrong when I add the subtitles using converter I did use the wrong output video it’s isnt software issue it’s was mine therefore this issue closed may also be delete
