### ISSUE TITLE
How to make sure that the highlighted section in waveform is at the middle of waveform screen?

### ISSUE THREAD

**Issue by learner007** [SubtitleEdit/subtitleedit#3514]
Many a times, half of the selected waveform is visible while other half becomes visible after that section is played and cursor goes off the visible part.

Is there a way so that selection line's waveform will be at the centre of waveform section (and not at the end)?

**Comment by learner007** [comment]
I think I got it. Need to double tap/click on the line in "List View".

**Comment by learner007** [comment]
It seems that double clicking shift the selected portion near left end of waveform view. There is another button I need to click to bring it at center.

Can both this actions be done at one go? (select portion + bring to centre)

**Comment by OmrSi** [comment]
Have you tried using the "Center" option?

**Comment by OmrSi** [comment]
Related, I think. https://github.com/SubtitleEdit/subtitleedit/issues/3378
