### ISSUE TITLE
Bug - simple words not recognized

### ISSUE THREAD

**Issue by NikitaT** [SubtitleEdit/subtitleedit#3519]
What might cause issue like this? Simple words like "do", "so", "we", "to" and so on, are not recognized. Dictionaries are set to EN.
![simple](https://user-images.githubusercontent.com/1424279/55550381-5de93500-56d8-11e9-9d39-70bc92913c6e.png)

**Comment by niksedk** [comment]
Perhaps it's not really an "o"... could you attache or email the sub?

**Comment by NikitaT** [comment]
I tried to remove this text and just type "do" - same result. So it's not some similar looking UTF-symbol.
What is more interesting - I can't reproduce it anymore, PC has not been rebooted, but SubtitleEdit has been turned off for ~24 hours. So if some of readers experience same issue - just take some rest :)

I'm attaching requested file (line 93) - just for completeness of the posted issue, although I can't reproduce this bug so I'm closing the issue.

**Comment by NikitaT** [comment]
Vob file:
[vob.zip](https://github.com/SubtitleEdit/subtitleedit/files/3047779/vob.zip)
