### ISSUE TITLE
Merge continuous lines.

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#3527]
Tool > merge short lines.

It is very time consuming to have to uncheck all line with ...
Not all ... is continuous with the same character.
Can you exclude lines ending with ... from merge continuous lines. It would speed up the merging.

**Comment by taxen** [comment]
I agree. An option "Exclude line with ... (or customized characters)" would be greatly appreciated.
In the meantime, we have a workaround to replace ... with . proceeded by some uncommon word like @@, then merge lines before replace .@@@ with "...".

**Comment by taxen** [comment]
In addition, a block containing a dialog should be excluded, at least as an option. Most of the cases, I do not merge blocks if one of them has a dialog.
