### ISSUE TITLE
Subtitle Edit 3.5.9，c424586.  64-bit

### ISSUE THREAD

**Issue by xivi1839** [SubtitleEdit/subtitleedit#3528]
Subtitle Edit 3.5.9，c424586.  64-bit：

Message: 对 COM 组件的调用返回了错误 HRESULT E_FAIL。
Source: SubtitleEdit

Stack Trace: 
   在 QuartzTypeLib.<841050c4-622c-499d-8776-4d3d20565178>IMediaControl.RenderFile(String strFilename)
   在 Nikse.SubtitleEdit.Logic.VideoPlayers.QuartsPlayer.Initialize(Control ownerControl, String videoFileName, EventHandler onVideoLoaded, EventHandler onVideoEnded)
   在 Nikse.SubtitleEdit.Logic.UiUtil.InitializeVideoPlayerAndContainer(String fileName, VideoInfo videoInfo, VideoPlayerContainer videoPlayerContainer, EventHandler onVideoLoaded, EventHandler onVideoEnded)

**Comment by niksedk** [comment]
Try installing LAV filters installer: https://github.com/Nevcairiel/LAVFilters/releases
Or use mpv as video player
Also read this: https://www.nikse.dk/SubtitleEdit/Help#codecs
