### ISSUE TITLE
Metrics Spec - weird line appears in smi file 

### ISSUE THREAD

**Issue by haagen19** [SubtitleEdit/subtitleedit#3530]
When using it with a smi file, I edited from krcc to encc and saved. It then produced a "Metrics Spec" line on the video at the start for a few seconds. I check the smi file, and the lines aren't there. It turns out if you open the smi file in notepad, there is a 

"<"SAMIParam">"
  Metrics {time:ms;}
  Spec {MSFT:1.0;}
"</"SAMIParam">"

(without the quotes.)
which must be deleted to resolve the issue. I have been manually deleting this, and it seems to be a relatively well known issue. Can this be fixed?
Thank you.

**Comment by niksedk** [comment]
What player do you use?
It's part of the spec I think: https://en.wikipedia.org/wiki/SAMI
