### ISSUE TITLE
[Request] Improve (auto) break/unbreak

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#3531]
always break after comma or after other punctuation if not exceeding line lenght

**Comment by Moerges** [comment]
I would like this as well—at least as an option. :)

**Comment by OmrSi** [comment]
I agree. I've been using `, \w+` in the do-not-break-after list, but that makes it always break at the first comma for some reason, I only want it to not to break after one word after a comma, and I haven't been able to do that... I don't know how regex there works. :\

**Comment by xylographe** [comment]
Did you remember the Regex attribute? (`<Item Regex="true">, \w+</Item>`)

**Comment by OmrSi** [comment]
@xylographe I added it from inside SE...

**Comment by niksedk** [comment]
Will be fixed in SE 3.5.12 - see https://github.com/SubtitleEdit/subtitleedit/issues/3899
