### ISSUE TITLE
Tesseract 4.00 Download Error

### ISSUE THREAD

**Issue by ddelella** [SubtitleEdit/subtitleedit#3532]
When attempting to use Tesseract 4.00 in the IDX/SUB import tool I get the following error:

![image](https://user-images.githubusercontent.com/548747/55834295-937e8b80-5ae7-11e9-903c-e1aada24fdd0.png)

I am using the latest version of Subtitle Edit 3.5.9 on a Windows 10 x64 VM.

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/3172#issuecomment-457005393
