### ISSUE TITLE
No Translation

### ISSUE THREAD

**Issue by pimo11** [SubtitleEdit/subtitleedit#3535]
When will translate the system returns a error in google translate : external server error 403 not allowed 
When translate with Microsoft get the error 401 not authorized
![Knipsel](https://user-images.githubusercontent.com/9959362/55956494-64415900-5c64-11e9-8269-a9b81e359c48.JPG)

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/3438#issuecomment-469980483

**Comment by HansBemelen** [comment]
With new google api key up and running

**Comment by OmrSi** [comment]
@HansBemelen You can't.
It can only be closed with the account which opened it or by the owner.
