### ISSUE TITLE
Translate with Google screen-scraping is not working

### ISSUE THREAD

**Issue by Sopor** [SubtitleEdit/subtitleedit#3536]
It seems that `Google screen-scraping` is broken. The progress bar is slowly moving but without any translation (the lines will also move but without any translations). I have tried to lower the `Bulk max sizes` but it is still not working.

`Bing screen-scraping` is working.

GT Screen-Scraper 0,5
Subtitle Edit 3.5.9 NEXT, beta 226

**Comment by Sopor** [comment]
I tried `Google translate` and it seems to work but it will show this text `Trying to translate wihtout API key... (slow and limited data)`

Btw, i can see a typo here: `without` is spelled wrong.

**Comment by OmrSi** [comment]
It's working fine with me, win 10, 1809.

**Comment by Sopor** [comment]
This is 2 minutes in 5x speed in a loop...

![subtitleedit-google2](https://user-images.githubusercontent.com/5789283/56055692-6ede1a00-5d5a-11e9-86da-c441332df9f4.gif)
