### ISSUE TITLE
Remove formating from srt via command line

### ISSUE THREAD

**Issue by JySzE** [SubtitleEdit/subtitleedit#3537]
Is it possible to remove all formatting via command line? I have massive amounts of srt files with poor sizing and viewing on plex causes it to be a horrible experience. 

I've been opening each individual srt and removing formatting manually and that has been extremely tedious.

**Comment by OmrSi** [comment]
Hmm. Why not use batch convert?!
![Annotation](https://user-images.githubusercontent.com/20923700/56070673-df545d80-5d91-11e9-8ad1-2c95e10ee889.png)

**Comment by OmrSi** [comment]
@niksedk I think this is closed.
