### ISSUE TITLE
Double subtitle in the same scene

### ISSUE THREAD

**Issue by Namkap** [SubtitleEdit/subtitleedit#3538]
Hello,
I'm having an issue with the most recent version of SubtitleEdit.
Yesterday, I started a project and today when I got back to it I get double subtitles in the same scene. This didn't happen in the previous versions.
I've already looked into the program settings, googled it and searched the Github issues, and found nothing. Is this a new issue or a new setting in the program?
Below I copy the screenshot to better illustrate this issue:
![SE_3 5 9](https://user-images.githubusercontent.com/48698927/56081380-a43f4200-5e04-11e9-9a1b-64f999c02c3a.png)
Thank you for your help!

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/3268

**Comment by Namkap** [comment]
Kudos @OmrSi!
Your link to that similar situation it really helped.
I was using the DirectShow video engine like I always did in SE, but reading the thread I decided to go with the installation of the mpv and it solved this double subtitle issue.
Thanks again!

**Comment by OmrSi** [comment]
@Namkap You got it. ^_^
You should close this...
