### ISSUE TITLE
Batch convert hotkey

### ISSUE THREAD

**Issue by 07416** [SubtitleEdit/subtitleedit#3547]
Can you add a hotkey for batch convert? I generally use Subtitle Edit exclusively in this mode to process with all tools at once.

I would also appreciate a shortcut or a launch parameter to start batch convert directly.

**Comment by niksedk** [comment]
`Batch convert` already has a custom shortcut - add something like `Ctrl+B`:
![image](https://user-images.githubusercontent.com/1261331/56268847-a2ba9600-60f2-11e9-9dbe-7da29d53725a.png)

**Comment by OmrSi** [comment]
`I would also appreciate a shortcut or a launch parameter to start batch convert directly.`
@niksedk Maybe make it work with "Alt" like "Okay" does?

**Comment by 07416** [comment]
> 
> 
> `Batch convert` already has a custom shortcut - add something like `Ctrl+B`:
> ![image](https://user-images.githubusercontent.com/1261331/56268847-a2ba9600-60f2-11e9-9dbe-7da29d53725a.png)

I highly suggest making this the default setting.
