### ISSUE TITLE
Error Message Related To RTL Functionality

### ISSUE THREAD

**Issue by YM36** [SubtitleEdit/subtitleedit#3549]
I'm getting this error message when I use RTL mode or open SE with RTL mode enabled
![Error](https://user-images.githubusercontent.com/49760866/56375827-d25ac280-6206-11e9-91b4-35f5d492924b.jpg)

![Error 1](https://user-images.githubusercontent.com/49760866/56470581-bde01b00-63fc-11e9-8f2d-ab0fb94a3e5f.jpg)

And here is details:
[Details.txt](https://github.com/SubtitleEdit/subtitleedit/files/3101214/Details.txt)

I'm On Windows 10 1809 X64' This Error Occures With The Installer, Beta Or Portable SE Versions

**Comment by OmrSi** [comment]
This is also happening on another friend's computer:
![image](https://user-images.githubusercontent.com/20923700/86774943-a91e9000-c05f-11ea-8178-4301a7224595.png)

**Comment by OmrSi** [comment]
After a bit of searching, here is the solution https://stackoverflow.com/a/55809637/14349868

```
the issue then issue could be with your OS. Similar issues were started occurring with windows version 1803.

If you have windows version 1803 then disabling the beta feature will solve the issue.

To Disable Beta: unicode UTF-8 for world wide language support Start=> Region & Language settings => Related settings -> Additional date, time & regional settings => Region -> Change date, time or number formats => select Administrative tab => Click on Change System Locale.. => UnCheck Beta: unicode UTF-8 for world wide language support => restart your system.
```

@niksedk Tested on my friend's PC and it works.
This should be closed.
