### ISSUE TITLE
/FixRtl for CLI 

### ISSUE THREAD

**Issue by wawa0078** [SubtitleEdit/subtitleedit#3551]
anyway to add /FixRt option to SE cli 
like other 
        /removetextforhi
        /fixcommonerrors
        /redocasing
        /forcedonly
i want to /FixRtlReverseStartEnd for files using cli
....

**Comment by OmrSi** [comment]
Hehe. https://github.com/SubtitleEdit/subtitleedit/commit/5a5300583a52767152b0cd80dbad1bbba9462043#r33215599

**Comment by niksedk** [comment]
Do you mean ``ReversRtlStartEnd`  ?

**Comment by OmrSi** [comment]
Reverse rtl Start\End, not via Unicode control. 
I would suggest adding both.

**Comment by OmrSi** [comment]
Closed.

**Comment by OmrSi** [comment]
@xylographe @niksedk implemented, should be closed.

**Comment by xylographe** [comment]
Thx, @OmrSi 

Implemented in 18287cd975909959d9eb9050daa1dbdadbb9eabb
