### ISSUE TITLE
"Fix (add dash)" should be executed before "Fix (remove dash)"

### ISSUE THREAD

**Issue by nyuszika7h** [SubtitleEdit/subtitleedit#3553]
When "Fix (remove dash) lines beginning with dash (-)" and "Fix (add dash) line pairs with only one dash" are both enabled, the former is executed before the latter, which can cause unexpected behavior.

**Input**:
```
Line 1
- Line 2
```

**Expected output**:
```
- Line 1
- Line 2
```

**Actual output**:
```
Line 1
Line 2
```

And since the dash is removed, this won't be fixed in the next pass either.

**Comment by Ding-adong** [comment]
I agree. Add before remove.

For now uncheck `Fix (remove dash)` then fix errors then check `Fix (remove dash)` and fix errors again. A pain in a butt but it works.

**Comment by xylographe** [comment]
@nyuszika7h @Ding-adong

Please, try  **SE-3.5.9-issue3553.7z** (or **SE-3.5.9-issue3553-setup.exe**) from [this folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)

**Comment by Ding-adong** [comment]
That worked. Congrats.
