### ISSUE TITLE
EBU STL only saves or exports as 25 frame rate

### ISSUE THREAD

**Issue by Valer3456** [SubtitleEdit/subtitleedit#3554]
Hi,

I have the version 3.5.9, c424586 of SE.

I discovered that it will only let you save EBU STL files as 25 fps, even if you change that value in the EBU properties save options and you choose 29.97, 24 or any other frame rate.

The saved file will always be 25 fps.

Has anyone noticed this?
When is this going to be fixed?

Thanks!

**Comment by niksedk** [comment]
Works fine here... could you attached a saved file? 
Note that not all programs supports 29.97 fps...

**Comment by Valer3456** [comment]
Hi Nikolaj,

Thanks for your answer. I've been reading many SE topics on GitHUB, so great. 

Sorry, can't post it for privacy reasons. But I have an image showing what I did.

![image](https://user-images.githubusercontent.com/49956617/56682138-51d21100-66a1-11e9-95b1-18c2669ce6d2.png)

I think I have improved a bit now, I selected the option "Disk format code" closer to my frame rate of 29.97. Now the resulting file is 30 fps, but not 29.97. But much closer than 25 to 29.97.

Is this the way I should do it?

Thanks!!!

**Comment by Valer3456** [comment]
OK, I found something interesting. I saved the EBU in all the different possible frame rates: 23.97, 24, 25, 29.97 and 30.

The 3 first work OK, but the last two are exchanged. You save as 30 fps and you get 29.97. And you save as 29.97 and you get 30. That's why I couldn't save as 29.97 choosing 29.97.

Is that going to be fixed?

Thanks!

**Comment by niksedk** [comment]
Works fine here... try viewing the result file with a hex viewer.

**Comment by Valer3456** [comment]
Thanks!

**Comment by nekomatic** [comment]
EBU STL only supports 25 or 30 fps, creating a file with different framerate than these two may result with the file being rejected by may systems as not conforming to the actual file format.
