### ISSUE TITLE
Forms Thread Exception (Win10): 80040111 ClassFactory cannot supply requested class

### ISSUE THREAD

**Issue by StarCaller** [SubtitleEdit/subtitleedit#3555]
![subtitle edit](https://user-images.githubusercontent.com/11780218/56780686-8925e800-679d-11e9-8d9f-084ea2421b99.JPG)

it ran perfect for years.
didn't change nething (win10, latest update).
tried portable & install. tried all versions from 3.56 on.
not working nemore.

**Comment by OmrSi** [comment]
I think this is related https://github.com/SubtitleEdit/subtitleedit/issues/3182

**Comment by StarCaller** [comment]
yep, that was it. I disabled the high contrast setting in 'themes' & everything works perfect again!
thanks for helping me out here!

**Comment by OmrSi** [comment]
Cool, you got it.

**Comment by OmrSi** [comment]
@niksedk Closed?
