### ISSUE TITLE
Wrong waveform

### ISSUE THREAD

**Issue by irenivanova** [SubtitleEdit/subtitleedit#3556]
From .mkv file SE 3.5.9 doesn't extract correct waveform - the waveform doesn't correspond to real events (conversations).

**Comment by OmrSi** [comment]
You need to use FFmpeg which allows you to choose one of the audios.

**Comment by irenivanova** [comment]
Hi, Omar.
Thanks for your piece of advice but I still had the same problem.
I downloaded  FFmpeg but the problem is persisting.
I converted the fıle in mp 4 format as well but problem is still here.
Irena

На сб, 27 апр 2019 г., 15:20 Omar Si <notifications@github.com> написа:

**Comment by OmrSi** [comment]
If there is more than one audio track in the file, ffmpeg should allow you to choose between them.
If that's not working, I'd imagine @niksedk would want to check the video file.
