### ISSUE TITLE
Something wrong with SRT file created by SubtitleEdit

### ISSUE THREAD

**Issue by tuanbs** [SubtitleEdit/subtitleedit#3557]
Hello sir, I have an issue is that the SRT file (please check attachment) created by using SubtitleEdit sometimes cannot be read by another packages to convert it into VTT file. But when I use VLC player to play its video, VLC player stills show the subtitle. 

FYI, I uploaded this SRT file into my server and use [srt-to-vtt](https://github.com/mafintosh/srt-to-vtt) or [SubtitleParser](https://github.com/AlexPoint/SubtitlesParser) to convert it into VTT file, but the first one returns VTT file with blank content, and the other one causes exception when parsing it. Please let me know if I miss any step using this tool to create a good SRT file. Thank you.
[That Girl - YouTube.en.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/3124028/That.Girl.-.YouTube.en.srt.zip)

**Comment by OmrSi** [comment]
Why not use SE to save it as VTT?

**Comment by tuanbs** [comment]
> Why not use SE to save it as VTT?

Well, the requirement is that the website only accepts SRT format to upload, not VTT.

**Comment by tuanbs** [comment]
sorry, issue is fixed by putting my conversion code outside of the `using` block. Somehow the FileStream returns empty content of the SRT file inside the `using` block. Please closed or deleted this issue. Thanks.
