### ISSUE TITLE
JSON file with shot changes

### ISSUE THREAD

**Issue by Valer3456** [SubtitleEdit/subtitleedit#3558]
Hi!

I have this .json file with shot changes I tried to open it using some of the Json file types, and it doesn's seem to work. Any ideas?

Using version 3.5.8 of SE.

[DMN_H264_480p238_185_Proxy_2ch_EN_shot_changes.txt](https://github.com/SubtitleEdit/subtitleedit/files/3131134/DMN_H264_480p238_185_Proxy_2ch_EN_shot_changes.txt)

***I changed the file extension to .txt because it wouldn't let me upload here.

Thanks!

**Comment by niksedk** [comment]
Should be possible... what programs is this json file from?

**Comment by Valer3456** [comment]
I really don't know. 
Maybe EZ Titles.

**Comment by niksedk** [comment]
@Valer3456: How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip (Generate waveform, then go the the "Video menu" and "Genereate/import scene changes)

**Comment by Valer3456** [comment]
AWESOME!

Perfect! Thanks!

**Comment by niksedk** [comment]
Closed in da8f465d13ed4ff8ff8ba0f695957f362d84f4b1
