### ISSUE TITLE
Delay Tool Not Working for Ahead Subtitle

### ISSUE THREAD

**Issue by pootz10** [SubtitleEdit/subtitleedit#3559]
I have a subtitle ahead of sound and I need to decrease 2 seconds 835 milliseconds to let it be synchronized.

I remembered I've already did it on Subtitle Edit older version by pressing Ctrl + Shift + A and setting up a negative time there, but on the current version 3.5.9 is not working.
It does work if I wanted to increase time.

I'm on Win 7 x64 OS

Thanks in advance.

**Comment by xylographe** [comment]
Not sure why you would need a _negative_ time offset. There are two buttons in the dialogue box:
**`Show earlier`** will subtract the offset from the timecode(s). [decrease time]
**`Show later`** will add the offset to the timecode(S). [increase time]

**Comment by pootz10** [comment]
> 
> 
> Not sure why you would need a _negative_ time offset. There are two buttons in the dialogue box:
> **`Show earlier`** will subtract the offset from the timecode(s). [decrease time]
> **`Show later`** will add the offset to the timecode(s). [increase time]

Wow thank you! That's exactly what I needed.
I knew I've already did that before and I couldn't get it.
My bad it was my noobish.
I guess the translation of the application for my native language confused me.

Thank you.
