### ISSUE TITLE
[Suggestion] Allow editing when Find/Find and Replace window is opened

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3564]
Just like Adjust all times, can you make editing allowed when Find/Find and Replace window is opened?
Sometimes you just want to copy another word or edit it while using Find/Find and Replace.

**Comment by Ding-adong** [comment]
I agree and I was about to start a post about it. It is not just this but all open boxes should be allowed to flit between SE and box without the irritating shaky "not allowed" visual punishment.

**Comment by Monovox** [comment]
I want to join this Suggestion. It will make life easier. I often use 'replace' to find lines I need to fix and then continue searching.
