### ISSUE TITLE
[Request] "Allow overlap" setting in Adjust durations dialogue

### ISSUE THREAD

**Issue by Moerges** [SubtitleEdit/subtitleedit#3565]
The "Adjust durations" dialogue notes that "Display time will not overlap start time of next text", and in most cases, this is exactly the desired behaviour. However, for some operations, it would be useful to have the option to allow overlap.

Hence my question: would it be possible to add an "Allow overlap" checkbox to the "Adjust durations" window?

Thank you for your consideration—and for the wonderful tool that Subtitle Edit is in general.

**Comment by OmrSi** [comment]
I think this issue should be closed.
The PR did exactly what the author said, but Nik said he doesn't think it's really needed.
Writing a plugin for it is not worth it, it would be exactly the same with just one extra option.
