### ISSUE TITLE
Slow scanning of folders  in Batch mode

### ISSUE THREAD

**Issue by stephen147** [SubtitleEdit/subtitleedit#3569]
There's a noticeable slow down in the batch tool for folders/subfolders. I haven't used the batch tool in a while but my directory had 13 folders with media files inside. It takes around a minute to scan.

Something not quite right.

**Comment by Ding-adong** [comment]
It depends on how many files you have in all the folders. The more you have the longer it takes.

**Comment by stephen147** [comment]
Perhaps the filter for file types to scan is broken. If I run a `DIR` command in DOS to find `srt` files on the folder it doesn't take any time at all but the program takes around five minutes to find find **`11 files`**.

**FYI**
The root folder has **`11 files`** and in them are **`378 Files, 26 Folders`** exist from the properties dialog.

**Comment by Ding-adong** [comment]
537 files in 23 folders. Scan filter all files - 17 seconds.
4104 files in 316 folders. Scan filter all files - 1 minute 05 seconds.

**Comment by stephen147** [comment]
I was a bit out with the time on my first example. But as you can see the second result of yours is similar. The program for me just hangs on larger scans.

### Full test done, results as follows:

Minutes | Files | Folders
--- | --- | ---
1:05 | 378 | 26
33:10 | 2,841 | 601

**Comment by Ding-adong** [comment]
33 minutes!!!

Perhaps a reinstall?

**Comment by stephen147** [comment]
First thing I have done. 2,500 odd files are not much. It's 1500 less than yours!

Definitely something wrong. 

Where can I find a log of what may be happening?

**Comment by xylographe** [comment]
I have to agree, it is slow!
In powershell:
```
PS> $sw = [System.Diagnostics.Stopwatch]::new()
PS> $sw.Restart(); (Get-ChildItem -File -Recurse -LiteralPath 'E:\Misc' | Measure-Object).Count; $sw.Stop(); "$($sw.Elapsed)"
52368
00:00:08.4611759
```
Subtitle Edit has been scanning the same folder for over 15 minutes now, and not finished yet. However, some of the sub folders contain lots of media container files (more than 10000 in total). I assume, SE is scanning each of these files in turn.

**Comment by stephen147** [comment]
Thanks for that code @xylographe . I'm jumping ship from DOS to PS.

Here's the redults on the folder that took **30mins** `$LOL`.
```
PS C:\Users\user> $sw = [System.Diagnostics.Stopwatch]::new()
PS C:\Users\user> $sw.Restart(); (Get-ChildItem -File -Recurse -Path 'Z:\Movies & TV\2. HD\').Count; $sw.Stop(); "$($sw.Elapsed)"
3561
00:00:07.6953741
```

**Comment by xylographe** [comment]
I think, the second time is so much faster, because Windows has cached the results of the first run in memory, wich should _definitely_ be faster than traversing the file tree on disk.

As can be seen in [BatchConvert](https://github.com/SubtitleEdit/subtitleedit/blob/a6e28848147834f83ead041f40ceb235170a1619/src/Forms/BatchConvert.cs#L1571), SE excludes some file types (extensions), but all the other files are thoroughly tested against all known subtitle formats. This is what is taking so long.

**Comment by stephen147** [comment]
You're dead right about that the caching.

So, in other words, it scans media files also for embedded sub files like `mkvs` when it's not in the exclude list? (*Actually, this is mentioned it does in the changelog*).

I've tried on a folder containing these `mkv` files that I know contain embedded subs `srt` in this case and it doesn't show any when scanning with *batch*.

#### Maybe there be an option to skip media files and just go for the external type filtering out `mkvs` in the process?

**Comment by xylographe** [comment]
After I had a closer look at the source: I was _wrong_ in my assumption!
SE skips files larger than 10MiB. To count the smaller files in powershell:
```
(gci -File -Recurse -Path $pathVar | ?{ $_.Length -lt 10MB }).Count
```
AFAICT SE will extract supported subtitles from Matroska files iff the files are specifically selected (drag-drop or file selector), and _not_ when scanning folders.

I also noticed that while recursively scanning this folder with 50,000+ files it was nearly impossible to abort the operation, but at least that was easy to fix. :-)

**Comment by stephen147** [comment]
> I also noticed that while recursively scanning this folder with 50,000+ files it was nearly impossible to abort the operation, but at least that was easy to fix. :-)

Yes, that was also something that was happening 100% of the time.

#### Smaller file count my end on the same `3561` files. *Not much in the difference*.
```
3307
00:00:01.7560106
```

> and not when scanning folders
Well, it sure does look like it does this. Probably explains the slowness. But yet it doesn't display then after the scan.

If I import that Matroska file in it's literally instant and imports all its subs.
*But*, it takes 7 seconds to scan the same folder where that file lies with no subs in at all with:
**40 Files, 2 Folders**.

**Comment by xylographe** [comment]
> But, it takes 7 seconds to scan the same folder where that file lies with no subs in at all with:
40 Files, 2 Folders.

This is a worst case scenario, 40 files must each be probed for _all_ the subtitle formats supported by SE. If they (or at least most of them) were subtitle files, the probing would stop as soon as the matching format had been found.

The unresponsiveness while scanning is addressed in `SE-3.5.9-issue3569.7z` (or `SE-3.5.9-issue3569-setup.exe`) from [this DropBox folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0). There might still be some delay when pressing **Esc** or clicking the close box, but it should be no more than a second or three.

Solving the ‘slowness’ of the scan is a whole other ball of wax. Using a DFA (deterministic finite automaton) to determine the subtitle format (or reject the file for not containing a subtitle at all) could speed up the scan considerably, but would require a substantial effort to create.

**Comment by stephen147** [comment]
Sorry, just tested and it's **26mins** as opposed to the **30min** test.

My machine can render a 10min 4K video in 10mins. I'd hate to think what it's like on a slower machine.

**Comment by niksedk** [comment]
I've tried to improve the scanning speed a bit in latest beta. Also, it's displays file names so it's possible to see which files are taking a long time to scan (please report those!). Batch convert also has a visible cancel button during scanning.

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by stephen147** [comment]
Thanks, it's way faster and doesn't seem to hang as much. But it's showing that it's scanning `.mp3` files, for which there is no need.

My 26min test has now become 3mins 30 seconds.

I'm sure if mp3's were removed from the search that would improve drastically.

**Comment by niksedk** [comment]
@stephen147: thx for testing and reporting the mp3 issue :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by stephen147** [comment]
Ah, that's more like it.

1 min 35 seconds.

Thanks very much.

![image](https://user-images.githubusercontent.com/14054664/63804560-5d636c00-c90f-11e9-92e5-e7dea8df95f4.png)
