### ISSUE TITLE
[Suggestion] Line-based (language) tagging

### ISSUE THREAD

**Issue by Moerges** [SubtitleEdit/subtitleedit#3571]
An idea for a feature that I would find very useful: (language) tagging on a line-by-line basis.

What I mean by this is: being able to assign a tag to each individual line, and then export subtitle files compiled from selectable (sub)sets of those tagged lines.

---

For example, this would be helpful when creating both standard subtitles and SDH (subtitles for the deaf or hard-of-hearing) subtitles from the same project.

The way I do this now is to create the full SDH subtitles (so with speaker tags, audio event indicators, et cetera), save the file, make a copy of it, and then remove all the SDH cues to create a set of non-SDH subtitles.

With the tagging feature I outlined above, I could simply tag the SDH lines as such, and then, when it comes to exporting, save one set that includes the standard lines plus the lines tagged SDH, and another set that omits the SDH-tagged lines and includes just the standard lines.

---

This would also be useful for creating different sets of forced subtitles for multi-language movies. Let's say I have a movie with three spoken languages—for example, English, Italian, and French—, and I am creating English subtitles for it.

With a line-by-line tagging feature, I could tag the subtitle lines for the English-spoken lines as English, the Italian-spoken lines as Italian, and the French-spoken lines as French, and when exporting, easily create a full set of subtitles (that shows all lines), a forced set for English speakers (so only the Italian- and French-tagged lines), a forced set for Italian speakers (so the English- and the French-tagged lines), and a forced set for French speakers (so the English- and the Italian-tagged lines).

---

I hope I am making myself clear as to what I am proposing—and why. :)

(From a technical standpoint: I suppose the tags wouldn't be saved in the subtitle file itself, but in a sidecar or project file?)

If something like this isn't too difficult to implement, I'd love to see it in future.

**Comment by OmrSi** [comment]
Well, another way to do this would be to put a special char at the beginning of the lines you want, and by that "tagging" them, then select those line via Modify Selection and then export those lines and use `Save selected lines as...` from the right-click menu.

To be clearer, Just add ^ at the beginning of every SDH line you have, then open Modify Selection from the Edit menu, from there select the rule `Starts with` and type ^.
Now all SDH lines are selected, click OK then use `Control + Shift + I` which would invert the selection, therefore exporting all lines that are not SDH lines, and save those via `Save selected lines as...` from the right-click menu.
Then using Replace, replace all ^ with nothing, and by that you would have you SDH file.

You can use anything to "tag" a line, I use {\*} for example, which would tag them and it wouldn't show up on the video.

**Comment by Moerges** [comment]
Thank you for this very helpful tip, OmrSi. I was not aware of the "Modify selection" feature, nor of inverting the selection with Control + Shift + I. I will certainly employ this method on my next project.

I will still leave this thread open for now, in case others are interested in a similar feature (which would mostly just be a shortcut to more easily achieve what you have described), but it has clearly lost a lot of its allure/importance thanks to your method. :)

(Lastly, I'd fully understand if this feature were considered a waste of time and resources.)

**Comment by OmrSi** [comment]
You got it!
The rest is up to the developers. :D
