### ISSUE TITLE
Error message about the file being used by another process

### ISSUE THREAD

**Issue by giramel** [SubtitleEdit/subtitleedit#3573]
I tried to run a Netflix Quality Check on an dfxp file and go the below message even though the file was not being used by another process.

![image](https://user-images.githubusercontent.com/50675501/57797192-cef12300-7741-11e9-8cce-dc61dee2e9ed.png)

**Comment by niksedk** [comment]
I'll close this for now... feel free to open if you can provide steps to re-create this issue
