### ISSUE TITLE
How did the lightweight tesseract4 being built?

### ISSUE THREAD

**Issue by windywater** [SubtitleEdit/subtitleedit#3578]
The standalone tesseract.exe is only 3M, how to build? The [installation of UB-Mannheim](https://github.com/UB-Mannheim/tesseract/wiki) is so huge...

**Comment by niksedk** [comment]
Using vcpkg, see more here: https://github.com/tesseract-ocr/tesseract/wiki/Compiling
(I guess it requires c++ runtime)
