### ISSUE TITLE
Why ClassNN of Waveform keeps changing? How can I prevent or predict that?

### ISSUE THREAD

**Issue by vassilyzaitsev** [SubtitleEdit/subtitleedit#3579]
[null]

**Comment by niksedk** [comment]
Could you explain a bit more? Screenshots are also helpful.

**Comment by vassilyzaitsev** [comment]
Don't worry about it. I was trying to tweak the mouse wheel on the waveform using autohotkey, but I ended up using coordinates (not so reliable) instead of the class. 
It was the first time I faced a program/software that had a class/block/control that kept changing its ID/name.
Anyway.. something very specific... I don't even know why I opened this topic. 
Thanks
