### ISSUE TITLE
Commandline only works when i cd in.

### ISSUE THREAD

**Issue by snusy123** [SubtitleEdit/subtitleedit#3581]
Hey! 

So i am trying to convert .sub to .srt using commanline, and it works great. The problem is that i have to cd into the directory for SubtitleEdit to work.

Running this command does work:
cd "C:\Users\MyUser\Desktop\SubEdit" && SubtitleEdit /convert test.sub srt /fixcommonerrors

This one does not:
"C:\Users\MyUser\Desktop\SubEdit\SubtitleEdit.exe" /convert test.sub srt /fixcommonerrors

When i use the command that does not work i get: Subtitle Edit 3.5.9 - Batch Convert, and then it exits. While the other one i get the correct information.

Anybody kind enough to help? :) Currently running on a windows 10 PC with the portable version 3.5.9.

**Comment by xylographe** [comment]
Apparently, in the second case, your current working directory (which is displayed if you run `cd` without arguments) is _not_ `C:\Users\MyUser\Desktop\SubEdit`. If you don't tell SubtitleEdit the location of the input file(s), it will only look in the current directory. It will _not_ look in the directory where the program itself (`SubtitleEdit.exe`) is located.

Hence, you can either use `/inputfolder:C:\Users\MyUser\Desktop\SubEdit` (useful if you want to convert several subtitle files), or pass the filename as `C:\Users\MyUser\Desktop\SubEdit\test.sub` (or, if your current working directory would be `C:\Users\MyUser`, you could use `/inputfolder:Desktop\SubEdit` or `Desktop\SubEdit\test.sub`.
