### ISSUE TITLE
Regex: How to change the case?

### ISSUE THREAD

**Issue by teodargent** [SubtitleEdit/subtitleedit#3583]
How do I change a letter to lowercase using multiple replace and regex? Like [this](https://regex101.com/r/5RqdC7/1).

**Comment by OmrSi** [comment]
You can't. :\
C# Regex doesn't support it.

**Comment by niksedk** [comment]
Alternatively you could right click in the main window list view - and choose "Change casing for selected lines..."

**Comment by OmrSi** [comment]
I don't think that would work for him, depending on the regex he wrote...

**Comment by OmrSi** [comment]
@teodargent Only thing I could see you doing for this is adding a whole list like:
```
(\p{Ll} )(a) -> $1A
(\p{Ll} )(b) -> $1B
(\p{Ll} )(c) -> $1C
(\p{Ll} )(d) -> $1D
.....
.....
.....
(\p{Ll} )(z) -> $1Z
```

**Comment by teodargent** [comment]
Nice workaround! I'll try doing that.
