### ISSUE TITLE
Application error when loading a video

### ISSUE THREAD

**Issue by Lauca2** [SubtitleEdit/subtitleedit#3585]
When loading a video, I get a Windows Forms Thread exception as shown in the attachment (error box #1).

![image](https://user-images.githubusercontent.com/51126250/58487623-2fcc2280-8168-11e9-9688-1a8046d18d8f.png)

If I click "Ignore", the error box close but I'm unable to extract the sound form from the video, I get a similar error, although a bit different (Error box #2)

![image](https://user-images.githubusercontent.com/51126250/58487594-204cd980-8168-11e9-9155-722b2d955129.png)

**Comment by Lauca2** [comment]
I forgot to indicate that I tested on 2 PCs, both runing Win7 x64, as well a using the internal video player and VLC 3.0.6.
SE version is 3.5.9.0

**Comment by niksedk** [comment]
Should be fixed via commit 0e492d3178c3eadb5fc1af7a6ad89aa92a3cad81

**Comment by Lauca2** [comment]
It's fixed in the beta version received from Nikolaj.
This problem occured on Windows 7 with the latest path. I didn't have the problem on a windows 7 not up to date nor on Windows 10.
Thanks to Nikolaj
