### ISSUE TITLE
Keep failing to export the compared subtitles

### ISSUE THREAD

**Issue by ekdrmsthd** [SubtitleEdit/subtitleedit#3591]
I keep failing to export the compared subtitles
as an html file which I'd been able to do easily without any problems.

I re-installed Subtitle Edit with the newest version
and still have problems doing it.

I attach the error message that pops up
whenever I try to export it.

Please let me know what I should do
to solve the problem ASAP.

Thanks in advance.

Regards,

![0096](https://user-images.githubusercontent.com/51323702/58800162-20564900-8642-11e9-9ff7-89902f59bcee.jpg)

**Comment by xylographe** [comment]
I cannot reproduce this on Windows 7. Could you provide two example files that fail?

**Comment by xylographe** [comment]
Closing due to lack of response.
