### ISSUE TITLE
[request] Registry Key location on Windows XP

### ISSUE THREAD

**Issue by xylographe** [SubtitleEdit/subtitleedit#3592]
I suspect that commit 429f3183476c2f62a648b125aa034260e808ae5e might not be compatible with Windows XP, but I cannot test this myself. Hence, it would be much appreciated, if someone who has installed Subtitle Edit on Windows XP, could perform _one_ of the following two tests.

**1** — If you are familiar with PowerShell, execute this statement first.
```
Get-ChildItem -Recurse 'HKCU:\Software\Classes\Local Settings\MuiCache' | Format-List
```
If that shows two or more registry keys, Windows XP is compatible with Vista (and later). If OTOH that produces an error message or no output at all, try:
```
Get-ChildItem -ea:0 -Force -Recurse 'HKCU:\Software' | ForEach-Object {
  foreach ($v in ($k = $_).GetValueNames()) {
    if ($v.Contains('\SubtitleEdit.resources.dll,')) { $k.Name; break } } }
```
That should report the Windows XP Registry location(s) of the cached indirect strings.

**2** — Testing with **regedit**.
  - Press **Win+R** to open the Run dialog. Type **`regedit`**. Click **OK**.
  - When **regedit** has started, select **HKEY_CURRENT_USER** in the left panel.
  - Press **Ctrl+F** to open the Find dialog.
  - Type **`\SubtitleEdit.resources.dll,`** in the **Find what** text box.
  - Check **Values**. Uncheck **Keys**, **Data**, and **Match whole string**.
  - Click the **Find Next** button.

The search might take a considerable amount of time (like 5‒10 minutes), but eventually (assuming the search has been successful) the full name of the key will be displayed in the status bar at the bottom. It should look like **`HKEY_CURRENT_USER\Software\Classes\Local Settings\MuiCache\8C9\18012CD5`** (the two hexadecimal numbers after **`\MuiCache\`** will be different). If the location of the key is not below **`Software\Classes\Local Settings\MuiCache`**, you can copy it to the clipboard (menu item ‘Edit > Copy Key’).

**Comment by niksedk** [comment]
OK, apparently not much interest in WinXP :)
