### ISSUE TITLE
Line display time is corrupted when change from the waveform.

### ISSUE THREAD

**Issue by xmrea** [SubtitleEdit/subtitleedit#3598]
English | Sorry for my bad english...
-
Subtitle view..
Tools > Sort by > Duration

in this conditions

when I edit the start/end time of a line from the waveform, display time is minus.

----------------
Türkçe

Altyazı görünümü...
Araçlar > Sırala > Süre
şeklindeyken,
dalga formundan bir satırın süresini düzelttiğimde, görüntüleme süresi tabiri caizse uçuyor.

![waweform by time](https://user-images.githubusercontent.com/46967762/58977358-32ff8800-87d2-11e9-97a4-950234dacb5f.gif)

**Comment by Ding-adong** [comment]
What were you trying to do and why use Tools > Sort by > Duration?

**Comment by OmrSi** [comment]
That's probably because of line numbers, just renumber them via Tools -> Renumber and it should work fine.
