### ISSUE TITLE
Some hearing impaired issues 

### ISSUE THREAD

**Issue by teodargent** [SubtitleEdit/subtitleedit#3599]
1. 
<img width="729" alt="dash 2" src="https://user-images.githubusercontent.com/20757457/58983543-5ed13c80-87d7-11e9-9537-2c8a5882e536.PNG">
Expected: 

> <i>Era stato avvertito.</i>

2.
<img width="758" alt="dash" src="https://user-images.githubusercontent.com/20757457/58983585-76102a00-87d7-11e9-94e8-99ac91f67a94.PNG">
Expected: 

> Fidanzato, d'accordo.<br />Okay, fidanzato.

3.
![Annotazione 2019-05-29 213705](https://user-images.githubusercontent.com/20757457/58983943-27af5b00-87d8-11e9-90db-f4dad77d993a.png)
Expected: 

> Non è permesso...

4.
![Annotazione 2019-05-29 004138](https://user-images.githubusercontent.com/20757457/58984051-5d544400-87d8-11e9-868f-5f6c478153fa.png)
Expected: 

> Senti,<br />dille semplicemente che ti è mancata.

5.
<img width="490" alt="puntini" src="https://user-images.githubusercontent.com/20757457/58988738-9db8bf80-87e2-11e9-97e2-d3a5a91fe106.PNG">
Expected:

> Oddio.

**Comment by Ding-adong** [comment]
What version SE?

**Comment by teodargent** [comment]
3.5.9 (10th February 2019)

**Comment by Ding-adong** [comment]
Hearing impaired than use fix common errors.
1 - fix common errors will sort it.
2 - correct as two speakers.
3 - mine removed `Oh!` I can not replicate yours. Use multiple replace find .! replace .
4 - Use multiple replace find , , replace ,
5 - Use multiple replace find .... replace .

**Comment by teodargent** [comment]
I wasn't asking for workarounds, I know how to deal with those issues. I am just trying to help finding bugs. Please let me know if I should continue reporting these kind of issues or if it's something you consider to be normal behavior and are not willing to address.
Also:
2. - There is only one speaker.
3. - You need to add a space after the "..." to correctly reproduce the issue. Copy this: Text... oh!

@niksedk

**Comment by niksedk** [comment]
@teodargent: Sorry, I've been AFK from March... and will be away for a few more moths yet - I have two broken water pipes and everything is packed away :(

**Comment by teodargent** [comment]
@niksedk 
Sorry to hear that :( . I just wanted to know if it's ok for you if I report this kind of issues. You can deal with them when you can, no rush :)

**Comment by Ding-adong** [comment]
`3. - You need to add a space after the "..." to correctly reproduce the issue. Copy this: Text... oh!`

I get Text...

**Comment by teodargent** [comment]
Maybe it's just me then

**Comment by psonnosp** [comment]
No it's not just you.
I get the same thing and I'm on 3.5.10 (18th August 2019) and SE has been behaving like this for me as long as I can remember and I reported it a long time ago in the comments section on the website. Think I got an answer like it was to time consuming to fix at the moment so I just solved it by using 'Multiple replace' and haven't really thought about it up until now.

**Comment by niksedk** [comment]
These cases should now work fine in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

(I've my dev computer up and running - the house is almost fixed after the broken water pipes)

**Comment by niksedk** [comment]
@psonnosp: Sorry, I cannot remember your issue - do create a new issue with attached subtitle file + detailed description - also do test latest beta before posting :)

**Comment by psonnosp** [comment]
It was a looong time ago so I didn't expect you to, just wanted to tell teodargent that he wasn't alone with the issue. But looks like you've fixed it now so all good, thanks.
Glad to hear you have your house back in order :)
