### ISSUE TITLE
[request] Auto top align when OCR

### ISSUE THREAD

**Issue by teodargent** [SubtitleEdit/subtitleedit#3601]
Some subtitles have lines that are top aligned for better visibility but when you OCR those lines became bottom aligned. It would be nice to have the option to preserve the alignment formatting when OCR.
Currently I'm using [this](https://forum.videohelp.com/threads/393321-Is-there-a-tool-to-get-a-list-of-the-sub-lines-not-alligned-bottom) method to locate the lines of interest and then manually adjust the alignment but it is a pretty time-consuming process.

**Comment by niksedk** [comment]
Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

Right-click on the image to enable this "secret" settings:
![image](https://user-images.githubusercontent.com/1261331/64067097-28169100-cc23-11e9-8ea2-d08ee9b311de.png)

**Comment by teodargent** [comment]
It doesn't work for me. 
I tried with this:
https://github.com/SubtitleEdit/subtitleedit/files/3543181/Gravity-.Special.Edition_t01_track11_.ita.zip
Line 7 is top aligned.

![Immagine](https://user-images.githubusercontent.com/20757457/64075042-5f348300-ccb3-11e9-8610-abdc989c55e7.png)
![Annotazione 2019-09-01 122333](https://user-images.githubusercontent.com/20757457/64075044-6360a080-ccb3-11e9-89cd-960b6909e5a2.png)

**Comment by teodargent** [comment]
It worked with this (vobsub):
[interstellar.zip](https://github.com/SubtitleEdit/subtitleedit/files/3563411/interstellar.zip)

Line 433.

**Comment by niksedk** [comment]
OK, thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

Should work with bdsup and vobsub so far.

**Comment by teodargent** [comment]
I can confirm it works with pgs and vobsub now. But it doesn't catch lines where the subs are aligned top and bottom at the same time, like this one:
![Annotazione 2019-09-01 182158](https://user-images.githubusercontent.com/20757457/64079258-c5d29480-cce5-11e9-91d1-7d196464db33.png)

You can use this Borat subs for further testing of unusual lines like the following:
![Annotazione 2019-09-01 182415](https://user-images.githubusercontent.com/20757457/64079288-1b0ea600-cce6-11e9-95eb-00ad25e6d9ab.png)

[Borat 2006.zip](https://github.com/SubtitleEdit/subtitleedit/files/3563701/Borat.2006.zip)
