### ISSUE TITLE
Subtitles littered with <c.mono_sans></c.mono_sans></c.white>, does not display properly in VLC

### ISSUE THREAD

**Issue by Runisco** [SubtitleEdit/subtitleedit#3602]
Is it possible to remove this kind of formatting?

These subtitles look horrible in VLC. I tried using replace all to just replace it with empty, but the the text got formatted weird.

There is also the problem with the lines appearing at the wrong time, relative. The first thing said is on the bottom, the second on top.

Example:
1
00:00:15,120 --> 00:00:17,160
<c.mono_sans>PICARD:</c.mono_sans></c.white>

2
00:00:15,120 --> 00:00:17,160
<c.mono_sans>Resistance is futile.</c.mono_sans></c.white>

3
00:00:17,160 --> 00:00:23,079
<c.mono_sans>You will disarm your weapons</c.mono_sans></c.white>

**Comment by OmrSi** [comment]
You could do this: `</?c.[^>]*>`
![Annotation](https://user-images.githubusercontent.com/20923700/59140288-3ea2a880-89a4-11e9-9fb7-af5800146154.png)

**Comment by xylographe** [comment]
I would start by opening **Edit > Multiple replace…**, create a new group ‘ctags’, and add the regular expression `</?c\.[^>]+>` (with empty replacement). Then open **Tools > Merge lines with same time codes…**. And, finally, **Tools > Minimum display time between subtitles…**.

**Comment by xylographe** [comment]
@OmrSi 
The dot is special char in regex. To match a literal dot, use `\.` (escape with backslash).

**Comment by OmrSi** [comment]
@xylographe I know. :)
I missed it the first time, you commented while I was editing my comment.

**Comment by xylographe** [comment]
@OmrSi
LOL

**Comment by OmrSi** [comment]
@xylographe  Should be closed as well.
