### ISSUE TITLE
Google API key

### ISSUE THREAD

**Issue by duiveldoder** [SubtitleEdit/subtitleedit#3605]
I thought I give the google paid API a chance .. there's a free trial granting you 300 USD to trial..

https://cloud.google.com/translate/pricing?hl=en_US&_ga=2.176325477.-156519926.1560250209

Translation API v2, v3 | Language detection | $20 per 1,000,000 characters* | $20 per 1,000,000 characters*

Obviously language detection isn't needed.. the Subtitle Edit you can set it.

Translation API v2 | Text translation | $20 per million characters | $20 per million characters

Obviously this cost 20 USD per 1 million characters

Translation API v3 | Text translation | Free* | $20 per million characters

up to 500.000 per month is free. After that 20 USD per million characters.

Now even with no restrictions I get errors. It translate a bit and then some 403 error ..

But that's not the weirdest...

even after trying 23.866 characters, that's well within the 500.000 range google substracted already 34,96 USD from the trial account. 

This means translating these 23.866 characters in a paid account would have been 34,96 USD already.

So something must be wrong.

And why not using the v3 API? That allows 500.000 free characters per month.

my average TV show is like 15.000 characters. So that would be 30-40 TV episodes per month

My average movie is like 50.000 characters so that would be 10 movies

also the first 500.000 are free but after that 20 USD per 1 million, that's like 20 movies the translation would be 1 USD per movie or 33 cents per TV show.

Google clearly asking WAY TOO MUCH here but still, first 500.000 would have been free 
so first 30 movies per month, or 100 TV shows per month would cost 20 USD..

but anyway, very weird Google charging 34,96 USD already for 23.866 characters and knowing google I doubt they charge wrong so must be something with your API?

**Comment by niksedk** [comment]
You can monitor the traffic with tool like Fiddler
GT v3 api is still in beta
