### ISSUE TITLE
Add linear synchronization 

### ISSUE THREAD

**Issue by 5j9** [SubtitleEdit/subtitleedit#3607]
[SubShifter](https://subshifter.bitsnbites.eu/) has a Linear correction feature. I could not find a similar feature in SubtitleEdit. Of-coarse one can use the "Change speed"and then "Adjust all times", but this method requires calculating the needed speed change and shift manually. I find entering the four timestamps much easier.

Example:

Timestamp1:	0:00:01.000 ➙ 0:00:02.000
Timestamp2:	0:00:03,000 ➙ 0:00:07,000

the linear equation is y = 5/2 x - 1/2

therefore a speed change of 250% + a shift of -0.5 seconds is required.

**Comment by xylographe** [comment]
[Subtitle Edit Help.](https://www.nikse.dk/SubtitleEdit/Help#sync)

I suspect you want visual sync or point sync.

**Comment by 5j9** [comment]
Oh, I see, I should have read the help pages first, sorry, and thanks!
