### ISSUE TITLE
Wrong fix for uppercase "i" inside word

### ISSUE THREAD

**Issue by XhmikosR** [SubtitleEdit/subtitleedit#361]
```
<i>on another world,
on Jupiter's moon Io...</i>
```

http://en.wikipedia.org/wiki/Io_%28moon%29

/CC @niksedk

**Comment by ivandrofly** [comment]
/CC @niksedk  I think this can also be close tested and seems to be fixed

**Comment by niksedk** [comment]
Seems fixed
