### ISSUE TITLE
Error in fix missing space

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#3610]
Here's a case where the automatic fix is adding a space between the dash and the </i> tag so after the correction, there would be two spaces between the dash and the first word.

![image](https://user-images.githubusercontent.com/11799308/59552291-a9984480-8f8d-11e9-82b8-fd638d712d03.png)

In fact, there's also a problem in detecting that dash as italic (in the original sup file, it's not). Is there a way to avoid setting a single dash as italic if everything around it is not? Probably needs a separate issue ticket for that, just let me know if I should open one.

**Comment by ivandrofly** [comment]
```
- <i>Are targets in sight?
- </i>No, sir.
```

> Here's a case where the automatic fix is adding a space between the dash and the tag so after the correction, there would be two spaces between the dash and the first word.

That is because SE always add space after the closing italic tag `</i>` , so the main problem here is to fix the closing tag position.
