### ISSUE TITLE
Missing italics tag

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#3611]
![image](https://user-images.githubusercontent.com/11799308/59552424-53c49c00-8f8f-11e9-8f2c-5b1cf3ec7a10.png)

The compare matches are OK but the subtitle line only has an ending italics tag before the last " character and does not set it again as italic.

**Comment by niksedk** [comment]
could you attach or email the subtitle?

**Comment by Boulder08** [comment]
I uploaded it here:

[https://drive.google.com/open?id=18eIItDJdHHb5GltIMbNywBevSyITDO7z](url)
