### ISSUE TITLE
feature request - batch process translation

### ISSUE THREAD

**Issue by duiveldoder** [SubtitleEdit/subtitleedit#3612]
First of all I can edit the source code myself as c++, c# programmer but not sure if it's wanted.

Here's my suggestion:

there's this nice plugin using the google scraper.

I need to process a large amount of files and wish for the following.

- use the batch process form and add another option "translating to" 
- a new form for the "translating to" where you can select the languages you need translation
- the software will now automatically load the translation plugin and one after the other translate the files
- a bug in the plugin sometimes leaves empty lines - has to be fixed or verified to redo the translation if empty line is detected
- allow the user to detect if his original filename is using some coding standard like
   xxxxx.ru.srt or xxxxx.rus.srt  for Russian language and if translated into English the result to
   save the files will be:
   xxxxx.ru.srt -> xxxxx.en.srt
   or
   xxxxx.rus.srt -> xxxxxx.eng.srt

Just let me know if it's desired for me to add this I would do it the next week..
or if the developer is going to add this functionality.

Both is fine by me, just do it asap and not waiting 2 months :)

**Comment by darnn** [comment]
I can't speak for Nikolaj, but it doesn't seem likely he'd add anything on that scale in the next few months: https://github.com/SubtitleEdit/subtitleedit/issues/3599#issuecomment-500123302

**Comment by niksedk** [comment]
Feel free to add a plugin for this.
Note that auto-translate is somewhat volatile as the remote hosts can be somewhat difficult to communicate with and they can make changes anytime... as many ppl has complained about ;)

**Comment by duiveldoder** [comment]
Yes I know the remote hosts like to change things. Also I noticed when connection drops the plugin doesn't warn you that you lost connection and you just get "empty lines" instead of translations.

If this is only for 5 seconds, the rest of the returned data looks correct so you might miss it until you start watching the movie.

I think I can build in a handler for this as well... to "retry" for let's say 5 times each time between 10 seconds and if still empty lines push a warning to the user to let him know to "abort" or "continue with empty lines" or "try for another 60 seconds every 5 seconds" before the warning comes again..

so the user can figure out himself why the connection is down.. maybe just needs to restart router or fiber modem or whatever..

But if you see if I add this code you can add it to the main program or as plugin I'll be working on it this week to see to get it done..

Time is short here as well but I think I can handle this in a few days I'll usually find a few hours to work on it.

**Comment by orbittwz** [comment]
Hi!
Can I just reference VASE as the solution to batch google translate??
The repo is gone now, though I have the program and can share it to allow the code for this feature to be implemented for SE, and keep updating it.

**Comment by cocowash** [comment]
Is there a chance that this could also be implemented to translations made by Microsoft Azure?

**Comment by orbittwz** [comment]
any luck implementing this?
I'm attaching the class from VASE for a reference...
There is a 2.5 seconds pause between each call to the API for translating, it's on line 679.
[googletranslate.txt](https://github.com/SubtitleEdit/subtitleedit/files/5665499/googletranslate.txt)
