### ISSUE TITLE
Feature request: Two things regarding the removal of timecodes

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3617]
Hi. So, I realize this will probably take a while, but I just wanted it on the record.
There's currently no easy option to completely remove the timecode for a given subtitle or group of subtitles, which is to say, to set it to this:
`00:00:00,000 --> 00:00:00,000`
Currently I have to manually set the start time to 00:00:00:00 and the duration to 0.00. So it would be nice if there were an option along the lines of "remove timecodes for selected subtitles" (and the ability to bind it to a keyboard shortcut).
The second thing is: When I'm inserting subtitles into a finished file just to translate captions on the screen, I'm instructed to leave the timecode blank. So it would help me if there were an option like "insert new subtitle (before/after) with empty timecode".

**Comment by OmrSi** [comment]
Well, here is a workaround for you.
Go to `Source view` and use Replace to find the regex `\d{2}:\d{2}:\d{2},\d{3}(?= -->)|(?<=--> )\d{2}:\d{2}:\d{2},\d{3}` and replace it with `00:00:00,000`.

**Comment by darnn** [comment]
Oh yeah, workarounds I've got, but they're still only workarounds.
