### ISSUE TITLE
Google Translate Plugin can't handle specific symbols in filenames

### ISSUE THREAD

**Issue by duiveldoder** [SubtitleEdit/subtitleedit#3621]
If the filename of the original .srt file has specific letters like the French "ê" then it won't work and you get empty lines in return.

**Comment by niksedk** [comment]
Works fine here...

**Comment by duiveldoder** [comment]
If it does there must be something else wrong with several of my files. I'll to run the debugger while processing the files


On Jun 17, 2019 21:41, Nikolaj Olsson <notifications@github.com> wrote:
Works fine here...
