### ISSUE TITLE
[Shortcut request] Move forward and back with selected time

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3625]
I'm just leaving this here until later, just so I don't forget.
Would it be possible to add shortcuts to move forward and back with selected time, by that I mean the times we choose from here:
![Annotation](https://user-images.githubusercontent.com/20923700/59714565-a1086e00-921a-11e9-86c5-5dd2462a9077.png)
So, add shortcuts for the arrows...

**Comment by Lucas077** [comment]
I also asked myself this question
I asked this question if I want hotkeys why not put.
Especially for beginners.

**Comment by OmrSi** [comment]
Well, I make an AHK script to use those at the end.
