### ISSUE TITLE
Translating to random letters and numbers in every language you choose to translate to

### ISSUE THREAD

**Issue by Ormendahl** [SubtitleEdit/subtitleedit#3632]
This never happened before and it just started happening yesterda. Picture -->https://i.imgur.com/2yB5pXH.png

**Comment by kitty-code** [comment]
Me too, yesterday

**Comment by niksedk** [comment]
Hm, how is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip ?

**Comment by kitty-code** [comment]
I download the link of beta and it was ok thanks

**Comment by Ormendahl** [comment]
> Hm, how is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip ?

The beta is working, thanks.

**Comment by OmrSi** [comment]
@niksedk @xylographe Already fixed. Closed?

**Comment by niksedk** [comment]
Let's keep it open for a while... it's more visible here (but yes, I do consider this closed)
