### ISSUE TITLE
Command Line Automation - Extract MPEG-TS DVB Subtitle Tracks

### ISSUE THREAD

**Issue by MounaLafi** [SubtitleEdit/subtitleedit#3633]
Just wondering if command line method is working for exporting DVB subtitles embedded into MPEG-TS files.

basically the process is available in SE GUI as follows:

The .ts file is opened in SE, "Blu-ray sup" is exported, then the Video resolution is changed to "1080p (1920x1080)" align is changed to "Center" and then "Export all lines".

I have many videos which I need to extract their subtitles and this way of extracting the subtitles is really consuming time and require a lot of user intervention.

Subtitle Edit command line seems to be a convenient solution to automate the process, but the issue is that it seems that .ts files are not supported as input files.

When I try the below command:
SubtitleEdit /convert "E:\Videos\Test.ts" Blu-raysup

I'm receiving the below error message: 
input file too large!

**Comment by xylographe** [comment]
ATM only Matroska (mkv) and Mp4 supported in command line convert.

**Comment by MounaLafi** [comment]
Hopefully the support for MPEG-TS files will be added in the near future.

**Comment by niksedk** [comment]
SE now has some support for cmd-line/batch convert TS files - only to Bluray sup + bdn/xml for now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by MounaLafi** [comment]
Thanks Nikse for working on this enhancement.

Nevertheless, there is an issue when using the below command line with SE 3.5.10.230:
SubtitleEdit /convert 1.ts Blu-raysup

I'm receiving the below error message:
1.ts - Can only convert transport streams to Bluray-sup or BDN/XML

So, I tried to see what will happen when I convert a subtitle within MKV file using below command:
SubtitleEdit /convert M.mkv Blu-raysup

it seems that it is trying to OCR the subtitle as I'm receiving the below message:
Using OCR to extract subtitles

Going back to SE 3.5.6.214 using the same command line to extract SUP files from MKV generated (2) SUP files:
M.5.ara.sup
M.8.eng.sup

**Comment by niksedk** [comment]
@MounaLafi: thx for testing :)
Cmd line issues should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by MounaLafi** [comment]
Works like charm now for ts files.
The output file is: 1.2073.sup
and it is perfect.
I'm not really concerned about MKV files, but I can see that when using the
below command on MKV file:
SubtitleEdit /convert M.Mkv Blu-raysup
SE is still trying to OCR:
Using OCR to extract subtitles
OCR... : 16%
Shouldn't the output be a SUP file like older versions of SE.
Anyhow, my issue for ts files is resolved. Many thanks for your usual
support.

Kind Regards,
Mouna.

**Comment by MounaLafi** [comment]
It seems that the parameter "/resolution" is being ignored.

Trying the below command:
SubtitleEdit /convert *.ts Blu-raysup /resolution:1920x1080
or
SubtitleEdit /convert *.ts Blu-raysup /resolution:1920,1080

resulting in a SUP file with original resolution (PAL 720x576).

**Comment by niksedk** [comment]
Thx for testing :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Beta updated again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
(was using new "width" for both width and height...)

@MounaLafi: You might need to resize, as the video player often will handle this.

**Comment by MounaLafi** [comment]
The issue is still there.

I tried to open resulting SUP file in BDSup2Sub and it is still showing original resolution as following:

![SUP_PAL](https://user-images.githubusercontent.com/16671403/67165042-9f4de300-f391-11e9-90fa-808379c1da26.png)

For comparison, below is the resolution of SUP file in BDSup2Sub which is generated through SE GUI:

![SUP_1080](https://user-images.githubusercontent.com/16671403/67165050-ad9bff00-f391-11e9-96f1-7ffa8d8cc5ce.png)

In SE GUI, I have opened the .ts file and then chose export to Blu-ray sup and then changed the resolution as shown below:

![SE_Export](https://user-images.githubusercontent.com/16671403/67165156-ca850200-f392-11e9-8bd4-14bc5f32f602.png)

**Comment by niksedk** [comment]
This cmd line works fine for me:  `subtitleedit /convert a.ts bluray /resolution:1920x1080`

Anyway, just updated latest beta to be sure: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

In SE Batch convert, you need to use the "TS settings" for .ts/.m2ts files:
![image](https://user-images.githubusercontent.com/1261331/67179244-0d1bfe00-f3d6-11e9-8a80-265d34f5ad85.png)

**Comment by MounaLafi** [comment]
Command line is still not working for me with resolution parameter. 
Might be an issue from my end, but anyhow SE batch converting did the trick.

Thanks for you usual support Nikse.

**Comment by niksedk** [comment]
Ah, bdsup does not show the resolution until after the "Conversion Options":
![image](https://user-images.githubusercontent.com/1261331/67236375-72f59d80-f449-11e9-8aff-3dee8a38ee46.png)

Np, this is a nice feature - and it's the first time that SE respects the resolution from the transport streams :)
