### ISSUE TITLE
[issue] Auto Correct special simbols in Spanish

### ISSUE THREAD

**Issue by Lokotito** [SubtitleEdit/subtitleedit#3635]
Working with stable version, in SRT subtitles in Spanish language. Using Win10 x64.
When you use "FIX COMMON ERROR...", and select/check:
"Fix Spanish inverted question and exclamation marks"

The program disclaim the user choice of the lines to apply this correction, even if a line is not selected by the user the program apply the correction.
Example:
Line 1: ¿Debo preguntar...
Line 2: ...otra vez?

Result of fix (even is not selecting line1 and line2):
Line 1: ¿Debo preguntar...?
Line 2: ...otra vez?

Sometimes the dialog was divided in two lines and when the question/exclamation mark is present in line1 sometimes is closed in line2 (or line3), but the program apply the fix to all lines starting whit "¿" or "¡" characters, even if users didn't wat to apply this fix to that lines.

**Comment by xylographe** [comment]
Reproduced with 3.5.9 beta. Both lines unchecked in FCE:
```
¿Debo preguntar?...
...otra vez?
```

**Comment by xylographe** [comment]
Please, test **`SE-3.5.9-issue3635.7z`** (or **`SE-3.5.9-issue3635-Setup.exe`**) from [this DropBox folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0). Unchecked (not selected) fixes should no longer be applied.

**Comment by Lokotito** [comment]
Tested SE-3.5.9-issue3635.7z from dropbox, still the same results:
Line1: ¿Cuántos hermanos...
Line2: perdieron la vida sin
conseguir un ritual adecuado?

UNCHECKED "Fix Spanish inverted question and exclamation marks" in FCE
Same result
Line1: ¿Cuántos hermanos...?
Line2: perdieron la vida sin
conseguir un ritual adecuado?

What I notice is that Line2 was not detected as a line that needs FIX question marks, only Line1 is listed (and auto corrected even without check mark).

**Comment by xylographe** [comment]
Image 1, Main window

![esp1](https://user-images.githubusercontent.com/8535293/60362729-f3e3e180-99e1-11e9-90a1-f7252e79813f.png)

Image 2, Fix Common Errors step 1

![esp2](https://user-images.githubusercontent.com/8535293/60362747-00683a00-99e2-11e9-804a-c4803d49e167.png)

Image 3, Fix Common Errors step 2

![esp3](https://user-images.githubusercontent.com/8535293/60362762-0827de80-99e2-11e9-9821-08715440f752.png)

All three proposed fixes unchecked.
After clicking **Aplicar correcciones** nothing has changed.
