### ISSUE TITLE
settings are not reset in beta

### ISSUE THREAD

**Issue by svenverslype** [SubtitleEdit/subtitleedit#3641]
Hello

my setting is always reset if i open my subtitle edit
beta version 3.5.9

**Comment by xylographe** [comment]
Is it possible that you extracted the ZIP archive in a restricted folder (like `C:\Program Files`)?
SE would not be able to store `Settings.xml`, unless run as Administrator.

**Comment by niksedk** [comment]
I'll close this for now... feel free to re-open if you can provide steps to re-create this issue
