### ISSUE TITLE
Generate QC Report to HTML or print to PDF

### ISSUE THREAD

**Issue by jamiegau** [SubtitleEdit/subtitleedit#3643]
A common issue is that I use SubTitle edit is to deal with subtitles I add to Independent films and the creation of DCPs.
Commonly the subtitle files are created by external services.

These subtitle files are commonly very poor.

It would be great if the ISSUE or FIX suggestion tool could be used to output a REPORT (Based on what issues to scan for) that can then be sent to the clients wanting me to use the subtitle files so I can give them something material as to why the subtitles they have supplied are not so great.

Could this be a plugin for example?

**Comment by niksedk** [comment]
You could try to change the subtitle format to "Timed Text 1.0" and check Tools -> Netflix quality check...
