### ISSUE TITLE
copypaste .js script to automatically copy results from google.com

### ISSUE THREAD

**Issue by andradadad** [SubtitleEdit/subtitleedit#3649]
Could you improve copy-paste so that it become faster?
1. Icon on toolbar for faster access, and shortcut.
2. The initial prompt is already the text copied (without having to click on the useless "translate")
3. Someone make a greasemonkey javascript so when you paste on google, it already copies the result to clipboard. Because it's very tiresome to scroll to the bottom of the page at each paste, because the text is too long.

I'm on windows 7, and the "google-screenscrapping" isn't available for my OS yet sadly.

**Comment by niksedk** [comment]
2) I'm not sure what you mean?

3) to scroll to the end just presss ctrl+end

**Comment by andradadad** [comment]
1. An icon to the toolbar instead of several clicks to find the option.
2. I have to select all lines with ctrl+a, then right click, then wait for "translate selected lines" (because there's a small ms delay to show up the options),  then find copy/paste and click, so finally still having to click on "translate" even if it could already be prompting the "translate block" dialog cancelling afterwards if any change is needed (which I personally never had to do).
3.Still, there's so much mechanic work. I believe a script for the browser could easily perform this, saving the user a lot of clicking and scrolling.
