### ISSUE TITLE
Add ability to time-shift VobSub subtitles without OCR

### ISSUE THREAD

**Issue by SumatraPeter** [SubtitleEdit/subtitleedit#3650]
I just got my hands on a VobSub .IDX+.SUB pair for an MP4. Unfortunately the subtitles were 5 secs. slower to display throughout than required, and thus obviously needed to be sped up by 5 secs. I tried opening the .SUB with SubtitleEdit in order to time-shift it by -5 secs., but the program seems to insist on performing OCR first!

I then searched the net and found that I could simply edit the .IDX in any text editor and insert one or more `delay: [-/+]HH:MM:SS:sss` lines in it as required in order to time-shift all the following _timestamp_ lines. So all I had to do was the following in order to fix the subtitle's timing:

**FROM**

    # VobSub index file, v7 (do not modify this line!)
    # Created by BDSup2Sub 5.1.2
    (some lines omitted)
    # English
    id: en, index: 0
    # Decomment next line to activate alternative name in DirectVobSub / Windows Media Player 6.x
    # alt: English
    # Vob/Cell ID: 1, 1 (PTS: 0)
    timestamp: 00:00:29:947, filepos: 000000000
    (further timestamp lines)

**TO (Note addition of _delay_ line)**

    # VobSub index file, v7 (do not modify this line!)
    # Created by BDSup2Sub 5.1.2
    (some lines omitted)
    # English
    id: en, index: 0
    # Decomment next line to activate alternative name in DirectVobSub / Windows Media Player 6.x
    # alt: English
    # Vob/Cell ID: 1, 1 (PTS: 0)
    delay: -00:00:05:000
    timestamp: 00:00:29:947, filepos: 000000000
    (further timestamp lines)

I also found that a tool like SubResync (part of VobSub I believe) can fix all the succeeding _timestamp_ lines based on any specified _delay_ lines, so that in the end one can have a fixed .IDX with no _delay_ lines at all.

My question is, since all it takes to time-shift a VobSub subtitle is to edit the text format .IDX (i.e. no modifications to the .SUB and no OCR required), can this feature be added to SubtitleEdit? I mean to say that SubtitleEdit should allow users to open and time-shift VobSub subtitles without popping up the OCR dialog.

**Comment by OmrSi** [comment]
Well, you can do that, kinda.
Just open the SUB/IDX file then click OK without OCR, it will give you an SRT file without text, do what you want on that file and save it.
Now open the SUB/IDX again and right-click on any line then choose "Import new time codes" then select the SRT file, then right-click again and choose Export.

**Comment by SumatraPeter** [comment]
@OmrSi: Thanks, I'll try it out next time. Just to be clear though, this will result in a SUB/IDX with fixed timestamps, but all original styling (italics, font color etc.) will be lost? What about positioning (some SUB/IDX files display text at specific locations) - will that be lost as well?

I'd really love to see SubtitleEdit accomplish time shifting without causing data loss or making any other changes to VobSub subtitles.

**Comment by OmrSi** [comment]
Yeah, you would lose it all.
When I asked the developer he said, `Sorry, SE do not keep positions from binary files`

There is a workaround if you wanna keep them, though.
After you export the file with new time codes, you'll get a SUB/IDX file without styling, so you'll need to get those from the original file.
Take all lines from the new file and put them here: https://regex101.com/r/JkcK3q/1
Then take all lines from the original file and put them here: https://regex101.com/r/5L9eaM/2
Then copy the result of the first and second link and put them here after changing `2141` to the number of lines in your file: https://regex101.com/r/uaqcoi/1
Now copy the result to the last `timestamp: xx:xx:xx:xx, filepos: xxxxxxxxx` to the original file.
That way, you'll get a file with the new timing and the old styling/positioning.

It might seem a bit complicated at first, but it's easy when you try it.
As far as I know, SubResync removes styling as well.

**Comment by SumatraPeter** [comment]
Or I suppose I could just split at the comma in Excel and replace the original timestamp column data with the updated one. 🙂

BTW the output of your third regex doesn't seem to result in the expected `timestamp: dd:dd:dd:ddd, filepos: ddddddddd` as expected, unless I'm doing something wrong?

>  As far as I know, SubResync removes styling as well.

Is that so? Surely there's _something_ out there that can accomplish this without data loss? Hard to imagine that's not the case, given how this honestly seems to be a not-so-complex text editing feature involving changing successive timestamp values without touching anything else in the file.

**Comment by OmrSi** [comment]
Hehe, I use the Excel way, but I just didn't wanna add another program to the mix.
The important thing is that you get the idea of copying the timestamps from the new file to the old one.

The regex works, you have to just copy the lines that contain both timestamp and filepos and ignore the rest. But using Excel is easier.

To be honest, I didn't try `SubResync` myself, but someone who uses it was asking for a way to keep the styling/positioning so I took it that it doesn't keep them.

**Comment by SumatraPeter** [comment]
> The regex works, you have to just copy the lines that contain both timestamp and filepos and ignore the rest.

I get that, but the problem is that in the _Substitution_ section I'm not seeing **$0$1** result in any lines with both parts (timestamp and filepos) joined back together:

![image](https://user-images.githubusercontent.com/15380332/71862255-40417400-311f-11ea-9bb5-19c9a0a2eb71.png)

**Comment by xylographe** [comment]
I'm not entirely sure what the goal is. If you just want to change the timestamps without changing filepos, [a simple posh-script](https://gist.github.com/xylographe/4fc5652e9642d6e81bc73c0dc79e6dce) should do it. The _Delay_ argument is in milliseconds, for example
 `Delay-VobSubTime -LiteralPath Title.idx -Delay 4000`
or
 `Delay-VobSubTime 4000 Title.idx` (without explicit parameter names delay goes before path).

**Comment by OmrSi** [comment]
@xylographe But you can't do that if you wanna do something more complex, right?
Like delay some lines or add to the duration of each line?

**Comment by xylographe** [comment]
@OmrSi 
Not impossible, but it would be a lot easier to write a utility in C# to apply the delay to selected lines only.

How do you change duration in an IDX file?

**Comment by OmrSi** [comment]
@xylographe It was just an example, I meant that instead of having to write a script for each operation on timing, you can just edit it with SE then return it to the original file.

**Comment by xylographe** [comment]
@OmrSi 
I think, I understand what you meant now. Perhaps, it would be more convenient, if one could [replace the IDX timestamps with the new timestamps from the SRT](https://gist.github.com/xylographe/d8f4300b99f88f2bb2ac0e7abdd65670) without exporting the SRT first?

**Comment by OmrSi** [comment]
That would be best.
But even now when you Import new timecodes from an SRT, you have to export again and by that lose the styling/positioning.

**Comment by xylographe** [comment]
Yes, it is a different script. It takes the recalculated timestamps from the SE generated SubRip file, and puts them in the original IDX file.

**Comment by SumatraPeter** [comment]
@xylographe: Will take me some time to figure this out (haven't really used PS a lot), but thanks for the scripts. My original request of course was to have such functionality available in a GUI editor such as SubtitleEdit itself, but I guess these scripts will do for now.

**Comment by xylographe** [comment]
@SumatraPeter I suppose the simple substitution of timestamps in an IDX file can be easily made available in SE via a plug-in.

**Comment by xylographe** [comment]
This [VobSubTimestamps](https://www.dropbox.com/s/mnfbey41n49hv2h/VobSubTimestamps.7z?dl=0) plug-in is similar to the _Import-VobSubTimestampsFromSubRip_ script, but there is no need to save the SRT file. Use **File > Import/OCR VobSub** to import the VobSub timestamps. Adjust start time codes with SE as usual, then select **Synchronization > Replace IDX timestamps**.

**Comment by OmrSi** [comment]
@xylographe Pretty cool. You should add it to the plugins, it's very useful. :D

**Comment by SumatraPeter** [comment]
Thanks @xylographe! And yeah, if this can be added to the official package or plugins list it would be great.

P.S. I'm attaching your file [here](https://github.com/SubtitleEdit/subtitleedit/files/4060021/VobSubTimestamps.zip) as well in case it drops off Dropbox in future.

**Comment by xylographe** [comment]
Added to the [SubtitleEdit/plugins](https://github.com/SubtitleEdit/plugins) repository.
Available in SE via **Files > Plugins...**

**Comment by Jack1789** [comment]
@xylographe 

Hi, with some files I'm getting a "Too many timestamps in IDX file" error message
while trying to save modified timings. Can that be fixed somehow?

**Comment by xylographe** [comment]
@Jack1789 

The number of time codes in the SubRip subtitle must be exactly the same as the number of timestamps in the IDX file. The `Too many timestamps in IDX file` error message appears when one or more lines (time codes) have been deleted in SubtitleEdit.

**Comment by Jack1789** [comment]
> @Jack1789
> 
> The number of time codes in the SubRip subtitle must be exactly the same as the number of timestamps in the IDX file. The `Too many timestamps in IDX file` error message appears when one or more lines (time codes) have been deleted in SubtitleEdit.

Alright, now I understand it and makes sense, since with some subtitles,
I delete some erroneous "dupe" lines, besides doing the needed time adjustments.

Is there a way you contemplate this kind of scenarios, where one has to delete dupe lines,
so they also get deleted in the "idx" files, before saving?

Thanks.
