### ISSUE TITLE
crc error on defective dvd

### ISSUE THREAD

**Issue by petremure** [SubtitleEdit/subtitleedit#3652]
Trying to extract the subtitles from a defective dvd, i get successive crc error warnings, culminating with program crash - see jpg attachment.
Anything i can do?
![error](https://user-images.githubusercontent.com/52654602/60805494-efa98800-a188-11e9-8524-4bc21b045d3d.jpg)

**Comment by darnn** [comment]
I mean, if the DVD is well and truly damaged, you're not going to be able to read it with anything, and that's certainly beyond the scope of Subtitle Edit. If it's merely scratched but potentially readable, I'd recommend copying it using DVD Decrypter, and then trying to extract the idx/sub from the local copy: http://www.dvddecrypter.org.uk/

Barring that, you're probably going to have to find another copy of the DVD, or try to buff out the scratches, but I've never done that myself so I can't speak to that.
