### ISSUE TITLE
Error by open TS File

### ISSUE THREAD

**Issue by MrRoso** [SubtitleEdit/subtitleedit#3653]
Error Message:
Eine Ausnahme vom Typ "System.OutOfMemoryException” wurde ausgelést.
Stack Trace:
bei System.IO.MemoryStream.set_Capacity(Int32 value)
bei System.IO.MemoryStream.EnsureCapacity(Int32 value)
bei System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
bei Nikse.SubtitleEdit.Core. TransportStream. TransportStreamParser.Parse(Stream ms, LoadTransportStreamCallback callback)
bei Nikse.SubtitleEdit.Core. TransportStream. TransportStreamParser.Parse(String fileName, LoadTransportStreamCallback
callback)
bei Nikse.SubtitleEdit.Forms.Main.ImportSubtitleFromTransportStream(String fileName)
bei Nikse.SubtitleEdit.Forms.Main.OpenSubtitle(String fileName, Encoding encoding, String videoFileName, String
originalFileName)
bei Nikse.SubtitleEdit.Forms.Main.OpenNewFileQ)
bei Nikse.SubtitleEdit.Forms.Main. ToolStripButtonFileOpenClick(Object sender, EventArgs e)
bei System.Windows.Forms.ToolStripltem.RaiseEvent(Object key, EventArgs e)
bei System.Windows.Forms.T oolStripButton.OnClick(EventArgs e)
bei System.Windows.Forms.ToolStripltem.HandleClick(EventArgs e)
bei System.Windows.Forms.T oolStripltem.HandleMouseUp(MouseEventArgs e)
bei System.Windows.Forms.ToolStripltem.FireEventInteractive(EventArgs e, ToolStripltemEventType met)
bei System.Windows.Forms.ToolStripltem.FireEvent(EventArgs e, ToolStripltemEventType met)
bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
bei System.Windows.Forms.Control.WndProc(Message& m)
bei System.Windows.Forms.ScrollableC ontrol.WndProc(Message& m)
bei System.Windows.Forms.ToolStrip. WndProc(Message& m)
bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
bei System.Windows.Forms.NativeWindow.Callback(ntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

What is going wrong. What can i do to open the Transport Stream file and get the included subtitels?

**Comment by niksedk** [comment]
I'm aware that this uses a lot of memory... how much memory did you have free and how large was the ts file? when did the error occur (in the end or middle of reading the ts file)?

**Comment by mkver** [comment]
I made the observation that the transport stream reader uses lots of memory, too. I came to the conclusion that it's the tracks whose underlying PES streams are of private_stream_1 type. In my case it's a teletext stream and a ac3 stream which seems to be completely cached in memory despite it not being used at all. Memory usage grows to more than 1.4 GB. The reason for this seems to be that private_stream_1 tracks aren't analyzed right away whether they are potentially dvbsubs (i.e. whether their payload begin with 0x20), but are cached and only analyzed at the end. See [here](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/TransportStream/TransportStreamParser.cs#L110).

(Given that you have not uploaded a sample it is possible that your problem has a different cause than what I just said.)

**Comment by niksedk** [comment]
@mkver: thx for the info. I just tested with a 3.8 GB .ts file and SE used up to 1.3 GB which does seem way too high (2.5 million TS packets in memory).

How is this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
Now the PES packets are created while parsing the ts packages and non-image PES packets are thrown away.
(not tested much, and I've not included m2ts yet)

But I want to keep the teletext packages as SE will hopefully be able to read these somewhat too someday... just converted a small C program to C# for just that: https://github.com/niksedk/telxcc-sharp.

**Comment by niksedk** [comment]
The memory went from 1.3 GB to 75 MB for my 3.8 GB file :)

@MrRoso: Sample files are always nice... does the beta work for you?

**Comment by mkver** [comment]
I worked for me (but I only tested it on one file). Thanks for the fix.
