### ISSUE TITLE
Is there a shortcut to reset video playback speed?

### ISSUE THREAD

**Issue by goodju** [SubtitleEdit/subtitleedit#3660]
It's good that there are shortcuts to speed the video up to 300%,
but is there a shortcut to reset the speed to 100% directly rather than gradually?

I know I can do that using the mouse, but with keyboard shortcuts it would be much easier and faster.

**Comment by goodju** [comment]
Well, maybe there isn't.
Anyway, I really hope that we see this feature in the next versions.
It will be very useful.

**Comment by niksedk** [comment]
Thx for the suggestion - included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
(default shortcut is Crl+0)

**Comment by goodju** [comment]
> Thx for the suggestion - included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
> (default shortcut is Crl+0)

Thank you very much niksedk for responding to my suggestion.

It does reset the video speed to 100% in the actual video, but unfortunately not in the speed list icon on waveform. So if I make the speed 300% "the maximum" and then reset it to 100% using Crl+0, it does reset it, but when I want to make it faster again, It doesn't go any faster because it's still at 300%.
So I'm stuck at 100% actual speed, and what it says is 300%.

What would the best is if you can make "Crl+0" reset the speed in both the actual video and the speed list icon.

Thank you again.

**Comment by niksedk** [comment]
Fixes for UI added in commit 6cb9a122c5ea690ea36e554cca0ca3b8f3272327
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by goodju** [comment]
> Fixes for UI added in commit [6cb9a12](https://github.com/SubtitleEdit/subtitleedit/commit/6cb9a122c5ea690ea36e554cca0ca3b8f3272327)
> Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

It works perfectly now. Thank you.

**Comment by niksedk** [comment]
thx for testing :)
