### ISSUE TITLE
[Feature Request]: Point sync PGS timings from SRT subtitle

### ISSUE THREAD

**Issue by steffenmandrup** [SubtitleEdit/subtitleedit#3661]
I'm one of those weirdoes who prefer PGS subtitles as they are more comfortable to look at.

Would be nice to be able to point sync a PGS sup to the timings from a SRT sub. Often the linecount are the same, but the timings are different.

If i convert from PGS to SRT using tesseract i can get errors and also end up loosing position data as well as the font used.

Would be great just to be able to direct translate timings from a SRT file into the existing PGS file and maintain all the old data

**Comment by steffenmandrup** [comment]
Might be related to https://github.com/SubtitleEdit/subtitleedit/issues/3650

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/3650 is closed with a plugin, so this might be as well.
Note that the plugin works for SUB/IDX but not SUP.
