### ISSUE TITLE
WindowsFormsThreadException when opening sync via other subtitle

### ISSUE THREAD

**Issue by avnerbh** [SubtitleEdit/subtitleedit#3665]
Below is an ocr of the error message popup - I also attached image of the popup message:

**Windows Forms Thread Exception** 

An application error occurred in Subtitle Edit 3.5.9.0. Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information: 

Error Message: n 1131 "V111910 MY,- COM DV CLSID,W {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} D- ICIassFactory 80040111 :Men DWAVin 2pIl15W21ClassFactoly cannot supply requested class (0 n- HRESULT: 0x80040111 (CLASS_E_CLASSNOTAVAILABLE)). 
Stack Trace: 1- System.Windows.Forms.OpenFileDialog.CreateVistaDialog0 2- System.Windows.Forms.FileDialog.RunDialogVista(IntPtr hWndOwner) 1- System.Windows.Forms.CommonDialog.ShowDialog(lWin32W indow owner) 2- Nikse.SubtitleEdit.Forms.Main.pointSyncVia0therSubtitleToolS tripMenultem_Click(Objed sender, EventArgs e) 1- System.Windows.Forms.ToolStripltem.RaiseEvent(Object key, EventArgs e) 1- System.Windows.Forms.ToolStripMenultem.OnClick(EventArgs e) 1- System.Windows.Forms.ToolStripltem.HandleClick(EventArgs e) 1- System.Windows.Forms.ToolStripltem.HandleMouseUp(Mouse EventArgs e) 2- System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventAr gs mea) 2- System.Windows.Forms.ToolStripDropDown.OnMouseUp(Mo useEventArgs mea) 2- System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, InS2 clicks) 2- System.Windows.Forms.Control.WndProc(Message& m) 2- System.Windows.Forms.ToolStrip.WndProc(Message& m) 1- System.Windows.Forms.ToolStripDropDown.WndProc(Messag e& m) 2- System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, InS2 msg, IntPtr wparam, IntPtr Iparam)

![error](https://user-images.githubusercontent.com/3755468/61588723-f5e82d00-aba8-11e9-9918-8f581c3d7652.png)

**Comment by darnn** [comment]
This is neither here nor there, but have you tried the latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by avnerbh** [comment]
it is reproduced with the beta too.
BTW, yesterday I checked it with SubtitleEdit-355 and it was reproduced too.

**Also, please notice that on my other PC this error doesn't occur.  Hence, the error has something to do with something to you don't find in the current PC.**

![error-with-beta-403](https://user-images.githubusercontent.com/3755468/61588970-955aef00-abac-11e9-9097-f61cb3a83152.png)

**Comment by xylographe** [comment]
Is it possible the two PCs are running different versions (releases) of Win10?

**Comment by avnerbh** [comment]
both PCs are running Windows 10 Pro.
the Windows version of the "bad" PC is 1809 (OS build 17763.615).
the Windows version of the "good" PC is 1903 (OS build 18362.239).  However, this was only recently updated and I used the "sync via other subtitle" even before the Windows update on this PC.

**Comment by avnerbh** [comment]
Hi
I used Windows Update for updating the "bad" PC to latest version of Windows - 1903.
Now the problem doesn't occur any more.
Cheers,
  Avner

**Comment by xylographe** [comment]
:+1:
