### ISSUE TITLE
"File on disk modified" dialog appears for no reason

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3666]
So, I'm not sure when this was introduced, since I haven't updated since February or so (since everything works great, pretty much!).
But now that I switched to the most recent beta (3.5.9 NEXT 403), this started happening.
In translator mode, after working for a while and using the keyboard shortcut "save all", I get the following message:
![se-file on disk modified](https://user-images.githubusercontent.com/19672444/61599921-1b6f4800-ac36-11e9-86af-fde171564527.png)

If I simply click "yes" everything proceeds as intended, but I don't know what's causing it to begin with. I'm actually not entirely sure how to reproduce this exactly, so I hope that won't be necessary since you know what changes you made that might have caused this, but there you go.

Edit: I should add that the file it's asking about is the translation rather than the original, if that makes a difference.

**Comment by xylographe** [comment]
Please, try **`SE-3.5.9-issue3666.7z`** (or **`SE-3.5.9-issue3666-Setup.exe`**) from [this DropBox folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)

**Comment by xylographe** [comment]
> I'm actually not entirely sure how to reproduce this exactly,

This won't happen if the file is located in a regular folder on a local file system. But `D:\Dropbox\` is not a regular folder. Sometimes a file's `LastWriteTime` may change without content change.

**Comment by darnn** [comment]
Thank you! I'll try with files in the Dropbox folder and report back. Today this doesn't seem to have happened (with the same build I was using), but half the time my files weren't in the Dropbox folder, and I didn't work on any one thing for as long as yesterday.

**Comment by niksedk** [comment]
Could it have been related to "reo-do" ?
Fixed in latest beta via commit 0a589836897bc7dc2bbfc4d2a1d79ac2e93cdb6c

**Comment by darnn** [comment]
Possibly! I actually haven't been able to replicate it since, even in the same build...

**Comment by niksedk** [comment]
I'll close this for now - let me know if it happens again
