### ISSUE TITLE
Cannot download .srt file, getting an error message.

### ISSUE THREAD

**Issue by mayageorge** [SubtitleEdit/subtitleedit#3669]
After completing captioning the file, I tried to download it. But couldn't save/download it, I am getting a error message along with it. Tried with different browser and different systems. But still facing the issue.
<img width="625" alt="Screenshot at Jul 23 20-23-08" src="https://user-images.githubusercontent.com/53230867/61729840-c21e2a80-ad95-11e9-9fe8-371f8d62e622.png">
<img width="743" alt="Screenshot at Jul 23 20-22-47" src="https://user-images.githubusercontent.com/53230867/61729841-c21e2a80-ad95-11e9-8695-bdb07153fdcd.png">

**Comment by niksedk** [comment]
Not really related to the Windows program, so I will close this.
But it works for me...
