### ISSUE TITLE
OCR with manual edit

### ISSUE THREAD

**Issue by csengh** [SubtitleEdit/subtitleedit#3671]
I want to convert a .sub file extracted from a DVD in .srt subtitle,
After I stop OCR and make some text changes then I start OCR again from begining, the manual changes are lost, the old text is restored. Is it possible to make manual editing definitive and start OCR again from begining? After all manual editing  I want to get empty list in "All fixes" for the last OCR.

**Comment by OmrSi** [comment]
@niksedk Do you think this still happens?
