### ISSUE TITLE
eng_OCRFixReplaceList

### ISSUE THREAD

**Issue by csengh** [SubtitleEdit/subtitleedit#3672]
I delete all in ReplaceList of eng_OCRFixReplaceList.xml file however after a .sub file OCR all ` characters are replaced by ' characters.  "All fixes" tab shows:

> something` ->something'

eng_OCRFixReplaceList_User.xml and "multiple replace" are empty too so where is this replacement stored and how can I stop it?

**Comment by xylographe** [comment]
Try unchecking **"Fix common OCR errors"** in **Options > Settings > Tools**.

**Comment by csengh** [comment]
Ok but where is the "hard-coded rule" specified in this option? I want to modify his list!

**Comment by xylographe** [comment]
It is specified in the source code, in [libse/Dictionaries/OcrFixReplaceList.cs](https://github.com/SubtitleEdit/subtitleedit/blob/52823ed50341920b51238e428cfe559b7363615f/libse/Dictionaries/OcrFixReplaceList.cs#L346).

**Comment by csengh** [comment]
Oh Yeah, I found it in //always replace list
Thank You!
