### ISSUE TITLE
Unable able to Parse subtitle file. Syntax error.

### ISSUE THREAD

**Issue by jenn-sung** [SubtitleEdit/subtitleedit#3676]
![Annotation 2019-07-26 093518](https://user-images.githubusercontent.com/26034676/61966253-746d1200-af8f-11e9-98bc-1378ad5c126a.png)

**Comment by niksedk** [comment]
Seems to be a problem related to video decoders... try installing lav-filters (use installer): https://github.com/Nevcairiel/LAVFilters/releases

Alternately you can switch the video player to mpv - see Options -> Settings -> Video playe
