### ISSUE TITLE
Waveform playback head slow

### ISSUE THREAD

**Issue by dvjrickkraft** [SubtitleEdit/subtitleedit#3677]
New user, working with Premiere (ugh) and making subs, love your program.  Problem- the playback head is really jumpy, looks like updating every 0.3 seconds or so.  Using the install version of VLC 3.0.7, FFmpeg installed through SubtitleEdit for wave extraction. Video playback buttery smooth, waveform interface not so much ;)  System spec: i9-9900K on MSI Tomahawk z390, 64GB ram at 2133mhz, NVMe 970EVO m.2 500GB and MSI GTX 1660 Ti.  Please let me know if I can assist in any testing!  -Rick

**Comment by OmrSi** [comment]
Use DirectShow or better yet, MPV.
DirectShow is smoother than MPV, but MPV is better for SE.

**Comment by niksedk** [comment]
Sorry, VLC simply just has un-precise seeking :(

**Comment by dvjrickkraft** [comment]
Perhaps MPV could be suggested by default, or suggested as the fastest?  As a new user, it's certainly not obvious.  After switching to MPV, playback was great!

**Comment by OmrSi** [comment]
It also makes it possible to choose the preview font and it supports ASS tags, it is the best for SE. 👌
