### ISSUE TITLE
Request for dark mode for user interface

### ISSUE THREAD

**Issue by dvjrickkraft** [SubtitleEdit/subtitleedit#3678]
Searched all the way through the interface for a dark theme and found there were none!  Would like to request this for a future update.  Staring at the interface for hours, dark is much easier on the eyes.  Thank you in advance!

**Comment by OmrSi** [comment]
It's there, but it's hidden because it's incomplete.
You can find it in the setting file:
`<UseDarkTheme>False</UseDarkTheme>`
As I said, it's incomplete and doesn't look good as @niksedk didn't finish working on it.

**Comment by dvjrickkraft** [comment]
Wow, cool!  I'll try that for now. Looking forward to this in the future!

**Comment by xylographe** [comment]
The most compatible way to open the location of the settings file,
1. Press **Win+R** to open the Run dialogue
2. Enter **`%APPDATA%\Subtitle Edit`** in the Run dialogue
3. Click **OK** to open the folder in Explorer

The settings file is named **`Settings.xml`**.

**Comment by niksedk** [comment]
This theme looks nice: https://github.com/SubtitleEdit/subtitleedit/issues/3960#issue-556943511

**Comment by dvjrickkraft** [comment]
I'd like to bump this, it's coming up to a year 😃 This is the only program we use for video production, really awesome, frame accurate results, too!  Thanks for your consideration!  
Rick Novlesky, Techspin

**Comment by evayor** [comment]
> It's there, but it's hidden because it's incomplete.
> You can find it in the settings file:
> `<UseDarkTheme>False</UseDarkTheme>`
> As I said, it's incomplete and doesn't look good as @niksedk didn't finish working on it.

Do you change then FALSE to TRUE? Because I did it and nothing changed in the interface. 
I just installed the penumbra theme from the 3960 feed and it looks nice, though I'm not sure how to set the background dark in SE itself.

**Comment by Splike** [comment]
Yes, a proper dark theme would really make the user experience a whole lot better.

**Comment by daveout** [comment]
A dark theme would be ~very~ nice indeed.

**Comment by lolawithl** [comment]
indeed  :eyes:

**Comment by niksedk** [comment]
It's very hard to make a nice dark theme with `Winforms` (the window framework SE uses), as some controls do not support this very well or at all.

We're are giving it a try in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
See Options - Settings - Font - Dark theme

And still, this Windows theme might work better for you: https://github.com/SubtitleEdit/subtitleedit/issues/3960#issue-556943511

**Comment by MuhammadiJK** [comment]
@niksedk Thank you so much.
This one seems to be the portable version. Do you have an installed version?

Please let me know how to enable List view/Source View options.

I've switched it to black and it's almost perfect) There are still white sections (Format, Encoding, etc.) but they are not a big deal.

Please let me know if there's a way to change the following colors:

- active selected text & background.
- inactive selected text & background.
- selected text and background in the text box.

If there isn't, can you add the option to choose the text & background colors (at least just the background color) of these sections?

Also, do you have a Payoneer account? Paypal doesn't work in my country.

![Subtitle Edit11b](https://user-images.githubusercontent.com/58576192/102694472-09d30b00-4243-11eb-8771-45b1d87bd249.jpg)

![Subtitle Edit10a](https://user-images.githubusercontent.com/58576192/102693991-10ac4e80-4240-11eb-840e-144eb19d05d4.jpg)

**Comment by OmrSi** [comment]
@MuhammadiJK This is still a work in progress. We'll do our best to improve it as much as possible.

I've fixed the "Format, Encoding" section, but it hasn't been merged yet:
![image](https://user-images.githubusercontent.com/20923700/102695084-da65d380-422d-11eb-954b-ef5bf3fdcc68.png)

>Please let me know how to enable List view/Source View options.

Right-click in the list view, then `Go to source view`, or you use the default shortcut `F2`, you can also change that from the settings:
![image](https://user-images.githubusercontent.com/20923700/102695119-0d0fcc00-422e-11eb-959c-26e9c3298616.png)

You can change `ListViewUnfocusedSelectedColor` from the settings file.

**Comment by OmrSi** [comment]
@MuhammadiJK 
>I've chosen dark theme & changed the Subtitle background color to black.
Your dark theme changes it back to brown. Please find attached the screenshots.

This is also fixed.

**Comment by OmrSi** [comment]
This is a question for everyone, do you the ListView looks better with or without the gridlines?

**Comment by MuhammadiJK** [comment]
What I mean is that in previous versions there's a list/source view option in the left top part.
How can I enable it in the Beta version?

I definitely don't need gridlines & lots of other grey lines.
It'll be the best if you'll make all lines black to make them invisible in black theme.

![Subtitle Edit12a](https://user-images.githubusercontent.com/58576192/102695947-8f0eed80-424c-11eb-9f53-5b621b7ee578.jpg)

**Comment by OmrSi** [comment]
>What I mean is that in previous versions there's a list/source view option in the left top part.
How can I enable it in the Beta version?

This is gone, you can only do it from the right-click menu or via shortcut.
It was causing issues with the dark theme.

**Comment by niksedk** [comment]
You can switch to source view via F2 (or right-click on choose `Go to source view`).
Omitting the tab control give a few extra lines - and the tab control don't look good with dark theme.

**Comment by MuhammadiJK** [comment]
All my function keys are the global keys performing other operations.

Having List/source view was a really useful feature.
It'll be great if you'll give an option to enable it in the settings, doesn't matter how it looks (as long as it's black) for those who need it.

**Comment by OmrSi** [comment]
It wasn't turning black. It was like this:
![image](https://user-images.githubusercontent.com/20923700/102696537-d8a10d80-4237-11eb-8ffd-7316bc7aafd7.png)

Also, the tab control is removed completely, so I think there can't be an option to activate it in the settings.

**Comment by daveout** [comment]
This is looking great. Much thanks everyone. 🙌😄

**Comment by OmrSi** [comment]
@niksedk Should be closed. :)

**Comment by BenjamimCS** [comment]
> The most compatible way to open the location of the settings file,
> 
> 1. Press **Win+R** to open the Run dialogue
> 2. Enter **`%APPDATA%\Subtitle Edit`** in the Run dialogue
> 3. Click **OK** to open the folder in Explorer
> 
> The settings file is named **`Settings.xml`**.

I changed it to True but in some parts it's still white.
![Imagem 3](https://user-images.githubusercontent.com/83431838/116624170-d5bcd480-a91d-11eb-9a38-914dd8e498ad.jpg)

**Comment by niksedk** [comment]
|I changed it to True but in some parts it's still white.

Try changing the settings via the UI - should be a little better...


In 3.6.0 it is in Options - Settings - Font - enable "Dark mode"

![image](https://user-images.githubusercontent.com/1261331/116650081-cb7ff200-a980-11eb-8c81-a5e4fa6fb9ec.png)


In 3.6.1 it will be Options - Settings - Appearance - enable "Dark mode"

![image](https://user-images.githubusercontent.com/1261331/116650168-f5391900-a980-11eb-8123-ccd249eac8a6.png)

**Comment by BenjamimCS** [comment]
> > I changed it to True but in some parts it's still white.
> 
> Try changing the settings via the UI - should be a little better...
> 
> In 3.6.0 it is in Options - Settings - Font - check `Use dark theme`
> 
> ![image](https://user-images.githubusercontent.com/1261331/116650081-cb7ff200-a980-11eb-8c81-a5e4fa6fb9ec.png)
> 
> In 3.6.1 it will be Options - Settings - Appearance - check `Use dark theme`
> 
> ![image](https://user-images.githubusercontent.com/1261331/116650168-f5391900-a980-11eb-8123-ccd249eac8a6.png)

Ow, man, thanks! So, the dark theme is now available, it is only "hidden".
