### ISSUE TITLE
Feature request: Show profile selection in toolbar

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3679]
Hi.
So, the profile thing is indeed very handy, but I still have to go into the options to change them every time. Would it be possible to add an option to select them from the toolbar, similarly to "show frame rate in toolbar"?

**Comment by niksedk** [comment]
It's now possible to change profile via a custom shortcut + the status bar will show (non "default") profiles...
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Looks great so far! Thanks!
