### ISSUE TITLE
Fix Bridge small gaps in durations

### ISSUE THREAD

**Issue by AlexandreMT** [SubtitleEdit/subtitleedit#3680]
![image](https://user-images.githubusercontent.com/25598649/62173345-1b450b80-b30c-11e9-91ab-5dbfac8bf281.png)

SE should not alert when gap duration is 1ms.

**Comment by niksedk** [comment]
Thx for reporting this :)

Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
