### ISSUE TITLE
Allow letters stuck to numbers for Arabic spellcheck

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3682]
We started this convo here https://github.com/SubtitleEdit/subtitleedit/commit/b9c87dc7f7e6859febd6c1d4dce2dffbb78db0b9
But didn't complete it.
In the end, you asked me for a regex, here it is: `^(?:و|\p{IsArabic}+ـ)\d+$`

EDIT: Maybe to allow decimals and thousands `^(?:و|\p{IsArabic}+ـ)\d+(?:[.,،]\d+)*$`

**Comment by niksedk** [comment]
Tried to fix it in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
How does that work?

**Comment by OmrSi** [comment]
![{4301EB4F-5597-4380-8854-775DEF1961AA} png](https://user-images.githubusercontent.com/20923700/64133407-8c318480-cdde-11e9-93ac-16f3c4999400.jpg)

**Comment by OmrSi** [comment]
We write normal numbers, not `'١', '٢', '٣', '٤', '٥', '٦'`

**Comment by OmrSi** [comment]
Working great now, thanks. :D
