### ISSUE TITLE
[Bug] ASS files changing time on their own in latest beta

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3683]
![Untitled Project](https://user-images.githubusercontent.com/20923700/62476685-2e465880-b7b0-11e9-8d58-04aa4425b6da.gif)

**Comment by niksedk** [comment]
Thx, that looks very annoying... beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip
Hopefully fixed now

**Comment by OmrSi** [comment]
Fixed. 👌
Thank you.
