### ISSUE TITLE
[Feature Request ] Use the mpv configuration file mpv.conf for subtitle display

### ISSUE THREAD

**Issue by Mattgrafiker** [SubtitleEdit/subtitleedit#3686]
Hello,
as many of us have mpv installed, not only in SE but also the mpv program itself. Would it be possible to use the mpv.conf to use inside SE (for subtitle display mostly, like color, size, border, etc)... with a path to the mpv.conf file like the libvlc player in the videoplayer option ?

mpv.conf is a simple text file with settings like this below :

## SUBTITLES ##
slang=fr,fra,fre,fra,French,eng,en,enUS,en-US,English
sub-pos=97
sub-font-size=50
sub-color="#FFffffff"
sub-border-size=1.5
sub-border-color="#FF000000"
sub-shadow-color="#000000"
sub-shadow-offset=1.5

Or is there already a way to do it ?

Thank you for your hard work.
Best subtitle software I have ever used so far !!!!

**Comment by OmrSi** [comment]
There isn't a way to do that exactly, but you can change those things from:
![{02340E11-88A3-4565-A377-DDB6FDF547F2} png](https://user-images.githubusercontent.com/20923700/62728383-576f1f00-ba24-11e9-8aa0-c70312de3a9b.jpg)

**Comment by Mattgrafiker** [comment]
Ah Ok. I didn't know the ASS/SSA tab could influence the aspect of the subtitles design within mpv preview. Thank you for the tip !!
