### ISSUE TITLE
Feature Request: Please make this available as an Appimage or Snap

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3705]
The current work arounds like Wine or Mono just do not provide a fully functional piece of software. Linux (Ubuntu) has made it so much easier to port Windows programs over, please.

**Comment by OmrSi** [comment]
Like this https://github.com/SubtitleEdit/subtitleedit/issues/3952?

**Comment by dausruddin** [comment]
I really hope this can be done. There is so much headache trying to run this on Linux.
