### ISSUE TITLE
The auto-translate sometimes not translating at all!

### ISSUE THREAD

**Issue by duiveldoder** [SubtitleEdit/subtitleedit#3708]
I reported this already I think. Sometimes a file just hangs and not translating anything at all. The whole file not being translated...

so I tried to get it down to the line(s) causing this and found out this:

Example line:
Anything on the shelves,<br />20% off.

Removing the % fixes it..

I tried this on other files that weren't translating as well..

Always the % causing this..

Probably related to: https://github.com/SubtitleEdit/subtitleedit/issues/401

**Comment by niksedk** [comment]
Could you attach a screenshot or two?

**Comment by niksedk** [comment]
Could you attach some screenshots?

**Comment by duiveldoder** [comment]
Hi Niksedk.

I couldn't report what you asked me because of course I continue my work and fix the error manually. 

So I could first report heads up on this, screenshot, AFTER I get the same error a 2nd time..

Which is today, but you already closed this problem.

Anyway, I'll try to attach a 'srt' file here which has this problem again.

I select translate from English to Russian and it just gives the blanks again.

I uploaded it as a zip because github doesn't allow the real file to be sent.

[Crime Busters (1977).eng.zip](https://github.com/SubtitleEdit/subtitleedit/files/3567574/Crime.Busters.1977.eng.zip)

Screenshots I can't make on this computer with this keyboard.. At least I don't know how as the "print screen" button doesn't exist here (logitech K780) but you can just open this file in subtitle edit -> auto-translate -> "English" to "Russian" and then click on translate... 

only empty lines as a result.

removing the two "%" and replace them with "percent" and it translates.

Sorry you had to close this issue. I hope you can forgive me for continuing my work and first being able to supply more information when I hit another file with this "error"

**Comment by LeonCheung** [comment]
@duiveldoder  I see this is an issue report. In case you need a workaround urgently, maybe a nice plugin can help (thanks to niksedk), see #3246. See my last post there to learn how to use it. Just trying to help a bit.

**Comment by niksedk** [comment]
thx for the subtitle file :)
Could you update the plugins (GT/BT screen-scraper) ?

**Comment by duiveldoder** [comment]
Yes, just did that. And found out how to make a screenshot on a K780:   fn-alt-del (for those who're interested)

![start](https://user-images.githubusercontent.com/15773876/64216657-54186780-ceec-11e9-8668-44e7b9e90a56.jpg)
![during](https://user-images.githubusercontent.com/15773876/64216659-5a0e4880-ceec-11e9-86d1-007cbe192840.jpg)
![end](https://user-images.githubusercontent.com/15773876/64216662-5d093900-ceec-11e9-9c40-88aa934f57a6.jpg)
![back](https://user-images.githubusercontent.com/15773876/64216666-60042980-ceec-11e9-8629-fa781be0d7ba.jpg)
![pluginversion](https://user-images.githubusercontent.com/15773876/64216668-64304700-ceec-11e9-97e1-0d0b489ff5e7.jpg)
![seversion](https://user-images.githubusercontent.com/15773876/64216671-6692a100-ceec-11e9-8d75-2b05380d985a.jpg)

**Comment by niksedk** [comment]
GT screen-scraper plugin updated... 
It was a bit hard to find the issue - translate.google.com does not accept % in the url...
