### ISSUE TITLE
Incomplete default filename for mkv-imported subtitle

### ISSUE THREAD

**Issue by jrjordao** [SubtitleEdit/subtitleedit#3716]
When saving a subtitle previously imported from a mkv file, the default filename omits the last dot-separated section of the original (mkv file) name.
a.mkv -> a.srt (OK)
a.b.mkv -> a.srt (NOK)
a.b.c.mkv -> a.b.srt (NOK)

This issue was introduced in version 3.5.10.

**Comment by niksedk** [comment]
Hm, it's somehow related to this Windows settings:
![image](https://user-images.githubusercontent.com/1261331/63635331-ce7df780-c661-11e9-9abe-e967d7f1133d.png)

Should hopefully be fixed in latest beta now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
Does it also work for you?

**Comment by jrjordao** [comment]
I have the "Hide extensions for know file types" option off (unchecked).

I also noticed that when opening the a.b.c.mkv file, SubtitleEdit's toolbar shows <path>\a.b.c , without extension. Not sure if that was the behaviour in previous versions... Maybe the real issue is at file opening and not later when saving the subtitle.

Unfortunately, the beta is presenting the same behaviour. :-(

**Comment by niksedk** [comment]
@jrjordao: Could you try to re-download latest beta - sometimes it's cached... 
Help -> About should say beta 25 or later...

**Comment by jrjordao** [comment]
![1](https://user-images.githubusercontent.com/46447023/63650742-fc3c6c80-c745-11e9-8c39-11a5e0fc25c4.png)

![2](https://user-images.githubusercontent.com/46447023/63650743-fc3c6c80-c745-11e9-9651-adf860d88a08.png)

![3](https://user-images.githubusercontent.com/46447023/63650744-fc3c6c80-c745-11e9-9ca1-960cb6e1f39e.png)

![4](https://user-images.githubusercontent.com/46447023/63650745-fc3c6c80-c745-11e9-8f6e-e478d0254ba4.png)

**Comment by jrjordao** [comment]
In version 3.5.9

![3a](https://user-images.githubusercontent.com/46447023/63650848-f8f5b080-c746-11e9-9d3a-56b733bdb1e2.png)

![4a](https://user-images.githubusercontent.com/46447023/63650849-f8f5b080-c746-11e9-9d33-0e434dbe6c92.png)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

I still wonder why I cannot re-create this... have you changed other "Folder options" than "hide known extensions"?

**Comment by jrjordao** [comment]
It's working now! :-D

Repeated the test with 3.5.9, 3.5.10 (official) and 3.5.10 beta 26, just to make sure.

Incidentaly, this beta also fixes one apparently related minor issue I just detected now on 3.5.9. After correctly providing "a.b.c.srt" as default subtitle filename imported from "a.b.c.mkv", after saving the subtitle on disk, the titlebar switched from "[path]\a.b.c.srt" to "[path]\a.b.c" (it lost the extension). That no longer happens in this beta 26.
