### ISSUE TITLE
Helpful shortcut

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#3719]
There so many helpful shortcuts in SE, is it possible to add one that adjusts char/sec in the current subtitle to the one set in the rules. That would be very helpful indeed.

PS. You could add the same option in the right click menu on the waveform/spectrogram or as a standalone button in the "Adjust" panel.

**Comment by niksedk** [comment]
Try the `Re-calculate` shortcut:
![image](https://user-images.githubusercontent.com/1261331/63638335-2a0eac00-c687-11e9-8851-7b2e7894de6e.png)
