### ISSUE TITLE
Error with characters "<" and ">" as they are sometimes interpreted as "&lt;" and sometimes not.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#3721]
I am using a .vtt subtitle and the the characters "<" and ">" are strangely interpreted. There is trouble only with the spell check because when I save the file, they go back to normal.
![Untitled](https://user-images.githubusercontent.com/37704802/63636942-46521f00-c66e-11e9-8cf9-42008b8ec3bd.png)

**Comment by niksedk** [comment]
Could you attach or email the subtitle?

**Comment by lambdacore12** [comment]
Gladly.

[httpsFR_2585_08_02_XR30Rmp4.fr.zip](https://github.com/SubtitleEdit/subtitleedit/files/3537267/httpsFR_2585_08_02_XR30Rmp4.fr.zip)

**Comment by niksedk** [comment]
LOL, I had to look a few times - code in the subtitles... but it's a code tutorial ;)

Looking at the spec ( https://www.w3.org/TR/2014/WD-webvtt1-20141111/#dfn-webvtt-cue-text ) it seems that `<>&` must be escaped.... do you agree @xylographe  @ivandrofly  ?
