### ISSUE TITLE
Batch Convert Function Failure

### ISSUE THREAD

**Issue by Jack1789** [SubtitleEdit/subtitleedit#3723]
Hello, while trying to convert some SubRip subtitles to BD Sup format, I realized the conversion process ends up quite faster than it usually does, but the converted files are corrupted/unusable. I get this error message right after trying to open one of them:

![subt](https://user-images.githubusercontent.com/54497604/63648693-d2fdeb00-c709-11e9-81f6-6c38c21bc00a.jpg)

Contrarily, converting the subtitles individually works fine.

Thanks.

**Comment by niksedk** [comment]
Several fixes regarding "Batch convert" has been made since the release... could you try latest beta? 
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by Jack1789** [comment]
It's working fine again with latest beta, thanks.

**Comment by niksedk** [comment]
thx for verifying :)
