### ISSUE TITLE
[Feature Request] Little Sized Buttons' Improvement

### ISSUE THREAD

**Issue by Jack1789** [SubtitleEdit/subtitleedit#3725]
Hi, I usually have to deal with subtitles' having incorrect duration and/or start times, and therefore have to make a great use of the relevant arrows buttons; the thing is, they are way too tiny how to work in a comfortable way. That in the sense of always having to "aim" exactly on them, so to avoid casual misses. 

Would it be possible to make those arrows bigger? Maybe in an optional way, for those who already like it that way.

Thanks.

**Comment by Jack1789** [comment]
I forgot to mention it, but for what it's worth, I'm certainly not going nearsighted neither something like that; I actually see those buttons, but the thing is, they are too near each other besides being tiny, so clicking wrongly it around the corner. :)

**Comment by darnn** [comment]
This doesn't really solve your problem, but have you considered using the arrow keys, instead of pressing on the buttons? It works for me. Personally I don't use the buttons at all because it's rare to have to adjust the values manually. Either I sync things myself, and then change the values with set start time/set end time, or timing for the whole file needs to be shifted forward, in which case I use set start and offset the rest, etc.

**Comment by Jack1789** [comment]
Thanks for the suggestion, but in my case it would be quite tedious/impractical have to do the duration's related corrections with the arrow keys; it will take more time as well.

I forgot to mention it, but the same issue occurs (although less noticeably) in other synchronization related tasks, were those little buttons are present, like in "Point sync...", "Fix common errors...", etc.

I use those buttons with %99 the subtitles I edit, since most of them have timing's issues. Basically, I first make sure they have the correct frame rate; after that, I run them through the "Fix common errors..." task; next, I use the "Split long lines..." function; then I manually adjust the incorrect duration times and/or overlaps for each problematic line/s. This last step is probably the most tedious one (just behind mismatching frame rates), moreover when there are many lines involved, but I doubt it can be done automatically.

Just a little sample:

https://streamable.com/sapxc

Sometimes there are just a few wrong duration times, sometimes a bunch of them, but even in untouched, official DVD/BD subtitles they are present; I don't admit anything below 1 second, even if it's just a monosyllabic word.

**Comment by darnn** [comment]
Hmm. Well, if you do use the buttons that extensively, I do understand the desire for them to be bigger.

Unlrelated to that, though, I still don't quite understand what you're doing. In the video you linked, the first thing you do is extend the length of the 43rd subtitle. Based on what? And how are you then determining that you should shift the next subtitle forward, etc.?

**Comment by Jack1789** [comment]
Well, I'm certainly not trying to get rid of all the problems the subtitles' I usually edit have. I mean, since in all cases they target a determined content I still didn't watch, doing it from scratch, in a thorough way, would suppose spoilers all around; besides it taking ages.

After adjusting several subtitles according to the default "subtitle edit" rules, I found in most cases they were good enough how to properly fix most errors, mostly time related ones. So, once I reach the point a determined subtitle has only short duration's problems, which can't be automatically fixed, I take the time to fix each problematic line by arbitrarily adding/substracting a few hundreds milliseconds, till they meet the rules' criteria (nothing below 1 sec, no overlaps, etc.). 

I know this isn't by any means the proper way of fixing a subtitle, but as I mentioned before, that's not the real intention. And despite not giving them a perfect synchronization and being it's still a time consuming and annoying task, it turns them into a "watchable" condition, which is my ultimate goal.

**Comment by darnn** [comment]
Ah. Well, in that case, I guess all I can say is good luck!

**Comment by Jack1789** [comment]
Well, I see it took the developer more than a year to even look at this and just close it; without even a comment. That's certainly encouraging when it comes to keep giving suggestions and/or feature requests.
