### ISSUE TITLE
[Suggestion] Replace VLC with FFMPEG for waveform extraction or use both.

### ISSUE THREAD

**Issue by adelinn** [SubtitleEdit/subtitleedit#3726]
Would it be better if you would replace VLC with FFMPEG for waveform extraction?
I've faced an issue with waveform extraction a short time ago... and I had to use ffmpeg to extract the the audio as "wav" file and then to load it into SubtitleEdit.
Could you do that automatically to avoid this issue?

**Comment by niksedk** [comment]
Check Options -> Waveform :)
![image](https://user-images.githubusercontent.com/1261331/63664733-4e25d680-c7c8-11e9-9b49-5e306f416471.png)
