### ISSUE TITLE
Can't change speed

### ISSUE THREAD

**Issue by MirellaVinc** [SubtitleEdit/subtitleedit#3728]
I can't change the speed. This error:

Windows Forms Thread Exception

‘An application error occurred in Subtitle Edit 3.5.10.0,
Please report at
https:/aithub.com/SubttleEdit/subtitleedit/issues with the
following information:

Error Message!
Значение не попадает в ожидаемый диапазон.

Stack Trace!
‘Quartztypelib.< e6a6t1de-2209-46a3-a5¢7-6c6ffS8456e5>Medi
aPosition.set Rate(Double pdRate)
Nikse.Subtitle€dit.Logic.VideoPlayers. QuartsPlayer.set_PlayRat
e(Double value)

' Nikse,Subtitle€dit.Forms.Main.SetPlayRate(Object sender,
EventArgs e, Boolean skipStatusMessage)

15 System. Windows.Forms.ToolStripitem RaiseEvent(Object
key, Eventargs e)
system.Windows.Forms.TooIStripMenultem.OnClick(EventAras
3
system.Windows.Forms.TooIStripitem.HandleClick(EventArgs )
system.Windows.Forms.TooIStripitem.HandleMouseUpiMouse
Eventargs e)
system,Windows.Forms.TooIStrip.OnMouseUp(MouseEventAr
‘9s mea)
System.Windows.Forms.TooIStripDropDown.OnMouseUpiMo
useBventArgs mea)

' System,Windows.Forms.Control.WmMouseUp(Message&
mm, MouseButtons button, Int32 clicks)

' System,Windows.Forms,Control,WndProc(Messageg m)

#5 System.Windows.Forms.ToolStrip. WndProc(Message& m)
system.Windows.Forms.TooIStripDropDown.WndProciMessag
e& m)

' System, Windows Forms.NativeWindow.Callback(intPtr
hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)
.

**Comment by niksedk** [comment]
You could try to install latest version of LAV filters (use the installer): https://github.com/Nevcairiel/LAVFilters/releases

Or switch to mpv player which is much better at speed change (no sound distortion)

**Comment by MirellaVinc** [comment]
Thank you. MPV is much better)))


С уважением, ваш руководитель группы
Шиганова Мария

**Comment by MirellaVinc** [comment]
Nikolaj, hello again.

I have one more question. 

In the Settings-General we have Max. words/min. I set up 235 words/min. But when I write more than 235 the programm doesn't highlight in red this mistake. Only in waveform I can control words/min.

Is it possible to change this option. It could be more comfortable if this mistake was higlighted.

Sorry for my English

Thank you

Maria

**Comment by niksedk** [comment]
You can right-click on the list view column header, and show the column "words/min"

**Comment by MirellaVinc** [comment]
Thanks. I know this function. 

But it could be more comfortable if subtitle was higlited in red, such as symbols in seconds or length of subtitle, for example.

It's my wish. 

If it's possible to realize this option it could be much better. 

Now we always have to control  amount of words. Highlighting could have facilitated our work.

We are waiting for new updates. Thank you.   

Best regards, Maria

**Comment by MirellaVinc** [comment]
Thank you. I understand now))) I'm sorry to trouble you)


Четверг, 29 августа 2019, 15:35 +03:00 от Nikolaj Olsson <notifications@github.com>:
