### ISSUE TITLE
Ocr not setting italics properly

### ISSUE THREAD

**Issue by teodargent** [SubtitleEdit/subtitleedit#3729]
![Annotazione 2019-08-26 231259](https://user-images.githubusercontent.com/20757457/63724928-47936f80-c859-11e9-878f-414e67438efa.png)

It looks like the ocr engine recognizes the word in italics correctly in this example but it does not set it accordingly.

[Gravity- Special Edition_t01_track11_[ita].zip](https://github.com/SubtitleEdit/subtitleedit/files/3543181/Gravity-.Special.Edition_t01_track11_.ita.zip)

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip ?

**Comment by teodargent** [comment]
> How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip ?

This works but there is another issue:
![Annotazione 2019-08-28 025702](https://user-images.githubusercontent.com/20757457/63818114-af23ea80-c93f-11e9-8b62-f743c2cf57f4.png)

It removed the dash (-) in front of "Explorer".

**Comment by teodargent** [comment]
Also this:

![Annotazione 2019-08-28 030511](https://user-images.githubusercontent.com/20757457/63818339-d4652880-c940-11e9-9447-1cdc6e35a8b2.png)

**Comment by niksedk** [comment]
Thx for testing :)
Could you re-test the beta below?
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by teodargent** [comment]
> Thx for testing :)
> Could you re-test the beta below?
> Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

Now it works fine 👍

**Comment by teodargent** [comment]
![Annotazione 2019-09-09 222758](https://user-images.githubusercontent.com/20757457/64564354-a8d73a80-d351-11e9-9069-8d16102d4f1b.png)

Is this fixable?

**Comment by teodargent** [comment]
![Annotazione 2019-09-15 111907](https://user-images.githubusercontent.com/20757457/64919441-fec13d80-d7aa-11e9-8387-7800accbbc34.png)

@niksedk
