### ISSUE TITLE
OCR - binary image compare issues with apostrophes, quotes and the letter י

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3731]
Latest beta (3.5.10 46), though I believe this hasn't been introduced recently.
When I attempt to perform OCR on a Hebrew subtitle using binary image compare, SE has issues distinguishing between apostrophes, quotation marks and the Hebrew letter Yod (י), even with max error% set to 0.1.
Here are some of the errors:
![se-acc01](https://user-images.githubusercontent.com/19672444/63945096-74bf6800-ca7b-11e9-9ff5-72eee9c31f2f.png)
‫‎`רוחו של מארל"'`‎
should read
‫‎`רוחו של מארלי"`‎

![se-acc02](https://user-images.githubusercontent.com/19672444/63945471-0a5af780-ca7c-11e9-982f-af8857394a53.png)
מת כמו גוו"ה
should reald
מת כמו גווייה

![se-acc03](https://user-images.githubusercontent.com/19672444/63945585-3c6c5980-ca7c-11e9-9450-27cf1fb638e3.png)
ג"יקוב מארלי
should read
ג'ייקוב מארלי

![se-acc04](https://user-images.githubusercontent.com/19672444/63945680-6c1b6180-ca7c-11e9-8aca-194a6705b9ba.png)
קרצ"ט
should read
קרצ'יט

I'm attaching the subtitle itself as well as its complete OCR db file:
[acc.zip](https://github.com/SubtitleEdit/subtitleedit/files/3555831/acc.zip)

**Comment by gru123** [comment]
Set max error% to 0.0, and problem solved.
If max error% differs from 0.0, then SE can't distinguish many pairs of letters and characters, e.g. "O" and "Q" - that's why I always set max% to 0.0.
I know it's annoying, but that's how it is.

**Comment by darnn** [comment]
This happens with the new nOCR method as well, by the way.

**Comment by niksedk** [comment]
@darnn: Hm, this is what I get... does it look right?
![image](https://user-images.githubusercontent.com/1261331/84591499-33981900-ae3f-11ea-88c9-e6a997c142d0.png)

**Comment by darnn** [comment]
Still not quite. Note the differences here:
![se-ocr-apostrophe01](https://user-images.githubusercontent.com/19672444/84591684-1c5e2900-ae49-11ea-8c8c-f7598759c656.png)
![se-ocr-apostrophe02](https://user-images.githubusercontent.com/19672444/84591687-208a4680-ae49-11ea-9e32-60c9d1258dbf.png)

And in nOCR it doesn't differentiate between the apostrophe and the letter י at all, even though they're at different heights.

**Comment by niksedk** [comment]
You can double click in the list view (OCR window) on trouble-some lines (will start "inspect" window).
You can e.g. delete the wrong character (probably best here) or  change the text and click "Add better match" / "Update".

![image](https://user-images.githubusercontent.com/1261331/84591855-f4b79280-ae41-11ea-902f-5c9aba0be99c.png)

**Comment by darnn** [comment]
Oh, I didn't know that. That does help. But is there any way of preventing this from happening to begin with? Because if I start with a new image database, the character in that screenshot gets recognized the same way again.
