### ISSUE TITLE
[Bug] SE Fix Common Errors - LOS, L.A. issues

### ISSUE THREAD

**Issue by Araynilmar** [SubtitleEdit/subtitleedit#3733]
### SE Version
v3.5.10 64bit

### Issues
![img_url](https://res.cloudinary.com/aray/image/upload/v1567198430/Screenshots/SE_Fix_Common_Errors_-_LOS_L.A..png)

Example:
LOS ANGELES police say the incident was not racially motivated
LOS ANGELES -> IOS ANGELES -> iOS ANGELES

Example:
L.A. should go back to L.A.
L.A. -> I.A.

**Comment by niksedk** [comment]
Could you try a clean install? (e.g. the portable version)

**Comment by Araynilmar** [comment]
> Could you try a clean install? (e.g. the portable version)
> Edit: OK, it does that here as well... will look at it asap.

I am a clean reinstall, not just overlay.

**Comment by niksedk** [comment]
Could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip ?
The bug should hopefully be fixed now.

**Comment by Araynilmar** [comment]
> Could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip ?
> The bug should hopefully be fixed now.

Thx, I'm grateful for your help.

**Comment by niksedk** [comment]
np, and thx for reporting this :)
