### ISSUE TITLE
timestamp issue with WebVTT-files

### ISSUE THREAD

**Issue by laurensscheers** [SubtitleEdit/subtitleedit#3736]
Since version 3.5.10, every time I open a webVTT-file, the end time of each line is increased by a few milliseconds and sometimes even by a few seconds. This only happens when the second line of the file is a time stamp, something like:
`X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000`

Some examples (see [example files.zip](https://github.com/SubtitleEdit/subtitleedit/files/3562348/example.files.zip)):

- When I import this file ("imported 1.vtt")...

```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000

00:00:16.360 --> 00:00:20.840
00:00:20.920 --> 00:00:24.320
00:00:24.800 --> 00:00:27.160
00:00:28.600 --> 00:00:31.120
00:00:31.200 --> 00:00:33.880
00:00:33.960 --> 00:00:34.960
00:00:35.040 --> 00:00:38.560
00:00:38.640 --> 00:00:42.360
00:00:42.440 --> 00:00:46.880
00:00:47.600 --> 00:00:51.160
00:00:51.240 --> 00:00:54.520
00:00:54.600 --> 00:00:56.880
00:00:56.960 --> 00:00:59.160
00:00:59.240 --> 00:01:03.800
```

- ... is this result when I export it ("exported 1.vtt"). The time between parentheses after each line is the difference with the original:

```
WEBVTT

00:00:16.360 --> 00:00:20.896 (+00:00:00.056)
00:00:20.920 --> 00:00:24.776 (+00:00:00.456)
00:00:24.800 --> 00:00:28.576 (+00:00:01.416)
00:00:28.600 --> 00:00:31.176 (+00:00:00.056)
00:00:31.200 --> 00:00:33.936 (+00:00:00.056)
00:00:33.960 --> 00:00:35.016 (+00:00:00.056)
00:00:35.040 --> 00:00:38.616 (+00:00:00.056)
00:00:38.640 --> 00:00:42.416 (+00:00:00.056)
00:00:42.440 --> 00:00:47.576 (+00:00:00.696)
00:00:47.600 --> 00:00:51.216 (+00:00:00.056)
00:00:51.240 --> 00:00:54.576 (+00:00:00.056)
00:00:54.600 --> 00:00:56.936 (+00:00:00.056)
00:00:56.960 --> 00:00:59.216 (+00:00:00.056)
00:00:59.240 --> 00:01:13.800 (+00:00:10.000)
```

Another example:

- "imported 2.vtt":

```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:6300000,LOCAL:00:01:00.000

00:01:05.120 --> 00:01:08.360
00:01:08.760 --> 00:01:13.160
00:01:13.240 --> 00:01:16.280
00:01:16.360 --> 00:01:18.400
00:01:18.480 --> 00:01:21.480
00:01:21.560 --> 00:01:24.920
00:01:25.000 --> 00:01:27.000
00:01:27.080 --> 00:01:28.960
00:01:29.560 --> 00:01:32.720
00:01:32.800 --> 00:01:34.200
00:01:34.280 --> 00:01:35.800
00:01:35.880 --> 00:01:40.000
00:01:41.120 --> 00:01:45.560
00:01:45.640 --> 00:01:49.400
00:01:49.480 --> 00:01:50.680
00:01:52.440 --> 00:01:55.880
00:01:55.960 --> 00:01:59.360
00:01:59.440 --> 00:02:02.760
```

- "exported 2.vtt":

```
WEBVTT

00:01:05.120 --> 00:01:08.736 (+00:00:00.376)
00:01:08.760 --> 00:01:13.216 (+00:00:00.056)
00:01:13.240 --> 00:01:16.336 (+00:00:00.056)
00:01:16.360 --> 00:01:18.456 (+00:00:00.056)
00:01:18.480 --> 00:01:21.536 (+00:00:00.056)
00:01:21.560 --> 00:01:24.976 (+00:00:00.056)
00:01:25.000 --> 00:01:27.056 (+00:00:00.056)
00:01:27.080 --> 00:01:29.536 (+00:00:00.576)
00:01:29.560 --> 00:01:32.776 (+00:00:00.056)
00:01:32.800 --> 00:01:34.256 (+00:00:00.056)
00:01:34.280 --> 00:01:35.856 (+00:00:00.056)
00:01:35.880 --> 00:01:41.096 (+00:00:01.096)
00:01:41.120 --> 00:01:45.616 (+00:00:00.056)
00:01:45.640 --> 00:01:49.456 (+00:00:00.056)
00:01:49.480 --> 00:01:52.416 (+00:00:01.736)
00:01:52.440 --> 00:01:55.936 (+00:00:00.056)
00:01:55.960 --> 00:01:59.416 (+00:00:00.056)
00:01:59.440 --> 00:02:12.760 (+00:00:10.000)
```

So usually the end time is increased by 56 milliseconds, but sometimes also by a couple seconds.
When I delete the timestamp, no time shift occurs. So actually this is not really an issue, I'm just wondering why this happens and if I can use it practically in the future.

**Comment by niksedk** [comment]
I tried to add support for the `X-TIMESTAMP-MAP` header in 3.5.10 - but it does not seem to work too well... so now an updated beta is out: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

The `MPEGTS` part add time (divided by 90000=secs) and the `LOCAL` part is subtracted: See https://bitmovin.com/docs/player/faqs/why-are-my-webvtt-subtitle-tracks-not-in-sync-with-the-video

SE now has a secret setting (in Settings.xml) called `WebVttUseXTimestampMap` that can disable using the header.

(and thx for a well written issue)

**Comment by laurensscheers** [comment]
This works great! 

I don't know if it's common, but usually when I download webVTT files from a VOD site, they are all just 1 minute long and the start and end times are relative to 00:00:00. 
So until now I had to use a script to add a certain amount of minutes to the start and end time of each line (1 minute for the second file, 2 minutes for the third file etc.). 
Afterwards I merged them into 1 file with SE. With this fix I can make my script a lot easier. 
Thank you very much for the effort @niksedk . 

So the only thing that is still missing in my script (and what I have to do manually), is the merging of the vtt-files. Do you think it is possible to add this as a command line option? Something like: 
`SubtitleEdit /join /convert *.vtt subrip`. 
And if so, shall I open a feature request for this?

**Comment by FUXIANGEN** [comment]
new timestamp issue
[https://s4.aconvert.com/convert/p3r68-cdx67/b7c5w-1qzxs.jpg](url)
