### ISSUE TITLE
Why can't i import subtitles from mkv files anymore.

### ISSUE THREAD

**Issue by ljdssdgOjosdgOsd** [SubtitleEdit/subtitleedit#3738]
I tried to import subtitles when I get an error message and I get a long list of issues I don't understand.
It first says 

Error Message: There is a non-legitimate sign in the given code. Row 10, position 12.
And then a bunch of stuff I don't understand and I don't know how to upload a screenshot but hopefully, you understand what the fix is based on the first line.

**Comment by niksedk** [comment]
What version of SE are you using?
What OS?
A screenshot would be very nice too (just press PrtScr and paste here)
The mkv file would also be nice to take a look at.

**Comment by ljdssdgOjosdgOsd** [comment]
How do i post a screenshot but i don't know how.
Im using the most recent version on the site.
How would you look at the file?

**Comment by niksedk** [comment]
You can email the mkv file to me it's below 25 mb (mkvtoolnix can remove video/audio tracks) or you could use a file share service.

Screnshot - actually presss ctrl+c when you get the messagebox - and press ctrl+v in the text box here...

**Comment by ljdssdgOjosdgOsd** [comment]
![Å](https://user-images.githubusercontent.com/54765920/64134296-f6e1c080-cddc-11e9-8e1c-8146ffc21668.png)
What's your email?
