### ISSUE TITLE
Error in replacing music symbols

### ISSUE THREAD

**Issue by paolovador** [SubtitleEdit/subtitleedit#3739]
Hello,

I've got an error when trying to replace music symbols on SE 3.5.10.

I didn't found where the logs were so here's a picture of the stacktrace.
![image](https://user-images.githubusercontent.com/6412153/64078185-fce57d80-ccc6-11e9-8782-3e3427c9f904.png)

Corresponding SRT.
[Asterix & Obelix Mission Cleopatra 2002.fr.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/3563609/Asterix.Obelix.Mission.Cleopatra.2002.fr.srt.zip)

Thanks for this great software !

**Comment by niksedk** [comment]
Thx for reporting this :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
