### ISSUE TITLE
[Feature Request] make two separate blocks a dialog in PGS

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#3741]
When two people talk in a scene, the two sub blocks are sometimes placed separately and accordingly to the position of speakers in PGS.
In these cases, each sub does not have a hyphen, which is needed when merging into one sub block.
Right now, I check all the lines and add necessary hyphens once OCR is done.
Can it be done automatically?

**Comment by RedRain77** [comment]
Is there any update on this?
I've run into this issue recently myself when SE runs into a part with multiple pieces of dialogue at the same time it just combines them all into a jumble at the bottom.
