### ISSUE TITLE
OCR Bug

### ISSUE THREAD

**Issue by NoYBMe** [SubtitleEdit/subtitleedit#3742]
When working with the last two betas **v3.5.10.55** and **v3.5.10.61** on idx, sup, VobSub or PGS files with the OCR in either Tesseract 3.02 or 4.1.0 ALL two line subtitles are joined at the **LAST** word of the **FIRST** line and the **FIRST** word of the **SECOND** line, for example:

"That is what's left of New York City
after the military fired the weapon"

Gives "Word not found" as "Cityafter"

This was not happening with the 3.5.10 release. Prior betas to 3.5.55 not 100% sure but not that I noticed though. I have tested on a fresh installation with the same results.

Screen-cap examples below:

![Untitled-1](https://user-images.githubusercontent.com/54785488/64086400-ef42ee80-ccec-11e9-9bd4-8e495b80e3d1.png)
![Untitled-2](https://user-images.githubusercontent.com/54785488/64086412-0386eb80-cced-11e9-9aa9-af3da9efd12a.png)
![Untitled-3](https://user-images.githubusercontent.com/54785488/64086956-c96b1900-ccef-11e9-9636-e1442eb944f8.png)

**Comment by NoYBMe** [comment]
You're welcome, glad to help.

Thank you for your work and promptness to this issue.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
Please re-test :)

**Comment by NoYBMe** [comment]
Preliminary testing shows OCR (Tesseract 302/410) is behaving as expected.

The bug seems fixed.

If anything turns up, after I do more thorough testing, I will report it.

Again, thank you for your time and work on this project.

**Comment by NoYBMe** [comment]
The original bug reported, after further testing, remains fixed.

However, there are a couple of things I found while testing;

1. OCR with Tesseract 302/410 is automatically translating [♪♪♪] as [NI] from an idx/sup.

The settings when this happens are:
- "Fix OCR errors" CHECKED.
- "Prompt for unknown words" CHECKED.
- "Try to guess unknown words" is UNCHECKED.
- "Auto break paragraph if more than two lines" CHECKED.

This automatic OCR change does NOT prompt or show under:
- "Unknown words"
- "All Fixes"
- "Guesses used"

It just inserts [NI] in place of [♪♪♪].

I obviously have no program screen-cap for this, but I can send you the idx/sup file (5MB) if you 
want it.

2. OCR with Tesseract 302/410 and same settings as above will randomly and rarely skip the first line of a two line subtitle.

I'm almost certain I read about this before, I tried quick searching Google, Github, VideoHelp, Doom9, etc but could not find anything. Therefore, I'm bringing it to your attention.

For example:

- Go.
- Thanks.

Will read:

- Thanks.

Screen-cap below:
![image](https://user-images.githubusercontent.com/54785488/64245268-73e56680-cebf-11e9-96ae-094cf8e77608.png)
