### ISSUE TITLE
issue with downloading dictionaries used in spellcheck

### ISSUE THREAD

**Issue by lmorera** [SubtitleEdit/subtitleedit#3747]
The program doesn't download dictionaries used in spellcheck
![photo_2019-09-04_11-09-47](https://user-images.githubusercontent.com/54908014/64278569-09faaa80-cf1b-11e9-8e58-f15b8ab9dd05.jpg)
![photo_2019-09-04_11-12-08](https://user-images.githubusercontent.com/54908014/64278570-09faaa80-cf1b-11e9-90e7-acd577ed2317.jpg)

**Comment by niksedk** [comment]
Does the problem also occur with latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
