### ISSUE TITLE
[Bug] Blu-Ray Subtitle Imported Incorrectly

### ISSUE THREAD

**Issue by Jack1789** [SubtitleEdit/subtitleedit#3748]
Hello, I wanted to get the time codes from a PGS subtitle file present into a M2TS container, but the program loads it as if it were a VOBSUB DVD's subtitle. Times gets kind of scrambled, with many lines having wrong duration lengths, like this:

![subs](https://user-images.githubusercontent.com/54497604/64309181-1fe78a00-cf72-11e9-9599-dda43c81624c.jpg)

I have extracted the PGS subtitle with a third-party tool, and it looks fine:

![subs-ok](https://user-images.githubusercontent.com/54497604/64309237-4b6a7480-cf72-11e9-884d-aaae51bb5d6f.jpg)

The aforementioned M2TS file weights ~23 GB, but tell me in case you need it.

Thanks.

**Comment by niksedk** [comment]
@Jack1789: Could you split it and send a smaller part, like 100 mb?
I've a slow internet connection and less that 15 GB free space in my current pc :(

**Comment by Jack1789** [comment]
I already sent you a ~100 MB sample, with the title "PGS-Handled-As-VOBSUB".

**Comment by niksedk** [comment]
The for the file... I finally has some time to look at it - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
