### ISSUE TITLE
[Minor] Changing profile from status bar doesn't work well when showing progress

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3750]
When `ShowProgress` is activated, you have to click on the subtitle number to change the profile:
![{513EC08C-6A1D-454B-AC99-4DABBCAB4682} png](https://user-images.githubusercontent.com/20923700/64461124-f6ab3300-d104-11e9-8f9c-ade8522363a7.jpg)

**Comment by niksedk** [comment]
How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Perfect. :D
Thank you!
