### ISSUE TITLE
Issue with name of English (GB) dictionary files

### ISSUE THREAD

**Issue by AbsenceJam** [SubtitleEdit/subtitleedit#3754]
3.5.10

I noticed I could not select en-GB for OCR auto correction / spell checking (it was fine for regular spellchecking), it would switch to en_US. Other English locales were okay.

I saw that there was a dash rather than an underscore in the name en_AU, en-GB, en_US, etc.

Renaming en-GB.aff & en-GB.dic to en_GB.aff & en_GB.dic resolved the problem.

**Comment by niksedk** [comment]
thx for the info - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
