### ISSUE TITLE
Invalid character in row 10, position 12

### ISSUE THREAD

**Issue by ljdssdgOjosdgOsd** [SubtitleEdit/subtitleedit#3755]
I'm trying to extract Swedish subtitles and when I'm trying to apply Swedish dictionary it says: "Invalid character in row 10, position 12" Can someone help me with the code so I can continue?

**Comment by niksedk** [comment]
Could you attach the subtitle giving this problem?

**Comment by ljdssdgOjosdgOsd** [comment]
it's an mkv file that I want to extract subtitles from. I'm pressing extract from mkv and it will give me the error message.
![q](https://user-images.githubusercontent.com/54765920/64706997-a809ea00-d4b2-11e9-8fee-27c3f01a8010.png)

**Comment by niksedk** [comment]
OK, try to uninstall - be sure to delete all files and then do a re-install.
One of the dictionary files seem to be corrupt.

**Comment by ljdssdgOjosdgOsd** [comment]
Where do I find the dictionaries?

**Comment by xylographe** [comment]
`%APPDATA%\Subtitle Edit\Dictionaries`
