### ISSUE TITLE
[Feature request] Make OCR-scanning work in background while going over single lines

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#3756]
Hello

I have been thinking about something. An OCR scan of an MKV takes quite a while because it is a single process. So if the file has a 1000 subtitles line it start from the beginning and then prompts for unknown words (if that option is ticked) when it finds one. 

If the entire OCR scanning process worked in the background and continued while the user was prompted, then that would speed up the entire thing considerably.

I hope my suggestion makes sense.

Btw, I think the software is brilliant either way. It is just a suggestion :-)

**Comment by Maitch** [comment]
It does not seem like it does it. 

It prompts me and stop the scanning and then resumes the scanning when I have chosen something from the dialogue box.

**Comment by Maitch** [comment]
I just did a test, ripping a tv episode.

I started OCR scan and it stopped on subtitle #3 out of 321 subtitles in total. Then I waited 10 minutes to repond to the prompt. 
When I reacted to the prompt, the OCR scanning just resumed. If it had ran it the background, it should have been done in the 10 minutes I have waited.

**Comment by 1024mb** [comment]
I seconds this, would be great if the OCR keeps going while SE waits for user input on unrecognized words instead of pausing the OCR until one inputs the correct text.

**Comment by Asinin3** [comment]
Yeah this has been the biggest issue with SE for me, pausing all the time really slows down the process. Simply turning off "prompt on unknown words" then spell-checking after isn't really an option either because you lose some functionality once you're back at the main window with the OCR finished e.g you can't see the lines in yellow that it wasn't sure about

**Comment by xylographe** [comment]
https://github.com/SubtitleEdit/subtitleedit/blob/b9310aed16a5312a9b4d86cd94b26b51b4067728/src/Forms/Ocr/VobSubOcr.cs#L5091

**Comment by Asinin3** [comment]
Any updates on this?
