### ISSUE TITLE
Importing JSON files

### ISSUE THREAD

**Issue by jaccoud** [SubtitleEdit/subtitleedit#3757]
When I saw JSON between the file types supported I thought SE would identify and try to import the files generated by Amaxon Transcribe, a AWS service which is very useful to provide a starting point for the transcription process. A always get an error though. The JSON file produced by transcribe is not dificult to parse, and would be of great value to get this working in SE.

**Comment by jaccoud** [comment]
Yes, I attached a zip
[aws-transcribe-samples.zip](https://github.com/SubtitleEdit/subtitleedit/files/3610506/aws-transcribe-samples.zip)
 archive with 3 JSON outputs for different tests I made at Amazon Transcribe. All are in Portuguese, but that should not matter. educacao.json resulted from a video with a single speaker, hackaton.json from another with two, and pre-sal with six. You will verify that the speaker detection got them all wrong, so I doubt we should bother to get that into the subtitle files. Unfortunately, I could not find there a description for the JSON structure, but it looks simple. 
I found some (mostly Python) scripts on the Internet, but they always try to group the words according to some "reasonable" rules, and the results are always wrong, and we lose the timing of the inner words. I think the grouping of words should be made mostly inside SE, no by some language-anaware script. Only long silences are universally relevant, and SE can handle that already. 
I'll try to help with what I can, please feel free to ask.

**Comment by niksedk** [comment]
OK, I've made a quick test here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
How does that work?

**Comment by jaccoud** [comment]
Hi

I could open educacao.json and the result is exactly what I expected – a subtitle line for each tagged emission in the transcription file.
The other two, longer files, issued errors; I suppose this is expected for this very first iteration.
Thanks a lot; I did not expect you to work on this so quickly, although I suspect this feature would be useful for many people.

Cheers.
=============================================
Marcelo Jaccoud Amaral
PETROBRAS
Tecnologia da Informação e Comunicações - Arquitetura (TIC/ESTTIC/ARQTIC)
[cid:image001.png@01D56C7B.705F5210]
tel: +55 (21) 2166-7507
=============================================
Há dois tipos de pessoas: as que conseguem extrapolar dados incompletos.

**Comment by niksedk** [comment]
Beta updated again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

Please do test again :)

**Comment by jaccoud** [comment]
Yes, I could import all three correctly. I will try to produce some more files for a more extensive test, activating some other service options that could affect the output, and will give you feed back maybe at the end of next week.
Again, thank you very much for the prompt answer.
