### ISSUE TITLE
Would it be possible to publish libse to Nuget

### ISSUE THREAD

**Issue by EraYaN** [SubtitleEdit/subtitleedit#3761]
I'd love to consume libse from another (dotnet core) project. And since the licenses are compatible I should be able to do so. But a release on Nuget would make this a lot easier.

EDIT: Alright I gave it a try running it on dotnet core. And for it to work on netstandard it will need version 2.1 (so the end of this month). And I had to remove some Registry stuff for the configuration. But it DOES work to parse subtitles.

**Comment by EraYaN** [comment]
@niksedk @xylographe So now that #3946 is in, what else do you guys need for this to show up on Nuget? I can add some script stuff that adds a `dotnet pack` to the build, but if you want to split the libse folder out then that would preferably happen first. (example result: https://github.com/EraYaN/libse)

**Comment by niksedk** [comment]
libse is now a a nuget package
