### ISSUE TITLE
Linux: This file is not a valid Matroska file

### ISSUE THREAD

**Issue by JGoutin** [SubtitleEdit/subtitleedit#3762]
Hello,

I get `This file is not a valid Matroska file: path/to/my/file.mkv` error message when trying to open a MKV file under Linux. I run Subtitle Edit 3.5.10 using mono 5.18.1.3 under Fedora 30.

The file I try to open is a proper MKV file that I successfully open under Windows and the same Subtitle Edit version.

**Comment by niksedk** [comment]
Perhaps someone could download "monodevelop" and debug - https://www.monodevelop.com/download/#fndtn-download-lin
The class to debug is called `MatroskaFile`

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by JGoutin** [comment]
I confirm the bug fixed with the new beta. Thanks !

**Comment by niksedk** [comment]
Could you also test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
Install the following packages: "libmpv-dev" + "vlc" + "libhunspell-dev"

How does the video player work?

**Comment by JGoutin** [comment]
I installed packages "hunspell-devel", "vlc", "mpv-libs-devel" (Packages names on Red Hat based distributions).

The video player work (Video + sound), but the subtitle does not appear in the video.

**Comment by niksedk** [comment]
Hm, it works on Ubuntu... but you can try Options -> Settings -> Video player, and turn off, that mpv handles preview text.

New beta up with other minor improvements for Linux (ocr via tesseract + settings): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by JGoutin** [comment]
I understand what is wrong : subtitles I open are in Blu-ray image format.

The subtitle preview works well with text subtitles.
