### ISSUE TITLE
timestamp issue with WebVTT-files

### ISSUE THREAD

**Issue by FUXIANGEN** [SubtitleEdit/subtitleedit#3764]
since version 3.5.10 beta,every time I open a webVTT-file,all times will  increased for ten seconds

This only happens when the second line of the file is a time stamp, something like:
```
X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000
```
sample files
[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/3624568/test.zip)

When I import this file ("imported 1.vtt")...
```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000

00:00:16.360 --> 00:00:20.840
00:00:20.920 --> 00:00:24.320
00:00:24.800 --> 00:00:27.160
00:00:28.600 --> 00:00:31.120
00:00:31.200 --> 00:00:33.880
00:00:33.960 --> 00:00:34.960
00:00:35.040 --> 00:00:38.560
00:00:38.640 --> 00:00:42.360
00:00:42.440 --> 00:00:46.880
00:00:47.600 --> 00:00:51.160
00:00:51.240 --> 00:00:54.520
00:00:54.600 --> 00:00:56.880
00:00:56.960 --> 00:00:59.160
00:00:59.240 --> 00:01:03.800
```
I export it ("exported 1.vtt")...
```
WEBVTT
00:00:26.360 --> 00:00:30.840(+10S)
00:00:30.920 --> 00:00:34.320(+10S)
00:00:34.800 --> 00:00:37.160(+10S)
00:00:38.600 --> 00:00:41.120(+10S)
00:00:41.200 --> 00:00:43.880(+10S)
00:00:43.960 --> 00:00:44.960(+10S)
00:00:45.040 --> 00:00:48.560(+10S)
00:00:48.640 --> 00:00:52.360(+10S)
00:00:52.440 --> 00:00:56.880(+10S)
00:00:57.600 --> 00:01:01.160(+10S)
00:01:01.240 --> 00:01:04.520(+10S)
00:01:04.600 --> 00:01:06.880(+10S)
00:01:06.960 --> 00:01:09.160(+10S)
00:01:09.240 --> 00:01:13.800(+10S)
```

**Comment by FUXIANGEN** [comment]
#3736

**Comment by tamplin** [comment]
Got the same  issue

**Comment by niksedk** [comment]
Hm, I think that's the purpose of the header: https://support.brightcove.com/synchronizing-webvtt-captions.

You can turn it off by edit Settings.xml and change the value of the tag called `WebVttUseXTimestampMap` to `False`.

Comments are welcome...

**Comment by tamplin** [comment]
may 

> Hm, I think that's the purpose of the header: https://support.brightcove.com/synchronizing-webvtt-captions.
> 
> You can turn it off by edit Settings.xml and change the value of the tag called `WebVttUseXTimestampMap` to `False`.
> 
> Comments are welcome...
Settings.xml couldn't find WebVttUseXTimestampMap,
may you can add this tag to settings

**Comment by xylographe** [comment]
The `WebVttUseXTimestampMap` tag was added after the release of SE 3.5.10. Try [SubtitleEditBeta.zip](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip).
