### ISSUE TITLE
Error Message: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by mophawka** [SubtitleEdit/subtitleedit#3765]
Haven't seen this one before. attached error windows. Thank you

![subtitlesedit error](https://user-images.githubusercontent.com/45985083/65227328-48e14200-da7d-11e9-90f5-c53257d5ceb2.jpg)

**Comment by niksedk** [comment]
Could you attach the subtitle?

**Comment by mophawka** [comment]
got this error message at 99% of a loaded m2ts file processing (ive done this around 218 times so far). its 30gb. let me see if i can extract the subtitle track and attached it. thank you

**Comment by mophawka** [comment]
@niksedk attached. thank you
[00000.zip](https://github.com/SubtitleEdit/subtitleedit/files/3633426/00000.zip)

**Comment by niksedk** [comment]
@mophawka: thx for the file :)
SE didi not crash on the `00000.zip` file with version 3.5.10... what version of SE do you use?
From your image stacktrace I've tried to fix the error in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip 
How does that work?

**Comment by mophawka** [comment]
@niksedk. correct SE does not crash when loading just the subtitles track. however, (as mentioned in the previous post) it does give that error when processing the m2ts track looking for subtitles.  also using latest stable 3.5.10.0. I updated to the beta zip file to provided and still getting errors.
please see attached details. thank you for taking the time to look this over.
![SE Error](https://user-images.githubusercontent.com/45985083/65299301-e2632f00-db23-11e9-9a1e-e1d4dcf63a0a.jpg)

**Comment by niksedk** [comment]
It's a bit hard to fix without being able to re-produce the error, but beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
Any better?

**Comment by mophawka** [comment]
god amongst men! that last beta fixed it. no error! thank you!
