### ISSUE TITLE
An apostrophe and a period are not reversed correctly

### ISSUE THREAD

**Issue by phistuck** [SubtitleEdit/subtitleedit#3766]
Version 3.5.10 (and below)
Have a subtitle with the following text -
.'קולג
Reverse it (not using control characters).

Expected -
קולג'.
(All of the punctuation marks should be on the same side - at the end of the text, first the apostrophe and then the period)

Actual -
'קולג.
(The apostrophe stays at the beginning and only the period is moved to the end)

**Comment by niksedk** [comment]
Thx for the info - beta updated (somewhat late): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

@OmrSi: Is it correct in your opinion to add the `'` to the list of start/end chars to reverse? (see commit)

**Comment by OmrSi** [comment]
I think it is correct. 
We don't usually use it in Arabic, so I didn't notice it. 
I believe this is a leftover from the quotation issue which you have already fixed.
