### ISSUE TITLE
SE 3.5.10 portable cannot OCR translate using mono

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3767]
Upon opening a .sup file the following error window pops up. When the error window is closed the OCR translation continues but each line's translation just says. "Error"

![image](https://user-images.githubusercontent.com/37562304/65308862-83ea8f00-dbbd-11e9-8455-71032bdb3030.png)

**Comment by niksedk** [comment]
Did you install `Tesseract ocr` ?

**Comment by shag00** [comment]
I did but found that the transcription quality was significantly worse than the built-in version, almost 1 error per line. I imagine this is because there does not appear to be a way to pre-process the bitmaps prior to the OCR operation. I attempted to pre process but the software I have does not accept .sup files as input (file corrupt or not a picture file).

If we can get this to work I would be more than happy to write a tutorial on how to set up an operational ubuntu Subtitle Edit if you would like to include it as a readme or on your site for your Linux users.
________________________________

**Comment by niksedk** [comment]
Yes, you're right - switching to tesseract 4.1.0 will fix it (just download it even though you don't need it).... I'll try to make a cleaner fix...

Also, could you also test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
Install the following packages: "libmpv-dev" + "vlc" + "libhunspell-dev"
How does the video player work?

**Comment by shag00** [comment]
I did 3 tests after ensuring I had the 3 packages installed.

1/ Without linux tessseract installed I got the same error message that is conatined
  in my initial error report.
2/ With linux tesseract installed:
  a/ Tesseract 3 - no translation took place - all empty lines although time codes did display,
  b/ Tesseract 4 - system requested to download tesseract 4 which completed without error. On translation start the attached error message popped up and SE froze.
________________________________

**Comment by shag00** [comment]
After closing all the open windows I found another pop-up, tesserect closed with 1.

________________________________

**Comment by niksedk** [comment]
Thx for testing :)

New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by shag00** [comment]
You are welcome, I did not test VLC as the first part did not work. Do you still want me to proceed with that?

________________________________

**Comment by niksedk** [comment]
Please do test the video player... but mpv works better than vlc as vlc cannot seek very well.
I'll close this as the OCR part seems to work now :)

**Comment by shag00** [comment]
I have tested the video player as follows:
1/  MPV

  *   no volume control
  *   can go to fullscreen mode but not return to composite view mode
  *   there is no time information displayed

________________________________

**Comment by shag00** [comment]
Video test:
1/ MPV

  *   works in a basic way
  *   no volume level control but can mute
  *   can enter fullscreen mode but not return to composite screen mode
  *   no timing information displayed

2/ Other video

  *   not able to deselect MPV or select any other video mode

OCR test:
It seems not fixed. I no longer get an error message although I have included a screen shot after 4 minutes of processing using Tesseract 4 and default settings with English language. As you can see only 3 lines processed with no output.

________________________________

**Comment by shag00** [comment]
Sorry, forgot to mention I used 3.11 beta version.

________________________________

**Comment by niksedk** [comment]
New beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

You need "libvlc-dev" or something for vlc to work...

**Comment by shag00** [comment]
Test results:

No change at all for the OCR processing, each line processes for almost 2 minutes each and produces no output.

I installed libvlc-dev as per your advice and VLC is now a selectable option as the video player however it does not launch/start and throws up the following error messages:

[0000558e1b637a50] vlcpulse audio output error: digital pass-through stream connection failure: Not supported
[0000558e1b637a50] main audio output error: module not functional
[00007f7b48130680] main decoder error: failed to create audio output
[0000558e1b637a50] vlcpulse audio output error: digital pass-through stream connection failure: Not supported
[0000558e1b637a50] main audio output error: module not functional
[00007f7b48130680] main decoder error: failed to create audio output

Another message which I get when I start mono/SE is: X does not support your locale, not sure if this is relevant.
________________________________

**Comment by shag00** [comment]
Since our last series of e-mails back in late September I have been waiting for the next release which was today but there seems like there is no forward movement from the last release. To recap, I am using Kubuntu 19.10 and I am trying to run SE under the latest version of mono, 6.6.0 with the following ubuntu libraries installed:

mono version 6.6.0

libhunspell-dev

hunspell

hunspell-en-au

libtesseract-dev

libtesseract4

with SubtitleEditBeta, released today. When we left off I could not get OCR or VLC to work correctly.


On starting the OCR process the following screen appears which gives an OCR option of Binary Image Compare or Tesseract 4. The portable file contains a folder named  Tesseract302 only, though Tesseract 4 is installed in Ubuntu.


[cid:5a1fa95d-d7d7-4338-bb5f-6e70c0de7f21]



In the second instance there is no language installed but a pop-up requesting to download one. The result is that the greys out and becomes non resposive at 100%:


[cid:cdbbcb4d-99b3-4bb8-aafb-d83571a33e8d]


I am not a programmer and don't know what or where the program is looking for data. If it is looking for languages etc then I see that languages and tesseract 3.02 are included in the download file but it does not find them, though tesseract 4 is not. If it is looking for them on the host system they are installed but again cannot find them. So my question is should tesseract 4 be installed into the downloaded file from you. Or more precisely where is the program looking to find tesseract?


________________________________

**Comment by niksedk** [comment]
The "Tesseract302" folder is for windows only.

I just tested latest SE with Ubuntu 18.something... OCR / libmpv / spell check - all work fine here.
(besides a few buttons are missing the OK/Cancel label for some reason)

**Comment by shag00** [comment]
Thank you for your reply. I am tearing my hair out here trying to make this work. I wonder if you might be able to help me troubleshoot why I cannot get Tesseract to work. I just don't know what to look for.

Thanks.

________________________________

**Comment by shag00** [comment]
Even trying to install a language for tesseract produces this error:

[cid:2dce6b79-d340-4fad-9f78-93b83d048de0]

________________________________

**Comment by xylographe** [comment]
@shag00 
Tesseract OCR on Linux does not use the Subtitle Edit tessdata directory at all. It is presumed that the necessary language training data has been provided in the Tesseract tessdata directory (e.g. `/usr/share/tesseract-ocr/4.00/tessdata`).

**Comment by xylographe** [comment]
@shag00 
To work around the Tesseract deadlock problem you reported earlier you can try
[`SE-3.5.11-issue3851.7z`](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0).

**Comment by shag00** [comment]
Thank you for taking the time to address this issue. What I have at the moment at that location is:

scott@scottubuntu:/usr/share/tesseract-ocr/4.00/tessdata$ ls
configs  pdf.ttf  tessconfigs

The contents of both folders are all files, ie. no sub folders. I have also installed the following:

mono version 6.6.0

libhunspell-dev

hunspell

hunspell-en-au

libtesseract-dev

libtesseract4


________________________________

**Comment by shag00** [comment]
Again,
thank you for your reply.

If the deadlock problem you cite is the the problem that occurs when you press the box with the 3 dots (below) and
1
[cid:a72cd23e-8acf-4fef-91ef-b471b955bcaa]
the following screen pops up
2
[cid:1926203e-e71f-4dd4-bd37-be43acb86655]
then press Download
3
[cid:260dea88-dfec-46f2-8107-e2f9b8aed125]
and then the process stops at 100%, file SE-3.5.11-issue3851.7z<https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0>. does not fix the problem.

If the deadlock problem is the error produced by clicking the Open 'Dictionaries' folder link (in blue on the images 2 & 3 above) which produces the following error then it is also not fixed?
4
[cid:2eaf6301-21cd-4ccf-9812-fa50413353dd]
These screenshots were taken with SE-3.5.11-issue3851.7z<https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0>. installed.

Regards,

Scott
________________________________

**Comment by xylographe** [comment]
@shag00 Your comments above (except for the original post) do not display the images. All I can see is `[cid:260dea88-dfec-46f2-8107-e2f9b8aed125]`, `[cid:1926203e-e71f-4dd4-bd37-be43acb86655]`, etc. Please, edit your last comment to fix this.

With _deadlock_, I was referring to:
> each line processes for almost 2 minutes each and produces no output.

I don't understand why your tessdata directory is practically empty. At least the following three files should be present, (after `sudo apt install tesseract-ocr`)
```
tessdata/configs/hocr
tessdata/eng.traineddata
tessdata/osd.traineddata
```
Extra language training data would be installed with `apt` (e.g. `sudo apt install tesseract-ocr-nld`).

Instead of downloading language training data in Subtitle Edit, you create a symlink to the directory that is actually used by tesseract. Let's say you extracted the Subtitle Edit archive into `$HOME/SubtitleEdit`, then you would run,
```
cd ~/SubtitleEdit/Tesseract410
mv tessdata tessdata.orig
ln -s /usr/share/tesseract-ocr/4.00/tessdata
```

**Comment by shag00** [comment]
OK, we are at risk of miscommunicating here, the deadlock issue relates to a series of e-mails from September 2019. The issues at that time relate to the beta version of SE 3.5.11, the issues I have spoken about in the last several days relate to the beta version of 3.5.12. Basically, I did some testing on the 3.5.11 beta and waited the 3 months until the 3.5.12 beta came out (a couple of days ago) which is what I am using now. So in effect my last email to you (dated today) is talking about a problem which was not mentioned in the September emails which you appear to have and appear to be referencing. So to clear the air, I am now using 3.5.12 beta and I have not been able to get to a stage where I can test the deadlock issue.

I will revert to you more fully tomorrow morning (my time) with further details.

Regards,

Scott
________________________________

**Comment by shag00** [comment]
Attached are the screenshots that you did not reeive yesterday,

________________________________

**Comment by shag00** [comment]
Based on your last e-mail I have successfully linked SE to Tesseract and have, at about 90% functionality at this stage, thank you very much for your assistance in this. There are some smaller problems which I will address later.

________________________________

**Comment by shag00** [comment]
Thank you for your assistance, I now have OCR translation working.

________________________________

**Comment by shag00** [comment]
I wonder if you could tell me how to change the Hunspell dictionary that SE uses. I have 2 dictionaries installed, US English and Australian English but the only dictionary that is visible in SE is the US dictionary.

Thanks

________________________________

**Comment by xylographe** [comment]
First run `hunspell -D` to find the Hunspell dictionary search path. Let's assume the Hunspell dictionaries (`en_US.dic`, `en_US.aff`, `en_AU.dic` and `en_AU.aff`) are in the `/usr/share/myspell` directory. To let Subtitle Edit know that the Australian dictionary is available, create links in the Subtitle Edit `Dictionaries` directory,
```
cd ~/SubtitleEdit/Dictionaries
ln -s /usr/share/myspell/en_AU.dic
ln -s /usr/share/myspell/en_AU.aff
```

**Comment by shag00** [comment]
In 19.10 seems they have changed the directories. The links that work are:

ln -s /usr/share/hunspell/en_AU.aff
ln -s /usr/share/hunspell/en_AU.dic



________________________________

**Comment by shag00** [comment]
I can now select the appropriate dictionary.

Where are the Word Lists located, specifically, Names Ignore List, User Word List and OCR Fix List?

Thanks,

Scott

________________________________

**Comment by xylographe** [comment]
The Word Lists are located in the Subtitle Edit **`Dictionaries`** directory,
Names in `names.xml`, `en_names.xml` and `en_names_user.xml` (optional),
OCR fixes in `eng_OCRFixReplaceList.xml` and `eng_OCRFixReplaceList_User.xml`  (optional),
User Word lists in `en_AU_user.xml` and `en_US_user.xml`.
