### ISSUE TITLE
Removal of music-symbol-only lines

### ISSUE THREAD

**Issue by jrjordao** [SubtitleEdit/subtitleedit#3768]
Lines consisting of only music symbols and whitespace, such as "♪" and "♪ ♪", used for instrumental or background/indistinct music, seem to me irrelevant for all non hearing impaired. We can thankfully hear the music playing, just as well as the door opening, the dog barking, etc.

Although it's quite simple to get rid of those lines with a regex rule in "multiple replace", it seems to me they should be handled by default in "remove text for hearing impaired". The existing "remove text between (music symbol) and (music symbol)" option already removes them, but it also removes "(music symbol) lyric text (music symbol)" lines which I prefer to keep.

**Comment by niksedk** [comment]
I think most ppl would also remove the text too... so "multiple replace" is a good alternative.

**Comment by jrjordao** [comment]
So you think most people needing the dialogue lines do not need the lyric lines as well? I find that odd. If you need help understanding spoken language, you probably need it as much for "sung language".

**Comment by niksedk** [comment]
If you're hearing impaired I think you would need both music symbols and text
