### ISSUE TITLE
Weird line import

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#3769]
Hello 

For certain tv DVD's (The Simpsons, Frasier & Scrubs so far) I get this strange line popping up at the very beginning, the end and a couple of places in the middle.

TesserAct 4.1 translates this as the character ', but it is really just noise.

If I had to guess, I would think it is a case of bad formatting from the DVD publisher.

You can download the vobsub in question here:
[subtitle.zip](https://github.com/SubtitleEdit/subtitleedit/files/3635432/subtitle.zip)

Here is what it looks like in SE
![Udklip](https://user-images.githubusercontent.com/5127386/65318980-f6984200-db9e-11e9-881e-c5fc8a620db3.PNG)

**Comment by niksedk** [comment]
I think you forgot to include the .sub file in the `subtitle.zip` attachment.

**Comment by Maitch** [comment]
Yes, I forgot. Lets try again

[subtitle2.zip](https://github.com/SubtitleEdit/subtitleedit/files/3636322/subtitle2.zip)

**Comment by niksedk** [comment]
Hm, I don't get those lines:
![image](https://user-images.githubusercontent.com/1261331/65336093-ff503e80-dbc5-11e9-846e-a2ce67afdf34.png)

**Comment by Maitch** [comment]
That's weird. I used Inviska MKV Extract to extract the sub from the MKV. 
When I open the sub directly it does not give me the lines, but when I open it from the MKV file, I get the lines.
I could upload the MKV, but wouldn't that be a copyright violation?

**Comment by niksedk** [comment]
Perhaps you could use a "file split" program and email me like the first 10-20 MB of the file - hopefully that should be enough.
