### ISSUE TITLE
Shortcut - Add Dash.

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3770]
Hello,
I would like to know if there is or can be added, a shortcut that will add dashes before the start of the line indicating a two-speaker subtitle. Now we have to add a dash manually before the start of the line to indicate a two person dialogue. It would be easier if a shortcut does it.
So:
How are you?
I'm good.
will become:
- How are you?
- I'm good.
with just one shortcut.
Thank you.

**Comment by uckthis** [comment]
-is a dash, btw.

**Comment by uckthis** [comment]
- How are you?
- I'm good.

**Comment by uckthis** [comment]
- How are you?
- I'm good.

**Comment by uckthis** [comment]
I don't know why that dash is being shown as a bullet point. it's a -

**Comment by niksedk** [comment]
Check the shortcut "Toggle dashes" :)

**Comment by uckthis** [comment]
@niksedk Thank you, man. I didn't know this existed. Will save me a lot of time from now on.
