### ISSUE TITLE
An error I haven't encountered before

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3771]
3.5.10 NEXT 46.
Not sure how to reproduce it, but I encountered this error:
![se-error-import](https://user-images.githubusercontent.com/19672444/65387791-63ecd400-dd53-11e9-9f16-379478a43979.png)

I was in a SE window that I hadn't opened in a while, that had both video and subtitles open. I pressed the keyboard shortcut for file->new (which closed both), and then immediately the keyboard shortcut for import plain text. This is something I do fairly often and I haven't had this happen until now.

**Comment by niksedk** [comment]
thx for the info - I'm not really sure what's happening... but I've tried a little ;)

**Comment by darnn** [comment]
Thank you!
