### ISSUE TITLE
Line Merging is too slow

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3773]
Hello,
Few months back DirectShow stopped working for me. It would only play audio and display screen would be blank. I saw an issue posted here about that, but it was closed without any proper solution and so I tried everything I could to fix it, but nothing fixed it. I reinstalled Windows, updated codec, whatnot... 
So, I just moved to MPV as the default video player. I never liked MPV because it's slower than DirectShow, but I had no choice. MPV is still faster than VLC and MPC-HC.  The thing I hate the most is the slow merging of the lines. If you have a subtitle file that has over 2000 lines, it takes ages to merge two lines. I generally make two copies of 1000 lines each and join them later to workaround it. With DirectShow, line merging was super smooth. 
Any solution? I use MPV and video output direct3d_shaders.
Thank you.

**Comment by uckthis** [comment]
Slow merging and switching to MPV might not be related, but it started happening when I switched.

**Comment by niksedk** [comment]
Directshow is very dependent on what's installed on your local computer... 

How long is "ages" ? 
It takes less than one second here with 2000 lines...

**Comment by uckthis** [comment]
@niksedk Between one and 3 seconds depending on where I'm at. it'll take more time if I'm at line 700 than If I'm at 1700.

**Comment by niksedk** [comment]
Latest beta should be a few milliseconds faster: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
Any better for you?

Merging the two last lines in a subtitle with 2.000 lines takes about 700 ms on my pc.

**Comment by uckthis** [comment]
@niksedk Yes, it has improved in the latest beta. 
I tried merging lines at 700 and then at 1700 and it was similar time; which is good. And yeah, it was about 500ms (I have a faster computer).
Thank you very much.

**Comment by niksedk** [comment]
thx for reporting and testing :)
