### ISSUE TITLE
Small font size of UI in 3.5.10, difficult to read

### ISSUE THREAD

**Issue by Xenos71** [SubtitleEdit/subtitleedit#3776]
In 3.5.10, the font size of the main menu, the drop-down menus and basically all texts in the UI, are smaller than what they were before. It's really hard to read, especially on a laptop.

![SE10](https://user-images.githubusercontent.com/32386964/65537475-f46f1400-df0d-11e9-9361-3dfc358a3f9a.jpg)

Would it be possible to add an option to the general UI font settings for setting the font size, like there is for List view and Text box? Or maybe just restore the size to what it was in 3.5.9, if it doesn't cause trouble elsewhere?

Thank you in advance,
Xenos

**Comment by niksedk** [comment]
It's possible to change via Settings.xml... change these tags to your preferred font name/size:

         <SystemSubtitleFontNameOverride>Comic Sans MS</SystemSubtitleFontNameOverride>
         <SystemSubtitleFontSizeOverride>12</SystemSubtitleFontSizeOverride>

**Comment by Xenos71** [comment]
Thank you!
