### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by AlexandreMT** [SubtitleEdit/subtitleedit#3777]
Statistics are taking tags into account.

What statistics says:
![image](https://user-images.githubusercontent.com/25598649/65562773-f214b600-df1d-11e9-8bea-c774f4b3fac6.png)

But actually:
![image](https://user-images.githubusercontent.com/25598649/65562824-1bcddd00-df1e-11e9-8a7d-d0e99d58ada5.png)

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
