### ISSUE TITLE
Waveform

### ISSUE THREAD

**Issue by AlexandreMT** [SubtitleEdit/subtitleedit#3779]
When waveform is focused it's not possible to add tags to the text using shortcuts, is there any way to make that possible?

**Comment by niksedk** [comment]
@AlexandreMT: I've some tags like italic and alignment in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
Does that work okay and do you need more shortcuts working in waveform?

**Comment by AlexandreMT** [comment]
It's perfect.

Thanks a lot!
