### ISSUE TITLE
Choose current line with one click 

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#3780]
Hi
Is it possible to choose current line in waveform with just one click instead on two click like it is now?

**Comment by niksedk** [comment]
One click in "set video position"... so you would like it more customizable?

**Comment by m0ck69** [comment]
Yes.

**Comment by OmrSi** [comment]
Related:
https://github.com/SubtitleEdit/subtitleedit/issues/2928
https://github.com/SubtitleEdit/subtitleedit/issues/2990

This is for when you, for example, go to a video position and want to offset the next line it but you don't have the list focused, you have to go to next line, and thereby losing the video position.

@m0ck69 The way to do this with the mouse is to right-click and then escape the menu that pops up, but a shortcut would be easier.

**Comment by OmrSi** [comment]
@niksedk Can you take a look at this?
We just want a shortcut to select the current line without changing video position.

**Comment by OmrSi** [comment]
@niksedk Closed.
![image](https://user-images.githubusercontent.com/20923700/79578833-6f2c9600-80cf-11ea-99f0-d041a12051fb.png)
