### ISSUE TITLE
Crash when using point sync

### ISSUE THREAD

**Issue by psonnosp** [SubtitleEdit/subtitleedit#3781]
Point sync freezes the program and only solution is to shut the program down from the task manager.

Win10 and SE 3.5.10 (18th August 2019) but this error has been appearing in earlier versions to but then it wasn't happening 100% of the tries.

How to reproduce:
Open point sync dialog.
Mark subtitle line.
Click on 'Set sync point'.
Change 'Sync point time code'.
Click 'Set sync point'.
And freeze...

**Comment by niksedk** [comment]
Hm, it works fine here... what video player are you using?
What happens if you change your video player to "mpv" - go to Options -> Settings -> Video player

**Comment by psonnosp** [comment]
I already use mpv, it's the only one where the "moving line in the spectrogram" sync properly to the video but it's the same no matter what player I use. Haven't tried VLC though cause for some reason I can't select it even though it's installed and pointing to the install folder doesn't help. But that's another issue I guess ;)

**Comment by psonnosp** [comment]
Tried it again just for fun and it worked so tried a few others and found some others that also worked but there are still some that I cant get to work. So can there be an issue connected to certain video files for some reason?
They are all .mkv and fully functional files and they play just fine in the player in SE.
Are there a debug mode or something so I can create and post a log when this occurs?

**Comment by niksedk** [comment]
You can attach a subtitle that does not work?
I've tried 4-6 subtitles and all work.

**Comment by psonnosp** [comment]
Thought I had found the cause, empty lines at the end of the file, not empty subtitle lines but completely empty lines. But then after a few tries adding and removing lines in notepad to confirm it, it all of a sudden didn't matter any more...
The attached sub looks fine to me so don't think it'll help you find anything without the video.

**Comment by niksedk** [comment]
@psonnosp: Also works for me... let me know if you find a way to re-create this.

**Comment by psonnosp** [comment]
Without the video loaded it works for me to so that was no surprise.
So there's no debug version/mode so I can log what's happening? So we can rule out if there's something outside SE that's causing it to happen.

**Comment by psonnosp** [comment]
Got this one 
![Capture_3](https://user-images.githubusercontent.com/28609335/66258172-22701600-e7a2-11e9-8c71-f8d99bbe5867.jpg)
when changing video output for mpv if can be to any help.

**Comment by niksedk** [comment]
thx, that's a bug - should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by psonnosp** [comment]
Didn't change anything regarding this issue though.
I'm out of both ideas and possibilities to dive any deeper in this so guess I'll just have to figure out a new way to sync my subs.
Thanks for your time, much appreciated.

**Comment by VideoPlayerCode** [comment]
@niksedk I am seeing the same thing on 64-bit Win 10. With mpv downloaded inside Subtitle Edit, and with VLC 64-bit loaded externally.

Results:

- MPV engine is the only frame-accurate engine. It is great. But it crashes EVERY time you try to do Visual Sync or Point Sync.
- VLC can do Visual Sync and Point Sync.

**Comment by niksedk** [comment]
How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

I've seen other developers with the same problem with libmpv freezing, but it seems (I hope) that some delays helps but I don't know why...
