### ISSUE TITLE
Adjust tool fails when there is exactly one line

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#3782]
Hello

I just noticed one thing when I am using the "Adjust all times" tool.

If you only have exactly one line selected and have it on the "Selected lines only". It will not adjust the time. Sometimes it will only adjust one time when clicking either of the buttons, but most of the time it will not do anything.
It works fine when there are multiple lines chosen. 

![Udklip](https://user-images.githubusercontent.com/5127386/65834207-20591380-e2d9-11e9-9224-2c41c8daf6f2.PNG)

**Comment by niksedk** [comment]
Show earlier will not move is the move will cause an overlap
