### ISSUE TITLE
no video after updating Windows 10 1803 to 1903

### ISSUE THREAD

**Issue by clem2** [SubtitleEdit/subtitleedit#3784]
Using Directshow, mkv/mp4 video was fine on 1803, but on 1903 it's just a black screen with only the subtitles showing. Tried reinstalling LAV and Subtitle Edit and using Codec Tweak Tool, but no luck.

**Comment by HoangZMB** [comment]
Same problem.

**Comment by niksedk** [comment]
I'll close this for now - could be a windows version problem and also the Settings.xml setting `DirectShowDoubleLoadVideo` equals `true` might also help. And switching to `mpv` video player is also a solution (notice that VLC has bad precision which should be fixed in v4 at some point)

**Comment by Gittyperson** [comment]
I'll just report this issue too. It did not happen in the past. Windows 10 1909.

Setting DirectShowDoubleLoadVideo=true fixed it. I don't know what this does, but at least it works.
