### ISSUE TITLE
Problem with fixing overlapping

### ISSUE THREAD

**Issue by Xenos71** [SubtitleEdit/subtitleedit#3787]
Hi,

When I load the attached subtitles to Subtitle Edit, the following occur:
In List view, the two cases of overlapping (subs 2-3 and 5-6) are marked by colored starting and ending times. If I click on any of them, I get a specific message of overlapping on the left of the Text box, under Start time and Duration.
However, when I hit "Fix common errors", only the first overlapping case appears in the Fixes window.

My guess is that when two subtitles overlap, if the start time of the second is earlier than the start time of the first, then for some reason the above behaviour occurs.
Can you please have a look at it?

Thanks in advance,
Xenos
[SE - Problem with overlapping.zip](https://github.com/SubtitleEdit/subtitleedit/files/3673909/SE.-.Problem.with.overlapping.zip)

**Comment by niksedk** [comment]
The reason only one line appears in "Fix common errors" is that SE cannot do more automatically - you need to fix the rest manually. 

SE should now handle this with better messages (I hope):
![image](https://user-images.githubusercontent.com/1261331/69498317-0e65ac80-0ee7-11ea-8acd-e433ab92d43a.png)

Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip
