### ISSUE TITLE
OCR scanning unicode character … vs. 3x .

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#3788]
Hello

This is not really a bug per se, but I am having a problem with the OCR scanning recognizing ... as the unicode character … instead of 3 normal characters .

The problem is my TV is unable to display the unicode character properly, so I would prefer the 3 normal punctuation.

Right now I am using a batch search and replace, but I was wondering if there were a place where you could configure it to omit the character … from the OCR scan.

**Comment by Maitch** [comment]
So if anybody else is bothered by this issue. I have solved it by adding this to LANGUAGE_OCRFixReplaceList_User.xml
`<Word from="…" to="..." />`
and 
```
  <PartialWordsAlways>
    <WordPart from="…" to="..." />
  </PartialWordsAlways>
```

**Comment by niksedk** [comment]
What "OCR method" are you using?

**Comment by Maitch** [comment]
I am using Tesseract. (I know. You keep saying switch to binary, but it does not give me a very good result and has more manual input)

Anyway, I switched to this to finally get rid of the unicode character for all cases.
```
 <RegularExpressions>
    <RegEx find="[…]" replaceWith="..." />
 </RegularExpressions>
```
