### ISSUE TITLE
Blu-Ray MKV - MAYBE 20% success rate

### ISSUE THREAD

**Issue by JaySMa** [SubtitleEdit/subtitleedit#3789]
Hello..
While the fast OCR of the subtitles is nice, I find myself spending more time now than with prior versions, fixings issues with the final SRT's.

For example, just recently, tried a MKV.
- All lower case 'e's' at the end of words were were 'c's'; some were even in the middle of words.  E.g.: 'wcrc' for 'were'.
- Multiple characters had spaces added before them; ' m', ' n', ' o', ' ,', etc.  E.g.: 'c o m m e nt' for 'comment'.
- Most left brackets '[' were entered as 'J'.  E.g:  '<i>JWhilstles]</i>'
- Periods '.' at the end of sentences ended up becoming multiple comma's ',,,'.  E.g.: 'this is the end of the line,,,'

Now while there are multiple tracks available for subtitles in the MKV, would trying another track be more beneficial over another?  Also, is there a way to better train the OCR?  I'd rather spend five minutes training the OCR to be better than spending four hours fixing the final SRT.

Thank you..

**Comment by darnn** [comment]
Have you tried selecting "Binary image compare" as the OCR method?

**Comment by JaySMa** [comment]
Yes, that was the default setting and what ultimately seemed like the issue.

Bought Spiderman yesterday and I tried the Tesseract 4.1 setting and got much better results.  It missed all of the italics and the music icons, but overall things were much better.

I then tried the "BIC" setting and compared the two results.  As before, spaces before periods and some letters, "I" marked as "L" or "1", things like that with BIC.

But with comparing the two results, I could see where the <i> was missed, etc., and just manually edited to fix.

**Comment by darnn** [comment]
Sounds like you might want to try a lower value of "max. error%" with BIC, you'll get less false positives that way (although it will be more time consuming since you'll have to enter the right character more often).

**Comment by niksedk** [comment]
It's a bit hard to say without the sub... (you can right-click in the ocr window list view and save as e.g. sup).

"BIC" is normally the best, but you often need to fix a few letters. I use a low error % at the beginning + double click on lines in the list view to inspect and update bad guesses.

**Comment by JaySMa** [comment]
I've been playing with the settings and have made the BIC better at guess the words than Tesseract. 'max. error %' I have set down to 2-2.5% and the pixel for spaces set to 8-10.  Every now and again, I'll get words put together or spaces before letters, but most times using the built-in spell check works to correct these errors.  I also open the SRT in notepad++ and using this spell check function will help show me these items as well.

One issue which has arisen is the percent sign; '%'.  For some reason, it corrects these to 'o/o' and I can't find where to correct this.  Thank you..

**Comment by niksedk** [comment]
Try to double-click on in line in the ocr window list view, then right-click and the first bad letter and choose "Add better multi match":
![image](https://user-images.githubusercontent.com/1261331/66585796-caf9ed80-eb87-11e9-92b8-c734bce8737e.png)

In the "Add better multi match" window, select all three characters, and press "OK":
![image](https://user-images.githubusercontent.com/1261331/66585884-f1b82400-eb87-11e9-8602-2b87c97707c3.png)


Hopefully this will not be needed too often...
