### ISSUE TITLE
[Feature] Add Removal of text between * 

### ISSUE THREAD

**Issue by MB053** [SubtitleEdit/subtitleedit#3790]
Can u please add an option under the crtl+alt+h "Remove Text for hearing impaired" to remove lines where text is between the * icon ?

**Comment by darnn** [comment]
In "remove text between", the last option before "only if in separate line" allows you to type in characters of your own, so you could just do it that way.

**Comment by MB053** [comment]
Thankss so stupid i didn’t saw that
