### ISSUE TITLE
[Feature Request] Insert new subtitle at each key-press, set end time for previous subtitle line if exist

### ISSUE THREAD

**Issue by molokal** [SubtitleEdit/subtitleedit#3791]
I just found this shortcut 'Insert new subtitle at key-down, set end time at key-up' and it made my work a little bit easier. Kudos for that!

Though after a while holding down a key while waiting musician in the video singing the next line make the next subtitle appear much later. As I need to press the key fast twice to set end time and create new subtitle simultaneously.

It will be much better with a simple key-press to start a new subtitle and the next key-press will set its end time if exist while creating new subtitle. And automatically put end time for a new subtitle when the video finish playing to prevent any error somehow. 

I don't know if there are already something like this as I can't find them from the settings.
Hope this idea helps. BTW thanks for creating this great subtitle editor!

**Comment by amiaship** [comment]
You might be looking for "Set end, add new and go to new" under "Create/adjust" in Shortcuts. It automatically sets the end time for the current subtitle and starts a new one. I have it set to Shift + Return so I can keep typing the next subtitle without pausing the video.
![negativesubs-2](https://user-images.githubusercontent.com/38370615/69012211-e4394b00-0938-11ea-8f1f-2a8d7e09a2ec.JPG)
Not sure about auto end times for subtitles at the end of a video, but that should only throw one error per file. It may be worth the work to manually set the final timestamp.

**Comment by OmrSi** [comment]
@niksedk Closed? `Set end, add new and go to new` should to the trick.
