### ISSUE TITLE
OCR missing one of two lines

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#3792]
Hello

Sometimes an entire line is missing in the OCR scanning. In this case I had the following subtitle:
![Image109](https://user-images.githubusercontent.com/5127386/66207417-05a8e500-e6b3-11e9-8401-d8465a6a21ab.png)
Which only resulted in "- Han tager fejl."

![Udklip](https://user-images.githubusercontent.com/5127386/66207401-f7f35f80-e6b2-11e9-865d-26d565627b97.PNG)

Here is the subtitle in question.
[Tyger Tyger_Subtitles02.DAN.zip](https://github.com/SubtitleEdit/subtitleedit/files/3690726/Tyger.Tyger_Subtitles02.DAN.zip)

**Comment by Maitch** [comment]
Here is another example:

![Image104](https://user-images.githubusercontent.com/5127386/66207674-abf4ea80-e6b3-11e9-9c37-dbf7e86573d3.png)

![Udklip](https://user-images.githubusercontent.com/5127386/66207659-a1d2ec00-e6b3-11e9-8d54-05e996b61ac2.PNG)

**Comment by niksedk** [comment]
thx for the bug report and thx for including the subtitle which makes things so much easier :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
How is that?

**Comment by Maitch** [comment]
I can confirm that I don't have the issue in the beta.
