### ISSUE TITLE
copy-paste makes list view jump to top

### ISSUE THREAD

**Issue by singulararmchair** [SubtitleEdit/subtitleedit#3793]
Strange that I hadn't noticed before, but since v 5.8, after pasting a line, the list view always jumps to line 1. I've tried deleting my settings file, didn't make a difference. Tested versions 5.10, 5.9, and 5.8: all of them behave this way. Had to revert to 5.7 to be able to copy-paste normally.
I'm on Ubuntu 18.04.3.

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
