### ISSUE TITLE
Can't download tesseract 4.0

### ISSUE THREAD

**Issue by Nottt** [SubtitleEdit/subtitleedit#3794]
![image](https://user-images.githubusercontent.com/13532436/66261738-294e5700-e7a9-11e9-9985-71a3af30300a.png)

**Comment by xylographe** [comment]
Presumably fixed in commit a0d0d5ef2e75e02c0cc9afa509bb53bd97ed5dee.
Please, try [SubtitleEditBeta.zip](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip).

**Comment by Nottt** [comment]
It is indeed fixed. 

But my antivirus killed it when I tried to start OCR lol
