### ISSUE TITLE
OCR scan - strange {/an8} output

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#3796]
Hello

I have gotten a few files with the OCR outputting {/an8} in front of all uppercase text.
I am using the current beta.

![Image205](https://user-images.githubusercontent.com/5127386/66272236-4e090400-e867-11e9-9aae-631503b7de5c.png)
[Title_1_Subtitles02.DAN.zip](https://github.com/SubtitleEdit/subtitleedit/files/3694636/Title_1_Subtitles02.DAN.zip)

![Udklip](https://user-images.githubusercontent.com/5127386/66272210-23b74680-e867-11e9-89df-6ab2e4f81fd1.PNG)

**Comment by xylographe** [comment]
If the subtitle text starts with `{\an8}`, the subtitle appears at the top (top centre alignment).

**Comment by Maitch** [comment]
I see. Sorry for the ticket.
