### ISSUE TITLE
[Bug] Disappearing spaces when converting DFXP2SRT

### ISSUE THREAD

**Issue by gru123** [SubtitleEdit/subtitleedit#3797]
Hi,

I'm trying to change format of the subtitles, but when converting dfxp2srt the spaces between italic words mysteriously disappear. Using SE v3.5.10.

Here is an example (dfxp file):
![test1](https://user-images.githubusercontent.com/42896067/66595283-ecb0a000-eb9a-11e9-82b2-fa01736f7f6e.png)
And the conversion result (srt file):
![test2](https://user-images.githubusercontent.com/42896067/66595324-06ea7e00-eb9b-11e9-8016-807620bb69af.png)
Sample DFXP file is attached.

Best regards.

[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/3714005/test.zip)

**Comment by niksedk** [comment]
Thx for the info :)

Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by gru123** [comment]
Thanks for the quick response :)
