### ISSUE TITLE
OCR binary compare: first word after caps missed italic style

### ISSUE THREAD

**Issue by alexantr** [SubtitleEdit/subtitleedit#3798]
All italic letters recognized correctly but resulting text has one word with missed italic after words with all caps.

How to reproduce:
* Download SE3510.zip and unpack
* [Download SUP file](https://github.com/SubtitleEdit/subtitleedit/files/3714202/F1_T7_.eng.SDH.zip), unpack and open
* Create new database and set other settings like on screenshots below
* Start OCR
* After OCR will finished check subtitles with #: 358, 363, 367, 386, 391, 664, 1562

![SubtitleEdit_2019-10-10_21-34-05](https://user-images.githubusercontent.com/4941848/66599225-63559980-ebab-11e9-9e6f-86b50f63cb5a.png)
![SubtitleEdit_2019-10-10_21-18-33](https://user-images.githubusercontent.com/4941848/66599237-6badd480-ebab-11e9-82c1-81bc6c7d06a1.png)
![SubtitleEdit_2019-10-10_21-36-47](https://user-images.githubusercontent.com/4941848/66599248-723c4c00-ebab-11e9-9ef5-bbb0ec201a64.png)
![SubtitleEdit_2019-10-10_21-22-36](https://user-images.githubusercontent.com/4941848/66599252-75cfd300-ebab-11e9-81f3-f2eab169bc25.png)
![SubtitleEdit_2019-10-10_21-38-41](https://user-images.githubusercontent.com/4941848/66599259-77999680-ebab-11e9-849b-c1ba8ae050db.png)
![SubtitleEdit_2019-10-10_21-38-25](https://user-images.githubusercontent.com/4941848/66599272-7bc5b400-ebab-11e9-8934-641f20807f34.png)

Database: [Lat.zip](https://github.com/SubtitleEdit/subtitleedit/files/3714229/Lat.zip)

**Comment by alexantr** [comment]
Problem in version 3.5.10 only.

3.5.8 works fine:
![SubtitleEdit_2019-10-10_22-19-07](https://user-images.githubusercontent.com/4941848/66599771-b5e38580-ebac-11e9-8e68-637a5d139665.png)

3.5.9 has best result:
![SubtitleEdit_2019-10-10_22-23-23](https://user-images.githubusercontent.com/4941848/66599826-d0b5fa00-ebac-11e9-9679-94d21032bfdd.png)
![SubtitleEdit_2019-10-10_22-23-37](https://user-images.githubusercontent.com/4941848/66599832-d27fbd80-ebac-11e9-9f5b-0934aa66b9f3.png)
![SubtitleEdit_2019-10-10_22-23-47](https://user-images.githubusercontent.com/4941848/66599840-d4498100-ebac-11e9-8624-7a83a3ac611f.png)

**Comment by niksedk** [comment]
This is fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
SE 3.5.11 final should be out soon-ish...

**Comment by alexantr** [comment]
Thanks!
