### ISSUE TITLE
Sub/IDX OCR Conversion, not saving subtitle position on screen.

### ISSUE THREAD

**Issue by RedRain77** [SubtitleEdit/subtitleedit#3801]
whenever I load a SUB/IDX file into Subtitle Edit in order to OCR them and then convert them to ASS it ignores the screen position and just puts everything at the bottom in a jumbled mess.

I have tried a few other programs and have somewhat been able to get it to work but those programs come with their owns problems making yours the best option.

I know that there's an option to change the position of the subtitle but that just gives me the same problem as above but in a different location.

For example, this issue usually starts what two or more characters are talking at once or something in the background is being translated.

Looking through the history of the issues on the git page i've seen that this question has been asked a bunch of times and a few of them were closed, does that mean that this issue has been fixed?

Any help is much appreciated, thank you :)

**Comment by niksedk** [comment]
Latest beta can detect top alignment - can be enabled by right-clicking on the image in the OCR window:
![image](https://user-images.githubusercontent.com/1261331/67138564-b5e72380-f245-11e9-89d5-37bd123a6e65.png)

Positions are really complex and can be messed up easily, so personally I'm not really a big fan of it, but in latest beta TS to SUP can keep positions (it's an option).

Also, if you want me (or others) to take a look, we definitively need some sample files where these positions are present.

And... please don't react to your own posts :)

**Comment by pintassilgo** [comment]
Tried it here with two VobSUB (two different languages) in a 4K video. 

It seems that SubtitleEdit 3.5.14 can only detect top align in one line subtitles. It misses when the subtitle has two lines.

In one language it was two consecutive top subtitles:
_First_: two lines, top alignment not detected by SubtitleEdit;
_Second_: one line, correctly detected.

On the other language, the same sequence had three top subtitles:
_First_: two lines, not detected;
_Second_: one line, detected;
_Third_: two lines, not detected.

I searched the entire result file and there is not a single `{\an8}` in two line subtitle. I can't watch the whole movie, but there are probably other two line top subtitles.

If you need any info or data to test just ask me.
