### ISSUE TITLE
Issue with change casing for selected lines

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3805]
Hi. 3.5.10 NEXT beta 46.
If I use change casing and check "only change all upper case lines", like so:
![se-casing](https://user-images.githubusercontent.com/19672444/67146755-cb386e00-f296-11e9-823a-a4ae1c73e513.png)
Then a line like the following:
`MARK SEALY: It's a huge responsibility when you engage someone with your camera.`
will be changed into this:
`Mark SEALY: It's a huge responsibility when you engage someone with your camera.`
That is, the name casing has been fixed even though the line is not an all-uppercase line.

**Comment by niksedk** [comment]
The "Only change all uppercase lines" only applies to the "normal casing"... I can see this is unclear in the UI!
Hm, any suggestions to how this should work, and how to make it clear in the UI???

**Comment by xylographe** [comment]
I think it should work as @darnn expects. That is what I would expect too. If "Only change all uppercase lines" is enabled, then any line with lower case letter(s) should be skipped completely, i.e. no fixing of name casing should be attempted in those lines.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Thank you!
