### ISSUE TITLE
Font size should accept decimal numbers

### ISSUE THREAD

**Issue by Meivyn** [SubtitleEdit/subtitleedit#3806]
Whenever you open or save a script with a font size set with a decimal, Subtitle Edit displays an error. This should not be the case as ASS subtitles support it.

![image](https://user-images.githubusercontent.com/793322/67153832-858f9b80-f2be-11e9-89a7-369e8493efb7.png)

**Comment by niksedk** [comment]
thx for reporting this :)
Latest beta updated to allow floating point font size: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip (I hope)
