### ISSUE TITLE
[Feature Request] Shortcut to fetch the start of next subtitle and "stick" it to the end of current subtitle.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#3808]
Hello. Thank you for this very rich piece of software. It would be very useful indeed while adjusting subtitles to add a shortcut that would make the start of the next subtitle to be equal to the end of the current subtitle in order to avoid the painstaking task of doing this manually which puts strain on the hand and the eyes of the user.

**Comment by m0ck69** [comment]
That would be cool but according to rules (NETFLIX for instance) there need to be a gap between the end of one subtitle and start of the next one. They can't be equal. So in that case, there should be an option to add frame gap (0 - equal, 1 frame gap, 2 frames gap etc)

**Comment by lambdacore12** [comment]
@m0ck69 they don't have to overlap, one could make them as close to one another as possible, like a 1 ms gap

**Comment by OmrSi** [comment]
Can't you just use "Bridge gap in durations"?

**Comment by lambdacore12** [comment]
@OmrSi "Bridge gap in durations" cannot be used in the beginning of subtitle adjustment because they are yet to be adjusted. It can be used after you might say, but it lacks the option to "divide the gap between texts by 2/3 - 1/3 ratio" which is the one I need (not equal halves).

**Comment by lambdacore12** [comment]
@OmrSi In addition to that, bridging gap in durations does that in bulk, which means it would upset any carefully adjusted duration in accordance with specific char/sec.

**Comment by niksedk** [comment]
What about this shortcut:
![image](https://user-images.githubusercontent.com/1261331/67237012-aedd3280-f44a-11e9-940e-582f7c54fa78.png)

**Comment by lambdacore12** [comment]
Yes. It is the same principle but it would be very helpful if it could be in reverse since we work on subtitles from left to right, and the current subtitle has the priority for adjustment and so, it makes sense to want to make the next subtitle extend to the current one.

**Comment by niksedk** [comment]
So you want to expand length of current subtitle by moving the START time to the END of previous subtitle?

**Comment by lambdacore12** [comment]
No. I want the START of the next subtitle to go back and join the END of the current subtitle. The command would be something like "Pull start of next line to join end of current subtitle".

**Comment by btsix** [comment]
If I got what you mean, you can set a "Min. gap between subtitles in XX ms" in settings, and then when you set the END of the current subtitle, you can "insert a line after" that SE will respect the gap.
![image](https://user-images.githubusercontent.com/47198437/67345429-5e7cd800-f511-11e9-80c4-eaaa9e77c041.png)

**Comment by andradadad** [comment]
> 
> 
> What about this shortcut:
> ![image](https://user-images.githubusercontent.com/1261331/67237012-aedd3280-f44a-11e9-940e-582f7c54fa78.png)

This command isn't working by selecting more than one line in the panel. Could you make it work with more than individual lines?

**Comment by andradadad** [comment]
@niksedk

**Comment by Fhining** [comment]
Hi @niksedk! Hope you're ok. I've been checking this as well and I totally what the initial post is asking. The thing is that there's not a shortcut that allows to edit the end time and start time of the following forcing them to not overlap.

If I can explain my self better, it would be great to have one step more on this shortcut: **set end, next start and go to next** It would be perfect to have this: **set end, add new, next start and go to next**

This will help people to spot only pressing that shortcut (unless they need to adjust something or to retry the spotting on a specific part).

It would be great if this shortcut can be added! :)

**Comment by OmrSi** [comment]
@lambdacore12 Well, now you have this:
![image](https://user-images.githubusercontent.com/20923700/83154964-66d16d00-a109-11ea-8489-c2c5689c1369.png)
Which would do what is required here, but you have to select the next kine to do it and that can be done with the arrows.

As for @Fhining you have:
![image](https://user-images.githubusercontent.com/20923700/83155243-b3b54380-a109-11ea-83b5-acc1a75e6461.png)

**Comment by Fhining** [comment]
> @lambdacore12 Well, now you have this:
> ![image](https://user-images.githubusercontent.com/20923700/83154964-66d16d00-a109-11ea-8489-c2c5689c1369.png)
> Which would do what is required here, but you have to select the next kine to do it and that can be done with the arrows.
> 
> As for @Fhining you have:
> ![image](https://user-images.githubusercontent.com/20923700/83155243-b3b54380-a109-11ea-83b5-acc1a75e6461.png)

If you're spotting on the wave sound or being in the text box this will require additional steps, like going to the list and use the arrows or using a shortcut to move the position of the current subtitle. (Next and previous). This shortcut will do exactly it's job, saving actions for spotting even faster. :)

**Comment by OmrSi** [comment]
Alt + Arrows always work no matter where you are.

**Comment by Fhining** [comment]
Ok so you don't see the convenience of not having to stop the video or pressing other shortcuts to manage this adding just an "add new" to **"set end, next start and go to next"**?

I understand what you propose but that would be a solution while not having that shortcut, right?

The idea for this is to make easier the way people use Subtitle Edit. :)

**Comment by lambdacore12** [comment]
@Omar Si <omrsi97@gmail.com>  Thank you for keeping me updated. Much
appreciated.

**Comment by andradadad** [comment]
> 
> 
> @lambdacore12 Well, now you have this:
> ![image](https://user-images.githubusercontent.com/20923700/83154964-66d16d00-a109-11ea-8489-c2c5689c1369.png)
> Which would do what is required here, but you have to select the next kine to do it and that can be done with the arrows.
> 
> As for @Fhining you have:
> ![image](https://user-images.githubusercontent.com/20923700/83155243-b3b54380-a109-11ea-83b5-acc1a75e6461.png)

This takes a lot of time and so much CPU consumption by working on multiple lines.
But if I fractionate the lines in smaller group numbers, I can get it less than a minute.

Any solution for this?

**Comment by Adam71OFM** [comment]
I’m experiencing the exact same pain here. Subtitle Edit has tons of advanced features (voice detection, Google Translate, OCR, waveform snapping etc.) — yet *still no basic way* to edit the **end of subtitle A** and have the **start of subtitle B** automatically follow when they are adjacent.

This is a **common, everyday need** during fine-tuning: adjust end of A → adjust start of B → review timing. It’s two steps *every single time*. When you do this hundreds of times per video, it adds up.

Please consider adding a simple **“link end → next start” checkbox or mode**. It would save real time and make Subtitle Edit feel *intuitive and responsive* — not forced tedious.

Thanks for all the amazing work — a small change like this would mean a lot to daily users of the app.

**Comment by Fhining** [comment]
> I’m experiencing the exact same pain here. Subtitle Edit has tons of advanced features (voice detection, Google Translate, OCR, waveform snapping etc.) — yet _still no basic way_ to edit the **end of subtitle A** and have the **start of subtitle B** automatically follow when they are adjacent.
> 
> This is a **common, everyday need** during fine-tuning: adjust end of A → adjust start of B → review timing. It’s two steps _every single time_. When you do this hundreds of times per video, it adds up.
> 
> Please consider adding a simple **“link end → next start” checkbox or mode**. It would save real time and make Subtitle Edit feel _intuitive and responsive_ — not forced tedious.
> 
> Thanks for all the amazing work — a small change like this would mean a lot to daily users of the app.

@Adam71OFM, I'm not sure if you found the solution, but I think this is what you're looking for: 

<img width="737" height="385" alt="Image" src="https://github.com/user-attachments/assets/fa769098-33d7-4a23-9c63-4f5d6359dc05" />

Keep the options without the gap cleared and check these one. That's how it works for me.
