### ISSUE TITLE
Re-calculate shortcut overlap.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#3809]
Hello. Thank you so much for SE!
Is possible to make the Re-calculate shortcut overlap the concerned subtitle over other subtitles?
When I use this shortcut and there is the possibility of the current subtitle overlapping another, the shortcut doesn't work and recalculates to an incorrect duration.

**Comment by niksedk** [comment]
Could you explain what happens and what you expected?

**Comment by lambdacore12** [comment]
I expect the current subtitle to recalculate to the Max char/sec I have set in the settings (25 in my case). It works only if the next subtitle is far away enough, but if it is close (meaning the recalculation will make them overlap), the "recalculate" function acts improperly (it make the subtitle go something like 28 or 30).

**Comment by lambdacore12** [comment]
[first subtitle.zip](https://github.com/SubtitleEdit/subtitleedit/files/3750684/first.subtitle.zip)
Take for instance the first subtitle in this file. In order for "recalculate" to work, I need to push the second subtitle further away, or else it won't get to 25. Like the second subtitle is stopping its advance.

**Comment by niksedk** [comment]
Hm, that how SE works... it don't cause overlap.
