### ISSUE TITLE
SMPTE DCP xml subtitle file export has wrong namespace

### ISSUE THREAD

**Issue by jamiegau** [SubtitleEdit/subtitleedit#3812]
The SMPTE DCP export produces XML with the wrong namespace.

xmlns:dcst="http://www.smpte-ra.org/schemas/428-7/2007/DCST"

Should now be at least:
xmlns:dcst="http://www.smpte-ra.org/schemas/428-7/2010/DCST"
Or possibly 2014 as that is the latest revision of that SMPTE standard and schema.
Either way, due to this the DCP created with the XML file this produce will be rejected by many QC companies.

This needs to be fixed.

**Comment by niksedk** [comment]
@jamiegau: You can choose the format in the format dropdown list in the toolbar:
![image](https://user-images.githubusercontent.com/1261331/67427405-5dfd4380-f5dc-11e9-8c6f-3b0753d32abd.png)

2014 just added: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip
