### ISSUE TITLE
error in convert srt and ass to vobsub

### ISSUE THREAD

**Issue by saeid0034** [SubtitleEdit/subtitleedit#3815]
i when try to convert some **srt** and **ass** sub to vobsub get a **fatal error** and program crash
it happen a lot of time

**Comment by niksedk** [comment]
Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

The the error still happens please attach a subtitle that fails (as a zip file) and a screenshot from SE (are you using cmd line convert or ui batch convert or just a simple export?)
