### ISSUE TITLE
Fix common errors problem

### ISSUE THREAD

**Issue by CyberScm** [SubtitleEdit/subtitleedit#3816]
in fix common error settings you can remove the option for renaming numbers like 100 000 to 100000 but even if you untick that option it still convert it from 100 000 to 100000.
how can I get it to stop changing the numbers ?

**Comment by gru123** [comment]
Menu > Options > Settings > Tools >
Uncheck "Fix common OCR errors - also use hard-coded rules"

You must be aware that this will also disable many other rules.

**Comment by OmrSi** [comment]
@niksedk Closed?

**Comment by CyberScm** [comment]
That did the trick, Thank you. 👍
