### ISSUE TITLE
[Feature Request] Always open subtitle chooser, even if there's only one subtitle

### ISSUE THREAD

**Issue by JaySMa** [SubtitleEdit/subtitleedit#3819]
Hello..
Maybe it's already an option, but haven't been able to find it.

When you open the video file (MKV for e.g.) and there's only one subtitle, Subtitle Edit begins to automatically importing the video.

An option in the settings to allow auto-import on one subtitle or not would be nice.  Especially if I'm only looking for the forced subtitles but because I can't confirm there's a force and there's only the full, I have to kill Subtitle edit or let it run its course.

Thank you..

**Comment by niksedk** [comment]
@JaySMa: Could you be more specific... what is "importing the video" and what did you expect?

**Comment by JaySMa** [comment]
Usually, I'll open subtitle edit and drag and drop a MKV over to it.  If there's more than one subtitle available, a box will open and show me the different subtitles available; some are forced subs, some are full, etc.

If there's only one subtitle in the MKV, subtitle edit automatically begins the process of importing the one subtitle without prompting.  If I don't fully know if the video file only has one sub-title and am only looking for a forced sub, I either have to kill subtitle edit or let it do it's full import.

The request would be having the option of subtitle edit showing me that there's only one subtitle and if I wish to import this or not.

Hope this clarifies my request..

**Comment by OmrSi** [comment]
@niksedk He means this:
![image](https://user-images.githubusercontent.com/20923700/79578553-0cd39580-80cf-11ea-886d-50eb97a7d798.png)

He wants it to show up even if there is just one available.
