### ISSUE TITLE
Error message: "Stream is too small" on opening SE

### ISSUE THREAD

**Issue by bowtiedalien** [SubtitleEdit/subtitleedit#3820]
SE is giving me the following error message as soon as I open it. I tried uninstalling and reinstalling but it still gives the same error. 

![image](https://user-images.githubusercontent.com/16901700/67747614-2eb26080-fa3a-11e9-8e4d-8dc00bb210e6.png)

**Comment by xylographe** [comment]
You might try,

- Press **Win+R** to open the Windows Run dialogue.
- Enter  **`%APPDATA%\Subtitle Edit`**, and click OK to open Explorer.
- Delete the **`Spectrograms`** folder, and  the **`Waveforms`** folder.
- Start SubtitleEdit.

**Comment by bowtiedalien** [comment]
> You might try,
> 
> * Press **Win+R** to open the Windows Run dialogue.
> * Enter  **`%APPDATA%\Subtitle Edit`**, and click **OK** to open Explorer.
> * Delete the **`Spectrograms`** folder, and  the **`Waveforms`** folder.
> * Start SubtitleEdit.

Thanks, this does remove the error but now the waveform cursor is moving over the waveform slower than it should, and the mouse cursor sort of glitches twice when I try to pause or start the video. As if the software is heavy for some reason.

**Comment by niksedk** [comment]
Yes, VLC jumps a lot in the waveform as it does not have precise seeking - when VLC Media Player 4.0 is out this should improve.
