### ISSUE TITLE
Can't create waveform, subtitles not displayed on the video

### ISSUE THREAD

**Issue by mindinmedia** [SubtitleEdit/subtitleedit#3821]
The subtitles are no longer displayed below the video. Also, when I try to add time codes to a new project (mp4) and click to add the waveform, this error message is prompted
![waveform-error-subtitle-edit](https://user-images.githubusercontent.com/57176770/67850590-5cb6a400-fb11-11e9-81d4-5ef8f5c33a2a.gif)

.

**Comment by niksedk** [comment]
Could you translate the message to English?

**Comment by mindinmedia** [comment]
> Could you translate the message to English?

Hi Nikolaj, the error message reads: 

"In path C:\Users\Mind...\*.wav use has been prevented."

Then under Stack trace, the word "kohteessa" means "in target" or "in directory".

Hope this helps!

**Comment by niksedk** [comment]
SE needs write access... what happens if you unpack to "C:\Tools\SE" instead?
