### ISSUE TITLE
Binary image compare issue with spell check in the last version

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3824]
Spell check in Binary image compare is asking to check every word in some cases when the word is stuck to an Arabic comma "،" or question mark "؟":
![Screenshot_1](https://user-images.githubusercontent.com/20923700/67967016-8b19a980-fc0d-11e9-9fe8-ca32a9237ad8.png)
![Screenshot_2](https://user-images.githubusercontent.com/20923700/67967018-8b19a980-fc0d-11e9-8af3-ffb3dc62ba26.png)
![Screenshot_3](https://user-images.githubusercontent.com/20923700/67967020-8b19a980-fc0d-11e9-9a08-aa1457f19cb5.png)
![Screenshot_4](https://user-images.githubusercontent.com/20923700/67967021-8bb24000-fc0d-11e9-8a18-42b1a343188a.png)

**Comment by niksedk** [comment]
How is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta3824.zip

(I'm guessing a bit as no sub was attached)

**Comment by OmrSi** [comment]
Here is a test sample, the comma part was solved, the question mark and the "ـ" haven't.
Keep in mind that "ـ" could be connected to any letter, like "لـ" or "بـ" or anything else.
[OCR issue with Arabic.zip](https://github.com/SubtitleEdit/subtitleedit/files/3802369/OCR.issue.with.Arabic.zip)

**Comment by niksedk** [comment]
thx for the file - how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Thank you.
It's better, but it caused another issue.
When you have an unknown word connected to some of the punctuations mentioned above, it asks to correct the whole thing like so:
![4E35F8F0-578E-4BCA-A235-8D47B3E0F5DF](https://user-images.githubusercontent.com/20923700/68209115-5e81db00-ffdb-11e9-8cec-6b4f5d1123fd.png)

**Comment by niksedk** [comment]
How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip ?
If it's not working... could you upload the sub? (or does the above sub contain this line?)

**Comment by OmrSi** [comment]
Still causing issues with "ـ". 
Like "لـ(اسم", the "ـ" can be connected to whatever comes after it, and when it's connected to a '(' it's always showing up as a mistake.

**Comment by OmrSi** [comment]
There is still a problem, even though the spell check doesn't show it, SE is considering them "Unknow words".
So if you have a known word with one of the mentioned punctuations, it will show up with that punctuation in the "Unknown words" section.
And the words that are really unknown and are connected to these punctuations are showing up in the unknown section with the punctuation.
Here, "اسم" is known, but the other word at the last 3 lines are gibberish:
![5E0C5E90-BECB-474C-87F9-E9B3A4B7E936](https://user-images.githubusercontent.com/20923700/68354830-1c10e900-0116-11ea-8fee-f92caef1fad9.png)
Notice that in the word on lines 9 and 12, it only shows the words with the first '('.
It didn't use to happen in the previous version.
[Test.zip](https://github.com/SubtitleEdit/subtitleedit/files/3817660/Desktop.zip)

**Comment by niksedk** [comment]
Is latest beta better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
It seems to be fixed. :D
Thank you so much for putting up with me.

**Comment by niksedk** [comment]
thx for testing :)

Unrelated - do you have any .ts files with Arabic teletext (as SE now supports some...)?
Also, next version will have more "auto br" options - see https://www.nikse.dk/Home/Details/637078432060000000

**Comment by OmrSi** [comment]
@niksedk 
Sadly, I do not work with .ts files. :\

As for the auto break, just wow.
The bottom heavy idea is awesome. I do see it better to have the second line longer.
The comma break is also awesome, I had to add a regex to the do-not-break-after list to do it before but the regex caused SE to always break after the first comma while I only wanted it to not break after one word after comma `، \b\w+\b`
Speaking of which, I hope the Arabic comma and question mark are included in these auto break options. :D
Arabic comma "،"
Question mark "؟"

Also unrelated, was there a hidden shortcut to switch between "HHMMSS" and "HHMMFF"?
I recall "Control + Shift + Alt + F" did that but it isn't working, I might be remembering wrong. ^^"

**Comment by niksedk** [comment]
Arabic comma and question mark are included... now, thx:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

I don't remember any such shortcut...

Let me know if you stumble upon a .ts with Arabic teletext.

**Comment by OmrSi** [comment]
> I don't remember any such shortcut...

@niksedk Found it in the code ^^"
![image](https://user-images.githubusercontent.com/20923700/94873112-f8a20b80-0456-11eb-888a-0c81e71d1a47.png)
