### ISSUE TITLE
Subtitle edit can't read the images OCR

### ISSUE THREAD

**Issue by rookiefromspace** [SubtitleEdit/subtitleedit#3829]
Hello. sorry for bad eng. i have an mp4 file with hardsubbed subtitle. so i scan the subtitles with videosubfinder, then create cleared images as step 2 and i get my clear images at TXTImages folder. and as the final step i opened the subtitle edit and chose import images and added to TXTImages all to the OCR. and chosed none on dictionary, and tesseract 3.0.2 and added turkish language as the last thing to do.
but when i press start OCR everytime i get this error : 
![Adsız](https://user-images.githubusercontent.com/57327902/68090286-ff10b780-fe82-11e9-9e4f-f8ce9399d074.png)

**Comment by niksedk** [comment]
Perhaps a white color works better?

Please attach a subtitle sample if you want a better answer... (pack as .zip and attach)

**Comment by rookiefromspace** [comment]
wdym by white color? do you want some of the images from TXTImages folder az zip?

**Comment by rookiefromspace** [comment]
> Perhaps a white color works better?
> 
> Please attach a subtitle sample if you want a better answer... (pack as .zip and attach)

where can i upload it?

**Comment by niksedk** [comment]
You can delete all lines but a few in the ocr window (select lines in list and and right-click for delete context menu) and right-click in the list again and choose export -> blu-ray sup:
![image](https://user-images.githubusercontent.com/1261331/68090589-b69ecd00-fe75-11e9-9034-960b1b1addfb.png)

Zip the .sup file, and then drop the zip file here...
[sample.zip](https://github.com/SubtitleEdit/subtitleedit/files/3802000/sample.zip)

**Comment by rookiefromspace** [comment]
> You can delete all lines but a few in the ocr window (select lines in list and and right-click for delete context menu) and right-click in the list again and choose export -> blu-ray sup:
> ![image](https://user-images.githubusercontent.com/1261331/68090589-b69ecd00-fe75-11e9-9034-960b1b1addfb.png)
> 
> Zip the .sup file, and then drop the zip file here...
> [sample.zip](https://github.com/SubtitleEdit/subtitleedit/files/3802000/sample.zip)

sir, do you have skype? otherwise im gonna lose my mind. it doesnt work at all no matter what i did or what i watched. i really need you help

**Comment by rookiefromspace** [comment]
> You can delete all lines but a few in the ocr window (select lines in list and and right-click for delete context menu) and right-click in the list again and choose export -> blu-ray sup:
> ![image](https://user-images.githubusercontent.com/1261331/68090589-b69ecd00-fe75-11e9-9034-960b1b1addfb.png)
> 
> Zip the .sup file, and then drop the zip file here...
> [sample.zip](https://github.com/SubtitleEdit/subtitleedit/files/3802000/sample.zip)

it doesnt work either, cant fix it all. i dont know what to do. i watched like 5 videos about this and non of them havs the problem i had.

**Comment by darnn** [comment]
Since I'm interested in this as well, I did this with a random YouTube video and I'm attaching sample image files and the SUP file that SE exports:
[videosubfindersampe.zip](https://github.com/SubtitleEdit/subtitleedit/files/3802082/videosubfindersampe.zip)

**Comment by niksedk** [comment]
For tesseract 3.02 you can right-click in the list view and choose "Image pre-processing" - try invert colors:

![image](https://user-images.githubusercontent.com/1261331/68100209-0f4a8600-fec7-11e9-9ac8-4bcfb451f50b.png)

This option is not available in "Image pre-processing" for tesseract 4... I'll have to look more at this.

**Comment by niksedk** [comment]
Invert colors pre-processing is now available for both Tesseract 3.02 and Tesseract 4: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

**Comment by HerrHulaHoop** [comment]
I had this exact same issue. None of the images from VideoSubFinder worked and it was driving me crazy. Inverting colors with the beta works like a charm. 

Thank you so much for all your work. Can't wait to see this in the next release!
