### ISSUE TITLE
[bug] merge (more than two) lines as one line changes end time

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#3830]
When merging three or more lines, the end time of the resulting line becomes different from that of the original last merged line.

Tested on 3.5.11 beta 24 and 3.5.10.

![merge1](https://user-images.githubusercontent.com/3875423/68109152-2de36800-ff2d-11e9-9a6b-83008a51787f.png)
![merge2](https://user-images.githubusercontent.com/3875423/68109163-32a81c00-ff2d-11e9-9d60-945c03dc0090.png)
![merge3](https://user-images.githubusercontent.com/3875423/68109167-36d43980-ff2d-11e9-858d-e031d0456586.png)

**Comment by niksedk** [comment]
thx for the info - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

**Comment by taxen** [comment]
Checked beta 33 and worked fine!
Thank you!!
