### ISSUE TITLE
fix import with wrong text formatting

### ISSUE THREAD

**Issue by andradadad** [SubtitleEdit/subtitleedit#3831]
Some text tools remove empty lines, thus confusing SE's source fix to wrong formatted texts as:
**(normal text)**
```
1
00:00:12,083 --> 00:00:15,726
text

2
00:00:15,750 --> 00:00:28,892
text

3
00:00:28,916 --> 00:00:33,726
text
text
```

(format SE can't recognize)
```
  1
  00: 00: 12,083  -->  00: 00: 15,726
  text
  2
  00: 00: 15,750  -->  00: 00: 28,892
  text
  3
  00: 00: 28,916  -->  00: 00: 33,726
  text
  text
```

The spaces after ":" are fixed natively, by inputting source text in SubtitleEdit and then simply changing to list view for a save. But the dialog numbers without newlines to separate them, bugs the import leaving the dialog's id as part of the dialog.
Can you fix this? It would help me a lot, and surely many other users as well in the future.

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip
