### ISSUE TITLE
Error 0x800706BA

### ISSUE THREAD

**Issue by wilsonalves00** [SubtitleEdit/subtitleedit#3832]
I'm havving a bit of a problem. Everytime I try to use funciton "Fix common errors" a pop up shows at the screen.

Here's the error. It's in Portuguese

"Error Message:
O Servidor RPC não está disponível .(Exceção de HREsult:0x800706BA)

Stack Trace:
 em
Microsoft.Office.Interop.Word.ApplicationClass.get_ActiveDocument()
 em
NIkse.SubtitelEdt.PLuginLogics.PluginForm.PluginFOrm_FormCLoring(Object sender, FormClosingEventArgs e)
 em
System.Windows.Forms.Form.OnFormClosing(FormClosginEventArgs e)
 em Systema.Windows.Forms.Form.CheckCloseDialog(BooleanclosingOnly)"

**Comment by VaslD** [comment]
Looks like the error is related to some plugin communicating with Microsoft Office. Try  disabling all plugins and re-enable one by one if you can't be sure which works with Office. If you found the erroneous one, you should redirect the issue to plugins project.

Also https://github.com/SubtitleEdit/plugins/issues/172 may help.
