### ISSUE TITLE
OCR: "Ja." turns to "SEN"

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#3833]
Hello

I've been having this problem on several tv shows dvd's in which "Ja." is interpreted at "SEN".
Since "Ja." is a pretty common line of dialogue to have in Danish, it turns up often.

This is the subtitle
![Image16](https://user-images.githubusercontent.com/5127386/68342973-11415e80-00ec-11ea-9ea5-07ba995bd3b4.png)

This is a screenshot of the OCR scan. I'm using 3.5.11
![Udklip](https://user-images.githubusercontent.com/5127386/68342986-18686c80-00ec-11ea-9017-11aaafb77fa2.PNG)

And this is an VobSub extraction .
[Scrubs - s06e11 - My Night to Remember_Subtitles03.DAN.zip](https://github.com/SubtitleEdit/subtitleedit/files/3816988/Scrubs.-.s06e11.-.My.Night.to.Remember_Subtitles03.DAN.zip)

**Comment by niksedk** [comment]
thx for a well explained issue :)
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip
