### ISSUE TITLE
[Feature Request] Blinking Subtitle Edit Icon in Taskbar

### ISSUE THREAD

**Issue by wtester7** [SubtitleEdit/subtitleedit#3837]
Hello Nik, hope you're doing fine :-),

I have a feature request regarding while ocr'ing a subtitle with the option "Prompt for unknown words" enabled when the prompt window will pop up. Is it possible that the Subtitle Edition Icon in your taskbar is blinking until you click on the icon or the prompt window pop up is visible to you?

This is a really great feature if you're multitasking on your computer, it's like an visible reminder,
you will know when the next prompt for unknown words pop up will occur while it's ocr'ing the subtitle...

Best regards
wtester7

**Comment by niksedk** [comment]
Hoes does latest beta work?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by wtester7** [comment]
@niksedk The feature is working great, thank you!! But after a while the blinking will disappear when it's idling. Can you stop the blinking **after** you click on the subtitle edit logo again? When you click on the icon it is like a confirmation to the user, because it is highly possible that the user will miss the notification/blinking when the user is away from the computer. When he returns back he wouldn't know...

**Comment by niksedk** [comment]
Unattended OCR alarm is now customizable (via Settings.xml) and these settings:

        <UnfocusedAttentionBlinkCount>50</UnfocusedAttentionBlinkCount>
        <UnfocusedAttentionPlaySoundCount>2</UnfocusedAttentionPlaySoundCount>
        <UnfocusedAttentionPlaySoundEvery>2</UnfocusedAttentionPlaySoundEvery>

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip
