### ISSUE TITLE
OCR: ... turns to single dot

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#3841]
Hello

This is also an issue i run into a lot of DVD OCR. Some times "..." is interpreted as ".", which also results in the following letter being wrongly uppercased.
Below is an example. "... finde fødselsdagsbarnet." turns to ". Finde fødselsdagsbarnet."

The subtitle:
![Image82](https://user-images.githubusercontent.com/5127386/69044092-971aaf00-09f4-11ea-9492-cfc385f2e9d3.png)

The OCR prompt:
![Udklip](https://user-images.githubusercontent.com/5127386/69044064-879b6600-09f4-11ea-8ddd-ca657feeb2e2.PNG)

The VOBSub:
[Batman The Animated Series - s01e08 - The Forgotten_Subtitles02.DAN.zip](https://github.com/SubtitleEdit/subtitleedit/files/3858110/Batman.The.Animated.Series.-.s01e08.-.The.Forgotten_Subtitles02.DAN.zip)

Here is another example from the same MKV. Here the problem is at the end. "Bare bliv ved at kigge. Så vil jeg ..." turns to "Bare bliv ved at kigge. Så vil jeg ."
![Image81](https://user-images.githubusercontent.com/5127386/69044624-81f25000-09f5-11ea-9001-6b71298fb816.png)

![Udklip2](https://user-images.githubusercontent.com/5127386/69044558-65561800-09f5-11ea-81f6-dd1d8a7ebf54.PNG)

**Comment by niksedk** [comment]
Wrong subtitle in the .zip file?

**Comment by Maitch** [comment]
Yeah, sorry. It was the next episode my example was from. I have the issue in every episode though.
[Batman The Animated Series - s01e09 - Be a Clown_Subtitles02.DAN.zip](https://github.com/SubtitleEdit/subtitleedit/files/3859576/Batman.The.Animated.Series.-.s01e09.-.Be.a.Clown_Subtitles02.DAN.zip)

**Comment by niksedk** [comment]
I think this is an issue for https://github.com/tesseract-ocr/tesseract
I've added some "pre-processing" in latest beta which seems to work with the dots, but that creates other issues (Set scaling to something like 200%).

If you're working on multiple image based subs with the same font I would definitively recommend "Binary image compare"... will take a bit longer for first sub, the the results should be be better then Tesseract.
