### ISSUE TITLE
subtitle error report when opening srt not working in latest version

### ISSUE THREAD

**Issue by hani-yassine** [SubtitleEdit/subtitleedit#3846]
latest version error reporting not working, such as if we have a line :
2400:00:09,289 --> 00:00:11,958 
something
(it should be)
24
00:00:09,289 --> 00:00:11,958
something
in latest version it doesnt report this error i had to roll back to version 5.3.9 where it report error like that 
![Capture](https://user-images.githubusercontent.com/39760468/69464146-38ec2400-0d86-11ea-9c3c-3b86230cfeaa.PNG)

**Comment by niksedk** [comment]
I cannot re-produce this with 3.5.9... could you attach the subtitle?

**Comment by niksedk** [comment]
Fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

**Comment by hani-yassine** [comment]
> Fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

hello i tried the latest version you linked it doesn't seem to be working in version 3.59 it warn me about the error like the pic below and re number the subtitle lines in the latest version it dont warn me keep the error and dont re-number i will leave the test srt i used for testing 
![test5](https://user-images.githubusercontent.com/39760468/69676280-12412c80-10a9-11ea-8970-27940535cf15.PNG)


[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/3894176/test.zip)
thanks :)

**Comment by xylographe** [comment]
That beta does not yet include commit 1f0b1d85eed1996bb19608d02446ae71dce0c90a.

Try **`SE-3.5.11.126.7z`** from [this DropBox folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0).
