### ISSUE TITLE
[Feature Request] Preserve folder structure / path in GUIs batch convert tool

### ISSUE THREAD

**Issue by mgutt** [SubtitleEdit/subtitleedit#3847]
If you use Tools -> Batch convert... it saves all converted files into the root of the output folder. It would be nice if it would save them in the subdirectories where it found the different source files.

**Comment by xylographe** [comment]
Isn't that supposed to happen if you leave the output folder undefined?

**Comment by mgutt** [comment]
You mean this setting? But doesn't it delete the source file?
![2019-11-23 11_47_38](https://user-images.githubusercontent.com/10757176/69477483-1fc78f80-0de7-11ea-83a8-236e351599ce.jpg)

**Comment by xylographe** [comment]
Yes, that option would delete the original file. However, I was thinking of the **`CommandLineConverter.FormatOutputFileNameForBatchConvert`** method, which determines the output file path:
```c#
internal static string FormatOutputFileNameForBatchConvert(string fileName, string extension, string outputFolder, bool overwrite)
{
    string outputFileName = Path.ChangeExtension(fileName, extension);
    if (!string.IsNullOrEmpty(outputFolder) && Path.GetFileName(outputFileName) != null)
    {
        outputFileName = Path.Combine(outputFolder, Path.GetFileName(outputFileName));
    }
    if (!overwrite && File.Exists(outputFileName))
    {
        outputFileName = Path.ChangeExtension(outputFileName, Guid.NewGuid() + extension);
    }
    return outputFileName;
}
```
The **`fileName`** parameter contains the input file path. As you can see the **`outputFolder`** parameter is not used if it is empty. In that case the location of the output file will be the same as the location of the input file. Hence, if you leave the "Ausgabeordner wählen" field empty, each output file should be saved in the location (folder) where its input file was found.

**Comment by mgutt** [comment]
It's not possible to leave the output folder empty:
![2019-11-25 00_12_28](https://user-images.githubusercontent.com/10757176/69503295-8bf5e080-0f18-11ea-8b17-6bec1203c930.jpg)

But my problem is solved anyway. I thought it would delete the source file in any case. But it really means only if the output has the same file extension.  As I'm converting from SUP to SRT this does not happen so the source is untouched. The english translation of Subtitle Edit is a little bit more clear in this point but still a confusing as its talking about "original files" and "new extension if format is changed":
![2019-11-25 00_20_49](https://user-images.githubusercontent.com/10757176/69503389-85b43400-0f19-11ea-8070-aabf0351e4a0.jpg)

Maybe someone should change this settings so they become more clear:

```
---Output-----------------------------------------
( ) preserve input folder structure
    [ ] overwrite existing files (does not overwrite source files if output format / extension changes)
OR
( ) Choose output folder:
    [__________________________]  [ ... ]
    [ ] overwrite existing files
-----------------------------------------------------
```

**Comment by xylographe** [comment]
I think, it would be best to remove the unnecessary "Overwrite original files" option. The "output folder" field should determine the location of the output files: either a chosen folder or the location of the input file if empty. The "Overwrite existing files" option is independent of location.
```
---Output-----------------------------------------
 Choose output folder:
 [__________________________]  [ ... ]
 [ ] Overwrite existing files
----------------------------------------------------
```
Empty "output folder" and "overwrite existing files" enabled will be the same as the former "overwrite original files".
Empty "output folder" and "overwrite existing files" disabled will do what is currently not possible: save output file in folder of input file without overwriting an existing file, which seems to be a very reasonable modus operandi in the absence of a version control system.

**Comment by mgutt** [comment]
Of course. This would be a solution, too. But then the word "optional" should be added:
---Output-----------------------------------------
 Choose output folder (optional):
 [__________________________]  [ ... ]
 [ ] Overwrite existing files
----------------------------------------------------
Or some people probably think they **must** select an output folder.

**Comment by niksedk** [comment]
So it's these two options we have?

![image](https://user-images.githubusercontent.com/1261331/69565228-cdd46480-0fb4-11ea-881a-a7cc9d2a48ed.png)

![image](https://user-images.githubusercontent.com/1261331/69565425-3cb1bd80-0fb5-11ea-8ace-0ba483c1d054.png)

**Comment by xylographe** [comment]
I would prefer the second: overwriting existing files is not related to the save location.

**Comment by mgutt** [comment]
Both are ok.

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip ?

**Comment by xylographe** [comment]
![se-batch-conversie](https://user-images.githubusercontent.com/8535293/69573572-ab4b4700-0fc6-11ea-8975-4cae37e843ff.png)

**Comment by mgutt** [comment]
Looks nice
![2019-11-26 00_44_54](https://user-images.githubusercontent.com/10757176/69587486-fd4f9500-0fe5-11ea-8bae-d4b4b3b2f559.jpg)

**Comment by xylographe** [comment]
Looking good!

![se-batch-conversie](https://user-images.githubusercontent.com/8535293/69601971-3b64ad00-1016-11ea-8fd3-b09db8d5e0b2.png)
