### ISSUE TITLE
[Feature Request] Find/Replace in Import/OCR VobSub Window

### ISSUE THREAD

**Issue by splerman** [SubtitleEdit/subtitleedit#3848]
After performing an OCR, I manually review line-by-line comparing the recognized text against the subtitle image. I often find repeats of the same error. It would be very helpful to have a find/replace function available inside the Import/OCR VobSub window while the subtitle image is still available. I believe the only way to access find/replace is to close the Import/OCR window, after which the subtitle images are no longer available. Am I missing a better way to do this or would this suggested feature improve workflow?

Thanks for an incredible product!!

**Comment by niksedk** [comment]
You should probably add your error fixes to the `eng_OCRFixReplaceList_User.xml` (if you're using English).
If you prefer to fix stuff after the OCR, then "Edit -> Multiple replace" should work well for you (build a library of your own fixes).

A few hints:

- I normally use "Ctrl+G" (Go to line number) a lot to find a line.
- You can also open the image sub again, and then right-click in the list view and import (Import text with matching time codes) your already ocr'ed srt file again.

You can export both texts and images by right-clicking in the list view and choose "Save all images with html index" - nice for reviewing.

Tesseract OCR is the easy way, but Binary Image Compare can give the best results, but it's harder to learn.
