### ISSUE TITLE
Listview problem

### ISSUE THREAD

**Issue by AlexandreMT** [SubtitleEdit/subtitleedit#3849]
Listview is not working well, the size and informations are weird. If I hide one of the columns and show it again, the problem is temporarily fixed.

![image](https://user-images.githubusercontent.com/25598649/69502402-9ea6f000-0eed-11ea-9354-1aece1aec905.png)

I'm using the latest beta version.

**Comment by niksedk** [comment]
Works fine here... a special sub?

**Comment by AlexandreMT** [comment]
It's not the sub. The problem occurs when I open SE, before I load any subtitle. I already deleted SE and downloaded again, but the problem is still there. 

You can see the problem here: https://drive.google.com/open?id=1iquoTOQU4cfJdDOQZQsQki2JG_-7PWaM

**Comment by AlexandreMT** [comment]
It's not the sub. The problem occurs when I open SE, before I load any subtitle. I already deleted SE and downloaded again, but the problem is still there.

You can see the problem here: https://drive.google.com/open?id=1jLwQn0_Li5E34kiRYG7DWg-ruE6Qof63

**Comment by xylographe** [comment]
Seems to happen as well if all list-view columns are enabled.

**Comment by niksedk** [comment]
thx for the info guys :)
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip
