### ISSUE TITLE
[Feature Request] Batch convert... > Filename contains...

### ISSUE THREAD

**Issue by mgutt** [SubtitleEdit/subtitleedit#3855]
I have exported all subtitles of all my video files and now in a first step I only want to convert the forced subtitles. But Subtitle Edit sadly misses an option to filter by filename:
![2019-11-28 21_29_57](https://user-images.githubusercontent.com/10757176/69830691-3c6c2900-1226-11ea-90eb-03c3d3422215.jpg)

I solved that by searching for those files through the Windows Explorer and pasted the search results into the Batch conversion tool, but maybe you could add this as an internal feature.

**Comment by OmrSi** [comment]
@niksedk I have sent you an email about this but it might be better to write it here.
If I understand this, the files containing what you write should be skipped?
![image](https://user-images.githubusercontent.com/20923700/74253749-28e63f80-4cf8-11ea-832d-4f0a9d62259e.png)

Also, Let's say I have two files with embedded subtitles in multiple languages and I want to filter just the ones from my language, which is Arabic.  what would I do if I want to filter just the "ara" from the formats?
![image](https://user-images.githubusercontent.com/20923700/74253972-7b276080-4cf8-11ea-9041-8b532088966b.png)

**Comment by OmrSi** [comment]
@niksedk Okay, I get now that it only works for "Scan".
But my second question remains, how can I go about selecting only "ara" from Format?
I can't even sort them by Format so I can delete the rest...
