### ISSUE TITLE
Split long lines in batch convert (3.5.10~11 also don't work right.)

### ISSUE THREAD

**Issue by xmrea** [SubtitleEdit/subtitleedit#3858]
Split long lines in the Tools menu is not the same as Split long lines in batch convert.

After version 3.5.9, split long lines in batch convert is similar to auto balance lines.
Even short lines are split.

Please change it back to v3.5.9.

Thanks...

**Comment by niksedk** [comment]
Thx, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip ?

How does it work now?

**Comment by xmrea** [comment]
> Thx, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip ?
> 
> How does it work now?

thanks, it works as it should 👍

**Comment by niksedk** [comment]
@xmrea: thx for verifying :)
