### ISSUE TITLE
Bulk waveform generation

### ISSUE THREAD

**Issue by ThiefMaster** [SubtitleEdit/subtitleedit#386]
It would be nice to have a tool to extract the waveform data for multiple videos in one go. When resyncing an entire season it's quite annoying to wait a minute or two for the waveform data after each episode.

**Comment by niksedk** [comment]
Fixed in 3.4.6 :)
In the "Video" menu... "Batch generate waveforms..."

**Comment by ThiefMaster** [comment]
Thanks! Dropping mkv files on the panel doesn't work though

**Comment by niksedk** [comment]
thx - should be fixed in this commit - https://github.com/SubtitleEdit/subtitleedit/commit/ac85ef8eae3d18a3c348c235aa57e1546a396e5c
