### ISSUE TITLE
OCR's Prompt for unknown words isn't saved over sessions

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3863]
It's really annoying to have to set them each time, is there a way to add them to the settings file?

**Comment by niksedk** [comment]
It's remembered here... vobsub files have a separate settings as they often are smaller.

**Comment by OmrSi** [comment]
"Prompt for unknown words" resets every time I open a session even in the latest beta.

"No. of pixels is space" is saved, I think it didn't use to or maybe I got it wrong.

**Comment by niksedk** [comment]
OK, remembering "Prompt for unknown words" was not working for "binary image compare" (or after batch convert)... beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
@niksedk I found it.
When you open an xml\png subtitle, No. of pixels is space always resets to 11.

**Comment by OmrSi** [comment]
@niksedk It seems that `No. of pixels is space` still resets to 11.
