### ISSUE TITLE
OCR a turkish empty image returns "TARRRRRRRRRR..."

### ISSUE THREAD

**Issue by mgutt** [SubtitleEdit/subtitleedit#3868]
It returns:

> TARRRRRRRRRRURRRRRRRRRRRRRRRRRRRRRRRRKRRRRKKKKKUKKUKUKUKUUÇ

![2019-12-04 14_19_06](https://user-images.githubusercontent.com/10757176/70145879-5a5fe080-16a1-11ea-96cc-ed20842534a9.jpg)

(Tesseract 4.1.0, Turkish, Turkish Dictionary)

If I use the batch conversion tool it returns:
`<i>%</i>`

![2019-12-04 14_22_22](https://user-images.githubusercontent.com/10757176/70145956-83807100-16a1-11ea-98a2-fd29fbcb65cd.jpg)

**Comment by niksedk** [comment]
Not really a SE issues as SE just uses Tesseract

**Comment by mgutt** [comment]
Ok, but as I used the Batch conversion directly after the manual conversion, shouldn't be both results the same?
