### ISSUE TITLE
Is "Fix OCR Errors" the same as "Fix Common errors" in OCR Scan?

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#3871]
Hello

I have some OCR issues with two lines being interpreted as one line. An example could be 
`- Hi John! - Hi Ida!`, which of course should be 
`- Hi John!<br /> - Hi Ida!`

Now, I can fix this by running the subtitles through the "Fix Common Errors" dialog, but it does not seem to get fixed by "Fix OCR errors" in the OCR dialog.

So my question is:  Is "Fix OCR Errors" the same as "Fix Common errors" in OCR Scan?

And if no, could it be possible to have as part of the OCR scan.

![Udklip](https://user-images.githubusercontent.com/5127386/70246455-14c21700-1778-11ea-8d17-7dd228093a33.PNG)
![Udklip2](https://user-images.githubusercontent.com/5127386/70246456-14c21700-1778-11ea-835c-db64f01a119b.PNG)

**Comment by niksedk** [comment]
No, "Fix OCR Errors" is not the same as "Fix Common errors". "Fix common errors" is has many other options besides "Fix OCR errors".

Could you attach an image based file with the problem?

**Comment by Maitch** [comment]
Here is a case for you:

![Image100](https://user-images.githubusercontent.com/5127386/70706007-5f421700-1cd5-11ea-9e3f-432e100d3cd1.png)
![Udklip](https://user-images.githubusercontent.com/5127386/70705969-4e91a100-1cd5-11ea-931f-796186e377dc.PNG)

VobSub:
[Batman The Animated Series - s01e01 - On Leather Wings_Subtitles02.DAN.zip](https://github.com/SubtitleEdit/subtitleedit/files/3955296/Batman.The.Animated.Series.-.s01e01.-.On.Leather.Wings_Subtitles02.DAN.zip)

**Comment by niksedk** [comment]
Works fine for me... what version of SE are you using?

![image](https://user-images.githubusercontent.com/1261331/70745182-92ab9280-1d23-11ea-9600-2675f9cd28cc.png)

**Comment by Maitch** [comment]
Strange.
Originally, I used a beta for next version, but I have also try to downgrade to 3.5.11 with the same result.
Then I tried emptying my OCRFixReplace_User.xml entirely to see if that resulted in the error, but it did not change anything.
