### ISSUE TITLE
A bug in "Go to previous subtitle from video position"

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3872]
If video position is after the last line, "Go to previous subtitle from video position" doesn't work.

**Comment by OmrSi** [comment]
@niksedk 
Beta after for this?
Or better yet, @xylographe can you tell me how to compile a beta?
I already have VS, but when I try to compile it, I get extra files than the ones in the normal beta, also the build number becomes 9999 or something...

**Comment by xylographe** [comment]
@OmrSi
Download **`Build-SubtitleEditBeta.ps1`** from [this DropBox folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0). Read the _Notes_ and _Description_ sections at the top of the file. After modifying your PowerShell profile (as explained in the _Notes_) it's as simple as running `Build-SubtitleEditBeta -Verbose -Master`.

**Comment by OmrSi** [comment]
@xylographe Thank you.
I still get "powershell cannot be loaded is not digitally signed" even after doing the `Set-ExecutionPolicy -Force -Scope CurrentUser -ExecutionPolicy RemoteSigned` and it shows `CurrentUser    RemoteSigned`

**Comment by xylographe** [comment]
About ExecutionPolicy, I suspect that your download software has blocked the file. Firefox, Chrome and most other browsers will do that. I use FDM to avoid the problem. You can open the file's Properties window in Explorer, or use Unblock-File in PowerShell:
```
Unblock-File -Verbose -LiteralPath ~\Documents\WindowsPowerShell\Build-SubtitleEditBeta.ps1
```

To create the Beta zip-archive, files from different locations are copied to a temporary directory, and subsequently archived by 7-Zip: (from `build.bat`)
```
ECHO Creating ZIP archive with 7-Zip...
PUSHD "src\bin\Release"
IF EXIST "temp_zip"                  RD /S /Q "temp_zip"
IF NOT EXIST "temp_zip"              MD "temp_zip"
IF NOT EXIST "temp_zip\Languages"    MD "temp_zip\Languages"
IF NOT EXIST "temp_zip\Dictionaries" MD "temp_zip\Dictionaries"
IF NOT EXIST "temp_zip\Ocr"          MD "temp_zip\Ocr"
ECHO.
COPY /Y /V "..\..\..\LICENSE.txt"      "temp_zip\"
COPY /Y /V "..\..\..\Changelog.txt"    "temp_zip\"
COPY /Y /V "Hunspellx86.dll"           "temp_zip\"
COPY /Y /V "Hunspellx64.dll"           "temp_zip\"
COPY /Y /V "SubtitleEdit.exe"          "temp_zip\"
COPY /Y /V "Languages\*.xml"           "temp_zip\Languages\"
COPY /Y /V "..\..\..\Dictionaries\*.*" "temp_zip\Dictionaries\"
COPY /Y /V "..\..\..\Ocr\*.*"          "temp_zip\Ocr\"
PUSHD "temp_zip"
START "" /B /WAIT "%SEVENZIP%" a -tzip -mx=9 "SubtitleEdit-%VERSION%.zip" * >NUL
```
If you install 7-Zip, Build-SubtitleEditBeta will build a similar archive (without the English Hunspell dictionary, and using 7z i/o zip archive format).

**Comment by OmrSi** [comment]
Do I have to add anything other than `Build-SubtitleEditBeta -Verbose -Master`?
I have 7-zip and InnoSetup installed, but neither is created.

**Comment by xylographe** [comment]
The directory that contains `7z.exe` (or `sevenz.exe`) must be included in the PATH environment variable. Either in the Registry (inherited by PowerShell), or in a PowerShell profile (`$PROFILE.CurrentUserAllHosts` or `$PROFILE.AllUsersAllHosts`). Same for the directory that contains `ISCC.exe`.

**Comment by OmrSi** [comment]
Ah. Thank you. The zip part worked.
The setup file is giving:
`Error on line 407 in ...\Desktop\subtitleedit-master\installer\Subtitle_Edit_installer.iss: [ISPP] File not found: "...\Desktop\subtitleedit-master\installer\..\src\bin\Release\Resources.h".`

The is another error above that:
`...\Desktop\subtitleedit-master\src\Win32Resources\Win32Resources.vcxproj(19,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default
.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

**Comment by xylographe** [comment]
Check "Installed products" ("About Microsoft Visual Studio") for "Visual C++ 2017".
AFAIK `VC\VCTargets\Microsoft.Cpp.Default.props` is part of Visual C++ 2017.

**Comment by OmrSi** [comment]
`VC\VCTargets\Microsoft.Cpp.Default.props` exsists.

**Comment by xylographe** [comment]
Try,
```
Get-Item -Path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\*.props'
Get-Item -Path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default.props'

```

**Comment by OmrSi** [comment]
It's my bad, I haven't added enough features because I don't use VS often.

**Comment by xylographe** [comment]
If you add "VC++ 2017 version 15.9" with the Visual Studio Installer, it will work.

**Comment by xylographe** [comment]
If you install "VC++ 2015.3 v14.0 (v140)" with Visual Studio Installer, it will work.

**Comment by OmrSi** [comment]
I installed it properly last night, now I get:
```
Error on line 92 in ...\subtitleedit-master\installer\Subtitle_Edit_installer.iss: Minimum NT version specified by MinVersion must be at least 6.0. (Windows 2000/XP/Server 2003 are no longer supported.)
Compile aborted.
```

**Comment by niksedk** [comment]
Perhaps you need an older version of Inno setup: http://files.jrsoftware.org/is/5/innosetup-5.6.1-unicode.exe
SE has not been updated to support version 6.x yet.

**Comment by OmrSi** [comment]
Yeah, that was it.
It works now, no more asking for betas. xD
Thank you both.

**Comment by OmrSi** [comment]
@niksedk Still doesn't work like this:
![image](https://user-images.githubusercontent.com/20923700/70764345-feabec00-1d5f-11ea-903e-bccf6b8dd630.png)
It's supposed to go to the beginning of the line.

**Comment by OmrSi** [comment]
@xylographe What's wrong?
![image](https://user-images.githubusercontent.com/20923700/86521809-1e227780-be5e-11ea-95a2-e617bb78d7c7.png)

**Comment by OmrSi** [comment]
Seems like the new design changes the hash position so it's not matching it anymore.
