### ISSUE TITLE
download dictionnary

### ISSUE THREAD

**Issue by ManuNice** [SubtitleEdit/subtitleedit#3874]
Hi

i try to download a dictionnary but this happen : 
subtitle edit stack trace à Nikse.Subtitle.Core.ZipExtractor.Open(Stream stream) à Nikse.SubtitleEdit.Forms.GetDictionaries.wc_DownloadDataCompleted(Object sender, DownloadDataCompletedEvenArgs e) à System.Ney.WebClient.OnDownloadDataCompleted(DownloadDataCompletedEvenArgs e)

what can i do ?

**Comment by niksedk** [comment]
What dictionary?

**Comment by niksedk** [comment]
All dictionaries verified... be sure you have latest version SE and/or retry a few times.
