### ISSUE TITLE
Q: Select text in waveform view by single click

### ISSUE THREAD

**Issue by X-Raym** [SubtitleEdit/subtitleedit#3884]
Hi,

DO I miss something obvious here ?

I need to double click to select (make red) a text/line in waveform view.

I can right click to instant select but this will open a contextual window.

How can I select text in waveform view with single left click ?

Thx !

**Comment by LeonCheung** [comment]
Congrats, you are at least the 4th one to touch this topic. It might have already been on someone's TODO list I bet.  :-}
#2928 
#2990 
#3780

**Comment by X-Raym** [comment]
You are totally right !

For my defense:

* #2928 is closed
* #3780 title doesnt reflect that the feature is about waveform view
* #2990 title doesnt reflect that it is about single click (the answer could have simply been "double click")

But I can close if you think it is redundant :)

**Comment by OmrSi** [comment]
#2928 is closed because it's repeated. I referenced it to another one with the same demand.

**Comment by m0ck69** [comment]
Many people asked for this. Any update on the issue?

**Comment by OmrSi** [comment]
Yep. It's implemented. @niksedk Should be closed.
![image](https://user-images.githubusercontent.com/20923700/79579079-c894c500-80cf-11ea-8a3b-21464be35c9d.png)

**Comment by crisc82** [comment]
For those who have searched for this options for 5 minutes (like me)
Menu => Options => Settings => Waveform/spectogram

p.s. this should be selected by default

**Comment by crisc82** [comment]
> 
> 
> For those who have searched for this options for 5 minutes (like me)
> Menu => Options => Settings => Waveform/spectogram
> 
> p.s. this should be selected by default



> 
> 
> Yep. It's implemented. @niksedk Should be closed.
> ![image](https://user-images.githubusercontent.com/20923700/79579079-c894c500-80cf-11ea-8a3b-21464be35c9d.png)

For those who have searched for this options for 5 minutes (like me)
Menu => Options => Settings => Waveform/spectogram

p.s. this should be selected by default
