### ISSUE TITLE
FR: Continuous edge editing with mouse

### ISSUE THREAD

**Issue by X-Raym** [SubtitleEdit/subtitleedit#3885]
Hi,

Currently, edge editing isn't possible in waveform view.

We can only start and end, but not continuous points of juxtaposed items. (end of first item and start of next one, one after each other)

This feature is seen in many editing program.

![img](https://i.imgur.com/mOb53aZ.gif)

This will be nice to have.

Thx !

**Comment by OmrSi** [comment]
Well, what about this?
`Holding down ALT when moving start/end will move nearest subtitle start/end too if it's closer than 500 milliseconds - [like this](https://www.nikse.dk/Content/SubtitleEdit/WaveformMoveNextPrev.gif).`

You can view those [here](https://www.nikse.dk/SubtitleEdit/Help#waveform).

**Comment by X-Raym** [comment]
@OmrSi Oh thanks this could help !

I wish it could it be the default behavior with a toggle in option settings,
Cause for me it is the expected behavior as it is what happen in all my editing software both audio and video.

**Comment by X-Raym** [comment]
@niksedk has this been integrated in new release ?

**Comment by niksedk** [comment]
Nope, sorry. It's a `Won't fix`...

**Comment by X-Raym** [comment]
@niksedk oh ok. Can you add a Wont Fix label to this issue then ? So I can keep track of my requests status ;)
