### ISSUE TITLE
While in text editor, Control+Delete removes whole line in Windows 7 but one word in Windows 10.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#3886]
I work with SE on two computers, one on win7 and another on win10.
While in the text editing box, when I press Ctrl+Delete, it behaves in two different ways:
1- In win7, it deletes the whole line.
2- In win10, it deletes only the next word.

**Comment by OmrSi** [comment]
Ah, I missed the `text editing box` part before, sorry about that.
If you open a normal notepad on Win7 and use `Ctrl+Delete`, what does it do?

**Comment by lambdacore12** [comment]
It deletes the whole line.

**Comment by OmrSi** [comment]
Exactly, it seems to be a Windows behavior, not related to SE.
We'll leave the final word to @niksedk
