### ISSUE TITLE
A bug in "Fetch first word from next subtitle"

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3887]
If the second line had a tag with a space, it would fetch part of the tag that is before the space.
```
AAAAA BBBB CCCCC DDD EEE

{\an8\fnArabic Typesetting\fs34}FFF GGGG
```
Becomes:
```
AAAAA BBBB CCCCC DDD {\an8\fnArabic

Typesetting\fs34}EEE FFF GGGG
```

**Comment by OmrSi** [comment]
@niksedk It's still happening with HTML tags:

```
Hey

<font color="#000000" size="63">You. How are you?</font>
```

Becomes:
```
Hey You. <font

color="#000000" size="63">How are you?</font>
```

And then:
```
Hey You. <font color="#000000"

size="63">How are you?</font>
```

And so on...

**Comment by OmrSi** [comment]
@niksedk How about this? https://github.com/OmrSi/subtitleedit/commit/05feff1d4648f95da5cfafadc5ed6c753cae05ea

**Comment by OmrSi** [comment]
@niksedk Can you check on this? 

And Merry Christmas. 😁

**Comment by niksedk** [comment]
Merry Christmas :)

When moving words down (using `Hey You. <font color="#000000" size="63">How are</font> you?`) I got this:
![image](https://user-images.githubusercontent.com/1261331/71482373-897df380-2802-11ea-8eef-a088d1124037.png)

**Comment by OmrSi** [comment]
Well, yeah.
I didn't fix all cases, this behavior exists in the original version as well.
What I mean this, what I did fixes some cases but doesn't cause others.

**Comment by OmrSi** [comment]
The problem with moving words down is that you used to check if the line starts with a tag, but you needed to check if the last line does.
Here, you need to check if the last word is the only word in the tag, I don't think I know how to do that.

The same thing happens with moving words between lines, but that makes sense because when you move a word between lines, the tags have to follow.

**Comment by OmrSi** [comment]
This also fixes a problem you had with deleting `</font>` if one word is left.
It used to be deleted even if one word is left, now it's only deleted when no words exist.

**Comment by niksedk** [comment]
@OmrSi: I've moved the logic to a new class called `MoveWordUpDown.cs` as the logic actually is pretty complex. Also, I've added unit tests to make it stable hopefully... but I'm pretty sure that it does not handle all situations ATM, so feel free to add unit tests or/and code :)

**Comment by OmrSi** [comment]
It seems to be working well. :D
If I face something I can solve, I will add it.
Thank you. :)
