### ISSUE TITLE
Feature request - Final Check

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3888]
Hello,
This request is more or less like a feature like Netflix Quality Check for all subtitle formats.
In Caption Maker we have it like this:
![Untitled](https://user-images.githubusercontent.com/28671050/70768953-59a60900-1d89-11ea-9542-c9d53869e26a.jpg)
A similar window with options like Max time, Min time, No. of lines, Chars per line, illegal characters (an editable list) , Min display time b/w subtitles, etc. 
We can add more options if requested by others.
I know SE does all of these things and gives color alerts for, say, exceeding line length, but you have to  scroll through the file to find these. It would be nice to have them all in one place.
Caption Maker auto fixes these errors one by one.
Once an error is found, it asks you:
![ddddd](https://user-images.githubusercontent.com/28671050/70769221-7a229300-1d8a-11ea-82b6-7b79f3bc3eea.jpg)
Then it will go to the next. Maybe auto-fixing is too much to ask, so let's just stick with finding errors for now.
How does it sound?

**Comment by OmrSi** [comment]
Isn't this like "Fix common errors"?

**Comment by uckthis** [comment]
@OmrSi , Nope. Those are two totally different things.

**Comment by niksedk** [comment]
"Fix common errors" should be this...
