### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by j0boelaert** [SubtitleEdit/subtitleedit#3889]
Each time I start Subtitle Edit, I get this message:

Error Message:
Access to C:\Program Files\Subtitle Edit\Spectrograms is denied.

Stack Trace:
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   bij System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   bij System.IO.Directory.CreateDirectory(String path)
   bij Nikse.SubtitleEdit.Core.WavePeakGenerator.SpectrogramDrawer.GetSpectrogramFolder(String videoFileName)
   bij Nikse.SubtitleEdit.Forms.Main.OpenVideo(String fileName)
   bij Nikse.SubtitleEdit.Forms.Main.Main_Shown(Object sender, EventArgs e)
   bij System.Windows.Forms.Form.OnShown(EventArgs e)
   bij System.Windows.Forms.Form.CallShownEvent()
   bij System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   bij System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   bij System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bij System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   bij System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by xylographe** [comment]
It looks like you unpacked (in an elevated process) SE portable in `C:\Program Files\Subtitle Edit`. Now you are running SE without elevation, therefore SE no longer has write-access to `C:\Program Files\Subtitle Edit`, and fails to create the `C:\Program Files\Subtitle Edit\Spectrograms` folder.

Either install SE with the SE installer (then data like Spectograms will be stored under `%APPDATA%\Subtitle Edit`) or unpack SE portable under `%USERPROFILE%` (e.g. C:\Users\Me\Programs\Subtitle Edit`).

**Comment by j0boelaert** [comment]
Thanks, that's it!
