### ISSUE TITLE
[Bug] Change frame rate... - wrong formula

### ISSUE THREAD

**Issue by gru123** [SubtitleEdit/subtitleedit#3890]
First of all, I want to thank you for the SE, it's great tool.

But I've noticed a bug. The program incorrectly calculates the new times when changing the frame rate.
For example, when changing from 25 to 23.976, it's using this formula:

`time_23976 = time_25000 * 25/23.976;`

But 23.976 fps is not 23.976 when it comes to math. In fact, it's 24000/1001, or 24/1.001 if you like. And 29.97 is 30000/1001.
So the correct formula looks like this:

`time_23976 = time_25000 * 25/(24000/1001);`

The difference between 25/23.976 and 25/(24000/1001) is 1/959040. I know it's a small number, but not zero.

Example (test_25fps.srt):
```
1
01:00:00,000 --> 02:00:00,000
Test
```
Converted in SE (test_23.976fps_SE.srt) - tested with the latest beta:
```
1
01:02:33,754 --> 02:05:07,508
Test
```
And this is how the converted file should look (test_23.976fps_proper.srt):
```
1
01:02:33,750 --> 02:05:07,500
Test
```
The drift is circa 4 milliseconds after one hour (for 25>23.976).

You can look at MKVToolNix to check the correct FPS values.
![SE](https://user-images.githubusercontent.com/42896067/70919941-0c909400-2022-11ea-8598-9938683ca324.png)

**Comment by niksedk** [comment]
Thx, it's not a lot of drift... but it's more than I though it would be.
How is this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

**Comment by gru123** [comment]
Something is still wrong. I think you changed the numerator with the denominator.
test_25fps.srt:
```
1
01:00:00,000 --> 02:00:00,000
Test
```
test23976_SE_Beta.srt:
```
1
00:57:32,547 --> 01:55:05,095
Test
```

**Comment by xylographe** [comment]
```
PS > $ts = [timespan]::FromHours(1); "${ts}"
01:00:00
PS > "$([timespan]::FromMilliseconds([decimal]::Round(($ts.TotalMilliseconds * 25D * 1001D) / 24000D, [System.MidpointRounding]::AwayFromZero)))"
01:02:33.7500000
```

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip
