### ISSUE TITLE
Open files from NAS (although 10G) is really slow

### ISSUE THREAD

**Issue by mgutt** [SubtitleEdit/subtitleedit#3893]
This is the usual read speed of Subtitle Edit:
![2019-12-20 00_46_27](https://user-images.githubusercontent.com/10757176/71218822-416f4600-22c3-11ea-93a8-ed5dec6b6201.png)

And this is the usual speed if I download a file from the same location:
![2019-12-20 00_54_01](https://user-images.githubusercontent.com/10757176/71218852-5f3cab00-22c3-11ea-8b74-54807a11f6e6.png)

Because of that I download the file first and then open it locally. Funnily this is much faster.

**Comment by Maitch** [comment]
This also happens to me.
Downloading a file from the NAS and reading it is way faster than opening it directly in Subtitle Edit. 
I am using Windows 10 and Synology DS218+

**Comment by niksedk** [comment]
Does latest beta perform any better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip ?

Or does it crash...

**Comment by mgutt** [comment]
I performs 5 to 6 times better, but its still miles away from copying the same file from the NAS:
![2020-04-06 10_29_29](https://user-images.githubusercontent.com/10757176/78538926-0f420f80-77f2-11ea-8e74-007b5f667720.png)

**Comment by niksedk** [comment]
`.mkv` files are read in small blocks or bytes even... that could be a reason.
How are `.ts` files performing (if you have any)? 

But still, 5 to 6 times better is an improvement :)
