### ISSUE TITLE
Add: GUI - Close File, hot keys for Changed speed (percent); CLI - Changed speed

### ISSUE THREAD

**Issue by MMasutin** [SubtitleEdit/subtitleedit#3894]
Despite reasons why some of these aren't there, some may benefit from them.
Close File, not just Exit, in the menu File.
Assigned keys for Changed speed (percent).
Changed speed (percent) in the batch converter.

**Comment by OmrSi** [comment]
You can close a file by using "New".
`Change speed` is called "Adjust speed" in Batch convert.
