### ISSUE TITLE
Auto-translate - Change place on Google and Bing

### ISSUE THREAD

**Issue by Sopor** [SubtitleEdit/subtitleedit#3896]
Is it possible to change place so Google and Bing are on the same place for both translating and screen-scraping?
As it is now you have Google first and then Microsoft and for screen-scraping Bing is first and then Google:

![image](https://user-images.githubusercontent.com/5789283/71380701-8996ad00-25d0-11ea-8ded-d5c4f67648cc.png)

Maybe you have made it like this because you have them in alphabetical order, but that is quite annoying when Google is above Microsoft and later below Bing.

**Comment by niksedk** [comment]
I don't think the plugins are sorted... but I've switched GT (Google Translate) and BT (Bing Translate) anyway - and also hidden BT if no key/endpoint entered.

**Comment by Sopor** [comment]
It seems that you can use GT without an API key, but it will only let you translate one sometimes two files :)

**Comment by Sopor** [comment]
I'm now running 3.5.14 and it is still annoying that Google it first at the top of the menu and when i want to use screen-scraping it is at the bottom.

Can't you make Google at the top on both sides of the separator?

**Comment by niksedk** [comment]
How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip ?

![image](https://user-images.githubusercontent.com/1261331/78538355-22a0ab00-77f1-11ea-9999-b330cd0fba1d.png)

Text are now more alike - and plugins are now sorted by name.

(Also, Bing translate should now work better with lines with line-break).

**Comment by niksedk** [comment]
OK, changed it slightly again:

![image](https://user-images.githubusercontent.com/1261331/78538620-917e0400-77f1-11ea-9c6b-732f4f0b34aa.png)
