### ISSUE TITLE
Bug? Timings for subtitle preview text are "inclusive".

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#3897]
I recently upgraded my main installation from 3.5.3 to 3.5.11 to make use of all the new features.

I noticed that something with the subtitle preview text has changed somewhere in between those versions: the preview text now uses "inclusive timings".

What this means:
When the out cue of a subtitle is e.g. 00:00:03,000 and the video position is exactly 00:00:03,000 (by using the shortcuts for 1 frame backwards/forwards), the subtitle is still visible, while it's supposed to be hidden, since the SubRip timings are exclusive. So out cue = 00:00:03,000 = subtitle gone at 00:00:03,000.
While I don't know if this is the original specification, most players (VLC/MPC) do work like this. (I'm sycing to shot cuts and the resulting .srt doesn't overshoot subtitles by 1 frame).

I'm using mpv, and "mpv handles preview text" is off.
When I turn it on, the subtitle is not visible when on the out cue, i.e. it's using "exclusive timings".
The other players don't work properly on my pc, so I couldn't test if it's isolated to mpv.

3.5.3 did use "exclusive timings", so I think something has changed along the way.

**Comment by niksedk** [comment]
SE has always used "Begin time" and "End time" and I don't think you can find anything about .srt times being exclusive. But... I think most programs uses a start time (inclusive) and an (excusive) "out time" when the text is hidden.

I've thought about making the "End time" to a "Out time" / "Hide time" but that probably requires more than one change.

**Comment by Flitskikker** [comment]
@niksedk 
Sorry for the late reply. I'll try to clarify it some more:

> I think most programs use a start time (inclusive) and an (exclusive) "out time" when the text is hidden.

So, indeed, the out times / end times of subtitles are exclusive.
This means, when a subtitle's end time is 00:00:03,000, and the video position is exactly 00:00:03,000, the subtitle should not be visible anymore.

However, in the subtitle preview text in the video player, the subtitles are still visible at 00:00:03,000. They only disappear on the next frame (e.g. 00:00:03,040).

![image](https://user-images.githubusercontent.com/3516155/79641238-84202c80-8196-11ea-9467-0735e28e0553.png)

![image](https://user-images.githubusercontent.com/3516155/79641245-913d1b80-8196-11ea-804e-ea8078e043f2.png)

**Comment by niksedk** [comment]
SE has always worked like that... could be something for a 4.0 release.

**Comment by OmrSi** [comment]
Hmm. It's working like that with MPV
![image](https://user-images.githubusercontent.com/20923700/79641651-876ce580-81a1-11ea-8633-ebc845c0452d.png)

**Comment by Flitskikker** [comment]
@niksedk 
Hmm, strange. Are you sure?
I did some testing and in v3.5.9 it still worked the way I described:

![image](https://user-images.githubusercontent.com/3516155/79642028-6b664580-819b-11ea-9c77-0c42e6c2d9c8.png)

Only starting from v3.5.10 it changed.

@OmrSi
I also use MPV, but I have "mpv handles preview text" unchecked, because I like the way that the subtitles are not "on" the video.

**Comment by OmrSi** [comment]
MPV doesn't handle:
![image](https://user-images.githubusercontent.com/20923700/79642234-fe57ad80-81a4-11ea-8ad0-59989657ead7.png)

MPV handles:
![image](https://user-images.githubusercontent.com/20923700/79641651-876ce580-81a1-11ea-8633-ebc845c0452d.png)

**Comment by chenlung** [comment]
#6650
