### ISSUE TITLE
Is There A Way THat I can Use the program without API Key? for translation because it's to confusing

### ISSUE THREAD

**Issue by princessahmni** [SubtitleEdit/subtitleedit#3898]
Is there a way That I can Use the program without the API key for auto-translation because it's to confusing.

**Comment by niksedk** [comment]
You can still translate using Google translate... probably just not many subtitles at a time.

Also, File -> Plugins contains some extra translation methods like "GT (Google Translate) screen-scraper" + "BT (Bing Translate) screen scraper" + Copy-Paste Translate which should work with all translation web site (with a little copy-pasting).
