### ISSUE TITLE
[Feature Request] Fix missing dots

### ISSUE THREAD

**Issue by pcroland** [SubtitleEdit/subtitleedit#3901]
It would be nice to have a "Fix missing dots" feature in the common fix list. It should add spaces to the end of the paragraph if the next paragraph starts with an uppercase letter.

**Comment by OmrSi** [comment]
You mean "It should add dots"?
![image](https://user-images.githubusercontent.com/20923700/71731671-01c16600-2e4e-11ea-8a6d-e39bef1bb2b0.png)
