### ISSUE TITLE
Attempting to play video using mpv crashes mono and Subtitle Edit

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3902]
From the main window, selecting, Video>Open video file... and selecting a video to play causes both Subtitle Edit and mono to crash. Upon clicking the video to play the little revolving wait circle displays for a few seconds and then SE just disappears.

System Environment:
Ryzen 3700X
X570 chipset
current subtitle edit beta
Kubuntu 19.10
mono 6.6.0
mpv 2.0.30
libmpv-dev 0.29.1
libmpv1 0.29.1

In Options>Settings>Video Player tab, mpv is selected as the video engine.

The mono crash log is attached. It was a json file converted to a txt file.
[mono_crash.12b2f9c488.0.txt](https://github.com/SubtitleEdit/subtitleedit/files/4021694/mono_crash.12b2f9c488.0.txt)

**Comment by niksedk** [comment]
SE with libmpv works fine om my Ubuntu 18.something... but I just tried Kubuntu 19.10 which also works fine for me (Kubuntu looks nice by the way):
![image](https://user-images.githubusercontent.com/1261331/71771663-64def580-2f3f-11ea-8bdc-6875a336dcbf.png)

Installed these packages:

    sudo apt-get install mono-complete
    sudo apt-get install libhunspell-dev
    sudo apt-get install libmpv-dev
    sudo apt-get install tesseract-ocr

Spell check and OCR also works fine:
![image](https://user-images.githubusercontent.com/1261331/71771767-fdc24080-2f40-11ea-9971-a0b1fe5f7518.png)

**Comment by shag00** [comment]
It seems there may be another hidden problem. I successfully ran mpv media player on an older PC also using Kubuntu 19.10 as per your configuration using the older version of mono. It may be mono or perhaps related to these issues reported here with my CPU/chipset combination:
[https://community.amd.com/thread/241192](url)
[https://github.com/ValveSoftware/Proton/issues/2927](url)

I will do further tests and advise.

**Comment by shag00** [comment]
I updated the working PC to mono 6.6.0. which causes both mono and Se to crash, so it looks like that is the culprit. This issue can closed.
