### ISSUE TITLE
eng_OCRFixReplaceList_User.xml appears to be ignored

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3904]
This is the user list generated through Word Lists from: Otions>Settings...>Word lists>OCR fix list.

Although the list itself (eng_OCRFixReplaceList_User.xml) is updated with any input it appears that when performing an OCR translation the program does not use this list.

Applies to 3.5.11 beta portable beta and  Windows installation version 3.5.11.

**Comment by xylographe** [comment]
When installed on Windows the location should be
 `%APPDATA%\Subtitle Edit\Dictionaries\eng_OCRFixReplaceList_User.xml`

The recognized XML tags are, (differs from `eng_OCRFixReplaceList.xml`)
```
<?xml version="1.0" encoding="utf-8"?>
<ReplaceList>
  <WholeWords />
  <WholeLines />
  <PartialLines />
  <BeginLines />
  <EndLines />
  <RemovedWholeWords />
  <RemovedWholeLines />
  <RemovedPartialLines />
  <RemovedBeginLines />
  <RemovedEndLines />
</ReplaceList>
```

**Comment by shag00** [comment]
Yes, exactly, that is why I am saying it is ignored. We are talking about the installer version that generates it's own file when the list is created and I have not moved it. In other words, it is in the Dictionaries folder with all the other Dictionary files like en_AU_user.xml, en_names.xml, and eng_OCRFixReplaceList.xml. The content tags are irrelevant in this discussion because the entire folder is ignored.

**Comment by xylographe** [comment]
> […] the entire folder is ignored.

Select **Options > Settings…**. Select the **Word lists** tab. Click _Open Dictionaries folder_.

**Comment by shag00** [comment]
NB: I corrected folder to read file.

OK, I do that and eng_OCRFixReplaceList.xml and eng_OCRFixReplaceList_User.xml are both there, as I said in my last post.

**Comment by niksedk** [comment]
@shag00: It works fine here... perhaps a screenshot of you OCR window could help and perhaps also a screenshot of the exact issue that does work as you expected.

**Comment by shag00** [comment]
Attached is the screenshot you requested.

Additionally, there is a sup file attached which I renamed as a txt file so I could upload it. the third attachment is the eng_OCRFixReplaceList_User.xml also renamed as a txt file that I have used for my testing.

Run the OCR translation and see nothing happen at line 95.

[eng_OCRFixReplaceList_User.txt](https://github.com/SubtitleEdit/subtitleedit/files/4038173/eng_OCRFixReplaceList_User.txt) 

![OCR](https://user-images.githubusercontent.com/37562304/72030511-5006b700-32dd-11ea-8078-ef400b22b2e5.JPG)

[02798.track_4608.txt](https://github.com/SubtitleEdit/subtitleedit/files/4038162/02798.track_4608.txt)

**Comment by niksedk** [comment]
@shag00: I think you attached a .srt file instead of the .sup file (you can attach .zip files btw).

**Comment by shag00** [comment]
Attached.
[02798.track_4608.zip](https://github.com/SubtitleEdit/subtitleedit/files/4047981/02798.track_4608.zip)

**Comment by shag00** [comment]
This may also be part of the problem with this issue. I went to the word list in the GUI and deleted everything in the list and the result was surprising, at the end of the delete process it threw up an error message (not an issue) but the surprising thing was that the eng_OCRFixReplaceList_User.xml file was populated by, I assume, the contents I had just deleted from the GUI window. Approx 4100 entries were added but this is not the entire eng_OCRFixReplaceList.xml as it is 4400 entries.

On restarting SE the GUI window now displayed 147 entries, I cannot identify where these came from. Repeating this step gave the same result.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

How does the above beta work for you?
(the GUI stuff was a separate issue but should be fixed also)

**Comment by shag00** [comment]
The new exe file fixes the specific issue of OCR translation of l.D. I will do more testing of other suspect letter combinations. This change has however brought some unintended consequences where the editable text is (so far discovered) either 1 or 3 characters as shown in the following images. The previous settings covered the entire word in blue highlight and any text input over write it as per normal Windows behaviour, now as the blue highlight does not cover the entire word after correcting the word manually you have to delete the remaining non highlighted characters
![SE11](https://user-images.githubusercontent.com/37562304/72202218-e3dcac80-34b0-11ea-8c54-7fd904b4f7eb.JPG)
![SE12](https://user-images.githubusercontent.com/37562304/72202221-eccd7e00-34b0-11ea-81d9-720f6e611090.JPG)

.

**Comment by shag00** [comment]
Run under mono the OCR fix does not work however the partial highlighting is not a problem.
![1](https://user-images.githubusercontent.com/37562304/72202564-f00a3f00-349b-11ea-8795-d2e3c1cf8a09.png)

**Comment by niksedk** [comment]
What do you mean by `he OCR fix does not work` ?

**Comment by shag00** [comment]
The changed exe file run in mono changed the translation from:
Don't engage until we get an l.D.
Don't engage until we get an !.D.

I added 2 lines to my (the one I sent previously)
eng_OCRFixReplaceList_User.xml)
!.D>>>I.D and !.D.>>>I.D.

Refer the first screen shot in my last post and you will see SE accepted !.D. as a valid word.

**Comment by niksedk** [comment]
OK, SE treats some characters as word splitters... like "!", so you need to do something like this (or some regular expression) in your `eng_OCRFixReplaceList_User.xml`:


    <PartialLines>
        <Word from=" !.D" to=" I.D" />
    </PartialLines>

Perhaps just splitting words only on space would be better... that's a completely other issue.

Beta updated, so that current word is NOT highlighted in the `OCR spell check window`: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

**Comment by shag00** [comment]
Just a comment: this may cause a lot of issues with people using Tesseract 4 as it seems to have a lot of problems with decoding "I" (capital eye) being translated as "!" as well as l (lower case elle). Lower case elle is easy to fix, ! is not.

**Comment by shag00** [comment]
The changes you advised in your last post are effected with the new exe file in both Windows and mono.

**Comment by niksedk** [comment]
@shag00: thx for reporting and testing... 2-3 bugs/issues has been fixed with this :)
