### ISSUE TITLE
Spell check pop-up during OCR translation using Ubuntu

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3905]
Using 3.5.11 Beta portable.

During OCR translation when an unknown word is translated the following screen pops up which does not immediately allow you to recognise or correct the problem:
![b4](https://user-images.githubusercontent.com/37562304/72045443-0c1dad00-32f1-11ea-9b60-07bf76f6b2bd.png)
To get the correct window to display it is necessary to click on the 'Edit whole text' button then immediately click on the 'Edit word' button which was previously greyed out to get to the screen which allows you to correct the word:
![after](https://user-images.githubusercontent.com/37562304/72045834-07a5c400-32f2-11ea-88a5-506f1d0307ff.png)

This should be corrected so the second (after) screen dispays immediately an unknown word is translated.

**Comment by niksedk** [comment]
Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip
(took several hours as Mono had problems with SendToBack/BringToFront - had to switch to Visible = false/true)

**Comment by shag00** [comment]
Thank you for that fast fix. I think you have met a major mile stone with this software now - the linux version, as far as I can tell, matches the Windows version in every respect of function when translating a sup file to an srt file with English corrections and other user requirements - congratulations..
