### ISSUE TITLE
Music symbol under mono

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3907]
There are a few parts to this issue. Firstly is the OCR introduction screen, under mono there is no little box to tick, next to italics, as there is in Windows:
![win1](https://user-images.githubusercontent.com/37562304/72211029-fd0c4a00-34fe-11ea-95e9-a291589ca72d.JPG)

Secondly, under Options>Settings...>Tools, left hand side, 2nd pane there is an item named Music symbol with a drop down box. This drop down box does not  contain a music symbol:
![1](https://user-images.githubusercontent.com/37562304/72211084-df8bb000-34ff-11ea-9754-52d9de5439ed.jpeg)

Depending on the font used seems to dictate whether SE displays a music symbol or whatever symbol is selected in the drop box in point 2. As there are a few variables here I have not been able to pinpoint what the issue is.

**Comment by niksedk** [comment]
2) It seems Mono chooses a default font with limited Unicode support... I guess SE on Linux could check if "FreeSerif" / "DejaVu Serif" / "FreeSans" is available - would that help? You try by changing "Settings.xml... look for "Override".

**Comment by shag00** [comment]
________________________________

**Comment by shag00** [comment]
I might be missing your point but the fonts you mentioned above plus Liberation Sans all display the ♪ symbol if an srt file containing that symbol is present. None of them changes the symbols that appear in the drop down box I refer to in my initial post. 

I did change the override as you suggested:
<SystemSubtitleFontNameOverride>DejaVu Serif</SystemSubtitleFontNameOverride>
which also had no effect. Initially, I am not sure it changed anything because 2 lines later
<SubtitleFontName>DejaVu Serif</SubtitleFontName>
was already there.

As far as I can tell the box symbol displayed in the drop-down menu is character 2395
[https://www.unicode.org/charts/PDF/U2300.pdf](url)

**Comment by niksedk** [comment]
It was to avoid a square instead of a music symbol:
![image](https://user-images.githubusercontent.com/1261331/72313772-c106ef80-368c-11ea-86e3-410d8f37798c.png)

And get something like this:
![image](https://user-images.githubusercontent.com/1261331/72313888-3246a280-368d-11ea-917e-e9e47316b01e.png)

**Comment by shag00** [comment]
Ah, OK, I did understand what you said. In that case this solution did not work for me.

**Comment by niksedk** [comment]
Strange... the second screenshot above is from my Kubuntu.
Did you have SE closed while editing the "Settings.xml" ?

**Comment by shag00** [comment]
Could you post your settings.xml please.

**Comment by niksedk** [comment]
@shag00: latest beta now defaults to "FreeSerif" on Linux: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip
(I've tested on latest Kubuntu + an older Ubuntu which both worked fine for me ... I'll test latest Manjaro later)

**Comment by niksedk** [comment]
Also tested on Manjaro now - updated the help a little: https://nikse.dk/SubtitleEdit/Help#linux

**Comment by shag00** [comment]
VLC as packaged with Ubuntu does not work out of the box with SE. I think you also need to tell linux users how to set up a tesseract directory and links to tesseract.

**Comment by shag00** [comment]
OK, I now get a music symbol in the drop down menu. This issue is fixed and can be closed.

**Comment by xylographe** [comment]
@shag00 
When running on Linux, SE checks the existence of these directories,
```
/usr/share/tesseract-ocr/4.00/tessdata
/usr/share/tesseract-ocr/tessdata
/usr/share/tessdata
```

@niksedk 
Perhaps, check for the existence of `${env:TESSDATA_PREFIX}/tessdata` first?

**Comment by shag00** [comment]
@xylographe  is this comment in the correct issue?

**Comment by xylographe** [comment]
It was in response to https://github.com/SubtitleEdit/subtitleedit/issues/3907#issuecomment-574473040.

**Comment by niksedk** [comment]
Closed as music symbol under mono is fixed. Requires a Unicode font as stated on help page: https://nikse.dk/SubtitleEdit/Help#linux
