### ISSUE TITLE
[Feature Request] Option for "Save as" default directory

### ISSUE THREAD

**Issue by chorong761** [SubtitleEdit/subtitleedit#3908]
It would be nice if there is a feature that could set the "Save As" default directory be the same as the source file or to a custom directory.

**Comment by darnn** [comment]
Hear, hear.

**Comment by niksedk** [comment]
A setting already exists for this... does it not work?
![image](https://user-images.githubusercontent.com/1261331/72665091-98248880-3a05-11ea-9ab9-335953990196.png)

**Comment by darnn** [comment]
Ah, huh, I suppose it does.  What I was thinking of was, in addition to that, the option to set a default directory to which all files would always be saved when you use "save as".

**Comment by chorong761** [comment]
> A setting already exists for this... does it not work?
> ![image](https://user-images.githubusercontent.com/1261331/72665091-98248880-3a05-11ea-9ab9-335953990196.png)

thats not even what i want lol, that option only uses the file name but im talking about directory.

e.g the file opened was on desktop, and "save as" would default to desktop instead of last used folder
