### ISSUE TITLE
Music symbols essentially not able to be OCR translated by Tesseract 4 (or linux)

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3909]
I have been testing SE for use under linux recently and have discovered that Tesseract 4 is a significant issue for SE when certain characters appear in an image based format, in this case .sup. The following table was produced from a random .sup file that contains music symbols. Other characters with problems include 1, !, l and I, though not to the extent shown below.

This table just shows the OCR translation result of the first 20 lines of a 1,939 line file.

[music symbol.pdf](https://github.com/SubtitleEdit/subtitleedit/files/4050200/music.symbol.pdf)

I am aware that there may be different reasons that contribute to this result, of particular note being Tesseract, but Tesseract 4 scores zero for correctly identifying a music symbol in 26 consecutive attempts using both Windows and mono with windows returning no translation at all in a significant number of cases. The variety of translation returns is also alarming with this one character returning 12 different results (if my addition is correct). 

My requests would be a combination of the following:
1/ Tesseract 3 be enabled for mono
2/ Cease support for the current  Tesseract 4
3/ Urgently investigate the availability of Tesseract 5
4/ A warning to users that Tesseract 4 is unreliable
5/ Investigation of Tesseract alternatives such as OCRFree
6/ Is there a way to catch the mistranslated characters, especially the non alpha-numerics such as '?' and '<' which can be very common and have special meanings.
7/ Suggestions from other users

Attached are the source documents:
[Depraved 2019.track_4608.zip](https://github.com/SubtitleEdit/subtitleedit/files/4050215/Depraved.2019.track_4608.zip)
[Depraved ubuntu T4.zip](https://github.com/SubtitleEdit/subtitleedit/files/4050216/Depraved.ubuntu.T4.zip)
[Depraved windows T3.zip](https://github.com/SubtitleEdit/subtitleedit/files/4050217/Depraved.windows.T3.zip)
[Depraved windows T4.zip](https://github.com/SubtitleEdit/subtitleedit/files/4050218/Depraved.windows.T4.zip)

**Comment by xylographe** [comment]
Have you tried using the [**Legacy + LSTM** .traineddata files](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400-september-15-2017) (with _Engine mode_ set to _Original Tesseract_)?

**Comment by shag00** [comment]
I can use Tesseract 3 and get 92% accuracy for music symbols, so no need to go further back in the technology and risk other errors. I have lived with Tesseract 3 for years and learnt to put up with it. The point I am trying to make is that Tesseract 4 has some improvements over Tesseract 3 in some areas but significant declines, as I have indicated above, overall a step backwards.

**Comment by niksedk** [comment]
With the files/setting @xylographe mentioned, Tesseract 4 should run in "Tesseract 3 mode":
![image](https://user-images.githubusercontent.com/1261331/72216288-6d2ac800-351f-11ea-834d-86afbf0e4669.png)

I think this is more a Tesseract issue than a SE issue.
I fully agree with Tesseract 4 is lacking something - I really miss the italic support.
It is possible to train Tesseract with the font and characters you use mostly (probably not super easy).

Also, you can also use "Binary image compare" as OCR method...

**Comment by shag00** [comment]
I have raised this issue on the Tesseract Github site
[https://github.com/tesseract-ocr/tesseract/issues/2854](url)

I will test the Tesseract 3 functionality on mono tomorrow.

**Comment by shag00** [comment]
Obviously to set up SE with the engine mode you suggested needs further things to be done to make it work, what are those?

**Comment by shag00** [comment]
Someone has responded from tesseract github that I have the fast model installed and should use the best model (1.3GB) which is located  [ https://github.com/tesseract-ocr/tessdata_best](url)

Would either of you gents know how to install it?

**Comment by xylographe** [comment]
@shag00 
You need [Trained models with support for legacy and LSTM OCR engine](https://github.com/tesseract-ocr/tessdata). This set is the only one that supports the legacy recognizer. Just download `osd.traineddata` and the language(s) you intent to use (e.g. `eng.traineddata`), and copy them to `/usr/share/tesseract-ocr/4.00/tessdata` (after renaming the existing files from the tessdata-fast set).

**Comment by shag00** [comment]
xylographe,

is there a way to install both tesseract traineddata files and getting SE to use the one you want it to use?

**Comment by xylographe** [comment]
I don't think so, the traineddata files are uses by tesseract, not by SE. SE merely examines which files are available to let you choose the appropriate language.

**Comment by shag00** [comment]
> @shag00
> You need [Trained models with support for legacy and LSTM OCR engine](https://github.com/tesseract-ocr/tessdata). This set is the only one that supports the legacy recognizer. Just download `osd.traineddata` and the language(s) you intent to use (e.g. `eng.traineddata`), and copy them to `/usr/share/tesseract-ocr/4.00/tessdata` (after renaming the existing files from the tessdata-fast set).


Do you know if it is essential to use the osd.traineddata from this package or can I use the one I have installed at the moment?

**Comment by shag00** [comment]
I ask because I am thinking of installing the 'best' English traineddata as French traineddata and selecting French from SE to get it to use the best English trained data.

**Comment by xylographe** [comment]
I don't know. Compare the two osd files with cmp(1). If they are different, you'll need them both.

It looks like there might be a work-around by setting the TESSDATA_PREFIX environment variable before starting SE. For example: `TESSDATA_PREFIX=/usr/share/tessract-ocr/legacy mono SubtitleEdit.exe` (see [Command Line Usage](https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage)). Copy the legacy files to `/usr/share/tessract-ocr/legacy/tessdata` and keep `/usr/share/tesseract-ocr/4.00/tessdata` for the tessdata-best files.

**Comment by shag00** [comment]
And cmp(1) is?
[http://man.openbsd.org/cmp%26sektion%3D1](url)

**Comment by xylographe** [comment]
[cmp - compare two files byte by byte](https://manpages.ubuntu.com/manpages/trusty/en/man1/cmp.1.html).
Or run `man 1 cmp` (`man 3 cmp` also exists, but is not what you want).

**Comment by shag00** [comment]
I have rerun the tests u
[music symbol.pdf](https://github.com/SubtitleEdit/subtitleedit/files/4057956/music.symbol.pdf)
sing the Best traineddata model, not much joy.

**Comment by shag00** [comment]
I also tested the legacy traineddata tesseract 4. It beats the other tesseract 4 data sets by being able to detect and translate correctly just one of twenty six occurrences of the music symbol. This well below tesseract 3.

**Comment by shag00** [comment]
Just to summarise the current situation with this issue. I have tested 3 trainneddata files, legacy, fast and best. As far as the music symbol is concerned each dataset performs extremely poorly being able to virtually never being able to successfully translate this symbol. I have spot checked that it is indeed an issue with tesseract by spot checking the results from the Ubuntu terminal using the tesseract command. Capital i is another poor performer. As advised earlier I have logged an issue with tesseract github on these 2 characters. The upshot of this is I do not believe that SE can do anything to improve this poor performance.

As a work around is it possible to include in the OCR spell check window an, Insert Music Symbol key?

**Comment by xylographe** [comment]
Your results ([music.symbol.pdf](https://github.com/SubtitleEdit/subtitleedit/files/4057956/music.symbol.pdf)) show that most often tesseract generates **J** i/o **♪**.  Perhaps,
```xml
  <PartialLines>
    <LinePart from=" J " to=" ♪ " />
  </PartialLines>
```
in `eng_OCRFixReplaceList_User.xml` might help a little?

**Comment by shag00** [comment]
I think there are a couple of things to consider here, being:
1/ what tesseract dataset are people using as the results vary. In Ubuntu fast is default;
2/ How does your suggestion handle the outlier returns, eg. J'; 
3/ How does your suggestion handle names, eg. J.Smith;
4/ Niksedk indicated in a reply somewhere that teeseract does learn, how it does this I have no idea but I assume if you put in the desired character you want it will eventually translate to that character rather than J.
5/ At the moment to insert a music character you need to open the internet and search for one and what you find is likely not the correct font and probably changes over time or from slightly different search input. If tesseract can be trained then constant input would be the best way.

At the moment I just use the temporary Change To/All option in the spell check window until Niksedk decides how he wants to handle this issue. I think your suggestion is one he would consider highly because it is fast and easy to implement.

I feel my suggestion is more work, takes much longer for a result but ultimately gives a better result.

**Comment by xylographe** [comment]
I think, the learning applies to OCR methods _Binary image compare_ and _OCR via nOCR_, but **not** to OCR method _Tesseract_.

`J.Smith` is not affected by `from=" J "` (space before and after `J`). If `J';` often occurs, add it too.

I don't see what Nikolaj can do, it's a Tesseract problem.

**Comment by shag00** [comment]
Nikolaj needs to decide what action to take from the alternatives available in view of the fact of this tesseract problem. He cannot fix the problem but he can decide from a number of work arounds.

**Comment by niksedk** [comment]
I still think this is mostly a Tesseract issue. 
Also, you can train your own Tesseract files to work with the font/chars you need (shag00's font is perhaps a bit more bold than usual) but it's not super easy (I added a `music.traineddata` file for Tesseract 3.02 to improve music symbols).

Also, SE has the OCR method "Binary image compare" which requires more work to learn, but it does work nicely with both music symbols and italic for most fonts.

**Comment by Rumourd** [comment]
Whenever I used Tesseract to batch-convert previously-generated SRTs to CHANGE CASE only, it introduces a music symbol and a space in lieu of any uppercase "J" character.

I can't use OCR as it voluminously introduces other bad characters; it is even worse.

**Comment by shag00** [comment]
My "J"'s often are translated as "$"'s.
