### ISSUE TITLE
Remove RTL unicode tags command line script

### ISSUE THREAD

**Issue by D00oo00M** [SubtitleEdit/subtitleedit#3910]
when i try to use this command line script:
@echo off
cd /d %~dp0
SubtitleEdit /convert %1\* SubRip /multiplereplace /encoding:windows-1255 
pause

 i got an question mark before and after the line
https://imgur.com/Ar0jMul
when i used thats command:
SubtitleEdit /help
i saw that no have "Remove RTL unicode tags"
there is any chance to add "Remove RTL unicode tags" to the command line script ?

**Comment by OmrSi** [comment]
You could just add Regex "\p{Cf}" to your multiple replace...
![image](https://user-images.githubusercontent.com/20923700/72220660-8baeb480-355b-11ea-81fc-59f990fe3368.png)

**Comment by D00oo00M** [comment]
ty its worked like a charm!
