### ISSUE TITLE
Difference between OCR translate and spell check screens

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3915]
If I am not mistaken until fairly recently these 2 screens were showing the same line of text, now the translation screen is always one line behind. Would be nice to have them both showing the line being worked on.
![14](https://user-images.githubusercontent.com/37562304/72412729-133d3300-37a9-11ea-8c5b-9b2bbc29c464.jpeg)

**Comment by niksedk** [comment]
thx, should be fixed in latest beta - verified on Ubuntu/Kubuntu/Manjaro.
