### ISSUE TITLE
3.5.12 Beta enhancements for Linux - some text now to big

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3917]
The new font that was introduced in the last beta is now to big to fit in some windows or columns, in particular the start time as shown in the main screen of SE. This numerical text needs a smaller font size. The font of the actual subtitle text is OK and does not need to be changed, just the values for: start time, end time and duration.

**Comment by niksedk** [comment]
Should be fixed on latest beta - tested on Ubuntu/Kubuntu/Manjaro

**Comment by niksedk** [comment]
Related: I tried vlc player too, but libmpv is so much better working in SE that I'll avoid mentioning vlc as video player in SE on Linux.
