### ISSUE TITLE
The dash (-) symbol now appears as a box on linux.

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3918]
Please see the screen shots.
from the srt file:

![15](https://user-images.githubusercontent.com/37562304/72433282-e6eadc00-37d3-11ea-9353-b4361eab2635.jpeg)

Screen shot from movie
![vlcsnap-2020-01-15-20h08m09s534](https://user-images.githubusercontent.com/37562304/72433425-3d581a80-37d4-11ea-9145-2ee0b6f0ee09.jpg)
:

**Comment by xylographe** [comment]
Change the font in **ASS/SSA Style** tab in **Settings** dialogue?

**Comment by shag00** [comment]
Changing the ASS/SSA Style Font made no difference.

**Comment by shag00** [comment]
Further info: The picture above shows the subtitle after having being converted to a .sup file when combined with the audio and visual. When that sup file is translated back to srt the box characters are, apparently, translated into a random letter.

**Comment by niksedk** [comment]
This issue I cannot re-create (tried on Ubuntu/Kubuntu/Manjaro).
