### ISSUE TITLE
OCR translation spell check window display text window Mono to small 

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3920]
Please see the following screen shot, the text in the highlighted display box is difficult to read.
![16](https://user-images.githubusercontent.com/37562304/72502192-b490bb80-3873-11ea-8ede-381d37c59125.jpeg)

Also, the Find window This the "[" character:
![2](https://user-images.githubusercontent.com/37562304/72508226-47cfee00-3880-11ea-8491-4a36a89fe96c.png)

**Comment by niksedk** [comment]
First issue I cannot re-create (tried on Ubuntu/Kubuntu/Manjaro).
