### ISSUE TITLE
[Feature Request] Save path = file location

### ISSUE THREAD

**Issue by mgutt** [SubtitleEdit/subtitleedit#3922]
If I doubleclick through W10 x64 on an SUP file to open it with Subtitle Edit and after finishing the OCR process like to save the SRT file, it wants to save the file under "C:\Users\<username>\Documents\" or if I saved a SRT file before it uses the last folder instead of the location of the opened SUP file.

In both cases it should use the location of the opened SUP file. ❤

**Comment by aaaxx** [comment]
Dupe: https://github.com/SubtitleEdit/subtitleedit/issues/2384
