### ISSUE TITLE
Error on cursive or bold.

### ISSUE THREAD

**Issue by LustigKnorre** [SubtitleEdit/subtitleedit#3926]
Hi,
If I put the cursor inside the textarea and DON'T highligt anything, then right-click and select "cursive" or "bold" I get an error message.
Error Message: (translating from swedish so it might not be the exact words....)
Index outside the intervall. It may not be negative and must be less than the size of.... "mängden"
Name of parameter: index.
-----------
I know it's stupid to select cursive whithout selecting any text but I would expect that the application just to "ignore" it or give me an "You must select text to make it cursive/bold ... whatever"
--------------
Windows 10
Subtitle Edit 3.5.11.322
Can repeat it every time. 
It does NOT happen if I don't put the cursor in the textfield first.

Cheers

**Comment by niksedk** [comment]
@LustigKnorre: thx for the info, but I cannot re-create this in the textbox in the main window. 
Can you attach a screenshot?

**Comment by xylographe** [comment]
When I click _Italic_ or _Bold_ in the textbox without text selection, the whole subtitle is affected.

**Comment by LustigKnorre** [comment]
> When I click _Italic_ or _Bold_ in the textbox without text selection, the whole subtitle is affected.

Yes, but if you put the cursor in the textbox first, at the end for example, then right-click and select cursive. If that doesn't cause the error, try doing it a couple of times "add bold" "remove bold" by right-clicking.
![Clipboard01](https://user-images.githubusercontent.com/39223156/72671864-92549480-3a51-11ea-9c64-f4ff921c51dd.jpg)

**Comment by darnn** [comment]
Might be a Windows 10 thing, I can't reproduce this either on Windows 7 (3.5.11 NEXT 318).

**Comment by darnn** [comment]
In fact I can't reproduce it on Windows 10 either (build 18362.535).

**Comment by LustigKnorre** [comment]
Strange, it happened in SE3.5.11 99 as well so I updated and the error is still there.
I just noticed that it doesn't happen in every row, seems to happen more when there is a lot of text?
And you can force the error by doing "italic" or "bold" back and forth.
Well, I have reported it and it's not a biggie for me just wanted to let you know.

**Comment by darnn** [comment]
Can you upload a specific subtitle with a certain line where you can get it to happen consistently? That way we'll at least be testing the same thing.

**Comment by darnn** [comment]
Oh, never mind, I got it too now:
![bold](https://user-images.githubusercontent.com/19672444/72672021-5c68dd80-3a5c-11ea-880a-0174a3826a92.png)

The line does have to be long. I created a single-line subtitle that consisted of this:
`The quick brown fox jumped over the rose of quartz. The quick brown fox jumped over the rose of quartz. The quick brown fox jumped over the rose of quartz. The quick brown fox jumped over the rose of quartz. The quick brown fox jumped over the rose of quartz.`

**Comment by LustigKnorre** [comment]
Yes, I just thought of that. I tried an English subtitle and the error didn't occur...
ah, ok. Nice, now I know I'm not crazy :)
I'll upload a file that the error occurs on line 4 in. If anyone else needs to try it.
[blood.txt](https://github.com/SubtitleEdit/subtitleedit/files/4082047/blood.txt)

**Comment by niksedk** [comment]
Thx for reporting/investigating this :)

Seems to happen when the textbox wraps the text - I was running SE in full-screen so I could only re-create it with darnn's very long text.
