### ISSUE TITLE
Source+translation pair in reopen list with video offset

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3928]
Hi. Still using 3.5.11 318, but I assume this hasn't changed since yesterday.
The circumstances are as follows: There's a source file and a translation file open. The video offset has been changed. Then, for instance, a new subtitle file is created, so the two open files are closed, as well as the video file. At this point, attempting to open the translation file from the file->reopen menu will open both the translation and the source, but will display the source as a blank file:
![se-reopen](https://user-images.githubusercontent.com/19672444/72684243-916e4200-3ae7-11ea-908c-bf0591a7cefa.png)
The line in settings.xml looks like this:
`      <FileName OriginalFileName="D:\Dropbox\TEST22 ENG.srt" FirstVisibleIndex="0" FirstSelectedIndex="0" VideoOffset="3450000">D:\Dropbox\TEST22 HEB.srt</FileName>`
And if `VideoOffset="3450000"` is removed, SE opens both files properly. If it's restored SE opens the source as blank again.

**Comment by niksedk** [comment]
thx - seems like an old bug... should hopefully be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.12/SubtitleEditBeta.zip

**Comment by darnn** [comment]
It's still doing the same thing over here, alas. Quick way to reproduce:
Create new subtitle file with three lines. Put some text in them. Use "make new empty translation from current subtitle". Put some (different) text in the translation lines. Open a video file. Set video offset to 00:57:30:00 (or 00:57:30.000). Save the translation and the original. Create a new subtitle file so that the two previous files are closed. Now use file->reopen to open the translation subtitle.

**Comment by niksedk** [comment]
thx for testing :)
Should be working now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.12/SubtitleEditBeta.zip

**Comment by darnn** [comment]
It is! Thank you!
