### ISSUE TITLE
Timecode issue in conversion to PE2

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#3929]
3.5.11 318.
Previously, if I had an SRT open with a video at the proper framerate and saved it as a PE2 file, the timecodes were converted correctly. In this version they aren't. For example, timecodes from the SRT:
`01:00:00,042 --> 01:00:01,417`
At a framerate of 23.976, in 3.5.10 NEXT 258, this would be converted to:
`01:00:00:01`
`01:00:01:10`
Currently it's converted to:
`01:00:00:00`
`01:00:01:00`
And the whole sequence of timecodes seems to be a very rough approximation:
`01:00:00:00 a`
`01:00:01:00`
`01:00:01:00 a`
`01:00:03:00`
`01:00:03:00 a`
`01:00:06:00`
`01:00:07:00 a`
`01:00:09:00`
`01:00:09:00 a`
`01:00:10:00`
`01:00:11:00 a`
`01:00:13:00`
`01:00:13:00 a`
`01:00:14:00`
`01:00:14:00 a`
`01:00:16:00`

**Comment by niksedk** [comment]
thx for the info - is latest beta better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.12/SubtitleEditBeta.zip

**Comment by darnn** [comment]
After a few tests, seems to be, yes! Thanks! You can close this for now, I'll open a new one if anything else pops up.
