### ISSUE TITLE
Vietnamese subtitle got error

### ISSUE THREAD

**Issue by namv22** [SubtitleEdit/subtitleedit#3931]
So I'm doing sub for a video for my friend and the Vietnamese got messed up, I don't know how to properly describe this so here's a picture
https://photos.app.goo.gl/HxwTDb6yREL5dXmF8

If anyone knows how to fix it, please help

**Comment by xylographe** [comment]
In **Options > Settings > ASS/SSA Style** select a font that contains Vietnamese glyphs.

**Comment by namv22** [comment]
> In **Options > Settings > ASS/SSA Style** select a font that contains Vietnamese glyphs.

thanks for the help, but it doesn't work, the normal fonts that can be used to write Vietnamese are Arial, Cambria, Times New Roman, and I have tried them all

**Comment by xylographe** [comment]
What is the "Encoding" in the toolbar?

**Comment by namv22** [comment]
> What is the "Encoding" in the toolbar?

UTF-8

**Comment by xylographe** [comment]
This is what I get with font set to "Arial Unicode MS":

![Vietnamese](https://user-images.githubusercontent.com/8535293/72871756-f4302b00-3ceb-11ea-9b89-1e142e00b005.png)

**Comment by xylographe** [comment]
Oops, a little late, but I just realise that the font in the preview on the right, and the font in the list view on the left are the same (set in **Options > Settings > Font**). Very strange that in your image above, the text is OK on the left (in list view and text box), but not on the right (in preview).

**Comment by namv22** [comment]
wow, it finally works, thanks for the tip
![image](https://user-images.githubusercontent.com/13979900/72882618-7ee94800-3d35-11ea-88b8-1581eaedd753.png)
