### ISSUE TITLE
The fix OCR errors tool

### ISSUE THREAD

**Issue by vivadavid** [SubtitleEdit/subtitleedit#3934]
Hello,

I’m sorry if the information I’m requesting is provided somewhere else, but I couldn't find it. 

When you perform an OCR on a subtitle file, you can enable or disable the "fix OCR errors" tool, but is it possible to determine which kind of corrections it makes? Going through the whole programme, I found the "fix common errors" tool, but, after some testing, I got to the conclusion that it was a different kind of tool with no connection to the one in the OCR section.

I’d specifically like to disable the conversion from the double quotation ("") marks to the Spanish quotation marks («»). When I write in Spanish, I certainly use the latter, but the "fix OCR errors" tool makes an undesired change regarding punctuation. I also noticed, when there's only a quotation mark on a subtitle, that the tool doesn't know whether it needs to place an opening or an ending quotation mark. My final reason to use double quotation marks is that, in any case, they are more legible.

Right now, I’m just disabling the tool, but I wish I was able to enable or disable each type of correction individually.

Thanks for your help and sorry again if I should have found the solution myself: I tried.

**Comment by xylographe** [comment]
In **Options > Settings >  Tools** you will find the _"Fix common OCR - also use hard-coded rules"_ option. If disabled some OCR fixes will not be performed.

**Comment by vivadavid** [comment]
Thank you, @xylographe .

I've disabled the option, but the OCR still replaces the quotation marks.

**Comment by xylographe** [comment]
It looks like quotations are replaced via `Dictionaries/spa_OCRFixReplaceList.xml`. Try renaming the file (e,g, `spa_OCRFixReplaceList.xml.orig`), then SE won't be able to use it. Obviously, this will also disable many useful replacements. But, if it works, it might be possible to disable only the unwanted rules in `spa_OCRFixReplaceList.xml` via `spa_OCRFixReplaceList_User.xml`.

**Comment by vivadavid** [comment]
Thank you, @xylographe: the changes made by the tool have to do with the rules stored in spa_OCRFixReplaceList.xml.

I don't understand very well some of the rules (especially the regex ones), but I can get now an idea about the type of replacements they make. Based on this fact, I think I could just disable the tool, although I suppose I could edit the file and remove the rules I don't need, but it looks a bit risky.

**Comment by xylographe** [comment]
Better not change `spa_OCRFixReplaceList.xml`. Your changes will be lost after the next update. But, you can use the `<RemovedRegularExpressions>` section in the user list (`spa_OCRFixReplaceList_User.xml`) to deactivate regular expressions defined in `spa_OCRFixReplaceList.xml`. The user fix list has priority over the distributed fix list.

**Comment by vivadavid** [comment]
Thank you for the suggestion, @xylographe. I'll do that if I decide to keep the tool enabled.

**Comment by OmrSi** [comment]
@niksedk Closed?
