### ISSUE TITLE
OCR dictionary download freezes on Ubuntu

### ISSUE THREAD

**Issue by lxs602** [SubtitleEdit/subtitleedit#3935]
Hi,

Installing language dictionaries for Tesseract OCR freezes when the download reaches 100%.

However, OCR auto correction / spell checking dictionaries install without any problems.

I have used SE 3.5.13 on Ubuntu 19.10.

A link to mono logs are below,  the command:
```MONO_LOG_LEVEL="debug" MONO_LOG_MASK="all" mono SubtitleEdit.exe > SubtitleEdit.log```:

https://gofile.io/?c=L0IwNG

**Comment by xylographe** [comment]
From Mono log:
```
Mono: mono_w32file_create: Opening /usr/share/tesseract-ocr/4.00/tessdata/fra.traineddata with share 0x1 and access 0xc0000000
Mono: mono_w32file_create: Error opening file /usr/share/tesseract-ocr/4.00/tessdata/fra.traineddata: Permission denied
```
Perhaps, you can solve this by using the overlayfs?

**Comment by shag00** [comment]
I find it easier to download dictionaries without using mono. Just go to the tesseract github and download directly using ubuntu.

**Comment by lxs602** [comment]
An access error... 

Sorry for the stupid question.
