### ISSUE TITLE
Unexpected result after using search in mono

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#3936]
Normally, when searching for a character or string in a srt file, SE takes you to the line with the found string and allows you to directly edit that string. So once you click FIND, SE searches for the string and highlights it in the edit box, if your next action is to press DELETE then those characters will be deleted.

What is happening at the moment is that SE highlights the string as expected but if you then press DELETE nothing happens. To delete the string it is necessary to mouse click in the edit box first. Subsequent searches for the same string, that is press FIND again, work as expected.

**Comment by niksedk** [comment]
I can confirm this for both Ubuntu and Manjaro. Mono seems to ignore there commands:
- ActiveControl = tb;
- tb.Select();
- tb.Focus();
