### ISSUE TITLE
Dictionaries and Languages ​​- Questions

### ISSUE THREAD

**Issue by ticao2** [SubtitleEdit/subtitleedit#3938]
Question 1: Are these possible files for any language?
For example, Brazilian Portuguese **(EDITED)**:
pt_BR.aff
pt_BR.dic
pt_BR_user.xml

~~pt_BR_names.xml~~
~~pt_BR_names_user.xml~~
pt_names.xml
pt_names_user.xml
pt_NoBreakAfterList.xml

por_OCRFixReplaceList.xml
por_OCRFixReplaceList_User.xml

Question 2: Which language prefix should or can be used in the **NoBreakAfterList** file?
2 letters (pt, en, es, sr)
3 letters (por, eng, spa, srp)
4 letters (pt_BR, en_US, es_MX)
I found this file name variation in the folder:
hr_NoBreakAfterList.xml
hrv_NoBreakAfterList.xml
sr_NoBreakAfterList.xml
srp_NoBreakAfterList.xml

Question 3: Which language prefix should or can be used in the **OCRFixReplaceList** file?
Only 3 letters (por, eng, spa)?
Or can a 4-letter prefix (pt_BR, en_US, es_MX) be used?

Question 4: Is the statement below correct?
In **Word lists > Language** there is a list of **16** languages.
If your language does not appear as an option in this list, then, for it to appear, create a **user.xml** file with the prefix of your **language_COUNTRY**. For example **pt_BR_user.xml**.

Note: It would be interesting if the language prefix used for all files was 4-letter **language_Country** (pt_BR, en_US).
The absence of a file with 4 letters would refer to the use of the file of 3 and/or 2 letters.

**Comment by xylographe** [comment]
`pt_BR.aff`, `pt_BR.dic` and `pt_BR_user.xml` are for Hunspell spell checking. Other prefixes are possible (e.g. `pt_ANY.aff`/`pt_ANY.dic` would indicate the Hunspell dictionary can be used for European, South-American and African Portuguese). Variants are possible too (used by French dictionary, which comes in four variants).

SE checks the existence of `pt_NoBreakAfterList.xml` (all Portuguese flavours), `pt_names.xml` and  `pt_names_user.xml`. The prefix must be an ISO 639-1 Code.

For the OCRFixReplaceList and OCRFixReplaceList_User files the prefix must be an ISO 639-2 Code. For languages with two ISO 639-2 Codes, only one of them will be valid to SE (e,g. nld ⇒ Dutch, while dut ⇒ invalid).

To see the languages that SE can support on **your** computer with **your** operating system, select **Tools > Fix common errors** (list of available languages on the right).

**Comment by ticao2** [comment]
Apparently a file **pt_names_user.xml** is not used as much when selecting the Portuguese language of Brazil as Portuguese of Portugal.
When I enter a new name, it is added to the **pt_names.xml** file. And not in the **pt_names_user.xml** file.

I'm probably doing something wrong.

**Comment by xylographe** [comment]
No, you're absolutely right. _I_ was wrong! I looked a bit closer at `NameList.Add()`, and it doesn't use `xx_names_user.xml` at all. The so-called `LocalNamesFileName` is actually one of the `xx_names.xml` files (obviously, `pt_names.xml` for Portuguese).

**Comment by xylographe** [comment]
Thank you, @ticao2.
Use of user Names lists (`xx_names_user.xml`) is restored in commit 5828cec1d189fe9df8fe5014601400dd9b2cef0b.

**Comment by ticao2** [comment]
Perhaps it is interesting to leave here the **complete example** in Portuguese:

pt_BR.aff
pt_BR.dic
pt_BR_user.xml

pt_names.xml
pt_names_user.xml
pt_NoBreakAfterList.xml

por_OCRFixReplaceList.xml
por_OCRFixReplaceList_User.xml

**Comment by xylographe** [comment]
Also, `names.xml` is used independent of subtitle language.
