### ISSUE TITLE
Feature req: Move subtitles upwards in full screen viewer

### ISSUE THREAD

**Issue by gh658804** [SubtitleEdit/subtitleedit#3939]
As is now, fullscreen viewer is nice enough to let you see a video comfortably, in order to add/edit subtitles, however when you move the mouse, the toolbar appears and is shown over the subtitles (which is irritating). It would be nice if this didn't happen (move subtitles upwards so that the seek-bar does not hide them) or if there were two (numeric) settings, one to define the height of the black subtitles area and another to defined how many pixels of "whitespace" to leave below the subtitles (so the higher this number is, the more upwards the subtitles would be moved).

**Comment by OmrSi** [comment]
I think if you use MPV, you won't face this issue.
