### ISSUE TITLE
SSA & ASS properties don't swap

### ISSUE THREAD

**Issue by DKqwerty** [SubtitleEdit/subtitleedit#3941]
When working with either Sub Station Alpha or Advanced SSA, if user changes "properties" for the current format, switching to the other prevents any updates to the new format. Settings persist between formats, but are not added to the source text of the new format.

For example:
- Start with an ASS file (or just take another format and switch to ASS) and move to 'source view' tab
- Open "Advanced Sub Station Alpha properties" from 'File' menu
- Change the title to "TEST" (and/or any other changes) and accept changes
- Title will be added or changed to "TEST" in source
- Now switch the format to SSA and open "Sub Station Alpha properties"
- Note that "TEST" is the current title (but missing from source)
- Now change the title to "FOO" (and/or any other changes) and accept changes
- Note that none of the changes take effect
- After switching format back to ASS, all changes to properties will now propagate in source

_(Same is true when going from SSA > ASS)_

The only way to resolve this is to save in another format (eg. ASS > SRT), close the program, then open intermediate format and swap it to the other (eg. SRT > SSA).

Using 3.5.13 on Windows 10 Pro x64.

**Comment by niksedk** [comment]
thx for the info :)
How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip ?
