### ISSUE TITLE
Is it possible to add an option to remove the text(usually names) behind ":" at the start of each line in the tool that removes text for hearing impaired?

### ISSUE THREAD

**Issue by Ormendahl** [SubtitleEdit/subtitleedit#3943]
Example: https://i.imgur.com/HUYepDU.png?1

So it removes all the names before the ":" in the whole subtitle

**Comment by OmrSi** [comment]
What about this?
![image](https://user-images.githubusercontent.com/20923700/73019204-cf42d180-3e2b-11ea-86b8-b80b0aefbe4d.png)

**Comment by Ormendahl** [comment]
Thank you @OmrSi , how did i miss that smh. You can remove this thread.
