### ISSUE TITLE
In version 3.5.13, you can't apply color to just one line of text.

### ISSUE THREAD

**Issue by OhaengCha** [SubtitleEdit/subtitleedit#3945]
![3511](https://user-images.githubusercontent.com/60292505/73122373-858eee00-3fc7-11ea-9f3a-15c913a87fac.jpg)

In version 3.5.11, you could apply color by selecting only one line from two lines of text. In 3.5.13 it's uncomfortable because it doesn't work.

**Comment by OhaengCha** [comment]
The inserted image is version 3.5.11.

**Comment by niksedk** [comment]
Works fine here... what happens when you click on "Color..." in version 3.5.13 ?

**Comment by xylographe** [comment]
Before,
![colorA](https://user-images.githubusercontent.com/8535293/73122478-c0703200-3f85-11ea-86e4-83b11283c296.png)

After,
![colorB](https://user-images.githubusercontent.com/8535293/73122482-ca923080-3f85-11ea-8a5c-9026dec5c4d5.png)

**Comment by OhaengCha** [comment]
![3513](https://user-images.githubusercontent.com/60292505/73122539-74df7780-3fc9-11ea-8246-85c7e05f354b.jpg)

In 3.5.13 version, the 'Color' item is not visible. I use different colors to distinguish song titles and lyrics, but it's uncomfortable because it suddenly disappears.

**Comment by OhaengCha** [comment]
![3513-1](https://user-images.githubusercontent.com/60292505/73122552-b1ab6e80-3fc9-11ea-908f-94ec140f3c47.jpg)

**Comment by niksedk** [comment]
Could you take a screenshot with the whole window, so we can see what subtitle format you're using. Not all formats supports color.

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

**Comment by OhaengCha** [comment]
![wow](https://user-images.githubusercontent.com/60292505/73130200-28cb1c00-4037-11ea-836c-08716d86d50b.jpg)
Thank you very much. The problem is solved. I was worried that most of the smi subtitle format is in Korea.
