### ISSUE TITLE
UI issue in latest beta

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3947]
I thought it would be better to open a separate issue for this.
There is something wrong with the spacing in the lastest beta, could be because of https://github.com/SubtitleEdit/subtitleedit/commit/6165d51eee9d1c303ecc6d0e545bdb5d941bb052
![Screenshot (546)](https://user-images.githubusercontent.com/20923700/73127574-07cce180-3fcb-11ea-992e-70fb0af3f42a.png)

**Comment by OmrSi** [comment]
Looks like changing the `18` in `numericUpDownDuration.Left = textBoxListViewText.Left - numericUpDownDuration.Width - 18;` to about `65` does it

**Comment by xylographe** [comment]
I'm using this,
```
                timeUpDownStartTime.SetAutoWidth();
                numericUpDownDuration.Left = timeUpDownStartTime.Right + 4;
                labelDurationWarning.Left = numericUpDownDuration.Left;
                labelDuration.Left = labelDurationWarning.Left;
```

**Comment by xylographe** [comment]
@OmrSi
Could you test [this branch](https://github.com/SubtitleEdit/subtitleedit/tree/xg/issue3947) on Win10?
[Use **`-Archive https://github.com/SubtitleEdit/subtitleedit/tree/xg/issue3947`** instead of  **`-Master`**,]

**Comment by OmrSi** [comment]
@xylographe I'm getting:
![image](https://user-images.githubusercontent.com/20923700/73136587-d9e1ae80-4057-11ea-8b99-5cca839f7773.png)

**Comment by xylographe** [comment]
Sorry,wrong URL. Should be
```
-Archive https://github.com/SubtitleEdit/subtitleedit/archive/xg/issue3947.zip
```

**Comment by xylographe** [comment]
Result on Win7,

![se-main](https://user-images.githubusercontent.com/8535293/73136758-8704f880-4051-11ea-93e9-20da59f88035.png)

**Comment by OmrSi** [comment]
Looks good here as well:
![image](https://user-images.githubusercontent.com/20923700/73136846-eddadf80-405a-11ea-8234-ac398970a2cb.png)

**Comment by xylographe** [comment]
Thank you, @OmrSi.

**Comment by OmrSi** [comment]
@xylographe Thank YOU. :D

**Comment by niksedk** [comment]
Good vibes :)
Also looks good on Linux.
