### ISSUE TITLE
Snap packaging for Linux

### ISSUE THREAD

**Issue by NickZ** [SubtitleEdit/subtitleedit#3952]
After getting tired of the rigamarole of downloading the right packages and setting the right configuration to get SE working on Linux, I decided to create a Snap package. This Snap package packages up the whole required dependencies and environment necessary to run SE on Linux, and it can be run on every single distro that supports Snap packages (which is most of them). 

You can find it here: https://github.com/NickZ/subtitle-edit-snap

Please provide feedback and report any bugs you find there.

**Comment by NickZ** [comment]
For the build of Subtitle Edit that I'm using in this, I'm currently depending on a few hanging PRs:

#3873 
#3951
and the [xg/issue3851 branch](https://github.com/SubtitleEdit/subtitleedit/tree/xg/issue3851) (which partly fixes #3851)

**Comment by lxs602** [comment]
Hi, I gave it a try. It worked well and without problems. L

**Comment by Signy13** [comment]
I started writing notes to this version and it ended up as a small comparison on Xubuntu 18.04.

**Snap package**
Plus:
* It is able to OCR subtitles with native Tesseract.
* Easy installation.

Minus:
* SubtitleEdit appeared in Development menu (Multimedia might be better).
* It looks weird. 
* Open file dialog has weird My computer, missing icons...
* Not able to write correct letters with diacritics. I wrote text: `Příliš žluťoučký kůň úpěl ďábelské ódy`.
* Not able to select more than two lines in grid by SHIFT+UP/DOWN keys.
![SubtitleEdit_12](https://user-images.githubusercontent.com/18901924/79071017-8cc9bc00-7cd9-11ea-9ce0-bf75d2bcb262.png)
![SubtitleEdit_15](https://user-images.githubusercontent.com/18901924/79071027-93583380-7cd9-11ea-9d85-5b40ba7141f7.png)

**Mono JIT compiler version 4.6.2** (Debian 4.6.2.7+dfsg-1ubuntu1)
Plus: 
* It is able to OCR subtitles with native Tesseract.
* I like the look of the Open dialog - except the list in My computer, not very useful.
* Not too difficult to install.

Minus:
* It does not have completely native look (different font). But I could live with it.
* Not able to write correct letters with diacritics. I wrote text: `Příliš žluťoučký kůň úpěl ďábelské ódy`.
* Not able to select more than two lines in grid by SHIFT+UP/DOWN keys.
![SubtitleEdit_13](https://user-images.githubusercontent.com/18901924/79071061-d3b7b180-7cd9-11ea-9720-dd6e9048a211.png)
![SubtitleEdit_16](https://user-images.githubusercontent.com/18901924/79071066-da462900-7cd9-11ea-93c5-6912ee2cc968.png)

**Wine 5.0 + dotnet40**
Plus:
* Native look (colours and font).
* @niksedk fixed problems with empty Language comboBox (OCR method) - OCR was not working without this fix.
* Writing letters with diacritics works.
* Selecting lines in grid by SHIFT+UP/DOWN keys works.

Minus:
* Not easy installation. Using PlayOnLinux and not upgrading Wine (it might break SubtitleEdit) is probably a good idea.
* Using original .NET SW from Microsoft.
* Not completely happy with Open file dialog - but list in My computer is OK.
![SubtitleEdit_14](https://user-images.githubusercontent.com/18901924/79071077-f2b64380-7cd9-11ea-85e7-6d06eaedec56.png)
![SubtitleEdit_17](https://user-images.githubusercontent.com/18901924/79071079-f5189d80-7cd9-11ea-8ef8-68a9321919fe.png)

BTW: There is a possibility to run SubtitleEdit on Wine 3.21 with mono installed inside Wine. It works, but operations with SubtitleEdit are rather slow (for example delete a subtitle/row in grid takes some time). Look is not native, but I could live with it. But Wine 5.0 with dotnet40 is probably better option.

**Conclusion**
I do not know why writing letters with diacritics does not work under Mono. It is not just different letter written. Once I use dead key the behaviour is completely crazy - I hit a key three times and it does print nothing and then I hit another key and it writes three times the last letter I wrote with the dead key...
I am not sure whether it is just on my computer, but I can not use SubtitleEdit with Mono at all...

**Comment by lxs602** [comment]
@Signy13 

You're using an old mono version. It might well help to upgrade:

https://www.mono-project.com/download/stable/#download-lin-debian

**Comment by Signy13** [comment]
Thanks for your adice - Mono from Xubuntu 18.04 repository was pretty old (4.6.2) in comparison with this new one 6.8.0.105 (tarball Tue Feb  4 21:20:20 UTC 2020). 

I updated Mono but results are pretty the same: I can not write letters with diacritics correctly (when I type `ďábelské` it writes `ďďbelskď`) etc. 
Screenshots with  Mono 6.8.0.105
![SubtitleEdit_30](https://user-images.githubusercontent.com/18901924/79119031-a75e6c80-7d8f-11ea-8a03-51d647f0f940.png)
![SubtitleEdit_31](https://user-images.githubusercontent.com/18901924/79119036-a9283000-7d8f-11ea-9ec5-3ad076744012.png)

.

**Comment by lxs602** [comment]
Perhaps search for anyone else having problems with mono programmes and diacritics?

I found this thread, though it is a very old: https://ubuntuforums.org/showthread.php?t=1467124 . 

Alternatively, you could try Ubuntu 20.04 in a few days time.

**Comment by niksedk** [comment]
I would guess it's a mono issue: https://github.com/mono/mono/issues/17029

**Comment by Signy13** [comment]
Yes, it is probably a Mono bug - but I do not mind -  for me Wine is better option.

**Comment by rezad1393** [comment]
can this great program be make as a flatpak package?

**Comment by dausruddin** [comment]
Can we get an update for the latest one?

**Comment by CodeCubeNeo** [comment]
I would also like for this app to be available as a flatpak.

**Comment by CodeCubeNeo** [comment]
Why is this closed?

**Comment by niksedk** [comment]
Sprint cleaning... of inactive issues.
