### ISSUE TITLE
Without audio edit

### ISSUE THREAD

**Issue by serquis** [SubtitleEdit/subtitleedit#3953]
Should be able to drag subtitle length in waveform editing area without audio.

I think need it.
e.g. Desktop capture movie, silent movie etc...

**Comment by niksedk** [comment]
OK, I've tried to fix this in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zipHow does that work for you?

**Comment by serquis** [comment]
I tried the beta version.

It is working perfectly. Works as I thought.

Thank you very much :D

**Comment by niksedk** [comment]
Thx for verifying :)
