### ISSUE TITLE
Thread Exception when attempting to add waveform

### ISSUE THREAD

**Issue by rbfaerch** [SubtitleEdit/subtitleedit#3955]
In several MP4 files, when clicking below in the add waveform the following exception is shown. I've setup my Subtitle Edit to use VLC player.
![Error](https://user-images.githubusercontent.com/60399392/73284713-4219c700-41f5-11ea-8c88-684a6e759a82.jpg)

**Comment by niksedk** [comment]
SE needs write access to data folder.
So try uninstalling SE ( + delete "Subtitle Edit" folder under program files).
Then use the installer if you want SE in program files or use the portable version and unpack to something like C:\Tools\SE.
