### ISSUE TITLE
Generated filenames being truncated

### ISSUE THREAD

**Issue by beeeeswax** [SubtitleEdit/subtitleedit#3956]
Using 3.5.13 on Win10 1909 64-bit.

If I open a .ts file (teletext) and save the resulting srt, SE attempts to generate the srt filename using the original .ts file's name.  It's using some kind of splitting technique to rebuild this filename though because dots in certain places cause it to truncate the filename.

Example .ts filename that will cause the problem:

ShowName.S01E01.1080p.HDTV.DD2.0.H.264-RlsGrp.ts

Results in an output srt filename of: ShowName.S01E01.1080p.HDTV.DD2.0.H.srt

This bug seems to occur anywhere in SE where a filename is generated from the input source filename, including batch jobs.

It seem from the "Similar issues" list, this is a regression as it was supposedly fixed here: [https://github.com/SubtitleEdit/subtitleedit/issues/3716](url)

I don't have any weird settings enabled in Explorer and I have filename extensions enabled.

**Comment by xylographe** [comment]
Looks like SE takes the base name `ShowName.S01E01.1080p.HDTV.DD2.0.H.264-RlsGrp` (without the `.ts`), before it strips the extension, which, of course, is no longer the ‘real’ extension.

**Comment by xylographe** [comment]
Most likely, **`Path.GetFileNameWithoutExtension()`**, without doing a **`fileName.EndsWith(".ts")`** first.
