### ISSUE TITLE
settings to remember last values

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#3957]
These are not really bugs, but two settings are not remembered.
One is "Remove line-breaks from selected lines..." in the right click menu on lines. This is always set to 32.
Another is "Maximum characters in one paragraph" <- "Merge short lines" <- "Tools" menu. This is always set to 43.
I want them remember the last value that I set.

I also hope "Maximum milliseconds between lines" to be limitless. Now 2000 is its hard limit.

**Comment by OmrSi** [comment]
I believe those two depend on your settings:
![image](https://user-images.githubusercontent.com/20923700/73361072-e3b01f80-42ac-11ea-8461-ecc0ac132749.png)

**Comment by taxen** [comment]
I missed the setting. Having set "Unbreak subtitles shorter than" option to 10 (current minimum value), and yet "Remove line-breaks from selected lines..." is set to 9 by default. Since 5 is the minimum there, I think the minimum value of "Unbreak subtitles shorter than" option should be also 5.
