### ISSUE TITLE
This Format?

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3959]
Hi,
Is it possible for SE to read the following format? I think the issue is that timing is only two values: minutes, seconds. I had to add milliseconds via regex to make it work. 
[New Text Document.txt](https://github.com/SubtitleEdit/subtitleedit/files/4127727/New.Text.Document.txt)

**Comment by niksedk** [comment]
Yes, the timing is too difficult for the auto-guess-time-code module... 
New custom format in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip (Unknown 94)

**Comment by niksedk** [comment]
How does this format look when time codes go over 60 minutes?

**Comment by uckthis** [comment]
No idea, man. They were hand written by some guy and i had to convert to srt.
