### ISSUE TITLE
Visual Sync not working with mpv

### ISSUE THREAD

**Issue by Ouroboros1995** [SubtitleEdit/subtitleedit#3960]
![Untitled](https://user-images.githubusercontent.com/60438566/73371163-8ff60400-42b5-11ea-9dc2-a7c46ba836e7.png)
Visual sync not working when using mpv as the main player.
Complete program simply freeze and then I get the following error.

**Comment by OmrSi** [comment]
Wait, How did you get that theme?!
Here is what it looks like when I use SE's dark theme:
![image](https://user-images.githubusercontent.com/20923700/73374231-8cb54500-42c2-11ea-813b-1ecfed955b20.png)

**Comment by Ouroboros1995** [comment]
I use Penumbra Windows theme (you can get it on Deviantart), alongside explorer, it also makes other programs dark. Except for subtitle fields, I ve set the colors for them directly in Subtitle Edit (black for the background and white/gray for text). I think this particular mix of greys and blacks is really the best for eyes and prolonged work in this program.

**Comment by OmrSi** [comment]
Cool. I installed it, BTW.
And Visual Sync works fine here with and without it.

**Comment by Ouroboros1995** [comment]
Fixed in the newest beta!

I ve used the newest version of mpv with this beta and UI didnt get unresponsive, with previous versions of SE, whenever I use the latest version of mpv, UI instantly gets unresponsive, now thats not the case.

_Originally posted by @Ouroboros1995 in https://github.com/SubtitleEdit/subtitleedit/issues/3476#issuecomment-580721523_

**Comment by Ouroboros1995** [comment]
Again after nesest beta, visual sync doesn't work with mpv player.
