### ISSUE TITLE
[Bug] Windows exception when opening original subtitle without an open file

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3964]
I usually just open SE and use "Open original subtitle" and open a file, then SE creates the main file from the original file, it's like a shortcut instead of opening the file then using "Create Empty file from current subtitle", but sometimes I get this error:
![image](https://user-images.githubusercontent.com/20923700/73551134-86ec6a80-444e-11ea-9b21-c309a21582c3.png)

And SE works just fine if you ignore it.

**Comment by niksedk** [comment]
thx - should be fixed now :)

**Comment by OmrSi** [comment]
Yep. Thank you.
