### ISSUE TITLE
Checkbox to skip capitalized words for spell check?

### ISSUE THREAD

**Issue by rhazor** [SubtitleEdit/subtitleedit#3969]
To be exact only words that are in the middle of the sentence, not the starting sentence word that is always capitalized.

For foreign subtitles names, places, brands, etc. are not translated, but they always start with capital letter and you end up clicking Skip All 200 times each time.

**Comment by valnar1** [comment]
Was this completed?  I don't see the option.  I too would like to skip capitalized words instead of being prompted.
