### ISSUE TITLE
UTF-8 or UTF-8-BOM?

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3972]
Hello,
Recently one of my client sent back one of the file I sent saying it was UTF-8-BOM when they want a UTF-8. Frankly, I didn't and don't the difference between the two. Encoding was set to UTF-8 in SE, but when I checked the encoding in Notepad++ it was UTF-8-BOM and I converted it with Notepad++. 
Is it possible to rename the current encoding as UTF-8-BOM and add another encoding which is UTF-8?
Thank you.

**Comment by xylographe** [comment]
Which subtitle format?

**Comment by uckthis** [comment]
@xylographe SRT. Any file. Open with Notepad+= and under encoding it says UTF-8-BOM.

**Comment by niksedk** [comment]
@uckthis: To change the encoding "UTF-8" in SE to save without BOM is a bad idea as SE has always written UTF-8 with BOM (except for a few formats that requires the absence of BOM). Also, some programs require presence of an UTF-8 BOM to function correctly.

In a perfect world UTF-8 without BOM would suffice, but there are still a lot of people using other encoding types, e.g. ANSI encoding (which naturally sucks) . The BOM is an excellent way to tell computers how a file is encoded and is by default added to UTF-8 files when using .NET framework.
Some programs (especially on Linux) cannot handle BOM and file appending can also give problems regarding BOM.

In SE, perhaps "UTF-8" could be split into "UTF-8 with BOM" and "UTF-8 without BOM"...

**Comment by uckthis** [comment]
@niksedk You know best. Splitting is how they do it in Notepad++. 
Default should be UTF-8-BOM and if someone needs without BOM, he can just switch it.

Thank you.

**Comment by niksedk** [comment]
@uckthis: How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip ?

**Comment by uckthis** [comment]
@niksedk Perfect!

**Comment by niksedk** [comment]
Closed via commit 0f28d058ccb2c5942d95cdbf182c526b02641a63
