### ISSUE TITLE
[Bug] opening original subtitle with no time codes doesn't work

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3974]
If you have two files with no time codes, if you open one as the original you get:
![image](https://user-images.githubusercontent.com/20923700/74085869-37c5bb80-4a86-11ea-9e65-8bad69c47fca.png)

Another bug: when you set the start of a line and it takes an auto duration:
![image](https://user-images.githubusercontent.com/20923700/74085967-3c3ea400-4a87-11ea-8c8f-5e080356be0d.png)

**Comment by niksedk** [comment]
Hm, I cannot follow/replicate your - could you explain a bit more?

**Comment by OmrSi** [comment]
Sure.
For the 1st one, import a plain text the save then make an empty subtitle of the current file.
Close the original subtitle and open it again.

For the 2nd, set the start of a line.

**Comment by niksedk** [comment]
1) I still don't get it... sorry!

**Comment by OmrSi** [comment]
Hmm, I can not recreate it, I have not Idea why.
I timed the files so I don't have a version of them when the issue occurred. Sorry.

But a similar thing happens when you open the file as Original. Open this file as original without opening any subtitle: 
[1.zip](https://github.com/SubtitleEdit/subtitleedit/files/4181912/1.zip)

**Comment by niksedk** [comment]
about (2) - how do you set the "start"?

**Comment by OmrSi** [comment]
F11 or my shortcut for setting the start, both cause the same thing.
Using the mouse with shift doesn't work in the first place.

**Comment by niksedk** [comment]
I fix something... hopefully what you found? ;)

**Comment by OmrSi** [comment]
It still takes one line if you open just the original:
![image](https://user-images.githubusercontent.com/20923700/74187715-d18f9300-4c55-11ea-9794-078ee83c6a35.png)

Weird thing is, if you use "Switch original and translation" you get:
![image](https://user-images.githubusercontent.com/20923700/74187797-f257e880-4c55-11ea-8bb4-14bbfa98a101.png)

**Comment by niksedk** [comment]
Ah, you're missing lines... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Works great. :D
Thank you.
The shortcut is still doing the same, but I don't think you tried, or want, to change how it works.
