### ISSUE TITLE
Recognized duration of some SUP subtitles much longer than on Blu-Ray

### ISSUE THREAD

**Issue by mgutt** [SubtitleEdit/subtitleedit#3980]
SUP File:
https://www.dropbox.com/s/dpqhjhgyw25c2o9/ger.forced.sup?dl=0

Result (used 3.5.13):
![2020-02-09 12_54_29](https://user-images.githubusercontent.com/10757176/74101635-2dfe8f80-4b3c-11ea-8e9a-f9a64f371dc6.png)

SUP was extracted from Blu-Ray rip through mkvextract.

**Comment by niksedk** [comment]
Thx for the file :)
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

**Comment by mgutt** [comment]
> Should be fixed in latest beta
It is. Thank you.
