### ISSUE TITLE
Custom DPI UI/text cropped

### ISSUE THREAD

**Issue by Gittyperson** [SubtitleEdit/subtitleedit#3981]
Hello,

Not sure when this occurred but it must be a recent issue since I've been using SE for a long time on the same monitors/DPI setting. I tried resetting SE's settings and also played with the Compatibility/high DPI Windows fixes with no luck.

I am set on Custom 125% DPI. "Standard" DPI solves this (both 100 and 125%) but becomes blurry.

![Subtitle Edit DPI](https://user-images.githubusercontent.com/7165208/74102920-8cce0400-4b50-11ea-8628-4ce382fdb902.png)

Windows 10 x64 1909 (18363.592), SE 3.5.13 x64 Portable

![Subtitle Edit DPI settings](https://user-images.githubusercontent.com/7165208/74102919-8c356d80-4b50-11ea-8231-7ce2a515ed7c.png)

**Comment by Gittyperson** [comment]
Tried 3.5.12: issue is there.
Tried 3.5.11: issue is not there.

**Comment by niksedk** [comment]
How is latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

**Comment by Gittyperson** [comment]
Thanks, this beta solves most of these.

Start time/Duration boxes are now ok. The "Start time/Duration" text remains slightly cropped but it's not an issue.

Below them, Create/Adjust sections: the "Go to sub position" boxes remain slightly cropped to the right. Adjust/Video position text blends with the numbers. Perhaps these are caused by the video player window which goes too far on the left, squashing the section on the left.

Some longer text is also cropped in a few Settings sections but it's not really an issue (Video player and Font).

**Comment by niksedk** [comment]
Minor improvements here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

Are there any big issues left?

**Comment by Gittyperson** [comment]
Thanks again, it's fine as it is. I only hope you could fix those two boxes too because the last number is barely visible. Occurs in both Create/Adjust and with either Waveform/Video being on bottom.


![SE boxes](https://user-images.githubusercontent.com/7165208/74105510-34eec780-4b67-11ea-9dcd-7e293e49484b.png)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

**Comment by Gittyperson** [comment]
Perfect.
