### ISSUE TITLE
Error when try to fix Spanish Inverted Questions

### ISSUE THREAD

**Issue by Lokotito** [SubtitleEdit/subtitleedit#3984]
I found an error when i try to us "Fix Common Errors" (Crtl+Shit+F) in a Spanish SRT subtitle.
Only selecting "Fix Spanish inverted questions and exclamations marks" the error appears.
Attached error screen and SRT subtitle:

![Captura](https://user-images.githubusercontent.com/12678696/74249587-c5402000-4cbf-11ea-87dc-810a12dfc438.JPG)
[https://mega.nz/#!JCRmmAyY!jy4pF_AwF-qjpFTQV2LQnDZ5QXJV9J2FsWblPDo-vb4](url)

**Comment by Lokotito** [comment]
Sorry, this will fixed in the next release of SE?

**Comment by OmrSi** [comment]
@Lokotito Yes. Also in the beta version https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip
