### ISSUE TITLE
Requesting some new features

### ISSUE THREAD

**Issue by YouKnow-sys** [SubtitleEdit/subtitleedit#3985]
Hi
i think it would be great if  you add a **batch converter** for **convert** any Subtitle to vobsub in one click
also convert multi Subtitle to any other format at once will be a good idea too

also when i try to convert ass sub to vobsub I have a problem
when i try to convert ass sub to vobsub i cant use any style or font
So I need to convert ass to srt before convert to vobsub but when i do that, some line are missing
for example
this screenshot with ass sub
![image](https://user-images.githubusercontent.com/17937017/74377291-db9dc700-4df8-11ea-95e5-9b4df41451d2.png)
this screenshot with (ass=>srt) and then convert to vobsub
![image](https://user-images.githubusercontent.com/17937017/74377518-4b13b680-4df9-11ea-8586-098d6be04921.png)
ass you can see some sub line are missing 
can you fix this?
i think its becuse sub timing

**Comment by OmrSi** [comment]
You mean like Tools -> Batch convert?

**Comment by saeid0034** [comment]
> You mean like Tools -> Batch convert?
yes it will be great
also anywaye to fix vobsub problem?

**Comment by saeid0034** [comment]
any luck to add this?

**Comment by LustigKnorre** [comment]
No expert at this, but I don't think .srt can handle text both at the bottom and top of the screen.

What you are asking is already in the program. What language are you using in the program?
In English it is under "tools -> Batch Convert" but I know that in Swedish for example the translation is very strange so it might be difficult to find if the tranlation to your language is wrong.

I'll attach a picture so you know where it is, it is in Swedish but it should(?) be in the same place for you.
OmrSi said this in an earlier answer, but I don't think you understood if you are using the program in a different language.
![se batch convert location](https://user-images.githubusercontent.com/39223156/74573188-92787f00-4f80-11ea-8ec9-9a179950eec6.jpg)

**Comment by saeid0034** [comment]
> No expert at this, but I don't think .srt can handle text both at the bottom and top of the screen.
> 
> What you are asking is already in the program. What language are you using in the program?
> In English it is under "tools -> Batch Convert" but I know that in Swedish for example the translation is very strange so it might be difficult to find if the tranlation to your language is wrong.
> 
> I'll attach a picture so you know where it is, it is in Swedish but it should(?) be in the same place for you.
> OmrSi said this in an earlier answer, but I don't think you understood if you are using the program in a different language.
> ![se batch convert location](https://user-images.githubusercontent.com/39223156/74573188-92787f00-4f80-11ea-8ec9-9a179950eec6.jpg)

tnx for your help i find batch convert tool
But about the second question
Is vobsub support subtitle in bottom and top of the screen?
If not, is there any other subtitle format that looks like **vobsub** and support sub in **bottom and top of the screen** too?

**Comment by uckthis** [comment]
Have two subtitles of similar start and end time. Place one on top of screen and other at the bottom. There's no other way of doing that in SRT.

**Comment by saeid0034** [comment]
> Have two subtitles of similar start and end time. Place one on top of screen and other at the bottom. There's no other way of doing that in SRT.

It is possible to merge two line with same start time or Or near times? like
![image](https://user-images.githubusercontent.com/17937017/74592669-c31bef80-5038-11ea-96b1-d3993c24b486.png)
to
![image](https://user-images.githubusercontent.com/17937017/74592688-08d8b800-5039-11ea-9f10-fd10eda31892.png)

**Comment by uckthis** [comment]
@saeid0034  Yes, there's an option under Tools -> Merge lines with same timcodes... but the whole idea is that you don't merge and have one at top and other at bottom...

If you think that Swedish translation can be better, please help updating it.

**Comment by saeid0034** [comment]
> @saeid0034 Yes, there's an option under Tools -> Merge lines with same timcodes... but the whole idea is that you don't merge and have one at top and other at bottom...
> 
> If you think that Swedish translation can be better, please help updating it.

Some lines have different but almost identical times
What about them
and I'm not Swedish and I use English lang in the program
Maybe I can help translate the program into Persian

**Comment by uckthis** [comment]
@saeid0034  Almost identical is not identical. You'd have to merge them manually.

**Comment by saeid0034** [comment]
> @saeid0034 Almost identical is not identical. You'd have to merge them manually.

It's great if add a feature to merge lines with similar times
like

`00:17:02,370 --> 00:17:06,610
*test 1*`
`00:17:03,350 --> 00:17:10,610
*test 2*`
**merge to**
`00:17:02,370 --> 00:17:10,610
*test 1* - *test 2*`

**Comment by ivandrofly** [comment]
> Maybe I can help translate the program into Persian

https://github.com/SubtitleEdit/XmlContentTranslator

**Comment by ivandrofly** [comment]
> > @saeid0034 Almost identical is not identical. You'd have to merge them manually.
> 
> @niksedk @ivandrofly
> It's great if add a feature to merge lines with similar times
> like
> 
> `00:17:02,370 --> 00:17:06,610 |test 1|`
> `00:17:03,350 --> 00:17:10,610 |test 2|`
> **merge to**
> `00:17:02,370 --> 00:17:10,610 |test 1 - test 2|`

Maybe this weekend I will take a look at this!

**Comment by saeid0034** [comment]
> Maybe this weekend I will take a look at this!

tnx I think it's great for converting subtitles from **ass/ssa** to any other sub like **srt** and **vobsub**
Because they do not support some **ass/ssa** display formats like show **multi line** at once

**Comment by ivandrofly** [comment]
> tnx I think it's great for converting subtitles from **ass/ssa** to any other sub like **srt** and **vobsub**
> Because they do not support some **ass/ssa** display formats like show **multi line** at once

By increasing the "Max. milliseconds difference" can help solve the problem (see the image below), unless you want something specific...

![image](https://user-images.githubusercontent.com/6579818/75173045-2d621d80-5726-11ea-9de5-4a5615a2a368.png)

**Comment by ivandrofly** [comment]
Should there be a checkbox that for example "Always merge on overlaps" in (Merge lines with same time codes form) - so when it's checked both of the paragraphs should be merged as long as one of the time codes is within the threshold: `a2-a1 < = maxms or b2-b1 <= minms`?

@niksedk

**Comment by saeid0034** [comment]
> Should there be a checkbox for example "**Always merge on overlaps**" in (Merge lines with same time codes form) - so when it's checked both of the paragraphs should be merged as long as **the difference** of one of the time codes is within the threshold: `a2-a1 <= maxms or b2-b1 <= minms`?
> 
> ### Note:
> a = represents start-time
> b = represents end-time

it will be great 
look at these Three line for example
![image](https://user-images.githubusercontent.com/17937017/75182540-e3912b80-5755-11ea-9540-de5d9d786ab2.png)


Their times are not exactly alike but also their times are intertwined
subtitle edit needs an option to find and merge this line too

**Comment by saeid0034** [comment]
any chance?
