### ISSUE TITLE
GUI Batch convert eating memory.

### ISSUE THREAD

**Issue by LustigKnorre** [SubtitleEdit/subtitleedit#3990]
Hi,
I noticed that when I run mass numbers of subtitles through Batch convert the memory usage gets huge after a while.
If I run a memory "cleaner" it drops down again. 
Could you add some some code to release the old file in memory after each file? (if that is how it works)

And after 1895 files I get some kind of error.
![se batch convert error](https://user-images.githubusercontent.com/39223156/74574423-f0f32c80-4f83-11ea-8ab4-398f63b414de.jpg)
It is below the blue line, roughly translated from Swedish:
"Replace multiple/batch convert: It was not possible to create window reference."

And one last thing. Is it possible to suggest a translation change?
I changed it in my installation but it gets over written when I update the program. And now I have learned where it is.
But in Swedish the "Tools --> Batch convert" is translated to " --> Konvertera stycke" and that is very missleading. Translating that back to English becomes "Convert paragraph".... and... yeah.
I think it should be "Batch konvertera" or maybe "Konvertera flera" meaning "convert many"

/Cheers

**Comment by GitGerby** [comment]
Seeing memory leaks with the command line version as well on 3.5.18; input files are mkv with a specified output of subrip.

**Comment by GitGerby** [comment]
ignore my last comment, this was an environment specific issue that just happened to coincide with every launch of the cli.

**Comment by Candyffm** [comment]
I have seen that problem as well. Subtitle Edit is currently hovering at around 10GB (of 32GB) of RAM usage in batch mode, OCR performance is getting terrible (with little to no cpu usage) and the GUI is unresponsive (I minimized the batch window and I am no longer able to restore the window).
