### ISSUE TITLE
[Bug] Opening original without an opened file resets Recent Files

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3991]
When I use open original without an open file, the Recent Files are deleted.
Reopen becomes empty.

**Comment by OmrSi** [comment]
Looks like it happens because the file name is empty.

**Comment by OmrSi** [comment]
Now you have the original file in the recent menu which, if you open it, open the original and itself as an original file. But I guess it's better than deleting the whole list.
Thank you.

**Comment by OmrSi** [comment]
I just noticed that it also always opens the most recent file when I open SE even if you close it before closing SE.
But I haven't tested after the last 2 commits.

**Comment by niksedk** [comment]
He, yes - that's what the second last commit is for... and the last commit is for a crash.

**Comment by OmrSi** [comment]
Cool.
The original is now shown in the recent files as well, but if you open it, it opens alone.
I guess that's as good as it can get. :D
Thank you.

**Comment by OmrSi** [comment]
@niksedk Just noticed something new.
Now when you open a file and open its original, you'll get both files in the "Recent files".
So, Look what happens when you open another file with a file that has an original opened:
![Untitled Project](https://user-images.githubusercontent.com/20923700/74789606-e0adbb00-52bd-11ea-9bd3-02091ada2e4c.gif)

**Comment by niksedk** [comment]
@OmrSi: could you give it a test run (also in dialog style branch).
Actually found a few old errors regarding saving recent files with translations.
Also, recent files with menu will show both translation + original.

**Comment by OmrSi** [comment]
@niksedk Nice!
It's cool how translation + original are shown.
A couple of things, it's opening the most recent file again when you close and open SE.
And, When you open an original, you'll have an entry for the translation file and the translation + original, and if you remove that entry from the settings file, you'll again get an entry for the both of them.
What I'm saying is, opening an original for a file should edit the existing entry and make it translation + original, closing the original should edit the entry removing the original part so you'd get one entry for the file, either its name if no original is opened, or name + original name.
Also, now when you do the "open original" shortcut, you only get the original's name in the menu.
So if you open a file named: "a_original" then save the file that was created by the name of "a", you only get "a_original" in the menu.
I don't know if any of that is possible.

**Comment by OmrSi** [comment]
@niksedk Or maybe you can add the possibility of deleting an entry? Maybe that's easier.

**Comment by OmrSi** [comment]
@niksedk Or maybe you can add the possibility of deleting an entry by pressing "Delete" or a "Delete" option in a context menu? Maybe that's easier and a good compromise.
If someone doesn't want the repetition, he can just delete it.

And It looks like there is something wrong, each time I open a file, one of these is added:
![image](https://user-images.githubusercontent.com/20923700/74982556-03b2a900-543d-11ea-8f71-379888fab0f7.png)

**Comment by OmrSi** [comment]
@niksedk Okay, I got a better idea for a way to do this.
Bare with me, when you open original, the current entry of "translation" would be deleted and a new one of "translation + original" would be created.
Same if you close an original, "translation + original" is deleted and "translation" is created.
I think it would be easier as you would only have to delete the last entry.

**Comment by OmrSi** [comment]
@niksedk Okay, I got a better idea for a way to do this.
Bare with me, when you open original, the current entry of "translation" would be deleted and a new one of "translation + original" would be created.
Same if you close an original, "translation + original" is deleted and "translation" is created.
I think it would be easier as you would only have to delete the last entry.

Also, **another bug**.
If you open a file and go to a line, then close that file and open it again without closing SE, the index of the line isn't saved, it just goes back to the line you were on before closing SE.

**Comment by OmrSi** [comment]
@niksedk Okay, I got a better idea for a way to do this.
Bare with me, when you open original, the current entry of "translation" would be deleted and a new one of "translation + original" would be created.
Same if you close an original, "translation + original" is deleted and "translation" is created.
I think it would be easier as you would only have to delete the last entry.

This is also causing **another bug**.
The index of "translation + original" isn't saved, it always goes back to the first line when opening the it.

**Comment by OmrSi** [comment]
@niksedk 
![Untitled Project](https://user-images.githubusercontent.com/20923700/75095704-5eb0e100-55a0-11ea-8ad0-1c75856facf1.gif)

**Comment by OmrSi** [comment]
You just fixed the index issue, right?
I saw `Files.Remove(existingEntry);` in the commit so I thought you made it remove the current when opening original. Just wanna make sure.

**Comment by OmrSi** [comment]
Thank you.
You just fixed the index issue, right?
I saw `Files.Remove(existingEntry);` in the commit so I thought you made it remove the current when opening original. Just wanna make sure.

Anyway, now opening an original makes the file go to the first lines, this didn't happen before:
![Untitled Project](https://user-images.githubusercontent.com/20923700/75099210-abf47900-55c7-11ea-9ff2-ab1db2569276.gif)
