### ISSUE TITLE
[Bug] Invalid Gap values displayed in SubtitleListView after "Set start and off-set the rest"

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#3995]
I have the "Gap" column enabled in the SubtitleListView.
When you click "Set start and off-set the rest" on the Adjust tab, the gap values in the ListView are not updated correctly.
The actual gaps are correct, they just are being displayed incorrectly, until I force a refresh (e.g. by merging subtitles).

![image](https://user-images.githubusercontent.com/3516155/74613479-15c7db00-510f-11ea-90be-44bf4425717c.png)

**Comment by niksedk** [comment]
thx :)
Can hardly remember a smaller change.
