### ISSUE TITLE
Cursor goes to start

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3996]
Hello,
After applying any of the following, cursor goes to the start of the text.

**Move last word to next subtitle
Fetch first word from next subtitle**

Why? Is it possible for cursor to remain in the same position?

**Comment by OmrSi** [comment]
@niksedk Can you do this for "Break at first space from cursor position" as well?

**Comment by niksedk** [comment]
@OmrSi: I think the cursor is okay here... ?

**Comment by OmrSi** [comment]
@niksedk You mean it's okay as it does return to its place or as it's normal for it to go to start?
If it's the latter, then it's not a big issue.

**Comment by niksedk** [comment]
@OmrSi: Here the cursor goes the end of broken line...

**Comment by OmrSi** [comment]
Oh, my bad.
I was using it on a line in Arabic so the cursor went to the right which is the end of the broken line but I thought it was the start. ^^"
