### ISSUE TITLE
Encoding problem in latest beta

### ISSUE THREAD

**Issue by Ouroboros1995** [SubtitleEdit/subtitleedit#3997]
Whenever I try to save subtitle with certain encoding, program always discards my choice and use utf-8 with bom instead or some random encoding.

Hope you will be able to fix this issue.

Thanks.

**Comment by niksedk** [comment]
Sorry, generally this is just not possible as "UTF-8 without BOM" and "ANSI" often is the same!
Note that ANSI encodings are obsolete and should be avoided.

Please attach file(s) if you want me to take a look at your specific issue.

**Comment by Ouroboros1995** [comment]
Where can I download previous beta version to make a comparison, then I will record my problem and upload a  link to video.

Thanks and sorry to bother you.

**Comment by niksedk** [comment]
np, feedback is welcome :)

You can find older release here: https://github.com/SubtitleEdit/subtitleedit/releases
(if you upload a video please also upload the subtitle which will make it easier for me to re-create the issue)

**Comment by Ouroboros1995** [comment]
Here you can see what the problem is:
[https://drive.google.com/file/d/1QaFSb1JcU6ic3D74tt5U4tJ6ZTSeTgIV/view?usp=sharing](url)

And this is the subtitle I have used:

https://drive.google.com/file/d/1AY0cPMEmhxigLpcZuijY9bD8xQHGezgi/view?usp=sharing

**Comment by Ouroboros1995** [comment]
I fixed it by unchecking auto detect ANSI encoding

**Comment by niksedk** [comment]
> I fixed it by unchecking auto detect ANSI encoding

Yes, I guess that's the solution.
(do love your theme)

**Comment by OmrSi** [comment]
The theme is awesome. This is exactly what SE's dark mode should look like.
