### ISSUE TITLE
LATEST BETA - After splitting dialog dashes remain

### ISSUE THREAD

**Issue by Ouroboros1995** [SubtitleEdit/subtitleedit#4002]
Dialog dashes remain in front of sentences after splitting.

**Comment by OmrSi** [comment]
Yep. My bad for not testing.
It doesn't remove them for Normal and Original.

**Comment by Ouroboros1995** [comment]
Let me  use this opportunity to ask about something unrelated, is there an option to set shortcut for line splitting? Thanks.

**Comment by OmrSi** [comment]
There are like, 4 shortcuts for line splitting.
You have:
1. Split line at cursor position.
2. Split line at cursor/video position.
3. (Waveform) Split.
4. Split selected line bilingual. (If a line contains two languages)

**Comment by Ouroboros1995** [comment]
Oh, okay, I now see that i can search shortcuts. :)
Thanks, anyway.

**Comment by niksedk** [comment]
Thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

(Split worked sunday... must have been a bug introduced in one of the latest commits)
