### ISSUE TITLE
French dictionary not included in "Use do-not-break-after list".

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#4005]
Hello,
I have installed the french dictionary but it still won't show in the list of languages in the "Use do-not-break-after list" tool.

**Comment by xylographe** [comment]
Presumably, the file `fr_NoBreakAfterList.xml` does not exist, unless you have created one,
```
PS S:\SubtitleEdit> (gci Dictionaries\*NoBreakAfterList.xml).Name
da_NoBreakAfterList.xml
en_NoBreakAfterList.xml
es_NoBreakAfterList.xml
hr_NoBreakAfterList.xml
mk_NoBreakAfterList.xml
pt_NoBreakAfterList.xml
sr_NoBreakAfterList.xml
```
You could copy `es_NoBreakAfterList.xml` (the smallest file) to `fr_NoBreakAfterList.xml`, then change its contents with Subtitle Edit.

**Comment by OmrSi** [comment]
Yep. That's what I did to make a file for my language.

**Comment by OmrSi** [comment]
@niksedk Closed?

**Comment by xylographe** [comment]
@Omri 
Perhaps, you might consider adding your `ar_NoBreakAfterList.xml` (I'm assuming you created an Arabic no-break-after list) to the SE distribution?
Either via a pull request, or by attaching the file in a comment.

**Comment by OmrSi** [comment]
I would love to, though I think it's pretty thin:  [ar_NoBreakAfterList.zip](https://github.com/SubtitleEdit/subtitleedit/files/4494661/ar_NoBreakAfterList.zip)

**Comment by xylographe** [comment]
Thank you, @OmrSi.

Arabic no-break-after list (`ar_NoBreakAfterList.xml`) added in e21ab99f742d276309abb42b7d7c6fd2301c2859.
