### ISSUE TITLE
Import plain text with time codes generate from files name.

### ISSUE THREAD

**Issue by ChuotVu** [SubtitleEdit/subtitleedit#4006]
I used VideosubFinder to extract subtitle images . After I use Abbyy OCR to text file with files name is time code, Can you add function to import plain text with time codes generate form files name similar to auto generate time code function in Import images.

Thanks. Regards

**Comment by niksedk** [comment]
Could you attach a .zip sample file?

**Comment by BlazeSeven1989** [comment]
Hello,
 
I also use Videosubfinder and have the same question as the OP so, I made some sample txt files using a short clip with Abby Finereader and will attach the zip below. Each txt file is a separate subtitle line. And the names of the txt files are the start and end times.
[Plain Txt Samples.zip](https://github.com/SubtitleEdit/subtitleedit/files/4247722/Plain.Txt.Samples.zip)


Thank you.

**Comment by niksedk** [comment]
How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip  ?

**Comment by BlazeSeven1989** [comment]
It works. :)

Thanks.
