### ISSUE TITLE
Truncated three-line subtitles with stl files

### ISSUE THREAD

**Issue by rustyjm** [SubtitleEdit/subtitleedit#4008]
I've been trying to use Subtitle Edit but I have an issue where three-line subtitles seem to be truncated even after increasing the max lines and durations in the options. Is there a fix for this at all please? I use stl files.

I've created a test file of ascending numbers to demonstrate the issue. 

Please see two images for how it should appear and what happens in Subtitle Edit.

![image](https://user-images.githubusercontent.com/61387439/75116638-66d15500-5662-11ea-8c66-2ccd08b25877.png)

![image](https://user-images.githubusercontent.com/61387439/75116648-8ff1e580-5662-11ea-8102-cde3a6714252.png)

Any guidance or fixes are much appreciated. Thanks.

**Comment by niksedk** [comment]
Thx for the info :)
SE did not read the last 16 bytes available for EBU STL text... but do note that you're very close to the max with 92 chars.

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

**Comment by rustyjm** [comment]
Fantastic - thank you very much!

**Comment by rustyjm** [comment]
That looks good so far, many thanks for that! I'll continue to test and make you aware of any issues. 
Is there a maximum number of characters? What happens if I go over that limit?

**Comment by niksedk** [comment]
The maximum size is 112 bytes - but that's with control codes and line breaks characters - so it's 95 characters for three lines.

> What happens if I go over that limit?

You will loose the last characters.

**Comment by rustyjm** [comment]
OK, many thanks for your help!

**Comment by niksedk** [comment]
np, thx for reporting this issue :)

**Comment by rustyjm** [comment]
Sorry, just one more question if that's ok - would there be scope for increasing that byte limit to hold more characters or is it a hard limit?

**Comment by niksedk** [comment]
It's a hard limit in the spec

**Comment by rustyjm** [comment]
Great, thanks for confirming.
