### ISSUE TITLE
Visual Sync not working with mpv IN LATEST BETA

### ISSUE THREAD

**Issue by Ouroboros1995** [SubtitleEdit/subtitleedit#4009]
Again with this latest beta, program just freeze whenever I try to use visual sync using mpv player.

Thank you for your time.

**Comment by niksedk** [comment]
Is this any better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip ?

When does it freeze - when entering "Visual sync" or when closing "Visual sync"?

**Comment by Ouroboros1995** [comment]
When closing. I will try now this newer version.

**Comment by Ouroboros1995** [comment]
It seems that now it is okay.
