### ISSUE TITLE
Auto-translate (google translate) not work

### ISSUE THREAD

**Issue by rujakgosong** [SubtitleEdit/subtitleedit#401]
my system
Windows 7 64 bit SP1.
I am using SSH tunnel internet connection.
![untitled](https://cloud.githubusercontent.com/assets/9784739/5657997/1d5ff296-972c-11e4-91f4-3e67f8e4e7ae.jpg)

**Comment by niksedk** [comment]
Have you tried the options -> settings -> proxy ?

**Comment by rujakgosong** [comment]
no, i am using proxyfier

**Comment by duiveldoder** [comment]
Had this problem as well and finally found out why:

after several files not working and had this problem, i thought: let's take the time and go through it line by line see where it hangs:

Anything on the shelves,<br />20% off.

Removing the % fixes it..

I tried this on other files that weren't translating as well..

Always the % causing this..

**Comment by OmrSi** [comment]
@niksedk You think this is done?

**Comment by rujakgosong** [comment]
Yes, this fixed.

Pada tanggal Jum, 17 Apr 2020 19.06, Omar Si <notifications@github.com>
menulis:

**Comment by OmrSi** [comment]
@niksedk Closed.

**Comment by OmrSi** [comment]
@niksedk Fixed.
