### ISSUE TITLE
[Bug] Max value in "Auto balance selected lines" always defaults to 41

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#4011]
I know I've mentioned this before, just thought I'd open a separate issue for it so I don't forget.
This value in "Auto balance selected lines" is not saved or taken from the profile, it **always defaults to 41**:
![image](https://user-images.githubusercontent.com/20923700/74974857-a9aae700-542e-11ea-869a-1dc9cd1d55a9.png)

**Comment by niksedk** [comment]
It's related to "Unbreak subtitles shorter than"
![image](https://user-images.githubusercontent.com/1261331/76015744-ee00b180-5f1b-11ea-8f68-dc56d0ef0469.png)

**Comment by OmrSi** [comment]
@niksedk I have that set at 42, yet this always goes back to 41.

**Comment by niksedk** [comment]
it's "-1"

**Comment by OmrSi** [comment]
Hmm.
Okay, thanks.

**Comment by OmrSi** [comment]
But why?
If it is allowed for my line to have 42 chars, why would it be 41?

**Comment by OmrSi** [comment]
@niksedk  Hmm. Okay, thanks.
But why?
If it is allowed for my line to have 42 chars, why would it be 41?
That way, lines with 42 would be broken.

**Comment by OmrSi** [comment]
Thanks, I got lost a bit at the "shorter than". ^^"
