### ISSUE TITLE
Subtitle format and plugins

### ISSUE THREAD

**Issue by AlexandreMT** [SubtitleEdit/subtitleedit#4019]
When I'm working with .sub format and run some plugin (e.g. lines unbreaker or tight hyphen), the subtitle format is switched to .srt. I believe this is not happening only with .sub format.

**Comment by niksedk** [comment]
OK, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.13/SubtitleEditBeta.zip

Note that you now can set "Dialog style" in Options ->Settings...
