### ISSUE TITLE
Fix overlap, but in the other direction

### ISSUE THREAD

**Issue by quickreactor** [SubtitleEdit/subtitleedit#4024]
I have an srt file from youtube that has overlapping captions, no problem, just "Fix overlapping display times", right?

Except that it has fixed them in the wrong direction and now every individual sub is starting at the point where the NEXT sub should be started. I need the overlap to be be brought BACK from the end. rather than extended forward.

I can't seem to find an option for which direction to trim the overlap. Is this possible?

**Comment by OmrSi** [comment]
I maen, can't you just do an offset?

**Comment by quickreactor** [comment]
> I maen, can't you just do an offset? (I might not be getting the picture)

Yeah you're not, each subtitle is offset by the length of the next sub, so an offset won't help.

If there was a way to shunt them all back by one, that would work?

**Comment by OmrSi** [comment]
I'm just a normal user but I try to help, can you maybe post the video link?

**Comment by quickreactor** [comment]
Thanks, but I can't post it, it's something I'm doing for work. I think I'll just continue on with the overlapping subs for now and hope that someone knows the solution. Appreciate your response though!

**Comment by OmrSi** [comment]
Okay.
You can do a "column shift up" or "column shift down" from the context menu if that helps.
You can also select a number of lines and shift them up or down via a shortcut.
If not, the developer might be able to help

**Comment by quickreactor** [comment]
Thanks! I'll give that a try, sounds promising! Cheers, mate

**Comment by uckthis** [comment]
Post fresh srt from youtube. I'll have a look.

**Comment by quickreactor** [comment]
Here ya go https://www.dropbox.com/s/zs7smtdvaw8obfj/captions.srt?dl=0

**Comment by uckthis** [comment]
@quickreactor Apply Minimum gap b/w subtitles. It's under TOOLS. Set value 1 ms.
 If you're using an old version, it used to be called Minium Display time between subtitles.

**Comment by quickreactor** [comment]
> @quickreactor Apply Minimum gap b/w subtitles. It's under TOOLS. Set value 1 ms.
> If you're using an old version, it used to be called Minium Display time between subtitles.

You are my saviour! That totally worked! Thanks so much for your help!
