### ISSUE TITLE
Line missing from hearing impaired detection

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#4025]
This one doesn't get caught in the hearing impaired detection to remove text before a colon.
```

955
01:13:19,896 --> 01:13:25,484
<i>-Stay, little Valentine</i>
-WOMAN: <i>Stay, little Valentine</i>
```

**Comment by niksedk** [comment]
Sorry, missing end-of-line-char...

**Comment by Boulder08** [comment]
You'll probably need to check the same thing for fixing common errors as the missing space (between the dash and the S) is not caught on the first line.
