### ISSUE TITLE
[Feature request] Split doesn't change end time

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#4026]
Right now, when you split a line, it adds the gap to the end time.
Can we have an option to keep the end time fixed when splitting?
Most times, you already set the end time to audio, so you don't want it to change when you split.
I remember someone already mentioned this here before.

**Comment by niksedk** [comment]
OK, now gap time will be subtracted from the two new paragraphs duration (half each).
Does that work for you?

**Comment by OmrSi** [comment]
It's usually subtracted from the second one.
As you are splitting at the place you want the first line to end with, so you're already ending the first line where you want it to end.
By "usually " I mean on Netflix's subtitling platform.

**Comment by niksedk** [comment]
OK, if user supplies split time, then gap will be subtracted from second sub - if no split time from user, then gap is taken from both subs evenly... sounds/works okay?

**Comment by OmrSi** [comment]
Sounds good to me, and it's working well.
Thank you, as always.
