### ISSUE TITLE
Problem with binary image compare

### ISSUE THREAD

**Issue by xplayman** [SubtitleEdit/subtitleedit#4028]
Edit: It's version 3.5.14 on windows 10 pro v1903

When I try to use binary image compare I get this glitch.
I tried 3.5.13 yesterday and 3.5.14 today same problem on them both.
![Untitled2](https://user-images.githubusercontent.com/5961606/76170893-3a4b2c00-617e-11ea-969f-87ba77c66f07.jpg)

![Untitled](https://user-images.githubusercontent.com/5961606/76170838-a5e0c980-617d-11ea-975d-b04c031c79cd.jpg)

And also both tesseracts are really slow compared to older version (can't remember the version atm)

EDIT2: Image files
[TXTImages.zip](https://github.com/SubtitleEdit/subtitleedit/files/4304023/TXTImages.zip)

**Comment by xplayman** [comment]
When I have auto transparent background the window appears to be normal, but is no use since the program cant understand the image.
![Untitled3](https://user-images.githubusercontent.com/5961606/76171109-babe5c80-617f-11ea-9eec-d79cdd51396e.png)

**Comment by niksedk** [comment]
Could you attach or email the sub? (e.g. as a .zip file)

**Comment by xplayman** [comment]
I have attached them to the first post.

**Comment by niksedk** [comment]
OCR in SE works best with white text color. 
If you right-click in the list-view you can choose "Image pre-processing...":

![image](https://user-images.githubusercontent.com/1261331/76187345-634adb80-61d5-11ea-935b-7cc0a083f9f6.png)

But still, I think the quality is too low?

![image](https://user-images.githubusercontent.com/1261331/76187510-d2283480-61d5-11ea-9e3b-747ac9b0b187.png)

**Comment by xplayman** [comment]
Yes I agree, the quality is to low, but those are the only subtitles I've found.
Butt still if they are low quality, why does the window brake?
![Untitled4](https://user-images.githubusercontent.com/5961606/76229931-ddea1a00-621a-11ea-8586-346092a3fbf6.jpg)
I was able to run trough the images with tesseracts but the binary brakes the manual image window.

**Comment by niksedk** [comment]
OCR in SE works best with white text color... perhaps only with white text color.

**Comment by xplayman** [comment]
ok, but that doesn't explain why the window brakes like in that picture.

**Comment by niksedk** [comment]
It's because SE thinks that the whole picture is just one letter...
