### ISSUE TITLE
long term user - feedbacks

### ISSUE THREAD

**Issue by wellloaded** [SubtitleEdit/subtitleedit#4030]
First of all, thank you so much for the software I have been using it for literally years and converted hundreds of subtitles.

I have a couple of feedbacks on the current state of the project which might or might not translate in improvements/feature requests. See list here below:

- Foreign videos even with English  subtitles will still retain original names, this can be a real pain for Scandinavian, Portuguese and similar languages where you find unusual characters for an Anglo-Saxon user. Is there any way to improve the detection of **âãäåæçêëîïñôõöûüĈĉ**? Just to mention a few

- I relay on Windows "Character Map" to pick up "strange" characters as per above, but it's not nice/practical if you ask me. So could we have this build in SubtitleEdit? e.g. little icon in the GUI corner where you could copy the wanted character from?

- Could SubtitleEdit on this very topic provide option of potential matches rather than just go for one? If the user corrects the matching this could be applied at least within the same file automatically

- Say one name appears on top of the guess list example:
**Tiäo** is converted into **Tido**, I'm ok correcting the very first occurrence as per Unknown Words list, but could this manual correction be automatically propagated to all the further cases within the same file? If the mistake is made on the name of the main character of a movie chances are that it's quicker to save the file as it if and use standard CTRL+F/CTRL+R to replace all the occurrences. So a build in feature to achieve this would be greatly appreciated

- I appreciate there' very little difference between "**I**" "**[**" and "**1**" but I'm wondering is any improvement could be made (e.g. looking also at the semantic of the sentence) as this is the most common mistake SubtitleEdit falls into. I can safely state that you will never find a **[** or **]** alone in the same sentence so if SubtitleEdit thinks so it's likely to be an easy to spot at code level mistake

- Considering we're in 2020, is there any better source of information to correct the guessed text? Like AI or so? I can see subsync utilities relying on publicly available AI libraries, wondering if this could be a good idea for SubtitleEdit 4.x

- Would you consider allowing the program upgrade directly from the program itself (like notepad++ or Handbrake do just to give an example) rather than redirecting to the download page? Just to save click time

Many thanks!

**Comment by niksedk** [comment]
I'm glad you find SE useful :)

I don't understand what you're doing... are you using OCR or ?
Some screenshots could help. Also some sample subtitles with the problems you talk about.
