### ISSUE TITLE
Issues with subtitle extraction from MKV in 3.5.14

### ISSUE THREAD

**Issue by ryvec** [SubtitleEdit/subtitleedit#4037]
Hi! There seems to be an issue with SubtitleEdit 3.5.14
 - when opening MKV files with embedded subtitles, they don't get extracted. Rolling back to 3.5.13 fixes this issue. Attached is the video with demonstration

[NoSubs.zip](https://github.com/SubtitleEdit/subtitleedit/files/4316199/NoSubs.zip)

**Comment by Symos404** [comment]
Seems simular to what happens with me, except I try converting vob embedded in a MKV via OCR. Once OCR is done, no subs are on the main screen. Again rolling back to 3.5.13 does resolve this.

**Comment by OmrSi** [comment]
@uckthis  Same as here?
https://github.com/SubtitleEdit/subtitleedit/issues/4015#issuecomment-594562405

**Comment by niksedk** [comment]
Thx for the info - I can see from the video that drag-and-drop were used... it seems I only tested with File -> Open...

How is latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by ryvec** [comment]
T

> Thx for the info - I can see from the video that drag-and-drop were used... it seems I only tested with File -> Open...
> 
> How is latest beta?
> https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

Thanks! This seems to have fixed the issue
