### ISSUE TITLE
Error Message: The value of argument °value° (65617) is invalid for Enum type °Keys°. Parameter name value

### ISSUE THREAD

**Issue by MaOz63** [SubtitleEdit/subtitleedit#4042]
Hi. I got this Error Message:
The value of argument °value° (65617) is invalid for Enum type °Keys°.
Parameter name value.
![image](https://user-images.githubusercontent.com/60763777/76592140-5bc36380-6542-11ea-9c0c-980be2e39525.png)

**Comment by niksedk** [comment]
Could you attach your `Settings.xml` file?
Probably in `C:\Users\USERNAME\AppData\Roaming\Subtitle Edit`
(Windows key + R, and paste "%appdata%\Subtitle Edit")

**Comment by MaOz63** [comment]
Sure Nkolaj. Here it is.

**Comment by niksedk** [comment]
@MaOz63: You need to attach the settings file as a .zip file here or github... or email it to me.

**Comment by MaOz63** [comment]
Hi Nik. I am sending the file again. Please let me know if you received it.

 Settings.xml
<https://drive.google.com/file/d/1gs7RgtfTLM5DoWPwFqKWFcreNFCRswgk/view?usp=drive_web>

El dom., 15 de mar. de 2020 a la(s) 12:53, Mao Oz (mao2oz63@gmail.com)
escribió:
 Settings.xml
<https://drive.google.com/file/d/1gs7RgtfTLM5DoWPwFqKWFcreNFCRswgk/view?usp=drive_web>

> Sure Nkolaj. Here it is.
>
> El vie., 13 de mar. de 2020 a la(s) 17:23, Nikolaj Olsson (

**Comment by niksedk** [comment]
The shortcut is available in the "Video menu" - and all shortcuts in menu items must have `Alt` or `Ctrl` enabled.

**Comment by MaOz63** [comment]
The error still the same

[image: image.png]
and erase all the shortcut keys for video
[image: image.png]

**Comment by niksedk** [comment]
You have to make a new shortcut for toggle video control docked/un-docked

**Comment by MaOz63** [comment]
It worked. Thank Nik.
