### ISSUE TITLE
Roll-on subtitles

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4043]
Hello,
Many a TV shows that are captioned live have roll-on subtitles. SE does a good job of converting them into pop-on captions using Merger Lines with same text tool, but in some cases it doesn't work. I'm attaching a file. Anything that could be done to automate it?

[Kids In The Hall - S02E15 [digitaldistractions].txt](https://github.com/SubtitleEdit/subtitleedit/files/4329097/Kids.In.The.Hall.-.S02E15.digitaldistractions.txt)

**Comment by OmrSi** [comment]
Well, each lines contains different text and has a different time code from the one before it.
I don't think you can do anything to automate it, as the lines keep repeating with no obvious pattern, but that's just my opinion.
