### ISSUE TITLE
Stop merging lyrical lines by 2 singers.

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#4046]
This is valid.

```
- ♪ You better ♪
- ♪ Ooh ♪
```
then it goes all wrong.
Becomes via merge short lines.

`- ♪ You better ♪ - ♪ Ooh ♪`

becomes via fix lines beginning with dash.

`♪ You better ♪ - ♪ Ooh ♪`

When there is a musical symbol at the end of the line then do not merge ever, the same as `.` full stop.

**Comment by niksedk** [comment]
Could you supply a screenshot?

**Comment by Ding-adong** [comment]
Oh scrap this thread. The problem looks like it was solved in 3.5.14 as I was using an old version. Also auto balance no longer balance the two singers lines which is great.

**Comment by niksedk** [comment]
Cool :)
