### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by MintHawk** [SubtitleEdit/subtitleedit#4048]
Would it be possible to add some functionality that shows perfect duration in subtitles according to standards? Something like VisualSubSync where double-clicking at the right edge of the selected subtitle in the wavelength, brings the subtitle to the right duration automatically.
Many thanks for the great work so far.

**Comment by OmrSi** [comment]
The is a "recalculate duration of current subtitle" shortcut, it might be what you're looking for.

**Comment by MintHawk** [comment]
I do not understand what you are saying.
Does the program have that as a feature or not?

**Comment by OmrSi** [comment]
If you mean that the program gives the perfect duration based on Chars/secs, then yes.
You can allocate a shortcut for it from the settings, it's called "Re-calculate duration of current subtitle".

**Comment by MintHawk** [comment]
Thank you, I found it.
However, I think that the recalculation done lacks in comparison to VSS as it limits the time available for reading the subtitle. By the way, what standards are followed in calculating the times?

**Comment by OmrSi** [comment]
As far as I know, if you have the max chars/sec set to 20, it calculates the duration to meet that number.

**Comment by MintHawk** [comment]
But most subtitlists use the 40 characters per line norm.
Anyway, I'm just used to VSS and I thought that this issue could be addressed (if it is an issue).
You are doing great work. I love all the features. The only one I'm missing is this calculation which gives less reading time for the viewer.

**Comment by OmrSi** [comment]
I'm actually just a user. The developer, @niksedk is doing awesome work here.

Wait, what's with the 40 characters per line? That's the max chars per line, I'm talking about the max chars/sec which is the reading speed. It calculates the duration to fit the chars/sec you set, as far as I know.

**Comment by MintHawk** [comment]
Yeah, not every line is 40 chrs. However, having worked as a subtitlist for 10 years, I think the time available for reading a sub could be extended. Kudos for the excellent work.

**Comment by niksedk** [comment]
@MintHawk: As OmrSi said, **chrs** (characters - length) and **cps** (characters per second - speed) are not the same...

SE uses "Optimal char/sec" for re-calculating duration:

![image](https://user-images.githubusercontent.com/1261331/77001665-95d5a080-695a-11ea-8cbe-85e018f35907.png)

You can probably set the value to like 12.5 or something if you want a longer duration.

**Comment by MintHawk** [comment]
Many thanks for the great work you're doing, niksedk.
Also, thanks for the explanation. Btw, can I do this for the whole episode? Do I have to select all the lines and then do it, after I have assigned a shortcut key?

**Comment by Boulder08** [comment]
> 
> 
> Many thanks for the great work you're doing, niksedk.
> Also, thanks for the explanation. Btw, can I do this for the whole episode? Do I have to select all the lines and then do it, after I have assigned a shortcut key?

This is probably something that you apply via the Fix common errors functionality. There's a bunch of things related to subtitle length etc.

**Comment by niksedk** [comment]
You also use Tools - Adjust durations.... 
(if you right click on sselected lines in list view, you can also adjust durations via the context menu)

**Comment by OmrSi** [comment]
@niksedk Why does recalculate sometime set to 16.67 while my optimal is 20.00?
![image](https://user-images.githubusercontent.com/20923700/82057910-b0af6180-96cc-11ea-983f-155b1fe61c65.png)

I want to to be 20 because I have to put it before the shot change:
![image](https://user-images.githubusercontent.com/20923700/82057955-bdcc5080-96cc-11ea-8b8c-709c4fac2f16.png)
