### ISSUE TITLE
Help with Regex

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4049]
Hello,
I have got this file and in many places it has sentences like this...

_Help him, He is falling._

A capital letter after a comma. I want to know how I can find these with regex, ,\w doesn't help. I want to know code that only finds capital letters. Anything?

**Comment by niksedk** [comment]
You can use Find with this regex: `, \p{Lu}`

**Comment by uckthis** [comment]
Thanks, man, this is awesome. I should learn Regex in depth.

How about a non-cap character after a period?

**Comment by niksedk** [comment]
Lowercase letter after line ending could be: `[\.!?] \p{Ll}`

**Comment by uckthis** [comment]
Perfect. Thank you very much.
