### ISSUE TITLE
Issue with single character italics

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#4053]
Sometimes dashes or commas are being picked up as being italic even if the rest of the sentence is normal text. Maybe in these cases the italic tags should be removed.

```
127
00:12:24,244 --> 00:12:28,332
<i>- </i> Sir, I need to get in there.
- Get away from her! Get away!
```

**Comment by niksedk** [comment]
It would be easier to test/fix if you could provide sub samples.

**Comment by Boulder08** [comment]
I'll try to find a new one, that particular case was from a DVB capture which I no longer have. I'll post a link here if I come across one.

**Comment by Boulder08** [comment]
I found this from my archives. In fact, the issue is probably not because of false detection but when removing HI parts, the italic dash is left intact. In this sample, such thing happens at subtitle number 284.

If this is the case, probably the best way to handle it is like you've done now and fix it semiautomatically.

[xfiles.zip](https://github.com/SubtitleEdit/subtitleedit/files/4399373/xfiles.zip)

**Comment by Boulder08** [comment]
I have a similar case with this subtitle file. The "T" in subtitle 426 is marked as italic, but it's not like that in the resulting subtitle line.

![image](https://user-images.githubusercontent.com/11799308/94844477-f7f18100-0426-11eb-997e-c0d7b9668f14.png)

This is the original sup file:[tng_s02e09.zip](https://github.com/SubtitleEdit/subtitleedit/files/5313914/tng_s02e09.zip)
