### ISSUE TITLE
Batch convert sub naming problem

### ISSUE THREAD

**Issue by Rodark** [SubtitleEdit/subtitleedit#4054]
I havent been able to find a setting, is there a way to change the naming style of the subtitles while in **batch convert**? currently it adds the language at the file name example: 
regular OCR -> file name.srt
Batch OCR -> file name #3.eng.srt
Is this a current problem, or am i doing something wrong? Cause i just had to manually rename 167 files XD

**Comment by niksedk** [comment]
SE reads more than 300 formats... which one are you using?

**Comment by Rodark** [comment]
> 
> 
> SE reads more than 300 formats... which one are you using?

SU version:3.5.14
files that i edit: mkv 99% of the time
Always converting them to srt with UTF-8 with BOM, if thats helpful
The subtitles that i convert are in HDMV PGS format

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip ?

Right-click in the batch convert list view, and enable the "2-3 language code option":
![image](https://user-images.githubusercontent.com/1261331/78531834-79ed4e00-77e6-11ea-9de8-1a5fb4213bec.png)

**Comment by Rodark** [comment]
> 
> 
> How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip ?
> 
> Right-click in the batch convert list view, and enable the "language-code-convert-option":
> ![image](https://user-images.githubusercontent.com/1261331/78531834-79ed4e00-77e6-11ea-9de8-1a5fb4213bec.png)

this is indeed helpful, removing the # as it can help when a file has many subs, but most of the times the problem is that it INCLUDES the sub language. would it be possible to also add a setting that names the sub with the same name as the video file?
basically remove the eng part from the sub. so the sub file is VideoName.srt as it it in the normal conversion mode

**Comment by niksedk** [comment]
Ah, I just needed the "two letter conversion" ;)

Added more options here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

How does this work?

![image](https://user-images.githubusercontent.com/1261331/78561438-06643480-7818-11ea-86aa-3bf2afe55ad1.png)


![image](https://user-images.githubusercontent.com/1261331/78561414-f51b2800-7817-11ea-906f-fcdc30c30dd2.png)

**Comment by Rodark** [comment]
perfect mate! no language code is exactly what i needed! thank you very much!
