### ISSUE TITLE
[Bug] Duplicating a line in translator mode

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#4057]
When duplicating a line in translator mode, the original text takes the text of the duplicated normal line text.
![image](https://user-images.githubusercontent.com/20923700/77235617-2d87f880-6bc0-11ea-9f49-04e30fcd29db.png)

**Comment by OmrSi** [comment]
Working well now. Thanks. :D

**Comment by niksedk** [comment]
And thx for verifying :)
