### ISSUE TITLE
Error when select translate (by Microsoft)

### ISSUE THREAD

**Issue by satpowers** [SubtitleEdit/subtitleedit#4058]
When select context menu 
Translate selected line -> translate (powered by Microsoft)
get Error
Error Message:
Invalid URI: The URI is empty
![image](https://user-images.githubusercontent.com/24232769/77250533-50162200-6c51-11ea-812a-59ec5ead28a5.png)

**Comment by niksedk** [comment]
thx for the info :)
That menu item should only be visible when you have entered a "key" + "endpoint" in Options -> Settings -> Tools -> Microsoft translate...
