### ISSUE TITLE
[Feature request] Add (or copy) support for maximum single line length based on pixels (safe area)

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#4059]
In theory, the maximum line length of subtitles is defined as maximum characters per line. However, because not all letters have the same width, lines with the same number of characters can have varying widths.

Spot, the software most professional Dutch subtitlers use, therefore detects "too long lines" not based on the amount of characters, but based on exceeding the safe area.

Take for example this subtitle in SE, which is marked too long because it exceeds 42 CPL:
![image](https://user-images.githubusercontent.com/3516155/77255510-71363d00-6c68-11ea-82a5-7511d992f46e.png)

However, as Spot shows, it does fit in the safe area, because the second line contains a lot of narrow characters:
![image](https://user-images.githubusercontent.com/3516155/77255534-96c34680-6c68-11ea-853e-d100a8e38d1d.png)

Fortunately, SE offers the "Check line width" plugin, which I use extensively to check my subtitles' "actual" width. I did some comparing and I found that these settings are a close enough match to Spot's safe area:
![image](https://user-images.githubusercontent.com/3516155/77255624-1d782380-6c69-11ea-8740-7d36b511570c.png)
(I chose Arial 16, which is Spot's editor font, but it's changed to 15,75 for some reason.)

My request is to copy this functionality to SE itself, because it's quite a hassle to open the plug-in everytime, scroll to the line I want to check, make changes etc.

My idea would be to just add a label next to the CPL counter, and populating it with the values as seen in the plug-in. For example:

![image](https://user-images.githubusercontent.com/3516155/77255697-b0b15900-6c69-11ea-99a4-c72963bc2831.png)
_(Exceeds CPL, but fits within safe area)_

![image](https://user-images.githubusercontent.com/3516155/77255742-fbcb6c00-6c69-11ea-84b8-d0ec816caf43.png)
_(Does not exceed CPL, but exceeds safe area)_

The pixel limit and used font would be added to the settings.
The text in the ListView will be highlighted red when it exceeds either the CPL or pixel value.
The "Auto br" could change into "Auto br using pixel width" (as in the plug-in) on Shift+Click/Alt+Click or depending on what error.

I looked into adding this feature myself, but the Main.cs form has a lot going on. It's also quite a change to the "basics' UI", so maybe it's best to run it by you first.

Thanks! :)

**Comment by OmrSi** [comment]
There is a plugin called "Check line width". It might have something to do with this.

**Comment by OmrSi** [comment]
@Flitskikker Closed now?

**Comment by Flitskikker** [comment]
@OmrSi Yes!

**Comment by xylographe** [comment]
Implemented in commit 6384a609f1a1f140c061406d1c0f7e1319501340.
