### ISSUE TITLE
Options / Settings

### ISSUE THREAD

**Issue by chocobobill** [SubtitleEdit/subtitleedit#4061]
Hello,

I get the following error when I select Settings from the Option menu.

![SettingsCrash](https://user-images.githubusercontent.com/62725526/77701148-393a3d00-6f7b-11ea-9764-f85a0c663c48.png)

**Comment by niksedk** [comment]
@chocobobill: I've fixed the crash... but I do think you need to re-install SE.
Either use the installer or unpack to portable version to something like "C:\Tools\SE" where SE has full write access.

**Comment by chocobobill** [comment]
Thank you. I have re-installed to several different paths (including creating a Tools folder for it under C:) but continue having the problem each time.

**Comment by niksedk** [comment]
@chocobobill: Could you attach a screenshot of your folder content + structure?
Does SE have write access to the folders?
Are you using the installer or the portable version?
As much info as possible :)

**Comment by chocobobill** [comment]
I used the installer from SubtitleEdit-3.5.14-Setup.zip

I think SE has write access to the folder, included in screenshot below.

![Folder and Permissions](https://user-images.githubusercontent.com/62725526/77785342-a86a6c80-7021-11ea-8cda-aa2701fb1c4c.png)

**Comment by niksedk** [comment]
If you're using the installer the check your profiles folder:
(click windows key + r... and enter "%appdata%\Subtitle Edit")
![image](https://user-images.githubusercontent.com/1261331/77818013-6ef03a80-70cf-11ea-8a90-74e9e587522a.png)
Check this folder for read/write access!

But to make things as simple as possible, perhaps you should use the "portable version" where all files are in the same folder. Uninstall your current version - and download and unpack the portable version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SE3514.zip

**Comment by chocobobill** [comment]
Everything is good. Thank you very much; I appreciate it!
