### ISSUE TITLE
Auto capitalize after punctuation

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#4062]
So I have been trying to figure this one out. It seems like SubtitleEdit has a hardcoded rule that if a lower case letter has ". " before it, then it is automatically changed to an uppercase letter.

This causes some problems, since when the subtitle starts with "... " - it usually should have a lower case letter.
I've also seen examples of uppercase after common Danish abbreviations like "pga.", "ph.d.", "kl." and so forth.

Is there a way to turn auto uppercase off?

![Udklip](https://user-images.githubusercontent.com/5127386/77828349-252d4180-711b-11ea-9053-59f6abff4aa9.PNG)
![Image807](https://user-images.githubusercontent.com/5127386/77828355-2eb6a980-711b-11ea-9ff8-137774aaf280.png)
[Beverly Hills Cop II (1987)_Subtitles03.DAN.zip](https://github.com/SubtitleEdit/subtitleedit/files/4397453/Beverly.Hills.Cop.II.1987._Subtitles03.DAN.zip)

**Comment by niksedk** [comment]
In this case, the uppercase "S" is from Tesseract, so I can't really do anything, sorry.
You can try the OCR method "Image compare"...

**Comment by Maitch** [comment]
I see. Thanks for the reply.
