### ISSUE TITLE
Feature Request:  please add support to convert  video to  .srt  via OCR

### ISSUE THREAD

**Issue by solidmaple** [SubtitleEdit/subtitleedit#4063]
Feature Request:  please add support to convert  video to  .srt  via OCR

currently  subtitleedit supports  OCR from   .idx/.vob and .sup but not from video file itself

can subtitleedit  able to use OCR from a video file?

such as this sample example file

https://x0.at/dwp.mp4

**Comment by tonsofpcs** [comment]
It seems that converting such a video file to an image sequence and OCRing the image sequence works at present except that the resultant subtitles all start at 0 and have the same duration (except the last one) and there doesn't appear to be an obvious way to simply set them all to a single frame duration and 'bump' the next ones down.  I agree that being able to OCR a video (or, ideally also, a window on a video) into subtitles would be quite useful.

**Comment by uckthis** [comment]
Use VideoSubFinder

**Comment by OmrSi** [comment]
@niksedk Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/1328?
