### ISSUE TITLE
Add missing quote issue with commas

### ISSUE THREAD

**Issue by Rouzax** [SubtitleEdit/subtitleedit#4070]
Running on the latest SubtitleEdit beta release.
When running Common Errors: `Add missing quotes (")` it will also add them to sentences that end with a comma. That should not be the case since the quote will be closed at the end of the sentence.
![image](https://user-images.githubusercontent.com/4103090/77911942-fa192e00-7291-11ea-949b-6e5be62b699e.png)

Here is the original section
```
358
00:23:17,458 --> 00:23:20,041
"Dear Juilliard School of Music,

359
00:23:21,083 --> 00:23:26,500
I was baffled by your restraining order
of October the 13th.

360
00:23:26,583 --> 00:23:27,875
What did I do?"
```

This is how it is fixed now
```
358
00:23:17,458 --> 00:23:20,041
"Dear Juilliard School of Music,"

359
00:23:21,083 --> 00:23:26,500
I was baffled by your restraining order
of October the 13th.

360
00:23:26,583 --> 00:23:27,875
"What did I do?"
```

This is how it should be fixed
```
358
00:23:17,458 --> 00:23:20,041
"Dear Juilliard School of Music,

359
00:23:21,083 --> 00:23:26,500
I was baffled by your restraining order
of October the 13th."

360
00:23:26,583 --> 00:23:27,875
"What did I do?"
```

**Comment by niksedk** [comment]
I think that SE should actually not touch anything here... ?

**Comment by Rouzax** [comment]
Either not touch or the one I proposed.
If you are looking for ends of sentences in the `Add missing quotes (")` the last one makes the most sense.

**Comment by niksedk** [comment]
I've looked a bit on existing subtitles and found quotes spanning up to four lines - so I'll try to make SE not touch those lines (if time gap is small between all lines).
