### ISSUE TITLE
Adjustment to Fix first letter to uppercase after paragraph

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#4073]
These kinds of lines trigger the fix incorrectly. Probably two or more dots will do the same there.

```
177
00:07:45,793 --> 00:07:47,327
That's what
I needed it for--

178
00:07:47,378 --> 00:07:49,930
to process this bomb
that you dropped on me.
```

**Comment by niksedk** [comment]
Hm, I disagree with this one... I think two hyphens indicate abrupt interruptions - and a line ending.

**Comment by borifax** [comment]
These two characters often appear in subtitles. I always have to replace them with an ellipsis (...).

**Comment by OmrSi** [comment]
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/360
