### ISSUE TITLE
Shortcut for increasing/decreasing subtitle duration frame by frame

### ISSUE THREAD

**Issue by matmaggi** [SubtitleEdit/subtitleedit#4078]
Hello, I'm wondering if it's possible to do the following shortcuts for subtitles with less than 100/150ms gaps:

1. Increase/decrease a subtitle frame by frame at the start of subtitle, but dragging the previous together maintaining gap. (If the gap beetween subtitles is bigger than 100/150ms, only selected subtitle is affected)
2. Increase/decrease a subtitle frame by frame at the end of subtitle, but dragging the following together maintaining gap. (If the gap beetween subtitles is bigger than 100/150ms, only selected subtitle is affected)

**Original subtitle:**
![image](https://user-images.githubusercontent.com/48259053/78136021-4632b280-73f9-11ea-92d4-e42e5425cdb0.png)

**For the first shortcut:**

Increasing one frame forward in subtitle 2 and decreasing one frame in subtitle 3.
![image](https://user-images.githubusercontent.com/48259053/78136461-015b4b80-73fa-11ea-9575-0c8fc814050a.png)

Or the opposite. Decreasing one frame in subtitle 2 and increasing one frame in subtitle 3.
![image](https://user-images.githubusercontent.com/48259053/78136826-a2e29d00-73fa-11ea-88ea-3ba71f8b8ff1.png)

**For the second shortcut:**

Increasing one frame backward in subtitle 2 and decreasing one frame in subtitle 1.
![image](https://user-images.githubusercontent.com/48259053/78137021-f5bc5480-73fa-11ea-9b32-fbedff84cd21.png)

Or the opposite. Decreasing one frame in subtitle 2 and increasing one frame in subtitle 1.
![image](https://user-images.githubusercontent.com/48259053/78137092-11bff600-73fb-11ea-8761-d363e42ca72f.png)

I don't know if I was clear, but I think this would help lots of people. Thank you.

**Comment by Fhining** [comment]
I totally agree. The possibility to adjust just one frame with the shortcuts options it would be a incredible feature, now that Subtitle Edit is working better with shotchanges (Scene Changes). 

Right now those "overwrite" shortcuts for previous and next subtitle doesn't exist, but neither the option to move just one frame and that would be a great start!

**Comment by btsix** [comment]
I think it's an amazing idea for those who works with frames.
This would be a nice tool, to be able to move frames with shortcut as the same to move ms.
Nice idea @matmaggi !

**Comment by niksedk** [comment]
Beta updated with shortcuts for move start/end by 1 frame: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

Is keeping the gap to prev/next important? If yes, that should be other shortcuts, right?

**Comment by Fhining** [comment]
> Beta updated with shortcuts for move start/end by 1 frame: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip
> 
> Is keeping the gap to prev/next important? If yes, that should be other shortcuts, right?

@niksedk 

Nikolaj! Thank you soooo much for this amazing update. This is exactly what matmaggi was saying (I think) and what I asked too. This feature + the new update with "snapping shot scene changes (shot changes)" is a powerfull combination.

About your question. I tested some other software with this shortcuts and what they do is keeping this combination "locking" the gap. And they create other shortcuts for "overriding" the previous or next subtitle (still keeping the gap). Don't know if I'm explaining myself.

That shortcut will allow you to move one frame  of the end of a subttitle and "eat" 1 frame of the next one. This way you don't have to go to the next one, substract one frame from the start, go back to your sub and add the last frame at the end.

So I think it should be 4 shortcuts like these ones but with this "override" function.

Again, THANK you so much for your tremendous work. :)

**Comment by matmaggi** [comment]
Thanks @niksedk! This is awesome!
My point of view is the same as @Fhining. If could adjust that, I'd appreciate!

**Comment by OmrSi** [comment]
@niksedk I think the idea of the second set of 4 shortcuts would be a match for this: https://github.com/SubtitleEdit/subtitleedit/issues/3027

**Comment by niksedk** [comment]
@OmrSi: yes, seems to be the same :)

New beta with four new shotcuts:
![image](https://user-images.githubusercontent.com/1261331/81074263-0f185b00-8ee9-11ea-8a98-4dbfae1aa7e9.png)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

Let me know how it works!

**Comment by matmaggi** [comment]
@niksedk I've tested now and it's working fine, which is awesome. Thank you so much!

I've found a bug. Duration of the subtitle not selected doesn't change in list view when I use the shortcuts. Just in the bottom.
![image](https://user-images.githubusercontent.com/48259053/81075659-06139380-8ec1-11ea-92de-f0b472f53183.png)

**Comment by niksedk** [comment]
@matmaggi: thx for testing :)
Hopefully fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

**Comment by matmaggi** [comment]
@niksedk  It's working fine now. Thank you! Have a great day.

**Comment by Fhining** [comment]
Thank you so much for this amazing update. Tested this last version and the shortcuts are exactly what I was saying. Such a great combo with "snap to scenechange feature".

Once again, thanks a lot @niksedk

**Comment by Fhining** [comment]
@niksedk I was thinking that maybe, regarding this same "frame topic" is it possible to set "gap" in frame as well? Because if people want to have an exact frame separation, they need to calculate them to get a near MS number.

![image](https://user-images.githubusercontent.com/64643541/81095819-d175fb00-8f05-11ea-9b51-f9a28dfdc3da.png)

**Comment by matmaggi** [comment]
Great idea, @Fhining. Maybe it shold be linked with time code mode. When working with frames, use gap between subtitles in frames. When working in miliseconds, use gap between subtitles in miliseconds.
