### ISSUE TITLE
Cannot open video file

### ISSUE THREAD

**Issue by AlexandreMT** [SubtitleEdit/subtitleedit#4081]
SE is crashing when I try to open any video. The version I am using is the latest beta.

![image](https://user-images.githubusercontent.com/25598649/78291222-65b20400-74fb-11ea-9f08-08650e5de329.png)

Sometimes I see this message too:
![image](https://user-images.githubusercontent.com/25598649/78291318-9134ee80-74fb-11ea-904a-672333ab71e4.png)

**Comment by niksedk** [comment]
Use mpv...

**Comment by AlexandreMT** [comment]
> Use mpv...

I did that before opening this issue, and also tried other ways, but I am still seeing the second error message.

**Comment by niksedk** [comment]
Some people does not find the "Error playing video file" window helpful... probably too much text. 
Perhaps if it was possible to switch to "mpv" directly from this window if would help people more?

The beta from yesterday has some issues... do you still have "the second error" with this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip
Also, can you provide steps to re-create "the second error"?

**Comment by AlexandreMT** [comment]
Okay, now I'm using the latest beta and things are working well. Video is now playing even without mpv. I like DirectShow because I can play the video with two different subtitles, like this:
![image](https://user-images.githubusercontent.com/25598649/78346104-f0831500-7574-11ea-8a86-ca17999e3048.png)

Anyway, thanks for you time :)
