### ISSUE TITLE
"Merge lines with same text" does not merge all lines

### ISSUE THREAD

**Issue by sneaker2** [SubtitleEdit/subtitleedit#4083]
Hi,

I have a sample (ASS) where SubtitleEdit does not merge all lines with the same text.

[SE_merge_same_text_problem.zip](https://github.com/SubtitleEdit/subtitleedit/files/4430880/SE_merge_same_text_problem.zip)
![SE_merge_same_text_problem](https://user-images.githubusercontent.com/8726180/78420888-a755c280-7653-11ea-832d-d65b3a14f3d3.png)

**Comment by niksedk** [comment]
Thx for the info :)
I've tried to make it handle merge in non-sequential lines too here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

Does that work for you?

**Comment by OmrSi** [comment]
@niksedk Works fine when testing on his test file.
