### ISSUE TITLE
I want to move the position of the waveform

### ISSUE THREAD

**Issue by OhaengCha** [SubtitleEdit/subtitleedit#4084]
In Mkvtoolnix, the audio of the B file is combined with the video of the A file with different sinks. The waveform is not aligned because the waveform is extracted from Subtitle Edit. The sync of video and audio is normal, and only the position of the waveform is shifted. Can't only the waveform move back and forth?

**Comment by niksedk** [comment]
Sorry, I don't understand what you mean...

**Comment by niksedk** [comment]
In Options -> Settings -> Waveform - you can switch to waveform extraction to "FFmpeg" which might do a better job...

**Comment by OhaengCha** [comment]
In the meantime, FFmpeg has been used for waveform extraction. I used VLC for this, but it was the same. Sometimes the waveforms are misaligned when the video and audio of different sinks are combined into one. I want to adjust only the sync of the waveforms loaded in Subtitle Edit, but there is no way. As it was a wav file, I was wondering if I could only adjust the start time.
