### ISSUE TITLE
Support pasting files from clipboard

### ISSUE THREAD

**Issue by 5j9** [SubtitleEdit/subtitleedit#4087]
Subtitle Edit already supports drag and drop for opening subtitle files. As a keyboard fan I'd like to suggest allowing pasting files directly, too.

(I don't know many programs that support this feature, one that comes to my mind at the moment is [PotPlayer](https://potplayer.daum.net/). [VLC ](https://www.videolan.org/) supports it too, but it shows a prompt instead of just opening the file and also does not support opening subtitles in this way, only the main video.)

I believe the related method in C# is [Clipboard.GetFileDropList](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.clipboard.getfiledroplist?view=netframework-4.8).

**Comment by niksedk** [comment]
Something like this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by 5j9** [comment]
Wow, that was super fast! Thanks so much!
