### ISSUE TITLE
[bug] Crash - The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by moob158** [SubtitleEdit/subtitleedit#4089]
The process cannot access the file because it is being used by another process

SE 3.5.14 build 152
When open an mkv file, **and the file is not used by another process**

**the SE 3.5.14 build 0 works fine**

The process cannot access the file because it is being used by another process
![Capturar](https://user-images.githubusercontent.com/60049180/78501658-672a3900-7754-11ea-8852-2c44a3119800.PNG)

**Comment by moob158** [comment]
@niksedk 

still crash

![Capturar](https://user-images.githubusercontent.com/60049180/78502666-1ddce800-775a-11ea-9167-a3c5f4c70fca.PNG)

**Comment by moob158** [comment]
![11](https://user-images.githubusercontent.com/60049180/78502974-b4f66f80-775b-11ea-87fb-e05c6cb72dc2.gif)

**Comment by moob158** [comment]
@niksedk 

the crash begin after the git-1e476f7549a065b07d892859a5f0b272536cc548

**Comment by moob158** [comment]
I've already detected the problem.
The problem is in MatroskaFile.cs file, git-2e839d1

**Comment by niksedk** [comment]
Just to be sure, does it still happen in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip ?

2e839d1a7aa4fa73e90a62326875f6b5c286b7d6 was made to optimize mkv reading - and it should fallback to the old way.

**Comment by moob158** [comment]
@niksedk 

the post above use last beta, and still crash, the problem is in MatroskaFile.cs, changes you made in 2e839d1

![Capturar](https://user-images.githubusercontent.com/60049180/78507735-ba62b280-7779-11ea-9256-08f343d36352.PNG)

**Comment by xylographe** [comment]
The exception in the previous comment occurs after the `FastFileStream` constructor has been invoked.
```
em Nikse.SubtitleEdit.Core.FastFileStream..ctor(String path)
```
This is not related to `MemoryMappedFile.CreateFromFile`,

**Comment by niksedk** [comment]
Hm, it might be because the MemoryMappedFile locks!?
And of course, I cannot re-create the error. Can you @xylographe ?

Anyway, SE now opens the MemoryMappedFile in "read-mode": https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip
Does that work better for you @moob158 ?

( The MemoryMappedFile could potentially help with #3893 )

**Comment by moob158** [comment]
@niksedk 

works fine with last beta, thank you ;)

**Comment by xylographe** [comment]
@niksedk No, I cannot reproduce the exception (running on Win7).
