### ISSUE TITLE
Issue with ANSI encoding detection since 3.5.14

### ISSUE THREAD

**Issue by Hurukan812** [SubtitleEdit/subtitleedit#4091]
Hi and thank you for this great software!
I work with French subtitles on Windows and previously ANSI files were detected as 1252 (Western Europe). However, since version 3.5.14, some files seem incorrectly detected as 28591 instead. The problem is that, unlike Windows-1252, ISO 8859-1 is missing some common French characters like "œ" and "Œ", that were implemented in ISO 8859-15. The result is that although those characters are present in the subtitle file and Windows notepad can display them, when opened in SubtitleEdit they are not recognized and are deleted.
A fix for this would be highly appreciated. Thanks!

**Comment by niksedk** [comment]
Could you attach a few sample files?

**Comment by Hurukan812** [comment]
Thanks! Here are 2 ANSI files that are detected differently for some reason. When the file detected as 28591 is opened in SubtitleEdit, the character "œ" present in the first line is deleted.
I've noticed that disabling the "Auto detect ANSI encoding" in the settings prevents this, as both files are then detected as 1252. To be honest I'm not sure what this setting does exactly, but it doesn't explain why a file including characters not present in 28591 would be detected as such.

[ANSI detected as 1252.zip](https://github.com/SubtitleEdit/subtitleedit/files/4439253/ANSI.detected.as.1252.zip)
[ANSI detected as 28591.zip](https://github.com/SubtitleEdit/subtitleedit/files/4439254/ANSI.detected.as.28591.zip)

**Comment by niksedk** [comment]
@Hurukan812: thx for the files :)
I've tried to improve the ANSI auto-detecting in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

And it's actually more like guessing - no program will ever guess ANSI encoding100% correct... that's why we have UTF-8 :)

**Comment by Hurukan812** [comment]
Thanks!
So I'm guessing that, while the auto detect tries to figure out a more specific encoding, disabling the "Auto detect" setting will always result in ANSI being detected as 1252?
Of course UTF-8 remains the best option, but it's good to know that using the original encoding of a file doesn't mean risking to lose some characters in the process. :)
