### ISSUE TITLE
Specify Language & Tesseract Version for convert via CLI

### ISSUE THREAD

**Issue by simonerni** [SubtitleEdit/subtitleedit#4096]
Hi all!

Is there a way to specity the language and tesseract version for converting via the command line?

I'd really like to be able to use Tesseract 4 via the CLI.

Thanks a lot!

**Comment by niksedk** [comment]
Hi @simonerni,

sorry, SE will just use last used language and Tesseract version ATM (I think).
Latest beta uses Tesseract 5 Alpha instead of Tesseract 4: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

Also, this is somewhat related to issue #3869

**Comment by simonerni** [comment]
Hi @niksedk,

I experimented with this and you're correct. I can modify the settings.xml before launch to achieve what I want - thanks a lot!
