### ISSUE TITLE
Visual Studio / Debugging: Wrong base-directory

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#4097]
If you have SE installer version is installed in your machine, when debugging in Visual Studio it will always point the the installed version (%appdata%\Roaming\Subtitle Edit) as the **base-directory** (note: even when the SE is run outside)

it also happen for the portable version of SE... (which makes the installed plugin in portable directory unusable)

ps: I think I already reported this issue before...

**Comment by niksedk** [comment]
Just copy the folders "Dictionaries", "OCR", and "Tesseract302" to your debug folder...

**Comment by ivandrofly** [comment]
> Just copy the folders "Dictionaries", "OCR", and "Tesseract302" to your debug folder...

Okay, but I think it's misleading... just want to access the plugin dir in debug... 🤔
