### ISSUE TITLE
Missing language selection in Import/OCR VobSub (Wine)

### ISSUE THREAD

**Issue by Signy13** [SubtitleEdit/subtitleedit#4105]
In Import/OCR VobSub I can not see any language in selector.
![SubtitleEdit_01](https://user-images.githubusercontent.com/18901924/78974755-f8156180-7b12-11ea-8649-69d28ad68b62.png)

When I click on a button with three dots I can see language files
C:\users\XXXXXXX\Application Data\Subtitle Edit\Tesseract302\tessdata
![SubtitleEdit_02](https://user-images.githubusercontent.com/18901924/78974757-f8adf800-7b12-11ea-9c03-0dccd9566b84.png)

Tested versions: 3.5.11, 3.5.14.
Wine: 4.x, 5.0, dotnet4.0, dotnet4.7.1, Xubuntu 18.04
It used to work a week ago but something happened and it is not working any more. 
* I tried to make clean fresh install inside virtual machine - it did not help. 
* I tried to make new wineprefix i386 only (32b), it did not help.
* I tried install dotnet4.0 - did not help. Upgraded dotnet to 4.7.1 - did not help

Do you have any idea what can be wrong?

**Comment by niksedk** [comment]
Sorry, don't have any ideas... 

Does running directly in Linux not work?
https://nikse.dk/SubtitleEdit/Help#linux

**Comment by Signy13** [comment]
Thank you very much for quick reply. 
Yes, I installed Linux version as well but there is another problem with Tesseract 4.X - it ignores green subtitles (this is probably for another bugreport) - on the left side is Mono version with native Tesseract 4.x, on the right side Wine version which can use Tesseract 3.x and this is the only option which can recognize subtitles in all colours
![SubtitleEdit_03](https://user-images.githubusercontent.com/18901924/78977057-be932500-7b17-11ea-8bd4-8397368c9083.png)

**Comment by Signy13** [comment]
I am still trying make SubtitleEdit working under wine. The last version SubtitleEdit (from yesterday) asks me to download Tesseract 5.00 Alpha 2020-03-28, which is not working under Wine. 
I downloaded the Tesseract and installed it, but SubtitleEdit can not see it. 
* How Subtitle edit recognizes, that Tesseract is installed?
* Is there any preferable directory, where Tesseract should be installed, or it does not matter?
* I do not know whether SubtitleEdit runs as 32b or 64b application. It is problem when Tesseract is 32b application?
* How SubtitleEdit recognizes which languages are available in Tesseract?

**Comment by niksedk** [comment]
SE detects Tesseract by looking for a path: `DataFolder`/Tesseract500.Alpha.20200328

`DataFolder` is calculated like this: SE first checks for an `installer installed version` in "`Roaming Profile`/Subtitle Edit" otherwise SE checks if the folder where SubtitleEdit.exe resides has a `Dictionaries` folder, if yes, then this folder is used as the `DataFolder`.

SE 64-bit is able to use tesseract 32-bit just fine - as it's not library call (just a cmd line).

SE (on windows) looks for tesseract languages in the `DataFolder`\Tesseract500.Alpha.20200328\tessdata folder

**Comment by Signy13** [comment]
Thanks for info, it works. Maybe "Download failed!" error 
![SubtitleEdit_04](https://user-images.githubusercontent.com/18901924/79039734-a2f55080-7be3-11ea-9885-dbab97e21d0b.png)
could be improved with text like:
* Download from https://some_server.de/... Tesseract-ocr_w...exe failed. Please install Tesseract 500 Alpha 2020-03-28 into folder:
D:\users\...\Tesseract500.Alpha.20200328"

in case other people have troubles with not working download.

I downloaded Tesseract 5, installed it (and downloaded traineddata within its installation program, that worked) and now SubtitleEdit can see Tesseract 5, but language selection is still empty although *.traineddata are in the correct folder.
Tesseract itself is working, command `wine tesseract.exe --list-langs` returns 5 language codes (according to it's tessdata folder) and this command is working too:
`wine tesseract.exe test.png test -l ces --oem 3 hocr`

Is there any way how I could test the way how SE searches the languages?

**Comment by Signy13** [comment]
BTW: other selectors work, for example dictionary selector is OK:
![SubtitleEdit_05](https://user-images.githubusercontent.com/18901924/79040489-236a8000-7be9-11ea-9103-3f15dc5aaec7.png)
Is there something special with the language selector for Tesseract?

**Comment by niksedk** [comment]
OK, added a version that will show msg boxes for the tesseract dir stuff: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBetaDebug.zip

**Comment by xylographe** [comment]
SubtitleEdit expects to find the `*.traineddata` files in the `tessdata` subfolder.
For example, (German, English, French and Dutch)
```
<DataFolder>\Tesseract500.Alpha.20200328\tessdata\deu.traineddata
<DataFolder>\Tesseract500.Alpha.20200328\tessdata\eng.traineddata
<DataFolder>\Tesseract500.Alpha.20200328\tessdata\fra.traineddata
<DataFolder>\Tesseract500.Alpha.20200328\tessdata\nld.traineddata
<DataFolder>\Tesseract500.Alpha.20200328\tessdata\osd.traineddata
```
The `osd.traineddata` file is needed by Tesseract for most languages.

To locate the SubtitleEdit Datafolder you can select **File > Plugins...** to open the Plugins dialogue, then select "Open 'Plugins' folder" (bottom left corner). The parent folder of the Plugins folder is the Datafolder.

**Comment by Signy13** [comment]
Thanks for the beta. I selected the Tesseract 5.00... and got:
* `Searching dir for tesseract languages: C:\Aplikace\SubtitleEdit_portable2\Tesseract500.Alpha.20200328\tessdata`
* `Checking file: C:\Aplikace\SubtitleEdit_portable2\Tesseract500.Alpha.20200328\tessdata\.traineddata`
* `Checking file: C:\Aplikace\SubtitleEdit_portable2\Tesseract500.Alpha.20200328\tessdata\.traineddata`
* `Checking file: C:\Aplikace\SubtitleEdit_portable2\Tesseract500.Alpha.20200328\tessdata\.traineddata`
* `Checking file: C:\Aplikace\SubtitleEdit_portable2\Tesseract500.Alpha.20200328\tessdata\.traineddata`

So the checking of file `.traineddata` was 4 times (I have trained data fof 4 different languages + osd), but there was missing the name of the file. Was it supposed to be checking file `eng.traineddata`?

**Comment by Signy13** [comment]
Thanks to xylographe, now I am sure where the `<DataFolder>` is and location of `*.traineddata` files seems to be correct.

**Comment by Signy13** [comment]
One another test - when I run the SE beta under Mono, I got something else:
`Searching dir for tesseract languages: /usr/share/tesseract-ocr/4.00/tessdata`
`Checking file: /usr/share/tesseract-ocr/4.00/tessdata/IVL.traineddata`
`Checking file: /usr/share/tesseract-ocr/4.00/tessdata/ara.traineddata`
`Checking file: /usr/share/tesseract-ocr/4.00/tessdata/bul.traineddata`
`... `
SE searches a lot of (20 or more) different `*.traineddata` files, although there are only four of them (3 languages + osd) in the folder.

**Comment by xylographe** [comment]
https://github.com/SubtitleEdit/subtitleedit/blob/089f71274f1cdcfa5a0bdd836862b47da0219459/src/Forms/Ocr/VobSubOcr.cs#L6583

It sort of looks like the `culture.ThreeLetterISOLanguageName` property is the empty string for each culture. Then the `trainDataFileName` (assiged to in the next line) will always end with `\tessdata\.traineddata`, which, obviously, won't exist .

Could this be a problem with Wine?

**Comment by Signy13** [comment]
Xylographe, you are right - the problem could be in Wine, but I have no clue where to find it. I tried to google it but did not find similar problem...

**Comment by niksedk** [comment]
Is this any different: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBetaDebug.zip
Uses `CultureInfo.GetCultures(CultureTypes.AllCultures)` instead of `CultureInfo.GetCultures(CultureTypes.NeutralCultures)`

Perhaps Wine is not setting some windows setting correct?
https://blog.coryfoy.com/2006/06/how-mono-gets-its-cultureinfo/
https://stackoverflow.com/questions/27551567/why-doesnt-mono-have-a-culture-info-when-running-through-upstart

**Comment by Signy13** [comment]
Thanks for new testing version.
Now it shows only:
`Searching dir for tesseract languages: C:\Aplikace\SubtitleEdit_portable2\Tesseract500.Alpha.20200328\tessdata`
and nothing else (no info about `.traineddata` files).
The language selector is still empty.

**Comment by xylographe** [comment]
@niksedk 
Perhaps, something like,
```
foreach (var ci in CultureInfo.GetCultures(CultureTypes.NeutralCultures))
{
    var culture = CultureInfo.GetCultureInfo(ci.LCID);
    var tesseractName = culture.ThreeLetterISOLanguageName;
    var trainDataFileName = Path.Combine(dir, tesseractName + ".traineddata");
    // etc.
```
Perhaps, the `GetCultureInfo(int)` method might set the `ThreeLetterISOLanguageName` correctly.

**Comment by Signy13** [comment]
I did some tests on PlayOnLinux, tried different versions of Wine (3, 4, 5) with original Wine Mono, Win32 Mono and .NET and found out that my problems probably began when I upgraded Mono (which made SE crashing) and consequently installed .NET in Wine. Once I installed original .NET, the language selector stopped working.

* Installing some Win32 version of Mono (I do not remember which) inside Wine results in faster application but then SE crashes from some other reason. This is obviously bad idea - Wine has it's own version of Mono which is supposed to work with Wine.
* Native version of Mono 4.6.2 in Linux works fast, but it has problems with diacritics (like č, ř...) - most of the time I can not write letters with diacritics, sometimes is possible to paste a piece of text with diacritics from clipboard.

So now it seems that the best way is using SE under PlayOnLinux with rather older version of Wine (I will do another tests) without upgrade.

**Comment by Signy13** [comment]
BTW: why actually is this `ThreeLetterISOLanguageName` necessary? Is it just to get a list of acronyms to recognize language of `*.tessdata` files? 
If it is like that, simple workaround for this problem would be just getting names of `*.traineddata` files in the folder and then:
* either recognize language (and use it in the language selector) 
* and in case returned language is empty, just use the name of the `*.traineddata` file instead.

It might be similar to the Dictionary selector, when some files are recognized and some are not - but user can still use it (like cs_CZ_old in this example):
![SubtitleEdit_06](https://user-images.githubusercontent.com/18901924/79061686-e65ac800-7c92-11ea-9b35-2879eb18ae08.png)
I tested that Tesseract basically uses names of `*.traineddata` files as `-l` argument - I created  `bflmpsvz.traineddata` and this command worked with Tesseract 302:
`wine tesseract.exe testfile.png testfile -l bflmpsvz hocr`

This approach might be faster as well - instead of testing existence of dozens `*.traineddata` files just recognizing probably smaller number of files on the disk.

**Comment by niksedk** [comment]
OK, listing languages from *.traineddata now added via this commit: 058109de6fc5c47a1e15752ec8031fd475005710
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

Looking up and listing cultures are used many places in SE...

**Comment by Signy13** [comment]
Thank you, language selector for Tesseract is working now. 
The fact, that listing cultures are used on many places in SE, can be problem with this workaround. 
Surprisingly in the previous version (where Language selector for Tesseract was empty) Dictionary selection works (I can change language without any trouble).
In this version when I select Dictionary, SE freezes (it stops responding):
![SubtitleEdit_08](https://user-images.githubusercontent.com/18901924/79064352-76efd300-7ca8-11ea-8c18-4ebf4b137067.png)
I tested some other places and language selectors worked on this places:
* Spell check - Language
* Add to name list - Language
* Settings - Word list - Language

**Comment by niksedk** [comment]
OK, what happens if you change dictionary language in this version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBetaDebug.zip

Note: You can press "Ctrl+c" to get the text from a messagebox.

**Comment by Signy13** [comment]
Thank you, that is an interesting version :-)
If I change Dictionary in OCR auto correction (OCR method is default - Binary image compare), SE says:
* `Getting culture from: cs_CZ`
* `Culture result: cs`

and it works.
Afterward I changed OCR method to Tesseract 3.02, SE said:
* `Getting culture from: cs_CZ`
* `Culture result: cs`
* `Getting culture from: cs_CZ`
* `Culture result: cs`
* ... many many many times...

It looks like an indefinite loop.

**Comment by niksedk** [comment]
OK, it seems like the property `ThreeLetterISOLanguageName` is blank...
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by Signy13** [comment]
First test:
1.  When SE is started, OCR method: Binary image compare (default), Dictionary: none.
2. I change Dictionary (OCR auto correction) - it works.
3.  I change OCR method to Tesseract 3.02 - it freezes.
![SubtitleEdit_10](https://user-images.githubusercontent.com/18901924/79067207-179cbd80-7cbe-11ea-8d15-57197b07fbe6.png)

Second test:
1. When SE is started, OCR method: Binary image compare (default), Dictionary: none.
2. I change OCR method to Tesseract 3.02 - it works.
3. I change Dictionary (OCR auto correction) - it freezes.
![SubtitleEdit_11](https://user-images.githubusercontent.com/18901924/79067213-1bc8db00-7cbe-11ea-8117-b11a996c589c.png)

BTW: I started SE from terminal and noticed some initial errors, part of it might be interesting:
`01d0:fixme:wer:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscordacwks.dll", 0x79140000) stub!
01d2:err:ole:CoGetContextToken apartment not initialised
01d0:fixme:path:parse_url failed to parse L"System"
01d0:fixme:path:parse_url failed to parse L"System.Windows.Forms"
01d0:fixme:path:parse_url failed to parse L"System.Drawing"
01d0:fixme:nls:LCIDToLocaleName unsupported flags 8000000
01d0:fixme:nls:get_dummy_preferred_ui_language (0x0 0x32af8c (nil) 0x32af88) returning a dummy value (current locale)
01d0:fixme:nls:get_dummy_preferred_ui_language (0x0 0x32af8c 0x3b483b8 0x32af88) returning a dummy value (current locale)
01d0:fixme:path:parse_url failed to parse L"Accessibility"
01d0:fixme:path:parse_url failed to parse L"System.Core"
01d0:fixme:ntdll:EtwEventRegister ({8e9f5090-2d75-4d03-8a81-e5afbf85daf1}, 0x1130792, (nil), 0x14c0c70) stub.
01d0:fixme:path:parse_url failed to parse L"mscorlib.resources"
01d0:fixme:path:parse_url failed to parse L"mscorlib.resources"
01d0:fixme:process:FlushProcessWriteBuffers : stub
01d0:fixme:gdiplus:GdipGetFamilyName No support for handling of multiple languages!
01d0:fixme:nls:GetCalendarInfoW Unimplemented caltype 2
01d0:fixme:nls:GetCalendarInfoW Unimplemented caltype 4`

**Comment by niksedk** [comment]
OK, the freeze is probably because the `OcrFixEngine` also fails due to the blank ThreeLetterISOLanguagename... 

How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by Signy13** [comment]
Great! It works like a charm!
This version runs under latest Wine 5.0 with .NET v4.0.30319 (Xubuntu 18.04).
And what more - SE is probably more versatile because it allows to call Tesseract with different `.traineddata` files in an easy way.
@niksedk - thank you for your time and effort :-)

**Comment by niksedk** [comment]
Thx for reporting and testing again and again.
Yes, nice with better Tesseract language detection :)
