### ISSUE TITLE
Missing green coloured subtitles in Inport/OCR VobSub

### ISSUE THREAD

**Issue by Signy13** [SubtitleEdit/subtitleedit#4106]
There are missing green coloured subtitles if I choose OCR method Tesseract 4 or Binary image compare. Green subtitles (in all colours) are recognized only with Tesseract 3.02.
![SubtitleEdit_03](https://user-images.githubusercontent.com/18901924/78982343-39613d80-7b22-11ea-8799-25d4b911082d.png)

File for testing:
https://uloz.to/file/xTsFGbjHHufh/se-test-subtitles-mkv

SubtitleEdit version: 3.5.14, Mono installation on Xubuntu 18.04, Wine installation with dotnet471.

**Comment by niksedk** [comment]
thx :)

Was an issue with using wrong threshold value when making image binary.

Latest beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by Signy13** [comment]
Thank you very much for such a quick solution. It works now.
BTW: thank you for your effort with this piece of software :-)
