### ISSUE TITLE
Settings windows crashes

### ISSUE THREAD

**Issue by hros** [SubtitleEdit/subtitleedit#4107]
Opening Option/Settings
results in the following error:
InvalidArgument=Value of '0' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex

version 3.5.14 (packaged by Chocolatey)
Windows 10

**Comment by niksedk** [comment]
Does it also happen in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip (just overwrite the files)?

Probably need longer stack-trace or the Settings.xml file.

**Comment by joeheaven** [comment]
Hi,
I can confirm this. Happens here as well, Windows 10, 1903.

Also tried the referenced Beta files, same result.

Unfortunately I cannot copy&paste the trace, I made a screenshot, but cannot attach it here.

**Comment by niksedk** [comment]
You can drop (or paste) .zip files or image files here.

**Comment by niksedk** [comment]
Feel free to email me too :)

**Comment by lupinthird** [comment]
This happened to me too.  I discovered the issue, which is that Subtitle Edit has to be run as an Administrator before this screen will open.  Appears to be throwing an exception in SubtitleEdit.Forms.Settings.InitComboBoxWordListLanguages() if you aren't running as an Administrator.

**Comment by niksedk** [comment]
@lupinthird: I could also not re-produce this... even though I tried multiple different installation ways.
Did you install the "portable version" to "C:\Program Files\..." ? That will require you to run in admin mode, so it's better to install the "portable version" to something like "C:\Tools\SE" (or use the installer).

Still very interested to hear how this happens, so I can re-create and fix it! (please supply as many details as possible, like OS, Settings.xml file, installation folder, full strack-trace, screenshots etc.)

**Comment by lupinthird** [comment]
I used the installer with the filename of SubtitleEdit-3.5.14-Setup.exe with a file size of 6,639,647.  I installed it to the default location, which in this case is C:\Program Files\Subtitle Edit

OS is Windows 10 Enterprise 1903, Build: 18362.476

Yes, it is joined to a domain. :)
[SubtitleEditBugReport.zip](https://github.com/SubtitleEdit/subtitleedit/files/4487340/SubtitleEditBugReport.zip)

**Comment by EuphoricCatface** [comment]
Arch Linux ARM. found similar thing happening after installing it via AUR.
It seems that it happens when `~/.config/Subtitle\ Edit/Dictionary` is not properly populated.
Probably one of the recent commit on the Dictionary folder on Github repo broke it, imo

Portable version seems to default to `~/.config/Subtitle\ Edit/` as well, if the folder exists.

**Comment by maderios** [comment]
Linux Arch Aur last 3.14 version
I get crash too with "settings" 
![subtitleedit-3 14-settingcrash](https://user-images.githubusercontent.com/34273459/79581951-68038900-80cb-11ea-9ec5-df9e916d21e8.jpg)

**Comment by maderios** [comment]
No crash with 3.13 version

**Comment by lupinthird** [comment]
Did anyone else mess with their Dictionaries folder prior to launching for the first time after install?  Confession: I installed 3 separate French dictionaries, the .add and .dic files, anyway.  But mine does actually launch and open properly, if I run it as Administrator.  For Linux, does it still happen if you run it with sudo?

**Comment by maderios** [comment]
@lupinthird Which Linux system? If you need to be root to run dictionnary, you have permissions problem on your system. Check your user directories permissions.

**Comment by lupinthird** [comment]
I'm not running Subtitle Edit in Linux, lol.  My report was for Windows.  I was asking the Linux users (you) if the problem went away during that condition.  I have a workaround for Windows, it's running as Administrator.  Not a great workaround, but it DOES work.

**Comment by niksedk** [comment]
@maderios / @EuphoricCatface : Could you see if you still get the crash in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip ?

**Comment by lupinthird** [comment]
The latest beta solves the issue for me (in Windows 10).

**Comment by maderios** [comment]
@niksedk "options" works (Linux system) in latest beta. No crash.

**Comment by EuphoricCatface** [comment]
No crash with the beta version. Even when "~/.config/Subtitle\ Edit/Dictionary" is already created and the beta binary is opened without any data files with it; that is, where I assume the beta binary is running with the Settings.xml file and Dictionary folder initialized with the "stable" binary.

While we're at it, could you do me a favor? I think I deserve it since I provided the key perspective for the bug ^^
I'm trying to run this program on Crostini on my Chromebook. Crostini doesn't provide GPU accelerated video decoding (yet), so I would love it if you could add `--no-video` and `--ao=` options or equivalents for mpv and vlc. (though the reason for the latter option is probably my fault not getting PulseAudio to work right :P)

Much appreciated with your work on this awesome project!

**Comment by niksedk** [comment]
I think the crash is fixed.

@EuphoricCatface: you can change the -vo for Llinux via the xml tag `MpvVideoOutputLinux` in the file `Settings.xml`. You could probably use `null` for no video, or try some other options here: https://mpv.io/manual/master/#video-output-drivers

**Comment by EuphoricCatface** [comment]
Indeed the crash is fixed. I have the container reset (for another reason) and freshly installed it. now I have no problem about it.

I have tried `vo=null` with mpv, but it is still somehow significantly different than `no-video`. I can tell the difference by how the audio lags.
If you could tell me how to add a `Settings.xml` entry, I could file a pull request. Alternatively, if you just want me to open another issue, I could do that too.

**Comment by niksedk** [comment]
OK, latest beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15
Try fix the Setting `MpvExtraOption` to `video=no`

**Comment by EuphoricCatface** [comment]
It works flawlessly! Much appreciated :D
