### ISSUE TITLE
Improvement of "Tesseract returned with code X"

### ISSUE THREAD

**Issue by Signy13** [SubtitleEdit/subtitleedit#4109]
It would be useful to get more info from "Tesseract returned with code 1". 
![SubtitleEdit_07](https://user-images.githubusercontent.com/18901924/79063196-7fdca680-7ca0-11ea-873a-73806c2719f6.png)
I would be lost without knowledge how SE calls Tesseract.

I saved subtitle image as `example.png` and I ran this command:
`wine tesseract.exe example.png example -l ces --oem 0 hocr`
It returned:
`Error: Tesseract (legacy) engine requested, but components are not present in C:\Aplikace\Tesseract_500/tessdata/ces.traineddata!!
Failed loading language 'ces'
Tesseract couldn't load any languages!
Could not initialize tesseract.`

In similar cases might be helpful:
* if SE showed the error message produced by Tesseract (if it is not too complicated),
* if SE showed the command which led to this error (which arguments were used),
* maybe even to advice right clicking on subtitle image and save it as...

Or another approach - if this info was sent in some log file, there could be just notice like:
`Please check file D:\....\logfile.log for more information about this error.`

With similar info would be for users easier to find out why Tesseract is not working and solve problems, which are not related to SE itself.
(BTW in my case the problem is in the `ces.traineddata` file - it does not support `Original Tesseract only` mode.)

**Comment by xylographe** [comment]
Try **`SE-3.5.14-issue4109.7z`** from [this DropBox folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0).
It should show the actual Tesseract error message (if any) instead of "Tesseract returned with...".

**Comment by Signy13** [comment]
@xylographe thank you for this improvement. But I am a bit lost now. 
I am running SubtitleEdit on Wine 5.0 .NET 4.0 (Xubuntu 18.04) and I can not see any Tesseract errors now - just results are as if there was something not working:
![SubtitleEdit_32](https://user-images.githubusercontent.com/18901924/79120199-a0852900-7d92-11ea-86d2-2c789ee80c1a.png)
I have got the same behaviour even if I test it with different versions of Wine and .NET. Where older versions show error, new one does not.
The most weird thing is that I am pretty sure I could see the error from your version yesterday, when I did a quick test...

**Comment by xylographe** [comment]
SE mostly invokes Tesseract asynchronously (i.e. from a threadpool thread). Such invocations will never report errors. SE only reports the last (most recently encountered) error if Tesseract has been invoked from the UI thread:

https://github.com/SubtitleEdit/subtitleedit/blob/bb369ec385dcf6d3d3b19e1014f4a66d64045893/src/Forms/Ocr/VobSubOcr.cs#L5574

However, if more than 2 Tesseract errors have been accumulated nothing will be reported, to prevent the same error being shown in a MessageBox over and over again. Unfortunately, that also means that if the first Tesseract invocation (from the UI thread) were to accumulate more than 2 errors, there will be no feedback (MessageBox) at all.

**Comment by Signy13** [comment]
I am sorry I do not understand the using of the threadpool (I am not a programmer), but if errors can not be reported to a user then is not very convenient situation. The user can see that something is wrong but he gets no information what can be wrong and how to solve it.
Is there any way how to get this information for user?

The fact that there can be a lot of same/different errors can be solved by a user decision with three options:
* continue to the next error,
* continue and ignore the rest of errors
* cancel OCR.

It might be a dialogue with three buttons like:
`Line nr. X`
`Tesseract was called with arguments: "tesseract.exe input.png output -l ces --oem 0 hocr" and returned with code 1`
`Error: Tesseract (legacy) engine requested, but components are not present in C:\Aplikace\Tesseract_500/tessdata/ces.traineddata!! Failed loading language 'ces' Tesseract couldn't load any languages! Could not initialize tesseract.`
`Would you like to continue, or cancel OCR?`
`Continue` `Continue and ignore errors` `Cancel`
