### ISSUE TITLE
Incorrect treatment of unicode HYPHEN sign

### ISSUE THREAD

**Issue by JereckNET** [SubtitleEdit/subtitleedit#4112]
These last few weeks, I have downloaded multiple SRT files with the same problem :
In texts the character [HYPHEN "‐" [U+2010]](https://www.fileformat.info/info/unicode/char/2010/index.htm) is used instead of the [HYPHEN-MINUS "-" [U+002D]](https://www.fileformat.info/info/unicode/char/2d/index.htm).
The _arrow_ in the timecodes are not affected.

**In case of dialogs**
There is not visual difference, but it is not properly treated when using the "Remove text for hearing impaired" (Some lines that should be completely removed are still there, with only the hypen sign).
Example :
`
‐ You're weird!<br />
‐ [sigh]
`
Is replaced by :
`
‐ You're weird!<br />
‐ 
`
Instead of simply :
`
You're weird!
`

--> Both [U+2010] and [U+002D] should be treated as equals.

**When used in words**
Some players can't render the [U+2010] hyphen, and will render a "Non-printable character" in the middle of words.
--> A replacement tool to transform [U+2010] to [U+002D] should be added to the "Fix common errors" fixes.

**Comment by OmrSi** [comment]
@niksedk Copying the example and testing works. Closed?

**Comment by JereckNET** [comment]
I reviewed the commit, but it only takes care of one part of the problem (and I am already grateful for that)..

May I suggest to assign both the labels "fix common errors" and "remove text for hi" to this issue ?

**Comment by OmrSi** [comment]
I think the new "Normalize text" in FCE now changes this to `HYPHEN-MINUS "-" [U+002D]`.
