### ISSUE TITLE
Feature Request / Sugesstion: Convert Option with Dynamic Order

### ISSUE THREAD

**Issue by Gosokan** [SubtitleEdit/subtitleedit#4113]
Hello developer,

The convert option in the latest stable version cannot be changed in order
![image](https://user-images.githubusercontent.com/13587422/79121173-e2c45f80-7dbe-11ea-81f4-9f99b7813761.png)

I think it would be better if convert option checkbox can be arranged in order dynamically. As an illustration with image because I can't write English well:

I want to deleting match string in many srt files at once, so I can drag ![image](https://user-images.githubusercontent.com/13587422/79122813-e35ef500-7dc2-11ea-8cc7-43bb365a0b5b.png) and drop to first order. Then I can drag  ![image](https://user-images.githubusercontent.com/13587422/79122736-b1e62980-7dc2-11ea-85f9-4783791d2e40.png) and drop in second order.

![image](https://user-images.githubusercontent.com/13587422/79124456-882f0180-7dc6-11ea-99d5-0a6e0c82f72e.png)

It would be better also, if text line in List view can be multiple selected only by mouse drag-select , as can be done in the Workshop Subtitles program

![subtitle-workshop](https://user-images.githubusercontent.com/13587422/79126846-ee1d8800-7dca-11ea-86dd-1bf5af37950b.gif)

Thank you

**Comment by OmrSi** [comment]
The mouse thing is also mentioned here https://github.com/SubtitleEdit/subtitleedit/issues/3743
