### ISSUE TITLE
Dialogue

### ISSUE THREAD

**Issue by Lero91** [SubtitleEdit/subtitleedit#4118]
I am a two-year user of your wonderful program and I thank you, guys, for your excellent work.
Since the introduction of the dialogue style in 3.5.14, not all are following the same style. I am not sure, if I use dash or a hyphen matters, or the language I write in. I have also tried the latest beta and the issue remains. For now, I rolled back to 3.5.13.

**Comment by OmrSi** [comment]
When are they following the same style?
Can you give an example?

**Comment by Lero91** [comment]
![Pre-fix 3 5 14](https://user-images.githubusercontent.com/63797709/79486600-9b88d980-801f-11ea-99c5-4f2d0d1c1d7f.jpg)
![Settings](https://user-images.githubusercontent.com/63797709/79486626-a80d3200-801f-11ea-98c7-3842b40ab9c3.jpg)
![Post fix 3 5 14](https://user-images.githubusercontent.com/63797709/79486640-ac394f80-801f-11ea-935d-dc765bfbbabd.jpg)
See that not all lines are recognized as dialogue and there is no space between the dash and the word after it.

**Comment by OmrSi** [comment]
@niksedk It's because `;` isn't consider an end of a line, right?

**Comment by Lero91** [comment]
Yes, you are probably right. I haven't thought of that.

**Comment by OmrSi** [comment]
Yes. SE depends on the presence of an "End of line character" to determine if a line is considered a dialog or not. So if the first line ends with `?!.` it means that the line has ended and it is a dialog.
Because they use `-` in some languages for things other than dialog, that's why it uses this rule.
Anyway, the developer @niksedk will decide what to do with this.

**Comment by Lero91** [comment]
Thank you for the help.

**Comment by niksedk** [comment]
Is `;` considered a line ending in Greek?

**Comment by OmrSi** [comment]
@niksedk It seems so: http://questionmark.guide/greek-question-mark/

**Comment by Lero91** [comment]
Yes, it is a line ending.

**Comment by niksedk** [comment]
@Lero91: Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip ?

**Comment by Lero91** [comment]
@niksedk Tested it and it works fine. It also fixes the casing after the question mark that I wanted. Thank you very much.
