### ISSUE TITLE
[bug] Fix Common OCR errors problem in punctuation and quotes last SE beta

### ISSUE THREAD

**Issue by moob158** [SubtitleEdit/subtitleedit#4119]
In Fix Common OCR errors on last beta always change the punctuation in text if there are quotes after the punctuation

how to stop this?
I don't like the "new continuation style" options

![Capturar](https://user-images.githubusercontent.com/60049180/79480573-2f4dac00-8006-11ea-85f7-d5afd64e15f9.PNG)

**Comment by niksedk** [comment]
Could you attach the subtitle file?

**Comment by moob158** [comment]
@niksedk 

this happens with any subtitle, I tested with subtitles in Portuguese and English

[The Innocence Files s01e01.zip](https://github.com/SubtitleEdit/subtitleedit/files/4489762/The.Innocence.Files.s01e01.zip)

**Comment by niksedk** [comment]
Bug should be fixed in latest beta now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip
