### ISSUE TITLE
[Feature Request] Add a new line with "SAMPLE TEXT" to multiple subtitle at once.

### ISSUE THREAD

**Issue by zicksl** [SubtitleEdit/subtitleedit#4122]
Hello!

On batch convert if it's possible to add a feature that let you add a new line with "SAMPLE TEXT" to every subtitle at the beginning and the ending. I see many topics with people who wants to remove a certain piece of text , I want the opposite.

**Comment by niksedk** [comment]
Not really a common thing to do... more suited for a plugin IMO
