### ISSUE TITLE
Text to UPPERCASE and lowercase

### ISSUE THREAD

**Issue by zcraber** [SubtitleEdit/subtitleedit#4123]
Is there any option to change the text to UPPERCASE and lowercase?

**Comment by niksedk** [comment]
Tools -> Change casing :)

**Comment by niksedk** [comment]
If you mean for a whole subtitle (or selected lines) that is.

**Comment by niksedk** [comment]
For the textbox you can use these shortcuts:
![image](https://user-images.githubusercontent.com/1261331/79553058-358e6780-809c-11ea-99f9-408d9f2f34b9.png)
