### ISSUE TITLE
Sub encoding always sets to 28592: Central European (ISO), so can't save the file with proper encoding.

### ISSUE THREAD

**Issue by Mounter81** [SubtitleEdit/subtitleedit#4124]
Hello!

I've been using SubEdit portable (zipped version) for a while, since many releases for editing and translating .srt subfiles from English to Hungarian. What never happened me before: now with the latest **3.5.14**, every time I try to load a new subtitle, it auto sets the encoding to **28592: Central European (ISO)**, no matter if its an English or Hungarian subtitle. And so does save it in this encoding format, no matter if I try to set it to **1250: Central European (Windows)** every time before, the result is the same, it wont change and the saved sub will stay **28592: Central European (ISO)**.
I don't know what could went wrong since, what is the miss setting, but it happened a day to another. Have tried to reset the settings and also delete and reunzip the  **3.5.14** version, but it still operates this same wrong way, which is very strange IMO.

I have also some previous version of SubEdit portable in hand, so I could check it that with i.e. version 3.5.13 it still works the proper way like before, so I can load up and save the sub files with the proper, desired encoding setting. 

What could have gone wrong here, and how to fix it (if possible)? Or is this some new bug in  **3.5.14** I wasn't yet aware about?

Thanks for the replies and suggestions!

**Comment by OmrSi** [comment]
Have you tried the latest beta?
I think this is related to https://github.com/SubtitleEdit/subtitleedit/issues/4091

**Comment by Mounter81** [comment]
Not since, but will. But I'm sticking basically to the practice to always use stable releases. Will check and report back.

**Comment by OmrSi** [comment]
Well, if it works, it will also work in the next release. :)

**Comment by Mounter81** [comment]
You mean [this beta](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip)? No change, it still detects everything as **28592: Central European (ISO)** for me.

**Comment by niksedk** [comment]
Could you attach a few sample files - please include both an Hungarian and an English sub file (you can drag-n-drop .zip files here - or copy/paste)?

SE has some ANSI encoding auto guessing - but that probably fails for your files (it might work if you turn "Auto detect ANSI encoding" off in Options - Settings; but if would rather get this working)

**Comment by Mounter81** [comment]
Sorry partially I was wrong, so for unedited and unsaved English subs it detects them as UTF, but for all my previously saved Hungarian subs it still loads and saves as **28592: Central European (ISO)**. Here are some Hungarian sub samples.
[Sub Samples HUN.zip](https://github.com/SubtitleEdit/subtitleedit/files/4493493/Sub.Samples.HUN.zip)
When I disable "Auto detecting ANSI" itt keeps on loading and detecting every of them as **1252 Western European (Windows)**, so that's still incorrect.

**Comment by niksedk** [comment]
Thx for the sample files :)

I've tried to improve the Hungarian ANSI auto detect: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip
Is that better?

**Comment by Mounter81** [comment]
Yes, now it appears to detect and save them correctly, thanks for the correction! :)
