### ISSUE TITLE
Bug in "Adjust durations" with lines shorter than minimum duration

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#4125]
I found a bug in the "Adjust durations" feature:

When using the Adjust via seconds option:
Lines that are shorter than the minimum duration (1400 ms in my case) don't get adjusted properly.

For example, take this subtitle:

![image](https://user-images.githubusercontent.com/3516155/79638692-26381880-8187-11ea-9e0c-a5c3035af282.png)

When I add 40 ms, the line that is too short gets reset to the minimum duration, causing overlap:

![image](https://user-images.githubusercontent.com/3516155/79638702-3f40c980-8187-11ea-835a-0e77628cdbd9.png)

When I substract 40 ms, the line that is too short will remain unchanged:

![image](https://user-images.githubusercontent.com/3516155/79638756-76af7600-8187-11ea-9f47-755b7ec2d5cb.png)

**Comment by OmrSi** [comment]
An issue related to "Adjust duration" https://github.com/SubtitleEdit/subtitleedit/issues/3276

**Comment by OmrSi** [comment]
I think this is closed with https://github.com/SubtitleEdit/subtitleedit/commit/349c562a8f4a66438cb5f717c03dc6088e9b7574
