### ISSUE TITLE
.srt to 3d

### ISSUE THREAD

**Issue by btd1337** [SubtitleEdit/subtitleedit#4130]
Hi devs, 

Congratulations on this great work.

I have one question: This app supports to convert .srt subtitles to 3d side-by-side, like [3DSubtitler](https://www.videohelp.com/software/3DSubtitler) and [sub3dtool](https://github.com/TheZoc/sub3dtool)?

Thanks in advance

**Comment by OmrSi** [comment]
I think you can do that by exporting the subtitle to sub/idx and choosing 3D:
![image](https://user-images.githubusercontent.com/20923700/79677805-b3b64f80-81fd-11ea-86f8-3a439006053e.png)

**Comment by btd1337** [comment]
@OmrSi Unfortunately this legend type seems don't work with Plex on LG TV. It's that I need.

Sub3dtool convert to Advanced Sub Station Alpha format (.ass), but for some unknown reason, the caption on the right side renders approximately 1s after the left side and this causes problems in reading.
