### ISSUE TITLE
[Feature Request]/ Command line  convert to plain text  optional-parameters

### ISSUE THREAD

**Issue by raidsan** [SubtitleEdit/subtitleedit#4133]
for  convert to plain text by command line,  not support specify  optional-parameters?
such as :   Unbreak lines (default not select) ,   Show line numbers (default not select)
when I use it in GUI,  it can remember the option on next start,  but  in command line,  it always use default option,  and can't specify these options.

**Comment by raidsan** [comment]
hi, I read the source code and found the issue.   If open export plain text window once and  change the options, it should save to settings, but it doen't work.   pls see the source code:

subtitleedit\libse\Settings.cs:  lines 7046 - 7048:
`7046                textWriter.WriteElementString("UseNoLineBreakAfter", settings.Tools.UseNoLineBreakAfter.ToString(CultureInfo.InvariantCulture));
7047                textWriter.WriteElementString("NoLineBreakAfterEnglish", settings.Tools.NoLineBreakAfterEnglish);
7048                textWriter.WriteElementString("UseNoLineBreakAfter", settings.Tools.ExportTextFormatText);
`
I think in the 7048 line ,  "UseNoLineBreakAfter"  should be "ExportTextFormatText"

**Comment by niksedk** [comment]
Nice catch :)
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

Fixed in 1f3eb1a893be03ab9097cde4527d1b45b616a708
