### ISSUE TITLE
Pathlogical Bluray sup file that causes timestamps to reset to back to zero

### ISSUE THREAD

**Issue by amichaeltm** [SubtitleEdit/subtitleedit#4138]
So I used eac3to to extract a SUP file from the playlist of the Voltes V Bluray disc. The playlist is around a bit longer than 16 hours. What is weird is at after subtitle 10163 that ends at the timestamp 13:15:17.645 that the next subtitle below it shows a starting timestamp of 00:00:03.227. Here's a picture of what I'm referring to:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/38765529/79944205-8998a380-8430-11ea-974b-73bae390ad5b.png">

The sup file in question can be grabbed from here: https://www.dropbox.com/s/x409h737i4krbra/voltesv.sup?dl=1

**Comment by niksedk** [comment]
Thx for a nicely made issue :)

I don't know why the time code resets... but the actual byte values are as shown in your screenshot.
If anybody knows, please share :)
