### ISSUE TITLE
Feature Request: OCR unknown words - Add to selected dictionary

### ISSUE THREAD

**Issue by Signy13** [SubtitleEdit/subtitleedit#4139]
There is already option to add unknown word into user dictionary. I have got a dictionary where there is a lot of word missing so I would like to add them into the selected dictionary. As a result I could have:

* official dictionary with standard language improved by unknown  words (this dictionary is shared with other applications so spell checking would be only improved, not spoiled by slang word),
* user dictionary with slang words used in common language in movies.

![SubtitleEdit_74](https://user-images.githubusercontent.com/18901924/80018916-0da56680-84d7-11ea-8554-5925722c7a43.png)
Is it possible to add button like `Add to selected dictionary`?

**Comment by niksedk** [comment]
Sorry, SE don't have any way of updating Hunspell (or voikko) dictionaries
