### ISSUE TITLE
[Feature Request] Improve excle subtitle type

### ISSUE THREAD

**Issue by geekfory** [SubtitleEdit/subtitleedit#4142]
Hope to import subtitles in excle format (xls/xlsx)，The format is as follows (The format does not include the yellow table).

![_20200423114221](https://user-images.githubusercontent.com/52827965/80056814-aed40180-8557-11ea-97e3-afa3138015b7.png)

time code mode: HH:MM:SS.MS
00:00:17.910 | 00:00:21.200 | Hiding from the rain and snow
-- | -- | --
00:00:21.200 | 00:00:25.740 | Trying to forget but I won't let go
00:00:25.740 | 00:00:29.630 | Looking at a crowded street
00:00:29.630 | 00:00:34.200 | Listening to my own heart beat
00:00:34.200 | 00:00:41.399 | So many people all around the world
00:00:41.399 | 00:00:48.239 | Tell me where do I find someone like you girl
00:00:48.239 | 00:00:52.179 | Take me to your heart take me to your soul

time code mode: HH:MM:SS:FF
00:00:17:22 | 00:00:21:05 | Hiding from the rain and snow
-- | -- | --
00:00:21:05 | 00:00:25:18 | Trying to forget but I won't let go
00:00:25:18 | 00:00:29:15 | Looking at a crowded street
00:00:29:15 | 00:00:34:05 | Listening to my own heart beat
00:00:34:05 | 00:00:41:10 | So many people all around the world
00:00:41:10 | 00:00:48:06 | Tell me where do I find someone like you girl
00:00:48:06 | 00:00:52:04 | Take me to your heart take me to your soul

**Comment by niksedk** [comment]
SE don't have any Excel reading capabilities atm.
You should probably attach one or two sample files as they might have more info about the format.

Alternatively, you could save as .csv and try to open that file in SE.
