### ISSUE TITLE
Subtitle edit only load part of the file

### ISSUE THREAD

**Issue by Seraphli** [SubtitleEdit/subtitleedit#4143]
I use subtitle edit to edit a srt file based on an audio file. The audio file is 9 minutes long. The subtitle file was generated by an SDK. So I use subtitle edit to correct the file.
And when I load the audio file for the first time, there is an error telling me to install LAVFilters. So I install the 0.74.1 version of LAVFilters. After that, I can open the audio file, but it only displays 5 minutes. I can not move the cursor forward.
![image](https://user-images.githubusercontent.com/1586755/80074993-975b3f80-857c-11ea-9d52-0e8088bb4db5.png)
![image](https://user-images.githubusercontent.com/1586755/80075183-e30de900-857c-11ea-9acb-8558c42defd5.png)
But in the waveform part, it displays more than 5 minutes, but still, I can not drag the cursor because it thinks the audio file is finished.
BTW, I can play the audio in another software.

**Comment by niksedk** [comment]
You can try another video player - see Options - Settings - Video player.
I would recommend that you click on "Download mpv lib" and use "mpv".

If that does not work perhaps you like link / post / e-mail the audio file?

**Comment by Seraphli** [comment]
Well I tried this. It turns out that I can not visit raw.githubcontent because I'm in China. I can't find any proxy setting. So is there another manual install way to enable this? Or maybe I could try to install a portable VLC.

**Comment by Seraphli** [comment]
Well I set the proxy and download `mpv`, but the problem still exists. I can send you the audio file by email.

**Comment by Seraphli** [comment]
Strange, the first time I load the audio file, I can not drag the cursor forward. But when I double click on the line that is on 7 mins, I can jump to the certain time. And when I click play, the total time increases. Although I can not drag the cursor, I can play the last line so that it displays the correct total time.

**Comment by niksedk** [comment]
@Seraphli: Please do send the audio by email - nikse.dk@gmail.com - I can take a look.

**Comment by Seraphli** [comment]
OK, I have sent you the audio file and the srt file.

**Comment by niksedk** [comment]
OK, both LAV filters and mpv returns 5 minutes which is strange.
VLC however returns the correct length of 9 minutes (important - install the 64-bit version of VLC as you're probably on a 64-bit version of windows).

**Comment by Seraphli** [comment]
Yes I installed the 64-bit version of VLC, but after I set the location, I can not drag the progress bar. Maybe it's because I'm not using portable version.

**Comment by niksedk** [comment]
OK, at least I fixed the "waveform progress bar": https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

The rest is really not SE I think, but the underlying media libs.
