### ISSUE TITLE
Can't open “Options | Settings”

### ISSUE THREAD

**Issue by gjgigol** [SubtitleEdit/subtitleedit#4145]
I get the following Windows Forms Thread Exception:

![image](https://user-images.githubusercontent.com/46090959/80192377-5f550a80-8617-11ea-8764-f3c2dbdc34f9.png)

OS: Windows 7 Professional

**Comment by niksedk** [comment]
thx for the info - should be fixed in latest beta :)

Also, duplicate of #4107
