### ISSUE TITLE
Replacement in OCR by regex does not work

### ISSUE THREAD

**Issue by borifax** [SubtitleEdit/subtitleedit#4146]
Anyone know how to solve this problem?
Despite the definition of regex, I still have to make changes manually.

![regex](https://user-images.githubusercontent.com/45988475/80201555-9978d900-8624-11ea-9928-f9e2a5556ea5.png)
![Schowek01](https://user-images.githubusercontent.com/45988475/80201559-9b429c80-8624-11ea-9bf5-54b80035f604.png)

**Comment by niksedk** [comment]
`<RegEx find="(\p{Lu})l\b"  replaceWith="$1I" />` works fine here:
![image](https://user-images.githubusercontent.com/1261331/80209580-a1d81080-8632-11ea-801d-e6da6d047583.png)

**Comment by borifax** [comment]
Ok, but why doesn't this happen automatically as in this case?

![ang regex](https://user-images.githubusercontent.com/45988475/80217207-9f2fe800-863f-11ea-8b2f-de3650da21f0.png)
