### ISSUE TITLE
Only part of the video shows using DirectShow

### ISSUE THREAD

**Issue by OliviaZ59800** [SubtitleEdit/subtitleedit#4147]
Hi,
I was working on a project, then accidentally put the computer to sleep (asus UX303U notebook). Turned it back on, and now, only a snippet of the video appears (I use DirectShow).

![here is a screenshot](https://user-images.githubusercontent.com/64307945/80277031-99dca700-86ec-11ea-8c1d-639d3cce3c2d.jpg)

Tried uninstalling/reinstalling SE, didn't change anything.
Tried switching to VLC 64 bit, but the video won't play properly (pixelated/lagging).
Tried mpv, but unable to play the video frame by frame.
Tried installing Lav filters, but didn't fix the pb (not sure if I installed it properly).

at a loss as of how to move forward. Each video option presents a different problem.

DirectShow was working fine until I accidentally restarted the computer.

How do you advise I proceed? Thanks.

**Comment by niksedk** [comment]
>Tried mpv, but unable to play the video frame by frame.
mpv works well with SE and should have frame stepping (see the shortcuts)
