### ISSUE TITLE
[Feature Request] Quality verification tool

### ISSUE THREAD

**Issue by Ouroboros1995** [SubtitleEdit/subtitleedit#4148]
Can you make a script or a tool for technical quality verification of subtitles, something like this:
It would really be of great use to many translators and subtitle editors.

![1](https://user-images.githubusercontent.com/60438566/80286606-b3054800-872c-11ea-9ca1-3215956b6e2a.png)

Many thanks.

**Comment by OmrSi** [comment]
You can set those from the settings, and lines that violate them are colored red, you can set a shortcut to go to those lines from the settings.

**Comment by Ouroboros1995** [comment]
I know about that, even though I didn't know that there is a shortcut that will lead you to those lines. Can you explain me how to set it?

**Comment by OmrSi** [comment]
Settings -> Shortcuts -> Go to next error

**Comment by Ouroboros1995** [comment]
Its already set - F8, thank you.

Regarding the technical aspect of subtitles, whats the optimal value of min. gap between subs, I set mine to 125 ms but I don know if that the accepted value?

**Comment by OmrSi** [comment]
It varies from company to another.
Netflix uses 2 frames, which is what I also use.
2 frames in 23.976 are 84 ms.

**Comment by Ouroboros1995** [comment]
Okay. Thanks for your time.

**Comment by OmrSi** [comment]
You got it. ^_^

**Comment by niksedk** [comment]
The `Go to next error - shortcut` will work outside the list view in next update.

**Comment by OmrSi** [comment]
@niksedk Closed?
