### ISSUE TITLE
Quickly skipping subtitle segments with Page Up and Down duplicates and overwrites next/previous lines

### ISSUE THREAD

**Issue by Waldkoenig** [SubtitleEdit/subtitleedit#4154]
Here is a video of the bug:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12908506/80410919-9c492780-88cb-11ea-9e58-ca8ba67267a1.gif)

This has been the case since at least a year but today I finally snapped. I'm on Windows 10 if that matters.

**Comment by niksedk** [comment]
What version are you running and what keys/shortcuts are you using?

**Comment by Waldkoenig** [comment]
Latest version with default shortcuts. Page up/down was used for the video.

**Comment by niksedk** [comment]
Page up/down do not do that!?

**Comment by niksedk** [comment]
Please check you version in Help -> About

**Comment by Waldkoenig** [comment]
I'm sorry, I forgot I changed that. Nothing else though. I just reset and reinstalled everything, loaded subtitles, loaded a video, set page up/down to skip lines and the same thing happens. There is a visible stutter happening every time a line gets copied.

Version is 3.5.14 64-bit

**Comment by niksedk** [comment]
What is `set page up/down to skip lines` ?

**Comment by Waldkoenig** [comment]
I customized 
![image](https://user-images.githubusercontent.com/12908506/80412815-b801fd00-88ce-11ea-9f21-5c4f1cc81262.png)

**Comment by niksedk** [comment]
How is latest beta now?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

Hopefully fixed in this commit: eb3617ae9bbf57ddc47675d5d2eb24607ecfc820

**Comment by Waldkoenig** [comment]
Same. The effect is the strongest when I keep pressing Page Down and quickly tap Page Up twice while still holding Page Down.

**Comment by niksedk** [comment]
I do not get changed time codes here anymore... do you?

**Comment by Waldkoenig** [comment]
I still do.

**Comment by Waldkoenig** [comment]
It's not just the time codes that are copied. The whole subtitle line is copied as well.

**Comment by niksedk** [comment]
Yes, this a bad bug... how is this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip ?

**Comment by niksedk** [comment]
Also, what video player are you using? (not too important though)

**Comment by Waldkoenig** [comment]
It seems to work now. :) Thank you for your prompt response!

I have a bigger project to transcribe until tomorrow and will report back in any case.

I tried MPC-HC and Direct Show today with the same result. I don't remember exactly which options I used earlier.

**Comment by niksedk** [comment]
Thx for reporting and testing :)

It was a little hard getting the error with "mpv video player" (the one I use most of the time), but luckily it was easier to re-create with VLC.

**Comment by Waldkoenig** [comment]
Hey, this seems to be fixed. I transcribed an hour long webinar and not once did it bug out. Thanks again for the quick help! :)
