### ISSUE TITLE
can't open "option", display error message

### ISSUE THREAD

**Issue by chinthanasl** [SubtitleEdit/subtitleedit#4158]
Error Message:

InvalidArgument=Value of 'O' is not valid for 'SelectedIndex'.

Parameter name: SelectedIndex

Stack Trace:

at System.Windows.Forms.ComboBox.set Selectedindex(Int32 value) at

Nikse.Subtitle Edit.Forms.Settings.Init ComboBox WordList Languages at Nikse.SubtitleEdit.Forms.Settings.Init) at Nikse. Subtitle Edit.Forms.Main.Show Settings at System.Windows.Forms.ToolStripitem.RaiseEvent(Object key, EventArgs e) at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e) at System.Windows.Forms.ToolStripltem.HandleClick(EventArgs e) at System.Windows.Forms.ToolStripltem.HandleMouseUp(MouseEventAr gs e) at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea at System.Windows.Forms.Control.MouseUp(Message & m, MouseButtons button, Int32 clicks) at System.Windows.Forms.Control. WndProc(Message 82 m) at System.Windows.Forms. ToolStrip.WndProc(Message& m) at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)

![Untitled](https://user-images.githubusercontent.com/64574662/80675489-311d7200-8ad2-11ea-9ba2-d9831c167c10.png)

**Comment by niksedk** [comment]
Nice error report :)
It should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

Was also reported here in #4107

**Comment by chinthanasl** [comment]
Thanks
