### ISSUE TITLE
Tesseract 4.1.1 & 5.00 More Broken Than 3.02 on Windows

### ISSUE THREAD

**Issue by greentrancer** [SubtitleEdit/subtitleedit#4160]
Hello,

Does anyone know what is going on with 4.1.1 and 5.00 versions? 4.1.1 cannot recognise the music symbol when processing a .sup file and 5.00 cannot even recognise capital 'i' and places a vertical line '|' instead.

3.02 seems to do all that without any issues. Therefore, what are the benefits of the newer versions of Tesseract?

Thank you.

**Comment by xylographe** [comment]
Tesseract 3.02 as distributed in the (Windows-only) SE installer includes data file `music.traineddata`. This file enables the recognition of music symbols.

Tesseract 4 and 5 seem to work OK when you set "Engine mode" to _Original Tesseract_.
Note: When running SE on Ubuntu (and probably on most other Linux distributions too) you have to replace the Tesseract LSTM-only trained data files with [trained data files with support for legacy and LSTM OCR engine](https://github.com/tesseract-ocr/tessdata).

**Comment by greentrancer** [comment]
Even though I do not know much of what you are talking about, it does make some sense - thank you.

I use SE on Windows, therefore I understand why Tesseract 3.02 works better for now.

I have no idea what "Engine mode" is for 4 and 5 version and whether it is available in Windows.

**Comment by xylographe** [comment]
Iff "OCR method" is set to "Tesseract 5" (or "Tesseract 4" in older SE versions), then"Engine mode" is one of the Tesseract OCR settings:

![image](https://user-images.githubusercontent.com/8535293/80872249-11907000-8cb1-11ea-9b52-ca94296bd3a2.png)

**Comment by greentrancer** [comment]
Ah right, okay - just did that and this is the result.

![SubtitleEdit_2020-05-02_21-17-30](https://user-images.githubusercontent.com/5639078/80891193-6b496800-8cba-11ea-8efb-a2c6dc703ef5.png)

**Comment by xylographe** [comment]
Yes, Tesseract 5 (or 4) cannot recognise music symbols (the `music.traineddata` file is only available for Tesseract 3.02). However, capital 'i' recognition should be (mostly) correct.
