### ISSUE TITLE
Improve Remove Text for HI --> Some text before ":" won't get removed!

### ISSUE THREAD

**Issue by dramirvf** [SubtitleEdit/subtitleedit#4163]
**SubtitleEdit
Version 3.5.15**

Hi,
I use SubtitleEdit to remove texts for HI.
Interestingly I found an issue in this regard.

Some texts before **":"** are not detected by software, although it is text for HI!

![image](https://user-images.githubusercontent.com/40552131/80916346-537eec00-8d6d-11ea-8cd7-4b44cc311295.png)

Here is a link to a sample file which contains 59 texts for HI which are being not detected to get removed: https://gofile.io/?c=IP5LKx

Thanks

**Comment by niksedk** [comment]
Hm, it seems like this file is using comma instead of period,,,

**Comment by dramirvf** [comment]
> Hm, it seems like this file is using comma instead of period,,,

No. There problem is not relevant to "comma" or "period" at the end of the file.
It looks to be due to its location of the second line!

If you look at the photo, all HI text before ":" which are in the second line are not removed!!!

**Comment by niksedk** [comment]
```
- Believe me,
- Edward: Mr, Heidecker!
```
should be
```
- Believe me.
- Edward: Mr, Heidecker!
```

And the same goes for 
```
- And I felt like,,,
- Tim: That was there,
```
Which should be
```
- And I felt like...
- Tim: That was there,
```

So it's seems that all periods are have been replaced by periods.

**Comment by dramirvf** [comment]
I understand.
But I wish there would be someway to be able to remove HI test when the first line ends with "comma".
