### ISSUE TITLE
Bug with gap when dragging subtitles with "alt" pressed inside waveform

### ISSUE THREAD

**Issue by btsix** [SubtitleEdit/subtitleedit#4164]
When two lines are next to each other and we hold click and "alt", drag to correct both end and begin of next the gap is altered as well if selected the first one. If we do that with the second selected it's fine.

![2020-05-03-13-28-53](https://user-images.githubusercontent.com/47198437/80920040-a2179080-8d43-11ea-9a9e-ee7f9cc74847.gif)

EDIT: This bug only happens when working with time code mode in frames:
![image](https://user-images.githubusercontent.com/47198437/80920146-47326900-8d44-11ea-91b2-3b7194e24d2c.png)

**Comment by niksedk** [comment]
Thx for reporting this :)
How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip ?

**Comment by btsix** [comment]
Seems all good now. Thank you so much! :)
