### ISSUE TITLE
[Request] auto fix Spell Errors when opening a subtitle from xml file (like OCRFix)

### ISSUE THREAD

**Issue by moob158** [SubtitleEdit/subtitleedit#4167]
Auto fix some Spell Errors when opening a subtitle from xml file (like OCRFixReplaceList)

**Comment by niksedk** [comment]
We have "Fix common error" - "Fix OCR errors", is that what you mean ?

Automatic fix of spelling errors does not sound possible!?

**Comment by moob158** [comment]
@niksedk: **No**, is a list that fixes spelling errors automatically everytime you opening a new the subtitle.

the format of xml file can be like "OCRFix", ("Word from="" to=!")

is useful for some repetitive errors
