### ISSUE TITLE
"Auto fix names where only casing differs" not working correctly.

### ISSUE THREAD

**Issue by Waldkoenig** [SubtitleEdit/subtitleedit#4169]
When I run spell check and have this option enabled I still have to click Use or Use always. To get it working on positive hits I have to disable and re-enable it every time. 

I remember this working last year, so I guess it broke some time in the last few month.

**Comment by niksedk** [comment]
Works fine here...

**Comment by Waldkoenig** [comment]
I made a recording. I don't think this is the intended behaviour: https://www.youtube.com/watch?v=xk_wFxBU6Po

**Comment by niksedk** [comment]
Sorry, I cannot see what's happening... perhaps some screenshots?

**Comment by Waldkoenig** [comment]
Is the video not visible for you?

Am Fr., 15. Mai 2020 um 14:20 Uhr schrieb Nikolaj Olsson <
notifications@github.com>:

**Comment by niksedk** [comment]
No, I cannot see the text... it's all blurry.

**Comment by Waldkoenig** [comment]
Change the quality to 1080p then, please.

**Comment by niksedk** [comment]
OK, I can see the text now :)

Yes, it's meant to work like that... can you explain why that's a problem?

**Comment by Waldkoenig** [comment]
It doesn't make sense having to enable that option for each and every hit.
And I'm pretty sure it worked differently a while ago.

If it were just a button I'd kinda understand, but as it is a checkbox I
expect it to work automatically instead of me having to press it twice(!)
every time.


Am Fr., 15. Mai 2020 um 14:45 Uhr schrieb Nikolaj Olsson <
notifications@github.com>:

**Comment by Waldkoenig** [comment]
If it is checked it should to its thing and move on immediately without me
having to uncheck and recheck it.

Am Fr., 15. Mai 2020 um 14:47 Uhr schrieb Dee Cee <
direncangoez@googlemail.com>:

**Comment by niksedk** [comment]
OK, thx for having patience... I think I understand now ;)

The code while running spell check and click on "Auto fix names..." was not the same... it's now.
Also,  I've added an option weather to use the "spell check suggestions" too or only the name lists:
![image](https://user-images.githubusercontent.com/1261331/82112937-227dbe80-9752-11ea-83dc-58f6a51eeba1.png)

Any thoughts about that? Should the new option be checked by default?

**Comment by Waldkoenig** [comment]
Oh, great, thank you. :) I think it should be on by default because of how useful it is.

**Comment by Waldkoenig** [comment]
Is there a beta version with this fix somewhere? I don't know how to build SE myself.
