### ISSUE TITLE
Error loading video - Ubuntu 20.04

### ISSUE THREAD

**Issue by th3bucch** [SubtitleEdit/subtitleedit#4171]
Hi,
I'm using Subtitle Edit for some time on Ubuntu with mono and it worked well until i upgraded from 18.04 to the latest LTS release, 20.04.
Since then I'm getting an error when loading any video file, even with files I've worked on without problems before the system upgrade. Here a screen of the error and of the related packages installed on my system.
![error_SubEdit](https://user-images.githubusercontent.com/57603626/81396030-f1cfd080-9124-11ea-8d66-6694651ac848.png)

![installed](https://user-images.githubusercontent.com/57603626/81396044-f8f6de80-9124-11ea-9de7-47347eaf3020.png)

It either occur with SubtitleEdit version 3.5.14 and latest 3.5.15, also the video player selection menu in the software settings tab is all greyed out. Same error launching mono as root or as a normal user.
Seems like it won't find player libraries.

Any thought?

**Comment by niksedk** [comment]
Hm, I get the same... a System.DllNotFoundException for libmpv.so 
I'm mostly a windows guy... can you try to create a symlink file or some search path?

**Comment by th3bucch** [comment]
Yesterday i was looking at this old issue: [https://github.com/SubtitleEdit/subtitleedit/issues/2386](url) but all seems good on my system.
![libmpv](https://user-images.githubusercontent.com/57603626/81415698-12aa1d00-9149-11ea-9f35-34a447869337.png)

I even tried to link the library file directly in SE folder without good results. I don't know how mono will load or search for systemwide libraries on Ubuntu. I'm still learning unfortunately.

**Comment by xylographe** [comment]
@th3bucch 
Try running Mono in debug mode, e.g.
```
MONO_LOG_LEVEL=debug MONO_LOG_MASK=all mono SubtitleEdit.exe >Mono-SubtitleEdit.log
```
The `Mono-SubtitleEdit.log` file should reveal where Mono is trying to locate `libmpv.so`.

**Comment by th3bucch** [comment]
Hi, thanks for your suggestion.
Looking at the log, you can also find attached, there was no mention at all to `libmpv.so` because wasn't that the issue, i found an error trying to load `libdl.so` so i searched for that library and tried to link it where mono was looking for, and it worked.
`# ln -s /lib/x86_64-linux-gnu/libdl.so.2 /usr/lib/libdl.so`

[Mono-SubtitleEdit.log](https://github.com/SubtitleEdit/subtitleedit/files/4601081/Mono-SubtitleEdit.log)
Please take a look at the log to see if there is something else not functioning properly.
I'm now trying to use SE, hope it will work right.

Thanks for now.

**Comment by niksedk** [comment]
Yes, you're right. Annoying that these libs change name... what's the idea behind this?

I've listed the names used by SE ( https://nikse.dk/SubtitleEdit/Help#linux ), so people have a fighting change to create a symlink file.
E.g. I had to do this for VLC to work: `sudo ln -s /usr/lib/x86_64-linux-gnu/libvlc.so.5 /usr/lib/x86_64-linux-gnu/libvlc.so` .

Also, latest beta uses "libdl.so.2" (so it should work with Ubuntu 20.04) and has better error handling + logging: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

SE 3.5.15 on Ubuntu 20.04 will probably require `sudo ln -s /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so`.

**Comment by th3bucch** [comment]
Thanks, I will try the beta in the next days.

**Comment by niksedk** [comment]
Super, let me know how it works :)

**Comment by xylographe** [comment]
> Annoying that these libs change name... what's the idea behind this?

A change of the number at the end of the library file name means that there was an essential change to the API. For example, programs that were written for `libvlc.so.4` may not work with  `libvlc.so.5`. And, programs written for `libvlc.so.5` will most likely not work with `libvlc.so.4`.

**Comment by niksedk** [comment]
OK, should symlink files created then be in the SE folder instead of the lib folder?

**Comment by xylographe** [comment]
I think, symlinking to the SE `BaseDirectory` might be the best choice for a package-management package (which should also create a link named **`.PACKAGE-MANAGER`** in the same folder).

For a private-use installation (typically under $HOME) this might be inconvenient: if you would want to test two or more releases and/or builds in parallel, each in its own folder, you would have to create the necessary symlink(s) in each SE `BaseDirectory`, which is easy to forget, leading to SE failure without clear and precise exception message.
