### ISSUE TITLE
Fix common errors using OCR replace list suggestion

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#4172]
Hello

I ran into a weird issue here. The word "Linien" gets corrected to "Iinien" using OCR replace list using the "Fix common errors" (line 543). However, I don't seem to have that rule in either dan_OCRFixReplaceList.xml or dan_OCRFixReplaceList_User.xml.
It would be great, if the dialogue said which rule it uses, so that I could correct it / fine tune it.

![Udklip](https://user-images.githubusercontent.com/5127386/81403324-6f9ad880-9133-11ea-9420-1aed39502cd7.JPG)
![Udklip2](https://user-images.githubusercontent.com/5127386/81410421-fb673180-9140-11ea-890b-30dd0c73751a.JPG)

[dan_OCRFixReplaceList.zip](https://github.com/SubtitleEdit/subtitleedit/files/4599190/dan_OCRFixReplaceList.zip)

**Comment by niksedk** [comment]
Hm, it works fine here:
![image](https://user-images.githubusercontent.com/1261331/81468925-ac71d880-91e2-11ea-9e8a-e97d04fa39fc.png)

>It would be great, if the dialogue said which rule it uses, so that I could correct it / fine tune it.

That would not be easy to make, sorry.

**Comment by Maitch** [comment]
> That would not be easy to make, sorry.

Fair enough. 
I tested it today with nothing changed in the settings and I couldn't replicate it. Maybe it was some weird bug caused by having the editor opened for too long.
