### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by Lero91** [SubtitleEdit/subtitleedit#4174]
I found out that, when in translator mode, after you change the start time of a line and then toggle the waveform or the video on and off and merging and then unmerging lines, the original text goes blank. That happens when the edit of the original subtitle is unchecked.

Now, about the greek question mark. When the question sentence is in a different line and the following sentence is within a dialogue, it will be detected and the casing will be fixed. When both sentences are in the dialogue, the line doesn't get detected at all. See the example.
![Casing](https://user-images.githubusercontent.com/63797709/81480392-3006e600-9232-11ea-9b58-6488c6bd7853.jpg)

See that only the casing at the second line will be fixed and not at the third.

I also found a rare case about the dialogue style, where a bunch of people singing a song, e.g. the happy birthday song, like this:
-Happy birthday to you
-Happy birthday to you

-Happy birthday to you
-Happy birthday to you

Now, those line are detected only when the add a period fix is selected.
![FCE](https://user-images.githubusercontent.com/63797709/81480975-aeb15280-9235-11ea-8400-0fc2c819ece9.jpg)
![FCE period](https://user-images.githubusercontent.com/63797709/81480981-b83aba80-9235-11ea-8c88-a83fe88c4ea9.jpg)

Also, if you check only the dialogue style fix and hit apply, it won't get applied.

If you uncheck the fix, they are not detected.
![FCE no period](https://user-images.githubusercontent.com/63797709/81480992-c557a980-9235-11ea-9d8d-f226c1a3faa4.jpg)
![FCE no period 2](https://user-images.githubusercontent.com/63797709/81480995-c8eb3080-9235-11ea-86e2-38ed971e2fc9.jpg)

Something odd is that if you add a comma at any of those lines, all possible combinations, they are not detected again.

Finally, as usual, I updated the translation and I decided to make a no-break-after list for Greek.
Is it possible to add the greek question mark at the break early for end of sentence?
[Files.zip](https://github.com/SubtitleEdit/subtitleedit/files/4604233/Files.zip)

**Comment by niksedk** [comment]
Thx for the files :)

Greek translation updated here: https://github.com/SubtitleEdit/subtitleedit/commit/90b4673e08ff33862b584421c3ff89d09270de44

Greek no-break-after-list added here: https://github.com/SubtitleEdit/subtitleedit/commit/307c57b57a0daf881a0ebe4ac71e3b954c6683cd

>I found out that, when in translator mode, after you change the start time of a line and then toggle the waveform or the video on and off and merging and then unmerging lines, the original text goes blank. That happens when the edit of the original subtitle is unchecked.

That's a feature...

>also found a rare case about the dialogue style, where a bunch of people singing a song, e.g. the happy birthday song, like this:
-Happy birthday to you
-Happy birthday to you

That's a feature...

( please next time, do not mix so many different stuff in one issue, thx :)

**Comment by Lero91** [comment]
Strange features.

> ( please next time, do not mix so many different things in one issue, thx :)

I'm sorry. I won't do it again.

**Comment by OmrSi** [comment]
@Lero91 SE fixes dialog based on a rule, as I've mentioned before.
If the first line ends with a line ending like a dot or a question mark, SE knows it's a dialog as fixes it based on that.
This is so SE doesn't fix lines that aren't actually dialog, some languages, like Spanish I think, use the dash for things other than dialog.
Which means it would cause a problem.

**Comment by Lero91** [comment]
@OmrSi Yes, I guess I can always do that. Thanks for the tip.

I fixed some typos and improved some lines of the translation.
[Translation.zip](https://github.com/SubtitleEdit/subtitleedit/files/4606077/Translation.zip)

**Comment by xylographe** [comment]
Ty, @Lero91.
Improved Greek translation applied in commit 9dc35cf5106597e22f8ee62c2e048a48ad85cb44.
