### ISSUE TITLE
[Minor Bug] List loses focus if SE is launched with a file if MPV is selected

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#4175]
I thought it would be better to open a separate issue to track and gather the information in a dedicated issue.

This is what happens and I've tested this with DirectShow/MPC/VLC, it only happens with MPV:
![Untitled Project](https://user-images.githubusercontent.com/20923700/81462213-8e43b280-91b9-11ea-9122-c53a43498b88.gif)
It has something to do with the start time of the first line. When I increase the start time, it doesn't lose focus. It also happens if a waveform isn't generated and it works fine if "MPV handles preview text" is disabled.

Test file: [Battlestar-Galactica - S02E10 - Pegasus.zip](https://github.com/SubtitleEdit/subtitleedit/files/4603449/Battlestar-Galactica.-.S02E10.-.Pegasus.zip)

**Comment by niksedk** [comment]
Still does not happen here... but how is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
@niksedk I tested it on another Laptop before the latest beta and it worked fine. I don't know why it happens like that here.
But it works fine on my laptop with the latest beta. Thank you.
You can close this with the commit.
