### ISSUE TITLE
Undo function undoes more than necessary

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#4177]
3.5.15 NEXT beta 45.
Create a new subtitle file with ten lines. Fill them all with text (e.g. line one can be "1 1 1 1 1 1" etc., just enough so that you spend a second or two typing each of them). 
Perform the undo action twice. The first time clears the text from the last line, the second time clears the text from all other lines.

**Comment by darnn** [comment]
Also, not sure how to reproduce, but at a certain point, this happens:
![se undo](https://user-images.githubusercontent.com/19672444/81505700-d833b200-92f9-11ea-9db4-db07a07bc0b4.png)

**Comment by OmrSi** [comment]
Isn't it linked to the time in which you do these changes?
Like, if you do them all at once they will be a whole chunk, while if you wait for a second or two after each change, you can undo them one by one.

**Comment by darnn** [comment]
That's how it's supposed to work, but that's not what's happening right now. In my example, the first undo action removes the text from the last line. It would stand to reason that the next undo action would remove the text from the previous line (or two). Instead it removes them all. That's true as of a month ago as well, but a particularly egregious form of this (along with the error) is happening in the most recent beta, where you get several minutes' worth of work "undone".

**Comment by niksedk** [comment]
@darnn: Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip ?

It should now force a change to history, when changing index (if any changes).

Any changes of steps to re-create the crash? (tried to reduce the risk in latest beta too)

**Comment by darnn** [comment]
I'm not sure, it was a file I had open for a while, and it happened after a bunch of undos and redos. I'll let you know if it happens again in this beta.

**Comment by niksedk** [comment]
OK, thx - and how is the `Undo function undoes more than necessary` ?

**Comment by darnn** [comment]
Looking good so far! I think you can basically close this, unless you want to wait and see if the error crops up again.
