### ISSUE TITLE
how to change hebrew subtitles layout after OCR recognition? 

### ISSUE THREAD

**Issue by levzahav** [SubtitleEdit/subtitleedit#4179]
I'm using the program to create hebrew subtitles after i downloaded them from NETFLIX.
The file that is downloded is .ttml.zip that contains the subtitles as .png files and also there is a file manifest_ttml2.xml that contains the timing.
I'm using the import tool to load the images files and than i add the time sync by importing it from the .xml file
Everything works fine but since hebrew is written right to left, after the process i get the subtitles left to right.
for example: if the picture shoes: מציגה NETFLIX i get it as ‭מציגה NETFLIX
or: if the picture is: 

מעל 7000 ספרדים -
 -.חצו את שערי מאוטהאוזן

i get it as: 

םידרפס 7,000 לעמ -
- .ןזואהטואמ ירעש תא וצח

So although the puntcuations are in place the text direction is wrong.
I'm sure there is a solution for this so a wan't have to work hard to fix it
Please explain to me what to do.

**Comment by darnn** [comment]
First of all, I suggest you use, for instance, this Greasemonkey script: https://greasyfork.org/en/scripts/26654-netflix-subtitle-downloader
(I use it with Violentmonkey in Chrome, for what it's worth.)
It will download the subtitles in VTT format, which SE can open, and no conversion will be necessary.

If you do want to troubleshoot your way, I suggest you add a few of these image files so they can be tested.

However, I don't believe SE has this reverse function. Years ago I used this program, but I can't get it to work now: http://www.divx-digest.com/software/convert_hebrew_files.html

**Comment by levzahav** [comment]
Thank for the answer. I played a little with the options and found out that the solution is : 1) Under the "EDIT" menu choose the option RTL 2) Whet importing the images file use the OCR - Tesseract instead of "binary image compare".
I might try your solution too.
Meanwhile I managed.
Thanks
