### ISSUE TITLE
I can't Align srt arabic subtitle to RIGHT JUSTIFY

### ISSUE THREAD

**Issue by waelmohammed5** [SubtitleEdit/subtitleedit#4180]
I can't Align srt arabic subtitle to RIGHT JUSTIFY
when I press export>bluray sup>alignment> now there is now right justify for Arabic language, because The Arabic language is read from right so I want it to be "right justify" I don't want it left justify as if it is English.
![LEFT JUSTIFY](https://user-images.githubusercontent.com/65189153/81598393-e3f1a800-93cf-11ea-9b58-27c483fd47a6.png)

**Comment by niksedk** [comment]
How does "Center, right justify" work in latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip
