### ISSUE TITLE
CHK files reading wrong timecodes

### ISSUE THREAD

**Issue by ginodecock** [SubtitleEdit/subtitleedit#4181]
Hi,

When opening CHK subtitle files the timecode read is not correctly.

I've added an example file.

[GETCARTER_1F674011.stl.txt](https://github.com/SubtitleEdit/subtitleedit/files/4613625/GETCARTER_1F674011.stl.txt)
[GETCARTER_1F674011.CHK.txt](https://github.com/SubtitleEdit/subtitleedit/files/4613626/GETCARTER_1F674011.CHK.txt)

**Comment by niksedk** [comment]
Thx for the info :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

I don't really know much about .chk files...

**Comment by ginodecock** [comment]
Hi,

Thx for the fast reply. I've tested this and noticed the timecodes are better. However there is a difference of a second at the beginning. After 784 titles the difference has become 30minutes.

The CHK version:
![image](https://user-images.githubusercontent.com/6877889/81843456-e8dc6600-954d-11ea-9395-b72ae0f4f2b7.png)

The PAC version:
![image](https://user-images.githubusercontent.com/6877889/81843540-05789e00-954e-11ea-9023-922a20d79602.png)

The STL version:
![image](https://user-images.githubusercontent.com/6877889/81843587-13c6ba00-954e-11ea-9aec-cdb9c763bffe.png)

**Comment by ginodecock** [comment]
The subtitle file:
[THEROMANTICS_1F702661.CHK.txt](https://github.com/SubtitleEdit/subtitleedit/files/4623541/THEROMANTICS_1F702661.CHK.txt)
[THEROMANTICS_1F702661.STL.txt](https://github.com/SubtitleEdit/subtitleedit/files/4623542/THEROMANTICS_1F702661.STL.txt)
[THEROMANTICS-1F702661-BEL.PAC.txt](https://github.com/SubtitleEdit/subtitleedit/files/4623543/THEROMANTICS-1F702661-BEL.PAC.txt)

**Comment by ginodecock** [comment]
Hi,

Thx for the fast Fix. I've tested this and it works.
First I saw the timecode was out of sync. However after correcting the framerate the result was perfect.
![image](https://user-images.githubusercontent.com/6877889/81844525-81271a80-954f-11ea-9b41-43be60452c16.png)

Thx.
