### ISSUE TITLE
Bug when dragging duration from waveform not refreshing in list view.

### ISSUE THREAD

**Issue by brayante** [SubtitleEdit/subtitleedit#4182]
This happens if I drag the sync inside waveform with the respective line selected from list view.
Duration from textbox is the only field updated.
CPS from textbox don't refresh.
CPS and duration from list view don't refresh.

If I drag the line that's not selected, all is fine.

![Sem título](https://user-images.githubusercontent.com/64877210/81767339-8718ef00-94ae-11ea-9a3e-da5997e87707.png)

Maybe something to do with https://github.com/SubtitleEdit/subtitleedit/issues/4078#issuecomment-624079989

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

**Comment by brayante** [comment]
Hi, @niksedk 
I only got to test it now at BETA 92:

CPS and Durations from textbox OK!
CPS and Durations from listview still not updating.

![image](https://user-images.githubusercontent.com/64877210/81871929-2988af00-954f-11ea-9fce-f9c07b04c79c.png)
