### ISSUE TITLE
Issue/Feature Request: please add support to extract forced subs only in batch convert

### ISSUE THREAD

**Issue by kiwilad-nz** [SubtitleEdit/subtitleedit#4183]
Correct me if I am wrong but you cannot currently convert subs with the forced flag via the GUI.

I see the option is there in CLI but I seem to be having issues with that working.

Below command seems to extract ALL srt's even though I know only 2-3 of the files have forced subs.

"C:\Program Files\Subtitle Edit>SubtitleEdit /convert FilePattern* SubRip /forcedonly /inputfolder:"P:\Media"

Is this a bug or is the command not for this intended purpose?

**Comment by niksedk** [comment]
In the OCR window you can filter forced subtitles via the check box "Show only forced subtitles":
![image](https://user-images.githubusercontent.com/1261331/81842413-45d71c80-954c-11ea-8d6a-d75074ac6977.png)

cmd line works fine with the Bluray .sup below:
[forced2.zip](https://github.com/SubtitleEdit/subtitleedit/files/4623453/forced2.zip)

Please attach a sample file.

**Comment by kiwilad-nz** [comment]
Sorry, I don’t mean under OCR.

As the below, I am extracting SRT’s from them, but some have forced subs which are the ones I am after more so.

Is this possible?

[cid:image001.png@01D629AD.99F464E0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by niksedk** [comment]
Sorry, can you explain the issue better? Please attach files + screenshots on Github

**Comment by kiwilad-nz** [comment]
Hi there,

I've attached my test file. 1st subtitle track is a forced only track. 2nd is the main fully subbed track. Borth SRT format in an MKV.

Maybe I am using the CLI wrong as I imagine this isn't it's intended purpose but if so, can this be a feature request where forced flags are identified and can be extracted only then?

![image](https://user-images.githubusercontent.com/50952231/81911178-0cbcac00-9621-11ea-8358-84a5b420f6ba.png)

[TEST.zip](https://github.com/SubtitleEdit/subtitleedit/files/4626950/TEST.zip)

Hope that clears things up.

Cheers

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

Please verify :)

**Comment by kiwilad-nz** [comment]
Hi there,

Nice work on adding it to the prompt when importing a file. This will be of great use.

![image](https://user-images.githubusercontent.com/50952231/82017149-9d08f880-96d6-11ea-8dcd-bdc0b6c224c7.png)

Could it possibly be added to the batch convert too as an option for forced flags?
This would help on bulk extracting subs with the forced flag only.
Apologies if you did, I don't see it as an option.

![image](https://user-images.githubusercontent.com/50952231/82017785-06d5d200-96d8-11ea-8993-c99266f0a9d0.png)


Regards
