### ISSUE TITLE
how change subtitle spacing 

### ISSUE THREAD

**Issue by fasilmrm** [SubtitleEdit/subtitleedit#4186]
@niksedk how to change subtitle spacing in the default player of this software. the spacing issue is only happens in default player. but when i use external player like pot player or km player, its fine. any solutions? 

![Capture](https://user-images.githubusercontent.com/61681381/82071977-e6157880-96e7-11ea-950f-e97a31fa4366.PNG)

**Comment by OmrSi** [comment]
Have you tried it with MPV?
Settings -> Video Player -> Download libmpv

And if that didn't work, I think @niksedk would as you to attach the file.

**Comment by fasilmrm** [comment]
@OmrSi thanks, issue solved
