### ISSUE TITLE
[Bug] Waveform zoom percentage does not update for newly generated waveform

### ISSUE THREAD

**Issue by Meliox** [SubtitleEdit/subtitleedit#4187]
Version: 3.5.15.

The waveform zoom percentage does not update after a new waveform has been generated. The stated zoom number is the previous one despite the new waveform is zoomed 100%.

How to reproduce:

1. Load video file
2. Create waveform
3. Zoom to 10%
4. Load new video file
5. Create waveform
6. Zoom is still listed at 10% but in reality the waveform is displayed at 100%. Changing zoom using +/- and it correctly gets the zoomnumber again.

So put in
`                audioVisualizer.ZoomFactor = 1;
                SelectZoomTextInComboBox();`
Either after succesfully loading video, or after generating wave form :)

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip
