### ISSUE TITLE
Blank SRT file created from using Guess timecodes from Waveform doesn't open

### ISSUE THREAD

**Issue by vinod-svj** [SubtitleEdit/subtitleedit#4191]
Hey,

I have a project where I guess timecodes and generate an SRT using guessed timecocodes.  I save the subtitle file after generating timecodes.  But I'm unable to reopen the subttile file after saving.  I guess it is mainly because there is text within the subtitles.  Can we have some default text like "??" inserted as text when we guess timecodes from Waveform?

**Comment by vinod-svj** [comment]
I'have also forked the project and trying to figure out if there is a way for the same and contribute to the project.

**Comment by niksedk** [comment]
Hey, saving an .srt file here with empty lines works fine here - also reopen.

**Comment by vinod-svj** [comment]
For me somehow it never worked till now. Sorry the I missed one important thing in this. This works on Subtitle Edit.  For some peculiar reason, I need to try and open this another subtitling software.  It gives unsupported format error, due to blank subtitles not being read.  to circumvent this error, just guide me on how to insert some dummy text into each subtitles.

**Comment by niksedk** [comment]
You can e.g. try Edit -> Multiple replace:
![image](https://user-images.githubusercontent.com/1261331/82444465-9649ff00-9aa3-11ea-8a94-6e2d80816078.png)

**Comment by OmrSi** [comment]
Well, many ways to do that. 
1. Select all line, right click, music symbol
It should add music symbol to all lines. 
2. Select all lines, Edit -> insert Unicode character 
It should be added to all lines. 
3. Using Regex From replace or Multiple replace 
Find what: `\A\s*\z` replace with: Anything you want.

**Comment by vinod-svj** [comment]
@niksedk @OmrSi Thanks a lot.  I have been trying to find this out for long time.
