### ISSUE TITLE
Subtitles Ctrl+C, Ctrl+V bug

### ISSUE THREAD

**Issue by gleaming** [SubtitleEdit/subtitleedit#4193]
1. Open "copy paste bug.srt" (attached) in Subtitle Edit.
2. In the List View, select two or more subtitles in a row, not including last (5th) subtitle. E.g. select subtitles 1...4, or 2...4, or 2...3, or 1...2 etc. You can do that by ctrl+clicking or shift+clicking. 
3. Press ctrl+c.
4. Press ctrl+v. You won't see any changes, because you copied and pasted the same thing.
5. In the List View, click on one of the subtitles of the selection, except the first one (e.g. click the last one subtitle of your selection). You will see that first subtitle of previous selection is redrawn - its text and time codes are changed.

There's a way to escape this bug. Maybe this information will help to resolve the bug.
To escape this bug, right after ctrl+v do one of next:
- Resize or maximize (but restoring from maximize state won't work) Subtitle Edit window.
- Or, if Subtitle Edit is not maximized, just click on its window border.

I've tried to redraw both window and List View control through AutoHotkey, but that didn't work.
Bug appears on Windows 8.1 x64, Subtitle Edit 3.5.15

[copy paste bug.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/4657571/copy.paste.bug.srt.txt)

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

**Comment by gleaming** [comment]
Thanks alot! I already checked it - bug is gone!
