### ISSUE TITLE
Error 404 when using Bing Translate

### ISSUE THREAD

**Issue by obliver27** [SubtitleEdit/subtitleedit#4194]
I get this error message whenever I try to use the Bing Auto-translate. I've already set up a Microsoft Azure account with the Translator resource, and copied into Subtitle Edit the Key and the Endpoint that appears there, which is resourcegroupname.cognitiveservices.azure.com/
I guess it has to do with the adress that the endpoint refers to, since when I paste that in the browser it  returns "{"error":{"code":"404","message": "Resource not found"}}", but that's the url I'm given in the APIs section, so I don't know what I'm doing wrong.
The other thing I've tried is using the Global endpoint from https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-reference but then when the Bing translator window opens and I click Translate all I get is another error saying the specified value has invalid CRLF characters.
![Sin título](https://user-images.githubusercontent.com/47262341/82522136-e609e400-9afe-11ea-88ca-05c97cecfd09.png)

**Comment by niksedk** [comment]
Thx for the info :)

Seems Microsoft has changed the way it works again...

I think you can just put this string in the "Token endpoint": https://api.cognitive.microsoft.com/sts/v1.0/issueToken

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip (token endpoint now a dropdown box)

**Comment by obliver27** [comment]
Perfect! Works now. Thanks a lot!
