### ISSUE TITLE
[Feature Request] Export D-Cinema SMPTE PNG

### ISSUE THREAD

**Issue by regraded** [SubtitleEdit/subtitleedit#4195]
Hi Nikolaj, 

We've been using your tool for some time now and love it. We often create subtitle packages for DCP's and are moving to SMPTE DCP package type.

Many d-cinema servers/projectors do not render text very well so the ideal method for supplying subtitles is to generate PNG's for the server to overlay. This eliminates the possibility of the text rendering badly or the projector having other issues. 

Would It be possible to add the export to SMPTE/PNG feature for the D-Cinema SMPTE 2014 (XML) type?

(there is already the interop/PNG export feature but interop DCP's are becoming less and less common)

Thank you for all your work!

**Comment by niksedk** [comment]
Hi @regraded,

Yes, that should be possible...
Could you possibly attach a small sample D-Cinema SMPTE PNG xml file?
