### ISSUE TITLE
v3.5.15 broke Max Number Of Lines (2)

### ISSUE THREAD

**Issue by thejester77** [SubtitleEdit/subtitleedit#4196]
v3.5.15 broke the MASTER SETTINGS of Max Number Of Lines...

My settings have always been 2 Max Lines... but in v3.5.15, the settings become broken and (2) Max lines are not being cleaned up and 3 lines are still existing.

Please fix this... rolled back to 3.5.14 until this is fixed.

Thank you very much and keep up the great work...

**Comment by niksedk** [comment]
How exactly are 2+ lines cleaned up in SE 3.5.14?

**Comment by thejester77** [comment]
In v3.5.14…  All a user has to do is hit FIX COMMON ERRORS and all 3 lines become 2 line subs.

Of course that all depends on what SETTINGS a user sets up within the app.

I’ve been using this app for more than 4+ years, always had 2 LINES MAX and never had a problem before v3.5.15.

It seems that no matter what settings a USER has setup in v3.5.15… whatever the subtitle has when IMPORTED into the app, it remains no matter what MAX LINES are setup.

Even after hitting FIX COMMON ERRORS, the subtitles still have 3 lines (if the subs had 3 lines to begin with).

**Comment by niksedk** [comment]
@thejester77 
You need to enable "Fix subtitle with more than two lines":
![image](https://user-images.githubusercontent.com/1261331/82782235-21d4de80-9e5c-11ea-9f73-017dc17b4adf.png)

**Comment by thejester77** [comment]
That setting is already in place, as well as Max Number Of Lines within Settings>General...

Trust me... everything worked until the latest version...

The program is not applying USER SETTINGS regarding 2-3 lines...  3 lines remain NO MATTER WHAT...

Like I said, that's why I rolled back to v.3.4.15... Everything works and all USER SETTINGS apply.

**Comment by niksedk** [comment]
@thejester77: It's works fine for me here...
You could attach a screenshot of your fix common errors windows + attach the subtitle that does not work?
It would really help as I cannot re-create the error.

**Comment by thejester77** [comment]
![02- SubEdit Fix Common Errors](https://user-images.githubusercontent.com/16092775/82842154-5745f000-9e8d-11ea-8b06-83c145cca12f.png)
![01- SubEdit Settings](https://user-images.githubusercontent.com/16092775/82842157-57de8680-9e8d-11ea-8273-906dce360b74.png)

[Harley.Quinn.S02E08.Inner.Para.Demons.1080p.DCU.WEB-DL.DDP5.1.H264-NTb_Track03.zip](https://github.com/SubtitleEdit/subtitleedit/files/4678781/Harley.Quinn.S02E08.Inner.Para.Demons.1080p.DCU.WEB-DL.DDP5.1.H264-NTb_Track03.zip)

As per your request, I've attached a screen shot of Settings, Fix Common Errors and a Subtitle with 3-Lines...

**Comment by OmrSi** [comment]
@thejester77 
![image](https://user-images.githubusercontent.com/20923700/82845841-c56ecf00-9eee-11ea-80fa-98019948925b.png)

**Comment by thejester77** [comment]
Here's a copy of my SETTINGS... keep in mind that I rolled back to v3.4.15 but the settings remain the same...

I pretty much have my settings exactly the way I need them, and just update the program ontop of the previous version... so anything that breaks my settings, like v.3.5.15 did I instantly notice, because I have to do double duty cleaning my subs... so something had to change in the code because my settings haven't changed in a least a 2 years.

Thanx for trying to pin point the problem though. :)
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/4679154/Settings.zip)

**Comment by OmrSi** [comment]
![image](https://user-images.githubusercontent.com/20923700/82850946-e7744b80-9f06-11ea-84ea-9383c56406cb.png)

**Comment by niksedk** [comment]
Thx for the files - helped a lot :)
I can see that dialogs (e.g. line 5) is not fixed... should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip (please confirm)

**Comment by thejester77** [comment]
Thanx... looking forward to trying latest version...

And thanx for all your hard work :)
