### ISSUE TITLE
(Question): Is there a full list of ALL the command line options anywhere?

### ISSUE THREAD

**Issue by shawty** [SubtitleEdit/subtitleedit#4198]
I'm driving subedit from a batch file at the windows command line using:

`subtitleedit /convert ".\tmp\Abandoned Engineering S05E05 - A City Torn Apart.sub" subrip /outputfolder:.`

As part of a script I use that also includes projectX.

However, the default settings don't convert the subtitles correctly.

For example:

![image](https://user-images.githubusercontent.com/1876454/82759287-5a38d600-9de4-11ea-89f0-d568c1cdcc2c.png)

Should look like this:

![image](https://user-images.githubusercontent.com/1876454/82759348-d4695a80-9de4-11ea-996c-4c4fe9671f85.png)

When converted properly.

Both of the images above where created from sub files processed by SE, and I know exactly what settings I need to make it work.

By default, this is the OCR dialog, for the sub files produced by projectx:

![image](https://user-images.githubusercontent.com/1876454/82759413-34600100-9de5-11ea-95fd-9879e007c1bd.png)

If I start OCR like this, it makes exactly the same mistakes as I get when running from the command line (I assume these are the default settings).

If I change the settings in the dialog like so:

![image](https://user-images.githubusercontent.com/1876454/82759506-d67fe900-9de5-11ea-98d9-561a967182bd.png)

Custom Colors selected, no transparent and the British Dictionary selected, the OCR has little to no errors in it.

With the default settings, every Subtitle line has at least one error in, and they are usually errors on really common easily recognized words too, so it's definitely not a tesseract thing.

What are the command line options I need to add to my above command line to enable the changes I show in the dialog shots above?

**Comment by xylographe** [comment]
**`SubtitleEdit.exe /help`** or **`SubtitleEdit.exe /?`** shows all command line options.
However, currently (Subtitle Edit 3.5.15) there is no way to change OCR settings on the command line.

**Comment by shawty** [comment]
Hmm weird... that didn't work for me when I tried it previously :-)

If I can't change the OCR settings, then any recommendation on a better way to produce subtitles that are better suited for the default settings then?

As I say, I'm using ProjectX, creating a "sub" file by way of the following subtitle setup:

![image](https://user-images.githubusercontent.com/1876454/82761107-0d5afc80-9df0-11ea-8c49-dffda1e2b138.png)

I can't do all the files I have by hand, as they are produced automatically and saved to a network folder, where they are then automatically processed by my scripts.

**Comment by shawty** [comment]
Update, I've downloaded the sources and built my own version, which I've added a small hack to.

Adding it here in case it's useful to anyone else.

Download a zip of the sources, load it into Visual Studio, and in the file "SubtitleEdit->Forms->Ocr->VobSubOcr.cs"

add the following lines, after line 594:

![image](https://user-images.githubusercontent.com/1876454/82762729-99722180-9dfa-11ea-8c91-af5be2cd5f45.png)

Once this is done, change your build from Debug to Release, build the solution, then copy the contents of the bin/release folder over the top of your existing installation, making sure you DON'T overwrite your settings.xml

This enables the custom colour settings by default, and makes for better decoding of sub files produced by projectx.

**Comment by niksedk** [comment]
@shawty: What are you trying to do? 

SE can also read Transport Streams (not added to cmd line yet).
If you're going for ts -> mkv then try to convert to blu-ray sup via Tools -> Batch convert... and use the .sup files directly as images.

**Comment by shawty** [comment]
@niksedk 

"SE can also read Transport Streams (not added to cmd line yet)."

Yep I found that out, quite by accident... was quite pleased :-)

"What are you trying to do?"

As I explained above, I have 2 TV sets that have connections to a network file system. (Ok, I didn't explain that bit... but they are)

These TV's when they "Record" a TV show, automatically trigger a set of automation scripts.

These automation scripts, perform several steps.

1) An advert detection tool, scans the TS file looking for markers, when these markers are found the positions are recorded as cut points

2) The application "ProjectX" is then told to load the transport stream and these cut points, and create a folder of "demuxed" streams minus the cut parts, typically these parts will have an m2v, mp2 and a "sub" format bitmap based subtitles file.

3) The sub file is passed to subtitle edit using the command line in my first post above ^^^^ for conversion to an SRT file using OCR

4) The m2v & mp2 files are passed to ffmpeg and combined back together

5) The newly created MP4 file and the SRT file are copied to an output folder ready to be used by a web interface for playback.

This entire process is automated using batch scripts, shell scripts and a sprinkling of C#, and it largley all works perfectly, except for one problem.

Subtitle edit fails to OCR the subtitle files correctly, unless I enable custom colours, turn off all transparency settings and set the dictionary to GB. (Again as shown in the dialog shots in my post above ^^^^)

What I wanted to know originally was "is there a way to make the settings change using the command line?" to which I was told no by @xylographe 

I can't use the batch mode or anything like that, I have to do this from the command line because it's an automatic process, there is (Or at least once it's fully finished) no manual access in the process at all.

Since there was no option to change the subtitle OCR settings I needed from the command line, I solved the problem another way.  BY making a small change to the main exe and building my own custom version.

**Comment by niksedk** [comment]
@shawty: Nice you got it working :)
I seem to remember that the colors from sub/idx files (that's what ProjectX generates, right?) are actually in the idx file (that ProjectX perhaps generates buggy?). So, perhaps you can just delete the .idx files? Idx files also contains timestamps, but normally the same timestamps are inside the .sub file.

**Comment by niksedk** [comment]
@shawty: OK, latest version should now uses custom colors, if no .idx file is found - try from src or https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

**Comment by shawty** [comment]
I'll give it a try today @niksedk :-)

I honestly couldn't tell you what or how ProjectX stores the colors for the subtitles, but I do know it has quite a few "different settings" which your supposed to set for the program your processing.

Here in the UK the "UK Freeview" standards folks set the colours as a standard set of colours that all broadcasters transmitting over a TS stream broadcast medium, must follow.

If you look at the screen shot above (The ProjectX dialog) you'll see I have my settings set to that option.  I really don't know how PX stores the info, all I know is I get a "<program name>.sup.sub" file produced, that when loaded into Subtitle edit and the settings changed to the above, the OCR works pretty much perfectly.  I do believe a "<programname>.sup.idx" file is produced too, but I really couldn't tell you what's in it, I've had no reason to look, trying to find ANY documentation for ProjectX that's written in english is an almost impossible task :-)

I can set options like 16 colours and even 256 colours in ProjectX but SE seems to really struggle with them, it took me a lot of experimenting and playing about to get the best combination of settings that worked well :-)

I'm just on making some tweaks to my script and such like at the moment, I'll test that zip above later on, once I've tested my changes in the script, and let you know how well it works.
