### ISSUE TITLE
Waveform position problem

### ISSUE THREAD

**Issue by madnesofjuice** [SubtitleEdit/subtitleedit#4199]
Hello! I have a problem with SE. So, waveform position is not moving when im playing video. I have checked the "set video position when start/end" in waveform tab. Im using SE beta. Ive tried with SE 3.5.15/14/13. 
https://i.imgur.com/jtWJfgu.png

**Comment by niksedk** [comment]
What video player are you using? How does "mpv" work for you?
(see Options -> Settings -> Video player)

**Comment by madnesofjuice** [comment]
same thing. I just tried mpv and its the same thing, It doesnt change the line when im playing the video

**Comment by niksedk** [comment]
OK, could be some weird video format that does not allow seeking - could you upload the video somewhere?
Does converting the video to mkv/mp4 with Handbrake make it work?

**Comment by madnesofjuice** [comment]
Here is the media info. Before reinstalling the windows it was working with the same videos. they have all the same codec. This is h264, I tried with x265 as well.
Maybe is because of the settings: https://i.imgur.com/E2YoyeB.png ; https://i.imgur.com/vXUi1Xb.png ; https://i.imgur.com/2ZA2Pau.png

**Comment by madnesofjuice** [comment]
Please close it im a fucking retarded blind. I didnt saw the "select current subtitle while playing". Im sorry for your losted time. My apologies.

**Comment by niksedk** [comment]
lol, np :)
