### ISSUE TITLE
Use Deepl properly for Auto-Translate

### ISSUE THREAD

**Issue by MaximPro** [SubtitleEdit/subtitleedit#4201]
Hi Nik,

Hope you are doing well in this times ;)
Thanks again for developing this essential Tool for Translation.
I want to use Deepl translation, but I couldn't get it working 

Maybe you could add it properly, just like Auto-Translate with Google?
This would be probably one of the best new features:

![Auto-Translate with Deepl-26-05-_2020_19-59-29](https://user-images.githubusercontent.com/20738357/82934761-8aff4380-9f7b-11ea-9f2b-ea5e06e62fdd.jpg)

Maybe we even need to add an API from Deepl. But it would certainly worth it.

Maybe you could implement this or use parts of this code:
https://github.com/MatejMecka/captionsTranslator

Please implement this, because it would be a huge time saver!!
Deepl Translation is far superiour to all others and could translate the subtitles much more accurate.

Thanks and best wishes from germany

**Comment by OmrSi** [comment]
Plugins:
![image](https://user-images.githubusercontent.com/20923700/82936104-c0655a80-9f96-11ea-92a3-3ae70b91b6e3.png)

**Comment by niksedk** [comment]
I tried to look at Deepl... but I must admit that their support sucks and I don't think that they are interested any integrations.

**Comment by OgnistyPoland** [comment]
Can you fix DeepL plugin? https://i.imgur.com/gqs0daI.png
