### ISSUE TITLE
Error when downloading dictionary

### ISSUE THREAD

**Issue by bluesea1401** [SubtitleEdit/subtitleedit#4203]
Getting error when downloading dictionaries. See screenshot of error.
Extremely useful software. Much appreciation to the SubtitleEdit team!

![Screen Shot 2020-05-26 at 12 46 03 PM](https://user-images.githubusercontent.com/65978615/82944201-a05e7880-9f4f-11ea-8abf-c80ac7b318a0.png)

**Comment by niksedk** [comment]
OK, what dictionary do you have problems with?

**Comment by niksedk** [comment]
OK, I think that libre office changed all their links.

**Comment by bluesea1401** [comment]
Problem Dictionaries: Spanish, French, Portuguese - many others
Some Dictionaries are Working: Afrikaans is working for example

**Comment by bluesea1401** [comment]
Link change would explain the issue. Is possible with fix on my end, or will fix require a new version of SE?

Much appreciated!

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip ?

**Comment by bluesea1401** [comment]
Beta version, which you provided, does download dictionaries. Problem resolved. Much appreciated!

**Comment by niksedk** [comment]
I think this might speed up the release of next version... will leave this open for a while so this issue will be more visible.

**Comment by ReeferMadness** [comment]
> How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip ?

**Comment by dmerces** [comment]
> How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip ?

Fix Libreoffice Portuguese BR. Thanks

**Comment by ReeferMadness** [comment]
[quote]How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip ?[/quote]
I tested this version, French dictionary is right but I have problems on the first 3 lines ...

**Comment by ReeferMadness** [comment]
![SubtitleEdit 3 5 15 b240 - 01](https://user-images.githubusercontent.com/66226948/84172847-c2421a00-aa7c-11ea-8c80-afb21b3d753e.jpg)

**Comment by ReeferMadness** [comment]
![SubtitleEdit 3 5 15 b240 - 02](https://user-images.githubusercontent.com/66226948/84172879-cc641880-aa7c-11ea-9942-b975497dbb04.jpg)

**Comment by ReeferMadness** [comment]
I re-installed SubtitleEdit 3.5.15 NEXT b180 : all is right !
