### ISSUE TITLE
Larger text size in windows

### ISSUE THREAD

**Issue by Monovox** [SubtitleEdit/subtitleedit#4207]
I've been using SE almost daily for years now and I love it. I can't imagine my life without it, seriously.
I have a few observations and suggestions I'd like to share, maybe you'll find some interesting. To keep things tidy I'll post them as separate topics.

![ver 3 5 15](https://user-images.githubusercontent.com/66067219/83138101-96bd4800-a0ea-11ea-908f-3de492b69a9e.jpg)

There was a known problem (#2434) with char size within boxes in the interface when using lager text in windows display options (125% in my case). This was fixed, but the size of some panels or boxes was reduced, resulting in too little space or truncated sentences. The type is much sharper now, but using bolder type may improve readability. 
Thank you

**Comment by niksedk** [comment]
Thx for not putting everything in one issue :)

I've fixed the buttons in the waveform settings (also in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip )

Generally "Window Forms" has poor support for high DPI.

You might already know, but the text box font can be set separately - I normally use a large and bold font.

**Comment by Monovox** [comment]
Thanks for your response.
Yes, I change the font in the list and box, and this is what important really. The font in the buttons is a little smaller in the last version, but it is sharp and fits inside which is great, especially for the digits.
