### ISSUE TITLE
Dragging MKVs with only subtitle tracks into Batch convert is very slow

### ISSUE THREAD

**Issue by lambdan** [SubtitleEdit/subtitleedit#4211]
If I drag in MKV files that contain video, audio and subtitle tracks into the batch convert window they pop up instantly. Great.

If I drag in MKV files that *only* contain subtitle tracks into the batch convert window, it takes a very long time for them to pop up and the program locks up. Eventually they show up and it works.

I've made a video demonstration here: https://www.youtube.com/watch?v=_GG-efOz-CE

I use ffmpeg to create MKVs that only contain subtitle tracks: `ffmpeg -i input.mkv -map 0:s -c:s copy output.mkv`

Attached zip file contains the mkv files that only contains subtitles that I made in the video demonstration.

[Subs_only.zip](https://github.com/SubtitleEdit/subtitleedit/files/4706503/Subs_only.zip)

**Comment by niksedk** [comment]
Thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip
