### ISSUE TITLE
Subtitles (from a template in translation mode) missing in video and waveform

### ISSUE THREAD

**Issue by evayor** [SubtitleEdit/subtitleedit#4212]
When I upload an English template file in translation mode to translate it in Bulgarian, I can't see the subs in the video or in the waveform.
![image](https://user-images.githubusercontent.com/57219975/83732307-865e1d80-a654-11ea-8e30-0a1fd19f802e.png)

This is true when I try to work only on the translated text. As you can see, it's an HBO movie I was sent in an avi format. Converted it to mp4, but it's still the same.

However, when I start creating subtitles from scratch, they appear as usual.
![image](https://user-images.githubusercontent.com/57219975/83732596-f66ca380-a654-11ea-8aac-e0cdd8f87518.png)

I need this fixed asap because the film is part of a test I'm doing to take on more work for HBO. However, if it turns out I can't work with their templates (because obviously the video is fine), I might lose the contract or will have to switch to another software which I'd hate.

**Comment by darnn** [comment]
Use video->set video offset. You can adjust the timecode so that it matches the timecode embedded in the video. As you can see, the subtitles' timecodes actually match it: they all start one hour in, instead of at 00:00:00.

**Comment by evayor** [comment]
Thank you so much, I completely ignored the timing and looked at everything else. It worked and I've fixed it.
