### ISSUE TITLE
Cloud Speech-To-Text API

### ISSUE THREAD

**Issue by MehdiZouaoui** [SubtitleEdit/subtitleedit#4220]
Hello everyone,

 I wonder if it is possible that we have the ability to add Cloud Speech-To-Text API key to Subtitle Edit. There is only Google Translate API which is paid service. Speech to Text will save the time of a lot of people because once they have the script in text they can directly translate it using normal Google Translate and just polish the translation. I downloaded a Json file from my Google Cloud console and but I have no idea what to do with it.

Thank you again and sorry if I'm writing that in the wrong place.

**Comment by patui** [comment]
i like the idea。

**Comment by Dnkhatri** [comment]
Would be use full inside subtitle edit. Currently I use 
https://github.com/raryelcostasouza/pyTranscriber

**Comment by Elheym** [comment]
I agree, it is nice idea.
"pyTranscriber" awesome program.

**Comment by patui** [comment]
you can try this app [https://github.com/patui/Nosub](url)

**Comment by MehdiZouaoui** [comment]
> Would be use full inside subtitle edit. Currently I use
> https://github.com/raryelcostasouza/pyTranscriber

Thank you. I'm trying it now and see how things will go

**Comment by MehdiZouaoui** [comment]
> you can try this app [https://github.com/patui/Nosub](url)

Thank you but the link doesn't seem to be working :/

**Comment by patui** [comment]
> > you can try this app [https://github.com/patui/Nosub](url)
> 
> Thank you but the link doesn't seem to be working :/

copy site link，paste browse direct。

**Comment by Jabe64** [comment]
You will probably be interested in the new Beta features see [#1878](https://github.com/SubtitleEdit/subtitleedit/issues/1878)
