### ISSUE TITLE
Networking and privacy

### ISSUE THREAD

**Issue by davidefer** [SubtitleEdit/subtitleedit#4224]
Hi
I have a question concerning networking: are the texts sent to your server?
I'm asking because of privacy issues with our project.
Thank you in advance.

**Comment by niksedk** [comment]
The texts are send to the server - where they are stored in memory.

You can setup your own service on Azure (or somewhere else) - get the source code here: https://nikse.dk/SubtitleEdit/Help#networking
I did that a few years back (and it's still running).

**Comment by davidefer** [comment]
Thank you Nikolaj
I've done some tests and as far as I've understood, the networking feature is really limited to concurrent sessions. It is not working when people modify the texts by their own. The modifications cannot be merged when they both join the same session later.
Anyway, very cool tool, thank you!
