### ISSUE TITLE
[Bug] Merging text changes comma

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#4225]
Hey, I have just noticed this.
I had two lines:
```
1
00:00:01,000 --> 00:00:02,053
يا فتيات، لديكن 5 دقائق

2
00:00:02,136 --> 00:00:03,000
لإنهاء كل التفاصيل.
```
And when I use and type of Merge, the Arabic comma is changed to an English one:
```
يا فتيات, لديكن 5 دقائق
لإنهاء كل التفاصيل.
```

**Comment by niksedk** [comment]
Hm, it does not do that here... how do you merge?

**Comment by OmrSi** [comment]
Well, I've been testing with the settings file for 40 minutes.
I got the cause, it happens when you have: `<ContinuationStyle>NoneTrailingDots</ContinuationStyle>`

**Comment by OmrSi** [comment]
It seems like it's not doing `ConvertBackForArabic` but only `ConvertToForArabic`.

**Comment by Flitskikker** [comment]
Thanks @niksedk for the swift fix!

**Comment by OmrSi** [comment]
@niksedk This is also causing original English text to be changed to Arabic punctations.
Before split:
![image](https://user-images.githubusercontent.com/20923700/89210002-0149a300-d5c8-11ea-8c38-b6a8bfc47303.png)

After spilt:
![image](https://user-images.githubusercontent.com/20923700/89209998-ff7fdf80-d5c7-11ea-8c6d-63b9e7774832.png)

The same happens with commas.
