### ISSUE TITLE
Combine subtitle files

### ISSUE THREAD

**Issue by davidefer** [SubtitleEdit/subtitleedit#4226]
Hi
I wanted to find a way so that different editors (people) can edit different parts of the subtitles of a video, without having to implement an online service managing concurrent sessions (no skills, no time).

I have though about splitting the subtitles in three files, let's say first half hour, second half hour, third half hour. This can already be done by selecting all the subtitles of each part and with right click save them in a different file. In this way, each editor can work independently on each part (and when they want).

Now we come to the final step: how to merge back the three edited parts in a single subtitle file? I couldn't find a way to do it in SE.
P.S. is there a way to jump to a bookmark?

Thank you in advance.

**Comment by niksedk** [comment]
Hi @davidefer,

Use Tools -> Split ->Advanced to split easily:
![image](https://user-images.githubusercontent.com/1261331/83974775-1c61a480-a8f0-11ea-9ae9-7c6bdd872b63.png)

And Tools -> Join to join:
![image](https://user-images.githubusercontent.com/1261331/83974788-2daab100-a8f0-11ea-874b-78e685084af9.png)


Check the bookmark shortcuts:
![image](https://user-images.githubusercontent.com/1261331/83974849-8c702a80-a8f0-11ea-8721-49cabc1c084b.png)

**Comment by davidefer** [comment]
Thanx a lot!! Perhaps you could document this in the online help.
This tool is kind of magic.
