### ISSUE TITLE
I want to see 3.02, 4.10, 5 alpha options on OCR page

### ISSUE THREAD

**Issue by ismail0100** [SubtitleEdit/subtitleedit#4228]
Hi  you can see below on picture there is only two options. But tesseract 3 and 5 not working correctly. I want to add v4. I copied files on roaming but not added here. How can  do? Sorry for bad english.

![Ekran Görüntüsü (10)](https://user-images.githubusercontent.com/16451393/83977878-4d4fd280-a90c-11ea-9ce4-201d04a1a498.png)

**Comment by niksedk** [comment]
Sorry, no Tesseract 4 as it's buggy: https://github.com/SubtitleEdit/subtitleedit/issues/3933

OCR works best with white text, so you might need some image pre-processing (right click in list vie for context menu).

You could also try latest beta and "nOCR" and see how that works.

**Comment by ismail0100** [comment]
Thank you for answering. I get this error very much "... returned error code 1".
Why v4 remove I understand now. Love this program thank you for your efforts and works.
