### ISSUE TITLE
Disable native video player subtitles

### ISSUE THREAD

**Issue by larvanitis** [SubtitleEdit/subtitleedit#423]
Hi.

When I open a video in SE the embedded player (`mplayer` in my instance) automatically opens and displays the subtitles - usually in an incorrect encoding. This is uneccessary because we already have the SE overlayed subs.

Please add `-nosub` (disables auto-selected embedded subtitles) and `-noautosub` (disables external file subtitles) in mplayer argumets found in `src/Logic/VideoPlayers/MPlayer.cs` > `_mplayer.StartInfo.Arguments`.

[src/Logic/VideoPlayers/MPlayer.cs#L143-L145](https://github.com/SubtitleEdit/subtitleedit/blob/3.4.5/src/Logic/VideoPlayers/MPlayer.cs#L143-L145)

**Comment by larvanitis** [comment]
On the patch you missed the last character in -noautosu**b**. Thanks for the quick response!

**Comment by niksedk** [comment]
Yeah, thx - should be fixed now via https://github.com/SubtitleEdit/subtitleedit/commit/91c0e18f6e3792508501543a4528174e58b7ea06
