### ISSUE TITLE
[Feature request] MPC-HC location

### ISSUE THREAD

**Issue by 514guy** [SubtitleEdit/subtitleedit#4231]
I noticed that in "Video player">Video engine, in Options>Settings, Subtitle Edit has a portable location field for VLC, but not for MPC-HC. It seems like even the VLC option, itself, can't be selected, as it's greyed out, as is MPC-HC. Could this be implemented, please?

**Comment by OmrSi** [comment]
@niksedk Is `    <MpcHcLocation />` in the settings file for this?

**Comment by 514guy** [comment]
@OmrSi It seems to be, but trying to use it, causes SubtitleEdit  to not even load the settings file. I tried filling in the portable location, and following it with </MpcHcLocation>.

**Comment by xylographe** [comment]
The file name must be
`mpc-hc64.exe` or `mpc-hc64_nvo.exe` (in 64-bit mode), or
`mpc-hc.exe` or `mpc-hc_nvo.exe` (in 32-bit mode).

The setting must be a full path, e.g.
**`<MpcHcLocation>D:\Tools\Mpc\mpc-hc64.exe</MpcHcLocation>`**

**Comment by adem0x** [comment]
I have never used this feature, as a result, I might be way off base.

AFAIK, MPC-HC is not maintained anymore.

I use MPC-BE which is updated quite frequently.

See: https://yadi.sk/d/hlf1lfC8mKU58

So, wouldn't it be more universal if SubtitleEdit also allowed for MPC-BE for those of us that use it.

i.e. e.g.

`<MpcHcLocation>C:\ProgramData\MPC-BE x64\mpc-be64.exe</MpcHcLocation>`

**Comment by niksedk** [comment]
MPC-HC is still being maintained here: https://github.com/clsid2/mpc-hc/releases

MPC does not really have an API like mpv or vlc... would be cool if it did though!
SE actually starts MPC, hides it, and then hi-jacks the video window - it's amazing it's working at all!

So, use the `MpcHcLocation` as OmrSi and xylographe  wrote.

**Comment by xylographe** [comment]
Start `cmd.exe` (for example via **`Win+R`**), and run these commands:
```
pushd "C:\ProgramData\MPC-BE x64"
mklink /H "mpc-hc64.exe" "mpc-be64.exe"
dir
```
