### ISSUE TITLE
frames visibility/grid in settings and waveform

### ISSUE THREAD

**Issue by evayor** [SubtitleEdit/subtitleedit#4233]
My new studio requires me to fix subs timing in respect of frames, not milliseconds. 

First, I need to set a min. gap between subtitles of 2 frames which, according to my calculations for 25 fps, is 80 ms. Is that right?

However, I also need to pay attention to frame gap between subs which is difficult when in the waveform grid there are only milliseconds. 

Is it possible to include a setting to switch it to frames? If not, could you suggest a way to handle that?

**Comment by OmrSi** [comment]
In the latest beta, SE can calculate that inside SE:
![image](https://user-images.githubusercontent.com/20923700/84033143-14157200-a9a1-11ea-9504-0dedbaaa61f9.png)

**Comment by evayor** [comment]
Thank you, I'll have it in mind. I'm not using it at the moment because I haven't found a way to export all my settings from SE 3.5.15 to Beta which is only portable so far.

But the other possibility to have a frame grid would be very useful because I need whether I ve 10 frames difference or less and then decide how to extend the previous sub.

**Comment by OmrSi** [comment]
I think you can do that with "Edit -> Bridge gaps between subtitles"
![image](https://user-images.githubusercontent.com/20923700/84039444-ea147d80-a9a9-11ea-8adc-5627a0a1afdd.png)

No need to check manually.

**Comment by evayor** [comment]
Yeah, I tried that,. However, I'd like to do it in real time, not post factum, but certainly it's an option.
Thanks again.

**Comment by niksedk** [comment]
Also, in Options -> Settings you can set `time code mode` to frames.
And in the list view column, you can right-click, and show `Gap`.

Will look like this:
![image](https://user-images.githubusercontent.com/1261331/84040234-a9653600-a9a2-11ea-9738-6aaf71e06858.png)

Plus check Tools -> Apply min gap between subtitles:
![image](https://user-images.githubusercontent.com/1261331/84040457-f2b58580-a9a2-11ea-95bc-d7bbc132d58f.png)

And further more, you can use "F8" which is "Go to next error" in main window (after setting 80 ms as min gap in settings).

**Comment by evayor** [comment]
Thank you @niksedk , I added the gap column and it will be helpful. 

However, I don't understand the value in the gap column. Does 0:02 stand for two frames? Because for other gaps in this mode I get 01:01, for example, and it doesn't mean anything to me.

**Comment by OmrSi** [comment]
0:02 means 2 frames, 1:01 means 25+1 if the framerate is 25, and so on...

**Comment by OmrSi** [comment]
And by the way, you can just take the `.exe` from the beta and replace the original `.exe` or take your `Settings.xml` file and put it in the beta folder.
`Settings.xml` holds all the settings, you can find it here: %appdata%/SubtitleEdit/%

But of course, there are also the support-files like extra of edited dictionaries and FFmpeg and MPV which you would need to copy to the beta folder too.

**Comment by OmrSi** [comment]
> The rule I need to follow is: if there are less than 10 frames between 2 subtitles, extend the first one to the next with a 2-frame gap, i.e. reduce every less than 10-frame gap to 2 frames.
@evayor when you see 0:10 on a line, use the extend shortcut, it will extend the current line's end to the next's start leaving the min. gap which is 2 frames.

And as you know, you can use Bridge gap by setting gaps smaller than 400 to 80.
