### ISSUE TITLE
[Bug] New extend to previous shortcuts don't affect original

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#4234]
The shortcuts which were merged here https://github.com/SubtitleEdit/subtitleedit/commit/309610357101c6fd9912bdbd8623a8fa5224f1e7
```
Extend selected lines to previous scene change (or previous subtitle)
Extend selected lines to previous subtitle
```
Don't affect the original subtitle **if the previous subtitle is +1 sec away**:
![image](https://user-images.githubusercontent.com/20923700/84079985-206eee80-a9e4-11ea-90fa-a34bbb6ff0f6.png)

**Comment by OmrSi** [comment]
I did some testing with the code, just for fun, and it seems like
`var original = Utilities.GetOriginalParagraph(idx, p, _subtitleAlternate.Paragraphs);`
is returning as `null` when the subtitle is +1 sec away:
![image](https://user-images.githubusercontent.com/20923700/84179598-e0187a80-aa8e-11ea-8291-1d6d85da4f9f.png)

And working fine when it's closer:
![image](https://user-images.githubusercontent.com/20923700/84179667-f7effe80-aa8e-11ea-86ef-530cda6b154f.png)

I don't know if it's even related, just wanted to test. ^^"

**Comment by OmrSi** [comment]
Also, doesn't line 14975 need `&& Configuration.Settings.General.AllowEditOfOriginalSubtitle` like line 14934?

**Comment by OmrSi** [comment]
I compared the process of two cases, one with +1 sec as a gap and one with less than 1.
It seems like `!p.StartTime.IsMaxTime` in `Utilities.GetOriginalParagraph` isn't met when the gap is more than 1 second so it returns `null`

**Comment by OmrSi** [comment]
It seems that `p.StartTime.TotalMilliseconds < paragraph.StartTime.TotalMilliseconds + TimeCode.BaseUnit` in `Utilities.GetOriginalParagraph` is the condition which is not met.

**Comment by OmrSi** [comment]
@niksedk Do you think this is a viable solution? https://github.com/OmrSi/subtitleedit/commit/2b4b6818abe15ed1c713300d27a12e2b2f2355ca

I changed the order of the conditions so that it would change the timing of the original first because the issue, as far as I could tell, was that `p.StartTime.TotalMilliseconds < paragraph.StartTime.TotalMilliseconds + TimeCode.BaseUnit` in `Utilities.GetOriginalParagraph` isn't working well when the `startTime` of the main is changed before the original and had more than 1-sec difference.
It worked with my tests but I don't know if it has any bad effects.

**Comment by niksedk** [comment]
Looks good to me :)

Will you make a PR?
