### ISSUE TITLE
[Feature request] In auto translation, to perceive the lines as a whole.

### ISSUE THREAD

**Issue by xmrea** [SubtitleEdit/subtitleedit#4238]
### In auto translation, to perceive the lines as a whole.

I don't know if it's feasible. I don't think it would be easy.

**English**

> ```
> 00:00:08,400 --> 00:00:09,900
> I love Yuki.
> 
> 00:00:11,150 --> 00:00:16,730
> I love his hair that gleams silver when
> the sunlight passes through it, his fair skin...
> 
> 00:00:17,370 --> 00:00:20,080
> I love his eyelashes that cast shadows
> on his cheeks when he closes them,
> 
> 00:00:21,000 --> 00:00:23,080
> his dignified, penetrating voice...
> 
> 00:00:24,210 --> 00:00:27,670
> Everything about Yuki is everything to me.
> ```

**Turkish** (Google Translate) 

>**### Accuracy rate : 70%**
> ```
> 00:00:08,400 --> 00:00:09,900
> Yuki'yi seviyorum.
> 
> 00:00:11,150 --> 00:00:16,730
> Ne zaman gümüş parıldayan saçlarını seviyorum
> güneş ışığı içinden geçer, açık tenidir...
> 
> 00:00:17,370 --> 00:00:20,080
> Gölgeleyen kirpiklerini seviyorum
> onları kapattığında yanaklarında,
> 
> 00:00:21,000 --> 00:00:23,080
> ağırbaşlı, delici sesi...
> 
> 00:00:24,210 --> 00:00:27,670
> Yuki ile ilgili her şey, benim için her şey.
> ```

**When I translate the above subtitle as plain text with google translate it gives more successful results.**

Plain text settings are like this...

![Screenshot_4](https://user-images.githubusercontent.com/46967762/84282396-5fb35180-ab42-11ea-8a3c-67f6bfa3a865.png)

In that...

**English**

> `I love Yuki. I love his hair that gleams silver when the sunlight passes through it, his fair skin... I love his eyelashes that cast shadows on his cheeks when he closes them, his dignified, penetrating voice... Everything about Yuki is everything to me.`

**Turkish** (Google Translate) 

> **### Accuracy rate : 95%**
> 
> `Yuki'yi seviyorum. Güneş ışığı içinden geçtiğinde gümüş parıldayan saçlarını, açık tenini seviyorum... Onları kapattığında yanaklarına gölge düşüren kirpiklerini, onurlu, delici sesini seviyorum... Yuki ile ilgili her şey, benim için her şey .`

**The accuracy rate is 70% in subrip format, while it is 95% in plain text.**
<hr>

### But when I translated it as plain text, I couldn't find any way to restore subtitle timing and formatting.

So I want to ask if a feature that can do this in the future will come.

Also, is there any way I can do this?

Thanks!!

**Comment by xmrea** [comment]
### I have an idea like this.

I'm not just saying this for auto-translation. 
Also, extracting subtitles as plain text... And import plain text with timing and formatting.

**The main component of this idea: Colors**

I looked for a format in subtitleedit, where times and texts were handled separately.
Json type7 format is best suited for this ...

Timing and texts are grouped separately in Json type7 format.

```
{"start": [8400,11150,17370,21000,24210,28970,33010,36510,45480,51400],

{"end": [9900,16730,20080,23080,27670,29960,34880,40680,50550,53150],

"text": ["I love Yuki.","I love his hair that gleams silver when the sunlight passes through it, his fair skin...","I love his eyelashes that cast shadows on his cheeks when he closes them,","his dignified, penetrating voice...","Everything about Yuki is everything to me.","But...","...<i>she</i> came out of nowhere,","started interfering, and messed everything up!","I won't let other women come and do as they please with Yuki any longer.","Absolutely not."]}
```

**We specify a color for each start-end time and the line corresponding to this time.**

Example:
![1](https://user-images.githubusercontent.com/46967762/84382474-5635f200-abf3-11ea-9a17-105af1655a7f.png)

Then, we convert the lines to plain text and extract them in html format (keeping the colors).

It should look like this ...
![2](https://user-images.githubusercontent.com/46967762/84380356-dfe3c080-abef-11ea-9276-2d616cfc0cc2.png)

Html Code...
`<p><span style="color: #99cc00;">I love Yuki.</span> <span style="color: #ff0000;">I love his hair that gleams silver when the sunlight passes through it, his fair skin...</span><span style="color: #00ffff;">I love his eyelashes that cast shadows on his cheeks when he closes them,</span></p>`

When importing;
We write the timecode and text of the same color, one under the other.

![3](https://user-images.githubusercontent.com/46967762/84381192-559c5c00-abf1-11ea-9c32-f8026312a329.png)

-------

**Let's come to automatic translation...**

**Google web site translator;**
Keeps the colors while translating colored text. 
![4](https://user-images.githubusercontent.com/46967762/84382314-1d961880-abf3-11ea-8588-8a6aeb05d5aa.png)

The matching text is automatically shifted. Words of other colors may enter between them.

**So, to convert it to lines, a strong algorithm is required.**

-------

### As a result, an plug-in is required to detect and combine timing and text by color.

**Comment by OmrSi** [comment]
Why are you complicating things?
He told you SE unbreaks continuous lines and translates them as a chunk which is all that matters. 
He also gave you a link to test.

**Comment by xmrea** [comment]
I just stated my opinion.

![Screenshot_1](https://user-images.githubusercontent.com/46967762/84384307-731ff480-abf6-11ea-92e2-8e10e01b2cd6.png)

Subtitleedit is an excellent software.

**Comment by OmrSi** [comment]
Yes, you did. 
And no one is saying there is something wrong with that. 
But he told you that SE does unbreak continuous lines and translates them as one sentence and gave you a link to test it out. 
So, if it already does translate lines like you want, what's the need for another way?

**Comment by xmrea** [comment]
If you look at my previous post... It wasn't just an auto-translation suggestion.

> I'm not just saying this for auto-translation.
Also, extracting subtitles as plain text... And import plain text with timing and formatting.

**Comment by xmrea** [comment]
> SE already does unbreak of single subtitles... for some source languages.
> 
> I've tried to add more languages + SE will now merge two subtitles where first sub ends with letter or comma and next sub starts with a lowercase letter.
> I've not tested much... but how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip
> 
> Source languages that will unbreak:
> 
> ```
>  "en", "da", "nl", "de", "sv", "nb", "fr", "it", "tr", "es", "pt", "sr", "ru", "lv", "lt", "et", "ro", "pl", "ar", "he", "no"
> ```

Thanks. More successful than before.
