### ISSUE TITLE
Wave form error

### ISSUE THREAD

**Issue by phyo123-art** [SubtitleEdit/subtitleedit#4240]
How to fix this error? I am using Subtitle edit 3.5.15 on windows 8.1 pro.
[
![image](https://user-images.githubusercontent.com/64297041/84474508-cec2a000-ac3f-11ea-9c24-50318af7e6bc.png)
](url)

**Comment by niksedk** [comment]
I don't know... is it English text or ?

Looks like a "Windows error"...
