### ISSUE TITLE
The problem is with EBU STL export in standard code for teletext

### ISSUE THREAD

**Issue by jaroslavr** [SubtitleEdit/subtitleedit#4242]
I started working with your Subtitle Editor and it is really great,
But I just have a small problem.

The problem is with EBU STL export in standard code for teletext.
In your  Subtitle Editor it looks like there is no error.

But… I have a very simple browser application for checking the correctness of teletext subtitles and there is one problem. 
If the title is two-line, one blank line is always created between them.

The error does not appear when exporting in standard code open titles, but then the subtitle color information is lost.

Is there any option in the settings for EBU STL export for teletext titles
unless it is an export error? Could you please advise me?

Thank you in advance.
Have a nice day

V.

[problem EBU STL teletext.docx](https://github.com/SubtitleEdit/subtitleedit/files/4771918/problem.EBU.STL.teletext.docx)

**Comment by niksedk** [comment]
Try File -> EBU STL properties...

![image](https://user-images.githubusercontent.com/1261331/84528906-d7b77e00-ace0-11ea-9a4b-5cd43f60c716.png)
