### ISSUE TITLE
typing and keyboard shortcuts stop working in text box and list view

### ISSUE THREAD

**Issue by evayor** [SubtitleEdit/subtitleedit#4243]
It started happening more and more often in the last weeks:
all of a sudden I can't type any more in the text box, shortcuts don't work and I can only start and stop the video clicking in the video window.
I need to restart the program and then everything is fine again.

However, after opening the already created file, some of the timings appear in red, as if overriding the given settings, and then I need to go back and fix them again.

**Comment by niksedk** [comment]
Do you have any idea of how to re-create this?

**Comment by evayor** [comment]
I'm not sure what you mean. Do you want me to make screenshots? Because there's not really much to be seen. The typing simply freezes.

**Comment by niksedk** [comment]
What version are you using? 
What video player are you using?
And most important - what do yo do to make the program freeze?

**Comment by evayor** [comment]
Sorry about the missing info:
SE 3.5.15
DirectShow
It usually happens after I make a short break. But there have been a couple of occasions when it happens in the middle of translation, without any obvious reason.

**Comment by niksedk** [comment]
Could you try using "mpv lib" as video player for a while?

**Comment by niksedk** [comment]
One of the SE versions has a problem with the Win-key... makes SE freeze, but I cannot remember the version...

**Comment by evayor** [comment]
OK, I'll try with mpv, but I've been using this last version since it was released and this problem only started several weeks ago.

**Comment by evayor** [comment]
I'll send feedback tomorrow when I start working.

**Comment by niksedk** [comment]
Actually, the SE 3.5.15 public/final release this problem... 
It's fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

Well, I guess that this and the "Dictionary download problem" makes a new release soon very possible...

**Comment by OmrSi** [comment]
I think [this](https://github.com/SubtitleEdit/subtitleedit/issues/4213) is related to this.
