### ISSUE TITLE
[Feature Request] Improve framerate in waveform playback

### ISSUE THREAD

**Issue by fru1tstand** [SubtitleEdit/subtitleedit#4244]
Great product, been starting to use this. For my workflow, I seem to depend on the waveform view a lot for timing due to its ease of adjustments. I noticed that after a short duration of playback that the time cursor within the waveform screen jumps by half second intervals or more. I was wondering if it were possible to improve this (ie. make it more smooth) as the program doesn't otherwise seem to be particularly resource intensive.

**Comment by niksedk** [comment]
@fru1tstand: You're probably using vlc 3 as video player? vlc has very poor seeking/precision which causes jumps in the SE waveform. Vlc 4 should fix this...
Try using "lib mpv" as video player instead.

**Comment by fru1tstand** [comment]
Swapping to libmpv works -- thanks! Wondering if it's worthwhile to put a warning.
