### ISSUE TITLE
Gap between title in / out and shot change

### ISSUE THREAD

**Issue by mjlgit** [SubtitleEdit/subtitleedit#4246]
Hello.

I've added shot changes installing ffmpeg.
However, how can I measure the gap between the title and the shot change?

Netflix needs us to know this in [their requirements](https://partnerhelp.netflixstudios.com/hc/en-us/articles/215758617-Timed-Text-Style-Guide-General-Requirements)

**Comment by OmrSi** [comment]
As far as I know, there is no existing feature that does this.
You have to do it manually.

**Comment by mjlgit** [comment]
Thanks Omar

So the next thing was to display Subtitle Edit[ in Frames rather than milliseconds](https://nikse.dk/Home/Details/634906853880000000) but can't find that change in options/settings.

Any clues? Thanks

**Comment by OmrSi** [comment]
![image](https://user-images.githubusercontent.com/20923700/84576010-1ff69f00-adba-11ea-8fb2-91168793d410.png)

**Comment by mjlgit** [comment]
Thank you, now I can place the titles around the shot change according to the rules.
It's quite a challenge.

**Comment by OmrSi** [comment]
You got it.
And here is a small piece of advice, use a demo version of EZTitles to generate shot changes and import them in SE, it's way better that way, less false positives.

**Comment by OmrSi** [comment]
Also, 12 frames in 23.976 videos are half a second, so you can use the `500 ms` shortcuts.

**Comment by mjlgit** [comment]
Well I'm looking at EZTitles, demo version only takes 25 titles

**Comment by OmrSi** [comment]
Yes, but you can open the video with it and it will generate shot changes, export them and import in SE.

![image](https://user-images.githubusercontent.com/20923700/84602930-505e3c00-ae93-11ea-9129-aa31b1814af3.png)

**Comment by mjlgit** [comment]
Oh OK. Is that better than the ffmeg shot changes found in SE?

**Comment by OmrSi** [comment]
Much better from my experience.

**Comment by niksedk** [comment]
Use the new "Beautify time codes"
