### ISSUE TITLE
Regex changed? help.

### ISSUE THREAD

**Issue by Monovox** [SubtitleEdit/subtitleedit#4247]
Related #4209 
To my horror I just found out that my regular expressions don't work properly in all latest versions, after 3.5.10. Have the regex flavor changed? 
I mostly use <.*[A-Za-z0-9()$].*> (stars after the dots) to catch whole lines that contain digits, Latin chars or parentheses and may cause problems in RTL subtitles, and it worked fine. The greedy <+> also doesn't work anymore. Same case in the beta.
Help? Please?

**Comment by OmrSi** [comment]
How does `[A-Za-z0-9()$]` mean whole lines?
`[A-Za-z0-9()$]` means one char which is a letter `A-Z`, case insensitive, a number `0-9`, parentheses `()`, OR a dollar sign `$`.
`\A[A-Za-z0-9()]+\z` or `(?m)^[A-Za-z0-9()]+(?=\n|\z)` might be what you want.

And how doesn't `+` work?

**Comment by Monovox** [comment]
@ OmrSi
I just got a mild panic attack. something did change, but I fixed the expression' adding ^ and it works fine again. for some reason the page does't like the stars' so I added a pic.
![screenshot 172](https://user-images.githubusercontent.com/66067219/84580798-b20e9f80-adda-11ea-9d21-9b05490bd68f.jpg)

**Comment by OmrSi** [comment]
I tested on 3.5.10 and the result was the same.
Can you give an example of a line that matches in that version but not the current?

**Comment by Monovox** [comment]
Version 3.5.10 works fine with both expressions and also with the + quantifier.
Later versions work only with the lower expression (that's not a problem), and don't work well with + 
Try a simple expression like \d+ in version 3/5/10 or earlier and in later versions and you will see what I mean. for a string 123 it should return 123 and continue, but it returns 123 then 23 and then 3.
It's the same behavior and differences with the whole line expression without the ^, but for the + quantifier I didn't find a remedy.

**Comment by OmrSi** [comment]
I tried it with `[a-z]+` on `abcdefg` and both versions had the same result.
The first one is the whole thing, then a char from the beginning is excluded every time you press F3.

**Comment by Monovox** [comment]
Try it in 'replace'. I commented earlier that 'find' doesn't work that well with regex, I don't know why.
It should return abcdefg once.

"A+ | One or more As, as many as possible (greedy), giving up characters if the engine needs to backtrack (docile)"
