### ISSUE TITLE
Jump to top when change made in waveform (beta)

### ISSUE THREAD

**Issue by Monovox** [SubtitleEdit/subtitleedit#4248]
In 3.5.15/Beta, when making a change in the waveform while main window in source view, both source and list jump to start of file.

**Comment by OmrSi** [comment]
Don't close an issue and open it again, it's really pointless.
The developer sees everything and fixes what he can when he can.
If you had doubts about an issue you closed, you can reopen it. https://github.com/SubtitleEdit/subtitleedit/issues/4223

**Comment by Monovox** [comment]
@OmrSi Sorry, I'm new to this platform.
When should I close an issue?

**Comment by xylographe** [comment]
In most cases one would close an issue when the problem has been solved in **SubtitleEditBeta**.
