### ISSUE TITLE
Invalid network paths in <RecentFiles> causes hang on startup

### ISSUE THREAD

**Issue by beeeeswax** [SubtitleEdit/subtitleedit#4249]
This started happening a while ago but I've only just got round to busting out ProcessExplorer to figure it out.  Whenever I launch SubtitleEdit, nothing happens for a good 30 seconds, then it finally opens.

ProcessExplorer gave the game up almost immediately though - there were references to .srt files at an smb path for a server that was no longer on my network (it died).

Right where the large (31 seconds) pause is in ProcessExplorer is a reference to \\192.168.0.7\tv07\etc.srt which is valid, then the big pause, then a reference to C:\Windows\CSC\v2.0.6\namespace\192.168.0.6 after it. 

192.168.0.6 was the IP of the server which died so I opened C:\Users\me\AppData\Roaming\Subtitle Edit\Settings.xml and cleared out the whole -RecentFiles- section which contained several references to \\192.168.0.6\* and now SE opens instantly again.  Hopefully an easy fix.

*cough* batch .ts/teletext processing *cough*.  Oh, excuse me :)

**Comment by niksedk** [comment]
Better late than never...

Latest beta should now check if recent files exists in the background: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.17/SubtitleEditBeta.zip

Cmd/batch-convert ts teletext processing in SE rocks now ;)
