### ISSUE TITLE
[Feature Request] Alternative version of "point sync via other sub"

### ISSUE THREAD

**Issue by Leopard20** [SubtitleEdit/subtitleedit#4250]
Let's say I have a subtitle that is synced with a version of some TV show with commercials, and another subtitle synced with the same TV show without those commercials. The frame rate for both subs is the same.

If point sync worked the way it should, I could easily sync the subtitle by matching the lines that have fallen out of place due to the commercials. However, using more than one sync points changes the timing as well, which is not needed in this case.

If you could somehow incorporate this feature, it would be great.

**Comment by Monovox** [comment]
If both files have identical lines just another language, you can try doing that using "Import time codes..." under "file".
"Point sync" works differently.

**Comment by leopard20** [comment]
@Monovox Thanks for the reply. I'll check it out.

**Comment by leopard20** [comment]
I tried the "import time codes..." option too, but since the two subtitles had different number of lines, the syncing was broken.

**Comment by hani-yassine** [comment]
was going to post asking for this feature it will good to add sync point that change duration after the elected line that will solve it (basically jut add "elected line and forward option just like the only available in the normal adjust time)

**Comment by Dnkhatri** [comment]
> Let's say I have a subtitle that is synced with a version of some TV show with commercials, and another subtitle synced with the same TV show without those commercials. The frame rate for both subs is the same.
> 
> If point sync worked the way it should, I could easily sync the subtitle by matching the lines that have fallen out of place due to the commercials. However, using more than one sync points changes the timing as well, which is not needed in this case.
> 
> If you could somehow incorporate this feature, it would be great.

Try alass 
https://github.com/kaegi/alass 
Though I would prefer the algorithms used in allas to be imported into subtitle edit or maybe a plugin

**Comment by OmrSi** [comment]
@Dnkhatri Just hearing about ALASS from you.
I tested it but it got stuck in a loop repeating the same action, has that happened with you?
![image](https://user-images.githubusercontent.com/20923700/85900496-98bd1880-b808-11ea-8f94-4fac85f191c9.png)

**Comment by Dnkhatri** [comment]
> @Dnkhatri Just hearing about ALASS from you.
> I tested it but it got stuck in a loop repeating the same action, has that happened with you?
> ![image](https://user-images.githubusercontent.com/20923700/85900496-98bd1880-b808-11ea-8f94-4fac85f191c9.png)
> 

No it hasnt. You seem to be using the video file directly where as the op asked for syncing against another sub. In my experience it works better with syncing against subs. Against video it can be a bit and miss as music or loud noise can throw it off.

**Comment by OmrSi** [comment]
It does the same thing when doing it against a sub, just keeps repeating the same thing until I manually close the window.
