### ISSUE TITLE
Auto subtitle edit issue

### ISSUE THREAD

**Issue by srmdnadem** [SubtitleEdit/subtitleedit#4251]
auto translator it is useless in program subtitle edit because it needs API of google or bing translater, any solution, please?

**Comment by niksedk** [comment]
Try the translator plugins

**Comment by srmdnadem** [comment]
whre can I find it, please?

**Comment by OmrSi** [comment]
File -> Plugins

**Comment by srmdnadem** [comment]
> File -> Plugins

where is it please? you mean Plugins of google chrome or what? give me name or links of it?

**Comment by OmrSi** [comment]
In SE, dude.

**Comment by srmdnadem** [comment]
> In SE, dude.

explain as I said
where is it please? you mean Plugins of google chrome or what? give me name or links of it?

**Comment by OmrSi** [comment]
It's pretty clear.
File -> Plugins in SE:
![image](https://user-images.githubusercontent.com/20923700/85209132-14692200-b33e-11ea-8278-82fb1984f8cf.png)

**Comment by srmdnadem** [comment]
> It's pretty clear.
> File -> Plugins in SE:
> ![image](https://user-images.githubusercontent.com/20923700/85209132-14692200-b33e-11ea-8278-82fb1984f8cf.png)

thank you very much I appreciate
