### ISSUE TITLE
AppVeyor CI

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#4252]
AppVeyor builds/tests fails: https://ci.appveyor.com/project/SubtitleEdit/subtitleedit/builds/33636584

@xylographe: Any hints?

**Comment by niksedk** [comment]
OK, `dotnet restore` does not work with the old `packages.config`... so the the build script at AppVeyor  not does both `dotnet restore` and `nuget restore`. 

The reason it worked was probably that some old files existed...

The AppVeyor build script looks like this now:

      dotnet restore src/SubtitleEdit.sln --disable-parallel
      nuget restore src  -Verbosity quiet
      msbuild "C:\projects\subtitleedit\src\SubtitleEdit.sln" /logger:"C:\Program Files\AppVeyor      \BuildAgent\Appveyor.MSBuildLogger.dll" -verbosity:m

**Comment by OmrSi** [comment]
@xylographe 
Seems like the new design changes the hash position so it's not matching it anymore:
![image](https://user-images.githubusercontent.com/20923700/86521809-1e227780-be5e-11ea-95a2-e617bb78d7c7.png)

I changed it to match with `$p = 'committed\s*<a +href="/SubtitleEdit/subtitleedit/commit/([0-9a-z]{40})"[^>]*>'` but then I got this:
![image](https://user-images.githubusercontent.com/20923700/86534502-9b430080-bee1-11ea-9604-290bc0574ee3.png)

Probably has something with the changes Nikolaj did here.

**Comment by OmrSi** [comment]
@niksedk Can you tell me how to build a functioning beta without this script?
When I build it gives a file with a size of 2 megas, what do I have to change?
I can't figure out what I have to change in @xylographe 's script.
