### ISSUE TITLE
Bug in the batch window in last version

### ISSUE THREAD

**Issue by Samo99** [SubtitleEdit/subtitleedit#4253]
Hello

I updated to the last version and i found out that in batch option the setting for adjusting the speed and offset time and changing the frame rate is gone, i don't know if it's a bug or something else.

![1](https://user-images.githubusercontent.com/12115578/85251587-59867480-b462-11ea-9aec-b4fd09d040ac.PNG)

**Comment by niksedk** [comment]
Batch convert has a lot more options now... and you have to click on item in the list view too see options regard that item to the right - see https://nikse.dk/SubtitleEdit/Help#batchconvert

**Comment by Samo99** [comment]
> Batch convert has a lot more options now... and you have to click on item in the list view too see options regarding that item - see https://nikse.dk/SubtitleEdit/Help#batchconvert
> 
> E.g. if you click on "Merge short lines", settings for "Merge short lines" will be shown:
> ![image](https://user-images.githubusercontent.com/1261331/85254990-aa499d80-b461-11ea-9490-e3ded62982ed.png)

I noticed it now that every command has it separate window but the adjust duration limit still not exist
