### ISSUE TITLE
v3.5.16 does not remember the window size of the 'Import plain text' feature

### ISSUE THREAD

**Issue by doquan0** [SubtitleEdit/subtitleedit#4255]
I'm using Subtitle Edit v3.5.16 on Windows 8.1 x64

My screen solution is 1366 x 768 and the taskbar is always displayed at the screen bottom. In Subtitle Edit, I use the 'File -> Import plain text' feature a lot. Every time I use it, the 'Refresh', 'OK' and 'Cancel' buttons are always behind the taskbar, so these button cannot be clicked. Therefore, I have to
- Maximize its window, so the 3 button will be above the taskbar. (SubtitleEdit doesn't remember to maximizing it)
- Or, auto-hide the taskbar temporarily until I finish working with this feature.

Could you please make SubtitleEdit remember the window size of the 'Import plain text' feature?

Thanks a lot

**Comment by darnn** [comment]
Oh yeah, the buttons always end up behind the taskbar for me too.
