### ISSUE TITLE
[Feature request] In Multiple replace, about moving rules up and down

### ISSUE THREAD

**Issue by xmrea** [SubtitleEdit/subtitleedit#4258]
With the right click, we can move the rules up and down.

![Screenshot_1](https://user-images.githubusercontent.com/46967762/86222877-7cfe9d00-bb8f-11ea-9547-1ee58e121306.png)

But that takes a lot of effort.

**It would be great if we could do this with the drag & drop method.**

I hope this happens.

Thanks.

**Comment by OmrSi** [comment]
@xmrea I was just reading the code, and I saw that you can move rules and groups using "Control + Up" or "Control + Down".
I think this is a good alternative.
