### ISSUE TITLE
move settings after Windows reinstallation

### ISSUE THREAD

**Issue by evayor** [SubtitleEdit/subtitleedit#4259]
I might have to reinstall my Win10 due to heavy lagging, and also change my SSD. 

What is the way to preserve all settings I have entered in SE 3.6.16 so that I don't need to do that again?

**Comment by xmrea** [comment]
Back up the **Settings.xml** file in the subtitleedit folder. After reinstallation, paste it into the subtitleedit folder.

**Comment by evayor** [comment]
Unfortunately, I don't see such a file in SE folder in Program files.

![image](https://user-images.githubusercontent.com/57219975/86237697-ea68f880-bba4-11ea-9ae6-268f6ed970a7.png)

**Comment by xmrea** [comment]
I am using a portable version. Settings are located in the subtitleedit folder.
The following are general methods. I'm not sure it will work.

**Method 1**
<hr>

Open Windows Explorer. Type %appdata% into the file path and press enter.

Find the subtitleedit folder. And back up.

After reinstallation, Go to %appdata% and paste it again.
<hr>

**Methot 2**

Open Regedit.

Computer\HKEY_CURRENT_USER\SOFTWARE

Did you find the subtitleedit here? 

If you found...
Right click on subtitleedit from SOFTWARE subfolders...
And click export.
Save.

After reinstallation, open the subtitleedit reg file and confirm.

**Comment by evayor** [comment]
Thanks. When I used Method 1, in the Se folder there was a settings.xml file. I've backed up the whole folder. 
After reinstallation, do I need to make a fresh install of Se and then paste the backed-up folder? Because, I guess, just pasting it back there won't make it work.

**Comment by xmrea** [comment]
Install subtitleedit after installing Windows 10. Paste the folder you backed up to %appdata% after reinstalling Subtitleedit. 
If you are going to install the portable version of subtitleedit, just paste the settings.xml file into the subtitleedit folder.

**Comment by evayor** [comment]
Thanks a lot.
