### ISSUE TITLE
[feature request] Windows 10 dark mode-able or dark mode

### ISSUE THREAD

**Issue by plonk264** [SubtitleEdit/subtitleedit#4260]
would it be hard to let the program let Windows 10 redraw the window in dark mode? or just straight up have a dark mode for the app?

**Comment by evayor** [comment]
+1 for this. I was going to ask if you're planning a dark mode.

**Comment by niksedk** [comment]
Duplicate of #3678

**Comment by plonk264** [comment]
The previous issue didn't mention the Win 10 dark mode which is why I created this one. I'll update that one.

Thanks for the program, tho! Made fixing OCRs soooo much less painless than the last time I tried it years ago (especially with the Fix Common Errors)! I think I finished my first movie ever last night in less than 2 hours!
