### ISSUE TITLE
Multiple replace - remove whole subtitle

### ISSUE THREAD

**Issue by Signy13** [SubtitleEdit/subtitleedit#4262]
Is there any way how to remove whole subtitle?
I have created a lot of regular expressions for multiple replace, which fix the most common errors in subtitles from TV broadcast - for example to remove text for hearing impaired.
Sometimes, when a subtitle has only text for hearing impaired, I would like to remove the whole subtitle. Is there any way how to do it in multiple replace?

Now I change subtitles for deleting by adding ___ (see screenshot bellow, as you can see not all of them are going to be deleted) and remove them manually
![SubtitleEdit_76_dodatky](https://user-images.githubusercontent.com/18901924/86433438-139b9d00-bcfb-11ea-90b3-58a3fe501822.png)

**Comment by vinodthebond** [comment]
Just Checking:

Doesn't Tools>Remove Text for Hearing impaired work for you?

**Comment by Signy13** [comment]
Thank you for your response, I checked it and it works.
It woud be more convenient If I could add this function into my taylored multiple replace, but it is better than do it manually.

**Comment by niksedk** [comment]
>Is there any way how to remove whole subtitle?

If the result is an empty string, the subtitle will be removed.

**Comment by Signy13** [comment]
@niksedk  Thank you very much for perfect solution :-)
