### ISSUE TITLE
Merge Separate Translations

### ISSUE THREAD

**Issue by erosman** [SubtitleEdit/subtitleedit#4263]
I am not sure if the feature already exists or not. If it doesn't, it would be good to have.

There are occasions that a multi lingual subtitle is desired (e.g. it is beneficial in language learning).

Example:
If we have an English `srt` and a French `srt`
```
1
00:00:26,960 --> 00:00:29,420
You are leaving I know
```

```
1
00:00:26,960 --> 00:00:29,420
Tu pars je sais
```

The desired result would be:
```
1
00:00:26,960 --> 00:00:29,420
You are leaving I know
Tu pars je sais
```

Is that possible to merge 2 `srt` into a new `srt`?

**Comment by darnn** [comment]
Yes. Open the translated srt file in SE. Then open the original file using file->open original subtitle. Now go into options->settings, and there to shortcuts. Under general, create a keyboard shortcut for "merge original and translation". Press okay to leave the settings window. Now you can use the keyboard shortcut you created to merge the subtitles.

**Comment by erosman** [comment]
Great .. Thank you :+1:
