### ISSUE TITLE
[bug] Shortcuts being written to Text (Move start, Move end)

### ISSUE THREAD

**Issue by rebawest** [SubtitleEdit/subtitleedit#4265]
Hello.
I have tried setting these shortcuts with the default values used in EzTitles. The shortcuts seem to work, but the text is also inserted in the subtitle text ("+" and "-").
Some shortcuts should be global and not introduce text, right? That's how EzTitles work.

![image](https://user-images.githubusercontent.com/6587015/86514176-bed55080-bde6-11ea-9eef-2b30bb97c31b.png)

Could this be fixed? Thank you!

**Comment by niksedk** [comment]
Thx for the info :)

Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip

**Comment by rebawest** [comment]
Thank you! It's working fine.
Now  I've discovered these two shortcuts also write text to the textbox.
![image](https://user-images.githubusercontent.com/6587015/86521476-82761480-be27-11ea-80bc-acd6f4db8093.png)
("One frame back" and "One frame forward" are OK).

Can you fix these please?

**Comment by niksedk** [comment]
OK, but that's only when you don't have a video loaded, right?

**Comment by rebawest** [comment]
Hello.
The video was open. But I've just noticed **4** and **5** are not working on the Beta 28. They do work on the stable version (3.5.16).
The other numpad keys are working fine as shortcuts (12357890.+-*).

BTW, I can't find **NumpadEnter** in the key list. I wanted to try that as well (for "Insert new subtitle at key-down, set end time at key-up"). Please let me know if you need a separate issue for this.
Thank you.

**Comment by rebawest** [comment]
Newsflash: The problem only occurs with MPC-HC.
With DirectShow and MPV, **Numpad4** and **Numpad5** work perfectly.

**Comment by rebawest** [comment]
Hello. This issue is back. Shortcuts are being written to the subtitle box.
I'm using "Numpad5" as Play, MPV as video player and SE version 3.6.6.

![image](https://user-images.githubusercontent.com/6587015/181996749-c02a1370-a4d1-4818-ae98-13df4ecc1785.png)

**Comment by darnn** [comment]
Go to settings -> appearance. Under text box, if you have "use syntax coloring" checked, uncheck it.

**Comment by rebawest** [comment]
Thanks, Darnn.
I did, but it still writes the numbers in the subtitle box.
Some globals shortcuts are working (Numpad Minus, Numpad Plus). The problem seems to be with the numbers only.

![image](https://user-images.githubusercontent.com/6587015/181997085-24fbe541-762c-4c8d-bdc2-faeca8f40d96.png)

**Comment by darnn** [comment]
Huh. Not sure, then. For me numpad5 works if I set it to pause/play. 4 and 6 still appear as numbers in the textbox, but 5 does, in fact, pause or play the video. I'm on v. 3.6.5 NEXT beta 99. Have you tried the latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by rebawest** [comment]
I've tried 3.6.6 Beta 214.
Numpad 4, 5 and 6 still don't work as global shortcuts. 
Numpad0 doesn't work either, but  Decimal does (the numpad period).

Syntax coloring is off and video player is Directshow.

![image](https://user-images.githubusercontent.com/6587015/182026019-92700285-e5d1-48d5-9e11-bd00fb21fd76.png)

![image](https://user-images.githubusercontent.com/6587015/182026047-78fd0e9e-0052-49af-8059-1f57450e30f3.png)

![image](https://user-images.githubusercontent.com/6587015/182026056-7e9b7514-eeb3-40f0-9dde-b1f2e46bd085.png)

![image](https://user-images.githubusercontent.com/6587015/182026061-914afaee-3c57-4867-b270-e358e10fb092.png)

Let me know if I could try anything else. Thanks!

**Comment by niksedk** [comment]
Also, be sure to set this settings: 
![image](https://user-images.githubusercontent.com/1261331/182026544-bd604257-5b68-4439-ac15-4afa592d96b6.png)

**Comment by darnn** [comment]
Oh, duh. I knew I was forgetting something. I honestly think this should be on by default and syntax coloring off by default, multiple people have had this problem and it's not really intuitive to find the exact solution to it.

**Comment by rebawest** [comment]
Thanks, Nikolaj. That fixed it.
I would never have found that setting. I guess it should be on the Settings page, not on Tools, if it does what I think it's doing.

Cheers!

**Comment by rebawest** [comment]
Sorry, I mean on the Shortcuts page!
