### ISSUE TITLE
Saving subtitles in HEBREW

### ISSUE THREAD

**Issue by Anchachi** [SubtitleEdit/subtitleedit#4267]
Hi everyone, would you be able to guide me through the process of saving subtitles in Hebrew so they end up in .srt and in the RTL mode? I've managed to set RTL directly in Subtitle Edit, but when I hit Save as Subrip and in UTF-8, after opening the document, the subtitles are read from left to right, which is not what I need. Where is the magic in this? Thank you in advance!

**Comment by darnn** [comment]
Try the two options in edit, under "left-to-right mode" (fix RTL and reverse RTL).
