### ISSUE TITLE
I can't download mpv lib in Subtitle Edit 3.5.16

### ISSUE THREAD

**Issue by Meng-Xi-Bi-Tan** [SubtitleEdit/subtitleedit#4268]
![Snipaste_2020-07-09_18-44-26](https://user-images.githubusercontent.com/14193417/87030494-44f0fd00-c214-11ea-9a8e-daa02e3679d5.png)

When I try to download mpv lib, here is a mistake. Maybe mpv has changed the github adress? 
Hope next release can fix the problem.

**Comment by niksedk** [comment]
Try the manual action...

**Comment by Meng-Xi-Bi-Tan** [comment]
Thank you for apply. But sorry, I already download mpv64 and ran mpv-install.bat, still can't use it in subtitle edit. 
Should I move some mpv file or folder to [C:\Users\xxxx\AppData\Roaming\Subtitle Edit\] ?

**Comment by niksedk** [comment]
https://github.com/SubtitleEdit/support-files/blob/master/mpv/libmpv64.zip does not contain any "mpv-install.bat" file?
Just unpack the dll file.
