### ISSUE TITLE
Windows forms thread exception 65619

### ISSUE THREAD

**Issue by LiMa79** [SubtitleEdit/subtitleedit#4271]
I get this error message when I start up the program.
I have windows 10 Home edition. I don't know how to know which specific version.

I can't open any video file. I can only open the subtitle file.

![image](https://user-images.githubusercontent.com/16935047/87349814-39287200-c557-11ea-9d03-3590b878e1cc.png)

I downloaded the latest update but got the same message.

Can anyone help me?

**Comment by niksedk** [comment]
Could you attach your Settings.xml file?

If you're using the installer, you can find file by pressing WinKey+R and pasting "%appdata%\Subtitle Edit" and pressing enter:
![image](https://user-images.githubusercontent.com/1261331/87388816-ceeaee00-c5a5-11ea-945b-efd85b2b2dd2.png)

**Comment by LiMa79** [comment]
Is this ok? 
[Settings.txt](https://github.com/SubtitleEdit/subtitleedit/files/4917179/Settings.txt)

**Comment by LiMa79** [comment]
I could add/create the sound wave form by clicking in the sound area but I coudn't play it because I couldn't play the video. I tryed to change the video player to mpv but that didn't change anything. I've allways used the direcshow alternative before.

Hope this gives any clues.

**Comment by niksedk** [comment]
Hi LiMa79, thx for the file :)
The "Spell shortcut" is invalid for a menu item (has stricter requirements than a non-ui shortcut...).
Delete your "Settings.xml" file or manually edit settings.xml and remove the spellcheck shortcut.

Beta updated with improved validation for some shortcuts: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip

**Comment by LiMa79** [comment]
Thank you for the help!

**Comment by LiMa79** [comment]
I removed the short key for the spell check in the XML-file and the program worked. But now when I had shut it down and opened it up again I got the same error message again :(

**Comment by niksedk** [comment]
Hm, can you try again?
Make sure all SE instances are closed when you do this.

**Comment by LiMa79** [comment]
The issue comes and goes, for now it works. I removed the short key for the spell check inside the programs settings as well. Will see how it goes. I have to choose the movie file a couple of times before it opens it correctly.
