### ISSUE TITLE
Waveform graph does not display time correctly

### ISSUE THREAD

**Issue by Meng-Xi-Bi-Tan** [SubtitleEdit/subtitleedit#4273]
In my timeline, End Time is 00:49:42,047, cursor position is 00:49:41,547. Here is 500ms distance.
But in Waveform graph, I only can see 4 squares between cursor position and End time, why I have this problem?
version: 3.5.16, ffmpeg for wave extraction or vlc for wave extraction is just same.
![Snipaste_2020-07-15_01-08-27](https://user-images.githubusercontent.com/14193417/87455582-45383080-c638-11ea-950b-c81926a29cb4.png)

**Comment by niksedk** [comment]
I think I can see about 0.6 square + 4.0 squares , 0.4 square... which equals 5 squares of 100 ms.
