### ISSUE TITLE
Editing subtitles with waveform sync

### ISSUE THREAD

**Issue by stdedos** [SubtitleEdit/subtitleedit#4274]
_I am an amateur on SubtitleEdit, my usage is a bit unorthodox (I am syncing lyrics rendered as subtitles https://en.wikipedia.org/wiki/Kim_Possible#Music), and I'd like to hear workflow improvements._

Source files:
https://en.wikipedia.org/w/index.php?title=TimedText:Kim_Possible_(Theme_Song_-_Sample).ogg.en.srt&oldid=749619892

The shown entry (and not the most recent one) has enough issues with time-sync.
To me, they cannot be fixed with some of the automated options (and it's not really worth trying for 12 lines / 30s).

More often than not, I needed to move one subtitle's duration on top of the next one. Of course, I had no intention to overlay visible subs; however, the program wouldn't even let me to temporarily overlay them.

- Can SubtitleEdit allow overlaying subtitles with Warning (somehow)?, or
- Can the functionality be augmented, that it automatically moves the start of the next one?[^1]

I am not sure why do these need to be drop-down lists
![image](https://user-images.githubusercontent.com/133706/87460108-00e76900-c615-11ea-9713-ccd96c1f088e.png)

Wouldn't they be better being number pickers?
For delay-duration, I'd also take a zero / decimal number.

When I was done syncing, I would set 2 Repeats / 0-0.5s delay, to get a fluent audio/visual representation of my result. It's not that 1 second was _too much_ - but I thought I'd ask if it's not complicated.

----

[^1] Of course, this opens the Pandora Box:
1. Is it allowed backwards (i.e. start time overriding previous' end time)?
2. What happens when the _next_ item reaches its minimum duration[^2]?
3. How does undo work? Is it two step (undo extension, undo shrinking) or is it atomic?

[^2] And this makes me think of cases like that https://forum.videohelp.com/threads/391480-SRT-blank-line-character#post2537546
Of course, if something is broken here, an automated tool might be of more use.
I am thinking if for manual edit, you can somehow click-select 1-or-multiple segments, and move them in time by click-drag

**Comment by OmrSi** [comment]
Settings -> Waveform -> Allow overlap

**Comment by OmrSi** [comment]
Oh, you can also move the start of the next one by pressing "Alt" while moving the end time.
