### ISSUE TITLE
Having some issues with double music notes in 3.5.16

### ISSUE THREAD

**Issue by brian-armstrong** [SubtitleEdit/subtitleedit#4277]
Hello,

First, let me say, I'm really enjoying this project. I felt some despair when I realized originally that my subtitles did not contain text information, but SubtitleEdit is doing great work of extracting most of the text in the subtitles I'm using.

I have noticed one little snag which is that double music notes seem to confused SubtitleEdit no matter which OCR engine is used. Generally I'm seeing more accuracy with Tesseract 5.0.0 Alpha 2020-03-28 with Engine set to "Default, based on what is available" than with any other mode. There is one place where this consistently fails though, which is when two music notes appear next to each other. This seems to basically always confuse Tesseract.

Is there anything I can do to improve accuracy for these? I'm a bit worried about globally changing everything that maps to these as it doesn't seem to be consistent as to which letter or letters it finds. I'm not sure how feasible it is to retrain Tesseract.

Thanks!

![image](https://user-images.githubusercontent.com/15702338/87904292-cf0a4400-ca12-11ea-929b-a561d3f7dc07.png)

**Comment by niksedk** [comment]
You can try to report an issue about poor music symbol support in tesseract 5 here: https://github.com/tesseract-ocr/tesseract/issues
Could might get better feedback if you attach the raw image and use the raw command line... like `tesseract input.png output.txt --oem 1 -l eng`

A similar issue was created here: https://github.com/tesseract-ocr/tesseract/issues/2960

Re-training Tesseract is a posibility, but will like take a lot of time to learn/do: https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00.html

Also, could you attach the sup file (as zip) or the raw image so I can test too?

**Comment by stweil** [comment]
Which Tesseract models are used to recognize musical symbols?

**Comment by niksedk** [comment]
Hi @stweil,

SE uses https://github.com/tesseract-ocr/tessdata which contains the old "Original Tesseract only" + the new LSTM models. The default engine mode is "Default, based on what is available". Does newer/better models exist?

This image does not detect the music symbol with neither original or the newer LSTM:
![image](https://user-images.githubusercontent.com/1261331/179574029-1c85c2e5-8d90-4d46-97e6-3b8d1a038e06.png)

This image does not detect the music symbol with the newer LSTM (but the original Tesseract works):
![image](https://user-images.githubusercontent.com/1261331/179574243-b821b1c6-d2d8-4351-b25d-fc8c3376fcc5.png)

**Comment by stweil** [comment]
I tried that image with the legacy OCR engine and the English model from `tessdata`. It detects `J‘ Until he runs out of gas J‘`, no musical notes.

What means "the original Tesseract works"? Which Tesseract version and what model was used to get it working? Or are musical notes detected with special code in SubtitleEdit?
