### ISSUE TITLE
Could SE be causing Win10 lagging?

### ISSUE THREAD

**Issue by evayor** [SubtitleEdit/subtitleedit#4278]
I'm using the last version of SE 3.6.16 on Windows 10. 
I've written before about serious lagging issues which, however, span over all my apps, not only Subtle Edit. 

So a week ago I switched to a larger (512 GB) ssd disc. this didn't solve the issue and then reinstalled Windows. For a couple of days everything was fine until the whole issue came back with full strength.

Now I\m investigating which software I have installed could be the cause and my question is if anyone has had a similar problem ot could SE, mpv filters or anything else connected with the app be the cause.

**Comment by niksedk** [comment]
Is your system lagging when SE is closed too?
SE nor libmpv should leave anything behind when the program is closed.
If you really want to wear a tin foil hat, use the portable version of SE (as the installer adds a few registry keys).
