### ISSUE TITLE
Comments (NOTE) in VTT files interpreted as subtitle content

### ISSUE THREAD

**Issue by Issity** [SubtitleEdit/subtitleedit#4279]
According to the WebVTT specs (https://www.w3.org/TR/webvtt1/#introduction-comments) "NOTE" keyword preceded by an empty line and followed by a space or new line denotes a comment.

SubtitleEdit only interprets NOTEs before the first subtitle as comments.
Any NOTEs placed further in the subtitle file are interpreted as a part of the subtitle.

Some transcription services include additional information as NOTEs and this bug makes them unusable in SE.

Expected result: All proper NOTEs should be interpreted as comments and not included in subtitle text.

![image](https://user-images.githubusercontent.com/36386566/88033806-16422300-cb40-11ea-84e1-9d04a4f9480f.png)

[VTT NOTE example.zip](https://github.com/SubtitleEdit/subtitleedit/files/4952314/VTT.NOTE.example.zip)

**Comment by niksedk** [comment]
Thx for the nice issue :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip

**Comment by wegylexy** [comment]
Is there a way to actually visualize and edit such invisible comments in SE? For WebVTT and also TSV2 where I insert comment lines without time codes (SE currently just skips them on open and thus loses them on save).
