### ISSUE TITLE
Waveform lagging

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4280]
Hello,
Recently I upgraded from a 43" LED 1980x1020 to a 49" 4k with 4096x2160 resolution. I opted to set 3840x2160. The problem that I realized immediately was the lag in waveform. The line that moves used to be so smooth that you'd hardly notice. Now it jumps from frame to frame.  I use MPV. And I have tried will all other options and it still lags. Any solution?
Also, with a screen this big, we're forced to set the scale and layout at 200%, and I have noticed that if you go close to the screen, you see the broken/blurry text. Any ideas?

**Comment by niksedk** [comment]
Sorry, I don't know how to solve this. The waveform requires some cpu power. How high is the SE cpu usage in % for you?
You can try to turn off the grid and make waveform smaller - that's my only ideas, besides a faster cpu.

**Comment by uckthis** [comment]
Processor: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz, 3001 Mhz, 4 Core(s), 4 Logical Processor(s)
Not only that, I have Nvidia GeForce 750Ti 2GB DDR5 graphics card. 
Issue started when I upgraded my 43" HD LED to 49" 4K smart LED.  Anyway, I'll make it work. I'm used to it being lagging now. Been a month. 
@niksedk

**Comment by cheetah92** [comment]
> Sorry, I don't know how to solve this. The waveform requires some cpu power. How high is the SE cpu usage in % for you?
> You can try to turn off the grid and make waveform smaller - that's my only ideas, besides a faster cpu.

Hi, I experienced this problem a lot. Waveform is amazing when I'm using on my ancient win 7 laptop, and laggy on my decent pc.
But I've seen many times that it's about rendering of the video (or formatting in that case, I don't know). So sometimes same video is incredibly laggy in the waveform and smooth with, let's say, mp4 format.
Also, changing video player option mostly helps this.

**Comment by OmrSi** [comment]
@uckthis The waveform is the smoothest with Directshow, then MPV, then VLC.
I don't know if this is related in anyway.

**Comment by OmrSi** [comment]
The waveform is the smoothest with Directshow, then MPV, then VLC.
I don't know if this is related in anyway.

**Comment by uckthis** [comment]
@OmrSi  Yes, Directshow is/was the smoothest, but since about May 2019, when I use Directshow I only get audio and no video. We have tried everything and after raising an issue here I decided to use MPV last year.
