### ISSUE TITLE
Punctuation with RTL and Latin characters

### ISSUE THREAD

**Issue by baerlein** [SubtitleEdit/subtitleedit#4281]
Hi
When there's an English word inside a Hebrew subtitle (didn't check other RTL languages), the punctuation is coming out wrong. That's after using the "Reverse RTL start/end.." option. Please see attached example. The text on the green background below is the correct way it should be.

![Untitled-1](https://user-images.githubusercontent.com/49202713/88308079-4db5f880-cd15-11ea-8a24-e864dd340459.jpg)

**Comment by OmrSi** [comment]
You need to use "Fix RTL via Unicode control characters" if there is an English word.

**Comment by baerlein** [comment]
Thanks but I tried it and it didn't do anything.

**Comment by darnn** [comment]
How do you mean? It works over here. Here's the sentence from your example (without anything applied to it):
![se-nasa-1](https://user-images.githubusercontent.com/19672444/88406691-b5ce1280-cdd9-11ea-8a72-92b1378d177b.png)

This is what it looks like if I align it left in the textbox using ctrl+shift:
![se-nasa-2](https://user-images.githubusercontent.com/19672444/88406946-0cd3e780-cdda-11ea-816b-f2dcd6b8727f.png)

And this is what it looks like after I use "fix RTL via Unicode control characters":
![se-nasa-3](https://user-images.githubusercontent.com/19672444/88407824-57a22f00-cddb-11ea-92a9-98bdd9a33481.png)

**Comment by baerlein** [comment]
Sorry, I should have mentioned it in the original post, the behavior described is when importing a .890 file, not when typing the text directly in Subtitle Edit. I've attached the sample file here.
[Test_NASA3.zip](https://github.com/SubtitleEdit/subtitleedit/files/4973018/Test_NASA3.zip)

**Comment by darnn** [comment]
Ah, okay, there does seem to be an issue with the way SE is importing that text. Even if you create a new file from scratch with that subtitle, export it as 890 and then import it again, it still gets imported wrong.

**Comment by Monovox** [comment]
In non-Unicode, a Latin string in the middle of a line causes the part of the line supposed to be before the Latin word and the part after reverse places. An option to fix that in the program can be a helpful feature. (If more then one Latin string is present, the replacement should be done in sequence from left to right).
