### ISSUE TITLE
Ebu TT XML to STL conversion issue

### ISSUE THREAD

**Issue by jayotirana** [SubtitleEdit/subtitleedit#4282]
While converting ebu tt xml file to stl format, it won't keep the same information for subtitle color in stl output:
EBU TT XML file:
![sample-xml](https://user-images.githubusercontent.com/17136894/88373076-cb7d1100-cdb4-11ea-9c27-2cf18e976d6a.png)

STL file:
![sample-stl](https://user-images.githubusercontent.com/17136894/88373112-d89a0000-cdb4-11ea-9c5b-df6842e091ef.png)

sample file:
https://bbc.github.io/subtitle-guidelines/sample-ebutt-prepared.html

While playing the same along with media, the xml file has color yellow for the second block and the same subtitle in yellow color will appear in the video. But the generated stl file won't have any color information for the subtitle text. 

Thanks

**Comment by niksedk** [comment]
When you save the STL file and want colors... you must use teletext.

![image](https://user-images.githubusercontent.com/1261331/88386865-8d322280-cdb1-11ea-8c31-7b62b1868f8d.png)

**Comment by jayotirana** [comment]
Thank you for the update @niksedk. Able to see the color in the video file too but there is still an issue with style tag creation though it's not creating any issue but if we compare the two file content xm and stl then it's not matching exactly that xml has.

EBU TT XML file:
![sample-xml](https://user-images.githubusercontent.com/17136894/88390174-7f8e9400-cdd5-11ea-8544-1d5332710fa4.png)

STL file:
![closing-tag-issue](https://user-images.githubusercontent.com/17136894/88390049-46eeba80-cdd5-11ea-933c-9d333981e75c.png)

Is there any solution to this, otherwise I will raise a new issue for this.

Thanks
