### ISSUE TITLE
Ebu TT XML to STL conversion issue

### ISSUE THREAD

**Issue by jayotirana** [SubtitleEdit/subtitleedit#4284]
There is still an issue with style tag creation though it's not creating any issue if we compare the two file content XML and STL then it's not matching exactly that XML has.
https://github.com/SubtitleEdit/subtitleedit/issues/4282

EBU TT XML file:
![ebu-tt-xml-file](https://user-images.githubusercontent.com/17136894/88509291-5dc42580-cffe-11ea-93a3-9d09fe02c949.png)

STL file:
![stl-file](https://user-images.githubusercontent.com/17136894/88509308-66b4f700-cffe-11ea-8a04-be842864a7e8.png)

Also, the fourth block has color information but the generated STL file won't have (I used the option that you suggested). Is there any solution to this, otherwise I will raise a new issue for this.

Thanks

**Comment by niksedk** [comment]
Do not expect spaces/styling to be the same across formats in SE... sorry.
I think the example file has weird white spaces...?

End font tags improved slightly here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip
