### ISSUE TITLE
Insert goes to last end time

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4287]
Hello,
This doesn't happen that often, but happens so much that it's giving me a headache now. What happens is, when I click insert, instead of adding a new subtitle at the pause time, subtitle's start time starts at the last end time. It only happens when I click insert and then Ctrl+V before the subtitle is added. But when you're working fast, you don't wait and try to do it as quick as possible. 
Example:  See where I pause the video and click insert, but subtitle starts at  last end time. Help!

![Bug](https://user-images.githubusercontent.com/28671050/88744313-6896cb80-d160-11ea-84c9-aec7569647c0.gif)

**Comment by niksedk** [comment]
I've just tested some with Shift+F9 and Ctrl+v and I was not able to re-create the error.
Also, which button do you click on? What video player do you use?

**Comment by uckthis** [comment]
For me, pause is Alt+space and then insert key is the insert. When I click insert and paste text before subtitle is added, it goes to last end time. Doesn't happen otherwise.
mpv

**Comment by uckthis** [comment]
Changed shortcut key from Insert to Home and now it's working without a hitch.
