### ISSUE TITLE
Join/Merge Subtitles 

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4288]
I have two files. One has the English subtitles and other has the translation of foreign parts. So, foreign parts maybe at 10:00 and then at 16:00 and then 49:00... I was under the impression that when I'd join subtitles, it will automatically put the right subtitles in their right place, but that doesn't happen. Join subtitles just joins the first file with the second file as A and B. What's the workaround?
I'm attaching the files I want to merge.

[2.zip](https://github.com/SubtitleEdit/subtitleedit/files/5000170/2.zip)

**Comment by niksedk** [comment]
Try Tools -> Sort by start time (+ renumber)

**Comment by uckthis** [comment]
@niksedk Thank you, it worked. For some reason all of the text from foreign subtitles doubled and there were two subtitles with same text, so I just used Merge lines with same text and it worked.
