### ISSUE TITLE
Is There a Way to Export Multiple Subtitle Files in a batch?

### ISSUE THREAD

**Issue by haripetrov** [SubtitleEdit/subtitleedit#4290]
This option can save a lot of time. As far as I can see there is no such option under: Tools > Batch Convert.
Real case scenario: I have multiple .srt files which need to be exported as: Plain text (Unbreak lines).

**Comment by niksedk** [comment]
Should be available (scroll to the bottom of output formats and choose "Plain text"):
![image](https://user-images.githubusercontent.com/1261331/89006250-96b61000-d306-11ea-9a96-c8c15ceabf10.png)

**Comment by haripetrov** [comment]
Thank you very much! It's working like a charm!
