### ISSUE TITLE
Linux (mono) + Voikko

### ISSUE THREAD

**Issue by Gitraffe** [SubtitleEdit/subtitleedit#4291]
Hi,

Has anyone got Voikko (finnish spell checking) to work with linux (mono)?

Voikko has spell-checking packages for linux distros and AUR repository have some too. Any way to use those?

I have run windows VM in my linux system for years only for SubtitleEdit, because I haven't made it work fully under wine or mono. So any help would be more than appreciated!

All other parts of SubtitleEdit runs correctly with mono. (characters, tesseract finnish etc.)

**Comment by niksedk** [comment]
Hi @Gitraffe,

The current implementation of SE/Voikko is Windows only... 
I've tried to change that in this commit: https://github.com/SubtitleEdit/subtitleedit/commit/fa877f151b2be52a1ac4f11573146e33447316e7
SE now looks for a file called "libvoikko.so" on Linux.

Binaries here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBetaFI.zip
(it's un-tested on Linux)

**Comment by Gitraffe** [comment]
Hi,

First of all, thanks that you are trying to solve this!

With that BetaFI version I can get "Finnish (finland) [fi_FI]" to dropdown menu in OCR auto correction / spell checking section, but seems that there is no words in dictionary. I can find libvoikko.so from my system from directory "usr/lib".

I don't know how user dictionary works, but if I add words there, they will be added to that Finnish dictionary. (no "errors" with those words if I run spell check again.

**Comment by niksedk** [comment]
Seems it needed a bit more: https://github.com/SubtitleEdit/subtitleedit/commit/be06dd9dcf9802c421779e9e6b359060da656cf2
FI beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBetaFI.zip
You probably need to make a link file, something like `sudo ln -s /usr/lib/x86_64-linux-gnu/libvoikko.so ~/Downloads/SubtitleEditBetaFI/libvoikko.so`


User added words are just saved in an xml file (something like fi_FI_user.xml)

**Comment by Gitraffe** [comment]
You have no idea how happy I'm right now, It's working!!! 
I had to make that file link as you instructed.
I will start to test that beta and will report if I run into any issues.

Now my biggest "problem" seems to be the "brownish gray" background color of the window when using mono.
I think that it's mono related and I have to find solution from there? Or do you have any information on how to change it, even if this is not really related to your program.

**Comment by niksedk** [comment]
Thx for verifying libvoikko functionality.

 I've not clue about the  "brownish gray/beige" background, sorry.
