### ISSUE TITLE
Synchronization > Change Speed .. 'Selected Lines Only' vs 'All Lines'

### ISSUE THREAD

**Issue by iSAWaUFO** [SubtitleEdit/subtitleedit#4292]
A bug? with version 3.5.16
I'm resynchronizing some titles to match a video of a different/unknown frame rate.

I've shifted all lines, so the first title syncs with audio.
I calculate the percentage of drift between the first title and the last title.

I **select all** the title lines and in the Synchronize > Change speed (percent), 
I select 'Custom' and 'Selected Lines Only', in the 'Adjust speed percentage' dialog box. 

The time changes affect all lines, even the first title line, exactly as though I had
chosen the option 'All Lines' instead of 'Selected Lines Only'.
The anchor for the time shift was a time zero, instead of the first selected title.
The result has all titles out of sync

The anchor point for the speed change, should be the start time of the first title in the selection (IMHO).
It seems that the anchor point for speed change is alwaysat  time zero, even when changing the speed of 'Selected Lines Only'.
Currently it is possible to make a speed change on a partial selection of lines, and end up with some lines have a start time shifted so much as to start prior to some of the preceding lines.

Two work around the problem, I must shift all titles earlier, so that the first title is at time zero, before making the speed change, then shift all titles later, by the same amount, after making the speed change.

**Comment by niksedk** [comment]
`Selected lines only` works fine for me...

**Comment by iSAWaUFO** [comment]
Just a quick follow-up question..
When you 'select lines only' does the start time change, for the first selected line?
If that's the way it's supposed to work, then I will adjust my thinking accordingly. 
Also, THANK YOU! for this great tool! It is a marvel, for those who need it.
