### ISSUE TITLE
Font style tags are not closed

### ISSUE THREAD

**Issue by hardevgun17** [SubtitleEdit/subtitleedit#4294]
Hi,

As I am using the SubtitleEdit (with version 3.5.16) source code in my application, And I have been facing one issue in conversion of ebu-tt xml to STL.
My xml file has some font tags with color property but when I convert it to STL format, the font tags are not closing where its required to. Although the preview of the subtitles are fine.

**Output:**

![image](https://user-images.githubusercontent.com/52063734/89283653-1e837d80-d66b-11ea-9a36-a21afb1969de.png)

**Expected Result:**

![image](https://user-images.githubusercontent.com/52063734/89283728-407d0000-d66b-11ea-8c36-0eab06237381.png)

I did tried the conversion from the Subtitle Edit software v3.5.17 (xth September 2020) BETA and it worked and the results were as expected. 
I am using libse.dll from your github code. If you recognize this issue and have the latest libse.dll with this issue resolved then can you please provide me that.

**Comment by niksedk** [comment]
OK, added libse here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/libse.zip

Alternately you can SubtitleEdit cmd line conversion: https://www.nikse.dk/SubtitleEdit/Help#commandline

**Comment by hardevgun17** [comment]
Hi @niksedk,

Thanks for your response. 

I have been facing some other issues related to the font tags. I am using SubtitleEditBeta version here and trying to convert the Ebu-TT XML file into STL format. You can see that there are no font tags in the fourth block of subtitles in STL output.

I also used the latest dll that you provided but didn't resolve this issue. 

Please look into the screenshots:

**EBU-TT Xml Output:**
![ebu-tt-xml-beta-version](https://user-images.githubusercontent.com/52063734/89563712-7f60b080-d839-11ea-8946-2f5f106e990b.png)

**STL Output:**
![stl-output-beta-version](https://user-images.githubusercontent.com/52063734/89563718-8091dd80-d839-11ea-8952-3221f974c658.png)

**Comment by niksedk** [comment]
Can you attach a sample file with the problem?

**Comment by hardevgun17** [comment]
@niksedk Here are the sample file of Ebu-tt xml and generated STL files.

[Sample files.zip](https://github.com/SubtitleEdit/subtitleedit/files/5039353/Sample.files.zip)

**Comment by niksedk** [comment]
@hardevgun17: thx for the file - SE strips color tags where the whole subtitle is white... is that a problem for you?

**Comment by hardevgun17** [comment]
@niksedk 

Yes..
There is issue in the fourth block i.e: "**...and they all lived happily ever after**" (which is also marked with red marker) are not matched. You also can check the screenshots above.

**Comment by niksedk** [comment]
Yes, it's a problem for you?

It's not a bug - it's a feature ;)

**Comment by hardevgun17** [comment]
@niksedk  Can you please explain me a little more about this feature?
