### ISSUE TITLE
Problem with Microsoft Translator

### ISSUE THREAD

**Issue by MehdiZouaoui** [SubtitleEdit/subtitleedit#4297]
I've added Microsoft Translator API to the program but when I click on "translate" an error message shows up ( it showed up in Turkish and below is my translation:

_An application error occured in Subtitle Edit 3.5.16.0_

Error message: the identified value contains an invalid CRFL characters.

Stack Trace
Location: System.net.WebheaderCollection.CheckbadChars(string name, Boolean is HeaderValue)
Location: System.net.WebHeaderColleciton.Add (string name, String value)
Location: Nikse.SubtitleEdit.Core.Translate.MicrosoftTranslator.Translate (String sourceLanguage, String targetLanguage, List1 paragraphs, StringBuilder log)
Location: Nikse.SubtitleEdit.Forms.GoogleTranslate.Translate (String source, String target, ITranslator, Int32 maxTextSize, In32 maximumRequestArrayLength)
Location: Nikse.SubtitleEdit.Forms.GoogleTranslate.ButtonTranslate_Click(Object sender, EventArgs e)

I've uploaded a screenshot of the error message and uploaded it to Google Drive [https://drive.google.com/file/d/1EUw0AnRkr0q73AM-DP4SFnjY2UbF3NJb/view?usp=sharing ](url)

**Comment by niksedk** [comment]
Github supports image paste
![image](https://user-images.githubusercontent.com/1261331/89556555-de123400-d811-11ea-96f7-36465e92e84e.png)

**Comment by niksedk** [comment]
It works fine here... could you attach a sample file that fails?

**Comment by MehdiZouaoui** [comment]
[https://drive.google.com/file/d/1g_dBsDDr_7Klux23-rhsdd71hdG0MJ06/view?usp=sharing](url) here it is. I used Pytranscriber. I was trying to translate it from Turkish to Arabic.

**Comment by niksedk** [comment]
Sorry, I cannot re-create the error with your file - tried with both API key and the plugin "BT screen-scraper"
