### ISSUE TITLE
[Question] Positioning, Colors and Similar Captioning Features for Scenarist Closed Captions

### ISSUE THREAD

**Issue by madprogramer** [SubtitleEdit/subtitleedit#4298]
Hello,

I discovered Subtitle Edit only a few months ago and I've been trying to get into it recently. In particular, I noticed that it has support for Scenarist Closed Captions (SCC) which allow for a lot of customization:

https://www.youtube.com/watch?v=taWLluM1pak

That being said, as far as I can tell Subtitle Edit can currently only "read" some of this information but doesn't really support the full set of features in SCC. Is there a hidden menu for this which I'm not seeing, or is it just not a feature yet? Will it be anytime soon, or would you advice me to Fork as this much support for a single format would be a bit out of place?

**Comment by niksedk** [comment]
Yes, SE only has basic support of .scc (no hidden menus or anything)

Any specific feature you are after?

Alignment: SE could support top alignment at the least... if I knew how? (SE has read support for top alignment...)
Colors: I guess Red/Yellow/Green/Blue/Cyan/Magenta would be nice to support too.

I don't have the .scc spec, so help or info welcome :)

**Comment by niksedk** [comment]
Alignment support might work in latest master branch - and in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip
Does that work for you?

**Comment by madprogramer** [comment]
Nice!
