### ISSUE TITLE
Lost settings and subtitle file after crash.

### ISSUE THREAD

**Issue by nkh0472** [SubtitleEdit/subtitleedit#4299]
For some reason, my windows 10 turned bluescreen when I saving(or autosaving) the subtitles. It seems like the mouse suddenly moves very slow, and then my computer didn't respond to any input. (windows version is 19042.388 and subtitleedit version is 3.5.16, which both are newest stable version)

After crashing, the subtitle file I was editing turning blank. To be precise, the file size has not changed, but when opened with notepad3, all the contents of the file become to NUL. Anyway, I'm not sure if the crash is a hardware problem or software problem, and I also have an autosave file to recover my progress to a few minutes ago, so it's not a big deal.

The biggest problem is, after the computer crashed, when I restart the subtitleedit, the software seems to restore to default config. The language setting or any other thing is just appeared, looks like a new installing soft. So I'm wondering that,
1. Why the settings of subtitleedit lost after a computer crash.
2. Where is the config file of this software, so I can backup it manually?
3. Or is it possible to add an import/export settings function like other software?

**Comment by niksedk** [comment]
You can find the settings file via the menu item `Spell check` - `Get dictionaries...`  - `Open dictionary folder` - go one folder up...
All settings are in a file called `Settings.xml`.

**Comment by nkh0472** [comment]
Well, this folder is too messy. I think it might be better if saving all settings files into My document folder, or simpler, under the installation dictionary. This allows me not to worry about losing the settings after reinstalling the system.

**Comment by niksedk** [comment]
If you use the portable version, `Settings.xml` is in the main folder.
