### ISSUE TITLE
Batch convert error

### ISSUE THREAD

**Issue by ismail0100** [SubtitleEdit/subtitleedit#4300]
Hi guys.
1- When I convert vtt to srt, just only convert srt. It does not make the settings I made. Like fixing common mistakes. I have to make again on srt files.

2- This is more important for me. Is it important idk but I use latest version in turkish language. When batch converts files, I choose "1254 turkish windows" and srt but SE hangs on the head. Some of them are Latin some of them are Turkish iso etc.

Thank you for your working.

**Comment by niksedk** [comment]
I think I need more/better info, like sample files and some examples from those sample files that does not work.

**Comment by ismail0100** [comment]
Can i sample with video?

**Comment by ismail0100** [comment]
This is latest build.  v3.5.13 there is a no problem for this convert. I tried 3.5.13-3.5.14-3.5.15-3.5.16.

https://vimeo.com/446274175

**Comment by niksedk** [comment]
ANSI encoding is all about guessing... what the difference between 1254 and 28599 ?
I changed the ANSI encoding guessing component a while back, but I could make Turkish ANSI prefer 1254 over 28599.

UTF-8 is the preferred format today.

**Comment by ismail0100** [comment]
But as you can see make "28593 latin 3 iso" too not only 28599 turkish. Utf-8 preferred and I like it for english subtitles but for turkish can be some errors because we have different letters. I dont understand why SE dont make our choose. We choose there 1254 but SE still guessing right?

**Comment by niksedk** [comment]
I think `28599` and `254` are actually the same (except for some not used control codes): https://en.wikipedia.org/wiki/ISO/IEC_2022#Control_character_sets

UTF-8 should be preferred for Turkish too - does have all Turkish characters and will also work on non Turkish computers.
(ANSI encoding has been obsolete for 20 years...)

 I could make SE prefer ANSI prefer 1254 over 28599 with Turkish is that will help and 1254 is the "Normal ANSI" encoding for Turkish?

**Comment by ismail0100** [comment]
Okay thank you. I will try when you add the next versions.

**Comment by Monovox** [comment]
@niksedk could you please also make SE prefer 1225 for hebrew?  This is the "Normal ANSI" encoding. Thank you.

**Comment by niksedk** [comment]
> 
> 
> @niksedk could you please also make SE prefer 1225 for hebrew? This is the "Normal ANSI" encoding. Thank you.

1225 instead of ... ?

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip
Please verify :)

**Comment by ismail0100** [comment]
99% works fine. Just one episode use latin 3 iso istead of turkish 1254. But I examine this subtitle has a error with turkish character. E.g "ý" instead of "ı", "ţ" instead of "ş". But I have one question though. I tried CC English sub to 1254 turkish but SE make Europe. Why couldn't I do what I wanted?

**Comment by niksedk** [comment]
You can always do File -> Open subtitle with manually chosen encoding...

Still do use UTF-8... ANSI encoding is obsolete!

**Comment by Monovox** [comment]
Instead of 28598. 
sorry

**Comment by ismail0100** [comment]
> You can always do File -> Open subtitle with manually chosen encoding...
> 
> Still, do use UTF-8... ANSI encoding is obsolete!

Mate I understand you very well. But I upload subtitle sometimes an one episode sometimes 100 episodes. Therefore, I need the coding I have chosen MUST be used. Because another coding cause error that the program chooses by guessing. Actually what I want; as in previous releases v3.5.13 , Instead of having a codec preferred by default, using **my chosen** one by necessity. If you don't mind, I will stay in version v3.5.13 for now. But I am very sorry that I will miss the improvements and fixes you will make.

**Comment by Monovox** [comment]
@ismail0100, You can try ticking off "Auto detect ANSI encoding" in settings, maybe this will help.

**Comment by ismail0100** [comment]
> @ismail0100, You can try ticking off "Auto detect ANSI encoding" in settings, maybe this will help.

I am sorry, It not works.

**Comment by niksedk** [comment]
@ismail0100: You can attach the subtitles that does not work and I'll take a look.

**Comment by ismail0100** [comment]
I want this three sub all have 1254 turkish code(I know one of them english subtitle but for batch convert I need this code). S01E01[TR] will be Latin, S06E01[CC-eng] will be 1252 Europe and S06E01[TR] will be 1254 Turkish.
[Glee.zip](https://github.com/SubtitleEdit/subtitleedit/files/5080538/Glee.zip)
