### ISSUE TITLE
Interacting with Subtitle Edit via PostMessage

### ISSUE THREAD

**Issue by gleaming** [SubtitleEdit/subtitleedit#4301]
Is there way to call Subtitle Edit functions from other app (especially from AutoHotkey script) via PostMessage?
Especially what I need:
- Get list of subtitles (number, start time, end time, text of any subtitle of current file) with PostMessage;
- Get indexes of selected items
- Call "Adjust durations of selected lines" with custom parameters with PostMessage. Without sending keystrokes and putting values into window from AutoHotkey
- Merge selected lines
- Undo
- Redo
- Move last word to next subtitle
- Move first word from next subtitle
- Move last word from first line down
- Move first word from next line up
So is it possible in current versions?

**Comment by niksedk** [comment]
Sorry, it's not possible.

**Comment by gleaming** [comment]
Are some developers gonna implement this? :-)

**Comment by OmrSi** [comment]
@gleaming He's THE developer.

**Comment by gleaming** [comment]
I know but maybe somebody else of SE developers (if there any) would like the idea ;-)

**Comment by OmrSi** [comment]
Well, you can say he's the only developer.
