### ISSUE TITLE
Subtitle Edit - Problems Seeking / Moving Audio Bar For Timing

### ISSUE THREAD

**Issue by devilcoelhodog** [SubtitleEdit/subtitleedit#4302]
Hi, Nikse.

When I try to use Subtitle Edit to time one video, I got some erors. Never happend before.

![ERROR](https://user-images.githubusercontent.com/36486762/90071498-10b5a400-dccc-11ea-9324-1201a822ec26.PNG)
[Video Text.txt](https://github.com/SubtitleEdit/subtitleedit/files/5066005/Video.Text.txt)

I'm using the version 3.5.16 NEXT - Beta 61.

Thanks.

Best regards.

**Comment by niksedk** [comment]
Hi @devilcoelhodog,

thx for the info - can you provide steps to re-create the error?
