### ISSUE TITLE
OCR uses different Fonts

### ISSUE THREAD

**Issue by t2YU2m8l83** [SubtitleEdit/subtitleedit#4304]
The OCR window uses two different fonts. One for the Edit Textfeld and one for the ~~"Unknown words"-list and~~ "add to replacement list"-boxes. But the later ~~two~~ uses a font which has no clear difference between I (uppercase i) and l (lowercase L). That's pretty annoying because I have to double check every time with the edit box.

Edit: looks like the Font in the "Unknown words"-list has already been changed

**Comment by niksedk** [comment]
Thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip

SE uses "Tahoma" for the OCR input text boxes (see we can see the difference between uppercase "i" and lowercase "L")
