### ISSUE TITLE
Better word break and word parts recognition

### ISSUE THREAD

**Issue by t2YU2m8l83** [SubtitleEdit/subtitleedit#4305]
It's pretty annoying that the "unknown words" OCR list includes "pany" if the subtitle is "com-\r\npany". Same goes for "com..." or "com…". You should also add something like "(\w+)-\r\n(\w+) => \r\n$1$2" to the common fixes list to remove all word breaks. This might also be a little bit more intelligent then the regex and uses the shortest line to stitch the words together.

**Comment by niksedk** [comment]
I don't think the `unknown words` OCR list contains `pany`...

**Comment by t2YU2m8l83** [comment]
Well it was an example. the problem is that subtitle edit doesn't recognize a splittet word correctly. I had the problem a couple of times were the first first and second part where decided. The German language has really long words for like "Keilwellenschleifmaschine", which can be split at the following points "Keil-wel-len-schleif-ma-schi-ne". If the subtitle contains "Keilwel-\r\nlenschleifmaschine" then both parts will be listed as unknown words when you run it through OCR.
