### ISSUE TITLE
Bulk OCR

### ISSUE THREAD

**Issue by t2YU2m8l83** [SubtitleEdit/subtitleedit#4308]
Bulk OCR should allow you to select the OCR settings like you can in the regular OCR window. It should also display you the "unknown words", "all fixes" and "guesses used" lists for each subtitle. You should also be prompted if a character couldn't be recognized. In short, you should have all the options and features in the Bulk OCR window you have in the regular OCR window.

**Comment by niksedk** [comment]
Sorry, no.
