### ISSUE TITLE
OCR word list won't recognize words starting with -

### ISSUE THREAD

**Issue by t2YU2m8l83** [SubtitleEdit/subtitleedit#4310]
OCR of anime subtitles includes sometimes name-honorific terms eg. Sakura-chan. Adding "-chan", "-san" and "-kun" to the names/noise list will still report "chan", "san" and "kun" als unknown words for OCR. simply adding such generic 3/4 letter terms to the list would be possible but could result in false positives at other places.

**Comment by niksedk** [comment]
Thx for the info/idea :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip

**Comment by t2YU2m8l83** [comment]
I updated to 3.5.17 but it still reports "kun" and co as unknown despite "-kun" listed in the "..._names_user.xml" file. Below you can find a subtitle which contains -kun, -san, etc. First "-kun" occurs at line 16.

https://mega.nz/file/1JAgyTqa#SlZF9wSYnbHb8qw5hMGoff03OUq7bf1PPA0XSX0EoNc
