### ISSUE TITLE
Allow switching original text and text fields positions [request]

### ISSUE THREAD

**Issue by crisc2000** [SubtitleEdit/subtitleedit#4319]
Use case: the translation mode . Go to Menu=>File=>Open original subtitle (auto-translated)

The "Original text" appear on the right and "Text" (translation that you are working) column appear on the left side.
Also the individual translation line editor appear in the same way.

The normal workflow is to read the original subtitle, then read the (auto)translated subtitle, or write the text by yourself (but working on auto-translated by google subtitles is more faster). So every time you must read in the right panel first then move the eyes to the left panel.

This eye movement is counter-intuitive for European languages, and it makes you tired more faster by fighting with your brain! In the European languages you read starting from left to right. 

While is possible to switch text with original text position (by drag and drop columns with the mouse) I did not found any option to switch the positions of lines editor.

Request: please add option in the settings that the original text should be on the left side then text on the right. This should be the default if this software is made for european languages. I asked for option and not hardcode this into program code because for some arabic languages probably is preferred to be like it is now, as they read from right to left.

![2020-08-23 (2)](https://user-images.githubusercontent.com/1497398/90988689-7132c400-e59d-11ea-85f0-0fb493b1178c.jpg)

**Comment by niksedk** [comment]
For me the current way is more natural... but you can switch current/original via a shortcut:
![image](https://user-images.githubusercontent.com/1261331/91015790-0bb9f400-e5ec-11ea-81ce-efe12c99b0cc.png)
And in the `Edit` menu you can choose to use the `original subtitle` in video/audio preview.

**Comment by crisc82** [comment]
thanks, it's working ... partially.
my translation appear to "original". labels should switch also (just a suggestion).

p.s.  maybe you have used Subtitle Edit for a long time, and you got used to read from right to left.

**Comment by darnn** [comment]
This might not be what you had in mind, but you can always try right-to-left mode (in the edit menu).
