### ISSUE TITLE
[REQUEST] Ability to select/filter FORCED texts

### ISSUE THREAD

**Issue by Lokotito** [SubtitleEdit/subtitleedit#4320]
In many "complete/full" subtitles (movies and series) had text lines commonly in uppercase format and is used to show names of signs, street names, names, etc., they are called also FORCED subtitles when this lines are in a separate subtitle file; this lines are very helpful when someone is working translating the subs to another language and/or using this translation with another audio language.

Will be useful have an option (preferably in the Edit menu) to filter this lines (uppercase lines), to save then late  in a forced subtitle.

Currently, in version 3.5.16, is possible to: Select all text lines -> [EDIT] Modify Selection... -> Subtract From Current Selection ALL UPPERCASE -> Delete (all other selected lines)

But this method don't take in count Uppercase lines + other format like Bold or Italic, ex:

`1
00:00:30,922 --> 00:00:34,380
<i>N-----X PRESENTA</i>`

I hope this request will be taken into account in future versions.

**Comment by niksedk** [comment]
Thx for the info :)
Latest beta should now ignore tags in Edit - Modify selection - Uppercase:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip

Source code change: https://github.com/SubtitleEdit/subtitleedit/commit/3fe3ab27a611c92fdc07246099e0a5aab12c86c0
