### ISSUE TITLE
Ubuntu 20.04 SE aborts when selecting a video file

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#4321]
Despite having it work some time ago on Ubuntu 19.10, SE how aborts when editing an srt file and selecting Video>Open video file. No error messages, SE just closes.

**Comment by niksedk** [comment]
Any message if you run via mono from terminal?
What video player are you using?

**Comment by shag00** [comment]
Not sure what you mean by run mono from a terminal. I am using mpv.

**Comment by shag00** [comment]
As there has been no recent movement I have raised a bug with mono: [https://github.com/mono/mono/issues/20444](url)

**Comment by niksedk** [comment]
Thx :)

My guess is a lib with a new name/version...

(I've fixed the url in the above post)

**Comment by niksedk** [comment]
OK, after testing a version compiled with dotnet framework 4.7.2 (instead of 4.0) it seems to work better... hopefully:

How does this version work for you? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.17/SubtitleEditBeta472.zip

**Comment by shag00** [comment]
Ah, wonderful video syncing is now working and possible again. The menus for various things are a bit, all-over-the-shop though.

**Comment by niksedk** [comment]
>The menus for various things are a bit, all-over-the-shop though.

A screenshot or two?

**Comment by shag00** [comment]
I cannot take a screenshot as the popup menu disappears as soon as it looses focus so attached is an mkv showing the issue.


________________________________

**Comment by niksedk** [comment]
Cannot see the mkv... email attachments to github comment might not work?

**Comment by shag00** [comment]
try this:
https://1drv.ms/u/s!Ag2UoFuJVGMmmyIp5rdeQBZVDngA?e=Djl9Se

**Comment by niksedk** [comment]
Should be fixed in latest SE
