### ISSUE TITLE
New shortcut needed (a modification of an existing one) "Extend selected lines to next scene change "

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4323]
Hello.
I found a shortcut which is very helpful when making subtitles.
"Extend selected lines to next scene change (or subtitle)".

However, according to some general translating rules, a subtitle cannot end at a scene change, it must end before it.
Usually it is 2 frames gap.

Can you add a new shortcut **"Extend selected lines to next scene change (or subtitle) with a gap"**, please?

It would help a lot and speed up the subtitling process significantly!

**Comment by OmrSi** [comment]
Or maybe add an option somewhere that lets you select which behavior you want...

**Comment by OmrSi** [comment]
@niksedk Can you check the pull request? Is it enough? Do you like where the option is?

**Comment by m0ck69** [comment]
I'll just add that the gap doesn't always have to be 2 frames.
The program should read the gap value from here:

![gap](https://user-images.githubusercontent.com/46628545/91142936-feffd380-e6b1-11ea-9c34-357bcfa81025.jpg)

**Comment by niksedk** [comment]
Beta updated with fix from OmrSi :)
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip
