### ISSUE TITLE
Splitting dialog without dashes remove

### ISSUE THREAD

**Issue by gleaming** [SubtitleEdit/subtitleedit#4331]
The official Russian subtitles guideline indicates that any change of speaker is accompanied by a hyphen.

E.g. subtitles in English:
1
Hi!

2
Hello!

But in Russian:
1
-Hi!

2
-Hello!

The problem is that when you split a subtitle with Right click -> Split, it removes dashes:

1
-Hi!
-Hello!

becomes this:

1
Hi!

2
Hello!

And every time I have to put dashes back manually. Could you add option to not remove dashes from dialogs, when splitting?

**Comment by OmrSi** [comment]
Well, one thing you can do is add a character to the end of line to every line that has a dash.
That way it won't remove the dash.

What I mean is, make:
```
1
-Hi!
-Hello!
```
```
Like this:
1
-Hi!/
-Hello!
```
And that way the dashes won't be removed.

You can do this using Regex like this:
Find what: `(?<=\A-.*)\n` Replace with: `/\n`
![image](https://user-images.githubusercontent.com/20923700/91340156-310f5380-e7e0-11ea-8f1f-1365521d40f2.png)
And when you're done working on the file you can just remove all `/` or any character you use.

@niksedk If you want to add this as an option, I think I might be able to help with that.
Just tell me where to add the checkbox for it and I'll try.

**Comment by gleaming** [comment]
No, please don't suggest such solutions, this is ridiculous :-) The last thing I agree to do is to add temporary foreign characters.

**Comment by OmrSi** [comment]
Well, that's up to you then.
Doesn't mean it's not an easy and valid solution in the absence of any other solution. :)
It's not `ridiculous` to me, and I would use it if I have to.
