### ISSUE TITLE
issue with auto-save & auto-backup

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#4334]
![image](https://user-images.githubusercontent.com/6579818/91503164-c5051c00-e8c1-11ea-9845-8e8c76b9f43b.png)

I think auto-save shouldn't depend on auto-backup timer to run... if auto-backup timer is set to none - so there should be no auto-save?

also for delete after months should independent action...

**Comment by OmrSi** [comment]
But auto-save works even if auto-backup is set to none. 🤔

**Comment by ivandrofly** [comment]
> But auto-save works even if auto-backup is set to none. 🤔

yes, I just find out the auto-save and auto-backup have two difference methods - the problem is in auto-backup, it uses the property which is supposed to be used in auto-save so that make it a bit confusing... I'm currently working in a patch for this!
