### ISSUE TITLE
error: "The variable 'timeCode3' is either undeclared or was never assigned."

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#4337]
when I try to view the Main window (in design mode) in visual studio it shows this error:

![image](https://user-images.githubusercontent.com/6579818/91634610-84a0bd80-e9e9-11ea-9f70-d62c13afb37c.png)

**Comment by niksedk** [comment]
After updating to Visual Studio 16.7 from 1.6.x I get this too :(

**Comment by ivandrofly** [comment]
> After updating to Visual Studio 16.7 from 1.6.x I get this too :(

If you click "Ignore and Continue" it shows the form but I don't know if it's safe though!

**Comment by ivandrofly** [comment]
I think I will close this for now, since is from Visual Studio...

**Comment by niksedk** [comment]
Hopefully it will work again in 16.7.3...

**Comment by moob158** [comment]
16.7.3 update solves the problem ;)
