### ISSUE TITLE
Batch covert is slower that regular sub edit

### ISSUE THREAD

**Issue by Rodark** [SubtitleEdit/subtitleedit#4340]
Hi there. i was curious if this is normal. if i drop one file to ocr its sub, it takes a minute or so. if i drop the same file, just one, in batch converter it takes at least double time. Is this normal? its a fresh install too
im trying to ocr the subs of a whole season and by the time it takes in batch converter, i could have done 2-3 seasons manually...

**Comment by SigHunter** [comment]
same for me. when I batch convert it takes hours for a few subtitles to convert with 0 % cpu load. when I do them manually they are done in under a minute (with about 5 % cpu load..)
no idea what ocr method is used when doing batch, but in GUI I set tesseract 5 and batch has tesseract.exe running. so probably the same ocr mode. 

STE 3.6.0 on a i9-10850K

**Comment by NHellFire** [comment]
I'm seeing this as well (v3.6.0). It's taking several minutes to OCR when using batch. If I do it manually through import, it takes under 10 seconds.

**Comment by n00mkrad** [comment]
This is still a problem.
