### ISSUE TITLE
Different values in subtitles gap

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4342]
Hi.
Why does Subtitle Edit give different values for subtitle gap?
Let's consider a video with 23,976 FPS.

Once the program says that 2 frames gap equals **83 milliseconds:**

![1](https://user-images.githubusercontent.com/46628545/92091618-4df3ea00-edd1-11ea-9e9c-4c7728663b4b.jpg)

but the second time it shows **84 milliseconds.**

![2](https://user-images.githubusercontent.com/46628545/92091639-53e9cb00-edd1-11ea-89bf-aea090f7aea2.jpg)

I know that the difference it extremely small but I still wonder about it.

I think it's beacause in "Apply minimum gap" the FPS is rounded up to 23,98 instead of 23,976.

Well, I'm  not that knowledgeable about this stuff so maybe it's the way it should be.
Can you expalin that to me, please?

**//edit**
Or maybe to avoid confusion, instead of milliseconds SE should use frames as default like EZTitles

![Clipboard01](https://user-images.githubusercontent.com/46628545/91959740-51bc3980-ed09-11ea-8d7a-7d11b7bc0a03.jpg)

**Comment by OmrSi** [comment]
Well, that's because one frame in 23.976 is 41.7 milliseconds, which is rounded up to 42, while 2 frames are

**Comment by OmrSi** [comment]
Well, that's because one frame in 23.976 is 41.7 milliseconds, which is rounded up to 42, while 2 frames are 83.4 which is rounded down to 83.

**Comment by m0ck69** [comment]
Ok, I get it. But look at the screen shots.
I just don't know why 2 frames are 83 millisecods in "Min. gap between subtitles in ms" and 84 milliseconds in "Apply minimum gap between subtitles". Shouldn't it be unified?

**Comment by OmrSi** [comment]
"Apply Min. Gap" uses the value you set as min. gap in the settings.
The label is there just to let you know what one frame equals in milliseconds.

**Comment by m0ck69** [comment]
OK, thx for the explanation.

**Comment by OmrSi** [comment]
Would this be better?
![image](https://user-images.githubusercontent.com/20923700/92145722-5411b700-ee21-11ea-853f-107f373eaac4.png)

**Comment by m0ck69** [comment]
> Would this be better?
> ![image](https://user-images.githubusercontent.com/20923700/92145722-5411b700-ee21-11ea-853f-107f373eaac4.png)

Yes, much better, very clear and not confusing :)

**Comment by OmrSi** [comment]
@m0ck69 I added this in a pull request.
It should available in the next version/beta if @niksedk accepts and merges it.

**Comment by m0ck69** [comment]
@OmrSi Thank you so much for your commitment and help.

btw, could you also express your opinion concerning this issue:
https://github.com/SubtitleEdit/subtitleedit/issues/4344
