### ISSUE TITLE
how to make shortcut work on waveform focus?

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4344]
Hello.
I have assigned a shortcut "move end 1 frame forward" to the key "OemPeriod"  ![Clipboard01](https://user-images.githubusercontent.com/46628545/92089193-1d5e8100-edce-11ea-8c4f-dcca85751abf.jpg)

However, this shortcut works everywhere: in list view and in text box so I cannot type a dot "."

Is there a way to make this shortcut work only when the mouse is on waveform? Or do I need to use a combination with ctrl, alt or shift?

This is strange because for testing I also assigned this shortcut to the "m" key and when the focus is on list view I can normally type "m" (shortcut doesn't work in this case) and when the mouse is on waveform and I press "m" the shortcut works.
And this is exactly what I want.

Why doesn't it work with othe keys like OemPeriod, Oemcomma, OemOpenBrackets etc?

**Comment by OmrSi** [comment]
This is because it is in the code that if the key is between A and Z, do not check for shortcuts if a textbox is focused. It doesn't cover OEMs. I don't know if this is on purpose.

I "fixed" this here https://github.com/SubtitleEdit/subtitleedit/pull/4348 but he'll decide whether to merge it or not. :)

**Comment by m0ck69** [comment]
I hope he will. It doesn't have to be default, the option to turn this feature on/off for those who want it is fine by me.

Anyway, thanks so much for the explanation and help.

**Comment by OmrSi** [comment]
Anytime. <3
We'll see, I guess.
