### ISSUE TITLE
Mimimum gap between subtitles not respected, but still not shown as a warning

### ISSUE THREAD

**Issue by Subtitling** [SubtitleEdit/subtitleedit#4345]
Version 3.5.11 of the tool.
Under settings, one can define the value for the min. gap between subtitles, however, unlike for the rest of parameters, if such value is not respected, no red warnings are shown by the tool, which can be quite confusing.

Has anyone experienced this? Will this be tackled eventually? Thanks in advance for your help!

**Comment by OmrSi** [comment]
You can activate the "Gap" column by right-clicking on the columns and adding it. 
Then the Gap field will turn red if the gap isn't respected.

Also, you should switch to the latest version.

**Comment by Subtitling** [comment]
> You can activate the "Gap" column by right-clicking on the columns and adding it.
> Then the Gap field will turn red if the gap isn't respected.
> 
> Also, you should switch to the latest version.

HI @OmrSi , thanks for your quick reply! I already have the Gap column displayed, however, it does not turn red whenever the gap is not respected, which I found quite weird. I don't know if the problem is linked to the version I'm using and if there is a work-around in place.

**Comment by OmrSi** [comment]
Here is a pic from the latest version.
My min. gap is 833 milliseconds, so when I set it to 832:
![image](https://user-images.githubusercontent.com/20923700/92131879-23c11d00-ee0f-11ea-807d-0a4370aa5879.png)

You should try the latest version.

**Comment by Subtitling** [comment]
Hi again @OmrSi ,
I will give it a go in my personal computer and report afterwards here.
The thing is that my company has version 3.5.11 in many different instances, and the process to update any IT tool is quite lenghty, that is why we try to find work-arounds whenever possible instead of shifting to a different version.

**Comment by OmrSi** [comment]
Sadly, I don't think there is a work-around.
This was not an available feature in 3.5.11:
![image](https://user-images.githubusercontent.com/20923700/92155900-cfc73000-ee30-11ea-9527-552e14ad83a5.png)

But it was added on Dec 25, 2019:
![image](https://user-images.githubusercontent.com/20923700/92156006-fa18ed80-ee30-11ea-912d-2ddf6059a0d9.png)

Via this https://github.com/SubtitleEdit/subtitleedit/commit/2c7333719899ed02fd13542923d53036dbd0de3a
