### ISSUE TITLE
extend sel. lines to previous scene with min. gap

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4359]
Hello.

Lately @OmrSi fulfilled my request and @niksedk added a very helpful shortcut "Extend selected lines to next scene change with min. gap". (https://github.com/SubtitleEdit/subtitleedit/issues/4323)
Thanks once again!

I think there should be also the opposite version "Extend selected lines to previous scene change with min. gap".

When you have time, please add this shortcut as well.

**Comment by OmrSi** [comment]
@niksedk Before I start. Do you want this in SE?

**Comment by m0ck69** [comment]
Yes, the same like here (#4323)

**Comment by OmrSi** [comment]
Done.
Like the last time, he will merge it if he wants it.

**Comment by m0ck69** [comment]
That was fast. Thx so much!

**Comment by OmrSi** [comment]
Anytime.
Well, I have a college exam tomorrow, so... anything to avoid studying. xD
Also, this is more fun.
