### ISSUE TITLE
Can't fix common errors

### ISSUE THREAD

**Issue by ljdssdgOjosdgOsd** [SubtitleEdit/subtitleedit#4363]
Can't use common errors fixer anymore. Why? How do i fix it?
https://imgur.com/a/fWsywXM

**Comment by OmrSi** [comment]
Have you tried the latest version? You're 5 versions behind.

**Comment by niksedk** [comment]
Looks like one of the dictionary files is corrupt. 
You're already running an older version - try to uninstall and install latest version: https://github.com/SubtitleEdit/subtitleedit/releases

Alternately, you could replace the damaged file with a fresh one from https://github.com/SubtitleEdit/subtitleedit/tree/master/Dictionaries

(also, please just paste images)
![image](https://user-images.githubusercontent.com/1261331/92693473-fcee7380-f345-11ea-9596-7bf51d8a9b05.png)

**Comment by ljdssdgOjosdgOsd** [comment]
> 
> 
> Have you tried the latest version? You're 5 versions behind.

I tried but could not get the API to work for translations.

**Comment by ljdssdgOjosdgOsd** [comment]
> 
> 
> Looks like one of the dictionary files is corrupt.
> You're running an older version, so do try to uninstall and install latest version: https://github.com/SubtitleEdit/subtitleedit/releases
> 
> Alternately, you could replace the damaged file with a fresh one from https://github.com/SubtitleEdit/subtitleedit/tree/master/Dictionaries
> 
> (also, please just paste images)
> ![image](https://user-images.githubusercontent.com/1261331/92693473-fcee7380-f345-11ea-9596-7bf51d8a9b05.png)

How do i replace them? Could not find a download button.

**Comment by niksedk** [comment]
You can download a single file at a time... right-click on the `Raw` button, and choose "Save link as..." (firefox)
![image](https://user-images.githubusercontent.com/1261331/92701417-3e841c00-f350-11ea-8d0f-186d0cdf999c.png)

**Comment by ljdssdgOjosdgOsd** [comment]
> 
> 
> You can download a single file at a time... right-click on the `Raw` button, and choose "Save link as..." (firefox)
> ![image](https://user-images.githubusercontent.com/1261331/92701417-3e841c00-f350-11ea-8d0f-186d0cdf999c.png)

Should i do this to every link?

**Comment by OmrSi** [comment]
@ljdssdgOjosdgOsd Can you compress your Dictionaries folder and paste it here so I can take a look?
It should be in `%appdata%\Subtitle Edit` if you're using the installed version.

**Comment by ljdssdgOjosdgOsd** [comment]
> 
> 
> @ljdssdgOjosdgOsd Can you compress your Dictionaries folder and paste it here so I can take a look?
> It should be in `%appdata%\Subtitle Edit` if you're using the installed version.
I tried to replace all the dictionaries but still doesn't work.
[dic.zip](https://github.com/SubtitleEdit/subtitleedit/files/5204342/dic.zip)

**Comment by OmrSi** [comment]
Hmm. I actually went and downloaded version 3.5.11 and the episode you're trying to translate and then translated it to Swedish using Google translate and then used your dictionary files but it worked fine:

Does it happen with all files?
And if so, can you share your Settings file? I don't know if it's relevant but I'm trying to replicate the error here.

**Comment by ljdssdgOjosdgOsd** [comment]
> 
> 
> Hmm. I actually went and downloaded version 3.5.11 and the episode you're trying to translate and then translated it to Swedish using Google translate and then used your dictionary files but it worked fine:
> 
> Does it happen with all files?
> And if so, can you share your Settings file? I don't know if it's relevant but I'm trying to replicate the error here.

Never had that trouble before. Tried another episode but it still doesn't work. I haven't tried many files but i think the same would happen to any file.

**Comment by OmrSi** [comment]
You can find the settings file in the same folder `%appdata%\Subtitle Edit`, compress and send.

**Comment by ljdssdgOjosdgOsd** [comment]
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/5204522/Settings.zip)

**Comment by OmrSi** [comment]
Still working fine here.
Okay, this should clear things out a bit.
This is a portable version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SE3511.zip
Download it and try using FCE with it.

**Comment by ljdssdgOjosdgOsd** [comment]
> 
> 
> Still working fine here.
> Okay, this should clear things out a bit.
> This is a portable version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SE3511.zip
> Download it and try using FCE with it.

What is FCE?

**Comment by ljdssdgOjosdgOsd** [comment]
> 
> 
> Still working fine here.
> Okay, this should clear things out a bit.
> This is a portable version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SE3511.zip
> Download it and try using FCE with it.

![vc2Apb7A](https://user-images.githubusercontent.com/54765920/92882022-d3018380-f40f-11ea-88e0-fdda6fe8f430.png)
Still can't translate.

**Comment by OmrSi** [comment]
I gave you the link to a portable version of 3.5.11 to see if the FCE issue still happens.
FCE is fix common errors.
