### ISSUE TITLE
Google translate Scrape does not translate.

### ISSUE THREAD

**Issue by ljdssdgOjosdgOsd** [SubtitleEdit/subtitleedit#4369]
I am using google scrape because the old translate function stopped running at all. 
The problem is that it doesn't translate properly! It just translates all the ones on the screen and when it goes down it doesn't translate and only put the ones on the previous screen on the ones on the next! 
How do I fix it so it translates everything?

**Comment by niksedk** [comment]
Google translate works fine here with a 1200 lines subtitle.
GT screen-scraper plugins also works fine here with a 1200 lines subtitle

What version of SE are you running?
What version of the GT screen-scraper plugin are you running?
Could you attach some screenshots + subtitle file?
