### ISSUE TITLE
new shortcut "Merge with next and make dialogue (insert dashes)"

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4378]
Another idea for a helpful shortcut.

**"Merge with next and make dialogue (insert dashes)"** Such shortcut would be really useful.

@OmrSi

**Comment by OmrSi** [comment]
Do you want this added @niksedk?

**Comment by m0ck69** [comment]
Thats exactly how I'm doing it now, that's why I came up with a new shortcut that combines those two.

**Comment by niksedk** [comment]
I think it already exists:
![image](https://user-images.githubusercontent.com/1261331/93715512-0cea2c80-fb6a-11ea-9616-84dc5055f083.png)

**Comment by OmrSi** [comment]
@niksedk He means a shortcut the does this without selecting two lines. "Merge dialog with next".

**Comment by OmrSi** [comment]
This is a possible alternative. https://github.com/SubtitleEdit/subtitleedit/pull/4381
If you use "Merge dialog" on one line, it merges it with the next as dialog (If the next isn't null).

**Comment by OmrSi** [comment]
@m0ck69 @niksedk Wouldn't it be better if it actually merges the lines with the previous one?
You usually realize you need the lines to be a dialog after reading the second line, not the first one.

**Comment by m0ck69** [comment]
I like it better when it mergers with the next line.
Merging with previous would also be helpful, no doubt. Why not make two versions of the shortcut?
Let people use the one they find more useful.
