### ISSUE TITLE
insert subtitle causes overlap

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4379]
When I want to insert a new subtitle between two subtitles using shortcut **"Insert new subtitle at video pos"**, it overlaps the next subtitle. No matter where I insert it, it is always 2 seconds long.

![Clipboard01](https://user-images.githubusercontent.com/46628545/93714360-72d2b600-fb62-11ea-8882-eb132582eb46.jpg)

**Comment by OmrSi** [comment]
If you want it to take 833 ms by default, you change it in the settings file from:
`<NewEmptyDefaultMs>2000</NewEmptyDefaultMs>` to what ever you want.
It makes sense to overlap here, IMO. As you are purposely inserting a line in this position.
+ You can just use "Extend line to next scene change or subtitle" to set the end back.

**Comment by m0ck69** [comment]
I think 2 second long is OK but only when there is enought space, otherwise SE should insert max allowed duration with a gap to next sub.
That would be ideal solution to my understanding.
