### ISSUE TITLE
[build] build_helpers.bat fails when git is installed but compiling from zip archive

### ISSUE THREAD

**Issue by agijsberts** [SubtitleEdit/subtitleedit#439]
I ran into a building error when trying to compile SubtitleEdit from the master zip. The problem is that I do have git installed, which returns an error on stderr since it does not find a repository in the current working path. As a result, CommandLineRunner.RunCommandAndGetOutput returns true, but CommandLineRunner.Result is null. This crashes UpdateAssemblyInfo and subsequently the entire build.

I believe the neatest fix would be to check for the exit code of the process (i.e., ```return p.ExitCode == 0;```) at  https://github.com/SubtitleEdit/subtitleedit/blob/master/src/UpdateAssemblyInfo/CommandLineRunner.cs#L32.

**Comment by niksedk** [comment]
Does it work for you now?

**Comment by agijsberts** [comment]
It compiles fine with this fix,thanks. Actually, I should've mentioned in my post that the fix I proposed indeed solved the problem in my case.

**Comment by niksedk** [comment]
cool, thx for verifying :)
