### ISSUE TITLE
Option for joining 2 [or more] subs of dif lang, (time) line by line [request]

### ISSUE THREAD

**Issue by gitut2007** [SubtitleEdit/subtitleedit#4398]
Hi.  Altoug the joining 'in bloc' works with some players, it would be good an option for joining 2 [or more] subs, not only one file after the other, but line by line, eg for 2 dif languages. 
Also, just after performing a translation, have the option 'save both interleaved', with an easy way to change the color/s of each language apart. 
When doing it with different files that don't match exactly the times, SubSplicer has a way: 
http://www.videohelp.com/software/SubSplicer

Thx.

**Comment by niksedk** [comment]
Take a look at the plugins:
![image](https://user-images.githubusercontent.com/1261331/94771611-ede46980-03b7-11eb-84a7-2f0fd50e19fa.png)

**Comment by gitut2007** [comment]
Please consider a srt option; as is now with ass/ssa, offers only top and bottom locations, no 'right one over the other'; putting both like this in a srt, one could move the pair to any wished vertical position in the player.
Now, if i use 'save as' srt, the different for each lang coloring is lost.
Thx.

**Comment by gitut2007** [comment]
Actually, better [option] inputting color just for one lang in the srt, producing not only a smaller file, but getting one lang that would take any color chosen in the player;one might want to change it... 
And having this merging options right there just after an 'Auto-translate' would be super...

**Comment by gitut2007** [comment]
Oh, i see it can be done with a shortcut for "merge original and translation" plus some extra steps, so what is needed is a way to change the color of just the original or just the auto-translated [or both] and  "merge original and translation" without having to do the extra steps to avoid both getting the same color. [and https://github.com/SubtitleEdit/subtitleedit/issues/4412 ] 
Thx
