### ISSUE TITLE
Original subtitles in video player

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4400]
Hello.
I'd like to have original subtitles visible in video player while translating.
I can't find such option in SE.  I'm using mpv.

![1](https://user-images.githubusercontent.com/46628545/94806662-9e6d6000-03ee-11eb-98a5-1e097011b332.jpg)

**Comment by OmrSi** [comment]
There isn't an option to show both subtitles. 
It's either or…

**Comment by m0ck69** [comment]
@OmrSi OK, can you make such option please?
That would be extremely helpful when doing QC but also when working on translation.

**Comment by OmrSi** [comment]
That would be for Nikolaj.
I would assume it needs changes in many places, meaning I don't think I can do it.

**Comment by m0ck69** [comment]
I understand, hopefully @niksedk can handle it.

**Comment by Monovox** [comment]
Hi
You can achieve what you want if you use "direct-show" for the video player under 'settings'. (You may have to install it from k-lite package or similar)
Have both original and translation in folder with the video and name the original file so it comes first, for example myvideo.a.srt for original and myvideo.b.srt for the translation, or more commonly: myvideo.eng.srt and myvideo.iw.srt.
Now when loading your file the player will show the original.
You can get the original subs to appear at the top by loading it, then selecting all lines, then under alignment chose "top center" and save.
Hope this helps.

**Comment by m0ck69** [comment]
@Monovox thanks for the tip, this is a workabout for sure, however, I think mpv is smoother than "direct-show" and works better as a video player.

@niksedk can you express your opinion on this? Are you planning to add such option? Just say yes or no, I will understand.

**Comment by niksedk** [comment]
I don't think this is very important as you can already see the text in the list view, but it not a bad idea.

I've made it possible to load a second subtitle in the video player in latest beta:
![image](https://user-images.githubusercontent.com/1261331/96359319-d3c5bd80-1111-11eb-9040-b9ca3b9fada1.png)

Note that it ruquires libmpv with "mpv handles preview text" disabled or VLC.

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.17/SubtitleEditBeta.zip
