### ISSUE TITLE
Does ReversoTranslate work?

### ISSUE THREAD

**Issue by willian-as** [SubtitleEdit/subtitleedit#4410]
When I try to translate something, nothing is returned:

![teste](https://user-images.githubusercontent.com/20363378/94869137-0e91db00-041b-11eb-8ce4-d37b60199f07.gif)

It goes through to the end that way.

I had created this issue in the Plugins repo but found it better to "recreate" here.

**Comment by niksedk** [comment]
Closed as duplicate (and wrong repro) - see https://github.com/SubtitleEdit/plugins/issues/178
