### ISSUE TITLE
`SubtitleEdit-3.5.17-Setup.zip` entry in Releases wrongly links to `SubtitleEdit-3.5.17.zip`

### ISSUE THREAD

**Issue by darkred** [SubtitleEdit/subtitleedit#4417]
In the [Releases](https://github.com/SubtitleEdit/subtitleedit/releases) tab, for the latest 3.5.17 release,
the `SubtitleEdit-3.5.17-Setup.zip` entry links to `SubtitleEdit-3.5.17.zip`
which doesn't contain SubtitleEdit-3.5.17-Setup.exe, but the following : 
![2020-10-06_201243](https://user-images.githubusercontent.com/723651/95237000-53998100-0810-11eb-84ad-8bf4fb0e0e08.jpg)

In other words, there's no actual `SubtitleEdit-3.5.17-Setup.zip` in the Release assets.

**Comment by niksedk** [comment]
thx :)
Fixed

**Comment by darkred** [comment]
Thanks for the fix. 
And, the new SHA256 Checksum to add 😉: `a1ce7ccfa0172d98421060e9c4511bf63191d27a9815f3a1826857c36278049c`

**Comment by niksedk** [comment]
Hm, I really messed the files up today ;)
Hopefully all is well now :)

**Comment by HRSCR** [comment]
@niksedk  Thanks for look into this
