### ISSUE TITLE
Errors when trying to batch convert and spell check

### ISSUE THREAD

**Issue by nicoleauringer** [SubtitleEdit/subtitleedit#4422]
Hello!

Anytime I try to batch convert or spell check I get these two error messages. Tried uninstalling and reinstalling and didn't help. Next steps?
![IMG_5944](https://user-images.githubusercontent.com/72620925/95607432-57502200-0a21-11eb-93a8-20737ff79905.jpg)
![IMG_5943](https://user-images.githubusercontent.com/72620925/95607458-6040f380-0a21-11eb-960b-c7a05546fc22.jpg)

**Comment by niksedk** [comment]
It looks like your dictionary files are corrupt...
Try uninstalling, and thren press Win+R, and paste `%appdata%\Subtitle Edit` and press enter
![image](https://user-images.githubusercontent.com/1261331/95650053-5a124c00-0ae1-11eb-9301-bc4b85864602.png)

Delete all files and dictionaries in the `Subtitle Edit Folder`

![image](https://user-images.githubusercontent.com/1261331/95650094-8fb73500-0ae1-11eb-9fe4-31b2feed38aa.png)
