### ISSUE TITLE
Several problems with ASS editor preview: impossible to edit accuratley

### ISSUE THREAD

**Issue by Mounter81** [SubtitleEdit/subtitleedit#4426]
Hello!

The issues I've found regrading editing ASS subtitle Styles can be read in this Forum thread from post # 7:
**https://forum.doom9.org/showthread.php?p=1925426#post1925426**

But in nutshell: The Alpha level changes in Shadow or Outline are not displayed accurately (or not at all) in the preview window and it's also impossible to do correct editing while the font size in the preview window is so small. For example, with the PGS editor for the Verdana font the font size is fine with 54 but in the ASS editor I have to set to 16 to get the same size displayed during video playback and that's too tiny to see in the editor's preview window. It means of course, that the PGS editor handles the font sizes much more differently than the ASS editor. Basically the ASS style editor is almost useless this way.

Could these issues be fixed up somehow in SubtitleEdit?

Thanks!

**Comment by niksedk** [comment]
OK, I've tried to improve the ASSA/SSA preview image with regard to alpha level (and especially shadow): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.17/SubtitleEditBeta.zip
How does the above beta work for you?

The font size is normally relative to the window size...

Important note: It's a preview, so do test in your choice of player as the actual result may very a lot from player to player (mpv and mpc do not render alike - previously SE was close to mpc, but now it's close to mpv/vlc).
