### ISSUE TITLE
An application error occurred

### ISSUE THREAD

**Issue by ExYuSubs** [SubtitleEdit/subtitleedit#4432]
Hi Nike, thanks for a nice SE work,
today I have this one error message on my work:

https://prnt.sc/uy1xxt
or
https://i.postimg.cc/L6JK8NFf/9gm-Wsp2-RTZ22nx2osf-Gy8-A.png

can't find in error logg hole text so I send you picture of that
This commin on _**Importing subtitle with manually chose encoding**_

Regards

**Comment by niksedk** [comment]
Could you attach the file?

**Comment by niksedk** [comment]
Could you also try latest beta and see if that works better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.17/SubtitleEditBeta.zip

**Comment by ExYuSubs** [comment]
> 
> 
> Could you attach the file?

Hi Nike, thakms for answer
this is a TS file on 7.98 GiB so .....  don't think I can make that,
on that TS file is 4 different languages, but just on Croatian language I have this error, on other language is no problems at all.

OK, I'll test beta version so I be back about resultate

**Comment by ExYuSubs** [comment]
Thanks Niki, but how to implement that and where?

**Comment by niksedk** [comment]
Download latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.17/SubtitleEditBeta.zip
Unpack to e.g. C:\Tools\SE

**Comment by niksedk** [comment]
Cool, thx for verifying :)

**Comment by ExYuSubs** [comment]
Now there is another problem, the program shuts down after the job is done, I can't even save it  :)

**Comment by niksedk** [comment]
OK, I probably need a lot more info... are you running out of memory? What is happening? What's the progress? etc?

**Comment by ExYuSubs** [comment]
Program reads the entire TS file with all the subtitle info, time, content, gap ect, 
then when the whole process is finished and I press "OK" then the program closes by itself, there is lost of memory so it is not questioned situation ...

Video: https://exyusubs.wistia.com/medias/giqnpk4klj

**Comment by niksedk** [comment]
OK, looks a bit like it's the video player that is crashing... try switching video player to "mpv" or "vlc" - see Options -> Settings -> Video player.

**Comment by ExYuSubs** [comment]
Fixed, Direct Show, MPC-HC and VLC won't work just on MPV lib
thanks once again

Regards

**Comment by niksedk** [comment]
Nice.

It also possible to turn off video auto-load via the setting `<DisableVideoAutoLoading>False</DisableVideoAutoLoading>` in Settings.xml.

If you're using the installer you can find your Settings.xml file via `WinKey + %appdata%\Subtitle Edit`:
![image](https://user-images.githubusercontent.com/1261331/96106241-44cf6000-0edb-11eb-93f5-c205ee467769.png)

**Comment by ExYuSubs** [comment]
working perfect
