### ISSUE TITLE
Cheetah Caption (.cap) export issue when using command line

### ISSUE THREAD

**Issue by batatop** [SubtitleEdit/subtitleedit#4434]
Hello, exporting as .cap format works really well on the Desktop application. However, it doesn't work when I try to export through the command line. I get a .cap file but it has issues. I can't import the subtitle that I exported back to the Subtitle Edit. It would be great if you could make the export available in the command line too. Thank you for your concern.

**Comment by niksedk** [comment]
What is your exact command line?

**Comment by batatop** [comment]
Thank you for your quick response. I tested it on Powershell in Windows 10.

I used: `./SubtitleEdit /convert "<srtPath>" "Cheetah Captions"`

I tried other names other than "Cheetah Captions" but that's the only one that worked without an error. The application generates a .cap file but it has some issues. However, it works flawlessly on Desktop. Thank you for your concern.

**Comment by niksedk** [comment]
I just tried `SubtitleEdit /convert a.srt cheetahcaption` which generates a .cap file that SE can read... perhaps it's a problem with your specific file? Have you tried different files?
I guess I need more info in order to re-produce the bug.

**Comment by batatop** [comment]
@niksedk , thank you for testing it out. I actually tried 2 different files (one in Spanish, one in English). And tried SE to test it out too but if that worked for you, probably I'm missing something else. I'll do more testing and update you. Have a nice day!

**Comment by batatop** [comment]
@niksedk Hello, I just realized that I didn't give an update here. I think it was my mistake, I'm using it on the server so many things could have gone wrong. But I'm working on other things now so I couldn't get it to work yet. Thanks again for your help!
