### ISSUE TITLE
Show both text and original text on video 

### ISSUE THREAD

**Issue by goodju** [SubtitleEdit/subtitleedit#4435]
Is there a way for both subtitles from "text column" and "original text column" to be shown on the video window?
I like to see original text on the video while translating.

**Comment by m0ck69** [comment]
That's exactly what I asked for here
https://github.com/SubtitleEdit/subtitleedit/issues/4400

**Comment by niksedk** [comment]
Closed as duplicate

**Comment by goodju** [comment]
Sorry about that. I wasn't aware.
