### ISSUE TITLE
Fix common errors - Need add dash in dual dialogues

### ISSUE THREAD

**Issue by kimphatcr** [SubtitleEdit/subtitleedit#4443]
Hi there,
My almost file got this issue that the translator just add one dash to a dual dialogue. 
for example:
What's going on here? -Help!

Usually I will fix this problem with SE but in recent updates, it seems like SE don't have this option.
I used shortcut Toogle dash or something but it kinda useless in my case.
Hope you could give me some ideas to fix this issue. Thank in advance.

**Comment by niksedk** [comment]
Hi @kimphatcr,

You need to use "Fix dash in dialogs via style":

![image](https://user-images.githubusercontent.com/1261331/96363601-bacf0380-1135-11eb-8502-7e101ef9a76a.png)


![image](https://user-images.githubusercontent.com/1261331/96363592-b0146e80-1135-11eb-9a0d-505e3f58a0ea.png)

You can control you settings in Options -> Settings -> General: Dialog style
![image](https://user-images.githubusercontent.com/1261331/96363635-e7831b00-1135-11eb-9c34-a13887271876.png)

**Comment by kimphatcr** [comment]
Hi there, thanks for your support but maybe you got me wrong, and also I applied this option but nothing changes.
I want to fix this one line dialogue sub like this

What's going on here? -Help!

will be like this

-What's going on here?
-Help!

Both lines apply dash.

**Comment by niksedk** [comment]
Ah, in the main windows list view, press ctrl+a (select all lines), press the "Auto br" button, and then do the "Fix common errors"

**Comment by kimphatcr** [comment]
Oh, thank you so muchhhhh, that works, but just affected some subs.
For illustrate, this is the original file
![image](https://user-images.githubusercontent.com/73057820/96399725-41004e00-11f9-11eb-94bf-3b8f80724ca3.png)
And this is the results when I applied 2 options that "Fix dash in dialogs via style" and "Fix dialogue in one line" (I can't find "Auto br" options, just options Remove line break for selected lines)

![image](https://user-images.githubusercontent.com/73057820/96399986-db609180-11f9-11eb-8d0f-f40c60f7b9bb.png)

Well, not sure why it happened like that but at least this fixed some lines ^^

**Comment by OmrSi** [comment]
That's because these lines don't have line endings.
A sentence should have a dot or a question mark or an exclamation point to be considered as "Can be dialog".
Try changing `Okay, Doc - Okay.` to `Okay, Doc. - Okay.` and see how it works.

**Comment by kimphatcr** [comment]
Wow, thank you so muchhhh! It works!! But I noticed that the function "Fix dialogue in one line" just affected with the full stop, so plz check this. My issue solved ^^ thank you so much
