### ISSUE TITLE
Original subtitles in video player v2

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4444]
With reference to https://github.com/SubtitleEdit/subtitleedit/issues/4400
The topic is closed and I don't know If I such topics are monitored so I created a new one.

Thank you so much @niksedk for adding this option.

However, I feel like a little of customization is needed. 
Basically two things are missing: changing the font of original subtitles **(especially the size)** and the **placement** (it would be perfect solution If we could drag the subtitles and put them whenever we want on the video).

Now original subs and translation are too close to one another and it doesn't look good.

I'd like to have the original subs on the top but If sb else doesn't like it, they should be allowed to put them whenever they want.

Please look the the photos below:

![Clipboard01](https://user-images.githubusercontent.com/46628545/96365772-2bc8e800-1143-11eb-94bc-e33dab129b52.jpg)

![94806662-9e6d6000-03ee-11eb-98a5-1e097011b332](https://user-images.githubusercontent.com/46628545/96365789-4d29d400-1143-11eb-99e1-1ca323481ad5.jpg)

**Comment by OmrSi** [comment]
I think this is not possible right now because he's not using MPV to handle the text.
Since MPV isn't handling the text, you can't change the font or the size or the place.
It might be a little tricky to make MPV handle two subtitles, or he would have done it in the first place.

Just letting you know what I think. :D

**Comment by m0ck69** [comment]
What handles the size and placement then? @niksedk original subs are smaller than mine and look slightly better.


![Screenshot](https://user-images.githubusercontent.com/46628545/96366088-9bd86d80-1145-11eb-87c4-c76a5663dcc3.png)

**Comment by niksedk** [comment]
The subtitle at the bottom is displayed via a text label inside SE by SE.
The top one is displayed on the video by the video mpv/vlc player... if you put `{\an8}` on a line it will actually display on top.
(the above functionality has been requested by another user... when I first added mpv it auto-loaded subtitles - like directshow will also do if you have directvobsub installed. Some people likes this even though it's not on purpose).

**Comment by OmrSi** [comment]
@niksedk Can't something be done with MPV's "--secondary-sid=<ID|auto|no>" option for example?
I haven't seen how SE works with MPV, that's why I'm asking.
