### ISSUE TITLE
mkv with embedded subs

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4447]
When I open mkv video with embedded soft subs, they appear on video.
How do I turn them off in SE?
Or maybe do I need to mux them out and import a "clean" video?

**Comment by OmrSi** [comment]
They go away as soon as you add a line, don't they?

**Comment by m0ck69** [comment]
No, they don't.

**Comment by OmrSi** [comment]
Here is a video showing what happens here:
![Untitled Project](https://user-images.githubusercontent.com/20923700/96622024-12c26180-1312-11eb-9324-f42248bdc500.gif)

As soon as I add a line, the soft sub disappears.

**Comment by niksedk** [comment]
I've trouble re-creating this... what steps are needed?

**Comment by m0ck69** [comment]
try this video example: https://we.tl/t-Ap7hTAH1tD

**Comment by OmrSi** [comment]
Ah, got it.

@niksedk You need to turn "MPV handles preview text" off.

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
