### ISSUE TITLE
subtitle edit 3.5.17 API Key

### ISSUE THREAD

**Issue by Hafidzgtg** [SubtitleEdit/subtitleedit#4449]
![image](https://user-images.githubusercontent.com/50311982/96753269-ceaa8c00-13f9-11eb-81c9-fe05ab6a51e0.png)

![image](https://user-images.githubusercontent.com/50311982/96753352-f4d02c00-13f9-11eb-9ea7-13b358642c82.png)

how ?
help me.. where do I get the API key ?

**Comment by OmrSi** [comment]
https://www.nikse.dk/SubtitleEdit/Help#translation

**Comment by Hafidzgtg** [comment]
is it a monthly API subscription?
