### ISSUE TITLE
Multiple Replace Shortcut Not Working (Ctrl+Alt+M)

### ISSUE THREAD

**Issue by ddelella** [SubtitleEdit/subtitleedit#4452]
Starting with version 3.5.17 the Multiple Replace shortcut key combination no longer works.  It opens when selecting form the menu.  I am using Windows 10 18363.1139.

**Comment by niksedk** [comment]
Sorry, I cannot re-produce this... are anybody else having this problem?

**Comment by OmrSi** [comment]
I am not.

**Comment by niksedk** [comment]
@ddelella: Perhaps you can attach your Settings.xml file as a .zip file - it could be conflicting shortcuts. You can also try to "Restore default settings".

**Comment by borifax** [comment]
For me it works as CTRL + ALT + M and CTRL + M.
W7

**Comment by ddelella** [comment]
This is still an issue.  Just updated to 3.5.18 and restored default settings.  Still does not work.  I tried both CTRL+ALT+M and CTRL+M.  The other two primary shortcuts I use work fine for CTRL+SHIFT+H and CTRL+SHIFT+F.  For some reason the multiple replace does not work.

![multiple-replace-1](https://user-images.githubusercontent.com/548747/99296526-e9afc680-2814-11eb-9c72-30fd3098c9cf.png)

**Comment by OmrSi** [comment]
> @ddelella: Perhaps you can attach your Settings.xml file as a .zip file - it could be conflicting shortcuts. You can also try to "Restore default settings".

**Comment by ddelella** [comment]
I said, I did a default settings restore.  GitHub says it does not support XML upload type.

**Comment by ddelella** [comment]
Did a default restore but here is the xml.

[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/5549121/Settings.zip)

**Comment by OmrSi** [comment]
My bad. I thought you did a clean install and restored your own settings.

@niksedk I still can't re-produce this.
