### ISSUE TITLE
Offset and length were out of bounds for the array

### ISSUE THREAD

**Issue by chcip2003** [SubtitleEdit/subtitleedit#4453]
Hi!
I received this error in binary image compare ocr method with File/Import images jpeg files.

Error mesage: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.

**Comment by niksedk** [comment]
Thanks for the info.

I will probably need some more info though. 
Did the error message also contain a stack trace?
Could you supply (link/attach or email) the images + your "OCR" folder?

**Comment by chcip2003** [comment]
Ok. I get the same error with binary image compare and nOCR.
![S-Edit Error via Binary](https://user-images.githubusercontent.com/73392822/97119318-17bf5080-1718-11eb-8e1a-52def0dad8c5.png)
![S-Edit Error via nOCR](https://user-images.githubusercontent.com/73392822/97119326-1db53180-1718-11eb-9bc0-4689aeb4f156.png)

**Comment by niksedk** [comment]
Thx for the details 👍 

OK, SE now supports larger images in OCR:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.17/SubtitleEditBeta.zip

You'll probably need to setup image pre-processing with "inverse colors":
![image](https://user-images.githubusercontent.com/1261331/97128111-c0cb7280-173b-11eb-9383-22e54880220f.png)

Tesseract 5 is also worth a try.

**Comment by chcip2003** [comment]
Thank you a lot!
