### ISSUE TITLE
Text size in windows, problem returns

### ISSUE THREAD

**Issue by Monovox** [SubtitleEdit/subtitleedit#4454]
The problem with text size within boxes when using lager text in windows display options is back in ver 3.5.17 and the beta.

**Comment by niksedk** [comment]
Could you tell more about the problem?
How was it fixed earlier? 
A screenshot would also help :)

**Comment by Monovox** [comment]
Hi niksedk
For whatever reason I couldn't attach the screen shots. I still can't. Related issue #4207 had a picture of one of the panels.
When choosing lager text in windows display options (125% in my case), the char size in the boxes becomes too large for the box size. This was fixed, as seen in that screen shot of ver 3.5.15, but reverted in the last update.
I will try to post the pics again, maybe using a different browser.
Thanks

**Comment by Monovox** [comment]
Here they are:
![Display options](https://user-images.githubusercontent.com/66067219/97323799-d3e45c80-1879-11eb-9618-039e95d0998b.jpg)
![ver 3 5 16](https://user-images.githubusercontent.com/66067219/97323825-da72d400-1879-11eb-8d5c-dcdbbb16e792.jpg)
![ver 3 5 17](https://user-images.githubusercontent.com/66067219/97323847-df378800-1879-11eb-83c0-a55de1cbe66f.jpg)
