### ISSUE TITLE
Removing HI removes characters from the beginning of subtitle

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#4458]
The original subtitle:
```
45
00:05:13,855 --> 00:05:16,691
{\an8}WINSTON CHURCHILL [ON RADIO]:
<i>--as to the youth of all the Britons,</i>
```

The result is:
```
45
00:05:13,855 --> 00:05:16,691
{\an8}<i>as to the youth of all the Britons,</i>
```

It takes those two characters off the beginning of the subtitle.

**Comment by vinodthebond** [comment]
{\an1} to {\an8} are subtitle alignment tags, not the hearing impaired tags.  To remove these load subtitle file, select all subs, right click>>remove formatting>>remove alignment option

**Comment by Boulder08** [comment]
I'm not looking to remove the alignment. The correct result after HI should be

`45
00:05:13,855 --> 00:05:16,691
{\an8}<i>--as to the youth of all the Britons,</i>`

**Comment by vinodthebond** [comment]
Try Tools>Remove text for hearing impaired>deselect { } >>Apply

**Comment by Boulder08** [comment]
No effect. SubtitleEdit correctly ignores the alignment tags when considering hearing impaired parts already.

**Comment by vinodthebond** [comment]
There are other options on screen. You can do select options as per your requirement

**Comment by Boulder08** [comment]
Yes, I am aware of those, being a long-time user of SE. They do not affect the output because the problem probably is not HI detection but some slight cleanup issue. It could well be intentional for all I know.
