### ISSUE TITLE
[Request] Difference between number of subtitle lines and selected line

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#4459]
Is it possible put the difference between the total number of subtitle lines and the selected line on the bottom right corner?
This way, we could know how many lines still needs to be translated.
Thank you.

**Comment by OmrSi** [comment]
Can't you just use `control + shift + I` to inverse the selection and let you know how many lines aren't selected?

**Comment by Andrebavila** [comment]
OMG. Sorry.
I didn't even think about it.
My bad.
Thank you very much.
