### ISSUE TITLE
Removing words after </ br>

### ISSUE THREAD

**Issue by mkchantony** [SubtitleEdit/subtitleedit#4463]
Hi
I want to remove all the words after the tag </ br>, how can I remove them?

Like:

ABCDE</ br>FGH
to
ABCDE

**Comment by borifax** [comment]
ctrl+h
Find what: <(.)+
Replace with:
Check "regular expression"

**Comment by borifax** [comment]
ctrl+h
Find what: <(.)+
Replace with:
Check "regular expression"

**Comment by OmrSi** [comment]
@borifax That's not a good expression. 
You have to be more specific, this will cause him to lose normal tags that are in the file, let alone that there is no need for the capturing group, and it will not work for events with more than one line. 

`</br>[\S\s]*` or `\s*</br>[\S\s]*` in case you also want to remove white space characters before it.
This should work for all cases.

Now, the </br> that show up in SE aren't actually there, it's just a way to indicate a new line, so you have to keep that in mind, meaning your file has to have this tag written out.

**Comment by niksedk** [comment]
Do try Edit -> Multiple replace, as you get a preview:
![image](https://user-images.githubusercontent.com/1261331/97702856-f790e800-1aaf-11eb-8f5b-b6dfd47f0466.png)

**Comment by OmrSi** [comment]
@niksedk That wouldn't work for events with more than 2 lines, though.
In case he has events with more than 2 lines, that is.
`\n[\S\s]*` would just remove the first line break and everything after it.

**Comment by niksedk** [comment]
@OmrSi: yes, three lines requires your regex `\s*\n[\S\s]*`:
![image](https://user-images.githubusercontent.com/1261331/97705694-c7981380-1ab4-11eb-9563-6fa9e0999aa4.png)
