### ISSUE TITLE
New line mistakenly capitalized

### ISSUE THREAD

**Issue by nogitbit** [SubtitleEdit/subtitleedit#4467]
Hi, I'm using Subtitle Edit to convert PGS subtitles to SRT so my TV can play them.  I run into this weird format of PGS where the lines are repeated every 300ms.  It works fine except when Subtitle Edit auto capitalize letters on a new line.  See the screen shot below.

I saw a similar issue https://github.com/SubtitleEdit/subtitleedit/issues/4062 and tried using the suggested Binary image compare OCR option, but this is still happening.  Is there an option to turn this auto capitalization off?

![Capture](https://user-images.githubusercontent.com/72414228/97793512-3c994500-1baa-11eb-9d58-057dcb02d71a.JPG)

**Comment by OmrSi** [comment]
What about using Tools -> Merge lines with same text?

**Comment by nogitbit** [comment]
Hello, thanks for the workaround.  I tried that out, and it worked very nicely.  No more distracting case switching in the subtitles.  Thanks!

**Comment by OmrSi** [comment]
Great. You got it!
