### ISSUE TITLE
Cannot change play rate

### ISSUE THREAD

**Issue by Martina2991** [SubtitleEdit/subtitleedit#4471]
![IMG_20201102_205826](https://user-images.githubusercontent.com/73852817/97913126-2d52fc80-1d4e-11eb-80d1-5031be2aedb3.jpg)

**Comment by OmrSi** [comment]
Does it happen every time you try to change the play rate? Are there certain steps to recreate this? Does it happen with a certain video?

**Comment by Martina2991** [comment]
> Does it happen every time you try to change the play rate? Are there certain steps to recreate this? Does it happen with a certain video?

It happens every time, in every video, on multiple computers. It worked up until about two hours ago. I've tried downloading several previous versions of the program - nothing changes. I use the shortcut below waveform to change play rate.

**Comment by Martina2991** [comment]
I don't know if it will work for everyone, but I fixed the problem by choosing mpv player in settings (I had DirectShow chosen previously).

**Comment by OmrSi** [comment]
@niksedk I couldn't replicate this even when I have DirectShow on. Might be because I'm using LAV filters?

@Martina2991 It should work for everyone with MPV. MPV is the best player for SE.
