### ISSUE TITLE
Duplicate spell check shortcut.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#4476]
Hello.
"Skip all" and "Undo skip all" have both the same hotkey : the underlined s.

**Comment by OmrSi** [comment]
It's actually not. The text is just moved there without getting changed but using `Alt + S` will always get you skip all.
Try using skip one and you'll see what I mean.
The shortcut for undo is `Control + Z`.

**Comment by lambdacore12** [comment]
Thanks! Now it's clearer.
