### ISSUE TITLE
Delete shortcut does not accept modifier keys.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#4477]
When I want to change the shortcut for "Column Delete text", it does not allow modifiers (alt, shift...)

**Comment by OmrSi** [comment]
It's working here:
![image](https://user-images.githubusercontent.com/20923700/98365514-389e7480-203b-11eb-9ee1-0a4548e1502f.png)

Are you trying a specific combination that I can test? Can you attach a photo of what happens?

**Comment by lambdacore12** [comment]
As soon as I pick a key modifier, 
![greyed out](https://user-images.githubusercontent.com/37704802/98365799-3d5f2a80-2033-11eb-9b4d-bf383d23a7c7.png)
Update gets greyed out."

**Comment by OmrSi** [comment]
Ah, you need to set a key as well. You can't just use a modifier.
Set a key with the modifier and it will no longer be greyed out.

**Comment by lambdacore12** [comment]
I see it works with modifier + key, but it won't work with modifier + delete. Is that normal?

**Comment by niksedk** [comment]
Yes, that is how it works for shortcuts.
Shortcuts not in menus are a bit more flexible and can be a key only, but it's of course a bad idea with a shortcut "a" in a text box as it will block the typing "a".

**Comment by OmrSi** [comment]
@niksedk "Control + Del" should still work.

**Comment by lambdacore12** [comment]
@OmrSi  Just tried it, doesn't work.

**Comment by OmrSi** [comment]
Okay, so I just noticed that the "del" shortcut doesn't work with anything.
The key name is "Delete" so "Del" isn't recognized.

This should fix it https://github.com/SubtitleEdit/subtitleedit/pull/4482

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.17/SubtitleEditBeta.zip
