### ISSUE TITLE
Auto replay video.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#4478]
Hello,
This is not an issue per se, but is it possible yo make it so that when end of video is reached, when we click play (or use according shortcut), the video starts playing from beginning.

**Comment by OmrSi** [comment]
Isn't that what this is for?
![image](https://user-images.githubusercontent.com/20923700/98429968-bf426880-20b2-11eb-9327-adf6cbea70b7.png)

**Comment by lambdacore12** [comment]
Is there a shortcut for it? And can it be automated?

**Comment by OmrSi** [comment]
@niksedk Should be closed via: https://github.com/SubtitleEdit/subtitleedit/commit/bfa1905f39b638f8b817261ebdc11945ee9db9ea

**Comment by niksedk** [comment]
Ah yes, thx :)
