### ISSUE TITLE
Spell check completion message.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#4479]
There is the option to not show the spell check report (at the end of a spell check), but there is a problem if no spelling mistakes were found : if we press the spellcheck button, it seems is if nothing happened. Can you show like a little message that disappears after showing the spell check was complete?

Thank you for SE!

**Comment by OmrSi** [comment]
You get this in the status bar, which shows up for about 10 seconds:
![image](https://user-images.githubusercontent.com/20923700/98364648-d133f500-2039-11eb-8986-ca3f48c74262.png)

**Comment by lambdacore12** [comment]
Ouch, completely failed to notice that as it is very small! Thanks Omar!
