### ISSUE TITLE
Auto duration to "push" start of next subtitle.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#4480]
When setting the auto-duration for a subtitle, sometimes the next subtitle is too close and the so it "stops" the current subtitle from reaching the desired duration. Can you make it so that the start of next subtitle can move further to allow this?
I think this problem is solved when using "fix common errors", but is it possible to do it manually?
Thanks!

**Comment by OmrSi** [comment]
I believe SE, in general, doesn't affect the start time. This applies to all tools.

**Comment by lambdacore12** [comment]
No, I think it does, remember "Fix short display time : Allow move of start time" in tools? I was just hoping it could be implemented during editing.

**Comment by OmrSi** [comment]
Yes, I said in general, this is a special case. :D
Anyway, we'll see what the developer thinks.

**Comment by raidsan** [comment]
I think it should add a function to support the usually used operate, which extend  current selected line duration,  and sync  push the next all forward lines time later.
Currently,  we can only doing this through menu item: Synchronization\Adjust all times,  then enter times in the popup menu and let it "show later",  but this is not inconvenient.

And on wave graph window,  we can do two action:
1. press shift + left mouse button press to move  current select line block to move  right and overlap with next line,  
2.  or,  press alt + drag the block end time line,   this can change current  block longer (shorter) and next block shorter (longer).
the two action is not we usual need.

suggestion:
1. press  ctrl+ move select block rigth,  if it will overlap the  next block,   then all forward line block time will all sync push later
2. press ctrl + drag block end time line,  if it will overlap the  next block,  do the same as 1.
