### ISSUE TITLE
auto load ass styles

### ISSUE THREAD

**Issue by z3us** [SubtitleEdit/subtitleedit#4483]
Hi
Is it possible that the program load automatically my ass styles file at the start?
Thanks

**Comment by niksedk** [comment]
I'm not sure what you mean... could you explain a bit more?
SE loads styles when opening an ass file.

**Comment by z3us** [comment]
When I want to assign styles in a ass file, I only have the default style. Then I have to go to the import button, search my styles file and load it. I want my styles yo be automatically imported in the program

**Comment by niksedk** [comment]
OK, how many "saved styles" would you normally need? 
GUI suggestions are welcome :)

**Comment by z3us** [comment]
It would be enough if the program just remembered the previously imported styles

**Comment by niksedk** [comment]
Style storage implemented in latest beta with @LeonCheung design:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by z3us** [comment]
> Style storage implemented in latest beta with @LeonCheung design:
> https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

And how does this feature solve my issue? I still have to reload my styles each time I open a subtitle

**Comment by niksedk** [comment]
So a solution could be an option to load the styles from the "style storage" automatically to new .ass subtitles?

**Comment by z3us** [comment]
Yes, as soon as u open an ass subtitle file, have the styles available

**Comment by ChocOranger** [comment]
It would be even better to have the "style storage" available when working with .ass files rather than just on load.
eg when switching format from .srt to .ass
Basically load "style storage" on program load - it shouldn't impact non-style users.

Additionally, and you might consider this a separate issue, but since you are looking at .ass styles, the style GUI does not contain nor save the following values which are in the .ass style header:
Spacing (this is so useful)
Scale X% / Y%
Angle

As it is, loading "style storage" will lose these values.

**Comment by LeonCheung** [comment]
@z3us To be honest I don't quite agree with that idea. Styles should be project-based. Most people don't want to auto-load extra styles they don't expect. Say, someone has 100 styles in the storage, is it really cool to auto-load all of them into the current project???

Your idea makes sense only when working on projects that are quite similar to each other. Imho, the only workable solution would be to implement kinda **Autoload Style List** separately (or, to define styles as auto-load ones by toggling them from the Storage table. For that, we may need a separate column). Not sure if it is worth doing though...

**Comment by niksedk** [comment]
New .ass files could get the styles from "style storage" ? (perhaps a "default" check box in storage styles... perhaps not?)

It's probably a bad idea to auto load "style storage" for existing .ass files... right?

**Comment by z3us** [comment]
> t the styles from "style storage" ? (perhaps a "default" check box in storage styles... perhaps not?)
> 
> It's probably a bad idea to auto load "style storage" for existing .ass files... right?

Yes, that would be nice. Or you can add an option to select a .ass styles file that you want to be auto-imported every time


> @z3us To be honest I don't quite agree with that idea. Styles should be project-based. Most people don't want to auto-load extra styles they don't expect. Say, someone has 100 styles in the storage, is it really cool to auto-load all of them into the current project???
> 
> Your idea makes sense only when working on projects that are quite similar to each other. Imho, the only workable solution would be to implement kinda **Autoload Style List** separately (or, to define styles as auto-load ones by toggling them from the Storage table. For that, we may need a separate column). Not sure if it is worth doing though...

I have now a folder with 52 subtitle files of a tv show that I want to use to create dual-language subs with ass subtitles. Not having to load the styles every time would be really great for me

**Comment by LeonCheung** [comment]
In that case, a quick and dirty way is to use regex in tools like notepad++ to batch add styles into those files in a few seconds.

**Comment by z3us** [comment]
> In that case, a quick and dirty way is to use regex in tools like notepad++ to batch add styles into those files in a few seconds.

Probably every feature of subtitle edit can be replicated using notepad ++, but I don't think it's the best way

**Comment by ChocOranger** [comment]
>@LeonCheung  Your idea makes sense only when working on projects that are quite similar to each other. Imho, the only workable solution would be to implement kinda **Autoload Style List** separately (or, to define styles as auto-load ones by toggling them from the Storage table. For that, we may need a separate column).

Aiegsub uses an excellent system with a Styles Manager whereby styles can be added to categories and styles can be loaded by choosing a category. A system like this would be excellent. The 'Default' category should always be loaded and others can be chosen by 'project'.
Well worth a look at how it's implemented.

**Comment by LeonCheung** [comment]
@ChocOranger The Styles Manager feature has been recently improved a lot, you can do the same thing in SE too, even easier, since SE provides an all-in-one panel to manage them, while in Aegisub you have to click Edit or double click every time when you want to edit one style. Just try it. :)  

As for the "Default" category, I think we are on the same page, similar to the **Autoload Style List** I mentioned. Let's brainstorm a bit here and try inspiring the dev, I guess your idea could be like this:

![storage-new](https://user-images.githubusercontent.com/494788/104153257-d851f780-541c-11eb-8a46-bb740ea6eb0f.png)

**Comment by ChocOranger** [comment]
@LeonCheung I understand the Style Manager in SE ;)
Thanks for the mock up but I feel it doesn't make it clear which styles are being used by the current script.

The Aegisub version is much clearer and has more functionality.  Adding 'Properties' to the side of its version would, in my opinion, be a better solution (although a modeless window for editing is even better so styles can be compared imo).

Aegisub's solution is smarter than it first looks. Have a play and you'll see what I mean.

**Comment by LeonCheung** [comment]
@ChocOranger Actually the mockup should be proposed for the Style Manager Improvement Version 2, which benefits a true project-based workflow, just thought it could possibly be helpful to this topic.  Anyway, just trying to help. :)

**Comment by z3us** [comment]
That improvement would be great

**Comment by niksedk** [comment]
Default profile can now be made in the ASSA style manager:
![image](https://user-images.githubusercontent.com/1261331/108590612-be34fe80-7364-11eb-978c-32eb11f3ce0f.png)

Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

Also "ASSA attachments" has been added + "categories in ASSA style manager".

**Comment by niksedk** [comment]
@ChocOranger: How does latest beta work regarding categories (and attachments)?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by ChocOranger** [comment]
Nice work.
Works as expected and is clear on which styles are which ie current file or storage.

Suggestions / bugs

When adding to storage and the 'Style' already exists, I suggest adding a confirmation dialogue.
Likewise, categories can contain styles with the same name, so when adding, I suggest adding a confirmation dialogue. 

The 'Remove All' button is only available when a style in the opposite panel is selected.
Buttons should only be available when a style is selected and the button will affect that Style. Currently there's no confirmation for deleting a style in the the opposite pane.
It's not possible to select more than one style to add to a document / remove 
It's not possible to select more than one style to export, although a selection is given in the export dialogue.
Can't overwrite an exported file.

As per issue https://github.com/SubtitleEdit/subtitleedit/issues/4701 Some style elements aren't preserved.
