### ISSUE TITLE
More than 2 points in Visual Sync [f. request]

### ISSUE THREAD

**Issue by gitut2007** [SubtitleEdit/subtitleedit#4488]
Although it usually works with the 2 points, in some cases many extra adjustments are needed; if in Visual Sync were possible to use more than 2 points [like what exist in Point sync via other subtitle], in just 1 operation [or 2: 1st with 2 points, sync, then add some extra inner points, final  sync] it would be a lot more convenient. 
Thx.

**Comment by niksedk** [comment]
We have "Sync - Point sync.." for this...
