### ISSUE TITLE
Alt + OEM 5-7 + OEM brackets shortcuts don't work

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4490]
Hello,
This issue started in 3.5.17 and I switched back to 3.5.16. I have shortcuts set to Alt +OEM 5 (Set end, start next, go to next), Alt + OEM 7 (Set start time), Alt + Oem6 (Set End time) and Alt + OEMOpenBrackets (Set start, keep duration). Since 3.5.17, whenever any of these shortcuts are pressed, nothing happens. Tab goes to File. 3.5.18 has the same issue. What's wrong? I won't change the shortcuts as I'm too used to them now. Took me a year to refine the shortcuts to be as efficient as humanly possible. Help!

Thank you. 

![Untitled](https://user-images.githubusercontent.com/28671050/98628342-33417280-2338-11eb-80da-ef25052dbdee.jpg)

**Comment by OmrSi** [comment]
Can you attach you settings file so it's easier to test?

**Comment by uckthis** [comment]
> Can you attach you settings file so it's easier to test?


[Settings.txt](https://github.com/SubtitleEdit/subtitleedit/files/5515957/Settings.txt)

**Comment by OmrSi** [comment]
The problem is that after this PR, you can't open a menu using "Alt + Underlines char".
