### ISSUE TITLE
Export Settings

### ISSUE THREAD

**Issue by nimma-vk** [SubtitleEdit/subtitleedit#4491]
Hi, Just check if there is an option to export settings from SE(installer version) and then import settings when I install SE on a different version.  I know there will be a settings file gets saved in the portable version.  Curious about such an option for installer version.

**Comment by OmrSi** [comment]
Well, you can export the shortcuts from the settings and import them again.
You can also copy your Settings file and just paste it after you install the new version.
But there isn't an option in the installer to import or export Settings.

The Settings file for the installed version is at `%appdata%/Subtitle Edit`, you can copy your settings file from the portable version to this location.

**Comment by vinodthebond** [comment]
Thànks a lot @OmrSi. This should save a lot of reconfiguring. However, a button to export/import from somewhere in the menu would be nicer.

**Comment by lambdacore12** [comment]
@nimma-vk there is also an option to export profiles if you are interested.

**Comment by nimma-vk** [comment]
@lambdacore12 Thank you for pitching in.  I'm already using the export profiles when needed.  The one I suggested/asked was to export whole of the settings.

**Comment by lambdacore12** [comment]
That would be very helpful indeed.

**Comment by Blackbird52** [comment]
This save me a lot of time thank you.
 I had two copy of SE in my Program list, one was very old beside new one, so i uninstall the old one say no to delete setting, but it delete all setting ! and also new SE was uninstalled everything gone. installed again but all setting was gone.
Searched and fiund this, copy mentioned folder from Backup and everything back.
