### ISSUE TITLE
select several subtitles and move them all together

### ISSUE THREAD

**Issue by PaulMoscow** [SubtitleEdit/subtitleedit#4496]
Please add an option with which you can select several subtitles and move them all together either forward or backward.
Now you can select several, but only one moves with the mouse.
I beg you very much! VERY VERY!
Thank you so much!

Sorry for my English

**Comment by OmrSi** [comment]
Settings -> Shortcuts:
![image](https://user-images.githubusercontent.com/20923700/98935315-059d2a80-24ec-11eb-9c48-17500c0c6dbd.png)
