### ISSUE TITLE
How to fix srt files that repeat the line number

### ISSUE THREAD

**Issue by Roysb01** [SubtitleEdit/subtitleedit#4498]
![Captura1](https://user-images.githubusercontent.com/67255950/98970163-3d4ca800-24d5-11eb-8b37-7f277767baaa.JPG)
![Captura3](https://user-images.githubusercontent.com/67255950/98970165-3de53e80-24d5-11eb-8fb2-49ac725cbf4c.JPG)
![Captura2](https://user-images.githubusercontent.com/67255950/98970168-3e7dd500-24d5-11eb-86de-10ab385cb87f.JPG)
[3. Tuning By Harmonics - copia.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/5532024/3.Tuning.By.Harmonics.-.copia.srt.txt)

I would like you to tell me, how can I solve? I have seen it in several SRT files, if it was already contemplated in the application or to be added, because that problem causes the line number of the next subtitle to appear. Attached images

**Comment by OmrSi** [comment]
You can do this: https://regex101.com/r/m84vNf/1

**Comment by uckthis** [comment]
Really don't like people who end a subtitle with "and".  And yeah, regex is the only solution for this.
