### ISSUE TITLE
[BUG] cannot type polish letter ó

### ISSUE THREAD

**Issue by pikopikopikopiko** [SubtitleEdit/subtitleedit#4500]
since v3.17 cant type polish letter "ó" right alt + o 
works fine with 3.16, last two are broken 3.17 + 3.18

**Comment by pikopikopikopiko** [comment]
ok one shortut cause this need to turn off switch original and translation

**Comment by OmrSi** [comment]
What happens in the latest beta?

Do you have a shortcut that uses "Alt + o"?
If you have a shortcut that uses this, you need to change it.
When using "Alt + Something" and it's set to a shortcut, SE now activates that shortcut.

**Comment by uckthis** [comment]
He is right, something is messed up. Open Notepad and then write Alt=Num1 - 9. These are default values: ☺☻♥♦♣♠•◘○. Now do it in SE. All are messed up. It shows a different character every time and all are Chinese. Fix?

**Comment by uckthis** [comment]
I know this because I use many of these as markers. I'll just add a ☺ and then replace it with [laughter] or whatever. It's efficient.

**Comment by OmrSi** [comment]
@uckthis This issue is related to the rich text box itself, it isn't recognizing alt codes…

It works if you uncheck "Use syntax coloring", as it defaults to a normal text box.

**Comment by uckthis** [comment]
Never mind, I have switched back to 3.5.16. That's been the most updated bug-free version so far.

**Comment by uckthis** [comment]
Maybe look into what changed after 3.5.16 that caused this error. If it was working fine before 3.5.17, there has to be a change that caused this; which can be undone. I don't know the ABC of programming, so I'm of no help.

**Comment by OmrSi** [comment]
Hey, @uckthis 

As I've mentioned in my last comment, in the latest betas, a RichTextBox was added to make syntax coloring possible. 
Writing alt codes in that text box is causing them to show up as Chinese characters. 
We do not know the reason behind this yet. 

If you'd like, you can go back to using the old normal text box from Settings -> font, uncheck "Use syntax coloring".

**Comment by niksedk** [comment]
@uckthis: thx for testing and reporting this :)
We do try out new stuff in the beta version even though the beta versions are also pretty stable.

I don't actually know how to fix this... seems that the RichTextBox just randomly switches to some Asian mode.
Any ideas @OmrSi ? 
I guess we could try to find/build some other component for the this syntax coloring... or default to the normal textbox.

**Comment by OmrSi** [comment]
I have been trying to track the cause of this, but I don't seem to be able to.
The strange thing is that if you open a file with Unicode characters, they show up just fine, but writing them inside SE doesn't work.
I'll keep trying, though.

**Comment by pikopikopikopiko** [comment]
@OmrSi no i had not suck a shortcut but this was the closest to my alt + o
switch original and translation was ctrl + alt + o, if I do have this shortcut enabled i cannot make alt + o
