### ISSUE TITLE
es_ANY user word list non-functional

### ISSUE THREAD

**Issue by jdsanchezii** [SubtitleEdit/subtitleedit#4506]
Hello,
I have been running into a consistent roadblock when trying to convert Spanish subtitles. When I try to add words to the [es_ANY] user word list the words are not stored or read properly, rendering the user word list non-functional.

- Subtitle Source: Blu-Ray SUP
- OS: Windows 10 Pro x64 1909 (Build 18363.1016)
- SubtitleEdit: Version 3.5.18 Portable
- OCR Method: nOCR
- OCR Dictionary: [es_ANY]
- Installed OCR Languages: Spanish - España, Spanish - Español Genérico, English (United States)

Steps to Reproduce:

1. Open SubtitleEdit 3.15.8
2. Make sure Spanish OCR languages are installed
3. Open a Spanish Blu-Ray SUP file
4. Select "OCR via nOCR" as the OCR method
5. Set the OCR dictionary to "[es_ANY]"
6. Click "Start OCR"
7. Wait for OCR to complete or stop OCR early
8. Select a word from the "Unknown words" list (note the line number)
9. Click "Add to user dictionary"
10. Select "[es_ANY]" in "Add to user dictionary" pop-up window
11. Click "OK" in "Add to user dictionary" pop-up window
12. Click "Cancel" in main OCR window
13. Re-open the same SUP file
14. Restart the OCR process
15. Find the same line number from the first OCR pass
16. The previously added word should show up in the unknown list again

My Observations:

- I noticed that the "Add to user dictionary" pop-up always says "en-US" above the language selection drop-down control.
![2020-11-14 15_51_37-Add to user dictionary-screenshot](https://user-images.githubusercontent.com/14120980/99159570-48006c00-2692-11eb-8795-9cb3812db9d0.jpg)

- When adding your first unknown word to the Spanish user word list, a new file named "[es_ANY_user.xml" is created, which contains the unknown word(s) added during the OCR process.
Notice the left bracket ("[") prefix. That schema does not seem to exist for any other language user word list file.
Does this suggest the OCR tool is not creating the Spanish user word list file correctly?

- Renaming the above mentioned file to "es_ANY_user.xml" does not solve the problem.
Does this suggest the OCR tool is not reading the Spanish user word list properly?

- A user word list file named "es_MX_user.xml" exists. However, manually modifying that file does not resolve the issue nor does it change the behavior of the OCR Spanish tool.

**Comment by niksedk** [comment]
thx for the info :)
I've tried to fix the "[" issue... is this beta better? 
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by jdsanchezii** [comment]
> I've tried to fix the "[" issue... is this beta better?
> https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
Thanks for the quick response. Unfortunately, the result is still the same. The "[" issue is still present.

**Comment by niksedk** [comment]
@jdsanchezii: thx for testing :)
Another beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
Better?
