### ISSUE TITLE
about "Merge short line (single sentence)"

### ISSUE THREAD

**Issue by drumachine** [SubtitleEdit/subtitleedit#4507]
Hello Nikse,
I can't find "**Merge short line (single sentence)**" unclick choose in "Fix common errors" module.
Where is it?

![SubtitleEdit 3 5 18 b](https://user-images.githubusercontent.com/49017044/99182047-873ac580-2743-11eb-8d5c-972b83fe0978.jpg)

**Comment by OmrSi** [comment]
It's this:
![image](https://user-images.githubusercontent.com/20923700/99184977-890a8600-274f-11eb-8495-b88da8026326.png)
