### ISSUE TITLE
Fix common errors - break long line

### ISSUE THREAD

**Issue by psonnosp** [SubtitleEdit/subtitleedit#4510]
Maybe it's me that's off in my English but in my eyes the breaks that this function makes are off.
Like now when I was editing a text for the movie Patton and SE want to fix the line 

Good God, look at that. Where you going, general?

into

Good God,
look at that. Where you going, general?

And that's how all of the fixes look like for a line with both a comma and a period in it and to me it's better to put the break at the period instead of the comma.

But maybe there are a reason for it to be like this?

**Comment by niksedk** [comment]
@psonnosp: What version of SE are you using?

Your line breaks fine here, so you might need to fix your settings (perhaps reset settings would be wise for you).
You can see the default "Auto br" settings here:
![image](https://user-images.githubusercontent.com/1261331/99198090-9f880000-2796-11eb-82b7-8046d5dfd10d.png)

**Comment by psonnosp** [comment]
I just updated to 3.5.18 and when looking at the settings I found that the 'Break early for comma' was checked. Never had this issue before so either there's a gremlin in my PC or the update somehow changed the behaviour of the setting or whatever.
But unchecking it sorted that out but I now found this instead. Maybe it was there before, don't know.


We're advancing constantly. We're not interested in holding on to anything...

are split into

We're advancing constantly. We're
not interested in holding on to anything...

and

Tell me, general, what do you think of Morocco?

are split into

Tell me, general, what
do you think of Morocco?

Where the 'We're' and 'what' shouldn't be left on the first line, right?

Tried the 'Break early for end of sentence' but that didn't change anything.

**Comment by niksedk** [comment]
This is another issue... but related ;)

You can enable use of the do-not-break-after list:
![image](https://user-images.githubusercontent.com/1261331/99235857-b0685e00-27f6-11eb-992a-f6e6958fd945.png)

Note that people have different opinions regarding this - that's why SE is very configurable :)
Also note, that single line max length is still enforced, and will take precedence over the do-not-break-after list.

**Comment by psonnosp** [comment]
Never noticed it before so thought it was something that had popped up now.

And sorry I don't get how that function would help with the last issue.

I don't want it to not break the line at all, I want it to break the line but not leave a single word hanging on it's own after the comma or period.

Since SE doesn't know how to interpret the text to see the meaning of the words and break the text out of that it should break where it know it's a correct place to break it, by using the commas, periods and maybe the word "and" as a break point. Everything else is more or less wrong if you can't grasp the meaning of the text.

Anyhow, it's never correct (whatever view you have on the whole about this) to leave a single word hanging like in the text in my previous post. Maybe in very long texts where you run out of space but not when there are plenty of room.

Some reading about it https://translations.ted.com/How_to_break_lines
And to quote the above "never break lines after relative pronouns like which, that, who, etc."
