### ISSUE TITLE
publish nuget package for libse

### ISSUE THREAD

**Issue by robertbaker** [SubtitleEdit/subtitleedit#4512]

**Comment by niksedk** [comment]
A readme.md should probably be made for libse with same examples.

Anyway, first should soon be available: 
![image](https://user-images.githubusercontent.com/1261331/99297682-dfa7bb00-2848-11eb-87e2-b296c7758a68.png)

Does that work for you?

**Comment by niksedk** [comment]
Also got the wrong version number ;)
https://www.nuget.org/packages/libse/3.5.8

**Comment by robertbaker** [comment]
Thank you!
