### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by AlexandreMT** [SubtitleEdit/subtitleedit#4513]
1. A noticed that when I use `CTRL + A`, the text box freezes and don't allow to insert any text.
2. The `Total length` below the text box sometimes stops counting
3. I'm not being able to use `Split line at cursor/video position` using a shortcut (CTRL + SHIFT + V), nothing is happening when I try to use it.

My SE version is the latest beta.

**Comment by niksedk** [comment]
OK, hopefully no 3 is fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

I could not re-create 1 + 2 - do you still get those ?

**Comment by AlexandreMT** [comment]
I believe everything is fixed now.

**Comment by niksedk** [comment]
Cool, thx :)
