### ISSUE TITLE
[Feature Request] Casing switcher Shortcut

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4515]
It would be quite efficient to have a shortcut to do EXACTLY what Shift F3 does in MS Office Word, which is, to do loop switch among lowercase, UPPERCASE, or only capitalize the first letter for the word that cursor is located, and/or multiple words in the selection. Thank you!

**Comment by niksedk** [comment]
Good idea: how does this work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
(ctrl+shift+F3 is the default shortcut)

**Comment by LeonCheung** [comment]
Pretty cool, Thanks again!

**Comment by LeonCheung** [comment]
Strange that the latest beta has strange default setting like below, which made it failed by default:

![casing](https://user-images.githubusercontent.com/494788/102640237-244eab00-4195-11eb-9972-25002e885f60.jpg)
