### ISSUE TITLE
MPV detection.

### ISSUE THREAD

**Issue by Achaean** [SubtitleEdit/subtitleedit#4521]
I already have MPV installed. Can I have (at settings) an option to locate it?
(Just like the one, that VLC already have).

**THANKS!!!**

**Comment by niksedk** [comment]
What package exactly? 
Properly not...

**Comment by OmrSi** [comment]
I think he means MPV.exe
But SE works with libmpv…

**Comment by niksedk** [comment]
Sorry, Subtitle Edit requires the `mpv-1.dll` file... and cannot use the `mpv.exe`.
