### ISSUE TITLE
.srt to .scc conversion issue about milliseconds

### ISSUE THREAD

**Issue by batatop** [SubtitleEdit/subtitleedit#4522]
Hello, I'm trying to convert `.srt` to `.scc` using SubtitleEdit. I'm using the app on Windows 10. However, there seems to be an issue with the end times of subtitles. It looks like it's rounding the milliseconds part sometimes. Because of that, sometimes the end time of a subtitle becomes the same as the start time of the next subtitle. And that can cause an overlapping issue.

To explain the issue better, I'll send a screenshot of the issue. I can also provide an example file if you need it. Thank you for your concern :)

Screenshot: [https://ibb.co/DW6JKwQ](https://ibb.co/DW6JKwQ)

**Comment by niksedk** [comment]
Subtitles are always nice as it saves me some time... but I think the read fix solves it: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
Does that work for you?

**Comment by batatop** [comment]
@niksedk , thank you for the quick response! The version that you sent actually changed the timestamps of the subtitle, and I didn't even have to convert the file again with the new version. Both the old and new versions gave the same output when I converted the `.srt` file to `.scc`. However, there is still a slight difference between the timestamps of the `.srt` and `.scc` file. 

If you want to check the files, here is the link: 
[https://www.dropbox.com/sh/8ztkuqi23vcxej4/AAAu9l3Qq0O7DNb9kWEZF-hXa?dl=0](https://www.dropbox.com/sh/8ztkuqi23vcxej4/AAAu9l3Qq0O7DNb9kWEZF-hXa?dl=0)
I included the `.srt` file that I converted from, `.scc` conversion from the old version, and `.scc` conversion from the new version (`.scc` files are identical). It would be great if you could check them out. Thank you for your concern.

**Comment by uckthis** [comment]
SCC doesn't acknowledge any gap lesser than three frames.  So, minimum display time between two subtitles should be at least 130ms. 4-5 frames gap is ideal, though. This is a SCC limitation, not SE error.

**Comment by batatop** [comment]
@niksedk and @uckthis , thank you for the information. This was really beneficial for me. I'll close this issue now.
