### ISSUE TITLE
Error open all file MKV

### ISSUE THREAD

**Issue by PPP142** [SubtitleEdit/subtitleedit#4526]
![STE53 5 18](https://user-images.githubusercontent.com/34751815/99732412-c2305680-2abf-11eb-940a-8e9d6b4345f1.png)

**Comment by PPP142** [comment]
Windows 10 x64
No problem open file.mkv in other program

**Comment by PPP142** [comment]
After reboot my computer, open file MKV it's OK
But the drag and drop does not work

**Comment by niksedk** [comment]
@PPP142: Drag and drop of what from where to where exactly? And what exactly is not working? Does it crash?
Drop an .mkv file on the video window will load the video, dropping an .mkv file in the list view will search for subtitles.
