### ISSUE TITLE
Amazon - Transcribe- Translate API's Features

### ISSUE THREAD

**Issue by drkhateeb** [SubtitleEdit/subtitleedit#4528]
**Hello Dear Developers**
I suggest adding these API's to Subtitle Edit

**Transcribe**

Transcribe is a service allowing you to transform speech to text. 
to use it to get the transcript of the MP3 file. 

**Timestamp generation**
Amazon Transcribe returns a **timestamp for each word**, so that you can easily find a word or phrase in the original recording or add subtitles to video. 

https://aws.amazon.com/transcribe/features/

**Translate**

Translate is a service allowing you to translate text file in different languages.
 to use it to translate subtitle files.

https://aws.amazon.com/en/translate/

I think this //https://github.com/aws-samples/aws-transcribe-captioning-tools// may help

Regards.

**Comment by drkhateeb** [comment]
Time stamp for each word 
![sonix1](https://user-images.githubusercontent.com/161371/99887205-64347800-2c53-11eb-9623-10f4c1a4bc22.jpg)

**Comment by drkhateeb** [comment]
![sonix 00_00_00-00_00_30](https://user-images.githubusercontent.com/161371/99887214-91812600-2c53-11eb-8fc1-d54f8b701cee.gif)

**Comment by Jabe64** [comment]
You will probably be interested in new Beta features see [#1878](https://github.com/SubtitleEdit/subtitleedit/issues/1878)
