### ISSUE TITLE
[Bug report] bilingual split issue in 3.5.18

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4530]
Basically, the end char of the selection in the text box (in the 2nd line of course) will be split into the next new subtitle, which is different and unexpected from what's in 3.5.17. Thanks.

**Comment by LeonCheung** [comment]
In the latest beta, try using the bilingual split tool on a small example below, you'll see what I'm talking about:

```
Try split this line.
一二三四五六
```

**Comment by OmrSi** [comment]
How do I test this exactly?
If I just use the shortcut, I get this:
![image](https://user-images.githubusercontent.com/20923700/101661528-0eccd900-3a51-11eb-9c1c-27d51ad30810.png)

**Comment by LeonCheung** [comment]
@OmrSi Please see #2995 on how to use this magic. :)

**Comment by LeonCheung** [comment]
![1111](https://user-images.githubusercontent.com/494788/101720872-aaa62580-3ae1-11eb-9fe3-34705305899c.gif)
Basically, there are two issues here:
1. cursor position for the non-English line is unexpected. There seems to be an offset.
2. Even splitting with expected selection, the result would also offset.

Both issues occurred for non-English lines.

**Comment by OmrSi** [comment]
Does it also happen when "syntax coloring" is turned off?

**Comment by LeonCheung** [comment]
Ah! You are right, hmm

**Comment by LeonCheung** [comment]
Ah, so that's it, everything works fine by turning it off...

**Comment by OmrSi** [comment]
@LeonCheung Should be fixed now.

**Comment by LeonCheung** [comment]
Thank you so much for the fix,  OmrSi! Closing. All the best.
