### ISSUE TITLE
Auto-split based on <br />

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4531]
Just wondering if there's any tool in SE that can auto-split all/selected subtitle lines into two or more lines at existing break(s) like this:

### Before:
![before](https://user-images.githubusercontent.com/494788/99903880-34907900-2d02-11eb-9b81-673a29085747.jpg)

### After:
![after](https://user-images.githubusercontent.com/494788/99903882-365a3c80-2d02-11eb-88ca-80bc9cc5e7a3.jpg)

It would be a big timesaver when we have to do such a conversion.

**Comment by uckthis** [comment]
File > Import Plain Text > One Line is one subtitle.

**Comment by LeonCheung** [comment]
@uckthis Thanks but that's totally different feature from here, I only need to split at every <br />, in one click, that's all I want. I cannot do it by importing plain text since the timecodes have been done already. 

I mean, Normally, for per subtitle, we need to put cursor at <br />  in the textbox then right click and choose "Split at cursor location", but what if I have thousands of lines to handle? I think it is quite doable since the expected cursor positions are quite clear:, which are all the breaks,

**Comment by cyzs233** [comment]
I'd suggest reopening this issue

**Comment by niksedk** [comment]
Closed with https://github.com/SubtitleEdit/subtitleedit/commit/cf59ed0b0e89a76eac8aeeb7016053ffbd8c672e

![image](https://user-images.githubusercontent.com/1261331/233699582-4e5ed8a5-eef1-467c-a45b-dcf9cf39d08f.png)

**Comment by LeonCheung** [comment]
Nice, thx!
