### ISSUE TITLE
Some lines are not translated when translating with Google Translate

### ISSUE THREAD

**Issue by chorong761** [SubtitleEdit/subtitleedit#4534]
When translating subs with google translate, there's always somewhere near 10-15 lines that are not translated. 

Eng - > Chinese Trad.

Using SE 3.5.18

**Comment by niksedk** [comment]
Please attach a subtitle to test with :)

**Comment by chorong761** [comment]
[view.zip](https://github.com/SubtitleEdit/subtitleedit/files/5585647/view.zip)

**Comment by niksedk** [comment]
OK, I think the lines are merged... I will look more into this.

**Comment by niksedk** [comment]
In latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

You can choose line merge option:
![image](https://user-images.githubusercontent.com/1261331/103912197-476ed980-5107-11eb-924a-d39b1ff26289.png)

**Comment by chorong761** [comment]
Hi, I just updated to 3.6.0 and I still have this issue
