### ISSUE TITLE
Problem with using the backslash (Oem5) as a keyboard shortcut

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#4536]
Hi. 3.5.18 NEXT beta 120, although I think this has been going on for some time (I haven't updated in several months).
My shortcut for "go to next line" is simply the backslash. However, in this version, if I'm in the textbox and I press the key, the result is that I simply type the backslash character. If I change the shortcut into control+Oem5, for instance, it works fine.

**Comment by OmrSi** [comment]
That's because of this: https://github.com/SubtitleEdit/subtitleedit/issues/4344

**Comment by darnn** [comment]
So, is there anything I can do? Only revert to a previous release? I see now that the square brackets (which I also use this way) have also been affected.

**Comment by OmrSi** [comment]
I don't know, TBH.
I mean, it makes sense to want those to be written in the text box, I think.
If you set the OemQuestion to a shortcut, how would you write a question mark?

**Comment by darnn** [comment]
That's true, but presumably one should be allowed to make the decision. The fact of the matter is it's worked out great for me until now with the backslash and the square brackets. I was even thinking of assigning something to the equals sign.

**Comment by OmrSi** [comment]
Well, I'm ready to do whatever @niksedk thinks should be done here…

**Comment by darnn** [comment]
Hey, @niksedk, I hate to bother you, but is there any chance you could take a look at this? I'd love to be able to use the latest beta, but I can't as long as the keyboard shortcuts I've used for years don't work. I'm using a build that's like a year old right now, since that's the last one I have where they do work.

**Comment by niksedk** [comment]
@darnn: How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip ?

You need to change `AllowLetterShortcutsInTextBox`'s value to `true` in Settings.xml.

**Comment by darnn** [comment]
Seems to work well now! Thank you!
