### ISSUE TITLE
remove all timestamps in batch tool?

### ISSUE THREAD

**Issue by babbahotep** [SubtitleEdit/subtitleedit#4538]
Hi, I'd like to convert srt to rich text. I my results I still have timestamps.
```
the data requiring a broad consent #00:00:41-1# rather than anything approximating
fully informed consent. #00:00:44-2# The fact that findings from this
```

Is it possible to remove the #***# timestamps completely?

**Comment by niksedk** [comment]
You can export to custom text format... the bottom export format.
