### ISSUE TITLE
Adjusting Blu-raysup subtitles?

### ISSUE THREAD

**Issue by stianlagstad** [SubtitleEdit/subtitleedit#4539]
Thank you very much for SubtitleEdit. I'm trying to get from a .srt subtitle file + a .ts video file => a .ts video file with a dvb_subtitle.

My .srt:
```
1
00:00:00,000 --> 00:00:05,000
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel hendrerit massa.

2
00:00:05,000 --> 00:00:10,000
Aliquam dolor sapien, molestie ac sagittis eu, tempus nec est.

3
00:00:10,000 --> 00:00:28,000
Morbi id sem eu sapien consectetur imperdiet. Morbi sed purus et sapien interdum placerat vitae quis orci.
```

My .ts: sample_1920x1080.ts from https://filesamples.com/formats/ts

SubtitleEdit command: `.\SubtitleEdit.exe /convert 'test_subtitles.srt' Blu-raysup /resolution:1920x1080 /overwrite`
This creates a `test_subtitles.sup` file as expected.

I then use `ffmpeg` to include the .sup subtitles, like this: `.\ffmpeg.exe -y -i 'sample_1920x1080.ts' -fix_sub_duration -i 'test_subtitles.sup' -map 0:v -map 1:s -vcodec copy -acodec copy -scodec dvbsub -copyts -muxdelay 0 -max_delay 0 'output.ts'`. This works, but the results are sometimes not very readable. Here's a screenshot:

<img width="956" alt="Capture" src="https://user-images.githubusercontent.com/4340859/100457311-163fca00-30c2-11eb-88d3-acb80154abb5.PNG">

Are there any options you can suggest that I use to f.ex. increase the size of the subtitles? Any pointers would be much appreciated. Thanks!

**Comment by niksedk** [comment]
SE does not have a resize cmd line function... what happens if you omit the `/resolution:1920x1080` parameter or use `/resolution:720x4800`?

Normally BDSups will be made bigger if the video has a better resolution (which is handled by the video player).

**Comment by stianlagstad** [comment]
That's exactly what I need, thanks @niksedk 👍 Is there a way to adjust these options from the command line? If not: Could you point me towards some relevant files in the code (like where the `/convert` options are handled) so that I can try to add such support myself?

**Comment by niksedk** [comment]
Sorry, no such option atm. And the bdsup *really* has a lot of options but I guess that font size is a good candidate. 
I think the source file is called `CommandLineConverter`... and PR is welcome :)
`
