### ISSUE TITLE
GT is not translating english to portuguese

### ISSUE THREAD

**Issue by bflehdermann** [SubtitleEdit/subtitleedit#4549]
![image](https://user-images.githubusercontent.com/59982497/100778246-83ff3500-33e5-11eb-9cee-d7cc78b5ce4e.png)

**Comment by bflehdermann** [comment]
![image](https://user-images.githubusercontent.com/59982497/100778528-e2c4ae80-33e5-11eb-9a2c-0b4597665727.png)

The new version.

**Comment by niksedk** [comment]
This version?
![image](https://user-images.githubusercontent.com/1261331/100779183-48c22d80-3408-11eb-8ea3-504e01b6a9d9.png)


Could you attach your source subtitle?

**Comment by bflehdermann** [comment]
Yes, is this GT version.
I was already using the compiled version, not the source code (SubtitleEdit-3.5.17-Setup.zip and SubtitleEdit-3.5.18-Setup.zip).

**Comment by niksedk** [comment]
OK, hopefully fixed in GT screen-scraper 1.01

**Comment by brayante** [comment]
@niksedk with GT screen-scraper 1.01 some few lines got like this (I got 4 instances in about 357 lines.) 

![image](https://user-images.githubusercontent.com/64877210/100946154-821a9c00-34e1-11eb-9fd9-bdb96302407d.png)
![image](https://user-images.githubusercontent.com/64877210/100946163-88107d00-34e1-11eb-86b5-66f832388a5f.png)

**Comment by niksedk** [comment]
@brayante: thx, GT screen-scraper 1.02 is out :)

**Comment by brayante** [comment]
@niksedk  Sorry to bother again, my friend. I'm noticing some spaces being added in translations between `...` or `%` .

![image](https://user-images.githubusercontent.com/64877210/101847636-68f19b00-3b32-11eb-9b68-028542b0cdb6.png)
![image](https://user-images.githubusercontent.com/64877210/101847663-7c046b00-3b32-11eb-8111-bf325468a06c.png)

**Comment by niksedk** [comment]
@brayante: thx, GT screen-scraper 1.03 is out :)
