### ISSUE TITLE
Auto break text; unbreak text don't work

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4550]
Hello,
Autobreak text [Ctrl+E] and Unbreak text [Ctrl+R] shortcuts don't work anymore. They work when I click auto br, but not with the shortcut. I don't do a lot of work these days because of COVID, but whenever I do, I keep finding new bugs in 3.5.18.

**Comment by niksedk** [comment]
Hm, it works fine here... what versions exactly are you using?

We did some tests with a web browser as textbox in some beta versions to enable syntax coloring for html/assa tags, but in latest beta that's removed: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
SE can do syntax coloring (via a RichTextBox like WordPad), but that does not work well with all languages.

**Comment by uckthis** [comment]
This latest beta works fine. The most common shortcuts I use are working fine. If I see something, I'll flag it.

Thank you.

**Comment by niksedk** [comment]
Cool, thx for testing :)
