### ISSUE TITLE
simplify append subtitles

### ISSUE THREAD

**Issue by z3us** [SubtitleEdit/subtitleedit#4551]
I frequently use this awesome program to create dual subtitles for my cloud videos. To do it, I open the first subtitle and then append the subtitle for the second language. When I do this , a window is opened with the video ready to be played. I don't really need this, in fact is not very convenient for me because my subtitles and the videos are all stored in Google drive.
Can the load of the video be optional? Maybe a checkbox to load the video if needed?
Also I find it unnecessary to have that many confirmation windows in the append process, that really cannot cause too much issues and is perfectly reversible. Maybe you could take a look on this

https://i.imgur.com/EnAuicy.png
https://i.imgur.com/F0Bz1Qb.png
https://i.imgur.com/4YJOcFp.png
Thanks

**Comment by niksedk** [comment]
You can use the list view context menu or the waveform context menu to quickly insert a subtitle into current subtitle:

![image](https://user-images.githubusercontent.com/1261331/101128459-0400e700-3600-11eb-968c-48fe6fc4884c.png)

![image](https://user-images.githubusercontent.com/1261331/101128427-ee8bbd00-35ff-11eb-9d3f-909a2ec35103.png)

**Comment by z3us** [comment]
But it´s not the same behaviour. With the "insert subtitle after this line", the times of the second subtitle are being modified and  placed after the last line of the first file.
With the "append subtitles" , the times of the second file remain unchanged

![image](https://i.imgur.com/04O7hpr.png)
![image](https://i.imgur.com/8tALh4j.png)

**Comment by OmrSi** [comment]
How about you use "Join" instead of "Append"?
