### ISSUE TITLE
Error using Microsoft Translator

### ISSUE THREAD

**Issue by Brummochse** [SubtitleEdit/subtitleedit#4554]
I set up a Microsoft Azure Account and wanted try the Bing Translation feature.

I set the endpoint given by azure ("https://api.cognitive.microsofttranslator.com/") and the key in SubtilteEdit settings.

When using the microsoft trasnlator it throws an error (System.ArgumentException) in:
https://github.com/SubtitleEdit/subtitleedit/blob/master/src/libse/Translate/MicrosoftTranslator.cs#L105

On the first sight it looks like the _accessToken was not created correct.

Did I something wrong during the microsoft bing Azure translator?

**Comment by niksedk** [comment]
Did you setup a key for cognitive services 'Translator Text' ?
 https://docs.microsoft.com/en-us/azure/cognitive-services/translator/translator-how-to-signup

**Comment by niksedk** [comment]
Be sure that you're using latest version of SE and you should probably have the "Token endpoint" to "https://api.cognitive.microsoft.com/sts/v1.0/issueToken".
The "token endpoint" is used to create the "access token" and it's normally "https://api.cognitive.microsoft.com/sts/v1.0/issueToken" unless you restrict access to a region or do other fancy stuff ;)

![image](https://user-images.githubusercontent.com/1261331/101127771-87213d80-35fe-11eb-894e-d696718a60c2.png)

**Comment by Brummochse** [comment]
Iam on Subtitle Edit 3.5.18

I tried both keys and I tried both endpoints (the "https://api.cognitive.microsoft.com/sts/v1.0/issueToken" default from SE settings and the "https://api.cognitive.microsofttranslator.com/" given from the microsoft page) and nothing worked

hmm any other hints for me?

![microsoft translate](https://user-images.githubusercontent.com/75454304/101142193-8fd13e00-3615-11eb-8141-763a20769022.png)
![se](https://user-images.githubusercontent.com/75454304/101142356-c6a75400-3615-11eb-99a3-f5b95805db89.png)

**Comment by niksedk** [comment]
OK, beta update with a list of all token endpoints - see https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/cognitive-services-speech-service-endpoints-token-service.md
You probably need `https://westeurope.api.cognitive.microsoft.com/sts/v1.0/issueToken`

**Comment by Brummochse** [comment]
perfect! works now great!
