### ISSUE TITLE
[FEATURES] - Translation / Localization Module

### ISSUE THREAD

**Issue by drkhateeb** [SubtitleEdit/subtitleedit#4555]
**Hello all developers**
I suggest adding this module for translation/localization
**Features**:
Advantages of  include: –  quick access to vocabulary, automatic translation, thesaurus and dictionary support, spell checking, Unit and RegEx conversions, including Time and Date Formatting, outlined in more detail below:

Vocabulary function – this allows users to quickly access their collection of phrases, names, locations, and so forth, from one central place.

Automatic Translation function –  allows subtitlers to configure **and choose from one or more translation engine**s such as **Google** and **Microsoft,** **MyMemory,** to provide parallel variants of a translation and store translation in MyMemory to reuse it in future.
MyMemory: API technical specifications
https://mymemory.translated.net/doc/spec.php

Thesaurus and **Dictionary** Support – support Libre Office/OpenOffice dictionaries, MS WORD.

Spell Checking – verifies proper word usage and spelling.

**Unit Conversions** – automatically converts to other units such as **mass**, **length**, **area**, **temperature**, based on the selected text (For example, for 12 lbs, suggested conversions will include 5.44kg, 5443 g, and 192 ounces).

RegEx Conversions – “RegEx” engine allows advanced text manipulations with unlimited functionality for altering text. 
All valid user-configured RegEx filters will be offered. For example, users can fix capitalisation if a word begins with more than one capital letter in a sentence, including the ability to swap words, remove repeated words, profanity filtering, and so forth.

**Date and Time Formatting**  – automatically suggests various formats for both European and American date formats (for example, if the selected text is 12.3.20, suggestions will include 12/03/20, 12/03/2020, and 12 Mar 2020).

Regards

**Comment by niksedk** [comment]
What's the difference to #4529 ?

**Comment by drkhateeb** [comment]
These features regarding localization:
Thesaurus and Dictionary Support – support Libre Office/OpenOffice dictionaries, MS WORD.

Spell Checking – verifies proper word usage and spelling.

Unit Conversions – automatically converts to other units such as mass, length, area, temperature, based on the selected text (For example, for 12 lbs, suggested conversions will include 5.44kg, 5443 g, and 192 ounces).

RegEx Conversions – “RegEx” engine allows advanced text manipulations with unlimited functionality for altering text.
All valid user-configured RegEx filters will be offered. For example, users can fix capitalisation if a word begins with more than one capital letter in a sentence, including the ability to swap words, remove repeated words, profanity filtering, and so forth.

Date and Time Formatting – automatically suggests various formats for both European and American date formats (for example, if the selected text is 12.3.20, suggestions will include 12/03/20, 12/03/2020, and 12 Mar 2020).
