### ISSUE TITLE
Remove Timecodes of Selected Lines

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4558]
Hello,
I just pasted a few lines in the middle of a file. New lines didn't have any timecodes. What SE did is set same start time for all of the new lines. Is it possibile to remove timecodes of the new lines so it's easy to timecode them? In older versions if lines didn't come with timecodes, SE didn't put any timecodes and timecode area used to be blank.

![Untitled](https://user-images.githubusercontent.com/28671050/101271908-22561680-37a9-11eb-8b4e-b9d07585441d.jpg)

As you can see in the image, start timecode is 00:00:35.736 for all of the new pasted lines. These used to be blank. I want to Remove Timecodes of Selected Lines so they're easier to handle.

Thank you.

**Comment by niksedk** [comment]
You can setup a shortcut for this:

![image](https://user-images.githubusercontent.com/1261331/101273175-75bd6a00-3793-11eb-867a-8ad8c0cbbba6.png)

**Comment by uckthis** [comment]
@niksedk , Thank you. Exactly what I was looking for. I didn't know there was this option as it wasn't listed when I right clicked. 

Thank you.
