### ISSUE TITLE
toggle play rate

### ISSUE THREAD

**Issue by Subtitle-Bob** [SubtitleEdit/subtitleedit#4561]
Is there a possibilty to toggle the play rate (e.g. 100% --> 150% --> 100%)? 

I put „play faster“ at Num9 and „play slower“ on Num3, but it increases only 10%. So I have to press the Num-keys four or five times to increase and decrease the speed.

**Comment by OmrSi** [comment]
There is a reset shortcut to set reset the play rate to 100%.
![image](https://user-images.githubusercontent.com/20923700/101494748-63e4ee00-3970-11eb-9b99-9636d4e28154.png)

But there isn't a way to set it to 150% directly.
