### ISSUE TITLE
Set Timecode

### ISSUE THREAD

**Issue by Subtitle-Bob** [SubtitleEdit/subtitleedit#4562]
Is there a way to set the video timecode to another format (e.g. 10:00:00:00)? Especially when I do have an offset (blackframes or color bar) at the beginning of the video I need to set a new start timecode.

**Comment by darnn** [comment]
options, settings, time code mode
and
video, set video offset

**Comment by niksedk** [comment]
You could also need the "Video - SMPTE timing"...

**Comment by Subtitle-Bob** [comment]
Ah, found it! Thanks a lot!

It's a bad translation to German: "Video Ausgleich". No one would call it like that. German Subtitler call it "offset" or "timecode offset".
