### ISSUE TITLE
line breaking

### ISSUE THREAD

**Issue by Subtitle-Bob** [SubtitleEdit/subtitleedit#4563]
Max. number of lines: 2
Auto-wrap.

![image](https://user-images.githubusercontent.com/75670206/101471498-ac3be600-3947-11eb-879a-3c6538afa302.png)

If I want "and" in the second line, I press Enter, this happens:

![image](https://user-images.githubusercontent.com/75670206/101471463-a3e3ab00-3947-11eb-8e88-8c1eafcf6f64.png)

Is there a way to break the line without creating a third line?!

**Comment by OmrSi** [comment]
Settings -> Shortcuts
![image](https://user-images.githubusercontent.com/20923700/101494604-3bf58a80-3970-11eb-8772-887f386c68db.png)

**Comment by Subtitle-Bob** [comment]
Thank you!
