### ISSUE TITLE
Issue with LoadSubtitle on Cheetah Caption

### ISSUE THREAD

**Issue by mook1975** [SubtitleEdit/subtitleedit#4567]
C:\Program Files\Subtitle Edit>SubtitleEdit.exe /convert "C:\FEAR110.cap" srt /outputfolder:"C:"

C:\Program Files\Subtitle Edit>

Subtitle Edit 3.5.18 - Batch converter

ERROR: Index was outside the bounds of the array.
   at Nikse.SubtitleEdit.Core.SubtitleFormats.CheetahCaption.LoadSubtitle(Subtitle subtitle, List`1 lines, String fileName)
   at Nikse.SubtitleEdit.Logic.CommandLineConvert.CommandLineConverter.Convert(String[] arguments)

0 file(s) converted

[FEAR110.zip](https://github.com/SubtitleEdit/subtitleedit/files/5661996/FEAR110.zip)

**Comment by niksedk** [comment]
Hi @mook1975 !

Thx for the info and thx for a well made bug report with sample file :)

Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
