### ISSUE TITLE
Certain Unicode chars cause spell checking to crash

### ISSUE THREAD

**Issue by SeproDE** [SubtitleEdit/subtitleedit#4576]
The spell checker crashes when used on the following file: [crash.zip](https://github.com/SubtitleEdit/subtitleedit/files/5681207/crash.zip)

The crash occurs in [WindowsHunspell.cs:22](https://github.com/SubtitleEdit/subtitleedit/blob/master/src/ui/Logic/SpellCheck/WindowsHunspell.cs#L22) (`AccessViolationException in NHunspell.dll`)

This is the Unicode symbol used in the file 🖤 (U+1F5A4)

**Comment by SeproDE** [comment]
My hotfix was to use [this regex](https://stackoverflow.com/a/28025891) to filter all non-BMP characters:
```csharp
string filtered = Regex.Replace(word, @"\p{Cs}", "");
```

Should I create a PR?

**Comment by niksedk** [comment]
> 
> 
> My hotfix was to use [this regex](https://stackoverflow.com/a/28025891) to filter all non-BMP characters:
> 
> ```cs
> string filtered = Regex.Replace(word, @"\p{Cs}", "");
> ```
> 
> Should I create a PR?

Please do :)

Do you know if this lib also crashes on "🖤": https://www.nuget.org/packages/WeCantSpell.Hunspell/ ?

**Comment by SeproDE** [comment]
`WeCantSpell.Hunspell` seems to work with those code points.
```csharp
var hsNHunspell = new NHunspell.Hunspell("en_US.aff", "en_US.dic");
hsNHunspell.Suggest("test");
hsNHunspell.Suggest("\U0001F5A4"); // crashes

var hsWeCantSpell = WeCantSpell.Hunspell.WordList.CreateFromFiles("en_US.dic", "en_US.aff");
hsWeCantSpell.Suggest("test");
hsWeCantSpell.Suggest("\U0001F5A4");
```

Should I still go ahead with the PR?

**Comment by niksedk** [comment]
Yes, please go ahead with the PR :)

And thx for testing WeCantSpell too :)
That might be the way to go at some point in the future.
