### ISSUE TITLE
batch-convert: Parallel OCR conversion

### ISSUE THREAD

**Issue by OlJohnny** [SubtitleEdit/subtitleedit#4578]
When batch-converting some subtitles (with OCR) it takes a very long time, as all files are processed in serial (and each file takes upwards of a couple minutes).

However when converting those files manually I can realistically open up 4-6 conversion processes at the same time (as far as I can tell).
Opening up multiple batch-convert processes at the same time seems to be working nicely as well.

I don't have any experience with the codebase of SubtitleEdit, but based on the experience above i think it shouldn't be impossible to implement?

This may make only sense when the conversion task per file takes longer than a couple of seconds.

**Comment by niksedk** [comment]
What OCR engine?

**Comment by OmrSi** [comment]
@niksedk I noticed the fixes are already done in a background worker, right?
The problem I see with doing multiple OCRs is updating the UI, it can be done with Tasks but you have to use the main thread each time the UI needs updating.

**Comment by OlJohnny** [comment]
> What OCR engine?

As far as I can tell, you are unable to change the OCR Engine for Batch Convert, so I guess the default one. (In general there doesn't seem to be a tab in the settings for batch-convert)
Thing is, when converting subtitles for one season with each episode >30min, each sub file can take up to 10 min, so it would benefit greatly from parallel working.

**Comment by niksedk** [comment]
Which OCR engine do you use for manual OCR?

Batch convert UI uses Tesseract which already runs parallel internally, so it makes no sense to start parallel execution of Tesseract.

**Comment by Enivex** [comment]
> Which OCR engine do you use for manual OCR?
> 
> Batch convert UI uses Tesseract which already runs parallel internally, so it makes no sense to start parallel execution of Tesseract.

My CPU is barely utilized when doing OCR. There should definitely be a lot to gain from parallel execution of Tesseract.
