### ISSUE TITLE
free quota exceeded with google translation

### ISSUE THREAD

**Issue by orbittwz** [SubtitleEdit/subtitleedit#4579]
![image](https://user-images.githubusercontent.com/45605734/102006649-3959b300-3d2b-11eb-9dbc-ee9b1f3b76ff.png)
does this have a solution? after translating multiple files with google, the program returns an error about free api quota exceeded .
I'm pretty sure setting a 2.5 seconds pause between each call to the api will solve this...

this could become the base implementation to batch google translating...

something about:
			DateTime T = DateTime.Now;
                        DateTime now = T;
			while ((now - T).TotalMilliseconds < 250.0
                                         DateTime now = DateTime.Now;

**Comment by niksedk** [comment]
You can try the "Google Translate Screen-Scraper" plugin or setup a key with billing - or wait.

**Comment by orbittwz** [comment]
oh...
wait for what?

**Comment by niksedk** [comment]
> 
> 
> oh...
> wait for what?

Wait until it works again...

**Comment by orbittwz** [comment]
ahhh... wait for the cooldown...
did you saw my suggestion? any thoughts?

**Comment by niksedk** [comment]
Yeah, wait for the cool-down.
Yes, saw your suggestion. That will probably just annoy people and I will get a lot of hate emails... will also be very volatile as these things change often.

If SE had batch translate it would only be for api key users... hammering APIs without paying will probably make someone pretty mad at some point.

**Comment by orbittwz** [comment]
I see, OK then...
maybe consider doing batch GT scraping?
for example, I want to translate multiple files, instead of loading them one by one and scrape them, with one command I can select the folder I want to scrape and the program will do everything automatically... load scrape and save them one by one...
