### ISSUE TITLE
Error (not sure how to reproduce)

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#4580]
3.5.18 NEXT beta 194.
I was playing around with a key remapper (see https://github.com/SubtitleEdit/subtitleedit/issues/4536), and I'm not sure if this is what caused it or not, because I was, frankly, doing a lot of random things, but I got the following error:
![se3 5 18 error](https://user-images.githubusercontent.com/19672444/102022321-b9653480-3d8e-11eb-8adc-e39407bb9ce7.png)

**Comment by darnn** [comment]
In fact, then I closed the program, opened it again, tried to open the settings window and got this:
![Uploading se3.5.18 error2.png…]()

**Comment by niksedk** [comment]
Sorry, I think that was a bad beta... try getting latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip (3.5.18 NEXT beta 243)

**Comment by darnn** [comment]
Ah, okay. I did that anyway, I just thought this might be something that hasn't been fixed yet that you might be able to puzzle out from the error messages. Feel free to close this.
