### ISSUE TITLE
3.5.18 Beta 254: Shortcut for go to beginning of video without play

### ISSUE THREAD

**Issue by GrampaWildWilly** [SubtitleEdit/subtitleedit#4584]
We have a shortcut for play from the beginning of the video, which is useful.  I'd also like a shortcut that just positions at the beginning of the video without playing.  I find that sometimes SE opens with the video positioned on the first caption, which can be several seconds or even minutes into the video.  I then have to reposition back to the start.  The shortcut to play from the start helps.  I just use that, quickly stop playback, then skip back to the beginning.  But a single shortcut instead of those 3 steps would be nice.

**Comment by OmrSi** [comment]
Or maybe just make the current shortcut not play? 
The user can simply use the Play shortcut if he wants to play the video. 
@niksedk What do you think?

**Comment by niksedk** [comment]
A new shortcut...

**Comment by OmrSi** [comment]
@niksedk Okay, I'll work on it.

**Comment by GrampaWildWilly** [comment]
I'm not sure that addresses my issue.  I see a shortcut for Stop.  (I'm now on 3.6.7 beta 105.)  I happen to have no key sequence defined for it.  I see a shortcut for Play from beginning of video.  But what I want is a shortcut for Reposition to beginning of video, which implicitly would not begin playback.  By the way, the shortcut for Play from beginning of video appears to have a default of Ctrl+Oem5.  Pardon my complete ignorance but what is Oem5?  What key on my keyboard is that?  I've tried the 5 on the top row of keys, the 5 on the numeric keypad (with & without NumLock), F5 (which I know isn't it).  But I haven't managed to find Oem5.  I see there's a few other keys whose names begin with Oem that I'd like to know about as well.  Is that a Mac-only or Linux-only thing?  I'm on a regular desktop PC running Windows.

**Comment by OmrSi** [comment]
@GrampaWildWilly `Stop` does exactly what you want, it returns to the beginning of the video and doesn't play.

Oem5 is the `\` and `|` key.

**Comment by GrampaWildWilly** [comment]
Aha! \|.  OK.  Just for the record, I have discovered by trial & error the following translations:

Oem1 = ; :  Shift or no shift, doesn't matter.  You get the same Oem1 with ; and with :.
Oem6 = ] }
Oem7 = ' "
Oem8 = I haven't managed to find this one on my keyboard.

Shift is ignored when navigating the list of keys.  I guess this is because Shift has its own little check box over to the left of the list of keys, which is to say Shift is treated differently.

Oem2, Oem3, & Oem4 apparently don't exist.  There are also several other keys with names that start with the characters Oem but they are named intuitively.

Kind of humorous note.  The PageDown key actually pages the list of keys down.  You can't use the key to actually select the PageDown entry in the list.  On the other hand, PageUp doesn't page up.  It does select the PageUp entry in the list.  In a similar apparent anomaly, the LeftArrow & RightArrow keys select, respectively, Left & Right in the list.  But the UpArrow & DownArrow keys navigate the list instead of selecting entries.

I have also now defined the Stop shortcut as Ctrl+Home.  This does indeed reposition the video to the start & does not launch playback.  Thanks for that explanation.  May I suggest that Stop is not a particularly intuitive name for that shortcut.  When I saw that name I thought all it would do is stop playback.  I would rename that as "Rewind to start" or "Reposition at time 00:00" or something along those lines.  Now if we could just get SE to remember that I've positioned it there the next time I open SE . . .

**Comment by darnn** [comment]
I think it would be totally fine to add a parenthetical clarifying what "stop" does, but I will say that it is the common shorthand for that in all standard video playing software. See VLC itself, for instance, where it's called "stop playback", and does the same thing.
