### ISSUE TITLE
Ctrl + Backspace Issue

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4585]
Hello,
In any text editor, Ctrl+backspace deletes one word. SE used to be like that, but now it deletes two words. 
I have 3.5.18 Beta 164. Does it have something to do with the textbox thing you all were talking about?

**Comment by OmrSi** [comment]
I don't know why that happens some time in RichTextBox, the one used with syntax coloring.
The last time it happened, I just restarted SE and it went back to normal.

**Comment by uckthis** [comment]
I have syntax coloring off. I have no idea what's it's for and it was causing me a lot of trouble. 

Restarting did nothing for me.

**Comment by OmrSi** [comment]
Ah, then please try the latest beta, the original implementation of the normal text box was returned here: https://github.com/SubtitleEdit/subtitleedit/commit/3d47ae17f66b3eb9fdd5c03facf8a213f16b5247

**Comment by uckthis** [comment]
Yes, updating solved the issue.

Thank you.
