### ISSUE TITLE
Error when translating with Bing

### ISSUE THREAD

**Issue by MarianTum** [SubtitleEdit/subtitleedit#4589]
![TranslateError](https://user-images.githubusercontent.com/76086361/102305253-9798c700-3fb3-11eb-87fc-c43ac4453556.JPG)

**Comment by niksedk** [comment]
@MarianTum: Could you attach the subtitle file?

**Comment by niksedk** [comment]
@MarianTum: OK, tried to fix it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
Does that work for your subtitle?
