### ISSUE TITLE
Defined custom colors are lost after a restart.

### ISSUE THREAD

**Issue by gitut2007** [SubtitleEdit/subtitleedit#4592]
Hi. Right-click : color -"define custom colors" ok but the new colors are lost after a restart. SE3.5.18 portable mode, win7 
Thx

**Comment by OmrSi** [comment]
If there are certain colors that you always use, you can set these shortcuts to use them: 
![image](https://user-images.githubusercontent.com/20923700/102485531-6d590f00-4070-11eb-9566-8ef592f3ccd1.png)

And then use them via the shortcuts.
You can set them from the settings file.
