### ISSUE TITLE
Black theme for Subtitle Edit

### ISSUE THREAD

**Issue by MuhammadiJK** [SubtitleEdit/subtitleedit#4596]
Hi Nikolaj,

Can you please make a black skin for Subtitle Edit: grey text, everything else is totally black?
I know about the dark theme in the "Settings" XML file, but it's not black.
Everyone with sensitive eyes is waiting for a black theme.

Maybe you can change the dark theme to a totally black one or add a new black theme?
If you don't want to do it, maybe you can tell me which strings to change in the "Settings" XML file, to make everything black?

Thanks a lot

**Comment by niksedk** [comment]
Dark theme is very hard to make with MS Winforms... 
Latest beta is a little better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by MuhammadiJK** [comment]
Thanks a lot for the response, Nikolaj.

If this thread is a duplicate & you don't want me write here, please give me the link to the original thread so that I could follow up.

I totally understand that it's very hard to make a dark theme.

But black is the best color for sensitive eyes, all the other color are more or less worse.
I really don't understand why people make dark skins if there's no black one.

I've chosen dark theme & changed the Subtitle background color to black.
Your dark theme forces it to be changed back to brown. Please find attached the screenshot.
![Black theme](https://user-images.githubusercontent.com/58576192/102658981-76de9600-419a-11eb-8562-3d6ce363bc25.jpg)

Can you give the option to choose the back color in the dark theme section?

**Comment by niksedk** [comment]
@MuhammadiJK: thx, forgot to enable the button... fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

The first issue for dark theme is here: https://github.com/SubtitleEdit/subtitleedit/issues/3678
