### ISSUE TITLE
[Shortcut Suggestion] Move Nearest Gap Back / Forward

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4606]
Although the name mentioned "gap", but I couldn't think of a better name for this feature. The basic idea is to move the end time of line A together with the start time of line B, even there is no gap between them, and it is exactly the true power of this operation. 

**Benefits:**
This is very useful for fine-tuning work, and it can also benefit scenarios when having to choose a faster play rate for urgent projects. Because as I tested, it can be even more efficient than Alt+Drag here.

After my testing on many real cases, the expected options would be:

```
Move nearest gap 100 ms back
Move nearest gap 100 ms forward

Move nearest gap 200 ms back
Move nearest gap 200 ms forward

Move nearest gap 500 ms back
Move nearest gap 500 ms forward
```

The 100 and 200 sets are more suitable for fine-tuning, while the 200 and 500 sets are more for working with faster play rate. e.g. we can set number key 1~6 as shortcuts for them conveniently,

FYI. Thanks!

**Comment by OmrSi** [comment]
Don't these do this?
![Uploading image.png…]()

**Comment by LeonCheung** [comment]
I remember we have such similar ones, just failed to find them in the long list... Yes, basically the same idea  :) but the increment by 1 frame is way too small....
