### ISSUE TITLE
Compare In Certain Cases

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4607]
I have to admit this is a very powerful tool! Just... the current "Ignore line breaks" cannot benefit languages like CJK:

![compare-CJK](https://user-images.githubusercontent.com/494788/102685240-36bef800-421a-11eb-974f-f00c1dcb1468.jpg)

Is there anything we can do here? :)

**Comment by OmrSi** [comment]
Seems there is special treatment for Zh and Ja:
![image](https://user-images.githubusercontent.com/20923700/103243776-90829900-4963-11eb-8b71-654746ca554e.png)

**Comment by LeonCheung** [comment]
Oh, I mean it works with English cases, but not for non-English cases. Please see GIFs below.

For English:
![111](https://user-images.githubusercontent.com/494788/187472471-1bb69aca-9f4d-462a-8401-df1c05d98b0b.gif)

For non-English:
![222](https://user-images.githubusercontent.com/494788/187472506-c3c5ef54-bd73-49c5-ab0b-ef4183942521.gif)
[examples.zip](https://github.com/SubtitleEdit/subtitleedit/files/9454043/examples.zip)

**Comment by niksedk** [comment]
Perhaps "Ignore whitespace" ?

![image](https://user-images.githubusercontent.com/1261331/187507715-8b170a40-81de-404e-94a6-9bb90fa05de6.png)

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Sweet. Thank you! Closing.
