### ISSUE TITLE
Framerate conversion

### ISSUE THREAD

**Issue by aki-sud** [SubtitleEdit/subtitleedit#4613]
Hi,
I just wanted to understand how conversion from one framerate to another is done by this program:-
1. 25 fps to 23.976 fps.
2. 25 fps to 29.97 fps.
3. 23.976 fps to 29.97 fps.

like is conversion is done by keeping frames or milliseconds same during conversion??
OR has any other method been used for the same??

**Comment by niksedk** [comment]
Internally milliseconds are used which are rounded to frames when saved.

**Comment by aki-sud** [comment]
Okk. So, conversion is done based on keeping milliseconds constant for any conversion. Could you please also explain the reason as to why this is done and not the other way around??

**Comment by niksedk** [comment]
Ms are much more precise...
