### ISSUE TITLE
[beta issue report] Another thing about F2 feature

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4616]
Corner case:

![F2](https://user-images.githubusercontent.com/494788/102704856-e009fa80-42bb-11eb-9bfe-c6780a9f86db.jpg)

**Comment by OmrSi** [comment]
How does this happen?

**Comment by LeonCheung** [comment]
When you 0 line.

**Comment by OmrSi** [comment]
Hmm, I'm not able to re-create.
Even if I add 10 empty lines in the source view, it still works.

What do you mean by "0 lines"?

**Comment by LeonCheung** [comment]
LOL well it means you have nothing in the file.  Beta 307.

**Comment by OmrSi** [comment]
Still can't re-create.
Have you tried it with the latest beta?

I made a new file, nothing.
I made a new SRT file from windows and opened it, still nothing.

**Comment by LeonCheung** [comment]
Ah, tested. 328 is fine...  :)

**Comment by niksedk** [comment]
Fixed it yesterday :)
