### ISSUE TITLE
Proposal for a new ASS Style Manager

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4617]
I know I got quite a few ideas to bother lately, but they just came like floods 🤣. As usual, a picture paints a thousand words:

![SE_ASS_Style_Manager_GUI_proto](https://user-images.githubusercontent.com/494788/102711296-786fa180-42f3-11eb-9616-7cd6be3b0d95.png)

The basic idea is to make the layout compact without losing any current options while enriching it with more useful stuff.

BTW, I guess it might also well solve #4483?

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip ?

Is `Strikethough` common?
What should margins for `safe area` be?

**Comment by OmrSi** [comment]
Cool. :)

Why is the button's font bold in the upper section, though?

**Comment by LeonCheung** [comment]
@niksedk Awesome! Though I can see it's still WIP now, it's already pretty awesome!

For `Strikethrough`, for me, it's uncommonly used like Underline, just I noticed that at least two other sub editors supporting that, so, just FYI.
For `safe area`, it's also a FYI feature here. I personally don't use it but not sure if everyone doesn't. After all, many video editors like Premiere support it, in case we need to burn subtitles to the video. But I think it's only useful when the SE preview is accurate. Currently, it's not.

Again, I know it's still WIP, since you ask:

1. Maybe it's nice to allow manual adjustment on the height ratio between Styles and Storage area? I mean, just try maximizing the style manager window, you'll notice that the storage area is over sized. So, maybe the height can be adjusted by putting the mouse cursor on the split line between the two area then move up / down? Like:

![adjust](https://user-images.githubusercontent.com/494788/102957340-2a39e880-4515-11eb-841d-4962aae55cef.jpg)

2. Again, a resolution-based preview can be really meaningful for this kind of format, especially for font size and position, so that we don't have to go back and forth, trial and error, to get a perfect font size/position according to what it looks like in SE player. So, even if it's not for safe area, an accurate preview system can also be nice to serve its name. :)
3. When clicking "Add to..." buttons, it would be nice to ask whether we need to override the existing one with the same name. I mean, usually, auto-rename is convenient, just sometimes we need to update the same style to the other side. (maybe another option is to add a little checkbox near the button? Hmm, not sure...)
4. An ad-hoc button on the toolbar can be quite convenient when working with this format. I mean, like when we edit EBU-STL, a but red "N" would show up on the toolbar for Netflix quality check. Since formatting can be very heavy lifting work here and we need to open style manager quite quite often. (maybe a big letter "A" is just enough lol)
5. "Add to storage" is duplicated in the context menu.
6. Multi-item selection can be welcome, say, when we want to add multiple styles to the other side by one single click.

@OmrSi Actually only the focused section is bolded, to keep reminding us that we are working on the right side. Imho it can make sense.

**Comment by LeonCheung** [comment]
Btw, a few fine-tune suggestions on GUI side:

![fine-tune](https://user-images.githubusercontent.com/494788/102984836-2b850880-4549-11eb-9b5c-35ac91455506.gif)

Preview area can be even larger in this way, maybe nice for 4:3 source.

**Comment by niksedk** [comment]
OK, the first working (hopefully) version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

1) height ratio between current styles + storage styles is 1:1 when resized and can be changed manually via a splitter.
2) the preview window is rather small, and not too well suited for a scaled preview as the text would be very small...
3) added prompt for overwrite 
4) added a shortcut instead.
5) fix duplicate menu item
6) TODO
7) added prompt for delete (unless delete prompt has been disabled in setting)

![image](https://user-images.githubusercontent.com/1261331/103149678-f3114480-476b-11eb-9875-642fd2b2dd0a.png)

**Comment by LeonCheung** [comment]
Cool!

For Point 2, when I maximize the manager window, the preview area also gets larger enough to preview everything, but your concern matters too. Then maybe a better solution is by simply adding an "Apply" button Next to the "OK" button, so that we can see the updated result in SE player without closing the manager window, assuming the current subtitle line is using the same style. I think this could be a nice workaround too if possible.

Plus a few GUI tweaks for perfectionists, which can be solved by simply offsetting one or two pixels:

![alignment](https://user-images.githubusercontent.com/494788/103150156-43a89200-47ac-11eb-9eda-5d3518449b35.jpg)

And just got an error message that says "invalid value (or param)", not sure why:
![error](https://user-images.githubusercontent.com/494788/103150163-58852580-47ac-11eb-9e92-1e436d497f20.jpg)

Again, thanks a lot for your amazing work on this.

**Comment by niksedk** [comment]
@LeonCheung: How did you get the `invalid value (or param)` error?

**Comment by LeonCheung** [comment]
For the error, I tried to re-produce but found nothing yet. I'll make sure it can be re-produced and let you know then. :)
The small t comes from the word "Alignment", now it's displayed as "Alighmen" + "t". I tested on another PC, the same. The OS font size is 100% standard btw.

**Comment by niksedk** [comment]
Ah thx, made a bit more room for "Alignment" in latest beta:  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Yes, Alignment fixed, thx.

**Comment by moob158** [comment]
I think it should be add to "Style Manager" the option of "Wrap style"

**Comment by LeonCheung** [comment]
@niksedk About the error message we mentioned, try simply minimizing the manager window, to see if it can pop up.

**Comment by LeonCheung** [comment]
@moob158 I think the idea would better be a Tag Library, or Tag List that would simply work like Copy / Paste, since there are many tags and Wrap is just one of them.

**Comment by niksedk** [comment]
thx - the minimize/reopen error should be fixed.

Beta (and code) updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

I'll close this now as this is implemented as a version 1 :)
