### ISSUE TITLE
Cannot change the size of text box

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4618]
Hi.
I've noticed that the SE layout changed a bit.
I am used to the old look with larger text box and small list view.
https://i.postimg.cc/Jhwb8hFm/old.jpg

I cannot change it in new version. Why isn't it customizable?
https://i.postimg.cc/2SL4gW22/new.jpg

**Comment by OmrSi** [comment]
The tab control for `list/source view` is gone. It gives more space to the list view, and it was not looking good with the dark theme.
It just seems weird at first, but you get used to it.

**Comment by m0ck69** [comment]
Probably I will but why can't I enlarge text box and make list view smaller? I can change the size of video preview but NOT the text box and list view.

**Comment by niksedk** [comment]
The text box was never meant to be this large - it was a bug.

(you can use paste images on Github - no reason to use image hosts)

**Comment by m0ck69** [comment]
OK, I understand, I'll get used to the new size although I still think that one should be allowed to set text box/list view size according to their own preferences.

Anyway, thanks for response.

**Comment by OmrSi** [comment]
@m0ck69 I just noticed there is a hidden option in the Settings file called `<SubtitleTextBoxMaxHeight>200</SubtitleTextBoxMaxHeight>`
You can increase it to get:
![image](https://user-images.githubusercontent.com/20923700/102772546-5b3ce080-4390-11eb-87fe-6fa95601379b.png)

:)

**Comment by m0ck69** [comment]
@OmrSi thx so much for the info. I think I'll stick with the new size, it's not that bad afterall but it's good to know that there is resizing option as well.
