### ISSUE TITLE
How to batch add tags to multiple subtitles?

### ISSUE THREAD

**Issue by rubensgpl** [SubtitleEdit/subtitleedit#4621]
Would be very time consuming to open each file and add the same tags I want them to have. The Batch Convert option is awesome, would be very interesting to have an option to add tags.

**Comment by OmrSi** [comment]
You can add them with regex in multiple replace.
If you want to add `{\an8}` to the beginning of each lines, you can add this regular expression:
Find: `\A`
Replace with: `{\an8}`
Then use multiple replace on all of the files.
You can use regex for all kinds of tags.

**Comment by rubensgpl** [comment]
@OmrSi I want to add: `<font face="Roboto Black" color="#ff9117">`
I have never used regex before, I'm a bit noob in this case, could you help me?

**Comment by OmrSi** [comment]
Should be easy enough.

1. Activate multiple replace.
2. Click on "Settings".
3. Add this:
![image](https://user-images.githubusercontent.com/20923700/102737673-bcdd5a80-4350-11eb-85da-18102d6d6a8c.png)
Find what: `\A[\S\s]+\Z`
Replace with: `<font face="Roboto Black" color="#ff9117">$0</font>`
With `regular expressions` activated.
4. Convert.

**Comment by rubensgpl** [comment]
@OmrSi Wow, that's amazing, it worked! Thank you!
But I can't leave without asking, how you got dark theme?

**Comment by OmrSi** [comment]
Anytime. 😄

We've been working on the dark theme lately. 
It will be available in the next version. 
For now,  you can use it in the beta version: 
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

It's in Settings -> Font

**Comment by rubensgpl** [comment]
@OmrSi I have tried the dark theme option, it's not perfect yet, so I'll keep using the standard version for now. I got another question that involves the use of Multiple Replace and I think you could help me with regex.

I have subtitles for some languages like English, Portuguese, French, etc. I like to rename each .srt with the same video file name, putting the language at the end. 
I.e: _Movie.2020.1080p.WebRip.x264.**English**.srt_
      _Movie.2020.1080p.WebRip.x264.**French**.srt_

Can I add this automatically at the end of each file with Multiple Replace, and maybe making SubtitleEdit understand which language the subtitle is?

**Comment by OmrSi** [comment]
>I have tried the dark theme option, it's not perfect yet

What do you think is missing?

> Can I add this automatically at the end of each file with Multiple Replace

In SE, you can append language codes with two letters or two letters.
You can choose by right-clicking in the batch convert window.

Before that, you can use this handy tool https://psarips.uk/get/psa-media-subtitle-renamer/ to rename the files.
It's very easy to use and has a friendly UI.
