### ISSUE TITLE
Why Subtitle Edit can't save files in a mounted local drive but aegisub can?

### ISSUE THREAD

**Issue by rubensgpl** [SubtitleEdit/subtitleedit#4622]
I have mounted Google Drive in Windows 10 using NSSM and WinFsp, now I can sync files just by dropping it inside the folder in `D:\gdrive\path` like a local drive. Aegisub, when editing some subtitles inside this path, can save and overwrite any .ass/.srt file simple as that. When using Subtitle Edit I get a message saying the access is denied. Any way to fix that?

![image](https://user-images.githubusercontent.com/2881202/102740179-f94b8f00-432d-11eb-848a-5755a72f784b.png)

**Comment by niksedk** [comment]
Perhaps make sure that the account running SE has access to this folder?

**Comment by rubensgpl** [comment]
@niksedk I don't see how SE wouldn't have access to the folder, the same user running aegisub is running SE. I have tried running SE as administrator, but no effect. One thing I noticed is, when **Saving** the file (overwriting) I get access denied, but when creating a new file with **Save as** there is no problem.

**Comment by niksedk** [comment]
I've tested with Google Drive File Stream and here save + re-save work fine... not really sure how to test this and also not really sure this has to do with SE as it just uses standard lib to save files. 

Did you check the folder properties to check access rights?
