### ISSUE TITLE
Fix missing spaces misses one case

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#4623]
I think both lines here require a space at the beginning.

```
126
00:08:28,967 --> 00:08:31,803
-But I thought she was--
-Silence, Tutlings!
```

**Comment by borifax** [comment]
Add
<RegEx find="^-(\p{L})" replaceWith="- $1" />
in OCRFixReplaceList.xml file

**Comment by borifax** [comment]
Add regex
"^-(\p{L})" replaceWith="- $1"
in OCRFixReplaceList.xml.
