### ISSUE TITLE
In version 3.5.18 Beta that you asked me to test (see  #4589 ) option "endPoint" for Bing is missing in Settings->Tools

### ISSUE THREAD

**Issue by MarianTum** [SubtitleEdit/subtitleedit#4626]
![image](https://user-images.githubusercontent.com/1261331/102851183-756fd080-441b-11eb-9485-e411fb7a5d74.png)

![SubtitleEditError-remote-server-22-12-2020](https://user-images.githubusercontent.com/76086361/102850511-c5778300-446d-11eb-99c8-bed79461589c.JPG)

Edited: redacted the key

**Comment by niksedk** [comment]
Looks like an old version of SE... should look more like this:

![image](https://user-images.githubusercontent.com/1261331/102851064-26c23680-441b-11eb-8680-9b98210f1b3e.png)
