### ISSUE TITLE
Too large files?

### ISSUE THREAD

**Issue by borifax** [SubtitleEdit/subtitleedit#4627]
Is there any size limit for files loaded into SE? Specifically, I mean the "names" files in the "Dictionaries" folder.
I am using the "pl_names.xml" file with a size of 1520KB. Until today, my "names.xml" file was 137KB in size. I spent a few hours enriching it :P and it grew to 1647KB. Since then, I can't scroll to the end of the names/ignore list.

SE works normally and correctly reads words from lists while extracting of subs.

![image](https://user-images.githubusercontent.com/45988475/102922543-7b52c980-448e-11eb-9047-ac097fe98c6f.png)

**Comment by niksedk** [comment]
OK, that's probably a lot more rows than this was intended for... perhaps some words could be moved to the global names list?

But I've tried another component - perhaps that works better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by borifax** [comment]
Great job. It works!!! Thanks!

![image](https://user-images.githubusercontent.com/45988475/103211218-e295d100-4907-11eb-897b-67bf12cf2fcc.png)
