### ISSUE TITLE
Duration 000

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4629]
This has happened to me quite a few times, so I decided to make a post. Sometimes whilst ripping subtitles from a certain source, duration of all subtitles is zero. Example: https://dailyuploads.net/3v5127fusgja
If you play the video in VLC with subtitles turned on, you can see the subtitles, but when they're ripped, duration goes to 000. 
![Untitled](https://user-images.githubusercontent.com/28671050/102995784-95021880-4543-11eb-9b7b-601fc24a8934.jpg)

**Comment by uckthis** [comment]
I use drag n drop for ripping.

**Comment by niksedk** [comment]
Thx for the bug report :)

The duration in this subtitle is actually 0.

Latest beta now auto guesses duration if it's 0. I'm not sure if it's the best solution...
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by uckthis** [comment]
That's strange, because in VLC they were working fine.

**Comment by niksedk** [comment]
Works relatively fine in VLC... they last until next subtitle shows.
