### ISSUE TITLE
BinaryOcrDb.Add: Image already in db!

### ISSUE THREAD

**Issue by jpinto0** [SubtitleEdit/subtitleedit#4631]
Hi,
   Using Subtitle Edit 3.5.18.1.
   After loading subtitles from a MKV video, which are imported correctly, and starting OCR, when I click on "Edit image Db" and make a character match, I get this error:
--
An application error occurred in Subtitle Edit 3.5.18.1.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:
Error Message:
BinaryOcrDb.Add: Image already in db!
Stack Trace:
at
Nikse.SubtitleEdit.Logic.Ocr.Binary.BinaryOcrDb.Add(BinaryOcr Bitmap bob)
at
Nikse.SubtitleEdit.Forms.Ocr.VobSubOcrCharacterlnspect.butt onAddBetterMatch_Click(Object sender, EventArgs e)
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e) at
System.Windows.Forms.Button.OnMouseUp(MouseEventArgs m eve nt)
at System.Windows.Forms.Control.WmMouseUp(Message&
m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(lntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)
--
The problem happens only for the comma character "," - all other characters work fine.
The message seem to indicate that the comma is already in the db, but as you can see from the attached screenshot, when I pick the comma image and try to match the corresponding character, I have only available the "Add" button, contrary to other characters that, if they exist, the "Update" and "Delete" buttons are also enabled.
So, no way for me to resolve this, can you help?

Thanks

**Comment by jpinto0** [comment]
Ok, screenshot file available here: https://www.dropbox.com/s/zryvs92xt6jn16b/Snap1.jpg?dl=0

**Comment by niksedk** [comment]
@jpinto0: could you attach .db file + the screenshot? (you can attach .zip files here).

**Comment by jpinto0** [comment]
Hi,
    Sure, here they go, I assume this is what you're asking for.    If not, please let me know.

Thanks
--João 

    On Friday, December 25, 2020, 12:50:25 PM GMT, Nikolaj Olsson <notifications@github.com> wrote:  
 
 


@jpinto0: could you attach .db file + the screenshot? (you can attach .zip files here).

**Comment by niksedk** [comment]
@jpinto0: Attachments from email replies do not seem to work... try doing it from github.

**Comment by jpinto0** [comment]
[attach.zip](https://github.com/SubtitleEdit/subtitleedit/files/5742061/attach.zip)

**Comment by jpinto0** [comment]
Attached. Tx.

**Comment by niksedk** [comment]
thx, got the db 👍 
By image i mean the image you were OCR'ing... you can right click on the image, to save it. The sub + line number will also work.

**Comment by jpinto0** [comment]
[Daffy Duck Hunt.zip](https://github.com/SubtitleEdit/subtitleedit/files/5742081/Daffy.Duck.Hunt.zip)
Subtitle file attached. It is not the same subtitle as the one I got the error on when reported this, but the problem is the same.
Line in question is line 3, but any line where you find a misspelled word ending in "r." will show the problem. Those "r." at the end of the words are in fact commas, and that is the character I can't add to the database since it causes this error.
OCR will take all commas for "r." and that's what you will see in the subtitle file.
Thanks.

**Comment by niksedk** [comment]
You attached a .srt file... should it have been a .sup file?

**Comment by niksedk** [comment]
You can either save the current OCR image (right-click on image):
![image](https://user-images.githubusercontent.com/1261331/103138255-0d4a1480-46d1-11eb-89f5-4007b0a1883e.png)

Or save a .sup file (right-click in list view):
![image](https://user-images.githubusercontent.com/1261331/103138271-29e64c80-46d1-11eb-93bc-6a72b5c28a89.png)

**Comment by jpinto0** [comment]
[Daffy Duck Hunt.zip](https://github.com/SubtitleEdit/subtitleedit/files/5742178/Daffy.Duck.Hunt.zip)
Attached both image and sup file. Thanks

**Comment by niksedk** [comment]
Thx for the files 👍 
Bug should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
