### ISSUE TITLE
SE does not remember video position

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4632]
Hello.
Whenever I open SE, it always starts from the beginning of the video.
How do I make SE remember last video position and line that I worked on?

I'm pretty sure that prvious versions of SE did that.
@OmrSi

**Comment by OmrSi** [comment]
@niksedk When loading SE, listview's visible is set to true, and therefore `visible changed` is invoked, and line `SubtitleListview1.SelectIndexAndEnsureVisible(0, true);` in line 11946 is applied, so the item is lost.

I don't know how to fix this, TBH.
It needs another condition to return if it's set on loading, and I don't know how to achieve that.
