### ISSUE TITLE
All capital letters in all words.

### ISSUE THREAD

**Issue by borifax** [SubtitleEdit/subtitleedit#4634]
I need to change all letters in words to uppercase.
In regex, I use \U or \L and I get the result as in the screenshot. Anyone have an idea what I should enter there?
![image](https://user-images.githubusercontent.com/45988475/103134632-f0064d80-46b2-11eb-92b0-a16ae47af856.png)

**Comment by OmrSi** [comment]
Regex in .NET doesn't support the \U and \L.

**Comment by borifax** [comment]
Thanks.

**Comment by OmrSi** [comment]
Also, there isn't any substitute.

**Comment by OmrSi** [comment]
You can:
1. Select all lines.
2. Copy text only to clipboard.
3. Paste it in Regex101 and apply your regex.
4. Copy the result.
5. Go to the first selected line in SE and right-click -> Column -> Paste from clipboard

**Comment by borifax** [comment]
For the more frequent errors I defined separate expressions. The rest I corrected manually.
Thanks again.

**Comment by LeonCheung** [comment]
@OmrSi However, when pasting back to SE, empty lines will be taken into account, not sure if it's something to fix. :-/

**Comment by OmrSi** [comment]
@LeonCheung How so? Column paste from clipboard allows you to paste only text and takes the empty lines in the text as an indication to new lines.

**Comment by LeonCheung** [comment]
I don't know, it shouldn't be like that but just confirmed in the beta 300 and 353.

**Comment by borifax** [comment]
For the test I made these corrections again. It was working. I copied and pasted from the source view.

**Comment by LeonCheung** [comment]
Ah oh, it occurs to me even with 3.5.1. I'm soooooo puzzled....
![test gif](https://user-images.githubusercontent.com/494788/103137054-94fb4780-4700-11eb-81f2-4bbe459ce59c.gif)

**Comment by OmrSi** [comment]
@LeonCheung Just took a look at the code, it actually just pastes every line in a paragraph even if it's empty.

**Comment by LeonCheung** [comment]
Then how to explain the GIF? 🤣

**Comment by OmrSi** [comment]
You missunderstood.
It just takes every line in the copied text and pastes it to a line in the list view.

Meaning if you have:
`Line1A
Line1B`
it will paste each line into a list view item, even if the line is a space.

**Comment by LeonCheung** [comment]
Ah I see. It puzzled me because I tried to follow your idea above step by step, but couldn't get the expected result, so...

**Comment by OmrSi** [comment]
That's my bad. I thought it worked that way.
Turned out I just copy the time with the text all the time, so I thought that was the default behavior.
I don't know which is better, tbh.

**Comment by LeonCheung** [comment]
It's okay just... it reminded me to a specific workflow in real life. Similar to what's mentioned in #1528. Maybe that's another topic.

**Comment by OmrSi** [comment]
I don't know if `Line break` is exactly right here, it should be something like `lines separator`.

**Comment by LeonCheung** [comment]
Ah yes, you are right.

**Comment by niksedk** [comment]
> I need to change all letters in words to uppercase.

Have you tried Tools - Change casing... ?

**Comment by OmrSi** [comment]
@niksedk He seems to have a letter at the end of the regex, so I guess he only wants to change certain words?

**Comment by borifax** [comment]
It is just like OmrSi says. I wanted to uppercase the text between "<<" and "Ł". These are descriptions for the hearing impaired, which I wanted to highlight in capital letters and in color. This is how they are presented in alphabetical order.

![image](https://user-images.githubusercontent.com/45988475/103150430-720a7b00-4774-11eb-9cd4-4a19736f1c5b.png)

**Comment by LeonCheung** [comment]
@borifax Very nice tip. I didn't know that plug-in, and it's very powerful, not sure @ivandrofly can see this.

**Comment by ivandrofly** [comment]
Here here... maybe have a option in HI2UC to allow user to define token for start&end  of HI?

**Comment by LeonCheung** [comment]
@ivandrofly Oh then it would definitely be even better if technically possible. :)
