### ISSUE TITLE
ASSA Manager color update issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4640]
Since this happens before the ASSA Manager refactoring work, we should make it a separate issue report.
The GIF below exposes two updating issues, not sure if they are caused by the same one:

![two-issues](https://user-images.githubusercontent.com/494788/103164329-d137c080-4844-11eb-91bb-8bacbbdbb9e7.gif)

Btw, I just wonder if the `Primary`column is necessary enough since we can already preview it from the color of the word `Text`.

**Comment by niksedk** [comment]
Tried to fix this in commit 8b574a04d5f0889d32ac278936c91c9cafbbb8d6

Is latest beta any better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Better, but the newly picked Outline color is still updated to Primary cell, unless close and reopen the window.

**Comment by niksedk** [comment]
thx - tried to fix the outline issue: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Well fixed. :)
