### ISSUE TITLE
OCR - Manual image to text

### ISSUE THREAD

**Issue by jpinto0** [SubtitleEdit/subtitleedit#4641]
Hi,
    I have a question about the behaviour of Subttitle Edit, specifically the way OCR is working.
    I have a bunch of mkv videos, ripped from DVD's with subtitles on it, for which I am using Subtitle Edit to extract them.
    For most of them so far, the process is straightforward, I choose "File -> Import subtitle from Matroska (mkv) file", then "Start OCR" and it goes through the video getting all subtitles. Looking at the way the OCR is working, I can see that it is recognizing one character at a time and works fine (see screenshots Snap-auto1.jpg and Snap-auto2.jpg).
    However, for some other videos, and using the same process in Subtitle Edit to import the subtitles from the mkv video, when I start OCR, it shows up a window entitled "OCR - Manual image to text", and asks me to manually enter the characters in the image as words, or parts of it. After doing it, when I click on the subtitle and choose "Edit image db", I can see that, instead of recognizing each character, OCR is attempting to recognize full words (or parts of them). Apart for the fact that it is cumbersome process, the worst aspect of it is that OCR does not recognize any spaces, so all the words (the ones recognized and the ones I had to enter the characters manually) end up as a single word (no spaces) and I have to manually correct them (see screenshots Snap-manual-[1-4].jpg).
   Since I have used the same process to rip these mkv videos and I am using the same Subtitle Edit session (thus, the same settings), is there a reason for the difference in behavior? And how can I "force" the OCR to be done without manual intervention?
   Thanks for the help.
[Sceenshots.zip](https://github.com/SubtitleEdit/subtitleedit/files/5744298/Sceenshots.zip)

**Comment by niksedk** [comment]
Some subtitles are impossible to OCR, and some requires some pre-processing...

Right click on image/list view and choose "Image pre-processing...":
![image](https://user-images.githubusercontent.com/1261331/103167465-99704f00-482b-11eb-8bc8-3cace24e54fa.png)

Also read this: https://www.nikse.dk/SubtitleEdit/Help#importvobsub

**Comment by jpinto0** [comment]
Ok, thanks a lot for the clear and quick direction. Regards.
