### ISSUE TITLE
3.5.18 has too many "0x00 invalid character..."

### ISSUE THREAD

**Issue by ZioPinjo** [SubtitleEdit/subtitleedit#4643]
![2020-12-27 16_12_11-New Issue · SubtitleEdit_subtitleedit — Mozilla Firefox](https://user-images.githubusercontent.com/76655660/103173952-8d51b500-485e-11eb-8044-85190f2aece4.png)

Changing the OCR method.

**Comment by niksedk** [comment]
Sounds like one of the name list xml files are corrupt - please uninstall (and make sure everything is delete) and re-install again.
