### ISSUE TITLE
Convert from vtt to srt - remove these extra lines

### ISSUE THREAD

**Issue by firebfm** [SubtitleEdit/subtitleedit#4644]
I download vtt from online drama websites. The vtt files come with lines such as WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:0. But when converted to srt, the lines are supposed to be removed. I have been using gotranscript subtitle converter to do it so I don't have to remove the lines manually. Please remove these lines. I have attached a vtt file.
[ep12.zip](https://github.com/SubtitleEdit/subtitleedit/files/5746428/ep12.zip)

**Comment by niksedk** [comment]
Hm, that's a very badly formatted vtt file... looks like multiple webvtt files has been merged without stripping the header.

Made a hack so the file will read okay in SE:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
