### ISSUE TITLE
ASSA Manager update issue 2

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4645]
Just found something else that don't update at once, similar to #4640.

1. `Italic `and `Underline` has no preview effect in Preview window.
2. the word "**Text**" in Outline column will not update at once for Bold, Italic, and Underline.

**Comment by niksedk** [comment]
thx :)
Beta (and code) updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
