### ISSUE TITLE
Window is forced to be maximized when importing things

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4647]
When importing things (File > Import...), the window is forced to be maximized, and window size cannot be changed or moved.  Lastest beta.

**Comment by niksedk** [comment]
Which window?

**Comment by LeonCheung** [comment]
All windows that require a file input. Okay. Try this: File > Open video file...

**Comment by niksedk** [comment]
There's no File > Open video file...

**Comment by LeonCheung** [comment]
Ah, sorry  I mean Video > Open video file. But wait, I just tried it on another PC, it works fine... So weird....

**Comment by niksedk** [comment]
Yes, I've tried most import windows and they look okay to me.

**Comment by LeonCheung** [comment]
I've just sent the screenshot via email. Hope you can help some...

**Comment by niksedk** [comment]
Sorry, SE cannot control this

**Comment by LeonCheung** [comment]
Sure. :)  Thanks anyway.
