### ISSUE TITLE
Some missing items for translation

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4648]
1:
![t1](https://user-images.githubusercontent.com/494788/103211986-9fa61e80-4944-11eb-98be-fdf95d655445.jpg)

2:
![t2](https://user-images.githubusercontent.com/494788/103211987-a16fe200-4944-11eb-9f66-21a7d45fd550.jpg)

3:
![t3](https://user-images.githubusercontent.com/494788/103211989-a2087880-4944-11eb-9c49-13128ce70070.jpg)

4:
![t4](https://user-images.githubusercontent.com/494788/103211990-a2a10f00-4944-11eb-9c91-f9d1f1969977.jpg)

5:
![t5](https://user-images.githubusercontent.com/494788/103211995-a6cd2c80-4944-11eb-8924-d8325133fcca.jpg)

6:
![t0](https://user-images.githubusercontent.com/494788/103211999-a9c81d00-4944-11eb-9afa-7fb0fa496237.jpg)
Not sure about the last one, anyway. :)

**Comment by niksedk** [comment]
thx :)
no 5 works here. 
hard-sub-ocr is a beta feature (not working)
The rest should be fixed
