### ISSUE TITLE
Dark theme for ASSA Manager

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4652]
I know it's WIP, just put it here: 
![GIF 2020-12-29 16-38-07](https://user-images.githubusercontent.com/494788/103271227-9c6a6b80-49f4-11eb-869e-6e1ef5e7f2e7.gif)

**Comment by niksedk** [comment]
sorry, winforms (what SE is built with) does not really support more than this...

**Comment by LeonCheung** [comment]
Hmm, just want to make sure we are on the same page, is that the reason why some texts appear dark while others don't? Even in the same panel:

![ee](https://user-images.githubusercontent.com/494788/103281126-03941a00-4a0d-11eb-998a-ec455c0081b9.jpg)

**Comment by niksedk** [comment]
yes...

**Comment by LeonCheung** [comment]
Got it thx
