### ISSUE TITLE
[Shortcut Suggestion] Merge with pre/next bilingual

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4657]
I know we have an existing shortcut called "Merge with selected lines bilingual", but every time when I try to merge two lines, I found that I have to select the two lines first before using this shortcut. I mean maybe we could possibly have two new shortcuts like:

```
Merge with previous bilingual
Merge with next bilingual
```

so that we don't have to do the selection step, especially when you have to do this quite often.

**Comment by LeonCheung** [comment]
@niksedk Could you help with this one, please?

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
Nice! Just one little bug here: Try this very simple example file: [bi-test.zip](https://github.com/SubtitleEdit/subtitleedit/files/9627839/bi-test.zip)

How to repeat: Select the first or the last line, then hit either one of the shortcuts.

It says the index is out of range or something...
![image](https://user-images.githubusercontent.com/494788/191806697-03e5abd3-63cb-4ea4-abff-840f099913cd.png)

**Comment by niksedk** [comment]
Thx - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip
Better?

**Comment by LeonCheung** [comment]
Perfect. Thank you so much! Closing.
