### ISSUE TITLE
Cursive in waveform text?

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4659]
Hi.
Don't you think that If the text is written in cursive, it also should be written in cursive on waveform preview?

When subtitling, I look mostly at the waveform and I often think that I forgot to put text in italic because the text displayed on waveform is always in default style.

![Clipboard01](https://user-images.githubusercontent.com/46628545/103418338-7d9fdc80-4b8e-11eb-8eb5-8b92d28a3f46.jpg)

**Comment by PMitsakis** [comment]
I agree with this. It would be nice to have changes done in the list view reflected in the waveform.
