### ISSUE TITLE
[f. Request] Japanese into Romaji and into Kana in 'autotranslate'

### ISSUE THREAD

**Issue by gitut2007** [SubtitleEdit/subtitleedit#4669]
Hi.  In case somebody can find and add an API for transliterating Japanese into Romaji and into Kana in 'autotranslate'.
In 'Google autotranslate' there is an option to 'Romanji', but it produces English.
In Web Google translate 'x' to Japanese = there's Romaji at the end , but not keeping the line breaks, so it seems unparseable for the timings.
Thx.

**Comment by eadmaster** [comment]
Was this implemented? I don't see any commit ref..
