### ISSUE TITLE
Videos are not loading MPV or VLC

### ISSUE THREAD

**Issue by gitut2007** [SubtitleEdit/subtitleedit#4674]
Hi.I don't often load videos in SE, but it used to work ok [win7 portable inst.], but now no video loads. mp4, avi, mkv...
I was using mpv ok [only sometines the audio level is too low, ok in external player].

So i put the latest VLC -portable [wich loads by itself the videos ok], and select that in SE, same as with mpv.
With both I do 'open video file', no crashes, nothing, and  'close video file' doesn't appear. 
Visual Sync tells 'no video loaded'
Only thing i have done lately was using 'bomi' which uses an outdated/custom mpv, but not installed, portable, and i closed it when the problem with SE v 3.18.
Since i was sure i had loaded videos in v 3.16 [i'm almost sure with v 3.18 too], i did a new portable with the old, but same. Also with latest beta.
in log:
Date: 01/04/2021 23:51:31
Message: Unable to load '' (also check libc.so.6 + libdl.so.2)

Date: 01/04/2021 23:51:31
Message: Not all required methods was found in libvlc

i don't have libc.so.6 or libdl.so.2 in Windows\System32
Thx.

**Comment by niksedk** [comment]
Do you install mpv via Options - Settings - Video player - Download mpv lib?

Try this VLC version: https://get.videolan.org/vlc/3.0.11/win64/vlc-3.0.11-win64.exe

**Comment by gitut2007** [comment]
Yes, Options - Settings - Video player - Download mpv was what was working previously, but nyway i did the from-SE-Download like this  again; 
/vlc-3.0.11-win64.exe is waat i put [portable, and it works with all the videos if i open it outside SE]

It seems unrelated to the video player; could it be related with .NET? i have 4.7.2 , it was the same when all was working,  have not done any change to .NET.

or with Visual C++? i have 2010 redistributable, 2013 redistributable, 2015 redistributable,  
 +- recently i added [because was needed by other program] 2015-2019 redistributable, [all both x86 and x64]. I don't remeber if i added it before using video ok in SE.
Thx.

**Comment by niksedk** [comment]
Try doing a clean install of SE + perhaps re-install your video card drivers + re-install the dot net framework. 
Something must be messed up....
Any luck with VLC or mpv after the above?

**Comment by gitut2007** [comment]
None works.
[so C++ has nothing to do with SE? it's the only change besides using bomi]
If i get it to work or something new happens, i'll inform. 
Thx.

**Comment by gitut2007** [comment]
I think it's the program that needed  Visual C++ 2015-2019 redistributable, [because it needed VCRUNTIME140_1.dll ]: https://github.com/crow-translate/crow-translate 
Why i think so? because sometimes, right after using it, if i 'suspended' Crow Translate with Task Manager, paste operations were screwed in all programs and SE was not-responsive ; i had to 'resume' it and wait a while until it finished some operation i guess, then i could suspend it, and paste and SE would be fine.

Now even if Crow is closed, SE video is not working, and CrowT has no 'uninstall' neither in its folder not in 'programs and features' there's an entry for it, and i'm not in the mood of a Win7 reinstall.
I'm pointing him to this, maybe it has nothing to do, but the way it afected SE before even when CrowT was 'suspended' makes me think now it may affect in a similar way Video even if CrowT is closed [or opened]. 

As an aside, CrowT works with Yandex translate as is, while in SE Yandex autotranslate asks for a credential.

**Comment by niksedk** [comment]
SE is written in C# and does not rely on VCRuntime (don't know about VLC and mpv but I doubt it)
You can try to enable logging for mpv by changing the value MpvLoggin to `True` in Settings.xml (look for `<MpvLogging>False</MpvLogging>`).
You can also check the Windows event log.

**Comment by gitut2007** [comment]
I re-installed .Net ... nope
Enabled logging for mpv, no log formed.

I'm suspecting this program https://github.com/Valyreon/Subloader [v 1.3.2 ; there are 2 newer releases] now: 
'Subloader is a simple and minimalistic software written in C# and .NET Core 3.1 ' ... 'Installer will also add an entry to right click context menu of .avi, .mkv and .mp4 files' 
i uninstalled it [but to complete the uninstall, i'm not restarting now because i'm not in a hurry to use video in SE [and for other reasons], if after a restart video in SE is fixed, i will post ]. 

Idk if this could be the reason: the install of v 1.3.2 altered these registry keys: 
HKEY_LOCAL_MACHINE\software\classes\systemfileassociations\.avi\shell HKEY_LOCAL_MACHINE\software\classes\systemfileassociations\.mkv 
HKEY_LOCAL_MACHINE\software\classes\systemfileassociations\.mkv\shell HKEY_LOCAL_MACHINE\software\classes\systemfileassociations\.mp4\shell
 HKCR\SystemFileAssociations\.avi\shell\Subloader
 HKCR\SystemFileAssociations\.mp4\shell\Subloader
 HKLM\SystemFileAssociations\.mkv\shell\Subloader

*If so*, could SE be made resilient/unaffected by changes to these registry keys? 

I might install the latest version 1.4 and see if it fixes SE, i will inform if so.
Thx.

**Comment by gitut2007** [comment]
idk if the uninstall of Subloader 'completed' while the pc was idle or what, but  video is loading now ok, and i have done  nothing more as per prev post, no restarting of pc...

**Comment by niksedk** [comment]
Stranger things has happened ;)

**Comment by gitut2007** [comment]
Hopefully someone else can confirm if indeed installing Subloader  can cause the video problem...
