### ISSUE TITLE
Shortcut question

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4675]
Hi.
Is there a shortcut that will extend end of subtitle by 1 frame forward until it reaches minimum gap and then will push (move on timeline) the next subtitle?
I hope you know what I mean :-P

@OmrSi

**Comment by OmrSi** [comment]
You can use:
![image](https://user-images.githubusercontent.com/20923700/103644263-c1b02a00-4f5e-11eb-837b-82470f6919e3.png)

Then when you reach the next subtitle use:
![image](https://user-images.githubusercontent.com/20923700/103644313-da204480-4f5e-11eb-84af-332618b06ac6.png)

**Comment by m0ck69** [comment]
Thanks.
