### ISSUE TITLE
scene change detection problem?

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4677]
Hello.
I'm not sure but I think SE have problems with proper recognition of scene changes.
I always use EZTitles to generate scene changes because I think it is most accurate.

Scene change should be the first frame of a new shot, right?
But SE shows scene change as the last frame of the shot so it's always one frame behind.
In other words, all scene changes sholud be moved forward by 1 frame.

I also tried generating SC in FFmpeg and it's the same.

**Now it is like this:**
![sc1](https://user-images.githubusercontent.com/46628545/103665858-32ae0c80-4f74-11eb-9121-138950aad3ae.jpg)

**Scene change should be here:**
![sc2](https://user-images.githubusercontent.com/46628545/103665358-a13e9a80-4f73-11eb-8da6-071e46547097.jpg)

**EZTitles recognizes sc properly.**
![ezt](https://user-images.githubusercontent.com/46628545/103666008-5c673380-4f74-11eb-9507-edfb88cb199f.jpg)

It looks like it's SE issue.
@OmrSi 
@niksedk

**Comment by OmrSi** [comment]
It happens with some videos for some reason, but not in others.
In my case, generating scene changes from SE using FFmpeg for some videos works fine, but importing them from EZtitles shows them one frame behind for some reason.
Up until now, I thought it might be a problem with the video itself...

**Comment by m0ck69** [comment]
Can't anything be done about it?
Maybe it's the matter of codec/resolution/extension?
EZTitles doesn't have problems with it whatsoever as shown in the last picture.

**Comment by OmrSi** [comment]
Can you attach the test file so I can do some tests?

**Comment by m0ck69** [comment]
Here you go:
https://1fichier.com/?91p1dyk1vcab9lnlknr6

**Comment by OmrSi** [comment]
Hmm, the file you attached works perfectly fine with changes generated from SE and EZtitles:
[test-shotchanges.zip](https://github.com/SubtitleEdit/subtitleedit/files/5771511/test-shotchanges.zip)

**Comment by m0ck69** [comment]
Not here. Still 1 frame behind.
![Clipboard01](https://user-images.githubusercontent.com/46628545/103677699-eae2b180-4f82-11eb-898a-05c753d1c5db.jpg)

Maybe I have old version of mpc or ffmpeg?
I never update those?

**Comment by m0ck69** [comment]
**I have updated mpv and it seems to be working!**

I'll do more tests tomorrow and let you know.

**Comment by OmrSi** [comment]
Sadly, my internet speed is real bad. I need about 7 hours to download the file.
Can you test PSA's version of the movie? I already have it downloaded.

**Comment by m0ck69** [comment]
Which version exactly? PSA has 3 versions on their site.

In the meantime I tried 720p version and it work fine. 1080p causes problems. Maybe resolution or the size is the issue. It's hard to tell.

**Comment by OmrSi** [comment]
Great, I have the 1080p version, I'll test and get back to you.

**Comment by OmrSi** [comment]
It's working well with PSA's 1080p version here.

**Comment by m0ck69** [comment]
I have do some tests. I have tested 4 different versions of the same movie: different resolutions, sizes, codec etc.
I've been checking only .xml scene changes generated in EZTitles.
Here are the conclusions:

movie no 1: 720p (x264), 4.4 GB - everything is OK
movie no 2: 1080p (x265), 2,12 GB - everything is OK
movie no 3: 1080p (x264), 5.88 GB - 1 frame behind
movie no 4: 1080p (x264), 11 GB - everything is OK


So what's the difference between movies 3 and 4?
Movie no 3 has chapters and cover jpg photo muxed in. I thought that those are causing 1 frame delay.
But I muxed them out for testing and it didn't help. There is still 1 frame delay in movie 3 no matter what I do.
Honestly, I don't know anymore.

Here is media info raport from movie no 4 which works fine:
[Wonder.Woman.1984.2020.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv.txt](https://github.com/SubtitleEdit/subtitleedit/files/5774777/Wonder.Woman.1984.2020.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv.txt)

Here is media info raport from movie no 3 which doesn't work: 
[Wonder Woman 1984.2020.1080p.WEB-DL.H264.DD5.1-EVO.mkv.txt](https://github.com/SubtitleEdit/subtitleedit/files/5774779/Wonder.Woman.1984.2020.1080p.WEB-DL.H264.DD5.1-EVO.mkv.txt)

It just bugs me. What does this stupid movie no 3 have that causes 1 frame delay?
There is no problem with other versions so there **must** be something inside this movie that causes this delay issue.

**Comment by OmrSi** [comment]
I guess that's why some people say EVO is bad? xD

It's really strange.

**Comment by m0ck69** [comment]
I guess so. Anyway, thx for trying to solve this. I guess this will remain a mistery... ;-P

**Comment by OmrSi** [comment]
Well, until I find a file that has this issue with a smaller size. xD

**Comment by chenlung** [comment]
One way would be to use Shutter Encoder's Cut Detection, deleting false positives and create an EDL list from there.
