### ISSUE TITLE
Suggestion about title case.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#4682]
Hello, since there are shortcuts for upper and lower case, how about adding one for title case? Thank you for SE!

**Comment by OmrSi** [comment]
There already is one, kinda.
![image](https://user-images.githubusercontent.com/20923700/103806928-606f8000-505e-11eb-998c-4ecd21826634.png)

**Comment by lambdacore12** [comment]
I cannot find the origin of your screenshot, but these are the shortcuts that I mean:
![Untitled](https://user-images.githubusercontent.com/37704802/103807373-93ae1100-5056-11eb-975e-7cd36c4348fb.png)

**Comment by OmrSi** [comment]
You should try the latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by lambdacore12** [comment]
Is that the same as 3.5.18?

**Comment by OmrSi** [comment]
This is a "Beta" version. It has more features which will be available in the next official version.

**Comment by lambdacore12** [comment]
OK, I'll give it a try. Should I close this issue?

**Comment by OmrSi** [comment]
I think so. Since the feature is already implemented. :D

**Comment by lambdacore12** [comment]
OK, got it.
