### ISSUE TITLE
Shortcut to Show/Hide subtitle in video player

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#4683]
Hello, is is possible to add a shortcut to show/hide the subtitles that display on the video, because sometimes, we may need to read something that is in the video but the subs will obstruct the view, so what we do is manually move out the sub out of the way of the player and then hit play to see the video. Thank you for SE!

**Comment by OmrSi** [comment]
@niksedk I swear this is not me. :3

**Comment by OmrSi** [comment]
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/3226

**Comment by lambdacore12** [comment]
Thanks @OmrSi !
