### ISSUE TITLE
Go back/forward a specified amount of time

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#4684]
In the shortcuts section, there are shortcuts to go back or forward one, five or three seconds. How about adding a dropdown menu to choose a set amount of seconds or milliseconds and then make a unified shortcut to go back/forward? Thanks for SE!

**Comment by OmrSi** [comment]
This should clear things up:

![image](https://user-images.githubusercontent.com/20923700/103883149-7d02cb00-50e5-11eb-8da3-684618a8261a.png)

**Comment by lambdacore12** [comment]
Thanks @OmrSi, awesome!
