### ISSUE TITLE
{\an1} tags randomly appear when reopening .scc files

### ISSUE THREAD

**Issue by singulararmchair** [SubtitleEdit/subtitleedit#4686]
This is a new problem with the latest version (3.5.18, Mono/Ubuntu). I've got {\an1} tags seemingly randomly appearing all over my .scc files whenever I open them. The file I'm working on seems fine when played in VLC after saving it. Haven't had this happen when working with .srt files.

**Comment by niksedk** [comment]
Could you attach a few samples?

**Comment by singulararmchair** [comment]
You have to change the extension to .scc , but this should do it.
I checked in VLC and it displays the first correctly without alignment problems. I merely opened the file and all these {\an1} appeared. For now I've reverted to using an older version of SE.
Is there anything in the settings that may cause this? I'm not seeing anything.

[2737078 - Zedd True Colors_orig.txt](https://github.com/SubtitleEdit/subtitleedit/files/5783509/2737078.-.Zedd.True.Colors_orig.txt)

[2737078 - Zedd True Colors_alignproblem.txt](https://github.com/SubtitleEdit/subtitleedit/files/5783512/2737078.-.Zedd.True.Colors_alignproblem.txt)

**Comment by niksedk** [comment]
Hm, it's because those lines really are left/bottom aligned :)

If you don't want that, the select all lines in the list view (ctrl+a), right-click, remove formatting, remove alignment

![image](https://user-images.githubusercontent.com/1261331/103938842-29b36b80-512b-11eb-9e16-91fb6f675931.png)

**Comment by singulararmchair** [comment]
Ah OK, must be because I got this from another source
