### ISSUE TITLE
Netflix Quality Check - Some adjustments for Dutch rules

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#4699]
@OmrSi 
Some quick notes referencing the updated Dutch rules for Netflix:
https://partnerhelp.netflixstudios.com/hc/en-us/articles/215350158-Dutch-Timed-Text-Style-Guide

- Reading speed: 17 characters per second
- When including ellipses in subtitles, please use the single smart character (U+2026) as opposed to three dots/periods in a row.
- If two characters speak in one subtitle, use a hyphen without a space to denote the second speaker only.

A general note:

"Frame gap: minimum 2 frames" and "Frame gap 3 to 11 frames => 2 frames":
I believe these are linked. So if a gap of 3 frames is used, the chaining should also be done with a 3 frame gap.
So, then the rule would be "Frame gap 4 to 11 frames => 3 frames".

Maybe add a gap setting box next to the language box, or follow the SE setting?

**Comment by OmrSi** [comment]
"Frame gap: minimum 2 frames" means a gap of 0 or 1 isn't okay, but a gap of 2 is.
"Frame gap 3 to 11 frames => 2 frames" means the gap must be 2 or 12.
It's 2 frames that are correct, not 3.

`Reading speed: 17 characters per second`

Should be an easy fix.

`When including ellipses in subtitles, please use the single smart character (U+2026) as opposed to three dots/periods in a row.`

Should be doable.

`When including ellipses in subtitles, please use the single smart character (U+2026) as opposed to three dots/periods in a row.`

This probably applies to all languages now, I just don't know if we need a separate check box for it or where to add it.

**Comment by Flitskikker** [comment]
> Should be an easy fix.

Great!


> This probably applies to all languages now, I just don't know if we need a separate check box for it or where to add it.

Looking through the guidelines for the different languages, it indeed seems to apply to all languages.
I would then just add a checkbox to the Rules in the NQC dialog, "Use ellipses instead of three dots".

**Comment by OmrSi** [comment]
I'm thinking about including it with the glyph check box, what do you think?

**Comment by Flitskikker** [comment]
I would make it a separate checkbox.
Both the dot and the ellipses are valid glyphs. It's just that 3 dots in a row need to be an ellipses character instead.

**Comment by OmrSi** [comment]
@Flitskikker Do some tests on the PR. :)

**Comment by Flitskikker** [comment]
@OmrSi 
Thanks! Will do some testing tonight.
