### ISSUE TITLE
[Suggestion]  Allow "Global" Mode Switch operation (Ctrl Left/Right)

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#47]
Currently, It seems that we havve to first click on any one of the **Translation/Create/Adjust** tab title, in order to use Ctrl + left or right key to navigate among these three modes. However, if the navigation just behaves like this, then it would be sort of meaningless. Isn't it?

In other words, it would be really nice to use these shortcuts to perform the mode navigation without having to have cursor focusing on that area.

(PS: I'm not so sure if this is my own problem, just fyi.:) )

![88](https://cloud.githubusercontent.com/assets/494788/2802869/5795fe74-cc93-11e3-868c-fd9930896dbc.png)

**Comment by OmrSi** [comment]
When you click on one of them, you don't need to use Ctrl, just the arrow.
I found it useful to use "focus on waveform" then arrows, it works.

**Comment by LeonCheung** [comment]
Strange behavior though, which makes the tip meaningless.

**Comment by OmrSi** [comment]
Yeah. Or he meant something else with it.
Let me ask you, what other secret shortcuts are there?
For example, I found out that each mode has its own waveform shortcuts,
when using Adjust, "T" plays from just before subtitle, "E" set end and go to next, "S" set start, "R" offset, "N" set end.
I didn't see them listed anywhere...
