### ISSUE TITLE
Style editor for .ass subs is missing settings for the Style Line

### ISSUE THREAD

**Issue by ChocOranger** [SubtitleEdit/subtitleedit#4701]
The style GUI windows for .ass subs do not contain nor save (for a loaded style) the following values which are in the .ass style line specification:

Spacing (this is so useful)
Scale X% and Y%
Angle
Font modifiers: Underline and Strikeout are missing
Encoding (for a font)

Can these be added please?

Also note that the GUI in settings differs from the GUI in Files>ASS Style setting. The latter being more complete.
Both should use the same GUI style.

**Comment by niksedk** [comment]
Should be added in latest beta - see https://github.com/SubtitleEdit/subtitleedit/issues/5084#issuecomment-854123311
