### ISSUE TITLE
Default profile for new .ass files

### ISSUE THREAD

**Issue by ChocOranger** [SubtitleEdit/subtitleedit#4702]
Can we have a default profile set for new .ass files please? Very useful for default resolution and the editing author / language. No point in having to fill them every sub. Users that don't need it can leave it as it is.

ie the details for File > AAS properties can have pre-filled defaults (including the resolution).
A loaded movie should override the defaults eg title and resolution. Although you could add a option not to do this.

**Comment by niksedk** [comment]
Default profile can now be made in the ASSA style manager:
![image](https://user-images.githubusercontent.com/1261331/108590612-be34fe80-7364-11eb-978c-32eb11f3ce0f.png)

Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by ChocOranger** [comment]
Currently , the beta Style Storage doesn't keep any of the properties in the Advanced Sub Station Alpha Properties windows.

I was asking for defaults here.
![Ass_properties](https://user-images.githubusercontent.com/77179521/108606524-67eeac80-73b2-11eb-8167-32dd805c08e1.png)

**Comment by OmrSi** [comment]
My bad, thought from the title it's for the styles.

@niksedk I guess this should be reopened, although I don't know if you're interested in doing defaults for the properties.

**Comment by ChocOranger** [comment]
I'd be happy enough for a default for the Resolution.
I sub for a single resolution and use black borders for any video that requires them.
