### ISSUE TITLE
shortcut doesn't respect gap

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4705]
Hi.
A quick question.
Does the shortcut "move start 1 frame back (keep gap to previous If close" work properly?
My gap is set to 2 frames but this shortcut seems to leave a bigger gap.
Look:

https://user-images.githubusercontent.com/46628545/104168922-12ac9c00-53ff-11eb-8735-520c09dc1750.mp4

@OmrSi

**Comment by OmrSi** [comment]
Yeah, That's how @niksedk meant for it to work.
`keep gap to previous If close`, he hardcoded `close` to 199 ms or smaller.

**Comment by m0ck69** [comment]
Well... I don't think it was a good idea to hardcode a gap. And why 199 ms and not 198 or 200 ms?
The gap is a variable value set in the settings and its length should be taken from there.
But thanks for your explanation.

**Comment by niksedk** [comment]
A minor bug...

(The `Min gap` has not existed forever... I've fixed it tons of places, but a few might be still left)

**Comment by OmrSi** [comment]
@niksedk This shortcut is pretty new. https://github.com/SubtitleEdit/subtitleedit/issues/4078#issuecomment-624071718
I'm sure that `Min gap` existed then.
That's why I thought it is intentional.

**Comment by niksedk** [comment]
It's not intentional.

**Comment by OmrSi** [comment]
Want me to change it?

**Comment by m0ck69** [comment]
@OmrSi 
Sorry for the offtop, but what's the name of the defaulf subtitle preview font?
It's not Adobe Devanagari.
![f2](https://user-images.githubusercontent.com/46628545/104299226-3fc38200-54c5-11eb-9bf7-1cd9ec2cc6da.jpg)

I mean this font.

![f1](https://user-images.githubusercontent.com/46628545/104299231-418d4580-54c5-11eb-935c-d7fd433d5511.jpg)

**Comment by OmrSi** [comment]
@m0ck69 Good catch.
It's actually Tahoma, which is the default.
