### ISSUE TITLE
Does Batch Convert work with FDX?

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4707]
Just tried but it seems you can add it to the list but nothing was generated.

**Comment by niksedk** [comment]
What is `FDX` ?

**Comment by LeonCheung** [comment]
Final Draft's .fdx format.

**Comment by niksedk** [comment]
It's text only... what did you want to happen?

**Comment by LeonCheung** [comment]
I was trying to convert tens of FDX files to custom format using the Batch Convert tool.
