### ISSUE TITLE
Toolbar button

### ISSUE THREAD

**Issue by PMitsakis** [SubtitleEdit/subtitleedit#4710]
Although everything is checked as shown in the settings, the only button that doesn't appear in the toolbar is the Netflix button,
as you can see in the images below.

![Στιγμιότυπο οθόνης 2021-01-12 173625](https://user-images.githubusercontent.com/63797709/104337003-b1b7bd80-54fd-11eb-847b-22c965a250bc.png)
![Στιγμιότυπο οθόνης 2021-01-12 173901](https://user-images.githubusercontent.com/63797709/104337028-b67c7180-54fd-11eb-8629-5010a9c5bf10.png)

**Comment by LeonCheung** [comment]
It only shows up when you are working on the related format, which makes sense, right?

**Comment by PMitsakis** [comment]
I didn't know that. Thank you very much.
