### ISSUE TITLE
Generating a waveform in background

### ISSUE THREAD

**Issue by jirih** [SubtitleEdit/subtitleedit#4712]
Currently generating the waveform blocks any possible work for long minutes.
This could be fixed by generating it in background.

The waveform tool does not have to be available during the generating. At least not for now. Later it would be nice if already processed parts were available for editing.

**Comment by niksedk** [comment]
ffmpeg is a lot faster than vlc... that might help a bit.

**Comment by niksedk** [comment]
Will be included in SE 3.6.5 - beta available here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
See Options - Settings - Waveform:
![image](https://user-images.githubusercontent.com/1261331/144746859-5de0a648-1f7c-495a-bd0d-e4608d11854a.png)
