### ISSUE TITLE
Cannot extend a subtitle duration

### ISSUE THREAD

**Issue by simsllama** [SubtitleEdit/subtitleedit#4734]
When I attempt to drag a part of subtitle across the waveform, this error pops up.
![image](https://user-images.githubusercontent.com/77080593/105058139-d1a33000-5a6d-11eb-9420-ac4d8f052870.png)
Does anyone know how to solve it?

**Comment by dintaap** [comment]
This is happening to me too. Did you manage to fix it?

**Comment by simsllama** [comment]
> This is happening to me too. Did you manage to fix it?

Hi! I closed the issue because I felt like an idiot. You need to insert a new subtitle like this:

![image](https://user-images.githubusercontent.com/77080593/105469888-c419c000-5c90-11eb-99bb-d125e9ead636.png)

So, there won't be any error when you modify a selection.
