### ISSUE TITLE
[Incompatibility] DCP SMPTE or Interop not respecting position

### ISSUE THREAD

**Issue by user024** [SubtitleEdit/subtitleedit#4735]
The DCP subtitles are read according to a first top-last bottom during import/opening.
So, if the sets of subtitles have the lower line entered first, the whole file will have the lines inverted, calling for a lot of work, to invert back to normal.
As an example:

```
<Subtitle SpotNumber="32" TimeIn="00:02:44:072" TimeOut="00:02:46:239">
   <Text HAlign="left" VAlign="bottom" VPosition="8">- You are welcome!</Text>
   <Text HAlign="left" VAlign="bottom" VPosition="14">- Thank you!</Text>
</Subtitle>
```
will end up as:
```
- You are welcome!
- Thank you!
```
That practically makes the subtitles unusable and you can figure out how time consuming is for a full feature if one has to mend the file.
And such examples (lower and then higher subtitle) are very often found in DCP subtitles, both Interop and SMPTE.

**Comment by niksedk** [comment]
Works fine here... perhaps you could attach a complete file?
Are you using latest version of SE?

**Comment by user024** [comment]
I would prefer not to publicly do so, since the subtitles are not mine to share, but -if I may- I will send you an email with a complete mxf file of English subtitles taken from the SMPTE DCP of a French movie.
The version is 3.5.18 on Windows 10.
Please, have a look.

**Comment by niksedk** [comment]
OK, it seems this line ordering was only implemented for "Interop"... should now hopefully be implemented for all DCinema formats: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

How does the above beta work for you?

**Comment by user024** [comment]
I tested it with the subtitle in question.
It did work just fine.
Thank you.

**Comment by niksedk** [comment]
You're welcome - and thx for verifying :)
