### ISSUE TITLE
SE 3.5.18 and 3.6.0 remove dialogue dash in single lines seems not to work. Linux version.

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#4760]
I am referring to the highlighted item in the screenshot below (Fix common errors)
![SE](https://user-images.githubusercontent.com/37562304/105930058-dd9d7c00-6083-11eb-8e36-5b87050cdede.png)

To ensure there is no internal conflict I have run this tool with only this option selected and it still does not work. Using the attached zipped srt file my expectation would be that, for example, lines 31 and 32 (and various others) would have the dash removed from the beginning of the sentence.

[Example.zip](https://github.com/SubtitleEdit/subtitleedit/files/5877177/Example.zip)

**Comment by OmrSi** [comment]
The dashes in your file are `HYPHEN (U+2010)` while the normal ones SE works with are `HYPHEN-MINUS (U+002D)`
You need to replace them or use the "Normalize" option in Fix Common Errors first.

**Comment by shag00** [comment]
Indeed you are correct, thank you.
