### ISSUE TITLE
Linux 3.6.0 Remove text for hearing impaired not working as expected

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#4762]
Assuming the 2 highlighted in the following screenshot items are missing (1)capitalised and (2) line
![SE1](https://user-images.githubusercontent.com/37562304/105936272-56a1d100-608e-11eb-838f-cd9754776a91.png)
and using the attached zipped srt file I still find that some instances are not removed, for example lines 1 and 4 among others.

I have run fix common errors/normalise.
[example2.zip](https://github.com/SubtitleEdit/subtitleedit/files/5877480/example2.zip)

**Comment by niksedk** [comment]
You probably need to un-check "Only if in seperate line"...

**Comment by shag00** [comment]
Unchecking "Only if in separate line"... makes no difference. The screenshot was of a new instance of SE so I could get a smaller screenshot. I have rerun the test and the anomalies remain.
