### ISSUE TITLE
[Feature Request] Position subtitles at video window

### ISSUE THREAD

**Issue by maknol** [SubtitleEdit/subtitleedit#4764]
Please, add an option to set subtitles position at video window, for example at top, not at bottom. When you have a hardsub subtitles movie is a good idea. Yes, i know, i can color it, but i need to see the hardsubs for corrections.

<a href="http://www.imagebam.com/image/5ed0e41368219798" target="_blank"><img src="https://thumbs2.imagebam.com/a0/78/90/5ed0e41368219798.jpg"></a>

**Comment by niksedk** [comment]
You can use the context menu to change alignment: 
![image](https://user-images.githubusercontent.com/1261331/106164623-79b1ab00-618a-11eb-9f89-77a539038e5e.png)

Or you can use this shortcut:
![image](https://user-images.githubusercontent.com/1261331/106164721-977f1000-618a-11eb-8644-26eefbea7d93.png)

**Comment by OmrSi** [comment]
@niksedk Do you think I should also add the vertical margin to the UI in my PR?

**Comment by OmrSi** [comment]
@niksedk Why should the user have to add a tag to each line in the file while you already have a player that allows the user to add a vertical margin to work on files like this?
I think such basic options should be accessible via the UI.

**Comment by maknol** [comment]
I was not talking for subtitles, but for the preview subtitles into SE video player. For positioning subtitles I know how to make it.

**Comment by OmrSi** [comment]
@maknol Yes, there was an option for MPV called "Margin Vertical" which adds a vertical margin to the subtitle in the preview, it can be found in Settings -> Ass style, but now it's gone.
I'm telling @niksedk that it should be exposed to the user so he can change it.

Anyway, if this PR https://github.com/SubtitleEdit/subtitleedit/pull/4756 is merged, you will find a hidden setting in the settings file called "MpvPreviewTextMarginVertical" which you can use to add a vertical margin to the video, you can also activate an opaque box that adds a back box to the subtitle.

**Comment by Maozai-Teng** [comment]
> @maknol Yes, there was an option for MPV called "Margin Vertical" which adds a vertical margin to the subtitle in the preview, it can be found in Settings -> Ass style, but now it's gone. I'm telling @niksedk that it should be exposed to the user so he can change it.
> 
> Anyway, if this PR #4756 is merged, you will find a hidden setting in the settings file called "MpvPreviewTextMarginVertical" which you can use to add a vertical margin to the video, you can also activate an opaque box that adds a back box to the subtitle.

YES,I have the same problem，and I can change the vertical margin in Settings -> Ass style(3.5.18 before), but I can't change this option in new version. 
I find the issue now, and you say a hidden setting in the settings file called "MpvPreviewTextMarginVertical" can work. But I can't find it in the setting.
Can you tell me the detailed solution? How to find the "MpvPreviewTextMarginVertical" and use it，THX~

**Comment by Maozai-Teng** [comment]
> > @maknol Yes, there was an option for MPV called "Margin Vertical" which adds a vertical margin to the subtitle in the preview, it can be found in Settings -> Ass style, but now it's gone. I'm telling @niksedk that it should be exposed to the user so he can change it.
> > Anyway, if this PR #4756 is merged, you will find a hidden setting in the settings file called "MpvPreviewTextMarginVertical" which you can use to add a vertical margin to the video, you can also activate an opaque box that adds a back box to the subtitle.
> 
> YES,I have the same problem，and I can change the vertical margin in Settings -> Ass style(3.5.18 before), but I can't change this option in new version. I find the issue now, and you say a hidden setting in the settings file called "MpvPreviewTextMarginVertical" can work. But I can't find it in the setting. Can you tell me the detailed solution? How to find the "MpvPreviewTextMarginVertical" and use it，THX~



> I don't know anything about what this does in practice, but this is what you do in order to find it. Close Subtitle Edit. Open your Subtitle Edit folder (the one where SubtitleEdit.exe is found). There's a file there called settings.xml. Open this file in a text editor and search for "MpvPreviewTextMarginVertical". Change the value (I don't know by how much, you'd have to experiment). Save the file. Now open Subtitle Edit and check the result.



> I don't know anything about what this does in practice, but this is what you do in order to find it. Close Subtitle Edit. Open your Subtitle Edit folder (the one where SubtitleEdit.exe is found). There's a file there called settings.xml. Open this file in a text editor and search for "MpvPreviewTextMarginVertical". Change the value (I don't know by how much, you'd have to experiment). Save the file. Now open Subtitle Edit and check the result.

OH! THX~ 👍 I have found it~
I changed the folder install location (E:\) when I installed the software, so I can't find it before.
I searched for this file called settings.xml, I found this file is in the %APPDATA%\Subtitle Edit，it is in C:\~
Anyway，Thank you very much again~👍👍👍
