### ISSUE TITLE
Batch conversion does not allow custom palette settings for VobSub

### ISSUE THREAD

**Issue by dgonyier** [SubtitleEdit/subtitleedit#4765]
For some VobSub file OCR attempts, I have to adjust the color palette options for tesseract to have any luck in processing the subtitles.  Batch convert feature does not allow changing of the color palette options so OCR conversion always generates garbage strings.

**Comment by kilorat** [comment]
I googled around to figure out if this setting existed and found this post. I'm sad to see its closed without comment as "won't fix", subtitleedit is such an amazing tool, but I can't use it to convert old DVD subs when there's hundreds of episodes without manually doing each one.
