### ISSUE TITLE
Subtitle edit: input string was not in a correct format

### ISSUE THREAD

**Issue by cylxx** [SubtitleEdit/subtitleedit#4771]
![image](https://user-images.githubusercontent.com/78300649/106381559-994c0c00-63f4-11eb-9a14-76a6e9847668.png)

When I try to view/ open a video, it pops out this message.
Does anyone know how to solve it? :(

**Comment by niksedk** [comment]
Could you try latest beta and see if the problem has been solved?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by cylxx** [comment]
> Could you try latest beta and see if the problem has been solved?
> https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

OMG It's works! Really appreciate your response T.T 
Do you have any idea how this issues appeared?

**Comment by niksedk** [comment]
Seems to be caused by video without audio tracks.
Was fixed here: https://github.com/SubtitleEdit/subtitleedit/commit/bd49294ec12ac184e4dd7bb1a87a112634d9529f
