### ISSUE TITLE
Fix Common Errors - dash dialogue still not working.

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#4772]
Last update I am using is 3.5.11 27/10/2019.
Ever since then it has all gone wrong.

```
- You can't talk either.
That's what I said.

```

No longer add dash to second line since 3.5.11. should be 

```
- You can't talk either.
- That's what I said.
```

**Comment by niksedk** [comment]
Is this any better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by Ding-adong** [comment]
A nice morning present thanks.

```
- You can't talk either.
That's what I said.
```

Worked.

However 

```
- Right.
It's ok, you can do it.
```

doesn't work, became 

`- Right. It's ok, you can do it.`

FCE sees the above less than 1 line max. ie mine being 34 thus treated as a single dialogue. The first example above was over 34.

**Comment by niksedk** [comment]
cool, thx for testing :)

It's a sick dialog... so I think this is okay. You can always run dialogs dash fix first (there might also be a plugin for this).

**Comment by Ding-adong** [comment]
What did you meant by sick dialogue?

```
- Right.
It's ok, you can do it.
```

suppose to be 

```
- Right.
- It's ok, you can do it.
```

There is a way around this by disabling remove line breaks in short texts (all except dialogues) then run FCE then enable it again and run FCE again. A bit of a pain.

**Comment by niksedk** [comment]
Sorry, perhaps `sick` was a little strong... it is `uncommon` though.
