### ISSUE TITLE
Move selected lines 10s

### ISSUE THREAD

**Issue by PaulMoscow** [SubtitleEdit/subtitleedit#4773]
Good day!
Additional feature urgently needed 
[Now we have:](https://user-images.githubusercontent.com/20923700/98935315-059d2a80-24ec-11eb-9c48-17500c0c6dbd.png)
Move selected lines 100ms back
Move selected lines 100ms forward

Need:
Move selected lines 10s back
Move selected lines 10s forward

(10 second back and 10 second forward)

Thank you very much!

**Comment by OmrSi** [comment]
I think right now, this can be easily achieved by one of two methods:
1. Select the lines, use `Synchronization -> Adjust all line`, choose `Selected lines only` then set the time to 10 seconds and show them earlier or later.
2. Select the lines, move 10 seconds back or forward, click F9, it will offset the selected lines only.

**Comment by PaulMoscow** [comment]
Thank you very-very-very much!
