### ISSUE TITLE
How to change srt preview color in MPV?

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#4774]
Newer beta versions doesn't allow this happen.
I can see the srt preview on video in white color only.
It seems impossible to change.

**Comment by OmrSi** [comment]
It is no longer possible to change MPV's preview color from the UI, instead, you need to open your settings file and change it manually from a line called: `MpvPreviewTextPrimaryColor`

@niksedk This is why I wanted the options to remain in the UI, many people use them.

**Comment by Andrebavila** [comment]
> It is no longer possible to change MPV's preview color from the UI, instead, you need to open your settings file and change it manually from a line called: `MpvPreviewTextPrimaryColor`
> 
> @niksedk This is why I wanted the options to remain in the UI, many people use them.

Thank you, OmrSi!!

**Comment by niksedk** [comment]
The video player preview font settings are now under "Video player" which is hopefully more intuitive than a using "ASS/SSA style" settings which was a little magical/secret/illogical.

**Comment by OmrSi** [comment]
@niksedk That's how it was in the main PR. 
![106356360-b9ea6800-6307-11eb-92e7-02593243a4c5](https://user-images.githubusercontent.com/20923700/106478361-cad6dd00-64b1-11eb-9649-9a656d29fd00.png)

**Comment by niksedk** [comment]
Cool, it's basically the same :)
Hopefully more than enough...

![image](https://user-images.githubusercontent.com/1261331/106479537-b7744380-64aa-11eb-9200-aa8995f2b288.png)
