### ISSUE TITLE
Play rate (speed) stopped working

### ISSUE THREAD

**Issue by TheCordatus** [SubtitleEdit/subtitleedit#4777]
Hi. I have been using the SubtitleEdit for over a month now and for a new user it works great and very easy to use.
Not sure what happened but since yesterday **Play rate (speed)** button stopped working, if I click on it nothing happens. I've tried to reset the setting to default and reinstall the software but it's still not working.  The only change that comes to mind is updating the VLC to the latest version if that might cause the issue. I am using the latest SubtitleEdit 3.5.18 on Windows 10. 
I tried to look for answers online but it seems no one had this kind of issue before. So forgive me for asking, but what I am doing wrong here? Thank you

**Comment by niksedk** [comment]
SE only allowed 200% speed... fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by TheCordatus** [comment]
Thank you for very prompt response. 
Actually what I meant is if when clicking the **Play rate (speed)** button, normally it would show the percentage of speed where one can go at lower or faster speed. But now the button just doesn't respond, no numbers would pop up when the green double arrow button is clicked.
I often need to use the 80% or 90% speed because the videos I subtitle often have very fast dialogues, so actually need to reduce the speed to be able to hear more clearly. Thus I am confused if perhaps I switched off that feature by mistake (if that's even possible) or why would that feature stop working. Everything else works fine. Reinstalling the software didn't work.
Thank you very much and apologies if this is too troublesome.

**Comment by niksedk** [comment]
Did you install the 64-bit version of VLC? 
https://get.videolan.org/vlc/3.0.12/win64/vlc-3.0.12-win64.exe

I normally use mpv video plaoyer in SE.

**Comment by TheCordatus** [comment]
Yes I installed the 64-bit version of VLC, I even reinstalled the VLC making sure it's 64-bit, then also tried to revert to previous version but didn't change the outcome.

I tried MPV but **Play rate (speed)** button remain unclickable. 

Not sure what I am doing wrong.

**Comment by TheCordatus** [comment]
Hi, just wanted to give you an update. 
Today the **Play rate (speed)** button isi once again functioning normally, no clue how that happened since I didn't alter anything was just using Subtitle Edit as always. 
So many thanks for your time trying to help finding the solution and of course for developing this very useful software.
