### ISSUE TITLE
Subtitle Edit Portable on a Drive

### ISSUE THREAD

**Issue by Hayholten** [SubtitleEdit/subtitleedit#4779]
Hello everyone and @niksedk ;)

Quick question: I put the latest portable version of Subtitle Edit in a Drive so that I can access all my parameters on the different computers I use it on.

What should I change in the folder for the next update to avoid overwriting this configuration? Just the ".exe" file?

Thanks a lot for your answer!

Best,
Thibault

**Comment by niksedk** [comment]
@Thibault: I think it's best to download the portable version (make sure it does not contain settings.xml) and unpack and overwrite files.
Perhaps also avoid overwriting the `OCR` and `Dictionaries` folders, if you made many modifications here.

**Comment by Hayholten** [comment]
@niksedk Thanks for your answer.

It sounds a little bit tricky to care about what you can easily upgrade and what you can't regarding the different folders involved like : Spectrograms / Dictionaries / AutoBackup and others.

But I use Beyond Compare so I'll find a simple solution to do that. By the way, I'm also using [https://portableapps.com/](url), maybe a Subtitle Edit integration for an easy way to update will be someday possible ?

Final thing: I have noticed that some parts of the software are not translated for French users like me. Are you looking for french translators? Maybe I coul help ;)

Anyway, thanks again for the support and your work.
Best

**Comment by niksedk** [comment]
@Hayholten: Yes, it's not totally straightforward to update a portable version if you have made changes to word lists or Latin ocr db, but for most users it is fine just to overwrite existing files with files from the new portable version.

Yes, definitively could need help with the french language file: https://github.com/SubtitleEdit/subtitleedit/blob/master/src/ui/Languages/fr-FR.xml
You can use e.g. XmlContentTranslator to fix the missing tags: https://github.com/SubtitleEdit/XmlContentTranslator/releases
The current English language file is here: https://github.com/SubtitleEdit/subtitleedit/blob/master/LanguageMaster.xml
