### ISSUE TITLE
nOCR detecting noise as letters / changing capitalization

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#4780]
Hello! I've been trying the new nOCR method, but it doesn't seem to handle noise (e.g. from VideoSubFinder) very well.
I created a new database using the latest beta and fed it the following image:

![sample](https://user-images.githubusercontent.com/3516155/106902198-d700ab80-66f8-11eb-8d3d-b3c4b61788c5.png)

It has some dots for which I pressed "Skip", so it will add an asterisk.
However, afterwards, after clicking "Start OCR" again, it detects one of the dots as an "a", and it changed the "o" with the dot to an "O", while there is no "O" in the database.

![image](https://user-images.githubusercontent.com/3516155/106901993-9bfe7800-66f8-11eb-9daf-fe21effe978e.png)

When setting "Max wrong pixels" to 0, it asks for both dots again so I can skip them, but it still changes the o into a capital O.
The noise-dots are a lot smaller than any characters in the database, so I suppose it shouldn't detect letters when "Max wrong pixels" is higher.

Am I missing a guessing setting somewhere?

Sample image and database file:
[nocr.zip](https://github.com/SubtitleEdit/subtitleedit/files/5926150/nocr.zip)

**Comment by Purfview** [comment]
Where from do you get such image?

**Comment by darnn** [comment]
Presumably, as they said, from the program VideoSubFinder.

**Comment by Purfview** [comment]
> 
> 
> Presumably, as they said, from the program VideoSubFinder.

Is there option to get non inverted images? I don't remember such there.
Anyway try https://github.com/Purfview/InpaintDelogo , it was designed to do better than VideoSubFinder, there is option to remove such noise.

**Comment by darnn** [comment]
Looks interesting! I believe there is some kind of option to invert the colors in SE, if you right-click the image. It's been a while since I've tried. I may or may not have just done it manually myself before imported the VideoSubFinder images the last time I did it.
