### ISSUE TITLE
[Feature Request] Custom Colors for Syntax Highlighting

### ISSUE THREAD

**Issue by coding-hobby** [SubtitleEdit/subtitleedit#4781]
Just wondering if we can get to use different colors for syntax highlighting.

The tool allows syntax coloring.  Currently, all error types are displayed with the same color.  Suggesting if the user gets to choose the custom color for each type of error, in the below syntax coloring windows.

![image](https://user-images.githubusercontent.com/19731090/106909300-290bf600-6726-11eb-85ba-20c1cc0b521f.png)

**Comment by Flitskikker** [comment]
This is a good idea -- I particularly liked the configurability of the syntax coloring in SubtitleWorkshop before switchting to SE.

![image](https://user-images.githubusercontent.com/3516155/106941010-8c942480-6722-11eb-928f-e9f31a8468ed.png)

However, it would be A LOT of work to implement something close to this.

**Comment by OmrSi** [comment]
@Flitskikker Where are these options in SW exactly? I have (6.0b), don't know if there is a newer version, I thought development stopped after that?

**Comment by Flitskikker** [comment]
@OmrSi 
I have 6.0a. You can find them here:
![image](https://user-images.githubusercontent.com/3516155/106942845-ef86bb00-6724-11eb-89db-16b194027e4a.png)

**Comment by nimma-vk** [comment]
The latest version of SW is 6.0e.  here are the links: https://www.videohelp.com/download/Subtitle_Workshop_6.0e_setup.exe
https://www.videohelp.com/download/Subtitle_WorkShop_6.0e_Portable.zip

**Comment by LeonCheung** [comment]
Actually, I've suggested something similar years ago, #2383. I can see that dev's idea was trying to distinguish errors by column. But anyway,  worth discussing.

**Comment by m0ck69** [comment]
@OmrSi Can you also add option to syntax coloring: Color line if there is live spell check error.
For instance I have a sentence: "hleb is tani" (it should be "chleb is tani)

So I'd like to have line 60 in red so that I won't miss the error.
![Clipboard01](https://user-images.githubusercontent.com/46628545/107192011-5b02ae00-69ed-11eb-803c-71f3f73296ed.jpg)

**Comment by OmrSi** [comment]
@m0ck69 That's a good idea, I will do it if @niksedk gives me the OK, but it would be for the next version. (A bit busy with exams right now)

**Comment by niksedk** [comment]
>m0ck96 wrote:
> Also, there should be a filter to show only flawed lines to fix, like:
> show lines with a spelling error, show lines with too short gap etc

You can use the list view shortcut "Go to next error (F8)". 
Perhaps an overview window could be made.

"Color line if live spell check error" is fine in a future version.

**Comment by niksedk** [comment]
By the way... the SW screenshot will *NOT* be implemented in SE. 
IMO it belongs in the bad-UI-hall-of-fame :)
