### ISSUE TITLE
Laggy Dragging Issue with Syntax Coloring

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4785]
Actually, I noticed it for a while in the recent beta but finally figure out how to reproduce it:

https://user-images.githubusercontent.com/494788/107175723-88108a00-6a08-11eb-8836-884329834c15.mp4

For an UNSELECTED line with duration error colored, the lag would occur when dragging it.

**Comment by m0ck69** [comment]
I also had problems with laggy waveform. https://github.com/SubtitleEdit/subtitleedit/issues/4754#issuecomment-774634035
But the latest beta seems to sove the issue although I didn't checkt it check thoughtfully yet.

**Comment by niksedk** [comment]
Also, subs with too short duration lags... (not a new thing though)

**Comment by niksedk** [comment]
Should be fixed in c8cae57beb9e2f1a9194ffc8be27c2f8a8081435

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Yep, lagging solved, but new issues arise:


https://user-images.githubusercontent.com/494788/107310778-0f710280-6ac8-11eb-98a7-9cb3060be5b3.mp4

**Comment by niksedk** [comment]
> 
> 
> Yep, lagging solved, but new issues arise:
> Also, adjusting window size will also cause something strange.

Hm, I cannot re-create this. Any ideas?

**Comment by LeonCheung** [comment]
I think its a bit tricky, but maybe try this:
https://user-images.githubusercontent.com/494788/107321898-5ec22d80-6ade-11eb-9040-66686383a3c5.mp4

**Comment by niksedk** [comment]
OK, still could no re-create this... is latest beta better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.17/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Problems gone. So far so good. :)

**Comment by niksedk** [comment]
Nice, thx for reporting and testing :)
