### ISSUE TITLE
♪ is not understood and converts into "J" or "§" or "&"

### ISSUE THREAD

**Issue by wellloaded** [SubtitleEdit/subtitleedit#4786]
As per title, there are some subtitles that are "singing text"
These start/end/both with either ♪ or ♫
SE out of the box seems to convert the minot "J" or "§"

Two questions:

- can SE consider this case?

- Given I OCRed an idx/sub and I have the result in front of me, I have added the "J to ♪" to the "Add pair to OCR replace list". Is there any way to apply the manual rule to the already OCRed text (preferred) or do I have to re-OCR the file from scratch?

Thanks

**Comment by niksedk** [comment]
Hi,

What OCR method are you using?
Could you attach the sub or a few images with music nodes?

In "Edit -> Multiple replace..." you can do some advanced replacements with preview:
![image](https://user-images.githubusercontent.com/1261331/107189493-c3e82700-69e9-11eb-97b9-5b1c277c7c1d.png)

**Comment by wellloaded** [comment]
Engine mode: default
I have added the OCR substitution so what you see on screen is nor re-OCRed, still you'll find some notes OCRed as "&" and "I

![image](https://user-images.githubusercontent.com/46318040/107196225-a53a5e00-69f2-11eb-89a3-0600f298cf5b.png)

![image](https://user-images.githubusercontent.com/46318040/107196294-bedba580-69f2-11eb-9538-81994fcd2b47.png)

![image](https://user-images.githubusercontent.com/46318040/107196325-cac76780-69f2-11eb-9469-b965d4be11b7.png)

**Comment by niksedk** [comment]
Tesseract 5 has poor support for the music symbol, sorry. 
I cannot fix this, as it's a Tesseract 5 issue.

Perhaps the OCR method "Tesseract 3.02" will work better for you?
