### ISSUE TITLE
Improve SE page on wikipedia (avoid deletion)

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#4787]
If someone good at Wikipedia could improve the SE article, that would be nice... otherwise the article will be deleted:
https://en.wikipedia.org/wiki/Subtitle_Edit

**Comment by nimma-vk** [comment]
@niksedk I'm not good at Wikipedia. I will try to improve it

**Comment by niksedk** [comment]
Found one article:

Open Source Subtitle Editor Software Study for Section 508 Close Caption Applications
https://ntrs.nasa.gov/api/citations/20140002618/downloads/20140002618.pdf?attachment=true


_"Subtitle Edit is the best subtitle creator option because it  allows the user to create a  transcript to embed into a desired video file. With Subtitle Edit's feature a user can customize the display of the subtitles, and review how they would look inside of Subtitle Edit's video preview terminal. Additionally Subtitle Edit gives NASA the option to convert all English subtitle files into other languages, for audiences of other countries."_

**Comment by nimma-vk** [comment]
Are you asking about the wikipedia page?  they are already referring to http://www.nikse.dk/home/Details/633550870660000000

do you want them to link to any another page on your website?

**Comment by niksedk** [comment]
I'm not sure, but linking to nikse.dk is perhaps a bad idea? 
_This article relies too much on references to primary sources_

**Comment by nimma-vk** [comment]
It is always a best practice link the original website.  However, I do see here are four links which refer to the same webpage http://www.nikse.dk/home/Details/633550870660000000
I think that is what the wikipedia is flagging.  Let me look into the same.

**Comment by nimma-vk** [comment]
I think, it would be to remove 3 of those and leave a single link to the sikse.dk page.

**Comment by chenlung** [comment]
The part about being the best looks wrong because it’s in bold and not neutral.

**Comment by niksedk** [comment]
> 
> 
> The part about being the best looks wrong because it’s in bold and not neutral.

Yes, sounds non neutral... feel free fix :)

**Comment by chenlung** [comment]
Done. It's better (might ward off threats of deletion in the meantime), but people are free to improve upon it.

**Comment by chenlung** [comment]
A new graphic is needed for the page (current one doesn't seem high resolution).

**Comment by cyzs233** [comment]
There is actually a Subtitleedit guide [written by Ted talks](https://translations.ted.com/How_to_subtitle_offline), this should be something.
