### ISSUE TITLE
Throws error when opening dropdown menus

### ISSUE THREAD

**Issue by DJHellduck** [SubtitleEdit/subtitleedit#4792]
Subtitle edit throws this error when i try to open certain dropdown menus. Pressing "cancel" terminates the program, "try again" just shows the error message again, while "ignore" lets me continue for a little while longer, before throwing the error message again. 

![image](https://user-images.githubusercontent.com/22552788/107498370-fc2b6900-6b93-11eb-8650-9e991255c88c.png)

**Comment by OmrSi** [comment]
Can you try the latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

**Comment by DJHellduck** [comment]
3.5.18 is the one i'm currently using. The best way to provoke this error wqas to hover the mouse over the video dropdown. I don't have a video file mounted, but a srt and a mks file.

**Comment by DJHellduck** [comment]
Ok, downloaded the beta, and the error doesn't immediately appear. Also, it now loads a video file when opening the srt, which it didn't before. 

Will use this build a bit more, and post an update if the error keeps showing up.

**Comment by OmrSi** [comment]
There is an option in the settings for this:
![image](https://user-images.githubusercontent.com/20923700/107509924-e9bd2980-6bab-11eb-9893-267dead0daea.png)

**Comment by niksedk** [comment]
I think this issue was fixed in this commit: https://github.com/SubtitleEdit/subtitleedit/commit/bd49294ec12ac184e4dd7bb1a87a112634d9529f

**Comment by OmrSi** [comment]
It's been about 800 commits since the last version, a lot of issues must have been fixed.

**Comment by DJHellduck** [comment]
Allright, great! Looking forwards to the next version release then :)
