### ISSUE TITLE
Invalid italics tag

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4794]
Hello,
This feature has been a life saver for over the years, but recently I came across a few errors that it doesn't pick. 
[Error i.txt](https://github.com/SubtitleEdit/subtitleedit/files/5968640/Error.i.txt)

698 and 700 have invalid italics tags, but Fix common erros doesn't recognize those. Solution?

**Comment by OmrSi** [comment]
Where are the tags exactly?

**Comment by uckthis** [comment]
@OmrSi 
[i.txt](https://github.com/SubtitleEdit/subtitleedit/files/5968631/i.txt)

**Comment by Rafawell** [comment]
@OmrSi You could add a two-pass mode, one using lstm (which works great) and the second pass just with tesseract to add italics to the words. Can this be implemented?
In this second passage, put the tesseract just to search for the Italics, and modify the result obtained with the lstm.
Thank you very much.
