### ISSUE TITLE
Remove blank lines when opening a Subtitle

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4795]
I have this option turned off, but still when I open a file, any blank subtitles are automatically deleted. I'm editing  some SCC files and need those blank lines. Any workaround?

**Comment by ivandrofly** [comment]
Have you tried this?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/c3476b7c-612e-46f2-b4f6-c8909283afe3)
