### ISSUE TITLE
The program does not create spaces between words.

### ISSUE THREAD

**Issue by Gotas10** [SubtitleEdit/subtitleedit#4796]
Why doesn't the program create spaces between words when I'm converting a .SUB subtitle to SRT?
Every time I type the words it doesn't recognize, I have to add the spaces manually, any solution?

**Comment by niksedk** [comment]
Are you using OCR via "Binary image compare" or "nOCR"?

"No of pixels is space" should be decreased if not all translated words are separated (like "wearefine."), and increased if there are too many separations (like "w e ar e fi n e.").

See more here: https://www.nikse.dk/SubtitleEdit/Help#importvobsub
