### ISSUE TITLE
[Feature Request] Select all Lines with bookmarks

### ISSUE THREAD

**Issue by moob158** [SubtitleEdit/subtitleedit#4798]
it's no longer necessary, I've already figured it out.

**Comment by OmrSi** [comment]
Did you find a way?

**Comment by moob158** [comment]
@OmrSi  yes.

I add code to Main.cs

first add an item to _bookmarkContextMenu

then add this:

`private void SelectBookmark()
        {
            try
            {
                for (var i = 0; i < _subtitle.Paragraphs.Count; i++)
                {
                    var p = _subtitle.Paragraphs[i];
                    if (p.Bookmark != null)
                    {
                        SubtitleListview1.Items[i].Selected = true;
                    }
                }
            }
            catch
            {
            }
        }`

**Comment by OmrSi** [comment]
Oh, it was code then.
I thought you were able to do it via something already implemented.

**Comment by moob158** [comment]
I don't know much about c# but it works ;)

**Comment by OmrSi** [comment]
I was thinking of adding it to "Modify Selection", would that be a good idea?

**Comment by moob158** [comment]
@OmrSi yes.

I had looked there to see if there was an option, but there isn't.

**Comment by OmrSi** [comment]
I will work on it and open a PR then.
