### ISSUE TITLE
Linux command line operations?

### ISSUE THREAD

**Issue by wellloaded** [SubtitleEdit/subtitleedit#4805]
I would like to use SubtitleEdit in command line mode on linux.

I have tried an **apt install subtitleedit** which seems to work but I now don't seem to be able to call the program with any parameter (not even help) as it tries to open the Gtk by default. I don't have the linux graphial interface as this is a NAS.

What is the correct syntax to command line SE in Linux please?

Thanks

**Comment by WaLLy3K** [comment]
Give this a go and see how it works: https://github.com/SubtitleEdit/subtitleedit/issues/3568#issuecomment-680327040

**Comment by niksedk** [comment]
See https://github.com/SubtitleEdit/subtitleedit-cli
