### ISSUE TITLE
Wrong EBU STL Header properties

### ISSUE THREAD

**Issue by BlankProgramming** [SubtitleEdit/subtitleedit#4806]
Hello,

When checking for EBU STL header properties, I ran into the following issue : some values seems wrongly read by SubtitleEdit

![image](https://user-images.githubusercontent.com/9356022/108046331-c7f8f200-7044-11eb-9d3d-77e839c49aee.png)

using the GSI specification here : https://tech.ebu.ch/docs/tech/tech3264.pdf and reading byte per byte my STL file, the values are looking good to me (ASCII representation of the bytes in excel) : 

![image](https://user-images.githubusercontent.com/9356022/108046926-7d2baa00-7045-11eb-99f0-7cae7407c8eb.png)
![image](https://user-images.githubusercontent.com/9356022/108046752-46559400-7045-11eb-8f9f-b96e6f65ac5f.png)
![image](https://user-images.githubusercontent.com/9356022/108046673-2de57980-7045-11eb-81d5-c4fff4f809df.png)

I may be wrong as I'm not an expert but I think you should check. I have attached the STL
[SerieClub.fr_SECL00_6336_22203061.zip](https://github.com/SubtitleEdit/subtitleedit/files/5987704/SerieClub.fr_SECL00_6336_22203061.zip)

Regards,
Emilien

**Comment by niksedk** [comment]
Hi Emilien,

thx for the info :)
I've tried to fix the issue here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
Does that work for you?

**Comment by BlankProgramming** [comment]
Hi Nikolaj,

I just checked with various input STL on my side, I think everything looks OK now !

Thanks for you quick fix i'll be using the beta version until release :)

Regards,
Emilien

**Comment by niksedk** [comment]
thx for testing :)
