### ISSUE TITLE
Vlc cannot load

### ISSUE THREAD

**Issue by ikaman** [SubtitleEdit/subtitleedit#481]
When i try to use VLC the field is disabled although I have VLC on my system. 

I have traced this problem to 
_libVlcDLL = NativeMethods.LoadLibrary(dllFile);

in libvlcdynamic.cs

When i did 
int a = Marshal.GetLastWin32Error();
I got 193 which should be
"x000000C1 ERROR_BAD_EXE_FORMAT %1 is not a valid Win32 application."

Not sure why that is. 
dllfile is "C:\Program Files (x86)\VideoLAN\VLC\libvlc.dll" which exists

I have vlc 2.1.5 32 bit on 64 bit system

**Comment by ikaman** [comment]
It seems that the problem is when using vlc 32 bit on 64 bit system.

When I reinstalled 64 bit vlc on 64 bit system it worked. 

Although I was still call this an issue because many people with 64 bits windows have 32 bits vlc (64 bit vlc is not the automatic install from the website you actually have to find it in the download area)

**Comment by xylographe** [comment]
If, in the top right corner of the media player settings dialogue, it says "64-bit", that is a clear indication that you cannot use 32-bit libraries. This limitation is true for any application.

**Comment by ikaman** [comment]
ok good enough for me :)
