### ISSUE TITLE
"Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#4810]
I think this was after dragging and dropping a subtitle file, but it was a couple of days ago so I'm not sure.

![se-error](https://user-images.githubusercontent.com/19672444/108397149-56759b00-7220-11eb-8964-32135b302480.png)

**Comment by niksedk** [comment]
SE 3.6.0 is out - can you re-create the issue?

**Comment by darnn** [comment]
I don't think so, I can't even recreate it in the same version I was using, unfortunately. I just thought the error message itself might give you some indication as to what actually caused it. The beta I'm using is from about three weeks ago, if it was any older I wouldn't even post an issue.

**Comment by niksedk** [comment]
I will close this for now... please re-open if you find a way to re-produce this
