### ISSUE TITLE
(Suggestions) Move `Use Dark theme` outside "Fonts", as separate entry + automatically switch theme to match system

### ISSUE THREAD

**Issue by darkred** [SubtitleEdit/subtitleedit#4811]
I've just updated to SE 3.6.0. Thanks for all your work, and especially the dark theme.

I have two suggestions, now that the dark theme is finally out of beta in the new version:

1. move the `Use Dark theme` group outside "Fonts". In it's current place, inside `Fonts`, I find it very hard to discover: [screenshot](https://user-images.githubusercontent.com/723651/108400509-f123a900-7223-11eb-800f-fe5a48d4fe7d.jpg).
I believe it deserves its own Settings entry, 'Appearance'. 
2. offer an extra option in the `Use Dark theme` group, to automatically switch theme to match system theme.

**Comment by niksedk** [comment]
Not a complete fix, but the "Settings name" if now "Appearance" in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
