### ISSUE TITLE
Broken theme color

### ISSUE THREAD

**Issue by ask2018** [SubtitleEdit/subtitleedit#4812]
Hi, I've just update to version 3.6.0. I'm using Windows 7 with classic theme (themes service fully disabled) And there the space under "list view" is now white with white buttons. It is possible to fix this to match system theme as it was in previous version 3.5.18?
Screenshots in the attachment.

**Comment by ask2018** [comment]
3.5.18 https://i.postimg.cc/zDWdWYnM/3-5-18.png
3.6.0 https://i.postimg.cc/dVQnz7zP/3-6-0.png

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/108423915-c6901b00-7238-11eb-88a0-a56c966f4846.png)


![image](https://user-images.githubusercontent.com/1261331/108423950-ce4fbf80-7238-11eb-9570-86982c5ae5e5.png)

**Comment by OmrSi** [comment]
Okay, this is getting weird.
What system is this?

Info on why this is done here: https://github.com/SubtitleEdit/subtitleedit/commit/7b1c42a5283947ced0d7c9e6c01763d715f7ad72#r46757806

**Comment by ask2018** [comment]
System is Windows 7 SP1 x64 with all updates ESU included and Themes service fully stopped and disabled via services.msc.
A no it was always grey on my system and I'm using Subtitle Edit for years (not sure exactly since which version), but this is really first time its white and I must say it's pretty annoying to have this space white and also unpleasant for my eyes.

**Comment by OmrSi** [comment]
@ask2018 Yes, I think the Tab Control gives a gray color when theming is disabled and white when it's enabled. I didn't account for that when I set it to white after removing the Tab Control.

**Comment by OmrSi** [comment]
Is this better in any way? 
[SubtitleEditBeta.zip](https://github.com/SubtitleEdit/subtitleedit/files/6006293/SubtitleEditBeta.zip)

**Comment by ask2018** [comment]
Yes now it is as before grey again.
https://i.postimg.cc/g0wZLRwW/ok-now.png
Thank you for quick fix.

**Comment by OmrSi** [comment]
@ask2018 Great. You got it.

By the way, you can paste images directly to GitHub, not need to upload them on another website.

**Comment by ask2018** [comment]
Yes I know. But there was some issue with the paste to github in my browser (I guess some addon I'm using broken something), so it was faster for me upload elsewhere, than trying to fix it. Need to look at this later. But thanks for info.
