### ISSUE TITLE
Text box text always bold (3.6.0)

### ISSUE THREAD

**Issue by AbsenceJam** [SubtitleEdit/subtitleedit#4815]
3.5.18
![Screenshot 2021-02-19 at 09 47 28](https://user-images.githubusercontent.com/24455272/108488274-15b96880-7298-11eb-8434-862691741353.png)

3.6.0
![Screenshot 2021-02-19 at 09 48 12](https://user-images.githubusercontent.com/24455272/108488317-236eee00-7298-11eb-8066-4571f7e7399b.png)

3.6.0 (bold checked)
![Screenshot 2021-02-19 at 09 48 52](https://user-images.githubusercontent.com/24455272/108488330-28cc3880-7298-11eb-8596-9750ec9fe224.png)

Tested with all settings reset.

**Comment by niksedk** [comment]
Notice that SE has different settings for bold for list view and text box:
![image](https://user-images.githubusercontent.com/1261331/108565363-d83ef480-7304-11eb-846f-0a9ae0a3c8e5.png)

**Comment by AbsenceJam** [comment]
I have it unchecked in 3.5.18, install 3.6.0 it's checked, install 3.5.8 unchecked again. Has 3.6.0 renamed the preference and enabled it by default or something? Else, I wouldn't expect any change.

**Comment by OmrSi** [comment]
Yes, it was renamed.
