### ISSUE TITLE
[Request] Remove HI replaces NAME: with dash when there are multiple speakers

### ISSUE THREAD

**Issue by Stone-D** [SubtitleEdit/subtitleedit#4817]
Please add a checkbox to enable this.

    23
    00:02:10,630 --> 00:02:11,680
    MAN 1: You got it? Pressure!
    MAN 2: Yeah.

becomes

    23
    00:02:10,630 --> 00:02:11,680
    - You got it? Pressure!
    - Yeah.

Entries with a NAME: only on the second line should be left alone or flagged:

    23
    00:02:10,630 --> 00:02:11,680
    You got it? Pressure!
    FRED: Yeah.

Single line dialog entries should remain un-dashed.

I'm currently pre-processing each sub with Notepad++ to add dashes to every one using a regexp, which is fine, but I think SE should be able to handle this.

    (^[A-Z][A-Z \-\.0-9]+?:)
    - \1

**Comment by OmrSi** [comment]
I don't understand, your regex suggests that you are replacing `NAME:` with `- ` everywhere in the file, so why does it matter that SE is also adding `- `?

Or do you mean that you want
```
23
00:02:10,630 --> 00:02:11,680
You got it? Pressure!
FRED: Yeah.
```

To become:
```
23
00:02:10,630 --> 00:02:11,680
You got it? Pressure!
- Yeah.
```

**Comment by Stone-D** [comment]
Sorry that wasn't clear. Subtitle Edit can remove leading "- " from single lines, so I add it to every instance of "NAME: " via regex, whether they are single or double line.

After all is done, what I want is 

    23
    00:02:10,630 --> 00:02:11,680
    - You got it? Pressure!
    - Yeah.

However, care needs to be taken to accomodate Dutch (I think?) and other conventions where 

    23
    00:02:10,630 --> 00:02:11,680
    You got it? Pressure!
    - Yeah.

is standard.

**Comment by OmrSi** [comment]
There is something in the settings called "Dialog Style", you can set it to "Dash second line" and the dash will only be added to the second line.

**Comment by Stone-D** [comment]
Ah, yes that would take care of that. My core want though still remains:

    23
    00:02:10,630 --> 00:02:11,680
    MAN 1: You got it? Pressure!
    MAN 2: Yeah.

to

    23
    00:02:10,630 --> 00:02:11,680
    - You got it? Pressure!
    - Yeah.

instead of what SE currently does when it removes hearing impaired:

    23
    00:02:10,630 --> 00:02:11,680
    You got it? Pressure!
    Yeah.

**Comment by niksedk** [comment]
With default settings, I get this:
![image](https://user-images.githubusercontent.com/1261331/108592892-951a6b00-7370-11eb-9adc-661bd82c47d7.png)

If I change the dialog style (as OmrSi suggested) to "Dash second line with space", I get this:
![image](https://user-images.githubusercontent.com/1261331/108592915-b67b5700-7370-11eb-9611-5cb6001ee54f.png)

(tested with SE 3.6.0)

**Comment by Stone-D** [comment]
Ok that's really weird. It's working now. I must have changed a setting somewhere. Sorry everyone, I'm closing this issue.
