### ISSUE TITLE
An idea on new ASSA category feature

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4818]
Maybe it's nice to have an "As Default" button for users to pick which one would be autoloaded, so that they can more easily switch among projects without re-defining styles in the Default category time and time again for different projects, maybe like this:

![proto](https://user-images.githubusercontent.com/494788/108596748-fc144000-73c1-11eb-9d06-73c699ea988a.jpg)

**Comment by niksedk** [comment]
Ah yes, much better solution IMO :)

**Comment by OmrSi** [comment]
@niksedk Want me to work on this?

**Comment by niksedk** [comment]
> 
> @niksedk Want me to work on this? Button or checkbox?

I think a button is fine... there should be some indication in the list view (e.g. "*") and remove/delete should not be possible :)
Give it a go :)

**Comment by OmrSi** [comment]
Wouldn't disabling the "Set as default" button be enough? It would be disabled so the user would know he is in the default category.

**Comment by niksedk** [comment]
> 
> 
> Wouldn't disabling the "Set as default" button be enough? It would be disabled so the user would know he is in the default category.

Could be... I will test, perhaps others will too :)

**Comment by OmrSi** [comment]
@LeonCheung Do test it out :D
[SubtitleEditBeta.zip](https://github.com/SubtitleEdit/subtitleedit/files/6016388/SubtitleEditBeta.zip)
