### ISSUE TITLE
Italics - / to be replaced by <i> wrap

### ISSUE THREAD

**Issue by eagleeyetom** [SubtitleEdit/subtitleedit#4822]
Hello!

I would like to apologise if this has been discussed before, but it seems that I am unable to find it.

In the Polish language, many translators use / to highlight the line as italics. I wonder if there is a possibility of replacing it with `<i>something</i>` wrap.

Current usage:
`/W POPRZEDNICH ODCINKACH`

Expected usage:
`<i>W POPRZEDNICH ODCINKACH</i>`

I would love to see this while converting to SRT or as an automated option within this wonderful app (e.g. one click to replace all the lines starting with /).

**Comment by niksedk** [comment]
Perhaps something like this in Edit - "Multiple replace" (can also be used from "Batch convert"):

![image](https://user-images.githubusercontent.com/1261331/108609025-67aedb00-73cb-11eb-9565-a90d1b4dbcbb.png)

Regex 1 is `^/(.*\n.*)` and regex 2 is `^/(.*)`

**Comment by eagleeyetom** [comment]
Thank you, good sir! That works pretty well! Please consider adding it to one of the future releases :)

**Comment by niksedk** [comment]
I don't think it's going to get much easier... you can even setup a custom shortcut:
![image](https://user-images.githubusercontent.com/1261331/109390755-b56b9c00-7913-11eb-9f0f-96f73f00740f.png)
