### ISSUE TITLE
Source view

### ISSUE THREAD

**Issue by calimea** [SubtitleEdit/subtitleedit#4823]
I am using the new version 3.6.0 PL
I'm looking for an option to enable "Source View" but can't find it.
Is this option no longer available?
--------------------------------------
Korzystam z nowej wersji 3.6.0 PL
Szukam opcji włączenia "Widok źródła" ale nie mogę znaleźć. 
Czy ta opcja jest już niedostępna?

**Comment by OmrSi** [comment]
You can:
1. Right-click in the list view, you'll find an option called `Go to source view`.
2. Use the shortcut `F2`, which is customizable from the settings.

![image](https://user-images.githubusercontent.com/20923700/108611092-c3855e00-73e3-11eb-87b1-493f4a44b434.png)
