### ISSUE TITLE
Cannot Sub My Video..

### ISSUE THREAD

**Issue by indianlix** [SubtitleEdit/subtitleedit#4826]
I can subtitle my video. there is some problem with mpv video player it doesn't play or isn't downloaded...

**Comment by OmrSi** [comment]
Can provide more details? a picture maybe?

I think you're missing a codec so SE is asking you to use another player or download MPV.
So, simply, download MPV from the button :)

**Comment by indianlix** [comment]
![Untitled](https://user-images.githubusercontent.com/79354706/108634708-dad65100-74a0-11eb-8e8b-7fff7b77403f.png)

**Comment by OmrSi** [comment]
Seems to be an issue with the video's audio tracks.
Any chance you could attach the video or its link or send it to @niksedk email?

**Comment by niksedk** [comment]
@indianlix: Is latest beta any better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by indianlix** [comment]
![image](https://user-images.githubusercontent.com/79354706/108678869-b070ac00-7511-11eb-9ace-90ac1f5dbbe8.png)
Sir can you please elaborate I have been using sub edit for past year and this is first time I have faced a issue and my personal opinion no offense old grey logo was better.

**Comment by niksedk** [comment]
>
> Access to the path 'C:\Program Filse\Subtitle Edit\Beta\mpv-1.dll.new-mpv' is denied

The beta version is a portable version which should be installed to something like "C:\Tools\SE" and not under "C:\Program files\something"

**Comment by niksedk** [comment]
Also, how did you open the video file?

**Comment by indianlix** [comment]
> > Access to the path 'C:\Program Filse\Subtitle Edit\Beta\mpv-1.dll.new-mpv' is denied
> 
> The beta version is a portable version which should be installed to something like "C:\Tools\SE" and not under "C:\Program files\something"

Sir I know that and is there any more complex way to open a video file.
Video [Tab] >> Open Video File

**Comment by OmrSi** [comment]
@indianlix Any chance you could attach the video file or send its link? If it's not private.
Or maybe send it to `nikse.dk@gmail.com` if it is private?

**Comment by indianlix** [comment]
ok

**Comment by indianlix** [comment]
sir i can't give a video if you want anything else i can give that and anyway if found another app easier and better thank you.
