### ISSUE TITLE
ASSA: Style colors cannot be saved.

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4830]
It occurs in the very latest beta 52.

**Comment by niksedk** [comment]
OK, I saw that yesterday and tried to fix it - worked for me, but perhaps there's still an issue?
How can I re-create this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Maybe. Tried this one, it still occurs:

1. unzip then open.
2. switch to .ASS format.
3. go to manager, try changing the colors in default in-file style, click OK.
4. re-enter the manager, colors are initialized.

However, for Storage styles, they are fine.
