### ISSUE TITLE
Lower audio part now following

### ISSUE THREAD

**Issue by LaMpiR** [SubtitleEdit/subtitleedit#4839]
I wanted to the subtitles and the lower part is not following, so it is very hard to determine when to add the subtitles without manually having to click around.
I have selected the option "Select current subtitles while playing", but still it skips them.

**Comment by OmrSi** [comment]
What you're saying is not very clear. What is "lower part"?
Do explain more and attach Images.

"Select current subtitles while playing" only selects the existing lines while the video is playing.

**Comment by LaMpiR** [comment]
https://ibb.co/9rjjRrV

This part. The blue line showing the exact time is moving with delay and not in real time, so it keeps skipping the time. Every few seconds.

**Comment by OmrSi** [comment]
Are you using VLC as your video player?

**Comment by LaMpiR** [comment]
> Are you using VLC as your video player?

Yes.

**Comment by OmrSi** [comment]
Yes, the cursor in VLC does that.
You should change your video player to MPV or DirectShow.
MPV being better for SE but DirectShow being smoother.
You would probably need LAVFilters with DirectShow.

You can change the video player from the settings -> video player page.

**Comment by LaMpiR** [comment]
> Yes, the cursor in VLC does that.
> You should change your video player to MPV or DirectShow.
> MPV being better for SE but DirectShow being smoother.
> You would probably need LAVFilters with DirectShow.
> 
> You can change the video player from the settings -> video player page.

Thank you. Its working properly with codecs now.

**Comment by niksedk** [comment]
Cool, VLC 4.0 should not have this issue, if/when it's released... 
https://www.theverge.com/2021/2/12/22279750/vlc-4-0-new-user-interface-videolan-media-player-video-music-movie-database-web-player
