### ISSUE TITLE
Question about syncing

### ISSUE THREAD

**Issue by evayor** [SubtitleEdit/subtitleedit#4841]
I have an English srt which I downloaded from the net and I'm using as a template. It's out of  sync with the video. However when I'm trying to adjust the time moving all lines backward using the Adjust all times option, they move but with every nest sub the lagging continues and I need to do it every several minutes.

Any idea if this is fixable somehow or where the issue comes from?

**Comment by OmrSi** [comment]
It's usually a frame rate issue.
Not necessarily, but most of the time when it happens, it's a frame rate issue.
Make sure the subtitle is made for a video with the same frame rate as your version of the video, and change your subtitle to match the original video's frame rate if not.

**Comment by evayor** [comment]
I thought that too and tried with all possible frame rates available. However, it won't match the waveform/timing of the video.
Besides, when downloading subs from the web, is there a way to check for which framerate they have been done?

**Comment by OmrSi** [comment]
You can check the name of the provided version and search for it and check its media info.

So far, I haven't found a way other than manual editing if this issue couldn't be solved by changing the frame rate.
I just always assume there are extra or missing scenes.
Or sometimes, if the movie/episode is old, the frames are just not right.

I tried once downloading a WEB and HDTV version of the same episode of an old tv show and put them side by side on Camtasia and noticed that after a while the HDTV version gets a bit of a delay for no reason, even thought they have the same framerate.

**Comment by evayor** [comment]
This has been really helpful. Thank you very much!
