### ISSUE TITLE
Translate Error

### ISSUE THREAD

**Issue by howblast** [SubtitleEdit/subtitleedit#4842]

**Comment by howblast** [comment]
![Uploading Sin título.png…]()

**Comment by howblast** [comment]
![Sin título](https://user-images.githubusercontent.com/41839586/108922927-81376900-75fd-11eb-9aca-b7d73cab8506.png)

**Comment by howblast** [comment]
this error launch 
i translate 346 line the translate stop in 318

**Comment by niksedk** [comment]
Could you attach the subtitle as a .zip file - or email it to me?

**Comment by howblast** [comment]
[[Erai-raws] Soukou Musume Senki - 07 [720p].zip](https://github.com/SubtitleEdit/subtitleedit/files/6039303/Erai-raws.Soukou.Musume.Senki.-.07.720p.zip)

**Comment by OmrSi** [comment]
Seems like these two empty lines at the end are causing this when using "No merging".

**Comment by howblast** [comment]
thanks for the solution

**Comment by OmrSi** [comment]
You got, but I think this should still be opened. 
It is still a bug that needs fixing.
