### ISSUE TITLE
Timestamp in "Start time" is white, same as background

### ISSUE THREAD

**Issue by dausruddin** [SubtitleEdit/subtitleedit#4844]
System: Ubuntu 20.04
SE version: 3.6.0

I can't see timestamp in the "Start time" input box.
![Screenshot from 2021-02-24 09-22-59](https://user-images.githubusercontent.com/5763466/108931513-bfc33700-7682-11eb-8198-7e3b7323c7e4.png)
unless if I'm highlighting it
![Screenshot from 2021-02-24 09-29-31](https://user-images.githubusercontent.com/5763466/108931572-d23d7080-7682-11eb-975b-154f26734281.png)

Anyway, does SE should be dark by default? Is this the default theme?
![Screenshot from 2021-02-24 09-28-09](https://user-images.githubusercontent.com/5763466/108931522-c18cfa80-7682-11eb-94a1-7d1b899115e8.png)

Thanks

**Comment by dausruddin** [comment]
Also this one I have been experiencing since forever on multiple devices and systems.
The navigation button went invisible. I had to guess which button is at which position whenever I need them.

![Screenshot from 2021-02-27 16-39-01](https://user-images.githubusercontent.com/5763466/109382276-8278d680-791a-11eb-9ca8-dbb50332afd4.png)

**Comment by Kenifornication** [comment]
Try to enable or disable Dark Theme in `Setttings > Font > Use Dark Theme` and see if it helps you.

**Comment by dausruddin** [comment]
That fixed the timestamp text/ But another issue occurs.
https://user-images.githubusercontent.com/5763466/109438359-9f212580-7a64-11eb-8334-767ec8795252.mp4

**Comment by dausruddin** [comment]
I tried on Arch with Plasma desktop and SubtitleEdit looks fine. I'll close this issue if somehow I fully migrated to Arch.

**Comment by dausruddin** [comment]
Moved to Arch a while ago. Closing.
