### ISSUE TITLE
<Alt + up/down> Switch the upper and lower lines, the cursor display position and operation should be improved

### ISSUE THREAD

**Issue by alvvaysu** [SubtitleEdit/subtitleedit#4845]
In version 3.5.18, when you switch to the current text edit box, you can press left or right to locate the beginning or end of the sentence, which I think is very smooth.
In version 3.6.0, when switching lines to the current text edit box, you need to press up or down, and for double lines, the up key cannot be positioned at the beginning of the sentence, which feels not very smooth.

I often extract hard subtitles of Chinese videos, use "Videosubfinder5.50" and Baidu OCR-based scripts to generate high-precision .srt files. Then hand it over to Subtitle edit for proofreading. I think the subtitle preview of SE's video player can provide a cursor function, which will definitely greatly improve the proofreading efficiency.

**Comment by OmrSi** [comment]
Do you mean that when you go to the next or previous line, the whole text is highlighted and when you click left nothing happens? 

The issue it's very clear.

**Comment by alvvaysu** [comment]
> 您的意思是当您转到下一行或上一行时，整个文本将突出显示，而当您单击鼠标左键时，什么也没发生？
> 
> 这个问题很明显。

Emm… My English is not good, use Google Translate.
I mean: After switching lines, when the entire text in the edit box is selected, press the ← key to place the cursor on the head, instead of pressing the ↑ key to place the head, and now double-line text pressing the ↑ key will not place the cursor on the head On the head

**Comment by LeonCheung** [comment]
Tested in the latest 3.6.0, it is exactly as what you expected. You can also try Home and End in this case.

**Comment by LeonCheung** [comment]
要不你用中文描述一下吧，看看能不能帮你，有助于快速解决问题。

**Comment by OmrSi** [comment]
@LeonCheung There was an issue with 3.6.0 where if you move to the next line and it's highlighted and you click the arrow left, it doesn't do anything.

It was later fixed. I don't know if this is what he means.
Note that the issue only happened when TextBox's syntax highlighting was enabled.

**Comment by alvvaysu** [comment]
> @LeonCheung 3.6.0中存在一个问题，如果您移至下一行并突出显示，然后单击向左箭头，则它无任何作用。
> 
> 后来修复了。我不知道这是他的意思。
> 请注意，仅当启用TextBox的语法突出显示时，才会发生此问题。

oh i see，thank you! really easy

**Comment by LeonCheung** [comment]
Maybe try the latest beta to see if it helps: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by alvvaysu** [comment]
> 要不你用中文描述一下吧，看看能不能帮你，有助于快速解决问题。

帖子主楼的第一

> Maybe try the latest beta to see if it helps: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

谢谢大哥，帖子主楼的第一个疑惑已经解决了。

还有一个提议是，我经常用Videosubfinder提取硬字幕视频，通过OCR生成.srt，然后用SE打开硬字幕视频进行校对。
校对时，想在视频播放器的字幕预览处，增加一个光标功能，这样我就不用看着左边的文本编辑框，直接看右边，能更加直观的校对我所提取的srt了

**Comment by LeonCheung** [comment]
但是你最终还是要在文本框里编辑文本的呀，你是说，希望把文本框放在播放器下面就更直观了对吗？如果是这样，目前看不太现实。那样就是两个文本框了，功能重复了。基于你的需求，我能想到的就是 文件>视频>取消停靠视频控件，然后把播放器放在文本框上面，调节列表的宽度，以免被它遮挡。也算是曲线救国了吧，如图：

![unlock](https://user-images.githubusercontent.com/494788/109157819-84715700-77ad-11eb-8902-0ff109c8ef8a.jpg)

**Comment by LeonCheung** [comment]
Just curious, do you think a new layout option could be a workaround in your case? 
![new_layout](https://user-images.githubusercontent.com/494788/109160168-6a854380-77b0-11eb-9ef7-717bcb9326c0.jpg)

**Comment by alvvaysu** [comment]
> Just curious, do you think a new layout option could be a workaround in your case?
> ![new_layout](https://user-images.githubusercontent.com/494788/109160168-6a854380-77b0-11eb-9ef7-717bcb9326c0.jpg)

不错啊，这个和我的预期差不多了，其实我校对的字幕都属于和简单的srt，没任何特效代码，所以我想适当变换下观察的位置。
有跟此图接近的效果 我已经很满意了
https://s3.ax1x.com/2021/02/25/yvL2eP.jpg

**Comment by LeonCheung** [comment]
I do know what you mean. Maybe there are others like you who prefer a more intuitive way to edit texts. We'll see. Good luck. :)
Translation: 我知道你的意思。也许还会有其他像你一样的人，喜欢用更直观的方式编辑文本。看开发者的意见吧，祝你好运。:)
