### ISSUE TITLE
Visual Sync with MPC-HC as videoplayer doesn't set the sub positions on opening

### ISSUE THREAD

**Issue by SuperDre** [SubtitleEdit/subtitleedit#4852]
When you have MPC-HC set as videoplayer, if you open the Visual Sync, it doesn't have the sub positions set.
Steps to reproduce:
-Open Visual Sync
-Left videoplayer is not set to the position of the first subtitle
-Right videoplayer is not set to the position of the last subtitle

Windows 10 (fullly updated), subedit 3.5.18

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
