### ISSUE TITLE
[Feature request] Add "Export bookmars" option, or make changes in the code so that *.bookmarks files could be read separately

### ISSUE THREAD

**Issue by kjaerlige** [SubtitleEdit/subtitleedit#4854]
Subject.

What I have in mind: it would be great to be able to turn bookmarks into a readable sheet with time codes and maybe even the content of the line included.

Why: It's a great asset for teamwork, to be able to pass your notes to the next guy (like editor? for example) and be able to do it smoothly and possibly without the need for anyone to open the source/use SE at all.

With Export Bookmarks feature implemented, it would be nice to have options of what to export - time code, maybe content - original, translation, or both, actor - for SubStation Alpha; maybe something else. Output format could be text (with line breaks after each bookmark), csv or xsl

If it is too much, and if it's possible to just change the way bookmarks are saved, would be great to have them being recorded with time codes, something like this:
`{"idx":48,"starttime":00:00:05,123,"txt":"this is a sample"},`
... this would already be something to work with.

But the idea is to be able to create something like a script sheet, but with bookmarks+notes with line timing and maybe with the content of lines themselves.
Thank you

**Comment by OmrSi** [comment]
You can simply:
1. Bookmark your lines.
2. Go to Edit -> Modify selection.
3. Copy the selected lines.
4. Do whatever you want with them.

Modify selection for bookmarked lines were added after the official 3.6.0, in the beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by kjaerlige** [comment]
Thanks for that, I'm on stable version. But - I can use Modify selection, yes, but only to work with lines, and what I need is the ability to save the notes I made.
I can't export these notes, only subtitle lines. if I press Copy on selection it'll give me raw text with tags and params but not bookmark notes, if I press Save these lines as... it will not give me the option to save bookmarks with notes. I don't know how to make this work, at least - how to make this work easily.

**Comment by niksedk** [comment]
Added export in the bookmark context menu:
![image](https://user-images.githubusercontent.com/1261331/109419717-20c67400-79cf-11eb-9c58-ecc7656dbef0.png)

Portable beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
