### ISSUE TITLE
[Bug] Screen-scraping auto-translate doesn't work

### ISSUE THREAD

**Issue by Kenifornication** [SubtitleEdit/subtitleedit#4855]
When attempting to auto-translate with DeepL or Google (Screen-scraping), the following error pops up:

![Screenshot 2021-02-27 202908](https://user-images.githubusercontent.com/12016198/109398166-528dfb00-793b-11eb-909c-180f861c46ad.png)

Translating with Bing or Google V1 works normally.

**Comment by niksedk** [comment]
The Google translate screen-scraper plugin uses the WebView control: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/webview
It requires Win10...

You can try the "translate via copy paste".

**Comment by Kenifornication** [comment]
> It requires Win10...

I am on Windows 10!

**Comment by lucasg87** [comment]
Hi man. Follow The steps of this vídeo and see if will help.

https://youtu.be/fkF52P-ucFQ
