### ISSUE TITLE
Google Translate Window Shortcut is Not Working

### ISSUE THREAD

**Issue by xmrea** [SubtitleEdit/subtitleedit#4859]
Google Translate Window Shortcut is Not Working.

![Screenshot_2](https://user-images.githubusercontent.com/46967762/109687192-0f7a9480-7b94-11eb-878b-cf5822eae04c.png)

Even though I press Ctrl + Shift + G, there is no reaction.

**Comment by niksedk** [comment]
Thx for the info - beta updated :)

![image](https://user-images.githubusercontent.com/1261331/109703074-574deb80-7b95-11eb-8c1a-ecf2dbcea793.png)

Should perhaps be `Ctrl+Shift+T` ?

**Comment by niksedk** [comment]
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
