### ISSUE TITLE
Color value cannot be pasted in ASSA manager

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4875]
The color here can be copied, but cannot be pasted to another color panel:

![new1](https://user-images.githubusercontent.com/494788/110424824-5f021880-80de-11eb-9863-f37d8291e80b.jpg)

**Comment by LeonCheung** [comment]
Or, is there a convenient way to copy colors? Currently, it seems we cannot do that...

**Comment by niksedk** [comment]
Is paste working in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
Very cool, thanks!
