### ISSUE TITLE
Modified Selection tool: support needed for ASSA break (\N)

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4876]
It seems the "More than two lines" rule doesn't take `\N `break into account when working with ASSA file.
Also, Could we have a "More than one line" rule here? It would be really handy in some cases too. Many thanks!  :D

**Comment by LeonCheung** [comment]
Sure that Regex can do that. For example:
For the first one: `\\N.*\\N|\r\n.*\r\n`
For the second one: `\\N|\r\n`

Free to close it if nothing worth considering here.

**Comment by OmrSi** [comment]
@LeonCheung You can actually do `(?:(?:\r?\n|\\N).*){2,}` to include all cases in one regex.

**Comment by LeonCheung** [comment]
Thanks for the tip. :) Closing.
