### ISSUE TITLE
PGS subs vertical alignment

### ISSUE THREAD

**Issue by akaicat** [SubtitleEdit/subtitleedit#4881]
When loading a .sup for edit, there are some issues with the auto align of some lines.
I'll post some comparisons with BDSup2Sub++, wich have the right alignment.

This top line is correct, and it have the same positions in BDSup2Sub++
![Screenshot_1](https://user-images.githubusercontent.com/25311863/110540912-5c77e100-8127-11eb-9559-07262bff8c90.png)

This sign is 200 pixel below
![Screenshot_2](https://user-images.githubusercontent.com/25311863/110541370-ef188000-8127-11eb-8730-4568cbe9b0e0.png)

This fullscreen picture is 810 pixel below, and the bottom line is out of the screen. Most of the problems are from these full screen pictures.
![Screenshot_3](https://user-images.githubusercontent.com/25311863/110541626-4caccc80-8128-11eb-9a59-e7af2d7f67fe.png)

These are the subs
[Kimi no Na wa. (Sub Ita - Ita)_Track04._PGS.zip](https://github.com/SubtitleEdit/subtitleedit/files/6111597/Kimi.no.Na.wa.Sub.Ita.-.Ita._Track04._PGS.zip)

Sorry for my english btw

**Comment by niksedk** [comment]
Thx for the info :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
@akaicat: You're welcome - easy to fix with a nicely written issue with images + sample file :)
