### ISSUE TITLE
Playback speed 300% don`t work :(

### ISSUE THREAD

**Issue by PaulMoscow** [SubtitleEdit/subtitleedit#4887]
Hey! Tell me why some playback speeds don't work.
For example, I really need a playback speed of 300%, but the maximum that works is 190-200%.
Maybe need to enable some setting in the program or in Windows?

Many thanks for the help!
Especially for Omar Si! :)

**Comment by OmrSi** [comment]
Hey @PaulMoscow 
What video player are you using?

**Comment by niksedk** [comment]
And what version of SE are you using - see https://github.com/SubtitleEdit/subtitleedit/issues/4777

**Comment by PaulMoscow** [comment]
> Hey @PaulMoscow
> What video player are you using?
![изображение](https://user-images.githubusercontent.com/74332592/111045145-77b35b00-845d-11eb-8779-bd7bb8fe3a63.png)
**Looks like Windows Media Player**


> And what version of SE are you using - see #4777
**3.6.0**

**Comment by OmrSi** [comment]
@PaulMoscow Here you go [SubtitleEditBeta.zip](https://github.com/SubtitleEdit/subtitleedit/files/6136608/SubtitleEditBeta.zip)
