### ISSUE TITLE
Langauges other than English appear as squares

### ISSUE THREAD

**Issue by sprajagopal** [SubtitleEdit/subtitleedit#4889]
Ubuntu 20.04, SE 3.6.0, 3.5.18
Are languages other than English supported? When I copy paste only squares appear.
![image](https://user-images.githubusercontent.com/6297136/111061657-82f0a000-84ca-11eb-82ca-0420eeff33bc.png)

I have selected UTF-7 as the encoding (tried UTF8 with BOM and without BOM also, no difference)
![image](https://user-images.githubusercontent.com/6297136/111061691-a7e51300-84ca-11eb-812a-a540cfc6a1f3.png)

**Comment by OmrSi** [comment]
Maybe you can try changing the font?

**Comment by AnterCreeper** [comment]
In my test, only some specific font is OK.

**Comment by niksedk** [comment]
Yes, I guess you will have to find a font matching your need.

Later Windows versions have extremely nice Unicode support... I wish it worked like that on Linux too, so all fonts had both Nordic, Spanish, Arabic, Japanese, Chinese (etc) letters.
