### ISSUE TITLE
[Feature Request] An option to fluff subtitles duration?

### ISSUE THREAD

**Issue by ninep9up** [SubtitleEdit/subtitleedit#4892]
Kind of bridge gaps but more single-stepped. For example, if you're just using bridges it takes one step to near inside-of-zone lines, but also a second to apply that for out-of-zone lines with upbringing a gap duration. While with a fluff option you just add additional timings to the possible limit of them overlapping.

**Comment by OmrSi** [comment]
You mean like `Tools -> Adjust durations`?

**Comment by ninep9up** [comment]
> 
> 
> You mean like `Tools -> Adjust durations`?
I mean, if you apply a fluff-step of 0.5 to 00:03:00-00:07:00, you get 00:02:50-00:07:50 in timings

**Comment by OmrSi** [comment]
You subtract from the start and add to the end?

**Comment by ninep9up** [comment]
> 
> 
> You subtract from the start and add to the end?

Kind of, if we're talking our pov for gap-lessening and subtitle duration-additioning, for subtitles in overall it's just fluffing

**Comment by ninep9up** [comment]
> 
> 
> > You mean like `Tools -> Adjust durations`?
> 
> I mean, if you apply a fluff-step of 0.5 to 00:03:00-00:07:00, you get 00:02:50-00:07:50 in timings
> But if there's 00:07:20 afterwards, you just prolong that up to it

On second thought, borderline fluffing should be more like equalizing, so it's -00:07:10/00:07:10-
It's just that kind of subs often bear weak timings in both where they start

**Comment by ninep9up** [comment]
actually, i was going through my mail to reminisce this thread out and this is kinda a crucial feature for language learners who subclick-copy from potplayer to search dictionaries. chinese is kinda too fast of the language, so it takes an additional half second to click on a sub that's already not there

**Comment by ninep9up** [comment]
heed my voice, i reopen it

**Comment by ninep9up** [comment]
i mean that's on the guy, some archivist will go thru this and think, that's some strange punctuality

**Comment by ninep9up** [comment]
anyway, if you have time try to click on chinese subtitles in potplayer when watching see you tomorrow. it's a chinese flick written by wong kar-wai, i wonder if you catch it

**Comment by ninep9up** [comment]
i mean, option of taking gap by previous sub could work, idk if i'm buying time for these learners who like to see subtitles before they appear, is this even a thing or is it but a heresy

**Comment by ninep9up** [comment]
like, when you divide gapping between tests you acknowledge this phenomenon, but you don't do that if this applies to a first of bunch? is this controversial?

**Comment by ninep9up** [comment]
it is, a bit, so i wonder if i just missed it or you haven't added it and made feature request completed equalized to wontfix like some perverse hyperweirdo

**Comment by ninep9up** [comment]
that's all i wanted to say

**Comment by ninep9up** [comment]
but then i thought and i want to add
that you discredit the notion that would appear as _learner-enhanced subtitles_
come on, just add this one array cycle string, that's not even funny, what's your beef

i mean, i did some programming in the school

**Comment by ninep9up** [comment]
you had like 3 minutes to tag wontfix to this and had no three minutes to write this string?
you're like from amsterdam or what
yeah i mean i'm sweating with wrath

**Comment by ninep9up** [comment]
let's go together 
for i++ while subline_end[i-1]!=subline_start[i] begin
subline_start[i]+=-1ms
subline_end[i]=+1ms
end

this was nightmare
man how did we make it
do they still pay us $3k a month
haha hecking idiots

**Comment by ninep9up** [comment]
don't choke on your ramen

**Comment by ninep9up** [comment]
man you like really crushed me, i'm not gonna lie that's not all of it, you still need to add additional components here and there
but like really
what made you so stiff
i hate to think it was your own stiffness
but like they pay you not to be washed away by resentment
if you have family that hates you, you can like be creative for a change not lacking in your character that your family loves
if you're single you can like use that money
and if you don't have any you can like give up this stuff and become an artist

**Comment by ninep9up** [comment]
or whatever, i hate that it came to this
every time i was syncing i was so lost with your program
dsrt made it like so many time easier
is i were you i'd leave just three options to be honest
move left move right 
fluf
sync subpoint to the video

it's 2024 and we have a dj panel for subtitles
hahaha this is nightmare
do what you will
i mean, someday i will press this netflix quality check button to see what it does

**Comment by ninep9up** [comment]
also, language-assisting should be the thing
i mean, potplayer is the solution to some extent,
but it's easier to do parallels in programs and stuff

like, maybe i'm living in the future
but i'm living in it for the last 10 years, and people seem not to take any preference to do this stuff

we're like ultranationwide earthrace mimicking to some older generations but like our thinking is not that stiff
so i'm like very sad

doing a hardsub is a nightmare
doing a cut is a nightmare
and thinking about even touching tv-gotten subs is a nightmare

and we're like most certainly have the tools so i'm like ultrasad people would have to spend more time on this and it will make them neurotic for no good reason

**Comment by ninep9up** [comment]
like, let's get real
you need analyzing audiographs and nothing more in case of going cuts
you need to do stellar ocr in case of hardsubbing
and you need cross-audio sub-sync analysis in case of tv-gotten subs

and this is all

**Comment by ninep9up** [comment]
i mean, it's up to you, if you wanna sync your program to times, but like i'd really do like reimagining if i were you
