### ISSUE TITLE
Timing options with video position

### ISSUE THREAD

**Issue by QuentinNetherwood** [SubtitleEdit/subtitleedit#4898]
Hi, could you please include these features into the drop-down menu and/or right-click menu with hotkeys too?

1. A quick option to shift the selected line to the position where the video is paused and **all the selected lines** with the same time.
2. A quick option to shift the selected line to the position where the video is paused and **all lines of the subtitle** with the same time.

Thank you very much.

**Comment by OmrSi** [comment]
What do you mean `With the same time`?
Do you mean at the same time or the lines that have the same time?

**Comment by QuentinNetherwood** [comment]
I mean the difference between the in cue of the selected line and the video position. Exactly like "set start and offset the rest" does now.

**Comment by OmrSi** [comment]
For 1, you can select the lines then use `set start and offset the rest`, it will only offset the selected lines.
For 2, you can use `Synchronization -> Adjust all times`, or you can use `set start and offset the rest` on the first line of the subtitle.

**Comment by QuentinNetherwood** [comment]
For 1: Great, thank you, I didn't think this works with only the selected lines too.
For 2:
- With "adjust all times" I need to give the time of the adjusting manually.
- With "set start and offset" I need the search the position of the first line.

That's exactly I would like to avoid. So if I find the exact position of any line of the subtitle with that I could resync every line instantly. This would be very helpful when the subtitle starts with a lot of forced narrative lines without speech. I could search the position on the waveform for the first line when there is actual speech and I could move the lines before the speech too in one step.

I use this with a custom script in an other subtitling program for years and I really got used to it. I would like to change to Subtitle Edit but I would really miss this option.

**Comment by niksedk** [comment]
Good stuff :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
