### ISSUE TITLE
Colour of selected line without focus

### ISSUE THREAD

**Issue by QuentinNetherwood** [SubtitleEdit/subtitleedit#4899]
When the selected line loses focus the colour of the line changes. In previous versions this was another shade of blue which is okay, but in the new version it changes to a darker colour with black letters and the I can't read the text of the line.

I couldn't find any option to change this colour or at least to switch off this change.

Could you please make this colour changeable in the settings?

Thank you.

**Comment by OmrSi** [comment]
It changes to a darker color when you switch to the Dark theme.
It changes back to the blue color if you disable the Dark theme.

There is an option to change it in the settings file called `ListViewUnfocusedSelectedColor`
If you want the default blue color, you can set it to `-5383962`

**Comment by QuentinNetherwood** [comment]
I tried the Dark theme but I changed back to Default. I see. Maybe after that this background colour didn't changed back. Because now I use the defaul theme but the colour of the line is dark. Thank you for your help I will change it in the settings file.
