### ISSUE TITLE
doubled shortcut?

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4902]
Set start and offset the rest?

![Clipboard01](https://user-images.githubusercontent.com/46628545/111632152-7df65e00-87f4-11eb-9e9d-4433827d50be.jpg)

**Comment by m0ck69** [comment]
whats the difference?

**Comment by OmrSi** [comment]
Nothing.
The default shortcut for it was `F9` and the user had the option to use another shortcut with `F9`, then the default was removed so some users, including me, wanted the option to have multiple shortcuts for it.
