### ISSUE TITLE
ASSA: One-click setup for Resolution

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4903]
We know that this is a format highly based on resolution. Instead of setting it manually every time, or looking up a video file (**mostly it would be the loaded one**), it would be nice to have a button to pick resolution from the loaded video. :) 
 Maybe like this:

![request](https://user-images.githubusercontent.com/494788/111640411-23322600-8837-11eb-84dc-e9ad6047b9c2.jpg)

**Comment by OmrSi** [comment]
@niksedk Can I do this?
