### ISSUE TITLE
Focus swapping randomly

### ISSUE THREAD

**Issue by farmaister** [SubtitleEdit/subtitleedit#4904]
Hi,
I'm working in SE a lot, but lately (i think, it's from last update), selection focus started randomly swapping from text field (where i edit subtitles) to title bar (or toolbar - where you have file - tools - video etc.).
When i translate subtitles, I use shortcut to pause and play video, and I use shift+enter to go to the next row, so i can use only keyboard, but sometimes, like 1 in 30 rows, it just swaps to that title bar and I have to use mouse and click back to the text field.

Is there any way to fix this? I tried finding a shortcut, which would swap to the text field, but it seems like there is none.

I hope you can understand what i mean and thank you in advance for any tips.

**Comment by OmrSi** [comment]
This should be happening only when you press `Alt` when you're in the text box.

SE used to ignore Alt presses when in the textbox, but that caused some issues for the RichTextBox (the text box with colors) so it had to be removed.

This is the default behavior everywhere for the system, if you press Alt, the focus will shift to the menu bar.

**Comment by farmaister** [comment]
Thank you very much! I am actually using one more shortcut to navigate through video, which is alt+arrows and it probably sometimes register only alt key. And i can press alt again to get back to the text bar.

Thanks again, you solved it so fast!

**Comment by OmrSi** [comment]
Yep, it might be because you press Alt for the shortcut then decide not to continue, so the Alt is left pressed alone.

You got it!
