### ISSUE TITLE
Toggle focus between subtitle text box and waveform

### ISSUE THREAD

**Issue by QuentinNetherwood** [SubtitleEdit/subtitleedit#4908]
Hi, there are some hotkeys to toggle focus, but it would be great to have a hotkey to toggle focus between subtitle text box and waveform.

When during resyncing I find something I need to edit in the text this would be very useful.

**Comment by OmrSi** [comment]
You can use `Toggle foccus between list view and text box` twice to get to the text box when the waveform is focused.

**Comment by QuentinNetherwood** [comment]
I see. One step would be better, but this works too. Thank you.
