### ISSUE TITLE
Setting start times and end times when the video position is in a gap between lines.

### ISSUE THREAD

**Issue by QuentinNetherwood** [SubtitleEdit/subtitleedit#4909]
Hi, I work a lot with a subtitling tool of one of my clients where setting start times and end times works a different way.

In Subtitle Edit, "set start time" and "set end time" hotkeys always change the selected line.

In that subtitling tool if the video position is in a gap between lines "set start time" always changes the start time of the next line and "set and time" always changes the end time of the previous line. If the video position is not in a gap it changes the selected line like Subtitle Edit.

I know I can use "go to next line" and "go to previous line" when resyncing, that's what I do now. But if you could include hotkeys for this "smart set", resyncing would be way more simple and a lot quicker.

**Comment by PreetM07** [comment]
I don't get exactly the use case here.

But for spotting you can use combination of "ctrl + click" and "alt + click" to modify start and end time on the waveform dock.
Zooming in and out and playing and even anticipating the exact position via waveforms are more quicker and faster.

However this also works for the selected line, but it definitely is way faster.

**Comment by QuentinNetherwood** [comment]
> I don't get exactly the use case here.
> 
> But for spotting you can use combination of "ctrl + click" and "alt + click" to modify start and end time on the waveform dock.
> Zooming in and out and playing and even anticipating the exact position via waveforms are more quicker and faster.
> 
> However this also works for the selected line, but it definitely is way faster.

I know there are always other ways to do something but I use this method for years in a client-given tool and I really love it. I can fix the start time and end times in a subtitle completely using only a few shortcuts without mouse. This is really fast for me. I use only the shortcuts for one frame back/forward, half second and one second back/forward, play/pause and set start time/set end time. I can jump through the subtitle and fix every start time and end time very quickly.
