### ISSUE TITLE
Erro "Windows Forms Thread Exception"

### ISSUE THREAD

**Issue by luannbr** [SubtitleEdit/subtitleedit#4916]
When using machine translation, when near the end this error occurs.
In version SE3518 this does not happen

[Print](https://cdn.discordapp.com/attachments/816861147780087858/823070074604486656/Screenshot_151.png)

Line 135
```
Dialogue: 0,0:09:43.11,0:09:44.74,Default,,0,0,0,,﻿It was that Ye Bu Gu
```

**Comment by OmrSi** [comment]
Are there empty lines in the file? 
If so, the issue should be fixed in the latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by luannbr** [comment]
> Are there empty lines in the file?
> If so, the issue should be fixed in the latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

Sorry, I forgot to warn you that I'm using this version that you sent, the error is occurring

**Comment by OmrSi** [comment]
Can you attach the subtitle file or send it to `nikse.dk@gmail.com`?

**Comment by luannbr** [comment]
> Can you attach the subtitle file or send it to `nikse.dk@gmail.com`?

[Sub](https://cdn.discordapp.com/attachments/816861147780087858/823250706084397106/Douluo_Dalu_ep_148.ass)

**Comment by niksedk** [comment]
Thx for the file - Works fine with latest beta :)
