### ISSUE TITLE
NUL character in imported .ASS files

### ISSUE THREAD

**Issue by pandalamp** [SubtitleEdit/subtitleedit#4925]
When importing an MKV file containing an .ASS subtitle file, a NUL character (ASCII code 0) gets added between the [V4+ Styles] and [Events] section.

The presence of this character means that switching to Source/List view (F2) will omit anything past it (the actual subtitle content) and show an unrecoverable error when trying to switch back: "Unable to parse source view text"

Inspecting the .ASS file in Notepad++ reveals the problematic character:

...
[V4+ Styles]
Format: ...
Style: ....
{NUL}

[Events]
...

I've uploaded an example here but am unsure if the bad character will make it through:
[example.txt](https://github.com/SubtitleEdit/subtitleedit/files/6197559/example.txt)

Opening that example in Subtitle Edit and pressing F2 twice should reveal the error mentioned above.

Worth noting is that extracting an .ASS file manually with MKV Extract does not include the offending character, implying it is introduced when Subtitle Edit imports the file. After manually removing the character outside of Subtitle Edit, the file can be interacted with normally within the application.

**Comment by niksedk** [comment]
Thx for the info - could you possibly share a .mks file (zip and attach) or perhaps the original mks file (email is fine)?
I was unable to re-produce this error with any files I have.

**Comment by pandalamp** [comment]
> Thx for the info - could you possibly share a .mks file (zip and attach) or perhaps the original mks file (email is fine)?
> I was unable to re-produce this error with any files I have.

Thank you for your reply and attention. Attached is an MKS file that exhibits the issue I described:
[nul_test.zip](https://github.com/SubtitleEdit/subtitleedit/files/6222348/nul_test.zip)

Possibly worth noting is that I have been unable to manually create an MKS to reproduce the issue with the tools I have, although it does seem to recur naturally with any MKV files I work with from Handbrake that have text-based (.ASS) closed caption tracks. That is to say, manually MKVextract-ing the .ASS file from the test MKS provided here will not present this issue, but rather importing the MKS file directly to Subtitle Edit will.

**Comment by niksedk** [comment]
Thx for the file :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
