### ISSUE TITLE
[ASSA] Failed to display Style column in certain case

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4929]
How to reproduce:

1. Open SE.
2. Open a file.
3. Then try loading another. Now the Style column disappeared and no way to unhide it.

**Comment by OmrSi** [comment]
@niksedk The Style column is usually shown when `SetCurrentFormat` changes the index of the `comboBoxSubtitleFormats`, therefore firing the code in `ComboBoxSubtitleFormatsSelectedIndexChanged`, but when the formats are the same, `ComboBoxSubtitleFormatsSelectedIndexChanged` isn't fired and the column isn't shown.
