### ISSUE TITLE
Small improvement for bilingual split

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4931]
When there are one or more empty lines (or lines with nothing but spaces or tabs) existing at the end, which was added accidentally in most cases, the operation cannot work unless removing them first manually. Can we just make it a bit smarter to ignore those lines and save some time? Thanks!

**Comment by OmrSi** [comment]
Would it be okay if it removed those lines?

**Comment by LeonCheung** [comment]
Sure! The problem now is that it's impossible to fix it by running Ctrl Shift F tool o**nce for all**, since I'm currently in a workflow that I have to constantly copy/paste things for each line (now you may see what the "accidentally" means  😛 )
