### ISSUE TITLE
ASS Styles

### ISSUE THREAD

**Issue by foresta86** [SubtitleEdit/subtitleedit#4937]
![Screenshot 2021-03-28 124958](https://user-images.githubusercontent.com/25081296/112749670-26aa7780-8fc4-11eb-8193-5fe77c5019ac.png)
As per screenshot

**Comment by OmrSi** [comment]
Can you provide steps to recreate? 
Is there a specific situation where this happened or did it only show up once?

**Comment by foresta86** [comment]
Every time I try to create a new style this error shows up

**Comment by OmrSi** [comment]
Can you try it with the latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by foresta86** [comment]
![Screenshot 2021-03-28 131452](https://user-images.githubusercontent.com/25081296/112750220-a38b2080-8fc7-11eb-83c4-1a3ffd13e212.png)

**Comment by niksedk** [comment]
@foresta86: Could you attach the subtitle file? (eg. zipped)

**Comment by OmrSi** [comment]
I could not reproduce this. I can add styles with no issues to the attached file.

**Comment by niksedk** [comment]
Hopefully working now...
