### ISSUE TITLE
Ending italic tag in a wrong position

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#4938]
Discovered one more case where the actual subtitle line has the italic tag in a wrong position.

[doctorwho_s04e03.zip](https://github.com/SubtitleEdit/subtitleedit/files/6217473/doctorwho_s04e03.zip)
![image](https://user-images.githubusercontent.com/11799308/112755681-6c7a3680-8fea-11eb-8d5a-faa4f821fa2d.png)
![image](https://user-images.githubusercontent.com/11799308/112755690-8287f700-8fea-11eb-9821-9a3b287eb641.png)

**Comment by ivandrofly** [comment]
How to recreate this?

**Comment by Boulder08** [comment]
I can still make it occur with that sup file. What files do you need from my installation to test OCRing?

**Comment by ivandrofly** [comment]
> I can still make it occur with that sup file. What files do you need from my installation to test OCRing?

Nop, the steps to reach where you are in the image above

**Comment by Boulder08** [comment]
That's just normal OCR stuff, so open the sup file in SubtitleEdit and OCR it. With my OCR training set, I get this output even now.
