### ISSUE TITLE
[Feature Request] Allow using current timecodes when importing plain text

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4939]
This is quite a timesaver option when you have ready-to-use timecodes loaded already. Normally, we have to save and close the loaded subtitle first, then import plain text, then import timecodes from that subtitle, which is not quite necessary in this case.

A promo could be:
![tim](https://user-images.githubusercontent.com/494788/112813264-98f88600-90b0-11eb-8733-3191f8a3dd3f.jpg)

Maybe it can only be clickable when the total line count matches between previewed list and the loaded subtitle. Or, it can always be clickable, just leave a warning message for users to use at their own risk. :)

Thanks!

**Comment by darnn** [comment]
For what it's worth, I would definitely leave it always clickable, since sometimes things don't match exactly but the difference is only in a few lines, so you'd still want to use this.

**Comment by LeonCheung** [comment]
@darnn, agree, at least we have some nice tools nested in _**Context menu > Column,**_ which are very handy to do fine tunes.

**Comment by darnn** [comment]
Yeah, I only do things like that fairly infrequently, and the last time I had tried until recently was still in Subtitle Workshop, and let me tell you, SE's is just so much more intuitive and easy to use, it's incredible.

**Comment by LeonCheung** [comment]
Yeah. There should have been more than one way to do this, say, there's also a "Paste from clickboard..." tool. However, it currently doesn't support splitting at separator (say, blank lines), which means it doesn't work with two-line subtitles...

**Comment by PreetM07** [comment]
I second this feature. Highly usable when there are 2 different workflow steps: Transcription and Spotting independently.

**Comment by niksedk** [comment]
Should be included in latest beta
