### ISSUE TITLE
Request for two useful shortcuts

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4940]
Just wondering if we could possibly have two new shortcuts below:

`Move parts before cursor position to previous subtitle.`
and
`Move parts after cursor position to next subtitle.`

Benefits:
1. Work perfectly for languages like CJK (few spaces used between characters, which causes existing "move word" shortcuts fail);
2. Save time when having to move many words/chars.

(P.S. even better to be also available in context menu)

**Comment by LeonCheung** [comment]
Hi, not sure if this is hard to implement, but it's so convenient in many cases. Take a real-life example:

Say, for a project, I have two sources in hand before starting: 
1. the original subtitle ready to translate.
2. a **translations.docx** file.

So, I start working in **Translation Mode**. All I have to do is constantly copy-paste translations from the **translation.docx** file into the "Text" column for each line, right? Depending on the total line numbers, it could be a huge time-waster for copy-pasting work.  

What's more, another problem is: Usually, a long sentence in the original file is split into several lines. So, after pasting into SE, I have to cut-paste parts for other lines. Obviously, it would waste so much time, too.

IMHO, a much better workflow is:

First, we copy a long sentence (or even a whole paragraph with many sentences) into the current line. Then, rather than cut-pasting parts over and over again, we can simply use the operators/shortcuts above to move parts up / down based on the cursor position, with one single click!

I'll make a GIF to illustrate that if necessary.

**Comment by darnn** [comment]
For what it's worth, even before using the shortcuts you're proposing here (which would indeed be useful), I would do what you're describing like this:
Before I open the original subtitle, I'd import the text from the docx file all at once using "import plain text". Then I'd copy the entire contents of this subtitle file into the clipboard.
Next I'd open the original, and use "make new empty translation from current subtitle". In the translation, I would use column paste to paste the contents of the translation file. Now you have them both in the same place and you don't have to paste them individually.
This is still the point at which you'd need the shortcuts you were talking about, but at least it's shorter.

**Comment by LeonCheung** [comment]
@darnn Yep, that's exactly the workflow I took. It seems we both agree that the key point here is "how to match original and translation as easy as possible", right?  :)

In some short projects, I've tried to use notepad++ to open two txt files, and break lines accordingly in order to finally match the line count, because I can then simply import the timecodes from the original srt. However, the biggest problem here is, original timecodes and break positions are not always perfect, I need to review the project again to do some tweaks which would double the work time, especially for long projects.

**Comment by darnn** [comment]
Oh yes, I do agree that that is the key point.

**Comment by niksedk** [comment]
thx for the input :)

I've added one of the shortcuts (with a go to next line):
![image](https://user-images.githubusercontent.com/1261331/116675873-96869600-a9a6-11eb-9050-281fbb260d0f.png)

I've also added a "Merge sentences..." menu item which can be used as a pre-translate step:
![image](https://user-images.githubusercontent.com/1261331/116676012-c59d0780-a9a6-11eb-991c-91840d0f1191.png)


https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
@niksedk Sorry for the late reply. It looks pretty. Thanks a lot for the timesaver feature! Btw, just found something fishy with "Merge sentences..." tool: 
After merging, if highlight some line in the list view area, some timecodes would be changed randomly. I tried with the latest beta. FYI

**Comment by niksedk** [comment]
Thx, random time codes after merge should be fixed in latest beta.

**Comment by LeonCheung** [comment]
Cool. Thanks for the fix!
