### ISSUE TITLE
Improvement on loading media

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4941]
Currently, when trying to load media via button or menu, it will be loaded really fast if we loaded it previously since waveform has already been generated. This is cool. And, it also works fine when dragging media into the video player. But when trying to drag into waveforms area, it will always be re-generated. Maybe it can be improved a little?

**Comment by niksedk** [comment]
Can't you drag to the video/audio player?

**Comment by LeonCheung** [comment]
I can, for sure. But sometimes when working with mp3, the video player doesn't need to be shown up, so... Not a big deal though, just point it out.
