### ISSUE TITLE
BinaryImageCompare for Batch converter (command line)

### ISSUE THREAD

**Issue by Daniel-Abrecht** [SubtitleEdit/subtitleedit#4943]
In the GUI, I can select the Binary image compare OCR method, which works really well for me.
However, I would prefer not to have to use the GUI, but it seams the Batch converter doesn't support `/ocrengine:BinaryImageCompare` yet.

It would be great if the Binary image compare OCR method could be made accessible from the command line.

**Comment by niksedk** [comment]
I think you can use `/ocrengine:nocr` which is about the same as binary image compare, only better.

**Comment by Daniel-Abrecht** [comment]
On the subtitle I tested with, `/ocrengine:nocr` didn't detect a single letter. Maybe I'm using it wrong?

**Comment by Daniel-Abrecht** [comment]
Ok, I got it working. I needed to also specify `/pac-codepage:Latin`. Now it works like a charm. Thank you very much!
