### ISSUE TITLE
[Resolved] Remove text not in italics, to remove non-translations

### ISSUE THREAD

**Issue by mentbrother** [SubtitleEdit/subtitleedit#4946]
Right now I'm unable to find a series of subtitles for only translated dialogue (Arabic and Russian dialogue in an English series), but finding many subtitles where translated lines are specially formatted in italics. I'd love to see a feature to remove all the unformatted text, preserving only translated dialogue. My apologies if this feature is already present, I searched but couldn't find it.

**Comment by OmrSi** [comment]
From `Edit -> Modify selection`

![image](https://user-images.githubusercontent.com/20923700/113142590-b99d1900-9233-11eb-9ca0-36ec4a567a17.png)

**Comment by mentbrother** [comment]
> From `Edit -> Modify selection`
> 
> ![image](https://user-images.githubusercontent.com/20923700/113142590-b99d1900-9233-11eb-9ca0-36ec4a567a17.png)

Nice, thanks king.

**Comment by OmrSi** [comment]
You got it. 
You should close the issue since it's resolved.

**Comment by mentbrother** [comment]
oh cool I didn't know that was an option :)
