### ISSUE TITLE
Customized shortcuts failed in Un-dock video controls mode

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#4948]
It only occurs when switching focus from textbox to waveform area directly. Not sure if it is a bug.

**Comment by LeonCheung** [comment]
UPDATE: It's specifically for some non-combo shortcuts. Say, when setting W for "Go to the previous line".

**Comment by OmrSi** [comment]
Shortcuts that only use a character like A or the dot or a number don't work when the text box is focused beacuse that would make the user unable to write that character. 

There is an option in the settings file that you can enable to be able to do this called `AllowLetterShortcutsInTextBox`

**Comment by LeonCheung** [comment]
Hmm, but I just tried Ctrl Shift F, which is the default Check Error shortcut, it also failed.

**Comment by OmrSi** [comment]
In which situation exactly? It's not very clear.

**Comment by LeonCheung** [comment]
Okay, to produce:

1. Un-dock.
2. Be sure focus is in the textbox first.
3. Then switch focus to the waveform area.
4. Hit shortcuts we discussed.
