### ISSUE TITLE
Bug: creating a new event > edit something in source view > go back to waveform > event gets erased

### ISSUE THREAD

**Issue by PreetM07** [SubtitleEdit/subtitleedit#4955]
While the source view + waveforms are active, creating a new event at some point then a change in source view editor and coming back to the waveform, erases the newly created event.

Steps to reproduce:
1. Activate the source view.
2. Create a new event on the waveform by clicking on waveform. (I am using keyboard shortcut here)
3. Go to the source view box, do some change and click back on the waveform.
4. This erases the newly created event.

**Comment by niksedk** [comment]
Thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
Does this solve the other issue too?

**Comment by PreetM07** [comment]
Hey Nikse. Thanks for the update!
This beta build doesn't fix the issue.

Instead the behavior is totally changed now.

Steps:
1. Activate the source view
2. Keep the file empty for testing so that the source view creates empty textbox
3. Insert a new event at some position using waveform. (Insert any number of events N >= 1)

Actual behavior:
All the created events are erased irrespective of the event number.

Desired behavior: (?)
All the event times should be registered in the source view. (This is the current behavior of latest release. This is needed.)

**Comment by PreetM07** [comment]
Also I think #4954 is connected. I am not able to test this as it is not possible with current Beta build's behavior.

**Comment by niksedk** [comment]
Works for me... could you explain better what you steps are? Images could help.

**Comment by PreetM07** [comment]
1. My initial screen. I have just kept 2 dummy events.
![image](https://user-images.githubusercontent.com/63149170/114169465-3d9b8300-994f-11eb-8608-581f2239deca.png)

2. Insert an event by clicking on the waveform position and shrotcut. (Here aslo, the timings are not directly registered (appeared?) in the source view box unless changed in-out cue time of that event.)
![image](https://user-images.githubusercontent.com/63149170/114169646-72a7d580-994f-11eb-8720-2691a86d92c7.png)

3. Now without changing the time, just go in the source box, do some editing and click back on the waveform. When we go in the source box, at this time also the event is not visible in the source box, so whatever editing is forced to be done is done in earlier event texts.

4. Newly created event would disappear.

**Comment by PreetM07** [comment]
Also as you might work on source view modules, can you please, please, please add ctrl+I addition in the source view (or I can log in a new bug, maybe.)
ctrl + I in the source view, I think indents the text instead of italicizing.
Would be a step closed for #3234

**Comment by niksedk** [comment]
OK, what shortcut do you use to create the new subtitle line?

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
Fix many shortcuts to update the source view... does it work now?

**Comment by PreetM07** [comment]
I use ctrl + alt + Q.
But I tested with default shift + f9 in last beta.

**Comment by PreetM07** [comment]
Works like a charm.
Not sure but just raising one thing here.
Performing the same steps, the issue is resolved. However, the default time (min time of an event) changes to 2 secs.

1. Activate focus mode.
2. Create an event by set keyboard shortcut. (shift + f9)
3. Event is created in waveform dashboard. and also populated in the focus mode editor. (Kudos) In my case default set is at 2.5 secs so notice the inserted event's time.
![image](https://user-images.githubusercontent.com/63149170/114223325-4d39bc80-998d-11eb-8bbc-f146c7de72de.png)

4. Go to the focus mode, edit something. 
5. The time becomes 2 seconds. This is irrespective of the min time set. (tested with 800, 1000 and 2500 mS)
![image](https://user-images.githubusercontent.com/63149170/114223471-82dea580-998d-11eb-9eae-9b3cbbaef3ba.png)

**Comment by niksedk** [comment]
Beta updated with changes in source view regarding default duration of new texts: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by PreetM07** [comment]
It works.

**Comment by OmrSi** [comment]
@PreetM07 Does it solve your other issue as well?

**Comment by OmrSi** [comment]
@PreetM07 Does it solve your other issue as well?

**Comment by PreetM07** [comment]
Yes, I forgot to mention. This fixes #4954 
Thanks for the update guys.
