### ISSUE TITLE
How to export to SRT after saving as a .sep project file?

### ISSUE THREAD

**Issue by cirosantilli** [SubtitleEdit/subtitleedit#4976]
subtitleeditor 0.54.0-4 Ubuntu 20.10, to reproduce:

- file > new
- add one random subtitle line
- file > save > save project > test.sep

Now, `test.sep` was created as the XML project file, but I can't find how to export to SRT after this point.

E.g. if I try the obvious:

- file
- save
- save as
- pick .srt from file type box

it generates `test.srt`, but that is not an SRT, it is still the exact same XML as `test.sep`

**Comment by niksedk** [comment]
Wrong project?

**Comment by cirosantilli** [comment]
Oooooooooooooooooooooooooooooooops.
