### ISSUE TITLE
Request: Add "Break early for colon" option

### ISSUE THREAD

**Issue by matheusguifer** [SubtitleEdit/subtitleedit#4979]
It would be useful to have this option in Settings > Tools because, when using a non-speech information to identify the manner of speaking in captions, I think it looks more polished to have the non-speech information on one line and the actual utterance on another. For instance:

(WHISPERING):
It's gonna be okay.

**Comment by niksedk** [comment]
You can try Edit - Multiple replace. Replace `: ` with `:\n`, like this:
![image](https://user-images.githubusercontent.com/1261331/115081678-fee46a80-9f04-11eb-876a-1430f2963e78.png)

**Comment by niksedk** [comment]
"Break early" would not work for you, as it only applies to lines that should be split.
