### ISSUE TITLE
Subtitle Edit Startup Error on SE 3.6.0

### ISSUE THREAD

**Issue by VikiPulsarkid** [SubtitleEdit/subtitleedit#4980]
Hi Niksedk,

I'm using a desktop with Win 10, 64-bit version. I was working with Subtitle Edit 3.6.0 for the past few months and it was working fine and today, I can't open the SE. I tried uninstalling the same and installed it back, still, the same issue happened. I also downloaded the portable version of SE 3.6.0 and nothing changed much. Please look into the image below about the issue. I've also tried with the older versions of the SE. Can't work it out. Do let me know to sort this out.

**Comment by niksedk** [comment]
What OS are you using?
What path did you install SE to?
Where is the image? ;)
