### ISSUE TITLE
Big5 Traditional Chinese Encoding Error when saving Screen Electronic PAC format

### ISSUE THREAD

**Issue by sandrickn** [SubtitleEdit/subtitleedit#4982]
I am having an issue when saving PAC format subtitles with big5 Traditional Chinese encoding. 
It appears some characters may be encoded with "?" when I try to reopen the file.

I attached some images for reference.
![image](https://user-images.githubusercontent.com/74899572/114489397-a7fd3d80-9c45-11eb-8415-78862eff171d.png)

**Comment by niksedk** [comment]
Could you attach the sub as srt with Chinese text?

**Comment by sandrickn** [comment]
@niksedk I attached the test file in SRT
[Big5 Test File.zip](https://github.com/SubtitleEdit/subtitleedit/files/6314714/Big5.Test.File.zip)

**Comment by sandrickn** [comment]
Hi @niksedk, I have revisited this issue recently after the 3.6.4 update and found the following error. I presume it happens when saving with negative timecodes.

![image](https://user-images.githubusercontent.com/74899572/145428609-1d550a9f-2e36-404d-a630-a3a7ff5c4945.png)

Additionally, the previous encoding issue still appears on both exporting individually and batch processing.

Hope this finding is helpful!

**Comment by sandrickn** [comment]
Hi @niksedk! I was playing around this issue again, let me report my new findings!

The exported file (File > Export > PAC (Screen Electronics)) based on my first comment last year, it appears that only lines with "-" character is corrupting the encoding of the line.

> I am having an issue when saving PAC format subtitles with big5 Traditional Chinese encoding. It appears some characters may be encoded with "?" when I try to reopen the file.
> 
> I attached some images for reference. ![image](https://user-images.githubusercontent.com/74899572/114489397-a7fd3d80-9c45-11eb-8415-78862eff171d.png)

As for the batch converter, I'm not sure which file to refer to but it appears to have skipped the encoding process altogether.

I tried looking into the source code but I have little experience with C Programming...
I hope this is helpful and thanks so much for your hard work!
