### ISSUE TITLE
Multithreaded 'Batch Converter'

### ISSUE THREAD

**Issue by adem0x** [SubtitleEdit/subtitleedit#4986]
I am using 'Batch Converter' to convert 104 .sub files to .srt.

I am grateful that there is an easy to use GUI exists for that.

But, I can see that each .sub file is processed sequentially.

While the CPU load is 0.2%, it does take a long to time to do each file that way.

Would it be possible to give me an option to specify the number of threads, n, and then process n files in n separate threads?

**Comment by adem0x** [comment]
To further support why I asked for multi-threaded processing, here is some more data:

104 files
.sup total: 927 MB
.srt total: 3.10 MB

Time taken to process: ~ 7 hours

OS: Windows 10
CPU: AMD Ryzen Threadripper 3990X, 4200 MHz (64-Core)
RAM: 256 GB
Disk: 2 TB NVMe, 4th Gen

**Comment by RedSoxFan04** [comment]
Multithreading would also be nice for individual subtitles.
