### ISSUE TITLE
Flickering of preview timecodes when seeking in video player

### ISSUE THREAD

**Issue by LucretiaAudrey** [SubtitleEdit/subtitleedit#4987]
Hi! Installed SubtitleEdit 3.6.0 on windows 8,1, and found a weird glitch - when attempting to seek a video, timecode  flickers (see video below)

https://user-images.githubusercontent.com/80807826/114827139-c39d4b00-9de1-11eb-827e-4e84c4d6512c.mp4

**Tried MPV, DirectShow, MPC-HC - all have same issue. Tried reinstalling .Net, Lav Filters - same thing

More so - hovering over seek bar also stops waveform from moving**

https://user-images.githubusercontent.com/80807826/114827459-28f13c00-9de2-11eb-97d0-8a87a3cdf931.mp4

Previous versions of SE don't seem to support preview timecode, so they work fine.

How can this be fixed?

For reference, PC specs are:

![hwinfo](https://user-images.githubusercontent.com/80807826/114827754-84bbc500-9de2-11eb-825a-c3ac28b777cc.png)

**Comment by niksedk** [comment]
thx @LucretiaAudrey and @OmrSi :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by LucretiaAudrey** [comment]
Thanks a ton! Checked - everything works fine now.

Out of curiosity - was this .Net related issue?

**Comment by OmrSi** [comment]
@LucretiaAudrey The tooltip was being shown when the mouse moves based on the `MouseMove` event, but the event seems to be firing even when the mouse isn't moving for some reason -could be that the relative position of the mouse to the shown tooltip is changing-, so I just made it store the old mouse coordinates and only show the tooltip again when the new position is different from the old one.
