### ISSUE TITLE
[Bug?] Unable to Process PGS Subtitle

### ISSUE THREAD

**Issue by peter-qgd** [SubtitleEdit/subtitleedit#4995]
Hi, while trying to change the brightness of a BD's subtitle, the program doesn't show up its preview and if I try to save
the changes, it will get frozen and start to hog the system's memory.

I leave you the aforementioned subtitle, in case you might be able to fix the issue:

[Unable-to-Change-Brigghtness.zip](https://github.com/SubtitleEdit/subtitleedit/files/6329034/Unable-to-Change-Brigghtness.zip)

Thanks.

**Comment by peter-qgd** [comment]
Hi, I see you were able to detect the problem, so I bet we may have the fix integrated in a next version.

Thanks. 👍

**Comment by niksedk** [comment]
Hi Peter,

thx for the issue with attached sub :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

SE bd sup edit had not been tested with full frame images.
The preview image is now cropped and the processing is now multi-threaded - memory usage is still huge for these kind of images - a seriously lot of pixes :)

**Comment by peter-qgd** [comment]
I just tried the beta, and now it works fine, although there is still some little issue I also noted about that subtitle:

![sub image](https://user-images.githubusercontent.com/82705380/115118739-1827fe00-9f7b-11eb-82c6-63658df5bc78.png)

The preview text is shown with a very little size, while with all the other PGS subtitle I worked with so far the text size is fine. Is that something you might be able to fix as well?

**Comment by peter-qgd** [comment]
> Hi Peter,
> 
> thx for the issue with attached sub :)
> Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
> 
> SE bd sup edit had not been tested with full frame images.
> The preview image is now cropped and the processing is now multi-threaded - memory usage is still huge for these kind of images - a seriously lot of pixes :)

Hello, I was trying the beta version to fix a few timing issue with the above PGS subtitle, but I noticed there are some features missing: "start time" and "gap" columns. Besides, they can't be relocated. And there are no "timing" issues reported at all.

Do you plan to add them back in a next beta? Thanks.

**Comment by peter-qgd** [comment]
Hello, I was trying the beta version to fix a few timing issue with the above PGS subtitle, but I noticed there are some features missing: "start time" and "gap" columns. Besides, they can't be relocated. And there are no "timing" issues reported at all.

Do you plan to add them back in a next beta? Thanks.
