### ISSUE TITLE
multiselect subtitles in wave

### ISSUE THREAD

**Issue by panther7** [SubtitleEdit/subtitleedit#5]
Copied from: http://code.google.com/p/subtitleedit/issues/detail?id=84

Hi,
i have suggestion, u can add multi-select subtitles (hold Ctrl + mouse click on subtitles) in waveline?
Eg. moveable selected subtitles on waveline and so on...

**Comment by niksedk** [comment]
Better late than never... should be added now :)

Ctrl + mouse left click is already taken... so latest beta now has "Ctrl + mouse right click" and "Shift + mouse right click".
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by panther7** [comment]
Thanks
