### ISSUE TITLE
Duplicate/Double Lines Issue

### ISSUE THREAD

**Issue by pandamoon21** [SubtitleEdit/subtitleedit#5001]
Hi, how can I change the maximum milliseconds time in "Merge lines with the same text more than 10000 ms (10s), because in my case the duplicate lines have more than 10s gap between the lines?
Or is there any way to find and delete/merge duplicate lines into a single line without finding them manually using "Spell check >> Find double lines"?

**Comment by OmrSi** [comment]
You can try `Merge line with same text` or `Merge line with same timecodes` from the tools menu.
