### ISSUE TITLE
[Question] Error Reading the timecode

### ISSUE THREAD

**Issue by pandamoon21** [SubtitleEdit/subtitleedit#5002]
Hi, I got the prompt regarding this problem. I can't find it in the issues so I decided to open a new one. (or maybe I missed it)
Here the screenshot,

![2021-04-20_095305](https://i.postimg.cc/RVqDwFPZ/2021-04-20-095305.png)

What is the trigger of this problem exactly? So I can try to fix it.
I converted the subs from `stpp` codec in `mp4` container into `srt`.

**Comment by OmrSi** [comment]
Can you attach the sub?

**Comment by niksedk** [comment]
It's the first time I've seen a subtitle going over 100 hours :)
SE does not support this. 
You could open the raw .srt file in a text editor and (regex) replacements.
How did you get the .srt from the mp4 file? Mp4box?
