### ISSUE TITLE
Missing features from latest Beta version

### ISSUE THREAD

**Issue by peter-qgd** [SubtitleEdit/subtitleedit#5003]
Hello, I was trying the beta version to fix a few timing issue with the above PGS subtitle, but I noticed there are some features missing: "start time" and "gap" columns. Besides, they can't be relocated. And there are no "timing" issues reported at all.

Do you plan to add them back in a next beta? Thanks.

**Comment by niksedk** [comment]
The timing issues reporting was not *really* working before... 
I've added live checks for overlap/duration here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
(some customization allowed for columns - right click on the list view header)

**Comment by peter-qgd** [comment]
>...

Hi, regarding the "timing issues", what I mean is that in the last stable version lines with "duration" issues were highlighted, while that wasn't the case with the previous beta. That's fixed now.

Respect "columns", although now they can be shown, they still can't be "relocated", which is possible in last stable version.

Thanks.

**Comment by niksedk** [comment]
Beta updated which should allow column re-ordering: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
