### ISSUE TITLE
Cannot apply Netflix quality check

### ISSUE THREAD

**Issue by dezraj** [SubtitleEdit/subtitleedit#5005]
When I visit the "Netflix quality check" option it shows me the lines and what must be changed. Then I click OK but nothing changes in the subtitles.

Is there a way to apply these changes just as we do with the "fix common errors" option or is it there just for the purpose of information?

I'm using version 3.6 portable on Windows.

**Comment by niksedk** [comment]
It's just for info atm, but the idea was to implement at least some auto fixes in the future.

**Comment by chenlung** [comment]
Maybe try [EditingTools](https://en.editingtools.io/subtitles) and [SubTimingsBeautifier](https://github.com/Flitskikker/SubTimingsBeautifier) in the meantime.

**Comment by Znuff** [comment]
it would be really nice if there'd be some update on this. 

The check is great, but without an actual way to apply them automatically, or at least manually selecting which modifications to make, it's a bit of a let down.
