### ISSUE TITLE
Text box not moving automatically

### ISSUE THREAD

**Issue by nmos25** [SubtitleEdit/subtitleedit#5006]
The text box where the subtitles are stopped playing automatically as the video plays as well and I don't know how to fix it. Could anyone help me out?

**Comment by niksedk** [comment]
Sounds like the check box "Select current subtitle while playing":
![image](https://user-images.githubusercontent.com/1261331/115978807-8031a200-a582-11eb-907c-2dbc8f4d46b6.png)
