### ISSUE TITLE
Text box/section resizes when opening/adding a video or waveform

### ISSUE THREAD

**Issue by AbsenceJam** [SubtitleEdit/subtitleedit#5013]
See below images. Would it be possible to prevent this behaviour?

![1](https://user-images.githubusercontent.com/24455272/116780264-72dd5180-aa73-11eb-9835-5d64ca7b7ffe.png)
![2](https://user-images.githubusercontent.com/24455272/116780266-740e7e80-aa73-11eb-8317-0ebe9dc4c453.png)
![3](https://user-images.githubusercontent.com/24455272/116780267-753fab80-aa73-11eb-9280-d5385b6a6301.png)
![4](https://user-images.githubusercontent.com/24455272/116780268-75d84200-aa73-11eb-8668-d402eb65d423.png)

**Comment by darnn** [comment]
Oh yeah, that would be great.

**Comment by niksedk** [comment]
Prevent what behavior exactly?

**Comment by darnn** [comment]
The textbox's height changing when you use show/hide video, show/hide waveform, etc. In the first two screenshots there, that's before show/hide waveform and after, you can see that the height is different (the third line is no longer visible).

**Comment by AbsenceJam** [comment]
*The first two are before and after the waveform is shown. Third and fourth are the same for video.

You can start off with the text section resized as large as it will allow but every time you show the video or waveform (hiding does not resize it, only showing) the size decreases until it reaches the minimum height it allows.

![1](https://user-images.githubusercontent.com/24455272/116820059-f9c12580-ab6a-11eb-829e-ec9fcde5a92c.png)
![2](https://user-images.githubusercontent.com/24455272/116820062-fc237f80-ab6a-11eb-943a-deda21893eaa.png)
![3](https://user-images.githubusercontent.com/24455272/116820065-fcbc1600-ab6a-11eb-8c65-8d29c9cbd842.png)
![4](https://user-images.githubusercontent.com/24455272/116820066-fd54ac80-ab6a-11eb-8b92-723aae8390e5.png)

**Comment by niksedk** [comment]
OK, it's no easy as winforms do not have events for maximized + de-maximize... gave it a try... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by darnn** [comment]
This seems to work properly now with show/hide video and show/hide waveform. However, since you're working on this, another case where the height changes even though I believe it shouldn't is when you resize the video:
![se-GIF 02-May-21 10-56-27 PM](https://user-images.githubusercontent.com/19672444/116825890-f4c79a80-ab99-11eb-990d-17ccc826f960.gif)

**Comment by niksedk** [comment]
Beta updated - should now handle waveform/video-player resize also: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by darnn** [comment]
For the recrod, the thing I demonstrated in the gif seems to still be happening for me, and the beta from two hours ago seems to be the same as the one from 17 hours ago.

**Comment by niksedk** [comment]
Trying again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
Better?

**Comment by darnn** [comment]
Somewhat, but it doesn't exactly work right away. If I open SE without a subtitle file or a video file, then add a few lines to the empty subtitle file so i can use the textbox, and then change the height of the video pane, it still changes the height of the textbox. However, if I use show/hide video and show/hide waveform several times, and then go back to just having an empty video pane, at that point it does work properly. I can go into more detail if you like.

**Comment by niksedk** [comment]
Yet another try: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Better, but not all the way: If I change the height of the video pane the textbox height doesn't change. But if I then change the height of the textbox, and _then_ change the height of the video pane again, the height of the textbox reverts to what it had been before:
![se-GIF 03-May-21 8-57-48 PM](https://user-images.githubusercontent.com/19672444/116913756-8b579280-ac52-11eb-8cc5-63f7c6c94c94.gif)

**Comment by niksedk** [comment]
Hm, I cannot re-create that...

**Comment by darnn** [comment]
Happens pretty consistently for me... I don't have access to my Windows 10 machine now, so I don't know if this is somehow a Windows 7 thing, but the quickest way to recreate it for me is:
Open SE without a subtitle file or a video file. Increase the height of the textbox. Now increase the height of the video pane. The height of the textbox reverts to its previous value.

**Comment by niksedk** [comment]
Still cannot re-create this on Win10.

Does it make any difference if you do it fast or slow? 
Sounds like a minor issue...

**Comment by darnn** [comment]
Doesn't seem to make a difference if it's fast or slow. And yes, I would say that it's minor.  Unless somebody else comes along who can recreate it on Windows 10, feel free to close it.

**Comment by AbsenceJam** [comment]
> OK, it's not easy as winforms do not have events for maximize + de-maximize... gave it a try... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

That works great.

I couldn't reproduce @darnn's issue either (W10).
