### ISSUE TITLE
Suggestion: Show/hide waveform shortcut

### ISSUE THREAD

**Issue by AbsenceJam** [SubtitleEdit/subtitleedit#5014]
This menu item seem to be missing from the shortcut settings. Would be great to have it added.

Thanks

**Comment by PreetM07** [comment]
You can adjust the area occupied by the waveform. Minimize the viewing area by dragging down.

**Comment by AbsenceJam** [comment]
I can also turn it off entirely via the menu, hence the suggestion for a shortcut for that. A menu item/shortcut to hide both in addition would be sweeter still.
