### ISSUE TITLE
Spell check with suggestions or "change" not change word in subtitle!

### ISSUE THREAD

**Issue by zildan** [SubtitleEdit/subtitleedit#5020]
Spell check replace word in file only using "Edit whole text"
 I use romanian dictionary, after select suggestions word and push "use" nothing is happened in file, also with typed word and push "replace".
Only "Edit whole text" change subtitle file!
![image](https://user-images.githubusercontent.com/4396001/116935474-147cc280-ac6f-11eb-9f2c-6695b61696cd.png)

Tested with 3.6.0 and 3.5.11

**Comment by niksedk** [comment]
Could you attach the subtitle file? (zipped or as .txt)

**Comment by zildan** [comment]
yes
[ex.zip](https://github.com/SubtitleEdit/subtitleedit/files/6419075/ex.zip)

**Comment by niksedk** [comment]
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by zildan** [comment]
Now it's fine. Thank you

**Comment by niksedk** [comment]
Thx for verifying :)
