### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by proall** [SubtitleEdit/subtitleedit#5022]
![Screenshot_2](https://user-images.githubusercontent.com/36814374/117047071-1c457100-ad1a-11eb-8f16-d4b854d5f745.png)

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by proall** [comment]
Already using the latest beta...
Maybe its because i am tried to translate subtitles that have the name Index on some lines?

**Comment by niksedk** [comment]
Could you attach the subtitle file?

**Comment by proall** [comment]
https://www.mediafire.com/file/5w5o54meqrh9rsb/IndexEP3.ass/file
