### ISSUE TITLE
Hebrew characters in UI text box

### ISSUE THREAD

**Issue by OMedicks** [SubtitleEdit/subtitleedit#5023]
trying to create subtitles in Hebrew.
The text box displays wrong encoding (please see attached screenshot)
The text appears correctly on the video

![Screenshot_20210505_165601](https://user-images.githubusercontent.com/79050468/117162568-2cfdf180-adc3-11eb-8176-a055aa5129cd.png)

My OS is Linux Manjaro 5.9.16 KDE Plasma desktop.
Running Subtitle Edit via mono

Thank you very much!

Oren

**Comment by niksedk** [comment]
Could you try another font? 
See Options - Settings - Font.

**Comment by OMedicks** [comment]
Yes. The screen shot is with Noto sans Hebrew.
no change

**Comment by OMedicks** [comment]
I apologize for misleading you.
After deleting the existing non-readable text,
new text is readable using the Hebrew font.
Thank you very much!

Oren

**Comment by niksedk** [comment]
Cool, I'm glad the text is readable now :)

**Comment by OMedicks** [comment]
Sorry again. I've just noticed that with the Hebrew font, this happens :((
![Screenshot_20210505_194424](https://user-images.githubusercontent.com/79050468/117185890-9a694c80-adda-11eb-8b09-2d8f6955fd25.png)

**Comment by OMedicks** [comment]
I am quite sure it has something to do with Linux.
I have worked with SE previously in Windows 10,
and all was very smooth.
I did install all dependency packages.

**Comment by OMedicks** [comment]
Does any one know of a shortcut to toggle between Waveform and Text box?
There is a context menu option, but couldn't find a fast keyboard shortcut.
Thank you very much for responding
