### ISSUE TITLE
Hebrew characters in UI text box - continued, unfortunately

### ISSUE THREAD

**Issue by OMedicks** [SubtitleEdit/subtitleedit#5024]
I was so happy to see Hebrew characters in the text box, I failed to notice this:
![Screenshot_20210505_194424](https://user-images.githubusercontent.com/79050468/117192105-a3a9e780-ade1-11eb-8325-226cabdb4c0e.png)

I am really sorry about this.
It is probably related to Manjaro, somehow.
Previously, I made Hebrew subtitles with SE in Win 10, with no problem.

I apologize for the confusion.

Oren

**Comment by proall** [comment]
You can use Hebrew, just switch to UTC-8 encoder, should be fix.

**Comment by OMedicks** [comment]
thanks proall, but no. :( Actually, there is no unicode font in the 'font' settings

**Comment by proall** [comment]
I'm using Hebrew with UTC-8 and its working..
BTW you speak Hebrew?

**Comment by darnn** [comment]
I do, if it helps, though I don't have Linux.

**Comment by OMedicks** [comment]
Proall - yes, I do
