### ISSUE TITLE
[Feature Request] Add a separate "pixels in space" value in OCR for normal and italics text

### ISSUE THREAD

**Issue by GoesUp** [SubtitleEdit/subtitleedit#5028]
When OCRing a `.sup` subtitle, there is an option called `No of pixels in space`, which allows for manual setting of how many pixels have to be between letters to detect a space.
However, I frequently encounter subtitles where a certain value works great for normal text, but not for italics, or the other way around. This way, I sometimes end up with subtitles where text in italics has missing spaces.

It would be great if I could set _two_ values, one for normal text and one for italics.

**Comment by niksedk** [comment]
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/4051
