### ISSUE TITLE
OCR rules

### ISSUE THREAD

**Issue by iGom** [SubtitleEdit/subtitleedit#5038]
Many Polish words end with "-ej" letters, OCR often detects the ending "ej" as "e]" so is it possible to somehow create a rule for OCR that will always change the ending "e]" to "ej"?

**Comment by niksedk** [comment]
Hm, you could try:

a `<PartialLines>` entry `<LinePart from="] " to="ej " />`

or

a `<PartialWords>` entry ` <WordPart from="e]" to="ej" />`

or some regular expression...

I guess you'll have to be careful not to "fix" correct `]` tags.

**Comment by iGom** [comment]
Unfortunately, both rules have no effect. I'm left with adding whole words to replace list for now. 
Also, I forgot to mention that the problem with those endings only occurs in the "Original Tesseract" engine

**Comment by niksedk** [comment]
I could try to look a bit more if you attached the sub (could just be a few lines, in SE you can delete lines and export as bd sup).

If the font is not too small (dvd like), you could try nOCR where you have more control of the trained of characters - see https://www.nikse.dk/SubtitleEdit/nocr

**Comment by iGom** [comment]
Some subs are from Blu-ray, some from DVD
[Test sup EJ.zip](https://github.com/SubtitleEdit/subtitleedit/files/6473368/Test.sup.EJ.zip)

I'll take a look at nOCR

**Comment by niksedk** [comment]
I've tried with both Tesseract 3.02 and 5 beta... and I don't get any "e]"

![image](https://user-images.githubusercontent.com/1261331/118174892-acc53500-b42f-11eb-9adb-3280c94eea18.png)

![image](https://user-images.githubusercontent.com/1261331/118174970-c8c8d680-b42f-11eb-9a60-f67492070ba7.png)

**Comment by iGom** [comment]
As I mentioned before it only occurs in the "Original Tesseract only" engine, (which I usually use because it detects italics.)

![obraz](https://user-images.githubusercontent.com/4786772/118191250-35e26900-b43c-11eb-8910-0b9eece7565c.png)
