### ISSUE TITLE
Wave form / Text box focus toggle shortcut

### ISSUE THREAD

**Issue by OMedicks** [SubtitleEdit/subtitleedit#5040]
Is there somewhere a shortcut that toggles focus between the text box and the wave form?
I saw a text box focus in the wave form context menu, but a shortcut would be far more efficient.
If it does not exist, is it possible to add it to a feature request?

Thank you very much!

**Comment by OmrSi** [comment]
Right now, it doesn't exist.
You can do it by using the `Toggle focus between list view and subtitle text box` twice, and it will take you to the text box.

**Comment by OMedicks** [comment]
Wow! Super useful! 
Thank you very much, Omar
