### ISSUE TITLE
"The cloud file provider is not running" issue.

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#5046]
Hello, I came across this issue when dragging a file from the cloud to SE.

![seerror](https://user-images.githubusercontent.com/37704802/118351398-5fd68100-b54b-11eb-8ca9-99da84a5e462.png)

**Comment by OmrSi** [comment]
Could this be a OneDrive issue?

**Comment by lambdacore12** [comment]
I know it's a OneDrive issue, I was just thinking if the developer would like to handle it.
