### ISSUE TITLE
Object reference not set to an instant of object

### ISSUE THREAD

**Issue by kocoten1992** [SubtitleEdit/subtitleedit#5047]
I got this from version v3.6.0

![Screenshot from 2021-05-16 08-48-55](https://user-images.githubusercontent.com/7130705/118383233-34749480-b626-11eb-8b58-e0c6d722f183.png)

It happen after I installed libmpv (as subtitleedit suggest)

**Comment by niksedk** [comment]
Hi @kocoten1992 - could you try latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

Should hopefully be fixed...

**Comment by kocoten1992** [comment]
No, I try it before, it did not fixed, but I think this is just UI bug.

Step to reproduce:
1. Click video->open
2. While video is loading (or if video is bugged) - try click video->open again, this bug will happen

The biggest elephant in the house is, I can't get it to load video on windowns (it could be because I install windows N version - https://support.microsoft.com/en-us/topic/media-feature-pack-for-n-editions-of-windows-10-version-1607-b657cb70-33e7-1f11-7119-3b4b50be4e89)

I'll try to fix it and let you know

**Comment by kocoten1992** [comment]
hi @niksedk , it is the root cause, install media pack + window media player does solve the problem.

I'mma leave the issue here, feel free to close it, thank you!
