### ISSUE TITLE
remove unused line breaks

### ISSUE THREAD

**Issue by igenaya** [SubtitleEdit/subtitleedit#5050]
After I remove text for hearing impaired, the break line between HI text remain and there's (-), but before HI there arent (-)
 here is the original text:
![image](https://user-images.githubusercontent.com/83929909/118586767-eac6ae00-b7cd-11eb-8588-8d61fd9f82cc.png)
after HI:
![image](https://user-images.githubusercontent.com/83929909/118586831-0467f580-b7ce-11eb-9c4c-5ed7b5b7176b.png)

I use Fix Common Error > Remove unused break line. But it only remove the break line at bottom

![image](https://user-images.githubusercontent.com/83929909/118586386-3593f600-b7cd-11eb-8ac3-0cce0caeffe7.png)

Then I use remove line-breaks from selected line but it remove the break line at middle and left space like this
![image](https://user-images.githubusercontent.com/83929909/118587182-bacbda80-b7ce-11eb-8f27-802372f6eb1b.png)

[sub.zip](https://github.com/SubtitleEdit/subtitleedit/files/6498246/sub.zip)

**Comment by niksedk** [comment]
I'll need the sub before "Remove text for HI", thx.

**Comment by igenaya** [comment]
here it is, thanks before
[original.zip](https://github.com/SubtitleEdit/subtitleedit/files/6501134/original.zip)
