### ISSUE TITLE
Error after changing video pane size

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#5052]
3.6.0 next beta 425.
![se-error](https://user-images.githubusercontent.com/19672444/118961258-cd7c1600-b96c-11eb-95be-b7fffb8108e0.png)

**Comment by niksedk** [comment]
How can I re-produce this?

3.6.1 is out :)

**Comment by darnn** [comment]
And then again when using "make new empty translation from current subtitle".

![se-error2](https://user-images.githubusercontent.com/19672444/118961820-69a61d00-b96d-11eb-863f-31cc7110fc2a.png)

**Comment by darnn** [comment]
Oh, I'm not sure, I thought the messages themselves would be able to give you some indication, and that it's recent enough that it must still exist in 3.6.1. But I'll switch and see if I can get it to happen again.

**Comment by niksedk** [comment]
Perhaps something in your settings.xml file?

**Comment by darnn** [comment]
Huh, apparently. Everything to do with splitterdistance looked like this in mine, and the errors continued popping up:
`    <SplitContainerMainSplitterDistance>339</SplitContainerMainSplitterDistance>`
`    <SplitContainer1SplitterDistance>1033</SplitContainer1SplitterDistance>`
`    <SplitContainerListViewAndTextSplitterDistance>230</SplitContainerListViewAndTextSplitterDistance>`
Once I pasted the values from the default settings.xml, i.e.
`    <SplitContainerMainSplitterDistance>638</SplitContainerMainSplitterDistance>`
`    <SplitContainer1SplitterDistance>1033</SplitContainer1SplitterDistance>`
`    <SplitContainerListViewAndTextSplitterDistance>492</SplitContainerListViewAndTextSplitterDistance>`
...the errors stopped. I don't know what to make of it, except to say that I did reach that situation organically, that is, I didn't change any of those values in settings.xml manually to end up like that. So it could happen again, theoretically, I just don't know how to do it intentionally.

**Comment by niksedk** [comment]
Tried with your settings - still could not re-create it... tried to fix it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by darnn** [comment]
It still happens with those settings in 3.6.1.0, but not in that beta, so I would say it's fixed.

**Comment by niksedk** [comment]
Cool, thx for reporting + testing :)
