### ISSUE TITLE
ASSA. Style Settings Minor Fixes

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5053]
I've had a problem with the some options in the ASSA. Styles settings.

When I mark one of the three options or all of them (see image 1) and reboot SE, I lose the configurations (see image 2).
I'm already using the version 3.6.1, but this was happening in older versions.

And, please, the third image shows the font size area part hidden every time I reboot SE.
Thank you very much!

![01_a](https://user-images.githubusercontent.com/64425752/118961640-e79d0080-b93a-11eb-9f49-697124b11f45.jpg)
![02_a](https://user-images.githubusercontent.com/64425752/118961673-f2579580-b93a-11eb-9099-167f8341cc38.jpg)

![03](https://user-images.githubusercontent.com/64425752/118962165-79a50900-b93b-11eb-80d0-d764e05d4bf1.jpg)

**Comment by niksedk** [comment]
Thx for the info :)
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
