### ISSUE TITLE
Unable to let OCR recognize italic c in binary image compare mode; always takes it as o

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#5057]
I have a trouble with OCR.
It always recognizes small italic "c" as small italic "o" no matter how many times registering small italic "c" as such and adjusting Max error % between 0.0 to 2.0.
Once registered, the letter "c" used in the dialog is recognized as such. However, when the next small italic "c" appears, OCR always takes it as small italic "o". So I have to do the procedure over and over again.
It seems no matter how many times "c" is registered, OCR does not care about this particular letter.
I tried this with my trained Latin.db. I also tried with blank db without any training.
I am using SE 3.6.1.

Here is a sample of the letter "c"
![ocr](https://user-images.githubusercontent.com/3875423/119208751-831aa680-bade-11eb-9d5b-d0faa6fdf936.png)
In this example, "c" is recognized as "o" in the word "scratching". So, I choose "o" and put correct "c" with italic option and push update.
![ocr2](https://user-images.githubusercontent.com/3875423/119208765-8d3ca500-bade-11eb-98dc-e53e7bfcf7ae.png)
Inside the Latin.db (brand new one) looks like this for letter "c"
![ocr3](https://user-images.githubusercontent.com/3875423/119208778-99c0fd80-bade-11eb-9417-e9ce07a3e638.png)
Also this is for letter "o"
![ocr4](https://user-images.githubusercontent.com/3875423/119208787-a0e80b80-bade-11eb-9b36-05a93554c66c.png)
Then, when I try to continue OCR, another wrong recognition happens. This time, "can" is recognized as "oan".
![ocr5](https://user-images.githubusercontent.com/3875423/119208795-a9404680-bade-11eb-8939-ebf39dcd23ca.png)
And this is where I have to do over and over again.
![ocr6](https://user-images.githubusercontent.com/3875423/119208802-afcebe00-bade-11eb-8b2d-78d8f848f3b3.png)

What is wrong with this OCR?

**Comment by niksedk** [comment]
I could not re-create this... if you attached the sub i could try again.

**Comment by taxen** [comment]
I am sorry to reply this late, but it took me some time to figure out what the sub came from and get prepared to report after I realized that I deleted the sub file.

Anyway, here is the HDMV PGS type sub file:
[tcm2.mks.gz](https://github.com/SubtitleEdit/subtitleedit/files/6595749/tcm2.mks.gz)

Here is my Latin OCR file only after trained once for the sub. I started importing the sub without any image DB.
(I think it is convenient for you to use this after erasing all italic small "c" and keep other letters, so you do not have to train other letters by yourself.)
[Latin.db.gz](https://github.com/SubtitleEdit/subtitleedit/files/6595779/Latin.db.gz)

SE setting to do the task looks like this:
![se-setiing](https://user-images.githubusercontent.com/3875423/120746055-6009e100-c539-11eb-9a8b-d8c91f48e422.png)

Result: (regarding only italic small "c")
Line 9: such <- suoh ... first, hit this word, and trained this "c" instead of wrongly recognized "o"
10 disgrace <- disgraoe ... the rest is the same; each word is recognized as the word on the right, and trained as the left word
58 stick <- stiok
203 Knocking <- Knooking
290 Stretoh <- Stretoh
400 Pencil <- Penoil
400 scratching <- soratching
423 can <- oan

So, while trained as many as 7 time, OCR still mistakes "can" with "oan"

**Comment by taxen** [comment]
Off the topic though, while I tested the sub once again, I hit on the following line.

In this case, I want to move back the focus and make OCR recognize two single quotes ('') as one double quote (").
For that, I proposed https://github.com/SubtitleEdit/subtitleedit/issues/171#issuecomment-525523972
I would like to hear how this proposal is handled after that.
Thank you.
