### ISSUE TITLE
Using "split line at cursor position" with subtitles without a timecode

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#5058]
Hi. 3.6.1 beta 4, but I think this hasn't been introduced recently.
If I use "import plain text" and generate timecodes where the gap is 0 and the duration is 0, I end up with a file where all the timecodes are "00:00:00,000 --> 00:00:00,000".
If I then use "split line at cursor position", what I get is this:
`597`
`00:00:00,000 --> -00:00:00,012`
`Hey, Owen, are there any other injustices`

`598`
`00:00:00,012 --> 00:00:00,000`
`in the world that I can strike about?`

Which is both undesirable in itself, and prompts SE to tell me the subtitle contains negative timecodes when I try to save it.

**Comment by niksedk** [comment]
Thx for the info :)
Does it work better now? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Works as intended over here now, yes.
