### ISSUE TITLE
Add converter for Narrator inside ( or [

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#506]
Before:
**(MALE)** Through the years,
I have been known by many names.

*After:*
**MALE:** Through the years,
I have been known by many names.

/cc @niksedk

**Comment by Betsy25** [comment]
I hope this becomes a "settable" option, otherwise it might be prone to quite a lot of false positives.

**Comment by niksedk** [comment]
Perhaps a plugin?

**Comment by ivandrofly** [comment]
:+1:
