### ISSUE TITLE
Add Support to "Non-Standard" PGS Subtitles

### ISSUE THREAD

**Issue by peter-qgd** [SubtitleEdit/subtitleedit#5066]
Hi, I'm wondering if it would be feasible to add support to "trivia" like subtitles. Example:

[Trivia Subtitle.zip](https://github.com/SubtitleEdit/subtitleedit/files/6542318/Trivia.Subtitle.zip)

Thanks.

**Comment by niksedk** [comment]
What are these? Just blank images?

**Comment by peter-qgd** [comment]
They look like that when opened with your program, but in fact, they are valid PGS subtitles. They work fine with common players, like PotPlayer:

![SAMPLE](https://user-images.githubusercontent.com/82705380/120081429-023a4c80-c094-11eb-9d50-3c28d1578780.png)

**Comment by niksedk** [comment]
OK, seems to be a problem with fading... is this better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by peter-qgd** [comment]
Yes, that works fine.

Thanks!

**Comment by niksedk** [comment]
Thanks for reporting and testing :)
