### ISSUE TITLE
UI Profiles - Minor Fixes

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5070]
Hello.
I've noted these size issues.
Could you take a look at them?
Thank you!

![1](https://user-images.githubusercontent.com/64425752/120118813-e5bd1380-c16a-11eb-9eb7-7cf83f3c8961.jpg)
![2](https://user-images.githubusercontent.com/64425752/120118817-eb1a5e00-c16a-11eb-92c7-377d21d4e06f.jpg)

**Comment by niksedk** [comment]
I can fix a little: 
![image](https://user-images.githubusercontent.com/1261331/120147845-9a951600-c1e7-11eb-9fc2-99cd32695bbe.png)

This string should be somewhat shorter:
<MinimumGapMilliseconds>Diferença mínima entre legendas (em milissegundos)</MinimumGapMilliseconds>
Any suggestions?

**Comment by Andrebavila** [comment]
Could it be this?
"Diferença mínima entre legendas (em ms)"
