### ISSUE TITLE
Remove HI Text - EXPORT

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5077]
I have two files. One is HI and other is not HI. The HI one is full of errors and other one is cleaned. Now, I want to get HI text from the bad file and merge them into the good non-HI file. It would be nice if there's an export option in  Remove HI page to export all the HI text with correct timecodes, so we can later merge it if we want to.

If there is a solution now, can someone tell me?

Thank you.

**Comment by niksedk** [comment]
This should probably have been a discussion: https://github.com/SubtitleEdit/subtitleedit/discussions

You could try opening the bad sub with HI and Edit -> Modify selection, select all lines with e.g. `[` (or what fits with your HI tags), click ok, use `inverse selection`, and delete the non HI now selected lines, and save.
Then Tool - Join subtitle... select the two subtitles (keep "subtitles already have correct time"), click "OK", then Tools - Sort by "start time"... and perhaps a renumber.

**Comment by uckthis** [comment]
@niksedk It worked. After modify selection, I just copied the selection and pasted in the good file and then Sort and Renumber.

Thank you.

**Comment by niksedk** [comment]
Nice, even smarter :)
