### ISSUE TITLE
Rich text box - text cursor can't be moved using arrows at start and end of line

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#5081]
3.6.1 next beta 52.
Create a new subtitle file. Insert a new subtitle. Type something. Try to use the left arrow to move the cursor. It won't move. Press home. Try to move the right arrow to move the cursor. It won't move. However, if moved to the middle of the string with the mouse, it will be possible to move it with the arrow keys as usual (until it reaches either the start or the end of the line).

**Comment by OmrSi** [comment]
You should mention that you're using RTL mode and writing a non-RTL language. :D

Before, it used to work for RTL languages in RTL mode, so if you select the whole text and try to move the cursor to the left, it didn't work, so I did this https://github.com/SubtitleEdit/subtitleedit/pull/4837

It seems that it's now casing other issues.

@niksedk I don't think I know how to fix this, at least not off the top of my head.

**Comment by darnn** [comment]
I suppose I should have! I'm just always in RTL mode, because I usually start off with an English file, to which I can add Unicode control characters ahead of time to display it properly in RTL mode (see https://github.com/SubtitleEdit/subtitleedit/issues/3205, if you recall). But I need the Hebrew I'm typing to always show up with the punctuation in the proper places, since I'm adding it on the fly.
