### ISSUE TITLE
Problem with the MPV Preview

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5084]
I've tested ASSA with some portable versions and this is happening.
I've tested with other videos and this trouble doesn't happen. Only with this video.
I don't know what it is.
Somebody could explain it?
![Error](https://user-images.githubusercontent.com/64425752/120389845-572fca00-c303-11eb-9e16-a731716fb700.jpg)

**Comment by niksedk** [comment]
Could you attach the subtitle file as a zip file?

**Comment by Andrebavila** [comment]
> Could you attach the subtitle file as a zip file?

[Test Subtitles.zip](https://github.com/SubtitleEdit/subtitleedit/files/6583702/Test.Subtitles.zip)

**Comment by niksedk** [comment]
OK, it plays like that in VLC too...

**Comment by uckthis** [comment]
Without going into much detail, just copy everything between [V4+ Styles] and  [Events] and paste in your subtitle file. If you're unhappy about the font size, where you see Arial Narrow, 28,  change 28 to a higher number to increase the font size and lower to... 


Time - Trailer.zip](https://github.com/SubtitleEdit/subtitleedit/files/6586390/Time.-.Trailer.zip)

**Comment by Andrebavila** [comment]
It's a bit out of alignment, but thank you!
Weird problem it is!

**Comment by uckthis** [comment]
You need aegisub to fix it. Open the ASS and video file. Click on the subtitle, then double click on the video screen. Wherever you double click, subtitle will be aligned there. You can also edit the style. Arial Narrow in this case and then apply it to all. I'm not fluent in aegisub, but I think YouTube will help you.

**Comment by LeonCheung** [comment]
Interesting, I did experience this problem today, even with the latest official release. @niksedk Here are both okay.ass and not_okay.ass.  FYI  :)

[comparison.zip](https://github.com/SubtitleEdit/subtitleedit/files/6588851/comparison.zip)

**Comment by niksedk** [comment]
SE does not show these style properties: ScaleX, ScaleY, Spacing and Angle
In recent beta versions these tags are kept in SE and not reset to defaults.

![image](https://user-images.githubusercontent.com/1261331/120590945-9d884480-c43b-11eb-9131-62060d13476c.png)

I guess it could be added to the UI, but SE would have trouble with the preview as dot net does not support "Spacing" as far as I know.

I don't know how much these styles are used?

**Comment by LeonCheung** [comment]
One example for these two could be:

![example](https://user-images.githubusercontent.com/494788/120593686-6f722700-c472-11eb-8077-249051554205.jpg)

Though we can also make it happen by tags like `\frx`, `\fry`, `\frz`, and manually add spaces between chars.  IMHO, it's more about compatibility?

**Comment by niksedk** [comment]
Ah, I see the bug... the beta was adding "scalex" in spacing + angle... 
Should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
Set spacing + angle to "0" to fix wrong styles.

![image](https://user-images.githubusercontent.com/1261331/120701433-1e365780-c4b3-11eb-9121-e0595c789316.png)

Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by Andrebavila** [comment]
I downloaded the new beta version, but everytime I go into the ass. settings and I try to get out of there, theses messages pops up.
I don't even need to change some configuration and this happens.
The second image pops up as soon as I click on the left button ("Anular") from the first image.

![Message](https://user-images.githubusercontent.com/64425752/120722709-9a766e00-c4a6-11eb-8622-65706d3c4452.jpg)

![Message 2](https://user-images.githubusercontent.com/64425752/120722946-18d31000-c4a7-11eb-9f64-69cfdadd461e.jpg)

**Comment by niksedk** [comment]
thx for testing :)
Should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

If you both have ffmpeg and mpv configured in SE, then mpv is used for the preview which supports spacing and angle (and just a better preview)

**Comment by LeonCheung** [comment]
Yes, mpv is my first choice. Thanks for adding the new features. :)

**Comment by Andrebavila** [comment]
Thank you very much.
The link for the beta version is not working.

**Comment by niksedk** [comment]
Ups, fixed: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
