### ISSUE TITLE
Publish to WinGet

### ISSUE THREAD

**Issue by felipecrs** [SubtitleEdit/subtitleedit#5089]
Hi, it would be awesome if we could install and get upgrades through winget: `winget install subtitleedit`. I was about to send a request for adding it to WinGet repo, but sadly it can't be packaged in a ZIP file.

Any chance you can upload the .exe directly to the GitHub releases?

https://github.com/microsoft/winget-pkgs

How to publish to WinGet on every new release: https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline

**Comment by Kronopt** [comment]
I bump this with the official microsoft docs on how to submit a package manifest to winget:
https://docs.microsoft.com/en-us/windows/package-manager/package/repository

**Comment by mtorressahli** [comment]
Hi, any updates on this? It would be awsome to have Subtitle Edit in the winget repositories

**Comment by niksedk** [comment]
I have no clue about this... any help appreciated.
Added something here: https://github.com/microsoft/winget-pkgs/pull/85278

**Comment by niksedk** [comment]
I do not know how to sign the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?

**Comment by felipecrs** [comment]
Send a message there, or open an issue, it seems not to be working.

**Comment by niksedk** [comment]
OK, I think I got it now... just required a reply with: @microsoft-github-policy-service agree company="Nikse"

**Comment by niksedk** [comment]
OK, only one PR approval away...

**Comment by niksedk** [comment]
`winget install Nikse.SubtitleEdit`  :)

**Comment by vedantmgoyal2009** [comment]
You can use https://github.com/marketplace/actions/winget-releaser to automatically deploy new releases to WinGet.

**Comment by niksedk** [comment]
> You can use https://github.com/marketplace/actions/winget-releaser to automatically deploy new releases to WinGet.
Would be nice with just a Github action, but I would need build + innosetup too... is both possible for free?

I used wingetcreate: https://github.com/microsoft/winget-create 
(SE auto-updates the manifest with new version numbers + hash)

**Comment by vedantmgoyal2009** [comment]
@niksedk Yes

**Comment by SpecterShell** [comment]
> Would be nice with just a Github action, but I would need build + innosetup too... is both possible for free?

This action doesn't build the project. Instead it just matches the assets in the release and use them to publish the new version to [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs). It will be triggered automatically when a new stable release is published.

**Comment by ckasprzak** [comment]
AH, issue. If you use winget to upgrade your manually installed client. That doesn't happen. Causing me confusion why it wasn't upgraded when I ran the upgrade via winget!

Open up Programs and Features from Control Panel and I see both versions installed!

**Comment by ckasprzak** [comment]
Cool, just wanted to make sure you were aware! :D
