### ISSUE TITLE
Breakline Minor error

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5099]
This is happenning on the version beta 3.6.1.72
"/" was replaced by "\N"

![Error](https://user-images.githubusercontent.com/64425752/120894841-d61d4f00-c5f0-11eb-9301-b92fb09e4a48.jpg)

**Comment by niksedk** [comment]
SE is now leaving the ASSA tags alone... like `\N` (hard line break).
The file probably has this "\N" character instead of a normal new line.

**Comment by Andrebavila** [comment]
Theres's a way to remove these "\N" and replace them by common line breaks?
Every ASSA file I have, they have this "\N".

**Comment by OmrSi** [comment]
@niksedk All line breaks in ASS files are stored that way AFAIK.
Even in SE, if you convert an Srt file to an ASS file, the line breaks become `\N`.

**Comment by OmrSi** [comment]
@niksedk In Aegisub, when you want a new line it just adds a `\N` to the line.
I think it's better when SE showed the lines on separate lines and then it converts those to `\N` upon saving.
