### ISSUE TITLE
Remove Dash on empty line

### ISSUE THREAD

**Issue by D00oo00M** [SubtitleEdit/subtitleedit#5106]
can somebody help me how to fix this in batch?
https://i.imgur.com/m5nKlZY.png

**Comment by darnn** [comment]
Replacing
\n-
with
\n
seems to do it for me, but ymmv. I'm not sure where there's a guide for SE's regex syntax.

Also, Pokemon cries look terrible in Hebrew, huh.

**Comment by OmrSi** [comment]
@darnn That would replace:
```
- Hey.
- Hey.
```
With:
```
- Hey.
 Hey.
```

You need to replace `\n-\s*\z` with nothing.

Regex syntax is the same as .NET regex syntax anywhere.

**Comment by D00oo00M** [comment]
> \n-\s*\z

can you tell me what to put i dont understand...

**Comment by darnn** [comment]
Ah, so it does... I really only know EditPad's regex syntax, which is mostly the same except some crucial areas.
D00oo00M:
![replace with nothing](https://user-images.githubusercontent.com/19672444/120923750-d1cc6100-c6d8-11eb-84db-49ae123debc9.png)

**Comment by OmrSi** [comment]
Batch convert -> Multiple replace -> add regex rule:
![image](https://user-images.githubusercontent.com/20923700/120923762-e14baa00-c6d8-11eb-89a6-ad14c8993d46.png)
