### ISSUE TITLE
Max. number of lines - Request

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5107]
Hello, guys!
Why the option "Max. number of lines" doesn't keep us from writing more lines than the choosen number?
And, for some reason, when we've writing just one line beyond the choosen number, it goes very very slow.
It would be amazing if the number on "Max. number of lines" kept us from writing another one.
The example below, I could write a third line, but not a fourth line.
I think that is kind of weird.

![Request](https://user-images.githubusercontent.com/64425752/120928034-7048ca00-c6b9-11eb-825c-7d9a73a1485b.jpg)

**Comment by niksedk** [comment]
Thx - should work now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

Also, you can press `Ctrl+Enter` to force a new line.
