### ISSUE TITLE
Waveform Issue

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5115]
Hello, guys.
I'd like to ask if you could take a look at that.
Whenever I click in one line (661) on the list view and drag another (662) in the waveform, this last one doens't change it's color to indicate it is right on the duration.
But, when I click on the line 662 (second image), the coloring change.
Look that it has the SAME duration when I was on the line 661.
I wanna know if I could drag a line on the wave form and the line change it's color, even though I'd be selecting another line.

![Error1](https://user-images.githubusercontent.com/64425752/121364752-71bf0000-c90e-11eb-8508-373cfb9ba217.jpg)

![Error2](https://user-images.githubusercontent.com/64425752/121364771-77b4e100-c90e-11eb-856c-04fd8e2a9dbb.jpg)

**Comment by niksedk** [comment]
Hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip ?

**Comment by Andrebavila** [comment]
Thank you!
It's amazing now!
