### ISSUE TITLE
Subtitle XML file shall not contain namespace prefix

### ISSUE THREAD

**Issue by altf78** [SubtitleEdit/subtitleedit#5116]
I'm trying to make a xml (D-Cinema SMPTE 2014), but when generating a packaged in Easydcp it gives me this error:

XML Document has default root namespace prefix: dcst. Default namespace should not use prefix for root or root namespace child nodes.

I sent the xml file generated with SubtileEdit to Easydcp support and the reply was:

The dcst namespace in your subtitle file shouldn't be there. Some validators/cinemas don't like them. I attached you a version of your subtitle without the namespace so you can see the differences for future reference.
![XML SAMPLE EASYDCP](https://user-images.githubusercontent.com/85633411/121383605-f36a5a00-c91d-11eb-863d-eeded42b07f5.JPG)

Worked fine with their file.

Thanks!

**Comment by niksedk** [comment]
Could you attach the file as a .zip file - would make things much easier...

**Comment by niksedk** [comment]
Tried to fix it in the latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
Is that better?

**Comment by altf78** [comment]
Hi, 

Here it is:
https://mab.to/7CxTAeT9y

I'll try the beta version.

Thanks!

**Comment by altf78** [comment]
Hi,

I've just tried the beta and worked perfectly.

Thanks!

**Comment by altf78** [comment]
Great tool!

I'm making a donation right now.

Thank you for your hard work!
