### ISSUE TITLE
How to disable spellcheck?

### ISSUE THREAD

**Issue by floaterest** [SubtitleEdit/subtitleedit#5119]
Every time I try to type a text in Japanese, SE blocks me and says that I need to install a dictionary. However, I cannot find a Japanese dictionary (a `.dic` and a `.aff` file) anywhere including [Open Office 3.x](http://extensions.services.openoffice.org/en/dictionaries). So I wonder if there is a way to disable spellcheck or where I can find a Japanese dictionary.

**Comment by niksedk** [comment]
Could you add a screenshot?

**Comment by niksedk** [comment]
Do you have live spell check enabled?

![image](https://user-images.githubusercontent.com/1261331/121475644-fae53e00-c9c5-11eb-8ff1-6f4747421edb.png)

**Comment by Floaterest** [comment]
> Could you add a screenshot?

![output](https://user-images.githubusercontent.com/56704092/121530772-bf4d7280-c9cb-11eb-90b6-2eb5c6180971.gif)

**Comment by Floaterest** [comment]
Every time I try to insert a Japanese character, the spellcheck dialog pops out and blocks me from typing.

**Comment by niksedk** [comment]
What OS are you using?

**Comment by Floaterest** [comment]
Linux, but I'll try if I can reproduce the same issue with Windows.

**Comment by Floaterest** [comment]
> Linux, but I'll try if I can reproduce the same issue with Windows.

The issue does not happen in Windows, even with live spell check enabled.
