### ISSUE TITLE
Issue with "Auto-translate"

### ISSUE THREAD

**Issue by saosaosaosaosao** [SubtitleEdit/subtitleedit#5120]
![1](https://user-images.githubusercontent.com/80646403/121478458-b5c70900-c9d1-11eb-9626-a2ab8f5ae61d.JPG)
![2](https://user-images.githubusercontent.com/80646403/121478464-b65f9f80-c9d1-11eb-9322-a04b79b73b01.JPG)
![3](https://user-images.githubusercontent.com/80646403/121478465-b6f83600-c9d1-11eb-994f-f4aa87c89eef.JPG)

[[SoftSubs][ED][16.91 KB][5ED15E6F].ass.zip](https://github.com/SubtitleEdit/subtitleedit/files/6628999/SoftSubs.ED.16.91.KB.5ED15E6F.ass.zip)

**Comment by vaclavmuller** [comment]
Automatic translation works fine for me. However, sometimes a bad translation language abbreviation is added to the subtitle file name. For example .pl instead of .cs
