### ISSUE TITLE
EBU STL Save options opens twice. 

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5122]
Whilst saving as STL file, the save option window opens twice. It started happening when I upgraded to latest version.  When I fill in the details and click okay, there's still another window of save options there.  I just hit cancel on it.

**Comment by niksedk** [comment]
Hm, I cannot re-create this... any hints?

**Comment by uckthis** [comment]
![Animation](https://user-images.githubusercontent.com/28671050/121784569-0f942280-cbce-11eb-963b-0fd04bc419c5.gif)
@niksedk

**Comment by niksedk** [comment]
Hm, still cannot re-create this... tried on different computers too.

**Comment by uckthis** [comment]
Then it's probably a me-issue, so let's forget about that. Sent a few STL files to some clients and nobody complained so far. I can close an extra window once in a while.
