### ISSUE TITLE
SCC Export with accentuation problem for PT-BR

### ISSUE THREAD

**Issue by EduGomesBR** [SubtitleEdit/subtitleedit#5124]
Hello, Nikolaj.
I am not able to export the SCC file correctly for my client.
The SE is removing letters that precede accented letters.

The image below shows the original srt file that was exported to SCC in UTF-8

![Print_SE_SRT_Original](https://user-images.githubusercontent.com/85190110/121585625-305f4b00-ca09-11eb-9c85-f9b6d4497c22.PNG)

In this image I used another software to import the SCC from Subtitle Edit and also imported the SCC that the client exported by MacCaption.
Note the accent...

![Print_EzTitle_SCC_Exported_By_SE](https://user-images.githubusercontent.com/85190110/121618398-0fb0e880-ca3d-11eb-8ace-1b59d16bfa9e.PNG)
![Print_EzTitle_SCC_Exported_By_MacCaption](https://user-images.githubusercontent.com/85190110/121618405-117aac00-ca3d-11eb-9f7e-5e46139fadfc.PNG)

In this image I used another software to import the SCC from Subtitle Edit and also imported the SCC that the client exported by MacCaption...

![Print_SubtitleNext_SCC_Exported_By_MacCaption](https://user-images.githubusercontent.com/85190110/121618479-366f1f00-ca3d-11eb-920a-81ea14baf256.PNG)
![Print_SubtitleNext_SCC_Exported_By_SE](https://user-images.githubusercontent.com/85190110/121618481-37a04c00-ca3d-11eb-87be-a34000e38aa3.PNG)

In this image I open the SCC with Subtitle Edit
The file exported by SE had the correct accent, and the file exported by MacCaption had duplicate letters...

![Print_SE_Import_SCC_FromSE_Exported](https://user-images.githubusercontent.com/85190110/121618677-92d23e80-ca3d-11eb-8af6-2cd5aba6f7eb.PNG)
![Print_SE_Import_SCC_FromMacCaption](https://user-images.githubusercontent.com/85190110/121618681-94036b80-ca3d-11eb-98ad-a17e3c3c4064.PNG)

I would be very grateful if you could help me.

Thanks.
EduGomes

[File SRT original and SCC by MacCaption.zip](https://github.com/SubtitleEdit/subtitleedit/files/6635281/File.SRT.original.and.SCC.by.MacCaption.zip)

**Comment by tarcisiooliveira** [comment]
There's a similar issue opened [here](https://github.com/SubtitleEdit/subtitleedit/issues/5108) and [here](https://github.com/mono/mono/issues/17029) but they are in Linux SO.
Maybe the problem is not in mono only.

**Comment by raphaelomoreira** [comment]
@EduGomesBR @tarcisiooliveira 
Hi!
Did you manage to get around this problem on SE?
