### ISSUE TITLE
Question : export nocr db

### ISSUE THREAD

**Issue by Harybo** [SubtitleEdit/subtitleedit#5127]
Hello, I am looking for how to export the db nocr to import it on another pc.

**Comment by niksedk** [comment]
Hi @Harybo,

Use the menu "Spell check" - "Get dictionaries". Click on "Open dictionaries folder":
![image](https://user-images.githubusercontent.com/1261331/122004487-c3570700-cdb4-11eb-9127-e6d6c221a2a5.png)

Go one folder up:
![image](https://user-images.githubusercontent.com/1261331/122004641-f13c4b80-cdb4-11eb-9f45-eb2c8aeddc0d.png)

In the "Ocr" folder, you can find your nocr dbs :)
![image](https://user-images.githubusercontent.com/1261331/122004774-1df06300-cdb5-11eb-99e3-8a50762d2331.png)

**Comment by Harybo** [comment]
thanks
