### ISSUE TITLE
Application Error: Found invalid data while decoding

### ISSUE THREAD

**Issue by legoladd** [SubtitleEdit/subtitleedit#5128]
When I try to add a Danish dictionary for OCR, I get this Thread Exception error every time.

![image](https://user-images.githubusercontent.com/42552742/122283122-38603480-ceba-11eb-9cfd-b87b13584c59.png)

**Comment by niksedk** [comment]
Could you try a newer version of SE?

**Comment by legoladd** [comment]
Yes!  I feel stupid for not trying that first. Thank you so much!

**Comment by niksedk** [comment]
np, cool it works now :)
