### ISSUE TITLE
Remove Line Breaks / Netflix QC

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5132]
For Netflix, line length is 42 and I have set to unbreak any lines under 43 chars, but SE doesn't unbreak those in most cases. When I click autobreak, it doesn't unbreak them. In Fix Common, Remove line breaks in short texts is selected and still it misses them.  Previously I'd catch them in Netflix QC and now it doesn't caches them either. 

[New Text Document.txt](https://github.com/SubtitleEdit/subtitleedit/files/6672685/New.Text.Document.txt)

Try it with SE and N-QC and you'll see none of them catches these errors.

**Comment by OmrSi** [comment]
Works fine with me, even with auto-break:

![image](https://user-images.githubusercontent.com/20923700/122460234-8cead900-cfba-11eb-8562-f91813c02536.png)

![image](https://user-images.githubusercontent.com/20923700/122460292-9c6a2200-cfba-11eb-82ba-9f14455632a2.png)

Can you attach your settings file?

**Comment by uckthis** [comment]
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/6672749/Settings.zip)

**Comment by uckthis** [comment]
It's been a headache. You do all the checks, send file and they send the file back with a list of unbroken lines. And you want to argue with them and then you check and they're right.

**Comment by OmrSi** [comment]
@uckthis There is a plugin just for this, it's called Lines Unbreaker.
I use it each time in my final checks, it works very well.

**Comment by uckthis** [comment]
@OmrSi Thank you, I didn't know about the plugin. But just tested it and it works great. Will use it in the future.
I hope the issue resolves within Common Errors, though.

**Comment by OmrSi** [comment]
@uckthis Ah, found the issue.
It's happened with me before, and I do not know why it happens.
In the settings file, you'll find two lines like this: `<MergeLinesShorterThan>42</MergeLinesShorterThan>`
Even though the UI shows that you've set it to 43, it's sometimes stored as 42 in the settings file, I had thought this was because of something I did in my settings file, but seems to be an issue from SE since it happened to you as well.

Right now, search for `<MergeLinesShorterThan>42</MergeLinesShorterThan>` in you settings file and change it to 43, it should work.
But we still have to find the cause of the issue which caused it to be stored like this.

**Comment by uckthis** [comment]
Yes, it worked. And it fixed N-QC too.

If we're getting this error for 42, it's possible that someone is getting for 39 or 52 or whatever.

**Comment by OmrSi** [comment]
@niksedk Maybe it from this line?
https://github.com/SubtitleEdit/subtitleedit/blob/efaf8dcfc88bfb0fe95f6a63de51218c7a3810ff/src/ui/Forms/Options/Settings.cs#L1970

It should be `gs.MergeLinesShorterThan = gs.SubtitleLineMaximumLength + 1;`

**Comment by OmrSi** [comment]
@uckthis Did you, at some point, try to make MergeLinesShorterThan bigger than SubtitleLineMaximumLength + 1?

**Comment by uckthis** [comment]
You're talking to a cow when you talk programming. lol.

I never had this issue before. I generally only do closed captioning for TV and they're pretty simple. It's when I took on some Netflix work that this was a requirement and it had issues. I never used this feature before, so don't know.

**Comment by niksedk** [comment]
Thx - seems I made of mess of things here: https://github.com/SubtitleEdit/subtitleedit/commit/33c76071f9782aed1785879861b27ce851964917

Hopefully fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

Also, @OmrSi: Is this correct: https://github.com/SubtitleEdit/subtitleedit/commit/73716711c60d0c6701ac9c2fc9e140ff1f8397d7 ?

**Comment by OmrSi** [comment]
@niksedk It should be, as far as I know.
I'm sure of it for Netflix and Amazon.
