### ISSUE TITLE
Snapping to shot changes - feature request

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5134]
Here is a picture of the tool I use for this..
![Untitled](https://user-images.githubusercontent.com/28671050/122509210-d3711f80-d01c-11eb-8ed5-99e4d31b5929.png)
Snap before shot change = 2 means that Endtime will automatically snap to the shot change minus 2 frames. I can change the value and say if put -5, end time will snap to shot change +5 frames. This feature will help with Netflix QC for Outcue is right on shot change, follow 2 frame rule.
Snap after shot change = 0, this means that Start time with snap to the shot change exactly. And of course I can change the value to +2 or +9 or -8 whatever.
I have set the snap area to 12 (Netflix), which means that the tool searches for shot changes in both directions 12 frames this side, 12 frames that side and then snaps to whatever, keeping the minimum duration b/w subtitles in mind. 
Once we have a basic tool, we can iron out the bugs and make it better. 
Who would like to see this feature besides me?

**Comment by PreetM07** [comment]
I second this feature.

**Comment by OmrSi** [comment]
On another note,  there are shortcuts for this right now. 
Snap start to scene change, extend start to scene change. 
Snap ens to scene change minus min. gap, extend end to scene change minus min. gap. 

Just set the min. gap to 2 frames in your frame rate and you're good to go.

I know this doesn't mean we don't need snapping, but it's helpful nonetheless.

**Comment by uckthis** [comment]
I tried the shortcuts, but first, if you do a whole file, it just keeps on loading and loading. And two: they don't adhere to 12 frames snap area and will snap to whatever is closest. I had captions that were snapped, reducing their length massively because the shot change was closest.
@OmrSi
