### ISSUE TITLE
ASSA Styles order issue

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5136]
Hello.
I've had this issue on ASSA. styles setting.
I've changed the styles order, but it doesn't saving.

![Error1](https://user-images.githubusercontent.com/64425752/122578566-5fd60f00-d02a-11eb-8efa-05ba1ecc6b1d.jpg)

![Error2](https://user-images.githubusercontent.com/64425752/122578583-64022c80-d02a-11eb-8642-fdd01ccc840e.jpg)

**Comment by niksedk** [comment]
thx for the info - tried to fix it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
Does that work for you?

Also, do check the new shortcut for text box - ASSA tag helper :)
(F1 goes to help, Enter/tab completes)

**Comment by Andrebavila** [comment]
Thanks for the fix! Now it works perfectly.
And I will try this new ASSA tag funcionality!
It will be very helpful!
