### ISSUE TITLE
Styles broken after loading saved file

### ISSUE THREAD

**Issue by Jwasik** [SubtitleEdit/subtitleedit#5137]
I saved my project in .ass. After opening it later i noticed that all non English (Polish letters) characters have been changed to random numbers, although i used UTF-8. This is minor issue, but i also lost all style formating. I still have my styles, but they doesnt apply to subtitles. Ex. i made style s1 which add blackbox under letters, but after loading saved file every subtitle looks like default default. Styles still exists, but they dont apply to text. Changing style also does nothing, like creating new style and changing to it.

**Comment by niksedk** [comment]
Hi @Jwasik: Could you try with latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

Does it still happen?
