### ISSUE TITLE
Error message while saving

### ISSUE THREAD

**Issue by peter-qgd** [SubtitleEdit/subtitleedit#5148]
Hello, I just noticed the next error message appears sometimes after hitting the "save" button:

![sub](https://user-images.githubusercontent.com/82705380/123026467-9a390680-d3b2-11eb-9c8f-089016f09be9.png)

I'm using v3.6.1.

Thanks.

**Comment by niksedk** [comment]
Hm, does anybody else get this?

I could put a retry around the saving... but perhaps it's your anti-virus provider?
Perhaps you can see more in a tool like this: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer ?

**Comment by niksedk** [comment]
I guess it means that the file is in use by some process... probably your anti-virus program.

In this beta I've tried to retry four times, with one second pause, to try to avoid conflicts with other programs "locking" the file: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by peter-qgd** [comment]
The issue isn't occurring anymore using that beta version, and it wasn't related to any "AV" program but to "PotPlayer". It had to do with me tweaking a subtitle while keeping it loaded to "PotPlayer"; but it only happened if the "saving" button was pressed very quickly a few consecutive times.

By the way, would it be possible to speed up the "show earlier" and "show later" buttons' response time? I mean, when I need to adjust the synchronization values, I have it configured with "500" ms steps most of the times and when I need to apply a few seconds more or less, it gets really slow to the program to process the timing changes. There will always be an annoying delay till the changes are applied, the quicker the buttons are pressed, the bigger are the delays.

Thanks.

**Comment by niksedk** [comment]
> 
> 
> The issue isn't occurring anymore using that beta version, and it wasn't related to any "AV" program but to "PotPlayer". It had to do with me tweaking a subtitle while keeping it loaded to "PotPlayer"; but it only happened if the "saving" button was pressed very quickly a few consecutive times.
> 

Yes, nothing to do with SE for sure :)

> By the way, would it be possible to speed up the "show earlier" and "show later" buttons' response time? I mean, when I need to adjust the synchronization values, I have it configured with "500" ms steps most of the times and when I need to apply a few seconds more or less, it gets really slow to the program to process the timing changes. There will always be an annoying delay till the changes are applied, the quicker the buttons are pressed, the bigger are the delays.
> 

It might be possible to save a few ms, but only updating visible items in the list view... but it will take a few hours to test/fix.

**Comment by niksedk** [comment]
Is "Show earlier" / "Show later" better in this beta version?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by peter-qgd** [comment]
Yes, it is much better now. : )

Thanks.

**Comment by niksedk** [comment]
Cool, thx for testing :)
