### ISSUE TITLE
export with sequenz image?

### ISSUE THREAD

**Issue by kkm** [SubtitleEdit/subtitleedit#5149]
like the example of https://github.com/mjuhasz/BDSup2Sub
VobSub export to XML with PNG image, I hope you can do it.

But https://github.com/mjuhasz/BDSup2Sub has bug with timestamp from PTS - Presentation Time Stamp.
thanks.

**Comment by niksedk** [comment]
You can right-click in the OCR window, and export to BDN/XML:
![image](https://user-images.githubusercontent.com/1261331/123089451-3e5c9500-d427-11eb-97f5-317f36d71928.png)

**Comment by kkm** [comment]
Ah I did found when you write faster.

But I use command line with
````
SubtitleEdit.exe /convert dvd_subtitle.sub BDN-XML /outputfolder:test /fps:23.976 /resolution:1920x1080
````

but this command line always used OCR, I dont want and how can I disabled and convert in command line without OCR?
