### ISSUE TITLE
Error changing shortcut

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5150]
Hello.
This is happenning when I've tried to change shortcuts.

Version: 3.6.1.163

![Error](https://user-images.githubusercontent.com/64425752/123296577-24858580-d4ed-11eb-8f98-38995746a068.jpg)

**Comment by niksedk** [comment]
Thx - should be fix now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip 

Was a bug introduced when I added customizable shortcuts to plugins.
