### ISSUE TITLE
Multiple minor size issues

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5151]
Language: Brazilian Portuguese

Settings
![Error 2](https://user-images.githubusercontent.com/64425752/123308020-8c41cd80-d4f9-11eb-9210-fb3904d8b3d7.jpg)

Settings -> Tools
![Error 3](https://user-images.githubusercontent.com/64425752/123308109-a7144200-d4f9-11eb-8921-5bb9a9addf8c.jpg)

ASSA helper
![Error 4](https://user-images.githubusercontent.com/64425752/123308179-bbf0d580-d4f9-11eb-864d-c6234ee5780c.jpg)

Export text
![Error 5](https://user-images.githubusercontent.com/64425752/123308220-c90dc480-d4f9-11eb-8683-063b7bc87105.jpg)

File -> Export **(All these are from the same size issue?)**

![Error 7](https://user-images.githubusercontent.com/64425752/123308548-2f92e280-d4fa-11eb-93c8-db2a294ae60f.jpg)

![Error 8](https://user-images.githubusercontent.com/64425752/123308619-43d6df80-d4fa-11eb-9694-f5e4437fc42d.jpg)

![Error 10](https://user-images.githubusercontent.com/64425752/123308653-4afded80-d4fa-11eb-9ad1-637845ff1746.jpg)

![Error 9](https://user-images.githubusercontent.com/64425752/123308631-46d1d000-d4fa-11eb-88fc-20ef13068c09.jpg)

There's more on the "Export" area, but I don't know if they are the same sizue isse.
By fixing one, it will fix the others?

**Comment by niksedk** [comment]
thx for the info :)
I've fixed some in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
The rest must be fixed by making texts in the language file shorter:  https://github.com/SubtitleEdit/subtitleedit/blob/master/src/ui/Languages/pt-BR.xml

"The DCinema/interop - is it really here" I could not re-create.

**Comment by niksedk** [comment]
>There's more on the "Export" area, but I don't know if they are the same sizue isse.
>By fixing one, it will fix the others?

Yes, fixing one should fix the others too.

**Comment by Andrebavila** [comment]
Thank you so much!
Found some more.

FAB Image Script
![Error3](https://user-images.githubusercontent.com/64425752/123960598-dd344480-d985-11eb-8129-cfa0c4a70e64.jpg)


Final Cut Pro XML advanced
![Error1](https://user-images.githubusercontent.com/64425752/123960215-6b5bfb00-d985-11eb-935e-2ad09db10f28.jpg)

Generate/Import Scene Changes
![Error2](https://user-images.githubusercontent.com/64425752/123960368-99d9d600-d985-11eb-9125-975e0b5be1f7.jpg)
