### ISSUE TITLE
EXPORT DVD STUDIO STL

### ISSUE THREAD

**Issue by nonofx** [SubtitleEdit/subtitleedit#5153]
Hi everyone,

i can't export in this format. SE crash (in attachment)
![crash_se_dvdstudio](https://user-images.githubusercontent.com/86473062/123417067-9de9aa80-d5b7-11eb-8443-8643fb35ecf5.PNG)

Anyone have a idea ?

**Comment by niksedk** [comment]
Thx for the info :)
Hopefully now fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by nonofx** [comment]
Hello Nicolaj,

Thank you very much, I can export images but not the .stl file.

Do you think it is normal ?

Best,

Bruno

**Comment by niksedk** [comment]
Hi @nonofx, thx for testing - I should have seen the stl file was missing too... anyway, new beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
How is that?
