### ISSUE TITLE
Import plain text not respecting split at end chars/line breaks.

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#5160]
So, this only happens occasionally, but when I'm importing dialogue, I sometimes get the following situation:
![import plain text](https://user-images.githubusercontent.com/19672444/123542429-4f244800-d752-11eb-954a-1e79bf88844b.png)

There's a line break after "Renegades." and it ends with a period, but "DESTINY: Let's roll." is still added to the same line.

**Comment by niksedk** [comment]
Could you attach the sub, thx?

**Comment by darnn** [comment]
Here:
[bunk'd 99.zip](https://github.com/SubtitleEdit/subtitleedit/files/6721690/bunk.d.99.zip)

This is the source txt file and the resulting srt file.

**Comment by niksedk** [comment]
Looks like this for me:
![image](https://user-images.githubusercontent.com/1261331/123551645-029d3480-d773-11eb-8bed-1dd0c5fdb76e.png)

**Comment by uckthis** [comment]
Happens to me about 10% of the time, so I just work with it.
