### ISSUE TITLE
[Feature Request] Where is font-size ???

### ISSUE THREAD

**Issue by jvsdr** [SubtitleEdit/subtitleedit#5165]
Hello???

Font name: ✔️
Font color: ✔️
But, font size: ❌

I need to add font-size via text editor, this is SO BORING!

![Screenshot_1](https://user-images.githubusercontent.com/10999602/123845203-49fa0100-d8ea-11eb-9813-4e5a9b0b6b13.png)

**Comment by niksedk** [comment]
Hallo, you can use format "Advanced Sub Station Alpha"... with ASSA you can even embed your own fonts.

**Comment by jvsdr** [comment]
> Hallo, you can use format "Advanced Sub Station Alpha"... with ASSA you can even embed your own fonts.

I'll try, but is not .srt... I was working with this format... Btw I think isn't hard to put this feature.... Thanks!
