### ISSUE TITLE
[Feature Request] Ability to OCR files using Google Drive API

### ISSUE THREAD

**Issue by minhngoc25a** [SubtitleEdit/subtitleedit#5167]
[This repo](https://github.com/Abu3safeer/image-ocr-google-docs-srt) is a Python script that enables users to use Google Drive API to OCR from images. You must have a Google drive platform credential to use the Google Drive API. [This Youtube video](https://www.youtube.com/watch?v=JXbL-PEoT4I) demonstrates exactly how to use the program step-by-step, but the method of acquiring API's client ID and secret in the video is outdated. The updated method can be found [here](https://www.youtube.com/watch?v=vt_PtZ6KYIE&t=0s).

My suggestion is to integrate this as an OCR method in addition to Terresact.

**Comment by cyzs233** [comment]
Somewhat related #5761 
![152559921-ae9ae069-689b-4526-8154-16700452b6d1](https://user-images.githubusercontent.com/25927091/179898803-9daf58ad-c937-4a2c-a424-1b8c4dffa31d.png)

It doesn't support Google Drive API directly, but now you can write the OCR tool yourself and assemble the result in subtitleedit via "Import plain text"

**Comment by niksedk** [comment]
A Google OCR method is available - or you can use export
