### ISSUE TITLE
Move text to next after cursor position

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5180]
Move text after cursor position to the next subtitle and go to next.
I never used this before, but looks like something I can get used to, so I tried it, but whenever I hit the shortcut (Ctrl+Num3), player goes to end of the file. 
Here:
![Animation](https://user-images.githubusercontent.com/28671050/124959743-f9df1500-e034-11eb-957a-b39da67eaeb8.gif)

I also noticed that this shortcut works properly if next subtitle has timecodes, so essentially I'm asking for a new shortcut without the go to next subtitle part, which seems to be causing the haywire.

Thank you.

**Comment by darnn** [comment]
The shortcut without the go to next subtitle part is "split line at cursor position" (under textbox in shortcuts).

**Comment by uckthis** [comment]
@darnn I know about that, but that creates a new subtitles and doesn't add text to the next subtitle after cursor.

**Comment by darnn** [comment]
Ah, I see what you're saying. I've just gotten used to move last word from first line down/move first word from next line up.
