### ISSUE TITLE
"Generate video with burned-in sub" crash

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5192]
This is happening when I click on "Generate video with burned-in sub"

Version: 3.6.1.223

![E3](https://user-images.githubusercontent.com/64425752/125152651-6422b300-e124-11eb-93b7-b23f1e46eaaf.jpg)

**Comment by niksedk** [comment]
Does that still occur in latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by Andrebavila** [comment]
It's fixed.
Thank you!
