### ISSUE TITLE
Editing text is extremely slow and laggy

### ISSUE THREAD

**Issue by maltium** [SubtitleEdit/subtitleedit#5197]
My use case is editing the text of subtitles for a 2 hour audio files. I notice that as the number of subtitles increase, editing text becomes slower and slower. By this I mean, pressing a key on my keyboard takes several 100s of milliseconds to update.

This is worse when editing subtitles towards the beginning of the file and gets better when editing those towards the end. Also, the longer the text of the particular subtitle, the slower the editing becomes.

Issue reproducible on a high-end PC.

Steps:

- Load subtitle file with around 1500 subtitles
- Edit text of subtitles towards the beginning of the file
- Observe the lag

**Comment by uckthis** [comment]
I raised this issue last year. The workaround is that make two subtitle files. Anything under 1000subs works smoothly. Make two files and then join them later. That's how I do it for file with 1000+ subtitles. Though, since I upgraded to 8th Gen i7, it's mostly smooth until 1500 subs.

**Comment by maltium** [comment]
Ah, I thought I couldn't be the only one. Yeah I'm doing the same thing and it's really an inconvenience. I'm on a 3900X but I don't think it matters much since the UI is running on a single thread.

Pretty sure the dev is doing something really inefficient for this to happen, like say, updating the whole UI on each keystroke.

**Comment by maltium** [comment]
I cloned the repo and after some debugging I identified the source of the lag. On each key press/release or subtitle selection a method called `AutoDetectGoogleLanguage` is called.

I believe the method is trying to perform some heuristics to infer the language code. Although I didn't delve deep into the code I'm not sure it makes sense to infer the language on each key stroke. For my purposes I just changed it to always return "en" as shown below.

![image](https://user-images.githubusercontent.com/4674453/125208501-1e382d00-e293-11eb-8ac6-a2d83bc04543.png)

Obviously this is not a feasible fix, but I hope this will help someone more familiar with the codebase to fix this.

**Comment by niksedk** [comment]
@maltium: thx for the info :)

I could only see the issue with about 20.000 subs with my 9 year old CoreI7 - but hopefully fixed for you in the above commit?

Beta also updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by maltium** [comment]
@niksedk I confirm that the issue is fixed with the beta build.

My subtitles contain much more text than the average movie subtitle, so probably that's why I got the issue with much less subtitles.

Thank you.

**Comment by niksedk** [comment]
Thx for reporting, debugging and testing :)
