### ISSUE TITLE
unable to translate from english to hindi

### ISSUE THREAD

**Issue by kshitijkapoor94** [SubtitleEdit/subtitleedit#5199]
Index was out of range. Must be non-negative and less than the size of the collection. 
Parameter name: Index

**Comment by niksedk** [comment]
Should hopefully bed fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip 
?

**Comment by kshitijkapoor94** [comment]
Yes, it is fixed. Thanks a ton. :D
