### ISSUE TITLE
[Suggestion] Better way to select line(s) via Waveform view.

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#52]
I've seen that there is a similar suggestion [here](https://github.com/SubtitleEdit/subtitleedit/issues/5). I just want to talk about my humble option:

I agree with this idea, and I believe it will work as a better workflow. Currently, I can see that we can double click on a wave clip to select that line actually, but it got three issues:
1. When double clicking, the first click will also change the position for current time indicator (that cyan line), which is usually unexpected;
2. We know that that time indicator can also be kept centered by enabling **Center** feature on the wave bar. However, it will work worse in this way: When click once, the whole wave was shifted, thus lead to the inaccurancy for position for the second click.
3. In any cases, double clicking will sometimes slightly  move the clips sometimes accidentally, which is also unwanted.

Considering the current <kbd>Ctrl / Shift / Alt</kbd> + <kbd>LMB</kbd> have already in use, my idea is: how about using <kbd>RMB</kbd> for wave selection? For example:
1. <kbd>Ctrl</kbd><kbd>RMB</kbd> to select single wave clip;
2. <kbd>Ctrl</kbd><kbd>RMB</kbd> and dragging to select successive lines;
3. <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>RMB</kbd> for append selection.
4. After selecting multiple lines, you can hold <kbd>Alt</kbd> to drag them; Context menu also works as usual for the single line that you right click on.

etc.

FYI. Thanks.! :)

**Comment by niksedk** [comment]
Today you can right `Ctrl+RMB` to toggle select + ctrl + move with LMB to move
