### ISSUE TITLE
[Feature request] Hotkey for in/out 12 frames before/after shot change

### ISSUE THREAD

**Issue by Fgrassano** [SubtitleEdit/subtitleedit#5200]
Hello! It would be great if we could add a shortcut to set the start/end time of a subtitle 12 frames before or after a shot change, which is what Netflix requires on timing to shot changes.
It could also work to just be able to move the video position in the same way.

Thank you!

**Comment by OmrSi** [comment]
Hey, @Fgrassano 
Netflix recently changed the `12 frames` rule to `half a second` rule.
There is already a shortcut in SE to seek half a second forward and backward.

**Comment by m0ck69** [comment]
@OmrSi out of curiosity, where is it, I can't find it.

**Comment by Fgrassano** [comment]
> @OmrSi out of curiosity, where is it, I can't find it.
Indeed, the only thing we can do is seek 1, 3, or 5s back or forward. Half a second would still be useful.

**Comment by Fgrassano** [comment]
> @OmrSi out of curiosity, where is it, I can't find it.

By the way, I just found it by chance, it's named "500 ms" instead of seconds, which makes total sense. Thanks a lot, @OmrSi !
