### ISSUE TITLE
Batch Convert: Remove Colour Formatting Only

### ISSUE THREAD

**Issue by DSGriff** [SubtitleEdit/subtitleedit#5201]
I have over 40 subtitle files that I need to convert and remove colour formatting. However, I would like to keep other formattings such as italics. I understand there's an option to remove a single type of formatting individually by right-clicking and picking under "Remove Formatting", but I can't seem to find this option when I'm doing batch convert. There is only "Remove Formatting Tags" which I assume removes all types of formatting. Am I missing something?
Thank you in advance.

![Individual](https://user-images.githubusercontent.com/72184444/125836815-479c4ea5-071c-4cdc-b4b5-a241972bf864.png)
![Batch](https://user-images.githubusercontent.com/72184444/125836811-c7ad39a4-7c89-47a3-a65f-ae0086ee23fe.png)

**Comment by TGreatOne** [comment]
You can't pick and choose what format type to keep (at least for now), I want do something similar, but to only keep the italics and remove everything else. Fingers crossed this will get added soon, as I'm grabbing subs from HBO Max with a script and they lose the italics during the exporting.
