### ISSUE TITLE
[Feature request] Resolution Resampler

### ISSUE THREAD

**Issue by Samo99** [SubtitleEdit/subtitleedit#5202]
Hello,

I wish that you add a Resolution Resampler option in batch convert for Sub Station Alpha file type.

This option existed in Aegisub which convert the file resolution to the resolution you input it in and correctly convert the font size and the position of the typesetting to it's new resolution.

take a look to this look for more info

https://aegi.vmoe.info/docs/3.0/Resolution_Resampler/

**Comment by niksedk** [comment]
How does this work for you?
![image](https://user-images.githubusercontent.com/1261331/126667503-151078a2-3d2f-4f4c-a2a0-ac42154a938d.png)

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by Samo99** [comment]
Thanks for the hard work.
I tried it and after pressing OK it gives me this error
![2](https://user-images.githubusercontent.com/12115578/126791014-2ffa794b-4ed3-44ef-9885-78a1279b482b.PNG)

will be your next step add this to the batch convert window?
like this 
![2](https://user-images.githubusercontent.com/12115578/126791637-e9a17f06-e5a5-48aa-ad6b-a40f84b82c5c.PNG)

**Comment by niksedk** [comment]
If we can get work working, it be possible to add to batch convert in a future version... but not soon.

Does this crash too? 
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by Samo99** [comment]
> If we can get work working, it be possible to add to batch convert in a future version... but not soon.
> 
> Does this crash too?
> https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

Unfortunately yes

![1](https://user-images.githubusercontent.com/12115578/126882251-dfb6b2c1-7c4d-4c1c-a94c-346885476bca.PNG)

**Comment by niksedk** [comment]
And... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip ?

**Comment by Samo99** [comment]
> And... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip ?

In this beta the error is gone but the calculation for the new positions still a little messy

**Comment by niksedk** [comment]
> 
> 
> > And... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip ?
> 
> In this beta the error is gone but the calculation of the new lines positions after resampling still a little messy

Could you go into details? Examples?
I need more info, if something should be fixed!

**Comment by Samo99** [comment]
> > > And... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip ?
> > 
> > 
> > In this beta the error is gone but the calculation of the new lines positions after resampling still a little messy
> 
> Could you go into details? Examples?
> I need more info, if something should be fixed!

OK i'll give you some examples, but first you need to know i unchecked the 4 boxes that says "keep the aspect ratio" and this is the result.

The first thing is the the vertical margin of the default style is 48 in the file resampled by Aegisub and still 28 in the one resampled by Subtitle edit like the original file.

And the position of one line is ( 757,280.8) in the file resampled by Aegisub and (504.667,187.2) resampled by Subtitle edit also like the original file.

It did great by resizing the fonts but everything else not that much. 

I'll give you the files to see by yourself which is better then explaining.

[subs.zip](https://github.com/SubtitleEdit/subtitleedit/files/6910623/subs.zip)
