### ISSUE TITLE
Can't type 0

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#5203]
Has anything changed in SE lately in terms of shortcuts and keys?
I haven't been using SE for a while. I have updated it to latest beta and noticed that I can't type 0 in text box.
I have a shortcut assigned to this key but it worked in previous versions of SE.

**Comment by darnn** [comment]
I really think this should be set this way by default, but open your settings.xml file and change
`    <AllowLetterShortcutsInTextBox>False</AllowLetterShortcutsInTextBox>`
to
`    <AllowLetterShortcutsInTextBox>True</AllowLetterShortcutsInTextBox>`

**Comment by m0ck69** [comment]
I doesn't work.
I just don't want shortcuts to work when I am in text box.
As I said, it was perfectly ok in previous version of SE, now it's a mess.

**Comment by niksedk** [comment]
> 
> 
> Has anything changed in SE lately in terms of shortcuts and keys?
> I haven't been using SE for a while. I have updated it to latest beta and noticed that I can't type 0 in text box.
> I have a shortcut assigned to this key but it worked in previous versions of SE.

I don't think anything has changed recently... what shortcut do you have with`0`? (so I have a chance to re-produce)

**Comment by m0ck69** [comment]
There are more examples of shortcuts that shouldn't be working in txt box.
For 0 I have "move end one frame forward (keep gap)
For 9 I have "move start one frame back (keep gap)
For Left I have "one frame back"
For Right i have "I frame forward"

The above are just examples that work everywhere (they shouldn't work in text box, and they didn't in older versions)
my settings file
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/6832707/Settings.zip)
