### ISSUE TITLE
live spell check doeasn't work

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#5206]
Live spell check does not work for me in the latest beta release.
I checked version SE361.zip and here live spell check works fine.

**Comment by niksedk** [comment]
Hm, works fine for me... is it still a problem in latest beta? What language? Perhaps a sample file?

Latest beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by m0ck69** [comment]
It doesn't work for latest beta either.
Polish language.
I try to edit a subtitle file with approx 1700 lines and the spell check does not work at all.


Subtitles
[example.zip](https://github.com/SubtitleEdit/subtitleedit/files/6872439/example.zip)

Just check the first line.
There is a sentence: A rose is red.
Róża jest czerwona. (OK)
Ruża jest czerwona. (a mistake)


Version SE361 works fine.
![ok](https://user-images.githubusercontent.com/46628545/126869139-d41a3110-482c-4cc4-bcd4-3a497919ec01.jpg)

Latest beta
![not ok](https://user-images.githubusercontent.com/46628545/126869152-30540253-eb36-44b6-b409-3890523bbf3c.jpg)

**Comment by niksedk** [comment]
Thx for the files :)
Should be fixed n latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
