### ISSUE TITLE
An Application error occurred in Subtitle Edit 3.6.1.0

### ISSUE THREAD

**Issue by devargas** [SubtitleEdit/subtitleedit#5207]
Good morning,

I downloaded the programme and when I start the section the error message appears and I have to inform the creator.
I send photo of the error that appears.

Kind regards,

Daniel Vargas
![photo_2021-07-19_10-31-52](https://user-images.githubusercontent.com/20271156/126168404-d14ffdec-3918-42d2-81bf-6be13f7c633c.jpg)

**Comment by niksedk** [comment]
Sorry, I cannot re-produces this.

When does this happen?
How did you install SE? 
Did you try both installer and portable version? 
What OS are you using?

**Comment by hamilaci** [comment]
I faced similar issue, pls look at the following picture saved as printscreen.
![application error report](https://user-images.githubusercontent.com/33340444/128360300-ee563318-a745-46ec-a2ee-db8f41a932dc.jpg)

**Comment by hamilaci** [comment]
I installed it as full (as recommended), I used the program for half a day, then the issue occurred several times during preparing a subtitle, using Win10.
Your support is appreciated.

**Comment by niksedk** [comment]
This should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by hamilaci** [comment]
Thanks for fixing the bug
BRLaszlo

 

    On Monday, 9 August 2021, 12:41:08 CEST, Nikolaj Olsson ***@***.***> wrote:  
 
 


Closed #5207.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
