### ISSUE TITLE
Subtitles export with black color

### ISSUE THREAD

**Issue by narcecl** [SubtitleEdit/subtitleedit#5209]
Hi, I'm editing a subtitle and exporting it as .ass file, but when I included into a movie, the text turns black
Can you guys help me out?

![imagen](https://user-images.githubusercontent.com/27156771/126218375-2e11b5f3-96c0-4303-a418-c72869dfe0df.png)
![imagen](https://user-images.githubusercontent.com/27156771/126218565-f0e742e8-157a-48aa-a31d-a5b4a810e6c0.png)

**Comment by OmrSi** [comment]
Any chance you can attach the file?

**Comment by narcecl** [comment]
> 
> 
> Any chance you can attach the file?

[Your Name [BD Remux 4K] [Lat-Jap].zip](https://github.com/SubtitleEdit/subtitleedit/files/6843824/Your.Name.BD.Remux.4K.Lat-Jap.zip)
this is the file that i get.

**Comment by narcecl** [comment]
Reading forums, I figure it out that the problem is not a with the subtitle file, but the player (VLC). It has troubles playing with UHD/4K movies.
