### ISSUE TITLE
merge lines with same text not identifying same text

### ISSUE THREAD

**Issue by davexnet** [SubtitleEdit/subtitleedit#5210]
I have an .ass subtitle (created using ffmpeg to extract a "timed text" tx3g sub)
[subs3.zip](https://github.com/SubtitleEdit/subtitleedit/files/6845023/subs3.zip)
, the sub contains almost all duplicated lines.
I can manually selected the group and choose merge these lines, but the the program automatic function is not working.
Thanks for looking at it

**Comment by niksedk** [comment]
Ah, the subtitles has not duration, so you will need to up the ms between lines to something like 3000 ms

![image](https://user-images.githubusercontent.com/1261331/128696600-21b4e84f-6e83-46d5-beae-ba412aa0f143.png)
