### ISSUE TITLE
Allow to hide Start time column in the List view.

### ISSUE THREAD

**Issue by ThomasLeigh** [SubtitleEdit/subtitleedit#5211]
Currently it is possible to hide End time column on the List View, but  oddly enough it cannot be done with the End time one. Could You please allow to hide it also?

**Comment by darnn** [comment]
I'm all for this as well. Currently I just have to shrink it down as much as I can (but not too much, since then it reverts to its full size on reopening SE). It would be much nicer to be able to hide it.
