### ISSUE TITLE
Separate colors for lines with errors and spell checking.

### ISSUE THREAD

**Issue by ThomasLeigh** [SubtitleEdit/subtitleedit#5212]
I use the app in the dark theme. In such a case lines with errors on the List view have light red background which makes reading harder due to the light color of the text. If, however, I change the error-line background color to the darker one - it will be applied also to the errors within the Text box - which has dark background (= dark mode), therefore, again, it’s hard to read, but this time within the Text box.

To solve this it would be enough to split colors for lines with errors (on the List view) and for error highlighting within the Text box. Would You be willing to do that? It would be of a great help.

**Comment by Kimpa-Tammas** [comment]
I have the same problem with the dark mode. I think it could be nice to change colors for each UI items, including color for grid lines in list.

**Comment by OmrSi** [comment]
Did you try changing the error color from the settings?

![image](https://user-images.githubusercontent.com/20923700/127159675-05224b35-20a3-4823-9c69-d0929d0ed1bd.png)

**Comment by niksedk** [comment]
@ThomasLeigh  / @Kimpa-Tammas: Could you attach some screenshots?

**Comment by ThomasLeigh** [comment]
@OmrSi @niksedk Yes, I’ve adjusted the error color within the app’s settings. In dark mode it looks like that: although the selected line with errors looks ok, errors in its content within the text field are harder to read.

![sshot-19](https://user-images.githubusercontent.com/26142231/127234153-7b925ff6-189a-43d3-ac09-76ea42cc24a4.png)
