### ISSUE TITLE
[REQUEST] Spell check - OCR .

### ISSUE THREAD

**Issue by slthelion** [SubtitleEdit/subtitleedit#5217]
Hello !

The "Text" area and "word not found" also the "Sugestions" area, the text size is very small.
Can you add a setting so I can change the font size ?

**Comment by niksedk** [comment]
You can right-click and use a larger font size:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/3ed5de5f-fc46-47c3-9bea-f67f85b3f33c)


![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/ff1f1f62-12d1-443d-83af-cba703d76712)
