### ISSUE TITLE
Add support for drtic (dtc) subtitles format

### ISSUE THREAD

**Issue by wesskywalker** [SubtitleEdit/subtitleedit#5218]
Feature request: add support for drtic subtitles (.dtc extension).

Sample subtitles:

- [a.cry.in.the.dark.(1988).eng.1cd.(93610).dtc](https://www.opensubtitles.org/en/download/drtic/93610)
- [miami.vice.brothers.keeper.(1984).eng.1cd.(4362446).dtc](https://www.opensubtitles.org/en/download/drtic/4362446)
- [psycho.(1960).spa.1cd.(32930).dtc](https://www.opensubtitles.org/es/download/drtic/32930)
- [grave.of.the.fireflies.(1988).ger.1cd.(111533).dtc](https://www.opensubtitles.org/de/download/drtic/111533)
- [the.life.of.david.gale.(2003).jpn.2cd.(151590).dtc](https://www.opensubtitles.org/ja/download/drtic/151590)
- [aladdin.(1992).bos.1cd.(4030548).dtc](https://www.opensubtitles.org/en/download/drtic/4030548)
- [the.matrix.(1999).fre.1cd.(114844).dtc](https://www.opensubtitles.org/fr/download/drtic/114844)

Further information can be found here:

- http://czdream.wz.cz/index_en.html
- http://czdream.wz.cz/about.html
- [Latest Version of Subtitle player enigma2](https://www.sat-universe.com/showthread.php?t=139246)
- [Advanced Subtitle Downloader](https://www.digital-kaos.co.uk/forums/showthread.php/27222-Advanced-Subtitle-Downloader)
- [Drtic - English Tutorial by Pingu v1.2](https://1lib.us/book/518436/d637a5)

**Comment by niksedk** [comment]
Thx for the info... so it's MicroDVD format with a new file extension + a header line?

Beta updated with support for this format: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
Does this work for you?

**Comment by wesskywalker** [comment]
Can't tell, I'm just an end user.

**Comment by niksedk** [comment]
OK, but do the .dtc files work for you?

**Comment by wesskywalker** [comment]
It works now. Thanks.
