### ISSUE TITLE
Can't type 0 v2

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#5219]
Hi.
My topic https://github.com/SubtitleEdit/subtitleedit/issues/5203 was closed so I thought the issue has been fixed.
I checked the latest beta and the problem still persists. Will it be fixed in official release?

**Comment by niksedk** [comment]
?

**Comment by m0ck69** [comment]
I have a shortcut "move end one frame forward (keep gap)" assigned to 0 key and I can't type 0 in text box.

**Comment by niksedk** [comment]
Hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by m0ck69** [comment]
yes, now it's working. thx

**Comment by LeonCheung** [comment]
Amazingly, it also fixed #5198.  :)
