### ISSUE TITLE
Add support for SubRip (.srt) format

### ISSUE THREAD

**Issue by wesskywalker** [SubtitleEdit/subtitleedit#5221]
Wonder if SubRip (.srt) format is supported? Couldn't find it on File - Save as...

[SRT subtitle format](https://www.programmersought.com/article/78322445267/)

**Comment by niksedk** [comment]
It's the top one in the combobox in the toolbar :)

In options - settings - subtitle format, you can add more formats to the top and set your preferred default format.

**Comment by niksedk** [comment]
SE is probably mainly used with SubRip :)

**Comment by wesskywalker** [comment]
SubRip happens to be the first option (top on the list) when Saving as, it's not sorted alphabetically like the rest of formats. Probably because it's the most important format? Didn't see it at first glance.

**Comment by niksedk** [comment]
> Probably because it's the most important format? 

Yes :)
