### ISSUE TITLE
Single line length

### ISSUE THREAD

**Issue by PMitsakis** [SubtitleEdit/subtitleedit#5226]
Unbreak lines shorter than value gets changed on its own. Openening the settings again, see that the value is changed to minus one of what you have chosen. Pressing cancel, though, it will function according to your desired value. Changing something else in the settings and not noticing it, it is set to minus one character of what you have chosen. Everytime, reopening the settings and pressing OK, the value will constantly be decreased. I am on beta version 278.

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by PMitsakis** [comment]
The link must be wrong, because it's the same build I already have.

**Comment by niksedk** [comment]
Ah, another bug for "Merge lines shorter than"... thx for the info :)

Hopefully fixed here:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by PMitsakis** [comment]
It is fixed. Thank you.
