### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PMitsakis** [SubtitleEdit/subtitleedit#5227]
I always encounter this error message, when I open the profiles' tab. It also appears when I click on certain profiles, like all Amazon profiles, Netflix and the default one.

![Σφάλμα](https://user-images.githubusercontent.com/85220137/127158046-c2648f23-4199-4520-a314-5ad8cae4e7ef.png)

**Comment by niksedk** [comment]
Fixed in latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by PMitsakis** [comment]
Yes, everything works fine now. Feel free to close it.
