### ISSUE TITLE
[Feature request] UI-friendly way of removing scene/shot changes

### ISSUE THREAD

**Issue by JDTR75** [SubtitleEdit/subtitleedit#5230]
Hello!

Is it possible to add a more friendly way of removing scene changes (false ones)? Like:
-Selecting a range in the waveform
-Right-click
-"Remove scene changes in selected range"

![image](https://user-images.githubusercontent.com/1891941/127339746-1010c3bb-2537-4485-916b-891c7ffb9f98.png)

Right now you have to go one by one, or go to the *.scenechanges file and remove several. But the latter is tricky because you don't have the visual aid.

Thanks!

**Comment by niksedk** [comment]
thx :)
Should now work in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by JDTR75** [comment]
Thank you so much! Works like a charm.
