### ISSUE TITLE
[Issue] Move to the next subtitle + .mpv - DELAY

### ISSUE THREAD

**Issue by nathaniel1977** [SubtitleEdit/subtitleedit#5238]
Hi,

I've noticed that when using mpv as the video player and moving from one subtitle to another, the subtitles (or the video?) are played (at least the sound) from about 0.5 second into the subtitle (the beginning of a subtitle is cut). Interestingly, on the waveform it looks as if the subtitle is being played from the very beginning, but on video it plays somewhere around 0.5 second into the subtitle.

**Comment by nathaniel1977** [comment]
No, I can confirm now. When moving from one subtitle to another on mpv, the subtitle isn't played from the beginning, but somewhere around 0.5 second after the beginning.

**Comment by niksedk** [comment]
I cannot re-create this... I and probably need some screenshots and how exactly do you move to next subtitle?

**Comment by nathaniel1977** [comment]
Hi,

 

I’ve got a key combination alt+down arrow to move to the next subtitle.

I’l’ try to make a video today. Might be that it’s my PC’s fault, but the problem retains in all versions I checked.

 

Best

 

W

**Comment by nathaniel1977** [comment]
Hi again,

 

It seems I can’t recreate this, either, on other video formats. The format that was affected in my case was .mpg

On .mp4 and others it works fine.

 

Best,

 

Wojciech

**Comment by niksedk** [comment]
OK, yes, it's very possible that some older container formats will have poor seeking.
