### ISSUE TITLE
Spell check window too small

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#5239]
Hello. Thank you very much for Subtitle Edit!

As the title says, the spell check window is too small by itself and this smallness in size becomes more apparent when the text to correct is too large and you need to scroll to find the error you are looking for. If only it could be adjusted.

Thank you.

**Comment by niksedk** [comment]
Could you supply some screenshots?

**Comment by lambdacore12** [comment]
Of course. Here, I know there is an error in the text but I need to scroll down to see it. It becomes tedious if there are multiple errors.

![Untitled](https://user-images.githubusercontent.com/37704802/128172582-4f726a08-2300-43d5-a5da-4c94e9a57888.png)
