### ISSUE TITLE
The ability to make the textbox scrollable

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#5240]
Hello. If I work with a very long text, I need to get to check all of the text quickly, but I can do that only by using the keyboard. If the textbox were scrollable, I could quickly check all lines, get to the end and go back to the beginning using the mousewheel, which would be very useful.

![Untitled](https://user-images.githubusercontent.com/37704802/128173084-5d0ac160-ff27-4a8c-8750-a5b738ccc864.png)

**Comment by darnn** [comment]
For what it's worth, it's already scrollable if you use linebreaks. Also this is neither here nor there but you can use ctrl+end/ctrl+home to quickly go back to the end or the start of the text (rather than just the specific line).

**Comment by LeonCheung** [comment]
Maybe this issue can be closed due to the latest improvement?
