### ISSUE TITLE
Import text with Do not Break after List enabled

### ISSUE THREAD

**Issue by ricerom** [SubtitleEdit/subtitleedit#5244]
When importing plain text with the "Use do not Break After List" option enabled (Language: Spanish), the text is converted into a single line. Example:

Hola, hola, hola.
Previamente en RuPaul's
Drag Race UK...
Y estarás montando
una noche de comedia...
...celebrando el tema del amor.

#Turns into:

Hola, hola, hola. Previamente en RuPaul's Drag Race UK... Y estarás
montando una noche de comedia... ...celebrando el tema del amor.

#For reference, with the option disabled it's like this:

Hola, hola, hola.

Previamente en RuPaul's
Drag Race UK...

Y estarás montando una
noche de comedia...

...celebrando el
tema del amor.

#Which is annoying, because all the breaks come after articles. Thank you very much for a great program!

**Comment by niksedk** [comment]
Hi @ricerom,

Hm, I cannot re-produce or entirely understand this issue... perhaps some screenshots would help?

**Comment by ricerom** [comment]
Of course, thank you very much for your attention. 

When I try to import plain text with this configuration:

![list off](https://user-images.githubusercontent.com/3451915/128738378-8eaa2da1-b16d-4e30-b970-d4345b2caa0a.PNG)

The result is this:

![list off import](https://user-images.githubusercontent.com/3451915/128738419-18d8cddb-7420-455f-aaf7-4409631badee.PNG)

I highlighted in yellow how most of the breaks come after particles (in English this would be "the", "a", "of", etc).

So I tried checking the do not break after list option, which as you know, when using auto break in a subtitle will break the line correctly avoiding breaks after said particles:

![list on](https://user-images.githubusercontent.com/3451915/128738696-29d55fe1-5061-41b0-8ebb-e4e6be37ba8e.PNG)

And the result is this:

![list on import](https://user-images.githubusercontent.com/3451915/128738751-d41abaa3-e6c5-4389-a687-ddfd32892406.PNG)

Suddenly, the entire text goes into a single sub. This is **only** an issue in Spanish. when importing plain text in English with the do not break after list option checked, the result is what you'd expect:

![list on import english](https://user-images.githubusercontent.com/3451915/128739599-7aaf1012-50e6-4d1e-9494-b439612cabe8.PNG)

Thank you for your patience, I hope I was able to explain it better this time.
