### ISSUE TITLE
Videos aren't playing even after installation of mpv lib

### ISSUE THREAD

**Issue by PraveenKochuveeedu** [SubtitleEdit/subtitleedit#5245]
![image](https://user-images.githubusercontent.com/88528496/128465192-5ed3079f-734f-47e5-b73d-dbeb27b34f41.png)
![image](https://user-images.githubusercontent.com/88528496/128465219-ff75a31b-8acc-4f4d-86e6-c58ca4e9e832.png)

**Comment by niksedk** [comment]
Hi @PraveenKochuveeedu,

What OS are you on?

What version of VLC did you install? You probably need to 64-bit version: https://get.videolan.org/vlc/3.0.16/win64/vlc-3.0.16-win64.exe

How did you install ffmpeg?

**Comment by PraveenKochuveeedu** [comment]
What OS are you on? windows 10

What version of VLC did you install? You probably need to 64-bit version:
https://get.videolan.org/vlc/3.0.16/win64/vlc-3.0.16-win64.exe yes this is
installed

How did you install ffmpeg? both direct on subtitle and form the github
linlk
