### ISSUE TITLE
Save/set default export format

### ISSUE THREAD

**Issue by gmariani** [SubtitleEdit/subtitleedit#5246]
I was converting a lot of ASS/SSA files to VTT. But to export to VTT i would have to scroll almost to the bottom for EVERY file i was converting. I would be SO nice to have it save the last used export format.

**Comment by niksedk** [comment]
In `Options - Settings - Subtitle formats` you can choose `- Auto -`, which should remember last used subtitle format - or you can just choose `VTT`. 

![image](https://user-images.githubusercontent.com/1261331/128691150-fbe58bfe-6828-44af-8f5f-b3c12b01b2fa.png)

It might only work in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

(If you're just converting a lot of subtitles from SSA/ASSA to VTT then `Tools - Batch convert` is probably much faster.)
