### ISSUE TITLE
Remove empty line not working

### ISSUE THREAD

**Issue by mataski** [SubtitleEdit/subtitleedit#5247]
Only removes one/first empty line?

![image](https://user-images.githubusercontent.com/62036912/128582734-e8a53082-93d4-4c0c-8902-f95a7dec28c4.png)
![image](https://user-images.githubusercontent.com/62036912/128582750-51335606-cf0c-44ff-9d6a-561661941bc7.png)

3.6.1

**Comment by niksedk** [comment]
Could you attach the subtitle file? (github supports .zip or .txt9

**Comment by mataski** [comment]
I deleted it after removing it manually. I tried doing that on random subtitle and it worked, so I don't know.

The subtitle in screenshot was made with VideoSubFinder and ABBYY FineReader PDF (hardcoded sub extracted into images) if that helps.
