### ISSUE TITLE
TTML subtitles are not detected/converted correctly

### ISSUE THREAD

**Issue by VXsz** [SubtitleEdit/subtitleedit#5253]
it probably is TTML but SubtitleEdit seems to mess up the timing when I open the file through it, TTML is in XML so I think SubtitleEdit is confusing XML's timecodes with the actual timings

Same issue has been reported here: https://github.com/yt-dlp/yt-dlp/issues/631

I attached an English subtitle if it could help (changed the extension so GitHub accept it, the original extension is `.ttml`)thank you ❤

[subtitle.en.txt](https://github.com/SubtitleEdit/subtitleedit/files/6962431/subtitle.en.txt)

**Comment by niksedk** [comment]
Thx for the info + sub file :)
The sample file is `Timed Text` in an mp4 container (might also be called ismt).

OK, I've some .ismt files where each segment starts from time code zero - and also some that do not... so now SE will only add time if a segment starts before last segment ends.
Also, `Merge lines with same text` is performed when reading the sub.

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip

**Comment by VXsz** [comment]
Working perfectly in my case, thank you so much as I wouldn't be able to do it alone (when I open the file it looks like binary lol) ❤❤
