### ISSUE TITLE
RIP subs from DVD dialog issue

### ISSUE THREAD

**Issue by freMea** [SubtitleEdit/subtitleedit#5255]
V3.6.1

Here is the dialog. It can not be resize. There is not horizontal scroll bar either. Hence, I can not see the full name of VOB files. Frustrating.
![image](https://user-images.githubusercontent.com/22337329/129051508-361b0541-5b3e-454d-934d-0d2b1d3bbec8.png)

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
3.6.2 should be out soon with above fix :)
