### ISSUE TITLE
Suggestion: Make the Spell checker window bigger. Currently it's far too small.

### ISSUE THREAD

**Issue by Mounter81** [SubtitleEdit/subtitleedit#5262]
Hello!

I use the Spell checker function very often, and my problem is, that it's window and the letter boxes are way too small to see correctly the words displayed. So it's very hard and time consuming sometimes to identify and find the right word e.g. when it comes to selecting from the suggestions it shows to replace a misspelled word. My suggestion is, to make the words better readable by increasing the size of the letters at minimum to double. I guess it can be also done by increasing the size of the whole Spell check window.
So, this is how it looks like form me:
[https://imgur.com/LzI0eB9](url)
As you can see it is very hard to spell out the correct words needed, with this small font size.
**Edit:** Specially when (that is in most of the cases) the subtitle file is over many thousand lines, when the correctable words can be also so many. 
I'm sure that many SubEdit users, who also use the Spell checker regularly, would agree to fix this inconvenience.

Please consider, and thank you!

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/129475952-b7527c62-ddc6-4d9b-82ff-87eb7033797c.png)

**Comment by niksedk** [comment]
It's kinda of the default font for winforms... you can perhaps change font size in windows?

**Comment by Mounter81** [comment]
Sorry, but I don't really think it1S a viable solution, to change the whole system's font size, because one application. This case with the Spell checker is rather special with the need of bigger font sizes, it only needed, when I'm translating and after checking the subtitles, but when I do, than it is a very important and with a subtitle lasting for 600-700 lines (and who knows how many thousand words) it could take up many time to exhaustively scan, with tightened, focusing eyes through the suggested words for each hit in the Spell checker, to select the proper word, because once you picked it wrong, there's no way back to find and correct it easily. I have thought if it's possible to change the fonts sizes in the main window of SubEdit, than it's also possible for the Spell checker sub window. Maybe I have guessed wrong, but are you saying, that there's no way you can make this change?

**Comment by niksedk** [comment]
Generally I don't think it a good idea to change the default font... but of course there are exceptions, like the SE text box.
Anyway, a little change is here:
![image](https://user-images.githubusercontent.com/1261331/129536938-aa8cc624-cf8c-4140-870c-a231fd1c8b0e.png)

You can also change `SystemSubtitleFontNameOverride` and `SystemSubtitleFontSizeOverride` in Settings.xml.

**Comment by Mounter81** [comment]
That looks like a change worth to try. Can you give a link to download, if you have already implemented?
And thank you! (Otherwise I will try to modify the settings).

**Comment by Mounter81** [comment]
What value I have to give for `<SystemSubtitleFontSizeOverride>1</SystemSubtitleFontSizeOverride>`? I have tried to change the zero value several times, like to 1, 2, 4 and 12, but none of it resulted any changes. So guess that's not the way to make it work, than can you describe the how to?
