### ISSUE TITLE
[Feature Request] Font Collector

### ISSUE THREAD

**Issue by JySzE** [SubtitleEdit/subtitleedit#5263]
In aegisub there was a option to scan a sub file for all declared fonts and confirm their availability and also the ability to fetch them.
![image](https://user-images.githubusercontent.com/70117278/129474585-9fc7e99e-1afc-489d-87c6-35d5bd9bd392.png)

I would love for this functionality added to SE and also for the possibility of improving what was missing from aegisub which is the ability to batch do this.

Allow us to batch collect fonts from large groups of sub files and have it automatically collect said fonts and create folders for each sub file with the called fonts inside.

**Comment by Samo99** [comment]
> In aegisub there was a option to scan a sub file for all declared fonts and confirm their availability and also the ability to fetch them.
> ![image](https://user-images.githubusercontent.com/70117278/129474585-9fc7e99e-1afc-489d-87c6-35d5bd9bd392.png)
> 
> I would love for this functionality added to SE and also for the possibility of improving what was missing from aegisub which is the ability to batch do this.
> 
> Allow us to batch collect fonts from large groups of sub files and have it automatically collect said fonts and create folders for each sub file with the called fonts inside.

Yeah that will be a good feature to have, but they need to watch out for couple of things:

1- In Aegisub it only collect the fonts the are in styles only so if you have line the uses a style but the translator uses the tag \Fn in this case Aegisub will collect the style of the line and not the font in the tag \Fn.

2- There need to be a warning system that warn the user in a txt file or a noew window about line that contain errors that may happened during the translation as you know the tag must be \Fn with capital F but sometimes they write it with small "f" or only "n" and that will cause an issue for the first point i wrote before.

3- Some time you find subtitles missing a style and in that case Aegisub will ignore that line so we need a warning that the line XX is missing a style and write i in a separate txt file or a window.

**Comment by niksedk** [comment]
Does this only use attached/inline fonts?
I mean, do you also want the font files from windows?

Would a "copy to folder" + a "syntax check" be enough?

Should probably be a plugin...

**Comment by JySzE** [comment]
> Yeah that will be a good feature to have, but they need to watch out for couple of things:
> 
> 1- In Aegisub will only collect the fonts that are in styles only so if you have line the uses a style but the translator uses the tag \Fn in this case Aegisub will collect the style of the line and not the font in the tag \Fn.
> 
> 2- There need to be a warning system that warn the user in a txt file or a new window about line that contain errors that may happened during the translation as you know the tag must be \Fn with capital F but sometimes they write it with small "f" or only "n" and that will cause an issue for the first point i wrote before.
> 
> 3- Some time you find subtitles missing a style and in that case Aegisub will ignore that line so we need a warning that the line XX is missing a style and write i in a separate txt file or a window.

1. Isn't a issue in a recent fork I use

2. I have always used fn not Fn.

The current fork I use for aegisub find fonts declared by /fn just fine but not when they are /Fn. If I batch replace all /Fn to /fn before this its not a problem. https://github.com/Ristellise/AegisubDC

3. Yeah I didnt even think of that.


> 
> 
> Does this only use attached/inline fonts?
> I mean, do you also want the font files from windows?


Yeah windows fonts would be needed to be grabbed also since I and others playback files on non windows devices. 

> Would a "copy to folder" + a "syntax check" be enough?
> 
> Should probably be a plugin...

If this achieves the ability to scan a sub file, find all fonts called (styled or not) and copy them to a folder of my choosing then yes.

But the real take away from this is that we really need this to be possible via batch. Trying to manually fetch fonts per episode of a large series is incredibly painful.

**Comment by Samo99** [comment]
> > Yeah that will be a good feature to have, but they need to watch out for couple of things:
> > 1- In Aegisub will only collect the fonts that are in styles only so if you have line the uses a style but the translator uses the tag \Fn in this case Aegisub will collect the style of the line and not the font in the tag \Fn.
> > 2- There need to be a warning system that warn the user in a txt file or a new window about line that contain errors that may happened during the translation as you know the tag must be \Fn with capital F but sometimes they write it with small "f" or only "n" and that will cause an issue for the first point i wrote before.
> > 3- Some time you find subtitles missing a style and in that case Aegisub will ignore that line so we need a warning that the line XX is missing a style and write i in a separate txt file or a window.
> 
> 1. Isn't a issue in a recent fork I use
> 2. I have always used fn not Fn.
> 
> The current fork I use for aegisub find fonts declared by /fn just fine but not when they are /Fn. If I batch replace all /Fn to /fn before this its not a problem. https://github.com/Ristellise/AegisubDC
> 
> 1. Yeah I didnt even think of that.
> 
> > Does this only use attached/inline fonts?
> > I mean, do you also want the font files from windows?
> 
> Yeah windows fonts would be needed to be grabbed also since I and others playback files on non windows devices.
> 
> > Would a "copy to folder" + a "syntax check" be enough?
> > Should probably be a plugin...
> 
> If this achieves the ability to scan a sub file, find all fonts called (styled or not) and copy them to a folder of my choosing then yes.
> 
> But the real take away from this is that we really need this to be possible via batch. Trying to manually fetch fonts per episode of a large series is incredibly painful.

Sorry for the mistake i meant the opposite about the \Fn and \fn, you are correct :)

**Comment by moi15moi** [comment]
If someone want to do it, but have no idea of all the detail of implementation, I did a script in python: https://github.com/moi15moi/FontCollector

**Comment by eddilara** [comment]
> > Yeah that will be a good feature to have, but they need to watch out for couple of things:
> > 1- In Aegisub will only collect the fonts that are in styles only so if you have line the uses a style but the translator uses the tag \Fn in this case Aegisub will collect the style of the line and not the font in the tag \Fn.
> > 2- There need to be a warning system that warn the user in a txt file or a new window about line that contain errors that may happened during the translation as you know the tag must be \Fn with capital F but sometimes they write it with small "f" or only "n" and that will cause an issue for the first point i wrote before.
> > 3- Some time you find subtitles missing a style and in that case Aegisub will ignore that line so we need a warning that the line XX is missing a style and write i in a separate txt file or a window.
> 
> 1. Isn't a issue in a recent fork I use
> 2. I have always used fn not Fn.
> 
> The current fork I use for aegisub find fonts declared by /fn just fine but not when they are /Fn. If I batch replace all /Fn to /fn before this its not a problem. https://github.com/Ristellise/AegisubDC
> 
> 3. Yeah I didnt even think of that.
> 
> > Does this only use attached/inline fonts?
> > I mean, do you also want the font files from windows?
> 
> Yeah windows fonts would be needed to be grabbed also since I and others playback files on non windows devices.
> 
> > Would a "copy to folder" + a "syntax check" be enough?
> > Should probably be a plugin...
> 
> If this achieves the ability to scan a sub file, find all fonts called (styled or not) and copy them to a folder of my choosing then yes.
> 
> But the real take away from this is that we really need this to be possible via batch. Trying to manually fetch fonts per episode of a large series is incredibly painful.

you should use the newer build of aegis
https://github.com/arch1t3cht/Aegisub

**Comment by JySzE** [comment]
Closing this as [FontCollector](https://github.com/moi15moi/FontCollector) Works better than I originally asked for, would be cool if SE could add this as a plugin inside its batch convert options.

Thanks

**Comment by csandman** [comment]
> Closing this as [FontCollector](https://github.com/moi15moi/FontCollector) Works better than I originally asked for, would be cool if SE could add this as a plugin inside its batch convert options.
> 
> 
> 
> Thanks 

Funny seeing you here, thanks for the recommendation!
