### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by 2Stereo** [SubtitleEdit/subtitleedit#5265]
Error Message: 
Tiedosto tai hakemisto on vioittunut ja lukukelvoton.

I would need to convert a DXFP file to .7z but it seems to be broken.

**Comment by niksedk** [comment]
What exactly do you click on? A screenshot would also be nice?
(SE do not support 7z files)

**Comment by 2Stereo** [comment]
![error](https://user-images.githubusercontent.com/89017718/129557791-9b26e40d-525a-48ef-93f8-c7405357683b.png)

This is what happens when I try to open the file in Subtitle Edit. So it doesn't depend on the program.
Yesterday, it worked just fine.

**Comment by 2Stereo** [comment]
The same message (the shorter one in Finnish) comes when I try to convert the file.

**Comment by niksedk** [comment]
Could you attach the file? 
It seems that SE cannot read the file from source...

**Comment by 2Stereo** [comment]
Github doesn't support DXFP files.
However,
I solved the problem by just downloading the previous version from my email! It seems to work fine.
Thank you for the comments.

**Comment by niksedk** [comment]
Github supports .txt or .zip

**Comment by 2Stereo** [comment]
Yes, but the problem is I cannot convert the file or rename it. I don't know how I could do that to upload the file.

**Comment by niksedk** [comment]
OK, if you find out how to upload or email the file to me, then please do so :)
