### ISSUE TITLE
Adda way to specify defaults for various formats

### ISSUE THREAD

**Issue by felagund** [SubtitleEdit/subtitleedit#5266]
One can set default style for ASS, but what about other formats? I use Subtitle Edit among other things to convert subtitles into the DCP xml format. Subtitle Edit defaults to values VAlign 8 and 14 for double-line subtitles, but I would prefer them to be 6 and 12. It is easy enough but tedious to change those afterall in a text editor editing the raw XML. Can the defaults be set somewhere (editing a file somewhere would be enough for me, but I have not found this documented at al if it is alrady possible)?

**Comment by niksedk** [comment]
You could try to edit "Settings.xml"... change the `DCinemaBottomMargin` value to `6` ...

**Comment by niksedk** [comment]
And probably in File - DCinema properties:
![image](https://user-images.githubusercontent.com/1261331/129773219-089e0ad2-3abb-4fe0-9989-c4e403db899d.png)


![image](https://user-images.githubusercontent.com/1261331/129773286-935b6896-bb01-45a9-a8b0-d94b4ae18c88.png)

**Comment by felagund** [comment]
Perfect, thank you, I have not realized this option appears when I save a file as DCP subtitle. Both ways go the same way. Thank you for fast reply!
