### ISSUE TITLE
Shortcuts issue

### ISSUE THREAD

**Issue by QuentinNetherwood** [SubtitleEdit/subtitleedit#5269]
Hi,

I tried to set these shortcuts I use a lot:

(Video) One second back CTRL+Left
(Video) One second forward CTRL+Right
(Video) 500 ms back CTRL+Shift+Left
(Video) 500 ms forward CTRL+Shift+Right

The problem is that Ctrl+Shift doesn't work with these settings, it's like I would press Ctrl+Left/Right only, the program always seeks one second when I try to seek 500 ms.

Could you please fix this?

Thank you.

**Comment by uckthis** [comment]
Just use ALT.  It's so much efficient. My play/pause is Alt+Space and 500ms is Alt+numpad0 and 10 frames is Alt+Left. Forwarding ¹ sec Alt+3. Anyway, ALT is my primary prefix for 80% of shortcuts because of its closeness to SPACE and play/pause.

**Comment by QuentinNetherwood** [comment]
> Just use ALT. It's so much efficient. My play/pause is Alt+Space and 500ms is Alt+numpad0 and 10 frames is Alt+Left. Forwarding ¹ sec Alt+3. Anyway, ALT is my primary prefix for 80% of shortcuts because of its closeness to SPACE and play/pause.

Now I use another shortcut for this, but I think this is just a bug so it should be fixed.

I use the same set of shortcuts in every subtitling tool I use (if shortcuts are changeable) and it's really disturbing to use different shortcuts for the same function.
