### ISSUE TITLE
Release 3.6.2 - Malwarebyte detects malware AI.4225176343

### ISSUE THREAD

**Issue by jed84** [SubtitleEdit/subtitleedit#5275]
Malwarebytes detects malware in the latest 3.6.2 release:
https://blog.malwarebytes.com/detections/malware-ai/

**Comment by niksedk** [comment]
Please report false positive to your anti-virus provider - thx :)

**Comment by niksedk** [comment]
Reported the issue here: https://forums.malwarebytes.com/topic/277972-false-positive/?tab=comments#comment-1476517
