### ISSUE TITLE
"Merge short lines" value crashing "batch convert"

### ISSUE THREAD

**Issue by fhtdtdj** [SubtitleEdit/subtitleedit#5277]
When changing the default value in "merge short lines" for an individual file via the tools menu, you can choose a value up to 10,000ms. But in the batch convert interface, the maximum is value is capped at 2,000ms so it creates an incompatibility between the two interfaces.
If you set it to 2,001 in the tools menu, and then try to open the batch convert interface, it simply crashes the whole program with the following error.

![2021-08-24 at 09 54 PM 001](https://user-images.githubusercontent.com/88416370/130682438-eed90d1f-7f3e-464f-bba0-097a74da549f.JPG)

**Comment by niksedk** [comment]
Thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
