### ISSUE TITLE
ASSA: Auto-set Resolution

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5284]
Hi, two cents for improving the workflow for ASSA, a highly resolution-based format:

When starting a project from scratch, or when loading a video file for the first time, the resolution in Properties should always be automatically set accordingly, instead of using 0 by default. 

And, when trying to load a video with a different resolution, it would be nice to have a pop-up as a reminder and ask for confirmation on whether the current resolution setting should be updated.

**Comment by LeonCheung** [comment]
@niksedk Hi, just noticed that when changing formats from SRT to ASSA, the resolution is still automatically changed, maybe it should be?

**Comment by niksedk** [comment]
> 
> 
> @niksedk Hi, just noticed that when changing formats from SRT to ASSA, the resolution isn't automatically updated, maybe it should be?

Yes, it should :)
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
Hmm, it seems working with a loaded subtitle, but when I open SE and start a project from scratch, it seems not working. Try this:

1. Open SE;
2. Load a video file;
3. Switch formats to ASSA, and check the resolution.

**Comment by LeonCheung** [comment]
Perfect, thx for the quick fix!
