### ISSUE TITLE
[Request] Shortcut to able and disable "Allow Overlap (when moving/resizing)"

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5287]
Is it possible add a shortcut to able and disable  "Allow Overlap (when moving/resizing)"?
Thank you.

![REQUEST](https://user-images.githubusercontent.com/64425752/131028304-05524d07-2fb8-4e2a-99c0-6c4ad14c3e18.jpg)

**Comment by niksedk** [comment]
For what scenario exactly?
When holding down "Shift" while moving the boarders overlapping is allowed.
