### ISSUE TITLE
Request: Multiple subtitle manipulation.

### ISSUE THREAD

**Issue by TomONeill** [SubtitleEdit/subtitleedit#529]
I wanted to sync a whole season of a series whose subtitles were off by 500 milliseconds and it seems to take some work to have to load every single subtitle and change the time codings.

Could you introduce a feature to change time codings for multiple subtitles?

**Comment by niksedk** [comment]
check Tools -> Batch convert... :)

**Comment by TomONeill** [comment]
Whoops. Sorry mate!
