### ISSUE TITLE
Subtitle Edit 3.6.1 , Subtitle Edit 3.6.2 errors

### ISSUE THREAD

**Issue by fiolek2000** [SubtitleEdit/subtitleedit#5290]
Sub Station Alpha ssa  format errors   
UTF-8 with BOM
Translator
Changing the size and color of subtitles and saving to ssa file 
There is no setting change made in the saved file  errors
older version Subtitle Edit good

Polski
Zmiana wielkości i koloru napisów  i zapis do pliku ssa  błąd
W zapisanym pliku nie ma zrobionej zmiany  błąd 
starsze wersję Subtitle Edit dobre

**Comment by niksedk** [comment]
Thx for the video - is the color working better in this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip ?

Also, try using "mpv" as video player - that should give a better preview.

**Comment by niksedk** [comment]
Just a small Windows hint... I always turn off "Hide extensions for known file types"
![image](https://user-images.githubusercontent.com/1261331/131213358-883dd3be-f69b-4f40-9237-a7f006200988.png)

**Comment by niksedk** [comment]
By the way, any reason for using "Sub Station Alpha" and not "Advanced Sub Station Alpha" ?

**Comment by fiolek2000** [comment]
By the way, any reason for using "Sub Station Alpha" and not "Advanced Sub Station Alpha" ?
change the size of subtitles
blocked
srt  not change the size of the subtitles
problem with the new save button
1  https://gofile.io/d/PYwDB3
2  https://gofile.io/d/Bb8eWg

**Comment by niksedk** [comment]
OK, thx for the videos :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

Also, unless you have a good reason, you should probably use the format "Advanced Sub Station Alpha" - about the same, but newer and better.

**Comment by fiolek2000** [comment]
Very good thank you 
https://gofile.io/d/F25ij2

**Comment by niksedk** [comment]
Nice we got it working :)

Still, I recommend to use "ASSA" instead of "SSA" and to use "mpv" inside SE for better preview:
![image](https://user-images.githubusercontent.com/1261331/131247384-86d2d2e4-5407-4915-810e-633ab7d99652.png)


![image](https://user-images.githubusercontent.com/1261331/131247393-23f39025-e31b-4af0-aeb0-3793f1af943c.png)
