### ISSUE TITLE
[Bug] Cannot adjust column width in subtitle view

### ISSUE THREAD

**Issue by JohnnySaliba** [SubtitleEdit/subtitleedit#5299]
Bug is present in v3.6.0, v3.6.1, v3.6.2. Bug is not present in v3.5.18.
Running Windows 10 1909 64-bit

https://user-images.githubusercontent.com/81323833/131376850-90d95672-4e31-4721-940a-cd0121738a0d.mp4

**Comment by niksedk** [comment]
Hm, it works fine for me... can you provide steps to re-create this?

Does this happen to anyone else?

**Comment by niksedk** [comment]
Ah, RTL mode?

**Comment by JohnnySaliba** [comment]
I'm currently running in RTL, but even when I uncheck it, I still get the same bug.

Here's a copy of my settings file, I just converted the extension to .txt for the upload.
[JohnnySaliba subtitle edit settings .txt](https://github.com/SubtitleEdit/subtitleedit/files/7078475/JohnnySaliba.subtitle.edit.settings.txt)

**Comment by JohnnySaliba** [comment]
I have in fact re-installed windows completely and I'm still facing the same bug. I've provided a speccy snapshot file as well as a dxdiag report, if they could be of any help. I'd be happy to provide any other info.

[JohnnySaliba DxDiag.txt](https://github.com/SubtitleEdit/subtitleedit/files/7109872/JohnnySaliba.DxDiag.txt)

[JohnnySaliba remove the .txt extension .speccy.txt](https://github.com/SubtitleEdit/subtitleedit/files/7109871/JohnnySaliba.remove.the.txt.extension.speccy.txt)
