### ISSUE TITLE
Removing formatting from the subtitles

### ISSUE THREAD

**Issue by Essam3152** [SubtitleEdit/subtitleedit#5301]
In some subtitles that are extracted from some streaming services, even after using "Remove all formatting" some formatting are still exists and the only way for removing them is by a regular expression using "Multiple replace", It will be great if you could add removing them to "Remove all formatting" and to "remove formatting tags" in batch convert. This is an example for that kind of subtitles.

[Vikings.S01E01.zip](https://github.com/SubtitleEdit/subtitleedit/files/7082795/Vikings.S01E01.zip)

<img width="721" alt="11" src="https://user-images.githubusercontent.com/87686356/131478304-07b3c70e-2fb4-4416-964a-70028da1c3d5.png">

<img width="931" alt="12" src="https://user-images.githubusercontent.com/87686356/131478331-6e8cd6a5-56f4-4eac-bc26-38fbf20c6d0e.png">

<img width="764" alt="13" src="https://user-images.githubusercontent.com/87686356/131478366-37b0a43e-fad2-4107-98e7-a215ad34c752.png">

<img width="728" alt="14" src="https://user-images.githubusercontent.com/87686356/131478388-b9efd954-dcc6-4539-902e-a1e564c01c9f.png">

**Comment by niksedk** [comment]
OK, tried to fix the issue in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by Essam3152** [comment]
Thank you so much, the latest beta fixed the problem.
