### ISSUE TITLE
[small fix, follow up with potential UI issues] Windows 10 DPI adjustment is missing in the application manifest 

### ISSUE THREAD

**Issue by eladkarako** [SubtitleEdit/subtitleedit#5303]
hi, just started using SubtitleEdit,  
my screen DPI is set to 150% through ease-of-access (Windows 10),  
programs that are not having a manifest entry for DPI awareness are getting blurred when some elements and controls (and text) are resized to fit the current screen resolution (however every controls is accurately located as if it was, in a screen that has DPI set to normal 100%).  (you can open image in new tab for full resolution):  
![1](https://user-images.githubusercontent.com/415238/131706658-02b366d7-c612-4429-9d2e-90308ea1779b.png)
![1_1](https://user-images.githubusercontent.com/415238/131706675-50e0bd49-4aab-43d2-aa10-d99fbc6f50d0.png)

I didn't compiled the binary exe again, instead I've used the `Microsoft (R) Manifest Tool` in [this tool I've made](https://github.com/eladkarako/manifest) to overwrite the embedded manifest with this one:  

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity name="Microsoft.Windows.Common-Controls"
        version="6.0.0.0" publicKeyToken="6595b64144ccf1df"
        type="win32" processorArchitecture="*" language="*"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
     <windowsSettings> <dpiAware      xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>                     </windowsSettings>
     <windowsSettings> <dpiAwareness  xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness> </windowsSettings>
     <windowsSettings> <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>                   </windowsSettings>
  </application>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"></supportedOS>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"></supportedOS>
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS>
    </application>
  </compatibility>
</assembly>

```

the important stuff is:  

```xml
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
     <windowsSettings> <dpiAware      xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>                     </windowsSettings>
     <windowsSettings> <dpiAwareness  xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness> </windowsSettings>
 </application>
```

it did get the text crisp and clean, in my 150% DPI without any blurring! (you can open image in new tab for full resolution)  

![2](https://user-images.githubusercontent.com/415238/131706711-013d2a1d-0f5b-4c6a-9b5e-915109cafb27.png)
![2_2](https://user-images.githubusercontent.com/415238/131706729-75d2771c-3841-4fa3-b343-1ee39a3cfd4d.png)

<hr/>

![1vs2__a](https://user-images.githubusercontent.com/415238/131707332-9ca2368d-fe56-4622-870d-cc57cc29c7f7.png)

<hr/>

I did noticed that the controls are "leaking" into one another,  
in Visual Studio this is solved by setting 'anchor' on buttons, labels and such,  
to "help" them get resize correctly,  
for example buttons placed near the bottom of the page anchored at the bottom will grow up, and to the sides.

**Comment by niksedk** [comment]
A PR is welcome :)

SE has about 180 forms...

**Comment by eladkarako** [comment]
@niksedk  
manifest editing is not really the problem,  
re-designing the UI to scale correctly with <code>PerMonitorV2</code> of <code>dpiAwareness</code> is.  
I already applied some fixes for visually impaired users <sup><a href="https://docs.microsoft.com/en-us/visualstudio/ide/reference/resources-for-designing-accessible-applications?view=vs-2019">Resources for designing accessible applications</a>/<a href="https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/walkthrough-creating-an-accessible-windows-based-application?view=netframeworkdesktop-4.8">Creating an Accessible Windows-based Application</a></sup>  
importing the project to my VS08 was quite a pain.  
task might be more suitable for dev.s whom are already familiar with the project.  
if there are none, you might as well close this one with wontfix tag :|

**Comment by eladkarako** [comment]
Edit:  
possibly great news.  

I had excellent results using additional entry in the manifest called <code>gdiScaling</code> (along with existing <code>dpiAwareness</code> and <code>dpiAware</code>),  
the gdiScaling is not a drop-in solution (sometimes mdi forms acts weird due to being scaled into their containing parents and get cropped), each app acts different, the rule of thumb is to try an look if it looks fine,  
and it does! no blur as far as I can see.

<details><summary>this is the manifest, and a patched exe you may drop locally and see it yourselves</summary>

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<!-- August 2021. Elad Karako. --> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
<!-- a segment for identity, optional (you don't need it, unless you know you need it). --> 
<!-- 
  <assemblyIdentity 
      name="Microsoft.Windows.Shell.calc" 
      processorArchitecture="x86" 
      version="5.1.0.0" 
      type="win32"/> 
  <description>Windows Calc</description> 
--> 
<!-- apply the current Windows-theme to the controls of the application, if possible. --> 
  <dependency> 
    <dependentAssembly> 
      <assemblyIdentity name="Microsoft.Windows.Common-Controls" 
        version="6.0.0.0" publicKeyToken="6595b64144ccf1df" 
        type="win32" processorArchitecture="*" language="*"></assemblyIdentity> 
    </dependentAssembly> 
  </dependency> 
  <application xmlns="urn:schemas-microsoft-com:asm.v3"> 
     <windowsSettings>  <dpiAware                           xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>                        </windowsSettings>     <!-- https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#dpiaware --> 
<!-- <windowsSettings>  <printerDriverIsolation             xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</printerDriverIsolation>             </windowsSettings> --> <!-- for apps that initiate printing (such as Chrome, MS-word, Paint.Net), calls printer driver from within a sandbox so if it crashes it does not really effects the app itself or the OS, not really needed. unspecified value tend to work fine in either classic or shared manner (shared is default win W7+).  https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#printerdriverisolation --> 
<!-- <windowsSettings>  <highResolutionScrollingAware       xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</highResolutionScrollingAware>       </windowsSettings> --> <!-- ** DO NOT USE!!!!!! **  crashes apps in W10! should increase resolution in mouses that supports high DPI (1200 and such) but even putting it in the manifest - regardless of value WILL CRASH THE APP in W10+!!!  manually look in entries in: https://docs.microsoft.com/en-us/windows/win32/sbscs/manifest-file-schema#code-try-0 --> 
<!-- <windowsSettings>  <ultraHighResolutionScrollingAware  xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</ultraHighResolutionScrollingAware>  </windowsSettings> --> <!-- ** DO NOT USE!!!!!! **  crashes apps in W10! should increase resolution in mouses that supports (very) high DPI (1200 and such) but even putting it in the manifest - regardless of value WILL CRASH THE APP in W10+!!!  manually look in entries in: https://docs.microsoft.com/en-us/windows/win32/sbscs/manifest-file-schema#code-try-0 --> 
     <windowsSettings>  <dpiAwareness                       xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness>    </windowsSettings>     <!-- improve 'dpiAware', can specify both. should help scale up legacy apps. https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#dpiawareness --> 
     <windowsSettings>  <longPathAware                      xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>                      </windowsSettings>     <!-- windows 10 only, override MAX_PATH (260) character limit in various windows APIs to allow 32k characters, paths are getting weird, although it is handled by the windows API so legacy apps should be fine too.   also requires registry editing since this feature is disabled in the OS by default. not a good idea to turn this ON since you might take files in sd-card or portable HD elsewhere and won't be able to copy or read stuff.   https://docs.microsoft.com/en-gb/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later  --> 
     <windowsSettings>  <gdiScaling                         xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling>                         </windowsSettings>     <!-- makes graphic programs such as ones that takes screenshots have bad functionality with larger-DPI (ease of access), since it also enlarges the controls in sub containers, and somtimes breaks the UI, for non-graphic-programs it might improve scale text and standard controls in apps, prevents blur. useful if you are using non 100% DPI for example in 'ease-of-access'. https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#gdiscaling --> 
<!-- <windowsSettings>  <activeCodePage                     xmlns="http://schemas.microsoft.com/SMI/2019/WindowsSettings">UTF-8</activeCodePage>                    </windowsSettings> --> <!-- changes a legacy program from default Windows code page 1252 to UTF-8, might mess-up display.     https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#activecodepage   https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page#code-try-1   --> 
     <windowsSettings>  <heapType                           xmlns="http://schemas.microsoft.com/SMI/2020/WindowsSettings">SegmentHeap</heapType>                    </windowsSettings>     <!-- change windows heap API to use a modern implementation, windows 10+ only.                         https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#heaptype                                                                                                          --> 
  </application> 
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <security> 
      <requestedPrivileges> 
        <requestedExecutionLevel level="asInvoker"            uiAccess="false" /> 
   <!-- <requestedExecutionLevel level="highestAvailable"     uiAccess="false" /> --> <!-- best to avoid! use either 'asInvoker' or 'requireAdministrator'.  if you want to use this one - essentially the cases are bi-functional application, use if program can manage most of its functionality (such read only protected files/registry) but can work in write mode when user has admin right, dialog for admin details will be shown on demans, and if not providing admin-auth the specific action fails but the app can still run. --> 
   <!-- <requestedExecutionLevel level="requireAdministrator" uiAccess="false" /> --> <!-- use if program requires admin-access. standard user gets credentials dialog for admin-account-details. won't start the app without some admin-auth-details. --> 
      </requestedPrivileges> 
    </security> 
  </trustInfo> 
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> <!-- without it, apps will run in windows vista compatibility in windows 7.   https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#compatibility --> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS> <!-- Windows 10/11  /  Windows Server 2016/2019  --> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"></supportedOS> <!-- Windows 8.1    /  Windows Server 2012 R2    --> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS> <!-- Windows 8      /  Windows Server 2012       --> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"></supportedOS> <!-- Windows 7      /  Windows Server 2008 R2    --> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS> <!-- Windows Vista  /  Windows Server 2008       --> 
    </application> 
  </compatibility> 
</assembly> 
 ```
patched using my manifest tool (see above).  

patched exe.
[SubtitleEdit.exe.zip](https://github.com/rust-lang/cargo/files/7108762/SubtitleEdit.exe.zip)

</details>

as far as I can see only thing needed is to slightly modify the manifest for the project,  
and re-build, or patch existing build with mt.exe (ms manifest tool), long file support is optional. 

click for 1080p

![Untitled1](https://user-images.githubusercontent.com/415238/132071570-f21b0917-5aa9-4ce1-a350-bb60f2cf3e02.png)  

![Untitled2](https://user-images.githubusercontent.com/415238/132071576-d56afef3-bb12-4193-9438-9a3927d47a1b.png)

compare it with original screenshots (before the manifest patching) and it looks pretty much the same, just the text is more clear.

**Comment by nkh0472** [comment]
A great PR. I once proposed an incomplete solution #4778, but it didn't solve the problem well.

**Comment by eladkarako** [comment]
@nkh0472  
I'll try to rebuild with some of the switches in https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element for .Net 4.8,  
my guess is that it just sums into project manifest, but I'm not 100% sure, some of the notes specify that automatic anchor for controls might be improved.  
  
Also, the manifest triggers DPI-awareness functions that works best in newer builds of Windows 10. I'm a using really new preview of 21H2 from uupdump so my results might be better looking than in older W10 builds (W7 has not support for DPI awareness at all anyway).. :|

**Comment by nkh0472** [comment]
I tested your patched file in https://github.com/SubtitleEdit/subtitleedit/issues/5303#issuecomment-912848651, and found a funny bug.
![20210905215558](https://user-images.githubusercontent.com/67589323/132129616-536ef6e2-e6a1-4a11-84cf-9a2f42bdb8eb.png)
The video playback panel appears in the wrong place, and its original position is a black window. After some tests, it is determined that the original program does not have this bug.

Anyway, the font has become clearer:)

**Comment by eladkarako** [comment]
> I tested your patched file and found a funny bug.

darn it!  
hey, would you please see if this one just dpi-awareness, but no GDI has it too?..
[SubtitleEdit.zip](https://github.com/SubtitleEdit/subtitleedit/files/7112399/SubtitleEdit.zip)

**Comment by nkh0472** [comment]
> would you mind to please see if this one w/ just dpi-awareness, but no GDI has it too?..
> (yes, controls will look ugly.. but I find it still usable and the text is so sharp..)

This time it looks all fine. Actually, I like this one more than the last one.

Last time, it seems that only the text display in the list has been significantly improved. But this time, the text of the menu bar (red marked) is obviously better looking. However, the problem I describe in https://github.com/SubtitleEdit/subtitleedit/pull/4778#issuecomment-772398574 still remains.

> At that time, the situation might be similar to: When I enable “Override High DPI scaling behavior” and set the Scaling Behavior to “Application”, "Windows won’t force such programs to use DPI virtualization", the font of the program is clear. However, the text in some places will be truncated because it is beyond the display range, such as "UTF-8 with BO……" at the top of the window.

![20210906164536](https://user-images.githubusercontent.com/67589323/132188157-c250fb3f-6d37-426d-92c7-8956d39da603.png)

place | Original | Last one | This one
--- | --- | --- | ---
Menu bar (Red mark) | unsharp | maybe sharper? | sharpest
List (Orange mark) | unsharp | sharper | sharpest
ComboBox (Green mark) | unsharp & complete | sharper & copmlete | sharpest & incomplete

Problems like the text display of ComboBox may really need to be adjusted one by one in the code.

**Comment by eladkarako** [comment]
that means there is no easy fix :(
quality wise, `dpiAwareness` with `PerMonitorV2` should render best results.  
`gdiScaling` can be avoided entirely.  
I guess there is 'no escape' from walking through the hundred and some forms to make sure they are all anchored correctly. should take ages.  
probably same amount of time it would take to rebuild everything using hybrid app and nodejs...

**Comment by eladkarako** [comment]
I've made a patch for the newest version <a href="https://github.com/SubtitleEdit/subtitleedit/releases/tag/3.6.5">3.6.5</a>.

<details><summary>original (no change)</summary>
https://github.com/SubtitleEdit/subtitleedit/files/8498902/SubtitleEdit__original.exe.zip  

<img src="https://user-images.githubusercontent.com/415238/163653276-85603ad6-1c98-4588-bd91-3e46150813d7.png"/>  

```xml
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity version="1.0.0.0" name="SubtitleEdit.app"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel level="asInvoker" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- Windows 7 -->
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" />

      <!-- Windows 8 -->
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" />

      <!-- Windows 8.1 -->
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" />

      <!-- Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
    </application>
  </compatibility>
</assembly>

```

</details>

<details><summary>with maximum DPI Awareness support (sharpest result, but controls will leak one into another sometimes)</summary>

https://github.com/SubtitleEdit/subtitleedit/files/8498904/SubtitleEdit__patched_with_dpi_awareness_.no_gdi_scalling.exe.zip  

<img src="https://user-images.githubusercontent.com/415238/163653395-551f0572-396a-434f-b4f8-286a639d3167.png" />

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
  <dependency optional="yes"> 
    <dependentAssembly> 
      <assemblyIdentity name="Microsoft.Windows.Common-Controls" 
        version="6.0.0.0" publicKeyToken="6595b64144ccf1df" 
        type="win32" processorArchitecture="*" language="*" /> 
    </dependentAssembly> 
  </dependency> 
  <application xmlns="urn:schemas-microsoft-com:asm.v3"> 
     <windowsSettings> <dpiAware      xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>                     </windowsSettings> 
     <windowsSettings> <dpiAwareness  xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness> </windowsSettings> 
     <windowsSettings> <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>                   </windowsSettings> 
     <windowsSettings> <gdiScaling    xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling>                      </windowsSettings> 
     <windowsSettings> <heapType      xmlns="http://schemas.microsoft.com/SMI/2020/WindowsSettings">SegmentHeap</heapType>                 </windowsSettings> 
  </application> 
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <security> 
      <requestedPrivileges> 
        <requestedExecutionLevel level="asInvoker" uiAccess="false" /> 
      </requestedPrivileges> 
    </security> 
  </trustInfo> 
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" /> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" /> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" /> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" /> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}" /> 
    </application> 
  </compatibility> 
</assembly> 
 
```

</details>

<details><summary>reduced DPI Awareness using GDI scaling flag (not as sharp but still sharper and keeps all the controls in their places, best solution)</summary>  

https://github.com/SubtitleEdit/subtitleedit/files/8498905/SubtitleEdit__patched_with_dpi_awareness_and_gdi_scalling.exe.zip  

<img src="https://user-images.githubusercontent.com/415238/163653475-1cfe2fde-fb29-4aba-b4c4-c9671cea51d2.png"/>

</details>

download, extract, no rename is needed, you can keep all 3 in the same folder and run each time what you want

<img src="https://user-images.githubusercontent.com/415238/163653541-02d4a080-ff42-4eb9-9767-95630120426d.png" />

<hr/>

<details><summary>bonus.</summary>

two patched exe will also support Windows new segmented heap and long-path awareness.

if you need it, use this registry patch and reboot

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001
```

it will not effect explorer (open/save dialog), just file/folder APIs from the program itself.

https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later

not effects any other program.

</details>

**Comment by eladkarako** [comment]
v3.6.6 portable <sup><a href="https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SE366.zip">1</a></sup>

<a href="https://github.com/SubtitleEdit/subtitleedit/files/8799739/SE366_manifest_patched.zip">SE366_manifest_patched.zip (4MB)
<img width="500" src="https://user-images.githubusercontent.com/415238/171032025-cac49432-2688-4df2-a5d3-dca98ceeba5b.png"/>
</a>

**Comment by eladkarako** [comment]
[subtitleedit_v3.6.7_manifest_patched.zip](https://github.com/SubtitleEdit/subtitleedit/files/9332109/subtitleedit_v3.6.7_manifest_patched.zip) for [v3.6.7](https://github.com/SubtitleEdit/subtitleedit/releases/tag/3.6.7)

<img width="700" alt="2022-08-13_231652" src="https://user-images.githubusercontent.com/415238/184509494-8803452f-1f2d-400f-b103-40e3f7fd9d07.png">

- if you've installed `SubtitleEdit-3.6.7-Setup.exe`, copy those files to `C:\Program Files\Subtitle Edit`:
```txt
SubtitleEdit__for_the_setup__original.exe
SubtitleEdit__for_the_setup__patched_with_dpi_awareness_and_gdi_scalling.exe
SubtitleEdit__for_the_setup__patched_with_dpi_awareness_(no_gdi_scalling).exe
```

- if you're using the portable version, copy those files to where you've placed the program:
```txt
SubtitleEdit__portable__original.exe
SubtitleEdit__portable__patched_with_dpi_awareness_and_gdi_scalling.exe
SubtitleEdit__portable__patched_with_dpi_awareness_(no_gdi_scalling).exe
```

- no need to rename anything, just launch either as is. you can close the program and launch another if you wish to check if it looks better.

**Comment by nkh0472** [comment]
Just out of curiosity: are the `SubtitleEdit.exe` for the portable and setup versions different? Where is the difference?

**Comment by eladkarako** [comment]
regardless, for the chance it is or will change in the future I test both.

**Comment by niksedk** [comment]
> Just out of curiosity: are the `SubtitleEdit.exe` for the portable and setup versions different? Where is the difference?

They should be exactly the same.
