### ISSUE TITLE
Shift + Right-click on a single subtitle throws error

### ISSUE THREAD

**Issue by darbor87** [SubtitleEdit/subtitleedit#5304]
When using the new feature to Shift + Right-click to select a range of subtitles, an error is thrown if you perform this command if you only select one subtitle (as if you were using the Ctrl + Right-click behavior instead). Selecting a subtitle first, _then_ Shift + Right-clicking another subtitle will select the entire range, as expected. Here is a screenshot of the error that appears.
https://i.imgur.com/E3BlHkX.png

**Comment by niksedk** [comment]
Good finding :)

Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Perfect, thx for the quick fix!
