### ISSUE TITLE
Error Message when generating burn-in sub

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5305]
This is with the latest beta:
![generate](https://user-images.githubusercontent.com/494788/131710743-11066d1a-21ea-4077-bd67-17663d408134.jpg)

**Comment by niksedk** [comment]
thx - is the latest beta better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
