### ISSUE TITLE
Regex doesn't work in Find/Replace

### ISSUE THREAD

**Issue by psonnosp** [SubtitleEdit/subtitleedit#5306]
Pardon my maybe stupid regex but it has worked fine up until today when I updated to the latest version, think I've skipped a few versions so this might be old.

Using
[Aa]-[Aa]|[Bb]-[Bb]|[Cc]-[Cc]|[Dd]-[Dd]|[Ee]-[Ee]|[Ff]-[Ff]|[Gg]-[Gg]|[Hh]-[Hh]|[Ii]-[Ii]|[Jj]-[Jj]|[Kk]-[Kk]|[Ll]-[Ll]|[Mm]-[Mm]|[Nn]-[Nn]|[Oo]-[Oo]|[Pp]-[Pp]|[Qq]-[Qq]|[Rr]-[Rr]|[Ss]-[Ss]|[Tt]-[Tt]|[Uu]-[Uu]|[Vv]-[Vv]|[Ww]-[Ww]|[Xx]-[Xx]|[Yy]-[Yy]|[Zz]-[Zz]|[Åå]-[Åå]|[Ää]-[Ää]|[Öö]-[Öö]|

to find texts like

- I-I-I need you two to hear me out!
- Oh, shut up!

results in no hits in 'Find' and 'Replace', but it work as intended in 'Multiple replace' so something seems fishy.

**Comment by OmrSi** [comment]
Does it end with `[Öö]|` or is there something after it?
