### ISSUE TITLE
Characters getting overwritten with italics in nOCR database

### ISSUE THREAD

**Issue by sderrow** [SubtitleEdit/subtitleedit#5307]
I started a new nOCR language file in order to have a clean slate, and I built it up with a few different subtitles (all Latin characters). Then, when doing an nOCR on a specific SUP subtitle, I noticed that some characters were being identified as italicized when they were not supposed to be. So I went in and updated / added a better match. But when I re-ran the nOCR from the start of the SUP, the characters were italicized again.

Investigating further, I clicked on "Edit" to look at the actual letter images and corresponding text that was stored for the entire database (not just the specific line of the specific SUP). For "A", it had multiple entries where the image was not italicized but the "Is italic" checkbox was checked. I went through an unchecked that box for the images that were not actually italicized, thinking that would fix the problem. However, after running the same SUP file through from the start, the changes I had just made to the database for the letter "A" had been reverted.

Is it possible that when running nOCR, the program will overwrite the "Is italics" flag for entries in the database, even though the database should only change when adding a new image? As far as I can tell, when the program sees a mix of what it thinks are italicized and normal characters in a single word, it'll force all of the characters to be one or the other. My hunch is that when the program changes those specific instances of those characters from normal to italics, it also erroneously changes the underlying database entry, which impacts future subtitle readings.

**Comment by niksedk** [comment]
Hi @sderrow,

What version of SE are you using?
I've tried to re-create this without any luck... could you possibly tell me how to re-create this?

**Comment by sderrow** [comment]
Hi @niksedk,

I'm using SE 3.6.1 on Windows 10.

See [this zip file here](https://github.com/SubtitleEdit/subtitleedit/files/7264179/SE-Issue-5307.zip) for a couple items that might help you recreate the issue. If you load the .nocr and open the .mks in nOCR mode, you can "edit" the language and see that one of the small "a" entries is not italicized even though the "is italic" box is checked (for me, it's the second "a" entry). When I uncheck the box and then run nOCR on any number of lines of the .mks, and then recheck the database, the second "a" entry has reverted to being marked "is italic".

Let me know if you have trouble, and thanks in advance for looking into it!

**Comment by chorca** [comment]
Commenting here as I'm having the exact same problem running 4.0.3 on Manjaro Linux.

Going through a subtitle file I see individual letters within a word being detected as italics. After correcting them via the "Check other..." menu and identifying that they incorrectly have the italic checkbox checked, I uncheck it and hit OK, then OK again to return to the main screen. I double-check that the change has occurred using the Edit button under the nOCR frame, and then restart the OCR on that subtitle line. As soon as it is scanned, I stop the operation.
Now here, if I go into the Edit button in the nOCR frame, it will show the letter correctly, without italic selected. However, if i double-click on the subtitle line that's been mis-recognized, and click Check Other..., it shows italic selected.

Some examples:
Via Check Other...
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1699703/33d91741-5a52-438c-8c03-02e0da088287)
Via Edit button
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1699703/9cca4ac5-3906-45ca-a9d9-2c0eae0dd79f)
