### ISSUE TITLE
No progress shown when generating burn-in sub

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5308]
I mean, is there a progress bar under "Please wait..."? I mean I can tell it's working indeed in the background, but I cannot tell how long I have to wait, especially for long videos:

![progress](https://user-images.githubusercontent.com/494788/131777265-0690c55d-b2dc-4670-b57c-54fa224018f3.jpg)

Oh one more thing, is it possible to expose customized parameters like kbps and resolution, and perhaps more? Sometimes we need to generate the target file with a specified size or resolution. It would be really useful if possible. ❤️

**Comment by niksedk** [comment]
So you don't get this?
![image](https://user-images.githubusercontent.com/1261331/131789597-f8b73e93-a59f-4a35-a7e8-e038bea43025.png)

With a non-ASSA file you get this:
![image](https://user-images.githubusercontent.com/1261331/131789733-d7155159-22d3-45e7-936a-2fdc027d741e.png)

**Comment by LeonCheung** [comment]
Yes, no "Time remaining" and green bar either way.  However, this is what's shown with build 30:

![build 30](https://user-images.githubusercontent.com/494788/131791256-1949f682-08da-46cc-b991-d3bdb9efb5df.jpg)

**Comment by keumala** [comment]
![SE error](https://user-images.githubusercontent.com/89993189/131875441-81a918bd-a51f-4c52-9b57-761d4a6af811.JPG)

**Comment by keumala** [comment]
can you help me with this?

**Comment by niksedk** [comment]
@LeonCheung / @keumala: How is latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

(Should be around build 44)

**Comment by LeonCheung** [comment]
@niksedk For the problem I mentioned, I'm afraid it's the same... build 45

**Comment by niksedk** [comment]
OK, could you try with latest beta:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
And attach the file `error_log.txt` here?

**Comment by LeonCheung** [comment]
Here it is, after generating a 7-minute video:
[error_log.zip](https://github.com/SubtitleEdit/subtitleedit/files/7104396/error_log.zip)

**Comment by niksedk** [comment]
Thx for testing Leon - could you test again:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

You can now get a log if you press F2... could you attach that log?

**Comment by LeonCheung** [comment]
Hi, sure. Here it is. :)
[F2 error log.zip](https://github.com/SubtitleEdit/subtitleedit/files/7105252/F2.error.log.zip)

**Comment by niksedk** [comment]
Thx again - it was the mp4 info that has a few missing fields... hopefully better now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Wow, it's working now, many thx!

**Comment by LeonCheung** [comment]
Btw, I can see that you are adding more parameters there for SRT, that's really cool! And hoping to see it available for ASSA soon.  🥂   And it would be perfect to support ABR besides CRF, which can be useful to keep the file size as close to the original video as possible.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
Settings should now actually work - for both ASSA and other sub formats.

ABR seems a lot of work for... nothing but a target file size... requires two encoding passes... any other benefits?
Perhaps target file size can be estimated with CRF?

**Comment by LeonCheung** [comment]
That's the point. I know CRF would be the better choice in most cases other than this. I think it would be cool to estimate with an ideal CRF automatically based on the file size needed. For me, normally, I have to try many times to get an expected CRF value for a given project, which is painful. And, it seems we can only set  CRF as integers for now? I mean, say, CRF=10 can be quite different from CRF = 10.2 assuming the target size is the requirement we have to follow (say, required by some clients).

**Comment by niksedk** [comment]
Beta updated with new settings + ABR: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

How does it work for you?
Does CRF support floating point in command line? Any documentation about this?

Testing this good is probably really hard...

**Comment by LeonCheung** [comment]
@niksedk, very cool update. ❤️ 
1. TBH, not sure if CRF support floating point in the command line, but the other tools I'm using support that. 
2. After testing it for quite some time, the latest beta works pretty well so far, just... the resolution for ASSA is locked, is it WIP or?
3. Is 2-pass encoding a rigid requirement for ABR? What about a single-pass option for the sake of time other than quality?
4. Just wondering if it is possible to support only burning a specific part/duration by defining start/end time. It is a nice feature to have if not too hard to implement.

**Comment by niksedk** [comment]
1) OK, I'll keep it at whole number for now.

2) The ASSA resolution should be unlocked now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
I've not tested it yet...

3) I think two passes are needed for ABR - no targeting of file size will result in just one pass - quality depends on CRF/Preset.

4) Maybe in a future version...


And F2 (toggle) will show the FFmpeg command line generated by UI parameters:
![image](https://user-images.githubusercontent.com/1261331/132997969-7f8e870e-f416-4b46-91c3-6df96460b44a.png)

````
ffmpeg -i "C:\Data\Video\50.mp4" -vf "ass=input.ass",yadif,format=yuv420p -g 30 -bf 2 -s 1280x720 -c:v libx264 -preset medium -crf 23 -c:a copy -tune film -use_editlist 0 -movflags +faststart ""

````

**Comment by LeonCheung** [comment]
Got it. And the resolution works great. Thank you so much!
