### ISSUE TITLE
burn-in error

### ISSUE THREAD

**Issue by keumala** [SubtitleEdit/subtitleedit#5310]
![SE error](https://user-images.githubusercontent.com/89993189/131878407-72b047e5-2e1d-4e37-b4a6-1a9102fdb3ee.JPG)

**Comment by niksedk** [comment]
Thx for the info - the crash is hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by keumala** [comment]
Hi, Nik.
The Beta I use now. And it stopped here. No progress
![image](https://user-images.githubusercontent.com/89993189/131942047-9a2ef06f-e9c0-4cf0-862f-9b2c48553fa3.png)

**Comment by LeonCheung** [comment]
@keumala I think it's the same problem as mentioned in #5308. Actually, it's still running, just can't see the feedback of time remaining. You can expect to get the generated video in a while if you just keep waiting, in case you really need this feature now.  :)

**Comment by keumala** [comment]
yes, the progress not showed up but after a while the file is generated in the folder. I think it's work. Thanks, guys
