### ISSUE TITLE
[Feature Request] Keyboard shortcuts for Apply

### ISSUE THREAD

**Issue by aotgunrt** [SubtitleEdit/subtitleedit#5311]
I love this Product!! :o)

I do most of my editing using the keyboard not the mouse.

1. I get stuck trying to Apply under Fix common errors.
2. I also get stuck trying to Apply under remove text for hearing impaired
 
![Fix common errors 75 ](https://user-images.githubusercontent.com/39061978/131891883-ff55c7f5-b466-454d-ab4b-d84469ec35e3.png)

![remove text for hearing impaired 75](https://user-images.githubusercontent.com/39061978/131891517-807d1c2f-20bc-4e36-a46f-11768fdf3deb.png)

Adding a way to apply in these cases would make my life easier.

Thank You

**Comment by niksedk** [comment]
Hopefully fixed in latest beta;  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by aotgunrt** [comment]
Thanks this looks Great.
