### ISSUE TITLE
SRT Color Issue (?)

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5312]
This is happening on the versions 3.6.2.27 - 30 - 38 - 45

![E2](https://user-images.githubusercontent.com/64425752/131932392-cf188d2e-07cc-4bab-8cc8-51eb6c6acdc6.jpg)

**Comment by OmrSi** [comment]
Personally, I am unable to reproduce this.

**Comment by LeonCheung** [comment]
Just curious, how can the SRT get shadows?

**Comment by Andrebavila** [comment]
Version 3.6.2.58 is alright.
I think the SRT was taking a ASSA style somehow.
I don't know what happened.
