### ISSUE TITLE
"Max. number of lines" enforcement

### ISSUE THREAD

**Issue by pandalamp** [SubtitleEdit/subtitleedit#5313]
As of version 2.6.2, the "max. number of lines" setting is being strictly enforced (instead of just turning the line red). Previously, text could exceed the threshold by at least one extra line as "too long" which was useful while editing.

When I am breaking up too-long text, I often try breaking the lines manually in different ways within the text window before splitting it, which sometimes exceeds the line limit. It doesn't end up being a problem since I split the lines anyway, but now that limit can no longer be manually surpassed even temporarily. I can change the max number of lines from 2 to 3 for the sake of editing and split them from there, but then I can no longer quickly identify the lines I need to break up.

In my opinion "max. number of lines" should refer to the amount of lines before the "too long" indicator is triggered, and not how many lines we are able to edit.

**Comment by OmrSi** [comment]
You can force a new line by using `Control + Enter`...

**Comment by pandalamp** [comment]
> You can force a new line by using `Shift + Enter`...

Thank you, that's helpful in a pinch, but I still find this change unusual since previous versions always allowed the maximum +1. Now I see Issue #5107 seems to be behind the change, but FWIW I think it should have been left alone and rolled back my version for now as the sudden change breaks my current workflow.

**Comment by niksedk** [comment]
I will roll it back or make a new UI setting.
