### ISSUE TITLE
ASSA missing info

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5317]
It seems the lastest beta cannot load (or save?) some key info:
![QQ截图20210904113945](https://user-images.githubusercontent.com/494788/132081228-a5da5c65-0fbf-43ef-bb6e-250f98a7c4ed.jpg)

When loading the file it seems okay at the beginning, but it just caused problems until I figured out what's wrong.

Another thing is, when loading an existing file, the first style is also set to Default while saving. Not sure both issues are the same one. FYI.

**Comment by niksedk** [comment]
Yes, definitively something strage going on...

**Comment by niksedk** [comment]
How is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Nice fix. Thanks, though the WrapStyle and ScaledBorderAndShadow are still missing. (personally, I never use them, just point it out)
