### ISSUE TITLE
Overlapping Messages' Location 

### ISSUE THREAD

**Issue by peter-qgd** [SubtitleEdit/subtitleedit#5319]
Is there a way to make the program keeps showing the overlapping values in their original position, as it was in pre 3.6.2 versions? I mean, after processing a lot of subtitles, I never had to deal with such high duration times which will make the overlapping values get into the text box; but mostly because I think those values were already in a convenient position, near the other time related values. I think having relocated them in the status bar leaves them kind of far from the sight, besides they  disappear after a few seconds. Maybe just making the text box resizable; or just putting one message below the other, after lowering the "< Prev" and "Next >" buttons a little bit.

Otherwise, making the messages don't disappear from the status bar till their triggering condition ceases,
would be good as well.

Thanks.

Should be fixed in 3.6.2

_Originally posted by @niksedk in https://github.com/SubtitleEdit/subtitleedit/issues/5193#issuecomment-904907977_

**Comment by niksedk** [comment]
The messages are still also just below the time boxes + in the list view:
![image](https://user-images.githubusercontent.com/1261331/132161563-69d682cc-bfc9-4abb-9e33-3698b3e32f25.png)

**Comment by peter-qgd** [comment]
Yes, but what I say is making the text box resizable, so in those few cases when someone finds an overlapping message gets into the text box, they might just resize it a little bit and fix it right away. Otherwise, relocating the two buttons a little bit, and using the wasted space below them, kind of like this:

![v3 6 1-messages-2](https://user-images.githubusercontent.com/82705380/132257639-63e29625-cc92-47c0-8c92-09fb013cd7e2.png)

That way, the messages as well as the values will still be shown near the "duration" and "start time" values and in a permanent way, while freeing the status bar.

I'm used to press a lot the "up" and "down" arrows from the "duration" and "start time" boxes, and having the overlapping values near to them makes it quicker to discern the exact needed values to fix the overlaps.

Maybe even better, making the current redundant "overlap" messages that appear below the above mentioned boxes (besides the status bar), get just swapped with the "values" that appear on the status box, like this:

![v3 6 1-messages-3](https://user-images.githubusercontent.com/82705380/132258919-a2cd6012-d176-44ee-ad65-5b2dd35ef817.png)
