### ISSUE TITLE
values does not fall within the expected range

### ISSUE THREAD

**Issue by nikoslamb** [SubtitleEdit/subtitleedit#5321]
Trying to slow down a wma audio file I received this message: values does not fall within the expected range.
![image](https://user-images.githubusercontent.com/26150566/132120573-26c40b2c-b638-4dbc-a5f6-ee4812fd076a.png).
Slowing down mp3 or wav file in directShow player results in slower pitch. Using VLC player slowing down results in same pitch.

**Comment by niksedk** [comment]
Your current filters do not support changing play rate... try to install lav filters: https://github.com/Nevcairiel/LAVFilters/releases
Or use "mpv" inside SE.

Yes, mpv and vlc are pretty smart - only slows the speed and not the pitch :)
