### ISSUE TITLE
Show both current subtitle and original subtitle in video zone and waveform zone

### ISSUE THREAD

**Issue by eZioPan** [SubtitleEdit/subtitleedit#5324]
Is it posible to show both current and original subtitle in `video zone` and `waveform zone`? Like the potplayer that can add the 2nd subtitle into video. When add 2nd subtitle to potplayer, it automatically show it at upper area of the video. This will be very helpful when translating and comparing the subtitles.
![potplayer](https://user-images.githubusercontent.com/10928361/132167680-8db485a6-b72a-4f27-91de-4462a32a64d4.jpg)

**Comment by LeonCheung** [comment]
Not sure if this helps:

![new](https://user-images.githubusercontent.com/494788/132182838-4b7b142f-bff1-4bea-ab01-1f12def75a02.jpg)

**Comment by eZioPan** [comment]
@LeonCheung Thanks!  
There is a problem, if I load original subtitle as the translator mode, and load the same subtitle from `Video` -> `Open Second Subtitle File ...`. If I edit the original file, the subtitle in video zone won't change dynamically.

**Comment by LeonCheung** [comment]
I see. Well, before a better solution coming out, a workaround is to merge both files as one. say, for per subtitle, Line1 is Language 1, Line 2 is for Language 2, then start working. on it  When you are done with everything, there are several ways to split/output the two languages individually.

**Comment by eZioPan** [comment]
@LeonCheung Thanks! That's what I'm currently doing. I hope this could be implemented someday.
