### ISSUE TITLE
[Feature request] Ability to duplicate a line

### ISSUE THREAD

**Issue by Kelvets** [SubtitleEdit/subtitleedit#5326]
I want to make dual-language subtitles for a video, so I'd like to be able to just right-click a line and duplicate it, which means: add a new line just below it which has the same beginning and ending timestamps, where I can write the second-language text. 

Without this feature, I have to apply a workaround: make a separate second-language file with the same timestamps, insert a line above the first line, and right-click "Insert subtitle after this line..." and choose the file I made.

**Comment by OmrSi** [comment]
Hmm. This already exists as a shortcut, but I don't know why It's been removed from the UI…

@niksedk Removed here by accident https://github.com/SubtitleEdit/subtitleedit/commit/bdf1bc92bc0b25025e109baa5a123783b89416bc#diff-3f6d5fda2a75ccaa557f97f7d2e45211b651612c785a8dbb06f74f316bc53f62L1261?

**Comment by niksedk** [comment]
Thx :)
Yes, was indeed removed by accident - nice find :)

Should be available again now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/132405381-c6fa8a86-f502-4dc7-8232-777d53ace94a.png)
