### ISSUE TITLE
subtitle color doesn't change

### ISSUE THREAD

**Issue by ib2dr** [SubtitleEdit/subtitleedit#5329]
Hi

When i select .ssa and add new station alpha styles

the color change to deterrent colors 

for example i select yellow here : 
![1](https://user-images.githubusercontent.com/81266218/132359178-4a64b5c9-ad82-4b3a-bb6a-a47559f9f8a2.png)

than save 

when i back i found it like this : 
![2](https://user-images.githubusercontent.com/81266218/132359180-522961d9-ff57-4ea9-963b-2a43525cbc11.png)

i tried everything but the issue still happen to me
the issue start when i update to 3.6.2

when it was 3.6.0 there was no problem  
< i jumped 3.6.1

and thank you <3

**Comment by OmrSi** [comment]
Could you try the beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
It was probably fixed.

**Comment by ib2dr** [comment]
> 
> 
> Could you try the beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
> It was probably fixed.

yes its perfect in the beta. thanks omr ..

great job,
again thanks guys <3
