### ISSUE TITLE
[LibSE] Publish v3.6.2 libSE in nuget repository

### ISSUE THREAD

**Issue by GerardSoleCa** [SubtitleEdit/subtitleedit#5330]
Hi,

I'm using libSE for a small project. Today I was checking why a ttml file I have was not properly parsed by TimedText10.cs. I saw that the time codes where using an "f" char at the end of the number.

After verifying the latest SubtitleEdit version and also the git history, I've seen that there is a commit that would solve my issue.

The commit I'm talking about is [Allow time codes with format "12529f" in TTML](https://github.com/SubtitleEdit/subtitleedit/commit/17b4e5833f5388112e10245fa42173da2d774c4e#diff-0ce8afd68b85d0ce231056e8b4f42b760b945160853c71bc7a631c81b29fd356). Unfortunately, I've checked the latest published libSE version in nuget and it's v3.6.0, which does not contain this commit.

If you don't mind, I'd really appreciate if you publish a libSE v3.6.2.

Meanwhile I'll verify that using master and generating the dependency straight from the repo solves my issues too. 

Thanks! And have a nice day! :D

**Comment by niksedk** [comment]
OK, tried to create and upload the package here: https://www.nuget.org/packages/libse/3.6.2

Let me know how it works :)

**Comment by GerardSoleCa** [comment]
@niksedk Thanks! I've just tested the new release and it's working. 
The subtitle is properly loaded and I can work with it.

I really appreciate your quick response, thanks! :D
