### ISSUE TITLE
Open PGS Subtitles in 'Edit Mode' by Default

### ISSUE THREAD

**Issue by peter-qgd** [SubtitleEdit/subtitleedit#5331]
Hello, given the fact I never do OCR on blu-ray subtitles but I always open them to alter some of its features, would you consider
to add a new option, which allows to open these kind subtitles always in edition mode? That will mean reducing the amount of clicks for such task considerably.

Thanks.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by peter-qgd** [comment]
> Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

I just tried last final version, and the new option is working fine, however it would still be better if:

**1-** The last used size as well as position of the editor window are remembered.

**2-** Once the editor window is closed, don't let opened a main program's blank window; make it closes completely.

Thanks.
