### ISSUE TITLE
Split Line when Opening New File

### ISSUE THREAD

**Issue by Thanebreaker** [SubtitleEdit/subtitleedit#5332]
Hello all, 
I am running into an issue where when I open the SCC file it has split line throughout, others are not reporting this issue so I believe it to be specific to my settings. I am using the latest version (just downloaded) and any insight into what may be happening will be helpful or  even a workaround that doesn't involve manually combing the lines. 
I have included an example of what I am see in text form, 
Thank you! 

2
00:00:16,959 --> 00:00:17,059
In the sprin

3
00:00:17,083 --> 00:00:18,792
g of
1805, a Shawnee man

4
00:00:20,417 --> 00:00:21,226
{\an1}named Lalawethika, who
was given to stron

5
00:00:21,250 --> 00:00:22,417
g drink

**Comment by niksedk** [comment]
Could you attach or email the scc file?
