### ISSUE TITLE
Errors converting files: WebVTT to SubRip

### ISSUE THREAD

**Issue by manuelrn** [SubtitleEdit/subtitleedit#5334]
Hello,

On many occasions I have had WebVTT subtitles that contain a multitude of "WEBVTT" and "STYLE" distributed throughout the subtitle.

By converting the WebVTT subtitle to SRT, Subtitle Edit only removes the first occurrence of them, all the others remain intact.
As a curiosity: until version 3.5.6 (included) this did not happen. That is, the resulting SRT with those old versions of Subtitle Edit do not contain any "WEBVTT" or "STYLE".

Would it be possible for Subtitle Edit to get rid of all that "garbage" during the conversion process?
It would be greatly appreciated and would be ideal.
<br /><br />

I have created a WebVTT subtitle to simulate these cases:
[sample.zip](https://github.com/SubtitleEdit/subtitleedit/files/7138982/sample.zip)
```
WEBVTT

STYLE
::cue() {
  font-family: Arial, Helvetica, sans-serif;
}

00:00:34.117 --> 00:00:36.036 line:85.19%,end
Line 1

00:01:04.898 --> 00:01:06.650 line:85.19%,end
<i>Line 2</i>

00:01:19.371 --> 00:01:22.833 line:85.19%,end
Line 3

WEBVTT

STYLE
::cue() {
  font-family: Arial, Helvetica, sans-serif;
}

00:14:17.733 --> 00:14:20.903 line:14.81%,start
Line 4

00:14:21.069 --> 00:14:24.031 line:14.81%,start
<i>Line 5</i>

00:14:24.114 --> 00:14:25.115 line:85.19%,end
Line 6

00:14:25.240 --> 00:14:28.619 line:85.19%,end
Line 7

00:14:28.785 --> 00:14:30.871 line:85.19%,end
Line 8

00:14:31.455 --> 00:14:34.333 line:85.19%,end
Line 9

00:14:35.834 --> 00:14:36.835 line:85.19%,end
Line 10

00:20:20.721 --> 00:20:22.723 line:14.81%,start
Line 11


WEBVTT
STYLE
::cue() {
  font-family: Arial, Helvetica, sans-serif;
}

00:25:22.105 --> 00:25:23.190 line:85.19%,end
Line 12

00:25:26.360 --> 00:25:27.486 line:85.19%,end
Line 13

00:25:35.744 --> 00:25:37.496 line:85.19%,end
Line 14

00:25:37.663 --> 00:25:41.291 line:85.19%,end
Line 15

00:25:41.458 --> 00:25:42.459 line:85.19%,end
Line 16

00:25:42.626 --> 00:25:43.961 line:85.19%,end
Line 17

00:25:44.044 --> 00:25:45.295 line:85.19%,end
Line 18

00:25:45.379 --> 00:25:46.505 line:85.19%,end
Line 19

00:25:48.298 --> 00:25:49.299 line:85.19%,end
Line 20

```
<br /><br />

SRT converted with Subtitle Edit 3.6.2:
```
1
00:00:34,117 --> 00:00:36,036
Line 1

2
00:01:04,898 --> 00:01:06,650
<i>Line 2</i>

3
00:01:19,371 --> 00:01:22,833
Line 3


STYLE
::cue() {
font-family: Arial, Helvetica, sans-serif;
}

4
00:14:17,733 --> 00:14:20,903
{\an8}Line 4

5
00:14:21,069 --> 00:14:24,031
{\an8}<i>Line 5</i>

6
00:14:24,114 --> 00:14:25,115
Line 6

7
00:14:25,240 --> 00:14:28,619
Line 7

8
00:14:28,785 --> 00:14:30,871
Line 8

9
00:14:31,455 --> 00:14:34,333
Line 9

10
00:14:35,834 --> 00:14:36,835
Line 10

11
00:20:20,721 --> 00:20:22,723
{\an8}Line 11


STYLE
::cue() {
font-family: Arial, Helvetica, sans-serif;
}

12
00:25:22,105 --> 00:25:23,190
Line 12

13
00:25:26,360 --> 00:25:27,486
Line 13

14
00:25:35,744 --> 00:25:37,496
Line 14

15
00:25:37,663 --> 00:25:41,291
Line 15

16
00:25:41,458 --> 00:25:42,459
Line 16

17
00:25:42,626 --> 00:25:43,961
Line 17

18
00:25:44,044 --> 00:25:45,295
Line 18

19
00:25:45,379 --> 00:25:46,505
Line 19

20
00:25:48,298 --> 00:25:49,299
Line 20


```
<br /><br />

Ideally, the Subtitle Edit should convert it like this:
```
1
00:00:34,117 --> 00:00:36,036
Line 1

2
00:01:04,898 --> 00:01:06,650
<i>Line 2</i>

3
00:01:19,371 --> 00:01:22,833
Line 3

4
00:14:17,733 --> 00:14:20,903
{\an8}Line 4

5
00:14:21,069 --> 00:14:24,031
{\an8}<i>Line 5</i>

6
00:14:24,114 --> 00:14:25,115
Line 6

7
00:14:25,240 --> 00:14:28,619
Line 7

8
00:14:28,785 --> 00:14:30,871
Line 8

9
00:14:31,455 --> 00:14:34,333
Line 9

10
00:14:35,834 --> 00:14:36,835
Line 10

11
00:20:20,721 --> 00:20:22,723
{\an8}Line 11

12
00:25:22,105 --> 00:25:23,190
Line 12

13
00:25:26,360 --> 00:25:27,486
Line 13

14
00:25:35,744 --> 00:25:37,496
Line 14

15
00:25:37,663 --> 00:25:41,291
Line 15

16
00:25:41,458 --> 00:25:42,459
Line 16

17
00:25:42,626 --> 00:25:43,961
Line 17

18
00:25:44,044 --> 00:25:45,295
Line 18

19
00:25:45,379 --> 00:25:46,505
Line 19

20
00:25:48,298 --> 00:25:49,299
Line 20


```
<br /><br />

Thanks and regards!

**Comment by larsk2** [comment]
I also had the exact same problem. Thanks in advance 👍

**Comment by niksedk** [comment]
Hm, that's not a valid WebVTT file...

**Comment by manuelrn** [comment]
> Hm, that's not a valid WebVTT file... how did you get the file. Perhaps the generating tool is buggy?

Admittedly, it doesn't make a lot of sense, but many VOD platforms contain subtitles like this...

If Subtitle Edit could be able to deal with it, it would be ideal.

Anyway, if you notice, Subtitle Edit does skip all the repeated "WEBVTT"... But it doesn't with "STYLE".
Just like Subtitle Edit does that process with "WEBVTT", couldn't it do it with "STYLE" as well?

Thanks and regards!

**Comment by niksedk** [comment]
OK, does this work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip ?

**Comment by manuelrn** [comment]
> OK, does this work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip ?

Yes, now it works perfect!

But in the SRT file those lines remain blank, instead of disappearing completely.
For example, using the same file that I attached in the first message, the result is this:
```
1
00:00:34,117 --> 00:00:36,036
Line 1

2
00:01:04,898 --> 00:01:06,650
<i>Line 2</i>

3
00:01:19,371 --> 00:01:22,833
Line 3



4
00:14:17,733 --> 00:14:20,903
{\an8}Line 4

5
00:14:21,069 --> 00:14:24,031
{\an8}<i>Line 5</i>

6
00:14:24,114 --> 00:14:25,115
Line 6

7
00:14:25,240 --> 00:14:28,619
Line 7

8
00:14:28,785 --> 00:14:30,871
Line 8

9
00:14:31,455 --> 00:14:34,333
Line 9

10
00:14:35,834 --> 00:14:36,835
Line 10

11
00:20:20,721 --> 00:20:22,723
{\an8}Line 11



12
00:25:22,105 --> 00:25:23,190
Line 12

13
00:25:26,360 --> 00:25:27,486
Line 13

14
00:25:35,744 --> 00:25:37,496
Line 14

15
00:25:37,663 --> 00:25:41,291
Line 15

16
00:25:41,458 --> 00:25:42,459
Line 16

17
00:25:42,626 --> 00:25:43,961
Line 17

18
00:25:44,044 --> 00:25:45,295
Line 18

19
00:25:45,379 --> 00:25:46,505
Line 19

20
00:25:48,298 --> 00:25:49,299
Line 20


```
<br />

Look at the gap between lines 3-4 and 11-12. There are 3 line breaks instead of 1.
Although I think it is something of little importance, but I mention it anyway just in case.

Thank you very much for your quick help!

**Comment by manuelrn** [comment]
Thank you very much @niksedk for the new correction af54f3aa38e320ff2d5ed60353aff8b0d1ae25c8!

Could you confirm if the beta has been updated with this new implementation?
I mean this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

I ask this because I just downloaded the Beta again, and I have tried again with the same file that I attached in the first message, but the line breaks are still present with the latest Beta version of Subtitle Edit.

I have also tried with a real subtitle that I got from a VOD platform, and the line breaks disappear sometimes yes and sometimes no. That is, some line breaks disappear but others remain.

Thanks for everything!

**Comment by niksedk** [comment]
Beta has been updated now :)

**Comment by manuelrn** [comment]
Thank you very much again @niksedk :)

I just tested several subtitles, and all perfect!

Regards!
