### ISSUE TITLE
Burnt-in subs - Same as Source

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5341]
I used it for the first time today, and it is quite quick and I'm impressed. One issue I noticed is that I changed the font size to 60, but SE set it to 89 every time a new instance was opened. If it remembers the last settings, that would be good. And ability to change fonts will be appreciated. 

Two: Same as source. An option that if we check, it'll keep everything same as source video (codecs, audio, etc.), so that it won't impact the quality, format or size of the video. 

Preview window: It took me three tries to get the size (60) right. Preview would be good to avoid this. 

Lastly, batch would be good. Did 21 videos now and batch would've saved a lot of monotonous work.

Thank you.

**Comment by niksedk** [comment]
OK, font family and preview are good ideas and I'll try to add those :)

Same as source is impossible, sorry.

Batch might happen in a later release if this will be working well.

**Comment by niksedk** [comment]
I've tried to add font family + some preview functionality here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by uckthis** [comment]
Can't test it. I replaced the old EXE with this new Beta and it won't open. Avast already has an exception for SE folder, so I don't know what's going on. New Beta opens on its own, but won't when I replace the old EXE from my folder. I have my settings, plugins, backups and all that from last 3-4 years in that folder and won't want to lose that.

Downloaded the 3.6.2 from the site to replace the beta I just replaced and SE opens fine.

**Comment by niksedk** [comment]
Ah, you need all the *.dll files from the beta... I've removed the exe-packing in latest beta to avoid trouble with antivirus programs.

**Comment by uckthis** [comment]
Workaround, I pasted the settings files, backups, plugins and dictionary folder in the new Beta folder and it opened. As long as I don't have to make a new Settings file, I'm good.

**Comment by uckthis** [comment]
Preview does take good 4-5 seconds to generate, but it gets the job done. And fonts work well too.
This will help a lot. Default value of 89 is higher, or maybe it is to me as I'm on a 49" screen. I'd set it at 60 by default and then remember the last settings if possible. 
Thank you.

**Comment by niksedk** [comment]
The preview actually generates the video with ffmpeg, and the takes a screenshot. So it takes a few seconds.

About the font size - SE earlier used 8% of video height - I've now changed it to 7.5% of video height - is that better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by uckthis** [comment]
I think it all boils down to the personal choice. Some may like the text big, some small, and I prefer to be in the middle. Now the font size is 84; which is a stone throw from 89. I just wanted it to remember my last choice so I won't have to change it every time. My choice for size, fonts, etc.

**Comment by niksedk** [comment]
OK, SE should now remember the font size (relative to the video height): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
How does that work?

**Comment by uckthis** [comment]
![Untitled](https://user-images.githubusercontent.com/28671050/133916102-e46e954a-58e0-402f-a6c0-61262632c7cd.png)

"How does that work?"
None.

**Comment by niksedk** [comment]
You need to copy both libse.dll (or rather all dll files) and subtitleedit.exe if you replace files in an existing SE folder.

**Comment by uckthis** [comment]
Fixed. All good now.

Thank you.
