### ISSUE TITLE
Subtitle edit wont be a video

### ISSUE THREAD

**Issue by Kixalvi** [SubtitleEdit/subtitleedit#5344]
Hello so recently i got subtitle edit to use for videos of mine and i cant seem to save the video with the subtitles it always says ".srt" as the file when i open it it opens in subtitle edit is there any way to make it a mp4 file ? please help!

**Comment by niksedk** [comment]
Normally you save the subtitle with the same file name as the video file, and in the same folder. So if you have a "video.mp4" then save the subtitle as "video.srt" which should be picked up by players like VLC, mpc or mpv.

Alternatively you can you use the Video menu "Generate video with hard-burned subs" to created a mp4 file with subtitles burned into the video (cannot be removed again or turned off).
