### ISSUE TITLE
No waveform

### ISSUE THREAD

**Issue by drsantilli** [SubtitleEdit/subtitleedit#5346]
Hi all,
I'm working in a Windows 10 PC and I can't seem to generate, for some reason, the waveform in Subtitle Edit (see attachment for error).
We have tried the following:
- using ffmpeg
- changing from vlc to mpv to all the other options as video players inside SE
- using older versions of SE
- installing K-Lite codecs (and of course VLC)
Videos work properly in other software like Subtitle Workshop or Aegisub, but in SE, the waveform doesn't appear.
Help anyone?

Damián
![subtitle edit error](https://user-images.githubusercontent.com/90929659/133838558-ef1b650a-27fa-4add-bba8-2b40ee9dfeb4.jpg)

**Comment by niksedk** [comment]
You temp folder looks weird. It's normally something like `C:\Users\USERNAME\AppData\Local\Temp`.

To get more info, you could try to run the ffmpeg command from a normal "command prompt": 
```` 
ffmpeg -i "C:\Users\Usario\Documents\Documents\Subtitulado\Clase 3\Silver Linings Playbook.mp4" -vn -ar 24000 -ac 2 -ab 128 -vol 448 -f wav "C:\Windows\system32\config\systemprofile\AppData\Local\Temp\out.wav"
````
