### ISSUE TITLE
Extracting Subtitles Messes up Timings 

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5347]
This happened to me twice, so I think this needs investigating. Whilst extracting the subtitle file from certain media, the output SRT has messed up timings. Initially I thought that the original file is poorly sync'd, but if you play it in VLC and turn on the embedded subtitles, they play accurately and are properly sync'd. 
Here is the file:
https://drop.download/lbjidtwzho
https://dailyuploads.net/6imza29e3c6k

**Comment by niksedk** [comment]
Neither of these links work for me...

**Comment by uckthis** [comment]
https://drive.google.com/file/d/114v4QA3xywnhrI_sh49Zqsi8MA7Kw2ef/view?usp=sharing
Try this.

**Comment by niksedk** [comment]
OK, got the file... thx :)
SE does has an issue with some mp4 files. I'll take a closer look.

**Comment by uckthis** [comment]
I tried with other extractors like CC Extractor and no one was able to extract it. At least SE extracted something albeit with messed up timings.

**Comment by kiumut** [comment]
@uckthis ,
I know this is late and not sure if it will even help solve the problem in SE, but as a workaround, from a command prompt, MP4Box in the [GPAC framework](https://gpac.wp.imt.fr/) seemed to extract the subtitles in this file to SubRip with the correct timings:
`MP4Box.exe "input_file.mp4" -srt 3`
The `3` refers to the number of the subtitles stream and should be changed accordingly. Obviously, so should "input_file.mp4" :-)

You can find the number of the subtitles stream with MP4Box.exe also:
`MP4Box.exe "input_file.mp4" -info`

And you will get:
```
# Track 3 Info - ID 3 - TimeScale 1000000
Media Duration 00:28:58.520
Track has 1 edits: track duration is 00:28:58.520
Media Info: Language "⌂⌂⌂ (⌂⌂⌂)" - Type "sbtl:tx3g" - 677 samples
1 UDTA types:
        name: English
Alternate Group ID 3
QT/3GPP subtitle
        Size 0 x 0 - Translation X=0 Y=0 - Layer 0
        RFC6381 Codec Parameters: tx3g
        All samples are sync
        Max sample duration: 21600000 / 1000000
```

Or you can determine it with [MediaInfo](https://mediaarea.net/MediaInfo):
```
Text
ID                                       : 3
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 28 min 58 s
Bit rate mode                            : Variable
Bit rate                                 : 128 b/s
Stream size                              : 27.2 KiB (0%)
Title                                    : English / English
Default                                  : Yes
Forced                                   : No
Alternate group                          : 3
```

**Comment by uckthis** [comment]
@kiumut Thank you. That seemed to have done the trick. I wasn't aware of  GPAC before, so it's good to have a new tool in the arsenal. It'll be helpful in the future. 

Thank you.
