### ISSUE TITLE
Subtitles are exported in BDSUP format with noisy shadows. Benefits: use different fonts for multiple lines.

### ISSUE THREAD

**Issue by shaino** [SubtitleEdit/subtitleedit#5352]
When subtitles are exported to bdsup format, there will be light noise at the edge of the background shadow.This noise can be eliminated by exporting it once through bdsup2sup app.Is it a palette problem or a sup format parameter problem?

  Exporting sup format will lose many ASS / SSA effects. However, some special effects can use SRT special effect keywords. Sometimes, we find that the font, color and size are filled in, but they are invalid. As long as we nest another layer of < font > at the end of this line of text, it will all be valid.

  Before fixing this bug, we can use this method to realize multiple lines, different fonts, different colors and different sizes, so as to make up for the lack of ASS / SSA support.

  Subtitle is very powerful. I hope that in the future, BDSUP mode can support time overlapping subtitle lines in the same frame, repair edge noise, and directly support more ASS / SSA effects.

  Thanks again.

**Comment by niksedk** [comment]
No sure about the noisy shadows... could you attach some files/images?

Could you also give some examples about the < font > at the end of the line?

ASSA to BDSUP would require libass and would work poorly with animations + large bitmaps. Not sure if BDSUP images has a max size of 64K?

Support of overlapping subtitles is a good idea...

**Comment by shaino** [comment]
About noise:
![Snipaste_2021-09-26_22-03-21](https://user-images.githubusercontent.com/34017325/134811493-7be3197e-72d0-4f77-a32c-fb3edd623420.jpg)
The previous line is the SUP format subtitles directly exported by SubtitleEdit, and the next line is the SUP format subtitles exported by BDSup2Sub++.
![Snipaste_2021-09-26_22-07-43](https://user-images.githubusercontent.com/34017325/134811775-7e6483c2-aa33-4116-918b-4f70ac32f7bf.jpg)
In fact, The BDSup2Sub++ APP open the SUP files and exports them without modification. The noise disappeared.
This problem exists for any color and width of font shadows.
My screenshot is using the VLC player. Windows or Android VLC players have the same problem.The potplayer player does not have this problem.

**Comment by shaino** [comment]
About noise:
![Snipaste_2021-09-26_22-03-21](https://user-images.githubusercontent.com/34017325/134811493-7be3197e-72d0-4f77-a32c-fb3edd623420.jpg)
The previous line is the SUP format subtitles directly exported by SubtitleEdit, and the next line is the SUP format subtitles exported by BDSup2Sub++.
![Snipaste_2021-09-26_22-07-43](https://user-images.githubusercontent.com/34017325/134811775-7e6483c2-aa33-4116-918b-4f70ac32f7bf.jpg)
In fact, The BDSup2Sub++ APP open the SUP files and exports them without modification. The noise disappeared.
This problem exists for any color and width of font shadows.
My screenshot is using the VLC player. Windows or Android VLC players have the same problem.The potplayer player does not have this problem.

**Comment by shaino** [comment]
SRT subtitle effects:
1
00:00:21,550 --> 00:00:24,850
This film was restored by PATHÉ in 2013
<font face="Symbol" size="50" color="#bb9633">The row to show:This film was restored by PATHÉ in 2013</font>

2
00:00:27,850 --> 00:00:33,250
This film was restored by PATHÉ in 2013
<font face="Symbol" size="50" color="#bb9633">The row to show:This film was restored by PATHÉ in 2013<font color="#3c8cb2"></font></font>

3
00:00:37,500 --> 00:00:40,500
This film was restored by PATHÉ in 2013
<font face="Symbol" size="50" color="#bb9633">The row to show:This film <font color="#3c8cb2">was</font> restored by PATHÉ in 2013<font color="#3c8cb2"></font></font>

4
00:00:41,500 --> 00:00:43,600
This film was restored by PATHÉ in 2013
<font face="Symbol" size="50" color="#bb9633">The row to show:This film <font color="#3c8cb2">was</font></font><font face="Symbol" size="50" color="#bb9633"> restored by PATHÉ in 2013<font color="#3c8cb2"></font></font>

![001](https://user-images.githubusercontent.com/34017325/134813438-8a08b122-65dd-46a4-b5e0-4d53be519f29.jpg)

![002](https://user-images.githubusercontent.com/34017325/134813454-7886134c-9878-4886-9826-04509b8d8ea6.jpg)

![003](https://user-images.githubusercontent.com/34017325/134813458-aaedff8d-e713-4e98-9dd2-145aaf17db38.jpg)

![004](https://user-images.githubusercontent.com/34017325/134813463-b26f8d87-c85d-47d8-81b5-365ade1d77e1.jpg)

**Comment by niksedk** [comment]
About the bd sup shadow/border noise -- is this beta better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by shaino** [comment]
Great job! The beta version of October 30 has fixed noise.But the font effect still hasn't improved.
Thanks.

**Comment by shaino** [comment]
Great job! The beta version of October 30 has fixed noise.But the font effect still hasn't improved.
Thanks.
