### ISSUE TITLE
Generated waveform won't load due to hyphen in the WAV title

### ISSUE THREAD

**Issue by Tuan-P** [SubtitleEdit/subtitleedit#5356]
When a waveform/spectrogram is generated, it loads automatically when the video file is reopened in SE. But this wasn't happening with a specific video I was working with, regardless of whether the waveform was generated with VLC or FFmpeg. Each time I opened this video, I needed to clear the waveform folder and generate a new spectogram, because clicking on "add waveform" wouldn't do anything. 

I checked out the waveform folder and the WAV file for this specific waveform was named "10ba7dd4532ebf80-1", with a hyphen. Then I removed the "-1" at the end of the filename and all the problems seem to be gone, now the waveform loads automatically.

**Comment by niksedk** [comment]
Thx :)

Should be fix now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
