### ISSUE TITLE
Automatically adding tags when splitting

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5358]
When merging multiple lines that contain, say, `{\an2}`, in each line, SE automatically removes extra tags, which is cool. 👍 
I just hope to see an option allowing automatically inherit tags to new lines after splitting.  ❤️

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Cool fix, thx, closing.
