### ISSUE TITLE
Importing files messes up Timing

### ISSUE THREAD

**Issue by OneManPartyCrew** [SubtitleEdit/subtitleedit#5361]
Hey,
New to Subtitle Edit and I hope I'm not posting something dumb.
I tried to import .xml and .rtf files and it messes up the timing and lenght of the subtitles compared to when I open them in a text editor.
Is there a solution for this problem?
Thanks in advance

**Comment by niksedk** [comment]
Could you attach the subtitles and a screenshots of what is messed up?

**Comment by OneManPartyCrew** [comment]
https://wetransfer.com/downloads/a21a514135f85f5c811f5fed2dad3d1620210930101026/5b894c9214a3e92794200c21c52d34cf20210930101047/837b54
![Messed Up](https://user-images.githubusercontent.com/91423988/135436833-5127248e-1277-4e2e-9d97-1928c86d881c.PNG)

It seems to be a framerate problem. But none of the frameratechanges I've done seems to fix the problem
