### ISSUE TITLE
Allow hiding tool panels

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5365]
IMHO, for those who rarely use the tool panels, it just keeps taking away quite a bit of space on the screen. It would be nice to allow hiding it in some way, a button or a shortcut, for example:

![QQ截图20210929224720](https://user-images.githubusercontent.com/494788/135292764-8b4102a2-a7d5-4ce7-8c55-4bb0451f60a5.jpg)

so that we can have more space to edit waveform. :)

**Comment by niksedk** [comment]
Probably not too intuitive... but the shortcut is here: 
![image](https://user-images.githubusercontent.com/1261331/135299278-45c7f8b5-622d-4821-91ef-6517f8caeaef.png)

A UI button would probably be nice :)

**Comment by LeonCheung** [comment]
Oh, that's nice! I didn't know that, awckward... XD

Maybe another solution can be:

![QQ截图20210929235311](https://user-images.githubusercontent.com/494788/135304781-b23ac28c-fda9-4884-99cd-948a10ebdb90.jpg)

Just brainstorming. :)

**Comment by OmrSi** [comment]
@niksedk Should I give it a try?

**Comment by LeonCheung** [comment]
Well solved, thx. Closing.

**Comment by OmrSi** [comment]
Oh, sorry. I didn't notice the reaction to this and forgot about it.

**Comment by niksedk** [comment]
> Oh, sorry. I didn't notice the reaction to this and forgot about it.

np :)
