### ISSUE TITLE
New sub format request

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5366]
Could you please support parsing texts like this?

[example.txt](https://github.com/SubtitleEdit/subtitleedit/files/7253009/example.txt)

**Comment by niksedk** [comment]
Could you provide a longer example?

**Comment by LeonCheung** [comment]
Sure, here is a longer one. 
[example2.txt](https://github.com/SubtitleEdit/subtitleedit/files/7253290/example2.txt)

Actually, it's pretty much the same as the reverse engineering work to the Export to custom format rule like this:

![NEW1](https://user-images.githubusercontent.com/494788/135303921-a139cb22-7bc2-42c0-b6e7-b85a9b53a389.jpg)

But the only difference is that there may be or may not be space before "[" or afeter "]" in some sections.

**Comment by niksedk** [comment]
What is this supposed to be?

````
         who's [unintelligible 00:00:11] to



Time code or text?

**Comment by LeonCheung** [comment]
Oh, things like that should be treated as text please.

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
(Unknown format 104)

**Comment by LeonCheung** [comment]
Hi, it's almost perfect! Just one more thing, not sure why there are still some lager gaps somewhere (take the example file here for example):

![QQ截图20211002174332](https://user-images.githubusercontent.com/494788/135711176-2e424dea-6695-410c-a68e-1de1a885c8e4.jpg)

**Comment by niksedk** [comment]
Well, as there's not end time, SE uses the `SubtitleOptimalCharactersPerSeconds` for calculating the duration (but caps at max display time)

**Comment by LeonCheung** [comment]
Yes, but can we please just simply extend every end to the start of the next line? (of course with preset gaps) because CPS doesn't always smart enough due to speakers' speed and the languages they use.  :)

**Comment by LeonCheung** [comment]
Thank you so much, it's perfect in the latest build, closing.
