### ISSUE TITLE
ASSA: Can't export per-line subtitle

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5369]
Not sure if it is caused by d555252, when trying to export certain line in custom format panel, it just failed:

![image](https://user-images.githubusercontent.com/494788/135575698-e2550834-e8bb-4876-9255-b4be3e3f07bb.png)

**Comment by niksedk** [comment]
Seems to work fine for me in latest beta...

**Comment by LeonCheung** [comment]
The version I used was 127. I just it tested it with 133, it's gone. No problems then. thanks. closing.
