### ISSUE TITLE
Can't export video with subtitles 

### ISSUE THREAD

**Issue by lisah07** [SubtitleEdit/subtitleedit#5370]
This is my first time using subtitle edit and I cannot generate the video with subtitles. Please view attachment of the picture!

What do I need to do?~!
![Capture](https://user-images.githubusercontent.com/84812839/135686481-a5dd8db4-406d-49aa-8b10-c88619ed658b.PNG)

**Comment by niksedk** [comment]
This is hopefully fixed in the current beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip ?

**Comment by lisah07** [comment]
This is still giving me the error.

**Comment by niksedk** [comment]
What beta version number do you have? See Help - About?
Please attach a screenshot again too :)

**Comment by lisah07** [comment]
I have 3.6.2.

I'm trying to add subtitles onto the video and saving it as a hardsub on the video. 

What I do is click:
Video-generate video with burn sub... and this pops up. 

![Capture1](https://user-images.githubusercontent.com/84812839/139940469-a1a79297-b88b-4ccc-9dbd-7eb447fa2485.JPG)

**Comment by niksedk** [comment]
Wait for next update... should be soon :)
