### ISSUE TITLE
[Shortcut issue] Set start and offset the rest

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5373]
In the latest build, there are actually two identical items for "Set start and offset the rest", and they function the same too. Maybe one of them should be removed?
 
![QQ截图20211005185440](https://user-images.githubusercontent.com/494788/136010169-4a8f0928-d853-4ecf-b15f-fff6923dbe9f.jpg)

**Comment by OmrSi** [comment]
That's intended and pretty old. https://github.com/SubtitleEdit/subtitleedit/issues/4902

**Comment by LeonCheung** [comment]
Alright then, thx for the info. Closing. :)
