### ISSUE TITLE
Is there a way to change case when replacing a regex capturing group?

### ISSUE THREAD

**Issue by kiumut** [SubtitleEdit/subtitleedit#5385]
I am trying to write a regex in the Multiple Replace dialog box (or in Find/Replace) that will change the case of a letter/word when replacing text in SRT subtitles and can't figure out how it might be done.

For example, if I have the line, "focused on liquid water... Follow the water." I want to make the "F" in "Follow" to be lowercase. I've tried the following regex construct but to no avail.
Find: "\.{2,} ([A-Z])"
Replace: "... \L$1"

Am I missing something simple? I looked at the Microsoft .NET regex pages but couldn't find anything that works for the _replace_ part. That is, "\.{2,} (\p{Lu})" works in the find portion of the regex, but not in the replacement.

I can do a "\L\1" regex replacement in other programs such as Notepad++ and I am currently unloading the SRT from Subtitle Edit, running those regex replacements in Notepad++, then re-opening it in SE. But I'd like to be able to do it all in one place, if possible.

Similarly, if there is a way to do this, can it also be done across multiple subtitle lines (i.e., not a multi-line subtitle)? For example,
Subtitle line 4: "focused on liquid water..."
Subtitle line 5: "Follow the water."

Any help/advice would be greatly appreciated!

**Comment by niksedk** [comment]
Sorry, I do not think this is possible - I've been having the same issue.
You can of course do a replace for each letter - but it seems that this is a missing feature indeed.

**Comment by kiumut** [comment]
OK, thanks both for confirming what I was seeing.
