### ISSUE TITLE
Windows Forms Thread Exception Error Message

### ISSUE THREAD

**Issue by random-username123** [SubtitleEdit/subtitleedit#5386]
I just downloaded the application. I wouldn't know what this refers to but happens upon launch and doesn't let me do anything ("Ignore" option closes the message but it comes back again). The Italian reads "Rectangle width can't be equal to zero."

<img width="463" alt="Immagine 2021-10-13 110402" src="https://user-images.githubusercontent.com/92431818/137103423-73dd7f9c-8a99-47dc-a7c2-acdc51aae9a3.png">

**Comment by niksedk** [comment]
It looks like something related to windows or the dot net framework.
Try to re-install dot net framework 4.8. If that does not work then perhaps try updating your graphics card drivers.

**Comment by random-username123** [comment]
> 
> 
> It looks like something related to windows or the dot net framework. Try to re-install dot net framework 4.8. If that does not work then perhaps try updating your graphics card drivers.

Everything is up to date.
