### ISSUE TITLE
[Suggestion] Is it possible to have a variety of Subtitle Background Styles

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#5391]
In Subtitle Edit it's possible to have Subtitle Backgrounds e.g. in ASS styles. 
At the moment, the styles available are Box Per Line (Uses Outline Color) and One Box (Uses Shadow Color) 

This is good and does the job.

However, it would be awesome to have a variety. 

1. 
For example, in the Box Per Line, you'll notice that the outlines overlap both lines and this results in a dark line when burning in subtitles to a video in between 2 line subtitles.  

- It would be awesome not to have a dark line between subtitles i.e. there should be a separation.

2. 
As for the One Box, it would be awesome to also have it move from one end of the video to the other. (If someone wants the box end to end, that's available)

3. 
Is it possible to adjust from a normal box to a box with rounded corners? 

4. 
Is it possible to change the background color for an individual subtitle box without changing the color for all subtitle backgrounds?

5. 
It would be awesome if the subtitle backgrounds would be available for SRT's as well. :) 

![Box for Background](https://user-images.githubusercontent.com/92556454/137415357-f5b92024-7f05-4dfa-acc6-e392389144a4.png)

I hope the image above is explanatory.

Thanks!

**Comment by niksedk** [comment]
The "ASSA styles" window is only for settings supported by ASSA styles. Other background boxes are not available.

I've tried to make a "Generate ASSA background box" generator (only for whole block)
![image](https://user-images.githubusercontent.com/1261331/148422025-354da269-93ca-4760-add4-a3107b4b5ce3.png)

Available via list view context menu - ASSA tools - Generate background box
(text should not be changed after doing this, as text box are hardcoded to pixels at the time of generating)


Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
