### ISSUE TITLE
[Bug] [Important] Subtitle Edit flashes bright blank white pages and GUI elements

### ISSUE THREAD

**Issue by Dark-Magician** [SubtitleEdit/subtitleedit#5394]
Subtitle Edit: 3.6.2
OS: Windows 10 - 64-bit

https://user-images.githubusercontent.com/19816749/137568333-670c816c-e4c1-41ea-97a4-b581bb27f2b1.mp4

Please, investigate and fix this as soon as possible because it is a severe accessibility issue with negative health implications, especially in low-light environments.

**Comment by niksedk** [comment]
I think we have done what we can, limited by Winforms ...

**Comment by Dark-Magician** [comment]
> I think we have done what we can, limited by Winforms ...

What did you do? Could you look at the commits that addressed this issue in Shotcut and Sandboxie Plus?

https://github.com/mltframework/shotcut/commit/a72b757c72ef085bfecebb7e379d1dd05a0667f9
https://github.com/sandboxie-plus/Sandboxie/commit/667535cdbe11115c44f7110ab3f800ba4844b409
https://github.com/sandboxie-plus/Sandboxie/commit/401e3d33570d02923bd51cef9aa8435800b90785
https://github.com/sandboxie-plus/Sandboxie/commit/0b1b4af79a366896ae3089214391880cb8c98b70

Can a similar workaround work in Subtitle Edit?
