### ISSUE TITLE
Please support BiDirectional text (Arabic, Farsi, Hebrew, etc ...)

### ISSUE THREAD

**Issue by hamedsbt** [SubtitleEdit/subtitleedit#5397]
My primary language is Persian, so I'm watching movie with Persian/Farsi (like Arabic lang) subtitle. after open .srt file with the SubtitleEdit it does not shown correctly because the chars on a verb should not be separated each other.

correct: ```سیستم عامل``` 
incorrect: ```س ی س ت م   ع ا م ل```

![image](https://user-images.githubusercontent.com/7298328/137696199-b6f0ae5f-f7c8-4ead-9296-b90361a3678b.png)

Linux archlinux 5.14.12-arch1-1 #1 SMP PREEMPT Wed, 13 Oct 2021 16:58:16 +0000 x86_64 GNU/Linux
Aur package: https://aur.archlinux.org/packages/subtitleedit/

**Comment by MasterKia** [comment]
I know it's been 4 years, but have you found any fix for this?

**Comment by hamedsbt** [comment]
> I know it's been 4 years, but have you found any fix for this?

**Unfortunately** not :'(

**Comment by darnn** [comment]
This is not a solution per se, but as a stopgap measure, a Windows VM (or Wine, I'm not sure as I'm not a Linux user myself) might do, because this works fine on Windows.

**Comment by MasterKia** [comment]
IIRC this software is Windows only so it _has_ to be run under Wine.
