### ISSUE TITLE
Generate burned-in sub: Better default naming rule

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5402]
Currently, when generating videos with the burned-in sub tool,  you need to choose the target file path and type the file name, every time. 

**For better project management**, it would be nice to automatically create a `SE_Output` folder in the same directory of the project file, and with a default file name like `[filename]_Burned.mp4` or something. Just my two cents.

**Comment by Tanialataniatania** [comment]
Hola.
When I try to generate burned-in sub, I get this:

Help?
![image](https://user-images.githubusercontent.com/93620769/139949826-08da5545-28bc-41ff-9843-d2e67108cbfc.png)

**Comment by niksedk** [comment]
@Tanialataniatania: Get the beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip
Or wait for next update (soon)

**Comment by niksedk** [comment]
Naming is a little better in latest beta
