### ISSUE TITLE
A chamada foi rejeitada pelo chamado. Exceção de HRESULT: 0x80010001 (RPX_E_CALL_REJECTED))

### ISSUE THREAD

**Issue by juliacaldana** [SubtitleEdit/subtitleedit#5406]
Every time I try to run the spellcheck with the plugin Word Spell Check I get this message 
![image](https://user-images.githubusercontent.com/92887499/138156876-2efba5dd-9693-49a5-91cc-00dc993b2558.png)
I'm working on Subtitle Edit 3.5.16

**Comment by juliacaldana** [comment]
I updated Subtitle Edit to the 3.6.1 version and I get the same message:
![image](https://user-images.githubusercontent.com/92887499/143916037-f1cfafc6-ef52-4812-b1a3-320dfcfcffb5.png)

After I click "Repetir" and then "OK", I get this one:
![image](https://user-images.githubusercontent.com/92887499/143916213-17d2c3df-c4ef-4b24-ae2b-7a0382a7d2a3.png)

After I click "Anular", I get the following:
![image](https://user-images.githubusercontent.com/92887499/143916284-f8fd8657-e522-4ffb-bbff-6378f92a81a1.png)
and finally this one:
![image](https://user-images.githubusercontent.com/92887499/143916346-a94c5273-397c-4200-bd60-85410239c89c.png)

**Comment by niksedk** [comment]
Are you using word 64-bit?

I don't have Word anymore, so I cannot look at this...

**Comment by juliacaldana** [comment]
Yeah, the one installed here (it came with the computer already) is 64b-bit:
![image](https://user-images.githubusercontent.com/92887499/143918681-2316800c-be25-428e-b66f-d9905474b42f.png)

I actually can't use Word actively because my trial period is over, but I know some fellow subtitlers who are in the same situation (have Microsoft Office downloaded but can't use it because they don't have a License) and the Subtitle Edit Plugin works just fine so I don't think that's the problem.
