### ISSUE TITLE
[Bug] Can no longer temporarily make 3+ lines in the subtitle "text" window

### ISSUE THREAD

**Issue by ghost** [SubtitleEdit/subtitleedit#5409]
In previous versions, I could make 3+ lines in the subtitle "text" window. I updated and screwed myself, basically, because now it won't let me do this. The only annoying hack I could find is to enter source mode and do it from there (F2). If this was intentional, why did you do this? A bad decision I think.

It's useful to be able to create 3+ lines when you're deciding where line breaks should go, or you're tweaking where they should be. Now I have to take an extra step to be able to do this. And no, I don't want to edit my settings and set auto break to three lines, I want to keep it at two like standard subtitles. 

Please help.

**Comment by OmrSi** [comment]
Check this out https://github.com/SubtitleEdit/subtitleedit/issues/5313

You can get this back by using the latest beta https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by Apocalypse612** [comment]
Thanks!
