### ISSUE TITLE
[suggestion] transcribe using microsoft Azura in windows 10&11 (or android google in win11)

### ISSUE THREAD

**Issue by amirbahalegharn** [SubtitleEdit/subtitleedit#5419]
hi
it would be great to see this feature which can auto transcribe(make subtitle) videos or audios simply by using Microsoft or google speech-to-text specially now that newest windows 11 support android, users could easily benefit from google assistant.etc as well which means transcribing any video or audio will be easier to do locally. after getting timing+text generated in the subtitle-editor, it will make a world-changing for any individuals to release subs for medias that hasn't gotten any subs in years&decades. 
thanks in advance

**Comment by niksedk** [comment]
SE beta now has speech recognition built-it:

Open a video and click on "Video/audio to text"
![image](https://user-images.githubusercontent.com/1261331/147871741-0d2106f3-ffa9-409a-b40b-e9df5a4ca6d0.png)


https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by amirbahalegharn** [comment]
Thnx man
Wish you & your beloved beings the best in new year
