### ISSUE TITLE
Laggy feeling when offsetting by dragging 

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5432]
3.6.2 official  release, which is okay:
![official](https://user-images.githubusercontent.com/494788/139432356-dc7552ac-d9e3-42c1-a03f-44931fec3ede.gif)

Beta build 202:
![beta](https://user-images.githubusercontent.com/494788/139433122-b02b7c24-9e05-42f1-b285-806648938282.gif)

It seems particularly occur to inactive lines, and always okay for the very first line in the file. Tested using the same Settings.xml.

**Comment by niksedk** [comment]
OK, I think I've found the issue... hopefully. At least it works on my ancient laptop ;)

The list view start-time/duration is now updated after a wave-form-move has ended
Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

How does that work for you, @LeonCheung ?

**Comment by LeonCheung** [comment]
@niksedk Amazing, I think the problem is sovled. 👍 ⚡
