### ISSUE TITLE
Error message - Generate Video with Burned-In Subtitles

### ISSUE THREAD

**Issue by Tanialataniatania** [SubtitleEdit/subtitleedit#5436]
Hola 
when trying to do this I get this error message.
Help?

btw I am new here ;)

![image](https://user-images.githubusercontent.com/93620769/139950112-44962462-0ee8-4cf7-abc8-2aa1ea5ed66d.png)

**Comment by niksedk** [comment]
It's a known bug - will be fixed in next update - which should be out soon :)
