### ISSUE TITLE
[Shortcut Issue] Upper limit

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5438]
For shortcut "set end, next start and go to next", it seems only work if the duration fro next subtitle is set to no more than 69 secs (including the gap before it),

To repeat, try the caption below:

```
1
00:00:00,000 --> 00:00:01,000
A

2
00:00:01,081 --> 00:02:29,093
B
```

Keep the 1st line selected, make sure the video position is at **00:01:10.001**, then use the shortcut.

NOTE: It does work when the video position is no more than **00:01:10.000** in this case.

Can we remove this limit? Because long durations have to exist in many cases, e.g. when working with ASSA effects, or for HI tags like [background noise], [music], etc.

**Comment by niksedk** [comment]
How is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
@niksedk 👍 Could you remove the limit for the other two set-end-related shortcuts as well? I mean:

```
set end, offset the rest
set end, offset the rest and go to next
```

Thx!
