### ISSUE TITLE
Regex issue with build 281

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5441]
Error messge:
![regex replace](https://user-images.githubusercontent.com/494788/140064262-37f2424e-e11f-4fdc-b3c8-5fc4274cfabc.png)

It doesn't pop up every time. Btw, I was trying to replace things with simple regex $1, and it doesn't work either with Multiple Place or Ctrl H.

**Comment by niksedk** [comment]
I cound not re-create this... tried to fix the crash anyway: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Thanks for the fix here. BTW, Could you check the other two set-end-related shortcuts in issue #5438? I think they might be related. These two shortcuts didn't work with long durations either. Tested in build 286.

**Comment by LeonCheung** [comment]
Thanks for both fixes. closing.
