### ISSUE TITLE
About subtitle form NHK plus

### ISSUE THREAD

**Issue by snakeLo** [SubtitleEdit/subtitleedit#5442]
I downloaded a subttile from NHK plus from a mpd file and it merged as a mp4 file. The format of the subtitle is ttml as it shows in the mpd file.
I tried changing the extension from mp4 to txt and dragging the file into the SubtitleEdit, and it only format the text but without the timecodes.
I noticed the timecodes have the initial "454416:", but when I deleted and replace it with blank, SE wouldn't recognize the subtitle.
Could someone help solve this one?

Thanks

[subtitle.zip](https://github.com/SubtitleEdit/subtitleedit/files/7467751/subtitle.zip)

**Comment by niksedk** [comment]
Hi @snakeLo,

Try to open the "mpdVideo.txt" (mp4 file) with latest beta - should now work somewhat: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

SE now ignores hours > 99

**Comment by snakeLo** [comment]
Thank you so much
That's fast
