### ISSUE TITLE
Angle can't greater than 270°

### ISSUE THREAD

**Issue by nyakohub** [SubtitleEdit/subtitleedit#5443]
Some subtitle has angle more than 270°
When I import such subtitles, the program will report an error

**Comment by niksedk** [comment]
OK, I've tried to fix the issue... how is this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

(a screenshot + sample file is always nice)

**Comment by nyakohub** [comment]
Thanks, I think it has been fixed
