### ISSUE TITLE
Syntax coloring updating issue 

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5445]
https://user-images.githubusercontent.com/494788/140455659-dbad990b-4060-4c8a-95bf-09a22aac17ac.mp4

After disabling the two options (others are fine), it only updates while the window size changed. Tested with another notebook, the same problem. Another issue here is some gap cannot update timely until clicking on the list view again. (from 01:16)

**Comment by niksedk** [comment]
OK, thx - I see at least some of the problem... how is this:https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
Cool!
