### ISSUE TITLE
Gap update issue with a shortcut

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5446]
For this shortcut: **set end minus gap, go to next, and start next here** The very similar issue with the syntax coloring issue mentioned in #5445, because it will update as well after window size changed. 

https://user-images.githubusercontent.com/494788/140472184-71ff47e1-dc10-4616-995c-542a10f7c8c0.mp4

**Comment by niksedk** [comment]
Thx, yes that was buggy, hopefully better here?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Yes, it works well now. Thx!
