### ISSUE TITLE
Correct Sentences that starts directly after previous sentence without Space

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#5449]
Hi!

I've found a hell lot of bad subs last week/s (this is about .SRT, but might concern all kinds of subs).

Is there a way in SE to Auto-Fix or to Search for Sentences that starts directly after previous sentence without a Space first, like this:

You good with this?It is what it is.
(Should be in Two different lines with Dash first)

Drop your weapon!LAPD!
(Should be in Two different lines with Dash first)

All right. Three.Here we come!
(Should be in Two different lines with Dash first)

So, this concerns both   ?   and   !   and also   .   when there's a word starting with a Capital directly behind one of those characters.
(There are probably many more characters that could be involved, but those three are the most common.)

Any fix available ?!

**Comment by LeonCheung** [comment]
Go to **Edit** > **Multiple replace...**, add a regular expression like this:

find what: `^(.+)(\.|\?|\!)(\w+)`
replace with: `-$1$2\n-$3`

![image](https://user-images.githubusercontent.com/494788/140616015-b0550eac-bb78-43c3-9eee-d23336c562dd.png)

**Comment by Minherre** [comment]
Thank you a LOT!

I've never really understood/looked into Regular Expressions, but it worked just FINE!

(It was SWAT 5x5 CAKES Sub that was messed up yesterday, but now it seems just fine, and this will Really be Useful in the future too, so Thanx Again!)

**Comment by cyzs233** [comment]
@niksedk 
Currently, this is a small fix in **AUTO break**.
![Untitled](https://user-images.githubusercontent.com/25927091/179879625-0d156238-ee3a-44c2-9d2d-9b69dafe8432.png)

It should detect "end of sentence" and be able to break after them.
![GIF 20-07-2022 09-59-40](https://user-images.githubusercontent.com/25927091/179879801-469277bd-5f71-4d19-9a2a-86511a59d9bb.gif)
