### ISSUE TITLE
CLI - Delete lines

### ISSUE THREAD

**Issue by sweetngx** [SubtitleEdit/subtitleedit#5450]
There are lines in my subtitle file that need to be deleted, as in the Interface, the "Delete lines" feature is unfortunately not available in the command line. Is there a way to do my request with command line?
I want lines containing some words to be delete

**Comment by niksedk** [comment]
Beta updated with "/deletecontains:WORD": https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip
