### ISSUE TITLE
Navigating to the start/end of the file in list view from the text box

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#5452]
3.6.2 NEXT beta 282.
Before the recent list view changes, it was possible, while in the text box, to press alt+home, or alt+end, and navigate to the first or last subtitle in the file in list view, while maintaining focus on the text box. Since the changes, this is no longer possible.
I'm sure it depended somehow on a previous behavior, and so doesn't work for a reason, but I'd like to at least request keyboard shortcuts for something that would function the same way, since currently I have to press a key combination to shift the focus to list view, press home and then press the key combination to shift the focus back to the text box.

**Comment by niksedk** [comment]
What about Ctrl+Home / Ctrl+End ?
