### ISSUE TITLE
[Feature request] "Column, insert text" for the original subtitle column

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#5453]
Occasionally you have two sets of subtitles for the same video in two different languages, but they're divided into individual subtitles differently, and you have to adjust one to match the other. For instance, something that's one subtitle with two lines in one file could be two one-line subtitles in the other.
The "Column, insert text" keyboard shortcut is useful for this, if you want to add a line to the translation file and shift every other subtitle down by one. However, there's currently no simple way of doing this in the source file. I essentially have to add a new line ("Insert after"), set its start time and duration to zero, shift the focus back to list view and use "Column, delete text and shift up". So, it would be great if there would be a keyboard shortcut similar to "Column, insert text" for the original subtitle as well.

**Comment by LeonCheung** [comment]
Actually, there are many things you can't do specifically for the original file, LOL. Currently, my workaround is to set a shortcut for "**Switch original and translation**". Say, if you want to apply "Column, insert text" to the original file, you can switch them first, apply, and then switch back.

**Comment by darnn** [comment]
Oh yeah, I would love to have that too, in general. I already do this with an additional program, essentially. Although in this case it wouldn't introduce the other "column, insert text" per se anyway, and I'd rather have a shortcut for the function itself rather than for, like, insert after + delete text and shift up.

Also, I did try to use switch original and translation for this, but it was a while ago, and I stopped because at a certain point it affected the actual original file in some undesirable way, but I don't remember how exactly.

**Comment by cyzs233** [comment]
I had proposed a solution to your problem, but it seems you have rejected yourself. #5778
The current Translator mode is internally linked by timestamps, which means independent editing on the translation&original is not possible right now. 
You could try "Switch original and translation", but I suggest you make a backup of your files before you smash the button. #5779

**Comment by darnn** [comment]
I assume it can be achieved by a number of programs, most commonly AutoHotKey, but I want to code as little as possible, so I just do it using this:
http://www.16software.com/breevy/

If I want the equivalent of a macro, I just write out the inputs I need in SE, and assign them to, e.g., " -- ", that is, space, minus, minus, space. So when I type that in the textbox (and it's something I wouldn't accidentally type other any other circumstance) it executes the "macro".

But yeah, I'd still love to just have specific shortcuts for this.
