### ISSUE TITLE
Gap synstax

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5454]
Build 309 and older:

Sometimes, gaps with the same length can be colored differently.
![image](https://user-images.githubusercontent.com/494788/140719188-56c1c70a-12d8-44db-adfa-d2d38c0f5ba5.png)

**Comment by LeonCheung** [comment]
@niksedk Hi, tested with build 323:

https://user-images.githubusercontent.com/494788/140960086-55bf7c60-230c-4ed3-ba55-62fc9194ddb1.mp4

**Comment by niksedk** [comment]
Is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Perfect. Thx. Closing.
