### ISSUE TITLE
Change casing (to normal casing only change all upper case lines)

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#5459]
Hi, when a line is selected and I choose [Selected lines] -> [Change casing for selected lines...] on right click and set [Normal casing. Sentences begin with upper letter.] with option [Only change all upper case lines.] enabled at a line like this,

- CAUTION. HEART RATE HIGH.
- Come on, boy.

nothing happens.

I expect the first line is treated as one line in the dialog with two (or more) lines.
So, the result should be

- Caution. Heart rate high.
- Come on, boy.

Can you fix this please?

Used version 3.6.2 NEXT, beta 282

**Comment by darnn** [comment]
When I copy the same text and repeat the process you describe, it changes the casing as expected. Can you attach the file this happens with? Maybe there are some hidden characters in the all caps line or something?

**Comment by taxen** [comment]
I think '-' to show a dialog was changed into dots in above example.
Can you check this one instead? Thank you.

```
- CAUTION. HEART RATE HIGH.
- Come on, boy.

```

**Comment by taxen** [comment]
It's weird. Both dialog and just two lines block are not changed on my side.
Here is my sample srt (please change .TXT to .SRT 
[test.txt](https://github.com/SubtitleEdit/subtitleedit/files/7504651/test.txt)
).

**Comment by darnn** [comment]
Hmm. Same here. I'm not sure how this was working before, but I do think it should at least be a separate option (that is, one for only change all upper case lines, and one for only change all upper case subtitles).
And to be fair, I've never encountered a situation like this, where there's a mix of both in one subtitle.
