### ISSUE TITLE
Auto-load audio file

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5465]
When loading a sub file, the video of the same name can be automatically loaded, but it will not if I only have the audio in hand. Not sure this is a little bug or something. FYI.

**Comment by niksedk** [comment]
Fixed in 6d1949a846592303492c1da779830ecee1e8de3f

**Comment by LeonCheung** [comment]
@niksedk Could you also solve a similar issue when importing plain text (.txt) files? It seems to work with video only. Thanks!

**Comment by LeonCheung** [comment]
Hi, it doesn't work now with the latest beta...

**Comment by niksedk** [comment]
Hm, works fine here...

**Comment by LeonCheung** [comment]
Okay, a screencast with the latest beta (with default settings.xml):

https://user-images.githubusercontent.com/494788/142185144-77322b99-9028-44a1-84c7-e7845cfb1974.mp4

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip
