### ISSUE TITLE
dotNET 6 multi platform targets

### ISSUE THREAD

**Issue by systemcrash** [SubtitleEdit/subtitleedit#5466]
Hi! Thanks for the greatest subtitle editor :heart: 

I've always had to run a VM or have some windows system to run SE. But MS now released [.NET 6, and MAUI is coming soon](https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/) - I wonder whether it would be just a question of re-compiling so it would work on e.g. Linux and macOS? ( "We are now targeting early Q2 of 2022 for .NET MAUI GA." )

If MS deliver, it would be nice to have a binary for macOS, among others.

**Comment by niksedk** [comment]
Sorry, it's not possible to convert Winforms to MAUI, but MAUI does sound interesting.
