### ISSUE TITLE
An error message

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5467]
Not sure if it's useful, I just encountered this with latest official release:
![error msg](https://user-images.githubusercontent.com/494788/141333799-b8a0b8a4-dc45-40b2-825d-c3b4a22e61cf.png)

Not sure how it's happened. I think I just downloaded the portable version and unzip it to an existing SE directory.

**Comment by niksedk** [comment]
Can you re-create it?

**Comment by LeonCheung** [comment]
Not sure, still trying to...

**Comment by niksedk** [comment]
Will close this for now... I think it's fixed in latest src :)
