### ISSUE TITLE
Yet another error msg

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5470]
How to repeat:

1. Load a video or audio to SE video player;
2. Delete source media;
3. Click to add waveform, then it pops up, though media can still be played in the player. 

![image](https://user-images.githubusercontent.com/494788/141470389-28029bb1-c737-48b6-bdc8-b3870366ae9d.png)

**Comment by LeonCheung** [comment]
I think this needs a final fix. Continue with the three steps above:

4. In the latest beta, when clicking to add waveform, an error would pop up if we click the **Cancel** button:
5. 
![image](https://user-images.githubusercontent.com/494788/142228167-5a7fefeb-9fc8-4b8c-9a2a-95806d06eb24.png)

**Comment by niksedk** [comment]
thx - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Cool fix, as well as the Textbox resize. Thx!
