### ISSUE TITLE
Application error while using nOCR

### ISSUE THREAD

**Issue by signedout** [SubtitleEdit/subtitleedit#5471]
I'm getting this error with latest SubtitleEdit.

[Link to the image in imgur](https://i.imgur.com/iVUrT89.png)

I used the "import images" option, imported some images, selected "ocr via nOCR" then I got the error a few seconds after Starting OCR.

**Comment by niksedk** [comment]
OK, can you re-create this? 
If yes, could you add a .zip file with the image/subtitle that causes this error?

**Comment by signedout** [comment]
I can recreate it. I'm loading a list of images, and it breaks at the first one. If I load the first one only, it doesn't break. So I'm attaching a zip file with all the images.

[Here it is.](https://hostb.org/1E75)

**Comment by niksedk** [comment]
Thx for the files - should hopefully work now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

That subtitle is somewhat difficult to OCR...

**Comment by signedout** [comment]
Thanks, works now! Here Tesseract 5 seems to be giving better immediate results, but they'll still need manual fixing. Anyway, that's a story for another time.
