### ISSUE TITLE
Generate burn-in subs issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5472]
Generate burn-in subs can only generate MKV successfully since official release 3.6.3.

**Comment by niksedk** [comment]
Works fine here for me... can you provide steps and screenshots? What happens when you save in .mp4 format ?

**Comment by LeonCheung** [comment]
I think the problem is caused by the dot before "x264" in the default filename.

**Comment by LeonCheung** [comment]
Okay, something weird here:

https://user-images.githubusercontent.com/494788/141668750-862dbfb4-b79f-431e-b4e4-6cc4aa766036.mp4

**Comment by niksedk** [comment]
Hm yes... avoiding "." seems to solve this, right?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Cool fix!
