### ISSUE TITLE
Open media as subtitle

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5473]
When accidentally loading a video/audio file (without subtitle track) as a subtle (or by dragging into the list view), SE will get stuck for seconds (even 10+ seconds with larger files) before saying "No subtitle found".

**Comment by LeonCheung** [comment]
A file for testing.
[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/7533669/test.zip)

**Comment by niksedk** [comment]
thx for another nice bug report :)

I think 3.6.4 will be out soonish ;)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
@niksedk Hmm, I think audio format like mp3 also needs to be excluded. Currently, it seems SE tries to parse mp3 files as unknown subtitles for seconds.
