### ISSUE TITLE
{\an8} tag added to TTML subtitles

### ISSUE THREAD

**Issue by musicadi** [SubtitleEdit/subtitleedit#5474]
Hi,

An {\an8} tag is being added in the subtitle for all lines which contain a specific region.

Subtitle Edit 3.6.3
Windows 10

Here is a sample code:

`<?xml version="1.0" encoding="UTF-8"?>
<tt xml:lang="en" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" ttp:profile="http://www.netflix.com/ns/ttml/profile/nflx-tt" ttp:frameRate="24" ttp:frameRateMultiplier="1000 1001" ttp:dropMode="nonDrop" ttp:timeBase="smpte">
  <head>
    <metadata>
      <ttm:title>Title</ttm:title>
    </metadata>
    <styling>
      <style xml:id="style.default" tts:fontFamily="Arial" tts:fontSize="100%" tts:fontStyle="normal" tts:fontWeight="normal" tts:backgroundColor="transparent" tts:color="white"/>
    </styling>
    <layout>
      <region xml:id="region.after.center" tts:displayAlign="after" tts:textAlign="center" tts:origin="10% 10%" tts:extent="80% 80%"/>
      <region xml:id="region.before.center" tts:displayAlign="before" tts:textAlign="center" tts:origin="10% 10%" tts:extent="80% 80%"/>
    </layout>
  </head>
  <body>
    <div>
      <p style="style.default" region="region.after.center" begin="01:00:04:21" end="01:00:07:07">region.after.center</p>
      <p style="style.default" region="region.before.center" begin="01:00:07:16" end="01:00:09:07">region.before.center</p>
    </div>
  </body>
</tt>`

**Comment by niksedk** [comment]
`{\an8}` is added when detecting top alignment in TTML. That's a feature.

Could you attach subtitle if these `{\an8}` lines are not top aligned?

**Comment by musicadi** [comment]
Hi, I put two subtitle lines in the sample code. First is with tts:displayAlign="after", the second with tts:displayAlign="before".

After exporting the file, the tags remain part of the subtitle text, so they are not actually exported as tags, and I'm not sure if this is intended

**Comment by OmrSi** [comment]
@musicadi It would be much easier to understand the issue if you attach an actual file.
You can just leave a couple of lines and change the text if you want.

Change the extension to `.txt` and attach it directly here.
Or you can send it to @niksedk via email.

**Comment by musicadi** [comment]
@OmrSi Thanks, here is the file

[TTML-test.txt](https://github.com/SubtitleEdit/subtitleedit/files/7533703/TTML-test.txt)

**Comment by niksedk** [comment]
Thx for the file :)

The second subtitle is top aligned, so that's on purpose that SE adds the `{\an8}` tag.

**Comment by musicadi** [comment]
@niksedk Yes, I understand, but when exporting, it keeps the tag in the subtitle text, instead of adding it as a paragraph tag

**Comment by niksedk** [comment]
OK, exporting how? To what format?

**Comment by musicadi** [comment]
I only tested with .dfxp extension, and it looks like the issue is there when saving to these formats:
- DFXP Basic (.dfxp)
- Timed Text draft 2006-04 Ooyala (.dfxp)

When saved in Netflix Timed Text (.dfxp), the tag is correctly saved.

**Comment by niksedk** [comment]
These formats do not support alignment in SE...

**Comment by larsk2** [comment]
It also adds to the text when exporting as srt

**Comment by niksedk** [comment]
> It also adds to the text when exporting as srt

That's a feature :)
Most video players and converters supports alignment tags for srt too.
If you don't want them - you can try to select the wanted lines in the list view, right click, remove formatting - alignment.

**Comment by larsk2** [comment]
> > It also adds to the text when exporting as srt
> 
> That's a feature :) **Most video players and converters supports alignment tags for srt too**. If you don't want them - you can try to select the wanted lines in the list view, right click, remove formatting - alignment.

Absolutely correct :) Works well with VLC and Plex, thanks a lot.

**Comment by musicadi** [comment]
> These formats do not support alignment in SE...

Oh, I see, thank you! Is it possible to add support for this?
