### ISSUE TITLE
Generate blank video - further ideas.

### ISSUE THREAD

**Issue by ThomasLeigh** [SubtitleEdit/subtitleedit#5478]
1. For me this is a fantastic feature because I work with many podcasts, creating subtitles for them - and often they are published on video platforms like YouTube, in a form of a video displaying a single still image while playing subtitled audio. This feature of generating blank video would be of a great help if it could **allow to add such a single image as background** (alongside already existing checkered image or solid color). Would You be willing to include such an ability?

2. It would also be useful to include the ability to **read the length of the audio file currently opened within the app to automatically put it as the blank video duration**. What do You think?

**Comment by niksedk** [comment]
OK, something like this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by ThomasLeigh** [comment]
> OK, something like this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

Exactly. **Thank You very much**, I have not expected such a lighting-quick response :) !
