### ISSUE TITLE
Double clicking on subtitle jumps to end of video

### ISSUE THREAD

**Issue by musicadi** [SubtitleEdit/subtitleedit#5479]
Hi,

One more issue I just found.

When double clicking on a subtitle line, the video player should jump to that specific timecode, but instead it jumps to the end of the video file (tested with both MPV and VLC)

Formats I used when experiencing this:

Video codec: H.264 (x264)
Audio codec: AAC (CoreAudio), Stereo
Container: .mp4
Timecode: SMPTE
Frame rate: 23.976 FPS

Subtitle formats: Timed Text 1.0 (.xml), Netflix Timed Text (.dfxp).

Unfortunately I am not allowed to share the files in question, but I hope you can reproduce the issue based on this data.

**Comment by darnn** [comment]
What's the timecode of subtitle you clicked on, and what's the length of the video? This only happens to me when I, for instance, have a file that's 40 minutes long, but the subtitles all start at 01:00:00:00, so naturally, for a 40-minute file, any subtitle just goes to the end. And then I use set video offset and it's okay, but you get the idea.

**Comment by LeonCheung** [comment]
I agree that this is an unwanted jump. So, when double-clicking on a line that's beyond the video length (either earlier or later), nothing should happen except either showing a pop-up message like "out of range", and/or a log on the status bar. But it should only apply when double-clicking behavior is set to the following:

![image](https://user-images.githubusercontent.com/494788/141709296-19b97018-263f-42f7-bfdf-1534b7dc63d1.png)

(And suppose you want to use the current behavior as a quick and dirty trick to jump to video start/end, maybe it could still be done by holding Shift or something if it makes any sense? Not sure if it's wanted though.)

**Comment by musicadi** [comment]
@darnn timecode format is SMPTE and all subtitles have the correct timing

**Comment by darnn** [comment]
So can you reproduce this with a different subtitle file, or a different video file, or both?

**Comment by musicadi** [comment]
@LeonCheung actually, I would like the video to jump to the position of the subtitle I double clicked on. It's setup correctly, but the video actually jumps to the end, no matter what subtitle line I double click on

**Comment by musicadi** [comment]
@darnn yes, same behaviour with all videos/subtitles which have the above format

**Comment by niksedk** [comment]
What video player do you use inside SE? 
Try "mpv" - go to Options - Settings - Video player.

**Comment by musicadi** [comment]
@niksedk I'm using mpv. Also, the subtitle don't even show up in the preview window.

Everything is on a fresh Windows 10 install, with no other software except SE installed.

**Comment by niksedk** [comment]
Could you attach the subtitle without texts?  
To delete all text: Select all in list view (Ctrl+a), right click, column, delete text

**Comment by musicadi** [comment]
So, I did some more testing, and it appears that the issue is related to the subtitle file.

Attaching you two files. One is working, one isn'
[TTML-test-subtitles NOT working.txt](https://github.com/SubtitleEdit/subtitleedit/files/7539947/TTML-test-subtitles.NOT.working.txt)
[TTML-test-subtitles working.txt](https://github.com/SubtitleEdit/subtitleedit/files/7539948/TTML-test-subtitles.working.txt)
t.

**Comment by niksedk** [comment]
What's the duration of the video file? The not working texts are starting after 1 hours. 
Perhaps you need to Video - Set video offset: 

![image](https://user-images.githubusercontent.com/1261331/141817103-3791d952-3f6b-40da-8e16-a0b083031405.png)

**Comment by musicadi** [comment]
@niksedk Oops, sorry, I missed that :)

However, starting at 01:00:00:00 is actually the SMPTE standard, so maybe this should be set as the default timecode start?

**Comment by musicadi** [comment]
Ok, confirming that all is good now, as soon as went to Video - Set video offset and set it to 01:00:00:00 (keeping the existing time codes).

However, I have to do this with every file, because since starting the time code at 1 hour is the industry standard, all the subtitle files I'm working on start at 1 hour :)

Is it possible to add a setting where we can choose the default time code start? This could be added in Options - General, right after the "Time code mode" option.

Thank you for your time!

**Comment by darnn** [comment]
I have like four or five regular ones that I always put in by hand, so I wouldn't mind the option of saving several timecodes to choose from.

**Comment by niksedk** [comment]
> 
> 
> I have like four or five regular ones that I always put in by hand, so I wouldn't mind the option of saving several timecodes to choose from.

OK, what are those? 10 hours, 1 hours and ?

**Comment by darnn** [comment]
I think they're very specific to the files I get, but, for instance:
09:57:36:00
09:58:30:00
09:59:30:00
09:59:20:00
00:59:30:00
00:59:57:00
And so on. I'd just like to be able to put in a few presets that I determine myself. But if that's too much work, that's okay too.

**Comment by musicadi** [comment]
@OmrSi Good idea about saving the latest entered value

**Comment by niksedk** [comment]
OK, how does this work?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

Should remember last one... and actually the last 10 offsets.

**Comment by darnn** [comment]
Works great so far!

**Comment by musicadi** [comment]
> OK, how does this work? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip
> 
> Should remember last one... and actually the last 10 offsets.

Cool, thank you! I didn't get to test it, but I'm sure it will work!

All the best!

**Comment by musicadi** [comment]
@niksedk Hi, looks like in the beta the "Keep existing time codes" option has no effect anymore, under "Set video offset".

Every time I change the value, the time codes of the subtitles are changing, even when I don't change the value, and just hit OK

**Comment by niksedk** [comment]
@musicadi: works fine for me... screenshots? Also, probably a new issue :)

**Comment by musicadi** [comment]
@niksedk It seems that it only happens when video has SMPTE timing, but the "SMPTE timing" option under "Video" is unchecked.

**Comment by niksedk** [comment]
`Set video offset` should have nothing to do with video frame rate... screenshots?

**Comment by musicadi** [comment]
https://user-images.githubusercontent.com/17009061/143076011-948b0bad-066d-4975-9bdf-1c2cfc6beab0.mov

**Comment by niksedk** [comment]
thx for the video :)

I've tried to fix the issue with video offset here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip
How is that?

**Comment by musicadi** [comment]
@niksedk Thank you! Looks good!
