### ISSUE TITLE
Sytax coloring issue for overlaps

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5482]
Start/end time overlap syntax coloring didn't update well when tweaking time via **waveform**. Build 19.

**Comment by niksedk** [comment]
Thx - I have tested this a lot, so I was sure it was working... well, hopefully working now :)
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Looking good! Thanks.
