### ISSUE TITLE
Linux - Hebrew text is reversed

### ISSUE THREAD

**Issue by zorbama** [SubtitleEdit/subtitleedit#5485]
# Steps

1. In Options > Settings > Appearance, change the display font to a font that supports Hebrew characters, e.g. Arial.
2. Load a subtitle file with Hebrew text.

# Expected Result

The text should be displayed correctly, e.g. `שלום`

# Actual Result

* The text's letter orders is reversed, e.g. `םולש`
* This happens in both RTL mode and regular mode.

See attached screenshot.

Tested on Linux Mint 20.2 and Ubuntu 21.10 with SE 3.6.3 and 3.6.2.

I would love to be able to use SE on Linux for work, but unfortunately this is a showstopper for me. I'm still using it on Windows for the time being.
Thanks in advance!

![Screenshot from 2021-11-15 19-51-43](https://user-images.githubusercontent.com/6951677/141830994-48d80da3-4d87-4035-a658-ca47da4360db.png)

**Comment by darnn** [comment]
I tried to test this but I have very little experience with Linux. I got as far as creating an Ubuntu VM and installing SE's dependencies and running it. I also installed Hebrew, although I can't seem to actually switch from English at all (it's still alt+shift to do that, right?). Anyway, I thought I would take a shortcut and just paste in some Hebrew text, and then this happened:
![Screenshot from 2021-11-15 14-59-31](https://user-images.githubusercontent.com/19672444/141866374-262bca39-33ca-4b99-ab05-1ac8a3568e59.png)

Then I tried again with a different string containing Hebrew and got this:
![Screenshot from 2021-11-15 15-08-35](https://user-images.githubusercontent.com/19672444/141866980-13e99812-e1be-4f52-8448-c7de661b26a8.png)

**Comment by zorbama** [comment]
I checked again. It seems I have made a mistake. I wasn't testing on the
latest version of SE on Ubuntu, but rather on the version provided with the
snap package in the software center, which was quite outdated.

I downloaded the latest version from Github and tried again. Typing in
Hebrew and copying/pasting doesn't seem to write anything, although the
program appears to register that a change has occurred in the file. After a
while, SE just froze and had to be force-quit. I didn't get the errors
above.

On Linux Mint, the behavior is as I described on the latest version. Sorry
about the confusion.

For changing the keyboard layout in Ubuntu, I believe the default shortcut
is now Win+Space, however I'm not sure. You can change it in the keyboard
section of the system settings.

**Comment by zorbama** [comment]
Opening a file in Ubuntu seems to reproduce the text reversal issue, but the text cannot be edited. Attaching file (Github won't let me share a .srt file, so I added the .txt at the end)

[test.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/7546386/test.srt.txt)
