### ISSUE TITLE
Shot changes don't get adjusted accordingly when SMPTE timing mode is activated

### ISSUE THREAD

**Issue by kmekme** [SubtitleEdit/subtitleedit#5486]
Hi,

Before I activate SMPTE timing mode, the shot change indicators on the waveform are accurate, but after activating it, they don't get adjusted accordingly and become inaccurate. Is there a way to solve this problem?

Also, now that SE supports saving in HH:MM:SS:FF format, is there also a way to convert a subtitle file with HH:MM:SS:MS format into HH:MM:SS:FF? I've been going through the settings and menu options, but I couldn't find a way to do this.

Thanks in advance!

**Comment by OmrSi** [comment]
@niksedk Is it enough to divide all shots by 1.001 like what's done on the subtitles or is it a bit trickier?

**Comment by niksedk** [comment]
> 
> 
> @niksedk Is it enough to divide all shots by 1.001 like what's done on the subtitles or is it a bit trickier?

Yes, it should be the same.

**Comment by OmrSi** [comment]
Okay, I'll give it a shot.

**Comment by niksedk** [comment]
thx for the fix @OmrSi, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by kmekme** [comment]
Thanks for the fix @OmrSi and @niksedk!
