### ISSUE TITLE
Problem with Style Sub Station Alpha

### ISSUE THREAD

**Issue by Plooton99** [SubtitleEdit/subtitleedit#5489]
Application crash during import of styles.
![Capture2](https://user-images.githubusercontent.com/94461878/141999539-a0edf1fc-5be2-4508-b19f-78304a08dda6.JPG)
Or other feature manipulation.
![Capture1](https://user-images.githubusercontent.com/94461878/141999687-30043e9c-9e89-4cc1-a2fc-4e4da326642a.JPG)

**Comment by niksedk** [comment]
Could the attach the subtitle (GitHub accepts .zip files)

**Comment by niksedk** [comment]
Could you also try the latest beta - the second issue has been fixed: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip
