### ISSUE TITLE
Error while merge lines with same text

### ISSUE THREAD

**Issue by gantangpedia** [SubtitleEdit/subtitleedit#5490]
While on merge lines with same text, after deselecting one of the lines, if you select other lines it throws an error.
![Error while merge lines with same text](https://user-images.githubusercontent.com/78692591/142082311-62b9b476-0311-4a07-95f9-5e7a4e8992be.png)

**Comment by niksedk** [comment]
thx for the bug report :)
Should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by gantangpedia** [comment]
wow that was fast. thank you so much for this.
