### ISSUE TITLE
Copy Text error

### ISSUE THREAD

**Issue by Charvelx04** [SubtitleEdit/subtitleedit#5491]
Greetings.

So.. I keep coming across this when I select any text to copy. All I have to do is highlight the text, and press CTRL C.

If there's any other info you need, please let me know.

![copyerror](https://user-images.githubusercontent.com/35577096/142084913-e5b11dcd-a857-401f-9d8d-08227a863d7c.jpg)

**Comment by niksedk** [comment]
What OS are you using?

**Comment by Charvelx04** [comment]
Windows 11 Pro, 21H2, 22000.346.

**Comment by niksedk** [comment]
OK, I just use a standard ms method - it seems that some other application is locking the clip-board.
I've added some retries and a more friendly error message: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by Charvelx04** [comment]
I'll keep you posted if anything regresses.

Thank you.
