### ISSUE TITLE
Textbox width issue in translation mode

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5492]
https://user-images.githubusercontent.com/494788/142136674-93ad1bf7-df0a-47d7-aa3c-8f3eb8000327.mp4

In the video above, I toggled Center in the Appearance setting. However, the issue is the same with the default setting:

![d](https://user-images.githubusercontent.com/494788/142136804-67a99b8a-6ad3-4d9c-986f-53ad22c20383.png)

**Comment by niksedk** [comment]
Hm, I cannot re-create this here.

**Comment by LeonCheung** [comment]
True, it doesn't occur every time. but I often see that for months I guess, regardless the builds...  Will try to find a way to reproduce it.

**Comment by LeonCheung** [comment]
Hmm, it seems to update only when changing the whole window position or size:

https://user-images.githubusercontent.com/494788/142186568-bfd39b60-684b-41d6-bb60-89f547532619.mp4

Tested on one PC and one laptop.

**Comment by niksedk** [comment]
thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Hmm, I think it's fixed partially. I mean, when toggling on and off the video player, it works well now. But when trying to change the video player size, it is still the same:

![image](https://user-images.githubusercontent.com/494788/142201873-cc57fe8e-e7ce-4fdf-9c85-5f65c53fedee.png)
