### ISSUE TITLE
Audio waveform cannot be fixed as in YouTube

### ISSUE THREAD

**Issue by haripetrov** [SubtitleEdit/subtitleedit#5494]
I cannot find a way the line that is showing what currently is playing (in the waveform window) to be fixed in the middle and the text to move according it (in the same as in YouTube subtitle editor). I just want this line to be centered and the text to move so that I can follow easily the previous and the next subtitle.
I don't know if I am missing something or just this functionality is not available at the moment?

**Comment by niksedk** [comment]
Is this what you're looking for?
![image](https://user-images.githubusercontent.com/1261331/142202013-781d30f7-7170-44f7-9b2b-688d8c4055c4.png)

**Comment by haripetrov** [comment]
Yes, strangely the last time didn't work but now after I restarted the program is working as expected.
