### ISSUE TITLE
Virus In Beta Detected

### ISSUE THREAD

**Issue by pzprovi** [SubtitleEdit/subtitleedit#5495]
https://github-releases.githubusercontent.com/1647____5/8b49fe73-e5_____26?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA___%2F20211117%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20____0246Z&X-Amz-Expires=300&X-Amz-Signature=6c90________8470___67&X-Amz-SignedHeaders=host&actor_id=3409___1&key_id=0&repo_id=164__5&response-content-disposition=attachment%3B%20filename%3DSubtitleEditBeta.zip&response-content-type=application%2Foctet-stream|pid:12__ProcessStart:13281635__4

**Comment by niksedk** [comment]
Try searching before posting... + add some description to your issue

Also, try https://www.virustotal.com/gui/home/upload
