### ISSUE TITLE
.WAV files failing to generate audio waveforms.

### ISSUE THREAD

**Issue by Apocalypse612** [SubtitleEdit/subtitleedit#5499]
Here's the error I've been getting when trying to work with a set of .wav files that were delivered to me for editing. Choosing to ignore the error produces an empty waveform. I'm on SE version 3.6.3.

![image](https://user-images.githubusercontent.com/6374154/142676841-76d8ab86-3ef5-4372-8bc5-26263501df77.png)

**Comment by niksedk** [comment]
thx for the info :)
Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by Apocalypse612** [comment]
You're quick, thank you. The clowns over at Adobe should take notes. :)
