### ISSUE TITLE
Fix unneeded spaces

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#5501]
These cases where there is a number on both sides of the decimal point are not detected as having unneeded spaces.

```
138
00:09:32,947 --> 00:09:37,452
Commander, I'll make my
preliminary adjustments at warp 1 .5
```

**Comment by niksedk** [comment]
Thx - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

I've added that "{number}{space}{period}" is changed to "{number}{period}" - that should hopefully not conflict with common sentences.

**Comment by Ding-adong** [comment]
I was going to raise an issue but then i saw this thread.

You need to reverse this terrible decision as i am getting too many errors. I haven't update SE for a while and now using the latest.

adjustments at warp 1 .5 is not a common error.

Many text have something like "got 3 .45 calibre guns" become 3.45
Many sci fic programmes have droids/robots speaking in number. 4555. 6787. 5643. becomes 4555.6787.5643.

Fix common errors should fix... not **create** common errors.

A simple reg in multiple replace (\d)[ ][.](\d) replace by $1.$2 - 1 .5 to 1.5 should be used by users to fix quirky/rare/weird errors.
