### ISSUE TITLE
some feature for future update

### ISSUE THREAD

**Issue by kucingkembar** [SubtitleEdit/subtitleedit#5503]
hi, sorry for my bad English,
i have some trouble using this software:
1.  when I translated it there 2 subtitles show up, A:inside video box subtitle, and B:under/outside video box subtitle, the problem show up when I tried to translate from a hardcoded sub, the inside video box subtitle is prevent me to read the hardcoded subtitle, how to hide it?
2. I  wish in the future, you can edit text inside the under/outside video box subtitle(point B at point 1), and you can hide(expand collapse with arrow button) the "top part" (from #, start time, to Split line button) and "bottom-left part"  (translate, create adjust), and add minimalist button, so i can read cleary the hardcoded subtitle
thank you, and have a nice day

**Comment by darnn** [comment]
1. In settings->shortcuts->general, there is an item called "toggle preview on video". I believe this is what you're looking for.
2. Here, I'm not sure what you mean, but there are two things that might be relevant: One is you can switch to fullscreen in the video player (settings->shortcuts->video->fullscreen). The other is that you can change the size of the video player in the window:

![se-video-resize 11-20-2021 9-58-46 PM](https://user-images.githubusercontent.com/19672444/142739481-8dd8a081-d2aa-494e-9573-16d13f9f6e8b.gif)

Also, I'm not sure whether you're using mpv as your video engine or not, but that's the preferred one. Settings->video player->video engine->mpv. Try it and see if that helps any.

**Comment by kucingkembar** [comment]
thank you for the reply,
for the first question, I tried to set a shortcut to it and press the button after closing the setting window, but the "inside video box subtitle" is still there

for the second question, the correct word is "minimize", but I think you need to edit a lot of things, so let assume this problem is solved

previously i using "direct show" because it safe to open another video using "MPC-HC" then switch it to "MPC-HC" and the first problem is solved,

thank you
