### ISSUE TITLE
Split line button

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5504]
When setting max lin number to 1, a Split line button will pop up in translation mode and block the text:
![image](https://user-images.githubusercontent.com/494788/142748691-a780ad3d-a655-4adc-a175-04d5cebd95de.png)

**Comment by niksedk** [comment]
I could not re-create this. What steps are needed?

**Comment by LeonCheung** [comment]
1. Setting max line numbers to 1;
2. Enter translation mode.
3. Do something so that "Split line" button should usually appear, like having two very very long lines.
