### ISSUE TITLE
Unwanted Placeholder for hidden modes

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5505]
How to repeat:

1. Hide the mode tabs;
2. Enter a fullscreen mode for media player;
3. Quit fullscreen. 

![image](https://user-images.githubusercontent.com/494788/142754872-3db472b5-2908-48ce-b1f8-09bcef7bb131.png)

**Comment by LeonCheung** [comment]
Two more things might be related a bit:

1. It seems SE can't remember the hide/show state from them after each launch...
2. Btw, is there any chance for #5365, please?

**Comment by niksedk** [comment]
OK, I've tried to make this setting work after fullscreen + remember this setting  + a context menu (right click) for the left 10 pixels to "show/hide video controls":
![image](https://user-images.githubusercontent.com/1261331/142756795-6781e361-fc35-4987-861f-8658ed809321.png)

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

How does that work for you?

**Comment by LeonCheung** [comment]
Cool enough! 🥇

**Comment by ThomasLeigh** [comment]
> a context menu (right click) for the left 10 pixels to "show/hide video controls

**Thank You so so  much :) !!!**
