### ISSUE TITLE
Is it possible to make a Shortcut for times <100ms?

### ISSUE THREAD

**Issue by TubaApollo** [SubtitleEdit/subtitleedit#5506]
Hey, is there a shortcut that can be assigned to times less than 100ms? Or are there shortcuts for these keys?:
![GvC4pR9ZAB](https://user-images.githubusercontent.com/86665265/142776750-767aecbb-14e4-4312-aeae-1043ead26ca7.png)

**Comment by OmrSi** [comment]
Yeah, the naming can be better but here they are:

![image](https://user-images.githubusercontent.com/20923700/142776832-c3b4fc68-9ac1-4b8d-a0fb-af621075bde2.png)

**Comment by TubaApollo** [comment]
Mh, i tried it with them, but thought they are wrong because they skip 1 second forward/back for me, and not the specified time.

**Comment by OmrSi** [comment]
There is a shortcut for 500ms and there are these. Make sure there isn't a conflict between the two.

**Comment by TubaApollo** [comment]
There should be no conflict with other shortcuts, I have also tried different keys because I had already suspected something like that.
![image](https://user-images.githubusercontent.com/86665265/142777030-7509b63b-a00f-47f5-a5c8-050ac0152bdd.png)

**Comment by OmrSi** [comment]
Could you attach your setting file? Should be in `%appdata%/Subtitle Edit` for the installed version, just change the extension to `.txt` and drop it here.

**Comment by TubaApollo** [comment]
Here is the setting file:
[Settings.txt](https://github.com/SubtitleEdit/subtitleedit/files/7577008/Settings.txt)

**Comment by TubaApollo** [comment]
Oh man, it works now, a programme restart helped, thanks for the help.

**Comment by OmrSi** [comment]
Ah. Okay, cool.
