### ISSUE TITLE
Go to next error fails

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5508]
This shortcut doesn't work when the Duration column is hidden.

**Comment by niksedk** [comment]
That's on purpose... the same with gap when it's not visible in the UI.

I guess SE could go to the line + show a description in the status bar, if that will help?

**Comment by LeonCheung** [comment]
Hmm, not sure. What I was trying to do is to do quick check text-related errors only by using F8, and skip other error types, because error types checking would be different among projects. It's not practical to constantly toggle them on and off via the Settings panel because they cannot be governed by the rules profile. So I just thought hiding other columns would help, but apparently not... 😂  (unlike Duration column, Gap works fine for me I guess... 0_o ) 

I can see they are sort of divided into four categories already. Or do you think we should have individual go-to-next error shortcuts for each type? I mean like:
```
Go to next duration error (if enabled)
Go to next text error (if enabled)
Go to next time code error (if enabled)
Go to next gap error (if enabled)
```

![image](https://user-images.githubusercontent.com/494788/142894599-8e0876ed-2bd4-49cf-9a61-395fa649631b.png)


TBH, not sure what's the best solution for now. Maybe it's your call. :)

**Comment by LeonCheung** [comment]
BTW, when the CPS column is hidden, the coloring for CPS errors will be shown in the Duration column instead. Is that also on purpose?

**Comment by niksedk** [comment]
> BTW, when the CPS column is hidden, the coloring for CPS errors will be shown in the Duration column instead. Is that also on purpose?

Yes...
