### ISSUE TITLE
Netflix Quality Check

### ISSUE THREAD

**Issue by PMitsakis** [SubtitleEdit/subtitleedit#5509]
NQC reports false errors when it comes to gaps, as seen in the images below.

![NQC](https://user-images.githubusercontent.com/85220137/142856687-800ba994-21ce-4185-9b16-b7337c25424c.png)

![66](https://user-images.githubusercontent.com/85220137/142856734-54108af0-fb53-433c-a17a-634875d4d756.png)

![192](https://user-images.githubusercontent.com/85220137/142856782-cbe01814-567e-4fe6-99b8-1cfbcd06aaa9.png)

**Comment by OmrSi** [comment]
Could you attach the subtitle file or just the lines that have the issue? 
Change the extension to `.txt` and drop it here.

**Comment by PMitsakis** [comment]
Here it is.
[Affected lines.txt](https://github.com/SubtitleEdit/subtitleedit/files/7581046/Affected.lines.txt)
