### ISSUE TITLE
Can't switch UI language

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5510]
beta build 74.
![error](https://user-images.githubusercontent.com/494788/142856986-f221c4e5-ca6a-4871-a44c-8e5084a1d18c.png)

**Comment by hugok79** [comment]
Thanks Leon for the language file fix

**Comment by niksedk** [comment]
Also, translation xml is now covered by a unit test, so it is auto checked for valid xml + correct culture name :)
