### ISSUE TITLE
Switch positions of textboxes

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5513]
Someone prefers to put "Original Text" column in front of "Text" column, so textboxes should respect their orders, which is expected in most cases. And, sometimes it is indeed convenient to switch the textboxes.

**Comment by LeonCheung** [comment]
I ask this mainly because it can dramatically save the distance you move the mouse between the active caption block and corresponding texts, because normally we are mainly handling with the Translation instead of Original.

![image](https://user-images.githubusercontent.com/494788/142985264-d050dfe8-1441-400e-9f8a-caccfdc30b28.png)

**Comment by darnn** [comment]
Oh yeah, I'd also love to have the ability to switch their positions.

**Comment by niksedk** [comment]
How is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/143009290-ad130486-bdae-4d87-8075-f2d5b07ec43e.png)

**Comment by darnn** [comment]
Working well here!

**Comment by LeonCheung** [comment]
Cool like a charm. 👍

**Comment by LeonCheung** [comment]
Thx for that! Closing.

**Comment by OmrSi** [comment]
Any relation to this https://github.com/SubtitleEdit/subtitleedit/issues/4319?
