### ISSUE TITLE
Toggle mode issue when modes are hidden

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5517]
Not a big deal just... when modes are hidden, it seems that we are still allowed to use shortcut for "**Toggle translate/create/adjust mode**" which may be a bit confusing:

![image](https://user-images.githubusercontent.com/494788/143032784-6c40b6a5-9334-402c-a291-d01ad6192125.png)

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip
