### ISSUE TITLE
Single letter shortcut conflict

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5520]
Say, if I assign letter W and R for Go to previous/next line, normally it works fine, but I just noticed conflicts for the textbox here:
![conf](https://user-images.githubusercontent.com/494788/143050279-55cd4003-e70e-43bd-8c65-d0bb99c0e1bd.gif)

**Comment by niksedk** [comment]
Did you enable this?
![image](https://user-images.githubusercontent.com/1261331/143068113-faa13a26-9e63-4736-b849-6639f99a09fe.png)

**Comment by LeonCheung** [comment]
Sorry but it doesn't solve the issue I mentioned...

**Comment by niksedk** [comment]
Hm, I cannot re-create the issue... any pointers?

**Comment by niksedk** [comment]
Ah, you're in fix common errors?

**Comment by LeonCheung** [comment]
Right.

**Comment by LeonCheung** [comment]
Hi, I think the issue still exists. I mean, it can allow most of shortcuts to work with single letter in Fix Common Errors window, except the two I mentioned.

**Comment by niksedk** [comment]
OK, is it these you mean?
![image](https://user-images.githubusercontent.com/1261331/143186197-a2b92a2a-e2d8-47f7-9e56-87be8df0e6a3.png)

They work fine for me in the text box in "Fix common errors"

**Comment by LeonCheung** [comment]
Yes. Hmm, here is a record with factory settings:

https://user-images.githubusercontent.com/494788/143186892-f1d5a842-8fe5-408e-9074-2d8d9d4390cb.mp4

In my case, there's no way to type letter "r" and "w" in that textbox regardless having that toggle in Settings.

**Comment by niksedk** [comment]
You did not check the check box... or the video did not  register it?

**Comment by LeonCheung** [comment]
this is a one-stop screencast with no cuts. And I've never enabled that checkbox in my life before you mentioned it in this issue report.

**Comment by niksedk** [comment]
Yes, it's a new checkbox - some wanted SE to work one way and some people wanted SE to work another way - hence a setting :)

**Comment by LeonCheung** [comment]
Yes, I know, and it shouldn't be checked in my case, right? 

But the thing is I cannot type the two letters now, as seen in the last video. Is that the expected behavior? 😲 

Again, it **ONLY** occurs in **Fix Common Errors** window, and **ONLY** occurs if single letters are used for **go to previous line** and **go to next line** shortcuts. Other than that, everything is cool.

**Comment by niksedk** [comment]
Ah, I see it know... I thought you had the check box checked.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Well solved, thx!
