### ISSUE TITLE
Textbox vertical scroll bar disappears

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5523]
The vertical scroll bars (for both Original and Translation textboxes) disappear sometimes.

**Comment by niksedk** [comment]
It's a feature.

**Comment by LeonCheung** [comment]
I know. 😂  I mean they disappear when they are supposed to appear:
![image](https://user-images.githubusercontent.com/494788/143075259-e671d394-947d-4e1e-939d-d6886730e195.png)

**Comment by niksedk** [comment]
I think it's controlled by MS... at least if you use the standard text box - or have you enabled syntax coloring?
![image](https://user-images.githubusercontent.com/1261331/143076271-5a6dc7ab-c868-490c-9ab6-7150d35c546b.png)

**Comment by LeonCheung** [comment]
Okay. here is a record with a factory setting:

https://user-images.githubusercontent.com/494788/143076947-84eaf5fc-7748-44e5-bd06-94b7bdd0d50f.mp4

**Comment by niksedk** [comment]
OK, the default textbox in Winforms does not support "auto detect scroll bar" (the rich text box from "use syntax coloring" do).
So the scrollbar is just guessing... it will never be perfect.

I've tried to improve it a bit here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip
Better or worse?

**Comment by niksedk** [comment]
New try... : https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
It seems working a lot better. Now it's all about the update. Sometimes you have to hit break or adjust the panel size to trigger the update:

https://user-images.githubusercontent.com/494788/143162481-9d6c614d-2d62-4855-b667-7a8aa92ebac9.mp4

Not sure if it helps to always show an empty scroll bar that doesn't harm at all:
![image](https://user-images.githubusercontent.com/494788/143162371-a556c2fc-f0ba-4eef-b177-06f5fdc215ed.png)

**Comment by OmrSi** [comment]
Now I'm having cases where it shows up even though it's not needed:

![image](https://user-images.githubusercontent.com/20923700/143474465-5d648059-265a-4996-a498-fcba62c8e8b5.png)
