### ISSUE TITLE
Allow to hide/swap GUI areas.

### ISSUE THREAD

**Issue by ThomasLeigh** [SubtitleEdit/subtitleedit#5529]
I personally don’t use the “Translate/Create/Adjust” area - I don’t know whether I am a rare example of a user or not. For me to be able to hide this area would improve my work due to more space available for the waveform.

Maybe You would be willing to consider to allow users to hide this area - or swap it with the waveform area. Similarly, I suppose, they would be users for whom it would be better to swap the list area with the video preview.

**Comment by LeonCheung** [comment]
See #5505

**Comment by niksedk** [comment]
I do not use the  “Translate/Create/Adjust” area either - just shortcuts :)
