### ISSUE TITLE
emSize error

### ISSUE THREAD

**Issue by Titela79** [SubtitleEdit/subtitleedit#5530]
Hi everyone,

I'm trying to generate a video with burn-in subtitles and I get this error message. Any idea how to solve it?

![image](https://user-images.githubusercontent.com/95028557/143434701-8a1bb20b-e561-4b5a-8003-7e27f903d00c.png)

Thanks!!!

**Comment by Titela79** [comment]
I've solved it, I think, installing the software again.

**Comment by niclainglese** [comment]
I haven't solved..do you have any suggestions?

**Comment by niksedk** [comment]
@niclainglese: Could you try latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
If you still get an error, please post screenshot.

**Comment by niclainglese** [comment]
I haven't solved..There is the same error in a different form.
![image](https://user-images.githubusercontent.com/50542623/151577114-d3dd2183-07ee-4b79-8621-98c5c09c3558.png)

**Comment by niksedk** [comment]
Is the above screenshot latest beta version?
Could you take a screenshot with the details expanded?

**Comment by niclainglese** [comment]
yes, i try latest beta. I insert a screenshot. Tank you
![image](https://user-images.githubusercontent.com/50542623/151675986-f4327e5f-cb0f-46ad-aa3f-135d98df046d.png)

**Comment by niksedk** [comment]
@niclainglese: Could you re-download the latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
and if you still get the error, then copy *all* the details text, and paste it here ?

**Comment by niclainglese** [comment]
I am italian. I followed your instructions and this is the error log:
Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.ArgumentException: '-29' non è un valore valido per 'emSize'. 'emSize' deve essere maggiore di 0 e minore o uguale a System.Single.MaxValue.
Nome parametro: emSize
   in System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   in System.Drawing.Font..ctor(FontFamily family, Single emSize, FontStyle style)
   in Nikse.SubtitleEdit.Forms.Main.GetOptimalSubtitleFontSize(Int32 height) in C:\git\subtitleedit\src\ui\Forms\Main.cs:riga 33035
   in Nikse.SubtitleEdit.Forms.Main.generateVideoWithHardcodedSubtitleToolStripMenuItem_Click(Object sender, EventArgs e) in C:\git\subtitleedit\src\ui\Forms\Main.cs:riga 32996
   in System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   in System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   in System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ToolStrip.WndProc(Message& m)
   in System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4420.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SubtitleEdit
    Versione assembly: 3.6.4.447
    Versione Win32: 3.6.4.447
    Base di codice: file:///C:/Users/utente/AppData/Local/Temp/Rar$EX45.280/SubtitleEdit.exe
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4400.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4360.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
libse
    Versione assembly: 3.6.4.447
    Versione Win32: 3.6.4.447
    Base di codice: file:///C:/Users/utente/AppData/Local/Temp/Rar$EX45.280/libse.DLL
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4455.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Drawing.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.resources/v4.0_4.0.0.0_it_b03f5f7f11d50a3a/System.Drawing.resources.dll
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

**Comment by niksedk** [comment]
Thx for the info :)
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by niclainglese** [comment]
Ok, it works! I'm happy :) thank you

**Comment by niksedk** [comment]
Cool, thx for verifying :)
