### ISSUE TITLE
Remember Column Order

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5531]
After experiencing this #5513 feature for days, it works pretty well. Just one more thing: 

It seems SE remembers the order of textboxes, but doesn't remember the column order. Hence, for users who would like to always swap the default textbox order, they have to reorder the column every time when re-launching SE.

So I think two easy solutions would be:

1. Allow SE to remember the order for all columns;

or,

2. Only swap the two columns according to the textbox order when launching SE every time, which makes a lot more sense.

**Comment by niksedk** [comment]
OK, tried "2" - how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Yeah, working as expected, thx! Closing.
