### ISSUE TITLE
During transition to/from vertical scroll bar in textbox, the text direction changes to LTR

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#5532]
3.6.3 beta 109, but this is an old issue. I thought it might be resolved by the recent changes to the textbox behavior, but it seems like it hasn't been.
When SE is maximized (this doesn't happen otherwise), if the text in the textbox is in the RTL alignment (that is, you press ctrl+shift on the right side of the keyboard), and enough lines are added that the textbox changes to one with a scroll bar, the text direction changes to LTR:
![se GIF 11-25-2021 1-46-15 PM](https://user-images.githubusercontent.com/19672444/143436293-15a48b53-f922-4bed-aa6c-58fbda583545.gif)

Next, I change the direction into RTL again, delete the last line, and it changes back to LTR:
![se GIF 11-25-2021 1-47-12 PM](https://user-images.githubusercontent.com/19672444/143436384-eb9a8ae3-a0a6-4db9-afb6-54fe4e4dce4b.gif)

**Comment by niksedk** [comment]
Kinda solved now auto scroll bar is always shown (the old functionality could crash some systems)

**Comment by darnn** [comment]
Looks like it's solved, yeah.
