### ISSUE TITLE
I can't see the videos with the burn-in subtitles

### ISSUE THREAD

**Issue by Titela79** [SubtitleEdit/subtitleedit#5534]
Hey there!

I've solved the previous issue by uninstalling and installing again the software but now I can't see my videos with the burn-in subs. The software seems to be working but when I click on **Open containing folder**, I can't see any video.

![image](https://user-images.githubusercontent.com/95028557/143482708-62d62612-8d1e-470a-a676-83e99d7948e0.png)

Thanks again!

**Comment by niksedk** [comment]
Does F5 / refresh help?

**Comment by Titela79** [comment]
Hey there! Nope, it doesn't. Perhaps I need to change some of the settings here but I don't know which ones... 
![image](https://user-images.githubusercontent.com/95028557/143494626-8fec6f90-7ceb-45c8-be86-e7401e2e2e63.png)

**Comment by niksedk** [comment]
Could you check latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip
It should actually check if the file exists after calling ffmpeg.

**Comment by Titela79** [comment]
Thanks but it's not working either.

**Comment by niksedk** [comment]
Can you provide steps to re-create this?
Also, SE should actually display a long log message, if the target file does not exist.
You can also press F2 in the "burn in window" to see the raw ffmpeg cmd line - you can even run it from the command line yourself to see any ffmpeg errors.

**Comment by Titela79** [comment]
Hey there! Thanks for helping! I'm a translator, not a programmer. So, maybe there are things that I don't fully understand. 
This is what I'm doing:
I open the video from: Video > Open video file (and I choose an MP4 file)
Then I open the .srt file I created from: File > Open (keep video)
Then I go to: Video > Generate video with burned-in subs
Then I choose the font and size and click on Generate.
I choose the folder to save it and here the problem starts, I guess
I get the message that the video with the burned-in subtitles was generated but that happens almost automatically. I don't see any progress bar, for instance.
Then I click on "Open containing folder", and the video is not there.
This is what I get if I press F2 in the burn in window but I don't know what to do with it:
![image](https://user-images.githubusercontent.com/95028557/144100648-b5606210-2517-4187-8bbb-bfbdea40cf1c.png)
Thanks a lot again for helping me.

**Comment by niksedk** [comment]
Does this happen with all video files?
Could you perhaps send me a link to one of the smaller video files + a screenshot of your settings?

**Comment by Titela79** [comment]
Yes, it does. I even tried with different video files, eg. MPG and MP4 and I get the same result.
![image](https://user-images.githubusercontent.com/95028557/144123444-3235d3ae-0210-4d1b-8740-6f5e2bf8a383.png)
Those are my general settings.
![image](https://user-images.githubusercontent.com/95028557/144123504-52ea945e-c510-485d-9c3d-fa403913035b.png)
And the video player settings. 
This is a link to a video I created with SE and burned the subs in before updating to the latest version:
https://photos.app.goo.gl/cFpXDfVtUAw35LuA9
And this one, another but I had to use some different software to burn the subs in:
https://photos.app.goo.gl/7Ycb6s9U8bbARont6

**Comment by brainstorm1313** [comment]
Hi
I have a same problem. I tried to change params (codecs, audio codec copy/not, output formats, reconvert video). File don't created. :-(

**Comment by brainstorm1313** [comment]
Problem solved
I rename file "y2mate.com - Jeff Buckley  Hallelujah Official Video_480p.mp4" to "123.mp4"
I think bug in a filename.

**Comment by niksedk** [comment]
Hopefully this is fixed in latest beta... fixes regarding spaces in file name and some mp4 files has been made
