### ISSUE TITLE
CTD when paste from google translate

### ISSUE THREAD

**Issue by kucingkembar** [SubtitleEdit/subtitleedit#5539]
hi, sorry for my bad English,
I don't know why, sometimes when I paste results from google translate to the program, the program Crash to desktop, all my 30+ minutes job is gone,
1. is there any way to recover that?
2. is this software has a log crash?

and this 3rd question is exclude the above problem,
when I press alt+enter, the video is the full-screen mode, 
then when I press alt+tab and the active window switch to another program, 
I can see the "translate, create, adjust" window, but somehow it is behind the video, 
(I can't see or use it)
so I cant use them, how to fix this?

edit
4. how to set subtitle solid color background, I don't know how must I explain it, similar to this(the grey one):
![Untitled](https://user-images.githubusercontent.com/47294266/143782600-95578c39-9e61-4a7b-8df9-36609b401abc.jpg)

**Comment by niksedk** [comment]
Please include the crash log + steps to re-create.
If a log is not displayed, perhaps something is logged to the SE folder?

For recovering lost work check - File - Restore auto-backup...

To use a box with background box use format "Advanced Sub Station Alpha" - and set the background box color in the "Style" window.

**Comment by kucingkembar** [comment]
thank for the reply
 i cant include the "crash log" because it question number 2, the step is: you paste from output google translate (using firefox), then paste to subtitle, the program does not respond then crash without any message

where is this "SE" folder?

thank you for "File - Restore auto-backup" info

for "Advanced Sub Station Alpha", I google it and found it, thank you
