### ISSUE TITLE
Seems to crash whenever I try italicizing text. 

### ISSUE THREAD

**Issue by Misterveeare** [SubtitleEdit/subtitleedit#5543]
Any time I try to italicize any text Subtitle Edit seems to crash.
It crashes both when I use a keyboard shortcut or right clicking the text.

I'm currently on version 3.6.3  using windows 10.

**Comment by niksedk** [comment]
OK, can you re-create the issue in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip ?

If yes, please attach a screenshot of the error and steps to re-create the issue, thx.
