### ISSUE TITLE
ASSA Style window: Remove All button is a bit narrow

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5544]
Not sure if it could be simply solved by making the button a bit wider:

![remove all button](https://user-images.githubusercontent.com/494788/143985159-0b439487-99e6-473f-9fc6-1093c78a2f39.gif)

**Comment by niksedk** [comment]
OK, is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

Have you enabled something in windows to get larger fonts?

**Comment by LeonCheung** [comment]
Well solved, thx. Hmm, I don't think so if this is the only entry to tweak system fonts:

![display](https://user-images.githubusercontent.com/494788/144015503-e16678b0-2f5c-4133-b6c3-42094fbddeb0.png)
