### ISSUE TITLE
Errors from English to Greek translation

### ISSUE THREAD

**Issue by ZTel1990** [SubtitleEdit/subtitleedit#5545]
I Use the 3.6.3.0 ver.
1.When i translating from English to Greek
at the beginning of each line when the first word
has a tone like "ήταν" (=was) the translation gives "wasταν",
or "ίσως" (=maybe) gives "Maybeσως".

2. I have and an error Message:
Stack Trace:
system.Decimal..ctor(Double value)
Nikse.SubtitleEdit.Forms.Main.VideoLoaded(Object sender, EventArgs e)
System.Windows.Forms.Timer.OnTick(EventArgs e)
System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
System.Windows.Forms.NativeWindow.Callback(IntPtrhWnd, Int32 msg,IntPtr wparam, IntPtr Iparam)

**Comment by niksedk** [comment]
Could you attach some screenshots + subtitle file?

**Comment by ZTel1990** [comment]
![Error if file Futuro Beach str](https://user-images.githubusercontent.com/95308295/144298049-f9a7c6e0-e9e7-4b4c-8525-fbc91d6b7dc1.PNG)
This message comes out when I load the video file.
The subtitle file how can Ι send it? (This Window does not allow me)

**Comment by niksedk** [comment]
Are you using mpv as video player? If not, do try it (go to Options - Settings - Video player)

Also, please send a screenshot of how you translate.
