### ISSUE TITLE
Fedora Installation Instructions

### ISSUE THREAD

**Issue by M4a1x** [SubtitleEdit/subtitleedit#5551]
Hey there, great project!

I just tried using it on Fedora and had some issues, when I found your installation instructions for Ubuntu/Arch here: https://www.nikse.dk/SubtitleEdit/Help#linux

If you have time you could add the following line for Fedora users which should be largely equivalent (at least it's working for me now, Fedora 34):
```console
$ sudo dnf -y install mono-complete mpv mpv-libs hunspell dejavu-sans-fonts tesseract tesseract-langpack-eng vlc vlc-extras ffmpeg
```

Cheers,
Max

**Comment by niksedk** [comment]
Just tried on a wm... it could not find mpv... do I need rmpfusion repros?
https://forums.fedoraforum.org/showthread.php?324163-install-mpv-player-on-fedora32

**Comment by niksedk** [comment]
It's working now, but mpv launches outside SE - but that might be a VirtualBox issue.

**Comment by niksedk** [comment]
Updated the help page: https://www.nikse.dk/SubtitleEdit/Help#linux

thx for the info :)

**Comment by M4a1x** [comment]
Nice! That was quick :)
I just checked again on my system and yes indeed for mpv you need rpmfusion repos enabled. For me mpv also opens outside of SE so it doesn't seem to be a VirtualBox issue. I didn't notice it because I had set SE to vlc manually in the settings before and forgot to check again with mpv. 

Because of these two points I think you could probably either:
* Just remove mpv and mpv-libs from the command, as vlc is already in there and SE chooses that automatically (maybe add a note that mpv from rpmfusion can be used instead if desired?)
* Or add a link to the official documentation on how to add rpmfusion repos for mpv: https://docs.fedoraproject.org/en-US/quick-docs/setup_rpmfusion/

I also upgraded to Fedora 35 in the meantime and it's working as well - as expected.

Cheers!
Max

**Comment by spontaneous-emission** [comment]
To get SubtitleEdit to fully work on Fedora 35 I also had to symlink libhunspell
```
sudo ln -s /usr/lib64/libhunspell-1.7.so.0 ~/Downloads/SubtitleEdit/libhunspell.so
```
otherwise it kept popping up with a error message about a missing hunspell despite having `hunspell`, `hunspell-devel`, and `hunspell-en` installed.

**Comment by niksedk** [comment]
I could make libmpv work after I changed "<MpvVideoOutputLinux />" to "<MpvVideoOutputLinux>x11</MpvVideoOutputLinux>" in Settings.xml - does that also work for you?

**Comment by niksedk** [comment]
Thx @M4a1x and @spontaneous-emission: Help file updated: https://www.nikse.dk/SubtitleEdit/Help#linux
SE now works for me with libmpv + spell check :)

**Comment by M4a1x** [comment]
I just tried your settings on my system and mpv launches inside SE now and with the symlink I got hunspell working as well. Great!
Thanks to both of you! :)
