### ISSUE TITLE
SE 3.6.4: Remember video position

### ISSUE THREAD

**Issue by GrampaWildWilly** [SubtitleEdit/subtitleedit#5553]
In the 3.6.4 Changelog, I see this:

   * Remember last chosen video offset - thx OmrSi

I have one (actually, many) of those Metropolitan Opera things which consists of 3 separate files: MP4 of video without audio, MP4 of audio without video, VTT of subtitles.  The VTT opens just fine in SE & the MPV window opens with the video positioned at the time index corresponding to the first subtitle for the opera, which is usually a certain offset into the file since they typically have an introduction of a few minutes for which they do not provide subtitles.  There is nothing in the waveform since you do not support video & audio from separate files, which is not a complaint, simply an observation.  If there's no audio, why would I open such a thing in SE?  There's almost always a few things about their subtitles that I like to change, including the occasional misspelling & certain punctuation habits they have that I consider incorrect.  So I watch the opera in VLC but I need our favorite application to fix the subtitles.

Let's say I open one of these things, then I position the video in the MPV window to time index 00:00:00.   SE remains positioned on the first subtitle, which is correct behavior.  Then I close SE.  Then I reopen SE, not from the VTT file but just from the Windows Start Menu.  The same VTT/video pair is opened but the video is not positioned as advertised in the Changelog entry I quoted above.  The video is once again positioned at the time index corresponding to the first subtitle.  My guess is the absence of an audio track in the MP4 is tripping this up.  But that's a guess.  I'm not sure this is relevant but I'll mention it anyway.  I have the controls undocked & I'm using 2 monitors.  The MPV window is on the second monitor (my TV) while the rest of SE is on the first monitor (my computer monitor).

**Comment by darnn** [comment]
That changelog entry refers (if I understand correctly) to the fact that the last offset entered in the set video offset dialog box will automatically be set the next time you use it (and it remembers the last few that you've used):

![set video offset](https://user-images.githubusercontent.com/19672444/144659532-23973100-463e-4746-b357-864e5bb83596.jpg)

So it's not really related to what you're talking about. But I do think it's a reasonable suggestion (though I say this as someone with zero programming experience, so I have no idea how much work it would be to actually implement).

**Comment by GrampaWildWilly** [comment]
I'm not sure what was completed but I'm still seeing this behavior.  Opening a captions file still positions the video on the first caption.  Even after I reposition the video to time index 00:00:00 & close SE, it still opens on the first caption instead of on the time index where I last positioned it, which was 00:00:00.  This is with SE 3.6.7 beta 105 now.
