### ISSUE TITLE
Norton: false positive?

### ISSUE THREAD

**Issue by BlaqCharles** [SubtitleEdit/subtitleedit#5555]
I was trying to install [3.6.4](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEdit-3.6.4-Setup.zip). It didn't have enough reputation with Norton 360 (Windows). I whitelisted it, then at the end didn't rec, Norton 360 (Windows) blocked two operations it deemed suspicious:

1:
```
Category: Data Protector

Date & Time
12/3/2021 20:25

Risk
High

Activity
Data Protector blocked a suspicious action by SubtitleEdit-3.6.4-Setup.exe

Status
Action Blocked

Recommended Action
No Action Required

Status
Action Blocked

Program Path
C:\Users\Charles\AppData\Local\Temp\Temp1_SubtitleEdit-3.6.4-Setup.zip\SubtitleEdit-3.6.4-Setup.exe

Program Name
SubtitleEdit-3.6.4-Setup.exe

Date & Time
12/3/2021 20:25

Action Observed
Suspicious process attempted to open a file protected by Data Protector

Target
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\_Video\Subtitle Edit\Help and Support\Online Help.url
```

2: A similar Norton event with the file `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\_Video\Subtitle Edit\Help and Support\Subtitle Edit on the Web.url` .

**Comment by niksedk** [comment]
To help, please report "false positive" to your anti-virus provider - thx :)
They should report back to you.

Also, do check files on VirusTotal.
Installer (currently two flags): 
https://www.virustotal.com/gui/file/3e57f38b4fe8097103f4040b5fc0e0bbc42b7367e17fcd0bd71db85fb4bdb123?nocache=1

Portable, SubtitleEdit.exe only (currently one flag):
https://www.virustotal.com/gui/file/3c1d73d763c9a720464b4b5df28f8f316c4a4c1c7f9e1137b07c4f31e79ca72f?nocache=1

Read more here: https://github.com/SubtitleEdit/subtitleedit/issues/5280

At the release of SE 3.6.2 SubtitleEdit.exe was flagged 26 (or 28) times! So yeah, this is very annoying for open source software devs... and users. 
![image](https://user-images.githubusercontent.com/1261331/144702474-e6528855-9856-4ac9-8e88-fbd622cc2676.png)

**Comment by BlaqCharles** [comment]
Reported to Norton. Will update if I get feedback.

**Comment by niksedk** [comment]
@BlaqCharles: Did you hear back from Norton?

Current status:
Subtitle Edit installer: 2 flags
SubtitleEdit.exe: 0 flags

**Comment by BlaqCharles** [comment]
Norton has been "analyzing (up to 48 hours)" it for ten days now.


Submission ID:
3b1b3078-ef44-4911-afd2-0e667e8773a4
Submission type:
False positive
Submission status:
Your submission is being processed
Submission details:
Analyzing (up to 48 hours)
Updated:
Sat, 04 Dec 2021 21:21:16 GMT

**Comment by niksedk** [comment]
OK, try writing them again, thx.

Current status on Virus Total:
Subtitle Edit installer: 0 flags
SubtitleEdit.exe: 0 flags

Yay :)

**Comment by BlaqCharles** [comment]
I have resubmitted. The report can be checked at https://submit.norton.com/?type=CHECK&submission_id=3b37b384-f743-42ce-a2db-94423ba68043 .

**Comment by niksedk** [comment]
OK, I'll close this now - seems like Norton has really poor support!
