### ISSUE TITLE
Google Translate V1 API

### ISSUE THREAD

**Issue by MehdiZouaoui** [SubtitleEdit/subtitleedit#5558]
Hello everyone,

I was trying to translate an SRT file from English to Arabic but an error message popped out:

Free API quota exceeded?

System: The remote server returned an error:(429) too many requests.

I wonder how we can bypass this issue.

Thank you in advance for your assistance.

Mehdi

**Comment by MehdiZouaoui** [comment]
I've used the online version of Subtitle Edit to autotranslate the file as a temporary solution.

**Comment by niksedk** [comment]
you need to sign up for an api key to avoid the daily limit.
