### ISSUE TITLE
Smarter VTT Parsing

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5562]
This is a real story: 
After sending translators the VTT files like this:

```
WEBVTT FILE

1
00:01.000 --> 00:03.000
hello

2
00:04.000 --> 00:06.000
world

3
00:06.002 --> 00:08.002
Welcome
```

They just translated them in text editors like Word or Notepad, and sent them back like this:

WEBVTT FILE

```
1
00:01.000 --> 00:03.000
hello
你好
2
00:04.000 --> 00:06.000
world
世界
3
00:06.002 --> 00:08.002
Welcome
欢迎
```

Now, when opening the updated files, it looks like:

WEBVTT FILE

```
1
00:01.000 --> 00:03.000
hello
你好
2

2
00:04.000 --> 00:06.000
world
世界
3

3
00:06.002 --> 00:08.002
Welcome
欢迎
```
I know it's not standard, just wonder if it could be a bit more smarter in this case. Thanks.

**Comment by niksedk** [comment]
Hi Leon, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip ?

Also, do check the `Auto-gen waveform when opening video` in waveform settings :)

**Comment by LeonCheung** [comment]
It's great, and I believe the auto-gen thing is a long-waited feature, Thanks!
