### ISSUE TITLE
Italian language file - Errors to fix

### ISSUE THREAD

**Issue by bovirus** [SubtitleEdit/subtitleedit#5568]
@niksed

I sent an email to the italian translator (to the email provided by you) reporting the errors in translation but he didn't answer.
It update the translation but leave in it many errors for standard Italian grammar. Ex.

**Most of the struings of "LanguageNames" are untranslated.**

**Most of the strings of "MeasurementConverter" are untranslated.**

**Some strings are untranslaed. Ex.**
    <ColorRequiresTeletext>Colors require teletext!</ColorRequiresTeletext>
        <Superscript>Superscript</Superscript>
        <Subscript>Subscript</Subscript>
        <InsertUnicodeControlCharactersLRO>Inizio dell'override da sinistra a destra (LRO)</InsertUnicodeControlCharactersLRO>
        <InsertUnicodeControlCharactersRLO>Inizio dell'override da destra a sinistra (RLO)</InsertUnicodeControlCharactersRLO>

**"Files" is not used with ending s.**
    <SubtitleFiles>Files sottotitoli</SubtitleFiles>
    <AllFiles>Tutti i files</AllFiles>
    <VideoFiles>Files video</VideoFiles>

**Use of "tag" (and bad "tags" plurals with s) instead "etichetta" or "etichette".**

**“Mostra” -> “Visualizza”. Es.**
    <ShowWaveformAndSpectrogram>Mostra forma Onda e Spettrogramma</ShowWaveformAndSpectrogram>

**“Cambia” -> “Modifica”. Es.**
    <ChangeResolutionFontSize>Cambia la risoluzione per la dimensione del carattere</ChangeResolutionFontSize>
    <ChangeResolutionPositions>Cambia risoluzione per posizione</ChangeResolutionPositions>
    <ChangeResolutionDrawing>Cambia risoluzione per il disegno</ChangeResolutionDrawing>

**Use uppercase only for first string of the paragraph (except for won names). Ex.**
    <ShowWaveformAndSpectrogram>Mostra forma Onda e Spettrogramma</ShowWaveformAndSpectrogram>
    <Collapse>Ripiega Tutto</Collapse>

**Use of "gruppo" instead "batch"**
  <BatchConvert>
    <Title>Conversione Gruppo</Title>
should be
    <Title>Conversione batch</Title>

**use "Clicca" instead of "Fai clic". Ex.**
    <SetPosInfo>Clicca sul video per attivare/disattivare la posizione di impostazione/spostamento</SetPosInfo>

**Not right way for interrogative form**
    <RemoveOneAttachment>Rimuovi l'allegato?</RemoveOneAttachment>
    <RemoveXAttachments>Eliminare {0} allegati?</RemoveXAttachments>
should be
    <RemoveOneAttachment>Vuoi rimuovre l'allegato?</RemoveOneAttachment>
    <RemoveXAttachments>Vuoi eliminare {0} allegati?</RemoveXAttachments>

**Use article when not necessary. Ex.**
    <ShowWaveformOnly>Mostra solo la forma d'onda</ShowWaveformOnly> ->     <ShowWaveformOnly><Visualizza solo forma onda</ShowWaveformOnly>

**There are strings that are word to word english to italian when in Italian we used a different strings flow (ex. adjective,).**
<GoogleTranslate>Google Traduttore</GoogleTranslate> should be  <GoogleTranslate>Traduttore Google</GoogleTranslate>
<DarkThemeRestart>Riavvia Subtitle Edit per rendere effettive le modifiche al tema scuro.</DarkThemeRestart>
should be
<DarkThemeRestart>Per rendere effettive le modifiche al tema scuro riavvia Subtitle Edit.</DarkThemeRestart>

**There are some strings with error in the text about italian spelling.**
    <DoNotDisplayMessageAgain>Non visualizzare più questo me**sss**aggio</DoNotDisplayMessageAgain>

**Storico instead "Cronologia"**
 <ShowUndoHistory>Mostra lo storico (per annullamenti)</ShowUndoHistory>

Thanks.

**Comment by bovirus** [comment]
There are many problem about alignmet betweeb master english and itralian translation

E = Englisgh strings not translated (some tiems is right but not always)

Red box = string in english file - not in italian file (string to translate)

Green box = strings nota available in english file but availabel in italian file (string to remove from italian file)

![SubTitle Edit- XM It Differnces-01](https://user-images.githubusercontent.com/1262554/145023158-94e43768-bf6a-41ab-88b5-7c517031acfd.jpg)

![SubTitle Edit- XM It Differnces-02](https://user-images.githubusercontent.com/1262554/145023160-c6bd71d6-3678-451a-b6d1-6029952c7fef.jpg)

![SubTitle Edit- XM It Differnces-03](https://user-images.githubusercontent.com/1262554/145023161-f17c5dbe-e2ff-4ee3-acc6-513c2993071f.jpg)

![SubTitle Edit- XM It Differnces-04](https://user-images.githubusercontent.com/1262554/145023162-ccf304f0-f9f1-4e30-8d61-ce1c2f076671.jpg)

![SubTitle Edit- XM It Differnces-05](https://user-images.githubusercontent.com/1262554/145023165-b39419cb-7f13-4f13-a275-50cf8efc2cf0.jpg)

![SubTitle Edit- XM It Differnces-06](https://user-images.githubusercontent.com/1262554/145023168-be07df6f-26b4-4e94-ae07-b1432ea30d9c.jpg)

![SubTitle Edit- XM It Differnces-07](https://user-images.githubusercontent.com/1262554/145023169-0213eb04-7492-403a-ad0d-adec1d117ed2.jpg)

![SubTitle Edit- XM It Differnces-08](https://user-images.githubusercontent.com/1262554/145023170-68c3d707-ed03-4f26-8bac-86601be2032e.jpg)

![SubTitle Edit- XM It Differnces-09](https://user-images.githubusercontent.com/1262554/145023171-102e3a3b-699c-45b9-9ff9-496f2deb823a.jpg)

![SubTitle Edit- XM It Differnces-10](https://user-images.githubusercontent.com/1262554/145023173-0963eb97-d9f1-4157-ada6-a71b17cac136.jpg)

![SubTitle Edit- XM It Differnces-11](https://user-images.githubusercontent.com/1262554/145023174-da890378-71c5-40d5-a851-b1029ce13300.jpg)

![SubTitle Edit- XM It Differnces-12](https://user-images.githubusercontent.com/1262554/145023176-3b25f4fb-c332-472a-a6fe-a0357a3f744a.jpg)

![SubTitle Edit- XM It Differnces-13](https://user-images.githubusercontent.com/1262554/145023177-6dd87501-416b-4225-a2c6-62d3f6b842ab.jpg)

![SubTitle Edit- XM It Differnces-14](https://user-images.githubusercontent.com/1262554/145023180-b86084f6-ecad-4461-9d0b-82cd61200401.jpg)

**Comment by bovirus** [comment]
@niksedk 

Here there is new italian language file.

Renove orphan italian strings
Add new strings (available only in english)
Translates strings about LanguageName and Measurement section

[it-IT.zip](https://github.com/SubtitleEdit/subtitleedit/files/7674778/it-IT.zip)

Please unzip and apply to github.

**Comment by niksedk** [comment]
Thx - fixed in f5569ca056fb6af3840f49c11bed62a05df17deb

**Comment by bovirus** [comment]
@niksedk 

Please remind installer script

https://github.com/SubtitleEdit/subtitleedit/pull/5567
