### ISSUE TITLE
Message for auto-gen waveform

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5569]
When auto-generating the waveform, it would be nice to have some message or tip to tell the user that SE is working on that, because for larger files you have to wait for quite a long time and it appears nothing happens there, until you can't help to click the waveform area once more. That's a bit confusing.

Maybe an optional idea could be to have the waveform area unclickable, and replace the text "**Click to add waveform**" with "**Generating waveform...**"   :)

**Comment by niksedk** [comment]
Thx for testing and feedback :)

Text on the waveform is now "Generating waveform..." - and you cannot click on waveform.
The status bar message will also display longer now (if not overwritten).

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Also, latest version of ffmpeg is pretty fast for extracting wav file - if you have an old installation of SE it might be worth to re-download ffmpeg.
`ffmpeg -version` should give `ffmpeg version 4.4.1` (cmd line)

**Comment by LeonCheung** [comment]
Perfect, thx!
