### ISSUE TITLE
[Feature request] Shortcut > Import > Subtitle from video file...

### ISSUE THREAD

**Issue by Teezton** [SubtitleEdit/subtitleedit#5571]
Hi, 

Any chance to allow this shortcut:

![Image 004](https://user-images.githubusercontent.com/5905860/144841028-1f8c3bf9-249f-45c1-b38d-242f068f4e37.png)

To here:

![Image 003](https://user-images.githubusercontent.com/5905860/144841061-ca437d4c-1230-4555-ac33-2765694464dd.png)

Or even better, allow us to create a button on this bar:

![Image 005](https://user-images.githubusercontent.com/5905860/144841116-4341f1ce-f0d3-4eb1-b03a-08612ec76bf4.png)

**Comment by niksedk** [comment]
You can use the Open icon...

**Comment by Teezton** [comment]
> You can use the Open icon... or drag the file into the "list view".

Thank you, good solutions!
