### ISSUE TITLE
AudioVisualizer fixes and suggestions

### ISSUE THREAD

**Issue by vitacon** [SubtitleEdit/subtitleedit#5573]
I noticed a few strange things in AudioVisualizer that I would like to change:

1. While changing zoom of the waveform the text disappears even when the items are still large enough. I suggest making the criteria paragraph-dependent and less demanding (or adjustable in settings):
```
// paragraph text
// if (n > 64) 
if (currentRegionWidth > 50)    // suggestion: the region has to be at least 50 pixels wide to display some text
{
    string text = HtmlUtil.RemoveHtmlTags(paragraph.Text, true);
```

2. Sometimes it is impossible to drag the ending border of some paragraphs - especially in small zoom 10-20 %. I suppose ClosenessForBorderSelection should be zoom-dependent. This change seems to work:
```
private bool IsParagraphBorderStartHit(double milliseconds, double startMs)
{
    return Math.Abs(milliseconds - (startMs - 5)) - 10 <= (ClosenessForBorderSelection / ZoomFactor); // zoom-dependent
}

private bool IsParagraphBorderEndHit(double milliseconds, double endMs)
{
    return Math.Abs(milliseconds - (endMs - 22)) - 7 <= (ClosenessForBorderSelection / ZoomFactor); // zoom-dependent
}
```

3. Right-click menu in an empty space of AudioVisualizer should definitely include an item "Insert a new subtitle here". It would be a useful shortcut for "Go to previous subtitle" and then "Insert after".

Just my two cents... =)

**Comment by niksedk** [comment]
1+2 fixed, thx :)
3) you have shortcuts for this... and the waveform is meant for making a new selection + pressing enter.

**Comment by vitacon** [comment]
> "the waveform is meant for making a new selection + pressing enter."

OK, I guess you're right. =)
I though the menu was the place where it should be too but maybe it would not be as elegant.
