### ISSUE TITLE
SubtitleEdit Doesn't Recognize Musical Notes

### ISSUE THREAD

**Issue by RedSoxFan04** [SubtitleEdit/subtitleedit#5578]
Even after I add the musical note character (♪) to the dictionary, SubtitleEdit doesn't recognize it. Instead, it mistakes it for a variety of different things, like dollar signs and various letters.

I'm using the portable version on Debian 11 via Mono. I have it set to use the Tesseract engine in English. Interestingly, it has no problem with musical notes with the nOCR engine.

**Comment by RedSoxFan04** [comment]
Never mind. Turns out I was using an old version (3.6.2) and the problem has been fixed in either 3.6.3 or 3.6.4.

**Comment by RedSoxFan04** [comment]
Never mind. Turns out I was using an old version (3.6.2) and the problem has been fixed in either 3.6.3 or 3.6.4.

**Comment by niksedk** [comment]
It's an Tesseract issue... https://github.com/tesseract-ocr/tesseract

**Comment by RedSoxFan04** [comment]
> It's a Tesseract issue... https://github.com/tesseract-ocr/tesseract

Oh, okay. Thanks!
