### ISSUE TITLE
3.6.4: WebVTT browser preview results in an exception error

### ISSUE THREAD

**Issue by koitsu** [SubtitleEdit/subtitleedit#5583]
Right-clicking on a subtitle line and choosing WebVTT browser preview causes a new browser window to be opened and the preview working as expected, however Subtitle Edit experiences a forms exception error (see JPEG below).  I can click Ignore, but the problem will recur on the next preview.  This issue is reproducible 100% of the time, and can happen even with a brand new file.  This problem existed in 3.6.2 and 3.6.3 as well; I'm not sure when it was introduced, as this is my first time tinkering with WebVTT.

OS: Windows 7 SP1 x64
.NET versions installed: Framework 4.7.2, and Desktop Runtime 5.0.12 (for unrelated software)

Thanks!

![capture](https://user-images.githubusercontent.com/8430773/145388100-fb895158-1c38-480b-b09a-3b16ba875a75.jpg)

**Comment by niksedk** [comment]
That should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
Does that work better for you?

**Comment by koitsu** [comment]
Works great! Thank you very much!
