### ISSUE TITLE
Add space between \n and - (minus symbol)

### ISSUE THREAD

**Issue by Kuju29** [SubtitleEdit/subtitleedit#5585]
\n- not work. I have a problem new line \n doesn't work. if it has minus symbol (-). I don't want to delete minus symbol (-). do you have a fix it?

![image](https://user-images.githubusercontent.com/22098092/145422115-6829a8ac-7bd0-43e8-b0c4-59b31d713b41.png)
This is what doesn't work after merging files with video.
![image](https://user-images.githubusercontent.com/22098092/145422479-7eeb0958-a1d4-4027-969c-cffb2a366f3f.png)

**Comment by OmrSi** [comment]
![image](https://user-images.githubusercontent.com/20923700/145425643-79a73027-d94a-47fe-ad8f-165c48b64c3d.png)

**Comment by Kuju29** [comment]
> ![image](https://user-images.githubusercontent.com/20923700/145425643-79a73027-d94a-47fe-ad8f-165c48b64c3d.png)

works in 1 file. but not work for batch convert
![image](https://user-images.githubusercontent.com/22098092/145426944-e2edca13-cd08-4689-87e1-d568e4c1d2eb.png)
![image](https://user-images.githubusercontent.com/22098092/145427503-feef7fee-12f3-487c-93a4-f848a755a70f.png)

**Comment by OmrSi** [comment]
The first rule should be of type regular expression.

If you're using regular expressions, `\n` should be `\\n` if you want the literal `\n`.

**Comment by Kuju29** [comment]
> The first rule should be of type regular expression.
> 
> If you're using regular expressions, `\n` should be `\\n` if you want the literal `\n`.

Still not working. I will replace it one file at a time. thanks for help. <3
