### ISSUE TITLE
Stretch Black Box

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5586]
It is possible stretch the black box, so it can cover the hardcoded subtitles?

![E1](https://user-images.githubusercontent.com/64425752/145462105-91939272-c502-44a5-96dd-36fe99e5b494.jpg)

**Comment by OmrSi** [comment]
You need to increase the `bord` size of the style.
But it will cause the box to be bigger on all sides.

**Comment by Andrebavila** [comment]
Thanks a lot, @OmrSi.
It would be nice if SE had this option.
For translators, videos with hardcoded subtitles is a pain in the ass.

**Comment by LeonCheung** [comment]
Yes, this is a pain point for me as well sometimes. If it's just for one or a few lines, actually, there is a quick and dirty way:
![image](https://user-images.githubusercontent.com/494788/147196033-3d6e6722-7e3b-4f10-961b-1671059eb6e5.png)

[example.zip](https://github.com/SubtitleEdit/subtitleedit/files/7767021/example.zip)

However, for batch editing, we really need sort of a new ASSA tool called "BG Box Generator", like an advanced version of the default opaque box parameter, and it can generate background boxes with the given height and/or width accordingly, say, by detecting text pixel. And, it would be even cool to support generating both rectangle and round rectangle. (Speaking of that, ASSA Draw needs to support drawing them too. XD  That's another topic)

**Comment by Andrebavila** [comment]
Thanks, @LeonCheung.
Sadly, I need the stretched opaque box in every line.
And I second your sugestion about "Box Generator"
Opaque box settings more updated would be perfect.
We need that!

**Comment by LeonCheung** [comment]
@Andrebavila Okay. In that case, before that magic happens, you can use Regex in **multiple replace** tool:

![image](https://user-images.githubusercontent.com/494788/147349202-e325a72e-aecc-46fd-8d08-7276f02ce7c9.png)

[multiple_replace_groups.zip](https://github.com/SubtitleEdit/subtitleedit/files/7774160/multiple_replace_groups.zip)

How to use:

Unzip It;
Click the Import from that tool. (find it in Edit > Multiple replace...);
Toggle all three toggles you've seen in the image above. Then click OK.

NOTE: It only works if you understand the example file I provided previously.

**Comment by Andrebavila** [comment]
@LeonCheung , thank you very much.
It's pretty handy and it did the trick very well.
Works like magic for me!
A Box Generator would be amazing to do all that stuff!
Thanks a lot!

**Comment by LeonCheung** [comment]
@Andrebavila Sorry it seems I failed to upload the updated version, which is safer. Please re-download the attachment above.

**Comment by Andrebavila** [comment]
Thanks, @LeonCheung.
The other way had worked nice too, but thank you, anyway.

**Comment by niksedk** [comment]
Should be closed via SE new ASSA bg box generator
