### ISSUE TITLE
Max. Number Of Lines

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5587]
Hello.
Why is this not working right?
The limit should not be two lines?

![E2](https://user-images.githubusercontent.com/64425752/145463290-459e3743-ac98-4420-ae5b-5c86ad343b7c.jpg)

**Comment by OmrSi** [comment]
There is a setting in the settings file called `MaxNumberOfLinesPlusAbort`, I think it's 1 by default, meaning it allows one more line than the max number of lines, you need to make it zero to not allow extra lines.

**Comment by Andrebavila** [comment]
Thanks, @OmrSi.
Now, it's perfect for me!
