### ISSUE TITLE
How to replace the waveform?

### ISSUE THREAD

**Issue by BlohoJo** [SubtitleEdit/subtitleedit#5589]
I'm really sorry for this basic question, but I have been trying to figure this out for the past hour. Can't find an answer via Google, searching issues here, or the help documentations. I'm probably searching wrong.

I opened an .srt and somehow, Subtitle Edit has decided to open a waveform from the subdirectory that I'm working in.

The problem, is that I have several waveforms in there I'm working on, and it opened the wrong one.

I simply cannot figure out how to replace the waveform with the right one. I tried dragging and dropping from Windows Explorer, and it didn't replace it... it keeps the one that it decided to open with. I can't find ANY function, menu, or anything that will allow me to replace the wave form with the correct one.

Can someone PLEASE help me out and post the instructions for removing the waveform and video files (so they default back to "click here to add"), and/or changing them to different files.

Sorry I couldn't figure this out on my own!

**Comment by niksedk** [comment]
SE uses a hash function of some bytes of the file name... so you will probably need to clear your waveform folder (either manually or via Options - Settings - Waveform)
