### ISSUE TITLE
Adjust all times in Batch

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5590]
Is it possible to have the Adjust All Times window in batch? Right now we have Adjust Duration in batch, but it's not as agile as Adjust All Times. Example: sometimes we get SCC files that need to be converted to SRTs and like most SCCs they either start with 10:00:00 or 1:00:00 instead of 00, so subtracting 10 hours or 1 hour is only way to fix them and I do not see how's it's achieved in Batch with a simple click like in Adjust all times.

Thank you.

**Comment by OmrSi** [comment]
You have `offset time codes` in batch, it does the same thing.

**Comment by uckthis** [comment]
Just saw it. Thank you.
