### ISSUE TITLE
SE 3.6.4: Timed Text Properties [Windows Forms Thread Exception]

### ISSUE THREAD

**Issue by gru123** [SubtitleEdit/subtitleedit#5592]
Hi,

If I change file extension to ".dfxp" in "Timed Text 1.0 properties..." it generates Windows Forms Thread Exception, and I can no longer use SE.
There is a Settings.xml file in the attachment which is causing the error (I had to change the extension to txt).
![1](https://user-images.githubusercontent.com/42896067/145674304-095d4fd4-7f86-4756-b224-4197b84cd634.png)
![2](https://user-images.githubusercontent.com/42896067/145674305-0f5007ec-d5ef-4f8c-869a-74926f20f0f3.png)
![3](https://user-images.githubusercontent.com/42896067/145674306-3e71991e-2ea9-4d8c-ba58-3a975aecefb7.png)
[Settings-Not_OK.txt](https://github.com/SubtitleEdit/subtitleedit/files/7696852/Settings-Not_OK.txt)
[Settings-OK.txt](https://github.com/SubtitleEdit/subtitleedit/files/7696853/Settings-OK.txt)

**Comment by niksedk** [comment]
@gru123: This should actually be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
Could you verify?

**Comment by gru123** [comment]
Thanks, it's okay now.
