### ISSUE TITLE
Selected line out of sight

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5593]
https://user-images.githubusercontent.com/494788/145679952-eae9522c-a99f-4a3a-a168-6ac4d088a173.mp4

In the latest version, sometimes the selected line can't be seen in the list, instead, you have to scroll up one line to expose it. 

Can we maybe try to keep it in the middle of the visible area? Because it is useful to see the adjacent lines (before and after it) at the same time.

**Comment by niksedk** [comment]
Hm, I cound not re-create this. Any ideas?

**Comment by LeonCheung** [comment]
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/7697267/Settings.zip)

Maybe because I used a larger font size? Anyway try my settings.

**Comment by niksedk** [comment]
Thx for the settings file - could re-create it :)
Should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Perfect, thx!
