### ISSUE TITLE
Remove text for hearing impaired - brackets

### ISSUE THREAD

**Issue by cokolwiek235** [SubtitleEdit/subtitleedit#5596]
Removing text between brackets option in Remove text for hearing impaired window doesn't remove all text between brackets.
File format or encoding doesn't matter, its always the same.

Example MPL2 file in attachments.

[22.txt](https://github.com/SubtitleEdit/subtitleedit/files/7697453/22.txt)
.

**Comment by niksedk** [comment]
Works fine for me... what is not working for you?

**Comment by cokolwiek235** [comment]
Ok, its my settings then. Something after update got messed up I guess. I always leave my old settings.xml so I wouldn't have to configure everything again and again. After removing it everything seems to be ok. So I guess I will just have to reconfigure SubtitleEdit everytime I update.

Thank you.

**Comment by niksedk** [comment]
Do use "mpv" for video player and "ffmpeg" for waveform extraction :)
