### ISSUE TITLE
Copy-paste in translator mode causes desync

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#5597]
3.6.4 NEXT beta 68.
In translator mode, select any subtitle in list view. Press ctrl+c and then ctrl+v. Desync between the original and the translation occurs.
Before:
![se-desync-01](https://user-images.githubusercontent.com/19672444/145692254-1c5cea07-f556-44aa-a18e-7a62fd238276.png)

After:
![se-desync-02](https://user-images.githubusercontent.com/19672444/145692257-bef4214d-79ef-4669-8333-c5a08bf60018.png)

**Comment by darnn** [comment]
@niksedk Any chance you could look at this at some point? It's still happening as of 3.6.8. It makes it really hard to edit source and translation subtitles together. For instance, if I need to add 150 empty lines, instead of just pasting them in the translation and having the source match, I need to add them manually one by one.
Ideally there would be a copy source+translation (and paste source+translation) mode, but I'd settle for just being able to paste into one and having the other match it instead of desyncing.

**Comment by niksedk** [comment]
Ctrl+C copies the translation row(s) to clipboard in SRT format:

E.g. like:
```
3
00:00:06,222 --> 00:00:07,835
Line3
```

For this to work, that would require SE to include the original text... like:


```
3
00:00:06,222 --> 00:00:07,835
Line3 <--> O3
```

Where `<-->` is some separator symbol... 

Any comments? @darnn @LeonCheung

**Comment by niksedk** [comment]
Also, I think this does not cause de-sync atm?

**Comment by darnn** [comment]
It does. With beta 3.6.10 NEXT beta 184, I copied the second line:
![se3 6 10-184-copypaste01](https://user-images.githubusercontent.com/19672444/210165349-a65e879b-add3-4b03-a67f-2496846dfb3c.png)

And then pasted:
![se3 6 10-184-copypaste02](https://user-images.githubusercontent.com/19672444/210165359-0cb5766e-206c-4dcc-b626-8e48c94f960d.png)

Part of the issue might be that when it pastes, it tries to modify the timecode so that it doesn't overlap with the timecode of the copied subtitle. But I don't think this should happen anyway, I think the timecode should remain the same.

As for the separator symbol, I don't think I understand what you mean. Ideally, in translator mode, when you paste a subtitle (or several subtitles), they should be pasted into the translation file normally, and the original file should just be updated with corresponding subtitles with no text in them, to avoid a desync.

Of course, it would be even nicer if we could copy the original and the translation at once, but I assume this would take more work, and it's not as essential for me. I can always do that myself with a few more steps, using "switch original and translation".

**Comment by LeonCheung** [comment]
Hmm, I'm not a programmer but I guess it could be like a little batch operation? I mean, by hitting Ctrl C once, SE will do the same thing for both the original and translation side. Same as Ctrl V.
