### ISSUE TITLE
App force close

### ISSUE THREAD

**Issue by mehrannnn** [SubtitleEdit/subtitleedit#5600]
Hi, recently whenever I try to open a video on Sub Edit, the app immediately closes itself. I tried the uninstall/install way too, but didn't work.

**Comment by niksedk** [comment]
Try deleting the Settings.xml file... 
Can you find any logs?

Try installing dot net framework 4.8: https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer

**Comment by mehrannnn** [comment]
> Try deleting the Settings.xml file... Can you find any logs?
> 
> Try installing dot net framework 4.8: https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer

I couldn't find setting.xml
there was a file named changelog or something and I deleted that, but didn't work.

**Comment by niksedk** [comment]
Did you install dot net framework 4.8 ?

The Settings.xml file is located in `C:\Users\<USERNAME>\AppData\Roaming\Subtitle Edit` if you're using the installer version.
Try using "mpv" as video player instead of VLC.

**Comment by mehrannnn** [comment]
Yep, but it says that I already have it.
I don't have an appdata folder on that address :(
I use potplayer. could the problem be because of that?

**Comment by mehrannnn** [comment]
> Did you install dot net framework 4.8 ?
> 
> The Settings.xml file is located in `C:\Users\<USERNAME>\AppData\Roaming\Subtitle Edit` if you're using the installer version. Try using "mpv" as video player instead of VLC.

Yep, but it says that I already have it.
I don't have an appdata folder on that address :(
I use potplayer. could the problem be because of that?

**Comment by niksedk** [comment]
`<USERNAME>` is your username...

Try the portable version then... use choose mpv as video player.

**Comment by OmrSi** [comment]
`%appdata%\Subtitle Edit` works as well for the installer version...

**Comment by niksedk** [comment]
Yes Winkey+R and
![image](https://user-images.githubusercontent.com/1261331/145876202-598c2552-1109-4360-a30e-b8363542365f.png)
