### ISSUE TITLE
The new 3.6.4 update has problem with"right-to-left mode"

### ISSUE THREAD

**Issue by parsivan** [SubtitleEdit/subtitleedit#5601]
I just updated the app and when I click the mode it doesn't bring everything to right and navigating between the words has become very hard. I have tried reopening the app and re-applying the settings.

**Comment by darnn** [comment]
Try this:
Go to Options->Settings->Appearance and uncheck "Use syntax coloring".

**Comment by parsivan** [comment]
it was unchecked from before

**Comment by darnn** [comment]
Huh. Well, you'll have to wait for someone more qualified than me, then. In the meanwhile, could you post screenshots of this?

**Comment by parsivan** [comment]
Ok I did take screenshots but I also want to add; it seems like the file I was trying to edit could not be changed to right-to-left mode but I tried another file and there was no problem.
[Link to Pictures ](https://drive.google.com/drive/folders/15DaJOYwRhjUaXzxe5jFmeO8Jc5Ovo2PN?usp=sharing)

**Comment by parsivan** [comment]
I thought if it's a file problem and not software then how is it that it can't change the mode?

**Comment by darnn** [comment]
I must admit I am at a loss, so once again, maybe someone more qualified could help. But in the meanwhile: What file format is this? And what encoding? Any chance you could upload the one that works and the one that doesn't? If there's information in there you're not supposed to share, you can just change the text into random characters, leaving the punctuation and tags the same (provided that the problem persists that way).

**Comment by darnn** [comment]
Also, if this is ssa/ass, are you previewing it in an external player? Because SE's internal preview (at least with MPV) should show the punctuation in its proper place even without using fix RTL via unicode, so you should check with an external player.

**Comment by parsivan** [comment]
ok so the original file was in .srt but I changed it into .ass and even when I do change the mode to right to left the texts are still on the left side. there was also a time where it didn't happen. ok, I will send the files later the ones which didn't work and those who do work.
