### ISSUE TITLE
get error code 0xc00d36c4 when you play it after video generation

### ISSUE THREAD

**Issue by peteryuling** [SubtitleEdit/subtitleedit#5604]
today after successfully adding subtitles for two videos(MP4 files), for the third one it can't be played with error code 0xc00d36c4. the original video (MP4) can be played with no problem. I have tried it on different players but it all comes with the same error code. and

**Comment by peteryuling** [comment]
it happened after I upgraded to windows 11

**Comment by niksedk** [comment]
What are you export settings (please attach a screenshot) and what input file did you use (can you upload it somewhere)?
