### ISSUE TITLE
Save as... dialog always defaults to the last used format regardless of what's selected in edit window

### ISSUE THREAD

**Issue by TerrorizedGakon** [SubtitleEdit/subtitleedit#5605]
Hi,

I have no idea whether that's intended, but by looking at settings.xml and the behaviour after the file is removed, I assume it's not.

Whenever you set format and encoding to whatever you want, these settings won't be applied to the save as. The format will be selected to the previous format that was chosen manually during save as dialog. 

Previously, it was always set to the format chosen in the edit window.

When the settings.xml file is removed, the previous behaviour is back and the format in save as dialog is matching the format in edit window. But when you close and then start the program again, it will always set the format to the last used format before the program was first closed.

**Comment by OmrSi** [comment]
What is selected in Settings -> Subtitle formats -> Default save as format?

**Comment by TerrorizedGakon** [comment]
> What is selected in Settings -> Subtitle formats -> Default save as format?

-Auto-

**Comment by TerrorizedGakon** [comment]
Exact steps I use to reproduce what I'm talking about everytime:

I'm on Windows 10, but it seems to happen on other computers I use, which have Windows 7

1. Remove settings.xml from %Appdata%/SubtitleEdit/
2. Make new subtitle
3. Add any text
4. Save as whatever format. Save as dialog always takes the setting from edit window, like I remember it
5. When subtitles are saved, all future subtitles will default to the format this subtitle was saved to, choosing format at edit window no longer. Manual change of subtitle format at save as dialog is required then

**Comment by OmrSi** [comment]
So, the way SE works is: If there is a format set in `Subtitle formats -> Default save as format`, then it takes this format.
If `Subtitle formats -> Default save as format` is `- Auto -`, then it takes the last used `Save as` format.

I think what you see when making a new settings file is because the last `save as` format isn't saved yet.

**Comment by TerrorizedGakon** [comment]
I see.

Wasn't it different in the past though? Or did I experience a bug which changed the behaviour previously?

If that is the intended behaviour, it would probably be nice to have the option to define the save as format as "Same as in edit window" or something like that

Because now, when setting the format in the edit window, it seems not so useful, since save as dialog is ignoring that setting anyway.

**Comment by niksedk** [comment]
The "subtitle format change" code was rewritten in last version, so it's seems like is has changed a little...
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by TerrorizedGakon** [comment]
> The "subtitle format change" code was rewritten in last version, so it's seems like it has changed a little... How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

Hey :)

Indeed, in the beta version, save as dialog is working like I remember it working, thanks for letting me know.

**Comment by niksedk** [comment]
Fixed in e352299fca151cba1d6951312080903f3b651983

**Comment by TerrorizedGakon** [comment]
Hello,

I've found that if I try to save as the default format that is set in the settings, in my case SRT, save as default will ignore that format and save to the last saved format (example EBU STL). If I save in anything except the default format, it's all correct.

Is that intended behaviour?

If not, I would like to reopen this issue. Or should I create a new one and reference this issue?
