### ISSUE TITLE
A fix common error corner case

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5606]
I think the casing fixer should ignore such a case:

![upper case](https://user-images.githubusercontent.com/494788/146021345-04928087-0061-4dc0-b78c-8317f4e295b0.png)

**Comment by niksedk** [comment]
Could you attach the sub? Seems to work for me...

**Comment by LeonCheung** [comment]
1
00:00:01,000 --> 00:00:03,000
This is line1

2
00:00:03,080 --> 00:00:05,080


3
00:00:05,160 --> 00:00:07,160
and line2

**Comment by niksedk** [comment]
Hm, I think this works as well as can be expected...

**Comment by LeonCheung** [comment]
Hmm, then the result for the first case will be:
![image](https://user-images.githubusercontent.com/494788/146205728-53ce2575-2187-4a36-80cb-831a1e48e8fe.png)

And this is unexpected because the two paragraphs actually belong to the same sentence:
"**I don't think this line should be capitalized**." I mean, the point here is, whether or not a empty line should be considered a valid paragraph.
