### ISSUE TITLE
Subs with duplicated lines - ability to delete duplicated lines

### ISSUE THREAD

**Issue by Rouzax** [SubtitleEdit/subtitleedit#5609]
Since recently, some of my subs I get from the file have duplicated subtitle line entries.
See for example
![image](https://user-images.githubusercontent.com/4103090/146200491-ab5ef22e-e0ac-4ec9-8631-3026a1d6fffd.png)

Here is a snippet of the srt file, see line 9 and 10
```
1
00:01:38,307 --> 00:01:39,308
Get you anything?

2
00:01:43,896 --> 00:01:44,897
Aloha.

3
00:01:44,980 --> 00:01:46,190
Mahalo.

4
00:01:47,149 --> 00:01:48,525
-Rabbi Sherman.
-Hello, boychick.

5
00:01:48,609 --> 00:01:50,777
-Or should I say the king of Ping-Pong?
-It's true.

6
00:01:50,861 --> 00:01:52,613
-Watch out. He has ninja moves.
-Thanks.

7
00:01:53,447 --> 00:01:56,325
Thea?
Either you're growing, or I'm shrinking.

8
00:01:57,075 --> 00:01:58,952
Hey, Nick and Toni's, right?

9
00:01:59,036 --> 00:02:01,455
-Wednesday night. I'm calling you!
-You got it.

10
00:01:59,036 --> 00:02:01,455
-Wednesday night. I'm calling you!
-You got it.

11
00:02:01,538 --> 00:02:02,664
You're gonna love the corn.

12
00:02:02,748 --> 00:02:06,210
Round Swamp Farm's.
I shucked it myself. There he is!
```

Would it be possible to add an option to delete the second duplicated line?
Maybe make it a derivative from `Merge lines with same time code` or `Merge lines with same text` but make the option to delete as it will pick out the duplicates perfect
![image](https://user-images.githubusercontent.com/4103090/146201078-a6624a65-d673-4196-b8f3-bf5fc3d94763.png)

![image](https://user-images.githubusercontent.com/4103090/146200775-436dcfcd-0b0f-46eb-ba81-1042ab03b518.png)

If you were to add it, please also make this available to the command line options

**Comment by niksedk** [comment]
This should be exactly what `Merge lines with same text` does...

**Comment by Rouzax** [comment]
You are right 😣 my bad,
I did test the 'Merge lines with same time code' but that joins both line together and assumed the other one would do the same.
