### ISSUE TITLE
is there possibility for Cmake (?) build system? 

### ISSUE THREAD

**Issue by Randrianasulu** [SubtitleEdit/subtitleedit#5612]
Some time ago I looked into this project
https://github.com/pavelliavonau/cmakeconverter

but because this only works with c/c++/fortran exactly this tool probably not very useful for SE? Or may be it can be extended, or there is already suitable fork..

mostly leaving it here for future searches (sorry if my dismissing of Visual Studio a bit outdated, just I found it odd choice.. but probably explainable by history of project..)

EDIT:
https://stackoverflow.com/questions/2074144/generate-c-sharp-project-using-cmake/46247927

https://github.com/bemehiser/cmake_csharp_example

not sure if things are easy to set up this way (cmake->sln) but I hope one day building this program on linux will be possible)

**Comment by niksedk** [comment]
I think you can compile SE on Linux with Mono Develop.

**Comment by Bond-009** [comment]
@niksedk https://github.com/SubtitleEdit/subtitleedit/blob/master/src/libse/LibSE.csproj#L43
Doesn't work on Linux

**Comment by niksedk** [comment]
> @niksedk https://github.com/SubtitleEdit/subtitleedit/blob/master/src/libse/LibSE.csproj#L43 Doesn't work on Linux

Yes, do remove it... also mentioned on the help page: https://www.nikse.dk/SubtitleEdit/Help#compile
