### ISSUE TITLE
An application error occurred in Subtitle Edit 3.6,4.0.

### ISSUE THREAD

**Issue by SarahElGayyar** [SubtitleEdit/subtitleedit#5613]
Hello

I got this warning while trying to generate a video with burned-in subtitles:

An application error occurred in Subtitle Edit 3.6,4.0.
Please report at
https://github.com/SubtitleEdit/subtitleedit/issues with the
following information:
Error Message:
Value of -2147483648' is not valid for 'Maximum'. 'Maximum'
must be greater than or equal to 0.
Parameter name: Maximum
Stack Trace:
at System.Windows.Forms.ProgressBar.set_Maximum(Int32
value)
at
Nikse.SubtitleEdit.Forms.GenerateVideoWithHardSubs.button
OK_ Click(Object sender, EventArgs e)
at System.Windows.Forms.Control.OnClick(EventArgse)
at System.Windows.Forms.Button.OnClick(EventArgse)
at
System.Windows.Forms.Button.OnMouseUp(MouseEventArgs
mevent)
at System.Windows.Forms.Control. WmMouseUp(Message&
m, MouseButtons button, Int32 clicks)
at System.Windows.Forms. Control. WndProc(Message& m)
m)
at System.Windows.Forms.ButtonBase,WndProc(Message&
at System.Windows.Forms.Button. WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr
hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)

I don't understand it and I don't know what should I do.
Please help me to solve this issue.

**Comment by niksedk** [comment]
What kind of input file do you use? mp4?
Could you possibly upload it somewhere?

**Comment by SarahElGayyar** [comment]
Yes. It's MP4.
And here's a screenshot of what I got after the last update. 

![Screenshot (98)](https://user-images.githubusercontent.com/96264803/146539002-04c34802-bfa9-4bf3-b028-9c5275666363.png)

**Comment by niksedk** [comment]
Does it work better in latest beta version? 
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

Could you possibly share the mp4 file?

**Comment by SarahElGayyar** [comment]
I haven't tried it.

I tried to create subtitles for the MP4 type of these two videos, and I got the same warning message and couldn't generate the video with burned-in subtitles.
https://www.youtube.com/watch?v=VvgGg7ZY534

https://www.youtube.com/watch?v=QHHrph7zDLw

**Comment by niksedk** [comment]
OK, I've downloaded the first video with "youtube-dl" and burning in with latest beta SE worked fine. 
How did you download the video from YouTube?

**Comment by SarahElGayyar** [comment]
I am usually using an Online video downloader/converter or Yout.com.

Is there anything that I can do or change in settings?

**Comment by niksedk** [comment]
Did you try the SE beta version?

**Comment by niksedk** [comment]
You can also try to re-download ffmpeg - go to Options - Settings - Waveform: click on "Download FFmpeg" - but do try the beta too :)

**Comment by SarahElGayyar** [comment]
I think the problem was just in the video I was working on, I tried another one and it worked fine with me.
Also, I tried the Beta version, as you suggested, and worked smoothly without any issues.

Thank you so much for your help, Nikolaj.
