### ISSUE TITLE
Program freezes when making an edit.

### ISSUE THREAD

**Issue by ljdssdgOjosdgOsd** [SubtitleEdit/subtitleedit#5614]
Everytime i make an edit, the program freezes and i have to wait a minute befor making another edit. How do i fix this?

**Comment by OmrSi** [comment]
Is `Auto save` on?

**Comment by ljdssdgOjosdgOsd** [comment]
> Is `Auto save` on?

I don't know, maybe. How do i check?

**Comment by OmrSi** [comment]
![image](https://user-images.githubusercontent.com/20923700/146457616-45f54796-4ed4-4307-9c5b-24316dcedaef.png)

Some formats take some time to save, so when `auto save` is on and you make an edit, it starts saving so SE freezes until it does.

**Comment by ljdssdgOjosdgOsd** [comment]
> ![image](https://user-images.githubusercontent.com/20923700/146457616-45f54796-4ed4-4307-9c5b-24316dcedaef.png)
> 
> Some formats take some time to save, so when `auto save` is on and you make an edit, it starts saving so SE freezes until it does.

I see, i have checked and auto save was not on.

**Comment by niksedk** [comment]
What is `make an edit` and could you try to re-install dot net framework 4.8: https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer

Does this issue appear both with and without video file?
Also, make sure that you use "mpv" as video player - see options - settings - video player.

**Comment by niksedk** [comment]
@ljdssdgOjosdgOsd - did you find out what caused this?
