### ISSUE TITLE
ASSA properties casing.

### ISSUE THREAD

**Issue by ThomasLeigh** [SubtitleEdit/subtitleedit#5615]
When I fill the _title_ and the _translation_ fields within ASSA properties - once the file is reloaded, the content of those two fields is lowercase - while in the same time within the actual .ass file the casing is correct.

**Comment by niksedk** [comment]
Thx for the info :)

Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by ThomasLeigh** [comment]
> Should now be fixed in latest beta:

Thank You, it’s fine now :)

**Comment by niksedk** [comment]
Thx for verifying :)
