### ISSUE TITLE
Bilibili subtitle format error cannot be fully transferred to the file to .ass 

### ISSUE THREAD

**Issue by jjigoku** [SubtitleEdit/subtitleedit#5617]
https://drive.google.com/file/d/1h_EFrPon42oA_eytNo6SnOHDhDJPxDbH/view?usp=sharing

I cannot transfer this file subtitle to this JSON format to the ass or srt completely, the original file is 30 minutes, but when switching to srt, they are only 4 minutes, I downloaded the subtitle file from bilibili.tv , Besides, can you integrate the feature to download all subtitles of a movie at Bilibili.tv?

**Comment by LeonCheung** [comment]
Try searching and deleting the "\\", that's where the parsing terminates in this case.

**Comment by jjigoku** [comment]
> Try searching and deleting the "\\", that's where the parsing terminates in this case.

Thank you, I have successfully converted  ^^
