### ISSUE TITLE
Spell check (english): Default treat word as stuck words

### ISSUE THREAD

**Issue by SuperDre** [SubtitleEdit/subtitleedit#5624]
### Discussed in https://github.com/SubtitleEdit/subtitleedit/discussions/5623

<div type='discussions-op-text'>

<sup>Originally posted by **SuperDre** December 18, 2021</sup>
Especially with tv-shows there seem to be whole subtitles which have their words stuck in the middle of a sentence (where one probably would expect a linebreak).
I normally use Spell check to find the words and fix it, but a lot of times the suggestion selects a completely different word instead of the 'broken up' version.
So I would like it to have a preference to first select the suggestion where all the characters are the same as the word it tries to replace, but broken up. for instance 'tobe' default 'to be'.
Ofcourse a complete option (like 'Remove text for hearing impeared') to fix stuck words would be even better, but I would already be very happy if Spell check would have the split version as a suggestion (a lot of times it does it already perfectly).
Also there doesn't seem to be a suggestion for 'bea' as 'be a'..</div>

**Comment by niksedk** [comment]
Should mostly be fixed in current beta
