### ISSUE TITLE
Modify Selection Error :(

### ISSUE THREAD

**Issue by MrKrio** [SubtitleEdit/subtitleedit#5625]
Error happens when i try to use Modify Selection, just on clicking on the option.
Error Message:
Ссылка на объект не указывает на экземпляр объекта.
Stack Trace:
в Nikse.SubtitleEdit.Forms.ModifySelection.Preview()
в
System.Windows.Forms.ListView.OnitemChecked(itemChecke
dEventArgs e)
в
System.Windows. Forms.ListView.WmReflectNotify(Message&
m)
в System.Windows. Forms.ListView.WndProc(Message& m)
в System.Windows. Forms.NativeWindow. Callback(IntPtr
hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam

Reinstalling helps, but not for long.

https://user-images.githubusercontent.com/23036815/146656399-bb6d4979-2e11-40c5-beca-df89c72fb05b.mp4

)

**Comment by niksedk** [comment]
Hi @MrKrio, could you attach the `jaha.ass` file too? (Github accepts .zip files)

**Comment by niksedk** [comment]
@MrKrio: do you still have the `jahy.ass` file?

**Comment by niksedk** [comment]
@MrKrio: ping
