### ISSUE TITLE
How to remove "\" from "\<br />"?

### ISSUE THREAD

**Issue by Kuju29** [SubtitleEdit/subtitleedit#5629]
How to remove `"\"` from "\<br />" I tried replacing `"\"` with a space. but it made "\n" change to "n" 

![image](https://user-images.githubusercontent.com/22098092/146877017-8127222c-956a-471a-adcf-296770ea6bf6.png)

**Comment by LeonCheung** [comment]
Why will you do that? Actually <br /> only displays in the list view. If you just want to change the style, you can edit it in the Settings:

![image](https://user-images.githubusercontent.com/494788/146878713-618fe924-b0fd-43bb-8401-d1d92c97a30b.png)

**Comment by Kuju29** [comment]
> 
I'm trying to add a space between words. because `\n` doesn't work when there is has `(` or `-` 

![image](https://user-images.githubusercontent.com/22098092/146880166-a1a911fc-e3a2-4382-b3d9-4e7b0facc78a.png)
