### ISSUE TITLE
Italic detection not working reliably with mixed italic/roman text (VobSub, OCR via Tesseract)

### ISSUE THREAD

**Issue by Ede123** [SubtitleEdit/subtitleedit#563]
The italic detection does not work reliably when the VobSubs include strings with mixed italic/roman font style.

E.g. many subtitles include something like
> NAME_OF_CHARACTER: *Only the spoken part is italic*.

But also many other compinations lead to errors, e.g.
> Some text from visible person
> *Some italic text from person not on screen*

If you need samples I can provide them (tell me how to send the subs to you).

**Comment by ivandrofly** [comment]
Add a \ before the tag like: \\ \<i>

**Comment by Ede123** [comment]
Sorry, I don't understand... Where should I add the \? And how should this fix the detection issue?

**Comment by niksedk** [comment]
SE just get the info from Tesseract, so this is a Tesseract issue...
