### ISSUE TITLE
Generate Progress Bar Doesn't start at the Beginning

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#5630]
Not sure if I'm doing it wrong but the Generate Progress Bar feature doesn't work the way I expect it to.
The progress bar starts at the center all the time. 

Is it possible to have it start at the beginning of the video? 
![Progress Bar](https://user-images.githubusercontent.com/92556454/147015460-3c4bb304-a3ad-47d9-ba41-ce73c3c0231a.jpg)

The green arrow is where the progress bar begins by default and red is where I'd expect it to begin.

Thanks!

**Comment by niksedk** [comment]
Does the script resolution match with the video resolution?
![image](https://user-images.githubusercontent.com/1261331/147057789-d34ccbd6-b1a3-42aa-9925-f82aa7f32aa7.png)

**Comment by LeonCheung** [comment]
Works fine for me. Have you tried the latest release?

**Comment by MbuguaDavid** [comment]
> Works fine for me. Have you tried the latest release?

I've tried the latest beta release, works fine. Thanks! 
The stable release 3.6.4 has the issue. 

Thank you! 
![starts at the beginning](https://user-images.githubusercontent.com/92556454/147143935-5a068ee8-3b5d-4276-a856-121023834852.jpg)

**Comment by MbuguaDavid** [comment]
> Does the script resolution match with the video resolution? ![image](https://user-images.githubusercontent.com/1261331/147057789-d34ccbd6-b1a3-42aa-9925-f82aa7f32aa7.png)

Yes, it does.
