### ISSUE TITLE
Problem happens when saving a file .json to .Srt

### ISSUE THREAD

**Issue by Kuju29** [SubtitleEdit/subtitleedit#5631]
`\\n` not work. can't new line. For new line work, I need to convert the file from '.json' to '.ass' and then from '.ass' to '.srt'

this file `.Json`
![image](https://user-images.githubusercontent.com/22098092/147024088-c8a5504d-caf8-476f-a183-7cb34efd966e.png)

Convert `.Json` to `.srt` new line is not work.
![image](https://user-images.githubusercontent.com/22098092/147024404-bf1907f4-2442-482c-9c21-bbaedf7b8372.png)

Convert `.Json` to `.ass`
![image](https://user-images.githubusercontent.com/22098092/147024587-1b2501d6-6f4f-4e23-ac66-35eba34320bf.png)

Convert `.ass` to `.srt` this new line is works.
![image](https://user-images.githubusercontent.com/22098092/147024676-29f213a5-0ce7-4e20-9331-2d4cba53d09e.png)

this is file for test : 
[Sword Art Online Alternative_ Gun Gale Online-ep-E1-th.zip](https://github.com/SubtitleEdit/subtitleedit/files/7759542/Sword.Art.Online.Alternative_.Gun.Gale.Online-ep-E1-th.zip)

Can you help me fix it or give me some advice? Thanks!

**Comment by LeonCheung** [comment]
@niksedk I think there's something fishy here indeed. e.g. when creating an SRT subtitle like:

1
00:00:01,000 --> 00:00:03,000
Line1
Line2

Then switch to .bcc format, and go to source view, the break will be parsed to `<br />`:

![image](https://user-images.githubusercontent.com/494788/147128268-5ee74876-9fa5-41c9-a9e8-fd83ff8bef40.png)


However, for Bilibili's json file, `\n` (not `\N`) should be parsed as break.

**Comment by niksedk** [comment]
Thx for the info / file :)

I had not seen a line break in this format before, but it should work better now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by Kuju29** [comment]
> ขอบคุณสำหรับข้อมูล / ไฟล์ :)
> 
> ฉันไม่เคยเห็นการขึ้นบรรทัดใหม่ในรูปแบบนี้มาก่อน แต่ตอนนี้ควรทำงานได้ดีขึ้น: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

It's working now. Thank you very much. <3
