### ISSUE TITLE
Stretch subtitle tool

### ISSUE THREAD

**Issue by jamesdeluk** [SubtitleEdit/subtitleedit#5635]
Is it possible to add a function where the subtitles are stretched until the next one? For example:

> 00:00:00.000 -> 00:00:01.000 | Hello Jack
> 00:00:10.000 -> 00:00:11.000 | Hello Jill

> becomes

> 00:00:00.000 -> 00:00:**10**.000 | Hello Jack
> 00:00:10.000 -> 00:00:11.000 | Hello Jill

Possibly also with a max-duration setting, e.g. if set to five seconds:

> 00:00:00.000 -> 00:00:01.000 | Hello Jack
> 00:00:10.000 -> 00:00:11.000 | Hello Jill

becomes

> 00:00:00.000 -> 00:00:**06**.000 | Hello Jack
> 00:00:10.000 -> 00:00:11.000 | Hello Jill

This could help when learning a foreign language, as it gives a bit more time to read the sub if the audio wasn't fully heard.

Basically, it's "Bridge gaps between subtitles..." or "Apply minimum gap between subtitles..." but the opposite, combined with "Apply duration limits...".

Cheers!

**Comment by OmrSi** [comment]
Maybe you can select all lines and use the `Extend selected lines to next subtitle` shortcut then use `Apply duration limits`?

**Comment by jamesdeluk** [comment]
> Maybe you can select all lines and use the `Extend selected lines to next subtitle` shortcut then use `Apply duration limits`?

I didn't even see that `Extend` option! I'd been looking in the Tools menu - didn't realise the right-click menu had different options :man_facepalming:

The issue with the duration limits is some subs are actually longer than e.g. five seconds, and need to be that way. I don't want to shorten them. But the `Extend` function does solve the main issue, so thanks for bringing that to my attention!
