### ISSUE TITLE
Adding new characters to a OCR language

### ISSUE THREAD

**Issue by Ninelpienel** [SubtitleEdit/subtitleedit#5636]
I want to OCR German anime Blu-ray subs and they have some special characters like Ôô and Ōō. With the German language selected, Tesseract can't recognize these characters. Is it possible to add these characters manually?

https://i.imgur.com/l6jjoai.png

**Comment by darnn** [comment]
Not for Tesseract, at least not easily within SE. You'd have to create your own train data, which is laborious to say the least. Use binary image compare as the OCR method instead. It's a bit more work but this does what you're trying to achieve.
