### ISSUE TITLE
Feature request: Can we have the ability to move a group of lines all together?

### ISSUE THREAD

**Issue by myfingerhurt** [SubtitleEdit/subtitleedit#5640]
1. Moving a group of lines all together inside the wave form
![image](https://user-images.githubusercontent.com/12622279/147409021-0c6e0e7e-7a16-4993-8331-9c36fd9a7d4f.png)

2. Moving a group of lines by increasing or decreasing the start time
![image](https://user-images.githubusercontent.com/12622279/147409082-5c2465d2-f9f6-425f-95fa-ef733e969434.png)

**Comment by LeonCheung** [comment]
@myfingerhurt Are you talking about the **Ctrl Shift A** tool, or the "Move selected lines 100ms back/forward" shortcuts?

**Comment by OmrSi** [comment]
An option is:
1. Select the lines you want to move.
2. Use `Set start and offset the rest` shortcut. It will only affect the selected lines.

The only thing not supported yet is moving multiple lines in the waveform using the mouse.
If I recall correctly, the code is there but it needs more work.

**Comment by Andrebavila** [comment]
"Shift + C" do the work.

**Comment by Andrebavila** [comment]
Shift + C works fine.

**Comment by myfingerhurt** [comment]
@LeonCheung  "drag selected lines (in the waveform using mouse) back/forth" shortcuts
@OmrSi's suggestion works for me, thanks.
@niksedk I tested your beta version from the link you provided, by `holding ctrl and drag the selected lines in the waveform` and it is working, Thank you!

**Comment by LeonCheung** [comment]
Not want to reopen this just... it doesn't work with 100% overlappd lines like working with ASSA, even by selecting via list view.
