### ISSUE TITLE
Using ♪ in OCR as substitution leads to fail

### ISSUE THREAD

**Issue by tommick** [SubtitleEdit/subtitleedit#5646]
![image](https://user-images.githubusercontent.com/29178340/147551953-66660f40-7291-41e9-8718-59c67fd59c4c.png)

Overall pool recognition of music symbol ♪ in OCR Tesseract 5.00

Kind regards

**Comment by niksedk** [comment]
Could you explain a bit more? What did you do? Cmd line or batch? How can I re-create this?

**Comment by tommick** [comment]
Hi
I did OCR VOB subtitle (Tesseract 5.0).  The symbol "♪" was very poorly recognized and mistaken with various other characters:  (e.g.: &,  », A“ ...)  
Than I was trying via Edit->Multiple replace... replace those symbols and somewhere there I got the error...
I'm sorry, I can't reproduce it again either ;-(

**Comment by niksedk** [comment]
If you find a way to re-create this do let me know :)
