### ISSUE TITLE
Crash on x265 file opening

### ISSUE THREAD

**Issue by Mmoi-Fr** [SubtitleEdit/subtitleedit#5650]
Hi,

It seems that the soft crashed when I try to open x265 files (some of them, at least).
The crash dump located the access violation in libvlccore.dll.
How can I get further info on that specific crash (to find out if it's VLC or SE related?

[FR]
Exception non gérée à 0x000007FEF1A6E9C8 (libvlccore.dll) dans SubtitleEdit.exe.3224.dmp : 0xC0000005 : Violation d'accès lors de la lecture de l'emplacement 0xFFFFFFFFFFFFFFFF.

VLC 3.0.16, SE 3.6.4 (Video + waveform enabled)

P.S: The crash happens after the subtitles are loaded (more or less 1s later the loading)

**Comment by niksedk** [comment]
I don't think the SE VLC code has change much the last 10 years... and SE handles any media file the same, so I do think this is a VLC problem.
Also, I do recommend using "mpv" as video player inside SE, as VLC has poor seeking (will be fix in VLC 4 if that ever will be released) and mpv also has better live preview (especially for different positions + ASSA).
