### ISSUE TITLE
Is it possible to set CPU priority and/or GPU-accelerated solution?

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5651]
For burning subs, a way to make full use of the hardware would be great. Not sure if it is possible...

**Comment by niksedk** [comment]
SE just uses FFmpeg from here: https://www.gyan.dev/ffmpeg/builds/

Could already be enabled... 4.x seems very fast compared to 3.x!
https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/

**Comment by LeonCheung** [comment]
Hmm, in that case, it would be very nice. Is it already enabled by default? I do see nvdec and nvenc enabled in the configurations list, but I just don't feel it, and the GPU seems not being utilized when burning it... Any hints, please?

**Comment by niksedk** [comment]
I don't have an nice graphics card... but I've made a test version here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

How does that work?

![image](https://user-images.githubusercontent.com/1261331/147776116-7647b1d2-a076-4a87-9b70-d85c0dd8644c.png)

**Comment by LeonCheung** [comment]
@niksedk That's amazing, I did see the boost. Just one thing: 

As tested, for a 200 secs video with ASSA, with default settings, having the "Enable CUDA hardware acceleration" disabled, it cost 25 secs to finish comparing to previous version of over 1 minute, which is really a huge boost. However, having that option untoggled will cost 43 secs here... though I can see the GPU is almost fully utilized in both cases. Is that expected?

**Comment by niksedk** [comment]
So with encoding "h264_nvenc" but with "CUDA" disabled, it took 25 secs?
And with encoding "h264_nvenc" + "CUDA" disabled, it took 43 secs?
And with neither "h264_nvenc" or "CUDA", it tooker a littler over 1 minute?

**Comment by LeonCheung** [comment]
Exactly, tested for times.

**Comment by niksedk** [comment]
OK, if the longer videos are the same, I guess I'll remove the CUDA option.

**Comment by LeonCheung** [comment]
Test video source info:

![mpv-shot0004](https://user-images.githubusercontent.com/494788/147806061-1eb5fd76-7384-4a85-afc1-bc8bb77da6e5.jpg)

![image](https://user-images.githubusercontent.com/494788/147806078-5d9bc332-35a5-4269-8611-3ce65d02b411.png)

Setting 1:
![image](https://user-images.githubusercontent.com/494788/147806130-7b327944-14b4-48b4-a0d1-1ef6e462df36.png)
Total burning time: 06:45

Setting 2:
![image](https://user-images.githubusercontent.com/494788/147806174-4034d485-70a2-457f-aae0-ae274f1c78e8.png)
Total burning time: 11:19

**Comment by LeonCheung** [comment]
Some other thoughts:

1. A typo: "Subtile" in the window title.
2. When burning finished, It's nice to show the time actually used, so that we can do trials and errors to find the optimized setting for different projects/cases.
3. Maybe also nice to play a sound when it finishes, so that we can go and have a cup of coffee without going back for times to check the time remaining.
4.  This is an existing issue before this commit I suppose: burning would fail if double space contained in the file path/ filename. say, when burning a video named "te  st.mp4"
