### ISSUE TITLE
An application error occurred in SubtitleEdit 3.6.4.0

### ISSUE THREAD

**Issue by hamilaci** [SubtitleEdit/subtitleedit#5662]
![application error](https://user-images.githubusercontent.com/33340444/147872118-ab43bd13-d087-4d1f-b6b8-6c6d024a0687.jpg)

**Comment by niksedk** [comment]
Thx for the info - can you re-create the issue? And how can I?

**Comment by hamilaci** [comment]
It appears several times in the past days.Both the original and the translated subtitle files are open. One of them is usually UTF-8 with BOM, the other is WIN 1250 coded. After saving the UTF converted file to Win1250, it asks whether I want to lose some characters (I never loses any of them), then the error occurs. I usually omit the error message, but it occurs several times.
RegardsLaszlo 

    On Sunday, 2 January 2022, 10:52:50 CET, Nikolaj Olsson ***@***.***> wrote:  
 
 


Thx for the info - can you re-create the issue? And how can I?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by niksedk** [comment]
@hamilaci: OK, I've tried to fix the issue here (hopefully): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

Is the bug gone?

**Comment by hamilaci** [comment]
Wow, great, now works fine.No bug. WIll let you know if occurs again.
Will you provide a setup file later so that I do not have to adjust the existing viewing, font etc. parameters?
Best regardsLaszlofrom Hungary

 

    On Sunday, 2 January 2022, 11:21:38 CET, Nikolaj Olsson ***@***.***> wrote:  
 
 


@hamilaci: OK, I've tried to fix the issue here (hopefully): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

Is the bug gone?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by niksedk** [comment]
Thx for testing :)
Beta installer link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBetaSetup.zip
