### ISSUE TITLE
"Sort By" missing "Gap"?

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5663]
Hello.
It wouldn't be interesting SE have the option "Gap" as a choice to sort by?

![E2](https://user-images.githubusercontent.com/64425752/147875298-0cb625f1-6e3a-4b87-a4b6-557e18a1810a.jpg)

**Comment by niksedk** [comment]
Added in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
It's a bit hard to use, as you cannot see the old gap after sorting...

**Comment by Andrebavila** [comment]
I don't think it's working.
It's all crazy.

![E3](https://user-images.githubusercontent.com/64425752/147879606-62b062ff-348b-4602-8d80-f8455010174d.jpg)

**Comment by niksedk** [comment]
He, yes. It's *is* crazy as the gaps are re-calculated after the sort... somewhat difficult to use as it's not possible to see the old gap.
