### ISSUE TITLE
Generate Background Box

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5667]
Guys, I don't understand.
I'm trying to generate an opaque box, but I can't do it as I wish.
Why this is happening?

![E4](https://user-images.githubusercontent.com/64425752/148068209-54303939-2afd-4c7d-89b7-510fc0a91064.jpg)

**Comment by LeonCheung** [comment]
It's not ready yet, just in beta. This is something to solve later. For the right moment, renaming the style as "Default" will do.

**Comment by Andrebavila** [comment]
Thanks, @LeonCheung!
Good luck you all!
I'm looking forward for it!

**Comment by niksedk** [comment]
@Andrebavila: Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
Does it work better now? If not, please attach .ass file before and after.

Also, the assa drawing alignment should work better now, but you can use a kind of templating in the drawing files, so LEFT, RIGHT, TOP, BOTTOM, WIDTH, HEIGHT will work inside brackets incl. normal math, e.g `[LEFT+2]` will be 2 if LEFT is 0.

**Comment by Andrebavila** [comment]
Thank you, @niksedk!
This feature is amazing! SE became an even greater subtitle editor!
I'm sure that many people will like it!
I love it!
Congratulations for everything you've done for the software!

**Comment by Andrebavila** [comment]
@niksedk , some questions:
How can I modify the opaque box after I have done one already? (Change color, size, etc). I can't see this option.

How can I select a subtitle on waveform with an opaque box in it?
No matter the video position, the selection is always at the opaque box code on list view.
"Select current subtitle while playing" doesn't even work with opaque box in the waveform.

And how can I align an one-line subtitle to a opaque box made for two-line subtitle or more?
Is it possible?

Thanks!

**Comment by niksedk** [comment]
@Andrebavila: Sorry, modification after creation is not possible. 
The boxes are calculated by first making a video with the subtitles burned-in, then getting a screenshot for each subtitle and analyzing the image to find the position + size of the subtitles by scanning for empty lines left/top/right/bottom - a little complex.

So I guess borders should be make as one of the last things - or you could use modify selection and select box styles, delete the lines, and re-do the boxes.

Will have to look at the waveform....

**Comment by niksedk** [comment]
Updated help page: https://www.nikse.dk/SubtitleEdit/Help#assa_bg_box

**Comment by LeonCheung** [comment]
I'm still puzzled here. 😂  I mean, say, left of what, or top of what? How to know the value of these constants?

**Comment by niksedk** [comment]
He, the constants are calculated from the current subtitle - does that help?

**Comment by LeonCheung** [comment]
Ah, I see, thanks.  :)
