### ISSUE TITLE
libopus audio codec gives empty waveform

### ISSUE THREAD

**Issue by 0TTA** [SubtitleEdit/subtitleedit#5668]
![Subtitle Edit 3 6 4](https://user-images.githubusercontent.com/82990310/148128572-832c1e2c-bcd5-4933-8e66-108564f7e6c3.png)

**Comment by niksedk** [comment]
Using ffmpeg or vlc for waveform generation?

**Comment by niksedk** [comment]
ffmpeg is recommended

**Comment by 0TTA** [comment]
It was vlc, ffmpeg fixed it
Thank you man!
