### ISSUE TITLE
Accentuation erros on "list errors"

### ISSUE THREAD

**Issue by matmaggi** [SubtitleEdit/subtitleedit#5669]
Hello. When I export the List Errors, all the accentuation in words are gone when I open Excel... Probably a codification issue.

Is it possible to fix it or is it an Excel issue?

![image](https://user-images.githubusercontent.com/48259053/148135585-5ad4bc10-53a4-45ac-8568-203c13e0397a.png)

**Comment by niksedk** [comment]
I don't have Excel atm... when importing data, you can choose UTF-8 as encoding... I think
