### ISSUE TITLE
"No Subtitles Found"

### ISSUE THREAD

**Issue by Subtitles4Joe** [SubtitleEdit/subtitleedit#5670]
Dear Nik or To Whom It May Concern, 

I was excited to almost be able to access transcripts of subtitles from your detailed site. I followed all the download steps for getting SubtitleEditBeta, including following through on getting the mpv and the FFmpeg until I got to the final step in Subtitle Edit 3.6.4 --> File --> Open (keep video). I keep getting the message "No Subtitles Found" (even with simple videos on YouTube where I can click on the CC so I know that it's there). Any ideas? I followed all of the steps that were explained in following video that I had hoped would get me to that final step of being able to see the subtitles:   https://www.youtube.com/watch?v=2hB1CiCeCyI 

Thanks and Happy New Year!
Joachim

**Comment by niksedk** [comment]
Hi Joachim,

Youtube videos do not have the subtitles embedded inside the video... you can use youtube-dl for downloading subtitles from YouTube 
https://github.com/ytdl-org/youtube-dl/releases or https://github.com/yt-dlp/yt-dlp/releases
