### ISSUE TITLE
new version od shortcut: Re-calculate duration of current subtitle

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#5671]
Hi.
Can you add a shortcut "re-calculate duration of current subtitle to match max CPS"?
So If I set max CPS to let say 17, I'd like to have a shortcut that will set duration of a current subtitle on waveform to match 17 CPS.

**Comment by OmrSi** [comment]
Like this https://github.com/SubtitleEdit/subtitleedit/pull/5381?

**Comment by OmrSi** [comment]
Like this https://github.com/SubtitleEdit/subtitleedit/pull/5381?

**Comment by m0ck69** [comment]
No exactly. I already tried this shortcut based on reading speed.
For me it extends duration too much.
I'd just like to have one that will use min CPS.

**Comment by OmrSi** [comment]
@m0ck69 There are two different shortcuts:
![image](https://user-images.githubusercontent.com/20923700/148402834-d4240643-c1ee-41b4-864a-924877d75ed7.png)

My PR added the second one which does exactly what you're describing.

**Comment by m0ck69** [comment]
@OmrSi I already tried those before I made a request here.
They don't work the way I'd like.

![1](https://user-images.githubusercontent.com/46628545/148405391-468ed47f-c0b7-4bae-b11f-6e261f62711c.jpg)

![2](https://user-images.githubusercontent.com/46628545/148405399-47c21dca-2a31-4751-bcad-943a88ad4b73.jpg)

**After using shortcut I get optimal 12 CPS, but I'd like 17 from Value Max chars/sec**

![3](https://user-images.githubusercontent.com/46628545/148405397-efcd7909-5a36-49da-a996-97abb0433f94.jpg)

**Comment by m0ck69** [comment]
@nikolajolsson 
thank you.
I don't want to be greedy but one more variant of the shortcut would be helpful as well.
This one
![Clipboard01](https://user-images.githubusercontent.com/46628545/148637595-bc0de1cc-f133-4715-b7eb-c012cd5cda07.jpg)

Im currently working on the subtitles which have lots of too short lines (timings) and such shortcut would help a ton.
