### ISSUE TITLE
An error message

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5673]
It occurs when trying to import plain text, but failed to reproduce it again.. yet.

![QQ截图20220107093454](https://user-images.githubusercontent.com/494788/148476944-27215139-de4a-4b00-a6d4-df279227c2d7.png)

**Comment by niksedk** [comment]
thx :)
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
Via https://github.com/SubtitleEdit/subtitleedit/commit/c91e89bad0c2ae8d9802c11224a61143efac23f4
