### ISSUE TITLE
ASSA Draw: Value blocked by text

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5675]
Could you give it a bit more space to show the complete value? Thanks!

![image](https://user-images.githubusercontent.com/494788/148557620-a250980b-0648-4689-ab60-2e6bbcf7dc7c.png)

**Comment by niksedk** [comment]
What display settings are you using in Windows?

**Comment by LeonCheung** [comment]
@nkh0472 Assuming that we are using the same system (I guess), could you help to check this? 
@niksedk Oh believe me, I'm using the default Windows fonts setting. Not sure if it's about the system (though as you can see from my other reports that I've already switched the system language to English). I've tried that on another laptop, and asked one of my friends to test it. The same issue occurs.

**Comment by nkh0472** [comment]
> @nkh0472 Assuming that we are using the same system (I guess), could you help to check this? @niksedk Oh believe me, I'm using the default Windows fonts setting. Not sure if it's about the system (though as you can see from my other reports that I've already switched the system language to English). I've tried that on another laptop, and asked one of my friends to test it. The same issue occurs.

How to open this window? I usually work with srt files, so I'm not very familiar with ASSA tools.

**Comment by LeonCheung** [comment]
@nkh0472 Try this:

https://user-images.githubusercontent.com/494788/148641080-158ef1e4-7e62-4726-af6d-6a51b7754896.mp4

**Comment by nkh0472** [comment]
![image](https://user-images.githubusercontent.com/67589323/148641241-c1384f00-682d-4e49-9836-26a60318bf6e.png)
Yep, there is something wrong with displaying.

**Comment by LeonCheung** [comment]
@nkh0472 Hmm, but it works well on @niksedk side (always XD), I guess it's a problem for Chinese OS, not sure. It's not the first case. Anway, thanks, man!

**Comment by nkh0472** [comment]
By the way, I found another unusual display, but it looks not a big problem yet: the text position in the red boxes seems to be too low, making the text truncated.
![image](https://user-images.githubusercontent.com/67589323/148644579-ab5be1d4-946a-4853-b004-07569c42a2cf.png)
![image](https://user-images.githubusercontent.com/67589323/148644617-4a21c815-c43e-4343-92ab-2027bba92f17.png)

**Comment by niksedk** [comment]
How is latest Assa Draw + latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
I think I figured out why...

Usually, I only check display settings via Settings > System > Display:
![image](https://user-images.githubusercontent.com/494788/148649932-83622dc6-f9ab-42ab-a3e3-96a12714cc53.png)

Everything seems okay, right? But I just noticed that there are more related settings located in Settings > Ease of Access > Display:

![image](https://user-images.githubusercontent.com/494788/148649782-2fc32994-d00d-464b-9506-5702c278609a.png)

After setting the first bar from 125% to 100%, it works fine now... Gosh, can't imagine it's a factory default setting. 

Both fixes work well now. Just... everything becomes smaller. I need some time to get used to it. XD

Btw, now I've set everything back to 100%, but the word Category is still blocked:

![image](https://user-images.githubusercontent.com/494788/148650145-610ef478-516d-43d8-a4d3-45f8049ea105.png)

**Comment by niksedk** [comment]
How does AssaDraw 0.20 look on your display?

**Comment by LeonCheung** [comment]
So great! And new features!! 👍 

![image](https://user-images.githubusercontent.com/494788/148650646-3eddfbe2-9486-480c-add5-f11604fdde41.png)

**Comment by LeonCheung** [comment]
@niksedk Maybe not necessary to open a new report but when clicking the Manage button, an error occurs, I bet it's due to the latest commit:
![QQ截图20220109131959](https://user-images.githubusercontent.com/494788/148672949-eff1b2cb-e3cc-4311-806f-c66ab4fc402b.png)

**Comment by niksedk** [comment]
thx, should be fixed now :)
