### ISSUE TITLE
Modify Selection error

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5676]
![modify selection](https://user-images.githubusercontent.com/494788/148563511-df949d77-c879-49bc-8ddf-971fe713fcab.png)

**Comment by niksedk** [comment]
How can I re-create this error?

**Comment by LeonCheung** [comment]
https://user-images.githubusercontent.com/494788/148566991-531e4f16-24a2-4082-a6d8-b8bedcbf1987.mp4
