### ISSUE TITLE
Font rendering problem in image export

### ISSUE THREAD

**Issue by red4dj** [SubtitleEdit/subtitleedit#5678]
Fonts don't render correctly in the image exporter when using embedded fonts (i.e. `<font face="Imprint MT Shadow">`) It appears the font selection in the exporter window is clashing with the inline font.

For single-line subs, the exporter font is chosen, even though the inline font should override it.
![Single-Line Rendering](https://user-images.githubusercontent.com/35785346/148637490-dd2d6ec9-7d0d-4a7b-928e-ff04e4db8b2f.png)

For multi-line subs, the top line changes to something something default (or at least Arial for me) and the bottom line gets the exporter font.
![Multi-Line Rendering](https://user-images.githubusercontent.com/35785346/148637494-732e0b7a-6d6d-496e-98bb-871c9abd232b.png)

**Comment by niksedk** [comment]
hi @red4dj, thx for the info - tried to fix it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by red4dj** [comment]
It's better, but still not fixed. Single line still renders in export font, multi-line is correct font over export font.
![Screenshot 2022-01-08 040010](https://user-images.githubusercontent.com/35785346/148638497-163c07de-dd68-4d21-8f43-3a553b56d2ec.png)

**Comment by niksedk** [comment]
Thx, tried again... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by red4dj** [comment]
It's so close! All the fonts are correct, but the spacing is strange. The top row of multi-line gets the spacing of the export font.
![Screenshot 2022-01-08 191805](https://user-images.githubusercontent.com/35785346/148664382-5806dce9-310a-4fa7-ad62-f130a2e78bc6.png)
![Screenshot 2022-01-08 191949](https://user-images.githubusercontent.com/35785346/148664383-978d5e1e-b11f-4a3b-af9d-312a093cbe9d.png)

**Comment by niksedk** [comment]
OK, tried to fix this too: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
Better ?

**Comment by red4dj** [comment]
Hey, it's all fixed! Thanks' so much!
