### ISSUE TITLE
[Bug?] Missing PGS Subtitle Lines

### ISSUE THREAD

**Issue by peter-qgd** [SubtitleEdit/subtitleedit#5680]
Hello, I just realized of a weird issue regarding a specific PGS subtitle, which despite it is being shown completely
while playing the MKV file with a video player, it has missing lines when opening it with Subtitle Edit. Opening the demuxed
PGS track with both (edit/OCR) options, shows it like this:

![sub-pgs-edit](https://user-images.githubusercontent.com/82705380/148643539-a1435138-7959-4db5-a161-1c16365865a4.png)

After that "148" line, there should be another one showing a "Mary wants to get off a letter to her fiancee" graphic line, but  it is missing. And it's like that along the whole subtitle.

Curiously enough, dropping the full MKV file to the program, the subtitle will be opened showing the al the lines, although there are many repeated ones:

![sub-pgs-edit-mkv](https://user-images.githubusercontent.com/82705380/148643738-65349bd0-30a0-4a99-a805-37489f490655.png)

I leave you the relevant PGS file attached.

![PGS SUB](https://user-images.githubusercontent.com/82705380/148643901-3847cd4a-e7f8-4363-85ca-81c75f420dbc.jpg)

Thanks.

**P.S.** jpg file has to be renamed to ".rar", since I can't attach it as such.

**Comment by darnn** [comment]
Huh, yeah, weird. opening the file in SupRip shows 1,336 subtitles, SE only shows 832.

**Comment by niksedk** [comment]
Thx :)
Yes, SE had a problem with merging fading lines... should be better now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip 
Is everything okay now for you guys?

**Comment by darnn** [comment]
Seems good over here!

**Comment by peter-qgd** [comment]
It is working fine in the last beta. Thanks.
