### ISSUE TITLE
BG Box: setting resolution issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5682]
It occurs when you haven't set the resolution after loading the video, and the tool will ask whether to set it. If click "Yes", the result looks not right. But if we delete that box and try to redo it, the result looks okay. 

https://user-images.githubusercontent.com/494788/148650433-6549c477-e092-4ca3-8937-c8e013d72c76.mp4

**Comment by niksedk** [comment]
thx :)
Fixed in f0fe1844c07643cbd54e5f58e54eccea64e80c22
