### ISSUE TITLE
Some strings needed to be put into LanguageMaster.xml

### ISSUE THREAD

**Issue by nkh0472** [SubtitleEdit/subtitleedit#5685]
1. Mainly in "Netflix quality check", which should be displayed in Chinese instead of English:
![Netflix 1](https://user-images.githubusercontent.com/67589323/148667686-7e6d254f-06c3-41c9-b85e-b16f526c4128.png)
![Netflix 2](https://user-images.githubusercontent.com/67589323/148667691-9e0d4bd4-5483-45ec-8dfc-917dbcfe116e.png)

2. And in "settings - tools", the text "Misc":
![settings](https://user-images.githubusercontent.com/67589323/148667754-144e4ea7-16f3-48b5-ab00-39bbb2d98db7.png)

3. In “Advanced Sub Station Alpha properties":
![image](https://user-images.githubusercontent.com/67589323/148668156-fa841102-3a4d-4e63-923e-5c5c769271d2.png)

---
Also, I found some minor bugs:
4. In "batch convert":
![batch convert](https://user-images.githubusercontent.com/67589323/148667822-39707441-1d01-4fda-bf26-3e17c0e1e98e.png)

5. In "generate video with burned-in subs":
![burned-in sub](https://user-images.githubusercontent.com/67589323/148667998-7afee3ef-173f-4b21-b0ff-8f60e1e1fbc5.png)

**Comment by niksedk** [comment]
The "netflix quality check" I really want to redesign with some fixing abilities too... at some point, so atm I consider it as kind a work in progress...

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
