### ISSUE TITLE
Lines are jumping when collaborating with people at the same time and involving the operation "merging lines"

### ISSUE THREAD

**Issue by ChaoZhang123** [SubtitleEdit/subtitleedit#5688]
It is a nice tool to collaborate on the same subtle file concurrently to proofread and finalize the captioning. Thank the maintainer and all the developers for such a helpful tool.

One minor issue during the concurrent collaboration is that lines are jumping when someone is merging lines in the upper region of the subtile; as I observe, the mind is very sensitive to this line jumping, and some people in the collaboration feel a bit annoyed.

Perhaps it is because I don't know how to use the software properly, if so, please point it out. Thanks. If not, I am suggesting a visual feature, that is, when merging lines, can the merged-from lines be blank lines visually instead of being removed? So that visually, the lines still stay put and it is visually friendly for people editing in the lower region of the subtitle.

Have a peaceful day.

**Comment by librafrog** [comment]
Yep. that's the way - probably will be good. Until then you can set them target lines: Person 1 - 100-220 Person 2 - 230-400 & etc.
Maybe that way it won't get flipped to often 😏
