### ISSUE TITLE
OCR Binary issue

### ISSUE THREAD

**Issue by Masina86** [SubtitleEdit/subtitleedit#5690]
Hello, when i OCR sometimes with binary i have problem with merged letters i will post SS to make it clearer.

![1](https://user-images.githubusercontent.com/73963066/148862109-34a9b4ef-3df5-40c4-8f01-0fe21161fa3a.png)
![2](https://user-images.githubusercontent.com/73963066/148862116-d8c53285-3995-4cbb-9e2c-66c6ab919d92.png)
![3](https://user-images.githubusercontent.com/73963066/148862119-86ea3e01-1040-42ab-97af-3fa641181ec2.png)

I tried everything i increases the number in pixel in space i tried it with 4,5,6,7 it helps on some lines but it messes other lines, i tried with invert colors options still nothing, tried with increasing the image pre-processing threshold still not coming out perfect.
Anyone has some suggestions or someone had the same problem?

**Comment by niksedk** [comment]
Latest beta version has a word split list... I've tried to generate one for Macedonian in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

It should help a little?

Macedonian  word split list: https://github.com/SubtitleEdit/subtitleedit/blob/master/Dictionaries/mkd_WordSplitList.txt

**Comment by Masina86** [comment]
Tried the beta version it helped little. Out of 1500 lines text it fixed 154 errors, but i fixed manually about 100 more. Most of the errors come from conjunction words like "do", "and" but on Macedonian. Thank you for your hard work Nikse and the community i love subtitle edit. I guess i will need to add words in the wordsplitlist, but there are so many combinations with conjunctions.

**Comment by niksedk** [comment]
Are "do" and/or "and" one letter words? I removed the one letter words from the split list... I could re-add some, like for English I added "I" and "a".

**Comment by Masina86** [comment]
It will take me some time to make decent word list coz the list is big. Something else is bugging me even i got the word in worrdsplitlist still it is not find as error and fixed see the ss


![4](https://user-images.githubusercontent.com/73963066/149193204-06f5c256-74cd-4314-9cd8-99751205ea1c.png)

Am i doing something wrong, something else is the problem? Yes the document is saved double checked it.

**Comment by niksedk** [comment]
Could you write this a text, so I can test it?

**Comment by Masina86** [comment]
Човечката фасцинираност со небото не исчезнала до денес.
