### ISSUE TITLE
Using libse on .net 6

### ISSUE THREAD

**Issue by groupmsl** [SubtitleEdit/subtitleedit#5697]
Writing the most basic code to load a subtitle works for me in a .net framework project, but not a .net 6 project.

I've built libse 3.6.4. In my .net framework project I add the framework dll as a dependancy. In my .net 6 project I add the .net standard dll as a dependancy.

I'm running the same code in both projects:

```csharp
Subtitle subtitle = new Subtitle();
System.Text.Encoding e;
SubtitleFormat sf = subtitle.LoadSubtitle(@"C:\subs\41089-003.stl", out e, null);
if(sf == null) Console.WriteLine("NULL!!");
```

On .net framework the file is loaded fine. On .net 6, sf is null.

I'm sure I'm doing something stupid, but any assistance would be appreciated!

**Comment by niksedk** [comment]
Could you try the dot net 6 branch? https://github.com/SubtitleEdit/subtitleedit/tree/feature/dotnet6-test

It might be because not enough encoding are enabled by default, see https://stackoverflow.com/questions/37870084/net-core-doesnt-know-about-windows-1252-how-to-fix

**Comment by groupmsl** [comment]
You were right - it was because not enough encodings were enabled by default. I added this to the project:

```xml
<ItemGroup>
  <PackageReference Include="System.Text.Encoding.CodePages" Version="4.3.0"/>
</ItemGroup>
```

And this to my code:

```csharp
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```

(As suggested by the link you provided)

All this was on the master branch using the .net standard dll. From very limited testing (the code in my original post) this seems fixed for me - thank you for the help. Do you still want me to try the .net 6 branch for another reason?

**Comment by niksedk** [comment]
No need to test the .net 6 branch, and thx for reporting back with results and details :)
