### ISSUE TITLE
Import from plain text does not work

### ISSUE THREAD

**Issue by hamilaci** [SubtitleEdit/subtitleedit#5698]
Hi you recently sent me a beta version that works fine.
I found another bug in this beta version (https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBetaSetup.zip) that means it fails to import plain text (subtitle plus time codes).
Could you help please?
Regards
Laszlo

**Comment by niksedk** [comment]
What's not working exactly? Import plain text works fine for me...

**Comment by hamilaci** [comment]
Import is in bad format, timing in one line, text in another line.
Will retry tomorrow.
Thanks
Laszlo

⁣Mobilról küldve​


-------- Eredeti üzenet --------
Feladó Nikolaj Olsson ***@***.***>
Elküldve: Wed Jan 12 21:19:42 GMT+01:00 2022
Címzett: SubtitleEdit/subtitleedit ***@***.***>
Cc: hamilaci ***@***.***>, Author ***@***.***>
Tárgy: Re: [SubtitleEdit/subtitleedit] Import from plain text does not work (Issue #5698)

What's not working exactly? Import plain text works fine for me...

**Comment by niksedk** [comment]
Could you attach your source file?

`Import plain text` imports text... not time codes.

**Comment by hamilaci** [comment]
So far I could use plain text import for times codes as well, not only text - used to work fine before the recent beta program.
OR how can I import from Youtube in two steps, one for text, one for time codes? I used to do it in one step so far.
See attached.
Laszlo

 

    On Thursday, 13 January 2022, 11:32:21 CET, Nikolaj Olsson ***@***.***> wrote:  
 
 


Could you attach your source file?

Import plain text imports text... not time codes.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  
00:02
[Music]
00:15
dear mom
00:18
i know you're wondering
00:22
if you should keep me
00:26
and if you need me
00:30
dear mom
00:33
i hope you get this message
00:37
i hope you hear me
00:41
can you feel my heartbeat
00:47
a few more months you'll get to meet me
00:55
just hold on
00:57
a little while
00:59
[Music]
01:03
it'll be worth it once you see me
01:08
i've got your nose i've got your eyes
01:13
dear mom
01:16
i've got your smile
01:24
dear mom
01:27
i wanna hear those ocean waves
01:31
i wanna walk with you
01:34
and feel the warmth of a summer day
01:40
dear mom
01:42
i just wanna hold your hand
01:47
i hope you understand
01:51
this is all god's plan
01:56
a few more months you'll get to meet me
02:04
just hold on
02:06
a little while
02:09
[Music]
02:12
it'll be worth it once you see me
02:17
i've got your nose i've got your eyes
02:22
dear mom
02:25
i've got your smile
02:29
you'll know love
02:32
like you've never known
02:36
and maybe one day when i'm older i'll
02:41
give you a grandchild of your own
02:44
[Music]
02:48
she'll have your nose she'll have your
02:51
eyes
02:53
dear mom
02:56
she'll have our
02:58
smile
03:02
[Music]
03:10
[Music]
03:23
foreign
03:35
you

**Comment by hamilaci** [comment]
transcript source:An unborn baby sings from the womb: LifeSite's official 'Dear Mom' music video - YouTube

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
An unborn baby sings from the womb: LifeSite's official 'Dear Mom' music...


 |

 |

 |






 

    On Thursday, 13 January 2022, 11:32:21 CET, Nikolaj Olsson ***@***.***> wrote:  
 
 


Could you attach your source file?

Import plain text imports text... not time codes.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hamilaci** [comment]
After playing with different settings, now it works fine again.Thanks for helping again.


 

    On Thursday, 13 January 2022, 12:09:20 CET, Nikolaj Olsson ***@***.***> wrote:  
 
 


I think you need File - Open...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
