### ISSUE TITLE
Subtitle's Time Codes Totally Messed Up After Changing FPS

### ISSUE THREAD

**Issue by peter-qgd** [SubtitleEdit/subtitleedit#5700]
Hello, I noticed a very weird behavior while trying to change a PGS subtitle framerate, which makes all its time codes get
erroneously altered. The next video sample shows exactly how:

https://gofile.io/d/2EkzgO

I'm using latest stable version (I got the same results with last beta as well), on Windows 10 Enterprise, 21H2 build 19044.1348, x64 and latest dotnet version:
 
![image](https://user-images.githubusercontent.com/82705380/149244962-729c3753-f2eb-4390-ae32-b1a2b0775a8e.png)

Curiously enough, I tried it on a fresh Windows 10 VM, and there were no problems there.

**Comment by niksedk** [comment]
Could you re-test latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by peter-qgd** [comment]
Thanks, it works fine now. Although it is still a mystery to me why not only the last stable version but other betas as well, started giving this problem all of the sudden in my main system, even when they worked fine before; and they still work fine on other similar systems. I bet it might have to do with some recent Windows' updates I applied, otherwise I don't know.

**Comment by niksedk** [comment]
I think it has to do with `decimal symbol` in some culture info settings...

![image](https://user-images.githubusercontent.com/1261331/149335931-4cddd00d-0759-4fc2-ac41-ca34a9cfe3a2.png)

**Comment by niksedk** [comment]
I should probably test more with  other culture settings ;)
