### ISSUE TITLE
The latest libmpv has been renamed

### ISSUE THREAD

**Issue by nkh0472** [SubtitleEdit/subtitleedit#5702]
I haven't tested more complex rendering in Subtitleedit, but I always use the [latest binary dev build of libmpv](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/) while editing SRT subtitle files, and I haven't found compatibility problems. Since not a long time ago, I found the latest libmpv under Windows has been renamed to `mpv-2.dll` while the original filename is `mpv-1.dll`.

By a simply `diff`, I found the mpv-2 removed the following APIs:
```
diff -r D:\Libraries\libmpv\mpv-2\mpv.def D:\Libraries\libmpv\mpv-1\mpv.def
15a16
> mpv_detach_destroy
24a26
> mpv_get_sub_api
31a34,39
> mpv_opengl_cb_draw
> mpv_opengl_cb_init_gl
> mpv_opengl_cb_render
> mpv_opengl_cb_report_flip
> mpv_opengl_cb_set_update_callback
> mpv_opengl_cb_uninit_gl
41a50
> mpv_resume
48a58
> mpv_suspend
```
These APIs do not seem to be used in this project, so I boldly assume that migrating to the new version of libmpv does not require complex work.

About migrating to `mpv-2.dll`, the following issue and related commits might be useful.
https://github.com/stax76/mpv.net/issues/356

**Comment by niksedk** [comment]
Was fixed here: https://github.com/SubtitleEdit/subtitleedit/commit/e0acd872ced4ad2927ff81d641f04a8d50338a03 + https://github.com/SubtitleEdit/subtitleedit/commit/a6a3ac9fd1287ece5b7b5ea11679229a8a65fdad :)

**Comment by niksedk** [comment]
And thx for the diff - did not know the changes, but I did test of course :)

**Comment by nkh0472** [comment]
That`s cool!
