### ISSUE TITLE
Batch generate waveforms doesn't have the option to generate the scene changes

### ISSUE THREAD

**Issue by JDTR75** [SubtitleEdit/subtitleedit#5704]
Hello,

I'm using version **3.6.4 beta 335**, and the option (check box) to generate the scene changes is not there now.

Thanks in advance.

**Comment by niksedk** [comment]
Thx - was really a bug... how is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
