### ISSUE TITLE
Drag-drop to open new sub retains first line of previous sub

### ISSUE THREAD

**Issue by beeeeswax** [SubtitleEdit/subtitleedit#5705]
This one is a bit odd, while re-visiting some of my previous OCR jobs for errors, I noticed that sometimes the first line of the previous sub was being retained when dragging and dropping the next sub into the SE window.  It's not a GUI-only problem because if I [Save As] the srt to a new file, that incorrect first line does get written.

I'm trying to narrow this down now but it seems if I just drag .srt's one after another into the window without actually doing anything with them, it works as expected but when I fully process an srt, re-save and then drag and drop a new one, I get the problem.

My workflow at the moment is drag-drop an .srt file into the SE window.  Remove all colour formatting.  Ctrl-F and search for some common errors, F3 through correcting errors.  Remove text for HI, Fix Common Errors, re-add colour (dark grey for HDR movies), save.  Now when I drag drop the next .srt, the first line from the last sub it retained.

**Comment by darnn** [comment]
This happens to me as well, but I also haven't found a way to quickly and reliably reproduce it.

**Comment by niksedk** [comment]
Hm, I've not been able to re-create this, but I tried to minimize the possibility here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
Can any of you re-create the issue with latest beta?
Also, this could an old bug?

**Comment by beeeeswax** [comment]
Thanks Nik, just tried the new beta and I can't reproduce it now so I think whatever you did, you cracked it.  I've done 6 subs back-to-back using the same SE instance, drag/drop, the same workflow and not seen the first line stick once.

**Comment by darnn** [comment]
It only happens to me every few days, but I'll let you know if it shows up again. Since it isn't for beeeeswax, I'm fine with considering it closed.

**Comment by niksedk** [comment]
I will let this be open for a little while... do report back if the issue happens again.
