### ISSUE TITLE
The text box will be obscured if the text image is too large.

### ISSUE THREAD

**Issue by Kuju29** [SubtitleEdit/subtitleedit#5706]
The text box will be obscured if the text image is too large.
![image](https://user-images.githubusercontent.com/22098092/149554953-7c7539b8-b88e-460e-83b2-9ac0e6ac7ba3.png)

**Comment by Kuju29** [comment]
> How can I re-creates this? Where is this and could you attache the image/sub?

![image](https://user-images.githubusercontent.com/22098092/149555726-aa5e1111-544b-40b8-b14a-08aed5ad2298.png)
this image for test
![0_00_14_347__0_00_17_057_0056400000012800072001280](https://user-images.githubusercontent.com/22098092/149555826-f01eb7cf-12b3-4aa0-824c-a9b73c027f60.jpeg)

**Comment by Kuju29** [comment]
I tested alternating colors on 1 image, it doesn't work. But with many images it works. This is the setting I use.
![image](https://user-images.githubusercontent.com/22098092/149556505-e3e62961-c9e4-42ca-a22d-8e9f406bd406.png)

**Comment by niksedk** [comment]
Thx for the images :)

Hopefully fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by Kuju29** [comment]
> Thx for the images :)
> 
> Hopefully fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

Thank you for all your hard work on this. 👍 💯 🥇

**Comment by Kuju29** [comment]
@niksedk 
Make the text without spaces? I added a text to the image but the text has spaces.
![image](https://user-images.githubusercontent.com/22098092/149602525-5d66212f-0e4b-4e81-a327-92de01ea2bb2.png)

**Comment by Kuju29** [comment]
It may also be due to the large of the image file. Make pixel conditions inactive.

**Comment by Kuju29** [comment]
I edited to increase the number of pixels and it worked.
