### ISSUE TITLE
TTML support?

### ISSUE THREAD

**Issue by JW022834756473837** [SubtitleEdit/subtitleedit#5708]
In Youtube, the only format that supports both styling and positioning (though it is in partial implementation. 
https://support.google.com/youtube/answer/2734698#zippy=%2Cadvanced-file-formats

**Comment by niksedk** [comment]
SE has support for lots of TTML based formats... try "Timed Text 1.0" or "ITunesTimedText".
What exactly does YouTube support of TTML?

**Comment by liamzachs** [comment]
It also supports TTML2
