### ISSUE TITLE
Missing/Joint Lines when Importing/OCRing

### ISSUE THREAD

**Issue by cornbreadman** [SubtitleEdit/subtitleedit#5713]
Hello! When I import .sup subtitles, I noticed lines that are same as the next line are joint together into 1 line by default. Is there a way to turn this off? It happens even if the same two lines are different colors.

![Subtitle Edit 1](https://user-images.githubusercontent.com/46472554/149802208-3a004330-4073-41f3-9f36-6122c465bd06.PNG)

**Comment by niksedk** [comment]
Could you zip and attach the sup file?
Not option to turn this off atm...

**Comment by niksedk** [comment]
Could even be a recently fixed bug - could you try latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by cornbreadman** [comment]
I am using 3.6.4 / Screenshot is from 3.6.4

**Comment by niksedk** [comment]
thx for the files :)

Hm, some sup files have multiple images and they really need to be merged.

I've looked at these two files a bit, and I cannot atm see any differences between a sup where lines should be merged and these two sup files. I guess the palettes could examined a bit more... and/or perhaps some kind of option to disable merge of equal images with no gap between them.

But it is really two separately spoken entries for both of these sups?

**Comment by cornbreadman** [comment]
Yes.

**Comment by niksedk** [comment]
I've added two new settings regarding bd sup merging in Settings.xml.

By default, SE will try to guess if to merge or not, slightly improved but no way 100% correct.
The two new settings:
BluRaySupSkipMerge: if true, Never merge
BluRaySupForceMergeAll: if true, force merge all (no guessing + overrides skip merge)

Updated beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
If anyone knows a better way, do let me know!
