### ISSUE TITLE
Missing Split line at cursor position in textbox context menu and other menus in lastest versions (betas)

### ISSUE THREAD

**Issue by DricaAlmeida** [SubtitleEdit/subtitleedit#5717]
SE 3.6.4

![Capturar](https://user-images.githubusercontent.com/97911653/149823360-abd7c070-7d13-464c-8352-16850c4dfd5e.PNG)

SE 3.6.4 lastest Beta

![Capturar2](https://user-images.githubusercontent.com/97911653/149823473-09aab727-e1af-44ac-9129-a712fcd9f11b.PNG)

**Comment by niksedk** [comment]
Thx :)
Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
