### ISSUE TITLE
Finnish dictionary

### ISSUE THREAD

**Issue by ElleshaHackett** [SubtitleEdit/subtitleedit#5718]
Can a Finnish dictionary be added please?

**Comment by niksedk** [comment]
Check the Finnish version under Releases

**Comment by ElleshaHackett** [comment]
I am using 3.6.4. Is there a special Finnish release?

**Comment by niksedk** [comment]
Yes, read more here: https://github.com/SubtitleEdit/subtitleedit/releases

**Comment by ElleshaHackett** [comment]
I see, but it's unclear to me as to why the Finnish version is a separate binary. Wouldn't it be more logical to have only one binary and just add the Finnish language as a language file, as with all the other languages?
