### ISSUE TITLE
Is there a way duration to shorten each text's time all at once?

### ISSUE THREAD

**Issue by Kuju29** [SubtitleEdit/subtitleedit#5723]
Is there a way duration to shorten each text's time all at once?
Following the visual sync with the video. The text has stick together. I'd want to shorten the duration of the text to make it look more natural.
want to drop about 24.

![image](https://user-images.githubusercontent.com/22098092/150265650-560cb870-0eca-4558-bfa3-f67417f0c9e4.png)
![Desktop-2022 01 20---09 42](https://user-images.githubusercontent.com/22098092/150265600-d286d0a9-4298-45f4-b9b9-471108db191b.gif)

and one more problem, text obscuring % in OCR image. on ไทย language
![image](https://user-images.githubusercontent.com/22098092/150265995-9e6ed230-1553-492d-a443-66dc9cf3893d.png)

**Comment by LeonCheung** [comment]
@Kuju29 For the first question, I think you need this:

![image](https://user-images.githubusercontent.com/494788/150459401-40ece1c0-8604-4134-b0e4-99f7c6fd38f5.png)

**Comment by Kuju29** [comment]
> 

Oh! Thank you 👍
