### ISSUE TITLE
Questions on .SCC

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5724]
Something not right here maybe?

https://user-images.githubusercontent.com/494788/150274110-aa331547-428f-4255-91b2-886f774ef83c.mp4

**Comment by PreetM07** [comment]
@LeonCheung This is the coolest way to log an issue. I myself was reading some logged issues and was not able to understand many of them, maybe due to not aware about some feature and its use case or structures of writing the issues which varies person to person. But this is cool. Kudos!

**Comment by LeonCheung** [comment]
@PreetM07 Yes. One video saves many words. XD
