### ISSUE TITLE
ASSA: Copy and paste issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5732]
![assaissue](https://user-images.githubusercontent.com/494788/150963962-e20908a3-f33e-4725-8004-c20e494cbcc3.gif)

Reproduce: Select a line then Ctrl C, Ctrl V

Another thing is, it doesn't copy the original style name. Instead, It will assign the style name "Default" to all new lines.

**Comment by niksedk** [comment]
Do you expect the source style/actor... or the style/actor from the current line?

**Comment by LeonCheung** [comment]
Yes, for this format, it should be the default behavior,  The reason is simple:  Why is the Default style more expected than the current one?  XD  And just imagine when duplicating a set of effect lines, say, bgbox+draw or something to reuse them somewhere else,  as sort of templates.  Currently, it has to be done in source view.

**Comment by niksedk** [comment]
Like this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Thx, list update well fixed, just something left:
![test2](https://user-images.githubusercontent.com/494788/151004801-ac3e04b2-5bb9-465e-ad8b-e45cd268c4a8.gif)

Btw, this test file doesn't have any style called "Default“...

**Comment by LeonCheung** [comment]
It should copy exactly **everything** from the selected line(s), including:
![image](https://user-images.githubusercontent.com/494788/151007148-edb82b47-25c8-48a6-bec6-1d1a0466197b.png)

Yes, including timecodes. You know, in ASSA, it's very common that we need to have 100% overlapped captions (mainly for effects). But I know there might be a concern here, like: "What about the current Ctrl C and Ctrl V behavior, the sort of no overlap duplication?". Actually, I think we can keep both simply by assigning a different shortcut for the 100% overlapped paste behavior. (e.g. use **Ctrl Alt V**)

**Comment by LeonCheung** [comment]
Actually, the Colum Paste tool is supposed to perfectly do the job, and it does work fine for that except lacking support for pasting all ASSA-related stuff.

![image](https://user-images.githubusercontent.com/494788/151014650-cb9b1569-6126-423d-9a4b-08f7b7f2e095.png)

**Comment by niksedk** [comment]
OK, tried to improve the assa support... is this better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
That's perfect! You are awesome! 👍 👍

**Comment by LeonCheung** [comment]
@niksedk Just noticed that it doesn't work well with comment lines:

https://user-images.githubusercontent.com/494788/151399829-1833b509-2117-46db-945a-71b04def4405.mp4
