### ISSUE TITLE
Merge already times short lines without the selected profile rules. 

### ISSUE THREAD

**Issue by ghalymt** [SubtitleEdit/subtitleedit#5734]
Can we add a feature to merge lines without breaking the selected profile rules (duration of the subtitle block, single line length).

**Comment by niksedk** [comment]
Could you give some examples where this does not work? 
Please attach screenshots + sample files.

**Comment by ghalymt** [comment]
My profile is 42 cpl, 2 lines, 7 second max. I am timing the lines as
single lines then merging it with merging lines 84 maximum paragraph and
2000 ms maximum between lines. subtitle edit after merging auto break
according to my breaking lines, which is a little strict. Is it possible to
skip merging the lines IF the outcome paragraph has a single line more than
42 or more than 7000 ms (according to the profile).
Thank you. Regards

**Comment by niksedk** [comment]
And "Tools" - "Merge short lines" does not work? Please attach sample files + screenshots + what was expected...
