### ISSUE TITLE
An error with beta 420

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5736]
Not sure how to repeat this but I got it twice today, when reopening SE then trying to load a new file:

![QQ截图20220126221608](https://user-images.githubusercontent.com/494788/151197753-da32023e-7cdf-48d5-bbcf-0f345c3eb4b0.png)

**Comment by niksedk** [comment]
OK, is this any better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Will try to use this beta for a while, so far so good. Thx!
