### ISSUE TITLE
Issue with "Allow overlap"

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5740]
When enabling "Allow overlap" (or holding **Shift** then drag), sometimes the operation isn't very reliable. Another thing is,  when hitting undo after that, the text changed:

https://user-images.githubusercontent.com/494788/151388187-9ddc93a2-ed5a-446c-bd80-3e2e4c4d6b83.mp4

**Comment by niksedk** [comment]
Is this better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Yeah, it's better! A perfect fix having this option toggled. However, it's the same as before when using Shift + drag without toggling it.

**Comment by niksedk** [comment]
OK, hopefully fixed now too: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
