### ISSUE TITLE
[Question/Suggestion]Coloring the displaying line(s) on the list view

### ISSUE THREAD

**Issue by vincentkilua** [SubtitleEdit/subtitleedit#5742]
It's embarrassing to say... well I always get lost after I played a bunch of lines and couldn't find the current displaying line(s).
Then I wonder is there a switch, which could turn on coloring of the displaying lines that I couldn't find.

I am now using the shortcut that "Go to previous subtitle(from video position)" under "video" and indeed it works fine, but I still hoping for the coloring feature and curious if anyone shares similar thoughts with me.

BTW there is shortcut "Three seconds back" under "video" and it works perfectly, the only problem is the "Three seconds forward" is somehow missing. I'm using the selected time forward as an alternative, it is not that big a deal so... just a friendly reminder. 

The version I'm using is the SubtitleEdit-3.6.4-Setup.zip on a Win 10 machine, and thanks for the tool it is really useful!

**Comment by niksedk** [comment]
I'm not really sure what you mean... but we several shortcuts that might work for you:
![image](https://user-images.githubusercontent.com/1261331/151694993-77b4992f-d4c3-4c3c-8862-fbe3ee5436eb.png)

![image](https://user-images.githubusercontent.com/1261331/151695005-0072e576-f0cf-44b8-b025-2bc334ceb37e.png)

Also,  setting this might be what you want:
![image](https://user-images.githubusercontent.com/1261331/151695018-f9e0d544-78c0-46a1-9088-b9225dc9768e.png)

**Comment by vincentkilua** [comment]
> I'm not really sure what you mean... but we several shortcuts that might work for you: 
>……

Thanks for the help, the shortcuts are really useful.
And sorry for my poor English, let me elaborate with a screenshot of Aegisub

![image](https://user-images.githubusercontent.com/23117405/151695431-933e2c29-4de0-4227-9a7b-ad521ffb8c97.png)
The green one is the selected line, while the yellow highlighted one is the line that is displaying.
I wonder if this feature is supported by SubtitleEdit, or will it?

**Comment by niksedk** [comment]
yellow?

**Comment by vincentkilua** [comment]
> yellow?

yes, line #125 was highlighted in light yellow...Was it too light that hard to notice?

**Comment by niksedk** [comment]
OK, thx - I see it now... a bit hard to notice for my eyes... don't know think this is supported in winforms...
