### ISSUE TITLE
[Feature Suggestion]Double click on the line will "Go to video position and play the line"

### ISSUE THREAD

**Issue by vincentkilua** [SubtitleEdit/subtitleedit#5743]
![image](https://user-images.githubusercontent.com/23117405/151696321-8331cba0-94f7-4444-98dd-6b62ff41f73f.png)
It might be nice to have such option, which is similar to the option in the pic, but only play the line and then pause.

**Comment by niksedk** [comment]
OK, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip ?

**Comment by vincentkilua** [comment]
> OK, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip ?

Exactly what I mean, thanks a lot!
