### ISSUE TITLE
[Feature Suggestion] Show original line from .sup when spellchecking after OCR

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#5744]
Current interface:
![spellcheck a ocr-ed sup](https://user-images.githubusercontent.com/25927091/151710589-93736258-63fa-4580-a663-35d126e75ad4.jpg)

This window isn't very helpful, I have no idea whether it's an ocr error or correct text from original .sup file.
I have to do some dirty work to find the corresponding line in original form to make a decision.

**Update: this spellcheck button** 
![Untitled](https://user-images.githubusercontent.com/25927091/151794473-6c969678-fc69-4cd5-8aa4-85b6ed37dc59.jpg)

**Comment by niksedk** [comment]
You can do spell check when OCR'ing... or export text + image after export via context menu in list view.

To make spell check show the correct image is only possible if time codes are not touched, which can be pretty hard to understand for users.

What is your workflow?

**Comment by niksedk** [comment]
Did a test - should work here, but only right after OCR'ing: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
Thoughts?

**Comment by cyzs233** [comment]
> Did a test - should work here, but only right after OCR'ing: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip Thoughts?

Thanks for the quick update, It works out great.
The idea behind this is the "prompt for unkown word" option in OCR pannel.
![unknown words in subtitleedit](https://user-images.githubusercontent.com/25927091/151915827-35af55be-d612-43d1-bbe2-4403866fc8bd.jpg)

Currently, most of the words it prompts are name/noise,  which is normally OCR-ed correctly. 
But it prompts a lot if this option is checked when OCR'ing, it would be nice to uncheck this and use spellcheck to double-check OCR results in one go.

Any support plan for other image-based subtitles like .sub? ❤

**Comment by niksedk** [comment]
"Prompt for unknown words" should be the same as spell check. Names can be added to the names list.

You can now open a .sup (or bdn xml/png) in spell check with "Ctrl+o" (the shortcut for file open): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by cyzs233** [comment]
> You can now open a .sup (or bdn xml/png) in spell check with "Ctrl+o" (the shortcut for file open): 

Shortcuts are fine, but most users probably won't notice they can do that.
Any chance of adding a button that states "compare to source" or something similar?

**Comment by niksedk** [comment]
Added a context menu - https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by cyzs233** [comment]
Any chance .idx would be supported?🤞
![idx](https://user-images.githubusercontent.com/25927091/163335313-9ee0505f-8cf3-4c34-8d3f-e18178385349.png)
