### ISSUE TITLE
Close subtitle and maintain video

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5748]
Is there a way, a option to close a subtitle file and maintain the video?
Whenever I've tried to close a subtitle, the video goes together.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

If you hold down "shift" when pressing new, the video will now stay open (... and if you open a new sub, then hold down "shift" again to keep the video).

Alternatively, you can just use File - Save as... + delete all

**Comment by Andrebavila** [comment]
> Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
> 
> If you hold down "shift" when pressing new, the video will now stay open (... and if you open a new sub, then hold down "shift" again to keep the video).
> 
> Alternatively, you can just use File - Save as... + delete all

Thank you very much, @niksedk!
It's perfect!
