### ISSUE TITLE
No select audio option in raw .m2ts file with multiple audio tracks

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#5750]
<details>
<summary>MediaInfo:</summary>

General
ID                                       : 0 (0x0)
Complete name                            : G:\Movie\Little.Italy.2018.DUAL.COMPLETE.BLURAY-CLASH\BDMV\STREAM\00004.m2ts
Format                                   : BDAV
Format/Info                              : Blu-ray Video
File size                                : 32.3 GiB
Duration                                 : 1 h 41 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 45.6 Mb/s
Maximum Overall bit rate                 : 48.0 Mb/s

Video
ID                                       : 4113 (0x1011)
Menu ID                                  : 1 (0x1)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : 27
Duration                                 : 1 h 41 min
Bit rate mode                            : Variable
Maximum bit rate                         : 37.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive

Audio #1
ID                                       : 4352 (0x1100)
Menu ID                                  : 1 (0x1)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Muxing mode                              : Stream extension
Codec ID                                 : 134
Duration                                 : 1 h 41 min
Bit rate mode                            : Variable
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless

Audio #2
ID                                       : 4353 (0x1101)
Menu ID                                  : 1 (0x1)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Muxing mode                              : Stream extension
Codec ID                                 : 134
Duration                                 : 1 h 41 min
Bit rate mode                            : Variable
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless

</details>

When dropping a .m2ts file with multiple audio tracks into the video section and click "add waveform", no selection part was prompted,  SubtitleEdit seems auto-selected the first track to generate waveform.
Was expecting something like this:
![choose audio track](https://user-images.githubusercontent.com/25927091/151938160-281e1d48-6a5e-47f1-a512-969e7b1001f0.jpg)

Not sure if the above issue is a bug, but you do can select the second audio track in the toolbar, as long as the first track was analyzed, which can take up to 5 minutes.
![choose audio track](https://user-images.githubusercontent.com/25927091/151938900-349ffec0-4b83-4c0d-a5bd-674444638ad7.jpg)

**Comment by niksedk** [comment]
Could you provide a sample file? (email is fine)

**Comment by niksedk** [comment]
Also, this is probably controlled by the video player that you use inside SE. Do you use mpv or ?

**Comment by cyzs233** [comment]
> Could you provide a sample file? (email is fine)

File uploaded to Google drive cause raw .m2ts are rather large in size.
https://drive.google.com/drive/folders/1khMbuSOjScZWuHpcQLBlNtksQMZAjyMn?usp=sharing
`00004.m2ts is the a smaller file with same problem, first audio German, second English.
Ein Rezept für die Liebe.mkv was remuxed using mkvtoolnix default setting without any metadate edit, original file"00004.m2ts"` 

Yes, I selected MPV as the default video player, but the problem still exist for vlc/direct-show
