### ISSUE TITLE
Minimum Gap Between Shotchanges

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5757]
Here's what happened to me. I finished a job with the instructions that each subtitle should end 1 frame before the shotchange.  Did so and later they decided that it should end 2 frames before the shotchange. I do not know how to auto do this. Is there an option or could there be an option exactly like minimum gap between subtitles option where you can just set the value of the frames to end a subtitle before the shotchange within a given range and/or extend the end time to meet the two-frame requirement within a range?
Say my subtitle ends 5 frames before the shotchange, I can just set value that each subtitle that ends at less than 5 frames before a shotchange should extend and end at 2 frames before the shotchange.
Similarly if my subtitle has a 1 frame gap, it should shrink to 2 frames.

I'm only talking about end times and shotchanges, not start time; which someone would want to have added too.

Thoughts?

**Comment by m0ck69** [comment]
Good idea. I'd like to have such feature as well.

**Comment by LeonCheung** [comment]
Menu > Tools > Adjust Durations... and good luck.

**(You have to do frame-to-second conversion manually for now)**
