### ISSUE TITLE
Error: Attempted to divide by zero.

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#5759]
I'm not sure how to reproduce this, but it happened when I had a video file open and was importing text. I held shift and clicked on okay in the "import plain text" window, in order to have the video stay open, and then got this:
![se-error](https://user-images.githubusercontent.com/19672444/152331099-818d4b90-25b0-4a62-b736-2bae4a934e39.png)

Edit: I managed to find the specific cause, it seems. In the "import plain text" window, if you click on "single line max length" and type in a different number and then press okay, this happens. If you type in a number and then use the little arrows next to it to move it up and then down again, so that the window updates with the correct line lengths, it doesn't happen. But ideally  it should update when you type in the number anyway.

**Comment by niksedk** [comment]
thx :)
Hopefully fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Seems to be! Thank you!
