### ISSUE TITLE
[Feature Suggestion] Better support of external OCR tools on image-based subtitles

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#5761]
Mostly about some stuff when working with ABBYY FineReader PDF 15. 
Suggestions digest:
- option to export pre-processed png files of image-based subtitle
- option to save those png files with time code as their filename
- auto detect&add space to ABBYY Chinese OCR results.

Those features are here to better support OCR a .sup using ABBYY. 
While Tesseract is impressive at English .sup OCR, its language support is limited and the accuracy of Chinese-like language is "Mehhh" at the best. Self-training a dictionary from scratch for nOCR/Binary image compare isn't a wise move, since each Chinese fonts change the character's shape in a minor way. It was acknowledged by Chinese fansubbers using Sup2srt that your dictionary is useless against a even slightly different font. It's better to seek out enterprise solutions.
Given the fact that ABBYY has 99% accuracy on Chinese-like characters, Japanese、Korean, etc. I sincerely hope SubtitleEdit could support ABBYY OCR workflow better.

If you're not familiar using ABBYY to do OCR, I strongly recommend watch through this [Hardsub tutorial](https://www.youtube.com/watch?v=Cd36qODmYF8) on youtube, all above Feature Suggestions are inspired by this video (except we're dealing with .sup OCR).

I'll use English PGS for better demonstration, Chinese PGS can be a little messier. 

### 1. option to export pre-processed png files of image-based subtitle
This is an exported png demo from a .sup. In OCR pannel, right click subs-> Export ->BDN xml/png.
![exported png](https://user-images.githubusercontent.com/25927091/152498952-3a31b99d-ceec-4d1b-8b49-2770b8286b59.jpg)

It's an untouched raw png, but not suited for OCR task. Transparent background、not entirely black&white etc. 
Abbyy doesn't seem to like it at all. Abbyy OCR result of above raw png:
![Abbyy ocr results](https://user-images.githubusercontent.com/25927091/152500179-5952b0dd-ca73-4c8f-8bc8-1a46a1b9e83e.jpg)

Below is a better OCR result using the default pre-processed image:
![pre pocessed in subtitleesit ocr result](https://user-images.githubusercontent.com/25927091/152501252-cd8becdd-31a1-4110-b2ca-a81983a4856c.jpg)

### 2. option to save those png files with time code in their filename
This is inspired by VideoSubFinder, save time code somehow. ABBYY save OCR .txt with the original image filename, you could use those timecode to reconstruct a .srt when using the "import plain text" function.
![import timecode from file](https://user-images.githubusercontent.com/25927091/152504002-5176a8c4-634e-47f9-956e-4f89ec92ad83.jpg)

### 3.auto detect&add "space" to ABBYY Chinese OCR results.
![unnamed](https://user-images.githubusercontent.com/25927091/152507453-154f3f21-ed9d-4717-a398-beed9ee3911e.jpg)
For this I had contacted ABBYY first, you can find the more detailed ticket in their [Official Q&A](https://support.abbyy.com/hc/en-us/community/posts/4416286297107-Missing-space-in-Chinese-OCR-results-).
Reply:
> As for your second screenshot, the space is not detected here. After you crop the image, the ABBYY FineReader PDF 15 program analyzes the text as a picture area. And visually it looks the same (with space between sentences). 
> As a workaround, we may only recommend you to manually put the space after the recognition in the verification window. 

Seems nothing can be improved on ABBYY OCR engine side, and they don't have any plan on fix it.

This is a "Godzilla feature", Chinese fansubbers will die for you, if you can implement a workaround.

Your product is amazing, don't hesitate to ask me of any source file.❤
English&Chinese PGS: https://drive.google.com/drive/folders/1Dw3XEDcX9t52GCr87E9u9CLLHnaPJrrI?usp=sharing

**Comment by niksedk** [comment]
OK, how is this?
![image](https://user-images.githubusercontent.com/1261331/152559921-ae9ae069-689b-4526-8154-16700452b6d1.png)

About word split... could you provide a list with Chinese words?

**Comment by cyzs233** [comment]
> OK, how is this? 
Works for me. 
Is this option output image that can be used in Abbyy? As you can see in the first suggestion, exported png using "BDN xml/png" option can't be directl used for further OCR. I can link you an ABBYY FineReader PDF 15 if you need to do more tests.
[Edit this link out after you get it](https://drive.google.com/file/d/1EVWEJqlBJ3dnp7j4VpiZ3RQ3soFb2m59/view?usp=sharing)

> About word split... could you provide a list with Chinese words?
In informal Chinese subtitles, the space serves a sentence separate purpose. You can replace them with ", or ." without causing any confusion.
Here is an example:
![Image39](https://user-images.githubusercontent.com/25927091/152565624-500aa846-5473-4e96-b7df-d4fb2e2e4004.png)
![Image37](https://user-images.githubusercontent.com/25927091/152565638-0193a3fa-e9be-4194-8546-50f99b731527.png)

**Comment by niksedk** [comment]
The images will have the OCR pre-processing applied.

**Comment by cyzs233** [comment]
@niksedk 
Regarding Chinese words list. What kind of content do you need.
I find 
- a rip of an official Simplified Chinese dictionary (Xinhua Dictionary). https://github.com/pwxcoo/chinese-xinhua
Containing 16142 single word (语 / 范), 264434 double words (版本 / 用途 / 使用者), 31648 idioms (哀鸿满地 / 不知其数). 

- a Chinese word splitter (Simplified  & Traditional Chinese ): https://github.com/kfcd/chaizi
Split single Chinese words into multiple words according to text shape  (拆 -> 扌 斥 / 吧 -> 口 巴).
This might be useful in Binay image compare and nOCR
<details><summary>demo</summary>

![ezgif com-gif-maker (10)](https://user-images.githubusercontent.com/25927091/152587237-277497bd-b04b-409e-aa4b-1507688526dd.gif)
</details>

- a tool that allows you to rip dictionary from an [input method editor](https://en.wikipedia.org/wiki/Input_method) https://github.com/studyzy/imewlconverter
Have more informal phases, like Pepaga in twitch, LOL, TLDR, etc.
