### ISSUE TITLE
[Feature Suggestion] Auto sync subtitle using  ffsubsync

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#5762]
[ffsubsync](https://github.com/smacke/ffsubsync) can auto synchronize subtitles with video using [voice activity detector (VAD)](https://github.com/smacke/ffsubsync#how-it-works). 
It works most of the time like a charm, but the original dev is a linux user and doesn't have plan on implement gui ([issue pending for three years).](https://github.com/smacke/ffsubsync/issues/53), thought integrating it into subtitleedit can benefit both.

Currently, ffsubsync is already integrated in Bazarr, see [How to use as library?](https://github.com/smacke/ffsubsync/issues/135)

Some cool things you can do with ffsubsync:
- auto sync subtitle using audio as reference.
This is might be the handiest tool to do a rough sync automatically. 
Before, I have to spend 30+ minutes manually check & synchronize a single subtitle. Now, since most subtitle entries are correctly aligned to the audio track, All I have to do is spend 1-2 minutes to make sure their duration isn't too short or too long.

-  auto sync subtitle using subtitle as reference.
Most subtitles in foreign languages are translated based on the English version. If you're planning to sync bunch of foreign subtitles to a single video. 
Instead of manually sync dozens of subtitle manually, with ffsubsync, you only have to make sure the English version is synced and use that as reference to sync all other subtitles. [Batch sync multiple subtitles](https://github.com/smacke/ffsubsync/issues/144)

More cool things you can do with SubtitleEdit support:
- [Use embedded PGS subtitles as a reference](https://github.com/smacke/ffsubsync/issues/94)
All ffsubsync need is the timestamps in PGS subtitles, which have better support in SubtitleEdit. 
You may also have more options like .idx from DVD and .dvb from .ts

- More user friendly:
ffsubsync is only intended to be used on CLI, so you have to manually check couple things to make it work.
  - no space in file path.
  - no exotic character in file name. 
     Most foreign language subtitles downloaded from opensubtitle will have foreign symbols in their filename (Un.moment.**d'é**garement.2015). 

   It's kinda annoying to let user handle all those details. As video player like VLC can load them correctly anyway, users don't want to double check filename most of the time.

Thank you for all previous quick patches, I'm out of ideas after this one 💖

related: #4117, #3332, Alass #1697

**Comment by Avamander** [comment]
May I ask why this feature request was closed?
