### ISSUE TITLE
Regex not working for "Replace with" field

### ISSUE THREAD

**Issue by maraqm** [SubtitleEdit/subtitleedit#5771]
Hello,
I'm using the Multiple Replace tool with a regex. I need find "...+space+uppercase" and change it to "...+space+lowercase".
The regex works for the "Find what" field, but it doesn't work for the "Replace with" field. 
I need assistance asap.
Thanks!
![SE_regex replace](https://user-images.githubusercontent.com/99214574/152861555-f64754b4-af58-4360-b021-b1addb033412.jpg)

**Comment by OmrSi** [comment]
Sadly, the `replace with` field can't take regex. It takes limited stuff like `\n`
Also, the isn't any way to replace with another casing in .NET regex.
