### ISSUE TITLE
Generate video with burned-in sub crashed

### ISSUE THREAD

**Issue by brainstorm1313** [SubtitleEdit/subtitleedit#5773]
![image](https://user-images.githubusercontent.com/17483986/153288492-6837d9f9-d389-438f-81cc-ecd23e774885.png)
Error message:
Value of '-29' is not valid for 'emSize'. 'emSize' should be greater than 0 and less than or equal to System.Single.Maxvalue. Parameter name; emSize

**Comment by niksedk** [comment]
Hi @brainstorm1313 - should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
Could you verify?

**Comment by brainstorm1313** [comment]
> Hi @brainstorm1313 - should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip Could you verify?

This beta works fine.
