### ISSUE TITLE
nOCR/binary image compare "No of pixels is space" limit of 50 pixels makes it impossible to detect Chinese characters

### ISSUE THREAD

**Issue by Edgar-Galan** [SubtitleEdit/subtitleedit#5780]
I am extracting subtitles in Chinese from images I generated using a different software. The images are super clear and with high resolution, still Tesseract fails to recognize most Chinese characters. Therefore I am using nOCR or binary image compare trained on a few Chinese fonts and manually building the database adding the correct character to each image.

The process should not take so long and for several characters it works smooth and accurate. However, I quickly found that most characters cannot be recognized since the OCR will try to read only the left component of a character (Chinese characters are often comprised of 2 or more components, e.g. 吗 吃 喝 叹 吧 and so on, will have the same 口 component on the left). This requires to click on expand to select the whole character over and over, so the process can never be automated. 

Then there are some characters such as 儿 and 八, where the space between the components seem to exceed the 50 pixel limit since these are impossible to select as a whole thus they are always treated as separate characters and can never be recognized. 

I thought that fixing this should be as simple as finding the variable determining 50 as the pixel limit and change for a bigger number, but despite hours trying I did not succeed in fixing it myself. I am not a programmer and I have no experience with editing and compiling the program.

I would really appreciate if the limit could be increased or uncapped (to a reasonable limit), right now I am really stuck with this issue and cannot use the program just because of this. Thanks in advance 👍

**Comment by Edgar-Galan** [comment]
Hi Zhang Qiang, thanks for replying

Actually the fact that Chinese do not use spaces works in my favor here since I only need to input a few thousand characters and I would get every word that can be written using those characters. So I can build my database in a couple of days and use it for the rest of my life. I do not need word segregation or definitions or nothing. Just the OCR and then export to srt. 

The issue has nothing to do with "OCR auto correction / spellchecking"  nor Tesseract. I do not intend to use any of those. I am specifically referring to the nOCR and binary image compare tools that have a limit of 50 pixels to consider as space. As a result, spaces are considered between individual characters, and therefore some are impossible to recognize, whenever the space is less than the 50 pixels or there is no space it works great. So, essentially if the limit was 100 or 200 for example, this would solve the issue and it would work nicely for Chinese (or Japanese/Korean). I hope is not too hard to change, I might keep trying to find a way to change it myself but I have minimal programming experience. 

By the way, setting a low pixel is space as in your example will cause the program to insert spaces after every character. I do the opposite, setting it as high as possible and it can recognize the text without inserting spaces.

Here is an example, the program can recognize all the characters in the sentence, except for 你 only because there is a space bigger than 50 pixel between 亻and 尔.

![example1](https://user-images.githubusercontent.com/73632883/153747367-31760450-9fc7-481d-9f9f-8b04a4dd21c8.png)
![example2](https://user-images.githubusercontent.com/73632883/153747389-15c06971-c8f6-4fb9-b3ae-9260d3379014.png)

**Comment by cyzs233** [comment]
I'm not familiar of how "Binarry image compare and NOCR" OCR works in SubtitleEdit, better let others step in.

But in my experience OCR Chinese, those two options in subtitleedit is still not recommended, they can't handle the minor difference in fonts. If you really want to build your own database, you might have a better experience using IdxSubOcr + Office2003 MODI. 

> By the way, setting a low pixel is space as in your example will cause the program to insert spaces after every character. I do the opposite, setting it as high as possible and it can recognize the text without inserting spaces.

If you are a casual Chinese OCR-er, Tessaract might suit your needs better, they perform pretty impressively on basic Chinese. Just remember to disable any auto-correct option like the image from previous reply, and replace extra space with "Edit/Replace"
