### ISSUE TITLE
Subtitle Edit 3.6.4 crashing when opening a video

### ISSUE THREAD

**Issue by zuzanagombikova** [SubtitleEdit/subtitleedit#5786]
Hi all,

I worked with SE few weeks ago, no issues. Now it crashes when I try to open a video.

Fixes I tried so far:
1. reinstall SE
2. installed older versions of SE (down to 3.5.19)
3. uninstalled the latest Windows updates (as advised on other thread here)
4. Installed VLC 64bit on my Win 64bit to be able to choose it as Video player instead of MPV
5. Tried to load other video format, tried to load old videos I worked on few weeks ago

There was no difference in SE behaviour, it just crashes every single time.

I have SE 3.6.4, WIN 10 64bit, videos are mp4

Can anyone advise what to do?
Thank you all in advance

**Comment by niksedk** [comment]
So SE crashes with both mpv and vlc? (mpv is preferred)
What is the crash message? Did you check the application event logs in the event viewer?

You could try to re-install the dotnet 4.8 runtime: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48
You could also try to update your graphics card drivers.

**Comment by uzanokuhle** [comment]
Hello. I have a similar issue, but while running SE on Parallels (M1 Macbook Air, Windows for ARM). Subtitle Edit crashes when loading video.

How to recreate the issue:
1. Open SE (on Windows ARM via Parallels).
2. Load video
3. App crashes/closes.

I initially thought it was HEVC codecs needing to be installed, but I installed those and the video plays fine on Windows' native video player. The problem doesn't happen on Intel-based Macs (Windows x64 on VMWare).

@niksedk - I would like to understand what you mean by mpv & vlc so I can try that solution please (is there a way to run VLC in SE?).

Thanks in advanced.

**Comment by niksedk** [comment]
@uzanokuhle: In Options - Settings -Video player, you can choose different video player engines - and mpv is the preferred one.

**Comment by uzanokuhle** [comment]
Thanks so much, it worked.
