### ISSUE TITLE
Turn auto break completely off

### ISSUE THREAD

**Issue by pboettcher** [SubtitleEdit/subtitleedit#5788]
I didn't find an option to turn the auto break feature completely off. Sorry, but it never breaks as I want and causes addidional work.

I would like that on merge there is a result line without additional breaks added and there is no break between parts. Breaks that were there should be kept. That on split no additional breaks are added. That breaks which were already there won't be removed.

How to achieve this?

**Comment by OmrSi** [comment]
There are multiple shortcuts for Merge, some of them merge and break and some merge and unbreak, and some merge and don't break.
