### ISSUE TITLE
How to merge empty lines with the previous line in batches, and modify the end time to the end time of the empty line?

### ISSUE THREAD

**Issue by dealday2013** [SubtitleEdit/subtitleedit#5790]
This is my result after using "Line merge: Merge max two lines"
![Screenshot_2](https://user-images.githubusercontent.com/100005834/154781178-c1c095e7-4bcc-4da0-be4a-85b292b1577a.png)

So, how to merge empty lines with the previous line in batches, and modify the end time to the end time of the empty line?
For example, number 3 is merged with number 4, and the end time is changed to 00:00:12.823
That is, number 3 needs Start time:00:00:08.510 and End time:00:00:12.823

Because I used "Remove empty lines/unused line breaks" of "Fix common errors", although the empty lines can be removed, the ending time has not been changed, which makes it hard to watch the translated subtitles on the video.

I know that "Merge with next" of "Shortcuts" can be solved, but I have more than 9000 lines and I am very tired, so is there a batch method, if not, can this function be added? Thank you

**Comment by dealday2013** [comment]
No one solved it. So I solved this problem myself with PYTHON.

**Comment by ahmad1920** [comment]
Please share the Python file
Because I also have this problem and I want a solution to this problem, thank you

**Comment by ftfox** [comment]
@dealday2013 你好，我也遇到了这个问题。使用合并翻译后生成了大量的空白行。
所以希望能一键让所有的中文空白行和上一行合并，请问下你是怎么批处理的？
