### ISSUE TITLE
Merge line

### ISSUE THREAD

**Issue by skyunix** [SubtitleEdit/subtitleedit#5791]
`1
00:00:02,375 --> 00:00:04,809
（same time and tetx1）`
`2
00:00:02,375 --> 00:00:04,809
（same time and tetx1）`
`3
00:00:04,833 --> 00:00:07,291
（same time and tetx2）`
`4
00:00:04,833 --> 00:00:07,291
（same time and tetx2）`
`5
00:00:16,875 --> 00:00:21,041
（same tetx2）`

when use"Merge line with same time codes" the result is

`1
00:00:02,375 --> 00:00:04,809
（same tetx1）（same  tetx1）`
`2
00:00:04,833 --> 00:00:07,291
（same  tetx2）（same tetx2）`
`3
00:00:16,875 --> 00:00:21,041
（same tetx2）`

so can we merge the "same time and text" whith the first line text like this?

`1
00:00:02,375 --> 00:00:04,809
（same tetx1）`
`2
00:00:04,833 --> 00:00:07,291
（same  tetx2）`
`3
00:00:16,875 --> 00:00:21,041
（same tetx2）`

**Comment by cyzs233** [comment]
"Merge line with same text" seems to solve your problem in this case.

**Comment by Marvll** [comment]
> "Merge line with same text" seems to solve your problem in this case.

Merge line with same text will merge different time codes line（adjacent）

00:00:02,375 --> 00:00:04,809
A: ok

00:00:04,833 --> 00:00:07,291
B: ok

then merge into 
00:00:02,375 --> 00:00:04,809
A: ok

lost B

**Comment by cyzs233** [comment]
Then, requesting a "delete duplicate line" option in "fix common errors" might be what you're looking for.

But this option potentially will do you more harm than good (delete normal repeated dialog). 
It's better manually delete unwanted lines by yourself. 

May I ask how do you end up in a situation like this, it's kinda rare to me

**Comment by Marvll** [comment]
> Then, requesting a "delete duplicate line" option in "fix common errors" might be what you're looking for.
> 
> But this option potentially will do you more harm than good (delete normally repeated dialog). It's better manually delete unwanted lines by yourself.
> 
> May I ask how do you wind up in a situation like this, it's kinda rare to me

m3u8 subtitle 
when i use /b merge the file to vtt it's duplicate (randomly)

**Comment by Marvll** [comment]
> Then, requesting a "delete duplicate line" option in "fix common errors" might be what you're looking for.
> 
> But this option potentially will do you more harm than good (delete normally repeated dialog). It's better manually delete unwanted lines by yourself.
> 
> May I ask how do you wind up in a situation like this, it's kinda rare to me

m3u8 subtitle 
when i use /b merge the file to vtt it's duplicate (randomly)
