### ISSUE TITLE
UI Update

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5794]
Not a big deal. Here is what it looks like:

https://user-images.githubusercontent.com/494788/155056224-60fac79b-10ab-40e9-b5d9-924c320a208e.mp4

**Comment by niksedk** [comment]
I'm not able to re-create this... any hints?

**Comment by LeonCheung** [comment]
Ah, then try my settings:
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/8154322/Settings.zip)

**Comment by niksedk** [comment]
Cool, the settings file helped :)
Should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Thx, now with build 513, I got this when trying to resize:

![image](https://user-images.githubusercontent.com/494788/156107860-60ef8f37-0134-4c0a-a0cb-6cefc982a16b.png)

**Comment by niksedk** [comment]
thx :)
Should be fixed: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Indeed, thx! Closing.
