### ISSUE TITLE
Timecode issue

### ISSUE THREAD

**Issue by ningsibuqu** [SubtitleEdit/subtitleedit#5799]
```
00:00:24:04	00:00:29:00
00:00:29:00	00:00:33:15
00:00:33:20	00:00:38:02
00:00:38:10	00:00:41:12
00:00:42:02	00:00:45:19
```
to srt

```
1
00:00:24,167 --> 00:00:29,000
2
00:00:29,000 --> 00:00:33,626
3
00:00:33,834 --> 00:00:38,083
4
00:00:38,417 --> 00:00:41,500
5
00:00:42,083 --> 00:00:45,792
```

Requires adaptation xx:xx:xx:xx Timecode
[1.txt](https://github.com/SubtitleEdit/subtitleedit/files/8147196/1.txt)

**Comment by LeonCheung** [comment]
It's already supported, try dragging it into SE to open it.

**Comment by LeonCheung** [comment]
Not sure, then try this latest beta:

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by ningsibuqu** [comment]
> Not sure, for your uploaded file, it works for me. Then try this latest beta:
> 
> https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

same, no works.

You can download and try it yourself.

**Comment by ningsibuqu** [comment]
```
00:00:24:04	00:00:29:00
00:00:29:00	00:00:33:15
00:00:33:20	00:00:38:02
00:00:38:10	00:00:41:12
00:00:42:02	00:00:45:19
```
It should be
```
1
00:00:24,040 --> 00:00:29,000
2
00:00:29,000 --> 00:00:33,150
3
00:00:33,200 --> 00:00:38,020
4
00:00:38,100 --> 00:00:41,120
5
00:00:42,020 --> 00:00:45,190
```1
00:00:24,040 --> 00:00:29,000
2
00:00:29,000 --> 00:00:33,150
3
00:00:33,200 --> 00:00:38,020
4
00:00:38,100 --> 00:00:41,120
5
00:00:42,020 --> 00:00:45,190
