### ISSUE TITLE
Error when using 'fix common errors'

### ISSUE THREAD

**Issue by BlueChip369** [SubtitleEdit/subtitleedit#5801]
![1oA52VRBcW](https://user-images.githubusercontent.com/100507020/155871881-1c77068c-eed0-44dc-aae7-9e57f3536385.png)

**Comment by niksedk** [comment]
It sounds like the file `C:\Users\<something>\AppData\Roaming\SubtitleEdit\Dicionaries\nl_names_user.xml` is broken...
Try to fix it in notepad (make it a valid xml file) - or just delete it.
