### ISSUE TITLE
Failed to parse VTT properly

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5810]
Test file:
[example.zip](https://github.com/SubtitleEdit/subtitleedit/files/8169531/example.zip)

**Comment by niksedk** [comment]
This works fine for me...

**Comment by LeonCheung** [comment]
Hmm, strange. I only got the first line parsed.... I think I figured out why. I make another VTT format in the favorates list, so it would use the one instead of the other one:

![image](https://user-images.githubusercontent.com/494788/156925674-e0eaee59-5a1d-4c67-a803-d782e9dd3a5b.png)
