### ISSUE TITLE
subs only start time no have End time, How to import?

### ISSUE THREAD

**Issue by ningsibuqu** [SubtitleEdit/subtitleedit#5811]
can have a duration until the next subtitle start time?
[1.txt](https://github.com/SubtitleEdit/subtitleedit/files/8176257/1.txt)

**Comment by ningsibuqu** [comment]
@LeonCheung

**Comment by cyzs233** [comment]
Your timecode is invalid, you can either drop the millisecond part or append "0" to each timecode.
![Untitled](https://user-images.githubusercontent.com/25927091/156591450-3aed2767-8dc0-48c6-afd2-5715aceac21a.jpg)

To "have a duration until the next subtitle start time", seems the inner detail is quite interesting.
The format of fake text will result in different behavior in SubtitleEdit. 
Not exactly sure what the conditions need to be met for your task, but here is a working example for your experiment.
[Millennial Bee.txt](https://github.com/SubtitleEdit/subtitleedit/files/8178825/Millennial.Bee.txt)

**Comment by darnn** [comment]
They're not milliseconds, they're frames (see "time code mode" in settings).

**Comment by LeonCheung** [comment]
@ningsibuqu Okay, for the specific case you mentioned, here's my quick and dirty trick:

https://user-images.githubusercontent.com/494788/156728812-69f36265-1031-4be1-9ea9-47eab86661e4.mp4

NOTE:

1. You have to manually handle the end time for the last line, as shown in the video.
2. You can use the shortcut **Ctrl Shift Alt F** to switch between frame# and ms# display mode. (I don't think this shortcut is officially documented XD)

**Comment by darnn** [comment]
Oh wow, thanks for that video. I used to do this in a text editor with regular expressions, this is certainly easier (and I can even do it in the text editor as well).
