### ISSUE TITLE
[Feature Suggestion] Waveform panel new right-click option "copy current time"

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#5815]
Useful when dealing with overlapping dialogues, 
Timecode will get pasted into source view directly, "move start backward" shortcuts don't seem to be able to generate overlapping dialogues.

**Comment by LeonCheung** [comment]
Switch to ASSA format, then select line(s) in list view, and try Ctrl C/ Ctrl V. Are you expecting things like that?

![image](https://user-images.githubusercontent.com/494788/157359576-ef4af33e-69c7-461c-9b00-1e5ab782a339.png)

**Comment by cyzs233** [comment]
> Switch to ASSA format, then select line(s) in list view, and try Ctrl C/ Ctrl V. Are you expecting things like that?

No, apparently you can't adjust overlapping line's timecode separately in waveform.

I do find out that there is an indicator on the bottom left. But still, why this isn't an option, that's where most people are expected it to be.
![Untitled](https://user-images.githubusercontent.com/25927091/157517413-21265b53-1adf-4b36-9986-23f35cb976c4.jpg)

**Comment by LeonCheung** [comment]
Okay, then try Shift + drag in waveform, or enable this:

![image](https://user-images.githubusercontent.com/494788/157519371-3cdd83d4-45c3-427e-acd7-92d178e41886.png)
