### ISSUE TITLE
Move Text From Cursor To Next and Go To Next

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5823]
When I do this, and then hit play/pause key, video goes at the end.

![Animation](https://user-images.githubusercontent.com/28671050/157302702-cad36c0d-d3d6-4493-a1d6-f497ebca2aab.gif)

Maybe if go to next was removed, then it would behave differently.

**Comment by LeonCheung** [comment]
When the Start/End time both show up like “-”, it means they are currently at `99:59:59,999`.

**Comment by uckthis** [comment]
I don't know of many situations where this shortcut would be handy. Probably a new shortcut without the Go to next part.

**Comment by LeonCheung** [comment]
It's mainly used for quickly arranging/distributing plain texts to an empty project which only got timecodes. Unlike the "Import Plain Text" tool, this shortcut leaves you great flexibility to do manual splits for a very long sentence, paragraph, or even an article.

**Comment by cyzs233** [comment]
dupe: #5180
