### ISSUE TITLE
[Feature Suggestion] Word list for auto break/split

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#5825]
Apart from basic punctuation, it's also ideal to take couple words into consideration while splitting long sentences.

- conjunctions (for, and, or, etc)
    <details><summary>Demo</summary>

    <p>

    ![GIF 10-03-2022 08-21-45](https://user-images.githubusercontent.com/25927091/157562153-0541763a-bc2c-432a-8af0-78dbc7a413b5.gif)

    </p>
    </details>

- prepositions (where, which, when,etc)
    <details><summary>Demo</summary>

    <p>

    ![GIF 10-03-2022 08-26-44](https://user-images.githubusercontent.com/25927091/157562640-c8938ab8-18fc-485b-976f-2d4e863b5b0f.gif)

    </p>
    </details>

There aren't many prepositions/conjunctions , so the list should be fairly short, hopefully won't cause any noticeable performance drawback.

Having a word list around, users can also tweak it to fits their own needs. #4711

**Comment by LeonCheung** [comment]
Does this help?

![image](https://user-images.githubusercontent.com/494788/157581611-33091f68-8187-4406-a763-ba373c0e2219.png)

Or use Text instead of Regex to add them one by one. Your call.

**Comment by cyzs233** [comment]
@LeonCheung it's more like a "break before" list,  recommend to break before those words for better subtitle readability.

**Comment by niksedk** [comment]
I think "break before" / "do not break after" is the same...
