### ISSUE TITLE
mkv audio delay not reflected in the waveform

### ISSUE THREAD

**Issue by signedout** [SubtitleEdit/subtitleedit#5834]
I have an mkv whose audio track looks like this in mediainfo:

Audio #1
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 19 min
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
**Delay relative to video                  : 3 s 875 ms**
Stream size                              : 109 MiB (3%)
Language                                 : Spanish
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Notice the delay. When I open the file in Subtitle Edit (using libmpv 1.108, Subtitle Edit 3.6.4) and load the waveform, the delay is not taken into account: the waveform is 3s875ms off from what I actually hear when pressing "play".

**Comment by cyzs233** [comment]
@niksedk I too think this audio delay should be correctly addressed.

Here is a sample file on my hand with 10s delay. 
`Delay relative to video : 10 s 0 ms`
Gdrive link(176MB): https://drive.google.com/file/d/1YiPq7XkvDAi709lC9ojOVAcDLDhDyBRd/view?usp=sharing
[in sync subtitle.zip](https://github.com/SubtitleEdit/subtitleedit/files/8790942/in.sync.subtitle.zip)

<details><summary>Full MediaInfo</summary>

<p>

General
Unique ID                                : 98625953607679922073093920732522628308 (0x4A32AAF0A8EB2AEADBEB0F8981D244D4)
Complete name                            : G:\Movie\10s delay on audio.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 176 MiB
Duration                                 : 1 h 36 min
Overall bit rate                         : 254 kb/s
Encoded date                             : UTC 2022-05-28 10:01:09
Writing application                      : mkvmerge v56.1.0 ('My Friend') 64-bit
Writing library                          : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L1.3
Format settings                          : 1 Ref Frames
Format settings, CABAC                   : No
Format settings, Reference frames        : 1 frame
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1 h 36 min
Bit rate                                 : 125 kb/s
Width                                    : 320 pixels
Height                                   : 238 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.068
Stream size                              : 86.3 MiB (49%)
Writing library                          : x264 core 163 r3059+11 1aa8b82 [Mod by Patman]
Encoding settings                        : cabac=0 / ref=1 / deblock=0:0:0 / analyse=0:0 / me=dia / subme=0 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=0 / keyint=250 / keyint_min=24 / scenecut=0 / intra_refresh=0 / rc=crf / mbtree=0 / crf=30.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=0
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 36 min
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 28.711 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 10 s 0 ms
Stream size                              : 88.4 MiB (50%)
Language                                 : Hungarian
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No


</p>
</details>
<details><summary>How it looks like in gMKVExtractGUI</summary>

<p>

![Untitled](https://user-images.githubusercontent.com/25927091/170820946-8efd2370-fac4-4d83-a2ac-103f210872f1.png)

</p>
</details>

When you play this film on a normal video player like VLC/MPV , the audio delay is honored and the subtitle is in sync with the audio.
But when opening this film in SubtitleEdit, in the waveform panel, you can clearly see that the audio has been mistakenly aligned to the start of the video track, which means the audio delay info is not respected by SubtitleEdit.

<details><summary>Demo</summary>

<p>

![Untitled](https://user-images.githubusercontent.com/25927091/170821282-b8a311bf-2c4a-4c9a-a75b-2c5b338e2d9e.png)


</p>
</details>
In such case, you can't really edit subtitles in SubtitleEdit, as the timeline will be a total mess even your subtitle is in sync with the film. 
<details><summary>Demo</summary>

<p>


![Untitled](https://user-images.githubusercontent.com/25927091/170821427-764d8ef7-f1fa-4303-b54d-c5560ae2e29e.png)


</p>
</details>

At last, here is a nice explanation on [why there is audio delay when mux a . ts into .mkv](https://forum.videohelp.com/threads/367447-How-to-Prevent-MKVMerge-adding-a-delay#post2348447))

❤

**Comment by niksedk** [comment]
@cyzs233: Thx for the sample files :)

I've tried to fix the issue here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

SE only looked in the first cluster (mkv building blocks).
Now SE looks in the first 100 clusters (will probably not work if the delay is 10+ minutes).
