### ISSUE TITLE
can you help add an option for auto translatoin via deepl? steve8000818@gmail.com

### ISSUE THREAD

**Issue by nissansz** [SubtitleEdit/subtitleedit#5843]
can you help add an option for auto translatoin via deepl? steve8000818@gmail.com

https://www.deepl.com/en/translator

**Comment by niksedk** [comment]
Check File - Plugins:

![image](https://user-images.githubusercontent.com/1261331/159151450-aa72eba0-09fb-45b3-866c-5249c87748cf.png)

**Comment by nissansz** [comment]
Is there any method no need to use API like google translate in your program?
By the way, how did you use google translate to translate subtitle, the result seems different from the google website translate result.

**Comment by niksedk** [comment]
Could you explain a little more?

SE just calls google translate...

**Comment by nissansz** [comment]
check example below
![image](https://user-images.githubusercontent.com/41010669/159152166-6ec3ad7f-e213-4794-94d4-6d6fdf9480e9.png)
