### ISSUE TITLE
Cannot add names... Casing Change

### ISSUE THREAD

**Issue by Charvelx04** [SubtitleEdit/subtitleedit#5844]
Just noticed this.. but in 3.6.4, I was not able to add any new names when within the Change Casing window.

I tried this with and without using the online names list... not that I'd know if the two are tied together; I don't.

Updated to 3.6.5.. still same issue.

Did you turn this feature off, or do we have a regression?

If you need any info, let me know.

Thank you.

**Comment by RocketFriday** [comment]
The latest version is now 4.0.1, is this still an issue?

**Comment by Charvelx04** [comment]
I haven't ran into having to edit subs that start off all caps... typically those are directly from CC not PGS.. yeah?

As of seeing this, I brought an old sub and clicked on Change Casing.

No... I was not able to add anything to the list the way we used to do prior to version 3.6.4.

I loved having that section where we could add names or replacements (it was in Settings) but that was removed some time back as well. You could add, say ... "fbi" and make it...  "FBI". I did this for a long list of triple letter names that would otherwise remain lowercase, when they should be upper. But... alas...

Thanks for checking back on this, I had forgotten I posted it.

**Comment by RocketFriday** [comment]
Well you could still do that using the replace multiple feature, I know it's not the same but it's really only one extra step.
Change Casing > Then > Custom Multiple Replace.
![casing](https://github.com/SubtitleEdit/subtitleedit/assets/24511919/bd712d7a-cfd1-4edf-9c3e-904bd007b005)

I think it might be a good idea to close this issue, but I'll leave it up you. 

Good luck.

**Comment by Charvelx04** [comment]
Yeah... we can close this.
