### ISSUE TITLE
Suggestion: Quick Profile Change

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5846]
I think a drop down menu next to framerate would be helpful in quickly changing the profile.
![InkedUntitled_LI](https://user-images.githubusercontent.com/28671050/159283772-ec982d1e-3b7c-4761-b46e-0a11b11ff1a7.jpg)

**Comment by matmaggi** [comment]
Currently, you can click in the bottom right too, next to the number of lines.
