### ISSUE TITLE
About burn-in settings

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5853]
It seems the two nvenc encodings don't work with the following Preset: ultrafast, superfast, veryfast, faster, slower, veryslow. 

![image](https://user-images.githubusercontent.com/494788/159721369-de314086-bba2-4c99-a084-0a0b47d4c519.png)

**Comment by niksedk** [comment]
OK, is this better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Cool, thx!

**Comment by LeonCheung** [comment]
It seems tuning info options are not compatible as well... [REF](https://gist.github.com/nico-lab/c2d192cbb793dfd241c1eafeb52a21c3).

**Comment by niksedk** [comment]
OK, how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Cool again. TBH I never used them but thought it may confuse people,  XD  so... Closing.
