### ISSUE TITLE
What kind of Subtitle is this?

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#5855]
Hi!

Can one use SE to Analyze a txt-file ( bla.txt ) to tell what kind of a Subtitle the txt-file is?

When I open it with SE I get an Error msg

![ErrorFromSE](https://user-images.githubusercontent.com/70509424/159908354-6cd924f6-1eaf-416b-b17f-c0579af92a57.jpg)

=======

The Sub contains:

=========

STYLE
::cue {
color: #DFDFDF;
}
::cue(.huvudpratare) {
color: #00FFFF;
}
::cue(.ljud) {
color: #FF00FF;
}
::cue(.ljudskylt) {
color: #FF00FF;
}
::cue(.relivemark) {
color: #FF0000;
}
::cue(.sang) {
color: #00FF00;
}

ac7ff7a0ad304689abbc836bf0248323
1
00:00:06,360 --> 00:00:10,080
1845 gav sig
en brittisk expedition ut–

901ad1de734b4b048110baa4068b2bf1
2
00:00:10,240 --> 00:00:15,040
–för att söka ett av forsknings-
resornas mest eftertraktade mål:

1b8b567723844b84910d7c6a149c9718
3
00:00:15,200 --> 00:00:18,120
Den gäckande Nordvästpassagen.

efa2d811e1814b4db20ca7d07c4792b0

=========

So what kind of a Sub is that?

**Comment by darnn** [comment]
I have no idea what those hash things ("ac7ff7a0ad304689abbc836bf0248323") are, but overall it's a WebVTT file, so if you change the extension to vtt (i.e. filename.vtt instead of filename.txt), SE will be able to open it.

**Comment by Minherre** [comment]
Ok, thanx, I changed to bla.vtt but no change when I opened it in SE, still the same same Error-msg as I showed in my first msg.

So SE doesn't think it's a VTT Sub.

**Comment by darnn** [comment]
Weird. I just copied what was in your file and saved it as a VTT file and it does open:
[text.zip](https://github.com/SubtitleEdit/subtitleedit/files/8341600/text.zip)

**Comment by Minherre** [comment]
Yes, it opens, but with that Error-msg.
And then you'll get those '1b8b567723844b84910d7c6a149c9718' at the end of each line.

[FaultyVTT.zip](https://github.com/SubtitleEdit/subtitleedit/files/8342099/FaultyVTT.zip)

Here's the entire Sub.

**Comment by darnn** [comment]
Took me a second, but here you go (rename back to .vtt):
[text3.vtt.txt](https://github.com/MiniGlome/Archive.org-Downloader/files/8343006/text3.vtt.txt)

SE gets confused by the timecodes containing commas, e.g.
00:00:06,360 --> 00:00:10,080
so I changed them all into periods:
00:00:06.360 --> 00:00:10.080

And got rid of the hash things, which I assume you don't need. But if this is some legitimate variation of WebVTT, SE should probably be able to read it on its own.

**Comment by Minherre** [comment]
Ok, thanx, that worked to save as .SRT file in SE.

=============

Just came to my mind that this had been up earlier, but then the other way around.

Found the ReadMe-file for the .EXE that someone made back in 2012.

=============

/**************************************************
 Replaces the dot (.) in a wsrt-file to a comma (,)
 for example
 00:00:53.200 --> 00:01:00.840
 becomes
 00:00:53,200 --> 00:01:00,840
 ***************************************************/

/*****************************************
 Input file: "in.txt"
 Output file: "out.txt"
 Execute/launch program: "wsrt_to_srt.exe"
 *****************************************/

=============

Some site back then apperantly used WSRT-Subs.

**Comment by darnn** [comment]
Apparently! I assume yours was generated more recently, though, because it has those hash things, which I've only seen in automatically-generated VTT files in recent years, e.g.:
---
WEBVTT

NOTE duration:"00:19:48.9150000"

NOTE language:en-us

NOTE Confidence: 0.847760260105133

79f07a0d-2714-48a0-b7b1-db0ddc3cf14b
00:00:08.420 --> 00:00:12.754
Lorem ipsum dolor sit amet,

NOTE Confidence: 0.847760260105133

79f92db3-7358-4f86-b0b6-e1e02b4b7895
00:00:12.754 --> 00:00:14.330
consectetur adipiscing elit.

NOTE Confidence: 0.896831274032593

565480d4-2aff-4b68-8de1-c550b773bd38
00:00:14.930 --> 00:00:16.976
Vivamus metus felis,


---
And since they were part of the NOTE block there, SE did parse this file correctly.

**Comment by Minherre** [comment]
> And since they were part of the NOTE block there, SE did parse this file correctly.

I got another new Sub with the same problem this morning, and SE gives the same Error as in my very first msg in this thread, so if you feel like it you can fix, or tell me How to fix, the Sub I attach in this msg now.

[SomeKindOfVTT,Perhaps.vtt.txt](https://github.com/SubtitleEdit/subtitleedit/files/8363963/SomeKindOfVTT.Perhaps.vtt.txt)

Did you Fix the last one by some BAT-file perhaps ?!

**Comment by darnn** [comment]
[SomeKindOfVTT.Perhaps3.vtt.txt.zip](https://github.com/SubtitleEdit/subtitleedit/files/8364219/SomeKindOfVTT.Perhaps3.vtt.txt.zip)


I fixed it using regular expressions in EditPad, which has a syntax that I think might be specific to it, but in case it isn't, the two things I did were:
Replace
(\d\d),(\d\d\d)
with
\1.\2
and then replace
\r\n\r\n.+\r\n(\d)
with
\r\n\r\n\1

And, of course, adding WEBVTT in the first line.

**Comment by Minherre** [comment]
> I fixed it using regular expressions in EditPad, which has a syntax that I think might be specific to it, but in case it isn't, the two things I did were: Replace (\d\d),(\d\d\d) with \1.\2 and then replace \r\n\r\n.+\r\n(\d) with \r\n\r\n\1
> 
> And, of course, adding WEBVTT in the first line.

Thanx a lot, I'll try that later, it should probably work with SE's Multiple Replace too.
