### ISSUE TITLE
[Linux] [Feature request] Make menu texts more adaptable.

### ISSUE THREAD

**Issue by heit0r** [SubtitleEdit/subtitleedit#5856]
Hello SE team,

I'm using Manjaro Linux. The text in the dropdown menu doesn't load correctly as show below in light and dark themes:

![o2CDmtj](https://user-images.githubusercontent.com/38054654/160023288-ed6ea64a-563f-4efe-962a-82659c7f7b10.png)

![acCHYXZ](https://user-images.githubusercontent.com/38054654/160023347-14bc0cc6-cad8-44ce-afc4-cd802ce97dcc.png)

**Comment by ManuLinares** [comment]
Ok then.
