### ISSUE TITLE
Windows installer SubtitleEdit-3.6.5-Setup.exe flagged as malicious by virustotal after unzip

### ISSUE THREAD

**Issue by DocShaker** [SubtitleEdit/subtitleedit#5859]
Hi there, just wanted to check something that I found odd. After unzipping the Windows installer, SubtitleEdit-3.6.5-Setup.exe was flagged as malicious by virustotal and malshare.

It was downloaded directly from git at: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEdit-3.6.5-Setup.zip

virustotal report: https://www.virustotal.com/gui/file/cc3f829f9b3742811e1f0ca35694f0624923b37f280e5b335234b7e20f3d8aec/detection

malshare report: https://malshare.com/sample.php?action=detail&hash=55bc1310a401a40fac6b9eafc4a38b32

My  OS: Windows 10 version 21H2

I appreciate any help you can provide clearing this up. 

Thank you

**Comment by niksedk** [comment]
As always... please report false positive to anti-virus providers, thx.
