### ISSUE TITLE
Using "{" and/or "}" for custom format export

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5860]
It seems we cannot export paragraphs with "{" and "}" defined, but it's really necessary to have. Any workaround pls?

![image](https://user-images.githubusercontent.com/494788/160146998-0cae0168-caec-4ba8-8481-021800bfa37e.png)

**Comment by niksedk** [comment]
Should hopefully be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip
