### ISSUE TITLE
The actual sound comes out slower than the waveform graph.

### ISSUE THREAD

**Issue by crucifyer** [SubtitleEdit/subtitleedit#5865]
The actual sound comes out slower than the waveform graph.
How do I fit it?
thank you.

**Comment by crucifyer** [comment]
If you tell me the option to extract wav with ffmpeg, I will try another way.

**Comment by cyzs233** [comment]
related ? #5834

**Comment by crucifyer** [comment]
I think it's about 0.3~0.5 seconds slower.

**Comment by crucifyer** [comment]
The size is too large and there is no way to send it.
When I test it again, it seems that the waveform is getting faster.
The waveform is fast about 0.5 seconds at about 5 minutes and 2 seconds at about 19 minutes.
After that, it's so fast I can't even compare.

Comparing the normal and faster ones, the fps seems to be the cause.
The normal video is 29.970 fps, and the wrong video is 59.847 fps.

**Comment by Nic0d3mu5** [comment]
Hello, I think I have the same problem : my waveform is a lot faster than the actual sound, and so for a 2h45 film, the waveform ends after 20 minutes : /

**Comment by cyzs233** [comment]
@niksedk 
Here is a sample where the actual sound comes out **faster** than the waveform graph.🤷‍♂️
film: https://www9.zippyshare.com/v/U3CrBaSb/file.html
subtitle: https://www49.zippyshare.com/v/kLeGM5oc/file.html
![Untitled](https://user-images.githubusercontent.com/25927091/185259297-6007e8b7-1fb1-4670-9e7a-aa7743c808a7.png)

It has a similar progressively out-of-sync problem as described by crucifyer, except it is in the reverse direction. The timestamps of this subtitle are correct (you can check it in any video player), so as shown in the above picture the waveform graph is lagging behind for some unknown reason.

Just downloaded the previous release, this problem persists.

**Comment by niksedk** [comment]
>Here is a sample...

Could you use another provider? Zippyshare does not work in the EU.

**Comment by darnn** [comment]
https://wetransfer.com/downloads/89d73f71994428187333e7522ff6649a20220818070900/94375ccb923813f121b90648fd9ec22c20220818070912/95bd2d

**Comment by darnn** [comment]
[Un siecle decrivains,Maurice Blanchot (Hugo Santiago, 1998)_final.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/9371372/Un.siecle.decrivains.Maurice.Blanchot.Hugo.Santiago.1998._final.srt.txt)
