### ISSUE TITLE
Subtitle lines are missing in BD SUP editor

### ISSUE THREAD

**Issue by manuelrn** [SubtitleEdit/subtitleedit#5869]
Hello,

On several occasions I have come across some subtitles that when passing them through Subtitle Edit some lines are lost.

Now I have found again a subtitle in which this problem occurs, but this time the problem is much more serious as there are a large number of lines that are lost. So this time I have decided to open an Issue.
<br />
I noticed that in this subtitle there are some subtitle lines that appear/disappear gradually, that is, they fade away little by little.
And in these cases Subtitle Edit does not maintain the fading and removes many of those lines.

I don't know if these fades are the only problem that is causing the line loss, or if there are other causes as well.
<br />
For OCR it may not matter (although I'm not sure), but for the editor I consider it very important as the resulting PGS looks very bad. So I think that at least the editor should respect and maintain the complete structure of the original PGS.

As note: In this subtitle the latest version of Subtitle Edit (v3.6.5) detects 2885 lines, however BDSup2Sub++ detects 3558 lines (although there may be even more lines, as this program gives multiple errors).

Thanks and regards!
<br />
PS: I attach the subtitle in a zip divided in 8 parts since GitHub only supports files of 10MB maximum.
I have also renamed the files by adding ".txt" at the end, you need to delete the ".txt" before extracting.

[sample_missing_lines.zip.001.txt](https://github.com/SubtitleEdit/subtitleedit/files/8358929/sample_missing_lines.zip.001.txt)
[sample_missing_lines.zip.002.txt](https://github.com/SubtitleEdit/subtitleedit/files/8358931/sample_missing_lines.zip.002.txt)
[sample_missing_lines.zip.003.txt](https://github.com/SubtitleEdit/subtitleedit/files/8358932/sample_missing_lines.zip.003.txt)
[sample_missing_lines.zip.004.txt](https://github.com/SubtitleEdit/subtitleedit/files/8358933/sample_missing_lines.zip.004.txt)
[sample_missing_lines.zip.005.txt](https://github.com/SubtitleEdit/subtitleedit/files/8358934/sample_missing_lines.zip.005.txt)
[sample_missing_lines.zip.006.txt](https://github.com/SubtitleEdit/subtitleedit/files/8358935/sample_missing_lines.zip.006.txt)
[sample_missing_lines.zip.007.txt](https://github.com/SubtitleEdit/subtitleedit/files/8358936/sample_missing_lines.zip.007.txt)
[sample_missing_lines.zip.008.txt](https://github.com/SubtitleEdit/subtitleedit/files/8358937/sample_missing_lines.zip.008.txt)

**Comment by niksedk** [comment]
Thx for the info + file :)
Seems to be karaoke...

Latest beta does not merge bd sup images in the bd sup editor: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

Does that work for you?

I still think the OCR should merge fade/karaoke images.

It's possible to override the OCR via these two settings in settings.xml
* BluRaySupSkipMerge
* BluRaySupForceMergeAll

**Comment by manuelrn** [comment]
Thank you very much @niksedk!

Is this beta a new version now? Or is it the same version that was discussed in #5713? (since I don't see any new commits related to this Issue)

I am commenting this because yesterday I saw that Issue but as it was from January and the latest version (v3.6.5) is from March, I assumed that those changes from that beta would already be implemented in the current version, so I directly tested the current version.
<br />
Answering your question: I just tested that beta version and it works fine now!

Thank you very much again ;)

**Comment by manuelrn** [comment]
Hello again,

I just tried the latest stable version (v3.6.5) again and tried editing the `Settings.xml` file by modifying the `BluRaySupSkipMerge` option to `True`, and now it works exactly the same as the beta version you just shared with me.

So I guess the changes coming from the Issue I mentioned before are also implemented in the stable version.
And then I guess the beta version simply consists of forcing the BluRaySupSkipMerge setting to True even if it is set to False in the Settings.xml file. Correct?

Regards!

**Comment by niksedk** [comment]
> I guess the beta version simply consists of forcing the BluRaySupSkipMerge setting to True even if it is set to False in the Settings.xml file. Correct?

Yes, the bd sup editor now shows ALL images.

**Comment by manuelrn** [comment]
> > I guess the beta version simply consists of forcing the BluRaySupSkipMerge setting to True even if it is set to False in the Settings.xml file. Correct?
> 
> Yes, the bd sup editor now shows ALL images.

Okay, thank you!
<br />
In the other Issue you commented on this:
> If anyone knows a better way, do let me know!

I have thought 2 things:
<br />
First, in the program `Settings`, in the `Tools` section, there is a section called `Misc.` which contains a setting called "BD sup/bdn-xml opens in" and has a dropdown with 2 options, "OCR" and "Edit".

I thought that 2 new settings could be added, for example called "Merge equal images with no gap between them in OCR" and "Merge equal images with no gap between them in Edit", and both settings have a dropdown with "Default", "Never merge" and "Force merge all" options.
<br />
Second, would it be possible to implement skipping the merging of images except if the lines are 100% identical (in which case they could be merged)?

That is, check if the end time of the current image is identical to the start time of the next image (exact time, that is 0ms difference, 1ms or more no longer counts as identical) and also check if the current image is identical to the next image (with checksum or something like that), and if both conditions are positive then merge both images.

For example in the subtitle I attached in this Issue, images 11 and 12 have the same time (00:04:48,247) and both are identical (same checksum), so both should be able to be merged without any problem.

Thank you very much again and regards :)

**Comment by cubicibo** [comment]
Where is this SUP file from? I don't think it is compliant, or is not designed to be used on a Blu-Ray.
- Epochs are enormous (first epoch has 457 DisplaySets, 22 MiB of encoded image data).
- Epochs lasts forever (more than a minute !)
- Palette entry 0xFF is never set but used by many images for background transparent color.
