### ISSUE TITLE
[Suggestion] Default custom format extension name per template

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5873]
When exporting custom format, the file type has to be manually typed each time. It would be great to have it defined in each template. Maybe like this:

![image](https://user-images.githubusercontent.com/494788/160754205-81d88041-c00f-4f03-9178-f3201b1bfa54.png)

**Comment by niksedk** [comment]
OK, how is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
I saw the UI changed in build 41, but not quite work when saving. Maybe already fixed in build 42?  :)

**Comment by niksedk** [comment]
What is not working?
Beta updated to include latest UI fix when re-sizing: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
I mean, when clicking "Save as...", it's the same as before: 
![image](https://user-images.githubusercontent.com/494788/161025210-6a7f8221-35e2-4ae4-b23a-ea0eacaebe1a.png)
![image](https://user-images.githubusercontent.com/494788/161025070-39b7d729-8e46-46c7-ac50-e79d0aaae31c.png)

**Comment by LeonCheung** [comment]
Perfect now, Cheers!

**Comment by LeonCheung** [comment]
I can't create new templates with the latest build... XD
