### ISSUE TITLE
"c" keeps on being recognized as "o"

### ISSUE THREAD

**Issue by tormento** [SubtitleEdit/subtitleedit#5874]
I have problems with "c" recognized as "o" in the [following subs](https://www.mediafire.com/file/krbyhyxsoq3p56k/0001_Fullmetal_alchemist_brotherhood.7z/file) in binary OCR method.

Tried to start with a clean character database but it doesn't help, even manually correcting and adding the wrongly recognized ones.

**Comment by cyzs233** [comment]
_It Takes Two_ #5057
