### ISSUE TITLE
Do not break after "Dr."

### ISSUE THREAD

**Issue by HeikeMuc** [SubtitleEdit/subtitleedit#5877]
Hi there,
I don't want SE to be a break after "Dr.". I have written both "Dr" and "Dr." in the do not break after list. Nevertheless, the program wraps. The "Dr." is then always in a single subtitle. Break earl for end of sentence is not activated. How can I prevent this wrong break? Example: 

Dr.
Meier, you said ...

Thank you for help.

**Comment by niksedk** [comment]
I cannot re-create this... could you provide a couple of full examples?
