### ISSUE TITLE
Too many short lines using audio to text function for Japanese

### ISSUE THREAD

**Issue by coastal45** [SubtitleEdit/subtitleedit#5882]
When using this on Japanese audio, it returns many individual phonetic lines that are not combined.
I can use Merge Short Lines to group them, but there is no real language processing there.

![Screenshot from 2022-04-03 13-10-57](https://user-images.githubusercontent.com/102390147/161447484-057ebf8d-78d4-4c79-ad63-6818ae33022c.png)

![Screenshot from 2022-04-03 13-11-16](https://user-images.githubusercontent.com/102390147/161447521-27c24d06-5266-4e07-89ea-a1a856762a7f.png)

With English, audio lines are basically complete and joined together.

So I’d like to understand if this is merely the results returned from Vosk, or if some action in SE is causing this.
There is a check box for post-processing in SE, is that involved?

**Comment by niksedk** [comment]
SE does the auto-merging - if the post processing check box is checked.

If it's not working, could you provide an audio file I can test with?

**Comment by coastal45** [comment]
I confirmed post-processing is checked. Attached is a short video clip with the .srt result I got.


https://user-images.githubusercontent.com/102390147/167480768-0d8c4797-3cb4-4318-adc4-0e7c4b3ad50a.mp4
[clip2_edit.txt](https://github.com/SubtitleEdit/subtitleedit/files/8654641/clip2_edit.txt)

**Comment by coastal45** [comment]
I confirmed post-processing is checked. Attached is a short audio clip along with the .srt result I got.
[test clip.zip](https://github.com/SubtitleEdit/subtitleedit/files/8655335/test.clip.zip)
.

**Comment by niksedk** [comment]
Thx for the files :)

Hopefully latest beta is better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by coastal45** [comment]
Thanks for the quick revision. It looks like it works well.
On some larger samples, I compared this result, and what I was previously doing.

That was:
On the release software, I ran the speech to text function, then after that Tools--> Merge short lines...

The result is basically the same, though the formatting of this one is a bit better than the revision. Depending on what the revision actually changed, just running speech to text as it was and program in the Merge short Lines function might be enough.

One other point worth looking at... As you can see in either version results, after each phoneme or grouping that Vosk recognizes, there is a space. For example:

3
00:00:05,700 --> 00:00:07,980
千 九百 五十 七 年 に 始まっ た

While the spaces can be removed by global replace in a text editor, it would be great if the spaces could be removed during the software processing.

**Comment by niksedk** [comment]
Thx for the input :)

Is this beta any better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip ?
(max char per line is now 12 - and periods are not added)

Do you know if Chinese should be handled similar?

**Comment by coastal45** [comment]
Thanks. Yes this is much better.

I made a larger sample that's attached. But it looks really good.

There is one minor point I'd like to understand better. In the attached srt, there are these examples...

```
40
00:01:09,060 --> 00:01:10,200
となるものが見つかり

41
00:01:10,230 --> 00:01:11,230
ました
***
49
00:01:31,500 --> 00:01:33,270
研究者の関心を引きまし

50
00:01:33,270 --> 00:01:34,270
た
***
73
00:02:18,030 --> 00:02:20,070
現在の近畿地方を基盤と

74
00:02:20,070 --> 00:02:20,370
する
```

In each pair, the second one is just finishing up the first one (together they are one phrase), and there doesn't seem to be enough separation to justify it being a separate line.
Is this related to the max char per line being 12? If so, maybe raise it to 16? Or another reason?

As for Chinese, I would say it should be the same, but I don't know any Chinese other than similarity of written characters. You might ask YingziWo who asked about this too, on Issue #5918.
They might be able to confirm it.

[clip 3_edit 0512.zip](https://github.com/SubtitleEdit/subtitleedit/files/8692054/clip.3_edit.0512.zip)

**Comment by niksedk** [comment]
@coastal45: Yes, this is related to the `max char per line` - it's 13-ish now (can go a little bigger).

Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by coastal45** [comment]
Latest beta looks good at this point. I'll check some samples in more detail (and do some editing), but additional issues will more likely be related to the Vosk model. Japanese by nature has issues that make the interpretation of speech (without considering context) difficult. It doesn't seem like the current model really addresses that.

**Comment by coastal45** [comment]
After checking further, in addition to segment joining, the readability seems better too. At this point I consider this issue resolved.

**Comment by niksedk** [comment]
OK, they don't have like a json or xml format?
