### ISSUE TITLE
Go to previous/next subtitle shouldn't place cursor within text area at all

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#5884]
I'm using shortcut **Video/Go to previous/next subtitle(from video position)** as navigation shortcuts. (all go to previous/next from General category will auto select text, It's often do more harm than good IMO).

Normally, I would use these two shortcuts to navigate between subtitle lines and press the space bar to playback the video.

But after you entered some text in "text area", this shortcut will "remember" that you did editing work, and put a cursor at the beginning of the next subtitle line. In such situation, you won't be able to press space to playback the video. (As it will be entered into "text area"). Demo below:
<details><summary>Demo</summary>

<p>

![GIF 04-04-2022 22-46-29](https://user-images.githubusercontent.com/25927091/161573120-63822fa9-2be0-4867-964b-e81574496007.gif)

</p>
</details>

Above mentioned behavior will make this shortcut similar to its sibling from "general" category. 
Additionally, I think we need a separate shortcut for "focus cursor in and out text box"(to avoid using mouse at all). Translation is a text intense task, best using keyboard throughout for an immersive experience.

Extra note: I think these two shortcuts are buggy, it do jump to adjacent subtitle line, but sometimes are jump at the middle rather than at the beginning. This bug appeared right after I assigned them to keyboard keys, and works fine afterwards. My guess is that it has something to do with "video parsing" related stuff🤔
💘

**Comment by LeonCheung** [comment]
Why not move the mouse towards Waveform? There's an option to switch focus:

![image](https://user-images.githubusercontent.com/494788/161601333-e7132e8b-a705-4dc3-ba53-4dcc942350ee.png)

Or, try setting another shortcut to play/pause other than using Spacebar, e.g. Function keys, or combo keys, even keys on your mouse if it's supported by the device.

**Comment by cyzs233** [comment]
@niksedk 
So, I'm basically on my way to writing another issue addressing the same problem. But this time, I come up with a solution instead: 
Either we implement another option : "Set focus on mouse enter for video preview window" or 
"Always shift window focus out of text area when clicking on the video preview window."

[LeonCheung](https://github.com/LeonCheung)'s solution works but it is just a counterintuitive thing to do when you simply want to pause the video.
Below is what you should be doing in the subtitleedit's way in order to pause the video.
![Untitled](https://user-images.githubusercontent.com/25927091/178125822-b924b793-3870-4988-84d3-c221c17f22ef.png)

<details><summary>And what will happen if don't follow the rules. </summary>

<p>

![GIF 10-07-2022 07-12-42](https://user-images.githubusercontent.com/25927091/178125808-e814043d-4b4d-4812-9e00-022d42bc4002.gif)


</p>
</details>
(<kbd>e</kbd> is a one-key shortcut I assigned for shifting timeline.) 
Since the window focus is still set on the edit section, I'm not allowed to use these non-control characters for shortcuts and am forced to use double-key shortcuts which start with control characters like <kbd>Control</kbd>/<kbd>Shift</kbd>/<kbd>Alt</kbd>, which is not user-friendly in my opinion.

**Comment by darnn** [comment]
I don't know how helpful you'll find this, but I use control+space for pause/play. I think this would solve your original problem, you'd be able to maintain focus on the text box and still pause/play. But then you'd have to change the thing you're used to, so I realize it's less than ideal.

**Comment by LeonCheung** [comment]
@cyzs233 Actually, you don't have to move the mouse cursor over the player area. You can simply move it down to the waveform, then hit <kbd>Space</kbd>, and it won't conflict with the  <kbd>E</kbd> key you defined for that function.

**Comment by cyzs233** [comment]
Come on fellows, is this a pure upgrade to the current workflow, which will save you the trouble of mastering unnecessary tricks, or is that there will be some workflow hindered by my amateur efforts?

**Comment by LeonCheung** [comment]
It seems you raised several topics under this thread... Could you just rephrase what you really want/expect with a few words so that we could hopefully get it loud and clear?

**Comment by cyzs233** [comment]
So basically, this continuing text-section-cursor-focusing feature is a bad thing, we should toast it into the trashcan. 
And enforcing another philosophy:  Only focus on it when user is actually trying to type some words, grey it out whenever possible. (A Switch would be best if you ask me)

**Comment by LeonCheung** [comment]
`>> ...Only focus on it when user is actually trying to type some words, ...`

But in your case, you said you don't want to type the letter **e** or **Space** accidentally into the textbox when using them as shortcuts elsewhere. Isn't it contradictory here?

@darnn and I both provided kind of one-key solutions for you as well, no mouse involved. I think you are requesting some kind of feature/shortcut like  **`toggle play/pause and focus out of the textbox`** . In that case, it's not a bad idea for this kind of workflow, say, using <kbd>Ctrl</kbd><kbd>Space</kbd>, in which case, you would be happy to use single-letter shortcuts afterward, like the <kbd>E</kbd> key you assigned.

**Comment by cyzs233** [comment]
So, I did a venture into the subtitle word and find some info and solution that deemed worthy of sharing.

@darnn actually discussed an identical problem just a few months ago. #4536. 
Of course, he is using <kbd>Backslash</kbd> instead of <kbd>m</kbd> in his case.
And niksedk impleneted couple soluions. You can either: 
> You need to change **AllowLetterShortcutsInTextBox**'s value to **true** in Settings.xml.

or 
> tick this option in the setting.

![Untitled](https://user-images.githubusercontent.com/25927091/179665862-41d36693-0db1-47d6-a5a5-dd0d17d1fecd.png)

The only problem is that you just have to pray you're not fat-finger enough to type some random characters into the text section. 

And whoever implemented this feature knows exactly what a pain it is to have the text box always focused. Now he has the privilege to assign a one-key shortcut for it (<kbd>m</kbd>) and be able to press other shortcuts as he sees fit.
![Untitled](https://user-images.githubusercontent.com/25927091/179666879-8589ba4f-0e90-437c-b217-a8820268d79c.png)

There are also two related issues about proactively focusing on text box. (If they ever get greyed out in the future)

> You can do it by using the **Toggle focus between list view and subtitle text box** twice, and it will take you to the text box. #5040

and a feature request. #4376

**Comment by niksedk** [comment]
There's also a new shortcut for "Toggle focus between waveform and text box".
Go to previous/next subtitle shortcuts should only focus text box when in "translate mode".

I will close this for now.

**Comment by niksedk** [comment]
Would new "go to next/prev and focus waveform" shortcuts help? 

The hard stuff here is that people like different way of doing stuff - and people even do different stuff o:)

**Comment by niksedk** [comment]
Well, the good old "go to previous/next subtitle" shortcuts should only focus text box when in "translate mode" - kinda does the same, but hey, there are now two new shortcuts in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
Are they working okay?

**Comment by cyzs233** [comment]
Thanks, it works and gets the job done, what more can I ask!

I'm not sure how much you have been following on the above discussion, but now we are at it, any chance another related UI tickable option "Set waveform focus on mouse enter in video view" be implemented. 😉
