### ISSUE TITLE
Suggest hyphen match included in common errors

### ISSUE THREAD

**Issue by iPolluxGem** [SubtitleEdit/subtitleedit#5888]
Checking for hyphen consistency in both source and target. If there's a pair of hyphens for dialogue in one subtitle line in source, and the hyphens in target doesn't match, or there are hyphen missing, there seems no easy way to check this. For example, "-I gotta go.\</br>-We'll see." in source, and the targets goes like "我得走了\</br>-我们走着瞧", and there might be a solution for such situations?

**Comment by cyzs233** [comment]
Is this option is what you're looking for?
<details><summary>Demo</summary>

<p>


![dashes](https://user-images.githubusercontent.com/25927091/162097949-675e9c2d-041f-40a7-8087-42a79d45e698.png)


</p>
</details>
