### ISSUE TITLE
v3.6.5 very slow to open certain mp4 files now

### ISSUE THREAD

**Issue by jupester** [SubtitleEdit/subtitleedit#5895]
Hi, this is a follow up to an issue I reported earlier, https://github.com/SubtitleEdit/subtitleedit/issues/5610#issuecomment-1073071209 I re-commented on that issue knowing you would probably not see it since it was closed, so anyway here is the new report, but you can refer to that topic because it may contain required info.

Basically since you made the changes in the linked topic, I no longer get the error dialog, but instead files take 35+ seconds to open a 45min file of that certain type of mp4.  Previously they would open near instantly but with error dialog.

Let me know if you need me to to upload a large 45min+ mp4 of that certain type for reproducing the issue, because normal mp4s load fine, its just this certain type that is affected.

**Comment by niksedk** [comment]
OK, please do upload a test file :)

**Comment by jupester** [comment]
Ok here is a link

https://workupload.com/file/EmvfHUvFFK8

it is just a random file and random srt, the subtitles don't match the video, and it is only 37min, but it will still demonstrate the slow loading.

Thanks.

**Comment by niksedk** [comment]
thx for the info + file :)

Hopefully better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by jupester** [comment]
Thanks, yes they seem to load the same speed as other mp4's again, job done.

Thanks for creating such a great app,
