### ISSUE TITLE
Fix common errors: Period after lines

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5899]
Hello!
I've had this problem.
Is it just me or some else has had the same issue?
![E1](https://user-images.githubusercontent.com/64425752/162630936-c506b517-1098-4fbe-b643-8e58d0a3eaa1.jpg)

**Comment by cyzs233** [comment]
"Next line" means "next subtitle line".
It works like this
![add period](https://user-images.githubusercontent.com/25927091/162900764-5890313e-9abc-49cc-bfc1-a0ecc8d2a05d.png)
.

**Comment by Andrebavila** [comment]
> "Next line" means "next subtitle line". It works like in the below picture. (I'm afraid you're gonna type "." in your example manually. Otherwise, S.E might misplace "." before "I"/names, etc.) ![add period](https://user-images.githubusercontent.com/25927091/162900764-5890313e-9abc-49cc-bfc1-a0ecc8d2a05d.png) .

I already know what it means.
This text was taken from a srt file which has hundreds and hundreds of lines.
This function is not working anymore.
I just have asked for a fix.
I hope for it.
