### ISSUE TITLE
Can't use IME to input into text

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#5904]
![image](https://user-images.githubusercontent.com/54498172/163206420-9e704298-d509-4b53-a25f-662c475a625a.png)

The IME will despair after a flash, then leave one letter.

![image](https://user-images.githubusercontent.com/54498172/163207358-71bc609f-d01d-4fb1-b8be-e4b8a346b1e8.png)

**Comment by Mishasama** [comment]
![image](https://user-images.githubusercontent.com/54498172/163211349-9623349b-4b2a-42eb-b246-99ffefed36aa.png)

It will occur when enabling the syntax coloring.

**Comment by niksedk** [comment]
Not really in my control I think.... sorry.

Is any of these better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SEBetaDotNet6.zip
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by Mishasama** [comment]
> Not really in my control I think.... sorry. SE just uses the RichText control included with WinForms/Visual Studio.
> 
> Is any of these better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SEBetaDotNet6.zip https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

What's different? You mean .NET6?

Nothing changes with these versions.

**Comment by euzenlee** [comment]
I'm having the same problem on one win10 computer, can't input any Chinese. But on another win10 everything is fine, so I guess it has something to do with my own computer, like some software version doesn't match.

**Comment by williamsp** [comment]
I'm having the same problem using SubtitleEdit version 4.0.12 on Windows 11.

To be able to format the text, the syntax coloring feature somehow "commits" the IME input prematurely, even when the user is not yet finished typing or the conversion has not yet been done, maybe? Also, this feature causes some Japanese text (if the first character is kanji, not hiragana) to be displayed in incorrect font (maybe Chinese).

But thanks to @Mishasama, at least I can temporarily disable the syntax coloring feature to be able to input Japanese text, and all of the lines now displayed using a single font.
