### ISSUE TITLE
[Feature Request] Blank video preview with audio and subtitle

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#5905]
Would it be possible to make a feature, so that we could disable video feed in video player preview, but leave the audio sounding and subtitles showing?

Sometimes the video is distracting, but I have to see how the subtitles fit the video. I can't find a way to do this except for rendering a new video each time in other software with disabled video but enabled audio feed.

Generating a blank video file didn't work for me, because it doesn't save audio in the new file.

**Comment by niksedk** [comment]
You can turn off the video in the toolbar - or you can use mkvtoolnix to remove the video track
