### ISSUE TITLE
[Feature Request] remove hearing impaired text using command line

### ISSUE THREAD

**Issue by siamak2** [SubtitleEdit/subtitleedit#5908]
Hi.
can you add an argument to command line to remove the hearing impaired text?
something like `/nohi` or `/removehi`
PS. I've changed some of the "remove text conditions" in the app so command line should use user defined conditions to remove HI.

**Comment by niksedk** [comment]
Try `/RemoveTextForHI`

**Comment by siamak2** [comment]
thanks.
I didn't know about this. the only reference I found was this:
https://www.nikse.dk/subtitleedit/help#commandline
which didn't list that argument.
