### ISSUE TITLE
App freezes after Visual Sync

### ISSUE THREAD

**Issue by ilCosmico** [SubtitleEdit/subtitleedit#5912]
Trying to use the Visual Sync for the attached srt file, I'm not able to save the file after changes because the app freezes.

Here a short video showing it.
![BugSubtitle](https://user-images.githubusercontent.com/8678145/163708619-e4028a89-cc48-40ad-8413-9117fdf4402f.gif)

[Scemo E Piu Scemo (1994).ita.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/8501282/Scemo.E.Piu.Scemo.1994.ita.srt.zip)

**Comment by niksedk** [comment]
Hm, works fine here...
Try updating libmpv: Go to Options - Settings - Video player, and click "download mpv lib"

**Comment by ilCosmico** [comment]
Ok, it made the trick! Thanks a lot!
