### ISSUE TITLE
How to find lines without space after hyphen?

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#5913]
Hello.
I have subtitles in which some dialogues don't have space after a hyphen and they should.
I corrected them manually but I might have missed some.
Is there a way to **find** only the lines which don't have space after a hyphen?
I looked at FCE but could not find anything related to that.

**Comment by niksedk** [comment]
First, setup the `dialog style`
![image](https://user-images.githubusercontent.com/1261331/163716715-5845c89b-3c9c-4902-871b-b166f86baee8.png)


The use `Fix dash in dialogs via style: xxx`
![image](https://user-images.githubusercontent.com/1261331/163716746-aecd1700-d841-4923-b4d5-9fdd31f0db36.png)

**Comment by m0ck69** [comment]
Thanks a bunch. I'll give it a go.
BTW, is there a way to save preferences in FCE? Everytime I use it, the same boxes are checked by default.

**Comment by niksedk** [comment]
FCE should remember settings... also, you can right-click, and set current fixes as defaults.

Also, to list lines with the issues, you can do Edit - Modify selection:
![image](https://user-images.githubusercontent.com/1261331/163716936-995c2b92-c239-4574-9bc9-eec10cfccd9f.png)

**Comment by m0ck69** [comment]
thanks!
