### ISSUE TITLE
Associated subtitle file type displays incorrectly

### ISSUE THREAD

**Issue by trietng** [SubtitleEdit/subtitleedit#5914]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/93473943/163770108-09f6e891-35db-4bf7-8b24-d8eba33cdbf5.png">
Shouldn't it be "SRT subtitle file" or something like that?<br/>OS: Windows 11 build 22000.613

**Comment by niksedk** [comment]
Thx for reporting - will be fixed in next update :)
