### ISSUE TITLE
Video to text with Kaldi

### ISSUE THREAD

**Issue by strayberryfilling** [SubtitleEdit/subtitleedit#5917]
Hello,

The changelog says you can use Kaldi to generate video to text, but I don't know where to put the directory (putting it in the Vosk directory doesn't work)

I'm trying to use the [CVTE Mandarin](https://kaldi-asr.org/models/m2) model. Is this compatible?

**Comment by nshmyrev** [comment]
You'd better use https://alphacephei.com/vosk/models/vosk-model-cn-kaldi-multicn-0.15.zip, it is more accurate than CVTE

**Comment by nshmyrev** [comment]
If you still want CVTE, you can download https://alphacephei.com/vosk/models/vosk-model-cn-kaldi-cvte-2.zip

**Comment by strayberryfilling** [comment]
Great, thank you!
