### ISSUE TITLE
Video / audio to text...  problem

### ISSUE THREAD

**Issue by YingziWo** [SubtitleEdit/subtitleedit#5918]
![SubtitleEdit_Err0](https://user-images.githubusercontent.com/104121906/164380890-dc6419af-f700-4f69-9175-920c3738f1a6.JPG)

Click "OK"
![SubtitleEdit_Err1](https://user-images.githubusercontent.com/104121906/164381346-a57ad483-1d6a-4b3d-a302-3fcaf24005f4.JPG)

Click "Generate"
![SubtitleEdit_Err](https://user-images.githubusercontent.com/104121906/164381555-5d5c1663-9389-4508-91eb-f1111ae84bc4.JPG)

How to deal with this problem. 
Thanks!

**Comment by eladkarako** [comment]
it creates a folder named `Vosk` in the SubtitleEdit folder,  

it downloads `vosk-win64-0.3.32.zip` from https://github.com/alphacep/vosk-api/releases and unzip it there (flat),  

and `vosk-model-en-us-0.22-lgraph.zip` (Big US English model with dynamic graph) from https://alphacephei.com/vosk/models
(content sits under `vosk-model-en-us-0.22-lgraph`, target file for example:  `D:\Software\SubtitleEdit\Vosk\vosk-model-en-us-0.22-lgraph\graph\HCLr.fst`).  

in my case download and extraction worked very well (I've verified it by comparing it vs.  the original packages I've downloaded manually),  

```txt
\Vosk
|   libgcc_s_seh-1.dll
|   libstdc++-6.dll
|   libvosk.dll
|   libwinpthread-1.dll
|   
\---vosk-model-en-us-0.22-lgraph
    |   README
    |   
    +---am
    |       final.mdl
    |       tree
    |       
    +---conf
    |       mfcc.conf
    |       model.conf
    |       
    +---graph
    |   |   disambig_tid.int
    |   |   Gr.fst
    |   |   HCLr.fst
    |   |   phones.txt
    |   |   words.txt
    |   |   
    |   \---phones
    |           word_boundary.int
    |           
    \---ivector
            final.dubm
            final.ie
            final.mat
            global_cmvn.stats
            online_cmvn.conf
            splice.conf

```

but I did got an exception:

<img src="https://user-images.githubusercontent.com/415238/164965621-1f691d9d-bb48-4d88-af8d-ba863f94d6cf.png">

it didn't matter when I've moved the dlls to the main folder.

it might be an issue with `libvosk` bad build or something (not declaring a manifest identity properly?)

<hr/>

here is the content, sorry I've used http://capture2text.sourceforge.net/
since there was no way of extracting it by hand, and no log a.f.a.i.c.t.

```txt
An application error occurred in Subtitle Edit 3.6.5.0.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with
the following information:
Error Message:
Could not load f‌ile or assembly 'Vosk, Version=0.0.0.0,
Culture=neutral, PublicKeyTokenznull' or one of its dependencies.
The system cannot f‌ind the f‌ile specif‌ied.
Stack Trace:

at NikseSubtitleEditFormsAudioToTextTranscribeViaVosk(String
waveFileName, String modelFileName)

at NikseSubtitleEditFormsAudioToTextButtonGenerate_C|ick(Object
sender, EventArgs e)

at System.WIndows.FormsControLOnClick(EventArgs e)

at System.Windows.Forms.Button.OnClick(EventArgs e)

at System.VVIndows.Forms.Button.OnMouseUp(MouseEventArgs
mevent)

at System.VWndows.FormsControLWmMouseUp(Message& m,
MouseButtons button, |nt32 clicks)

at SystemMf‌indows.Forms.Control.WndProc(Message& m)

at System.\Mndows.Forms.ButtonBase.WndProc(Message& m)

at System.\Mndows.Forms.Button.WndProc(Message& m)

at System.Windows.Forms.NativeWindow.Callback(|ntPtr hWnd,
lnt32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by niksedk** [comment]
Does it work if you have SE portable in a folder with only us chars, like `C:\Tools\SE` ?

**Comment by YingziWo** [comment]
Yes, after manually adding 4 dll files to the Vosk directory, the Video/Audio to Text... function of SubtitlesEdit works fine.
Thanks!

My system: Windows 64 bit system

Subtitles is installed by default and occupies two directories:
1) C:\Program Files\Subtitle Edit
2) C:\Users\Administrator\AppData\Roaming\Subtitle Edit
There is a Vosk directory in the second directory, and the 4 Dll files after decompression of vosk-win64-0.3.32.zip of the corresponding system will be downloaded from https://github.com/alphacep/vosk-api/releases and added. to this Vosk directory.
Models in various languages manually downloaded from https://alphacephei.com/vosk/models are also placed in this Vosk directory.

At the same time, today I found that there is still an error_log.txt file in the directory C:\Users\Administrator\AppData\Roaming\Subtitle Edit. Open this file and see the reason for the error.

**Comment by eladkarako** [comment]
> Does it work if you have SE portable in a folder with only us chars, like `C:\Tools\SE` ?

> Yes, after manually adding 4 dll files to the Vosk directory, the Video/Audio to Text... function of SubtitlesEdit works fine.

I forgot to mention,  
in my case I'm using the portable version (local `Settings.xml`) which does not work.

does the non-portable version does any .Net-assembly registering?
(Vosk does not seems to have any external functions in the dll,  
so I assume they are pure .net assembly)

**Comment by YingziWo** [comment]
Full manual installation of the portable version of Subtitle Edit:
1) Download the latest version SE365.zip at https://github.com/SubtitleEdit/subtitleedit/releases, unzip it on the hard disk location to be installed, and a SE365 directory will be generated;
2) Download the latest version from the ffmpeg official website http://ffmpeg.org/ and install it, find the ffmpeg.exe generated after installation, and copy it to the root directory of SE365;
3) Run the SubtitleEdit.exe file in the SE365 directory, then click "Options" ---> "Seting..." ---> "Waveform/spectrogram" Check "Use FFmpeg fo wave" in the "FFmpeg" tab extraction" , and after selecting the path of the FFmpeg.exe file, click the "OK" button under the "Settings" page.
![SE365_Version0](https://user-images.githubusercontent.com/104121906/165221989-68e8597f-9051-499b-961c-e4bf9d32b5f8.JPG)


4) Click "Video"--->"Open video file..." to select a video or audio file to be processed, after loading;
5) After clicking "Video"--->"Video/Audio to text...", a dialog box for downloading Vosk will appear, select the "No" button. At this time, a Vosk directory is added under the SE365 directory;

![SE365_Version1](https://user-images.githubusercontent.com/104121906/165222053-c07e38af-41b0-4b43-ac77-3680caf128e4.JPG)

6) From https://github.com/alphacep/vosk-api/releases, download the corresponding vosk-win64-0.3.32.zip decompressed 4 Dll files and add them to the Vosk directory;
7) Models in various languages ​​manually downloaded from https://alphacephei.com/vosk/models are also placed in this Vosk directory.

![SE365_Version](https://user-images.githubusercontent.com/104121906/165222076-962c0134-400a-4cfb-b384-14a78edd5783.JPG)

Then click "Video"--->"Video/Audio to text..." again, it will work normally.

**Comment by eladkarako** [comment]
nope, same.  
in fact if repeated while audio is playing, it will also crash.

tried various video-audio encoding/containers/<a href="https://github.com/nanake/ffmpeg-tinderbox/releases/latest">ffmpeg</a> variations,  
here is with <a href="https://www.youtube.com/watch?v=r2kEj9zXzBA">mp3</a> and Japanese model,  
just to keep things fresh (unmute..).

https://user-images.githubusercontent.com/415238/165226111-d2b3c68a-c433-492f-8c75-c39577f40dcf.mp4

**Comment by YingziWo** [comment]
In the Japanese Ja Model and Chinese Mandarin Cn Model applications of the Audio to text function, it seems that only a single sound or a single word can be recognized when the speech is converted into text, and a sentence cannot be formed. The sentences tend to be fragmented, and the amount of later intervention and adjustment is very large.
![Ja and Cn](https://user-images.githubusercontent.com/104121906/165238494-350771e2-f65b-427c-9610-b44e8b46c0e9.JPG)

**Comment by coastal45** [comment]
I raised this issue in Issue #5882 . My question was whether this effect was returned from the Vosk model or done by SE. It doesn't seem to happen in English, so I suppose the Vosk model is responsible for making logical sense of phrases.
As for the fragments within a phrase (with some separation between them), you can use Tools --> Merge short lines... to join them. But as mentioned in the Vosk documentation, the audio quality is very important in getting a good result (clear speech with no background noise). It's my experience so far.

**Comment by YingziWo** [comment]
> I raised this issue in Issue #5882 . My question was whether this effect was returned from the Vosk model or done by SE. It doesn't seem to happen in English, so I suppose the Vosk model is responsible for making logical sense of phrases. As for the fragments within a phrase (with some separation between them), you can use Tools --> Merge short lines... to join them. But as mentioned in the Vosk documentation, the audio quality is very important in getting a good result (clear speech with no background noise). It's my experience so far.

Indeed it is. Speech recognition and composition of sentences mainly depend on the capabilities of the VOSK module.

**Comment by niksedk** [comment]
@YingziWo: Latest beta should form longer sentences now... let me know how it works for Chinese: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by YingziWo** [comment]
> @YingziWo: Latest beta should form longer sentences now... let me know how it works for Chinese: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

The ability of this beta version of Mandarin Chinese to form sentences is obviously much stronger than that of the official version. Looking at it this way, there is something wrong with my point of view. By comparing the speech-to-text function of the beta version and the official version, when using the same Model, the same speech sample is converted, and the beta version is much stronger in the composition of sentences. It can be seen that the composition of sentences is the SubtitleEdit program. main effect.

**Comment by niksedk** [comment]
Also see https://www.nikse.dk/subtitleedit/help#audio_to_text
