### ISSUE TITLE
Possible Mistake

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#592]
Shouldn't this return -1 https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Core/StringExtensions.cs#L95 /cc @niksedk

**Comment by xylographe** [comment]
The built-in `IndexOf()` returns zero when the pattern is an empty string,
```
PS> "abc".IndexOf("bc")
1
PS> "abc".IndexOf("")
0
```

**Comment by ivandrofly** [comment]
:+1:

**Comment by ivandrofly** [comment]
Can be closed /cc @niksedk
