### ISSUE TITLE
auto translate removes '\' from '{\i0}' and '{\i1}' (SubStation Alpha)

### ISSUE THREAD

**Issue by eladkarako** [SubtitleEdit/subtitleedit#5922]
what is kept (along with the auto-translated content) are `{i0}` and `{i1}`, 
which needed to be fixed manually afterwards.

it is an example it does the same for bold and other styles that have pair of tags.

**Comment by niksedk** [comment]
Thx for reporting this :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

It's probably not a good idea to run a heavy styled assa file through auto translation.

**Comment by eladkarako** [comment]
<blockquote>It's probably not a good idea to run a heavy styled assa file through auto translation.</blockquote>

true.

my workaround was,  
a little nodejs code (actually two) that walks through the text,  
replaces every `{.....}` with a placeholder (`###1234###` - no English === non-translatable), it does not care about pairing matching pairs,  
just super dumb string manipulation.  
it creates a "dictionary" (in an external file).  

this still creates a perfectly (ugly) subtitle with all sensitive stuff cut away, safely protected from modifications.

I then use auto-translate.

afterwards I run the subtitle through the reverse process,  
the placeholders are replaced with the original data.

I wish I could streamline external scripts in SubtitleEdit somehow,  
or custom exclude regexp from auto-translate..

**Comment by eladkarako** [comment]
<blockquote>Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip</blockquote>

I like it, that is a nice fix.  
 https://github.com/SubtitleEdit/subtitleedit/commit/b5928d20b7a90e09383c55da4526199589dedf54#diff-75792b20c5175a2a54c4644c2230467860d213a9d0f8db61a05ba94327338fcaR484-R492

<hr/>

note:  

I haven't came across issues with other tags in real world examples,  
but there are $h!t load (pardon my French) of styles that matches semi-translatable English phrases.

https://forencode-com.translate.goog/aegisub-alt-yazu-duzenleme-kodlari?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp#language-markup

such as `{\be}` or `{\blur}` (for blur) or `{\alpha}` for transparency.  

it is especially weird if the original subtitle is not English but something like 
Finnish <sub>(not the dishwasher tablets;)</sub> which also takes (sometimes) stuff like `{\fe}` or `{\fad(1200,250)}` (for example) for Fade text over few milliseconds.

<sub>
(the official spec. <a href="http://www.tcax.org/docs/ass-specs.htm">http://www.tcax.org/docs/ass-specs.htm</a> 
does not lists much more, but just to be sure,   
but I still uses my workaround (encode/decode) which is not content sensitive.)
</sub>

**Comment by niksedk** [comment]
Added a bit more tags:
https://github.com/SubtitleEdit/subtitleedit/blob/master/src/ui/Forms/Translate/GenericTranslate.cs#L482

I've also listed ASSA tags here (tried to make some examples too): https://www.nikse.dk/subtitleedit/formats/assa-override-tags

**Comment by eladkarako** [comment]
nicely done, thank you for you hard work. if I haven't said it before, this is a one superb piece of software.
