### ISSUE TITLE
Error with Video/Audio to text

### ISSUE THREAD

**Issue by ilCosmico** [SubtitleEdit/subtitleedit#5923]
Step to reproduce the issue:
1. Open video from URL: https://www.youtube.com/watch?v=OFFK5Fd7uLY
2. Choose Video/audio to text...
3. Start it and you will get the below error.

![image](https://user-images.githubusercontent.com/8678145/164884841-7bb8d626-ba55-4000-b486-9c931d1efdbb.png)

**Comment by niksedk** [comment]
Sorry, it's possible to generate text from online video/audio.

SE will now display an error:
![image](https://user-images.githubusercontent.com/1261331/164885380-4845b13a-891c-4856-93b0-ac1de3f1317a.png)
