### ISSUE TITLE
Error pasting spanish text

### ISSUE THREAD

**Issue by mapasteper** [SubtitleEdit/subtitleedit#5925]
Every time I paste Spanish text, the editor fails when my text contain ñ,á,é,í,ó,ú,ü,!,?

![image](https://user-images.githubusercontent.com/24288197/164955689-1020dfd9-932e-4b55-9b21-6328ed6d0478.png)

**Comment by niksedk** [comment]
I think this is a Mono issue: https://github.com/mono/mono/issues
