### ISSUE TITLE
OCR Spellcheck conflict

### ISSUE THREAD

**Issue by brhurrell** [SubtitleEdit/subtitleedit#5927]
SubtitleEdit 365. When I do a spellcheck to British English, words like "traveling" and "canceled" are correctly changed to travelling and cancelled, but when I use the "fix common errors" function afterwards it flags these words up as OCR errors.

**Comment by niksedk** [comment]
Hm, I don't get this issue - could you try a clean install or the portable version w latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by brhurrell** [comment]
Hi  I also get the same issue with words like "honour" and "armour". I
spell check with UK English from US English, then when I'm finished
everything I want to do, I recheck "fix common errors in selected lines"
and it comes up with"OCR errors" trying to change the spelling back to US
English.
 I reinstalled 364 and so far I'm not getting any problems.

Cheers
