### ISSUE TITLE
 input file too large!

### ISSUE THREAD

**Issue by Emerica** [SubtitleEdit/subtitleedit#5930]
Seem to have an issue with batch conversion, I'm able to open this file on Windows 3.6.5, though it takes some good time to parse.
I have some automation that's using headless debian and would like to convert these mcc's to scc.

```
 DISPLAY=:0 mono ./SubtitleEdit.exe  /convert /xxx/xxx/A.mcc ScenaristClosedCaptions /fps:29.97 /outputfolder:/tmp

Subtitle Edit 3.6.5 - Batch converter

/xxx/xxx/A.mcc: scenaristclosedcaptions - input file too large!

0 file(s) converted

```

Any ideas?

**Comment by niksedk** [comment]
How large is the file?

**Comment by Emerica** [comment]
~12MB - 12375112
That's only a ~6minute segment though could have longer potentially.


Is there anyway to append/concatenate + ripple via cli
Been a great debugging tool for me this week.

**Comment by Emerica** [comment]
File Format=MacCaption_MCC V2.0
MCC V2.0 - 30DF
MacCaption Version 5.4

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip
