### ISSUE TITLE
waveform problem

### ISSUE THREAD

**Issue by fumikokf** [SubtitleEdit/subtitleedit#5932]
New to this program. 
When I tried to add waveform to my video, I got this error message. 
How can I fix this? 
![image](https://user-images.githubusercontent.com/104466877/165397404-cbb07293-9c09-43d9-b4c1-573e8ad2d554.png)

**Comment by niksedk** [comment]
Try using ffmpeg for generating the waveform - go to Options - Settings - Waveform, click on "Download ffmpeg".
And then try generating the waveform again... better?

**Comment by fumikokf** [comment]
Already tried that. No change!


On Apr 26, 2022, at 9:09 PM, Nikolaj Olsson ***@***.***> wrote:

﻿

Try using ffmpeg for generating the waveform - go to Options - Settings - Waveform, click on "Download ffmpeg".
And then try generating the waveform again... better?

**Comment by niksedk** [comment]
OK, what OS are you on and how much free disk space do you have on drive C?

Try using the portable version - https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SE365.zip
Unpack to something like C:\Tools\SE

**Comment by fumikokf** [comment]
I’m on Windows10 and I have more than 7GB of space.
I tried what you suggested but it is not working.
What could be the problem?



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by niksedk** [comment]
Don't know why it's not working for you - could it be something with access rights?

**Comment by eladkarako** [comment]
this exception is also thrown when the file is already opened.  
(`File.Open` locks the file).  
maybe clicking twice (fast enough) on the waveform area gets the click handler execute more than once (and the second time probably fails because of it).

**Comment by niksedk** [comment]
This should be fixed in latest beta... it seems VLC has starting locking files.
Switching video player to mpv should also fix the problem.
