### ISSUE TITLE
Subtitle Edit crashes in Wine when mpv is used

### ISSUE THREAD

**Issue by bugisbuggingme** [SubtitleEdit/subtitleedit#5933]
Subtitle Edit (SE) running on Wine crashes every time a video is loaded with mpv set as the video engine. It doesn't crash when VLC media player is used, nor when it runs on Mono. Is there a way to prevent the mpv lib crash in Wine?

Subtitle Edit 3.6.5

> Unhandled exception: page fault on write access to 0x00000000 in 32-bit code (0x6e952ef4).
> Register dump:
>  CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
>  EIP:6e952ef4 ESP:16dbfa00 EBP:16dbfa40 EFLAGS:00010246(  R- --  I  Z- -P- )
>  EAX:0fbf58f0 EBX:0fbe09ac ECX:16dbf970 EDX:00000000
>  ESI:16dbfb7c EDI:00000000
> Stack dump:
> 0x16dbfa00:  0fbe09ac 16dbfb7c 00000000 16dbfa2c
> 0x16dbfa10:  16bb54d0 16bb54d0 16dbfa40 0fbf5860
> 0x16dbfa20:  00000000 6e975048 16dbfa48 0fbf58f0
> 0x16dbfa30:  16bb54d0 16bb54d0 16dbfb7c 16dbfb7c
> 0x16dbfa40:  16bb5450 1130f531 0fbe09b0 16dbfb7c
> 0x16dbfa50:  00000000 00000000 16dbfac8 16a70000
> Backtrace:
> =>0 0x6e952ef4 D3D11CoreCreateDevice+0xe0e4() in d3d11 (0x16dbfa40)
>   1 0x1130f531 EntryPoint+0xce181() in mpv-2 (0x16bb5450)
>   2 0x16bb54d0 (0x147483c0)
>   3 0x1130c240 EntryPoint+0xcae90() in mpv-2 (0x1130bbd0)
> 0x6e952ef4 d3d11+0x12ef4: movl	%eax,0x0(%edx)
> Modules:
> Module	Address			Debug info	Name (77 modules)
> PE	00400000-0086a000	Deferred        subtitleedit
> PE	009a0000-012da000	Deferred        shell32
> PE	01ba0000-01c67000	Deferred        winmm
> PE	03040000-034bc000	Deferred        mscorlib
> PE	038d0000-03b94000	Deferred        system
> PE	03ba0000-0433a000	Deferred        system.windows.forms
> PE	04340000-043c0000	Deferred        system.drawing
> PE	043c0000-043c8000	Deferred        accessibility
> PE	043d0000-0462c000	Deferred        libse
> PE	04640000-04666000	Deferred        system.configuration
> PE	0cee0000-0cef0000	Deferred        i18n
> PE	0d140000-0d250000	Deferred        system.core
> PE	0d360000-0d396000	Deferred        i18n.rare
> PE	0d3a0000-0d3ba000	Deferred        i18n.west
> PE	0d3c0000-0d3d0000	Deferred        i18n.other
> PE	0d3d0000-0d47c000	Deferred        i18n.cjk
> PE	0d480000-0d48e000	Deferred        i18n.mideast
> PE	0d4b0000-0d7be000	Deferred        system.xml
> PE	0d7c0000-0d84d000	Deferred        gdiplus
> PE	0da90000-0da92000	Deferred        usp10
> PE	0f050000-0f079000	Deferred        libvlc
> PE	10000000-103ed000	Deferred        libmono-2.0-x86
> PE	11240000-15f5d000	Export          mpv-2
> PE	61500000-6152f000	Deferred        iphlpapi
> PE	61740000-61783000	Deferred        advapi32
> PE	61f40000-61f51000	Deferred        uiautomationcore
> PE	62d40000-62ee7000	Deferred        windowscodecs
> PE	62fc0000-6304e000	Deferred        rpcrt4
> PE	63480000-6348c000	Deferred        version
> PE	637c0000-63805000	Deferred        oleacc
> PE	63bc0000-63bda000	Deferred        shcore
> PE	63e00000-63e0b000	Deferred        avrt
> PE	64a40000-64a94000	Deferred        shlwapi
> PE	64ec0000-64fec000	Deferred        oleaut32
> PE	66240000-66256000	Deferred        bcrypt
> PE	663c0000-66472000	Deferred        winspool
> PE	66740000-66751000	Deferred        rtworkq
> PE	66b00000-66b3f000	Deferred        win32u
> PE	676c0000-676e5000	Deferred        explorerframe
> PE	67c40000-67c7e000	Deferred        mscoree
> PE	68240000-682ac000	Deferred        mfplat
> PE	68500000-6855b000	Deferred        combase
> PE	68700000-68730000	Deferred        uxtheme
> PE	68cc0000-68ccb000	Deferred        avicap32
> PE	69180000-69190000	Deferred        wsock32
> PE	69940000-6996c000	Deferred        propsys
> PE	6a040000-6a062000	Deferred        msacm32
> PE	6a280000-6a32c000	Deferred        msvcrt
> PE	6a400000-6a534000	Deferred        ole32
> PE	6a740000-6a9c9000	Deferred        libvlccore
> PE	6adc0000-6ae01000	Deferred        dxgi
> PE	6bc00000-6bc2c000	Deferred        sechost
> PE	6bcc0000-6bd3f000	Deferred        setupapi
> PE	6be40000-6beba000	Deferred        dwrite
> PE	6c080000-6c08c000	Deferred        cfgmgr32
> PE	6c9c0000-6ca46000	Deferred        gdi32
> PE	6cc40000-6cd9c000	Deferred        comctl32
> PE	6d640000-6d655000	Deferred        fusion
> PE	6d780000-6d7a8000	Deferred        ws2_32
> PE	6e4c0000-6e4d6000	Deferred        dnsapi
> PE	6e940000-6e9b3000	Dwarf           d3d11
> PE	6ec40000-6ec4d000	Deferred        dwmapi
> PE	6ed00000-6eee6000	Deferred        user32
> PE	6f480000-6f48b000	Deferred        nsi
> PE	6fa80000-6fafa000	Deferred        dbghelp
> PE	70b40000-70c18000	Deferred        ucrtbase
> PE	70cc0000-70cdd000	Deferred        msftedit
> PE	70d00000-70e08000	Deferred        comdlg32
> PE	70e80000-70e8a000	Deferred        msimg32
> PE	71200000-7121c000	Deferred        imm32
> PE	71440000-716b7000	Deferred        wined3d
> PE	7a840000-7a844000	Deferred        opengl32
> PE	7ac00000-7ac85000	Deferred        riched20
> PE	7b000000-7b25f000	Deferred        kernelbase
> PE	7b600000-7b666000	Deferred        kernel32
> PE	7bc00000-7bca5000	Deferred        ntdll
> PE	f7a70000-f7a74000	Deferred        winex11
> Threads:
> process  tid      prio    name (all IDs are in hex)
> 00000038 services.exe
> 	0000003c    0     
> 	00000040    0     
> 	0000004c    0     
> 	00000094    0     
> 	000000a0    0     
> 	000000c4    0     
> 	000000dc    0     
> 	000000f4    0     
> 00000044 winedevice.exe
> 	00000048    0     
> 	00000054    0     
> 	00000058    0     
> 	0000005c    0     
> 	00000060    0     
> 	000000e8    0     
> 0000006c explorer.exe
> 	00000070    0     
> 	000000b0    0     
> 	000000bc    0     
> 00000088 winedevice.exe
> 	0000008c    0     
> 	00000098    0     
> 	0000009c    0     
> 	000000a4    0     
> 	000000a8    0     
> 	000000ac    0     
> 000000b4 plugplay.exe
> 	000000b8    0     
> 	000000c8    0     
> 	000000cc    0     
> 	000000d0    0     
> 000000d4 svchost.exe
> 	000000d8    0     
> 	000000e0    0     
> 	000000e4    0     
> 000000ec rpcss.exe
> 	000000f0    0     
> 	000000f8    0     
> 	000000fc    0     
> 	00000100    0     
> 	00000104    0     
> 	00000108    0     
> 00000110 (D) C:\Program Files\Subtitle Edit\SubtitleEdit.exe
> 	00000114    0     
> 	00000118    0     
> 	0000011c    0     
> 	00000120    0     
> 	00000124    0     
> 	00000128    0     
> 	0000012c    0     
> 	00000130    0     
> 	00000134    0     
> 	00000138    0     
> 	0000013c    0     
> 	00000148    0     
> 	0000014c    0     
> 	00000154    0 <== 
> 	00000158    0     
> 	00000164    0     
> System information:
>     Wine build: wine-7.7
>     Platform: i386
>     Version: Windows 7
>     Host system: Linux
>     Host version: 5.17.4-arch1-1

**Comment by eladkarako** [comment]
try get `mpv-2.dll` yourself and put it in the same folder as `SubtitleEdit.exe` (portable).
- x64: https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20220508-git-3458651.7z/download
- (or) x86: https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-i686-20220508-git-3458651.7z/download

<sub>(I prefer Media Player Classic HC https://github.com/mpc-hc/mpc-hc/releases/latest)</sub>
