### ISSUE TITLE
Windows data usage

### ISSUE THREAD

**Issue by hellcry37** [SubtitleEdit/subtitleedit#5934]
Just looked into windows data usage and I was stunned.

1st place SubtitleEdit.exe with 54,93 GB used data
2nd Firefox with 46,90 GB used data

I would be very curious to know why? Anybody else has this problem?

I use the latest portable version, and always used the portable version.

**Comment by hellcry37** [comment]
nothing?

**Comment by niksedk** [comment]
I don't know what / where Windows data issue is... more info + screenshots?

Video files are quite big...

**Comment by hellcry37** [comment]
I think maybe this is due the playback of videos from my nas, so maybe is LAN traffic not internet
