### ISSUE TITLE
Merge Short Lines in Batch Convert discards custom settings

### ISSUE THREAD

**Issue by maharaj12** [SubtitleEdit/subtitleedit#5936]
I tried different settings of Merge Short Lines in the Batch Convert UI and the generated file did not really merge the short lines.

Using the tool Merge Short Lines in the main UI with the same srt file did merge the short lines. 

The other possibility is that Batch Convert did not save the converted version of files,, Instead, the original version was saved.

Could you look into it?

Note: I was using version 3.6.5.

**Comment by niksedk** [comment]
Thx, the UI settings was not used - should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip
