### ISSUE TITLE
Edit > Modify Selection: Errors when using Rule: Style or Rule: Actor

### ISSUE THREAD

**Issue by pepsimaxaddict** [SubtitleEdit/subtitleedit#5939]
The issue is that Subtitle Edit produces several errors when you use the Rule: Style or Rule: Actor options.

**STEPS TO REPRODUCE**
1) Load a subtitle file with either styles or actors set for each of the subtitle
2) Click Edit  >Modify Selection
3) Change the Rule to "Actor" or "Style" then check one of the styles, and click OK. Everything is fine.
4) Now click Edit > Modify Selection. Several error messages will be displayed, but if you ignore them you can still use the 'Modify Selection' tool and it still seems to work properly.

**Contents of the error messages (all say the same):**
`An application error occurred in Subtitle Edit 3.6.4.0..

_Error Message:_

Object reference not set to an instance of an object.
_Stack Trace:_

at Nike.SubtitleEdit.Forms.ModifySelection.Preview()

at System.Windows.Forms.ListView.OnItemChecked(ItemCheckedEventArgs e)

at System.Windows.Forms.ListView.ReflectNotify(Messaage &m)

at System.Windows.FOrms.ListeView.WndProc(Message &m)

at System.Windows.Forms.NativeWindow.Callbak(IntPty hWnd, Int32 msg, intPtr wparam, IntPtr lparam)

![ste error](https://user-images.githubusercontent.com/32737416/167268533-96d206f1-a7bb-47fc-9ed9-aafc430ad244.png)
`

**Comment by niksedk** [comment]
This was fixed in SE 3.6.5 :)
