### ISSUE TITLE
[Feature suggestion] FCE new option : Convert Left & Right quotation mark into "

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#5940]
Something like this
Left & right quotation mark: 
`“ ” --> " "`
![Untitled](https://user-images.githubusercontent.com/25927091/167277914-0f095a93-b707-43e7-bec0-510f82ab6173.png)

**Comment by eladkarako** [comment]
nice idea,  
normalizing those stuff (or doing the opposite, of beautifying normal `"`),  
can be pretty helpful.  

although you can probably do a search/replace with regular expression,  
with your text-editor of your choice,  
searching for `[‘’‚‛“”„‟❛❜❝❞❟⹂〝〞〟＂]+` and replacing it with `"` .  

based on  
https://unicode-table.com/en/sets/quotation-marks/  
and  
https://op.europa.eu/en/web/eu-vocabularies/formex/physical-specifications/character-encoding/quotation-marks  


the fancy quotation marks would probably be only present in actual content,  
and not in stuff like `.ass` styles section,  
so a global search/replace should be pretty safe too.

**Comment by cyzs233** [comment]
> nice idea, normalizing that stuff (or doing the opposite, of beautifying normal `"`), can be pretty helpful.
> 
> although you can probably do a search/replace with regular expression, with your text-editor of your choice, searching for `[‘’‚‛“”„‟❛❜❝❞❟⹂〝〞〟＂]+` and replacing it with `"` .
> 
> based on https://unicode-table.com/en/sets/quotation-marks/ and https://op.europa.eu/en/web/eu-vocabularies/formex/physical-specifications/character-encoding/quotation-marks

Thank you for the links! Normalizing all kinds of quotation marks into one unified `" ` should be better.
This idea originated from OCR results, where quotation marks are constantly being inconsistently recognized.
