### ISSUE TITLE
What is "waveform multi move"?

### ISSUE THREAD

**Issue by HeikeMuc** [SubtitleEdit/subtitleedit#5943]
The update info box says "waveform multi move". What does this mean? I would like to click on a line in the waveform and move it with all the subtitles that come after it. I can do it with Shift+Ctrl+A. Is it also possible now with "waveform multi move?

**Comment by niksedk** [comment]
You could try "Set start and offset the rest"
https://www.nikse.dk/subtitleedit/help#waveform

I think "waveform multi move" is that you can move selected lines in waveform - by holding down control while move a selected subtitle in the waveform.

**Comment by HeikeMuc** [comment]
"Set start and offset the rest" is the right thing, but I would like to do it with the mouse.

**Comment by niksedk** [comment]
Try mouse left click+Ctrl+Shift
