### ISSUE TITLE
Lost effects in subtitles after translation

### ISSUE THREAD

**Issue by Aljenci** [SubtitleEdit/subtitleedit#5945]
Hello!

I am trying to translate some subtitles that have multiple effects, color, animations, etc...
For example: `{=65}{\blur0.6\bord3.42\fscx31.1\fscy31.1\pos(1026.15,934.11)\frz339.07\c&H0E0908&}Bam {the beginning... again}`

After the translation the \ is lost. In Json.DecadeJsonText it deletes the \. And all the parameters don't work.

I don't know much about subtitles formats. The decode is wrong? maybe it is getting the subtitle like Json but is not?

**Comment by niksedk** [comment]
Could you try latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by Aljenci** [comment]
Thanks for the quick response!

I just tested it and is not working.
Original: `{=65}{\blur0.6\bord3.42\fscx31.1\fscy31.1\pos(1026.15,934.11)\frz339.07\c&H0E0908&}Bam {the beginning... again}`
Result: `{=65}{blur0.6bord3.42fscx31.1fscy31.1pos(1026.15,934.11)frz339.07c&H0E0908&}Bam {el principio... otra vez}`
Result in beta: `{=65}{\blur0.6bord3.42fscx31.1fscy31.1pos(1026.15,934.11)frz339.07c&H0E0908&}Bam {el principio... otra vez}`

In beta is mantaining the first \ only.

**Comment by niksedk** [comment]
Thx :)
Hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by Aljenci** [comment]
Tested now in beta.
Working correctly! Thanks!

**Comment by niksedk** [comment]
Thx for testing :)
