### ISSUE TITLE
no support for Unicode file names in open/save dialogs in Linux version

### ISSUE THREAD

**Issue by coastal45** [SubtitleEdit/subtitleedit#5953]
It looks like this:

![Screenshot from 2022-05-15 16-07-26](https://user-images.githubusercontent.com/102390147/168497868-901ff47d-736f-476c-86e2-b522c494a40f.png)

This is a problem if I have to display multiple such files in a directory, otherwise I have to rename files somewhat to keep them straight. Is there any way to display them correctly, or some workaround for this?

**Comment by niksedk** [comment]
Sorry, that from the mono project... cannot be fixed from SE.
