### ISSUE TITLE
Compare history items

### ISSUE THREAD

**Issue by xylographe** [SubtitleEdit/subtitleedit#596]
[SE 3.4.5-399](https://github.com/SubtitleEdit/subtitleedit/commit/e4d5501)
When I try to compare history items, the compare dialogue opens, then closes immediately.
Can someone confirm/deny?

**Comment by xylographe** [comment]
It sure helps to replace `Show()` by `ShowDialog()`. :smile:

**Comment by ivandrofly** [comment]
:+1: Nice :D

**Comment by xylographe** [comment]
Resolved in commit  fdae704a9ebb15fc76d3a8b2c568545df350288e
