### ISSUE TITLE
opened text file is incomplete (truncated) if paragraph is long

### ISSUE THREAD

**Issue by voblaunsane** [SubtitleEdit/subtitleedit#5960]
heres an example, opening a text file with following contents:

```
00:00
aaaaaaaa

00:10
bbbbbbbb

00:20
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,

00:30
dddddddd
```

will only import first three paragraphs and the "00:30" will not appear. but if I shorten "00:20" paragraph, erasing the last sentence:

```
00:00
aaaaaaaa

00:10
bbbbbbbb

00:20
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

00:30
dddddddd
```

the entire file is opened.
Import -> Plain Text -> Open Text File doesn't have this issue.....

thank you.

**Comment by niksedk** [comment]
Well, it's not really a subtitle format...

**Comment by voblaunsane** [comment]
yup, fair, i just thought for a moment since it interprets the beginning of the text file, maybe it could continue doing so...
this text file i got out of free version of Otter AI transcriber.

Anyway, importing this file as plain text is not pretty either, time codes are not picked up correctly and captions are floating all over the place. Here are setting I used:
-"split at blank lines"
-"remove lines without letters"
-"generate time codes"
-"take time from current file"

If anyone else used free Otter AI for video transcription, I wrote a little script to convert these annoying plain text files to SRT, feel free to use it (just save it as html file, paste your Otter AI transcription (export as txt with "show timestamps" checked) and click convert). This script only places captions in the right place with 5 sec duration, which then can be adjusted:
```
<html lang="en-us">
<body>
<textarea id="textOtterAI" style="display:block;width:100%;height:45%" rows="10"></textarea>
<button onclick="convert()">convert</button>
<button onclick="reset()">clear</button>
<textarea id="textSRT" style="display:block;width:100%;height:45%" rows="50"></textarea>
<script>

function isTimeCode(timeCode) 
{
	var result = false
	var m;
	var re = /^\d{1,2}(\:\d{1,2})/;

	if (m = timeCode.match(re))
	{
		result = (m[0].length === 4 ? "0" : "") + m[0];
	}

	return result;
}

function add5Secs(timeCode)
{
	// convert timecode to seconds
	var d = (Number(timeCode[0]) * 10 + Number(timeCode[1])) * 60 + Number(timeCode[3]) * 10 + Number(timeCode[4]);

	//add 5 secs;
	d += 5;

	// convert seconds back to timecode
	var d = Number(d);
	var m = Math.floor(d / 60);
		m = m < 10 ? "0" + m : m;
	var s = Math.floor(d % 60);
		s = s < 10 ? "0" + s : s;

	return m + ":" + s ;
}

function reset()
{
	document.getElementById("textOtterAI").value = "";
	document.getElementById("textSRT").value = "";
}

function convert()
{
	var lines = document.getElementById("textOtterAI").value.split('\n');
	var count = 0;

	document.getElementById("textSRT").value = "";

	for(var i = 0; i < lines.length; i++)
	{
		var time = "";

		if (timeCode = isTimeCode(lines[i]))
		{
			count++;

			document.getElementById("textSRT").value += 
				count + "\r\n" +
				"00:" + timeCode +
				",000 ---> 00:" + add5Secs(timeCode) + ",000\r\n";
		}
		else
		{
		document.getElementById("textSRT").value += lines[i] + "\r\n";
		}
	}
}
</script>
</body>
</html>
```

**Comment by niksedk** [comment]
Does Otter AI transcriber have a more structured format - like in json or xml?

**Comment by voblaunsane** [comment]
paid version has SRT; free version has 30 min duration limit and TXT exports with time code option (as above). while it recognises words pretty darn well (I tried transcribing Italian person speaking English), punctuation is not there, but also pauses are not recognised well, which means lots of captions get mashed together. Splitting required. Subtitle Edit is irreplaceable here, thank you, it's a fantastic app :)

**Comment by uckthis** [comment]
Descript is better than Otter. 3 hours free transcription. After 3 hours, make a new account with fake email. Adobe Premier is very good too: almost as accurate as  Descript.

**Comment by niksedk** [comment]
SE has audio to text too: Go to Video - Audio to text... even has batch: https://github.com/SubtitleEdit/subtitleedit/discussions/5954

What format does `Descript` save in?

**Comment by uckthis** [comment]
Yes, I know but Descript is very fast. An hour can be transcribed in 8-10 minutes. Same with Adobe Premiere, though I have a relatively good computer and GPU. 

I never save from Descript. I just copy/paste the transcript in InqScribe and then import text in SE after fixing.

**Comment by voblaunsane** [comment]
> Descript is better than Otter. 3 hours free transcription. After 3 hours, make a new account with fake email. Adobe Premier is very good too: almost as accurate as Descript.

thanks, awesome advice, will have to try this out!



> SE has audio to text too: Go to Video - Audio to text... even has batch: #5954

SE is fire!
