### ISSUE TITLE
Translation mode: Column position doesn't update

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#5961]
Please see the GIF below. I always prefer putting Text column to the right, and SE remembers that. However, it doesn't update each time until resizing something:
![demo](https://user-images.githubusercontent.com/494788/169181973-a1a53f5a-a681-48e9-a76f-6ad48d6b8e6a.gif)

**Comment by niksedk** [comment]
Thx @LeonCheung :)

How is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Ah, nice fix! Thanks a lot! Closing.
