### ISSUE TITLE
Option for defining "non-word" characters when jumping accross words ctrl + left/right in the edit box

### ISSUE THREAD

**Issue by pavhofman** [SubtitleEdit/subtitleedit#5966]
Some subtitles have HTML tags, but the < > and some punctuation characters are not defined as non-word chars. As a result editing the text with ctrl+left/right arrows is quite tedious (typically when editing word endings in languages with declinations), because the caret jumps over the word and the final fullstop, or the subsequent/preceeding HTML mark (typically `<i>`). However, char specs wrapped in {} are regarded as non-word chars correctly and the caret stops before them.

Some editors consider fullstop as part of word when jumping forward, OK. But IMO a HTML tag should not be considered as part of a word in any jump direction.

Thanks a lot for considering any solution.

**Comment by niksedk** [comment]
You can enable the "use syntax coloring":
![image](https://user-images.githubusercontent.com/1261331/169373343-28efdf37-6c86-4b33-9219-2d51562201cb.png)


This uses a "rich text box" which is more advanced than the default text box.

**Comment by pavhofman** [comment]
Works perfectly, thank a lot!
