### ISSUE TITLE
"Merge sentences" not working

### ISSUE THREAD

**Issue by Alessa19** [SubtitleEdit/subtitleedit#5969]
I like using "Merge sentences" to merge sentences into one when they are split up into different lines.
However, "Merge sentences" doesn't seem to catch them all. Some of the sentences are merged, while others are left as it is.
For example, if a line ends in a comma and the sentence continues into the next line, it won't combine it into one sentence.

**Comment by niksedk** [comment]
Could you provide some example files?

**Comment by Alessa19** [comment]
Here's an example. I think that maybe if some time has passed between the lines that are one sentence, "Merge sentences" won't join them.

1
00:02:12,080 --> 00:02:13,960
This is a test.

2
00:02:50,400 --> 00:02:51,960
This is supposed to be

3
00:02:52,160 --> 00:02:53,200
a test.

4
00:03:16,400 --> 00:03:17,560
This is supposedly,

5
00:03:17,700 --> 00:03:21,760
a test.

6
00:03:25,140 --> 00:03:26,740
Actually,

7
00:03:27,220 --> 00:03:29,860
this is a test.

8
00:06:31,100 --> 00:06:32,580
I thought,

9
00:06:33,300 --> 00:06:35,620
it was supposed to be a test?

10
00:12:42,100 --> 00:12:43,900
I mean, this is

11
00:12:44,300 --> 00:12:45,500
a test, right?

**Comment by niksedk** [comment]
You can up the value of "Maximum milliseconds between lines":

![image](https://user-images.githubusercontent.com/1261331/169641090-89a268b3-889f-462b-a44f-eb7c87a45054.png)

**Comment by Alessa19** [comment]
That seems to do the trick. Now when I press "Merge sentences", they're merged.
