### ISSUE TITLE
Reversing mouse wheel scroll direction...

### ISSUE THREAD

**Issue by voblaunsane** [SubtitleEdit/subtitleedit#5970]
Options > Settings > Waveform/spectrogram > Reverse mouse wheel scroll direction

checkbox reverses waveform scrolling direction, which is great. At the same time this checkbox could also reverse video seek control scroll direction, which is located under the waveform...

thanks

**Comment by niksedk** [comment]
Thx :)

How does this work? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by voblaunsane** [comment]
hi, sorry for late reply.

seek control scrolling reversed just fine, but it lost ability to control waveform either direction. clicking on seek bar doesnt effect waveform position either..
