### ISSUE TITLE
BD SUP editor: Greater precision in 'Adjust brightness' option

### ISSUE THREAD

**Issue by manuelrn** [SubtitleEdit/subtitleedit#5974]
Hello,

Would it be possible to have more precision in the 'Adjust brightness' option of the BD SUP editor?
Currently only integers can be specified, it would be great if you could enter a number with 2 decimal places for example.

I mean for example to do the following: The slider would still work the same as it does now (adjusts integers numbers with decimals set to 0), but the X% value (e.g. 100.00%) would be an editable field so the user could click on the value and type in any value the user wants, including decimals.

Thanks and regards!

**Comment by manuelrn** [comment]
Thank you very much @niksedk!
As always, very attentive and very fast.

I will test it when the Beta is updated with these new changes.

Thank you again for your great dedication ;)

**Comment by niksedk** [comment]
You're welcome, and beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.5/SubtitleEditBeta.zip

**Comment by manuelrn** [comment]
I just tried it and it works great, thanks again @niksedk!

As a note, it would be great if in the future Subtitle Edit would support batch subtitle editing.
I mean having something similar to what already exists with command line conversion.

For example, this would be an example of the current command line conversion:
```SubtitleEdit /convert *.mp4 SubRip /encoding:utf-8```

And this would be an example (or something similar to this) to what I comment:
```SubtitleEdit /edit *.sup /brightness:70,25```

It would be very useful to be able to edit all the subtitles at once instead of doing it manually one by one.

If you wish, I can open another new Issue with this suggestion.
Thanks again and regards!
