### ISSUE TITLE
Shortcut needed for "Merge with line before"

### ISSUE THREAD

**Issue by coastal45** [SubtitleEdit/subtitleedit#5975]
After running Audio/video to text function, there are cases where a single spoken line is split into two or more subtitle lines. There is no significant spacing between them, so it doesn't seem to be a spacing issue.
It's Japanese language in my case, though this might apply to other languages too.

![Screenshot from 2022-05-21 21-54-02](https://user-images.githubusercontent.com/102390147/169710215-508c7364-59f6-4d46-8647-ce2359bfcf73.png)

This only occurs intermittently, so it's not a big enough problem to require some program change.
By running the video, I can easily stop on the last segment of such a pair. Then it is easy to fix using "Merge with line before" from the context menu.
However, this is cumbersome to do repeatedly, so I would like to request a shortcut for "Merge with line before", for easier line merging.

Also there is a line break inserted between such merged segments.

![Screenshot from 2022-05-21 21-55-26](https://user-images.githubusercontent.com/102390147/169710270-98cfb808-534a-4cc1-97dc-48be5efa666d.png)

I don't know if there is a reason for this, but in my case it's a problem. Is it possible to add an option or remove that?

**Comment by niksedk** [comment]
The shortcut is already there :)

![image](https://user-images.githubusercontent.com/1261331/169712590-27de8791-293c-4646-acdc-105fe20e9b9a.png)

**Comment by coastal45** [comment]
Sorry, I haven't modified shortcuts before, and should have looked closer.
As for the line break issue, can it be modified somehow? Should I make it a separate issue?

**Comment by coastal45** [comment]
Never mind, I see that shortcut now.

**Comment by coastal45** [comment]
The problem I reported in Issue #5975 is occurring more often when using the vosk Japanese big model, maybe once every few minutes or more. Rather than using the shortcut to join them so many times, would it be possible to add a function to join all such occurrences in one file? In these, the end time of the first line is the same as the start time of the second line. At least this would resolve the immediate difficulty.

**Comment by niksedk** [comment]
> The problem I reported in Issue #5975 is occurring more often when using the vosk Japanese big model (vosk-model-ja-0.22), maybe once every few minutes or more. Rather than using the shortcut to join them so many times, would it be possible to add a function to join all such occurrences in one file? In these, the end time of the first line is the same as the start time of the second line. At least this would resolve the immediate difficulty.

Could you give some examples of texts that should be merged - SE only allows 13 chars per subtitle - see https://github.com/SubtitleEdit/subtitleedit/blob/master/src/libse/AudioToText/AudioToTextPostProcessor.cs#L129

**Comment by coastal45** [comment]
Attached is a short clip. You can see where joining would be needed in lines 4-5, 10-11, 16-17 and 22-23. It appears to be a 12 char. limit issue as you mention.
Is there a specific reason for the character limitation? And if there is no way to increase it, could a separate operation exist where SE just parses an srt file and joins any pair where the end-next start times are the same?
[clip.zip](https://github.com/SubtitleEdit/subtitleedit/files/9164458/clip.zip)

**Comment by coastal45** [comment]
I'd like to restate my issue here. Giving a current example, an entire spoken phrase is split midstream. 
Expecting that the vosk model does not do any grammar or such phrase checking, these four should be contained in one subtitle line. So what is deciding the break points?
Subtitles extracted as they are now are basically useless, as too much manual editing would be needed.

![Screenshot from 2022-07-18 13-49-37](https://user-images.githubusercontent.com/102390147/181687623-64bb56c6-a2ab-42b1-a7fd-be5e2e635fd8.png)

Also, separated が can't be explained by char limit.

I don't understand the reason of 13 char. limit. Is it a vosk or SE post-processing issue?
I can write a much longer line without any problem.
If it's a vosk issue, I can ask them, if I can understand the interactions between vosk and SE.

![Screenshot from 2022-07-28 22-18-44](https://user-images.githubusercontent.com/102390147/181687943-70056a39-e137-4fc7-b2ec-86382864bb00.png)
English audio to text doesn't have such a char. limitation:

![Screenshot from 2022-07-28 22-35-15](https://user-images.githubusercontent.com/102390147/181690110-22426755-8dd9-4d84-a7d7-306870be8345.png)

**Comment by niksedk** [comment]
The 13 chars per sub is a SE issue - I took 13 chars from here: https://partnerhelp.netflixstudios.com/hc/en-us/articles/215767517-Japanese-Timed-Text-Style-Guide

**Comment by coastal45** [comment]
Understood. I think in horiz. text the Netflix 13 char limit is somewhat severe or a Netflix issue. Also could be to support various display formats.

I checked a couple of jp commercially subbed dvds, it looks like 52 max. char (26 x 2 lines) is reasonable.

In extracting jp text from the audio, I think getting the complete phrase on one srt line, with surrounding timing, is necessary first.
Also, having a line break within the line is troublesome. Can two line text be displayed without it?

So my idea is one srt numbered line per spoken phrase, timed at start and end of speech. Max. length of 52 max. full-width characters.
OK to split into two lines if line break is not used. Actually, I think the line break can't be added out of context. It's not like with western language words.

Something like this:

![Screenshot from 2022-07-29 15-31-27](https://user-images.githubusercontent.com/102390147/181870593-2725ec19-ef95-4c65-a008-31d99ff5f5cc.png)

**Comment by niksedk** [comment]
OK, default jp max chars per subtitle is now `32` - but you can try different values be editing Settings.xml and change the value `AudioToTextLineMaxCharsJp`.
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by coastal45** [comment]
Thanks so much. This makes for a cleaner format/timing, and text comprehension is a lot better.

I have noticed that on some lines the first spoken phoneme (or two) are not in the returned text. Can't tell if that's some timing issue or vosk just didn't pick it up. In previous versions, that might be why the text when combining partial segments was not so understandable.
But it's manageable now.

And I think 32 char max. is fine.

**Comment by coastal45** [comment]
Regarding the issue mentioned above (missing first part of text line), I'll add an example here.
If you listen and check the waveform and text around line 7, you can see the waveform and hear "wakanaideshou".
However, in the return text, you only get back "でしょ" (deshou). So first part is clearly missing.
This seems to occur in about one line every 5 minutes, so it seems rather common issue.

I don't know the mechanism that transfers the audio to vosk, or vosk returned text to SE, but I wonder if some clipping is is involved. Maybe a timing or delay issue?
Is there any way to investigate this from SE point of view?
[clip audio.zip](https://github.com/SubtitleEdit/subtitleedit/files/9391320/clip.audio.zip)
