### ISSUE TITLE
[Feature Request] - CLI change output filename

### ISSUE THREAD

**Issue by BenJamesAndo** [SubtitleEdit/subtitleedit#5981]
Currently the CLI lets you specify an output folder. I'd also like to be able to specify a new file name for the converted file.
Something like this
`SubtitleEdit.exe /convert test.srt ScenaristClosedCaptionsDropFrame /renamefile test-done.scc`

Something like that would effectively convert test.srt to test-done.scc

If this is already possible, please let me know. If not please consider adding this feature to the CLI.
Thanks!

**Comment by BenJamesAndo** [comment]
@niksedk Wow, thanks for the quick reply and implementation on this.
It mostly works, except it doesn't handle renaming with the file extension properly.

If I do `SubtitleEdit /convert "C:\tmp\Test.srt" ScenaristClosedCaptionsDropFrame /outputfilename:"New_Name"` then it outputs a file called` New_Name` with no .scc ext
If I instead do `/outputfilename:"New_Name.scc"` it outputs `New_Name.scc.scc`

Ideally I'd like to run it and if I don't specify a file ext then it'd insert the correct file ext. And if I do specify the file ext then have it not insert it twice.

Another observation is that if the filename already exists, it inserts a bunch of numbers and letters. E.g. if I run that second example a second time then it outputs `New_Name.scc.6a42bc61-8c25-4d50-8047-cfbef0f9624d.scc`
Could be good if the random unique name was shorter, e.g. .1, .2, .3 etc.
And a bonus feature would being able to specify whether I want a unique name or to overwrite the existing file.

**Comment by niksedk** [comment]
@BenJamesAndo: thx for testing and feedback :)

Now `subtitleedit /convert a.srt srt /outputfilename:myfile.srt` will output the following if the file already exists:
`1: a.srt -> C:\git\subtitleedit\src\ui\bin\Debug\myfile_2.srt... done.`

If not really sure if auto extension is a good idea - it's easy, but then you cannot override ext to something else, like `.txt`...

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by BenJamesAndo** [comment]
@niksedk I've had a good test and it's all working perfectly now!
I appreciate you adding this feature, it'll be very helpful for me.

I didn't know about `/overwrite` thanks for pointing that out.

**Comment by sapphire-bt** [comment]
This works when converting from `.srt` to other formats but doesn't seem to work the other way around.

When I run:

```
SubtitleEdit /convert a.sup srt /outputfilename:b.srt
```

The output file is `a.srt`.
