### ISSUE TITLE
Is it possible to add OCR from google API?

### ISSUE THREAD

**Issue by Kuju29** [SubtitleEdit/subtitleedit#5982]
I found that Tesseract doesn't work with Thai language.
![image](https://user-images.githubusercontent.com/22098092/170431472-08dfb806-6142-40c2-8994-b48d79f87fef.png)

There are 3 methods I use to solve this problem.
1. Type it yourself and use Binary image compare.
2. Use the script from [https://github.com/Abu3safeer/image-ocr-google-docs-srt](https://github.com/Abu3safeer/image-ocr-google-docs-srt)
3. Use abbyy finereader program.

So I'm wondering if it's possible for you to get users to add APIs in a similar fashion to Method 2.

**Comment by niksedk** [comment]
Fix via https://github.com/SubtitleEdit/subtitleedit/pull/6195
