### ISSUE TITLE
Some BATCH-Convert issues [bleep], and more.

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#5987]
Hi!

#1: What's the solution for when there are [bleep] one don't want to have removed, especially when one's doing BATCH-Convert of several Subs ?!

Else the Remove Text for Hearing Impaired will remove the BLEEP.

When I have individual Subs I just search for [bleep] and then do a Replace to make them =BLEEP= instead, but is that possible when doing a BATCH-Convert?
(It's in Expedition Unknown that Josh always curse...)

It's a pretty common problem that [bleep] are removed, so there should be a Permanent way to NOT Remove Certain Words within [word].

#2: Also (NOT Related to the other problem here above!), when BATCH-Converting, I would like to Add a Line with only a _ (UnderScore) Very First in the Sub, with the Lenght of 0,001 second, and Start at 00:00:00,001 second.
Is that possible to Automate in Batch?

#3: Is there a way to Auto-Fix when the continuing Sentence (on the next line) starts with a CAPITAL Letter, as in the sentence below ?!

2
00:00:01,102 --> 00:00:03,502
So potentially,
there is a nazi tunnel

3
00:00:03,504 --> 00:00:05,604
In a volcano
in the middle of this town.

The word 'In' shouldn't have an 'I' but an 'i'.

/Thanx!

**Comment by DrReddP** [comment]
For the first one, I use "multiple replace" in batch first. I'll run everything through replacing [bleep] with bleep, then I will run the batch removing HI, then I will do multiple replace again to put the brackets back.
