### ISSUE TITLE
[Feature Request] Manual speech recognition

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#5988]
I want to use it just on my select lines. Line by line. With manually selected area.
Cause you can't get a correct result with the wrong line break.

**Comment by niksedk** [comment]
Could could you explain a bit more? 
Do you mean dictation with your own voice?

**Comment by Mishasama** [comment]
This is the working procedure I envisioned:
1. Manually divide the period for each sentence/line of subtitles with reference to the waveform
2. Choose different languages for different rows
3. Use speech recognition to generate subtitle content.

This will avoid inappropriate line breaks. And it is more helpful to improve the accuracy of automatic translation.
It also solves the problem of recognizing multiple languages in a single video.



There is another case.
YouTube's speech recognition engine is more accurate, but it often results in recognition errors due to sentence breaking errors (this is often the case for non-Latin native languages, such as Asian languages).
So, I don't need to have speech recognition for the whole video. I just need to adjust the broken segment and recognize it once to fix it.

**Comment by coastal45** [comment]
Related to the incorrect line breaks issue, as I described in Issue #5975, I think it would be important to understand the source of the line breaks, rather than trying to time around them. That might result in a better solution.

**Comment by Mishasama** [comment]
> Related to the incorrect line breaks issue, as I described in Issue #5975, I think it would be important to understand the source of the line breaks, rather than trying to time around them. That might result in a better solution.

There's the STT engine problem. It even happens on Google's STT engine.
So I think there is nothing SubtitleEdit can deal with this.
The best solution for now is manually set the period. Force it to be recognized as a whole sentence.

**Comment by coastal45** [comment]
But still, wouldn't it be possible for SE to (perhaps optionally) join any two segments automatically when there is less than say .5 seconds between them? Basically just taking over the manual joining process. In my experience, these segments are back to back.

**Comment by cyzs233** [comment]
LeonCheung actually had already requested his feature #1968.
After 6 years, the main part of this feature request "Speech Recognition" has been implemented via vosk. The remaining peice is Subtitleeit needs to add some toolkit that can split the audio track into chunks (based on timestamp from each subtitle line) and be able to feed these chunks into vosk separately. 
Basically, it means to achieve "Perform ASR on selected line".
![Untitled](https://user-images.githubusercontent.com/25927091/180008753-cf4d6d32-b123-4e8f-871e-e712dfcf0ab6.png)

But, in the end, it is left to niksedk to decide whether this feature is worth implementing or not. 
We still can't "Perform OCR on selected image", I won't put much hope on this one either.

**Comment by niksedk** [comment]
How is this?
![image](https://user-images.githubusercontent.com/1261331/180837051-0149f7e4-186e-4c59-ba17-7a8adb32abcd.png)


https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by Mishasama** [comment]
> How is this? ![image](https://user-images.githubusercontent.com/1261331/180837051-0149f7e4-186e-4c59-ba17-7a8adb32abcd.png)
> 
> https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

The function does not work. It can't replace the text. It only displays the translated text on the line. But when you click another line, it will revert to the old text. The text box also has not changed.


![image](https://user-images.githubusercontent.com/54498172/181167148-c42baa84-7a19-4d86-9c18-c86141c7b090.png)
And not support dark mode.

**Comment by niksedk** [comment]
@Mishasama; thx for testing :)
Beta updated - better now?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by Mishasama** [comment]
> @Mishasama; thx for testing :) Beta updated - better now? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

Problem: It does not support Undo & Redo.

----
![image](https://user-images.githubusercontent.com/54498172/181654973-ee17466e-9d7f-42a9-ba2c-7557432deb62.png)
And it looks different than other menus.

----
This is another bug just found it.
![image](https://user-images.githubusercontent.com/54498172/181652855-3d20fbf1-0cf6-4b65-bde8-87127e6b7c08.png)
When the dark theme was deactivated, open this setting page, all related settings were still activated.
It should be like this.
![image](https://user-images.githubusercontent.com/54498172/181653909-f46ab419-c9a3-4637-831d-1f5a61dfc670.png)

----
And it's weird why changing the light theme to the dark theme can be done without restart, but not the other way around.

**Comment by niksedk** [comment]
@Mishasama: thx, undo now added: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by Mishasama** [comment]
> @Mishasama: thx, undo now added: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

Uh, what about redo...
In history, it still empties.
![image](https://user-images.githubusercontent.com/54498172/181908122-62e7072f-7a74-47b6-9526-6cefd3293841.png)

**Comment by niksedk** [comment]
Hm, it works fine here...

**Comment by Mishasama** [comment]
> Hm, it works fine here...

Try to click Rollback.

**Comment by niksedk** [comment]
> > Hm, it works fine here...
> 
> Try to click Rollback.

He, "Rollback" has always worked like that... but I've tried to make it more logical here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by patarapolw** [comment]
So far, I can make Audio-to-Text work on selected time segment, by creating 1 new line. However, it doesn't break to multiple lines (even if it is like 1 minute or so). If to create multiple blank lines in advance, I don't know how many lines to make.
