### ISSUE TITLE
Application Error 

### ISSUE THREAD

**Issue by ReallyInventiveUserName** [SubtitleEdit/subtitleedit#5989]
I received an application error while trying to use "fix common errors" so I took a screenshot of what it said.
This is the first issue I've ever encountered with _**SE**_ and I've used the software for years.. Thanks for all that you do I love the software.. 
![Error message](https://user-images.githubusercontent.com/22139153/170806372-e87f848f-4dc3-4dba-97f0-937f8edaf755.JPG)

**Comment by niksedk** [comment]
Thx for the issue - could you attach or email the subtitle file?

**Comment by niksedk** [comment]
OK, I hope the crash is fixed in this new beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
