### ISSUE TITLE
How to batch convert single subtitle out of many in the mkv file?

### ISSUE THREAD

**Issue by vsrawat** [SubtitleEdit/subtitleedit#5994]
Say, a season has 10 mkv files, and each file has 18 subtitles in different languages, including more than one subtitle for some of the languages.

I want to extract only those in one language, say English, plus say where vlc player says SDH [English]. All other languages' tracks have no meaning for me. The program extracts all of them giving some 180 files, and it is a problem to keep the ones I need and delete other as they all have same starting names and mkv file also has same name.

How to batch convert single subtitle track out of many in the mkv file?

could you add a filter option to accomplish that in batch conversion?

Thanks.

**Comment by niksedk** [comment]
Does this work for you?

![image](https://user-images.githubusercontent.com/1261331/170839663-7912b0f4-42d1-4796-b747-0804a033ece0.png)

**Comment by niksedk** [comment]
You can also determine if language code (and how) should be included in file name:

![image](https://user-images.githubusercontent.com/1261331/170839717-810fe09b-6e89-418f-a3db-c4eef2dacf3c.png)

**Comment by vsrawat** [comment]
> Does this work for you?
> 
> ![image](https://user-images.githubusercontent.com/1261331/170839663-7912b0f4-42d1-4796-b747-0804a033ece0.png)

oh, here that was. yeah, that is what I was suggesting. Now I have to figure out where to find language code in vlc. Any tips.

Thanks for the prompt reply and solutions.

**Comment by vsrawat** [comment]
> > Does this work for you?
> > ![image](https://user-images.githubusercontent.com/1261331/170839663-7912b0f4-42d1-4796-b747-0804a033ece0.png)
> 
> oh, here that was. yeah, that is what I was suggesting. Now I have to figure out where to find language code in vlc. Any tips.
> 
> Thanks for the prompt reply and solutions.

**Comment by vsrawat** [comment]
> > > Does this work for you?
> > > ![image](https://user-images.githubusercontent.com/1261331/170839663-7912b0f4-42d1-4796-b747-0804a033ece0.png)
> > 
> > 
> > oh, here that was. yeah, that is what I was suggesting. Now I have to figure out where to find language code in vlc. Any tips.
> > Thanks for the prompt reply and solutions.

It is already naming the file with the original file name plus some method of language name, so that helps me to make out what is what. Good enough.

I will experiment with this language naming system to figure out how it improves.

Thanks.
