### ISSUE TITLE
[Feature Request] Embed Soft Subtitles 

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#5995]
It would be awesome to be able to use Subtitle Edit to embed (soft subtitles) one or multiple subtitles to a video. :) 
I normally use MKVToolnix to do this but would love to only use Subtitle Edit in my workflow. 
- Support adding multiple subtitles
- Selecting language
- Enabling default sub, etc

Image taken from MKVToolnix. 
![embed subtitles](https://user-images.githubusercontent.com/92556454/170842707-ccda43a2-0fe3-4275-958d-25e1a7c8a3f2.PNG)

Thanks!

**Comment by eladkarako** [comment]
it is also super fast (no encoding),  
  
<details><summary>and can be done with just ffmpeg (which is already present)</summary>

```txt
ffmpeg -y -loglevel "repeat+info" 
-i "file:my_input_video.mkv" 
-i "file:subtitle.en.vtt" 
-i "file:subtitle.iw.vtt" 
-i "file:subtitle.ja.vtt" 
-i "file:subtitle.ko.vtt" 
-map 0 
-c copy 
-dn -ignore_unknown -map "-0:s" 
-map "1:0" "-metadata:s:s:0" "language=eng" "-metadata:s:s:0" "handler_name=English"  "-metadata:s:s:0" "title=English" 
-map "2:0" "-metadata:s:s:1" "language=heb" "-metadata:s:s:1" "handler_name=Hebrew"   "-metadata:s:s:1" "title=Hebrew" 
-map "3:0" "-metadata:s:s:2" "language=jpn" "-metadata:s:s:2" "handler_name=Japanese" "-metadata:s:s:2" "title=Japanese" 
-map "4:0" "-metadata:s:s:3" "language=kor" "-metadata:s:s:3" "handler_name=Korean"   "-metadata:s:s:3" "title=Korean" 
-movflags "+faststart" 
"file:my_output_video.mkv"

```
optional: `-disposition:s:s:5 forced` to set 4th subtitle as the default one.

<hr/>

</details>

<details><summary>although, in some cases you would also need to embed few fonts as well as subtitles..</summary>

<img width="527" alt="2022-05-30_190005" src="https://user-images.githubusercontent.com/415238/171028548-28a1565e-ed05-4b00-8a64-e211ea895d47.png">

although if you choose to skip it a fallback font will be used,  
which in 99% of the cases is perfectly fine as well.
 
</details>
