### ISSUE TITLE
Exception bad index

### ISSUE THREAD

**Issue by loicvan** [SubtitleEdit/subtitleedit#5996]
when a line ends in : and RemoveHITtext is run and exception is thrown. the comparison is wrong, should be -1 not  + 1

diff --git src/libse/Forms/RemoveTextForHI.cs src/libse/Forms/RemoveTextForHI.cs
index 985604933..238a0f312 100644
--- src/libse/Forms/RemoveTextForHI.cs
+++ src/libse/Forms/RemoveTextForHI.cs
@@ -367,7 +367,7 @@ namespace Nikse.SubtitleEdit.Core.Forms
                                     string s = line;

                                     var skipDoToNumbers =
-                                        indexOfColon < line.Length + 1 &&
+                                        indexOfColon < line.Length - 1 &&
                                         char.IsDigit(line[indexOfColon - 1]) &&
                                         char.IsDigit(line[indexOfColon + 1]);

**Comment by niksedk** [comment]
Fixed in https://github.com/SubtitleEdit/subtitleedit/commit/653e180d9baaa66214f55d3ae2754035a18ffc12
