### ISSUE TITLE
Export formatting ONLY

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5998]
Hello,
I don't know if there is an option to do it, but here's what I want. I have two files, one English and other French. French file has styling like italics and positioning. English file does not. Their timecodes match exactly. What I want to do is export formatting only. So only the position info and possibly the italics as well; which I can later join/merge the file, etc. Ideas?
Is there a tag for custom exports to export styling only?

Thank you.

**Comment by niksedk** [comment]
Hm, does the plugin "Load formatting from other subtitle" work for you?
(I think it requires the same number of lines)

**Comment by uckthis** [comment]
Yes, it worked. It's a new plugin or I'd have known about it.

**Comment by niksedk** [comment]
He yes, it's new :)
