### ISSUE TITLE
Spell check sudden error

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#6006]
Hello. I just tried to activate the live spell check when this happened:
![image](https://user-images.githubusercontent.com/37704802/171603187-0b2ece92-0b5f-4db8-840a-78a3d9870fb7.png)

**Comment by niksedk** [comment]
Any hints on how to re-create this?

**Comment by lambdacore12** [comment]
I used spell check on another random subtitle and it did the same error. I also noticed that the text in the listbox moved to Gap.
![image](https://user-images.githubusercontent.com/37704802/174475323-edb98435-8e20-4592-a22d-9684b2f292ab.png)

**Comment by niksedk** [comment]
Yes, the columns looks a bit weird... I cannot re-create this... could you attach your `Settings.xml` file?
Also, do you do something before the spell check?

**Comment by lambdacore12** [comment]
I am working normally, nothing special. Where can I find the settings.xml file?

**Comment by niksedk** [comment]
Press `Ctrl+Alt+Shift+d` - will open the SE `data` folder...

**Comment by lambdacore12** [comment]
OK. Got it.
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/8935701/Settings.zip)

**Comment by niksedk** [comment]
Hm, it does still not crash here... is it only some subtitle files? What OS are you using?

**Comment by lambdacore12** [comment]
I am using windows 11. I just downloaded a random srt file on the net and it crashed again.

**Comment by niksedk** [comment]
OK, I cannot re-create this on Windows 10 - tried with 10+ different subs.
Could be a Win 11 issue.

**Comment by lambdacore12** [comment]
Well, thanks anyway. I'll let you know if it's fixed.

**Comment by niksedk** [comment]
I've installed Windows 11... but it's still working here...

**Comment by lambdacore12** [comment]
I don't really know how to respond to that. Maybe it's the processor? Maybe it's .NET FRAMEWORK ? I really can't tell since I am only a beginner in programming...

**Comment by niksedk** [comment]
I cannot fix this as I cannot re-create the issue. 
If you ever find out what causes this, do let me know :)

**Comment by lambdacore12** [comment]
OK. You got it.
