### ISSUE TITLE
ASS size

### ISSUE THREAD

**Issue by satstarter** [SubtitleEdit/subtitleedit#6010]
is it me or is it a bug?
text size ass subtitles in 1 file set to 50 is ok
but when i set it in bulkconversie also on 50 they are very huge?

**Comment by niksedk** [comment]
The size of text in ASSA files depend on `PlayResX` and `PlayResY`.
If `PlayResX` and `PlayResY` are not defined, then subtitles will be scaled (up) from the default ASSA resolution which is 384x288 (very very low), so do set the resolution...

**Comment by satstarter** [comment]
Thank you for your reply
but i dont understant it i think because when i set in bulkconversion the resolution to 1280 x 720
letterzise 21 is good but when i do this in a single file so no bulkconversion 21 is very smal then i must
set it to 53 to get about the same size also in single file the scale Y and R is default 100,0
by the way also the side and shadow defines are diferent 1.5 side and 0.9 shadow gives me more black sides in bulk
then in single file
maybe its me ? but thanks annyway ;)

**Comment by niksedk** [comment]
You should probably attach a few screenshots and sub files...

I just tried to Tools - Batch convert... and it worked fine for me:
![image](https://user-images.githubusercontent.com/1261331/172133062-c79c3334-6da5-4f60-9c7e-bb3fac46b99e.png)

**Comment by satstarter** [comment]
my bad sorry and thanks again for your reply
the problem was the example screen that gives me a huge textzise in bulk but not in the single file
and that was what confused me but after converting the sizes are the same in bul as in single
ps thanks for this great software ;)
