### ISSUE TITLE
Capture top align not working

### ISSUE THREAD

**Issue by tormento** [SubtitleEdit/subtitleedit#6011]
I have found a specific sup file that skips the top align {\an8} insertion, [this](https://krakenfiles.com/view/J9KMhI7PZP/file.html).

I don't know if it's the quotation marks or what else.

**Comment by niksedk** [comment]
Thx for the info + file :)

Should be fixed in latest beta now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
