### ISSUE TITLE
Separate Top align and bottom align

### ISSUE THREAD

**Issue by tormento** [SubtitleEdit/subtitleedit#6013]
There are some sup where there is top aligned text along with bottom aligned text.

Usually SE simply joins them in a multiple line bottom text.

Would be possible to simply "split the screen in half" and put {\an8} and normal text on different number lines, duplicating their time?

That would simplify subsequent manual editing A LOT!

Attached is a sample
[tears [ita].zip](https://github.com/SubtitleEdit/subtitleedit/files/8843238/tears.ita.zip)

**Comment by Ninelpienel** [comment]
I have the same problem.
![Image456](https://user-images.githubusercontent.com/1890524/175900412-54065f6a-0a19-4a4e-8dd1-de56eb897063.png)
Output: `Da da da da da da, Dada-Planet,
Nie gehört.`

**Comment by Eniff** [comment]
I have the same problem as well, top align correctly recognises text at the top when it is the only place a subtitle is shown but it joins them together when there are subtitles both at the top and at the bottom.
When top and bottom subtitles are overlapping but the bottom subtitle changes during the overlap it creates a very distracting effect where the top subtitles will constanly reposition from top to bottom and vice versa.
Sometimes it even misses the break even though there is a large vertical gap between the differently aligned subtitles and that makes it a lot harder to follow the script.
Is there an easy way to correct this behaviour post OCR?
![Screenshot (91)](https://user-images.githubusercontent.com/60354139/193263425-c74f8832-e590-43ad-bc92-638dacbb4950.png)
![Screenshot (92)](https://user-images.githubusercontent.com/60354139/193263895-86e38935-06aa-4c35-b2ca-80754b954981.png)

**Comment by FrequencyLost** [comment]
![Image726](https://user-images.githubusercontent.com/28737028/208263055-4757b8a6-c968-4e6e-ad28-89ded847113f.png)

Having the same issue as the others. When theres subtitles aligned at both the top and bottom of the screen, they get merged and positioning gets messed up. Happens with any OCR method including Cloud Vision API. Having a split screen option would save a LOT of manual editing time

Dialogue: {\an8}The faster I run, the clearer it becomes,<br />that dangerous line (ahh)
Dialogue: The faster I run, the clearer it becomes, that dangerous<br />line (ahh) Are you okay? We're getting outta here!
