### ISSUE TITLE
TTML2 support

### ISSUE THREAD

**Issue by OtaStrom** [SubtitleEdit/subtitleedit#6020]
Conversion from TTML2 almost works, but if it's in italic a useless font tag remains there: <font face="sansSerif" color="white">Subtitle Text</font

Here is an example ("txt" extension added to be able to upload it here):
[All the Old Knives (2022).ttml2.txt](https://github.com/SubtitleEdit/subtitleedit/files/8865024/All.the.Old.Knives.2022.ttml2.txt)

**Comment by niksedk** [comment]
Thx for the sample file - works fine for me.... you can remove font tags in the list view context menu (e.g. select all lines, Remove formattings, remove font color + remove font name).
