### ISSUE TITLE
[Improvement] Correct detection of Icelandic language

### ISSUE THREAD

**Issue by Elheym** [SubtitleEdit/subtitleedit#6021]
Icelandic "Fix common errors" gets mistakenly detected as Danish. Could this be fixed? Please find [Icelandic subs](https://github.com/SubtitleEdit/subtitleedit/files/8870359/Icelandic.zip) attached.

**Comment by niksedk** [comment]
thx :)
Hopefully Icelandic auto detect in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by Elheym** [comment]
Awesome! Works like a charm. :)
Thank you very much!
