### ISSUE TITLE
[Suggestion/Improvement] Remember selected line after subtitle reload in "Compare" tool

### ISSUE THREAD

**Issue by Elheym** [SubtitleEdit/subtitleedit#6023]
Would be cool if the program could remember the selected line after the subtitle is reloaded. If X number of lines disappear after reload, the selection should jump down X number of lines.

**Comment by niksedk** [comment]
thx - hopefully some compare improvements in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
