### ISSUE TITLE
Multiple Replace should have whole or partial word option for Normal find/replace

### ISSUE THREAD

**Issue by cyberbrix** [SubtitleEdit/subtitleedit#6026]
It would be great to have a whole word option for Find/Replace normal word.

For example, replacing disc with disk would impact the word discovery.

Can be done with regex, but that may be more resource intensive.

**Comment by maknol** [comment]
You can try with \b disc \b - Regular extension

**Comment by cyberbrix** [comment]
Wouldn't using regex just be more resource intensive
