### ISSUE TITLE
Tesseract 5 problem with Ubuntu

### ISSUE THREAD

**Issue by shag00** [SubtitleEdit/subtitleedit#6027]
I have upgraded to SE 3.6.6 and also took the opportunity to upgrade tesseract to 5.1.0, https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr5?field.series_filter=jammy. I linked the ubuntu tesseract files the same way as I did for tesseract 4 (ln -s /usr/share/tesseract-ocr/5/tessdata) but find that SE does not see it.

When I attempt to OCR translate I have 3 options in the OCR Method drop down, Binary image compare, Tesseract 4 and OCR via nOCR. In my SE directory I have 3 subdirectories related to tesseract: Tesseract302, Tesseract410 and Tesseract510.

Any assistance would be appreciated.

**Comment by shag00** [comment]
For posterity's sake I have resolved the issue, it appears to revolve around libtesseract4. Using the above mentioned PPA no libtesseract5 is created/installed. Google revealed that a libtesseract5 seems to exist for Debian Sid but not for Ubuntu. This may be the reason that SE does not recognise that Tesseract 5 is installed on the system.

Anyway, to enable SE to work I deleted the following folders:
- ~/Portable/SubtitleEdit/Tesseract410
- /usr/share/tesseract-ocr/4.00/

SE still only lists Tesseract 4 in the OCR Method drop down despite it not existing on my system rather, it uses the Tessercat 5 engine for OCR and now works.

This begs the question again of why this program is not released as an appimage.

**Comment by niksedk** [comment]
@shag00: In what folder are your Tesseract 5 data files? `/usr/share/tesseract-ocr/5/tessdata` ?

**Comment by niksedk** [comment]
OK, tried to detect Tesseract 5 in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip
Let me know if it works :)

**Comment by shag00** [comment]
@shag00: In what folder are your Tesseract 5 data files? /usr/share/tesseract-ocr/5/tessdata ?

Correct.

**Comment by niksedk** [comment]
Latest beta should now check the `/usr/share/tesseract-ocr/5/tessdata` folder.

**Comment by shag00** [comment]
The drop now correctly shows Tesseract 5.
