### ISSUE TITLE
problem reading lines with smpte 2010

### ISSUE THREAD

**Issue by stephw999** [SubtitleEdit/subtitleedit#6029]
with some imported smpte 2010 xml file, lines merge on export
[subfile(smpte).zip](https://github.com/SubtitleEdit/subtitleedit/files/8883547/subfile.smpte.zip)

**Comment by niksedk** [comment]
Could you explain your issue a bit more? You are missing some spaces?

**Comment by stephw999** [comment]
on the original file there is subtitling on two lines. But when I import this file, the program merges each spots into a single line. The carriage return is not done.
Also the "Italic" attribute is not interpreted in this case.

**Comment by niksedk** [comment]
How is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

I've not seen D-Cinema 2010 lines structured like this before...

**Comment by stephw999** [comment]
thank you, it's much better, but the first spot is missing :)

**Comment by niksedk** [comment]
>thank you, it's much better, but the first spot is missing :)
Could you explain more again?

**Comment by stephw999** [comment]
That's work !
Thanks Nikolaj
