### ISSUE TITLE
Compare subtitles isn't working properly

### ISSUE THREAD

**Issue by JDTR75** [SubtitleEdit/subtitleedit#6032]
Hello,

Like the subject says. This tool is not working properly. Please see the image below:

![image](https://user-images.githubusercontent.com/1891941/173207788-bfc85161-8870-4df9-86e9-96e4f7faaaaf.png)

As you can see, it's only highlighting the difference in text. It's pretty clear no time code is the same so it should be highlighted and it's not the case.

Thank you!

**Comment by niksedk** [comment]
Thx :)
The compare has been improved a little... but a little got in there too...

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
