### ISSUE TITLE
[Feature suggestion] Auto-translate window: single file support with Google translate

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#6033]
Currently google translate api is limited for free users (~1000 lines per day?). It would be nicer if subtitleedit adds some support around Google Translate's documents translation option to bypass its api limitations.
![Untitled](https://user-images.githubusercontent.com/25927091/173209197-1c797949-702c-4a6b-90be-482d1e2629b1.png)

- Export as a single document file. 
- Import&parse translated file returned by google.

It's doable manually but takes a lot of steps. Hopefully, we could support it directly in this translate window.🤞
![Untitled](https://user-images.githubusercontent.com/25927091/173209324-21387436-20f3-4346-84a1-d72b8e4e6468.png)

Documentation : [Translate documents
](https://support.google.com/translate/answer/2534559?ref_topic=7011659&hl=en#:~:text=translation%20form.-,Translate%20documents,-You%20can%20translate)

**Comment by niksedk** [comment]
OK, tried to add some support for this - via `Auto-translate via copy-paste` - https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

How does this work?

**Comment by darnn** [comment]
For the record, at least when I tried this a few months ago, the translation of the uploaded document was different (and worse) than the one you would get just pasting the text into the website version a few lines at a time. Some lines were left in English altogether, for instance.

**Comment by cyzs233** [comment]
> OK, tried to add some support for this - via `Auto-translate via copy-paste` - https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
> 
> How does this work?

Yeah, it works. But to be honest, it's kinda cumbersome to use this copy-paste translation window, it's generally not recommended to copy-paste translation back & forth between browsers. Thus we need to export the original subtitle to a single file.
First, you have to max the "block size" to the maximum to reduce it into a single copy-paste. Second, you have to remove any "line separator" since it will mess up the formatting of the translation returned by google.
![Untitled](https://user-images.githubusercontent.com/25927091/173228964-e4b6ca1b-b4e7-4434-89b6-8c61810cbcb2.png)
 (Period get translated into other punctuations)
![Untitled](https://user-images.githubusercontent.com/25927091/173229510-67b70572-1f23-4489-a70f-54410b64e261.png)

Maybe we could add pdf support directly in the translate window I have mentioned? Cause that's all we wanted in the end and has been supported by all translation services. You will get instant translation results on google, which is significantly faster than API requests.
IMO, the currently workflow (edit parameter ---> export to .txt ---> convert to .pdf/.docx  ---> copy translation & paste into subtitleedit) needs a refactor. I don't think most user will get the feel of how to use this copy-paste feature.

@darnn Yes indeed, but it seems more like an "unknown word" (or names) related problem.
![Untitled](https://user-images.githubusercontent.com/25927091/173231915-79867136-aa6b-4c5f-800d-2036561de880.png)

**Comment by niksedk** [comment]
OK, how should lines be separated?

Is ".rtf" supported?
C# cannot write pdf/docx unless using some third party libraries... I just tested a pdf lib which added about 150 MB to SE...
I found a docx library that was smaller.

It's harder to maintain code that uses external libs.

**Comment by cyzs233** [comment]
> OK, how should lines be separated?
A simple new line will do in this case.

> Is ".rtf" supported? C# cannot write pdf/docx unless using some third party libraries... I just tested a pdf lib which added about 150 MB to SE... I found a docx library that was smaller.
> 
> It's harder to maintain code that uses external libs.

Adding .docx support to SubtitleEdit would be great. Maybe half of the current text editing issues can be closed if you offer them an option to edit in Word instead. 
Some other cool things you can do with .docx are more:
- More language support.
More spelling check support on non-english subtitles. Even grammar check! [Grammarly for Microsoft Word](https://www.grammarly.com/office-addin)
- More text editing support
#6001, custom word list, coloring, etc.
- More happy translator
You can now use SubtitleEdit to handle the transcription part(and rough timestamp), then maybe merge&export those transcription texts into logically separated segments(instead of translating line by line in subtitleedit). Hopefully, the translation result will be more context-aware & easier to compile into a working subtitle.
- More encouraging for plugin writer
There are generally more cool things you can do with Word (compare to plain text or heavily structured subtitle formats).

Of course, developing difficulty is the first concern. Someone has to actually implement it first😉

**Comment by niksedk** [comment]
It would only be .docx file reading/saving.

**Comment by cyzs233** [comment]
> It would only be .docx file reading/writing.

Hmm, that doesn't sound motivating to implement .docx support at all. Guess we'll stick with plain text then.

Now that we have discussed the restriction of this copy-paste feature, maybe we could deprecate this feature and move its save&load functionality to the Auto translate window (if there is no other use than simply copy-paste)?
Web browsers tend to add formating to the translation result in their web UI, in such cases, users shouldn't just assume the copy-pasted translation just magically works in Subtitleedit and have to paste & review the result locally first. (Line separator get translated into other punctuation for example)

**Comment by niksedk** [comment]
The "Translate via Copy paste" is extremely useful... and the line separator is customizable.

I've tried to add docx import/exort in the "Translate menu"... let me know if it's useful or not:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
@cyzs233 : did you have a change to try the above beta?

**Comment by cyzs233** [comment]
@niksedk I'm having trouble upload this .docx on Google translate.
it says "file corrupted". (maybe .docx version compatability problem?🤔 )
<details><summary>Demo</summary>

<p>

![fail to upload on google translate](https://user-images.githubusercontent.com/25927091/175134804-5aa17bb5-1458-4df3-9dba-273e1c3d6b74.png)


</p>
</details>

It works on Baidu online translate(upload), but the table structure got reformated.
Currently, You can use Word's built-in translator instead, it will maintain the original table structure.
<details><summary>Reformated result</summary>

<p>

![table structure lost in translation process](https://user-images.githubusercontent.com/25927091/175134873-a2eed4e4-d533-49e2-8b28-798112f739c4.png)

</p>
</details>

And then when I tried to open it using "Step 2 - import", an error was prompted. 

<details><summary>import error</summary>

<p>

![error when importing](https://user-images.githubusercontent.com/25927091/175150779-8fb8915f-4349-44a3-964f-b79ee91572ab.png)
</p>
</details>

[translation (returned by baidu).docx](https://github.com/SubtitleEdit/subtitleedit/files/8962073/translation.returned.by.baidu.docx)
Actually, this import error will also occur even if the .docx is the file previously produced by "step 1 - Export"
[exported docx.docx](https://github.com/SubtitleEdit/subtitleedit/files/8962179/exported.docx.docx)

source .srt attached below:
[It Is Good to Live.1956.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/8962131/It.Is.Good.to.Live.1956.srt.zip)
