### ISSUE TITLE
I can t get the subtitles in the program

### ISSUE THREAD

**Issue by tiomaldy** [SubtitleEdit/subtitleedit#6038]
![image](https://user-images.githubusercontent.com/61519589/173760218-b3b4d746-a9db-45b3-9cf4-46511b405fc9.png)
Here you can see that the subtitles are present in the video when I watch them from any program like window movie maker or vcl, but when I upload it to subtitle edit those subtitles do not appear, is there any way to make them appear to be able to edit them?
![image](https://user-images.githubusercontent.com/61519589/173760524-f3539e22-b148-4d29-9437-6253f2632a7e.png)

**Comment by lambdacore12** [comment]
@tiomaldy, can you share the link to the subtitles fils?

**Comment by tiomaldy** [comment]
> @tiomaldy, can you share the link to the subtitles fils?

The subtitles not appear in a file is like a burn in in the video or something like that

**Comment by lambdacore12** [comment]
Can you send us the file so we can check it?

**Comment by tiomaldy** [comment]
I can t upload the video here  is a MKV video

**Comment by niksedk** [comment]
You can check if subtitle tracks exists with e.g. MkvToolNix o ffmpeg...
