### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by A-Winters** [SubtitleEdit/subtitleedit#6040]
I get this error when I try to export my font styles. The app force closes following this message.

![Fullscreen capture 15062022 230728 bmp](https://user-images.githubusercontent.com/81023806/173940819-3af34140-2772-4f04-9a3f-33b54dac5027.jpg)

**Comment by niksedk** [comment]
Could you attach the ssa subtitle file?

**Comment by niksedk** [comment]
Fixed in https://github.com/SubtitleEdit/subtitleedit/commit/1fed36acd157fc879ea0964c917d6662f3b8a7a3
