### ISSUE TITLE
[Shortcut Request] Setting start/end for multiple selected lines

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6047]
Say, If I want to set two or more lines with the same Start and/or End, can it possibly be done with a single operation instead of setting them one by one? (or, we don't actually need new shortcuts and just batch doing it when multiple lines are selected?)

Yes, it'll certainly cause overlaps, but that is needed when working with ASSA projects (at least). :)

**Comment by niksedk** [comment]
Not really sure what is the best solution... just using the time for the first selected sub?
In the list view or the waveform?

**Comment by LeonCheung** [comment]
Sorry for the very late reply... Hmm, right, I have to admit that neither of them is the perfect solution. That's why I mentioned the thought of a multi-track waveform like many other NLA editors, which is the ultimate solution to all kinds of overlapped issues and could be much more powerful than that. Maybe I'll do some deep diving on this idea. :)

**Comment by cyzs233** [comment]
looks like a dupe #5225
