### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by MizzouDawg** [SubtitleEdit/subtitleedit#6048]
Hello, I have been using Subtitle edit for years, thank you, but today everytime i click on fix common errors i get an error code
that says:
String cannot be of zero length. 
Parameter name: oldValue

Stack Trace:

And then has a whole lot of lines. Never seen anything like this before. Could would appreciate any help I could Get, Thanks.

DD

**Comment by niksedk** [comment]
Hi @MizzouDawg,

What version of SE are you using?

Could you paste the error screenshot?
The subtitle would also help (you can drag'n'drop zip files here on Github)

**Comment by MizzouDawg** [comment]
Hey brother, you actually already helped me. When I deleted the J from my music symbol replacement...I had one sub that used J's for music symbols, very annoying...I left a blank space in between the commas. When you told me it had something to do with music symbols, I went and looked, and it all made sense. Thank you so much for your amazingly quick response, I have enjoyed using SE for so long, I would be lost without it. Thanks again!!

DD
________________________________

**Comment by niksedk** [comment]
Thx for the bug report and info - the crash should not also be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
