### ISSUE TITLE
Auto-naming rule for Translation file

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6058]
For translation work, take the workflow below for example:

1. First load the original subtitle;
2. Make empty translation lines for the current subtitle, then start translating;
3. Click Save, then a window pops up for you to choose the file name and the directory. Here the file name is the same as the Original file by default, but I think at least we can be allowed to auto-name it as something like xxx_translation.srt, or we could be able to define customized suffix in Settings, something like xxx_DE.srt or xxx.French.srt,  et cetera. so that we don't have to rename the name every time to avoid confusion and accidentally overwrite the original subtitle.

**Comment by niksedk** [comment]
How is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/205730669-42e458a9-705d-4c37-bc4b-d9e61cf89c8d.png)

**Comment by OmrSi** [comment]
@niksedk You're adding `<Auto>` each time the settings are opened, so if  `<Auto>` is added to `TranslationAutoSuffixes`, you'll have two of  `<Auto>` 

Also, there should be an option for `None`.

**Comment by niksedk** [comment]
Thx OmrSi, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
Better?

**Comment by LeonCheung** [comment]
Ah this is really cool. I didn't expected that there are so much coding work needed... Great work @niksedk ! Works as expected. Just one suggestion:

I think it would make more sense to add the sufix based on the original file name rather than the video source name. Because:

1. Sometimes translators are only provided with original SRTs. There are even no media provided. I just tested the latest beta, the default name was blank when trying to save the translation with no video loaded.
2. Even if there are media provided, for some reason, translators may not always get the original version, meaning that the media can be either compressed or covered with watermarks, e.g. the video name can be something like ***_burn-in_320x240_x264.mp4**.

Afterall, we are literally translating the SRT file, not the media itself. right?  :)

**Comment by LeonCheung** [comment]
Hi just found a little bug: It seems suffix will be added to every job, even it's not for translation... beta 66.

**Comment by LeonCheung** [comment]
Nice. Thank you!
