### ISSUE TITLE
Export Multiple Replace to CSV or TXT?

### ISSUE THREAD

**Issue by evayor** [SubtitleEdit/subtitleedit#6059]
I need to export my Multiple Replace lists to a CSV or TXT file in order to import them, hopefully, in Ooona where I have several projects. The export is in a .template file. I dropped it on Notepad, but I'm not sure it will work. Any ideas?

**Comment by sapphire-bt** [comment]
Hi there.

I'm not a developer for this repo, but it looks like this would be fairly trivial to do outside of Subtitle Edit as the template files are XML.

The first result when searching for "XML to CSV" brought me to https://www.convertcsv.com/xml-to-csv.htm - try copying/pasting the XML from Notepad into there and it should give you something you can work with.
