### ISSUE TITLE
exception exit

### ISSUE THREAD

**Issue by YongChingShieh** [SubtitleEdit/subtitleedit#6064]
I edit Subtitle use SubtitleEdit, But when I open any one video by mpc-be, exception exit!
systeminfo:
SubtitleEdit 3.6.6
Microsoft Windows 10 Enterprise 10.0.19044 N/A Build 19044
mpc-be 1.6.3.0
settings.xml
 
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/9032784/Settings.zip)

**Comment by niksedk** [comment]
Try libmpv as your video player.

Or if you have to: https://github.com/clsid2/mpc-hc/releases
I think mpc-be is dead...
