### ISSUE TITLE
Crashes importing to words list

### ISSUE THREAD

**Issue by Charvelx04** [SubtitleEdit/subtitleedit#6065]
3.6.6 is crashing when I choose to add a word during spell check, or Import OCR, to the words list. I can add names, not words.

I tried to find the log in Settings, but it crashes trying to open that as well.

**Comment by niksedk** [comment]
Do you have screenshot?

Probably a corrupt word list... and probably needs a clean install (delete "Dictionaries" folder before installing)

**Comment by Charvelx04** [comment]
Well, I can't grab an SS when it crashes... all I know is at this point, opening the program, clicking on Options, then Settings.. the Settings window opens, then the program crashes. I have compared this to a beta version that runs like a portable, and it does not crash. I was going to get a screen grab app and upload a small vid for you to see, but it doesn't take much to crash it.

I didn't notice the crash, until I was ripping a Bluray, and using the OCR feature. I could add anything I wanted to the name's list, but not the dictionary. 

I tried copying the dictionary folder from the portable to the main install, still crashed.

So, I think you're right.. might be time for a clean install. 

Also.. for anyone else reading this, the Dictionary folder is in Users/(profilename)/AppData folder. Explorer needs to have "show hidden folders" option checked in order to see it.

**Comment by Charvelx04** [comment]
I have also noticed, that this version doesn't completely shut down MPC-HC. After closing the app, MPC stays open in Task Manager and will not let you delete or move any video file it had open.

Not sure if you want me to start a different thread, but this is the last post I'll add to all this.. going to do a new install.

**Comment by Charvelx04** [comment]
And found your 3.6.6. portable. Same crash.

So.. I'll just use the installed version 3.6.6 and await further instructions, not much else I can think of.

**Comment by niksedk** [comment]
SE does not pop up a message when it crashes?
You can try to look in the "Event Viewer"...

Also, try libmpv instead of mpc-hc.
Re-installing dot net framework 4.8 might also help.

Did you delete the "Users/(profilename)/AppData/SubtitleEdit" folder? (you can also open this folder by pressing ctrl+shit+alt+D in SE).

**Comment by Charvelx04** [comment]
"SE does not pop up a message when it crashes?"
No. Quick crash; open program, click on Settings; settings window pops up and as it's trying to render, the program crashes.

"You can try to look in the "Event Viewer"..."
I keep forgetting about this.. seeing as I only used it back in the XP days.

Here's what Event Viewer has on it:

Faulting application name: SubtitleEdit.exe, version: 3.6.6.0, time stamp: 0x628e72b9
Faulting module name: mscorlib.ni.dll, version: 4.8.9032.0, time stamp: 0x6250a958
Exception code: 0xc0000005

- System 

  - Provider 

   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
 
   EventID 1000 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2022-07-05T21:07:49.1763931Z 
 
   EventRecordID 7901 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  16704 
   [ ThreadID]  13052 
 
   Channel Application 
 
   Computer Dad 
 
  - Security 

   [ UserID]  S-1-5-21-1183044535-3212934803-2919677781-1001 
 

- EventData 

  AppName SubtitleEdit.exe 
  AppVersion 3.6.6.0 
  AppTimeStamp 628e72b9 
  ModuleName mscorlib.ni.dll 
  ModuleVersion 4.8.9032.0 
  ModuleTimeStamp 6250a958 
  ExceptionCode c0000005 
  FaultingOffset 00000000005ae497 
  ProcessId 0x43ac 
  ProcessCreationTime 0x1d890b31d21281f 
  AppPath C:\Program Files\Subtitle Edit\SubtitleEdit.exe 
  ModulePath C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\mscorlib\5b8c945e30aa4099a8c0741d874b8f36\mscorlib.ni.dll 
  IntegratorReportId a417e548-eb27-42a6-b071-88d024b38e57 
  PackageFullName  
  PackageRelativeAppId  


"Also, try libmpv instead of mpc-hc."
I've switched back to VLC for now... had to copy that over from a portable settings file... as after a clean installation, you cannot add any video player if Settings crashes constantly.

"Re-installing dot net framework 4.8 might also help."
Since the crash is being reported under a .NetFramework error under the Viewer, I'll give this a shot.

"Did you delete the "Users/(profilename)/AppData/SubtitleEdit" folder? (you can also open this folder by pressing ctrl+shit+alt+D in SE)."
Yes... all folders for SubtitleEdit were removed.

**Comment by Charvelx04** [comment]
You nailed it, boss.

Bad .Net Framework files... I repaired all versions installed, and she works like normal again.

Thank you... most appreciated. 👍

**Comment by niksedk** [comment]
Cool, I'm glad it works now :)

By the way, if you use the waveform, you will be happier with mpv as it has a more precise position (VLC will fix this in version 4... which is a few years late).
