### ISSUE TITLE
add a tag to multiple (all) lines

### ISSUE THREAD

**Issue by yahyamurat** [SubtitleEdit/subtitleedit#6068]
hi,
I have a movie with embedded subtitles of a language I am not familiar with. I have a .srt file for it. In its default location (bottom), the subtitle overlaps the embedded one. I want to add {\an8} to the beginning of all lines, so that the lines of srt are displayed at top. With Find and Replace I don't know what to enter for Find. Is this possible in SubtitleEdit? Thanks

**Comment by niksedk** [comment]
Select all lines in the list view (Ctrl+a), then right click in the list
view and choose alignment and top center

**Comment by yahyamurat** [comment]
So easy and effective. Thanks a lot niksedk.
