### ISSUE TITLE
Use Sub1 Time Codes for Sub2 ?!

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#6073]
Hi!

I have Two Subs in two different languages.

How do I use the Time Codes from Sub1 for Sub2?

They both have equal number of lines.

**Comment by darnn** [comment]
If you're absolutely sure they're identical, you can open the one with the text you want and then use file->import->time codes.
To be on the safe side, what I'd do is this:
Open the file to which you want to apply the time codes. Select all the lines and press control+C to copy them to the clipboard. Now, open the file with the proper time codes. Go to tools->make new empty translation from current subtitle. This will put you in translator mode, and you'll have a new, empty subtitle file with the same time codes as the first one. Now right-click the first line in the file, and select column->paste from clipboard. Here, select "text only" and "overwrite" and click OK. Now you should get the text you wanted with the time codes you wanted. You can now save this file, and also go over the lines to make sure everything does indeed match.

**Comment by Minherre** [comment]
Thanx a Lot!
Will try those options as soon as possible!
