### ISSUE TITLE
Opus in MP4 doesn't show waveform, MKV does

### ISSUE THREAD

**Issue by 0TTA** [SubtitleEdit/subtitleedit#6078]
Opus in MP4 doesn't show waveform, MKV does

I use ffmpeg to generate waveform

**Comment by niksedk** [comment]
Could you explain more?

What is Opus?
Where can I get a sample file?

**Comment by 0TTA** [comment]
It was my fault. I mapped the FFmpeg my self. I let subtitle edit download it by itself and that seems to fix it.
