### ISSUE TITLE
Import Plain Text issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6080]
Not sure what happened here, but when importing the attached piece and using "Split at blank lines", the last line was kind of split unexpectedly. 
[test.txt](https://github.com/SubtitleEdit/subtitleedit/files/9129101/test.txt)

**Comment by niksedk** [comment]
Seems to work here... what exactly is the issue?

**Comment by LeonCheung** [comment]
Actually, I've noticed that last year or so, but rarely happens depending on the actual texts. It only occurs on the end piece. Please see the GIF below:
![GIF](https://user-images.githubusercontent.com/494788/179451016-dda85b76-5627-4e66-a0df-3df44e08ea03.gif)

However, it would be okay if I add an extra break under the end line. Not a big problem though...

**Comment by uckthis** [comment]
I get this issue with Auto Split. 
Char length is set to 36, but see the last line:
![Untitled](https://user-images.githubusercontent.com/28671050/179501884-e257def3-c588-4092-841e-fea10c69f8a7.png)

I have three copies of SE that I work on. I don't like changing profiles every time, so I have two copies for two clients and one for varying specs and this only happens in one version/copy. Other two work fine, so I just split in one of them. Have been happening to me for close to 6 months.  
Maybe make another folder and extract another copy of SE portable in it and see if that works.

**Comment by niksedk** [comment]
thx for the info - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
