### ISSUE TITLE
[Suggestion] Fine-grained mouse wheel control on waveform

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6086]
Currently, when scrolling over Waveform with the mouse wheel,  the increment seems to be like 500 ms around. It would be more convenient to allow customize this increment in Settings, or, another quick and dirty solution might be like, Shift + Scroll to allow an increment of 100 ms, and/or while Alt could be something like 50 ms, which could be very helpful for fine-tuning work.  :)

**Comment by cyzs233** [comment]
How about we bound the "increment" to the current waveform zoom level?
![Untitled](https://user-images.githubusercontent.com/25927091/180198289-57c9d46f-2502-418b-8852-fc30dd251d91.png)

100% zoom --> 500ms increment
200% zoom --> 250ms increment
50% zoom -->1000ms increment

**Comment by LeonCheung** [comment]
I won't second that because in that case you have to zoom in / out first, which is not always expected. They are two different things, and should not be bound together.
