### ISSUE TITLE
Request: Export as 8 bit indexed PNG

### ISSUE THREAD

**Issue by franontanaya** [SubtitleEdit/subtitleedit#609]
It seems some tooling expects 8 bit (255 colors) indexed PNGs for formats like BND XML+PNG. 

Running SE 3.4.5 on Ubuntu 14.10, the output is full RGB PNG. Batch converting them afterwards is fairly trivial, but a checkbox option would be nice.

**Comment by niksedk** [comment]
Could you test latest beta version: http://www.nikse.dk/SubtitleEdit.zip (portable version)
