### ISSUE TITLE
How to create a split audio file for 1 line or several continuous line as Ageisub? steve800018@gmail.com

### ISSUE THREAD

**Issue by nissansz** [SubtitleEdit/subtitleedit#6090]
![image](https://user-images.githubusercontent.com/41010669/180693529-8d5264ec-5645-45ac-887d-93bef9db8d75.png)

**Comment by niksedk** [comment]
Hi,

I'm not really sure what menu item you're pointing too... also, I don't know what "split audio file" is? Could you explain more?

**Comment by nissansz** [comment]
I mean, is it possible to add a function to create audio clip from subtitle?
This is a function from aegisub on the screen capture.

**Comment by cyzs233** [comment]
ground base for this feature request #5988

**Comment by niksedk** [comment]
@nissansz: What do you use the audio clip for?

**Comment by nissansz** [comment]
asking some friends the text of the audio.

**Comment by niksedk** [comment]
OK, how is this?
![image](https://user-images.githubusercontent.com/1261331/180836768-3736d142-31b3-4965-a6e5-f4b6f46ebda7.png)

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by nissansz** [comment]
It works. But it is best to pop a window to save as audio.
Or add an option to export all split audios to a folder with time code for easy tracking,

**Comment by cyzs233** [comment]
I agree with nissansz's export all audio idea. Vosk is not the best speech recognition tool on the planet. 

Similar to this feature request, https://github.com/SubtitleEdit/subtitleedit/issues/5761#issuecomment-1030114980
it would be wonderful for SubtitleEdit to provide external ASR support. 
Workflow would be : export all audio clips, ASR them via [Google](https://cloud.google.com/speech-to-text) or something, and assemble the result texts into a working subtitle using SubtitleEdit.

**Comment by niksedk** [comment]
OK, time codes are now used in file names. 
SE should be able to import plain text files with time codes in file names via "File - Import plain text - multiple files".

Let me know if some external ASR engine give a format back, that "File - Import plain text - multiple files" will not read.

**Comment by nissansz** [comment]
By the way, any app on cell phone to navigate subtitles easily during play?

**Comment by cyzs233** [comment]
> asking some friends the text of the audio.

Merely audio is not sufficient for asking for transcription help. You prbably want to make a video clip out of it to provide more context background information.
A gdrive demo: https://drive.google.com/file/d/1e27DAD-Ooc1RoO0cqFZE02sBfhGrhceh/view?usp=sharing
Tools for video clipping: [lossless-cut](https://github.com/mifi/lossless-cut) / [vidcutter](https://github.com/ozmartian/vidcutter)

**Comment by nissansz** [comment]
it is from an audio, no video, so audio is enough.
