### ISSUE TITLE
Batch Convert Issue

### ISSUE THREAD

**Issue by stephpw** [SubtitleEdit/subtitleedit#6094]
Hi, I'm a user for Subtitleedit and are facing the following issue when try to apply "Batch Convert" function. Can anyone kindly advise how can I solve this problem? 

![image](https://user-images.githubusercontent.com/110153385/181432611-7c30b7f5-de3c-4888-8a62-2b827085c149.png)

**Comment by niksedk** [comment]
Thx :)
Should hopefully be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
