### ISSUE TITLE
Cannot generate waveform: `-vol` option dropped from FFmpeg

### ISSUE THREAD

**Issue by qwerty12** [SubtitleEdit/subtitleedit#6099]
Subtitle Edit 3.6.6 on Windows 11

Since yesterday, FFmpeg has dropped the `vol` argument: https://github.com/FFmpeg/FFmpeg/commit/8cbf229c941b3c77a756bff05d0ceb5f4f2219c5

Using ffmpeg version N-107574-ge0691eab22-20220729 (from [here](https://github.com/yt-dlp/FFmpeg-Builds/releases/tag/autobuild-2022-07-29-13-05)) gets me the following inside SE:

```
Could not find extracted wave file!
This feature requires VLC media player 1.1.x or newer (64-bit).

Command line: C:\Users\fp\scoop\apps\ffmpeg-shared-nightly\current\bin\ffmpeg.exe -i "Video.mkv" -vn -ar 24000 -ac 2 -ab 128 -vol 448 -f wav  "C:\Users\fp\AppData\Local\Temp\beca7c29-2448-423d-af70-9567aa7f07df.wav"
```

and the following when I run the same command in `cmd`:

```
Unrecognized option 'vol'.
Error splitting the argument list: Option not found
```

If I downgrade to ffmpeg version N-107546-g6f7d3bde11-20220728 (one build before), then the extraction works with the following warnings:

```
-vol has been deprecated. Use the volume audio filter instead.
-vol is forwarded to lavfi similarly to -af volume=1.750000.
[pcm_s16le @ 000001ff40961400] Bitrate 128 is extremely low, maybe you mean 128k
```

**Comment by niksedk** [comment]
OK, what happens if you go to Options - Settings, and click on "restore default values" - and retry?

**Comment by qwerty12** [comment]
Thank you for the quick reply. I just checked: replacing `-vol 448` with `-af volume=1.750000` produces an identical wav file

**Comment by qwerty12** [comment]
Thanks!

**Comment by niksedk** [comment]
Updated source :)
And beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by qwerty12** [comment]
Thank you - just tried the beta from your link with ffmpeg version N-107574-ge0691eab22-20220729 and everything works
