### ISSUE TITLE
High resolution logo

### ISSUE THREAD

**Issue by XhmikosR** [SubtitleEdit/subtitleedit#61]
We need a higher resolution logo to use in the program itself and on GitHub.

**Comment by glaubersm** [comment]
alt+tab menu shows pixelated icon on linux, Gnome desktop environment

![alttab](https://user-images.githubusercontent.com/15967631/65831845-eb769d80-e293-11e9-8fbc-e829f6ea88f7.png)

**Comment by zcraber** [comment]
@niksedk Is it possible to get the SVG version of the current logo?

**Comment by niksedk** [comment]
![1024](https://user-images.githubusercontent.com/1261331/220973101-7a94355f-7c2c-47d5-b5fa-4e8345e06426.png)

![SE](https://user-images.githubusercontent.com/1261331/220974068-db0b48fe-4cb6-4c38-a9ea-748342daa916.svg)
