### ISSUE TITLE
Need help with a regular expression - select all text in parenthesis

### ISSUE THREAD

**Issue by BlohoJo** [SubtitleEdit/subtitleedit#6101]
I apologize if this is the wrong place to ask. I tried and tried, but I am not smart enough to figure it out.

All I want is to match any text in parenthesis.

Example:

(Blah blah.)

I want to match just the entire above line, so it matches _anything_ inside the parenthesis, including the parenthesis.

Obviously I want anything not in parenthesis to be left alone.

Is there a way to do that?

The best I can get anything to do is select only the ) parenthesis, and a single character to the left of it.

I really hate that I can't get it. :P

**Comment by niksedk** [comment]
You're the right place :)

You can try Edit - Multiple replace, and add a regex like this:

![image](https://user-images.githubusercontent.com/1261331/181885956-43c62606-da56-4bbe-b254-22bdf5d67349.png)

Does that work for you?

**Comment by darnn** [comment]
Since you can only select text in the subtitle that's currently in the textbox, to select anything in parentheses, you just basically use the same regular expression you used in your example, except only the middle part, no? That is, search for `\(.*\)` as a regular expression?
