### ISSUE TITLE
Audio/video to text doesn't support kaldi models.

### ISSUE THREAD

**Issue by Honzecki** [SubtitleEdit/subtitleedit#6105]
Hello,
according to the Audio/video to text window, you should be able to use Kaldi models natively, but simply dragging the Kaldi model into the models folder didn't work and I couldn't find any documentation that could help me, except for changelogs claiming that using Kaldi models should work.
Could you please help me with this?
I'm using the latest 3.6.6 version.

**Comment by niksedk** [comment]
What model are you using? Do you have a link?
And probably, you should ask here: https://github.com/alphacep/vosk-api/issues

**Comment by Honzecki** [comment]
I'm using the larger version of the Rhasspy Czech model [cs_kaldi-rhasspy v1.0](https://github.com/rhasspy/cs_kaldi-rhasspy/releases/tag/v1.0) as I find the small model to not be sufficient.

**Comment by niksedk** [comment]
You can download Czech model from SE....

**Comment by Honzecki** [comment]
I understand that but the SE model is very small, is there any way for Kaldi models to be used?

**Comment by niksedk** [comment]
I think your linked model is even smaller... and sorry, I've no clue on how to use it.

**Comment by nshmyrev** [comment]
@Honzecki https://alphacephei.com/vosk/models/vosk-model-small-cs-0.4-rhasspy.zip is actually bigger than the one you linked. In the linked on final.mdl is just 6Mb, it is not enough.  If you still want to use it you have to rearrange the files accordingly.

If you need more accurate model, you have to train it yourself.
