### ISSUE TITLE
MSI installer possible? (Feature request)

### ISSUE THREAD

**Issue by maxi07** [SubtitleEdit/subtitleedit#6107]
Hi,
is it possible to have an MSI installer for easier software distribution, eg. Endpoint Manager (Intune)?

Thanks!

**Comment by eladkarako** [comment]
until then, use [innoextract](https://github.com/dscharrer/innoextract/releases/latest) on the setup file, copy the content of `userappdata` to `%AppData%`, and `app` to program files. it lacks getting the [registry entries](https://github.com/SubtitleEdit/subtitleedit/blob/29255f28dfc1ca5807118ee46478edd160dd60e4/installer/Subtitle_Edit_installer.iss) `Software\Nikse\SubtitleEdit`, `Software\Classes\Applications`, `Software\RegisteredApplications`, `Software\Microsoft\Windows\CurrentVersion\App Paths` (`HKEY_CURRENT_USER`) but it would still work. you can export a reg key once, from a computer that had it installed properly.

**Comment by niksedk** [comment]
A PR is welcome
