### ISSUE TITLE
[Bug]Windows Forms Thread Exception

### ISSUE THREAD

**Issue by holduan** [SubtitleEdit/subtitleedit#6108]
![Bug Windows Forms Thread Exception](https://user-images.githubusercontent.com/80377040/182559474-cef56046-6fac-4137-ac38-af09893a7b66.png)
video: [Concepts in SuperMemo](https://www.youtube.com/watch?v=gbHTn_fIs1A&ab_channel=SuperMemoWiki)
[[Bug]Windows Forms Thread Exception-srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/9249407/Bug.Windows.Forms.Thread.Exception-srt.zip)

**Comment by niksedk** [comment]
Hm, that looks like a problem with the underlying system... try restarting or perhaps upgrade the OS.

**Comment by holduan** [comment]
> Hm, that looks like a problem with the underlying system... try restarting or perhaps upgrade the OS.

My friend and I have tried restarting our computers, three pc's with Windows 10 19044 and Windows 11 22000, and all reported errors.

**Comment by niksedk** [comment]
OK, could you attach the subtitle?
I assume it not happening with all subtitles?

**Comment by holduan** [comment]
> OK, could you attach the subtitle? I assume it is not happening with all subtitles?
In the description there is an srt file and video link.

**Comment by niksedk** [comment]
thx for the file :)
I'm not really sure how to fix this, as it is the underlying system that crashes... 

SE could possibly remove a character in the waveform - not a nice solution, but better than a crash.

**Comment by niksedk** [comment]
Characters like these seems to crash: 用‍‍ 是‍ 习‍‍ 建‍‍

I have no clue how to fix this issue - help welcome :)

**Comment by holduan** [comment]
It seems that there is a problem with the txt file, at line 80: "They're gonna be skinning this door
[Part 02 - Technical Scout.txt](https://github.com/SubtitleEdit/subtitleedit/files/9274577/Part.02.-.Technical.Scout.txt)
"

**Comment by niksedk** [comment]
Yes, it will also crash on long lines... 
I've hacked a bit here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
Will display `?` in the waveform when GDI crashes... hopefully.

**Comment by holduan** [comment]
> Yes, it will also crash on long lines... I've hacked a bit here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip Will display `?` in the waveform when GDI crashes... hopefully.
> 
> Somewhat better or are you still crashing?

Both srt files were tested and the original crash no longer crashes, thx.
