### ISSUE TITLE
Random {\an1} continue to appear on .scc files

### ISSUE THREAD

**Issue by Defal7c** [SubtitleEdit/subtitleedit#6109]
Hello, I have the same problem as #5234 , I tried doing the Remove formatting solution but when I open the file again, it just happens again! I never manually placed the alignment tag there, how should I proceed?

[TLC388633-PRT.scc.zip](https://github.com/SubtitleEdit/subtitleedit/files/9255141/TLC388633-PRT.scc.zip)

**Comment by eladkarako** [comment]
<details><summary>just a workaround for now</summary>  

use notepad++ to globally replace with regular expression  
`\{\\an\d+}\s*` with empty string.  

(I'm pretty sure this tag does not include something else  
so I would not advise removing stuff after - `\{\\an\d+[^\}]*\}\s*` )

after that you can try to remove remaining ones that are a part of more than one instruction in a self-closing tag,  
replacing just `\\an\d+` with empty string.  

</details>

**Comment by Defal7c** [comment]
I'm trying my best to do it but it seems that my .scc doesn't work like that...
![image](https://user-images.githubusercontent.com/32604521/182751682-dadd81ff-eba9-4bb5-bfe7-780b128779b5.png)

**Comment by eladkarako** [comment]
sorry that's a thing for clear text,  
you need to save the closed caption subtitles as srt (or vtt),  
edit that with notepad++, save and convert it back to close caption format.  

note that if subtitleedit can not be used for converting back to close caption,  
you can try looking for other srt to close caption programs  
(there are also pycaption for python and its NodeJS "fork" node-captions).

**Comment by Defal7c** [comment]
Well, it looks like it kinda solved the issue. I'll try sending the """fixed""" .scc files to my boss and see if there are any complaints. Just wished that SubtitleEdit wouldn't do that...

**Comment by Defal7c** [comment]
I've been working with .scc files for one or two months now and my "workaround" is to work on a .srt file for anything that I need to work with and, at the end of the project, export it as a .scc file and never think about it again.

My """theory""" (if you can call it that) is that SubtitleEdit doesn't properly **open** .scc files, instead of not properly **saving** them.

So far all of my clients didn't complain about any {/an1} tags so I just put it under the rug and call it a day.

**Comment by roseditor** [comment]
Thanks for the input Defal. I think you're right. 
I don't know if this might be useful info for you, but I'm creating .srt files from Premiere Pro, opening them in Subtitle Edit. When I save as .scc and re-open in SE I see the added {\an1} but when I open those .scc files in PPro I don't see that formatting but I do see shortened caption durations. 

Seems like SE is adding formatting when it opens .scc and PPro is shortening captions when opening .scc files. Frustrating, but I think your theory is right and these .scc files are fine.

**Comment by niksedk** [comment]
Should be somewhat improved
