### ISSUE TITLE
[Bug] Audio Track 1 is always chosen for audio to text

### ISSUE THREAD

**Issue by edwardg117** [SubtitleEdit/subtitleedit#6110]
**Expected behavior**
Audio track 2 is transcribed when it is selected.
**Actual behaviour**
Audio track 1 is transcribed when track 2 is selected.
**Detailed Description**
I've been trying to transcribe specific audio tracks that aren't the first audio track and found that track 1 will always be used, even if another is selected.
In the attached video, I grabbed a short recording where the second audio track is blank because it's all I had avaible to test (all others are several hours long). I expected no subtitles to be generated as I selected track 2. However track 1 was used anyway.
There was an odd behaviour during recording, where the progress was not displayed and the window displayed "not responding". This has not happened outside of recording so I'd attribute that to recording with OBS.
**Extra Details**
**OS:** Windows 10 (64bit)
**Subtitle Edit version:** 3.6.6 (64 bit)

https://user-images.githubusercontent.com/8350193/182759776-0d3f9b80-5e58-4a14-bb61-7b1229d861af.mp4

**Comment by niksedk** [comment]
Thx for the info :)
Is latest beta better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip

**Comment by edwardg117** [comment]
I tried it with the clip from the video, it seems to be working though the waveform was the same for both tracks. Might be user error because I tried a different clip and that worked fine.
Latest beta works great and this issue is not present 😄

**Comment by edwardg117** [comment]
Thanks for the fast response too!

**Comment by niksedk** [comment]
Thx for testing :)
