### ISSUE TITLE
GUI issues about translation

### ISSUE THREAD

**Issue by bovirus** [SubtitleEdit/subtitleedit#6119]
@niksedk 

Please check screenshoots of GUI issues about tarnslation

![SubTitleEdit 3 6 7 - 01](https://user-images.githubusercontent.com/1262554/182936570-f08b2afe-40c3-4742-831f-692f672cfcf6.jpg)

![SubTitleEdit 3 6 7 - 02](https://user-images.githubusercontent.com/1262554/182936578-a1bbf92c-a2e8-4631-b955-c399b9ff4196.jpg)

![SubTitleEdit 3 6 7 - 03](https://user-images.githubusercontent.com/1262554/182936579-b287f3ad-73ec-4313-b3c7-4823937d64e7.jpg)

![SubTitleEdit 3 6 7 - 04](https://user-images.githubusercontent.com/1262554/182936581-faf180c7-ed9d-48ab-918a-42e04812c566.jpg)

![SubTitleEdit 3 6 7 - 05](https://user-images.githubusercontent.com/1262554/182936583-d701e050-341d-40e1-9a0c-a137b1f52403.jpg)

![SubTitleEdit 3 6 7 - 06](https://user-images.githubusercontent.com/1262554/182936584-04b43e56-2506-4b1e-a06a-03f4117fcc47.jpg)

![SubTitleEdit 3 6 7 - 07](https://user-images.githubusercontent.com/1262554/182936585-488ee14a-81aa-4f07-807f-6080579228a7.jpg)

![SubTitleEdit 3 6 7 - 08](https://user-images.githubusercontent.com/1262554/183032968-fd668622-2472-42cd-904a-631e98de2e57.jpg)

![SubTitleEdit 3 6 7 - 09](https://user-images.githubusercontent.com/1262554/183033012-517e5ec9-7d0b-4e62-a158-80db94fdce17.jpg)

**Comment by niksedk** [comment]
thx for the info :)

Some of these have dynamic text and are hence somewhat difficult to make translation for...

But this should be fixed:
![image](https://user-images.githubusercontent.com/1261331/183233934-45e4390d-faae-4da4-8ea5-3d2c0e9fbe35.png)

And this now has a bit more space:
![image](https://user-images.githubusercontent.com/1261331/183234149-103450df-81dc-4a07-bf7b-79dc6ab1f142.png)

New language tag for this:
![image](https://user-images.githubusercontent.com/1261331/183234251-bc135b58-b882-4b5b-a9f9-2f896d1480ab.png)


Where is this from?
![image](https://user-images.githubusercontent.com/1261331/183234257-368403eb-4950-4b63-9c3c-5f4c38a37afc.png)
