### ISSUE TITLE
"Play first selected subtitle", "Play selection" jump to next subtitle.

### ISSUE THREAD

**Issue by rebawest** [SubtitleEdit/subtitleedit#6122]
Hello. There seems to be an issue with these two commands.

![image](https://user-images.githubusercontent.com/6587015/183219816-45cbe2df-a2a9-4184-bc7a-41b599e9ab6c.png)

“Play first selected subtitle” sometimes jumps to next subtitle.
It seems random. In this video, you can see the first time it fails, but the second time it stays on the subtitle.

https://user-images.githubusercontent.com/6587015/183219844-ccd6dc7b-be22-493c-a322-76a254110e8e.mp4

![image](https://user-images.githubusercontent.com/6587015/183219863-9086b446-fb62-4e05-bec8-925d524ed07c.png)

Something similar happens with “Play selection”. Sometimes it plays the subtitle and stays on it, and other times it plays two subtitles (the current one and the next one).

I'm using SE 3.6.6.
Let me know if you need more information.
Thanks!

**Comment by niksedk** [comment]
Works fine here for me... 
I think your mp4 file is audio only?

**Comment by rebawest** [comment]
It's a video file. I don't know why it doesn't show. If you download it, it plays.

**Comment by niksedk** [comment]
Still works fine here for me...
What video player are you using?

**Comment by rebawest** [comment]
MPV.
It also fails with VLC and MPC.
It seems to work fine with Directshow, but it's too random to be 100% sure.

At first, I thought it might have the gap between subtitles, but it's not. I can't find a pattern.

I mostly use the frame mode, but it also fails in millisecond mode.
I've tried pressing F4 several times in a row. Sometimes it fails on the 4th key press, sometimes on the 3rd.

**Comment by niksedk** [comment]
Could you attach the subtitle file?

**Comment by rebawest** [comment]
[776_PokemonUnite_PP_Crowley_SOC_v3-lowres_5994_LAS.zip](https://github.com/SubtitleEdit/subtitleedit/files/9275487/776_PokemonUnite_PP_Crowley_SOC_v3-lowres_5994_LAS.zip)

Here it is.

**Comment by niksedk** [comment]
Hm, I still cannot re-create the issue... could you attach your Settings.xml too?

**Comment by rebawest** [comment]
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/9275510/Settings.zip)

Here it goes.

**Comment by niksedk** [comment]
Sorry, I cannot re-create this.

**Comment by niksedk** [comment]
I could work better in latest beta...
