### ISSUE TITLE
nOCR in batch convert tool

### ISSUE THREAD

**Issue by Gen3ric** [SubtitleEdit/subtitleedit#6129]
Is there any way to change the OCR software used in the batch convert tool? My last used is nOCR but when I try batch converting subtitles I get different results so I think it's using different OCR software.

**Comment by niksedk** [comment]
How is this?

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/184807287-3a4dd198-abc7-4b55-8245-d17aed51fda0.png)

**Comment by Gen3ric** [comment]
Works great, thank you very much!
