### ISSUE TITLE
Volume gets insanely loud and distorted out of nowhere

### ISSUE THREAD

**Issue by matheusguifer** [SubtitleEdit/subtitleedit#6130]
I'm using VLC as video player and the volume keeps getting insanely loud and distorced out of nowhere. 

I have the latest version of both Subtitle Edit, VLC and FFmeg. 

I did have audio boost enabled but after disabling it the issue persisted.

**Comment by OmrSi** [comment]
Could you try using MPV? It's the best video player for SE.

**Comment by eladkarako** [comment]
> using MPV

I also advise to update the components.

- `mpv-2.dll` from https://sourceforge.net/projects/mpv-player-windows/files/libmpv/ (https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20220807-git-9add44b.7z/download).
- `libvlc.dll` from https://artifacts.videolan.org/vlc/nightly-win64 (https://artifacts.videolan.org/vlc/nightly-win64/20220809-0424/vlc-4.0.0-dev-win64-957c2d6a.7z).
- MPC [Media-Player Classic](https://sourceforge.net/projects/guliverkli/files/Media%20Player%20Classic/MPC%206.4.9.0/), and [Media Player Classic Home Cinema (MPC-HC)](https://nightly.mpc-hc.org/) are over 5 years old.  
download [Media-Player Classic BE](https://sourceforge.net/projects/mpcbe/files/MPC-BE/Release%20builds/1.6.3/), drop its files over wherever you've installed MPC.
- `quartz.dll` direct-show runtimes comes as part of Windows installation.  
you can rip a more updated one, from the `install.wim` of generated dev-preview-release of Windows 11, using https://uupdump.net/ .

**Comment by matheusguifer** [comment]
I'd rather use VLC because it is louder, which is paramount to me as I am hard of hearing.

**Comment by darnn** [comment]
This is neither here nor there, and if this is actually a bug that was introduced into SE sometime recently, I'm all for fixing it, of course. But generally speaking, if I were you, I would use MPV, and boost the volume of the audio in the actual file you're working with. There are all kinds of programs to do this with, but Izotope RX 9, for instance, seems to be pretty good at increasing volume while also preventing clipping. Granted, this is more convoluted, but MPV is just smoother (in skipping X seconds back and forth, for instance), so to me it's worth the effort.
