### ISSUE TITLE
Youtube Timed Text support

### ISSUE THREAD

**Issue by Richienb** [SubtitleEdit/subtitleedit#6133]
This internal subtitle format used on YouTube provides the most features. The current solution is to [author .ass files and then approximately convert them](https://www.reddit.com/r/youtube/comments/ahater/undocumented_subtitle_format_discovered_and_boy/).

It has also been referred to as [SRV3](https://www.reddit.com/r/youtube/comments/es4yd2/misc_fd_stylized_captions_are_now_broken/) and that [it is based on TTML](https://stackoverflow.com/questions/46494279/what-is-this-subtitle-format-called/46506730#46506730).

**Comment by liamzachs** [comment]
There is a problem which can be seen very clear. And it is that there are unwanted spaces and the text seems to double when exporting-- which can't be seen clearly-- but if seen in Subtitle Edit/YouTube Transcription, it will show that it is double-text.
Even worse, it seems to overlap in YouTube if seen in the YouTube Transcription.

**Comment by eladkarako** [comment]
https://github.com/arcusmaximus/YTSubConverter
