### ISSUE TITLE
[Shortcut suggestion] Repeat selected line

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#6137]
Most language learning tools benefit from the ability to A-B cycle given dialogues, implementing this functionality will make subtitleedit more desirable to language learners who seek precise replay control on personal favored linguistic Corpus in the form of digital media, ie, movies.
Other usecase would be to actually transcribe each line in subtitleedit.

Keyword-Stuffing：A-B loop, Auto-repeat, replay, cycle, fractal, quantum physics.

**Comment by OmrSi** [comment]
I think A-B loop is a bit hard, but a good idea in my opinion might be an infinite loop shortcut for a line, the start and end of the line would be the A and B.

**Comment by niksedk** [comment]
I think SE already has this - via translate mode:

![image](https://user-images.githubusercontent.com/1261331/185037457-fd32f90e-2827-438f-b6c6-02f41646ac19.png)


Or alternatively use F5:

![image](https://user-images.githubusercontent.com/1261331/185037367-be653a07-d6f2-4d97-8410-5a7f8f97914b.png)

**Comment by niksedk** [comment]
> transcribe each line in subtitleedit

Do you mean like, right-click in list view?
![image](https://user-images.githubusercontent.com/1261331/185037806-63d31353-991c-47bb-8764-9df906eb7560.png)

**Comment by OmrSi** [comment]
@niksedk True, but it's somewhat limited since it's only in `translate mode`.
As for play selected lines, it plays them once while loop would keep playing it.

I do think maybe a better logic is needed?
Like a pause event for the video where it would reset the variables that should be reset when pausing a video.

**Comment by cyzs233** [comment]
Yes, besides the inconvenience of it being a `translate mode` only utility as covered by OmrSi, this shortcut was initially requested more towards the language learning direction on top of the already usable `AUTO Repeat`. 
When you're just started getting your hands on a language, your listening skills are limited and most of the time you end up looping a given dialogue over and over until enlightenment finally descends upon you. 
The current 'AUTO Repeat' is designed for that specific widget, the fact that it has text box always focused, only has redefined repeat count option, having to **use your mouse** to click that not-so-obvious 'play' trigger button, only viable in 'translate mode', I suggest we make it a standalone shortcut.

**Comment by niksedk** [comment]
>The current 'AUTO Repeat' is designed for that specific widget, the fact that it has text box always focused, only has a couple predefined ‘repeat count’ options, having to use your mouse to click on that not-so-obvious 'play' trigger button...

It also works with go to prev/next subtitle (Alt+Arrow up/down).

**Comment by OmrSi** [comment]
Should be closed now?

**Comment by niksedk** [comment]
Yes, we now have three different, but each nice, ways of doing this:
* Auto repeat x times + auto continue with x delay (in translate mode) - and go to next skips earlier to next subtitle
* F5 for repeat one (custom shortcut, so it can be reconfigured)
* The new `Loop selected lines` (also support a custom shortcut)

@cyzs233: Okay with you?

**Comment by cyzs233** [comment]
Sounds great, thanks OmrSi for taking up this trouble👏
