### ISSUE TITLE
[Feature Request] Option to use center channel for audio/waveform

### ISSUE THREAD

**Issue by shanedk** [SubtitleEdit/subtitleedit#6141]
In most videos that are mixed in 5.1 or 7.1 audio, the center channel is generally where the dialogue lives. When one is transcribing subtitles, a lot of times noises and music mixed in the other channels can obscure the audio. Being able to use the center channel for the waveform and for audio playback can make this much clearer for transcribers.

**Comment by niksedk** [comment]
This has actually been on my to-do list for a long time. 
I know some people convert media files to only have center audio, before starting SE.

Does this cmd line work for you? (I use ffmpeg 5.1 from here: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip )
```` 
ffmpeg -i input.mkv -af "pan=mono|c0=FC" out_pan2.wav



Commets anyone? @qwerty12 ?

**Comment by qwerty12** [comment]
> Commets anyone? @qwerty12 ?

Sorry, I don't actually know anything about ffmpeg, so I can't offer any comments on the command... But after digging out a hard drive with the only file I have with 6-channel audio, I can confirm that with ffmpeg version N-107767-g7158f1e64d-20220812 (https://github.com/yt-dlp/FFmpeg-Builds) the command does extract the center channel successfully according to my quick tests with Audacity

**Comment by niksedk** [comment]
@qwerty12: OK, and thx for testing :)
It did take some time to find the command!

**Comment by niksedk** [comment]
@shanedk: SE could automatically use the "center" channel for waveform + audio-to-text for 5.1/7.1... but that would not play the video with center track only. To do that, SE would need to encode a new video with only center track. 
So SE could offer encoding a new video when encountering 5.1/7.1 audio - or just use this for waveform/audio-to-text? Or Both?
Other ideas?

@OmrSi or @LeonCheung  ?

**Comment by OmrSi** [comment]
@niksedk I just thought of something but I don't know if it's possible.
Could the center channel be added as an extra audio track?
That way the user could switch between using the center track and not.

In MPV, you could extract the center audio then load it as an external audio track.
That would be easier than encoding a new video, I would think.
As I said, I do not know how applicable this is, just brainstorming.

**Comment by niksedk** [comment]
Added in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/185986891-357ff971-1e1d-48ca-838a-3f980026cbf5.png)

**Comment by niksedk** [comment]
Note: Only mpv supports this during play.

**Comment by shanedk** [comment]
> To do that, SE would need to encode a new video with only center track.

It does seem like a lot to go into. It would be worth it if it could be done simply. Otherwise, the way OmrSi said would be the way to go: play the extracted channel as an alternate audio track. I don't know much about the other video players, but I know VLC supports it.

**Comment by niksedk** [comment]
When using mpv this will work during normal play - mpv can play only front center audio channel :)
Waveform/Audio-to-text does not depend on video player (but requires ffmpeg).

**Comment by niksedk** [comment]
It would probably be nice with some kind of visual indicator that SE is using FC audio channel only ?

**Comment by OmrSi** [comment]
@niksedk Maybe a text like `SMPTE` next to the video duration would be enough?

**Comment by niksedk** [comment]
It's now slightly visible when SE is using only "Front Center audio channel":

![image](https://user-images.githubusercontent.com/1261331/187990399-5640c203-85ac-4e0c-8ac1-127852ae5923.png)
