### ISSUE TITLE
Fix Common Errors ERROR + Don't remove BLEEP

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#6142]
When using Fix Common Errors a new problem has occured this season.
Some subtitlers has started to use:

" - Vad står på? (italics ON)- Det är Jimmy.(italics OFF) "

And then SE wants to:

Remove dialog dashes in single lines

Which probably are due to the 

(italics ON) (italics OFF)

and instead turn the line into:

Vad står på? (italics ON)- Det är Jimmy.(italics OFF)

But that's wrong since there are Two Persons speaking.

===========

And the:

Remove text for hearing impaired

should NOT remove

[Bleep]

or any kind of BLEEP anywhere, it could instead be an option if one wants SE to Remove Bleeps or not.
Since without Bleep certain sentences won't make sense at all, so they should mostly be kept!

**Comment by niksedk** [comment]
Could you attach a subtitle?

**Comment by Minherre** [comment]
In this sub it's on line 669.
In some subs there are plenty of the same type of writing, depe
[For.All.Mankind.S03E10.Stranger.In.A.Strange.Land.720p.ATVP.WEB-DL.DDP5.1.H.264-NTb_track38_[swe].zip](https://github.com/SubtitleEdit/subtitleedit/files/9330883/For.All.Mankind.S03E10.Stranger.In.A.Strange.Land.720p.ATVP.WEB-DL.DDP5.1.H.264-NTb_track38_.swe.zip)
nds on the translator.

**Comment by Minherre** [comment]
Yet another Sub with the same problem (Remove dialog dashes in single lines) on Lines 483 and 495, where it also wants to 'Fix dialogs on one line'.

But in both cases there are Two Different Persons speaking, so it should not be 'fixed' at all.

[Better.Call.Saul.S06E13.Saul.Gone.720p.NF.WEB-DL.DDP5.1.x264-NTb_track21_[swe].zip](https://github.com/SubtitleEdit/subtitleedit/files/9356432/Better.Call.Saul.S06E13.Saul.Gone.720p.NF.WEB-DL.DDP5.1.x264-NTb_track21_.swe.zip)
