### ISSUE TITLE
To which path is the ffmpeg file downloaded? I cannot find it. And everytime the version is updated, I need to re-download ffmpeg. 

### ISSUE THREAD

**Issue by nissansz** [SubtitleEdit/subtitleedit#6143]
To which path is the ffmpeg file downloaded? I cannot find it. And everytime the version is updated, I need to re-download ffmpeg. 
Is it possible to directly copy from old version to new version?
Please tell the ffmpeg storage path to make it work.

**Comment by niksedk** [comment]
[SE-data-folder]\ffmpeg\ffmpeg.exe

you can find the `SE-data-folder` by pressing Ctrl+Shift+Alt+D in the SE main window. 
Notice that ffmpeg is also updated regularly, so it's good idea to re-download it when a new SE version is out.

**Comment by nissansz** [comment]
I found it in settings. And copied it to new version.
![image](https://user-images.githubusercontent.com/41010669/184524347-c1858e59-aded-4dba-b179-5f829cd011f2.png)

**Comment by niksedk** [comment]
It's still good to update... ffmpeg 4 is way slower than ffmpeg 5.
SE uses the release build from here: https://www.gyan.dev/ffmpeg/builds/ (currently version 5.1)
