### ISSUE TITLE
There is one bug for shortcut "Go to previous line and play" when the current line is line 2, on line 2, the shortcut does work if you want to go to line 1.

### ISSUE THREAD

**Issue by nissansz** [SubtitleEdit/subtitleedit#6144]
There is one bug for shortcut "Go to previous line and play" when the current line is line 2, on line 2, the shortcut does work if you want to go to line 1.

**Comment by nissansz** [comment]
How to effect this change on the portable version? Wait for next release?

**Comment by niksedk** [comment]
You can compile your own version, wait for next final, wait for next beta or try this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SE367-dotnet-6.zip (requires dotnet 6 probably)
