### ISSUE TITLE
[Suggestion, Request Feedback] During OCR, allow overriding language/dictionary on a per-line basis

### ISSUE THREAD

**Issue by dakotahawkins** [SubtitleEdit/subtitleedit#6146]
Working on OCR for a movie that's 99% English but does include untranslated (in the movie) Spanish lines, e.g. song lyrics.

It would have been _really_ helpful to be able to tell SE that certain lines should use a Spanish dictionary instead of an English one. Otherwise each switch means an abort, manual switch, run, abort, manual switch back, run.

Feedback request: Regardless of how important this would be to whoever reads this, how feasible is it? If it might not be that bad I wouldn't mind taking a look.

Edit: If it would require a major refactor of some sort, I'm happy to close this as impractical :)

**Comment by niksedk** [comment]
I've added this in latest beta... but only for nOCR - What OCR method are you using?

**Comment by dakotahawkins** [comment]
@niksedk To be honest I was trying a bit of everything, the font was pretty problematic. I haven't finished with it yet so I'd be happy to try it out in the beta! Is there a better place to put discussion about that?

**Comment by niksedk** [comment]
Here is fine... beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip
