### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Technogeek20** [SubtitleEdit/subtitleedit#6147]
![Error](https://user-images.githubusercontent.com/111253201/184557700-3c61def7-fbcb-4799-9490-a49a5c41b64e.png)

Hello, i'm new to the entire thing.. and seeing as i've probably scoured (I could have missed something, if i did let me know) but, i've been plagued by this error that you see.. can anyone identify?

**Comment by darnn** [comment]
This is a total guess, but can you try placing the file outside of a temp folder? Just, like, in c:\workfiles or something simple like that?

**Comment by Technogeek20** [comment]
> This is a total guess, but can you try placing the file outside of a temp folder? Just, like, in c:\workfiles or something simple like that?

Where do I find the .WAV file btw? Cause I'm looking at it now and I do not see it

**Comment by niksedk** [comment]
@Technogeek20: Did you install ffmpeg via SE? Perhaps try re-downloading ffmpeg could help?
Does this happen with all video files or only some?

**Comment by Technogeek20** [comment]
> @Technogeek20: Did you install ffmpeg via SE? Perhaps try re-downloading ffmpeg could help? Does this happen with all video files or only some?

Afaik, it happened with one of the MP4 videos, until I did something to make it work (that happened last night) then today, when trying to get some subtitles out an mkv file.. that error popped up.. and I did download ffmpeg via subtitle edit.. and I'll give it a try later

**Comment by niksedk** [comment]
This error occurs when no audio file could be extracted by ffmpeg... are you sure the video has audio?

**Comment by Technogeek20** [comment]
> This error occurs when no audio file could be extracted by ffmpeg... are you sure the video has audio?

Yeah, the video has audio.. it can be an mkv, or MP4.. still would not extract

**Comment by niksedk** [comment]
Could you e-mail me a link to a file that does not work for you?

Or you can try via ffmpeg in cmd line: `ffmpeg -i "input.mkv" -vn -ar 16000 -ac 1 -ab 128 -af volume=1.75 -f wav "output.wav"`

**Comment by Technogeek20** [comment]
Sorry that i took long to respond..

should i send link via MEGA? Or Gmail? And i'll give the CMD Line a try

**Comment by niksedk** [comment]
Sure, MEGA should work, you can send the link in email if the video is not public.

**Comment by niksedk** [comment]
Yes, thx.
All three files works fine for me...

**Comment by Technogeek20** [comment]
> Yes, thx. All three files works fine for me...

Well... That's weird... And two questions: do I access the CMD prompt via ffmpeg? And do I possibly need a .DLL file in order for it to work? Cause, as far as I know, that usually helps when programs don't work

**Comment by niksedk** [comment]
You use ffmpeg via a command prompt.
No, ffmpeg.exe is a full program that contains all it needs.

**Comment by niksedk** [comment]
@Technogeek20: 
Have you found a solution?

It seems the problem has occurred again: #6193
Any input on this? https://github.com/SubtitleEdit/subtitleedit/issues/6193#issuecomment-1235198457

**Comment by Technogeek20** [comment]
Hello.. and.. (sorry to burst your bubble) I have not found a solution to
the SE error.. I tried the beta, and found nothing.. sorry I did not answer
you via github, so I hope this I'll do.

**Comment by niksedk** [comment]
@Technogeek20: thx for testing :)

Could you try this in a command line with one of the files that does not work for you?
`ffmpeg -i "input.mkv" -vn -ar 16000 -ac 1 -ab 128 -af volume=1.75 -f wav "output.wav"` ?

And what does `ffmpeg -version` say?

**Comment by niksedk** [comment]
Probably a VLC issue: https://github.com/SubtitleEdit/subtitleedit/issues/6193#issuecomment-1242330939
