### ISSUE TITLE
OCR image is blank, does not load up subtitles

### ISSUE THREAD

**Issue by LisbonMapping** [SubtitleEdit/subtitleedit#6150]
Attempting to load up an image-based subtitle file to OCR into text-based subtitles, I'm met with this no matter what combination of transparencies I select (and attempting to save the image just returns "No image!")
![image](https://user-images.githubusercontent.com/111280036/184619168-8d9937e6-09dc-4c18-a800-2dc6976ed152.png)

When I right-click the black space and select image pre-processing, this error shows up. 
![image](https://user-images.githubusercontent.com/111280036/184619285-d418c4b4-cfd4-4497-87f8-34efbd4b18d0.png)

Not sure what the issue is, this is a bit beyond me. Clicking "Start OCR" obviously does nothing. The subtitles definitely should exist, as they exist when I watch the mp4 file they're contained in.

**Comment by LisbonMapping** [comment]
Ok, I updated to the latest version and that didn't fix the issue but I just ended up sourcing another version of the movie which also had those subs and it's letting me OCR that now.

**Comment by darnn** [comment]
If it's possible, I still think it would be a good idea for you to upload the subtitles that are causing the error, so that a general fix for it might be made.

**Comment by niksedk** [comment]
I do think the error has been fixed... try latest SE version.
