### ISSUE TITLE
Export Custom Text Format / Sharing with others

### ISSUE THREAD

**Issue by chocolate-elvis** [SubtitleEdit/subtitleedit#6160]
Love tha app, thank you!

I wrote a custom text format to handle a specific amazon prime video DFXP file in SE v3.6.6 and want to share this format with the team. I wrote up an elaborate document on how to duplicate the steps I did to create it, and of course as expected, some folks are missing a step here and there - we're all human. But wondering other than doing a dumpster dive and hacking the Settings.xml file, (in the Settings.xml file you can grab the text from <ExportCustomTemplates>  to </ExportCustomTemplates> and paste that) is there another, easier way to interchange this format with my team? Thanks for your help!

**Comment by niksedk** [comment]
Do you know C# ?

We could add the format to the build-in formats in SE - like the 300+ files here: https://github.com/SubtitleEdit/subtitleedit/tree/master/src/libse/SubtitleFormats

If you could you attach the custom format def + one or two sample files. It's probably a minor adjustment of some of the other TTML formats, right?
Anything special about this format?

**Comment by chocolate-elvis** [comment]
I don't know c#, but I can give it a try.
The DFXP isn't anything remarkable by any stretch, just some specific XML formatting (snowflake'd timed text is still popular). Thanks for the link and I'll give it a go.

**Comment by chocolate-elvis** [comment]
Oh, apologies, one last question. What's the best way to test a .cs file in S.E to see if it works?

**Comment by niksedk** [comment]
Copy one of the existing dfxp subtitle formats, give it a name, add that name here: https://github.com/SubtitleEdit/subtitleedit/blob/master/src/libse/SubtitleFormats/SubtitleFormat.cs#L38

Compile SE with build_beta.bat (probably requires git for windows + visual studio community edition).

I can also add this format if you have trouble.

**Comment by niksedk** [comment]
If you attach one or two sample files - I can try to add the format...
