### ISSUE TITLE
"Rambo First Blood Part II (UHD)" -- doesn't ingest subs

### ISSUE THREAD

**Issue by Rumourd** [SubtitleEdit/subtitleedit#6169]
This is the only time this has occurred.  The program spends no time ingesting it (instead of the usual minute or two to read the huge MKV file), then brings up the OCR conversion/grid screen, and all the subtitle lines are blank - nothing to convert.

Again, this is the only time I've encountered this.

I then updated to 3.6.7, but the problem persists.  The only subs on the disc that import properly are the German/French FORCED subs.  Everything else -- blank.

**Comment by niksedk** [comment]
Could you post or email a sample ?
