### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by seriousam** [SubtitleEdit/subtitleedit#617]
Using the latest portable version, windows 7 64x, klite codec pack.

All I'm trying to do is to "adjust all times to show earlier/later" +1second.
When I save the changes using "save as", it asks me weather I want to over-right  the original file, I select yes but nothing happens. When I open the movie, the subtitles are not adjusted.
After saving, If I open the same .srt file using SE, the subtitles are adjusted (+1second), but when I open the same .srt file using notepad, the subtitles are not adjusted.

I also noticed, that if I try to save in a different directory (for example in desktop), the program saves the file without any errors, but no file is generated(I don't see the saved file). If I try to save again at the same directory, it says that there is already a file there, but I don't see it! 
I tried "show hidden files and folders", "show system files" but still I can't see the file..

**Comment by niksedk** [comment]
I cannot re-create anything about not saving after adjusting all times... neither with save or save as.

If the file is in use, you will get an error like this:
The process cannot access the file 'video.en.srt' because it is being used by another process.
