### ISSUE TITLE
First part of text returned on some lines missing in Japanese audio to text 

### ISSUE THREAD

**Issue by coastal45** [SubtitleEdit/subtitleedit#6171]
When doing audio to text using Japanese big model, text for the first part of the spoken line will be missing.
Example is attached.
If you listen and check the waveform and text around line 7, you can see the waveform and hear "wakanaideshou".
However, in the returned text, you only get back "でしょ" (deshou). So first part is clearly missing.
This seems to occur in about one line every 5 minutes, so it seems rather common issue.

I don't know the mechanism that transfers the audio to vosk, or vosk returned text to SE, but I wonder if some clipping is is involved. Maybe a timing or delay issue?
Is there any way to investigate this from SE point of view?
[clip audio.zip](https://github.com/SubtitleEdit/subtitleedit/files/9396686/clip.audio.zip)

**Comment by niksedk** [comment]
I thinks it's a Vosk/Kaldi issue - you can try using selected line in SE via context menu 

![image](https://user-images.githubusercontent.com/1261331/185995868-9234e4d3-152d-4b5d-9c12-b2df97ee1d3a.png)

See https://www.youtube.com/watch?v=RlJVIjYGreI

**Comment by coastal45** [comment]
The individual wav file extracted only contains audio for "deshou", not the full phrase. So same result.

Presuming the wav file is what's sent to vosk, then it's natural that only "deshou" text could be returned. Is that correct?

Anyway, how is the wav segment length decided? Why is it only 11,387 - 12,387, and not ~ 10,800 - 12,387 containing the spoken phrase?

Or, is the segment 11,387 - 12,387 the only part of the audio that vosk understood (making it a vosk issue)?

![Screenshot from 2022-08-22 17-18-50](https://user-images.githubusercontent.com/102390147/186042186-6828e9a0-736d-458b-816b-f8a130cd7930.png)

**Comment by niksedk** [comment]
Yes, it must be an issue with the model.

**Comment by coastal45** [comment]
Thanks. I'd like to take up this issue with vosk people, but if I could ask at first:

Is there any way to check this action outside of SE that you know of?

Could you confirm my idea on related actions in SE?
1. Audio extracted as wav format.
2. Audio run through vosk api.
3. Where vosk can match text, text and timing returned to SE.
4. SE places text timed in the resulting srt.

And finally, does SE only support wav format audio? I wonder if different format/sampling might make some difference.
And does SE use left channel or right channel in case of stereo sound?

**Comment by niksedk** [comment]
The four steps are correct.
SE extracts the wave file, then passes the wave file to Vosk, and receives words with time codes.

SE extract the audio with all channels mixed (except for this case: https://github.com/SubtitleEdit/subtitleedit/issues/6141 )
I do not think higher sample rate will give any differences.
