### ISSUE TITLE
MS Word spell check default language

### ISSUE THREAD

**Issue by jdbigguy** [SubtitleEdit/subtitleedit#6172]
Spell and grammar check in MS Word plug-in defaults to English (United States). Can the default language be changed?
![Image3](https://user-images.githubusercontent.com/111851481/186103501-e551553d-8b85-4542-a4b5-69626167df4b.jpg)

**Comment by eladkarako** [comment]
M$ 0ff!ce ole communication isn't language specific,  
it will use all the languages you currently have installed in the Office program,  
some language packs comes with spell check, some have additional grammar. make sure you have office that not only has language pack but grammer and spellcheck pack as well. you can google it and its free.

you can adjust some switches in your office to see if it changes anything. 
https://webcache.googleusercontent.com/search?ie=UTF-8&q=cache:support.microsoft.com%2Fen-us%2Foffice%2Fcheck-spelling-and-grammar-in-a-different-language-667ba67a-a202-42fd-8596-edc1fa320e00  
https://web.archive.org/web/20220408003920/https://support.microsoft.com/en-us/office/check-spelling-and-grammar-in-a-different-language-667ba67a-a202-42fd-8596-edc1fa320e00

**Comment by jdbigguy** [comment]
> M$ 0ff!ce ole communication isn't language specific, it will use all the languages you currently have installed in the Office program, some language packs comes with spell check, some have additional grammar. make sure you have office that not only has language pack but grammer and spellcheck pack as well. you can google it and its free.
> 
> you can adjust some switches in your office to see if it changes anything. https://webcache.googleusercontent.com/search?ie=UTF-8&q=cache:support.microsoft.com%2Fen-us%2Foffice%2Fcheck-spelling-and-grammar-in-a-different-language-667ba67a-a202-42fd-8596-edc1fa320e00 https://web.archive.org/web/20220408003920/https://support.microsoft.com/en-us/office/check-spelling-and-grammar-in-a-different-language-667ba67a-a202-42fd-8596-edc1fa320e00

Hello and thanks for your reply. That partially worked, but as you can see it still defaults to English (US). The difference is that all the non-English languages have gone, and now I have a bunch of versions of English. Do you have any other ideas
![2022-08-24 01_11_41-Greenshot](https://user-images.githubusercontent.com/111851481/186295607-55ed3d85-00e3-4dc7-b9cf-09a50377520e.jpg)
?

**Comment by jdbigguy** [comment]
> M$ 0ff!ce ole communication isn't language specific, it will use all the languages you currently have installed in the Office program, some language packs comes with spell check, some have additional grammar. make sure you have office that not only has language pack but grammer and spellcheck pack as well. you can google it and its free.
> 
> you can adjust some switches in your office to see if it changes anything. https://webcache.googleusercontent.com/search?ie=UTF-8&q=cache:support.microsoft.com%2Fen-us%2Foffice%2Fcheck-spelling-and-grammar-in-a-different-language-667ba67a-a202-42fd-8596-edc1fa320e00 https://web.archive.org/web/20220408003920/https://support.microsoft.com/en-us/office/check-spelling-and-grammar-in-a-different-language-667ba67a-a202-42fd-8596-edc1fa320e00

Hello and thanks for your reply. That partially worked, but as you can see it still defaults to English (US). The difference is that all the non-English languages have gone, and now I have a bunch of versions of English. Do you have any other ideas
![2022-08-24 01_11_41-Greenshot](https://user-images.githubusercontent.com/111851481/186295607-55ed3d85-00e3-4dc7-b9cf-09a50377520e.jpg)
?

**Comment by jdbigguy** [comment]
In case it wasn't clear, this only happens with the "spell and grammar check in microsoft word..." option of SE. If I use "Spell Check" option, then it goes straight to the English UK option.
