### ISSUE TITLE
Corrupted images when ripping DVD subtitles

### ISSUE THREAD

**Issue by gandbg** [SubtitleEdit/subtitleedit#6176]
I'm trying to rip the VobSub subtitles from a DVD-Video but a lot of the extracted images are corrupted making impossible to figure out any character.

Here are some samples:

https://user-images.githubusercontent.com/62039938/186277441-97de0338-93e5-4808-bd21-ea2ca6fded40.mp4

I'm using the latest version of Subtitle Edit (3.6.7)

---

EDIT: While this issue gets sorted out you can try this:
1. Make a copy-protection-free 1:1 copy of your DVD (you can use [DVDFab DVD Copy](https://www.dvdfab.cn/dvd-copy.htm), [DVDFab All-in-One](https://www.dvdfab.cn/all-in-one.htm) or any software capable of doing this)
2. Mount the created ISO file (Double-click or Right click > Open with > File Explorer)
3. Inside Subtitle Edit choose the desired IFO file from the mounted ISO (it will apear as a DVD)
4. When you are done, un-mount the ISO with Right click > Eject

**Comment by niksedk** [comment]
Could you post or email a sample ?

**Comment by gandbg** [comment]
Here you are.

![Image4](https://user-images.githubusercontent.com/62039938/187046002-71a4bb4e-7c28-428b-b6a6-a9a53140d331.png)
![Image6](https://user-images.githubusercontent.com/62039938/187046006-34112a94-0b12-4d4c-b70e-bc575779c58f.png)
![Image7](https://user-images.githubusercontent.com/62039938/187046007-83c18727-9d86-4b6c-a1bc-9b97b9e0c516.png)

**Comment by niksedk** [comment]
Could you post or email a sample of the input file?

**Comment by gandbg** [comment]
Oh, yeah... sorry for the misunderstanding.

[VTS_01_1.VOB.zip](https://github.com/SubtitleEdit/subtitleedit/files/9438813/VTS_01_1.VOB.zip)
[WINX2_RN.ISO.zip](https://github.com/SubtitleEdit/subtitleedit/files/9438818/WINX2_RN.ISO.zip)

I doubt it will help you since trying to rip the subtitles from this ISO file, Subtitle Edit was able to extract everything perfectly so i imagine that might be problem specific to my DVD (to extract the sample i've used [DVDShrink](https://www.videohelp.com/software/DVD-Shrink) that does a little bit of re-encoding).

I can upload a full 1:1 copy of the DVD if that's necessary.

**Comment by niksedk** [comment]
Works fine here, so I probably need the 1:1 copy...

**Comment by gandbg** [comment]
Here's the 1:1 copy with the copy protection removed to allow for playback

[WINX2_RN.iso.7z](https://transfer.sh/vbEGoO/WINX2_RN.iso.7z)

I'm starting to think that the problem might be the copy-protection itself, but i can't send you a "pure" copy-protected ISO of the DVD otherwise you won't be able to do anything because... it's copy-protected.

According to DVDFab this DVD uses [CSS](https://en.wikipedia.org/wiki/Content_Scramble_System), [RC](https://en.wikipedia.org/wiki/Regional_lockout) and [UOP](https://en.wikipedia.org/wiki/User_operation_prohibition) protection

**Comment by niksedk** [comment]
Thx for the file :)

If I open the "VTS_01_0.IFO" file I do not get any garbled images... does that work for you too?

**Comment by niksedk** [comment]
OK, thanks for the info and file - good to know :)

I no longer have my old dvd collection to test on, so I hope people can live with the solution to remove copy protection before ripping subtitles with SE.
