### ISSUE TITLE
Error: GT Screen-Scraper

### ISSUE THREAD

**Issue by alfanegativo** [SubtitleEdit/subtitleedit#6182]
this plugin no longer works and the translation is better with it

![Captura de Tela (40)](https://user-images.githubusercontent.com/112188752/186936666-239a0145-48f6-4fa8-912f-537bf7e27336.png)

**Comment by niksedk** [comment]
It works fine here... you might be missing some component from Windows (something related to Microsoft Edge).
This plugin uses this Browser control: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/webview 

Probably also a plugin issue: https://github.com/SubtitleEdit/plugins
