### ISSUE TITLE
Graphical way to adjust subtitle offsets

### ISSUE THREAD

**Issue by layoutanalysis** [SubtitleEdit/subtitleedit#6188]
When I download subtitles for videos, I often notice that they are offset, i.e. ahead or delayed compared to the sound of the video. I'm aware that SubtitleEdit offers a numeric way to specify the offset, but finding out the correct value can often be cumbersome. 

I wonder whether there could be a graphical way to correct subtitle offsets like in the mockup below, where the subtitles are represented by pink bars that are dragged towards the pink line:
![image](https://user-images.githubusercontent.com/32068685/187089005-ad1dece6-0dc9-4c7c-80e8-ad2f171aeec4.png)

**Comment by OmrSi** [comment]
Doesn't going to the video position and using the offset shortcut work well for you?

**Comment by niksedk** [comment]
Mouse single click+Ctrl+Shift will set of start selected line + offset all lines after selected line (keeping duration) 
See https://www.nikse.dk/subtitleedit/help#waveform

As OmrSi mentioned, also do check the shortcuts in Options - Settings - Shortcuts (search for "offset")
