### ISSUE TITLE
SPLIT lines after certain words/characters

### ISSUE THREAD

**Issue by Slopz** [SubtitleEdit/subtitleedit#6189]
I've been looking around but haven't found a way to split lines after certain predefined characters/words. The closest I've gotten was find and replace adding a line break, but that's not what I'm looking for. 

Example: 
![image](https://user-images.githubusercontent.com/39817415/187342061-22e4231c-197f-4c86-b7de-57c868dc9835.png)

So I'm looking for the ability to split the lines like shown

Is that possible in the current version of SE? Is there perhaps a way to split the lines the same way you'd add a line break using find and replace?

**Comment by LeonCheung** [comment]
Hmm, reminds me of something like #4531.
