### ISSUE TITLE
SE 3.6.7 beta 81: Error after MPV update

### ISSUE THREAD

**Issue by GrampaWildWilly** [SubtitleEdit/subtitleedit#6192]
It had been a while since I had updated my version of MPV so I decided to do that just now.  All seemed to go fine.  It said the new version was ready to use.  It prompted me saying I needed to close & reopen SE in order to use the new mpv.  I did that.  Now I'm getting the error you can see in the attached image.  It pops up twice so it needs to be dismissed twice.  It's quite annoying, too, because until I do dismiss it, it sits on top of any task window I might switch to.  Video playback is now impossible with MPV.  Fortunately, VLC still works as the video player.  But seems to me Nik told me once MPV was preferable, although I forget his reasons now.  This doesn't appear to have been previously reported.

![#01](https://user-images.githubusercontent.com/75588964/187559648-bd3067a0-4461-46e4-8aa0-cca744419a4d.jpg)

**Comment by GrampaWildWilly** [comment]
I noticed there was a new beta that went up just a few hours ago.  This is still happening with beta 105.

**Comment by niksedk** [comment]
What OS are you using?
Latest mpv might has dropped support for older Windows versions...

mpv is more precise and has better seeking than VLC (visible when using the waveform) and mpv has on video preview (better position support).

**Comment by GrampaWildWilly** [comment]
Windows 7 64-bit.  I will go check the MPV web site.  Hang on . . .

It seems there's this guy named Shinchiro who makes builds of MPV.  There is recent activity in his Github support forum that mentions Windows 7 & it looks to me like it is still supported.  It also looks like he's creating new versions all the time.  Maybe the place you're taking MPV from isn't the place where he's putting up his builds.  I don't know.  I'm guessing.  In the hopes I might get one of those recent builds, I just now again tried the button in the SE settings for getting a new MPV lib.  Didn't fix the problem.

If you want to implement some experimental code in a beta that gets one of Shinchiro's builds of MPV, I'd be willing to try it.  Maybe my test will show you should be getting MPV from him instead of . . . wherever.

**Comment by niksedk** [comment]
SE already uses mpv builds from shinchiro :)
You can try different dll files from: https://sourceforge.net/projects/mpv-player-windows/files/libmpv/
Be sure to use files that starts with `mpv-dev-x86_64`... you might have find an old version!
Let me know how it works out.

**Comment by niksedk** [comment]
Actually, I've added latest mpv by shinchiro to the automatic SE download - does that work for you?
( https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-v3-20220829-git-211ce69.7z/download )

**Comment by niksedk** [comment]
The new mpv/SE at least work on one Windows 7 64-bit machine :)

**Comment by GrampaWildWilly** [comment]
Make that two!  Maybe he had one strange build & lucky us, that's the one we were getting.  The one you've put up now works for me.  It used to show a version number in the bottom right corner of the video window.  But now I'm seeing Libmpv 2.0, which is the same as what it said before I tried the update for the first time yesterday.  Doesn't he put a unique release number on every build?  I think it would be reassuring to see that number change whenever you get a new version.  If it doesn't change, then you know you already had the latest one.  A minor quibble.  I'm just happy MPV is working again in SE.  Thanks for doing something about this.

**Comment by niksedk** [comment]
When I update mpv (about every 1-2 months) I naturally test the dll file with SE before I activate it ( by uploading it to https://github.com/SubtitleEdit/support-files/ ).

Sorry, mpv does not increment the version number very often - that would have been nice though.

Yes, https://sourceforge.net/projects/mpv-player-windows/files/libmpv/ always has the latest version on top.
