### ISSUE TITLE
Requested improvement: Fullscreen isn't really fullscreen

### ISSUE THREAD

**Issue by GrampaWildWilly** [SubtitleEdit/subtitleedit#6194]
When I have MPV set as my video player & it is open in not fullscreen, it looks like this:

![#01](https://user-images.githubusercontent.com/75588964/187660058-70cd0d7f-f807-442f-949a-5985f0f40265.jpg)

You have the Windows title bar at the top.  The other 3 sides show the window borders.  There's 2 vertical black bars on the sides.  The bottom of the window is taken up by the usual player controls & a progress bar.

When I Alt+Enter to toggle into fullscreen, it looks like this:

![#02](https://user-images.githubusercontent.com/75588964/187660350-dc16f636-a50f-44b2-9c55-48919ef8750f.jpg)

The title bar at the top & the window borders on the other 3 sides are gone.  This is good.  But the 2 vertical black bars on the sides are still there, although they are a bit narrower.  And the area that had been occupied by the player controls is now just a gray rectangle.  That space isn't reclaimed.

Going through the same exercise with VLC . . .

![#03](https://user-images.githubusercontent.com/75588964/187660709-b66241e4-de6a-4f45-a737-7c3c1e6ebf5b.jpg)

Very much the same as for MPV except for the positioning of the caption.  With MPV, the caption occupies space within the video image.  With VLC, the video image is smaller by enough to leave a black stripe across the bottom in which the caption appears.

Toggling Alt+Enter with VLC . . .

![#04](https://user-images.githubusercontent.com/75588964/187661334-e226b716-6ff6-4cae-9d83-5fd99e72ce11.jpg)

This is not much changed from the non-fullscreen VLC view, and is somewhat worse than the MPV fullscreen view because the image occupies less of the screen.

My request is to make the fullscreen image occupy the full 1920x1080 aperture of my monitor with both MPV & VLC.  I know for at least VLC playing on its own outside SE, fullscreen really fills the full screen.  So my suspicion is SE is doing something to waste space on my screen that I wish were devoted to an image that would actually occupy the full screen.

**Comment by niksedk** [comment]
SE can't make VLC work the way you want, as VLC does not have the same sub load functionality as mpv.

Also, SE will keep the aspect ratio, so black bars may occur.
I will look into the mpv fullscreen issue and see if it's easily fixable...

**Comment by GrampaWildWilly** [comment]
OK.  One more thing that makes MPV better for our purposes here than VLC.  I can accept that.

You should know, however, that the particular source video I'm showing in my sample images above happens to be 1920x1080.  So there shouldn't be any need for black bars with that one.  I do have some stuff that is of lower resolution & I could understand the black bars there.  But this one really shouldn't have the black bars.  If you can make it do something better, great.  If not, I'll accept it.  You certainly know more about this than I do.

**Comment by GrampaWildWilly** [comment]
BRILLIANT!  In beta 110, MPV in fullscreen is now really fullscreen.  VLC, as expected, still is not & I understand it's not possible.  But I use MPV so I don't care about VLC.  Such great service!  Things we pay a lot for generally don't match up to SubTitle Edit.  Thanks, Nik!

**Comment by OmrSi** [comment]
Honestly. Nik's support for this program is one of a kind.

**Comment by GrampaWildWilly** [comment]
I've noticed your contribution here, Omar, has been considerable.  I could be coaxed into flipping a morsel of thanks your way, too.
