### ISSUE TITLE
Mp3 Lyrics without end time

### ISSUE THREAD

**Issue by lollita** [SubtitleEdit/subtitleedit#6214]
Do it is possible to edit and save Mp3 Lyrics without end time?

**Comment by darnn** [comment]
You should probably post an example of the format.

**Comment by lollita** [comment]
[00:10.10]My baby don't care for shows
[00:13.92]My baby don't care for clothes
[00:19.27]My baby just cares for me

**Comment by darnn** [comment]
Then yes, it can. This appears to be an LRC file, at least that's what SE recognizes it as. So just open an actual LRC file using the program, or copy its contents into a TXT file and open that one.

**Comment by lollita** [comment]
I know but the problem is that when I save I get empty row for end time:
[00:10.10]My baby don't care for shows
[00:10.30]
[00:13.92]My baby don't care for clothes
[00:14.00]
[00:19.27]My baby just cares for me
[00:19.50]

**Comment by darnn** [comment]
In that case, can you upload a sample file of what you start out with, and a sample of how it's saved improperly? Just rename the files to .txt and you can attach them here.

**Comment by lollita** [comment]
It happens when I use "Set & go to next" button.
[ORG Nina Simone - My Baby Just Cares For Me.lrc.txt](https://github.com/SubtitleEdit/subtitleedit/files/9484176/ORG.Nina.Simone.-.My.Baby.Just.Cares.For.Me.lrc.txt)
[Nina Simone - My Baby Just Cares For Me.lrc.txt](https://github.com/SubtitleEdit/subtitleedit/files/9484177/Nina.Simone.-.My.Baby.Just.Cares.For.Me.lrc.txt)

**Comment by darnn** [comment]
Hm, you're right, there are issues with the way SE reads and writes these. If I take your original file, open it, change the timing slightly and save it, and then open it again, it opens all wrong:
![se lrc](https://user-images.githubusercontent.com/19672444/188302189-0e9a4bbe-4763-4c32-8479-f92b754abcd2.png)

**Comment by niksedk** [comment]
The timing has changed due to the offset...

I do not get the empty rows for end time - how can I re-produce that?

**Comment by lollita** [comment]
[Here](https://interno.altervista.org/temp/sEdit.mp4) step to reproduce.

**Comment by niksedk** [comment]
> [Here](https://interno.altervista.org/temp/sEdit.mp4) step to reproduce.

That's is how SE works...  try using only a "set start time" shortcut.

I could make an "LRC without end-time" format, which when saving would omit end-time - would that help? 
Well, it is now included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/188312511-966c9f56-a683-4b36-a16f-32955cc98a10.png)

**Comment by lollita** [comment]
It work fine now.
But also have warning uselesse in the context:
"Subtitle contains negative duration in line(s): 1, 2, 3, 4, 5"
"Subtitle contains negative time codes. Continue with saving?
Lines found: 0, 1, 2, 3, 4"

**Comment by niksedk** [comment]
Thx for the info - hopefully removed the "negative duration" message: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by lollita** [comment]
Ty.

**Comment by niksedk** [comment]
Thx for verifying and testing :)
