### ISSUE TITLE
VobSub sutitles placed on top-right

### ISSUE THREAD

**Issue by mzeddd** [SubtitleEdit/subtitleedit#6219]
I'm trying to put subtitles on top-right position, but it seems like not possible.

When I set aligment = right, I see that text is placed on bottom-right position. When I'm trying to lift it up it is moving up and to the letf.
Shift to the left increases when I move text higher.

Is this done on purpose or this is the bug?

Thanks.

**Comment by niksedk** [comment]
In the main list view, you can set the alignment for selected lines, via the context menu:
![image](https://user-images.githubusercontent.com/1261331/188696274-a224d734-b9c1-41c9-90e8-a650de737b5b.png)

**Comment by mzeddd** [comment]
Thank you for the answer!
