### ISSUE TITLE
Previous shortcuts stopped working after update

### ISSUE THREAD

**Issue by helipotamus** [SubtitleEdit/subtitleedit#6225]
I use keyboard shortcuts for several features (F8 for creating a new subtitle, NumPad4 to toggle pause/play, etc.). After updating the software from 3.5.15 to the most current version, all my shortcuts stopped working entirely despite still being logged correctly in the settings.

**Comment by niksedk** [comment]
Could it be this setting you need to enable?

![image](https://user-images.githubusercontent.com/1261331/188941070-2c46f7a6-4c07-4da9-8a10-7984519fa28b.png)
