### ISSUE TITLE
Typo ?

### ISSUE THREAD

**Issue by hugok79** [SubtitleEdit/subtitleedit#6229]
I don't understand code but is this okay or is a typo in the word Assa**Resolution**Changer?

https://github.com/SubtitleEdit/subtitleedit/blob/edd98287850f94678d13cb9f787f37e49334d2be/LanguageBaseEnglish.xml#L227
https://github.com/SubtitleEdit/subtitleedit/blob/edd98287850f94678d13cb9f787f37e49334d2be/LanguageBaseEnglish.xml#L236

Same in LanguageMaster.xml

**Comment by niksedk** [comment]
Thx :)

Should be fixed now.
