### ISSUE TITLE
Installer should install to "Program Files" not "Program Files (x86)"

### ISSUE THREAD

**Issue by Orvid** [SubtitleEdit/subtitleedit#623]
Currently, even though the installer defaults to installing in `Program Files (x86)`, even though this is a .net program, and runs as 64-bit on 64-bit platforms.

**Comment by ivandrofly** [comment]
@Orvid you can just replace `(x86)` from Program Files (x86) path and everything should be :+1: , by doing  your suggestion we will have to compile two different setup which isn't good idea.

**Comment by xylographe** [comment]
It should be quite simple, as there is only one program, but, unfortunately, INNO won't do this.

**Comment by ivandrofly** [comment]
:+1: @xylographe
