### ISSUE TITLE
Audio to text in greek, results to one-word subtitles

### ISSUE THREAD

**Issue by Xenos71** [SubtitleEdit/subtitleedit#6233]
Hi,

after using audio to text function on english language with very good results, I tried it on greek.
Unfortunately, things didn't go so well. For some strange reason, instead of getting subtitles with one or two lines of text, I got subtitles with just one word each.

Even when the software recognizes a full sentence correctly, instead of filling one or two lines of subs (like it does in english), it breaks it to one-word subs. This results to a whole bunch of subs with very short duration that change rapidly, displaying only one word at a time.

I couldn't find any setting that could fix this, is there something I could try or is it an actual bug?

I'll appreciate any help, thanks in advance

**Comment by niksedk** [comment]
Do you have "post processing" on?

![image](https://user-images.githubusercontent.com/1261331/189272031-b2472f0f-c281-4392-be66-056823f356b3.png)

**Comment by Xenos71** [comment]
Hello Nikolaj,

yes, it was on by default. I also tried with this off (just in case), but I got the same results, one word per sub.

**Comment by niksedk** [comment]
Do you have a small audio/video sample, so I can test?

**Comment by Xenos71** [comment]
Yes, I hope I'll manage to post the link correctly, so you can download the file:
[https://mega.nz/file/tEBEAYoT#X89ZyzyGNLozNIBjLemuJlISmyhNDr9O9xfE0Ifgtf8](url)

**Comment by Xenos71** [comment]
Yes, I hope I managed to attach the file correctly...

https://user-images.githubusercontent.com/32386964/189415312-23418a65-1130-4934-a037-6e00ab42c67a.mp4

**Comment by niksedk** [comment]
Thx for the sample file :)

Should now work better in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by Xenos71** [comment]
That's great, thank you very much!
