### ISSUE TITLE
[Request and Bug] Karaoke Effect

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#6234]
1. Kindly add support for word-level Karaoke Effect?
2. When I add the Karaoke effect to a video, the subtitles tend to flicker. Is this normal and can it be fixed?

**Comment by shanedk** [comment]
I'll second the request for a word-level effect.

**Comment by ivandrofly** [comment]
Related with https://github.com/SubtitleEdit/subtitleedit/issues/7947

**Comment by ivandrofly** [comment]
Just found another bug for example if text is like "{\an5}<i>All</i> good." the italic closing tag will not be 
included in the generation sequence!
