### ISSUE TITLE
[Bug] Uncaught exception when dictionary file has an error

### ISSUE THREAD

**Issue by NadCat1** [SubtitleEdit/subtitleedit#6240]
If an .xml file has errors (for example a name list containing something like <name>Foo<name> instead of </name>) there is an [uncaught exception ](https://prnt.sc/h8Zx4qiWaicW)when trying to fix casing or to open the batch tool. The new window has "Abort", "Retry", and "Ignore" buttons but none of them actually do anything - the UI crashes either way. The Subtitle Edit process is left running in the background.

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/189517899-319e3eef-261b-4648-9a52-2dc5c05bd552.png)

(just pasting the image)
