### ISSUE TITLE
Video player mpv not downmixing to stereo

### ISSUE THREAD

**Issue by E-t-z** [SubtitleEdit/subtitleedit#6243]
Not sure if related to Subtitle Edit, but what i have observed is, when Video Engine is set to mpv using mpv lib.
Audio is not downmixed, but rather channels are being dropped, that makes pretty much impossible to sync subtitles visually or by hearing.

Most likely, it can be rectified how that mpv lib is being called, by adding --audio-channels=stereo

**Comment by niksedk** [comment]
Can you supply a video sample?

**Comment by E-t-z** [comment]
Well, it kind of happens to all files, but you can use this as sample: https://www96.zippyshare.com/v/ssOwlIX0/file.html

It has dissapearing and reappearing dialogues as sound moves between channels, etc...
It does not happen when using VLC as video engine, but unfortunately when running SE on Crossover (Wine derivative) VLC renders black text on black background, which makes it hard to use...hence why I am relying on mpv.

**Comment by niksedk** [comment]
Sorry, I can't reach Zippyshare... could you upload to another host? (github even accepts smaller mp4 files).

(I normally use SE with mpv and have not observed this issue)

**Comment by E-t-z** [comment]
https://www.upload.ee/files/14493498/Sample.mkv.html

For example, Male character dialogue is completely missing...only background music is outputted.

**Comment by niksedk** [comment]
OK, thx - got the file :)

ffmpeg says `Audio: eac3, 48000 Hz, 5.1(side), fltp, 640 kb/s`

The sound is fine here with mpv inside SE.

The new "Front Center" audio only also works for me - does that work for you in latest SE beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip
![image](https://user-images.githubusercontent.com/1261331/189572131-61a6ce60-3c28-4150-bb6e-3472c8f22891.png)

**Comment by E-t-z** [comment]
@niksedk yes, it works. Thx.

**Comment by E-t-z** [comment]
Root cause is probably related to audio driver, I believe.
On normal circumstances, you pass (decoded) audio stream(s) to audio driver, which would perform downmix according to actual output channels.
It does look like that, wine audio driver (for coreaudio at least), does not do that.
Even if it detects output correctly as stereo, hence the need to force decoder to do it.

**Comment by niksedk** [comment]
How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

You need to adjust the `MpvVideoVf` parameter in `Settings.xml`... does this work for you?

**Comment by E-t-z** [comment]
@niksedk it kind of does not and also shouldn't audio related filters in mpv, begin with af, not vf?

https://github.com/mpv-player/mpv/blob/master/DOCS/man/vf.rst
https://github.com/mpv-player/mpv/blob/master/DOCS/man/af.rst

Code itself in SE probably works though as I can make the player hang, when attempting some really weird stuff with video or attempting to apply any audio related filters... 😆

**Comment by E-t-z** [comment]
Works great, I used:

`format=channels=stereo,loudnorm`

and

`format=channels=stereo,dynaudnorm`

Basically, I would say it is all that is needed, to make it work in occasions where audio driver lacks that certain capability.
SE is not "multimedia player" so I really doubt anyone would need anything more complex, like per channel volume adjustements, etc.

**Comment by E-t-z** [comment]
And huge thank you for implementing this, finally I can ditch Windows virtual machine on my Mac, since Crossover is now enough to cover all my Windows needs. 😎

**Comment by dante3732** [comment]
> https://forum.manjaro.org/t/is-there-an-audio-in-track-normalization-for-mpv/58574/2

Good afternoon, is there any way to enable normalisation for audio in subtitle edit? The sound is very quiet and I have to switch it to maximum.
