### ISSUE TITLE
MPV in full screen mode only in Ubuntu 22.04.1 LTS 

### ISSUE THREAD

**Issue by edcol** [SubtitleEdit/subtitleedit#6244]
Hello,

I have just upgraded OS to Ubuntu 22.04.1 LTS and started having issue with mpv displaying video in full screen only, not embedded into SubtitleEdit. Any hint how to lower video back into app?

I run SE v 3.6.7 portable with use of mono app.
libmpv.so.1.109.0 

Kindly share your advise how to fix it. In "Ubuntu 20.04 LTS" it did work properly.

**Comment by niksedk** [comment]
Try to change "<MpvVideoOutputLinux />" to "<MpvVideoOutputLinux>x11</MpvVideoOutputLinux>" in Settings.xml

**Comment by edcol** [comment]
Thanks Nikolaj, it did help!

**Comment by niksedk** [comment]
Cool, what parameter did you use?
