### ISSUE TITLE
[BUG] Can't select portable VLC in settings

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#6255]
![image](https://user-images.githubusercontent.com/54498172/190286723-28203603-a501-43aa-9ca0-9cc28c8d4191.png)
![image](https://user-images.githubusercontent.com/54498172/190282516-0f8f483d-1962-4910-b7b4-196695044ed8.png)
I can't use portable VLC even though I set the path for it.

**Comment by niksedk** [comment]
Is VLC the 64-bit version?

**Comment by Mishasama** [comment]
Oh sorry, my bad. Didn't notice I was using 32-bit SE before. 😜
