### ISSUE TITLE
 Is there any function like aegisub to generate pronunciation above characters? Steve8000818@gmail.com  Effect as below. 

### ISSUE THREAD

**Issue by nissansz** [SubtitleEdit/subtitleedit#6257]
Is there any function like aegisub to generate pronunciation above characters? Steve8000818@gmail.com

Effect as below. 

![image](https://user-images.githubusercontent.com/41010669/190837056-8a49283b-526a-4195-9842-db7002dfbe34.png)

**Comment by niksedk** [comment]
Hm, you can set a shortcut for ASSA set position
![image](https://user-images.githubusercontent.com/1261331/190893847-dac1ba2b-357f-4dcf-a226-3d6c5ef6f6e4.png)


How does this work in aegisub?

**Comment by nissansz** [comment]
Aegisub can use plugin, which finally use mecab

**Comment by niksedk** [comment]
I have no idea how that works...
