### ISSUE TITLE
Naming Issue - In ASSA Draw

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#6258]
There's a naming/titling issue in ASSA Draw. The Square is indicated to be a circle. 
![naming issue](https://user-images.githubusercontent.com/92556454/190876148-0ea23993-184d-4a32-b594-6c6b1b9bfabb.png)

**Comment by niksedk** [comment]
Thx David :)
Fixed in https://github.com/SubtitleEdit/plugins/commit/86e7f3a38b253040bf94c4d1162c52f61084387c
