### ISSUE TITLE
can't open netflix quality check

### ISSUE THREAD

**Issue by evafans** [SubtitleEdit/subtitleedit#6262]
![image](https://user-images.githubusercontent.com/88836421/190890989-f91fb06e-ef7a-4110-a287-e55c6ffaaf83.png)
If SE was set to simplified Chinese, sometimes Netflix quality check can't be used. It seems only appears in Simplified Chinese, if I change the language to others, it's fine. I'm not sure if I'm the single case.

**Comment by niksedk** [comment]
Could you attach the subtitle you're checking?

**Comment by evafans** [comment]
[00000.track_4608.zh-cn.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/9593473/00000.track_4608.zh-cn.srt.zip)

**Comment by niksedk** [comment]
Thx for the file :)
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip ?
