### ISSUE TITLE
[Bug] Regex replace wrong count

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#6263]
Say I have this file:

![image](https://user-images.githubusercontent.com/20923700/190912570-83d88481-11e2-408f-a5e6-54141df010a9.png)

If I regex replace anything, I get `Found nothing to replace`:

![image](https://user-images.githubusercontent.com/20923700/190912683-b588c7f5-da83-4a88-9a95-771291d4b03f.png)

**Comment by OmrSi** [comment]
I looked a bit into and and for some reason this line: https://github.com/SubtitleEdit/subtitleedit/blob/main/src/libse/Common/RegexUtils.cs#L262 always returns zero, while it returns the correct number if you move the same logic to the original place at: https://github.com/SubtitleEdit/subtitleedit/blob/main/src/ui/Logic/ReplaceAllHelper.cs#L71

**Comment by OmrSi** [comment]
I looked a bit into and and for some reason this line: https://github.com/SubtitleEdit/subtitleedit/blob/main/src/libse/Common/RegexUtils.cs#L262 always returns zero.

**Comment by niksedk** [comment]
thx :)

**Comment by OmrSi** [comment]
Spent an hour trying to find why it didn't match and never noticed it was matching after replace, hehehe.

**Comment by niksedk** [comment]
He, that happens :)
