### ISSUE TITLE
Error when using audio to text

### ISSUE THREAD

**Issue by minaw12** [SubtitleEdit/subtitleedit#6264]
![subtitle edit error](https://user-images.githubusercontent.com/23407864/190928170-43c714db-b04f-4777-8f96-9548954e2afd.PNG)

model: vosk-model-small-ja-0.22

**Comment by niksedk** [comment]
Could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip ?

**Comment by minaw12** [comment]
> Could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip ?

I get no errors when I use the beta.

**Comment by niksedk** [comment]
Cool, thx for testing :)
