### ISSUE TITLE
can't open source 

### ISSUE THREAD

**Issue by YongChingShieh** [SubtitleEdit/subtitleedit#6267]
I   get error message when I try to open source by visual  studio  2022
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Invalid Resx file. Could not find file 'C:\Users\cosco\Source\Repos\subtitleedit\src\ui\Resources\record.png'. Line 138, position 5.	SubtitleEdit	C:\Users\cosco\Source\Repos\subtitleedit\src\ui\Properties\Resources.resx	138	`

**Comment by niksedk** [comment]
Should be fixed via 6fb01f33f875f89345fd16b1441bcb4fae03a88a
