### ISSUE TITLE
Just I use ASS Draw And I got this error. Please any one help me,Note: I use Win11 and my subtitle edit version 3.6.7.

### ISSUE THREAD

**Issue by SorrHash** [SubtitleEdit/subtitleedit#6271]
![Screenshot 2022-09-20 202901](https://user-images.githubusercontent.com/114016987/191325091-58b93429-7091-478c-a46c-9fb88b7d0847.png)

**Comment by niksedk** [comment]
OK, could try to re-download ffmpeg in Options  - Settings - Waveform... and re-download ASSA draw...
It should display the ffmpeg cmd line used, so you could try that in a command prompt and see what error you get.

**Comment by SorrHash** [comment]
> 
![23](https://user-images.githubusercontent.com/114016987/191759097-83d4201a-1175-4057-b962-d39482a66719.png)

I use subtitle beta and he worked
thank you anyway

**Comment by Deligen** [comment]
Got  the same error. Is there any reliable solution?
