### ISSUE TITLE
Words in the text box aren't selected by double-clicking and dragging

### ISSUE THREAD

**Issue by KLaurence** [SubtitleEdit/subtitleedit#6275]
When double-clicking and then dragging, space-separated words in the Subtitle Edit text box cannot be selected — only the word under the cursor becomes selected, regardless of where the mouse is dragged. In applications like Notepad, words are selected when double-clicking and dragging.

In comparison, holding Ctrl+Shift and then pressing arrow keys in the Subtitle Edit text box and in Notepad selects words.

Issue happens for me on Windows 7, but this issue might not be exclusive with W7.

**Comment by niksedk** [comment]
Does it work if you enable this: (Option - Settings - Appearance`

![image](https://user-images.githubusercontent.com/1261331/192096533-41f93e45-b121-4458-bb77-ff8a1c22e5d8.png)

**Comment by KLaurence** [comment]
It does work when `Use syntax coloring` is enabled.

**Comment by Hakunamatata67** [comment]
Hello,
I have the same issue on W11. "Use syntax coloring" is enabled.
No issue on Word or Notepad.

https://user-images.githubusercontent.com/66781048/212028522-738f9762-cec4-4ecd-8fd6-7a8ceaadb10d.mp4
