### ISSUE TITLE
Subtitle Edit "Audio to Text" feature doesn't work in Linux

### ISSUE THREAD

**Issue by zoltan-dulac** [SubtitleEdit/subtitleedit#6276]
I have noticed the "Audio to Text" feature doesn't work in Linux currently. Are there any plans to get this done? If it does work, can you tell me the steps to do so?

**Comment by niksedk** [comment]
It should hopefully work in next beta - see https://github.com/SubtitleEdit/subtitleedit/issues/6071

**Comment by zoltan-dulac** [comment]
@niksedk Thanks so much for the speedy response.  I will definitely test the beta this evening.  So excited!  :-)

**Comment by zoltan-dulac** [comment]
(since this is a dupe, I'll close this ticket).
