### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hugok79** [SubtitleEdit/subtitleedit#6278]
Typo in 'prevous'.

https://github.com/SubtitleEdit/subtitleedit/blob/c82a0c45ad2e235896a321e469b65408aab3067b/LanguageBaseEnglish.xml#L2528

Is **previous**

**Comment by niksedk** [comment]
thx :)
Fixed in https://github.com/SubtitleEdit/subtitleedit/commit/6731b84826987dd971276764470298f27d3f6cc0
