### ISSUE TITLE
Video player strange behavior

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#628]
Video player will play/pause after hiding it if you click in area corner bottom right of SE...

**Comment by niksedk** [comment]
Where exactly? Perhaps a screenshot? (clicking in the video area will play/pause)

**Comment by ivandrofly** [comment]
![subtitleedit](https://cloud.githubusercontent.com/assets/6579818/6547307/47f080f6-c5cc-11e4-946e-d6718779cc3e.PNG)

**Comment by ivandrofly** [comment]
![subtiitleedit2](https://cloud.githubusercontent.com/assets/6579818/6547318/6edc7bf2-c5cc-11e4-81d2-5896736501e1.PNG)
![subtitleedit](https://cloud.githubusercontent.com/assets/6579818/6547319/6ee4cb90-c5cc-11e4-8cf8-fdfd776be242.PNG)

**Comment by ivandrofly** [comment]
I'm using VLC portable version 64x

**Comment by niksedk** [comment]
Nicely found - gave some weird functionality ;)
