### ISSUE TITLE
Auto Translate Japanese to English stopped working

### ISSUE THREAD

**Issue by Simva9** [SubtitleEdit/subtitleedit#6281]
I've started getting this error message for all Japanese translations
Other languages work ok, and Japanese worked a couple of weeks ago.

Subtitle Edit was unable to connect to the translation service
Error: Sequence contains no elements

**Comment by niksedk** [comment]
Works fine here... could you attach a subtitle that does not work?
Perhaps you have used up your daily free quota?

**Comment by niksedk** [comment]
Thx for the file + screenshot.
I also get the error now... seems to be an issue with "Line merge: Merge sentences"...

**Comment by niksedk** [comment]
Should be fixed in SE 3.6.8
