### ISSUE TITLE
Bug: Windows Forms Thread Exception While Using "Audio To Text"

### ISSUE THREAD

**Issue by SleepyCatten** [SubtitleEdit/subtitleedit#6283]
Full error message here:
https://gist.github.com/SleepyCatten/c43c1270ecdc059506c02d5246ef170d

Steps taken

1. Load video (Video - Open Video File)
2. Video - Audio To Text
3. Download English (very large)
4. Click Generate
5. Wait a few moments & the error message appears

**Comment by niksedk** [comment]
Are you using VLC as media player inside SE?
Probably a duplicate of  #6193 or #6264

**Comment by SleepyCatten** [comment]
> Are you using VLC as media player inside SE? Probably a duplicate of #6193 or #6264

Just checked the settings & yes I am.

**Comment by niksedk** [comment]
OK, thx for the info - try switching to mpv :)
Gives better on video preview + smoother waveform + does not crash "audio to text".

Alternatively you can try latest beta under SE 3.6.7 release
