### ISSUE TITLE
Support bold in DCP subtitles

### ISSUE THREAD

**Issue by felagund** [SubtitleEdit/subtitleedit#6286]
This file:
[test_srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/9640662/test_srt.txt)
when saved as Digital cineam file (Interop or any version of SMPTE) results in this:
[test_xml.txt](https://github.com/SubtitleEdit/subtitleedit/files/9640664/test_xml.txt)
However, he result should be 
[test_correct_xml.txt](https://github.com/SubtitleEdit/subtitleedit/files/9640670/test_correct_xml.txt)
as per http://www.deluxecdn.com/dcinema/reference/ti_subtitling_spec_v1_1.pdf

Specifically, bold text should be inside `<Font Weight="bold">Bold text goes here</Font>` tags.

**Comment by niksedk** [comment]
How is bold for Interop in latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by felagund** [comment]
Did I really report it just as you were fixing it or did you spin it just for me:-)? I did try on 3.6.7.

It looks good. However, it adds `Effect="border"` to the font tag - I am not sure that is necessary.

**Comment by niksedk** [comment]
Just for you :)

Beta updated with more bold support + removed `Effect="border"` : https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

Better?

**Comment by felagund** [comment]
Perfect, thank you!
