### ISSUE TITLE
Audio to text issue

### ISSUE THREAD

**Issue by denis1982al** [SubtitleEdit/subtitleedit#6288]
I receive the following error message when trying to Generate subtitles:

Could not find file:
C:\Users\User\AppData\Local\Temp\4fe8......................wav

Stack trace:... etc

Please help

**Comment by niksedk** [comment]
Related to #6283 ?

**Comment by denis1982al** [comment]
Will check. Appreciated.

**Comment by denis1982al** [comment]
Whoa! You are the best! 
Solved!
Such a simple solution! Go figure.
