### ISSUE TITLE
Batch nOCR

### ISSUE THREAD

**Issue by Eniff** [SubtitleEdit/subtitleedit#6289]
Hello,

I have seen you have added this to the Beta changelog:
"Add "nOCR" option to "Batch convert" - thx Gen3ric"

I couldn't find any way to use this. It is not in the "Convert options". Is this available already in the beta? How can I use this?

**Comment by Eniff** [comment]
Nevermind, I had to right click.

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/192352335-bc6cd264-d58b-4c48-a207-ddec96c39904.png)

**Comment by Eniff** [comment]
It is working, altough sometimes it throws an error before starting the next file:

```
An application error occurred in Subtitle Edit 3.6.7.318. Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:
Error Message: Object reference not set to an instance of an object.

Stack Trace:
at 
Nikse.SubtitleEdit.Forms.Ocr. VobSubOcr.NOcrT hreadDoWork( Object sender, DoWorkEventArgs e)
at 
System.ComponentModel.BackgroundWorker.OnDoWork(Do WorkEventArgs e)
at 
System.ComponentModel.BackgroundWorker.WorkerThreadS tart(Object argument)
```

If I press retry, it will process a few files again without problem and then it throws the error again.

**Comment by niksedk** [comment]
OK, I had trouble finding the root cause... but I've tried a hack - does this work better for you?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by Eniff** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/60354139/192550237-67292137-70cc-4672-989a-cb58b07be7a0.png)

I ran it twice over 32 files and it showed the error only once in the first run.
Thank you for the prompt replies and for helping with this. It is an amazing piece software.

**Comment by niksedk** [comment]
Thx for testing and the nice words :)
New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by Eniff** [comment]
I ran it twice again on the new version and the error seems to have gone. Thank you again for your work!
