### ISSUE TITLE
Issue with saving files

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6290]
It doesn't happen quite often but it's something like this:

Start SE and create a new SRT file, then hit Save, now I see the default format is switched to ASSA... Well, I did save something in ASSA hours ago, but I also saved a bunch of SRT files after that. Maybe a little bug here?

**Comment by Ding-adong** [comment]
Check settings then subtitle formats for default format.

**Comment by LeonCheung** [comment]
@Ding-adong The default format is always set to SRT. That's why it's kinda weird.
