### ISSUE TITLE
Improvement for one shortcut

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6291]
The **Set start and set end of previous (minus min gap)** shortcut works quite well basically, but sometimes when the video cursor is around the second-half part of one block, it doesn't work... I bet there's some limitation by design, but maybe we can remove that limitation for the greater good?  :)

Try this file for testing, and try to put the video cursor at any pos in blue sections:
```
1
00:00:00,087 --> 00:00:02,063
Line 1

2
00:00:02,064 --> 00:00:04,462
Line 2

3
00:00:04,463 --> 00:00:06,653
Line 3
```
![image](https://user-images.githubusercontent.com/494788/192820932-79259529-7065-4015-8338-25b215a249d5.png)

**Comment by niksedk** [comment]
The shortcut will not make the subtitle shorter than `MinimumDisplayMilliseconds`...

**Comment by LeonCheung** [comment]
Oh I see. It makes sense then. Thanks for clarifying, closing.

**Comment by LeonCheung** [comment]
Wait... Hmm, but what if I need to have both without no conflict? I mean, min duration is important for me, as well, but I also need to ignore that limit because of the real case I'm doing, which is: I'm fine-tuning the timecodes on 100+ SRTs that have been translated from the original language because the timecodes are okay for the original videos, but not for dubbed videos (or another audio track), that's why I need to adjust everything accordingly. That's why I need to fine-tune the start/end time, for almost every line. It turns out this shortcut is extremely useful here except for that min duration rule under the hood. I think a perfect way would be to add a new shortcut called **Set start and set end of previous (minus min gap, ignore min duration)**.

Actually it would be totally fine because, even if I break the min duration rule for the current line, it could be then fixed when moving to the next line, then the next line, then the next line... Hope you can understand the point here or have a better idea to make everyone happy. :)
