### ISSUE TITLE
Feature Request: Exporting and Importing Word Lists

### ISSUE THREAD

**Issue by RedSoxFan04** [SubtitleEdit/subtitleedit#6292]
SubtitleEdit is a fantastic program, but for those of us who use it on either Linux or MacOS via Mono, it would be nice to be able to import and export word lists so we can upgrade to the latest version of SubtitleEdit without losing our word lists and having to start from scratch.

**Comment by niksedk** [comment]
OK, what lists are most important for you?

**Comment by RedSoxFan04** [comment]
I see you made a change, but will that help with the portable version?

**Comment by niksedk** [comment]
It should mean that you can copy the `*_user.xml` files from your old dictionaries folder, to your new dictionaries folder. 
Before this, SE also included user files (which is probably a bad idea).

**Comment by RedSoxFan04** [comment]
Thank you!
