### ISSUE TITLE
Request for a few custom format parameters

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6301]
Hi, May I ask for a few new parameters for Export Custom Format? They are:

1. Video/audio filename (with / without extension)
2. Convert timecodes to seconds with decimals, e.g. **00:02:14,789** to **134.789**.

Thank you so much!

**Comment by niksedk** [comment]
Should video/audio filename contain path?

**Comment by LeonCheung** [comment]
Not sure if anyone else needs the full path but for me the filename alone is fine. Thanks!

**Comment by niksedk** [comment]
I think `{title}` already does this?

**Comment by LeonCheung** [comment]
Not exactly imho, because: 

1. {title} doesn't support the text line Yet. We can only insert it to Header and/or Footer, right? I know it's kinda weird, but for some reason, it is really needed to have the media filename in the first column of every single line...
2. {title} only shows the name of the SRT file, not the media itself.

**Comment by niksedk** [comment]
OK, how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Oh that's really nice! One more thing, can we have the media file name with extension? 

I mean, currently the {media-file-name} returns **Myvideo**, and {media-file-name-full} returns **C:\Video\MyVideo.mp4**, but how to return **Myvideo.mp4**?

**Comment by niksedk** [comment]
Sure, how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Perfect. Thank you sooo much for the help!
