### ISSUE TITLE
Optional full path for exporting comparsion results

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6302]
When talking about the full path thing in another thread, it reminds me of something, which is, when exporting the comparison results by Compare tool, it always exports the full path of both files, which usually would not be expected when sharing the results to others, say, clients, for privacy concern. (I always have to edit the HTML file manually after exporting.  XD )

**Comment by niksedk** [comment]
OK, hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
So cool. Thank you! Closing.
