### ISSUE TITLE
Burned in subtitle with video feature - Reducing video quality

### ISSUE THREAD

**Issue by soundarsurya** [SubtitleEdit/subtitleedit#6303]
Subtitle edit is a nice and cool tool for editing subtitle for our video. 

I have edited subtitle in .ass format for my video which is in FHD quality (size 2.5GB). 
When I tried `generate video with burned-in subtitle` it actually worked fine but the size of video is drastically reduced from 2.5GB to 275MB. 

Is there any way to add burned in subtitle to video without compromise in video size and quality?

**Comment by niksedk** [comment]
Depending on chosen video codec... you can either lower the CRF value or choose a file size:

![image](https://user-images.githubusercontent.com/1261331/193450936-5c39e56c-fad8-45d3-aa8e-3b8cf9d9e0d2.png)

For libx264 see: http://trac.ffmpeg.org/wiki/Encode/H.264
For libx265 see: http://trac.ffmpeg.org/wiki/Encode/H.265

You should probably choose "Copy" for audio codec (just using the existing audio track)

**Comment by soundarsurya** [comment]
Hi @niksedk,
Even though i changed CRF value, file size is not changing. If i want at same size of 2.5GB do i need to set it manually?
Will the quality of video affect, if size if reduced to 275MB from 2.5GB?

**Comment by niksedk** [comment]
Then check "Target file size" + set file size to 2.5 GB

**Comment by soundarsurya** [comment]
@niksedk so manually we need to set the target file size?
reduction in video size from 2.5GB to 275MB will affect the quality?

**Comment by niksedk** [comment]
> @niksedk so manually we need to set the target file size? 
Yes, if you want the same file size.

>reduction in video size from 2.5GB to 275MB will affect the quality?
Probably, but you could compare some screenshots of both videos.
