### ISSUE TITLE
Ordinals Have Spaces

### ISSUE THREAD

**Issue by RedSoxFan04** [SubtitleEdit/subtitleedit#6304]
Whenever SubtitleEdit comes across an ordinal (i.e. 23rd), it puts a space between the number and the letters.

**Comment by niksedk** [comment]
Can you supply a screenshot?

**Comment by RedSoxFan04** [comment]
![Screenshot_20221003_130721](https://user-images.githubusercontent.com/13876066/193637386-f8cdf340-c8f9-433b-9d8d-0ab6d1f773b9.png)

**Comment by niksedk** [comment]
Thx - should hopefully be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by RedSoxFan04** [comment]
Thanks!
