### ISSUE TITLE
Can't open a .mp4 file in subtitle edit to start subtitling from scratch

### ISSUE THREAD

**Issue by Intrepid-Buddhiya** [SubtitleEdit/subtitleedit#6307]
Hi,

This is probably the wrong place to ask my question, but I have come here because I could not find help anywhere else.

I am a newbie and want to add subtitles to my .pm4 video file.

My problem is I can't open my video file in subtitle edit 3.6.7, it keeps asking for a audio file.

I have a windows 10 laptop, and I have set up VLC as my video player and have also downloaded and installed FFmpeg.

Please help, or suggest where I can find a solution to this problem.

**Comment by niksedk** [comment]
How do you open the video file? Try drag-n-drop it on the waveform in SE.
Also, try mpv as video player.

If you still got an issue, please provide a screenshot or two.
