### ISSUE TITLE
Problem with automatic subtitling for a Hindi video

### ISSUE THREAD

**Issue by Intrepid-Buddhiya** [SubtitleEdit/subtitleedit#6313]
Hi,

I am trying to generate automatic subtitle for a Hindi video, but I keep getting the following error which asks me to report it here. So there goes.

I have installed the vosk engine, and the HIndi model,.

I have a windows 10 asus computer with nvidia rtx 3060 gpu.

![image](https://user-images.githubusercontent.com/104341073/194359872-f20fa9db-9654-48b5-80ee-47ea0f5497c8.png)

Thanks
Intrepid Buddhiya

**Comment by niksedk** [comment]
Related to https://github.com/SubtitleEdit/subtitleedit/issues/6283 ?
