### ISSUE TITLE
ASSA default resolution

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6317]
When working with an ASSA project from scratch, we need to set the resolution manually (usually by clicking the From Video button), but maybe it could be set automatically by default?  (I remembered it used to be auto, not sure if it needs kinda fix)

**Comment by niksedk** [comment]
Hm, works fine here with default settings...

**Comment by LeonCheung** [comment]
Ha, indeed, but just wondering why it doesn't work with my Settings.xml 😂 
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/9826099/Settings.zip)

**Comment by LeonCheung** [comment]
Maybe a video would be more straightforward here:


https://user-images.githubusercontent.com/494788/196993639-5d9c8e54-6b8e-4512-a908-2522e3af7777.mp4

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip ?

SE now always sets the res when no subtitles are added and in the properties window, the current resolution will be displayed if different from the res in the ASSA file.

**Comment by LeonCheung** [comment]
Nice idea and works really well imho. Cheers! 👍

**Comment by LeonCheung** [comment]
@niksedk Hi. maybe there are some regression lately? It doesn't work again. 😆

**Comment by LeonCheung** [comment]
Hmm, rechecked the Settings file, **<AssaResolutionAutoNew>** tag was set to **False** again for unknown reasons, I don't think that's what I did, which is so weird... Anyway, problem solved for now. Closing.
