### ISSUE TITLE
MultipleReplace bug

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#632]
Hi...

in MultipleReplace i can only search and replace a single with checkbox checked at a time.

if I have multple checkbox checked for search and replace nothing happens.

![capturar](https://cloud.githubusercontent.com/assets/7856897/6591006/ad079b82-c7b1-11e4-9917-4c64b3ca57da.PNG)

I think the bug was introduced here in this change: https://github.com/SubtitleEdit/subtitleedit/commit/2baf6d9edb5728b088df2c2a543e5b72f17a75ae

I reverted back the change and compile SE and works well as you can see on image below

![capturar2](https://cloud.githubusercontent.com/assets/7856897/6591139/f614a562-c7b2-11e4-98c1-5e4e9ff716cd.PNG)

**Comment by niksedk** [comment]
Thx @marb99 and @Ivandrofly :)
