### ISSUE TITLE
Can batch mode add batch remove  formatting?

### ISSUE THREAD

**Issue by i990049** [SubtitleEdit/subtitleedit#6327]
hundred files to deal with the same，thank you.
![屏幕截图(10)](https://user-images.githubusercontent.com/103364093/195649376-f624417a-81d3-400e-84e2-937f185d3d31.png)

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/195995896-6ca55692-838d-4063-b8dc-0d26e99b47cf.png)

**Comment by i990049** [comment]
Thanks for your reply. How to solve this problem that batch split long line with total lenth 79 and make sure every line is single line?I sent you the test files. I know how to split one subtitle, and the test file was splited into 618 lines. I want to deal with hundred files. When I try the batch mode, there is no line maximum length setting, so it was splited into 588 lines. Can you add maximum length setting to the batch convert mode? Thanks for you help.












43409628
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SubtitleEdit/subtitleedit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月15日(星期六) 晚上11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SubtitleEdit/subtitleedit] Can batch mode add batch remove  formatting? (Issue #6327)
