### ISSUE TITLE
Is it Possible to add batch change casing？

### ISSUE THREAD

**Issue by i990049** [SubtitleEdit/subtitleedit#6330]
Stills hundred subtitle files from TVshow，all upper case.
![屏幕截图(15)](https://user-images.githubusercontent.com/103364093/195899610-22c7e525-7b37-450b-8839-3e7f98323309.png)

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/195988351-023ba57b-027f-4525-be01-905571805fdf.png)
