### ISSUE TITLE
MP4 subtitles don't get fully converted

### ISSUE THREAD

**Issue by LucretiaAudrey** [SubtitleEdit/subtitleedit#6331]
Hi! Encountered weird issue - subtitles ripped from CBS only get converted halfway, even though they're full. Can you please fix this issue? Thanks!

Attaching file in question

[stream [stream].en-US.mp4.zip](https://github.com/SubtitleEdit/subtitleedit/files/9791220/stream.stream.en-US.mp4.zip)

Conversion cuts of at 

467
00:19:09,756 --> 00:19:12,000
Wait a minute, Deac.
Check this.

**Comment by niksedk** [comment]
Thx for the file :)

Should work in latest beta now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by LucretiaAudrey** [comment]
Almost. now it cuts off at 31 minute :(

**Comment by LucretiaAudrey** [comment]
I think it has to do with SE automatically merging strings it thinks are the same

**Comment by LucretiaAudrey** [comment]
Or maybe ad breaks

**Comment by LucretiaAudrey** [comment]
Almost. now it cuts off at 31 minute :(

I think it has to do with SE automatically merging strings it thinks are
the same

Or maybe ad breaks

**Comment by niksedk** [comment]
> Almost. now it cuts off at 31 minute :(

I'm sure that SE got the last text - and no lines were merged.

**Comment by LucretiaAudrey** [comment]
Converting with mp4box seems to extract fully


[stream [stream].zip](https://github.com/SubtitleEdit/subtitleedit/files/9792736/stream.stream.zip)

**Comment by niksedk** [comment]
Thx, I see the difference now... I will look into it (mp4 is not an easy format to read)

**Comment by niksedk** [comment]
OK, mp4 files normally has time codes matching with texts... I thought so at least.
It seems that time codes can cover multiple texts when time codes has the optional size field:

![image](https://user-images.githubusercontent.com/1261331/196026641-9e885fd4-0bf6-464f-8204-4f79e28f8b62.png)

**Comment by niksedk** [comment]
@LucretiaAudrey: OK, how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip
Are texts okay?
Are time codes okay?

**Comment by LucretiaAudrey** [comment]
Thanks a lot! Now it seems to extract fully, although time codes might be a bit skewed after some position. I'll check it today

**Comment by LucretiaAudrey** [comment]
Yeah, sadly timings are screwed(

**Comment by niksedk** [comment]
Hm, if I extract the webvtt with mp4box via `mp4box -raw 1 stream [stream].en-US.mp4` I get *very* equal results:

![image](https://user-images.githubusercontent.com/1261331/196498847-94bb8502-af32-4455-953b-e94fc85c7de2.png)

**Comment by niksedk** [comment]
OK, no differences now in latest beta between SE/mp4box: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/196692022-8c17b74d-4f96-4d17-af38-28b57243ee2c.png)

Thx for the interesting file :)

**Comment by LucretiaAudrey** [comment]
Thank YOU for constantly improving SubtitleEdit!
