### ISSUE TITLE
[Feature Request] bilingual: exported as bilingual srt.

### ISSUE THREAD

**Issue by sihunqu123** [SubtitleEdit/subtitleedit#6332]
## Description

See the screenshot below, I can have both English and Chinese version subtitle of a movie after using the auto-translate feature, but there is no way to export/`save as` a srt file that contains both English and Chinese.

![image](https://user-images.githubusercontent.com/22839917/195977020-381c57a0-cf6a-4c34-88c5-3de4c75ec571.png)

## Expected result
![image](https://user-images.githubusercontent.com/22839917/195977170-504f86d8-af51-48fb-9a4d-6b6ebffb8bd0.png)

@LeonCheung @niksedk  @OmrSi noticed that you have handled bilingual-related issues before, see if you could help, thanks.

Anyway, this free-multiPlatform software is already very awesome and even more powerful than most of those paid alternative software, appreciate your guys for contributing!

**Comment by LeonCheung** [comment]
There are some ways, like:

1. There's a shortcut called **Merge original and translation**, which is **Ctrl Shift Alt M** by default. Then you can have the bilingual style to export.
2.  Using the powerful Export custom text format feature, and create a new format of your own:
![image](https://user-images.githubusercontent.com/494788/195977542-1e77716a-c1bd-4522-b86a-6de0dc2848f8.png)

**Comment by sihunqu123** [comment]
@LeonCheung Thanks for your help! Now we can close this issue, now.

**Comment by o-data** [comment]
@LeonCheung is there a way to merge two different file instead of "original" + "translated"? Thank you.

**Comment by LeonCheung** [comment]
@o-data If you mean bilingual merging, I can't think of any, sorry. Maybe it helps by providing a typical scenario.

**Comment by o-data** [comment]
Hi Leon,

Example: I got 2 separate .srt from two different people.

Person A send VideoName.English.srt
Person B send VideoName.Chinese.srt

As I didn't personally translate these file and didn't use the "Original + Translated" feature of SubtitleEdit I don't have this menu (screenshot below), but I want to create exactly what @sihunqu123 wanting to do.
![image](https://user-images.githubusercontent.com/67723461/225487418-e48d99ce-5a00-4dea-a5f1-fabf6a8cbf5f.png)

**Comment by LeonCheung** [comment]
@o-data Well, if they share the same timecodes, you can certainly load them both in SE, one as original, another one as translation. Then you can use the trick above.

If they don't share exactly the same timecodes but the same line count, meaning that they match paragraph by paragraph, then you can load one of them in SE, then File > Import > Timecodes, and choose the other file. Then they will share the same timecodes and allow you to do the same trick as above.

If they both are not your case, then I'm afraid there is no quick and dirty way for that. Or you have to process them in tools like Excel or something.
