### ISSUE TITLE
[Request] Checkbox to enable/disable bookmarks' text on waveform

### ISSUE THREAD

**Issue by Tuan-P** [SubtitleEdit/subtitleedit#6334]
![Screen Shot 10-17-22 at 01 45 PM](https://user-images.githubusercontent.com/91291342/196236234-3252006a-e6a9-4e00-a61b-88509eca503e.JPG)

A checkbox similar to "show chars/sec", "show words/min", in the waveform/spectrogram settings.

**Comment by LeonCheung** [comment]
@niksedk BTW, I think the Toggle Bookmarks shortcut works weird somehow. I mean, everything will get lost after re-toggling.
