### ISSUE TITLE
Percent Signs Interpreted as "olo"

### ISSUE THREAD

**Issue by RedSoxFan04** [SubtitleEdit/subtitleedit#6335]
For example, 27% is interpreted by SubtitleEdit as "27olo".

**Comment by niksedk** [comment]
Could you upload the image/sub?

You can probably double-click on the line, right click on the first letter and choose "add better multi match"
![image](https://user-images.githubusercontent.com/1261331/196265354-e185cf07-d59b-4661-9eae-7f100dfe75a1.png)

**Comment by RedSoxFan04** [comment]
Sure!
![Screenshot_20221018_150903](https://user-images.githubusercontent.com/13876066/196522111-aa9a0430-23a3-49d6-96f8-5d57fd2a97fd.png)

**Comment by niksedk** [comment]
Step 1)
![image](https://user-images.githubusercontent.com/1261331/196689345-23d913c5-5413-468b-9381-35a888c72ed5.png)


Step 2)
![image](https://user-images.githubusercontent.com/1261331/196689406-7131a8b2-7050-4808-bada-0ed2d9ed49ca.png)


Step 3)
Accept or draw new lines


Also included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip
