### ISSUE TITLE
Can extract subtitle files from MKV, but not when you're in batch.

### ISSUE THREAD

**Issue by DrReddP** [SubtitleEdit/subtitleedit#6342]
Basically, if I have an MKV with an embedded subtitle file, I can drag that individual file into SE and it recognizes the embedded file just fine, but when I drag the entire season into batch and hit convert, it just blinks and doesn't do anything.
Screencap: https://imgur.com/a/t9qjm75

The weird thing is, if I drag that same file into MKV toolnix, it doesn't see a subtitle file anywhere

**Comment by niksedk** [comment]
Hm, seems to work fine here...
Could you send a link to one of the files? E.g. via email?

**Comment by DrReddP** [comment]
I can DM you a google drive link. I don't know how to DM on github though lol

**Comment by niksedk** [comment]
You can use nikse.dk@gmail.com

**Comment by DrReddP** [comment]
Ok sent

**Comment by niksedk** [comment]
Thx, got the file :)

**Comment by niksedk** [comment]
It should work now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

SE now has some mp4 support in "Batch convert".

**Comment by DrReddP** [comment]
Ok that worked, but two hangups.
1. Not a big deal, but fyi, it now lags when you drag video files into the
batch window. About 15 seconds per video, and it stacks if you drag
multiple.
2. It's not adding the eng suffix even though it recognizes the subs as
english. it used to do that, right?

**Comment by niksedk** [comment]
I've added language suffix for .mp4 files too (your file is mp4 and not mkv - so mp4 support in batch convert is new)

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by DrReddP** [comment]
Thank you. Is this going to carry my settings over from 3.6.6?

**Comment by niksedk** [comment]
> Thank you. Is this going to carry my settings over from 3.6.6?

Settings should not reset... Installer nor portable version should include "Settings.xml".

Still, it's recommended to reset settings once in a while (or do a clean install if you have an really old SE installation) + redownload ffmpeg + mpv once in a while.

**Comment by DrReddP** [comment]
You're saying it's recommended I have to go back through end manually reset
all of my settings every once and a while??

**Comment by niksedk** [comment]
> You're saying it's recommended I have to go back through end manually reset all of my settings every once and a while??

Yes, I would say a clean install is a good idea every few years.

**Comment by DrReddP** [comment]
How do I carry over my original settings??

**Comment by niksedk** [comment]
> How do I carry over my original settings??

If you just install latest version, your settings will be kept.

**Comment by DrReddP** [comment]
That was the very first question that I asked you. When I install this beta
version that you have just linked for me, is it going to carry over my
settings? I don't know how any of this works so I don't know if installing
a new version is the same as installing a beta

**Comment by DrReddP** [comment]
I'm using whatever is in the zip file that you just gave me. Is there an
installer versus something different in the zip file?

**Comment by niksedk** [comment]
The beta zip file can just overwrite the files from the portable version.

If you're using the installer version, then *.dll + SubtitleEdit.exe from the beta should overwrite files in e.g. "C:\Program Files\Subtitle Edit"... and the "Dictionaries" + "Ocr" + "Languages" folders should be copied to something like "C:\Users\[USERNAME]\AppData\Roaming\Subtitle Edit"

**Comment by DrReddP** [comment]
Okay, thank you for all your help. This new MP4 tool is great

**Comment by DrReddP** [comment]
So, I batched these mp4s, and it changed the sync? The mov.text is fine in
the mp4s, but not after SE rips them.
https://drive.google.com/drive/folders/159Ydod6MhalGoVlxSTMjl8WfqYN0EJiu?usp=share_link

**Comment by niksedk** [comment]
Thx for the files :)
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

**Comment by DrReddP** [comment]
That works nicely, thank you. How do I support you?

**Comment by DrReddP** [comment]
Hello,

I have this MP4 that has closed captions embedded. VLC recognizes and plays
them, Plex recognizes and plays them, but when I drag the file into
subtitle edit, it says there's no subtitle file. I did try the beta version
of that other one that allows you to batch mp4s but that didn't work
either. I've also tried mkvtoolnix and it only sees a video and audio
channel too, no subs

Here's the file.
https://drive.google.com/file/d/1xGMmtFAsEi4mMzXE4JzGpZ_heVvVNax-/view?usp=share_link

**Comment by DrReddP** [comment]
Could you please respond? Here's another one. Handbrake, VLC, and Plex
recognize the CC. Subtitle Edit and MKV ToolNix do not.
This file might not be uploaded till later.
https://drive.google.com/drive/folders/1SqWVXwN055MglgE_mXtxgPYanuDqvV69?usp=sharing

**Comment by DrReddP** [comment]
do you guys respond to emails anymore

**Comment by niksedk** [comment]
Hi @DrReddP,

Sorry for the late answer, and thx for the file :)

It seems to be yet another variation of subtitles in mp4. This time in the obscure American CEA 608/708 format.
I have a hard time finding out how these subtitles exactly are stored in mp4. If anyone has info on this. please share :)

The MKV ToolNix author wrote at some point that he gave up on subtitles in mp4.
