### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by tormento** [SubtitleEdit/subtitleedit#6343]
Unfortunately when converting timings from srt (milliseconds) to ass (hundred of second), SE truncates the values instead of rounding:

SRT:

1
00:00:01,001 --> 00:00:08,**008**
AKUDAMA DRIVE - I CATTIVI -
2
00:00:12,554 --> 00:00:15,224
KANSAI
3
00:00:34,034 --> 00:00:37,412
{\an8}KANSAI
AREA SUD
4
00:00:37,**579** --> 00:00:38,**747**
STOP

ASS:

Dialogue: 0,0:00:01.00,0:00:08.**00**,Default,,0,0,0,,AKUDAMA DRIVE\N- I CATTIVI -
Dialogue: 0,0:00:12.55,0:00:15.22,Default,,0,0,0,,KANSAI
Dialogue: 0,0:00:34.03,0:00:37.41,Default,,0,0,0,,{\an8}KANSAI\NAREA SUD
Dialogue: 0,0:00:37.**57**,0:00:38.**74**,Default,,0,0,0,,STOP

**Comment by niksedk** [comment]
Thx, that's a nice catch :)

How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by tormento** [comment]
Much better.

Thanks for the superfast fix!
