### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by chuck4683** [SubtitleEdit/subtitleedit#6344]
i keep getting this error and the file is there i see it
![Untitled](https://user-images.githubusercontent.com/56807433/196802625-ca9e39fc-7e59-4e2e-b6a4-45d360ddf43c.jpg)

**Comment by niksedk** [comment]
What OS are you using? 32-bit or 64-bit?
How did you install SubtitleEdit? Portable or Installer?
Did you try a clean install?
