### ISSUE TITLE
Cntrl + Shft + M (Multiple Replaces) is not working [ver 3.6.7]

### ISSUE THREAD

**Issue by cndhng** [SubtitleEdit/subtitleedit#6349]
Hello, as per the question in the headlines. I can't seem to make that key shortcut work. Very similar to this issue #4584 where I tried to do the same by changing to Cntrl + M but did not work as well. Thank you

**Comment by niksedk** [comment]
Ctrl+Alt+M ?

**Comment by cndhng** [comment]
my bad, Cntrl + Alt + M and also I tried to remap but no luck as well.
