### ISSUE TITLE
How to remove the line without a subtitle line that I do not need?

### ISSUE THREAD

**Issue by cndhng** [SubtitleEdit/subtitleedit#6350]
I had a video OCR scanned and of course it's not perfect, depending on the source. Now the common error that I see repeating is as per screenshot below.
![Issue](https://user-images.githubusercontent.com/83151768/197431374-71290b84-6b03-48ea-af1e-16fc699701c8.jpg)

My question is, how would you remove these lines with those symbols and leave only the meaningful lines below with find and replace? Thank you very much

**Comment by niksedk** [comment]
Could you attach the subtitle?
You could try doing something with multiple spaces, but it's probably not too easy.

**Comment by cndhng** [comment]
[sub.zip](https://github.com/SubtitleEdit/subtitleedit/files/9849140/sub.zip)

**Comment by cndhng** [comment]
Hello. I wonder if you took a look at the subtitle that I sent :D. Thank you
