### ISSUE TITLE
3.6.8 post-update VLC conflict

### ISSUE THREAD

**Issue by kjaerlige** [SubtitleEdit/subtitleedit#6351]
Updated with the latest 3.6.8 installer version on Win10 x64, VLC worked before, now I'm getting this message with any video I'm trying to open.
Installed mvp, which works, switched back and forth - didn't help. Videos aren't corrupted and successfully played with VLC otherwise.
![Screenshot 2022-10-24 114210](https://user-images.githubusercontent.com/32398503/197486367-2a10f7ab-c7c6-437a-9231-ba45c7e765ff.png)

**Comment by sp00n** [comment]
I don't even get that far, for me the program just freezes when I select VLC as the media player and try to select a video file.
Also when I try to specify the path to VLC (using the regular install, not the portable one).

DirectShow works.

**Comment by niksedk** [comment]
thx for reporting :)
SE was calling vlc position/duration during loading of video... this should be fixed (in latest source).

Sorry, do try mpv... this bug was surely not intentional, but mpv is better ;)

(Let keep this open for a while - I guess other people might have this issue)

**Comment by LauMia** [comment]
System is W11 x64 (and VLC of course is x64 too).
Same pb here. Downloaded today's 3.6.8 zip version.
VLC worked fine with 3.6.7, and now is not recoognized.
Anyway, thanks for your wonderful software !

**Comment by pandalamp** [comment]
So the current solution for VLC users is to roll back to 3.6.7 and wait for the next release? Just confirming.

All the same, thanks for fixing it in code so quickly @niksedk

**Comment by jmaraujouy** [comment]
> So the current solution for VLC users is to roll back to 3.6.7 and wait for the next release? Just confirming.
> 
> All the same, thanks for fixing it in code so quickly @niksedk

Yes, I can confirm that downgrading to v3.6.7 solves the problem. That's what I did while I wait for a fix. ;)

**Comment by niksedk** [comment]
Should be fixed in 3.6.9
