### ISSUE TITLE
After updating to 3.6.8.0, right click on subtitle produces error

### ISSUE THREAD

**Issue by Octom7** [SubtitleEdit/subtitleedit#6353]
Normally I right click subtitle, for example to delete a line, but since I did the update this morning I get an error message as per the attached snip.
![Screenshot 2022-10-25 144646](https://user-images.githubusercontent.com/77089301/197684978-56e7d209-b9cb-49b6-bfd1-e08a08d14e54.jpg)

**Comment by Jyaelev** [comment]
So do I!  I can't do any right click!
Thanks for you help!
JYL

**Comment by niksedk** [comment]
Thx, hopefully now fixed in latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

**Comment by Octom7** [comment]
Which files must I transfer from the zip file to maintain the current default settings or do I run the .exe file?

**Comment by Jyaelev** [comment]
...Again, I have the same question!
not sure what to do with all these files!

Thank you for your reactivity and your help.

JYL

**Comment by niksedk** [comment]
You can unpack the whole beta zip (a portable version) to something like C:\Tools\SE... or you can take SubtitleEdit.exe + libse.dll and overwrite your old installation - like in C:\Program Files\Subtitle Edit

**Comment by Octom7** [comment]
Thank you, I replaced SubtitleEdit.exe + libse.dll and the program works fine now. Well done for being so prompt.
John

**Comment by Jyaelev** [comment]
All perfect!
Thank you so much for your reactivity!
JYL
