### ISSUE TITLE
Google API Key Invalid

### ISSUE THREAD

**Issue by toMochika27** [SubtitleEdit/subtitleedit#6354]
Hi there!

I wanted to try the Google Cloud Vision for OCR so that I can edit PGS/SUP subtitles. But, it kept saying that the Google API Key is invalid after I already input the API key. I don't think it's a billing issue since my Cloud account has free credit currently. Is there any document/tutorial that I can lookup to use this for OCR?

Thanks!

**Comment by niksedk** [comment]
I've not tested this, but you probably need to setup billing... you need to do that for the translate API.
@Flitskikker; Is that correct?

**Comment by AommyPatty** [comment]
Did you fix it. It is so confusing.
