### ISSUE TITLE
Whisper can get much faster :) 

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#6357]
I recently checked the **[Open Ai's Show and Tell Page](https://github.com/openai/whisper/discussions/categories/show-and-tell)** and found a **[C/C++ Implementation of the Whisper Model](https://github.com/openai/whisper/discussions/130)** that's using less memory and outputting the transcripts/subtitles much faster.

Is it possible to check this out and hopefully incorporate it in Subtitle Edit? 
https://github.com/openai/whisper/discussions/130

Thanks!

**Comment by dgoryeo** [comment]
> I recently checked the **[Open Ai's Show and Tell Page](https://github.com/openai/whisper/discussions/categories/show-and-tell)** and found a **[C/C++ Implementation of the Whisper Model](https://github.com/openai/whisper/discussions/130)** that's using less memory and outputting the transcripts/subtitles much faster.



Can the C implementation run side by side pyhon environment?  Does it support GPU?

**Comment by patarapolw** [comment]
It doesn't support GPU afaik, but in return, it doesn't require large GPU VRAM as in Whisper's medium (5 GB) and large (10 GB) models, which is impossible with GPU on my machine.

Small model is unreliable for my case - https://github.com/openai/whisper/discussions/135#discussioncomment-3731917

**Comment by niksedk** [comment]
I've just tested with a 2 minutes clip, and got these results:

````
Calling whisper-CPP with : whisper --language "en" --model "tiny.en.bin"  "input.wav"
Calling whisper-CPP done in 00:00:34.8508224

-----------------------------------------------------------------------------
Calling whisper-php with : whisper --language "en" --model "tiny.en"  "input.wav"
Calling whisper-php done in 00:00:20.6111411

````

It seems I get way slower results with whisper cpp... any ideas?

[wav.zip](https://github.com/SubtitleEdit/subtitleedit/files/9953993/wav.zip)

**Comment by niksedk** [comment]
OK, it can get faster :)
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip ?
SE should now download whisper.cpp in-program to make it easier... requires a cpu with AVX2.
Please test :)

**Comment by dgoryeo** [comment]
> cpu with AVX2

Doesn't work for me. Would that be caused because I use Ryzen CPU? 
I tried with both base, and large models for Japanese, but the output SRTs were empty. In both cases, the progress bar shows audio extraction, and transcribe finishing in 5 seconds. 
Is that caused by CPU or am I missing something?

**Comment by niksedk** [comment]
> > cpu with AVX2
> 
> Doesn't work for me. Would that be caused because I use Ryzen CPU? I tried with both base, and large models for Japanese, but the output SRTs were empty. In both cases, the progress bar shows audio extraction, and transcribe finishing in 5 seconds. Is that caused by CPU or am I missing something?

Could you check the se error log? You can also press F2 in the whisper window.

**Comment by dgoryeo** [comment]
@niksedk, embarrasingly the function keys on my keyboard don't work. Can you poin me to where the log file is --I can dig into that.

**Comment by uckthis** [comment]
When I click generate, it extracts audio and then says "No text found". Tried with medium and large EN models.

**Comment by coastal45** [comment]
> OK, it can get faster :) How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip ? SE should now download whisper.cpp in-program to make it easier... requires a cpu with AVX2. Please test :)

Running on a cpu (like mine) that doesn't support AVX, the operation is the same as before, right?

**Comment by niksedk** [comment]
Try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

And download this a "Whisper" folder (beside the "OCR" and "Dictionaries" folders): https://github.com/SubtitleEdit/support-files/raw/master/whisper/whisper.cpp-2022-11-09-SSE2.zip
I assume your cpu has SSE2 ?

**Comment by uckthis** [comment]
> Try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip
> 
> And download + unpack this to a "Whisper" folder (beside the "OCR" and "Dictionaries" folders): https://github.com/SubtitleEdit/support-files/raw/master/whisper/whisper.cpp-2022-11-09-SSE2.zip I assume your cpu has SSE2 ? (Windows only)

This:
![Untitled](https://user-images.githubusercontent.com/28671050/201425045-a3500973-d10d-41fd-9c3a-4a64860a1a0d.png)

**Comment by niksedk** [comment]
@uckthis: It seems that your "SubtitleEdit.exe" and "libse.dll" files are not matching...

SE beta also updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

**Comment by uckthis** [comment]
> @uckthis: It seems that your "SubtitleEdit.exe" and "libse.dll" files are not matching...
> 
> SE beta also updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

Back to square one.... :(

![Animation](https://user-images.githubusercontent.com/28671050/201490004-17dcd857-e41c-461b-bab2-19892a6df7a0.gif)

**Comment by niksedk** [comment]
Check the file `error_log.txt`

**Comment by uckthis** [comment]
> Check the file `error_log.txt`

`
-----------------------------------------------------------------------------
Date: 11/12/2022 23:48:03
Message: Calling whisper-CPP with : E:\Softwares\Utilities\Subtitles editor\SubtitleEdit\SubtitleEdit 3.6.8 Portable\SE368\Whisper\whisper.exe --language "en" --model "E:\Softwares\Utilities\Subtitles editor\SubtitleEdit\SubtitleEdit 3.6.8 Portable\SE368\Whisper\Models\medium.en.bin" --output-srt --max-len 1 --fp16 False "C:\Users\Waqas\AppData\Local\Temp\e8a7c88b-a7ff-4c58-b503-e21636d88acc.wav"
Wav file name: C:\Users\Waqas\AppData\Local\Temp\e8a7c88b-a7ff-4c58-b503-e21636d88acc.wav
-f FNAME, --file FNAME     input WAV file path

-m FNAME, --model FNAME    model path (default: E:\Softwares\Utilities\Subtitles editor\SubtitleEdit\SubtitleEdit 3.6.8 Portable\SE368\Whisper\Models\medium.en.bin)

-l LANG,  --language LANG  spoken language (default: en)

-nt,      --no_timestamps  do not print timestamps

-pc,      --print_colors   print colors

-ps,      --print_special  print special tokens

-owts,    --output-words   output script for generating karaoke video

-osrt,    --output-srt     output result in a srt file

-ovtt,    --output-vtt     output result in a vtt file

-otxt,    --output-txt     output result in a text file

--translate      translate from source language to english

-v,       --verbose        verbose output

-wt N,    --word-thold N   word timestamp probability threshold (default: 0.010000)

-ml N,    --max-len N      maximum segment length in characters (default: 1)

-mc N,    --max-context N  maximum number of text context tokens to store (default: max)

-d  N,    --duration N     duration of audio to process in milliseconds (default: 0)

-on N,    --offset-n N     segment index offset (default: 0)

-ot N,    --offset-t N     time offset in milliseconds (default: 0)

-p N,     --processors N   number of processors to use during computation (default: 1)

-t N,     --threads N      number of threads to use during computation (default: 4)

-s SEED,  --seed SEED      RNG seed (default: -1)

-h,       --help           show this help message and exit

options:

usage: E:\Softwares\Utilities\Subtitles editor\SubtitleEdit\SubtitleEdit 3.6.8 Portable\SE368\Whisper\whisper.exe [options] file0.wav file1.wav ...

error: unknown argument: --fp16
Calling whisper-CPP done in 00:00:00.8056948
Loading result from STDOUT


`

**Comment by niksedk** [comment]
Could you attach the video/audio file?

Does this one work for you: https://github.com/SubtitleEdit/subtitleedit/issues/6357#issuecomment-1305944845

**Comment by uckthis** [comment]
Yes, removing --fp16 from the settings did the trick. Thank you, it was a headache. This is my first time using it, so I'm not sure how fast it is or if it's better than Descript, but it's good to have the option.

**Comment by niksedk** [comment]
Whisper seems a bit unstable and timestamps are not very accurate.... but it's good to have the option - and hopefully it will improve over time...

**Comment by darnn** [comment]
I've finally gotten it to work inside SE itself by removing fp16 from the settings, but the results are not exactly presentable, it seems to have placed every chunk (a syllable or so) in its own subtitle.
[rk2.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/9995734/rk2.srt.txt)

**Comment by uckthis** [comment]
If the audio is clean, and I don't want to consume my minutes, I generally use Adobe Premiere, and it is almost as good as Descript. And I do not want these models to improve a lot of we'll be out of a job... :D

**Comment by niksedk** [comment]
@darnn: Did you enable post processing?

**Comment by darnn** [comment]
Yes. It helps, but very little. Attaching results with it on and off.
[rk2.zip](https://github.com/SubtitleEdit/subtitleedit/files/9995745/rk2.zip)

**Comment by patarapolw** [comment]
I think it's probably best to have explicit choice between whisper and whisper.cpp (and vosk). The result of whisper and whisper.cpp aren't the same.

whisper.cpp often doesn't transcribe theme songs at all.
