### ISSUE TITLE
Import SUP to OCR window doesn't resize correctly on Linux (mono) (see screenshot).

### ISSUE THREAD

**Issue by Mangoes** [SubtitleEdit/subtitleedit#6364]
The Problem:

It's impossible to increase the size of the subtitle text list in the import to OCR window as it doesn't resize correctly.

System: Linux/mono.

See the screenshot.
![SubtitleEdit Linux BUG](https://user-images.githubusercontent.com/2153273/198037745-515aa868-ea18-4885-8c40-c807bd473b5c.png)

Thanks in advance for fixing this.

**Comment by niksedk** [comment]
thx - hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

**Comment by Mangoes** [comment]
Yes, the fix is perfect. Thanks !
