### ISSUE TITLE
Crash when trying whisper

### ISSUE THREAD

**Issue by dgoryeo** [SubtitleEdit/subtitleedit#6365]
I get the following error:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/113683958/198109813-47b88637-2066-46bc-a522-5d42185579a1.png">

My environment:
Win 11
Insatlled from installer --as upgrade previous version
Whisper works in my CLI (py-env)

**Comment by coastal45** [comment]
How did you install Whisper?

**Comment by dgoryeo** [comment]
I installed Whisperf from git: pip install git+https://github.com/openai/whisper.git

**Comment by dgoryeo** [comment]
$python -m site gives me these paths:

    'C:\\Users\\U1\\.pyenv\\pyenv-win\\versions\\3.9.13\\python39.zip',
    'C:\\Users\\U1\\.pyenv\\pyenv-win\\versions\\3.9.13\\DLLs',
    'C:\\Users\\U1\\.pyenv\\pyenv-win\\versions\\3.9.13\\lib',
    'C:\\Users\\U1\\.pyenv\\pyenv-win\\versions\\3.9.13',
    'C:\\Users\\U1\\AppData\\Roaming\\Python\\Python39\\site-packages',
    'C:\\Users\\U1\\.pyenv\\pyenv-win\\versions\\3.9.13\\lib\\site-packages',
    'C:\\Users\\U1\\.pyenv\\pyenv-win\\versions\\3.9.13\\lib\\site-packages\\win32',
    'C:\\Users\\U1\\.pyenv\\pyenv-win\\versions\\3.9.13\\lib\\site-packages\\win32\\lib',
    'C:\\Users\\U1\\.pyenv\\pyenv-win\\versions\\3.9.13\\lib\\site-packages\\Pythonwin',

**Comment by niksedk** [comment]
You can try to point to `whisper.exe` manually in Settings.xml - point `WhisperLocation` to the full path.

**Comment by dgoryeo** [comment]
Afteradding whisper.exe in settings.xml, I get the folloeing error:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/113683958/198827632-1967f6bb-13b3-493b-b4a1-9392aacdcac1.png">


This is the line in xml:
  <WhisperLocation>C:\Users\U1\.pyenv\pyenv-win\versions\3.9.13\Scripts\whisper.exe</WhisperLocation>

**Comment by aykutx25** [comment]
setup python 3.10 version! this is very important. I try 3.11 but not working. Select path c:/python and install other components. very important here copy ffmpeg.exe to system32 and syswow64 folders. good luck.
