### ISSUE TITLE
No text error whisper!

### ISSUE THREAD

**Issue by aykutx25** [SubtitleEdit/subtitleedit#6366]
Hi I setup everything but still get no text error! what should I do? please help!

**Comment by coastal45** [comment]
Which OS? And what language are you setting in the Whisper dialog box?
Also see https://github.com/SubtitleEdit/subtitleedit/discussions/6328 and https://github.com/SubtitleEdit/subtitleedit/discussions/6300 .

**Comment by aykutx25** [comment]
Hi I solved problem but very bad results.. I hope fixed soon.

**Comment by niksedk** [comment]
The Whisper project is here:  https://github.com/openai/whisper
