### ISSUE TITLE
SubtitleEdit error on latest version

### ISSUE THREAD

**Issue by fredb92264** [SubtitleEdit/subtitleedit#6368]
See attached screen shot
[Windows Forms Thread Exception 20221028.pdf](https://github.com/SubtitleEdit/subtitleedit/files/9892243/Windows.Forms.Thread.Exception.20221028.pdf)

**Comment by niksedk** [comment]
The error message says the video file is in use... so you probably have the video file open in VLC or some other program. 
Close the other program that is locking the mp4 file and try again.
