### ISSUE TITLE
se3.6.8 in linux :audio to text error 

### ISSUE THREAD

**Issue by bfdqs** [SubtitleEdit/subtitleedit#6369]
OS: ubuntu 22
generate text from audio via vosk
vosk model: small-ja-0.22
![image](https://user-images.githubusercontent.com/11681071/198763022-c6350a88-87ed-457e-a68d-347e316c9492.png)

**Comment by coastal45** [comment]
Check out https://github.com/SubtitleEdit/subtitleedit/issues/6071#issuecomment-1229306587 and following posts.
Basically, a symlink is needed between SE and the vosk installation directory.

Also it's documented in SE Linux help pages https://www.nikse.dk/subtitleedit/help#linux under "Audio to text".

**Comment by bfdqs** [comment]
After I installed vosk, it worked fine. Thanks.
