### ISSUE TITLE
Toggle Play/Pause don't work correctly

### ISSUE THREAD

**Issue by Base-115** [SubtitleEdit/subtitleedit#6370]
Hi there, first, thank you for the great software.

My problem is:

_In main computer, when I use the keyboard shortcut *Toggle Play/Pause*, generally, the video play and stop in sequence. So, I need to press the shortcut a fewer times until it's finally play and not stop._

I used the portable version of the software, but I try out too the installer version and the problem keeps going.

I tested the software in my notebook and it problem isn't happening. My notebook is a low-end computer, different of my desktop, where the problem is happen, that is a better hardware with AMD graphics card.

I wait for a possible help, thank you! 

Follow the video showing the problem:

https://user-images.githubusercontent.com/112908515/198858613-794bdc5c-2b9a-4d5e-982b-b653c8f689f8.mp4

**Comment by niksedk** [comment]
It works fine here on a fast computer... what shortcut are you using and what video player?

**Comment by Base-115** [comment]
Thank you for reply, niksedk. 🙏 

💡 After to read your comment and the question about the _video player_, I had the idea of change the video engine from **MPC-HC** (that I have used) to **mpv** (how I configed in my _notebook_, I remembered now).

### ✅ Solution
📜 Path to setting (just to mark):

**_Options_ -> _Setting_ -> _Video player_ -> _Video engine_ -> _mpv_**

So the solution is just use the _mpv_ like _video engine_. Seem that MPC-HC have perfomance's issue in _Subtitle Edit_. For me, I don't care to use _mpv_ instead of _MPC-HC, so that's it!

Now, when I press the keyboard shortcut "Toggle play/pause" to play to video, it play without stop in sequence.

_This issue is so dumb, but, ok, now this are documented, 😅_
