### ISSUE TITLE
Download Tesseract 5.00 failed error

### ISSUE THREAD

**Issue by zcraber** [SubtitleEdit/subtitleedit#6371]
Download failed! Please download https://github.com/Subtitle Edit/support-files/raw/master/Tesseract500.tar.gz manually and unpack into this folder: "C:\Users PC\AppData\Roaming\Subtitle Edit Tesseract500\"

The request was aborted: The connection was closed unexpectedly.: at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size) at System.Net.HttpWebRequest.MakeMemoryStream(Stream stream)

![image](https://user-images.githubusercontent.com/61133303/198893139-6fa16b21-6e12-48a1-9b96-1cc469dbd7ca.png)

**Comment by niksedk** [comment]
Download a newer version of SE: https://github.com/SubtitleEdit/subtitleedit/releases
