### ISSUE TITLE
[Feature Request] Skimming

### ISSUE THREAD

**Issue by GrampaWildWilly** [SubtitleEdit/subtitleedit#6372]
I've come across something that I'd like to change in the way SE behaves.  I'm currently using 3.6.8 beta 23 but I'm not sure this is something that is really dependent on the release number.  I don't know if this is a behavior that is new or of long standing.  It's a bit hard to describe so bear with me.

I wanted to skim through this opera I just got online.  It came with a VTT file so of course I opened it with SE.  I thought Alt+DownArrow (and Alt+UpArrow) would skip me quickly through the opera.  But I found that these keys would go to a particular caption, play the associated bit of footage 3 times, and then pause.  This is not how I think it ought to work.  If I have the video playing & I hit Alt+Arrow, or press & hold Alt+Arrow, SE should skip forward one caption, or however many as long as I'm holding down the keys, then resume playback from that point.  Since I started with the video playing, it should continue with the video playing.  Instead it does this play 3 times & pause trick.  On the other hand, if I have paused the video, then SE should skip to whatever caption & remain paused at the beginning of the footage for that caption.  The play 3 times thing is just weird.  But having the playback pause when I had started the operation with it playing is kind of annoying.  The keyboard shortcut should be sensitive to whether the video is playing or paused & maintain whichever mode is in effect at the time I press the keys.

I note in the Shortcut list in the Settings that the 2 Alt+Arrow shortcuts appear to be defined for Translate Mode.  I was in List Mode for my tests.  I'm thinking that this shortcut is good in all modes (although I haven't tested that) so maybe the wording in the settings dialog needs to be adjusted.

In a closely related issue, scrolling through the captions when focus is in the captions list, not the text box, doesn't always act right.  I have held down either DownArrow or PageDown, thinking I would skip through large swaths of captions.  But the highlight keeps jumping back to my starting point.  If I hold the key down long enough, it eventually scrolls down to another caption.  The jumping back to the starting point is just weird.  I think it's anomalous behavior.  Moreover, when I do something like this, the video window should reposition to the footage in the media associated with the selected caption.  Plus, as I described above, the state of playback should also be honored.  That is, if the video was playing, it should continue to play from the new position.  But if the video was paused, it should stay paused, but at the new position.

Perhaps it's relevant that I am using Windows 7 64-bit.  My video controls are undocked.  My video window is on my second monitor (my TV) while the rest of SE is on my primary monitor.  I am using MPV as my video viewer.  If there's some other detail about my system environment you need to know, of course I'll tell you.

I'm not sure how clear this is.  I'll try to make it clearer if you need that.

**Comment by niksedk** [comment]
These repeat things is meant for "translate mode" where these things are very useful:
![image](https://user-images.githubusercontent.com/1261331/198938100-8c45c64f-339e-4ffb-b434-09c4c61aa1bc.png)


You can change to another "tab/mode"... or use "Shift+Enter".

For skimming, you can also select multiple lines, make the playback speed faster, and then do a "play selected lines" (F5).
(you can also change auto-continue to repeat 0 times + auto continue, which is the same as the above)

**Comment by GrampaWildWilly** [comment]
Brilliant!  Thank you so much, Nik!

I never noticed those things before.  I usually just close that window (I run undocked) because it's in the way & I never used anything in there.  I can see where the repeats would be extremely useful for translating.  But since that's not what I generally do, I disabled the auto repeat option & enabled the auto continue option with 0 seconds delay, and now Alt+Arrow works EXACTLY the way I want.

As for scrolling in the caption list, it's weird only while something is playing.  It keeps repositioning to the current caption because that's what it's supposed to do.  I'm a bit slow understanding things sometimes.  When you pause playback, the Arrow & Page keys operate as you would expect.  You just have to hit Enter once you get to your desired caption to make the video reposition to that caption.

I'm back to being a happy camper.  Thanks again, Nik.
