### ISSUE TITLE
[Feature suggest] "minimize to system tray" button in Audio-to-text window

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#6376]
![無題](https://user-images.githubusercontent.com/25927091/199235329-db851139-011b-4a2b-a2f7-196a49805176.png)
A "minimize to system tray" button would be appreciated.

**Comment by niksedk** [comment]
Sure, that's now fixed in https://github.com/SubtitleEdit/subtitleedit/commit/df5a89d768da9c6471029d285ddcd794ccad6331

Also, if the existing time codes are very good, you can try this:
![image](https://user-images.githubusercontent.com/1261331/199277024-0dad465e-ecfd-479c-86e8-d4a0c8c3683b.png)

**Comment by cyzs233** [comment]
Thanks for the patch.
I thought it would be more convenient if the extra selection step could be avoided since we are always select-all anyway (providing better timing). Then I realize I don't even use subtitleedit command line nor do I work on batch converting an entire Show series, so 🤷‍♂️
