### ISSUE TITLE
I deleted all the files in Dictionaries. 

### ISSUE THREAD

**Issue by topmask** [SubtitleEdit/subtitleedit#6377]
The startup speed of subtitleedit is too slow
so, I deleted all the files in Dictionaries. 
This is no problem.
I don't need a language other than English

**Comment by niksedk** [comment]
How long is the startup time for SE on your machine?
Is the startup faster without all files in "Dictionaries"?
Do you use a SSD?

**Comment by topmask** [comment]
CPU   AMD Ryzen 5 3600X 

Memory  16G  3600hz

SSD     WDS250G


It takes 2 to 3 seconds to start
I feel like deleting the dictionary is quicker

**Comment by niksedk** [comment]
If you use the portable version, you might be able to speed the SE startup a little with NGEN: https://learn.microsoft.com/en-us/dotnet/framework/tools/ngen-exe-native-image-generator

I've profiled the startup a lot... but if anyone feel like give it a go, do feel free :)
Removing the "Plugins" folder can help, but I do not think the Dictionaries folder does too much difference.

**Comment by topmask** [comment]
I use the portable version
No Plugins" folder 
How NGEN compiles SE

**Comment by niksedk** [comment]
for ngen... start a cmd prompt. 
CD to "C:\Windows\Microsoft.NET\Framework64\v4.0.30319" (or similar)
Run something like "ngen install "C:\Data\Tools\SE\SubtitleEdit.exe""

**Comment by topmask** [comment]
Microsoft (R) CLR Native Image Generator - Version 4.8.9065.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Failed to load dependency Microsoft.Win32.Registry of assembly NAudio.WinMM, Version=2.1.0.0, Culture=neutral, PublicKeyToken=e279aa5131008a41 because of the following error : The system can not find the file specified。 (exception comes from HRESULT:0x80070002)
All compilation targets are up to date.

**Comment by niksedk** [comment]
OK, try to go to your SE folder, and run:

````
C:\Tools\SubtitleEdit>C:\Windows\Microsoft.NET\Framework64\v4.0.30319\ngen install SubtitleEdit.exe

Microsoft (R) CLR Native Image Generator - Version 4.8.4341.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Failed to load dependency Microsoft.Win32.Registry of assembly NAudio.WinMM, Version=2.1.0.0, Culture=neutral, PublicKeyToken=e279aa5131008a41 because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
2>    Compiling assembly libse, Version=3.6.8.33, Culture=neutral, PublicKeyToken=null (CLR v4.0.30319) ...
1>    Compiling assembly C:\git\subtitleedit\SubtitleEditBeta\SubtitleEdit.exe (CLR v4.0.30319) ...
````

**Comment by niksedk** [comment]
Try again... beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

**Comment by topmask** [comment]
great
Startup is much faster
Do SE still need ngen?

**Comment by niksedk** [comment]
Did you try with "ngen install" ?

**Comment by topmask** [comment]
Microsoft (R) CLR Native Image Generator - Version 4.8.9065.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Failed to load dependency Microsoft.Win32.Registry of assembly NAudio.WinMM, Version=2.1.0.0, Culture=neutral, PublicKeyToken=e279aa5131008a41 because of the following error : The assembly manifest definition found does not match the assembly reference。 (exception comes from HRESULT:0x80131040)
1>    Compiling assembly C:\Program Files\Program Files\Subtitle\Subtitle Edit\SubtitleEdit.exe (CLR v4.0.30319) ...
2>    Compiling assembly libse, Version=3.6.8.48, Culture=neutral, PublicKeyToken=null (CLR v4.0.30319) ...

**Comment by niksedk** [comment]
Oh, you should not get the `Failed to load dependency Microsoft.Win32.Registry of assembly NAudio.WinMM` anymore in latest beta.

**Comment by topmask** [comment]
You mean I don't have to "ngen install" to compile
The new version is a bit faster. Good.
thank you very much
