### ISSUE TITLE
[Feature Request] Extract Audio from Video

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6378]
Hi, I wonder if we could have a tool to extract the audio, say, to a **.mp3** file for 3rd-party auto-transcription or post-processing. etc, or just simply want to caption with the audio because it's much smaller than the hi-res video source).

Even better to allow:

1. Extracting specific track(s) (if there is more than one).
2. Extracting specific channel(s) (R and/or L, in most cases).
3. Extracting a specific section/range.

Many videos have tracks for different languages. Occasionally, even for bilingual dubbing videos, R can be used for one language and L for another, which is kind of weird but I did see both scenarios in the real world...

**Comment by jeesusonherraturku** [comment]
With ffmpeg one can do this with simple commands(copied from web):

.\ffmpeg -i "C:\Users\Me\testvideo.mp4" -map 0:a -c copy sample.m4a

-map 0:a selects all audio streams only. Video and subtitles will be excluded.
-c copy enables stream copy mode. This copies the audio and does not re-encode it. Remove -c copy if you want the audio to be re-encoded.


.\ffmpeg -i input.mkv -map 0:a:3 -c copy output.m4a

-map 0:a:3 selects audio stream #4 only (ffmpeg starts counting from 0).
-c copy enables stream copy mode. This copies the audio and does not re-encode it. Remove -c copy if you want the audio to be re-encoded.

The output file extension has to match what is in the video if using copy mode(no re-encoding).
