### ISSUE TITLE
Whisper crashes when trying to use it

### ISSUE THREAD

**Issue by leonelcba** [SubtitleEdit/subtitleedit#6381]
![Captura de pantalla 2022-11-03 125855](https://user-images.githubusercontent.com/117379507/199771274-a9cdc014-f08f-4f3f-be7d-c91b0661fd41.png)

I get this error when I try to use Whisper in the lastest Subedit beta. I have windows 10 
Is there any solution for this?

**Comment by niksedk** [comment]
Sounds like SE cannot find ffmpeg.exe... probably.
Download ffmpeg in SE via Options - Settings - Waveform... and be sure to run latest SE beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip
