### ISSUE TITLE
SE 3.6.xx Batch Mode → Very Slow & Not Responsive !

### ISSUE THREAD

**Issue by metagondria** [SubtitleEdit/subtitleedit#6383]
Hello,

So, mainly iam using SE for converting subtitles to PGS/SUP format subtitles.
Doing that manually one by one in SE works just perfect, no problem there.

BUT!  As soon i open the batch tool and setup everything like source path, destination path, and put the many subtitles in queue, and hit the convert button.  

SE creates atleast 3 .sup files at once (i have noticed), and is probebly the reason why the process isn't responding correct !!
In task manager i have noticed SE isn't responding from time to time, and utilizes the cpu for like only 12 - 14% ! 
When doing 1 file at an time manually, SE uses 26 - 30 % of my cpu, hence the very slow process in batch mode i mentioned  !

SE slows down so much in batch mode, that i can't even cancel the process, unless i kill it through task manager !!

Iam baffled i HAVE'NT found any posts at all from users having the exact same problem i have had!  This is something that has been happening since the first time i started to use SE in my life...  But haven't created an thread, because SE eventually does the job.  

But it takes much longer in batch mode to convert the subs than it should take (12-14% cpu multiple / batch VS 25-30% cpu single file) !!

Now, i do ALLOTS of editing / encoding / convertions on this pc with 3rd party software like , hybrid, bdrebuilder, Sub2sup, etc etc without an problem.

So, i can't think of one thing about my PC/Settings why this is happening , IF the problem is on my end that is !!

Also important, Iam not using any corrections in Batch mode such as, spell check, sync, etc etc...  That is all done manually by my hand ..

It's not that i don't have the patience for se to complete everything.
But this event is interfering with the playback of video movies i'm watching at the same time iam using SE to batch convert!!!

anyway, any ideas to overcome this are welcome, else thanks for reading :)

PS: Short pc setup descripion:

**MOBO: Asus Sabretooth FX990 r2.0
CPU: FX-8350 @4700
RAM: DDR3-1866Mhz
SSD:  Samsung EVO 850
GPU: RX-6600
OS: Win10 Build  10.0.19045**

cheers,
Metagondria

**Comment by niksedk** [comment]
I'm not really seeing much difference between single and batch convert... 
I do see it's a bit hard to cancel, which I've tried to fix. SE can now abort in the middle of creating a file... not entirely sure it's a good idea though.

I've also played around with threading for "batch convert" and on my computer it's about 5% faster (not much, I know).
How does it work on your computer?

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

**Comment by metagondria** [comment]
Hello nikse,

First of all, i want to thank you for looking into the matter :).

And thank you again, for the test version you've posted for me to try out.  

Question, Is se batch mode suppose to process multiple srt files simultaneously ? 
Iam asking this , because according to an moderator at "videohelp" forums.  The srt files are processed one by one at an time in batch modus !??

But when i put like for instance 4, 8, XX, or any number of srt files in queue for convertion, SE starts to write atleast 3x bluray *.sup files right from the bat !!!??  

even processing 1 srt file suddenly takes a lot MORE of time in batch mode, compared to the amount of time it would take by doing it by myself in se !!  REALY, no JOKE -_- !!

Again, like manually it takes litterally arround 10 secs +/-  ..  In batch mode however, it takes litterally 10x more time to do 1 file !!!

**Comment by niksedk** [comment]
I've done some tests with a 45 kb srt file. 
File - Export - Blu-ray sup, it took 3 seconds.
The same file 10 times in batch convert took 35 seconds... so yes, there is some overhead with batch convert.

Batch convert handles 3 files at a time. I tried with 1 file at a time, but it was not faster.

This bugfixed version can now run after cancelling a run: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

**Comment by metagondria** [comment]
> I've done some tests with a 45 kb srt file. File - Export - Blu-ray sup, it took 3 seconds. The same file 10 times in batch convert took 35 seconds... so yes, there is some overhead with batch convert.
> 

3 seconds is pretty fast , depending wich settings you are using!  Full Frame settings ← comes to mind :).

In my case using Full frame , 1080p resolution it takes aprox about 10 secs with my current hardware of wich i have posted the specs.

> Batch convert handles 3 files at a time. I tried with 1 file at a time, but it was not faster.

EXACTLY my POINT ↑, makes no different wich is very odd !!  SE processes much faster doing it manually ,  in batch mode it takes much much longer to even process 1 file in queue !!  Done the test by just adding 1 srt in batch to watch and see what happends.  And indeed, it makes no difference like you have said :) .
> 
> This bugfixed version can now run after cancelling a run: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

Thanks iam looking forward for some improvements... 

Maybe one suggestion, would it be possible for you to add the option in batch to set an specific amount/number of files that SE processes simultaneously ?  Iam convinced there lies the problem partialy...  That or like you have mentioned, the amount of cpu threads batch mode wants to use may be too much !!

And granted, my cpu isn't known for excellent thread handling :(  (Amd FX-xxxx series) !!
But it did excell in Overclocking ^_^ 👍  hehe..

Thank you very much for the support niks, MUCH obliged 👍 

If there's anything i can do to ease the workload for you let me know, and i will be right on it :) .
As long it doesn't require C++ programming o_0 ..  Iam just an end user :) ..

cheers

**Comment by niksedk** [comment]
I've tried to make bd sup saving use more cpu... not sure if that works for you though if you have a slow/bad cpu: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

Responsiveness was good for me in previous beta... but it's not now as the cpu is pretty busy.

**Comment by metagondria** [comment]
> I've tried to make bd sup saving use more cpu... not sure if that works for you though if you have a slow/bad cpu: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip
> 
> Responsiveness was good for me in previous beta... but it's not now as the cpu is pretty busy.

That's just the thing i want to adress niksen!!  
My desktop seems to be decent and fast enough to process the subs manually, like i have said before.

Only in batch mode, all of an sudden it takes painfully allot of time to process the subs !!  
That ↑  i don't get!!  

I mean, if my system is at fault, shouldn't SE process the subs alway's at the same speed, batch mode or NOT ?

anyway, thanks for looking into it.. 

cheers,

**Comment by niksedk** [comment]
How is the latest beta for you?

Batch convert is more complex than single mode...

**Comment by metagondria** [comment]
> How is the latest beta for you?
> 
> Batch convert is more complex than single mode...


Just done testing latest beta.. → 👍 
You are going in the right direction this time 👍  

You have improved the batch mode by A++ LOT ^^ .  

I have added 3 srts for testing.
And all subs are processed at the same fast speed (maybe faster) like it would be processed manually now..  

DASBUt!! 

SE utilizes now like 99% of all my cpu cores lol 0_0 ... instead of 15% - 30% before..
I guess, watching video's while batch converting subs is wishfull thinking and a thing of the past -_- !!

Anyway , nice done niksen 👍  
I knew it could be improved :), 
It's all a matter of optimizing 👍   

Also..

As for the speed at which batch processes subs and the amount of CPU power and/or threads it requires. 
Would the following have an effect on that, if you now would added the option to let users control how many files SE batch process at the same time ?

AGain, you've pretty much nailed it for the most part 👍  


Thanks allot,

cheers
