### ISSUE TITLE
[Feature Request] Tag & Export FNs (Forced Narratives)

### ISSUE THREAD

**Issue by matmaggi** [SubtitleEdit/subtitleedit#6384]
Hello, I was wondering if it's possible to include a new column called FN (Forced Narrative) here. This new column would be or empty or with "FN".

![image](https://user-images.githubusercontent.com/48259053/199867716-6f64f972-9b4e-4ebc-b1e6-13af39192d1c.png)

I was looking for a way to tag FN lines (like on-screen text, songs, foreign language, etc) with a shortcut and maybe a button here too, like Tag FN/Untag FN.

![image](https://user-images.githubusercontent.com/48259053/199867917-d1b82e85-f7f0-4831-9f08-bd2103cbce04.png)

And then a way to export (or save as) only subtitles tagged as FN.

This would be very helpful! Thank you.

**Comment by uckthis** [comment]
What I do is always write FN in caps. Then I can go to Edit > Modify Selection and select ALL UPPERCASE. (You can add a marker in your FN subtitles to identify them, and then choose that in your Modify Selection. For example, you can add * in all FN lines and then choose Contains in Modify Selection, and it'll select all lines containing * which are FN.) Once done, I Apply and Okay it and then Invert Selection with Ctrl+ Shift + I. This selects everything other than the FN I already selected in Modify Selection and then just delete those lines, and I'm left with FN only.  Or, once you're out of Modify Selection, just press Ctrl+C and paste those in a new file, and you'll have FN only. 

Lastly, you can bookmark FN lines using a custom shortcut and select bookmarks in Modify Selection., but if you have unique mark to identify FN, you will have an option in Modify Selection.

We don't need a new option, as I'd argue that Bookmark is the tag you're looking for.

**Comment by matmaggi** [comment]
That's helpful, @uckthis. Thanks.
