### ISSUE TITLE
[ASSA Efficiency Boost Idea] A much faster way to tweak values

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6385]
First, I have to say that feature is not contradictory to existing ASSA tools. Instead, it will save time dramatically when tweaking values. The workflow is like this: 

1. First, highlight the value that you want to tweak, like this:
![image](https://user-images.githubusercontent.com/494788/200158472-c04dcb7c-4cea-4515-adf6-6818cdadb584.png)
Or, simply put the text cursor within the value for auto-detection, which can be smarter if possible),
2. Add/subtract the value by 1 or 10 by doing a magic operation. I would suggest we do it by modifier keys like Alt + scrolling the mouse wheel up/down for the increment of 1, and Shift + Alt + scroll for the increment of 10, or using other shortcuts.

I propose this because I've been doing ASSA subtitles a lot and I can feel it's sort of a pain to fine-tune values by editing numbers manually, sometimes you have to do trials and errors many times to get ideal values, e..g. when you need to offset existing position by a few pixels. Same as milliseconds, font size, etc. 😞

**Comment by rRobis** [comment]
This would be very useful for me too. I use this on daily basis and it would drastically improve workflow.
