### ISSUE TITLE
Whisper / SubtitleEdit srt result differences

### ISSUE THREAD

**Issue by coastal45** [SubtitleEdit/subtitleedit#6386]
After running Whisper speech to text, SE returns subtitles that can be saved as an srt file (of course).
Also, Whisper itself generates three results files (srt, txt, and vtt) that are saved in the users home directory.

While I noticed this some time ago, I never really checked them. In my case these are Japanese subtitles.

One problem I had with the srt generated by SE is there are many separate lines run together in one subtitle. This requires creating new lines and splitting the text, which takes time.

Then looking at the Whisper generated srt file, the lines are split correctly. Timing still needs some correction (a general issue regarding how whisper works) but each spoken line is separated correctly.

So I wonder how the difference happens. Text samples showing the difference are attached.

[srt files.zip](https://github.com/SubtitleEdit/subtitleedit/files/9946715/srt.files.zip)

[srt files2.zip](https://github.com/SubtitleEdit/subtitleedit/files/9946734/srt.files2.zip)

**Comment by niksedk** [comment]
Is this any better: https://github.com/SubtitleEdit/subtitleedit/issues/6357#issuecomment-1309397041

**Comment by coastal45** [comment]
> Is this any better: [#6357 (comment)](https://github.com/SubtitleEdit/subtitleedit/issues/6357#issuecomment-1309397041)

No, it's still the same. I ran another sample attached if you want to confirm it. Japanese, small model.

I guess my point is that I wonder why the whisper generated srt file is correct (properly separated lines), but the one displayed in SE is different.
To get around this, I just open the whisper generated srt file in SE and then proceed.

So it's not really a problem for me, but I wonder why the difference occurs.

[srt file3.zip](https://github.com/SubtitleEdit/subtitleedit/files/9986527/srt.file3.zip)

**Comment by niksedk** [comment]
Could you attach the audio file?

**Comment by coastal45** [comment]
> Could you attach the audio file?

It's in the zip file.

**Comment by niksedk** [comment]
SE logs a lot more in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip
See `error_log.txt` in the SE data folder.

SE now uses the result from the output file (if SE can find it).

It seems whisper has a hard time outputting Japanese as far as I can see.

````
UnicodeEncodeError: 'charmap' codec can't encode characters in position 26-33: character maps to <undefined>

return codecs.charmap_encode(input,self.errors,encoding_table)[0]

File "C:\Users\nikse\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode

print(f"[{format_timestamp(start)} --> {format_timestamp(end)}] {text}")

File "C:\Users\nikse\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\transcribe.py", line 165, in add_segment

add_segment(

File "C:\Users\nikse\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\transcribe.py", line 204, in transcribe

result = transcribe(model, audio_path, temperature=temperature, **args)

File "C:\Users\nikse\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\transcribe.py", line 298, in cli

sys.exit(load_entry_point('whisper==1.0', 'console_scripts', 'whisper')())

File "C:\Users\nikse\AppData\Local\Programs\Python\Python310\Scripts\whisper-script.py", line 33, in <module>
````

**Comment by coastal45** [comment]
Using same audio file, with beta 95 I got this error and never completed.

![Screenshot from 2022-11-12 12-05-46](https://user-images.githubusercontent.com/102390147/201493657-a51a1afc-8260-4823-8dad-7831199c3dfb.png)

I noticed in beta 70 a few days ago it created a Whisper folder like this:

![Screenshot from 2022-11-12 12-10-45](https://user-images.githubusercontent.com/102390147/201493691-b9b41035-5043-4c66-8ca5-430413660c40.png)

 but not in beta 90. This seems to be a handy way for SE to find the Whisper output file.

 Nothing to speak of in the error log files.
[error_logs.zip](https://github.com/SubtitleEdit/subtitleedit/files/9995885/error_logs.zip)

**Comment by niksedk** [comment]
You have probably enabled Whisper CPP - to use whisper.cpp you must download/compile https://github.com/ggerganov/whisper.cpp:
1) `git clone https://github.com/ggerganov/whisper.cpp.git`
2) Compile whisper.cpp using make or cmake
3) Copy `main` to [SE-DataFolder]\Whisper

You can control using whisper.cpp or the default Python one by edit the settings `UseWhisperCpp` in the file `Settings.xml`

**Comment by coastal45** [comment]
> You have probably enabled whisper.cpp (the faster c++ version). To use whisper.cpp you must download/compile https://github.com/ggerganov/whisper.cpp:
> 
>     1. `git clone https://github.com/ggerganov/whisper.cpp.git`
> 
>     2. Compile whisper.cpp using make or cmake
> 
>     3. Copy `main` to [SE-DataFolder]\Whisper
> 
> 
> You can control using whisper.cpp or the default Python one by edit the settings `UseWhisperCpp` in the file `Settings.xml`

No I didn't. Still just Python installed version. Nothing changed since Whisper first supported in SE.
Going back to release version 3.6.8, it works correctly.

**Comment by coastal45** [comment]
> You have probably enabled whisper.cpp (the faster c++ version). To use whisper.cpp you must download/compile https://github.com/ggerganov/whisper.cpp:
> 
>     1. `git clone https://github.com/ggerganov/whisper.cpp.git`
> 
>     2. Compile whisper.cpp using make or cmake
> 
>     3. Copy `main` to [SE-DataFolder]\Whisper
> 
> 
> You can control using whisper.cpp or the default Python one by edit the settings `UseWhisperCpp` in the file `Settings.xml`

Did SE change that recently? AFAIK, I didn't do anything related. Still just Python installed version.
I haven't changed anything in my system since Whisper first supported in SE.
Going back to release version 3.6.8, it works correctly.

**Comment by niksedk** [comment]
What is your `UseWhisperCpp` setting?

**Comment by niksedk** [comment]
Some minor improvements for whisper detection in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

I was able to get both whisper php + whisper cpp versions running on Windows + Ubuntu...

**Comment by coastal45** [comment]
> What is your `UseWhisperCpp` setting?

Setting is "False".

**Comment by coastal45** [comment]
> Some minor improvements for whisper detection in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip
> 
> I was able to get both whisper php + whisper cpp versions running on Windows + Ubuntu...

I appreciate your efforts, but to keep this from getting too complicated, perhaps it would be better to keep php / cpp operation separate, maybe by a separate selection in the "Video" menu?

As for me, I don't need cpp version at all, so it's operation could be skipped this way.

**Comment by niksedk** [comment]
OK, I've updated whisper.cpp and now just compiled with "SSE2" which I assume most CPUs support. 
Not really much performance difference between whisper.cpp with SSE2/AVX2.

Does this beta work for you on Windows: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip ?

**Comment by coastal45** [comment]
So far I haven't got the SE whisper function to work on Windows, as in this issue, https://github.com/SubtitleEdit/subtitleedit/discussions/6328
Same result for this beta.

As a result I'm only running whisper on Linux (Ubuntu 20.04).

**Comment by coastal45** [comment]
I still get "No text found!". Error log is attached. Looks like it only took ~1 sec.
Not enough time to check the F2 log. As before, command line operation works correctly, though I can't use exact wav file in temp directory as you delete it. Can it not be deleted? Or use/save it in an SE directory rather than user temp location?

Anyway, I think some extra check points or logging are needed. 
 
This same problem also happened in release version 3.6.8, though it ran about 10 sec. longer before failing. So I think the problem is more basic, but I can't tell why.

[error_log.txt](https://github.com/SubtitleEdit/subtitleedit/files/10027650/error_log.txt)

**Comment by hendrack** [comment]
> I still get "No text found!". Error log is attached. Looks like it only took ~1 sec. Not enough time to check the F2 log. As before, command line operation works correctly, though I can't use exact wav file in temp directory as you delete it. Can it not be deleted? Or use/save it in an SE directory rather than user temp location? Reason being, then you can copy exact command SE sends to whisper on a command line.
> 
> Anyway, I think some extra check points or logging are needed.
> 
> This same problem also happened in release version 3.6.8, though it ran about 10 sec. longer before failing. So I think the problem is more basic, but I can't tell why.
> 
> [error_log.txt](https://github.com/SubtitleEdit/subtitleedit/files/10027650/error_log.txt)

Go here for Linux fix: https://github.com/SubtitleEdit/subtitleedit/issues/6433#issuecomment-1320862323
Windows howto: https://github.com/SubtitleEdit/subtitleedit/issues/6324#issuecomment-1319105747

**Comment by niksedk** [comment]
OK, latest beta (probably very close to SE 3.6.9 now have a small context menu, to make things easier to switch between php and cpp version + allow keeping temp files).

Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/202909944-b6a2e161-fc53-4ba2-a464-c4429a6759d3.png)

I'm pretty sure not all videos or all people will/can work with whisper...
