### ISSUE TITLE
how to hide style codes‏‏

### ISSUE THREAD

**Issue by rezamxc** [SubtitleEdit/subtitleedit#6390]
Hi
How to hide style codes in subtitle edit?
Is there such an option?
I intend to translate animes, but style codes are annoying. If they can be hidden during translation, it will be much easier.

**Comment by niksedk** [comment]
I do not think this is possible with advanced formatting, sorry.
Could you give some examples of what you want translated? ASSA or just italic tags?

**Comment by rezamxc** [comment]
### For example
<a href="https://ibb.co/bWBfvFf"><img src="https://i.ibb.co/bWBfvFf/Capture.png" alt="Capture" border="0"></a> <a href="https://ibb.co/HGnrkw4"><img src="https://i.ibb.co/HGnrkw4/Capture1.png" alt="Capture1" border="0"></a>

**Comment by niksedk** [comment]
Sorry, no way to hide style codes.
