### ISSUE TITLE
Slowness in opening the menu.

### ISSUE THREAD

**Issue by ErTenebra** [SubtitleEdit/subtitleedit#6393]
I wonder if this is a problem of mine or not.
I use Subtitle edit on Windows 7 32 bit.
Since I installed the last version, 3.6.8, the first time I right-click on a line of subtitle, it takes ages to open the menu. Usually something like 1 minute. After it works regularly.  I never had such problem with previous versions, the first right click opened immediately the menu. Anyone else has this behaviour?

**Comment by ErTenebra** [comment]
> Thx for the feedback - is this beta better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip ?

Unluckily not.  Clearly i have no idea about the reason, but I have the feeling this is someway connected to the waveform. 
I mean, the tool is fantastic and I have no problem to wait that minute, so no need that you go crazy trying to find the cause ;)

**Comment by niksedk** [comment]
He, ok  - please test again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

I've made some changes recently that might cause this delay... it would be nice to get it working properly for SE 3.6.9.

**Comment by ErTenebra** [comment]
Well, I'm tring right now last beta, and seems like it works fine now! I recreated the same conditions and it now opens the menu immediately :)

**Comment by niksedk** [comment]
Thx for reporting and testing :)
