### ISSUE TITLE
[Feature Request] Batch feature for external OCR (export sup to png and import txt)

### ISSUE THREAD

**Issue by Ninelpienel** [SubtitleEdit/subtitleedit#6397]
It would be great if the png export with timestamps could also be done with multiple sup file at once. The same when importing txt files with timstamps. I want to use Abbyy for some Blu-ray subs and exporting and importing every single file seperatly is really exhausting.

**Comment by niksedk** [comment]
I'm not really sure what you a trying to do... a few screenshots might help?

**Comment by Ninelpienel** [comment]
I need this png export function

![image](https://user-images.githubusercontent.com/1890524/200930275-79dcc65d-e4a7-4736-b9ce-5f22e263d536.png)

and this plain text import function

![image](https://user-images.githubusercontent.com/1890524/200930604-1d06a9df-ef90-4670-b234-0dfdbb148340.png)

as batch convert feature.

**Comment by Ninelpienel** [comment]
I don't mean to be pushy, but are you interested in implementing this feature? It's really exhausting to do all this manually. :/

**Comment by niksedk** [comment]
How does this work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip ?

![image](https://user-images.githubusercontent.com/1261331/216433080-7ed93e76-26ed-4102-8a7f-b120d32b1f1d.png)

**Comment by Ninelpienel** [comment]
> How does this work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip ? Tools - Batch convert, Choose last "output format":
> 
> ![image](https://user-images.githubusercontent.com/1261331/216433080-7ed93e76-26ed-4102-8a7f-b120d32b1f1d.png)

That's almost perfect, thanks, but it seems the "ocr image proprocessing" is missing.

![image](https://user-images.githubusercontent.com/1890524/216443864-dfbc392e-c712-4806-af24-562a7e8bb211.png)

![0_00_08_800__0_00_10_469_01](https://user-images.githubusercontent.com/1890524/216443935-7e61ed29-65dd-4df0-88a9-061b298b153a.png)

Without it, ocr is really hard. Abbyy wants black text on a white background.

**Comment by niksedk** [comment]
OK, does this work for you? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by Ninelpienel** [comment]
> OK, does this work for you? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

Yep, that's perfect! Thank you so much!

Now, if you add the possibility to insert folders with plain text (multiple files) in the batch conversion, then I could convert the subs that I ocred with Abbyy to .ass batchwise. That would optimize my workflow.

**Comment by Ninelpienel** [comment]
There is also a small bug: I have to hit the setting button one time, otherwise the ocr preprocessing will not work.
