### ISSUE TITLE
Right mouse button opens this

### ISSUE THREAD

**Issue by Tainted-love** [SubtitleEdit/subtitleedit#6400]
Right mouse button opens this
![Capturar](https://user-images.githubusercontent.com/117912702/201086424-cb745722-66c8-413e-9927-262a66cd184c.JPG)

**Comment by niksedk** [comment]
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip
