### ISSUE TITLE
Whisper with Silero VAD

### ISSUE THREAD

**Issue by caytienkuagai99** [SubtitleEdit/subtitleedit#6411]
I've seen them combine Whisper with a Silero VAD for long-form recovery and I've heard it's better than Whisper alone. You can research to incorporate it.
https://colab.research.google.com/github/ANonEntity/WhisperWithVAD/blob/main/WhisperWithVAD.ipynb#scrollTo=qGS9GFEnOoB_
![image](https://user-images.githubusercontent.com/32349700/201467771-e33ab3c8-a745-4df7-95dc-6c0523aa428b.png)

**Comment by niksedk** [comment]
I've no clue about this, sorry.

**Comment by niksedk** [comment]
I do hope that somebody will make time codes more accurate in whisper.
(I'm not a Python developer)
