### ISSUE TITLE
Whisher install

### ISSUE THREAD

**Issue by MrKidzZ** [SubtitleEdit/subtitleedit#6412]
I installed SE 3.6.8 Beta
install git: pip install git+https://github.com/openai/whisper.git
run whisper and path error. Is there any way to fix it?
![2](https://user-images.githubusercontent.com/118055655/201473637-98c29378-5da7-4f58-a00c-f6ebcd6fb770.PNG)

**Comment by niksedk** [comment]
Thx :)

Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip
