### ISSUE TITLE
Issue with Deepl translation Plugin free api

### ISSUE THREAD

**Issue by soares23** [SubtitleEdit/subtitleedit#6413]
Hi, does some else have today or in the last days that problem?

![Screenshot 2022-11-12 170301](https://user-images.githubusercontent.com/560476/201484872-411de1b1-b04d-4d2f-bd52-c04d3085d2bf.png)

It was says error 400 and after that now 403.

On Monday i don't have any Problem but today this happend.

**Comment by niksedk** [comment]
You should not post your api key... do generate a new one.

I'll try to test in a few days - if nobody else can verify?

**Comment by soares23** [comment]
i have generate after that a new one. And also with the new api key is not working

**Comment by niksedk** [comment]
OK, is latest deepL 1.2 any better for you?

**Comment by soares23** [comment]
yes with deepl pro 1.2 plugin is working again with no issues. Thank's for your great work.
