### ISSUE TITLE
SE won't work with VLC

### ISSUE THREAD

**Issue by Ninko85** [SubtitleEdit/subtitleedit#6414]
Hi,
I've selected VLC player in settings but SE still asks for a video player.
Am I doing something wrong?
Thanks

**Comment by niksedk** [comment]
It's a bug in SE 3.6.8... see more here: https://github.com/SubtitleEdit/subtitleedit/issues/6351

**Comment by Ninko85** [comment]
Ok, thanks

**Comment by niksedk** [comment]
Should be fixed in 3.6.9
