### ISSUE TITLE
Windows Forms Thread Exception on Brand New Installation of SE3.6.8.0 when choosing to use Whisper

### ISSUE THREAD

**Issue by natelawrence** [SubtitleEdit/subtitleedit#6415]
![image](https://user-images.githubusercontent.com/2601664/201503821-ad060f6b-c48b-49f7-aeb2-603a4e9c8cbd.png)

"An application error occurred in Subtitle Edit 3.6.8.0. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information: 

Error Message: 
The system cannot find the file specified

Stack Trace: 
  at  
System.Diagnostics.Process.StartWithCreateProcess(ProcessSta
rtInfo startinfo) 
  at  
Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.Get
WhisperProcess(String waveFileName, String model, String 
language, DataReceivedEventHandler dataReceivedHandler) 
  at 
Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.Tra
nscribeViaWhisper(String waveFileName) 
  at  
Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.But
tonGenerate_Click(Object sender, EventArgs e)
  at  
System.Windows.Forms.Button.OnMouseUp(MouseEventArgs
mevent)
  at System.Windows.Forms.Control.WmMouseUp(Message&
m, MouseButtons button, Int32 clicks)
  at System.Windows.Forms.Control.WndProc(Message& m)
  at System.Windows.Forms.NativeWindow.Callback(IntPtr
hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)"

**P.S. Could you please make your error dialog text copyable so that your users don't have to transcribe an entire long error message (and possibly make mistakes while trying to report them to you)?**

**Comment by niksedk** [comment]
SE whisper support and also whisper is somewhat experimental...

But, you could try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

You should be able to get the text from the error message by pressing "ctrl+c".

**Comment by hendrack** [comment]
Does whisper work standalone? My setup works in Windows, see this: https://github.com/SubtitleEdit/subtitleedit/issues/6324#issuecomment-1319105747
