### ISSUE TITLE
Shortcuts not working outside waveform

### ISSUE THREAD

**Issue by IMANWriter** [SubtitleEdit/subtitleedit#6417]
Hello All,
I, very greatly, appreciate Subtitle Edit.

However, I'm facing an issue that has kept me using v3.6.1. From v3.6.2 on, I cannot seem to work with shortcuts such as "play/pause" or "one second back/forward."
I'm able to use these shortcuts while typing inside the text box, and therefore, conveniently moving back and forth on the video/waveform without leaving the text box. I use D1, D2, and D3 for this purpose.
On v3.6.2 and onwards, however, when I press the shortcuts inside the text box, it types the numbers "1," "2," and "3." Outside the text box, though, (if I remember correctly) the shortcuts work just fine.

Any help is much appreciated.

**Comment by darnn** [comment]
If I recall correctly, you need to set AllowLetterShortcutsInTextBox to True in settings.xml.

**Comment by IMANWriter** [comment]
> 
And my life will be easier from now on. It did work!
Thank you, also, for the quick reply.
