### ISSUE TITLE
Font size in the spell check window

### ISSUE THREAD

**Issue by V3semir** [SubtitleEdit/subtitleedit#6418]
Hello, would it be possible to add an option to change the font size in this window (see attachment)? I'm sitting quite far from my monitor, and have to lean towards it each time I need to input something manually because I can't see quite clearly. My back is starting to give up, haha. 

![Screenshot 2022-11-13 213041](https://user-images.githubusercontent.com/45462483/201543173-5b71b571-2357-4654-9fc1-6255e1357f3c.png)

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip ?
(right click, use larger font size - same as normal spell check)

**Comment by V3semir** [comment]
> How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip ? (right click, use larger font size - same as normal spell check)

That's perfect! Thank you very much! This is so much better!
