### ISSUE TITLE
Punctuation Issue

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#6419]
I tried Subtitle Edit Beta 3.6.8 NEXT, Beta 104 - Used Whisper to Auto transcribe audi but noticed that it's adding a full stop after almost every line. This is not the desired result. 

![punctuation issue](https://user-images.githubusercontent.com/92556454/201733249-4597bb83-837c-4bc0-9a3e-b7d52517f415.png)

Kindly fix this and the character segmentation using Whisper is highly welcome. 

https://youtu.be/ODaDJr_nXkk

Thanks.

**Comment by niksedk** [comment]
Thx for the input - how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip ?

**Comment by MbuguaDavid** [comment]
> Thx for the input - how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip ?

Much better. Thanks!
