### ISSUE TITLE
path access denied!

### ISSUE THREAD

**Issue by bustel2022** [SubtitleEdit/subtitleedit#6421]
when I want to add a new field to put subtitles in, I get this error: path access denied: c:\Users\user\AppData\Local\Packages\Microsoft.Windows.Cortana_cw5n1h2txyewy\AC\Microsoft\Internet Explorer\DOMStore\8P8JSD5E

and I can't get any further. No new blank line is added.

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip
