### ISSUE TITLE
Improving Timecode Display for Compare Tool

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6422]
The problem only occurs for the export result:

![image](https://user-images.githubusercontent.com/494788/202125529-897e4b3a-4d1d-4ebe-aa00-9ec8e79c1dc5.png)

I mean, the timecode should be written in **hh:mm:ss.zzz** for every single line.

**Comment by niksedk** [comment]
Thx - hopefully fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Nice fix Thanks! Just one more thing, maybe it would be even better to widen gaps for columns? As seen below, it's a bit hard to distinguish them. :)
![t](https://user-images.githubusercontent.com/494788/202191123-b210f519-b1c0-47b6-ac06-69cd901b5bd1.png)

**Comment by niksedk** [comment]
OK, is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

If somebody likes html/css, feel free to make a better template :)

**Comment by LeonCheung** [comment]
Better! Thanks again.
