### ISSUE TITLE
Importing subs

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#6423]
Some vids have 

```
Text #1
ID                          : 6
Format                      : Timed Text
Muxing mode                 : sbtl
Codec ID                    : tx3g
Duration                    : 2 h 17 min
Bit rate mode               : Variable
Bit rate                    : 48 b/s
Frame rate                  : 0.355 FPS
Stream size                 : 48.0 KiB (0%)
Language                    : English
Default                     : Yes
Forced                      : No
Alternate group             : 2
Encoded date                : UTC 2022-06-16 16:11:46
Tagged date                 : UTC 2022-06-16 16:11:46
tagc                        : public.main-program-content
```
and when i import it the timing are off and adds some spanish subs lines from spanish version of sub into the english subs.

I had to use staxrip to demux the sub and all is well.

Either the importation of subs faulty or perhaps a demux feature in subtitleedit.

**Comment by Ding-adong** [comment]
Errmm no. The sub is inside the file. I have compression the file to 7mb.

https://mega.nz/file/3nQWWTzI#9yWMWjXMuskwyclVb3Cuo9OzoMY_J20UoCzoYvsSYfM

**Comment by niksedk** [comment]
thx :)
Got the file - and can see the issue.

**Comment by niksedk** [comment]
How is this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

Seems to work better...
