### ISSUE TITLE
[Feature suggestion?] Start/End position should affect start/end position of nearby segments when moving them with the waveform

### ISSUE THREAD

**Issue by Danteska** [SubtitleEdit/subtitleedit#6425]
So the title is a bit long but I'll try to explain it. I think this option is not implemented because I can only find "Allow overlap (when moving/resizing)" and that's not it.

If you try to move a segment on the waveform with the mouse, currently (as far as I know) it only affects that segment's start and end time. If you try to "collide" it against the next or previous segment, their start/end times won't change if "allow overlap" is disabled". If "allow overlap" is enabled, they would overlap one another, but this would still not affect the start or end time of the segment that you're *not* moving directly.

So I think there should be a third option. The first one is no overlap, second is overlap and the third one is this:

**Moving a segment *forward* should affect the start (but not the end) time of the *next* segment, but only if they're next to each other.** This is, moving one segment forward should push forward the next one, but this is not the same as moving them in block as this would not affect its end time, effectively shortening its on screen time.
**Moving a segment *backwards* should affect the end (but not the start) time of the *previous* segment, but only if they're next to each other.**

Here's an example:

https://streamable.com/mmixte

I want the nº 662 to end where the vertical blue line is, but moving or expanding 662 doesn't affect the start time of 663, forcing me to do it manually.

This is a feature that is available on Sony Vegas, for example. I notice its absence on SE whenever I'm fixing subs so bad that you need to go line by line to get the correct sync, instead of moving all segments at once. Such lines sometimes end too soon and the next one starts too soon because of that. So if you decide to adjust the end time of one, you'll necessarily have to adjust the start time of the other manually without this option.

Please let me know if this is already an option that exists on SE, as I can't find it. If it doesn't exist, here goes the suggestion.
Also, can you even move segments in blocks on the waveform? Selecting two and moving them at the same time?

**Comment by LeonCheung** [comment]
For adjacent subtitles, have you tried moving start/end while holding Alt key?

**Comment by Danteska** [comment]
> For adjacent subtitles, have you tried moving start/end while holding Alt key? If you really want to offset the whole block(s), [here](https://youtu.be/gFRFJnBX7uA?list=PLRdh-Ktd5fg67KABLKxE2YYjlZr6GKUL2) is some tips (from 06:42)

This works, thank you very much.
