### ISSUE TITLE
Color coding lost when saving in EBU STL format

### ISSUE THREAD

**Issue by 8543** [SubtitleEdit/subtitleedit#6426]
Hi! I need to create subtitles for teletext with assigning different colors for each character. The client needs it in EBU STL. But when I save it or export the work to EBU STL all color coding is lost. An example:
![grafik](https://user-images.githubusercontent.com/33127238/202515193-99536c77-ed97-4f9f-8848-ab293d510627.png)

results after saving it to EBU STL in simple text and all color assignment is lost:
![grafik](https://user-images.githubusercontent.com/33127238/202515234-300ae136-eb74-4734-9505-b272e9b55bed.png)

So is it maybe a bug or does sb know a way to fix this issue?

Thanks a lot!

**Comment by niksedk** [comment]
Make sure you a "Display standard code" with support for colors:
![image](https://user-images.githubusercontent.com/1261331/202745121-48521526-4822-4a96-b0b0-0ebba9a02740.png)

**Comment by 8543** [comment]
Thank you! Of course I'm using this setting for colors in the EBU properties, but nevertheless I'm losing all color assignments after saving it as EBU STL. On the other hand I found out that saving the subtitles as DVD Studio Pro all color setting are kept.  A subtitler friend of mine working with EZTitles was able to save it as EBU STL with keeping all color assignments. So I'm still wondering what's going on here...

**Comment by niksedk** [comment]
Sorry, I cannot re-create your issue.
