### ISSUE TITLE
New Time - Offset the Rest

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#6429]
Recently I did many files where I had to adjust the times. E.g, 00:00:08:06 to 08:15:00:00 or 00:02:09:002 to 16:05:04:00 and so on and so forth. I used Adjust all Times option and manually put the new timecodes and then Show Later and then show earlier... I'm hopeless at math, so had to use a calculator to figure out 33+14=47 or whatnot. This gave me an idea that instead of doing show later and show earlier multiple times, we just enter the new timecode and the click this hypothetical New Time - Offset The Rest, and it'll do all the calculation and +- all by itself. It is quite similar to Set Video Offset, but this one is specifically listed in Adjust All Times and is quicker and easier.

Two:
I had to manually type all the time codes. I had the time codes in an Excel sheet, but copy/pasting wasn't working in Adjust All Times, so copy/paste would help as well. 

Thank you.

**Comment by niksedk** [comment]
I suggest use the waveform - set start and offset the rest - also has a shortcuts which is `Mouse single click+Ctrl+Shift`
https://www.nikse.dk/subtitleedit/help#waveform

**Comment by uckthis** [comment]
> 

I know about that shortcut. These files didn't come with a video file. We were just given new start time codes and subtitle files..

**Comment by LeonCheung** [comment]
TBH, I second this feature. Personally, I also feel I need this sometimes, I mean, to save the calculation when you only know the target pos. True that we can use the shortcut trick, but it's really hard when you need to set an accurate pos by a simple click. I would propose something like this, just my two cents:

![as_target](https://user-images.githubusercontent.com/494788/202841990-b875ced9-7afa-4671-be0d-edb4b2bc74c6.png)
