### ISSUE TITLE
Slow Performance in Version 3.6.8 with .dfxp /Timed Text 1.0.xml

### ISSUE THREAD

**Issue by AE-Ismail** [SubtitleEdit/subtitleedit#6436]
Hello,
I'm using Subtitle Edit 3.6.8 installed on a Windows 11 PC with 32 GB of RAM.
I've been using it for many years with no problem at all, however, two days ago, I received .dfxp project files from a client 
and faced a strange lag from the application.
Whenever I try to edit any line, it takes up to 2 seconds to delete or write any letter or to even respond.
I'm using the Translator mode as usual, but with this specific file format the software is lagging.
I'm attaching a video of the issue:
https://drive.google.com/file/d/1CENILTKZ_EAXGKPdw1vz3hLo_Mx7i8_c/view?usp=sharing

Thank you all for your help.

**Comment by niksedk** [comment]
Does it also happen with mpv as video player?

What uses the cpu in task manager?

**Comment by AE-Ismail** [comment]
Yes, I'm using MPV as the video player.
I canceled autosave and it helped a little.
Subtitle Edit uses around 10-12% of an AMD 5 2400g CPU as attached.

![2022-11-20_00-41-46](https://user-images.githubusercontent.com/118636398/202874368-ab9e4add-22cb-48aa-ad6d-7decb8c34349.png)

**Comment by niksedk** [comment]
Sorry, I cannot re-create this... anybody else having this issue?

Does a clean portable version work any better?

**Comment by AE-Ismail** [comment]
I tried the portable version, and it's the same thing.
When I uncheck the autosave option, it gets a bit faster, but still lags a lot.
I also tried the new version 3.6.9 but nothing changed.

**Comment by niksedk** [comment]
SE works with other subtitle files/videos just fine on your computer?
Could you attach or email the dfxp file?

**Comment by AE-Ismail** [comment]
Yes, the application works perfectly with any other file type and videos with any video player.
The dfxp files are confidential, do you mind sending them directly on e-mail?

**Comment by niksedk** [comment]
That will be fine... and any video with this dfxp file gives the slow performance?

**Comment by AE-Ismail** [comment]
Now, I uninstalled the program completely, deleted any related files from the system, and did a clean installation of version 3.6.9 without changing any settings at all, whether the video player or waveform extraction; and it's the same thing with this file extension.

**Comment by niksedk** [comment]
Sorry, I still cannot re-create the issue.... I am also on Win11 w 32 GB ram, cpu i7-1065G7
Also tried a performance profiler, but that did not show anything either.

I did have some poor performance when using MPC-PC video player... mpv is better.

**Comment by AE-Ismail** [comment]
I think I figured out what was wrong.
The file format is .dfxp as shown on Windows explorer, but when I open SE it shows that the format is Timed Texr 1.0.xml.
Once I choose .dfxp from the drop-down menu, the program works fine.
But this costs me the custom formatting of the original file as received from the client.

<img width="518" alt="2022-11-24_00-47-21" src="https://user-images.githubusercontent.com/118636398/203658924-e960881b-d350-4721-85cb-dbada0a9e465.png">
