### ISSUE TITLE
Whisper. cpp issue

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#6437]
I'm running into the issue attached once I try to download Whisper.cpp in 3.6.9. 
![Error - Subtitle Edit 3 6 9](https://user-images.githubusercontent.com/92556454/202926987-557e504c-a7e1-4a54-a219-a80bf6dc8562.png)

Hopefully we'll get a fix.

**Comment by hendrack** [comment]
Whisper.cpp uses CPU decoding and the cpu needs AVX2 instruction set.

**Comment by niksedk** [comment]
SE is missing a dll file... will update SE soon...

**Comment by niksedk** [comment]
SE 3.6.10 is out: https://github.com/SubtitleEdit/subtitleedit/releases
