### ISSUE TITLE
[Bug] Downloads doesn't work

### ISSUE THREAD

**Issue by Purfview** [SubtitleEdit/subtitleedit#6439]
Downloads doesn't work on Windows 7 x64 / v3.6.9

![This is an image](https://i.imgur.com/PHd3bed.png)

I think that 3.6.4 was the last version when downloads worked properly.

**Comment by niksedk** [comment]
@Purfview: It's works fine here. Are you behind a firewall or something similar? What OS are you using?

**Comment by niksedk** [comment]
This beta should log a bit more: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.9/SubtitleEditBeta.zip

Perhaps a dotnet framework 4.8 install would help?
https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

**Comment by Purfview** [comment]
.NET 4.8 is installed (latest SE doesn't work without it).

Here is error message from the log:
```
Message: DownloadAsync failed

System.Net.Http.HttpRequestException
Message: An error occurred while sending the request.
StackTrace:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()
System.Net.WebException
Message: The request was aborted: Could not create SSL/TLS secure channel.
StackTrace:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
```

**Comment by niksedk** [comment]
Thx for the log :)
Is this any better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.9/SubtitleEditBeta.zip ?

**Comment by Purfview** [comment]
> Thx for the log :) Is this any better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.9/SubtitleEditBeta.zip ?

No, same error.

**Comment by niksedk** [comment]
Does this help?
https://stackoverflow.com/questions/63352796/error-in-windows-7-the-request-was-aborted-could-not-create-ssl-tls-secure-cha

**Comment by Purfview** [comment]
Yes, that reg fixed it.

But why v3.6.4 was OK, and why Afrikaans dictionary still worked without this reg tweak?

**Comment by niksedk** [comment]
It might have something to do with what the servers in the opposite end requires - and they (e.g. Github) up the requirements once in a while.

**Comment by Purfview** [comment]
Installed v3.6.4 and 'Arabic' download works with that reg removed, so it's not "the servers in the opposite end".

**Comment by niksedk** [comment]
OK, It might not then...
