### ISSUE TITLE
Error when trying to use whisper audio to text module

### ISSUE THREAD

**Issue by RYucel** [SubtitleEdit/subtitleedit#6441]
![subedit_error](https://user-images.githubusercontent.com/24809488/203042095-503989c5-7dda-4995-8efc-9d7b4e414097.png)

How can we solve this issue on windows 10 machine? I am receiving this error while to install this new module on my machine.

**Comment by niksedk** [comment]
thx :)

Should be fixed in 3.6.10: https://github.com/SubtitleEdit/subtitleedit/releases

A dll file was missing
