### ISSUE TITLE
BDN-XML always falls back on the default resolution DCI 2K Scoper

### ISSUE THREAD

**Issue by saalmedia** [SubtitleEdit/subtitleedit#6444]
It would be great if the pre-defined resolution would be the last value.

**Comment by niksedk** [comment]
What are you doing and where? Screenshots are welcome :)

**Comment by saalmedia** [comment]
File -> Export -> BDN XML/png
Video res: Dropdown is always DCI 2K Scope (2048x858)
-> I change it to 1080p (1920x1080)
-> Export all lines...
-> After exporting, I leave the export window
File -> Export -> BDN XML/png
Video res: The dropdown is always DCI 2K Scope (2048x858) and not the value I have chosen before

As I can see, every other parameter is still the previously defined value - except for "video res."

**Comment by niksedk** [comment]
Hm, works fine here... it uses the video resolution if a video is loaded though.
