### ISSUE TITLE
[Feature Request]Some subtitles lines exported by whisper are too long，can split long line by any chars add to batch mod？

### ISSUE THREAD

**Issue by i990049** [SubtitleEdit/subtitleedit#6446]
![屏幕截图(155)](https://user-images.githubusercontent.com/103364093/203260587-9b1da3a6-b10c-4eeb-ae8d-c91f16dd3083.png)
![屏幕截图(156)](https://user-images.githubusercontent.com/103364093/203261543-2d5e838d-a070-4f81-a14c-1d4f60ed519e.png)
I hope the batch convert mode can batch split long lines according to the settings.
<img width="960" alt="屏幕截图(157)" src="https://user-images.githubusercontent.com/103364093/203262373-ec8f19c8-6ac2-47c8-9f6c-0a22f79fdfa0.png">

https://wwi.lanzoup.com/idAwt0giqywh
Here is the test ass，the settings will show which lines are more than 19 characters.

**Comment by niksedk** [comment]
Could you attach a small audio file with... is that Chinese?
Could you attach the file `error_log.txt` ?

**Comment by i990049** [comment]
> Could you attach a small audio file with... is that Chinese? Could you attach the file `error_log.txt` ?

![屏幕截图(158)](https://user-images.githubusercontent.com/103364093/203390948-1698d1e8-fa22-45d0-9ab8-fcda04f22cb0.png)
Maybe you haven't understood what I mean, voice translation is no problem, the problem is that after translating into other languages and merging subtitles, the length of subtitles needs to be controlled, and the length of each Chinese character and alphabet text is different. This is the audio processed by izotope, click the red button to download the audio. This is another subtitle I made, each line Chinese and English are a separate line, you can see that the maximum number of Chinese words in each line is not the same as the maximum number of English words, Chinese characters are much wider than English.
audio in Italian
https://wwi.lanzoup.com/iaGoB0gn0s5i
another ass already well done
https://wwi.lanzoup.com/iqvWZ0gn10fg

**Comment by niksedk** [comment]
Could you attach the `error_log.txt` too ?

**Comment by i990049** [comment]
> 

There is no error_log.txt, because SE just can't batch split Chinese subtitle no more than 19 characters.It just can't work.You can try the first link ass file above.

**Comment by niksedk** [comment]
Whisper should also log to `error_log.txt` - are you using latest SE?
