### ISSUE TITLE
[Issue] Google Cloud Vision OCR not breaking lines correctly

### ISSUE THREAD

**Issue by pyrr** [SubtitleEdit/subtitleedit#6449]
Echoing the issue described by @Flitskikker in #6319, using the Google Cloud API to perform OCR can sometimes lead to lines breaking incorrectly e.g. below:

![image](https://user-images.githubusercontent.com/54674214/203422407-1e678d8b-c0cf-4973-a8c2-1480bc667487.png)

Fortunately we can interpret the response to break the lines ourselves-- as in this code snippet: https://stackoverflow.com/a/54380077

```Python
from google.cloud import vision
client = vision.ImageAnnotatorClient()
image = vision.Image()
image.source.image_uri = <subtitle-image-uri>

response = client.text_detection(image=image)
texts = response.text_annotations

print(texts[0].description)
print("====")

items = []
lines = {}

for text in response.text_annotations[1:]:
    top_x_axis = text.bounding_poly.vertices[0].x
    top_y_axis = text.bounding_poly.vertices[0].y
    bottom_y_axis = text.bounding_poly.vertices[3].y

    if top_y_axis not in lines:
        lines[top_y_axis] = [(top_y_axis, bottom_y_axis), []]

    for s_top_y_axis, s_item in lines.items():
        if top_y_axis < s_item[0][1]:
            lines[s_top_y_axis][1].append((top_x_axis, text.description))
            break

for _, item in lines.items():
    if item[1]:
        words = sorted(item[1], key=lambda t: t[0])
        items.append((item[0], ' '.join([word for _, word in words]), words))

for i in items:
    print(i[1])
```

Yields:

```
I've already
necessary
said what's
to be said.
====
I've already said what's
necessary to be said .
```

Any chance we could see some implementation of this "manual" line breaking in a future version?

[One of the commenters provided a C# implementation.](https://stackoverflow.com/a/71517399)

**Comment by pyrr** [comment]
Here is my (horrifying) attempt at writing a C# equivalent to the python snippet:

https://github.com/pyrr/subtitleedit-pyrr/commit/a86a271f232c96565dfaf5ec953c978ba769d611

**Comment by niksedk** [comment]
OK, I've tried to improve this in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

You need to set `OcrGoogleCloudVisionSeHandlesTextMerge` to `True` in `Settings.xml`.

It's more complex that I thought... and I've not tested it much as I have not created api key+billing currently.

**Comment by pyrr** [comment]
Thank you for working on this! I tried it again and it looks like it accurately breaks the line, but now the words are missing spaces:

![image](https://user-images.githubusercontent.com/54674214/203866750-d3a7ea70-70b5-418f-976f-8b95b1d24fd9.png)

I added a comment to your commit as to where I think this is occurring. If I'm reading it right, instead of a threshold I think you should use the API response for determining spaces. Since you don't have an API key, I've pasted the response I get for this subtitle here: https://pastebin.com/AjpGZtSq

Thanks.

**Comment by Flitskikker** [comment]
@pyrr Could you try setting a background color by playing with the "Image palette" settings?
Based on my testing, Cloud Vision does not like transparent backgrounds.
Maybe also playing with / without shadow could be worth a try.

**Comment by pyrr** [comment]
> @pyrr Could you try setting a background color by playing with the "Image palette" settings? Based on my testing, Cloud Vision does not like transparent backgrounds. Maybe also playing with / without shadow could be worth a try.

Good tip, I tried it with a black background+shadow and it performed a little better:

![image](https://user-images.githubusercontent.com/54674214/203870118-3eee3324-9f83-4eb8-a418-4a072a2d6310.png)

In any case it definitely seems like it should be extracting the spaces from the API instead of using a hardcoded threshold.

**Comment by niksedk** [comment]
OK, now SE also uses space info from the json: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
Better?

**Comment by pyrr** [comment]
It's perfect, thank you so so much!!

**Comment by niksedk** [comment]
Should this new line breaking be default?

**Comment by pyrr** [comment]
I think so, it's broken for me otherwise. Maybe have a toggle on a checkbox so users can play with the setting.

**Comment by Flitskikker** [comment]
Fixed an exception when processing empty images while `OcrGoogleCloudVisionSeHandlesTextMerge` is `True`:
https://github.com/SubtitleEdit/subtitleedit/pull/6463

**Comment by Flitskikker** [comment]
I think a checkbox would be the best choice for now.
The new method works well in 99.5% of the cases, but there could be some problematic images, especially when working with low quality rips (for which Cloud Vision is probably the only and best option).

Two examples in a recent rip:

![0_41_54_800__0_41_59_319_0019200020002860025600320](https://user-images.githubusercontent.com/3516155/204050506-f7d91671-1bf4-447c-9942-3da9517417d9.jpeg)

OcrGoogleCloudVisionSeHandlesTextMerge False:
```
✰
Misschien hebt u gelijk.
Hoe dan ook, we hebben geen keus.
```

OcrGoogleCloudVisionSeHandlesTextMerge True:
`HMoise sdchain en oohke, bwt e u gheeblijbke. n geen keu✰ s.`

---

![0_45_03_640__0_45_07_559_0019200020002860025600320](https://user-images.githubusercontent.com/3516155/204050509-7b2beb5d-2e37-4983-9061-58599aa02128.jpeg)

OcrGoogleCloudVisionSeHandlesTextMerge False:
```
Ze blussen een brand.
-Ze lanceren een raket
ATI
```

OcrGoogleCloudVisionSeHandlesTextMerge True:
`Z-Ze e bllaunssceen reen een ebn rarankde. t ATI`

---

Google's own result is easier "cleanable" in these examples.
In all other cases, SE's merging is much better. No more random shuffling of words (that could easily slip through).

If I would imagine my usecase, I would have the option "SE handles text merge" checked by default, but only in these problematic cases, it would be useful to be able to disable the checkbox, run OCR again, and then re-enable the checkbox.
