### ISSUE TITLE
Whisper - error on attempting to download model

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#6452]
3.6.10. In the regular, non-cpp version of Whisper, when I attempt to download a model, this happens:

![se whisper error](https://user-images.githubusercontent.com/19672444/203530090-fd1dedd6-1091-4db4-9dfe-fd21c5ce1bff.png)

**Comment by niksedk** [comment]
Thx :)
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip ?

**Comment by darnn** [comment]
Windows 10. I can give you the specific details from winver if you want.
Before trying the new beta, it looks like the ones that produce the error are the English-only ones, and the rest at least start to download normally.
With the new beta, as soon as the "download whisper.cpp" dialogue pops up and I click that I do, I get this error:
![sewhispererror2](https://user-images.githubusercontent.com/19672444/203852564-4de66e3a-5ad7-4cc1-b7cf-3b2afc95d6b5.png)
