### ISSUE TITLE
Whisper Audio To Text Not Working

### ISSUE THREAD

**Issue by omodia** [SubtitleEdit/subtitleedit#6453]
**Audio to text not working when,**
- Japanese language is selected and translate to English option is checked.
- Error message - No text found.

**Comment by The-Johnson** [comment]
It's the same for me: 

I have a fresh install of SE-3.6.10 on a fresh install of Windows 11 in Parallels on a M1 Pro MacBook.

SE runs fine, Vosk/Kaldi works fine. (Well I mean, it generates a file, which is 90% wrong, but still at least works)

Before trying whisper on this fresh install I did:
install python 3.10.8 and add to Path
install ffmpeg and add to Path
pip install ffmpeg-python
pip install whisper
pip3 install torch torchvision torchaudio
installed VLC

SE still asked me to download ffmpeg and whisper despite them already being installed, so I don't think it mattered that I did install them before.

I open a new SE instance and without loading in a video initiate whisper, I add an audio file and press generate, using the base model. After a few seconds, the program tells me a file has been generated in the source folder and it is an empty .srt

I tried going into the settings file and changing useWhisperCpp to false, but nothing changed, I don't even think that setting had any effect as I still see the CPP in the top right corner of the audio-to-text window. 

If I load the video in before initiating whisper I also get the No text found! error.

**Comment by coastal45** [comment]
If setting "Choose language" to English (actual audio doesn't matter) and it returns something, but Japanese gives you "No text found!" dialog...

Check the error log for something like:
`UnicodeEncodeError: 'charmap' codec can't encode characters in position 26-37: character maps to <undefined>`

I have this problem, even back to SE 3.6.8 on Windows 10. I'm not a programmer, but it appears to be an issue with some Python version not recognizing non-ASCII characters. If I recall, in Windows Python could be installed both from GUI and command line.

Works correctly on linux though.

**Comment by The-Johnson** [comment]
So I just tried to test things again, @niksedk thanks for pointing out where to find the error log, I'm pretty new to this fine software. Switching to the php version makes the problem go away and whisper is able to generate the subtitles just fine. The only issue with the php version is the inability to download the large model, as another user has already pointed out. 

First I made sure Whisper works on my Windows instance, I ran the:
pip install git+https://github.com/openai/whisper.git command and after called Whisper in powershell.
Whisper works fine.

Here is my error log when attempting to run Whisper.cpp via SE:
Date: 11/24/2022 08:15:41
Message: Calling whisper-CPP with : C:\Users\johnson\AppData\Roaming\Subtitle Edit\Whisper\main.exe --language "en" --model "C:\Users\johnson\AppData\Roaming\Subtitle Edit\Whisper\Models\base.bin" --output-srt --max-len 77  "C:\Users\johnson\AppData\Local\Temp\e46b0b9b-61d9-48aa-9884-f5a0a30ca2a3.wav"
whisper_model_load: loading model from 'C:\Users\johnson\AppData\Roaming\Subtitle Edit\Whisper\Models\base.bin'

whisper_model_load: type          = 2

whisper_model_load: f16           = 1

whisper_model_load: n_mels        = 80

whisper_model_load: n_text_layer  = 6

whisper_model_load: n_text_head   = 8

whisper_model_load: n_text_state  = 512

whisper_model_load: n_text_ctx    = 448

whisper_model_load: n_audio_layer = 6

whisper_model_load: n_audio_head  = 8

whisper_model_load: n_audio_state = 512

whisper_model_load: n_audio_ctx   = 1500

whisper_model_load: n_vocab       = 51865
whisper_model_load: model size  =   140.54 MB

whisper_model_load: memory size =    22.83 MB

whisper_model_load: ggml ctx size = 140.60 MB

whisper_model_load: adding 1608 extra tokens

whisper_model_load: mem_required  = 506.00 MB
Calling whisper-CPP done in 00:00:04.3672848
Loading result from STDOUT

**Comment by niksedk** [comment]
Is it Japanese audio your are targeting?

````
Message: Calling whisper-CPP with : C:\Users\johnson\AppData\Roaming\Subtitle Edit\Whisper\main.exe --language "en" --model "C:\Users\johnson\AppData\Roaming\Subtitle Edit\Whisper\Models\base.bin" --output-srt --max-len 77 "C:\Users\johnson\AppData\Local\Temp\e46b0b9b-61d9-48aa-9884-f5a0a30ca2a3.wav"

````

`--language "en"` seems to indicate that you have chosen English?
Also, you might try the medium model.

Download of the large model should work okay in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by The-Johnson** [comment]
I'm only working with English audio, I just commented here because it seems the issues are independent of language. 
So far the large model tun natively on my mac seems to give the best results. I just can't get the CPP version to run in SE. PHP runs okay, just slow because it's running on the CPU.

**Comment by niksedk** [comment]
@The-Johnson: New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
The beta has "Auto adjust timings" which might help when there is absolute silence between text.

![image](https://user-images.githubusercontent.com/1261331/204386430-fbd3e9fb-19b0-4b7c-aa52-46af0b0ace84.png)

Any better on your end?

**Comment by coastal45** [comment]
Does "Auto adjust timings" function apply to CPP version only? Windows only?

**Comment by niksedk** [comment]
"Auto adjust timings" should work for all whisper - but it requires silence between speech.

**Comment by coastal45** [comment]
I tried auto adjust timing on Linux (Ubuntu 20.04), but after a few minutes this error happened. At that time, whisper operation had stopped, but timer kept running. Nothing in the error log.

![Screenshot from 2022-11-29 16-07-57](https://user-images.githubusercontent.com/102390147/204676426-71df6ce2-81fc-4183-a143-cf21ec8a98a1.png)

**Comment by niksedk** [comment]
@coastal45: thx for the crash report - hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip ?

**Comment by coastal45** [comment]
Thanks. It's fixed now.
