### ISSUE TITLE
The specified executable is not a valid application for this platform

### ISSUE THREAD

**Issue by xtofnz** [SubtitleEdit/subtitleedit#6454]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/63341559/203643953-76ecba1f-f520-4524-8814-ed741a422cc7.png">

roughly:

**Comment by xtofnz** [comment]
Windows 11, 
Trying to run Whisper on a German video 
(Vosk works)

**Comment by niksedk** [comment]
32-bit ?

**Comment by xtofnz** [comment]
I'm 64. Got to check the version. Good point.

**Comment by niksedk** [comment]
Could you add a screenshot of your "System Information" from Windows:
![image](https://user-images.githubusercontent.com/1261331/204019609-493e7066-a686-4da1-b4b8-112adeada1df.png)

Perhaps also a screenshot from your cpu:
https://www.cpuid.com/softwares/cpu-z.html

**Comment by niksedk** [comment]
Also, what happens if you run "main.exe" from your "Whisper" folder
(press ctrl+shift+alt+D in SE to open the SE data folder)

**Comment by xtofnz** [comment]
= = = = = = = =
Christof Schneider
www.linkedin.com/in/christof-schneider-Ranui [http://www.tailor-made-communications.com/]
www.tailor-made-communications.com [http://www.tailor-made-communications.com/]
On 26/11/2022 04:52:24, Nikolaj Olsson ***@***.***> wrote:
Also, what happens if you run "main.exe" from your "Whisper" folder
(press ctrl+shift+alt+D in SE to open the SE data folder)

**Comment by niksedk** [comment]
Sorry, I did not understand your last message... sometimes email answers do not port well to github...

**Comment by xtofnz** [comment]
Ok, so what happened was that Acronis Cyber Protect quarantined Whisper's main.exe. It also did the same to my g7zip. 

It works now that I asked to re-save the exe at the original place. 
Interesting. 

Thank you so much for your help!
Christof



= = = = = = = =
Christof Schneider
www.linkedin.com/in/christof-schneider-Ranui [http://www.tailor-made-communications.com/]
www.tailor-made-communications.com [http://www.tailor-made-communications.com/]
On 1/12/2022 22:43:13, Nikolaj Olsson ***@***.***> wrote:
Sorry, I did not understand your last message... sometimes email answers do not port well to github...
