### ISSUE TITLE
How to merge two subtitles timely correct?

### ISSUE THREAD

**Issue by mpek** [SubtitleEdit/subtitleedit#6457]
I wanted to complement a short subtitle (scripture on objects in video) with another full text subtitle. Both subtitles already got correct time codes.

I expected SE would:
Merge both subtitles and arrange correct place in time to become one subtitle file with correct timecodes. 

What I did: 
I tried "Join subtitles..." and "Append subtitles..." from Tools menu, but both do not merge the subtitles timely correct. 

When joining, the second subtitle file will be placed on top of first subtitle inside SE. 
The second subtitle text gets the first line numbers, 
and when appending, the second subtitle will be place below the first subtitle inside SE.

I made a [screenshot](https://i.imgur.com/0vvAyb3.png) in which you can see what happened with arrangement and timecode. You can compare timecode and line numbers. SE would need a sorting mechanism to re-arrange line numbers by timecode. 
I'd do a screenshot of the Append subtitle result, if you need it. 

Did I miss something?

**Comment by darnn** [comment]
Yes, the tools->sort by menu.

**Comment by niksedk** [comment]
Normally when joining two subtitles, they are not mixed. At least I've not seen that... is that common for you?
I've just mostly seen the good old part1 and part2 (or even cd1 + cd2, or similar) where the subtitle have been split into multiple parts.

**Comment by mpek** [comment]
Yes, if you want to mix forced subtitles with normal subtitles that are missing the forced elements, it would be very handy to quickly add them to their right position in time.

**Comment by THGhost** [comment]
> Yes, if you want to mix forced subtitles with normal subtitles that are missing the forced elements, it would be very handy to quickly add them to their right position in time.

I second this.

**Comment by peace2000** [comment]
I had this same issue as well. When joining these subtitles (CD1 and CD2), CD2 will be placed first. This happens despite I'd drag and drop CD1 first.

Also, the other part is not added. Only the other part.

**Comment by boelle** [comment]
i know this is a year later... what i did (which seems to work) is to open the first one... then select the last line and select insert after line and then select the next file

**Comment by boelle** [comment]
to make it a bit worse, the documentation https://subtitleedit.github.io/subtitleedit/features/join-subtitles.html

but you cant reorder them. you can only add or delete

hence i tried my add routine...

**Comment by niksedk** [comment]
This works in Subtitle Edit 5: in Tools → Join subtitles, choosing **Keep time codes** merges all files and sorts the lines by start time, so a forced-subtitle track can be combined with a full track directly. **Append time codes** keeps the list order (part 1 + part 2), and the files can be reordered in the list.

**Comment by boelle** [comment]
<img width="922" height="768" alt="Image" src="https://github.com/user-attachments/assets/aaef902b-def1-4812-b9ba-52288e71e11b" />

i added them in the order 1 2 3, but it shows as 3 1 2, why is that?

you say i can change the order? but how, its not logical like grap and drag

and in my case each part starts from 0

**Comment by niksedk** [comment]
Could you attach the subtitles files here (e.g. a zip file)?

When having "Keep time codes" SE will try to auto-sort the subtitles.

**Comment by boelle** [comment]
[mirrors.zip](https://github.com/user-attachments/files/32244109/mirrors.zip)
