### ISSUE TITLE
Weird issue with Whisper Audio to Text

### ISSUE THREAD

**Issue by shanedk** [SubtitleEdit/subtitleedit#6458]
So this is my weird experience with Whisper Audio to Text:
![anydesk00000](https://user-images.githubusercontent.com/5156668/203864959-4744ad04-4959-4578-a1f9-aa459c76a381.png)

I knew it'd take awhile since it's an hour-long video, so I left it running. This is what I saw when I came back. I don't know if Whisper has crashed or is still running (I'll leave it running awhile longer to see), but at the very least, the negative time remaining is something I don't think should logically happen.

**Comment by shanedk** [comment]
So, quick update: Whisper was indeed running, because the progress bar moved forward, but then Windows crashed and rebooted.

By the way, Whisper runs fine from the command line.

**Comment by niksedk** [comment]
SE just runs whisper via command line... see more in the `error_log.txt` or press F2 in the whisper Window while running.

I've not been able to re-produce the negative seconds...

**Comment by shanedk** [comment]
There was nothing written to the error log at that time.

**Comment by niksedk** [comment]
New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

Progress should no longer go to negative seconds + a fix for wrong model file name extension

Better?
