### ISSUE TITLE
Question. Common errors

### ISSUE THREAD

**Issue by mariusberget92** [SubtitleEdit/subtitleedit#6461]
Hi. I have a few subtitles where there are some common errors I can't seem to fix automatically with the common errors option.
Example would be that alot of words contains a lowercase "l" instead of the letter "i". 

Example words:
`walt` should be `wait`
`rlslng` should be `rising`
`thls` should be `this`

Is there any way to configure my own rules anywhere?

**Comment by niksedk** [comment]
Works fine here:
![image](https://user-images.githubusercontent.com/1261331/204026963-d0a03a09-eac4-4928-92a8-aeede32fec06.png)

Perhaps you need a clean install?

**Comment by mariusberget92** [comment]
![image](https://user-images.githubusercontent.com/4356128/204027648-fa9d728d-03b9-4115-9e53-05546d1edf86.png)
I just downloaded a new portable version. It works sometimes and sometimes it doesn't.
