### ISSUE TITLE
[BUG]Break long lines don't support Chinese/Japanese

### ISSUE THREAD

**Issue by i990049** [SubtitleEdit/subtitleedit#6465]
First the setting in SE version 3.6.10.
<img width="588" alt="QQ图片20221126121628" src="https://user-images.githubusercontent.com/103364093/204074008-d927e8d7-e94c-4dfa-a590-4d6bb6eeb775.png">
The orange lines show that SE didn't break long lines more than 19, so does the batch mode. Here are test files.
[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/10095732/test.zip)

<img width="960" alt="屏幕截图(176)" src="https://user-images.githubusercontent.com/103364093/204074110-095f0f48-8359-43dd-971c-dabb43aa95a6.png">
<img width="960" alt="屏幕截图(177)" src="https://user-images.githubusercontent.com/103364093/204074114-3ee51a8d-7441-4875-ae9b-947ce8d0c52c.png">

**Comment by niksedk** [comment]
What are the break characters?  `。，？一` ?

**Comment by i990049** [comment]
> What are the break characters? `。，？一` ?

That's Chinese punctuation, similar to English punctuation. You can let SE deal with them as Chinese character.
。，、＇：∶；?‘’“”〝〞ˆˇ﹕︰﹔﹖﹑·¨….¸;！´？！～—ˉ｜‖＂〃｀@﹫¡¿﹏﹋﹌︴々﹟#﹩$﹠&﹪%*﹡﹢﹦﹤‐￣¯―﹨ˆ˜﹍﹎+=<­­＿_-\ˇ~﹉﹊（）〈〉‹›﹛﹜『』〖〗［］《》〔〕{}「」【】︵︷︿︹︽_﹁﹃︻︶︸﹀︺︾ˉ﹂﹄︼

**Comment by i990049** [comment]
> What are the break characters? `。，？一` ?

That's Chinese punctuation, similar to English punctuation. You can let SE deal with them as Chinese character.
。，、＇：∶；?‘’“”〝〞ˆˇ﹕︰﹔﹖﹑·¨….¸;！´？！～—ˉ｜‖＂〃｀@﹫¡¿﹏﹋﹌︴々﹟#﹩$﹠&﹪%*﹡﹢﹦﹤‐￣¯―﹨ˆ˜﹍﹎+=<­­＿_-\ˇ~﹉﹊（）〈〉‹›﹛﹜『』〖〗［］《》〔〕{}「」【】︵︷︿︹︽_﹁﹃︻︶︸﹀︺︾ˉ﹂﹄︼

**Comment by niksedk** [comment]
OK, should `塔诺·卡里迪先生，在这里，乎意料地提高了他的价格。` split to
´´´´
塔诺·卡里迪先生，在这里，
乎意料地提高了他的价格。
´´´´
?

**Comment by i990049** [comment]
> OK, should `塔诺·卡里迪先生，在这里，乎意料地提高了他的价格。` split to
> 
> ```
> 塔诺·卡里迪先生，在这里，
> ´乎意料地提高了他的价格。
> ```
> 
> ?
Yes, break Chinese/Japanese long lines according to punctuation not by average characters. If the general settings and batch convert can add a total line max length like this picture, it will be helpful to me, so I don't need to change 90 to 19 one by one subtitle everytime. Thank you.
<img width="960" alt="屏幕截图(188)" src="https://user-images.githubusercontent.com/103364093/205427153-6f120483-a76d-4f9f-b036-626539d5d78e.png">

**Comment by LeonCheung** [comment]
@i990049 Hi, maybe a bit off-topic, but have you tried using different profiles for that?
![image](https://user-images.githubusercontent.com/494788/205427300-0bac1c56-9e11-426a-9103-4a666c56a562.png)

You can quickly switch among profiles by clicking here:

![image](https://user-images.githubusercontent.com/494788/205427338-0edde5ed-db77-4ff4-bb7b-6c35956e089d.png)

Hope it helps a bit.

**Comment by i990049** [comment]
> @i990049 Hi, maybe a bit off-topic, but have you tried using different profiles for that? ![image](https://user-images.githubusercontent.com/494788/205427300-0bac1c56-9e11-426a-9103-4a666c56a562.png)
> 
> You can quickly switch among profiles by clicking here:
> 
> ![image](https://user-images.githubusercontent.com/494788/205427338-0edde5ed-db77-4ff4-bb7b-6c35956e089d.png)
> 
> Hope it helps a bit.

You are talking about setting a single line maximum length, the feature I asked for is to add setting for the total line maximum length. There is no such setting in general and batch mod, only in break long lines one by one. That's a repetitive and boring job.
你说的是设置一条字幕的长度，我要求添加的功能是设置整条字幕的长度，常规设置和批量模式里面没有这个设置，一条条拆分长字幕那里才有，这样重复拆分长字幕很无聊。

<img width="960" alt="屏幕截图(189)" src="https://user-images.githubusercontent.com/103364093/205428178-e9922979-f1d9-4eab-9443-d2c2d3b33473.png">

**Comment by LeonCheung** [comment]
I know. That's why I said it's **off-topic**. Good luck then. BTW, it seems you are trying to use that feature for a bilingual subtitle. Is that really make any sense? O_O Just curious.

**Comment by i990049** [comment]
> I know. That's why I said it's **off-topic**. Good luck then. BTW, it seems you are trying to use that feature on a bilingual subtitle. Is that really making any sense? O_O Just curious.

This is the subtitle made by the subtitle group, and what I said earlier is used for Chinese/Japanese subtitles , batch break English subtitle to the right setting, then translate into Chinese/Japanese, check whether every single line maximum length is exceeded, if ok then merge two language into a bilingual subtitle, if exceeded then batch break long lines again, so that's why I asked  for the genaral and batch mode setting for the total line maximum length.

**Comment by LeonCheung** [comment]
Okay. First, I agree that it would be nice that SE could store the _Line .max length_ value in **Settings.xml** so that you needn't reediting it each time. 

Second, I agree with the idea that it would be helpful to break after some punctuations. But I don't think all characters you listed should be used for all cases. Instead, there should be a text field for users to customize split-at-end chars, just like the one used for importing plain texts.

**Comment by i990049** [comment]
> Okay. First, I agree that it would be nice that SE could store the _Line .max length_ value in **Settings.xml** so that you needn't reediting it each time.
> 
> Second, I agree with the idea that it would be helpful to break after some punctuations. But I don't think all characters you listed would apply to everyone. Instead, there should be a text field for users to customize split-at-end chars, just like the one used for importing plain texts.

I said break Chinese/Japanese long lines according to punctuation not by average characters, you didin't see what I said.

**Comment by LeonCheung** [comment]
Oh, trust me I did see what you said carefully, every single word.

1. You mentioned the pain of having to change the value from 90 to 19 each time, right? And I said I agree with that. Correct?
2. You listed a bunch of characters/punctuations, which you are expected to be used as split-at-end chars, right? And I said I agree with that and also share my opinion on it. Correct?
3. You mentioned split by average character, on which I haven't had any comments yet. Correct? Tell me wrong if missed anything else. Thanks.

**Comment by i990049** [comment]
> Oh, trust me I did see what you said carefully, every single word.
> 
> 1. You mentioned the pain of having to change the value from 90 to 19 each time, right? And I said I agree with that. Correct?
> 2. You listed a bunch of characters/punctuations, which are expected to be used as split-at-end chars, right? And I said I agree with that and also shared my opinion on it. Correct?
> 3. You mentioned NOT breaking by average character, on which I haven't had any comments yet. Correct?
> 
> Tell me if missed anything else. Thanks.

So what‘s your suggestion apply to everyone making a bilingual subtitle except by punctuations or average character？Tell me if you know.

**Comment by niksedk** [comment]
OK, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip ?
Can hopefully auto break lines with Chinese comma/period a little better.

**Comment by LeonCheung** [comment]
@i990049 I can't help you more without knowing exactly what kind of workflow you guys are taking, I mean on a very detailed level. Nevertheless, that should be another topic.

**Comment by i990049** [comment]
> OK, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip ? Can hopefully auto break lines with Chinese comma/period a little better.

It didn't work，neither Chinese nor Japanese. Maybe you should add a customized setting in the general like the fourth picture above then add batchmode.

<img width="960" alt="屏幕截图(190)" src="https://user-images.githubusercontent.com/103364093/205434842-50ea7ad2-d5ea-4a0f-9ff7-0a830bc22e5d.png">
<img width="960" alt="屏幕截图(191)" src="https://user-images.githubusercontent.com/103364093/205434848-2f629395-c795-4c74-a184-a3cbecf54847.png">

**Comment by niksedk** [comment]
OK, tried again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
Better?

**Comment by i990049** [comment]
> OK, tried again: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip Better?

Break Chinese much better except two lines, But break Japanese the test file above, it didn't work. I tried another Korean subtitle, it works. Why Japanese can't? How about the same setting in general and the batch convert?
<img width="960" alt="屏幕截图(193)" src="https://user-images.githubusercontent.com/103364093/205439409-a8837597-04ef-437e-ae7b-c0813e58aaed.png">
<img width="960" alt="屏幕截图(194)" src="https://user-images.githubusercontent.com/103364093/205439423-3797630d-26f2-44df-bc9f-0e6f5d87bc39.png">

**Comment by niksedk** [comment]
Tried to fix Japanese break here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

I presume this will also work in batch convert / fix common errors...

**Comment by i990049** [comment]
> It didn't work，neither Chinese nor Japanese.



> Tried to fix Japanese break here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
> 
> I presume this will also work in batch convert / fix common errors...



> Tried to fix Japanese break here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
> 
> I presume this will also work in batch convert / fix common errors...

It didn't work again，neither Chinese nor Japanese. And I can't find  what's the difference in batch convert / fix common errors, just no total line max length setting. Maybe you miss something.I suggest add a customized setting in general, and batch convert / fix common errors use general settings.
<img width="960" alt="屏幕截图(188)" src="https://user-images.githubusercontent.com/103364093/205427153-6f120483-a76d-4f9f-b036-626539d5d78e.png">

**Comment by i990049** [comment]
@niksedk
I know why SE can't  break Japanese long line. All the subtitles I tested are UTF8-BOM, include Chinese/Korean/Japanese. The Japanese subtitle you tested is ANSI. That's why you can break Japanese long line but I can't.
![屏幕截图(201)](https://user-images.githubusercontent.com/103364093/206250980-8a8b1aaf-cdb4-44ff-a258-c7f13e153650.png)

Is it possible that SE could set the total line max length value in general settings and batch convert mode？I hope next version can be set. Thanks.

<img width="960" alt="屏幕截图(200)" src="https://user-images.githubusercontent.com/103364093/206250888-12f9379c-110d-421a-880e-8953b02247bb.png">
<img width="960" alt="屏幕截图(204)" src="https://user-images.githubusercontent.com/103364093/206251028-f84ea11c-1aa0-400f-848d-55ac746a2723.png">

**Comment by i990049** [comment]
@niksedk
[TEST.zip](https://github.com/SubtitleEdit/subtitleedit/files/10293516/TEST.zip)
![屏幕截图(219)](https://user-images.githubusercontent.com/103364093/209299315-e807ceb1-2313-4724-b7d0-8805d2d3031d.png)
<img width="960" alt="屏幕截图(220)" src="https://user-images.githubusercontent.com/103364093/209299341-6ea8543e-c1e1-41d0-9d4d-4a25cce0f150.png">
I tried the latest test version with the test subtitles uploaded，some is UTF8-BOM，some is ANSII. SE breaks Korean/Chinese long line is much better，still can't break Japanese long line，and can't batch break long line acording to TOTAL Line max length value 19.

**Comment by n-99** [comment]
The difficulty of breaking long lines in Chinese and Japanese is due to a feature of those languages, the missing spaces. Maybe the should be an option to consider a handful of very common particles as breaking characters? They might occasionally give some wrong breaks, but that might still be preferable.

(Simplified) Chinese examples:
Before and after 还是, 或者
After 的, 们
Before 和, 他, 她, 是

Japanese:
Before a kanji that comes after a kana.
Maybe after です?

**Comment by i990049** [comment]
> The difficulty of breaking long lines in Chinese and Japanese is due to a feature of those languages, the missing spaces. Maybe the should be an option to consider a handful of very common particles as breaking characters? They might occasionally give some wrong breaks, but that might still be preferable.
> 
> (Simplified) Chinese examples: Before and after 还是, 或者 After 的, 们 Before 和, 他, 她, 是
> 
> Japanese: Before a kanji that comes after a kana. Maybe after です?

I don't ask for long sentences based on prepositions, I can split them according to punctuation manually. If some  sentences  produced by whisper more than 19 characters, you can use the method of equal splitting. After all, the author is not Chinese, Japanese or Korean.

**Comment by i990049** [comment]
version3.6.11 still can't break Japanese long lines to 19, so does the batch mode. here is the subtitle.
@niksedk
[[Abystoma] Manga Sekai Mukashibanashi-  001A, 107A (WEB 720p) [70CCF8D9].人声 (Transcribed on 07-Jan-2023 12-13-19).zip](https://github.com/SubtitleEdit/subtitleedit/files/10543752/Abystoma.Manga.Sekai.Mukashibanashi-.001A.107A.WEB.720p.70CCF8D9.Transcribed.on.07-Jan-2023.12-13-19.zip)
<img width="960" alt="无标题" src="https://user-images.githubusercontent.com/103364093/215692209-31da4e9c-328a-4aaa-afd1-b5bd3695586f.png">

**Comment by Whitesttax** [comment]
I'd really just want to break long sentences on comma. Seems to break . really well for Japanese, but for comma it doesn't work at all. Have the option on settings > tool > break early for comma as well just in case it helps but it's not working.

**Comment by TokerX** [comment]
> What are the break characters? `。，？一` ?

一 is the character for "one" (or "a"). so not that one.
