### ISSUE TITLE
Multiple Language Translation feature in one click

### ISSUE THREAD

**Issue by jacobjr5050** [SubtitleEdit/subtitleedit#6467]
Requesting a feature to convert the language to multiple language in one click

**Comment by niksedk** [comment]
Use free translation is just too limited... it's only suited for one or two translations.

**Comment by MbuguaDavid** [comment]
> Using free translation is just too limited... it's only suited for one or two translations.

Probably try and incorporate the Facebook M2M -100 Multilingual AI Model.
 
Official writeup - https://ai.facebook.com/blog/introducing-many-to-many-multilingual-machine-translation/

GitHub project - https://github.com/facebookresearch/fairseq/tree/main/examples/m2m_100

Thanks!
