### ISSUE TITLE
[Feature Request] Change location of waveform folder

### ISSUE THREAD

**Issue by Belleyy** [SubtitleEdit/subtitleedit#6468]
My current waveform folder take a good amount of space (4GB). my `C:` drive is already low on space so I would like to be able to change the location of this folder.

**Comment by niksedk** [comment]
You can use the portable version of SE and place it on any drive - the portable version will stay in the one folder (and sub folders).

You can empty your waveform folder... normally you don't work on more that a few subtitles anyway.
