### ISSUE TITLE
Stand by despite running batch conversion

### ISSUE THREAD

**Issue by mpek** [SubtitleEdit/subtitleedit#6469]
I just came across, that I wanted to run SE to extract subtitles from many videos overnight. 
The next morning computer was off. 
I turned it on and it continued to run the batch conversion. 

Current Windows energy plan "Balanced" is set to turn off Monitor after 10 minutes and go to Stand by after 1 hour of inactivity. 

Do you know why computer turned to stand by while batch conversion was still in progress?

I know that you can set Windows to maximum performance, but I don't want that at all. 
Do you know which setting works in the energy plan "Balanced" so that it doesn't switch to stand-by while SE is working?
Is SE sending the right signal to not go to stand by while working?

**Comment by niksedk** [comment]
thx for the input :)
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip ?

**Comment by mpek** [comment]
Thank you, I'll try it, hopefully today and get back to you.

**Comment by mpek** [comment]
Needs some optimization. 
Computer stays on, but won't go to standby when batch is finished and time is reached to go to standby, as long as SE is open.
