### ISSUE TITLE
Error when translating into deepl

### ISSUE THREAD

**Issue by joseata4** [SubtitleEdit/subtitleedit#6471]
When I try to translate with deepl, I get the error shown in the attached image.

![t1](https://user-images.githubusercontent.com/88949341/204275470-d7ff6c0a-5bed-404d-b563-6a5de7b295cd.png)

**Comment by niksedk** [comment]
Do yo have the latest DeepL plugin? See File - Plugins?

Does this happen with all subtitles or only this one?

**Comment by joseata4** [comment]
> ¿Tienes el último plugin de DeepL? Ver Archivo - ¿Complementos?
> 
> ¿Esto pasa con todos los subtítulos o solo con este?

Yes, I have everything updated, happens with all subtitles.

**Comment by niksedk** [comment]
Works fine here...
