### ISSUE TITLE
 text not found error and not working whisper PHP and it is telling me to locate which I don't have

### ISSUE THREAD

**Issue by hachiro87** [SubtitleEdit/subtitleedit#6472]

**Comment by niksedk** [comment]
Could you try latest beta using whisper.cpp? 
New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
(unpack to something like "C:\Tools\SE")

If it's not better, please attach the `error_log.txt`.
