### ISSUE TITLE
Subtitle contains negative codes, but "0" lines found

### ISSUE THREAD

**Issue by mpek** [SubtitleEdit/subtitleedit#6476]
https://i.imgur.com/b0YF4Rn.png

Weird message: 
Subtitle contains negative time codes. Continue saving?
Lines found: 0

Subtitle is a XML and SE calls it "Timed Text 1.0" with Frame rate 50.

What i did: 
- Adjusted all times
- Deleted one wrong line

SE shows the same message also when format has been changed to SRT.

**Comment by niksedk** [comment]
He, might be a little confusing... it's actually the first subtitle that seems to be negative.
