### ISSUE TITLE
Import Sub Station Alpha styles: an application error occurred (Windows Forms Thread Exception)

### ISSUE THREAD

**Issue by mariecora** [SubtitleEdit/subtitleedit#6477]
Windows Forms Thread Exception
An application error occurred in Subtitle Edit 3.6.10.0. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
La référence d'objet n'est pas définie à une instance d'un objet.

Stack Trace:
   à Nikse.SubtitleEdit.Forms.Styles.SubStationAlphaStyles.SetControlsFromStyle(SsaStyle style)

   à Nikse.SubtitleEdit.Forms.Styles.SubStationAlphaStyles.listViewStyles_SelectedIndexChanged(Object sender, EventArgs e)

   à System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)

   à System.Windows.Forms.ListView.WmReflectNotify(Message& m)

   à System.Windows.Forms.ListView.WndProc(Message& m)

   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by niksedk** [comment]
Hi @mariecora,

Could you attach the subtitle? (as a .zip file)

**Comment by SMSourov** [comment]
@niksedk I'm also facing the same problem. Everytime when I try to do that, error occurs.

**Comment by niksedk** [comment]
Could you please attach a subtitle that crashes  on assa style import (you can attach it as .zip here or email it to me)

**Comment by niksedk** [comment]
@mariecora and @SMSourov  - can either of you re-create this still? if yes, please attach the crashing subtitle, thx.

**Comment by SMSourov** [comment]
> @mariecora and @SMSourov - can either of you re-create this still? if yes, please attach the crashing subtitle, thx.

After seeing this, I tried. Couldn't reproduce the bug. May be you have fixed this. I had this problem in version 3.6.5. I usually don't update SubtitleEdit.

**Comment by niksedk** [comment]
@mariecora: Let me know if this happens again - and if it does, please upload the crashing import subtitle file, thx :)
