### ISSUE TITLE
Improve the feature of locating ffmpeg

### ISSUE THREAD

**Issue by SMSourov** [SubtitleEdit/subtitleedit#6480]
In the waveform setting, we have to give the location of FFmpeg. We have to provide the full location of FFmpeg. I use the portable version of SubtitleEdit.

Problem:
When I move the subtitle edit folder, I have to change that setting every time manually.

Expected behaviour:
In the waveform settings, in the FFmpeg location field, if I write "ffmpeg.exe", it should use the "ffmpeg.exe" of that directory/folder where Subtitle.exe is located.

Current behavior:
It prompts to download and use FFmpeg.

**Comment by niksedk** [comment]
It should work now if you use "ffmpeg\ffmpeg.exe": https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by SMSourov** [comment]
Thanks!
This also fixes the problem when the app is run via WINE (v7.0.1) in Ubuntu 22.04.
