### ISSUE TITLE
can't use whisper cpp on Windows

### ISSUE THREAD

**Issue by coastal45** [SubtitleEdit/subtitleedit#6483]
When I use cpp on Windows SE, I get "No text found!" error dialog almost immediately.
In the error log, the error:
`whisper: error: argument --model: invalid choice: 'C:\\software bu\\SubtitleEditBeta\\Whisper\\Models\\small.bin' (choose from 'tiny.en', 'tiny', 'base.en', 'base', 'small.en', 'small', 'medium.en', 'medium', 'large')`

It is the same on 3.6.10 and also beta 31. Windows 10 up to date. Error log is attached.

[error_log 120122.txt](https://github.com/SubtitleEdit/subtitleedit/files/10136377/error_log.120122.txt)

**Comment by niksedk** [comment]
Please try a newer beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by BeanJean** [comment]
@niksedk 

I also meet exactly this problem. I have been tried solve the bug following below youtube tutorial. Do exactly the instruction step but it does not work. I saw that other person also got result like me.

https://www.youtube.com/watch?v=Al894WeQmgU

#### Process
![process](https://user-images.githubusercontent.com/119668124/205279785-c549a971-dbcb-4969-ae66-c143d58018af.png)

#### Finish
![finish](https://user-images.githubusercontent.com/119668124/205280127-93035837-dbbe-4fe6-8883-3c585712792e.png)


#### Environment
![environment](https://user-images.githubusercontent.com/119668124/205277357-51863a46-9f8d-4b98-99a8-dcaef6b577e5.png)

**Comment by niksedk** [comment]
@BeanJean: Could you attach the error_log.txt file?

**Comment by BeanJean** [comment]
@niksedk 

There're some last line in error log file. Please check attach file for detail. Thank you!
```
error: failed to initialize whisper context

whisper_init: failed to load model from 'C:\Users\admin\AppData\Roaming\Subtitle Edit\Whisper\Models\large.bin'

whisper_model_load: ERROR not all tensors loaded from model file - expected 1259, got 896

Calling whisper-CPP done in 00:00:19.8642252
Loading result from STDOUT
```
[error_log.txt](https://github.com/SubtitleEdit/subtitleedit/files/10141180/error_log.txt)

**Comment by niksedk** [comment]
OK, the large model is probably not complete... try to re-download it.

**Comment by coastal45** [comment]
> Please try a newer beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

Now beta 49. Error is gone, but same result. Error log attached.

[error_log 120222.txt](https://github.com/SubtitleEdit/subtitleedit/files/10143961/error_log.120222.txt)

**Comment by niksedk** [comment]
I don't suppose latest beta is any better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

Also, is it better if you choose the `medium` model?

If no to both the above, could attach the audio file?

**Comment by coastal45** [comment]
> I don't suppose latest beta is any better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
> 
> Also, is it better if you choose the `medium` model?
> 
> If no to both the above, could you attach the audio file?

This one, beta 114, works correctly now. Though I'm using non-AVX2 cpu so it's still slow for me.

**Comment by niksedk** [comment]
@coastal45: thx for testing. It's slow for me with AVX2 with medium or large models :)
