### ISSUE TITLE
An application error occurred in Subtitle Edit 3.6.10.0

### ISSUE THREAD

**Issue by Gramint** [SubtitleEdit/subtitleedit#6486]
I have a problem with 3.6.10.0 but also with the old version now

Error Message: La reference d'objet nest pas definie a une instance d'un objet. 
Stack Trace: 
à Nikse.SubtitleEditlogic.VideoPlayers.QuartsPlayer.Pause0 
à Nikse.SubtitleEdit.Controls.VideoPlayerContainer.Pause0 
à Nikse.SubtitleEdit.Controls.VideoPlayerContainer.PauseAndDi sposePlayer(l 
à Nikse.SubtitleEdit.Forms.Main.FormMain_FormClosing(Object sender, FormClosingEventArgs e) 
à System.Windows.Forms.Form.OnFormClosing(FormClosingEve ntArgs e) 
à System.Windows.Forms.Form.WmClose(Message& m) 
à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam) 

Thank you for your help

**Comment by niksedk** [comment]
Try installing mpv video player - go to Options - Settings - Videoplayer - download mpv lib

Alternatively you can try to install lav filters: https://github.com/Nevcairiel/LAVFilters/releases/download/0.77.1/LAVFilters-0.77.1-Installer.exe

**Comment by Gramint** [comment]
Thank you.
I install lav filters.
It seems to wotk now.
