### ISSUE TITLE
Pop-up message missing translation

### ISSUE THREAD

**Issue by hugok79** [SubtitleEdit/subtitleedit#6492]
Taking the workflow below for example:

**Note: This happened when using the latest beta version.** I don't know if this happens in the latest stable version(3.6.10)

Open Subtitle Edit
Select Portuguese (Portugal) language
Open a subtitle

I get this pop-up message in **English:**

![Screenshot](https://user-images.githubusercontent.com/16929048/206176982-d77371f5-da90-4ea4-9e8c-86bb0308dd70.png)

**Comment by niksedk** [comment]
Better now?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by hugok79** [comment]
Much better now!
Only the **Close** button is untranslated... but that's no big deal either ;)
**Note**: This message appeared because on this laptop I didn't have **VLC** or **MPC-HC** installed...
 However I have **SMPlayer** which uses mplayer and mpv, strange...
@niksedk Thanks anyway :)

![Captura de ecrã 2022-12-07 214720](https://user-images.githubusercontent.com/16929048/206305061-f9e2465d-f41c-436d-a1fa-2b4fd06b0e01.png)
