### ISSUE TITLE
insert text to multiple lines

### ISSUE THREAD

**Issue by librafrog** [SubtitleEdit/subtitleedit#6493]
Is it possible to enter one text to multiple subtitle lines, let's say L18-21 will say MULTI LINE.
I'm trying to save time by using _guess times_ and just put timestamps. When I select them can't enter text in all of them together. :smile:
![image](https://user-images.githubusercontent.com/79138819/206189586-772f5945-c553-4311-8553-7911bdc75a66.png)

**Comment by OmrSi** [comment]
You could use: `Edit -> Insert Unicode symbol` then replace that symbol with your text as a workaround.

**Comment by librafrog** [comment]
Copy that 🐰
