### ISSUE TITLE
Burn-in video failed with Audio encoding = copy

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6500]
Not always, but sometimes it would fail here, not sure why. But after switching to aac, it could be burned somehow. FYI
Say, the original audio info is like this:
![image](https://user-images.githubusercontent.com/494788/206394898-04b51a6f-55c6-4515-831f-b59850c5defa.png)

**Comment by niksedk** [comment]
If you find a sample file you can upload and a way to re-create this, please do let me know.
