### ISSUE TITLE
SE doesn't find ALL of 'Remove text before a Colon'

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#6501]
Hi!

On Line 41 there's a 'Remove text before a Colon' that nor 3.6.7 or latest 3.6.10 catch!
(Just happen to have both those versions available)

Check it out with the Attached Sub!

[Line41--Hudson and Rex - 03x05 - Prescription-Rex!.SYNCOPY.English.C.edit.Addic7ed.com - Copy.zip](https://github.com/SubtitleEdit/subtitleedit/files/10183549/Line41--Hudson.and.Rex.-.03x05.-.Prescription-Rex.SYNCOPY.English.C.edit.Addic7ed.com.-.Copy.zip)

"- RACHEL: Briane."

It's always been like this on lines like that one, but I've just not got to write about it, YET!   ;-) 

Usually I also do a Search for : that will find that problem.

===========

Found another problem Sub also.

It wants to Remove the "Rossi: " from Line 301 "- Rossi: Or they had help." but without keeping the Dash first.
Can probably be avoided by running 'Fix Common Errors > Fix Subtitles with more than Two Lines' first, but if one not do that...

[Criminal.Minds.S16E04.Pay-Per-View.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb_track4_[eng].zip](https://github.com/SubtitleEdit/subtitleedit/files/10183882/Criminal.Minds.S16E04.Pay-Per-View.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb_track4_.eng.zip)

(And, BTW, there should be a possibility to Save ones Settings for 'Fix Common Errors', as there now is for 'Multiple Replace', wich, BTW, imports old saved Settings as Default_1 IF the Standard 'Default' already exists.
It could ask if it should Overwrite the Default instead of creating a new group.)

**Comment by niksedk** [comment]
Sorry, the input lines are just badly formatted.
