### ISSUE TITLE
Audio track selection for waveform+spectrogram is inconsistent

### ISSUE THREAD

**Issue by AlfonZ42** [SubtitleEdit/subtitleedit#6506]
Hello.

I have a mkv file with multiple audio tracks (a sample is attached). When I generate the waveform+spectrogram from a track, the output sometimes doesn't match the audio (inside SE using mpv, or outside SE).
It seems the track selection is random.

Some somewhat reproducible scenarios (start with empty cached waveforms+spectrograms):

A) select track 1, generate waveform+spectrogram, the displayed w+s is from track 2; select track 2, generate w+s, the displayed w+s from track 1

B) select track 2, generate waveform+spectrogram, select track 1, the displayed waveform is the one just generated and without spectrogram

C) select track 1, generate waveform+spectrogram, note the displayed w+s, empty cached w+s via settings, select track 2 (so the w+s display refreshes), repeat the loop; the output w+s is sometimes correct, sometimes incorrect, even during the same SE session

Part of the issue happens only when using the internal wave extraction. If I enable _FFmpeg wave extraction_ in settings, the output waveform+spectrogram is correct for the track selected in the dialog, but inter-track mixing can still occur (see scenario B).

Version: 3.6.10.73, Windows 10 x64.

Thanks.

[MultitrackWSSelectionSample.zip](https://github.com/SubtitleEdit/subtitleedit/files/10195994/MultitrackWSSelectionSample.zip)

**Comment by AlfonZ42** [comment]
I looked at the source code and the generating part of the issue (scenarions A,C) is due to VLC - https://code.videolan.org/videolan/vlc/-/issues/21592

The selection part of the issue (scenario B) might be due to _WavePeakGenerator.GetPeakWaveFileName_ (and _WavePeakGenerator.SpectrogramDrawer.GetSpectrogramFolder_) able to accept the audio track index but not been supplied one by all appropriate callers; or mpv using zero-based track indexing, so selecting first track then gets treated as no track index supplied (which results in searching for all generated waveforms).

**Comment by niksedk** [comment]
SE uses either FFmpeg or VLC... FFmpeg is preferred as it handles more formats + is faster.

Latest beta might be a little better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

Due to a change is this line: https://github.com/SubtitleEdit/subtitleedit/commit/f6af948b529e21f6a638c3f8d0dfc1e80bac1d34#diff-79d9c557c5825142386c2b89dc392aeb47970348d3cd52fd578637620f8ed662R347

**Comment by AlfonZ42** [comment]
Is there a missing _hash_ reference in filename creation in the following?
```diff
@@ -371,7 +344,7 @@ public static string GetPeakWaveFileName(string videoFileName, int trackNumber =
             var hash = MovieHasher.GenerateHash(videoFileName);
 
             string wavePeakName;
-            if (trackNumber > 0)
+            if (trackNumber > 0 || Directory.GetFiles(dir, "-*.wav").Length == 0)
             {
                 wavePeakName = $"{hash}-{trackNumber}.wav";
             }
```

Otherwise it looks fixed with build 203.
