### ISSUE TITLE
[Feature Request] AAS style replace

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#6509]
![image](https://user-images.githubusercontent.com/54498172/206831869-add3ce14-4a19-4483-8a5e-a3569c5f381a.png)

I have 3 styles in the file. And I want to use style3 to replace style2. But I can't do it quickly for now.
It would be great if I can replace any style in the file using any style in the storage with just 3 clicks. Or just copy and paste to replace it.

**Comment by LeonCheung** [comment]
Maybe you can try deleting **style2**, then rename **style3** with **style2**?

**Comment by Mishasama** [comment]
> Maybe you can try deleting **style2**, then rename **style3** with **style2**?

Thank you for the solution.
But what if I want to replace style1 to s3 and style2 to s4 at the same time?
I think a more intuitive and efficient operation mode is still needed.

**Comment by LeonCheung** [comment]
Something like this? 

![copy-settings-from](https://user-images.githubusercontent.com/494788/207642978-03c6d3ed-d533-4284-873a-02e2a08ed681.png)

In that case, it indeed can save many clicks in case you want to work on existing styles.

**Comment by Mishasama** [comment]
> Something like this?


Yes! It would be great if it could copy from both the current file and storage.
But I think the best commands in the context menu are "copy style" & "paste style". Then you can select what you want quickly.

**Comment by niksedk** [comment]
I do think the "style replace" is a good idea... added in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/210151675-3a8d5b33-1c35-4cbe-8a22-a99ac35bfceb.png)

![image](https://user-images.githubusercontent.com/1261331/210151683-fb593225-c8a7-4184-b05a-abc35ea0c9d9.png)
