### ISSUE TITLE
Set start time causes desync in translation mode

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6511]
![GIF 2022-12-10 下午 06-51-05](https://user-images.githubusercontent.com/494788/206851553-2bc4b7c9-ade0-4f74-a2b0-5ea4d03c5a84.gif)

And sometimes it even causes failure on Undo.
Same occurs for **set start for appropriate line**.

**Comment by LeonCheung** [comment]
@niksedk Could you look at this because I believe it is a bug:

[test files.zip](https://github.com/SubtitleEdit/subtitleedit/files/10328381/test.files.zip)

https://user-images.githubusercontent.com/494788/210162448-1539892c-34c3-42c6-ad30-547cb1fb26c7.mp4

**Comment by niksedk** [comment]
Yes, seems like a bug - is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Yes, thx! Another thing is that they don't match either if you try to copy/paste line(s). Should I open a new report?

**Comment by darnn** [comment]
I already have:
https://github.com/SubtitleEdit/subtitleedit/issues/5597
