### ISSUE TITLE
webvtt with ``X-TIMESTAMP-MAP`` header time as rounding error when converting it to sup/pgs

### ISSUE THREAD

**Issue by moi15moi** [SubtitleEdit/subtitleedit#6512]
### How to reproduce the bug
1. Open the vtt. We can see that the start time is **00:00:40,929**
2. Export it in .sup file.
3. Open the .sup file and see that the start time is **00:00:40,928**

### Sample
[sample.zip](https://github.com/SubtitleEdit/subtitleedit/files/10200735/sample.zip)

### SUP/PGS
Here is how the .sup time is generated: 
https://github.com/SubtitleEdit/subtitleedit/blob/98bea67a49bd2aa825258e28c925816a7c310a52/src/libse/BluRaySup/ToolBox.cs#L80-L89

#### A brief comment on the way it convert pts to ms
I am not sure if **PtsToTimeString** should floor, ceil or round ``pts / 90``.

To be sure which kind of operation we need here is what I propose.

1. Create a line in a .sup with those characteristics:
- Start_time IN pts is: 7471
- End_time IN pts is: 22589
2. Mux the .sup to an video that is 24000/1001 fps. You must be sure that the first frame start at ``00:00:00,000`` (you can verify it in mpv)

Then, we open the mkv in mpv and do those 2 tests:
**TEST 1**
If the subtitle appear at the frame 2 (00:00:00,083), there are 2 conclusion possible:
1. It floor(pts / 90) or int division, but it is the same thing since pts it always positive.
2. It round(pts / 90)

If the subtitle appear at the frame 3 (00:00:00,167), there is only one conclusion possible:
1. It ceil(pts / 90)

**TEST 2**
If the subtitle end at the frame 5 (00:00:00,209), there is only one conclusion possible:
1. It floor(pts / 90) or int division, but it is the same thing since pts it always positive.

If the subtitle end at the frame 6 (00:00:00,250), there are 2 conclusion possible:
1. It round(pts / 90)
2. It ceil(pts / 90)

With those 2 tests, we will be 100% sure if he need to floor, ceil or round.
For example, if the sub appear at the frame 2 and end at the frame 6, it round(pts / 90).

I have tried to do those tests, but I did not find how to edit directly the PTS time in an .sup subtitle.

### VTT
Since there is a ``X-TIMESTAMP-MAP`` header, it first calculate the offset: https://github.com/SubtitleEdit/subtitleedit/blob/1304bccf757009d8b234f60fa7cc7e951ba46447/src/libse/SubtitleFormats/WebVTT.cs#L449

Then, here is how the timing is generated: https://github.com/SubtitleEdit/subtitleedit/blob/1304bccf757009d8b234f60fa7cc7e951ba46447/src/libse/SubtitleFormats/WebVTT.cs#L74

# What may cause this issue
When it convert the time of the VTT to PTS for the .sup, it probably doesn't exactly take the ``00:00:40,929``. It probably take an variable that is an double which cause an rounding error.

**Comment by niksedk** [comment]
Could you test this version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

(fixed rounding here and there: https://github.com/SubtitleEdit/subtitleedit/commit/7010f1473da9455a3df392378e03210ad99bef60 )

**Comment by moi15moi** [comment]
It seems to work.

But, I have like opened 2 issues in one (that wasn't a great idea, sorry)
1. Rounding error when converting vtt to sup
2. The comment I named: ``A brief comment on the way it convert pts to ms`` which, I think, would need to be tested like I said..

**Comment by moi15moi** [comment]
I find a way to test what I have write in ``A brief comment on the way it convert pts to ms``
We need to round it, but subtitle edit already round it, so everything is fine.

Here is my [Sample.zip](https://github.com/SubtitleEdit/subtitleedit/files/10201012/Sample.zip)
