### ISSUE TITLE
Whisper large model (large.bin) download always incomplete

### ISSUE THREAD

**Issue by n-99** [SubtitleEdit/subtitleedit#6514]
The latest normal version of SE downloads about 2GB for me, and the 3.6.10 beta linked somewhere here downloads 2.88GB. since the file is incomplete, it just generates empty files.

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
Could you verify?

**Comment by n-99** [comment]
That's the beta I used.
I downloaded the model by hand, and it seems to be the same size (2.88GB). So I assume it was actually downloaded correctly in the second instance, and you just need to change the size info in the menu. It's running right now (not finished, though, seems to take a very long time even for a short video), so I assume it works. Don't know why it wouldn't work earlier.

**Comment by niksedk** [comment]
Could you attach the error_log.txt file?

` just repeating the same nonsense over and over again` is an whisper bug...
Can be improved in the select speech in the waveform, and right-click in the list view, choose "Selected lines". Audio - Audio to text...

I'm not really sure what you're seeing...

**Comment by n-99** [comment]
Error log just has two "InitializeVideoPlayerAndContainer failed to load video player" from earlier when MPC-HC wasn't selected yet. I'm using the main.exe via the console right now, and it seems to have no problem translating the subs

As for "Can be improved if you select speech in the waveform, and right-click in the list view, choose "Selected lines". Audio - Audio to text...", isn't that what I'm trying to do with Whisper itself?

I'm sorry, I guess the original problem is solved (hopefully…), and I should open another issue for the translate bug.

**Comment by n-99** [comment]
Splitting it up and doing it line by line like in the screenshot took ages, and the results included tons of things like *coughs* or machine learning artifacts (the infamous YouTuber sign-off). Gonna test it again, but a smaller model might actually work better sometimes.
