### ISSUE TITLE
whisper python unable to download models on Windows

### ISSUE THREAD

**Issue by Baenwort** [SubtitleEdit/subtitleedit#6518]
So I'm able to build Whisper on my Windows 10 machine. It works fine when running by itself in a command line.

I'm able to point SE at the proper script directory and it sees the whisper.exe.

However, when I go to select a different model than tiny it seems to be unable to retrieve them:

 
![image](https://user-images.githubusercontent.com/32050048/206937556-7f23fe95-9827-433c-960c-ffa5053ab9f3.png)

**Comment by Baenwort** [comment]
Testing the other models this only occurs with the large model. I am able to download the medium.en and others just fine.

**Comment by niksedk** [comment]
The 3.6.10 final version has a problem downloading the large model, so do try the latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
Better ?

**Comment by Baenwort** [comment]
Yes
