### ISSUE TITLE
2 problems with latest beta

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#6522]
Merge short lines except dialogues

```
- I'm glad.
- Whoo.
```

becomes

`- I'm glad. - Whoo.`

Fix dialogues

```
- No kidding. - All
right, last item.
```

when it should be

```
- No kidding.
- All right, last item.
```

V 3.5.11 works perfectly!!!!

**Comment by niksedk** [comment]
Hm, both works perfectly fine for me... could you attach the actual subtitle, your settings.xml + a screenshot?

**Comment by Ding-adong** [comment]
[sub and set.zip](https://github.com/SubtitleEdit/subtitleedit/files/10231274/sub.and.set.zip)

**Comment by niksedk** [comment]
This seems to be the "after" subtitle... could you attach the "before" subtitle?

**Comment by Ding-adong** [comment]
You mean the original?

[Hill Street Blues 1x01 Pilot.zip](https://github.com/SubtitleEdit/subtitleedit/files/10249423/Hill.Street.Blues.1x01.Pilot.zip)

**Comment by niksedk** [comment]
Yes, I still cannot re-produce this... could you attach a few screenshots?
