### ISSUE TITLE
Subtitle Edit not detecting VOBSUB subtitles for OCR, automatically shows gibberish instead?

### ISSUE THREAD

**Issue by Ocman76** [SubtitleEdit/subtitleedit#6523]
I am using Subtitle Edit to OCR subtitles from ~700 .mpg videos from the late 2000's. So far the OCR (binary image comparison) works great. However on ~10% of the videos I have tried Subtitle Edit does not appear to interpret the subtitles as VOBSUB, and instead somehow opens them directly. When this happens no OCR occurs (the OCR window does not automatically open) and the subtitles are shown as complete gibberish:
![image](https://user-images.githubusercontent.com/45700607/207237795-510a3265-2cb9-4ad5-8f0b-508a0f726175.png)

What's odd is that there doesn't appear to be anything wrong with the VOBSUB subtitles in the video files themselves. They play fine and don't show any odd characters like Subtitle Edit shows. Here is the same video as the screenshot above being played in MPC player:
![image](https://user-images.githubusercontent.com/45700607/207238035-399cd8ea-8c83-40d1-b811-0c0e9f5427a4.png)

What might be going on here? Is there anything I can do to force Subtitle Edit to interpret the subtitles as VOBSUB? Or force it to OCR them?

Any help is greatly appreciated!

**Comment by niksedk** [comment]
Could you supply a sample file?

**Comment by Ocman76** [comment]
Thanks for the quick reply! Yes of course, here is the video from my screenshots above:
[https://www29.zippyshare.com/v/D4Bextof/file.html](https://www29.zippyshare.com/v/D4Bextof/file.html)

**Comment by niksedk** [comment]
> Thanks for the quick reply! Yes of course, here is the video from my screenshots above: https://www29.zippyshare.com/v/D4Bextof/file.html

I'm in Europe, I cannot access zippyshare, sorry.

**Comment by darnn** [comment]
[20110227134914 Subtitle OCR Error.zip](https://github.com/SubtitleEdit/subtitleedit/files/10229128/20110227134914.Subtitle.OCR.Error.zip)

**Comment by niksedk** [comment]
Thx for the file - should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
