### ISSUE TITLE
Virus positive on bitdefender while running whisper

### ISSUE THREAD

**Issue by williethewolf** [SubtitleEdit/subtitleedit#6524]
![image](https://user-images.githubusercontent.com/74451917/207436991-1cec4267-deb3-487f-a221-b0aa73670e16.png)

Virus positive on bitdefender while running whisper

The "infected" files is main.exe and the virus detected is Gen:Variant.Lazy.364938

It happened after installing the latest version (3.6.10) and restarting, then trying to run whisper STT

**Comment by williethewolf** [comment]
Flagged as well by Virustotal

![image](https://user-images.githubusercontent.com/74451917/207439263-242f677a-1b3e-4b56-9e92-25916147dc08.png)

Probably a false positive but...

**Comment by williethewolf** [comment]
It seems to be related to Whisper.cpp implementation.
Im running whisper on a beta from 3.6.7 with no issues.

I saw in a post you added a drop down in a beta for 3.6.8 but I haven't seen it in 3.6.10 and it immediately prompts me to install Whisper.ccp which triggers the virus warning and if I disable the antivirus it gives a "no text found error".

whisper works fine as a standalone in my system.

**Comment by niksedk** [comment]
Please report false negative to your anti-virus provider.

If whisper.cpp gives problems try the whisper php version from https://github.com/openai/whisper
Or compile whisper.cpp via Visual Studio from https://github.com/ggerganov/whisper.cpp

Some improvements for SE/Whisper has been in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by williethewolf** [comment]
There's a mention of a similar issue here from 2018 (similar as in its a similar virus variant false positive and  also 17 services have flagged it)
https://steamcommunity.com/app/416600/discussions/1/3374780959392223564/

I'm not familiar with the issue but it seems to be related to how it is compiled.

**Comment by niksedk** [comment]
Did you report a false positive to your anti-virus provider?

**Comment by williethewolf** [comment]
There was no option for it, but there are still 17 positives in virus
total, which would also need to be addressed somehow.
It would also be a little bit irresponsible of me to report a false
positive on something I have not inspected the source code for or compiled
myself, for which I haven't had a chance.

**Comment by niksedk** [comment]
You're using Bitdefender, so you should report it to Bitdefender.

**Comment by niksedk** [comment]
Latest beta use a slightly newer whisper.cpp build - it's still flagged: https://www.virustotal.com/gui/file/a02edae3f2ded0b58c36bce5184ed77f09e9ad5c60464f94f7a7b5b847b679e4
I've reported a false positive to Bitdefender, but feel free to do the same.

Many anti-virus programs just flags unknown exe files as virus... has happened lots of time for SE: https://github.com/SubtitleEdit/subtitleedit/issues?q=is%3Aissue+virus+is%3Aclosed
