### ISSUE TITLE
Dropbox and Drive Plugins

### ISSUE THREAD

**Issue by v187077924** [SubtitleEdit/subtitleedit#6527]
Hello, both Dropbox and Drive Plugins are not working at all and causing the program to crash. please fix it. thx

**Comment by niksedk** [comment]
Drive plugin works fine for me... I've removed the dropbox plugin
( plugins is another repro - https://github.com/SubtitleEdit/plugins )

**Comment by niksedk** [comment]
Dropbox should also work now...
