### ISSUE TITLE
Does not work with network user profiles

### ISSUE THREAD

**Issue by ISKANDER499** [SubtitleEdit/subtitleedit#6530]
Good afternoon!
Transferring an audio track to text does not work if the user profile is not local, but network.
Example of a network profile path:
\\noname.com\profile\UserData\user123\Application Data

Is it possible to make the translation of audio into text Subtitle Edit could work with network profiles?

**Comment by niksedk** [comment]
You mean Video - Audio to text via Vosk/Whisper ?

**Comment by ISKANDER499** [comment]
> You mean Video - Audio to text via Vosk/Whisper ?

Yep, Video - Audio to text (Vosk/Kaldi)
