### ISSUE TITLE
Tricky ISMT file

### ISSUE THREAD

**Issue by LucretiaAudrey** [SubtitleEdit/subtitleedit#6531]
Hi! How can i convert this to srt without losing timings?

This is from Canal+ manifest, extracted using

yt-dlp --write-subs --sub-langs all --allow-u --skip-download  "https://ec37.waw3.cache.orange.pl/canal/v/canal/vod/store01/CAP_21048489_v1/_/hd4-hssdrm02.ism/Manifest" --external-downloader aria2c

[manifest and subs.zip](https://github.com/SubtitleEdit/subtitleedit/files/10244689/manifest.and.subs.zip)

**Comment by niksedk** [comment]
If you open the .ismt file in SE the timings are bad?

![image](https://user-images.githubusercontent.com/1261331/208174587-5e107d6d-8e82-4d03-96b6-71beef8eedca.png)
