### ISSUE TITLE
SUGGESTION: Define image palette BEFORE batch conversion 

### ISSUE THREAD

**Issue by mpek** [SubtitleEdit/subtitleedit#6533]
Thank you for the batch feature!
It would be nice to be able to set some settings with the image palette before running a batch. 

It would be nice to be able to TURN OFF: "Use custom colors"

Backstory: 
I let SE batch convert all my videos to have all subtitles exported, but DVD subtitles in particular are often not usable, because those characters being generated are not a language. 

"Use custom colors" turned ON: 
https://i.imgur.com/YZhoCdZ.png

"Use custom colors" turned OFF: 
https://i.imgur.com/jK2b8MS.png

When doing them one by one preview window shows what to expect and I recognized that often, not always, turning off "Use custom colors" reduces the task to SE prompt for unknown words only, but all other text is usable! 

What do you think?

**Comment by niksedk** [comment]
I think SE just uses the last OCR settings
There's really no right or wrong setting for using custom palette. The default settings is "off". Some vobsub files have colors not suited well for OCR or just wrong colors.
Vbsub may not be well suited for batch conversion.
