### ISSUE TITLE
Linux: audio to text error persists

### ISSUE THREAD

**Issue by ebaldino** [SubtitleEdit/subtitleedit#6534]
Hi. 
I'm having the same problem as mentioned in issues [6071](https://github.com/SubtitleEdit/subtitleedit/issues/6071#top) and [6276](https://github.com/SubtitleEdit/subtitleedit/issues/6276)

I carefully followed all the instructions there (installed vosk, created symlink), and I'm still getting the exact same error message as they did. The message appears after about 3.5 seconds of "Extracting audio" when I use either vosk or whisper.

**Ubuntu 22.04
SE 3.6.10.0**

![image](https://user-images.githubusercontent.com/11170427/208262894-c9cacbd5-9be9-44c4-8135-c807435940bc.png)

**Comment by ebaldino** [comment]
I'm so embarrassed.
I put the symlink in SubtitleEdit/Vosk, not in SubtitleEdit/
It's working now.
Sorry.

**Comment by niksedk** [comment]
I'm glad it's working :)
