### ISSUE TITLE
Whisper return the results with dots!

### ISSUE THREAD

**Issue by v187077924** [SubtitleEdit/subtitleedit#6537]
I've launched a movie with Whisper 3 times and after for like 45 minutes or so, every time the result was just a Dot for each line!! I don't know what's causing this. Can somebody help with this?

![image](https://user-images.githubusercontent.com/35186406/208336936-e42344cb-6878-4226-a839-4058d25dd18c.png)

**Comment by coastal45** [comment]
Can you add some more details? OS, SE version. Whisper php or CPP? Detect language?
Also can you add a sample including the a portion of the dots section and the normal text that preceded it?
"3 times" the same video?

**Comment by n-99** [comment]
Whisper often just starts repeating the same text over and over again, here it just happens to be a period. So this is a bug in Whisper, and the only solution for SE would be to recognize lines repeating more than twice and then restarting Whisper at that timestamp, possibly with some changed parameters to get different text.

**Comment by niksedk** [comment]
Issues with Whisper should be reported here: https://github.com/openai/whisper

I hope some of the Whisper issues will be fixed (looping, freezing) and the timestamps will be more precise.
