### ISSUE TITLE
"Value cannot be null" running audio to text with whisper

### ISSUE THREAD

**Issue by ebaldino** [SubtitleEdit/subtitleedit#6538]
Hi again.
I tried to be more thorough and pay more attention this time.

I'm trying to use Whisper for audio to text, as the quality of the recognition if far better than Vosk.
The subtitle results with Vosk are pretty much useless, at least for my use case. It's faster to do it by hand from scratch than to fix what it generates.
Whisper seems to produce much better results, even re:punctuation, so I'm hoping the resulting subtitles will be workable.

I can run Whisper from the command line with the small and medium models, and the results are good. I even converted its output to an SRT file, but the lines are just too long. 

When I try to run audio to text within Subtitle Edit, with the Whisper option (no matter which model I use), it will run for a few minutes and give me a "Value cannot be null. Parameter name: path1" error, like shown in the image below.

I would appreciate any help.
Thanks

![image](https://user-images.githubusercontent.com/11170427/208476216-9683773b-947d-42bf-8f4b-11481941d312.png)

**Comment by niksedk** [comment]
I think this has been fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
Right?

**Comment by ebaldino** [comment]
Yes!!!
Works great.
Thank you!
