### ISSUE TITLE
Import original image position from subtitle?

### ISSUE THREAD

**Issue by antoniu200** [SubtitleEdit/subtitleedit#6539]
Hello,

I have a couple of recordings from TV with DVB Sub which I would like to cut and re-encode. This means I would also have to edit the subtitles.

To consume as little time as possible (no OCR basically), I would go about editing the image-based subtitles' timecodes, display them earlier by how much I remove (ads) and save the resulting timecodes.
Then I would re-import the DVB Subs, apply the timecodes and export them as Blu-ray subtitles (since it has minimum quality impact on the images).

Problem appears here: many DVB Subtitles have custom positions applied to certain images, but Subtitle Edit does not import them from the original file, but rather asks me for a position for each of the images contained in the DVB Sub. **Could this be changed so that Subtitle Edit automatically picks up the original image positions right from the subtitle?**

Also, another suggestion. Please allow timecode editing in the OCR window, it would save some time while going back and forth exporting timecodes, then re-importing them.

**Comment by niksedk** [comment]
You can export to .sup directly from the TS sub chooser:
![image](https://user-images.githubusercontent.com/1261331/208498212-1f136bd7-6f80-4526-ae68-af7bd8c97b53.png)

Or the OCR window:
![image](https://user-images.githubusercontent.com/1261331/208498028-85c7c1fc-389f-4117-a374-178a67b98c16.png)


Then edit the sup file via:
![image](https://user-images.githubusercontent.com/1261331/208497696-190fd771-b201-46f2-9b8e-d4129753e4c3.png)

**Comment by antoniu200** [comment]
Thanks for the quick reply!

> You can export to .sup directly from the TS sub chooser:

Okay, that may be useful for MPEG-TS files with multiple subtitle sources, but my recordings usually only have one, so that menu never appears.

> Or the OCR window:

That's how I do them.

> Then edit the sup file via:

Yeah, that'll be useful. Same can be applied to .mks DVB Sub. Thanks!

> As far as I know the subtitle positions are kept.

They're not, please check the attached subtitle (it may only work after you mux it in a video, it's raw DVB Sub), the first few images should display at the center of the screen, but after conversion, their position changes to bottom center. MPC-HC correctly displays them.

Now that I applied your advice on editing those subtitles, I can notice Subtitle Edit does not load DVB Sub positions at all. When editing, all of them appear it the top-left corner. I am pretty sure Subtitle Edit does not properly support DVB Sub positions. Please check with the attached file.

[20220408 1225.zip](https://github.com/SubtitleEdit/subtitleedit/files/10263268/20220408.1225.zip)

**Comment by niksedk** [comment]
I will look into it... in the meanwhile you could also test Tools - Batch convert - TS => Bluray sup

**Comment by antoniu200** [comment]
> also test Tools - Batch convert - TS => Bluray sup

Tested. If I select the original MPEG TS file as source, it outputs a 0 byte .sup. If I select the .mks DVB Sub, it doesn't list it in the input files list.

**Comment by niksedk** [comment]
Does this beta work better for you? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

I've tried to improve the support for DVB in Matroska (not something I've seen often)

**Comment by antoniu200** [comment]
Yes, the Beta fixed the issue, but only on Matroska subtitles. On .ts files, the issue still persists and is somewhat different, while the sync is also completely wrong. It's worth mentioning that the .ts file has a -880 ms (negative) delay, but Subtitle Edit seems to subtract more than 880 ms. See the attached images.
Also, is the frame rate a default DVB Sub feature? Not that it affects the final result, but because on .mks subtitles, Subtitle Edit reports a wrong frame rate, while on .ts files it reports the correct frame rate.
![mks](https://user-images.githubusercontent.com/33966771/209352658-cba1e0fc-02f2-4afc-a189-2dd2359ff9fa.PNG)
![ts](https://user-images.githubusercontent.com/33966771/209352662-344f8127-d65c-425a-9dd0-e0cacff29f84.PNG)

**Comment by niksedk** [comment]
Could you attach the .ts file too?

**Comment by antoniu200** [comment]
It's going to take a while, since the file is 4 GB and AviDemux does not keep the DVB subtitle source, so it'll have to be cut on my DVB-C decoder.

**Comment by niksedk** [comment]
OK, I think a broke a few things when working the on the mks dvb... hopefully better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by antoniu200** [comment]
Tested, it works perfectly now. Thank you!

**Comment by niksedk** [comment]
Thx for reporting and testing :)

**Comment by antoniu200** [comment]
Oops, forgot to test one thing.

The timestamps are still wrong when opening a .ts, like I showed above. Not worth reopening the issue just for that, since it was originally opened for something else. But it would definitely help my conversion process if you could fix that.

Would it be worth opening a new issue? Do you reckon you could fix that?

**Comment by niksedk** [comment]
Hm, I don't know if I can fix it without looking at the .ts file.
