### ISSUE TITLE
File Type Names

### ISSUE THREAD

**Issue by witchpiggie** [SubtitleEdit/subtitleedit#6541]
Not sure if it's just the most recent version that did this, but I've noticed that the 'Type' of file listed in Windows Explorer is the path to Subtitle Edit - Not the type of file.

For instance:
.srt  -- C:\Program Files\Subtitle Edit\

Expected:
.srt -- Subtitle (or something)

Not all extensions are broken.

For instance (still correct):
.ass -- Advanced Sub Station Alpha subtitle file

**Comment by niksedk** [comment]
Looks okay to me:

![image](https://user-images.githubusercontent.com/1261331/209315503-02be3952-5572-4454-8209-daadaebe5b75.png)

**Comment by witchpiggie** [comment]
Oh. Sorry I didn't see your reply. I don't know what to tell you. Using the latest installer that's not what shows for me.
