### ISSUE TITLE
"Input string was not in a correct format" Error

### ISSUE THREAD

**Issue by ahmadtaeb** [SubtitleEdit/subtitleedit#6542]
Hey **niksedk**, I just recently got an error when I tried to open and save .Ass file
![image](https://user-images.githubusercontent.com/95315570/209343142-51550184-8724-4c4f-a49f-e791f8691654.png)
![image](https://user-images.githubusercontent.com/95315570/209343150-ce1a58b8-604f-4ba8-8267-013112c3b248.png)
I'm using the latest version (3.6.10)

**Comment by niksedk** [comment]
Hi @ahmadtaeb, could you attach the subtitle file?

**Comment by ahmadtaeb** [comment]
[matt damon.zip](https://github.com/SubtitleEdit/subtitleedit/files/10295427/matt.damon.zip)

**Comment by niksedk** [comment]
OK, works fine in latest beta here too :)
