### ISSUE TITLE
How to change wave displaying direction to rtl?

### ISSUE THREAD

**Issue by mohsenhrt** [SubtitleEdit/subtitleedit#6543]
Hi,  In rtl languages such as Arabic, there is a need to display the waveform window from right to left. Can we do this?
Thanks

**Comment by niksedk** [comment]
Sorry, it's not possible.

**Comment by mohsenhrt** [comment]
Can I split video into segments and order splitted sounds from rtl in wave window?

**Comment by niksedk** [comment]
Sorry, that's not possible in SE.

**Comment by mohsenhrt** [comment]
Ok and Thanks.
