### ISSUE TITLE
Subtitle appearing squeezed in preview

### ISSUE THREAD

**Issue by zcraber** [SubtitleEdit/subtitleedit#6544]
The subtitle is appearing weird like squeezed in a video with 410 x 720 pixels resolution. 
Any ideas to fix this? Version `3.6.10`

![image](https://user-images.githubusercontent.com/61133303/209443491-bf19c6ce-6df7-4cd7-997c-693ffc9f9918.png)

Attaching the video and SRT files.

[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/10298850/test.zip)

**Comment by niksedk** [comment]
That's by design... you can let SE (and not mpv) handle subtitle preview in Options - Settings - Video player

**Comment by zcraber** [comment]
Ok, unchecking that fixed the preview issue. 
But if I burn the sub using `Generate video with burned-in sub` it generates a video with distorted text! Any workarounds?

https://user-images.githubusercontent.com/61133303/209467958-2b2bc636-c5d5-4c19-92c8-feab6db72b71.mp4

**Comment by niksedk** [comment]
Hm, nothing is distorted here...

https://user-images.githubusercontent.com/1261331/209469634-6847fd04-4fc0-4c58-b734-7d91ce576957.mp4

**Comment by niksedk** [comment]
SE does not have orientation detection - so perhaps the width/height was switched!

**Comment by zcraber** [comment]
> SE does not have orientation detection - so perhaps the width/height was switched!

But I wonder how it worked perfectly on your machine. From my end, I get this distorted.

**Comment by niksedk** [comment]
I don't know, sorry.
If it's a long time since you downloaded ffmpeg, you can try to re-download ffmpeg.
