### ISSUE TITLE
SubtitleEdit beta (12/24/2022) OpenSubtitle Upload error

### ISSUE THREAD

**Issue by Baenwort** [SubtitleEdit/subtitleedit#6546]
I get the following:

![image](https://user-images.githubusercontent.com/32050048/209457187-17fa4d85-81f2-4205-a1e4-34964706133b.png)

When I click the three dots by IMDB and then press search.

**Comment by niksedk** [comment]
plugins is another repro - https://github.com/SubtitleEdit/plugins
