### ISSUE TITLE
Error message: No text found!

### ISSUE THREAD

**Issue by msjsc001** [SubtitleEdit/subtitleedit#6547]
![image](https://user-images.githubusercontent.com/93178788/209463185-74f18acf-4322-484b-b94c-071e94b442a5.png)

My system is Win11 22H2, 32G RAM, Subtitle Edit version is 3.6.10
I have installed the Whisper and torch libraries for python.
I have tried many times to recognize the video with Whisper, but it always says
"No text found!"

**Comment by niksedk** [comment]
Could you give latest beta a test run: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

You can right-click in the Whisper window to switch between the "OpenAI Whisper (python)" and the "Whisper c++" version.

**Comment by msjsc001** [comment]
![image](https://user-images.githubusercontent.com/93178788/209463815-02f315ed-8fe7-4d3a-b222-b5fd05118fc2.png)

This error occurs when "large" is selected, but not for other options .
I will try the latest beta version later .

**Comment by niksedk** [comment]
SE 3.6.10 cannot download the large model, sorry. That should be fixed in latest beta.

**Comment by msjsc001** [comment]
> Could you give latest beta a test run: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
> 
> You can right-click in the Whisper window to switch between the "OpenAI Whisper (python)" and the "Whisper c++" version.

![image](https://user-images.githubusercontent.com/93178788/209464349-9ed4ac15-2213-4fac-be55-ae29220d87fc.png)
In the SE program in this link, after right-clicking and selecting "Whiser php", I can download "lare". After the download is complete, I will try to generate subtitles. Thank you for your reply.

**Comment by msjsc001** [comment]
![image](https://user-images.githubusercontent.com/93178788/209469041-d1b0c8dd-6e8c-4c33-8ac8-05762d7b3272.png)

I tested the new version of SE's 'large' and it ran smoothly, but I noticed two issues.

It took a long time to download 'large', about 3 hours. If a link could be added to allow users to use a download software to download it, the speed would probably be much faster.
When 'large' recognition is running on the SE software, it almost does not use CPU or GPU, which means that a video of 1 hour duration may take dozens of hours to complete recognition. If there was an option to fully (or partially) use the CPU or GPU, it would likely be better

**Comment by msjsc001** [comment]
The program ran for about 2 hours and then prompted an error 
![image](https://user-images.githubusercontent.com/93178788/209473919-023ff29b-88f0-4239-8b50-2e6421e1b7be.png)

**Comment by niksedk** [comment]
OK, I've updated the help page a bit: https://www.nikse.dk/subtitleedit/help#audio_to_text (you might need to press Ctrl+F5 to refresh content)

Latest beta also has a few minor fixes: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
The whisper (original) models was linked a bit wrong - so you actually might need to re-download models.

Also, do attach the file "error_log.txt" from the SE data folder (press Ctrl+alt+shift+D in SE to open this folder)

If you're using Whisper CPP then your CPU should support AVX2 or it will be *very* slow.

**Comment by msjsc001** [comment]
Okay, I'll try again.

**Comment by msjsc001** [comment]
![image](https://user-images.githubusercontent.com/93178788/209478433-8e0d2861-3e0d-496b-b73c-6e3b58ef8d8e.png)

![image](https://user-images.githubusercontent.com/93178788/209478494-caaf61ba-3523-4b79-a09c-dab65d7c5e5e.png)

Thank you very much for your help.
I downloaded "ggml-large.bin" from "https://huggingface.co/datasets/ggerganov/whisper.cpp/tree/main", and it only took a few minutes. I renamed it to "large.bin" and placed it in "SubtitleEditBeta\Whisper\Models". When I opened SE, it started running normally, but the CPU usage was only 35% (I have an AMD R7 3700X CPU). Is there a way to make the program use more CPU?

**Comment by msjsc001** [comment]
![2T5E)$9{R _)R31DF0Y7OA3](https://user-images.githubusercontent.com/93178788/209478784-403042aa-23ee-4108-af27-ca5c66ed80fd.png) Also can the program calculate a completion countdown display?

**Comment by JBreezy222** [comment]
So why does this work with the beta version and not the regular version? I have been trying since whisper came out to get it to work on Subtitle Edit. And this was the first time it has ever worked for me. But why did it take almost 3 hours to sub a 20 minute video? I know GPU is faster than CPU but 3 hours? I have the Intel GPU and not NVIDIA GPU. So CUDA was a no go. Any answers to make this process much faster than 3 hours?

**Comment by niksedk** [comment]
> ![2T5E)$9{R _)R31DF0Y7OA3](https://user-images.githubusercontent.com/93178788/209478784-403042aa-23ee-4108-af27-ca5c66ed80fd.png) Also can the program calculate a completion countdown display?

It does when some info comes back from Whisper.

**Comment by niksedk** [comment]
Yes, the large model is very slow - but works well.
If you're using whisper cpp, you can try to up the number of threads used... set "WhisperExtraSettings" to "--threads 8" (will use 8 threads instead of the defailt 4).

**Comment by msjsc001** [comment]
I don't know anything about programming. Where can WhisperExtraSettings be set? (I couldn't find it in the help file or settings.) 

![image](https://user-images.githubusercontent.com/93178788/209517831-6c3d70a7-7400-4db4-be21-c83e27db5960.png)

Also, the sentence will change lines every 4-5 words after recognition, which can cause problems for machine translation of subtitles. How can I make it change lines after about 10 words ?

**Comment by niksedk** [comment]
"WhisperExtraSettings" is in the file Settings.xml in the SE data folder.

Machine translation in SE should work just fine with split lines.

**Comment by msjsc001** [comment]
> "WhisperExtraSettings" is in the file Settings.xml in the SE data folder.
> 
> Machine translation in SE should work just fine with split lines.

Thank you for your patient answer, my problems are basically solved。

**Comment by niksedk** [comment]
@chenlung:

What does the `error_log.txt` say?

You can also switch between `the original python` and `the c++ version`.

![image](https://user-images.githubusercontent.com/1261331/215890335-d6eed597-87d5-4298-8122-29c0adfd2787.png)

**Comment by chenlung** [comment]
> @chenlung:
> 
> 
> 
> What does the `error_log.txt` say?
> 
> 
> 
> You can also switch between `the original python` and `the c++ version`.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1261331/215890335-d6eed597-87d5-4298-8122-29c0adfd2787.png)
> 
> 

How do I generated an error log?

How do I get the Python version?

**Comment by niksedk** [comment]
Your questions should be answered here: https://www.nikse.dk/subtitleedit/help#audio_to_text
(press ctrl+F5 to get the latest version)

**Comment by chenlung** [comment]
> Your questions should be answered here: https://www.nikse.dk/subtitleedit/help#audio_to_text (press ctrl+F5 to get the latest version)

Thank you!

- [Here](https://github.com/SubtitleEdit/subtitleedit/files/10551750/No.text.found.txt) is the log.
- For loading the Python version, it looks for Whisper.exe, but I have large-v2.pt.

Feedback: for choosing between Python and C++, perhaps a radio button (suggesting one choice) would be better than a tick?

**Comment by niksedk** [comment]
Thx for the log. "error: unknown argument: --print-progress" means you have an older whisper cpp version. Try deleting main.exe + whisper.dll from your "SE data foler/Whsiper" folder - which should trygger a re-download of whisper cpp.

**Comment by chenlung** [comment]
> Thx for the log. "error: unknown argument: --print-progress" means you have an older whisper cpp version. Try deleting main.exe + whisper.dll from your "SE data foler/Whsiper" folder - which should trygger a re-download of whisper cpp.

Thanks, that works!

I don't know if a provision can be added to alert the user, possibly offering to automatically fix it?
