### ISSUE TITLE
New whisper compile much slower

### ISSUE THREAD

**Issue by n-99** [SubtitleEdit/subtitleedit#6551]
I exchanged the whisper.cpp-SSE2-2022-11-16 automatically downloaded by an earlier version by hand with whisper.cpp-SSE2-2022-12-19, and the sub generation is now about 25 to 30 times slower (3.5 minutes of text in 8 hours instead of 18 minutes). whisper.cpp-SSE2-2022-12-19 has the same problem. This might be a whisper bug, but it could also be a compile with some missing optimization or something of that sort.

Command used:
main.exe -m large.bin -l ja --translate -f input.wav -t 3 -osrt

**Comment by niksedk** [comment]
Use the AVX2 build...

**Comment by Baenwort** [comment]
Where did you find the AVX2 build?

**Comment by niksedk** [comment]
My builds are here: https://github.com/SubtitleEdit/support-files/tree/master/whisper

You can compile with VS / git pretty easily:
1) install whisper cpp with git: `git clone https://github.com/ggerganov/whisper.cpp.git`
2) run: cmake `-S . -B ./build` in the "Whisper" folder (use a visual studio 22 Developer command prompt)
3) Open .sln file and compile
