### ISSUE TITLE
"Fix dialogs on one line" for … does not work

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#6552]
In SE 3.6.10, "fix dialogs on one line" function in fix common errors does not work, where a word in a line ends with … (not ... 3 dots).

Ex.
```
1) - How are you… - How are you? -> How are you… - How are you?
2) - How are you... - How are you? -> How are you...<br />- How are you?
3) - How are you? - How are you? -> How are you?<br />- How are you?
```

![fix](https://user-images.githubusercontent.com/3875423/209485580-f0750573-9b87-4af6-9e49-2ca7011515ac.png)

I want 1) to be processed like 2) and 3) because some subs use … instead of 3 dots.
TIA

**Comment by niksedk** [comment]
Thx :)
Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
