### ISSUE TITLE
Program Closes without Error Message (But ok in Ver 3.5.11 all later versions have issue)

### ISSUE THREAD

**Issue by axleg31** [SubtitleEdit/subtitleedit#6555]
The attached file contains the subtitle streams only. The video and audio streams have been removed using ffmpeg. (it makes a small file and illustrates the issue). One works fine the other exhibits the error.
[Examples_Of_OK_and_Bad.zip](https://github.com/SubtitleEdit/subtitleedit/files/10307905/Examples_Of_OK_and_Bad.zip)

If Example_of_File_that_fails.ts is dragged onto the subtitle area of Ver 3.6.10 the OCR window opens as usual. (The OCR will work but is not required to show issue). Press OK and for me the timings go into the main window of a couple of seconds which then closes without any message. I have worked backwards through old versions 3.5.11 is ok however 3.5.12 introduces the issue.  

If Example_of_OK-File .ts is processed the same way that has no issues.

(The original files were both taken off a DVR recorder).

**Comment by niksedk** [comment]
Thx for the files.
I cannot re-produce the error. It could be something with video player. What video player do you use inside SE?

**Comment by axleg31** [comment]
Thanks for looking. I normally use VLC, but I have tried DirectShow as well. Both the same. I will have to try on another PC. The work round of the old version is good for me.

**Comment by niksedk** [comment]
OK, give mpv a go too - see Options - Settings - Video player.
You could also try to see if info is available in error_log.txt,

**Comment by axleg31** [comment]
OK thanks - this looks to be an issue with my PC. There are no new entries in the error_log. MPV didn't help either. However I have created a portable installation, this fails on my PC including on a new user, just tried on another machine and it is fine!!  Just strange it works on 3.5.11 but not 3.5.12??
Thanks for your help but the issue appears to be mine alone. Apologies for wasting your time.
