### ISSUE TITLE
If More than Two Lines Per Sub - Issues

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#6556]
I have noticed that if you have more than two lines per subtitle, many shortcuts don't work. E.G: Move first word from next line up, etc. Autobreak lines isn't as effective as it normally is, probably because it ignores do-not-break list or summat.

**Comment by vaclavmuller** [comment]
Would it be possible to automatically split lines containing the <br> tag into two separate lines? While the total time of the subtitle would be divided in the ratio of the length of the text before and after the <br> tag.
