### ISSUE TITLE
Crash when using vosk

### ISSUE THREAD

**Issue by jssilva25** [SubtitleEdit/subtitleedit#6559]
When trying to translate audio to text, using other than vosk-model-en-us-0.22-lgraph, meaning either vosk-model-en-us-0.22 or vosk-model-en-us-0.42-gigaspeech, programm completely crashes after extracting audio and starting conversion.

  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-12-27T16:08:15.1060791Z" /> 
  <EventRecordID>33579</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>MyPC</Computer> 
 
  <Data>SubtitleEdit.exe</Data> 
  <Data>3.6.10.0</Data> 
  <Data>637bbeac</Data> 
  <Data>libvosk.DLL</Data> 
  <Data>0.0.0.0</Data> 
  <Data>628f8017</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000017260</Data> 
  <Data>1048</Data> 
  <Data>01d91a0d302d0834</Data> 
  <Data>C:\Program Files\Subtitle Edit\SubtitleEdit.exe</Data> 
  <Data>C:\Users\me\AppData\Roaming\Subtitle Edit\Vosk\libvosk.DLL</Data> 
  <Data>afdb6073-ccf2-4d07-b3bb-12e1cf4b1b85</Data>

**Comment by jssilva25** [comment]
Furthermore, I'm running SE on a Windows 10 virtual machine (2 cpu cores, 4GB memory) with VirtualBox on a macOS Catalina MacBook Pro. It's really a pity I can't run SE natively; SE is an irreplaceable application. Tried Mono but doesn't work.

**Comment by niksedk** [comment]
OK, you're probably out of memory... 4GB is not a lot for Windows + SE + speech recognition

**Comment by jssilva25** [comment]
Thank you for replying and thank you for a most useful application.
I thought so too and I've tried with 8GB before posting, same result.

**Comment by niksedk** [comment]
OK, my computer peek at 19GB with Windows 11 + SE + Visual Studio + Vosk with "vosk-model-en-us-0.22"... so probably still memory :)

**Comment by jssilva25** [comment]
Thank you for supporting.
In the meanwhile, I tried whisper basic and it took a lot longer, about 7 hours for an interview (lots of talk) of an hour fifty minutes and 64k characters. It would probably take much less on a bare metal machine.
But, for my surprise, the quality is far, far better than vosk.
So, my problem is solved.
Thank you again for an application miles ahead of any similar.

**Comment by jssilva25** [comment]
Thank you! I'll give it a try although I won't trade shorter time for 
less quality because my VM is hosted on my TrueNAS server which is, 
anyway, working 24/7.

Wish you a very good year!

**Comment by niksedk** [comment]
I wish you a very good year too :)
