### ISSUE TITLE
Export .sup

### ISSUE THREAD

**Issue by donnje** [SubtitleEdit/subtitleedit#6560]
Hi,
How It exports to .sup if I do file-export-bluray sup the file has an extension .it and not .sup and then I rename it is not recognized by other apps

**Comment by niksedk** [comment]
How do you export? A few screenshots?

**Comment by donnje** [comment]
I muxed a dvd and I should add the translated sub, the program I use to add it is MuxMan which only accepts .sup files how should I do?
I do file - export -bluray .sup with these screenshots [and](https://i.postimg.cc/zGpvGjFT/Screen-Shott2069-vert.jpg) it offers me to save in .it and not .sup maybe it doesn't work for dvds

**Comment by niksedk** [comment]
I think you're exporting to VobSub (.sub)... try Blu-ray sup:

![image](https://user-images.githubusercontent.com/1261331/209862866-f69a3739-7726-4a6e-8253-ed5f9b4fa2c9.png)


Note that MuxMan might need another .sup file than a Blu-ray sup file... (e.g.  HD-DVD)

**Comment by niksedk** [comment]
The `Subpictures_23.it` is probably because you have a subtitle file called something like `Subpictures_23.it.srt`...

![image](https://user-images.githubusercontent.com/1261331/209863324-654344e5-9b8b-49e0-beae-c587c407d5b5.png)

The correct extension should be added on save, to e.g. `Subpictures_23.it.sup`

**Comment by donnje** [comment]
thanks for your quick reply,
yes MuxMan needs not a Blu-ray sup but a DVD sup, is it possible? what
would be HD-DVD?

Il giorno mer 28 dic 2022 alle ore 20:31 Nikolaj Olsson <
***@***.***> ha scritto:

**Comment by niksedk** [comment]
Sorry, I'm not familiar with DVD sup... so it's not an export format in SE, sorry.

Some really old format or specific for your application?

**Comment by donnje** [comment]
thanks anyway, unfortunately only DVD sup

Il giorno mer 28 dic 2022 alle ore 20:42 Nikolaj Olsson <
***@***.***> ha scritto:

**Comment by niksedk** [comment]
Perhaps this one can help? https://download.videohelp.com/DVDSubEdit/
(Seems very old though ;)

**Comment by donnje** [comment]
Thanks!

Il giorno mer 28 dic 2022 alle ore 20:48 Nikolaj Olsson <
***@***.***> ha scritto:
