### ISSUE TITLE
Will Whisper for the future SE support GPU use?

### ISSUE THREAD

**Issue by msjsc001** [SubtitleEdit/subtitleedit#6562]
I recently used the  [**beta 3.6.10**](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip)  version of SE's Whisper Larger to recognize many videos with good results. Will Whisper for SE support the use of GPU in the future? (My GPU is GTX1050TI)

![image](https://user-images.githubusercontent.com/93178788/210037981-cfb1a929-de32-4404-b5a1-71398002998d.png)

Also, the beta version of SE does not have the remaining time display.

**Comment by niksedk** [comment]
ATM, SE supports the "original OpenAI Python" version + the "Whisper CPP (C++)" version (right click in SE window to switch between the two version. The Python version can be a bit difficult to install.

I think Whisper will always be slow with the large model, but hopefully it will improve over time (incl. better GPU support).

Read more here:
https://github.com/ggerganov/whisper.cpp/discussions/126

So yes, I plan to update to future Whisper versions when they are available, but GPU support is Whisper is something Whisper/framework developers will have to fix.
