### ISSUE TITLE
Why does this double line happen and is there a fix?

### ISSUE THREAD

**Issue by Masina86** [SubtitleEdit/subtitleedit#6564]
I tried everything Grayscale on/off, invert colors, crop transparent colors it is always the same double line recognition. 

![1](https://user-images.githubusercontent.com/73963066/210116432-260faadf-c545-44e2-b471-7b75af0a1197.png)
![2](https://user-images.githubusercontent.com/73963066/210116433-79793699-4cdb-42e8-bd02-2f5db5403a72.png)
![3](https://user-images.githubusercontent.com/73963066/210116434-8142fbc1-7195-467d-b2f8-805326f84286.png)

It is binary image compare. The line is "Контрола, тука ЛФ1. Примероците се обезбедиме и си одиме дома." If someone needs the letters and wanna try something. Thanks in advance niksedk for the hard work until now i love subtitle edit.

**Comment by darnn** [comment]
Try changing "Min. line height (split)" in the main OCR window, where you set the OCR method and so on.

**Comment by Masina86** [comment]
> Try changing "Min. line height (split)" in the main OCR window, where you set the OCR method and so on.

I did. I tried 5,10,20,30,50,70,100,130,150. It was the same on every one of them. Maybe should be a default shrink button without expanding first?

**Comment by darnn** [comment]
Hmm. I'm afraid you'll have to wait from a response from the developer himself, then, since I'm just a fellow user. Meanwhile, it might help if you can upload the subtitle itself (as idx/sub, for instance).

**Comment by niksedk** [comment]
Sorry, only Tesseract can handle lines this close.

**Comment by darnn** [comment]
I would also try using SE to get an SRT file with the proper timecodes, but doing the actual OCR in Finereader and then importing the text and fitting the timecodes onto it.
