### ISSUE TITLE
Subtitle edit 3.6.10 starts automatic translation but leaves target field open

### ISSUE THREAD

**Issue by Bertemem** [SubtitleEdit/subtitleedit#6565]
I am working on translations with Deepl.pro which is great and with subtitle edit from nikse.dk which I also like. I have the API from Deepl and entered the API-code in SE. Now when I have an srt-source file in English and want to translate it into Dutch it does start the process and you can see that he is working and scrolling down each line but it doesn't fill the target lines with translated text. Am I missing something? 

Thanks in advance for your advice.

**Comment by niksedk** [comment]
Are you using the latest version of the DeepL plugin?

**Comment by Bertemem** [comment]
Hello niksedk, thanks for your reply. 
Yes I think so. I installed SE 3.6.10 today and renewed the api key (I subscribed at deepl 2 weeks ago), installed it today at my windows pc. Any way I can check if I have the latest version?
Thanks, Bert

**Comment by niksedk** [comment]
>> Any way I can check if I have the latest version?

Check File - Plugins...
