### ISSUE TITLE
google ocr crashing after few lines

### ISSUE THREAD

**Issue by T0biasCZe** [SubtitleEdit/subtitleedit#6567]
I am trying to ocr subtitles using the google ocr, i setuped the api (including billing etc) and when i click Start OCR, it convert 5-10 lines, and then it throws this error. when i click retry, pause, and then again start ocr, it again converts 5-10 lines and throws that same error again
![obrazek](https://user-images.githubusercontent.com/44525446/210158556-20692c7f-936a-45ec-b8e1-e33be835564d.png)

**Comment by thiraphat98** [comment]
To use the Google Vision API, a paid subscription is required.

**Comment by thiraphat98** [comment]
Try setting APIKey for Google Vision API only.
