### ISSUE TITLE
Is it possible to add below 2 features?

### ISSUE THREAD

**Issue by nissansz** [SubtitleEdit/subtitleedit#6568]
1. Jump with single click, instead of double click, or add an option to choose single click or double click.
![image](https://user-images.githubusercontent.com/41010669/210162054-38123fe2-12c6-41a4-882e-1ceca6e917bc.png)

2. When jumping to next or previous line, is it possible to add an option to stop in the middle of the time code?
Sometimes, the time code extracted is a little different from embedded subtitle, need to stop at a middle position to show both for comparing.

**Comment by nissansz** [comment]
When jumping to next line, for example, at a 3rd line,
sometimes, Subtitle may pause at the screen of 1st line,
I think there must be a bug

**Comment by nissansz** [comment]
It seems that, when the play is stoped after jumping to one line, the screen goes back to beginning of a time code.
So, may be if there is an option to go back to middle, it may be a solution for my demand.

**Comment by niksedk** [comment]
Would a double click on list view line action `Go to video position - 0.1 s and pause` help?

**Comment by nissansz** [comment]
I need a single click to jump.
Also, I found it is easy to use aegisub for jump by arrow, the screen jumps exactly, and then use a hotkey to play video line, it seems accurate
