### ISSUE TITLE
whisper audio to text time remaining

### ISSUE THREAD

**Issue by omodia** [SubtitleEdit/subtitleedit#6569]
### Time remaining

- Keeps on increasing instead of decreasing.
- It also has a minus symbol before the numbers.
- It started from -0 and kept on increasing.

![1](https://user-images.githubusercontent.com/116664905/210163903-ea4aea75-94da-4acb-ab2e-0e593d453b74.png)

**Comment by niksedk** [comment]
Are you using the latest beta?
If not, try it and let me know if it's fixed: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Could you attach the wave file?

**Comment by niksedk** [comment]
Hm, could you try to re-download SE beta + models: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

Latest beta works okay for me... the last Japanese text is somehow not recognized, but you can select that text in the waveform, press enter, and select the line in the list view, right-click and choose selected lines, audio, audio-to-text...

**Comment by niksedk** [comment]
The accuracy is a know (and annoying) issue for Whisper.

SE can only report progress if Whisper is reporting back, so nothing I can do here.
