### ISSUE TITLE
Whisper models

### ISSUE THREAD

**Issue by omodia** [SubtitleEdit/subtitleedit#6571]
Can you update the whisper models, as a new model was introduced and [updated models are smaller in size](https://github.com/openai/whisper/blob/main/model-card.md).

**Comment by niksedk** [comment]
Sorry, that is not correct as far as I can see - https://github.com/openai/whisper/blob/main/whisper/__init__.py

**Comment by niksedk** [comment]
Ah, you mean this?

![image](https://user-images.githubusercontent.com/1261331/219935324-e2beed63-09fd-4f4d-9d69-8171e87f807c.png)

I think the `39 M` for the tiny model is 39.000.000 parameters: https://towardsdatascience.com/neural-networks-parameters-hyperparameters-and-optimization-strategies-3f0842fac0a5
