### ISSUE TITLE
Installer - Add custom messages strings in "custom strings.iss" file

### ISSUE THREAD

**Issue by bovirus** [SubtitleEdit/subtitleedit#6572]
@niksedk 

In installer script there is this section

; Include the installer's custom messages
#include "Custom_Messages.iss"

[Messages]
;BeveledLabel=Subtitle Edit {#app_ver} by Nikse
SetupAppTitle=Setup - Subtitle Edit
SetupWindowTitle=Setup - Subtitle Edit {#app_ver}

;it.BeveledLabel=Subtitle Edit {#app_ver} di Nikse
it.SetupAppTitle=Installazione di Subtitle Edit
it.SetupWindowTitle=Installazione di Subtitle Edit {#app_ver}

Why don't move strings available in [Messages] section in "Custom_Messages.iss" file?

Now is availsble only in english and italian.
In this way any other translators can customize it.

**Comment by niksedk** [comment]
OK, how is this? 
https://github.com/SubtitleEdit/subtitleedit/blob/main/installer/Subtitle_Edit_Localization.iss

**Comment by bovirus** [comment]
@niksedk 

It's OK. Thanks.
