### ISSUE TITLE
CSV files which include commas in the dialogue are not parsed/opened correctly

### ISSUE THREAD

**Issue by Instinct64** [SubtitleEdit/subtitleedit#6575]
When opening CSV files, or converting CSV files to .ssa using Batch Convert, any lines containing a comma "," in the dialogue are omitted from the conversion, and/or not displayed in SubtitleEdit when the file is opened.

Attached an example file for your review:
[Subtitle-With-Comma.csv](https://github.com/SubtitleEdit/subtitleedit/files/10346166/Subtitle-With-Comma.csv)

![image](https://user-images.githubusercontent.com/7610500/210614025-783a98df-d786-40fe-aad2-4c6a31a14cc7.png)
![image](https://user-images.githubusercontent.com/7610500/210614842-16cb6118-0bf1-4e22-a5e8-a2c6c4738749.png)
Notice the first line in the file is missing in the Editor.

Version tested: 3.6.10

**Comment by niksedk** [comment]
Thx for the info - a very well written issue too :)

Is this beta better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip ?
(I've only looked at format "CSV Nuendo"...)

**Comment by Instinct64** [comment]
Thanks niksedk, this is only partially solved in the beta. Lines with a "," are converted/imported now, but the lines which contain them have quotes added to them.

**Expected:**
Cara Violet,

**Observed:**
"Cara Violet,"

**Comment by niksedk** [comment]
Hm, that works fine here... could you attach a sample file?

**Comment by Instinct64** [comment]
Ok - so it's a little bit obscure. If you use "Multiple replace" in batch to swap in commas, it causes strange behaviour in the batch convert.

[Subtitle-With-Comma.csv](https://github.com/SubtitleEdit/subtitleedit/files/10478909/Subtitle-With-Comma.csv)
![image](https://user-images.githubusercontent.com/7610500/214021149-370f5b47-adaa-4b9a-bb97-27f08a30add2.png)

Was using this as a workaround on the previous version so we could import and convert CSV files from translation company back to .ssa for use.

**Comment by niksedk** [comment]
Your attached CSV file is not recognized by SE as "CSV nuendo"... due to quotes being somewhat different.
Latest SE now accepts a somewhat looser quote style: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

Better?
