### ISSUE TITLE
[Feature Request] Automatic creation of dialogue

### ISSUE THREAD

**Issue by p1nkyy** [SubtitleEdit/subtitleedit#6579]
Hello, can I kindly request a feature that can automatically make dialogues if there are 2 lines of sentences in one line of subtitle? So it automatically adds dashes in front of each sentences? Thanks before.

E.g:
```
93
00:04:43,349 --> 00:04:44,522
How are you?
I'm good, thank you
```

could automatically becomes:
```
93
00:04:43,349 --> 00:04:44,522
- How are you?
- I'm good, thank you
```

**Comment by niksedk** [comment]
Hi @p1nkyy: You can setup a shortcut for this in Option - Settings - Shorcuts:
![image](https://user-images.githubusercontent.com/1261331/211153711-652d0d1c-f569-4180-87fb-3d1ce606bcd5.png)

**Comment by p1nkyy** [comment]
Thanks so much, sorry I didn't know this!
