### ISSUE TITLE
VTT import vertical positioning

### ISSUE THREAD

**Issue by ksn-systems** [SubtitleEdit/subtitleedit#6583]
Hi

I have found found an odd import behaviour when importing a VTT file. When the line offset is a % and not a number, the following lines:

01:10:18.800 --> 01:10:20.840 align:center line:69% position:66% size:33%
OH, YEAH!
THAT'S RIGHT.

01:10:18.800 --> 01:10:20.840 align:center line:85% position:40% size:25%
[ LAUGHS ]

Produce

![image](https://user-images.githubusercontent.com/60980627/211226952-930cebc5-9a26-4d0e-a2a2-e0db2e5a508d.png)

With the first caption being force to the centre of the screen

![image](https://user-images.githubusercontent.com/60980627/211227023-292421c1-3073-43e2-9e65-c5455655229b.png)

And not the expected ~70% from the top.

If the line values contain more traditional integer line numbers

01:10:18.800 --> 01:10:20.840 align:center line:11 position:66% size:33%
OH, YEAH!
THAT'S RIGHT.

01:10:18.800 --> 01:10:20.840 align:center line:-1 position:40% size:25%
[ LAUGHS ]

You get the expected result.

Interestingly the line element is not actually listed in the official W3.org spec, but Mozilla outlines it.

This is the best tool of its type out there, quite the Swiss army pocket knife of captions.

many thanks

Darren B.

**Comment by niksedk** [comment]
Hi Darren,

SE operates only with nine positions:

````
AN7   AN8   AN8
AN4   AN5   AN6
AN1   AN2   AN3
````
