### ISSUE TITLE
Whisper model doesn't download

### ISSUE THREAD

**Issue by rsmith02ct** [SubtitleEdit/subtitleedit#6584]
I have the latest beta of .10 installed on two machines and downloading the "small" Whisper model fails on both and leaves me with a 0KB file.

**Comment by niksedk** [comment]
What OS are you using? Win7 might not work well with SE - see https://github.com/SubtitleEdit/subtitleedit/issues/6439
You can read about downloading manually here: https://www.nikse.dk/subtitleedit/help#audio_to_text

**Comment by rsmith02ct** [comment]
I am using Windows 10 and Windows 11 respectively. I had been able to download base and medium in the past. 

Thanks for the manual link. The file names are different (GGML) I deleted that prefix and small shows up in Subtitle Edit if downloaded manually.

**Comment by i990049** [comment]
Whisper can't be downloaded in some countries. You can try buzz, and click the files name to export subtitles when buzz showing complete.
https://github.com/chidiwilliams/buzz

If the sentences are too long, try break long line.
https://github.com/SubtitleEdit/subtitleedit/issues/6465

**Comment by niksedk** [comment]
Could you check the `error_log.txt` after trying to download a Whisper model?
`error_log.txt` is located in the SE data folder, press Ctrl+Alt+Shift+D in the SE main window to open this folder.

**Comment by rsmith02ct** [comment]
I couldn't get the shortcut to work but found it manually in /roaming. 
No firewall here beyond Windows. Subtitle Edit is able to check for updates, for example. 

I think these entries might be from that:

Date: 12/23/2022 12:43:52
SE: 3.6.10.61 - Microsoft Windows NT 10.0.19044.0 - 64-bit
Message: DownloadAsync failed

System.Threading.Tasks.TaskCanceledException
Message: A task was canceled.
StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()
-----------------------------------------------------------------------------
Date: 01/02/2023 09:40:53
SE: 3.6.10.174 - Microsoft Windows NT 10.0.19044.0 - 64-bit
Message: DownloadAsync failed

System.Threading.Tasks.TaskCanceledException
Message: A task was canceled.
StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()
-----------------------------------------------------------------------------
Date: 01/02/2023 09:43:15
SE: 3.6.10.174 - Microsoft Windows NT 10.0.19044.0 - 64-bit
Message: DownloadAsync failed

System.Threading.Tasks.TaskCanceledException
Message: A task was canceled.
StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()
-----------------------------------------------------------------------------
Date: 01/08/2023 13:59:03
SE: 3.6.10.207 - Microsoft Windows NT 10.0.19044.0 - 64-bit
Message: DownloadAsync failed

System.Threading.Tasks.TaskCanceledException
Message: A task was canceled.
StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()
-----------------------------------------------------------------------------
Date: 01/08/2023 14:01:23
SE: 3.6.10.207 - Microsoft Windows NT 10.0.19044.0 - 64-bit
Message: DownloadAsync failed

System.Threading.Tasks.TaskCanceledException
Message: A task was canceled.
StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()
-----------------------------------------------------------------------------
Date: 01/09/2023 14:13:56
SE: 3.6.10.207 - Microsoft Windows NT 10.0.19044.0 - 64-bit
Message: DownloadAsync failed

System.Threading.Tasks.TaskCanceledException
Message: A task was canceled.
StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()

Date: 01/12/2023 12:15:33
SE: 3.6.10.207 - Microsoft Windows NT 10.0.19044.0 - 64-bit
Message: DownloadAsync failed

System.Threading.Tasks.TaskCanceledException
Message: A task was canceled.
StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()

**Comment by niksedk** [comment]
Thx for the log info... I think it might be caused by a timeout. 
I've made the timeout a lot higher in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
Better?

**Comment by rsmith02ct** [comment]
This time I hit download first for tiny and then for small and it began
downloading instantly. Before I didn't see any percentage counter even, it
just failed after a minute. I'll test on a second machine but it seems
better!

**Comment by niksedk** [comment]
It's possible the servers a busy or far from you... seems okay fast here from Denmark.

You can also download the models via your browser - you can find links here: https://www.nikse.dk/subtitleedit/help#audio_to_text

**Comment by RichardSharpe95thRifles** [comment]
> Thx for the log info... I think it might be caused by a timeout. I've made the timeout a lot higher in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip Better?

I have the exact same problem as rsmith02ct It seems that your patch solved it. Could you please upload it again? The link is dead :( The vosk on the other hand works fine and download its models with no problem but I like the Whisper better and besides Whisper support more languages and I need to transcript a movie in Danish which Vosk does not support for some reason. Please help.

**Comment by 3aluw** [comment]
> It's possible the servers a busy or far from you... seems okay fast here from Denmark.
> 
> You can also download the models via your browser - you can find links here: https://www.nikse.dk/subtitleedit/help#audio_to_text

(having the same issue).
Do I need to download the model and put it in the models directory ?.
 I did just that but the models doesn't show up.
![Capture](https://github.com/SubtitleEdit/subtitleedit/assets/82264545/3f807dd7-3e6c-4f41-8d18-5c0fa6b07fa2)
![Capture2](https://github.com/SubtitleEdit/subtitleedit/assets/82264545/3f2f6f29-db56-4f3a-b9cf-969132af6b5a)

**Comment by niksedk** [comment]
Latest beta is here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by kirinomamori** [comment]
Is there a direct download for the models? I'm trying to DL the large model, 2.88 GB even using the latest beta but it still cuts off.

**Comment by RazyRo** [comment]
go to the URL: https://www.nikse.dk/subtitleedit/help#audio_to_text
Find the Manual Model, use the search function to locate the "Manual Model" section. Here, you'll find various models available for download. Choose the one that suits your needs.
Download the Model
Open SubtitleEdit
press the following keyboard shortcut: Ctrl + Alt + Shift + D. This will open the SubtitleEdit data folder.
Add the Model File: Locate the "Model" folder within the data folder. Paste the model file you downloaded into this "Model" folder.
Rename the Model File: After pasting the file, make sure to change its file name ending. For example, if the downloaded file has the name "base.en.bin," ensure that it's named exactly as required by the application.

**Comment by john-kacino** [comment]
I have the same issue of downloading the files in the portable program. My network is not good enough.

The manual download guide mentioned above confuses me. 

I get the archive of Purfview's Faster-Whisper-XXL r245.4 on the github release page and extract everything in the archive to \SubtitleEdit\Whisper\Purfview-Whisper-Faster\_models, but the program keeps asking me to download the model.

What should I do? Should I ignore it?

**Comment by GrampaWildWilly** [comment]
This seems like a rather old thread, so if you're using an older version of SE, maybe what I'm about to suggest does not apply.  In SE 5, @niksedk changed the naming convention.  My Purfview Faster Whisper resides in `C:\Subtitle Edit V5\SpeechtoText`.  You can guess from the base directory that I am running portable SE.  The key idea is that the speech to text engines & models are all inside this new SE subdirectory named `SpeechtoText` in a tree of some structure.  I haven't used the other tools but I imagine you'd get a subdirectory named `TexttoSpeech` for the complementary feature.   But this is in SE 5.  I can't help you with old versions of SE.

**Comment by john-kacino** [comment]
Thanks for your reply, @GrampaWildWilly. Yes, you are right. The guide is ok for version 4, but it is outdated for version 5.
