### ISSUE TITLE
WebVTT romoving web styles

### ISSUE THREAD

**Issue by maknol** [SubtitleEdit/subtitleedit#6585]
Hi,
is it possible when saving WebVTT to srt, this web styles code to be clear and in the same time, italic code to become clear SRT italic?
Example:
```
 10
00:01:45,720 --> 00:01:47,720
<c.background-color_transparent.font-family_proportionalSansSerif.font-style_normal.font-weight_normal.text-shadow_black-4%>[exhales]

11
00:01:52,200 --> 00:01:54,320
<c.background-color_transparent.font-family_proportionalSansSerif.font-style_normal.font-weight_normal.text-shadow_black-4%>[Eddie] A word of advice.
Whatever you do…

61
00:05:25,880 --> 00:05:27,480
<c.background-color_transparent.font-family_proportionalSansSerif.font-style_normal.font-weight_normal.text-shadow_black-4%>[Vincent]<c.font-style_italic>Why would he make
such a claim?
```

Sometimes, the italic code, and other looks like this:

```
11
00:01:52,200 --> 00:01:54,320
<c.background-color_transparent.font-family_proportionalSansSerif.font-style_normal.font-weight_normal.text-shadow_black-4%>[Eddie] A word of advice.
Whatever you do…</c>

61
00:05:25,880 --> 00:05:27,480
<c.background-color_transparent.font-family_proportionalSansSerif.font-style_normal.font-weight_normal.text-shadow_black-4%>[Vincent]<c.font-style_italic>Why would he make
such a claim?</c></c>
```

**Comment by niksedk** [comment]
Could you attach the complete subtitle file?

**Comment by maknol** [comment]
Hi,  I send you more than one, because all have different codes for styling. I remove it manually, but will in help for others if there is a function for that.  
  Thank you!
 






 >-------- Оригинално писмо --------

 >От: Nikolaj Olsson ***@***.***

 >Относно: Re: [SubtitleEdit/subtitleedit] WebVTT romoving web styles (Issue
 #6585)

 >До: SubtitleEdit/subtitleedit  

 >Изпратено на: 11.01.2023 16:51



 
 
  
  
  
Could you attach the complete subtitle file?

**Comment by niksedk** [comment]
Sorry, files cannot be transferred from email to github - please attach files here on Github or send the files to my email, thx.

**Comment by maknol** [comment]
Resended on your email.








 >-------- Оригинално писмо --------

 >От: Nikolaj Olsson ***@***.***

 >Относно: Re: [SubtitleEdit/subtitleedit] WebVTT romoving web styles (Issue
 #6585)

 >До: SubtitleEdit/subtitleedit  

 >Изпратено на: 11.01.2023 16:51



 
 
  
  
  
Could you attach the complete subtitle file?

**Comment by niksedk** [comment]
OK, how does this beta version work for you when converting webvtt to srt ?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by maknol** [comment]
Now seems OK.

**Comment by niksedk** [comment]
Cool, thx for reporting and testing :)
