### ISSUE TITLE
Synchronize multiple subtitles at ones

### ISSUE THREAD

**Issue by maknol** [SubtitleEdit/subtitleedit#6586]
In a Bach convert is missing option for Synchronize, it it possible to be added? (When is need for Point sync)

**Comment by i990049** [comment]
There is batch synchronize mode, use the latest SE version and add the videos or audios files to SE.
If SE fails to do it, try buzz and click the files name to export subtitles when buzz showing complete.
https://github.com/chidiwilliams/buzz

If the sentences are too long, try break long line.
https://github.com/SubtitleEdit/subtitleedit/issues/6465
