### ISSUE TITLE
Subtitle Edit - VOBSUB and OCR results in random characters

### ISSUE THREAD

**Issue by mnoah66** [SubtitleEdit/subtitleedit#6587]
Using the latest beta version of SE.  My MKV file has a VOBSUB that Tesseract OCR is not working on.  Subtitles seem fine on the player and in the OCR screen.

![image](https://user-images.githubusercontent.com/24765755/211590026-3d3ba564-07c1-4d6e-97b1-38feaacd3546.png)

I saw a similar issue that was closed a few weeks ago with the beta version.

**Comment by niksedk** [comment]
You can experiment a bit with the colors... try not using custom colors, and if you're using custom colors, try to go for black text with no outline. See more here: https://github.com/tesseract-ocr/tesseract/issues/2048

Also, perhaps latest beta work a bit better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

Also, if you attach the subtitle file (you can export by right-clicking in the list view).

**Comment by mnoah66** [comment]
> try not using custom colors

Ah, that did it!  Works a treat now.  Thank you.

**Comment by niksedk** [comment]
> > try not using custom colors
> 
> Ah, that did it! Works a treat now. Thank you.

cool :)
