### ISSUE TITLE
VTT exports limited to 99 hours

### ISSUE THREAD

**Issue by User-3090** [SubtitleEdit/subtitleedit#6590]
Anything above 99 hours ends up broken with 00:00.000 --> 00:00.000 timestamps. My understanding is that VTT allows more than 2 digits for the hour field.

**Comment by niksedk** [comment]
Yes, WebVTT allow for 2+ digits for hours, like 99999999999999999999999999999 hours... 

SE only support 2 digits for hours. Is that a problem for you?

**Comment by hdosys** [comment]
This is a problem for me because I regularly produce educational or conference content exceeding 100h of recorded material in a single file. It would be helpful if SE could support that.
