### ISSUE TITLE
[Feature request] Transcription options in export plain text

### ISSUE THREAD

**Issue by zcraber** [SubtitleEdit/subtitleedit#6592]
Some transcription features I'd like to see in the `Export text` window:

1. Option to include timecode inside square brackets.
2. Checkbox to include/exclude `End time`.
3. Checkbox to include `Actor` name before the subtitle separated with a colon.

![image](https://user-images.githubusercontent.com/61133303/212174622-93a274f3-d350-442c-8eb6-be41e250c99f.png)

**Comment by niksedk** [comment]
Try File - Export - Custom format:

![image](https://user-images.githubusercontent.com/1261331/212185409-09413ab9-56ab-479e-b8db-22758e4d4fc6.png)

**Comment by zcraber** [comment]
> Try File - Export - Custom format:

Wow, this has all the features I needed! There is a minor improvement required regarding the 3rd feature I requested. If the `Actor` is mentioned in Malayalam language, it's not getting recognized using `{actor}` and uses the placeholder name in custom text format.

![image](https://user-images.githubusercontent.com/61133303/212253062-426d802a-48fc-4678-9105-b3959a2fb73d.png)
