### ISSUE TITLE
[Feature Request] Binary Image comparison in CLI batch convert

### ISSUE THREAD

**Issue by jlw4049** [SubtitleEdit/subtitleedit#6593]
Specifically i'm looking for a way to extract proper timestamps for a pgs file to properly sync my existing SRTs. So maybe the binary image comparison isn't exactly what I need.

**Comment by jlw4049** [comment]
nOCR is very fast it seems too

**Comment by niksedk** [comment]
I think you can use the `/ocrengine:nocr` parameter in the CLI

**Comment by jlw4049** [comment]
Thank you very much. This sill definitely do the trick.
