### ISSUE TITLE
Suggestion for "Audio to text" with Whisper

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6597]
I tested "Audio to text" with Whisper on Subtitle Edit 3.6.10 NEXT beta 219 with the "medium.en" model on "https://youtu.be/4qdvjslwvIU" (with a check mark at "Use post-processing", with a check mark at "Auto adjust timings", with Choose language = English). The results are textually impressive, except for one thing. The word "I" is always correctly in uppercase, but the word "US" is always also in uppercase -- but this is usually incorrect. The word "US" should be in uppercase when it's a short version of "USA" -- but when it's an "all or nothing" choice, I would suggest to always have the word "us" in lowercase.

**Comment by niksedk** [comment]
Could you attach the output?

**Comment by oep42** [comment]
Attached is the untouched output.
[Untouched output.zip](https://github.com/SubtitleEdit/subtitleedit/files/10421455/Untouched.output.zip)

**Comment by niksedk** [comment]
Thx - hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by oep42** [comment]
Thanks a lot. Everything is fixed, and more. All changes are improvements (more than I asked for; I earlier only talked about the most obvious/solvable issues). I'm impressed that the program now differentiates correctly between "us" and "US".
