### ISSUE TITLE
Save as... (video file name)

### ISSUE THREAD

**Issue by maknol** [SubtitleEdit/subtitleedit#6599]
In 3.6.10 NEXT Beta 234 this option not working.

**Comment by niksedk** [comment]
Works fine here... could you send a few screenshots/explain a bit more?

**Comment by niksedk** [comment]
Hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

**Comment by maknol** [comment]
In Beta 273 -  fixed! Thank you! Great job!

**Comment by RedSoxFan04** [comment]
I'm experiencing this problem in version 4.0.2.
