### ISSUE TITLE
CTRL+F in the OCR window

### ISSUE THREAD

**Issue by dokax** [SubtitleEdit/subtitleedit#6602]
For example, the subtitles from line 1 to line 3 are all "abc".
Now mouse click on line 1, and then CTRL+F to search for "abc", it will jump to line 3 instead of line 2.

**Comment by niksedk** [comment]
thx for the info :)
Find/find-next in OCR window should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
