### ISSUE TITLE
Suggestion for "Audio to text" post-processing options

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6604]
![increase length of resulting segments](https://user-images.githubusercontent.com/84353335/213189680-6b6683de-1e3d-45aa-a0bf-ba8c9a86757a.png)
I assume that the subtitle segments that result from "Audio to text", resemble the black lines in the image. In the image, the segments have been lengthened at the beginning (red line), and at the end (green line).

Is it possible to add options for the optional lengthening of all the resulting subtitle segments at the beginning and at the end? If so, I would suggest to do so.

[Option 1:] The red line is an example of the result of an option to lengthen all segments at the beginning (in milliseconds).

[Option 2:] The green line is an example of the result of an option to lengthen all segments at the end (in milliseconds).

[Option 3:] A third option is for the minimum distance (in milliseconds) between the end of a (lengthened) segment and the beginning of the next (lengthened) segment. This third option may overrule the other two options to prevent a collision.

**Comment by niksedk** [comment]
Sorry, Whisper timestamps are sometimes like 10 seconds off, which makes this somewhat hard. The large model is often better though.

SE already tries to match timestamps better when we have silence before/after some text... Seems to work well.
