### ISSUE TITLE
Error when trying to generate subtitles with OpenAI Whisper

### ISSUE THREAD

**Issue by drunk-0ctopus** [SubtitleEdit/subtitleedit#6607]
I've seen a few closed issues with this exact same error, but nothing I do seems to fix it. 
![error](https://user-images.githubusercontent.com/49104443/213622250-7eec069d-3761-4f4d-aa89-0cd28dd6ede0.png)

I'm on Windows 11

Things I've tried:
- Installing OpenAI Whisper, following the instructions on their github.
  - This involved having to install python, ffmpeg, torch, etc in the proper way until I could run the whisper command from PowerShell. I was able to generate an SRT file from an MP3 using the CLI.
- Updating to the Beta of SE
  - As well as running SE as an admin, just in case
- Trying different kinds of files

I am wanting to use OpenAI so that it can utilize my CUDA GPU, as the CPU variant with CPP is horrendously slow (over 7 minutes to transcribe a minute long video).

**Comment by niksedk** [comment]
Could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip
Where is your `whisper.exe` file located?

**Comment by drunk-0ctopus** [comment]
> Could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip Where is your `whisper.exe` file located?

I installed the beta around 11:45pm last night, so I'm not sure if it's changed since then.
I don't have a `whisper.exe` file as far as I'm aware? I can run Whisper via python in Powershell. So I have a `whisper.py` in my Python scripts folder.

I will say that I seemed to get it to somewhat work after I posted this. It involved uninstalling all python versions, reinstalling Python 3.10.9 (as 3.11 does not work with torch), then reinstalling OpenAI-Whisper and Torch. I confirmed I could still run the whisper command, and have it use CUDA - It took about 15 seconds or so to transcribe the 30s test clip I've been using. 
After that when I run Whisper via SE (after changing `<WhisperChoice>` to "openai" instead of "CPP") it will start to transcribe and no longer throws the error as above. However I notice that it doesn't seem to use my GPU (As the CLI Whisper does), and it takes several minutes to transcribe 30s of audio using the medium model. 
I can open a new issue for this if needed as the error is not currently popping up as it was.

**Comment by niksedk** [comment]
SE just calls the whisper.exe via cmd line... there really should not be any difference.
You can press F2 to see the actual call, or check the file "error_log.txt" where everything is logged to...

**Comment by drunk-0ctopus** [comment]
I appreciate the information, I wasn't aware about F2 or right-clicking. 

I can see that SE is calling whisper via Python but for some reason it takes a very long time to get past the initial command and actually start transcribing. When I run the command on my own via command line it takes only a couple minutes for the actual transcription to start. In SE even after 5 minutes it has not begun to transcribe. Like I said I can start a new thread for this if needed - I'm not really sure why SE would be any slower than just a command line. 

(Fwiw it is now using my GPU, so that's solved. It wasn't last night for some reason)

**Comment by franzau** [comment]
Thank you so much, Nikse and drunk-Octopus... I had the same issue and can now get Whisper to launch. 
I'm running the last beta under Ubuntu 22.04 on an late 2012 Macbook with 16Gb.
I'm try to subtitle 2 minutes video spoken in Danish using the "small" model (if it works I will try the large one).
My computer works for about 20 minutes and then freezes after writing "few seconds left".
When I cancel the process, I get an error message stating that i might have a problem with "libmpv" or "libvlc".
I have vlc installed (actually, two instances).
I am also new to linux.
Thank you in advance for your help


Below is my log file before things get wrong
franzubumac@franzubumac-MacBookPro:~$ mono /home/franzubumac/SubtitleEditBeta/SubtitleEdit.exe
[00007fb9ec005760] gl gl: Initialized libplacebo v4.192.1 (API v192)
libva info: VA-API version 1.14.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[00007fb9ec005760] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
[00007fba14068610] avcodec decoder: Using Intel i965 driver for Intel(R) Ivybridge Mobile - 2.4.1 for hardware decoding
[h264 @ 0x7fba1410dac0] get_buffer() failed
[h264 @ 0x7fba1410dac0] thread_get_buffer() failed
[h264 @ 0x7fba1410dac0] decode_slice_header error
[h264 @ 0x7fba1410dac0] no frame!
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/franzubumac/Downloads/Kajakenergi-Gruppeopmaerksomhed-Intro-4K-general.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Kajakenergi - Gruppeopmærksomhed - Intro
    artist          : Tue Olesen
    encoder         : Lavf58.20.100
    keywords        : Main
  Duration: 00:02:09.64, start: 0.000000, bitrate: 784 kb/s
  Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 652 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to '/tmp/2f0d10f6-f899-4763-abaa-4dfb8f3d8d37.wav':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    INAM            : Kajakenergi - Gruppeopmærksomhed - Intro
    IART            : Tue Olesen
    keywords        : Main
    ISFT            : Lavf58.76.100
  Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc58.134.100 pcm_s16le
size=    4052kB time=00:02:09.65 bitrate= 256.0kbits/s speed= 448x    
video:0kB audio:4052kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.003567%

**Comment by franzau** [comment]
For some reason, this time new subtitles did appear.
The text is not bad indeed for being the small model.
The timing is wrong (maybe because I had set timeframe to 25 instead of 23,9?). I can fix it "manually".
But I am still getting some error messages... it is a continuation of the previous log.
I don't want to waste your time, but... is it ok that I get "pulse audio output error: overflow, flushing"?

[00007fb9fc007820] gl gl: Initialized libplacebo v4.192.1 (API v192)
libva info: VA-API version 1.14.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[00007fb9fc007820] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
[00007fba2c054040] avcodec decoder: Using Intel i965 driver for Intel(R) Ivybridge Mobile - 2.4.1 for hardware decoding
[0000564e33cd5e90] pulse audio output error: overflow, flushing
[0000564e33cd5e90] pulse audio output error: overflow, flushing
[0000564e33cd5e90] pulse audio output error: overflow, flushing
[0000564e33cd5e90] pulse audio output error: overflow, flushing
[0000564e33cd5e90] pulse audio output error: overflow, flushing
[0000564e33cd5e90] pulse audio output error: overflow, flushing
[0000564e33cd5e90] pulse audio output error: overflow, flushing

**Comment by niksedk** [comment]
I don't know about the `pulse audio output error: overflow, flushing` but I recommend switching to mpv.

>The text is not bad indeed for being the small model.

OK, I could only get the `large` model to give anything close to the actual words with Danish. Longer videos sometimes freezes.
English works well even with the tiny model (but still better with the `large`  model).

>The timing is wrong (maybe because I had set timeframe to 25 instead of 23,9?). I can fix it "manually".

Whisper is not super good with timing. Again, the `large`  model is a little better, but the subtitle might need a little timing cleanup after Whisper.

**Comment by franzau** [comment]
Tak, Nikse! I switch now to Mpv, accept to do some manual cleaning and give a chance to the large model and maybe to the batch processor.
The result with these two was really impressive... I had not made subtitles in >10 years... Your "Subtitle Edit" was already great then, but now it is incredible!  🙏  tusind tak😀

**Comment by franzau** [comment]
Tak, Nikse! I switch now to Mpv, accept to do some manual cleaning and give a chance to the large model and maybe to the batch processor.
The result with these two was really impressive... I had not made subtitles in 10 years... Your "Subtitle Edit" was already great, but now it is incredible!  🙏
