### ISSUE TITLE
Old logo

### ISSUE THREAD

**Issue by q1k** [SubtitleEdit/subtitleedit#6608]
Can you return the old logo?
Maybe add an option to revert to the old logo. I much prefer that one.

**Comment by niksedk** [comment]
To change an application icon:

* Right-click the application, and select Properties from the pop-up menu.  
* On the General tab, click the Browse button next to Icon Path.
* Select the desired icon, or browse to another location to select the icon. After you've selected the icon, click Open. Click OK to apply.

**Comment by q1k** [comment]
That change icon option is only for the shortcut and nothing else. The ugly logo still appears everywhere else.

**Comment by niksedk** [comment]
Sorry, it's not really possible to switch icon dynamically (as far as I know), but you can compile your own version with Visual Studio community edition: https://visualstudio.microsoft.com/vs/community/

**Comment by q1k** [comment]
Well, winrar can change logo everywhere it is used by changing the theme. So it should be possible. If you find a way to do it, please re-add the old logo. Thanks
