### ISSUE TITLE
Output Audio Device Option

### ISSUE THREAD

**Issue by Shae-Clark** [SubtitleEdit/subtitleedit#6610]
Is there not an option to select which device I want the audio to play from when I'm editing?
Most of the time I like to edit with my Bluetooth headphones in, so I'll connect them which sets them as my main audio output for my computer but 8 out of 10 times the subtitle edit program will still play the audio through my speakers & not switch to my headphones.

**Comment by niksedk** [comment]
For me that's a windows setting...
