### ISSUE TITLE
Expected empty line but found number + time code

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#6612]
When I open the following file:
[we speak dance1.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/10479289/we.speak.dance1.srt.txt)
It opens properly. When I insert a Unicode RTL mark at the start of every subtitle, save and then try to open this new file:
[we speak dance2.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/10479308/we.speak.dance2.srt.txt)
What I get is this:
![se-expected empty line](https://user-images.githubusercontent.com/19672444/214032613-4f3f506c-8be4-407d-ae69-a881c1a0cb57.png)

Now, I understand what happened, because I did it myself, but I think the wording of the error message is confusing. That's one thing. The other thing is that it says that "number skipped" is 5 and 6, whereas the actual subtitles are 4 and 5 (presumably it's starting to count at zero).

**Comment by niksedk** [comment]
Is this better? `Line 19: Expected empty line, but found number followed by time code (subtitle number "5")`  ?

Or do you have  a suggestion?
