### ISSUE TITLE
DeepL auto-translate broken

### ISSUE THREAD

**Issue by Udoachim** [SubtitleEdit/subtitleedit#6616]
When trying to use the DeepL auto-translate feature I get errors 400 or 403 after clicking on "Translate".
This occured with the language pair Finnish-English. I believe there may have been some recent API changes by DeepL.

![Screenshot 2023-01-26 094155](https://user-images.githubusercontent.com/45949725/214781965-86ba53d0-e014-4b44-8009-7336ec3a3d8c.png)

**Comment by niksedk** [comment]
Are you using an old plug-in? See "File - Plugins" for updates.

**Comment by Udoachim** [comment]
Such an easy fix. Everything works as expected again. Thank you very much!
