### ISSUE TITLE
[Feature Request] Italic Option to Apply Separately To Each Line

### ISSUE THREAD

**Issue by Cankalay** [SubtitleEdit/subtitleedit#6618]
The subtitles I prepare require each line to be made italic separately, instead of one inclusive format.

Ex: 
i>They're full of minerals,</i
i>but they're really hard.</i

Instead of:
i>They're full of minerals,
but they're really hard.</i

It would be great if such feature could be added to options.

**Comment by Cankalay** [comment]
I just edited the italic formatting so you can see what I mean.

**Comment by niksedk** [comment]
@Cankalay: OK, how does the plugin "Italic each line" work for you?
See File - Plugins

**Comment by Cankalay** [comment]
@niksedk Thank you Nikolaj! Works great.
