### ISSUE TITLE
Set start and offset the rest not working as expected

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#6620]
SE 3.6.10 Portable, Win10 64-bits, Latest Updates.

I stand ON (so it's Blue) Line 1, and change the starttime to 05,00 (from 06,329) and then Hit 'Set start and offset the rest'.

"1
00:00:06,329 --> 00:00:08,129
In the nation's largest city,

2
00:00:08,134 --> 00:00:10,965
the vicious and violent
members of the underworld

3
00:00:10,970 --> 00:00:12,592
are hunted by the detectives

4
00:00:12,597 --> 00:00:15,603
of the Organized Crime Control Bureau.

5
00:00:15,608 --> 00:00:17,611
These are their stories.

6
00:00:30,198 --> 00:00:31,616
Hey.

7
00:00:36,120 --> 00:00:37,825
Sorry I'm late.

8
00:00:37,830 --> 00:00:39,207
They're running behind.

9
00:00:43,961 --> 00:00:46,793
You good?

10
00:00:46,798 --> 00:00:48,561
I honestly didn't realize how much"

And then this happens:

"1
00:00:00,000 --> 00:00:01,800
In the nation's largest city,

2
00:00:03,134 --> 00:00:05,965
the vicious and violent
members of the underworld

3
00:00:05,970 --> 00:00:07,592
are hunted by the detectives

4
00:00:07,597 --> 00:00:10,603
of the Organized Crime Control Bureau.

5
00:00:10,608 --> 00:00:12,611
These are their stories.

6
00:00:25,198 --> 00:00:26,616
Hey.

7
00:00:31,120 --> 00:00:32,825
Sorry I'm late.

8
00:00:32,830 --> 00:00:34,207
They're running behind.

9
00:00:38,961 --> 00:00:41,793
You good?

10
00:00:41,798 --> 00:00:43,561
I honestly didn't realize how much"

How can Line 1 suddenly be at 00:00:00,000 ?
And line 2 has changed from 08,134 to 03,134, that's suddenly 5 seconds earlier instead of 01,329 seconds earlier, and so on with the rest of the lines.

The way it used to work the few times I used the function 'Set start and offset the rest', was that it changed all line after the changed line with as much time as the first line was changed with.

So all the remaining lines should start 1,329 seconds later as well as Line 1 did before I clicked 'Set start and offset the rest'.

I can't understand what's wrong?

[law.and.order.organized.crime.s03e12.720p.web.h264-cakes.en.zip](https://github.com/SubtitleEdit/subtitleedit/files/10526878/law.and.order.organized.crime.s03e12.720p.web.h264-cakes.en.zip)

**Comment by niksedk** [comment]
`Set start and offset the rest` works relative to the current video position.

**Comment by Minherre** [comment]
But in this case there was no video loaded, and I'm sure this has worked earlier, also then without video loaded.

Don't tell me one HAS to have the video loaded as well suddenly, if so that must have changed lately ?!

Of course one should be able to adjust a Sub without having the Video for it!

**Comment by niksedk** [comment]
Try Sync - Adjust all times

**Comment by Minherre** [comment]
Ok, thanx, I'll try that later when I'm back in front of my Pc.

====

Where does SE save or keep the Waveform from 'Click to add waveform' ?

**Comment by niksedk** [comment]
Waveforms are kept in the `Waveforms` folder in the `SE Data folder` (press ctrl+alt+shift+D in the SE main window to open the `SE Data folder`)
