### ISSUE TITLE
[Feature Request] Option For "Auto-Split" to Add "..." to Ending and Beginning

### ISSUE THREAD

**Issue by Cankalay** [SubtitleEdit/subtitleedit#6622]
The subtitle format I work for requires "..." used at the end and beginning of split sentences. It would be really time saving if I can opt for automatically adding those when I use split.

Ex:
"This is a very long sentence needing of a split to make a good example."
[Hits "split"]

"This is a very long
sentence needing..."

"...of a split to make
a good example."

**Comment by niksedk** [comment]
Try to setup a `continuation style`:

![image](https://user-images.githubusercontent.com/1261331/215284395-b61c7a71-2c1e-4fb4-a397-9bd80aa68807.png)

**Comment by Cankalay** [comment]
Thank you!
