### ISSUE TITLE
2560*1440 monitor, set scale 125%, the software will be blurred.

### ISSUE THREAD

**Issue by alvvaysu** [SubtitleEdit/subtitleedit#6624]
On the screen of **2560*1440**, the desktop settings are scaled by 125%, and the software will be blurred when opened. I hope to adapt it accordingly.

I also tried 124% scaling, but many softwares (including SE) will display missing text, which may not be a good scaling.

Under **125%** scaling, the compatibility setting is high dpi (select the third option at the bottom.). Although it is clear overall, but my favorite font in "subtitle preview font" becomes inexplicably large.

**Comment by niksedk** [comment]
Sorry, I've no idea how to fix this...

**Comment by shanedk** [comment]
I have a 3840x2160 screen scaled 175%, and I'm not seeing this. Are you talking about the text box, or the video player? If the player, it might be something in your player settings.

**Comment by insurw** [comment]
If you use "Custom scaling" (System>Display>Custom scaling) instead of the dropdown menu (but use same scale settings), no software/settings will be blurred.
