### ISSUE TITLE
Enhance the display box of "subtitle preview font"

### ISSUE THREAD

**Issue by alvvaysu** [SubtitleEdit/subtitleedit#6625]
1. **The display box of "subtitle preview font"** only displays two lines by default, but there are many 3-line characters or more in the timeline. I hope to _**increase the display space**_, or _**have an adaptive line number function**_. Or _**set the maximum number of displayed lines, and then preview adaptively according to the font size**_.

2. Switch the timeline up and down, the position of the **insertion point** is at the last position, just like other text editing software (such as notepad++).

3. **The display box of "subtitle preview font"** displays the **insertion point.**

**Comment by niksedk** [comment]
1) use mpv.

2) a screenshot?

3) ?
