### ISSUE TITLE
Capitalize SDH Titles

### ISSUE THREAD

**Issue by seanmcnally98** [SubtitleEdit/subtitleedit#6626]
This would be great if it were a built-in feature, since the "Remove SDH" option works so well.  Basically, if I'm taking an ALL CAPS subtitle and making it Sentence Case, I want all my SDH titles to be capitalized.  Unfortunately, not even Multiple Replace can achieve this, since /U in regex seems to be broken.

**Comment by niksedk** [comment]
I think someone made a plugin for that:

![image](https://user-images.githubusercontent.com/1261331/215335294-031754d3-1486-4179-9ddd-746757177349.png)
