### ISSUE TITLE
[Releases 3.6.11] Batch convert tool broken

### ISSUE THREAD

**Issue by chensimmons** [SubtitleEdit/subtitleedit#6635]
Translated by Google Translate:
I don't know how to speak English. So it is impossible to accurately describe the problem.
The batch convert tool for version 3.6.11 is broken, while 3.6.10 is fine

**Version 3.6.11**

<img width="773" alt="上传2" src="https://user-images.githubusercontent.com/31755429/215741340-3303b368-99e5-44b5-960c-4681af47479a.png">

**Version 3.6.11**

**Version 3.6.10**

<img width="778" alt="上传1" src="https://user-images.githubusercontent.com/31755429/215741695-3792021c-2a21-434e-9d62-925bb0a5d90f.png">

**Version 3.6.10**

**Comment by niksedk** [comment]
@chensimmons: thx for the info, could you attach some of the subtitles that fails?
(the .ass files I have do not cause a crash)

**Comment by chensimmons** [comment]
> @chensimmons: thx for the info, could you attach some of the subtitles that fails? (the .ass files I have do not cause a crash)

[sub.zip](https://github.com/SubtitleEdit/subtitleedit/files/10553964/sub.zip)

OR
https://drive.google.com/file/d/1wUUZLJoOrREURLkey4tXdt6Qhd5LLW1U/view?usp=sharing

**Comment by niksedk** [comment]
Thx for the files :)

Could you try latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

I'm not really sure what the exact problem is (something with file locking), but hopefully it works now :)

**Comment by chensimmons** [comment]
@niksedk 

Thank you very much






> Thx for the files :)
> 
> Could you try latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip
> 
> I'm not really sure what the exact problem is (something with file locking), but hopefully it works now :)

**Translated by Google Translate:
If overwrite files is not checked, the latest beta version works fine, as does 3.6.11.**

<img width="778" alt="不勾选" src="https://user-images.githubusercontent.com/31755429/216262486-50a0b90d-d4d0-422a-a050-1cc9d96c5073.png">




**Translated by Google Translate:
If overwrite files is checked, the files that fail to convert seem to be random.**

**First test(the latest beta)**
<img width="778" alt="第一次测试" src="https://user-images.githubusercontent.com/31755429/216262897-d52b553b-b68f-4580-a409-9220a82bb57d.png">




**Second test(the latest beta)**
<img width="778" alt="第二次测试" src="https://user-images.githubusercontent.com/31755429/216262985-fc3cf1ba-bd59-4af1-9386-88e53b66bd73.png">




**Third test(the latest beta)**
<img width="778" alt="第三次测试" src="https://user-images.githubusercontent.com/31755429/216263091-42bfb6e8-9852-4cdc-84ed-1bb0f16b45f1.png">




**Fourth test(the latest beta)**
<img width="780" alt="第四次测试" src="https://user-images.githubusercontent.com/31755429/216263233-3198496e-8252-40be-a77c-d4bbe4475895.png">

**Comment by niksedk** [comment]
OK, if found the cult-pit, so latest beta should be working as expected: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip
