### ISSUE TITLE
IDX/SUB (VOBSUB) subtitle position

### ISSUE THREAD

**Issue by webmogul1** [SubtitleEdit/subtitleedit#6636]
Is it possible to get the subtitle position from the idx/sub and apply to Advanced Substation Alpha?
It is particularly useful when you have other text behind the subtitle. Like that:
![image](https://user-images.githubusercontent.com/5225701/215939637-15ad0a17-c693-48dd-bfb2-edbcb6cb1136.png)

Subextractor does that but its ocr is too basic.

**Comment by niksedk** [comment]
Dupe of #3801
