### ISSUE TITLE
Feature request, Whisper with OpenBLAS support

### ISSUE THREAD

**Issue by oniongarlic** [SubtitleEdit/subtitleedit#6637]
I'm testing the integrated whisper.cpp support and noticed it is much slower than cli version that I build with OpenBLAS support.
Could that be enabled ?

**Comment by niksedk** [comment]
Could you explain a bit more?

**Comment by oniongarlic** [comment]
Whisper can be built with openblas support, a library with optimized and multi threaded matrix operations. It makes a a lot faster.

**Comment by niksedk** [comment]
Can you explain a lot more? ;)
Links?

**Comment by oniongarlic** [comment]
Whisper.cpp, building with -DGGML_USE_OPENBLAS in Makefile
Unfortunately I'm not familiar with windows build environment, as I use WSL for cli whisper...
The closes issue I could find was https://github.com/ggerganov/whisper.cpp/pull/174

**Comment by darnn** [comment]
There is a Windows build with OpenBLAS on Whisper.cpp's releases page: https://github.com/ggerganov/whisper.cpp/releases/tag/v1.1.1

You can just replace the one SE downloads with this one and it works. Not sure about the speed improvement, but feel free to try yourself.

**Comment by darnn** [comment]
Actually, I got curious: One minute with OpenBLAS: 2:16 minutes. Without: 3:44. I only tried the one time, but seems cool.

**Comment by niksedk** [comment]
For the tiny model the AVX2 build is faster, but for the large model, OpenBLAS is much faster :)

Does anybody know if the OpenBLAS build requries AVX2 or how it works?

**Comment by niksedk** [comment]
Latest beta now uses OpenBLAS: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip
