### ISSUE TITLE
Whisper for SE3611.zip will not be closed.

### ISSUE THREAD

**Issue by msjsc001** [SubtitleEdit/subtitleedit#6638]
Thank you for developing the SE Whisper recognition feature, it has helped me to recognize a lot of subtitles recently, the effect is very good and convenient, and the effect combined with SE's DEEPL translation plugin is comparable to human translation is really great. (I have tested if the use of Google recognition and translation, or Whiper recognition with Google Translate after a lot of content can not be read, Google provides recognition or translation of the significance of very small)

I found some bugs in the new version of Whisper
The SE3611.zip version of Whisper will not be closed after closing the software.

Whisper php (original) is used：
![image](https://user-images.githubusercontent.com/93178788/216076257-5a07c459-a601-48d0-bdf5-b74c449458e6.png)

SE Whisper is still running after closing SE：
![image](https://user-images.githubusercontent.com/93178788/216076298-60354f09-2cda-49ae-9660-d89c266960e2.png)
![image](https://user-images.githubusercontent.com/93178788/216076318-7ede1422-8cc0-402d-a6d2-a47260820d98.png)

Two other bugs.
1, in whisper batch or individual recognition will not show the countdown.

2、After minimizing the Whiper interface in batch mode, the Whiper interface will disappear and cannot be opened again, and then the Whiper can only be closed via Task Manager in SE.

(My system is Win11 22H2)

**Comment by xiaoliddiao** [comment]
你好，请问你使用后字幕的时间线是对的吗？
Whisper (GPU)识别倒是很准确，但是输出的字幕时间总是快几秒或慢几秒。

**Comment by niksedk** [comment]
Sorry, I cannot re-produce this
