### ISSUE TITLE
How to compile in Linux?

### ISSUE THREAD

**Issue by lucas-04** [SubtitleEdit/subtitleedit#6639]
I try but not give success. 

https://github.com/SubtitleEdit/subtitleedit/issues/2510#issue-248616053 
I not try use .bat file on wine 

![image](https://user-images.githubusercontent.com/95548091/216098659-8d36ed6f-fd9d-4672-b19f-1fd6aa063e51.png)

**Comment by RedSoxFan04** [comment]
> I was able to make a successful compilation.
> 
> I recommend using the --oat from the mono runtime, it will decrease the RAM consumption by half

What exactly does --oat do? Why can't I find anything online about that option?

**Comment by Gzushgshsh** [comment]
> > I was able to make a successful compilation.
> > 
> > I recommend using the --oat from the mono runtime, it will decrease the RAM consumption by half
> 
> What exactly does --oat do? Why can't I find anything online about that option?

A mono runtime function for optimization, in some cases it can improve the performance of programs running on the mono runtime. I've noticed that in some versions of SubtitleEdit it improves RAM consumption

Mono documentation:
https://www.mono-project.com/docs/advanced/aot/

**Comment by RedSoxFan04** [comment]
> > > I was able to make a successful compilation.
> > > I recommend using the --oat from the mono runtime, it will decrease the RAM consumption by half
> > 
> > 
> > What exactly does --oat do? Why can't I find anything online about that option?
> 
> A mono runtime function for optimization, in some cases it can improve the performance of programs running on the mono runtime. I've noticed that in some versions of SubtitleEdit it improves RAM consumption
> 
> Mono documentation: https://www.mono-project.com/docs/advanced/aot/

I didn't notice any reduction in memory usage, but then again, I have 32GB on my system, so it's really not an issue for me. On the other hand, I've noticed that SubtitleEdit runs much more smoothly than before.

**Comment by Gzushgshsh** [comment]
> I didn't notice any reduction in memory usage, but then again, I have 32GB on my system, so it's really not an issue for me. On the other hand, I've noticed that SubtitleEdit runs much more smoothly than before.

The reduction in RAM consumption that I had noticed was more of a normalization, for some reason that I don't know, some older versions of SubtitleEdit used a lot more RAM than they should if mono oat wasn't used, in the newer versions this has stopped happening

**Comment by RedSoxFan04** [comment]
> > I didn't notice any reduction in memory usage, but then again, I have 32GB on my system, so it's really not an issue for me. On the other hand, I've noticed that SubtitleEdit runs much more smoothly than before.
> 
> The reduction in RAM consumption that I had noticed was more of a normalization, for some reason that I don't know, some older versions of SubtitleEdit used a lot more RAM than they should if mono oat wasn't used, in the newer versions this has stopped happening

Oh, okay. 

I gotta ask though, why do you keep calling it *oat* instead of *aot*?

**Comment by Gzushgshsh** [comment]
> > > I didn't notice any reduction in memory usage, but then again, I have 32GB on my system, so it's really not an issue for me. On the other hand, I've noticed that SubtitleEdit runs much more smoothly than before.
> > 
> Oh, okay.
> 
> I gotta ask though, why do you keep calling it _oat_ instead of _aot_?

I was spelling it wrong, sorry 😅
