### ISSUE TITLE
The bug of installing ver. 3.6.11 ??

### ISSUE THREAD

**Issue by Nanumy** [SubtitleEdit/subtitleedit#6642]
When I install ver. 3.6.11, **the "Korean" letters break on the popup box**.
So, I can't identify the letters.

please check it.

thank you!

![Bug_Install_Korean_language](https://user-images.githubusercontent.com/124282438/216548322-8b28b27e-26c9-4e4e-b569-ec3033c793f8.jpg)

**Comment by niksedk** [comment]
Should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBetaSetup.zip

**Comment by Nanumy** [comment]
[niksedk](https://github.com/niksedk) thank you! 고맙습니다~

**Comment by Nanumy** [comment]
I have just received it and resolved the issue.
always thank so much,
have a good day~

2023년 2월 3일 (금) 오후 7:05, Nikolaj Olsson ***@***.***>님이 작성:
