### ISSUE TITLE
[WebVTT] SE can't load YT's lyrics correctly

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#6643]
[timedtext.txt](https://github.com/SubtitleEdit/subtitleedit/files/10579814/timedtext.txt)
This is a subtitle file with verbatim capability downloaded from YouTube.
It looks SE can't correctly recognize the timecode in the file.

Test under SE 3.6.11 beta 20

**Comment by niksedk** [comment]
I think SE is reading this file fine...

**Comment by Mishasama** [comment]
![image](https://user-images.githubusercontent.com/54498172/217149401-11c4aed1-6001-4a80-8247-1f002f1eb424.png)

**Comment by niksedk** [comment]
It's just how the raw file looks:

````
00:00:07.700 --> 00:00:12.990 position:20%
[音楽]
この&lt;00:00:08.700&gt;<c>世界</c>&lt;00:00:09.179&gt;<c>で</c>&lt;00:00:09.840&gt;<c>女神</c>&lt;00:00:10.740&gt;<c>サンショウ</c>

````
