### ISSUE TITLE
Exported iTunes Timed Text of source file with milliseconds contains milliseconds

### ISSUE THREAD

**Issue by chenlung** [SubtitleEdit/subtitleedit#6644]
Download [these](https://github.com/SubtitleEdit/subtitleedit/files/10581870/Exported.iTunes.Timed.Text.of.source.file.with.milliseconds.contains.milliseconds.zip) files.

1. Open the WebVTT.
2. Select 'iTunes Timed Text' as 'Format'.
3. 'File'>'Save As'.
4. Choose another name.
5. Select 'iTunes Timed Text' as 'type'.
6. 'Save'.
7. Open the exported file in a plain text editor.

Expected result: timecode with frames
![Exported iTunes Timed Text of source file with milliseconds contains milliseconds  expected result](https://user-images.githubusercontent.com/2973439/216641489-489f1979-c434-4e94-9b13-ec603275557c.png)

Actual result: timecode with milliseconds
![Exported iTunes Timed Text of source file with milliseconds contains milliseconds  actual result](https://user-images.githubusercontent.com/2973439/216688634-70c25e85-e561-41da-938d-2acc18507759.png)

Notes:
- The [specification from Apple on iTunes Timed Text](https://help.apple.com/itc/filmspec/#/apdATD1E59-D1E1A1303-D1E59A1126) does not permit millisecond-based timecode (only frame-based), I don't think.
- Opening a properly formatted iTunes Timed Text file (expected result) appears to export fine, so it seems confined to ones with milliseconds.

Subtitle Edit 3.6.11 (stable) - Windows 10 Home.

**Comment by niksedk** [comment]
How is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

Also, you can change the time code format in the ITT properties (see the icon in the toolbar):
![image](https://user-images.githubusercontent.com/1261331/216700824-0e872488-7d65-4810-979b-b345de4611f8.png)

**Comment by chenlung** [comment]
I'm not an expert, but I think some Timed Text formats support milliseconds and frames. However, we should probably restrict options for the ones that support only one or the other, such as iTunes Timed Text (avoiding confusion or problems for less savvy users).

I notice you changed something hours ago, and iTunes Timed Text seems to save correctly now (even without going into Timed Text properties, I think). Thanks for this!

**Comment by niksedk** [comment]
Thx for the info :)

Yes, "Frames" is now the default "time code format" for ITT.
