### ISSUE TITLE
Pop-up error

### ISSUE THREAD

**Issue by DeaMorettoBR** [SubtitleEdit/subtitleedit#6645]
![error](https://user-images.githubusercontent.com/124404378/216718167-23a0b6ad-406b-4658-9bcb-5ecf918b7194.jpg)

**Comment by DeaMorettoBR** [comment]
I have just installed the new version of SE and this has popped up.

Thank you.

**Comment by niksedk** [comment]
It says 3.6.10... try uninstalling, and the re-install. 

You might also need to re-install the dotnet 4.8 framework: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

**Comment by DeaMorettoBR** [comment]
Thank you!

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Nikolaj ***@***.***>
Enviado:sábado, 4 de fevereiro de 2023 06:36
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [SubtitleEdit/subtitleedit] Pop-up error (Issue #6645)


It says 3.6.10... try uninstalling, and the re-install.

You might also need to re-install the dotnet 4.8 framework: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdotnet.microsoft.com%2Fen-us%2Fdownload%2Fdotnet-framework%2Fnet48&data=05%7C01%7C%7C7e96c51158444f85ef7808db06933f11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638111001703992475%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lKi2chqk%2BhyfYIQq5adll6dvhFT7tTCMoN5qd2G%2BVdM%3D&reserved=0>
