### ISSUE TITLE
 Installer of 3.6.11 causes crash of windows os

### ISSUE THREAD

**Issue by homunet** [SubtitleEdit/subtitleedit#6646]
The installer of causes of crash of windows. In addition, brakes the environment of previous version.
This does not occur one of 3.6.10

Environment:
Windows 11 Home (ARM)
21H2

**Comment by niksedk** [comment]
Did you choose Korean language? (this has recently been fixed in https://github.com/SubtitleEdit/subtitleedit/commit/027f3cc00d8d07b7a3044dd9b13af5463d223cbd)

**Comment by homunet** [comment]
Hi Nikolaj.
I selected Japanese as a installer dialogue language.
I've not tested other language. Is it better testing the others?

**Comment by niksedk** [comment]
@homunet: could you test this beta installer: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBetaSetup.zip
(I tried to save the Japanese translation in UTF8 - see )

**Comment by niksedk** [comment]
If you still get the error - could you attach a screenshot?
Also, does it work with the English language?

**Comment by homunet** [comment]
Hi again. Thank you for your work.
It works fine both with Japanese dialogue and English one.

**Comment by niksedk** [comment]
Thx for testing and reporting this issue :)

**Comment by homunet** [comment]
Your effort to develop Subtitle Edit is 1,000,000 times greater than mine.
You saved me a lot through the software.
Thanks a lot.
