### ISSUE TITLE
Unicode characters (specifically RTL, \u202B) are being displayed

### ISSUE THREAD

**Issue by hmkassem** [SubtitleEdit/subtitleedit#6649]
When trying to export subtitles into images (specifically BluRay sup), some unicode characters such as \u202B, (the RTL character) is being displayed and exported as well in some font families

1- In Arial and Calibri font, it is displayed. 
2- In Verdana, it is NOT displayed.

Any way around this? I would like to export in Arial.
Thanks

<img width="706" alt="RTL" src="https://user-images.githubusercontent.com/65424495/216784254-c6c05ba5-e317-4360-b45b-1f01f1e248e7.png">

**Comment by hmkassem** [comment]
I'm not sure if it has something to do with the font family, but I edited the actual Arial Font ttf file using fontforge and deleted those unicode characters and tried exporting it again and now they won't show :)

**Comment by niksedk** [comment]
Sorry, don't think I can fix this... I use just the MS tools.
