### ISSUE TITLE
EBU STL Export Issue - Application Not Responding

### ISSUE THREAD

**Issue by PascalsHere** [SubtitleEdit/subtitleedit#6652]
When attempting to save a file as an EBU STL, the application displays a window for setting the export options. However, after clicking the "OK" button, the application stops responding and does not complete the export process.
This is from a SRT file, But I have had the same issue with a WebVTT.
I am on Windows 11.
Version is 3.6.11

![after clicking ok](https://user-images.githubusercontent.com/71716875/216794546-1006db24-dec4-42d8-ba7a-9a6338ed4514.png)

https://user-images.githubusercontent.com/71716875/216794633-13cab626-6e94-4564-8b9e-4d8fdbe031de.mp4

Steps to Reproduce:

1.     Open the application
2.     Load a file in another format
3.     Go to the "Save As" menu and select "EBU STL" as the file format
4.     The export options window should appear.
5.     Fill in the required information and click the "OK" button.

Expected Result:
The application should complete the export process and save the file as an EBU STL.

Actual Result:
The application stops responding and does not complete the export process.

**Comment by niksedk** [comment]
Hm, I cannot re-create this... could you attach the file?
I presume it does not happen with all files?
