### ISSUE TITLE
Windows Defender protected your pc version 3.6.11

### ISSUE THREAD

**Issue by mvrhov** [SubtitleEdit/subtitleedit#6653]
I'm sure that the executable is fine. However the 3.6.10 works fine without any warnings.

**Comment by niksedk** [comment]
I've just update windows, restarted... and no warnings.

Try updating... still a warning? 
Are you using the installer version?

**Comment by Pax24fr** [comment]
Same here, Defender open when i launch the setup.exe
Also Whisper is not working anymore, it's start then after 1 second, it close saying "no text".
Back to 3.6.10 and it's ok.

**Comment by niksedk** [comment]
Try to update: 
![image](https://user-images.githubusercontent.com/1261331/216837395-89620f02-dd46-4326-8287-cad487085cee.png)


And as always, if you want to help, report "false positive" to your anti-virus provider, thx :)

https://www.virustotal.com is also a good way to check files

**Comment by mvrhov** [comment]
I extracted the portable zip. Same as with 3.6.10

**Comment by niksedk** [comment]
**And as always, if you want to help, report "false positive" to your anti-virus provider, thx :)**

**Comment by Pax24fr** [comment]
My security is up to date ! 
And reporting is always tricky I'm not an expert to say that it is 100% safe.

**Comment by niksedk** [comment]
Could you send some screenshots? Which file is it complaining about?

>I'm not an expert to say that it is 100% safe.
No, but you should report it... then they will/should check the file.
