### ISSUE TITLE
Subtitle Edit Whisper (GPU) time is not neat

### ISSUE THREAD

**Issue by xiaoliddiao** [SubtitleEdit/subtitleedit#6655]
Thank you for your hard work developing
I encountered a problem in the process of using

Subtitle Edit 3.6.11 calls Whisper (GPU) to recognize the subtitle, the time is not neat.
But the timestamps of the subtitles I recognize using the terminal command (GPU) are very correct and neat

win11(22H2)

**Comment by niksedk** [comment]
Could you explain a lot more? 
Also, I will need log files + sample files, thx.
