### ISSUE TITLE
Elipses

### ISSUE THREAD

**Issue by Sborsuk** [SubtitleEdit/subtitleedit#6656]
The "Fix Common Errors" doesn't pick up the 

(Hard Coded) Elipse
…

and convert it to 
... (three dots)

As in the sample I'm sending.

The original had them all within the sub files for the series, 
but unfortunately, I've already made the switch using
the "Replace" function, so I inserted 2 in the sub just
so you can play with it and get its code.

Perhaps you could add it the the rule for elipses.

Locke & Key s02e01 - The Premiere.English.srt
both in line 51

Thanks

Sam Borsuk
sborsuk@rogers.com
[Locke & Key s02e01 - The Premiere.English.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/10672377/Locke.Key.s02e01.-.The.Premiere.English.srt.txt)

**Comment by niksedk** [comment]
Hi Sam,

You can make your own rules in Edit - Multiple replace. It's even possible to run your "Multiple replace rules" in Tools - Batch convert.

**Comment by Sborsuk** [comment]
I didn't know that... Thank you...
    On Saturday, February 11, 2023 at 01:29:28 p.m. EST, Nikolaj Olsson ***@***.***> wrote:  
 
 


Hi Sam,

You can make your own rules in Edit - Multiple replace. It's even possible to run your "Multiple replace rules" in Tools - Batch convert.
