### ISSUE TITLE
[Linux BUG] Add support for tesseract 5 (error with tesseract 5)

### ISSUE THREAD

**Issue by Mangoes** [SubtitleEdit/subtitleedit#6658]
Hi,

When clicking on "start" (OCR) I get an error popup window : "Tesseract returned with code 1"

In OCR method : tesseract 4 is selected (as it is the only option available when running SE with mono on linux).

I have tesseract 5.3.0 installed.

Thanks !

**Comment by niksedk** [comment]
What version of SE are you running?

**Comment by Mangoes** [comment]
> What version of SE are you running?

version 3.6.11

**Comment by niksedk** [comment]
Where is you tessdata folder?
`/usr/share/tesseract-ocr/5/tessdata` ?

**Comment by Mangoes** [comment]
> Where is your tessdata folder?

 /usr/share/tessdata

(this is the install of the default repo in  opensuse tumbleweed, if you want to test this in a vm).

**Comment by niksedk** [comment]
OK, I presume Tesseract 5 is the default Tesseract version now?

Beta updated:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by Mangoes** [comment]
> OK, I presume Tesseract 5 is the default Tesseract version now?

Yes
 
> Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

Thanks!

But the problem is still the same (When clicking on "start" (OCR) I get an error popup window : "Tesseract returned with code 1"). If I click OK, it goes down each subtitle line # without outputting any text.

Some more info:
This is the terminal output of:
```
~> tesseract --version
tesseract 5.3.0
```

In "OCR method" I now see "Tesseract 5".

The tessdata location seems good, because when I try to download a dictionary it tries to save it to the same location and file name as the file that already exists from the repo install (i.ex: "/usr/share/tessdata/eng.traineddata"), but fails as it doesn't have write access to that directory (which is not a problem as we use the distribution package).

**Comment by niksedk** [comment]
Hm, I cannot make VirtualBox 7 work...

**Comment by Mangoes** [comment]
This issue is now fixed in v.3.6.12.

OCR now works fine with tesseract 5 on linux.

Thanks !
