### ISSUE TITLE
mp3 length issue

### ISSUE THREAD

**Issue by aspsenyo** [SubtitleEdit/subtitleedit#6662]
If I import a 1 hour and 55 minute mp3, I get 3 hours and 45 minutes of data. What should I do?
![11](https://user-images.githubusercontent.com/43168200/218062467-e6c6f966-66ec-431b-8e53-5f0cc2695025.jpg)
![22](https://user-images.githubusercontent.com/43168200/218062476-90c38958-d64a-4572-834a-8a0742794d9d.jpg)

**Comment by aspsenyo** [comment]
I converted from mp3 to wav and it is the normal length. Also the type of mp3? Depending on the type of mp3, the audio was of normal length. I was able to fix the problem, so if there is a bug there, I would appreciate it if you could fix it. Thank you.

**Comment by niksedk** [comment]
Sample file?
