### ISSUE TITLE
tesseract 5

### ISSUE THREAD

**Issue by galactic76** [SubtitleEdit/subtitleedit#6664]
howcan i skip all suggestions by default?
I want that tesseract 5 do all film wihtout asking anything
If it dont know it, i wat that he just skip it.
But it always ask me, and i always push skip always, but then it ask me again
How could I do skip all by default? Thanks

**Comment by niksedk** [comment]
Turn off "prompt for unknown" words.

**Comment by galactic76** [comment]
THanks!!!!
