### ISSUE TITLE
mpv download error...using windows 10 64bit

### ISSUE THREAD

**Issue by PurushothamK-23** [SubtitleEdit/subtitleedit#6665]
![-11 162719](https://user-images.githubusercontent.com/113305702/218254402-b38e51a1-5f82-42ab-8b0b-6a6f9bda0c70.png)

**Comment by niksedk** [comment]
Try again.. Perhaps something was down...
You can manually download mpv from here: https://github.com/SubtitleEdit/support-files/tree/master/mpv (you should probably get the libmpv2-64.zip
Or get the very latest versions here: https://sourceforge.net/projects/mpv-player-windows/files/libmpv/

**Comment by niksedk** [comment]
Also updated the help: https://www.nikse.dk/subtitleedit/help#settings_video
