### ISSUE TITLE
STL file says it's empty; how ot recover files in translation mode

### ISSUE THREAD

**Issue by evayor** [SubtitleEdit/subtitleedit#6666]
Hi, I was in the middle of translating a template STL file sent by client. Today, when I updated to version 3.11, tried to load the file, but it says it's empty or very short. In one of my many attempts, I somehow managed to load it, but then couldn't make it load the translation file in translation mode. [Here is the STL file](https://1drv.ms/u/s!AmDWN6Fzquj0hoAEgs309JqmSsajpw?e=FV82jM).
Two issues:
- how do I open the STL file and make it visible?
- how to restore the translation mode view I had before? Because it just creates a new translation file and I can't load my half-done file.
I have a very short deadline and I will really appreciate any ideas as fast as possible. Thank you!

**Comment by evayor** [comment]
Forgot to mention that I went back and reinstalled the older SE version because I thought there was something to do with the update.

**Comment by evayor** [comment]
Downloaded the client file again and this time managed to open it. Don't know how. 
Still, loading the half-done translated file in translation mode with the template was impossible. So I did something very lame, but that's the only way I can continue working:
- in translation mode inserted an empty line before the first one
- pasted the lines from the translated file
- all original lines, of course, shifted down
- erased the same number of lines as the translated ones I'd pasted, and the timing now is on
- however, now there's no original text on the side of the translated one to compare with, if you can follow my explanations

I really need to know how to handle this if it happens again.

**Comment by niksedk** [comment]
The file you liked in your first post is only 4 bytes... so downloading the STL file probably failed in your first attempt.

**Comment by evayor** [comment]
Yes, something strange happened with this file.
However, I still don't understand what's the way to put in translation mode the original template and an already existing translated file. Could you help me with that?

**Comment by niksedk** [comment]
You can open your translation subtitle file first. Then use File - Open original subtitle (translator mode)...
