### ISSUE TITLE
D-Cinema SMPTE 2014 always opening D-Cinema interop/png

### ISSUE THREAD

**Issue by MijBro** [SubtitleEdit/subtitleedit#6667]
Some releases ago it was still working that the option export --> D-Cinema SMPTE 2014 was exporting a proper SMPTE XML. If I choose the option now it always opens the window of the export option "D-Cinema interop/png". 

And while we are on it - it would be so nice to have as well a D-Cinema SMPTE/png option as interop/png is getting outdated ;)

<img width="1019" alt="Screenshot 2023-02-11 at 10 10 52" src="https://user-images.githubusercontent.com/125141007/218266087-bee6e9ec-8b60-4347-975d-72ffa22df1d4.png">

**Comment by niksedk** [comment]
thx for the info :)
Is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by MijBro** [comment]
wow that is a quick response! so now it opens a SMPTE png export panel which is great to have and I was searching for so long! but would it be possible to keep this one and have as well another option for a 2014 SMPTE XML with timed text? There is one in the "save as" but that is only 2007...

**Comment by niksedk** [comment]
In the toolbar we have multiple D-Cinema formats... is that what you are looking for?

![image](https://user-images.githubusercontent.com/1261331/218318667-3434569c-bfbc-4382-913e-71fa4d0d0d53.png)
