### ISSUE TITLE
Suggestion to automatically do "Auto br" in specific situations

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6668]
When working on improving subtitles by cutting and/or merging them, situations often arise, where some additional automation would be helpful. (Using Subtitle Edit 3.6.11 NEXT Beta 49.)

[1]
When selecting two lines in the list of subtitles, the first one very short, and the second one longer, and then choosing "Right click/Merge selected lines", the lines in the resulting subtitle often look like the lines in the original two subtitles. Example:
A>>> like him,
B>>> indeed really just like him.
Merging these two lines results in:
C>>> like him,
C>>> indeed really just like him.

Because such a result does not look good, I click, after the merging, on "Auto br" to correct this, which, in this example, results in:
C>>> like him, indeed
C>>> really just like him.

It happens a lot, that I have to click on "Auto br" after merging lines. How nice would it be, when this "Auto br" action would be happening automatically after each "Merge lines" action.

SUGGESTION 1: Add an option in Subtitle Edit, for automatically doing the "Auto br" action after each "Merge lines" action (for the subtitle that results from the "Merge lines" action). 

[2]
When splitting (with "Right click/Split line at cursor position") the following subtitle after the comma,
A>>> The king intervened, forcing the
A>>> enemy from their strongholds.
the following two subtitles appear:
B>>> The king intervened,
C>>> forcing
C>>> the enemy from their strongholds.

When a subtitle like this last one appears, I click, for this subtitle, after the splitting, on "Auto br" to correct this, which, in this example, results in:
C>>> forcing the enemy
C>>> from their strongholds.

SUGGESTION 2: Add an option in Subtitle Edit, for automatically doing the "Auto br" action after each "Split line" action (for both subtitles that result from the "Split line" action). 

Additional note:
In use cases as described above, I first select all subtitles and then click on "Auto br". Only after that, I start with manually correcting all subtitles. 
When I am done with all the manual corrections, I cannot use "Auto br" again on all subtitles, because some of the manual corrections I made, differ from what would result from "Auto br".

**Comment by niksedk** [comment]
1) Check the merge shortcuts - a few has auto-break too.

2) you can split at cursor pos (or even video+textbox cursor pos)

**Comment by oep42** [comment]
"2. you can split at cursor pos (or even video+textbox cursor pos)" ---> That's what I do in my situation [2], but that's not the point. The point is that I have to do an extra action after that splitting (clicking on "Auto br"), which I would like to see automated.

I never looked at shortcuts, because that is not the way I am used to work. I will try to use shortcuts, and perhaps I will regret not having tried that sooner.

I found the shortcut "Merge selected lines and auto-break", which I could use for my situation [1]. 
But I did not find a shortcut which I could use for my situation [2]. I found the shortcut "Split line at cursor position", but this does not include auto-break. 

Could you be so kind to add this shortcut: "Split line at cursor position and auto-break" (which auto-breaks both subtitles that result from this "Split line" action)?
