### ISSUE TITLE
Windows classic theme anomaly

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6669]
When using Windows with a classic theme, and when comparing the way an older version of SE looks compared to version 3.6.11 NEXT Beta 49, it turns out that the background of the text box in the newest version is not gray, but white. Please correct this anomaly.

![SE - Old and new user interface](https://user-images.githubusercontent.com/84353335/218277708-23cd43c9-0cc4-4280-98d9-14c40b42c1ab.png)

**Comment by niksedk** [comment]
OK, I cannot really sure any bugs... but is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by oep42** [comment]
Yes, that is better. In SubtitleEdit 3.6.11 NEXT Beta 50, the background of the text box is gray as expected in Windows with a classic theme. Thank you.
