### ISSUE TITLE
SE crashed. Can I recover temp saved file?

### ISSUE THREAD

**Issue by dgoryeo** [SubtitleEdit/subtitleedit#6671]
Hi, SE crashed (not responding) just when I finished my project nuf nuf. I had to force close it via Windows. How can I recover saved temporary file if any? Thanks!

**Comment by niksedk** [comment]
You could try File - Restore auto-backup...

**Comment by dgoryeo** [comment]
Wow, that did the job. Saved me few hours of work. Thanks!!!
