### ISSUE TITLE
Suggestion to add two 'Text box' shortcuts

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6673]
Could you be so kind to add the following two "Text box" shortcuts: 
   [Shortcut 1] "Split line at cursor position and auto-break" (which auto-breaks both subtitles that result from this action).
   [Shortcut 2] "Split line at cursor position and merge with next and auto-break" (which merges the second subtitle that results from this split with the next subtitle, and which auto-breaks both subtitles that eventually result from this action).

Situations where [Shortcut 2] would be useful, occur frequently. (For example, this is useful when changing where subtitles start and end in a list of subtitles.) It is much more work to do this without such a shortcut, i.e. to do this in three steps: (1) split, (2) select and merge, (3) select and auto-break.

EXAMPLE OF A SITUATION WHERE [Shortcut2] WOULD BE USEFUL:
Suppose that we want to improve these four subtitles:

You have a beautiful smile, by the way. Thank you, 
that's very kind of you to say. I don't want to mess 
up our friendship. I understand, but I can't stop thinking 
about you.

1A>>> Split before "Thank you" in the first subtitle:

You have a beautiful smile, by the way. 
Thank you, 
that's very kind of you to say. I don't want to mess 
up our friendship. I understand, but I can't stop thinking 
about you.

1B>>> Merge second subtitle with third subtitle:

You have a beautiful smile, by the way. 
Thank you, that's very kind of{br /}you to say. I don't want to mess 
up our friendship. I understand, but I can't stop thinking 
about you.

1C>>> Auto-break the first two subtitles:

You have a beautiful{br /}smile, by the way. 
Thank you, that's very kind of{br /}you to say. I don't want to mess 
up our friendship. I understand, but I can't stop thinking 
about you.

2A>>> Split before "I don't" in the second subtitle:

You have a beautiful{br /}smile, by the way. 
Thank you, that's very kind of{br /}you to say. 
I don't want to mess 
up our friendship. I understand, but I can't stop thinking 
about you.

2B>>> Merge third subtitle with fourth subtitle:

You have a beautiful{br /}smile, by the way. 
Thank you, that's very kind of{br /}you to say. 
I don't want to mess up our friendship.{br /}I understand, but I can't stop thinking 
about you.

2C>>> Auto-break the second and third subtitle:

You have a beautiful{br /}smile, by the way. 
Thank you, that's very{br /}kind of you to say. 
I don't want to mess up our friendship.{br /}I understand, but I can't stop thinking 
about you.

3A>>> Split before "I understand" in the third subtitle:

You have a beautiful{br /}smile, by the way. 
Thank you, that's very{br /}kind of you to say. 
I don't want to mess up our friendship.
I understand, but I can't stop thinking 
about you.

3B>>> Merge fourth subtitle with fifth subtitle:

You have a beautiful{br /}smile, by the way. 
Thank you, that's very{br /}kind of you to say. 
I don't want to mess up our friendship.
I understand, but I can't stop thinking{br /}about you.

3C>>> Auto-break the third and fourth subtitle:

You have a beautiful{br /}smile, by the way. 
Thank you, that's very{br /}kind of you to say. 
I don't want to mess{br /}up our friendship.
I understand, but I can't{br /}stop thinking about you.

How wonderful would it be, to be able to do the combined steps A, B and C (for cases like 1, 2 and 3) — by just using one shortcut.

[In the example, I had to change the notation of the linebreak symbol into "{br /}", because otherwise Github automatically breaks the lines with that symbol — which then makes the example less clear.]

**Comment by oep42** [comment]
Perhaps, instead of adding a specific shortcut that concatenates specific other shortcuts, it might be possible to add a more general approach to combining existing shortcuts.

Suggestion:
Add the option in "Settings/Shortcuts", to create a new shortcut that is a concatenation of existing shortcuts, i.e. to add a new shortcut that executes sequentially what is executed by two or more already existing shortcuts.

If this option would be added, I could create the shortcuts myself that I asked for above.

**Comment by darnn** [comment]
Oh yeah, I'd love some kind of macro function too (I've made my own just by using a text expander program to send keyboard inputs at specific intervals). But I assume that would be a lot of work.

**Comment by niksedk** [comment]
OK, added "split + auto br" (which I think split did once too): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip 

![image](https://user-images.githubusercontent.com/1261331/223550327-a232aba3-f9bb-4d11-a262-d3c7b8f2286c.png)


We have this shortcut:
![image](https://user-images.githubusercontent.com/1261331/223545367-efe3a9a6-7d9f-40e7-8959-cd7cf92d5982.png)

**Comment by oep42** [comment]
Thanks for adding the "Split line at cursor position and auto-break" shortcut, which is useful and works well. 

About [Shortcut 2] that I suggsted above. This shortcut can be described like this: "Split line at cursor position, [then] merge with line after, [then] auto-break previous and current line".

I did not earlier notice the shortcut "Move text after cursor position to next subtitle and go to next", which is about the same as "Split line at cursor position, [then] merge with line after". 

With this "Move text after..." shortcut, the last part of my suggested shortcut, "auto-break previous and current line", is missing. This last part is essential to prevent having to select those two lines and click on "Auto br" after each use of the "Move text after..." shortcut.

Could you be so kind to reconsider to add a shortcut which includes as last step "auto-break previous and current line"?
