### ISSUE TITLE
Redoing individual selected lines with Whisper can result in thousands of empty lines

### ISSUE THREAD

**Issue by albino1** [SubtitleEdit/subtitleedit#6677]
For context, this is a continuation of [the Const-me Whisper implementation](https://github.com/SubtitleEdit/subtitleedit/issues/6651) you so graciously added, more specifically this post by you in regards to the repeated line issue that whisper.cpp has where you said:

> OK, you could also chunk up the file... SE can also do Whisper on selected lines.

https://github.com/SubtitleEdit/subtitleedit/issues/6651#issuecomment-1426844328

Giving this a shot, it absolutely works, but unfortunately, there's some problems.

The main issue is that there are sometimes _thousands_ of these repeated lines, every two seconds, and the way that Subtitle Edit treats these is as _thousands_ of audio chunks.  I'm going to post some screenshots to more clearly illustrate what I mean:

<details>
  <summary>Repeated Lines in Subtitle Edit</summary>

![subtitle-edit1](https://user-images.githubusercontent.com/12164957/219272081-323faf59-405b-4bd9-866d-de4678a42ba3.jpg)

</details>

<details>
  <summary>Thousands of Extracted 2 Second Chunks</summary>

![subtitle-edit2](https://user-images.githubusercontent.com/12164957/219272134-24105318-a848-4bf1-bad6-ff3a767490c9.jpg)

</details>

<details>
  <summary>The Whisper Dialog</summary>

![subtitle-edit3](https://user-images.githubusercontent.com/12164957/219272269-f58ea96f-eade-4d25-9c1e-356e05326ac0.jpg)

</details>

Running these thousands of chunks through Whisper will work, but it takes hours and hours even with the Const-me GPU processing -- way longer than if you just redid the entire file from scratch dozens of times.  It starts and stops over and over, presumably going back and forth trying to get a full sentence, I'm not sure.

In the end, it does work, and you end up with a proper output, however Subtitle Edit is now filled with thousands of blank lines in between the actual sentences because there was either no dialog in that chunk, or it overlapped a different chunk.  In the end it looks like this:

<details>
  <summary>Thousands of Blank Lines</summary>

![subtitle-edit4](https://user-images.githubusercontent.com/12164957/219272870-143d7090-f20a-49fa-9ec3-050571c4a6f9.jpg)

</details>

So to sum up, the problems are: 1) Potentially thousands of repeated lines, 2) Many hours to process even with GPU acceleration, and 3) Thousands of blank lines after it's been "fixed".

Anyway, I'm not sure what the solution is for this.  Since the subtitle "lines" aren't real lines, because they're just 2 second snippets of time, you can't realistically redo them individually as if you were rechecking an actual line of dialogue.  Instead, it probably needs to just scan from first timecode to last timecode from scratch, which is probably not a practical solution from Subtitle Edit's perspective, but I thought it was worth mentioning.

The real answer is probably just to cross our fingers and hope that the repeated lines issue gets solved upstream, but I thought I would at least post this issue in case you have a better way of dealing with these in the mean time.

Feel free to close this if you think it's not worth trying to fix and that we're better off just waiting for fixes to the core Whisper components themselves.

Thanks!

**Comment by darnn** [comment]
How are you even generating the blank subtitle file? "Guess time codes"? Because it's not very effective for me, all the subtitles it creates are too short.

Regardless, I believe with Whisper it would be better to use large audio chunks anyway, because it, like, uses words it had previously identified to influence later guesses. My understanding of it is very limited, so I might be wrong, but that's what I know. And also, as I mentioned in that thread, if you do just take one sentence and try to recognize it, it doesn't work as well as several sentences together.

**Comment by albino1** [comment]
Initially I'm just running it from `Video` -> `Audio Text to Whisper` which brings up this dialog:

<details>
  <summary>Whisper Dialog</summary>

![subtitle-edit5](https://user-images.githubusercontent.com/12164957/219288622-10fbffa5-9b01-411a-9aaa-a5fef20ac662.jpg)

</details>


Then in an attempt to redo and fix the duplicate/repeated lines I'm selecting them and then right-clicking and choosing `Selected Lines` -> `Audio` -> `Audio to text (Whisper)` like this:

<details>
  <summary>Subtitle Edit Select Lines</summary>

![subtitle-edit6](https://user-images.githubusercontent.com/12164957/219288947-03bbc143-8862-4d16-8b1a-3da7c98628ae.jpg)

</details>

That brings up the normal Whisper dialog I posted above, except now there's however many audio chunks selected instead of just the main one for the whole file.

This is using the Subtitle Edit beta version 3.6.11 that was posted in the previous thread.

**Comment by darnn** [comment]
Ah, okay. Yeah, I think your best bet is to take just the chunk of the audio where the repeated lines appear (with maybe a minute on either end) and run that through WhisperDesktop on its own. Or, again, you could try this, which for whatever reason (presumably those more fine-grain Whisper settings we don't get access to) generates slightly different results, including not necessarily having repeating lines in places where they do appear with WhisperDesktop: https://colab.research.google.com/github/ANonEntity/WhisperWithVAD/blob/main/WhisperWithVAD.ipynb
To be clear, repeating lines do still appear there as well, just sometimes in different places (and, in fact, sometimes in different places in the same audio file).
Also, do you want to upload your test audio (or at least the part with the repeated lines)? Might make it easier to mess around with.

**Comment by albino1** [comment]
I could definitely chop up the audio myself and do parts of it separately until it works, but I was hoping to keep it all contained in Subtitle Edit so that it's synced all nice and tidy :)

I have several test files at this point, but they're all really long.  I'll see if I can come up with a smaller reproducible example tomorrow.  Though it seems this repeated lines problem is common enough that it shouldn't be too hard to make it happen, at least with non-English stuff.

**Comment by albino1** [comment]
This guy on the Const-me fork provided a Japanese audio clip which is reproducible:

https://github.com/Const-me/Whisper/issues/18#issuecomment-1435904777

I just muxed it into a random 8 min video to make a working Subtitle Edit example, and it exhibits the same problems as I was describing above.  Here's the initially generated duplicate lines after running Whisper Const-Me through Subtitle Edit with Japanese and `medium` selected:

<details>
  <summary>Repeated Lines</summary>

![subedit1](https://user-images.githubusercontent.com/12164957/219933546-248de8ae-7f85-4227-a40b-142898d06e8b.jpg)

</details>

This results in 243 total lines, almost all of which are 2 second chunk repeats.  Here's the actual outputted SRT file with the dupes (renamed from .srt to .txt so it could be uploaded to Github):

[张震号脉01_0002_MP3.txt](https://github.com/SubtitleEdit/subtitleedit/files/10776318/01_0002_MP3.txt)

Selecting all of the 2 second lines and choosing `Selected Lines` -> `Audio` -> `Audio to text (Whisper)` seems to kind of work (I don't speak Japanese, but it's certainly better than it was), however it results in tons of blank lines just like I initially described above:

<details>
  <summary>Empty Lines</summary>

![subedit2](https://user-images.githubusercontent.com/12164957/219934545-65d1fe0d-ab91-485b-8e9d-4ad58ed2bda9.jpg)

</details>

And here's the SRT file after having run through all of the `Selected Lines`, which took just over half an hour for 8 mins of video even using the GPU accelerated Const-me version:

[张震号脉01_0002_MP3-redone.txt](https://github.com/SubtitleEdit/subtitleedit/files/10776342/01_0002_MP3-redone.txt)

**Comment by darnn** [comment]
Ah, yes. I've actually run into it with one of my own files in the interim. This is neither here nor there in terms of the individual selected lines, but what I will say is, what got Whisper to actually recognize chunks of the file, if not the whole thing, was when I substantially edited it. YMMV, but in the audio editor I use, Goldwave, I applied an effect that boosted the stereo center (I believe), and then an equalizer setting called anti-RIAA something, which I think was supposed to be for badly-ripped mp3s back in the Napster days. And then I also sped it up to 1.7x, but that in itself doesn't help. So, I hope that can be of some use to you.

**Comment by albino1** [comment]
Thanks for the tips.  I've definitely found that if I just take a selection of a video and run it separately I get no repeated lines, so there's certainly workarounds outside of Subtitle Edit.  I guess what I'm just trying to get at is a way to do a selection of time from within Subtitle Edit without running it on thousands of 2 second "lines" and ending up with thousands of empty lines and mistimed subs.  For example running it on 10:00 -> 15:00 rather than 10:00 -> 10:02, 10:02 -> 10:04, 10:04 - 10:06, etc.

**Comment by darnn** [comment]
The only thing within Subtitle Edit itself is to set the start and end time of the section you want for a single subtitle. But then you get all the text in one subtitle and don't have the individual timing. However, you can also do the same thing and just extract the audio, and then stick it into WhisperDesktop outside of SE, which at least saves a step.

**Comment by albino1** [comment]
Right, you lose all the timings if you do it that way.  If it's only a few minutes long, like that example posted by the guy, it's not the end of the world, but trying to sort out a 2 hour movie in 10 minute chunks and then reassemble it with correct timecodes is just too time consuming to bother with currently unless you desperately need it :)

**Comment by niksedk** [comment]
You can use  "Guess time codes" to split into blocks of 25 seconds (is think the chunk size in whisper is 25 seconds), like this:
![image](https://user-images.githubusercontent.com/1261331/223523115-5043d3ae-68b3-4b72-90b1-2e85b6785273.png)
This will work poorly with the large model, as it takes too long to load (atm SE uses cmd line for each chunk).

I still hope these double lines (hallucinations) and improved time codes will be fixed in Whisper within the next year... if not SE could get some auto-chunking built in.

(I saw whisper got a few minor updates yesterday - https://github.com/openai/whisper/commits/main )

**Comment by albino1** [comment]
Looks like this is the same issue and is maybe fixed?

https://github.com/openai/whisper/commit/7858aa9c08d98f75575035ecd6481f462d66ca27

Fingers crossed :)

**Comment by niksedk** [comment]
> Looks like this is the same issue and is maybe fixed?
> 
> [openai/whisper@7858aa9](https://github.com/openai/whisper/commit/7858aa9c08d98f75575035ecd6481f462d66ca27)
> 
> Fingers crossed :)

That was an important bug fix where Whisper would sometime freeze/hang.

**Comment by niksedk** [comment]
We got a new commit that sounds interesting: https://github.com/openai/whisper/commit/919a713499d4c4f76ecf448617ada8e9ac008fbb
