### ISSUE TITLE
Opentype features

### ISSUE THREAD

**Issue by MuratKaribai** [SubtitleEdit/subtitleedit#6681]
@niksedk could you please add Opentype features because Chinese subtitles really need Stylistic Sets
![image](https://user-images.githubusercontent.com/40431755/219931991-c43bf8c8-24f3-4254-aeba-285f340a21b6.png)
![image](https://user-images.githubusercontent.com/40431755/219932008-a831d065-ce13-4f27-85c2-c79691458c49.png)

**Comment by niksedk** [comment]
Sorry, it's not possible in winforms as far as I known - I think GDI+ only supports TrueType fonts.
