### ISSUE TITLE
RTL line direction gets reversed after changing the color of a word

### ISSUE THREAD

**Issue by AE-Ismail** [SubtitleEdit/subtitleedit#6682]
Hello,

I’m trying to change the color of specific words in multiple lines in an Arabic .SRT,
but whenever I change the color, the text direction gets reversed and doesn't go back to normal.
I tried this process with .SRT and .ASS files, but it's all the same.

I attached a video of the problem:

https://user-images.githubusercontent.com/118636398/220166825-aa1ba133-6226-4c62-9084-031289586e22.mp4

**Comment by OmrSi** [comment]
I believe this isn't an SE issue, it's just how video player deal with text like this, it's been like that from as long as I can remember.
We've always written the text reversed because we knew coloring a word would reverse it back, or we avoid coloring one word altogether.

**Comment by AE-Ismail** [comment]
> I believe this isn't an SE issue, it's just how video player deal with text like this, it's been like that from as long as I can remember. We've always written the text reversed because we knew coloring a word would reverse it back, or we avoid coloring one word altogether.

I know this trick way before the RTL fix Unicode character tweak got included in SE, and I used it with punctuation marks. But never before have I been asked by a client to color a single word. 
For that file, I advised the client to use a video editing program that supports importing .srt files, which will be much easier and more accurate than SE. 

Anyway, thank you for the tip. :)
