### ISSUE TITLE
Damaged batch convert for last verion

### ISSUE THREAD

**Issue by Slava46** [SubtitleEdit/subtitleedit#6683]
Hi, for last Subtitle Edit 3.6.11 seems batch convert was broken.
For example using Offset time codes, like 200 ms delay or whatever. Usual .srt format and got for a lot of files error Failed.
For previous versions all were fine.

The same for Change frame rate for some numbers of files. Hope it'll be fixed because it's one of main SE functions. Thx.

![13](https://user-images.githubusercontent.com/22594656/220322134-253ac2dc-8814-44a0-8663-2cafb4df04db.png)

**Comment by Masina86** [comment]
Check the files i think that all have been converted successfully and only the "failed" message is a bug. Should be fixed tho.

**Comment by niksedk** [comment]
Something has been fixed in latest beta recently related to this and I cannot re-produce this. So, how does latest beta work for you?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by Slava46** [comment]
Fix possible crash in batch convert w overwrite - thx chensimmons
Seems in beta it's fine, thx.

**Comment by niksedk** [comment]
> Fix possible crash in batch convert w overwrite - thx chensimmons Seems in beta it's fine, thx.

thx for verifying :)
