### ISSUE TITLE
Unable to load 'libvosk'

### ISSUE THREAD

**Issue by zedoboss** [SubtitleEdit/subtitleedit#6685]
![image](https://user-images.githubusercontent.com/78974172/220541182-18b4408a-f2be-4ec5-942a-39c9cb7e89eb.png)

**Comment by niksedk** [comment]
Does installing this help? 
https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

Probably the 64-bit version (you most likely have a 64-bit os).
