### ISSUE TITLE
Double click on main list does not accomplish configured action.

### ISSUE THREAD

**Issue by esonec** [SubtitleEdit/subtitleedit#6689]
When mp3 audio is playing, then clicking at another location in the main list does not start playing at the dbl clicked location.

**Comment by niksedk** [comment]
It works fine here... if I have the correct setting in Options - Settings:

![image](https://user-images.githubusercontent.com/1261331/221008450-56e34e08-62cb-47bb-98c7-26516333014f.png)


What video player are you using?

**Comment by esonec** [comment]
![image](https://user-images.githubusercontent.com/46697807/221071685-0172300d-6876-4c76-84e6-ae4212045348.png)

I play the MP3 file with externally generated and loaded SRT file.
The problem is not affected by the selected Video Player.
When playback is stopped, then double clicking arbitrary subtitle line starts playing that line as expected.
But when playback is going on, then double clicking arbitrary subtitle just restarts playback of the current line that is being playback-ed. But does not jump to playback of the double clicked line.

**Comment by niksedk** [comment]
Hm, sorry. I still cannot re-create this.
