### ISSUE TITLE
don't save and change

### ISSUE THREAD

**Issue by amir385276** [SubtitleEdit/subtitleedit#6692]
Hi guys
in this new version 3.6.11 when i want to change and save some srt to the new srt coding like UTF-8 and in the tools tab batch converter 
don't change and save any srt file and say me the subtitle was broken
https://i.is.cc/22d4JJg6.jpg

please fix this issue

**Comment by niksedk** [comment]
Should hopefully be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by amir385276** [comment]
Hi niksedk
it's fixed in beta version
thanks a lot
