### ISSUE TITLE
{\an8} tag is not being added in NF subs

### ISSUE THREAD

**Issue by koewper** [SubtitleEdit/subtitleedit#6695]
Hello!

I recently noticed that the {\an8} tag is not being added in Netflix/XML subtitles, which positions the subtitle at the top, when I open them with the program. The XML contains 'region0' and 'region1' with the 'after' and 'before'

Example:
[sub.zip](https://github.com/SubtitleEdit/subtitleedit/files/10827902/sub.zip)

Thanks in advance

**Comment by niksedk** [comment]
Thx for the sub file and bug report :)

Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip
