### ISSUE TITLE
Whisper OpenAI model location

### ISSUE THREAD

**Issue by Purfview** [SubtitleEdit/subtitleedit#6698]
Can Whisper OpenAI models location be changed to SE/Whisper folder?
Now portable edition is not really portable when the models are kept in system's .cache folder.

**Comment by niksedk** [comment]
I think I will leave this `vanilla` so models are shared with cmd line.
CPP+Const-me models are in the SE Whsiper folder.

It would probably be possible using the `--model_dir` parameter...
