### ISSUE TITLE
How to set left/right margin to 0 for export BDD XML/PNG?  Below ass setting doesnot work for left / right margin

### ISSUE THREAD

**Issue by nissansz** [SubtitleEdit/subtitleedit#6702]
![image](https://user-images.githubusercontent.com/41010669/221419745-6ecc88b5-e0be-465a-b1e7-ea58ec5b3635.png)

Below ass setting doesnot work for left / right margin

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,GBK,37,&H00FFFFFF,&HFF000000,&H006C3300,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,0,0,0,134

**Comment by niksedk** [comment]
When using ASSA SE export should use the individual ASSA style margin for each line, so styles are controlled by ASSA and not SE settings (mostly).
Is something not working in the output?

**Comment by nissansz** [comment]
There is a minimal margin on left and right.
I need to use python to remove 1 pixel on left and right for each png.

Ass already sets 0 margin. But don't know why it does not work.

**Comment by niksedk** [comment]
Could you attach a few of the images?

**Comment by nissansz** [comment]
Original 
![image](https://user-images.githubusercontent.com/41010669/223256959-19903dd4-fe0c-464b-819d-f14e69f08106.png)

My cut version
![image](https://user-images.githubusercontent.com/41010669/223257263-74590e6d-bd72-46ea-aa3d-2901012d3e5c.png)

**Comment by nissansz** [comment]
Thank you, when can new version be released to include this change?

**Comment by niksedk** [comment]
Beta upped here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by nissansz** [comment]
Thank you.

**Comment by nissansz** [comment]
Another problem is full-width and half-width space.
The default space is too large.
full-width = 1 character 
half-width space = half character, or full English letter

**Comment by niksedk** [comment]
Probably another issue... and you will need to explain in great detail as I only know Danish and English!

**Comment by nissansz** [comment]
Half space original:
![image](https://user-images.githubusercontent.com/41010669/223560858-308d6b50-e3a1-4871-a3f9-7bc3f571fe8e.png)

My cropped version:
![image](https://user-images.githubusercontent.com/41010669/223560919-6346052f-ed9e-4003-ad89-33595c5d4753.png)


Full space original:
![image](https://user-images.githubusercontent.com/41010669/223560982-c859985f-0725-412b-adb6-751fc15fb0b4.png)


My cropped version:
![image](https://user-images.githubusercontent.com/41010669/223561022-622ded2b-adff-49ab-9bd0-4d49d8d33753.png)

**Comment by nissansz** [comment]
![image](https://user-images.githubusercontent.com/41010669/223561242-c71a119f-eb21-4c52-a90e-475ea83524ab.png)

**Comment by niksedk** [comment]
Sorry, I do not understand anything of the above...

**Comment by nissansz** [comment]
[spaces vs cropped.zip](https://github.com/SubtitleEdit/subtitleedit/files/10917835/spaces.vs.cropped.zip)

**Comment by niksedk** [comment]
Sorry, I cannot understand what you mean?
What is `The default space` in `The default space is too large.`? The default space between words? The space a letter uses?

**Comment by nissansz** [comment]
Try to generate png with this ass file. 
then you will know what I am saying.
[test space.zip](https://github.com/SubtitleEdit/subtitleedit/files/10917873/test.space.zip)

**Comment by niksedk** [comment]
Sorry, I do not understand what you mean - I have no knowledge of Japanese.

**Comment by nissansz** [comment]
Line 1 and 2 are too kinds of spaces. Just try to generate png.
