### ISSUE TITLE
Not found GPU supported Whisper model in new release

### ISSUE THREAD

**Issue by stevevaius2015** [SubtitleEdit/subtitleedit#6704]
After download and install latest release 3.6.11, I tried to transcript a video file with whisper. But only whisper OpenAI and whisper.cpp available to use. How can I add const.whisper GPU supported to tool? 
![image](https://user-images.githubusercontent.com/94312107/221833704-27f1f240-bc84-45a5-a3d3-7647c3d9bb11.png)

**Comment by niksedk** [comment]
You could try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip
