### ISSUE TITLE
Lack of UI help for synching external srt files

### ISSUE THREAD

**Issue by plajos1** [SubtitleEdit/subtitleedit#6705]
It would be a useful feature to start playing the video and just tapping a key like F11 to insert the next title into the actual position with a default length. The key is there, but the program does not updates which subtitle will be inserted next.

Synching between two files could be more intelligent. Setting some synch points could solve all the point between the synch points. 

If the original subtitle is encoded into the video file then the program is not capable of use it for comparision. Adjusting the times of an external subtitle is very painful this way.

**Comment by niksedk** [comment]
Thanks for your feedback, but please try to explain a bit more.
Read this: https://www.nikse.dk/subtitleedit/help#good-github-issue
