### ISSUE TITLE
Command line equivalent to the "Try to use source encoding" batch convert option

### ISSUE THREAD

**Issue by Hlsgs** [SubtitleEdit/subtitleedit#6707]
Is there such a thing? If I specify no `/encoding` option, subtitles get saved as `UTF-8 with BOM`, whitch the UI batch convert dialog always defaults to on open. This is a problem for, say, 1250 and 1251 encoding.

Thank you!

**Comment by niksedk** [comment]
OK, how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

But do save in UTF-8 if you possibly can... ANSI encoding is *so* outdated.

**Comment by Hlsgs** [comment]
> OK, how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip Use `/encoding:source`

Excellent. Thnak you very much, Sir!
 
> But do save in UTF-8 if you possibly can... ANSI encoding is _so_ outdated.

In an ideal world, I would agree. However, there's alot of stuff out there for non-english that is saved with the wrong encoding. Players don't care, as they override that with their default encoding setting, however, SE is unable to properly convert because of that(to be honest, I'm unaware if SE does conversion on the fly when using the command line and saving as UTF8). And since here we are talking about command line and not doing things by hand, not messing with the encoding is best. IMHO, it should be the default behavior for both command line and GUI batch convert, but having the option you've just implemented also works.

**Comment by niksedk** [comment]
Yes, it's included :)
