### ISSUE TITLE
Batch - redo casing settings not the same as in the menu

### ISSUE THREAD

**Issue by chschmit** [SubtitleEdit/subtitleedit#6711]
The ability to change to Normal Casing AND Fixing the Names Casing at the same time is availble in the Tools Menu under Change Casing, but in Batch mode under Redo casing, these are seperate settings.

Can the settings in be made to be the same?

**Comment by niksedk** [comment]
What is the problem?

**Comment by chschmit** [comment]
On individual files I'm able to change the casing AND preserve the proper
Names (dictionary.xml) in one process. Whereas in batch mode they are
separate radio buttons... I need to run the batch twice to do both
processes.

**Comment by niksedk** [comment]
OK. How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip ?

**Comment by chschmit** [comment]
That fixes the problem. Thank you so much!
