### ISSUE TITLE
Google Cloud API Function broken, help

### ISSUE THREAD

**Issue by Apocalypse612** [SubtitleEdit/subtitleedit#6716]
Trying to assign the latest beta of Subtitle Edit an API key. It has billing enabled, and the key is valid. I still have free trial credits, and my bank card is linked. I used it in Anki and it works just fine. Here, though, it spits an error. Help please.

![image](https://user-images.githubusercontent.com/6374154/222805599-5b42464f-d8d7-41a4-b3fb-1ed0dcfabbbf.png)

**Comment by githubfat** [comment]
me too
