### ISSUE TITLE
Error with Whisper CPP

### ISSUE THREAD

**Issue by rsmith02ct** [SubtitleEdit/subtitleedit#6718]
I'm  trying to use CPP again but am getting an error with 3.6.11. I did a clean re-install but it persists.

![image](https://user-images.githubusercontent.com/122251109/222942869-84a8fcdf-6ea2-4061-9cac-3ca698da7768.png)

**Comment by rsmith02ct** [comment]
I was able to avoid this error by resetting preferences and not associating Subtitle Edit with Whisper Standalone. If I associate the two I can't use Const-me or CPP anymore.

**Comment by Purfview** [comment]
He meant `Whisper OpenAI` from there -> https://github.com/Purfview/whisper-standalone-win
Btw, he copied beta standalone over installed in program files.

Try to delete FFmpeg from whisper's folder.

**Comment by euzenlee** [comment]
> I was able to avoid this error by resetting preferences and not associating Subtitle Edit with Whisper Standalone. If I associate the two I can't use Const-me or CPP anymore.

I also encountered the same problem. Once openai Whisper is used, I can no longer use cpp, and only reset it.

**Comment by niksedk** [comment]
I cannot re-create this error.

Try with latest beta at least: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip
(portable version - unpack to something like "C:\Tools\SE")

**Comment by niksedk** [comment]
@Purfview: Nice with your whisper executables... how did you compile it? PyInstaller?

**Comment by Purfview** [comment]
@niksedk Thx, yes PyInstaller.

**Comment by niksedk** [comment]
OK, cool :)

I do not game, but now I wish I had a nice gfx card ;)
