### ISSUE TITLE
OCRFixReplaceList.xml question

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#672]
Can OCRFixReplaceList.xml in Dictionaries be standalone file independent of any other language files in dictionary? 

I mean to send new patch for cro_OCRFixReplaceList.xml for Croatian language purposes, but I'm unsure of would it display automatically in SE, since currently it does not. Maybe it needs connecting with something,  for proper display? could you do that?

**Comment by xylographe** [comment]
I think, the three letter ISO language name for Croatian might be hrv ,
```
PS> [System.Globalization.CultureInfo]::GetCultures('AllCultures')|?{$_.EnglishName -match 'Croa'}|ft ThreeLetterISOLanguageName, EnglishName -auto

ThreeLetterISOLanguageName EnglishName
-------------------------- -----------
hrv                        Croatian
hrv                        Croatian (Croatia)
hrb                        Croatian (Latin, Bosnia and Herzegovina)
```

**Comment by diomed** [comment]
well, that's the least of my problems, I'll name it hrv if that's a must. 
I'd like an answer to my questions, please.

**Comment by niksedk** [comment]
The OCR fix replace lists can be standalone and will be used by Tools -> Fix common errors -> Fix common OCR errors.

When used via the OCR in SE the spell check dictionary is required to use the ocr fix list. The ocr fix replace list file is determined by the spell check language you choose in the ocr window.

**Comment by diomed** [comment]
Thank You for explanation. This is solved and can be closed.

**Comment by diomed** [comment]
ummm... something is unclear to me. should 'WordPart' change parts of words to fixed parts of words, or what exactly?

So if I have wrongly written homeybee would this change every homeybee in honeybee or not?
    <WordPart from="homey" to="honey" />

I need explanation on this.

**Comment by niksedk** [comment]
WordPart is part of a word, e.g. "vv" to "w" or "oo" to "cc" - it will only be replaced if the current word is not spelled correctly and the new word is, like "vvelcome" to "welcome".
