### ISSUE TITLE
Setting "Display standard code" while exporting STL

### ISSUE THREAD

**Issue by coding-hobby** [SubtitleEdit/subtitleedit#6720]
I want to set Display standard code as open subtitling/Level 1 Teletext/Level 2 Teletext while exporting an STL file. How can I achive this?

**Comment by niksedk** [comment]
Try clicking on the EBU STL properties icon in the toolbar (or File - EBU STL properties):

![image](https://user-images.githubusercontent.com/1261331/223141737-1f669039-56e5-4122-9719-317411ff8dad.png)

**Comment by coding-hobby** [comment]
Is there a way to set it during export or any command line command?

**Comment by niksedk** [comment]
You can use the `/ebuheaderfile:<file name>` parameter

**Comment by coding-hobby** [comment]
Thank you.
