### ISSUE TITLE
Whisper Const-me issue

### ISSUE THREAD

**Issue by JDTR75** [SubtitleEdit/subtitleedit#6721]
Whenever I click on the "Translate" option I get this:

![image](https://user-images.githubusercontent.com/1891941/223280234-44f0bd01-2f30-4fd6-98e3-19f783fb2003.png)

Is this happening to anyone else?

I already have whisper.cpp downloaded (both CPU and GPU). I only get prompted with this dialogue if I click on "Translate". If I go with the transcription, it works just fine.

Thank you in advance!

**Comment by niksedk** [comment]
Thx for the info :)
Const-me does not support "translate".

**Comment by darnn** [comment]
You mean in SE? Because it does work with WhisperDesktop itself (albeit only into English, since that's the only thing the original Whisper can do).

**Comment by niksedk** [comment]
@darnn: Thx. Yes, the "translate" functionality is left intact... I had overlooked it, but perhaps this work: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip ?

(I cannot run const-me due to my poor gpu)

**Comment by darnn** [comment]
Yes, at least with the very short sample I tried, it translates into English the same way WhisperDesktop does.

**Comment by JDTR75** [comment]
Thank you guys!
