### ISSUE TITLE
[suggestion][whisper.cpp] use their newer x64 builds with BLAS

### ISSUE THREAD

**Issue by eladkarako** [SubtitleEdit/subtitleedit#6722]
https://github.com/ggerganov/whisper.cpp/actions/workflows/build.yml?query=branch%3Amaster+actor%3Aggerganov+is%3Asuccess+event%3Apush

(for example https://github.com/ggerganov/whisper.cpp/actions/runs/4347009519)

<img width="250" src="https://user-images.githubusercontent.com/415238/223536912-c490b0f2-d8e8-4b8b-a5ac-56921dd3ebeb.png" />

it seems stable and there is a significant speed boost comparing to current version distributed w/ SE (drop in replacement)

- https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms
- https://github.com/ggerganov/whisper.cpp/issues/550#issuecomment-1455187082

**Comment by niksedk** [comment]
Latest beta already does this I believe :)
