### ISSUE TITLE
Batch convert simplified chinese PAC to Any File Format results in gibberish

### ISSUE THREAD

**Issue by sandrickn** [SubtitleEdit/subtitleedit#6723]
This issue can only be replicated in batch conversion, saving from the File > Save As option does not have this error.
I suppose its something to do with the language encoding/decoding for the batch process.

![image](https://user-images.githubusercontent.com/74899572/223604233-8d497555-b29d-4319-ab3b-29916045af69.png)

**Comment by niksedk** [comment]
Could you attach the pac file?

**Comment by niksedk** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/1261331/223669194-c06f3540-0888-4be8-9df7-b24461a06436.png)
