### ISSUE TITLE
Request: Burn from Selected Lines

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#6724]
I love the Cut video when exporting feature in the Beta version. 
![cut video](https://user-images.githubusercontent.com/92556454/223670396-5066e9f7-7eb6-4328-a486-9caceeb0ee91.png)

I was wondering,  is it possible to complement it with a Burn From Selected Lines? This will help alot because I don't need to keep writing down the time to cut the video.

![Burn Selected Lines](https://user-images.githubusercontent.com/92556454/223670557-3e2f3710-a8dc-4406-9e7e-1842a925edc2.png)

I hope this makes sense. 
Thanks!

**Comment by niksedk** [comment]
Nice idea :)
Something like this?

![image](https://user-images.githubusercontent.com/1261331/223677760-468b3f51-b2c1-4e44-b049-10c6bd1ddde2.png)


https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by MbuguaDavid** [comment]
> Nice idea :) Something like this?
> 
> ![image](https://user-images.githubusercontent.com/1261331/223677760-468b3f51-b2c1-4e44-b049-10c6bd1ddde2.png)
> 
> https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

Yes! Something like that.

It then takes us to the Burn in Window with the cut times (selected lines) already selected. :) 

It would take the guessing and writing down of the timecodes when we need to export part of a video with burned-in subs for review. :) 

Thanks!

**Comment by niksedk** [comment]
He, do try the linked beta ;)

**Comment by LeonCheung** [comment]
Hmm, what if the expected part doesn't start and/ or end EXACTLY at the first/last selected line? By creating blank lines as a quick and dirty trick? 😆

**Comment by MbuguaDavid** [comment]
> He, do try the linked beta ;)

Tried it but it's not auto-adding the time from the selected lines. 
It sets the cut time from the start to the end of the video. 

![not recognizing](https://user-images.githubusercontent.com/92556454/223681878-e2292221-ae5d-461e-a68e-a175523b4b3c.png)

**Comment by niksedk** [comment]
And with video time picker: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Wow, exactly what I imagined! 👍 Just it would be better if the window could be a bit higher, or it could be kinda auto-adaptive?

![image](https://user-images.githubusercontent.com/494788/223740915-6b949d0f-2927-404d-9a4a-72924d0194ef.png)

**Comment by niksedk** [comment]
OK, tried to improve it slightly: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip
Better?

**Comment by LeonCheung** [comment]
Much better! 🍺

**Comment by MbuguaDavid** [comment]
Thanks for this.
Works perfectly. 

Finally, is it possible to have the name that's pre-populated to burn in the subtitles have the timecodes selected at the end of the name?
