### ISSUE TITLE
Request: Support for embedding soft subtitles to video

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#6725]
I'm not sure if this has been asked before but Is it possible to support the embedding of soft subtitles to a video in Subtitle Edit?

I'd love to use Subtitle Edit as the only Subtitling tool but I have to use MKVToolnix when I need to embed soft subtitles (It also works without re-encoding the video).

 - You can for a subtitle to be the default subtitle when multiple subs are available.
 - Language Selection, etc
 
 
![Mkvtoolnix](https://user-images.githubusercontent.com/92556454/223672812-3ac81ffa-147b-4ae8-95d0-05536cfc8f93.png)

 I hope this can be implemented someday in Subtitle Edit.
 
 Thanks!

**Comment by niksedk** [comment]
For Matroska mkv files?

**Comment by MbuguaDavid** [comment]
Thank you so much for this. It works.
![Video with soft subtitles](https://user-images.githubusercontent.com/92556454/224443114-54a06ef4-4f6a-4817-b43c-18ca3b5eb3c1.png)

Is it possible to select the subtitle I'd like to be the default? At the moment, the subs are embedded but none is available by default.

This feature is highly welcome.

**Comment by MbuguaDavid** [comment]
Is it possible to also have the Subtitle Tracks indicate the Language of the Subtitle instead of Track 1, Track 2, etc? 
![Language -](https://user-images.githubusercontent.com/92556454/224447893-6d42fed4-e483-4fcf-ade3-58c1235d219a.png)

Thanks!

**Comment by niksedk** [comment]
New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip
SE should now try to set title, forced and default...

**Comment by MbuguaDavid** [comment]
> 

This is it. Works great.
There was a bug that I cannot re-create where the soft subbed video gave me a notification of TEST! 
Secondly, in one instance the Generate button was greyed out even though subs were available. Not sure why. 

![greyed out Generate button](https://user-images.githubusercontent.com/92556454/224471482-f26fdd80-b0d4-4b28-a46d-b85cadd29c6c.png)

I've tried to re-create the bugs... to no avail.

Thanks!

**Comment by ivandrofly** [comment]
I think the context-menu name is a bit confusing

## Rename suggestion
- `Generate video with embedded subtitle` => `Embedded Subtitles`
- `Generate video with burned-in subtitle` => `Burned-in Subtitles`

We can just drop the *Generate video with* part as we are not actually generating the video,
the subtitle is just being embedded into the video

/cc @niksedk

**Comment by niksedk** [comment]
New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
> I think the context-menu name is a bit confusing
> ## Rename suggestion
> 
>     * `Generate video with embedded subtitle` => `Embedded Subtitles`
> 
>     * `Generate video with burned-in subtitle` => `Burned-in Subtitles`
> 
> 
> We can just drop the _Generate video with_ part as we are not actually generating the video, the subtitle is just being embedded into the video
> 
> /cc @niksedk

Hm, SE does generate a new video file... I cannot seem to find a better name:

![image](https://user-images.githubusercontent.com/1261331/224493845-8503f531-1fa3-4b10-9ba8-754b7c95ba97.png)

We could use  multiplex/encode which is more precise, but it is probably not helping most users:
* `Multiplex video with (embedded) subtitles`
* `Encode video with burned-in subtitle`

**Comment by niksedk** [comment]
Updated beta - minor UI fixes +localization + you can now dbl-click on a subtitle to view it
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

@eladkarako: Does the ffmpeg cmd line look okay to you? Any ideas?
`ffmpeg -i "C:\Data\a.mp4" -i "C:\Data\a.srt" -i "C:\Data\b.srt" -map 0 -c copy -map 1 -map 2 -c:s:s:0 srt -c:s:s:1 srt -metadata:s:s:0 language="eng" -metadata:s:s:0 title="English" -metadata:s:s:1 language="eng" -metadata:s:s:1 title="English" "output.mkv"`

**Comment by MbuguaDavid** [comment]
The default and forced selections don't seem to work. 
I've tried to toggle default (alone) toggle Force (alone) or both but the video does not have a default subtitle when I play. :( 

![disabled](https://user-images.githubusercontent.com/92556454/224509791-551c3c59-452a-4d67-ab57-7a72fceb54f6.png)

**Comment by niksedk** [comment]
> The default and forced selections don't seem to work. I've tried to toggle default (alone) toggle Force (alone) or both but the video does not have a default subtitle when I play. :(
> 

If you look in SE/MKVToolNix... the sub is `default`, right? My guess is, that this auto play default is a player setting...

**Comment by MbuguaDavid** [comment]
> > The default and forced selections don't seem to work. I've tried to toggle default (alone) toggle Force (alone) or both but the video does not have a default subtitle when I play. :(
> 
> If you look in SE/MKVToolNix... the sub is `default`, right? My guess is, that this auto play default is a player setting...

I think the issue is when I save the video as MP4. Mkv works fine. 
Also, when the video is done generating the prompt to open the folder containing the video with embedded subs is no longer appearing. It was available in earlier versions.

**Comment by niksedk** [comment]
@MbuguaDavid: Ah, thx - close/prompt issue should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

@eladkarako: thx for the info... I think it's okay now. 
Blu-ray .sup files seems kinda hard to add! ATM I just add them with "copy" while SubRip files are added with "srt" as codec.
Pretty surprising ffmpeg could convert an "EBU STL" file to ASSA... but SE should probably do the conversion.

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/225583445-77920f9b-12d7-4507-96c7-a38a06ff4be1.png)

Note: ATM image based subtitles are NOT supported (like BDSup or DVD pics)

**Comment by MbuguaDavid** [comment]
There's a bug when selecting Toggle Default and Toggle Forced.

https://user-images.githubusercontent.com/92556454/226006681-469ae6c5-c428-4b1f-b72f-77584bf9ede0.mp4

**Comment by niksedk** [comment]
Thx David :)
Hopefully fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by MbuguaDavid** [comment]
> Thx David :) Hopefully fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

Yes, it is fixed. 
Thanks!

**Comment by triatomic** [comment]
Sorry for necro; but is it possible to have batch videos ?
