### ISSUE TITLE
DVB SUBTITLE (Image)

### ISSUE THREAD

**Issue by MetalBlade12** [SubtitleEdit/subtitleedit#6726]
Hello,
Thank your for your amazing work,

I have a question about DVB Subtitle (image based) i see SubtitleEdit can decode them but how about encode ?
Did you plan to work on it ? or maybe you have some idea how to achieve this ?

Many Thanks

**Comment by niksedk** [comment]
I've no plans to add encoding of dvb images, but what do you need it for and in what format?

**Comment by MetalBlade12** [comment]
we have a mpegts stream we want to mux with our subtitle (srt stl or pac in chineese) mpegts can contain DVBSUB Text (teletext) or image subtitle. Teletext can't contain chineese caracter so we need to convert them into dvbsub stream.
I try to mux VobSub created with Subtitle edit with ffmpeg to do this but IRD display ugly and unreadable bitmap.

**Comment by MetalBlade12** [comment]
not working too with .sup file

**Comment by MetalBlade12** [comment]
Here is a look of display the ugly grey is the bitmap subtitle ...

[image: Capture d’écran 2023-03-09 104956.png]
this one with vlc

[image: image.png]



Le jeu. 9 mars 2023 à 10:47, Nikolaj Olsson ***@***.***> a
écrit :
