### ISSUE TITLE
Frame bleeding with "Set start/end time" 

### ISSUE THREAD

**Issue by Perevodildo** [SubtitleEdit/subtitleedit#6730]
Recently, I've moved from older version (don't really remember which one, either 2.5.5 or 3.5.5 or 3.1.1) to 3.6.11. While using mpv in both as video provider, before, I could do exact timings with manual scene-snapping as I work through the file with next/previous frame buttons and F11/F12, marking the frame where the scene starts with F11 and the first frame of the next scene with F12. Now, when I use any of those buttons, a lot of time, lines visually appear one frame earlier or later than what I marked as beginning/end in the player, even if the timings are correct. Other external players also display them frame-bled. This has been an issue for two videos already, one 59.9 and the other 23.976 fps. 
It may be worth noting, when I try to do the same in Aegisub, it has no problem whatsoever handling this task with either of those videos. All I can really do about this is to edit the start/end time by entering the digits manually in the appropriate field, adjusting the timings by 10ms on average, which is understandably tedious. 
Sorry if this issue has been resolved already, or if that's not an issue at all. There seemingly wasn't anything of the kind in the list as I skimmed through it. 
I tried to show what I mean with a video
https://user-images.githubusercontent.com/58600674/224452429-28eba9c5-c498-4862-86b8-a6180a5466a6.mp4

**Comment by niksedk** [comment]
I'm not really sure what you mean...

Does re-downloading mpv help? You have an older version 1.x.

Does any of these shortcuts help?
![image](https://user-images.githubusercontent.com/1261331/224454999-26ded955-5f5f-48f9-9623-c50ad124cb0b.png)

Does re-encoding the video help?

Does switching time-code-mode help?
![image](https://user-images.githubusercontent.com/1261331/224455300-9a13f435-ee8b-43d1-ac76-2e874ee0fc30.png)

**Comment by Perevodildo** [comment]
>Does re-downloading mpv help? 

Done. The issue persists. 
>Does any of these shortcuts help? 

I'm using the first two of those, I don't see how they're supposed to help. 
>Does re-encoding the video help? 

Frames still occasionally bleed. 
>Does switching time-code-mode help?

Tried it. The issue persists.

**Comment by niksedk** [comment]
Could you upload the source files somewhere?

Also, could you explain a bit more... when you set the start/end time... it's not on the correct frame in the video preview?
If the open the same start/end time in Aegisub it is correct n the video preview?

I guess it possible that libmpv does not provide this framebased access to the video file.

Does anybody know more about this?

**Comment by darnn** [comment]
The only thing that comes to mind is that, in SE (at least with MPV, and in frame mode as opposed to MS mode, but I think it's true of both), the final frame of a subtitle doesn't appear in the preview. For example, if you have a subtitle that starts at 00:00:05:00, and you change the timing of the previous subtitle so it ends at 00:00:05:00, the preview will only show the subtitle that starts at 00:00:05:00. If you set the earlier subtitle to end at 00:00:05:01, it will show them overlapping, as you'd expect.

**Comment by niksedk** [comment]
@darnn: Yes, so the "End time" is probably more of a "Hide time", right?

**Comment by Perevodildo** [comment]
Here is a little excerpt from the video I'm experiencing this issue with, for demonstration, as well as the sub file made in SE: in that sub file, nearly every line appears in preview one frame later than intended and disappears one frame later as well, except for the border between lines 2&3 and 5&6, although I timed them all the same way - "find the frame where the new scene starts ➡hit F12 ➡Select next line ➡hit F11"
https://drive.google.com/drive/folders/10D2B6LL-CPLje-lWByB7fbmI0tX3bQxC?usp=sharing
On a sidenote, reinstalling SE as well as resetting the settings didn't help either.

**Comment by Perevodildo** [comment]
> when you set the start/end time... it's not on the correct frame in the video preview?

Yes. 

> If the open the same start/end time in Aegisub it is correct n the video preview? 

No, it's 1 or even 2 frames off in Aegisub either, as well as in VLC.

**Comment by Perevodildo** [comment]
Upd: reverted to 3.5.18 and it's fixed. Timings work smoothly, just like they used to. In the folder above, a file with timings done in 3.5.18 for comparison. Thanks, [niksedk](https://github.com/niksedk).

**Comment by Perevodildo** [comment]
Upd 2: went ahead and checked all the versions 3.6.5 through 10, this issue first appears in version 3.6.8 and onwards, I don't encounter anything of the kind in 3.6.7 or versions prior to it, so that's what I'll settle on for now. 
Hope it helps, in case you intend to fix this.

**Comment by niksedk** [comment]
@Perevodildo: thanks for looking more into this. 
I will try to see if I can fix it. First I will try to understand the issue (which can often be really hard), but I hope looking at the files with help.

**Comment by niksedk** [comment]
This commit was made for 3.6.8:
https://github.com/SubtitleEdit/subtitleedit/commit/a0704556c5600125b1303ac14351b439d300f805
Latest source with old assa time code: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/framebleedtest.zip

When I match scene3 the the image, it seems to work...
![image](https://user-images.githubusercontent.com/1261331/224502311-e6a4f7a8-fb78-461d-980c-b807fb8b1628.png)

**Comment by niksedk** [comment]
Also, SE uses milliseconds like "540" internally, while ASSA uses fragments with two digits, so "54".

**Comment by Perevodildo** [comment]
Yes! This build seems to be functioning perfectly in that regard.
