### ISSUE TITLE
3.6.11 not published to nuget.org ?

### ISSUE THREAD

**Issue by BryanJacobs** [SubtitleEdit/subtitleedit#6731]
Hey, forgive me if I'm missing something, but it looks like 3.6.11 was released on github at the end of January, but the `libse` on nuget.org is still at 3.6.10?

How is the release process here managed?

**Comment by niksedk** [comment]
libse is not published on NuGet at every UI release - I will try to publish libse on NuGet when releasing 3.6.12

**Comment by BryanJacobs** [comment]
Okay, thanks. FYI, the reason I was looking is that the master branch of Jellyfin is broken on Linux because its libse attempts to open the path `/Subtitle Edit`. I see you've made some commits in that area (reverting some changes in a Linux codepath?) so I was attempting to see if upgrading them from 3.6.10 to 3.6.11 would fix the issue.

**Comment by BryanJacobs** [comment]
Partial stack trace in the event you're already looking:

```Mar 11 20:46:07 typhon dotnet[2563980]: System.TypeInitializationException: The type initializer for 'Nikse.SubtitleEdit.Core.Common.Configuration' threw an exception.
Mar 11 20:46:07 typhon dotnet[2563980]:  ---> System.UnauthorizedAccessException: Access to the path '/Subtitle Edit' is denied.
Mar 11 20:46:07 typhon dotnet[2563980]:  ---> System.IO.IOException: Permission denied
Mar 11 20:46:07 typhon dotnet[2563980]:    --- End of inner exception stack trace ---
Mar 11 20:46:07 typhon dotnet[2563980]:    at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
Mar 11 20:46:07 typhon dotnet[2563980]:    at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
Mar 11 20:46:07 typhon dotnet[2563980]:    at System.IO.Directory.CreateDirectory(String path)
Mar 11 20:46:07 typhon dotnet[2563980]:    at Nikse.SubtitleEdit.Core.Common.Configuration.GetDataDirectory()
Mar 11 20:46:07 typhon dotnet[2563980]:    at Nikse.SubtitleEdit.Core.Common.Configuration..cctor()
Mar 11 20:46:07 typhon dotnet[2563980]:    --- End of inner exception stack trace ---
Mar 11 20:46:07 typhon dotnet[2563980]:    at Nikse.SubtitleEdit.Core.Common.Configuration.get_Settings()
Mar 11 20:46:07 typhon dotnet[2563980]:    at Nikse.SubtitleEdit.Core.SubtitleFormats.MPlayer2.get_Extension()
Mar 11 20:46:07 typhon dotnet[2563980]:    at MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser.<>c.<.ctor>b__2_0(SubtitleFormat subtitleFormat) in /home/aur/jellyfin-git/src/jellyfin/MediaBrowser.MediaEn>
Mar 11 20:46:07 typhon dotnet[2563980]:    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
Mar 11 20:46:07 typhon dotnet[2563980]:    at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
Mar 11 20:46:07 typhon dotnet[2563980]:    at System.Linq.GroupedEnumerable`2.GetEnumerator()```

**Comment by niksedk** [comment]
OK, thanks for the info. Could you get a bit more details about libse error?

**Comment by BryanJacobs** [comment]
Sorry, I'm trying to be a good bug reporter but I don't know much about dotnet applications. I wouldn't know where to start with packaging a patched version of this library for testing myself, although it looks like an easy fix right after the "hack for unit tests" in the configuration class.

**Comment by BryanJacobs** [comment]
FYI, running a test app shows that `Environment.SpecialFolder.ApplicationData` resolves to `$HOME/.config` in my environment under mono, but I don't know how to test it under `dotnet`.

**Comment by BryanJacobs** [comment]
Thank you so much @niksedk !

Whenever the next release comes out, hopefully I'll be able to use Jellyfin again.

**Comment by niksedk** [comment]
I've added a nuget 3.6.11 package (well, tried at least): https://www.nuget.org/packages/libse/

**Comment by BryanJacobs** [comment]
And what do you know, building jellyfin against that resolves the problem with libse!

Perhaps the problem was some previous version of the code, or maybe what you pushed up as "3.6.11" already included the above commit?

**Comment by niksedk** [comment]
Cool it's working again :)

Yes, what I pushed as "3.6.11" was latest src (so it's technically 3.6.11+)
