### ISSUE TITLE
Whisper speech recognition bug

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [SubtitleEdit/subtitleedit#6732]
I noticed that whenever I'm using the Whisper speech recognition model, the subtitle appears before the speech. See the image below:
![image](https://user-images.githubusercontent.com/35394195/224505064-96a4b383-7920-403c-aa86-5dfa2f28aed4.png)
As you can see, `- They weren't configured for landing.` appears after `- The flaps are up too.`, but before they actually say it. Is there a way to make the subtitles appear during the speech, and not before or after?

**Comment by darnn** [comment]
Not at the moment, at least not in SE. WhisperX is supposed to be more accurate, but I haven't tried it myself, and in any case it's still not _very_ accurate, just more than the regular one. You need to wait until either Whisper itself improves, or someone makes a fork or an addon that will correct the timing separately. The technology does exist, ostensibly (look up VADs if you want), but I haven't seen anyone actually make something ready to use that automatically corrects subtitles that only roughly correspond to the actual audio.

**Comment by Andrei-Iosifescu123** [comment]
It is accurate, but the timing is wrong. Vosk has correct timing, but is
not so accurate.

sâm., 11 mar. 2023, 21:02 darnn ***@***.***> a scris:

**Comment by darnn** [comment]
I just tried Vosk, and frankly, it didn't even recognize half the audio Whisper (Const-me) recognized. And even then, it wasn't so accurate that it's worth the tradeoff. Anyway, you can try to experiment with these:
https://huggingface.co/spaces/aadnk/whisper-webui
https://colab.research.google.com/github/ANonEntity/WhisperWithVAD/blob/main/WhisperWithVAD.ipynb

**Comment by niksedk** [comment]
This is a Whisper issue - sometimes the large model is a bit better, sometimes not.

SE actually supported WhisperX for a while... but I could not make it work well at all.

SE also has some post adjustments of timestamps if complete silence between text.

**Comment by darnn** [comment]
Is there a build with whatever WhisperX support there was enabled? I'd love to see it, even if it doesn't work well, because I haven't been able to get it to run myself at all.
