### ISSUE TITLE
"Max. number of lines" can not be increased above 25

### ISSUE THREAD

**Issue by homunet** [SubtitleEdit/subtitleedit#6733]
in the "General" section of "Setting", there is "Max. number of lines" setting.
Under the version 3.6.11, this parameter cannot be changed more than 25.
I need it permit more lines in one subtitle line.

**Comment by niksedk** [comment]
What max value do you need?

You can add more lines - use "Ctrl+Enter" to force a new line.

**Comment by homunet** [comment]
Hi.
It depends.
But at least 100, I need.
I put some notes in srt lines when editing and after remove them by a script.

**Comment by homunet** [comment]
I suppose that it does not required the limit of limit.
