### ISSUE TITLE
Provide default shortcut list on web for documentation + as an overview of what's possible

### ISSUE THREAD

**Issue by qubodup** [SubtitleEdit/subtitleedit#6735]
The search feature in the app is great but being able to find stuff online is also great and hopefully semiautomatically achievable.

Here is an example of what a good shortcut resource looks like: https://helpx.adobe.com/premiere-pro/using/keyboard-shortcuts.html

Because of the non-distinctive name, searching for "SubtitleEdit Shortcuts" currently leads to other sofware's hotkey lists.

This is basically https://github.com/Aegisub/Aegisub/issues/300 but without me having found a way to workaround. I use both tools.

**Comment by niksedk** [comment]
LOL, I posted in Aegisub... 

Is that something you could make?
Could be extracted from this window: 
![image](https://user-images.githubusercontent.com/1261331/224541013-fe29ca84-fbf6-4a25-861c-7033810279a9.png)


The most basic shortcut are listed here: https://www.nikse.dk/subtitleedit/help#shortcuts

**Comment by niksedk** [comment]
OK, how is this?
![image](https://user-images.githubusercontent.com/1261331/224553531-c6d3cfc5-21c9-43c9-8dbc-8f95ff76641e.png)

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

[SE_Shortcuts.zip](https://github.com/SubtitleEdit/subtitleedit/files/10951219/SE_Shortcuts.zip)

**Comment by niksedk** [comment]
ping @qubodup

**Comment by qubodup** [comment]
Oh cool, I didn't realize there was an xml export already for example. I'd expect this kind of stuff as a separate button (perhaps next to [search] [clear] [import/export v]) over there:
![image](https://user-images.githubusercontent.com/18312/224770539-c5813a7a-bd36-4927-8c51-d70f8a6e0c10.png)

It's certainly cool to have this in the app (although if one already knows where to find the shortcut info and that the context menu allows export, one might just stickt to searching there). – I was thinking that the important part would be to have this list online for all to search and find, who are still learning/checking about the capabilities of SubtitleEdit or are not yet comfortable enough with it to know or get used to the in-options-search.

So it'd be best if an export could be present near https://www.nikse.dk/subtitleedit

I don't know what the export looks like but for maximum usefulness, I would suggest that the exported table first only lists all commands that have shortcuts present and then, below with a different heading, lists all commands that *could* have a shortcut. This way, people might find out about the *capabilities* of SE by searching there or on search engines.

Of course I understand that having to take care of keeping one more html page might be unwelcome.

Side note, if suggestions for new defaults are accepted - I'd suggest CTRL ALT S as "save as". Most apps use "CTRL SHIFT S" but that one's reserved and at least Notepad++ also uses CTRL ALT S for "save as".

**Comment by niksedk** [comment]
Website updated:
https://www.nikse.dk/subtitleedit/help#shortcuts

**Comment by niksedk** [comment]
It's not perfect, but it's easy to update :)
Also - feel free to improve: https://github.com/SubtitleEdit/subtitleedit/blob/main/src/ui/Forms/Options/Settings.cs#L3423

>CTRL ALT S as "save as"

Thx, done :)

**Comment by qubodup** [comment]
Very cool!

There are some issues with escape characters perhaps and splits:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/18312/f9c02662-2703-41f4-98ae-61d6b6ee3c66)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/18312/a1561f53-7a19-4046-95a6-7c54c8d0599c)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/18312/9e18798f-fa84-44e1-97a7-8535dd357f14)

Also confused that some have [None] and others are empty.

I saw some manual html encoding going on - perhaps https://learn.microsoft.com/en-us/dotnet/api/system.web.httputility.htmlencode?view=net-7.0 can help (but perhaps that adds dependencies to annoying runtimes? IDK, all I know about C# is a little Unity 3D coding.)
