### ISSUE TITLE
[Linux BUG] Whisper does not launch

### ISSUE THREAD

**Issue by Lindere31** [SubtitleEdit/subtitleedit#6736]
Hi, when I try to generate the subtitles this error message appears

![SE Whisper Linux Bug](https://user-images.githubusercontent.com/70165850/224554222-9ef3a9fb-4ce8-429d-9dd3-494878a6f6f5.PNG)

**Comment by niksedk** [comment]
Thanks for the info... my computer is not quite right, and will not run VirtualBox atm, so... help wanted.
(I cannot fix this with my current computer)

**Comment by scribblemaniac** [comment]
I encountered the same error attempting to use whisper.cpp. It appears that Subtitle Edit does not make any effort to download the third-party tools on Linux, so you must manually install them into the PATH. For me the process went something like this:
- Clone [the whisper.cpp repository](https://github.com/ggerganov/whisper.cpp)
- Run `make` in the repository directory
- Symlink the resulting `main` executable to somewhere on the PATH (for me /usr/local/bin) with the name `whisper`.

Now the CPP option should work in Subtitle Edit on Linux. It is likely a very similar process for the other tools. It would be nice if this was all automated like on Windows.
