### ISSUE TITLE
Netflix QA button missing

### ISSUE THREAD

**Issue by qubodup** [SubtitleEdit/subtitleedit#6737]
3.6.11 portable win

The netflix quality check button is enabled but not present in the toolbar

![image](https://user-images.githubusercontent.com/18312/224554478-3943e13f-b914-4098-927c-635d768c0b32.png)

If intentional, perhaps it should be greyed off/out when not available if enabled to be shown

Cheers!

**Comment by niksedk** [comment]
It's always available in the tool menu:
![image](https://user-images.githubusercontent.com/1261331/224556913-2e519aac-8ce6-4172-8df9-f77e10f95353.png)

It's only visible for "Netflix timed text" + "EBU STL" I think... this part was actually coded by Netflix.
