### ISSUE TITLE
Multi Split/Merge

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#6738]
I realized that you can't make a selection and split more than one subtitles at one time. If more than one subtitles are selected, Split disappears from right click.
Also, split could use some enhancements. Things like split after a character like . or , or ? or even a line break. I was thinking of another something like "Split lines containing" but I assume if multi split is placed, then we can make a selection with whatever containing and then split those. 

With merge, select multiples and merge them. Merge Selected Lines shortcut only works with two lines.

**Comment by darnn** [comment]
Split is one thing and auto break is another. You can select several subtitles and then press your keyboard shortcut for auto break, and it will be applied to all of them.

**Comment by uckthis** [comment]
@darnn you're very bright.
