### ISSUE TITLE
Enhanced capabilities for subtitle burned-in video generation.

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#6739]
When I generated the video, I found that the encoded video format changed from High to Main.

![image](https://user-images.githubusercontent.com/54498172/224559071-a8ec4e4e-6c34-440d-ac86-96ac2ebb4668.png)

Can more encoder options be provided to improve video compression quality? For example, like _Handbrake_ or _OBS_, or allow free filling of _FFmpeg_ parameters.

**Comment by niksedk** [comment]
This is meant to a be a very simple encoder. FFmpeg has like 50 different settings for each encoder! See https://github.com/SubtitleEdit/subtitleedit/issues/6684

I could make a custom field where anything could be added...

SE also has this in latest beta (right-click on the "Generate button"):
![image](https://user-images.githubusercontent.com/1261331/224618038-4d5a1783-577d-4ab9-be6e-e49374864202.png)

**Comment by Mishasama** [comment]
> This is meant to a be a very simple encoder. FFmpeg has like 50 different settings for each encoder! See #6684
> 
> I could make a custom field where anything could be added...
> 
> SE also has this in latest beta (right-click on the "Generate button"): ![image](https://user-images.githubusercontent.com/1261331/224618038-4d5a1783-577d-4ab9-be6e-e49374864202.png)

Great! But it may not be perfect for 2-pass? Because it looks only shows up the first pass parameter.

**Comment by niksedk** [comment]
You will get the dialog twice for a two pass encoding (well, if the parameters for first pass was valid)
