### ISSUE TITLE
Burned-in video generate UI bug

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#6740]
When I choose copy, the bit rate can still be selected. And the 2-pass total bit rate can't update until selecting another audio bit rate.
![image](https://user-images.githubusercontent.com/54498172/224560611-26be2f5c-eb7e-4acd-9419-d793fcb3e89d.png)

**Comment by niksedk** [comment]
Thx :)
Is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by Mishasama** [comment]
> Thx :) Is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/54498172/225116475-1fe8f316-407a-4806-a821-cd814a33ae70.png)

Yes. Maybe you can fix this text styling issue as well.
