### ISSUE TITLE
Request to add a shortcut that toggles this ( ) on a word plz

### ISSUE THREAD

**Issue by HadiSparrow** [SubtitleEdit/subtitleedit#6744]
Hi
I have a request to add a shortcut that toggles this ( ) on a word plz
in the next update if possible
like this
Hadi ---> (Hadi)

**Comment by niksedk** [comment]
Try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/224986684-2bb1a906-8dea-4c28-8b33-d82924168d48.png)

![image](https://user-images.githubusercontent.com/1261331/224986876-2e19c52f-4598-46d8-b2b7-585b1dc9d03f.png)
