### ISSUE TITLE
Vosk Model Filesize is very small

### ISSUE THREAD

**Issue by o-data** [SubtitleEdit/subtitleedit#6746]
I download the Vosk large model and look at the Model folder but it is very small, I'm expecting it to be 1GB+ but it all only ~50MB or so.

Which one of the following I theorize is correct

- the model filesize written incorrect?
- compression?
- model is in some other folder instead of /Vosk/
- Some Subtitle Conversion that reduce the filesize?
- My download is corrupted

Anyone can share their expertise?

**Comment by o-data** [comment]
@niksedk You too quick! Screenshot now:

This is what my file look like.
![image](https://user-images.githubusercontent.com/67723461/224982607-c1ad69d4-ee1f-436b-8ddb-b0d6a81b1fa4.png)

These are what being shown in the download:
![image](https://user-images.githubusercontent.com/67723461/224982769-aaa64fd0-2b1b-458c-a9fb-3961baf426b3.png)

I did a test on a French audio and it clearly shown that Subtitle + Vosk working very good but I'm just surprise why the filesize so small. I'm happy it small but I have feeling there is an issue.
![image](https://user-images.githubusercontent.com/67723461/224982929-51e7717b-e76e-4334-a0cc-0bc3442109da.png)

**Comment by o-data** [comment]
> Could you explain exactly what model you're working with? Screenshots always help too.
> 
> The sizes in the download window, is the download size (a compressed zip file).
> 

OK, clearly there something wrong with my version! Let me download the English Large and compare.

**Comment by o-data** [comment]
OK, I think you can disregard this issue. I use Properties and the filesize seem to be more accurate now. It is my File manager.

**Comment by niksedk** [comment]
Cool, matches data here:
![image](https://user-images.githubusercontent.com/1261331/224984444-b9701c80-e6c7-47a5-9a35-b17d2b756299.png)

>PS. THANK YOU FOR CREATING SUBTITLEEDIT!

You're welcome :)
