### ISSUE TITLE
Auto-change app theme depending on system theme

### ISSUE THREAD

**Issue by rakleed** [SubtitleEdit/subtitleedit#6747]
Could you please add auto-change app theme depending on the system theme and make this the default behavior?

**Comment by niksedk** [comment]
Sorry, SE really do not have theming :(

**Comment by o-data** [comment]
Linux version seem to be able to force dark mode somehow @rakleed 
https://github.com/SubtitleEdit/subtitleedit/issues/6736

Maybe you can look into that.
