### ISSUE TITLE
Feature Request: Select nearest subtitle automatically based on audio playhead position, without having to hit play.

### ISSUE THREAD

**Issue by Apocalypse612** [SubtitleEdit/subtitleedit#6749]
The current feature, "Select current subtitle while playing" is excellent, but having an additional option to automatically select the subtitle based on the cursor position in the audio timeline would be even better (instead of arbitrarily having to hit play to get the subtitle selection update).

I can tell where I want my start and stop break points just by looking at the waveform, in a lot of cases. Having to hit play to get it to update just slows down my workflow.

Please consider. Thanks!

**Comment by niksedk** [comment]
Perhaps some of these?

![image](https://user-images.githubusercontent.com/1261331/225215022-be798538-b1da-467a-a69f-3e0d24b107b8.png)

**Comment by Apocalypse612** [comment]
Quite a bit different than what I described above. A feature for automatic functionality would be better. Thanks for pointing that out, though.

**Comment by niksedk** [comment]
OK, could you clarify a bit?

**Comment by Apocalypse612** [comment]
![image](https://user-images.githubusercontent.com/6374154/225379446-8eddf66a-fe5a-4b21-b05d-a66bc46d13db.png)

The command listed in this screenshot, above the audio timeline, if you can alter the behavior or add another option to do the following: have it automatically select the closest subtitle based upon where the play head currently is resting, in behavior other than when hitting the play/pause button, but also when you click around the timeline with the mouse, for example.

**Comment by rRobis** [comment]
I thought about this too.

Basically now you have to double-click on the subtitle to select it, or press "play" (if "Select current subtitle while playing" is checked).

There could also be a checkbox, that would say: "Select current subtitle when playhead overlaps" (or something like that).

Basically if playhead overlaps a subtitle, even though it's not playing at the moment, it would select that subtitle, without double clicking on the subtitle.

I guess it's not a big problem to double click, but it would be really helpful in situation, when you just scroll through the subtitles, and do an overview.

Currently the preview subtitles in video player are changing while scrolling, but textbox subtitles are staying the same.

**Comment by SrimanNarayanaSangha** [comment]
I had the exact same idea. I also think it is slowing down my workflow and wanted to raised this feature request as well.

**Comment by LeonCheung** [comment]
I always have this enabled, if that helps here:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/95ec20d8-5258-40b5-bb7b-57748d688462)

**Comment by SrimanNarayanaSangha** [comment]
Thank you!! That is exactly what I was looking for. But there is still one thing missing for me... When toggling play (control p), it does not play from the selected subtitle, or where the waveform was clicked. 

Example: I am editing a subtitle, I hear that the previous one was wrong, so I do alt+up to go the the previous one (or click the previous subtitle/waveform), fixed it and click ctrl+p to toggle play, but then the video begins from where it was, and not from the current selected subtitle.

**Comment by LeonCheung** [comment]
@SrimanNarayanaSangha then you may want to set two more shortcuts for the typical case:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/854f392a-f7e8-43a8-b70b-e2fbc90318fe)

**Comment by SrimanNarayanaSangha** [comment]
Thanks a lot Leon Cheung, that will improve my work flow!

**Comment by Apocalypse612** [comment]
Thank you!
