### ISSUE TITLE
Replacing default icon?

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#675]
I noticed how gray and outdated icon that represents program looks. 

So, I took the liberty of asking icon designer **Philippe Hong** make new, better one.
He agreed and only asked to credit him.

I hope you'll accept this, and replace that old gray icon with new, modern one

![subtiteeditor](https://cloud.githubusercontent.com/assets/72777/6882505/637f9d32-d587-11e4-9c30-b2e4c8516fe8.png)

My apologies, I don't know how to add .ico through github, so I hosted it on box
.ico file is here:
https://app.box.com/s/ookg1eksrx8q95yyd4q7jm2498qzlqws

**Comment by diomed** [comment]
@niksedk  What are your thoughts on this suggestion?

**Comment by niksedk** [comment]
Sorry, I'm not really too impressed... does not really look like an icon. Also tried to add it to an exe file - did not look pretty...

**Comment by diomed** [comment]
@niksedk 

How about this one:
![Imgur](http://i.imgur.com/YNV7Onm.png)

https://app.box.com/s/5k9y6swf9lqoknp9brmpuffosftr7dhd

**Comment by Betsy25** [comment]
I like it.

**Comment by diomed** [comment]
@niksedk , please.

**Comment by niksedk** [comment]
Much better than the previous one... still the "SE" text could be a little bigger and the bottom corners looks weird.

**Comment by diomed** [comment]
corners look weird only on png, not on small icon. you can't notice them on smaller sizes on screen.

I doubt anyone uses extra large icon size. on large size it looks okay.

**Comment by niksedk** [comment]
Also just got this one:
![Imgur](SubtitleEdit Icon-1024.png)

**Comment by LeonCheung** [comment]
@niksedk Nice. BTW, your avatar image can be another nice option. LOL

**Comment by niksedk** [comment]
He, yes - just took the worst image I could find - I think I'm eating :)

**Comment by diomed** [comment]
How about this one

![se ico](https://cloud.githubusercontent.com/assets/72777/11014539/4f09d8f4-853b-11e5-9489-5c494ded63e7.png)

[icon file](https://app.box.com/s/6ckef7bh6aeq4md540jep9thumdnxxh2)

**Comment by diomed** [comment]
3 years have passed since my suggestion, latest version being this one, sent to you via gitter in January:
![SE icon](https://files.gitter.im/SubtitleEdit/subtitleedit/nfDe/s.e.png)

do you have any wish at all to change default icon or is this gonna remain the same old grey one forever?

**Comment by diomed** [comment]
shall we see program getting new icon in any foreseeable future?

**Comment by diomed** [comment]
shall we see program getting new icon in any foreseeable future?

**Comment by diomed** [comment]
shall we see program getting new icon in any foreseeable future?

**Comment by diomed** [comment]
shall we see program getting new icon in any foreseeable future?

**Comment by OmrSi** [comment]
Now this is a beautiful one: 
![subtitleedit](https://user-images.githubusercontent.com/20923700/49287133-04ac9300-f4a5-11e8-832c-b7e0c23b1021.png)

**Comment by diomed** [comment]
This is one of the most disappointing threads I've ever started in my life.
After more than 3 and a half years no suggestion was taken into consideration,
no release was tried out with any of icons, and even when owner said he would, he didnt, 
and now you suggest monochrome / gray version again, and I'm trying to escape from it to colors.

oh well... F this

 (╯°□°）╯︵ ┻━┻

**Comment by OmrSi** [comment]
Well, If you don't like the colors, some of us do. 
I'm only suggesting it because it's what shows up when you search for "Subtitle Edit".

And what is up with this aggressive tone of yours?
"The owner" doesn't work for you... we only suggest and he decides what is best for HIS program.

Some people are just...weird!

**Comment by OmrSi** [comment]
The point is that it is close to the original but with a new material design that goes with the current systems design.

**Comment by Ding-adong** [comment]
@diomed You can make up your own icon and put it in the SE program file folder. Use filetypesman software to change the default icon to your icon. No need to wait for anyone else.

I am happy with the present one. Much better than the crappy icons inside SubtitleEdit.resources.dll

**Comment by Ding-adong** [comment]
I never notice the icon on the top left corner until now, ha ha ha.

**Comment by OmrSi** [comment]
I'm currently using this one and I like it a lot:
![screenshot 179](https://user-images.githubusercontent.com/20923700/52504039-f4750a80-2bef-11e9-84ad-a5e7a4fee962.png)

**Comment by ArtexJay** [comment]
IMO the best looking icon was the very first. I put it into a tile and looks amazing. way better than the original or other icons suggeted

**Comment by ArtexJay** [comment]
someone made this
![SubtitleEditLargeTile scale-125](https://user-images.githubusercontent.com/32932497/56476225-c8cd9680-6462-11e9-8cf7-22d5509cf2b4.png)

**Comment by Ding-adong** [comment]
Last two pics above.
1st - yuk.
2nd - too laughable, a 5 year old child can do better.

**Comment by amirrammari** [comment]
+1

**Comment by OmrSi** [comment]
Changed to: 
![image](https://user-images.githubusercontent.com/20923700/107876340-10da6a80-6ece-11eb-91e0-05902a474ac9.png)

**Comment by niksedk** [comment]
Yes, very different colors for sure, but shape and letters are still the same :)
Some reactions might come due to this been different, sure.

IMO it looks good in the taskbar and with dark mode (the previous icon not so much).

Good work by @LeonCheung <3
