### ISSUE TITLE
Feature Request: Add feature to merge every following line with same speaker identification into one block

### ISSUE THREAD

**Issue by eplinux** [SubtitleEdit/subtitleedit#6754]
Dear all,

as I was battling with my interview transcripts, I stumbled upon this wonderful peace of software that helped me convert my .ass formatted transcript into something more useful (srt) while retaining the speaker information. While I was playing around with the batch conversion options, there was one option I actually missed. Next to merge short lines & remove lines with style / actor, It'd be super helpful to have a conversion option that allows you to joing following lines based on speaker (or actor identification). In the following, I'll give you an example:

```
`1`
00:00:01,540 --> 00:00:07,399
[SPEAKER0]: Ich hoffe, dass ich das irgendwie
hinterherverwerten kann, weil dieses Mikrofon irgendwie nicht

2
00:00:07,400 --> 00:00:08,520
[SPEAKER0]: sehr gut auf.

3
00:00:09,800 --> 00:00:17,800
[SPEAKER0]: Ja, kannst du mir am Anfang
kurz ein bisschen was über dich erzählen?

4
00:00:18,400 --> 00:00:21,161
[SPEAKER0]: Wie alt du bist und
woher du kommst, was du so machst?

5
00:00:24,800 --> 00:00:25,800
[SPEAKER1]: Ja.`

```
into:

```
`1
00:00:01,540 --> 00:00:21,161
[SPEAKER_0]: Ich hoffe, dass ich das irgendwie hinterherverwerten kann, weil dieses Mikrofon irgendwie nicht sehr gut auf. Ja, kannst du mir am Anfang kurz ein bisschen was über dich erzählen? Wie alt du bist und woher du kommst, was du so machst?

2
00:00:24,800 --> 00:00:25,800
[SPEAKER1]: Ja`
```

**Comment by antoineyb17** [comment]
That would be awesome indeed. I also use Subtitle Edit for interview transcripts, and being able to merge all following lines until a change of actor occurs would be life-changing. One less complicated solution could be to make the "Merge all selected line'' feature work (as right now I don't think we can use it for more than two lines). 

Hope it'll be the case soon!

**Comment by eplinux** [comment]
@antoineyb17 for now, I'm just using a chatgpt-written python script that works okay for my purposes on srt files generated by whisperX:

`import sys
import re

# Get input file name from command line argument
input_file = sys.argv[1]

# Open input file
with open(input_file, "r") as f:
    lines = f.readlines()

# Initialize variables for merging lines
current_speaker = None
current_text = ""
start_time = None
end_time = None
counter = 1

# Create output file name
output_file = input_file.split(".")[0] + "_merged.srt"

# Open output file
with open(output_file, "w") as f:
    for line in lines:
        # Check if line contains speaker identification
        match = re.match(r"\[(.+)\]: (.+)", line)
        if match:
            speaker = match.group(1)
            text = match.group(2)

            # Check if speaker has changed
            if speaker != current_speaker:
                # Write merged lines to output file
                if current_speaker is not None:
                    f.write(str(counter) + "\n")
                    f.write(start_time + " --> " + end_time + "\n")
                    f.write("[" + current_speaker + "]: " + current_text.strip() + "\n\n")
                    counter += 1

                # Initialize variables for new speaker
                current_speaker = speaker
                current_text = text
                start_time = None
                end_time = None

            else:
                # Merge line with previous line
                current_text += " " + text.strip()

        else:
            # Check if line contains time stamps
            match = re.match(r"(\d\d:\d\d:\d\d,\d\d\d) --> (\d\d:\d\d:\d\d,\d\d\d)", line)
            if match:
                start_time = match.group(1)
                end_time = match.group(2)

    # Write last merged lines to output file
    f.write(str(counter) + "\n")
    f.write(start_time + " --> " + end_time + "\n")
    f.write("[" + current_speaker + "]: " + current_text.strip() + "\n\n")
`
