### ISSUE TITLE
Add option to change search engines

### ISSUE THREAD

**Issue by Keddyan** [SubtitleEdit/subtitleedit#6756]
When I'm on the Spell Check window, there's an option to "google it" if I don't know the word in question of something,.

But I don't use Google, I prefer DuckDuckGo, and others might prefer other search engines like Qwant, Searx, Bing, Startpage, etc.

I couldn't find any setting for it nor an issue here on github se that's why I'm opening this one, hope it's in the right place

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

You can now right-click on the search button:
![image](https://user-images.githubusercontent.com/1261331/226159460-e9975cc1-3394-440d-b285-416f7bf233ac.png)


You can setup your favorite search engine here:
![image](https://user-images.githubusercontent.com/1261331/226159492-9b856324-3977-4de4-bd25-8ae0589c8348.png)


How does that work for you?

**Comment by o-data** [comment]
Here hoping you support offline/local dictionary in future.

**Comment by niksedk** [comment]
> Here hoping you support offline/local dictionary in future.

Just make your own local site :)
