### ISSUE TITLE
Another TimerTextUndoTick error

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#6758]
![se undo tick](https://user-images.githubusercontent.com/19672444/226024744-2cfddb1c-e651-4e2b-8f48-9ca45eb07550.png)

**Comment by niksedk** [comment]
Steps to re-create?

**Comment by niksedk** [comment]
Is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

**Comment by darnn** [comment]
It didn't happen very frequently before, so I'll assume it is for now, and let you know if anything changes.
