### ISSUE TITLE
[Question] How to update Vosk/Whisper Model and see "New Version"

### ISSUE THREAD

**Issue by o-data** [SubtitleEdit/subtitleedit#6759]
I see that there was a recently beta commits for Whisper update, but how can I tell what my current version is or do I need to update the Vosk/Whisper model?

Do we just re-download it?

I see that Vosk have version number but Whisper does it. Or does Whisper is consider AI Model complete and no further model will be train or update?

Thank you

**Comment by niksedk** [comment]
Normally SE will prompt you for updating.

Updating manually is naturally a bit complicated... 

For OpenAI whisper, you can update use their update doc: https://github.com/openai/whisper

If you want a cutting edge version of Whisper CPP or Whisper Const-me, you can download their binaries and unpack to where SE unpack their files. But it might not work, as parameters could have changed.
The same goes for Vosk/Kaldi.
Read more here: https://www.nikse.dk/subtitleedit/help#audio_to_text
