### ISSUE TITLE
Batch convert errors

### ISSUE THREAD

**Issue by martinjgrunwald** [SubtitleEdit/subtitleedit#6765]
When I try to batch convert multiple files I get Errors. I want to batch remove text for HL. Under Status it says failed and in the bottom left hand corners it has a red error counter. My error_log.txt however doesn't give an error description, it just says how long it took

edit: it seems to be an error overwriting certain files. Saving them in a different folder solves it

**Comment by niksedk** [comment]
I think this issue is fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.11/SubtitleEditBeta.zip

Something like this was fixed a few weeks back...
