### ISSUE TITLE
[Feature request] Move last word to/fetch first word from next subtitle - option to extend to further subtitles

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#6766]
I often find myself in situations like this:
![image](https://user-images.githubusercontent.com/19672444/226716900-a16e3345-7267-458b-ad8e-7d6a913b7fcf.png)

Where I want to get both "one second" and "thank you" into subtitle 4 (leaving all timecodes as they are). If they were in subtitle 5, I could use "fetch first word from next subtitle". But since they're several lines down, I have to go to line 8, cut the text, paste it into line 7 after the text that's already there, then select all the text there, cut it and then paste it into line 4. But if "fetch first word from next subtitle" could apply to the following subtitles as well, I'd just have to press it a few times and it would be much quicker.

**Comment by vaclavmuller** [comment]
![Move words](https://user-images.githubusercontent.com/23431375/228785447-f79317c3-0c8e-4acf-b3e9-9d039e110964.png)

**Comment by darnn** [comment]
Yes, those are the commands I'm talking about. I'm asking for their functionality to be extended beyond just the next subtitle, as I said in my post.
