### ISSUE TITLE
Whisper GPU mode please!

### ISSUE THREAD

**Issue by martjay** [SubtitleEdit/subtitleedit#6778]
The two secondary development than the official practical less memory, faster recognition speed.

https://github.com/ggerganov/whisper.cpp

https://github.com/guillaumekln/faster-whisper

**Comment by niksedk** [comment]
Check SE 3.6.12. It should have both Whisper CPP + Whisper Const-me (GPU)

**Comment by martjay** [comment]
> Check SE 3.6.12. It should have both Whisper CPP + Whisper Const-me (GPU)

My goodness, I'm glad to see this message. Does it support batch video subtitle recognition?

**Comment by martjay** [comment]
> Check SE 3.6.12. It should have both Whisper CPP + Whisper Const-me (GPU)

GPU mode not work

![777777](https://user-images.githubusercontent.com/44982189/227938744-89405bbb-0093-4408-b090-a006d1e4bc56.jpg)

**Comment by niksedk** [comment]
Yes, click on "Batch mode" for batch mode:
![image](https://user-images.githubusercontent.com/1261331/227974906-df2d34d3-16f5-43da-a6d2-9d86c5c93d99.png)
