### ISSUE TITLE
New fix errror option for lines that go over the media duration

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6779]
It's fairly okay when the subtitle exceeds the media length for formats like SRT and many others. But there can be certain formats (or certain platforms) that will ignore such lines when importing, even with a very tiny excess. Maybe we could have a new fix error option for that? Usually, it could be the very last line of a subtitle.

**Comment by niksedk** [comment]
> I second this. Syntax coloring is supposed to color lines exceeding the entered optimal sreading speed, but unfortunately, this doesn't happen. When translating or proofreading, I need to check line by line and look specifically in the right corner above the text box to see if I need to edit something, which is tiring.

SE check the "Max chars/sec":

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/251930bf-b1db-42d2-88fe-c102216abf2a)

Shown in "list view" and "Error list" (Ctrl+F8)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/ad47127f-d55d-456e-83e7-dd966e2010d3)

**Comment by LeonCheung** [comment]
@niksedk Sorry for the very late reply. XD

I mean, say, the video is 01:00:00 long, but if the very last line exceeds that, which end time is 01:00:01 (for example), or the very first line starts before 00:00:00, it would cause a problem when uploading to some platform (causing it not displaying on the screen). This was a real case that happened to me once.
