### ISSUE TITLE
Selected lines > Audio to text (Whisper) seems to load the model again and again for each line

### ISSUE THREAD

**Issue by dezea** [SubtitleEdit/subtitleedit#6780]
Using the same feature for Vosk, it only loads the model once and then it goes to transcribing every selected line.
But when using Whisper with selected lines, it seems to load the model for each line which of course is way too slow (I haven't checked the code, but I can't find any other reasons for that lag - I have a decent system amd 7950 + nvidia 3060 gpu)

**after some more digging, this seems to happen only when using the C++ version, I know that's supposed to be slow anywway, but it's way slower in the selected lines mode than using Video>Audio to text directly**

**Comment by rsmith02ct** [comment]
![Screenshot 2023-03-27 20 53 42](https://user-images.githubusercontent.com/122251109/227934603-89832ce0-acbc-4bf3-ac56-0220eef5a5c4.png)
I'm having an odd issue Const-me- it says loading and then downloads it but can't seem to find it per the screenshot here. I restarted SE and it prompted me again to download. If I go to Const-me and then click on CPP and back it prompts me yet again.

**Comment by niksedk** [comment]
@dezea: Yes, this is true. SE just uses command line, so the model will be reloaded each time. I guess the tiny/small model is recommended for "selected lines"...

**Comment by dezea** [comment]
@niksedk Thank you for your reply and for the greatest subtitle editor of course. This feature is very useful in my worflow because I am using subtitles already made for other languages in order to more acurately grab the actual speech sections. This makes both Whisper and Vosk much more accurate and outputing a minimum number of garbage lines and halucinations.
I'll have at look at the code, maybe I can work out something. If not, a feature using directly the open AI whisper paid model which is quite cheap and fast might be a solution too. I used it and subtitled a lot of stuff with the free credits.

**Comment by dezea** [comment]
Is there a fix planned for this?  I had a look at the source code and the relevant code seeems to be here: "\src\ui\Forms\AudioToText\WhisperAudioToText.cs" The issue is that the model is loaded for each line, which is inefficient. To optimize it, 

1. Declare the `WhisperAudioToText` object outside the loop to avoid loading the model multiple times:

WhisperAudioToText whisper = new WhisperAudioToText(); 

2. Move the initialization of the model and other settings to the constructor or a separate initialization method:

private void InitWhisper()
{
    string modelPath = GetModelPath(); // path to Whisper model
    string languageCode = GetLanguageCode(); // language code
    bool translateToEnglish = checkBoxTranslateToEnglish.Checked;
    bool usePostProcessing = checkBoxUsePostProcessing.Checked;

    whisper.InitializeWhisper(modelPath, languageCode, translateToEnglish, usePostProcessing);
}
```

3. Modify the `GenerateBatch` method to use the initialized `whisper` object:

private void GenerateBatch()
{
    // ...

    InitWhisper();

    // ...

    foreach (ListViewItem lvi in listViewInputFiles.Items)
    {
        // ...

        var waveFileName = videoFileName;

        _outputText.Add(string.Empty);
        var transcript = TranscribeViaWhisper(waveFileName, whisper);
        if (_cancel)
        {
            // ...
        }

        // ...
    }

    // ...
}
```

4. Modify the `TranscribeViaWhisper` method to accept the `whisper` object as a parameter:

public List<ResultText> TranscribeViaWhisper(string waveFileName, WhisperAudioToText whisper)
{
    // ...

    var process = whisper.GetWhisperProcess(waveFileName, OutputHandler);
    
    // ...

    while (!process.HasExited)
    {
        // ...
    }

    // ...
}
```
Like this, `WhisperAudioToText` object is initialized once and reused for each line, avoiding the overhead of loading the model multiple times. This should significantly improve the costs of electric bills for many people.

**Comment by niksedk** [comment]
> Is there a fix planned for this? I had a look at the source code and the relevant code seeems to be here: "\src\ui\Forms\AudioToText\WhisperAudioToText.cs" The issue is that the model is loaded for each line, which is inefficient. To optimize it,
> 
>     1. Declare the `WhisperAudioToText` object outside the loop to avoid loading the model multiple times:
> 
> 
> WhisperAudioToText whisper = new WhisperAudioToText();
> 
>     2. Move the initialization of the model and other settings to the constructor or a separate initialization method:
> 
> 
> private void InitWhisper() { string modelPath = GetModelPath(); // path to Whisper model string languageCode = GetLanguageCode(); // language code bool translateToEnglish = checkBoxTranslateToEnglish.Checked; bool usePostProcessing = checkBoxUsePostProcessing.Checked;
> 
> ```
> whisper.InitializeWhisper(modelPath, languageCode, translateToEnglish, usePostProcessing);
> ```
> 
> }
> 
>     3. Modify the `GenerateBatch` method to use the initialized `whisper` object:
> 
> 
> private void GenerateBatch() { // ...
> 
> ```
> InitWhisper();
> 
> // ...
> 
> foreach (ListViewItem lvi in listViewInputFiles.Items)
> {
>     // ...
> 
>     var waveFileName = videoFileName;
> 
>     _outputText.Add(string.Empty);
>     var transcript = TranscribeViaWhisper(waveFileName, whisper);
>     if (_cancel)
>     {
>         // ...
>     }
> 
>     // ...
> }
> 
> // ...
> ```
> 
> }
> 
>     4. Modify the `TranscribeViaWhisper` method to accept the `whisper` object as a parameter:
> 
> 
> public List TranscribeViaWhisper(string waveFileName, WhisperAudioToText whisper) { // ...
> 
> ```
> var process = whisper.GetWhisperProcess(waveFileName, OutputHandler);
> 
> // ...
> 
> while (!process.HasExited)
> {
>     // ...
> }
> 
> // ...
> ```
> 
> }
> 
> Like this, `WhisperAudioToText` object is initialized once and reused for each line, avoiding the overhead of loading the model multiple times. This should significantly improve the costs of electric bills for many people.

SE cannot load the model only once for selected lines (as with Vosk/Kaldi) as each selected line results in a command line call... it's not SE that loads the model, but the command line.
You can use the tiny or small models which load really fast...

**Comment by dezea** [comment]
I see, I think I get it now, I thought it was used via library not command line. But can't whisper.cpp do that though? This would eliminate the overhead of external command and will be faster even without gpu for that application (transcribe via selected lines) 

Because I really needed this, I've done a litte python script that does just that which worked fast enough for me for now, if anyone is interested: https://github.com/dezea/subtransx/tree/main
