### ISSUE TITLE
Question: is there a way to copy a selection of subtitles and paste it later with the relative timings intact? 

### ISSUE THREAD

**Issue by pradeipp** [SubtitleEdit/subtitleedit#6782]
Use case - while creating subtitles for a song. If I have added chorus lyrics subtitles with 8 text entries and timestamps, is there a way to repeat them later in the song?

**Comment by OmrSi** [comment]
Go to source view, paste them at the end of the file, return to list view, sort by start time.

**Comment by OmrSi** [comment]
You mean paste it and keep the durations?
Click on the line that comes before the new section, go to the place on the waveform where the first line of the selection will start, focus on the waveform, paste.
