### ISSUE TITLE
Issue with the color #ff00ff (bright pink) 

### ISSUE THREAD

**Issue by Nitah123** [SubtitleEdit/subtitleedit#6786]
Hello, 

I use subtitle edit for work and I often have to use the mentioned color code (#ff00ff). The problem is, I cannot create a shortcut for this specific color, as the "pink" that is specified in the shortcuts has a different color code. I would greatly appreciate it, if this color code could be added to the color-shortcuts like yellow, cyan, green etc.

**Comment by niksedk** [comment]
In the file `Settings.xml` you can set a color value for the 8 custom colors:

````xml
    <Color1>Yellow</Color1>
    <Color2>#FF0000</Color2>
    <Color3>#00FF00</Color3>
    <Color4>Cyan</Color4>
    <Color5>Black</Color5>
    <Color6>White</Color6>
    <Color7>Orange</Color7>
    <Color8>Pink</Color8>
````

You can open the folder with `Settings.xml` by pressing `Ctrl+Shift+Alt+D` in the SE main window.

And then you can setup a shortcut for your color;
![image](https://user-images.githubusercontent.com/1261331/228292562-d236466d-6192-4861-867b-6441da7dcc36.png)

**Comment by Nitah123** [comment]
Thank you so much for your reply! I managed to get to the Settings.xml, but when I changed the color code for lets say "<Color8>Pink</Color8>" to "<Color8>#FF00FF</Color8>" and saved it didn't work. Do you have any suggestions, why this could be the case?

**Comment by niksedk** [comment]
Works fine here... make sure SE is closed while editing Settings.xml.

![image](https://user-images.githubusercontent.com/1261331/228659247-d6865019-4632-4c39-82c7-d2314422dca5.png)

**Comment by Nitah123** [comment]
Thank you, it worked now. I had subtitle edit open before, when I tried to change the color.
