### ISSUE TITLE
Issue with settings

### ISSUE THREAD

**Issue by JDTR75** [SubtitleEdit/subtitleedit#6787]
Hello! I'm getting error dialogs whenever I change something in the settings, whether it's a profile selection or changing from milliseconds to frame and viceversa. I just click on ignore twice and nothing happens but I thought it's worth mentioning.

![image](https://user-images.githubusercontent.com/1891941/228258134-0d83c459-41ae-4445-9105-889c4dcc43ab.png)

**Comment by niksedk** [comment]
Thanks for the info - could you email or attach your Settings.xml file?

**Comment by JDTR75** [comment]
Here it is. This started happening when I updated to the newer version 3.6.12. I'm currently using Beta 3 and it's still happening, just fyi.

[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/11092319/Settings.zip)

**Comment by niksedk** [comment]
Thx for the settings.xml file :)
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
