### ISSUE TITLE
possibility of using Whisper on a portion of a video

### ISSUE THREAD

**Issue by amirbahalegharn** [SubtitleEdit/subtitleedit#6789]
Sometimes The whisper in SE make error in it's translated srt sub that it made, so if  SubtitleEdit can implement an option for a segmented video portion from time X to Z where those corrupted speech-to-text has happened with repeated invalid subs and let the new generated subs from that portion be synced & put in the right timeline in the already made sub , that would be awesome. because then the transcription time would be much less than doing the whole video and possible same outcome.

[[no subs]30 Made ni to Urusakute 2022 Jdrama.zip](https://github.com/SubtitleEdit/subtitleedit/files/11094627/no.subs.30.Made.ni.to.Urusakute.2022.Jdrama.zip)

Thanks in advance for all your efforts all these years with such splendid software

**Comment by williethewolf** [comment]
This is already an option.

Selectect the messed up lines or Delete the text that is bad (make a timeline selection of the portion to transcribe and "add text here").

Right click on the lines to retranscribe>Selected lines>Audio>Audio to text (Whisper)

**Comment by darnn** [comment]
Also, if you have, for instance, a ten-minute chunk in the middle of a 90-minute video file, you can create a new empty subtitle in your file, set the start time as the time where the issue starts, and set the end time as the time it ends (so you'd have a ten-minute-long subtitle). Then right-click that subtitle, and click Selected lines->Audio->Extract audio. Now either open another instance of SE, or just WhisperDesktop (or any other version of Whisper), and recognize the resulting audio file again. Shift the timecodes of the subtitles you got to match the timecodes in your original file. You can do this by opening the ten-minute subtitle file in the new instance of SE, and opening the video you're working on, navigating to the timecode where the first subtitle starts and using the "set start and offset the rest" keyboard shortcut.
Now copy the subtitles from the new file, go back to the original SE window, go into source view using the keyboard shortcut, and paste your new subtitles where appropriate. Go back to list view. If you care about the numbering of the subtitles, you can now use Tools->Renumber to fix it.
The reason you can't simply paste the subtitles in listview is that currently SE modifies the timecodes of subtitles pasted this way.
Anyway, it might sound a bit cumbersome, but this is what I do, to avoid running Whisper separately on each subtitle, which takes a long time.

**Comment by niksedk** [comment]
Should be fixed via: https://github.com/SubtitleEdit/subtitleedit/issues/8109#issuecomment-2036828916

**Comment by rRobis** [comment]
If there is no subtitle inserted, the whisper option appears, but it's not possible to run whisper. 

Theoretically could just click "Insert text here" and then run whisper on newly created subtitle that is exact size of the selection. Would be perfect if this could happen automatically.

If there is empty subtitle inserted, then it works as expected

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/928422a5-b100-45b4-b95a-4a6715182ff6)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/5b92485b-5a65-4091-ae22-7697572f7d76)
