### ISSUE TITLE
FEATURE REQUEST: Groupings for Multiple Replace tool

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#679]
Any chance you can add groupings to Multiple Replace tool? With names for each group, and checkmarks for both the whole group and individual actions inside the group.

**Comment by xylographe** [comment]
In addition, it would be nice if groups could be (optionally) language dependent. Perhaps, by adding the three letter ISO language name as a postfix to the group name,
- Foo
- Foo[fra]
- Foo[nld]

The second and third group would be automatically disabled (unchecked) if the current subtitle is not French or Dutch, respectively. The first group would be language independent.

**Comment by niksedk** [comment]
See https://github.com/SubtitleEdit/subtitleedit/issues/1803
