### ISSUE TITLE
Any plan to support chatgpt api to do translation?

### ISSUE THREAD

**Issue by wuzimi** [SubtitleEdit/subtitleedit#6794]
The default google auto translation is not good. Do you have any plan to support translation through chatgpt api?
The translation quality is much better. Thanks for consideration.

**Comment by niksedk** [comment]
Sorry, no. They don't really have an API for that: https://platform.openai.com/overview
You can always use the Copy-paste-translate:
![image](https://user-images.githubusercontent.com/1261331/229043119-a5308344-075b-4282-856e-524128dc32b4.png)


You can also try to plugin DeepL - See File - Plugins.

**Comment by wuzimi** [comment]
Thanks for your reply. I tried the copy/paste feature but don't understand
how to do it. Also I googled it and found nothing about its introduction.
Could you pls tell me more about it?
Thanks!

Nikolaj Olsson ***@***.***> 于 2023年3月31日周五 14:41写道：

**Comment by niksedk** [comment]
Copy-paste feature:

Go to Auto-translate - Auto-transla via copy-paste
Set the line split to an empty string
Click on "Translate"
![image](https://user-images.githubusercontent.com/1261331/229106034-02eed7ec-490a-4e70-9527-b27647d8b3bb.png)


Go to OpenAI ChatGPT
Ask for tranlslation to e.g. Danish:
![image](https://user-images.githubusercontent.com/1261331/229106550-adbd861a-f8de-4f93-8ef4-c03b259c1b97.png)

Copy the text to the clip-board:
![image](https://user-images.githubusercontent.com/1261331/229106763-c29c617d-4b99-49f6-93b4-4ee9995b1a20.png)

Press the big button in SE:
![image](https://user-images.githubusercontent.com/1261331/229106867-3c338f3d-f3ee-4dc1-8784-1de2c125618c.png)

![image](https://user-images.githubusercontent.com/1261331/229107138-1682b2ca-50cb-4af3-b9b2-4884d57f6e41.png)

**Comment by wuzimi** [comment]
Thanks!

Nikolaj Olsson ***@***.***> 于 2023年3月31日周五 19:23写道：
