### ISSUE TITLE
[Feature request]Use Whisper to align pure text lines subtitle with audio/video file with the timeline

### ISSUE THREAD

**Issue by pendave** [SubtitleEdit/subtitleedit#6799]
I update SE to the latest version with Whisper, tha't gorgeous! If it possible to expand the ability for this requirement:

Sometimes I do hand-split the text-only captions (not pleasure with the machine-split captions), pure text line by line, Then I goto Tencent Zhiying（腾讯智影） or Jianying（剪映）to let it add timelines for each line of subtitles automatically.
![image](https://user-images.githubusercontent.com/1331881/229329542-e0d2ff7c-de8e-4fc1-b6fe-44ad0e612483.png)
![image](https://user-images.githubusercontent.com/1331881/229329634-d6f2d828-7e3f-4748-8e4f-1ec7787a1ce3.png)

I guess Whisper with some script could do this kind of work as well, it will be cool!

**Comment by pendave** [comment]
I don't know if it possile, now I find the Whipser generated subtitle is not that precise at line level. I have to check and align each subtitle manually.

![FNOS3_NI`WD_ 92G8GSRG3F](https://user-images.githubusercontent.com/1331881/229330474-6fd8cedc-1fdd-4b6d-9eaa-9f91fdac26c3.png)

**Comment by darnn** [comment]
Do these have an actual English interface somewhere? I poked around to try and find one, but couldn't.

**Comment by pendave** [comment]
> Do these have an actual English interface somewhere? I poked around to try and find one, but couldn't.

https://zenvideo.qq.com/

![image](https://user-images.githubusercontent.com/1331881/229548240-622df317-da87-4f33-9c70-34b1a5bdf11b.png)

I have no idea if there's English interface, I wonder you could use some webpage translation extensions.

**Comment by xiaopeng12138** [comment]
whisper x has a word by word transcript, maybe that can help?
