### ISSUE TITLE
Unocode Not Support

### ISSUE THREAD

**Issue by ShanLLLL** [SubtitleEdit/subtitleedit#6802]
My language is sinhala. new update not support to mu language. because some letters mix. can you fix it soon. Please..

**Comment by niksedk** [comment]
Could you add some screenshots?

**Comment by ShanLLLL** [comment]
This is photo of my error.can you see the some letters mixed

The correction  -ඔව්. ඔයා මට සමාව දෙනවද?

**Comment by niksedk** [comment]
@ShanLLLL: You need to attach the image on the Github website (email attachements are not shown here on Gitub)

**Comment by ShanLLLL** [comment]
This is photo of my error.can you see the some letters mixed

The correction  - මේ වික්ගේ සහෝදරිය 
![Screenshot 2023-04-04 172013](https://user-images.githubusercontent.com/129832142/229782851-6a910480-5c78-48cf-8a6b-0cacd13aae20.png)

**Comment by ShanLLLL** [comment]
can you help us.Please

**Comment by niksedk** [comment]
Sorry, I don't think I can do anything about this :(
