### ISSUE TITLE
Option Find and Find/Replace focus

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#6803]
This is not related to the latest version 3.6.12, it is common for all versions. The problem is when you use the option Find or Find/Replace in SE, that dialog has the full focus, and you can't go anywhere when this dialog window is open. Problems: 
1. Option Find. This option finds only one occurrence of the desired word or letter(s) and disappears. In MS Word, you can change the word you find and you can find all occurrences of this word. This is the case with hall other kinds of programs. They have some arrows and you can jump from one occurrence of that word to another until you see them all. And the focus can be changed if you double-click on some other thing, the find dialog window doesn't stop you from doing this. You can even minimize the window while the found dialogue window is open. If you want to do anything, you must close this dialogue first. This is not practical. 

2. Option replace. The problem with Replace is the same. It has the full focus, you can't simply find something in the subtitle to edit (some other thing), to click on the subtitle and focus to be in that subtitle. You simply can't go out of the Replace dialogue. If you want to edit something you didn't see is wrong, you must close Replace dialogue window, then edit, and reopen the dialogue window. It gives no comfort during work. 

If I wasn't clear, I want to focus to be removed from the Find/Replace dialogue, so I can minimize the whole SE window, do whatever I want, like editing a line of subtitle, without losing the Find/Replace dialogue, it should stay until I give it focus again. Option Replace in MS Word works like that. I can change anything while the dialogue Replace is open, and to do what I need, then go back to the Replace dialogue. In SE, you can't do anything while Replace dialogue is opened. The focus stays on it. You can't go to change a subtitle line (this is so natural if you find some error), and then continue to find/replace some other occurrences of some term or word. 

In the picture, I showed how I want to go to this area (see the arrows) to edit subtitles, but I can't, because Replace dialogue has a constant focus, and I can see some errors, but I can't go out of the dialogue. It simply won't let me. This is a very big restriction, I want to go where I want while Replace dialogue is opened, edit what I want, then go back to this Replace dialogue, like it is the case in any other program. Or I want to minimize the window of the program, without the need that I have to close dialogue Replace first. 

I use the term FOCUS and DIALOGUE as the programmers do. 

 
![Find and Replace](https://user-images.githubusercontent.com/128191515/229857984-ef4d9d82-74e3-496d-9ad9-dcebd23fbab2.jpg)

**Comment by niksedk** [comment]
OK, pretty huge change (in code lines)... how is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by Cyberyoda1411** [comment]
It works just fine. Find/Replace let me go and minimize the window, go to change some mistakes in the subtitle, and then go back to Find/Replace dialogues. So, you fixed everything: focus, I can find all occurrences of some word, not just one, and then the dialogue closes (find option). Everything looks just fine. 
One step forward. Your program deserves to be better every day.

**Comment by OmrSi** [comment]
@niksedk Could there be a way to make `Escape` close the window after using `Find`?

**Comment by niksedk** [comment]
@OmrSi: I think so... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
(seems search/replace lost focus - hopefully fixed now)

**Comment by OmrSi** [comment]
@niksedk Yeah, it works better now. The beeping thing persists, though.
This will take some getting used to. :D

**Comment by niksedk** [comment]
@OmrSi: thx, hopefully better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by jmaraujouy** [comment]
@niksedk 

In earlier versions, when you clicked _Find_ (or used the keyboard shortcut _Ctrl+F_), the search window would appear, and the focus was on the search window's input box.

This was the default behavior with the _Find & Replace_ window as well.

This was extremely useful because we only had to click Ctrl+F, and we could start typing the term to search directly. Everything was done with the keyboard.

In the latest versions, when calling the search window, the focus is no longer on the input box by default. When you press Ctrl+F, you then have to click inside the input box to be able to start typing the term to search for.

Is this change due to the modifications raised in this topic?
