### ISSUE TITLE
advanced sub station generate background

### ISSUE THREAD

**Issue by eagleftw023** [SubtitleEdit/subtitleedit#6805]
when i try to generate backgroung from assa tolls and then generate background box it give me this error everytime 

![image](https://user-images.githubusercontent.com/130007636/230237718-5a530228-a25c-4ff4-ac9e-ffa2921ee713.png)

**Comment by niksedk** [comment]
Could you translate the text after "Error message:" to English?

**Comment by eagleftw023** [comment]
Parameter is invalid
