### ISSUE TITLE
.ts error

### ISSUE THREAD

**Issue by hepalin** [SubtitleEdit/subtitleedit#6806]
There's a problem opening some .ts files. 

Error report:

System.NullReferenceException
Message: Objektin viittaukseksi ei voi määrittää objektiesiintymää.
StackTrace:    kohteessa Nikse.SubtitleEdit.Core.ContainerFormats.TransportStream.TransportStreamParser.Parse(Stream ms, LoadTransportStreamCallback callback)
   kohteessa Nikse.SubtitleEdit.Core.ContainerFormats.TransportStream.TransportStreamParser.Parse(String fileName, LoadTransportStreamCallback callback)
   kohteessa Nikse.SubtitleEdit.Forms.Main.ImportSubtitleFromTransportStream(String fileName)
   kohteessa Nikse.SubtitleEdit.Forms.Main.OpenSubtitle(String fileName, Encoding encoding, String videoFileName, Int32 audioTrack, String originalFileName, Boolean updateRecentFile)
   kohteessa Nikse.SubtitleEdit.Forms.Main..ctor()

Btw, thanks for the great program.

**Comment by niksedk** [comment]
Could you link to a .ts file or email me a link/file?

**Comment by hepalin** [comment]
Hi!

Here is a file: https://drive.google.com/file/d/1zwgPqCvBTXjrvEPUV5M_r8JXNvgK97GR/view?usp=share_link

Thanks!

**Comment by niksedk** [comment]
Thx for the file :)

Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Fix via this commit: https://github.com/SubtitleEdit/subtitleedit/commit/8d33ff3aad34149611c7fd7af2ffb016d4cf8844
Also added ".tts" as known video file ext

**Comment by hepalin** [comment]
Now it's working. Thank you very much!
