### ISSUE TITLE
Error on import ssa styles

### ISSUE THREAD

**Issue by librafrog** [SubtitleEdit/subtitleedit#6808]
Similar to IS's #5489 & #6477 I'm getting an error when importing ssa styles. Attaching picture, subs itself & the styles if it helps.
![image](https://user-images.githubusercontent.com/79138819/230572256-39abe015-3b04-428d-bf02-254c80692b45.png)
![image](https://user-images.githubusercontent.com/79138819/230572644-95c69670-9a4e-4995-8a33-2d856799515b.png)

[ssa-import.zip](https://github.com/SubtitleEdit/subtitleedit/files/11177341/ssa-import.zip)

###### Using version 3.6.12

**Comment by niksedk** [comment]
Thx for the info + files :)

Hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
