### ISSUE TITLE
Ability to only extract text based subs from CLI and not OCR image based subs.

### ISSUE THREAD

**Issue by dystopia2017** [SubtitleEdit/subtitleedit#6809]
Hello, My TV recordings have two sets of subtitles in them 888 subs which are text based subtitles and DVB subs which are image based.
When I run the following command 

`SubtitleEdit /convert !input! subrip`

SubtitleEdit will OCR the image based DVB subs and output them to filename.srt
and then after this it will deal with the 888 subs and output them to filename.888.srt
the DVB OCR job takes a couple of mins and the 888 takes a couple of seconds.

Is there some command I can run from CLI to ONLY do the 888 to srt conversion
and skip the DVB OCR job altogether? I ran

`SubtitleEdit /convert /list`

To look at the supported conversion list from the CLI but see no mention of Teletext or 888 subs.
But I know they are supported because it works with the earlier command

Here is a log and an attached sample, Thanks in advance.

```
S:\>subtitleedit /convert 10s.ts subrip

Subtitle Edit 3.6.4 - Batch converter

Parsing transport stream S:\10s.ts: 100%
Using OCR via tesseract to extract subtitles
OCR... : 100%
Extracted subtitles from file "S:\_Work_\_Records_\Prep\10s.ts"
1: 10s.ts -> S:\10s.en.srt... done.
1: 10s.ts -> S:\10s.887.srt... done.
1: 10s.ts -> S:\10s.888.srt... done.

1 file(s) converted
```

[10s.zip](https://github.com/SubtitleEdit/subtitleedit/files/11177400/10s.zip)

**Comment by niksedk** [comment]
Would `subtitleedit /convert 10s.ts subrip /teletextonlypage:888` be an okay syntax?

Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by dystopia2017** [comment]
Thanks very much niksedk the syntax is great and it works great
Thanks again :)
