### ISSUE TITLE
Rather cryptic crash of whisper/main.exe. Something wrong with my comp configuration?

### ISSUE THREAD

**Issue by nms42** [SubtitleEdit/subtitleedit#6810]
![Screenshot 2023-04-07 at 12 16 59](https://user-images.githubusercontent.com/3739370/230583503-a3836db1-3f70-41d7-bc5d-52b4223f09f9.png)

**Comment by niksedk** [comment]
Probably a cpu issue... could you supply your cpu info? Perhaps something from https://www.cpuid.com/softwares/cpu-z.html

**Comment by nms42** [comment]
For the record -- dependency of main.exe

```X:\exe\SubtitleEedit-3.6.12\Whisper>dumpbin /dependents main.exe
Microsoft (R) COFF/PE Dumper Version 14.35.32216.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file main.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    whisper.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    KERNEL32.dll

  Summary

        1000 .data
        1000 .pdata
        6000 .rdata
        1000 .reloc
        1000 .rsrc
       10000 .text
```

**Comment by niksedk** [comment]
OK, it *might* a lack of AVX(2) support on your cpu...

Does this whisper run any better?  https://github.com/SubtitleEdit/support-files/blob/master/whisper/whisper.cpp-64-SSE2-2023-01-28.zip

**Comment by nms42** [comment]
Yes! It does.

```X:\Common\tmp\whisper.cpp-64-SSE2-2023-01-28>main.exe
error: no input files specified

usage: main.exe [options] file0.wav file1.wav ...

options:
  -h,        --help              [default] show this help message and exit
  -t N,      --threads N         [4      ] number of threads to use during computation
  -p N,      --processors N      [1      ] number of processors to use during computation
  -ot N,     --offset-t N        [0      ] time offset in milliseconds
  -on N,     --offset-n N        [0      ] segment index offset
  -d  N,     --duration N        [0      ] duration of audio to process in milliseconds
  -mc N,     --max-context N     [-1     ] maximum number of text context tokens to store
  -ml N,     --max-len N         [0      ] maximum segment length in characters
  -bo N,     --best-of N         [5      ] number of best candidates to keep
  -bs N,     --beam-size N       [-1     ] beam size for beam search
  -wt N,     --word-thold N      [0.01   ] word timestamp probability threshold
  -et N,     --entropy-thold N   [2.40   ] entropy threshold for decoder fail
  -lpt N,    --logprob-thold N   [-1.00  ] log probability threshold for decoder fail
  -su,       --speed-up          [false  ] speed up audio by x2 (reduced accuracy)
  -tr,       --translate         [false  ] translate from source language to english
  -di,       --diarize           [false  ] stereo audio diarization
  -otxt,     --output-txt        [false  ] output result in a text file
  -ovtt,     --output-vtt        [false  ] output result in a vtt file
  -osrt,     --output-srt        [false  ] output result in a srt file
  -owts,     --output-words      [false  ] output script for generating karaoke video
  -ocsv,     --output-csv        [false  ] output result in a CSV file
  -of FNAME, --output-file FNAME [       ] output file path (without file extension)
  -ps,       --print-special     [false  ] print special tokens
  -pc,       --print-colors      [false  ] print colors
  -pp,       --print-progress    [false  ] print progress
  -nt,       --no-timestamps     [true   ] do not print timestamps
  -l LANG,   --language LANG     [en     ] spoken language ('auto' for auto-detect)
             --prompt PROMPT     [       ] initial prompt
  -m FNAME,  --model FNAME       [models/ggml-base.en.bin] model path
  -f FNAME,  --file FNAME        [       ] input WAV file path
```

**Comment by niksedk** [comment]
OK, then you'll have to settle with this probably very slow version as your CPU does not support AVX(2).

I don't know if you can run the Const-me version? (right-click in the Whisper window or click on the right-top gray label)

**Comment by nms42** [comment]
> then you'll have to settle with this probably very slow version as your CPU does not support AVX(2).

That is not cryptic, when explicitly informed!

> I don't know if you can run the Const-me version? (right-click in the Whisper window or click on the right-top gray label)

Same windows error window with error 0xc0000142

Can openblas cope with lack of AVX(2)? Not at full throttle, I guess

**Comment by niksedk** [comment]
You can check the "error_log.txt" in the SE data folder (press Ctrl+Shift+Alt+D in the main se Window)

**Comment by niksedk** [comment]
I've tried to compile latest whisper.cpp here:
[whisper-cpp-latest.zip](https://github.com/SubtitleEdit/subtitleedit/files/11179401/whisper-cpp-latest.zip)

Better?

**Comment by nms42** [comment]
> I've tried to compile latest whisper.cpp here: .... trying ...

Still error 0xc0000142

**Comment by niksedk** [comment]
[Whisper-Cpp-2023-04-07.zip](https://github.com/SubtitleEdit/subtitleedit/files/11179484/Whisper-Cpp-2023-04-07.zip)

**Comment by nms42** [comment]
> You can check the "error_log.txt" in the SE data folder (press Ctrl+Shift+Alt+D in the main se Window)

Correction the error(?) window in SE with text "No text found!"

The contents of error_log.txt
```
Date: 04/07/2023 17:15:49
SE: 3.6.12.0 - Microsoft Windows NT 10.0.19044.0 - 64-bit
Message: Calling whisper (CPP) with : X:\exe\SubtitleEedit-3.6.12\Whisper\main.exe --language ko --model "X:\exe\SubtitleEedit-3.6.12\Whisper\Models\small.bin" --output-srt --print-progress --max-len 76  "C:\Users\nms\AppData\Local\Temp\0c67fd14-5507-4f90-ab6b-efbd50fc296d.wav"
Calling whisper CPP done in 00:00:01.8184488
Loading result from STDOUT
```

**Comment by nms42** [comment]
> Yes, previous build was still with AVX2... this should be just SSE2: [Whisper-Cpp-2023-04-07.zip](https://github.com/SubtitleEdit/subtitleedit/files/11179484/Whisper-Cpp-2023-04-07.zip)

That works

**Comment by nms42** [comment]
> Yes, previous build was still with AVX2... this should be just SSE2: [Whisper-Cpp-2023-04-07.zip](https://github.com/SubtitleEdit/subtitleedit/files/11179484/Whisper-Cpp-2023-04-07.zip)

Can it be dropped into SE 3.6.12?

**Comment by niksedk** [comment]
> > Yes, previous build was still with AVX2... this should be just SSE2: [Whisper-Cpp-2023-04-07.zip](https://github.com/SubtitleEdit/subtitleedit/files/11179484/Whisper-Cpp-2023-04-07.zip)
> 
> Can it be dropped into SE 3.6.12?

I should think so...

**Comment by nms42** [comment]
> > Yes, previous build was still with AVX2... this should be just SSE2: [Whisper-Cpp-2023-04-07.zip](https://github.com/SubtitleEdit/subtitleedit/files/11179484/Whisper-Cpp-2023-04-07.zip)
> That works

No! That does not work. Falls flat without a sound/text ;-(

```
X:\Common\Projects\Speech\se>main.exe -pp -l korean -m ..\Models\small.bin -osrt ..\e01.wav
whisper_init_from_file_no_state: loading model from '..\Models\small.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 3
whisper_model_load: mem required  =  608.00 MB (+   16.00 MB per decoder)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     =  464.56 MB
whisper_model_load: model size    =  464.44 MB
whisper_init_state: kv self size  =   15.75 MB
whisper_init_state: kv cross size =   52.73 MB

X:\Common\Projects\Speech\se>
```

**Comment by nms42** [comment]
> ggerganov said that it needs "AVX + FMA + F2C", could it be compiled with AVX but without "FMA + F2C"?

At compile/build time *nix makefile automagically checks for workbench CPU capabilities and produce right binary. Actually SSE capability is the real minimum. The problem is the lack of such makefile for ms windows workbench.

I assume visual studio .sln stuff needs manual tuning for not so bleeding edge CPUs.
