### ISSUE TITLE
SE voice to text engines as separate applications

### ISSUE THREAD

**Issue by nms42** [SubtitleEdit/subtitleedit#6811]
No flashy windows, no bells and whistles. Just command line, so it can be compiled for macos, linux, freebsd, plan9(?), ...

**Comment by nms42** [comment]
Found ggerganov/whistler.cpp at github. Are there any compatibility requirements with SE?

**Comment by niksedk** [comment]
Yes, the different whisper versions (openai, cpp, const-me etc.) are just cmd line without bells and whistles - SE just call the command line.
Whisper CPP in SE is just from ggerganov/whistler.cpp
