### ISSUE TITLE
how to bacth remove text for hearing impaired..?

### ISSUE THREAD

**Issue by TimucinPusat** [SubtitleEdit/subtitleedit#6814]
there are lots of subtitles files which contain text for hearing impaired. I want to remove them all in once. Is it possible?

**Comment by niksedk** [comment]
Sure, see Tools - Batch convert...

![image](https://user-images.githubusercontent.com/1261331/230785229-8cc2fc01-1dd5-4af4-94cc-da74291f5f11.png)

**Comment by TimucinPusat** [comment]
> Sure, see Tools - Batch convert...
> 
> ![image](https://user-images.githubusercontent.com/1261331/230785229-8cc2fc01-1dd5-4af4-94cc-da74291f5f11.png)

Waaaw that's great @niksedk. I didn't realize that this option is there even I look quickly a few times. But I don't want it to convert I just want to remove HI. It doesn't ruin the other text while batch removing the text for HI since it will convert even it's the same fromat SubRip, does it? By the way are you the developer of subtitle edit software?

**Comment by niksedk** [comment]
You can use "Save in source folder" + "overwrite files" to keep the "same" files (if output format is the same as input format).

If you're unsure, it always good with a backup :)

Yes, I'm the main dev, but lots of people has helped with this project! 90 people has committed to this repository and many more have reported bugs/suggestions.

**Comment by TimucinPusat** [comment]
I got it. I tried it and the result is successful. I can't thank you and your team enough. It's a great program, great. I use it for language learning. It makes my work very easy. Thank you very, very much.
