### ISSUE TITLE
Can new version have more suitable video navigation buttons, forward/backward (buttons and keys)

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#6817]
I know that SE has the video window has **<<** and **>>** buttons for navigation through the video (plus-minus 3 seconds per click), but these buttons are too small and very inconvenient for work, they are too far from each other. I like that you choose the jump of 3 seconds, instead of 5 or 10. It is better and more precise. 

![Screenshot_2](https://user-images.githubusercontent.com/128191515/231325270-31435ba2-4d63-45a2-a370-3647c8299a65.jpg)

There are two solutions, and I'd like, if you can, you to do both, I think it won't be a lot of programming work. Every player has both options: buttons for that skip and can use arrows on the keyboard. 

1. I tried, and the **arrow buttons on the keyboard** can't make a video skip for 3 seconds forward/backward, and this option would be more than great. This option is more than standard for all kinds of players. That is, the Left/right arrows on the keyboard produce 3 second forward/backward jump, and the up/down arrows make the sound volume up/down. 

2. The second option is to put the **buttons on the video window** in SE. Button < and >. See in the picture, just put these buttons in a better place and make them bigger (and closer to each other). 

![Screenshot_1](https://user-images.githubusercontent.com/128191515/231325427-ec859c10-1295-476b-8b59-d2e3ed76a9af.jpg)

This is how this looks on the real player, GOM player plus.

![SKIP BUTTONS](https://user-images.githubusercontent.com/128191515/231324145-6af4d0db-7a04-4956-a218-767642936285.jpg)

I know that users are full of ideas, but the standard things are standard things. I use your program more often and I see more things that are not user-friendly. It is not 'can you do this', and this,..., it never stops. This is a standard feature and it is more than useful in your video window. With the present solution in SE, any navigation is not comfortable. You must have a sniper gun to hit very small double arrows on the video window and the distance between two buttons is too wide.

**Comment by GrampaWildWilly** [comment]
![#01](https://user-images.githubusercontent.com/75588964/231339074-939d80b8-41d5-4273-901f-058b392b6eb9.jpg)

**Comment by Cyberyoda1411** [comment]
Yes, this is some kind of solution. But, it is not so comfortable to use function keys on the keyboard, instead of having keyboard arrows up/down for volume, and left/right for the skip forward/backward for 3 seconds. And to have two buttons on the video window in SE, bigger and closer to each other. If Nikolay already made two small buttons, he can put them in some other position without any problem. That position is on the right of the volume scroller, that is, in the middle of the lower position of the window. 

This program is getting better by having some original and some STANDARD options. If we have a video window, it should have standard behavior: arrows on the keyboard to produce skipping for 3 seconds and two buttons on the window for the same purpose. 

The last thing I suggested was related to find/replace options. Nothing weird, just a STANDARD behavior for that options. And Nikolay did it successfully. Now he has the program that acts as Wordpad. To find all occurrences of some word, to replace some word with another one, and to let the user go out of the window find/replace, not to be captured in it. 

The closer SE is to the standard functionality, the better. And we always have some solutions to make our life easier with some shortcuts. Some general functionality should be present, to give us comfortable work.

**Comment by GrampaWildWilly** [comment]
You say, "it is not so comfortable to use function keys on the keyboard."  I would always prefer to use the keyboard to do anything than to use the mouse.  But I suppose each person has his or her own style.

I've just looked through the keyboard shortcuts & I don't believe any of the arrow keys is assigned to any shortcut by default.  But assigning them to shortcuts could get tricky.  As you well know, the arrow keys navigate around within text, like in the Text Box where a subtitle is displayed.  The UpArrow & DownArrow also navigate through the individual subtitles in List View or Source View.  So the meaning of these keys would depend on the context, that is, which window or pane of SE has focus.  I still say you can assign at least the LeftArrow & RightArrow to two of the shortcuts I show in my image above & it will give you exactly & completely what you want for skipping forward & backward in a video.  I would say the same thing about UpArrow & DownArrow for volume control except it seems there is no shortcut for volume control.  Maybe this is a request to add shortcuts for "raise volume" & "lower volume."

As for the position & size of buttons within the video player, my guess, and I admit I am just guessing, is that Nik  has no control over this.  Your images show you are using the mpv player, if I'm not mistaken.  The controls in the mpv player are, I believe, entirely in the hands of whoever writes & maintains mpv.  That is most decidedly not Nik.  But I could be wrong.  Nik no doubt knows more.

**Comment by Cyberyoda1411** [comment]
I am not a generation who doesn't know what is ctrl + x, s, v, f, But, sorry, I can't see function buttons as comfortable if it is not only one strike if I must use them very often and many strokes repeatedly. If it is used very often, that should be solved in some more practical manner. 

Arrow keys. If you don't click in the TEXT part for editing subtitles, there is no focus on that part of the screen (it is not active) and arrows won't be a problem. Left/right arrow doesn't affect the subtitles (they have the focus), only up/down keyboard buttons (arrows) move the subtitles up and down. 
Of course that Nikolaj can change the button size and position, it is part of any program that has GUI. Finally, if there is no nice solution, it can be a small standard pair of buttons, like OK, cancel,..., but smaller, you can make a button as big as you want. 

Every player has the option skip back, skip forward. KMPlayer, Gom Player (it is on the picture) not mpv, it is from the stone age, POT player, VLC player, every player in the world has that skip option buttons. I don't know why you didn't read my text that I use GOM PLAYER PLUS and in the picture is its title bar. And I don't know why do you mention it, Nikolaj won't write code for the player, but for his program. If there is no collision, left/right key can be used, but the buttons can be used anyway, he can simply remove the other two, very small ones. 

I am sure that Nick has a dozen of possibilities for the buttons he likes. Today, every programming language has a dozen libraries of all kinds.

**Comment by GrampaWildWilly** [comment]
Ah.  Key combinations.  Yes, those would be kind of inconvenient.  But you can assign RightArrow, not Ctrl+RightArrow, not Alt+RightArrow, just RightArrow by itself to one of the skip forward shortcuts.   And LeftArrow by itself to one of the skip backward shortcuts.  Have you tried to do that?  Try it.  Tell us what your experience is.

**Comment by Cyberyoda1411** [comment]
We are both right. 
I also use the keyboard only to navigate through a video. I use arrows. You are right, Alt + arrow is not so complicated to use. I wasn't satisfied with the skip of 0.5 seconds, and I changed the shortcut to 1 second. And it is totally OK and comfortable for work. 
And I am right that Nikolay should make some better buttons for the skip because sometimes it is easier to make many skips with the mouse, that option is totally OK. Sometimes the mouse is already in your right hand, so it is easier to skip that way. 

I will ask Nikolaj, and maybe you know, where the shortcuts are stored in the program. I didn't find any textual file for the configuration, so it must be stored in some dll file. It is pretty boring to set shortcuts for every version of SE from scratch.

**Comment by darnn** [comment]
They're stored in a file called Settings.xml, and you can indeed just copy it over.

**Comment by niksedk** [comment]
Yes, Settings.xml is in the `SE data folder` (press Ctrl+Alt+Shift+D in the SE main window to open this folder).

Just a note: Do not unpack the portable version (or betas) to `C:\Program Files\Subtitle Edit` as this will mess up file permissions. Portable version should be installed to something like `C:\Tools\SE`

**Comment by niksedk** [comment]
If you open the SE video player in full-screen mode, normal video player shortcuts will work (arrow up/down/left/right)

The SE video player gfx is just Windows Media Player from... some really old windows version. New buttons will probably require a new skin (sorry, I'm not good with gfx).

**Comment by Cyberyoda1411** [comment]
Nikolaj, you told me about settings, I hope I can copy my settings in every new installation over the original file. You told me about the new buttons. 

I am totally happy with the option Alt + left (right) in shortcuts. I have only one suggestion. In shortcuts, there are skip options: 100 milliseconds, 500 milliseconds, 1, and 5 seconds. If it is not too much, can you add 3 seconds (three seconds forward/backward), because 1 second is too small step, and 5 jumps are too much. When make a subtitle, 5 seconds bring you too much backward, and 1 second is not enough. Three seconds would be just fine. 

I know that it is not present in players, but it is their big problem. They skip too much backward, that is, 5 seconds. Keep all the other shortcut options, just (if you can) add the new ones, two shortcuts for 3 seconds forward/backward.

**Comment by niksedk** [comment]
New shortcuts added here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
You could also always use the custom timings:
![image](https://user-images.githubusercontent.com/20923700/231585534-c22ec627-fc16-4248-87d3-056792d58807.png)

**Comment by YassirMohammed** [comment]
Like didn't work, plz update
