### ISSUE TITLE
Gridline division

### ISSUE THREAD

**Issue by Jaafar1221** [SubtitleEdit/subtitleedit#6818]
I was wondering if there is a way to change how the waveform gridline is divided, instead of dividing each second to 10 parts, can it be divided according to the time frame of the video. Like in 25 frames, it should e divided into 25 parts, and so forth

**Comment by matmaggi** [comment]
That would be really nice!

But maybe it could change automatically when we select working with milliseconds (every 100ms) or frames (every frame).

**Comment by Jaafar1221** [comment]
yeah, that would be great. maybe some people prefer to work with milliseconds, I actually found a way to implement this change but I wasn't able to make a version of my own, can you help with that?
note: I know how to make it for 25 frames only, but it should be just a simple repeat for other frame rates.
