### ISSUE TITLE
application error in Subtitle 3.6.11.0- MS NT 10.0.19044.0.

### ISSUE THREAD

**Issue by Lennie1200** [SubtitleEdit/subtitleedit#6819]
Error Message: Parse error: input contains no value
![Subtitle](https://user-images.githubusercontent.com/130572403/231473593-58af2843-e38f-4815-9bb2-d2c29a6d98a3.png)

**Comment by Lennie1200** [comment]
Hi Nikolaj,

find attached

thanks
Holger

Mit freundlichen Grüßen

i. A. Holger Albrecht
***@***.***<https://ifm.com/de>
Holger Albrecht
ifm group services gmbh
Friedrichstraße 1
Senior Projektleiter
45128 Essen
IT Demand and
Germany
Project Management
Tel: +49 201 2422-2280
Fax: +49 201 2422-1200
***@***.******@***.***>Contact me on ***@***.***>
E-Mail: ***@***.***

[ifm]<https://ifm.com/>
Sitz der Gesellschaft ist Essen HR B 32929 Amtsgericht Essen
St.-Nr. 112/5779/1682  USt.-ID-Nr. DE 348 579 437
Geschäftsführer: Prof. Dr. Bernd Buxbaum, Steffen Fischer, Thorben Petersen,
Stefan Schneider, Andreas Thürer

***@***.***<https://www.ifm.com/de/de/shared/events/trade-fair/hannover-messe?utm_source=online&utm_medium=DE&utm_campaign=hm-e-mail>
Von: Nikolaj Olsson ***@***.***>
Gesendet: Mittwoch, 12. April 2023 15:42
An: SubtitleEdit/subtitleedit ***@***.***>
Cc: Albrecht, Holger ***@***.***>; Mention ***@***.***>
Betreff: [EXTERNAL]Re: [SubtitleEdit/subtitleedit] application error in Subtitle 3.6.11.0- MS NT 10.0.19044.0. (Issue #6819)


@Lennie1200<https://urldefense.com/v3/__https:/github.com/Lennie1200__;!!OETW8Nl5IZBQFw!hLlDer78I3eyi8f5-n3qUWLL5hZXjG04f6btDD_uwz7CoD6MLYvJN0ftvOrjmT4p0drS0vX1PTJ_ryrQFXd5So15qEw$>: thx for the info - could you attach or email the file that causes this error?

-

**Comment by niksedk** [comment]
Github does not support attachments from email, sorry. 
Please attach the file directly on Github or email it to nikse.dk@gmail.com, thx :)

**Comment by Lennie1200** [comment]
![Subtitle](https://user-images.githubusercontent.com/130572403/231491873-ddd8fbb7-e96c-4f64-8684-a3a15cf57b13.png)
Here it is..

**Comment by Lennie1200** [comment]
here it is

**Comment by niksedk** [comment]
Thx, it works fine here for me... could you try to check for plugin updates: File - Plugins ?

**Comment by Lennie1200** [comment]
Hi Nikolay,


Sorry for the late response. My responsible colleague was unfortunately ill.

Here is the screenshot:

***@***.***


Mit freundlichen Grüßen

i. A. Holger Albrecht
***@***.***<https://ifm.com/de>
Holger Albrecht
ifm group services gmbh
Friedrichstraße 1
Senior Projektleiter
45128 Essen
IT Demand and
Germany
Project Management
Tel: +49 201 2422-2280
Fax: +49 201 2422-1200
***@***.******@***.***>Contact me on ***@***.***>
E-Mail: ***@***.***

[ifm]<https://ifm.com/>
Sitz der Gesellschaft ist Essen HR B 32929 Amtsgericht Essen
St.-Nr. 112/5779/1682  USt.-ID-Nr. DE 348 579 437
Geschäftsführer: Prof. Dr. Bernd Buxbaum, Steffen Fischer, Thorben Petersen,
Stefan Schneider, Andreas Thürer

***@***.***<https://www.ifm.com/de/de/shared/events/trade-fair/hannover-messe?utm_source=online&utm_medium=DE&utm_campaign=hm-e-mail>
Von: Nikolaj Olsson ***@***.***>
Gesendet: Mittwoch, 12. April 2023 19:13
An: SubtitleEdit/subtitleedit ***@***.***>
Cc: Albrecht, Holger ***@***.***>; Mention ***@***.***>
Betreff: [EXTERNAL]Re: [SubtitleEdit/subtitleedit] application error in Subtitle 3.6.11.0- MS NT 10.0.19044.0. (Issue #6819)


Thx, it works fine here for me... could you try to check for plugin updates: File - Plugins ?

-
