### ISSUE TITLE
Bug or just weird regex flavour?

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#682]
The replace function doesn't work (i.e. it doesn't change anything and skips to the next occurrence) when lookahead or lookbehind is used in Find field.

**Comment by niksedk** [comment]
Could you give some examples?
Also, it's probably Microsoft flavour... see more here: http://www.nikse.dk/SubtitleEdit/Help#multiple_replace

**Comment by aaaxx** [comment]
If I try to find one or two words after punctuation at line end (unpleasant line breaks) using this:
`(?<=[,;.:!?])( )([^] ,:;!?]+( [^] ,:;!?]+)?)(\r\n)`
and push them into next line by replacing with this:
`$4$2$1`

... nothing happens when clicking the Replace button.

(Currently I just use a capturing group instead of that lookbehind, but I see no reason why lookarounds shouldn't work.)

**Comment by xylographe** [comment]
Your example works fine in Multiple Replace. Must be a bug in simple Replace.

**Comment by ivandrofly** [comment]
Well, have you tried to remove \r\n

**Comment by xylographe** [comment]
I can confirm it is a bug. The normal Replace works in two steps: regex.Match() and regex.Replace().
To succeed with a look-behind assertion both **should** use the same offset (index) into the text.

Example: `text` == `a b! c\r\nd e.`
The regex.Match() starts at index zero (the 'a' at the start of the text). But regex.Replace() starts at index four (the space after the exclamation mark). Obviously, in the second step the look-behind assertion fails, and nothing is replaced.

**Comment by niksedk** [comment]
Nice regex :)

Should be fixed now... you can compile the source from github or test this portable version: http://www.nikse.dk/SubtitleEdit.zip (beta)
