### ISSUE TITLE
repetition lines 

### ISSUE THREAD

**Issue by eagleftw023** [SubtitleEdit/subtitleedit#6821]
hi 
i got repetition/hallucination lines when trying to transcribe
repeated lines have the same words (it stop transcriping and just list the same words repeated)

**Comment by eagleftw023** [comment]
is there any alternative solution to this ?

**Comment by niksedk** [comment]
You can split the video file in multiple parts... not a good solution I know. 
You can also try with adjusting parameters (requires that you run plain cmd line).

I often see commits that could be tries to address this, like https://github.com/openai/whisper/commit/b0022b3283232b2b9f19262360cd80ec9975aeb4 (or else I'm reading my wishes into this)

**Comment by eagleftw023** [comment]
how can i upade decoding.py like this ?
where i can find the file?
i have subtitile edit for windows

**Comment by niksedk** [comment]
> how can i upade decoding.py like this ? where i can find the file? i have subtitile edit for windows

Try `pip install --upgrade --no-deps --force-reinstall git+https://github.com/openai/whisper.git` i a cmd line. See more here: https://github.com/openai/whisper
