### ISSUE TITLE
Add a shortcut that adds 3 dots at the end of the line

### ISSUE THREAD

**Issue by HadiSparrow** [SubtitleEdit/subtitleedit#6823]
Like this:
But I was

to
But I was...

That would be super helpful

**Comment by rRobis** [comment]
You could use Autohotkey (if you're on Windows), to create your own text expansions or macros for small things like that. It doesn't take much time.

SubtitleEdit.ahk
```
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

; Subtitle Edit Profile

#IfWinActive ahk_exe SubtitleEdit.exe
!.::Send,... ; Mapping Alt+Period to ...  **! - Alt; + - Shift; ^ - Ctrl**
#IfWinActive
```

**Comment by LeonCheung** [comment]
Maybe a bit off here, but if you really want to speed up your specific needs, you may want to have a mouse that can customize many buttons on it. e.g. I have a Razer Naga Pro in hand and it helps me a lot much faster in many use cases besides SE.

![image](https://user-images.githubusercontent.com/494788/233845657-0d53338b-ed73-44c1-9c48-0a4fd8c5a576.png)
![image](https://user-images.githubusercontent.com/494788/233845899-7d63ae8e-67db-476f-a24a-a3b8388ad75b.png)


Of course, there are many other cheaper options. Like the other guys, I'm just telling you another option. Just my two cents. :)

**Comment by rRobis** [comment]
Or Razer Tartarus V2. That one is also very good😄
