### ISSUE TITLE
Fix common errors list

### ISSUE THREAD

**Issue by HadiSparrow** [SubtitleEdit/subtitleedit#6824]
Could you add these 2 things?

1- Fix, after a comma must be a lowercase letters

2- Fix, make every lowercase letter at the beginning of a line, an uppercase letter
(This means: I want the first letter of each subtitle line to start with uppercase)

**Comment by Purfview** [comment]
These are not "common errors".

**Comment by HadiSparrow** [comment]
Then could you plz add a shortcut that do this thing?
I rly need it at my daily work

Best regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by HadiSparrow** [comment]
> These are not "common errors".

Then could you plz add a shortcut that do this thing?
I rly need it at my daily work

Best regards
