### ISSUE TITLE
Add option to remove text between * asterisks * from hearing impaired subtitles

### ISSUE THREAD

**Issue by janot** [SubtitleEdit/subtitleedit#6826]
Would be nice, since quite some subs have them

![Screenshot 2023-04-13 230418](https://user-images.githubusercontent.com/1689966/231882860-7e19a5a6-c095-41a6-8264-b937b0ac1b1d.png)

**Comment by SiaL8er** [comment]
Already possible:
![image](https://user-images.githubusercontent.com/130707737/231886223-86b7d79a-7153-4176-beca-c6447c1eca0c.png)

**Comment by janot** [comment]
oh, thanks! I didn't understand it's possible to not only choose, but also to input symbols there..
