### ISSUE TITLE
Feature Request: Word/Capitalized Case (in the Redo Casing)

### ISSUE THREAD

**Issue by lolipopsz** [SubtitleEdit/subtitleedit#6829]
Can you add a feature for Word/Capitalized Case in the Redo Casing for example:

1. Only change all uppercase lines.
    Before: THIS IS AN EXAMPLE  
    After: This Is An Example

2. Only change all lowercase lines.
    Before: this is an example
    After: This Is An Example

3. Only change all random case lines.
    Before: This IS an EXAMPLE
    After: This Is An Example

Also, feature that can ignore tags like "_italic_ {\i}", "alignment {\an8}" etc and "line break (\N)" in the Redo Casing.

**Comment by niksedk** [comment]
SE beta has improved the "Toogle casing" shortcut, so it also works in the list view (+ with tags): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/232194282-fa170e1a-7355-4c40-a7fa-300b848f0119.png)

**Comment by niksedk** [comment]
Thx for testing... here is more to test: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
Added "Proper Case" to "Redo casing" in "Batch convert"

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
(should be final)
