### ISSUE TITLE
Get plugins list bug

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#683]
Unable to download plug list: mscorlib: Input string malformed
![capturar](https://cloud.githubusercontent.com/assets/7856897/6926048/8f387bf0-d7db-11e4-8ce8-746b334fe444.PNG)

**Comment by niksedk** [comment]
What version of SE are you running?

**Comment by marb99** [comment]
SE 3.4.6

**Comment by Betsy25** [comment]
Can't reproduce here (3.4.6, Win7, default install)
Window opens fine.

**Comment by niksedk** [comment]
Should be fixed by commit 54e6d53231aca314a0026198e04b5bdb6f932c4c - was related to the current users settings (decimal symbol).
