### ISSUE TITLE
max context

### ISSUE THREAD

**Issue by eagleftw023** [SubtitleEdit/subtitleedit#6831]
hi how i can change --max-context to 0 for const me in subtitle edit?
if i cant change it in subtitle edit.exe
how can i change it in visual studio in which page and which command?

**Comment by eagleftw023** [comment]
@niksedk

**Comment by niksedk** [comment]
You could try setting "WhisperExtraSettings" to "--max-content 0" in Settings.xml...

**Comment by niksedk** [comment]
Maybe some more Whisper settings later... atm I can even find any documentation describing the parameters!?
