### ISSUE TITLE
Enhancement for Find/Replace in Translation mode

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6832]
When "**Allow edit of original subtitle**" is enabled, it is very nice to allow to choose the target column: **Original**, **Translation**, or **Both**. Because oftentimes we need to just find/replace on one side.

A humble promo:

![replace](https://user-images.githubusercontent.com/494788/232223557-f0431ecb-a203-45ab-a9d0-4ef1c3474f7d.png)

**Comment by niksedk** [comment]
OK, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
I think it's very nice, just... I found that you can only find one result when choosing **Original only** or **Translation and original**, meaning that you can't skip/jump to the next result by clicking the **Find** button again.

But it works fine with **Translation only**.

**Comment by niksedk** [comment]
Thx for testing - hopefully improved find/replace here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Thx. Two new topics:

1. Shall we remember the last choice? (Imho we should because other options is the same window do)
2. It's a bit interesting for the highlight part display, it seems it goes to the other column. e.g.:

![image](https://user-images.githubusercontent.com/494788/232390134-c687e973-c678-4bba-907e-90ece2cbadb2.png)

So far it seems occuring right after clicking the Yes button below:

![image](https://user-images.githubusercontent.com/494788/232390614-4f0e0f49-bd7b-4162-8e3c-3dcc6e494edc.png)

**Comment by OmrSi** [comment]
@niksedk The empty space in Replace when there is no original subtitle looks very weird, maybe you can leave the combo box visible but grayed out?
