### ISSUE TITLE
Replace all causes main SE window to lose focus

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#6838]
Hi. 3.6.12 NEXT beta 58 (I just checked and it's the same in beta 91 as well). I gather this is a result of the recent changes in the replace function.
Open SE. Open the replace dialogue. Type something in "find what", doesn't matter what. Press "replace all". Click either yes or no in "continue replace". Now click the X to close the replace dialogue. SE loses focus.

**Comment by niksedk** [comment]
Thx for the info - is this better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Seems to be! I'll reopen if I find any other instances of it.

**Comment by darnn** [comment]
Actually, this seems to have broken the regular search function. You type a word in the search window and search for it, and even if it exists in the file, SE doesn't find it. It does find it in the replace window.

**Comment by niksedk** [comment]
thx - better now? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Seems to be. I'll leave it open for now in case I run into any more trouble, but I'm not seeing any at the moment.

**Comment by niksedk** [comment]
Cool, thx for testing... it's a little complex, so I'm sure a few more errors will pop up - hopefully minor.
