### ISSUE TITLE
Quality of "Audio to text" with Whisper has decreased

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6839]
When testing and comparing earlier and later versions of SubtitleEdit, I noticed a decrease in the quality of the result of "Audio to text" with Whisper. 

For this test, I used as older version "SubtitleEdit 3.6.11 NEXT Beta 50", and as newer version "SubtitleEdit 3.6.12 NEXT beta 92".

For this test, I used for both these versions of SubtitleEdit:
--- The CPP engine.
--- Choose language = English.
--- Choose model = "medium.en" (downloaded on 1 February 2023).
--- Checkmark at "Auto adjust timings".
--- Checkmark at "Use post-processing".
--- Max. chars per subtitle line = 77.
--- Only these deviations from the default settings: [Settings/Tools/Auto br:] Checkmark at "Break early for end of sentence"; "Prefer bottom heavy" = 2.5%. (This may not be relevant in this context.)
--- This video: "https://youtu.be/qZ-bifYqK_Q".

Please compare the two attached srt files (in a zip file) that resulted from a test run with the older version and a test run with the newer version, to see in what way the quality has decreased.

[Results with older and newer version of SE.zip](https://github.com/SubtitleEdit/subtitleedit/files/11242700/Results.with.older.and.newer.version.of.SE.zip)

It would be nice if this quality decrease can be undone.

**Comment by niksedk** [comment]
I'm pretty sure this is due to the underlying whisper engine, and has nothing to do with SE.

You will also find that the different Whisper engines will give slightly results.

**Comment by oep42** [comment]
I looked into this some more.

For all today's and yesterday's tests, I use exactly the same Whisper engine and exactly the same Whisper model. See the images below.

![Same Whisper engine](https://user-images.githubusercontent.com/84353335/232509018-48d71f55-3254-4f53-9ff3-d96db8587f0d.png)
![Same Whisper model](https://user-images.githubusercontent.com/84353335/232509140-143d8011-e237-456e-9b55-7aa321629dcf.png)

Today I ran the same tests again as yesterday, this time with the option "Remove temporary files" turned off. 

In the zip file below, are four srt-files that resulted from today's test runs:
--- Temporary result (output of Whisper) with older version of SE.
--- Final result (output of SE) with older version of SE.
--- Temporary result (output of Whisper) with newer version of SE.
--- Final result (output of SE) with newer version of SE.

[New results with older and newer version of SE (with temporary results) (17-4-2023).zip](https://github.com/SubtitleEdit/subtitleedit/files/11251066/New.results.with.older.and.newer.version.of.SE.with.temporary.results.17-4-2023.zip)

I did some comparisons:
--- When comparing the two temporary results, they turn out to be identical. So the srt-files (output of Whisper) that are being post-processed by SE, prove to be idential for the old and the new version of SE.
--- Today's final result (output of SE) with the older version of SE of, proves to be identical to yesterday's final result (output of SE) with the older version of SE.
--- Today's final result (output of SE) with the newer version of SE of, proves to be identical to yesterday's final result (output of SE) with the newer version of SE.

Conclusion: The decrease in quality is caused by the newer version of SE.

(I have to say, that I am quite impressed by how SE improves the "raw" temporary srt-files into the final srt-files.)

Please be so kind to look into this again.

**Comment by niksedk** [comment]
Could you add/link/email the audio file?

**Comment by oep42** [comment]
Please see the zip-file below for the original audio stream.

[This is the original audio stream.zip](https://github.com/SubtitleEdit/subtitleedit/files/11251479/This.is.the.original.audio.stream.zip)

**Comment by niksedk** [comment]
I'm testing a bit... will take some hours as my pc is soo slow...

But I still think this has nothing to do with SE: https://github.com/openai/whisper/discussions/81

**Comment by oep42** [comment]
I think running tests with Whisper again, is looking at the wrong place. I guess that the output of Whisper, i.e. the "temporary results", have been identical in all the test runs I did. (So what is said in openai/whisper#81, is irrelevant here, because there is no variation in the output of Whisper here.)

The only thing that makes sense to test now, is this: Test SEs post-processing for both versions of SE, by giving both versions of SE as input the same "temporary result" file. If the srt-file that results from this post-processing, is identical for both versions of SE, then there is no quality decrease in the newer version of SE. However, if the result of the newer version of SE has a lower quality than the result of the older version of SE, then the quality decrease is caused by the newer version. (For this test, you can use a "temporary result" file that I provided above.)

I am not able to feed SE a "temporary result" file without also running Whisper, so I cannot do this test.

**Comment by oep42** [comment]
Thanks for this info. It is really helpful. 

I now see that speaking about "quality decrease" may have been unfair, because I now found out that the older version creates an erroneus period just after such a weird split, while the newer version doesn't. I am sorry for speaking about "quality decrease" while this was not conclusively the case.

Compared to the newer version, the older version seemed to better handle the weird splits and alone periods in the Whisper output, but this is irrelevant, if Whisper doesn't output such weird splits and alone periods anymore.

Based on the new info about how to prevent Whisper CPP to produce weird splits and alone periods, I did some more testing. I couldn't test this with the older version, because that one doesn't allow to give the value "None" tot "Max. chars/subtitle". So I tested again with the new version, this time with "Max. chars per subtitle line" set to "None".

In the zip file below, are two srt-files that resulted from today's test run:
--- Temporary result (output of Whisper) with newer version of SE (Max. chars/subtitle = None).
--- Final result (output of SE) with newer version of SE (Max. chars/subtitle = None).

[Results with 'Max. chars_subtitle = None' with newer version of SE (with temporary results) (20-4-2023).zip](https://github.com/SubtitleEdit/subtitleedit/files/11290072/Results.with.Max.chars_subtitle.None.with.newer.version.of.SE.with.temporary.results.20-4-2023.zip)

Now I see that Whisper CPP doesn't produce any weird splits and alone periods anymore, and I also see that all "quality decrease problems" that I earlier saw, are solved. Great!


**Additional suggestion**

Now that it is clear that the CPP engine sometimes creates weird splits and alone periods when "Max. chars per subtitle line" is NOT set to "None", it makes sense to change the default value of "Max. chars per subtitle line" from "77" to "None" WHEN the CPP engine is being used. 

Now, every time when I reopen the "Audio to text" dialog box when the engine is CPP, the value of "Max. chars per subtitle line" is automatically resetted to "77". This is impractical when only the value "None" is a 'safe' option when using the CPP engine.

There may be reasons why setting the default value to "None" is not a good idea. If so, please change the "Audio to text" dialog box so that the value of "Max. chars per subtitle line" is NOT resetted to its default value every time that dialog box is reopened (so let it keep its earlier value).

**Comment by oep42** [comment]
> (Perhaps it is a good idea to add an option to SE, to import a srt-file with "raw" Whisper-results [or any "raw" srt-file for that matter], which can then be post-processed by SE.) 

Perhaps it is an idea, to make such functionality accessible via "Batch convert".
