### ISSUE TITLE
Incorrect cutting of video length in the "burned-in subtitles" function

### ISSUE THREAD

**Issue by Alxndr6eo1yG8Lv8AJ0TkliH6** [SubtitleEdit/subtitleedit#6841]
When I try to cut a short video (less than a minute) using the "burned-in subtitles" function with the "from" and "to" parameters, I end up with a video that is several minutes long. The later the fragment I try to cut, the longer the resulting video will be.

For example (let's take a 20-minute source video):

- If I cut a fragment starting at 1 minute and lasting a few seconds, the result will be about a minute long.
- If I cut a fragment at 30 seconds on the 5th minute, the result will be about 5 minutes long.
- If I cut a fragment from the 10th to the 11th minute, the resulting video will be approximately 10-11 minutes long.

In all cases, the fragment is cut starting from the correct timecode, but it is much longer than necessary.

I am using Windows 10, MKV and MP4 formats, Subtitle Edit 3.6.12 portable build.

(Off-topic: I really like the "burned-in subtitles" function. Thank you.)

**Comment by niksedk** [comment]
Thx for the info :)

Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
(portable version - unpack to something like C:\Tools\SE)

**Comment by Alxndr6eo1yG8Lv8AJ0TkliH6** [comment]
Now it works as expected. Thank you!
