### ISSUE TITLE
Can Audio to text (whisper) option produce a subtitle without 'sounds'?

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#6843]
Is there any model under the whisper option to produce the subtitle without all 'descriptive' words about sounds in it, like '(audience laughing)', '(bell rings)', '(groaning)', '(soft music)',..., that is, whisper mode listens to EVERYTHING and puts it in the subtitle?

It is a very boring and tedious job to find any of these lines and delete them. We can't use REPLACE option, because it won't delete the whole line, it will delete only the text you were searching for. 
**Possible solutions,** if there is no way to avoid this kind of automatic translation. 
1. In REPLACE put the option to find something, like '(audience laughing)', and in option REPLACE WITH put some command like DELETE, in order for the whole line will be deleted if the search words are found. Or, to have the special text box or drop box with the option DELETE THE WHOLE LINE. 
It is not usual to have that in the ordinary REPLACE dialogue, but for the subtitling program, it would be more than useful to use the option to delete the whole line if we find some word or phrase. 

2. Or, we can find all occurrences of the searching phrase and change it with the blank (replace option), and the option can be like 'remove blank lines'. Maybe there is such an option in the program, if somebody knows, let me know. 

If somebody or our Nikolaj knows how to delete the whole line of the subtitle not by browsing through the subtitle and deleting that lines, but by some efficient way, let me know.

**Comment by niksedk** [comment]
Check Tools - Remove text for hearing impaired...

**Comment by Cyberyoda1411** [comment]
Yes, it works perfectly. Did I miss something, or this totally removes all 'sounds' from the subtitle? To me, it works.

**Comment by niksedk** [comment]
SE can remove text for HI - if it's relatively normal annotated.
