### ISSUE TITLE
There is no longer an Undo option in the text box.

### ISSUE THREAD

**Issue by yazbod** [SubtitleEdit/subtitleedit#6844]
Hello. When I was using version 3.6.11 and editing a line of subtitles in the text box, there was an Undo option (or ctrl+z). But in version 3.6.12, there is no such option anymore, and this is very annoying.
![Screenshot (25229)](https://user-images.githubusercontent.com/130897772/232444692-5d2dd40d-62ac-4b05-a95d-f15fc9fbbf06.png)
![Screenshot (25230)](https://user-images.githubusercontent.com/130897772/232444731-767219b3-7399-476e-9e42-289e2b8a7d8d.png)

**Comment by darnn** [comment]
It appears, but only about a second or two after the first change you make. Repeat the process in your screenshots but then just wait two more seconds and it will be there. At least this is the case in the latest beta.

**Comment by niksedk** [comment]
Thx, this is a known bug - should be fixed in latest beta:  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
