### ISSUE TITLE
Can the text box for the entering/editing subtitles be a bit wider

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#6847]
I like your program and I get to know it more and more every day. But, from the day one, I didn't like that the text box for the entering or editing subtitles is a bit too narrow. Look at the picture. In the edit text box there is the text wrapping, because the first row of the subtitle can't fit in the first row of the text box and goes to the next one, but in video view, it is one row. 

Can you make the edit text box just a bit wider, maybe for the 5-6 characters, I think there is enough space **on the left**? I am more than sure that is just a minor correction for you, but it would be nice to have that text box wider. If you expand it to the left, you don't need to change nothing else. 

![Screenshot_1](https://user-images.githubusercontent.com/128191515/232665473-76ef65d3-53d6-4f25-94a1-977493d6a8e8.jpg)

**Comment by GrampaWildWilly** [comment]
> ** Reply to message from Cyberyoda1411 ***@***.***> on Mon, 17 Apr 2023 20:52:07 -0700

Have you experimented with undocking the video controls?  I usually run SE undocked
because that lets me put the video player on my second monitor.  It seems to me when I've
got the controls undocked, my text box is a lot bigger than what you're showing.  The
option for toggling docking is on the Video drop down menu.  Also, Ctrl+Alt+d is a
default shortcut for toggling docking defined in the settings.  Try it & see how that
works for you.

**Comment by Cyberyoda1411** [comment]
Hi Gramapa. I tried to undock the video controls, but it seems too messy. Generally, we don't need too much space for comfortable work, Nikolaj can add 5-6 characters (wider textbox) on the left (there is an empty space), which suffice for 95% of our needs. If some line is extremely wide, let it be, let it be the text wrapping. But, in most cases, it will be more than OK with the slightly wider textbox.

**Comment by LeonCheung** [comment]
Imho, the textbox area needs some redesign indeed. But before that,  maybe you could try to reduce the textbox display font size a little bit in Settings?

**Comment by Cyberyoda1411** [comment]
I've just tried to make the font smaller, but it is not as comfortable for work. It seems that the original font 12pt is the best. 

I think it is not a big deal for Nikolaj to redesign that. It is just a few numbers related to the textbox dimensions and position. And the behavior of the textbox is defined in the libraries for that purpose. He doesn't need to move any other component, because there is a lot of space on the left of the edit textbox. Enough for 6 characters more.

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by Cyberyoda1411** [comment]
Yes, that is it. Thanks. This thing had to be changed, to have the same word wrapping in the edit text box and in the subtitle. 
Sometimes I have some pretty hard-to-implement wishes, it is maybe because I was programming a bit in Visual Basic, it is always drag-and-drop if we talk about the visual element of GUI. But this time, I knew you can easily change the width and position of the textbox, no matter which method you use to write programs: visual or strictly code based. 

You can close this topic. The subtitle editor is better and better every day.

**Comment by OmrSi** [comment]
@niksedk Two issues with this:
![image](https://user-images.githubusercontent.com/20923700/233260154-242ec382-0c06-4690-8691-cd70dd203cd6.png)

**Comment by niksedk** [comment]
A few adjustments has been made for the text box: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
