### ISSUE TITLE
Suggestion: Add word wrap in list view

### ISSUE THREAD

**Issue by SiaL8er** [SubtitleEdit/subtitleedit#6848]
Hello,

I've been using SE for quite some time now and I think this project is absolutely a gamechanger.

I have a suggestion:
When working in Translator Mode, with the list showing both original and translation + the video docked in the main window, sometimes lines can get cut off even on a pretty wide layout.
Would it be possible to add the option of wrapping in the list view? Meaning instead of showing breaks as `<br />`, the lines would actually break and the row would extend.
It can even go right here if you change it to a drop down:
![image](https://user-images.githubusercontent.com/130707737/233024527-3167919c-1fd8-473b-bade-aefd43512967.png)

**Comment by darnn** [comment]
FWIW, at the moment, you can at least replace `<br />` with a single character, which buys you five extra characters. I use the pipe (that is, |) myself. Also, I've removed every column other than text, original text and line number, and with this setup (and list view shown at size 15 Tahoma, and my resolution being 1920x1080), I get 101 characters in a line in English before it cuts off, and 91 in Hebrew:
![se-length](https://user-images.githubusercontent.com/19672444/233028689-ae0fe948-01c7-4043-a918-14f163fa7884.png)

**Comment by niksedk** [comment]
Sorry, it's not really easy to fix (or even possible with the default MS list view in Windows Forms)

**Comment by SiaL8er** [comment]
Thank you @niksedk for responding.

And thank you @darnn (fellow Hebrew translator!) for the tips, this definitely helps.

**Comment by darnn** [comment]
SE is the only subtitle program I know that has decent RTL support, so it makes sense we'd both end up here! Anyway, if you translate to Hebrew (or from it) professionally, would you mind emailing me at ![email](https://user-images.githubusercontent.com/19672444/233289705-9d6ab93c-f87d-431a-867b-2a6b0aaf9a01.png)? I'd love to ask you some questions about rates and such.
