### ISSUE TITLE
Only first 17 subtitles imported from MKV

### ISSUE THREAD

**Issue by frankfromaustria** [SubtitleEdit/subtitleedit#685]
Hi,
I just installed SubtitleEdit to convert VobSub to SRT - it worked great with external .sup files, but I ran into trouble when opening MKV files. I hope it is okay if I post my question here: I tried it with several MKV files that contain vobsub subtitles, and when opening, subtitle edit will only use the first 17 subtitles. I am using it on Windows 8.1 64 Bit and have selected VLC (64 Bit) as video player.
Thank you!
Frank

**Comment by xylographe** [comment]
You could check if all failing mkv files have been generated by the same software,
```
mediainfo --inform="General;%FileName%\n%Encoded_Application%\n%Encoded_Library%\n\n" <path>...
```

**Comment by niksedk** [comment]
Also, what version of SE are you using?
3.4.5 had some (refactoring) bugs regarding MKV...

If SE 3.4.6 is still having problems I would like to see a sample file... (you can also email a link or sample file)

**Comment by frankfromaustria** [comment]
Thank you for your answers.
All the MKVs have been created with MakeMKV.
I am using the current SE version, however it seems the files might be the problem. (Unfortunately, they are quite big, >30gig per file).

**Comment by niksedk** [comment]
OK, I've never tried MakeMKV but I'll give it a go.
You can split large files with a tool like mkvtoolnix: http://www.my-guides.net/en/guides/general-video/how-to-split-mkv-files-using-mkvtoolnix

**Comment by xylographe** [comment]
Closing due to lack of response.
