### ISSUE TITLE
Audio to text with selected box text only

### ISSUE THREAD

**Issue by willy2019** [SubtitleEdit/subtitleedit#6852]
Hi,

Thank you for adding (Whisper)
Can we use Audio to text with selected box text only?
Please find the screenshot.

Regards,

**Comment by willy2019** [comment]
[](url)
![Screenshot 2023-04-20 094120](https://user-images.githubusercontent.com/44941690/233284142-89aa49ab-1faf-46d4-996a-2217e3944696.png)

**Comment by willy2019** [comment]
![Screenshot 2023-04-20 094120](https://user-images.githubusercontent.com/44941690/233284281-094196dd-f570-4971-8d12-3316f65322bf.png)

**Comment by darnn** [comment]
Yes. In list view, right-click the subtitle you want to use Whisper on. There go to Selected lines->Audio->Audio to text (Whisper).

**Comment by Cyberyoda1411** [comment]
Darn, I don't understand what Willy wants and what is your solution? Can you be more precise, please? With more precise details. And please, use the latest beta version, not the regular 3.6.12, because it has already changed. A lot.

**Comment by darnn** [comment]
The way I understood it was that he wanted to take one specific subtitle and use Whisper only on the audio that corresponds to the subtitle's timecodes.

**Comment by Cyberyoda1411** [comment]
So, you select the lines of the subtitle and right-click, then... Selected lines option, but there is no Audio/audio to text there??? Do you refer to somewhere else or these options are not present in beta versions and they are present in the latest 3.6.12? I insist on beta versions because they will be part of the future 3.6.13. Some options are already obsolete. In the whisper, there are two new options in the upper right corner ConstMe and CTrasnlate2, while in 3.6.12 version there is only one besides OpenAI and CPP. 
Tell me what you do when you select the lines of the subtitle and want just that portion of the audio to be generated. If this is what you explained to Willy.

**Comment by darnn** [comment]
I mean, it's just like I said... but here's a screenshot, if that helps:
![image](https://user-images.githubusercontent.com/19672444/233329320-9954a8b0-21c8-4113-bd20-3be7a94c246a.png)
For the record, I'm using 3.6.12 NEXT beta 110, though this hasn't changed recently one way or the other.

**Comment by Cyberyoda1411** [comment]
I also use beta 110 and I don't get Selected lines/Audio/.... options, I have no Audio option. 

See my screenshot, maybe my subtitle is wrong, it is srt file. Did I do something wrong? 


![Screenshot_1](https://user-images.githubusercontent.com/128191515/233331926-c5ece8eb-3603-492b-b675-7a22651c2c62.jpg)

**Comment by darnn** [comment]
You currently don't have a video or audio file open. As soon as you have one open, the Audio line will appear there.

**Comment by Cyberyoda1411** [comment]
You are right, but still don't have AUDIO TO TEXT (Whisper) option??? Any suggestions?

![Screenshot_1](https://user-images.githubusercontent.com/128191515/233335231-aee72230-ee90-4e97-9df7-8f1428955298.jpg)

**Comment by darnn** [comment]
Do you have SE's Whisper installed currently? Like, if you go to the Video menu, do you have "Audio to text (Whisper)" there? And if so, what happens when you click on it? Maybe you need to do that first and download it. Beyond that, I'm afraid I'm out of ideas.

**Comment by Cyberyoda1411** [comment]
**You are the man!** YUP! That is it. I am not so dumb in 'real life' : ), but I have all kinds of versions of SE on my computer. I have the SE 3.6.12 version. I have several beta versions on my desktop, and I didn't update all versions with FFmpeg, CPP,... Especially not the newest 110 beta version. 

I tried this (whisper), and it replaced my original title directly, that line I selected. It is just overwritten. Does it suppose to do this?

**Comment by darnn** [comment]
Yes. That's the idea, I think it's mainly intended for subtitles that are currently empty or inaccurate. I'll sometimes use it if I have a snippet of a foreign language in something, I'll just add a new empty subtitle and set the timecodes myself, and then use Whisper on it.
If you want to use it on a subtitle without replacing its contents, insert a new subtitle and set its timecodes to the timecodes of your original subtitle. If you're not using translation mode, you can go to source view (through the toggle list/source view keyboard shortcut) and create a copy of the subtitle there:
![source view copy](https://user-images.githubusercontent.com/19672444/233341196-5051a8e7-2778-4ca1-bb76-f625e5df4a09.png)
Don't do this in translation mode, though, or it will create a desync.

**Comment by willy2019** [comment]
Thank you
