### ISSUE TITLE
"Shade" under waveform

### ISSUE THREAD

**Issue by SubtitlerPatricia** [SubtitleEdit/subtitleedit#6854]
Hi. Can you tell me why I see the waveform with some "shade" (see picture attached)?
How can I solve it?
Thanks a million!
![Falla Subtitle edit](https://user-images.githubusercontent.com/131397910/233455614-5215e6c7-efbf-4c65-925b-271c4d41f3f1.PNG)

**Comment by niksedk** [comment]
Hi Patricia,
Try to right-click in the waveform:
[image: image.png]

Best regards
Nikolaj

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/233461076-c5f2250b-9cdd-4d42-a8ca-7e79a2c489dc.png)

**Comment by niksedk** [comment]
And you can turn it completely off by  unchecking "Generate spectrogram":
![image](https://user-images.githubusercontent.com/1261331/233461743-568ab796-8773-4d9e-b48e-ed91b73696ba.png)
