### ISSUE TITLE
Missing character line 34 of TextSplit.cs again

### ISSUE THREAD

**Issue by gjbundy** [SubtitleEdit/subtitleedit#6855]
Ok sorry for the lame title, but one more code change is needed on the TextSplit.cs line 34:

`else if ((language == "zh" || language == "ja" || language == "ko") && "，。？、".Contains(text[i]))`

The question mark is also not the correct one. The line should read as follows:

`else if ((language == "zh" || language == "ja" || language == "ko") && "，。？、?".Contains(text[i]))`

**Comment by niksedk** [comment]
`?` is just a normal question-mark... is that okay?

**Comment by gjbundy** [comment]
I know it looks the same, but it is different from the original question mark that is in the code. I have tested and built locally and confirm that it allows splits with ? to occur properly. Happy to share the .cs file if you want that instead? Please let me know!
