### ISSUE TITLE
Suggestion to prevent very short subtitle lines in post-processing of Whisper transcription

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6856]
SEs post-processing of a Whisper transcription is great, but there is something that can be improved.

See the two examples below. The version on the left in the image is taken from a temporary srt-file that contains the Whisper output. The version on the right is the result of SEs post-processing. (These examples are taken from a test run at the end of Issue #6839.)

![Examples of too short subtitle lines](https://user-images.githubusercontent.com/84353335/233477432-c22db5fd-fe41-4a05-a4ce-323d6eea4fef.png)

Sometimes a Whisper transcription contains a very short subtitle line that is the end of a sentence, and this is kept that way in SEs post-processing. Such short subtitle lines can best be combined with the previous subtitle line. I suggest to add to SEs post-processing, to combine such short subtitle lines with the previous subtitle line.

**Comment by niksedk** [comment]
OK, how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by oep42** [comment]
Thank you.

The current implementation of the combining of very short subtitle lines with the previous subtitle line, creates textually better subtitles, but I'm afraid that the synchronization between the audio and the subtitles gets worse. Each of the four examples below, shows, from top to bottom:
1. The Whisper output (from a temporary srt-file).
2. The result of SE's post-processing with "SubtitleEdit 3.6.12 NEXT, beta 92".
3. The result of SE's post-processing with "SubtitleEdit 3.6.12 NEXT, beta 151". 

The first three examples below, are about the combining of a very short subtitle line with the previous subtitle line. In general, the deterioration in synchronization with this (when comparing the output of beta 92 with the output of beta 151), seems to come down to this: 
1. What used to be a very short subtitle, keeps the same duration, but gets filled with much more text. 
2. The two subtitles that previously existed before the original very short subtitle, are combined into one subtitle.

In addition, I noticed that the subtitle after the very short subtitle, starts later in SE's output than in Whisper's output, and this makes the synchronization worse there. (Sometimes this later start is only a little bit later, sometimes clearly more.)

Also, I have the impression that, perhaps, in general, the synchronization sometimes gets worse in SE's post-processing where I do not see a reason for such a deterioration. In the fourth example below, the content of two subtitles remains textually exactly the same before and after SE's post-processing, but there is, nevertheless, a deterioration in synchronization.

1
![Example 1](https://user-images.githubusercontent.com/84353335/235328178-ddfaafee-75eb-466c-974c-4fc8f3f62e61.png)

2
![Example 2](https://user-images.githubusercontent.com/84353335/235328184-1b18c3ab-d506-410a-b993-72350aeba4f4.png)

3
![Example 3](https://user-images.githubusercontent.com/84353335/235328185-77647711-d071-4188-bcbb-bba439f79d0a.png)

4
![Example 4](https://user-images.githubusercontent.com/84353335/235328189-c40bce04-4787-4d19-9828-a5464b1df2ac.png)

**Comment by oep42** [comment]
Additional thougts about this suggestion:

I think this suggestion for additional post-processing only makes sense, if the total length of the very short subtitle line plus the length of the previous subtitle line, is less than the maximum total length of a subtitle line (as it is known in SE).

Also, more generally, I think it's Whisper's responsibility during the processing phase, to create balanced subtitle lines, so that it doesn't produce such short subtitle lines that "belong" to the previous subtitle line.
