### ISSUE TITLE
LRC lyrics, no end time

### ISSUE THREAD

**Issue by zeoint** [SubtitleEdit/subtitleedit#6858]
White wash in waveform when opened a saved lrc file. And the subtitle is not changing, while it is working properly in my music player.
I attached the zip file containing the audio file and it's lrc file. Please check.

[I Took A Pill In Ibiza (Seeb Remix).zip](https://github.com/SubtitleEdit/subtitleedit/files/11295344/I.Took.A.Pill.In.Ibiza.Seeb.Remix.zip)

https://user-images.githubusercontent.com/127277950/233626650-736c0a12-4a73-4f75-9296-cb9b83991a7f.mp4

**Comment by niksedk** [comment]
How is this; https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip ?
