### ISSUE TITLE
Stream was too long.

### ISSUE THREAD

**Issue by MariuszHawrynski** [SubtitleEdit/subtitleedit#6864]
![2023-04-22 22_14_37-Windows Forms Thread Exception](https://user-images.githubusercontent.com/131555655/233804555-f941a982-341e-4cc8-912c-6ecda3cc6433.png)

**Comment by MariuszHawrynski** [comment]
OK – I upload the file to the cloud (40 GB). When it's ready, I'll send you a link. Unfortunately, my Internet is not very fast, so it'll take a while.

 

Regards

Mariusz

**Comment by MariuszHawrynski** [comment]
Hello

 

I had trouble sending it in full. Here is a link to the directory where there is a 7zip archive with a file divided into parts.

https://u.pcloud.link/publink/show?code=kZGMPqVZXKAktFbK9XLAt1f38YcJgzpzP1KV

 

Regards

Mariusz

From: ***@***.*** ***@***.***> 
Sent: Sunday, April 23, 2023 9:26 AM
To: 'SubtitleEdit/subtitleedit' ***@***.***>; 'SubtitleEdit/subtitleedit' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [SubtitleEdit/subtitleedit] Stream was too long. (Issue #6864)

 

OK – I upload the file to the cloud (40 GB). When it's ready, I'll send you a link. Unfortunately, my Internet is not very fast, so it'll take a while.

 

Regards

Mariusz

**Comment by niksedk** [comment]
Thx :)

Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
via this commit: https://github.com/SubtitleEdit/subtitleedit/commit/cd352b63d265f5f6d2b6b9472eba5063eacbeb22
