### ISSUE TITLE
Whisper JAX

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#6865]
Guys, I found this, and it runs 70x faster than PyTorch. I used the demo on Huggingface and a 5-minute video from a YouTube link was transcribed in less than 2 seconds. Amazed!!! 
GitHub: 
https://github.com/sanchit-gandhi/whisper-jax
Huggingface Demo:
https://huggingface.co/spaces/sanchit-gandhi/whisper-jax

So the idea here is that it's easier to run a model on a slow, local machine, why not use Huggingface TPUs?

**Comment by darnn** [comment]
This does look interesting (and does work very fast in their collab notebook). @Purfview, want to take a look at this? It's too much for me, sadly, since there isn't a simple command-line version.

**Comment by niksedk** [comment]
How could this be integrated into SE without a command line version of jax?

**Comment by uckthis** [comment]
Yes, you're right, there's no simple CMD version as of today.  I saw it working so fast and got excited to share. Watched another video where this guy transcribes 2.5 hours in 31 seconds. Something to look forward to in the future.

**Comment by iprospero** [comment]
Here is Whisper interface with CMD
https://github.com/Const-me/Whisper/releases/tag/1.11.0

**Comment by darnn** [comment]
@uckthis If I install WSL, will it be possible to use it from the command line? Do you have a tutorial or something? There's nothing about this on their page, as far as I could tell.
@iprospero Yes, this is already present in SE.

**Comment by uckthis** [comment]
@darnn I haven't been able to run it on CMD, even after spending a few hours, but you can see:
https://github.com/sanchit-gandhi/whisper-jax/issues/40

**Comment by iprospero** [comment]
> @iprospero Yes, this is already present in SE.

have no clue how to find it %(.

**Comment by darnn** [comment]
Go to Video->Audio to text (Whisper), and select it as the engine in the upper right corner.

**Comment by niksedk** [comment]
Perhaps somebody will wrap Whisper Jax in a cmd line version... much could probably be reused from other whisper versions.
But until then, I cannot really do much.
