### ISSUE TITLE
On Arch Linux, mpv runs full screen

### ISSUE THREAD

**Issue by EuphoricCatface** [SubtitleEdit/subtitleedit#6866]
When mpv is supposed to run inside the UI, it always runs full screen in a separate window, and it doesn't seem to have any way to get it back into the UI.

I am experiencing this on two systems, one with GNOME desktop environment on a laptop, and the other on Crostini setup on a Chromebook.

**Comment by darnn** [comment]
This is neither here nor there, but this happens on Windows occasionally too. Try closing the video file and opening it again several times, on Windows you are eventually able to get it to open in the video player area.

**Comment by EuphoricCatface** [comment]
I just tried opening and closing the video around 20 times using "Video - Open/Close video file". Not a single time did it open in the video player area. Restarting the whole program didn't fix it, either.

**Comment by GrampaWildWilly** [comment]
> ** Reply to message from EuphoricCatface ***@***.***> on Sun, 23 Apr 2023 01:22:11 -0700

Here's my wild-ass guess, shot in the dark.  Might be worth checking.  I usually run SE
with the MPV player in fullscreen on my second monitor.  But I'm doing it on purpose. 
I've undocked the video controls.  There is a menu entry for that on SE's Video dropdown
menu.  The shortcut is Ctrl+Alt+d for toggling docked & undocked.  Maybe somehow you
accidentally undocked your video controls.  Just redock them.

**Comment by EuphoricCatface** [comment]
> ** Reply to message from EuphoricCatface ***@***.***> on Sun, 23 Apr 2023 01:22:11 -0700
> Here's my wild-ass guess, shot in the dark. Might be worth checking. I usually run SE with the MPV player in fullscreen on my second monitor. But I'm doing it on purpose. I've undocked the video controls. There is a menu entry for that on SE's Video dropdown menu. The shortcut is Ctrl+Alt+d for toggling docked & undocked. Maybe somehow you accidentally undocked your video controls. Just redock them.

That's the same as "Video - Un/Re-dock video controls", right? I tried that and it didn't fix the problem. Regardless of whether the video was undocked or not, the video stays in a separate full screen window. Even when the video is supposed to be hidden with "Video - Show/hide video", the full screen video won't go away.

**Comment by niksedk** [comment]
In `Settings.xml` - is `MpvVideoOutputLinux` `x11` ?

**Comment by EuphoricCatface** [comment]
> In `Settings.xml` - is `MpvVideoOutputLinux` `x11` ?

Huh, the setting was empty (`<MpvVideoOutputLinux />`). It works correctly now that I make it `x11`. I haven't edited the entry before. Maybe the default value is wrong?

**Comment by TerrorizedGakon** [comment]
> In `Settings.xml` - is `MpvVideoOutputLinux` `x11` ?

Hey,

Is there anything for Windows, which might fix the issue? It's quite annoying when it runs fullscreen.
