### ISSUE TITLE
Whisper CTranslate2 Implementation - Incorrect Hebrew Language Tag + Model Name

### ISSUE THREAD

**Issue by SiaL8er** [SubtitleEdit/subtitleedit#6867]
Hi,

When trying to use the whisper-ctranslate2 implementation for Hebrew I get the "No Text Found" error, and I've noticed SE sends the command using `--language iw` but whisper-ctranslate2 is expecting `--language he`.

Also, the list of models only has "large" but it seems whisper-ctranslate2 is expecting only "large-v1" or "large-v2":
`--model {tiny,tiny.en,base,base.en,small,small.en,medium,medium.en,large-v1,large-v2}
                        name of the Whisper model to use (default: small)`

**Comment by niksedk** [comment]
Thx for the info :)

How is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by SiaL8er** [comment]
Nice! Both are fixed now :)
