### ISSUE TITLE
Instability of mpv

### ISSUE THREAD

**Issue by chenlung** [SubtitleEdit/subtitleedit#6868]
1. Open [this](https://github.com/SubtitleEdit/subtitleedit/files/11304226/Instability.of.mpv.zip) iTT.
2. Open video with [keyframes](https://drive.google.com/file/d/1j97jJzzTQthf-cd2KRyOtrskdbLaD7bf/view?usp=sharing) (also try [automatic](https://drive.google.com/file/d/1biVJgKO3uzog7eD3-eX9OVgMQorY--rU/view?usp=sharing)).
3. Double-click each entry from top to bottom.

Result: A progressive shift away of one frame from the timecode on screen at entries 5, 9, 14, and 18.
![Subtitle 1](https://user-images.githubusercontent.com/2973439/233851618-e4529b2f-fe3f-4c8e-b874-7e5b45daf58c.png)
![Subtitle 5](https://user-images.githubusercontent.com/2973439/233851625-012b05c0-81ca-4dbe-8504-4cdefb24a3fc.png)
![Subtitle 9](https://user-images.githubusercontent.com/2973439/233851629-24bdd476-457f-41e6-82c9-88262df56ef3.png)
![Subtitle 14](https://user-images.githubusercontent.com/2973439/233851632-c23e88d3-7981-4157-9d1c-1cdb1225040d.png)
![Subtitle 18](https://user-images.githubusercontent.com/2973439/233851635-ae41e5f3-7ede-4d3a-b438-638439bd9185.png)

Note: Both videos were produced in Final Cut Pro 7.0.3 and exported using Compressor 3.5.3.

Using Subtitle Edit 3.12.6 Beta - Windows 10 Home.

**Comment by chenlung** [comment]
In the context of a production environment, this bug represents a fundamental instability in relation to the video preview.

Unless fixed in an mpv nightly (could someone check, please?), I think an issue needs to be filed on their [issue tracker](https://github.com/mpv-player/mpv/issues).

Perhaps it already exists?
- [Small skip every 9 seconds playback](https://github.com/mpv-player/mpv/issues/6037)
- [mpv step backward is slow or sometimes it does not work properly whereas avidemux, djvview works](https://github.com/mpv-player/mpv/issues/6129)
- ["frame-step" skips extra frames upon unpausing proportional to times tapped](https://github.com/mpv-player/mpv/issues/6942)
- [Excessive frame drops on HFR video when using hardware decoding](https://github.com/mpv-player/mpv/issues/6940)
- [rpi 4 libmpv hardware decoding drops frames](https://github.com/mpv-player/mpv/issues/7862)
- [estimated-frame-number off-by-one and incorrect display when reversing frame direction.](https://github.com/mpv-player/mpv/issues/9206)
- [Videos trimmed by Quicktime fail to play properly](https://github.com/mpv-player/mpv/issues/10367)
- [pausing MPV player for mere 5 seconds then continue playing the video results in dropped frames](https://github.com/mpv-player/mpv/issues/10954)
- [Frame stepping is broken with gpu-next and interpolation](https://github.com/mpv-player/mpv/issues/11048)
- [sub-step skips over lines when paused](https://github.com/mpv-player/mpv/issues/11445)
- [frame-step and frame-back-step does not work consistently when beyond a video stream](https://github.com/mpv-player/mpv/issues/11471)

Regardless, I hope it can be investigated and fixed by mpv as a matter of urgency.

**Comment by chenlung** [comment]
It is also a problem in the three other players offered by Subtitle Edit (DirectShow, VLC, and MPC-HC), but with the following subtitles: 6, 10, 14, 18

**Comment by SiaL8er** [comment]
Works fine for me when using Video > SMPTE timing (as the video is 23.976 fps).
