### ISSUE TITLE
Apply Whisper post-processing + timing adjustments without running Whisper

### ISSUE THREAD

**Issue by Udoachim** [SubtitleEdit/subtitleedit#6870]
I like to run Whisper on a more powerful environment than my local machine such as Google Colab, however, when I open the resulting .srt in Subtitle Edit there is no option to apply the post-processing and timing adjustment options of the built-in Whisper version without having to run the whole text recognition again. It would be great to have the post-processing and timing adjustments available as an independent function or to give an option to import an .srt file as input in the Whisper menu.

**Comment by niksedk** [comment]
Should be possible here:
![image](https://user-images.githubusercontent.com/1261331/234381772-0a149070-8af4-4c3b-bf4b-e0d0f1330a0f.png)

Note that at least one of the two bottom check-boxes need to be checked.


https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
