### ISSUE TITLE
Change FPS in CLI.

### ISSUE THREAD

**Issue by larsk2** [SubtitleEdit/subtitleedit#6872]
There seems to be an issue with the fps converting in batch mode (CLI).

SubtitleEdit.exe /convert test.srt srt /fps:23.976
SubtitleEdit.exe /convert test.srt srt /fps:23,976
SubtitleEdit.exe /convert test.srt srt /fps:24.000
SubtitleEdit.exe /convert test.srt srt /fps:24,000
SubtitleEdit.exe /convert test.srt srt /fps:24

none of the above does anything to the sub. 

- While for instance "offset" is working just fine (SubtitleEdit.exe /convert test.srt srt /offset:-00:00:00:300)

Am I missing something here, or is it a bug?

v 3.6.12 Win10 64-bit

**Comment by niksedk** [comment]
Try something like: `SubtitleEdit /convert test.srt srt /fps:25 /targetfps:30`

**Comment by larsk2** [comment]
Where can I find the help page for these commands?

**Comment by niksedk** [comment]
I don't think much more than the cmd line info is available...
