### ISSUE TITLE
Please add two new features to the highly acclaimed sutitle edit

### ISSUE THREAD

**Issue by dycfan** [SubtitleEdit/subtitleedit#6876]
sutitle edit is a very perfect subtitle processing tool, I have been using it for more than two years.

The current subtitle translation function of sutitle edit uses Google's translation interface, and the translation quality is really average. In addition, some people have provided a plug-in for Baidu translation, but because this plug-in is very old, it is currently unavailable.

my suggestion is:

1. Can openai's chatgpt text translation capability be integrated into sutitle edit to significantly improve the subtitle translation quality of sutitle edit? Even if you need to pay for subtitle translation in sutitle edit using chatgpt, I think it is completely acceptable.

2. Can you add a function of exporting srt subtitles and ass subtitles to a CSV file in sutitle edit, and correspondingly add a function of importing subtitles from CSV files? With CSV files, we can process subtitle content more flexibly and quickly.

Looking forward to responding. Thank you so much!

**Comment by niksedk** [comment]
You can try the DeepL translation plugin.

SE already has support for several CSV files... is info missing that you need?

Also, it's a bit better to have only one issue in an issue: see https://www.nikse.dk/subtitleedit/help#good-github-issue
