### ISSUE TITLE
Need Show Remaining Subtitle Feature

### ISSUE THREAD

**Issue by SawL4yy** [SubtitleEdit/subtitleedit#6877]
Chat GPT Told Me there is show remaining Subtitle Feature Feature In subtitle Edit.But I can't see it anywhere.Can you help me to find this feature or add this feature please?
![show remaing](https://user-images.githubusercontent.com/131994471/234922826-b1e93c48-d3d9-44ff-a048-d1faddc12bbf.PNG)

**Comment by darnn** [comment]
There's no reason to get ChatGPT to tell you about the functions of a program that has its own documentation. It would be two years out of date, and in this case it's clearly pointing you to a setting that doesn't actually exist. Having said that, are you not just talking about something that already exists without needing to be enabled? Namely, this?
![se-subtitle-number](https://user-images.githubusercontent.com/19672444/234953826-53bddf0c-97e5-4ec4-b0f6-38d65331ee23.png)

**Comment by SawL4yy** [comment]
I know that function that you pointed bro,but i need the remaining line numbers only.Like 12 (125-113) lines remaining.I mean something like subtracted number.
