### ISSUE TITLE
Error attempting to open file used by another process

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#6878]
![se-file-used-by-other-process](https://user-images.githubusercontent.com/19672444/234954384-f8d46e89-d78e-4027-b2f2-e61f2c003964.png)

**Comment by niksedk** [comment]
If a file is opened in write-mode in another programs, then SE cannot open this file.

**Comment by darnn** [comment]
Oh, sure, I just thought it would have a regular error message, rather than this one that suggests something out of the ordinary has taken place.

**Comment by niksedk** [comment]
OK, probably not a bad idea :)
