### ISSUE TITLE
How to manually download trained data files for Tesseract

### ISSUE THREAD

**Issue by vivadavid** [SubtitleEdit/subtitleedit#6879]
Hi,

I'm not reporting exactly an issue, but was wondering how I could manually download trained data files for the latest version of Tesseract (and previous ones if possible). I know that you can do it very easily through Subtitle Edit, but I wanted to know the repository it gets the files from.

To test another programme, I've installed the installer for Tesseract 5.3.1 from Mannheim (https://github.com/UB-Mannheim/tesseract/wiki), which allows you to download the trained models for many languages. However, at least for Spanish and English, I'm getting files that are much smaller than those downloaded through Subtitle Edit and I wonder if my trained models are incomplete or low quality somehow.

I've been browsing on the Tesseract website on Github and all I can find is very old trained models back to 5-6 years ago, and yet Subtitle Edit 3.6.12 is able to retrieve the trained data for Tesseract 5.3.0.

I have no idea where I could get previous and current trained models and I'd appreciate some help: I don't know where else to look.

Thanks!

**Comment by niksedk** [comment]
The trained data is here: https://github.com/tesseract-ocr/tessdata

**Comment by vivadavid** [comment]
Thank you for your reply.

I did find this webpage a long time ago, but I thought I had to look elsewhere, as the trained data files are quite old. Was I wrong to think that for each Tesseract new version (at least, for each major new version), new trained data files had to be generated?

I have several versions of portable Subtitle Edit on my laptop and I have just wondered that, for example, the _spa.traineddata_ file downloaded through Subtitle Edit is the same file over and over again, even if, for example, on Subtitle Edit 3.5.14, the subfolder is called _Tesseract411_, whereas on the latest Subtitle Edit 3.6.12, the subfolder is _Tesseract530_.

It seems that new trained data files were generated for Tesseract 4 and that these have been the same since then, even for Tesseract 5.

What I still don't get is why through the Mannheim installer, the trained data files are much smaller (for _spa.traineddata_, we are talking about 2.18 MB compared to 17.4 MB).

In any case, thank you for pointing me in the right direction.

**Comment by vivadavid** [comment]
I'm sorry I bothered you with my questions. I realize they were basic and I eventually found an answer.

I have found, on Github, a fast trained data model, and that's why those files were smaller. I guess that every developer decides which model to use for their programme. I'm glad Subtitle Edit uses the "standard" model, as I presume it's more accurate.

**Comment by niksedk** [comment]
Yes, the trained data is not updated very often... it's still the version 4 files.

Yes, the standard should be a little more precise.
