### ISSUE TITLE
The failure of "WHISPER"

### ISSUE THREAD

**Issue by Nanumy** [SubtitleEdit/subtitleedit#6880]
I can't use "WHISPER" because of errors.
How can I solve it?

my issue is below,
(in SE error.txt)

-----------------------------------------------------------------------------
Date: 04/28/2023 13:04:21
SE: 3.6.12.0 - Microsoft Windows NT 10.0.22621.0 - 64-bit
Message: whisper --language fr --model "small"  "C:\Users\******\AppData\Local\Temp\9c130b76-aa27-4ae1-ab04-49f061481ada\00_05_23_179__00_05_28_902.wav"

-----------------------------------------------------------------------------
Date: 04/28/2023 13:05:39
SE: 3.6.12.0 - Microsoft Windows NT 10.0.22621.0 - 64-bit
Message: whisper --language fr --model "medium"  "C:\Users\******\AppData\Local\Temp\d76862ec-0a87-4d42-89ee-d06e34700de5\00_05_23_179__00_05_28_902.wav"

-----------------------------------------------------------------------------
Date: 04/28/2023 13:06:47
SE: 3.6.12.0 - Microsoft Windows NT 10.0.22621.0 - 64-bit
Message: whisper --language fr --model "base"  "C:\Users\******\AppData\Local\Temp\07ab38b8-cc91-47fa-a245-8c29f9cc32ef.wav"

**Comment by niksedk** [comment]
Works fine here... 

Read about OpenAI setup: https://github.com/openai/whisper#setup
