### ISSUE TITLE
 application error in Subtitle 3.6.11.0- MS NT 10.0.19044.0. (Issue #6819) no solution so far

### ISSUE THREAD

**Issue by Lennie1200** [SubtitleEdit/subtitleedit#6881]
Hi Team, 

My responsible colleague was unfortunately ill so I had no chance to answer to the ticket Issue #6819 in time.- 

Here is the requested screenshot of plugins : 
![image](https://user-images.githubusercontent.com/130572403/235112801-6429882d-e7f6-4908-a998-5ba4dd64aaf0.png)

**Comment by niksedk** [comment]
What's the exact error? What subtitle file caused this error (please attach)?
