### ISSUE TITLE
The beta version of CTranslate2 cannot generate text

### ISSUE THREAD

**Issue by despairTK** [SubtitleEdit/subtitleedit#6882]
I downloaded SubtitleEditBeta.zip today and wanted to try the newly added CTranslate2, but I tried a lot of video files or audio files but couldn't generate any text, only a blank subtitle file without any content.

**Comment by niksedk** [comment]
Follow installation instructions here: https://github.com/Softcatala/whisper-ctranslate2

**Comment by bastauno** [comment]
I'm joining the discussion because I also don't quite understand:
1) When I select ctranslate2, Subtite Edit looks for whisper-ctranslate2.exe. Where do I download this executable from?
2) To use the ctranslate2 function in Subtitle Edit, is it necessary to install python? and follow the procedure described in https://github.com/Softcatala/whisper-ctranslate2 ?
I don't have Python installed and use both Cpp and Const-me with models downloaded from https://huggingface.co/ggerganov/whisper.cpp/tree/main.
Thank you

**Comment by niksedk** [comment]
Whisper is not for everyone... 

Yes, you do need Python - follow the instructions here: https://github.com/openai/whisper#setup

It is best (or required for some implementations) that your CPU supports AVX.

For the larger models you might need up to 16 GB of free RAM.

Also, you might get weird Python errors that you will need to Google to find a fix.

**Comment by Purfview** [comment]
Or you can get ready to run executables from there: https://github.com/Purfview/whisper-standalone-win
People say "CTranslate2" has no errors with these.

**Comment by bastauno** [comment]
I tried following the instructions in https://github.com/Purfview/whisper-standalone-win .
Is it normal for SubtitleEdit to create two twin folders for each downloaded model ? 
One is located in C:\Users\...\.cache\whisper-ctranslate2\2ca96777261aeadd48e30bc5f26fd3ee462f4921dbc1f38dfd826a67c761c9b2.base-en and the other is in C:\Users\...\Downloads\SubtitleEditBeta\Whisper\_models\faster-whisper -base.en\.
 Each folder contains 4 files: config.json, model.bin,tokenizer.json and vocabulary.txt
Thank you.

**Comment by Purfview** [comment]
> Is it normal for SubtitleEdit to create two twin folders

Yes. First folder is created by SE, second one is created by faster-whisper-standalone. Only second is actually used, first one is just for SE to see that it has models because you can't select models folder in SE.
Btw, don't copy those models SE downloaded, those are outdated non-original models.

**Comment by niksedk** [comment]
OK, this was changed like 4 days ago... I will update SE to download the correct models soon :)

**Comment by Purfview** [comment]
@niksedk Maybe you could add standalones to your FAQ too, because many people don't know what to do with Python, and whisper-ctranslate2 doesn't run for some when standalone faster-whisper runs OK. [Or did you added it already, I see few traffic hits from your domain?]

**Comment by niksedk** [comment]
Sure, I can add something on the SE help page - needs an update too :)

Damn, this CTranslate2 folder structure is a bit annoying - single files are so much easier...

**Comment by despairTK** [comment]
> 我尝试按照 https://github.com/Purfview/whisper-standalone-win 中的说明进行操作。字幕编辑为每个下载的模型创建两个孪生文件夹是否正常？一个位于 C：\Users....cache\whisper-ctranslate2\2ca96777261aeadd48e30bc5f26fd3ee462f4921dbc1f38dfd826a67c761c9b2.base-en，另一个在C：\Users...\Downloads\SubtitleEditBeta\Whisper_models\faster-whisper -base.en。每个文件夹包含4个文件：config.json，model.bin，tokenizer.json和vocabulary.txt谢谢。

Hey, my friend. Are you able to use CTranslate2 properly? I followed the instructions from https://github.com/Softcatala/whisper-ctranslate2 to install and download the model, but only blank subtitle files are generated so far.

**Comment by despairTK** [comment]
> 嗨，我使用自己的 CLI 进行更快的耳语 [又名“CTranslate2”]，也许您在使用 Python 时遇到了一些问题，如果您使用 Windows，那么您可以尝试准备从我的存储库运行二进制文件：https://github.com/Purfview/whisper-standalone-win

Thank you very much for your reply. I have a special situation, so I will explain in detail: I have a completed subtitle timeline, and then I want to select each row of subtitles in Subtitle Edit, and then right click → convert audio to text. Recognition in this way can avoid the time axis offset or some strange problems that whisper itself will appear. But the current OpenAI's Whisper integrated in Subtitle Edit is accurate, but the speed is very slow, even if I use RTX 4090, (I think it is because each line of the selected subtitle will extract a piece of audio separately, and then recognize it one by one, it will stop Start recognition.). The integrated Const-me Whisper will be much faster than OpenAI's Whisper, but it doesn't feel fast enough. If a 30-minute video has about 300 lines, it will take about five minutes, and some recognition accuracy will be worse than OpenAI's Whisper. Some. I also saw that you included Faster-Whisper in https://github.com/Purfview/whisper-standalone-win which can also be used for Subtitle Edit. but. . It can be understood that I am stupid. After I run whisper.exe on a Windows 11 device, the CMD window stays for a few seconds and then crashes. And I'd rather use Faster-Whisper in Subtitle Edit. (I also installed Faster-Whisper following the tips here https://github.com/guillaumekln/faster-whisper)

**Comment by Purfview** [comment]
> After I run whisper.exe on a Windows 11 device, the CMD window stays for a few seconds and then crashes.

Are you sure that it crashes, what is the error?
Maybe you don't know how to run CMD programs, then watch this guide: https://www.youtube.com/watch?v=A3nwRCV-bTU
