### ISSUE TITLE
Download of Whisper CPP models fails

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6884]
When choosing "Video/Audio to text (Whisper)" for the first time after installing SubtitleEdit-3.6.12 NEXT, beta 151, the download of ffmpeg and Whisper CPP works as I am used to (with firewall in "Allow outgoing" mode). But after that, the download of Whisper models fails, even when disabling the firewall completely. (I earlier encountered the same problem with SubtitleEdit-3.6.12 NEXT, beta 92. I am using Windows.)

After a failed try to download the "tiny.en" model, in the "Whisper/Models" subfolder, a file "tiny.en.bin.$$$" with a size of zero bytes has appeared. It is possible to download the file with a browser when using this web address:  "https://huggingface.co/datasets/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin".

Please see the image below.

![Download of Whisper CPP model failed](https://user-images.githubusercontent.com/84353335/235328638-b335f12d-a38b-4672-83be-0be59b853837.png)

**Comment by niksedk** [comment]
OK, I cannot re-create this... What OS and SE version are you using?

**Comment by oep42** [comment]
I am using Windows 8.1 Pro. Please see above voor the relevant versions of SE.

If I am the only one having this problem, I guess it's just my problem. I can download the Whisper models in another way, so it's not a major problem for me.

**Comment by oep42** [comment]
I did some more testing with this, with three different versions of SE (two test runs per version). See the results below.


**SE 3.6.10 NEXT beta 264:**

FIRST TEST RUN: 
[FAIL A] Downloading does not work with:
--- tiny.en
--- base
--- small.en
--- small
--- large
[FAIL B] Downloading does not work with:
--- medium.en
--- medium
Downloading does work with:
--- tiny
--- base.en

SECOND TEST RUN:
[FAIL A] Downloading does not work with:
--- tiny.en
--- base.en
--- small.en 
--- medium.en
--- large
[FAIL B] Downloading does not work with:
--- medium
Downloading does work with:
--- tiny
--- base
--- small


**SE 3.6.11 NEXT beta 50:**

FIRST TEST RUN:
[FAIL A] Downloading does not work with:
--- tiny.en
--- small.en
--- medium
[FAIL B] Downloading does not work with:
--- medium.en
--- large
Downloading does work with: 
--- tiny
--- base.en
--- base
--- small

SECOND TEST RUN:
[FAIL A] Downloading does not work with:
--- tiny.en
--- base.en
--- small.en
--- medium.en
--- large
[FAIL B] Downloading does not work with:
--- medium
Downloading does work with: 
--- tiny
--- base
--- small


**SE 3.6.12.NEXT beta 151:**

FIRST TEST RUN:
[FAIL A] Downloading does not work with:
--- tiny.en
--- tiny
--- base.en
--- base
--- small.en
--- small
--- medium.en
--- medium
--- large

SECOND TEST RUN:
[FAIL A] Downloading does not work with:
--- tiny.en
--- tiny
--- base.en
--- base
--- small.en
--- small
--- medium.en
--- medium
--- large

There are two different ways in which downloads can fail:
(1) FAIL A: An error message appears; results in a zero bytes file with ".bin.$$$" as last part of file name.
(2) FAIL B: No errror message appears; gets asterisk in list of downloadable models; does not appear in "Choose model" list; results in a 162 bytes file with ".bin" as last part of file name.


**Conclusions of the above test results**

In the two tested earlier versions of SE, some downloads did work, and some downloads did not work. In the tested more recent version of SE, all downloads failed.

The test results of "SE 3.6.10 NEXT beta 264" and "SE 3.6.11 NEXT beta 50" are not consistent, because their first and second test runs produced different results. The test results of "SE 3.6.12.NEXT beta 151" are consistent, because its first and second test runs produced the same results. (I have no idea why the first and second test runs of "SE 3.6.10 NEXT beta 264" and "SE 3.6.11 NEXT beta 50" produced inconsistent results. This is not what I expected, because, as far as I know, the circumstances of the two test runs were the same.)

I'm not sure if these additional tests help, but who knows.

**Comment by niksedk** [comment]
What does the file "error_log.txt" say? 
(should be in the SE data folder - press Ctrl+Shift+Alt+D in the SE main window)

**Comment by niksedk** [comment]
Also, it could be related to this: https://learn.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client

**Comment by oep42** [comment]
First I looked at the "learn.microsoft" link. I found out, that the "DefaultSecureProtocols" registry setting was missing in my Windows registry. I added this registry setting as described in https://superuser.com/questions/1080317/how-to-set-tls-protocols-as-default-after-applying-kb3140245, and gave it the "AA0" value. After this, I did some retests, with the following results:

With "SE 3.6.12 NEXT beta 151", the downloads fails with [FAIL A], and this produces the following error info in "error_log.txt":

SE: 3.6.12.151 - Microsoft Windows NT 6.3.9600.0 - 64-bit
Message: DownloadAsync failed
System.Net.Http.HttpRequestException
Message: An error occurred while sending the request.
StackTrace:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()
System.Net.WebException
Message: The request was aborted: Could not create SSL/TLS secure channel.
StackTrace:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

With "SE 3.6.11 NEXT beta 50", sometimes a download works, sometimes it fails with [FAIL A], and sometimes it fails with [FAIL B]. Both [FAIL A] and [FAIL B] produce the same error info as above in "error_log.txt".

It seems that adding the "DefaultSecureProtocols" registry setting, doesn't make a difference.

**Comment by Purfview** [comment]
Similar for me, in some ~recent version the downloads stopped working [again].

**Comment by niksedk** [comment]
Updating Windows and the .net framework might help.

**Comment by Purfview** [comment]
Helps when I don't update SE. :P

**Comment by oep42** [comment]
@niksedk Thanks for your response.

I have .NET Framework 4.8 installed (from 2019). I guess this is not too old.

My current version of Windows is not fully updated. I suspect this is the reason why downloads of Whisper CPP models fail. I now prefer to download the Whisper CPP models separately, over doing a Windows update. (I will have to upgrade to a newer version of Windows at sometime in the future, but I am reluctant to do so because it is a lot of work.)

**Comment by niksedk** [comment]
OK, I've tried to make an older method of downloading available (might not work with larger files - or at all).

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
1) Run beta
2) Close beta, change "UseLegacyDownloader" to "True" in "Settings.xml"
3) Run beta and try downloading...

**Comment by oep42** [comment]
I changed "UseLegacyDownloader" to "True" in "Settings.xml". When choosing "Video/Audio to text (Whisper)" for the first time, the download of ffmpeg and Whisper CPP works. After that, for all models, trying to download a model results in [FAIL A] with this message in "error_log.txt":

SE: 3.6.12.198 - Microsoft Windows NT 6.3.9600.0 - 64-bit
Message: Error downloading https://huggingface.co/datasets/ggerganov/whisper.cpp/resolve/main/ggml-large.bin
System.Net.WebException
Message: The request was aborted: Could not create SSL/TLS secure channel.
StackTrace:    at System.Net.HttpWebRequest.GetResponse()
   at Nikse.SubtitleEdit.Core.Http.LegacyDownloader.<>c__DisplayClass0_0.<DownloadAsync>b__0()

**Comment by Purfview** [comment]
@oep32
Try this: [url]https://pastebin.com/h8NnpysH[/url]

Press a download button there and save with extension "reg" instead of "txt", then double click a reg file.

**Comment by oep42** [comment]
@Purfview Thanks for your suggestion.

The registry setting from https://pastebin.com/h8NnpysH was missing in my Windows registry. I added this setting and restarted Windows.

After that, with "UseLegacyDownloader" still set to "True" in "Settings.xml", trying to download a model, results in [FAIL A] with this message in "error_log.txt":

> SE: 3.6.12.198 - Microsoft Windows NT 6.3.9600.0 - 64-bit
> Message: Error downloading https://huggingface.co/datasets/ggerganov/whisper.cpp/resolve/main/ggml-tiny.bin
> System.Net.WebException
> Message: Unable to connect to the remote server
> StackTrace:    at System.Net.HttpWebRequest.GetResponse()
>    at Nikse.SubtitleEdit.Core.Http.LegacyDownloader.<>c__DisplayClass0_0.<DownloadAsync>b__0()
> System.Net.Sockets.SocketException
> Message: An attempt was made to access a socket in a way forbidden by its access permissions 65.9.86.125:443
> StackTrace:    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

After that, trying to download a model with SE 3.6.12.151, results in [FAIL A] with this message in "error_log.txt":

> SE: 3.6.12.151 - Microsoft Windows NT 6.3.9600.0 - 64-bit
> Message: DownloadAsync failed
> System.Net.Http.HttpRequestException
> Message: An error occurred while sending the request.
> StackTrace:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()
> System.Net.WebException
> Message: Unable to connect to the remote server
> StackTrace:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
> System.Net.Sockets.SocketException
> Message: An attempt was made to access a socket in a way forbidden by its access permissions 65.9.86.43:443
> StackTrace:    at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

This time, it seems that a permission is set in a way that doesn't allow this way of downloading. Because I guess that not being able to download the models, is related to just my system, and because I can download the models in another way, I prefer not to continue into a rabbit hole of searching for more tweaks to my system that may result in succesful downloading. I do not want to tweak my system any further for something that I don't really need. I will close this issue.
