### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by zhengstatic** [SubtitleEdit/subtitleedit#6885]
An application error occurred in Subtitle Edit 3.6.120-64-bit-
Microsoft Windows NT 10.0.19044.0.
Please report at https//github.com/SubtitleEdit/subtitleedit/issues with
the following information:
Error Message:
发生一个或多个错误，
Stack Trace:
System.Threading.Tasks.Task'1.GetResultCore(Boolean
waitCompletionNotification)
在
Nikse.SubtitleEditCore.Translate.Service.GoogleTranslator1.Translate(Stri
ng sourceLanguage,String targetLanguage,List'1 sourceParagraphs)
在
Nikse.SubtitleEditCore.Translate.Processor AbstractTranslationProcessor
1.Translate(ITranslationService translationService,String
sourceLanguagelsoCode,String targetLanguagelsoCode,List'1
sourceParagraphs,TranslationProcessCancelStatus processCancelStatus)
Nikse.SubtitleEdit Forms.Translate.GenericTranslate.Translate0
System.Windows.Forms.Control.OnClick(EventArgs e)
System.Windows.Forms.Button.OnClick(EventArgs e)
System.Windows.Forms.Button.OnMouseUp(MouseEventArgs
mevent)
System.Windows.Forms.Control.WmMouseUp(Message&m,
MouseButtons button,Int32 clicks)
System.Windows.Forms.Control.WndProc(Message&m)
System.Windows.Forms.ButtonBase.WndProc(Message&m)
System.Windows.Forms.Button.WndProc(Message&m)
System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd,Int32
msg,IntPtr wparam,IntPtr lparam)

**Comment by niksedk** [comment]
Could you add the subtitle file that causes this? Perhaps also a screenshots with the used settings...

**Comment by zhengstatic** [comment]
> 你能添加导致这种情况的字幕文件吗？也许还有带有所用设置的屏幕截图...

Thanks for the reply, I have solved it, the problem with the IP caused Google to not be used, now it works
