### ISSUE TITLE
Fix common errors in Chinese problem

### ISSUE THREAD

**Issue by TokerX** [SubtitleEdit/subtitleedit#6888]
There's a problem with the "fix common errors" in Chinese, the ellipsis (...) all get changed to the standard western 3 dots style, but in Chinese this should be 6 dots.

**Comment by niksedk** [comment]
Could you please add subtitle file and screenshots?

Do check this: https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by TokerX** [comment]
**State where and what you were doing.**

Fixing common errors on subtitle file.

**Attach a screen shot (use e.g. Alt+PrtScr or Win+Shift+S, please just use copy-paste and no image hosts) + text also (you can copy the text from an error message box with Ctrl+C)**

![elipses](https://user-images.githubusercontent.com/21122003/235787461-102bfa45-bae9-4fcb-8aab-6f08d9e1418d.png)

As you can see it is suggesting to turn the 6 dots into 3. But when fixing common errors it should turn 3 into 6 and leave 6 alone.

Ellipsis ( …… )
In Chinese, the [ellipsis](https://en.wikipedia.org/wiki/Ellipsis) is written with six dots (not three) occupying the same space as two characters in the center of a line.[[2]](https://en.wikipedia.org/wiki/Chinese_punctuation#cite_note-gbt15834-3)[[13]](https://en.wikipedia.org/wiki/Chinese_punctuation#cite_note-14)
Unicode provides an explicitly centered U+22EF ⋯ MIDLINE HORIZONTAL ELLIPSIS character[[14]](https://en.wikipedia.org/wiki/Chinese_punctuation#cite_note-15) in addition to the inexplicit U+2026 … HORIZONTAL ELLIPSIS character.[[15]](https://en.wikipedia.org/wiki/Chinese_punctuation#cite_note-16)

**Attach a subtitle (either whole or a sample, attach on Github as a .zip file)**

[The 300 Spartans (1962).zh-Hant.zip](https://github.com/SubtitleEdit/subtitleedit/files/11377810/The.300.Spartans.1962.zh-Hant.zip)


**Check if the file "error_log.txt" contains useful information (and attach the file on Github if relevant)**

Not a en error.
