### ISSUE TITLE
A BUG and a question

### ISSUE THREAD

**Issue by despairTK** [SubtitleEdit/subtitleedit#6889]
BUG: When I select multi-line subtitles to change the capitalization, when the first letter of the sentence is capitalized, it will not be applied to each line, and individual lines will be missed. Not sure if this is a problem with my setup or if there is another solution.

Question: How to add a period to the end of each line of subtitles?

**Comment by niksedk** [comment]
Hm, I need more info to understand your issue

>Question: How to add a period to the end of each line of subtitles?

Do explain a bit more...

Also, do read this: https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by despairTK** [comment]
![1](https://user-images.githubusercontent.com/111871110/235667612-ebfe42d0-cfee-4259-8f16-edc30f829faf.png)

The first screenshot is the subtitle file I want to process. You can see that some sentences start with capital letters, and some do not. Then I need to capitalize the first letter of the sentence in each line. I select all the subtitle lines, and then right click and use "Change Case of Selected Lines"

![2](https://user-images.githubusercontent.com/111871110/235667627-8382f094-ce55-422d-a1a1-42faa6c6a131.png)

The screenshot of the second chapter is the "Change the case of the selected line" setting,

![3](https://user-images.githubusercontent.com/111871110/235667632-02b31127-bf4a-4efd-9bf4-84d8bc4e6caf.png)

The third screenshot is the processing result of "Change the case of the selected line". You can see that the program has processed some subtitle lines and changed the first letter of the sentence to uppercase, but some of them have not been modified, such as in the screenshot Lines 15, 19, and 14 of the

![4](https://user-images.githubusercontent.com/111871110/235667640-866c3342-0d8a-4c7d-a84e-765e31c47c9d.png)

The fourth screenshot is that I selected the 15th line of subtitles individually, and then performed "Change the case of the selected line"

![5](https://user-images.githubusercontent.com/111871110/235667642-e0a11017-49ed-4a6f-a5e6-acd78899a506.png)

The fourth screenshot is processed. It can be seen that the correct result can be obtained by selecting the subtitle of the 15th line and "changing the case of the selected line".

With the same setting, the correct result can be obtained by selecting one row alone, but some deviations will occur if multiple rows are selected.


Regarding the question "How do I add a period at the end of each line of subtitles?", I found a solution using regular expressions.

In "Multiple Replacements", fill in "[^.?!]$" in the search content, fill in "$0." in the replacement, and select a regular expression below, so that a period can be added at the end of the sentence.

You may wonder why I do this. In fact, some sentences in the subtitles recognized by whisper are very long without any punctuation marks in the middle. When they are handed over to machine translation, they will only get a super long sentence without punctuation Sentences with symbols. However, if the first letter of this long sentence is changed to uppercase, and a period is added at the end of the sentence, when it is handed over to machine translation again, the long sentence will be correctly broken and separated by commas.

**Comment by niksedk** [comment]
"Change casing" will look at the previous line and only change uppercase the first letter if the previous subtitle is far back or has a sentence ending.

**Comment by despairTK** [comment]
So how to change the first letter of the sentence in each line to uppercase? Is there a regular expression? or other methods? I myself tried some regex yesterday to change the initial case, but without success.

**Comment by niksedk** [comment]
You can set the periods first... e.g. with a regex or with "Toggle custom tags" from latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

![image](https://user-images.githubusercontent.com/1261331/235850166-b9b156d3-798c-4158-884c-e09786e7aa55.png)

![image](https://user-images.githubusercontent.com/1261331/235850241-17bef2fd-9279-4c63-9f1c-b100b6b675c2.png)


And then you can use "Change casing for selected lines".

Regex cannot do change casing as far as I know :(

**Comment by darnn** [comment]
I don't know the syntax for changing casing in SE's regular expressions, if it exists, but generally speaking it is possible: http://web.archive.org/web/20230130141415/https://www.regular-expressions.info/replacecase.html
