### ISSUE TITLE
Can we move subtitle lines up and down? 

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#6890]
If a line is not where it should be, if it should be one or more rows up or down, is there some solution to move it up or down? The possible solution is to make a blank row where we want to move this line, and copy (or cut) its content, and paste it into this position. It is not so elegant solution, it is not comfortable for work. Especially if you have that situation more than once. 

Is there a more elegant solution? I don't know about that. Or, can't be added some new things like:
1. copy or cut the whole line and paste it into the desired position
2. or, to have the option to drag the desired line to the new position. The dragged line just inherits the timing of the line where it is dragged, it is no problem. 

It would be very helpful when (like I have now) you have some super messy subtitles, where you must delete lines, and move lines, it is a very hard job, but it would be much easier with the features I mentioned. 

![Screenshot_1](https://user-images.githubusercontent.com/128191515/235543530-ce58e2f5-abf0-42cb-8e46-37a0ac497d14.jpg)

**Comment by niksedk** [comment]
You can use ctrl+x and ctrl+v

**Comment by Cyberyoda1411** [comment]
Thanks. That is it.
