### ISSUE TITLE
Export > Final Cut Pro + Image > Shadow color > Alpha > 0 > Error

### ISSUE THREAD

**Issue by dimailer** [SubtitleEdit/subtitleedit#6892]
Export > Final Cut Pro + Image > Shadow color > Alpha > 0 > Error

Windows Forms Thread Exception 
An application error occurred in Subtitle Edit 3.6.12.0 - 64-bit - Microsoft Windows NT 10.0.19045.0.

Error Message: Value of '0' is not valid for 'Value', Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value

Stack Trace:
at
System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
at
Nikse.SubtitleEdit.Forms.ExportPngXml.buttonShadowColor_Click(Object sender, EventArgs e)
at
System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)

**Comment by niksedk** [comment]
Thx :)

Should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by dimailer** [comment]
Thank you
