### ISSUE TITLE
[Feature Request] Is it possible to implement GPT4Free Subtitle Translation & Batch Subtitle Translate.

### ISSUE THREAD

**Issue by Kristijan1001** [SubtitleEdit/subtitleedit#6893]
There is a free version of ChatGPT 4 Model, and it can be ran locally also. Is it possible to have this as an option to translate subtitles. I think it will be instantly better than anything present right now.

Also we need a Batch support unless that is already in and i dunno how to use it.

Git

https://github.com/xtekky/gpt4free

**Comment by darnn** [comment]
This is not a free version of GPT4 you can run locally. It's a GUI (or something) for various paid or limited APIs (most of which are actually GPT3.5). You're really better off just using ChatGPT/Bing/Bard and typing "Translate into (language): (text you want translated)". Although at various points Bing and Bard have refused to translate things into Hebrew except by using online translation services. But I gather with more common languages there's no such issue.

**Comment by Kristijan1001** [comment]
> This is not a free version of GPT4 you can run locally. It's a GUI (or something) for various paid or limited APIs (most of which are actually GPT3.5). You're really better off just using ChatGPT/Bing/Bard and typing "Translate into (language): (text you want translated)". Although at various points Bing and Bard have refused to translate things into Hebrew except by using online translation services. But I gather with more common languages there's no such issue.

You are right.
