### ISSUE TITLE
Fix {\an5} and {\an8} tag when Exporting to PAC file

### ISSUE THREAD

**Issue by willy2019** [SubtitleEdit/subtitleedit#6894]
please note that {\an5} look like {\an8} when converting to PAC file
{\an1}, {\an2} and {\an3} are perfect
the location for {\an5} to {\an8} are wrong.
please find the screenshot.

**Comment by willy2019** [comment]
![1](https://user-images.githubusercontent.com/44941690/235909388-3bc23d4d-224f-4c15-8600-b0b488b25114.JPG)
![2](https://user-images.githubusercontent.com/44941690/235909395-19bfa1ba-bf67-4537-9cd9-1b373bb2a503.JPG)
![3](https://user-images.githubusercontent.com/44941690/235909400-bc694cbc-9221-4491-a2b1-3b286c8b8c5b.JPG)
![4](https://user-images.githubusercontent.com/44941690/235909401-d3597b96-c92b-43ca-8b1e-58d3f6096466.JPG)

**Comment by niksedk** [comment]
Works perfectly fine for me... in two different third party programs.
