### ISSUE TITLE
Buttons "Show earlier" and "Show later"

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#6897]
I am really, really sorry because I have some issues every day. But I use SE every day. And it is natural that I see some new things that could be fixed. 

When I go to Synchronization/adjust all times/all lines dialog shows. There are two buttons: SHOW EARLIER and SHOW LATER. Their purpose is to move the title earlier/later in the timeline. Of course, I use 100 ms as the time measurement, because it is very precise. When somebody makes some mistake in the subtitle and you must delete several lines, it is a big gap and you must click these buttons once for every 100ms. One click instead of 30 would be more than nice. 

So, you must click many, many times on these buttons when you want to move your title 5 or more seconds earlier or later. I catch myself, it is beyond my will,  I click on the button EARLIER and LATER just ONCE, expecting that it will continue to move in the desired direction until I lift my finger up from the mouse. But no. I must click, click, click, for every 100ms, instead of just keeping the button pressed by my mouse until I am satisfied. 

Can it be fixed? I would like to press the button ONCE and the title to move until I lift my finger from the left mouse button. CAN IT BE DONE? It would be more than comfortable for editing. One-click instead of many. 

![Screenshot_1](https://user-images.githubusercontent.com/128191515/236059652-5e16fa12-fbd2-411a-9570-a3faa18fb565.jpg)

**Comment by LeonCheung** [comment]
In that case, you may want to use this feature instead:
![image](https://user-images.githubusercontent.com/494788/236096942-4aed8a2b-164d-4fb0-a099-81c4734212a3.png)

**Comment by Cyberyoda1411** [comment]
Leon, this is a very good solution. Let's see what Nikolay will say, but if he can't implement what I suggested, your solution is close to what I wanted. Personally, I'd like to have more control by one click moving of the title, but this works nicely too.

**Comment by niksedk** [comment]
I almost always use the waveform when syncing:

Mostly just "Left click+Ctrl+Shift" for "Set start of and offset the rest".
See these shortcuts:
![image](https://user-images.githubusercontent.com/1261331/236208954-3c47b965-6a4c-4c46-b393-3badf108fa83.png)

The buttons works as default. You can probably select a button and use space or enter for repeating, but the above is a better solution IMO.
