### ISSUE TITLE
Solving a Duplicate Shortcut

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#6899]
There is already a shortcut called "**Play from just before text**", with is **Shift** + **F10** by default. However, I found that the letter **T** is also used for that by default, and it seems undocumented either. I found this issue because I'm experiencing sort of a weird conflict when assigning T for some other shorcut. So maybe we could remove the second binding so that we could use **T** for other shortcut please?

**Comment by niksedk** [comment]
Hm, I cannot re-create this... just pressing "T" in the waveform or list view does "Play from just before text" for you?

**Comment by LeonCheung** [comment]
Yes, I've confirmed that with a clean beta build. What's interesting is that it occurs for Create/Adjust mode, and no problem for Translate mode. However, when totally hiding the Translate/Create/Adjust panel, everything is fine.

**Comment by LeonCheung** [comment]
In waveform.

**Comment by niksedk** [comment]
Try https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Hm, I'm afraid it still occurs. Especially in **Adjust** mode, I just found some other undocumented one-key shortcuts, e.g.:

S for setting start time; 
N for setting end time;
E for setting end and go to next;
R for Setting start and offset the rest;
and T.... XD

**Comment by LeonCheung** [comment]
NVM, I saw you just made another commit. I believe it will be tested in the next beta build.
