### ISSUE TITLE
Feature request: Find History

### ISSUE THREAD

**Issue by vsemozhetbyt** [SubtitleEdit/subtitleedit#690]
Could you add history list to the find dialog, please.

**Comment by niksedk** [comment]
It's already there... you mean persistent after restarting?

**Comment by vsemozhetbyt** [comment]
Sorry, yes, I do mean persistent one. For example, I've just split some subtitles by key word «Chapter N...» and each time I had to enter the  key word manually for new subtitle file after SE restarting.

**Comment by niksedk** [comment]
Does 15 sound like a reasonable number of history find items?

**Comment by ivandrofly** [comment]
I think 10 would be nice :wink:

**Comment by vsemozhetbyt** [comment]
I think 15 is OK and even 10 would be enough. Thank you a lot.
