### ISSUE TITLE
Unexpected behaviour when open .VTT subtitles

### ISSUE THREAD

**Issue by DeicPro** [SubtitleEdit/subtitleedit#6900]
Opening .vtt file increments magically 1,483ms globaly and add/change/remove a lot of properties.

[Original and opened .VTT files](https://github.com/SubtitleEdit/subtitleedit/files/11405702/vtt.zip)

Example
![Captura desde 2023-05-05 13-20-06](https://user-images.githubusercontent.com/12710770/236445072-0e86cd25-10b6-445b-aec8-229daa58b5ec.png)

Preview on SubtitleEdit
![Captura desde 2023-05-05 13-17-44](https://user-images.githubusercontent.com/12710770/236445066-bf9a1f2f-b300-4a16-8433-40c60a6d57de.png)

Opened VTT on VLC
![vlcsnap-2023-05-05-13h14m18s040](https://user-images.githubusercontent.com/12710770/236444953-01173a5e-a3bd-4d96-b4fd-643c15c5a138.png)

Original VTT on VLC
![vlcsnap-2023-05-05-13h13m22s150](https://user-images.githubusercontent.com/12710770/236444950-e12bd2b3-ac38-4658-8fb4-6b9bdb26f5a7.png)

If more info is needed, tell me please.
Thank you so much.

**Comment by niksedk** [comment]
This file has a timestap command `X-TIMESTAMP-MAP=MPEGTS:133508,LOCAL:00:00:00.000`.

You can make SE ignore this via un-checking "Use X-TIMESTAMP-MAP header value":
![image](https://user-images.githubusercontent.com/1261331/236456779-a25f95ae-4f01-47bd-a3b4-ec838ff4347e.png)

**Comment by niksedk** [comment]
Latest beta should now have a better preview in mpv: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip

**Comment by DeicPro** [comment]
> This file has a timestap command `X-TIMESTAMP-MAP=MPEGTS:133508,LOCAL:00:00:00.000`.
> 
> You can make SE ignore this via un-checking "Use X-TIMESTAMP-MAP header value": ![image](https://user-images.githubusercontent.com/1261331/236457143-c5e5f009-be5e-45c4-a5ef-5a854bbc3cf2.png)

Ty, but I tried that before and made no difference. I tested removing the line from the file before opening and that did the fix of the 1,483ms increment.

I will edit the issue to remove the thing about the time.

**Comment by niksedk** [comment]
New issue with details?
