### ISSUE TITLE
VTT subtitles are modified automatically when opening the file

### ISSUE THREAD

**Issue by DeicPro** [SubtitleEdit/subtitleedit#6901]
Opening a .vtt file add/change/remove a lot of line's values.

**Original on VLC**
![vlcsnap-2023-05-05-13h13m22s150](https://user-images.githubusercontent.com/12710770/236465357-cc0cc3c9-6dee-4065-b050-7e0a9559c578.png)

**Modifications applied automatically when open the file in SE**
![vlcsnap-2023-05-05-13h14m18s040](https://user-images.githubusercontent.com/12710770/236465363-cf7eb4b9-798c-4bc8-a077-427b25a355ea.png)

**Example**
```
Subtitle-C6_1
00:00:24.625 --> 00:00:29.791 line:71% 
<c.Subtitle-C6_1>That being the case, the idol fan is one</c>

Subtitle-C6_2
00:00:24.626 --> 00:00:29.791 line:78% 
<c.Subtitle-C6_2>who wants to be skillfully lied to.</c>

Song-C6_1
00:00:25.125 --> 00:00:26.875 line:85% 
<c.Song-C6_1>Let's ride!</c>
```

**Modifications applied automatically when open the file in SE**
```
00:00:24.625 --> 00:00:29.791 line:50%
<c.Subtitle-C6_1>That being the case, the idol fan is one</c>

00:00:24.626 --> 00:00:29.791
<c.Subtitle-C6_2>who wants to be skillfully lied to.</c>

00:00:25.125 --> 00:00:26.875
<c.Song-C6_1>Let's ride!</c>
```

**Another example**
```
Caption-C1_1
00:00:06.416 --> 00:00:10.708 position:40% line:57% align:left 
<c.Caption-C1_1>B Komachi</c>
```

**Modifications applied automatically when open the file in SE**
```
00:00:06.416 --> 00:00:10.708 line:50%
<c.Caption-C1_1>B Komachi</c>
```

**Files**
[original-and-opened-vtt.zip](https://github.com/SubtitleEdit/subtitleedit/files/11406474/original-and-opened-vtt.zip)

**What I expect**
An unmodified file exactly as original when open it with SE.

**Edited:** Just in case, I tried too to delete all values in File > WebVTT (.vtt) properties > alignment, and that also modify the file, deleting the properties of all lines.

**Comment by niksedk** [comment]
SE only supports 9 positions in VTT atm:

![image](https://user-images.githubusercontent.com/1261331/236473038-19be8498-768f-4f5a-b92a-2b1efc96769e.png)
