### ISSUE TITLE
When insert line, it adds 1ms delay

### ISSUE THREAD

**Issue by steam3d** [SubtitleEdit/subtitleedit#6902]
![image](https://user-images.githubusercontent.com/30986874/236502621-9f2435a5-b6b4-4f0f-8a98-7ebf0b00451c.png)

![image](https://user-images.githubusercontent.com/30986874/236502874-99d29488-2145-4a40-ba45-8fb778b995f6.png)

End time is  00:00:03,000, but start time of next line is 00:00:03,001 instead of 00:00:03,000

**Comment by niksedk** [comment]
Thx for the info :)
Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
