### ISSUE TITLE
UI - Minor Fix

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#6908]
A small problem here....
Brazilian Portuguese

![cats](https://user-images.githubusercontent.com/64425752/236635381-6a4fbeb3-fd45-426d-8857-f37540d97562.jpg)

**Comment by niksedk** [comment]
Thx :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
