### ISSUE TITLE
Update SubtitleEdit Snap

### ISSUE THREAD

**Issue by kallekruse** [SubtitleEdit/subtitleedit#6909]
Thanks for this great application!
I am using the SubtitleSnap on Ubuntu and trying to rip subtitles from a DVD seem to be facing this bug: https://github.com/SubtitleEdit/subtitleedit/issues/6523
Any chance to get a version upgrade for SubtitleEdit packaged as Snap?

**Comment by kallekruse** [comment]
Ah sorry, looking at the patch that solved that bug it seems to be a different issue than mine.

**Comment by niksedk** [comment]
Sorry, I don't know anything about Snap... you can try this: https://www.nikse.dk/subtitleedit/help#linux
