### ISSUE TITLE
[Feature Request] Export Shot changes as timecodes

### ISSUE THREAD

**Issue by anu2170** [SubtitleEdit/subtitleedit#6913]
Currently, when exporting the shot changes, we have options for Frames, seconds, and milliseconds.
Is it possible to allow for the export of the timecodes?

**Comment by niksedk** [comment]
In which time-code format? HH:MM:SS,MS ?

**Comment by anu2170** [comment]
Hi,
The format I would like is HH:MM:SS:FF.
Example 01:44:19:03
And just to clarify FF is for the frame

**Comment by anu2170** [comment]
Wow, awesome. Thanks a lot!
