### ISSUE TITLE
Minor bug (to fix) in FIND/REPLACE when you click YES button when the word was't find

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#6916]
FIND/REPLACE option has a message dialogue that says **the search item was not found**. If you click NO, everything will work just fine. If you click YES (the searching to go from the top and the searching to be performed one more time), you won't get the dialogue 'the search item was not found' anymore. No matter what. In both dialogues, in FIND, and in REPLACE. 

That means that some variable was set and it wasn't changed to the initial value, so there is no way to dialogue to be shown again. 

If you close SE and reopen it, everything will be OK. Until you click YES, everything works fine. When you hit YES, no dialogues that the word wasn't found, you won't get it.  

![Screenshot_2](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/d320b989-ec72-4dd8-92aa-6bbcde3daf4d)

**Comment by niksedk** [comment]
Works for me... I think...

**Comment by Cyberyoda1411** [comment]
Sorry because I reopen this topic again, but it doesn't work. If you click YES on the message that there are no more given word in the search or replace, you WON'T GET ANY MESSAGE in the future. Until you close and open the program again. 

On the other hand, if you click on NO, the program will work normally. Message dialogue with YES/NO will show up when it is necessary. But if you click YES, no more dialogues, it doesn't matter if the word didn't found or there are no new occurrences, there are no more dialogues.

**Comment by niksedk** [comment]
Could you spell it out for me via screenshots? (I do not understand the problem...)

**Comment by Cyberyoda1411** [comment]
Screenshots won't show anything, but I'll try to be more specific. 
Can you see dialogue **CONTINUE FIND?** The bottom one on my picture, below the FIND dialogue?  The message dialogue? Let's name it dialogue CONFIRM MESSAGE DIALOGUE. 

If you enter the search word in the Find (or Replace) dialogue, if there is a word FATHER, the program will find the word FATHER if there is that word, or as long as there is that word. When there is no FATHER, the CONFIRM dialogue appears and gives you three button options. YES, NO, CANCEL. 

If you click YES, to **'start from the top of the document and search one more time'** (this is written in CONFIRM DIALOGUE, you won't get CONFIRM dialogue ANYMORE. NEVER. You can enter a new word MOTHER, you can go to Replace dialogue, and enter the same word MOTHER, it doesn't matter if it is found or not, THERE IS NO CONFIRM MASSAGE DIALOGUE. The program WILL find all MOTHER words or no MOTHER word, but there is no CONFIRM dialogue anymore when there is no word MOTHER anymore. You can click on FIND button, but there is no CONFIRM dialogue. 

On the other hand, if you always click NO in the CONFIRM dialogue, everything will work fine. You will get CONFIRM dialogue when there is no more MOTHER or when there is no word MOTHER (at all) in the subtitle. It works as it should.


If you still don't get it .... The program works and finds the given word in all situations. That is OK. But if you click on YES in the MESSAGE dialogue, you won't get the MESSAGE dialogue anymore, You can change the word, but you won't get the message dialogue anymore. This is the bug. 

If we still don't understand each other, I'll make a Camtasia video to show it to you. If it is supported in GitHub.

**Comment by niksedk** [comment]
OK, maybe SE should just loop?
It seems many other programs do this...

**Comment by Cyberyoda1411** [comment]
OK.

**Comment by niksedk** [comment]
Is this any better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Is this more predictable? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by Cyberyoda1411** [comment]
Yes, that is it. You managed even the scroll to go to the first occurrence of the word when we hit YES (to go to the search again).
I had some (and sometimes I had this, maybe it when it is a new version unpacked???). I wrote the search word GOD, and nothing happened, it was just erased. Then again, it was erased again from the search field when I clicked on FIND NEXT. Then I reopened FIND and it works fine. You can check that initial status. Maybe it is when the program starts for the first time and some flags are not set yet.
