### ISSUE TITLE
Bug or something else? Unintetionally maximized dialog box makes all the others maximized

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#6917]
When I was trying to set OpenAI and the Whisper modes for the Audio to Text (Whisper) option, I (somehow) made the dialogue that asked for the whisper.exe file bigger. And it stayed big. I get the handles to resize it, but nothing happens. 

Now, I tried to open a new subtitle, and I still have a gigantic dialog File/Open, see the picture. What do I do wrong? This dialog where I choose the subtitle should be at least 4 times smaller and I can't resize it. I need a suggestion. It is not the end of the world, but it is a very unusual thing that I can't resize this dialogue (how could it so big?)

![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/bc9e5faa-dcbf-4955-8b8c-50484d813a5c)

**Comment by niksedk** [comment]
Double click on the title bar?

This is not a SE window, but a Windows window... so this is a Windows issue

**Comment by Cyberyoda1411** [comment]
You are the man. That works. Thank you.
