### ISSUE TITLE
[SubtitleEdit/subtitleedit]  application error in Subtitle 3.6.11.0- MS NT 10.0.19044.0. (Issue #6819) no solution so far (Issue #6881)

### ISSUE THREAD

**Issue by Lennie1200** [SubtitleEdit/subtitleedit#6920]
belongs to the ticketnumbers above I send you a screen shot with the error massage and a screen shot with installed plug ins and with the possible plug ins  
![image](https://github.com/SubtitleEdit/subtitleedit/assets/130572403/41d7ce56-8035-4bfc-8875-e32a0f7e2349)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/130572403/a8cf7af4-9ff5-41c4-ac45-a54840892e52)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/130572403/6c6168a2-93dd-44b8-a581-080411209903)

**Comment by niksedk** [comment]
Could you attach the source subtitle file?
It works fine here for me...

**Comment by Lennie1200** [comment]
Here it is:

Mit freundlichen Grüßen

i. A. Holger Albrecht
***@***.***<https://ifm.com/de>
Holger Albrecht
ifm group services gmbh
Friedrichstraße 1
Senior Projektleiter
45128 Essen
IT Demand and
Germany
Project Management
Tel: +49 201 2422-2280
Fax: +49 201 2422-1200
***@***.******@***.***>Contact me on ***@***.***>
E-Mail: ***@***.***

[ifm]<https://ifm.com/>
Sitz der Gesellschaft ist Essen HR B 32929 Amtsgericht Essen
St.-Nr. 112/5779/1682  USt.-ID-Nr. DE 348 579 437
Geschäftsführer: Prof. Dr. Bernd Buxbaum, Steffen Fischer, Thorben Petersen,
Stefan Schneider, Andreas Thürer

***@***.***<https://www.ifm.com/de/de/shared/moneo-iiot-plattform/produkte/testversion?utm_source=E-Mail&utm_medium=Footer&utm_campaign=moneo+30+Tage+Trial>
Von: Nikolaj Olsson ***@***.***>
Gesendet: Freitag, 12. Mai 2023 09:23
An: SubtitleEdit/subtitleedit ***@***.***>
Cc: Albrecht, Holger ***@***.***>; Author ***@***.***>
Betreff: [EXTERNAL]Re: [SubtitleEdit/subtitleedit] [SubtitleEdit/subtitleedit] application error in Subtitle 3.6.11.0- MS NT 10.0.19044.0. (Issue #6819) no solution so far (Issue #6881) (Issue #6920)


Could you attach the source subtitle file?
It works fine here for me...

-

**Comment by niksedk** [comment]
You need to attach the file on Github 
(Github does not support attachments from email)

**Comment by Lennie1200** [comment]
Here it is

**Comment by niksedk** [comment]
Github supports .txt or .zip...

**Comment by Lennie1200** [comment]
[ALPHR_DE_2.zip](https://github.com/SubtitleEdit/subtitleedit/files/11460866/ALPHR_DE_2.zip)
Here it is

**Comment by niksedk** [comment]
Hm, works fine here: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/e1ed1026-2c90-43ca-bc59-41fbf4f1f5c7)

**Comment by niksedk** [comment]
I guess the error message could be better...
