### ISSUE TITLE
Automatically set all subtitles to show before the next one

### ISSUE THREAD

**Issue by whentheis** [SubtitleEdit/subtitleedit#6924]
I have an .srt file with all the correct starting point, but the end point is wrong, every single line duration is 1 second. How may I automatically extend all the durations to before the next subtitle?

For example, line A keeps showing until line B, line B keeps showing until line C, etc etc.
I downloaded auto generated captions from a YouTube video, which does not have a correct end point

**Comment by niksedk** [comment]
Try Tools - Adjust duration - "Recalculate" is probably what you want:  
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/67216d54-e570-4ecb-9da4-3bd2779e0d0f)

**Comment by whentheis** [comment]
> Try Tools - Adjust duration - "Recalculate" is probably what you want: ![image](https://user-images.githubusercontent.com/1261331/238136274-67216d54-e570-4ecb-9da4-3bd2779e0d0f.png)

Hi! Thanks for replying so quick.
Yeah, I've already tried that before, and that is not what I wanted.

I'm gonna give another example

Line A, starts at 00.00, ends at 01.00.
Line B, starts at 06.20.

How do I adjust Line A so the end point is the same as Line B starting point?

**Comment by niksedk** [comment]
Just lower the optimal chars which will give longer subtitles (to e.g. 12) or use  a fixed duration of 10 seconds.

(Check the note, that display time will not overlap with the next.)

**Comment by whentheis** [comment]
> Just lower the optimal chars which will give longer subtitles (to e.g. 12) or use a fixed duration of 10 seconds.
> 
> (Check the note, that display time will not overlap with the next.)

Ah, close enough for me, thanks

**Comment by niksedk** [comment]
You're welcome :)
