### ISSUE TITLE
Discarded space replacement in Multiple replacement template import

### ISSUE THREAD

**Issue by OtaStrom** [SubtitleEdit/subtitleedit#6925]
When importing templates for multiple replacements, the space in the replacement field is lost.
For example, if I want to replace multiple spaces with one space, the space in the replacement is discarded, which means that spaces will only be deleted and not replaced.

**Comment by niksedk** [comment]
Thx for reporting this :)

Should be fixed now in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by OtaStrom** [comment]
Great. Thanks for fixing. :-)
