### ISSUE TITLE
how can apply auto adjust timing and use post processing to exists srt file

### ISSUE THREAD

**Issue by eagleftw023** [SubtitleEdit/subtitleedit#6932]
how can apply auto adjust timing and use post processing to exists srt file

![image](https://github.com/SubtitleEdit/subtitleedit/assets/130007636/a39d6cc3-0023-40b9-83e8-db981c1d0854)

**Comment by niksedk** [comment]
Right-click in the window, and choose "Run only post processing/time adjust":
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/514d71f0-44d9-4baa-930a-fd0c7cc1a2f1)
