### ISSUE TITLE
Randomly checks certain fixes when using 'Fix common errors'

### ISSUE THREAD

**Issue by Johnny-05** [SubtitleEdit/subtitleedit#6933]
When using 'Fix common errors', I'll select a few fixes and apply them. After it refreshes, it seems to randomly check certain fixes without me having selected them. Since I didn't notice this at first, I accidently ended up applying them with another set of fixes.

![issue](https://i.imgur.com/Q52CP07.png)

**Comment by niksedk** [comment]
Works fine here... how can I re-create this?
https://www.nikse.dk/subtitleedit/help#good-github-issue
