### ISSUE TITLE
MPC-HC disabled as the Video Player choice in SubtitleEdit's Video Engine

### ISSUE THREAD

**Issue by thiagojramos** [SubtitleEdit/subtitleedit#6934]
**- Problem Description:**
I'm having an issue with SubtitleEdit where I can't select "MPC-HC" as the Video Engine, even though it's my default video player on my Windows 11 system. The MPC-HC x64 option in the "Video Player > video engine" section is disabled (grayed out), and only DirectShow is available for selection.

**- Steps to Reproduce:**
1. I installed MPC-HC x64 using a custom installer and set it as my default video player in Windows 11.
2. I opened SubtitleEdit and went to the "Video Player > video engine" section.
3. The "MPC-HC" option is disabled for selection.

**- Expected Behavior:**
Since MPC-HC x64 is the default video player on my system, it should be available for selection in the "Video Player > video engine" section of SubtitleEdit.

**- Additional Information:**
As part of the troubleshooting process, I added the directory containing the "mpc-hc64.exe" file to the "system's PATH". However, this didn't resolve the issue. I'm attaching a screenshot showing the "Video Player > video engine" section of SubtitleEdit and the "environment variable" window displaying the directory with "mpc-hc64.exe" in the "system's PATH".

I appreciate any help or guidance I can get to resolve this issue.

**- ScreenShot:**

![2023-05-16 (1)](https://github.com/SubtitleEdit/subtitleedit/assets/45890502/1baa3030-f022-474f-95ec-f70cdc89defb)

**Comment by niksedk** [comment]
Is this better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by thiagojramos** [comment]
It worked great. Thanks a lot!! 

![2023-05-18 (4)](https://github.com/SubtitleEdit/subtitleedit/assets/45890502/29fbea82-ac93-4485-a9dd-bcecd239091a)

**Comment by Haikel-G** [comment]
> Is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

SE 4.0.8

![image](https://github.com/user-attachments/assets/c4adb67a-03fa-43a7-b525-004f921ba266)
