### ISSUE TITLE
[Deepl-pro plugin] Source turkish

### ISSUE THREAD

**Issue by tia3** [SubtitleEdit/subtitleedit#6935]
Hello,

Just get noticed plugin does not work if the source is set to turkish. (Source is really turkish)
Key is working, it translates from english to any language. But if the source is turkish it can't translate to any language. After the iteration all fields is empty.
rename the txt to srt, it could be an example.

Using SE 3.6.12
Deepl Pro 1.4 with api.free-deepl key.

[21.txt](https://github.com/SubtitleEdit/subtitleedit/files/11492358/21.txt)

could you please check this issue?

**Comment by niksedk** [comment]
Thx for the info :)

Hopefully fixed in version 1.5 of the plugin...

**Comment by tia3** [comment]
Thank you so much!

**Comment by mastercho** [comment]
@niksedk i can confirm this issue its exists on latest version once again
