### ISSUE TITLE
Sometimes won't open the original subtitle file (v3.6.13)

### ISSUE THREAD

**Issue by OSokil** [SubtitleEdit/subtitleedit#6936]
Sometimes won't open the original subtitle file. I'm did not find out the reasons. Sometimes it opens, many - not. 
Maybe that when opening the file, access to it is blocked by an antivirus

from log:
> SE: 3.6.13.0 - Microsoft Windows NT 10.0.19045.0 - 64-bit
> 
> System.IO.IOException
> Message: The process cannot access the file '****' because it is being used by another process.
> StackTrace:    at System.IO._Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at Nikse.SubtitleEdit.Core.Common.FileUtil.IsFileLocked(String fileName)

see `public static bool IsFileLocked(string fileName)`  method:
...
`            using (var stream = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.None)) `

replacing `FileShare.None` to `FileShare.Read` fixes the issue:

`            using (var stream = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.Read)) `

**Comment by niksedk** [comment]
Thx :)
