### ISSUE TITLE
could not find wav file

### ISSUE THREAD

**Issue by flgal** [SubtitleEdit/subtitleedit#6939]
v. 3.6.1.11

been working fine. i use it alot and not new at this.

all of a sudden,  now getting error message "could not find xxxx.wav"  file when trying to generate audio to text using Vosk PLUS does not work with whisper either

using windows 10 . did a system restore to back before latest update and that didn't help. any ideas

**Comment by niksedk** [comment]
Try re-downloading ffmpeg - go to Options - Settings - Waveform

SE 3.6.13 is latest version: https://github.com/SubtitleEdit/subtitleedit/releases
