### ISSUE TITLE
Suggestion to add an option to "Batch Convert" that can make each subtitle start a little earlier

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6951]
The "Adjust durations" option of Subtitle Edit's "Batch Convert", extends the duration of subtitles **only** at the end, and **not** at the beginning. So it allows you to make the duration of each subtitle longer at its end, so that the ending of each subtitle falls at a later point in time. However, it does not allow you to make the duration of each subtitle longer at its beginning, so that the beginning of each subtitle falls at an earlier point in time. In other words, the "Adjust durations" option only allows you to make all subtitles end a little later, not start a little earlier.

My suggestion is, to add an option to "Batch Convert" that can (independently) make all subtitles start a little earlier. More precisely, I suggest to rename the current "Adjust durations" option into "Adjust durations (endings)", and to add an analogous "Adjust durations (beginnings)" option that allows you to make all subtitles start a little earlier.

This distinction between 'beginnings' and 'endings', works well with "Adjust via Add seconds", because, with the suggested two versions of "Adjust durations", you can 'lengthen' the beginnings and endings of all subtitles independently. This distinction also works well with "Adjust by Percent", if you are using a percentage of the original subtitle length.

I don't know how to implement the distinction between 'beginnings' and 'endings' in "Adjust via Recalculate" and "Adjust via Fixed". Perhaps it is possible to implement these two sub-options in a way, that they only change the beginning of each subtitle, or only the ending of each subtitle. If it is not possible to make the 'beginnings' and 'endings' version of these two sub-options, work independently of each other — then this might be a way to implement "Adjust via Recalculate" and "Adjust via Fixed": If you have previously enabled such a sub-option in the 'beginnings' version of "Adjust durations", then the same sub-option may be automatically blocked in the 'endings' version of "Adjust durations" (and vice versa).

**Comment by uckthis** [comment]
Use Offset time codes and show earlier however many frames you want. Once done, then you can adjust duration and add the time to increase their duration (end).

Most professional subtitlers follow shot change rules and generally start time matches with a shot change and changing that will undo all the hard work.

**Comment by oep42** [comment]
@uckthis Thanks.

I don't know what "offset times codes" are, and I don't think in frames but in seconds and milliseconds. I'm just looking for an easy way to make all the subtitles in a SRT file start a little earlier without changing the time they end.

Currently, SE only provides an easy way to make all the subtitles in a SRT file end a little later without changing the time they start. If SE can provide an easy way to make all subtitles end a little later, then why not also provide an easy way to make all subtitles start a little earlier?

Maybe I'm a bit lazy. If you can explain how to use the method you are suggesting, or provide a link to a web page where it is explained, I would be very grateful.

**Comment by uckthis** [comment]
Offset time codes option is right above Adjust Duration option in batch convert. Once you select this option, it'll give you the option to add or minus time from all subtitles. You can choose Earlier or Later, but in your case you shall choose Earlier. What I'll do is change the start time of all subtitles to however many seconds you input. Once you're done, you can then use the Adjust Duration option to increase the duration of the subtitles.

**Comment by oep42** [comment]
@uckthis
Thanks a lot. That's a way to do what I was looking for. No need to add an option to "Batch Convert". (I guess I didn't look long enough at the options "Batch Convert" offers.)
