### ISSUE TITLE
Reverse disposition of text versus original text

### ISSUE THREAD

**Issue by Hayholten** [SubtitleEdit/subtitleedit#6953]
Hello everyone,

I open this topic to know if there was a possibility to reverse the text boxes in translation mode. The idea would be to have the original text box on the left and the text box that we translate on the right.

![SE-TextBoxes](https://github.com/SubtitleEdit/subtitleedit/assets/3150194/8434732b-2e4b-4574-b45a-93baf5b0861a)

Thanls a lot for your help ;)

**Comment by niksedk** [comment]
I'm not really sure... but does `<TextAndOrigianlTextBoxesSwitched>False</TextAndOrigianlTextBoxesSwitched>` set to `True` work for you?
(See Settings.xml in SE data folder)

**Comment by Hayholten** [comment]
Hello @niksedk,

Just perfect ! This is exactly what I was looking for ;)

Thanks a lot!
