### ISSUE TITLE
Suggestion to add an option to display Whisper progress information in a Command Prompt window

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6955]
When running a Whisper transcription through Subtitle Edit, no progress information is available. This is unfortunate when such a transcription takes a few hours to complete. 

There are Windows GUI programs that open and close a Command Prompt window when they run a "Command Prompt process". If this is possible with SE, I suggest to add an option to display Whisper progress information in a Command Prompt window while running a Whisper transcription through SE. (For an example of such progress information, see what WhisperX v2.0.1 displays by default when run from the Command Prompt).

**Comment by niksedk** [comment]
Try pressing F2 in the Whisper Window.

**Comment by oep42** [comment]
Thanks, that's what I was looking for. (Pressing F2 again, will return you to the normal "Audio to text" dialog box.)
