### ISSUE TITLE
No English base mode for Whisper

### ISSUE THREAD

**Issue by vivadavid** [SubtitleEdit/subtitleedit#6956]
Hi,

In Subtitle Edit (at least, in 3.6.12 and 3.6.13), it's not possible to download the English base mode for Whisper.

![English base model for Whisper](https://github.com/SubtitleEdit/subtitleedit/assets/9334287/aa13a646-1735-4e80-a947-c4776926c71b)

Such model does exist:

https://huggingface.co/ggerganov/whisper.cpp

Thanks.

**Comment by niksedk** [comment]
Hm, that works fine for me...

**Comment by vivadavid** [comment]
> Hm, that works fine for me...

Sorry, I forgot to check the Download list and the model was there. A few weeks ago, I must have downloaded all of the models except one by mistake. It was late yesterday when I was doing some testing with Whisper and my attention must have been poor.
