### ISSUE TITLE
how to find whisper-ctranslate2.exe？

### ISSUE THREAD

**Issue by Ansen-A** [SubtitleEdit/subtitleedit#6957]
Hello, I have already used whisper-ctranslate2 through the command line. It has a faster transcription speed than whisper and has good accuracy. I am glad to see that SE supports whisper-ctranslate2 now. I would like to call the whisper-ctranslate2.exe in SE, but I couldn't find the relevant files on https://github.com/Softcatala/whisper-ctranslate2. Could you please advise me on how to find this file?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/7991430/c09987ec-0d83-423a-99a5-6ccf6bbc104d)

**Comment by niksedk** [comment]
Whisper CTranslate2 command source is here: https://github.com/Softcatala/whisper-ctranslate2

Read more here: 
https://www.nikse.dk/subtitleedit/help#audio_to_text_whisper
https://github.com/SubtitleEdit/subtitleedit/issues/6914

**Comment by Ansen-A** [comment]
I apologize for making a mistake. I thought it needed to be packaged into a binary program for loading. I have found the script. Thank you once again.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/7991430/aab8eaba-ca4c-46ff-8538-74c6c64696a8)

**Comment by Policing2024** [comment]
When downloading file from github, this error msg appeared pls

This site can't be reached

[raw.githubusercontent.com](http://raw.githubusercontent.com/) took too long to respond.

Try:

Checking the connection

ERR_TIMED_OUT

**Comment by Policing2024** [comment]
But for more than a week, I can not download github files with all my
browsers, on Android or laptop these are the error msgs & Android please

**Comment by Policing2024** [comment]
But for more than a week, I can not download github files with all my
browsers, on Android or laptop these are the error msgs & Android please

**Comment by Policing2024** [comment]
Before iam using my android to download your latest subtitleeditbeta and
whisper faster.
But now i can not download any from my android or laptop, these are the
softwares i want to download and the error msg please

**Comment by Policing2024** [comment]
Hi
Im transcribing with SE 400 fine, but immediately when i updated purfview
153, it start showing no text found pls

**Comment by Policing2024** [comment]
How to use whisper faster xxl pls
