### ISSUE TITLE
Feature Req: Convert Excel to SRT

### ISSUE THREAD

**Issue by drkhateeb** [SubtitleEdit/subtitleedit#6958]
Hello all coders/developers of Subtitle edit
thanks for your extraordinary efforts 
I have an Excel sheet and I want to convert it to SRT
Scenario 1:
Excel is a mono language in this format:
**A column** = # serial number of titles
**B column** = Start time
**C column** = End time
**D column** = English Text
--------------------
Scenario 2: Excel is multilanguage
A column = # serial number of titles
B column = Start time
C column = End time
D column = English Text
E column = Translation-1
F column = Translation-2
G column = Translation -4
etc.
---------------------
the tool creates a separate SRT for Each Language
the user defines the numbers of languages in the Excel sheet
the created srt subtitles' names are based on the Language Name column

[[https://www.upload.ee/files/15259710/request.jpg.html](url)](https://www.upload.ee/image/15259710/request.jpg)

**Comment by Seesen1** [comment]
Hi,
i hope my code helps a bit for your translation in Excel,this is an basic Function to translate. 
example:  Translatetext=ranslateEnDe("Whats wrong?2, "EN", "DE")    for translate the englisch Text to German.

**Public Function TranslateEnDe(EnText As String, fromTL As String, ToTL As String)
    Dim http As Object
    Dim url As String
    Dim translation As String
    Dim englishText As String
    Dim Splittext() As String
    englishText = EnText 
    
    Set http = CreateObject("MSXML2.XMLHTTP")
    url = "https://translate.googleapis.com/translate_a/single?client=gtx&sl=" & LCase(fromTL) & "&tl=" & LCase(ToTL) & "&dt=t&dt=t&q=" & englishText
    
    http.Open "GET", url, False
    http.send
    
    Splittext() = Split(http.responseText, """")
    
   ' Debug.Print Splittext(1) 'Type Text to Console
    TranslateEnDe = Splittext(1)
End Function**

I dont know you have an Code for write the Sheet as .txt or .srt?

But i love Subtitle-Edit, its so powerful. I want a request for CLI, to translate srt (Build-in in the GUI) and save as "srt"!

**Comment by drkhateeb** [comment]
Hello [Seesen1](https://github.com/Seesen1)
thank you for this code
best
