### ISSUE TITLE
What to do if you want to change the order of the two lines?

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#6959]
I think this doesn't need any programming, it is just my ignorance. But I have had this problem since day 1 when I use SE. 

What if you have two lines that need to change the order? For instance, I want lines 2 and 3 to exchange their places, I want line 3 to go BEFORE line 2. That is, the text 'Why do I come up with this guy?' to come BEFORE the text 'Caveman'.
2
00:00:28,128 --> 00:00:30,128
Caveman.
3
00:00:31,001 --> 00:00:33,001
Why do I come up with this guy?

![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/c79194ca-b259-46ba-bb55-d92e350a71b0)

See the arrow to START TIME (on the left). My (wrong) solution is to use arrows on START TIME and to push line 3 to the left, that is, to use MINUS (down arrow), and to push line 2 to the right, to use PLUS (up arrow) to push the line 2 to the right. Visually, everything looks nice in the spectrogram (wave representations). But, it still can't change the order of these two lines. After this operation, line 3 is in minus timing, and line 3 is in overlap. These two lines stay where they are in the subtitle view, and the timing is not right. 
![Screenshot_2](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/1f9ae2e4-3eee-4431-8a6c-951d2650b0e8)

This picture says that the lines didn't change the place, just timing. Line 2 is on 32 seconds, and line 3 is on 28 seconds. They overlap, but they didn't change the position in the subtitle. Everything is the same, just the timing has changed. 

There is a solution, but it is totally clumsy. I can copy line 3 and delete it. Then insert a new line before line 2, and copy the text from the clipboard. But I think it is not an elegant solution. Or this is the ONLY solution?

**Comment by Cyberyoda1411** [comment]
I know that it can be solved with ctrl+c, to copy line 3, then paste it to line 1, and it will go to position 2. But, it is still the problem with the overlapping, The position of the subtitle will be OK, but we will have two subtitles at the same position, in wave representation it is hard to know which is which, sometimes they will be totally overlapped.

**Comment by jmaraujouy** [comment]
@Cyberyoda1411  Have you tried sorting it by time?

`Tools -> Sort by -> Start time`

**Comment by Cyberyoda1411** [comment]
Nice. It is a very good idea. To go to minus timing, then to sort the lines and they swap the places. This is a good solution. 

Copy/paste solution is also pretty good. But it must be resolved with a very messy job, by trying to find which is which in the overlapped waveform representation. 

I am still waiting for some more efficient and elegant solution if there is any.

**Comment by Cyberyoda1411** [comment]
Your solution also works with copy/paste, to sort by the start time. This is the solution for the overlapping mess. 

Again, let's see if somebody has some more elegant solution, it is not bad to see that. But your idea is brilliant to resolve every wrong minus timing. Though it is tedious to go Tools/Sort by/start time. There is no shortcut option for this thing. 

When you are here, how works Tools/merge short lines???? It doesn't merge short lines, I can't see it does anything.

**Comment by Cyberyoda1411** [comment]
Very good! Nice. That is a great thing to make the work faster. Thanks. 

We are still waiting for Nikolaj or somebody else for some more elegant solution... (if there is one).
