### ISSUE TITLE
Feature Request: Merge lines AND unbreak

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#696]
I wonder if it is possible to ask for a feature like "Merge selected lines and unbreak". For many many times, in order to merge two short lines as one single sentence, I have to first hit Ctrl Shift M, then click the "Unbreak" button. I found this is sort of inefficient. Highly appreciated for a new shortcut setting which can make this quicker.  :) Thanks!

**Comment by ivandrofly** [comment]
:+1:

**Comment by aaaxx** [comment]
How about making the feature smart and unbreaking only when the the resulting single line would fall within the length that's set in "Options > General > Unbreak subtitles shorter than" and otherwise just merge normally, one subtitle per line.

That would be better than unbreaking *all* merged lines and then later using "Auto br" for breaking too-long ones, because separate subtitles tend to be broken at semantically logical places and this way, as opposed to "Auto br", the place would be preserved as a line break when merging.

**Comment by LeonCheung** [comment]
Yeah, that sounds reasonable.

**Comment by aaaxx** [comment]
Could you give some examples (no offence, I'm just trying to figure out specific use cases)?

**Comment by LeonCheung** [comment]
Sure. Take one example:

You know, sometimes we need teamwork to working on subtitles. I mean, one guy does the transcription, another guy does the timing work, while a third guy does the reviewing work, etc. But unfortuanately, the transcription guy did a very good transcription work, but poor line breakings. Now, the second guy import the plain text by checking "one line is one subtitle" option. He has to merge some lines into one so that he could manually in to one single line, or split it again in a better way.

Now the thing is, when I select two lines then hit **Ctrl Shift M**, SE won't merge them into a single line (unless the total length is beyond the *Single line max. length* setting), but into two lines in one subtitle paragraph instead. Even I've set the *Single line max. length* to **100**, and the *Unbreak subtltes shorter than:* option to **99**, it stll keeps the break in the result. (**I assume this is a bug?**), which is unwanted in very common cases. Because we usually have to follow the "one line per subtitle" rule.

Take a real example:

line_n:
**I don't know**

line_(n+1):
**if you agree with me on this.**

After merging: 
**I don't know
if you agree with me on this.**

Expected:
**I don't know if you agree with me on this.**

When timing a transcription with very poor line breakings, we have to click the Unbreak button for countless times... I'm sure you can imagine the pain. (and this is just one of many examples/cases)

But, sometimes we DO NEED to keep exactly what SE currently behaves. I mean to keep the break, to have a "two lines per subtitle" thing work. Cases: merging dual-language lines, lyrics, chats/dialogues, etc.

So, I think all I want is either or both of below:

1. Improve/fix the *Unbreak subtltes shorter than:* option, if it is sort of problematic.
2. Add a new shortcut to allow merging lines without keeping the break. I assuem this can simply be processing a batch? (merge + unbreak)

Hope I've made myself understood a bit more. :)

**Comment by xylographe** [comment]
What would you expect if one of those lines (or perhaps even both)  contains a line break?

For example:

line(n)
**I don't know**

line(n+1)
**if you agree`<br />`with me on this.**

**Comment by LeonCheung** [comment]
I would respect this one. Because the break lives for a reason (right or wrong). If it is a right one, then why not keep it? If it is a wrong one, then Merge should not be the one to blame. It's not his job actually——His job is simply merge two lines **with or without THAT break**, not THIS one.  :)

However, since SE currently forces a single subtitle paragrash with no more than 2 lines (unless editing in Source View mode manually. I don't know why this limit came out), things here need to be considered though.

**Comment by OmrSi** [comment]
@niksedk Closed.
