### ISSUE TITLE
Is there any fast way to merge A LOT of short lines with very short duration (under 1 second)

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#6960]
I know that we can select a line and right-click/Merge with the line after (before), but sometimes the title is full of these kinds of short lines with short duration, under 1 second. In this case, you must repeat this process many, many times. 

![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/f3962f31-2167-4733-929c-743f776e8ff0)

Is there any way to do it automatically, it doesn't need to be very precise, but to shorten the whole process.

I give you an srt file with A LOT of short lines with short duration. 

[According To Jim S07e03 Safety Last.zip](https://github.com/SubtitleEdit/subtitleedit/files/11553933/According.To.Jim.S07e03.Safety.Last.zip)

**Comment by rRobis** [comment]
Maybe you can try:

1. Tools -> Merge Short Lines

Not sure if it works in your situation. You can try playing around with the settings

**Comment by Cyberyoda1411** [comment]
I tried it. It doesn't work. To be honest, I don't know what this option does. It takes some arbitrary short lines and merges them together. I used (just now) a subtitle and this option chose only two lines to merge them. Not the others.

**Comment by rRobis** [comment]
I just tried it with your file, with these settings:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/5c93bf53-56e4-477c-9867-0a9c5b623d4e)

And i think it does what you asked for, if i understood correctly.

You can try adjusting the maximum character count, and maximum line length in milliseconds.

[Merged subtitles](https://github.com/SubtitleEdit/subtitleedit/files/11570704/According.To.Jim.S07e03.Safety.Last_sfxy-ocr-mrg.-.MERGED.zip)

**Comment by Cyberyoda1411** [comment]
At least, you proved that this option works. It seems that we should uncheck ONLY MERGE CONTINUATION LINES, or nothing will be in the first textbox and there is nothing to merge.

Does it solve the problem? I don't know. Generally, yes, because it merges A LOT of lines in one, and the only lines with a duration under a second that are not merged, it is not done because the line upwards and the line downwards is too long to accept anything. 

I say 'I don't know', because this way packs too much in one line. There are 432 lines in the original file, and there are only 279 in the merged one. It is too much to shorten the subtitle to 153 lines. Too much packing. Maybe with some playing with the parameters, something nice can be done. 

Good job. Now we know that this option works and what is it for. The rest is to adjust the two parameters, as you said.

**Comment by Cyberyoda1411** [comment]
Hello Robis, I tested your theory, and it is more than well. 
1. We should count how many lines we have under 1 second. In this case, it is over 120. 
2. I didn't go more than 500 milliseconds, because it doesn't affect the count of merged lines. You have the counter NUMBER OF MERGES. So you change only MAX CHARACTERS PER PARAGRAPH and it will change the NUMBER OF MERGES counter. 

![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/dc5563be-0d78-4b48-bbd4-ac834adf6ca5)

3. You make your number of merges close to the number of lines with a duration of 1 second. That means, about 100 or a bit more. So, this is the number of lines to be merged, and not to produce too long lines. Just enough to merge the short ones. Of course, it doesn't work perfectly, it won't merge about 30 lines, but it is better than merging 120, one by one. 

Good team effort. And if Nikolaj adds something (the author of SE), it will be perfect.
