### ISSUE TITLE
OCR problems

### ISSUE THREAD

**Issue by bastauno** [SubtitleEdit/subtitleedit#6961]
Starting with Subtitle Edit version 3.6.11 I have noticed problems with the ocr of sup and sub files.
If,for example, I use subtitle edit 3.6.10 or 3.6.5, tesseract 5.2.0 or 5.3.0 (when needed by downloading them manually) and as engine mode tesseract+lstm, everything is fine.
From version 3.6.11 onwards, the ocr process is very slow but mostly it causes the program to crash, both with tesseract 5.3.0 and 5.2.0.
I don't know if it happens to anyone else. Hi everyone

**Comment by niksedk** [comment]
I cannot re-create this...
