### ISSUE TITLE
With the remove superfluous dialog dashes nothing happened

### ISSUE THREAD

**Issue by Tweaker12** [SubtitleEdit/subtitleedit#6963]
With the remove superfluous dialog dashes nothing happened. It is not detected in the filter (fix common errors) 

Hi, does anyone also have the bug with Subtitle Edit, that nothing happens with removing superfluous dialog dashes? It is not detected in the filter (fix common errors)

The intention is that Dialogs are always separated on two lines. Second line gets a dash. But if there is a dash on all 2 lines, Subtitle edit will not see this.

**Comment by niksedk** [comment]
Sample file / screenshots?
https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by Tweaker12** [comment]
![SE 1](https://github.com/SubtitleEdit/subtitleedit/assets/76883868/40d060b5-4164-4d29-b8a8-dbdff863cf6e)
![SE 2](https://github.com/SubtitleEdit/subtitleedit/assets/76883868/e0affd42-6067-482c-bfef-b4709b6b2512)
![SE 3](https://github.com/SubtitleEdit/subtitleedit/assets/76883868/f1fb7637-33cf-49dc-923b-42552d8a84e1)

**Comment by Tweaker12** [comment]
The log is empty, nothing was mentioned

**Comment by niksedk** [comment]
Go into Options - Settings, and set the dialog style:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/85062030-68fb-4159-9ae6-125a5525edbe)


Then use `Fix common errors`:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/de98fb9a-2ea2-4f86-a6f3-80d9722c87d2)

**Comment by Tweaker12** [comment]
Thanks this is the solution, it works. "Removing unnecessary dashes" (Translated Dutch to English) 
But the language changed to English "Remove dialog dashes in single lines"
Now I also see that the meaning is different in Dutch than if I change the language in SE to English. Now that the language has changed to English, it is understandable that the option I first chose has a different meaning than what is in Dutch.
