### ISSUE TITLE
A feature is missing.

### ISSUE THREAD

**Issue by keen0309** [SubtitleEdit/subtitleedit#6966]
Currently, there is only the option to play the selected lines, but there is no option to merge and export the selected lines as a video.

**Comment by niksedk** [comment]
Could you explain a bit more?
Also check this: https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by keen0309** [comment]
Splitting videos by subtitle lines and merging selected subtitle lines into a video。
The F5 function allows me to play the selected subtitle line. What I want is to export the selected subtitle lines as a video.

**Comment by keen0309** [comment]
> Splitting videos by subtitle lines and merging selected subtitle lines into a video。
> The F5 function allows me to play the selected subtitle line. What I want is to export the selected subtitle lines as a video.

Splitting videos by subtitle lines and merging selected subtitle lines into a video。
The F5 function allows me to play the selected subtitle line. What I want is to export the selected subtitle lines as a video.

**Comment by Purfview** [comment]
Subtile Edit is not video editor.

**Comment by niksedk** [comment]
You can do this via right-clicking on selected lines:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/22a4e64c-74d0-440e-bea5-2ec11b76360f)

**Comment by keen0309** [comment]
> You can do this via right-clicking on selected lines: ![image](https://user-images.githubusercontent.com/1261331/241576883-22a4e64c-74d0-440e-bea5-2ec11b76360f.png)

No, this function is to add the entire subtitle to the video export. My idea is to only select the subtitles I need and merge them into one video.
