### ISSUE TITLE
Option for allowing only Single Instance of Subtitle Edit

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#6968]
Sometimes i need to switch between multiple subtitle files, or make sure that i'm not editing another unsaved version of the subtitle file. Opening multiple instances can make a mess in some workflows.

There could be a checkbox in general settings: "Allow only one running instance"

If i would open new subtitle file, it would prompt to save the current file, and after saving, it would switch to the opened file and close the previous one.

**Comment by babywin** [comment]
I second this request based on the same arguments

**Comment by ChristianMalazarte** [comment]
Or have an option like VLC to open one instance when opened from file.

**Comment by rRobis** [comment]
> Or have an option like VLC to open one instance when opened from file.

I guess that's exactly what I'm asking (So that only one subtitle Edit could be opened)

**Comment by Onthrax** [comment]
This has my vote also.

**Comment by Apocalypse612** [comment]
Yes please!
