### ISSUE TITLE
Can someone help me? "An application error occurred..."

### ISSUE THREAD

**Issue by zzzzzaaaazzzz** [SubtitleEdit/subtitleedit#6969]
Can someone help me?
I keep getting this error whenever I try to open a video on SubtitleEdit.
I already downloaded the latest version, and I also downloaded FFMpeg. Nothing is helping.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/134885718/b014cbfb-44a1-4a91-9cc3-c294ab1483ac)

**Comment by niksedk** [comment]
Try using "mpv" as video player - see Options -> Settings -> Video player

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/b6c5e107-703a-43d1-ab25-d2c5a35973d8)

**Comment by zzzzzaaaazzzz** [comment]
> Try using "mpv" as video player - see Options -> Settings -> Video player
> 
> ![image](https://user-images.githubusercontent.com/1261331/241745100-b6c5e107-703a-43d1-ab25-d2c5a35973d8.png)

Thank you so much! IT WORKS!!!!!!!!!!!!!!!!!!!
