### ISSUE TITLE
Can Microsoft add text-to-speech functionality? This would enable subtitle voice-over narration.

### ISSUE THREAD

**Issue by ictsmc** [SubtitleEdit/subtitleedit#6971]
Our software is amazing. It can recognize speech and convert it into subtitles, as well as translate subtitles into various languages. If we add a new feature to synthesize speech from the subtitles and embed it in videos, it would be perfect. For example, we could use Microsoft's text-to-speech synthesis API to help us convert the content of the text into speech. Is this expression acceptable?

**Comment by niksedk** [comment]
Could you explain a lot more?

Also, do read this: https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by qihuoren** [comment]
Our software is amazing. It can recognize speech and convert it into subtitles, as well as translate subtitles into various languages. If we add a new feature to synthesize speech from the subtitles and embed it in videos, it would be perfect. For example, we could use Microsoft's text-to-speech synthesis API to help us convert the content of the text into speech. Is this expression acceptable?

**Comment by qihuoren** [comment]
> 你能解释更多吗？
> 
> 另外，请阅读以下内容：https://www.nikse.dk/subtitleedit/help#good-github-issue

https://azure.microsoft.com/en-us/products/cognitive-services/text-to-speech/

Using this API to add a voice button and automatically generate subtitles (.str) for what we are processing would be interesting. I'm not sure how it will be done, but it doesn't seem like a complex task and it will make many tasks easier.

**Comment by rsmith02ct** [comment]
That's a paid service isn't it? I use this with VEGAS Pro from subtitles I built with SubtitleEdit/Whisper.

**Comment by niksedk** [comment]
An early beta with TTS: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip
Press Ctrl+Shift+Alt+T in the main window:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/913205fd-6854-46c9-9c68-a471c7b508cb)
