### ISSUE TITLE
Suggestion to add the "Detect language" option to the Whisper language options

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6972]
Most (all?) Whisper engines offer the option "Detect language". 

This option can be useful if there are different languages spoken in a video and you want the subtitles to reflect the spoken language.
    I tested this with [WhisperX](https://github.com/m-bain/whisperX) version 2 in Windows PowerShell. It turns out that when the speech in a video transitions from one language to another, some of the audio near such a transition is not subtitled. These missing subtitles will have to be added later. Otherwise, multilingual transcription generally seems to work well, although language detection sometimes (very few times) detects the wrong language, and language detection does take some extra time. (The language is re-detected for each 15 to 60 second chunk of speech.)

This option can also be useful when processing a batch of videos in different languages, or for users who do not want to change the setting "Choose language" in the "Audio to text" dialog box, each time when transcribing another language than the previous one.

The option "Detect language" is missing in the "Choose language" setting in Whisper's "Audio to text" dialog box of Subtitle Edit. I suggest to add the option "Detect language" to "Choose language". (Whisper will use the "Detect language" option if no language is specified.)

**Comment by darnn** [comment]
This is neither here nor there as far as adding the option goes, but in my experience, if I have a video where, for instance, I have five minutes of language A, then five minutes of language B and then five minutes of language C, repeating, it's best to break them up into individual segments and process all of the language A segments together, then all the language B segments together and so on. As you've pointed out, Whisper itself doesn't really know what to do if there's more than one language in a file once it's already processing it as though it's in one specific language. It can't detect a new language and change into that on the fly, no matter what option you use.
