### ISSUE TITLE
(Speech to text)(No text found!) WhisperX and CTranslate2 related issues and desired features.

### ISSUE THREAD

**Issue by llurk** [SubtitleEdit/subtitleedit#6973]
I encountered some errors in Subtitle Edit (SE) while using the speech-to-text feature with WhisperX and CTranslate2. However, I managed to fix them by using the command prompt (cmd) without SE. I hope the developers can update the options so that users with older PCs, like mine with a GTX 1080ti GPU, can utilize these features without encountering these recurring problems.

Firstly, for machines with older GPUs like mine, running WhisperX with the default settings results in a "no text found" error. This is caused by my GPU only supporting compute type as int8, while WhisperX's default is float16.

The second issue involves the large model of WhisperX, which has two versions: large-v1 and large-v2. Using the syntax of SE can lead to an error and fails to call WhisperX. I'm not entirely sure about the specifics of this error, but I hope the developer can investigate it further.

The speech-to-text feature is one of my favorite aspects of Subtitle Edit, and I hope to see gradual improvements in these areas in the near future. Thank you.

**Comment by Sycosplat** [comment]
I also get the WhisperX "no text found", but it seems to be in calling the incorrect model when using large:

The error message you're seeing is due to the model size you're trying to use with WhisperX, it's trying to call a model called "large", but there isn't one.

```
ValueError: Invalid model size 'large', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2

This means that the model size 'large' is not recognized. Instead, you should use one of the following valid model sizes:

tiny.en
tiny
base.en
base
small.en
small
medium.en
medium
large-v1
large-v2
```

**Comment by frezer2011** [comment]
@llurk Здравствуйте! Как вы сделали это с помощью (CMD)? "текст не найден" Как исправить эту ошибку с помощью WhisperX

**Comment by morrellaberdeen** [comment]
Yes, I am experiencing the No text found issues with Ctranslate and WhisperX. This needs urgent fixing. But you said you solved yours at the command prompt. How did you do it?

**Comment by llurk** [comment]
u can check it here
https://github.com/m-bain/whisperX/issues/285#issuecomment-1569049792

**Comment by frezer2011** [comment]
@llurk  Thank you. That helped me!
