### ISSUE TITLE
[Dark Mode] Change highlighted text background colour in "Fix common errors" menu

### ISSUE THREAD

**Issue by THGhost** [SubtitleEdit/subtitleedit#6981]
I just found out about the dark mode and am really liking it. But is there any way to change background colour for highlighted text in the "Fix common errors" menu? I use this menu a lot but unfortunately for me it is barely readable.

![1](https://github.com/SubtitleEdit/subtitleedit/assets/32550606/fc5abd35-6267-4c61-af57-6c9c2463cc8d)
![2](https://github.com/SubtitleEdit/subtitleedit/assets/32550606/a2d85f8e-1ff1-41bc-b0bf-faa8dad33904)

My current dark mode settings:
![3](https://github.com/SubtitleEdit/subtitleedit/assets/32550606/564781c7-bf73-462a-8901-a03b97c11816)

**Comment by THGhost** [comment]
Any input on this would be greatly appreciated.

**Comment by niksedk** [comment]
thx for the info :)
Is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by THGhost** [comment]
> thx for the info :) Is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Yes, that is much better :)
