### ISSUE TITLE
Files opening multiple times

### ISSUE THREAD

**Issue by THGhost** [SubtitleEdit/subtitleedit#6982]
I'm using v3.6.13 and for some reason, whenever I import an MKV file, it asks me if I want to save the changes for it. After clicking "No", because I haven't even made any changes to it yet, it imports the MKV file again.

For MKV files with more than one subtitle, not only does it ask if I want to save the changes for it (I haven't made any yet!), it also asks me to choose which subtitle language I want from it twice, sometimes even three times, when it should only ask me once.

How do I stop this from happening?

**Comment by THGhost** [comment]
How do you mean?

**Comment by THGhost** [comment]
Annnd now it's doing it in v3.6.11 :(

**Comment by niksedk** [comment]
Please document each step you do with a screenshot here on Github.

**Comment by THGhost** [comment]
1. Import MKV file with multiple subtitles. SE asks which subtitle track I want to edit. So far, so good:
![1](https://github.com/SubtitleEdit/subtitleedit/assets/32550606/e912073a-489b-43c9-877f-15430ed3c13b)

2. After selecting which subtitle track I want to edit, this message then immediately pops up - asking me if I want to save the changes I made to the file I literally just opened and haven't made any changes to yet:
![2](https://github.com/SubtitleEdit/subtitleedit/assets/32550606/a9bb0075-c558-436a-8ab6-fed45a5f8ed9)

3. After clicking "No", because I haven't made any changes yet, SE then asks me again which subtitle track I want to edit:
![3](https://github.com/SubtitleEdit/subtitleedit/assets/32550606/1bc33aac-6639-4e1b-b673-1ce05981cdf9)

Sometimes it'll ask me if I want to save the changes again, sometimes it only happens the once.

Scratch what I said about it not happening in v.3.6.5 by the way, because it's happening on that now too. I did recently upgrade from Windows 10 to Windows 11. Maybe it has something to do with that?

**Comment by niksedk** [comment]
I cannot re-create this... you probably have a file opened in SE (with changes) before opening the mkv file...

**Comment by THGhost** [comment]
> I cannot re-create this... you probably have a file opened in SE (with changes) before opening the mkv file...

Nope, just the one MKV file open. It hasn't happened for a little while now though, despite me not doing anything differently. Using v.3.6.13 ¯\_(ツ)_/¯
