### ISSUE TITLE
the subtitles is not in order

### ISSUE THREAD

**Issue by faon-92** [SubtitleEdit/subtitleedit#6985]
please advice how to correct a disorder of the subtitles (see picture)
<img width="191" alt="SubtitleEdit_q7ywuZhhXr" src="https://github.com/SubtitleEdit/subtitleedit/assets/127494540/12b158c6-d0de-42e3-95da-2e48a5d60247">

**Comment by darnn** [comment]
Tools->Sort by.

**Comment by faon-92** [comment]
I got it, then I renumbered, 
thank you!
