### ISSUE TITLE
Feature Request: Break/split command on batch files.

### ISSUE THREAD

**Issue by Apocalypse612** [SubtitleEdit/subtitleedit#6988]
Please add the Break/Split long lines tool (from the Auto-Translate menu) to the list of commands available in Batch Mode. The options that are listed there perform different actions, though some are similar.

For example, if you combined "Split long lines", and "Auto Balance", there will be differences comparing the two results. Further, neither of these commands when used as a standalone does the same thing.

Thanks!

**Comment by BenJamesAndo** [comment]
I think the Break/split command is available in batch convert. But instead of being called Break/split it's simply called Split long lines.
