### ISSUE TITLE
When using Whisper AI with Translate feature, repeats lines

### ISSUE THREAD

**Issue by laonikoss** [SubtitleEdit/subtitleedit#6990]
I have a video with Japanese speech. I want to create subtitles in English.

If I use Whisper AI (CPP) with the Large (2.8GB) dataset and setting Japanese as the spoken language, and if I tick the "Translate" button within the WhisperAI dialog menu, I find that on some subtitle line it will get stuck and I will get the same line repeated from there until the end. 

If I only do Audio -> Text with WhisperAI in Japanese without translating from that dialog window, it transcribes into Japanese subtitles without any repeats/glitches.

I can then manually translate it into English using Google Cloud API but the problem is that it translates line-by-line and misses context, leading to quite illegible text. 

In the few sections where it works, ticking the "Translate" button in the Whisper AI menu leads to far better results when transcribing Japanese speech into English, however I get the glitch again and again and can't seem to work around it.

Any help would be much appreciated! (Attaching two subtitle files: one is Whisper AI with Japanese only; the other is with the Translate button ticked). I can send the original video too if useful.

[subtitle files repeat error.zip](https://github.com/SubtitleEdit/subtitleedit/files/11655815/subtitle.files.repeat.error.zip)

**Comment by niksedk** [comment]
I hope some future Whisper version will fix this...
