### ISSUE TITLE
The color palette does not display the subtitles correctly.

### ISSUE THREAD

**Issue by Gotas10** [SubtitleEdit/subtitleedit#6991]
I'm trying to convert subtitles from vobsub to srt, but I can't find a color palette to make the subtitles easy to see.
The vobsub subtitles are colored yellow.

Here I leave some images of what I mean and I also leave the subtitles that I was trying to convert from vobsub to srt, but as I mentioned before, the subtitles are not clear.
[Nuevo Archivo WinRAR ZIP.zip](https://github.com/SubtitleEdit/subtitleedit/files/11659837/Nuevo.Archivo.WinRAR.ZIP.zip)

**Comment by niksedk** [comment]
The ripped subtitles a badly ripped, try another ripper.

VLC show them like this:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/1f6f8500-18b6-45f6-97c4-ae08d4a7117f)

**Comment by Gotas10** [comment]
@niksedk , I extracted the subtitles with UsEac3To, and they were extracted in .sup format, then I opened it with Subtitle Edit and when I unchecked the "Use custom colors" option, the subtitles are clearly displayed, thanks.
