### ISSUE TITLE
Error when trying to enter Settings

### ISSUE THREAD

**Issue by JDTR75** [SubtitleEdit/subtitleedit#6998]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1891941/dbd88081-843c-46ea-81c3-7209870d1c02)

I'm getting this error with beta 36 when trying to open the Settings.

**Comment by niksedk** [comment]
Thx :)

Should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
