### ISSUE TITLE
Can we get the separator line between Merge with line before (after) and Extend to line before (after)?

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7004]
Look at the picture, when we right-click on the line of subtitle, we get the option to MERGE WITH THE LINE BEFORE (AFTER) and it is not easy to see it without reading all options in that part of the context menu. If we had the SEPARATOR line between MERGE and EXTEND options, it would be much more comfortable for work. When you make a subtitle for a couple of hours, it is not so comfortable to observe where is the MERGE WITH LINE AFTER is. See the picture. 
 
![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/65ae26fd-45da-48a6-83fa-fb161532bdf1)

It is nothing new in this program because there is a separator in the waveform if we talk about these options. See the picture. 

![Screenshot_2](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/61cb780b-bd26-4119-9ae6-c814574ad072)

**Comment by Cyberyoda1411** [comment]
I really don't know why this request is not approved. Lately, it seems that I am totally invisible in this forum. It is just a simple separator line, to make some options a bit more easier to find.

**Comment by niksedk** [comment]
Thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

I do not develop as much in the summer... and SE is a spare time project.
