### ISSUE TITLE
'Remove interjections' not cleaning all characters with Spanish proper punctuation...

### ISSUE THREAD

**Issue by jmaraujouy** [SubtitleEdit/subtitleedit#7007]
I think it would probably be better if I give some context regarding punctuation in the Spanish language, before explaining the issue. So, basically, for questions and exclamations the Spanish language uses two punctuation marks (one for opening, one for closing).

An expression like `Hi! How are you?` in Spanish it would be `¡Hola! ¿Cómo estás?`.

Here is the issue: This style of punctuation, which is completely different to other languages that only use a closing mark, causes SubtitleEdit to "leave some characters behind" when using the 'Remove interjections' feature.

Let's say we have the following subtitle:
```
- ¡Wow!    
- Increíble, ¿verdad?
```
It gets cleaned to this:
```
- ¡    
- Increíble, ¿verdad?
```
When it should be cleaned to this: `Increíble, ¿verdad?`

Here's a screenshot where this issue is noticeable:

![imagen](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/fabeb6d1-fa67-484d-9871-0a31e8ee7572)

I hope is something easy to fix. Thank you. 😁

**Comment by niksedk** [comment]
Hopefully better in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by jmaraujouy** [comment]
Yes! That's brilliant. Only just a little correction needed:

Now it removes the interjections with both opening and closing exclamation/question marks, but doesn't fix sentence case.
For example: `¡Oh, no!` become `¡no!` (in _small caps_).

Otherwise, this problem is completely fixed. Thank you so much, @niksedk !
