### ISSUE TITLE
Error when trying to add waveform

### ISSUE THREAD

**Issue by probit2011** [SubtitleEdit/subtitleedit#7009]
Hi,

I have installed Subtitle Edit (3.6.13.0 - 64-bit, Windows NT 10.0.22621.0) and VLC following the instructions/video on your website. However, when I try to create subtitles for an existing YouTube video (using "Open video from URL...), I am unable to add the waveform for the video. Upon clicking on the waveform area, I obtain the following Windows Forms Thread Exception error message:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/44330046/2f9c4ea7-19af-43ce-811d-27c729ff9358)

What could be causing this problem? Is it something I missed during the install?

Regards,

Patrick

**Comment by niksedk** [comment]
Try Options - Settings - Waveform, download ffmpeg, and re-try making a waveform again.

You can also take a look in the SE error log - should be located in "C:\Users\probi\AppData\Roaming\Subtitle Edit"

**Comment by probit2011** [comment]
> Try Options - Settings - Waveform, download ffmpeg, and re-try making a waveform again.

I did that, closed the app then restarted it. Same error message.

> You can also take a look in the SE error log - should be located in "C:\Users\probi\AppData\Roaming\Subtitle Edit"

There doesn't seem to be an error log file here:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/44330046/ca085a49-33f6-45a9-bf8f-b7c76fff8d91)

So where else could it be?

**Comment by niksedk** [comment]
Does the video have audio?
Are you out of disc space on drive C?

**Comment by probit2011** [comment]
Yes, the video has audio, here is the link (it's a cult French-Canadian movie): [https://www.youtube.com/watch?v=MABFy0WKFzA](url).

I have nearly 600GB of disc space left on my C: drive, so memory is not an issue.

I have since tried the following:

- Re-started my laptop; still the same result
- Uninstalled Subtitle Edit and re-install it; still the same result

I don't know what else to try...

**Comment by darnn** [comment]
For the record, it doesn't give me an error when I do this, but neither does it produce a waveform. The simple solution here is just to download the video from YouTube and open it in SE directly. Also, there's a better rip of this out there, but we should probably talk about that outside this forum, if you're interested: thedarnn@gmail.com
