### ISSUE TITLE
Uppercase letters and dots with audio to text vosk-api french

### ISSUE THREAD

**Issue by cslop3r** [SubtitleEdit/subtitleedit#7010]
Dear,
Are you using vosk-api or a script aside to know when a sentence ends and begins by adding uppercase letters and dots?

**Comment by niksedk** [comment]
SE uses custom code - also see Tools - Change casing...

**Comment by cslop3r** [comment]
> SE uses custom code - also see Tools - Change casing...

Thanks for answering! I meant how do you do that without using SE? Which librairy do you use?
