### ISSUE TITLE
Suggestion to add a shortcut for transcribing a subtitle line

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#7013]
When checking the subtitles of a video, I sometimes doubt the quality of a subtitle. Then, with that subtitle line selected in the List view, I do `Right-click/Selected lines/Audio/Audio to text (Whisper)/Generate` to see what subtitle Whisper would put there.

Sometimes, I do this quite often, which is why I suggest to add a shortcut for `Right-click/Selected lines/Audio/Audio to text (Whisper)/Generate`. Such a shortcut will immediately start generating subtitles for the selected subtitle line(s).

For those who want to check/change the settings in the "Audio to text" dialog box, an additional shortcut for `Right-click/Selected lines/Audio/Audio to text (Whisper)` may be a good idea.

**Comment by niksedk** [comment]
Something like this?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/6825852a-92c1-4db6-8c52-86b9b303f4bf)

**Comment by darnn** [comment]
While we're at it, could you possibly add one at some point for extract audio? I do that a fair amount to use WhisperX (or whatever) outside of SE, and currently you have to right-click and then go through two menus to get to it.

**Comment by niksedk** [comment]
@darnn: Like this?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/1c29ab46-ec1f-4065-af1f-16407ee7f5bf)

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Yeah, that's perfect!

**Comment by oep42** [comment]
> Something like this?

This is the shortcut that I suggested as an additional shortcut, which only opens the "Audio to text" dialog box, but doesn't start generating the subtitle. Thanks for letting me know this shortcut exists.

I didn't find that shortcut, because it is in the "Waveform/spectogram" category, and not in the "List view" category where I looked for it. Is there any way to (also) put it in the "List view" category? (For me, it makes sense to have a shortcut that does something with a subtitle line, in the "List view" category.)

The first shortcut that I suggested (which does not seem to exist) would be called something like "Audio to text selected lines (Whisper) + Start generating". Could you add a shortcut like this, so I do not have to click on "Generate", each time the "Audio to text" dialog box is opened for generating subtitles for the selected line(s)?
