### ISSUE TITLE
Previously generated waveforms won't reopen on first try

### ISSUE THREAD

**Issue by ParadoxDelta** [SubtitleEdit/subtitleedit#7014]
Edit: This issue doesn't occur when I generated a waveform for the first audio track in the file. It only occurs if I generated a waveform for an audio track other than the first one.

I'm having an issue where I open a new subtitle for a video with multiple audio tracks that I already generated one waveform for. Let's say I generated a waveform for the english audio track. When I open the video file with a new subtitle file and select the english audio track, the waveform field stays empty. When I click it again and select the english audio track again, it starts to generate a new waveform. In order to open the old waveform I have to go to 'video' - 'choose audio track' and select the other audio track. Then I have to open that path again and select 'english'. Now the previously generated waveform is displayed. 

I had this issue last year on Windows 10 but it went away after some time. Now I switched to Windows 11 and have the same issue again. What I've tried so far:
- Updating from v3.6.12 to v3.6.13
- Removing the windows write protection from the waveforms folder and all it's files
- Switched to waveform generation with ffmpeg
- Cleared the waveforms folder
- Restored the Subtitle Edit settings to default
- Deleted the Subtitle Edit folder under AppData/Roaming

Is there a solution to this problem?

**Comment by niksedk** [comment]
Hm, it's working fine here. How (installer / portable) and where did you install SE?

The portable version should be installed to something like "C:\Tools\SE" (no write protection)

The installer is fine under "C:\Program files\Subtitle Edit"... but all SE folders with writing should be in your roaming folder, like "C:\Users\nikse\AppData\Roaming\Subtitle Edit"
