### ISSUE TITLE
Feature Request (if not exist): Remove actors/effects in subtitle format .ass etc

### ISSUE THREAD

**Issue by lolipopsz** [SubtitleEdit/subtitleedit#7015]
is there a feature to remove actors/effects (in **SE batch convert**) for **.ass** subtitle format etc? (not removing the subtitle lines itself, just removing actors/effects)

like I want to remove any specified actors/effects which contains **"exp"** for example.
and also want to remove all actors/effects.

**Comment by artistry01** [comment]
You can use the trick with **Multiple Replace** (Ctrl+Alt+M) or Edit->Multiple Replace
Fill in the **Find what**  field with the necessary word, and leave the next field empty and add.  
Apply, this will automatically delete everything you don't need.

![flll](https://github.com/SubtitleEdit/subtitleedit/assets/130503228/48cb300f-25e7-4c35-bace-9774f998b306)
