### ISSUE TITLE
Suggestion to refine the option "Break early for end of sentence"

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#7019]
The result of the option "Options/Settings/Tools/Auto br/Break early for end of sentence (.!?)" is not always satisfactory. See the two examples below of what can happen when this option is active.

First example, before "Auto br":

> You know the flat with three bedrooms by the supermarket? It's

First example, after "Auto br":

> You know the flat with three
> bedrooms by the supermarket? It's

Second example, before "Auto br":

> impoverishes democratic public discourse. It

Second example, after "Auto br":

> impoverishes democratic public discourse.
> It

I suggest to add to the option "Break early for end of sentence", a sub-option for a minimum length of the text after the break that "Auto br" creates when breaking after the end of a sentence.

Perhaps this sub-option can be shared with this option: "Options/Settings/Tools/Auto br/Break early for comma".

**Comment by niksedk** [comment]
I do not understand the problem - SE is respecting the "single line max length"...

**Comment by oep42** [comment]
Sorry for being unclear. 

I find the result of the second example unsatisfactory, because the second line of that subtitle is only two characters long. I would prefer a result like this for the second example: 

> impoverishes democratic
> public discourse. It

To avoid unbalanced subtitles like the result of the second example in my earlier comment, I suggest to introduce a **minimum length** of the second line of a subtitle that results from using "Auto Br" with "Break early for end of sentence". So, when using "Auto Br" with "Break early for end of sentence" to break a subtitle, SE should only break at the end of a sentence, if the resulting second line of the subtitle will be longer than ... characters. (This ... is the value of the minimum number of characters of the second line of the resulting subtitle when using "Auto Br" with "Break early for end of sentence". For this value, I suggest to introduce a sub-option.) 

If there is a better way than the number of characters, to define the minimum length of the second line of a resulting subtitle, that would be fine too.

**Comment by oep42** [comment]
When using "Auto Br" with "Break early for end of sentence", unbalanced resulting subtitles can also be like this:

Third example, before "Auto br":

> you. I can only hook your curiosity.

Third example, after "Auto br":

> you.
> I can only hook your curiosity.

So not only the second line of the resulting subtitle can be very short, it can also be the first line. Therefore, the minimum length sub-option that I suggest, should apply to both the first and second lines of a subtitle that results from using "Auto Br" with "Break early for end of sentence".

Perhaps a better way to define the minimum length of the shortest line of a subtitle that results from using "Auto Br" with "Break early for end of sentence", may be a percentage of the length of the original unbroken subtitle. In this way, problems with minimum lengths that are too high can be avoided if the number of characters is used to define the minimum length.
