### ISSUE TITLE
Incorrect TextST DialogStyleSegment length in stream

### ISSUE THREAD

**Issue by cubicibo** [SubtitleEdit/subtitleedit#7021]
When exporting subtitles to TextST raw stream, DialogStyleSegment (0x81) packet has an incorrect header length. The value is always offset by +2 because SubtitleEdit includes the count of DialogPresentationSegment (uint16_t numberOfSubtitles using this specific style) in the length while it should not.

https://github.com/SubtitleEdit/subtitleedit/blob/f54fdbcb7f5d70e4780d83977764436256424d01/src/libse/SubtitleFormats/TextST.cs#L272-L275

Last line should be changed to `size - 5`.

Here's an example M2TS 0x81 packet from a commercial Blu-Ray.
```
000001BF 00638100 5E000002 00000000 01FB077F 01B00300 00000000 077E01AF 0102033C 00043604 05020100 00008D07 7F01B000 00000000 00077E01 AF010201 3C000436 01020200 1E001080 800001DA 8080FF02 1E8080C0 03108080 0004DA80 80FF051E 8080C007 DCEC1553 B0475800 316000FF FFFFFFFF
```
As you can see, bytes 0x07DC (= 2012) are not included in the 0x005E segment length. This is verified across numerous commercial Blu-Rays.

**Comment by niksedk** [comment]
@cubicibo: thx for the info :)

Latest beta also updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
