### ISSUE TITLE
Reguest: Video with burned in subtitles

### ISSUE THREAD

**Issue by Masina86** [SubtitleEdit/subtitleedit#7024]
Hello, Nikse. I really love SE and keep up the good work everyone. I have noticed that burned in subtitles dont have the option for "custom subtitle position" or maybe i cant see it. I work at the TV station and the people who still have analog signal cant see the button lines, they are cut. It would be nice SE to have this option like this 
![Custom Position](https://github.com/SubtitleEdit/subtitleedit/assets/73963066/7b72d9d2-0844-4079-823e-749edcd70683)

Also, the preview windows is nice but can it be with the actual video that u are trying to burn subtitles on, not just the chess dots with nothing on it. Sometimes the video really helps and save time to actually make the subtitles perfect. I rendered the video 4 times until I found the right font size and options. Something like this would be perfect.
![Preview1](https://github.com/SubtitleEdit/subtitleedit/assets/73963066/7f467b77-dd37-4332-a503-da990fca713b)

Thanks for this lovely product who keeps getting better and better and cheers to the community.

**Comment by niksedk** [comment]
OK, added preview of the whole video: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Using format "Advanced Sub Station Alpha" you can set the margins as you like:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/beec86d6-fa86-4631-a15c-f56270404f99)
