### ISSUE TITLE
Request idea: Navigation forward +seg

### ISSUE THREAD

**Issue by erichnagy** [SubtitleEdit/subtitleedit#7026]
I don't know if it's implemented and I didn't see it.
When I watch the video and want to fast forward, I press the -> key, but it only fast forwards so much. It could be added that with "Ctrl + ->" forward 30 seconds or "Ctrl + Alt + ->" forward 1 minute or be customizable. 
Thank you

**Comment by GrampaWildWilly** [comment]
<img width="960" alt="#01" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/8779e752-e766-4db1-ae0f-d995cfaa73cc">

**Comment by erichnagy** [comment]
Hi. Thanks for your answer.
Nice. Embarrassing that I didn't find it. 
But, is there an option for 30s or 60s forward? If it's possible.

**Comment by GrampaWildWilly** [comment]
Look again closely.  There's 4 particular shortcuts, 2 for going forward, 2 for going backward.  They all let you specify the size of the jump yourself.

**Comment by niksedk** [comment]
He, it's not super intuitive, but the "Adjust tab" has two time boxes:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/cd216982-5c9b-4449-b48b-9266bf8b4ae7)

**Comment by erichnagy** [comment]
Thank you.
