### ISSUE TITLE
Exporting to EBU STL under Linux broken

### ISSUE THREAD

**Issue by felagund** [SubtitleEdit/subtitleedit#7028]
How to reproduce:
1. On Linux, using mono, download this zip, extract it and open the sample SRT file:
[sample.zip](https://github.com/SubtitleEdit/subtitleedit/files/11811053/sample.zip)
2. Export it as EBU stl, setting code page number to 850

What should happen
An ebu stl subtitle with a newline and proper ü characters should display

What happens:
newline is lost and "u?" is displayed instead of "ü".

On Windows under Virtual Box, this works just fine.

**Comment by niksedk** [comment]
EBU writing is hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Please give it a test :)

**Comment by felagund** [comment]
@niksedk newlines seem to be respected (already on subtitle Edit 3.6.4), however the "ü" is still displayed as "u?", would you please reopen?
![Screenshot_20230904_152846](https://github.com/SubtitleEdit/subtitleedit/assets/1218098/e11c7a7f-bbfc-481d-9e7f-90561252ea53)

**Comment by felagund** [comment]
Thanks. I am on Kubuntu 22.04, I downloaded the beta linked about (is it the right file?), mono is at version 6.8.0 I think. I tested with VLC, as can be seen from the screenshot.

**Comment by niksedk** [comment]
Could you give latest beta a test run: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by felagund** [comment]
This seems to work. I tested both in Linux and under Virtualbox in Windows and the resulting files are now identical (same md5sum) and VLC displayes them with "ü". No more Virtualbox sessions for exporting EBU STL, yay, thanks a lot. (no matter that that format should die anyway :-D).

**Comment by niksedk** [comment]
You could also try: https://github.com/SubtitleEdit/subtitleedit-cli
(just updated)

**Comment by felagund** [comment]
I wish I knew that :-D.
