### ISSUE TITLE
[suggestion] add custom whisper command field.

### ISSUE THREAD

**Issue by tariq0101** [SubtitleEdit/subtitleedit#7030]
Hi, 
is it possible to add a custom command field because Whisperx supports diarization and that would be very helpful, also it would be great to fine tune the command to correct timestamps or make it translate after transcription.
and is it possible to add a console screen to see what whisper is doing and to view any potential errors?
thanks a lot for subtitle edit, literally the best in its field.

**Comment by niksedk** [comment]
Press F2 to see console... I will try to make an "Advanced settings" for inputting custom cmd line parameters

**Comment by niksedk** [comment]
Custom field added in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by tariq0101** [comment]
Thanks! that's great!

**Comment by MiskolcMiskolc** [comment]
> Custom field added in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Thanks! But can someone explain how to exactly use it? Especially to limit max characters. Thanks in advance.
