### ISSUE TITLE
Please provide support for 4k screen

### ISSUE THREAD

**Issue by YIRU69** [SubtitleEdit/subtitleedit#7036]
My computer is running Windows 11 and when I use this software with a 4k screen, to avoid font blurring, I have enabled the DPI settings in compatibility. Only when the DPI setting is set to "Application" will the font not blur. However, setting this option can cause visual errors, as shown in the following picture.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/48148292/8f0630cc-ccdf-4d40-bcbc-ab0e2374c1b6)

**Comment by niksedk** [comment]
Is this any better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
Have you tried all DPI settings?

I do not have a highres monitor so I cannot really help much with this... so any dev with 4k monitor please do help :)

**Comment by YIRU69** [comment]
Yeah, I tried all DPI settings, but it not worked. 
I'm sorry that it's not easy like this. I found a resource that might solve this problem, but I am not sure if it is feasible. Sir, I understand that it could be difficult, but if you have some free time and are interested, I would appreciate it if you could take a look at this issue. Thank you very much for your response to this question. Thank you.

**Comment by niksedk** [comment]
Did you test the beta too?

**Comment by YIRU69** [comment]
yes

**Comment by niksedk** [comment]
> yes

And?
The beta has the manifest file you linked to....

**Comment by eugenesvk** [comment]
FYI You could check this version https://github.com/SubtitleEdit/subtitleedit/pull/9637 (if you can't build, try [Windows downloads from here](https://github.com/eugenesvk/subtitleedit/releases/tag/4.0.13b)), which solves a lot of the DPI scaling issues for me (and doesn't require manually setting compatibility settings for the exe file)

It's still not perfect DPI-aware layout, but much better than the current version
Though I haven't tested with a 4k mon, but still with a scaled DPI version that avoids the artifacts on your screenshots
