### ISSUE TITLE
click on Apply should select / deselect everything

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#7038]
when in Fix common errors window, please make it so click on Apply deselects everything.

I often need just certain fixes, not all.
it's annoyance to deselect manually one by one

**Comment by jmaraujouy** [comment]
A quick fix is to click on 'select all', and then click on 'invert selection'.

**Comment by niksedk** [comment]
Also, in latest beta you can use some shortcuts in the list view:
Ctrl+A: select all
Ctrl+Shift+I: Inverse selection
Ctrl+D: De-select all

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

You can also do shift+click on a range in list views (somehow it does not work in the check-box column).
