### ISSUE TITLE
Set Start Offset the Rest with Custom Time

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#7040]
I have a video file with different on-screen timecodes during the video and a subtitle file with normal timcodes. For example, the video starts at 11:38:56:13 but three minutes in the video, the on-screen timecode cuts to 12:07:39:07. The client wants the timecodes to match the on-screen timecodes and I just can't figure out how to do it. With Offset timecode, it'll get the correct timecodes for the first three minutes of the video, but after that, it'll be 11:41:58:13 in the subtitle file and 12:07:39:07 on the screen. Is there a simpler way to do it? Or I was wondering if we could have the custom time in Set Start and Offset the Rest so I could just add 12:07:39:07 as my first value, and it'll reset the rest. If not, how about a calculator that will give the difference between 12:07:39:07 and 11:41:58:13 so I could just add that time in Show Later. 

This is how it's done in Ooona. 
![Untitled](https://github.com/SubtitleEdit/subtitleedit/assets/28671050/cbf12d07-8ece-4d92-99db-b258b572d7a7)

**Comment by OmrSi** [comment]
It's not really clear to me, but doesn't `Set video offset` do that?
