### ISSUE TITLE
Unable to edit in use subtitle file

### ISSUE THREAD

**Issue by witchpiggie** [SubtitleEdit/subtitleedit#7041]
This might be related to issue: #6986 

It appears to be a new behavior. I'm currently using version 3.6.13 and when viewing a video in VLC,
I am unable to open the corresponding srt file because I get an error about it being in-use. Previously,
I was able to open and edit these while watching. It's super inconvenient to have to close the video, then
reopen it and seek to where I was. The difference between this and the linked issue, is that the srt files are
separate from the video file, not embedded. In this case an mp4, and matching srt file.

**Comment by niksedk** [comment]
This should be fixed in latest beta I hope: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
