### ISSUE TITLE
Tesseract

### ISSUE THREAD

**Issue by doglover3920** [SubtitleEdit/subtitleedit#7044]
Trying to debug something else, I discovered several versions of Tesseract.
Can I delete the old versions?

![afbeelding](https://github.com/SubtitleEdit/subtitleedit/assets/3510990/69224d4a-46c7-4af6-9bb6-ec2aef865c86)

**Comment by niksedk** [comment]
Sure, delete all Tesseract folder but "Tesseract302" and "Tesseract530".

Next update will update to "Tesseract531" (and so "Tesseract530" can be deleted)
