### ISSUE TITLE
Batch OCR "Tesseract returned with code 1"

### ISSUE THREAD

**Issue by thealexmay** [SubtitleEdit/subtitleedit#7045]
When performing a Batch Convert OCR, the batch usually works fine but before it starts each file I get a dialogue window that says "Tesseract returned with code 1" that requires me to click OK. After two of those, the OCR conversion starts. But I have to do it before every single file in the batch, so I can't just leave a batch running and come back an hour later to a finished result.

How can I fix this?

**Comment by niksedk** [comment]
What OS are you using?

You could try to re-install (if it's on Windows - I cannot run Linux atm)

**Comment by thealexmay** [comment]
I am on Windows. Do you mean reinstall Subtitle Edit or reinstall Tesseract?

**Comment by thealexmay** [comment]
Copy, I'll give that a shot.

**Comment by thealexmay** [comment]
Well, now I'm not getting that error, but my OCR'd subtitles might as well be hieroglyphics. Screenshot:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/63341563/c2226d43-4c86-4610-95c3-e7f552c70a28)

**Comment by thealexmay** [comment]
Well, now I'm not getting that error, but my OCR'd subtitles might as well be hieroglyphics. Screenshot:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/63341563/8265f5eb-8954-475c-9287-27c8eaf22369)

**Comment by niksedk** [comment]
Did you choose Tesseract in the OCR window?

**Comment by thealexmay** [comment]
There is no option to choose Tesseract in a Batch Convert, at least not that I'm seeing. I was under the impression it has to be Tesseract for a batch OCR.

**Comment by niksedk** [comment]
Ah, you need to run OCR on a single file first.

**Comment by thealexmay** [comment]
That option is well hid. haha

I ran an OCR and installed Tesseract and made sure it was selected in batch before running a test file again and got the same result, unfortunately.

**Comment by niksedk** [comment]
Try installing both tesseract 3.0.2 and 5.x.x

**Comment by thealexmay** [comment]
I have confirmed that both of those are installed. I tried an OCR not in batch mode and it defaulted to Korean (I have English, Japanese, and Korean languages installed). I switched it to English and it worked fine in the regular interface.

But then I ran a batch again and it is the same result. Does Batch Convert default to the language of the subtitle, because I don't see anywhere to select the language? I'm wondering if it's trying to OCR the English subtitle in Korean and that's why it's coming out that way.

**Comment by niksedk** [comment]
Could you attach/email one of the source image files?

I think the batch OCR just uses the last OCR language/settings used, but I can actually depend of the input file.

The "Code 1" normally means that Tesseract is damaged or the installation of SE is damaged (often people overwrite/install the portable version in "C:\Program Files\Subtitle Edit" which messes stuff up)

**Comment by thealexmay** [comment]
Sure thing. Here's one of the sub files I'm trying to convert. Works fine in normal OCR, it's just Batch that has the issue. Had to zip it due to file format error.
[Battlestar Galactica (2003) - S02E01 - Scattered.zip](https://github.com/SubtitleEdit/subtitleedit/files/11923594/Battlestar.Galactica.2003.-.S02E01.-.Scattered.zip)

**Comment by thealexmay** [comment]
Okay, so further info, and I think this is the problem. It seems that my OCR process is defaulting to Korean no matter what. Even when I run an OCR in English, when I quit SubtitleEdit and launch it, then drag a file over to OCR, it still defaults to Korean.

**Comment by thealexmay** [comment]
I finally got it to work and I have no idea what I did. I just opened an OCR panel, switch the language to English, then opened a Batch Convert and ran it like normal and it worked as intended.

**Comment by niksedk** [comment]
Cool it's working now.
Latest beta should give the possibility to choose both OCR method and language: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip (still in the context menu - and no dictionary download yet)
