### ISSUE TITLE
WAV not found

### ISSUE THREAD

**Issue by Jslx7** [SubtitleEdit/subtitleedit#7047]
AppData\Local\Temp\cbf150-d0b8-48b8-48f3-a759-60a281dcb57e.wav   Not found.
Reinstall of app does not help.

**Comment by niksedk** [comment]
What OS are you using?
Are you using ffmpeg for audio extraction?
Are you using the installer or the portable version?
Is this a specific video file or do all video files give this error?

**Comment by Jslx7** [comment]
OK. Thank you for a quick reply. It seems, this has something to do with a specific video. Tried another one and this works as a charm.  What can be the difference? I thought .mp4 are about the same format allways.

**Comment by niksedk** [comment]
MP4 is just the container. The content can encoded with a lot of different codecs.

In SE, you can try with ffmpeg or vlc as audio extractor - if both does not work, then try converting the video file.

**Comment by Jslx7** [comment]
Ok. Thank you for the info. What I actually now did, was I converted it with Videopad editor - Now it's working fine. 
Many thanks for this SE. Great tool.
