### ISSUE TITLE
[suggestion] Video preview showing subtitles from the right column

### ISSUE THREAD

**Issue by xeophyte** [SubtitleEdit/subtitleedit#7050]
Make it so that the subtitle preview on video is showing the subtitles from the right column, not from the left; or add an option to choose which one to display on video.
When I translate subtitles, I first open original file (to left column) and then translation file (to the right). Video preview shows the left one, but I'd like to see my translation/changes on the preview, not the original subtitles.
Of course, I can switch the sides, but then there is not possible to copy many lines as text from the original file which I do for pasting to translation. Copying (and other options from the context menu) only works for the left column.

**Comment by darnn** [comment]
Settings->Shortcuts->Edit->Toggle translation and original in video/audio preview.

**Comment by darnn** [comment]
You might also be interested in:
Shortcuts->General->Switch original and translation.
Shortcuts->List view->Copy text from original to current.

**Comment by xeophyte** [comment]
Thanks, I didn't know it would be hidden like this.
Is there a possibility to assign "Copy only text from clipboard" to Ctrl+C?

**Comment by niksedk** [comment]
It's also in the Edit menu:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/20f92ae2-4647-44dc-a8a8-f7abd34996a8)


>Is there a possibility to assign "Copy only text from clipboard" to Ctrl+C?
Sorry, you will have to use another shortcut.
(the current Ctrl+C works well with Ctrl+V in SE)
