### ISSUE TITLE
Paragraph: Refact/Optimization suggestion

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#7054]
Hi @niksedk 

I'm suggesting that we replace Paragraph.Duration type from `TimeCode`  which is currently a reference type with a newly defined ValueType/TimeSpan.

Reason is that most of the time that we are calling Paragraph.Duration is to just reading value from TimeCode.TotalMilliseconds and also 
to invoke the formatting method within the TimeCode e.g: ToHHMMSSFF

Every time you call TimeCode.Duration, a new instance of TimeCode is created and returned that is if 
subtitle has 5000+ lines that is the amount object that will be created per call to the method  (see: FixLongDisplayTimes, FixOverlappingDisplayTimes, FixShortDisplayTimes) and GC will have to deal with all that clean up which can make
the app slow due to freeze that happen whenever GC runs.

Fix suggestion
Replace Paragraph.Duration's property type with a new defined type (Value Type) or TimeSpan.
If you don't want to lose the ability to call ToHHMMSSFF just like in TimeCode we can move all method signature to a
interface ITimeCode and create a new type Duration (structure) and make both Duration (struct) and TimeCode (class) inherit from that ITimeCode

FixShortDisplayTime
![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/8d17e115-0c26-443b-8bf1-22caae57104d)

21k New instance created by just running FixShortDisplayTime
![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/394f5a8a-51ea-49ba-8175-1d38ddba4bd8)

Note: For the image above 95% for TimeCode instance create is by copy constructor
if we are only duration I don't see the reason cloning the entire object (see line #72)

**Comment by niksedk** [comment]
I've added two helper methods in `Paragraph`, and `DurationTotalMilliseconds` seems to be heavily used in e.g. "Fix  common errors".

The `TimeCode` class is very light as it's just a double, but the new methods are about 4 times faster (using the old Duration.TotalMilliseconds is also really fast, but... faster is better)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/33b32a62-9a62-4723-86a6-30cd179f8221)
