### ISSUE TITLE
Add shortcut to "Set Actor" and "Set New Actor"

### ISSUE THREAD

**Issue by HadiSparrow** [SubtitleEdit/subtitleedit#7056]
Hi
could you please add these shortcuts to the list
Add shortcut to "set Actor" and "Set New Actor"
It would be super helpful 
thnx

**Comment by niksedk** [comment]
Now included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/ce43d323-fe4c-46d6-a8ac-86a81cca0ff1)
