### ISSUE TITLE
Text/word with insufficient space/box size

### ISSUE THREAD

**Issue by hugok79** [SubtitleEdit/subtitleedit#7059]
Portuguese language (pt-PT)
Some text/word with insufficient space to fit:

Under Options > Settings > Video player > **mpv** selected

![Captura de ecrã 2023-07-03 225159](https://github.com/SubtitleEdit/subtitleedit/assets/16929048/5b397438-beb9-45ec-a78d-7f996f71ae6a)

**Comment by darnn** [comment]
It's even more egregious over here, I can't see the duration at all:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/936c8e91-b019-4c68-878f-96151d744e11)
This was after I switched from a version from May 15th to one from June 16th.

**Comment by hugok79** [comment]
In Portuguese (pt-PT) looks good to me...

![Captura de ecrã 2023-07-03 231703](https://github.com/SubtitleEdit/subtitleedit/assets/16929048/2d736c1c-5903-4b71-bf06-9134c4690802)

**Comment by niksedk** [comment]
Hopefully OK now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by hugok79** [comment]
Thanks!
