### ISSUE TITLE
All models for Const-me download 1KB file

### ISSUE THREAD

**Issue by dausruddin** [SubtitleEdit/subtitleedit#7060]
I cannot download any models from the interface. It keeps downloading a 1KB file with "Invalid username or password." as the content.

<details><img src="https://github.com/SubtitleEdit/subtitleedit/assets/5763466/c419f3d6-059e-4d07-b545-f3f927f0a1d7)"></details>

After keep trying, I got this error

<details><img src=https://github.com/SubtitleEdit/subtitleedit/assets/5763466/4ec1f458-0bce-4ee4-a4a5-8cfc73535366"></details>

Seems that the link now asking for a password

<details><img src=https://github.com/SubtitleEdit/subtitleedit/assets/5763466/6f582e2e-f43d-4abe-9116-f3549d437e54"></details>

**Comment by KryptonGS** [comment]
For me I don't get any error, but I can't download either. There is a .bin-file here and it says "Invalid username or password"
Screenshot:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/93457534/75a647da-c878-4b33-93d2-3f1b8678ef5d)

**Comment by KryptonGS** [comment]
> I ended up downloading from here
> 
> https://huggingface.co/ggerganov/whisper.cpp/tree/main

I also downloaded it from there, but I can't choose it in Subtitle Edit (Ver. 3.6.13) when I move it to the models folder under:
C:\Users\User\AppData\Roaming\Subtitle Edit\Whisper\Models

**Comment by niksedk** [comment]
Thx for the info :)

The download links has been changed... SE beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
