### ISSUE TITLE
Changes not being applied in the New Burn-in Window + Suggestions 

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#7062]
I love the new Burn-in Window in Subtitle Edit 3.6.13 (Beta Version). 
Finally, we have a representation of what we see in the video. Thanks!

A few bugs in the new Burn-in Preview Window:
- The font size is not changing.
- Opaque Box is not Showing

And a few requests for improvements in the video below.
https://youtu.be/zdBDfvdNwVY
Thank you so much.

**Comment by niksedk** [comment]
thx for the video/info :)

How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip ?

**Comment by MbuguaDavid** [comment]
> thx for the video/info :)
> 
> How is latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip ?

This is much better. :) 
3 more additions I guess.

1. The Opaque Box - Is it possible to select the color we want? It defaults to black.
2. This probably means that we should also have the option to select font color if we're to change the color of the opaque box.
3. Can we have the same player preview in the Burn-in Window as for the default interface with a Maximize Player button?
![Burn-in preview window](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/6406deeb-4a78-49be-82b8-0b206f698804)

Thank you so much.

**Comment by niksedk** [comment]
thx for the input - improved version here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by MbuguaDavid** [comment]
> thx for the input - improved version here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Perfect! Thank you so much for the updates. 
Highly appreciated.

**Comment by MbuguaDavid** [comment]
Final request, can we have reset buttons for the opaque box color and font color? 
![Reset Button -](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/90c52874-6d9e-4db5-9a0e-6f8e7f80e9db)

Thanks!
