### ISSUE TITLE
"Fix Missing Space" sometimes may not detect all instances of it

### ISSUE THREAD

**Issue by squallmx** [SubtitleEdit/subtitleedit#7065]
It seems random, but sometimes FIX MISSING SPACE is not detecting some instances of it:

Examples: 

1
00:00:02,792 --> 00:00:04,750
-Oh, come on.
How are you doing that?
-Got to hit the left arrow,

2
00:00:12,500 --> 00:00:14,950
-And she would go, "No, no, no.
He wants another one.
-I never... I never

**Comment by ivandrofly** [comment]
What are you expecting? To add white-space after the hyphen (-)?

**Comment by squallmx** [comment]
> What are you expecting? To add white-space after the hyphen (-)?

Yes, in my language is the proper way for subtitles.
