### ISSUE TITLE
Show current time of playhead in the selected waveform segment

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#7069]
It would be very useful to see at what time the playhead is inside the current subtitle waveform timeline. 

This would help to time ASS effects more efficiently (currently i have to experiment with timing based on the total time of the subtitle segment).

So for example if i have a segment that is 2 seconds long, i want to see at what time inside that segment my playhead is at.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/eb2a0b0c-b45a-4606-b339-79eb988b8585)

**Comment by niksedk** [comment]
It's in the video player - lower right corner.

**Comment by rRobis** [comment]
@niksedk Hi!
Was my last comment clear enough to understand, what i mean?
 
If it's required, i could make some visual examples, of what i mean, if it's required. I would really appreciate, if this could be implemented.

**Comment by rRobis** [comment]
The calculation for relative current time inside selected segment would be:

Current playhead absolute time (from the beginning of the video) - Currently selected segment start time (in ms) = relative time inside selected segment
