### ISSUE TITLE
[Bug?] Some PGS Subtitle's Lines Aren't Being Displayed

### ISSUE THREAD

**Issue by Jack1789** [SubtitleEdit/subtitleedit#7070]
Hello, some hours ago I realized your program isn't showing up certain amount of lines, which are
being shown on two different players I'm using. It's the first time I see something like this happening, and I 
found it by chance, while testing the subtitles' timings. I bet it might be more examples, but I will leave you
just one, in case you can test it by yourself. It's around "00:09:42", and while after opening it with your program
just the "[IN FRENCH]" words can be read (with an upper-center position), while using the players, they are able to show
the missing lines at the same time. The start with: "The problem is one of criminal fraud." I leave you attached the pertinent
subtitle, in case something could be done about it.  

[Subtitle with Missing Lines (ENG).sup.zip] (https://github.com/SubtitleEdit/subtitleedit/files/11964067/Subtitle.with.Missing.Lines.ENG.sup.zip)

Remove the ".zip" part from the filename.

Thanks.

**Comment by niksedk** [comment]
Hm, both VLC and Potplay shows the same as SE for me...
(I checked a few subtitles around "[IN FRENCH]")

**Comment by Jack1789** [comment]
I just figured out what was the problem's cause, and it turned out to be about "hardcoded subtitles". One of the source's video tracks has burned-in subtitles for the "foreign parts" only, while the other hasn't, and I was wondering why after enabling the "SDH" English subtitles, I still wasn't able to see the expected text lines, i.e., those I was seeing in the hardcoded version. It seems both of the source BDs I'm dealing with (USA/UK) didn't manage to bring such subtitles correctly, since one of them simply left without translation the foreign parts, while the other, despite including subtitles for said parts, they burned them into the video.

Thanks.
