### ISSUE TITLE
plese tell me why this audio was auto cut at about 5th second??

### ISSUE THREAD

**Issue by xkungxfu** [SubtitleEdit/subtitleedit#7078]
plese tell me why this audio was auto cut at about 5th second??

THE AUDIO FILE IS ATTACHED ,PLEASE DOWNLOAD.

**THE FILE'S LENGTH IS MORE THAN 8 SECONDS. BUT AFTER IMPORTED INTO SUBTITLEEDIT, ONLY 5 SECONDS LEFT.**

[voice.zip](https://github.com/SubtitleEdit/subtitleedit/files/11990335/voice.zip)

![20230708171419](https://github.com/SubtitleEdit/subtitleedit/assets/135150023/20e4b044-8467-4a96-b1f2-c6f7ef10e19a)

**Comment by niksedk** [comment]
Works fine here with "mpv" as video player.

When using "DirectShow" SE uses the current codecs you have installed on your machine... mpv is recommended with SE.
Go to Options - Settings - Video player, to change to mpv.
