### ISSUE TITLE
EBU-STL problems with fps

### ISSUE THREAD

**Issue by glubglubs** [SubtitleEdit/subtitleedit#7085]
Hello!

Every time I make subs for a video in 23.98fps and save it in EBU-STL, my client says the subs arrive there in 24fps.
I don't know if I'm doing something wrong, or if I'm putting the wrong settings in the EBU properties panel...

I'm using the latest version of SE and I know they use MacCaption there, in case it helps clarify the issue.

Thanks!

**Comment by BattleAlchemist** [comment]
Technically speaking the EBU STL format only officially supports 25 and 30 FPS settings - the 'Disc Format Code' field in the GSI block (the header at the start of the file) can be set either to a value of 'STL25.01' or 'STL30.01' for 25 or 30 frames per second respectively. 

Using other frame rates in an STL file is therefore non-standard and you might need to check with your client exactly what they expect that value to be. 

In the "EBU STL properties" screen in Subtitle Edit, you can set the Disk Format Code from a list - you'll see it shows you 25 and 30fps, as well as some other options which it warns you are non-standard: 23.01, 24.01 and 29.01. 

My guess is that these correspond to 23.98, 24, and 29.97fps respectively, so if you select 23.01 that should theoretically give your client the (non-standard) files they're asking for, but I can't say for sure whether MacCaption supports those values, or if it supports them correctly. (I understand it is no longer sold or supported.) 

Best thing to do is to give it a try. Good luck! :)

**Comment by glubglubs** [comment]
Hi! Thanks for your reply.

I've already tried this, but they cannot open any file if I set it to 23.01.
Apparently, the problem only occurs with videos in 23.98fps. Videos in 29.97 work fine there (and I set them as 30.01).

Someone told me I should set "SMPTE timing" when working with 23.98 videos, but I just don't understand how it will resolve this issue.
