### ISSUE TITLE
3.6.13/151: Fix Common Errors doesn't seem to be fixing anything

### ISSUE THREAD

**Issue by GrampaWildWilly** [SubtitleEdit/subtitleedit#7086]
I captured the livestream of this opera a few months ago but only yesterday got the associated VTT captions.  The problem was that the captions matched an archived version of the livestream, which omits the intermissions & some other things.  So the captions were offset from the video in chunks spanning each act.  I spent a couple of hours fixing all of that with SE (thank you very much).  But there's some more I want to do.  Here's the story in pictures.

<img width="960" alt="#01" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/2b60551a-d367-498a-8d85-3a2727eaa5fd">
<img width="960" alt="#02" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/9448b78b-5edf-40a1-8e47-4ea06398cbf1">
<img width="960" alt="#03" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/272dc6db-f976-417a-9d60-0c165775d2f4">
<img width="960" alt="#04" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/8666f4df-ab99-4810-904c-b927d823e7c8">
<img width="960" alt="#04a" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/bbc608bc-cfac-4ab9-a291-95a873ec95f8">
<img width="960" alt="#05" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/fcf54679-f262-4e63-94f4-db35df9093c1">
<img width="960" alt="#06" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/e4d0c886-3c11-4f2e-8e23-d2baecdd3ed1">

If you look carefully in the upper left corner of the SE window behind the Fix Common Errors dialog, you can see that even after claiming to have fixed all those errors, the file is actually not changed.  There is no asterisk up there to warn me of unsaved changes.  In other words, the nearly 1800 fixes in truth never happened.

Just so you can try it yourself, I'm attaching the caption file.

[Don Carlo 20221129.zip](https://github.com/SubtitleEdit/subtitleedit/files/12009587/Don.Carlo.20221129.zip)

**Comment by Minherre** [comment]
You should NOT tick all Fix Common Errors, because some of them then will Restore previously ticked fixes!

**Comment by GrampaWildWilly** [comment]
Really?  Please cite a few examples.

**Comment by jmaraujouy** [comment]
Do this:

Go to **_Tools_** -> **_Merge lines with same text_**

![imagen](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/20df6836-ce9c-4878-b2a0-3a9d75094c0a)

Then set "Max. miliseconds between text" to 10 (this a good value for your case, in specific), and enable "Include incrementing lines". Click Ok.

It will fix the subtitles to this:

![imagen](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/5e947fdc-1ffa-4610-86f6-a66461ee26b9)

After that, you can check the file for common errors. Good luck!

**Comment by GrampaWildWilly** [comment]
Ah.  Brilliant!  Thanks guys.  So it's a two-step process.  Merge duplicates first, then fix common errors.  Got it.  Works like a charm.  The original 16,126 lines went down to 4.297.  Wow!  25%.  That's a lot.  Why do people create such bloated captions?  Rhetorical question.  But there were still things that fix common errors didn't fix.  They're in the log.  But I'm not too concerned about that.  Once I sit down for the THREE AND A HALF HOURS and probably more to watch this, I will see if any problems still exist in the captions & fix them as I watch.

Again, thanks so much.

**Comment by GrampaWildWilly** [comment]
Ah.  Brilliant!  Thanks guys.  So it's a two-step process.  Merge duplicates first, then fix common errors.  Got it.  Works like a charm.  The original 16,126 lines went down to 4.297.  Wow!  25%.  That's a lot.  Why do people create such bloated captions?  Rhetorical question.  But there were still things that fix common errors didn't fix.  They're in the log.  But I'm not too concerned about that.  Once I sit down for the THREE AND A HALF HOURS and probably more to watch this, I will see if any problems still exist in the captions & fix them as I watch.

Again, thanks so much.

**Comment by GrampaWildWilly** [comment]
Weird.  It's telling me I can't comment at this time, but it's posting my comment anyway.  I had to remove a duplicate.  Whatever.  Let's see if I can close this . . .

**Comment by GrampaWildWilly** [comment]
Wouldn't you know it.  I forgot to ask something.  How did you come up with 10 milliseconds?  Is that a number I could always use?  What do I look for in the captions, & how do I look for it, to come up with a number for that?

**Comment by jmaraujouy** [comment]
@GrampaWildWilly This is the time distance between the end of one subtitle and the start of the next subtitle line.

In your subtitle, "accidental" duplicate lines seem to be at a distance of 0 or 1 milliseconds apart. For example, line 1 ends at 00:05:06,220 and line 2 start at 00:05:06,220 (same time, so 0 milliseconds apart).

By keeping it a small value like 10 milliseconds, you avoid merging lines that have the same text but are not "accidental duplicates".

**Comment by GrampaWildWilly** [comment]
I think I understand part of that.  When you say "accidental" do you mean consecutive identical captions that have 0 gap between them?  Those are precisely the things I want to coalesce into a single caption with a duration equal to the sum of the original durations.  So you're saying that if they have a caption that repeats but it's more like 3 or 4 seconds later, making this number small will keep those 2 captions that might be identical but are separated in time.  That's actually something that wouldn't be too unusual in an opera.

OK.  I think I managed to explain it to myself.  But these captions were no accident.  There seems to be a fundamental lack of understanding among the folks writing these opera captions for that particular web site.  They seem to believe a caption is not allowed to be longer than 2 seconds.  This is, of course, rubbish.  But it means they didn't write those captions that way by accident.  It seems to be very much on purpose.

Another problem I've encountered has been the way captions are chunked in HLS streams.  They chop the video up into chunks for streaming.  I can understand that.  But then they chop the audio up into the same number of chunks.  And then they chop the captions up into the same number of chunks, which makes for a lot of the kind of duplication we just fixed in this VTT file.  They don't seem to get it that the number of chunks can be different between the video track, the audio track, & the captions.  It makes for rather cumbersome downloads, not to mention the massive repairs on the captions that are needed, like in this case.

**Comment by jmaraujouy** [comment]
> I think I understand part of that. When you say "accidental" do you mean consecutive identical captions that have 0 gap between them? Those are precisely the things I want to coalesce into a single caption with a duration equal to the sum of the original durations.

Yes. Perhaps it was a poor choice of words _(english is not my native language)_. I meant it to differentiate them to those subtitle lines that are intentionally repeated text.

> So you're saying that if they have a caption that repeats but it's more like 3 or 4 seconds later, making this number small will keep those 2 captions that might be identical but are separated in time. That's actually something that wouldn't be too unusual in an opera.

Exactly. That's exactly what I meant. _(Not necessarily 3 or 4 seconds later; it could be even sooner)_

Keeping a short time prevents SE to delete those kind of subtitles. An example of subtitle I see too often is something like this:

```
5
00:00:23,456 --> 00:00:24,956
Hello.

6
00:00:25,036 --> 00:00:26,536
Hello.
```

In this example, two people say "Hello" to each other. And the distance between both subtitles is 80ms.

If you set "Merge lines with same text" to something like, let's say 100ms, this two lines would get merged into a single "Hello" line, even when that word was spoken twice. _(I don't know if I'm explaining it correctly)_

Inputting a smaller value would prevent them from being merged.

**Comment by GrampaWildWilly** [comment]
Hello?
Hello?

That's hilarious.  And by the way, I did not guess English was not your first language.  You're doing great.  I understood everything you said.

The default I saw before I changed it to 10 ms was 250 ms.  That's clearly way too long.  I think I'll leave it permanently at 10 & if anything gets handled wrong, I'll just fix it myself.

You've been a great help.  Thank you so much!
