### ISSUE TITLE
Fix for capitalization after removing interjections (related to #7007)

### ISSUE THREAD

**Issue by jmaraujouy** [SubtitleEdit/subtitleedit#7089]
This issue is related to #7007 

With subtitles in Spanish language, **after removing interjections** that includes both opening and closing exclamation/question marks (¡! and ¿?), the text doesn't conserve sentence case.

For example: `¡Oh, no!` becomes `¡no!` (in _small caps_) instead of `¡No!`.
Other example: `¿Ah, sí?` becomes `¿sí?` (in _small caps_) instead of `¿Sí?`.

I hope it is an easy problem to solve.

Thanks in advance. 👍🏻

<br />
<br />

**EDIT:** I was checking some subtitles and here's another example... This one doesn't involve capitalization, but I think is related to #7007 too. Here it is:

This subtitle:
```
- ¡Wow!
- ¡Wow!
```

Gets cleaned to this:
```
- ¡
- ¡
```

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip ?

**Comment by jmaraujouy** [comment]
No, @niksedk  Unfortunately, it doesn't seem to be working.

Here are some examples _(I'll include a zip with those samples at the end of this message)_:

Characters "left behind" after cleaning:
```
1
00:01:34,963 --> 00:01:37,088
- Pero a escala, obviamente.
- ¡Guau!

2
00:29:28,713 --> 00:29:31,380
Entonces, dime qué hago.
¿Mmm? ¿Finjo que nada pasó?

3
00:35:12,671 --> 00:35:13,588
- Ah…
- Gracias.

4
00:37:27,208 --> 00:37:29,500
¿Y dónde está ese médico ahora? ¿Mmm?

5
00:41:43,755 --> 00:41:45,463
¡Oh! ¡Oh! Ay, perdóname.

6
00:41:45,487 --> 00:41:47,487
- ¡Wow!
- ¡Wow!
```

![imagen](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/221d3117-7fba-4107-a56c-9e574b74c511)

And capitalization of the first letter of the sentence:

```
1
00:02:24,588 --> 00:02:27,046
- Voy a casarme con él.
- ¡Oh, sí!

2
00:02:31,671 --> 00:02:33,546
¿Estás emocionada? ¿Sientes emoción?

3
00:11:26,171 --> 00:11:27,171
- Ah, ¿sí?
- Sí.

4
00:15:48,671 --> 00:15:51,088
"Ay, mierda. Ya se murió".

5
01:10:41,541 --> 01:10:44,125
Ay, ¿qué harías tú sin mí?

6
01:18:15,713 --> 01:18:18,630
Eh, ¿cree que su brazo era enorme? ¿Eh?

7
01:24:34,963 --> 01:24:38,296
- ¡Oh, tiene una reacción alérgica!
- ¿Tienen níquel los cubiertos?
```

![imagen](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/d419efae-d5b0-441c-9758-f99a565d575d)

Some of the interjections used in this examples are: `ah`, `ay`, `eh`, `guau`, `wow`, `oh`, `uy`, & `mmm`. Here is a zip with those two cases: [subtitles samples.zip](https://github.com/SubtitleEdit/subtitleedit/files/12061805/subtitles.samples.zip)


Thanks, Nikolaj!

PS: I don't want to be a PITA. I can always fix them manually.
