### ISSUE TITLE
SE overwrites older vtt files after opening a new one (3.6.11)

### ISSUE THREAD

**Issue by NT-cz** [SubtitleEdit/subtitleedit#7091]
After saving a finished file (vtt) and opening a new one (with a different name), the new one is sometimes automatically saved by overwriting the old one. At the same time the new file shows (and makes automatic saves) under its own name.
This happens in one of about 50 files.
IE I am done with file named 1A.vtt and save it (say at 9:00). Then I open file named 2A.vtt (say at 9:30). Suddently the file 1A.vtt shows it was created at 9:30 and is completely overwritten by 2A.vtt. Then it stays this way, while all the automatic saves are writing into 2A.vtt.

**Comment by niksedk** [comment]
I'm unable to re-create this... also, this seems very unlikely as the code only has one file name.
If you find out why this happened to you, do let me know.
