### ISSUE TITLE
text to speech functionality?

### ISSUE THREAD

**Issue by gitihobo** [SubtitleEdit/subtitleedit#7098]
Is there a way I can translate text and get text to speech audio thats in sync?

**Comment by niksedk** [comment]
Sorry, no.

**Comment by gitihobo** [comment]
Why not? It would make the software 10 times more useful, we would be able to speak to larger audiences

**Comment by gitihobo** [comment]
Is there a reason? It would help people with disabilities in other languages

**Comment by darnn** [comment]
I mean, off the top of my head, Subtitle Edit is a program for... editing subtitles. Text to speech is pretty far out of the scope of what it sets out to do.

**Comment by gitihobo** [comment]
Yeah, but subtitles are usually to help people with disabilities or translations, so if we got a native or some kind of plugin that allowed our srt files and text to speech to sync. subtitle edit would gain a lot of functionality. There is no open source way to do this yet, so if we could have offline translation and offline tts sync it would be insane

**Comment by darnn** [comment]
Yes, but as you say, there's no open source way of doing this. It is, in fact, something that companies charge a bunch of money to do even at the most basic level.
Also, consider that if we overlook everything else, you at the very least have several problems inherent in the premise: Firstly, a sentence in one language isn't necessarily the same length of time in another language. Secondly, if you have one sentence across four subtitles, for instance, you then need to put all the text of it together, perform TTS on it, and then take the resulting audio and split it into chunks of appropriate length again. None of this is trivial to do.
And just on the level of plain TTS, without getting into anything that has to do with SE: What you have out there right now is the old style of voices, the non-ML-based ones, which are free and easy to come by, but sound pretty bad. Then you have the ML-based ones, which sound much better but which can't be easily used in free software, and usually require an internet connection to use (e.g. in Edge). There are the paid-only ML ones, which sound even better, but are only accessible through paid online platforms. And then there are open-source ML-based ones, which... I mean, I guess some of them might sound okay, especially with English, but it's not like there's an easy way of working with them. There isn't just some executable and a model that you can download and easily generate audio from text on your own computer (for these open-source ML ones), which is what you'd need for what you're talking about here.

**Comment by gitihobo** [comment]
In terms of translation LLMs like llama 2 are the best alternative I can think about aside from google or deepl api, you are right that not all sentences translate correctly but with human feedback project we might get the ball rolling, when it comes to text to speech, a crude way we could go about it is programming it so both srt files are analyzed and the translation is speed up or slowed down to fit in the time of the original language.

**Comment by gitihobo** [comment]
here is a project that could be implemented https://github.com/ThioJoe/Auto-Synced-Translated-Dubs

**Comment by darnn** [comment]
As you can see on that page, you still need to pay for either Google Cloud or Azure to do this. Also, this has already been implemented, it's a whole program right over there. You could just use it, separately from SE.

**Comment by gitihobo** [comment]
But the actual tutorial has many steps, if we can stream line it with SE its a good start for implementing the feature no?
