### ISSUE TITLE
Bug: When two lines overlap completely, the first one doesn't appear

### ISSUE THREAD

**Issue by Firegloom** [SubtitleEdit/subtitleedit#7099]
I occasionally make two differently aligned lines overlap completely (to explain words, phrases and concepts when translating), but then the first line completely disappears because its duration gets set to -0,080. It happens whenever I open a file and when I burn in the subtitles, even after I've fixed it.
![bild](https://github.com/SubtitleEdit/subtitleedit/assets/139589667/d6705ccc-ea80-4046-8a9a-1c38d64a1d83)

**Comment by Firegloom** [comment]
This is how it's supposed to look:
![bild](https://github.com/SubtitleEdit/subtitleedit/assets/139589667/a4375ac6-2344-4bd7-8f35-6433d908d004)

**Comment by niksedk** [comment]
I cannot re-create this... The time codes are kept here... no duration gets set to -0,080.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/b622819f-10a3-4bb6-b69a-7282f33ff5bb)

**Comment by GrampaWildWilly** [comment]
I think this is intriguing.  What would happen if you copied the explanatory text into the same caption as the regular text.  Like this:

00:21:58.530 --> 00:21:59.480
Myra?
{\an8}{\i1}Ant in Swedish{\i0}

What happens if you don't make an entire new caption but rather just put the 2 things into the same caption?

**Comment by niksedk** [comment]
> I think this is intriguing. What would happen if you copied the explanatory text into the same caption as the regular text. Like this:
> 
> 00:21:58.530 --> 00:21:59.480 Myra? {\an8}{\i1}Ant in Swedish{\i0}
> 
> What happens if you don't make an entire new caption but rather just put the 2 things into the same caption?

Somewhat off topic... but alignment/position tags should always be at the start, and multiple alignment/position tags should not occur in one subtitle entry/cue.

**Comment by Firegloom** [comment]
> I think this is intriguing. What would happen if you copied the explanatory text into the same caption as the regular text. Like this:
> 
> 00:21:58.530 --> 00:21:59.480 Myra? {\an8}{\i1}Ant in Swedish{\i0}
> 
> What happens if you don't make an entire new caption but rather just put the 2 things into the same caption?

Creating a new line fixed the issue. Thanks!

**Comment by GrampaWildWilly** [comment]
You mean my idea actually solved the problem?  That was unexpected . . .

But Nik, you're saying it breaks the rules?  I think we know one person who wants you to never close this loophole.

**Comment by Firegloom** [comment]
Nevermind, the problem is still there. It just seems to have kicked it back.
