### ISSUE TITLE
I need a reply for this from Nikolaj. If it can be done, OK, if not, why not? 

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7111]
I see SE as a complete program, I can't see any flaw in it. Maybe somebody has some remarks or requests, but I have the only one. I haven't gotten the reply to my issue, I want to get it now. Can it be done? If not, why not? 

I already suggested that in Syncronizations/Adjust all times, that is, in dialogue ALL LINES we get two buttons more. They will move the subtitle line left/right in the waveform AS LONG AS WE keep pressing the button >> or << in this dialogue (the new buttons). It is very helpful when you need to go to some line (in wave representation below) and you want to go back to the earlier time (or to the left). It is tedious to click 20 times if the line is very distant. It is easier to keep the button pressed and the line goes right or left in waveform very fast and easily. 

If somebody says that we already have the button SET START AND OFFSET THE REST, it is true, but we would have much more freedom in work if we had the two additional buttons. And that SET START option moves all lines, not the ones we pick, we have much more freedom in the dialogue Adjust all times/All. 

![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/f26522d2-146a-4b6e-817d-50a44d1ee3b3)

**Comment by Cyberyoda1411** [comment]
Nikolaj, if something is not clear, just tell me. I really can't find anything more you can make better, than this. I'd like to know if this can be implemented.

**Comment by niksedk** [comment]
I'm not sure what you want to do...
You would like to move to other subtitles in main list-view/waveform for what? check sync? I could make alt+arrow up/down work here, would that help?

What should those two buttons do? Go to prev/next subtitle line?

**Comment by Cyberyoda1411** [comment]
Can I make you a youtube video? Last time with Reply we solve this problem this way.

**Comment by Cyberyoda1411** [comment]
Here is my youtube video for you: https://youtu.be/DKyNXgh4TR4. Sorry, my speaking English is rusty, I didn't speak it for long than 10 years. My written English is much better. 

Thank you for replying to me. If anything is not clear, tell me, I will make it clear. I think this feature would be nice to be implemented in SE. To have the line shifting with one click and this shift to last until we lift our finger from the mouse button. Not onClick event in programming, but onMouseDown, if I am right.

**Comment by niksedk** [comment]
Hm, it not working well: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
Too slow... perhaps "3 secs" + "5 secs" buttons?

**Comment by Cyberyoda1411** [comment]
If you refer that we could put some shift in H:m:s in this dialogue, the only acceptable shift is 0.100 seconds. Only this shift makes the work precise enough. So, any 3 or 5 seconds shift is too much.

**Comment by Masina86** [comment]
Hello, u know that u can drag the text in the waveform, right? That will give u precise placement of the text.

**Comment by Cyberyoda1411** [comment]
Yes, you can drag the text, but ONLY THAT LINE. When you use the option with 'all subsequent lines', you move ALL the lines after this line. And you want exactly that. Not to move only one line. But, it is better to do it with one click, instead of 30.

**Comment by Cyberyoda1411** [comment]
Masina, where are you from? Only Slavs use that word, MASINA.

**Comment by Masina86** [comment]
I am from MK. I dont know, if someone can do it than it is Nikolaj,

**Comment by Cyberyoda1411** [comment]
I am from Serbia.

**Comment by JDTR75** [comment]
Hey @Cyberyoda1411. If I understood you correctly, what you're asking can be done already.

- On the list view, click on the first subtitle you'd like to offset - from your video, subtitle 69.
- Then use Ctrl+Shift+Left-Click on the waveform view. You should left-click on the desired position you want to move the subtitles - from your video, it's around 05:02.

**Comment by Cyberyoda1411** [comment]
I can do it even faster with the F9 key, that is, with SET START AND OFFSET THE REST. Just click where I want the lines to be moved and F9 will move everything at that position. 

What I want is to have more control over the whole process of moving the lines more or less close to the position I need, and this is a bit later than the desired position, or I'll have a lot of lines without almost any pause between them.

**Comment by JDTR75** [comment]
Yes, you can but only if you're on the Adjust tab. Instead, you can ALWAYS use the mouse/keys in the waveform. Ultimately, what you're doing with this is just adding or subtracting time to both the in and out cues. Maybe you should check out the Visual Sync and Point Sync features - I'm guessing they'll help you a lot with what you're trying to do.

**Comment by Cyberyoda1411** [comment]
Nokolaj, tell me what is on your mind. What problems do you see from the technical point of view? 

If you ask me, even if it stays this way, it wouldn't be bad. I'd like to have this feature, even if it is just as it is, I mean the beta you sent to me. 
If you have problems with H : m: s part of the dialogue, just make two additional buttons for the fast move (this behavior from beta) and keep the rest as it was. 

Tell me what is on your mind, the best way to solve this is while it is still fresh in your head.

**Comment by niksedk** [comment]
It's not working too well... slow and jerky.... "3 secs" and a "5 secs" buttons might work better.
I could probably be made somewhat faster, but that is not super easy.

Note that you can press "Enter" on a button - will repeat.

**Comment by GrampaWildWilly** [comment]
> ** Reply to message from Nikolaj Olsson ***@***.***> on Fri, 21 Jul 2023 00:11:11 -0700

> Note that you can press "Enter" on a button - will repeat.

Also Spacebar.

WW
GO HABS GO!

**Comment by Cyberyoda1411** [comment]
Nikolaj, what settings do you use? Is it some 'system Windows' thing, or this behavior (jerky and slow) depends on the initial value of 0.100 seconds or some other value? Does its value make any difference? 
I am still wondering why you say 'slow', because on my computer, it is pretty fast, too fast. And it is jerky, that is true.

**Comment by niksedk** [comment]
Sorry, it will not work well... but you can use space or enter on the button.
I can add a e.g. 3 + 5 seconds buttons if that would help.

**Comment by Cyberyoda1411** [comment]
No, 3 seconds is too much. Or 5. I just wanted to avoid (while I work with a 0.100 shift) clicking endlessly when the title is shifted too much to the right, so I need to shift it to the left (waveform representation of the subtitles). 

Believe it or not, I still use the beta version you gave me, and when I am precise with the mouse, it is not bad. When I click once, it is a 0.100 shift. When I keep the mouse button down, it shifts pretty well, but I have to use my finger with a bit more feeling. 
My question was if you used 0.100 shift, or you used the system Windows settings. If it is the system, you can do one of two things: to implement this shift with all jerking or to forget the whole thing. As I said, it was pretty good for me. We just need to be more precise with the mouse, not just push the button of the mouse and keep the shifting going.

**Comment by Cyberyoda1411** [comment]
Nikolaj, I think I have the solution to this problem. I can see that you won't include this jumping OnMouseDown thing, because it is too clumsy and jumpy,  so I suggest you include SHORTCUTS for +0.5 seconds and -0.5 seconds in the waveform (to move one or more lines in desired direction a bit faster), or make **two buttons** in Synchronizatons/ Adjust all times dialogue. I think that step 0.5 seconds is very good to work in the waveform. I know it can be adjusted in the dialogue, but I work with 0.1 steps, and it would be tedious to click on arrows to raise it to 0.5, that is 5 clicks all the time. 

I showed you why I need that skipping option in my youtube video, When I must go back with some title, to shift it to the left. 
There is one more situation when it is a very desirable option. When you start editing, and the timing is not good, and all lines are so close to each other in the waveform, it is great to push everything at least 0.5 seconds to the right and make some space for the work. It is not too much, it is not too small shift. It is just fine.

If you have problems to understand me, just say, I'll make a youtube video for you.
