### ISSUE TITLE
Add "Reaction time" to settings

### ISSUE THREAD

**Issue by rebawest** [SubtitleEdit/subtitleedit#712]
When timing using shortcuts, such as "Insert new subtitle at video pos" or "Set end time", I notice there is a hidden setting called **SetStartEndHumanDelay = 100;**

Could yo please add it to the settings window. Something like this:
![image](https://cloud.githubusercontent.com/assets/6587015/7220932/99286d76-e6b0-11e4-9d86-350fd72e0a39.png)

Also, I tried changing the value at **SRC/LOGIC/SETINGS.CS:573** but nothing happened. I set SetStartEndHumanDelay to 500 and I still get 100 ms. 

I'm trying to change some things at InsertNewSubtitleAtVideoPosition, such as using the "Min. gap between subtitles" when timing on the fly (during video playback). I'll see how it goes.

Thanks. Regards...

**Comment by xylographe** [comment]
Why change the source code, instead of the actually used value in
`"${env:APPDATA}\Subtitle Edit\Settings.xml"` ?

**Comment by rebawest** [comment]
Because I'm a programmer and I'm trying to make some changes to InsertNewSubtitleAtVideoPosition and to other functions, hopefully to improve them.
Also, when I pressed F12, Visual Studio took me to settings.cs.

My request is still valid: to add the "Reaction time" to the settings window so that it doesn't remain a hidden parameter.

**Comment by rebawest** [comment]
Closed.
