### ISSUE TITLE
How to generate background box for multiple lines (ass)?

### ISSUE THREAD

**Issue by xeophyte** [SubtitleEdit/subtitleedit#7121]
I've got .ass subtitle file and don't know how to generate custom background box for multiple lines using ASSA tools.
When I use ASSA tools/Generate background box on the lines, under every line some script code is being created, like
`Dialogue: -11893,0:01:03.96,0:01:06.88,SE-box-bg,,0,0,0,,{\p1}m 595 766 b 580 766 580 766 580 781 l 580 795 b 580 810 580 810  595 810 l 1328 810 b 1343 810 1343 810 1343 795 l 1343 795 1343 781 b 1343 766 1343 766 1328 766 l  595 766{\p0}`
A lot of additional code...
Every use of ASSA tools/Generate background box on on every line creates another style, also lot of code...
Adding custom background using style created by ASSA tools/Generate background box is not working.
Is using ASSA Tools the only way to add custom background to multiple lines?

**Comment by xeophyte** [comment]
Btw, I think I found a bug through which it is not possible to add a background to multiple lines with ASSA tools/Generate background box - when more than one line is selected, not in sequence, only some of them, the added code jumps to the next lines and does not stay on the ones that I wanted to change :/

**Comment by LeonCheung** [comment]
It‘s highly recommended that we add background boxes as the final step of your captioning work because, as you see, lots of codes will be generated which seems to be messed up a bit.

If you just want to simply add the bg box quite similar to the YouTube CC style, you can simply use the ASSA style:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/2b34c9d3-56a3-4b51-8b01-0aadcd60de31)

**Comment by xeophyte** [comment]
I don't want the simple bg box because I want to set its margins and rounding.
I know I should add background boxes as the final step, but it's hard to select tens of correct lines at one go and use ASSA tools/Generate background box only once - to have only one style created (to minimize the amount of code).

**Comment by LeonCheung** [comment]
Hmm, so your question now is actually how to select multiple lines effectively? In that case, there is a multiple selection tool in the menu. Then you can select by Style, for example.

**Comment by xeophyte** [comment]
That's not what I meant, if it's how to mark many lines of a given number, but I don't think you can. So, I wrote down the appropriate line numbers in a notepad and from it I selected the lines.
But most of all, I wanted to not automatically create unnecessary styles when creating backgrounds from subsequent uses of the generator. I've come to the conclusion that it can be done by creating normally subsequent backgrounds and then changing the style of their line of code to the first style created by generator. After that, all styles except the first one can be removed in the styles' menu.
Anyway, thanks for the tip.

**Comment by niksedk** [comment]
Each style has a box size and location for the text in pixels... I don't think this will overlap very often.
