### ISSUE TITLE
"Open video from URL" not working

### ISSUE THREAD

**Issue by Kapowpenguin1** [SubtitleEdit/subtitleedit#7125]
i'm trying to open a youtube video, but regardless of whether i use the "www.youtube,com" version or the "youtu.be" version, the video doesn't seem to load. the link shows up below the video player, but otherwise, there's no indication that anything happened

**Comment by niksedk** [comment]
Are you using mpv + with yt-dlp?

**Comment by Kapowpenguin1** [comment]
i see "mpv" in video player but idk how to check about yt-dlp. ik yt-dlp is linux tho, and i'm running subtitle edit on windows, if that matters

**Comment by niksedk** [comment]
If you're using mpv as video player in SE, then SE should prompt for downloading yt-dlp if you don't have it.
(only on Windows)

**Comment by Kapowpenguin1** [comment]
i ended up just reinstalling the editor and that got "Open video from url" to work properly. on a different note, might be nice to have some sort of progress bar for yt-dlp?
