### ISSUE TITLE
Request: Add line selection in the Batch Converter's Offset time codes option

### ISSUE THREAD

**Issue by gandbg** [SubtitleEdit/subtitleedit#7127]
I'm batch converting some funky subtitles and i need to apply the `Offset time codes` option only on specific lines but there's no option like that.

Maybe a text input field can be added in the settings of the option can be added to select what lines to affect. The syntax could look something like this:
+ `,`: Separate a rule from the other
+ Y: Include line Y
+ !Y: Exclude line Y
+ X-Y Include lines X thought Y (inclusive)
+ !X-Y: Exclude lines X thought Y (inclusive)
+ `S`: First line (S stands for **S**tart)
+ `E`: Last line (E stands for **E**nd)

Compared to a more basic, two-input-fields system (one *Skip first X lines* and the other *Skip last X lines*), this rule-based system requires a slight learning curve, but is much more powerful

**Comment by niksedk** [comment]
Sorry,  I think this is too complex
