### ISSUE TITLE
Go to next line without video position

### ISSUE THREAD

**Issue by richja** [SubtitleEdit/subtitleedit#713]
Hi,
is there a way to not changing video position when I go to next/previous line using shortcut?
Setting for double-clicking line in main list view doesn't apply for that.

**Comment by LeonCheung** [comment]
Video position will only sync in Translate mode, you can try doing so in other two modes.

**Comment by richja** [comment]
Thank you for response, but sadly it doesn't work for me in neither. Same behaviour.

**Comment by LeonCheung** [comment]
Hmm, it works for me. :-\     What shortcut exactly are you using? (I suggest you upload a short example video to expose the problem)  :)

**Comment by richja** [comment]
I use alt+up and alt+down (I have also  defined my own in settings "go to next/previous line" with same result). Good idea with video, will add it later. (If you know Subtitle Workshop, this app has exact behaviour I would like to achieve.)
