### ISSUE TITLE
Can't generate waveform when importing video from URL

### ISSUE THREAD

**Issue by Gromko1111** [SubtitleEdit/subtitleedit#7140]
Hey, I've tried to load up a YT video from an URL. It's working, I can watch the video, but then I click on the waveform box to generate it, this error shows up: 
![obraz](https://github.com/SubtitleEdit/subtitleedit/assets/13754995/d77eead5-502a-43ad-a110-d6aff18b98e9)

Edit: "nie można odnaleźć ścieżki" means "couldn't find the path"

Is there any way to fix this?

Thanks in advance!
Gromko

**Comment by niksedk** [comment]
thx for the info :)
Could you try latest beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip ?

**Comment by Gromko1111** [comment]
Hi, I've tried it and I'm getting, I think, the same error:
![obraz](https://github.com/SubtitleEdit/subtitleedit/assets/13754995/9d8d1ddc-cd84-4282-b6a8-d5a98a67dad7)

**Comment by niksedk** [comment]
Thx for the hints... the cash should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

The waveform for online video will always just be a line - extracting audio waveform requires local video.
