### ISSUE TITLE
Crash with some .vtt files, minimal example attached

### ISSUE THREAD

**Issue by ms2048** [SubtitleEdit/subtitleedit#7148]
Subtitle Edit 3.6.13, Windows 7 Pro x64.

Trying to open the attached .vtt file and then immediately changing the type to .srt or trying to save as .srt results in a crash, recoverable after selecting 'Ignore'.

The file is a minimal example but for many bigger .vtt files the same error gets thrown.
[x.vtt.txt](https://github.com/SubtitleEdit/subtitleedit/files/12139167/x.vtt.txt)
(had to rename as .txt because of github limitations)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/25595047/623913da-6e9f-4bb7-ae95-7c040c1bda45)

Also trying to batch convert such a file results in an error.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/25595047/b0eff331-96e3-4896-ad35-f175e41aebae)

**Comment by ms2048** [comment]
... also tried with a newest beta (3.6.13 NEXT, beta 347), same result.

**Comment by niksedk** [comment]
Thx :)

Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by ms2048** [comment]
That was fast, thanks!

Looking good so far.
