### ISSUE TITLE
Error message, it pops out without any visible reason

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7151]
This is the error message, it pops out, I can't say why, every 10 minutes. I use the beta version 349, the latest, and this was present in the version before this one, too. 

Here is the screenshot. 

![Greska verzija 349](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/3e14621f-fccf-4049-916b-0f92684728fa)

**Comment by GrampaWildWilly** [comment]
Every 10 minutes makes me think something that runs on a schedule is triggering this. 
Maybe it's the auto-backup feature.  The interval for that is on the first page of the SE
settings dialog.  What do you have that set at?  Maybe that's a clue, maybe not.  I'm
just guessing here.

**Comment by Cyberyoda1411** [comment]
It is not strictly 10 minutes, it is just my estimation. It can be half an hour, then 15 minutes, I didn't measure that. And I didn't check the option autosave. The error talks about some threads and windows that don't work correctly. They are called 'form'.

**Comment by Flitskikker** [comment]
I think #7152 should fix this

**Comment by Cyberyoda1411** [comment]
Additional info for Nikolaj, if it is necessary. The error shows when I edit subtitles, I don't do anything unusual, I just edit the titles and move subtitles to change the timeline, standard editing tasks.

**Comment by niksedk** [comment]
Hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
