### ISSUE TITLE
Error message when trying to close the Find window when the “Import/OCR Blu-ray” window is open

### ISSUE THREAD

**Issue by przemo20** [SubtitleEdit/subtitleedit#7155]
Example steps to reproduce:
1. Download this zipped [test sup file](https://github.com/SubtitleEdit/subtitleedit/files/12152563/test.sup.file.zip), and extract it.
2. Drag and drop it onto the program window – “Import/OCR Blu-ray (.sup) subtitle - test.sup” window should open.
3. Press Ctrl + F – the Find window will show up.
4. Try to close the Find window, by clicking the X in the top right corner – the following error will show up:
```
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 3.6.13.362 - 64-bit  - Microsoft Windows NT 10.0.19045.0. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.FindDialogClose()

   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)

   at System.Windows.Forms.Form.WmClose(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Abort   Retry   Ignore   
---------------------------
```

Screenshot:
![obraz](https://github.com/SubtitleEdit/subtitleedit/assets/22180480/69fbb5f0-1f61-4672-a061-70f5ead32d37)

Other information:
I tested this on the latest stable version and the latest beta.
You can also reproduce this by taking different steps, like for example opening a MKV video with muxed PGS subtitles, selecting that subtitle from the “Choose subtitle from Matroska file” window, clicking OK and doing the steps 3 to 4 from the list above.

**Comment by niksedk** [comment]
Thx :)
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
