### ISSUE TITLE
can't download audio to text whisper

### ISSUE THREAD

**Issue by hoangtrismpk** [SubtitleEdit/subtitleedit#7156]
I can't download the audio to text whisper model, it just shows a waiting dialog and then turns off by itself and there is no error message at all, what should I do?

**Comment by niksedk** [comment]
Could you try latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by HeveraletLaidCenx** [comment]
Hi, I came across the same problem I think, which the last release can not download the whisper models properly, when you click model to download, the download progress rapidly flashed off and I check the model folder then, the model is very small size of some bytes. 

I changed to the Beta then, I think the download problem is fixed, the model can be download now with a correct size, but I found the result of it is strange, all the result are the same piece of words (as image showed below), I using Chinese now, and I will try English to see if it works.

![2023-07-25_184058](https://github.com/SubtitleEdit/subtitleedit/assets/34192286/45e16942-2d64-46ec-b0eb-be6e10d9447c)

**Comment by hoangtrismpk** [comment]
> Could you try latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Yes, I used  latest beta

**Comment by niksedk** [comment]
> > Could you try latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
> 
> Yes, I used latest beta

Please add what steps you use with screenshots :)

**Comment by hoangtrismpk** [comment]
> > > Could you try latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
> > 
> > 
> > Yes, I used latest beta
> 
> Please add what steps you use with screenshots :)

hmmm. After changing to using the Portable version instead of the Setup version, it worked. Thanks
