### ISSUE TITLE
Download Wisper Model not working

### ISSUE THREAD

**Issue by ChristianErdtmann** [SubtitleEdit/subtitleedit#7158]
Hey i try to download a Model for Wisper Audio to Text.

But if i hit the download button just some text appers for a secound in the windows and there is no download running. Doesnt matter wich model i choose (large or smal)....
If i choose large it creates a tiny.en.bin in the models folder with size of 1kb.

Already downloaded to software here from git and reinstalled everything but same result.
(I use Windows 11)

What can i do is there wa way to manual download models and add them to the folder?

**Comment by ChristianErdtmann** [comment]
That is working thank you.

**Comment by meiersa78** [comment]
> You could try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip (It's a portable version, unpack to something like C:\Tools\SE)
> 
> The download links were changed...

Perfect, thank you! This portable version works. I had the same issue with the Windows installer version 3.6.13 and no models could be downloaded.

**Comment by moigres051** [comment]
> You could try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip (It's a portable version, unpack to something like C:\Tools\SE)
> 
> The download links were changed...

sorry i do not understand, what exactly do i have to do, to correct this issue about not being able to select the model to use audio to text whisper function, can you please explain it more

**Comment by niksedk** [comment]
> > You could try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip (It's a portable version, unpack to something like C:\Tools\SE)
> > The download links were changed...
> 
> sorry i do not understand, what exactly do i have to do, to correct this issue about not being able to select the model to use audio to text whisper function, can you please explain it more

Wait about a week for SE 4.0 - here model download should work again.
If you want to to work right now, you will have to use the beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by moigres051** [comment]
Thanks a lot for your help. I will do both Thanks again ☺️

**Comment by moigres051** [comment]
i download this version
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
but now i am experimenting this problem

[image: image.png]
how can i solve it
