### ISSUE TITLE
hotkey request

### ISSUE THREAD

**Issue by aoifeaoibhee** [SubtitleEdit/subtitleedit#7159]
If there's a way to do these things that already exists, I haven't been able to find them in the settings. I would love hotkeys for the following:

1. "insert new subtitle at video pos," and "insert new subtitle at video pos (no text box focus)" hotkeys that take into account the set min. gap between subtitles, as in **"insert new subtitle after min. gap" for each of these settings**.

2. A hotkey to **deselect/exit out of the text box**.

Also, and I'm sure this is a big ask, but if there's a way to incorporate foot pedal keys as hotkeys (like VEC Infinity) it would be hugely helpful to people from transcription backgrounds.

You can map foot pedals to keys with Pedable as well, but I haven't been able to figure out a key that works well, as mapping it to anything makes it interact with other hotkeys as I start typing. Typically, the foot pedal would **toggle play/pause upon tap/release**, like you'd press and hold it while the video is playing, then release it to pause.  It's a timesaver, versus having to tap/release to play, then tap/release to pause.

Thank you for all your hard work!! ♥

**Comment by niksedk** [comment]
You can fix min gaps later... or use insert after.

For focus you can use some of these (or I could make a "Focus <something>" shortcut...):
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/da773c96-7f6c-4123-a18e-0061d11c15b3)

I do not know anything about foot pedals... can't they hook into shortcuts?
