### ISSUE TITLE
The word "do-gooder" in a subtitle file triggers quotation markings around this word during "fix common OCR errors" scan

### ISSUE THREAD

**Issue by Firestorm2359** [SubtitleEdit/subtitleedit#7160]
If the word "do-gooder" exists in the subtitle file, the "fix common OCR errors" function/scan will add quotation marks around the word. If the quotation marks are not removed and "fix common OCR errors" is run again, another set of quotation marks will be added ad infinitum eg., """""do-gooder"""""

**Comment by Firestorm2359** [comment]
Take a look at these files and let me know what might be happening.

Note it happens with every file that has the word "do-gooder" in it (singular) but not "do-gooders" (i.e., plural will not trigger it).

Also note that it's the "fix common OCR errors (using OCR replace list)" checkmark _within_ the "fix common errors" function that does it.

[Do-Gooder.zip](https://github.com/SubtitleEdit/subtitleedit/files/12180459/Do-Gooder.zip)

**Comment by niksedk** [comment]
I've added "do-gooder" + "do-gooders" to the English words list, so spell check will be happy.

I cannot re-create this, so I would guess that you dictionaries are messed up... sorry.
Uninstall SE, remove all in "%appdata%\Subtitle Edit", and then re-install SE.

**Comment by Firestorm2359** [comment]
Thank you for getting back to me. Can you tell me which specific dictionary file may have been corrupted? Is it the "en_US_se.xml"?
