### ISSUE TITLE
Audio to text only works on the first audio track.

### ISSUE THREAD

**Issue by aristocrato** [SubtitleEdit/subtitleedit#7164]
Great job adding the audio to text feature. That saves me a ton of time. But is there any way to choose which audio track to use this feature when dealing with videos with multiple audio tracks? It's always applied to the first audio track by default, even if I have switched to other audio tracks before (by clicking Video->Choose audio track). I also tried to generate corresponding waveforms before using audio to text, but it doesn't work either.

**Comment by niksedk** [comment]
Using Whisper?
A screenshot would help... also check https://www.nikse.dk/subtitleedit/help#good-github-issue

Whisper in SE should work on the selected audio track...
