### ISSUE TITLE
Blu-ray SUP image is too wide/cropped

### ISSUE THREAD

**Issue by ScribbleGhost** [SubtitleEdit/subtitleedit#7167]
Here is an example:

![2023-07-27T07-58-25](https://github.com/SubtitleEdit/subtitleedit/assets/49068170/0f46861d-76b5-4982-aa79-09a9faa1c271)

Now I am not sure if this is just how the image is, or if SubtitleEdit has cropped it.

Any advice?

**Comment by eddilara** [comment]
why don't you just split it into 2 lines?

**Comment by ScribbleGhost** [comment]
The problem is I can't see the whole line, so how am I supposed to split something which I cannot see?

**Comment by niksedk** [comment]
You can see the whole line...

**Comment by ScribbleGhost** [comment]
In that case, can you tell me what comes after the word "henious"?

**Comment by niksedk** [comment]
> In that case, can you tell me what comes after the word "henious"?

`CI` ?

**Comment by ScribbleGhost** [comment]
Exactly, "CI" is not really a word, is it? It's supposed to say "crimes". Hence my point about the image being cropped.

**Comment by niksedk** [comment]
Could you attach the subtitle file (Github accepts zip files)
Or email it...

**Comment by ScribbleGhost** [comment]
Sure. Here it is: [22128823.zip](https://github.com/SubtitleEdit/subtitleedit/files/12266839/22128823.zip)

**Comment by eddilara** [comment]
just took a look at that sub file
if thats a original sub from the company...its WAYYYY outta spec
a bd sub file should never be that long
its not allowed in retail sub file specifications
