### ISSUE TITLE
Subtitle Edit ver. 3.6.13 - video and list are not "moving" together

### ISSUE THREAD

**Issue by GardfieldMe** [SubtitleEdit/subtitleedit#7180]
Hi,

I'm using `Subtitle Edit ver. 3.6.13` (installed in Windows 10)
It happens that when the video is playing, the corresponding subtitle in the list doesn't "follow" accordingly.
I've tried selecting different players in the `Settings -> Video player`. Same behavior.

I also have the `portable version 3.6.7`, and works fine.

Am I missing something? Has any settings parameter changed with this new version?
I'd appreciate some help.

Thanks,
G.

**Comment by niksedk** [comment]
You might be looking for the "waveform center" state button?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/2ef2b1e9-45b3-4c89-b72e-72d020dcd6e6)

**Comment by GardfieldMe** [comment]
Oh yes!
I don't know how I missed it. It works now, thank you! 

Anyway, it's just me or it's located like something related to the _waveform_?

Thanks,
G.

**Comment by niksedk** [comment]
He, it might not be the best place, but it also works in the waveform... where would it be easier and more logic to place?

**Comment by GardfieldMe** [comment]
My two cents...
First option would be the "Video" menu. And the second, in "Settings >
Video player" 🤔

Cheers and thanks for this great program.
G.

**Comment by Abernecio** [comment]
Is it possible for the opposite to happen?
What I mean is by doing ALT+Up or ALT+Down to go to the previous/next subtitle, the video also jumps to that subtitle.
Right now, I have to double-click every line so that the video jumps.

Cheers!
