### ISSUE TITLE
Detect color when doing OCR under Linux

### ISSUE THREAD

**Issue by skittlesvampir** [SubtitleEdit/subtitleedit#7187]
I have a DVBSUB subtitle that I'd like to OCR with SubtitleEdit. The subtitle has different colors that I'd like to keep. I read that it used to be possible with Tesseract 3 but that isn't available in Linux anymore. Is it not possible anymore?

Thank you all in advance.

**Comment by niksedk** [comment]
I think you need to check the "Use color" check box (should work with all OCR methods):

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/bc849082-ba12-4de9-8128-d9ee1d1974aa)

**Comment by skittlesvampir** [comment]
I can confirm, that when I convert my video to MPEG-TS, that I do get this option you were showing and it seems to work. The reason that I didn't see this option was because I was using a matroska container.
Is this maybe a bug? Anyway, converting to .ts works just fine to me so I see no problem.

**Comment by skittlesvampir** [comment]
If you think this is fine, feel free to close this issue.

**Comment by skittlesvampir** [comment]
Is there a way to reduce the line splitting that SubtitleEdit was warning be about?
