### ISSUE TITLE
Speech-to-text module, the engine CTranslate reports an error when the selected language is not English.

### ISSUE THREAD

**Issue by YingziWo** [SubtitleEdit/subtitleedit#7188]
语音转文字模块，引擎CTranslate在选择语言为非英语时报错。
在加载视频后，使用音频转文字模块时，用引擎CTranslate在选择语言为非英语时报错，错误显示为“NO text found！”，而在选择语言是英语时，引擎工作正常。只要一选非英语语种，引擎就会报错。
但是，同一CTranslate（既 Whisper-faster）在命令行模式下，无论语言选择的是英语，还是非英语，CTranslate（既 Whisper-faster）的工作都是能够正常运行，识别出所选语言。

Speech-to-text module, the engine CTranslate reports an error when the selected language is not English.
After loading the video, when using the audio-to-text module, the engine CTranslate reports an error when the selected language is not English, and the error is displayed as "NO text found!", but when the selected language is English, the engine works normally. As long as a non-English language is selected, the engine will report an error.
However, the same CTranslate (Whisper-faster) works in the command line mode, regardless of whether the language is English or non-English, CTranslate (Whisper-faster) can work normally and recognize the selected language.

![subtitle_err-1捕获](https://github.com/SubtitleEdit/subtitleedit/assets/104121906/3be6e84f-88c3-4185-b046-ac7e2139e45e)
![subtitle_err-2捕获](https://github.com/SubtitleEdit/subtitleedit/assets/104121906/8672a2c8-9d1d-4bd7-aaa3-320d888c49df)

**Comment by niksedk** [comment]
Did you check the `error_log.txt` file?
It's located in the SE data folder - press Ctrl+Shift+Alt+D in the SE main window.

**Comment by YingziWo** [comment]
> Did you check the `error_log.txt` file? It's located in the SE data folder - press Ctrl+Shift+Alt+D in the SE main window.

按照提示，在Subtitle为当前活动窗口的时候，按下Ctrl+Shift+Alt+D，进入到 “..\Users\Administrator\AppData\Roaming\Subtitle Edit”文件夹，打开该文件夹下的error_log.txt，发现下面这段文字：
“SE: 3.6.13.0 - Microsoft Windows NT 10.0.17763.0 - 64-bit
Message: Calling whisper (CTranslate2) with : ..\Program Files\Subtitle Edit\Whisper-Faster\whisper-ctranslate2.exe --language ja --model "medium"  "C:\Users\Administrator\AppData\Local\Temp\8140241d-4a94-481f-b179-37aaf1b2008c.wav"
Model not found at: ..\Program Files\Subtitle Edit\Whisper-Faster\_models\faster-whisper-medium”

其意思是说缺少模型文件，但实际情况是在“..\Program Files\Subtitle Edit\Whisper-Faster\_models\faster-whisper-medium”文件夹下已经由Subtitles自身下载的faster-whisper-medium和faster-whisper-medium.en两个模型文件，然而在whisper-ctranslate2.exe调用这个由Subtitles自身下载模型文件时，估计是它校验了下载的模型文件完整性有问题，所以报了没发现模型文件的错误。

       而前面提出问题中，有提到的命令行下各种语言下都正常，这个命令行下的环境模型下载，因为根本无法由Whisper-faster.exe自身（在我所处的网络环境下）进行自动下载，所以这个命令行环境的模型全部是通过手动在：https://huggingface.co/guillaumekln 下载，而非自动下载。下载网页中模型有轻量化的和大、中型的，该页面下列有10个模型链接，点进链接后，再点“File and versions”（文件和版本）标签页，这页列有模型的版本和可下载文件列表，通常只需下载“config.json;  model.bin; tokenizer.json; vocabulary.txt"四个文件组成一个模型，模型文件放在与whisper-faster.exe同目录的”_models“文件夹下，下载的四个文件根据文件版本号命名来设置模型文件夹命，如中型模型有两个文件夹：”faster-whisper-medium“和”faster-whisper-medium.en“，下载的8个中型文件根据版本不同放在相互对应的文件夹中。下载文件工具最好用有断点续传和校验功能的下载工具下载，比如开源的Motrix，因为网页下载会莫名其妙地断了或报错误，而造成下载模型文件的不全而不能使用。
     通过比较命令行的运行环境和Subtitles下的运行环境，根据error_log.txt报错的提示，怀疑是模型文件下载的不够完整引起的本问题，因此，把运行正常的命令行环境下的模型文件夹拷贝到Subtitles环境下的” ..\Program Files\Subtitle Edit\Whisper-Faster\_models\”下覆盖原来的文件夹和文件后，再运行引擎CTranslate的各语种语音转文字时，工作都正常运行，问题得到解决。


According to the prompt, when Subtitle is the current active window, press Ctrl+Shift+Alt+D to enter the "..\Users\Administrator\AppData\Roaming\Subtitle Edit" folder, and open the error_log under this folder. txt, found the following text:
"SE: 3.6.13.0 - Microsoft Windows NT 10.0.17763.0 - 64-bit
Message: Calling whisper (CTranslate2) with : ..\Program Files\Subtitle Edit\Whisper-Faster\whisper-ctranslate2.exe --language ja --model "medium" "C:\Users\Administrator\AppData\Local\Temp \8140241d-4a94-481f-b179-37aaf1b2008c.wav"
Model not found at: ..\Program Files\Subtitle Edit\Whisper-Faster\_models\faster-whisper-medium”

It means that the model file is missing, but the actual situation is that the faster-whisper-medium and There are two model files of faster-whisper-medium.en. However, when whisper-ctranslate2.exe calls the model file downloaded by Subtitles itself, it is estimated that it has verified the integrity of the downloaded model file, so the report did not find the model file error.

        In the previous question, the command line mentioned is normal in all languages. The environment model download under this command line cannot be performed by Whisper-faster.exe itself (in my network environment). Automatic download, so the models of this command line environment are all downloaded manually at: https://huggingface.co/guillaumekln, not automatically downloaded. The models on the download page include lightweight models, large and medium models. There are 10 model links below the page. After clicking on the link, click on the "File and versions" tab. This page lists the model versions And the list of downloadable files, usually only need to download "config.json; model.bin; tokenizer.json; vocabulary.txt" four files to form a model, the model file is placed in "_models" in the same directory as whisper-faster.exe Under the folder, the downloaded four files are named according to the file version number to set the model folder name. For example, the medium-sized model has two folders: "faster-whisper-medium" and "faster-whisper-medium.en", the downloaded The 8 medium-sized files are placed in corresponding folders according to different versions. It is best to use a download tool with breakpoint resume and verification functions to download the file download tool, such as the open source Motrix, because the web page download will be interrupted or report an error inexplicably, resulting in the incomplete download of the model file and cannot be used.
      By comparing the operating environment of the command line and the operating environment under Subtitles, according to the error message in error_log.txt, it is suspected that the problem is caused by the incomplete download of the model file. Therefore, copy the model folder under the normal command line environment. Go to "..\Program Files\Subtitle Edit\Whisper-Faster\_models\" under the Subtitles environment to overwrite the original folders and files, and then run the engine CTranslate to convert speech to text in various languages, and the work runs normally. The problem has been solved.

**Comment by Purfview** [comment]
Standalone Faster-Whisper has different defaults for models location, copy them to `..\Whisper-Faster\_models\`, or run it in console to download them automatically.

Or you can set models dir in advanced settings with `--model_dir` argument.

**Comment by Purfview** [comment]
Ah, just now I found "hidden" text that "The problem has been solved.", and problem was "incomplete download of the model file".
