### ISSUE TITLE
"culture is not supported" error

### ISSUE THREAD

**Issue by XuTpuK** [SubtitleEdit/subtitleedit#719]
Hi! I opened russian subtitles then tried to edit some line (at bottom in TextBox). When I typed a letter, program is crashed with "culture is not supported" error. Why so?

**Comment by ivandrofly** [comment]
@XuTpuK could you provide screenshoot?

**Comment by XuTpuK** [comment]
Easy! I even spot the moment it happen: when I put cursor in subtitle editor TextBox and switched to Russian locale.

 



 

Place where you see "Начались схватки" at the bottom – it's where I put cursor.

**Comment by niksedk** [comment]
I cannot re-create this... what OS are you using?

**Comment by XuTpuK** [comment]
Win7 x64 with additional Russian keyboard. When I try to switch on my language, program crashes. I don't know what a sh!t is that .NET when completely Unicode strings fail on using non-english letters. Just now tried again – same crash:

 

See the end of this message for details on invoking 

just-in-time (JIT) debugging instead of this dialog box.

 

************** Exception Text **************

System.Globalization.CultureNotFoundException: Culture is not supported.

Parameter name: culture

0 (0x0000) is an invalid culture identifier.

   at System.Globalization.CultureInfo.InitializeFromCultureId(Int32 culture, Boolean useUserOverride)

   at System.Windows.Forms.InputLanguageChangingEventArgs..ctor(InputLanguage inputLanguage, Boolean sysCharSet)

   at System.Windows.Forms.Control.WmInputLangChangeRequest(Message& m)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.Form.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

 

 

************** Loaded Assemblies **************

mscorlib

    Assembly Version: 4.0.0.0

    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

----------------------------------------

SubtitleEdit

    Assembly Version: 3.4.6.544

    Win32 Version: 3.4.6.544

    CodeBase: file:///C:/Program%20Files%20(x86)/Subtitle%20Edit/SubtitleEdit.exe

----------------------------------------

System.Windows.Forms

    Assembly Version: 4.0.0.0

    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

----------------------------------------

System.Drawing

    Assembly Version: 4.0.0.0

    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

----------------------------------------

System

    Assembly Version: 4.0.0.0

    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

----------------------------------------

System.Core

    Assembly Version: 4.0.0.0

    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

----------------------------------------

System.Xml

    Assembly Version: 4.0.0.0

    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

----------------------------------------

System.Configuration

    Assembly Version: 4.0.0.0

    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL

    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

----------------------------------------

 

************** JIT Debugging **************

To enable just-in-time (JIT) debugging, the .config file for this

application or computer (machine.config) must have the

jitDebugging value set in the system.windows.forms section.

The application must also be compiled with debugging

enabled.

 

For example:

 

<configuration>

    <system.windows.forms jitDebugging="true" />

</configuration>

 

When JIT debugging is enabled, any unhandled exception

will be sent to the JIT debugger registered on the computer

rather than be handled by this dialog box.

**Comment by niksedk** [comment]
Can you test this beta: http://www.nikse.dk/SubtitleEdit.zip (portable version)
(I've tried to just ignore the error...)

**Comment by XuTpuK** [comment]
Sorry, Nik, same crash. May be you caught at wrong place? Usually I write trap at class Program in Main function:

 

Application.ThreadException += Application_ThreadException;

Application.SetUnhandledExceptionMode(UnhandledExceptionMode.CatchException);

AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;

**Comment by niksedk** [comment]
thx for your input - I've tried that here: http://www.nikse.dk/SubtitleEdit.zip (portable version)
Any better?
Perhaps you can try the source code too?

**Comment by XuTpuK** [comment]
Nik, it works fine! Thank you J

Yep, I can code myself, but it takes a lot of time to inspect unknown project and do stuff _properly_.

 

Good luck!
