### ISSUE TITLE
Speech-to-text allow additional options

### ISSUE THREAD

**Issue by emcodem** [SubtitleEdit/subtitleedit#7190]
Dears, 
sorry i did not check how exactly you interface with the Whisper projects but i guess you use the commandline examples?
If you do so, it would be really cool if you could provide the option to submit addtional custom commandline parameters, e.g.  to help prevent forever repeated output on foreign language and longer files.
In Const-me and cpp version, the corresponding commandline param is:
-mc 0
in whisper original and faster-whipser its more like 
--condition_on_previous_text False

But of course it would be great if one could specify also all other available parameters to influence the transcription.

**Comment by Purfview** [comment]
It's implemented already, maybe it's not in the stable release yet, I use beta test version.

**Comment by emcodem** [comment]
Fantastic, thanks!
