### ISSUE TITLE
Some WEBVTT files not working in batch converter

### ISSUE THREAD

**Issue by frasderp** [SubtitleEdit/subtitleedit#7195]
As per title, I have some recent files that have a WEBVTT format (appears in mediainfo as S_TEXT/WEBVTT).

These are not recognised in the batch converter. I can load them individually however in Subtitle Edit, 1 by 1, and then save them as srt for example.

Any tips or ideas?

**Comment by niksedk** [comment]
Could you explain a bit more - screenshots are nice, and so are sample files :)
