### ISSUE TITLE
UI Minor Fix

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#7196]
Hello!
There's space missing here.
Language: brazilian portuguese

![V1](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/86feadd3-0f33-4e66-89a3-dc1ba0b7911a)

**Comment by jmaraujouy** [comment]
@Andrebavila , @niksedk :
Here's another case of not enough space for the text:

![imagen](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/0b63ef0a-4acd-4215-85d0-6eab6a2754b5)

Altough the main text seems fine, there is no enough space for the text that simulates the _shadow_, and the text doesn't fit completely. (I raised the brightness of the image so the shadow is more visible in the sample).

It doesn't happen in all languages (english, french and italian, for example, doesn't have this problem). But it does happen, at least, in PT-BR, PT-PT, all three ES variants, Croatian, Dutch, Slovenian and Greek.
