### ISSUE TITLE
Move text after line break to the next susbtitle

### ISSUE THREAD

**Issue by maser478** [SubtitleEdit/subtitleedit#7198]
Hi there,
I want to move test after line break to the next subtitle, does anyone know what kind of hot keys or features can I use?
Preferably in batch.
For example, I want to move 1's "So where's the hot spot? " to the first line of 2's first line.
Split feature is not an option since I have to first create the next time code so the text will be in the right spot.

from
1
00:05:18,708 --> 00:05:22,507
really gonna help me in this game.
So where's the hot spot?

2
00:05:22,540 --> 00:05:24,540

to 
1
00:05:18,708 --> 00:05:22,507
really gonna help me in this game.

2
00:05:22,540 --> 00:05:24,540
So where's the hot spot?

Thank you!

**Comment by niksedk** [comment]
We have this shortcut:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/98a01c5f-1a9d-4d9a-b2a2-55272c57d77e)


Or you can use F2 to source view, move text, and F2 back to list view again
