### ISSUE TITLE
[Feature Request] google Translate option in Commandline

### ISSUE THREAD

**Issue by Seesen1** [SubtitleEdit/subtitleedit#7199]
Hello,
I use SE to translate subtitles in Asian videos. It can also be 20 or more in a row, works quite well via the UI.
The process is always the same:
1. Loading the video (mostly with English subtitles)
2. Translate with GoogleTranslate V1
3. Run bug fixes
4. Load a new video, saving the translation as .srt beforehand.

Many videos have special characters in UTF-8 format (notes, hearts, etc.), which SE translates and saves in the UI in an exemplary manner.
I wrote scripts that automate my process, with SE I use /FixCommonError , but unfortunately this doesn't work via command line or BatchUI, is the translation.

My request would be that the translation via command line would also work like this:

SubtitleEdit /convert Filename .srt /TranslateV1:orgLang:destLang /Fixcommonerror

At this point I would also like to praise all the developers who are really working on this project continuously, that is not to be taken for granted, SE is getting better and better.

**Comment by niksedk** [comment]
Sorry, free translation is limited, so this feature will not work well

**Comment by Seesen1** [comment]
Hi,
Thanks for the feedback.

**Comment by kkm** [comment]
@niksedk I'm not sure, but I read that it's an unlimited offer. https://py-googletrans.readthedocs.io/en/latest/
what do you think? I have more than 4 million characters translator, still no problem.
