### ISSUE TITLE
The format combo box has bugs with new UI.

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#7200]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/89a79f29-0088-46d1-be4c-249be15e5389)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/5626bf26-1183-4738-bf7e-91f406717160)

In the old version of the interface, it was possible to switch formats directly with the mouse wheel, which was convenient. This was very convenient, even when the window was in the background. 
But now in the new version, you can only use the mouse to change the format, which is very inconvenient. I hope it can be changed back.

**Comment by Flitskikker** [comment]
Another bug (or feature?) I found with the new combobox:

It automatically closes when the cursor is further outside the list's bounds.
System comboboxes don't close automatically, allowing you to just pull the scroll bar all the way to the bottom of the screen to get to the end of the list quickly. With the new control, you have to be very precise to keep the cursor within the list.

**Comment by niksedk** [comment]
He, that's a feature for now. The "not-close" area can be expanded.
The combobox just opens a list view control in the current form... another approach would be opening a modal Window, but I'm not sure how that works with minimizing or moving windows.

**Comment by niksedk** [comment]
Hopefully latest beta is OK: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
thx for testing :)

How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip ?

**Comment by Mishasama** [comment]
> thx for testing :)
> 
> How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip ?

OK, fixed.

**Comment by Mishasama** [comment]
@niksedk Hello? This bug happened again on 4.0.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/2d7208f8-0fee-4e2a-87bc-dbbb1c0fbc51)

**Comment by niksedk** [comment]
> @niksedk Hello? This bug happened again on 4.0. 

Ah yes. This was requested by a user.
I is also a bit weird that the combobox can do stuff without focusing the control (either via tab key or mouse click) as the only control.
If this is very important to you I might be able to make this configurable...

**Comment by Mishasama** [comment]
> Ah yes. This was requested by a user.
> It is also a bit weird that the combobox can do stuff without focusing the control (either via tab key or mouse click) as the only control.

What?! That's the interaction design that Windows has always had! All interactive elements in the background window can be operated directly with the mouse scroll. It's really the first time I've encountered a background window that can't be operated with a mouse scroll. This is simply counter-intuitive and customary design!
![2023-09-16_15-20-34](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/e0bd982e-1402-4c20-b030-9629893a357d)
When I can scroll the wheel, why do I change it to 2 clicks (click menus, click options) to do it? What about efficiency? The same problem happens with other toolbar buttons. You have to first click once to activate the window, then click another time to enable the corresponding functionality. This is also not in line with Windows' design specifications.
![2023-09-16_15-30-51](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/024919a2-02de-45c5-bc94-0fd5bb1f4676)
I haven't used Linux very much, and I don't know what that user thinks. Maybe that's the design of Linux, but it's definitely not suitable for Windows.
I think this is not just an important issue for me but for all Windows users... Because when it is inconsistent with the native design specifications of the system, everyone will think that this is a bug and that the software design is very rough.

**Comment by niksedk** [comment]
OK, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
Added this to numeric up/down too...

**Comment by Mishasama** [comment]
> OK, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip Added this to numeric up/down too...

Looks good. But the tool bar... still has to double click when background.
![2023-09-16_17-07-58](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/b98a32ec-d444-412d-acb1-feb7e761039f)

**Comment by niksedk** [comment]
> > OK, how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip Added this to numeric up/down too...
> 
> Looks good. But the tool bar... still has to double click when background. ![2023-09-16_17-07-58](https://user-images.githubusercontent.com/54498172/268436860-b98a32ec-d444-412d-acb1-feb7e761039f.gif) [ ![2023-09-16_17-07-58](https://user-images.githubusercontent.com/54498172/268436860-b98a32ec-d444-412d-acb1-feb7e761039f.gif) ](https://user-images.githubusercontent.com/54498172/268436860-b98a32ec-d444-412d-acb1-feb7e761039f.gif) [ ](https://user-images.githubusercontent.com/54498172/268436860-b98a32ec-d444-412d-acb1-feb7e761039f.gif)

That's Microsoft...

**Comment by Mishasama** [comment]
> That's Microsoft...

Err... sorry no.
![2023-09-16_17-29-15](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/9b75795a-ed88-4d65-8687-a1a57c12d71b)

Taskman:
![2023-09-16_17-30-59](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/7672ea2a-ac7b-4503-b857-4cd990b02823)

**Comment by niksedk** [comment]
Could you explain more? The Toolbar is a Microsoft component in Winforms. What behavior exactly is wrong in your opinion?

**Comment by Mishasama** [comment]
When I click on the Task Manager menu in the background, I just need one click to pop up the menu while activating the window.
But in SE, you have to click once to activate the window, and then click again to open the menu.
