### ISSUE TITLE
[Libse] - Multi-Platform targeting mistake!

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#7202]
To start I would say to go to https://dotnet.microsoft.com/en-us/platform/dotnet-standard
and play with the combobox to see how it affect the other .NETs 

Currently in Subtitle Edit (UI) project we are targeting the .NET-Framework 4.8,
The Libse is multi-targeting: **.net48** (which is another alias for .net-framework) and also **.netstandard2.1**.

If you go to the link I shared above, you will see that the *.netstandard2.1* doesn't have support for all
of the .NET-Framework version, the best match for .NET-Framework48 which is the version that Subtitle Edit (UI) is also using
is `.netstandard2.0`. 

This means the Libse should have targeted only `.netstandard2.0`  (e.g: https://github.com/octokit/octokit.net/blob/main/Octokit/Octokit.csproj#L9)

For what was being said here https://github.com/SubtitleEdit/subtitleedit/pull/7192,
Due to .netstandard2.1 not supporting .net48, when you build the Libse project you would see the dll in the output for .net48 but
that dll is basically irrelevant if Libse has https://github.com/ivandrofly/subtitleedit/commit/863a7bb50f2d7e8cee90470e1469bfe732aa8351#diff-2510567800cb65f7adb4340b4f0647f798d4e77355f4f5e60eaec9f80caeb4f8R72

With Libse targeting *.netstandard2.0* if you build there will be no others dll in the output beside libse.dll 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/31675575-6c4f-4256-960c-85664e39f931)

And when Subtitle Edit (UI) builds you should expect no `System.Security.Cryptography.ProtectedData`  (ref to https://github.com/SubtitleEdit/subtitleedit/pull/7192)

Was there a specific reason for Libse to target both .net48 and .netstandard2.1?

**Comment by ivandrofly** [comment]
The combobox I'm referring to above is this (see image bellow)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/4d5ffd2a-2efe-480f-b3b9-e84d1543a891)

**Comment by niksedk** [comment]
Sorry, libse does not work with `.netstandard2.0`
