### ISSUE TITLE
Please support MPC-BE

### ISSUE THREAD

**Issue by leoxxx** [SubtitleEdit/subtitleedit#7204]
It support MPC-HC, then why not support MPC-BE?

**Comment by niksedk** [comment]
mpv is the recommended video player.

SE tries to search for mpc-be... where and how is your mpc-be installed?

**Comment by leoxxx** [comment]
Zip packgae version, no install. Just set it default apps for video.

**Comment by niksedk** [comment]
You can use the setting MpcHcLocation in Settings.xml, to point to you exe file.

**Comment by leoxxx** [comment]
Thanks
