### ISSUE TITLE
Something left in dark mode

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7205]
Maybe these small parts could be turned too:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/016f2732-8c0b-4475-b6c1-7dfda1ad5c8b)

And maybe it's better to change these little arrows to light color:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/d0a730c3-76c8-4e48-ab03-3bf006231b5f)

FYI. :)

**Comment by LeonCheung** [comment]
A few more:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/605cce93-f3fd-4ca0-ae6b-66264e01704f)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/5148467d-8cdc-4d1d-9232-df4d79ad72c4)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/9d47027d-e60e-48f7-9ef7-8204d2a5b7e3)

**Comment by niksedk** [comment]
Thx, I've updated some labels to have another "disabled" color. (I'm also make them italic + smaller font size atm)
The default Winforms controls often cannot change scrollbar color / border colors etc :(

In latest beta all combo boxes + numeric up/down uses the new layout.

How does the latest beta work for you?

**Comment by LeonCheung** [comment]
@niksedk Yes, I saw the new combo boxes and arrows, that's a great update! 👍

Just downloaded the latest beta (499). An error message when enabling dark mode:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/1bd51d60-2420-4eaa-a66f-e24a8ef7ffe5)

After restarting SE, it looks like this (I didn't toggle show list view grid lines so far):
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/5ae6ea79-db84-4a1c-9fa7-1a67ae293c65)

FYI.

**Comment by niksedk** [comment]
Thx, tried to fix it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
Better?

**Comment by LeonCheung** [comment]
Cool, it's resolved. 👍 And:

1. Maybe one more 😆  :

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/ad231024-ebad-4217-af63-c942a9c0db1e)

2. Maybe the default height of this combo box can be optimized:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/e48aff0b-cf8e-4583-94ca-62e59b230662)

3. For the little arrow indicator, it seems to be possible to change the color:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/3fe113cd-137e-416a-945c-d5b3df36db59)
Or we are still limited by Winforms for now in this regard?

**Comment by LeonCheung** [comment]
Not sure about this case, just FYI:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/604437c7-4857-4e0e-acda-da4b629c39ff)

**Comment by niksedk** [comment]
Beta updated with some theme related UI fixes: C:\Data\Issues\new unknown sub

The small menu triangle I do not know how to change - the collapsed menu I will have to look more at.

**Comment by jmaraujouy** [comment]
> The small menu triangle I do not know how to change - the collapsed menu I will have to look more at.

Does [this](https://stackoverflow.com/questions/26605368/change-the-color-of-the-arrow-near-the-menuitem-in-c-sharp) help?

_(Please, ignore my message if I'm saying something stupid. I'm not a coder, but still want to help in any way I can)_

**Comment by niksedk** [comment]
> > The small menu triangle I do not know how to change - the collapsed menu I will have to look more at.
> 
> Does [this](https://stackoverflow.com/questions/26605368/change-the-color-of-the-arrow-near-the-menuitem-in-c-sharp) help?

A lot, thx :)
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Maybe one more:


https://github.com/SubtitleEdit/subtitleedit/assets/494788/e9b3cb66-8e3c-4014-9ade-1803b9a2a380

**Comment by niksedk** [comment]
A few more fixes (still missing the file type icon): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

@jmaraujouy: I'm testing a dark theme messagebox... could you possible make some blue (or themed) icons?
    Error
    Question
    Exclamation
    Warning
    Information

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/a23989a5-ad5e-4ab7-bcb4-d247074e10ea)

**Comment by jmaraujouy** [comment]
> @jmaraujouy: I'm testing a dark theme messagebox... could you possible make some blue (or themed) icons?

@niksedk Something like this, I suppose?

![imagen](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/f3ae3e1a-a88f-4964-a469-1db9d2e13616)

They can be made bigger, to fill the full 32x32px area, like the ones pictured above.
(Icons in this icon set are padded, but that can be removed)

[Icons.zip](https://github.com/SubtitleEdit/subtitleedit/files/12298840/Icons.zip)

**Comment by niksedk** [comment]
New MessageBox up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
A few more, no big deal. FYI.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/2e910965-a6f5-46d4-873b-17e8a0c83f68)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/66022a62-ffeb-4eab-9f77-bad935581a8b)
