### ISSUE TITLE
Audio to Text (Whisper) -> wrong timestamps

### ISSUE THREAD

**Issue by Purfview** [SubtitleEdit/subtitleedit#7207]
3.6.13 NEXT beta 490

Actual .srt has proper timestamps but somehow they become different in SE:

![alt text](https://i.imgur.com/glKVCnK.png)

**Comment by niksedk** [comment]
Could you attach the audio file?

**Comment by Purfview** [comment]
https://we.tl/t-8xiNgZnACD

**Comment by niksedk** [comment]
thx - good to have this fixed :)

Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
Via this commit: https://github.com/SubtitleEdit/subtitleedit/commit/b80f996bc0f2283c40aa1b2ff827ac5ca17a6b38

**Comment by niksedk** [comment]
This bug has probably always been there.

"Auto adjust timestamps" adjust timestamps to audio-start-after-silence, so it works via the waveform, but only when silence exists between speech.
