### ISSUE TITLE
ASSA: Better logic for Set Position tool

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7222]
Sometimes we have to work on a video source of different resolution (e.g. a smaller/watermarked version from the original HD version) Then we have to set the resolution like this to work as if we already have the target resolution:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/4ae1a026-4c2e-4e5c-853b-982bb1a3126e)

However, the Set Position tool seems not to respect that, and still follows the actual video source, which is unwanted:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/fbf8a15e-8b54-4501-9208-b971f5d7f4a0)

So a better logic, in this case, would be to simulate the target resolution set in Properties. Because otherwise, it's unusable at all.

**Comment by niksedk** [comment]
Thx for the info :)
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
That's awesome. Thank you so much!
