### ISSUE TITLE
Find and Find&Replace has lost focus...

### ISSUE THREAD

**Issue by jmaraujouy** [SubtitleEdit/subtitleedit#7224]
In earlier versions, when you clicked Find (or used the keyboard shortcut Ctrl+F), the search window would appear, and the focus was on the search window's input box.

This was the default behavior with the Find & Replace window as well.

This was **extremely useful** because we only had to click Ctrl+F or Ctrl+H, and we could start typing the term to search directly. Everything was done with the keyboard.

In the latest beta versions, when calling the search window, the focus is no longer on the input box by default. When you press Ctrl+F, you then have to click inside the input box to be able to start typing the term to search for.

_(Note: I don't know if this is a bug or a feature... I found a [closed issue with a similar topic](https://github.com/SubtitleEdit/subtitleedit/issues/6803) and maybe the behavior I'm describing are a consequence of those changes)_

**Comment by niksedk** [comment]
Hm... it's working fine here for me in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Hm, it looks like it does...

**Comment by niksedk** [comment]
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
