### ISSUE TITLE
Problem with the change of resolution script and margins

### ISSUE THREAD

**Issue by Nagutos** [SubtitleEdit/subtitleedit#7225]
Hello, I have a problem with the script to change the resolution in the convert batch. When I use the script on a ".ass" file, the x,y margins don't apply. 

Here is a screenshot of the margin results after the conversion. The "left" parameter should be at **633** but it remains at **211**. 
The original **640x360p** file is converted to **1920x1080p.**

![Capture d’écran 2023-08-07 230803](https://github.com/SubtitleEdit/subtitleedit/assets/78440072/5f505cab-399e-41db-b38e-6c5fd5838128)

Also, in the French translation of the software, there's a "g" missing in the "Supprimer les li "g "nes" tab.

![Capture d’écran](https://github.com/SubtitleEdit/subtitleedit/assets/78440072/bd265a51-7274-4d64-bf10-1d5280d605ce)

**Comment by niksedk** [comment]
Did you enable margins?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/7ffbfd8e-1ae9-41d2-975e-13cc87996aa7)

**Comment by Nagutos** [comment]
> Did you enable margins?
> 
> ![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/7ffbfd8e-1ae9-41d2-975e-13cc87996aa7)
> 

Yes I did

**Comment by niksedk** [comment]
Hm, it works fine here... could you attach your ASSA subtitle?

**Comment by Nagutos** [comment]
> Hm, it works fine here... could you attach your ASSA subtitle?

### Yes, of course

# Here are the [subtitles](https://github.com/SubtitleEdit/subtitleedit/files/12333317/ASS.zip)

### I've also taken screenshots of the parameters I've set 

![image](https://github.com/SubtitleEdit/subtitleedit/assets/78440072/b4ff7d90-d5d8-4ab3-8836-b5e42cad104f)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/78440072/abd1dc61-bd25-4934-a8b2-5b9575101c21)

I also specify that I am on the latest version of the software there 3.6.13

**Comment by niksedk** [comment]
Hm, I do not see anything not working... what exactly is the problem?

**Comment by Nagutos** [comment]
> Hm, I do not see anything not working... what exactly is the problem?

 Here you can see the margin left value in the original file, with the video resolution of the file set to 640x360p.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/78440072/03da360b-a2bf-4096-8a95-a8984499dedb)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/78440072/eef77c03-2b10-44e1-b4fb-933092b388af)

Here, the value of the left margin is not modified according to the resolution of the output file, even though the file has been converted to 1920x1080p.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/78440072/74b3d2b9-9b3a-4f5b-a407-dc2fc6bf895d)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/78440072/d9c91101-4b0c-45ac-9696-21d8095ddef1)

You can find this information by opening the file with notepad++ and going to line 72.

This gives me the following result in 1920x1080p which is not centered :  
 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/78440072/cdd7db29-d470-4dc7-a74d-682404531ad8)

Results I have in the source video: 

![image](https://github.com/SubtitleEdit/subtitleedit/assets/78440072/cd4b093a-6a6d-4539-8ea6-ec4f877b8f68)

This is what the output file should normally look like when converted to 640x360p --> 1920x1080p resolution.

640x360 * 3 = 1920x1080

Then the margin should normally be calculated with : 

211 * 3 = 633

213 * 3 = 639

However, as you can see from the previous screenshots, the margin left modification is not applied correctly. 

I try to be as clear as possible in my explanations.

**Comment by niksedk** [comment]
Thx for explaining :)
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
?

**Comment by Nagutos** [comment]
> Thx for explaining :)
> Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
> ?

It looks good, thank you very much. I'll let you close the issue.
