### ISSUE TITLE
Hotkeys to move start and end points of a new selection don't work until Duration box is selected

### ISSUE THREAD

**Issue by traycerb** [SubtitleEdit/subtitleedit#7226]
If i create a new subtitle (using hotkey, on my system, `Shift+F9`), the hotkeys I created to change selection length (adjusting start or end) won't work until I click into the duration text box, which appears to disable the flashing `Auto `text.  Attempts to lengthen the duration revert back to default of `1.000 `seconds.  It's hard to explain in person, here's a video of it, and a screen shot of my settings further down

https://github.com/SubtitleEdit/subtitleedit/assets/4313283/522a8a30-4591-4b98-8de7-b1ae5a9a2697

After creating the new subtitle selection, pressing the hotkeys causes unexpected behavior, either time-shifting, or doing nothing at all.   After I click into the duration box, the flashing `Auto` marker goes away, and the hotkeys then work as expected, increasing and decreasing the selection length as desired.

EDIT: If Waveform setting "Set focus on mouse enter" is on, then just going outside the waveform box and back in is enough to trigger the correct behavior.  It looks like it is some issue with hotkeys being instantiated depending on what part of the program has focus. 

![2023-08-08  904  - Settings - ShareX Screenshot](https://github.com/SubtitleEdit/subtitleedit/assets/4313283/82731b2a-9609-4d7e-92c7-c1a46fad253d)

```
Move Start 100 ms back Ctrl+Shift+Left
Move Start 100 ms forward Ctrl+Shift+Right
Move End 100 ms back Ctrl+Shift+Down
Move End 100 ms forward Ctrl+Shift+Up
```

Thanks for Subtitle Edit, it's one of the most powerful subtitle editors, free or otherwise.  I donated a year ago when I first started using it, and I continue to be appreciate of it and the developers.

**Comment by traycerb** [comment]
Also, not sure it's worth creating a new issue, but while the hotkeys can't go past or under durations (`Settings - General - Min/Max duration)`  dragging the handle with mouse works fine.  

Frankly I think it makes sense that we can override that easily, but then maybe the hotkeys should be able to also.  But again, then what function would the duration settings serve? 🤔

**Comment by niksedk** [comment]
Tried to stop the auto-timer when moving start/end here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

**Comment by traycerb** [comment]
Thanks for looking at it.  I gave the 4.0.0 beta a quick try, and the behavior seems to be the same unfortunately.

The duration briefly changes, and then is reset.  If I hold the hotkey down on repeat, it goes a few durations out before resetting quickly.

**Comment by niksedk** [comment]
Hm, works fine here...

**Comment by traycerb** [comment]
Yes, uninstalled and did a fresh install, and now it's working. 

Before, I installed without removing old version, and though the new version was clearly installed (new interface, etc), the behavior was acting like the old version.
