### ISSUE TITLE
Error: subrip - input file too large!

### ISSUE THREAD

**Issue by JeWe37** [SubtitleEdit/subtitleedit#7244]
For converting ass subtitles to srt, I have run into this issue for some subtitles that are large enough to exceed the 10MB limit. I don't fully understand why it exists in the first place, it seems to have caused issues before, say in #5930. Are there any hard limits elsewhere in the code or does this merely exist so that memory usage doesn't explode? Removing [it](https://github.com/SubtitleEdit/subtitleedit/blob/d59b6bb0bcdf82f1704e5b9f7e194ec703f200eb/src/ui/Logic/CommandLineConvert/CommandLineConverter.cs#L779) should be trivial in so far as I can tell, is there any reason not to?

**Comment by niksedk** [comment]
SE let all 300+ formats try to open the input file... if the input file is 10MB+ this will freeze SE for a long period of time!

How do you open the file? Drag-n-drop where? File menu?
Could you attach a subtitle that get this "Input file too large" message?

**Comment by JeWe37** [comment]
Sorry, I should have been more precise: I'm referring exclusively to the command line conversion. I have never even used the GUI, so freezes aren't exactly a concern. The line I linked is also used only when command line conversion happens, so freezes are a non-issue. The subtitles themselves are fine, they just happen to feature rather excessive tagging for subtitling the OP and ED. If you want a sub that breaks like this tho, that's easy enough. Just run this script:
```python
import sys
import datetime

with open(sys.argv[1], "w") as f:
    f.write("""[Script Info]
; This is a Sub Station Alpha v4 script.
; For Sub Station Alpha info and downloads,
; go to http://www.eswat.demon.co.uk/
; or email kotus@eswat.demon.co.uk
Title: Wolf's rain 2
Original Script: Anime-spirit Ishin-francais
Original Translation: Coolman
Original Editing: Spikewolfwood
Original Timing: Lord_alucard
Original Script Checking: Spikewolfwood
ScriptType: v4.00
Collisions: Normal
PlayResY: 1024
PlayDepth: 0
Wav: 0, 128697,D:\Alex\Anime\- Fansub -\- TAFF -\Wolf's Rain\WR_-_02_Wav.wav
Wav: 0, 120692,H:\team truc\WR_-_02.wav
Wav: 0, 116504,E:\sub\wolf's_rain\WOLF'S RAIN 02.wav
LastWav: 3
Timer: 100,0000

[V4 Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding
Style: Default,Arial,20,65535,65535,65535,-2147483640,-1,0,1,3,0,2,30,30,30,0,0
Style: Titre_episode,Akbar,140,15724527,65535,65535,986895,-1,0,1,1,0,3,30,30,30,0,0
Style: Wolf main,Wolf_Rain,56,15724527,15724527,15724527,4144959,0,0,1,1,2,2,5,5,30,0,0

[Events]
Format: Marked, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text""")
    for i in range(200000):
        delta = datetime.timedelta(seconds=i)
        f.write(f"Dialogue: Marked=0,{delta}.00,{delta}.00,Wolf main,test,0000,0000,0000,,test")
```
(adapted from the next best example of an ass file I could find) this breaks with the error
```
Gtk not found (missing LD_LIBRARY_PATH to libgtk-x11-2.0.so.0?), using built-in colorscheme

Subtitle Edit 3.6.13 - Batch converter

/home/jellyfin/test.ass: subrip - input file too large!

0 file(s) converted in 00:00:00.0239418
```
Trying to see how long a conversion would actually take, I'm also not sure if there isn't a bug here already, as in [this line](https://github.com/SubtitleEdit/subtitleedit/blob/d59b6bb0bcdf82f1704e5b9f7e194ec703f200eb/src/ui/Logic/CommandLineConvert/CommandLineConverter.cs#L845) you are comparing to 1MB rather than 10MB. Based on what I am seeing though I think it should still remain under a minute with the CLI interface.

**Comment by niksedk** [comment]
Fix included in latest beta version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Or are you using https://github.com/SubtitleEdit/subtitleedit-cli ?

**Comment by JeWe37** [comment]
I was unaware of the cli version, though that may be handy as it would likely save me from having to have a dummy X server running. I suppose the same change is needed there for consistency.

**Comment by niksedk** [comment]
yep, cli project updated too: https://github.com/SubtitleEdit/subtitleedit-cli
