### ISSUE TITLE
Adjust/Set end & go to the next (F10) sometimes produces a totall mess and push the line in MINUS duration

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7247]
When I merge two lines, the fastest way to **set the end point** is to use F10 where I want, that is, SET END & GO TO THE NEXT (the slow way is to do it manually, which is very tedious: to go to the end of the merged lines, then to drag and shrink it to the left in the waveform).

But, maybe in 1 of 20 times, instead of setting the endpoint at a desired position, the program pushes some lines in MINUS duration. It is mostly -8 to -10 seconds. Instead to have your endpoint of the two merged lines where you want, you get some line(s) to have minus duration and VANISH from the waveform because they have negative duration. To fix this, you must go (the left of the textbox, where you edit titles) and use the arrow to go to the plus duration and your text to appear again. 

Do I miss something and do something wrong, or this is a bug? IF YOU ARE NOT SURE what I am talking about, I'll make a youtube video for you, Nikolaj.

**Comment by niksedk** [comment]
He, got it one... tried perhaps 30 times. Don't know what happened... yet ;)

**Comment by Cyberyoda1411** [comment]
I thought that it occurs when there is some overlap in the subtitle, but there are no rules. You can have an overlap and this F10 shortcut to work perfectly and you can have everything normal, but you get a 'standard' -8 sec duration and your line just vanishes, because it is in the negative duration, it goes to non-existence. : ) 

Maybe you can find some reason, I couldn't find one. Yes, it is not '20 times', it is some random number. You click a lot of times, and it works perfectly. Then you click and you got the mess...

**Comment by niksedk** [comment]
Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip ?
It will prevent anything from happening if  the current video position is before start time... 
I think this is what happened... I made about 50 F10 carefully and not one miss... then turned the speed up and got the error.

>To fix this, you must go (the left of the textbox, where you edit titles) and use the arrow to go to the plus duration and your text to appear again.

Or press Ctrl+Z

**Comment by Cyberyoda1411** [comment]
Of course, I'll test the newest beta. I won't force anything, I'll edit some subtitles, and see if the error will occur. Generally, it always occurs in 20 minutes video at least twice. That means, not too often, but at least a couple of times in one sitcom episode. I'll let you know if the problem is present or if it is fixed. 

Now I don't understand you, for a change. How did you 'turn the speed up'? Do you mean the last button below the waveform (Play rate/Speed), and you put it at more than 100% speed, e.g. 110%? If it is so, I don't use any other speed than normal. I always use 100%. 
-----------------------------------------------------------------------------------
Out of topic, or maybe not. What if we have two lines totally overlapped? It is the case when we have somethng like this:
37
00:02:39,114 --> 00:02:42,084
38
00:02:39,114 --> 00:02:42,084

In this case, the start time of line 38 is earlier than end time of the line 37. Sometimes it can be drag in waveform, and to separate them, but sometimes you can't move anything. What is the most elegant solution for this, to separate these two lines in the waveform? My only solution is to go to START TIME (left of the edit texbox) and to make line 37 to show earlier, to make it to be moved to the left in the waveform. Is there any more elegant solution for that? When the overlap is complete?

**Comment by niksedk** [comment]
He, by "turned up the speed", I mean that I just did it really fast and not too careful...

**Comment by niksedk** [comment]
> What if we have two lines totally overlapped? It is the case when we have somethng like this: 37 00:02:39,114 --> 00:02:42,084 38 00:02:39,114 --> 00:02:42,084
> 
> In this case, the start time of line 38 is earlier than end time of the line 37. Sometimes it can be drag in waveform, and to separate them, but sometimes you can't move anything. What is the most elegant solution for this, to separate these two lines in the waveform? My only solution is to go to START TIME (left of the edit texbox) and to make line 37 to show earlier, to make it to be moved to the left in the waveform. Is there any more elegant solution for that? When the overlap is complete?

I do not have a more elegant solution for this... and some times, like in format ASSA is okay and even normal with more than one line with same time codes.

**Comment by niksedk** [comment]
I presume this is fixed, so I will close this now... do re-open is the issue still occurs
