### ISSUE TITLE
Unable to download mpv player

### ISSUE THREAD

**Issue by fasilmrm** [SubtitleEdit/subtitleedit#7248]
Unable to download mpv player. kindly see the attachment. 
![Uploading IMG20230817123630.jpg…]()

**Comment by niksedk** [comment]
Check your internet connection + firewall...
Read more here: https://www.nikse.dk/subtitleedit/help#settings_video

**Comment by fasilmrm** [comment]
![Screenshot (2)](https://github.com/SubtitleEdit/subtitleedit/assets/61681381/93073cbf-5e34-47d0-a8eb-1892f0219aee)

**Comment by niksedk** [comment]
**Check your internet connection + firewall!!!**

What country are you in?

**Comment by fasilmrm** [comment]
India
