### ISSUE TITLE
When the title lose focus, the letters are pretty blurred and not so visible (settings?)

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7252]
This is the picture of the earlier version of SE beta 257, you can see how the letters are still pretty visible, even if they have no focus (it is in the edit textbox or in the waveform, it doesn't matter). 

![Screenshot_4](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/49f982ec-9101-47ea-98e4-79b8b5c78760)

But, in the new beta versions, when the focus is not on the line, the letters are almost invisible, and it is pretty uncomfortable to see what is the current line, letters are pretty GRAY:

![Screenshot_6](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/3be35651-33dc-426e-9236-0bdc81c0f05e)

Can it be changed in some settings? Or, can it be changed to be MORE VISIBLE AGAIN, like in the earlier beta versions?

Nikolaj, as you can see, I don't have exotic remarks anymore, these are just practical things because I use your program almost every day (subtitles are my hobby). The same as hitting F10 produces (sometimes, without any known reason) some minus duration (and it should be solved), this thing makes the work uncomfortable, because we have GRAY letters on the blue selection color, every time when the current line loses the focus.

**Comment by Cyberyoda1411** [comment]
This is COMPLETED? What about the issue? It is not so nice for eyes to see the gray on blue. It should be offered to be black on blue. 
And what happened to the overlap messages that are totally false? This topic is also considered CLOSED and I see that non-accurate messages all the time.

**Comment by niksedk** [comment]
It is back to black :) 
(sounds like an Amy Winehouse song..)

**Comment by niksedk** [comment]
Overlap messages that are totally false are also fixed :)

**Comment by niksedk** [comment]
If you look closely, you can the issues are closed by a commit...

**Comment by Cyberyoda1411** [comment]
THANK YOU! 
If you can, find out what happens with the F10 and the minus duration, that would be magnificent. At least, when it happens. So I can avoid some things related to this.

**Comment by Cyberyoda1411** [comment]
I can't see any new beta, and the text is still gray. You didn't upload the changes yet?

**Comment by niksedk** [comment]
Now a new beta is up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
