### ISSUE TITLE
Modify Selection Tool with ASSA

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7258]
It seems the latest beta doesn't support selecting by Style and Actor?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/2d3c1b28-02ef-4441-ab52-03158887cb80)

build 678.

**Comment by LeonCheung** [comment]
Cool. Maybe extend the dropdown a little bit since Actor is hidden beneath here:  :)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/196123a1-3b70-46a9-8ff3-4dbb47553d99)

**Comment by niksedk** [comment]
Hm, any better? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Perfect. :)
