### ISSUE TITLE
After audio to text, certain words have uppercase when it shouldn't

### ISSUE THREAD

**Issue by Prebstermus** [SubtitleEdit/subtitleedit#7259]
Norwegian words like "Meg" meaning me , and the word "Jeg" meaning I, have upper case when it should have a lower case unless it is at the start of a sentence.

**Comment by niksedk** [comment]
Could you provide a small audio sample?

**Comment by Prebstermus** [comment]
https://github.com/SubtitleEdit/subtitleedit/assets/142585122/e5610327-a9d5-40bc-b139-0329d8d1a33f

**Comment by Prebstermus** [comment]
As you can see, the word "Meg" got upper case.

**Comment by Prebstermus** [comment]
Words like "Jo" "Heller" also have upper case when they shouldn't
