### ISSUE TITLE
Import Blu-ray (sup) for edit functionality - Bugs and suggestions

### ISSUE THREAD

**Issue by nautilus7** [SubtitleEdit/subtitleedit#7261]
Hi, I am using this new functionality to quickly edit my blu-ray subtitles (synchronization and brightness adjusting). I find it very handy. I have a couple of suggestions:

1. In the "Adjust Brightness" window, the number (percent) inside the input box does not match the number shown on the top left (above the slider). Once the % is changed from 100%, the two numbers do not match anymore!

2. When I set a brightness percent and press the OK button, the "adjust brightness" window closes and it starts changing the brightness. While this task is running (usually it takes around 10-20 seconds for a normal sup) a progress bar is shown at the bottom of the main window. The problem is that if the user selects another operation **while the progress bar is loading**, the brightness adjusting task stops and not every image in the sup file is brightness adjusted.
  I suggest, when adjusting the brightness, display the progress bar on the "adjust brightness" window, instead of the main window. After the task is complete, aka all images are changed, then close the "adjust brightness" window and return to the main one.

3. Is it possible to know the original brightness of the images inside the sup file? If yes, it would be great to allow adjusting the brightness by directly entering the desired brightness level (0-255) as well. If not, allowing the user to enter both the initial/original and the final/desired brightness levels would be nice. This way, the program would do the calculation instead of the user... For example entering brightness levels 255 / 180, the program would apply a brightness adjustment of 76,60% automatically.

**Comment by niksedk** [comment]
Thx for the info :)

I've fixed an issue in the "Adjust Brightness" window. I've kept the progress bar in the main window, but disabled controls.
How does this work for you?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

If you're still getting anything weird, a screenshot would be nice :)

----------
It's not possible to get the original brightness of an image - and it's pixels based and not image based

**Comment by nautilus7** [comment]
Thanks! Disabling controls during brightness adjustment works fine, but the inconsistency between the two brightness values still remains. See attached screenshot.

![ss1](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/62f86477-e62d-45bb-8911-081eddc2268f)

**Comment by niksedk** [comment]
Thx :)
Should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by nautilus7** [comment]
Thanks for the quick fix, but still the number on the top left does not show any decimal points. It's always an integer. But at least it rounds off correctly, so no big deal for me.
