### ISSUE TITLE
Player button update issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7262]
I noticed this for a while with latest betas. The state for STOP button is kinda not right occasionally, not always, but I did experience it quite a few times:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/8205b51b-d424-45eb-8527-ecdf53503e12)

Not sure if there is a little update issue. FYI. :)

**Comment by niksedk** [comment]
How can I re-create it ;)

**Comment by LeonCheung** [comment]
Haha, that's the same question I'm asking myself.  We'll see about that. XD
