### ISSUE TITLE
Renumber in batch convert

### ISSUE THREAD

**Issue by miniop** [SubtitleEdit/subtitleedit#727]
Hey i would like to ask if it is possible in the batch convert to add also the renumber.

Thanks

**Comment by ivandrofly** [comment]
Working on it ;) /cc @miniop

**Comment by ivandrofly** [comment]
http://www43.zippyshare.com/v/FflwMyGV/file.html /cc @miniop 
Let me know if is that way you wanted

**Comment by miniop** [comment]
yess!! :) thank you very much

**Comment by ivandrofly** [comment]
;) @miniop

**Comment by Ede123** [comment]
@ivandrofly: Any chance for a patch / pull request?
I would love to have this feature, too!

**Comment by ivandrofly** [comment]
yeah... I just need to setup a few thing ;)

**Comment by niksedk** [comment]
Should we just always renumber?
Could there be any reason not to renumber?

**Comment by Ede123** [comment]
I can't think of any...

Maybe just add an option to "normalize" subtitle files (e.g. renumber, remove double blank lines, remove blank lines at the end of file, etc.) could be added.
