### ISSUE TITLE
"Actor" Shortcut and "Actor" show up on Ass Subtitle

### ISSUE THREAD

**Issue by JeffersonPenPen** [SubtitleEdit/subtitleedit#7272]
Hello,

I use the "Actor" function a lot, especially because SE is my main tool to translate, not only subtitles, but also scripts. And I do that for voice over studios, so it is imperative that the "Actor" tag is next to the subtitle. Two things that could help a lot are:

1. Shortcut to "Actors": I need to setup macros on my keyboard or mouse in order to add "actors" in every single line. A shortcut to it would be a great help.
2. "Actors" tag showing up on subtitles: If there was a checkbox to show the "Actor" along with the subtitle as a review tool - in order to avoid label lines with wront tags - would also be great. Something we could just easily toggle on and off, like:

[LUCIA] Hello, darling. / Hello, darling.

If those functions already exist, I couldn't find them at all. If not, Id be happy to help testing them or anything I could assist with.

Thank you in advance.

**Comment by niksedk** [comment]
1) It's in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
Please give it a test run :)
You need to configure shortcuts in Options - Settings - shortcuts (search for Actor)

2) Depending for subtitle format, you can show the "Actor" as a list view column:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/b73a92b5-cb44-4691-b3dc-e7d9e781928d)

**Comment by JeffersonPenPen** [comment]
Thank you! I will check the lastest Beta. 

And concerning the 2 request, I didnt mean on the list view, but on the subtitle showing on the video. 

I normally use ASS because of the Actor function. And as I am translating right now, I just made a mock-up of what I pitched.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/91253192/057cf7da-7a9e-4241-a289-c76818be393a)

While the first one would be just be used during translation and for review before sending them to a studio, the second one would be the final - and actual version.

**Comment by JeffersonPenPen** [comment]
Just gave it a test on the Beta version and I have a couple remarks and a possible bug.

1. It is not clear how you link a specific actor to a specific position. For what I could assume, the first 8 actors on the list would be set as 1 to 8. That can be a problem with your lead character is called "Zebra", for example. lol I understand you can name it 1_Zebra beforehand just to make it to the top of the list, but still, it is not clear how that works. Is that a step I should do it before using the shortcuts to be able to choose any actor I want to a given position?

2. My first attempt was making shortcuts using my Numpad - which is the keys I assign my macros nowadays, but it didnt work. In fact, I guess any key doesnt work, unless it is a combination of two keys, meaning: If I assign just NumPad 8 I got a error message when I press my right button on my mouse, but if I assign it Ctrl+NumPad 8 works fine. I just attached the message I got everytime I tried to assing a single NumPad key as a shortcut. I tried assigning single letter keys, as a matter of testing, and I also got the same error message when I pressed right button on my mouse. 

![image](https://github.com/SubtitleEdit/subtitleedit/assets/91253192/7fbf2181-d94e-49d4-ad8f-90871a709458)

Besides that, the structure of the actor shortcuts are fantastic. Id just amp them up to 10 Actor Shortcuts to be able to use the 10 NumPad keys.

I was waiting for that since I began using Subtitle Edit. It will make work with it way easier. Thank you.

**Comment by niksedk** [comment]
OK, SE has 10 actor shortcuts now. 
The shortcuts are assigned to the first 10 actors alphabetically.
SE cannot use single letters as menu shortcuts requires either Ctrl/Alt/Shift. If we removed the shortcuts from the context menu,  single key shortcuts are possible, but then we have no no context menu with shortcuts.

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
