### ISSUE TITLE
Color/colour picker malfunction Windows 10

### ISSUE THREAD

**Issue by Windrider6** [SubtitleEdit/subtitleedit#7273]
Subtitle Edit 3.6.13, both the release version and the latest Beta
Windows 10 Pro 64 bit Version 22H2

This annoying malfunction happens on both of my computers.

The color picker colors get corrupted, with the shown colors, color codes, and what is in Settings.xml not matching each other.  Also, colors getting into the color picker that I have never chosen before, usually blue (#0000FF).  Sometimes I will see 3 or more of the colors being blue, yet I have never chosen that color!

Here is the color picker at the moment, with only the last color being consistent and correct:

![Color_picker_problem](https://github.com/SubtitleEdit/subtitleedit/assets/74514948/4b17cfc5-fc38-4c77-94f7-12bbfdda164f)

0: Code showing is FFFFFF (wrong), but color produced and Settings.xml is FFD0FF, which is correct
1: Code showing is FFFF7F (wrong), but color produced and Settings.xml is FFBE7F, which is correct
2: Code showing is CCCCCC (wrong), but color produced and Settings.xml is CCFFCC, which is correct
3: Code showing and color produced are both 0000FF (which I have never chosen), and Settings.xml is FF80FF, which is correct
4: Code showing and color produced are both A0A0FF, which are both correct, but Settings.xml says A0FFFF
5: Code showing, color produced, and Settings.xml all say 0000FF, but I've never chosen that color
6: Code showing, color produced, and Settings.xml all say A0FFEF, but I've never chosen that color.
7: Code showing, color produced, and Settings.xml all say FF0000, which is the only one that is 100% correct

**Comment by niksedk** [comment]
Thx, good catch :)

Hopefully better now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by Windrider6** [comment]
After a bit of some use, quitting and running the program a few times, there is some improvement.

+ Colors I have not chosen are not appearing anymore
+ Color appearance and actual color used in the color picker are the same as the codes in Settings.xml
- Color picker codes still differ from the color appearance and actual use.

One screenshot as an example:
![2023-08-22 05_50_26-Choose color](https://github.com/SubtitleEdit/subtitleedit/assets/74514948/48aab6cd-00aa-4fb6-8e07-af4d10ecd9fe)

0: Code is A0A0FF, actual color is A0FFFF
1: Code is FFFFFF, actual color is FF80FF
2: Code is CCCCCC, actual color is CCFFCC
3: Code is CCCCFF, actual color is CCCCFF
4: Code is AAAAFF, actual color is AAAAFF
5: Code is FFFF7F, actual color is FFBE7F
6: Code is FFFFFF, actual color is FFD0FF
7: Code is FFFFA0, actual color is FFA0A0

**Comment by Windrider6** [comment]
### **Ooops!**  I clicked the wrong button.  The issue should not be closed yet!

**Comment by niksedk** [comment]
OK, a few issues fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
Which hopefully makes it work correctly...

@Windrider6: If it's not working, please let me know:
1) How you start the color picker
2) How you set the color / read the value of the hex
3) How you see that the color is not wrong

**Comment by niksedk** [comment]
Fixed another issue when picking colors from the recent colors... and the OK/Cancel buttons are now also correctly positioned
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by Windrider6** [comment]
Just in case, I deleted Settings.xml before replacing with your latest Beta.

Things seemed to be going OK, with the colors shown and used being the same as the code displayed.

Then a color showed up that I had not chosen:
![2023-08-22 10_04_27-Choose color](https://github.com/SubtitleEdit/subtitleedit/assets/74514948/cee8fd1a-60d8-467e-95bd-b31e788da0a5)
I had last used #A0FFFF, which is shown as the second color, but now the first color #A0FFFB showed up out-of-the-blue without having been "chosen".

Your questions:

1.     How you start the color picker
I right-click the line in the list view, or select text in the text area, and choose "Color".

2.     How you set the color / read the value of the hex
I click on the color I want, or if the color is not one of the eight, I enter the hex code, then click OK.

3.     How you see that the color is not correct
I see that the color displayed is correct, and if I choose to use it, the code used in the text is correct.  But the hex code shown is wrong for the color, as you can see with my previous screen shots.  **But**, at the moment, it seems that **this** issue is fixed.


Now a new problem.  The "Translate", "Create", and "Adjust" tab area disappears randomly until I quit the program and restart it.  Grrrr.  Most times I don't notice right away when it disappears, but I know that once it disappeared after coming back from full-screen of the video (using MPC-HC), and once it disappeared while I was merely typing in the "Text" area.
![2023-08-22 09_56_11-_Dead Man's Gun S01E04 The Imposter srt - Subtitle Edit 3 6 13](https://github.com/SubtitleEdit/subtitleedit/assets/74514948/9edd5c57-f10f-48b2-9983-d6ca9a61367a)

Also, another issue I cannot pin down is that sometimes the right-click menu is missing the ♪.  I haven't been able to pin down when it happens, but it will disappear, then later reappear in the same session.  I hate inconsistent computer behavior.
![2023-08-22 10_20_30-_Dead Man's Gun S01E04 The Imposter srt - Subtitle Edit 3 6 13](https://github.com/SubtitleEdit/subtitleedit/assets/74514948/f0644ea4-b5d8-44b3-bdd5-908330a7b256)

I don't know yet if these two latter issues happen on my other computer, since I have not tried using the program on it for a bit.  It is my media center computer, and I have mostly doing subtitle work on my main computer.

I'm going to stop doing subtitles for a day or two to relieve my frustration.
