### ISSUE TITLE
UI Minor Fix

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#7284]
Missing space
Brazilian portuguese.

![UI](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/ea3d713d-661d-4814-b7ec-2b5154f7656b)

**Comment by niksedk** [comment]
Thx - hopefully better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
