### ISSUE TITLE
Issue with PGS generation - Shadow is always transparent despite alpha set to 255

### ISSUE THREAD

**Issue by nautilus7** [SubtitleEdit/subtitleedit#7292]
Pretty much the title says it all. I am trying to create blu-ray subtitles, but the shadows is always transparent. See attached picture. Is it normal?

![line0004](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/a47816f1-7341-42fd-b245-ea9425e20b98)

**Comment by niksedk** [comment]
Works fine here... set e.g. border width to 4 and shadow to 0:

Checking w color picker, the alpha is 255 (some alpha do add some pixels)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/8554ce29-b06a-40e4-ae12-3d05f849c422)

**Comment by nautilus7** [comment]
Hi, thanks for testing, but I am not talking about border. I am talking about shadow.

Border can indeed be not transparent if set to, but shadow is ALWAYS transparent, regardless the setting.

**Comment by niksedk** [comment]
It's close to 255:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/7f29d4b1-bd2f-4a75-9a35-06a901111ee9)

Alpha 100:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/87b40261-329e-4f26-92d3-93529976cf45)

Alpha 10:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/562706d0-4315-447c-8a47-8edce87faa53)

It seems to work...

**Comment by nautilus7** [comment]
Original from blu-ray on the left, custom made with subtitle edit on the right.

![shadow](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/3609500c-9b5a-48b1-9243-e4fea160f5f1)


You see how the custom one has transparent shadow? I cannot find a setting to recreate the style of the original. 
Custom made with subtitleedit is on first post.
Original from blu-ray for testing is below:
![Image3](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/824406c2-db33-4cde-9d96-0906f0f2f7c8)

**Comment by niksedk** [comment]
That's is probably due to the alpha blending... you can try "simple rendering"
