### ISSUE TITLE
Translating with Google Translate Cloud V2

### ISSUE THREAD

**Issue by Rielaph** [SubtitleEdit/subtitleedit#7293]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/78386551/33822ea4-fae4-4b00-9340-567b3aea9cff)

**Comment by Rielaph** [comment]
Translating using an .ASS file throws that error, using other like .srt dont.

**Comment by niksedk** [comment]
Could you attach the actual subtitle file as a .zip?
Does it crash with the regular translate too?
