### ISSUE TITLE
Audio to Text: Whisper

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#7295]
If you open "Audio to Text (Whisper)" from "Video" menu and then click the
combo box "Chose Language" and close it, a shadow will be rendered behind "Translate to English" checkbox  text (see image below)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/cbb6eb66-d395-4c36-96a1-85e30f4f9b1e)

**Comment by niksedk** [comment]
I think it's just disabled...

**Comment by GrampaWildWilly** [comment]
I've been meaning to mention this but didn't want to open a new thread to do it.  This seems like as appropriate a place as any to do it.

I want to thank those of you who have posted screenshots of the dark theme of SE. It saves me the trouble of looking at it & realizing how horrible it is.

FOR ME.

I want to emphasize that.  It is important to realize that not everybody's eyes work the same.  Color perception differs from person to person.  Maybe your color perception makes you think the dark theme is cool, rad, slick, wonderful in every way.  It would be impossible for me to deal with if I had to look at that for any length of time.  Just as an example of what I'm talking about, for anything that shows black text on a red background, it might as well be invisible ink.  All I see is the red background.  For me, the only workable color scheme involves black text on a white background.  Other colors may intrude as accents.  But the primary color scheme for me must be black on white.

I have encountered situations over the years in which somebody has gone to a lot of trouble to color code certain things.  You might see such screens as containing a dazzling rainbow of colors.  I just see dark letters on a light background.  The colors pass me by.  Color coding is mostly wasted on me.  I discourage it.

I am grateful that the dark theme is NOT the only choice in SE.  I hope you NEVER consider eliminating the original black-on-white theme.  If I ever notice any color combinations that appear in some part of SE that just don't work for my eyes, I will be sure to point it out.  Just remember that simple dark on light, preferably black on white, is what I need.  I daresay I am not alone with this requirement.

**Comment by GrampaWildWilly** [comment]
I notice that you, Nik, have already put an up thumb on my post.  That was fast.  It also gives me comfort that you are sympathetic to the cause & I have nothing to worry about.

**Comment by niksedk** [comment]
He, yes. I've not plans of removing the default light theme :)

I normally use the light theme, but in latest beta I use the dark theme often - it is a little more calm for me, especially in the evening or with not too much light around. Dark theme could still be improved a little, but it way better now than in last version.

**Comment by ivandrofly** [comment]
> I think it's just disabled...

![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/2fb314b2-9c9b-4b88-ba52-b62c94592bd6)

Maybe it's more visible now.

**Comment by ivandrofly** [comment]
> 

This reply was for https://github.com/SubtitleEdit/subtitleedit/issues/7282#issuecomment-1696698877

**Comment by ivandrofly** [comment]
> He, yes. I've not plans of removing the default light theme :)
> 
> I normally use the light theme, but in latest beta I use the dark theme often - it is a little more calm for me, especially in the evening or with not too much light around. Dark theme could still be improved a little, but it way better now than in last version.

This reply referes to https://github.com/SubtitleEdit/subtitleedit/issues/7282#issuecomment-1696698877
