### ISSUE TITLE
Auto adjust timings - duration is too short with "audio to text" Whisper Purfview's

### ISSUE THREAD

**Issue by AlmostHuman34** [SubtitleEdit/subtitleedit#7302]
![too short](https://github.com/SubtitleEdit/subtitleedit/assets/122727543/287c313e-fb07-4bb7-88df-3b67550f8fc8)
Hello, I'm new to subtitleedit, I used models large v1 and large v2, no matter which one I always have my subtitles 0,5-2s too short but if I would move them all by this amount they would start way too early, is there some magic trick to fix that? I use auto timings and post-processing. Manualy it would take me years to fix that since I work with large files 1h+.

**Comment by niksedk** [comment]
Inaccurate timestamps is a known issue for Whisper, sorry.

In SE - Tools - Adjust duration, you can add e.g. 500 ms to duration for all subtitles (where space is available)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/55222248-5201-4f20-a7b8-46bec16889a1)

**Comment by AlmostHuman34** [comment]
> 

Amazing! It worked like a charm, thank you very much!

**Comment by AlmostHuman34** [comment]
Is there also option to  increase duration not only in front but also at start?

**Comment by niksedk** [comment]
> Is there also option to increase duration not only in front but also at start?

Sorry, no

**Comment by Purfview** [comment]
@AlmostHuman34 Look at https://github.com/SubtitleEdit/subtitleedit/issues/6946

Some users reported that timestamps with ffmpeg v6 are worse, try to download ffmpeg v5.
