### ISSUE TITLE
Could not find extracted wave file! This feature requires VLC media player 1.1.x or newer (64-bit).

### ISSUE THREAD

**Issue by zcraber** [SubtitleEdit/subtitleedit#7308]
Latest VLC is already installed. Subtitle Edit version 3.6.13.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/61133303/545e6783-25d8-49ee-92d3-4330e38bd5e6)

**Comment by niksedk** [comment]
FFmpeg is better... go to Options - Settings - Waveform, and click on "Download FFmpeg"

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/00e305f9-b21c-4272-b886-545a216dba41)
