### ISSUE TITLE
convert Srt to EBU STL on Ubuntu via CLI newline is ? instread Š

### ISSUE THREAD

**Issue by PunchaiW** [SubtitleEdit/subtitleedit#7309]
Hello,

I have a problem when convert SRT to EBU STL file 

My goal : SRT -> EBU STL -> SRT 

Here my scenario : I convert SRT to  EBU STL on Ubuntu via CLI newline is ? in the output instread Š

This is SRT -> EBU STL file convert on Windows opened by sublime and it's show encoding is Western (Windows 1252)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/77190490/401df45e-1bb7-489c-b776-aab69006c788)

This is SRT -> EBU STL file convert on Ubuntu opened by sublime and it's show encoding is Western (Windows 1252)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/77190490/08887ba4-91f7-4088-b775-4654bf5ea8f3)
xvfb-run -a mono SubtitleEdit.exe /convert /yourinputpath/subtitle_file.srt EBUSTL /outputfilename:/youroutputpath/subtitle_file.stl 

![image](https://github.com/SubtitleEdit/subtitleedit/assets/77190490/e4b66e6a-3118-4cbd-87b3-d6b87580961b)

How do i slove this?

Thank you!

**Comment by niksedk** [comment]
I guess it needs to be fixed in SE... SE should probably write bytes directly instead of mixing text and raw bytes.
Probably here: https://github.com/SubtitleEdit/subtitleedit/blob/main/src/libse/SubtitleFormats/Ebu.cs#L570

**Comment by niksedk** [comment]
EBU writing is hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Better now?

**Comment by niksedk** [comment]
Thx for testing :)
