### ISSUE TITLE
BDN XML bug ?

### ISSUE THREAD

**Issue by qlwj202** [SubtitleEdit/subtitleedit#7310]
SUP is right .BD XML output Wrong time axis？

**Comment by niksedk** [comment]
Could be... could you provide some more info - perhaps read this: https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by qlwj202** [comment]
Is it normal for BDN and SUP times to be different?
![20230903214126](https://github.com/SubtitleEdit/subtitleedit/assets/75620040/40466deb-3f62-4cb7-b091-ebdb9e6531cc)

**Comment by niksedk** [comment]
What are you doing and where? Exporting and then OCR'ing?

**Comment by niksedk** [comment]
Could you attach the source files?
