### ISSUE TITLE
Can be Help/Check for the newest beta version be added (beside the option Help/Check for updates)?

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7311]
This change is no serious work for Nikolaj, the only question is if he wants to do it. 

We use new official versions of SE just for a day, because a day after that we get some new beta versions, a new, improved SE. Sometimes we have several beta versions a day. And it is very smart to use new beta versions, with a lot of new features. Nikolaj continuously improves this program. 

So, we have the option Help/Check for updates, which is only for the official version, in our case, it is 3.6.13. In the meantime, SE was changed A LOT. Can we have an option **Help/Check for the new beta version** and directly from the program download the NEWEST beta version? 

It would be much easier program to determine if there is a newer beta than the beta we currently use and we to get the choice to download it from SE, not to go to nikse.dk and do it the hard way, step by step, asking ourself if it is the version we use, or there is something newer. This option would make our life easier. 

The program would give the messages (when we click on this new option): "You use the latest beta", or "There is a newer beta version" with the download button as the option. The download can be on our desktop by default, for instance.

**Comment by niksedk** [comment]
Sorry, no easy way of doing this as far as I know.

You can check manually when it's was last updated: https://github.com/SubtitleEdit/subtitleedit/releases/tag/3.6.13
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/abb4b922-864e-4849-92e2-3a2bad1421d2)
