### ISSUE TITLE
The operating experience of the toolbar is unnatural.

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#7320]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/b084e1aa-6854-4241-89ae-d91a580b3214)

When the program window is in a non-foreground state, clicking any toolbar button with the mouse cannot activate its corresponding function. A second click is necessary to bring up the window corresponding to that function. This is entirely inconsistent with the usage habits of Windows and the UI experience from previous versions. It's likely a bug in the new UI.

**Comment by GrampaWildWilly** [comment]
I'm not so sure about that.  Here's something similar.  You can test it with any application, the file manager, Notepad, Word, any application, including of course SE.  Switch tasks from anywhere to any other task.  Click the Alt key once.  This is supposed to activate the menu bar.  But immediately after switching focus to any window, Alt does nothing.  You have to click it a second time.  After that first anomalous double Alt, it takes only a single Alt to activate the menu bar.  But switch tasks again to anything else.  The situation will repeat.  The first time you hit Alt in the window, it does nothing.  Only the second Alt gets the menu bar to activate.  But as long as you stay in that window, it takes only one Alt to activate the menu bar after that.  I suspect something similar is going on with the SE toolbar.  I would not be surprised if Nik comes back & says that behavior you have noted with the SE tool bar is out of his hands.

**Comment by niksedk** [comment]
Hm, I've not changed anything regarding toolbar... and it works exactly the same way in 3.6.13 + latest beta for me...

**Comment by Mishasama** [comment]
> Hm, I've not changed anything regarding toolbar... and it works exactly the same way in 3.6.13 + latest beta for me...

Let me show you... The record is under version 4.0
![2023-09-05_12-01-12](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/e99677e5-bd02-4f70-85c1-04fde7ae3b73)
As you can see, firstly, Notepad is in the foreground, while SE is in the background. When I first clicked the button on the SE toolbar, it only switched SE to the foreground and did not respond to the corresponding function.
Of course, this also occurs on the menu above the SE window.
![2023-09-05_12-15-41](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/9df3dc43-9462-4f80-ab1a-cf0d3005a3c1)
But this situation did not occur on Windows Explore. I only clicked once to display the drop-down menu.
