### ISSUE TITLE
possible bug or something? 

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#7324]
![possible subtitle edit bug](https://github.com/SubtitleEdit/subtitleedit/assets/72777/c8038f4e-85f5-4d50-b668-40e8a8bd660c)

why is it when I click on file in zip archive I can open it normally, then I can edit it, and save it into a zip archive.

- but when I take that file, and drag it to Subtitle Edit window it gives me this error.

it's a minor annoyance, but if it something could be done, would be nice.

**Comment by eddilara** [comment]
pretty sure its cause when you unzip it to open it...it put it in a temp folder...but dragging it doesn't do that

**Comment by diomed** [comment]
ah. i see. then really not SE issue. heh.
