### ISSUE TITLE
Purfview's Faster-Whisper keep asking update

### ISSUE THREAD

**Issue by abc16361** [SubtitleEdit/subtitleedit#7325]
On version 4.0, Purfview's Faster-Whisper keeps asking update everytime doing whisper audio to text. It was tested on Windows 11 pro.
<img width="590" alt="202309041523" src="https://github.com/SubtitleEdit/subtitleedit/assets/101362122/baba6410-a537-4223-ae7e-2fa570fabe7c">

**Comment by niksedk** [comment]
Thx, will be fixed in next update :)
Also, here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip
