### ISSUE TITLE
[4.0] A small flaw in user experience.

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#7327]
## About mpv lib download
![image](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/bb742557-d072-4451-9623-57da878d7884)
When clicking to download the MPV LIB, a window will appear again, requiring the user to click the same button again to start the download. I feel that it's unnecessary. Is it really necessary to add such a step? Moreover, this window will automatically close after the download is complete, making the OK button redundant.

It is recommended to click the download button on the settings interface for the first time and start downloading directly, displaying the download progress and a cancel button. Once the download is complete, replace the cancel button with an OK button to close the window.

If you want to add a download error, just display the progress text in red after the error, and the user only needs to click the cancel button or close the window directly. If the user wants to retry the download, click download again.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/36ebccab-584d-413a-983d-a92f8495c3b9)
Also, when the download is complete, a window will pop up indicating that the download is complete. However, the location of this window is not above the original interface, but rather in the upper-left corner of the screen. As long as the screen size (or resolution) is too large and not noticed, users are likely to think that the program is stuck and cannot be operated.

Later, I tried the download function of FFmpeg again and felt that a design like that would work. It looks much like what I mentioned above, and the user experience is much better.

## About Performances
![2023-09-05_10-01-06](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/1682005f-a2b1-4d1b-973a-bf751a3ef378)
Also, I found that in the settings interface, even if you haven't selected a different category or clicked on the blank space below the category on the left, the settings item interface on the right will "refresh", just like pressing F5 in the Windows Explorer.
I think if the content on the right doesn't need to be changed, there's no need to redraw it, right? I feel like this kind of behavior looks quite strange, although in order to simplify code design, generally no one cares about it.
Perhaps if the computer's performance is powerful enough, this process is difficult for users to detect?
However, generally speaking, modern computers will run at reduced frequencies when the load is not that high to save energy and reduce issues such as heat generation. In this situation, no matter how powerful the hardware is, users still have the opportunity to encounter this visual flaw, right?
Perhaps I would consider adding an IF judgment when the user clicks to determine if they have selected a different page, and then decide whether to reload the content of the target page. I think an IF judgment should be faster and more resource efficient than reloading, and it won't slow down too much when changing pages. It can be said that the advantages outweigh the disadvantages.

Say... do you want to consider upgrading to .NET 7? It is said that the performance of parallel processing has been greatly improved, which should be helpful when dealing with files with a large amount of content. Currently, it is still relatively slow to load a 100KB + SRT subtitle file, and the program interface is not very smooth to operate.

**Comment by niksedk** [comment]
Thx for the input - hopefully improved a little here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

If I upgrade to .NET 7 then Linux users will not be able to run SE...
I've tested upgrading to .NET 6 which was a little slower in the UI - file handling is a bit better probably.
I think SE is pretty fast :)

**Comment by Mishasama** [comment]
> Thx for the input - hopefully improved a little here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

![image](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/d3a49959-d0f5-421c-b2ff-5676739e97af)
👆 mpv, upper-left corner.


And, did you forget about this? #7200 
https://github.com/SubtitleEdit/subtitleedit/commit/5cad1dfd56c20b6a8765dca15e762773ec07d6c0


> If I upgrade to .NET 7 then Linux users will not be able to run SE...

Why? What are you talking about?
```
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh --version latest --runtime aspnetcore
```
https://github.com/dotnet/core/blob/main/linux.md
https://learn.microsoft.com/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website

**Comment by niksedk** [comment]
> mpv, upper-left corner.

What does this mean?

Winforms dot net 6+ is not ported to Linux as far as I know.

**Comment by Mishasama** [comment]
> > mpv, upper-left corner.
> 
> What does this mean?

These error windows will still pop up in the upper-left corner of the screen. Is it randomly?


Also, it looks like you forgot to integrate this change into 4.0.

https://github.com/SubtitleEdit/subtitleedit/issues/7200
https://github.com/SubtitleEdit/subtitleedit/commit/5cad1dfd56c20b6a8765dca15e762773ec07d6c0
After loading a file, all drop-down menus can't be changed by the mouse wheel.
