### ISSUE TITLE
Import shot changes: dat file from Ooona doesn't work

### ISSUE THREAD

**Issue by evayor** [SubtitleEdit/subtitleedit#7334]
Hi, I'm trying to import a dat file with shot changes i downloaded from the client's Ooona platform. However, it's not recognized as a file type, so I opened it in Notepad and saved it as txt. Unfortunately, this didn't work either. How can I handle this?

Here's the [dat file](https://1drv.ms/u/s!AmDWN6Fzquj0hrRq95jAjTOR8Nxzkg?e=puPnJY).

I'm on Windows 10, SE 3.6.13

**Comment by niksedk** [comment]
Hi @evayor,

thx for the file :)

Shot changes should able to import in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

**Comment by evayor** [comment]
Thank you very much, Nikolaj, I tried it an it worked.
However, it installed/started as a new version of SE and all my settings, especially shortcuts, don't work in the beta. I imported profiles, but entering shortcuts again would be too much work. Is there a way around it?

**Comment by niksedk** [comment]
You can copy your Settings.xml file to your beta folder.
