### ISSUE TITLE
4.0.0: "Bridge small gaps" dialog does not remember settings

### ISSUE THREAD

**Issue by bgaesslein** [SubtitleEdit/subtitleedit#7335]
In the latest release, it always sets the gap size to 1 and minimum gap size to 0 every time I open the dialog. This is very inconvenient and actually made me downgrade back to 3.6.13.

**Comment by niksedk** [comment]
Thx for the info :)

Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

**Comment by bgaesslein** [comment]
Cool, I'll check it out later.
