### ISSUE TITLE
Burn-in subtitle is summing the total time of all subtitles in video duration

### ISSUE THREAD

**Issue by Joao-Victor-Moura** [SubtitleEdit/subtitleedit#7339]
I REALLY need help, sorry if this isn't a bug, but I subtitled a video with about 14 minutes, I used the .ass format, when I put the video to generate with burn-in subtitle, the final duration always becomes about 25 minutes, I believe it is summing the duration of all subtitles into the video, since most of the video I have two or more simultaneous subtitles on the screen and the statistics say that the sum of all subtitles alone are 24 minutes long.

Is this a bug? If not, could you tell me how I can keep the original duration of the video when I burn-in the subtitle? For my project I really need to have simultaneous subtitles and keep the original video length. Sorry for any english mistakes.

Original duration that i want to keep 
![imagem_2023-09-07_001948117](https://github.com/SubtitleEdit/subtitleedit/assets/81198608/608dc4ed-d87c-4532-b054-c271da9ee2c4)

Duration after generate burn-in subtitle 
![imagem_2023-09-07_002028373](https://github.com/SubtitleEdit/subtitleedit/assets/81198608/79c4a88e-15c5-41b3-8143-9c68ce27b100)

Statistics 
![imagem_2023-09-07_002106745](https://github.com/SubtitleEdit/subtitleedit/assets/81198608/d4c26a2c-d3c3-4157-97c9-9e6d4d75d800)

**Comment by niksedk** [comment]
I cannot re-create this... works fine here.
You can try to re-download ffmpeg - go to Options - Settings - Waveform - Download ffmpeg

If it's still weird, then what video encode settings do you use?

**Comment by Joao-Victor-Moura** [comment]
I downloaded ffmpeg again and the problem continued. I've also tried going back to a previous version.

I'm using the default encoding settings, but I also tried changing the encode and none of them worked, some gave an error before generating the video and those that did generated continued to increase the length of the video

encoding settings:
![imagem_2023-09-08_152552446](https://github.com/SubtitleEdit/subtitleedit/assets/81198608/e5719604-7f9f-496b-98ed-e8a16b644651)

error:

![imagem_2023-09-08_153626153](https://github.com/SubtitleEdit/subtitleedit/assets/81198608/b9c9d6d5-cd91-42fd-95fe-146392cf988b)

![imagem_2023-09-08_153646428](https://github.com/SubtitleEdit/subtitleedit/assets/81198608/cb3e05d0-598b-4f53-852e-afa1fdd27e90)

![imagem_2023-09-08_153705177](https://github.com/SubtitleEdit/subtitleedit/assets/81198608/0f3de444-eb9b-43d3-a030-4894ad93727d)


I managed to burn-in the subtitles while maintaining the original length of the video using VLC, I took the video and the subtitle that I created in SE and did the process there. But there were some small errors, like the fadeout not happening in two parts and a moment where some subtitles overlapped (in the SE preview these parts with errors were normal). So if possible I would like to generate the video with SE.

I can send the subtitle file, if it's of any use.

**Comment by niksedk** [comment]
Please do email or attach the subtitle file, thx :)

**Comment by Joao-Victor-Moura** [comment]
I'll send it by email, I can't attach because it doesn't support the file type

**Comment by niksedk** [comment]
Thx for the ASSA file... I still cannot re-create this. 
Could you possibly send the video file too?

**Comment by Joao-Victor-Moura** [comment]
I uploaded it to google drive:
.
https://drive.google.com/file/d/1HXmK9VyAt5-nzaNqGE9Hmc55k2-KhmL3/view?usp=drive_link

I took the opportunity to record a video re-creating the process and
uploaded it too:
https://drive.google.com/file/d/1O_wE04ZnfkH9Lfikpui-UCDHa8g7hNwO/view?usp=drive_link

Em sáb., 9 de set. de 2023 às 03:46, Nikolaj Olsson <
***@***.***> escreveu:

**Comment by Joao-Victor-Moura** [comment]
I gave permission to access the link, sorry I didn't know I would need to
give permission, first time sharing link on Google Drive.

Em sáb., 9 de set. de 2023 às 13:36, João Victor de Moura Prudencio <
***@***.***> escreveu:

**Comment by niksedk** [comment]
Thx for the files - I can re-create this with your files.
I will do some testing with different ffmpeg version and parameters.

**Comment by Joao-Victor-Moura** [comment]
Okay. Thank you.

Em seg., 11 de set. de 2023 às 01:46, Nikolaj Olsson <
***@***.***> escreveu:

**Comment by niksedk** [comment]
OK, I've tested with FFmpeg 5.1, 6.0 + latest git... all versions makes the same 25 min video.
I tried burning-in your video with only one simple subtitle line... and it still makes a 25 minutes video.
I've tried with other video files and your assa subtitle file - all works perfectly.

So... I pretty certain your video file is damaged or buggy. 
(If the video file is not buggy or damaged in any way, then FFmpeg could have a bug. Perhaps open an issue there...)

To solve your current issue, you could try using a cut when burning-in in SE or convert your video file to mkv.
