### ISSUE TITLE
Windows install SE 4.0.0 Keyboard shortcuts colors incorrect

### ISSUE THREAD

**Issue by Cyprien-22** [SubtitleEdit/subtitleedit#7342]
Under Options -> Settings ->Shortcuts -> List view and text box, color 1 to color [none] appear to be incorrectly listed. 

![image](https://github.com/SubtitleEdit/subtitleedit/assets/144349105/99db7290-00a6-4141-9cf8-ce110cda1d22)

SE400 zip however appears fine 

![image](https://github.com/SubtitleEdit/subtitleedit/assets/144349105/7af73b1d-7e75-4326-b787-e682e4f9b364)

Sorry if already mentioned, I looked at a few pages here and I couldn't see it. 

EDIT: The SE400 reverts to the same as the Windows installed version after setting a shortcut and trying to use it. Going back into the settings looks the same as the first image I posted.

**Comment by niksedk** [comment]
thx for the color bug info :)
Should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip
