### ISSUE TITLE
Sortable styles

### ISSUE THREAD

**Issue by tormento** [SubtitleEdit/subtitleedit#7345]
Please make the columns of the styles window sortable:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/2351785/56de049d-8762-48cf-9529-90889bd4a266)

Sometimes is really a PITA to attach the proper fonts without forgetting anything! :)

**Comment by niksedk** [comment]
Does sorting styles work OK in this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

**Comment by tormento** [comment]
Works really fine, thank you!

Without opening another issue, please, add a column beside font name with font styles, such as (B)old. (I)talic, etc to know at first glance what "flavor" of the font to attach, as many fonts have different files for every style.
