### ISSUE TITLE
V4.0.0: Subtitle syncing with another subtitle file not (always) work

### ISSUE THREAD

**Issue by MrDummyNL** [SubtitleEdit/subtitleedit#7358]
Today, when i try sync the subtitle with another subtitle, i noticed i can select rows at both sides, but i cannot add sync points.
Even clicking many times and reload subtitles, it refuses to add sync point.

I go downgrade to latest 3.6.13, and see if button still works.

Did you test it with different subtitles, and do the button works or not?

Update: 3.6.13 works, and when i install 4.0.0 again, then it works. I don't know why it refuses earlier.

Update2: trying click on other subtitle, it refuses again. 3.6.13 has also same issue where it just refuses to add sync point.
Please, this drives me to nuts why it refuses. I clicked like i always do, and it works, but next subtitle it just refuses for no reason.

Update 3: now i am able to edit more subtitles. I keep in eye when it refuses. I did before full reset.

**Comment by eddilara** [comment]
maybe clean install SE
