### ISSUE TITLE
Whisper CPP no longer works

### ISSUE THREAD

**Issue by cyberofficial** [SubtitleEdit/subtitleedit#7360]
When using Whisper CPP on version 4.0.0 it crashes the application.

I make a time line selection, i click add text, then i open the dialog option to use whisper to translate. I then choose CPP, use large model. I then click any language, click translate box, then click generate and the application closes.

This works as intended on previous version 3.6.13

**Comment by niksedk** [comment]
Can you see any errors in "whisper_log.txt"?
Works fine here with tiny/small model...

**Comment by cyberofficial** [comment]
> Can you see any errors in "whisper_log.txt"? Works fine here with tiny/small model...

![SubtitleEdit_TGylNXUY7c](https://github.com/SubtitleEdit/subtitleedit/assets/19499442/4b2d6503-8a39-4661-9818-90c5d3bddc74)

![SubtitleEdit_TW4kxHPatU](https://github.com/SubtitleEdit/subtitleedit/assets/19499442/3e31196e-5703-4d73-9fc3-81c6235a417d)



This is the error I get when I use it.

**Comment by niksedk** [comment]
OK, I cannot re-create this... but do check your whisper log!
You could try deleting your "SE whisper folder", and re-download CPP + models...

**Comment by cyberofficial** [comment]
whisper log just shows this, no errors.
[whisper_log.txt](https://github.com/SubtitleEdit/subtitleedit/files/12590289/whisper_log.txt)


i uninstall everything, nuked the cache and app data files, reinstalled, and still the same issue

**Comment by niksedk** [comment]
OK, it looks like SE cannot find your Whisper CPP exe file... where is it located?

**Comment by cyberofficial** [comment]
I deleted the entire directory in app data `C:\Users\cyberofficial\AppData\Roaming\Subtitle Edit` 

and the exe is in `C:\Users\cyberofficial\AppData\Roaming\Subtitle Edit\Whisper\Cpp` when it downloads

**Comment by niksedk** [comment]
OK, somewhat strange... but a whisper cpp check was missing, so this beta might work better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

**Comment by cyberofficial** [comment]
> OK, somewhat strange... but a whisper cpp check was missing, so this beta might work better? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

Yea this works for me

**Comment by niksedk** [comment]
Cool it works now :)

**Comment by cyberofficial** [comment]
Thanks for the help 💯

**Comment by niksedk** [comment]
Thx for testing :)
