### ISSUE TITLE
Auto-Translate breaking accented characters

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#7361]
Subtitle Edit 4.0.0.39

Whenever I've tried to translate from english to portuguese, ALL the accented characters are turning like these.
Is it my fault? There are settings I've missed? What I have to do to get it right?
This never happened before.

![34](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/bee78076-fe76-4f47-8eaf-772927221b23)

**Comment by niksedk** [comment]
Works fine here...

**Comment by ivandrofly** [comment]
> Subtitle Edit 4.0.0.39
> 
> Whenever I've tried to translate from english to portuguese, ALL the accented characters are turning like these.
> Is it my fault? There are settings I've missed? What I have to do to get it right?
> This never happened before.
> 
> ![34](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/bee78076-fe76-4f47-8eaf-772927221b23)
> 

Looks like an encoding issue... will check it out.

**Comment by Andrebavila** [comment]
> Works fine here...

Wow...
This never happened before here.
I've tested some subtitltes, but this issue persists

**Comment by Andrebavila** [comment]
> > Subtitle Edit 4.0.0.39
> > Whenever I've tried to translate from english to portuguese, ALL the accented characters are turning like these.
> > Is it my fault? There are settings I've missed? What I have to do to get it right?
> > This never happened before.
> > ![34](https://user-images.githubusercontent.com/64425752/266859730-bee78076-fe76-4f47-8eaf-772927221b23.jpg)
> 
> Looks like an encoding issue... will check it out.

Thank you for the help.
I have no ideia why this problem.
I've tested some subtitles, but the issue persists

**Comment by ivandrofly** [comment]
Can you share the sub file here?

**Comment by Andrebavila** [comment]
> Can you share the sub file here?

[Original.zip](https://github.com/SubtitleEdit/subtitleedit/files/12570943/Original.zip)

**Comment by ivandrofly** [comment]
It working fine here!
![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/45074d23-fb41-4711-9c2f-a5b04a072a8b)


One remark maybe you sent me the file that wasn't processed.
If you try to compare the line number from the file you sent me and the screenshot you shared, they don't seem to match
by line number and also text! 

Are you able to also produced the same output using the file you send me?

Did you run another action any other than translate against the subtitle e.g: Fix Common Errors?

**Comment by Andrebavila** [comment]
I just translated the sub and that's it. I didn't run any other action.
I translated it again now and....
![797](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/1099affd-b4f3-4e19-a2a5-f5a6154a4028)

**Comment by ivandrofly** [comment]
From Settings\General, 
e.g: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/924f3a3f-ed03-45ac-b319-e753b605bd99)

What do you have as default encoding?

I'm suspecting that after the request is sent to google 
and the response is received SE is trying to use a different encoding other then UTF-8
to decode.

Another theory is the issue might be coming from Control-Panel\Region
![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/e33fa0b0-c6a8-4d45-bff9-c3a6355cafac)
Can you check what options you have selected there?

**Comment by ivandrofly** [comment]
One more thing, can you save the buggy translated file and shared it here also?

**Comment by ivandrofly** [comment]
> I'm suspecting that after the request is sent to google
> and the response is received SE is trying to use a different encoding other then UTF-8
> to decode.

Well... I was able to re-create it by choosing "File\Import subtitle with manually chosen encoding"
and choosing encoding `1252 Western European (Windows)` encoding.

It produces similar buggy text as the ones in your screenshot
![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/16119db9-b811-43f5-944f-7351e1ebbd6c)

**Comment by Andrebavila** [comment]
> From Settings\General, e.g: ![image](https://user-images.githubusercontent.com/6579818/266878561-924f3a3f-ed03-45ac-b319-e753b605bd99.png)
> 
> What do you have as default encoding?
> 
> I'm suspecting that after the request is sent to google and the response is received SE is trying to use a different encoding other then UTF-8 to decode.
> 
> Another theory is the issue might be coming from Control-Panel\Region ![image](https://user-images.githubusercontent.com/6579818/266878723-e33fa0b0-c6a8-4d45-bff9-c3a6355cafac.png) Can you check what options you have selected there?



I'm from Brazil.
I've changed everything you suggested.
Sadly, the issue's still here.
I'm using Windows 7 and the option "Beta: Use Unicode UTF-8 for worldwide language support" doesn't exist.

[Buggy Sub.zip](https://github.com/SubtitleEdit/subtitleedit/files/12571076/Buggy.Sub.zip)

**Comment by Andrebavila** [comment]
> > I'm suspecting that after the request is sent to google
> > and the response is received SE is trying to use a different encoding other then UTF-8
> > to decode.
> 
> Well... I was able to re-create it by choosing "File\Import subtitle with manually chosen encoding" and choosing encoding `1252 Western European (Windows)` encoding.
> 
> It produces similar buggy text as the ones in your screenshot ![image](https://user-images.githubusercontent.com/6579818/266879468-16119db9-b811-43f5-944f-7351e1ebbd6c.png)


I have used "1252 Western European (Windows)" all time.
I've imported the sub, like you said, and I didn't see any bug.

**Comment by ivandrofly** [comment]
> I have used "1252 Western European (Windows)" all time.

Set UTF-8 instead of *1252 Western European (Windows)*

**Comment by Andrebavila** [comment]
> > I have used "1252 Western European (Windows)" all time.
> 
> Set UTF-8 instead of _1252 Western European (Windows)_ From SE\Settings
> 
> Make sure you re-do the translation from the original subtitle (English). Because once the file is messed up it cannot be fixed by just changing encoding

Sadly, it didn't work.
I've tried when you told me sooner, but still not working.

**Comment by ivandrofly** [comment]
Maybe his issue can be fixed with https://stackoverflow.com/a/12237870/2766753
I've done a quick peek the source code and there is chance that HttpClient couldn't find the proper encoding to read the string and fall back to it's system encoding (which is 1252) but the bytes received was encoded with utf-8

Method of interest LibSE\Http\HttpClientDownloader.cs:33

**Comment by Andrebavila** [comment]
> @niksedk Maybe his issue can be fixed with https://stackoverflow.com/a/12237870/2766753 (instead of Unicode we use utf8) I've done a quick peek the source code and there is chance that HttpClient couldn't find the proper encoding to read the string and fall back to its system encoding (which is 1252) but the bytes received was encoded with utf-8
> 
> Method of interest LibSE\Http\HttpClientDownloader.cs:33


Thank you very much, @ivandrofly 
I don't know how to work with theses codes.
I'm hopeless with that.

**Comment by ivandrofly** [comment]
No worries, let see what @niksedk has to say about it with the infos obtained ;)

**Comment by Andrebavila** [comment]
> No worries, let see what @niksedk has to say about it with the infos obtained ;)

Thank you very much for all your troubles, @ivandrofly!!

**Comment by Andrebavila** [comment]
I would like to say that the Auto-Translate works PERFECTLY on Subtitle Edit 3.6.12.0
The versions after that, it is broken here.

**Comment by niksedk** [comment]
@Andrebavila: How is latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip
Implemented the solution from @ivandrofly :)

**Comment by Andrebavila** [comment]
> @Andrebavila: How is latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip Implemented the solution from @ivandrofly :)

Thank you very much, @niksedk!
You've solved this damn problem! It is working perfectly now!
You know how to do the magic!
Thank you very much!

**Comment by niksedk** [comment]
Thank you guys - for finding the problem and solution :)
