### ISSUE TITLE
Save as BDN/XML utf-8 encoding

### ISSUE THREAD

**Issue by nautilus7** [SubtitleEdit/subtitleedit#7362]
Hi, when saving a PGS/SUP subtitle as BDN/XML, the xml is always encoded as utf-8 with BOM.

Under options I have set preferred encoding when saving subtitles to be utf-8 without BOM, but this does not work for BDN/XML format.

In addition, I am not sure whether using utf-8 with BOM for xml is even allowed. For example, the SUPer program which uses the python's xml parser cannot work with xml files if they contain a BOM. Putting a BOM seems like it's [not recommended in when using utf-8](https://stackoverflow.com/a/2223926/1370918) anyway.

Regards.

**Comment by nautilus7** [comment]
No comment at all?

**Comment by niksedk** [comment]
OK, maybe not the worst idea,... 

BOM is 100% allowed for XML and other text files. IMO all files should be in UTF-8 and then we would not need BOM, but it's not like that (especially on Windows), and programs than cannot handle BOM are just poorly made.

**Comment by nautilus7** [comment]
I have already reported to the SUPer author, because I was not sure who's fault it is.

But should the setting below also work for bdn/xml output? 
![Screenshot 2023-09-10 234732](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/e6d6ad84-6d07-4261-b83e-a7c0578b7aa3)

**Comment by niksedk** [comment]
Should hopefully work in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

**Comment by nautilus7** [comment]
Thanks, I'll test tonight.
