### ISSUE TITLE
Bridge small Gaps between Subtitles dialog forgets settings

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#7364]
Bridge small Gaps between Subtitles dialog forgets settings

After 4.0.0 update, the dialog forgets the set settings (returns to default after opening again).

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/24cd2d02-1662-4da4-af39-06e4ada902d3)

After pressing OK and reopening
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/8953c721-b991-4f41-bdb6-a6fd3885fe0f)

Remembering settings was better, because I used to have macro, that automatically presses OK, but now it would be more complicated to do.

**Comment by niksedk** [comment]
Should hopefully be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

**Comment by rRobis** [comment]
Thanks
