### ISSUE TITLE
Crash when exporting ASS-Subs to PGS / Bluray sup

### ISSUE THREAD

**Issue by Pheromir** [SubtitleEdit/subtitleedit#7365]
When opening any .ass subtitles and trying to export them via `File -> Export -> Bluray-sup...` SE hangs for some seconds and then crashes.

Only happens in Version 4.0.0, SE Version 3.6.13 works fine.
OS is Windows 11 22H2 (Build 22621.2134).

An example ass file I tried to export is attached (packed as zip because GitHub won't let me upload .ass files).
[Test.zip](https://github.com/SubtitleEdit/subtitleedit/files/12573825/Test.zip)

**Comment by niksedk** [comment]
Hm, works fine here... could be some font issue on your machine.

**Comment by vinnpinn** [comment]
Can confirm the same issue under Windows 11 with SE 4.0.0.
Export Screen shows up for a second before it crashes
![image](https://github.com/SubtitleEdit/subtitleedit/assets/26883610/da3fbe84-71d4-491d-8cbf-fec4fbcf99c9)

**Comment by Pheromir** [comment]
Font is installed, Arial also crashes. Shouldn't SE 3.6.13 crash too if the font was the problem?

**Comment by niksedk** [comment]
> Font is installed, Arial also crashes. Shouldn't SE 3.6.13 crash too if the font was the problem?

Yeah, I guess so.
I can re-create the error with SE 4.0.0, but not with latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip
Does latest beta work for you too?

**Comment by Pheromir** [comment]
Yes, the beta works.

**Comment by niksedk** [comment]
Thx for verifying :)
