### ISSUE TITLE
Saving: Wrong message displayed

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#7368]
Wrong message displayed when saving a unicode-based subtitle with a different
encoding

![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/361f270a-286d-41b3-8e3d-96c0788fa3df)

The chosen encoding is not ANSI and it will always says ANSI

**Comment by niksedk** [comment]
The chosen encoding is ANSI...
https://en.wikipedia.org/wiki/Windows_code_page
