### ISSUE TITLE
Find / Replace not auto picking selected word(s)

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#7369]
Before when we selected a word(s) and pressed Ctrl+F or Ctrl+H, the selected word(s) was automatically written in Find bar, now it does not. The old system was more efficient.

Thank you.

**Comment by ivandrofly** [comment]
This issue seems to be fixed in the latest Beta
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

**Comment by uckthis** [comment]
> This issue seems to be fixed in the latest Beta https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

So it has.

Thank you.
