### ISSUE TITLE
i dont think its issue but its about my setting .  when i open video file with media player then the video in my  subtitle edit

### ISSUE THREAD

**Issue by maloadjav** [SubtitleEdit/subtitleedit#7372]
have change into the video file that i want to play 

and the media player classic do nothing  .

its bug me because every time i  want to stop  subing and i want to  watch the movies 

i use  media player for opening the video file but   seem like the video file in my  subtitle have change  into this video file .

now  i cant  open  both  subtitle edit and media player classis  at the same time at all  because there is something  really  baddd will hapen 

any one have idea ???

okay . i have been reset  setting and everything back to  normal now ...its bad solotion  ^--^ 

but if you have any idea then you can share .for the  future

**Comment by niksedk** [comment]
I recommend using mpv with SE
