### ISSUE TITLE
Live Spell Check is not working in Version 4.0.0

### ISSUE THREAD

**Issue by AE-Ismail** [SubtitleEdit/subtitleedit#7373]
Hello,

I recently updated to version 4.0.0 without resetting my settings or dictionaries,
but the syntax coloring live spell check doesn't seem to be working anymore.

![2023-09-12_18-18-06](https://github.com/SubtitleEdit/subtitleedit/assets/118636398/624229cb-d515-424c-a64f-b86da456a9d7)

Can you please check and see if it's a single issue with my device or a version issue?

Thank you

**Comment by niksedk** [comment]
Thx for the info :)
Live spell check should now work again in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip
