### ISSUE TITLE
When will the new features be part of the help? 

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7384]
For instance, you can't find Tools/beautify time codes. I have no clue what this options do and how to work with it, how to set the parameters in it.

**Comment by niksedk** [comment]
When someone makes the help ;)

OK, I can try to add info for "Beautify time codes". 
What other new features would be nice to have help for?

**Comment by niksedk** [comment]
Triggering help (default F1) in "Beautify time code" windows will now open: https://www.nikse.dk/subtitleedit/help#beautify_time_codes 
(Press Ctrl+F5 if help is no there)
