### ISSUE TITLE
One Issue with Translation Mode

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7386]
Some operations like this can't be added to only one side by selecting line(s) in the List view:
![GIF 9-15-2023 1-26-45 AM](https://github.com/SubtitleEdit/subtitleedit/assets/494788/e3f5f286-f184-4441-a71b-3437a069b645)

I mean, for one or two lines, it's okay to do that individually via textbox, but for many lines... 😂

**Comment by niksedk** [comment]
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.0/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Maybe also for the  ♪  symbols, please?

**Comment by niksedk** [comment]
> @niksedk Maybe also for the ♪ symbols, please?

OK, how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Great, thanks for that!
