### ISSUE TITLE
its about how to again..  i always open 2 subtitle ( for some reason )at the same time ...it have different shortcut and setting

### ISSUE THREAD

**Issue by maloadjav** [SubtitleEdit/subtitleedit#7388]
and i noticed that  when  i open subtitle next time  .... my setting  was change because   it will  save as " other  subtitle setting) 

for example 

1  i have  subtitle  number  1  that  i  have the shortcut for    actor  ( 1,2,3  )  and other  shortcut 
2  i have  subtitle  number  2 that  i dont  have any shortcut  because  its new subtitle  

and then i close all my subtitle  .... when i  open the subtitle 1 again then  all  my setting  was  change to ( subtitle 2 setting  )  
that mean all  my setting was gone 

...
so with the problem like this ,, what can i do  ??
anyway for imported  all setting from other subtitle ??

or  anyway for making  all  subtitle have the same shortcut and setting  all the time  ???

**Comment by niksedk** [comment]
Could explain a bit more? Screenshots could help...

**Comment by maloadjav** [comment]
![1](https://github.com/SubtitleEdit/subtitleedit/assets/85825392/2dee87f3-7edf-45e6-8934-1f679fa7b94f)
![2](https://github.com/SubtitleEdit/subtitleedit/assets/85825392/b5f4b807-b774-4672-9bb0-fb0dbd482edb)
![3](https://github.com/SubtitleEdit/subtitleedit/assets/85825392/03a29d3a-3985-4787-a29c-18446427e9ea)
