### ISSUE TITLE
British English / American English

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#7393]
I do not understand exactly how "fix common errors" works regarding British English and American English.
Sometimes it suggests to replace British to American and on the next line it suggests to replace American to British.

"Fix common errors" will then not become empty.
It would be nice if the user can **_then_** explicitly select a certain flavour/flavor

I prefer European movies to have British subtitles and only American (continent) movies to have American English subtitles.

**Comment by eddilara** [comment]
is there REALLY that big a difference....their both english

**Comment by fraternl** [comment]
There's already support for it. 
I'm merely discussing an anomaly.

If you're not using or having an interest for some feature, this is not the place to discuss it.
Try your family!

**Comment by eddilara** [comment]
little stuck up brit aren't ya

**Comment by fraternl** [comment]
"their both english"
I'm not British, yet I know this is not English...
