### ISSUE TITLE
Whisper: When using translate to English also keep original language

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#7395]
Whisper can take a long time and when I have a French movie and like to have both the French and English subtitle, I will need to run it 2 times.

I have no idea if it's feasible as Whisper is a foreign project, but getting both in one run would be nice from a user point of view.

I fully understand if that's not possible.

Even if it's not possible, I would like to know if the translation is a seperate process done after the STT.
I also would like to know if such a translation is superiour to a Google translate afterwards (I haven't used it enough to know).

Sometimes Google translate can make rubbish translations as it is not context sensitive or not context sensitive enough.

It seems if Whisper IS context sensitive, so I wonder if its translation to English is also context sensitive.

**Comment by niksedk** [comment]
Sorry, Whisper does not have this feature as far as I know.

I don't know the inner workings of Whisper... try looking https://github.com/openai/whisper

**Comment by darnn** [comment]
Whisper does the translation during the TTS phase, not after (per OpenAI's GitHub), so yes, if you wanted both the transcription and the translation, you'd have to run it twice.
Regardless, I wouldn't recommend using Whisper for translation. It sometimes produces things that are quite legible, but other times it can be much worse than Google Translate. The best option I know of at the moment is using ChatGPT:
https://github.com/SubtitleEdit/subtitleedit/issues/6346#issuecomment-1466534741
The free version does a decent job, but if you're doing large volumes of text, and often have somewhat more complex sentences, I'd recommend paying the $20 a month for access to GPT-4.
