### ISSUE TITLE
Subtitle crash... .NET issue?

### ISSUE THREAD

**Issue by Charvelx04** [SubtitleEdit/subtitleedit#7402]
From version 4.0.1 (Windows 11 Pro x64 Event Viewer)

Faulting application name: SubtitleEdit.exe, version: 4.0.1.0, time stamp: 0x65054b8e
Faulting module name: MessageBus.dll_unloaded, version: 1.22.2758.1620, time stamp: 0x5dc56514
Exception code: 0xc0000005
Fault offset: 0x00000000003afd30
Faulting process id: 0x0x137C
Faulting application start time: 0x0x1D9E8EA0481E24A
Faulting application path: C:\Program Files\Subtitle Edit\SubtitleEdit.exe
Faulting module path: MessageBus.dll
Report Id: 760adbd0-bd88-4253-9b36-4b2e303130fd
Faulting package full name: 
Faulting package-relative application ID: 

Application: SubtitleEdit.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFB36F3FD30

Faulting application name: SubtitleEdit.exe, version: 4.0.1.0, time stamp: 0x65054b8e
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2338, time stamp: 0xc0c1b229
Exception code: 0xe06d7363
Fault offset: 0x0000000000064ffc
Faulting process id: 0x0x137C
Faulting application start time: 0x0x1D9E8EA0481E24A
Faulting application path: C:\Program Files\Subtitle Edit\SubtitleEdit.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e6d0c47d-df47-46f1-86c1-ca8b61246f71
Faulting package full name: 
Faulting package-relative application ID: 

Faulting application name: SubtitleEdit.exe, version: 4.0.1.0, time stamp: 0x65054b8e
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2338, time stamp: 0xc0c1b229
Exception code: 0xe06d7363
Fault offset: 0x0000000000064ffc
Faulting process id: 0x0x137C
Faulting application start time: 0x0x1D9E8EA0481E24A
Faulting application path: C:\Program Files\Subtitle Edit\SubtitleEdit.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b834f209-2f45-426d-9a83-7eff66fa8968
Faulting package full name: 
Faulting package-relative application ID: 

This happened when opening a sub (UTF8) after immediately closing it. I went to add some more edits I forgot, the app opened no issue.. .but as soon as I tried changing anything, the app froze... then closed.

**Comment by niksedk** [comment]
OK, I cannot re-create this. How did you open the subtitle? Mouse drag to list view? Shortcut?

**Comment by Charvelx04** [comment]
There are usually two ways I open them... if I'm doing a single from the desktop, I'll drag and drop it. In this case, I am working on a season of subs, and using the Open dialog box. 

What happened here is, when I was "done" editing, I closed it... then realized I had skipped doing the spell check, and reopened the file using the dialog box (folder icon)... not the File/Reopen option. 

I started the spell check, and when I ran into my first change..., it just stopped responding. I could click on things, but nothing opened, closed.. and then the app just faded out. The window didn't turn white like other apps do when they stop responding, it just closed. I seen at least five different entries in the Event Viewer... but with as many changes Microsoft is doing with Windows 11, I really couldn't tell you if it was the app, or the OS that coughed up a hairball.

**Comment by pakirus** [comment]
I'm having the same problem. Now I've reinstalled Windows and I'm still having problems.
It has been since the Windows update.

i9 -13900k MB ROG STRIX Z790-A GAMING WIFI D4 Ram 32 GB

**Comment by niksedk** [comment]
I will need steps to re-create the issue... also, screenshots and logs are nice.

**Comment by ScriptTiger** [comment]
@Charvelx04, @pakirus,
Did you ever find a solution to this?

**Comment by Charvelx04** [comment]
> [@Charvelx04](https://github.com/Charvelx04), [@pakirus](https://github.com/pakirus), Did you ever find a solution to this?

That was on version 4.0.3... we're now up to 4.0.11.

If you are having .Net issues... go into your Programs and Features... select any and all (one by one) .Net installs, click to highlight.. then click on Repair when it shows up above the lists. This will re-install the framework by using the latest version. 

Also... in your Windows Update options, make sure you select "all Microsoft products" that way MS will update your framework and support files automatically.
