### ISSUE TITLE
What is this EMPTY SPACE on the left side of the waveform (spectrogram) in version 4.0.1??

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7403]
It is in beta version 18 (the latest). Left of the waveform we have 3 tabs: Translate, Create, Adjust. Only when we click Translate, the waveform shifts to the right (this is the desired behavior because there are some buttons to perform some translation tasks), but when we use the Create or Adjust tabs, there shouldn't be any shifting. 

Program (now) shifts the waveform to the right in all circumstances and leaves empty space (create and adjust tabs). This is a bug. 

![Screenshot_2](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/334107e9-a2de-4468-8165-e9512e38664e)

**Comment by rRobis** [comment]
It's already fixed in latest beta

**Comment by niksedk** [comment]
The new layout feature should be relative stable now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
