### ISSUE TITLE
Bold text, check box is empty

### ISSUE THREAD

**Issue by Charvelx04** [SubtitleEdit/subtitleedit#7404]
Even though the text boxes in Settings are not checked, text boxes in all three sections, lower left and the primary text box... are bold.

You have to check the box, click OK... bring it back, uncheck box, click OK. However, it doesn't matter as the bold returns once SE is closed.

![Untitled](https://github.com/SubtitleEdit/subtitleedit/assets/35577096/d985a507-d337-45eb-91e9-79699fceacd7)

**Comment by Jack1789** [comment]
I just noticed the same issue on latest v4.x. Font's size from the text box
isn't remembered and will always get "bold" after a restart.

**Comment by niksedk** [comment]
thx - should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by Charvelx04** [comment]
Sounds good.. I'll get that beta up and running.

Thank you.
