### ISSUE TITLE
Value scroller inconsistency

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#7405]
If we press arrow UP = adds to the value (down - decreases)
If we SCROLL UP = decreases the value .

In my opinion, it should be same (scroll UP and arrow UP = increase) and down = decrease 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/65406c38-595f-4267-941b-91c2fbb9ec7e)

**Comment by niksedk** [comment]
So, scroll wheel should be inverted, right?

**Comment by rRobis** [comment]
yes

**Comment by niksedk** [comment]
Thx :)
Hopefully better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
