### ISSUE TITLE
Subtitle Edit error report

### ISSUE THREAD

**Issue by woodfold** [SubtitleEdit/subtitleedit#7416]
I was editing and got this message, captured from my screen. 

![Subtitle Edit error](https://github.com/SubtitleEdit/subtitleedit/assets/145411197/4df6df4f-6fb1-4527-8172-5cc20626496f)

I chose ignore and completed my editing with no ill effects.
I'll check back tomorrow in case you need more information.

**Comment by niksedk** [comment]
Could you provide a way to re-create this?

**Comment by niksedk** [comment]
OK, do let me know if you ever find a way to re-create this.
