### ISSUE TITLE
[Suggestion] Automatically apply values when changing ASSA styles (could work for other dialogues too)

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#7423]
It would be nice, if the changes would apply automatically on changing the values. 
That way it would be possible to quickly fine-tune the values, without clicking apply each time, and see the changes in the video player.

Maybe this principle can be applied in other places too (like settings for example).

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/23240384-c5b1-4161-8eb2-7f21b16e8135)

**Comment by LeonCheung** [comment]
That's why there's the Preview there. 😂 I don't think auto-apply to any value change is a good idea because it may lead to mis-change that cannot be undone conveniently. It's too risky...

But I do admit that usually we have to hit Apply several times before having an expected setup. Perhaps optionally using a screenshot as the preview BG is a better idea, like **Basic Preview** mode vs. **WYSIWYG** mode.

**Comment by rRobis** [comment]
I didn't think of this, but then maybe it would be possible to make the preview actually show the video player instead. Or make a switchable option between this preview, and "real preview"

**Comment by rRobis** [comment]
Actually, I noticed, that in preview window, you also must press apply, to see the changes in the preview (although, at this point the preview is not very useful, because it doesn't show the actual video as preview)

**Comment by LeonCheung** [comment]
TBH, the size for the style preview window is not really nice for real-time preview especially for smaller font size and vertical videos (although you can tweak the UI layout), A simple solution could be something like this:

![piv](https://github.com/SubtitleEdit/subtitleedit/assets/494788/09c81a46-9471-4c45-a023-6f1c38954c87)

Changes only applied after clicking OK. Hopfully everything is safe and everyone is happy. Just allow to remember the toggle for those who want to enable that by default. :)

**Comment by rRobis** [comment]
Alternatively, could put the preview in new column, for it to be bigger (optionally?)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/d2bbe8e3-846f-4d91-9c18-4b5071d29305)
