### ISSUE TITLE
can u please try to fix this 

### ISSUE THREAD

**Issue by TheFmC** [SubtitleEdit/subtitleedit#7424]
i tried to export subtitle as blu-ray sup 
set the align option to Center, right justify
and it show like this https://ibb.co/DDswkmz
but if i set it in Center it works fine

**Comment by niksedk** [comment]
![subedit-sup](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/9f367051-56f2-4eaa-a58b-55ccb6d3fe23)

**Comment by niksedk** [comment]
So... SE cuts off some text or what?
Could you attach the subtitle? (Github supports .zip files)

**Comment by niksedk** [comment]
Hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Thx for testing :)
