### ISSUE TITLE
Purfview-Whisper-Faster, will  generate  dump files

### ISSUE THREAD

**Issue by wazhong** [SubtitleEdit/subtitleedit#7425]
When using the Purfview-Whisper-Faster in SubtileEdit, after successfully getting the result, it will generate dump files in the "C:\Users\'username'\AppData\Local\CrashDumps\whisper-faster.exe.83896.dmp". 
If you run whisper-faster.exe in Powershell, the problem also exists, but if you run whisper-faster.exe in CMD, no dump files.

**Comment by Purfview** [comment]
https://github.com/Purfview/whisper-standalone-win/issues

**Comment by wazhong** [comment]
The *.dmp files that are generated only when using the Purfview Whisper Faster in SubtileEdit, only for some files, are kind of weird.
