### ISSUE TITLE
Keyboard Shortcuts do no work as expected

### ISSUE THREAD

**Issue by justinhow** [SubtitleEdit/subtitleedit#7427]
I have a keyboard macro routine that basically automated the "Fix Commom issues" process.
I noticed this got broken with Subtitle Edit version 4.0.0 (and still is on 4.0.1).
I have traced the issue and to reproduce (all using keyboard shortcuts).
1. Edit some Subtitles in Subtitle Edit (using 4.0.1 currently).
3. Press **CTRIL-SHFT-F** to bring up **Fix Common Issues** dialogue (dialogue "**step 1 of 2 - choose which errors to fix**")
4. Press **ALT-N** to move to next dialogue window  (dialogue "**step 2 of 2 Verify fixes**")
5. Pressing **ALT-P** should then "**Apply Fixes**" but actually remains on "**Step 2 of 2**" and seems to change the working language (which is correctly greyed out on this dialogue - changes it to "Papiamento" in my case)

FYI I am using the portable version of Subtitle Edit 4.0.1
Thanks, Justin

**Comment by niksedk** [comment]
Hm, that works fine here... I need to press **Alt+O** last to close the window.

Note you can also start in `Fix common errors` step 2 via this setting:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/2f1a6d57-82b9-40c4-86bd-4043a4ca1100)
(practical if you always use the same rules)

**Comment by justinhow** [comment]
Sorry for delay - did not get notified for some reason.
So it appears to behave differently here from you.
However with the "_Skip step one..._" option checked the ALT-P then behaves as expected. So this is a great workaround - thanks!
I am indeed using English.
So I have just edited my keyboird macro to remove the ALT-N and it now works again.
