### ISSUE TITLE
Shortcut keys for Color

### ISSUE THREAD

**Issue by Dr-Nilusha** [SubtitleEdit/subtitleedit#7428]
It is better if we can change the color of text by shortcut key. Now we can only assign shortcut for White color, not for custom colors. This was available in previous 3.x.x versions.

**Comment by niksedk** [comment]
It's still here: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/168771ed-befd-4809-af8b-fb6e428a077a)


Note you might need to do a "Restore default settings" in Options - Settings, as SE 4.0.0 has a bug where colors where messed up.

Also, you can change the colors in Settings.xml:
```` xml
    <Color1>#ffff00ff</Color1>
    <Color2>#ff0000ff</Color2>
    <Color3>#00ff00ff</Color3>
    <Color4>#00ffffff</Color4>
    <Color5>#000000ff</Color5>
    <Color6>#ffffffff</Color6>
    <Color7>#ffa500ff</Color7>
    <Color8>#ffc0cbff</Color8>
````
