### ISSUE TITLE
Multiple replace user interface

### ISSUE THREAD

**Issue by Neverwrotealineofcode** [SubtitleEdit/subtitleedit#7431]
Hello! Sorry if that's not the good place to post (not only am I french, but that's also my first time on github. I tried to "pull a new feature" but I was lost when choosing "compare between main, 3.5X etc).

I often use the multiple replace tool to censor words in subtitles. And it appears that we cannot simply sort words from a list in alphabetical order. That would help when searching for a word, to know if I already have it in my list or if I need to update it.

Also, having the ability to export it in text/csv would be helpful, and not only in ".template".

Anyways, subtitle edit is great!
Thank you.

**Comment by eddilara** [comment]
why not just replace the words with blanks with find and replace
