### ISSUE TITLE
Suggestion for the "Break/split long lines" dialog box

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#7432]
The dialog box of the tool "Break/split long lines" contains two tables. When changing the height of this dialog box, only the height of the bottom table changes. The height of the top table always stays the same. 

**Suggestion:** Make it possible to change the height of the top table of the "Break/split long lines" dialog box, by dragging with the mouse pointer (up/down) between the two tables.

The reason for this option to change the height of the top table, is this use case:

I use "Break/split long lines" to split long lines. However, the resulting split position of this automatic split, is often unsatisfactory. Therefore, such automatic splits often have to be improved manually. To do this, I open two copies of SE side by side on the screen, with the same "srt" file and video. In both copies, I open the "Break/split long lines" dialog box. In one of those copies, I perform the automatic splitting of long lines. I then check (and correct if necessary) all the automatic splits performed, one by one, from top to bottom of the subtitle list. I will only check the subtitles that have been split. To know which subtitles to check, I look at the top table of the "Break/Split Long Lines" dialog box in the other copy of SE. With this, it is convenient to increase the height of this top table (and decrease the height of the bottom table at the same time), as the bottom table is then not needed.

**Comment by niksedk** [comment]
OK, hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
?

**Comment by oep42** [comment]
This has been fixed. Thank you.
