### ISSUE TITLE
merge short lines followed by a dialog does not place the first dash correctly

### ISSUE THREAD

**Issue by taxen** [SubtitleEdit/subtitleedit#7434]
I have updated to 4.0.1.
This is kind of reopening of #3527, but the following subscript

<pre>1
00:00:15,605 --> 00:00:17,482
When I come back,

2
00:00:17,482 --> 00:00:19,192
- he says...
- Fuck.
</pre>

when processed by merge short lines, is changed to

<pre>1
00:00:15,605 --> 00:00:19,192
When I come back, - he says...
- Fuck.
</pre>

where my desired outcome is

<pre>1
00:00:15,605 --> 00:00:19,192
- When I come back, he says...
- Fuck.
</pre>

**Comment by niksedk** [comment]
I've tried to improve merge dialogs - how is this:https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip ?

**Comment by taxen** [comment]
I am sorry for my late response. I just tried the beta version. It worked pretty well! Thank you!
