### ISSUE TITLE
some lines from ttml subtitles are ignored, without any warning

### ISSUE THREAD

**Issue by ms2048** [SubtitleEdit/subtitleedit#7439]
In Subtitle Edit 4.0.1, some lines from TTML format are just skipped.

Real-life excerpt:
[example.zip](https://github.com/SubtitleEdit/subtitleedit/files/12707680/example.zip)

There, the middle line of the three does not show up.

**Comment by niksedk** [comment]
Thx for the info + file :)
I've never seen this before in ttml.

Fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
