### ISSUE TITLE
Context Based Auto-Translation Tool

### ISSUE THREAD

**Issue by Cankalay** [SubtitleEdit/subtitleedit#7444]
Hey people, today I’ve seen on twitter that a software developer named Yiğit Konur developed an open source tool for “boostsing translation quality by using the context of the surrounding sentences” and I was wondering if implementation was possible?

Here’s the link to the repository: https://github.com/yigitkonur/context-aware-srt-translation-gpt

**Comment by niksedk** [comment]
SE already sends bulk of text of the translation services - not just the current line.

Also, this seems a little shady...

**Comment by darnn** [comment]
It requires an OpenAI or DeepL API key anyway, so it's not like just sticking it into SE would make a difference for people who don't have them.
