### ISSUE TITLE
Missing position with dfxp files

### ISSUE THREAD

**Issue by Kloud29** [SubtitleEdit/subtitleedit#7445]
Hello,

I have several dfxp subtitle files that I want to convert in .srt or .vtt but Subtitle Edit doesn't seem to understand this kind of positions, all lines are at the bottom of the screen.

Subtitle 0 to 15 are at the bottom center, subtitles 16 to 20 should be at the top center/left.

Best Regards.

[Episode1.zip](https://github.com/SubtitleEdit/subtitleedit/files/12714096/Episode1.zip)

**Comment by eddilara** [comment]
srt doesn't do positioning
use ass instead

**Comment by Kloud29** [comment]
srt does (light) positionning but it's not the problem here if you read well, I tried also with .vtt.
It works well usually, I have srt with positionning except with this new kind of dfxp.
