### ISSUE TITLE
Just a slight tweak of FIND/REPLACE dialogues 

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7448]
From the start, I have been trying to ask for some standard behavior in SE, which is implemented in Notepad, Wordpad, and MS Word. Again, I'll talk about FIND/REPLACE. 

Everything works just fine if the word is found at least once. No problem. But if the word **is not found** in dialogues Find/Replace, there is no message window to say CANNOT FIND THE WORD "XXXXXX" with the OK button below it. Instead, we must hit the button FIND several times, without any result or any response from the program,  to realize that there is no such a word. We can hit this FIND button as many times as we can, without any response from the program. We should get a message after the first click on the button FIND. 

For instance, Notepad resolves this situation (when our word is not in the file), it gives a message: 

![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/efe3a38f-c625-48f3-8337-b484405b4d3f)

We can see that, when this message is displayed, the button FIND is changed (its label) into FIND NEXT. It is not necessary, it can stay in its initial shape, as FIND (if it is the problem), we just need to get the message that there is no such a word in the subtitle.

**Comment by jmaraujouy** [comment]
There is a "text not found" message. It is located in the status bar.

![screenshot](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/430809ac-6212-44ff-bd02-dbc6d216125d)

**Comment by Cyberyoda1411** [comment]
No, it is not always the case, sometimes you get the message that the search has started from the line xxx and that is all. Nikolaj already made a dialogue for this. 

For Nikolaj. Everything is just fine now. Can the dialogue you made be a bit smaller, and not to cover the find or replace dialogue, to see better what is happening? If not, it is OK. It is one step forward.

**Comment by Cyberyoda1411** [comment]
Nikolaj, I have a total grasp of the Find/Replace dialogues behavior.

1. The first line of the subtitle is selected.  If you try to find the non-existing word, you will get a message in the status bar 'XXX' not found. No other dialogues to make it more visible. And the message in the status bar will VANISH in 10 seconds. 

2. If you are in the middle of the subtitle, some line in the middle is selected. If you try to find the non-existing word in Find/Replace, you will get two things: 
a) in the status bar you will get a message that means nothing useful: "Searching for "xxxx" from line 34...," which says only where is your selected line. 
b) you get the message window CONTINUE FIND? With text: "The search item was not found" If you want to start searching from the top (YES BUTTON), nothing happens. 

This is a very inconsistent behavior, not even close to Notepad which tells you if there is no word you are searching for, and gives you a message window for that, you don't need to watch the status bar or to pay attention where your selection in the subtitle is. 

I KNOW, it is not a BIG THING. But it would be nice if you don't need to click the button Find and get the message if there is no such a word, instead to watch around.
