### ISSUE TITLE
SUP to PNG/XML

### ISSUE THREAD

**Issue by tormento** [SubtitleEdit/subtitleedit#7450]
I have an idea to OCR anime BD.

1. Export SUP to PNG+XML
2. split PNG in two parts
3. OCR the PNG+XML for every semi-image
4. combine the two srt.

Is possible with Subtitle Edit the 1st and 3rd part?

**Comment by eddilara** [comment]
bd subs are sup...you can just load them

**Comment by tormento** [comment]
@eddilara I can't understand what your answer has to do with my question…

Update: I saw that I can export png+xml from OCR. Still have to find a way to do it without having to call the OCR, directly from SUP.

**Comment by eddilara** [comment]
> @eddilara I can't understand what your answer has to do with my question…
> 
> Update: I saw that I can export png+xml from OCR. Still have to find a way to do it without having to call the OCR, directly from SUP.

you better explain better what you are trying to do

**Comment by tormento** [comment]
Animes often upper and lower subtitles with overlapping timings.

A simple OCR makes you lose hours to fix that timings.

My idea was to split sup in upper and lower part in png format, to separately OCR the two parts and then join the srt together.

**Comment by eddilara** [comment]
ahh...yea I know those subs
subtitle edit can't do anything about that tho...you have to go ask tesseract devs to implement it
I tried many times...they basically ignore me
basically what you want is positioning on your OCRed subs
