### ISSUE TITLE
ASSA: Preview for Set Position tool

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7451]
The preview should be taken from the video cursor position rather than taken from the start of the selected line, simply because the snapshot taken by SE is not always expected and useful. :(

**Comment by LeonCheung** [comment]
UPDATE
Some common reasons:

1. When using it on multiple selected lines, SE will always pick an early frame from the FIRST selected line as the reference frame which is not always expected.
2. When trying to align pos with OSD texts that have a very long fade-in time, it can be hardly visible in the first few frames...
3. Currently, we don't have a tool like "position picker", so in order to get a second position value for **\move** tag for example, it can hardly help, especially when you want to track moving texts on the screen.

In a word, Taking the preview at the current time would be a much better idea.

**Comment by niksedk** [comment]
thx for the info - how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
Hi, working as expected, thx so much! Two more points to add:

1. It seems that the very first frame of the video will be displayed for some milliseconds in the tool, and then it's gone very soon, not a big deal, just in case there's room for improving a bit. (same with the Generate BG Box tool)
2. It will be also nice to make the Image Color Picker tool like this as well:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/1f9ac4a0-2852-4008-91a4-15233081a8f3)
