### ISSUE TITLE
The 'Replace' option is not functioning correctly

### ISSUE THREAD

**Issue by kadrimarzouki** [SubtitleEdit/subtitleedit#7452]
I got the following error message:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/47260178/babb2323-55e5-444b-b30f-948f07a4cba4)

**Comment by niksedk** [comment]
How can I re-create this?
Is it a special subtitle or what?

**Comment by kadrimarzouki** [comment]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/47260178/0ed955b5-c6bf-4f25-ac46-f793776bf4f3)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/47260178/ccf89ba5-2355-4a96-8a97-f19bc66cc5ec)

It's not a special SRT file; it happens every time I press Ctrl+H or (Menu, Edit, Replace)

**Comment by kadrimarzouki** [comment]
Are there any updates on this issue? Am I the only one experiencing it?
I am using the latest beta, uploaded yesterday (Oct, 7) 
@niksedk

**Comment by niksedk** [comment]
Could you try this debug beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBetaDebug.zip

It should supply a line number when crashing which is often helpful

**Comment by kadrimarzouki** [comment]
https://github.com/SubtitleEdit/subtitleedit/assets/47260178/aeaf712f-e180-4555-899c-2fe2adf805b0


@niksedk 
_**Clicking on the 'Replace' option in SEdebug isn't producing any results**_

**Comment by niksedk** [comment]
Sorry, I just cannot re-create this.
