### ISSUE TITLE
Improved translation,  other API [LibreTraslate]

### ISSUE THREAD

**Issue by AnonymousWebHacker** [SubtitleEdit/subtitleedit#7453]
When you are caught using the google API, you have veryyy bad translation, However, if you use LibreTraslate, give a better translation.

LibreTraslate has public APIs, and it would be great to use them
Website Official Demo: https://libretranslate.com
Github Proyect: https://github.com/LibreTranslate/LibreTranslate

**Comment by darnn** [comment]
I'm not sure what languages it could conceivably be better than Google Translate, but one, it doesn't even support Hebrew, for instance, and two, on a fairly elementary Russian sentence, it's clearly worse:
Russian:
Возьми глубокий вдох и на выдохе закрой глаза.
Libre:
Take a deep breath and close your eyes.
Google Translate:
Take a deep breath and close your eyes as you exhale.

Libre completely missed that last part.

Which is not to say I'm against it being accessible via SE, but we should at least be clear on the potential benefits.

**Comment by niksedk** [comment]
OK, it was easy to add LibraTranslate after adding NLLB, so it's included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

Note: Python is required - see https://www.nikse.dk/subtitleedit/help#translation and/or https://github.com/LibreTranslate/LibreTranslate

**Comment by AnonymousWebHacker** [comment]
> OK, it was easy to add LibreTranslate after adding NLLB, so it's included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
> 
> Note: Python is required - see https://www.nikse.dk/subtitleedit/help#translation and/or https://github.com/LibreTranslate/LibreTranslate

It is a shame that it is OpenSource, and does not have its version for Linux

**Comment by niksedk** [comment]
Why should it not work on Linux?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/89e5823e-04ad-457c-91df-445587d5b5f2)

**Comment by niksedk** [comment]
Works just fine on Linux:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/fbd900af-9bd1-421c-a1fc-cf3a334c1d01)

**Comment by AnonymousWebHacker** [comment]
I was referring to running subtliteedit without wine or mono

**Comment by AnonymousWebHacker** [comment]
IF I chose a public API, why does it keep telling me that I need Libretraslate selfhost? I can't use the public one?

![Captura desde 2023-10-05 13-01-46](https://github.com/SubtitleEdit/subtitleedit/assets/43164089/2da70b17-c1e0-43b5-8823-2d2f9188ff79)

**Comment by niksedk** [comment]
You need an API key - read more here: https://libretranslate.com/

Error msg improved a bit:
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
> I was referring to running subtliteedit without wine or mono. I don't like contaminating my system, or running wine, or emulating things

Wine is emulating things... mono is just a framework.

**Comment by AnonymousWebHacker** [comment]
> I'm not sure what languages it could conceivably be better than Google Translate, but one, it doesn't even support Hebrew, for instance, and two, on a fairly elementary Russian sentence, it's clearly worse: Russian: Возьми глубокий вдох и на выдохе закрой глаза. Libre: Take a deep breath and close your eyes. Google Translate: Take a deep breath and close your eyes as you exhale.
> 
> Libre completely missed that last part.
> 
> Which is not to say I'm against it being accessible via SE, but we should at least be clear on the potential benefits.

**Winstxnhdw** offers a better translation than Google translate, at least in the English - Spanish language

**Comment by AnonymousWebHacker** [comment]
[niksedk](https://github.com/niksedk)   You should also check out this yandex API, it gave me a much more perfect translation than Winstxnhdw 

Doc: https://yandex.com/dev/translate/
API http://translate.yandex.com/

The public API could be used for a while, then some way for each user to put their own API KEY

**Comment by AnonymousWebHacker** [comment]
[niksedk](https://github.com/niksedk) There is also a problem, what if the API installations are not local, and are on a subnet IP? 
I installed the winstxnhdw/nllb-api API on a CT on my local network, but now I can't use it because I can't specify the IP of my API

**Comment by valador** [comment]
I am running LibreTranslate on docker in windows (wsl2) and still hawe error - "requires web server running locally!" On address http://localhost:5000/ i see libretranslate webpage, but Subtitle Edit not see :(

**Comment by niksedk** [comment]
Could you send a screenshot?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/5cfafada-0ff9-4627-8c53-0da75f218007)

is something if the file "error_log.txt"?
I will probably need to improve the error logging...

**Comment by AnonymousWebHacker** [comment]
@valador Remember that you have to have an instance of LibreTranslate installed locally (selfhost)

**Comment by valador** [comment]
LibreTranslate on Windows - only work in docker, i try to build with conda - some libs not have for windows.
![изображение](https://github.com/SubtitleEdit/subtitleedit/assets/3517485/e9faa828-a296-4d57-94b5-9534e88d50da)
![изображение](https://github.com/SubtitleEdit/subtitleedit/assets/3517485/e65bfead-cbed-4393-aa4b-538103349d4f)

**Comment by niksedk** [comment]
Could you try latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
It should have a better log in `error_log.txt`...

**Comment by niksedk** [comment]
@valador: `{"error":"es is not supported"}`... so you have not installed Spanish it seems.

**Comment by valador** [comment]
[niksedk](https://github.com/niksedk)
> `{"error":"es is not supported"}`... so you have not installed Spanish it seems.

My bad, all translate work, just std container without CUDA not download default models without --update-models, I haven't checked this :( My mistake. Sorry for wasting your time.

**Comment by niksedk** [comment]
No problem, I'm glad it's hopefully working for you now.

Did you find the docker image or make it yourself? 
Actually, a docker image could be nice to have for SE... Python component-versions seems to be a bit problematic!

**Comment by valador** [comment]
> No problem, I'm glad it's hopefully working for you now.
> 
> Did you find the docker image or make it yourself? Actually, a docker image could be nice to have for SE... Python component-versions seems to be a bit problematic!

Docker container for LibreTranslate - from official instruction. Docker container for SE might be made, only i'm not shure - how be work GUI in Windows, on linux just need xhost + for host and provide options for container -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix
For support CUDA need cuda-toolkit for docker and add option for container --gpus all

It may be necessary to split SE into server and client parts. Completely transfer the client interface to the web server, then you can host SE anywhere and connect without problems. But then there will be downloading and uploading for video and not direct access + you will need to select and mount directories for tmp and the working folder. There are pros and cons to this approach.
