### ISSUE TITLE
BUG: Filetype description duplicated (Windows)

### ISSUE THREAD

**Issue by gaiking-uk** [SubtitleEdit/subtitleedit#7454]
Hi Nikolaj,

The filetype names in Windows seem to be duplicated.

**EXAMPLE**
- Extension: `.srt` file
- Description: `SubRip subtitle file subtitle file`

![SRT file](https://github.com/SubtitleEdit/subtitleedit/assets/37931190/a1ed56a0-bd73-4654-ba50-cea5ba608486)

PS -- Personally I prefer filetype descriptions as short as possible (e.g. `SRT Subtitle`) as this helps them display more easily in the `type` column in File Explorer, especially when space is limited.

**Comment by niksedk** [comment]
Hm, I don't get that, I get "SubRip subtitle file (.srt)":
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/d50a95f3-c910-48be-a5f0-2a1f5a725cbd)

**Comment by gaiking-uk** [comment]
Thanks for looking into this, it might just have been weird anomaly on my system I guess...

I de-associated and then re-associated `.srt` files from within SubtitleEdit, however the filetype then just showed just as `SRT File` so guessing it could be due to some old/conflicting registry entries or something... No worries, I am happy to crawl into RegEdit and sort it out manually (and if it is not affecting other users, then that's fine!👍🏼)

***

✅ Assuming there's nothing else, then happy to close this issue
