### ISSUE TITLE
REQUEST: Custom import option

### ISSUE THREAD

**Issue by gaiking-uk** [SubtitleEdit/subtitleedit#7455]
### Summary
- Please can you add a "custom text format" ***import*** option, ideally with the same interface/idea as the current `File > Export > Export custom text format` option.

### Current Limitations
- While the current custom ***export*** feature is great, and have used this to export info from `.srt` files to other formats such as: 1️⃣ `.lrc` file (lyric file used to display time-synced words over music), and 2️⃣ `.csv` file, to make more intricate/complex changes in Excel for example...
- However, it is then tricky to re-import the updated timings/text back into Subtitle Edit
- I know there is a ***plain text file*** import option that can be configured *to some extent*, however I have struggled to configure the import format to match the export format I created when I exported the subtitles from Subtitle Edit originally

***

### Additional Notes
- Ideally the import engine would reference the same formats that have been created in the custom export menu, e.g. ...
![Subtitle Edit custom export formats](https://github.com/SubtitleEdit/subtitleedit/assets/37931190/8d9acd4d-37ee-4eb3-9ee0-e23fd4f996ae)

- If possible, the above would also help the UI - as the custom formats for ***export*** are very easy to configure -- e.g. the below `.lrc` file took me less than 2 minutes to setup in Subtitle Edit...
![Subtitle Edit custom export format creation](https://github.com/SubtitleEdit/subtitleedit/assets/37931190/bd8910e2-5cbc-46c6-8719-42090fc92f40)

- I appreciate parsing unknown input is more difficult that exporting known data, however hopefully the above option would make this easier (as relies on the user to exactly specify the input format, and is means the data is more likely to parse successfully, as it was originally exported by Subtitle Edit in the format selected.

**Comment by niksedk** [comment]
Sorry, I do not think this is possible.
