### ISSUE TITLE
FPS not showing correctly

### ISSUE THREAD

**Issue by JDTR75** [SubtitleEdit/subtitleedit#7459]
Hi, I'm leaving a video for easier understanding of the issue. Please focus on the duration and the actual frame rate of the video.

https://github.com/SubtitleEdit/subtitleedit/assets/1891941/4baecce7-255f-4f1d-9475-0ae93d7c3ee6

The frame rate of the video is 29.97 but the duration is only moving up to 24. I don't remember this happening before. Yes, I have the default frame rate set at 24 but this always adapted/updated automatically depending on the video loaded.

Hope it makes sense, and thank you in advance!

**Comment by niksedk** [comment]
Thx for the info - I can confirm this is a 4.x bug. I will look into this soon.

**Comment by niksedk** [comment]
This frame rate issue should hopefully be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by JDTR75** [comment]
Thank you! Working fine now 👌
