### ISSUE TITLE
Remove text for hearing impaired leaves additional space in when removing text in the middle of a line

### ISSUE THREAD

**Issue by sbraz** [SubtitleEdit/subtitleedit#746]
Hi, when a word present for HI is removed in the middle of a line, two spaces appear instead of one:
```
Ha. (LAUGHS) That's weird.
```
is replaced with
```
Ha.  That's weird.
```
The correct output would be:
```
Ha. That's weird.
```

**Comment by ivandrofly** [comment]
@niksedk  | @sbraz  can be closed

**Comment by niksedk** [comment]
Yes, this works in latest beta: http://www.nikse.dk/SubtitleEdit.zip (portable)
