### ISSUE TITLE
sound clipping / distortion after running Subtitle Edit

### ISSUE THREAD

**Issue by gautxori-yuyu** [SubtitleEdit/subtitleedit#7461]
Hi, I have used subtitle edit to fix some subtitles with video sync feature, using mpc-hc for playback, and after that all sounds in laptop's speakers sound heavily clipped. I mean ALL sounds, be it from MPc-HC, foobar2000, system sounds, etc. I removed audio drivers from device manager, windows reinstalled them after rebboting, but problem persists.
Any clues?

**Comment by niksedk** [comment]
Sorry, no. I don't think this is SE related...

mpv is the recommend video player in SE.
