### ISSUE TITLE
Docker: Error during connect

### ISSUE THREAD

**Issue by Masina86** [SubtitleEdit/subtitleedit#7463]
What am I doing wrong?

C:\nlb-serve\nllb-serve-main>docker run --rm -e SERVER_PORT=5000 -e APP_PORT=7860 -p 7860:7860 -v C:\Windows\Temp\cache.bin:/home/user/.cache ghcr.io/winstxnhdw/nllb-a
docker: error during connect: this error may indicate that the docker daemon is not running: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.

How can i fix this?
I am following this guide how to install: https://www.nikse.dk/subtitleedit/help#translation

**Comment by niksedk** [comment]
Did you install and start docker?
