### ISSUE TITLE
Whisper speech recognition is getting worse

### ISSUE THREAD

**Issue by marwanhbt4** [SubtitleEdit/subtitleedit#7464]
Hello community, I have been using the latest version of Subtitle Edit and I noticed that the whisper models are getting worse and have a lot of problems. For example, whisper const me is only giving me hearing impaired tags like [music] [piano] and not giving me any subtitles. Whisper faster purfview is giving sentences of two people merged in each other in one line and it has a lot of hallucinations. I hope the developers can notice this and fix it soon. Thank you.

![Screenshot 2023-10-02 004953](https://github.com/SubtitleEdit/subtitleedit/assets/145354804/c062e667-e55a-4f39-b888-c8667a1474ea)

**Comment by nhan000** [comment]
File the bug report accordingly. This repo doesn't have anything to do with Whisper.

**Comment by niksedk** [comment]
Yes, SE is only using Whisper and doing a little post-processing.
Report your bugs to the Whisper projects (upstream) - probably with audio files + more details about the issues.
