### ISSUE TITLE
BUG: Can't generate waveforms because of VLC crashing

### ISSUE THREAD

**Issue by gaiking-uk** [SubtitleEdit/subtitleedit#7467]
### Issue
- Unable to generate waveforms, VLC crashes when trying to transcode the file

### Notes
- I am sure that I have generated waveforms previously, but I have tried today with multiple files and I keep getting an error message saying that VLC has crashed.
- I tried on `4.0.1` and rolled back to `3.6.13` in case it was a bug in the new version, but could not generate waveform in either
- I checked the VLC log and there is nothing explicitly to show any traceable error -- VLC opens, loads its plugins, opens the file, begins transcoding it, and then the log just stops (no specific error message or anything).
- VLC is able to play the audio in the MP4 file, so it doesn't *seem* like an error with VLC or the specific file(s)
- Would it be worth / better to use `FFmpeg` for transcoding? 🤔

### Screenshot
![image](https://github.com/SubtitleEdit/subtitleedit/assets/37931190/35a4e730-4b18-46d1-87ee-0c8e594e5458)

**Comment by niksedk** [comment]
It is highly recommended using FFmpeg for extracting audio :)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/0b78207f-7495-45b6-9fa2-d46ec91d9347)

**Comment by gaiking-uk** [comment]
> @niksedk: It is highly recommended using FFmpeg for extracting audio :)

Ah OK, I didn't realise about that setting, but I think that explains it because I already configured FFmpeg! 🙂...

![image](https://github.com/SubtitleEdit/subtitleedit/assets/37931190/b4679b78-814c-4f09-8903-87da0a694d0d)

I *think* what happened was...
1. I opened SE (`v3.6.13`) and saw `v4.0.1` was available
2. I closed SE and deleted everything in the SE directory, except `settings.xml`
3. I downloaded `v4.0.1` (portable version) and extracted all the files back into my SE directory
4. **At this point:** SE was upgraded to `v4.0.1`, however the settings file now had a bad link to `FFmpeg` because I deleted `FFmpeg` folder, when I cleared out the contents of `v3.6.13`
... It also possibly explains why even rolling back to `v3.6.13` didn't resolve it, as I still wasn't restoring the `FFmpeg` folder!

***

### Interestingly, I fixed the `FFmpeg` path and the waveform started working again! 😁🎉
![image](https://github.com/SubtitleEdit/subtitleedit/assets/37931190/696f5cb4-e11b-4dc2-8acb-ebc7b70f9f7e)
