### ISSUE TITLE
BUG: Play/pause waveform button doesn't pause (only plays)

### ISSUE THREAD

**Issue by gaiking-uk** [SubtitleEdit/subtitleedit#7468]
### Issue
- When pressing ▶️ in the video preview window, the button changes to ⏸️ and clicking it again pauses the video (good behaviour that users would expect in most apps)
- However pressing ▶️ in the waveform window does not work the same way. The button stays as ▶️ and pressing it again does not pause the video

### Notes
- The above may be considered "working correctly" and more of a change request, however it is inconsistent behaviour and making both buttons work the same way (the way the video preview works) would definitely be better
- This is especially true when trying to play/pause at a sync point in the video and you want to get the end timestamp as close as possible (by the user clicks, nothing happens, they are confused for a second and then has to move the mouse to another button, the timestamps will be several seconds different)

**Comment by niksedk** [comment]
Hm, I cannot re-create this... what video player are you using in SE?

**Comment by gaiking-uk** [comment]
Thanks for looking into this. Based on your experience I re-tested in some more specific scenarios and have think when I first noticed it, is was happening a lot because of the VLC issue I had at the same time. Further testing today has helped to narrow it down, please see below...

### Updated testing, covering more scenarios...
- **SETUP**: Open `.srt` file which has a related `.mp4` file in same folder, SE loads subtitles and video automatically
- **Test 1**: Waveform not generated (click ▶️ with no waveform): ❌ As described, video plays but button doesn't change
- **Test 2**: Waveform generation fails (using VLC): ❔Results inconsistent, sometimes seemed to work, sometimes not
- **Test 3**: Waveform generation successful (using FFmpeg): ✅ Button works as expected, changing between ▶️ / ⏸️

**Comment by niksedk** [comment]
Should be fixed in latest beta
