### ISSUE TITLE
Doesn't keep font size in Text box settings

### ISSUE THREAD

**Issue by Hakunamatata67** [SubtitleEdit/subtitleedit#7469]
Hi,

since the last version, every time I open Subtitle Edit, I have to go to Settings > Appearance > Text box, because it doesn't keep my font size and the original setting is too small for me.

Not a big issue, but just want to let you know.

**Comment by niksedk** [comment]
Dupe of https://github.com/SubtitleEdit/subtitleedit/issues/7404
