### ISSUE TITLE
ASSA set position tool error

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7472]
Not sure why but I suddenly got this message, it is gone with a clean settings.xml though:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/d830c117-8a98-40e4-a94c-3af09423d938)
[Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/12795212/Settings.zip)

**Comment by niksedk** [comment]
Hm, it works fine here... could you test this beta with debug info?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBetaDebug.zip

**Comment by LeonCheung** [comment]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/bf673462-879b-402e-9dbb-32dfef7f409b)
[details.txt](https://github.com/SubtitleEdit/subtitleedit/files/12800328/details.txt)
