### ISSUE TITLE
Problems Opening EBU STL Teletext

### ISSUE THREAD

**Issue by raphaelomoreira** [SubtitleEdit/subtitleedit#7475]
Hey guys!
When opening EBU STL TELETEXT files with parameters, such as italics, SubtitleEdit does not recognize it. Other programs, like EZtitle, are recognizing it. These are files created in SubtitleEdit itself! EBU STL OPEN SUBTITLING, no problems.
I'm on version 4.0.1
Has anyone noticed this issue? Is there a way to resolve it?

Thanks!

![EBU_TELE](https://github.com/SubtitleEdit/subtitleedit/assets/105943943/21f8ac67-ffb9-443e-bacc-324dd9ea2056)

![EBU_OPEN](https://github.com/SubtitleEdit/subtitleedit/assets/105943943/587ae70f-d298-45ff-b513-5526fa4e409e)

**Comment by niksedk** [comment]
Could you attach some sample files?

**Comment by raphaelomoreira** [comment]
Hi, Mr. Nikolaj!
Thank you for your help. Here are some files.
[EBU_STL_TELETEXT_FILES.zip](https://github.com/SubtitleEdit/subtitleedit/files/12803247/EBU_STL_TELETEXT_FILES.zip)
I would like to say how wonderful your SubtitleEdit is.
You have no idea how much this incredible software
helps people's accessibility. Congratulations!

**Comment by niksedk** [comment]
According to the EBU spec, colors are only available when having "teletext" and italic/bold/box is only available when using "open subtitling":

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/fe0632b5-8912-4de1-a316-1cb82580902f)
