### ISSUE TITLE
Unable to download ffmpeg

### ISSUE THREAD

**Issue by rajuaryan21** [SubtitleEdit/subtitleedit#7476]
I get this error while the pop-up dialog opens to download FFmpeg. Is there any fix? I have attached the screenshot. Subtitle Edit is enabled in the 
![Screenshot (17)](https://github.com/SubtitleEdit/subtitleedit/assets/3599630/646bcf5d-ac1f-483f-957a-ff5e60f6899d)
firewall.

**Comment by niksedk** [comment]
Try again later... and double check the firewall
