### ISSUE TITLE
Subtitle timings are wrong when exporting to bdn/xml

### ISSUE THREAD

**Issue by nautilus7** [SubtitleEdit/subtitleedit#7477]
Hi, I had a conversation with @cubicibo the author of SUPer and ass2bdnxml programs and it seems that we came across a bug in subtitleedit.

The subtitle timings of the bdn/xml file created with subtitleedit are different from the timings of a bdn/xml create by ass2bdnxml.
Example workflow:

ass --> bdn/xml with subtitleedit
ass --> bdn/xml with ass2bdnxml

It seems that for NTSC framerates like 24000/1001, 30000/1001 and 60000/1001, the timings in the bdn/xml format should be scaled by 1001. See his comment at https://github.com/cubicibo/SUPer/issues/9#issuecomment-1743803170 where he provides a better explanation.

What do you think?

**Comment by nautilus7** [comment]
If this is actually a but, then it's possible to also affect the timings in the sup export/creation function in subtitleedit.

**Comment by cubicibo** [comment]
I peeked at the code and the issue comes from this function:
https://github.com/SubtitleEdit/subtitleedit/blob/a090311ce260d0cd9aa2de732b138394dff43f28/src/ui/Forms/ExportPngXml.cs#L191-L194

It performs a real time conversion of a fractional TC (BaseUnit of 1000 ms) to a NDF TC. However, NDF TC with NTSC framerates increment slower than real time so this linear correction should be applied:

$t_{NTSC} = \frac{1000}{1001}TC_{real\ time}$

**Comment by niksedk** [comment]
BDN XML has the `DropFrame` attribute... I guess SMPTE time codes only should be used if `DropFrame` is `True` ?
ATM  `DropFrame` is always `False` in SE, so that would require an UI input field.

````xml
<Format VideoFormat="2048x858" FrameRate="23.976" DropFrame="false" />
````

(SE does have SMPTE mode where the video player has a faster time)

**Comment by cubicibo** [comment]
BDN XML is only using SMPTE timecodes.
You can use DF SMPTE  with DropFrame="true" but then authoring software will expect valid drop frames TC that skips 2 frames every minutes except when $mm\ mod10 == 0$.
The easiest is simply to use SMPTE NDF but scale timestamps by /1.001 whenever the framerate is 23.976, 29.97, 47.95 or 59.94.

**Comment by cubicibo** [comment]
Looks good to me! But nautilus should have the final word.

**Comment by nautilus7** [comment]
Will test in the weekend and report back. Thanks!

**Comment by nautilus7** [comment]
Hi, I tested the new version. It seems that it's almost ok. 2 issues I found:

1. Reading (opening) of a bdn/xml is wrong. I suppose the reading function should get the same treatment (scaling of the timecodes) as the writing function did.

2. There is a difference between the bdn/xml output of subtitleedit vs ass2bdnxml regarding the timecodes of _very last event_. There is 1 frame difference between the two. Not sure which one is wrong, since ass2bdnxml had a bug that was recently fixed regarding the last event timecodes, but I think subtitleedit got it wrong here. Please both @niksedk and @cubicibo check your programs to be sure.

Thanks!

New sample: 
[sample-new.zip](https://github.com/SubtitleEdit/subtitleedit/files/12837241/sample-new.zip)

**Comment by cubicibo** [comment]
Both are correct and depends on the implementation.

If we assume SE and A2B samples at TC + 1/(2*fps), we have the following:
```
ASS: TC(1000,  '02:56:41.59')       = 10601.591 s
A2B: TC(23.98, '02:56:30:23')*1.001 = 10601.611875 s
SE:  TC(23.98, '02:56:31:00')*1.001 = 10601.570166 s
```
$E_{A2B} = \lvert 10601.591 -  10601.611875\rvert{} = 0.0208749$
$E_{SE} = \lvert 10601.591 -  10601.570166\rvert{} = 0.020833$

As you can see, both are equidistant to the ASS timecode, with SE being ever so slightly more correct here. ass2bdnxml always samples at $frame_i + frameduration/2$, which is more consistent for continuous animations embedded in ASS files but indeed, can lead to a single frame drift in such situation.

**Comment by nautilus7** [comment]
Ok, thanks for the explanation.

So only the issue related to reading bdn/xml remains then.

**Comment by nautilus7** [comment]
> Both are correct and depends on the implementation.
> 
> If we assume timestamps are sampled in the middle of the current TC frame, we have the following:
> 
> ```
> ASS: TC(1000,  '02:56:41.59')       = 10601.591 s
> A2B: TC(23.98, '02:56:30:23')*1.001 = 10601.611875 s
> SE:  TC(23.98, '02:56:31:00')*1.001 = 10601.570166 s
> ```
> 
> EA2B=|10601.591−10601.611875|=0.0208749 ESE=|10601.591−10601.570166|=0.020833
> 
> As you can see, both are equidistant to the ASS timecode, with SE being ever so slightly more correct here. ass2bdnxml always samples at framei+frameduration/2, which is more consistent for continuous animations embedded in ASS files but indeed, can lead to a single frame drift in such situation. The main issue is really just ASS lack of accurate timestamps. centiseconds is not enough for frame durations and this ASS file in particular, as the timestamp is defined exactly in the middle of a frame.


@cubicibo I read again you last post... and I am confused.

The last event in my ASS subtitle has a starting time of 02:56:41.59, which is just 1ms off of the frame accurate time. This is due the lack of the milliseconds accuracy in the ASS format. In addition, since milliseconds are rounded to centiseconds in ASS, this means that ASS timecodes can be off by at most +/- 5ms.

Now, reading the bdn/xml files with subtitleedit we have:

bdn/xml created with subtitleedit -- in time of 02:56:41.59 from the original ASS is now changed to 02:56:41.550
bdn/xml created with ass2bdnxml-- in time of 02:56:41.59 from the original ASS is now changed to 02:56:41.591

This is exactly 1 frame off for subtitleedit. How are both programs correct and how is subtitleedit more accurate here? I am puzzled.

![bdn](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/f05f6ba0-4d1e-4379-9762-0a28ba78766f)

**Comment by cubicibo** [comment]
It is not that easy. BDN XML+PNG is a snapshot of the subtitles in different unit of time. But when do you take the snapshot? Start time? Start_time + frame_duration/2? This could change the TC by a frame due to rounding behaviour which depends on the implementation. Use MPV as ground truth with a TCR reference video. Not ass2bdnxml.

If this is really a SE issue, the only line I think could cause it is this: https://github.com/SubtitleEdit/subtitleedit/blob/a090311ce260d0cd9aa2de732b138394dff43f28/src/ui/Forms/ExportPngXml.cs#L180
where a frame is lost due to rounding.

**Comment by nautilus7** [comment]
Hi, what about this last code correction by cubicibo? Is that fixed?

**Comment by cubicibo** [comment]
No, with v0.6a, timestamps now differs even more to SubtitleEdit. About a few dozen of events have +/-1 frame to either TCin and/or TCout.

The new code performs rounding to closest frame, rather than "some offset + floor".
