### ISSUE TITLE
Import/Export Interjection List

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#7478]
Hello there!
What do you think about the possibility to import and to export interjection list?
I have a english interjection list and, sometimes, I have to add one by one from that list to the SE.
Wouldn't it be nice has these options?

![Inter01](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/b26f7e66-4d08-40d5-a1bd-bbd99cf506c2)

**Comment by niksedk** [comment]
Would an edit list work?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/57b0a821-8086-4a47-b91d-0dfe830e04e6)


https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by Andrebavila** [comment]
> Would an edit list work?
> 
> ![image](https://user-images.githubusercontent.com/1261331/272804706-57b0a821-8086-4a47-b91d-0dfe830e04e6.png)
> 
> https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

You've made the whole thing easier, @niksedk 
It'sa lot better than my suggestion. It's perfect!
Thank you for listening!
