### ISSUE TITLE
How to use Multiple Replace to set font outline thickness?

### ISSUE THREAD

**Issue by Kaiji-Kun** [SubtitleEdit/subtitleedit#7480]
I have a set of .ass subtitles but the font outline thickness is bigger in odd numbered episodes.

I was able to change the font color using a solution I found here...

`Find what: "(?s)\A(<font color=".+?">)?(.+?)(</font>)?\z" and Replace with: <font color="#ffffff">$2</font>`

...but how do I set all the font outlines to a specific thickness (thin)?

**Comment by niksedk** [comment]
What version of SE are you using?

**Comment by Kaiji-Kun** [comment]
3.6.10

**Comment by Kaiji-Kun** [comment]
3.6.10

I figured out the problem... "ScaledBorderAndShadow" was set to "No" for even numbered files and "Yes" for odd numbered.
