### ISSUE TITLE
Error in Format "Advances Sub Station Alpha styles"

### ISSUE THREAD

**Issue by iVent-Zor** [SubtitleEdit/subtitleedit#7481]
When starting option "Generate background box"

A "Windows Forms Thread Exception" box appears!

![Error in Format -Advances Sub Station Alpha styles-](https://github.com/SubtitleEdit/subtitleedit/assets/147071386/dd9c5f88-1b8c-4863-88b0-fd5b16b82eb0)

**Comment by niksedk** [comment]
Hi @iVent-Zor,

How can I re-create this?

If you could post the details using the debug version, that would help too: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBetaDebug.zip

**Comment by iVent-Zor** [comment]
https://github.com/SubtitleEdit/subtitleedit/assets/147071386/828aa172-e1ba-4f77-8c1a-e8a4b0544cf2

**Comment by iVent-Zor** [comment]
[error_log v3.6.13.txt](https://github.com/SubtitleEdit/subtitleedit/files/12821328/error_log.v3.6.13.txt)
[error_log v4.0.1 Dev.txt](https://github.com/SubtitleEdit/subtitleedit/files/12821331/error_log.v4.0.1.Dev.txt)

**Comment by niksedk** [comment]
Thx... I need the text from the messagebox in the debug version!

**Comment by iVent-Zor** [comment]
Is the same text (Which I can not copy!) as in the two log files I sent you.

Op do 5 okt. 2023 19:51 schreef Nikolaj Olsson ***@***.***>:

**Comment by niksedk** [comment]
I've tried to improve the error handling a bit here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

Also, do re-download FFmpeg - go to Options - Settings - Waveform

**Comment by niksedk** [comment]
You can copy text from message boxes by using "Ctrl+c" when it active.

**Comment by iVent-Zor** [comment]
Okay

Op do 5 okt. 2023 20:13 schreef Nikolaj Olsson ***@***.***>:

**Comment by iVent-Zor** [comment]
This is what you want?
---
Unable to generate video with FFmpeg.
-i
"C:\Users\iVent-PC\AppData\Local\Temp\2dd4ee36-1baf-4541-b672-9d9899650131.mkv"
-vf "ass=f7367e44-df58-438c-8503-3179e2027aff.ass",yadif,format=yuv420p -g
30 -bf 2 -s 645x360 -c:v libx264    -c:a  -ar  -use_editlist 0 -movflags
+faststart
"C:\Users\iVent-PC\AppData\Local\Temp\b81f337a-9ede-48b5-a8ef-32af39696d9a.mp4"

Op do 5 okt 2023 om 20:13 schreef Nikolaj Olsson ***@***.***>:

**Comment by niksedk** [comment]
You seem to have a problem with ffmpeg - have you re-downloaded ffmpeg?

**Comment by iVent-Zor** [comment]
I downloaded ffmgeg again, and still the same error. Here is the new
message:

P.s. What is the .mkv doing in the message? The video file in the test is
.mp4!
---
Unable to generate video with FFmpeg.
-i
"C:\Users\iVent-PC\AppData\Local\Temp\85f43f8b-df60-4b40-b8fb-b7ece41a9239.mkv"
-vf "ass=749d629f-a8d4-4c73-9703-eec9678d8ee7.ass",yadif,format=yuv420p -g
30 -bf 2 -s 645x360 -c:v libx264    -c:a  -ar  -use_editlist 0 -movflags
+faststart
"C:\Users\iVent-PC\AppData\Local\Temp\4f1ff7c7-6c37-4af4-9b89-4ed84eb36e10.mp4"


Op do 5 okt 2023 om 20:27 schreef Nikolaj Olsson ***@***.***>:

**Comment by niksedk** [comment]
Does this happen with all videos, or only some?

**Comment by iVent-Zor** [comment]
Only some. I tested a few videos and the error occurs completely
randomly. It seems that more boxes go right than wrong.

[image: 2023-10-12_175518.jpg]

Op wo 11 okt 2023 om 17:03 schreef Nikolaj Olsson ***@***.***

**Comment by niksedk** [comment]
Hm, it works fine here... could link to a video/subtitle that fails?

**Comment by niksedk** [comment]
> What is the .mkv doing in the message?

A temporary mkv file with only subtitles is created with only texts, so SE can calculate the precise position/size of each subtitle image.

**Comment by iVent-Zor** [comment]
Oh, okay. Thanx!

iVent

Op za 21 okt 2023 om 15:13 schreef Nikolaj Olsson ***@***.***

**Comment by iVent-Zor** [comment]
Strange! I'll try some videos on other computers. Maybe it's my laptop or
its settings.

iVent

Op za 21 okt 2023 om 10:18 schreef Nikolaj Olsson ***@***.***
