### ISSUE TITLE
Issues with the new layout(s)

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#7482]
I'm using the latest beta.
The first problem is that when I select the eighth option in the choose layout window...
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/0a89208a-4100-4d5a-9b8a-ade4bf5a482c)
...instead of the video player on the bottom, I get the waveform. So it's identical to the sixth option.
The second problem is that show/hide video now no longer works, and show/hide waveform only opens the choose layout window.

I would also suggest that an option like this be added:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/595db977-c584-434b-90be-8fef7d25cb6d)
Since this was the old Subtitle Workshop 2.51 outline, and I'm sure there are still a few people making their way from that to SE occasionally, and when I did that, many years ago now, it was an adjustment for me.

**Comment by niksedk** [comment]
I have not added controls to video-only layouts yet, as it is somewhat difficult...

`show/hide waveform` and `show/hide waveform` are replaced by layouts. I missed removing/renaming shortcuts?

**Comment by niksedk** [comment]
Sorry, the old show/hide video and show/hide waveform are gone - replaced by the 9 layouts.

I think 9 looks good in the "layout chooser", but perhaps more is needed?

**Comment by niksedk** [comment]
OK, added a new layout (and we space space left for two more):
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/77d48a17-1d22-4e6b-a0d7-e934371ba47e)

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by Flitskikker** [comment]
One extra option I could think of is the one from Aegisub?
https://www.authot.com/wordpress.new/wp-content/uploads/2018/09/test-AE.png

**Comment by niksedk** [comment]
OK, new layout included:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/48a3ee0f-fc53-4d63-a515-c088bc862163)

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by MbuguaDavid** [comment]
Is there a way to get back to the Default Subtitle Edit layout? 

![How to get Default Layout](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/a7131e53-dbcf-4332-9732-9771a25d3b9f)

Maybe have it included in the layout options.
Thanks!

**Comment by MbuguaDavid** [comment]
By the way, when I click on the Layouts for the 1st time, layout 1 is highlighted by default but is not the default Subtitle Edit layout. 
Can we have that as the default Subtitle Edit Layout? 

![layouts - Subtitle Edit](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/ad87f440-f3eb-4cf2-9321-ccc7e9b236f8)

Thanks!

**Comment by niksedk** [comment]
@MbuguaDavid: Is "Layout 1" not the default layout? "Layout 1" should the same as the old default layout...

**Comment by darnn** [comment]
Okay, 6 now works mostly as intended, but it still doesn't look like what I had before when I hid the waveform, because the video controls are missing. What it looked like before:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/8197de68-5571-4036-90ef-9d2acd3a2f23)

And what it looks like, with 6, now:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/ae0573ba-f6ef-4581-9d76-81de07871174)

**Comment by niksedk** [comment]
Updated layout 7+8 to have the video controls (when enabled): https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

SE has a shortcut for the layout picker. I guess a shortcut for going to a layout directly could be made if needed...

**Comment by darnn** [comment]
Okay, 8 does now work as intended. Two things, though:

One is that before this change, it was impossible to shrink the elements (the textbox and video player) to nothing. Now, if I drag down the border that separates the list view from the textbox in 8, I can in fact do this:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/9e7b7fd4-b88a-42ff-af67-7d2b882f4134)

I don't actually mind this and think it makes more sense, but I don't know if it was intended.

The other thing is, when I try the new method of going from what is now the 8 layout to what is now the 12 layout and then going back, the size and position of the elements is reset.
Here's 8, set up the way I want it:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/0c20522d-f7a3-4cb1-b711-f9caf697b738)

When I switch to 12, everything is as it should be:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/f501d91d-a1d0-4456-b4e4-d07b0f433fb2)

But then when I switch back to 8, the placement of the elements (that is, the height of the textbox and the height of the video player) has been reset:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/c9b78fa3-abd2-4102-be22-fb7d7f4d6c67)

**Comment by darnn** [comment]
That does seem to work now. However, it seems like shrinking elements down to a size that was previously not possible does cause issues. Before:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/0cf8a8d4-5fc1-46b4-9aa0-86ea044cc16f)

Shrunk down:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/29a1a5ca-2142-450d-8702-0dd21294ee24)

After:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/4d3eefd9-ed86-4c07-be97-3c7bd8a95f67)

**Comment by niksedk** [comment]
Thx for testing :)
Latest beta now tries to keep a min text-box size, and the resize issue should be fixed too.
It's still possible to make stuff "collapsed" and it can be useful, e.g. if you show video player full-screen on a 2nd monitor...

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

Should SE have a shortcut for each layout?

**Comment by darnn** [comment]
Seems okay on my end now, though I haven't tested it extensively. And yes, personally I would like to be able to use shortcuts for the layouts.

**Comment by niksedk** [comment]
Shortcuts for all 12 layouts added: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Toolbar icon in toolbar:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/5ecef10e-d925-43c5-9e72-83397762b6b0)

Available layouts:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/261ab527-b06a-4db1-9a42-ea69a98f19c1)

`Show/hide video` and `Show/hide waveform` have been replace by the above layouts.
Note layouts also have shortcuts.
