### ISSUE TITLE
Faster-Whisper dont work - Empty file

### ISSUE THREAD

**Issue by DonKolia** [SubtitleEdit/subtitleedit#7484]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/55564649/da207cf7-7d5d-4f91-80c9-4b85d3fcaa6e)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/55564649/d5667781-b8eb-4821-9501-1a6a7f0ddfe8)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/55564649/bcd849bc-4960-4165-85a7-80a9491e0718)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/55564649/94c85d53-7fed-40cb-8f85-45f215955b31)

I am using Windows 10 64 Bits, i tried with normal.exe program and Beta, it happens the same.

**Comment by Purfview** [comment]
What `error_log.txt` shows?
What GPU and VRAM?

**Comment by DonKolia** [comment]
Where the file? I need a PATH
GTX 960 4 GB

**Comment by DonKolia** [comment]
I see only whisper_log.txt
![image](https://github.com/SubtitleEdit/subtitleedit/assets/55564649/2cf4715e-b253-4c4a-9a3d-64bb63ec787a)

**Comment by DonKolia** [comment]
Once the arguments are set, now I work with CPU and it is taking more time

**Comment by Purfview** [comment]
> Purfview's Faster-Whisper is only for RTX cards?

No.

**Comment by DonKolia** [comment]
I see. Your amazing solution.
--device=cpu

**Comment by DonKolia** [comment]
You could say it's a bug. I understand it's open source and everyone wants quick fixes and you're probably tired of programming. But don't try to make fun of me.

**Comment by DonKolia** [comment]
As I see that this is of no use, I am closing the ticket. The treatment is shameful.
