### ISSUE TITLE
Feature Request: Ability to specify multiple Styles/Actors in batch convert

### ISSUE THREAD

**Issue by V3semir** [SubtitleEdit/subtitleedit#7485]
I’ve been using the Batch Convert feature in SubtitleEdit and it’s been incredibly helpful. However, I’ve come across a situation where I need to remove lines associated with multiple styles or actors at once. Currently, it seems that the “Remove style/actor” option under Batch Convert only allows for one style or actor to be specified at a time. This can be quite time-consuming when dealing with subtitles that have multiple styles or actors to be removed. Also, it would be nice to have an option to do Renumbering in the Batch.

**Comment by niksedk** [comment]
In latest beta you can now add multiple styles/actors to remove - separate with comma.
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
