### ISSUE TITLE
How do I delete the extra argument history for the Whisper command line?

### ISSUE THREAD

**Issue by despairTK** [SubtitleEdit/subtitleedit#7487]
When using Whisper, I fill in different extra parameter command lines depending on the video. However, the command line history of the extra parameters used always exists. I cannot delete these historical records or there is a way that I don't know to delete these historical records.

**Comment by Purfview** [comment]
Look at `Settings.xml`, after custom arg `--beep_off` it saved it there:

```
    <WhisperExtraSettings>--beep_off</WhisperExtraSettings>
    <WhisperExtraSettingsHistory>--beep_off
```
