### ISSUE TITLE
{\an8} IDX/SUB (Capture to align)

### ISSUE THREAD

**Issue by Codling** [SubtitleEdit/subtitleedit#7490]
Hello,

With DVDs and the "Capture to align" option, all subtitles have a {\an8) tag, even when the subtitle is at the bottom.

Can you fix this, please?

**Comment by Codling** [comment]
BTW, it works very well with SUPs, thank you. :)

**Comment by niksedk** [comment]
Works fine here... could you attach a sample or email a link?

**Comment by niksedk** [comment]
Thx for the sample :)
Those images have a large transparent top margin, so top position was wrong... SE now crops the image to detect a more correct top position in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
