### ISSUE TITLE
Interjection list reseting to default

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#7491]
Hello!
Whenever I update SE to a new beta version, the interjection list resets to default and I need to import the interjections I want
all over again.

**Comment by niksedk** [comment]
I've not made "user-files" yet... so e.g. `es_interjections.xml` will be overwritten in each update...

**Comment by Andrebavila** [comment]
> I've not made "user-files" yet... so e.g. `es_interjections.xml` will be overwritten in each update...

Thank you very much!
