### ISSUE TITLE
D-Cinema SMPTE 2014 broken since 4.XX

### ISSUE THREAD

**Issue by erodas** [SubtitleEdit/subtitleedit#7494]
There is wrong timecode conversion from milliseconds to frames, e.g. converting SRT to SMPTE 2014 XML @24fps subtitle yields timecodes with XX:XX:XX:24. Also font colour coding is erroneous e.g. setting font colour to FF000000 always becomes FFFFFF00 in source.

**Comment by niksedk** [comment]
Is latest beta better? 
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
