### ISSUE TITLE
[Feature request] Ability to speed up playback in player

### ISSUE THREAD

**Issue by anonn32** [SubtitleEdit/subtitleedit#7495]
Hey

As in Topic name. VLC have this possibility of slowin/speeding-up the playback of the video and maybe somehow it could be incorporated into SubtitlEdit program?

**Comment by uckthis** [comment]
![Untitled](https://github.com/SubtitleEdit/subtitleedit/assets/28671050/d2633ace-bd20-4046-8e46-400378d25c51)

**Comment by niksedk** [comment]
And you can setup shortcuts too:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/9f794d2f-c8db-4afc-8e71-5cd5c894124a)

**Comment by anonn32** [comment]
I can't believe how I've missed this icon 🤦‍♂️ 
Thanks @niksedk and @uckthis ,have a wonderful day.

**Comment by anonn32** [comment]
I can't believe how I've missed this icon 🤦‍♂️
Thanks @niksedk and @uckthis ,have a wonderful day.
