### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#75]
Add export statistic in [image-below], like saving it to text file....
![sshot-2](https://cloud.githubusercontent.com/assets/6579818/3003774/82d9d802-dd60-11e3-8adf-66234906d703.png)
PS: Sorry for selection above.

**Comment by ivandrofly** [comment]
Can be closed @niksedk | @XhmikosR

**Comment by XhmikosR** [comment]
@ivandrofly: I'm no longer a member of SE.

**Comment by niksedk** [comment]
Fixed in #449
