### ISSUE TITLE
Renaming bookmarks

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#7501]
Hello!
It wouldn't be nice if we could rename the bookmarks at this board?

![Book1](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/3205d280-9fa6-495d-8765-2fdcb11ebd0c)

**Comment by niksedk** [comment]
OK, latest beta has a context menu: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/bd6a7f1a-aaab-402e-8f50-84b079e204c4)

**Comment by Andrebavila** [comment]
> OK, latest beta has a context menu: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

It's perfect!
Thank you very much, @niksedk !
