### ISSUE TITLE
Monitoring Whisper progress information

### ISSUE THREAD

**Issue by es-maryland** [SubtitleEdit/subtitleedit#7502]
Ref:  "Suggestion to add an option to display Whisper progress information in a Command Prompt window #6955"

Great suggestion.  Just what I was looking for, but it's not intuitive to press F2 to check on task progress.  Suggest adding text to the window stating that pressing F2 will display the Whisper output.

**Comment by niksedk** [comment]
Normally (for me at least) the progress bar starts working after a while.

I've mentioned the "F2" on the help page now: https://www.nikse.dk/subtitleedit/help#audio_to_text (the page might need a Ctrl+F5 refresh)

**Comment by Purfview** [comment]
For faster-whisper you can use `-pp` argument to print the progress bar.
