### ISSUE TITLE
OCR not working.

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#7504]
Beta 198

![Untitled](https://github.com/SubtitleEdit/subtitleedit/assets/28671050/a2a1952e-ec90-41a3-b787-bb21271da399)

**Comment by niksedk** [comment]
Could you email/link/attach the file?

**Comment by uckthis** [comment]
https://rlsbb.to/the-great-british-bake-off-s14e03-1080p-web-h264-edith/

Release was The.Great.British.Bake.Off.S14E03.1080p.HDTV.H264-DARKFLiX

**Comment by niksedk** [comment]
Could you try extract the sub only or a small part of the file? Or does that not generate the crash?

**Comment by uckthis** [comment]
First few lines.

[ocr.zip](https://github.com/SubtitleEdit/subtitleedit/files/12867942/ocr.zip)

**Comment by niksedk** [comment]
Works fine here... did you try a clean beta (including all files) ?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by uckthis** [comment]
Yes, works fine. Old libse.dll was causing the issue.

Thank you.
