### ISSUE TITLE
Curious problem with RTX 2060 (WIN 11) Vs RTX 2060 SUPER (WIN 10)

### ISSUE THREAD

**Issue by Thiagobhmg** [SubtitleEdit/subtitleedit#7506]
Curious problem with RTX 2060 (WIN 11) Vs RTX 2060 SUPER (WIN 10)

Hello, I would like to know if someone can help me. I have two machines, the first one with an RTX 2060 (Lenovo Notebook, Legion 540 with WIN 11) and the second one with an RTX 2060 SUPER (WIN 10).

On the machine with the RTX 2060 (WIN 10), I run audio transcription and I see through Task Manager that the GPU usage is correct, being done by Faster-Whisper, with the GPU Load staying above 96%.

However, on the machine with the RTX 2060 SUPER (WIN 10), I see through Task Manager that the GPU memory is being used by Faster-Whisper, but the GPU Load doesn't go beyond 4%.

As can be verified in the image below.

https://prnt.sc/XJJoomJJtnKH

**Comment by Thiagobhmg** [comment]
Checking on other open issues, I noticed that some users reported that it worked with CONST-ME. And it really did work, even on the other card I have on the machine, which is a GTX 1070 Ti, so CONST-ME should work on the RTX 2060 SUPER. I believe it's something related to the CUDA drivers that are loaded along with Faster-Whisper on Windows 10.

https://prnt.sc/5fH5koNFI5Bn

**Comment by Purfview** [comment]
Probably it works OK where you think it doesn't and and it doesn't where you think it work OK.
You need to run it in console with `--verbose` to see what you are doing there.
