### ISSUE TITLE
drag rules in multiple replace 

### ISSUE THREAD

**Issue by Clarencezzh** [SubtitleEdit/subtitleedit#7509]
The multiple replace function is very useful and we need to sort the rules to make them worked.
But it's hard to sort them when the rules amount is more and more, just by "move up/down/to top/to bottom".
Is that possible to add the drag function for the multiple replace rules?
Thanks a lot.

**Comment by niksedk** [comment]
I have given rule drag'n'drop a try... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by Clarencezzh** [comment]
Thx, i have tried and the function is achieved in this beta version.
It will be better if we could have a cursor to lead drag & drop place.
Thanks again.

**Comment by niksedk** [comment]
Sorry, I don't know how to show a target cursor for drag & drop place

**Comment by niksedk** [comment]
Did you really just need a sort by the way?

**Comment by Clarencezzh** [comment]
No problem. It's just a suggestion,  not necessary. 
The drag & drop function in the beta version is already enough.
