### ISSUE TITLE
BD SUP editor: Add option 'Select unforced lines'

### ISSUE THREAD

**Issue by manuelrn** [SubtitleEdit/subtitleedit#7510]
Hello,

Currently there is already the option "Select forced lines", it would be ideal if there was also the opposite option.
This would be very useful to be able to select all non-forced lines and then delete them, resulting in a subtitle with only the forced lines.

Thank you very much ;)

**Comment by manuelrn** [comment]
Thank you very much @niksedk, as always very professional and very fast!

**Comment by niksedk** [comment]
You're welcome, and thx for the feedback :)
