### ISSUE TITLE
BD SUP editor: Improve option 'Change frame rate'

### ISSUE THREAD

**Issue by manuelrn** [SubtitleEdit/subtitleedit#7511]
Hi!

When using the "Change frame rate" option and apply a change of FPS, it would be ideal that the "Frame rate" property of the PGS subtitle is also automatically changed by the new frame rate that the user chose in the "To frame rate" option.

I don't know if I have explained myself well.... I am referring to the "Frame rate" option that is located to the right of "Video res".
Currently the user has to make a change of FPS with the option "Change frame rate" and then must manually change the "Frame rate" property by the new value, then it would be ideal that the latter is done automatically.

Thanks for all!

**Comment by manuelrn** [comment]
Thank you very much @niksedk, as always very professional and very fast!

**Comment by niksedk** [comment]
You're welcome, and thx for the feedback here too :)
