### ISSUE TITLE
The "Merge selected lines" command does not work with more than 3 selected lines?

### ISSUE THREAD

**Issue by Loriem** [SubtitleEdit/subtitleedit#7514]
I'm not sure if this is a issue, but on the other hand, I haven't found a solution, although it's quite possible that I'm doing something wrong in the first place.

The "Merge selected lines" command, called by Ctrl+Shift+M keyboard shortcut, does not work for me when three lines (and more) are selected. When two lines are selected, the command works as it should. But when three is selected, just nothing happens.

Tell me, can this be somehow fixed or configured?

**Comment by niksedk** [comment]
Could you attach screenshot and subtitle file?

SE tries to help, not allowing merge of too long lines... you can probably up "Single line max length" from 43 to e.g. 60.
