### ISSUE TITLE
BD SUP editor: Fix option 'Toggle "Forced" for selected lines'

### ISSUE THREAD

**Issue by manuelrn** [SubtitleEdit/subtitleedit#7515]
Hi!

When the user has several lines selected and clicks on the "Toggle "Forced" for selected lines" option, the operation is not correct since only the first selected line is toggled instead of all of them.

Thanks for all :)

**Comment by niksedk** [comment]
thx for the bug report :)

**Comment by manuelrn** [comment]
Thank you very much again for all your kindness @niksedk :P
