### ISSUE TITLE
Multiple Replace Cursor Placement and Sound Annoyances - Can We Fix It?

### ISSUE THREAD

**Issue by Firestorm2359** [SubtitleEdit/subtitleedit#7516]
Hey there! 😊

I've noticed a small thing since SE 4.0. When I use the find and replace feature (CTRL + H), the cursor starts on the "replace" line, and I find it a bit inconvenient to move it back to the "find" line each time. Also, it now plays the Windows "asterisk" sound every time it finds the next item, which can be a little annoying.

Any chance we could look into adjusting these two aspects? Would love to hear your thoughts on it! 🙏🤔

**Comment by niksedk** [comment]
Hm, replace does not do any of those things here...

**Comment by Firestorm2359** [comment]
I'm using the portable version, would this make a difference?

**Comment by niksedk** [comment]
Could you test latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by darnn** [comment]
The problem in the `replace` window persists: If you use the keyboard shortcut for replace, type something and then press Enter (without using the mouse at all), the windows asterisk chime will play, and if you continue pressing enter to go to the next result, it will continue to play. If you click `find` with the mouse, this doesn't happen, even if you just do it once to focus the `find` button and then press Enter again.

**Comment by Firestorm2359** [comment]
> Could you test latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

I did a quick test on the beta version, and it seems the CTRL + H dialog window doesn't appear at all.
 
I'm not sure if you noticed my edited message above, but it seems that enabling the dark theme might be triggering this issue on the main version. Can you check it out on your end?

**Comment by darnn** [comment]
What I wrote happens with both themes, for what it's worth, and the keyboard shortcut for the `replace` dialog does work for me in both.

**Comment by niksedk** [comment]
Ah, using only keyboard I get the 'ding' sound too... should now be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Yeah, seems to be fixed on my end.

**Comment by Firestorm2359** [comment]
> Ding sound is hopefully gone now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

My CTRL + H dialog box is still not opening.

**Comment by niksedk** [comment]
Ctrl+H works fine on my computers...

Could you have changed the shortcuts?

**Comment by Firestorm2359** [comment]
> Ctrl+H works fine on my computers...
> 
> Could you have changed the shortcuts?

I've been having a bit of trouble with the CTRL + H shortcut in the beta app. Sometimes it works fine, but other times, the dialog box doesn't open or I encounter a "Windows Forms Thread Exception" error. I haven't made any changes to the default shortcut. I also noticed that when I copy my settings file from version 3.6.13, the video window opens by default even though I turned this off in 3.6.13. Any ideas on what might be causing this?

**Comment by niksedk** [comment]
@Firestorm2359: Could you the post the "Windows Forms Thread Exception" error?
The layout stuff is a little different now - you choose one of 12 layouts via the layout picker.

**Comment by Firestorm2359** [comment]
> @Firestorm2359: Could you the post the "Windows Forms Thread Exception" error? The layout stuff is a little different now - you choose one of 12 layouts via the layout picker.

In SE3.6.13, with or without a subtitle file loaded, I hit CTRL + H on the keyboard (no mouse), and it correctly brings up the "multiple replace" dialog box with the cursor on the "find what" line.

Now, with a clean unzip of SE4.0.1 and no subtitle file loaded, the CTRL + H keyboard shortcut does nothing. However, when a subtitle file is loaded, I get the Windows error in the screenshot attached.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/140573813/10150fd1-1e86-4b38-8d3e-9601a3eb62c9)

**Comment by niksedk** [comment]
Sorry, I cannot re-create this... I will test on a few more computers.

**Comment by Firestorm2359** [comment]
Thanks for the advice! I tried reinstalling .NET Framework 4.8.1 and rebooting my PC, but the issue remains. I will just keep using SE3.6.13 and hopefully this resolves itself in a future version.
