### ISSUE TITLE
Crash during translation

### ISSUE THREAD

**Issue by davethabass** [SubtitleEdit/subtitleedit#7519]
!
![image](https://github.com/SubtitleEdit/subtitleedit/assets/147850468/3e4b432c-27e9-4b5b-af80-1426138bd9d6)

Hi, I was translating in SubtitleEdit using auto translate with a Microsoft Azure key when I got the attached error message. I have not had any other instances of this problem, after 20 or so successful translations.

Many thanks for a great programme.

Kind regards, Dave

**Comment by davethabass** [comment]
3 attempts made, always crashed at line 2159.

**Comment by niksedk** [comment]
This issue is hopefully fixed in the beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
?

**Comment by davethabass** [comment]
Nice new version, thanks for sending the link. I see you've added a lot of new translator options, great. When I went to add my Microsoft Translate key the box was greyed - I pasted the key anyhow and then couldn't see Microsoft Translate in the drop down translator list.
Also it didn't want to play videos from cue points, though it did play when positioned with the mouse cursor.
Hope this helps.

**Comment by niksedk** [comment]
OK, the play thing sounds like something else...
