### ISSUE TITLE
problem with whisper

### ISSUE THREAD

**Issue by nielka98** [SubtitleEdit/subtitleedit#7521]
Hey when using Subtitle Edit it turned out that Whisper has very big problems even if I use the largest model over and over again and over and over again and it generates one and the same word. Do you know how to fix it? Downloading the models again didn't help. The same as reinstalling the program .Please help me. I've been struggling with this for a week. I'd like to point out that I'm using whisper with the const-me engine

**Comment by Purfview** [comment]
Use Faster-Whisper.

**Comment by nielka98** [comment]
> Use Faster-Whisper engine.

and one more question, what if I have a problem installing cuda

**Comment by Purfview** [comment]
What problem? What is you GPU?

**Comment by nielka98** [comment]
Nvida geforce gtx 1060 6gb

**Comment by Purfview** [comment]
so what problem?

**Comment by nielka98** [comment]
I don't know, I just think my computer doesn't like this program... 
Is it possible to download this program manually?

**Comment by Purfview** [comment]
https://github.com/Purfview/whisper-standalone-win/releases

**Comment by Purfview** [comment]
> I don't know, I just think my computer doesn't like this program...

Then who knows? What you see on your PC?

**Comment by nielka98** [comment]
> Is it possible to download this program manually?

And once I download it cuBLAS and cuDNN so no Where What folder should I put it in?

**Comment by Purfview** [comment]
Not folder, but those dll files should be in same folder where whisper-faster.exe is.
