### ISSUE TITLE
How to get Japanese Furigana to show up in subtitles?

### ISSUE THREAD

**Issue by FlippFuzz** [SubtitleEdit/subtitleedit#7524]
I'm using ASS file format and am trying things like:
```
<ruby>規制<rt>きせい</rt></ruby>
```

I do see mentions of furigana in the code, but not exactly sure what is it doing.
https://github.com/SubtitleEdit/subtitleedit/blob/a1b8ab3d9e87a7da98ce129dbc922abe5200837c/src/libse/Common/NetflixImsc11JapaneseToAss.cs#L59

If it's not possible to do this using ASS format, I'm happy to switch to whichever subtitle format supports this.

**Comment by niksedk** [comment]
I think I talked with Netflix about this around 4 years ago, and then I stopped hearing from them... so this format was never finished.

The preview should be a little better here (requires mpv as video player): https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

Use the subtitle format called "Netflix ISMC 1.1 Japanese"
https://partnerhelp.netflixstudios.com/hc/en-us/articles/360034199033-Japanese-IMSC-1-1-Creation-Guide



(It actually uses ASSA behind the scenes)

**Comment by niksedk** [comment]
Alternatively, it could probably be possible to add a few ASSA helper tools for Furigana/Bouten.

**Comment by FlippFuzz** [comment]
Thanks, that is very helpful. We are almost there.
Furigana now shows up in the preview, but I can't correctly generate the burn-in subtitles.

---

### Selected string for demonstration
To demonstrate, I'm going to use the text in Figure 5 of https://partnerhelp.netflixstudios.com/hc/en-us/articles/360034199033-Japanese-IMSC-1-1-Creation-Guide

Base String： `力を集め新世界へのボータルを開く`
Ruby 1： `あつ`
Ruby 2： `しんせかい`
Ruby 3： `ひら`

The video is just blank.
Generate a blank video via Video -> Generate Blank Video... -> 1 min.

---

### Furigana shows up in the preview

Input to the Text Box in Subtitle Edit is:
```力を<ruby-container><ruby-base>集</ruby-base><ruby-text>あつ</ruby-text></ruby-container>め<ruby-container><ruby-base>新世界</ruby-base><ruby-text>しんせかい</ruby-text></ruby-container>へのボータルを<ruby-container><ruby-base>開</ruby-base><ruby-text>ひら</ruby-text></ruby-container>く```

![image](https://github.com/SubtitleEdit/subtitleedit/assets/41221030/03bf7fd9-5a19-4c23-891e-f3d6e834fa18)

It's also a little off-center, but not a big deal. 
I don't care about the preview as long as the final generated video is good,

---

### Furigana does not show up in the generated video

Video -> Generate video with burned-in subtitle
![image](https://github.com/SubtitleEdit/subtitleedit/assets/41221030/155b4049-df0c-4c29-806a-624478674d18)

Opening the generated video in VLC also doesn't help.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/41221030/96186f05-9411-42b9-9b87-52ebfc29b901)

**Comment by niksedk** [comment]
Beta updated a bit: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

The generate burn-in subtitles should hopefully work now:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/6cea7d63-abae-490e-9852-2227f4e7c652)


Also, if you change format to ASSA you will get the raw ASSA subtitle:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/268c4b00-5bbc-427a-bc83-2b8d99a9f4d0)

**Comment by FlippFuzz** [comment]
It's pretty good now, definitely able to generate the burn-in.
Sorry, for the bother, but there are two more smaller issues and I'm all set.

---

Issue 1: Is there a way to change the font size?
I've tried converting to ASSA and then adjusting the font size there, but the furigana is simply overwritten by the enlarged base text.
I think the positions are hardcoded when we change from Netflix to ASSA.

Change of colour works fine if I convert to ASSA (because this doesn't affect positioning).

---

Issue 2: Is there a way to center the furigana over the base text?

I'm referring to this portion:
`<ruby-base>新世界</ruby-base><ruby-text>しんせかい</ruby-text>`
![image](https://github.com/SubtitleEdit/subtitleedit/assets/41221030/51c6856b-4ec3-4ad2-b97e-aeacb3c7a73a)
`しんせかい` should be spread over `新世界` because the furigana represents the Kanji. Not aligned left.

It should look like:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/41221030/7c877a1a-dad3-43fd-9cbf-c7ff16678caf)


---

> Also, if you change format to ASSA you will get the raw ASSA subtitle:

Thanks!
I think I understand what is happening now.
SubtitleEdit is actually internally converting the "Netflix ISMC 1.1 Japanese" into ASSA. 
I can see a bunch of tags for positioning and so on (I'm far from an expert on what they mean).

**Comment by FlippFuzz** [comment]
@niksedk I'm starting that furigana is just too much effort.
I will just put it in brackets instead of having the text on top :)

Thanks for your help!

**Comment by niksedk** [comment]
@FlippFuzz: OK, thanks for testing :)
Sounds like a simple solution.

If you ever need some function in ASSA for Furigana do let us know.
