### ISSUE TITLE
How install WhisperX.exe?

### ISSUE THREAD

**Issue by DonKolia** [SubtitleEdit/subtitleedit#7525]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/55564649/1a411aa2-6d98-46da-8f46-418bf36bd57c)

Dont exist a Whisper.exe ....

**Comment by niksedk** [comment]
You can try to follow the instructions here: https://github.com/m-bain/whisperX

Note that e.g. Purfview's Faster Whisper or Const-me are much easier to install.

**Comment by DonKolia** [comment]
I did, i cant found whisper.exe

**Comment by DonKolia** [comment]
For this i am here

**Comment by niksedk** [comment]
If successfully installed you should be able to find `whisperx.exe` ...

**Comment by DonKolia** [comment]
Okay, send me the PATH Folder of Whisper.exe

**Comment by niksedk** [comment]
Search your HD

**Comment by DonKolia** [comment]
hahaha you don't know anything, you're a casper.
I hope you guys remove the WhisperX function in Subtitle edit, it doesn't work and doesn't exist.

**Comment by DonKolia** [comment]
Close this, this is ridiculous.

**Comment by lrq3000** [comment]
Contrary to other standalone bundled binaries such as Const-me's or Purfview's, WhisperX.exe is not yet distributed in standalone, but only as a [console-script](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html), a standard in Python to make Python scripts callable from the OS commandline directly. But so it is NOT standalone. You need to install Python and the whole AI ecosystem dependencies to run WhisperX first.

For more instructions, see: https://github.com/SubtitleEdit/subtitleedit/issues/6914
