### ISSUE TITLE
Faster-Whisper doesn't quit when you cancel transcription

### ISSUE THREAD

**Issue by Purfview** [SubtitleEdit/subtitleedit#7528]
It still runs in background after cancel.

If you use it alone in console, after CTRL+C it quits after it finishes a block, but with cancel in SE I waited and it never quit.

**Comment by niksedk** [comment]
When SE start Faster-Whisper, soon another process is started:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/0eadc508-d453-4953-9cfa-717fda3b0804)

I've tried with a `process.CloseMainWindow()` which does not work... the `process.Kill()` only kills the process SE started.

Is it possible to signal cancel to the whisper process?

Perhaps if the extra process was started as a child process it would work?

**Comment by cubicibo** [comment]
Whisper should terminate its spawned process when it gets a SIGTERM. Alternatively, Whisper should declare its subprocess as a daemon so any OS signal to the main process is passed along to its daemons.

**Comment by Purfview** [comment]
@cubicibo
Do you mean something should be written in Python script? If yes then can you link to some examples?

**Comment by cubicibo** [comment]
I don't know what you are doing in FasterWhisper. A daemon Process is declared like this:
https://github.com/cubicibo/SUPer/blob/dac0c86f783c496a8006a172271b6f6d451af1f9/supergui.py#L109
This should be enough to have the side process close when the main one is terminated.

If you can't use a daemon or would like to play safe, you need to set up a signal watcher like this: https://github.com/cubicibo/SUPer/blob/dac0c86f783c496a8006a172271b6f6d451af1f9/supergui.py#L232

And the registered callback should then pass down a signal to the subprocess using some means like an OS signal to the subprocess using the PID, or a command to terminate it like proc.kill()/proc.terminate(), and so on.

**Comment by Purfview** [comment]
Actually I don't do anything fancy, that child is how pyinstaller works I guess.
I'll try few things...

**Comment by cubicibo** [comment]
Oh? Then the bootloader of PyInstaller plays a role. This is relevant and may help you: https://pyinstaller.org/en/stable/feature-notes.html#signal-handling-in-console-windows-applications-and-onefile-application-cleanup

**Comment by Purfview** [comment]
@cubicibo Looked at that, as understand I don't need to do anything on Python part, no?

@niksedk Maybe there is something: https://github.com/microsoft/terminal/issues/11823
Or try `process.Kill(true)`, but this way it would leave bunch of temp files not cleaned up.

**Comment by niksedk** [comment]
`process.Kill(true)` is not available in dotnet 4.8. 

I've tried some ctrl+c code from stackoverflow... seems to work, but not nice code ;)

**Comment by Purfview** [comment]
Tested new beta, it works now, waits for block to finish then close processes.

Close would be cleaner, because when I run it in console and press "X" then it cleanly terminates both processes immediately.
Did you tried to generate "CTRL_CLOSE_EVENT"?

**Comment by uckthis** [comment]
Spares me from making a new thread, but for some time now, Whisper doesn't close after a batch conversion. You'd have to close SE via Task Manager. It's possible that as my SE runs in full screen, there could be an okay window which doesn't come to the front when batch is finished.
