### ISSUE TITLE
[LINUX] ASSA Tools > Set position.

### ISSUE THREAD

**Issue by PascalsHere** [SubtitleEdit/subtitleedit#7530]
It is completely broken. 
It seems like a mouse not updating position issue, as randomly it will update it.
[Screencast from 2023-10-16 21-46-05.webm](https://github.com/SubtitleEdit/subtitleedit/assets/71716875/a1b58c24-5c12-4941-b990-e27452235214)

**Comment by niksedk** [comment]
I think this might be a mono issue, sorry.
It's just a mouse move event on a picture box...

**Comment by niksedk** [comment]
OK, it should work now in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

The set position tool is now using a timer instead of a mouse move event... as a bonus it allows for a bit more movement of the text
