### ISSUE TITLE
New "re-calculate" shortcut 

### ISSUE THREAD

**Issue by ext666** [SubtitleEdit/subtitleedit#7533]
Hi, I would like to suggest a new keyboard shortcut based on "re-calculate". This one would override the in-cue of the next subtitle and move it forward including the minimum gap. This would be very useful when the overall sync is not precise.

**Comment by niksedk** [comment]
Is it this?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/efd5d694-44e8-46f7-a032-869e2756d838)

**Comment by ext666** [comment]
yes, but if you press these, the subtitle stops at the next in-cue. I would like it to move the next in-cue forward if necessary.  So basically "recalculate and and set start".

**Comment by niksedk** [comment]
`set start of the next (with the minimum gap)`

Could you like explain a lot more?

**Comment by ext666** [comment]
Sorry fot the confusion. These things are quite hard to explain. Hopefully the pics will help.

[https://i.imgur.com/eGRTGr7.jpg](url)

[https://i.imgur.com/XxPOdbg.jpg](url)

**Comment by ext666** [comment]
Sorry fot the confusion. These things are quite hard to explain. Hopefully the pics will help.
![](https://i.imgur.com/eGRTGr7.jpg)

![](https://i.imgur.com/XxPOdbg.jpg)

**Comment by niksedk** [comment]
Thx for the nice explanation :)

What should happen if the next subtitle would be too short after moving the start time?

**Comment by ext666** [comment]
Maybe nothing? :) I can press recalculate on the next one again if necessary.
