### ISSUE TITLE
to Purfview

### ISSUE THREAD

**Issue by nielka98** [SubtitleEdit/subtitleedit#7534]
How fix this :RuntimeError: CUDA failed with error out of memory

**Comment by niksedk** [comment]
Do attach the file `whisper_log.txt`... you probably need a gfx card with more memory. 
Which model are you using? You could try a smaller one.

**Comment by nielka98** [comment]
> Do attach the file `whisper_log.txt`... you probably need a gfx card with more memory. Which model are you using? You could try a smaller one.

[whisper_log.txt](https://github.com/SubtitleEdit/subtitleedit/files/13031105/whisper_log.txt)

**Comment by Purfview** [comment]
Then who knows? :)
Anyway, from your log I can see that it ran large model on some files without error, you can reduce memory usage by adjusting some parameters.

Try `-bo=1` parameter, with it program will use a bit less memory, if you still get the error then use `--temperature_increment_on_fallback=None`, these parameters would reduce accuracy a bit.

**Comment by nielka98** [comment]
I should use the commands you wrote for me in the program, right?

**Comment by nielka98** [comment]
ok, that's what I meant, but I think I did something wrong because I switched from GPU to CPU and I don't know how to reverse it

**Comment by nielka98** [comment]
![Zrzut ekranu 18-10-2023 18 59 20](https://github.com/SubtitleEdit/subtitleedit/assets/116809558/a7e2b810-08d3-4527-adbf-c04f23046433)

**Comment by nielka98** [comment]
But with the command you told me, it probably worked because it continues to generate the text

**Comment by Purfview** [comment]
Looks OK, if it used GPU before then it's using GPU now too.

Btw, you can force device with `--device=cpu` or `--device=cuda` parameters.

**Comment by nielka98** [comment]
ok

**Comment by nielka98** [comment]
ok

**Comment by JDTR75** [comment]
Let me use this thread to ask something about Whisper-Faster r160. I've been using r153 just fine and decided to update to the 160 version. But now it just doesn't do anything it gets stuck on "Starting transcription on..."
I downloaded the 160 version directly from Purfview rep. I had to downgrade to 153 and it's working again.
Thoughts?

**Comment by Purfview** [comment]
@JDTR75 What `--verbose` shows?

**Comment by Purfview** [comment]
`True`

**Comment by JDTR75** [comment]
Here you go:
[whisper_log.txt](https://github.com/SubtitleEdit/subtitleedit/files/13044663/whisper_log.txt)

**Comment by Purfview** [comment]
Did it program stopped by it self or you canceled it?
What if you use `medium` model?

**Comment by JDTR75** [comment]
It stopped by itself. Same thing with medium model.
[whisper_log.txt](https://github.com/SubtitleEdit/subtitleedit/files/13044862/whisper_log.txt)

This works fine with r153 and large model, just fyi.

**Comment by JDTR75** [comment]
I'm getting this from console now 🙃
`Could not load library cudnn_cnn_infer64_8.dll. Error code 126
Please make sure cudnn_cnn_infer64_8.dll is in your library path!`

And I have the libraries where they should be

**Comment by Purfview** [comment]
Make a screenshot of the console and the folder with faster-whisper.

**Comment by JDTR75** [comment]
Console: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1891941/0de6fda8-d69b-4866-aeb9-868e9afd5a5d)

Faster-Whisper folder:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1891941/21298fc3-79d1-4d6c-ab41-d76032697f5d)

**Comment by Purfview** [comment]
There is one dll missing.

**Comment by JDTR75** [comment]
You're right, `zlibwapi.dll` was missing. It worked from console with `medium`.
Another question, I'm running these tests on a separate SE instance - not the usual one I use. The only difference I can think of between the two SEs is the `ffmpeg` each one has. Could this be the reason?
The new and clean instance where I'm running the tests has ffmpeg is 6.0-essentials_build-www.gyan.dev
And the one I have on my usual SE instance is 5.1.2-full_build-www.gyan.dev

**Comment by Purfview** [comment]
Why it was missing? Didn't SE downloaded those libs automatically?

>Another question, I'm running these tests on a separate SE instance - not the usual one I use. The only difference I can think of between the two SEs is the ffmpeg each one has. Could this be the reason?

"The reason" to what?

**Comment by JDTR75** [comment]
Because I copied them from the ones I already have in my other instance.
The reason for not running. Could it be the different versions of `ffmpeg`?

I was further testing with the clean setup and `r160` still can't run the `large` model on this audio, but the the `r153` did. Here's what's happening, just fyi. And I can happily live with `r153` - just curious as to why this is happening.
https://github.com/SubtitleEdit/subtitleedit/assets/1891941/06964778-0c8c-4e4b-87bd-0117b1dc491f

**Comment by Purfview** [comment]
ffmpeg version can have influence -> https://github.com/SubtitleEdit/subtitleedit/issues/6946

And there is different compute type by default in r153 & r160 versions.
In r153 default is `int8_float32`, in r160 it's `auto` which on your gfx card defaults to `int8_float16`.
You can try `float16` to check which is fastest.

Btw, you are not the first who reported that they have issues with values over the thresholds with `int8_float16`.

**Comment by JDTR75** [comment]
Yes, I read that thread and that's why I asked you about `ffmpeg`. Will try with `--compute_type` now.
Having said this, would you recommend sticking to `ffmpeg` 5 or 6?

**Comment by Purfview** [comment]
Imo, stick to 5.

**Comment by Purfview** [comment]
@JDTR75 Could you share that audio where you had the issue with values over the thresholds with int8_float16?

**Comment by JDTR75** [comment]
Hey @Purfview ! Unfortunately, I can't - confidentiality reasons

**Comment by Purfview** [comment]
Could you then make few tests on that file?

**Comment by JDTR75** [comment]
Sure!

**Comment by Purfview** [comment]
> Sure!

Thx. First test if you can get same thresholds issue, then save old libs and repeat same test with some updated [libs_v2](https://wetransfer.com/downloads/1311caf3b70a4c2b310e443438ffcc8720231102171925/6a2c88), and then with [libs_v3](https://wetransfer.com/downloads/2e43652b7ad8e8c64914c0329c26f8bf20231102172208/41931b).

**Comment by JDTR75** [comment]
Got it. You want me to test it with int8_float16 exclusively?

**Comment by JDTR75** [comment]
Here you go. Both worked fine. I removed the actual transcription on each one.

[With libs_v2.txt](https://github.com/SubtitleEdit/subtitleedit/files/13244505/With.libs_v2.txt)
[With libs_v3.txt](https://github.com/SubtitleEdit/subtitleedit/files/13244506/With.libs_v3.txt)

**Comment by Purfview** [comment]
Thanks, could you make same "txt" with old libs?

**Comment by JDTR75** [comment]
[With libs_v1.txt](https://github.com/SubtitleEdit/subtitleedit/files/13244732/With.libs_v1.txt)

**Comment by Purfview** [comment]
Looks like some bug in older libs, I'll uploa updated libs. Thx, for tests.

Btw, all users who reported this issue are with "GTX 1650". :)

**Comment by JDTR75** [comment]
You're welcome! Thank you for double checking.
I have a qq. Is there a way (via command line or sth) to get the voices/speakers "marked"? I mean, like having a chevron >> or a hyphen - for when it detects the different voices/speakers.

**Comment by Purfview** [comment]
Not in mine project.

**Comment by JDTR75** [comment]
Got it. Thx for confirming
