### ISSUE TITLE
Merge short lines doesn't ignore music symbol.

### ISSUE THREAD

**Issue by RocketFriday** [SubtitleEdit/subtitleedit#7535]
When using merge short lines it break intro/outro music, which need to split lines based on verse/chorus; 
yet it doesn't ignore lines with music symbol as prefix/suffix and no option seems to exist for this.

Thank you.

**Comment by niksedk** [comment]
Could you give some examples?

**Comment by RocketFriday** [comment]
Oh...
I'm sorry.
I was converting CC into srt and in an attempt to show you an example, 
I see now that the _part_ of the intro subs were already broken in the CC _before_ subedit merged short lines. 
**My mistake.**
:( many apologies 🫂 

However, the issue still persists, because they were only _partially_ broken and subedit did break them more by unnecessarily merging short lyrics, I made an example for you:
![example](https://github.com/SubtitleEdit/subtitleedit/assets/24511919/f399442a-6446-4157-8300-ba1e9ef6d5c7)


P.S: Idk why the green highlight has such poor contrast, I'm sorry about that. I'm pretty sure that is my pc, not subedit.

**Comment by niksedk** [comment]
Hm, seems to work okay here:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/41875c77-c44b-4bba-a1db-34b74d852f13)


Could you attach your subtitle file?

**Comment by RocketFriday** [comment]
No, apparently: ![nope](https://github.com/SubtitleEdit/subtitleedit/assets/24511919/89055b9e-bab2-4018-abd0-febfa4a57d9b)
zip works tho?
[srt_and_screenshot.zip](https://github.com/SubtitleEdit/subtitleedit/files/13046884/srt_and_screenshot.zip)

**Comment by niksedk** [comment]
Thx for the file :)
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by RocketFriday** [comment]
All fixed! Thanks!

Unrelated question:
_So I was converting a CC into srt and most of the time subedit runs circles around my own code which is pretty impressive, but in this one scenario I gave up trying to figure out how to with subedit and just used my own converter.
Seeing as subedit helps me out so often, I was wondering if there's a way to give back without too much effort._

_The converter is written in python,
I know subedit is C# and while I work in C# daily, 
when it comes to everyday utility, I typically use python or ahk or both._

_It's meant for vtt => srt but right now I'm writing in support for whatever more generalized CC, because apparently srt is a common CC format._ 

**Question:** 
_When I'm done, is it worth sharing it here somehow? 
It's poorly written and will take someone to clean + convert it 
but it works as is and is probably a good headstart._

**Comment by niksedk** [comment]
Sure, do post it here :)
Improvements to SE are very welcome. 
I can read some python, and if I can debug it in VS code, then it's helps.

**Comment by RocketFriday** [comment]
I provided test material and it was too big for github so it's on my google [drive](https://drive.google.com/drive/folders/1CPGgpYFCaaHQbQc0A0Yb3vgjxnfKXmt2).
enjoy, and thanks again for the quick bug fix.
hmu, if you need anything.

**Comment by niksedk** [comment]
Thx for the files :)

Not too sure what to look for... does some of the files, show something that SE do not convert properly?

**Comment by RocketFriday** [comment]
Yes, in **'vtt_to_srt_testing\Result'**, I cannot find a way to get SE to turn 
_'vtt_to_srt_testing\Result\S01E02 - String_Theory [Original].srt'_ 
into 
_'vtt_to_srt_testing\Result\S01E02 - String_Theory [Converted].srt'_

If there is a way, please let me know where && how?


================


if you play 
_'vtt_to_srt_testing\Result\S01E02 - String_Theory [Converted]_**.mkv**'
with 
_vtt_to_srt_testing\Result\S01E02 - String_Theory [Original].srt_,
 you will see it's a mess.
However,
_vtt_to_srt_testing\Result\S01E02 - String_Theory [Converted]_**.srt**
is not. 

That's what **vtt_to_srt.py** does.

It's still not perfect but now, 
if you combine **vtt_to_srt.py** to clean the file 
and then SE to merge short lines, 
it is very close to a usable file.
