### ISSUE TITLE
Error in latest beta

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#7537]
Not sure how to reproduce this, I had SE open when I went to bed, and when I woke up I saw this:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/549b7d55-a0f4-4cef-8a21-e2a281d2ca52)

And when I clicked OK, SE closed.

**Comment by niksedk** [comment]
Does the file `error_log.txt` say anything related?

**Comment by darnn** [comment]
No, sadly. For what it's worth, the version I still have from late August, which I also had open, threw this error at what I believe was the same time (though I only saw it some time later):
![se old error](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/7183684b-1022-48e0-b632-8c5345f23807)
error_log.txt hasn't had any new entries in either since the 17th.
