### ISSUE TITLE
Remove text for Hearing Impaired could remove lines containg only musical symbols

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#7541]
After removal of Hearing impaired text, subtitles often still contain orphaned musical symbols.
Personally I like those removed, so I will do this in Notepad++

It would be nice if Subtitleedit could (optionally) deal with them.

**Comment by niksedk** [comment]
Could you attach a screenshot?
Could you attach a sample .srt file (Github supports .zip files)?

Could it be this, you were looking for?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/66b6c1a9-6522-4e77-a5ea-60406d682f31)

**Comment by fraternl** [comment]
I just tested that option.
It removes each line containing musical symbols.
It even removes the complete section of lines. (Do you want that at all?)

I merely want it to remove orphaned  lines with no text. Just musical symbols with other symbols.

**Comment by fraternl** [comment]
@niksedk 
Did I give you enough info or do you need more?

**Comment by fraternl** [comment]
Thanks I will let you know if it works as expected after I can download a new compiled version.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
I'm considering a new check box "Remove if only music symbols"... in case somebody want to keep them.

**Comment by fraternl** [comment]
Hi, Niksedk

Only just now I noticed it doesn't remove lines like this:

```
674
00:35:24,484 --> 00:35:26,550
<i>♪ ♪</i>

```

I assume the italic markers have something to do with it.

**Comment by fraternl** [comment]
Thank **_you_**!
