### ISSUE TITLE
Problem with .ASS and .MP4 container

### ISSUE THREAD

**Issue by ocrhell** [SubtitleEdit/subtitleedit#7543]
So I'm not sure if it is an issue on my end, but embedded .MP4 videos with .ASS subtitles just don't work.
In the preview of the player, the correct font/size/style etc... is displayed but when I generate video (.MP4) with embedded subtitles (.ASS), font/size/style are no longer what they were in the preview. I checked with MediaInfo and this is the outcome:
```
ID                                       : 3
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 6 min 42 s
Bit rate mode                            : Variable
Bit rate                                 : 61 b/s
Stream size                              : 3.02 KiB (0%)
Title                                    : English
Language                                 : English
Default                                  : Yes
Forced                                   : No
Alternate group                          : 3
```
Clearly it is not in .ASS
However when I use the .MKV container to generate embedded subtitles, I do not encounter this issue and the displayed subtitles are styled accordingly. This is the outcome:
```
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Duration                                 : 6 min 42 s
Compression mode                         : Lossless
Title                                    : English
Writing library                          : Lavc60.3.100 ass
Language                                 : English
Default                                  : No
Forced                                   : No
```
If I keep the .ASS externally and play the .MP4 file normally, the styling is displayed properly.

Also, would it be possible to batch generate video files after a batch Audio to text?

**Comment by niksedk** [comment]
Sorry, you cannot embed ASSA with original styring in mp4.
