### ISSUE TITLE
Trying to use WhisperX as Engine: no "whisperx.exe" file to locate

### ISSUE THREAD

**Issue by Kirk2ko** [SubtitleEdit/subtitleedit#7545]
Subtitle edit requests me to locate whisperx.exe file if I pick whisperX as an engine
but there is no such file on the downloaded whisperX folder from github (https://github.com/m-bain/whisperX)

Where do I get this file from?

**Comment by Purfview** [comment]
Read there: https://github.com/SubtitleEdit/subtitleedit/issues/7525

**Comment by niksedk** [comment]
WhisperX is extremely difficult to compile... read and follow the instructions very carefully from https://github.com/m-bain/whisperX 
You need Conda/Python/pip/git and probably more...

Afterwards following instructions you can search your hd for "whisperx.exe" like this:

````
C:\>dir whisperx.exe /s
````

Mine was here in `C:\Users\nikse\anaconda3\envs\whisperx\Scripts`

So, I recommend going the easy way and just use Purfview's Faster Whisper :)

**Comment by Kirk2ko** [comment]
> WhisperX is extremely difficult to compile... read and follow the instructions very carefully from https://github.com/m-bain/whisperX You need Conda/Python/pip/git and probably more...
> 
> Afterwards following instructions you can search your hd for "whisperx.exe" like this:
> 
> ```
> C:\>dir whisperx.exe /s
> ```
> 
> Mine was here in `C:\Users\nikse\anaconda3\envs\whisperx\Scripts`
> 
> So, I recommend going the easy way and just use Purfview's Faster Whisper :)

Thank you, will do.
