### ISSUE TITLE
Add command line option for using a reference ass file for stylings and ass attributes

### ISSUE THREAD

**Issue by Ninelpienel** [SubtitleEdit/subtitleedit#7547]
Hey, I want to use the command line convert option of SubtitleEdit but I noticed that I can't set stylings and other attributes of a ass file. It would be great if could specify a reference ass file for these settings.

Example: `SubtitleEdit.exe /convert file.ttml2 ass /ass-styling:"styling.ass"`

This should add every attribute and styling from the styling.ass file:

```
[Script Info]
Title: Some title
ScaledBorderAndShadow: Yes
YCbCr Matrix: TV.709
PlayResX: 1920
WrapStyle: 0
PlayResY: 1080

[Aegisub Project Garbage]

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,PT Sans,78,&H00FFFFFF,&H000000FF,&H00000000,&HB4000000,-1,0,0,0,100,100,1,0,1,6,1,2,100,100,70,1
```

**Comment by niksedk** [comment]
OK, does this work for you: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip ?

````
subtitleedit /convert a.srt assa /assa-style-file:styling.ass
````

**Comment by Ninelpienel** [comment]
Thank you, it works!

**Comment by niksedk** [comment]
Thx for reporting and testing :)

**Comment by Ninelpienel** [comment]
Okay, something is wrong. Other programs like [prass](https://github.com/tp7/Prass) can't handle the outputfile. But I can't figure out what's the difference to the batch variant. If I convert it directly with the batch function of the program, then it works.

Both output files: [Test.zip](https://github.com/SubtitleEdit/subtitleedit/files/13173985/Test.zip)

The error code from prass when I use the command line version:

```
Error: That's some invalid ASS script (no parse function at line 0)
Traceback (most recent call last):
  File "E:\User\Nino\_Tools\Programme\prass\prass.py", line 311, in <module>
    cli(default_map=default_map)
  File "C:\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "E:\User\Nino\_Tools\Programme\prass\prass.py", line 218, in tpp
    script.tpp(actual_styles, lead_in, lead_out, max_overlap, max_gap, adjacent_bias,
  File "E:\User\Nino\_Tools\Programme\prass\subs.py", line 427, in tpp
    events_iter = (e for e in self._events if not e.is_comment)
  File "E:\User\Nino\_Tools\Programme\prass\subs.py", line 279, in _events
    return self._find_section(EVENTS_SECTION).events
AttributeError: 'NoneType' object has no attribute 'events'
```

And is it possible to define a specific output file name?

**Comment by niksedk** [comment]
> And is it possible to define a specific output file name?

try `/outputfilename:<file name>` (for single file only)

**Comment by Ninelpienel** [comment]
Thank you! And I think I found the problem:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1890524/9738d03d-34db-49fe-b55a-9deb3352399b)

**Comment by niksedk** [comment]
OK, I can see that `TRS3-ger_04_command.ass` has a double BOM header... seems to need a fix

**Comment by niksedk** [comment]
Hopefully fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by Ninelpienel** [comment]
Is it possible to define that output files may be overwritten instead of writing a new file with "_2" in the name?

**Comment by niksedk** [comment]
> Is it possible to define that output files may be overwritten instead of writing a new file with "_2" in the name?

You could try adding `/overwrite`
