### ISSUE TITLE
Delete ASSA override tags entries

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#7548]
Is there a way to delete some of these entries?
And the space below 'em.......what is it for?

![E11](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/27a8b5af-7271-4afa-b4e6-37cd533ab2ba)

**Comment by niksedk** [comment]
OK, I will add delete by "DEL" key or context menu.

The bottom is just a preview, but probably not needed as must override tags will not be multi-line

**Comment by niksedk** [comment]
Included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
