### ISSUE TITLE
Size of 3D sup export

### ISSUE THREAD

**Issue by oallouch** [SubtitleEdit/subtitleedit#755]
My player needs the sup file to have the same width than the video file.
Is it possible to set the width of the 3D sup file export ?

Thx in advance,
Olivier

**Comment by oallouch** [comment]
Or do you know where I case find a doc explaining the .sup file format ? Maybe I can use a Photoshop batch to resize the images.

**Comment by niksedk** [comment]
It might be possible to add a 'full frame' check box... (is already used for some other formats) 
Would that help?

**Comment by oallouch** [comment]
Ooooh yeah ! That would help.

**Comment by oallouch** [comment]
Any news on that matter ?

**Comment by niksedk** [comment]
Could you test the fix?
If you don't want to compile from source try this: http://www.nikse.dk/SubtitleEdit.zip (portable beta)

**Comment by oallouch** [comment]
Hi,
My player is my Internet Box (from France) but they cut the fiber by mistake. I'll only be able to test it in a week (I hope). All I can say for now, using VLC on Windows 10, is that the export doesn't seem to use the font size and line height (at least for br tags).
