### ISSUE TITLE
Error when saving "Simple mode" settings while editing Beautify Timecodes settings (Edit profile)

### ISSUE THREAD

**Issue by leonardoschwider** [SubtitleEdit/subtitleedit#7550]
Hey guys,

While fixing the settings of Beautify Timecodes, I've noticed there's a Simple Mode button. Even more interesting is the "Load Netflix rules" - which should make the process even easier.

Despite that, I'm getting a "Windows Forum Thread Exception" error (image attached).

<img width="402" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/36590063/1106f5d0-a9c3-4c37-b8e0-cd00143a8db4">

This happens both when loading Netflix rules and when manually adjusting the settings. Changing the frame gaps from 3 to 2 and saving, for example.

Has anyone else faced this issue too? Any solutions?

Current setup: 
Subtitle Edit 4.0.1 running on Windows 11 Home (21H2) ARM Virtual Machine via Parallels Desktop 19 for MacBook Pro

**Comment by niksedk** [comment]
Thanks for the info - could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip ?

If it still crashes, please do attach the error again (as it should now have line numbers).

**Comment by niksedk** [comment]
Thx for testing... could you download latest beta and test once more?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

There should be some info logging in `error_log.txt` in the SE data folder - https://github.com/SubtitleEdit/subtitleedit/commit/be5e74881206fa94aac859509ed7fbc619e71ab5

**Comment by niksedk** [comment]
LOL, I was expecting an error again... well, do let me know if you see the error again.
