### ISSUE TITLE
Unable Removing "Font Name"s

### ISSUE THREAD

**Issue by PureOcean** [SubtitleEdit/subtitleedit#7554]
I encountered a subtitle in which the font names of each line were tagged with different style. I wanted to remove only the font names, not the aligment: `Select All -> Context Menu -> Remove Formatting > Remove font name`

Unfortunately, 'remove font name' doesn't work. Also 'remove alignment'. However, 'remove all formatting' works.

Examples of a few lines of the subtitle:

<p>
<details>

1
00:00:01,000 --> 00:00:03,120
{\pos(200, 80)\fnBookman Old Style\fs12}Lorem

2
00:00:36,260 --> 00:00:37,900
{\fnPalatino Linotype\fs16\3c&H000003&}Ipsum

3
00:01:59,023 --> 00:02:06,344
{\fnBastard\fs28\b1\c&H000000&\a6\3c&HFFFFFF&}Dolar

4
00:03:20,500 --> 00:03:24,450
{\pos(195, 100)\fnCentury\fs22}Amet

5
00:03:25,500 --> 00:03:29,450
{\fnCentury\fs22}consectetur

6
00:22:28,963 --> 00:22:31,760
{\a6\fnAtlandSketches BB\c&H0979A8&\3c&H000000&}adipiscing

</details>
</p>

**Comment by niksedk** [comment]
Included in latest beta: 
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by PureOcean** [comment]
@niksedk I just tried new beta build. Yes, `Remove -> Remove font names` now works. 

Thank you so much for you fixed the problem by coding [this](https://github.com/SubtitleEdit/subtitleedit/commit/858dfc814630bf51c7b738625424406e881b29dd) and [that](https://github.com/SubtitleEdit/subtitleedit/commit/c30bba2d11365e13253d7c92741b13d15508e7df). 

However, `Remove formatting -> Remove aligment` doesn't work. It is not important to me. I wanted to mention that because others could use it.

I also noticed that there are "font size" tags in the lines. Strange, because `\fs` tag belongs SSA format. However, I quoted the lines from an SRT-coded subtitle.

I know, "`font size`" feature not exist in "`Remove formatting`". Therefore, font-size tags also cannot be removed.

<pre>
<details>
<summary><b>Test For Remove Formatting; two subtitle line that contains alignment and font size</b></summary>

1
00:00:01,500 --> 00:00:04,500
{\pos(200, 190)\fs42}The font size of this line is 42. Also Position: 200, 190

2
00:00:04,600 --> 00:00:07,600
{\pos(250,270)}Only position line.
</details>
</pre>
