### ISSUE TITLE
[Feature Request] - CLI split long lines operation

### ISSUE THREAD

**Issue by BenJamesAndo** [SubtitleEdit/subtitleedit#7555]
Currently the CLI lets you run a number of operators such as `/RemoveLineBreaks` & `/BeautifyTimeCodes`. Would it be possible to also add `/SplitLongLines`? In the Batch converter it's called Split long lines or under the tools menu it's called Break/split long lines.

I'd anticipate the way it'd work is you set the single line maximum length & line maximum length in the GUI and then the CLI grabs those values similar to Batch convert. I don't need to specify different maximum lengths via the CLI.

My use case is for delivering .srt files to TV networks that have to conform to the [BCC Line length](https://www.bbc.co.uk/accessibility/forproducts/guides/subtitles/#Line-length) standards. So I'd like to use the command line to automatically fix up any files that go beyond 37 characters per line.

If this is already possible, please let me know. If not please consider adding this feature to the CLI.
Thanks!

**Comment by niksedk** [comment]
Good idea - `/SplitLongLines` should now be added in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

Let me know how it works.

**Comment by BenJamesAndo** [comment]
Tested and works perfectly. Thank you!

**Comment by niksedk** [comment]
@Sparviero-Sughero: Use something like `SubtitleEdit /convert "d:\My subs\2012\2012-05-03.srt" srt /SplitLongLines /outputfolder:"d:\My subs\2012"`

Read more here: https://www.nikse.dk/subtitleedit/help#commandline

If you run `subtitleedit /convert` it will display this:
````
Subtitle Edit 4.0.1 - Batch converter

- Usage: SubtitleEdit /convert <pattern> <name-of-format-without-spaces> [<optional-parameters>]

    pattern:
        one or more file name patterns separated by commas
        relative patterns are relative to /inputfolder if specified

    optional-parameters:
        /adjustduration:<ms>
        /assa-style-file:<file name>
        /deletecontains:<word>
        /ebuheaderfile:<file name>
        /encoding:<encoding name>
        /forcedonly
        /fps:<frame rate>
        /inputfolder:<folder name>
        /multiplereplace (equivalent to /multiplereplace:.)
        /multiplereplace:<comma separated file name list> ('.' represents the default replace rules)
        /ocrengine:<ocr engine> ("tesseract"/"nOCR")
        /offset:hh:mm:ss:ms
        /outputfilename:<file name> (for single file only)
        /outputfolder:<folder name>
        /overwrite
        /pac-codepage:<code page>
        /profile:<profile name>
        /renumber:<starting number>
        /resolution:<width>x<height>
        /targetfps:<frame rate>
        /teletextonly
        /teletextonlypage:<page number>
        /track-number:<comma separated track number list>

      The following operations are applied in command line order
      from left to right, and can be specified multiple times.
        /ApplyDurationLimits
        /BalanceLines
        /BeautifyTimeCodes
        /ConvertColorsToDialog
        /FixCommonErrors
        /FixRtlViaUnicodeChars
        /MergeSameTexts
        /MergeSameTimeCodes
        /MergeShortLines
        /RedoCasing
        /RemoveFormatting
        /RemoveLineBreaks
        /RemoveTextForHI
        /RemoveUnicodeControlChars
        /ReverseRtlStartEnd
        /SplitLongLines

    Example: SubtitleEdit /convert *.srt sami
    Show this usage message: SubtitleEdit /help
    List available formats: SubtitleEdit /help formats
````
