### ISSUE TITLE
Seeking Help: What Regex Engine Does Subtitle Edit Use?

### ISSUE THREAD

**Issue by Firestorm2359** [SubtitleEdit/subtitleedit#7557]
Could someone please tell me which regex engine Subtitle Edit uses? I couldn't find this information in the online docs. Thanks!

**Comment by niksedk** [comment]
The built-in engine into dotnet framework... from Microsoft.
There's an online tool that uses the same engine: http://regexstorm.net/tester

**Comment by Firestorm2359** [comment]
Thanks for the heads-up! I'm working on a regex for a "find and replace" task. My goal is to have the program identify "OK" at the start of a line or sentence and replace it with "Okay" with the correct case. If it encounters "OK" anywhere else, I'd like it to become "okay" in lowercase.

I've put together a two-part regex for this. If you have any insights on simplifying it into a single regex, I'd appreciate your advice.

**Part 1**

- Find what: (?<=[.!?]\s|^)OK
- Replace with: Okay

**Part 2**

- Find what: (?<![.!?]\s|^)OK
- Replace with: okay

**Comment by niksedk** [comment]
You can try using groups and replace groups ($1 $2 etc): https://www.nikse.dk/subtitleedit/help#multiple_replace

**Comment by Perkolator** [comment]
Just tested regex101.com and regexstorm.net, and it seems that SubtitleEdit uses Java 8 "flavor" of regex.

I tested a complex regex (85 chars long) which used a _variable width lookbehind_ (only Java 8 and .NET 7.0(C#) flavors work in regex101), and escaping a `"` character (regex101 .NET 7.0(C#) flavor needs an `"` to escape, and Java 8 needs an `\` to escape). The regexstorm.net site nikse mentioned works with a variable width lookbehind and `"` needs to be escaped with `\`. And I get identical result in SubtitleEdit. So, Java 8 flavor it seems to be.
