### ISSUE TITLE
FFprobe doesn't load exact frame time codes

### ISSUE THREAD

**Issue by LV8HDT** [SubtitleEdit/subtitleedit#7559]
Hi guys, basically what the title says.
I'm trying to beautify timecodes for a subtitle file. If I click on "Use FFprobe to extract exact time codes" it looks like the program is extracting them but in the end I just get "No time codes loaded"

![SubtitleEdit_EWyMHMRGwI](https://github.com/SubtitleEdit/subtitleedit/assets/83229405/e1eb6672-1f0b-4376-b0a5-f8defb5ebf88)

**Comment by niksedk** [comment]
Could you share the video file?

**Comment by LV8HDT** [comment]
Sure, [here it is](https://mega.nz/file/x0Jy3TCD#AyP4ObIsWjHgh3nBstkHas4-xacRH_Nm2mbBo2fQ81E)

**Comment by niksedk** [comment]
OK, this video has no audio tracks... 

@Flitskikker: Does this require an audio track?

**Comment by niksedk** [comment]
I've guessed a bit... is this beta better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by LV8HDT** [comment]
Actually no, it doesn't eve let me star analyzing the video
![SubtitleEdit_aAyeaDgGPi](https://github.com/SubtitleEdit/subtitleedit/assets/83229405/f871ae72-483b-4c26-a076-d4937bfbcf39)

**Comment by niksedk** [comment]
Did SE prompt for download of ffmpeg and ffprobe?

**Comment by LV8HDT** [comment]
Yes, as I clicked on "Beautify Timecodes" the prompt asking me to download ffprobe appeared. I clicked yes and it actually downloaded it in the ffmpeg folder, however, as you can see it's like if it wasn't downloaded at all

**Comment by niksedk** [comment]
Hm, I just downloaded the beta, went to options - settings, and download ffmpeg + mpv.
The opened your video, and clicked "Beautify time codes", seems to work here...

Can you reproduce the error with some steps?

**Comment by LV8HDT** [comment]
I take back what I sad. It works if I import/analyze shots and I apply them without timecodes, AFTER that if I click on "Beautify time codes" again the ffprobe option works fine.
