### ISSUE TITLE
Add new causes 0 ms overlap

### ISSUE THREAD

**Issue by Lorqu1n** [SubtitleEdit/subtitleedit#7560]
I am using the current version of SubtitleEdit on a new laptop and it's great software except this new bug... If I use "set end time" then "insert new at video pos" or ideally "set end, add new and go to new" then about 50% of the time the subtitles will flag as overlapping, with the same timestamp for end/start (not usually a problem). I have set my minimum gap to be 10 ms - same as on my old machine - but the problem happens on 0 ms and on 100 ms too. 
I can't find a pattern to when it happens, it doesn't seem to matter whether the video pos line is within the existing subtitle or further down the waveform. It's intermittant but seems to come in batches.
It's really slowing me down having to fix this with the mouse (drag new sub to the right and then back again). All of the settings I know of are the same as I was using on a previous edition. 

Edit: Just realised it's easily fixable later with the "apply minimum gap between subtitles option" so not a crisis, but it's still an odd bug. Youtube freaks out if there are overlaps in an .srt file unfortunately.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/149019827/9b68e362-ff93-47ed-9572-bb05bca380c0)

**Comment by niksedk** [comment]
I'm not really sure what the problem is... could you explain more?

`insert new at video pos` will insert the video at the current video position - no mater where.
If you want a subtitle after current subtitle, use `insert after`.

**Comment by Lorqu1n** [comment]
Sorry, I'm not explaining very well! I typically have back-to-back subtitles with no gap between, so I will play the video to where I want the subtitle to end and use my keyboard shortcut for "set end, add new, go to new". This has always worked perfectly, ending the subtitle and with 0 gap adding in the new one and going to it. 

At the moment, this works about 50% of the time. The rest of the time, it works except the two subtitles are flagged as overlapping by 0 ms. It's only a problem if I'm asking for back-to-back subtitles. If there's a gap in the speech I can use "insert new at video pos" and it's fine. 

Looks like "insert after" doesn't suffer the same problem, but would be two steps (+ end current) where previously I could use one. Good to know though!

**Comment by niksedk** [comment]
I've changed it a bit, so "set end, add new and go to new" is only allowed if the duration will be between min-ms and max-ms (from settings).

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/7e768864-7f35-4e6a-986e-e162ddd4c021)

Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

Does this work better for you?

If you right-click in the list-view-column-header, you can show gap as a column which makes testing this easier:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/b9749020-a5dd-41de-9707-98dcb082e32d)

**Comment by Lorqu1n** [comment]
Hi,

Thanks so much for working on this, you're a legend. I tested the two versions, the previous one had 2 of these errors in 10 subtitles, the new version had one error. There has been a development though, when I reopened the old file to screenshot the differences, the error messages had all gone. Saved and reopened the new version and the same thing happened. So the error message disappears if the file is closed and opened again.

FYI, the gap error appears as -0.000
![image](https://github.com/SubtitleEdit/subtitleedit/assets/149019827/bbb317ac-0cef-4b5b-9707-e2fed6572f4c)

If a close and open is all I need to do then I'm satisfied with that, confused, but satisfied!

**Comment by Lorqu1n** [comment]
I haven't found an exact trigger which is frustrating. The video is paused. It happens for "set end, add new, and go to new" it also happens with "set end" "add new" done separately. The length of the subtitle and char/sec doesn't seem to affect it. If I undo then try again, the problem repeats. It happens when the video position is inside or outside the last subtitle (aka if I'm shortening or lengthening the subtitle with "set end").

It doesn't happen on my other laptop running an older version (I can look this up in a couple of days). That one is win 10, this is win 11.

This is a little cluster of them, no pattern that I can see. Sometimes come in clusters but not always. And yes, those char/sec are awful but this is 5 people who all like to talk fast and on top of each other!
![image](https://github.com/SubtitleEdit/subtitleedit/assets/149019827/f29aa34c-a811-4d90-8b0a-6e26d14ad694)

**Comment by Flitskikker** [comment]
> I've changed it a bit, so "set end, add new and go to new" is only allowed if the duration will be between min-ms and max-ms (from settings).

@niksedk 
Could this change please be reversed? I use this shortcut all the time when spotting, and now the shortcut doesn't do anything when the selected subtitle (left-hand side) will be shorter than my minimum, or longer than my maximum. But that is what I want in some cases: I might want to split it or merge it with another subtitle later. This is a workflow-breaking change for me.

An alternative could be a separate shortcut that does the following:
- Add a new subtitle at the current position
- Set the end of the selected subtitle to the start of the new subtitle minus gap
- Go to the next (the newly added) subtitle

It should do this even if the selected subtitle (left-hand side) ends up being 0,1 seconds or 20 seconds. I feel that this is my own responsibility.

When undoing, the previously selected subtitle should be selected again, as before with the current shortcut (which selects the next subtitle now).

(This is what I had been using this shortcut for.)

**Comment by niksedk** [comment]
> > I've changed it a bit, so "set end, add new and go to new" is only allowed if the duration will be between min-ms and max-ms (from settings).
> 
> @niksedk Could this change please be reversed? 

Sure, it now allows > 0 and <= 60 seconds: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

Have you seen the gap problem in this issue?

**Comment by Flitskikker** [comment]
@niksedk 
Thank you!

The shortcut now works again, but strangely enough doesn't produce the desired result all the time.

An example:

Starting point:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/2b8fb623-69f3-4458-af57-d56777dad741)

Pressing the "set end, add new and go to new" shortcut:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/ccc89f1f-e4b4-4f59-9511-2baf5889d84b)

But elsewhere in the subtitle, it correctly shortens the left subtitle (minus gap).

---

Test file to reproduce:

[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/13210064/test.zip)

Selecting "We zijn neergedaald..." halfway and using the shortcut produces an overlap.
But selecting "Test1" halfway and using the shortcut correctly shortens the left subtitle.

<details>
<summary>Click for my settings</summary>

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/c5df3148-11c9-47e1-9825-a672697f07a1)
</details>


Perhaps it's related to OP's problem?

**Comment by Flitskikker** [comment]
I tried out OP's scenario by setting my minimum gap to 0 msec and then creating new subtitles back-to-back using the "set end, add new and go to new" shortcut in the waveform, and I'm indeed seeing the same thing on the latest beta:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/7f7992cf-8680-4e74-aaa2-0352d6bee852)

Saving and reloading the file shows the actually created gaps. Apparently, it's creating actual overlaps (-0,001) and gaps larger than the set 0 msec (0,001):

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/32e68e6e-ffe2-47a5-860c-eab08350e9f9)

Changing optimal / maximum CPS or minimum duration doesn't seem to have an effect.
Maybe it's some rounding issue when converting waveform pixels to msec?

**Comment by niksedk** [comment]
OK, I could re-create the issue here too now :)

How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

Tried to fix the overlap + fix "-0.000" displayed in gap

**Comment by niksedk** [comment]
And this one is hopefully better: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by Flitskikker** [comment]
@niksedk 
Finally had time to check the new build today.

The varying gap when creating subtitles using the "Set end, add new and go to new" shortcut seems to be fixed!

Some things I still noticed:

- The created subtitle is always 2 seconds, while my minimum is 1,4 seconds.
- Auto duration is not active after creating, but that may be deliberate?
- When the gap is >0, it doesn't add it, but moves the new subtitle backwards.

Beginning:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/cb5ec053-e221-4ff6-9145-452ef7ed929e)

After pressing the shortcut (gap set to 120 ms):
![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/485a4731-d800-4575-ae7b-aacc2960ee52)

Expected result:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/f5dac57c-f7cc-4581-9b91-33ce8eb94f4a)

**Comment by niksedk** [comment]
@Flitskikker: thx for testing :)
1) Inserting uses the const `NewEmptyDefaultMs`
2) Auto-duration is now on
3) Should be respect the `min gap`

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by darnn** [comment]
I'm not sure if this is quite the same thing, but it seems relevant: When inserting a new subtitle between two subtitles that have a very short gap between them, you get a subtitle with a negative duration.

Before:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/fee0fc57-3498-4af1-902f-f7c93548fee7)

`703`
`01:24:23,959 --> 01:24:29,916`
`I'm still waiting`

`704`
`01:24:29,940 --> 01:24:31,696`
`Thank you.`

After:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/2bd3f365-8db0-4973-b22b-66d56eff06d9)

`703`
`01:24:23,959 --> 01:24:29,916`
`I'm still waiting`

`704`
`01:24:29,940 --> 01:24:29,916`


`705`
`01:24:29,940 --> 01:24:31,696`
`Thank you.`

And while we're on the subject, I wish there was an option to have the new subtitle, when you insert it, always have a timecode of all zeros:

`704`
`00:00:00,000 --> 00:00:00,000`

Because as it is, I have to manually change the timecode to that each time (though I have a script that automates the keypresses), and I do this every time I'm working with something that already has timecodes where I'm adding new subtitles (which is often).
