### ISSUE TITLE
about layout

### ISSUE THREAD

**Issue by drumachine** [SubtitleEdit/subtitleedit#7562]
Hey,
How can I back old layout in last version "Subtitle Edit 4.0.1"?
https://prnt.sc/Xqq9UUVMza4J

Thanks for great works...
D.
![layout](https://github.com/SubtitleEdit/subtitleedit/assets/49017044/020f074f-360b-4d9c-a12f-88f703219a4f)

**Comment by darnn** [comment]
If you're talking about the icons, Options->Settings->Appearance->Graphics buttons.

**Comment by drumachine** [comment]
> If you're talking about the icons, Options->Settings->Appearance->Graphics buttons.

Yes, that's it. 
Thanks for information.
D.
