### ISSUE TITLE
Ignoring interjections

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#7563]
I see that in versions since September, interjections have been moved into their own xml file. In en_interjections_user.xml, I see there's an ignore section:
`  <ignore>`
`  </ignore>`
How do I add things to it? Specifically, if I want to add a phrase? It always bugs me that it tries to remove the "oh" from "oh my god".

**Comment by niksedk** [comment]
You should just go into "Remove text for hearing impaired", and press edit:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/8114ee32-1936-468f-8aa0-2d9fdc39455c)

Here you can remove `Oh`... it's not possible to ignore "oh my god" atm...

**Comment by niksedk** [comment]
OK, how is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/67535834-34d7-43e4-bd78-69220c23f702)
