### ISSUE TITLE
Translation Form Problem

### ISSUE THREAD

**Issue by salmarenami** [SubtitleEdit/subtitleedit#7564]
I found a problem when translating subtitles from English to Indonesian.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/133254337/8c5bb845-8b28-4dd2-9d65-a9218f1e5219)

[https://yifysubtitles.ch/subtitle/where-are-you-christmas-2023-english-yify-564897.zip](url)

**Comment by niksedk** [comment]
Sounds line an internet connections problem... auto-translate is re-written in latest beta, could you try that: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by salmarenami** [comment]
Currently the process is going well, thank you for your help.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/133254337/a08b64e4-9e3f-4e28-b95c-c64b88cdce54)
