### ISSUE TITLE
Auto-translate some encoding problem

### ISSUE THREAD

**Issue by Purfview** [SubtitleEdit/subtitleedit#7565]
![alt text](https://i.imgur.com/HXIGV7u.png)

**Comment by niksedk** [comment]
Do you have `    <UseLegacyDownloader>False</UseLegacyDownloader>` in `Settings.xml` ?

**Comment by Purfview** [comment]
It's `True`. I set it to `False` and now it shows translations properly.
Why `UseLegacyDownloader` affects this?

**Comment by niksedk** [comment]
The LegacyDownloader is for some Windows 7 users where SSL/TLS is not configured probably (could be win8 too)...
And I'm afraid, that the LegacyDownloader cannot force UTF-8, so I do not think I can fix this.

I guess the LegacyDownloader could be removed in a year or too.

**Comment by Purfview** [comment]
> The LegacyDownloader is for some Windows 7 users where SSL/TLS is not configured

But in my Win7 it's configured to use TLS 1.2.

Does SE sets LegacyDownloader to True silently? Could you make some confirmation pop-up?

**Comment by niksedk** [comment]
When SE switches it will add this line to the "error_log.txt": 
`Switching to legacy downloader due to old OS!`

**Comment by niksedk** [comment]
I guess removing the legacy download could be a good idea... as it's not working correctly anyway.
