### ISSUE TITLE
Error starting MS Translate

### ISSUE THREAD

**Issue by davethabass** [SubtitleEdit/subtitleedit#7568]
Hi, I went to use MS Translate having just installed SE 4.0.1.0 and got the attached error. Thanks for a great piece of software, I use it regularly. 
Kind regards, Dave.

<img width="594" alt="Screenshot 2023-10-27 181827" src="https://github.com/SubtitleEdit/subtitleedit/assets/147850468/bce2b71b-0a2f-4c8a-afc7-53ad30fe7b4b">

**Comment by niksedk** [comment]
Hi Dave,

thx for your issue. Hopefully it's fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
(auto-translate re-written in the beta)

**Comment by davethabass** [comment]
Thanks, I'll try it tomorrow and comment here.
