### ISSUE TITLE
Issue when generating shot changes for SMPTE or HH:MM:SS:FF files

### ISSUE THREAD

**Issue by leonardoschwider** [SubtitleEdit/subtitleedit#7572]
Hey guys,

I'm wondering if anyone's facing the same issue. While creating subtitles for a HH:MM:SS:FF video (rather than milliseconds), I've noticed the shot change generation doesn't really work in frames.

It seems like the shot change generation with FFmpeg creates shot changes in milliseconds by default, not frames, so upon completion, the shot changes don't really match the video. Seems to be quite a few frames off.

Has anyone dealt with this before? Is there a way to generate the shot changes in frames? How did you solve this?

P.S: As a workaround, I'm generating the shot changes using another software and importing them in frames to Subtitle Edit, that seems to do the trick.  I have the SMPTE setting enabled, as well.

**Comment by Talzuz** [comment]
What was your workaround program for this? This is driving me crazy, I can't imagine trying to manually adjust subtitles at each shot change.
