### ISSUE TITLE
Libvosk error on Linux Mint

### ISSUE THREAD

**Issue by TheCheddarCheese** [SubtitleEdit/subtitleedit#7575]
![billede](https://github.com/SubtitleEdit/subtitleedit/assets/124603704/02ca5321-1255-4fd9-ac78-02e60f471797)
I can't use whisper either but there it's some audio file not being found

**Comment by tariq0101** [comment]
yeah I had the same error on LMDE, I had to dual boot windows just to use SubtitleEdit there.
