### ISSUE TITLE
Two bugs: appearance reseting & double space with autobreak

### ISSUE THREAD

**Issue by matmaggi** [SubtitleEdit/subtitleedit#7576]
Hello, I found 2 minor bugs on version 4.0.1 Portable (Windows 11).

---------

First: everytime I open Subtitle Edit, the layout is like this (bold and not Arial, which is selected)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/48259053/ccca20ae-90f0-4f12-bd81-f27a8b01c2a1)

But the appearance settings is like this:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/48259053/5c67a5ba-466f-4944-809c-9bb61b312b85)

To fix, I always have to open Settings, select Bold, click Ok, then go back there and unselect Bold. But the next time I open Subtitle Edit again, it's in bold again.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/48259053/d2f5f468-6c90-4851-bc9f-3210d35dd12f)

---------

Second: in the previous versions, when I had double spaces and did an autobreak, the space was corrected, but now this doesn't happen.

Eg:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/48259053/d730147a-0324-42ad-a120-f811b854b82b)

Should be like this after autobreak:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/48259053/d8179e74-1c23-4cc7-895a-f40897a7b576)

But it does this:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/48259053/47aa9789-266f-400d-9e0e-214e9356e150)

Thank you!

**Comment by niksedk** [comment]
Thx for the bug report :)

How is this beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by matmaggi** [comment]
Thank you. Everything workis fine now!

**Comment by niksedk** [comment]
Thx for testing :)

**Comment by rRobis** [comment]
@niksedk Could additionally check for these types of double spaces, when there is a tag in between:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/127ea2d4-b47c-4987-9539-dc1c4bb0295e)
