### ISSUE TITLE
ASSA: Replace multiple styles with one click

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7577]
It would be even better to allow the "Replace with.." feature to show up when multiple styles are selected that are supposed to be replaced with a target style. :)

![replace](https://github.com/SubtitleEdit/subtitleedit/assets/494788/4671e939-b7c2-4425-9d89-e3ad998b8d03)

**Comment by niksedk** [comment]
Thx - good idea :)
Should be fixed in latest beta now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Great, thx!
