### ISSUE TITLE
29,97 FPS video - Grid bug

### ISSUE THREAD

**Issue by matmaggi** [SubtitleEdit/subtitleedit#7578]
SE 4.0.1 - Windows 11

When working with 29,97fps, SE detects the video as 29,97...
![image](https://github.com/SubtitleEdit/subtitleedit/assets/48259053/1af41fee-f838-4ad4-85ba-cc27eec51aee)

But the grid is working as 24fps (from 23, it goes to 00, not 24-29)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/48259053/348713b2-2aa2-4d8f-9f03-bfc89d34e3d0)

Maybe this happens with 25fps/30fps as well (I haven't tested it)

Thank you.

**Comment by niksedk** [comment]
I think this has already been fixed in latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by matmaggi** [comment]
Oops, my bad! I just tested. Indeed, it is fixed.

Thanks for your time!
