### ISSUE TITLE
SUP's palette is missing

### ISSUE THREAD

**Issue by mojie126** [SubtitleEdit/subtitleedit#7579]
When saving as SUP, the palette will be missing. Upon checking the code, it should be channel A of the image>0 before adding palette information

**Comment by niksedk** [comment]
Please supply more info - read more here: https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by niksedk** [comment]
Could you add some screenshots of what you see?

**Comment by niksedk** [comment]
> [re_1.zip](https://github.com/SubtitleEdit/subtitleedit/files/13225702/re_1.zip) For example, for this SUP, I used SupRead to see that the first one had 93 color palettes, but after re saving with SE, there were only 61. I don't know what the impact was

It's probably because SE removed unused colors from the palette...
