### ISSUE TITLE
Stable-ts with purfview faster whisper ?

### ISSUE THREAD

**Issue by Martyprod** [SubtitleEdit/subtitleedit#7585]
Hello, 

Not sure it's an issue, just trying to figure out how to make stable-ts working with purfview faster-whisper, (by hoping it does better subtitles sync than without it lol), it seems that actually , when selecting stable-ts, it use only the normal whisperX one. Thx !

**Comment by niksedk** [comment]
Stable-ts ( https://github.com/jianfch/stable-ts ) and purfview faster-whisper ( https://github.com/Purfview/whisper-standalone-win ) are different projects...

You can check the file `whisper_log.txt` in the SE data folder to see the actual commands / info.
"Stable-ts" is enabled in latest beta (but you need to compile it yourself via Python etc.): https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by Martyprod** [comment]
Hi, thanks for the reply but it was not my issue.

1/ already running beta since a long time. i have a 1050ti. it work well since the update allowing Faster Whisper running with int8 (before it was not working certainly due to the limit of the card). i can run the Large v2 model on it with an acceptable time, which is amazing. but the issue is still a lack of great timestamp for the result. then i saw the update in the beta about stable-ts.  so it lead to : 

2/ already downloaded stable-ts, found the stable-ts.exe in the script folder of anaconda3 here : 
"C:\Users\***\scoop\apps\miniconda3\23.3.1-0\Scripts\stable-ts.exe"

 already tried it in beta, but no matter what i try, unfortunately lead to a 0 bytes file. and only a large model is available in the list. is it less better than the v2 ? would love to give it a try, but don't know what to do from there. thanks.

and you're the dev behind subtitleedit, so i take the opportunity to thank you a lot for this software ! i'm hearing impaired, but thanks to you, you allow me to watch and see stuff now that i could'nt since 30 years !
