### ISSUE TITLE
Auto-translate messing characters up

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#7586]
Subtitle Edit 4.0.1.345

Again.
I've tried translate english to portuguese and this happens.

![e02](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/5b098d7d-742f-4a86-bdfd-8d6d69f7b5a5)

And, please, whenever I want to use the auto-translate, the option "to" is always "Spanish".
It could be possible SE remember our last choice (portuguese, for me)?

![e4](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/b03bc4a4-ebdb-4ec6-89d3-dc26c4ac9dd5)

**Comment by niksedk** [comment]
What OS are you using?

**Comment by Andrebavila** [comment]
> What OS are you using?

Windows 7

**Comment by niksedk** [comment]
Is this any better? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by Andrebavila** [comment]
> Is this any better? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

It's perfect!
Thank you!
