### ISSUE TITLE
Error runtime to choice a shorcut maybe press keys shift+F10 in wrong window prompt?

### ISSUE THREAD

**Issue by Ronaclo** [SubtitleEdit/subtitleedit#7587]
![deception](https://github.com/SubtitleEdit/subtitleedit/assets/128189996/fd3dcc60-3032-4da2-94e6-c06119f92ef9)

a Problem that appeared suddenly to choice a shorcut for sub edit.

Specificaly shift + F10

NOW each time I open the program appear this message, now and I do not know  to do.

I will be reinstall the program. again.

**Comment by niksedk** [comment]
Works fine here... could you attach or email your settings.xml file?

**Comment by Ronaclo** [comment]
Maybe it was a computer error, I suppose these things happen suddenly and are fortuitous, at the moment it doesn't seem like the program is damaged, it continues to work after installing the portable version. Thanks for your attention.
