### ISSUE TITLE
Bloq Num ON block the Shorcut Commands in Sub Edit

### ISSUE THREAD

**Issue by Ronaclo** [SubtitleEdit/subtitleedit#7588]
This for me is a problem because I have to press block num in off for can this way use the shorcuts, 

dont you repare this incovenient? 

That works the shorcuts in ON as in OFF state  the yellow light in the key Block Num.

Thanks.

**Comment by niksedk** [comment]
Could you explain a little more? Screenshots would be nice.

**Comment by Ronaclo** [comment]
_Just the buttons shorcuts works with the block num in off, the problem must be because I use the mouse in the keyboard and these keys are blocked when activate in on the block num key._ 

**The shorcuts that I use are in where are the numbers 0-9, /, *,-, + and Intro key, as well it's where the num block key is found.**
