### ISSUE TITLE
SubtitleEditBeta Microsoft Translator API Error

### ISSUE THREAD

**Issue by LordOfTurk** [SubtitleEdit/subtitleedit#7591]
I am trying to translate with Microsoft Translator API but I get the following error.

Parse error: input contains no value.
   konum: Nikse.SubtitleEdit.Core.Common.JsonParser.Value()
   konum: Nikse.SubtitleEdit.Core.Common.JsonParser.Parse(String text)
   konum: Nikse.SubtitleEdit.Core.AutoTranslate.MicrosoftTranslator.Translate(String text, String sourceLanguageCode, String targetLanguageCode)
   konum: Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__0.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__21.MoveNext()

**Comment by LordOfTurk** [comment]
'System.Collections.Generic.Dictionary`2[System.String,System.Object]' türündeki nesne 'System.Collections.Generic.List`1[System.Object]' türüne atılamadı.
   konum: Nikse.SubtitleEdit.Core.AutoTranslate.MicrosoftTranslator.Translate(String text, String sourceLanguageCode, String targetLanguageCode)
   konum: Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__21.MoveNext()

**Comment by niksedk** [comment]
I've improved the error handling a bit in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

How does that work for you?

**Comment by niksedk** [comment]
SE already uses V3
