### ISSUE TITLE
I implore you once again - Language List in OCR Fix

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#7592]
![SElist](https://github.com/SubtitleEdit/subtitleedit/assets/72777/b0fc1f17-96d8-4f07-b1bb-89f5faa5f0e5)

I implore you once again - to fix this list of languages in OCR fix - to shorten it only for languages that are actually there - in Subtitle Edit.
Because it's a big time waster to browse for my language every time.

## OCR now has not even 20 languages and list is made of over 100 of them. So unnecessary! 

**This HAS TO BE SHORTENED. 
PLEASE!**

**Comment by diomed** [comment]
IT would also be good if we could select our language and it would stay that way in settings.

**Comment by niksedk** [comment]
It's already in latest beta:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/459fee02-b216-41bf-9704-251201ac7eba)
