### ISSUE TITLE
Unable to download faster-whisper r153.zip

### ISSUE THREAD

**Issue by MyKareee** [SubtitleEdit/subtitleedit#7599]
This is my first time, writing issue... Please let me know if more information is needed

My internet is okay.. but when i click to download Purview Fast Whisper .. picture below pop up...

![error](https://github.com/SubtitleEdit/subtitleedit/assets/116965857/68c9dd33-1193-41d8-9996-5bd86d525a9b)

I already downloaded the file manually, where should i put it

Thank You

**Comment by MyKareee** [comment]
Windows 11

**Comment by Purfview** [comment]
And what Subtitle Edit version?

**Comment by MyKareee** [comment]
Yes... subtitle edit 4.0.1..

**Comment by Purfview** [comment]
Hmm, maybe internet is blocked by firewall?

Here is folder for it: `Subtitle Edit v4\Whisper\Purfview-Whisper-Faster\`

**Comment by MyKareee** [comment]
Aight so i just need to extract the zip file into the path right ?

**Comment by Purfview** [comment]
> Aight so i just need to extract the zip file into the path right ?

No! You need to have the program in the path.
