### ISSUE TITLE
If Purfview's Faster-Whisper crashes, partial output not handled properly, utf-8?

### ISSUE THREAD

**Issue by oniongarlic** [SubtitleEdit/subtitleedit#7600]
When Purfview's Faster-Whisper crashes (In my case, RuntimeError: CUDA failed with error out of memory, anyway) the partial output is not handled correcly, all ÖÄÅ etc are black ? marks.
If it runs properly to the end without crashing, the the output is fine.

**Comment by Purfview** [comment]
Better reduce memory usage, try `-bo=1`, if that doesn't help then try `-bo=1 -bs=1`.

**Comment by niksedk** [comment]
@Purfview: SE assumes that the stdout from output from `Purfview's Faster-Whisper` is utf-8 (like cpp/openai), but it's probably not... could you check?

https://github.com/SubtitleEdit/subtitleedit/blob/main/src/ui/Forms/AudioToText/WhisperAudioToText.cs#L1117

**Comment by Purfview** [comment]
@oniongarlic Do you see those umlauts when whisper-faster.exe is used directly in console?

@niksedk I think in Python3 everything is utf8 unless you set otherwise. And I think this issue is actually in SE. 
`if stdout_encoding != "utf-8"` <- isn't this [in Python] getting encoding of SE's env or whatever? I think it's reporting that it's not utf8.

**Comment by niksedk** [comment]
> @niksedk I think in Python3 everything is utf8 unless you set otherwise. And I think this issue is actually in SE.
> `if stdout_encoding != "utf-8"` <- isn't this [in Python] getting encoding of SE's env or whatever? I think it's reporting that it's not utf-8.

SE cannot determine how other programs writes to stdout. 
Could you force it to use utf8? 
In some older Python versions the environment variables `PYTHONIOENCODING` and `PYTHONLEGACYWINDOWSSTDIO` should be `utf-8`...

**Comment by Purfview** [comment]
As I remember, `if sys.stdout.encoding != "utf-8`, was to fix some problem in SE with Japanese, this conditional comes as True only when exe is used in SE, if "true" then code converts all non ansi chars to "?".

**Comment by niksedk** [comment]
@Purfview: SE uses utf-8 for reading console output, so that should be enabled, something like this?

````Python
# Set the default encoding to UTF-8
sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding='utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding='utf-8')
````

**Comment by niksedk** [comment]
@Purfview: Could you try something like above?

With Danish I get something like this:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/c6bc1286-26a6-473a-830e-33025a85d223)

**Comment by Purfview** [comment]
Some day, atm this issue is not a priority.

**Comment by niksedk** [comment]
OK, np. 
Also something here: https://github.com/pyinstaller/pyinstaller/pull/6065

**Comment by Purfview** [comment]
There is comment: "Yes, utf8 mode is configured at runtime rather than at build-time, and depends on LC_CTYPE and PYTHONUTF8 on the target machine, not the build machine."

Isn't that what you should set before running exe?

**Comment by Purfview** [comment]
> If Purfview's Faster-Whisper crashes, partial output not handled properly, utf-8

Should be fixed in Standalone Faster-Whisper **r160.4**.
