### ISSUE TITLE
Set end, add new, go to the new

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#7601]
I have been using this shortcut for years now, but now it doesn't always work. This started happening a few weeks ago and no one has posted this issue. I'm using latest beta.
![Animation](https://github.com/SubtitleEdit/subtitleedit/assets/28671050/6f511c68-f574-47e1-928c-df8291cef79e)

**Comment by niksedk** [comment]
What is not working? Are you using the latest beta?
Read more about the changes here: https://github.com/SubtitleEdit/subtitleedit/issues/7560

**Comment by uckthis** [comment]
Yes, the latest beta.

As you see in the GIF, it doesn't set end.  It creates new, go to new, but doesn't set end.

**Comment by uckthis** [comment]
Also, it doesn't always happen. Mostly it happens when supposed auto duration overlaps with the next start time.

**Comment by niksedk** [comment]
Hm, I'm not sure what you're trying to do... add a new subtitle inside another subtitle?

**Comment by uckthis** [comment]
Yes. And in the past, 4-5 years I have been using SE, it would end current sub, add new, and go to new. Now, many a time, it would create new, go to new, but wouldn't end the current sub. Doesn't happen all the time, so I don't know what's causing the issue.

In the attached, if you try to set end, create new and go to new in subtitle 2, you'll see it won't set end, which it should as the name says.
[0.txt](https://github.com/SubtitleEdit/subtitleedit/files/13280356/0.txt)

**Comment by niksedk** [comment]
Thx for explaining... I've really tested this shortcut a lot, but not this situation of course ;)

How is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by uckthis** [comment]
Yes, working fine now. If I noticed any issues in the future regarding this, I'll post them. It was a surprise that no one had commented on it, as this issue is at least two weeks old. Guess very few people use this shortcut the way I do.

Anyway, thank you.

**Comment by Flitskikker** [comment]
@niksedk 

The release issue was getting flooded, so duplicated here to keep things together:

One additional (minor) improvement:

Starting situation:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/0cd7d421-7fd5-4206-ac3c-986e8e743d8c)

Press "Set end, add new, and go to new":
![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/6a0ba8da-b52b-4e04-ada3-c5cfa890d944)

Press undo / Ctrl+Z:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/3e37f930-fe7e-45a5-924c-c7ab3da38ac7)

Would it be possible to re-select the subtitle on the left, as before the action, so I can retry directly?

**Comment by niksedk** [comment]
@Flitskikker: hopefully working here? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by Flitskikker** [comment]
> @Flitskikker: hopefully working here? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

Yes, perfectly!

**Comment by Flitskikker** [comment]
@niksedk 
Sorry, I found another little bug 😬

Could you disable the Auto timer for newly inserted subtitles as soon as the user starts changing the subtitle duration, for example by dragging/stretching in the waveform?
Unfortunately it's clashing with the Auto timer now:

https://github.com/SubtitleEdit/subtitleedit/assets/3516155/126e2295-b5a3-4365-889f-368913f5cdac
