### ISSUE TITLE
Open MP4 video is taking forever

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#7603]
Whenever I've tried open a MP4 video, is taking so long to open it.
Meanwhile, MKV videos open instantly.
What could it be the problem?

**Comment by niksedk** [comment]
How do you open the video?

**Comment by Andrebavila** [comment]
> How do you open the video?

Drag and drop

**Comment by niksedk** [comment]
And dropping where?

**Comment by Andrebavila** [comment]
> And dropping where?

To the place where the video play.
Just it. Nothing more.

**Comment by niksedk** [comment]
Thanks :)
I've reworked some mp4 code, but it worked fine for most of my files, but I found one file where I could re-produces this.
So, is this better for you? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by Andrebavila** [comment]
> Thanks :) I've reworked some mp4 code, but it worked fine for most of my files, but I found one file where I could re-produces this. So, is this better for you? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

It's perfect now, @niksedk !
Thank you very much!
