### ISSUE TITLE
Add ability to open sound files like wav or mp3 [feature request]

### ISSUE THREAD

**Issue by SirBuvex** [SubtitleEdit/subtitleedit#7604]
Hi, it would be cool, if Subtitle Edit had an option to create subtitles for sound-only files like mp3 or wav. 
Currently there is only an error message when trying to open a wav or mp3-file.

Workaround: Export audio as Video with black screen and then import it as a video.

**Comment by niksedk** [comment]
Works fine here:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/bdf719e6-7b27-44f5-9335-93718f0b8af1)


What's the error?

**Comment by niksedk** [comment]
In the `Open video file`  dialog, you can choose `Audio files`:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/3f6f137a-d0f5-4f11-b08c-f9f68dadd755)

**Comment by SirBuvex** [comment]
> Works fine here: ![image](https://user-images.githubusercontent.com/1261331/281161535-bdf719e6-7b27-44f5-9335-93718f0b8af1.png)
> 
> What's the error?

I'm so sorry, I got my mistake: I tried to open the sound file via File > Open...
A bit dumb 😖
Maybe it would be cool to have the `Open video file`-entry as an addition also in the Files-menu.
Usually I start a project (in any program) with File > Open... so I think it is a bit confusing...
