### ISSUE TITLE
DeepL translation problem

### ISSUE THREAD

**Issue by venomousraid** [SubtitleEdit/subtitleedit#7606]
Hello, first of all, I am using Subtitle Edit version 4.0.1. I'm using the DeepL plugin and it's incredibly nice that it translates as a whole and not just a single line, but it has some problems. Let me give an example as an output:

1- Hello, I am using Subtitle Edit. (normally there is no period at the end but it adds itself)
2- newly updated.

I hope I have explained the problem. There are still problems with sentence connections and unfortunately I don't understand why. If it is not fully understood, I will send you the screenshots.

**Comment by niksedk** [comment]
Please to add screenshots + subtitle in .srt (you can drag-n-drop images to github - .srt files can be attached as .zip or .txt)

**Comment by venomousraid** [comment]
I've been working on English to Turkish translations and I've noticed something odd that also seems to happen in other languages. Take a look at this screenshot I've highlighted. You'll see that in the Turkish translation on the left, there's a full stop added at the end of the sentence. And then, the part that's supposed to continue that sentence is being treated like it's a whole new sentence. It's weird. I've seen this happen quite a few times and I just can't figure out why it's doing that.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/121519245/b25f292f-0390-423d-8756-a9e4bac19f1f)
[srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/13296055/srt.zip)

**Comment by niksedk** [comment]
The attach subtitle is not the one from the screenshot?

Also, SE will not give good results with subtitles where breaks mostly are in the middle... garbage in = garbage out, sorry.

**Comment by venomousraid** [comment]
Oh, I'm sorry. I sent you the one that is not auto-broken by subtitle edit, in case you want to look at the default version of the transcribed subtitle. Actually, I break it because if I don't, it leaves gaps like in the screenshot I sent you and again it causes ambiguities in the translation. For example, look at the places I have drawn in green. It perceives the bottom sentence in green as a different sentence again. And where I have drawn in red, the problem I posted in the previous screenshot occurs again. In other words, even though some sentences continue, it translates them as separate sentences and illogical translations occur. By the way, I am using Purfview, could this be the reason? Do you have the same problem with the Turkish translation output?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/121519245/ac0fc8a4-eea3-4a1c-8f67-94ba9e1499b4)

**Comment by niksedk** [comment]
Try using latest beta of SE: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
Also, use Whisper via SE or auto-break lines, so new sentences mostly start on a new line.
The beta also has DeepL built-in.

**Comment by venomousraid** [comment]
I don't know if it is appropriate to open the topic again with this comment, if this is a mistake, I apologise very much. If anyone gets the same error, follow niksedk's last comment in this thread. Thank you very much again for your interest and solution.
