### ISSUE TITLE
Waveform centering out-of-order

### ISSUE THREAD

**Issue by miellaby** [SubtitleEdit/subtitleedit#7610]
Win10. SE v4.0.1 mpv or vlc player. The waveform center switch doesn't work when subtitling a video without audio track.

My use case:
- I open a video without audio track
- I generate a waveform.
- SE says there is no audio track and offers me to generate an empty waveform
- it looks like it works. However there is no green line in the waveform view.
- i click on the center button to get the waveform auto-scrolling when browsing my work
- however, the waveform *never* scrolls on its own whatever I do: subtitle focusing, video playing, wafeform playing, etc.  That being said, the waveform view is manually scrollable and the current position cursor in the waveform view moves accordingly to the current video frame and so on. All in all, everything works good enough but the "center" button.

Scroll centering works with one of the videos I got. For this specific video, generating the empty waveform generates a flat green line in the waveform-view. In the waveform folder, the wav file is not empty while all the other video waveforms are 54 bytes length empty wav files. Hope it will help.

**Comment by niksedk** [comment]
Sorry, I cannot re-create this... works fine here.

54 bytes wave files seems very short indeed.
Seems like you have trouble generating wave files. Try to go into Options - Settings - Waveform, and (re-)download ffmpeg, and then try again.

**Comment by miellaby** [comment]
Already did it. Thanks you for trying to reproduce. As said earlier, at least one audioless video gets its waveforme, so it depends on the input video.

 As a workaround, I encoded all my input videos with a blank audio track via ffmpeg, and now everything is fine.
