### ISSUE TITLE
Whisper v 3

### ISSUE THREAD

**Issue by nielka98** [SubtitleEdit/subtitleedit#7612]
Hello, I have a question: when can we expect Whisper version 3 in the program?

**Comment by JDTR75** [comment]
It's already implemented for OpenAI Whisper and Purfview's Faster Whisper. Update to the latest beta and you'll access it.

**Comment by justdoc1** [comment]
> It's already implemented for OpenAI Whisper and Purfview's Faster Whisper. Update to the latest beta and you'll access it.

I installed the subtitle edit up to date. Still, v3 doesn't install automatically, only v2.  Do I need to install any other programs? What do I need to install and how do I install it? Please tell me in detail for beginners.

**Comment by rRobis** [comment]
@justdoc1 

It's currently only available in Subtitle Edit Beta:
https://github.com/SubtitleEdit/subtitleedit/releases/tag/4.0.1  (scroll down to releases, and there SubtitleEditBeta.zip)

Either use SubtitleEditBeta.zip if it's very urgent or better wait till 4.0.2 release.

**Comment by uckthis** [comment]
There isn't any improvement in V3, it's same sh*t as V2 wrapped in a different packaging. It's slower and, just like V2, it randomly adds periods (.) in the middle of the sentences for no reason. You're better off using Medium or Large.

**Comment by darnn** [comment]
Oh, I don't know. I've seen some improvement with Hebrew, even with the random periods.

**Comment by niksedk** [comment]
I will update SE for CPP/Const-me when a final release package is released
