### ISSUE TITLE
Font or Encoding or Filter Problem Need Help 

### ISSUE THREAD

**Issue by Vegeta780** [SubtitleEdit/subtitleedit#7613]
Hi Greetings Sir I have a issue with subtitle and i don't know how to fix this issue
below there is two files .ass and srt encoding with SubtitleEdit  but in .ass subtitle characters are mixed its not separate like srt subtitle 

How can i get subtitle like srt ? because ass subtitle characters become mixed. is this font problem or anything else Thanks in advance 
Best Regards  

![screen srt](https://github.com/SubtitleEdit/subtitleedit/assets/31349213/43dfb243-1497-4ac1-92df-8c80ea5a109c)

![screen ass](https://github.com/SubtitleEdit/subtitleedit/assets/31349213/56bd7ff1-9e57-4583-b482-c494a73a72fb)

**Comment by eddilara** [comment]
your problem with the ass is the styling of the font
use aegisub to change the  font styling

**Comment by Vegeta780** [comment]
> your problem with the ass is the styling of the font use aegisub to change the font styling

i already change the fond styling but didn't work 
[Untitled3.zip](https://github.com/SubtitleEdit/subtitleedit/files/13326074/Untitled3.zip)
