### ISSUE TITLE
Finnish spell checking dictionary download option missing (OCR auto correction)

### ISSUE THREAD

**Issue by fyhtma** [SubtitleEdit/subtitleedit#7614]
In Import/OCR VobSub window the "Finnish - suomi" spell checking dictionary download option is missing from the list. Could you add it or where could I find the file? Thanks

![Sieppaa](https://github.com/SubtitleEdit/subtitleedit/assets/52983487/f72520c0-1f65-4966-a752-66b8f68f2209)

**Comment by niksedk** [comment]
Finnish is kinda special, so it requires a special version of SE: See https://github.com/SubtitleEdit/subtitleedit/releases

Actually if this works, then no special Finnish version is needed: https://github.com/fluks/fi-FI-mozilla-spellchecker/tree/master/dictionaries
Could you test it? The two files needs to be saved in SE-data-folder in the "Directories" folder.

**Comment by fyhtma** [comment]
> Finnish is kinda special, so it requires a special version of SE: See https://github.com/SubtitleEdit/subtitleedit/releases
> 
> Actually if this works, then no special Finnish version is needed: https://github.com/fluks/fi-FI-mozilla-spellchecker/tree/master/dictionaries Could you test it? The two files needs to be saved in SE-data-folder in the "Directories" folder.

Thanks! I tested and seems that the spell checker of fluks/fi-FI-mozilla-spellchecker doesn't work as good as the voikko spell checker (SE401FI) - fluks/fi-FI-mozilla-spellchecker gives way too many unknown words which should not be unknown
![kuva](https://github.com/SubtitleEdit/subtitleedit/assets/52983487/bb9efa4d-9a60-4742-8a93-d37be15d08b8)
![kuva](https://github.com/SubtitleEdit/subtitleedit/assets/52983487/b7060e79-f963-47d0-abb6-94f3b3c3a697)

seems that I can use voikko with SubtitleEdit-4.0.1-Setup.zip version when i moved the voikko files from SE401FI.zip's "Dictionaries\2\mor-standard" folder to path "AppData\Roaming\Subtitle Edit\Dictionaries\2\mor-standard" + fi_FI.dic (144 bytes) file to the "Directories" folder.

I just found it easier to keep SE updated with the installer version compared to the portable version
