### ISSUE TITLE
Error after downloading Faster-Whisper model

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#7617]
Latest beta. Selected Faster-Whisper from the drop-down menu. Was prompted to download it, and did. Then was prompted to download the CUDA dlls for it (or whatever it is) and did that as well. Then I selected the tiny.en model from the list and downloaded that. When it finished this error popped up:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/02063e0e-bbd0-4886-b451-9f24c7ff0e2e)

**Comment by niksedk** [comment]
I've seen the once too... I have not been able to re-create it.
