### ISSUE TITLE
UI missing when switching among Layouts

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7618]
Typically, when switching from Layout 8/9 to another layout (e.g. 1), the waveform controls are missing.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/36de9fd1-ca9b-46b4-a59d-9c77d89552fc)

build 423.

**Comment by niksedk** [comment]
I cannot re-create this.

**Comment by LeonCheung** [comment]
> I cannot re-create this.

So strange. Tested with the latest beta too...

**Comment by niksedk** [comment]
Ah yes, I see it now.

**Comment by niksedk** [comment]
Thx, a nice thing to have fixed in SE 4.0.2 :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
