### ISSUE TITLE
Replace tool disappear

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7619]
Sometimes when hitting Ctrl +H or the Replace toolbar button, nothing shows up, while the Find tool works fine...

I can't repeat it but I'm still suffering it with my current [Settings.zip](https://github.com/SubtitleEdit/subtitleedit/files/13328453/Settings.zip)

**Comment by niksedk** [comment]
I cannot re-create this... 

but when the "replace window" is already visible, Ctrl+H does nothing. Could that be your issue?

**Comment by LeonCheung** [comment]
Not exactly. It happens after I constantly change the screen resolution, I guess. I have a feeling that it does pop up, just somewhere outside the visible screen border... Maybe that's why I cannot see it...

**Comment by LeonCheung** [comment]
I admit that it's very hard to recreate. I'll try to reopen this issue when I got the trick to it. 😆

**Comment by LeonCheung** [comment]
Oh, it happened again on another project... Maybe it helps by sending the project file?

**Comment by LeonCheung** [comment]
![GIF 11-13-2023 4-47-59 PM](https://github.com/SubtitleEdit/subtitleedit/assets/494788/9e92e393-4769-4126-97c1-e8ad1026cc79)
Please pay attention to the title bar. When clicking Find, the focus is on the popup window, so the titlebar turned gray. However, when clicking Replace, nothing happend, so we can confirm that the new window didn't pop up at all.

**Comment by LeonCheung** [comment]
Update:

Click "New" button to start a new project then click Replace, I got this:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/a07fd59e-b4d1-4391-8374-1a42b0cc8122)

**Comment by LeonCheung** [comment]
Again:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/bdfae549-ab90-4bf4-9a3a-19fdfa023ebe)

**Comment by niksedk** [comment]
Thx for finding this bug :)
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
