### ISSUE TITLE
Version 4.0.1: Appearance settings don't persist

### ISSUE THREAD

**Issue by skycommand** [SubtitleEdit/subtitleedit#7621]
Hello. I'm reporting an issue for version 4.0.1.

I changed my appearance settings so that the contents of the textbox is not in boldface, not centered, 16 pt, and use a different font.
![Before](https://github.com/SubtitleEdit/subtitleedit/assets/17097175/63e0553d-302a-40f6-bbae-5d2b1fef78f2)
After restarting, Subtitle Edit 4.0.1 ignored some of those settings. The text is in boldface, and not 16 pt.
![After](https://github.com/SubtitleEdit/subtitleedit/assets/17097175/b912da11-c953-48f9-b95f-5812cadbee4d)

**Comment by eddilara** [comment]
it sounds like you want font styling
use ass subs for this
