### ISSUE TITLE
Shortcut comflict with Fix Common Errors tool?

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7624]
Say, my customized shortcut setting is that W for go to previous line and R for go to next line. However, when trying to edit texts in Fix Common Errors textbox, I can't type these two letters...

**Comment by niksedk** [comment]
Thx for the info :)
Hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Cool, thx!
