### ISSUE TITLE
Remember the last used multiple Selection rule

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7625]
This is a very cool and useful tool. Just.. it would be much more convenient if it remembers the last used rule. Currently, the default rule is always set to "Contains" each time it is opened, But, like me, I used other rules much much more than Contains, so I have to switch it every time... Hope there could be a little improvement here if possible. 

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/a146a129-af15-40c6-9019-c8a281992e5f)

**Comment by niksedk** [comment]
SE remembers the last used "modify selection" rule here...

**Comment by LeonCheung** [comment]
Oh, you are right. I guess that's because I didn't always click Apply or OK, because I don't actually need the selection at all. For example, when I want to use Exactly one line or Exactly two lines to check if there are any exceptions to fix, so I only use it more like an error searcher more than a selection tool. Hmm, in that case, not a problem then. :)
