### ISSUE TITLE
[Suggestion] Keep List Errors tool open

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7626]
After double-clicking on one of the rows in the list in order to jump to that line in List View, the tool will close automatically, but what if we need to check multiple errors? So it would be great if we keep the window on top until we decide to close it. Something like how the Find/Replace window works.

**Comment by niksedk** [comment]
You can use the "Go to next error" shortcut - Ctrl+F8 (I think)

**Comment by LeonCheung** [comment]
I know. The thing is that many times I found that I only need to quickly jump to specific lines of certain errors or certain error types via this tool, rather than having to go through the whole list from the beginning to the end.
