### ISSUE TITLE
Format starting to not apply to the display after do a format 10 times

### ISSUE THREAD

**Issue by MKN-Makuno** [SubtitleEdit/subtitleedit#7628]
![colorformat](https://github.com/SubtitleEdit/subtitleedit/assets/63585685/c930df79-2390-4b95-bba8-dd27fd61669e)

This only occurred on program. It displays formatted properly when I tried to upload it to YouTube.

**Comment by niksedk** [comment]
Could you attach as a subtitle file? (GitHub accepts .zip files)

**Comment by MKN-Makuno** [comment]
@niksedk 
[Holiday.zip](https://github.com/SubtitleEdit/subtitleedit/files/13350971/Holiday.zip)
