### ISSUE TITLE
How to convert .srt file with Asian language to .pac format

### ISSUE THREAD

**Issue by AnkushSeth** [SubtitleEdit/subtitleedit#763]
Hello there,
I am using subtitle edit to convert srt files into .pac files. Its working great. But i face issues while working with Unicode data. It is making junk files. Can i have any suggestions on this?

**Comment by xylographe** [comment]
Do you mean Thai subtitles?

**Comment by AnkushSeth** [comment]
No ! I mean languages like Indian,Chinese,Japanese ,etc which have unicode format not "ANSII"

**Comment by niksedk** [comment]
PacUnicode is another format... 
I do have a Chinese sample file so "Chinese Traditional (Big5)" could probably be added. If you have samples of Indian or Japanese do post them there (you can also email)

**Comment by AnkushSeth** [comment]
Hello Nikolaj,

Thanks for the reply! I have Indian language file that needs to be
converted to Pac file. I am attaching the file. when i convert this file
with SE then it gives me junk output.

Ankush Seth
Project Engineer
CDAC-GIST
Pune
+91 9527303360

**Comment by AnkushSeth** [comment]
Hello Nikolaj,

Thanks for the reply! I have Indian language file that needs to be converted to Pac file. I have mailed you the files. Please suggest me how can i convert them.Your help is required. Thanks !

**Comment by niksedk** [comment]
I've not received any pac files?
Also, you can test the Chinese in this test version: http://www.nikse.dk/SubtitleEdit.zip (or use latest source)

**Comment by AnkushSeth** [comment]
Hello Nikolaj

Please find the attached files.

Thanks & Regards,
Ankush Seth
Project Engineer
CDAC-GIST
Pune
+91 9527303360

---------- Forwarded message ----------
From: Ankush Seth <ankush1890@gmail.com>
Date: Mon, May 25, 2015 at 12:08 PM
Subject: Re: [subtitleedit] How to convert .srt file with Asian language to
.pac format (#763)
To: SubtitleEdit/subtitleedit <
reply@reply.github.com
>


Hello Nikolaj,

Thanks for the reply! I have Indian language file that needs to be
converted to Pac file. I am attaching the file. when i convert this file
with SE then it gives me junk output.

Ankush Seth
Project Engineer
CDAC-GIST
Pune
+91 9527303360

**Comment by AnkushSeth** [comment]
Nikolaj ,
Just one query? why the software asks for code page. can't all text be treated as Unicode. And then we will have support for all the languages of the world? Pardon me if i am wrong! 
Thanks

**Comment by niksedk** [comment]
Hi AnkushSeth,

We would need Indian pac files... not srt files.
The problem with pac files is that they are not unicode files or text files - it's a format by Screen Subtitling Systems (with no public specs as far s I know)

**Comment by niksedk** [comment]
I need a sample for in order to look more at this...

**Comment by gru123** [comment]
Hi, Nikolaj
There's free EZConvert Demo.
Demo version supports up to 25 subtitles, but it's enough to test every format you need, and every language you need.
[https://www.eztitles.com/index.php?page=download-demos](url)

**Comment by niksedk** [comment]
Japanese works fine as far as I can tell....

**Comment by gru123** [comment]
![pac](https://user-images.githubusercontent.com/42896067/133029211-87e0c428-5398-47f0-895f-f1e82238d1b4.png)
I think Latin Czech should be renamed Latin Central Europe. This seems to work with Polish, Hungarian etc.
