### ISSUE TITLE
Polish menu unreadable subtitleedit

### ISSUE THREAD

**Issue by SonGoku90** [SubtitleEdit/subtitleedit#7632]
I have Fedora Workstation 39, but I can't use it because the menu is unreadable in Polish. As shown in the picture. How to fix it?
![2023-11-14_11-09](https://github.com/SubtitleEdit/subtitleedit/assets/57522176/be00a618-2d9f-4a6c-8136-cd8f0c8841eb)

**Comment by niksedk** [comment]
Sorry, I think that's a mono issue....

**Comment by SonGoku90** [comment]
> Przepraszam, myślę, że to problem monofoniczny....

And how can this be fixed?
