### ISSUE TITLE
4.0.1 Whisper (Audio to Text) CPP Large Model is not downloading

### ISSUE THREAD

**Issue by DeinName** [SubtitleEdit/subtitleedit#7634]
Hi, I downloaded this version (4.0.1) after formatting my PC, I'm trying to use Whisper (Audio to Text) CPP, but the Large Model is not downloading. Any solution? Thanks in advance.

**Comment by niksedk** [comment]
Could you try latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip

What OS are you using?
