### ISSUE TITLE
Display Bitrate Somewhere

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7636]
Knowing the video bitrate of the original video source can be very useful for controlling the burnt-in video quality, especially when you are trying to match the original bitrate. IMHO it could be displaced in the Burn-in tool UI for a nice reference so that we don't have to view it somewhere else. (e.g. by right-clicking on the video file, then **Properties**, then go to **Details** tab... )

**Comment by LeonCheung** [comment]
Maybe another workaround like this?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/c96b87dd-2d58-47d9-a837-5c041a2b7582)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/6f33457d-30b6-4ad8-8409-9b12e6c06da5)
