### ISSUE TITLE
Error message when

### ISSUE THREAD

**Issue by Hakunamatata67** [SubtitleEdit/subtitleedit#7637]
Hello,

I have this error message when I want to use Beautify Time codes
![Capture d'écran 2023-11-16 154556](https://github.com/SubtitleEdit/subtitleedit/assets/66781048/5341906e-f61a-423e-aa1a-57ac5b930945)

I didn't have any issue using it when I start the subtitles. Now I'm half the subtitle file and I got this message. I restard SE, but still have the error.

**Comment by Flitskikker** [comment]
Looks like the logic ended up in a situation that I thought could never happen. 😮

Could you please share the subtitle file and the shot changes (Video -> Remove/export shot changes -> Export...) ?

I suspect it could also be due to very specific profile settings, so just to be sure, please also share your Settings.xml file (or just the `BeautifyTimeCodes` portion).

Then I will debug it over the weekend.

Thank you.

**Comment by Nachtuil** [comment]
> Hello,
> 
> I have this error message when I want to use Beautify Time codes ![Capture d'écran 2023-11-16 154556](https://private-user-images.githubusercontent.com/66781048/283491678-5341906e-f61a-423e-aa1a-57ac5b930945.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDkzMjcsIm5iZiI6MTcwMjA0OTAyNywicGF0aCI6Ii82Njc4MTA0OC8yODM0OTE2NzgtNTM0MTkwNmUtZjYxYS00MjNlLWFhMWEtNTdhYzViOTMwOTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDE1MjM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMjIwMjRmYzMyM2JiNDI3ODllM2FlNjM2MGEyMmZhMDZjNzJiYjRlMmViODBjZDUxNWU0ZDlkNDI1NTBjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g96dWfjIc9xc5BqRenp39ulgWeqVrOeWKGz_DbFP0xc)
> 
> I didn't have any issue using it when I start the subtitles. Now I'm half the subtitle file and I got this message. I restard SE, but still have the error.

**Comment by Flitskikker** [comment]
That is not an error from the Beautify Time Codes feature. Please open a separate issue.

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
