### ISSUE TITLE
When using italic/bold/underline with Format, format will incorrectly place in source file

### ISSUE THREAD

**Issue by MKN-Makuno** [SubtitleEdit/subtitleedit#7638]
Three examples here

## **Ex1: Two Lines, colour format with italic inside**
![exs1](https://github.com/SubtitleEdit/subtitleedit/assets/63585685/89ac65fb-343f-4f3e-b0b1-474a97b08ec5)

## **Ex2: One Line, colour format with bold and underline outside**
![exs2](https://github.com/SubtitleEdit/subtitleedit/assets/63585685/1b44102d-a4ee-43c9-a31e-aa2596d6de39)

## **Ex3: One Line, colour format with bold, underline, and italic outside**
![exs3](https://github.com/SubtitleEdit/subtitleedit/assets/63585685/3c93d89a-d29c-4cf3-b1d1-3a55596123ec)

**Comment by niksedk** [comment]
Could you attach the source subtitle file?

**Comment by MKN-Makuno** [comment]
@niksedk 
[Tragic.zip](https://github.com/SubtitleEdit/subtitleedit/files/13397104/Tragic.zip)
It might be messier than what I've shown above.
