### ISSUE TITLE
Bug or not? Alignment option doesn't work on my computer????

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7639]
When you select some line in a subtitle, and right-click on it/ Alignment option from the context menu, you get the option to position your subtitle line in 9 positions, all combinations of Top/middle/bottom, and left/center/right. It is meant (mostly in those cases) when something is in the place of the subtitle and we want to move it to be visible. 

But, in my case, the only combination that works is Bottom/left, Bottom/center, and Bottom/Right. All the other positions don't work, I always have these 3 positions. Bottom - left, right, center. AM I WRONG, or it is a bug? 

![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/49f46dd3-8e0a-4122-8e9b-231fe88e742f)

You can see on the picture, that I set it to be Middle/center and it stayed Bottom/center. Why it doesn't work? The subtitle should be in the middle of the video, and it stays in the bottom/center position. What am I doing wrong?

**Comment by niksedk** [comment]
What video player are you using? Only mpv has alignment preview.

**Comment by Cyberyoda1411** [comment]
Thanks for the info. As I can see, we must download mpv lib and check the option 'mpv handles preview text'. Problem solved.

**Comment by Cyberyoda1411** [comment]
While the topic is still open, I want to tell you something. 

You should add the path on how to set up **stable-ts** (audio to text) in the help file. I had to search through the topics to find the web address (you gave it) to this stable-ts. If there are some other versions of AUDIO TO TEXT you didn't cover in the help, you should add the web addresses in it. 

And it would be nice to tell people with exclamation marks not to play with Python versions. They shouldn't uninstall the old versions, because some modules work with version 3.10 only. So, if people have 3.10, and 3.11, and they want to install 3.12, it is OK, but not to delete 3.10 and 3.11. Or they will regret it, they will have to reinstall them again. I had luck, I didn't empty my recycle bin and I could restore data.

**Comment by niksedk** [comment]
Yes, thx. I need to update the help page a bit.
But it's really impossible to write detailed instructions for python whisper versions, as close to endless situations can appear on users machines!

**Comment by Cyberyoda1411** [comment]
I am aware that you can't help with all nuances, but it would be nice to tell people NOT TO DELETE python data from earlier versions of Python. I did it and I almost stayed with most of the settings for Audio to text modules. And people will read the author's note that some modules work with Python 3.10 only. The current version 3.12 is not supported in that case.

**Comment by niksedk** [comment]
Also, the Python Whisper versions requirements change all the time!

I've updated the help page a little: https://www.nikse.dk/subtitleedit/help#audio_to_text
