### ISSUE TITLE
Const-Me  doesn't show the "Large" model anymore ? V4.0.2

### ISSUE THREAD

**Issue by shruru** [SubtitleEdit/subtitleedit#7640]
I just upgraded from 4.0.1 . Win11. 
I found the Whisper - "Const-Me" doesn't show up the large mode download options and niowhere to download them again.
Please help.

It worked in 4.0.1 like a charm. 
Thanks a lot. 🙏🏻

<img width="782" alt="SCR-20231119-reoi" src="https://github.com/SubtitleEdit/subtitleedit/assets/2038477/bd477e02-c58b-420c-93a7-78a37ee5074e">

**Comment by niksedk** [comment]
Yeah, Const-me really needs an update

Hopefully an update will be available soon: https://github.com/Const-me/Whisper

**Comment by shruru** [comment]
> Yeah, Const-me really needs an update
> 
> Hopefully an update will be available soon: https://github.com/Const-me/Whisper

It showed up on **SubtitleEdit V4.0.1 this morning**, now after I installed 4.0.2, the "large" model option is missed now. 😁

**Comment by Purfview** [comment]
That's why you need to help test betas when it's announced that a new version will be out soon. 😁

Like there: [Release Subtitle Edit 4.0.2 ](https://github.com/SubtitleEdit/subtitleedit/issues/7593)

**Comment by shruru** [comment]
sure. Thanks for the input~ 🤝

**Comment by Purfview** [comment]
Just rename large model file as tiny and continue to use it that way.

**Comment by shruru** [comment]
> Just rename large model file as tiny and continue to use it that way.

what?! are you a genius 😄 let me try it...👍🏻

**Comment by niksedk** [comment]
Latest beta has the large model again: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
(requires re-download I think)

**Comment by 1001ruchka** [comment]
Please don't remove Const-me, just add the option to download large_v2 model. The Const-me version works great with my Nvidia gtx970. The original version of @ggerganov Whisper-cpp (1.5.x) unfortunately does not support GPU for older video cards such gtx970, but Const-me works through DirectX and works fine, and most importantly works very fast!

**Comment by Purfview** [comment]
You can use faster-whisper with gtx970

**Comment by 1001ruchka** [comment]
I used faster-whisper, installed CUDA 11 and CUDA 12, installed necessary libraries, but when using faster-whisper the video card is not used (I also used the -device cuda:0 option on command line). And in const-me version GPU is 90% loaded.

**Comment by Purfview** [comment]
> the video card is not used

Them what error did you got?

**Comment by 1001ruchka** [comment]
I am sorry, I was mistaken. I installed GPU-Z and was able to track the GPU load normally. In Fast-Whisper GPU is loaded too.

But Fast-Whisper is much slower on the medium.en model. On Large models similar values are given, but it is necessary to compare exactly with a stopwatch, remembering that in cont-me - Version v2, and Fast-Whisper - v3.

I compared the same video (13 minutes), in English, model medium.en
Fast-Whisper - 7 minutes 25 sec.
Const-Me - 2 minutes 17 seconds

**Comment by Purfview** [comment]
Const-Me is a low quality implementation, for comparison you should use same low quality settings for Faster-Whisper.

Before benchmarking Faster-Whisper add these options to the advanced field:
`-bs=1 -bo=1 --temperature_increment_on_fallback=None --word_timestamps=False`

**Comment by 1001ruchka** [comment]
With
`-bs=1 -bo=1 --temperature_increment_on_fallback=None --word_timestamps=False`
Faster-Whisper - 5 minutes 42 sec.

**Comment by 1001ruchka** [comment]
I also have a question on Faster-Whisper - how do you affect the maximum character length in a subtitle line. I use subtitles for translation and use the sentence merge functionality in Subtitle Edit. Ideally, I want Faster-Whisper to not split subtitle sentences at all.

**Comment by 1001ruchka** [comment]
> Const-Me is a low quality implementation, for comparison you should use same low quality settings for Faster-Whisper.

Thank you. I will compare the quality of texts received by Faster-Whisper and Const-Me.

**Comment by Purfview** [comment]
> I also have a question on Faster-Whisper - how do you affect the maximum character length in a subtitle line. I use subtitles for translation and use the sentence merge functionality in Subtitle Edit. Ideally, I want Faster-Whisper to not split subtitle sentences at all.

Read there -> https://github.com/SubtitleEdit/subtitleedit/issues/7662
I'll test that spaghetti code now, let's prey that it works. 😆

**Comment by Purfview** [comment]
After one bugfix looks like it works. Need to think about the parameters names and defaults now...

**Comment by Purfview** [comment]
> I also have a question on Faster-Whisper - how do you affect the maximum character length in a subtitle line. I use subtitles for translation and use the sentence merge functionality in Subtitle Edit. Ideally, I want Faster-Whisper to not split subtitle sentences at all.

Implemented in r160.8.
Post feedback there-> https://github.com/Purfview/whisper-standalone-win/discussions/125

**Comment by 1001ruchka** [comment]
--max_line_width
--max_line_count
What's the difference?

**Comment by 1001ruchka** [comment]
max_line_count - number of subtitle lines?
max_line_width - number of characters in one line or total in all lines?

**Comment by 1001ruchka** [comment]
I used to use:
--max_line_width 1000 --max_line_count 1
But the sentences were still split.
Sentences should not be split if the end character is not equal to "." or "?" or "!", or unless the max_line_width is exceeded.
