### ISSUE TITLE
CTRL+U messes up spacing when words wrap

### ISSUE THREAD

**Issue by shanedk** [SubtitleEdit/subtitleedit#7642]
This is an error I first noticed with 4.0.1 and persists in 4.0.2. If you select a word that's capitalized, and hit CTRL+U to make it lowercase, sometimes it messes up with the spacing. For example, it might change "This should be LOWER case" to either "This should belower  case" or "This should be  lowercase."

It only seems to do it when words are wrapping around the text box. If you have a word after or near the first wrap point, it'll tend to do it. Or, if it's before the first wrap but changes the wrapping. It doesn't happen all the time, but often enough that it should replicate easily.

**Comment by niksedk** [comment]
Hm, I cannot replicate this.

**Comment by niksedk** [comment]
Any hints on how to replicate this?

**Comment by shanedk** [comment]
Frustratingly, I can't make it happen. Next time it happens, I'll make a video of it.
