### ISSUE TITLE
GUI Related and Settings Issues

### ISSUE THREAD

**Issue by Jack1789** [SubtitleEdit/subtitleedit#7644]
Hello, would it be possible to sort out some of the next old issues in v4.x?

**While in ".SUP" edit mode window:**

**1 -** Make the program remembers the window's size and position between executions; and not only 
the main window, but the "previewing" ones as well ("Apply duration limits...", "Resize images...", etc.).
This would avoid the user having to resize and reposition said windows each time, which gets annoying.

**2 -** Right after closing the edition window, don't let opened an unnecessary main program's instance,
but close the program completely.

**3 -** Make the program remembers the exact chosen active columns, and their positions. Right now, I would like
to always see the "Gap" column, besides the other "5" active columns that are visible by default, but the program
will not show it the next time, after closing it.

**4 -** Add a regular "Save" option, instead of always having to use the "Save as..." one, so making
a few simple corrections to a subtitle won't require saving it as a new one, or having to rewrite it.

**5 -** Make the "SUP edit" windows have their own presence in the taskbar, I mean, like any other program/folder
regular window, make them visible over there. Since most times, I have plenty of windows already opened, and the
"SUP edit" windows remain in a "background" state, which makes them hard to find them or even remember there
was one of them opened. Using the "Alt+Tab" keys' combination helps, but I think it shouldn't be necessary.

**6 -** Right after opening a .sup subtitle and choosing to show the "Gap" column, none of the "Tools" and
"Synchronization" options will open, unless one of the lines is selected previously. Look:

https://gofile.io/d/dPZs13

**While in main window:**

**1 -** Simplify the many clicks it takes to export a textual subtitle into a "Blu-ray sup" format.
I mean, going from this chain:

**"File>Export>Blu-ray sup...>Preview Window>Export all lines...>Save"**

to something like this:

**"File>Export>Blu-ray sup..."** (this alone would omit at least two further steps)

Since in case like mine, when I always use the very same image settings and saving location, going thru
the "previewing" as well as "saving" windows make it just a waste of time. Maybe leaving such a chain as it
is now but just for those who need it, and adding a kind of shortcut or button which just saves the current
subtitle to a BD SUP one, would be the quickest approach.

**2 -** Make the program remembers the BD SUP previewing window's size and position between executions.
Right now, it will remember them, but not after a restart.

Finally, regarding the program's settings, add an option which let the user be able to export/import them as needed.
Right now, after installing last "4.0.2" version, I saw some of my previous settings were just gone; and trying to
reestablish them with a "manually" copied "Settings.xml" file didn't make any differences this time, since it seems
just a few of the previous settings are still valid in the new 4.x versions.

Thanks.

**Comment by niksedk** [comment]
Thanks - that's a long list... a few issues improved in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by Jack1789** [comment]
Hello, it's great to see you were able to fix at least some of them. Thanks. : )

Regarding the implemented fixes so far:

**While in ".SUP" edit mode window:**

**1-** The program is able to remember its windows' sizes, although still misses to remember
the "previewing" ones, like "Apply duration limits...", "Resize images...", "Apply brightness...", etc.

**2 -** Fixed.

**3 -**  I see now the "Gap" column is present by default after starting the program, but neither
the columns' position nor its presence will be remembered after a restart.

**4 -** No changes.

**5 -** Fixed.

**6 -** Fixed.

**While in main window:**

**1 -** I saw you added a commit about this feature, but I wasn't able to find
a button or another kind of shortcut to test it.

**2 -** No changes.

Regards.

**Comment by niksedk** [comment]
I will close this now... I think the fixes made are the best of your suggestions.

If there's something you think is really important do open a new issue.
Normally only put one request in an issue. Read more here: https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by Jack1789** [comment]
@niksedk 

Alright, maybe in a near future, I request again those still pending to add/fix, but in a "one by one" basis. : )

By the way, if that "BDSUP saving shortcut" is working somehow, please explain how to use it.

Thanks.

**Comment by niksedk** [comment]
You can now setup a shortcut for exporting BD sup from the main SE window. Go to Options - Settings - Shortcuts:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/292b9570-e05a-4294-a7d1-b1cdf76c25c4)

**Comment by Jack1789** [comment]
@niksedk 

I see, that saves me "two clicks", but I still have to see the preview window and set the subtitle's path
and name, which are the main slowdown repetitive tasks I wanted to avoid.

I thought about suing the command line, but it won't work with ".sup" output:

```
C:\Program Files\Subtitle Edit>SubtitleEdit.exe /convert "C:\TEST (sub)\test 1234.srt" Blu-raysup

C:\Program Files\Subtitle Edit>

Subtitle Edit 4.0.2 - Batch converter

1: test 1234..srt -> C:\TEST (sub)\test 1234.sup...
ERROR: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Cast[TResult](IEnumerable source)
   at Nikse.SubtitleEdit.Logic.CommandLineConvert.CommandLineConverter.BatchConvertSave(String targetFormat, TimeSpan offset, String deleteContains, TextEncoding targetEncoding, String outputFolder, String targetFileName, Int32 count, Int32& converted, Int32& errors, List`1 formats, String fileName, Subtitle sub, SubtitleFormat format, IList`1 binaryParagraphs, Boolean overwrite, Int32 pacCodePage, Nullable`1 targetFrameRate, ICollection`1 multipleReplaceImportFiles, List`1 actions, Nullable`1 resolution, Boolean autoDetectLanguage, BatchConvertProgress progressCallback, String ebuHeaderFile, String assaStyleFile, String ocrEngine, String preExt, Nullable`1 renumber, Nullable`1 adjustDurationMs, PreprocessingSettings preprocessingSettings, CancellationToken cancellationToken)
   at Nikse.SubtitleEdit.Logic.CommandLineConvert.CommandLineConverter.Convert(String[] arguments)


0 file(s) converted in 00:00:00.4211815
```

Thanks.

**Comment by niksedk** [comment]
Thx, that's a bug... hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by Jack1789** [comment]
Alright, with the help of a little batch file as a workaround, now it works as intended to me: **the less clicks the better**.

This is the batch file, in case someone finds it useful as well (remove the 'pause' value to avoid even one additional click/press):

```
@echo
FOR /f "tokens=*" %%G IN ('dir /a-d /b *.SRT') DO (
	SubtitleEdit.exe /convert "%%G" Blu-raysup
)
pause
```
Thanks.

**Comment by Jack1789** [comment]
@niksedk

Hello, regarding the "settings" feature, earlier today I faced a serious issue after having replaced all the installed files
from a previous "beta" version, with the ones from the latest beta version: "settings.xml" file was reset by the program
after initiating the program for the second time.

Would you please take a look into that issue? Since fortunately, I had a backup copy of the settings file,
and it would be quite annoying to set all from scratch in case of a sudden reset.

Thanks.
