### ISSUE TITLE
4.0.2 video autoload 

### ISSUE THREAD

**Issue by Deepcuts** [SubtitleEdit/subtitleedit#7648]
I am using SE to edit subtitles and I never use the video player or sync features.
Up until 4.0.2, hiding the video player was easy.
I lost the last 15 minutes looking for a way to only have plain subtitle window and cannot find a way.
Am I doing something wrong or the option is really missing now?

**Comment by niksedk** [comment]
Read here: https://github.com/SubtitleEdit/subtitleedit/issues/7482#issuecomment-1821244059
