### ISSUE TITLE
where can i look at all   actors ..  i have more than 3 actors but  i can see only  3 actor and it keep  change every time i add  new actors

### ISSUE THREAD

**Issue by maloadjav** [SubtitleEdit/subtitleedit#7652]
![0000actors](https://github.com/SubtitleEdit/subtitleedit/assets/85825392/fe6dff79-b0cc-479c-8694-0090386e012c)
![0000actors](https://github.com/SubtitleEdit/subtitleedit/assets/85825392/6de0012a-924f-4db5-8df7-7783eefc6681)

i want to set  shortcut for every actors so  i cant do it   because i only 3 actors 

can i do it in notepad or some file in subtitleedit ??

**Comment by niksedk** [comment]
Could you attach your subtitle file? (Github supports .zip or .txt files)

**Comment by niksedk** [comment]
You only have 3 actors...

You can set shortcuts here:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/12c2ea66-6651-4163-92fc-4c195701866c)

**Comment by maloadjav** [comment]
- -" 
i add many actor  .

today i add 4 actors  and its work  for 10 minute 

after i  use program  , doing sub , set shortcut for actors .. and  test it   a  little bit 

it work  ..... 

and then  there is only   3 actors  in the list   again   ....

and then  because  there is only  3 actors  .. all  my shortcut   was ... change  ...

[actorsv3.zip](https://github.com/SubtitleEdit/subtitleedit/files/13459543/actorsv3.zip)


but thank you for the shortcut
