### ISSUE TITLE
Bug: /MergeShortLines uses Singe line max. length as paragraph limit

### ISSUE THREAD

**Issue by BenJamesAndo** [SubtitleEdit/subtitleedit#7655]
I have a subtitle file with one word per line. I'd like to use the Merge short lines feature. When using it through the GUI I specify the maximum character in one paragraph and click OK. It then merges them adhering to, in my case, 74 characters in one paragraph. It works perfectly.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/44917135/2c978228-2cc2-442a-9426-8940244d6dc7)
Using Merge short lines GUI

![image](https://github.com/SubtitleEdit/subtitleedit/assets/44917135/f2556673-9f5e-49e3-9f3b-0cd4a94acfeb)
After clicking OK

Typically the CLI seems to inherit the settings through the GUI. However when using `/MergeShortLines` it seems to use the Singe line max. length through general settings as the Maximum character in one paragraph setting. So if the Singe line max. length is 37, then the max characters in one paragraph is also 37 when using the CLI.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/44917135/005a531d-a03b-4ad4-bd6b-c3a311d12fcd)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/44917135/1684389c-9955-4ab3-9816-270429b25153)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/44917135/7185abee-e7ae-4b57-adaa-3a00cc76a891)

The first two photos is using the GUI, and the second two are using the CLI. As you can see using CLI makes max paragraph length to 37, instead of 74.

My use case is to use Faster-Whisper with `--one_word` to generate subtitles, and then use Subtitle Edit to merge the short lines. This gives me ultimate flexibility in how many characters are in a paragraph. Whereas using Faster-Whisper without `--one_word` via CLI the paragraph length would sometimes be too long.
A kind of workaround is to set the Singe line max. length to 74, however that can lead to other problems with other workflows I use.

**Comment by niksedk** [comment]
Is this any better? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

Should now use the setting from the UI.

**Comment by lj739** [comment]
How to batch merge short lines? I have a lot of  srt files to be handled.

**Comment by BenJamesAndo** [comment]
@lj739 it doesn't look like the Batch convert has an option to merge short lines, so you'd need to do it through the CLI. Something like this would work
`subtitleedit.exe /convert *.srt srt /inputfolder:"C:/Users/user/Documents/captions" /mergeshortlines`
