### ISSUE TITLE
issue “Whisper SHA-512 hash does not match!” when downloaded whisper cpp cublas

### ISSUE THREAD

**Issue by gkngkngkn** [SubtitleEdit/subtitleedit#7656]
![31875f339f97d7a3074e95881949842](https://github.com/SubtitleEdit/subtitleedit/assets/151842080/7427bb68-6821-4fa5-8df7-2b8799ad457b)

**Comment by urona** [comment]
I'm getting the same error..

**Comment by niksedk** [comment]
Also, latest SE beta now includes Whisper CPP 1.5.1: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by tomcatsv** [comment]
我换个梯子就好了，应该是被墙拦截了
