### ISSUE TITLE
Drop down menus are broken using wine SE V4

### ISSUE THREAD

**Issue by Canuma** [SubtitleEdit/subtitleedit#7657]
OS:  Kubuntu 23:10
SE:  4.0.2
Wine: 8.0.2

I am running SE under wine, as unfortunately, the native Linux Version is way to crashy for me to use. Until SE V 3.x most stuff worked just fine. 
However, since SE 4.x drop down menus aren't working as expected, they have the mouse buttons changed. I am able to open a drop down menu and select an item with the left mouse button, however, to confirm that selection, I have to press right mouse button.  (I cannot open a drop down menu with right click, but I can select an Item with right click immediately)

Now I don't know if this is a problem within wine or SE, all I can tell is, it worked within V 3.x of SE. 
It would be nice if you could look into that issue.

**Comment by niksedk** [comment]
I have no idea of what to do...

**Comment by Canuma** [comment]
Just in case anybody else is using SE via Wine, it seems I finally found a solution for that problem. Just install comctl32 via winetricks and drop down menus should work again.
