### ISSUE TITLE
Support for Opus in Whisper

### ISSUE THREAD

**Issue by vivadavid** [SubtitleEdit/subtitleedit#7659]
Hi,

I'd like to suggest adding support for Opus in Whisper. I think it's included in FFmpeg, so it should work.

Thanks in advance!

**Comment by niksedk** [comment]
Why and what is Opus?

**Comment by vivadavid** [comment]
Hi,

Opus is an audio codec. It's used, for example, to record your voice on WhatsApp, but as far as I know, it can be added as a track on a video. As it's open-source and well-optimized, it's expected to become more and more popular in the future, and so, there will be times when you need to transform your Opus audio into text via Whisper.

**Comment by niksedk** [comment]
How is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip ?

**Comment by vivadavid** [comment]
Thank you, @niksedk . Now it does allow to add Opus files, and Whisper works on them as expected!
