### ISSUE TITLE
Is there a way to split subtitles for specific line lengths using specific punctuation marks? 

### ISSUE THREAD

**Issue by gkngkngkn** [SubtitleEdit/subtitleedit#7662]
Due to the way Whisper recognizes subtitles, it often breaks a complete sentence into several segments.
 
I usually merge the subtitles for each line and split them based on punctuation marks indicating the end (such as "." or "!") to ensure that each subtitle is a complete sentence for translating better. 

However, sometimes, a long sentence with only commas in the middle so cannot be split using the aforementioned method, which affects the viewing experience.(imaging a sentence over 200 characters and only "," between it.)

In light of this, could there be a new setting introduced? For example, specifying that text segments below 100 characters should only be split by ".", while text segments above 100 characters should be split by "." and ",", ensuring that there are all complete sentences and no excessively long subtitles.

Another approach could be to set a maximum character limit, such as 100. When a text segment exceeds 100 characters (usually after manual merging), automatically use the nearest punctuation mark after the 100th character as the mark for segmentation. This would ensure that each text segment is around 100 characters, maintaining readability and coherence by using punctuation as natural breakpoints.

**Comment by niksedk** [comment]
Sorry, this is not possible in SE.

**Comment by Purfview** [comment]
> is not possible in SE

Why? This looks very simple.
Such output actually makes sense for translations, I may implement it in Standalone Faster-Whisper.

**Comment by gkngkngkn** [comment]
If this could be achieved, it would be truly great,sir. 

However, there is another issue bothering me: during transcribing some lengthy texts, there often appears a large chunk of text (possibly hundreds of characters in length) without any punctuation marks. 

This makes it impossible for me to automatically segment them into separate sentences using punctuation after merging subtitles, which is crucial for a proper translation.

 I've tried several models and prompt of whisper, but keep encountering this situation. The only method available is to manually identify lengthy subtitles within the subtitle file, place them into ChatGPT to automatically add punctuation marks, and then segment them based on punctuation. However, this process is too slow. I'm unsure if there are any existing tools capable of automatically recognizing text of specified length within SRT files and automatically annotating punctuation marks.
 
 I wonder if there's an appropriate solution to this problem.

**Comment by gkngkngkn** [comment]
> > is not possible in SE
> 
> Why? This looks very simple. Such output actually makes sense for translations, I may implement it in Standalone Faster-Whisper.

If this could be achieved, it would be truly great,sir.

However, there is another issue bothering me: during transcribing some lengthy texts, there often appears a large chunk of text (possibly hundreds of characters in length) without any punctuation marks.

This makes it impossible for me to automatically segment them into separate sentences using punctuation after merging subtitles, which is crucial for a proper translation.

I've tried several models and prompt of whisper, but keep encountering this situation. The only method available is to manually identify lengthy subtitles within the subtitle file, place them into ChatGPT to automatically add punctuation marks, and then segment them based on punctuation. However, this process is too slow. I'm unsure if there are any existing tools capable of automatically recognizing text of specified length within SRT files and automatically annotating punctuation marks.

I wonder if there's an appropriate solution to this problem.

**Comment by Purfview** [comment]
> If this could be achieved, it would be truly great,sir.

Already implemented `a complete sentence per sub` yesterday [not released yet], then I spaghettified that code with unrelated "max_chars" and "max_lines" parameters and atm I lost whole logic of it... 😆  

> However, there is another issue bothering me: during transcribing some lengthy texts, there often appears a large chunk of text (possibly hundreds of characters in length) without any punctuation marks.

With what whisper engine? There will be like "max_gap_in_sentence" param.

**Comment by Purfview** [comment]
Implemented in 160.8.
Post feedback there-> https://github.com/Purfview/whisper-standalone-win/discussions/125
