### ISSUE TITLE
How to use GPU in Purfviews Faster Whisper?

### ISSUE THREAD

**Issue by JohnEvgen** [SubtitleEdit/subtitleedit#7664]
Hello. I am trying to use new Purfviews Faster Whisper, but it use CPU. In a command line I see this part. But what should I command to set in GPU use? 
![photo_2023-11-25_14-24-16](https://github.com/SubtitleEdit/subtitleedit/assets/101524261/1bb82bca-3373-4992-b142-e54dbe1bf2ca)
I have 4070ti and 5600x. GPU is much powerful than CPU. And I really want to use GPU. I tried to type commands like   
--device GPU, -d GPU, but nothing worked. What do I need to do?

**Comment by darnn** [comment]
`--device cuda`.

**Comment by JohnEvgen** [comment]
> `--device cuda`.

Thank you so much. I don't know if it works in full now or not, because Const me loaded the GPU at 100%, and here writes only 10% of usage, but the use of graphics memory has definitely increased.

**Comment by Purfview** [comment]
That info there is incorrect, `--device` default is not "cpu", it was for niksedk when he checked the help because he doesn't have cuda gpu.

**Default is "cuda" if CUDA device is detected, else is "cpu"!**

So basically you don't need to touch `--device`, unless a cuda gpu is not the first device.
