### ISSUE TITLE
Auto-translate errors

### ISSUE THREAD

**Issue by Purfview** [SubtitleEdit/subtitleedit#7667]
This error when selecting Bing Translate:

![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/69023953/4293c70e-6d83-41a1-a21f-a3099159903a)

Bit navigated around SE's tools without doing anything and now it doesn't let to "Auto-translate" at all:

![Screenshot_2](https://github.com/SubtitleEdit/subtitleedit/assets/69023953/8ab2c940-a05b-4faa-bcfe-4302414081f0)

Looked at LegacyDownloader it was True again for some reason, set it to False, now this error when selecting "Auto-translate":

![Screenshot_3](https://github.com/SubtitleEdit/subtitleedit/assets/69023953/699e1997-9d10-4375-b7e0-49800f46c0e3)

Maybe related: [Auto-translate some encoding problem](https://github.com/SubtitleEdit/subtitleedit/issues/7565)

**Comment by niksedk** [comment]
OK, `LegacyDownloader` is not longer auto after a download error.

Windows 7 and C# download is not a good match... sorry.
