### ISSUE TITLE
DeepL API key error

### ISSUE THREAD

**Issue by alvarusk** [SubtitleEdit/subtitleedit#7668]
Hi, I have a DeepL Pro Advanced account with its corresponding API key. I'm trying to use it in SE, but all I get is 'Bad API key.' Any ideas? Thanks.

**Comment by alvarusk** [comment]
If it further helps, I do have the DeepL Pro plug-in installed.

**Comment by niksedk** [comment]
Enable billing... 

And take this key (it ends with `:fx`):
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/a964ebe9-eb25-40f2-9d13-db27e241350c)
