### ISSUE TITLE
Focus lost on Text box

### ISSUE THREAD

**Issue by alvarusk** [SubtitleEdit/subtitleedit#7669]
Hi, when working in the Text box of any given subtitle, when you place the mouse _outside_ the box (in a regular layout, upwards to the subtitle grid or downwards to the audio wave, but not rightwards, to the video preview), the focus on the text is lost.

This is a minor thing, but incredibly annoying, and not sure if designed as intended. When reviewing subs, I make edits here and there. I use the mouse to place the text cursor at a certain place, then make my changes. Thing is, I click on the place, I move away the mouse to see clearly, I try to make the change, then nothing comes out because I lost the focus on the Text box. Hope that makes sense.

Is this intended? If so, for any particular reason? I think it wasn't like this in the past. Any ideas? Thanks.

**Comment by niksedk** [comment]
Works fine here... try restoring default settings, or uncheck these:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/0b8d85fb-9393-4465-9515-8cdd1284bdf0)
