### ISSUE TITLE
When reopening files, it doesn't keep space between gap duration

### ISSUE THREAD

**Issue by Hakunamatata67** [SubtitleEdit/subtitleedit#7675]
Hi,

Every time I'm reopening subtitles files, it doesn't keep gap duration between lines.
I had to manually I had to go to "Bridge gap in duration" or "set minimal duration" each time.

I don't know if it has anything to do with the Beautify timecodes, because I didn't have this issue before using that function.

**Comment by niksedk** [comment]
Please attach sample subtitle file + screenshots.

**Comment by niksedk** [comment]
ASSA time codes look like `0:00:03.25` and SRT time codes look like `00:00:03,250`... so ASSA time codes will be rounded to one less digit.
