### ISSUE TITLE
to Purfview 2

### ISSUE THREAD

**Issue by nielka98** [SubtitleEdit/subtitleedit#7677]
Hello, I have a request again. Do you already have a link to manually download it in Whisper Large version three?

**Comment by Purfview** [comment]
Why you don't post in the right repo-> https://github.com/Purfview/whisper-standalone-win 😀

>  Do you already have a link to manually download it in Whisper Large version three?

https://huggingface.co/Purfview/faster-whisper-large-v3-fp16

**Comment by nielka98** [comment]
Thanks, it will be downloaded tomorrow

**Comment by nielka98** [comment]
Thanks It will be downloaded tomorrow
