### ISSUE TITLE
Feature request: Play Current Line and Pause

### ISSUE THREAD

**Issue by ArtyIF** [SubtitleEdit/subtitleedit#7682]
[Subtitle Composer](https://subtitlecomposer.kde.org/), a subtitle editor for Linux (and Windows, although the builds are broken), has an option in the Video menu called "Play Current Line and Pause". It does exactly what it says - it seeks to the start position of the selected line, plays it and pauses once it reaches the end position. It's really useful to check if the line is synced with the audio.

I don't seem to have found a similar option in Subtitle Edit, so it would be very nice if it was added here.

**Comment by niksedk** [comment]
You can try `F5` (play selection),

Or you can setup a shortcut:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/5ea2c50d-8e66-48d8-a44b-933ae21f101b)

Or you can setup a double click action for list view:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/ee15018a-3171-4025-adfd-3969ea9b17cb)

**Comment by ArtyIF** [comment]
Got it. Then it should be make clearer that this option exists. Put it in a context menu for the line, maybe?
