### ISSUE TITLE
How to disable the "Beep" sound effect when doing Whisper...

### ISSUE THREAD

**Issue by shruru** [SubtitleEdit/subtitleedit#7684]
Hi , I batch list of movies for Whisper..each one done , got a "Beep" sound / notification. it's quite annoying sometimes. Is it able to disable it instead of mute the whole computer. Thank you. 🙏🏻

**Comment by darnn** [comment]
Presumably, you're using Whisper-Faster. In `Audio to text`, click `Advanced`, and in the text line add the following: `--beep_off`

**Comment by Purfview** [comment]
Much faster is to do the whole batch in one run. SE must be doing it all one by one, in such case it could add "--beep_off" automatically.

Only one disadvantage doing all in one run - if one file from batch is borked then whole process fails.
