### ISSUE TITLE
Auto Translate ( CN Language) is now really slow! on v4.0.2

### ISSUE THREAD

**Issue by JoqniX** [SubtitleEdit/subtitleedit#7686]
hello! i've recently updated to the latest version - v4.0.2! so i noticed that it takes forever! for "Google Translate V1 API" to translate!
i use the translate to chinese simplified one! ( seems this update brought new fixes and changes to cn translations) i wonder if its cuz of that? idk! 

usually it would take just 10mins or less than 20mins! on older versions! ( yes i do know that v1 api will be really slow without api key! but v4.0.1 was manageable! ) 
but now its taking more than 2-3hrs ;w;! please do look into this! and do provide a hotfix in the next update! 

for now ill switch to old version! since its really time consuming to wait so long for just auto-translate 1 subtitle file! when i could just revert to old version and finish 3-4 subfiles within this timeframe!

thanks again! for those who checked this issue! keep on doing a wonderful work out there devs! lob yu <3 thank you for doing your best!

**Comment by niksedk** [comment]
Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip ?

**Comment by JoqniX** [comment]
hello! sorry i didnt get notified until i checked my mail today! thanks for responding! 

> Auto-translate was rewritten in SE 4.0.2... it should produce a little better results for Latin languages where sentences end with a period. But... auto-translate now sends smaller chunks at a a time, so that's probably why you see a slow down.

ohh that's why! 

> Could you attach a typical Chinese subtitle? I assume Chinese does not use sentence endings like periods?

okie here yu go! so usually i use youtube's CC ( i download it using https://downsub.com/ ), so for  videos/livestreams more than 5+hrs youtube's chinese subtiles kinda breaks and becomes empty after like 1hr or 2hr ? or something idk why? so i translate the english cc to chinese ( simplified ) 

---
so ill post the subtitle stuff here - ( since i couldnt upload it directly i made a zip file for it!)

zip file: - 
[Subtitless.zip](https://github.com/SubtitleEdit/subtitleedit/files/13541482/Subtitless.zip)


there will be 2 folders - ones i had gotten from youtube using subtitle.to/ and processed on subtitle edit ( which fixes the removes extra dots etc ) using fix common errors option.
i usually do these for chinese 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/54277349/f4940467-3c47-41eb-9d26-947ab7402c10)
same thingy with english as well. 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/54277349/7ce05a60-2542-49af-a00b-4bcca047b21e)

and raw ones . which are not processed. 
and directly fresh from https://downsub.com/ 

the ones which are titled [ English ] - feel free to put it on subtitle edit and auto translate to chinese simplified. 
the ones titled [ Chinese Simplied ] - are ones from youtube auto cc. 

---

> Could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip ?

yes i did test this beta out! apparently i got a error when trying to autotranslate to chinese simplied!
ref the file from > "\Subtitless\Processed in Subtitle Edit\[English (auto-generated)] 【Co-Working】✦ let's work on the credits page for the website in framer! [ Twitch POV ] [DownSub.com].srt" 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/54277349/80612732-c4f3-4c72-a8e7-2333b185df89)
and try to use the auto translate and change language to chinese simplied. and see if you could also reproduce the same bug? 

i tried with v4.0.1 - it doesnt show that error for this same file! 
![SubtitleEdit_xwzjm8JuL6](https://github.com/SubtitleEdit/subtitleedit/assets/54277349/e56c0dd5-afc3-48f8-8d23-26bb9036d872)

**Comment by niksedk** [comment]
Hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
