### ISSUE TITLE
Missing output formats?

### ISSUE THREAD

**Issue by Purfview** [SubtitleEdit/subtitleedit#7688]
Missing or I can't find these output formats:
1) Wanted to save subtitle to plain text, just text without any timestamps and ect.
2) TSV [Tab-separated values]

How TSV looks like [numbers are milliseconds]:

```
start	end	text
2080	5600	With their signature orange fur and black stripes,
6180	11180	tigers have become icons of beauty, power, and the importance of conservation.
13100	15800	Tigers have evolved into six subspecies.
```

**Comment by niksedk** [comment]
Added two TSV formats in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

SE has export plain text via File - Export - Plain text (or a shortcut):

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/91f16879-6d89-45b1-8447-4a5e37d028e0)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/912a968c-31e1-4d06-b0a2-d96fadb630c4)

**Comment by Purfview** [comment]
There is so many features that's hard to know them all.

Thank you!
