### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by hugok79** [SubtitleEdit/subtitleedit#7689]
![Error](https://github.com/SubtitleEdit/subtitleedit/assets/16929048/ab04254d-bca0-46de-a400-4017e5afcafb)

**Comment by niksedk** [comment]
Looks like it's some error that occurs when you're extracting audio from a video file. 

You should be able to switch between ffmpeg or vlc in Options - Settings - Waveform.
You could try ffmpeg versions from here: https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/releases

(do consider upgrading to 64-bit Windows 10/11 some time in the future)

**Comment by hugok79** [comment]
Thanks for your reply. Your tip works!
This is an old potato laptop... ASUS T100TAM laptop running Windows 8.1 32-bit
