### ISSUE TITLE
Options to hide video / waveforms have been removed in 4.0.2

### ISSUE THREAD

**Issue by bronis75** [SubtitleEdit/subtitleedit#7690]
Hi,

Before 4.0.2, we could hide the waveform and video windows in options menu. So that they do not show up everytime we start SubtitleEdit.

Before : 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/44083671/e0af80b2-8f50-4e2b-aa7b-7a1e57a4add4)

Now in 4.0.2 the option  has been removed : 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/44083671/9d2c5d22-3fc6-47ea-8a68-167ac4016819)
We can only detach these windows, but at each startup we have to close them...

Regards,

**Comment by niksedk** [comment]
Show/hide video and Show/hide waveform have been replaced by layouts - layout 12 has neither video nor waveform.

Read more here: https://github.com/SubtitleEdit/subtitleedit/issues/7482#issuecomment-1821244059

**Comment by niksedk** [comment]
Do you have the "Layout" icon in the toolbar?

**Comment by bronis75** [comment]
Yes thank you !
 i was actually looking for  "text" menus, I did not think about icons to change layouts.

**Comment by juanmbt** [comment]
I know this is old and already closed as completed, but I just updated after not using the program for many months.

The help page still shows the old way to Show/Hide controls:

https://www.nikse.dk/subtitleedit/help#main_resize

![image](https://github.com/SubtitleEdit/subtitleedit/assets/21691159/0c8c2329-47f2-4765-979f-889439612a5d)
