### ISSUE TITLE
Make True as default for <AssaResolutionAutoNew>

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7691]
Everytime when I try to update SE by unzipping directly to the existing directory to overwrite existing files with newer ones, the **AssaResolutionAutoNew** tag was always set to False afterwards, so I have to manually change it to True after EACH update like this, which is kinda annoying... Can we please improve it a bit?

**Comment by niksedk** [comment]
Hm, these should be the default values

````csharp
            AssaResolutionAutoNew = true;
            AssaResolutionPromptChange = true;
            AssaShowScaledBorderAndShadow = true;

````

How can I test this?

**Comment by LeonCheung** [comment]
The thing is that I didn't remember when and how... It just happens, for times. Not sure what triggered it yet. Maybe I'll keep an eye on it and update here.

**Comment by LeonCheung** [comment]
Closing for now.
