### ISSUE TITLE
Whisper X

### ISSUE THREAD

**Issue by Link70903** [SubtitleEdit/subtitleedit#7695]
How can i use whisper x in subtitle edit. I am bad in this stuff. Help

**Comment by niksedk** [comment]
If you're some a lot of time to spare and are looking for trouble the:

- Read more here: https://github.com/SubtitleEdit/subtitleedit/issues/6914

- And follow the instructions here *very* carefully (yes, you need conda): https://github.com/m-bain/whisperX
