### ISSUE TITLE
Error occurred : Can't find '*.srt' file

### ISSUE THREAD

**Issue by ddoddohee** [SubtitleEdit/subtitleedit#7696]
![스크린샷 2023-12-02 142315](https://github.com/SubtitleEdit/subtitleedit/assets/152710878/80d7d6ed-9471-4492-aa61-a98e80ca97cc)

**Comment by niksedk** [comment]
Does SE have write permission to the target folder?

**Comment by ddoddohee** [comment]
Now I'm trying it on 'D:' drive.
While I'm writing this mail, I get the message " 1 file saved to the video source folder."
I think It was the permission issue.
Thanks for letting me know.



-----Original Message-----
