### ISSUE TITLE
Ctrl+Shift+Alt+F12 opens Word split dictionary generator and no way to redefine shortcut

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#7698]
Ctrl+Shift+Alt+F12 opens **Word split dictionary generator** and no way to redefine shortcut in settings.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/44278c6e-d937-4a4f-ad5b-0ae6f5355199)

**Comment by niksedk** [comment]
Is it blocking a shortcut you want to use?

This is more an internal tool. Was not really intended for users...
