### ISSUE TITLE
Question regarding selecting subtitles with shortcuts

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#7700]
Is there a way to select the subtitle that my playhead is on right now without playing ? tried to find a way, but there seems no way to do this. 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/389422cd-e154-4900-86e6-81049e6c2256)

**Comment by niksedk** [comment]
Could this one work?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/90370234-2d24-4829-98c0-603d4425b932)

**Comment by rRobis** [comment]
ok i was just trying to explain my cause in depth, but realized that i was trying to bypass the root problem that i was trying to solve.

Basically i needed this because i want to be able to move the bordering gap around.

I made the minimum subtitle length less, so it now allows me to make the subtitle shorter with the shortcuts (before i couldn't figure out why it works in some situations and in others not).

But i think i miss one shortcut

Is it possible to make an analogue to this one, but with end?

This one seems to work fine  **Set start and set end of previous (minus min gap)**

**Comment by rRobis** [comment]
It seems like this one is working as i wanted. 

The only problem that I found is that if i have a subtitle that takes about 3 or 4 seconds, and I try to set the end at about 1 second of the selected subtitle, it doesn't set the end of the next subtitle.  If i put it closer to the next one, then it does work as expected.
 
 
 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/f0a8a7af-3f92-4ffd-8719-81ac6e37041a)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/ec1037da-5ee6-4f9b-b140-15e6009d0c2b)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/4b4a36d9-4912-4bc3-b6c6-e58c4df1c4ee)

**Comment by niksedk** [comment]
OK, the shortcut now allows to move the next subtitle up, if it's closer than 5 seconds - does that seem like an okay value or ?

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by rRobis** [comment]
Maybe it's possible to make an identical shortcut, but without the limit at all? Or have an option to define or disable the limit. In some cases, the 5 seconds is not enough.
