### ISSUE TITLE
Problem with translation and breakdown of lines

### ISSUE THREAD

**Issue by odyn1982** [SubtitleEdit/subtitleedit#7701]
Hello,

I have a problem with translating the subtitles from English to Polish.
The program splits the translation of the line into two lines. Using Google or Microsoft Translator doesn't change anything.
This problem does not occur when I translate subtitles via an online website.
I am attaching a photo and a file with subtitles.
Please help me how to set the program so that the translated subtitles have the same number of lines.
![Automatic Translation](https://github.com/SubtitleEdit/subtitleedit/assets/117115809/78c7b5f5-643d-428c-84bf-e7f8a0c83c92)
[Translation.zip](https://github.com/SubtitleEdit/subtitleedit/files/13538788/Translation.zip)

**Comment by niksedk** [comment]
@odyn1982 I presume you have invalidated the API key?

**Comment by odyn1982** [comment]
No, API Keys are working fine. I have keys for Google API v2 and Bing Microsoft Translator.

**Comment by odyn1982** [comment]
I understand now :)

**Comment by odyn1982** [comment]
And Google Translate error also:
![2023-12-03 17_34_20-Google Translate](https://github.com/SubtitleEdit/subtitleedit/assets/117115809/559b721b-75a8-469e-a7f3-5c247bc0ab47)

**Comment by odyn1982** [comment]
Unfortunately, the translation of subtitles by Google Translate v2 API and Microsoft Bing Translator stops halfway due to errors. I am attaching screenshots of both errors.
![GOOGLE TRANSLATE ERROR](https://github.com/SubtitleEdit/subtitleedit/assets/117115809/19cf4706-2928-460d-a658-4b9bb2f73ded)
![MICROSOFT BING TRANSLATOR ERROR](https://github.com/SubtitleEdit/subtitleedit/assets/117115809/445afe24-aae1-46dd-96a8-45f493aed637)

**Comment by niksedk** [comment]
Could you try latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by odyn1982** [comment]
It is better because the entire file can be translated into Polish, but the original text sometimes ends up in other lines, as can be seen in the attached screenshots.
![Translation](https://github.com/SubtitleEdit/subtitleedit/assets/117115809/bb96be43-b2ce-413a-a869-30056c06ac13)
![Translation2](https://github.com/SubtitleEdit/subtitleedit/assets/117115809/58807dd6-e379-4fc8-bd17-bf191d280ede)
[subtitles_eng.zip](https://github.com/SubtitleEdit/subtitleedit/files/13689680/subtitles_eng.zip)

**Comment by diegomagalhaesm** [comment]
Also happening to me. I tried the beta versions provided, but didn't work as well.

I think the behavior it's just the opposite of what was reported. Hope this helps.
The translation highlighted in yellow should be in the next line.

![Subtitle Edit split lines](https://github.com/SubtitleEdit/subtitleedit/assets/23707904/abfc5b35-6a9d-4505-87e3-2791fc4e8c63)
