### ISSUE TITLE
Merge lines until punctuations/capitalized words

### ISSUE THREAD

**Issue by MilkAndBanana1** [SubtitleEdit/subtitleedit#7703]
I have noticed that merging short lines with word level timestamps doesn't take into account capitalized words and punctuation marks and both can end up at the middle of the sentence which looks unpleasant.
Example Output:
```49
00:00:41,990 --> 00:00:43,380
you Why does

50
00:00:43,390 --> 00:00:44,160
google have so

51
00:00:44,170 --> 00:00:44,950
many photos of

52
00:00:44,110 --> 00:00:45,480
you? Okay, you
```
Desired Output:
```49
00:00:41,990 --> 00:00:42,110
you 

50
00:00:42,110 ---> 00:00:43,380
Why does

51
00:00:43,390 --> 00:00:44,160
google have so

52
00:00:44,170 --> 00:00:44,950
many photos of

53
00:00:44,110 --> 00:00:44,300
you? 

54
00:00:44,400 ---> 00:00:45,480
Okay, you
```
Since I primarily work with word level timestamps, it would take the capitalized word/word with punctuation timestamp and use the next word's timestamp as reference for the end timestamp since it's mostly just to fix the appearing in the middle issue.

**Comment by niksedk** [comment]
Where are what are you doing?
I cannot follow what you mean... could you explain a bit more? Are your examples correct?

**Comment by Purfview** [comment]
> ...doesn't take into account capitalized words... 

Problem is that Capital doesn't mean a new sentence.

If you are using Faster-Whisper then you can try `--standard` option, you would need to download a new version, option is till WIP.  [btw, disable SE's auto auto-tweaks]

> I cannot follow what you mean...

I think he meant merging subtitles were every word comes as a separate sub line.
