### ISSUE TITLE
lost my settings after update

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#7705]
Hello,

I haven't used SE in a long time, and the last version I had was 3.6.5. Today, I updated to the latest beta (I use only portable versions).

I noticed that SE looks different. The size of the translation box, video preview, etc., is not the same as I set. Most importantly, it seems like my settings and shortcuts (or at least most of them) are gone. I copied my settings.xml into SE dictionary, but many saved settings/shortcuts, such as "ExtendToNextSceneChangeWithGap," appear to be missing.

I don't know what's going on. Is my settings.xml too old for the new version of SE? I guess I will have to stick with 3.6.5 for now.

**Comment by niksedk** [comment]
Hi @m0ck69,

We have worked hard on trying to improve SE, so there's a lot of changes in 4.x.
The toolbar button and many controls look a little different.
See https://github.com/SubtitleEdit/subtitleedit/issues/7323
I'm not sure if I like the "Black icons" or the "Legacy icons" best... what do you think? Or do you prefer the dark theme (which is much improved)?


>ExtendToNextSceneChangeWithGap

I think the shortcuts has been replaced by Flitskikker to `MainAdjustExtendToNextSubtitleMinusChainingGap` :
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/1e88c641-622d-482e-af5e-887d956d24b4)

Do check the related PR out from Flitskikker : https://github.com/SubtitleEdit/subtitleedit/pull/7105

If the old one was simpler to use for you, we can add it back.

**Comment by m0ck69** [comment]
@niksedk `MainAdjustExtendToNextSubtitleMinusChainingGap` is compleely broken. Does not work at all.

Also, where are those now? Couldn't finf them.

![1](https://github.com/SubtitleEdit/subtitleedit/assets/46628545/f8678d6f-f434-40b6-9468-6b2468b256cc)

**Comment by Peppins32** [comment]
I've got the same issue, i've lost everything, the multiple replace settings, the dictionary, everything. Many thanks devs, years of work lost in an instand, thanks again (restore from windows backup didn't help)...
