### ISSUE TITLE
"Ghost" XML subtitle in "Reopen" list 

### ISSUE THREAD

**Issue by F5System** [SubtitleEdit/subtitleedit#7706]
There is a "ghost" xml subtitle in "Reopen" list when you close D-Cinema interop (.xml) subtitle without saving it. The XML on the screenshot doesn't exist, but it is in the list.
![SE](https://github.com/SubtitleEdit/subtitleedit/assets/7966722/4beca299-28b8-4154-bdc2-9e031f0badfc)

To reproduce:

1. Open SRT subtitle
2. Change format to D-Cinema interop (.xml)
3. Reopen some old subtitle from "File - Reopen"
4. Choose "NO" in the dialog "Save changes to xxx.xml ?"
5. Go to "File - Reopen" and see that now there are two lines for previous subtitle:
xxx.SRT
xxx.XML
6. If you click on this not saved .XML it will popup window "File not found xxx.XML"

This connects with my workaround with my another D-Cinema bug https://github.com/SubtitleEdit/subtitleedit/issues/5032

**Comment by niksedk** [comment]
I've tried to fix it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
How does that work?

**Comment by F5System** [comment]
Yes, looks like it is fixed now. Great, thanks once more for great app! I'll donate ;)
