### ISSUE TITLE
how to merge multiple blank lines to precede line?

### ISSUE THREAD

**Issue by llurk** [SubtitleEdit/subtitleedit#7711]
I am experiencing issues and need assistance with subtitle files. My generated file contains many blank lines, and these lines take up the time of the previous line, causing it to disappear faster. How can I automatically merge multiple blank lines into the preceding line?

![Screenshot 2023-12-07 171349](https://github.com/SubtitleEdit/subtitleedit/assets/134845325/79beb1d5-0173-4fba-b33e-fb6d89479a7f)
![Screenshot 2023-12-07 172753](https://github.com/SubtitleEdit/subtitleedit/assets/134845325/3c75a02e-82ad-4ccd-952e-d3b199da33a9)

**Comment by niksedk** [comment]
You can try `Merge selected lines`

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/38fc7f80-a994-4cba-9b4b-9bd6a619362d)


It even has a shortcut:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/4e2abb35-e2e5-428d-ad5e-8a5f351c6dd7)

**Comment by nielka98** [comment]
But I also have this problem and could someone advise how to solve it
