### ISSUE TITLE
0.5 second sound problem

### ISSUE THREAD

**Issue by tctccc** [SubtitleEdit/subtitleedit#7712]
Hello
When I play a video, it always starts without sound for about 0.5 second.
For example if a line is 'Nice to meet you', I can only hear 'to meet you'.
How can I fix this problem? I would really appreciate a solution.
Thank you.

**Comment by niksedk** [comment]
What video player are you using inside SE?
`mpv` is normally the recommended video player.

**Comment by niksedk** [comment]
You could try updating your drivers for video and audio.
You could also try direct show - probably install with lav filters ( this version seems best: https://github.com/Nevcairiel/LAVFilters/releases/download/0.77.2/LAVFilters-0.77.2-Installer.exe )
