### ISSUE TITLE
Whisper v 3

### ISSUE THREAD

**Issue by nielka98** [SubtitleEdit/subtitleedit#7714]
Hi, I have been using Whisper Large version 3 on the Purfview engine for some time now If I'm honest, this model is terrible and I'm wondering whether this model works better on other engines or has Open just messed something up? because it was supposed to be better, it isn't

**Comment by niksedk** [comment]
What language are you transcribing?

Did you try OpenAI and CPP ?
It could be interesting doing a comparison!

**Comment by nielka98** [comment]
> W jakim języku dokonujesz transkrypcji?

in Italio

**Comment by nielka98** [comment]
> Did you try OpenAI and CPP ? It could be interesting doing a comparison!

And how to install open ai engine

**Comment by Purfview** [comment]
`large-v3` is bad, in OpenAI it's much worse.

**Comment by nielka98** [comment]
and on other engines, should we accept that this model is stupid and wait for new ones?

**Comment by Purfview** [comment]
Models are made by OpenAI, if there it's bad then it will be same in all engines.

**Comment by darnn** [comment]
I've noticed some improvement in Hebrew in V3, FWIW. It definitely produces something that's easier to edit later, even if it might be more "wrong" in some places.

**Comment by Purfview** [comment]
@darnn
> I've noticed some improvement in Hebrew in V3, FWIW. It definitely produces something that's easier to edit later, even if it might be more "wrong" in some places.

I'm testing new beta -> https://we.tl/t-ZKEB5J0Uvk

Try it with `--reprompt=2`.

Btw, I wonder how this reverse stuff actually work in whisper, what you get if you use `--sentence` or `--standard` switches?

**Comment by nielka98** [comment]
And apart from the topic at hand, now I wonder why Google won't do something similar to whisper

**Comment by niksedk** [comment]
I did some tests with the large models and Danish audio file from YouTube with a duration of 1 min and 42 seconds.

Wave file: [Danish.zip](https://github.com/SubtitleEdit/subtitleedit/files/13619277/Danish.zip)
CPU only:  i7-1065G7 CPU, 1.30GHz
Engines was tested with default settings. 
`PFW=Purfview's Faster Whisper`  and `CPP=Whisper CPP` and `OAI=OpenAI Whisper`

| Engine   | Model   | Errors  | Time   |
|---|---|---|---|
|  PFW | Large V2  | 5 | 6:30  |   
|  PFW | Large V3  | 8 | 6:43  |   
|  CPP | Large V2   | 4 | 10:50 |   
|  CPP | Large V3   | 6 | 10:40 |   
|  OAI | Large V2  | 4 | 28:27  |   
|  OAI | Large V3  | 6 | 28:19  |   

------
------

It's not wise to conclude too much for only one test, but it does look like that V2 could be better for non-English.

I did a test with English too, but it was spot on - only a few errors that I could not really hear myself ;)

------


------

>And apart from the topic at hand, now I wonder why Google won't do something similar to whisper

Google/YouTube have had something similar for many years. It's just not open... and not nearly as good.

**Comment by nielka98** [comment]
> Engine	Model	Errors	Time
> PFW	Large V2	5	6:30
> PFW	Large V3	8	6:43
> CPP	Large V2	4	10:50
> CPP	Large V3	6	10:40
> OAI	Large V2	4	28:27
> OAI	Large V3	6	28:19


.😮🤯
is it that bad? shocking

**Comment by nielka98** [comment]
And apart from the topic, today I did some tests and it turns out that it works better if it has an MP3 file rather than an MP4 one, interesting

**Comment by Jabe64** [comment]
> I did some tests with the large models and a Danish audio file from YouTube with a duration of 1 min and 42 seconds.
> 
> Wave file: [Danish.zip](https://github.com/SubtitleEdit/subtitleedit/files/13619277/Danish.zip) CPU only: i7-1065G7 CPU, 1.30GHz Engines were tested with default settings. `PFW=Purfview's Faster Whisper` and `CPP=Whisper CPP` and `OAI=OpenAI Whisper`
> 
> Engine	Model	Errors	Time
> PFW	Large V2	5	6:30
> PFW	Large V3	8	6:43
> CPP	Large V2	4	10:50
> CPP	Large V3	6	10:40
> OAI	Large V2	4	28:27
> OAI	Large V3	6	28:19
> It's not wise to conclude too much from only one test, but it does look like that V2 could be better for non-English.
> 
> The V3 model did seem to include some interjections, that the V2 model removed.
> 
> I did a test with English too, but it was spot on - only a few errors that I could not really hear myself ;)
> 
> > And apart from the topic at hand, now I wonder why Google won't do something similar to whisper
> 
> Google/YouTube have had something similar for many years. It's just not open... and not nearly as good.

Hi @niksedk ,

Thanks for the amazing work on Subtitle Edit. I really prefer to have more accurate transcription than faster with lot of mistakes and losing time afterwards correcting everything. 

In my case I bought a computer with a new dedicated GPU specifically for this purpose and with the same test it would probably go way faster than with an iGPU.

It would be great to implement option directly in Subtitle Edit to set better accuracy (for example I read about --beam-size 20 [here]([url](https://github.com/SubtitleEdit/subtitleedit/issues/7723)) but I didn't achieve to use it).

And maybe add a little note/warning explaining that activating these settings would give better results but slow down the process.

By the way I read in the changelog about [version 4.0.3](https://raw.githubusercontent.com/SubtitleEdit/subtitleedit/master/Changelog.txt) but I can't find the Beta download link. Is it available to test somewhere? Is it better to use this Beta version for slower but more accurate use of Whisper v3?

Please let me know.

**Comment by Jabe64** [comment]
> > It would be great to implement option directly in Subtitle Edit to set better accuracy (for example I read about --beam-size 20...
> 
> That was a joke. 😉

Oh thanks a lot for the clarification, I didn't get the joke at all 😂

**Comment by niksedk** [comment]
See about beam size here: https://github.com/SYSTRAN/faster-whisper/issues/392

You can try with a beam size of 10 - click on the "Advanced" button in the Whisper Window:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/1bde61a7-f103-448d-b905-c89b1ca1ace7)

**Comment by Jabe64** [comment]
> See about beam size here: [SYSTRAN/faster-whisper#392](https://github.com/SYSTRAN/faster-whisper/issues/392)
> 
> You can try with a beam size of 10 - click on the "Advanced" button in the Whisper Window: 

Thanks a lot I will definitely look into this 👍
