### ISSUE TITLE
IT IS POSSIBLE TO ADJUST THE POST-PROCESSING FUNCTION?

### ISSUE THREAD

**Issue by raphaelomoreira** [SubtitleEdit/subtitleedit#7716]
Is the use of post-processing directly linked to any adjustment in the Subtitle Edit Options or are they pre-determined adjustments?
Is there no way to make personal adjustments in this post-processing?
For some things it is very useful, but for others it is not good.
Maybe small adjustments will improve!

![post-processing](https://github.com/SubtitleEdit/subtitleedit/assets/105943943/0454f29d-dd4f-449c-a8d5-052bf1748919)

**Comment by raphaelomoreira** [comment]
The intention is wonderful, but not everything is working 100%. It would be interesting if this option was linked to the **Options** parameters that we customized in Subtitle Edit.

**Comment by niksedk** [comment]
> Imho, it's creating more problems than it's fixing

Could you please give some examples? (audio + text)

**Comment by niksedk** [comment]
It's possible to adjust the settings now:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/37f3cdef-6d94-4895-a3ba-aac336839484)


https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

Note that the current line settings / auto-break setting are used for split and merge.

**Comment by raphaelomoreira** [comment]
Some functions still work even with some options unchecked.
See an example below, please.
Only Fix casing unchecked in Settings should make the word victory lowercase, but Subtitle Edit is still making it capitalized.
But if I uncheck Use post-processing, Subtitle Edit makes the word lowercase.
The word victory is not a proper name for a person in Portuguese in this context. Therefore it must be lowercase.
Whisper normally handles this.

![Vitoria_1](https://github.com/SubtitleEdit/subtitleedit/assets/105943943/cff0180b-7530-4f69-bba8-5e3c08e084a6)


![Vitoria_2](https://github.com/SubtitleEdit/subtitleedit/assets/105943943/6f4070f7-0683-4659-8d4f-a4562c41f955)

**Comment by niksedk** [comment]
Another bug, thx for testing again :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
