### ISSUE TITLE
Numpad operator shortcuts activating in Text field

### ISSUE THREAD

**Issue by pandalamp** [SubtitleEdit/subtitleedit#7717]
In Subtitle Edit 4.0.2, if any Numpad operators (/*-+.) are assigned to a shortcut, the shortcut will activate even when they key is pressed inside the main Text field. Was this an intentional change?

For example, if the shortcut _"Set start time"_ is set to the Subtract key, using that key to enter a dash into the Text field will _move the line's start time_ instead of entering the character. I routinely use the Numpad operator keys for quick access to those characters as text, and until 4.0.2 those keys have always worked as normal input in the Text field even when assigned to shortcuts.

Essentially, typing in the text field used to be exempt from firing those shortcuts.

I can modify my shortcuts with Ctrl or Alt if this is working as intended, but wanted to check here first.

Thank you!

**Comment by niksedk** [comment]
I think you're looking for this?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/c3d2db44-cdb6-41ff-adc6-4c7d957115db)

**Comment by pandalamp** [comment]
> I think you're looking for this?

Thank you, but that option does not seem to have any effect on the behavior I described. Using the example above, pressing the Subtract key to enter a dash into the Text field will still activate its assigned hotkey and fail to input the character whether or not that box is checked.

**Comment by niksedk** [comment]
These keys (divide/subtract/add/multiply) should probably work like single letters/digits... and now the hopefully do:
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

So you should now be able to control the behavior via this:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/8f8524a5-a5bb-4a04-a2a9-4652e2b6824a)

**Comment by pandalamp** [comment]
> These keys (divide/subtract/add/multiply) should probably work like single letters/digits... and now the hopefully do: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

That's working perfectly. Thank you so much Nikolaj!
