### ISSUE TITLE
How to save settings about choised languages in Auto translation window? Ver. 4.0.2

### ISSUE THREAD

**Issue by rewolw** [SubtitleEdit/subtitleedit#7720]
In the Auto Translate window, I can select the language and translation service. If I leave this window, the translation service information is saved, but the information about the selected languages is not saved. It is very inconvenient to select languages every time. Ver. 4.0.2

Or how can I save this settings?

**Comment by niksedk** [comment]
It is save here on my computer ;)

Could you make some screenshots?
