### ISSUE TITLE
Best New Function + Fix for [BLEEP]

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#7722]
Best Function EVER is >> Remove text for Hearing Impaired > Remove if ONLY Music Symbols
Thanx a LOT for that, it's Very Useful!

Now you just have to Fix the constant problem with [bleep] -- that mostly shall Remain or else the Sentences mostly doesn't make sense -- that should instead be 'Auto'-changed to =BLEEP= so it doesn't conflict with the "Remove text between [ ]" function!

**Comment by niksedk** [comment]
I'm glad you like the new feature :)

Where is [Bleep] handled wrong? Could you give a few examples?

**Comment by niksedk** [comment]
OK, feel free to post again, when you run into a subtitle list this (I do not remember seeing this).
