### ISSUE TITLE
to Purfview - Whisper best settings

### ISSUE THREAD

**Issue by nielka98** [SubtitleEdit/subtitleedit#7723]
I know this isn't the right place for this, but I don't know where to write to you, so I'm writing here. I need help. Are there any commands that will make Whisper more accurate and better? If so, could you tell me please?

**Comment by uckthis** [comment]
--beam-size 20 would be very accurate.

**Comment by nielka98** [comment]
doesn't work

**Comment by niksedk** [comment]
For Purfview's faster whisper, post here: https://github.com/Purfview/whisper-standalone-win
