### ISSUE TITLE
How are audios with variable bitrate handled?

### ISSUE THREAD

**Issue by sukiletxe** [SubtitleEdit/subtitleedit#7724]
When I open an audio file with variable bitrate and its corresponding subtitle (created by using a file which had constant bitrate), Subtitle Edit's adjustment of time seems to not be correct. Specifically, when I check where a subtitle starts and ends with F5, the placement is not correct. Interestingly, this problem goes away when using constant bitrates, even if the bitrates are different (or so it seems according to my tests).

**Comment by niksedk** [comment]
SE just uses time internally to sync subtitles, so I think variable frame rate or variable bit rate should work fine. SE just relies of what it gets from the video player (mpv, directhos, or vlc).

**Comment by sukiletxe** [comment]
Ah OK. Just realised I was using the default player (Direct Show). I've switched to MPV and the issue is gone. Thanks a lot! Closing.
