### ISSUE TITLE
When I use Chatgpt translate Japanese to Chinese ，error。

### ISSUE THREAD

**Issue by tianshi12138** [SubtitleEdit/subtitleedit#7728]
![VL HN%DK5_J3 U }F_`1@5](https://github.com/SubtitleEdit/subtitleedit/assets/153604164/ffa37eba-8619-4b00-852a-a40935c8713a)
You can see，some Japanese can be translated and error， but sometimes nothing can be translated success。

**Comment by niksedk** [comment]
it says `too many requests`: ChatGPT atm only allow for 3 request per minute, and about 50 requests per hour. If you want more, you will need to pay.
