### ISSUE TITLE
Bad API Key for DeepL Pro

### ISSUE THREAD

**Issue by magnetic-moon** [SubtitleEdit/subtitleedit#7729]
Hi. I've been subscribing for Deepl Pro Advance. I've put my API key on SE and findout with this error. Anyone can help?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/100338624/d2266971-1f73-468b-b4b9-441b7cd119e1)

I use Subtitle Edit Beta Version. Thank you in advance!

**Comment by niksedk** [comment]
It's says wrong endpoint, you could try updating the endpoint - see Options - Settings - Auto-translate
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/6f90a4cc-5127-46c6-bca4-2c36fb331194)

**Comment by henrycrisna** [comment]
after changing it's shown like this
![image](https://github.com/SubtitleEdit/subtitleedit/assets/100338624/25c3ae26-013e-4858-adf1-e4b8740d95a7)

**Comment by niksedk** [comment]
Could you tell more about the api key and how you made it? 

Which one do you have?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/3f4dd2a9-6c7d-4329-93c7-3bdb4ee07009)


Did you enable billing or ?

**Comment by niksedk** [comment]
And better error handling in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by magnetic-moon** [comment]
the error log shown like this one

Date: 12/14/2023 15:45:49
SE: 4.0.2.0 - Microsoft Windows NT 10.0.22000.0 - 64-bit

System.Exception
Message: Bad API key
StackTrace:    at Nikse.SubtitleEdit.Core.AutoTranslate.DeepLTranslate.Translate(String text, String sourceLanguageCode, String targetLanguageCode)
   at Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__21.MoveNext()

After using the Beta one, it keep show like this
![image](https://github.com/SubtitleEdit/subtitleedit/assets/100338624/90a2e768-3f6a-4b57-a5ff-68b26d3201a0)

**Comment by niksedk** [comment]
Thx for testing... another beta uploaded: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
Any better?
It now allows updating DeepL url directly in the auto-translate window.

**Comment by magnetic-moon** [comment]
It just shown the same on two both DeepL url.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/100338624/858f8f12-befd-4073-8749-564fffb65f4c)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/100338624/da554107-c304-435f-9638-2004879e4196)

I'm gonna make sure. The API code is from here, right?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/100338624/be9e6097-fb70-43ab-9556-819f1b931179)

**Comment by niksedk** [comment]
Do you something like this (under `Account`) ?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/c96385b5-8c0d-49f4-9853-83dab340f06d)

**Comment by magnetic-moon** [comment]
I think because it's pro account, it's look like different one? I dont have any code with "fx" as the ending.

**Comment by niksedk** [comment]
There's not some PRO DeepL API key?
Is only "CAT tools" API key available?

**Comment by magnetic-moon** [comment]
No, the API Key is only the one I've provide before.
