### ISSUE TITLE
French orthography

### ISSUE THREAD

**Issue by tormento** [SubtitleEdit/subtitleedit#7730]
Please add the following vowels to french language popup, as I think that some are missing.

I know that there are doubles with the ones that we already have, but I preferred to have a complete list.

Àà, Ââ, Ææ
Çç
Éé, Èè, Êê, Ëë
Îî, Ïï
Ôô, Œœ
Ùù, Ûû, Üü
Ÿÿ

**Comment by niksedk** [comment]
Thx for the info :)
Should now be included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
