### ISSUE TITLE
BUG that occurs when using the Merge short lines function.

### ISSUE THREAD

**Issue by despairTK** [SubtitleEdit/subtitleedit#7735]
When the first line ends with numbers or some special symbols at the end of the sentence, it cannot be merged with the next line.

![QQ截图20231214212747](https://github.com/SubtitleEdit/subtitleedit/assets/111871110/f07e7630-befb-49ab-bd34-111dd6453074)
![QQ截图20231214212755](https://github.com/SubtitleEdit/subtitleedit/assets/111871110/cc2747fd-c400-4ce9-8e9d-030d0e6bda7d)

**Comment by niksedk** [comment]
Thx for the info :)
Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
