### ISSUE TITLE
A little yet convenient option for burning videos

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7737]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/f74980c6-2125-4d48-a86e-01c66c29bc2a)

SE will remember the directory used for the previous file. However, when burning videos for different projects, we have to navigate to the target folder manually each time (which usually should be where the current source video is located). A small toggle would save so much time.  :)

**Comment by niksedk** [comment]
Would just always default to the source folder be okay?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Ah, even better. Thanks for the prompt response! Closing.
