### ISSUE TITLE
Feature request: Loop current subtitle

### ISSUE THREAD

**Issue by thelabcat** [SubtitleEdit/subtitleedit#7739]
While making some subtitles where the person is talking particularly fast, I think it would be helpful if the region of audio just kept playing over and over while I typed. Maybe adding a toggle button somewhere to loop the selected subtitle's region?

**Comment by niksedk** [comment]
You can setup a short for loop:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/a5903725-dba7-4106-886f-837edc106d3d)

Or you can use the more advanced translator mode, when you can setup `repeat count` + auto-continue:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/37a7389d-0e37-4d71-a6ea-eafc635482e3)
