### ISSUE TITLE
Apply Netflix Rules for frames around shot changes - issue

### ISSUE THREAD

**Issue by ludem93** [SubtitleEdit/subtitleedit#7740]
<img width="334" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/94044360/49cc3863-eecc-4190-8a84-612722f241d3">

This happens when I go to

Options
Settings
Waveform/Spectogram
Edit profile... (next to "Snap to shot changes")
Simple mode...
Load Netflix rules
OK

**Comment by niksedk** [comment]
Could you supply the subtitle file + video file?

**Comment by ludem93** [comment]
it happens regardless of subtitle files and video files, just tried it on various videos.
i would drop settings.xml if I knew where it is :)

**Comment by niksedk** [comment]
OK, interesting.
You can find your settings.xml in your SE data folder (press Ctrl+Alt+Shift+D in the SE main window to open this folder).

What video player are you using in SE? mpv?

@Flitskikker: Any ideas?

**Comment by Flitskikker** [comment]
Thanks for the report! :)

@niksedk  
PR #7749 fixes this error (and some other bugs)

**Comment by niksedk** [comment]
Beta updated with latest changes by @Flitskikker : https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by ludem93** [comment]
oh wow you're fast! thank you1
