### ISSUE TITLE
Remember the switch in the list

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7743]
Could SE remember the switch here as well? I mean, those who use the 2nd option quite often have to switch it each time, so...
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/61d56398-9b1f-4287-8560-dc79b225e9c4)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
