### ISSUE TITLE
ASSA Tools shortcut issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7744]
It seems the ASSA tool(s) shortcut can also be triggered and work when working on other formats (e.g. SRT), which I think is not expected.

**Comment by niksedk** [comment]
Which one(s)?

**Comment by niksedk** [comment]
Still an issue?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Well solved, thanks!
