### ISSUE TITLE
interesting error

### ISSUE THREAD

**Issue by nielka98** [SubtitleEdit/subtitleedit#7748]
Hey, I think I found an interesting error and I'm wondering how to fix it. Maybe someone had this too. Well, no matter what subtitles it generates on Whisper in the second version, the beginning always sounds identical, it makes the beginning of only the same subtitles of this type: "Sottotitoli creati dalla comunità Amara.org." and then it generates normally. Does anyone know how to fix?

**Comment by niksedk** [comment]
It's a known issue... Whisper has seen these ads some many times, that it has learned to add them ;)
The same also happens for Danish.

Read more: https://github.com/openai/whisper/discussions/928
