### ISSUE TITLE
Fix common error discussion in Translation mode

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7752]
There's an old open topic here #5528
Not intend to start a duplicate issue report but to draw your attention because IMHO it's a big issue.

As we know, an internal rule in Translation mode is, after tweaking timecodes on either side, the timecode will be auto-synced to the other side (when "**Allow edit of original subtitle**" is enabled of course). However, there are four timecode error checkers don't quite follow this rule, which are:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/4b490495-cbda-4637-b2f9-c8de19d8740d)

This will cause big trouble if the same fix is not applied to the other side, because it will be really difficult or hardly possible to sync the two files again after quitting, not to mention having **merge original and translation** feature working properly aferwards because they are not synced anymore. 😂 

In a word, time-related error fixes should be applied to both translation and original when **Allow edit of original subtitle** is enabled.

**Comment by niksedk** [comment]
OK, how is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
THANK YOU!

**Comment by niksedk** [comment]
Yes, it should only affect the original is "Allow edit of original" is enabled.

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip
