### ISSUE TITLE
SE thinks WebVTT is .SRT Sub

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#7755]
I picked up some series with strange Subs, 'Ancient.Civilizations.2017', and 'Galactic.Messages'.

When I tried to extract the Subs with 'gMKVExtractGUI v2.4.2.0', I got this Error:

'Exception: Mkvextract exited with error code 2 'D_WEBVTT/SUBTITLES' is not supported'

I then opened the MKV with SE 4.0.2, and it managed to Extract the Sub, BUT...
On the Drop-Down List it says it's an .SRT file, whick it clearly is NOT!

1
00:00:00,000 --> 00:00:04,980
align:middle line:90%

2
00:00:04,980 --> 00:00:07,470
align:middle line:90%
[MUSIC PLAYING]

3
00:00:07,470 --> 00:00:08,964
align:middle line:90%

4
00:00:08,964 --> 00:00:11,454
align:middle line:90%
[THEME MUSIC]

5
00:00:11,454 --> 00:00:28,910
align:middle line:90%

6
00:00:28,910 --> 00:00:31,010
align:middle line:10%
>> Edfu, Egypt.

7
00:00:31,010 --> 00:00:34,730
align:middle line:84%
This ancient town is located
on the Western side of the Nile

8
00:00:34,730 --> 00:00:39,350
align:middle line:84%
River in upper Egypt,
60 miles South of Luxor.

9
00:00:39,350 --> 00:00:44,270
align:middle line:10%
In the mid-19th century, French
Egyptologist Auguste Marriette

10
00:00:44,270 --> 00:00:48,320
align:middle line:10%
is credited with uncovering the
mysterious ruins here, Temple

(This Sub is attached here)

[Ancient.Civilizations.2017.S04E02.Zep.Tepi.The.Lost.History.of.Egypt.1080p.GAIA.WEB-DL.AAC2.0.H.264-NTb.zip](https://github.com/SubtitleEdit/subtitleedit/files/13700291/Ancient.Civilizations.2017.S04E02.Zep.Tepi.The.Lost.History.of.Egypt.1080p.GAIA.WEB-DL.AAC2.0.H.264-NTb.zip)

When I change the Drop-Down List to show any of the two different 'WebVTT File', nothing changes, and it's not possible to Clean the Sub 'automatically' in any way.

SE must be doing something wrong when it extracts and think it's an .SRT Sub ?!

How to make these Subs into pure .SRT Subs?

**Comment by niksedk** [comment]
You can probably remove lines starting with "align"

Could you attach/email the mkv file?

**Comment by Minherre** [comment]
> You can probably remove lines starting with "align"
> 
> Could you attach/email the mkv file?

https://torrentgalaxy.to/torrents.php?search=Galactic+Messages#results
https://torrentgalaxy.to/torrents.php?search=Ancient+Civilizations+2017#results

Chose from the hits, I think all of them have the same kind of VTT-Subs.

**Comment by niksedk** [comment]
Could you possible remove the audio/video tracks and email the file?

**Comment by Minherre** [comment]
> Could you possibly remove the audio/video tracks and email the file or attach it here?

We're obviously writing 'OnTop' of each other; while I added two URLs, you had already answered this above here, so pick up from the URLs i my prev. msg.

How large can an attached file be here?

**Comment by niksedk** [comment]
You can attach zip files here... I think up to 25 MB.

**Comment by niksedk** [comment]
With MKV toolnix you can remove the audio+video streams... that should give a small file.

**Comment by Minherre** [comment]
> With MKV toolnix you can remove the audio+video streams... that should give a small file.

Sorry, but I can't understand why You just can't use the already attached Sub, or use any of the two URLs to pick-up any of the MKVs involved, to try to fix this SE-Problem?!
My PC is getting too old to use even more strange programs...  ;-)

**Comment by niksedk** [comment]
I do not download torrents...
