### ISSUE TITLE
Two more things that cause desync/"count does not match" in translator mode

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#7758]
Latest beta (but this has always been the case).
To follow up on https://github.com/SubtitleEdit/subtitleedit/issues/7752, when you're in translator mode, going into source view and changing a specific subtitle's time causes a desync. More thorough changes (adding whole chunks of subtitles and so on) give a "count does not match" error in the indicator box. Whereas it should just be adding subtitles with the same timecodes (but blank text) into the translation as well.
Another thing that causes a "count does not match" error is copying and pasting a subtitle in list view (that is, with ctrl+c/ctrl+v, not through column paste or anything).

**Comment by niksedk** [comment]
Copy paste should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

Source view is more difficult to fix. If many changes are made, it's impossible for SE to figure what to do!
