### ISSUE TITLE
Auto Translate not working in batch convert

### ISSUE THREAD

**Issue by Lunchbox209** [SubtitleEdit/subtitleedit#7759]
Auto translate using LibreTranslate for a single .srt file works perfectly and completes pretty quickly. However when running it in batch convert for a single or multiple .srt files, Subtitle Edit freezes and the batch convert can't be cancelled. 

This happens on 4.0.2 and the latest 4.0.2 Beta.

**Comment by niksedk** [comment]
Thx for the info :)

Hopefully no freeze and translate should be abort-able: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by Lunchbox209** [comment]
That's a quick fix, thank you! Seems to be working correctly now. 

Only small issue I'm seeing now is the filename doesn't change based on the language it is translated to. It does do this when not using batch convert. Not a big deal, but something you might want to know.

![batchtranslate](https://github.com/SubtitleEdit/subtitleedit/assets/154269131/fd252393-8942-42ff-9f22-d3b5051912e1)
![batchconvert-language](https://github.com/SubtitleEdit/subtitleedit/assets/154269131/551cc43e-ea84-4cb4-9231-dfb80a240dad)

**Comment by niksedk** [comment]
Thx for testing :)
Beta updated, so it now tries to use target language code in file name: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.2/SubtitleEditBeta.zip

**Comment by chirick86** [comment]
![image](https://github.com/user-attachments/assets/8ec12475-706d-437c-a47a-eab968130b59)
Seems not working at all. Tryed all 4 metods.
Should I install one of those first?
