### ISSUE TITLE
Allow to use OCR corrections on all files.

### ISSUE THREAD

**Issue by mlpo** [SubtitleEdit/subtitleedit#776]
Hi!

It would be great if it were possible to apply OCR corrections on all files, even without performing OCR. Indeed, currently the only way to correct OCR errors is to use "Import/OCR"; it would be nice to use the corrections directly (eg. on a .srt).

Thank you.

**Comment by niksedk** [comment]
To fix OCR errors in a srt file, try Tools -> Fix common errors: "Fix common OCR errors"... also you can use some of the other common fixes, and also Edit -> Multiple replace can help.

**Comment by mlpo** [comment]
Yes, indeed, I did not see this option. My bad. Thank you.

Issue solved ;).

**Comment by mlpo** [comment]
Yes, indeed, I did not see this option. My bad. Thank you.

Issue solved ;).
