### ISSUE TITLE
Jumping subtitle sync

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#7762]
At a certain point a feature was added when syncing 2 subtitles.
If you click on a line in either window, it will jump to a line around that time in the other window.

When the 2 subtitles are much out of sync it becomes tedious to work with.

If it's changed, so only clicking on a line **in the left window** will make a jump in the right window and not the other way around, I'm convinced it'll be much easier to work with.

**Comment by niksedk** [comment]
Where and what are you doing?
Read more here: https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by fraternl** [comment]
I have, for instance, a Dutch subtitle for a DVD version which I want to sync using an English subtitle for a Blu-ray.

It quickly becomes clear that they are not 1:1 and have different scenes.

When I select a line in the left window it jumps to the same time in the right window. That's no problem, really... I then have to find the corresponding line and when I select it in the right window, my selected text in the left is gone.

I know it is still selected and if I would be sure I chose the correct line I could just press sync...

To be sure I will have to find the line I selected in the left window....

It becomes tedious as it's not 1 line, but multiple lines.

If only the left window select leads to a jump in the right window, I'm sure it becomes better to work with.

**Comment by niksedk** [comment]
I cannot follow what you're doing... could you attach some screenshots?

**Comment by fraternl** [comment]
Too bad.
The issue doubles the work I have on subtitles that are somehow heavy out of sync due to missing scenes.
I'm glad I don't have many of those.

One subtitle is in sync, but in the "wrong" language. The other subtitle is in the correct language, but out of sync.

When doing a sync on those, one first needs to find out what frame rates they are and at least try to match the out-of-sync-one with that.

Then you try to match them with the 2-pane window.

If you select a line in the left pane, it will _"follow"_ it in the right pane.
For the first lines of the subtitle the matching line in the right pane will be close to the position it has jumped to.

You can check the surrounding lines to find the matching lines and both the left pane and the right pane show more or less the same scene.
You can then pair those 2 lines.

At that moment you still have the same scene in both panes.

But further on in the movie, when the subtitles are becoming more out of sync, this following doesn't come close to match the scene. 
You will not have matching scenes anymore in the 2 panes.

At that stage in the process of syncing you would prefer it stops trying to find a matching subtitle.

Before you select a line you want to sync, you will have the same scenes already more or less matched in both panes.
This because you matched them just before.

If you then scroll some minutes down in the left pane and some minutes in the right pane. You can see 2 lines you want to match.

**Now is the moment that _"the following"_ becomes counter productive and you would prefer it didn't have that feature anymore.**

If you then select the line you would like to sync in the left pane, the right pane jumps away from that scene.
You need to find that line **again**.
That's a shame because, just before, you had both matching lines in the 2 panes.
 
After you find the line in the right pane by scrolling down or up (you also need to remember if you are ahead) you can select the matching line.

If you are sure it is the one, you can select it and press sync.
You're doing this "blind" because the moment you select the line in the right pane, the left pane goes away from that scene because it will match the timestamp of the line in the right pane.

If you're unsure if the 2 lines are a match you need to scroll in the left pane.
The selected line is marked (light blue) and if the surrounding lines also match you can then safely press sync.

**Having a checkbox in the 2-pane window to turn the feature off would also work.**

The feature helps you when you are matching 2 already fairly synced subtitles.
It becomes a pita when they don't match.

I hope I'm explaining it better now.
