### ISSUE TITLE
Remove cross line text for hearing impaired.

### ISSUE THREAD

**Issue by Mishasama** [SubtitleEdit/subtitleedit#7763]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/54498172/a8cd77b5-da7e-4a91-9604-cba41245a857)
The subtitle files I download often have these broken tags across lines. I wonder if there's a way to improve the recognition of this feature.

**Comment by niksedk** [comment]
Sorry, I think this is too complex / not-common.

**Comment by Mishasama** [comment]
> too complex

What about like this?
```
if line X "After" = "[" or "]"
then check line X+1 or X-1 "After"
if X+1 or X-1 "After" = "hearing impaired]" or "[hearing impaired"
then delete line X and X+1 or X-1
```
Sorry I only know a little VB...😂
