### ISSUE TITLE
Capitalize all text within brackets and/or parenthesis

### ISSUE THREAD

**Issue by poeBaer** [SubtitleEdit/subtitleedit#7765]
An automated menu option to capitalize any and all text that's contained between brackets [] or parenthesis () at once would be appreciated

The majority of all SDH/HI English Blu-ray subtitles contain the information within them capitalized, eg [DOOR SLAMS] or (TIRES SCREECH), to make identification even easier. But there's always an exception to the rule, and some Blu-ray subtitles have them all lowercase, or with normal grammar capitalization

It would make cleaning up those problematic subtitles even quicker

**Comment by niksedk** [comment]
I think Ivandrofly has written a plugin for this - see File - Plugins:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/94265b73-6e98-48b9-b1e1-784a6cf8a718)
