### ISSUE TITLE
what means this color?

### ISSUE THREAD

**Issue by johnfelipe** [SubtitleEdit/subtitleedit#7767]
![SNAG-0132](https://github.com/SubtitleEdit/subtitleedit/assets/428820/52525ab3-a323-4c83-ad66-214d7e00c3b4)

tnks for you answer

**Comment by johnfelipe** [comment]
this is same but with english and text and duration is with that color, and change, is not same like in spanish:

![SNAG-0133](https://github.com/SubtitleEdit/subtitleedit/assets/428820/b5beb47d-b33c-4fe7-8d7e-2751daa15fab)

**Comment by Flitskikker** [comment]
Red duration = too high reading speed, too short duration, or too long duration  
Red text = too many characters per line
