### ISSUE TITLE
Single-letter Shortcut Conflict with Source View

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7768]
as the title says. To test it, just try some create/adjust shortcuts for example.

**Comment by niksedk** [comment]
I love examples and screenshots ;)

**Comment by LeonCheung** [comment]
Sure, for example, there's no way to type letter A in source view mode in this case:

https://github.com/SubtitleEdit/subtitleedit/assets/494788/7695d340-00e5-4a93-99d8-8a074ce9a90f
