### ISSUE TITLE
Whisper on drive D? 

### ISSUE THREAD

**Issue by nielka98** [SubtitleEdit/subtitleedit#7770]
How to safely transfer Whisper  models to the D drive and is it even possible? Because my C drive is dying and I have very little space

**Comment by niksedk** [comment]
Uninstall installer version, make sure C:\Users\<USER-NAME>\AppData\Roaming\Subtitle Edit is empty
Download portable version, unpack to drive D

If you're already using the portable version, just move the folder to your D drive.
