### ISSUE TITLE
Feature Request: Add "Single sentence only" mode for "Unbreak short line (pixel width)" in "Fix common errors..."

### ISSUE THREAD

**Issue by BlohoJo** [SubtitleEdit/subtitleedit#7774]
For "Unbreak subtitles that can fit on one line (pixel width)", also add "Unbreak subtitles that can fit on one line (pixel width) (single sentences only)".

Assuming two lines per subtitle, it should work like:

`This is a`
`sentence`
to
`This is a sentence.`

---

`BILL:`
`This is my line.`
to
`BILL: This is my line.`

---

`[SOFTLY]:`
`Hi.`
to
`[SOFTLY]: Hi.`
&nbsp;

**But it should leave alone:**

`Hi.`
`This is a sentence.`

The current option ""Unbreak subtitles that can fit on one line (pixel width)" will unbreak the above to:

`Hi. This is a sentence.`

**Comment by niksedk** [comment]
You can use these two options:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/9d84afd2-5f4f-441b-bd47-197ca919ce51)

**Comment by niksedk** [comment]
It sounds like you want "Remove line breaks in short text with only one sentence"

**Comment by BlohoJo** [comment]
"Remove line breaks in short texts with only one sentence" does not correct:

---

`BILL:`
`This is my line.`
to
`BILL: This is my line.`

---

`[SOFTLY]:`
`Hi.`
to
`[SOFTLY]: Hi.`
&nbsp;

"Remove line breaks in short texts (all except dialogs)" will actually correct the above, but, it will change (typically in a non SRT subtitle):

`Hello.
- Hello.`
to
`Hello. - Hello.`

There is a workaround, which is: after running "Remove line breaks in short texts (all except dialogs)", then run "Fix common errors" again, with "Remove line breaks in short texts (all except dialogs)" **deselected**, and "Fix dialogs on on line" **selected**, which will change:

`Hello. - Hello.`
back to
`Hello.`
`- Hello.`

I guess that's fine. "Single sentence only" mode for "Unbreak short line (pixel width)" in "Fix common errors..." would make this happen in one step. Unless maybe it should be changed instead of having a new item/mode added?

Happy Holidays by the way. :)
