### ISSUE TITLE
Failed to remove {\an8} tag

### ISSUE THREAD

**Issue by iqbalsyamsu** [SubtitleEdit/subtitleedit#7775]
I want to remove `{\an8}` or any position tag `{\anX}` but it can't be done by the 'Remove text for hearing impaired' tool, even though `'{' and '}'` is checked.

![SE_impairedTag](https://github.com/SubtitleEdit/subtitleedit/assets/3842150/60326c54-d08e-48e9-869b-11d6ec503b61)

**Comment by niksedk** [comment]
Hi @iqbalsyamsu,

`{\an8}` is tags for HI, but an alignment tag.

You can remove them in the list view. Right-click on selected lines, via `Remove formatting`, `Remove alignment`:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/6152e23a-f1f2-4129-bd0b-94a849e7b8de)

**Comment by iqbalsyamsu** [comment]
> Hi @iqbalsyamsu,
> 
> `{\an8}` is not a tag for HI, but an alignment tag.
> 
> You can remove them in the list view. Right-click on selected lines, via `Remove formatting`, `Remove alignment`:

Foolish of me, thank you!
