### ISSUE TITLE
SHA256 Checksum for file SE403FI.zip doesn't match

### ISSUE THREAD

**Issue by Perkolator** [SubtitleEdit/subtitleedit#7787]
Downloaded the file several times, checksum doesn't match. Tried to download the other 4.0.3 version files and their checksums match.

**Comment by Perkolator** [comment]
Seems to be working now. Don't know what happened..

**Comment by niksedk** [comment]
@Perkolator: thx for the info :)
I had a wrong hash on the release page - updated.

**Comment by Perkolator** [comment]
Ok. Thanks. I didn't take a note of the hash when initially testing, so now when I was checking it again, I couldn't remember what the hash was before and if it had changed (and github doesn't seem to show any "history", or date/timestamps of edited release texts).
