### ISSUE TITLE
Bug: Auto-translate (English to Chinese/Japanese) is still super slow on 4.0.2 and 4.0.3

### ISSUE THREAD

**Issue by ftfox** [SubtitleEdit/subtitleedit#7788]
## The API I use
Google Translate V1 API

## Translation speed in version 4.0.1
Translates over a hundred lines in four seconds
![4 0 1-result](https://github.com/SubtitleEdit/subtitleedit/assets/56379264/affcfa76-8d0b-47c9-9d3f-46f6c1169a28)

## Translation speed in version 4.0.3 (4.0.2)
Only 2 lines can be translated per second
![4 0 3-result](https://github.com/SubtitleEdit/subtitleedit/assets/56379264/60afa0ea-6d4c-47f3-8bb5-ece1386b7be7)

**Comment by niksedk** [comment]
Hm, about 96 lines here for English to Chinese...
