### ISSUE TITLE
The Spacified executable is not a valid application for this OS platform.

### ISSUE THREAD

**Issue by Sato69** [SubtitleEdit/subtitleedit#7790]
Hello, I am facing this problem with my computer. I know that this problem is most likely because my computer is very old. (32bit, made in 2009, Wid7 operating system)

I can't exchange it (not because of money) but it's something my mother bought for us (me and my brothers) and It is considered a souvenir that has sentimental value to us

I've been using it for a while and it even has dead pixels but I haven't had a chance to fix the screen. I hope you can fix this problem because I don't really want to change my computer.
![PSFix_20231225_144652](https://github.com/SubtitleEdit/subtitleedit/assets/101804302/5a9de2b9-703e-46e6-93c0-c23e7ad436d0)

**Comment by niksedk** [comment]
It's possible you need another ffmpeg version - you can try some from here: https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/releases

**Comment by Sato69** [comment]
Ok, I'll try to find another ffmpeg version works on my computer, Thank you.

**Comment by Sato69** [comment]
Thank you, I found the version who work with my computer.
