### ISSUE TITLE
PGS subtitle question about frame rate

### ISSUE THREAD

**Issue by nautilus7** [SubtitleEdit/subtitleedit#7792]
Hi, I have some pgs subtitle files that come from a movie (mkv) which is 23,976 fps. These subs are recognized by subtitleedit as 25 fps. 

My question is, does the pgs file format has a specific field that determines its fps? I was under the impression there wasn't such field, but if it exists, then either my subs have the wrong value, or subtitleedit somehow gets it wrong.

If my subs are wrong and subtitleedit indeed displays the correct value, then how can I change this value? I don't want to change the start or end time of the subtitles, I just want to change that field that declares the fps.

See file attached.

[gre.zip](https://github.com/SubtitleEdit/subtitleedit/files/13771706/gre.zip)

![Screenshot 2023-12-26 151008](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/6731988a-65d8-4969-8f48-71a892c6cdbe)

**Comment by niksedk** [comment]
I'm not too sure about this, but I do not think SUP uses frame rate for anything at all.

There is a `Frame rate` field, but I not looked at how this field is used.. Read more here:
https://blog.thescorpius.com/index.php/2017/07/15/presentation-graphic-stream-sup-files-bluray-subtitle-format/

**Comment by cubicibo** [comment]
All PCS in a PG stream must report the same framerate value and it should ideally match the framerate of the muxed video to comply with Blu-ray requirements.

The possible values are quite straightforward:
| value | FPS |
| ------------- | ------------- |
| 0x10 | 23.98 |
| 0x20 | 24 |
| 0x30 | 25  |
| 0x40 | 29.97 |
| 0x60 | 50 |
| 0x70 | 59.94 |

**Comment by nautilus7** [comment]
Hi, any update on this issue? Thanks.
