### ISSUE TITLE
A slight addition. To make a new button OPEN VIDEO, just after OPEN (subtitles) button in toolbar

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#7793]
When you open the new title and video, you go to the icon NEW in the toolbar to load subtitles. Then you go to the menu, Video/ open video file and you choose the video file. 

It would be a bit more comfortable if after the NEW button in the toolbar would be another one, the OPEN VIDEO button, you don't need to go in the menu bar at all, you stay in the toolbar and you open the whole thing just being in the toolbar. 

![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/eadeac20-831b-41cb-b180-45c435ab991c)

It is just an innocent suggestion, I think it would make this program more useful, if we had some other buttons, like burned subtitles and the others, which also could be found in the menu, I don't see any obstacle that the very frequent option video/ open video file shouldn't be in the toolbar, because there is enough space for it. 

You know, even the button SAVE can be considered as redundant because it can be found in the menu and to be ctrl + S, but it is more than great, because we need to save our work, and it is more than useful.

**Comment by Cyberyoda1411** [comment]
This button is more important than SAVE AS which is already part of the program. Save as is not as used as an opening video file.

**Comment by skockobagi** [comment]
I agree. The same as Save as can be reached through the menu, and it has its own icon in the toolbar, I think that "open video file" would be very helpful because it is used every time when we use SE.  To be more precise, we don't need to use Save as, but we must use open video/open video file.

**Comment by Cyberyoda1411** [comment]
Nikolaj, as soon as you finish your job, and not be too busy, please, give me a direct reply, if it will be applied or not. I watch every time about my suggested change if you made it. It would be very nice to have one button for the subtitles (we already have it), and the other button (on the toolbar) for open video.

**Comment by niksedk** [comment]
Beta updated with "Open video" toolbar item: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by skockobagi** [comment]
THANK YOU SO MUCH. REALLY. During this pause, I got very attached to this
idea. THANK YOU for making it true.

**Comment by Cyberyoda1411** [comment]
The last comment was from my mail. Thank you, Nikolaj.

**Comment by niksedk** [comment]
Thx to jmaraujouy for the new icons:
https://github.com/SubtitleEdit/subtitleedit/discussions/6921#discussioncomment-8898859
