### ISSUE TITLE
When is needs update whisper model or version

### ISSUE THREAD

**Issue by johnfelipe** [SubtitleEdit/subtitleedit#7796]
I download a lot of gb for whisper cpp and faster
How is need review of necessary redownload or review if update new version...

**Comment by niksedk** [comment]
Please provide more information.
Do read this: https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by johnfelipe** [comment]
I think it may be a question, when to check if the downloaded model was updated or if there is a new version of the model, for example model v3, they may update it to model v3.2

**Comment by johnfelipe** [comment]
Subtitle Edit 4.0.3, improve function about faster whisper but not models, right?

**Comment by Purfview** [comment]
> Subtitle Edit 4.0.3, improve function about faster whisper but not models, right?

It updated to new Faster-Whisper version.

**Comment by johnfelipe** [comment]
1. can u tell me if this is a good example of use GPU with faster for video of 26 min, transcribe and translate to english in 8:25 min?
here video:

https://drive.google.com/file/d/1BuglPhVT5S1fd5UmjTEOMnBC5g6gfSH9/view?usp=sharing

2. we have may be a calculator for have in RTX 3060 TI of 8 gb how many min need SE for transcribe one video with X min using large-v3?

3. is possible improve use of GPU for reduce 8:25 min?

tnks

**Comment by Purfview** [comment]
SE's ETA stat is not accurate, if you want to see actual stats then you need to run Faster-Whisper directly in console.

> is possible improve use of GPU 

Possible, set:
CUDA Sysmem Fallback: OFF
Hardware-accelerated GPU scheduling: ON

**Comment by niksedk** [comment]
Models are not updated... sometimes a new model will appear (like V3).
