### ISSUE TITLE
Why did you remove the line merging option in the auto-translate section?

### ISSUE THREAD

**Issue by corvtte** [SubtitleEdit/subtitleedit#7797]
i need this option for no merging
Is this option moved to another part that I don't know?
Not available for me from version 4.0.1 onwards

**Comment by niksedk** [comment]
You can try Tools - Merge short lines.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/469bc044-2f52-4700-b679-753b0217d8a7)

This was remove from the auto-translate menu, at it's not built-in in the auto-translate, so it's not needed for translation anymore.

**Comment by corvtte** [comment]
I need no merge on the lines, but when translating the lines are automatically merge, is this option a good solution and can be used to prevent merge lines?

**Comment by niksedk** [comment]
I'm not really sure what you mean...

In the  auto-translate, you can force translating one-line-at-a-time, by right-clicking and click on this option:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/099c97fb-c8fa-4292-8ebc-b27eac5b8c31)

**Comment by corvtte** [comment]
I mean :

![image](https://github.com/SubtitleEdit/subtitleedit/assets/155023632/bbd43b21-c76f-4807-953a-60b11454e987) 
In the first picture after the translation in line 25, no additional words have been added from other lines (translated by version 4.0.1)

But in the second picture :
![image](https://github.com/SubtitleEdit/subtitleedit/assets/155023632/0bb0047c-4323-42fb-ac47-d0ef6a41eddd)
After the translation of line 25, there are more words that are related to other lines
(translated by version 4.0.3)

I need the lines not to merge after translating the text.
  This feature was available in version 4.0.1 and earlier by activating the no merging option, but it is not possible in newer versions, or I don't know how to do it.

**Comment by niksedk** [comment]
Again... check this option:

![293844014-099c97fb-c8fa-4292-8ebc-b27eac5b8c31](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/b4e6438f-e74b-465c-b4cf-1fc922914686)

**Comment by corvtte** [comment]
Thank you, my previous problem is solved
But I ran into a new problem while translating
![image](https://github.com/SubtitleEdit/subtitleedit/assets/155023632/facaed8d-89a3-42cc-abda-341a6c54c39c)
Sometimes some lines are not translated and I have to close the translation page and try again 

And another issue is that for single-line translation, you need to check the box every time after reopening the program, and the settings are not saved.
I wish, like the previous version, the single-line translation option was clear on the translation page and did not require right-clicking, or at least the settings were saved after applying.

Thank you for your help and response
