### ISSUE TITLE
In SE 4.* the shortcuts "extend selected lines to previous/next shot change" don't work anymore past the first encountered shot change

### ISSUE THREAD

**Issue by paolo-gajo** [SubtitleEdit/subtitleedit#7799]
in SE 4.*, when using the shortcuts "extend selected lines to previous/next shot change", the selected subtitle's in/out cue can be pushed to the first shot change before/after it, but pressing the shortcut again does nothing. This is unlike SE <= 3.6.13, where pressing it again would move it to the previous/next shot change until another subtitle is encountered.

Is this intended new behavior? Would it be possible to have the old behavior back, even in form of a toggle? Thank you!

**Comment by matmaggi** [comment]
I'd love the way it was before too!
