### ISSUE TITLE
[Problem] It's a 2hrs Korean Film but Why is 'Audio to Text (Whisper AI, Korean)' Generating subs for the first 6min only? 

### ISSUE THREAD

**Issue by advthankyou** [SubtitleEdit/subtitleedit#7800]
Why isn't the whole audio subbed? New User ... should I change any settings?

**Comment by niksedk** [comment]
It's mostly likely due to out of memory... try using a smaller model.

For more info, you can check the file `whisper_log.txt` in the SE data folder (press Ctrl+Alt+Shift+D in the SE main window to open this folder).

**Comment by advthankyou** [comment]
smaller model seems to work, thanks!
