### ISSUE TITLE
How to implement the functions of seeking help, merging, and splitting time

### ISSUE THREAD

**Issue by 17745615050** [SubtitleEdit/subtitleedit#7802]
I want to implement two functions, but I don't know where to set them in the software. Please help me!
The first function: The English generated by Whisper always uses (,) and (.) signs to separate sentences, such as these two sentences,
four
00:00:13347-->00:00:17114
But we're going to be able to use this
Idea, these concepts, to better
five
00:00:17114-->00:00:19570
Understand what it is we've been doing in
ML
I hope to combine the sentences into one sentence, for example, all sentences before (.) are combined into one sentence. Simultaneously merge time! Just like this
four
00:00:13347-->00:00:19570
But we're going to be able to use this idea, these concepts, to better understand what it is we've been doing in ML
May I ask how the experts can operate to achieve this function.
The second function is sentence segmentation: how to divide two sentences with (.) signs into two sentences in a long sentence. For example, this sentence:
two
00:00:14565-->00:00:30400
Let's dig in! You can think of programming in blueprint a little bit like wiring up an electrical circuit You have your different components and you can wire them up so that when a light switch is switched on then the light will switch on
I want to split it into two sentences that are perfectly timed. For example
two
00:00:14565-->00:00:22135
Let's dig in! You can think of programming in blueprint a little bit like wiring up an electrical circuit
three
00:00:22135-->00:00:30400
You have your different components and you can wire them up so that when a light switch is switched on then the light will switch on
I found that when a sentence is split by Whisper, there is a situation where one word is separated from the next sentence. There may be obvious errors when translating into other languages. I am currently using PGT translation. But sometimes the translation is not very clear. So I can only manually adjust each sentence to a (.) sign and the result will be clear after translation using translation software. The only drawback is that I can't keep up with the time card. Can anyone help me solve these two problems. What methods should be used in the software to modify these two functions. Thank you very much!

**Comment by Purfview** [comment]
Can you reformat your post to the readable form for humans?

Looks like it's something about the sentences... Try `--sentence` with Faster-Whisper.

**Comment by 17745615050** [comment]
I want to implement two functions, but I don't know where to set them in the software. Please help me!
The first function: The English generated by Whisper always uses (,) and (.) signs to separate sentences, such as these two sentences,

4
00:00:13347-->00:00:17114
But we're going to be able to use this
Idea, these concepts, to better

5
00:00:17114-->00:00:19570
Understand what it is we've been doing in
ML.

I hope to combine the sentences into one sentence, for example, all sentences before (.) are combined into one sentence. Simultaneously merge time! Just like this.

4
00:00:13347-->00:00:19570
But we're going to be able to use this idea, these concepts, to better understand what it is we've been doing in ML.

May I ask how the experts can operate to achieve this function.


The second function is sentence segmentation: how to divide two sentences with (.) signs into two sentences in a long sentence. For example, this sentence:

2
00:00:14565-->00:00:30400
Let's dig in! You can think of programming in blueprint a little bit like wiring up an electrical circuit You have your different components and you can wire them up so that when a light switch is switched on then the light will switch on.

I want to split it into two sentences that are perfectly timed. For example:

2
00:00:14565-->00:00:22135
Let's dig in! You can think of programming in blueprint a little bit like wiring up an electrical circuit

3
00:00:22135-->00:00:30400
You have your different components and you can wire them up so that when a light switch is switched on then the light will switch on.


I found that when a sentence is split by Whisper, there is a situation where one word is separated from the next sentence. There may be obvious errors when translating into other languages. I am currently using PGT translation. But sometimes the translation is not very clear. So I can only manually adjust each sentence to a (.) sign and the result will be clear after translation using translation software. The only drawback is that I can't keep up with the time card. Can anyone help me solve these two problems. What methods should be used in the software to modify these two functions. Thank you very much!

**Comment by Purfview** [comment]
For your 1st idea -> Use `--sentence` with Faster-Whisper.

For your 2nd idea -> Use `--sentence` with Faster-Whisper.
