### ISSUE TITLE
Can't Glean File Name From MKS File

### ISSUE THREAD

**Issue by RedSoxFan04** [SubtitleEdit/subtitleedit#7804]
Well, at least not when it comes time to save your finished SRT file. It can grab the name and remember it while you're in the OCR window, but then it seems to discard that name from memory.

**Comment by niksedk** [comment]
Thx for reporting this issue :)

Hopefully fixed in latest beta now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip 
( portable version, unpack to something like C:\Tools\SE )

**Comment by RedSoxFan04** [comment]
> Thx for reporting this issue :)
> 
> Hopefully fixed in latest beta now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip ( portable version, unpack to something like C:\Tools\SE )

Yes! It works! Thank you!
