### ISSUE TITLE
"Replace" pop-up window won't open on first try

### ISSUE THREAD

**Issue by dmaccountsetup** [SubtitleEdit/subtitleedit#7814]
I'm using the latest version 4.0.3 
Edit->Replace pop-up window won't open with "Source View" of ASS format under first trial. (it worked on previous version) 
Here are the steps I've taken...
1. Open any ASS subtitle file by double clicking
2. Click "Toggle List/ Source View" **</>** button on the toolbar (I made it visible under Settings-> Toolbar)
3. Click "Replace" or Edit->Replace or Ctrl+H ...usually the Replace pop-up window comes on but nothing pops up. (When I go back to the "regular" view, click "Replace", close the pop-up and toggle back again, it works.)

What I am trying to do was to add `\blur5\` in front every line. The only way I know how is to switch to source view, find "`Default,,0,0,0,,`" and replace with "`Default,,0,0,0,,\blur5\`"
Thank you!

**Comment by niksedk** [comment]
Hm, it works just fine here.
What OS are you using?

**Comment by dmaccountsetup** [comment]
> Hm, it works just fine here. What OS are you using?

Win 10 Home Ed (64-bit)

**Comment by niksedk** [comment]
Could the window have popped up on another monitor or something?
