### ISSUE TITLE
can your program be used for batch processing via bat?

### ISSUE THREAD

**Issue by AdventurerRussia** [SubtitleEdit/subtitleedit#7815]
I need the subtitles to be shifted forward by 1 second, are there any examples of working scripts for this? 
I know about batch mode in the gui, but I would like to have a bat script for this.
does the program allow this?

**Comment by niksedk** [comment]
You can use SE via cmd line.

Something like: `SubtitleEdit /convert  a.ass subrip  /offset:00:00:1:000`

**Comment by AdventurerRussia** [comment]
> You can use SE via cmd line.
> 
> Something like: `SubtitleEdit /convert a.ass subrip /offset:00:00:1:000` (add one second)
> 
> Something like: `SubtitleEdit /convert a.ass subrip /offset:-00:00:1:000` (subtract one second)

`"C:\Program Files\Subtitle Edit\SubtitleEdit.exe" /convert  "E:\Раздачи\Ijiranaide, Nagatoro-san 2nd\eng sub\01.ass" subrip  /offset:00:00:1:000`

Is that so? I don't understand what should be with the paths, can you please give an example, or give a link to some documentation for the command line?

**Comment by GrampaWildWilly** [comment]
subtitleedit /?

WW
GO HABS GO!

**Comment by AdventurerRussia** [comment]
I've already figured it out without a program, I asked the bot to write a python script

`import os
import re
import shutil
import time

# Получаем путь к папке скрипта
folder_path = os.path.dirname(os.path.abspath(__file__))

# Просим пользователя ввести значение сдвига времени
time_shift = int(input("Введите насколько сдвинуть субтитры (в миллисекундах): "))

# Создаем папку "Completed", если она не существует
completed_folder = os.path.join(folder_path, "Completed")
os.makedirs(completed_folder, exist_ok=True)

# Получаем все файлы ASS в папке скрипта
ass_files = [file for file in os.listdir(folder_path) if file.endswith(".ass")]

# Обрабатываем каждый файл ASS
for ass_file in ass_files:
    # Читаем оригинальный файл
    original_file = os.path.join(folder_path, ass_file)
    with open(original_file, "r", encoding="utf-8-sig") as file:
        lines = file.readlines()

    # Модифицируем временные коды
    for i in range(len(lines)):
        # Находим строки с временными кодами
        if re.match(r"Dialogue:|Comment:", lines[i]):
            # Разделяем строку на компоненты
            components = lines[i].split(",")
            start_time = components[1]
            end_time = components[2]

            # Сдвигаем временные коды на указанное значение
            start_time_parts = start_time.split(":")
            start_time_parts[-1] = str(float(start_time_parts[-1]) + time_shift / 1000)
            start_time = ":".join(start_time_parts)

            end_time_parts = end_time.split(":")
            end_time_parts[-1] = str(float(end_time_parts[-1]) + time_shift / 1000)
            end_time = ":".join(end_time_parts)

            # Обновляем строку с модифицированными временными кодами
            components[1] = start_time
            components[2] = end_time
            lines[i] = ",".join(components)

    # Сохраняем модифицированный файл в папке "Completed"
    completed_file = os.path.join(completed_folder, ass_file)
    with open(completed_file, "w", encoding="utf-8-sig") as file:
        file.writelines(lines)

    print(f"{ass_file}")

print("Обработка субтитров завершена!")
time.sleep(10)`

**Comment by AdventurerRussia** [comment]
I wrote a python script through the bot that makes the shift. 
the program was not even needed for this.

**Comment by AdventurerRussia** [comment]
[СДВИГ СУБТИТРОВ v2.zip](https://github.com/SubtitleEdit/subtitleedit/files/13854840/v2.zip)
