### ISSUE TITLE
Error when entering wrong character in "remove text between" (in Remove text for HI)

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#7818]
In Remove text for HI, I was trying to set the custom characters < and >, and accidentally entered a period or a question mark or something. Then I got this error:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/3de44490-e34f-4047-aaa7-b7d60bd08214)

**Comment by niksedk** [comment]
Thx for the info darnn :)

Hopefully now fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip
