### ISSUE TITLE
[Feature] Fixed encoding when opening a file instead of automatically recognizing the encoding

### ISSUE THREAD

**Issue by wifi-left** [SubtitleEdit/subtitleedit#7820]
Fixed encoding when opening a file instead of automatically recognizing the encoding.

Currently the default for opening a file (drag in a file) is to automatically recognize the code. However, encoding recognition is often inaccurate (for example, `GBK` encoded files are identified as `1252 Windows`).

I know that the menu can select the encoding to open the file, but this is a bit cumbersome. And the encoding is automatically detected by default every time you drag and drop a file.

I want to be able to open the file with the "encoding" selected from the home page. 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/63381531/6d614641-57c8-48d2-80ee-19b2f97421e0)

Or add a new selection box to select the encoding for opening the file.

Here are the files that have problems with coding recognition:
[Petit Rabbit's - なんとなくミライ.zip](https://github.com/SubtitleEdit/subtitleedit/files/13852121/Petit.Rabbit.s.-.zip)

The correct encoding format is GBK (or GB2312, GB18030).

Wrong coding:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/63381531/729e057f-003f-4322-9410-a20b4c08fea8)

Correct coding:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/63381531/5bbc8aa5-1086-4dd4-bdf5-666e91c90522)

Note: The lyrics are in Chinese and Japanese.

**Comment by niksedk** [comment]
You can also try File - Import - File with manually chosen encoding...
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/33e3bb84-bb2e-4180-9c9e-6264f6ce3dd6)

The ANSI auto detect should be a bit better in this beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

Also, do you use UTF-8 (or UTF-32) encoding... ANSI is outdated!

**Comment by wifi-left** [comment]
It in `4.0.3/SubtitleEditBeta.zip` version works!
Surprisingly, however, it does not work in the version installed with `4.0.3/SubtitleEdit_setup.exe`.
😂
