### ISSUE TITLE
Feature Request: changing selected line background color

### ISSUE THREAD

**Issue by Hakunamatata67** [SubtitleEdit/subtitleedit#7822]
Hi,

I use the dark theme as it's less tiring for my eyes.
But sometimes, I'm having a hard time to find which is the selected line as the background color is dark blue.

![Capture d'écran 2024-01-07 174241](https://github.com/SubtitleEdit/subtitleedit/assets/66781048/cb7f8d1f-22b3-4180-b60b-e0744c4352fa)

Could it be possible to chose a different color ourselves in a next release, maybe?

Thanks and have a nice day

**Comment by niksedk** [comment]
You might be able to find a setting called `DarkThemeSelectedBackgroundColor` in the file Settings.xml

**Comment by Hakunamatata67** [comment]
Thank you. I actually find it under <DarkThemeBackColor>#18344bff</DarkThemeBackColor>
But when I open SE, the color doesn't change. And when I close SE, Settings.xml reset the color to the old one.
