### ISSUE TITLE
machine translation tips

### ISSUE THREAD

**Issue by manu69x** [SubtitleEdit/subtitleedit#7830]
After many hours of trying with Whisper, I can suggest preset the only configuration that works in a simple and optimized way, which is the CPP version with the ggml-large-v3-q5_0.bin template that must be added.
Furthermore, it would be very important to add a preset automatic configuration for the number of treads to use.
For example, as the AUTO ADJUST TIMER option is now pre-set, an AUTO DETECT CPU TREAD option should be added which automatically sets the correct treads (in my case -t 24), for those approaching automatic translation with Whisper it would be very important because the default is only for 4 threads and therefore with modern CPUs there can be a huge difference in performance.
Furthermore, the LARGE models which are the most accurate do not work unless you set the mc (maximum number of text context tokens to store) parameter to the value 5 as default (default is -1 and does not work)
With these settings I get Whisper CPP working and with an acceptable speed, and I was able to convert the HAPPINESS TV series which I could only find in Korean.

Thanks for your hard work

**Comment by niksedk** [comment]
The large models work without any extra settings on my machine.

Also, latest SE beta has Whisper CPP V1.5.4: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

Good tip setting the `-t <number-of-threads>` parameter. 
Four threads are probably fine on my computer... how many cores do you have?

**Comment by manu69x** [comment]
Hello dear :)

I have 24 tread.
Only after many attempts did I realize that there was the possibility of
speeding up operations significantly.

Yes i'm using 4.03 beta

Whitout the parameter - mc 5 i have
just a few words repeated hundreds of times, I read about this trick online
and it actually worked.

Also the quantized vertion q5 of large model v3 work and is a very good
compromise.

I have renamed manualy the file model and work good.

Thanks for your answer.

Il gio 11 gen 2024, 19:40 Nikolaj Olsson ***@***.***> ha
scritto:
