### ISSUE TITLE
Remove All Formatting function clears Music Notes (♪♪♪)

### ISSUE THREAD

**Issue by postlab-io** [SubtitleEdit/subtitleedit#7837]
Using Subtitle Edit 4.0.3 on Windows Version 10.0.19045 Build 19045

When I use the 'Remove Formatting > All' on closed captions, the function erases the `♪♪♪` characters, leaving behind `()`

[See video recording here.](https://www.loom.com/share/652d6c4581f04df48b37a29678737164?sid=4a56216c-4634-4596-9192-d87c317c9530)

**Comment by postlab-io** [comment]
> Hm, is `(♪♪♪)` formatting? It probably is...
> 
> Did you expect an empty line or `(♪♪♪)` being left alone?

Expecting the `(♪♪♪)` line to be left alone :)

**Comment by niksedk** [comment]
OK, how is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

Note that `♪ Welcome ♪` will still be changed to `♪ Welcome ♪`... so... sometimes music symbols are considered formatting and sometimes not.
