### ISSUE TITLE
default style in Advanced Sub Station Alpha (.ass) conversion when no video is loaded

### ISSUE THREAD

**Issue by mpr0st** [SubtitleEdit/subtitleedit#7839]
Hi.

In the _Advanced Sub Station Alpha styles_ dialog I have defined, in _Style storage_, my own category (MyCategory) with one style (MyStyle):

![image](https://github.com/SubtitleEdit/subtitleedit/assets/49242687/ef70ce97-6512-4a41-a5d2-4e11a28330f2)

and I have set MyCategory as default (in the _Assa Categories Manager_):

![image](https://github.com/SubtitleEdit/subtitleedit/assets/49242687/063f0f95-6523-4d44-91ba-854d20a54ff3)

If I:

1. open a .srt and
2. choose Advanced Sub Station Alpha (.ass) from the dropdown

the style is correctly applied to every line in the GUI:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/49242687/f9fe3364-6665-4d86-80d3-bcbef9a458bd)

But when I press save, MyStyle is correctly saved as a style in the resulting .ass (in [V4+ Styles]), **but every line has Default style applied**, instead of MyStyle:

```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: MyStyle,Calibri,67.0,&H0000FFFF,&H0000FFFF,&H00000000,&H7F000000,-1,0,0,0,100,100,0,0,1,2.0,3.0,2,20,20,75,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:07.28,0:00:08.64,Default,,0,0,0,,Us two...
```

But, if I:

1. open the same .srt
2. choose Advanced Sub Station Alpha (.ass) from the dropdown and
3. open a random video file

when I press save, the style is correctly applied to every line:

```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: MyStyle,Calibri,67.0,&H0000FFFF,&H0000FFFF,&H00000000,&H7F000000,-1,0,0,0,100,100,0,0,1,2.0,3.0,2,20,20,75,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:07.28,0:00:08.64,MyStyle,,0,0,0,,Us two...
```

The same behavior can be observed when converting from the command line (that's how I noticed the issue in the first place) with `/convert subtitle.srt AdvancedSubStationAlpha`, the style is present in [V4+ Styles] but it's not applied to every line.

Thank you.

**Comment by niksedk** [comment]
Hi @mpr0st,

Thanks for reporting this :)
Should now hopefully be fixed in latest beta version (portable): https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

**Comment by mpr0st** [comment]
Wow, thank you for the quick response.

It's fixed in the GUI, but converting from command line still assigns Default style to the lines (it's, in fact, generating the same file as before the fix).

**Comment by niksedk** [comment]
Thx for testing and reporting back :)

Hopefully finally fixed in the new beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

**Comment by mpr0st** [comment]
Works perfectly now.

Thanks!!!!
