### ISSUE TITLE
Error: https://www.youtube.com/shorts/DZ94dfgZaf4

### ISSUE THREAD

**Issue by mariagregory** [SubtitleEdit/subtitleedit#7848]
I'm trying to generate subtitles from a video
using **Video/audio to text**
Version **3.6.6**

![subtitleEdit_Error](https://github.com/SubtitleEdit/subtitleedit/assets/35348733/82ad8f76-9193-4252-9c79-61301c342f0b)

Tried installing a newer SE version (4.0.X), but newer versions don't even seem to offer text generation :(

**Comment by niksedk** [comment]
Sorry, SE cannot extract the audio from online videos.
