### ISSUE TITLE
Request to bring back No Merging option in auto-translation

### ISSUE THREAD

**Issue by laisuk** [SubtitleEdit/subtitleedit#7851]
I would like to request bringing back the old No Merging option in auto-translation. 
With current auto-translation from English to East Asian language, the translation becomes unusable and run out of time-stamp.
For version 4.0.3 I still manage to get that option with: select all line -> translate selected line -> auto translate. So I follow this way currently. 
When I check the beta version I noticed that No Merging Option in translated selected line is removed as well, I have a felling that this option will gone forever in future version. So please bring back that option, that is really a big help in my subtitle editing.
Thanks in advanced.

![sshot-2024-01-19- 17-43-14](https://github.com/SubtitleEdit/subtitleedit/assets/98227764/5991607c-bef6-4bd3-83ad-3b239e71023e)

**Comment by niksedk** [comment]
Could you explain the problem a bit more?

You can right-click in the translation window, and enable "translate single lines":

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/46e63d59-8463-4601-840d-e8ebe30561c2)

**Comment by laisuk** [comment]
> Could you explain the problem a bit more?
> 
> You can right-click in the translation window, and enable "translate single lines":
> 
> ![image](https://private-user-images.githubusercontent.com/1261331/298303477-46e63d59-8463-4601-840d-e8ebe30561c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTYyMzMsIm5iZiI6MTcwNTgxNTkzMywicGF0aCI6Ii8xMjYxMzMxLzI5ODMwMzQ3Ny00NmU2M2Q1OS04NDYzLTQ2MDEtODQwZC1lOGViZTMwNTYxYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMDU0NTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDAyODZiZWZjYmIwMmJlOWY1OTZhMmQ0MGI0MWNhZGI2MzNkZWNiYWUxZWVlMjUwYTIyYTVhMjJmM2U4NDVmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rvak0dKtUh8WF2_BU6skhI766W5MxCSZA6nOKt5JIk4)
Wow thanks a lot! I've never realized there is a hidden right-click option for that. Really big help and appreciate your guide.

As the said previous line merging problem is something like (Just example, might not happen in some cases):
Line 1: I have an apple
Line 2: Apple is rotten
Sample line merged translation: I have a rotten apple
Results:
Line1: 我有一粒蘋果
Line2: 蘋果已腐爛
Sample line-merged translation: 我有一粒腐爛了的蘋果 <- Not what I want

P/S: I just noticed the right-click "Translate single line" option have to be triggered each time we enter Auto-Translate. Is there any permanent/remember setting for that? (It's alright if there isn't any, current state is er satisfactory for my subtitle editing routine )

Thank you so much.
