### ISSUE TITLE
Beautifier

### ISSUE THREAD

**Issue by JDTR75** [SubtitleEdit/subtitleedit#7853]
Hi! If there a way of creating and saving your own presets? I'm asking because I noticed the shortcuts (shot changes related) work with the beautifier presets, and they're fine for 24 fps videos. But if you load a 30 fps video, for instance, the shortcuts aren't doing the right thing because they're fixed with the other presets. I have to manually edit the beautifier specs in order for the shortcuts to work properly.

**Comment by Fhining** [comment]
Hello! @niksedk! So this won't be added?

I really think it's necessary. Having only Netflix and SDI setups available to load limit us to save our own setups for different specifications.

Do you think it's possible to rethink this option?

Thank you so much! :)
