### ISSUE TITLE
TTS using elevenlabsTTS for dubbing feature

### ISSUE THREAD

**Issue by johnfelipe** [SubtitleEdit/subtitleedit#7855]
https://drive.google.com/file/d/1u9_0IH3HHbmn9YiuXEaA92ZIOYAjYsw4/view?usp=sharing

There is an example using https://github.com/jianchang512/pyvideotrans

pls tell me if is interesting for add in roadmap?

**Comment by johnfelipe** [comment]
any progress with dubbed using elevenlabsTTS
spanish - english
english - englishdubbed
etc?¡

**Comment by niksedk** [comment]
Included in latest beta

**Comment by johnfelipe** [comment]
How can install latest beta for test?

**Comment by niksedk** [comment]
You can get it here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by johnfelipe** [comment]
where is submenu for dubbing?
