### ISSUE TITLE
Waveform cuts off about 12 and a half hours into file.

### ISSUE THREAD

**Issue by SoundTheHorn** [SubtitleEdit/subtitleedit#7856]
While the app has no issue playing audio, displaying video, or inserting subtitles past that point, the waveform view cuts off at 12:25:39.240 and doesn't scroll any farther.

It's a niche issue that doesn't affect overall usage, but it's an issue nonetheless.

**Comment by SoundTheHorn** [comment]
Update on this. As of the release of 4.0.4, the maximum time the waveform will display has shortened to 07:06:03.219

**Comment by niksedk** [comment]
Hm, I've looked a bit at this.

VLC cuts the wave file after 7 hours and 15 minutes.
ffmpeg cuts the wave file after 12½ hours.

It's possible ffmpeg can extract the full audio with some special parameters...
