### ISSUE TITLE
ASS Tags does not work when exporting SUP

### ISSUE THREAD

**Issue by dadlklk** [SubtitleEdit/subtitleedit#7857]
The font style should look like this when previewing:
![1](https://github.com/SubtitleEdit/subtitleedit/assets/59605688/8b6f736b-bc96-46df-b5b4-b81199e00d81)

But when exporting SUP, it's like this
![2](https://github.com/SubtitleEdit/subtitleedit/assets/59605688/1282012f-f24c-4a3e-b0e2-3a0486369da8)

Why does the ASS tag not work at this time?

**Comment by LeonCheung** [comment]
Because tags are not compatible between formats.
