### ISSUE TITLE
Filters for shortcuts page (Show all, used and unused shortcuts only)

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#7863]
It would be very nice if it would be possible to filter shortcuts based on whether they are set or not, to easily edit only the ones that you have set.

So 3 settings:
- Show all shortcuts
- Show set shortcuts
- Show not set shortcuts 

It would perfectly fit right next to the search input field

**Comment by Fhining** [comment]
This is a great request. It would totally improve the shortcut page experience.

**Comment by niksedk** [comment]
How is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

**Comment by rRobis** [comment]
Seems very good. On fast check didn't notice any bugs
