### ISSUE TITLE
Fix common errors - Issue

### ISSUE THREAD

**Issue by nautilus7** [SubtitleEdit/subtitleedit#7867]
Hi, I am using the "Fix common errors" tool. Under that, there is an option to "Fix commas" which fixes various issues in text subtitles with commas, like detecting whether there is a space after comma.

Problem is with the Greek word `ό,τι`. This word, like you see has a comma inside it. The comma is used to distinguish it from `ότι` without comma, which has a different meaning.

As a result, the "Fix commas" tool detects `ό,τι` as an error and tries to correct it to `ό, τι` by adding a space. Is there a way to add an exception for this word, or it has to be done programmatically?

Either way, an exception should be made for all variations of the word, which are `ό,τι` `Ό,τι` and `Ο,ΤΙ `

The tricky part if  you decide to add a check for this word is to make sure you match this exact word and not just this sequence of characters. For example, `αυγό,τι λες` is indeed wrong and should be corrected to `αυγό, τι λες` by adding a space.

![ss1](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/43feac98-91c4-4b61-8064-676540b4ae23)
![ss2](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/d4063c28-caf8-4852-a6d0-fb8c079df57d)

**Comment by niksedk** [comment]
With a subtitle like this (and Greek), I do not get any available fixes:

````
1
00:00:01,000 --> 00:00:03,000
ό,τι and Ό,τι and Ο,ΤΙ.

2
00:00:03,024 --> 00:00:05,024
- ό,τι Ό,τι and Ο,ΤΙ.
- ό,τι Ό,τι and Ο,ΤΙ.
````

**Comment by nautilus7** [comment]
Hi, sorry for the late reply.

That is odd. Let's me check again (this weekend) with your example subtitle and various versions of subtitleedit, and get back to you. Thanks.

**Comment by nautilus7** [comment]
Just tested with your example subtitle. I DO get the suggestion to add a space after commas.

![fix-commas-new](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/74519727-a62c-4f83-9b0e-bdf0ed36c0d6)

**Comment by nautilus7** [comment]
Same with "fix missing spaces" option...

![Uploading fix-missing-spaces-new.png…]()

**Comment by nautilus7** [comment]
Same with "fix missing spaces" option...

![fix-missing-spaces-new](https://github.com/SubtitleEdit/subtitleedit/assets/1540233/9bdc6cae-574f-4aa2-aac3-0e414457557a)
