### ISSUE TITLE
Issues with MyMemory in Auto-translate

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#7875]
While we're on the subject, the output when using MyMemory sometimes will get strange additions to it. And in Hebrew and Russian it comes back as, like, codes for individual letters instead of the letters themselves. I'm attaching an English file and several translations.
[mymem.zip](https://github.com/SubtitleEdit/subtitleedit/files/14077428/mymem.zip)

**Comment by niksedk** [comment]
Hopefully better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip  ?

**Comment by darnn** [comment]
The same, sadly. I should mention I haven't given it an API key, if that affects it.

**Comment by niksedk** [comment]
OK, thx for testing... should now really be fixed: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Seems to mostly be fixed, but I will still occasionally get a "u05da" or "u05d4" here and there. Also, the way the text is split in the lines of the translation isn't quite the same as in the source:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/860b1c4a-e935-4eec-b88b-1deb512f8d0b)

Here, in the translation, `"I will be` jumped up to the previous line, along with the quotation mark.

**Comment by niksedk** [comment]
>Seems to mostly be fixed, but I will still occasionally get a "u05da" or "u05d4" here and there

thx, was a json decoder bug - should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Working fine on this end now, thank you!

**Comment by niksedk** [comment]
Thx for reporting and testing :)
