### ISSUE TITLE
VLC.exe file move renders program useless

### ISSUE THREAD

**Issue by ayathedoggo** [SubtitleEdit/subtitleedit#7884]
I downloaded VLC Nightly (dev build of VLC) after having previously set up (and really enjoyed) SE, and SE would not open.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/105717495/8c774a0a-4e1c-4282-bbbb-7e1fdf70fac6)
It returned an Assertion failed message, and I understand, as I did change the files. However, the program would automatically close without opportunity for input from me, and I could thus seemingly not remedy the issue on my own by re-specifying the location of VLC.

I tried via %AppData%, the Settings.xml, finding VLC media player, listed as "Relative", specified location, tried my best to copy how it looked for FFmpeg, still wouldn't open.

I reinstalled the program, made backups of some app data.

It would be great if an option to change the file location was possible.

I love SE, and look forward to future updates.

**Comment by niksedk** [comment]
I've not tried VLC 4 alpha/beta in a few years... but it's probably very unstable still.

You can change the VLC location in Options - Settings - Video player
