### ISSUE TITLE
[required features] batch add tags for every ass file 

### ISSUE THREAD

**Issue by Cairl** [SubtitleEdit/subtitleedit#7886]
When batch converting ass subtitles, I hope to add this feature. It is used to add tags to hundreds of ass subtitles all at once.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/20336299/3dca08be-ea39-45e8-bf7f-37eff4e2c61a)

**Comment by LeonCheung** [comment]
You can already do that via the Multiple Replace feature while doing batch conversion:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/1833f303-743c-4cec-bf19-cc221dbeed64)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/6fb8dbad-ba60-4726-ac2e-0ecab4911713)
