### ISSUE TITLE
Why is this happening? Help, please!

### ISSUE THREAD

**Issue by lowriderxx** [SubtitleEdit/subtitleedit#7888]
https://github.com/SubtitleEdit/subtitleedit/assets/158306320/8f9e2c77-3090-49b0-8293-415896077fe7

This keeps happening and I don't know what to do! I've been using Subtitle Edit for a long time and this never happened and I'm getting desesperate! Please, help.

**Comment by niksedk** [comment]
Perhaps a corrupt video file? 
Try re-encoding to a new mkv/mp4 file, e.g. using Handbrake or ffmpeg.

**Comment by lowriderxx** [comment]
Yeah, I think that might be it. Can you tell me how do I re-encode the file? Thanks!

**Comment by matmaggi** [comment]
I believe this is a general bug. It happens several times with my files. If I play before a shot change, it plays ok. But if I pause in the "sketch" area, it jumps forward like your video. But if we close and restart SE, it plays the sketch smoothly, but skips in another random part that was okay before. Not sure what is the problem.

**Comment by coastal45** [comment]
I've seen this problem lately from time to time. It seems to start when I'm entering/editing in the text box. Playback starts by itself.
Then, if I stop the video and undo the last two edits, it's back to normal.
I wonder if it's a hotkey problem. It always starts while entering text.
