### ISSUE TITLE
[Bug] Character count not showing properly in the text box.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#7889]
I think it has something to do with this: https://github.com/SubtitleEdit/subtitleedit/commit/0dcea07dc6009a43cbb2ddd3dc9fd52624e3beb3#diff-dda74420a3ca009425ef93b861075046d6a46e335e4f5f499841caa3ad42d682

When you first click on the line from the List, it shows the correct count:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/20923700/fc71636f-9007-4285-a473-45091c34e242)

But then when you click in the text box:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/20923700/0959fd10-610a-45f4-ab6a-2909f005fe49)

Which is causing some other issues:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/20923700/93dfb939-fb99-40c2-b3e1-e5cc8e092234)

I'm using the option `Ignore Arabic Diacritics`
The line:
```
إذًا لا يكون المرء عظيمًا
إلا بأن يكون مثاليًا؟
```

Steps to recreate:
1. Add the text to a line.
2. Click on some other line from the list view.
3. Click on the line that contains this text.
4. Click inside the text box.

I noticed when writing in the text box, the characters count is dropped by one whenever I write a diacritic.
Examples of a diacritic: ً  ُ  َ

**Comment by niksedk** [comment]
thx for the info :)

Is this by any change better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Much better. :)
Thanks!

**Comment by OmrSi** [comment]
@niksedk Hey, been a while.
Looks like this is still broken, but the other way around now.
If you choose `Count all characters`, it still ignores the Diacritics.
In `Count all characters` and `Ignore Arabic Diacritics`, this line has the same length:
```
إذًا لا يكون المرء عظيمًا
إلا بأن يكون مثاليًا؟
```

**Comment by OmrSi** [comment]
It seems like the code is flawed?
When a character in Arabic something like `بً` it's seen as 2 elements, not one.
So the conditions in the `Ignore Arabic Diacritics` aren't actually working, but the code is just adding 1 when it receives more than 1 element, which is how `بً` is seen.

This is why the "Count all" isn't working, it's receiving two elements but only adding one:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/20923700/b3a5ad75-5b93-4327-8797-a9ccb19c894a)

**Comment by niksedk** [comment]
@OmrSi: Could you give some sample string + counts, for CalcAll and CalcIgnoreArabicDiacritics ?
Perhaps a list of all possible Arabic letter with Diacritics ?

The current code works for some other languages where complex chars should only count as 1.

**Comment by niksedk** [comment]
Letters with Diacritics should be counted as `two` according to Netflix etc. ?
Would `one` not be more correct?

**Comment by OmrSi** [comment]
@niksedk Diacritics shouldn't be counted according to Netflix.
So, technically, letters with Diacritics should be counted as one, which is what the `Ignore Arabic Diacritics` option rightfully does.

`Ignore Arabic Diacritics` was causing an issue, the one described here, but then you made some changes and it was fixed, but now when I return your code to the way it was, it doesn't cause any issues, so I'm guessing the issues was actually elsewhere and it was later fixed, meaning the changed made here https://github.com/SubtitleEdit/subtitleedit/commit/51f95d9489e06a4a78cd3c9c3dbde7570b008fc2 can be undone.

Now the issue is that "Count all" doesn't actually count the Diacritics, which it should since it counts everything, that's how it's defined in Arabic, at least.
See, some companies still count Diacritics.

The line `أهلًا وسهلًا` should be 12 for CalcAll and 10 for CalcIgnoreArabicDiacritics.
The line `مرحبًا بك` should be 9 for CalcAll and 8 for CalcIgnoreArabicDiacritics.
The line `إنه شابّ يُعجب` should be for 14 CalcAll and 12 for CalcIgnoreArabicDiacritics.

**Comment by niksedk** [comment]
Hm, so perhaps you should have a `Count Arabic Diacritic +1` ? (and remove `Ignore Arabic Diacritics`)

Could you list all letters with Diacritics?

**Comment by OmrSi** [comment]
Arabic Diacritic are composition characters, they can be put on any letter, there are 26 letters and about 8 Diacritic, so it's a bit hard to make a list.

`The current code works for some other languages where complex chars should only count as 1.`

Hmm, it's weird that `Count all` in other languages doesn't count composition characters. Makes things a but complicated.
It's a bit counterintuitive that `Count All` wouldn't count the Diacritic as well, but if that's how it is for other langaues, I guess you can change the option to `Count Arabic Diacritic`.

**Comment by OmrSi** [comment]
I guess we could change the whole option to `Count composition characters`?

**Comment by OmrSi** [comment]
We could make the original `Count all` count everything, including composition characters, and change `Ignore Arabic Diacritics` to `Exclude composition characters`, how does that sound?

**Comment by OmrSi** [comment]
How does this look https://github.com/OmrSi/subtitleedit/commit/dec8beec018f1f4d2891c99458af89bc9443e43a ?

**Comment by niksedk** [comment]
Hm, I think I would like to keep `Count all` as `Count all characters as one`, sorry.

Counting diacritics as an extra character should be the special option.

**Comment by OmrSi** [comment]
@niksedk It's a bit weird that `Count all` doesn't actually count ALL.

> Counting diacritics as an extra character should be the special option.

Actually, most programs do count composition characters and don't even have an option to exclude them, like Subtitle Workshop and Aegisub, Ooona has an option called `Don't count composition characters` that is off by default. Most of the other online platforms I use do count them as well. Even SE used to count them by default, which is why I had added the option to Ignore the Arabic ones. The special case should be to exclude them, since they are counted if you write them in any text editor.
This is why we had the options `Ignore Arabic Diacritics` and `Ignore Thai Composite Characters`, and the funny thing is they were identical.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/20923700/d7425e3a-adca-4dbc-91bf-52b380266596)


Anyway, I guess the best next thing is this: https://github.com/OmrSi/subtitleedit/commit/24deb908560eca9c0ca566a06b2a5b79b6ef28be

**Comment by niksedk** [comment]
Your code looks good :)
Could you do a PR?

The `Count all` count all Unicode characters as one. Older programs just cannot count Unicode characters which is why SE calculated two chars for some Unicode characters earlier.

Will do a SE 4.0.6 relatively soon...
