### ISSUE TITLE
The video plays outside its assigned space!

### ISSUE THREAD

**Issue by dramirvf** [SubtitleEdit/subtitleedit#7891]
Hi,
I have installed Subtitle Edit V 4.03 and have chosen a layout to show video playback on the right side.
But when I start the playback, a smaller pop up appears over the subtitle area on the left which plays a distorted video and also interferes with the layout. Nothing will ever play on the predefined location for video playback.

It does not have anything to do with the video engine. All of them have the same result.

Any suggestion?
![Subtitle Edit](https://github.com/SubtitleEdit/subtitleedit/assets/40552131/1701fd34-fd45-4dbf-b76b-7a60e9cc576d)

**Comment by niksedk** [comment]
Hm. do you have a "Video - Re-dock" menu item: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/a4b7fc4e-1e4b-4111-bb43-932b0f179604)

Also, perhaps a reset settings could help. Go to Options - Settings - Restore default settings

**Comment by dramirvf** [comment]
> Hm. do you have a "Video - Re-dock" menu item: ![image](https://private-user-images.githubusercontent.com/1261331/301612008-a4b7fc4e-1e4b-4111-bb43-932b0f179604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4Mzg3NDAsIm5iZiI6MTcwNjgzODQ0MCwicGF0aCI6Ii8xMjYxMzMxLzMwMTYxMjAwOC1hNGI3ZmM0ZS0xZTRiLTQxMTEtYmI0My05MzJiMGYxNzk2MDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMDE0NzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWUwNmY4ZTY2ZTU1YWFmMmYyNTI4NDVkNWFmODU4Y2RiNzdhNTAyYTVkODBkMTZkYmE0NDNlODNiZGFiYzU3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rx4EeiPnS5_HtMq8z7DhcPT2d5mrRMD6JXK-TijCpJE)
> 
> Also, perhaps a reset settings could help. Go to Options - Settings - Restore default settings

Docking / Un-docking video controls don't change anything. Actually the controls are docked when the issue happens. The flying portion is also stuck in its weird own location and doesn't move or interact with mouse hovering or clicking.

Restoring the setting also did not change anything.
