### ISSUE TITLE
[BUG] Subtitles not extracted from Twitch stream

### ISSUE THREAD

**Issue by superbonaci** [SubtitleEdit/subtitleedit#7893]
Download Twitch stream https://www.twitch.tv/videos/1980035805 in ts format. Open with Beta version.

Says No subtitles found.

MediaInfo data:
![output](https://github.com/CCExtractor/ccextractor/assets/8339596/9ede7203-22a8-4596-9b0d-0e07cc82dfc7)

**Comment by GrampaWildWilly** [comment]
I took this as an intellectual exercise.  Am I helping?  Probably not.  But here goes . . .

First I downloaded the Twitch stream using Video Download Helper, a product you can find elsewhere on GitHub.  VDH did not offer a ts stream to download, just mp4.  I downloaded that.  Indeed, it did have closed captions.  But Mediainfo didn't list them.  They appeared in VLC.  VLC claims there are 4, not 8, closed captions tracks.  But only the first one actually contains closed captions.  According to VLC, now.

Then I downloaded the same stream with ffmpeg.  As an mp4, for comparison.  There was no difference with what I downloaded with VDH.  Exact same number of bytes, same video properties, same audio properties, same alleged 4 closed captions tracks, same only the first one actually containing captions.

Mediainfo on both of those showed no captions.

Then I downloaded the video with ffmpeg again, but this time I specified .ts as the output file.  Now I'm seeing Mediainfo the same as @superbonaci.  8 closed captions streams.  But despite that, VLC still shows only 4 closed captions streams & only the first of them actually contains closed captions.  I tried using Media Player Classic but it didn't recognize captions of any type.

I opened the video in SE, of which my version is 4.0.3 beta 113, which I admit may not be the absolute latest, but I did get it just a few days ago.  The video does play fine, with audio, but without captions.  I tried selecting various different formats in the Formats drop-down menu but nothing I tried actually made captions appear in the MPV player.  I'm actually surprised I didn't make SE just pack it in with some of the things I did.  Two formats caught my eye under the title Scenarist.  The entries in the menu contain the words "closed captions."  But they didn't make captions appear.

OK.  That's enough from the guy who hasn't a clue what he's doing.  Time to make way for those who actually do know what they're doing.

**Comment by superbonaci** [comment]
Video Download Helper requires to change the settings to get m2ts streams. Anyway here's a sample video:

[output.ts.2.zip](https://github.com/SubtitleEdit/subtitleedit/files/14138476/output.ts.2.zip)
[output.ts.1.zip](https://github.com/SubtitleEdit/subtitleedit/files/14138477/output.ts.1.zip)

Restore it:
```
unzip output.ts.1.zip
unzip output.ts.2.zip
cat output.ts.1 output.ts.2 > output.ts
```

**Comment by GrampaWildWilly** [comment]
I had some errors trying to reconstruct that video.  But my errors are a distraction here.  Somebody who can actually help you should pick up the trail.

**Comment by superbonaci** [comment]
What kind of errors? There are no errors when extracting the zip file.
