### ISSUE TITLE
Tool for replacing user defined words

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#7894]
It would be nice to have some sort of way to define user word list that would be replaced in the current file.   

It would be useful, when Whisper consistently makes same mistake in all videos, so that i wouldn't have to fix it myself every time.

User List example:
Incorrect term to replace  --- Correct term to replace with

**Comment by darnn** [comment]
I suggest you look into `Fix common errors`->`Fix common OCR errors (using OCR replace list)`, and into `Edit`->`Multiple replace`. You can do this with both of these.

**Comment by rRobis** [comment]
> I suggest you look into `Fix common errors`->`Fix common OCR errors (using OCR replace list)`, and into `Edit`->`Multiple replace`. You can do this with both of these.

Ooh, I completely missed Edit->Multiple replace. Thanks
