### ISSUE TITLE
When SE translates, letters in a sentence are pushed to the next space

### ISSUE THREAD

**Issue by codingcafeGH** [SubtitleEdit/subtitleedit#7895]
When SE translates a long text, or when the translation is much longer than the original, the length of the original sentence and the translated sentence will be different, and if the translated sentence is longer, the space for the translated sentence will be pushed to the next space.

If this keeps happening, the space between the original and translated sentences will eventually be very close together, and the timing will not work.

The same thing happens when I use the merge lines feature.

It would be nice to have a way to force them to be on the same line functionally.

**Comment by niksedk** [comment]
This is a general issue with translation as merging gives translation engines a better change of doing a good job.
Re-splitting can be difficult.

Latest beta has some improvements in this area: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

If you have any issues, attaching the source subtitle + some screenshots + detailed description can help me improve the re-splitting.
