### ISSUE TITLE
CLI `/RemoveTextForHI` does not adhere to the `Remove if only music symbols` GUI setting

### ISSUE THREAD

**Issue by Hlsgs** [SubtitleEdit/subtitleedit#7898]
Even if `Remove if only music symbols` is checked in the GUI `Romeve text for HI` interface, running the subs through the CLI does not remove such lines. The other settings in the GUI seem to be respected by the CLI.

**Comment by niksedk** [comment]
Thx for the bug report :)

I've tried to fix the CLI issue here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip
Better?

**Comment by niksedk** [comment]
Hm... works perfectly fine here.
