### ISSUE TITLE
New Icons missing in 4.0.3

### ISSUE THREAD

**Issue by PaulVeld** [SubtitleEdit/subtitleedit#7899]
In a fresh install on Window10, the new icons are missing.
![afbeelding](https://github.com/SubtitleEdit/subtitleedit/assets/23476332/5039197f-d0ef-49bf-a3e3-80f14c04afd1)
In the Settings > Appearence the Graphic Buttons panel is empty!
Maybe it has to do with the fact that I installed the program in a different useraccount (localadmin) then the user that I normally login.

**Comment by GrampaWildWilly** [comment]
What happens if you stretch the window to be a little wider?

**Comment by PaulVeld** [comment]
No change. It is already full screen.
