### ISSUE TITLE
Adding music notation to italics, removes italics

### ISSUE THREAD

**Issue by Charvelx04** [SubtitleEdit/subtitleedit#7905]
When selecting two lines (for this example) that are already italicized, when you highlight, right click, add music notation... the second line loses it's italics.

I just noticed this updating a sub that needed just a few changes... I tested it twice before taking these screenshots to make sure I wasn't being senile and seeing things.

![1](https://github.com/SubtitleEdit/subtitleedit/assets/35577096/de46dabc-fd3b-456e-a290-0ef7b66d17cd)
![2](https://github.com/SubtitleEdit/subtitleedit/assets/35577096/1e6851c7-a482-43a5-aa51-3a52497d849e)
![3](https://github.com/SubtitleEdit/subtitleedit/assets/35577096/779d177d-d47b-424e-97f3-7f88f0447fb9)

**Comment by Charvelx04** [comment]
I know you're busy, but since this regression gets in my way, having to repeat steps to replace missing music quotes, I am going to go back to 3.16 for now. 

I'll keep an eye out for new releases if/when you've had a chance to take a look. :)

By the way... it also affects large groups of selected text. If you select say, ten, twenty lines of music and you're fixing the musical notes where you have to remove those notes, it gets rid of all of the italics. Which.. in turn, you have to go back and re-add.

**Comment by niksedk** [comment]
Thx for the info :)

Yeah, I've been pretty busy with my day-time job, so I've not had much time for SE, but now SE 4.0.4 will be out soon, so I'm going through issues for stuff like this.

Hopefully fixed in the latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

**Comment by Charvelx04** [comment]
I will test it, and let you know as always. :)

**Comment by Charvelx04** [comment]
As of this email... I have tested adding, removing music symbols with and without italics.

I reinstalled 4.0.3 over the top of 3... and then applied the beta files.

Issue seems to be fixed in that version.

Thank you for the resolving the matter. :)

**Comment by niksedk** [comment]
Thx for reporting and testing :)

**Comment by Charvelx04** [comment]
Glad to help!

Yeah anytime...
