### ISSUE TITLE
Open LLms API support

### ISSUE THREAD

**Issue by TheNeObr** [SubtitleEdit/subtitleedit#7908]
I've been trying to use the gpt chat function but used opensource llms with LMSTUDIO as a server but it doesn't seem to have support, is there any thought to add this support for this type of use, this would greatly reduce the translation work for independent translators.

**Comment by darnn** [comment]
This doesn't address your issue, but if I may ask, what models are you running in LMSTUDIO that produce translations you're satisfied with?

**Comment by darnn** [comment]
But also, see if this helps you any:
https://github.com/SubtitleEdit/subtitleedit/issues/7704

**Comment by TheNeObr** [comment]
I registered it as a problem because I was unable to generate a new topic in the function request, another point as I was unable to use the same path as the Openai api, as the call is similar in LMSTUDIO, for this I need the api working to test which model does better, but the vast majority of models that do good PR in several languages are also very good at translating. 13b+

> This doesn't address your issue, but if I may ask, what models are you running in LMSTUDIO that produce translations you're satisfied with?
