### ISSUE TITLE
Addition to shortcuts list in settings to be able to exit the program

### ISSUE THREAD

**Issue by Onthrax** [SubtitleEdit/subtitleedit#7911]
Hello,

I would like to request the addition of a new shortcut in the settings menu. Most of the menu items under File can be set to a custom shortcut, but Exit is not available in the list. Please add it.

Thank you.

**Comment by niksedk** [comment]
You can try `Alt+F` and then `X`

**Comment by Onthrax** [comment]
Yes I know that I can do it that way, but that's not what I am requesting. I am asking for an update on the custom shortcuts window in the settings, so I can assign my own custom combination for it.

**Comment by Onthrax** [comment]
@niksedk please reopen the issue, as I cannot seem to find where to do this myself.

**Comment by Onthrax** [comment]
Awesome. Thank you! @niksedk
