### ISSUE TITLE
EOL change in batch convert

### ISSUE THREAD

**Issue by dramirvf** [SubtitleEdit/subtitleedit#7915]
I have set some convert options to implement on some files in the batch convert tool.
After conversion, unfortunately, I noticed that additional to my requested convert options, all LFs have also been converted to CRLFs.

I did not request any changes on EOLs and I want to keep all EOLs as they are.

How could I make Subtitle Edit to ignore EOLs?

**Comment by niksedk** [comment]
In SE some formats have hard coded the type of EOL - other more text based formats adhere to the operating systems EOL... like `\r\n` on Windows and only `\n` on Linux.
