### ISSUE TITLE
Would really like to have a IMSC 1 Profile for IMF

### ISSUE THREAD

**Issue by ryzen88** [SubtitleEdit/subtitleedit#7916]
Subtitle edit already has the Netflix IMSC 1.1 Japanese profile, but like the name suggest this is officially only for Japanese.
Would be really nice to have a IMSC 1 profile.

We use IMSC 1 in .xml or .ttml files for assembly of IMF packages, but Resolve is really horrible handling subtitles so would be so sweet if we could export IMSC 1 directly from Subtitle edit.

**Comment by niksedk** [comment]
Timed Text IMSC 1.1 added in latest beta
