### ISSUE TITLE
[BUG] The Subtitle Operation Not Complete | Subtitle Edit 4.0.3 

### ISSUE THREAD

**Issue by MyKareee** [SubtitleEdit/subtitleedit#7918]
Version : Subtitle Edit 4.0.3

Function :  Audio to Text (Whisper : large-v3)
Video Language Source : Korean
Translated to : English

Usually it takes around 30 - 90 min per video. but when its popup and say its completed... I open the subtitle file (srt) it only translated the first 2 minute? 

Picture Below Show the Proof of Translated of first 2 minute 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/116965857/60bd7165-3e19-4998-87c2-473b98f4c6e8)

MediaInfo of the video i use ... the runtime is around 1 hour 17 min... 

![1](https://github.com/SubtitleEdit/subtitleedit/assets/116965857/d8282c87-2102-4965-ba2e-ef30370f05c8)

Acknowledgement : I already tried with 4.02 and 4.0.1 with the same setting / video

Please let me know if u need more informaiton.

**Comment by Purfview** [comment]
Which "Whisper" exactly?

Probably a model crashed because of the low GPU memory, try `-bo=1` option.

**Comment by niksedk** [comment]
Also, do check your `whisper_log.txt` in the SE data folder... you will probably find something about out of memory.

**Comment by MyKareee** [comment]
> Which "Whisper" exactly?
> 
> Probably a model crashed because of the low GPU memory, try `-bo=1` option.
> 
> EDIT: Or use a smaller model, in your case `medium`.

I tried with medium. same thing happen... what is -bo=1 ? I dk / about this 

> Also, do check your `whisper_log.txt` in the SE data folder... you will probably find something about out of memory.

SE data folder ? still cant find the whisper log.txt... T.T

**Comment by Purfview** [comment]
> I tried with medium. same thing happen...

Then you need to run "Whisper" directly with `--verbose=true` and look what happens.
What is your GPU and how much VRAM it has?

**Comment by MyKareee** [comment]
> What is your GPU and how much VRAM it has?

GPU: NVIDIA GeForce GTX 1050 Ti
VRAM: 4096MB (4GB)

**Comment by Purfview** [comment]
> > What is your GPU and how much VRAM it has?
> 
> GPU: NVIDIA GeForce GTX 1050 Ti VRAM: 4096MB (4GB)

Medium should work on this.
