### ISSUE TITLE
Papago translator api is going to change

### ISSUE THREAD

**Issue by wjdtkd9977** [SubtitleEdit/subtitleedit#7922]
Hi. Thank you for making this promgram.
I've been using this program for a long time.

However, the merging API system from Naver Development Center to Naver Cloud Platform, the current system won't work from March 1st 2024. ( https://developers.naver.com/notice/article/14501 )

Could you update the API value of the program?

Thanks a lot.

**Comment by niksedk** [comment]
LOL, I've not even released a stable Papago yet... only the beta works correctly.

Can you find the API info page? Also, it's probably impossible to register for me as I live in Denmark... so I can be rather hard to fix.
