### ISSUE TITLE
[BUG] Text disappears when merge lines

### ISSUE THREAD

**Issue by undergolan** [SubtitleEdit/subtitleedit#7923]
Hello!

After updating to release 4.0.3, the following bag is observed: when merge two lines, the text of the second line disappears. The error is reproduced on two different computers (one on Windows 7, the other on Windows 10) and using various subtitle files. 

There is no such issues on release 4..0.1.

https://github.com/SubtitleEdit/subtitleedit/assets/159784535/317854fa-83fe-4659-9406-2bea88f6e61e

**Comment by niksedk** [comment]
Hm, I cannot re-create this... could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip ?

**Comment by undergolan** [comment]
Everything is working correctly in this release.
Thanks for your great work.  I am happy to use this program.
:)
