### ISSUE TITLE
VirusTotal and Jotti detect the presence of a Trojan "TrojanLoader.MSIL.DaVinci.Heur" in the portable versions of SubtitleEdit.

### ISSUE THREAD

**Issue by TheMoye** [SubtitleEdit/subtitleedit#7929]
Hello everyone,

I have scanned versions 4.03, 4.02, and 4.01 of the portable version of SubtitleEdit on VirusTotal and Jotti websites. The VBA32 antivirus detects the presence of "TrojanLoader.MSIL.DaVinci.Heur" :

SE403
https://www.virustotal.com/gui/file/8c336d9e340102ab6664b0063a1a4d2b4156d5b702913621369c2124d6be51d8
https://virusscan.jotti.org/fr-FR/filescanjob/w0dvkqy2qo

SE402
https://www.virustotal.com/gui/file/f729b94a352f433ef7df1d7950d04cd036aa975d2811b34015029f3e30cff69b
https://virusscan.jotti.org/fr-FR/filescanjob/2rml5qmlgb

SE401
https://www.virustotal.com/gui/file/3729606b10a6cc47bc72c6ff1570931eaf1072974f979137ea6239ed6edada48
https://virusscan.jotti.org/fr-FR/filescanjob/sg29f11wdw

Is this a new false positive?

**Comment by Purfview** [comment]
> Is this a new false positive?

Yes.

**Comment by niksedk** [comment]
This is a very common issue - see 
https://github.com/SubtitleEdit/subtitleedit/issues?q=is%3Aissue+virustotal+

To help, please report SE as a false positive to your anti virus provider (or failing ones on virus total), thanks.
You should hear from the anti-virus providers in about a week.

**Comment by niksedk** [comment]
Write to the anti-virus provider...

**Comment by niksedk** [comment]
And use common sense. 
One to two alarms from smaller anti-virus providers are normally safe. 

Every single version of SE has at least two flags, but the flags go away if someone write to the vendors.

**Comment by niksedk** [comment]
You can find emails here: https://gist.github.com/skmedix/6cdce9d6d3b464c1bd719b72d1f6bce4

**Comment by TheMoye** [comment]
> And use common sense. One to two alarms from smaller anti-virus providers are normally safe.

I am not convinced by the 'advice'.
The 'common sense' is neither universal nor a barrier to error: it is not once the harm is done that questions should be asked.

It is not up to me, an average user who may not necessarily have the skills to know whether downloading is safe or not, to tell the antivirus provider that they are wrong. I'm just passing along the information. 🤷

**Comment by niksedk** [comment]
Again, write to the anti-virus provider if you're in doubt.

**Comment by Purfview** [comment]
> It is not up to me, an average user who may not necessarily have the skills to know whether downloading is safe or not, to tell the antivirus provider that they are wrong. I'm just passing along the information.

You are passing it in the wrong place, this is not an antivirus dev place.

**Comment by TheMoye** [comment]
> You are passing it in the wrong place, this is not an antivirus dev place.

I disagree, that's exactly where it needs to be raised. I'll pass the information on to the developer, the person most capable of knowing the program. It's not up to the user to guess out of the blue whether it's a false positive or not; they have no authority.

In what strange world is it not up to the developer/publisher to indicate that their program is legitimate and that the antivirus is mistaken? 🤔

**Comment by niksedk** [comment]
If you can check a file on virus total, you should also be able to send an email...

But SE 4.0.3 portable looks fine to me on virus total: https://www.virustotal.com/gui/file-analysis/NWIxNzQ4Y2VkMjk1NzYxM2M5M2ViZWE2YmZlMDYwMTc6MTcwODQ5NDkyOA==

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/ab745b59-8c5e-41a3-b7fd-d1ccb666ab44)

**Comment by TheMoye** [comment]
> If you can check a file on virus total, you should also be able to send an email...

I can do it, yes, but I don't have a good reason to do it.


> But SE 4.0.3 portable looks fine to me on virus total

Indeed, VBA32 seems to have fallen into line, including for previous versions !

![ScreenshotsVT](https://github.com/SubtitleEdit/subtitleedit/assets/46683101/1ae7bf7b-1427-4a8e-a04e-9476a37499c3)
