### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by hugok79** [SubtitleEdit/subtitleedit#7936]
In the Menu Bar, under Options ->Settings->Auto-transtale the setence **More info** doesn't appear everywhere

![Picture](https://github.com/SubtitleEdit/subtitleedit/assets/16929048/f0c26719-f388-4062-99a6-9ad01c08676d)

**Comment by niksedk** [comment]
Thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

**Comment by hugok79** [comment]
It's better now but one of the translations doesn't show the whole text... strange. This doesn't happen in English

![Picture](https://github.com/SubtitleEdit/subtitleedit/assets/16929048/78a31e7f-30ae-4617-9e71-acfcd939d23c)
