### ISSUE TITLE
Bug: Regex: Replacing `(\s)` captured `<br />` line break results in the replacement being doubled

### ISSUE THREAD

**Issue by redactedscribe** [SubtitleEdit/subtitleedit#7940]
`(\s)` captures the visual aid `<br />`, and replacing it with `foo$1` will give the result `foo<br />foo<br />`, which appears to be a bug.

My expectation is that when `(\s)` matches a `<br />`, it should be treated exactly like a single `\n` new line would be: `foo$1` should give `foo<br />`.

I looks like there's actually two consecutive `<br />`s present per line, and only one is being rendered (there are no literal "\<br />" strings in my subtitle's source). For example, searching for regex `\s` via the File > Replace window and stepping through each hit with Find, shows that once you reach a line's end, Find requires to be pressed twice to go on to match the first space character of the next line. That is to say that there are two line breaks per one visual line break. Or so it seems.

My current workaround is to use `\s` minus the new line, i.e. `[\t\f\v\ ]` (no `\r\n`), to avoid capturing new lines, and thereby this bug.

Hope that helps,
Thanks.

Subtitle Edit 4.0.3 64-bit
Windows 11

**Comment by niksedk** [comment]
Sorry, it's not very clear to me... a sample file + screenshots often helps me understanding issues and makes it easy for me to re-produce.

Old issues will be closed as "Won't fix".

**Comment by niksedk** [comment]
I think it's because new-line is `\r\n` on Windows.
