### ISSUE TITLE
Auto-Translate issue

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#7941]
I noticed that when translating using the auto-translate, the lines get shifted. 

Meaning that it doesn't translate exact lines, but some of the text from subtitle line 4 may be in subtitle line 5 etc (resulting in delayed subtitles on the screen).

When doing it by copy-paste method, the timing and content of the lines stay consistent with the original subtitle placement, since every line is dealt with separately.

**Comment by killuaotaku** [comment]
are you using google translate or other?... Yep, the copy-paste method gives problems with papago,deepl,yandex and bing translator...

**Comment by rRobis** [comment]
I'm talking about auto translate without copy paste and with default google translate. (the copy paste works for me better in this aspect, as far as i tried)

**Comment by ibandalo1** [comment]
It's the same for me. I have to use the old version to be able to translate automatically.

**Comment by rRobis** [comment]
Probably related ?  #7973

**Comment by rRobis** [comment]
Also i just found out, that if you select specific lines and auto translate them through right click (selected lines --> Auto translate), then the translate dialog is empty, and doesn't translate anything.

**Comment by ibandalo1** [comment]
I don't notice a problem with the copy-paste variant.

**Comment by ibandalo1** [comment]
It looks like they removed the menu where you could choose "No-merging".
![Capture](https://github.com/SubtitleEdit/subtitleedit/assets/161168501/3dff726c-3845-4066-a417-ecfdff7365bb)

**Comment by rRobis** [comment]
I just accidentally found out something amazing 😄 

If you right click on blank space in the auto translate dialog this pops up, and it translates it separately
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/d26e6770-9cfa-4939-ba82-7ce3d118ed4f)

**Comment by ibandalo1** [comment]
Bravo! :+1: It seems to work well with that hidden option!
We can conclude that this is the most unintuitive option ever. :blush:

**Comment by nielka98** [comment]
> Zauważyłem, że podczas tłumaczenia za pomocą automatycznego tłumaczenia linie ulegają przesunięciu.
> 
> Oznacza to, że nie tłumaczy dokładnych linii, ale część tekstu z 4. linii napisów może znajdować się w 5. linii napisów itd. (co powoduje opóźnienie napisów na ekranie).
> 
> Robiąc to metodą kopiuj-wklej, czas i treść wierszy pozostają zgodne z oryginalnym rozmieszczeniem napisów, ponieważ każdy wiersz jest traktowany osobno.

I also have this problem, can someone help me solve it

> I noticed that when translating using the auto-translate, the lines get shifted.
> 
> Meaning that it doesn't translate exact lines, but some of the text from subtitle line 4 may be in subtitle line 5 etc (resulting in delayed subtitles on the screen).
> 
> When doing it by copy-paste method, the timing and content of the lines stay consistent with the original subtitle placement, since every line is dealt with separately.

I also have this problem, can someone help me solve it

**Comment by rRobis** [comment]
> > I noticed that when translating using the auto-translate, the lines get shifted.
> > Meaning that it doesn't translate exact lines, but some of the text from subtitle line 4 may be in subtitle line 5 etc (resulting in delayed subtitles on the screen).
> > When doing it by copy-paste method, the timing and content of the lines stay consistent with the original subtitle placement, since every line is dealt with separately.
> 
> I also have this problem, can someone help me solve it

See my answer above https://github.com/SubtitleEdit/subtitleedit/issues/7941#issuecomment-1962833912

**Comment by Internetezoo** [comment]
Hi! Can't embed DeeplX localhost api?
https://github.com/OwO-Network/DeepLX/releases/tag/v0.9.1
deeplx_windows_amd64.exe

**Comment by niksedk** [comment]
Could you try latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.14/SubtitleEditBeta.zip

If it still fails, what error do you get?
