### ISSUE TITLE
Feature Request - Faster Whisper progress indicator

### ISSUE THREAD

**Issue by LucretiaAudrey** [SubtitleEdit/subtitleedit#7949]
Hi! Would it be possible to implement some sort of progress indicator for recognition using Faster Whisper? It's hard when you have no idea how much time is left to go

**Comment by Purfview** [comment]
>Hi! Would it be possible to implement some sort of progress indicator for recognition using Faster Whisper? It's hard when you have no idea how much time is left to go

Use `-pp` command in "Advanced" , then when it's running press F2 to see the Faster-Whisper's progress bar:

```
30% |  91/306 | 00:08<<00:20 | 10.34 audio seconds/s
```

`00:20` is estimated time left.
