### ISSUE TITLE
"Fix common errors" mistakes "{\i0}" for a sentance

### ISSUE THREAD

**Issue by Firegloom** [SubtitleEdit/subtitleedit#7952]
The "Fix common errors" menu seems to mistake "{\i0}" for a sentence, since it tries to add a missing period at the end, even when there already is a punctuation mark in the actual text.
<img width="636" alt="Skärmbild 2024-02-20 162134" src="https://github.com/SubtitleEdit/subtitleedit/assets/139589667/d5f9813b-a367-4806-9ca5-2bb6f832269d">

**Comment by niksedk** [comment]
Thx for the info :)

Should be fixed in latest beta now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip
