### ISSUE TITLE
Traditional Chinese support for ChatGPT Auto Translate

### ISSUE THREAD

**Issue by adan89lion** [SubtitleEdit/subtitleedit#7954]
Hello,

It seems like Traditional Chinese (zh_TW) is missing in `ChatGptTranslate.cs` file.

Also, there are duplicates for Simplified Chinese: `Chinese`, `Mandarin` and `Mandarin Chinese` are the same language. Maybe you can merge them into `Chinese (Simplified)` and add a `Chinese (Traditional)` to the list?

Additional, it would be nice to let user add additional languages, as there are many dialects that are not covered in it.

**Comment by niksedk** [comment]
Can you make this work on https://chat.openai.com ?
Getting a difference between simplified and traditional Chinese?

**Comment by adan89lion** [comment]
Of course.

This is my prompt:
```
Translate the following text to both Simplified and Traditional Chinese:

All human beings are born free and equal in dignity and rights. They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood.
```

and here is the result:

```
Sure, here is the translation in both Simplified and Traditional Chinese:

Simplified Chinese:
人人生而自由,在尊严和权利上一律平等。他们赋有理性和良心,并应以兄弟关系的精神相对待。

Traditional Chinese:
人人生而自由，在尊嚴和權利上一律平等。他們賦有理性和良心，並應以兄弟關係的精神相對待。
```

However, in my experience, when using with local LLMs, the LLM recognize the two different writing systems better with language codes like `zh_CN` (or `zh-Hans`) and `zh_TW` (or `zh-Hant`).
