### ISSUE TITLE
History function of "Search and Replace"

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#7958]
I'm slowly starting to ditch Notepad++ as the extra editor to do replacements.
The spelling check is similar in SE and a few things even better (I like the Google search) and replace all.

But the history function in "search and replace" in Notepad++ also reacts on the up and down keys.
This way you don't need to take your hands of the keyboard to use the mouse and go through the drop-down.

Can you make it similar in SE ???

The conversion of "Hearing impaired" => "normal" has improved a lot and I'm now relying completely on it.
It may miss some things, but doing it in Notepad++ is so much more work.

Thanks for constantly improving this!!

**Comment by ivandrofly** [comment]
> I'm slowly starting to ditch Notepad++ as the extra editor to do replacements. The spelling check is similar in SE and a few things even better (I like the Google search) and replace all.
> 
> But the history function in "search and replace" in Notepad++ also reacts on the up and down keys. This way you don't need to take your hands of the keyboard to use the mouse and go through the drop-down.

Interesting feature, I will take a look
