### ISSUE TITLE
Batch Auto Translate (no Google?) and add new language to LibreTranslate

### ISSUE THREAD

**Issue by thehijacker** [SubtitleEdit/subtitleedit#7968]
Hello,

I always used auto translate (Google v1) to translate to Slovenian and wife was OK with translation. Now I have whole season of English only that I wish to translate to Slovenian and trying the Auto Translate option under Batch convert. But there is no option for Google as engine. Bug or on purpose.

Next I tried with LibreTranslate but I can not find Slovenian language there to select.  On their page it exists:

https://libretranslate.com/?source=auto&target=sl&q=

Can you add it if Google Translate is not an option under Batch convert.

Thank you.

**Comment by niksedk** [comment]
Google translate is rate limited so IMO it makes no sense to have in batch translate as it would fail...

Thx for noticing new languages for libre translate - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip
