### ISSUE TITLE
non-destructive opening of "original subtitle"

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#7971]
After using "translate" and subsequently manually translating and resyncing the translated result, I noticed that it also changed the original text.

The translation I'm currently working on has a lot of lines missing or badly timed in the original subtitle.
It's however still of value for the order and rough timing.

I would like to "protect" that original file from changes in a way that's sticky, so it will keep that status after I close and later reopen both translations.

I believe I still have the original subtitle, so I can revert that subtitle.

**Comment by niksedk** [comment]
You should be able to do this by turning off "Allow edit of original subtitle":
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/ef9e427b-7be0-469f-acf1-2cdd198922f2)

**Comment by fraternl** [comment]
Thanks, I didn't notice that option
