### ISSUE TITLE
OCR window crash (reproducible)

### ISSUE THREAD

**Issue by phagocythus** [SubtitleEdit/subtitleedit#7978]
Hello, I'm experiencing a crash with the settings below, you can reproduce it with image below.
Import the image, invert colors and launch OCR with the settings I use.
When OCR is complete, CTRL-A on the text box and type anything, the OCR window will crash.
If I delete the text before typing anything, the window doesn't crash.

I use v4.0.3

![settings](https://github.com/SubtitleEdit/subtitleedit/assets/158509253/8bef8797-8c75-4482-ad30-429197df5434)
![file_to_ocr](https://github.com/SubtitleEdit/subtitleedit/assets/158509253/a4fd040e-f5ad-4985-9ec6-aa76485820e4)

**Comment by niksedk** [comment]
Thanks for the informaton, but I cannot re-create this.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/7de0780b-d210-4523-a86e-7d4d85b922b7)

I select the text box and press Ctrl+A, and type "a"... 

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/48e397f0-c8ac-437d-aaa3-2d5ac537da07)


No Crash....

**Comment by phagocythus** [comment]
When I do the OCR, the text box show me the words + random characters on 6 or 7 lines I don’t remember I’m not at home right now, I will send you the exact text when at home.
But maybe if you put random words on 7 lines and do the CTRL-A + type « a » it will trigger the crash ?

**Comment by phagocythus** [comment]
Here is the textbox content when I launch the OCR.
I think if you put this, it will crash. I'm able to reproduce it everytime.

Je l’ai
ue
a
s COU
pé
e !

**Comment by niksedk** [comment]
Sorry, I cannot re-create this... and it also sounds like a crash in Winforms/text-control which I cannot fix
