### ISSUE TITLE
Can ollama translation option be added?

### ISSUE THREAD

**Issue by despairTK** [SubtitleEdit/subtitleedit#7980]
Recently, I have tried some AI translations deployed locally. For example, I am currently using ollama and using the open source gemma 7b model. I feel that the translation effect is much better than that of traditional translation service providers. I wonder if it can be added to the automatic translation list of Subtitle Edit.

https://github.com/ollama/ollama

**Comment by Copy2Translator** [comment]
Agreed, it's much needed.

**Comment by niksedk** [comment]
SE beta supports LM studio: https://github.com/SubtitleEdit/subtitleedit/issues/7704

How do one start the ollame api?
Recommanded models?

**Comment by niksedk** [comment]
Included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/ac2bc24b-99a1-48c9-9ffc-a80fb8e3d01a)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/ef3c05eb-cad0-41c4-ac1d-7575049dfc22)
