### ISSUE TITLE
Audio gets out of sync

### ISSUE THREAD

**Issue by GCRaistlin** [SubtitleEdit/subtitleedit#7983]
Audio gets out of sync when [sample video file](https://mir.cr/N42O6DI9) (6 secs) is being played. It can be noticed by the actor's articulation. There's no such issue in MPC-HC.

**Comment by oniiz86** [comment]
@niksedk I was just curious why this bug was closed as the problem still persists, will this ever be looked into?

**Comment by niksedk** [comment]
Seems to work fine here using mpv

**Comment by GCRaistlin** [comment]
I encountered this issue with default settings, i. e. DirectShow. The issue is present with VLC, too.
With MPV, video playback doesn't work at all for me: the screen is black, the Play/Pause button stays looking like Pause ( || ) forever. I'm using Windows 8.1 x64.
MPC-HC radio button is greyed out. I'm using the portable version of MPC-HC. How do I enable it?

**Comment by GCRaistlin** [comment]
The last mpv version that works on Windows 8.1 x64 is [mpv-dev-x86_64-20240922-git-71f2220.7z](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20240922-git-71f2220.7z/download).
With DirectShow, Video Player feature is unusable: the same issue is present on another machine,
As I wrote above the issue is present if VLC is selected as Video Player. ffdshow audio decoder icon appears in system tray when the sample file is being played. VLC itself plays the sample file without any issues, and ffdshow audio decoder icon doesn't appear.
MPC-HC plays the sample file without any issues but it is hardly an option. First, the portable version doesn't suit here. Second, MPC-HC can be set for example to play the next file in the folder after playback. It can lead to unexpected behaviour of SE.
