### ISSUE TITLE
Timecode-shift when auto-translated

### ISSUE THREAD

**Issue by mpek** [SubtitleEdit/subtitleedit#7984]
Hello, 
recognized a shift in timecode in auto-translated version. 
It occurs that some lines (not all) are getting a different timecode when translated, than the original. 
That means that they show at the incorrect position, much too late. 
This does not happen with every translated file, but too often that it can be ignored. Cannot see a fault-pattern. 

The original SRT file gets auto-translated from english to german with Google Translate V1 API. 
The new file is being saved as an SRT in utf-8. 
That's all. 
Seems to be a bug, because there should not be a reason to put the translation to a different starting position than the original sentence. What do you think?

**Comment by niksedk** [comment]
I cannot re-create this.
