### ISSUE TITLE
Replace Issue

### ISSUE THREAD

**Issue by amir385276** [SubtitleEdit/subtitleedit#7985]
Hi Guys
in the new version i can't replace any text or anything correctly
please fix this issue

thanks
![Clip_3](https://github.com/SubtitleEdit/subtitleedit/assets/43181048/a3c5fe46-fea3-4be2-bd47-882cff844b95)

**Comment by niksedk** [comment]
How can I re-create this?

**Comment by amir385276** [comment]
Hi niksekdk
in the new version the issue exist - i can't copy and replace any text from any windows programs or subtitle edit from text line to subtitle edit

every paste or replace cause number 1 in the replace field
![Clip_22](https://github.com/SubtitleEdit/subtitleedit/assets/43181048/0daa5e27-8b9d-442e-9c52-3c080f5951e4)

as you can see i marked and copied text from subtitle edit srt to replace it but replace number 1 in text field

please fix it 

thanks a lot

**Comment by niksedk** [comment]
Sorry, I cannot re-create this.

**Comment by amir385276** [comment]
Hello again
why you are sorry?! i'm so confused.
that's a bug
![Clip_23](https://github.com/SubtitleEdit/subtitleedit/assets/43181048/900f2487-fa00-428d-8dff-06c535b79a89)

![Clip_22](https://github.com/SubtitleEdit/subtitleedit/assets/43181048/1ae4591f-7a20-43bd-9afd-703d69392e27)

if you can't recreate it OK 
have a good day niksekdk
