### ISSUE TITLE
Multiple Replace does not look for text outside of subtitles.

### ISSUE THREAD

**Issue by IIeTp** [SubtitleEdit/subtitleedit#7986]
Subtitles example
```
WEBVTT

NOTE Netflix
NOTE Profile: webvtt-lssdh-ios8
NOTE Date: 2023/09/11 18:41:09

NOTE SegmentIndex
NOTE Segment=595.804 28308@350 149
NOTE Segment=598.139 28675@28658 144
NOTE Segment=280.447 12957@57333 63
NOTE /SegmentIndex

00:00:12.095 --> 00:00:14.472
hello
```
and i'm trying to find strings after WEBVTT, like this `\bNOTE\b.*` (regular expression). but it doesn't work. normal search works fine with this scenario

**Comment by fraternl** [comment]
I like it a lot that search only looks in the subtitle itself.
I used notepad++ before and coming up with a logical expression that wasn't spoiled by non-body text was sometimes hard.

If your request will be implemented, I hope it will be made optional.

**Comment by niksedk** [comment]
You can switch to `Source view` or use a good text editor
