### ISSUE TITLE
False Positive: Musical symbol is placed (when turned on) on commonly used sentences.

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#7987]
I'm bumping now on this one:

<img width="599" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/8692856/68791426-07bf-490f-b120-93118e26c2a5">

o 'clock will get a musical symbol.

I remember having this it in French subtitles.
**J'ai**  will get a replacement as well.

There's another condition where this happens in English, but I can't remember.

**Comment by fraternl** [comment]
Found the other one (it's in the same subtitle).....

<img width="544" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/8692856/0674b498-0347-4b3e-be06-7639cc24df73">

U.S.  => U.♪.

**Comment by niksedk** [comment]
I cannot re-create this.
