### ISSUE TITLE
Dutch OCR wants to replace e-mail to je-mail

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#7989]
<img width="736" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/8692856/c442f82e-de7b-4052-9330-4413d14a97fd">

**Comment by niksedk** [comment]
I cannot re-create this.

**Comment by fraternl** [comment]
I didn't make a fake screenshot.
Was it a Dutch subtitle?

**Comment by niksedk** [comment]
> I didn't make a fake screenshot. Was it a Dutch subtitle?

I typed it and chose "Dutch" in the FCE window (yes, it easier if a subtitle file is attached).
