### ISSUE TITLE
Some more typical false positives in Dutch

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#7990]
P.S. Zoek me maar niet

P.Is. Zoek me maar niet

<img width="806" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/8692856/68efdc55-fafc-42d0-a92a-9d17cf872920">

A - E - I - O - U
A - E - Ik - O - U

**Comment by niksedk** [comment]
I cannot re-create this.

**Comment by fraternl** [comment]
So I have to keep making sure I keep OCR-correction disabled.
A shame as it is potentially a powerful feature.

You do know those are screenshots?

**Comment by niksedk** [comment]
>You do know those are screenshots?

Yes.

Sorry, it could be a broken SE installation... and I cannot re-create the issue.
