### ISSUE TITLE
Shortcut to get Netflix Quality Check?

### ISSUE THREAD

**Issue by HeikeMuc** [SubtitleEdit/subtitleedit#8003]
Hi,
I very often need the button for Netflix Quality Check. Is there any other way than click the mouse on the button? I really would like to have a shortcut for that. 
It also would be good if this window could stay open while working so one could correct one after the other error. 
Thank you.

**Comment by SuperiorAlpaca** [comment]
You can use `alt, T and then N`, or even `alt+T+N` (T has to be first). I use a similar shortcut for Options (`alt+O+S`).

**Comment by HeikeMuc** [comment]
> You can use `alt, T and then N`, or even `alt+T+N` (T has to be first). I use a similar shortcut for Options (`alt+O+S`).

Thank you! Sometimes, the nearest solution is far away ... I will ask another question but open a new thread.
