### ISSUE TITLE
Add new features：Resolution PNGs ''output the PNG of the same size of the whole video''

### ISSUE THREAD

**Issue by KSSW** [SubtitleEdit/subtitleedit#8008]
Can you add the output XML+PNGs file with a resolution of 1920x1080

![image](https://github.com/SubtitleEdit/subtitleedit/assets/76238373/5d92a2a4-29a9-4b0a-9a02-a5d646900ad1)

If we directly output PNG+XML resolution, It's like this

![image](https://github.com/SubtitleEdit/subtitleedit/assets/76238373/acb53d1a-3929-424b-8e0c-ffbbac6c756e)

It should be like this

![image](https://github.com/SubtitleEdit/subtitleedit/assets/76238373/bce2f6bd-c139-48bb-94b6-b51bbf1e0b6f)

Add PNG exports with the same video resolution 1920x1080

![image](https://github.com/SubtitleEdit/subtitleedit/assets/76238373/aabda3c6-080f-4b6d-aef7-2f12375f29c0)

If it's possible to add both of these

![image](https://github.com/SubtitleEdit/subtitleedit/assets/76238373/f6c935ba-7326-45b5-b472-0d16f88977e2)

**Comment by tormento** [comment]
I take this opportunity to ask: please add the capability to output the PNG of the same size of the whole video too.

I want to try to solve a problem that arises with anime by splitting in two the image but the output is the image of the subtitle only and not the whole screen.

**Comment by KSSW** [comment]
Yes
