### ISSUE TITLE
A possible bug?

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8012]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/37066e07-940b-4fb1-8739-b4652ab66346)
Maybe it's supposed to display the start/end time for the cut?

**Comment by niksedk** [comment]
Thx :)
Fixed in https://github.com/SubtitleEdit/subtitleedit/commit/e5bc19548ad5889bb65a63d94ace02ec37d0260b
