### ISSUE TITLE
Subtitle Edit - "application error"

### ISSUE THREAD

**Issue by QuantillionMe** [SubtitleEdit/subtitleedit#8013]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/72719313/643af5f6-7108-4321-914e-45b86e613d1a)

**Comment by niksedk** [comment]
How can I re-create this?

**Comment by QuantillionMe** [comment]
Sorry, I've only seen your message now. 
And now I can't remember which file triggered it. I've used SE since then with no problem. If it happens again I'll make a note of what I was doing.
