### ISSUE TITLE
[Feature Request] Making Selected subtitles as Quote

### ISSUE THREAD

**Issue by coding-hobby** [SubtitleEdit/subtitleedit#8014]
In many subtitling use cases, when a character is speaking to self/songs/recollections etc, the subtitles needs to put within single quotes.

Need a way to select multiple subtitle files and apply quotes on both sides of the subtitle.

Two options needed.  1. right-click on selected subtitles and apply.  2. A shortcut for the feature. 

Here is subs for example.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19731090/92d36328-5da8-4832-b70a-5a6b3f895cf5)

and the subtitles put in single quotes.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19731090/13a1c52f-edab-4464-a6f6-b8f1e0f8381e)

**Comment by m0ck69** [comment]
Also, quotes should be selectable as some languages use "text," or „text”.

**Comment by niksedk** [comment]
Should be possible with `Toggle custom start/end` ?:  
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/56102fa0-4dc2-412d-86aa-2298a416cce9)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/fb897b32-ffb0-4f53-8351-92ed31ebb0e6)

**Comment by m0ck69** [comment]
thanks , works like a charm.
any chance to change quotas marks depending on a language in FCE?
„…” “…” ‘…’ «…»
https://en.wikipedia.org/wiki/Quotation_mark#Summary_table

**Comment by coding-hobby** [comment]
That works great but single is not available in options.  Can you please include it?

**Comment by niksedk** [comment]
> That works great but single is not available in options. Can you please include it? I understand there are workarounds. Checking if you can add it.
> 
> Once way is to apply music symbols and replace them with single quotes. I'm using it at the moment.

You can type anything in the two custom fields...

**Comment by coding-hobby** [comment]
https://github.com/SubtitleEdit/subtitleedit/assets/19731090/a419dfb9-0cfe-4c0d-86c3-9365d498c894

I faced this bug, when using the custom tags method.  The single quotes in the subtitle text goes away.
