### ISSUE TITLE
How to setup find and replace rules from word collection (table or txt)?

### ISSUE THREAD

**Issue by mpek** [SubtitleEdit/subtitleedit#8018]
Looking for a way to quickly setup new 'find and replace rules' template when having a word collection in a table with these rows titles: 

Find what | Replace with | Description

And the words listed below that. 

Is there a way to import that table (or table exported txt file) into SubtitleEdit (Multiple Replace) or convert it into a find and replace rules template?

**Comment by darnn** [comment]
If you open `Multiple replace`, you'll see there are `import` and `export` buttons there. Export what you currently have, then open the resulting file in a text editor and see how it's structured. From that you should be able to figure out how to convert your file into a file you can import. If you can't you can upload it here and I'll try to take a look at it for you.

**Comment by mpek** [comment]
Thank you for your answer. I did already export it and seen that it's an XML document. 
My table has nearly 500 different words to be replacable in SE. It's quite long to wrap the xml code around the values from that table manually, so I wonder if there is a direct import feature that goes from table to xml or table to multiple replace?

**Comment by liam1900** [comment]
> Thank you for your answer. I did already export it and seen that it's an XML document. My table has nearly 500 different words to be replacable in SE. It's quite long to wrap the xml code around the values from that table manually, so I wonder if there is a direct import feature that goes from table to xml or table to multiple replace?

you can use python to create that xml for you.

**Comment by mpek** [comment]
Hi @liam1900 thank you for your hint. Is this like copy/paste my word list to python and generate that xml? If not, what is the workflow?

**Comment by liam1900** [comment]
> Hi @liam1900 thank you for your hint. Is this like copy/paste my word list to python and generate that xml? If not, what is the workflow?

you can use chatgpt for python and speak to it like you are speaking to me send him sample of what you want. and send him that works. so he will create xml file for you in blink of an eye
