### ISSUE TITLE
Shortcut Request for Insert New Subtitle

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8022]
I believe this is a very simple yet useful one:

`Insert new subtitle at video pos, and set end as long as possible.`

Here, "**as long as possible**" means, it should extend to the next nearest subtitle, OR, if there's none, just simply extend to the video end (the very last video frame).  Yes, this may create a super long blank one, but it is really perfect for a workflow like this:

Copy and paste a piece of text into it, then use the **split at video/cursor position** feature to distribute everything properly and much faster.

I know we do have the powerful Import Plain Text tool, but that's totally different, and it doesn't support appended import.

Also, this is super handy for doing dictation and timecoding work all together in SE, especially for very short videos.

**Comment by AuroraMartell** [comment]
I agree with this!

**Comment by niksedk** [comment]
How does this work?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/c3cd217a-6466-49a6-8b8b-fb5ca3d45f92)

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Amazing! Thank you so much @niksedk! Trust me, it's gonna be a feature of great potential.  ;)
