### ISSUE TITLE
SubtitleEdit always uses Unix newlines, even on Windows.

### ISSUE THREAD

**Issue by guijan** [SubtitleEdit/subtitleedit#8026]
This can cause some issues. The Notepad of older versions of Windows 10 and older versions of Windows doesn't support Unix newlines.

I'm also part of a fansub group where we use version control and one member is using Aegisub and another is using SubtitleEdit, and when SubtitleEdit edits the Aegisub file, the commit's diff ends up as the whole file because SubtitleEdit converts the DOS newlines to Unix newlines.

Ideally, SubtitleEdit would use whatever newline format the file is already in and default to the platform's tradition for new files, that way no harm is ever done.

**Comment by niksedk** [comment]
Subtitle formats are different... some requires/uses specific line break - others just uses the default platform line break character(s).

Also, most diff programs can ignore white space.
