### ISSUE TITLE
SubtitleEdit.exe CLI unexpected exit 1

### ISSUE THREAD

**Issue by Rouzax** [SubtitleEdit/subtitleedit#8029]
First of all, thank you for this great program :)
I know this is going to be an issue which you can't resolve, but I'm trying to understand how I can best troubleshoot this.
Running SubtitleEdit 4.0.3 NEXT beta 291
https://github.com/SubtitleEdit/subtitleedit/commit/62b433a

I'm calling SubtitleEdit through a script which has been working for many years flawlessly, but since recently sometimes (cannot pinpoint how or why) SubtitleEdit.exe will exit with an Error 1 code. When running the script again on the same files, it will complete successful.

I call SubtitleEdit through PowerShell with this portion of code

```powershell
    $StartInfo = New-Object System.Diagnostics.ProcessStartInfo
    $StartInfo.FileName = $SubtitleEditPath
    $StartInfo.RedirectStandardError = $true
    $StartInfo.RedirectStandardOutput = $true
    $StartInfo.UseShellExecute = $false
    $StartInfo.Arguments = @('/convert', "$Files", 'subrip', "/inputfolder`:`"$Source`"", '/overwrite', '/MergeSameTexts', '/fixcommonerrors', '/removetextforhi', '/fixcommonerrors', '/fixcommonerrors')
    $Process = New-Object System.Diagnostics.Process
    $Process.StartInfo = $StartInfo
    $Process.Start() | Out-Null
    $stdout = $Process.StandardOutput.ReadToEnd()
    $stderr = $Process.StandardError.ReadToEnd()
    $Process.WaitForExit()

    # Regular expressions to extract information
    $versionRegex = "Subtitle Edit (\d+\.\d+\.\d+)"
    $filesConvertedRegex = "(\d+) file\(s\) converted"
    $timeTakenRegex = "(\d+:\d+:\d+\.\d+)"

    # Extract information using regular expressions
    $matchResult = $stdout -match $versionRegex
    if ($matchResult) {
        $version = $matches[1]
    }

    $matchResult = $stdout -match $filesConvertedRegex
    if ($matchResult) {
        $filesConverted = $matches[1]
    }

    $matchResult = $stdout -match $timeTakenRegex
    if ($matchResult) {
        $timeTaken = $matches[1]
        # Convert the string to a TimeSpan object
        $timeSpan = [TimeSpan]::Parse($timeTaken)
        # Format the TimeSpan object as a string in a user-friendly way
        $userFriendlyTime = $timeSpan.ToString("hh\:mm\:ss")
    }

    switch ($process.ExitCode) {
        0 {
            Write-HTMLLog -Column1 'SubtitleEdit:' -Column2 "V $version"
            Write-HTMLLog -Column1 'Subtitles:' -Column2 "$filesConverted Converted"
            Write-HTMLLog -Column1 'Time Taken:' -Column2 $userFriendlyTime
            Write-HTMLLog -Column1 'Result:' -Column2 'Successful' -ColorBg 'Success'
        }
        default {
            Write-HTMLLog -Column1 'Exit Code:' -Column2 $($Process.ExitCode) -ColorBg 'Error'
            Write-HTMLLog -Column1 'Error:' -Column2 $stderr -ColorBg 'Error'
            Write-HTMLLog -Column1 'Result:' -Column2 'Failed' -ColorBg 'Error'
            Stop-Script -ExitReason "SubEdit Error: $DownloadLabel - $DownloadName"
        }
    }
```

If it finishes successful, I will get something like this
![image](https://github.com/SubtitleEdit/subtitleedit/assets/4103090/e95a5f43-fe21-4e58-a919-920e5e8314d2)

When it is unsuccessful, I will get this
![image](https://github.com/SubtitleEdit/subtitleedit/assets/4103090/d8bdcd3e-0c7b-49a6-8791-6396cc6a4a71)

Is there anyway for me to capture or log the actual error of what is happening, so I can debug the issue?

**Comment by niksedk** [comment]
Could you send me the files you're converting?

**Comment by Rouzax** [comment]
> Could you send me the files you're converting?
I don't have any at this moment that came from a failed convert, but next time it happens I'll send them

**Comment by niksedk** [comment]
> > Could you send me the files you're converting?
> 
> I don't have any at this moment that came from a failed convert, but next time it happens I'll send them

OK 👍

**Comment by Rouzax** [comment]
So it happened again, but it was on an entire season of srt files, so I don't know which actual file it was processing while it failed.
Do you want me to upload the files here? Not sure if that is an issue with copyright
![image](https://github.com/SubtitleEdit/subtitleedit/assets/4103090/2aecc11d-5c42-4431-ac99-2c9d3f79a241)

**Comment by niksedk** [comment]
Could you first try latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

Now it will allow the number of subtitles created be different from the number of input files - it only check for any errors now.

**Comment by Rouzax** [comment]
Had it on another season folder happen to me as well, and just kicking of the exact same script on the exact same files results in a success the second time around
![image](https://github.com/SubtitleEdit/subtitleedit/assets/4103090/ea2d4b94-100f-4f18-8692-fbdb9144358f)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/4103090/6d4e31d3-4058-4d57-b630-afa2946004ad)

**Comment by Rouzax** [comment]
> Could you first try latest beta? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip
> 
> Now it will allow the number of subtitles created be different from the number of input files - it only check for any errors now.

I'll update and keep an eye on it.

**Comment by niksedk** [comment]
>Other question, should the error be logged to the $stdout or $stderr in my script?

Actually all is written to stdout... I guess stderr would be better for errors?

**Comment by Rouzax** [comment]
> > Other question, should the error be logged to the $stdout or $stderr in my script?
> 
> Actually all is written to stdout... I guess stderr would be better for errors?

Not sure if one is better than the other one, as long as I know where it is written I can pick it up 😄
I'll edit my script to just dump the stdout when it fails entirely, that might help with debugging.

**Comment by Rouzax** [comment]
The new debugging worked, running it again gave me an error now

```
Subtitle Edit 4.0.3 - Batch converter 1: Boat.Story.S01E01.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB.en.srt -> D:\TEMP\Torrent\PROCD\TV\Boat.Story.S01.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB\Boat.Story.S01E01.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB.en.srt... done. 2: Boat.Story.S01E01.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB.nl.srt -> D:\TEMP\Torrent\PROCD\TV\Boat.Story.S01.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB\Boat.Story.S01E01.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB.nl.srt... done. 3: Boat.Story.S01E02.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB.en.srt -> D:\TEMP\Torrent\PROCD\TV\Boat.Story.S01.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB\Boat.Story.S01E02.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB.en.srt... done. 4: Boat.Story.S01E03.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB.en.srt -> D:\TEMP\Torrent\PROCD\TV\Boat.Story.S01.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB\Boat.Story.S01E03.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB.en.srt... done. 5: Boat.Story.S01E04.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB.en.srt -> D:\TEMP\Torrent\PROCD\TV\Boat.Story.S01.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB\Boat.Story.S01E04.2160p.iP.WEB-DL.AAC2.0.HLG.H.265-playWEB.en.srt... done. ERROR: Index was outside the bounds of the array. at Nikse.SubtitleEdit.Core.Forms.FixCommonErrors.FixStartWithUppercaseLetterAfterColon.Fix(Subtitle subtitle, IFixCallbacks callbacks) at Nikse.SubtitleEdit.Forms.FixCommonErrors.RunSelectedActions() at Nikse.SubtitleEdit.Forms.FixCommonErrors.RunBatch(Subtitle subtitle, SubtitleFormat format, Encoding encoding, String language) at Nikse.SubtitleEdit.Logic.CommandLineConvert.CommandLineConverter.RunActions(TextEncoding targetEncoding, Subtitle sub, SubtitleFormat format, List`1 actions, Boolean autoDetectLanguage) at Nikse.SubtitleEdit.Logic.CommandLineConvert.CommandLineConverter.BatchConvertSave(String targetFormat, TimeSpan offset, String deleteContains, TextEncoding targetEncoding, String outputFolder, String targetFileName, Int32 count, Int32& converted, Int32& errors, List`1 formats, String fileName, Subtitle sub, SubtitleFormat format, IList`1 binaryParagraphs, Boolean overwrite, Int32 pacCodePage, Nullable`1 targetFrameRate, ICollection`1 multipleReplaceImportFiles, List`1 actions, Nullable`1 resolution, Boolean autoDetectLanguage, BatchConvertProgress progressCallback, String ebuHeaderFile, String assaStyleFile, String ocrEngine, String preExt, Nullable`1 renumber, Nullable`1 adjustDurationMs, PreprocessingSettings preprocessingSettings, CancellationToken cancellationToken) at Nikse.SubtitleEdit.Logic.CommandLineConvert.CommandLineConverter.Convert(String[] arguments) 5 file(s) converted in 00:00:07.0534204
```

**Comment by Rouzax** [comment]
With beta 299, I can't successfully clean the srt files anymore, it will give this error every time
Have reverted to previous version

**Comment by niksedk** [comment]
Thx - nice catch :)

Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Let me know if you ever see this again!

**Comment by Rouzax** [comment]
> Let me know if you ever see this again!

Thanks, will keep an eye out.
