### ISSUE TITLE
Please make it possible to show Netflix errors!

### ISSUE THREAD

**Issue by HeikeMuc** [SubtitleEdit/subtitleedit#8031]
Netflix has certain rules how subtitles have to be adjusted before and after shot changes. I found the Netflix Quality Check at SE and would love it so much if I could see errors in the waveform so that the region around the shot change would turn green if everything is okay and red if not.

**Comment by SuperiorAlpaca** [comment]
Agreed. It would be even better if we could just apply all Netflix fixes, just like in Fox common errors window.
