### ISSUE TITLE
updating to latest beta seems to have broken my whisperx transcribing

### ISSUE THREAD

**Issue by fznx922** [SubtitleEdit/subtitleedit#8035]
Good morning, not sure what has happened but updating to the newest one has stopped my whisper from working as it did in the past, was there a way to reset the engine path? i wanted to try and maybe reset the enviroment and see if that helped, but its quite strange as i used it the other day to generate subs but after drop and dragging the update she stopped also included log snippet 

Date: 03/17/2024 09:02:18
SE: 4.0.3.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: C:\Users\fznx\anaconda3\envs\whisperx\Scripts\whisperx.exe --language ja --model "large-v3" --language ja --chunk_size 6 --batch_size=25 --beam_size=5 --patience=0.5 "C:\Users\fznx\AppData\Local\Temp\8e893d3e-d716-476c-a796-3a6d18d37c9f.wav"

doesnt show any errors but theres no text output, and if i watch task manager it doesnt seem to load into gfx memory once it buffers in ram

any help appreciated 

thank you so much :)

**Comment by darnn** [comment]
If it's any help, one issue I see there is that WhisperX expects the model name "large" rather than "large-v3". Other than that, you can just run the same command line yourself (with a different audio file, naturally, since that one got deleted) and see if it works.

**Comment by fznx922** [comment]
thanks for that, unfortunately redownloading model didn't help at all, it was running with the v3 model previously as set, i did try to run it manually and got this error now 

  File "C:\Users\fznx\anaconda3\envs\whisperx\lib\site-packages\whisperx\asr.py", line 288, in load_model
    model = model or WhisperModel(whisper_arch,
  File "C:\Users\fznx\anaconda3\envs\whisperx\lib\site-packages\faster_whisper\transcribe.py", line 130, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.

but nothing on that side of things has changed to my knowledge, and its running through conda so im not sure why my enviroment would suddently change 

any ideas? :) thanks so much

**Comment by fznx922** [comment]
so a bit of an update, it runs as normal now, theres no errors on the log file, the gpu shows all the right activity im used to but still when it finishes it just has an empty srt file, tried many reinstalls, older version etc, any ideas? thanks :)

**Comment by fznx922** [comment]
Date: 03/22/2024 18:08:15
SE: 4.0.2.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: Calling whisper (WhisperX) with : C:\Users\fznx\anaconda3\envs\whisperx\Scripts\whisperx.exe --language ja --model "large-v2" --task translate --language ja --chunk_size 6 --batch_size=25 --beam_size=5 --patience=0.5 "C:\Users\fznx\AppData\Local\Temp\a1888823-e69d-4b8a-9d8c-95dda95a5d50.wav"
torchaudio.set_audio_backend("soundfile")

C:\Users\fznx\anaconda3\envs\whisperx\lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.2.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\fznx\.cache\torch\whisperx-vad-segmentation.bin`
>>Performing transcription...

Model was trained with torch 1.10.0+cu102, yours is 2.2.1. Bad things might happen unless you revert torch to 1.x.

Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Calling whisper WhisperX done in 00:01:44.3530154
Loading result from STDOUT

**Comment by niksedk** [comment]
I'm removing WhisperX... following the instructions on their github page is not enough to install... so way to much hassle and we have Purfview faster whisper + Whisper CPP which both work well and are easy to install.

**Comment by fznx922** [comment]
thats unfortunate to hear, to be honest, its been the best engine via subtitle edit. gives a solid output and super speedy  and better alligned subtitles vs purfview/ whisper cpp, ran the others and always felt disappointed

**Comment by darnn** [comment]
You could always keep a portable older version of SE just for WhisperX and update it manually.

**Comment by niksedk** [comment]
Sorry, I can no longer successfully install WhisperX (wasted several hours) with their installations instructions - if they fix it, I can re-add it.
(If I cannot install, then I cannot test it and see model names etc., and probably many will have problems installing it too)
