### ISSUE TITLE
U.S. OCR gives music symbol

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8036]
<img width="554" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/8692856/14bc79cf-4351-4726-8d28-a3520ca690bb">
[rs.zip](https://github.com/SubtitleEdit/subtitleedit/files/14626384/rs.zip)

**Comment by niksedk** [comment]
What OCR method are you using? Tesseract?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/028a4c9c-63e7-4ab7-a8e7-6a53b91a9a0c)

**Comment by fraternl** [comment]
Yes, Tesseract 5.0
