### ISSUE TITLE
Issue with "Redock-Undock video controls"

### ISSUE THREAD

**Issue by flandriai** [SubtitleEdit/subtitleedit#8038]
I cannot find the possibility to permanently undock and then **hide** the video controls anymore. It is possible to dock or undock the video and waveform panels but, if I choose to undock them, then every time I start the program I have to click on the small "X" in each separate window to close them all. Formerly it was possible to hide these controls permanently. It would be great if this option could reappear again.

**Comment by LeonCheung** [comment]
Try turning off this checkbox before undocking:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/a7cd125d-e7c4-40bf-9194-04ed66ea0ab0)

**Comment by flandriai** [comment]
I don't know if it's a bug, or this feature was removed on purpose.
