### ISSUE TITLE
problem with the latest version

### ISSUE THREAD

**Issue by nielka98** [SubtitleEdit/subtitleedit#8042]
Hey when I try to install Faster-Whisper from  Purfview this message pops up: "whisper sha -512 hash does not match" 
how to fix it and what causes this error?

**Comment by niksedk** [comment]
Sorry, I cannot re-create this.
What SE version are you using?

**Comment by nielka98** [comment]
Today I updated to the latest version

**Comment by Purfview** [comment]
> "whisper sha -512 hash does not match"

Can't reproduce it too, when do you get it?
Why it's "whisper" not "Faster-Whisper"? 

There is another report -> https://github.com/SubtitleEdit/subtitleedit/discussions/8046

**Comment by Purfview** [comment]
Maybe it's something with your antivirus.
Here you can download it directly: https://github.com/Purfview/whisper-standalone-win/releases

**Comment by niksedk** [comment]
I also think this is an anti-virus issue

**Comment by Valirius** [comment]
> Maybe it's something with your antivirus. Here you can download it directly: https://github.com/Purfview/whisper-standalone-win/releases

and then what to do? 
Where should I put it? 
I unpacked it at "AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster", but the subtitle doesn't see it, it offers to download anyway.

**Comment by Purfview** [comment]
Make a screenshot of that folder.

**Comment by Valirius** [comment]
> Make a screenshot of that folder.

![Image](https://github.com/user-attachments/assets/456a5560-31bf-43b2-ae7a-168e23c7567d)

**Comment by Purfview** [comment]
You can see that your extracted files are nested somewhere in "Faster-Whisper-XXL_r245.2_windows" folder.
Move the files from there to this folder you have screenshoted.

**Comment by jebacwasXD** [comment]
still no working

**Comment by jebacwasXD** [comment]
w/e guys just use version 4.0.11 
The new one is bugged. Not worth to update if u didnt, then keep it and DONT EVER THINK about updating this to the latest version. Crap as hell. Sitted there for 3 hrs to fix it. Also all things what they say to fix it its BS, putting files in folders, AV, other solutions just dont work. Program is great and god bless sm1 who created it but just stick to the versions from 2k24. GL in fixing boyz
