### ISSUE TITLE
Problems with new IMSC 1.1 text template

### ISSUE THREAD

**Issue by ryzen88** [SubtitleEdit/subtitleedit#8043]
First of all thanks for implementing a IMSC 1.1 TT template 
Unfortunately IMF tool, that we use for creating IMF packages gives a wrapping error, probably something regarding the layout that is not correct. 
I added an example of a IMSC TT that works on all software, and that TT converted with your new beta profile. 
Couple of things i noticed that could maybe be the issue.
- The amount of things in the <TT header is like is really crazy lots.
- The fact that you only specify the region and not the style in line.
Anyway i hope that especially the example could give clarity, If i can assist in any other way feel free to ask.
Thanks again!

![Screenshot (142)](https://github.com/SubtitleEdit/subtitleedit/assets/111976708/a8681440-4c2b-447b-a2d3-154a7da02720)
![Screenshot (143)](https://github.com/SubtitleEdit/subtitleedit/assets/111976708/d7640e66-4873-4c36-8125-1747c9259dde)

**Comment by niksedk** [comment]
Could you add your working file as an attached .zip file?

The tool you're using, is that: https://github.com/IMFTool/IMFTool ?
How can I test this import/wrapping ?

**Comment by ryzen88** [comment]
Certainly, thanks for taking the time. I have put 2 examples of IMSC subtitles, they do differ a bit but these are both layouts that work very well with all other software. Now the resolve version lacks italics but that has more to do that resolve has some strange quirk of not doing italics and has nothing to do with the IMSC, but i thought it was helpful for including it nonetheless.

Yes, the IMF tool, partly build for netflix who was really the driver of the IMF standard, now a lot of the large studio's also switched to IMF.
When you have the IMF tool, you first have to open an existing package, or create a new one. quickest way is to just make a new one in a empty folder
When you have done that you can add asset, choose wrapped time text essence. In the window that pops open you can browse for the xml or ttml and select it.
Then you see the subtitle file on the left, normally you would build the entire package with lots of audio, video, subs and package it with al the metadata, for specific territories and stuff.
With the subtitle imported you can go to the Write IMF Package button in the top toolbar and then it Packages, and that's the point that it also errors out, and where the other examples have no problems.
I also noticed that the beta IMSC file is also unable to import in davinci resolve who is also a real pain in the ass and it only works if its according to the very narrow specs.


[IMSC1.zip](https://github.com/SubtitleEdit/subtitleedit/files/14654357/IMSC1.zip)

**Comment by niksedk** [comment]
OK, I've tried to improve the IMSC 1.1 compability here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

It still needs some better positioning support + better frame rate support, but does it work for you now?

**Comment by ryzen88** [comment]
Yes, it seems to work like a charm. Awesome. 
I tried to convert from different sources and seems to work every time. 

What also is great when you select the framerate in property's for the document the choices are like 24.0 25.0 result in 24 and 25. Previously if i tried to preserve a IMSC layout when only needing to adjust timing i always had to make sure i just typed in 24 because the dropdown menu would result in 24.0 in the document and would make it invalid. But with the new IMSC it already works perfectly

I do have one more very strange edge case, Its when exporting a multi region IMSC from davinci resolve, it makes a strange layout that i'm not really sure if that is according to the rules, but a lot of other software seems to have issues with it. 
Subtitle Edit also does not properly understand the document structure.
But most playback software seems to handle it fine, I have added it in a zip. Its a weird duck because i have not seen any other software do it like this but it's an interesting case nonetheless.

It separates all the lines by region, So you have region 1 all the lines from start to finish, then region two all its lines. But when importing such a document it just reads it as tangled mess of timecodes.

I will continue some more testing to look for edge cases and weird stuff but it feels very solid.
And it also looks very clean, i appreciate that in a subtitle doc.

[Resolve multi region export.zip](https://github.com/SubtitleEdit/subtitleedit/files/14691555/Resolve.multi.region.export.zip)

**Comment by ryzen88** [comment]
Hey, i was testing out the new beta, and seems it works like a charm. Only thing i noticed, and had this with all the previous versions as well. The first time you go into IMSC properties and change the XML to TTML it give an error, and you have to close the software. After that initial error it works without any issue. I had the same thing on 3 different machines all the first time i ran the software.
![subtitle edit error](https://github.com/SubtitleEdit/subtitleedit/assets/111976708/4b55916e-2950-47ff-b9d7-59c69a78a5b1)

**Comment by niksedk** [comment]
Thx :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip
