### ISSUE TITLE
Serbian subtitle ruined

### ISSUE THREAD

**Issue by cvrle77** [SubtitleEdit/subtitleedit#8044]
About Purfview's Faster-Whisper voice-to-text, new one, it seems that Russian (or Ukrainian) is in place of Serbian. Previously, Serbian was in latin, now it's in cyrilic, mix of Serbian and Russian letters, and transcription is horrible, it just resembles what has been said. So, something that worked flawlessly is now a complete goner.
Not sure how to return to previous version, without messing with OCR word list and multireplace...

It would be nice if there's a downgrade button. Right now, I am stuck with nothing, unusable tool.

**Comment by cvrle77** [comment]
If I go with v4.03 with large model v3 it's good (always using large model, it's the best).
If I update to v4.04 without updating Whisper and model v3, it's giving me letter for letter same audio to text output.
Only when I update PFW, it creates this nonsense...
Here is before PFW update:
![Subtitle edit before](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/79511840-5209-4e05-8959-780592c86aa4)

Here is after
![Subtitle edit after](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/234ec1e4-0b19-42bb-8f4f-63e25fe3b8f3)

I don't know which language is that, maybe Bulgarian? Belarussian? Not sure who else is using cyrilic.
It made no difference if I removed all models and redownloaded large v3.
If I were to restore only whisper.exe to previous version from my backup, everything is back and working again, except for the fact that SE is asking me to update PFW. 

That could be changed, remove popup dialogue, and integrate Update button (which could double down as 'Restore previous version') for Whisper - something like this:
![Subtitle edit button](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/ad4fecbd-1e17-4026-99f0-6c0ef3165a0d)

Going back without backup is mission impossible.

**Comment by Purfview** [comment]
> ...it seems that Russian (or Ukrainian) is in place of Serbian
> I don't know which language is that, maybe Bulgarian? Belarussian? Not sure who else is using cyrilic.

But... Cyrillic is official alphabet of Serbia.

> and transcription is horrible, it just resembles what has been said

Are you sure?

**Comment by cvrle77** [comment]
> But... Cyrillic is official alphabet of Serbia.
> 
1. It is not Serbian cyrilic, it's Russian alphabet. ю and ы are Russian letters, and can be seen in transcription images.
2. We use both cyrilic and latin equally, and learn them in school equally. Official only means government is obliged to use cyrilic as primary, but they use latin too, as secondary. What that has to do with the software and the sudden switch from latin to cyrilic without a single option to switch and use what I want to use?
> Are you sure?
>
When I transcribe Serbian audio and get Russian alphabet as output, it can only resemble Serbian language, it cannot be Serbian. There's some grammar errors that can be found in cyrilic version, but not in latin version, and some other mistakes and differences in transcription. Sure, latin version isn't perfect, but I got used to glitches and adopted to them the best way I could.

**Comment by Purfview** [comment]
> What that has to do with the software and the sudden switch from latin to cyrilic...

Latest version is using new custom prompt, which is cyrilic for Serbian.
You can use `-prompt=default` for previous version behaviour, or disable it with `-prompt=None`.

**Comment by Purfview** [comment]
> There's also this difference between 4.03 and 4.04, nothing to do with Whisper, it's the same one from 4.03 without update, just an 'addon' of empty lines.

Looks like you've enabled `post-process` in SE. Disable it!

**Comment by cvrle77** [comment]
> > What that has to do with the software and the sudden switch from latin to cyrilic...
> 
> Latest version is using new custom prompt, which is cyrilic for Serbian. You can use `-prompt=default` for previous version behaviour, or disable it with `-prompt=None`.

Nice, I did not know that, however, that is not Serbian cyrilic, it is Russian cyrilic, as I said. ю and ы are Russian letters and cannot be found in Serbian language and grammar.

**Comment by cvrle77** [comment]
> > There's also this difference between 4.03 and 4.04, nothing to do with Whisper, it's the same one from 4.03 without update, just an 'addon' of empty lines.
> 
> Looks like you've enabled "post-processing" in SE. Disable it!

When I disable it, I get HUGE lines of text, unbroken, one after the other, and I need to manually break them. 
Majority of lines go red.

**Comment by Purfview** [comment]
> just an 'addon' of empty lines

Looks like some BUG with "post-processing", share the original srt for @niksedk [not srt made by SE]

> When I disable it, I get HUGE lines of text, unbroken

That was maybe before, now it's impossible because there is `--standard` option by default in SE.

**Comment by cvrle77** [comment]
> > just an 'addon' of empty lines
> 
> Looks like some BUG with "post-processing", share the original srt for @niksedk [not srt made by SE]

What do you mean 'not srt made by SE', there is no other srt because I create srt using audio to text with whisper.

> That was maybe before, now it's impossible because there is `--standard` option by default in SE.

Well, standard only really breaks it by character number, as far as I can see. And it moves a single word in a new line. It makes no grammatical sense, it should at least try to use last comma as a separator to move all words after it in a new line, or something else, not just number of characters. Same thing happens with line break in a single field.
![line break](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/69257302-147a-4918-ab15-d311b65f3a92)

**Comment by Purfview** [comment]
> What do you mean 'not srt made by SE', there is no other srt because I create srt using audio to text with whisper.

First srt is made by whisper, then that srt is opened by SE.

> Well, standard only really breaks it by character number...

It does what it's meant to do - max 42 chars and max 2 lines, nothing more nothing less.

**Comment by niksedk** [comment]
> @niksedk Original issue is solved. New issue is that "post-processing" is creating some empty lines. Could be related to breaks in input srt.

Cool, how was the original issue solved?
I have also seen Danish audio giving weird languages with tiny model.

How can I re-create the empty lines from SE post-processing?

**Comment by niksedk** [comment]
@Purfview: thx :)
I see some issues now....

**Comment by cvrle77** [comment]
> > @niksedk Original issue is solved. New issue is that "post-processing" is creating some empty lines. Could be related to breaks in input srt.
> 
> Cool, how was the original issue solved? I have also seen Danish audio giving weird languages with tiny model.
> 
> How can I re-create the empty lines from SE post-processing?

It's not solved, it's just masked with a switch `-prompt=None` Russian cyrilic instead of Serbian cyrilic is still present, and latin Serbian and fake cyrilic Serbian subtitles do not match word for word. It's not just going from one alphabet to another.

Here's the audio.
[Untitled.zip](https://github.com/SubtitleEdit/subtitleedit/files/14670094/Untitled.zip)

To recreate empty lines, follow the image: 
![11](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/1fc15094-9d2f-4203-98ad-681aea5bf11b)

**Comment by Purfview** [comment]
>It's not solved, it's just masked with a switch -prompt=None Russian cyrilic instead of Serbian cyrilic is still present, and latin Serbian and fake cyrilic Serbian subtitles do not match word for word. It's not just going from one alphabet to another.

This is not SE's nor Faster-Whisper issue.
Models are made by OpenAI.

**Comment by cvrle77** [comment]
Oh, ok, Weird that you haven't pointed that in your first reply. I thought it's a switch inside SE to go from cyrilic to latin and vice versa, because it's the only thing that makes sense.

Regarding empty lines, it seems that they pop up in both 03 and 04 versions with newest PFW and post-processing/split long lines. In both 4.03 and 4.04 with older version and no switches, split long lines doesn't cause empty lines.
But if I put switches `--standard -prompt=None` in both new and old PFW, with `split long lines`, I get empty rows. :/

**Comment by Purfview** [comment]
> Oh, ok, Weird that you haven't pointed that in your first reply.

Your original issue was more about latin vs cyrillic.

**Comment by niksedk** [comment]
Post-processing should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by Purfview** [comment]
Looks good now.
