### ISSUE TITLE
All subtitles appear as boxed in video player

### ISSUE THREAD

**Issue by BlueMeow7** [SubtitleEdit/subtitleedit#8045]
This is very frustrating as it's a lot harder to see which subtitles are truly boxed and which just appear to be in the video player. I have not chosen the "opaque box" option in "Video player" settings, so I have no idea how to get rid of this. Please, fix it - the problem arose after updating to the latest version.

**Comment by niksedk** [comment]
Could you explain a bit more?
Could you supply a screenshot?

**Comment by BlueMeow7** [comment]
![Posnetek zaslona 2024-03-19 131559](https://github.com/SubtitleEdit/subtitleedit/assets/163998514/0e9b8cb5-cbb3-4340-95b9-fb132aa8816c)

(there is no box command in the subtitles, the file was saved in EBU STL with "Use box around text" unticked, video player is set to show outline of the letters, not an opaque box)

**Comment by niksedk** [comment]
Could be your default settings for video player preview?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/4316e238-f996-4750-95a8-b271b4212333)

**Comment by BlueMeow7** [comment]
Hello, I have attached a test subtitle file - all subtitles look like
they're boxed in video player on my end. As stated in my original post, I
have not chosen the "opaque box" option in "Video player" settings. The
"Outline" option is selected.

Thank you for helping out,
Nataša

V V tor., 19. mar. 2024 ob 17:46 je oseba Nikolaj Olsson <
***@***.***> napisala:

**Comment by niksedk** [comment]
@BlueMeow7: Could you attach the file here on Github (email attachments are not automatically attached on Github)

**Comment by BlueMeow7** [comment]
I cannot attach a .stl file here.

**Comment by niksedk** [comment]
Github supports .zip files

**Comment by BlueMeow7** [comment]
Oh cool, didn't know that. :)
[testing.zip](https://github.com/SubtitleEdit/subtitleedit/files/14664533/testing.zip)

**Comment by niksedk** [comment]
OK, thx for the file :)

I see what you mean I hope... and now SE beta should have improved box preview: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

Let me know how it works for you.
