### ISSUE TITLE
MPV Lib Problem - Can't open video

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#8049]
I updated the mpv lib, but whenever I've tried to open a video, this pops up!
What can I do to solve this?
Thank you!

![Área de Transferência01vc](https://github.com/SubtitleEdit/subtitleedit/assets/64425752/aee2fdfc-ae14-4605-9cf5-1ce7cd563d06)

**Comment by niksedk** [comment]
What OS are you using?

**Comment by Andrebavila** [comment]
> What OS are you using?

Windows 7

**Comment by niksedk** [comment]
OK, it's possible mpv no longer supports Windows 7 - try downloading an older mpv:
https://github.com/SubtitleEdit/support-files/tree/master/mpv 

It's seems like supporting Windows 7 is really hard now :(

**Comment by Andrebavila** [comment]
> OK, it's possible mpv no longer supports Windows 7 - try downloading an older mpv: https://github.com/SubtitleEdit/support-files/tree/master/mpv
> 
> It's seems like supporting Windows 7 is really hard now :(

Thank you very much, @niksedk! It solved the problem!
I think it's time to change OS. I didn't want it, but I don't see a way out.
Other things is driving me crazy as well because OS is outdated!
