### ISSUE TITLE
OCR replace (in French) wants to decapitalize the L' in an all Capital word (sentence even)

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8052]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/8692856/37ec0bef-9c7d-4e80-a64e-854ae50bbe19)

**Comment by niksedk** [comment]
Could you attach the text?
Have you tested on a clean portable version of SE?

**Comment by ivandrofly** [comment]
Looks like Hard-Coded rules issue from OrcFixEngine.

I will take a look

**Comment by niksedk** [comment]
> Looks like Hard-Coded rules issue from OrcFixEngine.
> 
> I will take a look

Could also be a local corrupted file...
