### ISSUE TITLE
Remove Hearing Impaired - Interjections - French - Empty

### ISSUE THREAD

**Issue by Zodler** [SubtitleEdit/subtitleedit#8053]
Remove Interjections for French is an empty list. This was not the case in previous versions.

**Comment by Zodler** [comment]
Oh ok, thank you. That explains it. I checked the other languages and they are empty too.

**Comment by niksedk** [comment]
Would this be an okay French interjections list?

```xml
<interjections>
  <word>Aïe</word>
  <word>Ouïe</word>
  <word>Ouille</word>
  <word>Ouf</word>
  <word>Oups</word>
  <word>Ho</word>
  <word>Hé</word>
  <word>Hein</word>
  <word>Zut</word>
</interjections>

```

**Comment by Zodler** [comment]
French is not my native language so I leave this for others to say.

But I think Ah should be there! (maybe!) I have seen a lot of Ah! :)

**Comment by niksedk** [comment]
I am not sure what to do about "ah bon"...

If any native French people can help improve this please do so :)

**Comment by Codling** [comment]
"Ah bon ?" isn't relevant, it means "Really?".
"Aïe", "ouïe", "hein", "zut" neither BTW.
"Hé" may be useful sometimes.

Here is an non exhaustive list of French interjections you can add:
Ah
Chut
Euh
Han-han
Hum
Hum-hum
Oh
Oh-oh
Ouh
Whoa
Wouah
Wow

**Comment by Zodler** [comment]
And Eh, I saw Eh yesterday!

**Comment by niksedk** [comment]
@Codling: So...  `Aïe`, `ouïe`, `hein`, `zut` should be removed from this list?

```xml
<interjections>
  <word>Ah</word>
  <word>Aïe</word>
  <word>Chut</word>
  <word>Eh</word>
  <word>Euh</word>
  <word>Han-han</word>
  <word>Hein</word>
  <word>Ho</word>
  <word>Hum-hum</word>
  <word>Hum</word>
  <word>Hé</word>
  <word>Oh-oh</word>
  <word>Oh</word>
  <word>Ouf</word>
  <word>Ouh</word>
  <word>Ouille</word>
  <word>Oups</word>
  <word>Ouïe</word>
  <word>Whoa</word>
  <word>Wouah</word>
  <word>Wow</word>
  <word>Zut</word>
  <skipIfStartsWith>
    <text>Ah bon</text>
  </skipIfStartsWith>
</interjections>
```

**Comment by Codling** [comment]
Yes, @niksedk
You can remove them, as "Ah bon". :)

**Comment by niksedk** [comment]
@Codling: thx :)

Should "Ah bon" be kept and "Ah" removed?
Like this?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/aaa5ba2a-6627-4505-9870-db58c46c60a7)

New interjection list:

```xml
<interjections>
  <word>Ah</word>
  <word>Chut</word>
  <word>Eh</word>
  <word>Euh</word>
  <word>Han-han</word>
  <word>Ho</word>
  <word>Hum-hum</word>
  <word>Hum</word>
  <word>Hé</word>
  <word>Oh-oh</word>
  <word>Oh</word>
  <word>Ouf</word>
  <word>Ouh</word>
  <word>Ouille</word>
  <word>Oups</word>
  <word>Whoa</word>
  <word>Wouah</word>
  <word>Wow</word>
  <skipIfStartsWith>
    <text>Ah bon</text>
  </skipIfStartsWith>
</interjections>

```

**Comment by Codling** [comment]
Yes, absolutely. :)

**Comment by Zodler** [comment]
Is the meaning of "Ah bon" different than "bon"? I always considered them the same and was not bothered if "Ah bon" was changed to "bon"!

**Comment by naifs2015** [comment]
Aaaahh
Aaah
Aah
Ah
Aha
A-ha
Ahem
Ahh
Ahhh
Ahhhh
Argh
Augh
Aw
Aww
Awww
Badum tish
Ba-dum-tss
Bah
Bahaha
Blech
Bleh
Boo
Booh
Boohoo
Boo-hoo
Brr
Brrrr
Bwahaha
Doh
D'oh
Duh
Eeeek
Eek
Eep
Eh
Ehh
Ehhh
Erm
Err
Eww
Ewww
Eyh
Fuff
Gah
Gee
Grr
Grrrr
Hah
Haha
Hahaha
Harumph
Heh
Hehe
Hm
Hmm
Hmmm
Hmmmm
Hooray
Huh
Humph
Hurrah
Hush
Huzzah
Ich
Ick
Jeez
La-dee-dah
La-di-da
Meh
Mhm
Mm
Mmh
Mmhm
Mmm
Mmmm
Muahaha
Mwah
M-wah
Mwahaha
Nah
Nuh-hu
Nuh-uh
Nu-huh
Oh
Ohh
Ohhh
Oh-lala
Oh-oh
Oi
Ooh
Ooh-la-la
Oomph
Oooh
Oops
Ouch
Ow
Oww
Owww
Oy
Oy vay
Oyh
Pee-yew
Pew
Pff
Pffh
Pfft
Phew
Pssh
Psst
Sheesh
Shh
Shoo
Shush
Tsk-tsk
Tut-tut
Ugh
Ughh
Uh
Uhh
Uhhh
Uh-hu
Uh-huh
Uhm
Uh-oh
Uh-uh
Umm
Ummm
Umph
Unh-uh
Unh-unh
Waaaaah
Waah
Wee
Weee
Whee
Whew
Whoa
Woohoo
Wow
Yahoo
Yak
Yay
Yeah
Yech
Yeeeeaah
Yeehaw
Yee-haw
Yeow
Yikes
Yippee
Yoohoo
Yoo-hoo
Yuck
Yuh-hu
Yuh-uh
Yu-huh
Zing
