### ISSUE TITLE
Incorrect language code when saving auto-translated subtitles.

### ISSUE THREAD

**Issue by vaclavmuller** [SubtitleEdit/subtitleedit#8054]
I often use Subtitle Edit this way:
I convert the video file in its original English language to subtitles using Audio to text (Whisper). Then I automatically translate these subtitles into Czech. (Google Translate V1 API)
Translated subtitles have the correct suffix (cs) in the Title bar.
However, it often happens that when the save dialog is called, the code is "pl" instead of "cs".
![1](https://github.com/SubtitleEdit/subtitleedit/assets/23431375/dbf6da4a-cb33-457f-9ae4-6f4576a24828)
![2](https://github.com/SubtitleEdit/subtitleedit/assets/23431375/2d59093e-82be-47fb-b1ab-8f36c18bb800)

**Comment by niksedk** [comment]
Could you attach a subtitle or two that gives "pl" instead of "cs" ?

**Comment by vaclavmuller** [comment]
Here are a few of these subtitles - original English + translation into Czech with the wrong language code.
[srt files.zip](https://github.com/SubtitleEdit/subtitleedit/files/14729037/srt.files.zip)

**Comment by niksedk** [comment]
Thx for the files - hopefully better in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by vaclavmuller** [comment]
[srt files 2.zip](https://github.com/SubtitleEdit/subtitleedit/files/14735930/srt.files.2.zip)
Thank you very much.
I am sending one more file, this time from the new beta version wrongly detected as Slovak.
By the way, twice in this version it happened to me that the program crashed when I clicked to save the translated subtitles.
