### ISSUE TITLE
Add OCR method "OCR via Google Cloud Vision API" for batch conversion

### ISSUE THREAD

**Issue by Wernouxe** [SubtitleEdit/subtitleedit#8057]
At present, it's only possible to use "**Tesseract**" and "**nOCR**", so I suggest adding the OCR method with the **Google Vision API**.

![SubtitleEdit_Nggyu-1869d4f2-3a72-4981-9d21-8d172010201d](https://github.com/SubtitleEdit/subtitleedit/assets/143150091/98175440-fec1-4a1a-b100-098066900dbf)

*I'm talking about this method*
![SubtitleEdit_Nggyu-dad2d73f-3313-4dcc-af89-8b4b37590029](https://github.com/SubtitleEdit/subtitleedit/assets/143150091/27ca70d2-9e51-4588-8937-2b3a95a67050)

**Comment by Krautmaster** [comment]
yeah + commandline

**Comment by niksedk** [comment]
Sorry, I will not add any pay stuff in batch/command-line.... it will just too much support hassle.

**Comment by Krautmaster** [comment]
Öhm? Why. If someone's enters a API key and uses the batch, why would it do any hassle? It's the user who does multiple steps to do so?

**Comment by jordancurve** [comment]
+1 I would also like to batch convert a bunch of dvd/idx subtitles using the Cloud Vision API.
