### ISSUE TITLE
Q: Open app with video as argument?

### ISSUE THREAD

**Issue by noembryo** [SubtitleEdit/subtitleedit#8064]
This is not an issue, just a question for your wonderful application.

I have associated the `.srt` files plus some video types (`.mp4`, `.mkv`, `.avi`,..) to open with `Subtitle Edit` using the command `"APP_PATH" "%1"`.  
And although the `.srt` file opens in the app normally, the video files open the app but are not loaded.
Instead I see a "No subtitles found" error dialog.

I use this all the time, when I want to create subtitles from scratch for a video that has none.
So, the question is:
Is there a command that will open the app _and_ load a video file (without subtitles) at once?

TIA 🙏

**Comment by niksedk** [comment]
I think you can add something like `/video:<video_file_name>`, e.g. `SubtitleEdit.exe a.srt /video:myvideo.mkv`

Note that SE will auto-open video files that matches the subtitle file name, e.g. when opening `a.srt` then SE will look for a video file like `a.mkv`.

**Comment by noembryo** [comment]
What I was referring to, was to open the app using only a video file as argument, with no subtitle file involved..

But your suggestion works perfectly! 🥳 🎆 🍾 
The argument I used was `"APP_PATH" /video:"%1"`

Thank you! 👍
