### ISSUE TITLE
A Fix Error Issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8068]
If there's any line ending with a colon or a semicolon, an error occurs when using **Start after uppercase letter after colon/semicolon**:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/9ccdc7b6-fe83-4270-ba45-f6c081e7450c)

**Comment by niksedk** [comment]
Hm, has this already been fixed in latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Ha, indeed. I should keep updating the beta more often. XD  False alarm then, Thanks. closing.

**Comment by niksedk** [comment]
Thx for reporting :)
