### ISSUE TITLE
Add a few "fast" options for Purfview's Faster Whisper

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#8069]
To make it easier/faster for the most useful options for SE:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/6ac2ccc1-e660-444f-a5dc-6e441de0425e)

Any ideas for more button or comments?

@Purfview: input?

**Comment by Purfview** [comment]
Good idea.
There could be some info/help what those options/buttons do, maybe a tooltip when a pointer hovers over button?

`--one_word 2` should be better for SE than `1`.
`--standard_asia` for Japanese/Chinese/Cantonese/Korean output.

**Comment by niksedk** [comment]
@Purfview:
What does `--standard` and `--standard_asia` actually do?

**Comment by Purfview** [comment]
standard:
        sentence = True
        max_line_width = 42
        max_line_count = 2
        max_comma_cent = 70%

    standard_asia:
        sentence = True
        max_line_width = 16
        max_line_count = 2
        max_comma_cent = 80%

**Comment by uckthis** [comment]
Anything to stop hallucinations would be nice too. 
Also, an "ideal" settings. For me, it was --temperature 0.5 --beam_size 10 --best_of 3 --threads 4 --vad_window_size_samples 1024

I only use cuBLAST since its release, so these ideal settings may vary since the new version.

**Comment by Purfview** [comment]
> Anything to stop hallucinations would be nice too.

What hallucinations? Do you use the last version?

> --temperature 0.5 --beam_size 10 --best_of 3 --threads 4 --vad_window_size_samples 1024

That doesn't make much sense... 😆

**Comment by uckthis** [comment]
[Videos.zip](https://github.com/SubtitleEdit/subtitleedit/files/14763820/Videos.zip)
Check out subtitles 33 and 34. The audio is very clean, but it still hallucinates. When the audio is bad, hallucinations are very frequent. This SRT was generated with the latest Beta and Purfview with default settings. 

As far as settings is concerned, I asked an LLM to figure out the best settings for me, and it gave me those. I compared the results and this setting provided better results, and I'm not tech-savvy, so I didn't bother looking into why or how.

**Comment by Purfview** [comment]
> [Videos.zip](https://github.com/SubtitleEdit/subtitleedit/files/14763820/Videos.zip) Check out subtitles 33 and 34. The audio is very clean, but it still hallucinates. When the audio is bad, hallucinations are very frequent. This SRT was generated with the latest Beta and Purfview with default settings.
> 

A bit inaccurate transcription is not a hallucination.
Here it's 33 and 34 from your srt:
```
33
00:02:15,736 --> 00:02:21,716
Since 2023, many of our low-value and
repetitive tasks have been done.

34
00:02:21,800 --> 00:02:25,940
We've also been automated, which makes our
job more efficient and enjoyable.
```

Here is correct transcription with `-m=medium -ct=float32 -bs=1`:
```
  Processing segment at 02:08.360
[02:15.580 --> 02:26.300]  Since 2023, many of our low-value and repetitive tasks have been automated, which makes our job more efficient and enjoyable.
[02:27.000 --> 02:28.900]  So what do I do now?
  Processing segment at 02:21.680
```

Such inaccuracies can happen if word is split by chunk/window border.
Run it directly with `--verbose=true` to see what's actually going on.

You can try `-hst=2`. Or better run Faster-Whisper-XXL and use MDX filter option.



> ...LLM to figure out the best settings...

No wonder. ChatGPT spews nonsense to the complex questions. In this case it's not even answerable.

**Comment by uckthis** [comment]
I used the V3 model. I have utilized all available Whisper modules, both on SE and online, for transcription purposes. However, I noticed that the Faster module exhibits hallucinations. During the transcription of a low-quality, hour-long audio file, the Faster module hallucinated to such an extent that I had to generate a new transcription after just 15 minutes. Consequently, I primarily rely on the cuBLAS module now, as it is remarkably fast. Nevertheless, I continue to test newer releases of other modules and have consistently observed this hallucination phenomenon with the Faster module, which prompted me to share this experience. However, I will experiment with the configuration settings you have suggested. This is precisely why I suggested the 'ideal' settings, so that we can achieve optimal results.

**Comment by Purfview** [comment]
> I have utilized all available Whisper modules, both on SE and online, for transcription purposes.

No idea what that means, Standalone Faster-Whisper is offline...

> However, I noticed that the Faster module exhibits hallucinations.

But you didn't provided any example with an actual hallucination.

**Comment by uckthis** [comment]
If my understanding is correct, a hallucination is when you see something that is not there, and here it generated some text that was not in the audio - it made up stuff AKA a hallucination.

**Comment by Purfview** [comment]
> If my understanding is correct, a hallucination is when you see something that is not there, and here it generated some text that was not in the audio - it made up stuff AKA a hallucination.

No correct.

**Comment by uckthis** [comment]
In that case, let's call it Some Hazy Illusory Text - S.H.I.T for short. No other module that I have used so far does this S.H.I.T.

**Comment by Purfview** [comment]
Every Whisper "module" does it.
Looks like you don't understand how model works and can't evaluate what you are experiencing.

**Comment by uckthis** [comment]
I just redid the file with V3 and --standard (default) and it produced the same S.H.I.T. Earlier I did this video with cuBLAS module and Const-Me to check, and they didn't halluci-- sorry, I mean produce S.H.I.T. Maybe it's something on my machine as no one else has reported it. 
Anyway, thanks for being prompt with your responses. I don't miss going on 4chan.

**Comment by Purfview** [comment]
Don't bother, it's futile for you as you don't understand what you are doing.

**Comment by rRobis** [comment]
I know this is a little bit off-topic, but is it possible to implement/expose this option in Faster Whisper?

`parser.add_argument("--max_words_per_line", type=optional_int, default=None, help="(requires --word_timestamps True, no effect with --max_line_width) the maximum number of words in a segment")`

**Comment by Purfview** [comment]
> --max_words_per_line

I fail to see what is the point of such option, sounds useless...
Could you describe its use case?

**Comment by rRobis** [comment]
> > --max_words_per_line
> 
> I fail to see what is the point of such option, sounds useless... Could you describe its use case?

I wanted to experiment with it, i'm not sure yet how it would work in practice.

But i imagined that it could be useful in situations where you want a certain amount of words per line.  But now, when i think, i guess it would be problematic, because words are different length and it would probably have to break. 🤔

**Comment by rRobis** [comment]
@niksedk **On topic:** there could be a button that allows to save your own presets with name and pick them from a pop-up list.

**Comment by Purfview** [comment]
>in situations where you want a certain amount of words per line.

I can't imagine such situation.

>i guess it would be problematic, because words are different length

Exactly!
