### ISSUE TITLE
Change the Audio Track

### ISSUE THREAD

**Issue by Zodler** [SubtitleEdit/subtitleedit#8072]
How on earth we change the audio track in this new version? I don't see it in the menu anymore!

**Comment by niksedk** [comment]
If you use `mpv` as video player (see Options - Settings - Video player), then you should be able to use the `Video toolbar menu`:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/9b2f1fd8-4579-4789-887d-24594b5813dc)

**Comment by Zodler** [comment]
Oh sorry. I did a clean install and forgot to install mpv. It was DirectShow.
