### ISSUE TITLE
change "embed" before .mkv of exported file and remove old video

### ISSUE THREAD

**Issue by liam1900** [SubtitleEdit/subtitleedit#8074]
hi guys. 
1-i want save video with edited sub.there is an option as embed video.but it adds embed before .mkv of file.i want edit this text.for example i want add Softsub instead of embed.(the embed word  must be editable.)
so this original file be saved as filename-softsub.mkv
2-there be an option to automatically remove original video after exporting the video in same directory.because we do it manually now
3-in 
![Capture](https://github.com/SubtitleEdit/subtitleedit/assets/107861779/99ad274a-55c4-46ac-bcf7-dcf79184fa12)
in the filed that a highlighted. we must be able to add desired values  too like our website name.cause thats shown in player menu and mkvtoolnix

**Comment by liam1900** [comment]
i edited based on my need but i dont know how create working and functional exe and install it.
i tried Advanced installer but not working

**Comment by liam1900** [comment]
> i edited based on my need but i dont know how create working and functional exe and install it. i tried Advanced installer but not working

https://drive.google.com/file/d/17tSdyhpaBkDVeqj-NJLodfMjhj5QAwwW/view?usp=sharing

**Comment by liam1900** [comment]
i solved the problem and works fne
i want this features to automatically delete original file after creation of new movie

**Comment by liam1900** [comment]
i edited and added above feature
to generate and delete automatically.
shall i send source code for you for future updates?here?

**Comment by niksedk** [comment]
Sure, send the code file to my email or add a .zip file here.

**Comment by liam1900** [comment]
[Forms.zip](https://github.com/SubtitleEdit/subtitleedit/files/14783029/Forms.zip)
just replace this form folder
i also edited that file which had .embed  and rename stuff based on my needs
line 453 i think.
GenerateVideoWithSoftSubs.cs
so thats it.

**Comment by niksedk** [comment]
OK, I've updated the latest beta with "embed/softsub" updates: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

Language/title setting window updated:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/3c7260b9-5eeb-4437-b425-e200add7122e)

You can set the "output file suffix" too: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/026f48aa-2003-4e06-81f9-c247d6287516)

And PGS support for output mkv files:

**Comment by liam1900** [comment]
good job
Language/title setting window updated:
is what we see in mkvtoolnix and users in mkv player subtitle details?

**Comment by liam1900** [comment]
what about addig desired words before ext of file. i mean instead of embed
can we set multiple in setting?
like this
            var fileName = Path.GetFileNameWithoutExtension(_inputVideoFileName);
            fileName = fileName.Replace("NIGHTMOVIE", "");
            fileName = fileName.Replace("NightMovie.top", "");
            fileName = fileName.Replace("NightMovie.Top", "");
            fileName = fileName.Replace("NightMovie.TOP", "");
            fileName = fileName.Replace("NIGHTMOVIES", "");
            fileName = fileName.Replace("NightMovie", "");
            fileName = fileName.Replace("Night-Movie", "");
            fileName = fileName.Replace("nightmovie", "");
            fileName = fileName.Replace("night-movie", "");
            fileName = fileName.Replace("nightmovies", "");
            fileName = fileName.Replace("NightMovies", "");
            fileName = fileName.Replace("softsub", "");
            fileName = fileName.Replace("SoftSub", "");
            fileName = fileName.Replace("sub", "");
            fileName = fileName.Replace("Sub", "");
            fileName = fileName.Replace("SUB", "");
            fileName = fileName.Replace("AvaMovie.in", "");
            fileName = fileName.Replace("AvaMovie", "");
            fileName = fileName.Replace("30nama", "");
            fileName = fileName.Replace("30NAMA", "");
            fileName = fileName.Replace("30Nama", "");
            fileName = fileName.Replace("30NaMa", "");
            fileName += "_IMDBtops.Com_SoftSub_";
            fileName += Configuration.Settings.Tools.GenVideoEmbedOutputExt == ".mp4" ? ".mp4" : ".mkv";
            return fileName;

**Comment by niksedk** [comment]
OK, a `Remove list` has been added:

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

Context menu: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/fefb520c-1e88-47cc-9c94-60d6810aeafd)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/517b039b-3cf5-4f0a-ae28-dc589dd5ce7f)

**Comment by liam1900** [comment]
excellent bro

**Comment by liam1900** [comment]
OK, a Remove list has been added:

this menu must be in setting and permanent. cause every time setting this words is a pain in ass
