### ISSUE TITLE
single line CMD command for doing the job

### ISSUE THREAD

**Issue by liam1900** [SubtitleEdit/subtitleedit#8075]
i have many videos. more than 60k :)
i am supposed to do same job for them .i want use cmd command like mkvtoolnix.
is it possible?
command must include replace rules/export videos in embed mode/add remove subtitle just like in embed mode.
is it possible?
or using python to make it automatic?

**Comment by niksedk** [comment]
Sorry. That's a bit more that SE can do.
Try ffmpeg/mkvtoolnix

**Comment by liam1900** [comment]
> Sorry. That's a bit more that SE can do. Try ffmpeg/mkvtoolnix

thx bro
