### ISSUE TITLE
Linux HIDPI support?

### ISSUE THREAD

**Issue by niels0n** [SubtitleEdit/subtitleedit#8078]
Hey there!
I'm trying to use subtitleedit on my hidpi monitor on Linux but as you can see in the screenshot attached the sizing of the windows is pretty broken and I can't use it like this.
Is there some way to make this better?
Thank you.
![Screenshot from 2024-03-26 23-38-17](https://github.com/SubtitleEdit/subtitleedit/assets/47432766/07a68dfb-5ac3-4c38-83d7-16095d155a90)

**Comment by niksedk** [comment]
Sorry, it's really impossible to support HIDPI in Winform 4.x :(
