### ISSUE TITLE
Whisper cpp opencl 

### ISSUE THREAD

**Issue by Oplay66** [SubtitleEdit/subtitleedit#8079]
Possible add support whisper cpp opencl via clblast?

**Comment by niksedk** [comment]
Is the one SE uses
https://github.com/SubtitleEdit/subtitleedit/blob/main/src/ui/Forms/AudioToText/WhisperDownload.cs#L16

**Comment by Oplay66** [comment]
> Is the one SE uses https://github.com/SubtitleEdit/subtitleedit/blob/main/src/ui/Forms/AudioToText/WhisperDownload.cs#L16

Any tutorial to use opencl whisper cpp in SE?
Whisper cpp opencl and constme whisper which one is better?
