### ISSUE TITLE
Dialog buttons should be possible to activate with space button

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#8091]
Currently, the dialog buttons can be activated only with enter. 

Usually apps let press buttons with space button also, which is in the most cases more comfortable.

**Comment by niksedk** [comment]
Which buttons does not work?

**Comment by rRobis** [comment]
For example these ones in settings and Whisper dialog. Probably in others too, i didn't check. When i press space, it just changes color

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/de20752b-0e7d-4fc2-9ba8-a4599b4ae30c)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/c4f589a7-551b-4c2e-a762-feba5e820a04)

**Comment by niksedk** [comment]
Hm, works for me using latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by rRobis** [comment]
Ugh 😅  I just figured out that some of my AutoHotkey remap was causing this issue. 

Sorry for the false alarm.
