### ISSUE TITLE
Original media input for Faster-Whisper

### ISSUE THREAD

**Issue by Purfview** [SubtitleEdit/subtitleedit#8097]
Could that be implemented?
It doesn't need pre-converted 16khz wav input, all engines can do that internally.
Problem is that Faster-Whisper (and WhisperX) has various features where it needs the original media as input.

**Comment by niksedk** [comment]
Yes, sure.
What features do Faster-Whisper have extra with original input?

SE has an option to use only front-center-audio, so when this is enabled, SE will still pass a generated wave file.
(SE also uses the wave file internally)

I did a small test, and Faster-Whisper seems to ignore the "-standard" parameter with original video file? But it works with a wave file...

**Comment by Purfview** [comment]
> Yes, sure.

Cool. There could be one issue, if SE has option to select different audio track,.. all whispers just use the first audio, but I can add such selector by argument.

>SE has an option to use only front-center-audio, so when this is enabled, SE will still pass a generated wave file.

Do you mean extracting the third channel from 5.1, or do you use some algo?
That's OK as long as wav is not downsampled to ~16k-22k.

> I did a small test, and Faster-Whisper seems to ignore the "--standard" parameter with original video file? But it works with a wave file...

Not sure what you meant by "ignore", Faster-Whisper doesn't ignore any parameters depending on different inputs.
Maybe SE ignores it?

>What features do Faster-Whisper have extra with original input?

These and probably more coming:

https://github.com/Purfview/whisper-standalone-win/discussions/178
https://github.com/Purfview/whisper-standalone-win/issues/224

That question was for you -> https://github.com/Purfview/whisper-standalone-win/issues/224#issuecomment-2025186352

**Comment by niksedk** [comment]
Thx, SE was loading srt from stdout (not using the file name from the input, but should be fixed now).

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

Yes, SE uses the current audio track selected from the SE UI (Video menu in main window).

**Comment by Purfview** [comment]
Thx, I'll check it later.

I've implemented track selection, for example this selects the second audio track: "--ff_track 2"

What command do you use to extract front-center-audio? I may implement that too.

And could you point to your "Auto-adjust timing" code? I want to know more how it works.

**Comment by niksedk** [comment]
>What command do you use to extract front-center-audio? I may implement that too.
It very nice when working with BD SUPs, SE uses the ffmpeg parameter `-af "pan=mono|c0=FC"`

>And could you point to your "Auto-adjust timing" code? I want to know more how it works.
SE check for silence close to the start/end time.
https://github.com/SubtitleEdit/subtitleedit/blob/main/src/libse/AudioToText/WhisperTimingFixer.cs#L42
