### ISSUE TITLE
Feature request:  Use GPU only if it's not under heavy workload when starting.

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8104]
Lately I'm using Topaz Video which is really hurting the GPU and this for a long period.
I love Whisper to make use of the GPU, but when it is already being stressed down I would prefer it uses CPU only.

The CPU will have more time to finish the task for Whisper and probably Topaz will not slow down as much.

A short probe of the GPU-load before the job starts.

**Comment by niksedk** [comment]
You can use add a  `--device cpu`  parameter

**Comment by fraternl** [comment]
I know I can tell Whisper to not use the GPU.
I just restarted it with "-ng" (no GPU).

But that's not the point.
I want to use the GPU only if it's available.
Topaz is sometimes running for days and I'm not really aware that it's running.

I would like SE to start Whisper with --no-gpu only if the GPU is already very busy.
