### ISSUE TITLE
Error: Sequence contains no matching elements

### ISSUE THREAD

**Issue by highflowerG** [SubtitleEdit/subtitleedit#8106]
![Screenshot (19)](https://github.com/SubtitleEdit/subtitleedit/assets/165585366/a2621390-acec-4c60-90cb-b5064b46fb5f)

**Comment by niksedk** [comment]
How can I re-create this?

**Comment by highflowerG** [comment]
It was quite recreatable until I 're-docked video controls' from Video.
Before that I accidentally (apparently) 'undocked' video while editing
subtitle text.

**Comment by niksedk** [comment]
Thanks for the info :)
I've tried to fix the layout change crash here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip
Let me know how it works

**Comment by highflowerG** [comment]
Is yours a portable version now? Looks good, I can't reproduce the original
problem with your verison. It is still reproducible with the original
4.0.4. But your fixed version now always shows 'Un-dock video control' as
the last choice of Video menu. That's another bug now :)

**Comment by niksedk** [comment]
@highflowerG: thx for testing :)
Beta (portable version) updated again: 
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

Un-dock should work again, and you can now switch layout from un-docked state.

**Comment by highflowerG** [comment]
Fixed! Спасибо :)
