### ISSUE TITLE
Any dictionary for Chinese simplified ?

### ISSUE THREAD

**Issue by djlaludo** [SubtitleEdit/subtitleedit#8107]
Hi,

I'm surprised to see there is not the chinese dictionnary included. Is it possible to easily transform a libreoffice file to SubEdit dictionnary?  

Thanks!

**Comment by niksedk** [comment]
Sorry, I don't know any Chinese spell check

SE, uses hunspell - see https://github.com/hunspell/hunspell/issues/502
