### ISSUE TITLE
ℹ️ as an idea. we must add cmd command to application...

### ISSUE THREAD

**Issue by liam1900** [SubtitleEdit/subtitleedit#8108]
hi again. we must add cmd command to prevent repetitive actions.
i do this actions every time just same.

**add video. >edit>multiple replace>apply changes ?ok> video menu> generate video softsub...>click old sub then remove button> generate video while removing old one**

this process is same for many many videos
we must figure this out to make it work with command so we can use python to automatically do this
any suggestion or better idea?

**Comment by yovelcohen** [comment]
There's https://github.com/SubtitleEdit/subtitleedit-cli which exposes a CLI for SubtitlesEdit, I call it using subprocess from python.

**Comment by liam1900** [comment]
> There's https://github.com/SubtitleEdit/subtitleedit-cli which exposes a CLI for SubtitlesEdit, I call it using subprocess from python.

thx i wrote my own code to work with ffmpeg and extract srt and edit it and merge it with movie automatically with mkvtoolnix and delete old movie from dir
