### ISSUE TITLE
Running whisper only in waveform selection region?

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#8109]
Is there a way to run whisper only on highlighted waveform region. 

If I make a one long empty subtitle, and run whisper on that line, then it just puts all text in one subtitle. (i know that i can use post-processing to split them, but it will mess up the timestamps then)

Maybe i'm missing something.

**Comment by darnn** [comment]
There isn't currently. I make one long empty subtitle, extract the audio, open another instance of SE, open the audio and run Whisper there. Then I adjust the timing to match that of the original file, copy the subtitles and paste them back into the original file in source view (otherwise the timing gets shifted).

**Comment by niksedk** [comment]
OK, latest beta should now treat a single selected line (with duration > 10 seconds) as "normal mode", and generate many subtitle lines.

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip
Does that work for you?

**Comment by Purfview** [comment]
Btw, if you use whisper directly then there is `--clip_timestamps` arg to select region for transcription.
For example `--clip_timestamps 120.0,180.0` would process only the third minute.

**Comment by rRobis** [comment]
Thanks, seems to be working as expected now. 

The only improvement that I could suggest is adding item in context menu (in waveform window), that would automatically create a subtitle in selected region in waveform, and do whisper there (or just do whisper without creating subtitle).

**Comment by niksedk** [comment]
You can setup a shortcut:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/085820b5-4a4d-4527-ae46-1236c833fb12)

**Comment by niksedk** [comment]
Also, new context menu item for a long paragraph:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/26ae49cf-b466-4286-ac2c-d4afb133e300)
