### ISSUE TITLE
Translate selected lines not working.

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#8111]
When i select specific lines and use the context menu to Auto Translate the lines, Translate - selected lines dialog doesn't have any lines in it. 

Am I doing something wrong, or this is a bug?

I am using latest beta, but i noticed this a while ago.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/1cfca825-f02b-470b-a878-050b21db0344)

**Comment by niksedk** [comment]
Thx, good finding :)

Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip ?

**Comment by niksedk** [comment]
Thx for testing. 

Yes, could be an option for selected lines not in translator mode... but for now, it should just enter translate mode... I think...

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by rRobis** [comment]
I tested, it works as expected now. When selecting and translating, it opens translator mode and translates the selected lines.

Thanks!
