### ISSUE TITLE
Can't use DeepL API key to translate. 

### ISSUE THREAD

**Issue by Yukineko2121** [SubtitleEdit/subtitleedit#8126]
<img width="631" alt="1" src="https://github.com/SubtitleEdit/subtitleedit/assets/160497356/7fbfb7cf-a0df-4ced-bb65-1a90727af135">
<img width="527" alt="Screenshot 2024-04-03 120653" src="https://github.com/SubtitleEdit/subtitleedit/assets/160497356/39cc635b-27b6-4e34-b838-bfd3bac4da5f">

Any available solution to fix this problem ? Thank you !

**Comment by niksedk** [comment]
The plugin has been replace by built-in functionality.

You still need to enable billing on Deppl.com
