### ISSUE TITLE
Is there any free machine translation option better than Google Translate V1?

### ISSUE THREAD

**Issue by angelfire76** [SubtitleEdit/subtitleedit#8127]
The current options that require an API require a paid account as far as I can see. Is there a free model that does a better job than GT V1?

**Comment by niksedk** [comment]
You can use Google Translate V1 with a free quota each day.
Another option is DeepL free API (requires enabling of billing). Is probably a tiny bit better than Google Translate.

Also, more and more "Chat GPT" like models are coming all the time. Many you can run locally via "LM Studio" or Ollama, which will be support in next SE beta. These models are slow (unless you have a nice gfx card), and the quality is probably yet worse then Google Translate.

Libre translate is also okay, but still not as good as GT.
