### ISSUE TITLE
Instruct Powershell to run SubtitleEdit.exe CLI synchronously

### ISSUE THREAD

**Issue by Hlsgs** [SubtitleEdit/subtitleedit#8133]
Contrary to the case of a tool like ffmpeg, Powershell does not wait for SubtitleEdit.exe CLI to finish before proceeding to the next commands in a ps1 script. I am aware that this can be mitigated by piping SE to ` | Out-Default`, but I believe SE CLI should run sync by default because of it's nature(we may wish to subsequently operate on the converted subtitles). Since tools like ffmpeg do not have this issue, there must exist a means of compiling the executable so as to instruct Powershell to run it sync.

**Comment by niksedk** [comment]
I'm not really sure that's possible to fix, as SubtitleEdit.exe is not really an CLI...

You could try https://github.com/SubtitleEdit/subtitleedit-cli (which also works on Linux/Mac)
