### ISSUE TITLE
Waveform feature where you move it with a mouse is missing in v4

### ISSUE THREAD

**Issue by Purfview** [SubtitleEdit/subtitleedit#8136]
I meant the waveform moving feature when you mouse click at sides of it...

Till today I was mainly using v3 and v4 was there too for tests only, so, I decided to get rid of v3 and switched to v4 and to my horrors the waveform doesn't move how I used it to move by simple mouse clicking...

**Comment by Purfview** [comment]
> I do not think anything have changed for the waveform.

It definitely moved before as it is my main used feature, that I just noticed as the first thing, maybe it was like centering thing when you click at the sides.

> You can move the left side by shift down + left click.

That moves the "cursor" not the actual waveform, and it's nuisance to use.

**Comment by niksedk** [comment]
Is it the center option?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/3319de44-7234-4bea-8724-1f2e493ab83d)

**Comment by Purfview** [comment]
> Is it the center option? 

Oh, yes it is! What we would do without you. 😆
Somehow it was disabled after update. Imo, it should be enabled by default.
