### ISSUE TITLE
Some sentences skips in Auto-Translate

### ISSUE THREAD

**Issue by PureOcean** [SubtitleEdit/subtitleedit#8139]
After 4.0.1 version, Auto-Translate skips some sentences. For this reason it translates the next line in the existing time code. So several lines are out of sync.

Can you try the following sample subtitles both in 4.0.1 and 4.0.4 or beta version? 4.0.1 is without problems.

Translate engine: Google Translate V1 API

> Example 1:
> Language source: English
> Language target: Turkish
<pre>
<details>
<summary>Subtitle lines:</summary>
1
00:08:19,374 --> 00:08:23,253
Look, Victor,
we have to discuss our options.
</details></pre>

*

> Example 2:
> Language source: Swedish
> Language target: Turkish

<pre>
<details>
<summary>Subtitle lines:</summary>
1
00:31:18,070 --> 00:31:23,526
Med en skuld som nu uppgår
till 8 445 000 kronor.

2
00:31:23,550 --> 00:31:27,726
Och du lever på förbehållsbelopp
när vi dragit pengar på din lön.
</details></pre>

**Comment by niksedk** [comment]
Works fine here for me....

**Comment by PureOcean** [comment]
Thank you for test.

Let's compare the Auto-Translate outputs of both versions:

> Example 1 ( English -> Turkish )
<pre>
<details><summary>Subtitle source lines:</summary>
1
00:08:19,374 --> 00:08:23,253
Look, Victor,
we have to discuss our options.
</details>
</pre>

<pre><details><summary>4.0.4 (beta 171)'s translate output: (Second lines cannot translate.)</summary>
1
00:08:19,374 --> 00:08:23,253
Bak Victor.
</details>
</pre>

<pre><details><summary>4.0.1's translate output: (Correct. The second line translated.)</summary>
1
00:08:19,374 --> 00:08:23,253
Bak Victor,
seçeneklerimizi tartışmalıyız.
</details>
</pre>

<hr>

> Example 2 ( Swedish -> Turkish )
<pre>
<details><summary>Subtitle source lines:</summary>
1
00:31:18,070 --> 00:31:23,526
Med en skuld som nu uppgår
till 8 445 000 kronor.

2
00:31:23,550 --> 00:31:27,726
Och du lever på förbehållsbelopp
när vi dragit pengar på din lön.
</details>
</pre>

<pre><details><summary>4.0.1's translate output: (All lines translated correctly.)</summary>
1
00:31:18,070 --> 00:31:23,526
Şu anda 8.445.000 SEK
tutarında bir borcu var.

2
00:31:23,550 --> 00:31:27,726
Ve maaşınızdan kesinti yaptığımızda
rezerv miktarıyla yaşıyorsunuz.
</details>
</pre>

<pre><details><summary>4.0.4 (beta 171)'s translate output:</summary>
1
00:31:18,070 --> 00:31:23,526
Şu anda 8.

2
00:31:23,550 --> 00:31:27,726
445.
</details>
</pre>
4.0.4's result: All lines were not translated. After the `.` character, the next ones cannot be detected and translated.

**Comment by niksedk** [comment]
Thx, I see it now... only with Turkish. Looks like a bug...

**Comment by niksedk** [comment]
I've tried to improve the issue here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip
Better?

**Comment by PureOcean** [comment]
@niksedk Thank you very much for [fix codes](https://github.com/SubtitleEdit/subtitleedit/commit/ee519c597a5d24bfc3e086c91c35128e59ac4aa9) and compiled the build.

I just tried examples. Yes, all fixed. I tried a few subtitles. At first view, there is no problem.

However, I tried the next lines of the first example. Merging issue.

<pre><details><summary>Source subtitle</summary>
1
00:08:19,374 --> 00:08:23,253
Look, Victor,
we have to discuss our options.

2
00:08:23,336 --> 00:08:28,508
The rebels could be at our door
any day now, so just talk to me.

3
00:08:28,591 --> 00:08:30,552
I believe in the virtue of loyalty,
Mr. Singer,

4
00:08:30,635 --> 00:08:33,138
so there's nothing left for us to discuss.
</pre></details>

<pre><details><summary>4.0.4 beta 186's English -> Turkish translate output</summary>
1
00:08:19,374 --> 00:08:23,253
Bak Victor.

2
00:08:23,336 --> 00:08:28,508
Seçeneklerimizi tartışmalıyız.

3
00:08:28,591 --> 00:08:30,552
İsyancılar her an kapımıza gelebilir, o yüzden konuş benimle.

4
00:08:30,635 --> 00:08:33,138
Sadakat erdemine inanıyorum Bay Singer, tartışacak bir şeyimiz kalmadı.
</pre></details>

<pre><details><summary>4.0.1's English -> Turkish translate output</summary>
1
00:08:19,374 --> 00:08:23,253
Bak Victor,
seçeneklerimizi tartışmalıyız.

2
00:08:23,336 --> 00:08:28,508
İsyancılar her an kapımıza
gelebilir, o yüzden konuş benimle.

3
00:08:28,591 --> 00:08:30,552
Ben sadakatin erdemine
inanıyorum Bay Singer,

4
00:08:30,635 --> 00:08:33,138
o yüzden tartışacak
bir şeyimiz kalmadı.
</pre></details>

4.0.4 breaks the synchronization by throwing the sentence after the comma in the first line of the subtitle to the next timecode. So line "2" shifts to line "3", and line "3" shifts to "4". No problem in 4.0.1.

**Comment by niksedk** [comment]
This is a known minor issue....
