### ISSUE TITLE
Incorrect API key message with ChatGPT

### ISSUE THREAD

**Issue by stephanedebove** [SubtitleEdit/subtitleedit#8141]
Hi there,

I’m trying to use ChatGPT to auto-translate but can’t get it to work. I have an API key with a paid plan. When I input it in the "API key" field, I get the message 

`The model my_api_key does not exist or you do not have access to it.
`

So it looks like it wants a model name in this field. But if I enter a model name such as gpt-4-1106-preview, it replies:

`Incorrect API key provided: gpt-4-11******view 
`

So am I supposed to put both the model name and API key in this field, and if yes, with what syntax? 
Thanks.

**Comment by niksedk** [comment]
Sorry, this is a bug - should hopefully be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by stephanedebove** [comment]
Thanks, can I simply replace my old install with these files, overwriting everything? I don’t want to download a second time the big Whisper models I use for Audio to text...

**Comment by niksedk** [comment]
If you're using the installer, you could replace "SubtitleEdit.exe" + "libse.dll". SE 4.0.5 should be out soonish...

If you're using the portable version, overwrite all.
