### ISSUE TITLE
ConstMe outputs only question marks in Hebrew

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#8144]
Hi. I'm not sure exactly when this broke, it's not 4.0.5 (maybe 4.0.2-4.0.4), but when using ConstMe with the large model (that is, large-v2, the one it uses), and trying to recognize audio in Hebrew, the output it produces is just question marks. It looks like something's going wrong with the text encoding, because the question marks clearly correspond to actual words that would be in its normal output. WhisperDesktop.exe from the same version handles the same file just fine.
I'm not sure what other languages this affects, but English works fine, including with the same file if you tick `Translate to English`.
You can get a sample Hebrew file here:
http://hebrew.voiceoversamples.com/HEB_M_EriDE.mp3

**Comment by niksedk** [comment]
Thx, good catch :)

SRT loading from Whisper should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Works here!
