### ISSUE TITLE
Special arguments used with Faster Whisper?

### ISSUE THREAD

**Issue by stephanedebove** [SubtitleEdit/subtitleedit#8145]
I was trying to replicate the results I get using Subtitle Edit’s Audio to Text function, engine Purfview Faster-Whisper, language english and large-v1 model. I am *not* ticking the "Auto adjust timings" or "Use post-processing" boxes.

I was thinking I would get the exact same results using this python code:

```
from faster_whisper import WhisperModel

model_size = "large-v1"
model = WhisperModel(model_size, device="cuda", compute_type="float16")
segments, info = model.transcribe("video.mp4")

for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
```

but I don’t. It’s 95% the same but some segments are not cut the same way. For instance, with python I will get this segmentation:

```
0:00:21,460000 --> 0:00:23,960000
 Thank you so much. Go ahead and move my car out

7
0:00:23,960000 --> 0:00:25,080000
 so fire can pull in.
```

and with Subtitle Edit this one:

```
6
00:00:21,480 --> 00:00:22,480
Thank you so much.

7
00:00:22,780 --> 00:00:25,060
Go ahead and move my car out so fire can
pull in.
```

Of course the one by Subtitle Edit is better.

So is Subtitle Edit doing some post-processing even if I didn’t tick the box, or is it sending non-default arguments to Faster Whisper? Can I achieve the same results through Python?

**Comment by Purfview** [comment]
> I was thinking I would get the exact same results using this python code

It's not comparable as Standalone Faster-Whisper is not exact implementation.
Even if it was, model is non-deterministic, results can be different every run.
