### ISSUE TITLE
Char/sec 

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#8148]
I have a file and some of its subtitles durations is long enough to have 10 characters per second value, some 15, some 13, etc. I was thinking about an option which would allow us to make the end times shorter so it would fit our desired characters per sec limit - say 20 or 18.

**Comment by ext666** [comment]
Try to fiddle with the "re-calculate" shortcut in the settings menu.

**Comment by niksedk** [comment]
In latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

You can do a modify selection with `CPS greater/smaller than`... and do a adjust duration on selected lines.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/2936a70f-f17f-447e-93be-748b88dfbb47)


![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/5d109ac8-fd2b-4f41-be44-509ad07cd50f)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/9bec9614-e4f7-4783-ab30-305edf914d55)
