### ISSUE TITLE
How to use Intel GPU in Purfviews Faster Whisper?

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8153]
I have an Intel 14th gen i7 with GPU.
Standard Whisper was able to use the Intel GPU.
It seems Purfviews Faster Whisper can only use nVidia's GPU (--device cuda)

Is there a reason why only nVidia's GPU can be used?
If there's a potential gain could it be implemented?

**Comment by Purfview** [comment]
>How to use Intel GPU in Purfviews Faster Whisper?

You can't.

>It seems Purfviews Faster Whisper can only use nVidia's GPU (--device cuda)

Bingo!

**Comment by fraternl** [comment]
You're not getting into the reason why it's difficult to implement support for Intel.
It seems the more we're getting into the "information age" the less information is given.

**Comment by Purfview** [comment]
> You're not getting into the reason why it's difficult to implement support for Intel.

Did I said somewhere that it's difficult?
For things to not happen you don't need any reason at all, and you need reason for things to happen.

> It seems the more we're getting into the "information age" the less information is given.

The perception of receiving less information may stem from encountering questions or statements that appear contradictory or paradoxical. Oxymoronic questions often challenge conventional thinking and may not have straightforward answers.

**Comment by Purfview** [comment]
Faster-Whisper's backend is CTranslate2 and it supports only CUDA.

**Comment by Azzhoe** [comment]
I have an NVIDIA RTX 3090, how do It the Audio to text feature from Subtitle Edit 4.0.7 to work using my GPU instead? I am using Purfview's Faster-Whisper as the engine with large-v3 language model. I am trying to convert Spanish to English in my video. I'm not sure what the best engine to use that will give me the best result in the shortest amount of time?

**Comment by niksedk** [comment]
Note that large-v2 is recommended over large-v3

**Comment by Azzhoe** [comment]
> Note that large-v2 is recommended over large-v3

Why is that?

**Comment by peteciank** [comment]
At least in Windows 10 and 11, you can use Intel GPUs by assigning GPUs to Python in Graphic Settings. 

![Image](https://github.com/user-attachments/assets/77b40872-45cd-4f90-a22f-13d0dc819a9d)

![Image](https://github.com/user-attachments/assets/0e5fec82-3287-4846-8460-e3ab2f1460e9)

I tested Faster-Whisper using this setting (device is still in cpu or it will  fail cuda driver), and when you monitor resource consumption, you can see python using GPUs and performance is wide better!

Hope that helps :)
