### ISSUE TITLE
Like Ctrl-I will surround a selection with "italics", can we have music symbols

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8154]
Often, especially after a Whisper-rip, I have a part that's actually music.
It's a tedious job to surround every line with a music symbol.

I solve this by first giving the selection a "Ctrl-I" so it turns into italics and `then do a search and replace on <i> and then on </i>.`

It does the job, but having something like "Ctrl-M" would be much more elegant.

**Comment by niksedk** [comment]
You can use `Toggle customs start/end` + shortcut
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/aef9ab49-f797-43a8-b4e9-2c6f6487456a)

Or just toogle music symbols:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/69c829ac-3d0d-4091-91e6-6dda599ad02e)

**Comment by fraternl** [comment]
Thanks for the explanation!
I have it implemented now...
