### ISSUE TITLE
Support Custom Auto-Translate Server - Create Standard API Specs

### ISSUE THREAD

**Issue by ewwink** [SubtitleEdit/subtitleedit#8155]
I think it would be a good idea if SubtitleEdit supports a custom HTTP API Server for auto-translate, but the server should meet the criteria required by SubtitleEdit.

Example API specs:
- `exndpoint`: http://localhost8000
- `Authentication`: Optional
- `from`: Source of language
- `to`: Target of translation
- `text`: text to translate

Example Request:
```
GET http://localhost8000/?from=en&to=id&text=hello+world
User-Agent: SubtitleEdit 
Authentication: verysecretkey (optional)
```

Response
```
{
  "original": "hello world",
  "translated": "halo dunia"
}
```

**Comment by niksedk** [comment]
I think we could just use the API LibreTranslate as it seems okay simple:
https://libretranslate.com/docs/#/translate/post_translate

**Comment by pedjas** [comment]
I would support this request. I need transliteration not translation. It would be really simple if I could set up small custom web app that would act like translations service and do transliteration using custom rules I set.
