### ISSUE TITLE
[Suggest] New Auto Translation Engine

### ISSUE THREAD

**Issue by rikimtasu** [SubtitleEdit/subtitleedit#8158]
Would it be possible to add Command R Plus by Cohere as a new Auto Translation Engine for subtitles edit?

https://huggingface.co/CohereForAI/c4ai-command-r-plus
https://txt.cohere.com/command-r-plus-microsoft-azure/

**Comment by GOvEy1nw** [comment]
I'd also like to suggest the use of NLLB via ctranslate2 also, as it's designed to be much faster than the current NLLB implementations.

**Comment by niksedk** [comment]
@rikimtasu: Try via "LM Studio" or Ollama. Maybe they already have them or can add them.
