### ISSUE TITLE
Unable to read name list file (found a solution)

### ISSUE THREAD

**Issue by eastone11** [SubtitleEdit/subtitleedit#8159]
I encountered a problem that affects users whose profiles are stored on the network. This problem occurs when using the function of converting video\audio to text using the Vosk-Kaldi method.
I found a solution: copy the ru_names.xml file to the same folder, but with a new name - ru_names_user.xml.

![Без имени](https://github.com/SubtitleEdit/subtitleedit/assets/139941473/76c7dcc2-9163-4671-b04f-be05e46c324c)

**Comment by ivandrofly** [comment]
Looks like the app is trying to read from a network path

**Comment by ivandrofly** [comment]
Make sure the machine running SE has read-access to that path
