### ISSUE TITLE
SubtitleEdit ignores sometimes breaks in RTF files

### ISSUE THREAD

**Issue by Ninelpienel** [SubtitleEdit/subtitleedit#8168]
Hello, I ocr my subtitles with Abbyy and would like to merge the output with the import function of SubtitleEdit. RTF is the only format I could find that preserves italics and can be read properly in with the import function. But sometimes the breaks are gone. Is this a bug?

Here are two example files where the breaks are no longer present after the import:

[Break Gone.zip](https://github.com/SubtitleEdit/subtitleedit/files/14947586/Break.Gone.zip)

They are still present here:

[Breaks Not Gone.zip](https://github.com/SubtitleEdit/subtitleedit/files/14947613/Breaks.Not.Gone.zip)

**Comment by niksedk** [comment]
Where and how in SE are you doing this? A screenshot would help...

**Comment by Ninelpienel** [comment]
Seems like problem was me, SE does everything correctly. The issue can be closed.
