### ISSUE TITLE
Found another IMSC1.1 Bug

### ISSUE THREAD

**Issue by ryzen88** [SubtitleEdit/subtitleedit#8169]
Hey, its me again.

I found another issue with the new IMSC1.1 profile.
It often does not notate the frame rate multiplier in the subtitle file even when filling it in with the properties tab.

With a blanc new subtitle not, it can remove it when importing something that has it notated.
Not per definition always but more often than not.

**Comment by ryzen88** [comment]
[test package.zip](https://github.com/SubtitleEdit/subtitleedit/files/14954746/test.package.zip)
I have added some screenshots and the bug and sub file, and demonstration with a new sub, but noticed that is also happens with subs that already have the value in the subtitle and it just clears them. Also added a normal TT that does not have the issue

**Comment by ryzen88** [comment]
I also found that when the Title is annotated with the <ttm:title> Titel name go here </ttm:title> in the original subtitle for example a normal TT. The title gets removes  in the conversion to IMSC. 
With the normal TT you have the option to manually insert the title name, but not with the IMSC TT. 
It would be cool if there is a title name in the original that it preserves it.

**Comment by niksedk** [comment]
> I also found that when the Title is annotated with the ttm:title Titel name go here </ttm:title> in the original subtitle for example a normal TT. The title gets removes in the conversion to IMSC. With the normal TT you have the option to manually insert the title name, but not with the IMSC TT. It would be cool if there is a title name in the original that it preserves it.

Do you have a sample IMSC 1.1 document with a title? I have a hard time finding this in the spec: https://www.w3.org/TR/ttml-imsc1.1

**Comment by ryzen88** [comment]
[Example_IMSC1.zip](https://github.com/SubtitleEdit/subtitleedit/files/15212518/Example_IMSC1.zip)

**Comment by niksedk** [comment]
OK, I've added the title here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

I will close this as. you also have a similar issue.
