### ISSUE TITLE
Extract images from video

### ISSUE THREAD

**Issue by Wernouxe** [SubtitleEdit/subtitleedit#8175]
Hi, I have a suggestion that I think might be of interest to many! (Especially if you use Tesseract!)

Extract subtitled frames from a video
This function captures each frame of the video containing a subtitle, renaming the frames with the timecode.
(So it's possible to do this for several videos).

**Comment by niksedk** [comment]
Duplicate of https://github.com/SubtitleEdit/subtitleedit/issues/340 I think... ?

**Comment by Wernouxe** [comment]
Ah yes sorry!
