### ISSUE TITLE
The actor column didn't display when set ass as default format

### ISSUE THREAD

**Issue by zxzlf** [SubtitleEdit/subtitleedit#8180]
When I open an ass file directly, the actor column didn't display
I need to change the format to another one and reopen the ass file, then the actor column comes back
but if I close SE and reopen it, the actor column disapear again

**Comment by niksedk** [comment]
Right-click on the column-header to change visible columns

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/aaeb0439-633b-4af9-ba4f-d7f3247a04d5)

**Comment by zxzlf** [comment]
> Right-click on the column-header to change visible columns
> 
> ![image](https://private-user-images.githubusercontent.com/1261331/322222314-aaeb0439-633b-4af9-ba4f-d7f3247a04d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNjIyNDIsIm5iZiI6MTcxMzA2MTk0MiwicGF0aCI6Ii8xMjYxMzMxLzMyMjIyMjMxNC1hYWViMDQzOS02MzNiLTRhZjktYmE0Zi1kN2YzMjQ3YTA0ZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMDIzMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjVhYmI0Mzg5Nzc2MTk1ZDU0ZjIyMzljYzMyMTk2NDdlNWEwNmJjNGFhN2U2NzZhN2I1Yjc4ZDc4MTBhNGUzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p2X988wT7qX7QxicI4AnkQ6IUxmuDrY5eVz-ZcaYiVo)

I've already set actor visible, but it still not display, i need to uncheck actor and recheck it to make it display

**Comment by zxzlf** [comment]
> Right-click on the column-header to change visible columns
> 
> ![image](https://private-user-images.githubusercontent.com/1261331/322222314-aaeb0439-633b-4af9-ba4f-d7f3247a04d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNjM2MDYsIm5iZiI6MTcxMzA2MzMwNiwicGF0aCI6Ii8xMjYxMzMxLzMyMjIyMjMxNC1hYWViMDQzOS02MzNiLTRhZjktYmE0Zi1kN2YzMjQ3YTA0ZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMDI1NTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU1ZTliNmYzM2U2MjdjYmFjMzNkNDE0NTI5NmViZjMzMjY4MTRjNWIwYzUxMTVmODRkNGI5ZDdkMTY2ZjdiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QZX1lTvsBzf0IJEmClIXFG0_6ynF2gdbQcgT4rOkPTM)

You can reproduct this issue by these steps:
1.Set ass as default subtitle format in options
2.Right-click on the column-header to change the actor column visible
3.Close SE and double click an ass file to open it in SE, then you will see the actor column disapear
