### ISSUE TITLE
OCR replace: "l'" followed by a capital letter becomes "L'" (in French)

### ISSUE THREAD

**Issue by Codling** [SubtitleEdit/subtitleedit#8184]
Hello.

Since this fix: https://github.com/SubtitleEdit/subtitleedit/issues/8052 all the "l'" followed by a capital letter becomes "L'", which is quite annoying.

Example: "l'Arbre" becomes "L'Arbre"

Thanks.

**Comment by Codling** [comment]
Any help for this issue, please?

**Comment by niksedk** [comment]
Could you attach a screenshot + a subtitle file so we can understand and re-produce this easier?

Also, do you have other words that give the same error with casing?

**Comment by Codling** [comment]
Sure:

![Sans titre](https://github.com/SubtitleEdit/subtitleedit/assets/48414823/94006c80-720f-4221-99ed-96f7cd14cddd)

[Example.zip](https://github.com/SubtitleEdit/subtitleedit/files/15239684/Example.zip)

**Comment by ivandrofly** [comment]
Taking a look at this issue!

**Comment by Codling** [comment]
Any news about this issue, please?
The problem still occurs.

**Comment by ivandrofly** [comment]
> Any news about this issue, please?
> 
> The problem still occurs.

Well, the patch is provided but hasn't been merged yet!

**Comment by Codling** [comment]
Cool! Thanks a lot, Ivandro!

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by niksedk** [comment]
Fix included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip
