### ISSUE TITLE
Error reading big m2ts files (MakeMKV output)

### ISSUE THREAD

**Issue by yellobyte** [SubtitleEdit/subtitleedit#8186]
The program reports errors when reading big transport stream files >64G produced from UHD-BDs by MakeMKV.

![SubtitleEdit_Error](https://github.com/SubtitleEdit/subtitleedit/assets/76921504/f989d64d-6baa-422e-be4d-77c5804165f1)

**Comment by niksedk** [comment]
Wow, that's a big file indeed!

I've tried to fix it in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
Better?

**Comment by yellobyte** [comment]
Nope. The error still occurs, this time with a slightly different message. Snapshot attached. 
However, many thanks for your impressively quick reaction. Cheers Th

![SubtitleEdit_ErrorBeta](https://github.com/SubtitleEdit/subtitleedit/assets/76921504/e7211914-d95a-43e4-8da7-1afd3d5c3426)

**Comment by niksedk** [comment]
Thx again... new beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
Better?

**Comment by yellobyte** [comment]
Nope. It now went to about 80% and then triggered an error again. Last time it managed only ca 10%. Getting better...

![SubtitleEdit_ErrorBeta2](https://github.com/SubtitleEdit/subtitleedit/assets/76921504/d6b737b8-7e58-4bc1-8869-8ac0bd082404)

**Comment by niksedk** [comment]
OK, how close are we with https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip ?

**Comment by yellobyte** [comment]
Scanning a small 40GB file is successful though. Here the RAM usage timeline for this scenario.
If you want me to capture the RAM usage while digesting a 93GB m2ts file please raise your hand.

![SubtitleEdit_Beta2_RAM_usage_with_40GB_m2ts_file](https://github.com/SubtitleEdit/subtitleedit/assets/76921504/2a571307-d0c0-481d-aa6d-73a0b5d63179)

**Comment by yellobyte** [comment]
Ok, here we chew through a 93GB m2ts file. I killed the tool when it hit ~99% RAM usage.

https://github.com/SubtitleEdit/subtitleedit/assets/76921504/eca8073b-25af-45e2-a2d1-2975b707de6a

**Comment by niksedk** [comment]
Sorry, I cannot see why SE should use so much memory (but these files are huge). Also, really hard to test...
Any help is welcome.

**Comment by yellobyte** [comment]
Maybe a memory leak somewhere...malloc/calloc without free.
The file I test with is a standard m2ts file of a 2:35h UHD movie with 18 subtitle tracks. Maybe that's simply too many ?

**Comment by niksedk** [comment]
I have no way to test this

**Comment by yellobyte** [comment]
No worries. Cheers Th
