### ISSUE TITLE
How to set up automatic translation? 

### ISSUE THREAD

**Issue by Primalaprima** [SubtitleEdit/subtitleedit#8188]
Hi? Thank you for this wonderful software. 

I have a problem with auto translation which is a bit annoying after v4.0.2.

In version 4.0.2, auto translate works very well. Where the translation result matches the line in the source. But, after that version, the translation becomes a bit ambiguous, the translation result is not loaded on one line, there are words that are loaded and merged on the line after it.
Is there anything that needs to be adjusted again?

**Comment by niksedk** [comment]
What translator and from/to language are you using?
Could you add a screenshot + subtitle file?

You can try to use "translate single lines" via the context menu:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/05f9ace8-88e3-4e23-8934-0a94c13b5acb)

**Comment by Primalaprima** [comment]
Additional information.
I change "Single line max line to 51"
