### ISSUE TITLE
Multi-line captions in SRT files created by MacCaption not imported correctly

### ISSUE THREAD

**Issue by msl521** [SubtitleEdit/subtitleedit#819]
When exported from MacCaption, multi-line pop on captions are separated by CRLF. When one of these SRT files is opened in Subtitle Edit, only the first line of the caption is kept. A minimal example is below. When that is opened in Subtitle Edit, only **Line1** is kept.

```
00:00:00.367,00:00:03.003
Line1
Line2
Line3
```

**Comment by msl521** [comment]
Digging deeper on the MacCaption side, this format is what MacCaption calls "Youtube .srt" but comes up in Subtitle Edit as "SubViewer 2.0 (.sub)".

**Comment by niksedk** [comment]
It would be easier with a sample file... you possibly add a link here or send it in an email?

**Comment by msl521** [comment]
There is a sample in my original comment and [here](https://gist.github.com/msl521/0a626a09574a4bff56ea#file-maccap_youtube-srt).

**Comment by niksedk** [comment]
Do you have a sample *file*

**Comment by msl521** [comment]
Same as the other two places: https://drive.google.com/file/d/0BwCJo1usxdkdcTJGVDVtWG5oNEU/view?usp=sharing

**Comment by niksedk** [comment]
lol, you don't have longer file?

**Comment by msl521** [comment]
Here's a [30 second file](https://drive.google.com/file/d/0BwCJo1usxdkdX0tuWHFvaUdpMWc/view?usp=sharing). The other is the minimum required to reproduce the issue.

**Comment by niksedk** [comment]
Thx for the longer file :)
After looking at YouTube subtitle support page ( https://support.google.com/youtube/answer/2734698?hl=en# ) I was rather... disappointed. Your file should be a "SubViewer 2.0" file for YouTube (if this file is a SRT from MacCaption, then MacCaption has mislabeled the export text). Further more YouTube's version of a "SubViewer 2.0" file is incorrect (wrong new line + time codes), so they have actually created their own format ;)

SE will be fixed shortly to support "YouTube sbv" files better shortly :)

**Comment by niksedk** [comment]
You can compile latest source from github or use this portable beta: http://www.nikse.dk/SubtitleEdit.zip
