### ISSUE TITLE
Reviewing own dictionary from within SE

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8190]
I just installed 4.0.5 and I let SubtitleEdit remove all my customisations...
This means I will have to add all those words again that aren't in the dictionary.

It's a price I want to pay, because my own dictionary clearly had some rotten apples in it.
I have only done a few subtitles since and so far I haven't seen any strange stuff like _"U.S."_ turning the _"S"_ into a music symbol....
I also don't know how it ever got in there.

Anyhow, so far so good....

Can it be made possible in the future to check the custom library.
Something like checking all the words in there using the standard dictionary and a button which lets me remove it.

I've seen the regular expressions for replacements and I understand that you can't make something for that.

**Comment by niksedk** [comment]
SE should not overwrite custom dictionaries.... 
User stuff should be saved in files ending with "_user" (mostly).

Also, you can add words to the SE dictionaries so all SE users can benefit from them.
I regularly check a few English subtitles and update the dictionaries.
