### ISSUE TITLE
4.0.5 ollama server crash with api call 

### ISSUE THREAD

**Issue by zalastone** [SubtitleEdit/subtitleedit#8191]
did anyone have problems running the Ollama server with API calls from subtitle edit 4.0.5
run perfectly in cli but after the translation request ,
it says it requires ollama require server running locally 
 cli error 
"Error: Post "http://127.0.0.1:11434/api/chat": dial tcp 127.0.0.1:11434: connectex: No connection could be made because the target machine actively refused it."
it could be my fault 
 it run ones and then I started getting this problem 
I think I changed the URL  but why crash the ollama server ? 
http://localhost:11434/api/generate/      
model : gemma:7b

**Comment by niksedk** [comment]
Works fine here... 

llama3 should be out soon!
