### ISSUE TITLE
Auto-Translate Feature Not Working Despite API Key and Sufficient Balance

### ISSUE THREAD

**Issue by venomousraid** [SubtitleEdit/subtitleedit#8192]
Hello,

I attempted to use the auto-translate feature provided by Anthropic. I have correctly configured the API key and verified that there is a sufficient balance. However, the translations are not appearing; the output remains blank. Additionally, I noticed that the balance has been deducted as per the dashboard, yet I am unable to receive any translations. Could someone assist me in resolving this issue?

Thank you!

![image](https://github.com/SubtitleEdit/subtitleedit/assets/121519245/8f0f7085-0baa-432d-ae87-b5d587ef55a8)

**Comment by niksedk** [comment]
Thx for the info :)
Looks like a bug... is this better? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by venomousraid** [comment]
Yes, it works fine now. Appreciate it.

**Comment by niksedk** [comment]
Thx for reporting and testing :)
