### ISSUE TITLE
Unbreak/Autobreak buttons to be cropped (blank spaces from sides), text box resizable by height (4 rows), start time cropped for 2-3 characters

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#8196]
These are just cosmetic changes, very easy to implement, and the benefit will be a less claustrophobic text box for subtitle editing in the middle of the SE screen. There is no need text box to be so small, in comparison to the earlier versions. 

I know that new versions of SE have predefined LAYOUTS, and there is no absolute freedom of making the text box smaller or bigger, if we talk about their HEIGHT. We can make them wider, by dragging the video field to the right. At the same time, the UN-BREAK and AUTOBREAK buttons (on the right of the text box) are TOO WIDE, without any reason. They should be cut from both sides, for at least 1 or 2 characters (that width), there is a lot of empty space for nothing. And these buttons have a constant size in all layouts. 

Let's see the comparison of the old version 3.16.13 and the newest 4.0.5.  The old text box gives the feeling of having a lot of space for editing because the text box of the older version had 4 rows for editing, and the new one only 3. 

![Poredjenje sa bojama](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/267d6c37-6b84-4f21-9a04-0157e79cb57d)

I suggest that we should be able to resize the height of the text box to 4 rows, which is not possible now, you can drag the waveform down, but you can't get a bigger textbox than 3 rows. Plus, as I said, the buttons Autobreak/un-break, should be cropped to be smaller, and give the more wider text box, for at least 4 characters. There is no need to have so empty space from both sides of the text on the buttons.  

What do we get with this cropping? Without any dragging of the video to the right, it is predefined that an OLD VERSION can have 36 characters in one line, while the NEW ONE has 31. If two buttons are not so wide, we can get in any layout 35 characters in the NEW VERSION.  

![Smaller button more for text](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/a366fb53-15c2-4481-bffa-8c65573fe375)

We would have a fully customizable text box for editing, if the buttons were less wide, and cropped, and if the text box could be resized by height. The width we can resize by moving the video field to the right/left. That is OK. So, we can customize the text box in all directions and the smaller buttons would give us more space from the very beginning, no matter what layout we use. 

P.S. Let me make another request. LeonCheung is right. The guy who replied to me. I'll repeat his observation. This part, on the left of the text box, also can lose some space. START TIME can lose at least 2 character's width, so it can be added to the text box. 

![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/2bf0bdf5-9fc4-479e-bed9-5cfd5e79bf26)

And we seriously get closer to 43 characters in line, because we can have 37 characters in one row, without disturbing anything in layouts, without moving anything left or right.

**Comment by LeonCheung** [comment]
@Cyberyoda1411 Maybe something discussed in #7422 would solve all problems like this.

And a side note for you, maybe a bit off-topic: If CPL is a must-follow rule for you, you may want to use a mono font (fixed-width font) for text display, so that you can have a better visual judgment on line length by the line width displayed on the screen. e.g. I prefer Ubuntu Mono. FYI.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/50f3e553-899a-42c6-9c36-fa38ee9ff1d0)

BTW, just curious, say, out of 10 projects, how many would you (or everybody) touch the left section **even once**?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/ef20ae6f-c6ad-43aa-a45e-f0a1e72ab4f1)

**Comment by Cyberyoda1411** [comment]
First of all, it must be that you have the monitor for at least 32", if your text boxes are so big. Ubuntu, I don't like it. 

But, your last thing is right. Let people have these options, but START TIME, shouldn't be so wide. We can get at least 2 characters more for the text box, and the space for all layouts. I'll add that to my request.

**Comment by rRobis** [comment]
Maybe just put the Start time, Duration and the prev next buttons in one line above/below the text box

I usually use Duration only because of the #7859

**Comment by Cyberyoda1411** [comment]
I can understand Nikolaj. What we see as 'only' and 'you can fix this easily', is not always like that. It must be that there are predefined standard dimensions of the buttons and this START TIME element, and it is not as easy to crop them as we think it should be. It must be that Nikolaj can do something, but we must know that he doesn't use visual C#, and it can be that these changes require using some other libraries and additional adjusting. 
I know you can do a button in whatever dimension you like if you use Visual C++ or Visual Basic, but I don't know which libraries Nikolaj uses. It can be done, but everything depends on how much work it takes, and if Nikolaj has enough time to investigate the thing. 

Or maybe I am wrong, and Nikolaj will do it in a second, with some other customizations, and surprise us all. Our good and great Nikolaj.

**Comment by Cyberyoda1411** [comment]
I did some research, it seems that Nikolay can use some easy adjusting, by setting attributes for the button sizes. I know that it can be set in Visual C++, but there is no reason that it can't be set in C#, it is a basic button class option.

**Comment by niksedk** [comment]
This is a lot more complicated than you think. Different languages have different width of the text, so for some languages this cannot be done. We also have font scaling that can also be different. And we have Linux systems that works a little different.

**Comment by Cyberyoda1411** [comment]
OK, I just suggest, and you do what you can. That's why your program
is more than unique and great. You are a great person.

**Comment by niksedk** [comment]
Thx, I do not mean to offend, but these things take time...

**Comment by Cyberyoda1411** [comment]
If some things are really complicated, and they don't bring some
totally new functionality, it is not worth of your time. As you say,
what is in Visual C++ just one attribute, width, or in Visual Basic,
on some other platform it can be a lot of work.
