### ISSUE TITLE
How do you train a nOCR db with a font?

### ISSUE THREAD

**Issue by wave-dash** [SubtitleEdit/subtitleedit#8200]
https://www.nikse.dk/subtitleedit/nocr

At the bottom of this page, there's a note that you can "actually train a new nOCR db with your specific font".

Tesseract OCR isn't very accurate, and binary image compare and nOCR both seem impractical because of how tedious it is to input every unique character that's needed. However, my .sup files are high quality and I have very similar fonts, so it seems like automatically importing the characters from a font file and training on them would be a much more efficient way to go. How do I do that?

**Comment by niksedk** [comment]
In the OCR window press Ctrl+T or use the context menu:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/d71e47cf-611a-4a23-93ab-3fd98f4b10cd)

In the training window you must select a subtitle with the letters you want to train "a b c d"... etc - I think it's a good idea to have a space between letters...
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/9aa62ae0-cf1f-4672-aa38-e16b33b4d0c3)

**Comment by wave-dash** [comment]
What do you mean by "a subtitle with the letters you want to train"? Is that a raster subtitle file, like .sup? Or text-based subtitle, like .srt? Or if it's supposed to be a list of characters, could it be a text file with every character I want to train on?

**Comment by Purfview** [comment]
As I remember just srt subtitle with letters.

**Comment by niksedk** [comment]
I used this file
[OCR_TRAIN.zip](https://github.com/SubtitleEdit/subtitleedit/files/15012438/OCR_TRAIN.zip)
