### ISSUE TITLE
Whisper and Translator mode problems

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#8204]
There is a problem with running whisper, while you are in translator mode.

I tried to run it, and it appends the Whisper results to the translated text side, not the original subtitle one.
It should logically be that it will append it to the original, because while translating, it means that the sound will match the original one (or at least there should be a choice presented).

The original side just repeats same sentence again and again.

Also for some reason after appending it to the translate side, it started from 1

**How to recreate the bug:**
1. Run whisper on original file for 10 minutes (let's say we have 20 minutes file) 
2. Auto Translate the file, and it opens translator mode
3. Insert new subtitle in last 10 minutes and run whisper
4. It should add the whisper results to the original subtitles, but it adds it to translated ones and starts from 1.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/07d1477d-3b47-48cf-82b8-4da2d3c4e7c8)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/d2b18d5a-dc45-48d7-b735-f018a0d0fd1a)

**Comment by rRobis** [comment]
So it seems like this can be split in two separate issues: 
1. When running Whisper on selected lines, it starts counting from 1 and disregards the count of the context
2. Whisper should append subtitles to the original subtitle, instead of translated one.

**Comment by rRobis** [comment]
There are some bugs:
1. I make empty subtitle
2. Run Whisper on selected paragraph
3. After Whisper finishes, the newly subtitle disappears.
4. Newly parsed subtitles do not appear in SE List view.
4. Original SRT file now contains empty subtitle that is overlapping the newly parsed subtitles 

Perhaps it doesn't remove the initial empty subtitle, and that's why it doesn't add it to the List view?

I tried on new file, it does the same thing.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/d217a1ef-2ca4-439e-881b-739e62a8292a)

**Comment by niksedk** [comment]
Hm, I do not understand what you mean...
This might be difficult to handle when adding new lines where existing subtitles already exists!

**Comment by niksedk** [comment]
It's really impossible to do the "correct" thing in all situations, but... hopefully a little better: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by rRobis** [comment]
@niksedk 
There is still a bug, but half of the bug is fixed (the part that the new subtitles didn't appear at all)

I made a video to demonstrate the bug from beginning to end. I just took random video as an example from YouTube.

(Reduced the quality of the recording to fit under 10MB )
https://github.com/SubtitleEdit/subtitleedit/assets/19517183/19932ff1-06c3-47ca-8997-e21c3f9e7e4b

**Comment by niksedk** [comment]
Thx for the video :)

Fixed a bug I think: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by rRobis** [comment]
I will test more, but it seems that is fixed now! Thanks! 


btw. While testing, i found a small sidebug. 

When you Auto-translate whole file, it turns the translator mode ON automatically side by side, and you have text boxes for both languages.

BUT - when you have original opened, and you translate **only selected lines,** it opens translator mode, but you can edit only the translated text (there is no original textbox on the right side)

**Comment by niksedk** [comment]
Could you add a video with the "sidebug" too?

**Comment by rRobis** [comment]
Ok seems like it shows clearly, where's the problem

https://github.com/SubtitleEdit/subtitleedit/assets/19517183/a205d2b3-e3c9-4579-a00c-ec8cc0f09ba5

**Comment by niksedk** [comment]
Thx for the new video :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by rRobis** [comment]
Thanks, I tested, everything works as expected now. 🥇

**Comment by niksedk** [comment]
Thx for testing and videos - we did some good work/fixes :)

**Comment by rRobis** [comment]
@niksedk I noticed another small bug.😄

When doing whisper on paragraph between two existing subtitles, the last whisper line seems to overwrite the next subtitle in the list view, but when you do something with that overwritten line, then it becomes what it has to be. 

If you need, i will try to make a video on it in the evening.
