### ISSUE TITLE
Burning videos without subtitle

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8205]
It's very common to use the **Generate burn-in video** tool as a video converter/resizer, so it's would be more humane to allow generating it even without any subtitle line. I mean, instead of: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/f717f115-b445-47f6-8b87-8e508049f700)

It could be: "**No subtitle loaded. Proceed anyway?  [Yes]  [No]**"   :)

**Comment by niksedk** [comment]
He, I also find myself needing this :)
