### ISSUE TITLE
Feature request : mute bad words

### ISSUE THREAD

**Issue by marwanhbt9** [SubtitleEdit/subtitleedit#8206]
Hi subtitle edit community 

I am requesting a feature for subtitle edit, and my specific feature request is to implement a "mute bad words" function. This feature could utilize an online dictionary to identify and mute inappropriate words automatically, or it could allow manual entry of specific words to be muted. The implementation would involve muting the audio clip at the selected word or cutting the clip containing the word and gradually reducing its volume to zero within that clip only. This feature would be particularly useful for the AI speech-to-text (Whisper) version that generates subtitles word by word.

**Comment by niksedk** [comment]
I think this is too specialized, sorry.
