### ISSUE TITLE
[Feature request] Batch mode for burn-in feature

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8210]
If it is possible to implement, please consider adding this, since it's really magic when generating tens or even more files, say (TV/short video series):

A humble UI mockup (GIF):

![demo](https://github.com/SubtitleEdit/subtitleedit/assets/494788/74cb9a80-dafb-40bc-94f8-2246d2aa0770)

After preparing all subtitle files (with the same file names in the same path(s) of the video source), all chosen files could share the same setting, and start burning with a single click. ⚡

**Comment by niksedk** [comment]
Something like this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by MbuguaDavid** [comment]
> Something like this? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

Subtitles are not burned into the video. :( It's just creating a new video without the burned in subtitle. 
Also, there's no way to get out of Batch Mode. Once you click on Batch mode the Batch interface is always on. 

![Batch Mode Icon gone](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/5d67475b-871b-4bc2-9932-a5cfde35d9dc)

**Comment by LeonCheung** [comment]
Brilliant solution! One button, two functions. 👍 Even better than I imagined. XD

Feedback for now:

1. Error occurs when trying to remove item.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/4901e2f7-ccc9-42db-89fa-aec6af02505e)

2. When trying to cancel, something happened like this:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/a674c4a8-5d71-4d42-8edd-5e2e2956a1b7)


3. When there are both SRT and ASSA files detected (same filename), ASSA should be used by default, because in 99.9% cases the ASSA file is generated from SRT for burning purpose.

4. Better show the resolution column as well, for better QC and decisionmaking.
5. Maybe also support custom text other than "_new", e.g. user may prefer adding something like "v2", "English" "small_size", or even other languages. Maybe putting it here:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/b9cceef9-b603-42a8-bbcc-02e9d9752be7)

**Comment by niksedk** [comment]
Thx for testing guys :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
@niksedk A few issues with beta 60:

1. The pick / remove subtitle file option now updates to the Size column.
2. The text "Converted" now updates to Subtitle File column.
3. It seems I was allowed to add the same video to the list many times. Maybe it could better be avoided?

**Comment by niksedk** [comment]
thx @LeonCheung :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

It's still allowed for the same video file multiple times - in case ppl would like that, e.g. with different subtitles.

**Comment by MbuguaDavid** [comment]
When burning videos with different resolutions, it seems the resolution set in the Video section e.g. 1280 x 720 is what is used. This means that a vertical video of say 1080 x 1920 is going to be converted to the resolution set on the interface. This also applies if a video is of a higher resolution 1920 x 1080. 

Is it possible to work with the resolution of the video? Vertical videos are getting converted to landscape videos. :(

 
![Video Resolutions - Batch Burn](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/c667e15c-7aa9-419b-bbda-8c4b0a39ca3d)

**Comment by niksedk** [comment]
@MbuguaDavid: Do you mean an option to keep the existing resolution?

**Comment by MbuguaDavid** [comment]
> @MbuguaDavid: Do you mean an option to keep the existing resolution?

Yes! Maintain the resolution of the video I'm burning subtitles to.

**Comment by niksedk** [comment]
OK, I've tried to make this possible here:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/f63d06b3-0290-44e5-ac0c-aeeb669a2682)

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
> It's still allowed for the same video file multiple times - in case ppl would like that, e.g. with different subtitles.

Ah, right, haven't thought about it, making good sense then. 👍    Btw, just updated my second post, would you help evaluate some of the rest, especially # 6 if it makes some sense?

**Comment by MbuguaDavid** [comment]
> OK, I've tried to make this possible here: ![image](https://private-user-images.githubusercontent.com/1261331/324241542-f63d06b3-0290-44e5-ac0c-aeeb669a2682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTY3ODgsIm5iZiI6MTcxMzY5NjQ4OCwicGF0aCI6Ii8xMjYxMzMxLzMyNDI0MTU0Mi1mNjNkMDZiMy0wMjkwLTQ0ZTUtYWMwYy1hZWViNjY5YTI2ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMTA0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzIyYjk0ODQzZTA1MGVhNzVkZTY2MTRiZmZiNDYwMzMyOTMxZjdjNDQ1NTY2Y2ZmNDUzYTkwMWE5N2RmZDhkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t0qhYvrf-T4MSg4eqtpW62SIyN0lkG89Ak1cOUa-EvE)
> 
> https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

This is much better and it works. Thanks! 
For some strange reason, I'm not getting the subtitles burned into any video I add. hmmm

**Comment by LeonCheung** [comment]
> > OK, I've tried to make this possible here: ![image](https://private-user-images.githubusercontent.com/1261331/324241542-f63d06b3-0290-44e5-ac0c-aeeb669a2682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTY3ODgsIm5iZiI6MTcxMzY5NjQ4OCwicGF0aCI6Ii8xMjYxMzMxLzMyNDI0MTU0Mi1mNjNkMDZiMy0wMjkwLTQ0ZTUtYWMwYy1hZWViNjY5YTI2ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMTA0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzIyYjk0ODQzZTA1MGVhNzVkZTY2MTRiZmZiNDYwMzMyOTMxZjdjNDQ1NTY2Y2ZmNDUzYTkwMWE5N2RmZDhkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t0qhYvrf-T4MSg4eqtpW62SIyN0lkG89Ak1cOUa-EvE)
> > https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
> 
> This is much better and it works. Thanks! For some strange reason, I'm not getting the subtitles burned into any video I add. hmmm

@MbuguaDavid Did it work with previous version? And have you tried a clean installation? Not sure if it's something about parameters with ffmpeg lib on your side. Anyway, just try a clean installation.

**Comment by MbuguaDavid** [comment]
> > > OK, I've tried to make this possible here: ![image](https://private-user-images.githubusercontent.com/1261331/324241542-f63d06b3-0290-44e5-ac0c-aeeb669a2682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTY3ODgsIm5iZiI6MTcxMzY5NjQ4OCwicGF0aCI6Ii8xMjYxMzMxLzMyNDI0MTU0Mi1mNjNkMDZiMy0wMjkwLTQ0ZTUtYWMwYy1hZWViNjY5YTI2ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMTA0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzIyYjk0ODQzZTA1MGVhNzVkZTY2MTRiZmZiNDYwMzMyOTMxZjdjNDQ1NTY2Y2ZmNDUzYTkwMWE5N2RmZDhkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t0qhYvrf-T4MSg4eqtpW62SIyN0lkG89Ak1cOUa-EvE)
> > > https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
> > 
> > 
> > This is much better and it works. Thanks! For some strange reason, I'm not getting the subtitles burned into any video I add. hmmm
> 
> @MbuguaDavid Did it work with previous version? And have you tried a clean installation? Not sure if it's something about parameters with ffmpeg lib on your side. Anyway, just try a clean installation.

I'm working with fresh beta downloads. I'm not sure why the subs are not getting burned in but let me see if it's going to work as it should.

**Comment by LeonCheung** [comment]
@niksedk Ooops, sorry, for some reason it wasn't updated well, one sec.

**Comment by LeonCheung** [comment]
Awkward... now it's updated. 😅 But wow, you already did it!

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/b2a705e7-36a6-4975-a31b-502f76dee5dd)

**Comment by MbuguaDavid** [comment]
> Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
> 
> ![image](https://private-user-images.githubusercontent.com/1261331/324243045-b2a705e7-36a6-4975-a31b-502f76dee5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTgzNjIsIm5iZiI6MTcxMzY5ODA2MiwicGF0aCI6Ii8xMjYxMzMxLzMyNDI0MzA0NS1iMmE3MDVlNy0zNmE2LTQ5NzUtYTMxYi01MDJmNzZkZWU1ZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMTExNDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTY2YjVhN2U4N2QxZGVhYzIyYzFmYWZmMjExNTI1YjZkYmI3MDg3MTM5NzE2NGQwY2Q1NzdiYmYxZWVmN2M2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xEfvGO7n9nTMv3iSx4cbk8I__I9Fl4eV0T7ONHY1V24)

Nice! Is it possible to have an option to save in a custom folder as well?

**Comment by LeonCheung** [comment]
@MbuguaDavid Seems like the same thing to  # 10 in my post.
@niksedk BTW, the custom resolution feature doesn't work in beta 70, just nothing happend.

**Comment by LeonCheung** [comment]
A few more to bother:

1. It's amazing that the list keeps rolling while genrating so that we could monitor which file is currently burning, that's so nice. I just think it's even better to have a {num} of {total} indicator somewhere to know how the whole process goes, e.g.:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/4eabdd8b-b14b-48e4-9a0d-d0a8b03f83da)

2. Something happens when I resize the window:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/c284cc46-0401-4cc6-9600-6037c93790af)

**Comment by LeonCheung** [comment]
And audio files should not be allowed to generate.

**Comment by LeonCheung** [comment]
Another interesting by-product of the tool could be allow extracting audio file for convictive purposes. I mean, there could be three options: **Video only**, **Audio only**,  **Video+Audio**.

I know extracing audio might be kind of beyond the true purpose of this tool, and we can always count on other tools. However, audio is often expected for subtitle workflow when considering performance, file size, and easy collaberation with others.

**Comment by niksedk** [comment]
New beta with more output settings: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/4d9ea133-060d-4c15-9c09-b18f071ee2d5)

**Comment by LeonCheung** [comment]
Nice design, thx so much! BTW, just wonder if the User Source resolution would respect the source resolution of each file individually (making more sense), or using a same resolution for all?

And it cannot be switch back to 0x0, I guess:

![demo](https://github.com/SubtitleEdit/subtitleedit/assets/494788/48238273-f9b3-4c97-b8a3-3946e4e32b62)

**Comment by LeonCheung** [comment]
Reslution display difference:
![res display issue](https://github.com/SubtitleEdit/subtitleedit/assets/494788/13191f3b-958d-4a51-b9c8-365159cc39ad)

**Comment by MbuguaDavid** [comment]
> Reslution display difference: ![res display issue](https://private-user-images.githubusercontent.com/494788/324248705-13191f3b-958d-4a51-b9c8-365159cc39ad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MTYxOTgsIm5iZiI6MTcxMzcxNTg5OCwicGF0aCI6Ii80OTQ3ODgvMzI0MjQ4NzA1LTEzMTkxZjNiLTk1OGQtNGE1MS1iOWM4LTM2NTE1OWNjMzlhZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxNjExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjI3ZTg2Yzc2MGEyNzIyNzE0MTNiNTZhODM3YWI5MWJmNDFiNTc1ZDc1ZjNlNDQxYjk0YWQ3NmM4Yzg0YTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K36DA03uWosFxn8bgDaKRfOpraGNCtDImBpfKaB8Alo) [ ![res display issue](https://private-user-images.githubusercontent.com/494788/324248705-13191f3b-958d-4a51-b9c8-365159cc39ad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MTYxOTgsIm5iZiI6MTcxMzcxNTg5OCwicGF0aCI6Ii80OTQ3ODgvMzI0MjQ4NzA1LTEzMTkxZjNiLTk1OGQtNGE1MS1iOWM4LTM2NTE1OWNjMzlhZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxNjExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjI3ZTg2Yzc2MGEyNzIyNzE0MTNiNTZhODM3YWI5MWJmNDFiNTc1ZDc1ZjNlNDQxYjk0YWQ3NmM4Yzg0YTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K36DA03uWosFxn8bgDaKRfOpraGNCtDImBpfKaB8Alo) ](https://private-user-images.githubusercontent.com/494788/324248705-13191f3b-958d-4a51-b9c8-365159cc39ad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MTYxOTgsIm5iZiI6MTcxMzcxNTg5OCwicGF0aCI6Ii80OTQ3ODgvMzI0MjQ4NzA1LTEzMTkxZjNiLTk1OGQtNGE1MS1iOWM4LTM2NTE1OWNjMzlhZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxNjExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjI3ZTg2Yzc2MGEyNzIyNzE0MTNiNTZhODM3YWI5MWJmNDFiNTc1ZDc1ZjNlNDQxYjk0YWQ3NmM4Yzg0YTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K36DA03uWosFxn8bgDaKRfOpraGNCtDImBpfKaB8Alo) [ ](https://private-user-images.githubusercontent.com/494788/324248705-13191f3b-958d-4a51-b9c8-365159cc39ad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MTYxOTgsIm5iZiI6MTcxMzcxNTg5OCwicGF0aCI6Ii80OTQ3ODgvMzI0MjQ4NzA1LTEzMTkxZjNiLTk1OGQtNGE1MS1iOWM4LTM2NTE1OWNjMzlhZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQxNjExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjI3ZTg2Yzc2MGEyNzIyNzE0MTNiNTZhODM3YWI5MWJmNDFiNTc1ZDc1ZjNlNDQxYjk0YWQ3NmM4Yzg0YTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K36DA03uWosFxn8bgDaKRfOpraGNCtDImBpfKaB8Alo)

When you set "use source resolution" it respects the different resolutions.

E.g. This is the 1st file. It automatically sets the resolution to 1080 x 1920 
![1080](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/e079a9fc-7c78-431d-899a-54546e1cd77e)

And once it moves to the next file of a different resolution 1920 x 1080, it sets that resolution as well.

![1920](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/91921761-c73b-47be-b7a8-b877adf7d898)
Thanks!

**Comment by LeonCheung** [comment]
Hmm, don't know how it looks in the latest beta. IMHO the 0x0 diplay could be a bit difficult for users to understand. Maybe a toggle that disables the resolution input field (turned grey) would make more sense?

**Comment by niksedk** [comment]
> Hmm, don't know how it looks in the latest beta. IMHO the 0x0 diplay could be a bit difficult for users to understand. Maybe a toggle that disables the resolution input field (turned grey) would make more sense?

Yes, you're right. Not a good UI... hopefully a little better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Hi @niksedk, Regarding this issue:

![res display issue](https://github.com/SubtitleEdit/subtitleedit/assets/494788/fd7e8765-bf1e-44a4-9885-c5a262b104ab)

I found it only occurs on those videos that were generated by SE's burning tool... Tested videos generated by other apps, the resolution displayed is correct. FYI

BTW, shall we ignore adding audio to the list?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/391ea9c2-9fe8-4599-b501-d1f4140925cc)

**Comment by LeonCheung** [comment]
@niksedk UPDATE: 
I found that I made a stupid mistake by simply selecting one of the resolution presets and forgot that they are vertical TikTok videos! 😂  You know, the current presets are all for legacy aspects. (**Sidenote: A possible improvement for the preset list needed for that? Or, allow to switch Height and Width values?**)

However, later I found that it doesn't help with the incorrect res display issue. Luckily it's only about display on UI, the file itself is correct.

**Comment by niksedk** [comment]
@LeonCheung: Do we have a bug with the resolution? I did not understand the issue...

Fixed a few issues + added 1080x1920 resolution - I guess that's the most common?

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
@niksedk Sorry for not making that clear, and thanks for the update. I think it's better we only focus on one issue from now on. :)

About the resolution display issue, here is how to recreate:

1. Use the burning tool to burn one or more videos, try using different resolution presets, e.g. from 1920x1080 to 960x720.
2. After burning complete, add the generated video to the list again, and see if the resolution displayed is correct.

**Comment by LeonCheung** [comment]
>Is it only with .mp4 files?

I think so. All previous tests are based on mp4 files. Just tried **mov**, **mkv**, **avi**, they seem working fine. So, what happened? 😂

**Comment by niksedk** [comment]
Seems better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

But it could be some ffmpeg size parameter that should be different or is missing... I will look into this.

**Comment by LeonCheung** [comment]
@niksedk Yes, working fine just very slow loading this time, especially when loading multiple videos. 😢 

BTW, I think we'd better start a new issue for any other possible issues, because this thread is a bit too long. :)

**Comment by amir3dsmax** [comment]
working fine but font change does not applied
