### ISSUE TITLE
Unable to export video with embedded subtitles

### ISSUE THREAD

**Issue by hygorlennon** [SubtitleEdit/subtitleedit#8213]
I am writing to report an issue I am experiencing with the latest version of SubtitleEdit (4.05) on Windows 11. I am unable to export videos with embedded subtitles.

When I click on "Generate subtitles," the following error message appears:

Error: An error occurred while trying to export the subtitle file. 

I have attached an image of the error message to this email.
![Captura de tela 2024-04-17 174357](https://github.com/SubtitleEdit/subtitleedit/assets/148033504/37b6c4d2-7fe1-4871-8623-66601e396379)

I have tried reinstalling SubtitleEdit, but the problem persists. I have also searched for a solution online, but I have not been able to find anything.

I would appreciate it if you could investigate this issue and provide a solution.

Thank you for your time and attention to this matter.

**Comment by niksedk** [comment]
I cannot re-create this... seems to be problem with ffmpeg on your computer. Could be antivirus or something similar.
Sorry, I cannot read Spannish...
