### ISSUE TITLE
Feature request: Need option to choose the audio track in burn-in settings

### ISSUE THREAD

**Issue by zcraber** [SubtitleEdit/subtitleedit#8214]
Currently, the default audio track gets burned even if the desired audio track is selected through `Choose audio track settings`. An option to choose the desired audio track would be useful.

[Reddit discussion](https://www.reddit.com/r/SubtitleEdit/comments/17w0glb/2_audio_tracks_subtitle_burn_in_problem/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by niksedk** [comment]
Something like this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/2e1c3b00-6328-4cb3-b77b-2de83c6f2d3d)

**Comment by zcraber** [comment]
This would be awesome!
