### ISSUE TITLE
SE 4.05 - ASS and tweo font will not be used. The render shows only one used font in the right weight.

### ISSUE THREAD

**Issue by Radrauf** [SubtitleEdit/subtitleedit#8221]
I made a subtitle file in ass style, with two used fonts. When I preview the subtitle, the preview window looks great, but when I export the ass to Blu-Ray sub or XML/PNG all the pictures use the 1. font in my style list "Eurostile". When I change during one subtitle string the fontname, the preview is ok, but the exported picture shows the complete subtitle image in "Eurostile" and not in "Eurostile and Eurostile Black".Can someone help me what is going wrong here?

Also in the Export Review I see that the "Eurostile Black" font is not used. Everything is rendered in "EuroStile" normal.
Also the positions (overlapping some subs) will not be rendered correctly. The position on these are always "bottom".
![17-04-_2024_17-17-58](https://github.com/SubtitleEdit/subtitleedit/assets/42355935/6f58b9aa-e56e-4a58-9f5c-62194cc37c2b)
![17-04-_2024_17-18-43](https://github.com/SubtitleEdit/subtitleedit/assets/42355935/18c85e89-8cbf-4111-b493-8c77656e3481)
![17-04-_2024_17-19-34](https://github.com/SubtitleEdit/subtitleedit/assets/42355935/8fea54b3-958f-4fc6-b136-60ced7ef9aaa)

**Comment by niksedk** [comment]
Could you attach the subtitle? Are the fonts installed on your computer in embedded in the ASSA file?

**Comment by Radrauf** [comment]
Yes they are installed on the computer and they are embedded in the ASS. The preview look exactly as they should, but when it comes to render the 2. Font is gone.
[Example.zip](https://github.com/SubtitleEdit/subtitleedit/files/15047826/Example.zip)
[Eurostile.zip](https://github.com/SubtitleEdit/subtitleedit/files/15047827/Eurostile.zip)

**Comment by niksedk** [comment]
SE only supports TTS fonts.

**Comment by niksedk** [comment]
You could try converting the font to TTF: https://www.google.com/search?q=convert+otf+to+ttf

**Comment by Radrauf** [comment]
Good to know. Is there any place where we can read such details, because I do not find a HELP file or any explanation to the settings. The Online Help do not contained all the settings and the meaning for settings during a dialogue.

**Comment by niksedk** [comment]
Sorry, not everything is documented.

Help file updated a little: https://www.nikse.dk/subtitleedit/help#export

**Comment by Radrauf** [comment]
Thanks. That explaines not the second fault. When I design the subtitle and allow overlapping (for example to place the text free into the image) the preview is ok, but when I render the lines are all placed to the bottomand not the place in the preview). The position is lost after rendering. Can SE not make a single image of the positions that I used in the preview. I think it has something to do with the overlapping.
