### ISSUE TITLE
Feature Request: Make Unknown Word Section Reflect Changes in Word Lists Without Re-OCRing

### ISSUE THREAD

**Issue by RedSoxFan04** [SubtitleEdit/subtitleedit#8227]
Subtitles often have names and words which aren't in the word/name lists. It's great that they can be added to the the word/name lists without having to leave the OCR window, but it would be nice to not have to re-process the subtitles every time I make changes to the word list from the OCR window. Reprocessing can take a minute or two, while simply removing items from the unknown word section would be very quick. 

This improvement would make subtitle conversions quicker and less tedious.

**Comment by niksedk** [comment]
Sorry,  I do not understand what you mean?
Perhaps a few screenshots?

**Comment by RedSoxFan04** [comment]
> Sorry, I do not understand what you mean? Perhaps a few screenshots?

![SubtitleEdit Unknown Words](https://github.com/SubtitleEdit/subtitleedit/assets/13876066/a2793d47-d602-4ee0-9ab8-b7eaf539be81)
![SubtitleEdit Unknown Words - Annotated](https://github.com/SubtitleEdit/subtitleedit/assets/13876066/2fbd4bf5-5e31-47d9-9c81-c370ea6c96bf)

**Comment by niksedk** [comment]
You can right-click in the unknown word box, and remove a word:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/392e45a7-4e8d-49c9-919e-47917bbb8099)

**Comment by RedSoxFan04** [comment]
> You can right-click in the unknown word box, and remove a word:
> 
> ![image](https://private-user-images.githubusercontent.com/1261331/324966362-392e45a7-4e8d-49c9-919e-47917bbb8099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDI0NDEsIm5iZiI6MTcxMzkwMjE0MSwicGF0aCI6Ii8xMjYxMzMxLzMyNDk2NjM2Mi0zOTJlNDVhNy00ZThkLTQ5YzktOTE5ZS00NzkxN2JiYjgwOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTk1NTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI1MmVhNTM4ZjAyMjVhYzc1ZTY0NmEwYTJkNWI5MDEwOTIwZTk5Y2E4YjlhZTA1MGJmNmI1NTEzZDQ4MGU5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gh-IMdUIo8r3ulW18UTw9a18cWBoE3pUtKxECmZJkVI)

Alright, that's pretty good. Still a bit tedious, though. Maybe you could make it possible to remove words with the delete key?
