### ISSUE TITLE
[Feature Request] Join duplicate lines when OCR in the same time frame

### ISSUE THREAD

**Issue by Abu3safeer** [SubtitleEdit/subtitleedit#8228]
Hello Everyone, OCR with Google Vision is a game change feature, I use VideoSubFinder to extracte images.

let me explain in steps, Imagine you have "Hello There" dialogue that starts at 00:01:00 and ends at 00:05:00

some time, when the scene changes the background, it extracts the same text several time with divided timing, the above will become 
"Hello There" = 00:01:00 -> 00:02:00
"Hello There" = 00:02:00 -> 00:03:29
"Hello There" = 00:03:29 -> 00:05:00

The feature I want is to mix these three into one, Subtitle Edit must check the start and the end time, if they are the same text in the same time frame, it should merge them into one dialogue, and take the first one start time, and the last one end time.

Note: There are some cases when the duplicate is more than three, so it should check several times until it find a different text.

**Comment by niksedk** [comment]
You can do this via Tools - Merge lines with same text:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/0fe085d1-0917-4fa3-9dbd-b3545c11e36a)
