### ISSUE TITLE
[Idea] Subtitle Editing View

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#8234]
There could be a view mode, that is basically the same as a single line subtitle text box, but with ability to display all subtitle lines and edit text and add formatting there.

So it would be somewhat a blend between List view and text box (meaning that we see all lines, and we can edit all lines without switching to them).

**Benefits:**
Let's say, if we already know that the subtitles are in-sync (start / end) and we just have to add formatting or color some words, I think it would be faster to just do it from one window, without going through each subtitle line.

**Comment by niksedk** [comment]
Sorry, I do not follow... could you add a screenshot?

**Comment by rRobis** [comment]
Please, let me know, if this makes more sense.

So basically what i'm asking:
A view that allows to edit all subtitle line text without switching to that line (similarly like source view)
It should show BGR color in the brackets (as in text box).
The context menu there should be like text box (so that you could add colors and other formatting)

https://github.com/SubtitleEdit/subtitleedit/assets/19517183/94e6102b-a4e9-42da-9519-a8a54c8c39ee
