### ISSUE TITLE
Shadow looks transparent if border width is set to 0

### ISSUE THREAD

**Issue by pixelhunterX** [SubtitleEdit/subtitleedit#8235]
(reopening issue https://github.com/SubtitleEdit/subtitleedit/issues/6462 and https://github.com/SubtitleEdit/subtitleedit/issues/5866)

Hello there,

for one of my Star Wars subtitle projects, I wanted to create subtitles with a shadow but without a border (to match the original font style used in the film prints).

When I set the border style to width=0 in the Blu-ray SUP export settings, the shadow looks like duplicates of the text with small gaps in between (in both the preview and the exported file). It doesn't matter what font, font size or resolution I choose, the problem still persists (alpha is set to 255).
So far, the only solution seems to be to use a border width of ≥2, which is actually what I'm trying to avoid.

I'd be very happy if someone could investigate this problem!

Here are a few examples:

shadow width 4, border width 0,
![image](https://user-images.githubusercontent.com/119071833/204036666-97f48c46-69d4-4b14-8f51-3ec688deccff.png)

shadow width 12, border width 0 looks even weirder
![image](https://user-images.githubusercontent.com/119071833/204036922-0bb58293-fb75-4b1a-bc44-c0ee2b68352f.png)

border width 2 looks normal
![image](https://user-images.githubusercontent.com/119071833/204037205-f0ea83bb-0ed0-4620-bc4f-37a6827992f6.png)

**Comment by niksedk** [comment]
@pixelhunterX: Is the shadow better in this beta version?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by pixelhunterX** [comment]
Yes, it seems to be fixed in the beta. :)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/119071833/15d9202a-dddb-44fd-8f7c-3406f3e3ebe6)

**Comment by niksedk** [comment]
Cool, thx for verifying :)
