### ISSUE TITLE
Whole Subtitle Edit task is unclickable anywhere when downloads stop without failing (Windows 10)

### ISSUE THREAD

**Issue by StickyChannel92** [SubtitleEdit/subtitleedit#8237]
I am on a Windows 10 machine, to which has a problem where some apps get their connection killed randomly when downloading (except for the internet browser, Opera GX in this case). Unfortunately, the downloads don't fail; they just hang there as if they're downloading without any in-connection.

For the case with Subtitle Edit, if that happens, the window is unclickable. Clicking on it just emits the default Windows warning sound, and can't even be closed. It requires me to use Task Manager to kill the program.

Windows 10 Pro
DESKTOP-0NVBBQ4
Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz
32GB RAM
Nvidia RTX 2060 Super

**Comment by niksedk** [comment]
If I disable the internet I get an instant error... I cannot re-create this.

**Comment by StickyChannel92** [comment]
@niksedk 
Found the problem. Using the button that minimizes every window, to show the desktop, makes the Subtitle Edit windows unclickable. If subtitles are being made, they will still process after that.
