### ISSUE TITLE
auto-parse lyrics with 3-digits for hundredths of a second

### ISSUE THREAD

**Issue by eadmaster** [SubtitleEdit/subtitleedit#8240]
this is a common variation of the [specs here](https://en.wikipedia.org/wiki/LRC_(file_format)):
````
[00:12.566]光る雲を突き抜け
[00:14.958]Fly away fly away
[00:17.730]からだじゅうに
[00:21.559]広がるパノラマ
````

**Comment by niksedk** [comment]
Would that be a whole file with 3 decimals, or a file with mixed two and three decimals together ?

**Comment by eadmaster** [comment]
Usually it's the whole file.

**Comment by niksedk** [comment]
Could you attach a whole file? Github supports .zip files.

**Comment by eadmaster** [comment]
sure, no problem
[Dragon Ball Z OP1 - Cha-La Head-Cha-La.zip](https://github.com/SubtitleEdit/subtitleedit/files/15083935/Dragon.Ball.Z.OP1.-.Cha-La.Head-Cha-La.zip)

**Comment by niksedk** [comment]
Thx fot the file :)

How does this work for you?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by eadmaster** [comment]
yes, it is working fine.

**Comment by niksedk** [comment]
cool :)
