### ISSUE TITLE
Improve list sorting for some tools

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8241]
I think I should open a new issue because it doesn't only occur for Batch Burning.

1. Batch burning list:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/7a7e18fc-0360-4036-aa4f-6fb1cb7148fc)

2. Join subtitles list:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/9c146300-8aa1-4162-bb9b-37967fa91da4)

Sorting matters in both tools, especially for Join subtitles. (it would be great if they behave like the Batch Convert list)

One more issue for Join subtitles: New items cannot be added to the end of the existing list. I mean, each time you add something, the list will shuffle again randomly.

**Comment by niksedk** [comment]
Hm, different issues I think...

**Comment by LeonCheung** [comment]
Okay. Then let's focus the 2nd one:

Is it expected?
![join sub](https://github.com/SubtitleEdit/subtitleedit/assets/494788/970562d0-6513-4c08-ba3a-0902d7bf6759)

I mean how to join subtitles in order?

**Comment by LeonCheung** [comment]
Just noticed it seems the default sorting is by start time rather than file name. Hmm, so maybe this is more like a new feature rather than an issue?
