### ISSUE TITLE
A question about automatic translation

### ISSUE THREAD

**Issue by despairTK** [SubtitleEdit/subtitleedit#8242]
Currently I am using Gemini for automatic translation. When the current subtitle file has a large number of paragraphs (for example, there are 800+ subtitle paragraphs), the text content will be sent to the AI model and then returned in the result. There will be blank lines or it will be translated into other languages, or some sentences will not be fully translated. .

However, if the number of subtitle paragraphs is not particularly large (for example, the number of subtitle paragraphs within 500), the unexpected situation I mentioned above will rarely occur.

Is it possible to provide a setting for automatic translation so that the number of text paragraphs sent can be customized and the maximum number per second can be set to prevent the AI model from being unable to process too much text at a time and causing unexpected situations.

(It is also possible that after Gemini PRO goes online on May 2nd next month, increasing the request limit will solve this problem.)

**Comment by niksedk** [comment]
You can use "Translate single lines" mode:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/797ce83d-47b3-4e2a-b2a2-74f06d9fb47a)

I will try to make something a little more user-friendly soon...
