### ISSUE TITLE
Subtitle edit version 4 and above source view font size too small

### ISSUE THREAD

**Issue by dggrau** [SubtitleEdit/subtitleedit#8245]
In version 3 source view font size matched size in list view. In version 4 it doesn't.

**Comment by niksedk** [comment]
We now have different settings:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/8ddec2c5-2f7e-4733-a989-0f79bd49cef2)

**Comment by dggrau** [comment]
See how small source view font is compared to list view in my org post. Here are my 
 settings.
![Untitled 1](https://github.com/SubtitleEdit/subtitleedit/assets/89820160/fdb56e28-9714-4301-8c23-6a46c64b4e49)

**Comment by dggrau** [comment]
Here are images from Version 3

![list view](https://github.com/SubtitleEdit/subtitleedit/assets/89820160/190dfd53-ab30-471f-8226-af6e6ddf213c)
![source view](https://github.com/SubtitleEdit/subtitleedit/assets/89820160/4617cf6f-1f75-4875-b779-f11075d96a44)
![settings](https://github.com/SubtitleEdit/subtitleedit/assets/89820160/e6b2b750-b4b9-4f1e-9fc7-d26bafbe4b92)
