### ISSUE TITLE
Api Key deepl Pro Error 

### ISSUE THREAD

**Issue by KedaiTubeMsb** [SubtitleEdit/subtitleedit#8246]
![1](https://github.com/SubtitleEdit/subtitleedit/assets/45764771/818e4e5d-8867-47c2-8a69-e1d416ace255)
![2](https://github.com/SubtitleEdit/subtitleedit/assets/45764771/bdf96f5d-dbff-432e-94be-f54e6ddaf338)

**Comment by niksedk** [comment]
I cannot re-create this.

Try re-generating the api key or contacting deepl support
