### ISSUE TITLE
A request: Add new format

### ISSUE THREAD

**Issue by lererledd** [SubtitleEdit/subtitleedit#8247]
![imagen](https://github.com/SubtitleEdit/subtitleedit/assets/153466538/5ada8321-8e3e-48ce-ada6-34e321151d34)

There's a similar format to Whisper that you've added; I hope they add this one as "txt" as well, so it's just copy and paste, and it detects this format. Thank you! @niksedk

**Comment by niksedk** [comment]
Please attach a full sample file - Github supports .zip attachments

**Comment by niksedk** [comment]
@lererledd ping

**Comment by lererledd** [comment]
> How does the time code look after 1 hour?

[Srt whisper.txt](https://github.com/SubtitleEdit/subtitleedit/files/15137215/Srt.whisper.txt)
