### ISSUE TITLE
I just opened the ass file and the style has been modified.

### ISSUE THREAD

**Issue by ShaoXinSen** [SubtitleEdit/subtitleedit#8249]
I reinstalled the latest version and reset the settings. 
But I found that when I open the ass subtitles, the style was modified. I just want to modify the timeline, not the style.

Currently I have rolled back to version 3.6.13 and everything is working fine.

**Comment by niksedk** [comment]
Could you attach sample files and screenshots? You can attach .zip file here on GitHub.

See https://www.nikse.dk/subtitleedit/help#good-github-issue

**Comment by niksedk** [comment]
It works fine here...

**Comment by ShaoXinSen** [comment]
[example.zip](https://github.com/SubtitleEdit/subtitleedit/files/15137617/example.zip)

Sorry, I received the notice from github late. Now I attach the zip file.

**Comment by ShaoXinSen** [comment]
At the same time, I also discovered the key to the problem: 
opening the ass file alone will not cause the style to be automatically modified. 
But when I open it in the movie folder, subtitle automatically changes the style of the ass file for some reason while loading the movie file.

**Comment by niksedk** [comment]
What is changed?

**Comment by ShaoXinSen** [comment]
> 有什么变化？

Mainly the subtitle style. Now I have re-uploaded example.zip. It contains ass and mkv, as well as the automatically modified ass file.
[example.zip](https://github.com/SubtitleEdit/subtitleedit/files/15137701/example.zip)

**Comment by ShaoXinSen** [comment]
![1714209634391_d](https://github.com/SubtitleEdit/subtitleedit/assets/13616801/972a069d-af55-4b4e-bbdb-d139fd7aa4d2)
Unchecked this in settings and now it's fine.

Another question, in the new version, how to hide these areas by default when the subtitle is opened ?
![1714209771507_d](https://github.com/SubtitleEdit/subtitleedit/assets/13616801/6548db3f-8410-4e07-8793-1f92c8fd7a6a)

**Comment by ShaoXinSen** [comment]
Un-dock video controls does not hide them, and a separate window will still be displayed when the subtitle is opened again.
In version 3.x, these can be hidden.
