### ISSUE TITLE
Join subtitle issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8257]
For the 2nd issue in #8241, now I believe it's an issue rather than a new feature discussion. I mean, the "Add end time of previous file " option makes little sense if the "previous" file is not defined as an expected previous one, right?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/60ec2f81-759c-4954-ad17-a52a0790adfe)

**Comment by niksedk** [comment]
Could you explain more and a few more screenshots?

**Comment by LeonCheung** [comment]
Sure:

https://github.com/SubtitleEdit/subtitleedit/assets/494788/47c7f3c2-75f8-488f-871b-52670b656cd4


As see, the result 100% depend on the list order, but the default order is not always expected.

**Comment by LeonCheung** [comment]
@niksedk Ah, I think the list does support **sorting by the filename** when selecting **Adding end time of previous file** which is expected,

However, the bug here is that the list sorting rule doesn't switch respectively when you switch between the two options.

**Comment by niksedk** [comment]
It's seems fine here for me... the "Files already have correct time codes" sorts the smallest start time first which is what is expected most of the time.
[parts.zip](https://github.com/SubtitleEdit/subtitleedit/files/15142624/parts.zip)

**Comment by niksedk** [comment]
Ah, the "Add end time of previouis file" probably could use sort of file name + allow move up/down

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

Should be better now :)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/70550676-82a9-4ed1-8945-2a045f433a5c)

**Comment by LeonCheung** [comment]
Finally, you got my point. I almost start crying. 😂 

Two more things to discuss basted on the beta version:

1. Do you think it would make more sense by automatically switch sorting rules back and forth when switching between the two modes?

2. Could you improve the sorting a bit to make it more acceptable by default? I mean:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/f9b987db-1e1b-4bf7-b0d8-5b96efba3e15)

As shown above, the Windows sorting rule make more sense I bet. (I found the same issue for some other list windows, say, Batch Convert, etc, so maybe this isn't something only related to Join Subtitle tool)

**Comment by niksedk** [comment]
1) Yes, sorting should be completely off when using existing time codes I think.

2) I can try... something like this?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/b9eb0971-e5d0-4ae9-a259-6de21761ff46)


https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
1. Agree, and working nice.
2. I see the decending/ascending filename sorting feature, it's very nice. Thanks! Just a few issues left here. BW, your exmaple file "parts.zip" isn't quite ideal for the purpose of this test because the four files are in the same order, either by starting times or by file name, so I just reset the start time for part4.srt try this [parts-rev.zip](https://github.com/SubtitleEdit/subtitleedit/files/15143009/parts-rev.zip)

ISSUE #1:
Try the following steps:

1. Choose "Files already have correct time codes" **BEFORE** adding any files.
2. Add files, not the list sorting is by start time (COOL).
3. Now, switch to "Add end time of previous file", the list sorting is still by start time, nothing happend (NOT COOL).


Issue #2:

What I really mean is the sorting rule difference:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/ab047778-280a-46d4-a41c-c3171f1f55d4)

I know the current logic may be technically correct, and maybe it's not a problem if filenames are like 001, 002... 100, rather than 1, 2, 3... 100, but the Windows way makes more sense, because it's really common to have filenames already written in the latter case, right?

**Comment by niksedk** [comment]
OK, new beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

Now uses a more natural sort... hopefully.

I do not think SE should auto sort in "Add end time of previous file" mode  - seems to magic/hidden to do so... and we can easily sort now :)

**Comment by LeonCheung** [comment]
@niksedk Thanks for keeping working on this. 🍻 

A few more:

1. Now we finally have the list sorted as expected, but the final joint result seems not. 😂 (after re-decending/ascending the list)
2. Dragging folder(s) is denied (or not supported?)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/33c8fdcf-85a6-469a-a59e-1804ed555ceb)

**Comment by niksedk** [comment]
Hopefully better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip ?

**Comment by LeonCheung** [comment]
So far so good, thanks a lot, though the dropping folder still failed, but not a big problem at all. :)
