### ISSUE TITLE
TTS adding own model missing feature?

### ISSUE THREAD

**Issue by cvrle77** [SubtitleEdit/subtitleedit#8258]
I do not see a way how to add my own Piper voice model (except from overwriting some other model with my own by renaming my model to the model I am replacing) 
Just dropping *.onnx and *onnx.json files in Piper folder, where the rest of the voices are, doesn't do anything.
Any help/help file/option to add voices would be appreciated.

**Comment by niksedk** [comment]
Piper now uses a json voices list like ElevenLabs, so you could add your own voices here.

Also, the voices combo-box now has a "Refresh voices" context menu

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
