### ISSUE TITLE
Auto fixing auto translate 

### ISSUE THREAD

**Issue by rmtjokar** [SubtitleEdit/subtitleedit#8264]
Hi,
Thank you for your great app.
I have a question regarding auto translate feature.
I don't know if this feature exists or not

I'm using Google api v1 as a translator (english to persian)
In Persian we don't speak like the way we write. Spelling a word like "Ba'ra'n"(rain) will be "Ba'roon", in most cases we convert 'A' to 'Ou'.
Is it possible to create a feature for this?

Actually this will be an auto fixing an auto translated text. In another case it's humanize the words like we spoke now (not 200 years ago!)

So this feature should've trigger after a auto translation is done.

With this, we just need a dictionary for correcting words and sentences to be like human.

Thanks in advance.

**Comment by darnn** [comment]
You might want to look into `Edit`->`Multiple replace...`, and into `Tools`->`Fix common errors`, where you have `Fix common OCR errors`, which also uses a list you can edit. These are the ones I use for similar purposes.
