### ISSUE TITLE
Command Create tab/INSERT NEW SUBTITLE AT VIDEO POS should be part of the context menu too

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#8266]
**Correct me if I don't know the process and I will delete my issue.** 
It doesn't matter if you edit some subtitles, or go from scratch to translate, you will need one of the two approaches to **INSERT THE NEW LINE** of the subtitle:
1. You go into the text of the subtitle (below the toolbar), right-click on the desired line, and from the context menu choose INSERT AFTER/BEFORE. You will get the new line of subtitles. 
2. Or, you can position your cursor in the waveform (to create a vertical red line in the waveform, the current position) and go to the button on the left, CREATE TAB/Insert new subtitle at video pos(ition).  

For both of these approaches, you must go to the top of the screen or the distant left side of it. You must go through the whole screen to get the buttons and commands you need. It is tedious if you translate from scratch. To do the same for every new line. 

Can we have (when we position the cursor at a desired position in the waveform) when we right-click, the command INSERT NEW SUBTITLE AT VIDEO POS in the context menu TOO, which is not present now? It would be much more comfortable work, you don't move your mouse across the screen. It doesn't need to have such a long name, but it should have the same function. 
It can be named in the context menu as INSERT NEW LINE HERE. But it will be the same module which does the job when we click the button INSERT NEW SUBTITLE AT VIDEO POS.

![Screenshot_4](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/986c9f1f-f8de-44d4-8f28-121e1c446723)

This command should be here too: 

![Screenshot_2](https://github.com/SubtitleEdit/subtitleedit/assets/128191515/88586ee5-93b3-4f6c-b77c-706948904db9)

**Comment by niksedk** [comment]
Hopefully you're using one of the many shortcuts for this or the mouse in the waveform to make a new selection + "Enter" to add the new selection.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/bc93b861-bda3-4e03-8d1d-d75703a3ed9c)

**Comment by Cyberyoda1411** [comment]
I knew the option with selection + Enter, and even with the shortcuts, it
is less comfortable than right-clicking/inserting a new line (at video
position). Especially if you are going to translate the whole move from
scratch. It is not so nice to use (for instance) SHIFT+F9, you must move
your right hand from the mouse. You must do it through the whole movie of 2
hours. It is more elegant to get the new line with the context menu, it is
a superfast option. And very comfortable. Right-click, the command. There
is nothing better than that.

Especially because it is a 10-minute job for you, to add a command in the
context menu, which will call the routine that is performed when we click
the button INSERT NEW SUBTITLE AT VIDEO POSITION. It seems redundant, but
it is a much easier way to work. Even selection + enter is not as good as
the INSERT NEW line, because you must leave your mouse with your right hand
and go to the keyboard. Every command that is often used, should be more
than comfortable to use.

**Comment by Cyberyoda1411** [comment]
I always think about your work. Will you need 10 hours to implement something I suggested or 10 minutes?   

But now, it doesn't matter if something is a bit redundant if it leads to better comfort. And you really (I think) need just one more command in your context menu, and to call a function which is behind the button INSERT NEW SUBTITLE at the position..., or to cut/paste function from the event clickbutton, but it is not so hard to implement.

**Comment by niksedk** [comment]
A lot more than 10 minutes...

**Comment by Cyberyoda1411** [comment]
Sorry, then forget it.

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by Cyberyoda1411** [comment]
Thank you very much.
