### ISSUE TITLE
Application Error when generating audio to subtitle

### ISSUE THREAD

**Issue by teijiIshida** [SubtitleEdit/subtitleedit#8268]
I'm currently using the "Audio to text" feature to generate subtitle (see picture). My GPU is RTX 3080 FE. Every time it finishes generating the subtitle, I get an error in the Event Viewer. The subtitle (.srt) seem to work fine, but this error is bugging me. Does anyone know what's going on?
![2024-04-27 20_59_27-Untitled - Subtitle Edit 4 0 3](https://github.com/SubtitleEdit/subtitleedit/assets/33733459/b1f35472-b127-417f-b754-b38e3ca59eb3)
![2024-04-27 21_00_58-Event Viewer](https://github.com/SubtitleEdit/subtitleedit/assets/33733459/0fcdc3bd-cb53-44ee-8c81-ab9446a71599)

**Comment by niksedk** [comment]
I do not get those errors... you can also check the file `whisper_log.txt` in the SE data folder.

**Comment by niksedk** [comment]
Also,, not really an SE issue...
