### ISSUE TITLE
Improvements for listing in Batch Burn-in tool ()beta)

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8272]
1. In the latest beta, the resolution seems not right:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/0f442f2e-da31-4bf1-87e9-89c1856dbc8f)

The first and second item in the list should be 720x1280, and the 4th one should be 360 x 640. (I know maybe you are still working on that, so pls ignore this if you do)

2. Can we also support list natural sorting by filename here? I mean like the recent improvement for Join Subtitle tool, It's very useful for quickly targeting video(s) from a very long list, say, if you want to remove them, or pick other subtitle files, or check video info, etc.
3. As shown in the image above, I bet we can exclude all audio files if there are any?

**Comment by niksedk** [comment]
Thx :)
1+2 should now be better: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
