### ISSUE TITLE
Move video Information pop up to context menu

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#8273]
Is there a way to disable the Video information window, when you click on the bar above waveform? 

I sometimes accidentally click it and the video information dialog pops up, sometimes it gets annoying 😁 

Maybe it would be possible to move it to a context menu in that same place, instead of single click?

**Comment by LeonCheung** [comment]
Yes, I also experience this quite often, though it's not a very big deal. You are right, it's a bit confusing and annoying. 😂 

@niksedk, try clicking the area here to re-create:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/d0f1d6b7-f990-4372-989b-e9f84ae294bc)

**Comment by niksedk** [comment]
Ah yes :)
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/68e15511-d900-431b-81d9-d2d2786b258a)
