### ISSUE TITLE
Error message when trying to Cancel/Abort in Batch Burn-in

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8274]
FYI  

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/1d96908b-48d4-424c-82cd-dc71ed7439d4)

**Comment by niksedk** [comment]
Fixed in https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
