### ISSUE TITLE
https://nikse.dk Unavailable

### ISSUE THREAD

**Issue by Martii** [SubtitleEdit/subtitleedit#8276]
You may already know this but just in case.

https://github.com/SubtitleEdit/subtitleedit/blob/7b15d11cc1228601e62de1d9cbacc22925d5d621/README.md?plain=1#L11

https://nikse.dk seems to be currently unavailable:

<a href="https://github.com/SubtitleEdit/subtitleedit/assets/114709/7a7956ca-8796-496a-ba1a-ae0405418cec"><img src="https://github.com/SubtitleEdit/subtitleedit/assets/114709/7a7956ca-8796-496a-ba1a-ae0405418cec" width="121" height="80" alt="20240429_121602 Unavailable" title="Click to enlarge... 20240429_121602 Unavailable"></a>

Thanks for the look.

**Comment by niksedk** [comment]
See https://github.com/SubtitleEdit/subtitleedit/discussions/8267
