### ISSUE TITLE
Bookmark icon in the latest Beta

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#8277]
Is this normal, or is this bug? (When i click on it, it shows the bookmark text)

I'm in translator mode.

I don't remember seeing it, so it must be something new, but the first impression was, that it's somehow not where it should be 😄 

I guess a better place would be under the Prev and next buttons in the free space (or next to them?)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/1377b74e-fbf7-4d74-8e12-88ce72b97a2e)

**Comment by niksedk** [comment]
I can right-align it with the duration box... a little better?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/d8db9871-44b1-4758-beee-b76deaf51b46)

**Comment by rRobis** [comment]
i guess this looks a little better.

Is it in the latest Beta already ? (if yes, then it seems that it didn't change the position)

**Comment by niksedk** [comment]
It's here now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip :)

**Comment by rRobis** [comment]
Ok thanks. I checked it looks good.

The waveform translation is working good too. Very good new feature 😄
