### ISSUE TITLE
[Feature request] "Find All" and/or "Go to line" in Multiple Replace

### ISSUE THREAD

**Issue by rubenalmaguer** [SubtitleEdit/subtitleedit#8284]
Continuously clicking on "Find next" in the Find dialog can be cumbersome. That's why I use Multiple Replace to see all instances of a term at a glance.

The problem is that I have to constantly (1) close the dialog, (2) hit CTRL + G, (3) type the line number, (4) make the changes, and (5) re-open Multiple Replace.

It would be helpful to have the option to **Go to line** in the Lines Found section of Multiple Replace, as a workaround for the lack of a **Find All** option in the Find dialog.

Thank you for your hard work!

**Comment by niksedk** [comment]
Is `F3` for find next not good enough?
