### ISSUE TITLE
Can't OCR with Tesseract3.03 on Linux

### ISSUE THREAD

**Issue by YamashitaRen** [SubtitleEdit/subtitleedit#830]
Hello,
I'm surprised nobody reported it yet (well, I'm facing this bug for 1 year so...) but SubtitleEdit can't OCR pgs/sup (and maybe vobsubs too) with Tesseract 3.03rc1 (and 3.04rc1 too). When I start the OCR, it takes way more time than usual and OCRed lines are orange and "empty".
OCR works perfectly with Tesseract 3.02.02 installed.

edit : I'm using Archlinux and this bug is confirmed on Ubuntu 14.04 iirc.

**Comment by niksedk** [comment]
thx for the info - don't have Ubuntu atm... 

SE acutally just call tesseract via cmd line, like this:
tesseract "someimage.png" "someoutput.txt" -l eng -psm 6 hocr

Could you give the the tesseract cmd line a try and see if you can find a syntax that works?

(a bit annoying that a final has not been released for nearly 3 years)

**Comment by YamashitaRen** [comment]
Ah !
If you use the hocr output, then I think I faced the exact same bug in one of my scripts : Tesseract 3.02 used .html extension when Tesseract >3.03 now uses .hocr extension.
http://pastebin.com/VQ0n5QCV

(yeah project doesn't seem very "dynamic" theses days)

**Comment by niksedk** [comment]
thx for the info :)
Github updated + latest beta uploaded here: http://www.nikse.dk/SubtitleEdit.zip (portable version)
Does it work again?

**Comment by YamashitaRen** [comment]
Latest beta works as expected (except for some tesseract garbage output but I bet this has nothing to do with SE).
And kudos for your reactivity !

**Comment by niksedk** [comment]
cool, thx for your fast responses too :)
