### ISSUE TITLE
How generate Hindi subtitles using whisper models

### ISSUE THREAD

**Issue by mubrimubri** [SubtitleEdit/subtitleedit#8302]
When we generate subtitles for a Hindi language audio or video using whisper models. Subtitle generates in roman script not in Hindi/devnagri script. Please fix it.

**Comment by niksedk** [comment]
Does it work manually via command line?

**Comment by mubrimubri** [comment]
Yes, it works via command line.

**Comment by niksedk** [comment]
Could you attach a sample audio file?
What does `whisper_log.txt` ? Anything about loading srt from file or STD OUT?
