### ISSUE TITLE
Automatic download error

### ISSUE THREAD

**Issue by thuongsugar** [SubtitleEdit/subtitleedit#8310]
I'm a new user, I use win 10 operating system, I tried turning off the firewall but it solved the above problem. I am using subtitle Portable version, 4.0.5

Date: 05/05/2024 12:20:12
SE: 4.0.5.0 - Microsoft Windows NT 10.0.19045.0 - 64-bit
Message: DownloadAsync failed - https://github.com/SubtitleEdit/support-files/releases/download/ffmpeg-2024-03-25/ffmpeg-2024-03-25-git-ecdc94b97f.zip

System.Net.Http.HttpRequestException
Message: An error occurred while sending the request.
StackTrace:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Http.HttpClientDownloader.<DownloadAsync>d__9.MoveNext()
System.Net.WebException
Message: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
StackTrace:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
System.Security.Authentication.AuthenticationException
Message: The remote certificate is invalid according to the validation procedure.
StackTrace:    at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

**Comment by niksedk** [comment]
I cannot re-create this error. 

Can you download the file via a browser? 
Are you getting any SSL certificate errors when browsing GitHub?

Try installing latest updates for your computer.

**Comment by thuongsugar** [comment]
Thanks for the quick response

Q: Can you download the file via a browser?
A: I can download that file directly from my browser
Q:Are you getting any SSL certificate errors when browsing GitHub?
A: no, I still use it normally

**Comment by niksedk** [comment]
Have you installed the latest updates for your computer?

Read more here: https://kinsta.com/knowledgebase/could-not-establish-trust-relationship-for-the-ssl-tls-secure-channel-with-authority/
