### ISSUE TITLE
Frame rate conversion issues with Timed text and IMSC

### ISSUE THREAD

**Issue by ryzen88** [SubtitleEdit/subtitleedit#8312]
Hey, I came across some strange issues regarding frame rate conversion regarding Timed text, IMSC and probably any format that has a frame rate annotation in the the header.

All the examples are with HH:MM:SS:FF
The problem manifests in a couple of different ways. When opening the document the framerate annotation in subtitle edit does not seem to read the FPS form the document. When opening a 30fps document it suggest in the main view that it is 23,976 but displaying values like HH:MM:SS:28 <--- indicates higher FPS than 23,976. When using the frame rate conversion the FPS indicator does switch to the new converted frame rate and displays the subtitle in the new FPS value.
But the FPS in the header documentation remains unchanged at 30 fps. So the FPS in the document needs to be changed manually.
This creates lots of potential issues when working on a subtitle multiple times because it quickly becomes almost impossible to know what the real framerate is of the document.

I have noticed with IMSC it does overwrite the document header if you change the FPS in the program tab but here also it does not Import/display the correct framerate when importing a subtitle.

It would be great if the framerate header could match the document frame rate when opening a subtitle. And if changed also update the document header so to prevent the document from getting warped with wrong values.

![fps2](https://github.com/SubtitleEdit/subtitleedit/assets/111976708/c1e99496-4074-4391-809e-743762857aa9)

![subtitle edit fps](https://github.com/SubtitleEdit/subtitleedit/assets/111976708/86b71183-673d-4d88-b9f3-afafc7090f21)

**Comment by niksedk** [comment]
SE takes frame rate from the video, so the settings are more just for info - improve the frame rate multipler in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by ryzen88** [comment]
Thanks for the improved frame rate multiplier.
We never import the video In SE, we prepare the content in resolve, check, and modify the sub in SE and do the final compilation in IMF tool. 
Sometimes the timecode and frame numbers in SE are going out of sync with the resolve timeline 
but when compiling most of the time everything works out well.
I will keep updating the FPS header manuel in properties tab to make sure it is annotated correctly
But thanks for the response.

**Comment by ryzen88** [comment]
> SE takes frame rate from the video, so the settings are more just for info - improve the frame rate multipler in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

Unfortunatly the Frame rate and multipler seem locked now in the IMSC properties, With Timed text i can still change it in the properties but in IMSC not. unable to click on it or edit it.
![subedit](https://github.com/SubtitleEdit/subtitleedit/assets/111976708/9f8edea0-bb6f-49fc-8545-19061423677f)

**Comment by ryzen88** [comment]
Light mode shows it a bit better about the unavailability of the options
![subedit](https://github.com/SubtitleEdit/subtitleedit/assets/111976708/51a5b3ad-9cbb-4c6a-ac78-6e522f4402bb)

**Comment by niksedk** [comment]
Hm, I'm not really sure what is the best thing to do... but for now I've allowed changing the frame rate when no video is loaded: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

Or should it be allowed also if a video is loaded?

**Comment by ryzen88** [comment]
Hmm We never use it with video, But if i think generally in case if i did. 
The subtile document when annotated with FF has ofcourse its ''own'' Framerate that is annotated in the header (Although that is mostly informative) and regarding de annotation to how many frames are maximally annotated, for example MM:SS:28 can only be 29.97 or higher. But this becomes tricky because at import it does not read out its framerate so it can get a bit messy.
So when the video is imported, technically the framerate of the subtitle file should still be leading, Of the header is correct it should be obvious what frame rate conversion needs to happen then the end result should match the video, and then the header should be adjusted so all matches again. 
But you often find a document already undergone a FPS conversion while the header is not updated and then it more becomes less clear of what needs to happen.

**Comment by niksedk** [comment]
OK, now the dialog always allow changes: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
(and tab-order fixed too)
