### ISSUE TITLE
Use a generic exe name on VLC player selection

### ISSUE THREAD

**Issue by rtritto** [SubtitleEdit/subtitleedit#8319]
## Background
I'm using a portable VLC player and the _exe_ file isn't called as `vlc.exe`.
I need to select the _exe_ path of VLC player (Settings --> Video player --> VLC path --> ...).

## Solution
<img width="542" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/40242971/b9f635bc-0b08-4cf9-8f20-6e3933861629">

On check selection, replace `vlc.exe` with `*.exe` or `vlc.exe`/`*.exe`.

**Comment by niksedk** [comment]
You can type "*.*" in "File name"... why is not called "vlc.exe" ? Did VLC change the file name?

**Comment by rtritto** [comment]
> You can type `*.*` in `File name`... why is not called `vlc.exe` ?

Each Portable app (I'm using PortableApps) has a launcher that isn't called as main launcher of app (`vlc.exe`).
Typing `*.*` in `File name` isn't explicit, it's better to add/change the selection filter.

> Did VLC change the file name?

No.

**Comment by niksedk** [comment]
I'm not really sure, but `./App/vlc/vlc.exe` is probably better - be sure you have `libvlc.dll` in that folder too.

**Comment by niksedk** [comment]
Also, mpv is recommended over vlc as it has better seeking + more features.

vlc 4 hopefully has better seeking than vlc 3, when it's out in a final version - in about 7 years ;)

**Comment by rtritto** [comment]
`*.exe`, instead of `*.*`, should be the right filter.

**Comment by rtritto** [comment]
> I'm not really sure, but `./App/vlc/vlc.exe` is probably better - be sure you have `libvlc.dll` in that folder too.

`./App/vlc` folder contains `libvlc.dll` file.

> vlc 4 hopefully has better seeking than vlc 3, when it's out in a final version - in about 7 years ;)

I'm using VLC v3.

**Comment by niksedk** [comment]
OK, then try with `./App/vlc/vlc.exe`

**Comment by rtritto** [comment]
@niksedk still not fixed (nothing changed) in version 4.0.6 (after https://github.com/SubtitleEdit/subtitleedit/commit/bc6c382a4f7a68fae06a825134588b673e6ad7da was merged)
