### ISSUE TITLE
TTS merging errors

### ISSUE THREAD

**Issue by cvrle77** [SubtitleEdit/subtitleedit#8323]
I've already reported this issue, but it was mentioned in a comment section under a different issue, so it has gone unnoticed.

This is something that happens way too often, in the middle of merging, and causing me loss of LOTS of credits. SE gets stuck in this message, and retry or ignore don't help, I have to cancel the job, losing all my work wasing hours on it, or I can use files from temp folder, and again lose hours putting each audio file on a timeline in video editor.

It isn't just annoying, it's also hitting my pocket. I can't continue my work if it fails like this all the time, because I can't save project.
Please make TTS as a project that can be saved and loaded.

Btw, one way this error happens is if I have only one line of text, but also I have noticed that it never happens if I don't regenerate stuff.
If I regenerate few things here and there, it's almost certain that error will happen. Not sure if file naming is wrong so the SE gets stuck, but something in that line of work isn't correct.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/56ea1885-4e64-4e58-a75b-c980f8fd9107)

**Comment by niksedk** [comment]
The crash should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
