### ISSUE TITLE
Allow clicking "Generate" button for burn-in again

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8332]
I noticed the commit 60680c2, which is quite nice, however the Generate button seems not to work again in either Batch or Single mode. I suppose it is not by design?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/3911f664-6bbe-461d-a269-3341664d42bd)

**Comment by niksedk** [comment]
How is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
