### ISSUE TITLE
"User source resolution" for Burn-in Basic mode

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8334]
Yes, I think it should be consistent with what's like in Batch mode now, because if you messed up with values and want to reset, it seems not very straightforward.  :)

Maybe something like this:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/d86bd482-e4e1-4320-b23a-7b863450d1bd)

**Comment by niksedk** [comment]
Sorry, I do not understand what you mean?

**Comment by niksedk** [comment]
Thx - hopefully working here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Really nice. Thanks for implementing!
