### ISSUE TITLE
Feature Request: Clear list when job has done in batch convert

### ISSUE THREAD

**Issue by gudwls5022** [SubtitleEdit/subtitleedit#8340]
I usually use subtitle edit for subtitle file conversion. In Korea, subtitle files are usually shared as smi, so we have to go through conversion to srt, and subtitle edit performs that function best.
The problem is that even after the file conversion process, the work remains on the list, so you have to press the clear button every time, but it would be really convenient to have the ability to automatically empty the list when the conversion process is completed.
Thank you for your hard work in developing the program.

**Comment by niksedk** [comment]
I think most people would like the list kept, so you can see the status of all files conversions.
