### ISSUE TITLE
Subtitle Preview Options available in the Burn in Window

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#8342]
Is it possible to add some Subtitle Preview Options available when configuring the video player to the burn-in window? 
This would help alot especially for folks that want to match the subtitle preview look to the subtitles they need to burn in without the need to create .ass subtitles. 

See the highlighted section from the image below + the bold option.

![Burn in Window Additions](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/17ce6ee5-a21a-4028-af6d-21e085a1a71e)

Thanks!

**Comment by niksedk** [comment]
Not really room for much - and you can use ASSA... but a few more settings in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/6ee38501-d55c-4916-944a-ab71025ab81d)


If you need more settings, they will have to go into a conext menu...

**Comment by MbuguaDavid** [comment]
> Not really room for much - and you can use ASSA... but a few more settings in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
> 
> ![image](https://private-user-images.githubusercontent.com/1261331/329287509-6ee38501-d55c-4916-944a-ab71025ab81d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjg1MjAsIm5iZiI6MTcxNTI2ODIyMCwicGF0aCI6Ii8xMjYxMzMxLzMyOTI4NzUwOS02ZWUzODUwMS1kNTVjLTQ5MTYtOTQ0YS1hYjcxMDI1YWI4MWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMTUyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njc3ZTJiZDJhNDY4YjFmYjNiODFlOThhZjgyOTM5ZGU2ODY5MjFmMTJjOWNiYzIxODlmN2Y3ZTgxOTNmOTg1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sDw40X0aV_SeTRvRhfyiieqnGHbaN2sTFzlQdT5Yzp0)
> 
> If you need more settings, they will have to go into a conext menu...

This is perfect.
Thank you so much. :)
