### ISSUE TITLE
Important Features

### ISSUE THREAD

**Issue by Maroo1122** [SubtitleEdit/subtitleedit#8346]
Can you add option generate burn in subtitles for movies in blu-ray without loss in quality

**Comment by niksedk** [comment]
Choose a low CRF to minimize quality loss - read more here: http://trac.ffmpeg.org/wiki/Encode/H.264

**Comment by Maroo1122** [comment]
If I burned subtitles to blu-ray movie does it still blu-ray or it changes
I am confused about that
