### ISSUE TITLE
New TTS issues after the update

### ISSUE THREAD

**Issue by cvrle77** [SubtitleEdit/subtitleedit#8348]
TTS goes from quiet to normal loudness, and so is the quality. Lower volume has horrible quality, while loudest part have the best quality, not sure how to describe it, but sibilants are muddy like they've gone through horrible limiter, and are also muddy from compression, but everything sound at the edge of being distorted.

Second issue: Output went from good wav to bad mp3. Return wav output.

Third issue is: if there's only a single line of subtitle that needs to be TTS-ed, program gets stuck when I press generate.

4th issue, previous versions now can't generate anything, program simply gets stuck on generate. 195 works, none after that.

Sending you output in zip file so you can check what I'm talking about. Another 3000 credits destroyed. :/ fml

![image](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/858a3155-6887-41a1-9df7-c9f127dae9bb)

[Plazma kolač sa jagodama.zip](https://github.com/SubtitleEdit/subtitleedit/files/15269663/Plazma.kolac.sa.jagodama.zip)

**Comment by niksedk** [comment]
OK, we're back to wav... did that help?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by cvrle77** [comment]
Nope, here's the message, there's 3 wav, 3 mp3 files, and silence.wav, which is how it should look before it merges all together. So, this is a message that I get, when I hit OK in 'Review audio clips' window, to merge all files in one.

I've also tested one-liner TTS and it doesn't crash, but drops same message, when I want to merge.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/38558a15-6312-40c5-8889-ecaf71a4dafc)

**Comment by niksedk** [comment]
Ah, yes, sorry - should just be fixed: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by cvrle77** [comment]
Oh my god, you jump scared me with this comment, LOL

**Comment by cvrle77** [comment]
Yes, one-liner fixed, now I can generate a single line without crashing, quality is back, and it is merging files properly.

**Comment by niksedk** [comment]
Puh, nice :)

**Comment by cvrle77** [comment]
But we're now also back to mono -.-
Can we have an option like checkbox, to force stereo output when needed? Not to have it as default, mono default is good, Force Stereo Output as an option is best (BUT DO NOT CHANGE TO MP3!!) :D

**Comment by BlueBlue7891** [comment]
The issue I mentioned earlier has also been resolved, thank you very much for your efforts @niksedk
I have another requirement, can I export the content on this page, such as .csv
![image](https://github.com/SubtitleEdit/subtitleedit/assets/169237231/d03af06a-82cb-4282-bbad-f32e6e398478)

**Comment by BlueBlue7891** [comment]
The option for forced stereo cannot be selected

![image](https://github.com/SubtitleEdit/subtitleedit/assets/169237231/73f9cc4f-dffa-4529-88b6-b054a2ed1c2f)

**Comment by cvrle77** [comment]
> The option for forced stereo cannot be selected

You can't select stereo, if there's no subtitle.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/75b53e31-c326-47af-a448-30e7d15b4abc)

**Comment by BlueBlue7891** [comment]
I have loaded the subtitle file, and I have found the reason. When I did not load the video file, this option cannot be selected

**Comment by niksedk** [comment]
The "Stereo" option is only for the final video... why is this needed?

**Comment by cvrle77** [comment]
Stereo option doesn't work. I can select it, but output is still mono.
It is needed for stereo image panning in post processing, and it is time consuming to create stereo from mono in any other way.
Creating it at the source is fastest way possible.

**Comment by niksedk** [comment]
Stereo option should work in latest version - both for final audio file + for final optional merged video file: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by cvrle77** [comment]
But now we are back to mp3, instead of wav, for stereo. :S

**Comment by niksedk** [comment]
> But now we are back to mp3, instead of wav, for stereo. :S

Better with wav?

**Comment by cvrle77** [comment]
Wav is lossless, mp3 is losing quality, each time it is recompressed.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by cvrle77** [comment]
Now it's wav, but mono again :D
![image](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/4a476fac-809a-41b8-9597-91ab324bf53c)

**Comment by niksedk** [comment]
He, you can right-click on the `media file name` in SE and get the media info:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/bcf65762-8c26-49cf-a943-d33507a15310)

**Comment by cvrle77** [comment]
I am getting split results here:

I if **uncheck** '_Add audio to video file_' I get **mono** wav output.
If I **check** that option, I get **stereo** wav output, and video output in mkv container with mono sound.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/177f18f0-52b1-4a86-b071-a5c4ebbd76d9)

**Comment by niksedk** [comment]
Thx, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by cvrle77** [comment]
Well, it's hot mess now.
'Add audio to video file' now doesn't output video. Both options give same result - only audio file.
Force stereo doesn't get saved.
File is named filename_stereo_stereo.wav
But yes, output is stereo.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/6fac8ece-74f5-4e49-bfbe-47af8326ff9f)

**Comment by niksedk** [comment]
Hm, seems ffmpeg gives stereo per default... not too sure, but beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by cvrle77** [comment]
I am not sure what is going on, but 'force stereo' option is completely gone, and sound is mono. 

![image](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/ad6e2698-0dfa-44f6-ac3e-b0c48e652ecd)

**Comment by niksedk** [comment]
I'm getting stereo here... 

Audio output encoding could be a setting in a future version, but ATM I'm readying for SE 4.0.6,

**Comment by cvrle77** [comment]
If you are getting stereo, then I found another bug or you uploaded wrong version of beta, because I've tried several times, and it's always mono.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/cc4953db-46fc-4ae6-9e6e-51262df75b66)
