### ISSUE TITLE
Wrong color shortcuts in version 4.0.5

### ISSUE THREAD

**Issue by tofolcabeza** [SubtitleEdit/subtitleedit#8357]
I've noticed the shortcuts for colours have been wrongly changed to these (#FFFFFF, which is color White, is all over, and color Yellow (#FFFF00) has been removed).

![image](https://github.com/SubtitleEdit/subtitleedit/assets/169604193/97b1667a-f1e7-44da-9804-fe2de7c42db6)

Can anyone assig back Yellow to color 1 (#FFFF00) and then set other colors for color shorcuts 4, 5, 6, 7 and 8 instead of White?

For example:
Color 4 #00FFFF (Cyan)
Color 5 #FF00FF (Magenta)

Thanks in advance.

**Comment by niksedk** [comment]
Try Option - Settings, Restore default settings...

**Comment by tofolcabeza** [comment]
Thanks, it worked. I had to set all the shortcuts again, but it was worth doing so.
