### ISSUE TITLE
Prohibition of the use other than UTF-8 character set in the WebVTT files

### ISSUE THREAD

**Issue by kowpa1990** [SubtitleEdit/subtitleedit#836]
>4.1 WebVTT file structure
>
>A WebVTT file must consist of a WebVTT file body encoded as UTF-8 and labeled with the MIME type text/vtt. [RFC3629]

http://dev.w3.org/html5/webvtt/

These files must be created in accordance with the specification.

**Comment by niksedk** [comment]
OK, SE can force UTF-8... SE writes files and the specs says nothing about UTF-8 BOM header, but it will be included... MIME type is only for web...
