### ISSUE TITLE
2 requirements about TTS

### ISSUE THREAD

**Issue by BlueBlue7891** [SubtitleEdit/subtitleedit#8360]
1.can I export the content on this page, such as .csv

This way, I can easily refer to this content for subsequent work. 
For example,I can clearly see that the sentence has been accelerated, making it easier to cut and replace problematic audio in post-editing software.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/169237231/fcaa96f2-c983-4ea0-bd39-3b1c8fd80eaa)

Another requirement is whether the synthesized audio directory can be customized. Currently, it is automatically stored in a temporary directory.

If these two requirements can be met, I would be extremely grateful.

**Comment by niksedk** [comment]
CSV export added in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by BlueBlue7891** [comment]
CSV export added in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

Thank you very much
