### ISSUE TITLE
TTS - new issue - sound being sped up in preview mode

### ISSUE THREAD

**Issue by cvrle77** [SubtitleEdit/subtitleedit#8361]
This issue isn't often, I've seen it three times, and I cannot reproduce it on demand.
I can only describe it. I am working with ElevenLabs, so I don't know if it happens with other services.

When I hit Generate Speech, and I try to review line by line, speech speed is like 3x faster than it should be. It's like skipping the sample forward, and it sounds sped up. It looks like decoding codec somehow gets broken. But if I go to temp folder and play temp files before the merge, sound is normal. If I merge everything, sound is normal. So it's only the way how it plays them.
The problem is, reviewing the resulting lines becomes impossible, and I have to start all over. 
Again, another credit killer.

**Comment by niksedk** [comment]
I've not seen this... do you have mpv installed?

**Comment by niksedk** [comment]
Also, you can enable CPS in the main list view, and e.g. fix all texts with a CPS higher than 22.

**Comment by niksedk** [comment]
And the export now also list the audio file names

**Comment by niksedk** [comment]
should be more consistent now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

SE allows the voice clips to go a little over the end time, if next subtitle starts further ahead.
