### ISSUE TITLE
Windows Forms Thread Exception 

### ISSUE THREAD

**Issue by RafasJAc** [SubtitleEdit/subtitleedit#8366]
when I try to transcribe audio to text I get this screen 
![imagen_2024-05-13_144539836](https://github.com/SubtitleEdit/subtitleedit/assets/110063855/0cde0dd5-6879-4589-a7ee-437ac06afbe3)

**Comment by niksedk** [comment]
Works fine here... do you have ffmpeg installed in Options - Settings - Waveform?
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/95bd6338-bed0-4a4e-9d73-3b7e678d6ed2)

What kind of video file was your input?
It could also be a damaged video file.

**Comment by RafasJAc** [comment]
oh with the latest version it's fine, thanks
