### ISSUE TITLE
[FR] Add support to MPC-HC Portable

### ISSUE THREAD

**Issue by rtritto** [SubtitleEdit/subtitleedit#8373]
### Section
Settings --> Video player

### Description
Add support to Media Player Classic - Home Cinema Portable

**Comment by niksedk** [comment]
mpv is recommended.

If you really want, you can set `MpcHcLocation` in Settings.xml

**Comment by rtritto** [comment]
Such as VLC, it's needed an input to select the exe file of MPC.
