### ISSUE TITLE
Add selection to portable video engine

### ISSUE THREAD

**Issue by rtritto** [SubtitleEdit/subtitleedit#8374]
### Section
Settings --> Video player

### Description
If a portable path isn't empty, the related video engine needs to be enabled for selection

### Example:
- Add VLC portable path
- `VLC media player` video engine should be enabled

### Current behavior:
`Direct show` video engine is always selected

<img width="636" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/40242971/12368587-3a25-4418-8752-c1b4d9761774">

**Comment by niksedk** [comment]
You have to point to vlc.exe

**Comment by rtritto** [comment]
I can't change selection from DirectShow to VLC

**Comment by BlueBlue7891** [comment]
Just select the folder where vlc.exe is located.

**Comment by rtritto** [comment]
I don't know why but the player isn't loaded.
When I open a video, this popup is opened:

<img width="434" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/40242971/b684f66e-6f41-42a0-9f57-eec17be0b7c8">
