### ISSUE TITLE
Ability to load alternative faster-whisper models

### ISSUE THREAD

**Issue by yairl** [SubtitleEdit/subtitleedit#8377]
Hi,

Whisper is great in some languages, in others not so much.
Sometimes we have a tuned model we'd like to load (example: https://huggingface.co/ivrit-ai/faster-whisper-v2-d3-e3).

Loading it directly with faster_whisper in Linux is trivial:

model = faster_whisper.WhisperModel('ivrit-ai/faster-whisper-v2-d3-e3')

If it would be possible to enable the user to provide their own model path (a huggingface faster-whisper model) instead of only having the hard-coded models, that will be extremely useful for those tweaking the baseline whisper for less common languages.

Many thanks.

**Comment by darnn** [comment]
IIRC, if you click `Open models folder` in the `Audio to text` window with Faster-Whisper selected, the folder will open, and you'll be able to copy downloaded models there (provided you follow the naming scheme).

**Comment by yairl** [comment]
Tried that originally.
Retried after your comment, doing the most minor change - took an existing model faster-whisper-large-v2, and created a matching directory named faster-whisper-large-v4 (just for fun).

The model does not become available under "Choose model"; only way I can think of using it is by opening "Advanced" and adding a --model flag; easy for me but not friendly for more novice users.

What am I doing wrong?

**Comment by darnn** [comment]
Oh, perhaps I'm wrong then. I thought I did it that way, perhaps I was actually using the command line after all.

**Comment by niksedk** [comment]
I've tried to check for custom models in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by yairl-dn** [comment]
Thank you 🙏🏻
