### ISSUE TITLE
Batch Convert / Auto Translate option

### ISSUE THREAD

**Issue by EhabAli84** [SubtitleEdit/subtitleedit#8380]
Hi, 
Thank you for your great work in this application 
i have an issue with the Batch Convert / Auto Translate option 
it have only 
1- liberTranslate 
2-thammegowda-nllb-serve
3-winstxnhdw-nllb-api

all of them not working it shows - Translation Failed

but when i try to translate one file .srt using the Auto-translate (Ctrl+Shift+G) from main menu
it show a lot of other choises such as (Google Translate V1 API) and this one works perfectly

so
can you please add Google Translate V1 API to Batch Convert / Auto Translate option
thanks in advance

**Comment by niksedk** [comment]
Sorry, it's not a good idea to add Google Translate V1 in batch as it has limited quota

**Comment by Kev1n121** [comment]
I have the same problem, I can never get the batch convert working. Tried all the options to translate.
