### ISSUE TITLE
Make this FCE rule smarter a bit

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8386]
TBH, the end period shouldn't be added in these cases:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/e72996a0-292d-4d7f-9c29-1d6bfa2651ce)

**Comment by niksedk** [comment]
Could you add the example subtitle so I can test?

**Comment by LeonCheung** [comment]
Sorry for the late reply. Here it is:
[test.zip](https://github.com/SubtitleEdit/subtitleedit/files/15412477/test.zip)

**Comment by niksedk** [comment]
thx for the file - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
