### ISSUE TITLE
Request to add translation support for Sakura's Japanese model API

### ISSUE THREAD

**Issue by wzgrx** [SubtitleEdit/subtitleedit#8392]
https://github.com/SakuraLLM/Sakura-13B-Galgame

**Comment by niksedk** [comment]
I think this model is already available via LM studio:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/da94778e-761f-44d7-93aa-578c94a0ec8a)

**Comment by wzgrx** [comment]
> LM studio

ok，thx

**Comment by wzgrx** [comment]
> I think this model is already available via LM studio:
> 
> ![image](https://private-user-images.githubusercontent.com/1261331/331859227-da94778e-761f-44d7-93aa-578c94a0ec8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzU1MDAsIm5iZiI6MTcxNjEzNTIwMCwicGF0aCI6Ii8xMjYxMzMxLzMzMTg1OTIyNy1kYTk0Nzc4ZS03NjFmLTQ0ZDctOTNhYS01NzhjOTRhMGVjOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMTYxMzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI0OTFiOGQ5NTg3N2VlODg1YTA3ZjlkM2I0Yjg2ODg5NTNhMTg1ZGJhMThlMjM5M2E0NDU0ZjY4M2U2ZDNiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-vfzdtNGgWxXj5ZrWioGNBYMSuNGfwcfkt06CpRPpbo)
> 
> ![image](https://private-user-images.githubusercontent.com/1261331/331859277-c1a3bffe-8fbd-46e4-8e8b-421b488ea247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzU1MDAsIm5iZiI6MTcxNjEzNTIwMCwicGF0aCI6Ii8xMjYxMzMxLzMzMTg1OTI3Ny1jMWEzYmZmZS04ZmJkLTQ2ZTQtOGU4Yi00MjFiNDg4ZWEyNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMTYxMzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjFlZTUzOTRmZjMxNGJjYThlOGRmZjhkYmQwYzU4ZjkxZmRkODMyMDY0MTIyYTc5MTI3NDBjYjNkMjFkMzI0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xktsuXxUnQ08B9AyRoVtGxK-NvcPe_5-6AX1B-yiCgM)

Hello, I want to ask, how to set up this interface?

**Comment by wzgrx** [comment]
> I think this model is already available via LM studio:
> 
> ![image](https://private-user-images.githubusercontent.com/1261331/331859227-da94778e-761f-44d7-93aa-578c94a0ec8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzU1MDAsIm5iZiI6MTcxNjEzNTIwMCwicGF0aCI6Ii8xMjYxMzMxLzMzMTg1OTIyNy1kYTk0Nzc4ZS03NjFmLTQ0ZDctOTNhYS01NzhjOTRhMGVjOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMTYxMzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI0OTFiOGQ5NTg3N2VlODg1YTA3ZjlkM2I0Yjg2ODg5NTNhMTg1ZGJhMThlMjM5M2E0NDU0ZjY4M2U2ZDNiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-vfzdtNGgWxXj5ZrWioGNBYMSuNGfwcfkt06CpRPpbo)
> 
> ![image](https://private-user-images.githubusercontent.com/1261331/331859277-c1a3bffe-8fbd-46e4-8e8b-421b488ea247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzU1MDAsIm5iZiI6MTcxNjEzNTIwMCwicGF0aCI6Ii8xMjYxMzMxLzMzMTg1OTI3Ny1jMWEzYmZmZS04ZmJkLTQ2ZTQtOGU4Yi00MjFiNDg4ZWEyNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMTYxMzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjFlZTUzOTRmZjMxNGJjYThlOGRmZjhkYmQwYzU4ZjkxZmRkODMyMDY0MTIyYTc5MTI3NDBjYjNkMjFkMzI0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xktsuXxUnQ08B9AyRoVtGxK-NvcPe_5-6AX1B-yiCgM)

Hello, I want to ask, how to set up this interface?
![Snipaste_2024-05-20_00-40-01](https://github.com/SubtitleEdit/subtitleedit/assets/39661556/3684d885-1ab2-4611-82ca-50642de85dad)

**Comment by niksedk** [comment]
You need to click on the green button "Start Server"

**Comment by wzgrx** [comment]
> You need to click on the green button "Start Server"

Hello, lm studio doesn't seem to support the use of Sakura api, can't translate normally, I want to add Sakura's own api call to translate

https://github.com/FishHawk/sakura-launcher/releases/tag/b2859
