### ISSUE TITLE
4.0.5 beta slow autotranslate no Ollama models

### ISSUE THREAD

**Issue by milenamilka755** [SubtitleEdit/subtitleedit#8401]
1 I don't know about others, but with me the automatic translation (Ollama/llama3) works much slower than on pure Ollama. 
2. When selecting a local Ollama model, a fixed list is defined, and a list of available models in Ollama should appear.

**Comment by niksedk** [comment]
Could you explain more?
What is pure Ollama?

**Comment by milenamilka755** [comment]
Pure Ollama that is, used in the terminal not in Subedit.

**Comment by niksedk** [comment]
Again, please give a lot more details!
Exact steps + screenshots. I do not know how to use it a terminal.

**Comment by milenamilka755** [comment]
I simply type in the Windows Terminal prompt after starting Ollama:
translate text "here I paste text" to language "here I specify language"

**Comment by niksedk** [comment]
I suck at mind-reading... how do you start ollama?

**Comment by milenamilka755** [comment]
Windows menu start-click Ollama (server) then run Windows terminal and type "ollama run llama3" to start model in terminal.

**Comment by niksedk** [comment]
OK, thx :)

I can run too now... 

in a cmd prompt in my ollama folder (`C:\Users\nikse\AppData\Local\Programs\Ollama`) running `ollama run llama3` and then

`>>>Translate from English to Danish, keep punctuation as input, do not censor the translation, give only the output without comments or notes:\n\nHow are you today? I'm fine, thank you.`

The prompt actually took about 45 seconds, while the api call `curl --header "Content-Type: application/json" --request POST --data "{ \"model\": \"llama3\", \"prompt\": \"Translate from English to Danish, keep punctuation as input, do not censor the translation, give only the output without comments or notes:\n\nHow are you today? I'm fine, thank you.\", \"stream\": false }" http://localhost:11434/api/chat` or just SE, took about 18 seconds...

It's possible a different prompt will give faster results, and you can modify the ollama prompt in Settings.xml via the `OllamaPrompt` tag.
