### ISSUE TITLE
Método no encontrado: 'System.String

### ISSUE THREAD

**Issue by dasson1960** [SubtitleEdit/subtitleedit#8411]
Nikse.SubtitleEdit.Core.Common.Shortcuts.get_MainVideoText ToSpeech('.
Stack Trace:
en Nikse.SubtitleEdit.Logic.MainShortcuts.SetShortcuts()
en Nikse.SubtitleEdit.Forms.Main.SetShortcuts()
en Nikse.SubtitleEdit.Forms.Main.Main_Shown(Object sender, EventArgs e)
en System.Windows.Forms.Form.OnShown(EventArgs e)
en
System.Windows.Forms.Control.InvokeMarshaledCallbackHelp er(Object obj)
en
System.Threading.ExecutionContext.Runinternal(ExecutionCon text executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
en
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
en
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
en System.Windows.Forms.Control.InvokeMarshaledCallback(Thr
eadMethodEntrytme)
en System.Windows.Forms.Control.InvokeMarshaledCallbacks0

**Comment by niksedk** [comment]
I cannot re-create this.
Try a clean install...
