### ISSUE TITLE
Batch Convert errors out with .sub format

### ISSUE THREAD

**Issue by OlJohnny** [SubtitleEdit/subtitleedit#8413]
Using Batch Convert I just get an error display at the bottom of the Batch Convert window when trying to convert a <code>.sub</code> file.

Just normally OCR'ing the same subtitle file works without any problems.

The error log:
<pre>-----------------------------------------------------------------------------
Date: 05/22/2024 12:33:11
SE: 4.0.5.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: Batch convert took 78

-----------------------------------------------------------------------------
Date: 05/22/2024 12:33:21
SE: 4.0.5.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: Batch convert took 167
</pre>

If you need more information or a sample file, just hit me up!

**Comment by niksedk** [comment]
Hi @OlJohnny, please do attach a sample .sup file that does not work.
(batch ocr of .sub works fine here)

**Comment by OlJohnny** [comment]
okay interesting that it works for you 🤔
for me, it's not working for any <code>.sub</code> file.

for testing i have a [test file](http://s.derjohnny.de/sub-test-file) for you (let me know when you have downloaded it)

**Comment by niksedk** [comment]
> okay interesting that it works for you 🤔 for me, it's not working for any `.sub` file.
> 
> for testing i have a [test file](http://s.derjohnny.de/sub-test-file) for you (let me know when you have downloaded it)

I have the .sub file, thx :)
