### ISSUE TITLE
The uppercase (I) Fix Common Errors issue

### ISSUE THREAD

**Issue by Charvelx04** [SubtitleEdit/subtitleedit#8417]
I thought it was a goof at first... but when fixing a sub, ran across a regression concerning the last option in the Fix Common Errors dialog checkboxes. 

Fix Alone lowercase 'i' to 'I' (English)

It's now turning uppercase I's to lowercase if that I ends a sentence and a period is included.

![2](https://github.com/SubtitleEdit/subtitleedit/assets/35577096/5fd7f8b0-758d-44db-a3e8-11265b10ff84)
![3](https://github.com/SubtitleEdit/subtitleedit/assets/35577096/74d7779e-1d86-4099-b9ab-b181bb37f47c)
![Untitled](https://github.com/SubtitleEdit/subtitleedit/assets/35577096/15ef3f5b-bc19-4414-bf9f-8beb59e7ce47)

**Comment by niksedk** [comment]
Hm, I cannot re-create this. Could you attach the subtitle file?

**Comment by Charvelx04** [comment]
Absolutely.
[From Dusk Till Dawn.zip](https://github.com/SubtitleEdit/subtitleedit/files/15412110/From.Dusk.Till.Dawn.zip)

**Comment by niksedk** [comment]
Thx for the file... it's still working fine here, so you must have an old or bad eng_OCRFixReplaceList file (or user file)...
A clean install would help.

**Comment by Charvelx04** [comment]
You're going to be the death of me, brother.

I just did a clean install to 4.0.3, coming off of the 3 series when I had issues with the music notation and italics... remember? The only upgrade has been from 4.0.3 to 4.0.5. 

I'll add an exception to the lists and keep going... thanks.
