### ISSUE TITLE
Support for Faster-Whisper-XXL

### ISSUE THREAD

**Issue by Purfview** [SubtitleEdit/subtitleedit#8421]
I was asked for that multiple times on my repo, dunno why they don't ask it here.  😃

Dunno if it's easier to support it on the same non XXL engine or as new engine.
It's practically same as non "XXL" with the new features and it's faster on CPU.

Its executable: `faster-whisper-xxl.exe`.
And it's not compatible with "non xxl" cuda libs.

**Comment by niksedk** [comment]
Probably a new engine... I could prompt for manual download and give info about save folder, would that be okay?

(I tried with a native 7zip component and it took 20 minutes to unpack a 500 mb file, so...)

**Comment by rRobis** [comment]
When possible, please, make beta (if it's done already), i want to try it

**Comment by niksedk** [comment]
Included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip

**Comment by rRobis** [comment]
When i switched to the XXL one, it asks whether to download it. It opened the normal Faster Whisper download dialog.

When downloading, it says in the download bar info "Downloading Faster Whisper" without XXL at the end.

Another time I opened it, and it said that i have to download and unpack it myself, and started to download in browser (this was the initial-intended behavior)

Will see how it goes after I download it....

**Comment by niksedk** [comment]
OK, I cannot re-create the first situation...

Files should look like this after unpacking and copying:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/efeeab63-f59e-4043-98ee-cca063b1fb8c)

Also, new beta up where it keeps "--standard" for XXL + engine name combo box a bit wider, so "XXL" fits... : https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip

**Comment by rRobis** [comment]
Exact steps how to reproduce:
1. Open Audio to text (Whisper)
2. Switch to Faster Whisper model  (Seems like it does this only if we had this model picked, didn't try with other ones)
2.1 Make sure that you don't have XXL unpacked
3. Switch to Faster XXL model
4. Dialog pops up asking whether to download Faster Whisper
5. After pressing yes, that first dialog in my previous reply appears
6. After it finishes, open the Audio to text again and it should work as expected.

**Comment by rRobis** [comment]
Besides this small bug, I tried, and it seems to be working as expected.

**Comment by rRobis** [comment]
It seems that after [e94c07b](https://github.com/SubtitleEdit/subtitleedit/commit/e94c07bafac18c5eb480ec7110bbb92a3cfd9a45)
now it's a little bit worse (if beta was generated after it)

It just pops up the first dialog (that i showed in the first image), after finishing, if you try to switch back to XXL it just repeats it, and doesn't give the expected dialog "unpack and copy files...........". 

Now the only way to get it, is if after finishing the first download progress dialog, you exit the audio to text dialog and reenter it, and it asks if you want to download XXL and then it gives the right dialog.

**Comment by JDTR75** [comment]
Hello @niksedk. JFYI, language selection is broken in latest update:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1891941/faf82ad5-c68d-44e4-b341-51af1dbab390)

It's happening both with the old and new Purfview's Whisper engines.

**Comment by JustAndreww** [comment]
Faster-Whisper-XXL is crashing if running from SubtitleEdit, but works fine if running the same command just in terminal. Looks that some environment variables are not being passed corectly?

Is there any reliable way to debug this crash when calling faster whisper (rtx 3060, CUDA 12.1) from SubtitleEdit?

All the files seems to be at the right places:
![image](https://github.com/user-attachments/assets/49ea6693-1b72-4f6b-9398-9eed66ee46b1)

```Date: 09/12/2024 02:21:13
SE: 4.0.8.0 - Microsoft Windows NT 10.0.19045.0 - 64-bit
Message: Calling whisper (Purfview's Faster-Whisper-XXL) with : C:\Users\xxx\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language ru --model "large-v3" --standard --beep_off --vad_alt_method pyannote_v3 --ff_mdx_kim2 "V:\xxx.mkv"
Standalone Faster-Whisper-XXL r192.3.4 running on: CUDA

Warning: 'large-v3' model may produce inferior results, try 'large-v2'!
Audio filtering is in progress...
MDX Kim_Vocal_2 model probably is running on CUDA:   0% | 0/181 | 00:00<<?
<..>
MDX Kim_Vocal_2 model probably is running on CUDA:  99% | 180/181 | 01:31<<00:00
MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 181/181 | 01:31<<00:00
OSError: [WinError 6] The handle is invalid

File "subprocess.py", line 1208, in _make_inheritable

File "subprocess.py", line 1161, in _get_handles

File "subprocess.py", line 808, in __init__

File "ffmpeg\_run.py", line 284, in run_async

File "ffmpeg\_run.py", line 313, in run

File "D:\whisper-fast\_XXL\__main__.py", line 151, in ffmpeg_audio

File "D:\whisper-fast\_XXL\__main__.py", line 1545, in cli

File "D:\whisper-fast\_XXL\__main__.py", line 1668, in <module>

Traceback (most recent call last):

MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 181/181 | 01:32<<00:00

[10900] Failed to execute script '__main__' due to unhandled exception!
Calling whisper Purfview's Faster-Whisper-XXL done in 00:01:49.5258649```


```
Running the same in terminal:
```<DIR_WITH_VIDEO_FILE>"C:\Users\xxx\AppData\Roaming\Subtitle Edit\Wh
isper\Purfview-Whisper-Faster\faster-whisper-xxl.exe" --language ru --model "large-v2" --standard --beep_off --vad_alt_method pyannote_v3 --ff_mdx_kim2 --verbose=true "V:\xxx.mkv"

Standalone Faster-Whisper-XXL r192.3.4 running on: CUDA

Number of visible GPU devices: 1

Supported compute types by GPU: {'bfloat16', 'float16', 'int8', 'int8_float16', 'float32', 'int8_bfloat16', 'int8_float32'}

[2024-09-12 02:32:22.857] [ctranslate2] [thread 21608] [info] CPU: GenuineIntel (SSE4.1=true, AVX=true, AVX2=true, AVX512=false)
[2024-09-12 02:32:22.857] [ctranslate2] [thread 21608] [info]  - Selected ISA: AVX2
[2024-09-12 02:32:22.857] [ctranslate2] [thread 21608] [info]  - Use Intel MKL: true
[2024-09-12 02:32:22.857] [ctranslate2] [thread 21608] [info]  - SGEMM backend: MKL (packed: false)
[2024-09-12 02:32:22.857] [ctranslate2] [thread 21608] [info]  - GEMM_S16 backend: MKL (packed: false)
[2024-09-12 02:32:22.857] [ctranslate2] [thread 21608] [info]  - GEMM_S8 backend: MKL (packed: false, u8s8 preferred: true)
[2024-09-12 02:32:22.857] [ctranslate2] [thread 21608] [info] GPU #0: NVIDIA GeForce RTX 3060 (CC=8.6)
[2024-09-12 02:32:22.857] [ctranslate2] [thread 21608] [info]  - Allow INT8: true
[2024-09-12 02:32:22.857] [ctranslate2] [thread 21608] [info]  - Allow FP16: true (with Tensor Cores: true)
[2024-09-12 02:32:22.857] [ctranslate2] [thread 21608] [info]  - Allow BF16: true
[2024-09-12 02:32:28.524] [ctranslate2] [thread 21608] [info] Using CUDA allocator: cuda_malloc_async
[2024-09-12 02:32:28.920] [ctranslate2] [thread 21608] [info] Loaded model C:\Users\xxx\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\_models\faster-whisper-large-v2 on device cuda:0
[2024-09-12 02:32:28.920] [ctranslate2] [thread 21608] [info]  - Binary version: 6
[2024-09-12 02:32:28.920] [ctranslate2] [thread 21608] [info]  - Model specification revision: 3
[2024-09-12 02:32:28.920] [ctranslate2] [thread 21608] [info]  - Selected compute type: int8_float16

Model loaded in: 6.16 seconds

Audio filtering is in progress...

MDX Kim_Vocal_2 model probably is running on CUDA: 100% | 181/181 | 01:30<<00:00

Audio filtering finished in: 101.17 seconds

Starting work on: V:\xxx.mkv

Processing audio with duration 45:13.120

VAD finished in: 52.22 seconds

VAD filter removed 12:22.769 of audio
VAD filter kept the following audio segments: [00:01.230 -> 00:56.731], [00:58.395 -> 01:02.368], [01:04.711 -> 01:08.497], [02:00.959 -> 02:03.285], [02:32.809 -> 02:36.426], [02:39.142 -> 02:42.623], [02:45.729 -> 03:06.341], [03:08.887 -> 03:13.913], [03:15.628 -> 04:57.326], [05:03.641 -> 05:19.499], [05:21.485 -> 07:11.315], [07:12.521 -> 07:18.293], [07:26.307 -> 07:30.110], [07:34.762 -> 08:36.103], [08:38.021 -> 09:41.757], [09:48.174 -> 09:51.791], [09:55.050 -> 10:18.514], [10:21.060 -> 11:59.957], [12:04.371 -> 12:15.984], [12:30.381 -> 12:44.117], [12:47.206 -> 12:57.818], [12:59.397 -> 13:03.862], [13:07.682 -> 14:02.928], [14:11.587 -> 14:16.782], [14:20.246 -> 14:56.528], [14:59.159 -> 15:02.725], [15:10.008 -> 15:38.039], [15:39.685 -> 15:52.181], [15:53.505 -> 15:57.224], [16:06.731 -> 16:18.276], [16:23.251 -> 16:27.818], [16:31.468 -> 16:42.368], [16:53.319 -> 16:57.173], [16:59.855 -> 17:54.592], [17:57.071 -> 18:13.540], [18:17.631 -> 18:22.708], [18:24.167 -> 20:34.711], [20:37.937 -> 21:04.507], [21:07.461 -> 21:11.231], [21:12.758 -> 22:06.562], [22:08.599 -> 22:20.942], [22:24.286 -> 23:56.511], [23:59.312 -> 24:43.200], [24:45.526 -> 24:47.733], [24:51.213 -> 24:59.346], [25:05.492 -> 25:48.650], [25:56.188 -> 26:07.563], [27:38.310 -> 27:40.585], [27:45.118 -> 27:49.872], [27:55.186 -> 27:57.716], [28:06.459 -> 28:15.288], [28:28.310 -> 28:35.730], [28:43.047 -> 28:46.799], [28:48.344 -> 28:58.446], [29:03.811 -> 29:08.548], [29:09.787 -> 29:23.913], [29:25.797 -> 29:33.641], [29:36.018 -> 29:39.448], [29:59.295 -> 30:05.781], [30:07.953 -> 30:11.078], [30:13.522 -> 30:17.937], [30:22.843 -> 31:17.258], [31:26.324 -> 31:36.697], [31:38.242 -> 31:41.910], [31:45.186 -> 33:06.239], [33:08.599 -> 34:15.068], [34:27.801 -> 34:32.860], [34:35.882 -> 34:41.791], [34:43.777 -> 34:47.784], [34:51.179 -> 34:55.254], [35:09.227 -> 35:31.248], [35:32.639 -> 35:41.706], [35:50.381 -> 35:53.370], [36:22.300 -> 36:26.460], [36:32.843 -> 36:40.823], [36:54.320 -> 37:06.748], [37:09.108 -> 37:13.336], [37:17.512 -> 38:11.265], [38:14.864 -> 38:19.940], [38:39.448 -> 38:48.361], [39:03.879 -> 39:09.125], [39:24.864 -> 39:27.920], [39:30.789 -> 39:34.355], [39:40.670 -> 39:54.066], [39:56.001 -> 40:00.925], [40:02.198 -> 40:05.645], [40:07.767 -> 40:22.164], [40:24.830 -> 40:29.125], [41:12.911 -> 41:25.781], [41:35.271 -> 41:47.954], [41:58.327 -> 42:05.832], [42:07.308 -> 42:10.585], [42:14.847 -> 42:19.023], [42:32.164 -> 42:43.675], [42:46.918 -> 43:11.214], [43:13.149 -> 43:16.086], [43:35.152 -> 43:38.701], [43:48.921 -> 45:08.208]

  Processing segment at 00:00.000
[2024-09-12 02:35:05.989] [ctranslate2] [thread 28524] [info] Loaded cuBLAS library version 12.1.0```

**Comment by niksedk** [comment]
> \Users\xxx\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language ru --model "large-v3" --standard --beep_off --vad_alt_method pyannote_v3 --ff_mdx_kim2 "V:\xxx.mkv"
> Standalone Faster-Whisper-XXL r192.3.4 running on: CUDA

large-v3 vs large-v2?

Note that large-v2 is recommended

**Comment by JustAndreww** [comment]
It doesn't matter actually. If running from SE ffmpeg can't extract audio from video.

**Comment by JustAndreww** [comment]
Should I create a new ticket or how else I can help you with debugging?
Thanks!

**Comment by niksedk** [comment]
Sorry, I do not think this is SE related

**Comment by JustAndreww** [comment]
Well, outside of SE it's working just fine, so SE somehow affects it's behavior, but hard to tell how. OK I got it, thank you for your time anyways :)

**Comment by Purfview** [comment]
>OSError: [WinError 6] The handle is invalid

Can't reproduce your problem with latest beta SE + Latest XXL
