### ISSUE TITLE
No Ollama models on list (auto-translate)

### ISSUE THREAD

**Issue by milenamilka755** [SubtitleEdit/subtitleedit#8425]
When selecting a local Ollama model, a fixed list is defined, NOT a list of available in my PC models in Ollama should appear.
In the case of LM Studio, the list of available models should also appear from the PROGRAM, not a predefined list.

Windows10/SubEdit 4.0.5 beta 295
![2024-05-24_103918](https://github.com/SubtitleEdit/subtitleedit/assets/149798060/430d79b9-5f0b-43f8-866b-87d4e3b4a7a1)

**Comment by niksedk** [comment]
You can type in any model name for now...

**Comment by milenamilka755** [comment]
You can now type in the name of the Ollama model yourself - in SubEdit version 4.0.5 beta 325

In my opinion, SE should retrieve the list itself by executing a command in the background:
ollama list 
and display it in the list of available Ollama models in SE
(similarly for LM Studio)

But thanks for the fix.

**Comment by niksedk** [comment]
Should work in latest SE version.

You can also, right-click on the model combo-box:

![image](https://github.com/user-attachments/assets/770b2267-d8ec-43e1-be73-fdb86b226236)
