### ISSUE TITLE
Buttons have no text

### ISSUE THREAD

**Issue by PureTryOut** [SubtitleEdit/subtitleedit#8427]
I'm running SubtitleEdit 4.0.5 on Linux using Mono 6.12.0.205, and none of the interface buttons have text in them. I sort of figured out which are the most relevant buttons by just pressing them and seeing what they do, but it really makes the whole interface extremely hard to use.

![Screenshot_20240524_234435](https://github.com/SubtitleEdit/subtitleedit/assets/1565836/f0f02700-2099-4f32-aa0b-481c46a3944e)

![Screenshot_20240524_234503](https://github.com/SubtitleEdit/subtitleedit/assets/1565836/e9a1ce1d-421f-4231-acb2-055e9161ee90)

**Comment by niksedk** [comment]
Does it help if you install the `DejaVu Serif` font?

Also check https://www.nikse.dk/subtitleedit/help#linux

**Comment by PureTryOut** [comment]
Huh, yeah missing DejaVu was indeed the problem. Is there no fallback of any kind?

**Comment by niksedk** [comment]
It possible you can manually enter a font name in the "SystemSubtitleFontNameOverride" in the file "Settings.xml"...

**Comment by ivandrofly** [comment]
> Huh, yeah missing DejaVu was indeed the problem. Is there no fallback of any kind?

Interesting... may take a look into it 

Fallback can happen if control graphic'pixel are all white (default background color)
