### ISSUE TITLE
Whisper CPP does not transcribe Japanese correctly

### ISSUE THREAD

**Issue by DeinName** [SubtitleEdit/subtitleedit#8428]
Hello. I recently formatted my PC, installed the latest version of SE (4.0.5.0), and when I tried to use Whisper CPP large-v2 (because it’s the one I always use), for some reason instead of transcribing the audio to text in the Japanese video, it outputs random characters. Is there something I forgot to install or maybe I need to configure something? It seemed strange to me since this is the first time it has happened, and I have formatted my PC several times before without any issues. What can I do? Thanks, and apologies in advance if the solution is simpler than it seems.

Here is the exact message that appears (I only included the first 3 minutes)
I always use Whisper to transcribe audio from Japanese; I don't use the auto-translation feature

> Calling whisper (CPP) with : C:\Users\Ale\AppData\Roaming\Subtitle Edit\Whisper\Cpp\main.exe --language ja --model "C:\Users\Ale\AppData\Roaming\Subtitle Edit\Whisper\Cpp\Models\large-v2.bin" --output-srt --print-progress  "C:\Users\Ale\AppData\Local\Temp\346cef43-2695-4d87-a69f-5de7fcb7dfac.wav"
> 
> whisper_init_from_file_with_params_no_state: loading model from 'C:\Users\Ale\AppData\Roaming\Subtitle Edit\Whisper\Cpp\Models\large-v2.bin'
> 
> whisper_model_load: n_langs       = 99
> 
> whisper_model_load: adding 1608 extra tokens
> 
> whisper_model_load: type          = 5 (large)
> 
> whisper_model_load: qntvr         = 0
> 
> whisper_model_load: ftype         = 1
> 
> whisper_model_load: n_mels        = 80
> 
> whisper_model_load: n_text_layer  = 32
> 
> whisper_model_load: n_text_head   = 20
> 
> whisper_model_load: n_text_state  = 1280
> 
> whisper_model_load: n_text_ctx    = 448
> 
> whisper_model_load: n_audio_layer = 32
> 
> whisper_model_load: n_audio_head  = 20
> 
> whisper_model_load: n_audio_state = 1280
> 
> whisper_model_load: n_audio_ctx   = 1500
> 
> whisper_model_load: n_vocab       = 51865
> 
> whisper_model_load: loading model
> ggml_opencl: device FP16 support: false
> 
> ggml_opencl: selecting device: 'NVIDIA GeForce GTX 1650'
> 
> ggml_opencl: selecting platform: 'NVIDIA CUDA'
> whisper_model_load:      CPU buffer size =  3094.49 MB
> whisper_model_load: model size    = 3093.99 MB
> 
> whisper_init_state: compute buffer (decode) =   99.23 MB
> 
> whisper_init_state: compute buffer (cross)  =    9.38 MB
> 
> whisper_init_state: compute buffer (encode) =  212.42 MB
> 
> whisper_init_state: compute buffer (conv)   =   30.98 MB
> 
> whisper_init_state: kv cross size =  245.76 MB
> 
> whisper_init_state: kv self size  =  220.20 MB
> main: processing 'C:\Users\Ale\AppData\Local\Temp\346cef43-2695-4d87-a69f-5de7fcb7dfac.wav' (27296818 samples, 1706.1 sec), 4 threads, 1 processors, 5 beams + best of 5, lang = ja, task = transcribe, timestamps = 1 ...
> 
> system_info: n_threads = 4 / 6 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0 |
> [00:00:00.000 --> 00:00:25.680]  ,,,,,,,,,,,,,, ,,, ,, , G, , , ,      leg         i             's          .
> [00:00:25.680 --> 00:00:52.780]  , 19, , does, , , ,, , , , , , , , , , , , , , . , , , at,
> [00:01:18.800 --> 00:01:20.080]  , .,.,., ,., , , , , , , , , , ,  pot,  , ., and, ,  G, s, c, ens  eh ,   top, ,-   tent,  , , v, , anything  tent, ,, tent, s, ,  than,  tent, ,,,  , , St, �,  because,     s, .     à ,      ,  的,   is  �  ,.  ,
> 
> [00:01:13.460 --> 00:01:18.800]  ,
> 
> [00:00:52.960 --> 00:01:13.460]  ,
> [00:01:20.440 --> 00:01:23.200]   c, at, at,
> [00:01:23.200 --> 00:01:28.180]  ,
> 
> whisper_print_progress_callback: progress =   5%
> [00:01:28.180 --> 00:01:58.180]  , , ,  , ,, , , , , , , , ,  ,   , , ,   ,  ,  V       ,        , ,   d      ,    eh, , ,  ", .  ,   m           ,     '    , ,                    "     ,   ,   ,  , ,          ,    ,-  ,,      ,  ,    ,       , die, ,  ,
> [00:01:58.180 --> 00:02:24.940]  .,, ,,,,,,,,,,,,,,,,,,, , , , , ,   ,  ,   .                      watching   's    al,
> [00:02:24.940 --> 00:02:54.940]  , 1, , , , , , , , G, , , , , , , , , un, . , , , , , , , , ,l, n, . ,
> 
> whisper_print_progress_callback: progress =  10%
> [00:02:54.940 --> 00:03:24.940]  ,. , , , ,, , ,  ,                ,     ,    ,  ,  ,       , ,  ,        ,   , ,  , ,. , ,, ,     .  , ,    , , , ,,, ,  ,      , ,  ,  z , ,   G     ,   ,,  ,     , ,  ,  ,   is   ,     ,         ,     ,   ,      ,  ,   ,
> [00:03:24.940 --> 00:03:51.460]  ,,,,  Night,, ,  T,  Firstly, . to,  , a ,   what  jo,      sky         .       Logan  S  ., Z
> [00:03:51.460 --> 00:04:08.980]   because- i,

**Comment by niksedk** [comment]
The end of the log is rather important... could you add this too.

You could also test the latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Japanese works fine here with both Whisper CPP and Purfview's Faster Whisper

**Comment by DeinName** [comment]
Sorry, I didn't know that. But how do you view the complete logs? When the transcription process is finished, the window closes and only the transcription appears.
I tried the beta and Whisper CPP large-v2 doesn't work either.
![xdd](https://github.com/SubtitleEdit/subtitleedit/assets/140866753/2f8a5ea7-96a4-400d-a344-e24dfc8970be)

**Comment by niksedk** [comment]
Check the file `whisper_log.txt` in the SE data folder (press Ctrl+Alt+Shift+D in the main window)

You might not have enough RAM, video memory, or your cpu might not have enough features.

**Comment by DeinName** [comment]
It seems strange to me because before formatting my PC, everything was fine. But after formatting and reinstalling all the programs, this error appeared for the first time, and I don't know why.

Here is the full message that appears in whisper_log.txt

> -----------------------------------------------------------------------------
> Date: 05/25/2024 11:48:12
> SE: 4.0.5.326 - Microsoft Windows NT 10.0.19045.0 - 64-bit
> Message: CUDA check reports: CUDA device: 1
> 
> -----------------------------------------------------------------------------
> Date: 05/25/2024 11:51:16
> SE: 4.0.5.326 - Microsoft Windows NT 10.0.19045.0 - 64-bit
> Message: C:\Users\Ale\Downloads\SubtitleEditBeta\Whisper\Cpp\main.exe --language ja --model "C:\Users\Ale\Downloads\SubtitleEditBeta\Whisper\Cpp\Models\large-v2.bin" --output-srt --print-progress  "C:\Users\Ale\AppData\Local\Temp\10704c7e-01f4-4bdc-8d61-105a580a8731.wav"
> 
> -----------------------------------------------------------------------------
> Date: 05/25/2024 14:57:42
> SE: 4.0.5.326 - Microsoft Windows NT 10.0.19045.0 - 64-bit
> Message: Calling whisper (CPP) with : C:\Users\Ale\Downloads\SubtitleEditBeta\Whisper\Cpp\main.exe --language ja --model "C:\Users\Ale\Downloads\SubtitleEditBeta\Whisper\Cpp\Models\large-v2.bin" --output-srt --print-progress  "C:\Users\Ale\AppData\Local\Temp\10704c7e-01f4-4bdc-8d61-105a580a8731.wav"
> 
> whisper_model_load: adding 1608 extra tokens
> 
> whisper_model_load: type          = 5 (large)
> 
> whisper_model_load: qntvr         = 0
> 
> whisper_model_load: ftype         = 1
> 
> whisper_model_load: n_mels        = 80
> 
> whisper_model_load: n_text_layer  = 32
> 
> whisper_model_load: n_text_head   = 20
> 
> whisper_model_load: n_text_state  = 1280
> 
> whisper_model_load: n_text_ctx    = 448
> 
> whisper_model_load: n_audio_layer = 32
> 
> whisper_model_load: n_audio_head  = 20
> 
> whisper_model_load: n_audio_state = 1280
> 
> whisper_model_load: n_audio_ctx   = 1500
> 
> whisper_model_load: n_vocab       = 51865
> 
> whisper_model_load: loading model
> 
> whisper_init_with_params_no_state: dtw        = 0
> 
> whisper_init_with_params_no_state: gpu_device = 0
> 
> whisper_init_with_params_no_state: flash attn = 0
> 
> whisper_init_with_params_no_state: use gpu    = 1
> 
> whisper_init_from_file_with_params_no_state: loading model from 'C:\Users\Ale\Downloads\SubtitleEditBeta\Whisper\Cpp\Models\large-v2.bin'
> 
> whisper_model_load: n_langs       = 99
> ggml_opencl: selecting device: 'NVIDIA GeForce GTX 1650'
> 
> ggml_opencl: selecting platform: 'NVIDIA CUDA'
> whisper_model_load:      CPU total size =  3093.99 MB
> whisper_model_load: model size    = 3093.99 MB
> 
> whisper_init_state: kv self size  =  251.66 MB
> whisper_init_state: compute buffer (decode) =  213.19 MB
> 
> whisper_init_state: compute buffer (cross)  =    9.38 MB
> 
> whisper_init_state: compute buffer (encode) =  926.66 MB
> 
> whisper_init_state: compute buffer (conv)   =   34.82 MB
> 
> whisper_init_state: kv pad  size  =    7.86 MB
> 
> whisper_init_state: kv cross size =  251.66 MB
> main: processing 'C:\Users\Ale\AppData\Local\Temp\10704c7e-01f4-4bdc-8d61-105a580a8731.wav' (27296818 samples, 1706.1 sec), 4 threads, 1 processors, 5 beams + best of 5, lang = ja, task = transcribe, timestamps = 1 ...
> 
> system_info: n_threads = 4 / 6 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0
> [00:00:00.000 --> 00:00:30.000]  , ,, ,,,,,,,,,,,,,,,,,, , , ,,   , ,      sais            R          possibly       mountain       ,  skill     tent    , by,,, , ,,  .   ,  kn, in  .      ,           ,   , ,  's      , ,  ,     just   , N,    .       ,   .  ,   than,    from               than   ,     R
> [00:00:30.000 --> 00:00:57.120]  ,
> [00:00:57.480 --> 00:01:16.800]   in no
> [00:01:44.360 --> 00:01:44.520]  ,
> 
> [00:01:43.920 --> 00:01:44.360]
> 
> [00:01:43.920 --> 00:01:43.920]
> 
> [00:01:42.580 --> 00:01:43.920]
> 
> [00:01:16.800 --> 00:01:42.580]  , lightning,
> 
> whisper_print_progress_callback: progress =   6%
> [00:01:44.520 --> 00:02:14.520]  ,s
> [00:02:14.520 --> 00:02:44.520]  ,    ,   ,  ,       ,  ,   ,               ,        , ,  , nuit ,  ,  ,ideo, ,, , ,   ", ,,        ,              ,                    in       Lo    .      c,          ,      -, s        ,  ,      ,       Na     , n    ,          ,
> whisper_print_progress_callback: progress =  11%
> 
> [00:02:44.520 --> 00:03:11.640]  ,lo,à,
> [00:03:11.960 --> 00:03:27.920]  ,
> [00:03:31.280 --> 00:03:54.680]  ,
> whisper_print_progress_callback: progress =  15%
> 
> [00:03:56.080 --> 00:04:26.080]  ,  un, ,, , , , ,, , , , , , , , ,  . ,  , , ,          i,  ,      ,     the     ,   fr     ,   ,  ,. , ,  ,  D , , ,  ,  .,  close,  , nt  ,  ,   ,  ,      ,       ,   ,   , ,     ,   .      ,   ,,  ,   ,   ,   ,   ,  ,  , ,  nt,  ,
> [00:04:26.080 --> 00:04:56.080]  ,, n,  m,  , , , ,  , , , , ,  , , ,  , , ,    .           and ,      ,   is,  is,     .  . . .,,  .  stitch, , m. , , g,, , ,  eh  ,  , , ,  , m, ,   , ,     ,  ,    ,    ,   ,          ,       ,  to, ,     s,, ,   ,    .   ,    ,  ,  , v,
> [00:04:56.080 --> 00:05:23.200]  ., ,  , , , , , ,  , , , , , ,  , , , ,     ,  ,           N,            than- to       N...  ,     lists,  ,  ,        ,    -, ,-    ,  S, ,   ,    ,  ,   v     ,     wh    ,
> [00:05:23.200 --> 00:05:52.720]  ,,,, ,,,,,,,,,,,  ton,lo,
> 
> whisper_print_progress_callback: progress =  20%
> [00:05:52.720 --> 00:06:15.400]  , g, g,., , ., , ,  , ,   , , , ,   , ,   and,  i      a   's   g, ,      mientras  -  P  to  m,
> [00:06:16.000 --> 00:06:39.760]  , already, as,ly
> [00:07:04.880 --> 00:07:07.600]   eh, eh, perspective
> 
> [00:06:42.400 --> 00:07:04.880]   , - , - ,  , , ,, , ,  ,  , ,  ,   , ,   suit,  à  U   already, ,. s,
> 
> [00:06:39.760 --> 00:06:42.400]  ,
> 
> whisper_print_progress_callback: progress =  25%
> [00:07:07.600 --> 00:07:26.080]  ,
> [00:07:32.560 --> 00:07:50.880]  ,� ,
> [00:07:50.880 --> 00:07:54.120]   N So N
> [00:07:54.120 --> 00:08:12.600]  ,
> whisper_print_progress_callback: progress =  30%
> 
> [00:08:12.600 --> 00:08:39.400]   n,
> [00:08:40.080 --> 00:09:04.040]  ,
> [00:09:06.680 --> 00:09:36.680]  ,.,n
> [00:09:36.680 --> 00:10:01.020]  ,
> 
> whisper_print_progress_callback: progress =  35%
> [00:10:01.800 --> 00:10:31.800]  ,  F, ,   , ,  ,  , ,   ,    mim,   ,s,    , ,  ,    ,  ,    , s, , ,    , ,   ,  , ,      ,  ,  ,    ,            ,                      ,  ,       ,  ,       , ,               ,             ,                 ,    -   ,
> [00:10:31.800 --> 00:11:01.800]   so to...
> [00:11:01.800 --> 00:11:19.320]  ,
> [00:11:19.320 --> 00:11:49.320]  ,, nt, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n, n,, n,n,, n,n,s,m,nt,r,,y,s,y,d,n,n,s,n,s,n,n,n,s,g,y,n,  ,y,  , ,  ,  ,  ,  , , ,  , , , , , , , , , , , ,, , ,, , , ,, ,,  ,,  ,, mus    .        , , ,      ,     ,     ,    , ,    eh,
> 
> whisper_print_progress_callback: progress =  41%
> [00:11:49.320 --> 00:11:51.880]   t z, the, the, the, the, the, the, the, the, the, the, the, se, al,
> [00:11:51.880 --> 00:12:09.600]  ,,,,,,,,,,,,,,,,,,,,,,,
> [00:12:09.600 --> 00:12:35.400]  ,0,,men,
> [00:13:01.680 --> 00:13:06.080]  , ás, � G u, .
> 
> [00:12:59.500 --> 00:13:01.680]   sp,
> 
> [00:12:36.720 --> 00:12:59.500]  ,
> 
> whisper_print_progress_callback: progress =  46%
> [00:13:06.080 --> 00:13:32.440]  ,
> [00:13:58.160 --> 00:14:02.160]    might ,  Gwen, 's,  stitches. �
> 
> [00:13:55.160 --> 00:13:58.160]
> 
> [00:13:50.720 --> 00:13:55.160]
> 
> [00:13:32.440 --> 00:13:50.720]  ,
> [00:14:02.160 --> 00:14:04.720]  ,,,,
> [00:14:04.720 --> 00:14:07.960]  ,
> [00:14:07.960 --> 00:14:37.960]   to do do do d
> 
> whisper_print_progress_callback: progress =  51%
> [00:14:37.960 --> 00:15:07.960]   will you wil you wil you will you will you will you will you will you will you will you will you will you will you will you will you will you will you will you will you will you will you will you will you will you
> [00:15:07.960 --> 00:15:34.160]  .
> [00:15:35.320 --> 00:16:03.940]   in  s   r     ,                         à         ,           to           "   ,    ,    "    st  .  ,   ,   ,
> 
> whisper_print_progress_callback: progress =  56%
> [00:16:03.940 --> 00:16:33.940]   N 's.           ,                            V   - , ,  -, , ,,   ", ,  is , , ... -    ,,  it ,   z    �       , ,     ,   是     - ,          S     ,
> [00:16:33.940 --> 00:16:38.740]  ,s, K,
> [00:17:04.060 --> 00:17:25.740]
> 
> [00:17:01.460 --> 00:17:04.060]  , gain, , , ,., , , , , , , , , , ,,  , , , , ,  ,,   , z, Sim, with,
> 
> whisper_print_progress_callback: progress =  61%
> [00:17:25.740 --> 00:17:50.900]  ,ip, and, , ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, , , , , , ,                                  and      attempting,
> [00:18:09.660 --> 00:18:12.620]  y
> 
> [00:17:50.900 --> 00:18:09.660]   me
> whisper_print_progress_callback: progress =  65%
> 
> [00:18:12.620 --> 00:18:31.100]  ,,,, ,,,,,,,,,,,, , , , , , , , , , , , ...
> [00:18:31.100 --> 00:18:35.700]  ,,,,,,,,,,,,,,,,,,,,,,,,
> [00:18:35.700 --> 00:19:05.700]   d d d
> [00:19:05.700 --> 00:19:10.260]  ,
> [00:19:10.260 --> 00:19:40.260]  , """""""""""""""
> [00:19:40.260 --> 00:20:07.220]  ., .,,,,,,,,,,,,,,,,,,,,,,,, ,,,,,, , , ,./,  in, the,v, to,
> 
> whisper_print_progress_callback: progress =  70%
> [00:20:09.180 --> 00:20:26.940]   .
> 
> [00:20:07.620 --> 00:20:09.180]  ,
> [00:20:26.940 --> 00:20:56.940]  .,  S, , ,  , , ,, , , , , , , , , , ,  ,  ,  ,  ,   , , ,    ,  ,   外,  ,   aspect,  .  ,  ,. , ,,,  isn, ,     tent, ,  ,    with,   ,    , ,  because.  ., Dr,  , , 'd,  ,   tent ,   t ,  t,   .   ,  , ,       *   ,        ,  ,  z     g   ,   ,,  , .,
> [00:20:56.940 --> 00:20:59.500]  ,,,, to, n, to,ol, to, in, to, to, sta, i, g
> [00:20:59.500 --> 00:21:05.060]  ,
> [00:21:05.060 --> 00:21:08.420]   G, T, you, N, G,, and, ",
> [00:21:08.420 --> 00:21:11.020]  -...- , , ,, , , ,, , ,  , ,   ,   ,   ,      ,  N       then      ,,      wh,,
> 
> whisper_print_progress_callback: progress =  75%
> 
> [00:21:32.180 --> 00:21:35.780]
> 
> [00:21:11.020 --> 00:21:32.180]    tomb -   Long.
> [00:21:35.780 --> 00:22:05.780]  ,n
> [00:22:05.780 --> 00:22:35.780]  ,、,、, 、 、 、 、 、 、 、 、 、 、 、 、 � 、 、 、 、 、 、 、 、 、 、 , 、 …
> [00:22:35.780 --> 00:22:40.340]  .,       ,   ,          ,       , ,,   , , sp,
> 
> whisper_print_progress_callback: progress =  80%
> [00:22:59.900 --> 00:23:29.900]  , seams, , ,  , ,                    ,        , ,    , , ,   , ,,    , ,,, , ,   ,        ,   ,,     . ,      ,   ,,   ,  ,,  ,  , , ,       'd ,  , , ,  ,      ,     ,   ,   ,  ,      , ,    , ,      ,     , ,  -  ,     G ,  ,
> [00:23:29.900 --> 00:23:55.740]  ,,, -,.,, ,, , , ,, ,  ,  , ,    ,  ,                   3       leg    , 's   , I  em,
> [00:23:55.740 --> 00:24:09.740]  , because, what,,, to,s N,
> whisper_print_progress_callback: progress =  86%
> 
> [00:24:09.740 --> 00:24:37.260]  , Ra/  , ,   ,         ,       s, ,       z, , as  i   -    , municip , gro,
> [00:24:37.300 --> 00:25:00.740]  , from, , ,, , , , ,,,   , , ,,  , �,     st        nt,   , Na    any ,  plan,   g   v   Co  . ,, s'd,
> [00:25:00.740 --> 00:25:25.300]  , dB,  ,  , , , , , , , , , , , ,  ,  , ,   , ,   , g ,   ,  possibly,   . устить   's  dream         -  v    �  ,   's  ,  .   ,    G,   ",, ,  , by ,, ,  ,          ,    i,        ,, ,  ,   rout
> [00:25:26.460 --> 00:25:44.820]  ,,
> 
> whisper_print_progress_callback: progress =  90%
> [00:25:44.820 --> 00:25:47.420]  ,
> [00:25:47.420 --> 00:26:17.420]  ,  , ,, , , , , , , , , , , ,   ,  ,    ,            ,        ,  - ,  ç          tent     ,      to  i- �   st     Ge ,   Wh ,    ,   as    , ,  ,  ,     ,   ,  ,,   ,  ,  , ,     , , ,,,    ,  ,    ,    , ,,  ,   ,  ,   ,     ,  ,
> [00:26:17.420 --> 00:26:42.860]  , or, wants, g, ,, , , , , , , ,  ,  ,  ,                  N      from                     early
> [00:26:42.860 --> 00:26:45.260]  , . , , , , , , ,  ,  , ,      ,     ,     it             Joseph me     n sp- ,
> 
> whisper_print_progress_callback: progress =  95%
> 
> [00:26:45.260 --> 00:27:09.460]  - ,, -lo,-
> [00:27:09.460 --> 00:27:39.460]  , would, se, ens,  , as, , , , , , , , , , , , , ,  , ,  ,  ,    ,                       .            .  ,  ,  .      ,     «  ,   , , , ,     ,    ,  ,            ,                ,    ,            ,       tent             ,        ,
> [00:27:39.460 --> 00:28:03.220]   n,
> whisper_print_timings:    total time = 11179607.00 ms
> 
> whisper_print_timings:   prompt time = 107015.86 ms /  5094 runs (   21.01 ms per run)
> 
> whisper_print_timings:   batchd time = 9336987.00 ms / 270826 runs (   34.48 ms per run)
> 
> whisper_print_timings:   decode time = 854760.56 ms / 10451 runs (   81.79 ms per run)
> 
> whisper_print_timings:   encode time = 675153.81 ms /    74 runs ( 9123.70 ms per run)
> 
> whisper_print_timings:   sample time = 199198.81 ms / 281824 runs (    0.71 ms per run)
> 
> whisper_print_timings:      mel time =  1525.31 ms
> 
> whisper_print_timings:     fallbacks = 369 p / 145 h
> 
> whisper_print_timings:     load time =  4212.12 ms
> 
> output_srt: saving output to 'C:\Users\Ale\AppData\Local\Temp\10704c7e-01f4-4bdc-8d61-105a580a8731.wav.srt'
> 
> whisper_print_progress_callback: progress = 100%
> 
> [00:28:20.540 --> 00:28:29.600]
> 
> [00:28:20.060 --> 00:28:20.540]
> 
> [00:28:06.820 --> 00:28:20.060]   their
> Calling whisper CPP done in 03:06:20.0895368
> Loading result from C:\Users\Ale\AppData\Local\Temp\10704c7e-01f4-4bdc-8d61-105a580a8731.wav.srt

**Comment by niksedk** [comment]
Looks fine to me. You could try Purfview's Faster Whisper - is that better?
Did you try the beta?

**Comment by DeinName** [comment]
Yes sir, I use the beta version. I also just tried Purfview's Faster Whisper, and it does work. It transcribes Japanese audio to text, but it’s not as accurate as CPP (at least in my case, it misses dialogues that CPP detects), which is why I always use CPP.
So, is there no possible solution with CPP? I tried uninstalling and reinstalling SE three times, but CPP still doesn't work.

**Comment by niksedk** [comment]
CPP and Japanese characters works fine here.
You could try setting device to CPU via advanced parameters, and see if that helps.
