### ISSUE TITLE
No resolution set for ASS files, when batch generating whisper subtitles

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#8434]
The exported files from batch whisper generator are 0 x 0 resolution and have to be set manually in ASSA properties.

Would be great if it could pick the resolution from the video, that you generated the subtitles from during the generation (if it was generated from video)

**Comment by niksedk** [comment]
He, how do you generate ASSA files?

**Comment by rRobis** [comment]
In this case I did it like this:

1. Opened already created subtitles.ass file.
2. Opened Whisper Audio to Text in Batch Mode
3. Dropped all the .mp4 files in the batch input window
4. Generate
5. After finishing, SE saves .ass files in the same directory as each mp4 file is in.
(if there is already a subtitle.ass file, it adds some random string in between, if not, then saved as subtitles.ass)

**Comment by niksedk** [comment]
You have ASSA as default subtitle format?

**Comment by rRobis** [comment]
> You have ASSA as default subtitle format?

Yes. But my intention was to generate ass files, so the only problem was that resolution was 0 x 0, in the generated files (it didn't take the resolution from the files that i generated the ass files from).

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
