### ISSUE TITLE
Mouse Click Issue

### ISSUE THREAD

**Issue by amir385276** [SubtitleEdit/subtitleedit#8435]
Hi Support Team
after we change something on the srt file, then click mouse do the redo change on srt file

you can test it.
change the color then click on program and you can see the first line all changes are removed.

please fix it

thanks
![Clip_10_p1](https://github.com/SubtitleEdit/subtitleedit/assets/43181048/5840e372-2ea3-477b-aeaf-405bf5639fc0)
![Clip_11_p1](https://github.com/SubtitleEdit/subtitleedit/assets/43181048/49142381-b517-4cf9-8718-6f47d62d0c26)
![Clip_12_p1](https://github.com/SubtitleEdit/subtitleedit/assets/43181048/b9748c73-d975-4915-a037-e02006f713b0)

**Comment by amir385276** [comment]
I try it with any SRT with any items.
Click mouse 
ctrl+s

and the first line undo to any format that changed

**Comment by niksedk** [comment]
Sorry, I cannot re-create this... could you give more specific instructions?

**Comment by amir385276** [comment]
Hi niksedk
1- open srt file
2- change something like color or font of the line or lines or all lines
3- then click the right or left mouse 
4- as you can see the first line of your srt file undo any changes

it's very simple

**Comment by niksedk** [comment]
Works fine here.

**Comment by amir385276** [comment]
I'm confused 
maybe in the farsi language have a issue?
hun
