### ISSUE TITLE
Subtitle preview font size

### ISSUE THREAD

**Issue by kadrimarzouki** [SubtitleEdit/subtitleedit#8438]
Could you please increase the subtitle preview size a bit more? 
For some fonts, when using a 1080p resolution or higher, 
the fonts are way too small.

**Comment by MbuguaDavid** [comment]
> Could you please increase the subtitle preview size a bit more? For some fonts, when using a 1080p resolution or higher, the fonts are way too small.

You can increase the Subtitle Preview font size from the Settings > Video Player and increase to the size that works for your use case. 
![Settings - Video Player - Increase](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/18b5f0e8-6aa6-44e8-8f1f-e2f8ae2ff0a0)

Thanks!

**Comment by kadrimarzouki** [comment]
I meant above this '30' value, 
we can actually increase it manually from the 'settings.xml' file. 
The request was to give us the ability to do it from the Video Player settings that you were pointing to in the picture

> > Could you please increase the subtitle preview size a bit more? For some fonts, when using a 1080p resolution or higher, the fonts are way too small.
> 
> You can increase the Subtitle Preview font size from the Settings > Video Player and increase to the size that works for your use case. ![Settings - Video Player - Increase](https://private-user-images.githubusercontent.com/92556454/333913260-18b5f0e8-6aa6-44e8-8f1f-e2f8ae2ff0a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzQxNjIsIm5iZiI6MTcxNjc3Mzg2MiwicGF0aCI6Ii85MjU1NjQ1NC8zMzM5MTMyNjAtMThiNWYwZTgtNmFhNi00NGU4LThmMWYtZTJmOGFlMmZmMGEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAxMzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYjgxMWVkODVkY2FiM2E5NTg2ODg1NTk0ZjkxZTczOWJkNjg5MTdmMjczMDhhNzc0MTg5ZWIwMWRjY2FkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aM9iZzkRX6JX-lttKjU3Jbe_rxVED7K4cBMk_1VXQ6w)
> 
> Thanks!




I meant above this '30' value, 
we can actually increase it manually from the 'settings.xml' file. 
The request was to give us the ability to do it from the Video Player settings that you were pointing to in the picture
