### ISSUE TITLE
DeepL missing language (pt-br)

### ISSUE THREAD

**Issue by Uncle-Tio** [SubtitleEdit/subtitleedit#8439]
"Brazilian Portuguese" (pt-br) option is missing, only "Portuguese" (pt) is present.

This change alone should be enough, I tested it: 

**src/libse/AutoTranslate/DeepLTranslate.cs**
`MakeTranslationPair("Portuguese-Brazil", "pt-br", true),`

**Comment by niksedk** [comment]
thx for the info .- how is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

**Comment by Uncle-Tio** [comment]
> thx for the info .- how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

Working fine. Both Portuguese are coming out as they should. 
Thank you!
