### ISSUE TITLE
Subtitle create/adjust menu disappears

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#8442]
So. This doesn't seem to depend much on the version, since it happens both in the most recent beta and in one from early April.
The thing that disappears is this:
![se menu](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/b91c6933-9e4f-477a-be38-c05e051d686c)

I have no idea what triggered this, but it didn't happen when I changed to a newer beta or something. Everything was the same, it was working, and then suddenly it wasn't.
With a freshly unzipped beta, everything works fine. But as soon as I copy over my settings.xml file, the thing vanishes, and what I get is this:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/5e56487a-a9cb-4873-b025-e86f50034275)

The thing is, I don't even think I changed any settings before this happened. I suspect it has something to do with the hundreds of items I have in multiple replace, but I'm not sure. Anyway, I'm attaching my settings.xml file, because I don't know how else to reproduce this:
[Settings.xml.bad.txt](https://github.com/SubtitleEdit/subtitleedit/files/15461606/Settings.xml.bad.txt)

And here's a settings.xml file that's mostly the same (from a beta from February), but that doesn't cause the problem:
[Settings.xml.good.txt](https://github.com/SubtitleEdit/subtitleedit/files/15462105/Settings.xml.good.txt)

**Comment by niksedk** [comment]
Sorry, does not support scaling... pretty hard in WinForms

**Comment by darnn** [comment]
I'm not sure what you mean. Scaling as in size? Because if so, I don't understand what this has to do with it.
