### ISSUE TITLE
Add Whisper translation

### ISSUE THREAD

**Issue by subof** [SubtitleEdit/subtitleedit#8450]
The multilingual models were trained on both speech recognition and speech translation. The function of free translation into different languages would be very much in demand, given that besides Google v1, other translation systems require payment. Thanks

**Comment by darnn** [comment]
Whisper only translates into English, an option which is already present in Subtitle Edit (check the `Translate to English` box in the Whisper dialogue).

**Comment by GOvEy1nw** [comment]
> The multilingual models were trained on both speech recognition and speech translation. The function of free translation into different languages would be very much in demand, given that besides Google v1, other translation systems require payment. Thanks

With decent hardware you can run either LibreTraslate or NLLB locally for free
