### ISSUE TITLE
"Fix common errors/Fix missing spaces" does not always work

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#8479]
SubtitleEdit 4.0.6 NEXT, beta 18

With the attached srt files, "Fix common errors/Fix missing spaces" does not always work.

- It does work with subtitles 5, 10 and 55 of the srt file. 
- It does **not** work with subtitles 6, 9 and 14 of the srt file. 

In the zip file below, there are two versions of the srt file included: before and after the running of "Fix common errors".

[Before and after Fix common errors.zip](https://github.com/user-attachments/files/15571281/Before.and.after.Fix.common.errors.zip)

**Example of before:**
5
00:00:21,403 --> 00:00:22,703
-Oh, what?
-Oh.

6
00:00:22,803 --> 00:00:24,343
-Brilliant.

**Example of after:**
5
00:00:21,403 --> 00:00:22,703
\- Oh, what?
\- Oh.

6
00:00:22,803 --> 00:00:24,343
-Brilliant.

**Comment by niksedk** [comment]
That's because line 6 is not really a dialog.

"Fix common errors" has a fix for removing this dash:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/0b71b59e-0ef1-4ffc-adb6-87e708683aaf)

**Comment by niksedk** [comment]
Also, 4.0.6 final is out :)

**Comment by oep42** [comment]
I guess not everyone has the same opinion about what a "real" dialog is — and about which lines should begin with a dash.

I didn't think about the option "Remove start dash in first line for non-dialogs". Using this option, solves the inconsistency that results from using "Fix missing spaces" in the above srt file, if one prefers to remove a dash in the first line of "non-dialogs" (as I do).

However, for those who prefer to have a dash in "non-dialogs" and take the meaning of "Fix missing spaces" seriously, the option "Fix missing spaces" will be seen as broken for a dash in "non-dialogs". I think the option name "Fix missing spaces" is misleading, when that option does not remove all missing spaces.

So I would suggest to reconsider what the option "Fix missing spaces" does. If this option would add a space after a dash at the beginning of "non-dialogs", this would not do any harm at all. The option "Remove start dash in first line for non-dialogs" could still be used by those who prefer not to have a dash in the first line of "non-dialogs".
