### ISSUE TITLE
About advanced settings in the automatic translation feature

### ISSUE THREAD

**Issue by despairTK** [SubtitleEdit/subtitleedit#8480]
![QQ截图20240605105256](https://github.com/SubtitleEdit/subtitleedit/assets/111871110/e8c1d4e9-0544-40e3-b0b3-4954a54bac7d)
Can this option be modified to set any number of lines for yourself? This will allow users to adjust the actual translation speed and effect according to their hardware configuration.

**Comment by niksedk** [comment]
Sorry, I do not have any plans for this atm...

You can use "Max bytes in each server call" to control "batch size" which determines speed.
