### ISSUE TITLE
When transcribe audio into Chinese by using large-v3-fp16 and large-v3-int8 model in faster-whisper always failure.

### ISSUE THREAD

**Issue by likangkao** [SubtitleEdit/subtitleedit#8481]
Here is the error log:
-----------------------------------------------------------------------------
Date: 06/04/2024 21:57:47
SE: 4.0.6.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: Calling whisper (Purfview's Faster-Whisper) with : C:\Users\likan\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\whisper-faster.exe --language zh --model "large-v3-fp16" --standard_asia "C:\Users\likan\Music\WhatsApp Audio 2023-08-17 at 03.39.32_85b3026e.waptt.opus"
Warning: 'large-v3' model may produce inferior results, try 'large-v2'!

Standalone Faster-Whisper r192.3 running on: CUDA
Starting work on: C:\Users\likan\Music\WhatsApp Audio 2023-08-17 at 03.39.32_85b3026e.waptt.opus
[25612] Failed to execute script '__main__' due to unhandled exception!

ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead

File "faster_whisper\transcribe.py", line 1026, in encode

File "faster_whisper\transcribe.py", line 715, in generate_segments

File "faster_whisper\transcribe.py", line 1373, in restore_speech_timestamps

File "D:\whisper-fast\__main__.py", line 1527, in cli

File "D:\whisper-fast\__main__.py", line 1600, in <module>

Traceback (most recent call last):
Calling whisper Purfview's Faster-Whisper done in 00:00:17.8499789
Loading result from STDOUT

-----------------------------------------------------------------------------
Date: 06/04/2024 21:58:59
SE: 4.0.6.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: Calling whisper (Purfview's Faster-Whisper) with : C:\Users\likan\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\whisper-faster.exe --language zh --model "large-v3-int8" --standard_asia "C:\Users\likan\Music\WhatsApp Audio 2023-08-17 at 03.39.32_85b3026e.waptt.opus"
Warning: 'large-v3' model may produce inferior results, try 'large-v2'!

Standalone Faster-Whisper r192.3 running on: CUDA
Starting work on: C:\Users\likan\Music\WhatsApp Audio 2023-08-17 at 03.39.32_85b3026e.waptt.opus
[17128] Failed to execute script '__main__' due to unhandled exception!

ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead

File "faster_whisper\transcribe.py", line 1026, in encode

File "faster_whisper\transcribe.py", line 715, in generate_segments

File "faster_whisper\transcribe.py", line 1373, in restore_speech_timestamps

File "D:\whisper-fast\__main__.py", line 1527, in cli

File "D:\whisper-fast\__main__.py", line 1600, in <module>

Traceback (most recent call last):
Calling whisper Purfview's Faster-Whisper done in 00:00:17.5328943
Loading result from STDOUT

**Comment by niksedk** [comment]
My guess would be, that the `large-v3-fp16` model is not compatible with `Standalone Faster-Whisper r192.3`.

You could try "Purfview's Faster-Whisper XXL" and see if that is better?

Also, this issue is probably more regarding: https://github.com/Purfview/whisper-standalone-win/issues

**Comment by Purfview** [comment]
large-v3-fp16 and large-v3-int8 are not supported anymore, you can delete them.
