### ISSUE TITLE
Small Whisper UI bug

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#8489]
The word is cut off.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19517183/d4fde2fa-4dcb-4970-9b72-dbb81cbf3861)

**Comment by ivandrofly** [comment]
@niksedk  fixed?

![image](https://github.com/SubtitleEdit/subtitleedit/assets/6579818/1ad89c2f-8a7a-488a-adad-1b138fa4774e)

**Comment by rRobis** [comment]
Yes it's fixed now.
