### ISSUE TITLE
Please add an auto-save feature and when File->Save is clicked, it should not open a File Explorer Window

### ISSUE THREAD

**Issue by nyck33** [SubtitleEdit/subtitleedit#8495]
Third day on the job as a translator and just lost my work for an entire afternoon as it's confusing when I click File->Save I am expecting different behavior (silently save under same file name as the file open and being worked on) and not the same behavior as File->Save As which usually in most Windows programs would open File Explorer and I would get to name or rename the file for saving.  

I realize it's open source and free but these would be nice-to-haves, ie. better alignment with behavior of the majority of Windows software people are used to, ie. Microsoft Office.

**Comment by niksedk** [comment]
SE behaves just as other windows programs: If no file name is already specified, SE will prompt, Otherwise it will save using the current file name.
