### ISSUE TITLE
Translate Selected Lines Error

### ISSUE THREAD

**Issue by lhschroder** [SubtitleEdit/subtitleedit#8509]
I'm trying to translate selected lines in the subtitle (because Google Gemini's automatic translation fails a lot and leaves many empty lines) and when selecting the option I get the error indicated in the attached image.

![Captura de tela 2024-06-08 172130](https://github.com/SubtitleEdit/subtitleedit/assets/24702225/1dca62ad-7731-4178-be76-1f6a7d34747f)

**Comment by ivandrofly** [comment]
I think this has already been fixed!

**Comment by lhschroder** [comment]
> Acho que isso já foi corrigido!
> 
> Veja #8459

Pelo que entendi precisaria limpar as configurações anteriores e reinserir as chaves, mas acredito que fique para correção no backlog.
