### ISSUE TITLE
Object reference not set to and instance of an object

### ISSUE THREAD

**Issue by ksmtesoler** [SubtitleEdit/subtitleedit#8510]
Object reference not set to and instance of an object
![error message](https://github.com/SubtitleEdit/subtitleedit/assets/22252535/85380a8c-a7f2-418c-8326-99d39030e240)

**Comment by niksedk** [comment]
I cannot re-create this. 
What exactly did you do? And do you have ffmpeg/vlc installed and configured in SE?

**Comment by ivandrofly** [comment]
Well, there is change that `AudioVisualizer.ParagraphEventArgs e` can be null.

If you see places where `OnSingleClick` is been raised, you can see null is sometimes passed to the AudioVisualizer.ParagraphEventArgs
