### ISSUE TITLE
.NET Framework Initialization Error when Opening the App

### ISSUE THREAD

**Issue by Marcusng01** [SubtitleEdit/subtitleedit#8513]
![Untitled](https://github.com/SubtitleEdit/subtitleedit/assets/71885636/e89a9dfe-98fc-43c1-80c2-2595a21e25c8)

This error appears when trying to open the application.

I have tried reinstalling .NET and reinstalling SubtitleEdit, and still no luck

**Comment by niksedk** [comment]
Try here: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48
