### ISSUE TITLE
TTS audio glitching error

### ISSUE THREAD

**Issue by cvrle77** [SubtitleEdit/subtitleedit#8519]
I can't figure how this glitch can be reproduced, but I believe it's something like when I regenerate some sentence in Review audio clips window, and probably press stop in the middle of reproduction of that sentence, or pressing stop multiple times, I don't really know, but it's the exact same pattern, and it always surprises me when it pops. And for some reason, I can't rewind and remember what was the last thing I was doing. 

It renders all previous work unusable, and it's like a stomp in the eye. I already submitted this issue, but it was never solved solved. Effort was made on your side, but issue remained persistent.

Here's the video how it sounds, when it happens.
https://drive.google.com/file/d/1Q-NRqB8GIVXxY3hSXj42vxZcDkzqGnaC/view?usp=drivesdk

Oh, one more thing, once I start generating speech from text, it is impossible to cancel it, cancel button doesn't work, it grays out when you press it, and plays dead, up until it uses credit for TTS, does all the job, and then just cancels and shuts down the window. 

Just two superlarge massive credit drainage black holes. It gets really expensive really fast to test this or press the wrong button at the wrong moment. Cancel button is like a trap, if you press it, you're screwed.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/16167396/b6f3aa66-6f6b-4d6a-b84d-eec293015f00)

**Comment by niksedk** [comment]
Thx for the info :)

Cancel should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip

I cannot re-create the other issue... also, I'm not really sure what it is?

**Comment by cvrle77** [comment]
When I test line by line, to check how each line sounds, it seems it's a combination of mouse click on play, then keyboard space bar, and mouse stop button. It happened again. It probably happens if there's two or more audio calls to play the sound, or possibly to play the same sound at once.

**Comment by cvrle77** [comment]
> Thx for the info :)
> 
> Cancel should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip
> 
> I cannot re-create the other issue... also, I'm not really sure what it is?

Yes, I finally managed to successfully reproduce it each time. Just double click Play button, like you do it to start the program, with that speed.

You need to create a single subtitle line, do TTS with ANY engine/service, now do doubleclick on play button.. You'll get stuttering reproduction - broken STOP command -  and finally app will crash - in that order.

**Comment by niksedk** [comment]
Thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip
