### ISSUE TITLE
Actor in SRT

### ISSUE THREAD

**Issue by rjgout** [SubtitleEdit/subtitleedit#8522]
I use your wonderful program to transcribe my podcast. It works great. I want to add the actor/speaker. I found out it can only be done in .ass format. But I need an .srt file. I can export it with the custom settings and add the actor there. But I need a : after the actor. Not every line needs to an actor. But when I create the export even the lines without an actor get the :. Is there an easyer way to export to srt or save as srt with the right format with actors.
Als this would be nice for WebVTT.

See also: https://github.com/Podcastindex-org/podcast-namespace/blob/main/transcripts/transcripts.md

**Comment by niksedk** [comment]
You can export to custom text with actor via File - Export plain text, edit the subrip template:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/7b630146-eb7e-40df-9da3-65c1dab6f311)

Also, the json format from prodcasterindex is now included in SE: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip

WebVTT already supports voices in SE:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/b19447b2-678e-422e-88c1-b37d8764809e)
