### ISSUE TITLE
Allow Jump Forward/Backward by One Video Frame

### ISSUE THREAD

**Issue by AlfredPros** [SubtitleEdit/subtitleedit#8524]
In a case of song or action subtitling, I need subtitle to appear at an exact frame of the video. It would be helpful if there's a feature to jump by one frame. The button placement should be put beside the normal jump forward/backward buttons for ease of use.

For reference, the UI could look like the image below where one triangle is for a single frame.
![image](https://github.com/SubtitleEdit/subtitleedit/assets/28826962/bcae22d8-7567-45aa-ad76-2a9a7b5708b3)

**Comment by niksedk** [comment]
You can setup shortcuts:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/76e8ca00-d02a-436a-9cbc-fad382b1421e)


Note that not all formats supports frame navigation.
