### ISSUE TITLE
[QOL/ideas/Request for Auto Translation]

### ISSUE THREAD

**Issue by TobbyTravel** [SubtitleEdit/subtitleedit#8527]
Hi,

I've really enjoyed the AI integration for auto-translation, especially with Ollama, and I have a few ideas/suggestions:

**1. Enable Re-Translations of Sentences with Keywords:**

Sometimes, certain models may error out. It would be useful to search the completed translated text, mark only the sentences for re-translation, and rerun the translation for those specific sentences in bulk.

**2. Option to Choose Source Text:**

When opening auto-translation, allow the user to choose between untranslated and translated text as the source.

**3. Increase Maximum Bytes per Server Call:**

If possible, increase the current 10,000-byte limit per server call (Ollama). 
This might be related to context size, as many models have a context size of 8k tokens or more. 
(Guestimate 2 bytes per token).

**4. Resume Auto-Translation from Mid-Point:**

Currently, if you cancel and restart the process, it begins from the start. 
It would be beneficial to have the option to resume from the midpoint or where it was left off.

**5. Time Estimation for Completion:**

Provide some form of time indication based on the current translation speed.

**6. Completion Notification:**

A warning sound or notification when the translation is finished would be helpful, especially for users renting inference GPUs and paying per hour, not per token.

Thank you for considering these suggestions!

**Comment by niksedk** [comment]
Only one bug/request per issue please
Foir more info see https://www.nikse.dk/subtitleedit/help#linux

**Comment by TobbyTravel** [comment]
> Only one bug/request per issue please Foir more info see https://www.nikse.dk/subtitleedit/help#linux

Will do, thank you for your patience.
