### ISSUE TITLE
Is there a Linux version available?

### ISSUE THREAD

**Issue by LordOfTurk** [SubtitleEdit/subtitleedit#8529]
I looked at the documentation, but I couldn't get it to work on Linux. Is it possible for you to release a version for Linux? Or is there a simpler way to get it to work? I tried with Wine but it didn't work unfortunately.

**Comment by niksedk** [comment]
Sorry, we only have this: https://www.nikse.dk/subtitleedit/help#linux

Or you can run a VM/dual-boot with Window
