### ISSUE TITLE
Generate text from audio crash on Windows 10

### ISSUE THREAD

**Issue by MediaExpres** [SubtitleEdit/subtitleedit#8530]
Trying to generate text from audio by selecting a portion of the soundwave ends in this error:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/71558483/eeb782fb-a5cf-455a-a3bd-42e277e6d79e)

Thanks for considering,
Mihai

**Comment by niksedk** [comment]
Thx for the info :)
Hopefully fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip
