### ISSUE TITLE
Everytime I try to use Automatic Translation since I got my DeepL API...

### ISSUE THREAD

**Issue by Marv74BR** [SubtitleEdit/subtitleedit#8533]
![imagem_2024-06-15_235228147](https://github.com/SubtitleEdit/subtitleedit/assets/172946618/0db91b6f-14d7-4cce-9e00-3d82609cefdd)

I didn't happed before, but it didn't happen right away, the translation with API worked... for about 2 days.

**Comment by niksedk** [comment]
Sorry, seems to be a bug in 4.0.6... should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip
