### ISSUE TITLE
[Feature Request] Auto-Translation: Re-Translations of Sentences

### ISSUE THREAD

**Issue by TobbyTravel** [SubtitleEdit/subtitleedit#8537]
Sometimes, certain models may error out due to censorship or misintrepid system prompt on lower quality models.
It would be useful to search the completed translated text, mark only the sentences for re-translation, and rerun the translation for those specific sentences in bulk. This could be done by keywords for example. Re-translate all senteces with keyword "explicit" or "translated"

As requested in: https://github.com/SubtitleEdit/subtitleedit/issues/8527

**Comment by niksedk** [comment]
Could you explain more and give some examples?

**Comment by TobbyTravel** [comment]
Partly solved by my understanding correct use of https://github.com/SubtitleEdit/subtitleedit/issues/8538

I can search for keyword "explicit" in main window, but not select all matching search lines at once for "selected line translation", only "next" and do it manually. Is that something that could be added or already a function? (user-error)

**Comment by TobbyTravel** [comment]
Nevermind, this is solvable via "Modify selections", user-error. closing issue. Thanks for your time!

**Comment by TobbyTravel** [comment]
Let me keep this issue open until we confirm it's possible to transfer line selection from Translated subittles to original subtitles so it can be sent to auto-translated again.

**Comment by TobbyTravel** [comment]
It work as intended, awesome, case closed!
