### ISSUE TITLE
[Feature Request] Auto-Translation: Option to Choose input text

### ISSUE THREAD

**Issue by TobbyTravel** [SubtitleEdit/subtitleedit#8538]
When opening auto-translation, allow the user to choose between untranslated and translated text as the source.
Pressing OK and re-opening uses the already translated text as input instead of the original.

As suggested in: https://github.com/SubtitleEdit/subtitleedit/issues/8527

**Comment by niksedk** [comment]
Works fine on my computer via translate selected lines

**Comment by TobbyTravel** [comment]
Ahh, I though it was intend to be selected in the Auto-translate window on left side as multiple lines can be marked there, but it is only intended for single line-translation. 

Translate selected lines from main window, solves the problem Thanks.
