### ISSUE TITLE
[Feature Request] Auto-Translation: Resume Auto-Translation from Mid-Point

### ISSUE THREAD

**Issue by TobbyTravel** [SubtitleEdit/subtitleedit#8539]
Allow resuming from the mid-point. At the moment, you can't run multiple passes as it starts from the beginning or single-sentece only.

As suggested in: https://github.com/SubtitleEdit/subtitleedit/issues/8527

**Comment by niksedk** [comment]
You can translate selected lines from the main window.
You can also re-translate in the translate window - and it starts from selected lines. And you can re-translate cunrrent line only.
