### ISSUE TITLE
[Feature Request] Auto-Translation: Ollama Increase Maximum Bytes per Server Call

### ISSUE THREAD

**Issue by TobbyTravel** [SubtitleEdit/subtitleedit#8540]
If possible, increase the current 10,000-byte limit per server call (Ollama) assuming this affects context size.
This might be related to context size, as many models have a context size of 8k tokens or more.
Note sure how it affects ollama if it controls the context lenght of the model or only the request.
It would be helpful with more information in helpbox.

Separate issue created as suggested in: https://github.com/SubtitleEdit/subtitleedit/issues/8527

**Comment by niksedk** [comment]
Sorry, to complex IMO

**Comment by TobbyTravel** [comment]
No worries, thank you for the consideration!
