### ISSUE TITLE
Altenative way to generate Time Codes !

### ISSUE THREAD

**Issue by ihanulusoy** [SubtitleEdit/subtitleedit#8547]
Hi..

because whisper timecoding isnt perfect. can we combine plain text with whisper time code!?

for example , this is my plain text sentence ( hello first title, and second title , and third title ) 

keep in mind (for example) that auto timecode option and whisper audio to text , provide me sub like this :

00:01:10 - 00:01:20   hello first title 
00:01:20 - 00:01:30   hello second title
00:01:30 - 00:01:40   hello third title 

so , aftert generating audio to text with whisper, can SE understand my sentence (that i provide in plain text with 1 sentence in 1 line option), to combine whisper timecode and understand that, my sentence timecode should be start from 00:01:10 to stop on 00:01:40 

please help and ask me more explanation if you need, because I'm not sure that I explained it correctly, like what I have in my mind

**Comment by ihanulusoy** [comment]
thank you for you help. but its still need manual work to fix. if you find a auto way please share it here. actually its should be easy for SE developers to add this feature

**Comment by JDTR75** [comment]
Have you tried Purfview's Whisper version? It has a `--sentence` option that should do what you're needing.

**Comment by ihanulusoy** [comment]
> Have you tried Purfview's Whisper version? It has a `--sentence` option that should do what you're needing.

yes, but result is not perfect
