### ISSUE TITLE
Bitdefender detecting Trojan virus in v0.8.2 zip

### ISSUE THREAD

**Issue by trsmith78** [SubtitleEdit/subtitleedit#8550]
Hi,

I tried to download your latest version of GUI- subtrans-0.8.2.zip and get the following error from bitdefender:

Feature:
Antivirus

The file C:\Users\troyd\Downloads\d75b887a-446f-4403-b5bc-ae9d0bfb21b6.tmp is infected with Trojan.GenericKD.73124510. The threat has been successfully blocked, your device is safe.

Is this a false alarm?  Can someone verify?

I'm really interested in your application.  I know I could download the source and build it, but my computer is new and isn't setup with visual studio or development tools yet. 

Many thanks,
Troy

**Comment by niksedk** [comment]
I've no idea what GUI-subtrans.0.8.2.zip is....

**Comment by trsmith78** [comment]
Sorry wrong program to post this too...

**Comment by trsmith78** [comment]
Sorry wrong program to post this too...
