### ISSUE TITLE
VLC path not updated

### ISSUE THREAD

**Issue by rtritto** [SubtitleEdit/subtitleedit#8554]
After I selected the VLC exe file, the VLC path value isn't updated (the value is only equal to the folder):

<img width="618" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/40242971/28a08ea8-4ac9-47c6-9814-681f720bd474">

**Comment by ivandrofly** [comment]
> After I selected the VLC exe file, the VLC path value isn't updated (the value is only equal to the folder):
> 
> <img alt="image" width="618" src="https://private-user-images.githubusercontent.com/40242971/341555313-28a08ea8-4ac9-47c6-9814-681f720bd474.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MjExNzksIm5iZiI6MTcxODkyMDg3OSwicGF0aCI6Ii80MDI0Mjk3MS8zNDE1NTUzMTMtMjhhMDhlYTgtNGFjOS00N2M2LTk4MTQtNjgxZjcyMGJkNDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDIyMDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYTkyNGM5MTVjNmMzMmRmMWU1NThjMzNmMDk4MWZjYjViOGM0MDc0YWIzYTBlZjMxYzg4MWZiZGJmMTY3YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.56YTsqGrdVmGoV47UuPU7wLUgMW5D3bDGjQdWV0TzCY">

That should be the normal behavior. It only show the directory where the executable is stored!

**Comment by rtritto** [comment]
It's not explicit, the selected files should be visible in the path

**Comment by ivandrofly** [comment]
> It's not explicit, the selected files should be visible in the path

The vlc.exe that you selected, isn't it stored in `c:\Portable\VLCPortable\App\vlc`?

e.g; if you select `c:\Portable\VLCPortable\App\Vlc\Vlc.exe` then you should see => `c:\Portable\VLCPortable\App\vlc` (the Directory)

Because SE will use that path later  to select file like `libvlc.dll` which is required for video player

**Comment by rtritto** [comment]
I'm using a portable version of VLC and the file is `VLCPortable.exe`

**Comment by niksedk** [comment]
Sorry,, SE does not support this.
