### ISSUE TITLE
Latest update not an update?

### ISSUE THREAD

**Issue by GrampaWildWilly** [SubtitleEdit/subtitleedit#8555]
The GitHub repository for SE says the beta was updated 3 hours ago.  But when I downloaded the file, the newest date stamp inside the zip file was June 5.  That's distinctly not 3 hours ago, more like about 2 weeks ago.  Is there something weird going on?

**Comment by GrampaWildWilly** [comment]
The beta continues to not be current.

**Comment by GrampaWildWilly** [comment]
I'm surprised there haven't been several complaints about this.  The beta is still the one from June 5 even though the GitHub repository claims it was updated yesterday.  If there was an update yesterday, it didn't work correctly.  The same beta 34 that's been up since June 5 is all that's there.  I have seen mention in here from Nik that he's "merged into main" a few things.  So there is a newer beta in existence.  But it has not been posted.  Why has the problem not been resolved?  Why has there not even been a comment from somebody else added to this discussion since I opened it?

**Comment by niksedk** [comment]
Thx, seems a recent commit changed the output folder... will fix asap

**Comment by niksedk** [comment]
New beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip

**Comment by GrampaWildWilly** [comment]
Indeed.  I now have 4.0.6 beta 79.  Thanks Nik.
