### ISSUE TITLE
Windows Forms Thread Exception - Auto Translate 

### ISSUE THREAD

**Issue by Steinar-ichiban** [SubtitleEdit/subtitleedit#8561]
I get this error whenever i try to use auto translate. (Some of the text in the error is in Norwegian) 
I made a video of me reproduce the error:
https://1drv.ms/v/s!AkS-DirWiby7oIQZ86YcMiPBzsZTZw?e=z5ox7d

Windows Forms Thread Exception
An application error occurred in Subtitle Edit 4.0.6.0 - 64-bit - Microsoft Windows NT 10.0.22631.0.
Please report at
https://github.com/Subtitle Edit/subtitleedit/issues with the following information:
Error Message:
Unable to cast object of type 'System.String' to type 'Nikse.SubtitleEdit.Core.Translate.TranslationPair'.
X
Stack Trace:
ved
Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.SelectLangua geCode(NikseComboBox comboBox, String languagelsoCode) Nikse.SubtitleEdit.Controls.NikseComboBox.NotifyTextChange
ved
d0 ved
Nikse.SubtitleEdit.Controls.NikseComboBox.set_SelectedIndex(
Int32 value) ved
Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.InitializeAuto
TranslatorEngines()
ved
Nikse.SubtitleEdit.Forms.Translate.AutoTranslate..ctor(Subtitle subtitle, Subtitle targetLines, String title, Encoding encoding) ved
Nikse.SubtitleEdit.Forms.Main.MakeAutoTranslate(Boolean
onlySelectedLines)
ved System.Windows.Forms.ToolStripltem.RaiseEvent(Object key, EventArgs e) ved
System.Windows.Forms.ToolStripMenultem.OnClick(EventArgs
e)
ved
System.Windows.Forms.ToolStripltem.HandleClick(EventArgs
e) ved
System.Windows.Forms.ToolStripltem.Handle MouseUp(Mouse
EventArgs e)
ved
System.Windows.Forms.ToolStrip. OnMouseUp(MouseEventAr
gs mea) ved
System.Windows.Forms.ToolStripDropDown.OnMouseUp(Mo
useEventArgs mea)
ved
System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
m)
ved System.Windows.Forms.Control.WndProc(Message& m) ved System.Windows.Forms.ToolStrip.WndProc(Message&
ved
System.Windows.Forms.ToolStrip DropDown.WndProc(Messag
e& m)
ved System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)

**Comment by niksedk** [comment]
Sorry, this is a known bug... should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip

**Comment by abudulamh** [comment]
> > > Sorry, this is a known bug... should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip
> > 
> > 
> > Hi Nik This bug still exists with the dark theme When using nllb-api
> 
> Are you using latest beta? See help about...

I am very sorry for the late response
I use
SubtitleEdit-4.0.6-Setup.zip
Windows installer version

It's not a big problem, it works well with a light theme
![Capture](https://github.com/SubtitleEdit/subtitleedit/assets/135340122/72572322-665c-4c42-acff-81911d35f6c0)

**Comment by Steinar-ichiban** [comment]
> Sorry, this is a known bug... should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip

This is working for me, i don't have this issues anymore even in dark theme. But will there be an windows installer for the beta version instead of only the portable one?

**Comment by Steinar-ichiban** [comment]
> > > > Sorry, this is a known bug... should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip
> > > 
> > > 
> > > Hi Nik This bug still exists with the dark theme When using nllb-api
> > 
> > 
> > Are you using latest beta? See help about...
> 
> I am very sorry for the late response I use SubtitleEdit-4.0.6-Setup.zip Windows installer version
> 
> It's not a big problem, it works well with a light theme Thank you
> 
> ![Capture](https://private-user-images.githubusercontent.com/135340122/342503293-72572322-665c-4c42-acff-81911d35f6c0.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzE0NjYsIm5iZiI6MTcxOTI3MTE2NiwicGF0aCI6Ii8xMzUzNDAxMjIvMzQyNTAzMjkzLTcyNTcyMzIyLTY2NWMtNGM0Mi1hY2ZmLTgxOTExZDM1ZjZjMC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQyMzE5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWU1ZDgxN2ZkOWJjNzg5Yjc2NzU0M2RkNTAyY2E3YzEzN2RjNjNiYmUxODkxZTRiYTJmNWU3OGNlNzE4NDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ylQz923E7xiz0x4EoxpwRypN6tHHK9jl5AytRcv53DY)

Your version  is not the beta, you have to download using the link @niksedk posted.
The beta version: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/142811612/0b7a88b1-f6a0-44be-b524-2fb3ec288a5d)

**Comment by abudulamh** [comment]
> Your version is not the beta, you have to download using the link @niksedk posted. 

Well, I guess I didn't read nik's response well
I have difficulty reading small font
I will download the beta version
Thank you for the clarification

**Comment by niksedk** [comment]
Fix in 4.0.7
