### ISSUE TITLE
Burn-in function is broken

### ISSUE THREAD

**Issue by Hafran420** [SubtitleEdit/subtitleedit#8564]
after burning-in subtitles every video playback program fails except VLC player.

**Comment by niksedk** [comment]
Could you supply a lot more info? 
What codes/container-format are you using for save? 
Screenshots?

**Comment by Hafran420** [comment]
tried with MKV HEVC x265 10bit save as MP4, Im using version 4.0.6
![print](https://github.com/SubtitleEdit/subtitleedit/assets/82881984/e9b0242a-5e44-4a50-a18e-744bd555d244)

**Comment by niksedk** [comment]
Hm, works fine here... in vlc, mpv, and mpc-hc
