### ISSUE TITLE
WhisperSpeech

### ISSUE THREAD

**Issue by madey83** [SubtitleEdit/subtitleedit#8573]
Please add this text to speech solution....

**Comment by niksedk** [comment]
https://github.com/collabora/WhisperSpeech seems a little dead to me... and no easy way to run it

**Comment by madey83** [comment]
i see last commit was from 2 months ago

**Comment by niksedk** [comment]
How do you run it?

**Comment by madey83** [comment]
Not sure yet... When I figured it out I will update you
