### ISSUE TITLE
Request to Enable Text Justification Options

### ISSUE THREAD

**Issue by kadrimarzouki** [SubtitleEdit/subtitleedit#8582]
Hello,

Could you please give us the ability to choose text justification type (left-aligned, centered, right-aligned)?

The option is available but currently hidden.

    <MpvExtraOptions>--sub-ass-justify=yes --sub-justify=right</MpvExtraOptions>

![justify 2](https://github.com/SubtitleEdit/subtitleedit/assets/47260178/455bdebb-3063-453e-8c5a-df566d1542d0)
![justify 1](https://github.com/SubtitleEdit/subtitleedit/assets/47260178/e5021f06-b2fa-4fc0-99ab-1b8b6c68c82a)

Result on the software: 
When:
<MpvExtraOptions>--sub-ass-justify=yes --sub-justify=right</MpvExtraOptions>

![j1](https://github.com/SubtitleEdit/subtitleedit/assets/47260178/e69a58db-0d8d-48f1-bedc-8f1c9ee26f76)

When:
<MpvExtraOptions>--sub-ass-justify=yes --sub-justify=left</MpvExtraOptions>

![j2 left](https://github.com/SubtitleEdit/subtitleedit/assets/47260178/85c3afd7-af74-434b-bf36-8630eb93604f)

When:
<MpvExtraOptions>--sub-ass-justify=yes --sub-justify=center</MpvExtraOptions>

![j3 center](https://github.com/SubtitleEdit/subtitleedit/assets/47260178/5293b846-6f3d-4a66-9f02-b5e2920f3626)

**Comment by kadrimarzouki** [comment]
@niksedk

**Comment by niksedk** [comment]
Could be useful for "export hard-subbed subtitles"... but seems too advanced for normal users.
