### ISSUE TITLE
Overlapping between Thai Alphabet and Vowel

### ISSUE THREAD

**Issue by kimkibom** [SubtitleEdit/subtitleedit#8590]
Hi,

I would like to know if there are any option to turn on and off this shadow since I want it all merge to all white while i'm exporting PGS

<img width="96" alt="Screenshot 2024-06-30 at 2 57 13 PM" src="https://github.com/SubtitleEdit/subtitleedit/assets/16303562/b7dc18ae-e413-4d73-bc01-cfdcb525db5d">

Thank you in advance 🙏

**Comment by niksedk** [comment]
Sorry, not too much I can do about this, as it's a Microsoft issue.
You can try "simple rendering".
