### ISSUE TITLE
When changing frame rates it proposes the detected frame rate in "source". Shouldn't that be the target?

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8592]
When changing frame rates it proposes the detected frame rate in "source". Shouldn't that be the target?

<img width="391" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/8692856/23e1ca95-211f-4198-9635-7b0e5f77b2b7">

**Comment by niksedk** [comment]
Could be both...
