### ISSUE TITLE
A few questions about specifying a Video Engine 关于指定 Video Engine 的几个问题

### ISSUE THREAD

**Issue by jon3nity** [SubtitleEdit/subtitleedit#8593]
### Discussed in https://github.com/SubtitleEdit/subtitleedit/discussions/8381
After copying andf pasting the libvlc.dll file into the SE folder, I still cant select VLc as a media player from the radio button option.

**Comment by niksedk** [comment]
To use VLC, create a folder called VLC in the SE data folder, and unpack the whole VLC portable.
Like https://get.videolan.org/vlc/3.0.21/win32/vlc-3.0.21-win32.7z
