### ISSUE TITLE
[Help] Add specific set of characters to each subttile

### ISSUE THREAD

**Issue by coding-hobby** [SubtitleEdit/subtitleedit#8599]
I am working on a project in which I need to add speaker info at the start of already created subtitles.  I need help to add [ ] to add to the start of each subtitle like below.  How can I acheive this?

Before:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19731090/1f5465b0-2755-4dc9-8e10-c4ce1b1c7ce6)

After:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19731090/791ae9ce-4bfa-4dee-bab2-a416632bb656)

**Comment by uckthis** [comment]
Ctrl+H
Find: ^(.*)$
Replace: [Speaker] $1

Regular expression.

**Comment by coding-hobby** [comment]
Result from the above expression.  It is adding charecters to the second line also and duplicated too.  I need it to be done only for first line.

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19731090/7f651ac5-6ad8-4ed8-81d1-c3585caee500)

**Comment by niksedk** [comment]
Try Edit - Multiple replace:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/4e6f05f2-69dc-451f-bb65-8c68d463ce24)

Read more here: http://nikse.dk/subtitleedit/help#multiple_replace (like example 6)

**Comment by coding-hobby** [comment]
Worked like a charm.  Thank you @niksedk
