### ISSUE TITLE
Windows 10 x64 – Auto-translation fails with SubtitleEdit 4.0.6

### ISSUE THREAD

**Issue by Snapper44** [SubtitleEdit/subtitleedit#8601]
It was working just fine. I was able to translate several Dutch VTT subs using the 1st Google option.  I wanted to see if other options gave a better result.  I started going down the list and I don’t remember which option I selected that first gave me the error.  Since then I haven’t been able to even bring up the options without getting the error.  I reinstalled SE 4.0.6 and I still got the error.  I then reinstalled SE 4.0.5 and I was able to translate.  I then reinstalled SE 4.0.6 and the error was back.  The instant I selected Auto-translate... the error appeared.
![SE Translate Error](https://github.com/SubtitleEdit/subtitleedit/assets/174899943/dda90582-6a4b-4a3b-8817-4b86ae49c058)

**Comment by niksedk** [comment]
Yes, this a bug in 4.0.6... has been reported more than a few times now, so I guess a SE 4.0.7 will be out soon...

**Comment by niksedk** [comment]
Should be fixed in version 4.0.7 :)
