### ISSUE TITLE
text-to-speech issue

### ISSUE THREAD

**Issue by madey83** [SubtitleEdit/subtitleedit#8613]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/34553588/c576c8fd-60a8-468c-9723-fe6064f7a4d7)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/34553588/258977f9-6325-455f-869c-5e92063e1ace)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/34553588/ce993fa1-1e63-4e19-8f08-773454aaba42)

**Comment by niksedk** [comment]
Do you have python installed?

Have you red this?
https://github.com/SubtitleEdit/subtitleedit/issues/8608#issuecomment-2218666025
