### ISSUE TITLE
Mass Subtitle Synchro

### ISSUE THREAD

**Issue by MrGoraj** [SubtitleEdit/subtitleedit#8614]
I have several hundred subtitle files.

I now want to match the timing to another video based on the subtitles (mkv) included in it.

Likewise, I generally don't have much of a problem with this and everything works fine, but with so many files, doing this with each individual file gets really monotonous and tedious.

Furthermore, I miss the function of indicating the folder with subtitles and then the folder with the other subtitles (video in mkv) to which the synchronization should be adjusted

**Comment by niksedk** [comment]
Sorry, SE does not support auto sync
