### ISSUE TITLE
advance of whisper tts issues

### ISSUE THREAD

**Issue by DavidWilliam11** [SubtitleEdit/subtitleedit#8620]
When I use whisper xxl, the parameter i write for advance did not save. I have to write it again whenever i open it.

**Comment by niksedk** [comment]
Works fine here... 

What do yo do exactly? Some screenshots?

**Comment by DavidWilliam11** [comment]
![Screenshot (4309)](https://github.com/user-attachments/assets/0fb41599-5269-4d16-91b4-40cef42e2580)
here, is always back to --standard when close

**Comment by niksedk** [comment]
Perhaps all your settings are not saved?

You might need a clean install, be remove everything before re-installing.

Note, portable goes into something like C:\Tools\SE - and not under "C:\Program files" where write access is not granted.
