### ISSUE TITLE
Can I copy and paste multiple lines by content only?

### ISSUE THREAD

**Issue by ty010624** [SubtitleEdit/subtitleedit#8623]
I'm using Subtitle Edit to edit translated .srt files. A common problem I encounter is that sometimes, due to language differences, the translated lines do not perfectly match the original .srt lines, resulting in a shift. To fix this, I currently have to copy each line's content and paste it to the next line manually.

I wonder if there is a way to do this by block? Right now, if I select a block of lines and copy-paste, the timeline is copied and pasted along with the content, which is not what I want. I hope to be able to copy only the contents of multiple lines and then paste them with a shift so they are associated with the next time point.

Is there a way to achieve this in the tool currently? If not, could this feature be considered for future updates?

**Comment by darnn** [comment]
See if any of these list view shortcuts help you:
![image](https://github.com/user-attachments/assets/3d779606-6414-4535-b80b-971c068f6986)

If not, can you describe the issue in more detail? Like, give an example of what you're doing, what you want to happen and the way it isn't happening?

**Comment by ty010624** [comment]
That is indeed very helpful!!! Exactly what I was looking for! Thank you so much!
