### ISSUE TITLE
OCR: l' -> L' (French)

### ISSUE THREAD

**Issue by Codling** [SubtitleEdit/subtitleedit#8629]
Hello,

The issue still occurs, as you can see:

![Capture d'écran 2024-07-13 124346](https://github.com/user-attachments/assets/44bccf20-f8fb-490f-9996-a0e3444a7e7e)

(SE 4.0.7)

**Comment by niksedk** [comment]
Could you attach the actual subtitle file?

**Comment by Codling** [comment]
Sure, here it is:
[Sample.zip](https://github.com/user-attachments/files/16202094/Sample.zip)

**Comment by niksedk** [comment]
Could you also attach the log from the screenshot as text? Soooo much easier...

**Comment by niksedk** [comment]
Hm.... what is the rules of this... should  "asmal l + quote" like "l'ASSASSIN" in no situations be converted to uppercase "L'" ?

**Comment by Codling** [comment]
It should only be converted to "L'" if the whole sentence is capitalized.

Example: à séquencer **l'**ADN de micro-organismes éteints

À SÉQUENCER **L'**ADN DE MICRO-ORGANISMES ÉTEINTS

> Could you also attach the log from the screenshot as text? Soooo much easier...
How can I do that, please? I don't see any log.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
Please test :)
