### ISSUE TITLE
Window for burning subtitles is broken

### ISSUE THREAD

**Issue by Hafran420** [SubtitleEdit/subtitleedit#8631]
![image](https://github.com/user-attachments/assets/769742ea-5fd6-413f-b0b4-096ca3017e15)

1920x1080 16:9

4.0.7

**Comment by niksedk** [comment]
Thx for the info :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
