### ISSUE TITLE
cant play burned videos

### ISSUE THREAD

**Issue by Hafran420** [SubtitleEdit/subtitleedit#8632]
after burning-in ASS subtitles every video playback program fails except VLC player.

4.0.6 - 4.0.7

sendin some info about videos. I cant work with videos after burning in subtitles. Also I cant play it in tv, WMP or other windows media players...   

[original.txt](https://github.com/user-attachments/files/16202373/original.txt)
[burned_4.0.5.txt](https://github.com/user-attachments/files/16202375/burned_4.0.5.txt)
[burned_4.0.7.txt](https://github.com/user-attachments/files/16202377/burned_4.0.7.txt)

![image](https://github.com/user-attachments/assets/481c3c31-637b-44f9-8d50-7658b620c59a)
VLC showed difference in decoded format. That video with Planar etc dont work. VLC showing this format only in videos burned in 4.0.7, the original doesn't have it either. Or maybe buffer dimension...

**Comment by niksedk** [comment]
Works fine here... what input settings are you using? Screenshots?

**Comment by Hafran420** [comment]
![image](https://github.com/user-attachments/assets/aae4906b-fff4-4b00-aa0d-88ba9eec43ea)

maybe try to use some of preinstalled windows media players. I leave the settings same for several versions but the problems are from 4.0.6 only

**Comment by niksedk** [comment]
4.0.7 uses default ffmpeg color space, which gives better quality (less blur/patterns), which I do like!

I guess it possible with some extra setting in SE, to make the video more compatible with legacy video players, but sorry, I do find the current defaults to be the best AFAIK...

Commit: https://github.com/SubtitleEdit/subtitleedit/commit/4680df9ab890875fa6a4c4bd5d759c02818ce226

**Comment by niksedk** [comment]
Also, the box sizes should be back to normal in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

![image](https://github.com/user-attachments/assets/b1570cee-b037-47f6-b947-d78267b301df)

**Comment by Hafran420** [comment]
yeah its working, thank you, I used parameters from 4.0.5 and changed ass but I need to change it after pass 1 is completed too... it's not very practical
do you think you could add something to the next version to simplify changing ffmpeg parameters? Or another button or dropdown menu with settings from older versions? 

I think (I tested it on my two TVs) that these burned videos will not be played on TVs with their own operating system like LG and Samsung as well as on other devices without the right video player. 

Thank you for your answers and I will be glad if you think about adding such a feature to future versions

**Comment by niksedk** [comment]
OK, how is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
(try the new "pixel format" drop down)

**Comment by Hafran420** [comment]
thank you so much. its working perfectly I will take some more tests on other devices and I will let you know but so far it works without problems
