### ISSUE TITLE
Subtitle Edit 4.0.7 and Purfview Faster Whisper Still Broken Merging Subtitle Lines

### ISSUE THREAD

**Issue by TranslateFuture** [SubtitleEdit/subtitleedit#8634]
Hi, sorry I forgot to update 3 months ago, but yup, with the new Subtitle Edit 4.0.7 stable update there's still the broken/merged/random capitalization/etc. issues that I described here: https://github.com/SubtitleEdit/subtitleedit/issues/8209 and https://github.com/SubtitleEdit/subtitleedit/issues/8209#issuecomment-2065596273

The sample files were here already 3 months ago but please let me know if new ones need to be made: https://github.com/SubtitleEdit/subtitleedit/files/15019293/github.subtitle.edit.broken.translation.for.korean.chinese.etc.zip

This was another post that seems almost exactly the same, but with LibreTranslate instead of Purfview Faster Whisper: https://github.com/SubtitleEdit/subtitleedit/issues/8449

I've confirmed that it's a Subtitle Edit issue after Subtitle Edit 4.0.3, since the latest Purfview Faster Whisper version works just fine.

This random breaks/merging/capitalization with the lines issue also occurs with the newly implemented Purfview Faster Whisper XXL version for Subtitle Edit 4.0.7.

I really apologize for not replying back months ago, as once again Subtitle Edit is a lifesaver and it's always amazing to see the quick updates and fixes, thank you so much.

**Comment by TranslateFuture** [comment]
Forgot to mention what could be the source of the breaks/merging/capitalization issue too after these changes with Serbian/European languages before: https://github.com/SubtitleEdit/subtitleedit/issues/8044

**Comment by niksedk** [comment]
I'm not really sure I understand what you mean... 
Could you provide an English video - and with clear comments about what is wrong?

**Comment by Purfview** [comment]
> issues that I described here

Your posted issues are not clear, and you didn't followed in that thread further -> https://github.com/SubtitleEdit/subtitleedit/issues/8209#issuecomment-2066205766

**Comment by TranslateFuture** [comment]
I apologize for the late reply, here are new sample videos/files, for mainly the large-v2 and also a few large-v3 .srt files.

[github subtitle edit new broken translations for korean chinese spanish etc.zip](https://github.com/user-attachments/files/16236831/github.subtitle.edit.new.broken.translations.for.korean.chinese.spanish.etc.zip)

![github translate new korean chinese spanish shuhua workdol broken subtitles comparison 1080p](https://github.com/user-attachments/assets/37f6d078-a9fb-4db4-8810-1d603d2abd24)

The Korean subtitles are for this wood-grilled chicken/part time variety show called Workdol: https://www.youtube.com/watch?v=ZHc5r2udNC8

The Spanish subtitles are for this debate Spanish countries video from Dreaming Spanish: https://www.youtube.com/watch?v=4jWV0LyPqs4

The English subtitles are for this about the Cantonese language video from JuLingo: https://www.youtube.com/watch?v=lVJI2wdtqEY

The Chinese subtitles are for this stereotypes about other Chinese speakers video from Mandarin Corner: https://www.youtube.com/watch?v=jppHjPIQGis

For the steps, I unchecked "Use post-processing" but have "Auto adjust timings" enabled since these shorter videos from Youtube don't have much trouble when "Auto adjust timings" is turned off. In some cases though, the other longer videos (like 1 hour+) seem to go out of sync, and this causes the .srt file from the start to be frozen or rarely change lines at all, but that's a separate issue.

The "Translate to English" is also enabled, and for the Subtitle Edit 4.0.7 version of the files, it just has the default --standard parameters/et cetera (this new section (added or displayed with a new interface after Subtitle Edit 4.0.3) could be the root of the situation too since if you change it, it won't start or translate at all or it'll output the same broken translations/etc.). Oh and yes, for Subtitle Edit 4.0.3 I changed it to the latest Faster-Whisper r192.3, which is how it's confirmed that Subtitle Edit is the one with the issues, not so much Faster-Whisper.

What seems to be the main problem is that after Subtitle 4.0.3, there were some changes with the breaks and merging of lines. And so this affected the easy auto-translate from that window of Faster-Whisper inside Subtitle Edit.

For example in that first few seconds of the Korean video, it should be "It's hot today, so let's warm up first." instead of the current "It's hot today, so let's warm up first Wow Ouch Wait a minute The original of the 20s" displayed (and not changing despite the different speakers/etc.). Because those other words are from a few seconds after/ahead and yup, it's randomly merged/capitalized/etc. 

With Subtitle Edit 4.0.3, it is able to automatically distinguish with greater accuracy when the sentence is supposed to end/start, and it also doesn't produce those random merged line with capitalizations all over the place.

The .srt files for the Chinese video somehow only outputted Chinese characters after a few seconds (this happens sometimes, same with the "No text found!" error message when translating longer/etc. videos, though again a different issue but wanted to mention it since it might be tangentially related), but still there you can see the differences between Subtitle Edit 4.0.3 and Subtitle Edit 4.0.7. The words/sentences are somehow being merged together instead of forming new lines due to like the breaks/etc.

I apologize once more if I cannot describe the problem clearly since I am pretty new to all this, please check the files and screenshot, as the differences are immediate there if you pair them with the videos I linked above.

Thank you guys again for making Subtitle Edit/Faster-Whisper/etc. work so well together, it's so amazing and a dream come true.

**Comment by TranslateFuture** [comment]
Oh, I forgot to add the proper subtitles included with that Korean part time chicken worker video. The timing or breaks/merged lines differences is easier to see with it.

[경력직 짬바로 가볍게 왔다가 불 맛 제대로 봄...🔥ㅣ워크돌ㅣ통닭집ㅣ엔믹스 해원X(여자)아이들 슈화-1080p.en.vtt.zip](https://github.com/user-attachments/files/16237487/X.-1080p.en.vtt.zip)

**Comment by Purfview** [comment]
Problem is that translation sometimes has missing punctuations, and "--standard" joins the lines without periods.

I can force a better punctuation when translating in the next version of Faster-Whisper-XXL.
