### ISSUE TITLE
Does not create subtitles whith --diarization parameter

### ISSUE THREAD

**Issue by RAM512** [SubtitleEdit/subtitleedit#8639]
I tried to perform transcription with diarization using the --diarization parameter for the CPP and CPP cuBLAS engine.
In the input video, the audio parameters are as follows: Audio: AAC 44100Hz stereo 96kbps

As a result, subtitles were not created.
whisper_log:
error: failed to read WAV file 'C:\Users\taker\AppData\Local\Temp\ba0d1aae-f664-40bc-8f3d-4b4a959263ec.wav'

read_wav: WAV file 'C:\Users\taker\AppData\Local\Temp\ba0d1aae-f664-40bc-8f3d-4b4a959263ec.wav' must be stereo for diarization

If you run transcription without additional parameters, then recognition occurs correctly and subtitles are created.

**Comment by niksedk** [comment]
How good is the diarization?
Seems to be only for the small model?
Also, it's experimental... sounds like a too shaky feature!

**Comment by RAM512** [comment]
I do not know how good this feature is, because this is the first time I have met with it myself. I was asked to find a transcription with diarization and I'm trying to find the easiest way for a person who doesn't know how to use a computer well.

I also found the possibility of diarization in WhisperX, but I don't know how to create whisperx.exe which SE asks for.
