### ISSUE TITLE
4.0.7 does not install all the languages for menus

### ISSUE THREAD

**Issue by MediaExpres** [SubtitleEdit/subtitleedit#8640]
It happened I installed from zero 4.0.7. and no Romanian option in the menu languages, in settings.  A lot of more languages have disappeared.

I am installing 4.0.7 over 4.0.6., this does solve the issue. But it's not normal.

**Comment by niksedk** [comment]
Thx for the info - it seems that the version number was old... 4.0.5 
Fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

**Comment by MediaExpres** [comment]
Ha. Thanks.
