### ISSUE TITLE
2 min of 24 min not translate spanish to english

### ISSUE THREAD

**Issue by johnfelipe** [SubtitleEdit/subtitleedit#8644]
pls review why translation spanish to english give me entire 2 min in spanish not in english

![SNAG-0484](https://github.com/user-attachments/assets/73e1a19b-c5e5-4621-be16-c73c4c9b9438)

pls tell me how can fix this issue

**Comment by niksedk** [comment]
What exactly are you doing and where?
Also, do attach your subtitle file.

**Comment by johnfelipe** [comment]
[pgj-gukb-rca (2024-07-17 11_01 GMT-5).zip](https://github.com/user-attachments/files/16273279/pgj-gukb-rca.2024-07-17.11_01.GMT-5.zip)

if u see in srt

until 235 is good in english
but  236 to 253 not translate to english

im use whisper large v3 and use option for translate to english

**Comment by niksedk** [comment]
Generally v2 is preferred over v3

I will need the video to test this... but you should probably translate using Google or DeepL.
