### ISSUE TITLE
Can't install Faster-Whisper-XXL

### ISSUE THREAD

**Issue by shanedk** [SubtitleEdit/subtitleedit#8645]
I'm trying to install and use Faster-Whisper-XXL with no luck. It gives me the download link, and I extracted the files to `%APPDATA%\Subtitle Edit\Whisper\Purfview-Whisper-Faster`. Repeatedly, it keeps giving me the link to download and install the requested files even though I've already unzipped them into the folder.

Unzipping makes a subfolder called `Faster-Whisper-XXL`. I tried moving the files in that folder up one level so they'd be in `Purfview-Whisper-Faster`; it still didn't work.

Presently, the files in `Purfview-Whisper-Faster` are:

```
_models

Faster-Whisper-XXL

license.txt
```

And the error it gives me shows that it cannot find the file, but doesn't give me any clue as to what file it's looking for or where:

```
An application error occurred in Subtitle Edit 4.0.7.0 - 64-bit -
Microsoft Windows NT 10.0.19045.0.

Please report at
https://github.com/SubtitleEdit/subtitleedit/issues with the
following information:

Error Message:
The system cannot find the file specified

Stack Trace:

at
System.Diagnostics.Process.StartWithCreateProcess(ProcessSta
rtlnfo startlnfo)

at
Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.Get
WhisperProcess(String waveFileName, String model, String
language, Boolean translate, DataReceivedEventHandler
dataReceivedHandler)

at
Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.Tra
nscribeViaWhisper(String waveFileNamet String
videoFileName)

at
Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.But
tonGenerate_Click(Object sender, EventArgs e)

at System.Windows.Forms.Control.OnClick(EventArgs e)

at
System.Windows.Forms.Button.OnMouseUp(MouseEventArgs
mevent)

at System.Windows.Forms.Control.WmMouseUp(Message&
m, MouseButtons button, Int32 clicks)

at System.Windows.Forms.Control.WndProc(Message& m)

at System.Windows.Forms.ButtonBase.WndProc(Message&
m)

at System.Windows.Forms.Button.WndProc(Message& m)

at System.Windows.Forms.NativeWindow.Callback(lntPtr
hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)
```

**Comment by niksedk** [comment]
The files should be placed like this:
![image](https://github.com/user-attachments/assets/3bad5b15-d05b-4ff4-a0d6-f7ba7d71d2f3)

**Comment by shanedk** [comment]
This is what mine looks like. I don't have whisper-faster.exe or .cache. Are those needed?
![explorer_pP15soip5S](https://github.com/user-attachments/assets/97dc911f-c99f-421a-9173-1768cb014195)

**Comment by niksedk** [comment]
Thx for explaining :)
That's a bug... should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
