### ISSUE TITLE
Error as I loaded a small video and attempted to generate

### ISSUE THREAD

**Issue by morrellaberdeen** [SubtitleEdit/subtitleedit#8647]
Error as I loaded a small video and attempted to generate. See the screenshot with error details.
![Subtitle Edit - Screenshot of Error](https://github.com/user-attachments/assets/374263ec-bee5-473e-9313-bd60b4d33321)

**Comment by niksedk** [comment]
Could you attach or link the input video file?

**Comment by morrellaberdeen** [comment]
Please see the attached video file. I did not realise at the time, that it had no audio in the video. However, it should be a matter of concern that a crash occurred.

https://github.com/user-attachments/assets/630c79b8-ef27-40ea-9c0d-db3b27a13844

**Comment by niksedk** [comment]
Thx for the info :)

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
