### ISSUE TITLE
Filter preferred languages automatically to Batch convert

### ISSUE THREAD

**Issue by mpek** [SubtitleEdit/subtitleedit#8648]
I have an idea to make the process of choosing the languages in batch convert quicker. 

It would be nice to define the preferred languages to show in list before dropping them into that window. With many files you always have to go through the list, which subtitles to convert and delete the others manually. This is a task for a computer to filter quickly. 

I think about a window to show all available languages in one area and the other area to show the preferred languages and a default set entry for all languages for sure. 

What do you think?

**Comment by niksedk** [comment]
Sorry, I have no idea what this is about...
Can you explain better? A few screenshots would help too?

**Comment by mpek** [comment]
I'd like to define languages, and when throwing in video files into batch converter, only my preferred languages should be shown to convert.

**Comment by niksedk** [comment]
Please attach some screenshots!

**Comment by mpek** [comment]
How? This computer is not available for time travel.

**Comment by mpek** [comment]
Not interested in implementing a filter by language to batch convert then?

**Comment by niksedk** [comment]
Sorry, I do not understand what you mean...

**Comment by mpek** [comment]
When you throw in different video files that have multiple subtitles in them, not always all languages are necessary to convert, therefore it would be time saving if SE would allow to filter by languages before dropping the files into SE, but SE needs to be told which languages to show. 
At the moment you can only delete languages manually, that you don't want to convert. This takes long, when there are many files to work on. 
Do you think such a filter would be handy for others too?

**Comment by niksedk** [comment]
OK, I might understand a bit now (screenshots are really good for explaining though!).

You can probably use this:
![image](https://github.com/user-attachments/assets/2b83991f-1c31-46b9-a5f5-0cd37e5de1e1)

**Comment by mpek** [comment]
Yeah, thank you this is what I meant, but is it possible to define more than one language to be filtered in that box? "Help"-Site seems to be down atm.

**Comment by mpek** [comment]
I meant if it's possible to define more than one language at once in that filter you showed in that screenshot? Perhaps separated by comma?
