### ISSUE TITLE
Waveform stopping issues

### ISSUE THREAD

**Issue by Allen0522ty** [SubtitleEdit/subtitleedit#8649]
Hello. I am a Korean user of Subtitle Edit. I am experiencing an issue where the waveform stops for a moment when I enter to a subtitle. What can I do to solve this problem? Down is the video I recorded.
I appreciate your support!

https://github.com/user-attachments/assets/291352e1-fd4f-4b6e-8bc6-c4b793adf29e

**Comment by Allen0522ty** [comment]
I don't even know if this is the right place to write this, but I could't find the answer anywhere else.. Pls understand

**Comment by niksedk** [comment]
@Allen0522ty: You might need a faster computer, sorry. 
Also, you could try "mpv" as video player or direct show (via https://github.com/Nevcairiel/LAVFilters/releases - use the installer)

**Comment by Allen0522ty** [comment]
Ok thanks!!🥲🥲🥲
