### ISSUE TITLE
I get an error when correcting an error

### ISSUE THREAD

**Issue by Hardstylest** [SubtitleEdit/subtitleedit#8651]
After I've translated the subtitles from English to German, I fix any errors. This time, though, I got an error message like the one in the screenshot! It doesn't help if I click on repeat or ignore. The only thing that helps is to cancel, and then the program closes.

![Unbenannt](https://github.com/user-attachments/assets/a799a095-8946-43dc-907e-69e55960156d)

hope you can help?!
greetz

**Comment by niksedk** [comment]
Can you attach the subtitle file?

**Comment by Hardstylest** [comment]
sure
[until.zip](https://github.com/user-attachments/files/16321430/until.zip)

**Comment by niksedk** [comment]
Thx for the info :)

The crash should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

**Comment by Hardstylest** [comment]
> Thx for the info :)
> 
> The crash should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

thx a lot 👍
