### ISSUE TITLE
Unable to append subtitle and sync using Visual Sync

### ISSUE THREAD

**Issue by improck** [SubtitleEdit/subtitleedit#8652]
Using the release SE407. My use case is that I have an anime OVA that is three parts combined into one video. I have three separate .ass subs that I'd like to combine and add to the new full-length video. Each .ass file starts from the beginning of the episode. The first file (sub1) is already synced. The second and third (sub2 and sub3) need their times to be offset in order to sync with the video. I tried to append sub2, but can't get past the Visual Sync.

### Repro
- Opened the first sub file (sub1) in the SE main window
- Selected the _Tools/Append Subtitle..._ menu option; answered Yes
- Selected the next sub file (sub2); this opened the Visual Sync tool
- Added the video with the three combined parts of the OVA (30min each, ~1.5hrs total)
- Jumped forward in the "start scene" to the time when the first line of the sub2 is spoken and selected the first line from the dropdown.
- Jumped forward in the "end scene" to the time when the last line of the sub2 is spoken and selected the last line from that dropdown.
- Clicked Sync

### Result
Received an error message of "Start scene must come before end scene." This is unexpected because the start times chosen _do in fact_ come before the chosen end times.

### Expected
The start and end times for each line in the sub should be adjusted. Then, click OK to append to the current sub.

### Notes
I went to have a look at the code and found the following:

https://github.com/SubtitleEdit/subtitleedit/blob/c1fe42fac9d43b5c36a72658f6c2c61ecc80a436/src/ui/Forms/VisualSync.cs#L460

I believed that `subEnd > videoPlayerCurrentStartPos` should actually be `subEnd > subStart`. So, I cloned the repo and tried it out in a branch from the 407 tag. Appending the sub works after the change.

**Comment by niksedk** [comment]
Thx for the bug report + very precise description :)

Is not committed + included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
