### ISSUE TITLE
[Feature Request] Auto-Translation: Google Gemini API Settings

### ISSUE THREAD

**Issue by rikimtasu** [SubtitleEdit/subtitleedit#8655]
Would it be possible to add advanced setting with Google Gemini API?
like Safety settings so we can turn it off when needed
https://ai.google.dev/gemini-api/docs/safety-settings
and switching model to the more recent gemma 2 27b

**Comment by niksedk** [comment]
Hm, that's *really* bad documentation... can anyone find a simple curl example of calling with a model name?

Better documentation links are welcome!

A PR is also welcome.

**Comment by rikimtasu** [comment]
Would those two be any useful?
https://ai.google.dev/gemini-api/docs/get-started/tutorial?lang=python
https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models
it is a entire different kind of software but LunaTranslator had gemini-api code too. it should be useful.
https://github.com/HIllya51/LunaTranslator

**Comment by niksedk** [comment]
Sorry, I cannot see anything useful in the docs

Try using another provider...
