### ISSUE TITLE
SE crashing when opening Whisper

### ISSUE THREAD

**Issue by JDTR75** [SubtitleEdit/subtitleedit#8656]
As the title says, SE is crashing when opening Audio to Text (Whisper).

This is on SE 4.0.7 Beta 42.

https://github.com/user-attachments/assets/676d3157-5859-4c29-9265-cc3dd289a55d

**Comment by niksedk** [comment]
I cannot re-create this... do you have some logs?
What OS are you running?
se error log or event log?
You can also try to re-download ffmpeg.

**Comment by JDTR75** [comment]
I'm using Windows 11.
Couldn't see anything on the [error_log.txt](https://github.com/user-attachments/files/16338095/error_log.txt)
I can't see anything in the event log either:
![image](https://github.com/user-attachments/assets/8d47614c-7cfa-4e2a-ac2d-773ae29e04bc)
I re-downloaded ffmpeg but still the same issue.

I reverted to SE 4.0.7 stable version and it's working fine that way.
Lmk if I can share anything else with you to figure this out.

**Comment by niksedk** [comment]
Sorry, I cannot re-create this or have any ideas...

**Comment by JDTR75** [comment]
Here you go @Purfview 
![image](https://github.com/user-attachments/assets/9fe524a4-1484-4311-966e-a4c91099dda5)

I´ve just updated to Beta 61 and it's only crashing when I select Purfview's model.

**Comment by JDTR75** [comment]
Still crashing - even if I completely remove Faster Whisper XXL.
However, I did notice something.
I extracted a clean SE version in a different folder, downloaded everything from scratch (ffmpeg, Faster Whisper -the old one-, some models) and it's not crashing. So idk what's going on.
Again, if I revert to SE 4.0.7 Stable on my "regular" SE folder, everything works fine

**Comment by Purfview** [comment]
>Faster Whisper -the old one-

Faster Whisper XXL?

**Comment by JDTR75** [comment]
Faster Whisper XXL is also working fine in the clean SE I extracted in a separate folder. I think it's something related to my Settings file @niksedk.
Here's MY Settings file [Settings.zip](https://github.com/user-attachments/files/16383642/Settings.zip).
And here's the Settings file from the clean extraction: [Settings.zip](https://github.com/user-attachments/files/16383649/Settings.zip).
