### ISSUE TITLE
Problem with auto translate and unnecessary line breaks generation

### ISSUE THREAD

**Issue by Dyo-Anima** [SubtitleEdit/subtitleedit#8658]
In subtitle edit 4.0.7 stable when using auto translate it splits the line unnecessarily and harming the translation and its correct interpretation, in the case of Spanish it is very damaged by this, it happens with all the translation engines.
I also noticed that the translation goes to incorrect lines for some reason, it happens sometimes and with very long lines.
Using LLM studio I could observe that subtitle edit is splitting the lines before translating them.

Personally I think that the default behavior should be to translate the whole line and the user should decide to split it later as needed.

It is very annoying that it splits very short lines, I am not sure if it is a misconfiguration or a bug, I am using the default options, let me know.

As a extra I use srt and ass

Thanks for reading and thanks a lot for the great work with the program, I hope my problem will be solved.
![imagen](https://github.com/user-attachments/assets/4a28d696-1c59-4025-b872-0d170b8d41ec)

[sub.zip](https://github.com/user-attachments/files/16340792/sub.zip)

**Comment by niksedk** [comment]
Hm, I cannot re-create this:
![image](https://github.com/user-attachments/assets/fa16a87a-168a-495f-9489-e7736457332a)

Note that you can change line merge strategy in the "Advanced" window.

**Comment by Dyo-Anima** [comment]
Thanks for replying, it may be my fault for updating incorrectly (I'm not sure of anything) I deleted the “Settings.xml” file and it was fixed, I can't offer more information because I don't know what could have caused it. I'm sure it was my fault.
