### ISSUE TITLE
Release libSE 4.0.7 on nuget ?

### ISSUE THREAD

**Issue by BarbUk** [SubtitleEdit/subtitleedit#8661]
Hi,

Would it be possible to release `libse` 4.0.7 on [nuget](https://www.nuget.org/packages/libse/) ?
I'm trying to update it to check an issue with multiple ErrorCount returned while parsing subtitles with `LoadSubtitle`.

[Jellyfin issue](https://github.com/jellyfin/jellyfin/issues/12113).
[Code using libse](https://github.com/jellyfin/jellyfin/blob/2b0082bf15c8ea0c4248c1fcd2d2558c047e237f/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs#L52-L59).
Example of error:
```
Jul 12 12:20:15 jellyfin[99]: [12:20:15] [ERR] 547 errors encountered while parsing 'srt' subtitle using the SubRip format parser
```

**Comment by niksedk** [comment]
OK, 4.07 is on the way...

You can probably do something like this in 4.07:
````c#
public SubtitleTrackInfo Parse(Stream stream, string fileExtension)
{
   var subtitle = Subtitle.Parse(stream, fileExtension);
   if (subtitle == null)
   {
      throw new ArgumentException("Invalid subtitle with file extension: " + fileExtension);
    }
   ...
````

I presume the stream contains a valid .srt file? It would be interesting to try the actual file...

**Comment by BarbUk** [comment]
Thanks for the new version on nuget.
I did test the new version (only changing the vendor), and the issue seem fixed.
