### ISSUE TITLE
 I can't save/download subtitle

### ISSUE THREAD

**Issue by GeaninaGula** [SubtitleEdit/subtitleedit#8672]
Hello,

I have a problem. I subtitled a 48-minute video and now at the end I can't save/download. What should I do or how should I proceed to be able to save the subtitle?

**Comment by niksedk** [comment]
Please add a few screenshots, thx.

**Comment by niksedk** [comment]
Normally you press the `Save` button or use File - Save as...

**Comment by GeaninaGula** [comment]
![imagine_2024-07-26_085819226](https://github.com/user-attachments/assets/c75a7ad3-5ad6-489f-a6f7-116d44f5a4d7)

**Comment by GeaninaGula** [comment]
I pressed but it doesn't work

**Comment by GeaninaGula** [comment]
and the open button doesn't work either, you can't load a file with subtitles

**Comment by niksedk** [comment]
Should be fixed now :)

**Comment by GeaninaGula** [comment]
Thank You very much :)
