### ISSUE TITLE
Auto-translate issues with aligning subtitles

### ISSUE THREAD

**Issue by joseph2mi** [SubtitleEdit/subtitleedit#8682]
As many other closed issues have commented before, when auto-translating (no matter the model), certain lines are merged or broken up automatically, which cause the original and translated subtitles to not be aligned. 

Previous closed issues have said just use "translate each line separately," but this has it's own problems. The whole reason I'm using default is because I want to use AI translators to translate the lines "in context." If you translate the lines separately, the lines, tenses, and pronouns sometimes do not flow. 

What I need is for the lines to be "translated separately" but translated within the context of the surrounding lines. Basically, I want "Default" auto-translate but without the translated text merging and breaking up lines automatically.

I know this is possible, because I just copy lines in ChatGPT with the sequence numbers and timestamps and tell it to translate. Each original line aligns with the translated line. However, with long .srt files, subtitleedit is meant to do it in a faster, more automatic way.

**Comment by jeff11-1-1** [comment]
you could possibly adjust the prompt you are using if you're using an LLM. For example, you could add a special character after each line (like when translating using copy - paste) and provide the entire srt file after adding the character, and ask the LLM to keep the special character you set in the translation, that way, it should get the entire context and keep each line separate. It might take some trying to get to the perfect prompt but this should be achievable.
