### ISSUE TITLE
Why is the srt empty after successfully recognizing subtitles in audio to text

### ISSUE THREAD

**Issue by BlueSkyCaps** [SubtitleEdit/subtitleedit#8683]
As shown in the figure below, when I use Pufview's Faster engine, the subtitle file srt is successfully generated, but the srt content is blank
![image](https://github.com/user-attachments/assets/9ee10c17-0058-4add-ac64-366e55e7618f)
![image](https://github.com/user-attachments/assets/0418aad3-ae66-4dca-8e36-765ffc83a4cc)
The same goes for the CPP engine
my pc：
NVIDIA GTX 1660
Intel i5 9400f

However, when I use my laptop: AMD's CPU and integrated graphics, using Pufview's Faster, the subtitles have content：
![image](https://github.com/user-attachments/assets/790d3ae7-6ca2-4c68-afd9-715ee7b1e834)

**Comment by niksedk** [comment]
You might be able to find more information in the file ` whisper_log.txt` in the SE data folder (press Ctrl+Alt+Shift+D in the SE main window to open the SE data folder)

**Comment by BlueSkyCaps** [comment]
> You might be able to find more information in the file `whisper_log.txt` in the SE data folder (press Ctrl+Alt+Shift+D in the SE main window to open the SE data folder)

**think you，I use the following command:**

_whisper-faster.exe --language zh --model "medium" --standard "xxx.mp4"_

**I executed this command on my intel computer and output the following:**

_Standalone Faster-Whisper r192.3 running on: CUDA_
_Starting work on: xxx.mp4_
_Could not load library cudnn_ops_infer64_8.dll. Error code 126_
_Please make sure cudnn_ops_infer64_8.dll is in your library path!_

**However, when I execute this command on my AMD laptop, the output is:**
_Standalone Faster-Whisper r192.3 running on: CPU
Starting work on: E:viedo draftxxx.mp4
[00:00.000 --> 00:03.880]xxxxxx
.......
Transcription speed: 1.04 audio seconds/s_
**So my AMD laptop successfully generated subtitles with content.
Sorry how can I fix it, I think the easier way would be to have it always execute as cpu instead of CUDA**

**Comment by niksedk** [comment]
Try to locate your `cudnn_ops_infer64_8.dll` file... and add the path to your environment 
See https://www.google.com/search?client=firefox-b-d&q=windows+add+path+to+environment+variable

I can see others have the same problem: https://stackoverflow.com/questions/66355477/could-not-load-library-cudnn-ops-infer64-8-dll-error-code-126-please-make-sure

I do not have an nvidia GPU, so I cannot really test this, sorry.

**Comment by niksedk** [comment]
You can run via CPU with the parameter `--device CPU`:

![image](https://github.com/user-attachments/assets/6c333442-0bf1-4eb3-9f83-8719f29cad31)

**Comment by BlueSkyCaps** [comment]
> 您可以使用以下参数通过 CPU 运行：`--device CPU`
> 
> ![图像](https://private-user-images.githubusercontent.com/1261331/352807726-6c333442-0bf1-4eb3-9f83-8719f29cad31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjY5MDMsIm5iZiI6MTcyMjE2NjYwMywicGF0aCI6Ii8xMjYxMzMxLzM1MjgwNzcyNi02YzMzMzQ0Mi0wYmYxLTRlYjMtOWY4My04NzE5ZjI5Y2FkMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMTEzNjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ2MjBiYzYzMjJlNGZhYjFhYWI1MzcyNWU0ZTM4OTgyZjAwMGU1Mzc3ODQ2MDBlN2MwZTRjNjg2YWQ4MGQ4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9tiim9ZTRfxFXhIInM_3giVIVbKje-la63an55dlHZs)

Yes, I was about to reply to you, I found a way to do the same as you: add --device "cpu"

![temp_AzrppR](https://github.com/user-attachments/assets/f99b81b2-4873-4cf2-a975-a91029dd5065)
![temp_gJsSFI](https://github.com/user-attachments/assets/84f96dea-c58a-47d0-bbe9-58a4b7cda991)
Thank you for your help, thank you

**Comment by niksedk** [comment]
OK, I'm glad it's working for you now :)

If you have a lot of audio to transcribe you still might want to look at the CUDA issue.

**Comment by Purfview** [comment]
>Could not load library cudnn_ops_infer64_8.dll. Error code 126

You need to install cuBLAS and cuDNN libs:
https://github.com/Purfview/whisper-standalone-win/releases/tag/libs

**Comment by BlueSkyCaps** [comment]
> > Could not load library cudnn_ops_infer64_8.dll. Error code 126
> 
> You need to install cuBLAS and cuDNN libs: https://github.com/Purfview/whisper-standalone-win/releases/tag/libs

yes，i tried it and it was work good！thank you！
