### ISSUE TITLE
Can it display the subtitles block?

### ISSUE THREAD

**Issue by lhj5426** [SubtitleEdit/subtitleedit#8684]
Hello, developers.

I often work with videos that have no spoken dialogue, only hardcoded subtitles. Therefore, when editing, I mainly work with the visual timeline. To achieve precise frame-by-frame alignment of subtitles and hardcoded subtitles in the video, could a feature be added to the software to display something like a subtitle block?

![image](https://github.com/user-attachments/assets/2b1eb9de-b2ef-4ca6-976a-1e4ca0de1aa8)
![image](https://github.com/user-attachments/assets/6cb064d9-3573-4d5b-bf67-6a9c717f4456)
 
 
![image](https://github.com/user-attachments/assets/c841575b-b48d-4b15-bd95-1a28932389aa)
"Just like this, it would make adjustments more convenient, more intuitive to understand, and easier to modify."

![image](https://github.com/user-attachments/assets/f96b6569-3b62-473d-8d51-b621e3c6aeec)

"The default display is not very noticeable and makes it difficult to see the exact timing of a single line of subtitles. Adjustments are also quite troublesome. Could you consider this?"

"Because there are hardcoded subtitles, adjustments must be frame-by-frame, with no deviations allowed. The other software I demonstrated in the screenshot has an intuitive subtitle block display feature, but it lacks precise frame-by-frame accuracy and has some discrepancies.

I've searched the entire internet and haven't found a suitable tool. This tool is the best I've found, but it still lacks the subtitle block feature. I sincerely hope that the subtitle block feature can be added. Thank you."

**Comment by niksedk** [comment]
A block takes up full height in the waveform.

**Comment by lhj5426** [comment]
"It's because of this that it's hard to see clearly and distinguish the spacing between each subtitle, making it very tiring to read."
![image](https://github.com/user-attachments/assets/437f0368-e503-4c85-8ff5-2dd06b11bbc5)
