### ISSUE TITLE
SE crashes with Faster-Whisper engines

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#8688]
Windows 11 with SubtitleEdit 4.0.7 NEXT, beta 82.

After installing Subtitle Edit, after choosing "Video/Audio to text (Whisper)", and after the downloading of ffmpeg has been completed:
When selecting the engine "Purfview's Faster-Whisper" or the engine "Purfview's Faster-Whisper-XXL", the error "A new guard page for the stack cannot be created" appears. Then after clicking on "OK", Subtitle Edit crashes and disappears. This problem occurs only with the two "Purfview's Faster-Whisper" engines.
![Error with Faster-Whisper](https://github.com/user-attachments/assets/27481c10-f27e-4982-8ff8-2e04e6e111da)

**Comment by niksedk** [comment]
You're most likely out of memory, sorry.

**Comment by oep42** [comment]
I doubt that a lack of memory explains the problem.

Installed memory:
![SE Problem - Installed RAM](https://github.com/user-attachments/assets/25958251-3d44-46fd-9acc-9f71b00349c6)

Memory use just before starting SE:
![SE Problem - Memory use before starting SE](https://github.com/user-attachments/assets/a207480d-df7f-4609-96cd-6a776e32d047)

**Comment by niksedk** [comment]
What happens if you run the "whisper-faster.exe" file in a command line prompt?

64-GB is *sooo* good to have :)

**Comment by oep42** [comment]
I looked into this some more.

With SE Version 4.0.7, the problem which has been reported above, does not exist. A "Faster whisper" .7z file is downloaded and a dialog box with this message appears: <<<Unpack and copy files from "Faster-Whisper-XXL" to: "C:\Users\[User]\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster">>>. After closing this dialog box, a "Windows Forms Thread Exception" error appears, as was reported as issue 8645.

I noticed that SE Version 4.0.7 does not recognize/use my "Settings.xml" file that I put in the installation folder immediately after installing.

Is this a known problem, that a "Settings.xml" file is ignored bij SE?

With SE version 4.0.7 NEXT beta 82, I put my "Settings.xml" file in the installation folder immediately after installing, and this settings file was recognized/used. (I did not say above, that I put my "Settings.xml" file in the installation folder of SE version 4.0.7 NEXT beta 82, before starting SE.)

Perhaps some settings in my "Settings.xml" file may be in some way related to the problem reported above. So I deleted my "Settings.xml" file from the installation folder of SE version 4.0.7 NEXT beta 82. Then I started SE version 4.0.7 NEXT beta 82 and choose "Video/Audio to text (Whisper)". Then immediately a sub dialog box "Download Purfvieuw's Faster-Whisper" appeared. My conclusion: Some setting(s) in my "Settings.xml" file is (are) indeed in some way related to the problem reported above.

This is is my zipped settings file:
[Settings.zip](https://github.com/user-attachments/files/16443673/Settings.zip)

PS. I did not run "whisper-faster.exe" or "ffmpeg.exe" in a command prompt, because I saw your last message only after preparing this message. I can run those programs later, if the info in this message does not help to find a solution to the problem.

**Comment by niksedk** [comment]
The beta version should be unpacked to something like C:\Tools\SE - do not put it under "Program files".

**Comment by oep42** [comment]
The beta version has been placed in "C:\SEbetaWin11-01".

**Comment by oep42** [comment]
Thanks for looking into this. Too bad you cannot recreate the problem.

When I reuse my "Settings.xml" file in SE version 4.0.7 NEXT beta 82, the error "A new guard page for the stack cannot be created" appears when selecting one of the two Purfview Faster Whisper engines.

After deleting my "Settings.xml" file in SE version 4.0.7 NEXT beta 82, I was able to download one of those engines and use it to generate subtitles.

When I, after that, add my "Settings.xml" file again to SE version 4.0.7 NEXT beta 82, the error "A new guard page for the stack cannot be created" appears when selecting one of the two Purfview Faster Whisper engines. So SE version 4.0.7 NEXT beta 82 can be used with my "Settings.xml" file except for the two Purfview Faster Whisper engines.

I will now redefine the problem as not being able to reuse my old "Settings.xml" file in SE version 4.0.7 NEXT beta 82 when I want to use one of the two Purfview Faster Whisper engines. Also, with SE Version 4.0.7, I cannot reuse my "Settings.xml" file at all, because it is ignored by SE.

I will later look into this again. I am going to try to create a new "Settings.xml" file in SE version 4.0.7 NEXT beta 82, by changing its default settings until I have recreated all the settings of my old "Settings.xml" file. If this is possible, I will try reuse this new "Settings.xml" file with both SE version 4.0.7 NEXT beta 82 and SE Version 4.0.7.

**Comment by niksedk** [comment]
OK, I could actually re-create the issue with the Settings.xml file, thx :)

It seems SE made en endless loop (and probably used all of your 64 GB RAM).
Should  now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

**Comment by oep42** [comment]
Sorry, I made a mistake when placing the "Settings.xml" file for SE Version 4.0.7. I placed it in "C:\Program Files\Subtitle Edit", while I should have placed it in "C:\Users\[username]\AppData\Roaming\Subtitle Edit". When placing the "Settings.xml" file in the right location, it is used by SE Version 4.0.7 as expected.

After correctly placing the "Settings.xml" file for SE Version 4.0.7, I succeeded in downloading one of the Purfview Faster Whisper engines with SE Version 4.0.7 without the error "A new guard page for the stack cannot be created" appearing. I could also use that engine to generate subtitles.

PS. I saw your last message only after preparing this message. I am happy the error could be recreated and fixed after all. I will now try the latest beta.

**Comment by oep42** [comment]
Using SE version 4.0.7 NEXT beta 99.

The error "A new guard page for the stack cannot be created" did not occur.

FIRST DOWNLOAD: 
When downloading "Purfview's Faster-whisper" when asked to do so in the "Audio to text" dialog box, "Purfview's Faster-whisper-XXL" (= "Faster-Whisper-XXL_r192.3.4_windows.7z") was directly downloaded to my default download folder. This is unexpected. I expected that the file "whisper-faster.exe" would be downloaded.

SECOND DOWNLOAD:
When downloading "Purfview's Faster-whisper-XXL" when asked to do so in the "Audio to text" dialog box, "Purfview's Faster-whisper-XXL" (= "Faster-Whisper-XXL_r192.3.4_windows.7z") was downloaded to my default download folder via a browser that was opened automatically. (This download via a browser, was much slower than the earlier direct download of the same file.)

If I remember well, only after that second download, a useful dialog box appeared with an instruction about what to do with the downloaded file.

I would prefer a direct download without opening a browser to do the downloading. It was possible to download the file "Faster-Whisper-XXL_r192.3.4_windows.7z" without opening a browser to do the downloading, so I would suggest not to use a browser for downloading that file.

With this version of SE, it is not possible to download "Purfview's Faster-whisper" (= "whisper-faster.exe").

**Comment by niksedk** [comment]
I could not re-create the "faster whisper" issues. Works fine on my machine.

The "XXL" is a 7zip file, which is not built into dotnet, so cannot easily unpack this file by itself.

About the UI, I think you have some text scaling... 
UI is updated a tiny bit here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
The updated layout should look like this:
![image](https://github.com/user-attachments/assets/0f89c53d-53a5-4efa-b4cb-cf8a39ed978a)

**Comment by oep42** [comment]
Using SE version 4.0.7 NEXT beta 102.

The download of "Purfview's Faster-Whisper", when asked to do so in the "Audio to text" dialog box, now works as expected.

The download of "Purfview's Faster-Whisper-XXL", when asked to do so in the "Audio to text" dialog box, is done via a browser, and works as expected. When, after that, clicking on "OK" in the useful dialog box with the message <<<Unpack and copy files from "Faster-Whisper-XXL" to ...>>>, no "Windows Forms Thread Exception" error message appears.

I don't know why the size of the text in dialog boxes is bigger in my system than in yours. I may have changed some setting that causes this. Anyway, for those who have bigger sized text in dialog boxes, there is a clear difference now between the two Purfview engines in the engine pull-down menu. Thanks for the tiny UI update.

![Updated Dialog Box](https://github.com/user-attachments/assets/043fde3b-8214-475e-bceb-775869cd0be3)

I am happy that everything works as expected. Thanks a lot.

**Comment by oep42** [comment]
I am happy that everything works as expected. Thanks a lot.
