### ISSUE TITLE
STILL Can't install Faster-Whisper-XXL

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#8690]
( I don't know how to Re-Open a Closed Issue, so this should be a Comment to 
https://github.com/SubtitleEdit/subtitleedit/issues/8645 )

I've picked up the Beta 4.0.7 BETA 40, but the Faster-Whisper-XXL still can't be used.

When I click 'Open Models Folder' it's empty, so what should be in there?

![OpenModelsEmpty](https://github.com/user-attachments/assets/f1dc3ab1-6bfb-4b8a-8628-78671ecf50ab)

I have the other files in the Folders according to images in #8645.

**Comment by niksedk** [comment]
Click on the button on the three dots to download a model.

Also, to which folder did you unpack SE?

**Comment by niksedk** [comment]
Also, be sure to unpack to beta version to something like "C:\Tools\SE" and not under "Program files".

**Comment by Minherre** [comment]
I've already, several times, downloaded the 'Faster-Whisper-XXL_r192.3.4_windows.7z', and unpacked/put the files from it according to the images in that #8645 .

Do I have to download even more than that huuuge 1.1Gb file?

I have my SE in a folder of its own, not installed. 

\Portable-Subtitleedit\Whisper\Purfview-Whisper-Faster

**Comment by niksedk** [comment]
Have you downloaded a model?

**Comment by Minherre** [comment]
Ok, I've picked up a Model called 'medium.en (1.5GB)' and now it says
'Transcribing audio to text...' with an already filled green line underneath.

Perhaps it would be better if it could 'count down' so one can see that something is happening ?!
(But I can see, and Hear, that SpeedFan shows the CPU's getting hot hot hot... ;-)

**Comment by niksedk** [comment]
OK, sounds like it's better now.

You can try the tiny model and a small video to start with, if you want a result faster.

You can toggle F2 to see what's happening.

**Comment by Minherre** [comment]
Ok, that took from 19.35 - 20.52 = 1h17min, for a 50min video, but the Sub was Perfect!
There were plenty of names with very strange spelling, but all of them were spelled correctly!
(Unfortunately the video 'BBC.Timewatch.Julius.Caesars.Greatest.Battle' turned out to be quite boooring...)

When I earlier used vosk-model-en-us-0.22 for another 50min video, it took only like 20min,
but then the Sub wasn't perfect at all!

So perhaps I'll try a smaller Whisper Model later on some other video.

Have a look at the Sub with all those strange names spelled correctly!

(And one thing more; if one loads a Sub, and Only Change from 'UTF-8 with BOM' to 'UTF-8 without BOM' (from the TopMenu),
and then Exits, one don't get the question about Saving the Sub, so that change is lost, no good.

/Thanx a Lot!

[BBC.Timewatch.Julius.Caesars.Greatest.Battle.x264.AC3.MVGroup.org.en.zip](https://github.com/user-attachments/files/16450731/BBC.Timewatch.Julius.Caesars.Greatest.Battle.x264.AC3.MVGroup.org.en.zip)

**Comment by niksedk** [comment]
The utf-8 encoding change detect issue should now be fixed: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
