### ISSUE TITLE
Minor Issues in Generate Video with Burned in Subtitles

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#8691]
I've noted some issues with the Generate Video with Burned-in Subtiles Feature.

**1.** Reversed Resolution Dimensions and I'm assuming just in writing because this does not affect the output video when using **Batch Mode**

For example, the 1st video is a 1920x1080 video but reversed to 1080 x 1920

2nd video is a vertical video of 1080x1920 but it's reversed to 1920 x 1080 

![reversed resolution dimensions](https://github.com/user-attachments/assets/35c71900-53d4-42b7-bd5c-527258839097)

2. Error when re-encoding a video with or without subtitles to WebM in the Generate Video with Burned in Subtitles. 

https://github.com/user-attachments/assets/8f3433f9-52d5-498e-bf25-90e75ad6c32e

Thanks!

**Comment by niksedk** [comment]
Hm, I cannot re-create this...
