### ISSUE TITLE
Synchonization > Adjust all times is broken

### ISSUE THREAD

**Issue by markfilipak** [SubtitleEdit/subtitleedit#8695]
Both v.4.0.5+4.0.7

Synchronization > Adjust all times > Selected lines only
Synchronization > Adjust all times > Selected and subsequent lines

Neither works. All times are changed regardless of setting.

**Comment by niksedk** [comment]
Hm, works perfectly fine here... could you supply some screenshots and a subtitle file?

**Comment by markfilipak** [comment]
Howdy Boss,

![Selected and subsequent lines](https://github.com/user-attachments/assets/31e61d4a-ee4c-4311-a3ba-b00d48890138)
[00305+00306+00307+00308.zip](https://github.com/user-attachments/files/16461317/00305%2B00306%2B00307%2B00308.zip)

I tried selecting one entry and choosing "Selected and subsequent lines" and also selecting one entry and then the remaining entries to the end and choosing "Selected lines only".

**Comment by markfilipak** [comment]
Nikolaj,

I don't think this would make any difference: I'm running Win7-SP1.

**Comment by niksedk** [comment]
Please attach screenshots including the list view in the main window before and after adjusting.
Or make a video (.mp4 files can be attached here on GitHub.

**Comment by markfilipak** [comment]
Do you want to see that the time stamps prior to the change are also changing? Is that what you are seeking?

**Comment by niksedk** [comment]
Yes, I want to see the time codes in the list view before and after you press buttons in the adjust window.

**Comment by markfilipak** [comment]
![SubtitleEdit](https://github.com/user-attachments/assets/eb5d1bbb-15f2-434c-8ad5-45d4a0b24abb)

**Comment by niksedk** [comment]
Sorry, this only works in list view.

**Comment by markfilipak** [comment]
Thank you, Nikolaj. So, there's 2 modes and Synchronization works in only one of them, eh? Okay. I found list mode, and it does work. Thank you so much. :-)

**Comment by niksedk** [comment]
The selection will now be disabled in "Source view":

![image](https://github.com/user-attachments/assets/b0ae3803-575b-47eb-931f-af18e1c8259e)


Note that you can switch between "Source view" and "List view" by pressing F2 or via the context menu.
