### ISSUE TITLE
got an error message when converting the speech to subtitles using Purfview's Faster-Whisper.

### ISSUE THREAD

**Issue by hpcs444** [SubtitleEdit/subtitleedit#8697]
Hi, 

When i clicked "proceed" on the error-window,  "subtite edit" proceeded with converting text to speech using Purfviews's Faster-Whisper

greetz Harrie.

The error message itself: (it seems to be incomplete but this is all i got, i used online OCR utility to get the message in plain text)

An application error occurred in Subtitle Edit 4.0.7.0 - 64-bit - Microsoft Windows NT 10.0.22631.0.
Microsoft Windows NT 10.0.22631.0.
Please report at 
https://github.com/SubtitleEdit/subtitleeditfissues with the 
following information:

Error Message:
De indeling van de invoertekenreeks is onjuist.

Stack Trace:
bij System.Text.StringBuilder.FormatErrorQ
bij 
System.Text.StringBuilder.AppendFormatHelper(IFormatProvid 
er provider, String format ParamsArray args)
bij System.String.FormatHelper(IFormatProvider provider, 
String format ParamsArray args)
bij 
Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.Tra 
nscribeViaWhisper(String waveFileName, String 
videoFileName)
bij 
Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToTed.Ge 
nerateBatchQ
bij 
Nikse.SubtitleEdit.Forms.AudioToTed.WhisperAudioToText.But 
tonGenerate_Click(Object sender, EventArgs e)
bij System.Windows.Forms.Control.OnClick(EventArgs e)
bij 
System.Windows.Forms.Button.OnMouseUp(MouseEventArgs 
mevent)
bij System.Windows.Forms.Control.WmMouseUp(Message& 
m, MouseButtons button, Int32 clicks)
bij System.Windows.Forms.Control.WndProc(Message& m) 
bij System.Windows.Forms.ButtonBase.WndProc(Message& 
m)
bij System.Windows.Forms.Button.WndProc(Message& m) 
bij System.Windows.Forms.NativeWindow.Callback(IntPtr 
hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)

**Comment by tsg040** [comment]
I have the same problem. Last week the same configuration (subtitle 4.06) was working.

**Comment by niksedk** [comment]
Check the file `whisper_log.txt` in the SE data folder (press Ctrl+Alt+Shift+D in the main window)

Also, do test the latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
> The error message itself: (it seems to be incomplete but this is all i got, i used online OCR utility to get the message in plain text)

You can right-click and click on "Copy as text to clipboard", or just Ctrl+C to get the error/message text :)

![image](https://github.com/user-attachments/assets/c5f5d810-e9a6-4e68-b0c0-bf2e9485816b)

**Comment by tsg040** [comment]
The same with 4.07. 
----------------------------- Log.txt
Date: 08/03/2024 13:44:27
SE: 4.0.7.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: CUDA check reports: CUDA device: 0

**Comment by tsg040** [comment]
![Schermafbeelding 2024-08-03 141401](https://github.com/user-attachments/assets/75d32f3f-945b-4a75-8326-72d18ce76551)

This is the message

**Comment by niksedk** [comment]
Try adding as much information as possible... more logs + some screenshots of your whisper window. More is better :)

**Comment by niksedk** [comment]
Ah, seems to be a bug in the Dutch translation - should now be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

The Dutch translation could probably use an update...

**Comment by tsg040** [comment]
It is working again.
Thank you for the solution, and your time.
I am very pleased.
Have a nice weekend :=)

**Comment by hpcs444** [comment]
Hi Nikolaj

thank you for your answer about the Dutch translation, that was the
solution!
I selected the English language in Option->Choose Language and the problem
did not occur,
reselecting the Dutch language generated the error again. So i just select
English and the problem is over!

Thank you for you help!

Harrie  (from Linne, the Netherlands)




Op za 3 aug 2024 om 15:06 schreef Nikolaj Olsson ***@***.***>:
