### ISSUE TITLE
Waveform (spectrogram) GREEN VERTICAL LINE jumps in steps in version 4.0.7, and it is gliding in version 4.0.6.?

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#8699]
The spectrogram (waveform) on the bottom of the screen jumps (the green vertical line that shows the current position of the video) for some step in version 4.0.7, while it flows, glides continuously in version 4.0.6, I TESTED IT. Version 4.0.6 has a vertical green line that flows without any jumps. Why does this line JUMPS in version 4.0.7, instead of glide?  

It is very distracting. At first, I thought it was my bad observation, but I installed version 4.0.6 and saw that it was true. There is no pause in gliding in that version, while version 4.0.7 has a green vertical line that jumps, its move is not continual. I don't think it is some settings on my computer, because version 4.0.6 would act the same. Or, if it is, let me know. 

![Screenshot_3](https://github.com/user-attachments/assets/7c7e5d98-1b49-4dc0-ae5c-24e65961ac7d)

**Comment by niksedk** [comment]
It depends on the video player and video source.
mpv / directshow is best. VLC is really bad, but that should be fixed in VLC 4 (if it's ever released)

**Comment by Cyberyoda1411** [comment]
Thank you so much, Nikolaj. You are right. DirectShow video engine is the solution. I have it on 4.0.6 newly installed version, but on my 4.0.7, I had MpcHC video engine selected. You can remember when we had a conversation about the preview of the subtitle position, when we talked about the mpv video engine, and I clicked on the wrong MPCHC, instead to DirectShow when I set it as it used to be. My mistake.

You can close this topic.
