### ISSUE TITLE
Failure to completely download Faster Whisper models

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#8703]
Using Subtitle Edit 4.0.7 NEXT beta 106. Trying to download models for "Purfview's Faster-Whisper-XXL" engine.

Failure to completely download the "**faster-whisper-large-v2**" model, because SE tries to download a file that is not part of the files of this model (config.json, model.bin, tokenizer.json, vocabulary.txt).

![Failure to download faster-whisper-large-v2](https://github.com/user-attachments/assets/ae1fa9d6-3720-4d85-b1e6-219be4e82bb8)

After this failure to download all the files of this model, this model does appear in the "Choose model" pull-down menu. It would be better if this model would not appear in this pull-down menu when it is not completely downloaded.

----------------

Failure to completely download the "**faster-whisper-large-v3**" model, because SE tries to download a file that is not part of the files of this model (config.json, model.bin, preprocessor_config.json, tokenizer.json, vocabulary.json).

![Failure to download faster-whisper-large-v3](https://github.com/user-attachments/assets/3b91e4d9-6c31-4ff3-85d9-83d75e430f6c)

After this failure to download all the files of this model, this model does appear in the "Choose model" pull-down menu. It would be better if this model would not appear in this pull-down menu when it is not completely downloaded.

----------------

Failure to completely download the "**distil-large-v3**" model, because SE tries to download a file that is not part of the files of this model (config.json, model.bin, preprocessor_config.json, tokenizer.json, vocabulary.json).

![Failure to download distil-large-v3](https://github.com/user-attachments/assets/d0f8299d-1970-4f92-9b3a-241d7e99a04c)

After this failure to download all the files of this model, this model does appear in the "Choose model" pull-down menu. It would be better if this model would not appear in this pull-down menu when it is not completely downloaded.

----------------

Failure to completely download the "**distil-large-v2**" model, because SE tries to download a file that is not part of the files of this model (config.json, model.bin, preprocessor_config.json, tokenizer.json, vocabulary.json).

![Failure to download distil-large-v2](https://github.com/user-attachments/assets/3b61e51b-515c-43fb-b3db-713069be0e17)

After this failure to download all the files of this model, this model does appear in the "Choose model" pull-down menu. It would be better if this model would not appear in this pull-down menu when it is not completely downloaded.

**Comment by niksedk** [comment]
The files are part of the model, see https://huggingface.co/Systran/faster-distil-whisper-large-v2/tree/main

**Comment by niksedk** [comment]
Also, what does the file " vocabulary.json" file contains if it exists?
(please check your model folder and attach the file here)

**Comment by oep42** [comment]
I know, when a complete download of all files of a Faster Whisper model fails, that I then can download the missing files, by selecting that model in https://huggingface.co/Systran, then go to the "Files and versions" tab of that model, and download the missing files from there. But it would be much easier, when all those files would be downloaded by SE. (Also, it may not always be clear, exactly which files should be downloaded to get a complete model.)

The result of a failed download of the "faster-whisper-large-v2" model looks like this:

![Failed download of faster-whisper-large-v2](https://github.com/user-attachments/assets/89cfc064-646a-474a-bba7-fcaed0c17c3d)

The result of a failed download of the "faster-whisper-large-v3" model (and of the two "distil" models) looks like this:

![Failed download of faster-whisper-large-v3](https://github.com/user-attachments/assets/117fcca2-5947-4072-a1c0-e2cc2c588947)

**Comment by niksedk** [comment]
Sorry, I cannot re-create this.
What OS are you using?

**Comment by oep42** [comment]
Windows 11 Pro, Version 22H2, Build 22621.2506.

If I am the only one encountering this problem, I don't mind this issue to be closed, because I can download the missing files.

**Comment by niksedk** [comment]
Hm, I've tested on multiple machines with different settings (all win 11), and I am unable to re-create this.

**Comment by oep42** [comment]
Thanks anyway for looking into this.

**Comment by Beater34** [comment]
I have the same problem with Windows 11 Pro, version 121718 build 26200.8875 and Subtitle Edit v5.1.0-rc16 (26th of July 2026). When trying to install Faster Whisperer XXL large-v2, I get the error message "Download failed: preprocessor_config.json". Like oep42, I fixed the problem by downloading the file manually - but it would be good if it could be fixed in Subtitle Edit.
