### ISSUE TITLE
Problem during batch conversion of ASS files

### ISSUE THREAD

**Issue by SardanDev** [SubtitleEdit/subtitleedit#8707]
Hello, I've noticed that when batch converting .ass files, it doesn't place the Script Info etc. section at the top of the .ass file.

[Script Info]
; This is an Advanced Sub Station Alpha v4+ script.
Title: 
ScriptType: v4.00+
PlayDepth: 0
ScaledBorderAndShadow: Yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,10,1

[Events]

I noticed this while converting a .vtt file to .ass. I hope it can be fixed soon.

**Comment by niksedk** [comment]
OK, could you explain more?

**Comment by aaron-meyers** [comment]
I'm seeing the same problem. I have a source .vtt file in subtitles\00-initial folder and I'm outputting .ass file to subtitles\10-clean folder with the following command:
subtitleedit /convert .\subtitles\00-initial\orange-days-s01e01.ja.vtt AdvancedSubStationAlpha /outputFolder:subtitles\10-clean /overwrite

The resulting .ass file has no header, i.e. it is just a bunch of Dialogue: lines. However if I open the .vtt file in SubtitleEdit UI and save as to .ass it gets a header. So something specific to the CLI /convert command (or maybe include batch conversion from the UI as well, I haven't tried that).
