### ISSUE TITLE
Suggestion to add profiles to "Batch convert"

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#8711]
When using "Batch convert" for the same workflow, it is helpful that most options of "Batch convert" are being remembered. What if you want to use "Batch convert" for different workflows? Then you may have to change remembered options each time you run "Batch convert" with another workflow.

What could be helpful in such a situation, is the possibility to select a "profile" for "Batch convert", i.e. a predefined set of remembered settings for "Batch convert".

Suggestion: Add the possibility to define and select profiles for "Batch convert". With such profiles you can, after starting "Batch convert", choose from profiles for "Batch convert" that you defined earlier.

Subsettings of convert options that are shared (like with "Fix common errors" and "Multiple replace") cannot be unique for a profile. Other subsettings could be profile-specific.

**Comment by niksedk** [comment]
Sorry, too advanced
