### ISSUE TITLE
Not possible to play a subtitle

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#8712]
Using Subtitle Edit 4.0.7 NEXT beta 106.

The problem occurs in a video with subtitles which is in this zip:
[TEST - Last Giant.zip](https://github.com/user-attachments/files/16516141/TEST.-.Last.Giant.zip)

The problem occurs when doing this:

- Load both the subtitle file and the video file in Subtitle Edit. The video is visible with subtitles. The waveform is visible.
- Select subtitle number 9 in the list, by either clicking or double clicking.
- Try to play this subtitle with the Play button in the Translate tab (Auto repeat is on, repeat count 2 times).

When doing this, you can hear a short noise that is repeated three times.

Additional info:

- When selecting subtitle 9 by double clicking in the list, the contents of subtitle 10 is shown as subtitle in the video, which is incorrect.
- When playing subtitle 10, the playing does not start at the beginning of this subtitle, but near the middle of this subtitle, which is incorrect. 

**Added later:**

Another sample of a subtitle that is not played completely by SE (the beginning of subtitle 4 is not played):
[TEST - Last Giant-2.zip](https://github.com/user-attachments/files/16530080/TEST.-.Last.Giant-2.zip)

**Comment by niksedk** [comment]
This does indeed look weird.
A mpv issue... sorry. You might want to re-convert the mkv file with e.g. handbrake or ffmpeg - ur use directshow as video player.
