### ISSUE TITLE
[REQ] Applio support

### ISSUE THREAD

**Issue by MarcoRavich** [SubtitleEdit/subtitleedit#8718]
Hi there, 1st of all thanks for your great work !

I believe that could be useful for many - both 'cause it's open source ([MIT](https://github.com/IAHispano/Applio/blob/main/LICENSE)) and it can be used with own (local hw) computational power - to use @IAHispano's [Applio](https://github.com/IAHispano/Applio#readme) too as a TTS (and not only) backend.

Interesting video review/tutorial about:
[![FREE Text to Speech with YOUR Voice with Applio!](https://img.youtube.com/vi/gjggpadBgOo/maxresdefault.jpg)](https://www.youtube.com/watch?v=gjggpadBgOo "Watch FREE Text to Speech with YOUR Voice with Applio! on Youtube")

Git: https://github.com/IAHispano/Applio
Web: https://applio.org/
FAQ - https://docs.applio.org/faq

**Comment by niksedk** [comment]
Hm, does it have an API or cli?
