### ISSUE TITLE
SubtitleEdit shuts down after OCR

### ISSUE THREAD

**Issue by Sergio902** [SubtitleEdit/subtitleedit#8719]
Hi,

Never seen that before : after PGS ocerisation into SRT, I click on OK and SubtitleEdit crashes, all my working data are lost !

**Comment by niksedk** [comment]
OK, how can I re-create this?

**Comment by Sergio902** [comment]
Try this file (with which I have the issue) : https://1fichier.com/?tbj7v5z9293cqd1fnme7

**Comment by niksedk** [comment]
Could you attach the file here on GitHub as a .zip file?
