### ISSUE TITLE
Splitting Lines by Chars

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8721]
I'm trying to import plain text and split by punctuations, but it seems not as expected, something wrong with my setting please?

![image](https://github.com/user-attachments/assets/d0c47d41-5eb6-4bbd-84e6-aebbcaeca400)

**Comment by niksedk** [comment]
Hi @LeonCheung,

Is this any better?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Yes, much better, thank you so much!
