### ISSUE TITLE
Allow manipulation of multiple subtitle entries in the timeline (waveform box)

### ISSUE THREAD

**Issue by fgordon-maker** [SubtitleEdit/subtitleedit#8725]
Here's a feature which I think would greatly increase usability: 
Add the ability to select multiple time entries in the waveform box and to move them left and right with the mouse.
The selection could be made with the mouse and keyboard:
- Double-click on an entry to select it.
- Ctrl+click, Shift+click to select other entries.
- Other selection modes via shortcut keys: Select one entry, then Shift+left arrow would select the current entry plus all the ones on the left, Shift+right arrow would select the current entry plus all the ones to the right. Shift+A would select all entries.
- Once having a selection, allow moving with it the mouse left and right. Of course, the times of the moved entries would be updated to reflect their new positions.

**Comment by niksedk** [comment]
Try Ctrl+Mouse-right-click to select, and Ctrl-mouse-down-move to move
