### ISSUE TITLE
Unicode characters from Whisper transcription

### ISSUE THREAD

**Issue by keith555** [SubtitleEdit/subtitleedit#8726]
I've used Whisper to transcribe a Thai audio file. Some Thai characters have one or two marks above the character, a bit like the dot above the English character  "i".  Unlike Western codesets the Thai characters consist of multiple bytes. The attached image shows that some of the marks that should be above another character have become detached. Some marks are shown above a dotted circle. Those are the erroneous characters. The dotted circle is just a place-holder; it's not part of the Thai language.

I tried running Whisper from the command line and the characters displayed correctly. This leads me to believe that the problem lies in the way that subtitle-edit is displaying the characters, not in the way Whisper is generating them.

![Snag_16d8415](https://github.com/user-attachments/assets/2c28f2c8-ae84-4ee5-b185-2f78252e8c74)

**Comment by niksedk** [comment]
How can I re-create this?
Can you attach the whisper log from SE?

**Comment by niksedk** [comment]
Perhaps some display issue with MS? If you save and use the file, is it then okay?

**Comment by keith555** [comment]
The problem seems to be with what SE is doing with the output from Whisper. If I save the file and open it notepad, it still has the problems. But If I run Whisper from the command line - the same Whisper executable that SE is using - the output file is correct. I can open it in Notepad or any other program and it displays correctly.

**Comment by niksedk** [comment]
Sorry, seems to be some MS issue.... I can't really do anything.

**Comment by niksedk** [comment]
Notepad seems to do the same:

![image](https://github.com/user-attachments/assets/86e0066b-c396-4f6c-8746-dd526e8afb3a)

**Comment by keith555** [comment]
That's strange. Was that file created in SE or directly from Whisper on the command line? If I put valid Thai into Notepad, it always displays it correctly. If I put invalid Thai into it, for example the Thai that SE displays from Whisper, then Notepad displays it incorrectly too.

**Comment by niksedk** [comment]
The file was created with Whisper.
