### ISSUE TITLE
Opening a subtitle file (SRT) slow over network

### ISSUE THREAD

**Issue by jessielw** [SubtitleEdit/subtitleedit#8734]
I've noticed in the last several releases (maybe longer) that opening a subtitle file over a network drive/windows path it's very very slow. It can take upwards of up to 30 seconds to open it. Opening the _same_ file from the desktop/local drive (even a very slow drive) is pretty much instant. 

I'll drop an example file, but this is reproducible with all subs that I've opened. 

This particular file also crashes the GUI when opening it with a very long path attached to it, where as it opens fast/no issues on a local drive. 

**Note:** My network drive is **very** fast, so it's not speed/latency. It's also a local network. 

[spiderman.no.way.home.(2021).eng.1cd.(9008900).zip](https://github.com/user-attachments/files/16617049/spiderman.no.way.home.2021.eng.1cd.9008900.zip)

**Comment by niksedk** [comment]
Sorry, I do think this is a feature/bug in the dot net 4.x framework.

**Comment by jessielw** [comment]
Ah, that's a shame! You'd think the framework made for windows would work well with that! Thanks for the response.
