### ISSUE TITLE
Changing models folder location

### ISSUE THREAD

**Issue by SupahOozer** [SubtitleEdit/subtitleedit#8738]
I've had SE installed on my work computer, but as the security policies are so tight, I cannot use the language models etc. from their default install locations. For example, the Whisper.exe file installed in the default directory requires elevated admin rights which I don't have and will never get. I managed to move the ffmpeg.exe to the only folder I have appropriate access, and that works, but not the Whisper.exe, and probably not the language models, if they require extra privileges. So, how do I change the model folder/Whisper.exe location so that I can run them? Or am I just ***t out of luck?

I am able to open the settings.xml file, but I have no clue what to do there, if it's possible to indicate the allowed folder(s) on the command strings.

**Comment by niksedk** [comment]
What about using the portable version?

**Comment by SupahOozer** [comment]
Well, that did the trick, thanks a million!
