### ISSUE TITLE
Inability to display Persian subtitles correctly 

### ISSUE THREAD

**Issue by phoenixxx99** [SubtitleEdit/subtitleedit#8739]
![IMG_20240816_005118_558](https://github.com/user-attachments/assets/7ec0b4ad-c45a-45a0-8465-95d377269632)
hi im using linux endeavouros and subtitileedit 4.0.7-1
When I add  any  Persian subtitles to the app, the words are displayed as garbled or unreadabl

**Comment by niksedk** [comment]
Try to use a font the Persian characters.
Linux has poor Unicode support :(
