### ISSUE TITLE
When saving a subtitle that had unicode characters, but not anymore, you still get a warning.

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8743]
<img width="611" alt="image" src="https://github.com/user-attachments/assets/60fdb250-4df0-4737-99ca-1c54b9b16538">

Hi,

Not really necessary to fix, but if you save a file that _**had**_ unicode characters, but you already replaced those, SE still comes with a warning.

**Comment by niksedk** [comment]
How can I re-create this.

**Comment by fraternl** [comment]
Have SE set to save as UTF8 by default. _(I forgot to mention that)_
Open an ANSI srt containing unicode characters.

Convert all unicode characters to normal and then save the file (as UTF8 as that's the default).

**Comment by niksedk** [comment]
How do you "Convert all unicode characters to normal " ?

**Comment by fraternl** [comment]
Someone wrote a plugin for your program to remove/replace Unicode characters. 

Until tomorrow I have nothing but my phone and can't find it using Google. 

I will give you the answer tomorrow, but maybe you now know enough.

**Comment by fraternl** [comment]
There's a plugin named "RemoveUnicodeCharacters"
It took me some time to find it again, but found it here and apparently you're the author:
[Plugins4.xml](https://github.com/SubtitleEdit/plugins/blob/master/Plugins4.xml)
[RemoveUnicodeCharacters.zip(https://github.com/SubtitleEdit/plugins/releases/download/v.1.1/RemoveUnicodeCharacters.zip)

The DLL is in my "%APPDATA%\Subtitle Edit\Plugins" folder.

<img width="528" alt="image" src="https://github.com/user-attachments/assets/f81945fe-9449-4f56-bc6c-29bb79d6d99f">

I now forgot which subtitle I was working on and tried to find an ANSI srt containing unicode characters which can't be saved to UTF-8 giving that message.

That error message is normally correct, but because I converted all of them.
It doesn't really need repairing. I know I can ignore the message, but maybe you think it would be an improvement to the program if the error message still applies to the current save.

This is my configuration in `"%APPDATA%\Subtitle Edit\Plugins"`
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!--This XML file defines the settings for the Subtitle Edit 'Remove Unicode characters' plugin-->
<RemoveUnicodeCharactersSettings>
  <UseReplaceList>True</UseReplaceList>
  <ReplaceList>
    <Item>
      <Unicode>–</Unicode>
      <Ansi>-</Ansi>
    </Item>
    <Item>
      <Unicode>—</Unicode>
      <Ansi>-</Ansi>
    </Item>
    <Item>
      <Unicode>‘</Unicode>
      <Ansi>'</Ansi>
    </Item>
    <Item>
      <Unicode>’</Unicode>
      <Ansi>'</Ansi>
    </Item>
    <Item>
      <Unicode>‚</Unicode>
      <Ansi>,</Ansi>
    </Item>
    <Item>
      <Unicode>“</Unicode>
      <Ansi>"</Ansi>
    </Item>
    <Item>
      <Unicode>”</Unicode>
      <Ansi>"</Ansi>
    </Item>
    <Item>
      <Unicode>„</Unicode>
      <Ansi>"</Ansi>
    </Item>
    <Item>
      <Unicode>…</Unicode>
      <Ansi>...</Ansi>
    </Item>
    <Item>
      <Unicode>♪</Unicode>
      <Ansi>#</Ansi>
    </Item>
    <Item>
      <Unicode>♫</Unicode>
      <Ansi>#</Ansi>
    </Item>
    <Item>
      <Unicode>ﬁ</Unicode>
      <Ansi>fi</Ansi>
    </Item>
    <Item>
      <Unicode>ĳ</Unicode>
      <Ansi>ij</Ansi>
    </Item>
    <Item>
      <Unicode>œ</Unicode>
      <Ansi>oe</Ansi>
    </Item>
    <Item>
      <Unicode>р</Unicode>
      <Ansi>p</Ansi>
    </Item>
  </ReplaceList>
</RemoveUnicodeCharactersSettings>
```

**Comment by niksedk** [comment]
The remove Unicode chars plugin only removes/fixes a few characters... not that Unicode has about 155.000 characters!
