### ISSUE TITLE
Can't use SE

### ISSUE THREAD

**Issue by JDTR75** [SubtitleEdit/subtitleedit#8747]
Hello, as the subject says, I can't basically use SE because I'm getting this error all the time.

![image](https://github.com/user-attachments/assets/a2bab103-147f-42f3-97ae-42bae5a1ae90)

Can't ignore it, can't retry, nothing. This is happening to me on the latest beta 127.

**Comment by techguru0** [comment]
update your .net

**Comment by cvrle77** [comment]
![image](https://github.com/user-attachments/assets/e363186d-eac6-4a8f-a8e0-ddba4f2342ef)
Yep, same here!

**Comment by JDTR75** [comment]
> update your .net

I already have .NET v8.0.8 and it's not working.

**Comment by niksedk** [comment]
Test for reporting this. How is the new beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

**Comment by Codling** [comment]
No more error on my side with the latest beta. Thanks!

**Comment by JDTR75** [comment]
Same here 😊. No more errors. Thank you!

**Comment by JDTR75** [comment]
Didn't want to create a new issue because this might be related. I'm getting this error when running Faster Whisper XXL.

![image](https://github.com/user-attachments/assets/12a59e6b-726a-4414-93f5-d9f3e48a073a)
