### ISSUE TITLE
Help!!! Perfviews faster whisper is not working !!!!!

### ISSUE THREAD

**Issue by reiaoyama1** [SubtitleEdit/subtitleedit#8755]
Purview's fast whisper or faster whisper XXL isn't working. I get the same error on every whisper models. I have a lot of files to transcribe so please help me. 
Here's the video of the issue
https://drive.google.com/file/d/1gdn_QB7Yo7Nd3TjN_H-uwFhOoTPhDcct/view?usp=sharing
here is my hardware information if you guys need it
![unknown_2024 08 22-11 24](https://github.com/user-attachments/assets/3211be7a-c39d-4d92-83e8-da0b142302b5)

**Comment by reiaoyama1** [comment]
Seems like const me works just fine but the thing is that isn't purview's faster whisper the fastest version of whisper that's why i want to use it.

**Comment by JDTR75** [comment]
This is the same error I reported two days ago. https://github.com/SubtitleEdit/subtitleedit/issues/8747#issuecomment-2299244840

**Comment by JDTR75** [comment]
@reiaoyama1 if you really need to use Faster Whisper, you can do a downgrade for the moment and it should work. https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SE407.zip

**Comment by reiaoyama1** [comment]
ありがとう!!!! Thanks

**Comment by JDTR75** [comment]
Saw this marked as completed but the error is still present in the latest beta @niksedk:
![image](https://github.com/user-attachments/assets/d1ea7f67-5bec-4c4d-82b7-fe44ed08ac37)

**Comment by niksedk** [comment]
Works fine  here...
Try running from the command line and see what happens. Also, read more in the whisper_log.txt file.

**Comment by JDTR75** [comment]
Whisper is actually running if I omit the error (leave the dialog box open), but as soon as I click on OK (or Esc for that matter), SE asks me if I want to save the file and then it crashes.
And no issues running it from command line directly.

I have it unpacked to C:\SE. I even tried unpacking it to a complete new instance and the error still happens with the latest beta 148.

Here's a quick video for demonstration: https://screenrec.com/share/IQldqfKc1v

**Comment by niksedk** [comment]
Thx for the info - SE should not crash after Whisper now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

**Comment by JDTR75** [comment]
You're the best! Working normally now 😊
