### ISSUE TITLE
Hearing Impaired removal small bug.

### ISSUE THREAD

**Issue by RAMoynihan** [SubtitleEdit/subtitleedit#8756]
Hi folks,

I think I found a small bug in the 'remove HI' function. I've shown the issue in the capture below. 

All of the test subtitles contain the interjection "Mm" which is supposed to be removed, and lines 2 through 4 also include the text "MAN:" which should also be removed.

The issue presents itself in line 3. I would have expected the result to be a single line saying only "Text", but it retains the "MAN:" part plus a trailing period ('.') character at the end. To test whether the trailing period in line 3 was triggering the issue I tried a new subtitle (line 4) without the trailing period, but the issue remains.

I just happened to notice this and thought that I should report it.

Regards,
Bob

![Capture](https://github.com/user-attachments/assets/8a4ec099-7511-4606-9f8d-b0d41e53b442)

**Comment by RAMoynihan** [comment]
What a dope! I messed up by trying to simplify this bug before reporting it. When I look again at what I posted above I can clearly see the "Text MAN:" isn't a valid case for "Only if text is uppercase" removal. So I edited out the bug before reporting it. Sorry about that. I'll try again with the ACTUAL bug.

**Comment by RAMoynihan** [comment]
Here's what I should have presented originally.

You can see in line 2 below how the entire line "MAN: Mm." is removed as expected. But if that same text appears as the 2nd line in a 2-line subtitle (as in line 4 below) the "MAN:" part doesn't get removed. I would have expected the result to be simply "Text".


![Capture2](https://github.com/user-attachments/assets/8e598e51-2bf2-4540-b226-9ce0606e8674)

**Comment by niksedk** [comment]
SE does not support badly formatted lines, with e.g. missing periods.
