### ISSUE TITLE
Using a Macro Keyboard. 

### ISSUE THREAD

**Issue by thiagosamico** [SubtitleEdit/subtitleedit#8757]
Hello. I use your wonderful software and have accomplished great things with it!
I am an enthusiast of optimizing its use with the implementation of a macro keyboard. This has saved me precious hours of work and has certainly been a great addition!
The only thing I haven't yet been able to assign to the keyboard is expanding or shrinking the boundaries of the subtitles. The only way to do this is by clicking with the mouse on the edge and dragging it to the right or left. I am aware of the function that expands the subtitle (Extend selected lines to next subtitle) but this goes all the way until the next subtitle and my goal is to act with a shortcut just as I do with click and drag the cursor. 
I searched everywhere in the shortcuts but couldn't find anything similar to this function that I need. Any suggestions?
With this, I can perfectly integrate the macro keyboard into my use of Subtitle Edit, as I will use the knobs to adjust the subtitles more efficiently.

Thank you very much and much love from Brazil.

![photo_2024-08-22_13-45-33](https://github.com/user-attachments/assets/be66a32b-2d5c-4508-9472-522fe023b0c4)

![se](https://github.com/user-attachments/assets/75bf616d-4685-4807-9d64-9abcb0b3020d)

**Comment by darnn** [comment]
Check out these keyboard shortcuts in Create/adjust:
![image](https://github.com/user-attachments/assets/53f8fcc8-6f48-44b5-8acb-08d6fd15ade3)

**Comment by thiagosamico** [comment]
wow! Worked perfectly! 
Thank you very much! 
Now the right knob takes care of the right edge of the subtitle and the left... 
And so fast answered! Now back to work, even faster than never! 

Much appreciated!
