### ISSUE TITLE
Request for Fix on Merging Lines Without Auto-Break in Beta Edition

### ISSUE THREAD

**Issue by kadrimarzouki** [SubtitleEdit/subtitleedit#8767]
Please provide a solution for merging a line with the previous or next line.

As a matter of fact, when using the shortcut "Merge with Previous," SE used to merge lines without adding a break between them. However, in the beta edition, the merging option now involves some sort of auto-breaking, which we do not want. We prefer it as it was before.

Example:
Line 1:
Mrs. Danphy? She's not going to tell you the truth.

Line 2:
Why wouldn't she?

When we use the "Merge with previous Subtitle" option, the result should be:

Correct Result:
Mrs. Danphy? She's not going to tell you the truth.
Why wouldn't she?

And not:
Mrs. Danphy? She's not going to tell you the truth. Why wouldn't she?

The same issue occurs with the "Merge with Next" option.

----------------------------------

![image](https://github.com/user-attachments/assets/020ad671-41af-4db7-bb74-47c2a9fcfa89)

![image](https://github.com/user-attachments/assets/1df8df02-ed91-40b0-85f0-31c3595ea247)

![image](https://github.com/user-attachments/assets/5e1fe72f-8273-4632-9621-97e3fc58e7e9)

**Comment by LeonCheung** [comment]
Hmm, not sure if they are the same issue, but also see #8776

**Comment by kadrimarzouki** [comment]
> Hmm, not sure if they are the same issue, but also see #8776


**There is no point; these requests are ignored.
No one seems to care whatsoever**
