### ISSUE TITLE
Undesired break lines in Auto-Translate

### ISSUE THREAD

**Issue by Dyo-Anima** [SubtitleEdit/subtitleedit#8770]
Hi, thanks for the great effort with this program.

I downloaded this version https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

I see that in the beta version there is still a problem with creating unwanted break lines when the expected behavior is to translate the whole line without breaking it.
I have the default options,

 is there a force majeure reason for this to persist? Or is there already an option to avoid this problem?

[test_sub.zip](https://github.com/user-attachments/files/16764074/test_sub.zip)

![imagen](https://github.com/user-attachments/assets/864bc2fb-ecda-4c75-8237-b8dfef95b695)

**Comment by niksedk** [comment]
Beta updated with fix: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
