### ISSUE TITLE
Subtitle Edit crashes/freezes on Batch Auto Translate with Ollama. Also there is no option to select a model.

### ISSUE THREAD

**Issue by Anon1337Elite** [SubtitleEdit/subtitleedit#8771]
Individual translations work just fine takes 1-2 minutes per translate of a subtitle. Trying Batch auto translate with Ollama crashes/freezes. At first i monitored it it starts the model with ollama and its doing something for few seconds, then just the VRAM is full for like 10 minutes and the model gets unloaded while SubtitleEdit stays frozen and have to kill its proccess. Tested on the Beta from few days ago.

**Comment by niksedk** [comment]
Ollama translate is hopefully better in batch now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
