### ISSUE TITLE
Allow to change temporary folder

### ISSUE THREAD

**Issue by ArturAlekseev** [SubtitleEdit/subtitleedit#8774]
Because program uses temporary folder to save/delete temporary subtitle image files for recognition - it is better to allow to change temporary folder in settings. So we could change it to folder on RAM virtual drive. When folder is not available program should use default temp folder.
I think it should check for folder availability only during program start or when settings are changed.

**Comment by niksedk** [comment]
SE just uses the windows temp folder - which you can change.
