### ISSUE TITLE
Add support for FineReader

### ISSUE THREAD

**Issue by ArturAlekseev** [SubtitleEdit/subtitleedit#8775]
Yes FineReader is a commercial solution, but it is much better than tesseract.
It can be used same way as tesseract (from command line) and allows to save result to clipboard, that can be used.

**Comment by niksedk** [comment]
You can export and import images with time codes in SE.
This should make it possible to use most external OCR providers.

![image](https://github.com/user-attachments/assets/73a542e3-fed3-4818-855d-e638025d036e)

And File - Import images...
