### ISSUE TITLE
[QoL] - Move beginning and end of two subtitles simultaneously in spectrogram

### ISSUE THREAD

**Issue by MitchSirco** [SubtitleEdit/subtitleedit#8780]
As title says.

The idea is, when two subtitles are next to each other, you could move both the end of the left and the beginning of the right subtitle at the same time.
this could reduce time to adjust the timings of two subtitles.

Inspiration:

https://github.com/user-attachments/assets/61442c29-f1e2-400e-9e2a-a0f9de18d0b6

**Comment by niksedk** [comment]
Try holding down ALT

**Comment by MitchSirco** [comment]
Oh damn, didn't know that, thank you very much!
