### ISSUE TITLE
[QoL] - Allow pasting selected subtitles from list (or spectrogram), right at the position of the "play head" in the spectrogram

### ISSUE THREAD

**Issue by MitchSirco** [SubtitleEdit/subtitleedit#8781]
As title says.

When you select subtitles in the list view, and try to paste it into the spectrogram, it tries to literally paste the full ASS code into it.

It would be nice, if you could set your playhead somewhere, hit CTRL + V and then right at that position, it pastes all the selected subtitles (with the timings) into it

Inspiration:

https://github.com/user-attachments/assets/a3175c63-84e2-45e2-bcae-309b7cf47f35

**Comment by niksedk** [comment]
Thx, that's a bug.

**Comment by niksedk** [comment]
Should be fixed in latest beta now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

**Comment by MitchSirco** [comment]
Tested, works, thank you very much
