### ISSUE TITLE
Dialect

### ISSUE THREAD

**Issue by mantleinwndwjs9** [SubtitleEdit/subtitleedit#8793]
Hello everyone,

How can I use a precise dialect within SE?

For example, I can use the French language filter which is default, but I cannot specify the dialect to be French Canadian.

I checked all over the program itself and the issues here to see if someone else already asked and found dead ends to modify that within the program settings. Is there some fine settings I can do with certain Python libraries to force add dialects to used Whisper or Vosk/Kaldi?

**Comment by niksedk** [comment]
It's probably a lot of work, but more and more custom models popup.
Check the Open AI Whisper forum and also this: https://huggingface.co/blog/fine-tune-whisper

With SE you could e.g. use Edit - Multiple replace, to replace words...
