### ISSUE TITLE
Audio to text problems

### ISSUE THREAD

**Issue by Oplay66** [SubtitleEdit/subtitleedit#8794]
Low gpu utilization in purfview faster whisper.
The specified module could not be found in whisper xxl.

**Comment by niksedk** [comment]
Are you using CPU or GPU in Purfview Faster Whisper? Check the "whisper_log.txt".

"The specified module" could indicate that the "Faster whisper xxl" is not downloaded/unpacked completely.

**Comment by Oplay66** [comment]
> Are you using CPU or GPU in Purfview Faster Whisper? Check the "whisper_log.txt".
> 
> "The specified module" could indicate that the "Faster whisper xxl" is not downloaded/unpacked completely.

Gpu cuda

**Comment by niksedk** [comment]
I don't have a CUDA GPU, and it's really more of a Whisper issue, so ask here:
https://github.com/SYSTRAN/faster-whisper/commits/master/
https://github.com/Purfview/whisper-standalone-win/issues
