### ISSUE TITLE
Suggestion: Add Hability to Shift Shot Cut Data After Detection

### ISSUE THREAD

**Issue by acetilo** [SubtitleEdit/subtitleedit#8795]
Hi, first I want to start by thanking you all for this amazing piece of software, could not do my job without it.

I was wondering if it would be possible to add the possibility of shifting shot cut data after detection. Many times it is off by one or two frames and, even though you can work around it manually, it ends up adding many clicks to the task of timing correctly a file to the frame.

Spot 6 has this feature in case you want to check out what I'm talking about. If necessary I can provide example pictures or a short video showcasing it at work.

Again, many thanks!

**Comment by niksedk** [comment]
Something like this?

![image](https://github.com/user-attachments/assets/d5895837-57dc-4f37-a873-9093f80148a3)


Beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
