### ISSUE TITLE
"Set start/end time" not frame exact

### ISSUE THREAD

**Issue by drunkenimp1** [SubtitleEdit/subtitleedit#8799]
Both "Set start/end time" do not actually set the start/end of a subtitle to the frame you're currently seeing. 
I'm looking at this frame, the last frame of a shot, on which I want my subtitle to end and press "set end" 
![ex1](https://github.com/user-attachments/assets/e861e24f-3d82-4953-ac6f-b674f0350333)

but that makes the subtitle end one frame before the current frame
![ex2](https://github.com/user-attachments/assets/833a7b90-e6cb-464b-8e58-95aa504d50ad)

The same thing happens on "set start" only that it's one frame after the frame you're seeing. 
A similar issue is currently open with the "snap to end of shot" which also make the subtitle remain for one frame **after** the shot-end.

**Comment by Ding-adong** [comment]
Subs are based on timing not frames. Subs can start a bit earlier or a bit later than the actor speaking. It would come down to the speed of talking. Subs with long sentence would need more time to be 'scanned' by the user and if an actor was speaking faster than usual, the subs timings will still be the same.

Frames are irrelevant.

**Comment by drunkenimp1** [comment]
I think you completely misunderstood what my problem is. I'm not talking about some subtitles I have downloaded and aren't perfectly synced or anything like that ( I don't fully understand what you interpreted my problem to be). I'm talking about (as shown above) that both "set start/end" time (while apparently setting the timing correctly), do not actually set the subtitle "appearance/disappearance" to the frame you're currently seeing. 
![Capture](https://github.com/user-attachments/assets/5b0cb50a-7dc5-49d4-aeb3-cb5d0ede8d2a)
Maybe the above shows better what I mean. "test" should appear according to it's "start time" but it does not. 
(I'm fully aware my problem is probably due to my lack of understand how the subtitle-displaying/ video-files etc. function but surely the subtitle should start/"appear" at the time & frame it's supposed to.)

**Comment by niksedk** [comment]
It works fine here:
![image](https://github.com/user-attachments/assets/6e5ca8a7-b93e-49c6-a737-f56764d8e8f7)


I can depend on your video file and your video player...

Also, the "End time" is probably more a "hide time".

**Comment by niksedk** [comment]
Also, newer codecs can use variable frame rate... which makes using just ms much better and more logical.
