### ISSUE TITLE
Suggestion: Make it possible to select the do-not-break-after list(s) that you want to use

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#8804]
**Suggestion:** Allow the user of Subtitle Edit to select the do-not-break-after lists that are relevant to them. This will prevent unexpected things from happening due to items in do-not-break-after lists for languages the user is not working with.

This could be achieved by adding a new dialog box like this:

![Use do-not-break-after list-01](https://github.com/user-attachments/assets/98652d27-5151-4fdd-8ad9-9e28fe5e1447)

I suggest that when you click on "Settings/Tools/Auto br/Edit", a new dialog box like this will appear. When clicking on an Edit button in such a new dialog box, I suggest that the dialog box that currently appears when clicking on "Settings/Tools/Auto br/Edit", will appear with the language of the clicked Edit button preselected. (I suggest to remove the "New" button from the current dialog box, and to only add languages from the new dialog box.)

**Additional note:** In making this suggestion, I assumed that all existing do-not-break-after lists are currently used with actions that use do-not-break-after lists. However, this does not appear to be the case. See [here](https://github.com/SubtitleEdit/subtitleedit/issues/8803#issue-2512553354).

**Comment by Leinad4Mind** [comment]
+1

**Comment by oep42** [comment]
I didn't know that SE automatically detects the subtitle language and automatically uses the appropriate do-not-break-after list. So the above suggestion is useless.
