### ISSUE TITLE
Libretranslation error message

### ISSUE THREAD

**Issue by Tizioincognit0** [SubtitleEdit/subtitleedit#8812]
Hi. When I'm trying to bulk translate subtitles, I get "Translation failed" error. This is the error logged in the error_log.txt file.
`-----------------------------------------------------------------------------
Date: 09/10/2024 17:33:29
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22621.0 - 64-bit
Message: Batch translate failed

System.AggregateException
Message: Si sono verificati uno o più errori.
StackTrace:    in System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   in System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   in Nikse.SubtitleEdit.Forms.BatchConvert.RunAutoTranslate(Subtitle subtitle)
   in Nikse.SubtitleEdit.Forms.BatchConvert.buttonConvert_Click(Object sender, EventArgs e)
System.AggregateException
Message: Si sono verificati uno o più errori.
StackTrace:    in System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   in Nikse.SubtitleEdit.Core.AutoTranslate.LibreTranslate.<Translate>d__19.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__4.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Nikse.SubtitleEdit.Forms.BatchConvert.<>c__DisplayClass58_0.<<RunAutoTranslate>b__1>d.MoveNext()
System.Net.Http.HttpRequestException
Message: Si è verificato un errore durante l'invio della richiesta.
StackTrace: 
System.Net.WebException
Message: Impossibile effettuare la connessione al server remoto.
StackTrace:    in System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   in System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
System.Net.Sockets.SocketException
Message: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione 127.0.0.1:5000
StackTrace:    in System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   in System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   in System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
`

**Comment by niksedk** [comment]
This requires that you have the LibreTranslate API up and running locally: https://www.nikse.dk/subtitleedit/help#translation
