### ISSUE TITLE
[Feature Request] OCR using GEMINI API

### ISSUE THREAD

**Issue by 0wwafa** [SubtitleEdit/subtitleedit#8813]
Can you please add this feature?

If you need help I can help.

**Comment by niksedk** [comment]
It is not something I'm planning... but if someone adds this, then fine :)

Someone already added "Google vision"...

**Comment by 0wwafa** [comment]
> It is not something I'm planning... but if someone adds this, then fine :)
> 
> Someone already added "Google vision"...

yes. but google vision is way worse than tesseract.
