### ISSUE TITLE
Video burn in - Intel Quick Sync

### ISSUE THREAD

**Issue by ghostminhtoan** [SubtitleEdit/subtitleedit#8814]
Hi, 
I cannot use Intel Quick Sync when making hard sub videos. It only uses the CPU, not GPU intel UHD graphic. The video hard sub is slower than Vidcoder because it has intel quick sync. 
I don't want to switch to another app, I really love Subtitle Edit and it would be really cool to use intel graphic to encode video.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

Use "h264_qsv" or "hevc_qsv" video encoder :)
