### ISSUE TITLE
Unexpected results: Remove Text For Hearing Impaired

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#882]
Ups Edited: `Foobar <font color="#808080">(CHAINS RATTLING)</font> Foobar` @niksedk

**Comment by niksedk** [comment]
What is the result and what did you expect?

**Comment by ivandrofly** [comment]
Keeps font tag in text

**Comment by ivandrofly** [comment]
Another eg: `♪ <font color="#000000">(LIGHT SWITCH CLICKS)</font>`
