### ISSUE TITLE
[SE-4.0.8] Spell and gammar check in Microsoft Word

### ISSUE THREAD

**Issue by TarantinoMariachi** [SubtitleEdit/subtitleedit#8823]
Hi there, when I open this option it pre-select English. It could pre-select our own language, or having an option somwhere to set that up:
![image](https://github.com/user-attachments/assets/ac726ec8-28bf-4d49-9965-888d59789c0d)

Now, the bug is... after updating from 4.0.6 to 4.0.8, I notive that when I open, then change to portuguese it was not working properly and it even gave an error, then I found out that my installation didnt had the plugin installed, but the option was appearing on the menu, weird! After installing the plugin it worked fine. And after removing the plugin the optin dissapeared as it should. So some problem after one of the updates I did....

**Comment by niksedk** [comment]
Sorry, I do not have Word... so I cannot help-with/test this.
