### ISSUE TITLE
I can't find the document for Export Custom Text Format 

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [SubtitleEdit/subtitleedit#8829]
I would like to know what {tags} are available for me to use. But I have searched through the documents, the Issues, and Googled, but I couldn't find any clues. 

![图片](https://github.com/user-attachments/assets/1272f939-4b49-4611-8d14-91e9837ddc5a)

![图片](https://github.com/user-attachments/assets/3afd41a2-657e-4eea-8200-19f9607a9d7d)

**Comment by niksedk** [comment]
He, often SE will show some menu when using right-click (context-menu):

![image](https://github.com/user-attachments/assets/983ada42-5d55-47b5-acfc-f03713b79760)

**Comment by LakeishaKowalczyk** [comment]
@niksedk Thank you ^^
