### ISSUE TITLE
Minimum required modules for compiling using VS2022?

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#8846]
Is there somewhere a list of modules that compiling with VS2022 requires? I have plenty of this kind of errors during the process and eventually it fails.

`C:\sources\subtitleedit\src\ui\Logic\LanguageDeserializer.cs(539,42): error CS1061: 'LanguageStructure.AudioToText' does not contain a definition for 'WhisperNotFound' and no acce
ssible extension method 'WhisperNotFound' accepting a first argument of type 'LanguageStructure.AudioToText' could be found (are you missing a using directive or an assembly refer
ence?) [C:\sources\subtitleedit\src\UpdateLanguageFiles\UpdateLanguageFiles.csproj]`

**Comment by niksedk** [comment]
Hm, it's possible you need git?
https://git-scm.com/download/win

Any better?

**Comment by Boulder08** [comment]
I already have git installed, in fact I usually run git pull before using build.bat even if the script itself also checks for updates in the repo.

**Comment by niksedk** [comment]
A clean pull?

**Comment by Boulder08** [comment]
Doesn't help, in fact it's spitting out a huge amount of build errors like
`C:\sources\subtitleedit_new\src\Test\Logic\UtilitiesTest.cs(533,10): error CS0246: The type or namespace name 'TestMethodAttribute' could not be found (are you missing a using dir
ective or an assembly reference?) [C:\sources\subtitleedit_new\src\Test\Test.csproj]`

This is what I have installed, looking at the list in Visual Studio Installer
![image](https://github.com/user-attachments/assets/cd61bd31-a4a4-4e37-a89b-f3cd2c2ceb07)

**Comment by niksedk** [comment]
Have you solved it? Do you have the "NuGet package manager"?

Here's some of my settings:

![image](https://github.com/user-attachments/assets/cc6fd765-9f96-4ad7-bf5e-ee70fcb51c70)

![image](https://github.com/user-attachments/assets/08e68324-8e20-4cd7-9122-fe57eaa2075c)
