### ISSUE TITLE
Blurry font of the controls on the 4K screen

### ISSUE THREAD

**Issue by pavelsidyakin-warnermedia** [SubtitleEdit/subtitleedit#8848]
App version: 4.0.8.

OS: Windows 10 Pro 21H2
Screen resolution: 3840x2400
Font scale: 250%.

The font of the controls is blurry. The window's header font is normal. See the screenshots.
In other programs the font is normal. See the last screenshot.

<img src="https://github.com/user-attachments/assets/2790ed36-de64-412f-9250-5be86e85765f" height=400>

<img src="https://github.com/user-attachments/assets/5c981550-cfa9-47ce-aa84-ec9df9ff4c77" height=300>

<img src="https://github.com/user-attachments/assets/4bd5772a-0cef-429f-a303-dfdc5b9d128c" height=400>

**Comment by niksedk** [comment]
Dupe of https://github.com/SubtitleEdit/subtitleedit/issues/2434
