### ISSUE TITLE
Any method to globally extend the duration of subtitle display?

### ISSUE THREAD

**Issue by vsrawat** [SubtitleEdit/subtitleedit#8849]
It is not a bug, just seeking suggestions to solve one of the issues I am facing.

Often, subtitles are all correct and working, but there duration of display is so short that they appear and disappear before I can read them. Then I have hit the "back" button to replay those few seconds of the video, and may be press "pause" to get time to read the entire displayed subtitles.

Is there any method in Subtitle Edit that would just extend the duration for the display of subtitles? I mean, all time stamps are correct, but if there is any "end-subtitle-display", can that part be extended so that I get a few milliseconds or even 1-2 second more time to read the subtitles?

It will intefere with the display of next subtitle line if that modified "end-subtitle-display" time is longer than the ""start-subtitle-display" of the next subtitle line, but I guess you would find some way around.

VLC was great, it has option that subtitles can be displayed in 3-4 lines, previous-current-future subtitle line - sort of, and I got plenty of time to read that.

I use potplayer, may be that has some method to achieve, if someone can guide me to it.

Thanks.

**Comment by RAMoynihan** [comment]
There are minimum time and time-per-character settings, which should resolve your too-quick subtitles, I imagine.

**Comment by vsrawat** [comment]
> There are minimum time and time-per-character settings, which should resolve your too-quick subtitles, I imagine.

If you could be more clear as to whether I should look for those settings in subtitleEdit or in potplayer?

If not in subtitleEdit, could more members share their opinion whether they have faced similar issues and such a setting to globally change subtitle display time in SubtitleEdit would be a help?

Thanks.

**Comment by niksedk** [comment]
Check Tools - Adjust durations:

![image](https://github.com/user-attachments/assets/a43ff53e-1dfa-4092-bcd5-fec631e8a679)
