### ISSUE TITLE
Italic tags written incorrectly

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#8851]
Looking at the OCR matches, the italics detection has worked correctly, but the tags in the output SRT file are wrong.

![image](https://github.com/user-attachments/assets/a1663613-f25a-4e1d-932f-8bd091b65b65)

```
142
00:11:54,255 --> 00:11:56,257
-Yes?
LEO [OVER PHONE]:They'<i>re here.</i>
```

[batman_s01e19_en.zip](https://github.com/user-attachments/files/17115758/batman_s01e19_en.zip)

**Comment by niksedk** [comment]
Thanks, hopefully now fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

**Comment by Boulder08** [comment]
Looks like there still some tuning to be made. Similar case where the detection is good but the starting tag is not in the correct place.

![image](https://github.com/user-attachments/assets/3a2f1837-deba-447b-9bd7-9c79293e56c6)

[walkingdead_s10e22_en.zip](https://github.com/user-attachments/files/17316788/walkingdead_s10e22_en.zip)

**Comment by niksedk** [comment]
Hm, I cannot re-create this in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

**Comment by Boulder08** [comment]
Just tested, and yes, works with that release. Funny how the initial issue was fixed by the previous linked release but this one just now :)

**Comment by niksedk** [comment]
Ah, my first fix was a little buggy...
