### ISSUE TITLE
File shows warning when opened due to mix of line break styles

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#8854]
A file produced by ConstMe:
[phys.zip](https://github.com/user-attachments/files/17121142/phys.zip)
Gives the following warning when opened:
![image](https://github.com/user-attachments/assets/d9337df5-b2af-4149-8e4c-1ebb454c8e31)

As far as I can tell, this is due to the fact that the file has several styles of line breaks (i.e. something other than just CR LF).
Simply opening it as a text file and copying and pasting its contents into source view works fine. And if you change the line break style to Windows in the entire file (I do this in EditPad), it opens without warnings.

**Comment by niksedk** [comment]
It really depends on what editor you one the file in....

![image](https://github.com/user-attachments/assets/b341ac85-8231-4595-9041-e959666e3577)

![image](https://github.com/user-attachments/assets/411ded92-ac06-4121-80fa-5c5335c8cb16)

SE, will now try to do the same as VS code (I hope this will not break too much...)

**Comment by darnn** [comment]
Thank you! I have no idea about VS Code, but EditPad's always opened them with no issue, so I wouldn't have even thought there'd be a problem elsewhere.
