### ISSUE TITLE
Icelandic language to ChatGPT + Gemini

### ISSUE THREAD

**Issue by dhofverberg** [SubtitleEdit/subtitleedit#8855]
Icelandic language is missing from the drop down of **Auto-translate** when using both Google Gemini and ChatGPT, even though the language is supported by both services.

Could you please add it to the drop downs of both **From** and **To** when choosing ChatGPT and Gemini? Right now, Icelandic seems to only be visible when choosing Google Translate.

**Comment by dhofverberg** [comment]
This is supposed to have been added in version 4.0.19 according to the version history, but I still can't see Icelandic in the From and To drop-downs in Auto-translate when choosing ChatGPT or Gemini. Am I doing something wrong, or has it not been added after all?

**Comment by niksedk** [comment]
![image](https://github.com/user-attachments/assets/7c3135c7-aa05-4146-9812-4c516a97f1b5)

**Comment by dhofverberg** [comment]
I have tested again, and it works for ChatGPT, but not for Google Gemini - with Gemini, Icelandic still doesn't show up on the drop-down.

Does it work for you with Gemini, or did you miss to add it for Gemini?
