### ISSUE TITLE
LAV filters codec is not detected in SE, MPC-HC

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#8860]
I switched from the K-lite codec pack that worked perfectly all the time, but it showed soft-coded subtitles in the preview window, along with the external srt file subtitle. Two subtitles at the same time. I switched to LAV filters codec, but I have another problem. Subtitle edit doesn't recognize the MPC-HC video engine, and it should be part of LAV filters codec. I also included some external MPC-HC, but it is the same. 

Is there any solution for this? Look at the picture, SE doesn't recognize MPC-HC video engine to be present on my system. 

![Screenshot_1](https://github.com/user-attachments/assets/4d8f2711-0b03-4a25-b83e-9e0cf353e391)

**Comment by niksedk** [comment]
I think you will need a mpc-hc install, like from: https://github.com/clsid2/mpc-hc/releases

**Comment by Cyberyoda1411** [comment]
Thanks; it works. I added at least two other mpc-hc codecs outside the LAV filters package, but it seems that the one on GitHub is the most complete and has more MB than the others.
