### ISSUE TITLE
While typing in the text box, characters are replaced instead of moving forward.

### ISSUE THREAD

**Issue by AE-Ismail** [SubtitleEdit/subtitleedit#8861]
I have been encountering this bug for some time across different versions. I didn't pay much attention to it since it disappears after restarting Subtitle Edit. However, in the last two versions, the bug has started occurring more frequently within the same session.
I recorded a video of the issue:

https://github.com/user-attachments/assets/5b4b7456-6c89-4326-965e-01094c26d0e7

**Comment by niksedk** [comment]
IF you use the syntax coloring, then the text box will have `overwrite mode` (toggle via the `Insert` key)
![image](https://github.com/user-attachments/assets/0c3e2ba7-6696-40ed-8649-036defecc2ac)

**Comment by AE-Ismail** [comment]
Thank you, I'll try it out.
