### ISSUE TITLE
[Improvement] Add Import/Export to AutoBr Do-not-break-after list

### ISSUE THREAD

**Issue by Leinad4Mind** [SubtitleEdit/subtitleedit#8877]
Would be great to have an Import and Export option at AutoBr Do-not-break-after list.

And I've a doubt about this feature, how does it knows to use the french or spanish or english list? Does it automatically detects the language of the subtitle that is inserted?! It would make it easier so we can send share our lists

**Comment by niksedk** [comment]
The "no break after lists" are in the dictionaries folder, see e.g. dictionaryes/es_NoBreakAfterList.xml

Yes, SE auto detects the subtitle language and uses the appropriate list.

**Comment by Leinad4Mind** [comment]
Ok, that seems a good and easy workaround. 
Btw nik, is there any quick way to add a list between one by one? Like separated by comma or any special caracter? Just wondering.

**Comment by Leinad4Mind** [comment]
@niksedk one extra question, if the subtitle is english and Im starting translating it, SE will detect as english  I presume? But if I wanted to force to detect in portuguese, so it breaks automatically as I translate, is it possible? If not, we could win if we could to select which one to force. Or am I missing something?
