### ISSUE TITLE
can you add ReazonSpeech ai 

### ISSUE THREAD

**Issue by techguru0** [SubtitleEdit/subtitleedit#8881]
ReazonSpeech is suppose to be better then whisper for japanese to english stuff
and I do alot of that
and I suspect alot of others do as well

**Comment by niksedk** [comment]
Could not find an api...

**Comment by techguru0** [comment]
https://github.com/reazon-research/ReazonSpeech
https://huggingface.co/datasets/reazon-research/reazonspeech

**Comment by techguru0** [comment]
> Could not find an api...

its run locally like whisper

**Comment by niksedk** [comment]
Seems like this is the latest: https://huggingface.co/kotoba-tech/kotoba-whisper-v2.1/tree/main
Where is the .bin file?

**Comment by techguru0** [comment]
> Seems like this is the latest: https://huggingface.co/kotoba-tech/kotoba-whisper-v2.1/tree/main Where is the .bin file?

pretty sure you have to sign in on hugginface to see the files
