### ISSUE TITLE
Can't create new line in 'Fix common error' mode

### ISSUE THREAD

**Issue by p1nkyy** [SubtitleEdit/subtitleedit#8883]
Hello, prior to ver 4.0.7, I can create a new line when in 'Fix common errors' mode by pressing the Enter key in the intended line. Now when I do that, it exited the 'Fix common errors' mode immediately. Can this be rectified?
This is unrelated but the position for 'Search & replace' dialogue also becomes in the very bottom part of the screen every time we open SE. It will remember the position of the dialogue box in a session but not for future sessions. The position is very awkward. It didn't use to be like this in older versions (around v3 if I'm not mistaken)

**Comment by niksedk** [comment]
Hm, I cannot re-create either of these two issues... what OS are you using?

**Comment by p1nkyy** [comment]
Hi, Windows 10

**Comment by niksedk** [comment]
Hm, still cannot re-create this... if you have steps to reproduce, please share.
Also, screenshots can be attached. 

Are you using latest SE - 40.8 ?

**Comment by niksedk** [comment]
Beta updated with fix: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
