### ISSUE TITLE
Add Real-Time Subtitle Creation by Clicking Along with Audio/Video Playback?

### ISSUE THREAD

**Issue by PlexSir** [SubtitleEdit/subtitleedit#8885]
I'm using Subtitle Edit to make subtitles for a song. I'm surprised there isn't an easy way to place subtitles by clicking along with the music or video while it plays (or maybe I’m too stupid to find it by myself). I already pasted the lyrics from Google and expected it to be simple - just click a button when a line is being sung, a marker gets placed at that point then it moves to the next line, then you click again when that next line starts, and so on, until the last line. I guess you would have to edit the duration of each line later but that would still make it much faster to make subtitles

Is this possible in Subtitle Edit.

**Comment by techguru0** [comment]
not yet

**Comment by UnHolyGrounds** [comment]
I'm not positive that it'll work in that situation but it does kind of exist. I've not tried it extensively. 

From Main Subtitle Edit windows go to Options -> Settings
Then click on Shortcuts in the new window. Search for Key Down in shortcuts. Setting the key for it will allow you to hold the key while sound is being played and release to set the end of that subtitle line, then it will go to next line automatically.
