### ISSUE TITLE
Auto-translate new feature

### ISSUE THREAD

**Issue by phong-jack** [SubtitleEdit/subtitleedit#8890]
I think it better if this app add prompt input to optimize response result for auto translate

**Comment by niksedk** [comment]
Check advanced settings

**Comment by phong-jack** [comment]
Hmm i use google gemini ai and not see this
![image](https://github.com/user-attachments/assets/66280aa1-99fc-4703-b3f2-30350c6482c5)

but another model have prompt input? 
![image](https://github.com/user-attachments/assets/f3ae8aab-99c3-4d72-896d-d07f9f34991c)

Why? can't gemini add prompt?
