### ISSUE TITLE
Application error when translating subtitles

### ISSUE THREAD

**Issue by claudemartin** [SubtitleEdit/subtitleedit#8901]
![image](https://github.com/user-attachments/assets/24824fc2-b8b5-4c4e-84ab-eb0331a3d1cb)

I had to create a screenshot because it's not selectable text and I can't copy&paste it. 
It was running for hours and was almost done. Maybe it happened when translations were actually finished. Normally it works just fine.  I use  Ollama and gemma2. I can "ignore" the issue but then the translation window was gone. I managed to somehow get it to display again and all translations are still there.

**Comment by niksedk** [comment]
Thx for the issue report :)

Should now hopefully be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
