### ISSUE TITLE
waveform and audio playback synchronisation problem

### ISSUE THREAD

**Issue by wmeler** [SubtitleEdit/subtitleedit#8902]
While subtitling mp3 file on windows when you click on waveform to set playback point it stops playing and moves marker to clicked location as it shoud (maybe we shoud consider to not stop playback). After clicking play button it starts playing from another location in audio file with waveform out of sync. It should start from location pointed in waveform panel.

**Comment by niksedk** [comment]
It really depends on your video player inside SE. 
What video player inside are you using?

It is also possible to file was encoding poorly for seeking.

**Comment by wmeler** [comment]
![image](https://github.com/user-attachments/assets/d03c5f7f-ee4b-4d30-8fce-930bf3c641f9)

**Comment by niksedk** [comment]
Is it better if you use "mpv" ?

**Comment by wmeler** [comment]
mpv works like a charm! thanks a lot!

**Comment by niksedk** [comment]
Cool :)

**Comment by wmeler** [comment]
I also tried VLC - it works better than directshow but still worse than mpv
