### ISSUE TITLE
"Change casing" > "Only change all uppercase lines" does not redo lines that are all uppercase but also contain tags

### ISSUE THREAD

**Issue by Hlsgs** [SubtitleEdit/subtitleedit#8903]
This happens both in the main interface and when batch converting. The example I've come across is the basic `<i>` tag.

Example line that does not get changed:
`<i>LOREM IPSUM</i>`

However, this line does get changed:
`<I>LOREM IPSUM</I>`

So, I guess it's a matter of filtering out the tags before doing the all uppercase check.

**Comment by niksedk** [comment]
Thx for reporting this :)

Should hopefully now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
