### ISSUE TITLE
When you open settings, the "minimum milliseconds between lines" setting resets

### ISSUE THREAD

**Issue by stevens195** [SubtitleEdit/subtitleedit#8910]
Title is self-explanatory, whenever I'm working on a 29,97fps project for instance, where I need the minimum gap between subtitles to be 67 milliseconds, everytime I open the settings tab on SubtitleEdit the value resets to 24. Opening the settings seems to be itself the issue, even if I don't change any setting and just immediatly close the settings after opening them, the value resets to 24.

**Comment by niksedk** [comment]
Sorry, I cannot re-create this.

**Comment by stevens195** [comment]
Subtitle Edit v. 4.0.8

**Comment by stevens195** [comment]
> Sorry, I cannot re-create this.
> 
> What version of SE are you using?

Subtitle Edit v. 4.0.8

**Comment by stevens195** [comment]
![image](https://github.com/user-attachments/assets/06d342ca-d2b4-45e4-a8bc-e1481050f924)
 info on the left (milliseconds) resets back to 24 every time I open the settings, even if I don't change any value within the settings of SE. Tested it in 3 different computers and was able to replicate it in all of them

**Comment by niksedk** [comment]
Sorry, I still cannot re-create this... can you give exact steps?
Also, how do you install SE and to where? (portable version? To which folder?)

**Comment by stevens195** [comment]
I figured out what was going on, seems like the "General" tab in the settings also has an option for applying minimum gap between subtitles, which I had never changes so the value was 24 (default) 
![image](https://github.com/user-attachments/assets/54618246-6570-4189-b076-4ce68ae63eca)


That setting probably overlaps the one on the "Tools" tab, so everytime I opened up settings and clicked "OK" it reset to 24ms every time.
