### ISSUE TITLE
Listen to media-keys

### ISSUE THREAD

**Issue by thatux** [SubtitleEdit/subtitleedit#8913]
Is it possible to use the media keys on my keyboard: play, pause. To start and stop Subtitle edit?

https://gist.github.com/MightyPork/6da26e382a7ad91b5496ee55fdc73db2#file-usb_hid_keys-h-L266

Or as an alternative set a global key shortcut that Subtitle edit listens to even when it's not in focus?

**Comment by niksedk** [comment]
Can you setup a shortcut?

Go to Options - Settings - Shortcuts
![image](https://github.com/user-attachments/assets/2c4c2278-7b70-4eea-ba43-49a472f36c03)
