### ISSUE TITLE
Slow program opening

### ISSUE THREAD

**Issue by Domtecum** [SubtitleEdit/subtitleedit#8922]
When I open the program from right-clicking on a file, it takes a long time to open.
If there are multiple subtitle tracks, after choosing one, it takes 90 seconds for the program to open.
Can't you improve this! Thanks.

**Comment by niksedk** [comment]
Could you attach a sample file?

SE opens pretty fast here...

**Comment by Domtecum** [comment]
This is a whole movie that I can't attach.

**Comment by niksedk** [comment]
How large is the mkv file? Are you opening a subtitle embedded in the mkv file?

**Comment by niksedk** [comment]
You could also try another video player inside SE to see if that's better.

**Comment by Domtecum** [comment]
The video files are between 2 and 5 GB in size and are composed of several subtitle files (srt)
