### ISSUE TITLE
Murf Text to Speech API

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#8976]
Can we have the Murf Text to Speech API added in the Text to Speech Feature?
https://murf.ai/api

Thanks!

**Comment by niksedk** [comment]
@MbuguaDavid: Does this work? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

**Comment by MbuguaDavid** [comment]
Thank you so much for this. 
Can we have a way to set the Pitch and Speed of the voiceover?
![add pitch and speed](https://github.com/user-attachments/assets/1af65753-2161-4438-a1e7-0f7c699e3e29)

I've noted the speed in some of the voiceover is 100% speed making it too fast.

![Speed in TTS MUrf](https://github.com/user-attachments/assets/8d2aa840-0c0c-4571-ab6d-320846dd2ca8)

Thanks!

**Comment by niksedk** [comment]
Sure, I've tried to add pitch and speed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

**Comment by MbuguaDavid** [comment]
> Sure, I've tried to add pitch and speed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

Thanks! 
I;ve tested and noted that even with the speed set to 0, the final output is at over 150 %. 
Is there a way to force it to be normal speed or something? 

![speed too fast](https://github.com/user-attachments/assets/d5b72adc-2b19-47d4-aca0-a3a745163d13)

**Comment by niksedk** [comment]
When having speed above 100% means that SE has shortened the audio, as the duration is not long enough.

**Comment by DomoMKT** [comment]
you're looking for a way to convert text to high-quality speech with low latency, and i've got just the thing: you can find it all at [www.nemesyslabs.com](https://www.nemesyslabs.com)!
