### ISSUE TITLE
Pressing Enter for line breaks no longer works?

### ISSUE THREAD

**Issue by THGhost** [SubtitleEdit/subtitleedit#8980]
I'm using version 4.0.8 and I've noticed that pressing Enter/Return to insert a line break no longer works inside the "Fix common errors window". Pressing it now selects the "OK" button and saves all of the changes, including any you didn't want to make further down.

This completely breaks my workflow. Could it be reinstated please?

**Comment by THGhost** [comment]
Just tried version 4.0.7 and this does not happen. So something changed between versions.

**Comment by niksedk** [comment]
This should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
