### ISSUE TITLE
[Feature proposition] Add a second Text box/area to paste a second language

### ISSUE THREAD

**Issue by AmineMessabhia** [SubtitleEdit/subtitleedit#8983]
I don't know how easy/hard this might be, and even how helpful it would be, but please hear me out:

If you have a script in 2 languages, and you want to create subtitles for 2 languages at once, wouldn't something like this be helpful?

![image](https://github.com/user-attachments/assets/2e60d94a-3059-48a0-b4bd-3c125573e23b)

You'd select the audio duration, paste both texts, then click next, rinse and repeat, and once done, you'll be able to export 2 SRT files, each for a language.

What do you think?

**Comment by darnn** [comment]
Are you aware of translator mode? Open a subtitle and then go to `Tools`->`Make new empty translation from current subtitle`.
If you want to paste subtitles into here, you should have a second subtitle file ready (where the timings are irrelevant), copy it, and then use `Column paste`, either by creating a keyboard shortcut for it, or by right-clicking on the first subtitle and then navigating to `Column`->`Paste from keyboard`.

**Comment by AmineMessabhia** [comment]
Thank you! @darnn!
