### ISSUE TITLE
Question on: gpt-3.5-mini and gpt-4o-mini

### ISSUE THREAD

**Issue by marcello-pietrobon** [SubtitleEdit/subtitleedit#8992]
I have memory that in some older version of SubtitleEdit it was possible to transcribe a video by using 'gpt-3.5-mini' model for free without inserting any API key, and without having to connect to internet either.

Now in the current version of SE, I can see 'gpt-3.5-mini' model only in the Auto-translate utility, and a key is asked in there.

Do I remember correctly that, **it was possible in the past to transcribe a video with 'gpt-3.5-mini' model without any key?**

If so, **is it possible somehow to transcribe a video with a 'gpt-4o-mini' model without any key?**

If I'm confusing myself can you help me clarify?

Thank you.

**Comment by niksedk** [comment]
Sorry, that has never been possible. 
You can get a free API key with limited quota.

You can run Ollama with e.g. llama 3.2 for free.

**Comment by marcello-pietrobon** [comment]
Thank you for answering me.

After your reply I started wondering why Ollama is used only for translation and not for transcription. but reading around a bit it seems like that for transcription Whisper outperforms Llama, so, if that is true, I'm happy with how things are on this front.
