### ISSUE TITLE
regular expressions always worked fine, but recently I'm having this anomaly

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8996]
With Ctrl-M I can add music symbols at the beginning and the end of sentences and it works fine.
It doesn't work exactly how I want it, because it adds a symbol at each beginning and end of the line.

I prefer to have only 2 music symbols in total.

Not a big problem, as I can do a search-replace afterward with a regular expression and get rid of them.
Somehow it doesn't work anymore and I have to use Notepad++ to do this.

I haven't noticed any other strange behaviour with regular expressions.

Using 5.08

<img width="599" alt="image" src="https://github.com/user-attachments/assets/fdebb6cf-388a-4b5e-9045-4210cabcdf30">

**Comment by niksedk** [comment]
I think you can use the "Custom toggle tag":

![image](https://github.com/user-attachments/assets/0e1b905c-05fb-4ca9-b096-ba75e930a2a2)


![image](https://github.com/user-attachments/assets/db4db0e8-e013-4414-b9d8-b639be2c181c)
