### ISSUE TITLE
Is there anyway to adjust speed of audio conversion? 

### ISSUE THREAD

**Issue by solutionall** [SubtitleEdit/subtitleedit#9001]
After translating feature I used Text to Speech and it works. But only problem is some audio is too fast with long text. How can I adjust audio clip for that speed? Is there anyway to make this? For example in long text audio speed will keep normal however video will be slow down or freeze.

**Comment by niksedk** [comment]
Make sure you do not have a too high CPS (Characters per second) before doing TTS.

**Comment by solutionall** [comment]
What can I do if I got too high CPS from translation?

**Comment by niksedk** [comment]
You can make the duration longer is there room that that. Otherwise you will have to make the text shorter.

**Comment by DomoMKT** [comment]
you can achieve the perfect balance of speed and quality by converting your text into high-quality speech with extremely low latency on [www.nemesyslabs.com](https://www.nemesyslabs.com).
