### ISSUE TITLE
Automatic translation selection for chatgpt cannot choose Uyghur language

### ISSUE THREAD

**Issue by oqughin** [SubtitleEdit/subtitleedit#9003]
When using the tool to translate subtitles, the target language cannot be selected as Uyghur

**Comment by niksedk** [comment]
Does it work with Uyghur on the web site?

It's not in the supported languages list: https://botpress.com/blog/list-of-languages-supported-by-chatgpt

**Comment by darnn** [comment]
It at least does it in the chat with 4o, so it should be capable of it...
