### ISSUE TITLE
OCR .sup Tesseract + LSTM detect Italic

### ISSUE THREAD

**Issue by Slava46** [SubtitleEdit/subtitleedit#9012]
Is it possible to do italic detection when do OCR .sup using Tesseract + LSTM?
Because just Tesseract 5.3.3 can detect italic, but result of OCR'ing much better with using + LSTM mode.
And for more quality mode Tesseract + LSTM not working italic detect...

**Comment by niksedk** [comment]
Sorry, Tesseract LSTM is just bad at detecting font properties :(

You can try nOCR, which works well for subtitles with large fonts.
