### ISSUE TITLE
Reversed order of lines in displayed sets of lines in F2 dialog box of Whisper transcription

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#9021]
Subtitle Edit 4.0.8

When you press the F2 key while transcribing audio to text with Faster-Whisper-XXL, the order of the lines in the displayed batches of lines, is reversed.

In an earlier version of SE, this order was correct. When running the same process in a Windows command prompt, this order is correct. 

In the example below, the first set of displayed lines starts at 00:00.000, and the second one (just one line) starts at 00:28.760.

Please correct this order.

![Reverse order in batches of transcribed lines](https://github.com/user-attachments/assets/ce7a2750-3aee-45f4-bef1-0a360889913f)

**Comment by niksedk** [comment]
It works fine here... but SE just displays data received from Whisper, and Whisper does parallel processing, so lines may not appear ordered.

**Comment by Purfview** [comment]
F2/log always looked not in order for me like in your screenshot.
