### ISSUE TITLE
Whisper window cannot be restored after minimizing, can you provide an independent "audio to text"s executable program

### ISSUE THREAD

**Issue by vimbackground** [SubtitleEdit/subtitleedit#9024]
I often use subtitle edit for "audio to text" conversion, and I found that when I minimize the audio to text window while performing whisper operations, subtitle edit cannot continue to operate. There is no way to recover the audio to text function, and subtitle edit itself cannot continue to operate either. How can this issue be resolved?

Can an independent exe entry be provided for the audio to text function, as a sub-application of subtitle edit. Or, can an audio to text button be added to the toolbar?

Personally, I think subtitle edit's audio to text function is better than most other similar software I have used.

**Comment by Purfview** [comment]
>Can an independent exe entry be provided for the audio to text function

https://github.com/Purfview/whisper-standalone-win

**Comment by vimbackground** [comment]
Thank you for your reply. I have already favorited it.

The issue with the Subtitle Edit whisper window not being able to be restored after minimization, I hope this can also be resolved.

If a convenient entry point could be added for this window, it would be very useful, a GUI window is still quite convenient :）
![Snipaste_2024-11-24_11-25-17](https://github.com/user-attachments/assets/179fd361-f2b2-481a-9159-389a35482474)

**Comment by Purfview** [comment]
>  a GUI window is still quite convenient

Not at all, why you need a GUI for a program where you don't interact there with anything?
There is input and output, that's it.

**Comment by vimbackground** [comment]
You're right, it's not really necessary, but sometimes I just want to check the progress :)

**Comment by Purfview** [comment]
> You're right, it's not really necessary, but sometimes I just want to check the progress :)

You don't need GUI for that, you have accurate progress in CLI terminal and even in the title too. When in SE you don't see accurate progress.

Added "One Click Transcribe" tool in r194.2, and here is instruction: https://github.com/Purfview/whisper-standalone-win/discussions/337

**Comment by vimbackground** [comment]
OK，thx for you
