### ISSUE TITLE
minimize batch subtitle making with whisper

### ISSUE THREAD

**Issue by innerspeakerz** [SubtitleEdit/subtitleedit#9030]
When you minimize the batch audio to text subtitle maker that uses any whisper model, I am not able to view its progress later. I cant unminimize the whisper audio to text batch subtitle maker. I just see the main subtitle edit window. It does continue making them and finishes eventually, but the window that shows progression for the batch disappears.

**Comment by niksedk** [comment]
Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
