### ISSUE TITLE
Thread Exception

### ISSUE THREAD

**Issue by masterofthesith** [SubtitleEdit/subtitleedit#9032]
![SLGAR9lZ3k](https://github.com/user-attachments/assets/eb4d9be5-1c13-422d-aefb-bffffb5a1f39)
[eng.txt](https://github.com/user-attachments/files/17907104/eng.txt)
VTT file attached with txt extension

This error appeared when using translate function with deepL v2

**Comment by niksedk** [comment]
I think this has been fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

**Comment by masterofthesith** [comment]
> I think this has been fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

![xtl4wjFypQ](https://github.com/user-attachments/assets/dbb5e42b-21cb-4f8a-bb5a-beb907e41c95)

:(

**Comment by niksedk** [comment]
Tried the `ServicePointManager.SecurityProtocol = (SecurityProtocolType)192 | (SecurityProtocolType)768 | (SecurityProtocolType)3072;` - it was worth a shot, but it does not work...

I will do some more testing...

**Comment by niksedk** [comment]
Dupe of #9034
