### ISSUE TITLE
Previewing burned-in subs displays exception message

### ISSUE THREAD

**Issue by StickyChannel92** [SubtitleEdit/subtitleedit#9036]
![image](https://github.com/user-attachments/assets/6bd0a768-a4c5-4232-936f-d3ce23194bac)

Without opening a video before starting, go to Video > Generate video with burned-in subtitle, upload a bunch of videos that have sub files, then click on Preview.

**Comment by niksedk** [comment]
This should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
