### ISSUE TITLE
csv - wrong timestamp format

### ISSUE THREAD

**Issue by MariaB99** [SubtitleEdit/subtitleedit#9045]
Hi,
When saving subtitles in csv format, in columns 'Start time in milliseconds;End time in milliseconds' it creates strange values with decimal values like eg.: 329423.333333333. 
Then, after loading such a csv back into the editor it is unable to load this values and ommits those lines even though they are in raw csv.

Thanks for your help.

**Comment by wegylexy** [comment]
TSV1 and TSV2 too, please.
