### ISSUE TITLE
Do-not-break-after lists — Additional suggestions for improvements

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#9054]
SubtitleEdit 4.0.8 NEXT beta 238

Thanks for the recent improvements in the do-not-break-after lists in SE. I am sorry for whining about these lists again.

- The order of the language list in the "Use do-not-break-after list" dialog box in SE, is still not fully alphabetic. This is the current list, with items out of alphabetical order in bold italics:
Arabic
Bulgarian
Bosnian
Czech
Danish
_**German**_
_**Greek**_
English
_**Spanish**_
Finnish
French
_**Croatian**_
Hungarian
Indonesian
Italian
Lithuanian
Latvian
Macedonian
Norwegian
_**Dutch**_
Polish
Portuguese
Romanian
Russian
Sami
Sinhala
Slovak
_**Albanian**_
_**Serbian**_
Turkish
Vietnamese

- There is no do-not-break-after list for Estonian in SE. (See [here](https://github.com/SubtitleEdit/subtitleedit/issues/8764#issue-2485833561) for missing languages.)
- There is no do-not-break-after list for Slovene in SE.
- There is no do-not-break-after list for Swedish in SE.
- There is no do-not-break-after list for Ukrainian in SE.
- The Dutch do-not-break-after list in SE now lists only articles, but no abbreviations. This is inconsistent with the do-not-break-after lists of most other languages, because they list abbreviations. (There are two lists for Dutch [here](https://github.com/SubtitleEdit/subtitleedit/issues/8764#issue-2485833561).)
- Except for German ('dem', 'den', 'des' missing) and Greek, and now Dutch, articles as specified [here](https://github.com/SubtitleEdit/subtitleedit/issues/8764#issue-2485833561), have not been included in the do-not-break-after lists. Is it intentional that most languages that have two lists [here](https://github.com/SubtitleEdit/subtitleedit/issues/8764#issue-2485833561) (an article list and an abbreviation list), only use the language's abbreviation list?
- According to [this](https://radica-schenck.de/en/2020/10/25/macedonian-or-north-macedonian-what-is-the-correct-name-for-the-language-now/), "Former Yugosl..." should not be used to describe the Macedonian language. Macedonians would prefer their language to be named like this: "Macedonian (Македонски)".
- In the Lithuanian list, "pn." (with period) is now missing. [This is the complete Lithuanian list: "Dr, Dr., P., Pn, Pn., dr, dr., pn, pn.".]

**Comment by niksedk** [comment]
Hopefully the sorting + missing languages are better now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

Could you add a PR with your suggested changes to the `*_NoBreakAfterList.xml` files?

**Comment by oep42** [comment]
SubtitleEdit 4.0.8 NEXT, beta 240

Thanks for the improvements. The order of the list of languages in the "Use do-not-break-after list" dialog box in SE is correct now, and the four missing languages have been added. However, Sami and Sinhala have disappeared from the list.

A new problem has emerged: Some of the languages in the language list refer to the wrong xml file. For instance, Albanian now shows the Arabic do-not-break-after items.

The default language when opening the language list in the "Use do-not-break-after list" dialog box in SE is now Albanian, while is was English before. English makes more sense as default language.

The name "Macedonian" in the list of languages is still followed by "(Former Yugosl...", while I would suggest to replace this by "(Македонски)".

Because of the current unreliable relationship between a language in the language list, and the referenced xml file, I didn't check the contents of lists of do-not-break-after items for now.

I don't know how to add a PR, sorry. If that would be helpful, I could incorporate suggested changes into existing *_NoBreakAfterList.xml files and put them in a zip file and upload that here.

**Comment by niksedk** [comment]
Thx - the sort fix did not really work, but should now be better: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

Yes, if no PR, then please attach a zip file with _NoBreakAfterList.xml files :)

**Comment by oep42** [comment]
SubtitleEdit 4.0.8 NEXT, beta 241

Thanks for the improvements. As far as I can see, the languages in the language list now all point to the correct xml file.

Sami and Sinhala, which disappeared from the language list in beta 240, did not return to this list in beta 241.

I hadn't noticed this before: In the language list, the language name in English is followed by the language name in that language (in parentheses). Sometimes this name in parentheses starts with a capital letter, sometimes not. It may look better if they always started with a capital letter.

As a whining nitpicker, I still suggest to add "(Македонски)" after "Macedonian" in the language list. Also, Albanian is still the default language of the list, but perhaps this is intentional.

For 11 languages (Danish, Dutch, English, French, Hungarian, Italian, Lithuanian, Norwegian, Portuguese, Spanish, Swedish), I edited the xml files with suggested additions. Please see this zip file for these updated xml files:

[Updated_NoBreakAfterLists.zip](https://github.com/user-attachments/files/18001404/Updated_NoBreakAfterLists.zip)

**Comment by niksedk** [comment]
Thx for the files :)
Beta upated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

>Sami and Sinhala, which disappeared
Was just just other languages with wrong file name...

>I still suggest to add "(Македонски)" after "Macedonian
Sorry, the names are from Microsoft/Window...

Default language should now be better.

**Comment by oep42** [comment]
Thanks for all the improvements. Everything looks good now.

**Comment by niksedk** [comment]
Nice, and thank you too :)
