### ISSUE TITLE
Possibly wrong WAV conversion for whisper.

### ISSUE THREAD

**Issue by 0wwafa** [SubtitleEdit/subtitleedit#9060]
When I try using whisper, I see a temp wav file in `%appdata%Subtitle Edit\Waveforms`.

The wav file (for correct whisper input) should be obtained by:
ffmpeg -i INPUT.MKV -acodec pcm_s16le -ar 16000 -ac 1 -f wav "temp.wav"

This produces a 16khz signed pcm 16 bit little endian wav file.

Instead if I check the file I see this:

```
Input #0, wav, from '58861537686474c2-0.wav': 0KB sq=    0B
  Duration: 01:57:06.66, bitrate: 4 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 150 Hz, 2 channels, s16, 4 kb/s
   6.13 M-A:  0.000 fd=   0 aq=    1KB vq=    0KB sq=    0B
```

The length is right, but the rest is crazy: 150Hz?  4kb/s ?

**Comment by niksedk** [comment]
Looks good to me:

![image](https://github.com/user-attachments/assets/d9fb4a87-b056-409f-95a7-cb325d086cab)

File name: ...
File size: 812 kb
Duration: 26,005
Codec: WAV

Tracks:
#1 - Audio
pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s

___________

Small tip:
You can right-click on the media file name in SE (lower right corner) - and choose "Media information" for codec info.
![image](https://github.com/user-attachments/assets/c77ed4d0-41bd-49fd-a564-80ae2dfbd481)
)

**Comment by 0wwafa** [comment]
@niksedk 
Also: for long videos it seems to stop working after a while (and start repeating the last text)
Any idea how to avoid this?

**Comment by niksedk** [comment]
What model are you using?
Try with large-v2... and perhaps "Purfview's Faster Whisper"

**Comment by 0wwafa** [comment]
@niksedk you told me I can check the media by right clicking.. but all I see it's this:
![image](https://github.com/user-attachments/assets/fc988241-bd62-4f52-90e9-52a1b34147bf)

**Comment by 0wwafa** [comment]
```
Date: 12/05/2024 20:53:41
SE: 4.0.8.0 - Microsoft Windows NT 10.0.19045.0 - 64-bit
Message: C:\Users\Zibri\AppData\Roaming\Subtitle Edit\Whisper\Cpp\main.exe --language it --model "C:\Users\Zibri\AppData\Roaming\Subtitle Edit\Whisper\Cpp\Models\medium.bin" --output-srt --translate --print-progress -t 3 -l it "C:\Users\Zibri\AppData\Local\Temp\3fa169bf-5527-4d54-bb40-3fbbb05d6e62.wav"
```

**Comment by 0wwafa** [comment]
> Looks good to me:

Yep.. my bad. The wav in LocalTemp is correct.
I was looking at the wav in `%appdata%Subtitle Edit\Waveforms`

**Comment by 0wwafa** [comment]
@niksedk also, it would be nice to see the subtitles in the subtitle view "as they come", because sometimes the models f*ck up and you will know that only at the end.

**Comment by Purfview** [comment]
> Also: for long videos it seems to stop working after a while (and start repeating the last text) Any idea how to avoid this?

Use "Purfview's Faster Whisper".

**Comment by 0wwafa** [comment]
> > Also: for long videos it seems to stop working after a while (and start repeating the last text) Any idea how to avoid this?
> 
> Use "Purfview's Faster Whisper".

Thanks! This works perfectly!
I think whisper.cpp is deeply flawed.
Results (with the same model, medium or large-v2) are perfect with "Purfview's Faster Whisper" and are completely wrong, with whisper.cpp.
