### ISSUE TITLE
Crash while opening video file

### ISSUE THREAD

**Issue by nounours18200** [SubtitleEdit/subtitleedit#9065]
Hi,

I regularly use S.E. without any problem (perfect software) but I have a crash while opening several video files (coming from the same source, so it may be a problem with the video file itself).

The error window is here: 
https://mega.nz/file/424jVYDL#3Ax-WeVIlM4RbzskaPWr-9gboMITlj4BkKjxWa-_chY

and the video file is here:
https://mega.nz/file/lrByGT7B#hu1F7rGvwXOqTsVd-WgLk5gCO-jBeYh30rAvbH3bOgM

What can I do ?

Thank you

**Comment by niksedk** [comment]
Are you using mpv as video player? 
See Options - Settings - Video player.

**Comment by nounours18200** [comment]
After having dowloaded the MVP library (in Options->Settings->Video player), it works on most files of the set, but S.E. still fails in an infinite loop and does not open the following video file:
https://mega.nz/file/QmITxarS#YpP_KsIWVOAGihLIGsQISvcfhJB-DAjb88_cr6hO0PE

Any idea ?

P.S.: By the way, I already use the 4.0.8 version of S.E. dated 6th September 2024.

**Comment by niksedk** [comment]
Did you try the above beta?

**Comment by nounours18200** [comment]
Yes: as indicated above, my installed version is the 4.0.8.

I have found a turnaround to avoid the infinite loop problem: I have re-encoded the video file with Handbrake.
Then the re-encoded file is opened by S.E. without problem: so it was probably due to the original video file.

So I let the problematic video file on the Cloud (mega.nz) in case somebody wants to analyse it, but I have solved the issue by re-encoding the video file.

**Comment by niksedk** [comment]
Did you try the BETA version?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

**Comment by nounours18200** [comment]
Why the 4.0.8 BETA would solve an issue that the 4.0.8 regular (non Beta) would not solve ???

**Comment by niksedk** [comment]
The beta version is brand new... it is a beta of the next version of SE. 
You can also check the timestamp of the file (atm it's uploaded 7 hours ago)

**Comment by nounours18200** [comment]
Oh, I see, I would expect it to be named '4.0.9 Beta" ???

I am using S.E. 4.0.8 to finish the subtitle with the video that I have re-encoded with Handbrake (so far it seems OK, whereas not 100% perfect), and I will install the beta just after...

Thank you
