### ISSUE TITLE
Whisper --max_line_count extra parameter seems not to work

### ISSUE THREAD

**Issue by marcello-pietrobon** [SubtitleEdit/subtitleedit#9071]
Hello,

after your answer to the question #8994 (Question: Few questions on Whisper)
I applied and discovered that **the --max_line_count extraparameter seems not to work**.

Using Faster-Wisper-XXL with SE version 4_0_08_beta of last month, November 2024

I use the following extraparameters for Faster-Wisper-XXL:

`
--max_line_width 38 --max_line_count 1
`

(this is confirmed by the wisper_log.txt file),
```
Date: 12/07/2024 14:55:39
SE: 0.0.0.0 - Microsoft Windows NT 10.0.19045.0 - 64-bit
Message: C:\Users\giogio\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language en --model "tiny.en" --max_line_width 38 --max_line_count 1 "D:\Work\files\videos\Test\myvideo.mp4"
```

Here's the description of this parameter:
```
  --max_line_count MAX_LINE_COUNT
                        The maximum number of lines in one sub segment. (default: 1)

```

yet the output still has many paragraphs like:

```
5
00:00:11,733 --> 00:00:13,820
Well, the outlines
are pretty clear.

```

Questions:
What should I do in order to debug or assess this problem?
Do you think the problem is with whisper itself, which implementation did you use, or where should I ask for this problem to be fixed?

Thank you very much for any answer.

**Comment by Purfview** [comment]
Probably it was split by SE's post-processing, make sure that "Use post-processing" is not selected.

**Comment by marcello-pietrobon** [comment]
Thank you, I just unchecked the option 'Merge Short Lines' in the Postprocessing settings and now it works.
