### ISSUE TITLE
Whisper and multiple speakers

### ISSUE THREAD

**Issue by marcello-pietrobon** [SubtitleEdit/subtitleedit#9072]
What's the state of the art in SE handling multiple speakers with Whisper?
@Purfview 

If somehow this is not possible I wonder if SE is able to transcribe selected sections of the video,
this way it would be possible to do something like:

  **a**. select the  subtitles transcribed in the 'wrong' language
  **b.** have SE to tell whisper which time interval to transcribe
  **c.** have SE to replace the selected subtitles with those transcribed in the 'correct' language (which the user did manually set).

Even having any part of a, b, c capabilities would be nice.
Is it possible?

Thank you for your answer, beside the time given to SE

**Comment by Purfview** [comment]
>Whisper and multiple speakers

What about it? That's normal case for transcriptions.
If you meant different language speakers then try `--multilingual true` option.

**Comment by niksedk** [comment]
You can make a new subtitle line spanning the section you want to run Whisper on - and right click in the list view, selected lines, audio, whisper...

or... you can also selected the individual lines in the list view, and run Whisper on these (require precise selection and will be somewhat slow)
