### ISSUE TITLE
On 4.08, the issue of Whisper SHA-512 hash does not match occurred again

### ISSUE THREAD

**Issue by ms7107** [SubtitleEdit/subtitleedit#9073]
I saw that someone had this problem before in 4.02, and now I am using 4.08 with the same issue. Some people said that there is a problem with the firewall, and I have tried to turn it off. How can this problem be solved, or can we just wait for the version update?

**Comment by niksedk** [comment]
Could you add some screenshots and tell more about what exactly you're doing and where?

**Comment by ms7107** [comment]
It appears when installing whisper

[cid:ce7d7a0c-7c56-4e98-a981-88daf0bf50f3]

________________________________
发件人: Nikolaj Olsson ***@***.***>
发送时间: 2024年12月8日 17:36
收件人: SubtitleEdit/subtitleedit ***@***.***>
抄送: ms7107 ***@***.***>; Author ***@***.***>
主题: Re: [SubtitleEdit/subtitleedit] On 4.08, the issue of Whisper SHA-512 hash does not match occurred again (Issue #9073)


Could you add some screenshots and tell more about what exactly you're doing and where?

―

**Comment by ms7107** [comment]
The first time it appeared was when downloading and installing Whisper. When I cancelled and manually downloaded Whisper, it appeared a second time when starting to generate.
<https://1drv.ms/i/s!AmGJAIfVfSMqiURjBEAM_MlfSj0a>
[https://odrlmg.bn.files.1drv.com/y4moZchlSiyjZX-gGfsT9aRxtgb5LdaLcwph-7xEVOsySlzWd5dMC57nTmUN21O2iFQ7foHwe1RzGXpxogwvmwxpdRwk6nUmlaxSlfGQApQs_wwXvY6hfFFR0_y5fRoFWNr4SO10k_ndu5pU0YCWgBDbNkzyRiInqPDtTwV16ZE1VMmS6tdeHLvv-SkYBB1OfYoCIcwsBcFXO75VVuVonSJ_g?width=200&height=150&cropmode=center]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]54e01ba59dc75abb6a7cce0f69dbb68.png
<https://1drv.ms/i/s!AmGJAIfVfSMqiUUrdb4L6prYgoTv>
[https://nzrlmg.bn.files.1drv.com/y4mnTrEiYST67LaI4aLKU3foE0d_wZUCeFrzlsOHUc_t0gsNF8YRxT8-ruqXygXhWtKcTDJVRzjAw3pXa8oNKlsKQhRtGUF2uuyeWWJXqrUc-QPXIegdyneDY_-pF54iymt5qfA3LfS5MUkN823Be6b3FZSgurC8jhUGPeAhewO6Z3eIkh7vlnFzRInEN3NAhaUuwXN2vGRGwdtB_NaTsSXmA?width=200&height=150&cropmode=center]
[https://res-1.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]495f990b808e48c71829b6bdca711f0.png
<https://1drv.ms/i/s!AmGJAIfVfSMqiUY6qJjiMMSOHz0t>
[https://njrlmg.bn.files.1drv.com/y4mvUNKtR3EfaJBXdGXHIE4V-Lj4oTIqbnQQ5WKWGhscjl-3x69qzc6MftE9x6Ymgdw8h3OHtRm4rd9FL5l1zE5l8SIGvlyrWUs0jxX0WgTlb-pcDCcJpg3PcXhaO_qgeJSpX9D7fNmxmxg2oYgu_fGCCbeQKDj_PBSJCnVXm8btaJkLJOz3T6WMMgqwzs0pxWwbsWRiUadRh2AJI-lc7FQiw?width=200&height=150&cropmode=center]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]d14a1db0d72b1712c005a7a0d41baa7.png
<https://1drv.ms/i/s!AmGJAIfVfSMqiUdM5ljPKedFlYeI>
[https://ntrlmg.bn.files.1drv.com/y4mttOkbNkqjPfYNEF9hL9ZgVmwgGZVKTGQTudCT5VLSlNQvhrjOahmUklzPNj5blVY7EfmWAwnWxiVXZpUtJ9TFhcNG0DCH5OzG8sc1MnAhlIn9O7VUoeZH9vRGCkE2jRgo0s7p3ZqiPsZHCVURpmdeopYlo5RQ1DLfMd-zJaIXGvafpkHEui7zV3gJ4VhFqbWXimISK_Il5xxRnDzm6aiTw?width=200&height=150&cropmode=center]
[https://res-1.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]c2314ca13b86790f95cd648da5cdd34.png
​

________________________________
发件人: Nikolaj Olsson ***@***.***>
发送时间: 2024年12月8日 17:36
收件人: SubtitleEdit/subtitleedit ***@***.***>
抄送: ms7107 ***@***.***>; Author ***@***.***>
主题: Re: [SubtitleEdit/subtitleedit] On 4.08, the issue of Whisper SHA-512 hash does not match occurred again (Issue #9073)


Could you add some screenshots and tell more about what exactly you're doing and where?

**Comment by niksedk** [comment]
Could you attach the images here on Github?

**Comment by darnn** [comment]
![54e01ba59dc75abb6a7cce0f69dbb68 1](https://github.com/user-attachments/assets/e0949216-e8fa-4289-ac81-f2e2836cc24d)

![missing 2](https://github.com/user-attachments/assets/d99bddde-1fbf-4cb1-9422-7dbd32d6daa2)

![missing 3](https://github.com/user-attachments/assets/ce3c882a-59fc-47e3-8295-c73d7497d41d)

![missing 4](https://github.com/user-attachments/assets/f82b8157-56ba-45f3-84a8-fcfab518985a)

**Comment by niksedk** [comment]
Should be fixed in beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
