### ISSUE TITLE
Add vocalize subtitles in real time feature please !

### ISSUE THREAD

**Issue by trimechee** [SubtitleEdit/subtitleedit#9076]
Hi, thank you so much for offer generously to us the amazing Subtitleedit vital amazing software !  

So we know amazing Subtitleedit can convert susbtitles to audio but I would like please to avoid the conversion from subtitle to the audio file which could be long and my idea is to playback the streaming video in the web browser at the same time simultaneously I open Subtitleedit  which will vocalize the subtitle in real time so no need for conversion, thank you!

So I would like to know if Subtitleedit can do that, if not, we hope vocalize the subtitles in real time feature will be added please, thanks!

**Comment by niksedk** [comment]
Sorry, I dont know about this.
