### ISSUE TITLE
Windows Form Thread Exception when installing Whisper in the most recent beta

### ISSUE THREAD

**Issue by AuroraMartell** [SubtitleEdit/subtitleedit#9081]
Hello.

I get the following error when trying to install Faster Whisper XXL on the most recent beta.

![image](https://github.com/user-attachments/assets/04738e36-35a4-4c79-a4cc-1dbd331bd6aa)

What's causing the error? And how to fix?

**Comment by niksedk** [comment]
Hm, I've just added z-zip extraction, but it seems some more dll files are needed.
A new beta will be upped soon...

**Comment by AuroraMartell** [comment]
> Hm, I've just added z-zip extraction, but it seems some more dll files are needed. A new beta will be upped soon...

Thanks, will test when it's up. I'm waiting to see if XXL Faster Whisper works like non XXL Faster Whisper.

**Comment by niksedk** [comment]
This will take some time to fix :(

**Comment by AuroraMartell** [comment]
> This will take some time to fix :(

Shame. But I'm a patient girl.

**Comment by niksedk** [comment]
OK, new beta upped: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
Let me know how it works for you.

**Comment by Purfview** [comment]
Tested. It works.
Could there be a text changed when download completes from "Downloading 100%" to "Extracting..."?

**Comment by AuroraMartell** [comment]
> Tested. It works. Could there be a text changed when download completes from "Downloading 100%" to "Extracting..."?

That would help.

**Comment by AuroraMartell** [comment]
OK now there's a Date and Time error in the latest beta, as seen here:

![image](https://github.com/user-attachments/assets/041b26bd-79c2-46af-862e-72d8978222ef)

**Comment by niksedk** [comment]
OK, new beta uploaded: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
Any better @AuroraMartell  ?

**Comment by AuroraMartell** [comment]
> OK, new beta uploaded: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip Any better @AuroraMartell ?

Will test and report back.

**Comment by niksedk** [comment]
... new beta upped. Pointed to test 7-zip file...

**Comment by AuroraMartell** [comment]
> ... new beta upped. Old beta pointed to test 7-zip file...

Thanks for warning, Nikolaj. I got a no text found error in the previous beta.

**Comment by AuroraMartell** [comment]
OK, now it works.

**Comment by niksedk** [comment]
Thx for testing :)
