### ISSUE TITLE
Desync issue

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#9082]
So, sorry to be a broken record about this, but it's really affecting my workflow.

In translator mode, if there is a file where the first and last subtitles have a timecode of `00:00:00,000 --> 00:00:00,000`, and in between there is a subtitle with an actual timecode, using `split at cursor position` causes a desync:
![image](https://github.com/user-attachments/assets/7ced540b-d7d2-48d3-9542-705beacca1bc)

![image](https://github.com/user-attachments/assets/46f61683-b1a3-4948-b20d-ea4b25002a70)

And if I now use `split at cursor position` (whether or not the subtitle has text):
![image](https://github.com/user-attachments/assets/77168bf1-8050-45f3-bd33-d324e84e0ca0)

My original subtitle, for testing purposes:
[test orig.srt.txt](https://github.com/user-attachments/files/18078822/test.orig.srt.txt)

This is now a scenario I encounter practically every day. So far I've had to just place asterisks in all the subtitles I want to split, finish the translation and then open them separately, outside of translator mode, so I could split them that way.
Usually I either have a file with no timecodes where I'll insert a subtitle or two throughout it. If I don't remember to remove the timecode from these new subtitles, I now can't split anything until I open the file on its own.
Another scenario is that I sometimes have fully timed files, but then I add the film title (or something) in the beginning with no time code, and credits for the translation company at the end, also with no timecode (since someone times these after I finish translating). In this situation I also now can't split anything.
I'll just add that sometimes this takes a while to become apparent. Like, I might split some subtitle and everything will seem fine, there won't be a desync, but if I then try to retime a different subtitle, suddenly a desync will occur. This is just in translator mode, to be clear.

I know this is essentially a duplicate of this: https://github.com/SubtitleEdit/subtitleedit/issues/7777
But as I've explained, it really affects me. And recently conditions at my job have become much worse, and part of that is that I now have to time things where I previously didn't, so it's something I'm feeling particularly strongly at the moment.

**Comment by niksedk** [comment]
Hopefully better in latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Thank you! It does appear to be. I haven't been able to stump it so far. However, there's another thing that causes a desync which I thought was just downstream of this, but apparently not. I'm opening a new issue about it.
