### ISSUE TITLE
No text Found Error With purfview's faster-whisper using a custom model

### ISSUE THREAD

**Issue by SorrHash** [SubtitleEdit/subtitleedit#9083]
Hi, i have problem with purfview's faster-whisper when i use [faster-whisper-large-v2-japanese-5k-steps](https://huggingface.co/zh-plus/faster-whisper-large-v2-japanese-5k-steps).

Boom, Error (No text found).

![Screenshot 2024-12-10 161225](https://github.com/user-attachments/assets/87a9c88c-724e-4ad9-98f8-3ffdcb1571ca)

Whisper log
```
Date: 12/10/2024 16:11:36
SE: 4.0.8.211 - Microsoft Windows NT 10.0.19045.0 - 64-bit
Message: Calling whisper (Purfview's Faster-Whisper-XXL) with : D:\Games\Sonic Unleashed XBOX\xenia canary 2023\patches\SE\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language ja --model "large-v2-japanese-5k-steps"  "D:\Games\Sonic Unleashed XBOX\xenia canary 2023\patches\SE\New folder\[heponeko] Tsuyoshi Shikkari Shinasai #27 [ANIMAX 768x576 h264 AAC].mp4"
['tiny', 'tiny.en', 'base', 'base.en', 'small', 'small.en', 'medium', 'medium.en', 'large-v1', 'large-v2', 'large-v3', 'large', 'large-v3-turbo', 'turbo', 'distil-large-v2', 'distil-medium.en', 'distil-small.en', 'distil-large-v3']

Try these known models:

Unknown model not found at: D:\Games\Sonic Unleashed XBOX\xenia canary 2023\patches\SE\Whisper\Purfview-Whisper-Faster\_models\faster-whisper-large-v2-japanese-5k-steps
Calling whisper Purfview's Faster-Whisper-XXL done in 00:00:02.6909183
Loading result from STDOUT
```

Any Help?

**Comment by niksedk** [comment]
Whisper cannot find the model `large-v2-japanese-5k-steps`

**Comment by SorrHash** [comment]
> Whisper cannot find the model `large-v2-japanese-5k-steps`
> 
> Can you choose the model from the UI? How is the folder structure and what files does the `large-v2-japanese-5k-steps` folder contain?

![Screenshot 2024-12-10 191242](https://github.com/user-attachments/assets/77989588-9d53-487b-826b-b3a74e57f87b)
