### ISSUE TITLE
Error when I try to download Purfview's Faster Whisper XXXL 

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#9085]
This is the message I get when I try to download Audio to text (whisper)/ Purfview's Faster Whisper XXXL. When the download reaches 100%, I get this message window and nothing has been saved. 

![Screenshot_1](https://github.com/user-attachments/assets/a246a404-d9ab-441e-89b3-ca4230959f64)

**Comment by Purfview** [comment]
Download latest beta, it's fixed there. Beta "269"

**Comment by Cyberyoda1411** [comment]
Thank you, it works. I regularly update every beta version, without exception, but this, the last one, I didn't. Good job.
