### ISSUE TITLE
Player plays too fast or doesn't start at all (it is dead)

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#9086]
I have Windows 10, I use the Direct Show video engine, and LAV filters codec. 

In this beta version 4.0.8 beta 269 and a couple of versions before, my player when I start editing has superspeed, the voices of the people in the video are like babies, and the speed is at least 4x faster/or it won't start, video is dead. It is not always present, but I often must restart SE program to get either video to start (it doesn't respond), or it is too fast. 

Do I do something wrong, or there is a bug in the last 3 or 4 beta versions? 
UPDATE:
This last version 269 has this problem in 100% of cases. I must go to the speed of reproduction, to reduce it to 90%, then to bring it back to 100%, or it will be super super speed reproduction of video.

**Comment by niksedk** [comment]
I've not really change the Quarts/directshow code in many years... try with an older version of lav-filters
