### ISSUE TITLE
Can I remove the [Maximum number of bytes per server call] limit in [Automatic Translation]?

### ISSUE THREAD

**Issue by despairTK** [SubtitleEdit/subtitleedit#9089]
Currently, the maximum value that can be filled in is 10,000. Can this limitation be lifted so that a larger value can be filled in?
![83172651-a33c-4a9c-9df4-14ab48c99a5b](https://github.com/user-attachments/assets/76c44087-9f2c-4d08-8219-485795557fbe)

**Comment by niksedk** [comment]
Sure, now allows up to 128.000 bytes.

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
