### ISSUE TITLE
Missing Format: from [Events] when converting .vtt to .ass

### ISSUE THREAD

**Issue by aaron-meyers** [SubtitleEdit/subtitleedit#9092]
Trying .vtt to .ass conversion again using SubtitleEdit /convert CLI after #8707 was closed, it looks like there is still an issue.
Specifically, the Format: directive is missing in the [Events] section which causes some tools like alass to consider the .ass file to be invalid. Note that the [V4+ Styles] section has a Format: directive but the [Events] section does not.

For reference, I'm still running a similar command to what I mentioned in #8707 :
subtitleedit /convert .\subtitles\00-initial\orange-days-s01e01.ja.vtt AdvancedSubStationAlpha /outputFolder:subtitles\10-clean /overwrite

Let me know if you need any more info, thanks!

**Comment by niksedk** [comment]
Works fine for me using latest beta...
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

**Comment by aaron-meyers** [comment]
I just checked and both the 4.0.8 release and the latest beta generate the same .ass file which is missing the "Format: " line under the [Events] section. If I open my .vtt file in the SubtitleEdit UI and save as .ass file the Format: line is present.

Preview of .ass file generated by SubtitleEdit /convert from .vtt (missing Format: line under [Events]):
```
[Script Info]
; This is an Advanced Sub Station Alpha v4+ script.
Title: 
ScriptType: v4.00+
PlayDepth: 0
ScaledBorderAndShadow: Yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,10,1

[Events]
Dialogue: 0,0:00:07.64,0:00:10.91,Default,,0,0,0,,（櫂(かい)）お前も好きだね 大丈夫か？\N落ちんなよ
Dialogue: 1,0:00:10.98,0:00:11.81,Default,,0,0,0,,（啓太(けいた)）よいしょ！
Dialogue: 2,0:00:11.88,0:00:13.75,Default,,0,0,0,,（櫂）取れた？\N（啓太）ゲッチューです
```

Preview of .ass file created when opening .vtt file in SubtitleEdit UI and save as .ass (note the Format: line under [Events]):
```
[Script Info]
; This is an Advanced Sub Station Alpha v4+ script.
Title: 
ScriptType: v4.00+
PlayDepth: 0
ScaledBorderAndShadow: Yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H0000FFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:07.64,0:00:10.91,Default,,0,0,0,,（櫂(かい)）お前も好きだね 大丈夫か？\N落ちんなよ
Dialogue: 1,0:00:10.98,0:00:11.81,Default,,0,0,0,,（啓太(けいた)）よいしょ！
Dialogue: 2,0:00:11.88,0:00:13.75,Default,,0,0,0,,（櫂）取れた？\N（啓太）ゲッチューです
```

Hope this helps clarify!

**Comment by niksedk** [comment]
Thx for explaining - I've tied to add the "Event Format" line in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

Let me know if it works for you.

**Comment by aaron-meyers** [comment]
Yes, that worked. Thanks!

**Comment by aaron-meyers** [comment]
Yes, that worked. Thanks!

**Comment by niksedk** [comment]
Thx for reporting and testing :)
