### ISSUE TITLE
ffprobe fails extracting timecodes for beautifying if video format is HDR10(+)

### ISSUE THREAD

**Issue by warrentc3** [SubtitleEdit/subtitleedit#9097]
using the OOTB command, HDR10 videos fail to extract timecodes...
"`-select_streams v -show_frames -show_entries frame=pkt_dts_time -of csv`"

tried to repro locally and it appears side_data comes along with the frame dts.
`frame,0.000000,Mastering display metadata,34000/50000,16000/50000,13250/50000,34500/50000,7500/50000,3000/50000,15635/50000,16450/50000,50/10000,10000000/10000,Content light level metadata,2251,342,HDR Dynamic Metadata SMPTE2094-40 (HDR10+),1,1,500/1,17102/100000,13917/100000,13548/100000,51/100000,9,1,0/100000,5,6092/100000,10,100/100000,25,4/100000,50,12/100000,75,32/100000,90,134/100000,95,247/100000,99,6038/100000,0/1000,63/4095,76/4095,9,120/1023,244/1023,365/1023,483/1023,596/1023,706/1023,822/1023,908/1023,936/1023
frame,0.042000,Mastering display metadata,34000/50000,16000/50000,13250/50000,34500/50000,7500/50000,3000/50000,15635/50000,16450/50000,50/10000,10000000/10000,Content light level metadata,2251,342,HDR Dynamic Metadata SMPTE2094-40 (HDR10+),1,1,500/1,17102/100000,13917/100000,13548/100000,51/100000,9,1,0/100000,5,6092/100000,10,100/100000,25,4/100000,50,12/100000,75,32/100000,90,134/100000,95,247/100000,99,6038/100000,0/1000,63/4095,76/4095,9,120/1023,244/1023,365/1023,483/1023,596/1023,706/1023,822/1023,908/1023,936/1023`

adding this to the cmd at least dropped the metadata 
"`-select_streams v -show_frames -show_entries frame=pkt_dts_time:side_data= -of csv`"

`
frame,0.000000,
frame,0.042000,
`
but it does leave a superfluous comma at the end of each line.

**Comment by niksedk** [comment]
Thx for the info :)
Latest source/beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
Let me know how it works.
