### ISSUE TITLE
Two (connected?) issues in recent beta

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#9099]
So, I think these might have to do with this:
https://github.com/SubtitleEdit/subtitleedit/issues/9082
Since I didn't experience them in the beta immediately before the one that incorporated it. I'm on 269 now.
The first thing is that if SE is opened and it restores the previously open subtitle, and it's in translator mode, right away it appears to be modified (there's an asterisk in the window title). This didn't happen previously.
The second thing is that it seems like if I perform a `Column, paste` action, I can't undo it. And once (granted, I was trying to paste a large amount of text) SE froze altogether and I had to kill the task and restart it.

**Comment by niksedk** [comment]
Hm, I cannot re-create this...

**Comment by darnn** [comment]
The column paste issue seems to only be triggered in specific circumstances which I can't figure out. The first one, though, can be reproduced using these:
[desync1216translation.srt.txt](https://github.com/user-attachments/files/18153750/desync1216translation.srt.txt)
[desync1216original.srt.txt](https://github.com/user-attachments/files/18153752/desync1216original.srt.txt)

Open them as the original and translation, then close them (i.e. create a new file), and then open them again using `File`->`Reopen`.

**Comment by niksedk** [comment]
Hopefully fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
