### ISSUE TITLE
AutoTranslateSettings form size for easier custom prompts

### ISSUE THREAD

**Issue by gjaskula** [SubtitleEdit/subtitleedit#9101]
Issue: The AutoTranslateSettings form contains a listview (in advanced settings) for the prompt to be used by an LLM (ollama), modifying the standard prompt with a richer prompt is useful to yield different translation results, the current listview is too small and not resizable. 

Solution proposed: modify the form to be resizable and/or change the minimum size.
 The easy fix is to change the current FormBorderStyle to FormBorderStyle.Sizable

**Comment by niksedk** [comment]
Sure, now resizable + a little larger: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip
