### ISSUE TITLE
An Error Message

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#9110]
![image](https://github.com/user-attachments/assets/9051ffce-15bc-4ded-bb31-e3a7f9713651)
When pressing the shortcut "**Split line at cursor/video position**" while the cursor is at the end of the paragraph with space character(s) ahead. Tested in Beta 291.

**Comment by niksedk** [comment]
Thx :)
Should be fixed in 4.0.9 - https://github.com/SubtitleEdit/subtitleedit/releases
