### ISSUE TITLE
Fix common errors (default configuration in batch mode)

### ISSUE THREAD

**Issue by agmovi** [SubtitleEdit/subtitleedit#9115]
I would like to know how I can control the configuration of common errors in the batch version, since I do not know what is being repaired when using this mode, is there any option within the program for that?

**Comment by niksedk** [comment]
Click on the settings button.

**Comment by agmovi** [comment]
In batch mode there is no configuration option.
![2024-12-24_02-41-48](https://github.com/user-attachments/assets/db6763b9-72a1-46ee-8c7d-deadf7caeb6b)
But forget it, I'm not going to continue

**Comment by niksedk** [comment]
If you focus an option (e.g. click on "Fix common errors"), settings will appear to the right:

![image](https://github.com/user-attachments/assets/ac423c57-0686-4401-966b-bf5034ffc0da)

**Comment by agmovi** [comment]
It's not very intuitive; if I don't ask, I never find out. It's almost like an Easter egg...
![2024-12-25_03-23-54](https://github.com/user-attachments/assets/8cb6275c-3482-4671-aec6-d5fedd904627)
I appreciate your answer!
