### ISSUE TITLE
An application error occurred in SE 4.0.9.0 - 64-bit - Microsoft Windows NT - 10.0.22631.0.

### ISSUE THREAD

**Issue by briandunker** [SubtitleEdit/subtitleedit#9121]
Error message: El índice estaba fuera del intervalo. Debe ser un valor no negativo e inferior al tamaño de la colección.
Nombre del parámetro: index 

Stack Trace:
en System.Throw Helper ETCETERA ETCETERA
en Nikse.Subtitle Edit ETCETERA ETCETERA
![Screenshot_1](https://github.com/user-attachments/assets/64b4f344-2fb2-4755-bbd5-1de33e45aec2)

**Comment by niksedk** [comment]
It sounds like a name files is broken... try to install, delete all SE files (incl. dictionary files)., reinstall
