### ISSUE TITLE
[Feature Request]Whisper ASR API Support

### ISSUE THREAD

**Issue by ryfon** [SubtitleEdit/subtitleedit#9124]
It would be nice to offload STT/Translation to dedicated hardware, added language detection is nice as well.

Documentation can be found here:
https://ahmetoner.com/whisper-asr-webservice/endpoints/##Automatic-Speech-recognition-service-/asr
[Whisper Asr Webservice - Swagger UI.pdf](https://github.com/user-attachments/files/18219650/Whisper.Asr.Webservice.-.Swagger.UI.pdf)

**Comment by niksedk** [comment]
SE already has this... and more Whisper engines.

**Comment by ryfon** [comment]
There is no API support all i can find are local whisper engines

**Comment by niksedk** [comment]
It's just using "Whisper CPP"

**Comment by ryfon** [comment]
Yes, but the point is its running on remote hardware, instead of needing expensive high VRAM cards locally for each running instance of SE.
