### ISSUE TITLE
Remove Tags?

### ISSUE THREAD

**Issue by hellcezar** [SubtitleEdit/subtitleedit#9128]
Hello everyone, pls help me, when i do Audio->text ( Whisper ), its puts tags <br />. How to disable this function? i dont need this tags

**Comment by niksedk** [comment]
You can easily remove tags in SE.

**Comment by hellcezar** [comment]
> You can easily remove tags in SE.

How exactly? For example, I have 500 lines, I don’t want to manually delete it on each line

**Comment by niksedk** [comment]
It depends on the tags...

Hearing impaired tags can be removed via Tools - Remove text for HI

Italic/color/bold/alignment tags can removed via right-clicking in the list view, and remove tags...

**Comment by hellcezar** [comment]
> It depends on the tags...
> 
> Hearing impaired tags can be removed via Tools - Remove text for HI
> 
> Italic/color/bold/alignment tags can removed via right-clicking in the list view, and remove tags...

there is no "Remove tag"
![{8D2EC5B6-FED0-4B4C-8FDA-A26DC26D180C}](https://github.com/user-attachments/assets/06c33a0a-c867-4ec9-9ec0-b125c579bb80)
I also found in the settings "Show line breaks in list as <br />", but I need to completely remove this tag, because I use this SRT file for Sonitranslate to dub videos and Sonitranslate presents this tag as a dot and breaks the voiceover

**Comment by niksedk** [comment]
What tags do you have?

**Comment by hellcezar** [comment]
The line break tag "<br />", when dubbed, it is transformed into "." - the dot symbol, that's why I want to disable the function of this tag

**Comment by hellcezar** [comment]
> What tags do you have?

oh, excuse me, I just now noticed that when I wrote about this tag, GitHub itself transformed it and made it a line break

**Comment by niksedk** [comment]
You can select all lines in the list view, and click on the "unbreak" button

**Comment by hellcezar** [comment]
> You can select all lines in the list view, and click on the "unbreak" button

Sorry, but im still cant find unbreak option.
![{1465D1CF-8677-40F8-8641-5CE319586CDC}](https://github.com/user-attachments/assets/f74bc0f3-7f23-4992-8903-d3aaee3c944e)
as you can see this tags

**Comment by niksedk** [comment]
It a button... below the "Auto br" button

**Comment by hellcezar** [comment]
There is no "auto br" ? =)
i found only here settings, but it cant be blank
![image](https://github.com/user-attachments/assets/76526b2f-5b86-4a0b-a2a7-3676dcb1f448)

**Comment by GrampaWildWilly** [comment]
I have my video controls undocked so your layout probably doesn't look exactly like this, but . . .

![#01](https://github.com/user-attachments/assets/50522109-1bab-4022-92c4-72c411cb8721)

In the main SE window -- not in any subordinate dialog, not in any popup menu -- in the main window itself, click Ctrl+a.  That will highlight all the lines.  Then click the button.  THE BUTTON.  There's a button to the right of the text entry box.  That's what my arrows are pointing at.  Click the `Unbreak` button right above the `Auto br` button.

**Comment by hellcezar** [comment]
> I have my video controls undocked so your layout probably doesn't look exactly like this, but . . .
> 
> ![#01](https://private-user-images.githubusercontent.com/75588964/398155053-50522109-1bab-4022-92c4-72c411cb8721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTY0MTgsIm5iZiI6MTczNDk1NjExOCwicGF0aCI6Ii83NTU4ODk2NC8zOTgxNTUwNTMtNTA1MjIxMDktMWJhYi00MDIyLTkyYzQtNzJjNDExY2I4NzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEyMTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MzAzMjBlMjg5YzUzNTZlZTZmZGQ5YTFlYzRlZGIyM2U3MWZmYjUyMDQxZGFjNzY1NjRhZjMyNDMzYmQ1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vkg2KWpSe3jBAHmyY1UpUCCPJMgqmz6vG82n6aNgnTQ)
> 
> In the main SE window -- not in any subordinate dialog, not in any popup menu -- in the main window itself, click Ctrl+a. That will highlight all the lines. Then click the button. THE BUTTON. There's a button to the right of the text entry box. That's what my arrows are pointing at. Click the `Unbreak` button right above the `Auto br` button.

God bless you!

**Comment by GrampaWildWilly** [comment]
By the way, I have a different setting:

![#02](https://github.com/user-attachments/assets/b06bc1f1-95d5-4321-ab42-5baf93a46a00)

I wonder what happens if you just delete whatever it says in that setting.  Try that.  Maybe that will make a difference for you.

**Comment by hellcezar** [comment]
> By the way, I have a different setting:
> 
> ![#02](https://private-user-images.githubusercontent.com/75588964/398157187-b06bc1f1-95d5-4321-ab42-5baf93a46a00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTY3MDgsIm5iZiI6MTczNDk1NjQwOCwicGF0aCI6Ii83NTU4ODk2NC8zOTgxNTcxODctYjA2YmMxZjEtOTVkNS00MzIxLWFiNDItNWJhZjkzYTQ2YTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEyMjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZjA3YmRjZTBiMjFjMGEwNjhjNDJhM2EwOGJjM2QyNWJkNGZlNDI1ZmI4OGY5NTkzZWZhZmM2NzRiMzFmOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jinUp6MYnrLloegPvGqMAQQYMBS6tDeRnRLkMxKR07s)
> 
> I wonder what happens if you just delete whatever it says in that setting. Try that. Maybe that will make a difference for you.

it cant be blank, this are need any character. But cant be "space" button

**Comment by GrampaWildWilly** [comment]
Right.  I just tried removing the value completely.  Not blank, but empty.  It let me click OK but when I reopened the dialog, it had changed to `<br />` same as what you have.  I put it back to `<br>`.  I guess if there's line breaks, you have to have some sort of placeholder.  That seems like the logical thing to do.  In any case, did the `Unbreak` button solve your problem?

**Comment by hellcezar** [comment]
> Right. I just tried removing the value completely. Not blank, but empty. It let me click OK but when I reopened the dialog, it had changed to `<br />` same as what you have. I put it back to `<br>`. I guess if there's line breaks, you have to have some sort of placeholder. That seems like the logical thing to do. In any case, did the `Unbreak` button solve your problem?

yea, its solved! Thanks alot
