### ISSUE TITLE
Canceling the OCR screen results in a crash

### ISSUE THREAD

**Issue by xZise** [SubtitleEdit/subtitleedit#913]
I was checking subtitles using the OCR functionality (without actually parsing them) so after I've checked them I clicked "cancel" and an error occurred in version 3.4.6:

```
Message: Ausnahme von HRESULT: 0x80040266
Source: SubtitleEdit

Stack Trace: 
   bei QuartzTypeLib.<266615b5-7894-489d-9fff-ca185c768d97>IMediaControl.RenderFile(String strFilename)
   bei Nikse.SubtitleEdit.Logic.VideoPlayers.QuartsPlayer.Initialize(Control ownerControl, String videoFileName, EventHandler onVideoLoaded, EventHandler onVideoEnded)
   bei Nikse.SubtitleEdit.Logic.Utilities.InitializeVideoPlayerAndContainer(String fileName, VideoInfo videoInfo, VideoPlayerContainer videoPlayerContainer, EventHandler onVideoLoaded, EventHandler onVideoEnded)
```

(Props to Microsoft to translate stacktraces -.- )

I had a similar error in 3.3.1 and after acknowledging that message it crashed completely but it appears 3.4.6 doesn't crash immediately.

I'm using it on Windows 7 x64 if that is of any help and reading the PGS subtitles from a MKV file.

**Comment by diomed** [comment]
@ivandrofly  is this being fixed?

**Comment by niksedk** [comment]
It's a codec related crash. I cannot re-create it. Can you @diomed ?

**Comment by diomed** [comment]
ah, no.. I can't. sorry.

**Comment by niksedk** [comment]
Cannot re-create this... please supply a file is this is still a problem.
