### ISSUE TITLE
Batch convert fails to remove formatting tags

### ISSUE THREAD

**Issue by mkvTest** [SubtitleEdit/subtitleedit#9133]
Under "Batch convert", with Output "Save in source file folder" selected and "Overwrite files" check-box ticked, and select only the item "Remove formatting tags" in the Convert option, the program fails to remove the formatting tags despite the files have Status marked converted.

**Comment by Minherre** [comment]
When you chose/checked "Remove formatting tags", did you Stand ON it, so that WHAT to Remove shows on the Right Side?!
On the Right Side one can then chose to Remove 'All', 'Bold', 'italics' and so on.

**Comment by niksedk** [comment]
Work fine... if you pick the correct settings and are talking about formatting tags like italic, alignment or color.

![image](https://github.com/user-attachments/assets/a203a6b4-df01-4874-be5c-f4fd9e14ae3b)
