### ISSUE TITLE
How to download external Whisper models not available in the subtitle edit?

### ISSUE THREAD

**Issue by Morganbsl** [SubtitleEdit/subtitleedit#9135]
I'm working on a project that requires using the Whisper model for Arabic speech-to-text tasks. I've found a fine-tuned model (`mohmdsh/whisper-small-arabic-finetuned-on-halabi_dataset`) that seems to be more accurate for my specific use case. However, this model is not available in the main Whisper subtitle edit.

I was wondering if there's a way to download this model from its original source (Hugging Face) and use it in my project instead of relying on the main whisper.

Thank you for your help!

**Comment by Morganbsl** [comment]
@niksedk please can you reply me?!!

**Comment by niksedk** [comment]
Make a new folder with the required files... look at the content of the existing models.

**Comment by Morganbsl** [comment]
![My Video](https://github.com/user-attachments/assets/df480b4f-2a8c-4204-9933-f6af3605921b)

I recreated the folder structure with the exact same files as the original models, but still can't find it in Subtitle Edit. It seems like there's something specific that needs to be done for SE to recognize it

![Screenshot 2024-12-28 205052](https://github.com/user-attachments/assets/19b40ef9-afd1-4f0a-bd8c-1bf45c6e35b1)

**Comment by Purfview** [comment]
That model is for Whisper, not for Faster-Whisper
