### ISSUE TITLE
Faster-Whisper-XXL CUDA issue

### ISSUE THREAD

**Issue by nielka98** [SubtitleEdit/subtitleedit#9143]
Okay, I've spent several hours struggling with SE. What's going on? I don't understand, I totally don't understand. Can someone help me? Apparently, it's about CUDA, but I have the latest drivers. I already deleted the Purfview-Whisper-Faster folder, and it turns out it's essential for everything to work. I keep getting an error saying something is wrong with CUDA. Can someone please help me? I really don't understand what's going on. I'm attaching the log.
[whisper_log.txt](https://github.com/user-attachments/files/18266189/whisper_log.txt)

**Comment by niksedk** [comment]
It says `RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version`

Try updating your gfx card driver: http://www.nvidia.com/drivers

**Comment by nielka98** [comment]
Nikola a ja mam takie pytanie A to nie chodzi o te pliki które trzeba pobrać od znaczy o to Purfview
w sensie o to:https://github.com/Purfview/whisper-standalone-win/releases/tag/libs

**Comment by niksedk** [comment]
> Nikola and I have such a question And it's not about the files that you have to download from I mean Purfview I mean this:https://github.com/Purfview/whisper-standalone-win/releases/tag/libs

??

**Comment by nielka98** [comment]
the problem was solved
