### ISSUE TITLE
Cannot hit Enter key in FCE window

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#9148]
![QQ20241229-154025](https://github.com/user-attachments/assets/125b44f9-b61f-475f-9ed2-d469efab9bf8)

When trying to hit Enter when the textbox is focused, it either doesn't work or the window closes, thus we cannot do that in this way.

**Comment by niksedk** [comment]
What SE version are you using?

**Comment by LeonCheung** [comment]
> What SE version are you using?

Latest beta 201.

**Comment by niksedk** [comment]
4.0.10 ?

**Comment by LeonCheung** [comment]
Oops... it seems I just downloaded the wrong one Sorry for the false alarm, no problem now. 😂  Just one more thing, is there a way to make the textbox width adjustable? As shown in the image below, the 2nd line is not fully displayed: ![image](https://github.com/user-attachments/assets/fdf764af-e20f-4de1-b343-f3e69df43fdd)

**Comment by niksedk** [comment]
You can use the splitter in the main window to resize the text box:
![image](https://github.com/user-attachments/assets/fd68bba8-30ce-44c3-b666-8dfd90de392d)



I have tried to allow for a custom height for the video player preview sub box - use the "VideoPlayerPreviewBoxHeight" in Settings.xml
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.10/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Thanks for that but I guess it currently works a bit add:

![image](https://github.com/user-attachments/assets/3e4c8d86-13a0-4e0a-9f49-0750734aeeb1)

The value is 127 here, btw.

**Comment by niksedk** [comment]
Hm, does this work better? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.10/SubtitleEditBeta.zip

If not, please attach your subtitle file.

**Comment by LeonCheung** [comment]
Not it works great! Thank you!
