### ISSUE TITLE
BUG: Netflix quality check - Numbers in sentence

### ISSUE THREAD

**Issue by senna23** [SubtitleEdit/subtitleedit#9150]
![image](https://github.com/user-attachments/assets/8f3c8b53-11a8-4bef-8aeb-4cf1653c32ab)

**Comment by niksedk** [comment]
Thx - hopefully fixed now in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.10/SubtitleEditBeta.zip
(portable version, unzip to something like "C:\Tools\SE")
