### ISSUE TITLE
How to set another audio (lang.) ?

### ISSUE THREAD

**Issue by Draxler** [SubtitleEdit/subtitleedit#921]
Win7/Latest Subtitleedit 3.4.6 Build 544
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Is it posible to set another audio (lang) in video when played in Subtitleedit app? 
It happens i get this video from Russian site and they set their language (Russian) as primary language and English (Original audio) as secundary language in this video file. Now, when i open this video file with >> Subtitleedit << i get Russian audio playing and i couldn't find an option to change audio between these 2 languages. Is such option available in this app or not ? If option is available, i would very much appreciated if someone would tell me where to look and how to do it.
Regards

**Comment by niksedk** [comment]
Hi, try switching to VLC video player (be sure to install VLC 64-bit if you running a 64-bit os) which should give the ability to switch language in the "Video" menu.

**Comment by xylographe** [comment]
With LAV-filters (K-Lite Codec Pack) you can change subtitle/audio/video streams in the system tray, by right-clicking the white LAV icon. You can set preferred languages for subtitles and audio, to make LAV choose the ‘correct’ streams automatically.

**Comment by Draxler** [comment]
Thank you guys. I realy appreciated the suggestions.
